### ISSUE TITLE
SHAccountValidate.ps1 issues when validating Hybrid accounts

### ISSUE THREAD

**Issue by mohanse** [MicrosoftDocs/windows-itpro-docs#100]
$strAlias and $strLyncIdentity  variables are used to validate PasswordNeverExpires and Skype for Business account. The value is assigned from $mailbox.Alias. The alias is not a UPN , therefore the validation fails although the account is configured correctly. 

I suggest we get the value (assign the value) from 

$mailbox.UserPrincipalName to validate PasswordNeverExpires settings 

$mailbox.UserPrincipalName  or $mailbox.WindowsEmailAddress to validate Skype account setup

Thanks.

**Comment by jdeckerMS** [comment]
Thanks for providing this information. I'll pass it on to the engineering team to investigate if changes to the topic are needed. Sorry that I can't provide an estimate for when any changes will be made.

**Comment by jdeckerms** [comment]
I'm still working on getting a resolution for this issue.

**Comment by jdeckerms** [comment]
Thanks for your patience - the engineering team is focused on updates to the product, so it was a bit of a challenge to get their validation. I finally got their go-ahead to make your suggested changes, and the topic should be updated today. Thank you for your feedback!
