### ISSUE TITLE
out of context

### ISSUE THREAD

**Issue by lvazuka** [MicrosoftDocs/windows-itpro-docs#1000]
what poor article, no context at all... a bad code is written with many assumptions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e58aab9-1c17-2a85-1c7b-761366b67953
* Version Independent ID: 933993a9-3b19-72b1-586b-6360a7e7215a
* Content: [NFC-based device provisioning (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/mobile-devices/provisioning-nfc)
* Content Source: [windows/configuration/mobile-devices/provisioning-nfc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/mobile-devices/provisioning-nfc.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
Hi @lvazuka I'm sorry the topic didn't provide the information you were looking for.
