### ISSUE TITLE
Blocking errors on page: "Customize the Taskbar on Windows 11"

### ISSUE THREAD

**Issue by EricCote** [MicrosoftDocs/windows-itpro-docs#10004]
Some of the XML file samples provided on the page "Customize the Taskbar on Windows 11" do not work.  Some of these are blocking errors.  Here is what you need to do to solve the problem.

Permalink of the page with errors:
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/3ac31580cd5ff81b5ee4f52d26a35ec98e52de32/windows/configuration/customize-taskbar-windows-11.md

Lines 64-67 look like this:

```xml
<taskbar:TaskbarPinList>
  <taskbar:UWA AppUserModelID="Microsoft.Windows.Explorer"/>
  <taskbar:DesktopApp DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\Windows System\Command Prompt.lnk"/>
</taskbar:TaskbarPinList>
```

If you try the code (I did), you will get no icons on the taskbar.  To repair the sample, you need to type the following:

```xml
<taskbar:TaskbarPinList>
  <taskbar:DesktopApp DesktopApplicationID="Microsoft.Windows.Explorer" />
  <taskbar:DesktopApp DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\System Tools\Command Prompt.lnk" />
</taskbar:TaskbarPinList>
```

Line 65: Explorer is not a Store app, it's a desktop app that needs to be called with a Desktop application ID.

Line 66:
This error is bizarre:  in Window 11, the folder that contains the link is still **System Tools**, even though  *File Explorer* will display this particular folder with the 'Windows System' alias. (Command line tools like Powershell, cmd and bash still all see **System Tools**. And there's no 'Windows System' in sight)

> **UPDATE**  : The folder name is `System Tools`.  The localized display string that appears in the shell is "Windows System" when using `en-US` locale. This string changes when using other display languages.  Paths must use the folder name, not the localized display name. 

---

Lines 104-109:
```xml
<taskbar:TaskbarPinList >
  <taskbar:UWA AppUserModelID="MSEdge"/>
  <taskbar:UWA AppUserModelID="Microsoft.Windows.Explorer"/>
  <taskbar:UWA AppUserModelID="Microsoft.Office.Word_8wekyb3d8bbwe!microsoft.word" />
  <taskbar:DesktopApp DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\Windows System\Command Prompt.lnk"/>
</taskbar:TaskbarPinList>
```

This needs to be changed to:
```xml
<taskbar:TaskbarPinList >
  <taskbar:DesktopApp DesktopApplicationID="MSEdge"/>
  <taskbar:DesktopApp DesktopApplicationID="Microsoft.Windows.Explorer"/>
  <taskbar:DesktopApp DesktopApplicationID="Microsoft.Office.WINWORD.EXE.15" />
  <taskbar:DesktopApp DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\System Tools\Command Prompt.lnk"/>
</taskbar:TaskbarPinList>
```

Explanation:  
* Edge is a Desktop app, not a store app.
* Explorer is a desktop app, not a store app.
* In most organizations, Word is a managed desktop app.  Very few businesses will deploy the store version of the app.  Even the Office team recommends deploying the desktop version: https://docs.microsoft.com/en-us/deployoffice/overview-office-deployment-tool
* The command prompt is under `System Tools`, not `Windows System`. 

---

Lines 112-117:
```xml
<taskbar:TaskbarPinList>
  <taskbar:UWA AppUserModelID="Microsoft.Windows.Explorer"/>
  <taskbar:UWA AppUserModelID="Microsoft.Office.Word_8wekyb3d8bbwe!microsoft.word" />
  <taskbar:UWA AppUserModelID="Microsoft.Office.Excel_8wekyb3d8bbwe!microsoft.excel" />
  <taskbar:DesktopApp DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\Windows System\Command Prompt.lnk"/>
</taskbar:TaskbarPinList>
```

Should instead show:
```xml
<taskbar:TaskbarPinList>
  <taskbar:DesktopApp DesktopApplicationID="Microsoft.Windows.Explorer"/>
  <taskbar:DesktopApp DesktopApplicationID="Microsoft.Office.WINWORD.EXE.15" />
  <taskbar:DesktopApp DesktopApplicationID="Microsoft.Office.EXCEL.EXE.15" />
  <taskbar:UWA AppUserModelID="Microsoft.WindowsTerminal_8wekyb3d8bbwe!App" />
</taskbar:TaskbarPinList>
```
Explanation:
* Explorer is a desktop app, not a store app.
* Word and Excel are desktop apps (if they follow the recommended way to deploy)
*  I replaced the command prompt with the new 'windows terminal' which is included with Win11. 

---

Lines 120-124:
```xml
<taskbar:TaskbarPinList>
  <taskbar:UWA AppUserModelID="Microsoft.Windows.Explorer"/>
  <taskbar:UWA AppUserModelID="Microsoft.Office.Word_8wekyb3d8bbwe!microsoft.word" />
  <taskbar:DesktopApp DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\Windows System\Command Prompt.lnk"/>
</taskbar:TaskbarPinList>
```

Should be instead:
```xml
<taskbar:TaskbarPinList>
  <taskbar:DesktopApp DesktopApplicationID="Microsoft.Windows.Explorer"/>
  <taskbar:DesktopApp DesktopApplicationID="Microsoft.Office.WINWORD.EXE.15" />
  <taskbar:UWA AppUserModelID="Microsoft.WindowsTerminal_8wekyb3d8bbwe!App" />
</taskbar:TaskbarPinList>
```

Explanation:
* Explorer is a desktop app, not a store app.
* Word is a desktop app (it's the recommended way to deploy in businesses)
* I replaced the command prompt with the new 'Windows Terminal' which is included with Win11. 

---

The original document was authored by @MandiOhlinger .  Thanks for all the great work you put in. Bravo to you and your team!

**Comment by EricCote** [comment]
I solved the "System Tools" -> "Windows System" alias mystery.

"Windows System" is the English-US localized string for Shell and Start menu items. This string changes when you localize Windows with different languages. 

The underneath folder name always stays "System Tools", only the Shell (and File Explorer) is impacted. 

This is the case since Windows Vista.

**Comment by MandiOhlinger** [comment]
Fixed in https://github.com/MicrosoftDocs/windows-docs-pr/pull/5777. This GitHub issue can be closed.

**Comment by EricCote** [comment]
I can't consult the pull request. I get a 404. Would that be an internal (non-public) project?  

I can't validate that the fix is done.

**Comment by MandiOhlinger** [comment]
@EricCote Correct. That's an internal MS only link. I added it just for my reference, just in case. The changes are merged, and should go live later today/tomorrow morning PST.

**Comment by EricCote** [comment]
Good work!
