### ISSUE TITLE
Article littered with errors and missing steps

### ISSUE THREAD

**Issue by ProactiveServices** [MicrosoftDocs/windows-itpro-docs#10002]
This article is littered with missing steps and erroneous or outdated advice. It needs to be reviewed holistically by an expert.
A non-exhaustive example: Method 3, steps 3 and 4 both ask the user to use `/bootrec /rebuildbcd`, one without a backup, one using two backup methods, but with spurious backslashes in the commands, and the sample output lists a different drive letter than the commands (D,C). The steps and possible outputs in method 3 are also in the wrong order.

Method 4 lists two `attrib` commands without the filespec listed, and says to "copy and paste" the bootmgr file, whereas it should list `copy` commands.

Method 5 is essentially useless in modern-day Windows installs. It should be relegated to a hidden or footnote section, or be moved out to its own article.

Section "Clean Boot", command `SFC /Scannow /OffBootDir=C:\ /OffWinDir=E:\Windows` has mismatched drive letters. The final section which says to `Copy all the hives from the Regback folder, paste them in the Config folder` is likely irrelevant in modern day, but if not could result in data loss as all of the existing hives are over-written without the user backing them up first.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc264df-cbd1-ac1f-3926-841fcab7dc31
* Version Independent ID: 67c2aea4-0d28-3d8e-e935-8af05291c94e
* Content: [Advanced troubleshooting for Windows boot problems - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/advanced-troubleshooting-boot-problems)
* Content Source: [windows/client-management/advanced-troubleshooting-boot-problems.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/advanced-troubleshooting-boot-problems.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by MaratMussabekov** [comment]
Hello @ProactiveServices ,
please have a look at https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10219
**Method 3, steps 3 and 4 both ask the user to use /bootrec /rebuildbcd, one without a backup, one using two backup methods, but with spurious backslashes in the commands, and the sample output lists a different drive letter than the commands (D,C). The steps and possible outputs in method 3 are also in the wrong order.** - addressed in #10219 

**Method 4 lists two attrib commands without the filespec listed, and says to "copy and paste" the bootmgr file, whereas it should list copy commands.** - one command is for System Reserved partition, the second is for System drive

**Method 5 is essentially useless in modern-day Windows installs. It should be relegated to a hidden or footnote section, or be moved out to its own article.** - it has "note" section that describes that it is outdated method

**Section "Clean Boot", command SFC /Scannow /OffBootDir=C:\ /OffWinDir=E:\Windows has mismatched drive letters.** - addressed in #10219 

**The final section which says to Copy all the hives from the Regback folder, paste them in the Config folder is likely irrelevant in modern day, but if not could result in data loss as all of the existing hives are over-written without the user backing them up first.** - it has "note" section that describes that it is outdated step.

Thank you
