### ISSUE TITLE
DedicatedDumpFile, talks a lot about it, doesn't tell you what the registry key is to set it.

### ISSUE THREAD

**Issue by jeffstokes72** [MicrosoftDocs/windows-itpro-docs#10029]
[Enter feedback here]
DedicatedDumpFile, talks a lot about it, doesn't tell you what the registry key is to set it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b0674a-7bd1-6f30-9e7a-d258ab559138
* Version Independent ID: c1d5e93a-42cb-d29d-bb91-9c38d3a8647f
* Content: [How to determine the appropriate page file size for 64-bit versions of Windows - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/determine-appropriate-page-file-size)
* Content Source: [windows/client-management/determine-appropriate-page-file-size.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/determine-appropriate-page-file-size.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by jeffstokes72** [comment]
https://docs.microsoft.com/en-us/windows/client-management/determine-appropriate-page-file-size#dedicated-dump-files

How?!

**Comment by MaratMussabekov** [comment]
Hello, it is possible using GUI as well, for example - https://docs.microsoft.com/en-us/troubleshoot/windows-server/performance/memory-dump-file-options#configure-the-dump-type
I added PR with this link
Thank you
