### ISSUE TITLE
Importans business apps out of "Trust apps with good reputation" list

### ISSUE THREAD

**Issue by Rutikhal** [MicrosoftDocs/windows-itpro-docs#1002]
Hello
I have checked WDAC with test env and see that even most important apps/drivers that we are using every day are not in the "trusted" list  by Microsoft . How could I  implement this WDAC solution in my company in that case? How my company and other customer could add needed application ASAP in that list to not be locked by WDAC? //Alexander

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80b64219-4814-f414-e5fb-4bfa9be9a55f
* Version Independent ID: b1b2f9e2-912b-80e0-bee7-be41eaf9690f
* Content: [Deploy Windows Defender Application Control (WDAC) policies by using Microsoft Intune (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/deploy-windows-defender-application-control-policies-using-intune#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/deploy-windows-defender-application-control-policies-using-intune.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/deploy-windows-defender-application-control-policies-using-intune.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@theplaz currently Intune only allows selecting trust for Window components+WHQL+Microsoft Store apps or Window components+WHQL+Microsoft Store apps+Intelligent Security Graph.

If additional LOB apps need to be allowed then the current solution is relying on Intune’s custom URI capability to define identifiers (signers, hashes) for the LOB apps and include them in a CUSTOM WDAC policy that is pushed out through the AppLocker CSP. 

A catalog file is another option for LOB apps but Intune doesn't have a great way to deploy catalog files currently. You could try to bundle catalogs using MSIs. Or deploy them using Group Policy or SCCM: https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-control/deploy-catalog-files-to-support-windows-defender-application-control

**Comment by Justinha** [comment]
@Rutikhal Sorry to miss your question. You can use a catalog file to allow lob apps, or just stand up a reference device that runs all of the apps you need and create a code integrity policy there. Here are some links: https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-control/deploy-catalog-files-to-support-windows-defender-application-control or https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-control/create-initial-default-policy

**Comment by Rutikhal** [comment]
Is there any links to documentation about mentioned "CUSTOM WDAC policy that is pushed out through the AppLocker CSP"? Our company now uses AppLocker via Intune but we have a lot of problems with that. I just hope maybe custom WDAC works better?

**Comment by Justinha** [comment]
Yes, see the AppLocker CSP docs: https://docs.microsoft.com/en-us/windows/client-management/mdm/applocker-csp

**Comment by mypil** [comment]
@Rutikhal - Thank you for submitting feedback.

From our understanding, the issue has been answered by Justinha. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
