### ISSUE TITLE
IE11 Support on Windows 10

### ISSUE THREAD

**Issue by danjpadgett** [MicrosoftDocs/windows-itpro-docs#1003]
This article says ' It's also supported on Windows 10, but isn't pre-installed. '

However IE is bundled with Windows 10. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4bdee89-febb-5b86-d278-fa46a11e35ca
* Version Independent ID: 1e20fd00-a9f9-6433-fe6f-7bf042d335f6
* Content: [System requirements and language support for Internet Explorer 11 (IE11) (Internet Explorer 11 for IT Pros)](https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/system-requirements-and-language-support-for-ie11)
* Content Source: [browsers/internet-explorer/ie11-deploy-guide/system-requirements-and-language-support-for-ie11.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/internet-explorer/ie11-deploy-guide/system-requirements-and-language-support-for-ie11.md)
* Service: **unspecified**
* Product: **ie11**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by shortpatti** [comment]
@danjpadgett, thanks for catching.  I'll update the document with the correct information.
