### ISSUE TITLE
Keep my files or Remove Everything

### ISSUE THREAD

**Issue by wiicode** [MicrosoftDocs/windows-itpro-docs#10032]
There may be a material error in OOBE section.  This page reads:

> On the Virtual Machine, go to Settings > Update & Security > Recovery and select Get started under Reset this PC. Select Remove everything and Just remove my files. If you're asked How would you like to reinstall Windows, select Local reinstall. Finally, select Reset.

The choice today is "Keep my files" **or** "Remove Everything". When I attempted to use "Keep my Files" I did not trigger OOBE. While I am still troubleshooting the cause, finding this text was unwelcome as it leaves a large question about my process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc63299-cc1c-e031-deb7-915914b8f94e
* Version Independent ID: 356eaba5-16b0-952f-fc19-c8d5be5feb5f
* Content: [Demonstrate Autopilot deployment - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm#reset-the-vm-back-to-out-of-box-experience-oobe)
* Content Source: [windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by MaratMussabekov** [comment]
Hello @wiicode ,
**The choice today is "Keep my files" or "Remove Everything". When I attempted to use "Keep my Files" I did not trigger OOBE.** - "remove everything" should be chosen on this step.
Please have a look at https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10218

Thank you
