### ISSUE TITLE
High-Availability for NDES

### ISSUE THREAD

**Issue by adamgourd** [MicrosoftDocs/windows-itpro-docs#10033]
There's a section (#high-availability) in this article about configuring NDES servers for high-availability. This is very good info. My feedback is that the we should include this information in docs pages for NDES setup and configuration as well as configuring Intune with a cert connector to work with NDES. For example: this page, https://docs.microsoft.com/en-us/mem/intune/protect/certificates-scep-configure, should have this same #high-availability block. Perhaps give that its own page that these other articles can refer to. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f709fd4-0b5d-b238-4060-222d550cd538
* Version Independent ID: fb3f29da-2236-c47d-6bea-8efbcec8d7d3
* Content: [Using Certificates for AADJ On-premises Single-sign On single sign-on - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by MaratMussabekov** [comment]
Hello @adamgourd ,
I believe adding link will be enough, please have a look at https://github.com/MicrosoftDocs/memdocs/pull/2249
Thank you
