### ISSUE TITLE
Title on this page seems to be populated by a lot of text

### ISSUE THREAD

**Issue by paaff** [MicrosoftDocs/windows-itpro-docs#10040]
Hi,

Not sure if this is intended, but the title on this page [Advanced security auditing FAQ (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/advanced-security-auditing-faq) is extremely long.

It would seem as if the title should just be **Advanced security auditing FAQ**, and the rest of the text is simply an honest error :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd90a4a0-83db-adeb-241e-c70be8624741
* Version Independent ID: 0910454c-0e11-07a2-37a7-6a7b3e7411b5
* Content: [Advanced security auditing FAQ (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/advanced-security-auditing-faq)
* Content Source: [windows/security/threat-protection/auditing/advanced-security-auditing-faq.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/advanced-security-auditing-faq.yml)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Duplicate of #10059. Thank you for the feedback.
