### ISSUE TITLE
Remote Lock on Windows Desktop 10?

### ISSUE THREAD

**Issue by dfconroy** [MicrosoftDocs/windows-itpro-docs#1004]
Is there a method I haven't found - or a specified release for when remote locking of Windows Desktops will be introduced? 

I've noticed when you log into Windows Live with a user account that's attached to a computer you can remote lock a device that way... so I don't know why that same functionality wouldn't be available in MDM. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59f4582e-9f27-e356-695a-4ed783c708e2
* Version Independent ID: 5a76f24b-abea-ec60-4c15-eb3f193a71c0
* Content: [RemoteLock CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/remotelock-csp)
* Content Source: [windows/client-management/mdm/remotelock-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/remotelock-csp.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by dfconroy** [comment]
Any update on this?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @dfconroy ,
The feature you are talking about is not available in MDM.
Thank you

**Comment by mypil** [comment]
@dfconroy - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
