### ISSUE TITLE
Possible error in UserRights/DenyLocalLogOn

### ISSUE THREAD

**Issue by ElizabethGreene** [MicrosoftDocs/windows-itpro-docs#10054]
The UserRights/DenyLocalLogOn policy documentation says "This security setting determines which service accounts are prevented from registering a process as a service.  Note: This security setting does not apply to the System, Local Service, or Network Service accounts." 

That describes a different user right, "Deny log on as a service".  I believe that's incorrect and the text should be "This security setting determines which users are prevented from logging on at the computer.  Note: If you apply this security policy to the Everyone group, no one will be able to log on locally."

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b62d452-1910-d962-0ccc-9ac3f8135f15
* Version Independent ID: 5a4e6f0c-bcd4-8d8b-93f7-5bda7135b931
* Content: [Policy CSP - UserRights - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-userrights#userrights-denylocallogon)
* Content Source: [windows/client-management/mdm/policy-csp-userrights.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-userrights.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**
*

**Comment by RAJU2529** [comment]
@ElizabethGreene  Thanks for pointing out.  i am going to fixing it now

**Comment by ElizabethGreene** [comment]
Thanks very much @RAJU2529
