### ISSUE TITLE
This Page is broke.

### ISSUE THREAD

**Issue by iceph03nix** [MicrosoftDocs/windows-itpro-docs#10059]
When I load the page, it seems to have a broken heading, as the entire first section is all in Heading style text

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd90a4a0-83db-adeb-241e-c70be8624741
* Version Independent ID: 0910454c-0e11-07a2-37a7-6a7b3e7411b5
* Content: [Advanced security auditing FAQ (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/advanced-security-auditing-faq)
* Content Source: [windows/security/threat-protection/auditing/advanced-security-auditing-faq.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/advanced-security-auditing-faq.yml)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Thank you @iceph03nix for letting us know about this. We'll get it fixed.

**Comment by e0i** [comment]
@denisebmsft Can the article title be fixed by a public PR as usual?

Although it doesn’t look like a broken Markdown, please let me know if it can be publicly fixed so that independent contributors can take it away from here. Thanks.

**Comment by RAJU2529** [comment]
@e0i , just now i created PR #10102  for this issue.
