### ISSUE TITLE
AGPM 4.0 SP3 support for Server 2016

### ISSUE THREAD

**Issue by ZinSystems** [MicrosoftDocs/windows-itpro-docs#10068]
Hi,

I have AGMP successfully running on a Windows Server 2016 member server in a pre-prod environment. After reviewing the supported server operating system lists I have noticed Windows Server 2016 is not listed as a supported OS to run AGPM 4.3 on! This is odd as 2019 and 2012 are both listed as being supported. I do think this is a typo, but can someone please clarify that 2016 is a supported OS for AGPM 4.3, before I deploy this into a production environment?

Official support options article:

https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/agpm/choosing-which-version-of-agpm-to-install

**Comment by VLG17** [comment]
@ZinSystems You are correct, it is supported on Windows Server 2016, as described [here](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/agpm/):

![image](https://user-images.githubusercontent.com/41186174/148442678-18772d5f-2d9f-449b-83a3-c20ed44d42ab.png)

I've created a PR to reflect that.

**Comment by aczechowski** [comment]
This MDOP AGPM article isn't in this repo, and I see that VLG17 filed a PR to fix the request, so I'm closing this issue
