### ISSUE TITLE
Clarity on Where to Access This Tile

### ISSUE THREAD

**Issue by RichardGallo-MS** [MicrosoftDocs/windows-itpro-docs#10067]
Hi there - would it be possible to clarify where in Azure to access this tile? It isn't clear that one needs to navigate to LogAnalytics, Log space, Workspaces to access the tile. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cf1e851-9449-cd9d-0f8a-af797154ca88
* Version Independent ID: 9ce3da25-2bfc-d558-1853-0d16d8f26c40
* Content: [Using Update Compliance - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-using)
* Content Source: [windows/deployment/update/update-compliance-using.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-using.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@aamalhot can you make this update?

**Comment by jaimeo** [comment]
or actually, @RichardGallo-MS you can make the proposed edit yourself directly with the **Edit** button there on the live article.

**Comment by jaimeo** [comment]
@UCOwner

**Comment by e0i** [comment]
We are taking away the article from here thanks
