### ISSUE TITLE
OMA Website Link Resolves to a 404 Error

### ISSUE THREAD

**Issue by mkesler80** [MicrosoftDocs/windows-itpro-docs#10062]
This link  to the OMA website no longer exists and needs to be updated.  https://go.microsoft.com/fwlink/p/?LinkId=267526

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 765e6116-1f6a-9b78-970b-cbb25c66bece
* Version Independent ID: e307cb15-9ffe-fb35-2180-c77082add8e9
* Content: [Enterprise settings, policies, and app management - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/windows-mdm-enterprise-settings)
* Content Source: [windows/client-management/mdm/windows-mdm-enterprise-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/windows-mdm-enterprise-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Thank you for letting us know about this @mkesler80. The correct link is: https://www.openmobilealliance.org/release/DM/V1_2-20070209-A/OMA-TS-DM_Protocol-V1_2-20070209-A.pdf

I have updated the link in the article and the updates will be live later today

**Comment by e0i** [comment]
Addressed via commit, https://github.com/MicrosoftDocs/windows-itpro-docs/commit/5eabd84d585e989a879cf1d544846dede4dcafbf#diff-bce81590f2ffc5487cc5598ac07100c2318c69a832dcbc9a7e95ad75b45dcc97

Thanks.
