### ISSUE TITLE
Resetting service ACLs is dangerous!

### ISSUE THREAD

**Issue by joachimme** [MicrosoftDocs/windows-itpro-docs#10076]
[Enter feedback here]
In step 4b, the article claims it will reset the ACLs for the services BITS and Windows Update to their default value. I just checked Windows Server 2016 and Windows Server 2019 default values and both deviate from the alleged "default values" in the article.  So it will not reset the ACLs to the default values but instead it will change the default values. I think the risk is higher to break something by changing the service ACLs. Not sure if Microsoft would support changing from default values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@arcarley @Alice-at-Microsoft can either of you advise? Or connect with someone who can?

**Comment by Alice-at-Microsoft** [comment]
@jaimeo @arcarley Unfortunately, I don't know.

**Comment by arcarley** [comment]
Unfortunately outside of my area as well...

**Comment by joachimme** [comment]
Let me just add some more details. A service ACL controls which user account can for instance can stop or start a service or change the service configuration ([](https://docs.microsoft.com/en-us/windows/win32/services/service-security-and-access-rights#access-rights-for-a-service)).

Let's check the Windows 10 default ACL for the Windows Update service. I am running Windows 10 Enterprise 21H1:

`PS > Get-CimInstance -ClassName Win32_OperatingSystem | Select Caption

Caption
-------
Microsoft Windows 10 Enterprise

PS > [System.Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19043.0 Microsoft Windows NT 10.0.19043.0
`
The default ACL looks like this in SDDL format:

`PS > sc.exe sdshow wuauserv

D:(A;;CCLCSWRPLORC;;;AU)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;SY)
`
Let's convert it to a readable format:

`PS > $WuauservSddl = (sc.exe sdshow wuauserv)[1]
PS > $WuauservAcl = New-Object -TypeName 'System.Security.AccessControl.CommonSecurityDescriptor' -ArgumentList $false,$false,$WuauservSddl

PS > $WuauservAcl.DiscretionaryAcl | Select SecurityIdentifier,@{Name='NTAccountName';Expression={((New-Object -TypeName System.Security.Principal.SecurityIdentifier($_.SecurityIdentifier)).Translate([System.Security.Principal.NTAccount]).Value)}},AceType,AceFlags,AccessMask,@{Name = 'AccessMaskString';Expression={[Flags()] Enum EnumAccessMask{SERVICE_QUERY_CONFIG=1; SERVICE_CHANGE_CONFIG=2; SERVICE_QUERY_STATUS         = 4
>> SERVICE_ENUMERATE_DEPENDENTS=8; SERVICE_START=16; SERVICE_STOP=32; SERVICE_PAUSE_CONTINUE       = 64
>> SERVICE_INTERROGATE          = 128
>> SERVICE_USER_DEFINED_CONTROL = 256
>> DELETE                       = 65536
>> READ_CONTROL                 = 131072
>> WRITE_DAC                    = 262144
>> WRITE_OWNER                  = 524288
>> SERVICE_ALL_ACCESS           = 983551
>>
>>     }
>>     [EnumAccessMask][int]$_.AccessMask
>>   }
>> }

SecurityIdentifier : S-1-5-11
NTAccountName      : NT AUTHORITY\Authenticated Users
AceType            : AccessAllowed
AceFlags           : None
AccessMask         : 131229
AccessMaskString   : SERVICE_QUERY_CONFIG, SERVICE_QUERY_STATUS, SERVICE_ENUMERATE_DEPENDENTS, SERVICE_START, SERVICE_INTERROGATE, READ_CONTROL

SecurityIdentifier : S-1-5-18
NTAccountName      : NT AUTHORITY\SYSTEM
AceType            : AccessAllowed
AceFlags           : None
AccessMask         : 983551
AccessMaskString   : SERVICE_ALL_ACCESS

SecurityIdentifier : S-1-5-32-544
NTAccountName      : BUILTIN\Administrators
AceType            : AccessAllowed
AceFlags           : None
AccessMask         : 983551
AccessMaskString   : SERVICE_ALL_ACCESS
`

So we can see the ACL includes three Access Control Entries (ACEs). Administrators and SYSTEM have full control to the service and regular users (Authenticated Users) can read the configuration and start the service (but not stop it or change the service configuration.

Now let's have a look at the ACL for the Windows Update service from the article:

`D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;AU)(A;;CCLCSWRPWPDTLOCRRC;;;PU)
`
Convert it to a readable format:

`PS > $WuauservSddlFromArticle = 'D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;AU)(A;;CCLCSWRPWPDTLOCRRC;;;PU)'
PS > $WuauservAcl = New-Object -TypeName 'System.Security.AccessControl.CommonSecurityDescriptor' -ArgumentList $false,$false,$WuauservSddlFromArticle
PS > $WuauservAcl.DiscretionaryAcl | Select SecurityIdentifier,@{Name='NTAccountName';Expression={((New-Object -TypeName System.Security.Principal.SecurityIdentifier($_.SecurityIdentifier)).Translate([System.Security.Principal.NTAccount]).Value)}},AceType,AceFlags,AccessMask,@{Name = 'AccessMaskString';Expression={[Flags()] Enum EnumAccessMask{SERVICE_QUERY_CONFIG=1; SERVICE_CHANGE_CONFIG=2; SERVICE_QUERY_STATUS         = 4
>> SERVICE_ENUMERATE_DEPENDENTS=8; SERVICE_START=16; SERVICE_STOP=32; SERVICE_PAUSE_CONTINUE       = 64
>> SERVICE_INTERROGATE          = 128
>> SERVICE_USER_DEFINED_CONTROL = 256
>> DELETE                       = 65536
>> READ_CONTROL                 = 131072
>> WRITE_DAC                    = 262144
>> WRITE_OWNER                  = 524288
>> SERVICE_ALL_ACCESS           = 983551
>>
>>     }
>>     [EnumAccessMask][int]$_.AccessMask
>>   }
>> }

SecurityIdentifier : S-1-5-11
NTAccountName      : NT AUTHORITY\Authenticated Users
AceType            : AccessAllowed
AceFlags           : None
AccessMask         : 131469
AccessMaskString   : SERVICE_QUERY_CONFIG, SERVICE_QUERY_STATUS, SERVICE_ENUMERATE_DEPENDENTS, SERVICE_INTERROGATE, SERVICE_USER_DEFINED_CONTROL, READ_CONTROL

SecurityIdentifier : S-1-5-18
NTAccountName      : NT AUTHORITY\SYSTEM
AceType            : AccessAllowed
AceFlags           : None
AccessMask         : 131581
AccessMaskString   : SERVICE_QUERY_CONFIG, SERVICE_QUERY_STATUS, SERVICE_ENUMERATE_DEPENDENTS, SERVICE_START, SERVICE_STOP, SERVICE_PAUSE_CONTINUE,
                     SERVICE_INTERROGATE, SERVICE_USER_DEFINED_CONTROL, READ_CONTROL

SecurityIdentifier : S-1-5-32-544
NTAccountName      : BUILTIN\Administrators
AceType            : AccessAllowed
AceFlags           : None
AccessMask         : 983551
AccessMaskString   : SERVICE_ALL_ACCESS

SecurityIdentifier : S-1-5-32-547
NTAccountName      : BUILTIN\Power Users
AceType            : AccessAllowed
AceFlags           : None
AccessMask         : 131581
AccessMaskString   : SERVICE_QUERY_CONFIG, SERVICE_QUERY_STATUS, SERVICE_ENUMERATE_DEPENDENTS, SERVICE_START, SERVICE_STOP, SERVICE_PAUSE_CONTINUE,
                     SERVICE_INTERROGATE, SERVICE_USER_DEFINED_CONTROL, READ_CONTROL
`

This ACL includes four ACEs and the additional ACE allows member of the Power Users group. At least Power Users are not allowed to change the service configuration and thus can elevate their privileges to Administrator but it changes the default ACLs on Windows 10. The ACL fromt the article is probably the default from an older Windows version, maybe 7 or 8 but I would guess the Windows product group had its reasons to change that for Windows 10, Windows Server 2016 and 2019 and so I would say it's not a very good idea to change that value (possibly also results in supportability issues). In addition, the service ACL has nothing to do with the Windows Update agent not working properly. If the service ACL might get corrupted, you may not be able to start or stop the service but it does not affect the inner workings of the Windows Update agent. I would remove changing the ACL completely from the article.

**Comment by VLG17** [comment]
@joachimme I've tested on 2 fresh VMs (Windows 11 and Windows Server 2019) and found the following default security descriptors for BITS and Windows Update service.

sc.exe sdshow wuauserv
D:(A;;CCLCSWRPLORC;;;AU)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;SY)

sc.exe sdshow bits
D:(A;CI;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)

Hence i've created a PR to change the values to these.

**Comment by VLG17** [comment]
@joachimme Good point and I thought about that before doing the PR. I did it because I saw that the article applies only to Windows 10/11 and Server 2016/2019, which have those default security descriptors.

Until the "applies to" changes and the newer versions will have different default security descriptors, I think we should be good. But let's see what the author thinks about it.

**Comment by jaimeo** [comment]
I'm no longer working in this area; author metadata not assigned yet.

@arcarley can you direct to someone on the technical side to advise this person? @dougeby FYI.

**Comment by itsrlyAria** [comment]
Unfortunately, I am not sure who to redirect to on the product side..

**Comment by greg-lindsay** [comment]
A little investigation reveals that it is possible for Windows Update service to be set such that authorized users do not have permission to search for and install updates.  This can happen due to a GPO.  Resetting the ACLs might only be necessary under this circumstance. I suggest modifying the PR to have 4b as an optional step in cases where there is a permission issue.

**Comment by aczechowski** [comment]
@e0i & @joinimran FYI I reviewed this with our team's update SME @mestew and recommendation is to remove this article and/or put in a request to migrate it to docs.microsoft.com/troubleshoot. While the article gets a lot of PVs (32k in June 2022), a lot of the content is very out of date. I wanted to check with you if you had another plan in mind? (Personally I think migrating to troubleshooting is the best path at this point.)

**Comment by e0i** [comment]
@aczechowski

The best next step for us would be to move forward with Greg's advice as commented above. We couldn't have any plans if the article is meant to be removed afterwards as our team is only handling corrections.
