### ISSUE TITLE
Bitlocker Security FAQ mistranslation

### ISSUE THREAD

**Issue by IPv4v6** [MicrosoftDocs/windows-itpro-docs#10071]
English text: "For improved security, we recommend disabling sleep mode and that you use TPM+PIN for the authentication method."
German text: "Aus Sicherheitsgründen wird empfohlen, den Ruhezustand zu deaktivieren und TPM und PIN für die Authentifizierungsmethode zu verwenden."

**"Ruhezustand" means "hibernation", this is not the correct translation for "sleep mode".**

See: https://twitter.com/IPv4v6/status/1456016427077484545

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 074a9fb3-857d-bbca-ce57-e053d4a146fe
* Version Independent ID: d70d760c-2598-aca0-f7bc-fb2b360c33c0
* Content: [Häufig gestellte Fragen zur BitLocker-Sicherheit (Windows 10) - Windows security](https://docs.microsoft.com/de-de/windows/security/information-protection/bitlocker/bitlocker-security-faq)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-security-faq.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-security-faq.yml)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by TinaMcN** [comment]
@IPv4v6 thanks for reporting this issue, it is probably caused by poor machine translation.  I sent the article to be translated by a human and it should be completed within ~1 week.

**Comment by e0i** [comment]
The translation seems to have been applied to the article. Thanks.
