### ISSUE TITLE
Developer Mode Dynamic Code Trust

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#10077]
My policies are generated with a setting: "Enabled: Developer Mode Dynamic Code Trust". I don't see a reference to this anywhere. Any ideas where it comes from?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74ef7917-edec-5597-4689-1ffbf6735918
* Version Independent ID: 41f7ceb2-ad16-812c-3766-b9a9a72a42c1
* Content: [Understand Windows Defender Application Control (WDAC) policy rules and file rules (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by tylermontneyacc** [comment]
What was done to explain "Developer Mode Dynamic Code Trust"? I have the same question and the docs don't list it.

**Comment by jgeurten** [comment]
Hi folks, its documented in the table here: https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create#table-1-windows-defender-application-control-policy---policy-rule-options, but the description could use some work. On systems with Developer Mode turned on, any binaries deployed using F5 deploy will be allowed to run
