### ISSUE TITLE
TargetProductVersion incorrect

### ISSUE THREAD

**Issue by helmlingp** [MicrosoftDocs/windows-itpro-docs#10084]
TargetProductVersion should be ProductVersion. TargetProductVersion errors on device with "file or path not found". Please change doco.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ca58bd-f279-7739-0140-c4bd56784768
* Version Independent ID: 1d2ecc90-58a3-6bcd-84ae-ef04d7a3b7b4
* Content: [Policy CSP - Update - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update)
* Content Source: [windows/client-management/mdm/policy-csp-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @helmlingp ,
please have a look at https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10156
Thank you
