### ISSUE TITLE
URL update?

### ISSUE THREAD

**Issue by macmule** [MicrosoftDocs/windows-itpro-docs#10080]
The linked URL (https://www.microsoft.com/en-us/wdsi/filesubmission), doesn't seem to be correct.. (see attached).

Guessing there is an update needed for the URL, if not then the whole document might need correcting or deleting.

<img width="1509" alt="Screenshot 2021-11-06 at 10 59 57" src="https://user-images.githubusercontent.com/2464974/140607245-8878502c-2d03-4e1b-9d34-136ff8c38137.png">

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c18d83a-e2fe-3652-4e52-f580c8c3397a
* Version Independent ID: 2ef02e21-d2eb-78e2-6819-8330a5fce69e
* Content: [Submit files for analysis by Microsoft - Windows security](https://docs.microsoft.com/en-gb/windows/security/threat-protection/intelligence/submission-guide)
* Content Source: [windows/security/threat-protection/intelligence/submission-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/submission-guide.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Hello @macmule. THANK YOU for letting us know about the broken link. The correct link is https://www.microsoft.com/en-us/wdsi/filesubmission. I have updated the article with the correct links, and you will see the updates live later today. Thank you again for posting this issue.
