### ISSUE TITLE
Update the page with the new Update Compliance records

### ISSUE THREAD

**Issue by PanuSaukko** [MicrosoftDocs/windows-itpro-docs#10082]
Hi,

There are a bunch of new Update Compliance records:
- UCClient
- UCClientReadinessStatus
- UCClientUpdateStatus
- UCDeviceAlerts

Please update the page to contain information about those new records.

Panu
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d810dfe-ae87-176c-b3f8-7e6643fc9fab
* Version Independent ID: ebe32236-716e-8224-8a2e-54d940ea3b9e
* Content: [Update Compliance Data Schema - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-schema)
* Content Source: [windows/deployment/update/update-compliance-schema.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-schema.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@aamalhot can you do this update? Or work with Doug Eby to engage a writer to do so.

**Comment by aamalhot** [comment]
@jaimeo I don't work on this team. looks like you are looking someone else

**Comment by jaimeo** [comment]
oops, sorry about that!

**Comment by e0i** [comment]
Following up. @jaimeo @UCOwner

**Comment by aczechowski** [comment]
Closing, addressed in preview docs for UC
