### ISSUE TITLE
Update Compliance Already Installed, what should we do?

### ISSUE THREAD

**Issue by lexios** [MicrosoftDocs/windows-itpro-docs#10092]
We have been using Log Analytics/Update Compliance for some years now.
I thought that adding this Solution from the MarketPlace would add functionality or upgrade our workspace?

Nevertheless, I got the following message while trying to set it up.

"Update Compliance is already installed on selected LA Workspace"
"Proceeding with creation will overwrite existing solution"

We need some more information on how we can install this Solution without affecting our current setup or a specific paragraph referencing if there is a need at all for us to use this solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5549abd-da28-5d11-49c6-e66ecf5cd0b6
* Version Independent ID: 0
* Content: [Get started with Update Compliance - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-get-started)
* Content Source: [windows/deployment/update/update-compliance-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-get-started.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo
![Preexisting](https://user-images.githubusercontent.com/18334893/140973424-aacd285e-fd58-4aae-a5d2-8829c8384582.png)
**

**Comment by UCOwner** [comment]
@lexios  Can you elaborate on your scenario a bit more? When you started using UC a few years ago, did you not add UC to your solution? You created a subscription and workspace the first time? What are you trying to do now?

**Comment by jaimeo** [comment]
@UCOwner
