### ISSUE TITLE
Trusted Network Detection description is wrong

### ISSUE THREAD

**Issue by zerqent** [MicrosoftDocs/windows-itpro-docs#10095]
Hello.

From experience it seems like the information that Trusted Network Detection look at the DNS-suffix is wrong. Rather it seems to look at what Windows Names the network which usually is a DNS-suffix. You know unless Windows does something weird and suddenly you have "mydomain.example.com 2". (Get-NetConnectionProfile | Select Name)

In addition there is no mention of DomainAuthenticated-network which (in combination with the Name) should satisfy the condition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86069c62-780b-f32d-0f52-17a3361b4457
* Version Independent ID: 9216519b-8d11-3bee-b987-ef29f41757bf
* Content: [VPN auto-triggered profile options (Windows 10 and Windows 11) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-auto-trigger-profile)
* Content Source: [windows/security/identity-protection/vpn/vpn-auto-trigger-profile.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/vpn/vpn-auto-trigger-profile.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @zerqent ,
Trusted network detection checks all network interfaces for DNS suffixes, and if it can access resources located within these suffixes, VPN doesn't connect.
**it seems to look at what Windows Names the network which usually is a DNS-suffix** - not sure, Windows usually only provides one name to the network, while network interface could have more than one DNS suffix.

Thank you

**Comment by zerqent** [comment]
Wrll this is just plainøy wrong. Have you checked with the actual
developers?

**Comment by Judical** [comment]
This is still the case in 2023 it looks at the network name, not the DNS suffix.

**Comment by gverrey** [comment]
Yes, one week i try to understand why my detection of dns suffix with my policy Intune doesn't work and...after test it, eureka, it looks at the network name, not the dns suffix. And this is a huge issue because the networkname change always with a Network 2, Network 3.

**Comment by Judical** [comment]
My issue is that we are using a GPO that changes the network name. It appears that offices that were around before the GPO was created are fine. The new offices are having an issue that AOVPN is connecting when they are in the office. I figured out that adding the network name as a trusted network fixes the issue however it is going to be a pain to get new profile on all of the deployed machines. Does anyone know a way of modifying the trusted networks without creating a new profile?
