### ISSUE TITLE
Storage to AD DS is wrong, lacks Azure

### ISSUE THREAD

**Issue by zerqent** [MicrosoftDocs/windows-itpro-docs#10109]
"This policy setting is used to configure the storage of BitLocker recovery information in AD DS..."

This is inaccurate. Should also say that the information will be stored in Azure if the system is joined.

This should also be backported to every ADMX/ADML-template.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5476099c-9d70-97df-8ee6-bc442605cfbd
* Version Independent ID: 49ca0628-bd88-e05b-b705-3b361b57512d
* Content: [BitLocker Group Policy settings (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-group-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @zerqent ,
Could you please advise the source of this information? I cannot find any document where it is mentioned that this policy affects Azure AD joined devices.
Thank you

**Comment by zerqent** [comment]
> Hello @zerqent , Could you please advise the source of this information? I cannot find any document where it is mentioned that this policy affects Azure AD joined devices. Thank you

Well yeah, the problem is that it is not available in any direct documentation as far as I know. However, if you enable this setting, and the system is Hybrid Azure AD Joined, upon creation of a new Recovery password, the recovery information will be pushed to Azure AD as Well as AD DS.

So if you need a source you probably must reach out to whoever thought it was a good idea to merge these two settings (instead of making a separate one for Azure AD storage)

**Comment by MaratMussabekov** [comment]
Dear @Dansimp ,
is it possible to check this information with the production team?
Thank you

**Comment by aczechowski** [comment]
Thanks @zerqent for the feedback. This article in general is really old and too long, it needs some major revisions. Instead of making a minor tweak to include this note, we need to do a larger review and update. I've filed an internal tracking item to address that (task 6324300), and so am closing this issue.

I suggest filing feedback through the [Feedback Hub](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) about revising the strings on the group policy setting itself.
