### ISSUE TITLE
Important statement about OSManagedAuthLevel is contradicting

### ISSUE THREAD

**Issue by RonaldAi** [MicrosoftDocs/windows-itpro-docs#10100]
The "Important" box on this page contains this text "The default value for this key is 2, and unless it is changed to 4 before the TPM is provisioned, the owner password will not be saved."
This contradicts language on https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/trusted-platform-module-services-group-policy-settings that states "Beginning with Windows 10 version 1703, the default value is 5."
We (o the product team side) think the latter is correct, which means this page should be updated.

Thanks, Ron.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589107e3-caf8-797e-391e-41457437e5c1
* Version Independent ID: acce4c69-e822-f7e9-8341-06b6d3061c57
* Content: [Change the TPM owner password (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/change-the-tpm-owner-password)
* Content Source: [windows/security/information-protection/tpm/change-the-tpm-owner-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/tpm/change-the-tpm-owner-password.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @RonaldAi , please have a look at #10177.
Also, the table in article https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/trusted-platform-module-services-group-policy-settings doesn't contain the value 5 as well. Shouldn't it be updated too? Or since it mentions that the policy is not used any more, it could be ignored?
Thank you

**Comment by RonaldAi** [comment]
Hi @MaratMussabekov, 
@ZachMcW and I checked your PR. 
Here is some feedback (Thanks Zach):
As for the ask if the table at [TPM Group Policy settings (Windows) - Windows security | Microsoft Docs](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/trusted-platform-module-services-group-policy-settings) should be updated, I think it can be. But the information about the value of 5 is included in the Important box.

However, his statement “policy is not used any more” confused me. I looked to see what the page said, in the Important box:
“Beginning with Windows 10 version 1607 and Windows Server 2016, this policy setting is no longer used by Windows”.
This doesn’t seem to be right. We are still using this value.

Thanks, Zach and Ron.

**Comment by MaratMussabekov** [comment]
Hello @RonaldAi ,
thank you for the valuable information. So we can just remove the part "Beginning with Windows 10 version 1607 and Windows Server 2016, this policy setting is no longer used by Windows, but it continues to appear in GPEdit.msc for compatibility with previous versions. " from the **important** box?
Thank you

**Comment by RonaldAi** [comment]
Adding @***@***.***> for input

**Comment by RonaldAi** [comment]
Yes, that correction looks right.

Thanks,
Zach

From: Ronald Aigner (HE/HIM) ***@***.***>
Sent: Monday, December 13, 2021 8:39 AM
To: MicrosoftDocs/windows-itpro-docs ***@***.***>; MicrosoftDocs/windows-itpro-docs ***@***.***>; Zachary McWilliams ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/windows-itpro-docs] Important statement about OSManagedAuthLevel is contradicting (Issue #10100)

Adding @***@***.***> for input
