### ISSUE TITLE
Missing Entries

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#10105]
The XML example does not contain the Redstone entries under DLL and EXE therefore is not valid to import

`	  <RedstoneExtensions>
        <SystemApps Allow="Enabled" />
      </RedstoneExtensions>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d9a0607-b206-fab3-ef68-9de7c7e6a072
* Version Independent ID: 9ca53978-51c8-d2e1-c6a4-4b0a19bac244
* Content: [Allow apps deployed with a WDAC managed installer (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello, this code was already removed by https://github.com/MicrosoftDocs/windows-itpro-docs/commit/ef4e99945651c2c8655952b9f7bcc1294eeaf89c#diff-cf7faacaf5aefaa15bf26e015dbc45ab2718d8a42535eaf1d05fd2b30d7deaaf

Thank you
