### ISSUE TITLE
Embedded architecture images need to be resized

### ISSUE THREAD

**Issue by CltAvi8tor** [MicrosoftDocs/windows-itpro-docs#10110]
The images embedded in this article are almost impossible to read. They either need to be resized larger to shoe more detail or (better) there should be hyperlinks on each image to a full resolution version for ease of consumption.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f170bfe-711d-f875-8d5f-a49d3d5113b2
* Version Independent ID: a75c9aa8-b47b-51dd-9b84-c63bb5c6b782
* Content: [How Windows Hello for Business works - Provisioning - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-provisioning#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-how-it-works-provisioning.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-how-it-works-provisioning.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by MaratMussabekov** [comment]
Dear @CltAvi8tor ,
please have a look at #10200 
Thank you
