### ISSUE TITLE
Identifier Authority - Value table needs to have names/values a least till 16

### ISSUE THREAD

**Issue by zb-z** [MicrosoftDocs/windows-itpro-docs#10111]
https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/security-identifiers

Identifier Authority - Value table needs to have names/values a least till 16. Currently it doesn't even go to 5 (NT Authority).

That makes it quite useless little "illustration" - like someone was writing an article for aq computer magazine and editor in chief told him that he has to cut it since it will take too much paper in print. 

Also when y1 has a sequence of regular values that needs to be documented as well.

If this kind of page is not a definitive word on the subject matter is becomes it becomes useless pretty fast.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af0ec4a3-6f79-33d7-adab-0000742fc992
* Version Independent ID: db89d5e2-f49f-bf65-f583-a9545e6fe0bb
* Content: [Security identifiers (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/security-identifiers)
* Content Source: [windows/security/identity-protection/access-control/security-identifiers.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/access-control/security-identifiers.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
hello @zb-z ,
please have a look at https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10217
the table only misses s-1-5 and s-1-18, other Identifier Authorities do not present will-known SIDs
Thank you
