### ISSUE TITLE
lifecycle mistake

### ISSUE THREAD

**Issue by atilg-msft** [MicrosoftDocs/windows-itpro-docs#10124]
H2 releases have a support lifecycle of 30 months, while this document states 36. Is there a change in the policy? This is also stated in the announcement blog: https://blogs.windows.com/windowsexperience/2021/07/15/introducing-the-next-feature-update-to-windows-10-21h2/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd214c3a-e3db-4f0b-6a7d-286aec8e0399
* Version Independent ID: fd214c3a-e3db-4f0b-6a7d-286aec8e0399
* Content: [What's new in Windows 10, version 21H2 for IT pros - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-21h2)
* Content Source: [windows/whats-new/whats-new-windows-10-version-21H2.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/whats-new-windows-10-version-21H2.md)
* Product: **w10**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by RAJU2529** [comment]
Created PR #10127

**Comment by MandiOhlinger** [comment]
@atilg-msft Thank you! This is fixed, and the article changes are live - [https://docs.microsoft.com/windows/whats-new/whats-new-windows-10-version-21h2](https://docs.microsoft.com/windows/whats-new/whats-new-windows-10-version-21h2). 

You can close this GitHub issue.
