### ISSUE TITLE
Please update information by Windows 10 21H2

### ISSUE THREAD

**Issue by yukinork** [MicrosoftDocs/windows-itpro-docs#10121]
There are no information for "features removed" and "no longer developing" of Windows 10 21H2.

I know Windows 11 was GA so if no more "no longer developing" or "features removed" in Windows 10, I would like to be write it so like a "This page is no more update because we are moving to Windows 11".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215fea14-a9f3-6ed1-8aa3-8cbb4cbfc398
* Version Independent ID: ea54caae-1d90-fe54-217d-c43221cfce09
* Content: [Windows 10 - Features that have been removed - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-removed-features#feedback)
* Content Source: [windows/deployment/planning/windows-10-removed-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/planning/windows-10-removed-features.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by joinimran** [comment]
@yukinork - Thank you for your query here. I have checked and found that there is no major/minor feature removed from Windows 10 21H2. Only a few options that are added can be seen https://docs.microsoft.com/windows/whats-new/whats-new-windows-10-version-21h2.

Whenever there will be any change, it will be updated on the page. If there is something that you feel is missing, please let me know.

Thanks
Imran.

@e0i FYI&A Please.
