### ISSUE TITLE
Maybe it should be "Windows 10 Enterprise LTSC 2021" instead of "Windows 10 Enterprise LTSC 2019"

### ISSUE THREAD

**Issue by Luyeok** [MicrosoftDocs/windows-itpro-docs#10123]
![image](https://user-images.githubusercontent.com/7817555/142146929-69a37748-2ef2-4f8e-b1f2-382b4f021d3f.png)

The last line in the pic may should be Windows 10 Enterprise LTSC 2021?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684ab805-b732-043b-9d4c-e8c02660557a
* Version Independent ID: 5c288d08-f2cb-3927-93cb-acb2412fc62c
* Content: [Windows 10 Enterprise LTSC - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/ltsc/)
* Content Source: [windows/whats-new/ltsc/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/ltsc/index.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by joinimran** [comment]
Hello @Luyeok - I have checked and found that this has been fixed. Thank you for reporting this. We are closing this now.

@e0i - FYI & A please.
