### ISSUE TITLE
LTSC 2019 referenced twice

### ISSUE THREAD

**Issue by mrecek** [MicrosoftDocs/windows-itpro-docs#10120]
The table references LTSC 2019 twice. Is this a typo? Should the second reference be LTSC 2021?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684ab805-b732-043b-9d4c-e8c02660557a
* Version Independent ID: 5c288d08-f2cb-3927-93cb-acb2412fc62c
* Content: [Windows 10 Enterprise LTSC - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/ltsc/#feedback)
* Content Source: [windows/whats-new/ltsc/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/ltsc/index.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
Created PR for this issue.
