### ISSUE TITLE
Windows 10 servicing schedule is still 18/30 moths not 24/36 months.

### ISSUE THREAD

**Issue by yukinork** [MicrosoftDocs/windows-itpro-docs#10125]
Please, look at
https://docs.microsoft.com/en-us/windows/release-health/release-information
and https://blogs.windows.com/windowsexperience/2021/11/16/how-to-get-the-windows-10-november-2021-update/
"Release cadence and support"
"As a second half (H2) of the calendar year release, Home and Pro editions of the November 2021 Update will receive 18 months of servicing and support, and Enterprise and Education editions will receive 30 months of servicing and support beginning today."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd214c3a-e3db-4f0b-6a7d-286aec8e0399
* Version Independent ID: fd214c3a-e3db-4f0b-6a7d-286aec8e0399
* Content: [What's new in Windows 10, version 21H2 for IT pros - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-21h2)
* Content Source: [windows/whats-new/whats-new-windows-10-version-21H2.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/whats-new-windows-10-version-21H2.md)
* Product: **w10**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@yukinork Thank you! This is fixed, and the article changes are live - [https://docs.microsoft.com/windows/whats-new/whats-new-windows-10-version-21h2](https://docs.microsoft.com/windows/whats-new/whats-new-windows-10-version-21h2). 

You can close this GitHub issue.

**Comment by yukinork** [comment]
It is still remain 24.  It shulud be 18.

**Comment by MandiOhlinger** [comment]
@yukinork You are correct. We missed that one. It's fixed now. Changes should be live sometime tomorrow. Thanks again for looking out.

**Comment by yukinork** [comment]
Thanks.  I checked.
