### ISSUE TITLE
LockoutHealTime: 10 minutes or 2 hours?

### ISSUE THREAD

**Issue by jpm-z** [MicrosoftDocs/windows-itpro-docs#10135]
[Enter feedback here]
It is INDISPENSABLE that you provide CLEAR and SIMPLE instructions as how to configure the TPM anti-hammering policy on computers that run current versions of Windows.
 
The page I'm coming from is typical of the rest of your fussy and incoherent documentation about TPM management in Windows.
I'm not sure many care whether some  reg value was 4 and now is 5 or whether the TPM owner password is retained by Windows anymore.
I'm sure many care about not being locked out of their own machine for 2 full hours by the first idiot that comes by a powered-down machine or a locked screensaver, and decides to have fun.

I can't understand this information is not available. Don't you see the problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92fdc530-003f-eb25-15a3-8622502e53d1
* Version Independent ID: 4c8edcb5-53c3-3242-6eca-5ac24f3f8c30
* Content: [Manage TPM lockout (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/manage-tpm-lockout)
* Content Source: [windows/security/information-protection/tpm/manage-tpm-lockout.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/tpm/manage-tpm-lockout.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @jpm-z - Thank you for your feedback. Can you please explain what exact content you are looking for that is missing in the document?
If you are expecting any change in the way TPM works with Windows, I would suggest you use the Rise your Voice portal to send the feedback to the engineering team.

@e0i - Please guide the user on how he can send feedback using Rise your Voice Portal.

Thanks.
Imran.
