### ISSUE TITLE
Windows 10 Enterprise Service period

### ISSUE THREAD

**Issue by Taogura001** [MicrosoftDocs/windows-itpro-docs#10132]
Is the information below correct? 

>Windows 10 Enterprise: Serviced for 36 months from the release date.

I think 36 months is wrong and 30 months is correct.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fd214c3a-e3db-4f0b-6a7d-286aec8e0399
* Version Independent ID: fd214c3a-e3db-4f0b-6a7d-286aec8e0399
* Content: [IT プロ向Windows 10バージョン 21H2 の新機能 - What's new in Windows](https://docs.microsoft.com/ja-jp/windows/whats-new/whats-new-windows-10-version-21h2)
* Content Source: [windows/whats-new/whats-new-windows-10-version-21H2.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-21H2.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@Taogura001 Thank you! This is fixed, and the article changes are live - [https://docs.microsoft.com/windows/whats-new/whats-new-windows-10-version-21h2](https://docs.microsoft.com/windows/whats-new/whats-new-windows-10-version-21h2). 

You can close this GitHub issue.
