### ISSUE TITLE
Windows 10 Enterprise LTSC 2019	defined as both 1809 and 21H2

### ISSUE THREAD

**Issue by Inthedriversseat** [MicrosoftDocs/windows-itpro-docs#10136]
Windows 10 Enterprise LTSC 2019	Windows 10, Version 21H2	11/16/2021 - Should be Windows 10 Enterprise LTSC 2021, correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684ab805-b732-043b-9d4c-e8c02660557a
* Version Independent ID: 5c288d08-f2cb-3927-93cb-acb2412fc62c
* Content: [Windows 10 Enterprise LTSC - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/ltsc/)
* Content Source: [windows/whats-new/ltsc/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/ltsc/index.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@Inthedriversseat Date is correct
