### ISSUE TITLE
A typo?

### ISSUE THREAD

**Issue by Eddddeee** [MicrosoftDocs/windows-itpro-docs#10137]
Windows 10 Enterprise LTSC **2019**	Windows 10, Version 21H2	11/16/2021 

seems to be

Windows 10 Enterprise LTSC **2021**	Windows 10, Version 21H2	11/16/2021

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684ab805-b732-043b-9d4c-e8c02660557a
* Version Independent ID: 5c288d08-f2cb-3927-93cb-acb2412fc62c
* Content: [Windows 10 Enterprise LTSC - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/ltsc/)
* Content Source: [windows/whats-new/ltsc/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/ltsc/index.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by THUYAAUNGOO** [comment]
ID: 684ab805-b732-043b-9d4c-e8c02660557a
Version Independent ID: 5c288d08-f2cb-3927-93cb-acb2412fc62c
Content: Windows 10 Enterprise LTSC - What's new in Windows
Content Source: windows/whats-new/ltsc/index.md
Product: w10
GitHub Login: @greg-lindsay
Microsoft Alias: greglin

**Comment by RAJU2529** [comment]
@Eddddeee . I already created PR to change

**Comment by e0i** [comment]
Fixed via https://github.com/MicrosoftDocs/windows-itpro-docs/commit/a732dbab3de3e84a70da3d8d0226ce78b79f73a2#diff-9a971568d44f3cfb549c02d8ae6a3e38d11b3c6769e8ab8b9976202a1018dac3
