### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by JNLlB** [MicrosoftDocs/windows-itpro-docs#10147]
Typo in https://docs.microsoft.com/en-us/windows/deployment/windows-10-missing-fonts#install-optional-fonts-manually-without-changing-language-settings: clselectick [should be either _click_ or _select_, not both] .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be28a6d0-e0e4-474a-e867-c57586643a4c
* Version Independent ID: 8a91809d-7edb-fbd0-96c3-f8e5487d338e
* Content: [How to install fonts missing after upgrading to Windows client - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-10-missing-fonts#install-optional-fonts-manually-without-changing-language-settings)
* Content Source: [windows/deployment/windows-10-missing-fonts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-missing-fonts.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@JNLlB  You are welcome to fix the typo by editing the article here: 

https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-missing-fonts.md

The article is going to be updated by independent contributors otherwise.

**Comment by tiburd** [comment]
I corrected the typo. Closing this issue.
