### ISSUE TITLE
Grammar issue/typo in "Windows Sybsystem for Linux" section in whats-new-windows-10-2021.md

### ISSUE THREAD

**Issue by cuiwc** [MicrosoftDocs/windows-itpro-docs#10146]
There seems to be a typo in Section `Windows Subsystem for Linux`:

> Windows Subsystem for Linux (WSL) **is be available** in-box.

Should be either `is available` or `will be available`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25d0f32-d5a9-0a30-21f2-3ae1beaaf3c1
* Version Independent ID: a25d0f32-d5a9-0a30-21f2-3ae1beaaf3c1
* Content: [What's new in Windows 10 Enterprise LTSC 2021 - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/ltsc/whats-new-windows-10-2021)
* Content Source: [windows/whats-new/ltsc/whats-new-windows-10-2021.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/ltsc/whats-new-windows-10-2021.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by Lovygoogle** [comment]
`
![Screenshot_20211025_170330_com sec android app sbrowser~2](https://user-images.githubusercontent.com/94048360/143272886-747472db-e09d-4b37-b787-5e4c84cea491.jpg)
`

**Comment by Lovygoogle** [comment]
![Screenshot_20211023_020247_com pinterest~11](https://user-images.githubusercontent.com/94048360/143328894-817f6020-87e6-481a-a820-8dc8868490e5.jpg)
![Screenshot_20211023_020247_com pinterest~10](https://user-images.githubusercontent.com/94048360/143328908-58f49436-deec-46aa-9b6a-1494d338e110.jpg)

**Comment by e0i** [comment]
@cuiwc You are welcome to fix the typo by editing the article here: https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/ltsc/whats-new-windows-10-2021.md

The article is going to be updated by independent contributors otherwise.

Thanks.

**Comment by cuiwc** [comment]
Thanks, @e0i . 

I'd be happy to submit a PR if I know for sure which statement, "is available" or "will be available", holds true for this topic. Unfortunately I don't have the answer, and actually that's why I came across this issue in the document when I try to look for WSL support in Windows 10 LTSC 2021.

Anyway, I don't prefer picking one randomly, hope someone from Microsoft would help clarify that. 

Thanks
Wenchao
