### ISSUE TITLE
Manual Restart?

### ISSUE THREAD

**Issue by NFC153** [MicrosoftDocs/windows-itpro-docs#10149]
I always used to restart manually, as and when convenient. Is this still an option? It isn't clear from this page nor from the options offered on upgrade.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184809a-63ff-ecc2-ab67-9c9f4df900f8
* Version Independent ID: ac25ee6c-4c57-58b3-1313-e4a53f53c5a1
* Content: [Manage device restarts after updates (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-restart#feedback)
* Content Source: [windows/deployment/update/waas-restart.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-restart.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@arcarley can you advise?

**Comment by e0i** [comment]
@arcarley Please let me know if independent contributors can help with this issue in any way. Thanks.

**Comment by aczechowski** [comment]
I'm going to close this issue. I think Aria answered the question: you have to restart after updating, and there are multiple ways of getting there. This article is specifically about _managing_ that experience in an organization. While manual restart is always an option, that's not something you can manage at scale. This article covers the basics of the end-user experience: https://support.microsoft.com/windows/manage-updates-in-windows-643e9ea7-3cf6-7da6-a25c-95d4f7f099fe#WindowsVersion=Windows_11
