### ISSUE TITLE
Where are the docs for Cloud Trust hybrid deployment?

### ISSUE THREAD

**Issue by robmacf** [MicrosoftDocs/windows-itpro-docs#10144]
Windows 10 21H2 was released. This is the Windows release that enabled Windows Hello for Business Cloud Trust hybrid deployments.

https://blogs.windows.com/windowsexperience/2021/07/15/introducing-the-next-feature-update-to-windows-10-21h2/

Where are the docs for Cloud Trust hybrid deployment model? This page mentions that more information will be available... "Windows Hello for Business is introducing a new trust model called cloud trust"

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e5f5f1-16cf-57e2-bdfc-b090d90437b1
* Version Independent ID: 1662c47f-12cb-147d-25f0-dee98b6c7722
* Content: [Windows Hello for Business Deployment Prerequisite Overview - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-identity-verification.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-identity-verification.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mapalko** [comment]
This feature was delayed from 21H2 and is now targeting early 2022 for release. This will be in a patch to Windows 10 21H2. There is a note under Hybrid deployments section of this page indicating the delay. The docs will be updated with deployment information when the functionality ships.
