### ISSUE TITLE
Block Outbound Telnet Example Typo

### ISSUE THREAD

**Issue by robdew** [MicrosoftDocs/windows-itpro-docs#1014]
[Enter feedback here]

I believe this:

````powershell
New-NetFirewallRule -DisplayName “Allow Inbound Telnet” -Direction Inbound -Program %SystemRoot%\System32\tlntsvr.exe -RemoteAddress LocalSubnet -Action Allow –Group “Telnet Management”
New-NetFirewallRule -DisplayName “Block Outbound Telnet” -Direction Inbound -Program %SystemRoot%\System32\tlntsvr.exe -RemoteAddress LocalSubnet -Action Allow –Group “Telnet Management”
````

Should read:

````powershell
New-NetFirewallRule -DisplayName “Allow Inbound Telnet” -Direction Inbound -Program %SystemRoot%\System32\tlntsvr.exe -RemoteAddress LocalSubnet -Action Allow –Group “Telnet Management”
New-NetFirewallRule -DisplayName “Block Outbound Telnet” -Direction Outbound -Program %SystemRoot%\System32\tlntsvr.exe -RemoteAddress LocalSubnet -Action Block –Group “Telnet Management”
````
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e5a8b81-2950-e0df-e726-4d85b7a149ea
* Version Independent ID: f7784b48-0ab1-11df-8463-9083eaf2a3c1
* Content: [Windows Defender Firewall with Advanced Security Administration with Windows PowerShell (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/windows-firewall/windows-firewall-with-advanced-security-administration-with-windows-powershell)
* Content Source: [windows/security/identity-protection/windows-firewall/windows-firewall-with-advanced-security-administration-with-windows-powershell.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/windows-firewall/windows-firewall-with-advanced-security-administration-with-windows-powershell.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@robdew Thanks for the correction. This is fixed now. If you see other errors, click Edit in the upper right, then click the pencil icon in upper right, make the edit and click Commit changes. That way you are added as a contributor.
