### ISSUE TITLE
Trusted Platform Module Services: Turn on TPM backup to Active Directory Domain Services

### ISSUE THREAD

**Issue by santoshseth** [MicrosoftDocs/windows-itpro-docs#1015]
This setting has been removed since Windows 10 1607, please update the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d1e77d9-00eb-7907-08ba-ddb5557fa51e
* Version Independent ID: 5a0a4a51-0bea-a266-1796-f21918cd04e2
* Content: [Prepare your organization for BitLocker Planning and policies (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/prepare-your-organization-for-bitlocker-planning-and-policies#bkmk-addscons)
* Content Source: [windows/security/information-protection/bitlocker/prepare-your-organization-for-bitlocker-planning-and-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/prepare-your-organization-for-bitlocker-planning-and-policies.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@santoshseth Thanks for pointing this out. I took out the TPM policy info.

**Comment by Sidans** [comment]
Hello
Could some one please post the working GPO for windows 10 and bitlocker to AD.
we use TPM and UEFI.
thanks

**Comment by Justinha** [comment]
> Hello
> Could some one please post the working GPO for windows 10 and bitlocker to AD.
> we use TPM and UEFI.
> thanks

take a look here: https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings#a-href-idbkmk-rec3astore-bitlocker-recovery-information-in-active-directory-domain-services-windows-server-2008-and-windows-vista

**Comment by Sidans** [comment]
Hello
thank you for the information, but the only section that talks about storing Bitlocker key to AD applies to windows 2008 and vista:
[cid:04fca661-d96b-493c-8e40-36882cf72883]
________________________________

**Comment by Justinha** [comment]
@Sidans my bad, here it is: https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings#a-href-idbkmk-rec1achoose-how-bitlocker-protected-operating-system-drives-can-be-recovered

See the notes below the table for info about storing to AD on prem.

**Comment by Sidans** [comment]
Hello
I still don't see it
could you give me an exact keyword that I can search on the page.
it still looks the same as previous link
thanks

________________________________

**Comment by Justinha** [comment]
The policy name is Choose how BitLocker-protected operating system drives can be recovered. In the Reference section below the table, it says:
In Save BitLocker recovery information to Active Directory Domain Services, choose which BitLocker recovery information to store in Active Directory Domain Services (AD DS) for operating system drives. If you select Store recovery password and key packages, the BitLocker recovery password and the key package are stored in AD DS. Storing the key package supports recovering data from a drive that is physically corrupted. If you select Store recovery password only, only the recovery password is stored in AD DS.

The link I shared will take you right to the correct setting name. Or just click Start > Edit Group Policy and navigate to Computer Configuration\Administrative Templates\Windows Components\BitLocker Drive Encryption\Operating System Drive and you can see the setting there. The option to save recovery info to AD DS is in a pull-down menu.

**Comment by Sidans** [comment]
thanks
________________________________
