### ISSUE TITLE
The "RuleCollectionExtensions" und er the DLL section seem to be missing the Redstone Extensions.

### ISSUE THREAD

**Issue by marcushms** [MicrosoftDocs/windows-itpro-docs#10152]
The "RuleCollectionExtensions" und er the DLL section seem to be missing the Redstone Extensions.

This one should be correct:
 <RuleCollection Type="Dll" EnforcementMode="AuditOnly" >
:
:
    <RuleCollectionExtensions>
      <ThresholdExtensions>
        <Services EnforcementMode="Enabled" />
      </ThresholdExtensions>
      <RedstoneExtensions>
        <SystemApps Allow="Enabled"/>
      </RedstoneExtensions>
    </RuleCollectionExtensions>
:
:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d9a0607-b206-fab3-ef68-9de7c7e6a072
* Version Independent ID: 9ca53978-51c8-d2e1-c6a4-4b0a19bac244
* Content: [Allow apps deployed with a WDAC managed installer (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by bevanm8** [comment]
Could someone please explain to me how to add the "RedstoneExtensions" to my AppLocker XML? The post above isn't showing for me, and I can't figure it out for the life of me. The Set-AppLockerPolicy command throws an error without it. It took me a long time to find this post.. there's really nothing about this online.

**Comment by joinimran** [comment]
Hello @marcushms & @bevanm8 - Sorry for the trouble you got in. I have just checked and found in the document that <RedstoneExtensions>
</RedstoneExtensions>
are the part of the XML content and are described where it should be. Hope this will you solve your problem.

![image](https://user-images.githubusercontent.com/47118050/150946010-2c4fd408-098a-43aa-9e2e-5b839d2d9ce5.png)

@e0i - FYI & A Please.
