### ISSUE TITLE
DynamicManagement CSP : Regarding all possible trigger XML and their schema.

### ISSUE THREAD

**Issue by harishankar-gopalan** [MicrosoftDocs/windows-itpro-docs#1016]
Team, the document does not provide us with an exhaustive list of values which can be used for the SignalDefinition node. Also the DTD schema of the inner XML's is not provided blinding us out of all the intricacies of control that this CSP provides us. Request you to rectify the docs to address the above issues.
I had raised this to dochelp too and have been informed that the product team has been notified regarding the same. Request you to take ahead and do the required changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 482379e4-551a-fa09-9b8e-2dff29df7708
* Version Independent ID: 4982635e-c3fa-afef-e4d8-3941f391c4a1
* Content: [DynamicManagement CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/dynamicmanagement-csp)
* Content Source: [windows/client-management/mdm/dynamicmanagement-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/dynamicmanagement-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by TokyoScarab** [comment]
Hello @harishankar-gopalan , thank you for bringing this up!  This is being worked on and looked into.  The documentation will be changed to reflect this.

**Comment by mypil** [comment]
@ManikaDhiman - Can you please share your insights on how we can address this issue? Thank you.

**Comment by mypil** [comment]
@harishankar-gopalan - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via [Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
