### ISSUE TITLE
The minimum size of TPM NV 0x01C101C0

### ISSUE THREAD

**Issue by trchen1033** [MicrosoftDocs/windows-itpro-docs#10164]
The minimum size of NV 0x01C101C0 is unclear from the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31d623d9-316c-0ef1-b6be-c3773d77ca21
* Version Independent ID: 83ddb59d-0cfc-34f2-e666-8927d86a04a7
* Content: [System Guard Secure Launch and SMM protection (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection#system-requirements-for-system-guard)
* Content Source: [windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@e0i   Created PR #10167 for a different issues.
