### ISSUE TITLE
Link question

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/windows-itpro-docs#10172]
Is this supposed to be Copy PolicyDefinitions folder to \contoso.com\SYSVOL\contoso.com\policies\PolicyDefinitions or Copy PolicyDefinitions folder to \\contoso.com\SYSVOL\contoso.com\policies\PolicyDefinitions.

Supposed to be \ or \\ before the first contoso.com.  Another Microsoft doc shows it as \\.  

It doesn't say it here, but the other document says that it should be our domain name\SYSVOL.  Is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy#configure-the-auto-enrollment-for-a-group-of-devices)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @rconiv - Thank you for your query. Please note that information mentioned in step 5 **Copy PolicyDefinitions folder to \SYSVOL\contoso.com\policies\PolicyDefinitions** is correct. You need to copy the PolicyDefinitions folder to \SYSVOL\contoso.com\policies\PolicyDefinitions. Adding \ before the domain is to give the path idea for the end-user. SYSVOL paths areas:

- \SYSVOL
- \SYSVOL\domain
- \SYSVOL\staging\domain
- \SYSVOL\staging areas
- \SYSVOL\domain\Policies
- \SYSVOL\domain\scripts
- \SYSVOL\SYSVOL 

Visit https://support.microsoft.com/en-us/topic/04fc119e-295f-a556-9d7c-616796e96d5d to get more idea how the SYSVOL folder works and what needs to be taken into consideration.

Thanks.
Imran.

@e0i - FYI&A Pleaes.
