### ISSUE TITLE
Fix broken link

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/windows-itpro-docs#10170]
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis is broken (404) please change to https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/report-junk-email-messages-to-microsoft

Also note the section on manually submitting phish/junk to individual email addresses is removed from the target article. Consider removing from this page as well, if the (non-email) Admin/User submission methods are preferred and supported.

**Comment by RAJU2529** [comment]
@hudish  which Article are you referring to?

**Comment by hudish** [comment]
Apologies. https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/phishing

**Comment by RAJU2529** [comment]
@hudish , Thanks changed to new link.

**Comment by denisebmsft** [comment]
Thank you @hudish for raising this issue, and thank you @RAJU2529 for the fix. The pull request is merged and the updates will be live a little later this morning (around 11 Pacific Time).
