### ISSUE TITLE
Unable to enable Hardware Bitlocker in Windows 11

### ISSUE THREAD

**Issue by 3rg0n** [MicrosoftDocs/windows-itpro-docs#10179]
Following all the steps by both Samsung and Microsoft and Lenovo. I am unable to enabled hardware bitlocker as I have previously been able to on old generation hardware. Lenovo P1 Gen 3 hardware I am able to enable hardware bitlocker, however, on Lenovo X1 Carbon Gen 9 and P1 Gen 4 laptops I am unable to.

I also found that bitlocker worked in 1803 but anything newer fails, but even that on new hardware isn't working. I wish there was a step-by-step guide on how to enable Hardware Bitlocker.

I have a samsung 980 pro and it's simply not possible to do this. Even disabling auto encryption feature in windows by turning off modern standby in the BIOS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13a08c67-da5c-eef5-2ef8-a0613cb3a862
* Version Independent ID: 187b47b0-d2fb-a5b5-c28c-14a850e69416
* Content: [Encrypted Hard Drive (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/information-protection/encrypted-hard-drive)
* Content Source: [windows/security/information-protection/encrypted-hard-drive.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/encrypted-hard-drive.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@3rg0n . you should post your questions in below forum.
https://answers.microsoft.com/en-us/windows/forum/windows_11-security?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1
