### ISSUE TITLE
Credential Guard Requirements should list supported editions of Windows

### ISSUE THREAD

**Issue by alexometis** [MicrosoftDocs/windows-itpro-docs#10185]
This page has lots of information on requirements for Credential Guard but it doesn't mention which editions of Windows it's supported on. From reading elsewhere I _think_ that it's only available on Enterprise (not Business or Home) but I'd expect that to be clearly stated here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0238a73f-da06-ae17-c61d-85ae54e0f7cb
* Version Independent ID: e5bb4a25-a7c3-3a16-bd95-d6f2513402e0
* Content: [Windows Defender Credential Guard Requirements (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-requirements)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-requirements.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@alexometis . Windows 10  /11  Professional and Enterprise editions

**Comment by RAJU2529** [comment]
@e0i . I will add Windows 10 Professional, Enterprise editions and Windows 11 Professional, Enterprise editions in this article

**Comment by RAJU2529** [comment]
@e0i I am going to edit this article now.

**Comment by MaratMussabekov** [comment]
Hello @alexometis , unfortunately it only supports Windows 10 Enterprise edition.
Thank you
