### ISSUE TITLE
代码里的中文冒号要改成英文

### ISSUE THREAD

**Issue by Zhenyi-Wang** [MicrosoftDocs/windows-itpro-docs#10183]
子类别 GUID： 唯一的子类别 GUID。 若要查看子类别 GUID，可以使用此命令 ：auditpol /list /subcategory：* /v

这一句，代码中的冒号是中文的，直接复制执行报错，要改成英文冒号

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3b17394e-f264-534c-d762-81355e57ecc1
* Version Independent ID: eaf96ee2-5102-cbd3-85dc-483c59e55aac
* Content: [4719 (S) 系统审核策略已更改。 (Windows 10) - Windows security](https://docs.microsoft.com/zh-cn/windows/security/threat-protection/auditing/event-4719)
* Content Source: [windows/security/threat-protection/auditing/event-4719.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/event-4719.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
@TinaMcN can you take a look at this issue?

**Comment by TinaMcN** [comment]
@Zhenyi-Wang 感谢您报告此问题。这似乎是我们的机器翻译工具的问题。我把这篇文章寄给了人工翻译，应该在一周内完成。
你的意思是这个冒号是不正确的吗？ (Thank you for reporting this issue. It appears to be a problem with our machine translation tool. I sent the article to be human translated and it should be completed within a week.
Do you mean that this colon is incorrect?)
![image](https://user-images.githubusercontent.com/53281468/144898267-128b3bfe-47ef-47d4-b3c1-4d2eb2436227.png)

**Comment by Zhenyi-Wang** [comment]
> @Zhenyi-Wang 感谢您报告此问题。这似乎是我们的机器翻译工具的问题。我把这篇文章寄给了人工翻译，应该在一周内完成。 你的意思是这个冒号是不正确的吗？ (Thank you for reporting this issue. It appears to be a problem with our machine translation tool. I sent the article to be human translated and it should be completed within a week. Do you mean that this colon is incorrect?) ![image](https://user-images.githubusercontent.com/53281468/144898267-128b3bfe-47ef-47d4-b3c1-4d2eb2436227.png)

不，第二个冒号，代码里的
`/subcategory：*`

**Comment by Zhenyi-Wang** [comment]
> @Zhenyi-Wang 感谢您报告此问题。这似乎是我们的机器翻译工具的问题。我把这篇文章寄给了人工翻译，应该在一周内完成。 你的意思是这个冒号是不正确的吗？ (Thank you for reporting this issue. It appears to be a problem with our machine translation tool. I sent the article to be human translated and it should be completed within a week. Do you mean that this colon is incorrect?) ![image](https://user-images.githubusercontent.com/53281468/144898267-128b3bfe-47ef-47d4-b3c1-4d2eb2436227.png)

不，第二个冒号，代码里的
`/subcategory：*`

**Comment by TinaMcN** [comment]
中文文章中的代码是：
![image](https://user-images.githubusercontent.com/53281468/144945202-5eb92e75-2580-4006-915e-43b34dfbcf51.png)

英文文章中的代码是：
![image](https://user-images.githubusercontent.com/53281468/144945287-c6bfa70f-c57f-4d0c-af94-2268b8cdc049.png)

你的意思是英文文章也错了吗？  (Do you mean the English article is wrong also?)

正确的代码应该是什么？ (What should the correct code be?)

**Comment by Zhenyi-Wang** [comment]
> 

英文的是正确的，请注意中文文章中的冒号和英文文章中是不一样的，可能是机器翻译的关系，变成了中文的冒号，虽然视觉上差不多，但直接复制到cmd是无法执行的，英文文章中的应该没有问题

**Comment by Zhenyi-Wang** [comment]
中文的冒号：
英文的冒号:

**Comment by TinaMcN** [comment]
感谢您的回复。  人工翻译应在一周内完成。 然后让我们检查一下它是否已修复。 (Thanks for your reply.   The human translation should be completed within a week.  Let's check then to see if it's fixed.)

**Comment by TinaMcN** [comment]
@Zhenyi-Wang 这篇文章现在是人工翻译的。 您能确认问题现在是否已解决吗？(The article is now human translated.  Can you please confirm if the problem is fixed now?)
![image](https://user-images.githubusercontent.com/53281468/145897386-0d5fbcf2-ef1f-4e5a-b371-5afea4e964d5.png)
