### ISSUE TITLE
Info missing from before you begin

### ISSUE THREAD

**Issue by Nils-Berghs** [MicrosoftDocs/windows-itpro-docs#10184]
[Enter feedback here]
The 'Before you Begin' section misses an important piece of information: _Before you begin, make sure that the keyboard and mouse settings of the helper PC match those of the shares' PC_ 

I know it is mind bogling that someone actually implemented it this bad, but thats how it is so at least document it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfcd14cd-f887-660f-8a4c-465b3495e90e
* Version Independent ID: 121eead7-eb87-f033-024a-f688866c58a0
* Content: [Use Quick Assist to help users - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/quick-assist#feedback)
* Content Source: [windows/client-management/quick-assist.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/quick-assist.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment]
@e0i , What you think about suggestion given by @Nils-Berghs . I accept his suggestion. And i like to add in this article.

**Comment by jaimeo** [comment]
I think this could use some clarification--what exactly does it mean to have the keyboard and mouse settings match between the two PCs? Do they have to be the same model keyboard and mouse?

**Comment by e0i** [comment]
Under review. @RAJU2529 You are welcome to come up with updates in accordance with mapalko's feedback until I pass this to another contributor. Thanks.

**Comment by Nils-Berghs** [comment]
@jaimeo  what I mean is that the keyboard layout of the sharers and the helpers PC must match, for example if you share your PC with me, and I would for example type taskmgr in the run box there would appear 'tqsk,gr' (assuming that you use US Querty).

The same thing for the mouse I'm left handed and use my mouse like that, but if I do a primary mouse click this is passed to the shares PC as a 'right click' which is a secondary click on most systems.

I think the documentation should at least mention this.

**Comment by jaimeo** [comment]
You're absolutely right that the article should mention that! So it's the locale/language settings primarily that must match, is that right? (Though you did mention the mouse.) I ask because when we fix the article we should be very explicit for maximum clarity.

**Comment by Nils-Berghs** [comment]
@jaimeo the language/regional settings are not necessarely linked to the keyboard layout. You can have to PC's with the same language /regional settings but still different keyboards (e.g. people who moved to a different country but still use the keyboard they grew up with, or someone using a "better" layout like dvorak or colemak)

As for the mouse that is totally unrelated to country. I see this more as an accessibility feature ( and a lack of care from MS on this topic).

**Comment by RAJU2529** [comment]
@e0i, the Author @jaimeo  has to decide whether to add suggestions in this article, because here conversation is going on.

**Comment by jaimeo** [comment]
I'm no longer a writer, but I've let the manager for the area know and have engaged the PM for QuickAssist, who is getting set up with GitHub and then will be able to help directly with this.

**Comment by RAJU2529** [comment]
@jaimeo . Thanks for your reply. I hope this issue will be fixed very soon

**Comment by MaratMussabekov** [comment]
Dear @Nils-Berghs ,
please have a look at #10248 
Thank you
