### ISSUE TITLE
Hyperlink

### ISSUE THREAD

**Issue by harsco01** [MicrosoftDocs/windows-itpro-docs#1018]
'Surface Hub Site Readiness Guide' doesn't work, get below error.

We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36fa9e87-5664-70e8-e012-6aa6d94fc1e6
* Version Independent ID: 0bf1725e-5df5-4da2-0825-a86ec97afee9
* Content: [Device reset (Surface Hub)](https://docs.microsoft.com/en-us/surface-hub/device-reset-surface-hub)
* Content Source: [devices/surface-hub/device-reset-surface-hub.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/device-reset-surface-hub.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@harsco01 Thank you for catching that and letting us know! We'll get that link fixed today.
