### ISSUE TITLE
Making a Gui based off this script

### ISSUE THREAD

**Issue by greenmoonconsulting** [MicrosoftDocs/windows-itpro-docs#10180]
[Enter feedback here]
Greetings! Not sure how to contact the authors of this script. im creating a gui frontend, based off this script. i started this because i was having trouble getting memory integrity turned on. Didn't know anything about any of these security features a few days ago.  So i decided to make visual representation so i could picture what security features are dependent on to troubleshoot them. i feel i have most of your features implemented although i could use your help and clarity on some terms and commands. im not sure if this is the best way to communicate with the authors.  thank you, joe,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c12e9c4a-af05-9ecd-a791-ac89aa43787c
* Version Independent ID: 76517523-a960-c5fb-ce76-2c3efe642f37
* Content: [Windows Defender Device Guard and Windows Defender Credential Guard hardware readiness tool - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg-readiness-tool)
* Content Source: [windows/security/identity-protection/credential-guard/dg-readiness-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/dg-readiness-tool.md)
* Product: **m365-security**
* GitHub Login: @SteveSyfuhs
* Microsoft Alias: **stsyfuhs**

**Comment by RAJU2529** [comment]
@greenmoonconsulting  you can post your questions and queries on answers.microsoft.com
