### ISSUE TITLE
Unconfigured for PIN complexity should be "can not", not "cannot"

### ISSUE THREAD

**Issue by cdwiegand** [MicrosoftDocs/windows-itpro-docs#10193]
`Not configured: Users cannot include a special character in their PIN.` under PIN Complexity (for all 4 entries containing this text - lowercase, uppercase, numbers, and special characters) should actually read `Not configured: Users can not include a special character in their PIN.` or even better `Not Configured: Users are not required to include a special character in their PIN but may do so.` - unconfigured does not require or prohibit these options for the user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 789566d4-463a-4c64-bf89-fb963ac29f80
* Version Independent ID: 02946732-bb29-d8e6-cedd-7f5e508f8798
* Content: [Manage Windows Hello in your organization (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-manage-in-organization)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-manage-in-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-manage-in-organization.md)
* Product: **m365-security**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by RAJU2529** [comment]
@cdwiegand . Thanks for your feedback.  I will investigate

**Comment by RAJU2529** [comment]
@e0i  I am going to edit this article now.

**Comment by e0i** [comment]
Thank you, @RAJU2529
