### ISSUE TITLE
It Worked For Me

### ISSUE THREAD

**Issue by itsoriki** [MicrosoftDocs/windows-itpro-docs#10197]
I have tried resetting the windows update components agent using `net stop wuauserv` command, then deleting the SoftwareDistribution folder manually and restarting the agent using `net start wuauserv`.

I am using the latest Windows 11 version and the solution actually worked for me - **thank you very much!**

---
#### פרטי המסמך

⚠ *אין לערוך מקטע זה. פעולה זו נדרשת עבור קישור לנושאים ב- docs.microsoft.com ← GitHub.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/he-il/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment]
@itsoriki > Thanks for the confirmation, solution is mentioned in this article is worked for you too. 
All article authors are having technical knowledge including windows troubleshooting practical skills, so the solutions will work.

**Comment by RAJU2529** [comment]
@e0i , Write your comment to @itsoriki  and close it.
