### ISSUE TITLE
Conflicting information

### ISSUE THREAD

**Issue by moderor** [MicrosoftDocs/windows-itpro-docs#10208]
The prerequisite section of this documentation states that the subject name of the domain controller certificate should be the distinguished name, but the example domain controller template has this set to none. Which is the correct advice?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800b8090-65a9-da9f-a930-1f80dc9f2c2d
* Version Independent ID: b4495b6a-4ca5-7aa1-7964-ef6e19275c4e
* Content: [Configure Hybrid Azure AD joined key trust Windows Hello for Business - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md)
* Product: **m365-security**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by RAJU2529** [comment]
Investigation is needed

**Comment by MaratMussabekov** [comment]
Hello @moderor ,
both will work, subject is optional there, DNS as SAN is mandatory.
I will create PR to fix it.
Thank you
