### ISSUE TITLE
TPM 2.0 anti-hammering - described configuration values do not match actual values

### ISSUE THREAD

**Issue by wmjdgla** [MicrosoftDocs/windows-itpro-docs#10206]
> the TPM is configured by Windows to lock after 32 authorization failures and to forget one authorization failure every two hours.

Running `get-tpm` in powershell shows that the values are now:
```
LockoutHealTime           : 10 minutes
LockoutMax                : 31
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce559218-f2fb-e503-d839-422b0253154f
* Version Independent ID: d459f091-3ce6-f2c3-ca41-b9477d390a7e
* Content: [Trusted Platform Module (TPM) fundamentals (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/tpm-fundamentals)
* Content Source: [windows/security/information-protection/tpm/tpm-fundamentals.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/tpm/tpm-fundamentals.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @wmjdgla ,
yes, it was decreased to 10 min since Windows 10 1703, I created a PR to update the article.
Thank you

**Comment by wmjdgla** [comment]
> lock after 32 authorization failures
@MaratMussabekov I think you missed it out? `LockoutMax` is now 31.
