### ISSUE TITLE
reconfigure 

### ISSUE THREAD

**Issue by azammajid** [MicrosoftDocs/windows-itpro-docs#10202]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ad101fb-4701-91b8-4e2e-0b01979b6d46
* Version Independent ID: e51df428-cc54-5424-b016-c04dd591f6f9
* Content: [Windows 10, version 21H2, Windows 10, version 21H1, Windows 10, version 20H2 and Windows 10, version 2004 required diagnostic events and fields (Windows 10) - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/required-windows-diagnostic-data-events-and-fields-2004)
* Content Source: [windows/privacy/required-windows-diagnostic-data-events-and-fields-2004.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/required-windows-diagnostic-data-events-and-fields-2004.md)
* Product: **m365-security**
* Technology: **privacy**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by RAJU2529** [comment]
@e0i , No proper feedback so please close this issue #10202
