### ISSUE TITLE
"For details on how to run these and how to check results, see the deployment script."

### ISSUE THREAD

**Issue by Scoobysnax97** [MicrosoftDocs/windows-itpro-docs#1021]
The deployment script doesn't detail how to check the results of running the commands independently.   What kind of events are generated and where are they logged?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4273a259-c3c7-dca7-6353-954068d740a7
* Version Independent ID: 1084ea77-95c4-4e4a-da6c-f4d8668f9ebf
* Content: [Enrolling devices in Windows Analytics (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started)
* Content Source: [windows/deployment/update/windows-analytics-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-get-started.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
See https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-deployment-script, where it says "Log files are created in the drive that is specified in the RunConfig.bat file. By default this is set to: %SystemDrive%\UADiagnostics." That topic also has a section listing the exit codes.

**Comment by andreabichsel** [comment]
@jaimeo, can you investigate?

**Comment by jaimeo** [comment]
I'm sorry I misunderstood your question. I've also run it by the PM for this area and we're still not totally sure exactly what you're asking for. However:

* if you are looking for the results of each check that the deployment script runs, the location and exit codes for that are in the topic I referred you to.

* if you are looking for diagnostic data events that are logged when CompatTelRunner.exe is run by the deployment script, those are viewable by using the Diagnostic Data Viewer. Documentation for that is at https://docs.microsoft.com/en-us/windows/privacy/diagnostic-data-viewer-overview.

If we're still misunderstanding what you need, please feel free to clarify further.

**Comment by miaminemo** [comment]
Could anyone clarify which OS WAUR is supported for data collection on? Specifically can WAUR data be collected from server 2008, 2012 or 2016 devices?

**Comment by jaimeo** [comment]
I'm not exactly sure what you mean by "WAUR," but if you're referring to Upgrade Readiness, it does not monitor Windows Server at all. See https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-requirements.

**Comment by miaminemo** [comment]
@jaimeo - WAUR - Windows Analytics Upgrade Readiness is how our PFE always referred to it. The question I am trying to answer is whether we could gather office add-in information (https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-additional-insights#office-add-ins )  from users who work in a server OS environment. My initial inclination was to say no, but this PFE blog talks about how the deployment script could be targeted to server 2008:
https://blogs.technet.microsoft.com/askpfeplat/2018/07/02/deploying-upgrade-readiness-without-sccm/ 
Does that provide any clarity to the question?

**Comment by jaimeo** [comment]
Yeah, I kind of figured that. :^) . However, "WAUR" is not an acronym we use, so the PFEs should refrain from that. Can you clarify what you mean by "server OS environment"? Do you have users running Windows Server with Desktop Experience who then have Office + Office add-ins installed on those devices? To the best of my knowledge, Windows Analytics won't tell you anything about devices running Windows Server at all, so in an environment with both Windows 10 (or 7 or 8) and Windows Server, you can monitor the former devices but not the latter. I'll double-check with the PMs though....

**Comment by miaminemo** [comment]
The latter is what I am asking about... user who may RDS into a server for a VDI experience with office and add-ins installed.... Can UR run in such an environment and report the usage/installation date to Azure...

**Comment by zdvorak** [comment]
No, unfortunately UR does not support Server SKUs.  Due to differences in the diagnostic data that is collected from servers, you won't be able to see these devices in the Upgrade Readiness portal.  However, we do have the [Readiness Toolkit for Office](https://docs.microsoft.com/en-us/deployoffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro) which can be used to assess add-in and macro compatibility on Servers running Office.

**Comment by jaimeo** [comment]
Thanks Zach! I'll look into updating these topics to more clearly explain the situation with Windows Server.

**Comment by mypil** [comment]
@Scoobysnax97 - From our understanding, the issue has been answered by jaimeo. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
