### ISSUE TITLE
Add information about Intune/AzureAD calculated SIDs

### ISSUE THREAD

**Issue by Ross-Y** [MicrosoftDocs/windows-itpro-docs#10212]
Hello,
It would be nice to add information about Intune / Azure AD calculated SIDs, which start with S-1-12-1 . You could also add script example to calculate Azure ObjectID into SID and vice versa.
Thank you,
Ross

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af0ec4a3-6f79-33d7-adab-0000742fc992
* Version Independent ID: db89d5e2-f49f-bf65-f583-a9545e6fe0bb
* Content: [Security identifiers (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/security-identifiers)
* Content Source: [windows/security/identity-protection/access-control/security-identifiers.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/access-control/security-identifiers.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @Ross-Y ,
**It would be nice to add information about Intune / Azure AD calculated SIDs** - as far as I know, there are no well-known SIDs of Azure AD objects. Anyways, the article is only applicable to Windows 10 and Windows Server (which includes AD), it doesn't cover Azure AD.
**You could also add script example to calculate Azure ObjectID into SID and vice versa.** - there are some scripts in the Internet that could be used for this purpose, however, none of them was officially confirmed by Microsoft (therefore cannot be added to the documentation). Officially, it could be done using [Microsoft Graph API only](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0)

Thank you

**Comment by Ross-Y** [comment]
Hello @MaratMussabekov ,

Yes, it doesn't seem like there are well-known SIDs in Intune. I was only asking to consider adding a paragraph in the article, which will say that SIDs prefixed with S-1-12-1 are related to Intune. Because it is really confusing to see those SIDs on Windows 10 machines and not being able to find anything in the documentation on where they come from. These SIDs do not exist in Azure as an attribute on the objects, or at least they are not visible (nor GUI, neither powershell). I believe this article is the best place for such information, as it explains SIDs and talks about different SIDs categories, e.g. "capability SIDs".

If you find another article to be more relevant - then by all means, a piece of information about Intune SIDs can be shared there. As much as you can - since there are scripts to calculate SID from Azure Object GUID, it may be mentioned that they are calculated and numbers in sub-authority sections are not exactly sub-authorities, just like the last section is not exactly RID anymore. It will help administrators better understand what they see and how to configure those groups. It will also help to resolve those SIDs, as long as there doesn't seem to be any official guidance on how to resolve them. And it is scary to find some strange SIDs on all machines.

Thank you and best regards

**Comment by MaratMussabekov** [comment]
Hello, I believe it should be added there - [SID_IDENTIFIER_AUTHORITY](https://docs.microsoft.com/ru-ru/openspecs/windows_protocols/ms-dtyp/c6ce4275-3d90-4890-ab3a-514745e4637e).
It should be described with **{0x00, 0x00, 0x00, 0x00, 0x00, 0x1B}**, meaning **"Specifies the Azure Active Directory authority. It defines SIDs of Azure Active Directory objects."**, and placed between SECURITY_NT_AUTHORITY and SECURITY_APP_PACKAGE_AUTHORITY.
Dear @e0i, I cannot create PR for this article, is it possible to address it to the appropriate team?
Thank you

**Comment by aczechowski** [comment]
I sent a request to the owner of the OpenSpec. There's not much else we can do at this point, so I'm going to close this issue.
