### ISSUE TITLE
User cannot download app from the portal

### ISSUE THREAD

**Issue by Daveliddle** [MicrosoftDocs/windows-itpro-docs#1022]
I'm our MS Store for Business admin.  I have a user I am trying to publish an app to via the portal.  We are all on the same O365/AzureAD tenant.  I have assigned his account to the app.  He can sign-in to the Business Store, he can see the published app.  He clicks to install the app and is then prompted for his account.  This is defaulted to his domain account but it produces an error.  Another colleague who is tenant admin follows the same process and his works okay.  We've checked GPO, we ran wsreset.exe and we've tried different credentials but it won't let him download the ONLINE app.  Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e62232-54ab-fa9d-1e31-7a65e7506a12
* Version Independent ID: 51a94f92-9ff4-12e7-2f97-1bbe34855400
* Content: [Roles and permissions in Microsoft Store for Business and Education (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/roles-and-permissions-microsoft-store-for-business#feedback)
* Content Source: [store-for-business/roles-and-permissions-microsoft-store-for-business.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/roles-and-permissions-microsoft-store-for-business.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by mypil** [comment]
@Daveliddle - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot close
