### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by ionutromeo555** [MicrosoftDocs/windows-itpro-docs#10221]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd2798f8-c5c1-f42d-569c-a4dcde7431f6
* Version Independent ID: 1b56cb9a-6513-3235-4922-45291ec057cc
* Content: [Create a deployment plan - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/create-deployment-plan)
* Content Source: [windows/deployment/update/create-deployment-plan.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/create-deployment-plan.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment]
@e0i , there is no proper feedback so close this PR #10221 immediately
