### ISSUE TITLE
Hello errors during PIN creation

### ISSUE THREAD

**Issue by itsmeclancy** [MicrosoftDocs/windows-itpro-docs#10222]
How to fix this?

![IMG_20211220_034206](https://user-images.githubusercontent.com/80187036/146690202-eb4b0737-6c47-45e6-a4a9-b11f017bf786.jpg)

**Comment by RAJU2529** [comment]
@itsmeclancy , is your device is connected to organization means, then contact to your organization system administrator.
if your device is standard alone and is activated with a KMS key, then you won't help from here.
