### ISSUE TITLE
Certificate Tile Enumeration

### ISSUE THREAD

**Issue by jamesburkecissp** [MicrosoftDocs/windows-itpro-docs#10226]
[Enter feedback here]
Hi,
I need some professional services around certificate tile enumeration.
I can't find a contract for someone at Microsoft to assist me with this.
James

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 132e8bfa-12ba-2ae0-7745-545bcfd909f1
* Version Independent ID: 984c17f4-04a4-bf30-3a9e-3af49209f0bb
* Content: [Certificate Requirements and Enumeration (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration)
* Content Source: [windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Hello @jamesburkecissp. Can you take a look at this article: https://support.microsoft.com/en-us/office/find-digital-id-or-digital-signature-services-b06cfc76-56a1-4a74-b2dd-91a55de79cdf 

Does it have what you are looking for?

**Comment by jamesburkecissp** [comment]
Hi,
This doesn’t have the information I am looking for.
I am a PKI SME. I am trying to contact someone about a necessary change the GPO for Certificate Tile Enumeration.
I don’t wish to go into greater detail in a public forum, but happy to share more details in private.
James

From: Denise Vangel-MSFT ***@***.***>
Reply-To: MicrosoftDocs/windows-itpro-docs ***@***.***>
Date: Tuesday, December 21, 2021 at 3:22 PM
To: MicrosoftDocs/windows-itpro-docs ***@***.***>
Cc: ***@***.***" ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/windows-itpro-docs] Certificate Tile Enumeration (Issue #10226)


Hello @jamesburkecissp<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jamesburkecissp&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=h6G80RQ-puXFt15yxX-b-3LgVg4YbIPQwA9uEoG-wU8&m=HkCPqfRF-q-KQlRCd9JCMZMsWI95kX6lYNfaLCHFsGU&s=E_Rw06kqjwCa4WEaTDtfUqeCx_ulxYdjtzAkQqcRF_Y&e=>. Can you take a look at this article: https://support.microsoft.com/en-us/office/find-digital-id-or-digital-signature-services-b06cfc76-56a1-4a74-b2dd-91a55de79cdf<https://urldefense.proofpoint.com/v2/url?u=https-3A__support.microsoft.com_en-2Dus_office_find-2Ddigital-2Did-2Dor-2Ddigital-2Dsignature-2Dservices-2Db06cfc76-2D56a1-2D4a74-2Db2dd-2D91a55de79cdf&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=h6G80RQ-puXFt15yxX-b-3LgVg4YbIPQwA9uEoG-wU8&m=HkCPqfRF-q-KQlRCd9JCMZMsWI95kX6lYNfaLCHFsGU&s=sNOZeKeQB8iPoUi_Wdi3o5OItw87NygRizZFzN0V9wY&e=>

Does it have what you are looking for?

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MicrosoftDocs_windows-2Ditpro-2Ddocs_issues_10226-23issuecomment-2D999069672&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=h6G80RQ-puXFt15yxX-b-3LgVg4YbIPQwA9uEoG-wU8&m=HkCPqfRF-q-KQlRCd9JCMZMsWI95kX6lYNfaLCHFsGU&s=D7F2uqNLUIZDgcR77WDZSPmm0Csn5-kc74dPc3E4FtE&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AG6NKDWAQEVH6SLPOSL252LUSDOX3ANCNFSM5KNU6AAQ&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=h6G80RQ-puXFt15yxX-b-3LgVg4YbIPQwA9uEoG-wU8&m=HkCPqfRF-q-KQlRCd9JCMZMsWI95kX6lYNfaLCHFsGU&s=Z948n0LaDycIRI6xIan17J1cgsJzfWPeLi_r-NTQxvc&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=h6G80RQ-puXFt15yxX-b-3LgVg4YbIPQwA9uEoG-wU8&m=HkCPqfRF-q-KQlRCd9JCMZMsWI95kX6lYNfaLCHFsGU&s=xTKtQgGSRJPHqHNojWzuieJ93b4xYcpEE1CoUl_-w9g&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=h6G80RQ-puXFt15yxX-b-3LgVg4YbIPQwA9uEoG-wU8&m=HkCPqfRF-q-KQlRCd9JCMZMsWI95kX6lYNfaLCHFsGU&s=sSQnkaUQTAmr7lecJyyQSPGYauCT4lK46ctvkBtKcvQ&e=>.

**Comment by saif71** [comment]
The author didn’t report any issue with the doc. They just wanted to contact someone at Microsoft.  
Here we only deal with doc-related issues and do not provide support-related information.
