### ISSUE TITLE
Broken link (404 error)

### ISSUE THREAD

**Issue by JazzyAtWork** [MicrosoftDocs/windows-itpro-docs#10224]
The link on this page for "Enable passwordless sign-in with the Microsoft Authenticator app." results in a 404 error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 447f17ab-5056-df8a-7863-e29a62d583e0
* Version Independent ID: 088c99cb-4b8c-e495-28dc-50922e2aa00d
* Content: [Windows identity and user security - Windows security](https://docs.microsoft.com/en-us/windows/security/identity)
* Content Source: [windows/security/identity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@e0i , Assign user to review and merge PR #10228
