### ISSUE TITLE
Link on Kerberos/PKInitHashAlgorithmConfiguration is broken

### ISSUE THREAD

**Issue by tr5tn** [MicrosoftDocs/windows-itpro-docs#10234]
The link for more information at the bottom of the Kerberos/PKInitHashAlgorithmConfiguration content is broken, and this appears to be the only source of Microsoft information right now, so I could use more info. ;) 

(admin edit: refresh metadata with latest)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0e4a0b3-27f0-fa12-34aa-0be9415bfba0
* Version Independent ID: d45903ee-c06f-7ee8-6277-440e9837dcdc
* Content: [Kerberos Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-kerberos#pkinithashalgorithmconfiguration)
* Content Source: [windows/client-management/mdm/policy-csp-kerberos.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-kerberos.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Specific reference:

> More information about the hash and checksum algorithms supported by the Windows Kerberos client and their default states can be found at< https://go.microsoft.com/fwlink/?linkid=2169037>.

Interestingly, that fwlink ID doesn't exist, which is why it redirects to bing.com. 🙃  @vinaypamnani-msft this might be another one of those one-off exceptions in the automation. (I don't think we can create a fwlink with a specific ID.)

**Comment by vinaypamnani-msft** [comment]
Fixed this in the automation code. The link will be removed next time we refresh CSP articles. Closing this issue.
