### ISSUE TITLE
No Mention of Windows 11

### ISSUE THREAD

**Issue by ld0614** [MicrosoftDocs/windows-itpro-docs#10230]
This (and Associated Pages) don't make any mention of Windows 11 nor include the DDF files for Windows 11, does this mean that Windows 11 is not supported via CSP management?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162c8434-b3ab-e235-43ce-ed435d6cd06e
* Version Independent ID: 18b29b82-f1ad-81b8-2ea4-f7bebc506487
* Content: [Configuration service provider reference - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference)
* Content Source: [windows/client-management/mdm/configuration-service-provider-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/configuration-service-provider-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @ld0614 ,
Windows 11 is supported via CSP management, but the documentation is not fully updated yet.
As you can see, CSP articles already have Windows 11 in the applicability table, but it will take some time until all the articles in the MDM section of documentation is updated.
Thank you
