### ISSUE TITLE
"To test access as a given user, you can run this Windows PowerShell cmdlet while logged on as that user:"

### ISSUE THREAD

**Issue by Scoobysnax97** [MicrosoftDocs/windows-itpro-docs#1023]
The commands won't run on W7.  They're only listed in the Windows 10 and Windows Server 2016 PowerShell cmdlets, not the W8 or 8.1   https://docs.microsoft.com/en-us/powershell/module/nettcpip/?view=win10-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f20e3377-fdbc-ac87-239e-7184db24a685
* Version Independent ID: 0464da82-efa4-b147-bba9-d6802cf9d273
* Content: [Frequently asked questions and troubleshooting Windows Analytics](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-faq-troubleshooting)
* Content Source: [windows/deployment/update/windows-analytics-FAQ-troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-FAQ-troubleshooting.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by lizap** [comment]
You're correct - this is a Windows 10 and Windows Server PS cmdlet.
