### ISSUE TITLE
Windows 7 in 2021 as an example???

### ISSUE THREAD

**Issue by woodsonja** [MicrosoftDocs/windows-itpro-docs#10238]
Why is Windows 7 still being used as an example when it's no longer supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ab08370-69ab-d025-cea2-c41c3aa4b908
* Version Independent ID: 9f5603f8-10e6-2651-3120-6d5627217cc9
* Content: [Prepare for deployment with MDT (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by aczechowski** [comment]
Thanks @woodsonja for the feedback. We're not investing much at all in the MDT-related content. This article was written a few years ago when there were a lot of migrations from Windows 7 to Windows 10, which as you suggest isn't as relevant at this point. We don't have any plans in revising this content, but the concepts remain the same. We do plan on taking a broader look at the Windows deployment content and potentially reorganizing in the future.
