### ISSUE TITLE
There are no details on the requirements for Multi-Forest support

### ISSUE THREAD

**Issue by rh1701** [MicrosoftDocs/windows-itpro-docs#1024]
Please add details for multi-forest support, with and without SCCM integration.  My organization has multi-forest and full 2-way forest trust but since each forest uses an independent SCCM instance, can we still use a single MBAM instance?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bd86f5e-6388-d226-2460-997fc24945d9
* Version Independent ID: aa827a7d-725a-a5d0-f6aa-3f1df8cc310a
* Content: [MBAM 2.5 Supported Configurations](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/mbam-25-supported-configurations)
* Content Source: [mdop/mbam-v25/mbam-25-supported-configurations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/mbam-25-supported-configurations.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by R2D2components** [comment]
Hold up stop . This request has not been verified by corporate and all action needs to revert to its. Former self. This violates conditions of warranty. Revert this process immediately 

Please contact me ASAP 
Owner 
Jason Robertson

**Comment by R2D2components** [comment]
Revert this document and any and all setting that have been made and restore this device from any settings that were requested by whom ever. Stop and revert. This is a personal home computer and who ever is doing this needs to be stopped.
Please contact me ASAP

Jason Robertson

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by VLG17** [comment]
@rh1701 MBAM 2.5 supports multi forests topology. More details can be found [here](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/about-mbam-25#support-for-multi-forest-support-deployments).

**Comment by nam31** [comment]
@rh1701 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
