### ISSUE TITLE
Windows 11 documentation

### ISSUE THREAD

**Issue by jandreacola** [MicrosoftDocs/windows-itpro-docs#10240]
Documentation is missing information on Windows 11

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08436cb0-d0b6-0961-9e57-291b24d73644
* Version Independent ID: 36264f52-d3ac-4e50-f8e8-b09d6b210490
* Content: [Windows 10 upgrade paths (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-upgrade-paths)
* Content Source: [windows/deployment/upgrade/windows-10-upgrade-paths.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/windows-10-upgrade-paths.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
In general, devices running Windows 7 or 8.1 will not have hardware that meets requirements to run Windows 11.  That said, an upgrade might be possible using installation media. See https://www.microsoft.com/software-download/windows11

See https://support.microsoft.com/en-us/windows/windows-11-system-requirements-86c11283-ea52-4782-9efd-7674389a7ba3 for information about upgrading with Windows Update: "Windows Version for Upgrade:  Your device must be running Windows 10, version 2004 or later, to upgrade through Windows Update. Free updates are available through Windows Update in Settings > Update and Security."

**Comment by greg-lindsay** [comment]
I will work on the articles that are present in the IT Pro content library and make sure the details from these other articles that I linked above are clear.
