### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by Computer-Tsu** [MicrosoftDocs/windows-itpro-docs#10255]
The page, https://www.microsoft.com/en-us/download/details.aspx?id=25250 has Related links, one is titled GPO TechNet, that link, http://go.microsoft.com/fwlink/?linkid=31191, instead goes here which is Windows Deployment, and not the intended GPO topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ac5717f-e911-ac81-445d-6fbeb371b334
* Version Independent ID: 5e8e7627-d30e-d3ea-f673-c0093486cc99
* Content: [What's new in Windows client deployment - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-whats-new)
* Content Source: [windows/deployment/deploy-whats-new.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-whats-new.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@Computer-Tsu , could you tell me where the location is,that you have found incorrect link in this article.

**Comment by VLG17** [comment]
@e0i The article that needs editing is a Download Center article - https://www.microsoft.com/en-us/download/details.aspx?id=25250, not a Technet one.

Who can help edit it, so that Group Policy TechCenter under Related Resources points to the right article?

![image](https://user-images.githubusercontent.com/41186174/172140001-65f26df0-a06e-4b6a-b387-4afe579da148.png)

**Comment by aczechowski** [comment]
I'm checking with the owners of that fwlink, but can't make any promises that we'll be able to find the proper owner. I'm closing this issue as it's outside the scope of our control, but will try to get it addressed. Thanks @Computer-Tsu for the feedback
