### ISSUE TITLE
Olympia.windows.com link does not work

### ISSUE THREAD

**Issue by mapalko** [MicrosoftDocs/windows-itpro-docs#10266]
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/497c6d7ae578004a565841fa6b35392f7f0cb333/windows/deployment/update/olympia/olympia-enrollment-guidelines.md?plain=1#L34

The link "see https://olympia.windows.com/Info/FAQ." directs the user to a 403 web app has stopped error page.

**Comment by RAJU2529** [comment]
@e0i , Actual article link for  above issue 

https://docs.microsoft.com/en-us/windows/deployment/update/olympia/olympia-enrollment-guidelines

**Comment by msbemba** [comment]
@mapalko Thank you for your feedback. Olympia Corp, a virtual corporation was set up to reflect the IT infrastructure of real world businesses and Olympia has been formally retired on October 31, 2022.

Hope this helps!

@yogkumgit This can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mapalko Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
