### ISSUE TITLE
More info on Device Registration and troubleshooting?

### ISSUE THREAD

**Issue by jbostoen** [MicrosoftDocs/windows-itpro-docs#10263]
It's been a very frustrating experience trying to set up Windows Hello for Business on premises (without Azure). This is possible, right? I'm struggling very much to get Device Registration working on Windows Server 2019.

For some reason, there's this instruction for Device Registration in the certificate trust.

"In the Properties section, select Read msDS-KeyCredentialLink and Write msDS-KeyCrendentialLink."

https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs#configure-the-device-registration-service

Also the other pages could use some love: overly complicated (repeat certain steps a couple of time for each object; rather than just bulk selecting the objects and running certain actions once); I saw what looked like an internal question on one of the other pages there about WHFB, the above attributes were at one point spelled like ms-DSKeyCredentialLink + see also the typo in the text on this page). 

The requirements are not clear enough (MFA adapter seems required on https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification#on-premises-deployments while on https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-deploy-mfa it seems to suggest that a [device?] certificate is enough - here the phrasing could be better [or in list form] to make the difference between the two authentication provider methods more clear).

I for one also miss clear instructions on - if it's even possible - enabling Device Registration solely within ADFS, without Azure (very little info to be found on this topic; I think I did the entire server side config; but how do you get your devices to actually register and how to troubleshoot? I found out about dsregcmd /status; my machine is DomainJoined but not EnterpriseJoined which is seemingly what I'd need?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b063e00b-84e5-9da7-2229-e0e24da3b877
* Version Independent ID: da9f4867-2aa3-aefa-1603-ddb2ab1ed624
* Content: [Prepare and Deploy Windows AD FS certificate trust (Windows Hello for Business) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs#configure-the-device-registration-service)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md)
* Product: **m365-security**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by yogkumgit** [comment]
@paolomatarazzo Please help us in resolving this issue. Thanks
