### ISSUE TITLE
Please fix the phishing submission process for Microsoft 365.

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/windows-itpro-docs#10269]
Continuing from issue #10170. 

**The method to send junk or phishing for analysis via email has been removed from all Microsoft 365 documentation. Please change it accordingly.**

Replace text:

"Microsoft: Create a new, blank email message with the one of the following recipients:

Junk: junk@office365.microsoft.com
Phishing: phish@office365.microsoft.com
Drag and drop the junk or phishing message into the new message. This will save the junk or phishing message as an attachment in the new message. Don't copy and paste the content of the message or forward the message (we need the original message so we can inspect the message headers). For more information, see Report messages and files to Microsoft."

====

with: 

"Microsoft 365: Use Submissions in Microsoft 365 Defender (URL:https://security.microsoft.com) to submit the junk or phishing sample to Microsoft for analysis. For more information, see Report messages and files to Microsoft (URL:https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/report-junk-email-messages-to-microsoft)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08af6103-ad16-f4d5-fd46-38bf88b18423
* Version Independent ID: 872dc72c-b12c-97e0-ea1e-ab7882be12f4
* Content: [How to protect against phishing attacks - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/phishing)
* Content Source: [windows/security/threat-protection/intelligence/phishing.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/phishing.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @hudish ,
I made the recommended change in PR #10409. I only replaced link to the portal with link to the instruction.
Thank you
