### ISSUE TITLE
Links still take you to Cert trust

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/windows-itpro-docs#1026]
Hey, the links for guide #1 and #2 at the bottom here still take you to cert trust incorrectly. Please make sure these do not take you to the wrong deployment type. This causes some major navigation issues, and is present on all pages here, I believe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4784e8f-6d35-78d8-9160-7b39832a58d8
* Version Independent ID: 7f79559a-3a6d-473b-1ec1-66746c461318
* Content: [Windows Hello for Business Key Trust New Installation (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by MikeStephens-MS** [comment]
-FIXED
Should be visible in the next update coming out.  Thank you for the feedback and sorry for the delay.
-Mike
