### ISSUE TITLE
Couldn't manage to make this work

### ISSUE THREAD

**Issue by ncoffez** [MicrosoftDocs/windows-itpro-docs#10265]
I have tried any possible variation of the explained solution, to no avail. Finally, I was able to configure the upgradeEditionWithProductKey using **Devices > Windows > Configuration Profiles > Create Profile** and selecting **Templates > Edition Upgrade and mode switch**

Maybe this alternative should be mentioned as I spent multiple days looking for a way to upgrade all licenses to Windows Enterprise for InTune using this guide. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b01a2e6-e105-d3b8-decc-4a26ee1abaf9
* Version Independent ID: 40b419f6-0a39-369d-1d76-5308eb77b202
* Content: [WindowsLicensing CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/windowslicensing-csp)
* Content Source: [windows/client-management/mdm/windowslicensing-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/windowslicensing-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment]
Thanks @ncoffez for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

> **NOTE:**
> This article along with most of the other CSP reference docs were recently refreshed. They now are mostly auto-generated from the CSP DDFv2 XML and/or the associated ADMX. So you might take another look to see if the updated article provides further clarity.
