### ISSUE TITLE
"Invalid Login Attempt" unclear

### ISSUE THREAD

**Issue by jj4r3d** [MicrosoftDocs/windows-itpro-docs#10270]
Hello,

My team and I have a question regarding the account lockout threshold counter. We want to know if login attempts using an expired password count towards the "Invalid Login Attempt counter". We recently had a case where a user's account tried authenticating over 900,000 times using an expired password and did not receive an account lockout. 

Thank you

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82cb96d5-5901-a1ea-a32d-12f22c5c4a09
* Version Independent ID: d8073688-6782-c4b2-58c8-6a8650bfeb9c
* Content: [Account lockout threshold (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/account-lockout-threshold)
* Content Source: [windows/security/threat-protection/security-policy-settings/account-lockout-threshold.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/account-lockout-threshold.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@jj4r3d , Could you tell, user device is connected organization and or  a domain-joined device.
Is the system administrator is properly configured the locked-out policy and applied to connected user devices?

**Comment by jj4r3d** [comment]
The user/device is connected to an organization/domain, yes. Our lockout policy is 50 attempts in 5 minutes. We just want to know if expired password attempts count.

**Comment by RAJU2529** [comment]
@jj4r3d , I am not an expert, take user device with you, and  attend the account lockout, execute worng password attempt, and verify the deployed policy is  conformed and working correctly

**Comment by jj4r3d** [comment]
Thank you for your time. We tested the policy using wrong passwords and it works. However, if a user's password expires and they try it 50 times, it doesn't lock out. I wonder if anyone else knows

**Comment by RAJU2529** [comment]
@jj4r3d . I have doubt on his user device, he or she might applied registry key to avoid lockout policy . Please examine that user device

**Comment by MaratMussabekov** [comment]
Hello @jj4r3d ,
**We want to know if login attempts using an expired password count towards the "Invalid Login Attempt counter".** - no, it doesn't, because the password was correct. Password is not considered as incorrect when it is expired. When it is expired, it cannot be used to access resources, it only can be used to set the new password.
Thank you
