### ISSUE TITLE
Policy CSP DDF File Missing ADMX-Backed Policies?

### ISSUE THREAD

**Issue by eppsilon** [MicrosoftDocs/windows-itpro-docs#10273]
The [ADMX-backed policies](https://docs.microsoft.com/en-us/windows/client-management/mdm/policies-in-policy-csp-admx-backed) are listed on another page but not included in the downloadable Policy CSP DDF XML file. (I checked the 2004 and 20H2 versions.) Is that page the definitive list of ADMX-backed policies? Is there a way to know which ones are supported by each version of Windows 10?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 051c376e-e9dd-368d-0af7-ac0d997226c2
* Version Independent ID: e49d31fa-4ba6-2140-54ee-f9564f59371b
* Content: [Policy DDF file - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-ddf-file)
* Content Source: [windows/client-management/mdm/policy-ddf-file.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-ddf-file.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@eppsilon . Answering your question is too difficult to me, only author of this article can give correct  solutions

**Comment by MaratMussabekov** [comment]
Hello @eppsilon ,
**Is that page the definitive list of ADMX-backed policies?** - yes, according to its history, the article is being updated regularly
**Is there a way to know which ones are supported by each version of Windows 10?** - as far as I can see, it is not shown anywhere in Microsoft Docs. You can use ADMX file information for this purpose. As you will need to download ADMX file to use ADMX-backed policies, the settings will apply to all versions that support this ADMX.
Thank you
