### ISSUE TITLE
suggest to add warning to sandbox page

### ISSUE THREAD

**Issue by Haochen316** [MicrosoftDocs/windows-itpro-docs#10282]
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview#:~:text=%20Windows%20Sandbox%20has%20the%20following%20properties%3A%20,Microsoft%20hypervisor%20to%20run%20a%20separate...%20More%20

suggest adding warning to above page that windows sandbox does not isolate from network/lan
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c06f3ef-5946-862a-ae14-f897fdb518ca
* Version Independent ID: cd6a8b99-b1e9-dff5-f174-a15840b304f0
* Content: [Windows Sandbox - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @Haochen316 ,
that's an important warning, I added it in https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10410
Thank you
