### ISSUE TITLE
problème de sécurité

### ISSUE THREAD

**Issue by balti02** [MicrosoftDocs/windows-itpro-docs#10289]
[Tapez vos commentaires ici]

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 0d30d792-78bc-d594-ea45-5ca6b29dec72
* Version Independent ID: eff8bd5f-9480-59cb-0355-aa389be6e5f1
* Content: [Sécuriser le processus de démarrage de Windows - Windows security](https://docs.microsoft.com/fr-fr/windows/security/information-protection/secure-the-windows-10-boot-process)
* Content Source: [windows/security/information-protection/secure-the-windows-10-boot-process.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/secure-the-windows-10-boot-process.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Hello @balti02. Do you have feedback on the article?  Avez-vous des commentaires sur l’article?
