### ISSUE TITLE
Wrong link to Microsoft Security Report

### ISSUE THREAD

**Issue by MacKender** [MicrosoftDocs/windows-itpro-docs#10287]
" see the Microsoft Security Intelligence Report." links to https://www.microsoft.com/security/sir/default.aspx but that doesn't work.  Guessing it should link to https://www.microsoft.com/en-us/security/business/microsoft-digital-defense-report (?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e917fa76-653a-4bb9-0d2d-7f1db05a4b42
* Version Independent ID: 213c5a5a-63b1-5a0e-56a2-72f6deed70d3
* Content: [Protect devices from unwanted network traffic (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/protect-devices-from-unwanted-network-traffic)
* Content Source: [windows/security/threat-protection/windows-firewall/protect-devices-from-unwanted-network-traffic.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/protect-devices-from-unwanted-network-traffic.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@MacKender . Thanks for the report. I will add correct link today afternoon.
