### ISSUE TITLE
Correction of Windows 10 Version 

### ISSUE THREAD

**Issue by jobykjohn** [MicrosoftDocs/windows-itpro-docs#10286]
[Enter feedback here]

Instead of Starting with Windows 10, version 2006 (and in Windows 11), the Bypass option of Download Mode is no longer used, the statement should be Starting with Windows 10, version 2004 (and in Windows 11), the Bypass option of Download Mode is no longer used.

I don't believe there is a Windows 10 Version 2006 as per https://docs.microsoft.com/en-us/windows/release-health/release-information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb67e518-6f60-23e0-2545-c2839e2b4159
* Version Independent ID: e9a31629-e3cb-0367-31c4-5661284d89bf
* Content: [Delivery Optimization for Windows client updates - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization?source=docs)
* Content Source: [windows/deployment/update/waas-delivery-optimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-delivery-optimization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@dougeby

**Comment by aisgbnok** [comment]
This seems to have been resolved in d7b795456578bdb84e7256de8b9cfc74b2426d89. The current page no longer displays "Windows 10 Version 2006."
