### ISSUE TITLE
Updated for Windows 11.

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/windows-itpro-docs#10296]
"For real-time protection with automatic updates, use Microsoft Defender Antivirus on Windows 10 and Windows 8 or Microsoft Security Essentials on Windows 7. "

What should we do on Windows 11?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5bb1ce3-9128-5385-4417-d22eb5f8cb77
* Version Independent ID: cb6ba731-a2c2-e9b9-7c3e-db781b1b5222
* Content: [Microsoft Safety Scanner Download - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/safety-scanner-download)
* Content Source: [windows/security/threat-protection/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/safety-scanner-download.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@Dansimp , After reading this article, i added Windows 11 in the required place.

**Comment by RAJU2529** [comment]
@martingbrown , Same tool u.ful for Windows 11 too
