### ISSUE TITLE
False Information under "PIN can be complex"

### ISSUE THREAD

**Issue by urbndude** [MicrosoftDocs/windows-itpro-docs#10299]
The last sentence in this article "You can require or block: special characters, uppercase characters, lowercase characters, and digits." is incorrect.   There is no setting for Requiring or blocking of digits in Endpoint Manager.  Please either add this feature, or it should be removed from this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c34dbafa-df3c-a5a5-32d5-2ce152893534
* Version Independent ID: cebdd9a6-45d7-6306-373c-7d31121f9e16
* Content: [Why a PIN is better than a password (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password?source=docs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md)
* Product: **m365-security**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by RAJU2529** [comment]
@urbndude   "You can require or block: special characters, uppercase characters, lowercase characters, and digits.".
Above statement is correct, policies can be set by using grou[ policy editor.

Computer Configuration > Administrative Templates > System > PIN Complexity.

**Comment by urbndude** [comment]
How do you do this using Intune though?

**Comment by MaratMussabekov** [comment]
Hello @urbndude ,
both GPO and MDM could be used to set PIN policies, see here - https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-manage-in-organization#mdm-policy-settings-for-windows-hello-for-business
Thank you
