### ISSUE TITLE
This functionnality IS supported for key trust deployments

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/windows-itpro-docs#10298]
> "This functionality is not supported for key trust deployments"

This page says the exact opposite and explains how to make Windows Hello key trust work with RDP:
[https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs](url)

What page do we can trust?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e456736-63a3-672a-814f-047cc66f0f98
* Version Independent ID: 80cd84e4-6ea5-c707-f362-98fd507fcbfa
* Content: [Remote Desktop - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-remote-desktop)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-feature-remote-desktop.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-feature-remote-desktop.md)
* Product: **m365-security**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mapalko** [comment]
RDP does not work with just key trust unless you are using remote credential guard. The second doc is enrolling a certificate into the container which essentially migrates the user from key trust to certificate trust so they can supply a cert as a part of RDP. We can add a note to this document to clarify this point and to redirect to the documentation for cert enrollment

**Comment by RAJU2529** [comment]
@mapalko , iF possible will you include the above explanation in this article in note section.
include explanation written by you.

**Comment by Martony78** [comment]
@mapalko No it is not the same, Cert Trust requires ADFS, RDP cert doesn't.

**Comment by Martony78** [comment]
You closed this issue but I don't see any change in the doc. Please reopen or at least provide an explanation.
