### ISSUE TITLE
Support for Windows 11 & Windows Server 2022

### ISSUE THREAD

**Issue by Fojonx** [MicrosoftDocs/windows-itpro-docs#10292]
Is there a timeline/roadmap for adding support for Windows 11 and Windows Server 2022 deployments to MDT?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02d07ede-1437-53e7-8ea5-3ee441cda67d
* Version Independent ID: 8b657df5-9053-7611-9132-f9113d439a7c
* Content: [Get started with the Microsoft Deployment Toolkit (MDT) (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/get-started-with-the-microsoft-deployment-toolkit?source=docs)
* Content Source: [windows/deployment/deploy-windows-mdt/get-started-with-the-microsoft-deployment-toolkit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/get-started-with-the-microsoft-deployment-toolkit.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by msbemba** [comment]
@Fojonx Thank you for your feedback. Currently, we from the documentation team do not have that information However you can post this feedback directly on our main feedback portal( https://feedbackportal.microsoft.com/) so that a dev/product engineer can provide you with more information. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@Fojonx  Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
