### ISSUE TITLE
Broken Links to Channel 9 from Windows Defender Credential Guard Documentation

### ISSUE THREAD

**Issue by GoodOlClint** [MicrosoftDocs/windows-itpro-docs#10294]
None of the direct links to Channel 9 content on this page work, they all load to the same "Shows" homepage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87ec66f8-6598-5751-a10f-55951c08b3ff
* Version Independent ID: c3bb99fb-ec6f-638f-fb26-af3142f5d49c
* Content: [Protect derived domain credentials with Windows Defender Credential Guard (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello, the referred content doesn't exist any more, I removed the links in https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10411.
Thank you
