### ISSUE TITLE
Unable to get TimeLanguageSettings/BlockCleanupOfUnusedPreinstalledLangPacks to work

### ISSUE THREAD

**Issue by boivinx7** [MicrosoftDocs/windows-itpro-docs#10304]
Is its still an active existing config, seems to not exist anywhere but this doc.
Its not in intune Settings Catalog or ADMX, its not in Configuration Designer and it wont work.

./Vendor/MSFT/Policy/Config/TimeLanguageSettings/BlockCleanupOfUnusedPreinstalledLangPacks

![image](https://user-images.githubusercontent.com/30272385/150366217-2580f7df-3b3c-4721-a1b8-d770234a3805.png)

![image](https://user-images.githubusercontent.com/30272385/150366989-5bf17182-3d8a-4b6a-a421-905ef59edae6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86ff0ddd-37e5-2f87-920c-f83b07d4ebb1
* Version Independent ID: ca02de5e-14cb-5f64-b7e4-9b5fe738029f
* Content: [Policy CSP - TimeLanguageSettings - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-timelanguagesettings#timelanguagesettings-blockcleanupofunusedpreinstalledlangpacks)
* Content Source: [windows/client-management/mdm/policy-csp-timelanguagesettings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-timelanguagesettings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@boivinx7 , **BlockCleanupOfUnusedPreinstalledLangPacks**  policy is available in windows 11 with latest ADMX templates .
here is the proof
![Screenshot 2022-01-20 223254](https://user-images.githubusercontent.com/3296790/150386478-3ac7575e-b550-414a-a6df-a8012ea75f11.jpg)

**Comment by boivinx7** [comment]
@RAJU2529 
Yes I know about the GPO, im speaking about the CSP.

**Comment by aczechowski** [comment]
Thanks @boivinx7 for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

> NOTE:
> This article along with most of the CSP reference docs were recently refreshed. They are now mostly auto-generated with content from the CSP DDF XML and/or the associated ADMX. You might take another look to see if this update provided further clarity.
