### ISSUE TITLE
Include details of GPO policies that can be locked

### ISSUE THREAD

**Issue by Scoobysnax97** [MicrosoftDocs/windows-itpro-docs#10302]
You list MDM policies that can be locked, but also include GPOs please

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1b2158c-0737-8379-eddc-0d1f911b7c87
* Version Independent ID: f1b2158c-0737-8379-eddc-0d1f911b7c87
* Content: [Secured-Core Configuration Lock - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/config-lock)
* Content Source: [windows/client-management/mdm/config-lock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/config-lock.md)
* Product: **w11**
* Technology: **windows**
* GitHub Login: @Lovina-Saldanha
* Microsoft Alias: **v-lsaldanha**

**Comment by MaratMussabekov** [comment]
Hello @Scoobysnax97 ,
added in https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10419
Thank you
