### ISSUE TITLE
REquire Update for creation app policy for WIP from Endpoint Manager admin

### ISSUE THREAD

**Issue by AshishOnGit** [MicrosoftDocs/windows-itpro-docs#10301]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31038d8d-6b71-6b34-6590-81cb35c5954c
* Version Independent ID: db01fe97-9a4a-c852-5763-f0f4c28b6efd
* Content: [Create a Windows Information Protection (WIP) policy using Microsoft Intune (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/overview-create-wip-policy)
* Content Source: [windows/security/information-protection/windows-information-protection/overview-create-wip-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/overview-create-wip-policy.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@Dansimp  there is no proper feedback  description, so please close it immediately.

**Comment by AshishOnGit** [comment]
Require Update for creation app policy for WIP from Endpoint Manager admin

**Comment by RAJU2529** [comment]
@AshishOnGit , so please  include "Require Update for creation app policy for WIP from Endpoint Manager admin" in feedback description. 
Include Why it is needed>

**Comment by aczechowski** [comment]
WIP is [now deprecated](https://go.microsoft.com/fwlink/?linkid=2202124), so we're not going to invest further in updating the content. We recommend that you use [Microsoft Purview Information Protection](https://docs.microsoft.com/microsoft-365/compliance/information-protection) and [Microsoft Purview Data Loss Prevention](https://docs.microsoft.com/microsoft-365/compliance/dlp-learn-about-dlp).
