### ISSUE TITLE
Windows 10 Roadmap Link

### ISSUE THREAD

**Issue by PaulSIsaac** [MicrosoftDocs/windows-itpro-docs#1030]
This link goes to the 'Compare Windows 10 Editions' page and not a roadmap

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b010f23d-6d7e-8ab0-8a16-0ddbbacc0528
* Version Independent ID: 929b988a-e7e4-b8b0-2a85-756c69085063
* Content: [What's new in Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/whats-new/)
* Content Source: [windows/whats-new/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/index.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **trudyha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@PaulSIsaac - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by Malind19** [comment]
@PaulSIsaac @TrudyHa , Can you kindly suggest what is the actual link shall be?

**Comment by TrudyHa** [comment]
@mypil At one point there might have been a Roadmap topic, and now it is redirecting to this Compare editions topic. I'd go ahead and remove the link.

**Comment by Malind19** [comment]
@TrudyHa I will remove the link.

**Comment by Malind19** [comment]
@mypil Created PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3220

**Comment by mypil** [comment]
@PaulSIsaac  - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
