### ISSUE TITLE
"Intune Certificate Connector" section is out of date

### ISSUE THREAD

**Issue by MitchBrown1** [MicrosoftDocs/windows-itpro-docs#10308]
The Intune Certificate Connector application has been updated significantly since this document was created.  Here is the link to the location in the document:
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert#install-the-intune-certificate-connector

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f709fd4-0b5d-b238-4060-222d550cd538
* Version Independent ID: fb3f29da-2236-c47d-6bea-8efbcec8d7d3
* Content: [Using Certificates for AADJ On-premises Single-sign On single sign-on - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md)
* Product: **m365-security**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by aczechowski** [comment]
Thanks @MitchBrown1 for the feedback, and thanks @MaratMussabekov for the edit. The updated article removes the outdated screenshots and steps, and links to the source article in the MEM content on how to [install the certificate connector](https://docs.microsoft.com/mem/intune/protect/certificate-connector-install).
