### ISSUE TITLE
Other interacting policies

### ISSUE THREAD

**Issue by jasminrueegger** [MicrosoftDocs/windows-itpro-docs#10307]
Hi Microsoft
This article states "The device will try to download and install the update at a time based on your other download and installation policies (the default is to automatically download and install in in the background)."

What other policy allows to set a download and install time? 

We have "Configure Automatic Updates" configured to a specific weekdate and time, but this was ignored (the new policy mentions it overrides this, so we kind of expected this).
With Windows 11 and without the "Specify deadlines for automatic updates and restarts", quality updates would not install automatically, if the time configured in "Configure Automatic Updates" was missed. Windows 10 (also 21H2) updates immediately in this case. So we will have to set this new policy. But we would prefer updates to install at our defined time, if the computer is online then (and only install after this date if the computer was not).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44aabe97-360e-0655-09ec-5d1e352bdb1a
* Version Independent ID: 1c729c42-741d-ecb7-6490-a4bfdd029263
* Content: [Enforce compliance deadlines with policies in Windows Update for Business (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/wufb-compliancedeadlines)
* Content Source: [windows/deployment/update/wufb-compliancedeadlines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/wufb-compliancedeadlines.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@arcarley 
@dougeby for awareness
