### ISSUE TITLE
Is regularly clearing the NodeCache problematic?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/windows-itpro-docs#10329]
Obviously this will consume, CPU, bandwidth, etc, but is regularly clearing the NodeCache problematic? 
Example use case:

If I wanted to force windows to re-download the LockScreenImageUrl on a regular basis (part of PersonalizationCSP), I can do something like this:

`Clear-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Provisioning\NodeCache\CSP\Device\MS DM Server\' -Name CacheVersion`

`Clear-ItemProperty -Path 'HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\PersonalizationCSP' -Name LockScreenImageUrl`

`Get-ScheduledTask 'Schedule #1 created by enrollment client' | Start-ScheduledTask`

This achieves the desired result, but will it lead to exhaustion of Node IDs or a similar long-term problem?

(I notice the workstation generates new keys when this happens. Is there an upper limit?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8acbb6a2-add6-98e1-7670-472b114f7e42
* Version Independent ID: 787a0834-ec2b-2dfb-3b41-d31830a8c49d
* Content: [NodeCache CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/nodecache-csp)
* Content Source: [windows/client-management/mdm/nodecache-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/nodecache-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by vinaypamnani-msft** [comment]
Thanks @Mike-Crowley for taking the time to share this with the Windows documentation team. Unfortunately, this is something the docs team cannot answer, but I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
