### ISSUE TITLE
Incorrect link in documentation

### ISSUE THREAD

**Issue by jdaws2019** [MicrosoftDocs/windows-itpro-docs#10320]
The link in number 3 of this section points to a 404:
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-security-configuration-framework/windows-security-baselines#where-can-i-get-the-security-baselines

It is linked as:
(https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-mdm-all.md)

I removed the ".md" and got to what I believe is the correct page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3deb045-565e-169b-ecd4-6f0f07c966e4
* Version Independent ID: 1bd84f68-4820-4d11-aafc-da1657bddc80
* Content: [Security baselines guide - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-security-configuration-framework/windows-security-baselines)
* Content Source: [windows/security/threat-protection/windows-security-configuration-framework/windows-security-baselines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-security-configuration-framework/windows-security-baselines.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@e0i error link is already fixed , so please close #10320
