### ISSUE TITLE
2019 'ugs' scope description

### ISSUE THREAD

**Issue by kklouzal** [MicrosoftDocs/windows-itpro-docs#10338]
This note is misleading:
![image](https://user-images.githubusercontent.com/2928845/152263514-5926eb01-b513-4d3c-bb0f-aaba50635e13.png)
It specifically states when a 'Hybrid Certificate trust is performed'. This may be the case for the 'known PRT issue', however, in a 100% on-prem configuration, WHFB will NOT attempt to provision on client endpoints unless this workaround is implemented. The ADFS Admin event logs stated in the note do not show up, however, provisioning will not happen until this workaround is implemented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b063e00b-84e5-9da7-2229-e0e24da3b877
* Version Independent ID: da9f4867-2aa3-aefa-1603-ddb2ab1ed624
* Content: [Prepare and Deploy Windows AD FS certificate trust (Windows Hello for Business) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md)
* Product: **m365-security**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by yogkumgit** [comment]
@paolomatarazzo Please help us in resolving this issue. Thanks

**Comment by paolomatarazzo** [comment]
Thank you @kklouzal, I'm updating the documentation based on different feedback that you submitted.
