### ISSUE TITLE
Enroll for a TLS Server Authentication Certificate Additional Information Needed

### ISSUE THREAD

**Issue by kklouzal** [MicrosoftDocs/windows-itpro-docs#10339]
The 'Enroll for a TLS Server Authentication Certificate' section is missing critical information.
There is only a brief mention of _'enterpriseregistration.contoso.com'_ which is critical for ADFS Device Registration. This needs to be touched on way more in the documentation, it was a stumbling block for me in the beginning.
Secondly, there is absolutely no mention of 'certauth.fs.contoso.com' as a Subject Alternative Name which is something the ADFS configuration during setup looks for. This needs to be touched on in the documentation.
It needs to be said that 'Subject Name' can be a wildcard, along with including a wildcard 'Subject Alternative Name'.
It should also be noted that 'certauth.fs.contoso.com' and 'enterpriseregistration.contoso.com' need to be explicitly defined as Subject Alternative Names even if a wildcard is present or the configuration will complain and throw a warning.
Finally it needs to be mentioned that BEFORE moving into the next step in the server configuration wizard the user needs to open up DNS and create their A records and CNAME records. It needs to be explicitly stated that the 'fs.contoso.com' HAS to be an A record, it CANNOT be a CNAME...
I think that about covers it...

Oh yes.. This section:

> You can; however, issue one certificate for all hosts in the farm. If you chose this option, then leave the subject name blank, and include all the names in the subject alternate name when creating the certificate request. All names should include the FQDN of each host in the farm and the federation service name.

What?? Optionally use the same certificate across all hosts in your farm? How do all my hosts automatically renew the same certificate from my AD Certificate Authority? Do I need to manually copy the certificate to all hosts when the cert is renewed? That sucks.. What about the other option? The wording/verbiage implies that there is an alternate method of using a separate certificate for each individual host, this sounds a lot better since certs can automatically renew from AD CS. Why does the documentation mention nothing of how to set this up???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b063e00b-84e5-9da7-2229-e0e24da3b877
* Version Independent ID: da9f4867-2aa3-aefa-1603-ddb2ab1ed624
* Content: [Prepare and Deploy Windows AD FS certificate trust (Windows Hello for Business) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md)
* Product: **m365-security**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by yogkumgit** [comment]
@paolomatarazzo Please help us in resolving this issue. Thanks

**Comment by paolomatarazzo** [comment]
Thank you for the feedback @kklouzal. I made some changes to the documentation to address these asks.
