### ISSUE TITLE
Use Azure RMS for WIP. Determines whether WIP uses Microsoft Azure Rights Management

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#10331]
Hello,

I don't think that "Azure Rights Management" is good here, as far I know Azure Rights Management has been replaced by Unified Labeling isn't it?

And hyperlink is broken "Use Azure RMS for WIP. Determines whether WIP uses **Microsoft Azure Rights Management**"
Here I guess it should point to https://docs.microsoft.com/en-us/azure/information-protection/what-is-azure-rms

So could be good to update the link and maybe to replace the naming? As possibly no longer possible to deploy Azure Rights Management or Azure Information Protection, only the Office 365 Unified Labeling.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df27add-73fe-4f0b-7e30-face0f95cda3
* Version Independent ID: 3ec647d9-3470-8d8b-a941-d56f6522a35e
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@lightupdifire The link has been fixed and it points to the article you mentioned.

Regarding Microsoft Azure Rights Management, according to [this article](https://docs.microsoft.com/en-us/azure/information-protection/aka#does-azure-information-protection-now-replace-all-these-names) it is still used.

> As the cloud-based solution that you purchase, yes. Azure Information Protection offers the new capabilities of classification and labeling for an organization's documents and emails, which in turn can apply Rights Management protection.

> **However, Azure Rights Management is still used as the protection technology for Azure Information Protection, and for Microsoft 365 services that use this cloud-based Rights Management protection. So in the context of the protection technology that is used by Azure Information Protection, "Azure Rights Management" (Azure RMS) remains a current name.**

**Comment by lightupdifire** [comment]
Thanks for the link update and explanation!
