### ISSUE TITLE
前段階Power Shell 7.2.1 tar.pz(?)と重複している要素が多い

### ISSUE THREAD

**Issue by Africanj1952** [MicrosoftDocs/windows-itpro-docs#10346]
[フィードバックをこちらに入力してください]

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 925dc0f5-2351-7dfb-9e50-ef87230f65bf
* Version Independent ID: f7ee7aca-7c9d-5b0f-1e92-a4a67fc21512
* Content: [必要な Windows 11 診断データ イベントおよびフィールド - Windows Privacy](https://docs.microsoft.com/ja-jp/windows/privacy/required-windows-11-diagnostic-events-and-fields)
* Content Source: [windows/privacy/required-windows-11-diagnostic-events-and-fields.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/required-windows-11-diagnostic-events-and-fields.md)
* Product: **m365-security**
* Technology: **privacy**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by denisebmsft** [comment]
こんにちは。私たちのドキュメントについて質問がありますか?どのように我々は助けることができる?
