### ISSUE TITLE
Windows Event log encodeings ... where does one find the meanings.

### ISSUE THREAD

**Issue by burnalting** [MicrosoftDocs/windows-itpro-docs#10345]
Using Windows Security Audit event code 5058 as an example, where can one find the mappings of the hexcodes of the **KeyType**, **Operation** or **ReturnCode** _Data_ attributes to their textual context ... eg "User or Machine key for KeyType, or Write/Read/Delete for Operation"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbfd140e-f0d0-cd3d-3cd2-1f3285eda407
* Version Independent ID: 135e2f4a-8ca5-99ba-f7aa-6f4fad71514a
* Content: [5058(S, F) Key file operation. (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5058)
* Content Source: [windows/security/threat-protection/auditing/event-5058.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-5058.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by burnalting** [comment]
It should be noted this is a question for all events. One needs to map the value offered for an enumerated element in any event to the **human readable** textual description.

**Comment by burnalting** [comment]
Hi @VLG17, My scenario is that I have a centralized logging system, where only the XML form of the event is provided. I wish to 'decorate' the event with the human readable form of any encoded values within the XML (given they are an enumeration).

If one can't document the individual, can we get a reference (link) to a source code item that might provide the codes and their meanings in an include file?

**Comment by VLG17** [comment]
Understood, in that case my advise would be to reach out to [Windows support](https://support.microsoft.com/contactus) and check if this possibility exists.

I can only help with creating a PR for editing the linked article.
