### ISSUE TITLE
Mistakes and Improvements

### ISSUE THREAD

**Issue by DCameo** [MicrosoftDocs/windows-itpro-docs#10356]
[Enter feedback here]
[Configure Automatic Certificate Enrollment](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings#create-the-windows-hello-for-business-group-policy-object
)
Mistake: this should be configured under **Computer Configuration**

[Configure Security in the Windows Hello for Business Group Policy object](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings#create-the-windows-hello-for-business-group-policy-object)
Mistake is repeated again: this needs to be configured under **Computer Configuration**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ec90f64-9a12-fdf9-25db-0e83cf77b7a2
* Version Independent ID: fb68756c-2d0c-c28c-4bda-ef6a876576e7
* Content: [Configure Windows Hello for Business Policy settings - certificate trust - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings.md)
* Product: **m365-security**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mapalko** [comment]
Windows Hello for Business can be configured as either a user GP or a computer GP. This is not wrong, but we could add a note that computer configuration can also be used. Would that address your issue?

**Comment by DCameo** [comment]
On my Windows Server 2016, I don’t see the policy settings described, unfortunately (they’re only present in Computer Configuration)
Is this different in Windows Server 2019+?
