### ISSUE TITLE
Please detail supported env variables

### ISSUE THREAD

**Issue by jerryabo** [MicrosoftDocs/windows-itpro-docs#10350]
"Type the path to the program in the text box. Use environment variables as appropriate to ensure that programs installed in different locations on different computers work correctly."

Env variables can be system or user defined, built-in to Windows or custom/user defined. From testing, it appears that custom variables are unsupported, i.e. they fail (via GPO, UX, or MDM). 

Please detail what env variables are supported so that it can be understood which are not.

(admin edit: refresh metadata with latest)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c673d2f-a224-8f9c-c3c8-fd8c09d084dc
* Version Independent ID: f6668ab2-72b0-1a58-f18b-09252f068e9d
* Content: [Create an Outbound Program or Service Rule (Windows)](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/create-an-outbound-program-or-service-rule)
* Content Source: [windows/security/threat-protection/windows-firewall/create-an-outbound-program-or-service-rule.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/create-an-outbound-program-or-service-rule.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by jerryabo** [comment]
Some primer drafted by @markstan that might be helpful for context/validation:

Examples of supported file paths:

Canonical path - a reference to a single executable file.

Ex: [C:\windows\notepad.exe](file:///C:/windows/notepad.exe)

 
Built-in System Variables

A supported environmental variable in the form %VARIABLE%\<path> where VARIABLE is one of the values in the list below and <path> is the relative path to the file.

Ex:  PROGRAMFILES(X86)\MyApp\Myapp.exe
%SYSTEMROOT%\Notepad.exe

Default system variables:


"ALLUSERSPROFILE", "APPDATA", "COMMONPROGRAMFILES", "COMMONPROGRAMFILES(x86)", "CommonProgramW6432", "HOMEDRIVE", "HOMEPATH", "LOCALAPPDATA", `
                        "PATH", "PathExt", "PROGRAMDATA", "PROGRAMFILES", "ProgramW6432", "PROGRAMFILES(X86)", "SystemDrive", "SystemRoot", "TEMP", "TMP", "USERNAME", `
                        "USERPROFILE", "WINDIR", "PUBLIC", "PSModulePath", "OneDrive", "DriverData"

**Comment by vinaypamnani-msft** [comment]
Adding relevant blog link pointed out by @jerryabo https://techcommunity.microsoft.com/t5/intune-customer-success/how-to-trace-and-troubleshoot-the-intune-endpoint-security/ba-p/3261452

**Comment by paolomatarazzo** [comment]
closing this issue as the Windows Firewall documentation is in the process of being refreshed. Will take under consideration the feedback.
