### ISSUE TITLE
%Manufacturer% should be %make%

### ISSUE THREAD

**Issue by garegin16** [MicrosoftDocs/windows-itpro-docs#10368]
Windows 10 x64\%Manufacturer%\%Model% should be Windows 10 x64\%Make%\%Model%. I don't think %Manufacturer% exists at all. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@garegin16 ,below  command is worked in windows 11 
wmic computersystem get model,manufacturer
![Screenshot 2022-03-02 100819](https://user-images.githubusercontent.com/3296790/156296006-c0e000b8-085c-499c-b27d-dc9777842cb2.jpg)

**Comment by greg-lindsay** [comment]
https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt#edit-the-windows-10-task-sequence

done
