### ISSUE TITLE
Incorrect Variable Name in Step 6

### ISSUE THREAD

**Issue by SaberSHO** [MicrosoftDocs/windows-itpro-docs#10366]
This has been reported before on Issue #9894, which is closed. However, this is still incorrect in the documentation. Below is the report form the original issue by dcdorsey777 which is still reflected on the page. You can also see their comment on Sep 20th, 2021 indicating that the page is still saying the incorrect variable name. Please correct this for the next poor soul who follows this guide and has the same problem with drivers not injecting correctly! Thanks

In Step 6 "Create the deployment task sequence", under substep "edit the Windows 10 task sequence", the text instructions in Step 2-a-iii specify to set DriverGroup001 to Windows 10 x64\\%Manufacturer%\\%Model%

%Manufacturer% is the incorrect variable name. The variable name for the manufacturer name is %Make%. This is shown correctly farther down the page in the figure "The task sequence for production deployment".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
https://github.com/MicrosoftDocs/windows-docs-pr/pull/6331
