### ISSUE TITLE
Like a deer in headlights

### ISSUE THREAD

**Issue by oggystoop** [MicrosoftDocs/windows-itpro-docs#1036]
still learning - this is far too baffling to me

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2399593c-cd60-af48-04c8-d6718cd3d1ec
* Version Independent ID: 20dedc08-413b-fda3-622a-f5c1058f85ca
* Content: [Delivery Optimization in Update Compliance (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-delivery-optimization#known-issues)
* Content Source: [windows/deployment/update/update-compliance-delivery-optimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/update-compliance-delivery-optimization.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by DaniHalfin** [comment]
@oggystoop - anything in specific we can simplify? What are you struggling with?

**Comment by andreabichsel** [comment]
Closing for now until issue is clarified.
