### ISSUE TITLE
MsiInstallJob with installation parametres

### ISSUE THREAD

**Issue by elshobokshy** [MicrosoftDocs/windows-itpro-docs#10376]
Hello,

I'm trying to install an application using the .msi file and a MsiInstallJob XML file.

However, the installation fails because the .msi contains fields that needs to be filled (credential fields). Is there a way to add, inside the XML file, the value to use inside those fields?

Kind regards,
Alexandre

**Comment by denisebmsft** [comment]
Hello @elshobokshy. To which article(s) does your feedback apply? This information will help us route the issue to the correct writer/team. Thank you!

**Comment by elshobokshy** [comment]
Hello @denisebmsft 

To this one : https://docs.microsoft.com/en-us/windows/client-management/mdm/enterprisedesktopappmanagement-csp

Thanks!

**Comment by vinaypamnani-msft** [comment]
@elshobokshy - I know this is quite late, but what kind of field does the MSI expect? If the MSI requires installation parameters, you could try specifying that to the `<CommandLine>` , for example `<CommandLine>/quiet MSIPARAM=VALUE</CommandLine>`.

If that doesn't help, there are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

At this time, I'm closing this issue as there's nothing actionable for docs but please reach out if this needs to be reactivated.

**Comment by elshobokshy** [comment]
> @elshobokshy - I know this is quite late, but what kind of field does the MSI expect? If the MSI requires installation parameters, you could try specifying that to the `<CommandLine>` , for example `<CommandLine>/quiet MSIPARAM=VALUE</CommandLine>`.
> 
> If that doesn't help, there are a couple of options available to provide the best level of support for this issue:
> 
> * Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
> * Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
> * Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.
> 
> At this time, I'm closing this issue as there's nothing actionable for docs but please reach out if this needs to be reactivated.

Hello @vinaypamnani-msft 

That's what I eventually figured out, thanks for the answer tho as it might help other people!

Have a great day :)
