### ISSUE TITLE
Clarification - Configure Chat Icon

### ISSUE THREAD

**Issue by homotechsual** [MicrosoftDocs/windows-itpro-docs#10373]
Please advise whether the information given for "Configure Chat Icon" is correct - it appears not to work on Business (which is odd if it works on Home and Pro) and there are numerous reports that this requires Enterprise or Education to function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e8ecbe3-ba72-ec44-0591-7f604d50b1e3
* Version Independent ID: 9d5ff118-d539-dd6e-ae3e-102392c22287
* Content: [Policy CSP - Experience - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-experience#experience-configurechaticonvisibilityonthetaskbar)
* Content Source: [windows/client-management/mdm/policy-csp-experience.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-experience.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @v-smandalika ,
in the change https://github.com/MicrosoftDocs/windows-itpro-docs/commit/40658a428afed2cfb45b00297d6e15134c72d918, the scope for Experience/ConfigureChatIcon was changed, it seems to be incorrect, could you please confirm? Home and Pro unlikely to have more possibilities than Business (as Business is just an extension for Pro edition)
Also, if the information is correct, I believe it should be added to https://docs.microsoft.com/en-us/troubleshoot/windows-client/application-management/managing-teams-chat-icon-windows-11#removing-the-chat-icon-using-intune as well

Thank you

**Comment by vinaypamnani-msft** [comment]
Thanks for the feedback @homotechsual - Looks like this was incorrectly changed and I'm fixing it now and closing this issue.
