### ISSUE TITLE
PCPTool does not support current WBCL format

### ISSUE THREAD

**Issue by mikebeaton** [MicrosoftDocs/windows-itpro-docs#10370]
The PCPTool listed in this page no longer works. It decodes the first (header) entry in the log then fails with `ERROR - PcpToolDecodeLog(): (0x80070057) The parameter is incorrect.`

It seems pretty clear from a bit of single-stepping that the log format is no longer what is assumed by that (fairly old) code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 688de6fb-2db0-8aa4-c89c-bda8e3a5c1c0
* Version Independent ID: e3415e74-19f4-0267-a9b9-f8fe444cd258
* Content: [Decode Measured Boot logs to track PCR changes - Windows security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/ts-bitlocker-decode-measured-boot-logs)
* Content Source: [windows/security/information-protection/bitlocker/ts-bitlocker-decode-measured-boot-logs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/ts-bitlocker-decode-measured-boot-logs.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tappelgate**

**Comment by mikebeaton** [comment]
I do not know if it is relevant to mention here, but for anybody looking to be able to read their own TPM logs (or, also, for some good links and info about the current log format), this [SO answer](https://stackoverflow.com/a/66476492/795690) lead me to this [PowerShell WBCL log parser](https://github.com/mattifestation/TCGLogTools) project, which from my limited - but not zero! - use of it so far, does a very good job.

**Comment by aczechowski** [comment]
This article was migrated to the Windows troubleshooting content library, which is owned by another team in support. I've shared this issue with them if they want to take action on it. I'm closing this issue as there's nothing actionable for my team since this content no longer exists in this repository.

**Comment by mikebeaton** [comment]
@aczechowski - Is there a link to a new public issue on a repo tracking this somewhere?

**Comment by aczechowski** [comment]
> @aczechowski - Is there a link to a new public issue on a repo tracking this somewhere?

No, sorry. The other repo doesn't accept public feedback (but it does accept public contributions). That's why I shared the feedback directly with the content owners.
