### ISSUE TITLE
Add IE to start menu

### ISSUE THREAD

**Issue by nalhemyari** [MicrosoftDocs/windows-itpro-docs#1038]
I'm unable to pin Internet Explorer (IE) to the start menu using this line, Windows 10 1709
&lt;start:DesktopApplicationTile Size="2x2" Column="0" Row="4" DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\Accessories\Internet Explorer.lnk" 
any idea/suggestion?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140f038c-e307-78f0-5165-309e0cf34ca5
* Version Independent ID: b1011259-ee05-21a4-5308-aabc8b0dd74b
* Content: [Configure Windows 10 taskbar (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/configure-windows-10-taskbar#sample-taskbar-configuration-added-to-start-layout-xml-file)
* Content Source: [windows/configuration/configure-windows-10-taskbar.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/configure-windows-10-taskbar.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
Are you applying the Start layout using Group Policy or MDM? There's a note in the Start layout XML (https://docs.microsoft.com/en-us/windows/configuration/start-layout-xml-desktop#startdesktopapplicationtile) that says "In Start layouts for Windows 10, version 1703, you should use DesktopApplicationID rather than DesktopApplicationLinkPath if you are using Group Policy or MDM to apply the start layout and the application was installed after the user's first sign-in."

**Comment by nalhemyari** [comment]
Using group policy. Unfortunately this is a desktop app 'Internet Explorer' not a modern app

**Comment by jdeckerms** [comment]
DesktopApplicationID entry for IE is: DesktopApplicationID="Microsoft.InternetExplorer.Default" 

Also, copy the .lnk to %ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\.

**Comment by nalhemyari** [comment]
Thanks for the ID. a question, why i need to move the shortcut outside of $appdata$ it works fine for File Explorer but not IE?

**Comment by jdeckerms** [comment]
I'm not positive that you do, but I found a thread on the forum with a problem similar to yours and that was the solution they found: https://social.technet.microsoft.com/Forums/en-US/d2a5d021-b5d9-4ce2-ba2c-d5bf0baf2345/exportimport-startlayout-doesnt-retain-ie-11-pin

**Comment by shortpatti** [comment]
Closing.
