### ISSUE TITLE
Combining Credential guard with Remote Credential guard

### ISSUE THREAD

**Issue by bartvermeersch** [MicrosoftDocs/windows-itpro-docs#10380]
The info doesn't mention if Credential Guard can be used together with Remote Credential Guard.

Should it be possible to use Credential Guard on a local host while using Remote Credential Guard to connect to a remote server? The connection seem to succeed but when opening a file share on the remote server, it seems impossible to retrieve a Kerberos ticket via the local host.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c826587d-2e65-083f-254d-75f188158f08
* Version Independent ID: 746596b5-c1df-9ea0-abcc-f6ff97874e40
* Content: [Protect Remote Desktop credentials with Windows Defender Remote Credential Guard (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/remote-credential-guard)
* Content Source: [windows/security/identity-protection/remote-credential-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/remote-credential-guard.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@bartvermeersch Thank you for your feedback. Yes, it should be possible and the Remote Credential Guard will redirect any Kerberos requests back to the source machine. If you continue to have a problem, I'd recommend you contact Microsoft support so that this can be resolved.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
Thanks @bartvermeersch  for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:
- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
