### ISSUE TITLE
Information on vmdrv.sys addition to driver blocklist

### ISSUE THREAD

**Issue by voicemod** [MicrosoftDocs/windows-itpro-docs#10398]
Hi

We are Voicemod S.L. a software company with a voice changer technology based in Spain.
On 16 Feb, commit 832a449ad83ca2e6fde4a4368b9ced6c7b4f2e1b our driver was added to the list of recommended blocked drivers. Because of that since 22257.1 W11 Insider preview the driver is not working, we contact microsoft support team and a Escalation Engineer on WDK (Matt P.) finally point us to this list.

We are try to understand why this happens and the way to removed our driver for this list.
Can we have more information or contact about this issue? To fully understand this incident and prevent it in future developments.

In the meantime we sent our driver to [Microsoft Security Intelligence Driver Submission page](https://www.microsoft.com/en-us/wdsi/driversubmission) to be scanned and we are running HLK on W11 to find vulnerabilities.

Thanks for your time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e8740b8-c1f2-4b88-3d4d-66cdbf20215f
* Version Independent ID: 7986a684-b35d-06bd-be30-dfca9923cb9c
* Content: [Microsoft recommended driver block rules (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules.md)
* Product: **m365-security**
* GitHub Login: @jgeurten
* Microsoft Alias: **dansimp**

**Comment by vinaypamnani-msft** [comment]
@jgeurten mentioned this was handled, so I'm closing this issue.

**Comment by davidsalajan** [comment]
As of today, vmdrv.sys is still incorrectly appearing on the blocked list when attempting to install: Windows 11, version 22H2.

<img width="310" alt="image" src="https://user-images.githubusercontent.com/26533908/201453196-98fff1f3-e562-4d0b-beb7-0e551a21b96d.png">

**Comment by voicemod** [comment]
Hi @davidsalajan,

Yes, our driver version 10.0.10011.16384 was rightly added to this list finally, we have followed Microsoft’s recommendations to make the driver more safer for our users.

We encourage you to get the last version of our software/driver in the official channel [[voicemod.net](http://voicemod.net/)](https://www.voicemod.net/)

Regards

**Comment by banjohojo** [comment]
Hi,
Yesterday (15.02.2023) new update appears in WIN11. After restart got the infor that something goes wrong and software restoring. Starts normaly, after login it gets some (more time) and raise the error with the message that vmdrv.sys cannot load. Blank screen appears all the time. Restoring options dont work, Im stuck and cannot remove last update. Something goes wrong. Any suggestions how to solve it?

**Comment by jgeurten** [comment]
Hi @banjohojo, are you seeing a blank screen when running voicemod only? You can update to the latest version of voicemod which is not blocked by Windows: https://www.voicemod.net

**Comment by banjohojo** [comment]
Hi, What you mean running voicemod only. Blank screen is all the time. Safety mode runs the same way. After login blank screen again. Even If I start with disable early lunch anti malware protection it's the same process. Need to find the way to update it somehow without windows.

**Comment by jgeurten** [comment]
Can you access the security app to disable the "Microsoft Vulnerable Driver Blocklist": https://support.microsoft.com/en-us/topic/kb5020779-the-vulnerable-driver-blocklist-after-the-october-2022-preview-release-3fcbe13a-6013-4118-b584-fcfbc6a09936 and reboot?

**Comment by banjohojo** [comment]
No, I cannot start the security app. I'll tried to disable it directly in regedit but still had the same issue. Finally I refresh the windows :( and now it's working :)
