### ISSUE TITLE
Screenshot image does not match recent Windows versions UAC credential dialog

### ISSUE THREAD

**Issue by modernman1** [MicrosoftDocs/windows-itpro-docs#10391]
[Enter feedback here]
The screenshot that shows the prompt to enter username password does not match current version of Windows - only a default admin username is shown, and a "More Choices" link below the password text box must be clicked before there is any indication that the user can input any other administrative username name/password combo. 

Suggest to include updated gif - see (https://social.technet.microsoft.com/Forums/windows/en-US/6ba968a3-004a-4eaf-9679-74d411431f2c/how-to-customize-uac-prompts?forum=win10itprosecurity)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 495688e2-ca8d-a005-19d2-5ee9138c86f2
* Version Independent ID: 760f236c-5eb0-00cd-9553-990f29ee5aa4
* Content: [How User Account Control works (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/how-user-account-control-works)
* Content Source: [windows/security/identity-protection/user-account-control/how-user-account-control-works.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/user-account-control/how-user-account-control-works.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment]
Thanks @modernman1 for the feedback. A community member submitted a change for this issue, which should go live around 11 AM Pacific on 4 May.

**Comment by modernman1** [comment]
Thank you for taking the time to do this.
