### ISSUE TITLE
The Day Windows Stopped Being Fun

### ISSUE THREAD

**Issue by 12bucklemyshoe** [MicrosoftDocs/windows-itpro-docs#10393]
[the cryptic life-ending instructions to get out of inaccessible boot device ruined it for me - I have had it with Insider anything.  Microsoft breaks people and computers.  I know its you and not my computers.  Thanks god for pirates; no one could be as destructive as Microsoft.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 388514ac-6488-384c-fb86-e8dfd3970a28
* Version Independent ID: 7cd69358-f4bc-67a2-ba27-ea20f0946e32
* Content: [Advanced advice for Stop error 7B, Inaccessible_Boot_Device - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-inaccessible-boot-device)
* Content Source: [windows/client-management/troubleshoot-inaccessible-boot-device.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/troubleshoot-inaccessible-boot-device.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by vinaypamnani-msft** [comment]
Thanks @12bucklemyshoe for taking the time to share this with the Windows documentation team. I’m sorry that you’ve had problems. Please let us know what parts of this document were cryptic, so we can work on improving it. 

Alternatively, to get support on this, you can post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.

I'm closing this issue as there's nothing actionable for docs at this time, but feel free to reopen this issue and provide more details.
