### ISSUE TITLE
Explanatory note for Co-Management 

### ISSUE THREAD

**Issue by msarnabm** [MicrosoftDocs/windows-itpro-docs#10405]
An explanatory note for co-managed devices to leverage the enrollment method described in this Doc's link: https://docs.microsoft.com/en-us/mem/configmgr/comanage/tutorial-co-manage-clients

This is the only supported way for using Device Credentials for co-managed devices since the GPO toggle for Device Credentials isnt supported on Co-managed devices.

(admin edit: updating doc details to the latest)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 25a6e341-93c9-7012-48ee-e6b3e8323f13
* Version Independent ID: 25a6e341-93c9-7012-48ee-e6b3e8323f13
* Content: [Enroll a Windows 10 device automatically using Group Policy - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
There was a recent edit to the note via #11255. Otherwise we're not entirely clear what the feedback in this issue is regarding. So I'm closing the issue. If there's still further clarification needed, please reopen and provide from detail (or contact us internally 😉 )

**Comment by aczechowski** [comment]
FYI Paolo is going to revise based on further detail in #10611
