### ISSUE TITLE
"ShareCartPC"

### ISSUE THREAD

**Issue by rosswestgarth** [MicrosoftDocs/windows-itpro-docs#10415]
There is a reference to "ShareCartPC" on this page.  I can find no reference to it anywhere else on the internet!  Please help me understand the reference?

Ross

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ca58bd-f279-7739-0140-c4bd56784768
* Version Independent ID: 1d2ecc90-58a3-6bcd-84ae-ef04d7a3b7b4
* Content: [Policy CSP - Update - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update)
* Content Source: [windows/client-management/mdm/policy-csp-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment]
It's a typo. It should be [**SharedPC** CSP](https://docs.microsoft.com/windows/client-management/mdm/sharedpc-csp).

**Comment by paolomatarazzo** [comment]
This description has been updated.
