### ISSUE TITLE
Device registration type

### ISSUE THREAD

**Issue by rdudyk** [MicrosoftDocs/windows-itpro-docs#10429]
Could you explain exactly what type of registration require?
Could be one of:
Azure Ad Join
Azure Ad registered
Azure Hybrid Join

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d87ba3ab-d8a7-d038-2f7d-886bed956394
* Version Independent ID: cb2ea1fd-6a0d-8656-0bb4-0528c65ea03f
* Content: [Configure Device Registration for Hybrid Azure AD joined key trust Windows Hello for Business - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-devreg)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-devreg.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-devreg.md)
* Product: **m365-security**
* GitHub Login: @Gitprakhar13
* Microsoft Alias: **prsriva**

**Comment by rstenborg** [comment]
I agree, it's unclear if it supports domain joined machines with aad registration, or if hybrid join is required.

**Comment by rdudyk** [comment]
Hi, thanks on the main page you say:
 Device registration type: Azure AD join, Hybrid Azure AD join

**Comment by yogkumgit** [comment]
@msbemba

**Comment by paolomatarazzo** [comment]
This has been addressed by recent documentation updates
