### ISSUE TITLE
requirments

### ISSUE THREAD

**Issue by rdudyk** [MicrosoftDocs/windows-itpro-docs#10425]
Do I need to Azure Ad Premium licenses?
Do I need to Hybrid Azure Ad Join devices?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f37c7491-e550-86a8-5897-61d1a22c6631
* Version Independent ID: f37c7491-e550-86a8-5897-61d1a22c6631
* Content: [Hybrid Cloud Trust Deployment (Windows Hello for Business) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-trust)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-trust.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-trust.md)
* Product: **m365-security**
* GitHub Login: @Gitprakhar13
* Microsoft Alias: **prsriva**

**Comment by msbemba** [comment]
@rdudyk Thank you for your feedback. We have listed the prerequisites and unsupported scenarios in the document here -https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust?tabs=intune#prerequisites

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @rdudyk Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
