### ISSUE TITLE
The Credential type dropdown does not show (Auto MDM Enrollment, AD, GPO)

### ISSUE THREAD

**Issue by rsbedard** [MicrosoftDocs/windows-itpro-docs#10435]
I am currently working in a customer environment and we tried to deploy MDM template but the section in the middle left was empty.

Can anyone tell me how I can fix this? Do I need to update the template or do I need to update the domain controller level.

Please let me know,

**Comment by RAJU2529** [comment]
@rsbedard . Which article are you referring to ?

**Comment by rsbedard** [comment]
Auto MDM Enrollment - Differences between User/Device Credentials #4828

**Comment by aczechowski** [comment]
Thanks @rsbedard for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

We are reviewing all of the MDM documentation and specifically those for enrollment, so expect to have some broader revisions published in the near future. So I'm closing this issue.
