### ISSUE TITLE
Capture does not work for windows 10 21h2

### ISSUE THREAD

**Issue by somescout** [MicrosoftDocs/windows-itpro-docs#10432]
Looks like step "Apply Windows PE (BCD)" does not work after sysprep - VM restarts to current system without booting WinPE (Hyper-V VM hosted by Windows Server 2016)

As workaround I extracted from LTISysprep script to commit pending renames, and put them in following way:
1. Commit pending renames
2. Apply Windows PE (BCD)
3. Sysprep

This way OS being captured correctly.

But it would be nice to have supported solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0eb8c97-caa0-bb05-4b91-14ad2adc4aac
* Version Independent ID: 0cc541a3-8198-c029-d795-308e673ee2f4
* Content: [Create a Windows 10 reference image (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image)
* Content Source: [windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by msbemba** [comment]
@somescout Thank you for your feedback. The step Apply Windows PE (BCD) should work after Sysprep. If you continue to have this issue, I'd recommend contacting Microsoft support so it can be fixed or escalated to the product group.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
Thanks @somescout  for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:
- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
