### ISSUE TITLE
Convenience PIN Date

### ISSUE THREAD

**Issue by alevere** [MicrosoftDocs/windows-itpro-docs#10431]
Please publish a date to deprecate convenience PIN for an enterprise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82ecd7ea-0ecb-cf7b-a1ab-9cda97e5cc0a
* Version Independent ID: 81acb0ad-2d46-bd0b-abb5-7c2e851d7a71
* Content: [Windows Hello for Business Frequently Asked Questions (FAQ) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-faq)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-faq.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-faq.yml)
* Product: **m365-security**
* GitHub Login: @Gitprakhar13
* Microsoft Alias: **prsriva**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @alevere Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
