### ISSUE TITLE
Multi-app kiosk

### ISSUE THREAD

**Issue by Elis150** [MicrosoftDocs/windows-itpro-docs#10449]
Hello, 

i was project to make multi-app kiosk with AD user
Attached txt file with code

[New Text Document (2).txt](https://github.com/MicrosoftDocs/windows-itpro-docs/files/8352588/New.Text.Document.2.txt)
i used this guid 
https://techdirectarchive.com/2020/01/31/kiosk-mode-deployment-on-windows-10-with-an-ad-domain-account/

but after i runing this kiosk will create local user

the point is i need to create on AD user to reach some documentation which are in file server.

so maybe any ideas how to fix this.

**Comment by yogkumgit** [comment]
Thanks @Elis150 for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:
- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
