### ISSUE TITLE
migrate w10 oem to w10 (to be used in WmWare)

### ISSUE THREAD

**Issue by Berty9** [MicrosoftDocs/windows-itpro-docs#10442]
Hi,
If I use my w10oem on my WMware, I will get some issues.
So, which licence do I need, to use my Wmware every time, every where ?
And how it's work to buy it and to Upgrade ? 
thanks

**Comment by denisebmsft** [comment]
Hello @Berty9. Can you please tell us to which article your feedback applies? This information will help us route the issue correctly. Thank you!

**Comment by Berty9** [comment]
may be this one  : https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4094
or another
