### ISSUE TITLE
Conflict with NIST 800-63

### ISSUE THREAD

**Issue by nchpf** [MicrosoftDocs/windows-itpro-docs#10453]
The recommendation to enable secure desktop as a best practice conflicts with NIST's recommendation to allow pasting of passwords to enable/encourage complex passwords...
o	https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf?page=24
o	https://www.thesslstore.com/blog/nist-password-pasting/
o	https://www.ncsc.gov.uk/blog-post/let-them-paste-passwords

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac17ceb6-52c3-0b85-8dd8-998f7bffd7a5
* Version Independent ID: ab416216-7ad6-998d-27d1-426cfd0961b2
* Content: [User Account Control Switch to the secure desktop when prompting for elevation (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-account-control-switch-to-the-secure-desktop-when-prompting-for-elevation)
* Content Source: [windows/security/threat-protection/security-policy-settings/user-account-control-switch-to-the-secure-desktop-when-prompting-for-elevation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/user-account-control-switch-to-the-secure-desktop-when-prompting-for-elevation.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@nchpf This is a valid feedback and I recommend to use the builtin [Feedback Hub App](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) in Windows to share this feedback and ask for a feature request - being able to paste within a Secure Desktop session.

Similar requests exist - see here[https://github.com/keepassxreboot/keepassxc/issues/3460](url)

If the feature is approved, we can help with changing the documentation.
