### ISSUE TITLE
How to update policy templates

### ISSUE THREAD

**Issue by jotheman0303** [MicrosoftDocs/windows-itpro-docs#10465]
The article looks rather complete, only thing I would recommend adding would be to describe how to update the Group Policy templates to enable having the options required available in GPO's

(admin edit: update doc details with the latest)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7739850a-a445-faf1-eec8-8aecb6de8b95
* Version Independent ID: 7739850a-a445-faf1-eec8-8aecb6de8b95
* Content: [Windows Hello for Business Cloud Kerberos trust deployment](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust?tabs=intune)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by RAJU2529** [comment]
@jotheman0303 , i knew it, but author of the article should accept it before adding in to article

**Comment by paolomatarazzo** [comment]
Hello @jotheman0303 and thank you for the feedback. The article includes a link with detailed instructions how to update the templates as well as update the central store. Please check this link: https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust?tabs=gpo#update-administrative-templates
