### ISSUE TITLE
missing Windows IoT Enterprise policy csp reference

### ISSUE THREAD

**Issue by sveinungre** [MicrosoftDocs/windows-itpro-docs#10474]
The page "Policies in Policy CSP supported by Windows 10 IoT Enterprise" is visible in the search/filter on the left side, but the link does not lead to Windows IoT Enterprise, where has the content gone? I very much desire to read that page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e7455a-e798-e89e-a9bf-bdff51d00ba6
* Version Independent ID: 7dc81b34-4cc2-2ecc-bb5b-9900b85e3817
* Content: [Policies in Policy CSP supported by Windows 10 IoT Core - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policies-in-policy-csp-supported-by-iot-core)
* Content Source: [windows/client-management/mdm/policies-in-policy-csp-supported-by-iot-core.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policies-in-policy-csp-supported-by-iot-core.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by vinaypamnani-msft** [comment]
Hey @sveinungre, we're working on automating the CSP docs, and we don't have a supportability indicator for IoT Enterprise to automate this information so I'm closing this issue at this time.
