### ISSUE TITLE
0x801c03f2 not listed

### ISSUE THREAD

**Issue by MrShannon007** [MicrosoftDocs/windows-itpro-docs#1047]
Setting a PIN in a VM is failing with 0x801c03f2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
Hi @MrShannon007. Thanks for reaching out and sorry it took us so long to respond.
I realize that this issue might be irrelevant at this point, either way, for future reference - 
For error codes unlisted here, in most cases those are transient error codes being surfaced by other services in the Windows Hello dependency chain.
We are working on something to improve the user experience in that regard, but that will not solve the issues you are experiencing.
If we find a reoccurring error codes that isn't covered here and should be (meaning, in most cases, it is coming from Windows Hello and not other components) we'll make sure to add it to this page.
For any issue you're seeing, please either file a problem through Feedback Hub, or reach out through our various support channels. Both avenues allow us to properly investigate the issue in ways we could never do through a comments section on a GitHub issue.
The feedback section in the topic is generally meant for feedback on the content, and we can't really use it for in-depth troubleshooting.
We thank you for taking the time to reach out, but we also want you to have the best time to resolution of the issue, and going through this feedback channel won't get us there.
I'll be closing this issue, but feel free to respond if you feel we missed something. We can always re-open.
