### ISSUE TITLE
Error in Documentation

### ISSUE THREAD

**Issue by tryhardriceboy** [MicrosoftDocs/windows-itpro-docs#10484]
Hi,

I believe I've found an error in your documentation.  It refers to the environment variable '%Manufacturer%', but as far as I'm aware this variable does not exist - it should be set to '%Make%' instead.

To fix this error, just one line in the documentation needs to be changed:

OLD ==> Value: Windows 10 x64\%Manufacturer%\%Model%
NEW ==> Value: Windows 10 x64\%Make%\%Model% 

It seems the author of the article may have been confused by the 'WMIC' manufacturer/model fields, but the environment variables in MDT need to be make/model instead.

Regards,

Trevor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @tryhardriceboy for the feedback. I conveniently just fixed this yesterday.

(internal reference MicrosoftDocs/windows-docs-pr#6525)
