### ISSUE TITLE
What does "human presence sensor" exactly means?

### ISSUE THREAD

**Issue by peterweiweiwang** [MicrosoftDocs/windows-itpro-docs#10486]
What does "human presence sensor" exactly mean in this policy?
Is it HID Biometric Human Presence sensor? Or is it something like TOF sensor?

Thanks for your help on clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53c259bd-bfb2-91f3-86ba-374bb3623a13
* Version Independent ID: 53c259bd-bfb2-91f3-86ba-374bb3623a13
* Content: [Policy CSP - HumanPresence - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-humanpresence)
* Content Source: [windows/client-management/mdm/policy-csp-humanpresence.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-humanpresence.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@peterweiweiwang , I think, a biometric device with Realsense camera, it will be used for windows facial recognition

**Comment by MaratMussabekov** [comment]
Hello @peterweiweiwang ,
**What does "human presence sensor" exactly mean in this policy?** - It could be anything. Whatever is connected/built-in to your PC and identified by OS as presence sensor.
Thank you
