### ISSUE TITLE
Positively identify information in table "Supported Windows 10 downgrade paths"

### ISSUE THREAD

**Issue by RhysCLCsAustralia** [MicrosoftDocs/windows-itpro-docs#10499]
Tab
When viewing the table "Supported Windows 10 downgrade paths" the lack of cell outlines and the use of a blank cell to positively identify an outcome makes the table very hard to read.
Please update the table "Supported Windows 10 downgrade paths" to positively identify the situation for all scenarios:
https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-edition-upgrades#supported-windows-10-downgrade-paths

✔ = Supported downgrade path
❌ = Not supported
NA = Not considered a downgrade or an upgrade

[blank] = Not supported or not a downgrade
Edition	Home	Pro	Pro for Workstations	Pro Education	Education	Enterprise LTSC	Enterprise
Home	NA	❌	❌	❌	❌	❌	❌
Pro	❌	NA	❌	❌	❌	❌	❌
Pro for Workstations	❌	❌	NA	❌	❌	❌	❌
Pro Education	❌	❌	❌	NA	❌	❌	❌
Education	❌	✔	✔	✔	NA	❌	NA
Enterprise LTSC	❌	❌	❌	❌	❌	NA	❌
Enterprise	❌	✔	✔	✔	NA	❌	NA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d622668-cedc-5eec-4a1b-441ce84d3126
* Version Independent ID: 7da5e009-c1ac-0f18-c945-564da440e90f
* Content: [Windows 10 edition upgrade (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-edition-upgrades)
* Content Source: [windows/deployment/upgrade/windows-10-edition-upgrades.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/windows-10-edition-upgrades.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @RhysCLCsAustralia for the feedback, I totally agree. It should also use more consistent notation between the two tables on the same page. While they have different meanings, they should at least follow a similar pattern.

**Comment by RhysCLCsAustralia** [comment]
@aczechowski Thanks for the response - I actually searched directly for the downgrade info missed the first table., glad you're on the ball!

**Comment by aczechowski** [comment]
Thanks @VLG17 for the edit! I _think_ the table format and images will display ok, but will need to wait until it publishes to be sure. The change needs to sync to our private repo, then wait for daily publishing. So I _hope_ that will happen tomorrow (Wednesday, 13 July) around 1030 or 1530 Pacific. Once the changes are published, please let me know if the table formatting still looks wonky. I can make an edit via our private repo, which provides a preview before we publish. 😉
