### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by lumirjasny** [MicrosoftDocs/windows-itpro-docs#10491]
The bold-italic marked word "foreground" should be "background".

citation: 

Maximum Background Download Bandwidth
Starting in Windows 10, version 1803, specifies the maximum background download bandwidth that Delivery Optimization uses across all concurrent download activities as a percentage of available download bandwidth. The default value of "0" means that Delivery Optimization dynamically adjusts to use the available bandwidth for **_foreground_** downloads. However, downloads from LAN peers are not throttled even when this policy is set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a90fbf8-f755-5b82-5c21-fde7e30bd395
* Version Independent ID: 1a90fbf8-f755-5b82-5c21-fde7e30bd395
* Content: [Delivery Optimization reference - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/do/waas-delivery-optimization-reference#maximum-foreground-download-bandwidth)
* Content Source: [windows/deployment/do/waas-delivery-optimization-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/do/waas-delivery-optimization-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @carmenF
* Microsoft Alias: **carmenf**

**Comment by aczechowski** [comment]
Thanks @lumirjasny for the feedback! The change should publish tomorrow morning Pacific time.

In the future, you can submit these changes yourself! 😉 For more info, see http://docs.microsoft.com/contribute on how to make quick edits to documentation.
