### ISSUE TITLE
Validate "applies to" list

### ISSUE THREAD

**Issue by JamesTStanley** [MicrosoftDocs/windows-itpro-docs#10496]
[Enter feedback here]
The "applies to" section at the top of this page lists several versions of Windows Server, but I don't think that's right - this article is about Windows 10/11 clients

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1684b30a-3187-85ce-0cf7-10d1b8298b7f
* Version Independent ID: 9b7170fc-2b39-8e46-7898-894a45de8623
* Content: [Configure Windows Update for Business - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-configure-wufb)
* Content Source: [windows/deployment/update/waas-configure-wufb.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-configure-wufb.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I checked with a PM for WUfB who confirmed the policies support server OS, so that reference is accurate. However, she did clarify:

> That is correct noting that Server OS (outside of HCI) does NOT get Feature Updates from WU so really only the quality update policies apply. 

That's probably a good point that's worth noting here.
