### ISSUE TITLE
Why So Fk'd?

### ISSUE THREAD

**Issue by MrDravenX** [MicrosoftDocs/windows-itpro-docs#1050]
Everyone I talked to who have updated to the 1803 version has had issues.  Some minor but there are a lot of series ones.  I can't even install the update myself and with all the negatives reviews I'm hearing about I'm glad I can't update.  Is there any fixes for 1083?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c880203c-6a5b-28e7-c74d-152890baa955
* Version Independent ID: 59c9eb13-dd44-358a-130d-ca1e020573ba
* Content: [What's new in Windows 10, version 1803](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1803)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1803.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1803.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by lizap** [comment]
Sorry to hear that you're having issues. Have you seen the new [Setupdiag](https://docs.microsoft.com/en-us/windows/deployment/upgrade/setupdiag) tool? It might be able to help you figure out what's going wrong. You can also find support on the [Microsoft Support](https://support.microsoft.com/en-us) page, including a virtual agent who can help you find useful information. If none of those help, please use the [Feedback app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) to provide specific problems/issues you're running into. Thanks.
