### ISSUE TITLE
Information for UEFI network boot to load Windows PE 

### ISSUE THREAD

**Issue by mqqqqqqq** [MicrosoftDocs/windows-itpro-docs#10505]
Hi,
I was looking at this document to attempt to UEFI network boot WinPE (Windows 10), but it seems this is more for legacy bios instead of UEFI.  Is there any pointers on how to get this to work under UEFI?

Thanks,

Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6a95648-e93d-fdd5-b52f-afca6e49a139
* Version Independent ID: 607d9bc8-de81-eb28-5326-434e1cf6a696
* Content: [Configure a PXE server to load Windows PE (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/configure-a-pxe-server-to-load-windows-pe)
* Content Source: [windows/deployment/configure-a-pxe-server-to-load-windows-pe.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/configure-a-pxe-server-to-load-windows-pe.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @mqqqqqqq for the feedback. I checked with a SME, who confirmed that:

> Although the actual instructions seem to apply to either MBR/BIOS or UEFI, the PXE boot process summary part does only reference MBR/BIOS. For example steps one and two mentions PXEboot.n12. That is MBR/BIOS boot file. UEFI uses different boot files that end in .efi.

But we'll need to do some more investigation/testing to determine if the BCD configuration is different, and if so what are the steps. We plan to generally review/revise the Windows deployment content in the future, so it's good to get this feedback.

**Comment by frankroj** [comment]
Thank you for the feedback @mqqqqqqq. We have added this for consideration for future updates to the article.
