### ISSUE TITLE
Is this Version 1607 support for Developer Mode?

### ISSUE THREAD

**Issue by wdgoh** [MicrosoftDocs/windows-itpro-docs#10506]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9553b4c-8e2c-cbf2-bdfb-ebb0f2e92069
* Version Independent ID: 6f530596-e463-706d-16d3-540d688cf6c1
* Content: [What's new in Windows 10, version 1607 (Windows 10) - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1607)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1607.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/whats-new-windows-10-version-1607.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @wdgoh, according to the [System requirements](https://docs.microsoft.com/windows/apps/windows-app-sdk/system-requirements#windows-app-sdk) article associated with the articles to enable developer mode, Windows 10, version 1809 and later is required for the Windows App SDK. But I don't know if that means it's also the requirement for enabling developer mode. I'll check with some others.

**Comment by aczechowski** [comment]
Thanks @wdgoh for the feedback. Given the age of this issue, and reference to a version of Windows that's now unsupported, I'm going to close it.
