### ISSUE TITLE
Bitlocker Issues

### ISSUE THREAD

**Issue by Homayoon12** [MicrosoftDocs/windows-itpro-docs#1051]
Hey I hope you well be fine.
I have an issue with unlocking the bitlocker i have the password but when i want to open it the system wants the recovery key but unfortunately i don't have it but i have the password  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a2b6bec-05af-1e20-a22e-d2a0c71a7dca
* Version Independent ID: 5c644e57-ae1b-a510-ebdb-52391fb6407f
* Content: [BitLocker frequently asked questions (FAQ) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-deployment-and-administration-faq)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-deployment-and-administration-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-deployment-and-administration-faq.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@Homayoon12 sorry for delay. Please see this topic for info about retrieving your recovery key: https://support.microsoft.com/en-us/help/4026181/windows-10-find-my-bitlocker-recovery-key

**Comment by Justinha** [comment]
@Homayoon12 At the end of the article I shared, it says that if you did not save your recovery key anywhere, you'll need to reset your computer, and it has a link to more info about how to reset your pc here: https://support.microsoft.com/en-us/help/12415
