### ISSUE TITLE
Screenshot of system summary is too old

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#10519]
This article has old screenshot of the system summary which indicates intel i5-2500 processor and  the system does not booted in Secure mode. so screenshot should change with new latest processor.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d4b8d75-5d09-e0d6-1a90-45175fd1043d
* Version Independent ID: dfb10d10-a514-6ea5-1307-df865db530db
* Content: [Enable virtualization-based protection of code integrity - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity)
* Content Source: [windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@Dansimp , i am  trying to add below  screenshot, taken from intel i5-7200U which supports uefi and secure boot.
![systemsummary](https://user-images.githubusercontent.com/3296790/167240524-c2b5d664-8387-44c0-b3ed-0d956d751848.png)

**Comment by RAJU2529** [comment]
@Dansimp , just now I tried add a screenshot ,but adding the location of the image , ,in preview section , image does not visible , only , location path s visible 

**https://user-images.githubusercontent.com/3296790/167240524-c2b5d664-8387-44c0-b3ed-0d956d751848.png**

preview 
![Screenshot 2022-05-07 112949](https://user-images.githubusercontent.com/3296790/167240853-36bf56c1-54bc-4279-b29c-f1f12212752d.gif)

**Comment by aisgbnok** [comment]
@RAJU2529 It looks like you are adding a GitHub user link, which is not recommended. You want to replace actual image file at https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/device-guard/images/dg-fig11-dgproperties.png with your screenshot. Save it in the same location with the same name.

<p align="center">
  <img alt="Windows Snipping Tool" src="https://user-images.githubusercontent.com/10838153/167829709-fefba39c-a420-42a7-b04f-44e00ebce482.png">
</p>

I also recommend you take your new screenshot with the Window Mode in Windows Snipping Tool (<kbd>WIN</kbd> + <kbd>Shift</kbd> + <kbd>S</kbd>) so there aren't any extra artifacts. (Like the green `0/S` in your screenshot.)

Lastly, not super important, but your device can be updated to [OS Build `22000.675` if you want the latest stable Windows 11 release](https://support.microsoft.com/topic/may-10-2022-kb5013943-os-build-22000-675-14aa767a-aa87-414e-8491-b6e845541755) for your screenshot. Hope this helps!

**Comment by aisgbnok** [comment]
@RAJU2529 Most importantly I just realized this image is supposed to show "Windows Defender Device Guard properties" in System Information. So when you take your screenshot please ensure it shows "the bottom of the System Summary section," with those settings enabled!

**Comment by yogkumgit** [comment]
@msbemba
