### ISSUE TITLE
Allow Telemetry instructions are contradictory

### ISSUE THREAD

**Issue by callahan22** [MicrosoftDocs/windows-itpro-docs#10510]
Allow Telemetry | 1 - Basic | Configures the maximum allowed diagnostic data to be sent to Microsoft. Individual users can still set this value lower than what the policy defines. See the following policy for more information.

That's not accurate. 3 is the maximum allowed data. So now I'm not sure which to use. The stated "1" or "3" which would match the description you're giving.

Can you confirm which one we use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37a5ef77-5d80-ce40-7243-c96f708e907c
* Version Independent ID: 3e24d136-6af4-2531-31fd-feac09f37901
* Content: [Manually configuring devices for Update Compliance - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-configuration-manual)
* Content Source: [windows/deployment/update/update-compliance-configuration-manual.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-configuration-manual.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by RAJU2529** [comment]
@callahan22 , according ms docs  3-Optional is correct 
**https://docs.microsoft.com/windows/client-management/mdm/policy-csp-system#system-allowtelemetry**

**Comment by callahan22** [comment]
Hi @RAJU2529, not sure what you mean. The documentation for setting this up as a GPO:
Allow Telemetry | 1 - Basic

The explanation reads:
Configures the maximum allowed diagnostic data to be sent to Microsoft. Individual users can still set this value lower than what the policy defines. See the following policy for more information.

That explanation is misleading as it suggests that we should be using the "maximum" setting here. The maximum setting here would be 3 - Full. Which is it? 1 or 3?

Also, none of these options are optional as stated in the paragraph about this section of the guide:
"All Group policies that need to be configured for Update Compliance are under Computer Configuration>Administrative Templates>Windows Components\Data Collection and Preview Builds. All of these policies must be in the Enabled state and set to the defined Value below."

**Comment by aczechowski** [comment]
Thanks @callahan22 for the feedback. The following article in the Windows Privacy content should be considered the authoritative source for this information: [Configure Windows diagnostic data in your organization](https://docs.microsoft.com/windows/privacy/configure-windows-diagnostic-data-in-your-organization)

The value of `1` is what's required for features like Update Compliance to work. A value of `3` would send the most amount of data at the "optional" or "full" level. It looks like this Update Compliance article in general needs to be reviewed and updated.

> **NOTE**
> There were changes to this configuration in Windows 11 and the policy descriptions. For more info, see [Changes to Windows diagnostic data collection](https://docs.microsoft.com/windows/privacy/changes-to-windows-diagnostic-data-collection#behavioral-changes).
