### ISSUE TITLE
Add a notion about windows sandbox mouse settings behavior

### ISSUE THREAD

**Issue by Nils-Berghs** [MicrosoftDocs/windows-itpro-docs#10516]
Once again MS has succesfully degraded lefties to second class citizens. I understand that on installing a new operation system it uses a right handed mouse. When running such a 'new' operation system virtually it should either respect the mouse settings of the host system or communicate in terms of 'primary' and 'secondary' clicks instead of right or left.

I refuse to believe that this is a technical issue, nor that this is an oversight (a company the size of Microsoft certainly has some checks in place). The only remaining option is pure and intended discrimination op people who don't use the 'right' hand (pun intended). And if this is the case at least have the decency to communicate it. 

I sincerely hope that this gets fixed without a conviction for discrimination!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c06f3ef-5946-862a-ae14-f897fdb518ca
* Version Independent ID: cd6a8b99-b1e9-dff5-f174-a15840b304f0
* Content: [Windows Sandbox - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment]
@Nils-Berghs ⚠️ 
The [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/), which outlines the expectations for community interactions in and around docs.microsoft.com, is designed to help "provide a welcoming and inspiring community for all." The content of this issue is out of sync with the code of conduct. 

Normally, I would close it for this reason. However, it came to my attention because @michaelAngeloEgypt was kind enough to submit a contribution to the article to note the current technical behavior of Windows Sandbox. Once that pull request is merged, this issue will close.

I also suggest that you file [product feedback in the Feedback Hub](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) to share this bug with the engineering team. To help make sure the team reads and acts upon the feedback, please keep your feedback professional and constructive.

**Comment by Nils-Berghs** [comment]
So if I understand it correctly, it is ok to discriminate, but not to complain about it, because that is unprofessional....

And by the way I haven opened multiple tickets on the discrimination of left handed users in the feedback hub and guess what, none of them have been fixed yet.

**Comment by michaelAngeloEgypt** [comment]
Nils, I guess if your previous tickets were written with titles that rhyme with your original feedback title then they would have similarly lost their way to the Feedback team. "Discrimination" is too strong a word to describe the issue, which sounds to me like just the developers overlooking a special subset of people while it's possible to make that subset more comfortable.

**Comment by Nils-Berghs** [comment]
_We as members, contributors, and leaders pledge to make participation in our community a harassment-free experience for everyone, regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, caste, color, religion, or sexual identity and orientation.

We pledge to act and interact in ways that contribute to an open, welcoming, diverse, inclusive, and healthy community._

If only this would apply to MS-software itself...

- Ctrl+Insert, Shift+Insert an Shift+Delete have been Replaced by Ctrl+c,v,x for with right handed mouse user in mind. The old shortcuts still work but there are exeptions: shift delete is no cut in widows, when editing documents in teams Ctrl/Shift Insert do not work at al.
- Left handed mouse is not respected by Remote desktop, Remote assistance, Teams remote control, Sanbox.
- Windows+Insert does not open clipboard history.
- There is no way to set the mouse left handed on the login screen (it's called PC, notice the P)
- ...

Really, when using Microsoft products I often feel like my grandfather his teachers would hit him on the hand if he dared use his left hand for writing.
But maybe im overreacting it's not like people are being lynched simply for being left handed (Spoiler alert in some regions they still are)

**Comment by Nils-Berghs** [comment]
@michaelAngeloEgypt our posts crossed, but do you still think this is a mere oversight? If been trying for years to get things fixed (not for sandbox as that is relatively new).
One asks polite only that many times....

And I agree my title may have been way to strong but there is NO discussion possible about the fact that this IS discrimination (I'm even willing to believe that in this case it was an oversight, so I can rest assured? I have reported it on the feedback hub and it will be fixed in the next version? Surely Microsofts code of conduct can not allow such oversights?)

**Comment by Nils-Berghs** [comment]
@michaelAngeloEgypt on a more technical note: maybe also put in your change that just searching for mouse from the start menu in the sandbox will not work, you must manually open settings and look for mouse settings. 
I believe this has to do with the sandbox OS not being activated as it is a "new" system, but I guess you can understand that it feels like "adding insult to injury".

**Comment by michaelAngeloEgypt** [comment]
I see where you're coming from Nils, my only advise is to rally as much lefties (and sympathizers) as you can to upvote your feedbacks. At least in the digital realm lefties should have no such problems.

**Comment by aczechowski** [comment]
@Nils-Berghs I appreciate your passion, and I'm sorry for the difficulties you've experienced. Knowing the current culture of diversity and inclusion at Microsoft, this issue (and the others you noted) are to me undoubtedly oversights. I don't believe that anyone is purposefully coding the product in this way, it's most likely that such scenarios aren't tested, and as we know, bugs will always exist in software. But this experience is an excellent example of a bias that should be highlighted and improved upon in the future to be inclusive of all customers. As @michaelAngeloEgypt suggests, the wording and approach is key. If you can share links to the previous feedback that you've filed through the Feedback Hub, I can pass it along to some PMs that might be able to better influence change in the product.

**Comment by Nils-Berghs** [comment]
@aczechowski some of the issues I have created on the feedback hub (note that my attempts to get this fixed date back to way before the feedback even existed):

https://aka.ms/AAhl9un  (Quick assist)
https://aka.ms/AAhl4xa   (Teams)
https://aka.ms/AAhkx6k  (Clipboard history)
https://aka.ms/AAhlnnb (Sandbox, just created it, maybe previous ticket was deleted due to 'frustration'

An example of an older post (not by me)
https://social.technet.microsoft.com/Forums/en-US/7d053d2a-3567-4906-99e5-a8130842e202/rdp-and-lefthanded-mouse-users?forum=winserverTS

If you have any connections to get this fixed I would greatly appreciate it. And maybe (in the spirit of 'inclusiveness') you can also get the following issues fixed which are issues people are dealing with who are not working on a standard QWERTY keyboard and/or not having English as their mother tongue:

- The normal keyboard in my region is a french style, which requires SHIFT to enter numbers from the top row. As a result everybody uses the NUMPAD for entering numbers, and keyboards without numpad are rare (even on laptops). The inability to (reliably) set the NUMLOCK to ON at boot is a reason why people are actively refusing to use numbers on their windows password and a reason for a lot of IT support calls in companies where numbers are required (I can't think of any other small change that would have a positive impact on security that even comes close to this one)
- Same as for LEFT handed mouse RDP, Sandbox, Remote assistance do not respect the keyboad layout (changing the keyboard layout on a clients' server is often not appreciated, is a hassle for Sandbox, ....)
- The Windows store is an absolute mess in multi lingual countries (sorry there is no other way to put it). My computer is set to language 'English' and Culture Dutch-Belgium (As this is how I prefer it, and having the language set to english is also a company requirement). As a result the windows store app is partly in English, partly in Dutch, and partly in French. I can understand the english and the dutch (but that should be fixed), but the French ? Because the other half of the country is French? (just look for store language in feedback hub)
- Due to mild RSI in my right arm (by being coerced to use my mouse with the right hand for years?) I switched to the COLEMAK keyboard layout which is standard on all systems (Linux, Mac, Android, iOS) except windows. (Again search for COLEMAK in feedback hub)
