### ISSUE TITLE
MSI/ProductID/Name 404

### ISSUE THREAD

**Issue by andreamerico** [MicrosoftDocs/windows-itpro-docs#10511]
Hi,
I manage to install a .msi using ./Device/Vendor/MSFT/EnterpriseDesktopAppManagement/MSI/{productId}/DownloadInstall 
and got this message from the device 

`<Alert>
      <CmdID>4</CmdID>
      <Data>1224</Data>
      <Item>
        <Source>
          <LocURI>./Device/Vendor/MSFT/EnterpriseDesktopAppManagement/MSI/{productId}/DownloadInstall</LocURI>
        </Source>
        <Meta>
          <Type xmlns="syncml:metinf">Reversed-Domain-Name:com.microsoft.mdm.win32csp_install</Type>
          <Format xmlns="syncml:metinf">int</Format>
          <Mark xmlns="syncml:metinf">informational</Mark>
        </Meta>
        <Data>0</Data>
      </Item>
    </Alert>`

However, when I try to get the Name (or any other data) of the installed package I get a 404, here are the messages between server and client 

`<Get>
      <CmdID>6</CmdID>
      <Item>
        <Target>
          <LocURI>./Device/Vendor/MSFT/EnterpriseDesktopAppManagement/MSI/{productId}</LocURI>
        </Target>
      </Item>
    </Get>`

`<Status>
      <CmdID>2</CmdID>
      <MsgRef>1</MsgRef>
      <CmdRef>6</CmdRef>
      <Cmd>Get</Cmd>
      <Data>404</Data>
    </Status>`

I got the same result when trying to perform a Delete action

The {productId} is always the same, formatted like %7B....%7D, I'm testing on a Windows 10 machine, build 10.0.19042.1586 with an enterprise license.

(admin edit, switching doc details to en-us and the **EnterpriseDesktopAppManagement** CSP which is referenced above, versus the EnterpriseModernAppManagement originally linked)
 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a8c96f8e-b37d-843d-e788-d12b3906f4fb
* Version Independent ID: 4c6538e7-ba7c-98ae-6587-cd2792c571e2
* Content: [EnterpriseDesktopAppManagement CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/enterprisedesktopappmanagement-csp)
* Content Source: [windows/client-management/mdm/enterprisedesktopappmanagement-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enterprisedesktopappmanagement-csp.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @andreamerico for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. My apologies for not redirecting sooner. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

(Some more context: we're in progress to migrate all CSP reference content to be automatically generated from the CSP DDF and/or ADMX, but will pull in existing examples like in this article. In this specific instance, the examples here are at least 5 years old, as they migrated over from the previous content management platform. Our current team unfortunately doesn't have the resources to test and/or track down product owners in every situation. If you determine more information from working with support, please reopen and share back.)
