### ISSUE TITLE
RDP from Azure AD Registered Device - tenants

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/windows-itpro-docs#10525]
According to article, Azure AD registered device are supported:

> Your local PC (where you're connecting from) must be ... [Azure AD registered](https://docs.microsoft.com/en-us/azure/active-directory/devices/concept-azure-ad-register) if using Windows 10, version 2004 and above. Remote connections to an Azure AD-joined PC from an unjoined device or a non-Windows 10 device aren't supported.

But then it goes on to say:

> The local PC and remote PC must be in the same Azure AD tenant. 

A device can be registered to multiple tenants. What does "in" mean in this context? Does the device have to be registered to only one tenant? Is it the first tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows) - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by fowl2** [comment]
Yes it's possible, my Windows machine is registered to two tenants right now.

**Comment by fowl2** [comment]
> Azure AD added support for multiple Azure AD accounts starting in Windows 10 1803 release

-- https://docs.microsoft.com/en-us/azure/active-directory/devices/faq#i-can-t-add-more-than-3-azure-ad-user-accounts-under-the-same-user-session-on-a-windows-10-11-device--why

**Comment by MaratMussabekov** [comment]
Hello @fowl2 ,
**Azure AD added support for multiple Azure AD accounts starting in Windows 10 1803 release** - multiple azure ad accounts doesn't mean multiple Azure AD tenants
Tried to reproduce the case you described, but didn't succeed. When I try to register device on second tenant, I always got error that device is already registered in another organization.
Dear @Dansimp , can it be checked with product team?

**What does "in" mean in this context? Does the device have to be registered to only one tenant? Is it the first tenant?** - I believe it should work anyways. If local device is registered in the same tenant where remote device is joined, successful connection is expected.

Thank you

**Comment by yogkumgit** [comment]
@vinaypamnani-msft Please help us in resolving this issue. Thanks

**Comment by vinaypamnani-msft** [comment]
I tested and confirmed I can't register a device with TenantB when it's already registered with TenantA. I've recently made substantial edits to this article and am closing this issue.
