### ISSUE TITLE
revoke consent for microsoft store for business?

### ISSUE THREAD

**Issue by flobiata** [MicrosoftDocs/windows-itpro-docs#1052]
is it possible to revoke the connection (you consent for your organisation when you sign up) between Office 365 tenant and Store for business? That isn't part of the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a3b18ac-f556-8986-e13b-22cdcda3e31f
* Version Independent ID: d8f9e0d0-a162-0e0a-abe7-8e878510995f
* Content: [Sign up for Microsoft Store for Business or Microsoft Store for Education (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/sign-up-microsoft-store-for-business)
* Content Source: [store-for-business/sign-up-microsoft-store-for-business.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/sign-up-microsoft-store-for-business.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by glfhern** [comment]
I also don't see anything about pricing or if it costs to sign up for this.

**Comment by arsalangithubs** [comment]
I also want to know about the pricing, can someone from Microsoft comment on this, please?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by VLG17** [comment]
@flobiata @arsalangithubs After you have signed up for Microsoft store for Business, you can revoke this consent by reaching out to support - https://businessstore.microsoft.com/support)

There is no cost associated with signing up for Microsoft Store for Business.

**Comment by mypil** [comment]
@flobiata @arsalangithubs - Thank you for submitting this feedback.

From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
