### ISSUE TITLE
dead link to download the Windows ISO

### ISSUE THREAD

**Issue by TheBaban** [MicrosoftDocs/windows-itpro-docs#10533]
The link to download the windows ISO is not working anymore.
[evaluation version of Windows 10 Enterprise](https://www.microsoft.com/evalcenter/evaluate-windows-10-enterprise)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc63299-cc1c-e031-deb7-915914b8f94e
* Version Independent ID: 356eaba5-16b0-952f-fc19-c8d5be5feb5f
* Content: [Demonstrate Autopilot deployment - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm)
* Content Source: [windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @TheBaban for filing the feedback. We're aware of the issue. I'm investigating next steps.

**Comment by aczechowski** [comment]
See https://techcommunity.microsoft.com/t5/windows-11/accessing-trials-and-kits-for-windows-eval-center-workaround/m-p/3361125

We'll update this and other articles soon.
