### ISSUE TITLE
Simplify

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/windows-itpro-docs#10536]
What in the world is this encyclopia of a dictionary?  Could someone please simplify this trash?  We don't need a PhD here.  We need an automated solution that will TEST for some of these conditions before we waste our time?  I don't see any steps that test to see if any of these things are done already in an environment.  And you all wonder why support tickets are extreme...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93cb286c-03a9-187a-77a3-771c1c672342
* Version Independent ID: 875bbfa3-7ee3-960e-9b1c-ff5216a62d8b
* Content: [Configure Device Registration for Hybrid Azure AD joined Windows Hello for Business - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md)
* Product: **m365-security**
* GitHub Login: @Gitprakhar13
* Microsoft Alias: **prsriva**

**Comment by yogkumgit** [comment]
@Gitprakhar13 Please help us in resolving this issue. Thanks

**Comment by paolomatarazzo** [comment]
Thank you for the feedback @Karr. Please be mindful of the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/), which outlines the expectations for community interactions in and around docs.microsoft.com, is designed to help "provide a welcoming and inspiring community for all." 
The documentation is getting updated to simplify the processes around Windows Hello for Business, therefore I'm closing this issue.
