### ISSUE TITLE
Windows Update vs. Security level

### ISSUE THREAD

**Issue by nikolaj-j** [MicrosoftDocs/windows-itpro-docs#1054]
&lt;clip&gt;
If your organization relies on Windows Update for updates, you shouldn’t use the Security level. Because no Windows Update information is gathered at this level, important information about update failures is not sent. Microsoft uses this information to fix the causes of those failures and improve the quality of our updates.
&lt;/clip&gt;

Please clarify "you shouldn’t use the Security level. Because no Windows Update information is gathered".
What level will ensure that Windows Update will work?

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 893c364e-fcf4-8667-17d7-f9a3ec71e1a9
* Version Independent ID: f98f8870-d594-f5df-f6b6-44c9806db7d8
* Content: [Configure Windows diagnostic data in your organization (Windows 10)](https://docs.microsoft.com/da-dk/windows/privacy/configure-windows-diagnostic-data-in-your-organization#feedback)
* Content Source: [windows/privacy/configure-windows-diagnostic-data-in-your-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/configure-windows-diagnostic-data-in-your-organization.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
Hi @nikolaj-j, any level above security, which is the lowest, will provide information to help support the Windows Update cycle.
