### ISSUE TITLE
Question: Can BitLocker deployment be automated in an enterprise environment?

### ISSUE THREAD

**Issue by alex47** [MicrosoftDocs/windows-itpro-docs#10541]
In question: Can BitLocker deployment be automated in an enterprise environment?
The answer does not mention that BitLocker can (and should) be configured with group policies, instead of custom scripts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a2b6bec-05af-1e20-a22e-d2a0c71a7dca
* Version Independent ID: 5c644e57-ae1b-a510-ebdb-52391fb6407f
* Content: [BitLocker deployment and administration FAQ (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-deployment-and-administration-faq#feedback)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-deployment-and-administration-faq.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-deployment-and-administration-faq.yml)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@Dansimp Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@frankroj Please help us in resolving this issue. Thanks

**Comment by frankroj** [comment]
While I agree that BitLocker can be partially managed via group policy, I wouldn't go as far as saying it **should** be managed via group policy. There are certain scenarios, such as Azure AD joined devices, where there is no group policy. Group policy also probably offers the least flexibility and least amount of configurability when compared to scripting. Scripting unlocks options and flexibility that may not be available via group policy. You could also argue that that there are other methods to deploy and manage BitLocker that are better than group policy, including MDM solutions (such as Intune), Configuration Manager BitLocker Management, or MBAM. I think the purpose of this FAQ items is to offer a solution to FULLY manage BitLocker without specifically calling out a solution (e.g. Intune, Configuration Manager BitLocker Management, or MBAM).
