### ISSUE TITLE
Managed Installers only works for windows enterprise and not windows business/pro

### ISSUE THREAD

**Issue by stevenm57811** [MicrosoftDocs/windows-itpro-docs#10547]
[Please update the article to reflect that the managedinstaller feature is only available to Windows Enterprise SKUs. Tested two Windows 11 enterprise machines and managed installers worked. Tested two windows 10 business and pro machines and they have failed. Please update the article to save people time. 

This is most likely related to AppLocker only being supported for non enterprise SKU's if you use the AppLocker CSP. The AppLocker CSP does not actually support managed installers. I used powershell to deploy my applocker xml file, still no success unless it was on an windows enterprise machine.
 ]

(admin edit: refresh metadata with latest)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d9a0607-b206-fab3-ef68-9de7c7e6a072
* Version Independent ID: 9ca53978-51c8-d2e1-c6a4-4b0a19bac244
* Content: [Allow apps deployed with a WDAC managed installer (Windows)](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @jsuther1974
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
I'll keep this issue open for @vinaypamnani-msft to review re WDAC and other comments above, but regarding the point about Business SKU and the AppLocker CSP, see https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9560#issuecomment-1382191251

**Comment by aczechowski** [comment]
I think this issue will be addressed by work that @paolomatarazzo is doing broadly across our content to clarify licensing requirements. So we can either link to that PR or just close this.

Also, the new CSP articles show applicability from the DDFv2 XML in the OS itself, which is a technical requirement. We have found there are instances where a CSP policy technically works on an edition, but there is a different licensing requirement. At a later stage, we plan to add a note to all CSP articles to include this note.

**Comment by paolomatarazzo** [comment]
Thank you, @stevenm57811. WDAC and Applocker are supported on both Pro and Enterprise editions. The enablement to Pro was recently announced here: https://support.microsoft.com/en-us/topic/kb5024351-removal-of-windows-edition-checks-for-applocker-e3a763c9-6a3e-4d9c-8623-0ffe69046470
The documentation will be updated soon to reflect the change.

**Comment by stevenm57811** [comment]
Thanks for the feedback.

Steven Melentijevic
JUNIOR INFRASTRUCTURE ENGINEER

P. +61 2 9697 9988 D. +61 2 9183 8460 M. +61 0423 123 877
[Zimmermann]<http://www.zimmermannwear.com/>
[https://dspvpvtdtd9j5.cloudfront.net/images/email/instagram.png]<https://www.instagram.com/zimmermann/>[https://dspvpvtdtd9j5.cloudfront.net/images/email/facebook.png]<https://www.facebook.com/ZIMMERMANN.Sydney/>[https://dspvpvtdtd9j5.cloudfront.net/images/email/twitter.png]<https://twitter.com/zimmermann_>[https://zimwebmedia.s3-ap-southeast-2.amazonaws.com/images/email/WEIBO.png]<https://www.weibo.com/zimmermannofficial>[https://zimwebmedia.s3-ap-southeast-2.amazonaws.com/images/email/WECHAT.png]<https://www.zimmermannwear.com/wechat>[https://dspvpvtdtd9j5.cloudfront.net/images/email/pinterest.png]<https://au.pinterest.com/zimmermannonpin/>[https://dspvpvtdtd9j5.cloudfront.net/images/email/youtube.png]<https://www.youtube.com/channel/UCS7p_O6qb7CBSBfpuFqlR-g>

zimmermann.com<http://www.zimmermann.com/>

The Cannery, Level 1, 85 dunning ave, Rosebery Nsw 2018 Australia

PO BOX 7193, ALEXANDRIA NSW 2015

Zimmermann acknowledges Aboriginal and Torres Strait Islander peoples as the traditional owners and custodians of the land, waters and culture throughout Australia. We recognise this ongoing connection and pay our respects to the Elders past, present and emerging leaders.
DISCLAIMER: This communication may be confidential. If you are not the intended recipient you are hereby notified that any dissemination, copy or disclosure of it is prohibited. Please notify us via e-mail and delete it.
