### ISSUE TITLE
update with Azure Communication Service

### ISSUE THREAD

**Issue by RatMaster79** [MicrosoftDocs/windows-itpro-docs#10556]
[Enter feedback here]
We should publish ACS networking requirements in the page & remove Skype dependencies before releasing new Quick Assist on 23rd May 2022 - I guess 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfcd14cd-f887-660f-8a4c-465b3495e90e
* Version Independent ID: 121eead7-eb87-f033-024a-f688866c58a0
* Content: [Use Quick Assist to help users - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/quick-assist)
* Content Source: [windows/client-management/quick-assist.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/quick-assist.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @RatMaster79 for the feedback! I just fixed this based on input from a PM. The changes should publish on 5/25 by 11:00 Pacific time.
