### ISSUE TITLE
Rebrand?

### ISSUE THREAD

**Issue by Beschorr** [MicrosoftDocs/windows-itpro-docs#10554]
In WSA this feature appears as "Microsoft Defender Credential Guard". Should we be rebranding this article too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77f8afd0-78e2-b866-196e-7068fd3743fe
* Version Independent ID: 94338ba3-90f0-eb4c-54e8-d3de22d8647b
* Content: [How Windows Defender Credential Guard works - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-how-it-works?source=docs)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-how-it-works.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-how-it-works.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@Beschorr Thank you for your feedback. Most of the documents still refer to it as Windows Defender Credential Guard. I'm adding @Dansimp to confirm if we can rebrand or leave it as is.

Thanks
Sri

**Comment by yogkumgit** [comment]
@paolomatarazzo Please help us in resolving this issue. Thanks.

**Comment by paolomatarazzo** [comment]
Thank you @Beschorr, there hasn't been official guidance regarding the rebranding of WDCG. Once we get confirmation of the rebranding, then we will update the documentation accordingly. I'm following up internally an email thread started in October regarding rebranding efforts.
