### ISSUE TITLE
Replace bit.ly URL with aka.ms variant

### ISSUE THREAD

**Issue by 0xThiebaut** [MicrosoftDocs/windows-itpro-docs#10557]
The following snippet contains a `bit.ly` URL which is uncommon given MS's common practice of relying on the `aka.ms` shortner.

https://github.com/MicrosoftDocs/windows-itpro-docs/blob/758f7a98a5ca788cfa82024e7d5dfb87e3a1245a/windows/security/threat-protection/windows-defender-application-control/wdac-wizard.md?plain=1#L37

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 054ba21b-1dd4-f891-74f4-950b6dbba31e
* Version Independent ID: 8837a26c-2bdc-fcfa-e1d9-928460ccd2b6
* Content: [Windows Defender Application Control Wizard - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/wdac-wizard)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/wdac-wizard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/wdac-wizard.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @jgeurten
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Thank you @0xThiebaut for letting us know about this issue. Thank you @RAJU2529 for fixing it. Changes have been merged and will render live later today. Thank you for helping us improve our documentation!
