### ISSUE TITLE
Add additional Information about Troubleshooting Client-Licensing

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/windows-itpro-docs#10570]
Add additional Information about Troubleshooting Client-Licensing
**Level 100**
_Options in the Settings-Interface (Gui)_
- Settings > Accounts > Access work or school
- Settings > System> Shared Experiences

**Level 200**
_Commands_
net stop clipsvc
rundll32 clipc.dll,ClipCleanUpState
net start clipsvc

licensingdiag -cab c:\Temp\licensingdiag.cab

_Eventlog & Log Files_
- Client-Licensing, Client License Service (ClipSVC)
- Content of c:\Temp\licensingdiag.cab

**Level 300**
More Information around:
- Client License Service (ClipSVC) [ClipSVC]
- Microsoft Account Sign-in Assistant [wlidsvc]
- Microsoft.Windows.Pro.Addon_8wekyb3d8bbwe 
- Scheduled Tasks (EnableLicenseAcquisition and LicenseAcquisition)
- HKLM\SYSTEM\CurrentControlSet\Control\ProductOptions
- C:\ProgramData\Microsoft\Windows\ClipSVC\token.dat
- C:\Windows\System32\spp\store\2.0\token.dat

Source: https://call4cloud.nl/2022/02/escape-from-windows-10-pro/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6443e532-640d-81c0-8215-b711bd1977d4
* Version Independent ID: fc504984-91d7-b586-04ec-4c751fb48998
* Content: [Windows 10/11 Subscription Activation - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation)
* or Content: https://docs.microsoft.com/en-us/windows/deployment/deploy-enterprise-licenses
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by yogkumgit** [comment]
@aczechowski Please help us in resolving this issue. Thanks

**Comment by rudyooms84** [comment]
+1 To add this information to the docs.. As I am the writer of that blog... adding that information to the docs could be useful!

**Comment by aczechowski** [comment]
Thanks all for the feedback. I'm assigning to @frankroj for our backlog, something to work with the PM to revise this article. I can't promise it will happen for months, but we'll use this issue to track it.

**Comment by weyCC81** [comment]
I did not have a problem with KMS and specially not with Windows 7!, where can I find the troubleshooting for activation over subscription?
#please-reopen | @frankroj  | @aczechowski

**Comment by frankroj** [comment]
Thank you @weyCC81. I’m sorry that you’re having problems. Unfortunately, this is not a support forum. This is for feedback on product documentation. I did provide one link above where you can get started looking for troubleshooting information. However, if that doesn't help, I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by weyCC81** [comment]
Classic Microsoft when you try to improve the official documentation, after already having solved the case with an external source.
Thanks to @rudyooms84 and every other unofficial documentation.
