### ISSUE TITLE
Update Incompatible Switch List

### ISSUE THREAD

**Issue by Jurstin** [MicrosoftDocs/windows-itpro-docs#10576]
You need to add /listfiles: as an incompatible switch to be used with genconfig. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c7e6db2-1517-e9b9-cd9a-6a6aaf84ccc3
* Version Independent ID: daab80f9-640e-36c9-e60a-084901b11c05
* Content: [ScanState Syntax (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-scanstate-syntax)
* Content Source: [windows/deployment/usmt/usmt-scanstate-syntax.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/usmt/usmt-scanstate-syntax.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by msbemba** [comment]
@Jurstin Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11082

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by Jurstin** [comment]
I don't even recall what feedback I left but glad it helped with something.
