### ISSUE TITLE
Broken github links on this page for MMDM

### ISSUE THREAD

**Issue by scooleo** [MicrosoftDocs/windows-itpro-docs#10572]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e875fa6-9fa9-1d42-ab68-a1b0285a0666
* Version Independent ID: 618c4d23-f231-bac3-33ad-87f9d4952492
* Content: [Mobile device management - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/)
* Content Source: [windows/client-management/mdm/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/index.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment]
Thanks @scooleo for the feedback. We have a backend system that checks for broken links, and are working through a backlog. I'll take a look at this one shortly.

**Comment by aczechowski** [comment]
The MMAT repo doesn't exist on GitHub anymore, thus the broken links. I'm trying to find an owner to find out whether it was moved or removed.

**Comment by aczechowski** [comment]
The MMAT tool is going away. You can use [Group policy analytics in Microsoft Endpoint Manager](https://docs.microsoft.com/mem/intune/configuration/group-policy-analytics) to help determine which group policies supported by cloud-based MDM providers, including Microsoft Intune.
