### ISSUE TITLE
SetupDiag.exe version appears to be incorrect

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/windows-itpro-docs#1057]
When I launch the command SetupDiag.exe /? I get the following output:

SetupDiag v1.02

Copyright (c) Microsoft Corporation. All rights reserved.

Usage:
/Output:[Full path and file name for output file.]

/Mode:[Online | Offline - Online tells SetupDiag to look on the executing system for logs files.  Offline mode requires the /LogsPath parameter.]

/LogsPath:[Full path to logs to parse.  Only required when /Mode:Offline is used.]

Example 1 - Offline Mode
SetupDiag.exe /Output:C:\SetupDiag\Results.txt /Mode:OfflineMode /LogsPath:D:\Temp\Cabs\2c12b21f-9a91-4666-95ac-c99cf54c2eff

This would instruct SetupDiag.exe to parse the log files in the LogsPath directory in offline mode and output the resuts to C:\setupdiag\results.txt

Example 2 - Online Mode
SetupDiag.exe /Output:C:\SetupDiag\Results.txt /Mode:Online

This would instruct SetupDiag to run in Online Mode and output its results to C:\SetupDiag\Results.txt.

The release notes state:

SetupDiag v1.20 is released with 41 rules, as a standalone tool available from the Download Center.

When I open file properties on the latest file, I get File Version and Product Version of: 1.2.0.0.

Also, when running in Online mode, I also cannot get the /output:  argument to output a log file to the location I specify. When I run in Offline mode, the /output argument works fine. I will open a Feedback case for this unless you indicate otherwise. I can't seem to find where the log file is ending up.

Sorry for the bad formatting. See file attachments for screenshots.

![image](https://user-images.githubusercontent.com/20917262/41247357-65bd597c-6d73-11e8-8806-f3d6e63b8b3d.png)

![image](https://user-images.githubusercontent.com/20917262/41247377-76b0248a-6d73-11e8-9899-3f7698e7c4bc.png)

![image](https://user-images.githubusercontent.com/20917262/41247422-8e616418-6d73-11e8-8462-2f58af164149.png)

![image](https://user-images.githubusercontent.com/20917262/41247452-a182f386-6d73-11e8-9271-0125376ba086.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ad81361-15d8-0e95-9d5f-090dbf270f10
* Version Independent ID: c0c32397-d5d6-cce1-79fd-c310bec05240
* Content: [SetupDiag](https://docs.microsoft.com/en-us/windows/deployment/upgrade/setupdiag)
* Content Source: [windows/deployment/upgrade/setupdiag.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/setupdiag.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
It's a text bug. Thanks for pointing this out! We will get this fixed.

**Comment by AdamGrossTX** [comment]
While you are fixing the text, can you also add all of the command line parameters to the help within the EXE? I noticed that the online reference shows many more options than the EXE itself.

**Comment by ScottHendrix-MSFT** [comment]
That is fixed as well in 1.4, thanks for pointing it out.

**Comment by mypil** [comment]
@AdamGrossTX - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
