### ISSUE TITLE
Please clarify the extent of ineligibility when using servicing profiles

### ISSUE THREAD

**Issue by cakin027** [MicrosoftDocs/windows-itpro-docs#10581]
Could the following section be clarified in the text? Does this mean if a customer is using servicing profiles on a device, that device is ineligible for the Windows Autopatch service? Or does it mean that it will only be ineligible for M365 App updates, but will still be eligible for the service and will still get Windows Updates?

Microsoft 365 Apps servicing profiles
A service profile takes precedence over other management tools, such as Microsoft Endpoint Manager or the Office Deployment Tool. This means that the servicing profile will affect all devices that meet the above requirements regardless of existing management tools in your environment. So, if you're targeting a managed device with a servicing profile it will be ineligible for Microsoft 365 App update management.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8a5572-1135-3c0b-06d1-b8e1f258c17a
* Version Independent ID: ec8a5572-1135-3c0b-06d1-b8e1f258c17a
* Content: [Microsoft 365 Apps for enterprise - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopatch/operate/windows-autopatch-microsoft-365-apps-enterprise)
* Content Source: [windows/deployment/windows-autopatch/operate/windows-autopatch-microsoft-365-apps-enterprise.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopatch/operate/windows-autopatch-microsoft-365-apps-enterprise.md)
* Product: **w11**
* Technology: **windows**
* GitHub Login: @tiaraquan
* Microsoft Alias: **tiaraquan**

**Comment by tiaraquan** [comment]
@cakin027 

Thank you for your feedback. I'm working with the team to provide further clarity.

**Comment by tiaraquan** [comment]
Hi @cakin027 

We've updated the Servicing profiles section to address your feedback. The article has been updated:

https://docs.microsoft.com/en-us/windows/deployment/windows-autopatch/operate/windows-autopatch-microsoft-365-apps-enterprise#microsoft-365-apps-servicing-profiles
