### ISSUE TITLE
Missing explanation on how to unblock VSC

### ISSUE THREAD

**Issue by heliotarra** [MicrosoftDocs/windows-itpro-docs#1059]
There is no documentation on how to unblock a vsc. I can't seem to find anything online that does not require additional software. Being able to unblock a locked computer is a pretty important thing to be missing. Currently I would have to destroy the vsc, recreate the vsc, then issue a new certificate to get a user back online. We have the ability to create PUK's but there is no clear way to use it so what is the point?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 458fb7f8-3f6f-9111-2982-f6300268b935
* Version Independent ID: 936138f5-f85b-a049-2a93-a7b2b238f90b
* Content: [Tpmvscmgr (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-tpmvscmgr#feedback)
* Content Source: [windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-tpmvscmgr.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-tpmvscmgr.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@heliotarra Thanks for your feedback. There is more content at https://docs.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-deploy-virtual-smart-cards.  The PUK can be used by setting the Allow Integrated Unblock policy at https://docs.microsoft.com/en-us/windows/security/identity-protection/smart-cards/smart-card-group-policy-and-registry-settings#allow-integrated-unblock-screen-to-be-displayed-at-the-time-of-logon.

**Comment by Justinha** [comment]
@heliotarra I added all this to the docs.

**Comment by heliotarra** [comment]
Thanks for updating the page, I found the policy information shortly after posting the comment but hopefully this will save other people some time.
