### ISSUE TITLE
Incorrect information for EnableExtendedIEModeHotkeys

### ISSUE THREAD

**Issue by ken-chy** [MicrosoftDocs/windows-itpro-docs#10606]
Hi, I found the information about EnableExtendedIEModeHotkeys is incorrect:

ADMX Info: _(Incorrect info in italic)_ **[Correct info in bold]**

- GP Friendly name: _(Allows enterprises to provide their users with a single-browser experience)_ **[Enable extended hot keys in Internet Explorer mode]**
- GP name: EnableExtendedIEModeHotkeys
- GP path: Windows **[Components/Internet Explorer]**_(/Security Features/Add-on Management)_
- GP ADMX file name: inetres.admx

Regards,
Ken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d7e46e1-7659-2efd-341d-9a0ba4adb4bd
* Version Independent ID: 4e032a82-36f1-f1c1-d8d4-8cce7e42799b
* Content: [Policy CSP - InternetExplorer - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-internetexplorer#internetexplorer-enableextendediemodehotkeys)
* Content Source: [windows/client-management/mdm/policy-csp-internetexplorer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-internetexplorer.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@ken-chy Thank you for your feedback. The document does state the correct GP information now.

![image](https://user-images.githubusercontent.com/45987684/200585553-2f7bd41a-2639-4d93-a46a-f040a3c9571e.png)


Hope this helps!

@yogkumgit  There are no changes needed in the document as of now.

Thanks
Sri

**Comment by ken-chy** [comment]
@msbemba Sorry I wasn't clear enough. The GP path should be _Windows Components/Internet Explorer/Main_ instead.

Regards,
Ken

**Comment by msbemba** [comment]
@ken-chy Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10997

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ken-chy Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
