### ISSUE TITLE
Erro de tradução

### ISSUE THREAD

**Issue by jefesonalves** [MicrosoftDocs/windows-itpro-docs#10618]
**Acredito que onde está escrito:** "Depois que a emergência for **final**, desmarque a configuração para restaurar o tráfego de rede regular."
**Deveria ser:** "Depois que a emergência for **finalizada**, desmarque a configuração para restaurar o tráfego de rede regular."

Bing Translator says:

I believe that where it is written: "After the emergency is final, uncheck the configuration to restore regular network traffic."

It should be: "After the emergency is complete, uncheck the configuration to restore regular network traffic."

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 88e8e24b-481e-babb-a4e7-c5639f2492a2
* Version Independent ID: f61e0165-fd95-0fc4-a52c-0b4c40735ea3
* Content: [Práticas recomendadas para configurar Windows Defender Firewall - Windows security](https://docs.microsoft.com/pt-br/windows/security/threat-protection/windows-firewall/best-practices-configuring)
* Content Source: [windows/security/threat-protection/windows-firewall/best-practices-configuring.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/main/windows/security/threat-protection/windows-firewall/best-practices-configuring.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by denisebmsft** [comment]
@TinaMcN can you please take a look? Thank you!
