### ISSUE TITLE
How to troubleshoot MSP field value missing (UpdateCompliance Configuration)

### ISSUE THREAD

**Issue by jdb5** [MicrosoftDocs/windows-itpro-docs#10616]
At the [Configuring devices through the Update Compliance Configuration Script](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-configuration-script) page, at the bottom there is a section **Verify device configuration**.  I have followed the steps and my Commerical ID is showing, but the MSP field isn't there.  I've waited 72 hours and I am not seeing anything in my _UpdateCompliance Summary tile._

Run the Diagnostic Data Viewer.

Go to Start, select Settings > Privacy > Diagnostics & feedback.
Under View diagnostic data, select Open Diagnostic Data Viewer.
When the Diagnostic Data Viewer opens, type SoftwareUpdateClientTelemetry in the search field. Verify the following items:

The EnrolledTenantID field under m365a should equal the [CommercialID](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-get-started#get-your-commercialid) of your Log Analytics workspace for Update Compliance.
**The MSP field value under protocol should be either 16 or 18.**
If you need to send this data to Microsoft Support, select Export data.

**Comment by jdb5** [comment]
My device is hybrid joined, I'm not sure if that is supported.  The website says "All devices enrolled in Update Compliance must meet all prerequisites for enabling Windows diagnostic data processor configuration, including the Azure AD join requirement. This prerequisite will be enforced for Update Compliance starting on October 15, 2022."

**Comment by msbemba** [comment]
@jdb5 Thank you for your feedback. I have tested it in a  hybrid joined device and it shows up in the MSP field. If this continues to be a problem, we recommend you contact Microsoft support so that a support engineer can assist in fixing the issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
Thanks @jdb5  for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:
- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
