### ISSUE TITLE
Head of lnstitution

### ISSUE THREAD

**Issue by sanghaysanghay** [MicrosoftDocs/windows-itpro-docs#10612]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fb999d2-1864-9a75-8c93-44884a0d5f27
* Version Independent ID: da983002-7246-fb74-15fb-f4415ea90ee0
* Content: [Windows Privacy Compliance Guide - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/windows-10-and-privacy-compliance)
* Content Source: [windows/privacy/windows-10-and-privacy-compliance.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/windows-10-and-privacy-compliance.md)
* Product: **m365-security**
* Technology: **privacy**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by denisebmsft** [comment]
Hello @sanghaysanghay. Do you have some feedback for us? Not enough information came through. Please let us know if you have a question or suggestion. Thank you!

**Comment by sanghaysanghay** [comment]
> 
> [Enter feedback here]
> 
> 
> ---
> #### Document Details
> 
> ⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*
> 
> * ID: 7fb999d2-1864-9a75-8c93-44884a0d5f27
> * Version Independent ID: da983002-7246-fb74-15fb-f4415ea90ee0
> * Content: [Windows Privacy Compliance Guide - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/windows-10-and-privacy-compliance)
> * Content Source: [windows/privacy/windows-10-and-privacy-compliance.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/windows-10-and-privacy-compliance.md)
> * Product: **m365-security**
> * Technology: **privacy**
> * GitHub Login: @brianlic-msft
> * Microsoft Alias: **brianlic**
