### ISSUE TITLE
automatic rule creation

### ISSUE THREAD

**Issue by jefesonalves** [MicrosoftDocs/windows-itpro-docs#10619]
It is not clear how to prevent automatic creation of inbound rules from specifics apps. How to block all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88e8e24b-481e-babb-a4e7-c5639f2492a2
* Version Independent ID: f61e0165-fd95-0fc4-a52c-0b4c40735ea3
* Content: [Best practices for configuring Windows Defender Firewall - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/best-practices-configuring)
* Content Source: [windows/security/threat-protection/windows-firewall/best-practices-configuring.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/best-practices-configuring.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by yogkumgit** [comment]
@paolomatarazzo Please help us in resolving this issue. Thanks

**Comment by paolomatarazzo** [comment]
Hello @jefesonalves and thank you for the feedback. In the documentation that you linked, it says "If there's no active application or administrator-defined allow rule(s), a dialog box will prompt the user to either allow or block an application's packets the first time the app is launched or tries to communicate in the network."
If you define firewall rules via policy and block rule merging, it has the desired effect

**Comment by jefesonalves** [comment]
> a dialog box will prompt the user to either allow or block an ap



> Hello @jefesonalves and thank you for the feedback. In the documentation that you linked, it says "If there's no active application or administrator-defined allow rule(s), a dialog box will prompt the user to either allow or block an application's packets the first time the app is launched or tries to communicate in the network." If you define firewall rules via policy and block rule merging, it has the desired effect



> Hello @jefesonalves and thank you for the feedback. In the documentation that you linked, it says "If there's no active application or administrator-defined allow rule(s), a dialog box will prompt the user to either allow or block an application's packets the first time the app is launched or tries to communicate in the network." If you define firewall rules via policy and block rule merging, it has the desired effect

Hello @paolomatarazzo thank you for the reply! For example, if I delete all rules, some are included automatically and other apps or softwares prompts if I want to block or allow in the first access. Why not prompts to all apps or softwares?
