### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by tycastMSFT** [MicrosoftDocs/windows-itpro-docs#1062]
In step 6 under "Set up School PCs step-by-step," I see "theyâ€™re" instead of "they're."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2ca5807-f011-cdd1-eb80-c74655aa4738
* Version Independent ID: fe016307-69a4-ec63-4979-eac841d13c3c
* Content: [Use Set up School PCs app](https://docs.microsoft.com/en-us/education/windows/use-set-up-school-pcs-app)
* Content Source: [education/windows/use-set-up-school-pcs-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/use-set-up-school-pcs-app.md)
* Product: **w10**
* GitHub Login: @CelesteDG
* Microsoft Alias: **celested**

**Comment by jdeckerms** [comment]
@tycastMSFT Thanks for pointing that out, we'll get it fixed today.
