### ISSUE TITLE
[FIPS] Windows 10 21H2

### ISSUE THREAD

**Issue by salmahl** [MicrosoftDocs/windows-itpro-docs#10625]
Will this FIPS mode page be updated soon to include Windows 10 21H2?

(admin edit: update doc details with latest)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e93f07bf-c0dd-dd83-d7bf-8562e7f197c3
* Version Independent ID: a6c44187-8ff1-6519-5291-146b4c1bf46c
* Content: [Federal Information Processing Standard (FIPS) 140 Validation](https://learn.microsoft.com/en-us/windows/security/threat-protection/fips-140-validation)
* Content Source: [windows/security/threat-protection/fips-140-validation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/fips-140-validation.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
The current documentation is up to date. Once new certifications are released, the page will be updated.

**Comment by salmahl** [comment]
Where is the content on FIPS 199 modules in this specific version:  Windows 10 21H2 (https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10625#issuecomment-1382420121)?

**Comment by salmahl** [comment]
![image](https://user-images.githubusercontent.com/30274714/212428009-44ab92e4-b6ec-4a4c-8fa4-55689cfa2486.png)

**Comment by paolomatarazzo** [comment]
We should have some updates soon!
