### ISSUE TITLE
AADJ onprem SSO for AADJ devices in Cloud Trust Deployment

### ISSUE THREAD

**Issue by dbona75** [MicrosoftDocs/windows-itpro-docs#10624]
Hello, please add also a section about how to use the new Cloud Trust Deployment model for SSO to on prem using AADJ devices.

If you have Hybrid Cloud Trust Backend requirements (Kerberos Server and patched DC) you can use also AADJ devices to on prem resources access. In particular PKI configuration and DC certificates are no more required. Note that AADJ devices must have on prem DNS domain name in the primary DNS suffix using DHCP or manually in the network connection "dns suffix for this connection".

Regards

**Comment by denisebmsft** [comment]
Hello @dbona75. Can you please tell us to which article your feedback applies? This information will help us route the issue to the correct writer/team. Thank you!

**Comment by dbona75** [comment]
Hybrid Cloud Trust Deployment (Windows Hello for Business) - Windows security | Microsoft Docs<https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-trust>

Da: Denise Vangel-MSFT ***@***.***>
Inviato: mercoledì 15 giugno 2022 23:24
A: MicrosoftDocs/windows-itpro-docs ***@***.***>
Cc: Daniele Bona ***@***.***>; Mention ***@***.***>
Oggetto: Re: [MicrosoftDocs/windows-itpro-docs] AADJ onprem SSO for AADJ devices in Cloud Trust Deployment (Issue #10624)


Hello @dbona75<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdbona75&data=05%7C01%7Cdaniele.bona%40microsoft.com%7Ce9efd63a174745cc89c008da4f155007%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637909250259332580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EOPjY687QHEBmlqEhT%2BGxof0tJd1WyPIUt97QAzm4Bw%3D&reserved=0>. Can you please tell us to which article your feedback applies? This information will help us route the issue to the correct writer/team. Thank you!

-

**Comment by yogkumgit** [comment]
@paolomatarazzo Please help us in resolving this issue. Thanks

**Comment by paolomatarazzo** [comment]
This is comment before the documentation refresh. the current document addresses the issue
