### ISSUE TITLE
Commercial Data Pipeline - AAD Joined or Registered?

### ISSUE THREAD

**Issue by Aegrum** [MicrosoftDocs/windows-itpro-docs#10648]
[Enter feedback here]
Recently this document was updated by @mestew to cite the "Allow commercial data pipeline" as a required GPO. In the description it states:
> Configures Microsoft to be the processor of the Windows diagnostic data collected from an Azure Active Directory-**joined** device.

However, [the ADMX template for this setting states](https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.DataCollection::AllowCommercialDataPipeline):
> The device must be **registered** in Azure AD for this policy to succeed. 

Which is it? Azure AD **JOINED** or Azure AD **REGISTERED**?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37a5ef77-5d80-ce40-7243-c96f708e907c
* Version Independent ID: 3e24d136-6af4-2531-31fd-feac09f37901
* Content: [Manually configuring devices for Update Compliance - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-configuration-manual#group-policies)
* Content Source: [windows/deployment/update/update-compliance-configuration-manual.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-configuration-manual.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by mestew** [comment]
@Aegrum Thanks for noticing this. I highly suspect that wording is a bit off in the template. The device being Azure AD joined is listed as prereq for [enabling the Windows diagnostic data processor config](https://docs.microsoft.com/windows/privacy/configure-windows-diagnostic-data-in-your-organization#enable-windows-diagnostic-data-processor-configuration).

To suggest a wording change in the UI, please use the [Feedback Hub](https://aka.ms/feedbackhub) so it gets to the correct team for product feedback.

**Comment by Aegrum** [comment]
Thanks @mestew . Was there a reason this was just added to the config documentation when this is allegedly being removed?
> We’ll stop using policies, such as the “Allow commercial data pipeline” policy, to configure the processor option. Instead, we’ll be introducing an organization-wide configuration based on Azure Active Directory (Azure AD) to determine Microsoft’s role in data processing.
https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization#significant-changes-coming-to-the-windows-diagnostic-data-processor-configuration

**Comment by aczechowski** [comment]
Closing this issue as I don't think there's anything further actionable for docs at this time. (Correct me if I'm wrong!)
