### ISSUE TITLE
msp is 1 - what to do?

### ISSUE THREAD

**Issue by javoger** [MicrosoftDocs/windows-itpro-docs#10645]
What should we do or what is the reason if the msp value is 1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb8c41f-5e79-8310-3a2c-e2465d6aac96
* Version Independent ID: f517bcb0-3833-08b3-f3f4-75a732b3c629
* Content: [Update Compliance Configuration Script - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-configuration-script)
* Content Source: [windows/deployment/update/update-compliance-configuration-script.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-configuration-script.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by msbemba** [comment]
@javoger Thank you for your feedback. Ideally, the MS value should either be 16 or 18, it is unusual to have a value of 1. I'd recommend you contact Microsoft support so that a support engineer can assist you in identifying and fixing the issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
Thanks @javoger  for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:
- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
