### ISSUE TITLE
Link to Windows Update Reset Script broken

### ISSUE THREAD

**Issue by Smith-Rick** [MicrosoftDocs/windows-itpro-docs#10656]
Link to Windows Update Reset Script broken and does not actual go to any such script. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb9f2a2-76ad-8301-7d80-e33a7bb80a1b
* Version Independent ID: dd070c32-53d5-53d6-7ba2-a4361b5263bb
* Content: [Windows Update common errors and mitigation - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-errors)
* Content Source: [windows/deployment/update/windows-update-errors.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-errors.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by RAJU2529** [comment]
https://gallery.technet.microsoft.com/scriptcenter/Reset-Windows-Update-Agent-d824badc

**Comment by msbemba** [comment]
@Smith-Rick Thank you for your feedback. The script has been archived and as mentioned by @RAJU2529  it is available in third party website - https://web.archive.org/web/20170327052710/https://gallery.technet.microsoft.com/scriptcenter/Reset-Windows-Update-Agent-d824badc/file/162417/1/ResetWUEng.zip

Hope this helps!

@yogkumgit There are no changes needed on this document as of now.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Smith-Rick Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
