### ISSUE TITLE
Missing GPO for AllowSearchHighlights in latest Win10 & Win11 admx

### ISSUE THREAD

**Issue by mntorq** [MicrosoftDocs/windows-itpro-docs#10653]
For Search/AllowSearchHighlights GPO
https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-search#search-allowsearchhighlights 
It does not appear in Win11 21H2 search.admx (file date 6/5/21) files or latest Win10 download version 'Windows 10 November 2021 Update [21H2] found here: https://www.microsoft.com/en-us/download/103667  (file date 12/7/19)

I have searched the ADMX file of each and neither have the word 'highlight' which matches my finding when attempting to locate the specific GPO after placing the files in the Central Store - there is no entry for AllowSearchHighlights.

![image](https://user-images.githubusercontent.com/66257685/175385066-2c27aa40-ed59-4477-a90b-c0209dd681ae.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12404d25-d284-8578-6eb5-4cf3b2373781
* Version Independent ID: a6ff7cf5-1884-afe4-7415-8544de981fed
* Content: [Policy CSP - Search - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-search)
* Content Source: [windows/client-management/mdm/policy-csp-search.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-search.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mntorq** [comment]
ADMX files I have (renamed as txt)
[(From 11) Search.admx.txt](https://github.com/MicrosoftDocs/windows-itpro-docs/files/8970434/From.11.Search.admx.txt)
[(From 10 21H2) Search.admx.txt](https://github.com/MicrosoftDocs/windows-itpro-docs/files/8970435/From.10.21H2.Search.admx.txt)

**Comment by RAJU2529** [comment]
I will conform after checking in my laptop

**Comment by RAJU2529** [comment]
@mntorq . I conformed on windows 11 Enterprise build no 22000.778 preview  ** AllowSearchHighlights** is exists 
i uploaded the latest  search admx adml file

[Search.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/9020777/Search.zip)

![Screenshot 2022-06-30 201435](https://user-images.githubusercontent.com/3296790/176706823-a2d9d7db-b3b9-4caf-92be-13a890119da6.jpg)

**Comment by middletonk** [comment]
Confirming - this is still a live issue in the latest ADMX templates for Windows 10 (21H2 as of this comment). The value in the XML structure of the ADMX file should be "EnableDynamicContentInWSB" and does not appear in my own download, nor the OP's, but does appear in Windows 11. This is a clear mismatch with the Docs article stating it's supported in Windows 10. 

We could of course make a group policy preference for the raw Policies reg value but would prefer not to. Will follow up with Microsoft support.

**Comment by middletonk** [comment]
FYI, this was fixed in the Windows 10 22H2 ADMX templates and should be closed as an issue.

https://www.prajwaldesai.com/download-windows-11-22h2-group-policy-settings-admx/

https://techcommunity.microsoft.com/t5/windows-it-pro-blog/it-tools-to-support-windows-10-version-22h2/ba-p/3655750

**Comment by vinaypamnani-msft** [comment]
Thanks @middletonk for the update. Closing this issue.
