### ISSUE TITLE
Different supported OSs information

### ISSUE THREAD

**Issue by LeonardoFelippine** [MicrosoftDocs/windows-itpro-docs#1065]
Hello.

The "commercial" page of Windows Defender ATP (https://www.microsoft.com/en-us/windowsforbusiness/windows-atp) says that versions earlier than Windows 10 are supported, but this page lists only Windows 10 as supported. Can you please advise?

Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/minimum-requirements-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/minimum-requirements-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/minimum-requirements-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Hi, 
Thank you for your feedback!

We have recently released the public preview support for previous versions of Windows: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/onboard-downlevel-windows-defender-advanced-threat-protection
