### ISSUE TITLE
CMTrace indisponible

### ISSUE THREAD

**Issue by GowaP** [MicrosoftDocs/windows-itpro-docs#10651]
Le lien fourni dans cette page pour récupérer le composant CMTrace affiche une page en erreur 404. Merci de corriger.
Le moyen le plus simple d’afficher les fichiers journaux consiste à utiliser Configuration Manager Trace (CMTrace), qui est inclus dans le [kit de ressources Configuration Manager](https://go.microsoft.com/fwlink/p/?LinkId=734717).

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 02d07ede-1437-53e7-8ea5-3ee441cda67d
* Version Independent ID: 8b657df5-9053-7611-9132-f9113d439a7c
* Content: [Prise en main de Microsoft Deployment Toolkit (MDT) (Windows10) - Windows Deployment](https://docs.microsoft.com/fr-fr/windows/deployment/deploy-windows-mdt/get-started-with-the-microsoft-deployment-toolkit?source=docs)
* Content Source: [windows/deployment/deploy-windows-mdt/get-started-with-the-microsoft-deployment-toolkit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/main/windows/deployment/deploy-windows-mdt/get-started-with-the-microsoft-deployment-toolkit.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @GowaP - the link works ok for me now (https://go.microsoft.com/fwlink/p/?LinkId=734717). Sometimes the Microsoft Download Center does that. But I can confirm that the ConfigMgr 2012 R2 toolkit download is still currently available.
