### ISSUE TITLE
Allows you to configure the Enterprise Mode Site list changed

### ISSUE THREAD

**Issue by jonimattila** [MicrosoftDocs/windows-itpro-docs#1066]
Allows you to configure the Enterprise Mode Site list  is Configure the Enterprise Mode Site List

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f19c0a2-75ff-0504-78af-205a5bd88da3
* Version Independent ID: b661ca31-6826-db16-5276-bdff91e3db75
* Content: [Use Enterprise Mode to improve compatibility (Microsoft Edge for IT Pros)](https://docs.microsoft.com/en-us/microsoft-edge/deploy/emie-to-improve-compatibility)
* Content Source: [browsers/edge/emie-to-improve-compatibility.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/emie-to-improve-compatibility.md)
* Product: **edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@jonimattila, thank you for catching the name of the group policy.
