### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by yamaguchiyuta715** [MicrosoftDocs/windows-itpro-docs#10669]
[フィードバックをこちらに入力してください]
サービス アカウントは、サーバー オペレーティング システムで実行されているサービスのセキュリティ コンテキストを提供するために明示的Windowsユーザー アカウントです。

サービス アカウントは、サーバー オペレーティング システムで実行されているサービスのセキュリティ コンテキストを提供するための明示的Windowsユーザー アカウントです。
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7123be4d-125e-6894-5b15-222ec22184e8
* Version Independent ID: 5214af9d-4123-faf5-da75-7f1636b47c31
* Content: [サービス アカウント (Windows 10) - Windows security](https://docs.microsoft.com/ja-jp/windows/security/identity-protection/access-control/service-accounts)
* Content Source: [windows/security/identity-protection/access-control/service-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/main/windows/security/identity-protection/access-control/service-accounts.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment]
Thanks @yamaguchiyuta715 for the feedback. I'm going to assume that this is an issue with the translation in ja-jp locale, the en-us source information looks ok to me. I filed a bug to our localization team (211951) who will investigate. I'm closing this issue.
