### ISSUE TITLE
Suggestion, add a screenshot for step 4

### ISSUE THREAD

**Issue by SpitFire-666** [MicrosoftDocs/windows-itpro-docs#10677]
Purely a suggestion. Step 4 (right clicking Group Policy Objects and selecting Paste) was tripping me up - as you need to know exactly where and what to click. The rest of the copy process is easy!

I'm guessing others get stuck here too, as when you click "Copy", nothing appears to happen. Anyways a screenshot like below was all I needed:

![image](https://user-images.githubusercontent.com/38451588/176794257-e490f834-2887-43c0-9bb9-7619ed1cb6d4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc1944ed-39a5-07fc-3c95-91093c83d108
* Version Independent ID: 140ef3f3-e198-b886-8488-cf2554974b69
* Content: [Copy a GPO to Create a New GPO (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/copy-a-gpo-to-create-a-new-gpo)
* Content Source: [windows/security/threat-protection/windows-firewall/copy-a-gpo-to-create-a-new-gpo.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/copy-a-gpo-to-create-a-new-gpo.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@SpitFire-666 Thank you for your feedback. We will update a screenshot shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@SpitFire-666 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11021

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @SpitFire-666 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
