### ISSUE TITLE
the order

### ISSUE THREAD

**Issue by TheAnahaym** [MicrosoftDocs/windows-itpro-docs#1068]
please move the "step seven" before "step four"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c13083-9b29-e54b-fd85-8033ec665fcd
* Version Independent ID: ce8c4647-69bc-95d4-2192-6e737d5ad5da
* Content: [BitLocker How to enable Network Unlock (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock#bkmk-createcerttmpl)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@TheAnahaym Can you confirm you mean move Step Seven: Require TPM+PIN protectors at startup to appear before Step Four: Create the Network Unlock certificate? There are a few instances with step 4 and step 7 in this topic so I wanted to confirm. Why does TPM+PIN need to be configured first?

**Comment by TheAnahaym** [comment]
Step four: Create the Network Unlock certificate.
Step seven: Create the certificate template for Network Unlock.
How can you create a certificate before a creation of the proper template? Maybe the creation of the certificate template for Network Unlock is not a part of step seven, but still it must be before the certificate creation, doesn't it?

**Comment by Justinha** [comment]
@TheAnahaym I see, thanks for explaining. I moved that step and republished the topic.
