### ISSUE TITLE
How do I customize the Sandbox Window Size?

### ISSUE THREAD

**Issue by shantanub08** [MicrosoftDocs/windows-itpro-docs#10689]
[Enter feedback here]

How do I customize the Sandbox Window Size? By default it opens at half of the resolution of my entire screen [5120x1440] I want it to open in 1280x720 or 1920x1080

(admin edit: refresh metadata with latest)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2efc9d32-0f98-0804-78a4-4caccdfac010
* Version Independent ID: 797bb0d3-bade-98f6-fe85-508764571f37
* Content: [Windows Sandbox configuration](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aronreisx** [comment]
Still looking for an answer on this question. I have a Samsung G9 and always need to rescale the windows size manually.

**Comment by yogkumgit** [comment]
@Dansimp Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@vinaypamnani-msft Please help us in resolving this issue. Thanks

**Comment by TheAviationDoctor** [comment]
> Still looking for an answer on this question. I have a Samsung G9 and always need to rescale the windows size manually.

Same behavior observed here on a Samsung G9. Sandbox correctly opens to fill up the center of the priority grid (I use Power Toys' Fancy Zones) which is 2,560 x 1,440, but the within Sandbox window, there are two horizontal gray bars ~122 px tall at the top and bottom of the virtualized desktop. Using the Maximize button twice to resize the window to full screen and back to its original position solves it; the horizontal gray bars disappear and the virtualized desktop occupies the full Sandbox window.

**Comment by aczechowski** [comment]
I checked with the engineering team, and it currently doesn't support configuring the window size. I'm adding a note to the article to call that out. The engineering team is looking into the possibility of adding it in the future, but I suggest that you make your voice heard by [sending feedback in the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).

This issue will close when my pull request merges to add the note.
