### ISSUE TITLE
Applicable to Windows 11?

### ISSUE THREAD

**Issue by bfarmilo** [MicrosoftDocs/windows-itpro-docs#10684]
I see that this document applies to Windows 10, does it also apply to Windows 11?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9530a35b-23e4-fcc9-bb1f-b4954bb597d0
* Version Independent ID: e4e678b7-3d27-8cd2-a3a7-0c14056e8f79
* Content: [Security policy settings (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/security-policy-settings)
* Content Source: [windows/security/threat-protection/security-policy-settings/security-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/security-policy-settings.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment]
Thanks @RAJU2529 for contributing an edit for this issue
