### ISSUE TITLE
Thank you so very much for this page. After weeks of trying other things, I now have my Windows Defender Advanced Firewall Back ON!!! Thank You!!!

### ISSUE THREAD

**Issue by isepiq** [MicrosoftDocs/windows-itpro-docs#10685]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63ae3a36-8282-abf0-a355-0fa02ff21308
* Version Independent ID: da7bb5f7-78a4-594f-7a7d-db096928a89e
* Content: [Configure security policy settings (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/how-to-configure-security-policy-settings)
* Content Source: [windows/security/threat-protection/security-policy-settings/how-to-configure-security-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/how-to-configure-security-policy-settings.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment]
You're welcome @isepiq. Glad the content was of help to you. Thanks for taking the time to share your feedback.
