### ISSUE TITLE
HOMEBANK

### ISSUE THREAD

**Issue by dekdonlon** [MicrosoftDocs/windows-itpro-docs#10697]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4edaae97-455b-d25a-9228-5309e24b4aa3
* Version Independent ID: d38e56a7-d553-e519-95a9-dc93e2cdc771
* Content: [Microsoft Defender SmartScreen overview (Windows) - Windows security](https://docs.microsoft.com/en-gb/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview)
* Content Source: [windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by aczechowski** [comment]
I'm going to assume this issue was mistakenly filed, so I'm closing it. If you have some specific feedback about the SmartScreen overview article, please reopen and add more detail.
