### ISSUE TITLE
Unable to apply a deployment profile to more than 100 devices

### ISSUE THREAD

**Issue by mikemartin1090** [MicrosoftDocs/windows-itpro-docs#1069]
Hi - I recently received a shipment of 190 devices from my vendor and was successfully able to import the CSV file with hardware hashes and other required fields. I am now trying to apply my deployment profile to these devices, however I can only select 100 devices. Beyond that, I can only see 100 devices in the list - there is no "Load More" or anything like that on the screen. How would I modify the applied profile of these additional devices?

I can export a file of the devices I have from the AutoPilot section of Intune, however there is no place to perform any additional tasks in Intune. 

I don't see any powershell way to interact with the devices. The only thing I found was the [PS Module for Business Store](https://docs.microsoft.com/en-us/microsoft-store/microsoft-store-for-business-education-powershell-module), however that does not have the functionality to perform what I'm looking for. 

Is this a limitation in the UI? If so, how do I apply my deployment profile to not only these 190 devices, but to ALL devices that have been added to my AutoPilot enabled tenant?

![image](https://user-images.githubusercontent.com/6332286/41304242-9a97790a-6e3d-11e8-9e33-8d0c3cf8b3ba.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc947476-4fc3-cbb1-26c2-1e7dedb7892f
* Version Independent ID: 16bf5a1f-00d8-ad55-f66f-a9a38f115bb6
* Content: [Manage Windows device deployment with Windows Autopilot Deployment](https://docs.microsoft.com/en-us/microsoft-store/add-profile-to-devices#autopilot-device-information-file-error-messages)
* Content Source: [store-for-business/add-profile-to-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/add-profile-to-devices.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by lizap** [comment]
@greg-lindsay and @TrudyHa - I'm not sure which of you this falls more under, but can you please take a look? Thanks!

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
Hello @mikemartin1090  We are sorry that you have to face this issue. It should load all of your devices. Can you please confirm which browser you are using. I would recommend using Microsoft Edge or Internet Explorer and then try again.
If it still doesn't work, you can contact Microsoft support team to open up a support ticket to help you further.

@mypil Please guide the user how can he open a support ticket with Microsoft technical support.

Thanks.

**Comment by mypil** [comment]
@mikemartin1090 - Thank you for submitting feedback.

To get a resolution to your issue, you can open a service ticket. Based on outcome let us know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products: 
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

**Comment by mypil** [comment]
@officedocsbot close
