### ISSUE TITLE
CTRL + WINDOWS + Q stopped working in 21H2

### ISSUE THREAD

**Issue by pcpackrat** [MicrosoftDocs/windows-itpro-docs#10699]
CTRL + WINDOWS + Q stopped working in 21H2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfcd14cd-f887-660f-8a4c-465b3495e90e
* Version Independent ID: 121eead7-eb87-f033-024a-f688866c58a0
* Content: [Use Quick Assist to help users - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/quick-assist)
* Content Source: [windows/client-management/quick-assist.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/quick-assist.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by vinaypamnani-msft** [comment]
@pcpackrat I assume this issue has been addressed, as I was able to use the shortcut to launch Quick Assist in both Windows 10, and Windows 11, so I'm closing this issue.
