### ISSUE TITLE
[FIPS] Certificate #3197 has been marked "Historical" by NIST

### ISSUE THREAD

**Issue by thomasamaier** [MicrosoftDocs/windows-itpro-docs#10705]
Certificate # 3197 has been marked "Historical" by NIST.  That should be mentioned in this article and some information regarding the future direction indicated.

This is kind of a big deal for companies who deliver solutions to the US Federal Government that run on Windows Operating Systems.

(admin edit: update doc details with the latest)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e93f07bf-c0dd-dd83-d7bf-8562e7f197c3
* Version Independent ID: a6c44187-8ff1-6519-5291-146b4c1bf46c
* Content: [Federal Information Processing Standard (FIPS) 140 Validation](https://learn.microsoft.com/en-us/windows/security/threat-protection/fips-140-validation)
* Content Source: [windows/security/threat-protection/fips-140-validation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/fips-140-validation.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by aczechowski** [comment]
Thanks @thomasamaier for the feedback. We have a plan to do a major revision on this article, but don't have a specific timeframe right now. We'll talk with the PMs about incorporating this feedback.

**Comment by paolomatarazzo** [comment]
Hello @thomasamaier and thank you for the feedback. We're in the process of restructuring the FIPS documentation and we'll take into consideration your feedback, specifically how to mark certificates as historical.
