### ISSUE TITLE
デバイスごとにPIN変える奴なんかいるわけないだろ

### ISSUE THREAD

**Issue by yisikawa** [MicrosoftDocs/windows-itpro-docs#10711]
[フィードバックをこちらに入力してください]
デバイスごとにPIN変える奴なんかいるわけないだろ

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c34dbafa-df3c-a5a5-32d5-2ce152893534
* Version Independent ID: cebdd9a6-45d7-6306-373c-7d31121f9e16
* Content: [PIN がオンライン パスワードよりも優れている理由 (Windows) - Windows security](https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/main/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md)
* Product: **m365-security**
* GitHub Login: @Gitprakhar13
* Microsoft Alias: **prsriva**

**Comment by aczechowski** [comment]
Thank you @yisikawa for the feedback. I'm sorry for replying in English, but we don't have anyone who speaks Japanese on our team. We can engage with a localization team for assistance, but it will take additional time. If you're not able to communicate effectively in English, I can work with our other team for translation assistance.

I need to get more information from you about the nature of your feedback. Using machine-translation, I understand your comment to be, "There is no one who changes the PIN for each device." Can you elaborate to help me understand better?
