### ISSUE TITLE
Outlook blocks MDM enrollment deep-link

### ISSUE THREAD

**Issue by danboothisdm** [MicrosoftDocs/windows-itpro-docs#10714]
If we try to send an email containing  the deep link described in this article to launch MDM enrollment, Outlook removes the link.

(admin edit: update doc details with latest)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77442925-8ce4-44be-331f-079d0b97eb68
* Version Independent ID: 77442925-8ce4-44be-331f-079d0b97eb68
* Content: [MDM enrollment of Windows 10-based devices - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm-enrollment-of-windows-devices)
* Content Source: [windows/client-management/mdm-enrollment-of-windows-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm-enrollment-of-windows-devices.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by danboothisdm** [comment]
Hi @aczechowski thanks for your reply. We're using Office365. We did suspect host security software (Webroot) but nothing in documentation or being logged to confirm it's the culprit. If I click the link in my sent items it works fine. Recipients of my email see the text that is supposed to be a link, but the link is completely removed. Another link in the same email that's just a regular URL has been left untouched and works as expected.

**Comment by aczechowski** [comment]
@e0i Not sure why this closed...there are a couple of useful tweaks to be made to this article based on the feedback.
