### ISSUE TITLE
Just for devices/clients?

### ISSUE THREAD

**Issue by jasonjonesuk** [MicrosoftDocs/windows-itpro-docs#1071]
This article talks about "devices" but is the guidance also suitable for monitoring for potential intrusion on servers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5862cc7-3f36-5f2e-9ade-f7441f99f818
* Version Independent ID: b8bd1985-7b5b-ea79-976a-7d96ad69335c
* Content: [Use Windows Event Forwarding to help with intrusion detection (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection)
* Content Source: [windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md)
* Product: **w10**
* GitHub Login: @tedhardyMSFT
* Microsoft Alias: **justinha**

**Comment by MaratMussabekov** [comment]
Dear @jasonjonesuk ,
yes, server could also be used, as only thing needed is WinRM.
I've just created a PR to remove "Applied to: Windows 10" from the article, as it could be confusing.
Thank you

**Comment by Justinha** [comment]
@MaratMussabekov Thanks for following up. It will be better to add new bullet for Windows Server than to remove Windows 10. I'll look for the PR and comment there.

**Comment by mypil** [comment]
@jasonjonesuk - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
