### ISSUE TITLE
Missing entries in the table of content

### ISSUE THREAD

**Issue by cnotin** [MicrosoftDocs/windows-itpro-docs#10717]
The content of this page was lacking some entries as described in https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10026
It was fixed by https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10225

However, the new content was not added to the table of contents https://github.com/MicrosoftDocs/windows-itpro-docs/blob/9c545726726211c813844676e80fa1bf5fbe99ef/windows/security/identity-protection/access-control/special-identities.md?plain=1#L38-L86

For example, but not limited to, "Attested Key Property" was [added](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/special-identities#attested-key-property) but it's missing from the table of contents list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 486e8a12-8230-6ae2-264f-73c76b266682
* Version Independent ID: 2f47f94f-b416-beac-c75d-8908e4000e66
* Content: [Special Identities (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/special-identities#feedback)
* Content Source: [windows/security/identity-protection/access-control/special-identities.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/access-control/special-identities.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by vinaypamnani-msft** [comment]
@cnotin thanks for submitting this feedback! We've added the missing links and closed this issue.
