### ISSUE TITLE
Windows Release health

### ISSUE THREAD

**Issue by mmelkersen** [MicrosoftDocs/windows-itpro-docs#10718]
Hi

[Windows Release Health](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/check-release-health.md)

I don't see that in my portal and my user is Global Admin. Has it been removed or are there other requisites for this to be shown?
![2022-07-20_09-04-54](https://user-images.githubusercontent.com/77377683/179919269-fa99810b-6d43-49fa-be77-539ec541a59f.png)

**Comment by aczechowski** [comment]
I asked @mestew and she could see it in her portal. She's also checking about a PM that might be able to help.
Can you access it from this direct link? https://admin.microsoft.com/Adminportal/Home#/windowsreleasehealth

**Comment by e0i** [comment]
@aczechowski Any chance with a response from **mestew**? Thanks.

**Comment by aczechowski** [comment]
Not waiting on Meghan, if anything need more input from @mmelkersen, whether can access the direct link. There's already a note in the article (https://docs.microsoft.com/en-us/windows/deployment/update/check-release-health) about who can see the page, so I'm not sure what more we would add. This issue verges on a support request, so I'd suggest following up with more proper support channels. If there does appear to be some issue with the doc content, reopen this issue (or file a new one).

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by mmelkersen** [comment]
I am fine. Thanks @aczechowski
