### ISSUE TITLE
Link to script is broken

### ISSUE THREAD

**Issue by TerryJ123** [MicrosoftDocs/windows-itpro-docs#10726]
Under Related events, the link to the script referenced in item 2 is not valid.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef8b6967-0e45-bcdd-6d70-54759d9f7ec8
* Version Independent ID: 6651ebc1-04f0-421f-891b-6957ca37da7c
* Content: [Network access - Restrict clients allowed to make remote calls to SAM - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by vinaypamnani-msft** [comment]
Thanks for the feedback @TerryJ123! I've removed the broken reference to the script, and replaced with steps to filter the event log.
