### ISSUE TITLE
謝った翻訳

### ISSUE THREAD

**Issue by naokib** [MicrosoftDocs/windows-itpro-docs#10727]
[フィードバックをこちらに入力してください]
ネゴシエートに関する誤りがあります。

（誤：このページの表記）
ネ ゴシエート – ネゴシエート セキュリティ パッケージは、Kerberos プロトコルと NTLM プロトコルの間で選択します。 ネゴシエートは、認証に関係するシステムの 1 つで使用できない場合や、呼び出し元のアプリケーションが Kerberos を使用するのに十分な情報を提供していない**場合は**、Kerberos を選択します。

（正：本来あるべき表記）
ネゴシエート–ネゴシエートセキュリティパッケージは、KerberosプロトコルとNTLMプロトコルのどちらかを選択します。Negotiateは、認証に関係するシステムの1つで使用できない場合、または呼び出し元のアプリケーションがKerberosを使用するための十分な情報を提供しなかった**場合を除き**、Kerberosを選択します。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 80307c25-b809-e9b8-bab2-d37d3de7e920
* Version Independent ID: 24c32be1-2fc3-f22f-7e6c-da4049bf8458
* Content: [4625(F) アカウントのログオンに失敗しました。 (Windows 10) - Windows security](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/auditing/event-4625)
* Content Source: [windows/security/threat-protection/auditing/event-4625.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/main/windows/security/threat-protection/auditing/event-4625.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment]
Thank you @naokib for the feedback. Using a translation tool and comparing with what's in the source English version, I understand this issue to be with the translation of that paragraph in Japanese. I'm sending this issue to our localization team to review and address (bug ID 216509). I'm closing this issue, as the other team will take it from here.
