### ISSUE TITLE
Is the requirement "Active Directory-joined" true?

### ISSUE THREAD

**Issue by MarineBDCoru** [MicrosoftDocs/windows-itpro-docs#10734]
Hello, 

We would like to understand if we really can activate Windows 10 Sub. on **Active Directory-joined** devices. 
It's working on Azure Active Directory (AAD)-joined but not on Active Directory-joined devices.
Is the article correct? 

Thank you very  much, 
Marine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c34b8c-44b9-b3d3-9894-5a7fd68e2309
* Version Independent ID: ea643c8f-e92d-b90e-4e90-f338cea39e79
* Content: [Configure VDA for Windows 10/11 Subscription Activation - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/vda-subscription-activation)
* Content Source: [windows/deployment/vda-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/vda-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by msbemba** [comment]
@MarineBDCoru Thank you for your feedback. Yes, the requirement is accurate and it works if the VMs are joined to Active Directory or Azure Active Directory (Azure AD).

If this is still an issue, I'd suggest opening up a Microsoft support ticket so that our support engineers will be able to investigate, troubleshoot and resolve the issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
Thanks @MarineBDCoru  for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:
- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
