### ISSUE TITLE
Add policy that will allow additional certificate OID for enumeration

### ISSUE THREAD

**Issue by jamesburkecissp** [MicrosoftDocs/windows-itpro-docs#10739]
I am trying to find someone in Microsoft that can update a policy that would allow an additional certificate OID for enumeration.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 132e8bfa-12ba-2ae0-7745-545bcfd909f1
* Version Independent ID: 984c17f4-04a4-bf30-3a9e-3af49209f0bb
* Content: [Certificate Requirements and Enumeration (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration)
* Content Source: [windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment]
Thanks @jamesburkecissp for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by jamesburkecissp** [comment]
Aaron,
This issue is probably something that needs to be brought up to Microsoft Support or Microsoft Unified Support Team.
I have an technical white paper that explains the issue, but I don’t have a contact to share the paper with and discuss the issue.
James

James Burke, CISSP, CSEIP (ICAM PACS) - SynchroCyber Corporation – A HUBZone Company
***@***.******@***.***> |   703.862.5500<tel:703.862.5500> (m) 703.649.6285 (f)
17959 Dumfries Shopping Plaza, Suite 2B, Dumfries VA 22026
[signature_3184080142]<https://www.synchrocyber.com/>[Graphical user interface, text, application  Description automatically generated with medium confidence]

Cyber Security | Identity and Access Management | HSPD-12 / PIV / Smart Cards / Authentication

The information transmitted in this e-mail is intended solely for specified receiver(s) and may contain confidential and/or privileged material.  Any review, retransmission, dissemination or other use of the information contained in this email by persons or entities other than the intended recipient is unauthorized and prohibited. If you have received this email in error, please contact the sender by return e-mail and delete the material from any computer immediately. -


From: Aaron Czechowski ***@***.***>
Reply-To: MicrosoftDocs/windows-itpro-docs ***@***.***>
Date: Friday, July 29, 2022 at 11:40 AM
To: MicrosoftDocs/windows-itpro-docs ***@***.***>
Cc: ***@***.***" ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/windows-itpro-docs] Add policy that will allow additional certificate OID for enumeration (Issue #10739)


Thanks @jamesburkecissp<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jamesburkecissp&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=h6G80RQ-puXFt15yxX-b-3LgVg4YbIPQwA9uEoG-wU8&m=bGPD39cEWnvtUZEM2J7BBL1U0NgojT7uJS6Un8JR0KQ&s=5ED85JvgffMi-mV8ygkGdJQFhyvx1U-ef-rO3TNMliM&e=> for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

  *   Post to Windows on Q&A<https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.microsoft.com_answers_products_windows&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=h6G80RQ-puXFt15yxX-b-3LgVg4YbIPQwA9uEoG-wU8&m=bGPD39cEWnvtUZEM2J7BBL1U0NgojT7uJS6Un8JR0KQ&s=2i73QqDJ1iB7T5tUQtiSASgQ2dBIVbF42JfIE3Yg074&e=>. These are moderated by community members who are very experienced, knowledgeable, and helpful.
  *   Use Microsoft Support<https://urldefense.proofpoint.com/v2/url?u=https-3A__support.microsoft.com_windows&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=h6G80RQ-puXFt15yxX-b-3LgVg4YbIPQwA9uEoG-wU8&m=bGPD39cEWnvtUZEM2J7BBL1U0NgojT7uJS6Un8JR0KQ&s=u6nPO2AZh2vzxWAOCScRs5CHMpuEuXQPjnSi_dw-U0s&e=> to search for the issue, or open a case with professional support.
  *   Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
