### ISSUE TITLE
Error code 0x80090016 Not listed

### ISSUE THREAD

**Issue by ColetteJ1** [MicrosoftDocs/windows-itpro-docs#1073]
I get the error code 0x80090016 when I try to set up a Windows Hello pin number. It is not listed in the error code list that it sends me to. http://aka.ms/PINErrors

**Comment by DaniHalfin** [comment]
@MikeStephens-MS FYI

**Comment by DaniHalfin** [comment]
Hi @ColetteJ1, appreciate you reaching out and sorry it took us so long to get back to you.
For error codes unlisted here, in most cases those are transient error codes being surfaced by other services in the Windows Hello dependency chain.
We are working on something to improve the user experience in that regard, but that will not solve the issues you are experiencing.
If we find a reoccurring error codes that isn't covered here and should be (meaning, in most cases, it is coming from Windows Hello and not other components) we'll make sure to add it to this page.
For any issue you're seeing, please either file a problem through Feedback Hub, or reach out through our various support channels. Both avenues allow us to properly investigate the issue in ways we could never do through a comments section on a GitHub issue.
The feedback section in the topic is generally meant for feedback on the content, and we can't really use it for in-depth troubleshooting.
We thank you for taking the time to reach out, but we also want you to have the best time to resolution of the issue, and going through this feedback channel won't get us there.
I'll be closing this issue, but feel free to respond if you feel we missed something. We can always re-open.
