### ISSUE TITLE
Comparison & differences

### ISSUE THREAD

**Issue by Psuresh4206** [MicrosoftDocs/windows-itpro-docs#10733]
Hi Team,

if you can add differences in the page this will help us to figure out the resolution. currently McAfee is not getting installed on LTSC version and unable to troubleshoot the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684ab805-b732-043b-9d4c-e8c02660557a
* Version Independent ID: 5c288d08-f2cb-3927-93cb-acb2412fc62c
* Content: [Windows 10 Enterprise LTSC - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/ltsc/)
* Content Source: [windows/whats-new/ltsc/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/ltsc/index.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Psuresh4206 for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
