### ISSUE TITLE
## You can change the shell with dropdown options.

### ISSUE THREAD

**Issue by Lionz01** [MicrosoftDocs/windows-itpro-docs#10743]
## You can change the shell with dropdown options.
![image](https://user-images.githubusercontent.com/70012972/176994391-3a7c644c-8bfc-43de-9852-4642b0131376.png)

_Originally posted by @rohitkumarankam in https://github.com/0dayCTF/reverse-shell-generator/issues/92#issuecomment-1172866792_

**Comment by aczechowski** [comment]
I don't see anything in the windows-itpro-docs repo that has anything to do with this topic. So I'm going to assume this issue was misfiled. If that's not the case, please reopen with additional detail as to what specific docs.microsoft.com article this issue is referencing.
