### ISSUE TITLE
Outdated info

### ISSUE THREAD

**Issue by andlommy** [MicrosoftDocs/windows-itpro-docs#1074]
Windows 10 1803 includes more Per-user services than listed in the article. 
Example: CaptureService
List should be updated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa890d7-00c3-8e74-54af-3f3aa2aeb4c4
* Version Independent ID: 0ad75b5c-a4e1-a954-163a-fd8922b8f760
* Content: [Per-user services in Windows 10 and Windows Server](https://docs.microsoft.com/en-us/windows/application-management/per-user-services-in-windows#feedback)
* Content Source: [windows/application-management/per-user-services-in-windows.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/per-user-services-in-windows.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by Justinha** [comment]
@andlommy Thanks for the heads up. We are confirming some info with engineering then we will update the topic.

**Comment by Justinha** [comment]
@andlommy the list is updated.
