### ISSUE TITLE
Windows Firewall PORQUDAPROBLEMAS PC

### ISSUE THREAD

**Issue by arixdjw** [MicrosoftDocs/windows-itpro-docs#10747]
[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 8c552a93-32b2-294c-6b95-8e78bcf3055d
* Version Independent ID: 02adbfec-c878-1227-bfe2-8cb8d331276f
* Content: [Lista de comprobación Para implementar un diseño de directiva de aislamiento de dominio (Windows) - Windows security](https://docs.microsoft.com/es-es/windows/security/threat-protection/windows-firewall/checklist-implementing-a-domain-isolation-policy-design)
* Content Source: [windows/security/threat-protection/windows-firewall/checklist-implementing-a-domain-isolation-policy-design.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/main/windows/security/threat-protection/windows-firewall/checklist-implementing-a-domain-isolation-policy-design.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment]
Thanks @arixdjw for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
