### ISSUE TITLE
Correction needed to the Prerequisite part.

### ISSUE THREAD

**Issue by Ramnay** [MicrosoftDocs/windows-itpro-docs#10757]
[Enter feedback here]
Current https://docs.microsoft.com/en-us/windows/deployment/update/update-status-admin-center#prerequisites is not up to date based on the MC397469 below are the roles allowed to access the page

Global admin
Global reader
Office apps admin
Reports reader
Usage summary reports reader
Intune administrator
Exchange admin

https://admin.microsoft.com/adminportal/home?ref=MessageCenter/:/messages/MC397469

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be3fada2-23f1-8305-435d-b57192345e8e
* Version Independent ID: be3fada2-23f1-8305-435d-b57192345e8e
* Content: [Microsoft admin center software updates (preview) page - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-status-admin-center#prerequisites)
* Content Source: [windows/deployment/update/update-status-admin-center.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-status-admin-center.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by msbemba** [comment]
@Ramnay Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11018

Once the author approves, the changes will be live.

Thanks
Sri
