### ISSUE TITLE
ADMX_WinLogon/DisplayLastLogonInfoDescription

### ISSUE THREAD

**Issue by Niglb** [MicrosoftDocs/windows-itpro-docs#10753]
For "https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-admx-winlogon#admx-winlogon-displaylastlogoninfodescription" - "ADMX_WinLogon/DisplayLastLogonInfoDescription" we are seeing the error quoted ("Windows couldn't retrieve the information and the user won't be able to sign in") in Azure AD joined device environments recently. 

This error is intermittent but perhaps clarity on Azure AD joined environments should be specified in this description. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdf90c00-116e-a6f7-a2d4-caac61624ab6
* Version Independent ID: cb123103-f54f-0e28-8947-fd28526d7dda
* Content: [Policy CSP - ADMX_WinLogon - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-admx-winlogon#admx-winlogon-displaylastlogoninfodescription)
* Content Source: [windows/client-management/mdm/policy-csp-admx-winlogon.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-admx-winlogon.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by vinaypamnani-msft** [comment]
Thanks @Niglb for the feedback. We're automating all the CSP docs, and source the descriptions of the policies from the DDF and/or the ADMX files, and as such, we rely on those for the source of truth. This is a very old GPO, and as such would not include any specifics about Azure AD devices.

If you experience any issues, we recommend following options to seek help:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.
