### ISSUE TITLE
OSManagedAuthLevel 0x5

### ISSUE THREAD

**Issue by lexios** [MicrosoftDocs/windows-itpro-docs#1075]
Although nowhere to be found in the documentation all my machines deployed on 1709, have a value of 0x5 and the TPM is set to Full (not delegated).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d46fce78-6956-1b3a-124f-e8188d0412cd
* Version Independent ID: 5891df2d-6432-c5b4-0eff-49b520f59067
* Content: [TPM Group Policy settings (Windows 10)](https://docs.microsoft.com/en-us/windows/security/hardware-protection/tpm/trusted-platform-module-services-group-policy-settings)
* Content Source: [windows/security/hardware-protection/tpm/trusted-platform-module-services-group-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/hardware-protection/tpm/trusted-platform-module-services-group-policy-settings.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@lexios Thanks for raising this. I added that value to the topic.

**Comment by Justinha** [comment]
@lexios Sorry Alexander I got this update wrong. I'm working on improved text with the engineering team. ETA to publish that is Monday.

**Comment by lexios** [comment]
AndreaBichsel closed the case without it being resolved.

**Comment by andreabichsel** [comment]
Reopening--sorry, I thought it had been resolved.

**Comment by lexios** [comment]
It's been a month. Any progress?

**Comment by lexios** [comment]
You can update this ticket since the information are now updated on another documentation page.

https://docs.microsoft.com/en-us/windows/security/hardware-protection/tpm/trusted-platform-module-services-group-policy-settings



Thank you.

**Comment by Justinha** [comment]
@lexios I should have notified here, but I'm glad you saw the update back on June 29.

**Comment by RAJU2529** [comment]
on my windows 10 laptop , registry sets by default , why its  happened to me.
OSManagedAuthLevel  to  5

**Comment by hassmoha** [comment]
Although the TPM owner password is not retained starting with Windows 10, version 1607, or Windows 11, you can change a default registry key to retain it. However, we strongly recommend that you do not make this change. To retain the TPM owner password, set the registry key 'HKLM\Software\Policies\Microsoft\TPM' [REG_DWORD] 'OSManagedAuthLevel' to 4. For Windows 10 versions newer than 1703 the default value for this key is 5. For TPM 2.0, a value of 5 means keep the lockout authorization. For TPM 1.2, it means discard the Full TPM owner authorization and retain only the Delegated authorization. Unless it is changed to 4 before the TPM is provisioned, the owner password will not be saved.
