### ISSUE TITLE
VPN Delete issue on Windows 11.

### ISSUE THREAD

**Issue by dfconroy** [MicrosoftDocs/windows-itpro-docs#10754]
I'm working with Windows 11 and creating some MDM functionality using CSPs. My current issue is that on Windows 10 the DELETE function of a installed VPN is successful, but the same command fails on Windows 11. 
Windows 11 system:
> Edition	Windows 11 Pro
Version	21H2
Installed on	‎7/‎25/‎2022
OS build	22000.832
Experience	Windows Feature Experience Pack 1000.22000.832.0

This shows that the VPN is currently installed on the device: 

> <Get>
 	<CmdID>00000000-0000-0000-0000-000000000000|InstalledVPNs</CmdID>
	<Item>
		<Target>
			<LocURI>./Device/Vendor/MSFT/VPNv2</LocURI>
		</Target>
	</Item>

Returns this:

> <Results>
			<CmdID>3</CmdID>
			<MsgRef>1</MsgRef>
			<CmdRef>00000000-0000-0000-0000-000000000000|InstalledVPNs</CmdRef>
			<Item>
				<Source>
					<LocURI>./Device/Vendor/MSFT/VPNv2</LocURI>
				</Source>
				<Meta>
					<Format xmlns="syncml:metinf">node</Format>
					<Type xmlns="syncml:metinf">com.microsoft/1.2/mdm/VPNv2</Type>
				</Meta>
				<Data>AnyConnectVPN</Data>
			</Item>

And this command to get the details on that specific VPN succeeds too:

> <Get>

			<CmdID>00000000-0000-0000-0000-000000000000|InstalledVPN</CmdID>
			<Item>
				<Target>
					<LocURI>./Device/Vendor/MSFT/VPNv2/AnyConnectVPN</LocURI>
				</Target>
			</Item>
		
Returning this:

> <Results>

			<CmdID>5</CmdID>
			<MsgRef>1</MsgRef>
			<CmdRef>00000000-0000-0000-0000-000000000000|InstalledVPN</CmdRef>
			<Item>
				<Source>
					<LocURI>./Device/Vendor/MSFT/VPNv2/AnyConnectVPN</LocURI>
				</Source>
				<Meta>
					<Format xmlns="syncml:metinf">node</Format>
				</Meta>
		<Data>APNBinding/AppTriggerList/ByPassForLocal/DeviceCompliance/DomainNameInformationList/PluginProfile/ProfileXML/Proxy/RouteList/TrafficFilterList</Data>
			</Item>
		</Results>

But then trying to delete the VPN fails:

> <Delete>
			<Delete><CmdID>00000000-0000-0000-0000-000000000000|DeleteVPN</CmdID>
			<Item>
				<Target>
					<LocURI>./Device/Vendor/MSFT/VPNv2/AnyConnectVPN</LocURI>
				</Target>
			</Item></Delete>

Returning this:

> <Status>
			<CmdID>6</CmdID>
			     <MsgRef>1</MsgRef>
			     <CmdRef>00000000-0000-0000-0000-000000000000|DeleteVPN</CmdRef>
			     <Cmd>Delete</Cmd>
			<Data>500</Data>

Even if I put the DELETE in an ATOMIC it fails.

This:

> <Atomic>
			<Atomic><CmdID>delete vpnAtomic|RemoveVPN.0.0</CmdID>
			<Delete>
				<CmdID>delete vpnDelete|RemoveVPN.0.0</CmdID>
				<Item>
					<Target>
						<LocURI>./Device/Vendor/MSFT/VPNv2/AnyConnectVPN</LocURI>
					</Target>
				</Item>
			</Delete>
			</Atomic>

Returns this:

> <Status>
			<Status><CmdID>7</CmdID>
			<MsgRef>1</MsgRef>
			<CmdRef>delete vpnAtomic|RemoveVPN.0.0</CmdRef>
			<Cmd>Atomic</Cmd>
			<Data>507</Data>
		</Status>
		<Status>
			<CmdID>8</CmdID>
			<MsgRef>1</MsgRef>
			<CmdRef>delete vpnDelete|RemoveVPN.0.0</CmdRef>
			<Cmd>Delete</Cmd>
			<Data>500</Data>
		</Status>

Event viewer on the testing device has this:

> MDM ConfigurationManager: Command failure status. Configuration Source ID: (4F832533-66A2-4432-83FA-BFD4C594BA50), 
Enrollment Name: (MDMFull), 
Provider Name: (VPNv2), 
Command Type: (Clear: first phase of Delete), 
CSP URI: (./Device/Vendor/MSFT/VPNv2/AnyConnectVPN), 
Result: (An attempt was made to reference a token that does not exist.).

(admin edit: refresh metadata with latest)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3032f094-c9b7-6f8c-5b66-2ba152d7c326
* Version Independent ID: 83047fc5-7020-be72-85d6-85fa0bfbf5b7
* Content: [VPNv2 CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp#examples)
* Content Source: [windows/client-management/mdm/vpnv2-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/vpnv2-csp.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by dieterameis** [comment]
We have the same problem on all of our Windows 11 devices (mostly 22H2). 
We are using Intune/Endpoint Manager as MDM.

Changing an VPN profile in Intune results in the same error on delete.

The add operation throws following error: (./Device/Vendor/MSFT/VPNv2/Always ON VPN Device Tunnel/RouteList/0/Address), Ergebnis: (Unknown Win32 Error code: 0x82aa0002).

In the end the configuration gets deployed but is has to be connected manually. Then the tunnel is working as expected. 

The tunnel does not connect automatically because the registry setting under HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\RasMan\DeviceTunnel are missing.
After setting them manually the tunnel connects automatically. 

So reapplying the VPN profile results in missing registry entries. They are deleted but never reapplied.

**Comment by Sendros** [comment]
> We have the same problem on all of our Windows 11 devices (mostly 22H2). We are using Intune/Endpoint Manager as MDM.
> 
> Changing an VPN profile in Intune results in the same error on delete.
> 
> The add operation throws following error: (./Device/Vendor/MSFT/VPNv2/Always ON VPN Device Tunnel/RouteList/0/Address), Ergebnis: (Unknown Win32 Error code: 0x82aa0002).
> 
> In the end the configuration gets deployed but is has to be connected manually. Then the tunnel is working as expected.
> 
> The tunnel does not connect automatically because the registry setting under HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\RasMan\DeviceTunnel are missing. After setting them manually the tunnel connects automatically.
> 
> So reapplying the VPN profile results in missing registry entries. They are deleted but never reapplied.

Hi! Did you find any fix for this?

**Comment by aczechowski** [comment]
Thanks @dfconroy for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time. The CSP content is now mostly auto-generated from the Windows DDF source, including applicability tables for each policy. If something did work on Windows 10 but isn't working on Windows 11, then it should first be directed to support to help troubleshoot and escalate as needed.
