### ISSUE TITLE
Options for and examples of text alignment for displayed text

### ISSUE THREAD

**Issue by elang-bmrn** [MicrosoftDocs/windows-itpro-docs#10761]
Potentially product feedback - is there any way to left align the displayed text on Windows 11? If not, can the documentation describe what options there are (or are not) available for aligning the text, along with screenshots of examples of the text alignment for both Windows 10, and Windows 11?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8897b50b-10e9-5d0b-6150-c1834a296a20
* Version Independent ID: bed1c6d9-91c3-02f2-12c9-58229886118a
* Content: [Interactive Logon Message text (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-message-text-for-users-attempting-to-log-on)
* Content Source: [windows/security/threat-protection/security-policy-settings/interactive-logon-message-text-for-users-attempting-to-log-on.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/interactive-logon-message-text-for-users-attempting-to-log-on.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@elang-bmrn , At first you need to adjust the font and style writing in windows settings and then apply your text in GPO.

**Comment by yogkumgit** [comment]
@Dansimp Please help us in resolving this issue. Thanks.

**Comment by yogkumgit** [comment]
@vinaypamnani-msft Please help us in resolving this issue. Thanks

**Comment by aczechowski** [comment]
I don't think you can format that text in that way. I suggest you [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).

**Comment by elang-bmrn** [comment]
What is the rationale for having it centre-aligned? It doesn't look good if the text spans more than one line, which would cover most interactive logon text messages, including Microsoft's own example:

Interactive Logon Message text (Windows 10) | Microsoft Learn<https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-message-text-for-users-attempting-to-log-on>

"This system is restricted to authorized users. Individuals who attempt unauthorized access will be prosecuted. If you're unauthorized, terminate access now. Click OK to indicate your acceptance of this information."

________________________________
