### ISSUE TITLE
Delivery Optimization Download Mode and Cache Host policy

### ISSUE THREAD

**Issue by ChadSimmons** [MicrosoftDocs/windows-itpro-docs#10764]
When implementing Delivery Optimization policies and specifying the Download Mode and a Cache Host policy the behavior is not necessarily as expected.  This needs clarification.

Examples
1. when [DOCacheHost](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-deliveryoptimization?source=docs#deliveryoptimization-docachehost) policy is also set with multiple servers, it is unclear if a single server is used, all servers are given the same priority (this is our experience), or some logic is used for prioritization.

2. when [DODownloadMode](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-deliveryoptimization?source=docs#deliveryoptimization-dodownloadmode) is set to allow peering (mode 1 and 2) but the [DOCacheHost](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-deliveryoptimization?source=docs#deliveryoptimization-docachehost) policy is also set, it appears that only the cache host is used when available and peering is ignored.  It is unclear if this is the design, our limited testing, or a bug.

3. when [DORestrictPeerSelectionBy](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-deliveryoptimization?source=docs#deliveryoptimization-dorestrictpeerselectionby) is set, it appears that is ignored if a [DOCacheHost](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-deliveryoptimization?source=docs#deliveryoptimization-docachehost) is in use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06745768-affe-c86a-2da6-7bd694e847c9
* Version Independent ID: e832ada1-5f0c-7809-b8a1-bb91cadb6975
* Content: [Policy CSP - DeliveryOptimization - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-deliveryoptimization)
* Content Source: [windows/client-management/mdm/policy-csp-deliveryoptimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-deliveryoptimization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by ChadSimmons** [comment]
Thank you @cmknox for the explanations regarding DOCacheHost and DODownload mode.  That is helpful.

Regarding DORestrictPeerSelectionBy, unfortunately I no longer have access to the environment where this was being tested and causing confusion/concern.  However, your explanation that peering and DOCacheHost are effectively handled distinct from each other is helpful.

Can these comments / clarifications be incorporated into the documentation?

**Comment by aczechowski** [comment]
We're currently in progress to migrate this content over to auto-generated based on the DDF/ADMX. There are spots in the doc for editable sections that could include this information. Any edits should wait until the new automated page publishes. See private PR https://github.com/MicrosoftDocs/windows-docs-pr/pull/7585

**Comment by vinaypamnani-msft** [comment]
I've added clarifications to the doc in a PR which will be merged by end of month, so I'll close this issue now.
