### ISSUE TITLE
Erro na tradução para Português Brasil (pt-br)

### ISSUE THREAD

**Issue by Wagner-RM** [MicrosoftDocs/windows-itpro-docs#10766]
Título da página "4625(F): falha ao fazer logoff em uma conta" está incorreto, o certo seria "4625(F): falha ao fazer logon em uma conta"

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 80307c25-b809-e9b8-bab2-d37d3de7e920
* Version Independent ID: 24c32be1-2fc3-f22f-7e6c-da4049bf8458
* Content: [4625(F) Falha ao fazer logoff uma conta. (Windows 10) - Windows security](https://docs.microsoft.com/pt-br/windows/security/threat-protection/auditing/event-4625)
* Content Source: [windows/security/threat-protection/auditing/event-4625.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/main/windows/security/threat-protection/auditing/event-4625.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
cc @tiburd

**Comment by tiburd** [comment]
@Wagner-RM 
Thank you for submitting this.
I have submitted a translation bug and expect the issue to be fixed soon.

**Comment by TinaMcN** [comment]
@Wagner-RM Obrigado por relatar esse problema.  Foi causado por tradução automática.   Está consertado agora, como você sugeriu.
