### ISSUE TITLE
The output from `cmd` is corrupted.

### ISSUE THREAD

**Issue by oklokl** [MicrosoftDocs/windows-itpro-docs#10773]
https://youtu.be/-YhWF6gqDHI  bat file is broken. (This is my bug reproduction video.)
https://github.com/oklokl/advfirewall-ip-list-firehol_level1.netset/blob/main/v4.bat  That file.

On the first run, the text is garbled.
In the second run, the output is normally.
Windows 10~11 home en Insider all have the same symptoms.
[Version 10.0.19044.1947]

Originally, it was printed normally, but recently it is like this.

I had this symptom even when I ran it immediately after formatting Windows without any settings.

I gave feedback on the Feedback Hub, but it wasn't patched.

**Comment by aczechowski** [comment]
Thanks @oklokl for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time. I searched through our content and don't find any reference to `v4.bat` or anything that includes the commands in the sample you provided. If you have more detail on where this script is referenced in our docs, please let me know.
