### ISSUE TITLE
Instructions wrong

### ISSUE THREAD

**Issue by cthwallis** [MicrosoftDocs/windows-itpro-docs#10770]
When trying to follow the instructions for Intune, there is no Profiles->Endpoint Protection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3af4445-51a2-cca9-492b-458921a6f1d7
* Version Independent ID: ec35f3f6-1ba8-61c1-8f32-749ad741dcac
* Content: [Enable hardware-based isolation for Microsoft Edge (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard)
* Content Source: [windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@cthwallis Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11017

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @cthwallis Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
