### ISSUE TITLE
Wording in deprecation message misleading

### ISSUE THREAD

**Issue by rnitsch70** [MicrosoftDocs/windows-itpro-docs#10772]
"New versions of Windows won't include new capabilities for WIP, and it won't be supported in future versions of Windows."

-> if WIP is still in future versions of Windows, what does it mean "won't be supported". I assume that should mean the product group is not providing fixes. CSS (customer services and support) is still helping the customer wherever they can, so it is still supported in that sense. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d016c711-b1f4-668e-adbc-ff6911965851
* Version Independent ID: 64b2a1a4-1efe-35da-721e-7cbb0b1c684e
* Content: [Protect your enterprise data using Windows Information Protection - Windows security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip.md)
* Product: **m365-security**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @rnitsch70 for the feedback. A couple of additional resources that I suggest you review to help:

- [Announcing the sunset of Windows Information Protection (WIP)](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/announcing-the-sunset-of-windows-information-protection-wip/ba-p/3579282)

   > Certain capabilities within the solution known as Windows Information Protection (WIP), previously referred to as Enterprise Data Protection (EDP) will be discontinued over time. As a result, we recommend that you explore Microsoft Purview Information Protection and Data Loss Prevention for your multi-cloud and multi-platform data protection needs.

- [Windows client features lifecycle - Terminology](https://docs.microsoft.com/windows/deployment/planning/features-lifecycle#terminology)

  > - **Deprecation**: The stage of the product lifecycle when a feature or functionality is no longer in active development and may be removed in future releases of a product or online service.
  > - **End of support**: The stage of the product lifecycle when support and servicing are no longer available for a product.

**Comment by rnitsch70** [comment]
Aaron


Starting in July 2022, Microsoft is deprecating Windows Information Protection (WIP). Microsoft will continue to support WIP on supported versions of Windows. New versions of Windows won't include new capabilities for WIP, and it won't be supported in future versions of Windows. For more information, see Announcing sunset of Windows Information Protection<https://go.microsoft.com/fwlink/?linkid=2202124>.
For your data protection needs, Microsoft recommends that you use Microsoft Purview Information Protection<https://docs.microsoft.com/en-us/microsoft-365/compliance/information-protection> and Microsoft Purview Data Loss Prevention<https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-learn-about-dlp>. Purview simplifies the configuration set-up and provides an advanced set of capabilities.


  1.  What is versions of Windows - starting July 2022.
Is this Windows 12?
Is this Windows 11 22H2 and after?


  1.  It won't include NEW capabilities - so old once will still be there. But this won't be supported IN FUTURE VERSIONS OF WINDOWS
so - it will be in future versions but not be supported. But future versions of Windows will be within the lifecycle. So they will definitely be supported. And so will be WIP if it is in the product, therefore!
What you want to say here is that WIP will not receive any fixes. We will still provide support for WIP.
Or is this saying that if a customer opens a support call with us using Windows 22H2 with a WIP critical situation - we drop the phone and not support them? (I am saying this half ironical, because I know that will not be the case)



Roland

Senior Escalation Engineer
Windows Networking
Customer Services and Support
Office: +49 (221) 80102466
***@***.******@***.***>

My core working hours are 8:00-16:00 CET (UTC+1)

Microsoft Deutschland GmbH, Walter-Gropius-Straße 5, 80807 München
Datenschutzerklärung von Microsoft <https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprivacy.microsoft.com%2Fde-DE%2Fprivacystatement&data=04%7C01%7Crnitsch%40microsoft.com%7C1e891cd528d240528e4f08d8e4711765%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637510522655800848%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=coPXCeYEMXDPmmfURz6glj2XoyiIBRapfZjFDhp8IjU%3D&reserved=0>
