### ISSUE TITLE
"Windows 11" under Software Requirements should be clarified with specific editions

### ISSUE THREAD

**Issue by nimishkumar** [MicrosoftDocs/windows-itpro-docs#10778]
Under section Software Requirements > Operating System, "Windows 11" is not quite accurate since it implies that MDAG is supported on all Windows editions in Windows 11. This should be clarified to say that MDAG is only supported on certain editions of Windows 11 (Enterprise, Pro, Education).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfc5c60d-c82a-f2b6-f90e-01c58655665f
* Version Independent ID: f6c79142-8b99-faac-a2f5-0acb62fc26a8
* Content: [System requirements for Microsoft Defender Application Guard - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-application-guard/reqs-md-app-guard)
* Content Source: [windows/security/threat-protection/microsoft-defender-application-guard/reqs-md-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-application-guard/reqs-md-app-guard.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@nimishkumar  . I will add editions afternoon
