### ISSUE TITLE
Certificate Tile Enumeration

### ISSUE THREAD

**Issue by jamesburkecissp** [MicrosoftDocs/windows-itpro-docs#10776]
The problem with the document is digital email signature certificates that have this OID Secure Email (1.3.6.1.5.5.7.3.4) cannot be used because the Microsoft Tile Enumeration doesn’t recognize this OID as valid when it should. A large number of users have a digital email signature certificate with this OID that want to use it for authentication and cannot because Microsoft Tile Enumeration doesn't show the certificate as an option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 132e8bfa-12ba-2ae0-7745-545bcfd909f1
* Version Independent ID: 984c17f4-04a4-bf30-3a9e-3af49209f0bb
* Content: [Certificate Requirements and Enumeration (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration)
* Content Source: [windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration.md)
* Product: **m365-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by aczechowski** [comment]
Hi @jamesburkecissp can you share which document you're referring to? I can't find in our content any reference to some of the keywords you mentioned.

**Comment by jamesburkecissp** [comment]
This is the document: https://docs.microsoft.com/en-us/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration
Windows OS has polices to allow digital email certificates for authentication. It does this by Enumerating the digital certificates as login tiles.
It has some requirements for the certificate to be enumerated (displayed) as an option for login.
Many email signing certificates now come with the OID Secure Email (1.3.6.1.5.5.7.3.4), which the OS doesn’t allow for tile enumeration.
This is breaking allowing email signing certificates to be used for authentication.

James Burke, CISSP, CSEIP (ICAM PACS) - SynchroCyber Corporation – A HUBZone Company
***@***.******@***.***> |   703.862.5500<tel:703.862.5500> (m) 703.649.6285 (f)
17959 Dumfries Shopping Plaza, Suite 2B, Dumfries VA 22026
[signature_3987817807]<https://www.synchrocyber.com/>[Graphical user interface, text, application  Description automatically generated with medium confidence]

Cyber Security | Identity and Access Management | HSPD-12 / PIV / Smart Cards / Authentication

The information transmitted in this e-mail is intended solely for specified receiver(s) and may contain confidential and/or privileged material.  Any review, retransmission, dissemination or other use of the information contained in this email by persons or entities other than the intended recipient is unauthorized and prohibited. If you have received this email in error, please contact the sender by return e-mail and delete the material from any computer immediately. -


From: Aaron Czechowski ***@***.***>
Reply-To: MicrosoftDocs/windows-itpro-docs ***@***.***>
Date: Wednesday, August 17, 2022 at 11:59 AM
To: MicrosoftDocs/windows-itpro-docs ***@***.***>
Cc: ***@***.***" ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/windows-itpro-docs] Certificate Tile Enumeration (Issue #10776)


Hi @jamesburkecissp<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jamesburkecissp&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=h6G80RQ-puXFt15yxX-b-3LgVg4YbIPQwA9uEoG-wU8&m=57Pn0d3c8QmU6W8Fy7iCg9plJLg0qZ038O-4ZyD4On4&s=jKwuS5KTiqIJWf5xjVkf_Zk8V__1BYTzjX740ARv1MI&e=> can you share which document you're referring to? I can't find in our content any reference to some of the keywords you mentioned.

**Comment by paolomatarazzo** [comment]
@jamesburkecissp the documentation calls out this requirement: "The certificate must have the smart card logon EKU."
Are you saying that are you expecting the OS to enumerate certs without this EKU, but solely with the Secure Emai OID?

**Comment by jamesburkecissp** [comment]
The Document states “You can enable any certificate to be visible for the smart card credential provider.”

The associated policy, “Allow certificates with no extended key usage certificate attribute,” applies to enumeration (showing up as a logon tile). If this policy setting is enabled, certificates

with the following attributes can also be used to logon with a smart card:

• Certificates with no Enhanced Key Usage (EKU)

• Certificates with an All Purpose EKU

• Certificates with a Client Authentication EKU



Need to add certificates with EKU Secure Email OID 1.3.6.1.5.5.7.3.4

These are digital signing certificates and are able to complete authentication, but they are not showing up as a login tile/enumeration because they has the secure email OID.

This is impacting millions of civilian federal government using PIV/Smartcards to authenticate.

I have a document that explains this, but I don’t know how to send for review.

James Burke, CISSP, CSEIP (ICAM PACS) - SynchroCyber Corporation – A HUBZone Company
***@***.******@***.***> |   703.862.5500<tel:703.862.5500> (m) 703.649.6285 (f)
17959 Dumfries Shopping Plaza, Suite 2B, Dumfries VA 22026
[signature_296103672]<https://www.synchrocyber.com/>[Graphical user interface, text, application  Description automatically generated with medium confidence]

Cyber Security | Identity and Access Management | HSPD-12 / PIV / Smart Cards / Authentication

The information transmitted in this e-mail is intended solely for specified receiver(s) and may contain confidential and/or privileged material.  Any review, retransmission, dissemination or other use of the information contained in this email by persons or entities other than the intended recipient is unauthorized and prohibited. If you have received this email in error, please contact the sender by return e-mail and delete the material from any computer immediately. -


From: Paolo Matarazzo ***@***.***>
Reply-To: MicrosoftDocs/windows-itpro-docs ***@***.***>
Date: Friday, August 19, 2022 at 10:19 AM
To: MicrosoftDocs/windows-itpro-docs ***@***.***>
Cc: ***@***.***" ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/windows-itpro-docs] Certificate Tile Enumeration (Issue #10776)


@jamesburkecissp<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jamesburkecissp&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=h6G80RQ-puXFt15yxX-b-3LgVg4YbIPQwA9uEoG-wU8&m=SljuqXdDIw1EQVy_KjcNlz7C2dYDOKS3MrL-KV6T3n8&s=rYEhRBDBQjhTxCo0JR4szTjTx2xA0DCV0pd6s4TrXXE&e=> the documentation calls out this requirement: "The certificate must have the smart card logon EKU."
Are you saying that are you expecting the OS to enumerate certs without this EKU, but solely with the Secure Emai OID?

**Comment by paolomatarazzo** [comment]
Thanks @jamesburkecissp for taking the time to share this with the Windows documentation team. I want to make sure it gets to the right people that can help. Please reach [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, and open a case with professional support.

I'm closing this issue as there's nothing actionable for docs at this time.
