### ISSUE TITLE
MDE for Linux - frequency of automatic definition updates

### ISSUE THREAD

**Issue by Drieschi** [MicrosoftDocs/windows-itpro-docs#10775]
As the title says i wonder how often MDE for Linux will check for new definition updates if automatic security intelligence updates are enabled. Sadly i wasn't able to find any document clarifying this question.

**Comment by aczechowski** [comment]
Hi @Drieschi you can find the MDE for Linux documentation under Microsoft 365 Security: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux
If you're not able to find something there that answers your question, then you can file feedback on one of those articles to reach the authors of that content.

**Comment by Drieschi** [comment]
Hello @aczechowski, I already know all these articles, but I didn't find an answer or a way to contact the author of this article. So I asked here.

@Dansimp, since you are the author of the mentioned article, can you answer my question?

**Comment by aczechowski** [comment]
@Drieschi the MDE for Linux articles have this same feedback functionality enabled. For example, see the Feedback section at the bottom of the overview article: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide#feedback
and select the option for **This page**

**Comment by Oechiih** [comment]
Hi @aczechowski 
So the same question @Drieschi had came up for me as well. How does Linux actually handle definition updates? Is it on a schedule, if so: what is it? Or is there some sort of push mechanism that automatically updates the definitions on Linux as they are published?
Cheers
