### ISSUE TITLE
Duplicated content

### ISSUE THREAD

**Issue by miqm** [MicrosoftDocs/windows-itpro-docs#10785]
The section `Configure Web Sign-in Allowed URLs for Third Party Identity Providers on Azure AD Joined Devices`has duplicated content regarding setting up allowed urls. please verify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9dae9da-eaf0-c209-7c65-be8d2c1ada12
* Version Independent ID: 28b6788d-7982-23c2-5f19-f80690ebc0ce
* Content: [Pin Reset - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset?tabs=intune)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md)
* Product: **m365-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by RAJU2529** [comment]
@miqm I will remove duplicate content today afternoon

**Comment by paolomatarazzo** [comment]
Thank you for your contribution @miqm! The duplicate content has been addressed and you should see the document update soon.
