### ISSUE TITLE
EI.cfg incorrectly called IE.cfg

### ISSUE THREAD

**Issue by aisgbnok** [MicrosoftDocs/windows-itpro-docs#10782]
### Description

Unfortunately I couldn't figure out what repo this page belongs to. (I don't think it's public.) Anyway, `EI.cfg` is called  `IE.cfg` incorrectly on the first bullet point. Thanks!

![image](https://user-images.githubusercontent.com/10838153/185699790-39988093-3c51-4423-b85e-317df691b17d.png)

[Windows Setup Edition Configuration and Product ID Files (EI.cfg and PID.txt)](https://docs.microsoft.com/windows-hardware/manufacture/desktop/windows-setup-edition-configuration-and-product-id-files--eicfg-and-pidtxt)

**`original_content_git_url`:**  [`https://github.com/MicrosoftDocs/commercialization-docs-pr/blob/live/manufacture/desktop/windows-setup-edition-configuration-and-product-id-files--eicfg-and-pidtxt.md`](https://github.com/MicrosoftDocs/commercialization-docs-pr/blob/live/manufacture/desktop/windows-setup-edition-configuration-and-product-id-files--eicfg-and-pidtxt.md)

**Comment by aczechowski** [comment]
I'll pass this along to the content owner, but close this issue since it's not actionable for this repo.
