### ISSUE TITLE
Conditional Access?

### ISSUE THREAD

**Issue by wUEZRs** [MicrosoftDocs/windows-itpro-docs#10787]
I do not see any Conditional Access policies created by the enrollment of Autopatch. Is this not expected behaviour? If so why do I not see them? The requirement checks did not fail

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b585379-5f7d-61e7-cd7c-964ca6d9df72
* Version Independent ID: 0b585379-5f7d-61e7-cd7c-964ca6d9df72
* Content: [Maintain the Windows Autopatch environment - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopatch/operate/windows-autopatch-maintain-environment)
* Content Source: [windows/deployment/windows-autopatch/operate/windows-autopatch-maintain-environment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopatch/operate/windows-autopatch-maintain-environment.md)
* Product: **w11**
* Technology: **windows**
* GitHub Login: @tiaraquan
* Microsoft Alias: **tiaraquan**

**Comment by tiaraquan** [comment]
@wUEZRs 

Thank you for your feedback. Conditional access policies are no longer created in the Autopatch service as of August 15, 2022. We have updated our documentation to reflect this change.
