### ISSUE TITLE
Please provide examples for when to use

### ISSUE THREAD

**Issue by hanscees** [MicrosoftDocs/windows-itpro-docs#10798]
Some examples of scenarios where this can be useful would be helpful, this is not at all clear to me.
Also, how to prevent a major issue scenario where no one can login after a dns server is changed comes to mind.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f8c2ce-8edb-60d3-ebf9-bdb625bf66dc
* Version Independent ID: ee1ed0a8-b05c-c499-6504-40b5b298c53b
* Content: [Multi-factor Unlock - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/feature-multifactor-unlock)
* Content Source: [windows/security/identity-protection/hello-for-business/feature-multifactor-unlock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/feature-multifactor-unlock.md)
* Product: **m365-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @hanscees and thank you for the feedback.
At the beginning of the article there are some good use cases for multifactor unlock:
"Which organizations can take advantage of Multi-factor unlock? Those who:

Have expressed that PINs alone do not meet their security needs.
Want to prevent Information Workers from sharing credentials.
Want their organizations to comply with regulatory two-factor authentication policy.
Want to retain the familiar Windows sign-in user experience and not settle for a custom solution."

Are these scenarios not sufficient?
To answer your question about major issue like DNS, you can always login with cached credentials and fall back to password, if kept enabled.

**Comment by hanscees** [comment]
Hi Paolo, 
What I mean is more examples on what's possible. So for instance:

If you find pincode alone not sufficient possibilities are:
- add a Bluetooth signal from a user. So pin will only unlock when that Bluetooth signal is present
- Add a specific network range, so pin will only unlock when a the pc has an ip address in a specific network range 
- Combine facial discovery with pincode. 

In the text right now you have to delve into the tech bits to find the functional possibilities.
