### ISSUE TITLE
Possible editing error in this document?  Replace all instances of "adfssvc" with "the name of your AD FS service account"

### ISSUE THREAD

**Issue by frazeraccount** [MicrosoftDocs/windows-itpro-docs#10796]
In the section "Creating an Enrollment Agent certificate for Group Managed Service Accounts", steps 10 and 11, as well as the section, "Creating an Enrollment Agent certificate for typical Service Accounts", steps 8 and 9, it appears the document instructs us to select an account called adfssvc.  However, it appears to me the document should instead instruct us to select our AD FS service account name.  Am I mistaken?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd063d0c-8739-15bd-4f16-11b893029845
* Version Independent ID: cd3679fe-dd9c-44f9-04ed-c772a47ca4e4
* Content: [Configuring Hybrid Azure AD joined Windows Hello for Business - Public Key Infrastructure (PKI) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki#enrollment-agent-certificate-template)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki.md)
* Product: **m365-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @frazeraccount thank you for the feedback. The document that you are pointing to is a deployment guide, which starts here: https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki
If you follow the article step by step, you will find the "Configure AD FS step" which states: "In the Enter the object names to select text box, type adfssvc or substitute the name of the AD FS service account in your AD FS deployment. Click OK."
This obviously applies to the rest of the article, but it's not called out in each instance. If you take the section out of the deployment guide context, you are correct.
