### ISSUE TITLE
Cltr+Windows+Q doesnt work anymore

### ISSUE THREAD

**Issue by rgkey9000** [MicrosoftDocs/windows-itpro-docs#10797]
Shortcut doesnt work with the new Quick Assist which is prompted to install from the MS Store
This in contrary what it states on the page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfcd14cd-f887-660f-8a4c-465b3495e90e
* Version Independent ID: 121eead7-eb87-f033-024a-f688866c58a0
* Content: [Use Quick Assist to help users - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/quick-assist)
* Content Source: [windows/client-management/quick-assist.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/quick-assist.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @rgkey9000 for the feedback, we already have an item tracking this: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10699
So I'm closing this issue as a duplicate.
