### ISSUE TITLE
Editing Kiosk Browser:

### ISSUE THREAD

**Issue by JMelli** [MicrosoftDocs/windows-itpro-docs#1079]
To edit the policies in the Kiosk Browser, is Microsoft Intune required as a prerequisite?    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d983ddae-5666-2298-3dd7-12b4d3fd3e6b
* Version Independent ID: 4576b49b-5a2b-e838-50c9-181f9f265360
* Content: [Policy CSP - KioskBrowser](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-kioskbrowser#kioskbrowser-defaulturl)
* Content Source: [windows/client-management/mdm/policy-csp-kioskbrowser.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-kioskbrowser.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by larry0987** [comment]
I installed Windows Configuration Designer, both from the ADK and Store, neither has any options related to the KioskBrowser that I can find. Any documentation or screenshots on how to configure this via WCD?

**Comment by jdeckerms** [comment]
@larry0987 The settings are in the Policies section. Runtime settings > Policies > KioskBrowser

**Comment by larry0987** [comment]
Is there a version requirement for the ADK? I have an option for Browser, but no KioskBrowser. I have version 10.0.17134.1 of WCD. I started 'Advanced Provisioning' for all Windows editions to make sure nothing was filtered out. 
![wcd](https://user-images.githubusercontent.com/2936068/45449059-236b6c80-b6a2-11e8-8ee0-c821618fd40d.JPG)

**Comment by jdeckerms** [comment]
You want Advanced Provisioning for Windows 10 Desktop editions. :)

**Comment by jdeckerms** [comment]
@larry0987 Good questions -- I'm updating https://docs.microsoft.com/en-us/windows/configuration/guidelines-for-assigned-access-app#guidelines-for-web-browsers to make it clearer.

**Comment by jdeckerms** [comment]
@larry0987 Just to clarify: selecting "all Windows editions" means it only shows you the settings that every edition has in common.
