### ISSUE TITLE
Missing the DS at the end?

### ISSUE THREAD

**Issue by simonburbery** [MicrosoftDocs/windows-itpro-docs#10807]
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-faq#does-windows-hello-for-business-work-with-azure-active-directory-domain-services--azure-ad-ds--clients

Hi, the link above talks about "Does Windows Hello for Business work with Azure Active Directory Domain Services (Azure AD DS) clients".  But the last sentence shows "Hence, Windows Hello for Business doesn't work with **Azure AD.**"

Shouldn't it be "Hence, Windows Hello for Business doesn't work with **Azure AD DS**."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82ecd7ea-0ecb-cf7b-a1ab-9cda97e5cc0a
* Version Independent ID: 81acb0ad-2d46-bd0b-abb5-7c2e851d7a71
* Content: [Windows Hello for Business Frequently Asked Questions (FAQ) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-faq)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-faq.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-faq.yml)
* Product: **m365-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
thank you @simonburbery , I updated the string and will be reflected soon
