### ISSUE TITLE
Minimum password length Best Practices documentation are unclear and contradictory 

### ISSUE THREAD

**Issue by tristanweir** [MicrosoftDocs/windows-itpro-docs#10801]
The [Best Practices section of this article](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/minimum-password-length#best-practices) is not clear as to what the actual best practices are.

1. Guidance on password length is contradictory in the same paragraph.
> Set Minimum password length to at least a value of 14.

is in conflict with

> an eight-character password is recommended

and 

> A minimum password length greater than 14 isn't supported at this time

(i.e. you can't set a Minimum password length to **at least** 14 if that's the max value allowed).

2. Qualitative terms like _short_ and _long_ confuse the issue.

> Permitting short passwords reduces security because short passwords can be easily broken with tools that do dictionary or brute force attacks against the passwords. 

This is true, but not helpful  because it doesn't define what short is. I recommend you contextualize it (e.g. "short passwords (<12 characters)").

3. The article does not mention guarding against password reuse.

User education seems to be in scope, because the best practices encourage teaching users to use passphrases.

> if users are taught that they can use passphrases... they should be much more likely to remember.

This is then a good time to reinforce that users should pick passwords that are unique, which is the most valuable way to reduce risk of compromise, even for logging in to a local system. This is not directly related to password minimum length, but neither is password complexity which is partially covered in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bcaf30b-7304-6874-ba5d-791cc4d435d2
* Version Independent ID: 961def9f-094a-3d1e-82a4-bb152c2e5a1e
* Content: [Minimum password length (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/minimum-password-length)
* Content Source: [windows/security/threat-protection/security-policy-settings/minimum-password-length.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/minimum-password-length.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment]
Thanks @tristanweir for the feedback. There's an existing one https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10390 and an open pull request https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10756 regarding this issue. I'm trying to get more information from a relevant PM. So I'm closing this issue as a duplicate. (You can subscribe to one of the other items to get any future updates on this topic.)
