### ISSUE TITLE
Windows 11 error 65000

### ISSUE THREAD

**Issue by pchatham** [MicrosoftDocs/windows-itpro-docs#10819]
Is "_NewsAndInterests_" relevant for Windows 11? I just get error 65000 when I set it through the settings catalog
 
https://call4cloud.nl/2021/07/65000-days-of-night/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b8f2d68-ff96-ff9e-7707-fe8ac2efede0
* Version Independent ID: 9b8f2d68-ff96-ff9e-7707-fe8ac2efede0
* Content: [Policy CSP - NewsAndInterests - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-newsandinterests)
* Content Source: [windows/client-management/mdm/policy-csp-newsandinterests.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-newsandinterests.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
Thanks @pchatham for taking the time to share this with the Windows documentation team. I confirmed that the AllowNewsAndInterests policy is applicable for Windows 11 and I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
