### ISSUE TITLE
False statement under ADMX_WindowsStore/RemoveWindowsStore_1

### ISSUE THREAD

**Issue by VitalKoshalew** [MicrosoftDocs/windows-itpro-docs#10810]
The following statement under ADMX_WindowsStore/RemoveWindowsStore_1 is false or at least confusing:
"Access to the Store is required for installing app updates."
Automatic updates are being installed regardless of ADMX_WindowsStore/RemoveWindowsStore_1 being enabled or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2feed46f-cb92-87aa-dc7f-e1d03cdd5bb5
* Version Independent ID: 288a1749-4270-c0ab-64bd-4dd1b7018f23
* Content: [Policy CSP - ADMX_WindowsStore - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-admx-windowsstore)
* Content Source: [windows/client-management/mdm/policy-csp-admx-windowsstore.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-admx-windowsstore.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
We're revamping the CSP docs, and automating them. We'll be publishing an update to the ADMX_WindowStore CSP docs, and I've verified that the new content does not have this wording, so I'm closing this issue now. The changes would be live by end of this month when we merge the changes.
