### ISSUE TITLE
set-vmprocessor command without space

### ISSUE THREAD

**Issue by JohnMoor** [MicrosoftDocs/windows-itpro-docs#10820]
[Enter feedback here]
Under "If you're installing MCC on a local virtual machine" the first command has a space after Set, which should be removed:

Set -VMProcessor -VMName "VM name" -ExposeVirtualizationExtensions $true

should be:

Set-VMProcessor -VMName "VM name" -ExposeVirtualizationExtensions $true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b57838ef-4f28-8f97-d9be-fb841393c6a7
* Version Independent ID: b57838ef-4f28-8f97-d9be-fb841393c6a7
* Content: [Microsoft Connected Cache for Enterprise and Education (private preview) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/do/mcc-enterprise)
* Content Source: [windows/deployment/do/mcc-enterprise.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/do/mcc-enterprise.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @carmenF
* Microsoft Alias: **carmenf**

**Comment by msbemba** [comment]
@JohnMoor Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10980

Once the author approves, the changes will be live.

Thanks
Sri
