### ISSUE TITLE
Incorrect statement regarding subscription activation?

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/windows-itpro-docs#10823]
Hi

In the table towards the top of the page, subscription activation is listed as a dynamic deployment. 
However, further down the page, under the heading _Windows 10 Subscription Activation_ it states 

> Windows 10 Subscription Activation is a modern deployment method 

The statement seems to be incorrect, or at least to use an unfortunate wording which could lead to confusion. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1ef8892-3dcd-17ff-9162-77fe036d000a
* Version Independent ID: 46f90fbb-2ce7-e4a0-5cc9-81d46c5ca0e5
* Content: [Windows 10 deployment scenarios (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-10-deployment-scenarios?source=docs#windows-10-subscription-activation)
* Content Source: [windows/deployment/windows-10-deployment-scenarios.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-deployment-scenarios.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by msbemba** [comment]
@baardhermansen Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10986

Once the author approves, the changes will be live.

Thanks
Sri
