### ISSUE TITLE
doont wokr

### ISSUE THREAD

**Issue by Marphh** [MicrosoftDocs/windows-itpro-docs#10830]
[Enter feedback here]
did absolutely nothing bruh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6df748e4-5411-9c17-ad97-0a4fc43dc481
* Version Independent ID: 714fb464-896f-6c5b-edbf-573c0bff13a4
* Content: [Breaking out of a BitLocker recovery loop - Windows security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-recovery-loop-break)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-recovery-loop-break.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-recovery-loop-break.md)
* Product: **m365-security**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Marphh for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
