### ISSUE TITLE
ADMX_WindowsExplorer/EnableSmartScreen is incorrectly not applying due to a licensing rejection under Windows 11 Business

### ISSUE THREAD

**Issue by pcamh** [MicrosoftDocs/windows-itpro-docs#10831]
ADMX_WindowsExplorer/EnableSmartScreen is incorrectly not applying due to a licensing rejection under Windows 11 Business:

MDM PolicyManager: Policy is rejected by licensing, Policy: (EnableSmartScreen), Area: (ADMX_WindowsExplorer), Result:(0x82B00006) Unknown Win32 Error code: 0x82b00006.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe02a28-215f-f176-6086-8e79fcb48471
* Version Independent ID: f9143995-669d-be4d-3632-be2d0517d452
* Content: [Policy CSP - ADMX_WindowsExplorer - Windows Client Management](https://docs.microsoft.com/en-gb/windows/client-management/mdm/policy-csp-admx-windowsexplorer?WT.mc_id=Portal-fx#admx-windowsexplorer-enablesmartscreen)
* Content Source: [windows/client-management/mdm/policy-csp-admx-windowsexplorer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-admx-windowsexplorer.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
Hey @pcamh, we're in the process of updating the CSP docs using a new format which will make this issue obsolete as the new format doesn't include Business applicability. As we continue, we'll work further on including the Business edition applicability appropriately for all CSPs, so I'm closing this issue for the time being.
