### ISSUE TITLE
Please remove reference to IT as a service as Autopatch doesn't provide this even though it can assist. Thanks.

### ISSUE THREAD

**Issue by StephendillonMS** [MicrosoftDocs/windows-itpro-docs#10840]
[Enter feedback here]
Please remove reference to IT as a service as Autopatch doesn't provide this even though it can assist. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cb51c14-5d12-80e0-1c6a-0e02760ef6a3
* Version Independent ID: 3cb51c14-5d12-80e0-1c6a-0e02760ef6a3
* Content: [Privacy - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopatch/references/windows-autopatch-privacy)
* Content Source: [windows/deployment/windows-autopatch/references/windows-autopatch-privacy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopatch/references/windows-autopatch-privacy.md)
* Product: **w11**
* Technology: **windows**
* GitHub Login: @tiaraquan
* Microsoft Alias: **tiaraquan**

**Comment by tiaraquan** [comment]
@StephendillonMS 

Thank you for your feedback. I conferred with the team and we've updated the article accordingly.
