### ISSUE TITLE
A problem with apps sector on 'Set up School PC's' app

### ISSUE THREAD

**Issue by CybernetIL** [MicrosoftDocs/windows-itpro-docs#10849]
Hello,
i recently tried to work with this app but something really weird happened.
When i add my (Global admin) account information,
the 'add apps' sector is just dissapearing.
note that in microsoft education store my account is set as an global admin.
what should i do? the all reason was to set up all the computers with microsoft applications at a glance.
Thank you!

**Comment by aczechowski** [comment]
Thanks @CybernetIL for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
