### ISSUE TITLE
Connectivity/HardenedUNCPaths's documentation not clear

### ISSUE THREAD

**Issue by laurentdelosieresfactorial** [MicrosoftDocs/windows-itpro-docs#10842]
Hello Team,

The [documentation of the "Connectivity/HardenedUNCPaths"](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-connectivity#connectivity-hardeneduncpaths) is not clear to us. It is specified that:

`If you enable this policy, Windows only allows access to the specified UNC paths after fulfilling other security requirements.`

What do they mean by "other security requirements" ? Additionally, providing an example (OMA-URI + value) would be great.

Best,
L.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e70a68f-210c-b27a-3224-2cfd80028e60
* Version Independent ID: c6a94ff0-9ab2-cd09-c053-e09304d0d16a
* Content: [Policy CSP - Connectivity - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-connectivity#connectivity-hardeneduncpaths)
* Content Source: [windows/client-management/mdm/policy-csp-connectivity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-connectivity.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
Thanks @laurentdelosieresfactorial for the feedback. We're automating the CSP docs, which would list the OMA-URI for each policy. I've also updated this policy to include a link to https://support.microsoft.com/en-us/topic/ms15-011-vulnerability-in-group-policy-could-allow-remote-code-execution-february-10-2015-91b4bda2-945d-455b-ebbb-01d1ec191328 which talks about the additional requirements. These changes would be live later this month, so I'm closing this issue now.
