### ISSUE TITLE
Define/link to acronyms/components in use for the first time: WAP, MMS, NabSync

### ISSUE THREAD

**Issue by jerryabo** [MicrosoftDocs/windows-itpro-docs#10848]
"WAP messages received by the device to internal OS components that process them further: MMS, NabSync, SI/SL. This service doesn't send telemetry."

What's a WAP message? This is an acronym that appears to be undefined. Same for MMS, NabSync.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19461768-ab73-b97c-f754-24e5c75e261f
* Version Independent ID: 58c7b616-f5c7-c503-a689-4fadde8ee061
* Content: [What's new in MDM enrollment and management - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/new-in-windows-mdm-enrollment-management#what-is-dmwappushsvc)
* Content Source: [windows/client-management/mdm/new-in-windows-mdm-enrollment-management.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/new-in-windows-mdm-enrollment-management.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
@jerryabo I've updated the docs, which should be live later today.
