### ISSUE TITLE
provision package individual windows 11 home?

### ISSUE THREAD

**Issue by aguthrie19** [MicrosoftDocs/windows-itpro-docs#10859]
Awesome info! Simple question (for maintainers @lizgt2000, @aczechowski?): does this work for an individual using windows 11 home edition?

I like to reset my home computer once a quarter or so to keep my development environments from conflicting. I don't want my old user or system environment, but I do want some apps to stick around. I've used imaging, but I want a bit more control over my system reinstalls. According to the docs package provisioning does exactly what I want:
> Quickly configure a new device without going through the process of installing a new image.

The scope of this configure process seems appropriate for an individual doing routine resets too:
> It is best suited for small- to medium-sized businesses with deployments that range from tens to a few hundred computers.

I've installed the windows configuration designer as admin, created a simple desktop .ppkg that included removing pre-installed software and installing firefox nightly, and began to apply the package via usb drive during initial setup, HOWEVER it fails with 4 errors:
* Set or change network connectivity settings - ...
* Cause the device to reboot - failed
* Reset system and remove pre-installed software - failed
* Run Scripts (0) - ...

Am I missing something important? Is there an easier or more canonical Microsoft tool to accomplish these customized quarterly resets?

Thanks!
Alec
-p.s. an hour of customer service only got me so far
 ¯\_༼ ಥ ‿ ಥ ༽_/¯
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc6a7f82-c972-6aea-f045-08fb57a99ae6
* Version Independent ID: 384fe96b-ace9-3e34-e5e9-24bb7409e0e8
* Content: [Provisioning packages overview on Windows 10/11 - Configure Windows](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-packages)
* Content Source: [windows/configuration/provisioning-packages/provisioning-packages.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/provisioning-packages/provisioning-packages.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lizgt2000
* Microsoft Alias: **lizlong**

**Comment by aczechowski** [comment]
Thanks @aguthrie19 for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
