### ISSUE TITLE
https://docs.microsoft.com/en-us/education/windows/windows-11-se-overview#add-your-own-apps

### ISSUE THREAD

**Issue by tuckstarrydell** [MicrosoftDocs/windows-itpro-docs#10851]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2ca5807-f011-cdd1-eb80-c74655aa4738
* Version Independent ID: fe016307-69a4-ec63-4979-eac841d13c3c
* Content: [Use Set up School PCs app](https://docs.microsoft.com/en-us/education/windows/use-set-up-school-pcs-app#settings)
* Content Source: [education/windows/use-set-up-school-pcs-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/education/windows/use-set-up-school-pcs-app.md)
* Product: **windows**
* Technology: **windows**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by tuckstarrydell** [comment]
#10850

**Comment by paolomatarazzo** [comment]
addressed as part of 10850
