### ISSUE TITLE
References to 1903 and earlier

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/windows-itpro-docs#10856]
Windows 10 1903 went out of support in Dec 2020 and all versions before it are also EoS. Is it really necessary to keep calling out that 1903 or newer is required for certain functionality, and even have examples for how to configure WDAC prior to 1903?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44b2ee4a-d0c3-3812-68c9-22f948ac0434
* Version Independent ID: 44b2ee4a-d0c3-3812-68c9-22f948ac0434
* Content: [Deploy WDAC policies using Mobile Device Management (MDM) (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/deployment/deploy-windows-defender-application-control-policies-using-intune)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/deployment/deploy-windows-defender-application-control-policies-using-intune.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/deployment/deploy-windows-defender-application-control-policies-using-intune.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@aczechowski Thank you very much for sharing this explanation. @GenerAhl Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
