### ISSUE TITLE
Approved Version does NOT exist

### ISSUE THREAD

**Issue by djmahoney99** [MicrosoftDocs/windows-itpro-docs#10850]
LightSpeed System is NOT even up to version 2.6.2!   Their latest version is 2.2.3.  What was the approved version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d112f8-f653-f5f5-0fb5-7cd936865b3e
* Version Independent ID: 76d112f8-f653-f5f5-0fb5-7cd936865b3e
* Content: [What is Windows 11 SE](https://docs.microsoft.com/en-us/education/windows/windows-11-se-overview)
* Content Source: [education/windows/windows-11-se-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/education/windows/windows-11-se-overview.md)
* Product: **windows**
* Technology: **windows**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Thank you for the feedback @djmahoney99, I made the change, and it will be reflected soon.
