### ISSUE TITLE
How can i uninstall it?

### ISSUE THREAD

**Issue by frontendmonster** [MicrosoftDocs/windows-itpro-docs#1086]
How can I uninstall this app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f27b2-fc93-e90d-be8c-cb749b6dbcb2
* Version Independent ID: 8633dd0d-8ba8-8aba-a474-84dcf01e678f
* Content: [The Windows Defender Security Center  app](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-security-center/windows-defender-security-center)
* Content Source: [windows/security/threat-protection/windows-defender-security-center/windows-defender-security-center.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-security-center/windows-defender-security-center.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by andreabichsel** [comment]
Hi frontendmonster, you can't uninstall the Windows Defender Security Center app, but you can do one of the following:

Disable the interface on Windows Server 2016.
Hide all of the sections on client computers.
Disable Windows Defender Antivirus, if needed.

This article contains links on how to do all of the above.

Thank you!
Andrea
