### ISSUE TITLE
Traduction

### ISSUE THREAD

**Issue by lby912** [MicrosoftDocs/windows-itpro-docs#10861]
Bonjour,

Il y a un problème de traduction sur la note de mise en garde sur les attaque physique.
La phare suivante serait beaucoup plus compréhensible :
Cela ne protège pas contre les attaques physiques où un attaquant ouvre le boîtier et attaque le matériel.
au lieu de :
Cela ne protège pas contre les attaques physiques lorsqu’un attaquant ouvre le cas et attaque le matériel.

Cordialement,

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des défis GitHub.*

* ID: 02f6385e-7cdb-ee78-abe7-ba0056579dc7
* Version Independent ID: 89d2eb67-7778-4e81-4292-f4ce5acfe774
* Content: [Contre-mesures BitLocker (Windows 10) - Windows security](https://docs.microsoft.com/fr-fr/windows/security/information-protection/bitlocker/bitlocker-countermeasures)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-countermeasures.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/main/windows/security/information-protection/bitlocker/bitlocker-countermeasures.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment]
Thank you @lby912 for sharing this feedback, and my apologies for responding in English. I've filed a translation bug with our global team (229139), who will address the issue.
