### ISSUE TITLE
typo mistake

### ISSUE THREAD

**Issue by sadfriend** [MicrosoftDocs/windows-itpro-docs#10860]
[Enter feedback here]
there is a typo mistake this document: https://docs.microsoft.com/en-us/windows/security/information-protection/encrypted-hard-drive
`In the event that the DEK needs to be changed or erased, the data on the drive doesn't need to be re-encrypted. A new Authentication Key needs to be created and it will re-encrypt the DEK. Once completed, the DEK can now be unlocked using the new AK and read-writes to the volume can continue.`

I think *_DEK_* in first line should be *_AK_*
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13a08c67-da5c-eef5-2ef8-a0613cb3a862
* Version Independent ID: 187b47b0-d2fb-a5b5-c28c-14a850e69416
* Content: [Encrypted Hard Drive (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/information-protection/encrypted-hard-drive)
* Content Source: [windows/security/information-protection/encrypted-hard-drive.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/encrypted-hard-drive.md)
* Product: **m365-security**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@sadfriend Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10987

Once the author approves, the changes will be live.

Thanks
Sri
