### ISSUE TITLE
Missing ">" (Greater than sign) at the end of the XML code

### ISSUE THREAD

**Issue by gharatm** [MicrosoftDocs/windows-itpro-docs#10866]
Dism default association export command example is missing the **">"** (Greater than sign) at the end of the XML code and hence the Base64 encoded result syntax provided on this page is also incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0080ea96-3ae5-49ee-d621-eb8ffbd14a4f
* Version Independent ID: d17b7412-6993-4347-174c-9f20d045af00
* Content: [Policy CSP - ApplicationDefaults - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-applicationdefaults#applicationdefaults-defaultassociationsconfiguration)
* Content Source: [windows/client-management/mdm/policy-csp-applicationdefaults.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-applicationdefaults.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by RAJU2529** [comment]
@gharatm < thanks for point out
