### ISSUE TITLE
There is a typo in update-terminology.png.

### ISSUE THREAD

**Issue by bemaru** [MicrosoftDocs/windows-itpro-docs#10875]
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/images/update-terminology.png

orchestator -> orchestrator
It needs to be corrected in this way.

I found it on the page below.
https://learn.microsoft.com/en-us/windows/deployment/update/windows-update-overview?source=docs

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fcc8a7ec-75d7-894c-9499-cbb4c3807ea7
* Version Independent ID: a4c97095-7c09-1bff-690d-90c8cdeee6c2
* Content: [Get started with Windows Update - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/windows-update-overview?source=docs)
* Content Source: [windows/deployment/update/windows-update-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-overview.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by msbemba** [comment]
@bemaru Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10989

Once the author approves, the changes will be live.

Thanks
Sri
