### ISSUE TITLE
Building MDM for Windows Devices

### ISSUE THREAD

**Issue by Peter-TG** [MicrosoftDocs/windows-itpro-docs#1087]
When building MDM solutions for Windows devices, it is possible CSP or PowerShell?

Thanks!

Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162c8434-b3ab-e235-43ce-ed435d6cd06e
* Version Independent ID: 18b29b82-f1ad-81b8-2ea4-f7bebc506487
* Content: [Configuration service provider reference](https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference)
* Content Source: [windows/client-management/mdm/configuration-service-provider-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/configuration-service-provider-reference.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @Peter-TG ,
for MDM, deployment is usually made via CSP. If you need to run PowerShell Script you need Microsoft Intune Management Extension to be installed
Thank you

**Comment by mypil** [comment]
@Peter-TG - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
