### ISSUE TITLE
Script

### ISSUE THREAD

**Issue by felizondojr** [MicrosoftDocs/windows-itpro-docs#10872]
Discussed with Ranjith Vantakala and appears the script isn't necessary if using Intune because the config profile does the same, but this page still suggests that the script is required with MEM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f8d7dde-9471-7db2-e188-6d40fe66e5ce
* Version Independent ID: 8f8d7dde-9471-7db2-e188-6d40fe66e5ce
* Content: [Configuring Microsoft Endpoint Manager devices for Update Compliance (preview) - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/update-compliance-v2-configuration-mem?source=docs)
* Content Source: [windows/deployment/update/update-compliance-v2-configuration-mem.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-v2-configuration-mem.md)
* Product: **w10**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@felizondojr  Hey Fernando, Yikes. Oh yeah. That should definitely be do either a config profile OR script. The V1 article needs to change as well since this article is basically a copy/paste of the previous version. Thanks for noticing and reporting this. I'll get it fixed up shortly.

**Comment by mestew** [comment]
Poked at this a bit. Updated both v1 & v2 docs to make it clear that the script is optional but useful for troubleshooting due to the logs it generates. The bit about it being optional was buried in the script section.  Suspect the article should be updated within the next day or so.
