### ISSUE TITLE
[FIPS 140-2] validated certs have expired

### ISSUE THREAD

**Issue by garttyman** [MicrosoftDocs/windows-itpro-docs#10885]
What certs is Microsoft using to be compliant with the Federal FIPS requirements.  In addition, I see no Windows Server 2022 as well. 
for example: 
https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3197 

I see several modules in process and review can the publics get a preview of what is being tested:
https://csrc.nist.gov/Projects/cryptographic-module-validation-program/modules-in-process/Modules-In-Process-List

Any guidance would be helpful. or an update to this page.

(admin edit: update doc details with the latest)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e93f07bf-c0dd-dd83-d7bf-8562e7f197c3
* Version Independent ID: a6c44187-8ff1-6519-5291-146b4c1bf46c
* Content: [Federal Information Processing Standard (FIPS) 140 Validation](https://learn.microsoft.com/en-us/windows/security/threat-protection/fips-140-validation)
* Content Source: [windows/security/threat-protection/fips-140-validation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/fips-140-validation.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @garttyman and thank you for the feedback. We're in the process of restructuring the FIPS documentation and we'll take into consideration your feedback. However, note that the current documentation is up to date. Once new certifications are released, the page will be updated accordingly.
