### ISSUE TITLE
Bonjour

### ISSUE THREAD

**Issue by DRUON** [MicrosoftDocs/windows-itpro-docs#10889]
[Tapez vos commentaires ici]

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour learn.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 6e8740b8-c1f2-4b88-3d4d-66cdbf20215f
* Version Independent ID: 7986a684-b35d-06bd-be30-dfca9923cb9c
* Content: [Règles de bloc de pilotes recommandées par Microsoft (Windows) - Windows security](https://learn.microsoft.com/fr-fr/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/main/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules.md)
* Product: **m365-security**
* GitHub Login: @jgeurten
* Microsoft Alias: **dansimp**

**Comment by jgeurten** [comment]
There is no content/il n'y a aucun commentaires.
