### ISSUE TITLE
Configure a kiosk using a provisioning package

### ISSUE THREAD

**Issue by berchouinard** [MicrosoftDocs/windows-itpro-docs#1088]
In the Config for Group account the following does not work

<Config> 
  <UserGroup Type="LocalGroup" Name="mygroup" /> 
  <DefaultProfile Id="{9A2A490F-10F6-4764-974A-43B19E722C23}"/> 
</Config>

No matter if it is an existing local group or new one when running a provisioning package there is an error.
The error in the event log is 0xc00CE014 which according to https://msdn.microsoft.com/en-us/library/ms756003(v=vs.85).aspx is 'Element content is invalid according to the DTD or schema.'

Version of Windows 10 is 1709

**Comment by jdeckerms** [comment]
@berchouinard The feature to use group accounts for kiosk configuration was added in Windows 10, version 1803.
