### ISSUE TITLE
Why does this menu exist?

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/windows-itpro-docs#1089]
It seems like the purpose of this menu (to turn on MDM for certain groups) is redundant, considering the menu where you actually assign policies based on groups. It's like having two on-switches on the same control. Am I missing something here?

EDIT: Okay, I think I might have figured it out. The menu exists as a gateway for all MDM vendors, not just Intune. So this has to exist in order to allow other MDM vendors to be managed alongside Intune. This makes sense now. 

Second question: What happens when a user does not have any policies applied in Intune, but is enabled for MDM? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b95868d3-c141-0038-69b2-7a6a84d817d8
* Version Independent ID: b68e29a4-fe87-3c20-4abc-06ab815f33ee
* Content: [Azure AD and Microsoft Intune - Automatic MDM enrollment in the new Portal](https://docs.microsoft.com/en-us/windows/client-management/mdm/azure-ad-and-microsoft-intune-automatic-mdm-enrollment-in-the-new-portal)
* Content Source: [windows/client-management/mdm/azure-ad-and-microsoft-intune-automatic-mdm-enrollment-in-the-new-portal.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/azure-ad-and-microsoft-intune-automatic-mdm-enrollment-in-the-new-portal.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @thedrum808 ,
**What happens when a user does not have any policies applied in Intune, but is enabled for MDM?** - MDM and Intune are different products, there is no need to deploy Intune if you need to use MDM functionality. You should use CSP ([Configuration service provider reference](https://docs.microsoft.com/windows/client-management/mdm/configuration-service-provider-reference)) to configure settings on the device.

Thank you

**Comment by mypil** [comment]
@thedrum808 - From our understanding, the issue you raised has been MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
