### ISSUE TITLE
Wrong supported values for Search/AllowSearchHighlights

### ISSUE THREAD

**Issue by taikuli** [MicrosoftDocs/windows-itpro-docs#10891]
Regarding Search/AllowSearchHighlights the document mentions enabled / disabled as supported values.
However, using disabled or enabled results in an error.
Only using 1 for enabled and 0 for disabled produces the desired result.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12404d25-d284-8578-6eb5-4cf3b2373781
* Version Independent ID: a6ff7cf5-1884-afe4-7415-8544de981fed
* Content: [Policy CSP - Search - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-search)
* Content Source: [windows/client-management/mdm/policy-csp-search.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-search.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
@taikuli Thanks for reporting this. Changes should be live later today.
