### ISSUE TITLE
Inconsistent information regarding updating WinRE image

### ISSUE THREAD

**Issue by WebTiger89** [MicrosoftDocs/windows-itpro-docs#10892]
Hi,
I might have found some inconsistent information. In chapter _Update WinRE_ in the comments of the script is stated:

> Note: If you are using a combined cumulative update, there may be a prerequisite servicing stack update required
This is where you'd add the prerequisite SSU, before applying the latest combined cumulative update.

While the comment implies it is necessary to add SSU + CU the script only adds SSU actually. 

Could you please have a look and maybe update the docs. Also could you tell what is the correct approach? SSU + CU or only SSU?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7734ca5-0770-5bbd-7da5-dda4c1cf5ae0
* Version Independent ID: cb98ef23-d0c6-e62e-b72b-9b5f5d724e8e
* Content: [Update Windows installation media with Dynamic Update - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/media-dynamic-update#feedback)
* Content Source: [windows/deployment/update/media-dynamic-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/media-dynamic-update.md)
* Product: **w10**
* GitHub Login: @SteveDiAcetis
* Microsoft Alias: **aaroncz**

**Comment by SteveDiAcetis** [comment]
I'll try to explain, glad to discuss via a Teams call if needed as I believe you are a MS employee. 

The general pattern, shown in the table of steps, is SSU first, other steps, then finish with Safe OS update. However, for some RTM builds, we stopped publishing to Catalog the SSU and Cumulative Update as _separate_ updates. Instead, it is a combined cumulative update. So, in this case, depending on the specific image you are updating, you won't have a standalone SSU to install. Instead, we are advising to use the combined cumulative update for this step instead. This is covered in a note early in the article after the steps table. Consumers of the script will need to take this into consideration and adjust the code accordingly. 

Further, if there is a breaking change, and the combined cumulative update can't be installed without installing the SSU, then the SSU would have to come first. This should be a rare breaking change and would be known in the KB article for the combined cumulative update.

**Comment by SteveDiAcetis** [comment]
Actually, I thought the comment was from aaroncz, but I believe it is from WebTiger89. Anyways, glad to discuss via Teams either way, if talking may help to clarify. - Steve

**Comment by WebTiger89** [comment]
Thanks for your explanation Steve. 

> Actually, I thought the comment was from aaroncz, but I believe it is from WebTiger89. Anyways, glad to discuss via Teams either way, if talking may help to clarify. - Steve

The comment is taken from the powershell script shown on the docs page under the chapter _Update WinRE_. 

> The general pattern, shown in the table of steps, is SSU first, other steps, then finish with Safe OS update. However, for some RTM builds, we stopped publishing to Catalog the SSU and Cumulative Update as separate updates. Instead, it is a combined cumulative update. So, in this case, depending on the specific image you are updating, you won't have a standalone SSU to install.

Actually I understand the process but isn't there a difference if you apply only the SSU vs. the combined cumulative update? I mean in the latter case you also apply the whole CU to the image. Wouldn't it be better to adjust the docs page with an advise to extract the SSU from the combined CU and apply it instead of applying the whole combined CU?

Currently you say: Applying SSU vs. combined CU (SSU +CU) is the same but I doubt, because the latter operation does a lot of more work not?

**Comment by WebTiger89** [comment]
I mean this comment states exactly that one should apply SSU and then the combined one, i.e. CU:

> This is where you'd add the prerequisite SSU, before applying the latest combined cumulative update. 

I can imagine that this comment was copy/pasted from the powrrshell example for **WinPE**, where - according to the table - the SSU + CU has to be applied.

**Comment by WebTiger89** [comment]
Thanks for the insights Steven. I guess I could follow.
I think for someone who does not has those informations it is hard to grasp what is meant with the comment.

It would be more obvious if the code of the script would reflect what is stated in the comment:

Currently:
`Add-WindowsPackage -Path $WINPE_MOUNT -PackagePath $SSU_PATH | Out-Null`

While this operation reflects the "This is where you'd add the prerequisite SSU, ..." part of the comment the "before applying the latest combined cumulative update." part is not reflected.

You might want to add something like this with a comment:

```
# Add latest cumulative update if you are using a combined cumulative update
Write-Output "$(Get-TS): Adding package $LCU_PATH"
Add-WindowsPackage -Path $MAIN_OS_MOUNT -PackagePath $LCU_PATH -ErrorAction stop | Out-Null
```

This makes it clear, even for those who are not familiar with the insights.

**Comment by SteveDiAcetis** [comment]
OK - I will propose some changes. I don't believe I can edit this section of the docs, so I need to work through one of our writers. Then, hopefully through the writer can include you on a review, and we can tweak as needed. Hopefully won't take too long.

**Comment by WebTiger89** [comment]
Thanks Steve, much appreciated <3

**Comment by SteveDiAcetis** [comment]
Hi WebTiger89. There is a new version of the page live today. The internal process didn't allow me to add externals to the review. However, glad for you to take a look to see if this update provides more clarity. Most of the changes were in the comments, explaining the options depending on the OS release one was using. If you have any suggested changes, I'll review and can make revisions as needed.
