### ISSUE TITLE
[Windows Defender Credential Guard] How to disable it?

### ISSUE THREAD

**Issue by eldrift** [MicrosoftDocs/windows-itpro-docs#10895]
[Enter feedback here]

Versjon	Windows 11 Pro
Versjon	22H2
Installert den	‎23.‎09.‎2022
Operativsystembygg	22621.521
Opplevelse	Windows Feature Experience Pack 1000.22634.1000.0

I need to disable Windows Defender Credentional Guard, but the was no information here for my configuration how to disable it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows) - Windows security](https://learn.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **m365-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @eldrift and thank you for your feedback.
There is a section in this article that describes how to disable Credential Guard. Can you please clarify?
windows/security/identity-protection/credential-guard/credential-guard-manage#disable-windows-defender-credential-guard

**Comment by jirenugo** [comment]
Do you have `IsolatedCredentialsRootSecret` under `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0`

**Comment by extesy** [comment]
Yes, a binary value with `NtlmRootSecret` in the middle of it. Is this how Credential Guard detects Enterprise edition of Windows?

**Comment by jirenugo** [comment]
That means that you had credential guard running at some point before because your device was an enterprise device. We will be updating the documentation to reflect this.

**Comment by jirenugo** [comment]
Was it AAD joined at any point?

**Comment by extesy** [comment]
No, it wasn't. I explicitly keep my home PC separate from my work stuff. Never joined any domains, never installed any corporate software. I think there should be more reliable ways of detecting Enterprise edition (like by actually checking the license key) before enabling Credential Guard.

**Comment by jirenugo** [comment]
It says `LsaCfg` as opposed to `LsaCfgFlags`. You also need a reboot after setting it to 0.
