### ISSUE TITLE
Doesn't mention Feature Updates in some portions

### ISSUE THREAD

**Issue by StephendillonMS** [MicrosoftDocs/windows-itpro-docs#10898]
At this point it explains what QUs do but not FUs: "What does Windows Autopatch do to ensure updates are done successfully?" 
https://learn.microsoft.com/en-us/windows/deployment/windows-autopatch/overview/windows-autopatch-faq#what-does-windows-autopatch-do-to-ensure-updates-are-done-successfully

**Comment by tiaraquan** [comment]
Content has been updated to include feature updates. Thank you for informing us about this gap!
https://learn.microsoft.com/en-us/windows/deployment/windows-autopatch/overview/windows-autopatch-faq#what-does-windows-autopatch-do-to-ensure-updates-are-done-successfully
