### ISSUE TITLE
翻譯錯誤

### ISSUE THREAD

**Issue by AlexHuang-TERAOKA** [MicrosoftDocs/windows-itpro-docs#10901]
英文：However, note that even though local passwords are also local to the device, they are still less secure than a PIN, as described in the next section.
錯誤翻譯：不過，請注意，即使本機密碼也是裝置的本機密碼，它們仍然比 PIN 更安全，如下一節所述。
建議修正：不過，請注意，即使本機密碼侷限於裝置本機，它們仍然比 PIN 更不安全，如下一節所述。

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 learn.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: c34dbafa-df3c-a5a5-32d5-2ce152893534
* Version Independent ID: cebdd9a6-45d7-6306-373c-7d31121f9e16
* Content: [為什麼 PIN 優於 Windows)  (線上密碼 - Windows security](https://learn.microsoft.com/zh-tw/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/main/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md)
* Product: **m365-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @AlexHuang-TERAOKA and thank you for your contribution. Could you please describe the issue in English, as I have difficulties understanding it when using a translator. Thank you!

**Comment by AlexHuang-TERAOKA** [comment]
Sorry it's my first time to report via github.

Original English：However, note that even though local passwords are also local to the device, they are still less secure than a PIN, as described in the next section.
Wrong translation：不過，請注意，即使本機密碼也是裝置的本機密碼，它們仍然比 PIN 更安全，如下一節所述。("比 PIN 更安全" means "more secure than a PIN")
Suggestion：不過，請注意，即使本機密碼侷限於裝置本機，它們仍然比 PIN 更不安全，如下一節所述。("比 PIN 更不安全" means "less secure thaan a PIN")

**Comment by paolomatarazzo** [comment]
Thank you @AlexHuang-TERAOKA, I'm sending this issue to our localization team to review and address bug ID 231574. I'm closing this issue, as the other team will take it from here.
