### ISSUE TITLE
Applies to section doesn't list Server

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/windows-itpro-docs#10905]
Servicing Stack Updates are required for doing updates on recent versions of Windows Server, as well. Either add them to the applies to list or link to an article targeting Server OS.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b706f0af-d504-a8ca-7c38-b8bb9283bfad
* Version Independent ID: 14f31acf-9f47-59a6-269f-62ab249fe560
* Content: [Servicing stack updates - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates)
* Content Source: [windows/deployment/update/servicing-stack-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/servicing-stack-updates.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by msbemba** [comment]
@npherson Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10990

Once the author approves, the changes will be live.

Thanks
Sri
