### ISSUE TITLE
Double negation

### ISSUE THREAD

**Issue by Kuermel** [MicrosoftDocs/windows-itpro-docs#10900]
I assume that there is one "not" too many here. 

> Report all “Subject\Security ID” not equals “LOCAL SERVICE”, which means that the time change was **not made not** by Windows Time service.

> Report all “Process Information\Name” not equals “C:\Windows\System32\svchost.exe” (path to svchost.exe can be different, you can search for “svchost.exe” substring), which means that the time change was **not made not** by Windows Time service.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ef7538d-4d35-7932-cd40-83c525857170
* Version Independent ID: 2ca07b12-f44a-d7cc-ae3b-6bfb2e356f3f
* Content: [4616(S) The system time was changed. (Windows 10) - Windows security](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4616)
* Content Source: [windows/security/threat-protection/auditing/event-4616.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4616.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@Kuermel Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11016

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed
