### ISSUE TITLE
Alternate method

### ISSUE THREAD

**Issue by colemank1** [MicrosoftDocs/windows-itpro-docs#10908]
The article states that the only way to edit the custom support card is to go through the Windows Group Policy Management Editor. This is not the case.
The card can also be configured from Endpoint Manager. 
The path is: Endpoint security>Antivirus>Create Policy>Windows Security Experience>Windows Defender Security Center. From there, the user can set the company name and add contact information to the support button.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e09345e7-0b81-b2f5-410f-54a855adc39d
* Version Independent ID: c57c1b34-3999-54db-bf17-830af9dcf6bb
* Content: [Customize Windows Security contact information - Windows security](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-security-center/wdsc-customize-contact-information)
* Content Source: [windows/security/threat-protection/windows-defender-security-center/wdsc-customize-contact-information.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-security-center/wdsc-customize-contact-information.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by dariomws** [comment]
Hi @colemank1, thank you for your feedback.

I'm adding the following information to the article:

"To enable the customized notifications and add the contact information in Intune, see [Manage device security with endpoint security policies in Microsoft Intune](/mem/intune/protect/endpoint-security-policy) and [Settings for the Windows Security experience profile in Microsoft Intune](/mem/intune/protect/antivirus-security-experience-windows-settings)."

And the sentence "This can only be done in Group Policy" is being moved to the step to enable the contact card.
