### ISSUE TITLE
How to remove UEFI lock regarding HVCI?

### ISSUE THREAD

**Issue by Meld-O-Mat** [MicrosoftDocs/windows-itpro-docs#10912]
This manual lacks information on how to remove the UEFI lock regarding HVCI. As described here, regarding Windows Defender Credential Guard:
https://learn.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#disable-windows-defender-credential-guard

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d4b8d75-5d09-e0d6-1a90-45175fd1043d
* Version Independent ID: dfb10d10-a514-6ea5-1307-df865db530db
* Content: [Enable virtualization-based protection of code integrity - Windows security](https://learn.microsoft.com/en-us/windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity#troubleshooting)
* Content Source: [windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by dariomws** [comment]
Hi @Meld-O-Mat, thank you for your feedback.

In order to disable the feature, you must set the Group Policy to "Disabled" as well as remove the security functionality from each computer, with a physically present user, in order to clear configuration persisted in UEFI.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @Meld-O-Mat Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by taikuli** [comment]
> Hi @Meld-O-Mat, thank you for your feedback.
> 
> In order to disable the feature, you must set the Group Policy to "Disabled" as well as remove the security functionality from each computer, with a physically present user, in order to clear configuration persisted in UEFI.

Do you think you can elaborate a bit more on the steps, the physically present user needs to perform to clear the configuration from UEFI?

**Comment by dariomws** [comment]
Yes, that's what I understand:
https://learn.microsoft.com/windows-hardware/manufacture/desktop/disabling-secure-boot
