### ISSUE TITLE
Incorrect setting names in table of contents

### ISSUE THREAD

**Issue by eppsilon** [MicrosoftDocs/windows-itpro-docs#10910]
These setting names in the table of contents are incorrect:

- SetPolicyDrivenUpdateSourceForDriver
- SetPolicyDrivenUpdateSourceForFeature
- SetPolicyDrivenUpdateSourceForOther
- SetPolicyDrivenUpdateSourceForQuality

They should be:

- SetPolicyDrivenUpdateSourceForDriverUpdates
- SetPolicyDrivenUpdateSourceForFeatureUpdates
- SetPolicyDrivenUpdateSourceForOtherUpdates
- SetPolicyDrivenUpdateSourceForQualityUpdates

The names are correct in the sections that describe each setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91ca58bd-f279-7739-0140-c4bd56784768
* Version Independent ID: 1d2ecc90-58a3-6bcd-84ae-ef04d7a3b7b4
* Content: [Policy CSP - Update - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update#update-deferupdateperiod)
* Content Source: [windows/client-management/mdm/policy-csp-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by RAJU2529** [comment]
@eppsilon < thanks for pointing out, i have added **updates** to this article

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @eppsilon Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
