### ISSUE TITLE
Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

### ISSUE THREAD

**Issue by Lionz01** [MicrosoftDocs/windows-itpro-docs#10915]
Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

View this [failed invocation](https://github.com/google/libphonenumber/pull/2791/checks?check_run_id=7352317573) of the CLA check for more information.

For the most up to date status, view the checks section at the bottom of the pull request.

_Originally posted by @google-cla in https://github.com/google/libphonenumber/pull/2791#issuecomment-1185174859_

**Comment by vinaypamnani-msft** [comment]
@Lionz01 I'm not sure I understand how this issue is related to the windows-itpro-docs repo. Can you explain more?
