### ISSUE TITLE
It is unclear how to turn turn Windows Defender Credential Guard off in Windows 11 latest version, Pro version.

### ISSUE THREAD

**Issue by eldrift** [MicrosoftDocs/windows-itpro-docs#10919]
Hi

It is unclear how to turn turn Windows Defender Credential Guard off in Windows 11 latest version, Pro version.

It is not possible to follow the instruction. I have a non english version of Windows.

Terje

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows) - Windows security](https://learn.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **m365-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by eldrift** [comment]
Example of my problem:

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\WINDOWS\system32> DG_Readiness_Tool_v3.6.ps1 -Disable -AutoReboot
DG_Readiness_Tool_v3.6.ps1 : The term 'DG_Readiness_Tool_v3.6.ps1' is not recognized as the name of a cmdlet, function,
 script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is c
orrect and try again.
At line:1 char:1
+ DG_Readiness_Tool_v3.6.ps1 -Disable -AutoReboot
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (DG_Readiness_Tool_v3.6.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\system32>

**Comment by paolomatarazzo** [comment]
Hello @eldrift , if you keep reading there's an explanation for non-English OS:

When running the HVCI and Windows Defender Credential Guard hardware readiness tool on a non-English operating system, within the script, change *$OSArch = $(gwmi win32_operatingsystem).OSArchitecture to be $OSArch = $((gwmi win32_operatingsystem).OSArchitecture).tolower() instead, in order for the tool to work.

This is a known issue.
