### ISSUE TITLE
[Credential Guard] Pro SKU enablement

### ISSUE THREAD

**Issue by panos415** [MicrosoftDocs/windows-itpro-docs#10914]
This "Credential Guard" isn't activated by default just on Windows 11 Enterprise as you say.  It's activated on Windows 11 Pro as well.  As of yesterday all of sudden I have all these new pop-ups to the dozens of servers I connect to.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows) - Windows security](https://learn.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage?source=docs)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **m365-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @panos415 thank you for your feedback. I am awaiting confirmation from the feature owners on the expected behavior. We will update the documentation once we have more information

**Comment by paolomatarazzo** [comment]
@panos415  did your machine upgraded automatically to Enterprise edition by any chance? That would happen if you have an E3/E5 license, for example

**Comment by panos415** [comment]
I updated two Win11 Pro machines and they're both exhibiting the same behavior regarding the "Credential Guard."  These are both Windows 11 Pro machines with OEM PKs that say "Windows 11 Pro" in the settings (see below).  The personal account that I log in with is tied to my MSDN/VS subscription and a work account that is connected to the system has an E3/E5 license but none of that should be related.I'm attaching two screenshots as well, going from Ari20 to Whitecastle.  I RD to different machines dozens of times each day, with different accounts with saved credentials, and this change is extremely noticeable.  Happens where I'm logging in with my MS account or any domain account.Machine Ari20:Edition	Windows 11 Pro Version	22H2Installed on	‎9/‎30/‎2022OS build	22621.521Experience	Windows Feature Experience Pack 1000.22634.1000.0Machine Whitecastle:Edition	Windows 11 Pro Version	22H2Installed on	‎10/‎1/‎2022OS build	22621.521Experience	Windows Feature Experience Pack 1000.22634.1000.0On Oct 3, 2022, at 3:06 PM, Paolo Matarazzo ***@***.***> ***@***.*** did your machine upgraded automatically to Enterprise edition by any chance? That would happen if you have an E3/E5 license, for example—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
