### ISSUE TITLE
MEM Firewall Rules Configuration

### ISSUE THREAD

**Issue by BiggsSkeedR** [MicrosoftDocs/windows-itpro-docs#10913]
I am trying to replicate our firewall rules from Group Policy into Intune, however, I can't see how to configure firewall rules with the following local ports, as configured in Group Policy;
* RPC Dynamic Ports
* RPC Endpoint Mapper

Would be great to have an update on the page detailing whether these are on the backlog, and if so whether they're coming soon or not.

Also, the Edge Traversal section appears to now be out-dated as this is has a toggle when configuring firewall rules.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b84a77a5-54c7-22c7-b699-c1414c7cd6a1
* Version Independent ID: f78d7bc3-97c8-d8e9-d4f7-5ea82680c738
* Content: [Create Windows Firewall rules in Intune (Windows) - Windows security](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/create-windows-firewall-rules-in-intune)
* Content Source: [windows/security/threat-protection/windows-firewall/create-windows-firewall-rules-in-intune.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/create-windows-firewall-rules-in-intune.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Thank you for the feedback @BiggsSkeedR, we have the firewall rule doc enhancement in our backlog. Closing this request.
