### ISSUE TITLE
DISM API asynchron?

### ISSUE THREAD

**Issue by WebTiger89** [MicrosoftDocs/windows-itpro-docs#10920]
I haven't found any information about this. Does the DISM API support concurrency, i.e. parallel calls to mount images, add packages etc.?
Maybe the documentation page can be updated accordingly.

**Comment by yogkumgit** [comment]
@WebTiger89 Can you please tell us to which article(s) your question applies? This will help us route this issue to the correct writer/team. Thanks

**Comment by WebTiger89** [comment]
https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism/dism-api-reference?view=windows-11

It would be great if this page covers a section about asynchronous capabilities. I have written a powershell script which can mount and install packages to an wim image file in parallel but this works only if both use a different scratch directory. So it seems there is support for parallelization but since there is no documentation about it, it's hard to tell where are the limits etc.

**Comment by yogkumgit** [comment]
@aczechowski Please help us in resolving this issue. Thanks

**Comment by aczechowski** [comment]
That article is outside of the scope of this repository and content team. And unfortunately the windows-hardware repo/content doesn't support public feedback. 

I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for our team at this time.
