### ISSUE TITLE
Device Registration GPO

### ISSUE THREAD

**Issue by tpl2488** [MicrosoftDocs/windows-itpro-docs#10927]
[There is a second GPO setting that should be used for AutoEnrolling into Intune. It should follow (or be included with) step 7 in the section "Verify auto-enrollment requirements and settings".
https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.WorkplaceJoin%3A%3AWJ_AutoJoin
Set that GPO setting to Enable.
]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy?source=docs)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by dariomws** [comment]
Hi @tpl2488, thank you for your feedback.

The verification of the registration of the device to Azure AD is the step 4. I understand that there is no need for that GPO setting.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @tpl2488 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
