### ISSUE TITLE
Bump minimum requirement to Server 2012r2

### ISSUE THREAD

**Issue by pamcdo** [MicrosoftDocs/windows-itpro-docs#10923]
On this page we note the minimum requirement for domain controllers is 2008r2. This is no longer in support and hasn't been for a couple years. Should the minimum DC version be bumped to 2012r2 to reflect the current state of supported deployments?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02eda72c-ccd2-e8d8-4f7e-6edf95b79408
* Version Independent ID: be08aee5-2403-c131-0f39-005e1271d5f1
* Content: [Hybrid Azure AD joined Windows Hello for Business Prerequisites - Windows security](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs.md)
* Product: **m365-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Thank you for your contribution @pamcdo . I updated the documentation and should be live soon.
