### ISSUE TITLE
This article is not completely accurate.

### ISSUE THREAD

**Issue by Hideforpeace** [MicrosoftDocs/windows-itpro-docs#10932]
[Enter feedback here]
I did not see a prompt on step 6 to disable Windows Defender Credential Guard

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows) - Windows security](https://learn.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **m365-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @Hideforpeace thank you for the feedback. Can you please copy/paste the exact sentence you are referring to? I don't see a "step 6"
