### ISSUE TITLE
I have not found the error code

### ISSUE THREAD

**Issue by rabbanisyed** [MicrosoftDocs/windows-itpro-docs#10935]
I was desperately look for all windows update error but found most of them
But missing error code 0x80070020

**Comment by yogkumgit** [comment]
@rabbanisyed Can you please tell us to which article(s) your question applies? This will help us route this issue to the correct writer/team.

**Comment by yogkumgit** [comment]
@rabbanisyed We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
