### ISSUE TITLE
Windows 11 SE Printing Options

### ISSUE THREAD

**Issue by durrante** [MicrosoftDocs/windows-itpro-docs#10936]
Would you be able to define what printing options are available for the Windows 11 SE devices? Namely: 

- Is Universal Print supported?
- Can students add their own printers if located at home?
- Will PaperCut, a common application within Education be added to the supported apps at all?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22dfaafc-76bf-806e-0e5a-2314ae53ba3d
* Version Independent ID: 22dfaafc-76bf-806e-0e5a-2314ae53ba3d
* Content: [Windows 11 SE settings list](https://learn.microsoft.com/en-us/education/windows/windows-11-se-settings-list?source=docs)
* Content Source: [education/windows/windows-11-se-settings-list.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/education/windows/windows-11-se-settings-list.md)
* Product: **windows**
* Technology: **windows**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello Alex (@durrante), thank you for the feedback. I was talking to Anson a few minutes ago about this. We're trying to determine if we should document it here or in the Universal Print documentation. As far as PaperCut support goes, did you submit it as an app to be approved for Windows SE? https://aka.ms/eduapprequest

**Comment by durrante** [comment]
Hi Paolo,

Great, I've spoken to Anson before 😃. Hmmm, I would guess it would be best on the Windows 11 SE page itself and maybe an additional os listed on the Universal Print documentation to state that it also supports Windows 11 SE for completeness.

I guess by your reply that Univeral Print is indeed supported?

My client will soon create a request for the PaperCut app.

Outside of the above two items, is there anyway for users to add their own printers, not sure if drivers can be prestaged via Intune for SEs, I know normal Windows 10/11 allows this.

Thanks,
Alex.



-------- Original message --------
From: Paolo Matarazzo ***@***.***>
Date: 14/10/2022 17:53 (GMT+00:00)
To: MicrosoftDocs/windows-itpro-docs ***@***.***>
Cc: durrante ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/windows-itpro-docs] Windows 11 SE Printing Options (Issue #10936)


Hello Alex ***@***.***<https://github.com/durrante>), thank you for the feedback. I was talking to Anson a few minutes ago about this. We're trying to determine if we should document it here or in the Universal Print documentation. As far as PaperCut support goes, did you submit it as an app to be approved for Windows SE? https://aka.ms/eduapprequest

**Comment by paolomatarazzo** [comment]
If we start documenting what works, it will be a very long task. We tend to call out if something does not work.
Having said that yes, universal print is supported as it's a built in driver. Any driver that you can push via the Intune client (packaged win32) should work as well, but you need to do proper testing. there may be scenario where it doesn't work (e.g. a driver automatically installs a dependency or update that is not tracked by the managed installer). Please note that I'm not support, so you would need to escalate accordingly if something doesn't work as designed.
