### ISSUE TITLE
Different versions of media files prevents Windows setup routine

### ISSUE THREAD

**Issue by WebTiger89** [MicrosoftDocs/windows-itpro-docs#10937]
There seems to be some discrepancy with the "Update Windows installation media" table stating to update "New Media" with Setup Dynamic Update (DU) while actually this does not work because the media files in boot.wim and the main media files differ.

I have observed following while working through the steps stated in the table: 
Step 26: Initially the media files are of version 22621.1. I apply KB5017590 (Setup Dynamic Update) by expanding the cab files and replacing them with the originals. This bumps the version of the files to 22621.605.

Step 15: Next I apply the CU to the Setup image (index 2) of boot.wim. This bumps the media files in \sources\ to 22621.608.

While everything is in place, I create an iso file, boot it up and get following error:

> A media driver your computer needs is missing...

Checking the dism log, points out that the source media path cannot be found:

> Warning    [0x0605b1] IBS    Callback_WinPE_SetSourceMediaInfo:Could not determine the source media path. GLE is [0x0]
Info       [0x0605b3] IBS    Callback_WinPE_SetSourceMediaInfo_Unattend:Show flag for early F6 UI page is being to set to [Show]

Fortunately I found this article which pointed me in the right direction:
https://mskb.pkisolutions.com/kb/4041170

When I do not apply Step 15 (at least for the optional packages WinPE-Setup and WinPE-Setup-Client) and 26 so that both sources of media files are of version 22621.1 it works.

Checking an original iso confirms this. Main media files as well as media files in boot.wim image are in version 22621.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7734ca5-0770-5bbd-7da5-dda4c1cf5ae0
* Version Independent ID: cb98ef23-d0c6-e62e-b72b-9b5f5d724e8e
* Content: [Update Windows installation media with Dynamic Update - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/media-dynamic-update#update-windows-installation-media)
* Content Source: [windows/deployment/update/media-dynamic-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/media-dynamic-update.md)
* Product: **w10**
* GitHub Login: @SteveDiAcetis
* Microsoft Alias: **aaroncz**

**Comment by yogkumgit** [comment]
Thanks @WebTiger89  for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:
- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by WebTiger89** [comment]
I have no problems. I clearly pointed out that the documentation is wrong

**Comment by WebTiger89** [comment]
@yogkumgit It is fine if this is too complex for you but stop closing issues if you have no clue what is going on. Again, the documentation is wrong. And that a original image of windows does not follow the steps stated in the documentation confirms that the documentation is wrong.

**Comment by dariomws** [comment]
@SteveDiAcetis, I cannot confirm this information to update the article and it's the first time we´ve receive this request. Could you help here?

**Comment by SteveDiAcetis** [comment]
@dariomws Sorry for the late reply. Yes, this is indeed an issue. Has to do with how this file is serviced. I'm investigating better solutions, but until then, a workaround is needed. @WebTiger89 thanks for raising this.

**Comment by WebTiger89** [comment]
@SteveDiAcetis Steve, you are my man ;)
Always a pleasure to help

**Comment by SteveDiAcetis** [comment]
The documentation changes are under review, should go live in Jan. In addition, an existing support article is also being extended. This may go live in Jan as well, not sure yet.
