### ISSUE TITLE
Long strings which need to be typed into a GPO only exist as images

### ISSUE THREAD

**Issue by 9072997** [MicrosoftDocs/windows-itpro-docs#10933]
In Appendix C there is a photo containing 6 sets of "program/script" and "arguments" that need to by typed into a GPO. I would really appreciate these being copy-able. It is very easy to mix up the double and triple semi-colons or get one of the numbers wrong.
![image](https://user-images.githubusercontent.com/1310772/195700427-fc37fde9-d1a8-4ed1-bfa2-66adafcf726e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5862cc7-3f36-5f2e-9ade-f7441f99f818
* Version Independent ID: b8bd1985-7b5b-ea79-976a-7d96ad69335c
* Content: [Use Windows Event Forwarding to help with intrusion detection (Windows 10) - Windows security](https://learn.microsoft.com/en-us/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection)
* Content Source: [windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment]
Thanks @9072997 for the feedback, and thanks @dariomws for submitting the edit. The changes to the article will publish ... next week at this point. This issue will auto close when I merge Dario's PR in a bit.
