### ISSUE TITLE
Autopilot article needs an update??

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#1094]
The latest update to Autopilot is Self Deployment. 
There is not enough data on this update, can someone please update this article with the workflow?

I want to know how to assign a Autopilot deployment to a Self deploying Autopilot Hardware device.   This does not involve a user. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40564b31-c91f-2769-e3e0-0b72121a9951
* Version Independent ID: 2ad13ef4-41c5-3ce3-ddaa-827291fcc944
* Content: [Overview of Windows Autopilot](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-10-autopilot)
* Content Source: [windows/deployment/windows-autopilot/windows-10-autopilot.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-10-autopilot.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
Hello @Tdiwestyguy , Thank you for your feedback on the doc. Please note that Autopilot self-deployment is available at https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/self-deploying

Thanks.

**Comment by mypil** [comment]
@Tdiwestyguy -  From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
