### ISSUE TITLE
CMD.exe will run if opened as an administrator

### ISSUE THREAD

**Issue by BagginsLongshot** [MicrosoftDocs/windows-itpro-docs#10947]
The command prompt can be opened if run as an administrator by a user with the appropriate permissions. This is contrary to the documentation that says CMD cannot be run.

**Comment by BagginsLongshot** [comment]
To be clear, this is referring to Windows 11 SE and the Administrative Tools section

**Comment by yogkumgit** [comment]
@BagginsLongshot Can you please tell us to which article(s) your question applies? This will help us route this issue to the correct writer/team. Thanks

**Comment by yogkumgit** [comment]
@BagginsLongshot We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
