### ISSUE TITLE
Is there any way to activate Windows 10/11 from Windows Server 2022 or 2019 with KMS?

### ISSUE THREAD

**Issue by nezaras2000** [MicrosoftDocs/windows-itpro-docs#10948]
After upgrading WS2012R2 to WS2022, I discover that there is noway to activate our clients computers "Windows 10" from that server or any other server has WS2016 or newer version.

Is there any way I can reactivate my client computers after that upgrade?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ccd4e3f-7889-030e-a6cc-717017494739
* Version Independent ID: 0d5f0740-5c65-fbe5-1536-931a11c77600
* Content: [Volume Activation for Windows 10 - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/volume-activation/volume-activation-windows-10)
* Content Source: [windows/deployment/volume-activation/volume-activation-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/volume-activation/volume-activation-windows-10.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by dariomws** [comment]
Hi @nezaras2000, thank you for your feedback.

I think the following link has the information you are looking for:
https://learn.microsoft.com/windows-server/get-started/kms-create-host

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @nezaras2000 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
