### ISSUE TITLE
Audit/DetailedTracking_AuditProcessCreation Not working on latest Win 11 builds

### ISSUE THREAD

**Issue by ErrorRaffyline0** [MicrosoftDocs/windows-itpro-docs#10956]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dabca3f2-2b25-dc4d-9486-57ddfed187f8
* Version Independent ID: 561d395b-ef2d-589f-7bb3-c72e6862ca53
* Content: [Policy CSP - Audit - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-audit)
* Content Source: [windows/client-management/mdm/policy-csp-audit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-audit.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by ErrorRaffyline0** [comment]
For clarity, this issue is the cause of issue #10954 and issue #10955 refers to this issue in particular concerning the omission of documentation about this problem.

**Comment by winhelponline** [comment]
[KB5020044 Fixes Process Creation Audit Logging (Event ID 4688/1108 Issue](https://www.winhelponline.com/blog/kb5020044-process-creation-audit-event-4688-1108/)

The 1108 events should stop after updating to 22621.900. The [4688](https://learn.microsoft.com/en-us/answers/questions/1046836/no-more-events-4688-in-eventlog-anymore.html) (Process creation event) entries appear correctly now.

From [November 29, 2022—KB5020044 (OS Build 22621.900) Preview](https://support.microsoft.com/en-us/topic/november-29-2022-kb5020044-os-build-22621-900-preview-43f0bdf9-0b75-4110-bab3-3bd2433d84b3):

**Improvements**

> "It addresses an issue that affects process creation. It fails to create security audits for it and other related audit events."

**Comment by vinaypamnani-msft** [comment]
Closing this issue, as the problem was addressed.
