### ISSUE TITLE
Already provisioned a user before enabling dual enrollment

### ISSUE THREAD

**Issue by KrypticChewie** [MicrosoftDocs/windows-itpro-docs#10959]
If you have already provisioned a user before enabling dual enrollment what can be done?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f50a8599-301a-5993-1a86-e722f66ffcf2
* Version Independent ID: fffd0fc9-97f6-cfa9-70fb-7f1308804de0
* Content: [Dual Enrollment - Windows security](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-dual-enrollment?source=docs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-feature-dual-enrollment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-feature-dual-enrollment.md)
* Product: **m365-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @KrypticChewie, the enumeration should still happen after the policy is enabled.

**Comment by KrypticChewie** [comment]
Thanks for the info guys.
