### ISSUE TITLE
Extended Stable Channel support

### ISSUE THREAD

**Issue by AshishSukhija1** [MicrosoftDocs/windows-itpro-docs#10957]
For Edge updates via Autopatch, can we manage the customer choice of extended stable channel (8-week instead of 4-week), if so, can we update this DOCS article please ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06d983d1-8644-39b2-c3cf-00c182d65228
* Version Independent ID: 06d983d1-8644-39b2-c3cf-00c182d65228
* Content: [Windows Autopatch - Frequently Asked Questions (FAQ) - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/windows-autopatch/overview/windows-autopatch-faq)
* Content Source: [windows/deployment/windows-autopatch/overview/windows-autopatch-faq.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopatch/overview/windows-autopatch-faq.yml)
* Product: **w11**
* GitHub Login: @tiaraquan
* Microsoft Alias: **tiaraquan**

**Comment by tiaraquan** [comment]
Hi @AshishSukhija1, 

Thank you for reaching out!

At this time, Windows Autopatch only supports the Stable and Beta channel (Test devices) for Microsoft Edge updates.
