### ISSUE TITLE
Change in the details on this page

### ISSUE THREAD

**Issue by AshishSukhija1** [MicrosoftDocs/windows-itpro-docs#10964]
(https://docs.microsoft.com/en-us/windows/deployment/windows-autopatch/overview/windows-autopatch-faq#what-systems-does-windows-autopatch-update)
Microsoft Edge: We need to mention that BETA channel of Edge will be deployed to the TEST ring and updated accordingly. 
This is very important! "Microsoft Edge: Windows Autopatch configures eligible devices to benefit from Microsoft Edge's progressive rollouts on the Stable channel and will provide support for issues with Microsoft Edge updates."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06d983d1-8644-39b2-c3cf-00c182d65228
* Version Independent ID: 06d983d1-8644-39b2-c3cf-00c182d65228
* Content: [Windows Autopatch - Frequently Asked Questions (FAQ) - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/windows-autopatch/overview/windows-autopatch-faq#what-systems-does-windows-autopatch-update)
* Content Source: [windows/deployment/windows-autopatch/overview/windows-autopatch-faq.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopatch/overview/windows-autopatch-faq.yml)
* Product: **w11**
* GitHub Login: @tiaraquan
* Microsoft Alias: **tiaraquan**

**Comment by tiaraquan** [comment]
This is covered in this section https://learn.microsoft.com/en-us/windows/deployment/windows-autopatch/operate/windows-autopatch-edge#update-release-schedule

**Comment by yogkumgit** [comment]
@AshishSukhija1 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
