### ISSUE TITLE
Update Endpoint Manager to Intune

### ISSUE THREAD

**Issue by PiKappZ746** [MicrosoftDocs/windows-itpro-docs#10969]
Endpoint Manager branding should no longer be used.  That should be changed to Intune on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5508bf53-3aa5-7ce1-de3b-7da45b4b495b
* Version Independent ID: 86918067-b0b6-f0f3-a0a8-ece6c8f13c94
* Content: [Add or remove pinned apps on the Start menu in Windows 11 - Configure Windows](https://learn.microsoft.com/en-us/windows/configuration/customize-start-menu-layout-windows-11)
* Content Source: [windows/configuration/customize-start-menu-layout-windows-11.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/customize-start-menu-layout-windows-11.md)
* Product: **w11**
* Technology: **windows**
* GitHub Login: @lizgt2000
* Microsoft Alias: **lizlong**

**Comment by aczechowski** [comment]
Thanks @PiKappZ746 for the feedback! Mandi is working on fixing these terms across the content, and this particular article was revised yesterday.

(Internal reference https://github.com/MicrosoftDocs/windows-docs-pr/pull/7419)
