### ISSUE TITLE
Defender EDR Block Mode

### ISSUE THREAD

**Issue by AdultOnsies** [MicrosoftDocs/windows-itpro-docs#10966]
Looking for a quick answer. 

I've noticed EDR Block mode appears as a toggle on or off for an entire tenant. In my case, I have hundreds of customer subs within my tenant. I need the ability to disable EDR per subscription, not across the entire tenant. 

Is this possible?

**Comment by yogkumgit** [comment]
@AdultOnsies  Considering the nature of the issue, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
