### ISSUE TITLE
Standard hardware security not supported in Windows 11 version22H2 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#10961]
A few users are complaint  regarding showing **Standard hardware security not supported in Windows 11 version22H2**  even though, their computers have high-end windows 11 supported processors, enabled TPM 2.0, booted in secure  mode, enabled UEFI mode, 
Also those users are updated windows and updated bios firmware and updated latest drivers provided by System manufacturers, But still, they are facing issues **Standard hardware security not supported in Windows 11 version 22H2** 

A few users are said its a bug in Windows 11 version 22H2

Here is the question posted the link 
https://answers.microsoft.com/en-us/windows/forum/all/standard-hardware-security-not-supported-till-now/44ebabab-d772-4aa7-b12f-53daa2bdb3f5?page=5

I want to know when this issue will get solved,
Please forward this issue to Windows 11 22h2 development team.

Thanking you.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d4b8d75-5d09-e0d6-1a90-45175fd1043d
* Version Independent ID: dfb10d10-a514-6ea5-1307-df865db530db
* Content: [Enable virtualization-based protection of code integrity - Windows security](https://learn.microsoft.com/en-us/windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity)
* Content Source: [windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by msbemba** [comment]
@RAJU2529 Thank you for your feedback. From the Blog and support documents, we see that the product group is aware of this and an update will be released soon. More information on that will only be available with the support team, so request you contact technical support directly.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @RAJU2529 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
