### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by GitVoch** [MicrosoftDocs/windows-itpro-docs#10963]
In the otherwise v. helpful Help Page at url: https://learn.microsoft.com/en-us/windows/deployment/windows-10-missing-fonts

The text "In Settings, select Time & language, and then select Region & language."
Should read: In Settings, select Time & language, and then select Language & Region."
This is how it appears in the Time & Language Settings Page on Windows 11.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be28a6d0-e0e4-474a-e867-c57586643a4c
* Version Independent ID: 8a91809d-7edb-fbd0-96c3-f8e5487d338e
* Content: [How to install fonts missing after upgrading to Windows client - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/windows-10-missing-fonts)
* Content Source: [windows/deployment/windows-10-missing-fonts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-missing-fonts.md)
* Product: **windows-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @GitVoch Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
