### ISSUE TITLE
Clarification for VPN detection needed

### ISSUE THREAD

**Issue by maxbaldt** [MicrosoftDocs/windows-itpro-docs#10962]
[A connection will be treated as a VPN if the adapter description contains certain keywords, such as "VPN" or "secure."]
Can we please clarify what exactly these keywords are? I read VPN or secure - but is there more to it? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 971ae051-5d39-19d3-072e-fb098c82943b
* Version Independent ID: 971ae051-5d39-19d3-072e-fb098c82943b
* Content: [Delivery Optimization Frequently Asked Questions - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/do/waas-delivery-optimization-faq?source=docs#how-does-delivery-optimization-handle-vpns)
* Content Source: [windows/deployment/do/waas-delivery-optimization-faq.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/do/waas-delivery-optimization-faq.yml)
* Product: **m365-security**
* GitHub Login: @carmenF
* Microsoft Alias: **carmenf**

**Comment by Skorfulose** [comment]
Chiming in, can you please clarify on all keywords? Our Citrix VPN is using network adapter name "Citrix Virtual Adapter", so would it be correctly recognized as a VPN, or not?

**Comment by msbemba** [comment]
@maxbaldt Thank you for your feedback. You are right, the Keywords are only VPN or Secure. 

@Skorfulose  Delivery optimization tries to find out whether a computer is connected via VPN by checking the type of network adapter and whether its description contains certain keywords, such as "VPN" or "secure" and not the name.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @maxbaldt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
