### ISSUE TITLE
NTaphy789

### ISSUE THREAD

**Issue by Masonta1976** [MicrosoftDocs/windows-itpro-docs#10975]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e41c70e9-2889-a930-9f1b-1dfbffe0830f
* Version Independent ID: ae228f28-6128-b670-7aeb-2e8384237dc5
* Content: [Microsoft Defender Application Guard Extension - Windows security](https://learn.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-application-guard/md-app-guard-browser-extension)
* Content Source: [windows/security/threat-protection/microsoft-defender-application-guard/md-app-guard-browser-extension.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-application-guard/md-app-guard-browser-extension.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by msbemba** [comment]
@Masonta1976 Thank you for your feedback. I'm not sure if I understand the feedback here, Are you referring to any policy name?

Thanks
Sri

**Comment by yogkumgit** [comment]
@Masonta1976 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
