### ISSUE TITLE
99,999 minutes divided by 60 is 1,666.65 hours. 1,666.65 divided by 24 is 69.44375 days.

### ISSUE THREAD

**Issue by shutrshock** [MicrosoftDocs/windows-itpro-docs#10974]
[Enter feedback here]
Possible values
A user-defined number of minutes from 0 through 99,999

For this policy setting, a value of 0 means to disconnect an idle session as quickly as is reasonably possible. The maximum value is 99999, which is 208 days. In effect, this value disables the policy.

99,999 minutes divided by 60 is 1,666.65 hours. 1,666.65 divided by 24 is 69.44375 days. The excerpt above states incorrectly that the value 99,999 is 208 days. If fact it only describes the number of 8 hour business days. A more descriptive definition is needed if this is somehow referencing business hours and really reflects 208 business days, or 69 revolutions of the earth on its axis.

thanks, 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2291e02c-6e5b-e9b9-b8d0-1ce2d71ad32d
* Version Independent ID: 0ee07415-d973-44c1-2b7f-f0f36a96276f
* Content: [Microsoft network server Amount of idle time required before suspending session (Windows 10) - Windows security](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/microsoft-network-server-amount-of-idle-time-required-before-suspending-session)
* Content Source: [windows/security/threat-protection/security-policy-settings/microsoft-network-server-amount-of-idle-time-required-before-suspending-session.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/microsoft-network-server-amount-of-idle-time-required-before-suspending-session.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by msbemba** [comment]
@shutrshock Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10993

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @shutrshock Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
