### ISSUE TITLE
MFA requirements - must exclude windows store

### ISSUE THREAD

**Issue by Summit-T** [MicrosoftDocs/windows-itpro-docs#10972]
you need to update this with information about MFA requirements for the Windows Store.

https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-policy-compliant-device

_Subscription activation
Organizations that use the [Subscription Activation](https://learn.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation) feature to enable users to “step-up” from one version of Windows to another, may want to exclude the Universal Store Service APIs and Web Application, AppID 45a330b1-b1ec-4cc1-9161-9f03992aa49f from their device compliance policy._

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6443e532-640d-81c0-8215-b711bd1977d4
* Version Independent ID: fc504984-91d7-b586-04ec-4c751fb48998
* Content: [Windows subscription activation - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **windows-client**
* Technology: **itpro-fundamentals**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by msbemba** [comment]
@Summit-T Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10991

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by frankroj** [comment]
Fixed by https://github.com/MicrosoftDocs/windows-itpro-docs/pull/10991
