### ISSUE TITLE
To be case-sensitive or not?

### ISSUE THREAD

**Issue by eidze1** [MicrosoftDocs/windows-itpro-docs#10978]
"Both checks aren't case-sensitive." So, which one is and which one is not?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b5128d9a-e02a-df9b-24cc-32711ad37b54
* Version Independent ID: fecafb19-6b37-1f2e-ba3d-5e0bf0d49d09
* Content: [Password must meet complexity requirements (Windows 10) - Windows security](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements)
* Content Source: [windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
@eidze1 Not sure I understand the concern here. "Both checks aren't case-sensitive" means neither of the checks are case-sensitive.

**Comment by eidze1** [comment]
So you're saying that 
"Both checks aren't case-sensitive."
means
"Neither of the checks are case-sensitive."

Does it? Say we have two people, one works for MS and the other one does not. We could say that "both persons are not MS employees", couldn't we? How about other quantifiers? We could say "All of [smth] are not part of [smth else]" meaning "not all of them".

You might want to look the grammar up - I'm sure you will find "Both checks aren't case-sensitive." is ambiguous and confusing. In my opinion you should use "neither of... ...is" or better: "Both checks are case-insensitive.".

**Comment by vinaypamnani-msft** [comment]
I've made the statement less confusing, and am closing this issue. The change should be live later today.
