### ISSUE TITLE
In one of the notes on this page, there is a reference made to the 'domain profile' and then a reference for an "Azure Active Directory DC" - which isn't valid.

### ISSUE THREAD

**Issue by hilde-msft** [MicrosoftDocs/windows-itpro-docs#10996]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88e8e24b-481e-babb-a4e7-c5639f2492a2
* Version Independent ID: f61e0165-fd95-0fc4-a52c-0b4c40735ea3
* Content: [Best practices for configuring Windows Defender Firewall - Windows security](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/best-practices-configuring)
* Content Source: [windows/security/threat-protection/windows-firewall/best-practices-configuring.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/best-practices-configuring.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Thank you Michael, I'll fix it.
