### ISSUE TITLE
What is the supported version of Office for VAMT?

### ISSUE THREAD

**Issue by Elangamban** [MicrosoftDocs/windows-itpro-docs#10994]
In the Page its mentioned VAMT will work for supported versions of Windows, Windows server, Office.

But it didn't mentioned what are all the supported versions

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db3d4459-a57d-a227-a9ee-47a9d25fd8e1
* Version Independent ID: 43374c7a-f5d7-8168-6a0d-285f8fb29693
* Content: [VAMT technical reference - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/volume-activation/volume-activation-management-tool)
* Content Source: [windows/deployment/volume-activation/volume-activation-management-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/volume-activation/volume-activation-management-tool.md)
* Product: **windows-client**
* Technology: **itpro-fundamentals**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by msbemba** [comment]
@Elangamban Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11015

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by frankroj** [comment]
Fixed in https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11015
