### ISSUE TITLE
SandboxFolder tag is missing in VSCode.wsb snippet

### ISSUE THREAD

**Issue by sukesh-ak** [MicrosoftDocs/windows-itpro-docs#11000]
[Enter feedback here]
SandboxFolder tag is missing in VSCode.wsb snippet.  

I created a working sample here 
https://github.com/sukesh-ak/Windows-Sandbox-with-VSCODE
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2efc9d32-0f98-0804-78a4-4caccdfac010
* Version Independent ID: 797bb0d3-bade-98f6-fe85-508764571f37
* Content: [Windows Sandbox configuration - Windows security](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by msbemba** [comment]
@sukesh-ak Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11014

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @sukesh-ak Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
