### ISSUE TITLE
Windows-Docs

### ISSUE THREAD

**Issue by AnT1nG82** [MicrosoftDocs/windows-itpro-docs#11008]
[Microsoft](https://github.com/AnT1nG82)(https://g.dev/AnT1nG)
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54254070-539b-6cf2-f988-c80ad685c5fa
* Version Independent ID: 5bbe5140-eee5-abc3-1a26-1c0d13eab358
* Content: [Diagnostic Data Viewer Overview (Windows 10 and Windows 11) - Windows Privacy](https://learn.microsoft.com/en-us/windows/privacy/diagnostic-data-viewer-overview)
* Content Source: [windows/privacy/diagnostic-data-viewer-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/diagnostic-data-viewer-overview.md)
* Product: **windows-client**
* Technology: **itpro-privacy**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by RAJU2529** [comment]
@yogkumgit there is no proper feedback so close this issue #11008

**Comment by yogkumgit** [comment]
@AnT1nG82 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
