### ISSUE TITLE
CI Tools for Windows 10

### ISSUE THREAD

**Issue by davideverall** [MicrosoftDocs/windows-itpro-docs#11019]
Hi

The citool-commands docs page mentions that the "CI Tool is currently included in Windows 11, version 22H2", however there is no mention of Windows 10.

Is the tool supported on Windows 10 and, if so, is there a standalone package for download?

Regards

David

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20079bf8-5e82-f16b-a849-5eb7254f4ce1
* Version Independent ID: 20079bf8-5e82-f16b-a849-5eb7254f4ce1
* Content: [Managing CI Policies and Tokens with CiTool - Windows security](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/operations/citool-commands)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/operations/citool-commands.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/operations/citool-commands.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @valemieux
* Microsoft Alias: **jogeurte**

**Comment by RAJU2529** [comment]
@davideverall , might be supported try unzipping the folder 
[CITools.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/10031291/CITools.zip)

**Comment by davideverall** [comment]
Thanks!

This does seem to work on Windows 10 (tested on 22H2)
