### ISSUE TITLE
Typo in article

### ISSUE THREAD

**Issue by mdoyleeire** [MicrosoftDocs/windows-itpro-docs#11012]
[Enter feedback here]

Typo on template creation step 16,

Article specifies below

certutil -dstemplate \<TemplateName\> \> \<TemplateName\>.txt

this is incorrect as it should be 

certutil -dstemplate <TemplateName> > <TemplateName>.txt

Might save someone the hassle of figuring out why the original commmand doesnt work and doesnt create the txt file

Thanks,
Mark

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e9cc344-d2c1-1f8b-232a-b2cccd8b32a3
* Version Independent ID: eb87d132-cc0b-8ab2-4417-51e1bc719c14
* Content: [Deploying Certificates to Key Trust Users to Enable RDP - Windows security](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by msbemba** [comment]
@mdoyleeire Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11013

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by paolomatarazzo** [comment]
hello @mdoyleeire and thank you for your feedback. The process described in the article is correct and doesn't require any updates. Please verify the steps, you must export the template to a text by specifying a name. If you don't it will export all templates to the text file.
