### ISSUE TITLE
"Applies to" tag should be implemented (consistently) across Security documentation

### ISSUE THREAD

**Issue by ErrorRaffyline0** [MicrosoftDocs/windows-itpro-docs#11027]
Docs such as [copy-a-gpo-to-create-a-new-gpo.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/2ddba849403dbb7929327415e98df35359237973/windows/security/threat-protection/windows-firewall/copy-a-gpo-to-create-a-new-gpo.md) contain a tag that verifies to which Windows versions the feature applies.
![image](https://user-images.githubusercontent.com/48763181/202537181-3f0ac208-4d64-41e3-bda5-c6a9f10b788d.png)

This very useful identifier is missing on many pages where it can be of significant use. Instead, some pages just list the last supported version of a feature in the title and header, which causes confusion due to the feature being supported on many older versions as well.
You can see this in the latest update to the [event-4688.md](https://github.com/msbemba/windows-itpro-docs/blob/patch-13/windows/security/threat-protection/auditing/event-4688.md) documentation in PR #11001, where only "(Windows 10)" is listed in the title and header of the documentation, while in a different section it shows updates to the feature as far back as Vista.
![image](https://user-images.githubusercontent.com/48763181/202538787-53980539-e9c6-4b6d-bc1b-56084a0c1b53.png)
![image](https://user-images.githubusercontent.com/48763181/202541626-3a0d504f-b8c3-4891-940a-4025429a3505.png)

I would also like to point out that some pages lack the checkmark emoji in the "Applies to" section, and also omit the **appliesto** tag and instead just write it down in a list like this.
![image](https://user-images.githubusercontent.com/48763181/202540457-0616f5f5-fab6-494d-8d2b-67eb9bae5743.png)

**Comment by vinaypamnani-msft** [comment]
Appreciate the feedback @ErrorRaffyline0. Some work is already being done on the Applies To tag, so expect to see some improvements gradually.

**Comment by ErrorRaffyline0** [comment]
Are you sure this should be closed? The issue is also regarding replacing certain titles containing version names with appliesto tags in the text.

**Comment by paolomatarazzo** [comment]
@ErrorRaffyline0 there's a broader effort to standardize AppliesTo across all articles in the Windows repo. This will be done in stages and it's already undergoing. I'm closing this to avoid unnecessary tracking. The articles that you read may be already updated or may get updated within the next couple of months.
