### ISSUE TITLE
Server 2022

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#11029]
Is there a reason Server 2022 is not listed? please add it if appropriate

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a149789-67c1-e126-129b-6e77e831086d
* Version Independent ID: dd04d845-c098-46e5-fedf-92ba8fc64615
* Content: [Trusted Platform Module Technology Overview (Windows) - Windows security](https://learn.microsoft.com/en-us/windows/security/information-protection/tpm/trusted-platform-module-overview)
* Content Source: [windows/security/information-protection/tpm/trusted-platform-module-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/tpm/trusted-platform-module-overview.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment]
Thanks @DeanGross for the feedback. You can generally assume that if something applies to Server 2016/2019, it probably also applies to Server 2022. Thanks to @RAJU2529 for checking ([reference](https://learn.microsoft.com/windows-server/get-started/whats-new-in-windows-server-2022)) and making the edit! This issue will automatically close when I merge the pull request, and then the change should publish soon (could be this afternoon, but with the US holidays may not be until next week at this point!)

**Comment by DeanGross** [comment]
Thanks for the update, I have run into a lot of issues over the years when I have made assumptions like that, so I always like to get explicit confirmation
