### ISSUE TITLE
Bad email address

### ISSUE THREAD

**Issue by skenigma** [MicrosoftDocs/windows-itpro-docs#11025]
I tried to send an email to the pwdless@microsoft.com linked in this article.  and got it bounced back.

My MS Advisor was able to send a message to that address from his MS account, with no problem, but not from his External email account.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca080bd-ed37-60a8-ec22-b1929166ff0c
* Version Independent ID: d2742e0c-9d66-4b1f-8555-a1fb1546455b
* Content: [Password-less strategy - Windows security](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/passwordless-strategy)
* Content Source: [windows/security/identity-protection/hello-for-business/passwordless-strategy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/passwordless-strategy.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Thank you for your feedback, @skenigma! I verified, and you are correct. The DL doesn't accept external senders. I'm checking with the DL members and I will update the article accordingly.
In the meantime, is there any feedback you'd like to share?
