### ISSUE TITLE
Document configuration validity check request

### ISSUE THREAD

**Issue by KNCNS** [MicrosoftDocs/windows-itpro-docs#11020]
[Enter feedback here]
Hello,

In this document, it is noted that NLA should be turned on, however, even using AzureAD\username@domain.com (even if its a local  admin on a PC) does not succeed as NLA authentication fails.  The only way to use RDP is to turn off NLA and use AzureAD\username@domain.com on the Desktop login prompt without NLA.  We've tested this with Win 10 Pro 21H2, and the latest Win 11 Pro 22H2...even in Azure IaaS with the AzureAD Extension enabled on a Windows 11 Pro PC.

There are other blogs in WWW that suggest turning NLA off is the only option....is this MS doc valid?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows) - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by yogkumgit** [comment]
@vinaypamnani-msft Please help n resolving this issue. Thanks

**Comment by vinaypamnani-msft** [comment]
Closing this issue as obsolete as I've made a lot of edits to this document recently and this may no longer be relevant. IF you still notice any inaccuracies in the article, please reach out.
