### ISSUE TITLE
Title does not match content

### ISSUE THREAD

**Issue by Sergiortc** [MicrosoftDocs/windows-itpro-docs#11057]
The article has the title "What's new in Windows 10, version 22H2" but has no information on what is new in this version.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26b9d6c3-b5bc-129c-e985-ca03b43b3235
* Version Independent ID: 26b9d6c3-b5bc-129c-e985-ca03b43b3235
* Content: [What's new in Windows 10, version 22H2 for IT pros - What's new in Windows](https://learn.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-22h2)
* Content Source: [windows/whats-new/whats-new-windows-10-version-22H2.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/whats-new-windows-10-version-22H2.md)
* Product: **windows-client**
* Technology: **itpro-fundamentals**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by msbemba** [comment]
@Sergiortc Thank you for your feedback. There are no new features in the Windows 10 version 22H2 release. This update features a scoped set of quality improvements and security updates. This means there are no changes that users will notice on the surface, outside of fixes, and better performance for existing features and capabilities. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Sergiortc Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
