### ISSUE TITLE
Intune scep policy incorrect

### ISSUE THREAD

**Issue by mtengmo** [MicrosoftDocs/windows-itpro-docs#11058]
In the scep profile in Intune, the predefined values for the extended key usages have three options: Any purpose, Client Auth and Secure email. The smartcard option doesn´t exists that the documentation ask for. 

![image](https://user-images.githubusercontent.com/17195619/203721849-61d40fe2-8c72-4736-8937-fc41c46a97a2.png)

GPO: is it possible to enroll with autoenroll through GPOs?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e9cc344-d2c1-1f8b-232a-b2cccd8b32a3
* Version Independent ID: eb87d132-cc0b-8ab2-4417-51e1bc719c14
* Content: [Deploy certificates for remote desktop sign-in](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
@mtengmo thank you for the feedback. I'm updating the article accordingly. You can leave the *predefined value* as *not configured* and fill out the other two fields.
Regarding your questions: yes, you can use autoenroll through GPOs. as a matter of fact, that's how you want to do it at scale :)
