### ISSUE TITLE
Typo Subject Alternative Name SCEP policy Intune

### ISSUE THREAD

**Issue by Riinmo** [MicrosoftDocs/windows-itpro-docs#11053]
There is a typo in the section to create a policy voor the scep certificate for Intune. 
In the Subject Alternative name it should be only the value of the userprincipalname in stead of CN={{UserPrincipalname}}.
The value CN={{Userprincipalname}} is an invalid upn value that is used for authentication. So, it should only be {{UserPrincipalName}}.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e9cc344-d2c1-1f8b-232a-b2cccd8b32a3
* Version Independent ID: eb87d132-cc0b-8ab2-4417-51e1bc719c14
* Content: [Deploy certificates for remote desktop sign-in](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by msbemba** [comment]
@Riinmo Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11055

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by paolomatarazzo** [comment]
Thank you for catching it, @msbemba . The change is approved and merged
