### ISSUE TITLE
[WHFB] Cloud Kerberos trust migration

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/windows-itpro-docs#11064]
Enabled, seems to equal, "Once enabled don't allow it to be turned off ever again". The Remove option becomes greyed out, perhaps this could be documented better?  Is it by design?

For me the only way to then disable it, is to create a Hello for Business - Disabled policy, let it sync, the whole pin option is then Managed by my Org and greyed out, then run a certutil /deletehellocontainer and reboot / logoff.  On signing back in with password PIN is all gone but you now can't turn it back On again...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7739850a-a445-faf1-eec8-8aecb6de8b95
* Version Independent ID: 7739850a-a445-faf1-eec8-8aecb6de8b95
* Content: [Hybrid cloud Kerberos trust deployment (Windows Hello for Business)](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust?tabs=intune)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by AHMEDHAMDOUN01000** [comment]
في الاثنين، ٢٨ نوفمبر ٢٠٢٢, ٢:٣٧ ص mattsmacblog ***@***.***>
كتب:

**Comment by paolomatarazzo** [comment]
Hello @AHMEDHAMDOUN01000 and thank you for the feedback. Let me make sure I fully understand your suggestion.
The steps to migrate should be:

1. Disable the certificate trust policy
2. Enable cloud Kerberos trust via Group Policy or Intune
3. Remove the certificate trust credential using the command certutil -deletehellocontainer from the user context
4. Sign out and sign back in
5. Provision Windows Hello for Business using a method of your choice

Are you saying that you would change this way?

1. Disable the certificate trust policy
2. Enable cloud Kerberos trust policy
3. Wait for the policy to be applied to the devices
4. Remove the certificate trust credential using the command certutil -deletehellocontainer from the user context
5. Sign out and sign back in
6. Provision Windows Hello for Business using a method of your choice

Or this way?

1. Disable the certificate trust policy and let it sync to the devices
2. Remove the certificate trust credential using the command certutil -deletehellocontainer from the user context
3. Enable cloud Kerberos trust via Group Policy or Intune and let it sync
4. Sign out and sign back in
5. Provision Windows Hello for Business using a method of your choice

I believe the original steps are accurate, assuming that you wait for the policies to be refreshed. Did you notice a problem using the original steps?
