### ISSUE TITLE
More roles can be used for read access

### ISSUE THREAD

**Issue by AdmiralTolwyn** [MicrosoftDocs/windows-itpro-docs#11066]
In addition to the Global Reader roles (see docs excerpt below), you can use the following roles:

- Intune Administrator
- Intune Policy and Profile Manager
- Windows Update Deployment Administrator

This is the documentation section I am referring to:

_To display the workbook and view the Windows tab in the Software Updates page [Microsoft 365 admin center](https://admin.microsoft.com/) use the following role:

[Global Reader role](https://learn.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#global-reader)_

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9724d64b-716d-9191-8cb3-021b118b2d37
* Version Independent ID: 9724d64b-716d-9191-8cb3-021b118b2d37
* Content: [Windows Update for Business reports prerequisites - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/wufb-reports-prerequisites)
* Content Source: [windows/deployment/update/wufb-reports-prerequisites.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/wufb-reports-prerequisites.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by AdmiralTolwyn** [comment]
You might also want to mention that Intune Policy and Profile Manager and Windows Update Deployment Administrator roles are much more scoped and would be recommended for accessing the WUfB Reports.

**Comment by msbemba** [comment]
@AdmiralTolwyn Thank you for your feedback. The global reader role gives one access to view the workbook. The other roles mentioned in the document lets the admin view and edit. 

Not sure if we add the other three roles to read-only.

Hope this helps!

Thanks
Sri

**Comment by AdmiralTolwyn** [comment]
Just to clarify my earlier comment: the two roles I mentioned can be used to access (i.e.) read the workbook. Because of their limited nature they might be better suited for some organizations which are hesitant to assign the Global Reader role. This information came straight from the source. I am happy to clarify if you reach out to me directly. On Jan 24, 2023, at 1:53 PM, Sriraman M S ***@***.***> wrote:﻿
@AdmiralTolwyn Thank you for your feedback. The global reader role gives one access to view the workbook. The other roles mentioned in the document lets the admin view and edit.
Not sure if we add the other three roles to read-only.
Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@AdmiralTolwyn Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11302

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by aczechowski** [comment]
@mestew needs to investigate this, and is doing some work in similar content right now

**Comment by yogkumgit** [comment]
closing as per author's comment in PR. Thanks
