### ISSUE TITLE
How to add multiple url's to the blocked list or url exception list

### ISSUE THREAD

**Issue by mythjuha** [MicrosoftDocs/windows-itpro-docs#1106]
(using Windows Configuration Designer)
Adding a "*" to the blocked list, and a single url to the blocked exceptions works like a charm. However, i've been unable to figure out how to add multiple url's to the exception list. Every attempt made the kiosk browser app crash. I've used "," and ";" as seperators. Also tried Json style ["url1","url2"], but no luck.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd2d1007-2cbb-94a6-18aa-a0b879262ab1
* Version Independent ID: 625d9906-0cb0-23eb-3a56-a84ad774d291
* Content: [Guidelines for choosing an app for assigned access (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/guidelines-for-assigned-access-app#guidelines-for-web-browsers)
* Content Source: [windows/configuration/guidelines-for-assigned-access-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/guidelines-for-assigned-access-app.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@mythjuha That's a great question. I'll find out the answer and get back to you, and then also update the topic to help other customers as well.

**Comment by jdeckerms** [comment]
@mythjuha I don't have a final answer yet, but wanted to give you an update. The delimiter should be &amp;#xF000; (for example, www.microsoft.com&amp;#xF000;www.bing.com) but it doesn't seem to work when used in Windows Configuration Designer. The engineering team is still investigating.

I'm glad you brought this up, it's an important problem to solve.

**Comment by DrDrrae** [comment]
I was able to get it to work.

I saved and closed the project in Windows Configuration Designer.
I opened the XML file directly and made the change mentioned by @jdeckerms.
I added `&#xF000;` in between two domains in the BlockedUrlExceptions Key.
![image](https://user-images.githubusercontent.com/672350/41799928-51c44864-7641-11e8-8f28-f87eb048c9af.png)
I then saved the XML file and reopened the project in Windows Configuration Designer.
I then directly exported the provisioning package.
After applying it to the computer, it worked as expected.

When I re-examined the XML file, it was changed to a nonprintable character but it's still working.
![image](https://user-images.githubusercontent.com/672350/41800012-ad7812ee-7641-11e8-88c4-2baf3f1ffdec.png)

You may be able to directly add this non-printable character in the interface but I haven't tested that yet.

**Comment by mythjuha** [comment]
Thanks for the info and workaround. Will try this out as soon as i can get loopback to work (asp.net core API running in a windows service on the same machine).

**Comment by jdeckerms** [comment]
@mythjuha Thanks for the update. I passed on your work-around to the product team. They're still working on how to directly add the null character in WCD directly.
