### ISSUE TITLE
There is a typing mistake in this article

### ISSUE THREAD

**Issue by lulMeow** [MicrosoftDocs/windows-itpro-docs#11072]
in this part:

 This approach is the recommended one for third-party firewalls to coexist with the Windows Defender Firewall; **third-party party firewalls** that comply with this recommendation have the certified logo from Microsoft. 

instead of "third-party party firewalls" it should be "third-party firewalls"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b90732e6-ee7b-cb24-242a-38eafa5f6b05
* Version Independent ID: f39f3c93-fb61-de69-312c-64088eb568bb
* Content: [Basic Firewall Policy Design (Windows)](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/basic-firewall-policy-design)
* Content Source: [windows/security/threat-protection/windows-firewall/basic-firewall-policy-design.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/basic-firewall-policy-design.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
thank you for reporting this, @lulMeow. The typo has been fixed and it will be reflected soon in the document.
