### ISSUE TITLE
Transposed EventID number for Password Change

### ISSUE THREAD

**Issue by Havokmon** [MicrosoftDocs/windows-itpro-docs#11073]
Password Change follow up Event ID Is 4724, not 4742 - 

![image](https://user-images.githubusercontent.com/9556067/205372632-118a1ab4-d213-4d64-b90a-ac4427d3e00d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f2087986-5e1b-bf86-099a-5511f527a3a9
* Version Independent ID: 65196e47-4d59-f510-f486-63f2ef9bf963
* Content: [4716(S) Trusted domain information was modified. (Windows 10)](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4716)
* Content Source: [windows/security/threat-protection/auditing/event-4716.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4716.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by msbemba** [comment]
@Havokmon Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11291

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by vinaypamnani-msft** [comment]
@Havokmon @msbemba The event ID that's in the document is for "A computer account was changed", which is indeed 4742. The one in the screenshot (4724) is for "An attempt was made to reset an account's password".

**Comment by Havokmon** [comment]
My point was that an ANONYMOUS login 4716 is followed by a 4724, not 4742.

**Comment by vinaypamnani-msft** [comment]
@Havokmon Understood. I am actually trying to test this as well to confirm, so the entire event can be replaced, not just numbers transposed.

**Comment by vinaypamnani-msft** [comment]
In my test, I noticed both events logged, so I've updated the article accordingly.
