### ISSUE TITLE
"Interactive Services Detection" (UI0Detect.exe) service is gone since 1803?

### ISSUE THREAD

**Issue by juancorradine** [MicrosoftDocs/windows-itpro-docs#1107]
I use a software called AlwaysUp (https://www.coretechnologies.com/products/AlwaysUp/), which depends on this "Interactive Services Detection" Service (UI0Detect.exe), to show applications in a "Session 0" screen.

Since I upgraded to 1803 this service and the UI0Detect.exe file are gone.

I couldn't find any official reference to this in the "Features removed or planned for replacement starting with Windows 10, version 1803" page, or anywhere else really.. 

Is there any alternative, or way to manually install this service in 1803?

Thanks!

**Comment by andreabichsel** [comment]
Thank you for your feedback! Interactive Services Detection has been removed: https://support.microsoft.com/en-us/help/4014193/features-that-are-removed-or-deprecated-in-windows-10-creators-update. I'm not sure what you can use instead, but you might be able to get answers on our support page https://support.microsoft.com/en-us.

**Comment by LunarResearch** [comment]
Use my tool to go to session 0.
[UI0Detect.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/7269178/UI0Detect.zip)
