### ISSUE TITLE
[Intel Icelake Server] System Guard Enable but not running.

### ISSUE THREAD

**Issue by WillyChenn** [MicrosoftDocs/windows-itpro-docs#11088]
[Enter feedback here]

Hi,

 Refer the guide : https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection#how-to-verify-system-guard-secure-launch-is-configured-and-running

 I can enable it with 4 methods, but even the System Guard is enabled, but not running.
 Here is the snapshot : 
![image](https://user-images.githubusercontent.com/50037721/207002698-cb9ea054-b807-4f0b-a487-8143f625c9b7.png)
![image](https://user-images.githubusercontent.com/50037721/207002804-00242958-c1f6-483d-9fc5-aa1f4c2a30f3.png)

 I check the configuration with Intel Platform of "System requirements for System Guard".
 But it seem that is fine with this list.

 How should I enable this? Is there something else need to re-confirme?

 My configuration :
 Platform : Whitley
 CPU : Icelake 6330 * 2
 TPM : 2.0

Thanks,
Willy

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31d623d9-316c-0ef1-b6be-c3773d77ca21
* Version Independent ID: 83ddb59d-0cfc-34f2-e666-8927d86a04a7
* Content: [System Guard Secure Launch and SMM protection (Windows 10)](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection)
* Content Source: [windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by RAJU2529** [comment]
@WillyChenn . Your Intel processor model does not support Intel V pro technology feature, hence system guard will not run.

https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-system-guard/how-hardware-based-root-of-trust-helps-protect-windows

**Comment by WillyChenn** [comment]
@RAJU2529 

Thanks for the reply, is there any support list for Icelake-SP?
 Or all Icelake-SP CPU are not support this security feature?

Thanks,
Willy

**Comment by RAJU2529** [comment]
@WillyChenn . Few ice lake processors are supported Intel v pro feature here is the list
https://ark.intel.com/content/www/us/en/ark/search/featurefilter.html?productType=873&0_VProTechnology=True&1_Filter-Family=595

**Comment by WillyChenn** [comment]
@RAJU2529 
Sorry for the late reply, as the list, I can't find the Icelake-SP CPU.
So this fail situation is expected, right?

Thanks,
Willy

**Comment by RAJU2529** [comment]
@WillyChenn , Yes failure.

**Comment by WillyChenn** [comment]
@RAJU2529 
Got it, the last question, I find that some of the Icelake server have certified for Windows - Secured-Core Server.

But if Icelake CPU is not supported System Guard, why this Icelake server can certified by Window Server 2022 as Secured-core Server?
![image](https://user-images.githubusercontent.com/50037721/209935091-6a7eabae-4be7-4497-9600-3d022e1e1207.png)
https://www.windowsservercatalog.com/item.aspx?idItem=930CB804-102A-58E2-5450-7A2FC7C8F20F&bCatID=1333&qos=2000000001

Is it expected result?

Thanks and happy new year!
Willy

**Comment by RAJU2529** [comment]
@WillyChenn , I cannot comment on, we should ask the author of the windows sever catalog page

**Comment by WillyChenn** [comment]
@RAJU2529 
Is there any windows for it?

Thanks, Willy

**Comment by RAJU2529** [comment]
@WillyChenn Sorry  i dont know

**Comment by WillyChenn** [comment]
@RAJU2529 @yogkumgit 

I have some test and find it that it can be worked on Icelake.
I check some requirement and TXT disable will cause this fail situation.

So after enabling the TXT, this issue will be disappeared.
