### ISSUE TITLE
Wie kann ich den Zwang zur Passwortabgabe bei Win 11 2022 wieder los werden? Das habe ich nicht bestellt.

### ISSUE THREAD

**Issue by Olli-CIC** [MicrosoftDocs/windows-itpro-docs#11081]
Nichts von all den Tips funktioniert

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er wird für die Verknüpfung von learn.microsoft.com zum GitHub-Issue benötigt.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Verwalten von Windows Defender Credential Guard (Windows) - Windows security](https://learn.microsoft.com/de-de/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/main/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @Olli-CIC, can you please clarify the issue, what you tried to resolve and the behavior?
 If you could reply in English, it would be appreciated, as I may miss some details with automatic translation
