### ISSUE TITLE
Can the below document be updated for Ibiza?

### ISSUE THREAD

**Issue by onpremcloudguy** [MicrosoftDocs/windows-itpro-docs#1108]
Hi,

would we be able to get this file windows-defender-atp/configure-endpoints-mdm-windows-defender-advanced-threat-protection.md updated to use the new Azure Portal rather then the Silverlight Portal?

I'm happy to complete if you can provide guidance on how to put screen grabs in.

Cheers

Steve

**Comment by mjcaparas** [comment]
Hi, 
Thank you for your feedback. 

The section "Use the Azure Intune Portal to deploy Windows Defender Advanced Threat Protection policies on Windows 10 1607 and higher" provides guidance using the Azure Portal.

Did you mean that we should add screen captures for that section? 

Thank you for helping me understand.

**Comment by onpremcloudguy** [comment]
Hi, 
Sorry for the confusion, i've just realised that it's not an issue with this page, but the link from the onboarding process on this page: https://securitycenter.windows.com/preferences2/onboarding which is still referring to Silverlight version of Intune, rather then the Ibiza portal.

Would be good to esculate to the Defender Security Center team, but happy for this to be closed from a docs point of view.

Cheers

Steve
