### ISSUE TITLE
When does Micorosft stop with creating "directory-pages" and start making INFORMATION pages

### ISSUE THREAD

**Issue by pear7777** [MicrosoftDocs/windows-itpro-docs#11087]
I an looking for a procedure, and I find this page, but from there I need to kclick on to a complete TREE of sub sub sub sub sub pages, and back back back back back and sub sub sub sub sub .. etc   to find all information

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8835bcf1-6726-d6a0-22ff-9813f1e52a68
* Version Independent ID: 11deedce-db76-0a60-f7ba-254ad6dbc1fc
* Content: [Create Your AppLocker policies (Windows)](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/create-your-applocker-policies)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/applocker/create-your-applocker-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/applocker/create-your-applocker-policies.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @pear7777 for the feedback. I agree that the content in that section can use some information architecture rework. To be honest, there are some areas of our content that were unmanaged for a while, and so my team is working through that backlog of content debt. I've carved off an internal work item (7388445) to review this set of content. I think in this particular instance we have feature PMs that are very involved and can help out with that review. Thanks for bringing it to our attention.

Also note the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/), which outlines the expectations for community interactions in and around learn.microsoft.com, is designed to help "provide a welcoming and inspiring community for all." Please consider that in the future for your next feedback.
