### ISSUE TITLE
Beware of quotation marks translations in code

### ISSUE THREAD

**Issue by dubepaul** [MicrosoftDocs/windows-itpro-docs#11097]
Hi! In the canadian-french translation of this page there is a line of code with quotes, but the quote have been "translated" from "English quotes" to «French Quotes». This is completely wrong, as the french quotes aren't quotes at all for any system.

This
Enable-WindowsOptionalFeature -FeatureName «Containers-DisposableClientVM» -All -Online.

Should be
Enable-WindowsOptionalFeature -FeatureName "Containers-DisposableClientVM" -All -Online

(Even the trailing dot may cause problems to some)

Have a great day!
Paul

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour learn.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 8c06f3ef-5946-862a-ae14-f897fdb518ca
* Version Independent ID: cd6a8b99-b1e9-dff5-f174-a15840b304f0
* Content: [Bac à sable Windows - Windows security](https://learn.microsoft.com/fr-ca/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/main/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @dubepaul for the feedback. Yes, very problematic. An easy fix, that command line should be escaped as a code block, for example:

```markdown
   ```powershell
   Enable-WindowsOptionalFeature -FeatureName "Containers-DisposableClientVM" -All -Online
```

or even just

```markdown
`Enable-WindowsOptionalFeature -FeatureName "Containers-DisposableClientVM" -All -Online`
```

Any strings in a code block aren't translated. I'll put in that fix now. Please do file an issue for any other instances like this that you discover, and we'll get them fixed similarly.
