### ISSUE TITLE
undocumented error code

### ISSUE THREAD

**Issue by rastickl** [MicrosoftDocs/windows-itpro-docs#11095]
[Enter feedback here]
My pin is not working and was told to goto aka.ms/PINError and look up error code 
0x801c044f

which does not exist, must like my desire to figure this out ;-<

Any help on this would be greatly appreciated!

Thanks,
Ralph

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows)](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by lee-halford** [comment]
@rastickl you are missing an 's' off the end of the URL. The correct URL is 'https://aka.ms/PINErrors'.

Which should take you to: https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation

**Comment by rastickl** [comment]
And you are still missing the error code.

Please see if you can find this error code and file a bug to have the documentation updated to match the results of the Windows output.

If you search your error list, it is not on there.  Doesn't seem helpful to blame me if you haven't searched for the actual code that was provided.

Thanks for your attention on this,
Ralph

**Comment by paolomatarazzo** [comment]
0x801c044f means DSREG_E_WAM_TOKEN_REQUEST_CANCELLED
WAM is Web Account Manager (Azure AD account in this scenario)
@rastickl which OS are you using? what's the output of dsregcmd /status? have you tried logoff/logon again?

**Comment by paolomatarazzo** [comment]
Closing the issue due to the lack of response. @rastickl please reopen the issue if you see the same error code again
