### ISSUE TITLE
Certificate Services Lifecycle Notifications GPO not working?

### ISSUE THREAD

**Issue by RobMulder** [MicrosoftDocs/windows-itpro-docs#11098]
[https://social.technet.microsoft.com/wiki/contents/articles/14250.certificate-services-lifecycle-notifications.aspx](url)

I'm getting event 1003 for expiring certificates correctly BUT way to early (at 50% of lifetime).
Default should be at 90% of lifetime.

I wanted to change that, so I came along the website above.

Configured a GPO for _Computer and User_:
![GPO-settings](https://user-images.githubusercontent.com/37290742/208052862-b3661102-b13b-4208-8f52-0fa48567ce5a.jpg)

**BUT**, if I review the settings the configured policies are NOT showing in the computer settings:
![GPO-viewcomputersettings](https://user-images.githubusercontent.com/37290742/208052901-bea20936-c879-4ccb-b9ee-7a11afc1f8a7.jpg)

**HOWEVER**, I do see them under user settings:
![GPO-viewusersettings](https://user-images.githubusercontent.com/37290742/208052955-4694684f-25a6-4893-8da9-9118f1da9093.jpg)

Same for Group Policy Results and the Local Policies on a server with that policy!
Tested in on 3 different domains.
What is going on here?

UPDATE
I found the registry keys, so I can confirm that the percentage setting is enrolled to the servers.
HKLM and HKCU registry hives:	SOFTWARE\Policies\Microsoft\Cryptography\AutoEnrollment\
Keys: OfflineExpirationPercent, OfflineExpirationStoreNames=MY and AEPolicy=7

So, why do I get event ID 1003 when certificates are on 50% lifetime?

**Comment by aczechowski** [comment]
Thanks @RobMulder for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
