### ISSUE TITLE
Bad Hive string in LogonUI configuration

### ISSUE THREAD

**Issue by AlphaXD001** [MicrosoftDocs/windows-itpro-docs#11094]
"HKEY\_LOCAL\_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI"  should be "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a45c77e-0b22-27ef-8b4e-17db0ea60ddf
* Version Independent ID: 7068c1b3-aa7b-6629-4ff4-45f522297a86
* Content: [Set up a single-app kiosk on Windows 10/11 - Configure Windows](https://learn.microsoft.com/en-us/windows/configuration/kiosk-single-app)
* Content Source: [windows/configuration/kiosk-single-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/kiosk-single-app.md)
* Product: **windows-client**
* Technology: **itpro-configure**
* GitHub Login: @lizgt2000
* Microsoft Alias: **lizlong**

**Comment by aczechowski** [comment]
Thanks @AlphaXD001 for catching that. I'll fix it now, this issue will close automatically when the pull request merges, but given the US holiday, it may be a few days before the change is live.
