### ISSUE TITLE
Firmware Protection missing in Core Isolation

### ISSUE THREAD

**Issue by Fortress937** [MicrosoftDocs/windows-itpro-docs#11093]
![image](https://user-images.githubusercontent.com/119410273/207609521-f11f8921-ba0b-4807-9edb-6b556d829381.png)

Where is the Firmware Protection settings??
i want to turn on firmware protection but i couldn't find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31d623d9-316c-0ef1-b6be-c3773d77ca21
* Version Independent ID: 83ddb59d-0cfc-34f2-e666-8927d86a04a7
* Content: [System Guard Secure Launch and SMM protection (Windows 10)](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection#windows-security-app)
* Content Source: [windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by RAJU2529** [comment]
@Fortress937 . only Supported Intel V pro feature processors are supported in firmware protection.
Also Few AMD processors are supported firmware protection

**Comment by aczechowski** [comment]
Added link to one page that talks about this feature. My device doesn't have it either. There's some additional description of firmware protection in this support article: https://support.microsoft.com/windows/core-isolation-e30ed737-17d8-42f3-a2a9-87521df09b78

I'll assign this issue to @vinaypamnani-msft to look into this further if we need to add a bit more about this feature, even if just a note that not all devices support it.

**Comment by RAJU2529** [comment]
@aczechowski how to enable firmware protection is given in support article.

My suggestion is to add possible Intel v pro processors list starting from 8th gen onwards.

What's is your opinion?

**Comment by vinaypamnani-msft** [comment]
I've added a note to this article, linking to the system requirements.
