### ISSUE TITLE
Windows 10 vs 11

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/windows-itpro-docs#11099]
Hi!

There are 9 references to "This policy is only enforced in Windows 10 Pro, Enterprise, and Education editions." on this page.

1. Shouldn't that be true for Windows 11 as well? I.e. "This policy is only enforced in Windows 10/11 Pro, Enterprise, and Education editions."
2. Why is this statement even present? The compatibility matrix for each setting outlines which SKUs it supports. Should it be read as "It is supported on Windows 10 Business and Windows 11 SE but it will not be enforced"? If so, what will happen if you target those SKUs with a policy?

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06745768-affe-c86a-2da6-7bd694e847c9
* Version Independent ID: e832ada1-5f0c-7809-b8a1-bb91cadb6975
* Content: [Policy CSP - DeliveryOptimization - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-deliveryoptimization)
* Content Source: [windows/client-management/mdm/policy-csp-deliveryoptimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-deliveryoptimization.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Hi @GenerAhl. yes this will soon be unnecessary and moot. We're in progress to automate the creation of all CSP content pulling information from the DDF XML similar to what the Intune Settings Catalog does. With that, each policy in the CSP will have a new automated applicability table based on what's in the DDF, something very similar to the following:

| Scope | Editions | Applicable OS |
|:--|:--|:--|
| :heavy_check_mark: Device <br> :x: User | :x: Home <br> :heavy_check_mark: Pro <br> :heavy_check_mark: Enterprise <br> :heavy_check_mark: Education <br> :heavy_check_mark: Windows SE | :heavy_check_mark: Windows 10, version 1607 [10.0.14393] and later |

(that's copied from the **DOAbsoluteMaxCacheSize** policy in the newly automated article)

So can easily see which editions and which OS versions the specific policy applies.

@vinaypamnani-msft @lizgt2000 @nicholasswhite  FYI we'll need to make sure we don't copy those notes verbatim during the migration process. 😁 

I'm closing this issue
