### ISSUE TITLE
HypervisorEnforcedCodeIntegrity resulting in NotApplicable in Windows 10 

### ISSUE THREAD

**Issue by jerryabo** [MicrosoftDocs/windows-itpro-docs#11106]
CSP returns not applicable on Windows 10 (22H2+LCU) - please confirm applicability and correct if appropriate.

353578410

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c8cc4c83-133e-d299-8fcf-1580a572a8f4
* Version Independent ID: c8cc4c83-133e-d299-8fcf-1580a572a8f4
* Content: [Policy CSP - VirtualizationBasedTechnology - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-virtualizationbasedtechnology)
* Content Source: [windows/client-management/mdm/policy-csp-virtualizationbasedtechnology.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-virtualizationbasedtechnology.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by RAJU2529** [comment]
@jerryabo . Which processor model you are using and which windows version edition you have installed.

**Comment by aczechowski** [comment]
Hiya @jerryabo 😄 
We're in progress to migrate all of the CSP content to automated markdown pulled directly from the DDF XML, same as what's done with the Intune Settings Catalog. This specific article isn't published yet, but here's the new applicability table that will be included:

| Scope | Editions | Applicable OS |
|:--|:--|:--|
| :heavy_check_mark: Device <br> :x: User | :x: Home <br> :heavy_check_mark: Pro <br> :heavy_check_mark: Enterprise <br> :heavy_check_mark: Education <br> :x: Windows SE | :heavy_check_mark: Windows 11, version 21H2 [10.0.22000] and later |

Where you can see that it's only applicable on Windows **11** version 21H2 and later.

I'm closing this issue, as it will be addressed soon when we publish the new automated article 😁
