### ISSUE TITLE
UAC Prompt Info Needed

### ISSUE THREAD

**Issue by gstendig** [MicrosoftDocs/windows-itpro-docs#11102]
Please add commentary/verbiage addressing whether & how Hello for Business works with User Account Control (prompts) - along with configuration options, recommended settings, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82ecd7ea-0ecb-cf7b-a1ab-9cda97e5cc0a
* Version Independent ID: 81acb0ad-2d46-bd0b-abb5-7c2e851d7a71
* Content: [Windows Hello for Business Frequently Asked Questions (FAQ)](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-faq)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-faq.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-faq.yml)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @gstendig can you please clarify the exact questions that you would like to see addressed in the FAQ articles? If we determine that the questions are indeed asked frequently, then we can consider adding them. The documentation already covers some of these aspects so I'm not sure that adding every single possible question adds much value.

**Comment by gstendig** [comment]
Unless I missed something on that particular page (just did a quick search on it, to confirm) - I see no mention of UAC whatsoever. Kindly point me to resources you feel fit the bill, if I've overlooked them.

In terms of an exact question to add, would love to see "Does Windows-based User Account Control (UAC) and its associated UAC prompts work with Hello for Business?"

And ideally, the answer should address:

  *
Does it work - yes vs. no
  *
Supported authentication configurations (e.g. PIN vs. biometric vs. both/either, Cloud only vs. Hybrid vs. On-prem, etc.)
  *
Special considerations or scenarios (e.g. local logon vs. remote/RDP logon)
  *
UAC settings that are vs. are not compatible with WH4B
     *
[cid:e2615aee-2b06-477b-82bf-1ba3cd81dd1d]
     *
[cid:56506319-6c80-48df-ac4d-dab9d7398d18]
  *
And perhaps most importantly, MS-recommended settings and configuration options

________________________________

**Comment by paolomatarazzo** [comment]
I'm not aware of specific UAC settings that are not compatible with WHFB. If UAC prompts for username/password and the user is enrolled in WHFB, then the user can use WHFB to elevate. If a user is not an admin but have dual enrollment enabled, then can use a secondary account to perform the runas. Please review the following: https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-dual-enrollment
https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-remote-desktop
https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs

As far as recommendations go, please check our security baselines. Example: https://learn.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-mdm-all?pivots=mdm-november-2021#ms-security-guide

**Comment by paolomatarazzo** [comment]
sent email to feat PMs to confirm. Will update the documentation as I hear back.

**Comment by paolomatarazzo** [comment]
There are no dependencies between WHFB and UAC. During UAC prompt, all available credential providers will be enumerated. Therefore, if the user that is receiving the UAC prompt is enrolled in WHFB, he/she will see the WHFB credential provider.
Closing the issue, @gstendig please reopen if you think a change is needed.
