### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ericlaw1979** [MicrosoftDocs/windows-itpro-docs#1114]
"company’s developed data loss prevention" should be "companies developed data loss prevention" (although some such DLP schemes were not developed by any company at all).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d016c711-b1f4-668e-adbc-ff6911965851
* Version Independent ID: 64b2a1a4-1efe-35da-721e-7cbb0b1c684e
* Content: [Protect your enterprise data using Windows Information Protection (WIP) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by andreabichsel** [comment]
Thank you for your feedback! This has been fixed.
