### ISSUE TITLE
Still no 1803 or 1709 methods explained... if you can't keep your documentation up to date, that is a sign YOU HAVE A PROBLEM WITH YOUR RELEASE CYCLES!!

### ISSUE THREAD

**Issue by seamonkey420** [MicrosoftDocs/windows-itpro-docs#1115]
nobody in Enterprise environments gives a flying FUCK about 1803 or even 1709..  or 1703.. we are on 1607 and if we could, we would stay on this version FOREVER.. timeline? people? no fucks given for pointless features that don't bring anything worthwhile for enterprise users who just need a damn pc that works each day and doesn't  reboot in teh middle of the night.  also shouldn't be this hard to configure windows updates to only use WSUS...  then again, this is what happens when a company fires its QC/QA dept and thinks the engineers can  self test.. Engineers =/= users; explain how the VMXNET3 adapter issue happened now 4 times in the last year? oh yea, no one in your lab is using VMware prob just hyper-v yet the rest of the real tech world uses vmware more than anything....  /rant

**Comment by andreabichsel** [comment]
@coreyp-at-msft I'm not sure which topic this came from, but it appears to be about WSUS. Can you look into whether the topics need updating?
