### ISSUE TITLE
Can’t import setup school PCs ppkg to Windows configuration designer

### ISSUE THREAD

**Issue by prjoni99** [MicrosoftDocs/windows-itpro-docs#1119]
Trying to increase the sleep timeout on the computers but I can’t modify the ppkg in Windows configuration designer

**Comment by jdeckerms** [comment]
@prjoni99 Try starting a new project (advanced provisioning), and choosing to import the ppkg that you want to change. Then in the new project, change the setting, and export as a new ppkg.
