### ISSUE TITLE
Missing Windows 2016+ AUOption options (5-6-7_

### ISSUE THREAD

**Issue by OursonBleu** [MicrosoftDocs/windows-itpro-docs#11246]
https://learn.microsoft.com/en-us/windows/deployment/update/waas-wu-settings#configuring-automatic-updates-by-editing-the-registry

In step 3, its missing the option for windows server 2016 + to have the option of 1 to 7

Disabled Value:
decimal: 1
KeyName: Software\Policies\Microsoft\Windows\WindowsUpdate\AU

Id: AutoUpdateMode
ValueName: AUOptions
item: decimal: 2 => 2 - Notify for download and auto install
item: decimal: 3 => 3 - Auto download and notify for install
item: decimal: 4 => 4 - Auto download and schedule the install
item: decimal: 5 => 5 - Allow local admin to choose setting
item: decimal: 7 => 7 - Auto Download, Notify to install, Notify to Restart 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6efb8dfd-971e-7257-f8b7-f80843989eb8
* Version Independent ID: d7808728-bb89-a06e-a103-ec1c74682f64
* Content: [Manage additional Windows Update settings - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/waas-wu-settings#configuring-automatic-updates-by-editing-the-registry)
* Content Source: [windows/deployment/update/waas-wu-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-wu-settings.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@OursonBleu  Thanks for filing this issue. The docs will be updated in a bit.
