### ISSUE TITLE
ltsc

### ISSUE THREAD

**Issue by node-constructor** [MicrosoftDocs/windows-itpro-docs#11247]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 542f27b2-fc93-e90d-be8c-cb749b6dbcb2
* Version Independent ID: 8633dd0d-8ba8-8aba-a474-84dcf01e678f
* Content: [The Windows Security app](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-security-center/windows-defender-security-center)
* Content Source: [windows/security/threat-protection/windows-defender-security-center/windows-defender-security-center.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-security-center/windows-defender-security-center.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by RAJU2529** [comment]
@e0i , Close this issue #11247 immediately because no proper feedback and block the user to prevent spam post

**Comment by aczechowski** [comment]
Closing - @node-constructor  if you have further details about this feedback, please comment and reopen this issue.
