### ISSUE TITLE
Supported list of processors must be added 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#11244]
I like to add the supported list of Intel based V Pro   processors.

I would to like get opinion from article Main author and supported authors. 

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 50c07fb5-e000-a334-45a9-844e596d9080
* Version Independent ID: facb9dad-ba91-7d1f-5296-9289667fa7e3
* Content: [How a Windows Defender System Guard helps protect Windows 10](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-system-guard/how-hardware-based-root-of-trust-helps-protect-windows)
* Content Source: [windows/security/threat-protection/windows-defender-system-guard/how-hardware-based-root-of-trust-helps-protect-windows.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-system-guard/how-hardware-based-root-of-trust-helps-protect-windows.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by RAJU2529** [comment]
@vinaypamnani-msft What's is your opinion sir  in this issue #11244 ?

**Comment by vinaypamnani-msft** [comment]
@RAJU2529 I clarified the requirements, but we have no plans to list each individual processor and maintain the list in future.
