### ISSUE TITLE
A few small typos on page titled BitLocker Deployment and Administration FAQ

### ISSUE THREAD

**Issue by AaronInTheForest** [MicrosoftDocs/windows-itpro-docs#1124]
"You **can can** Group Policy settings to require that data drives be BitLocker-protected before a BitLocker-protected computer can write data to them"

"Although it's not the most secure way to encrypt a drive, this option can reduce encryption time by more than 99 percent, depending on how much data that needs to **beencrypted**"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a2b6bec-05af-1e20-a22e-d2a0c71a7dca
* Version Independent ID: 5c644e57-ae1b-a510-ebdb-52391fb6407f
* Content: [BitLocker frequently asked questions (FAQ) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-deployment-and-administration-faq)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-deployment-and-administration-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-deployment-and-administration-faq.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by andreabichsel** [comment]
Fixed--thank you!
