### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Vinothjv10** [MicrosoftDocs/windows-itpro-docs#11248]
[Enter feedback here]
Sometimes the microsoft store can't properly working, so fix that bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9db96ae7-52a1-83df-3913-35765fc62972
* Version Independent ID: 9db96ae7-52a1-83df-3913-35765fc62972
* Content: [What's new in Windows 11, version 22H2 for IT pros - What's new in Windows](https://learn.microsoft.com/en-us/windows/whats-new/whats-new-windows-11-version-22h2)
* Content Source: [windows/whats-new/whats-new-windows-11-version-22H2.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/whats-new-windows-11-version-22H2.md)
* Product: **windows-client**
* Technology: **itpro-fundamentals**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by RAJU2529** [comment]
@Vinothjv10 , You should post your issue in 
**https://answers.microsoft.com/en-us/windows/forum/windows_11-windows_store?**

**Comment by Vinothjv10** [comment]
@RAJU2529 Ok

**Comment by mestew** [comment]
Closing issue as there is nothing more to do.
