### ISSUE TITLE
Edge Favorites and Sticky Notes

### ISSUE THREAD

**Issue by BillerDude** [MicrosoftDocs/windows-itpro-docs#1125]
I've noticed that the current iteration of USTM does not appear to migrate favorites for the Edge browser, or existing Sticky Notes.  Is this something that is planned to be added in a future version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92c930a-371f-16be-6427-06432a692259
* Version Independent ID: 5bc2820d-989b-0fc1-f812-1a91f159fa25
* Content: [User State Migration Toolkit (USMT) Reference (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-reference)
* Content Source: [windows/deployment/usmt/usmt-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/usmt/usmt-reference.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
@BillerDude The current version of USMT can transfer Edge favorites. For sticky notes, you can migrate StickyNotes.snt placed under %appdata%\Microsoft\Sticky Notes. For this purpose, you can use custom XML.

@mypil Please guide the user how he can request for this feature. 

Thanks.

**Comment by mypil** [comment]
@BillerDude - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. 
They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
