### ISSUE TITLE
Unclear wording

### ISSUE THREAD

**Issue by mav147** [MicrosoftDocs/windows-itpro-docs#11252]
Are the descriptions for ForceInstantLock and ForceInstantWake unclear on this page? It states:

ForceInstantLock = This policy specifies, whether the device can lock when a human presence sensor detects a human.
ForceInstantWake = This policy specifies, whether the device can lock when a human presence sensor detects a human.

I would have worded it as such:

ForceInstantLock = This policy specifies, whether the device can lock when a human presence sensor does not detect a human.
ForceInstantWake = This policy specifies, whether the device can wake when a human presence sensor detects a human.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 53c259bd-bfb2-91f3-86ba-374bb3623a13
* Version Independent ID: 53c259bd-bfb2-91f3-86ba-374bb3623a13
* Content: [Policy CSP - HumanPresence - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-humanpresence)
* Content Source: [windows/client-management/mdm/policy-csp-humanpresence.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-humanpresence.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
We're switching how we manage the CSP content, but need to figure out the process for this sort of feedback.

**Comment by vinaypamnani-msft** [comment]
I just checked and these policies are already queued for automation and have better wording in the proposed PR. This will be fixed when we merge the PR, which will happen later this month.
