### ISSUE TITLE
PS Code error on a WDAC page

### ISSUE THREAD

**Issue by Uzhirian** [MicrosoftDocs/windows-itpro-docs#11251]
There is an error in the PS commands under the section 'Convert your WDAC policy XML to binary'

$WDACPolicyXMLFile = $env:USERPROFILE"\Desktop\MyWDACPolicy.xml" should be $WDACPolicyXMLFile = $env:USERPROFILE+"\Desktop\MyWDACPolicy.xml"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47b5e396-a7d4-af3c-fde2-5b8374d0ad27
* Version Independent ID: 9ea74c2f-76d4-9735-ac2b-cc38e1bd00f6
* Content: [Deploying Windows Defender Application Control (WDAC) policies](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control-deployment-guide)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control-deployment-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control-deployment-guide.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @jgeurten
* Microsoft Alias: **jogeurte**

**Comment by jgeurten** [comment]
Addressed in #7727

https://github.com/MicrosoftDocs/windows-docs-pr/pull/7727

**Comment by yogkumgit** [comment]
@jgeurten Please help us in resolving this issue. Thanks
