### ISSUE TITLE
Windows 10 22H2 Endpoint information is scheduled to be released.

### ISSUE THREAD

**Issue by tsnagata1** [MicrosoftDocs/windows-itpro-docs#11257]
The customer wants to know when Windows 10 22H2 is scheduled to be released for this article.

https://learn.microsoft.com/ja-jp/windows/privacy/manage-windows-21h2-endpoints

Best Regards,
Tsubasa Nagatani

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c231307-5106-4d90-5c2b-d614ccc2dadd
* Version Independent ID: e5a8a01b-e2d4-fc7c-b8a5-6d40c3d40f24
* Content: [Connection endpoints for Windows 11 Enterprise - Windows Privacy](https://learn.microsoft.com/en-us/windows/privacy/manage-windows-11-endpoints)
* Content Source: [windows/privacy/manage-windows-11-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/manage-windows-11-endpoints.md)
* Product: **windows-client**
* Technology: **itpro-privacy**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by tsnagata1** [comment]
Hi any update for my pleasure.

**Comment by DHB-MSFT** [comment]
Closing because discussion is happening internally with submitter and appropriate PM.
