### ISSUE TITLE
Lack of edge support in server 2016

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/windows-itpro-docs#1126]
I mean seriously, did anyone give a shred of thought to a consistent user experience?  I just had a client who put in tons of effort to remove/hide edge in new desktop deployments and passed on expanding their RDS environment because of poor decisions like this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47bd063-dbf5-f628-3a13-4602583fb750
* Version Independent ID: 9dad7d24-7e1b-73ec-819b-9760a23f33db
* Content: [Microsoft Edge requirements and language support (Microsoft Edge for IT Pros)](https://docs.microsoft.com/en-us/microsoft-edge/deploy/hardware-and-software-requirements)
* Content Source: [browsers/edge/hardware-and-software-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/hardware-and-software-requirements.md)
* Product: **edge**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by lizap** [comment]
Hi, Jordan - thanks for the feedback. This is something that's being discussed on the server side and RDS side. You might check out the [Windows Server posts in the User Voice forum relevant to Edge ](https://windowsserver.uservoice.com/forums/295047-general-feedback?query=edge)- that's probably the best channel for this feedback. Thanks.
