### ISSUE TITLE
testing public repo auto label and assignment

### ISSUE THREAD

**Issue by A-A-Ron42** [MicrosoftDocs/windows-itpro-docs#11264]
just a test from Aaron's secondary account 😉 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed605e51-e301-5a51-27ba-cb4a56d4a05a
* Version Independent ID: ed8eb42f-05f3-7155-3cbd-abcd0eb8f1e0
* Content: [How Windows Update works - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/how-windows-update-works)
* Content Source: [windows/deployment/update/how-windows-update-works.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/how-windows-update-works.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
oops - automation currently just for PRs, not issues. closing
