### ISSUE TITLE
Wider Windows 11 Support

### ISSUE THREAD

**Issue by jonathan-ford** [MicrosoftDocs/windows-itpro-docs#11261]
Is there any known plan to broaden support for this beyond the SE edition of Windows 11? (i.e. Pro and Ent?) 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4889cf2-86cb-9607-32d5-2851f68f63f6
* Version Independent ID: d4889cf2-86cb-9607-32d5-2851f68f63f6
* Content: [Configure federated sign-in for Windows devices - Windows Education](https://learn.microsoft.com/en-us/education/windows/federated-sign-in)
* Content Source: [education/windows/federated-sign-in.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/education/windows/federated-sign-in.md)
* Product: **windows-client**
* Technology: **itpro-edu**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @jonathan-ford , nothing new to disclose just yet.
