### ISSUE TITLE
May induce license violations

### ISSUE THREAD

**Issue by jyama4ta** [MicrosoftDocs/windows-itpro-docs#11262]
This document says '***Azure activation requires a connection to Azure KMS only.***'
However, from Product Terms, KMS activation is allowed on Azure Goverment only. The users need to use Azure AD-based activation on Azure. Please update the note that user should use Azure AD-based activation.

https://www.microsoft.com/licensing/terms/en-US/productoffering/WindowsDesktopOperatingSystem/EAEAS
> Windows 11 Virtualization on Azure
> Customers with Windows 11 Enterprise Per User SLs, Windows 11 Education Per User SLs, or VDA Per User SLs using Azure AD-based activation on supported editions may install the Windows 10 Creators Update or later version software on a virtual machine running in Customer's Microsoft Azure accounts. Each [Licensed User](https://www.microsoft.com/licensing/terms/product/Glossary/all) may access up to four instances of the software. **Azure Government customers may use KMS activation in lieu of Azure AD-based activation.** When configuring the image(s) on Microsoft Azure, Customers must indicate their use of the multitenant hosting for Windows and adhere to other software configuration requirements available at https://docs.microsoft.com/windows/deployment/vda-subscription-activation. This section does not apply to Students receiving access to software through [Student Use Benefit](https://www.microsoft.com/licensing/terms/product/Glossary/all).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6443e532-640d-81c0-8215-b711bd1977d4
* Version Independent ID: fc504984-91d7-b586-04ec-4c751fb48998
* Content: [Windows subscription activation - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **windows-client**
* Technology: **itpro-fundamentals**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by yogkumgit** [comment]
@frankroj Please help us in resolving this issue. Thanks

**Comment by frankroj** [comment]
Hello @jyama4ta. Can you make edits to the docs directly as you see fit. We will then review the changes and approve from there. Thank you.
