### ISSUE TITLE
default settings discrepency

### ISSUE THREAD

**Issue by vinpathak84** [MicrosoftDocs/windows-itpro-docs#11275]
this article states that the default value for "User Account Control: Behavior of the elevation prompt for standard users" in Group policy would be "Prompt for Credentials", however the following article states otherwise:

https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-account-control-behavior-of-the-elevation-prompt-for-standard-users

this reflects a default value of: Prompt for credentials **on the secure desktop**

please clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 38066882-5022-1f08-3565-c13041b10921
* Version Independent ID: 30a904f6-64ce-2d03-f9b1-721f75b8a106
* Content: [User Account Control Group Policy and registry key settings (Windows)](https://learn.microsoft.com/en-us/windows/security/identity-protection/user-account-control/user-account-control-group-policy-and-registry-key-settings)
* Content Source: [windows/security/identity-protection/user-account-control/user-account-control-group-policy-and-registry-key-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/user-account-control/user-account-control-group-policy-and-registry-key-settings.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @vinpathak84 and thank you for the feedback! Both articles are correct. The first article you are referring to explains the default GPO value, while the second article describes the default OS value. I will reword the second article to make it more clear.

**Comment by paolomatarazzo** [comment]
@vinpathak84 I double checked, and you are correct. Thank you for the feedback. I will update the article accordingly.
