### ISSUE TITLE
Typo in "...testing environments becaise they can be more..."

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/windows-itpro-docs#11270]
There is a typo in this sentence:

Dynamically expanding VHDXs are recommended only for development and testing environments **becaise** they can be more easily corrupted by a catastrophic system shutdown, such as a power outage.

the word _Because_ is incorrectly spelled.

https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/deploy-windows-on-a-vhd--native-boot?view=windows-11#types-of-virtual-hard-disks

**Comment by aczechowski** [comment]
Thanks @HotCakeX for the feedback, but that content is in a separate repo owned by a separate team. However, my team happens to be doing a bug bash today, and this is a simple/quick fix, so I made the change in the other repo. 😄

**Comment by HotCakeX** [comment]
Yes, sorry about that, I couldn't find the correct repo for it, some doc pages don't have the feedback button at the bottom of them. but glad to know it'll be fixed :)
