### ISSUE TITLE
Virtualization-Based Security

### ISSUE THREAD

**Issue by reuvygroovy** [MicrosoftDocs/windows-itpro-docs#11273]
Hi

The screenshots for GPO configuration for both enabling and disabling show a **Not Configured** value for Virtualization-Based Code Integrity:
![image](https://user-images.githubusercontent.com/1325158/212843128-72a9dfcc-7034-48ed-ae2d-0d139ce989dc.png)

In the Security Baselines for Windows/Server - for all new and current OSs the reccomendation is to have this value set:
![image](https://user-images.githubusercontent.com/1325158/212843446-1c13d75c-c822-45e2-8e45-fbced6a9dc6d.png)

Also, when running DG_Readiness_Tool.ps1 script is seems to enable this feature:
![image](https://user-images.githubusercontent.com/1325158/212843602-0a8a4667-38ec-49b2-bb08-145f452e4638.png)
![image](https://user-images.githubusercontent.com/1325158/212843623-3c54e0f0-1e0d-4dce-a38f-a1d59efb208f.png)

So the documentation is a bit confusing.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows)](https://learn.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @reuvygroovy and thank you for the feedback! The article describes how to *Enable Windows Defender Credential Guard by using Group Policy* and the screenshot reflect its enablement. The goal of this specific article is not to describe the different configurations available once VBS is turned on, one of them being HVCI. The configuration of HVCI is described here: https://learn.microsoft.com/windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity
