### ISSUE TITLE
Query - Prompt the user during enrollment

### ISSUE THREAD

**Issue by DaithiG** [MicrosoftDocs/windows-itpro-docs#11285]
Just a query if I need to click "Prompt the user during enrollment" when creating the cert template if I am going to be pushing the cert out via Intune and the Intune connector?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e9cc344-d2c1-1f8b-232a-b2cccd8b32a3
* Version Independent ID: eb87d132-cc0b-8ab2-4417-51e1bc719c14
* Content: [Deploy certificates for remote desktop sign-in](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @DaithiG and thank you for the question. Ideally, the process should be transparent to the end user. The process to create the certificate template is described here: https://learn.microsoft.com/mem/intune/protect/certificates-pfx-configure

I hope this helps!
