### ISSUE TITLE
Update Most recent password policy link

### ISSUE THREAD

**Issue by mazeunert** [MicrosoftDocs/windows-itpro-docs#11295]
[Enter feedback here]
Link to most recent password policy is a 2016 version. This should be the proper link

https://learn.microsoft.com/en-us/microsoft-365/admin/misc/password-policy-recommendations?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b5128d9a-e02a-df9b-24cc-32711ad37b54
* Version Independent ID: fecafb19-6b37-1f2e-ba3d-5e0bf0d49d09
* Content: [Password must meet complexity requirements (Windows 10)](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements)
* Content Source: [windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by msbemba** [comment]
@mazeunert Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11349

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mazeunert Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
