### ISSUE TITLE
Add description of %%14674 and %%14675

### ISSUE THREAD

**Issue by goosvorbook** [MicrosoftDocs/windows-itpro-docs#11308]
It can be useful if %%14674 and %%14675 are described as their human readable values "Value Added" and "Value Deleted" 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1209d651-ed6c-1504-09a2-7489913c4658
* Version Independent ID: c1885e1b-7afc-5352-996d-a0a374416134
* Content: [5136(S) A directory service object was modified. (Windows 10)](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5136)
* Content Source: [windows/security/threat-protection/auditing/event-5136.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-5136.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by msbemba** [comment]
@goosvorbook Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11355

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @goosvorbook Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
