### ISSUE TITLE
VT-x

### ISSUE THREAD

**Issue by powerdude** [MicrosoftDocs/windows-itpro-docs#1131]
How do we enable/disable VT-x for hardware virtualization?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5149561d-359f-875d-73c8-f14b2cfa8f80
* Version Independent ID: d465734d-6480-b7ed-6ca0-168e7b989063
* Content: [Manage Surface UEFI settings (Surface)](https://docs.microsoft.com/en-us/surface/manage-surface-uefi-settings)
* Content Source: [devices/surface/manage-surface-uefi-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/manage-surface-uefi-settings.md)
* Product: **w10**
* GitHub Login: @MiladCA
* Microsoft Alias: **jdecker**

**Comment by BrandonRecords** [comment]
There is no mechanism available on Surface devices or in Surface UEFI to disable VT-x or other CPU level settings.
