### ISSUE TITLE
DisableScanningNetworkFiles recommendation

### ISSUE THREAD

**Issue by PDarvMSFT** [MicrosoftDocs/windows-itpro-docs#11315]
Hello MS team,
This documentation page states that DisableScanningNetworkFiles should not be enabled. After many discussions with peers, I would argue that this setting should be enabled and recommended. As a matter of fact, tamper protection will enable this setting if it was disabled prior.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66b1ab2e-1964-5580-7c99-4bd4cd480075
* Version Independent ID: f7b5da46-04cb-3501-65fa-870a3c6f09b8
* Content: [Defender Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#allowscanningnetworkfiles)
* Content Source: [windows/client-management/mdm/policy-csp-defender.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-defender.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
Thanks for submitting this issue @PDarvMSFT. As we discussed internally, these docs are generated automatically, and the policy description comes from the GPO, so I recommend submitting feedback via the Feedback Hub app to correct the strings in the ADMX template for the policy which would then update the docs as well.
