### ISSUE TITLE
typo on this page

### ISSUE THREAD

**Issue by jlackman** [MicrosoftDocs/windows-itpro-docs#11314]
it says "Replated articles"

I think you want to say "Related" not "Replated"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0918f873-c505-e31f-e540-defc02b872e6
* Version Independent ID: a109ead4-7ec7-4ccd-b87b-d074ff05e9dc
* Content: [BitLocker Use BitLocker Recovery Password Viewer (Windows 10)](https://learn.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-use-bitlocker-recovery-password-viewer)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-use-bitlocker-recovery-password-viewer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-use-bitlocker-recovery-password-viewer.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you @jlackman for reporting the issue. This should be corrected later today.

**Comment by frankroj** [comment]
Fixed in https://github.com/MicrosoftDocs/windows-docs-pr/pull/7820
