### ISSUE TITLE
Windows Web Sign-in shouldn't be in private preview

### ISSUE THREAD

**Issue by amirjafarian** [MicrosoftDocs/windows-itpro-docs#11319]
This document mentions the Windows 10 Web Sign-in is in private preview but when checking Policy CSP (link below) this is supported and no longer is private preview. This seems to be confusing and if this has changed should be removed from document
https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-authentication#enablewebsignin

(admin edit: adding article metadata for proper linkage)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3d6356b-87ff-8c3a-56ef-1270a823d3ab
* Version Independent ID: 4d6ae878-66cf-0e10-bdf3-bdd6054cbc9d
* Content: [What's new in Windows 10, version 1809 - What's new in Windows](https://learn.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809#web-sign-in-to-windows-10)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1809.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/whats-new-windows-10-version-1809.md)
* Product: **windows-client**
* Technology: **itpro-fundamentals**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
@amirjafarian which article are you referring to that has the mention of the feature in private preview?

**Comment by aczechowski** [comment]
Assuming perhaps this article? https://learn.microsoft.com/windows/whats-new/whats-new-windows-10-version-1809#web-sign-in-to-windows-10

**Comment by amirjafarian** [comment]
@aczechowski, yes that's the link.

**Comment by aczechowski** [comment]
OK, thanks @amirjafarian for the clarity, and thanks for the feedback. Version 1809 (semi-annual channel, currently known as general availability channel) went end of service in 2021. Reference [Windows 10 release information](https://learn.microsoft.com/windows/release-health/release-information). The associated LTSC version is still in service, but that's covered by this article: [What's new in Windows 10 Enterprise LTSC 2019](https://learn.microsoft.com/windows/whats-new/ltsc/whats-new-windows-10-2019). That article also mentions [Web sign-in to Windows 10](https://learn.microsoft.com/windows/whats-new/ltsc/whats-new-windows-10-2019#web-sign-in-to-windows-10) without any mention of preview.
We've had much discussion about whether to keep those "what's new" articles for versions that are end of service like 1809, and the outcome was to keep the published, but they shouldn't be linked in the TOC. We do have some work planned for some additional cleanup, which may help this article be less discoverable.
I'm closing this feedback.

**Comment by aczechowski** [comment]
One additional point, articles like this for end of service versions is using the `ROBOTS: NOINDEX` metadata, so it should not be easily discoverable from internet search engines. If it is, or you found the link via another page, please let me know.
