### ISSUE TITLE
Screenshot lightbox code broken

### ISSUE THREAD

**Issue by AdmiralTolwyn** [MicrosoftDocs/windows-itpro-docs#11311]
Under "Monitor with Update Compliance" the lightbox code is broken and does not display the screenshot correctly:

`[[DO status](https://learn.microsoft.com/en-us/windows/deployment/do/images/uc_workspace_do_status.png)](images/UC_workspace_DO_status.png#lightbox)`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e39e363-99f3-a517-ef03-c4f177790551
* Version Independent ID: 6e39e363-99f3-a517-ef03-c4f177790551
* Content: [Set up Delivery Optimization - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/do/waas-delivery-optimization-setup)
* Content Source: [windows/deployment/do/waas-delivery-optimization-setup.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/do/waas-delivery-optimization-setup.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @carmenF
* Microsoft Alias: **carmenf**

**Comment by aczechowski** [comment]
Thanks @AdmiralTolwyn for catching that. @cmknox has an open PR in our private repo (https://github.com/MicrosoftDocs/windows-docs-pr/pull/7764) to make some changes to this article and others, so I injected a quick fix for that graphic. This issue will automatically close when that PR merges (although I don't have a specific timeline right now).
