### ISSUE TITLE
There is a missing option in this page for Enhanced SmartScreen features

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/windows-itpro-docs#11322]
Enhanced SmartScreen has a 5th feature that's not mentioned in this page. it's called `Capture Threat Window`. available in Group Policy and requires at least Windows 11 22H2:

![image](https://user-images.githubusercontent.com/118815227/216929200-483a3b27-737e-40e9-968b-dde6ef34dfb2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22e6cac6-7f29-c1d9-9619-667d253d2956
* Version Independent ID: 22e6cac6-7f29-c1d9-9619-667d253d2956
* Content: [Enhanced Phishing Protection in Microsoft Defender SmartScreen](https://learn.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/phishing-protection-microsoft-defender-smartscreen?tabs=intune)
* Content Source: [windows/security/threat-protection/microsoft-defender-smartscreen/phishing-protection-microsoft-defender-smartscreen.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-smartscreen/phishing-protection-microsoft-defender-smartscreen.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by msbemba** [comment]
@HotCakeX Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11356

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by HotCakeX** [comment]
@msbemba Thank you!

**Comment by paolomatarazzo** [comment]
this is still in preview, targeted for September 23. Closing the issue.

**Comment by HotCakeX** [comment]
Just wanted to update the issue to mention that this setting is now called Automatic Date Collection and is now available in the document in the CSP section only:
https://learn.microsoft.com/en-us/windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/enhanced-phishing-protection?tabs=csp
