### ISSUE TITLE
CreatorProcess instead of ParentProcess? 

### ISSUE THREAD

**Issue by rstanilewicz** [MicrosoftDocs/windows-itpro-docs#11326]
Is "CreatorProcess" (mentioned in the article) the same as "ParentProcess"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5eca37ef-510b-52ec-ed07-2fb4a2d307dc
* Version Independent ID: c4977b85-a93a-119d-3010-b6148c3421f0
* Content: [4688(S) A new process has been created. (Windows 10)](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4688)
* Content Source: [windows/security/threat-protection/auditing/event-4688.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4688.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by msbemba** [comment]
@rstanilewicz Thank you for your feedback. You are correct, The creator process is the same as the Parent process found in XML,

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @rstanilewicz Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
