### ISSUE TITLE
Please explain further on "./Device/Vendor/MSFT/Policy/Config/Defender/AllowScanningNetworkFiles"

### ISSUE THREAD

**Issue by diecknet** [MicrosoftDocs/windows-itpro-docs#11332]
The section "AllowScanningNetworkFiles" explains the setting "./Device/Vendor/MSFT/Policy/Config/Defender/AllowScanningNetworkFiles".
Currently the doc states:

> This policy setting allows you to configure scanning for network files. It is recommended that you do not enable this setting.
> - If you enable this setting, network files will be scanned.
> - If you disable or do not configure this setting, network files will not be scanned.

I would like to see these improvements:
1. What are Network files in this context?
2. Under what circumstances would Defender scan these network files?
3. Explanation **why** it is not recommended to enable this setting

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66b1ab2e-1964-5580-7c99-4bd4cd480075
* Version Independent ID: f7b5da46-04cb-3501-65fa-870a3c6f09b8
* Content: [Defender Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender?WT.mc_id=Portal-fx)
* Content Source: [windows/client-management/mdm/policy-csp-defender.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-defender.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by diecknet** [comment]
@vinaypamnani-msft is it really correct, that the recommendation changed from
> It is recommended that you do not enable this setting.
to
> It is recommended to enable this setting.
?

**Comment by vinaypamnani-msft** [comment]
@diecknet Yes, https://github.com/MicrosoftDocs/windows-itpro-docs/issues/11313 has some additional information about this policy.
