### ISSUE TITLE
Excluded Cloud Apps are configured in Conditional Access policies, not in a compliance policy

### ISSUE THREAD

**Issue by mchaudoir** [MicrosoftDocs/windows-itpro-docs#11335]
Excluded Cloud Apps are configured in Conditional Access policies, not in a compliance policy.

Please note the suggested update below

<<<<<<<<<<<<<<<<<<<<<< updated >>>>>>>>>>>>>>>>>>>>>

Note

Organizations that use the Subscription Activation feature to enable users to upgrade from one version of Windows to another and use Conditional Access policies to control access need to exclude the [Universal Store Service APIs and Web Application, AppID 45a330b1-b1ec-4cc1-9161-9f03992aa49f](https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/verify-first-party-apps-sign-in#application-ids-of-commonly-used-microsoft-applications), from their conditional access policies using Select Excluded Cloud Apps. For more information about configuring exclusions in Conditional Access policies, see [Application exclusions](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-policy-all-users-mfa#application-exclusions).

<<<<<<<<<<<<<<<<<<<<<  original >>>>>>>>>>>>>>>>>>>>>>>>>>

Note

Organizations that use the Subscription Activation feature to enable users to upgrade from one version of Windows to another and use Conditional Access policies to control access need to exclude the [Universal Store Service APIs and Web Application, AppID 45a330b1-b1ec-4cc1-9161-9f03992aa49f](https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/verify-first-party-apps-sign-in#application-ids-of-commonly-used-microsoft-applications), from their device compliance policy using Select Excluded Cloud Apps. For more information about configuring exclusions in Conditional Access policies, see [Application exclusions](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-policy-all-users-mfa#application-exclusions).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6443e532-640d-81c0-8215-b711bd1977d4
* Version Independent ID: fc504984-91d7-b586-04ec-4c751fb48998
* Content: [Windows subscription activation - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **windows-client**
* Technology: **itpro-fundamentals**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by msbemba** [comment]
@mchaudoir Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11350

Once the author approves, the changes will be live.

Thanks
Sri
