### ISSUE TITLE
Additional proxy URL

### ISSUE THREAD

**Issue by kistersr** [MicrosoftDocs/windows-itpro-docs#1133]
We also had to enable the *.s-microsoft.com URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 651b0b21-e639-2814-ebc6-94303a00ca2d
* Version Independent ID: 4587f785-d841-fd0e-7ec6-7ad895a0d4a7
* Content: [Prerequisites for Microsoft Store for Business and Education (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/prerequisites-microsoft-store-for-business)
* Content Source: [store-for-business/prerequisites-microsoft-store-for-business.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/prerequisites-microsoft-store-for-business.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by nenonix** [comment]
@kistersr I will have to confirm this before changing the content. Please assist me with any additional information you can supply and notes on how the content should be edited. Thank you for the feedback, much appreciated.

**Comment by TrudyHa** [comment]
@kistersr  Thanks for the feedback. I'll double check with our engineering org if this applies to all customers.
