### ISSUE TITLE
Documentation Links

### ISSUE THREAD

**Issue by ariendg** [MicrosoftDocs/windows-itpro-docs#1134]
Links to the documentation on the top are no longer working.
e.g. https://go.microsoft.com/fwlink/p/?LinkId=80347
This LinkId is beeing used in more articles like MBAM and older DaRT versions (https://www.google.com/search?q=https%3A%2F%2Fgo.microsoft.com%2Ffwlink%2Fp%2F%3FLinkId%3D80347)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2435ab4a-ddf7-d26d-d362-d7de3ff13b64
* Version Independent ID: c6354c18-4e1d-15aa-13c2-0c1dc3ce63b2
* Content: [Getting Started with DaRT 10](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/dart-v10/getting-started-with-dart-10)
* Content Source: [mdop/dart-v10/getting-started-with-dart-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/dart-v10/getting-started-with-dart-10.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by jdeckerms** [comment]
@ariendg Thanks for pointing this out, we'll get it fixed.
