### ISSUE TITLE
No signature block on PowerShell script

### ISSUE THREAD

**Issue by gdukevt** [MicrosoftDocs/windows-itpro-docs#11347]
the final three lines are: 

# SIG # Begin signature block
## REPLACE
# SIG # End signature block

I think someone didn't generate a signature.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c12e9c4a-af05-9ecd-a791-ac89aa43787c
* Version Independent ID: 76517523-a960-c5fb-ce76-2c3efe642f37
* Content: [Windows Defender Device Guard and Windows Defender Credential Guard hardware readiness tool](https://learn.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg-readiness-tool?source=recommendations)
* Content Source: [windows/security/identity-protection/credential-guard/dg-readiness-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/dg-readiness-tool.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Thank you for letting us know, @gdukevt! The tool has been deprecated. The article and all its references have been removed.
