### ISSUE TITLE
SeDelegateSessionUserImpersonatePrivilege is not linked

### ISSUE THREAD

**Issue by archeon1004** [MicrosoftDocs/windows-itpro-docs#11348]
Hello,

On the document there is mentioned new SeDelegateSessionUserImpersonatePrivilege user rights assignment called "[Obtain an impersonation token for another user in the same session](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/impersonate-a-client-after-authentication)" although clicking on the link is redirecting to https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/impersonate-a-client-after-authentication which is a different privilege. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7de1fb45-91eb-f37f-8106-81bf82a5602e
* Version Independent ID: 1c765989-4c50-4b89-83fe-a8625f0f9fd5
* Content: [User Rights Assignment (Windows 10)](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-rights-assignment)
* Content Source: [windows/security/threat-protection/security-policy-settings/user-rights-assignment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/user-rights-assignment.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @archeon1004 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
