### ISSUE TITLE
Domain Controller Requirements Conflicting with other documentation

### ISSUE THREAD

**Issue by ceasley112** [MicrosoftDocs/windows-itpro-docs#11358]
This article indicates Cloud Kerberos Trust does not have a Windows Server version requirement for domain controllers, while other documentation located:
https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust?tabs=intune#prerequisites

and

https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-authentication#hybrid-azure-ad-join-authentication-using-azure-ad-kerberos-cloud-kerberos-trust

seem to indicate a DC running Windows Server 2016 or newer is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87e5f5f1-16cf-57e2-bdfc-b090d90437b1
* Version Independent ID: 1662c47f-12cb-147d-25f0-dee98b6c7722
* Content: [Windows Hello for Business Deployment Prerequisite Overview](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-identity-verification.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-identity-verification.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by ceasley112** [comment]
This is in reference to https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification

**Comment by paolomatarazzo** [comment]
Hello @ceasley112 and thank you for the feedback. The link you provided has in the header the following "applies to:"

<img width="601" alt="image" src="https://user-images.githubusercontent.com/74918781/220673702-62f06958-ba04-4848-a379-25d79482c11d.png">

and the table has recently been updated with the following:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/74918781/220673968-5cb82671-3b1c-4305-8433-5a9eeec93ee6.png">

This is to avoid maintaining the table when an OS falls out of support. Hopefully this clarifies.
