### ISSUE TITLE
>>>  [Device Installation Restrictions Policy Check] >>>  Section start 2018/11/15 12:26:41.659 <<<  Section end 2023/11/15 12:26:41.751 <<<  [status: SUCCESS]

### ISSUE THREAD

**Issue by Afiq186** [MicrosoftDocs/windows-itpro-docs#11357]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c30e8535-b5d1-da85-117d-bcfd78c7e826
* Version Independent ID: 6189b9b2-f3ff-8ad0-1963-66c93bb061b1
* deviceinstallation.md](https://github.com/MicrosoftDocs/device-itpro-docs/blob/public/device/client-management/mdm/policy-csp-deviceinstallation.md)
* Product: **Device-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
@Afiq186 Can you provide more details about this issue? I'm closing this as not actionable at the moment.
