### ISSUE TITLE
Provision .lnk files using Windows Configuration Designer - section is wrong

### ISSUE THREAD

**Issue by JoergWu** [MicrosoftDocs/windows-itpro-docs#1135]
I tried to add the LNK files under the commandfiles section. I used a modified IE explore.lnk. This expands the commandfiles box after adding to the full path of the IE explorer.exe. So you can not simply add LNK files this way. I have added the LNK file to a zip file. And do some copy actions afterwards in a batch file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78038d67-04a1-f4ae-6a69-98e157688a31
* Version Independent ID: c86b4460-e8be-8537-a6c8-3cb094ef14a3
* Content: [Create a Windows 10 kiosk that runs multiple apps (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps#lnk-files)
* Content Source: [windows/configuration/lock-down-windows-10-to-specific-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/lock-down-windows-10-to-specific-apps.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@JoergWu You're right, the process isn't working correctly. I've asked the Windows Configuration Designer team to investigate, and I'll let you know what I find out.

**Comment by JoergWu** [comment]
Hi Jeanie, I found another working way. Do the copy stuff to the right places with PowerShell and import the PPKG with the new PowerShell command Add-ProvisioningPackage  this also allows you to get a very comprehensive logging. Have not yet found a better way to get logs. As regular provisioning package logs creating with WindowsPerformanceRecorder is very icky and you are looking for a needle in the haystack.

**Comment by jdeckerms** [comment]
@JoergWu Good tip for logging.

The team found that, while using Browse to select the .lnk file behaved oddly as you reported, they were able to paste the path file and have it work.
