### ISSUE TITLE
Error in the document: Unavailable path is specified

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/windows-itpro-docs#11361]
The document has these code blocks:

```PowerShell
$PolicyPath=$env:userprofile+"\Desktop\"
$PolicyName= "Lamna_FullyManagedClients_Audit"
$LamnaPolicy=$PolicyPath+$PolicyName+".xml"
$ConfigMgrPolicy=$env:windir+"\CCM\DeviceGuard\MergedPolicy_Audit_ISG.xml"

```

```PowerShell
cp $ConfigMgrPolicy $LamnaPolicy
```

<br>

The path mentioned there does not exist on Windows 11 22H2 and above (including insider builds)

<br>

This is the output of running those commands:

```PowerShell
PS C:\Windows\system32> $PolicyPath=$env:userprofile+"\Desktop\"
PS C:\Windows\system32> $PolicyName= "Lamna_FullyManagedClients_Audit"
PS C:\Windows\system32> $LamnaPolicy=$PolicyPath+$PolicyName+".xml"
PS C:\Windows\system32> $ConfigMgrPolicy=$env:windir+"\CCM\DeviceGuard\MergedPolicy_Audit_ISG.xml"
PS C:\Windows\system32> cp $ConfigMgrPolicy $LamnaPolicy
cp : Cannot find path 'C:\Windows\CCM\DeviceGuard\MergedPolicy_Audit_ISG.xml' because it does not exist.
At line:1 char:1
+ cp $ConfigMgrPolicy $LamnaPolicy
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Windows\CCM\...y_Audit_ISG.xml:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

PS C:\Windows\system32>
```

<br>

There is no `CCM` directory in `C:\Windows\`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3135ceea-f682-4667-6b91-4f30ac30eca7
* Version Independent ID: 4bfb7b1e-bd5c-798a-cf8c-409adea2efa9
* Content: [Create a WDAC policy for fully managed devices (Windows)](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/create-wdac-policy-for-fully-managed-devices)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/create-wdac-policy-for-fully-managed-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/create-wdac-policy-for-fully-managed-devices.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @jsuther1974
* Microsoft Alias: **vinpa**

**Comment by jsuther1974** [comment]
As the topic describes, this is for a device that is managed by Configuration Manager. The CCM directory is Configuration Manager's install folder.

**Comment by HotCakeX** [comment]
Thank you for the explanation!
