### ISSUE TITLE
Changes introduced in KB5024351

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/windows-itpro-docs#11364]
Hi, the changes introduced in https://support.microsoft.com/en-us/topic/kb5024351-removal-of-windows-edition-checks-for-applocker-e3a763c9-6a3e-4d9c-8623-0ffe69046470 removed the difference for editions in Pro and Enterprise for deployment methods. This document is referenced by Product Terms, so can we get this updated or mentioned there? Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c5b2cd1-331e-4b0f-cf2f-b6e35499c8b0
* Version Independent ID: 9a1a48ba-1174-9cf3-2a28-e53873409e7f
* Content: [Windows Defender Application Control feature availability](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/feature-availability)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/feature-availability.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/feature-availability.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @jgeurten
* Microsoft Alias: **jogeurte**

**Comment by jgeurten** [comment]
Hi, these changes have already been made and the update should be published shortly. Thanks!

**Comment by aczechowski** [comment]
Closing based on Jordan's response

**Comment by yumetodo** [comment]
ref: https://github.com/MicrosoftDocs/windows-itpro-docs/commit/a18b4700c79899290051fa7a9b6213877fa0e74e
