### ISSUE TITLE
New Update Making Games Stutter In Fps

### ISSUE THREAD

**Issue by floofycatto** [MicrosoftDocs/windows-itpro-docs#11367]
I've recently discovered an issue that translates across all of my games, the issue being ever since I installed the last two or so updates I've been noticing 5 second long fps stutters, my frames drop to about 5 for the seconds and then it goes back to a solid 60+, 30 minutes later rinse and repeat,

info:
I use nvidia geforce drivers,
processor: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz   2.30 GHz
graphics card: Nvidia Geforce GTX 1050

**Comment by HotCakeX** [comment]
This GitHub repository is only for Windows IT Pro documentation issues.

To submit your game related feedback, you can use these official methods and resources:

* [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332)
* [How to submit actionable game performance feedback](https://answers.microsoft.com/en-us/windows/forum/all/how-to-submit-actionable-game-performance-feedback/a8cfcd5b-194c-41b4-9df0-631426afec2e)
* [Understand feedback categories and diagnostics](https://learn.microsoft.com/en-us/windows-insider/feedback-categories)
