### ISSUE TITLE
Wrong info in the description of the example Base Policies table

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/windows-itpro-docs#11363]
In here:

AllowMicrosoft.xml | This example policy is available in audit mode. It includes the rules from DefaultWindows and adds rules to trust apps signed by the Microsoft product root certificate.
-- | --

It says "This example policy is available in audit mode"

but in fact, it isn't available in audit mode, it's available in **enforced mode**. There is no

```XML
<Rule>
<Option>Enabled:Audit Mode</Option>
</Rule>
```

in the `AllowMicrosoft.xml` file located in `C:\Windows\schemas\CodeIntegrity\ExamplePolicies\AllowMicrosoft.xml` in Windows 11 22H2 **or** Windows 11 insider dev build.

<br>

The document also mentions this path:

```
%ProgramFiles%\WindowsApps\Microsoft.WDAC.WDACWizard*\AllowMicrosoft.xml
```

but it's inaccessible due to Windows built-in file/folder permissions. I already have WDAC Policy Wizard latest version installed and can't access that path. I'm not sure why that path is even mentioned in there if we can't access it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b77ce817-c051-7617-7520-6f9a47845859
* Version Independent ID: 84150e0c-b9b8-9194-857c-eadd54ec7bcf
* Content: [Example Windows Defender Application Control (WDAC) base policies (Windows)](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/example-wdac-base-policies)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/example-wdac-base-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/example-wdac-base-policies.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @jsuther1974
* Microsoft Alias: **vinpa**

**Comment by yogkumgit** [comment]
@jsuther1974
