### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#11360]
The documentation of Offline Files CSP seems to miss entirely the various elements defined in the ADMX.
For example, Pol_PurgeAtLogoff requires the element "Lbl_PurgeOnlyAutoCachedFiles" with a boolean value of true or false.

I have not checked all the other ADMX CPS's. If it is normal that the documentation does not include elements, then it would be useful to give a reference to the ADMX itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 623ec73f-d591-1e43-08cf-e5aff51df10e
* Version Independent ID: 0407ef30-2ede-00a2-4677-c36c4a66433b
* Content: [ADMX_OfflineFiles Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-admx-offlinefiles#pol_purgeatlogoff)
* Content Source: [windows/client-management/mdm/policy-csp-admx-offlinefiles.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-admx-offlinefiles.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
@Air-Git Not all ADMX elements are exposed in the CSPs, but wherever applicable the ADMX reference is listed in a table under the policy node description. We recently automated the CSP articles, so any previously missing ADMX references should now be listed in the articles. I'll go ahead and close this issue as there's nothing actionable at the moment.
