### ISSUE TITLE
Missing Policy in Windows 10 22H2 environment

### ISSUE THREAD

**Issue by CanastraRF** [MicrosoftDocs/windows-itpro-docs#11375]
[Enter feedback here]

Hi
You describe a new policy.
I can't find this policy in our Windows 10 22H2 environment.
We can I get this policy template (admx, adml)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e5e70e7-fd3f-bbb3-9c24-9f2552f94d6d
* Version Independent ID: 0e5e70e7-fd3f-bbb3-9c24-9f2552f94d6d
* Content: [Use Windows Update for Business and Windows Server Update Services (WSUS) together - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/wufb-wsus)
* Content Source: [windows/deployment/update/wufb-wsus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/wufb-wsus.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @CanastraRF for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time. The policy on my Win11 device says that same as in the doc, that it's available on Windows 10, version 2004 and above. And we don't publish the ADMX files as far as I know. You can look at the CSP documentation, which has more details on the policies: https://learn.microsoft.com/windows/client-management/mdm/policy-csp-update#setpolicydrivenupdatesourcefordriverupdates
