### ISSUE TITLE
Devices in manually overridden rings

### ISSUE THREAD

**Issue by VigneshMitsume** [MicrosoftDocs/windows-itpro-docs#11378]
If I manually reassign a device between groups (say, from first to broad) will it be reassesssed and possibly moved back during the Autopatch ring assement later on? Covering this part either in this page or in FAQ's or in the flow diagrams will help customer understand much clear picture.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e020994f-a009-87f6-6761-097218d01813
* Version Independent ID: e020994f-a009-87f6-6761-097218d01813
* Content: [Software update management - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/windows-autopatch/operate/windows-autopatch-update-management#moving-devices-in-between-deployment-rings)
* Content Source: [windows/deployment/windows-autopatch/operate/windows-autopatch-update-management.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopatch/operate/windows-autopatch-update-management.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @tiaraquan
* Microsoft Alias: **tiaraquan**

**Comment by aczechowski** [comment]
I know this is for a different article, but looks to be essentially the same feedback as #11379, so I'm closing this issue as a duplicate
