### ISSUE TITLE
Regarding WordQ

### ISSUE THREAD

**Issue by ItsWillJLC** [MicrosoftDocs/windows-itpro-docs#11382]
Hi team, 

I must apologize, I am not the most acquainted with Git Hub.

My name is Will and I'm the Marketing Specialist at Quillsoft, the Creators of WordQ. I noticed that Math Et Mots (one of our resellers and partners) had submitted WordQ for approval on SE. Does that mean that our WordQ SKU is SE approved as well? Is it possible that we could be listed as a vendor alongside Math Et Mots as we sell the product in different markets?

Thank you so much!

Will

**Comment by paolomatarazzo** [comment]
Hello Will,
please fill out the form here https://aka.ms/eduapprequest and somebody will get in touch with you.
