### ISSUE TITLE
Typo in title

### ISSUE THREAD

**Issue by chbreakthrough** [MicrosoftDocs/windows-itpro-docs#1138]
Typo in title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ddde2ac-52eb-ddcf-cb89-bcbda8ab925c
* Version Independent ID: a4c41bfe-8a6b-cf05-6875-09e85aa1736e
* Content: [Find machine information by interal IP API](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/find-machine-info-by-ip-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/find-machine-info-by-ip-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/find-machine-info-by-ip-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by shortpatti** [comment]
@chbreakthrough, Thank you for pointing it out and have since fixed it.
