### ISSUE TITLE
incorrect GPO registry entry for "Enable features introduced via servicing that are off by default"

### ISSUE THREAD

**Issue by mcfand** [MicrosoftDocs/windows-itpro-docs#11386]
GPO registry entry for: "Enable features introduced via servicing that are off by default" @ https://learn.microsoft.com/en-us/windows/deployment/update/waas-configure-wufb#enable-features-introduced-via-servicing-that-are-off-by-default is incorrect. the GPO registry value is not "ExcludeWUDriversInQualityUpdate". It appears that the table above was copied but only the MDM entry updated.

the correct GPO value is referenced in a later section https://learn.microsoft.com/en-us/windows/deployment/update/waas-configure-wufb#summary-mdm-and-group-policy-settings-for-windows-10-version-1703-and-later

**Comment by vinaypamnani-msft** [comment]
Thanks @mcfand for pointing this out. The registry value has been corrected and changes will be live later today.
