### ISSUE TITLE
Flairs of "MBAM Client not Supported" Should be Added

### ISSUE THREAD

**Issue by nascar3000** [MicrosoftDocs/windows-itpro-docs#11381]
There is no information about how to start encryption on server SKU, customers trying to install MBAM Client to server OS.
Please add guide to activate bitlocker after enabling features and add "not supported" notice for MBAM/ SCCM client on Server SKU.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71d85a90-230f-84b0-a024-88a8da36825d
* Version Independent ID: bf2db39e-16b3-f5a8-af07-91ed301a5ca7
* Content: [BitLocker How to deploy on Windows Server 2012 and later](https://learn.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-how-to-deploy-on-windows-server)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-how-to-deploy-on-windows-server.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-how-to-deploy-on-windows-server.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
I am not sure what you are ask is. This is not MBAM or Configuration Manager documentation. This is BitLocker documentation. If you want supportability statements regarding MBAM and Configuration Manager, please consult their respective documentation. In general, we do not document what is not supported - that list is infinite. Instead, we document what is supported. If you do not specifically find a statement that something is supported, then you can assume it is not supported.

With that said, both the MBAM and Configuration Manager BitLocker Management (BLM) do call out that they do not support server OSes, at least not for the management of BitLocker piece. But again, that is in their documentation where it belongs.
