### ISSUE TITLE
"Working with Quick Assist" needs to be updated

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/windows-itpro-docs#11380]
"5. The helper receives a dialog offering the opportunity to take full control of the device or just view its screen. After they choose an option, the helper selects Continue."

Request control is now a button AFTER connection, not a dialog BEFORE connection.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bfcd14cd-f887-660f-8a4c-465b3495e90e
* Version Independent ID: 121eead7-eb87-f033-024a-f688866c58a0
* Content: [Use Quick Assist to help users - Windows Client Management](https://learn.microsoft.com/en-gb/windows/client-management/quick-assist)
* Content Source: [windows/client-management/quick-assist.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/quick-assist.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by BR77BE** [comment]
You just reworded it instead of bringing it up to date. Now item 4 is incorrect"

"4.The helper is prompted to select View Only or Full Control."

There is now no such prompt. Please test it.

**Comment by vinaypamnani-msft** [comment]
@BR77BE The PR was merged, which auto-closed this issue but the changes aren't live yet so you reviewed the same content that had wrong steps to begin with, they should be live within a couple of hours :)

**Comment by vinaypamnani-msft** [comment]
@BR77BE, I did miss updating the new steps in the "How it works" section though, I'll update those shortly too, please check again tomorrow or later this evening and see if you have any further feedback.

**Comment by BR77BE** [comment]
OK, will do. Thanks.

**Comment by BR77BE** [comment]
Better now, thanks.
