### ISSUE TITLE
Missing reference to NTLM blocked error

### ISSUE THREAD

**Issue by walkerreuben** [MicrosoftDocs/windows-itpro-docs#11384]
Error message includes the following snippet:
Failure Information:
	Failure Reason:		An Error occured during Logon.
	Status:			0x80090302
	Sub Status:		0xC0000418

Based on the following page, this sub status refers to STATUS_NTLM_BLOCKED - The authentication failed because NTLM was blocked.
https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55

This would be useful information to contain in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80307c25-b809-e9b8-bab2-d37d3de7e920
* Version Independent ID: 24c32be1-2fc3-f22f-7e6c-da4049bf8458
* Content: [4625(F) An account failed to log on. (Windows 10)](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4625)
* Content Source: [windows/security/threat-protection/auditing/event-4625.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4625.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
Thanks for raising this issue @walkerreuben. I've added the link in the article.
