### ISSUE TITLE
Dated video

### ISSUE THREAD

**Issue by tbiles** [MicrosoftDocs/windows-itpro-docs#11399]
Video is helpful but quite dated.  Any updates in the last 7 years that would be helpful to know?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3deb045-565e-169b-ecd4-6f0f07c966e4
* Version Independent ID: 1bd84f68-4820-4d11-aafc-da1657bddc80
* Content: [Security baselines guide](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-security-configuration-framework/windows-security-baselines)
* Content Source: [windows/security/threat-protection/windows-security-configuration-framework/windows-security-baselines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-security-configuration-framework/windows-security-baselines.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @tbiles for the feedback. We're not aware of any updated video content. @jmunck do you know?

@yogkumgit - assigning to you. After a quick chat with Vinay, let's remove the embedded video, but add a link to it in the "see also" section. As noted, it's still helpful. Unless Rick has any additional suggestions to add.

**Comment by jmunck** [comment]
Hi @aczechowski unfortunately we don't have any other videos. I'd be happy to work with folks on some though!

**Comment by msbemba** [comment]
@tbiles Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11406

Once the author approves, the changes will be live.

Thanks
Sri
