### ISSUE TITLE
Editing .rdp file needed for our environment

### ISSUE THREAD

**Issue by W00tFoo** [MicrosoftDocs/windows-itpro-docs#11393]
We have on-prem AD, and most of our PCs are Hybrid Azure AD Joined. However, for PCs that are just Azure AD Joined, RDP did not work until this line was added to the .rdp file:

enablerdsaadauth:i:1

Then, a Modern Auth window was presented, and auth worked. Otherwise, an incorrect username or password message was presented. 

This article should be updated to reflect that, or link to another article that indicates this option.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows) - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
Thanks @W00tFoo. I am already working on some much needed updates to this article, including the use of `enablerdsaadauth` property. The changes should be live next week.

**Comment by vinaypamnani-msft** [comment]
@W00tFoo I've published the changes, they should be live in a couple of hours.
