### ISSUE TITLE
Please incorporate older FAQs too

### ISSUE THREAD

**Issue by aakash-shah** [MicrosoftDocs/windows-itpro-docs#11394]
A lot of good documentation on older pages are not in the current FAQs. Please consider adding the older FAQs and other technical information either into this current page, or a more appropriate currently supported/monitored page.

Some of the older pages with good information include:
https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-7/ee449438(v=ws.10)?redirectedfrom=MSDN

For instance I don't appear to this see question answered anywhere in the newer documentation:
[How are the PIN and TPM used to derive the volume master key?](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-7/ee449438(v=ws.10)?redirectedfrom=MSDN#how-are-the-pin-and-tpm-used-to-derive-the-volume-master-key)

This page has an architecture diagram that I have not found elsewhere on the MS site either:
https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc732774(v=ws.10)?redirectedfrom=MSDN#bitlocker-architecture

This would help provide more detailed technical information for questions that may arise.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: feb93192-b78b-a16b-c174-f83e024aa4c4
* Version Independent ID: d7dd6ccd-f984-48d0-49ff-2f5383001fd9
* Content: [BitLocker Key Management FAQ (Windows 10)](https://learn.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-key-management-faq)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-key-management-faq.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-key-management-faq.yml)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
We have opened an internal task to look into incorporating the older valid FAQs into the current BitLocker docs.
