### ISSUE TITLE
Typo on this web page.

### ISSUE THREAD

**Issue by FecalFornicator** [MicrosoftDocs/windows-itpro-docs#11402]
The typo is shown in the attached image.

---
#### Document Details
![typo](https://user-images.githubusercontent.com/61040606/224982703-98b85935-d150-45c7-a340-edebaf42110b.PNG)

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5476099c-9d70-97df-8ee6-bc442605cfbd
* Version Independent ID: 49ca0628-bd88-e05b-b705-3b361b57512d
* Content: [BitLocker Group Policy settings (Windows 10)](https://learn.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings#disable-new-dma-devices-when-this-computer-is-locked)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-group-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Error has been corrected.
