### ISSUE TITLE
Typo in heading

### ISSUE THREAD

**Issue by shagtoth** [MicrosoftDocs/windows-itpro-docs#11403]
Cryprtographic algorithms

Should be ...

Cryptographic algorithms

(admin edit: add article metadata for proper linking/tracking)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e93f07bf-c0dd-dd83-d7bf-8562e7f197c3
* Version Independent ID: a6c44187-8ff1-6519-5291-146b4c1bf46c
* Content: [Federal Information Processing Standard (FIPS) 140 Validation](https://learn.microsoft.com/en-us/windows/security/threat-protection/fips-140-validation)
* Content Source: [windows/security/threat-protection/fips-140-validation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/fips-140-validation.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by yogkumgit** [comment]
@shagtoth Please indicate which document you are referring to. Thanks

**Comment by aczechowski** [comment]
Thanks @shagtoth for catching that, I found it in the https://learn.microsoft.com/en-us/windows/security/threat-protection/fips-140-validation article. I know @paolomatarazzo is working with PMs on revamping it, but that's a work in progress. Paolo - should community contributors fix this typo for now? What do you suggest?

**Comment by paolomatarazzo** [comment]
Thank you @shagtoth 
@aczechowski  not at this time, hoefully the revamped article will be live soon.
