### ISSUE TITLE
MDT is not supported with Windows 11

### ISSUE THREAD

**Issue by akiyoshi** [MicrosoftDocs/windows-itpro-docs#11410]
Since MDT is not supported with Windows 11, it should not be reccomennded as a alternative.

https://learn.microsoft.com/en-us/mem/configmgr/mdt/known-issues

It would better to add Intune as a alternative and remove MDT.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d85db01-954d-600d-3e5d-8f2d719d6068
* Version Independent ID: 6a0203c2-b269-32c3-bd68-926cc7729090
* Content: [Windows Deployment Services (WDS) boot.wim support - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/wds-boot-support?source=docs)
* Content Source: [windows/deployment/wds-boot-support.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/wds-boot-support.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
@akiyoshi Sorry I am not seeing where we recommend MDT at all for Windows 11 in this article. Also, this being MDT documentation, it wouldn't make sense to remove MDT since the documentation is regarding MDT.

**Comment by akiyoshi** [comment]
@frankroj 
Sorry for the confusion. I’d like to feedback to the docs below.
https://learn.microsoft.com/en-us/windows/deployment/wds-boot-support?source=docs

I’d like to suggest that MDT is no longer an alternative for WDS.
Windows 10 1809 or lator and Windows 11 are not supported with MDT.
In other words, MDT is not suitable for modern Windows. 
It would be better to change the following sentence from MDT to Intune.

"Alternatives to WDS, such as Microsoft Configuration Manager and Microsoft Deployment Toolkit (MDT) provide a better, more flexible, and feature-rich experience for deploying Windows images."
Would you re open this ticket and consider update the docs?
I will create another issue if needed.

Thank you,

**Comment by frankroj** [comment]
Hello @akiyoshi. Yes, because that is in a different article and different repo, please open a new issue on that page. Thank you.
