### ISSUE TITLE
Suggestion for CITool: List the actively enforced WDAC policies on the system

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/windows-itpro-docs#11414]
The page currently suggests using this to list the actively enforced WDAC policies on the system:

```PowerShell
$wdacPolicies = (CiTool -lp -json | ConvertFrom-Json).Policies

# Check each policy's IsEnforced state and return only the enforced policies
foreach($wdacPolicy in $wdacPolicies ){

    if($wdacPolicy.IsEnforced)
    {
        Write-Host $wdacPolicy.FriendlyName
        Write-Host $wdacPolicy.PolicyID "`n"
    }
}
```
![image](https://user-images.githubusercontent.com/118815227/226100472-9928c9e3-2a8a-4770-a0db-236b6479fe48.png)

The problem is that it outputs strings.

My suggestion is to use this instead so that the output will be objects which can be used by other cmdlets, it's shorter, the output has better formatting and it does exactly the same thing.

```PowerShell
(CiTool -lp -json | ConvertFrom-Json).Policies | Where-Object {$_.IsEnforced -eq "True"} |
Select-Object -Property PolicyID,FriendlyName | Format-List
```

![image](https://user-images.githubusercontent.com/118815227/226100423-18a0762d-6f5e-4833-89ce-68f77983d975.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20079bf8-5e82-f16b-a849-5eb7254f4ce1
* Version Independent ID: 20079bf8-5e82-f16b-a849-5eb7254f4ce1
* Content: [Managing CI Policies and Tokens with CiTool](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/operations/citool-commands)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/operations/citool-commands.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/operations/citool-commands.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @valemieux
* Microsoft Alias: **jogeurte**

**Comment by AngelaMotherofDragons** [comment]
Hi @HotCakeX - 

Thank you for checking. I'm not an SME for this topic, so I've escalated your inquiry to the appropriate team.

**Comment by jgeurten** [comment]
Hi @HotCakeX, we edited the CiTool doc with your suggestion. The PR has been merged and should be published in the next day or so. 

Thanks, 
Jordan

**Comment by HotCakeX** [comment]
Oh, thank you very much!

**Comment by valemieux** [comment]
Hi @HotCakeX, 

The change you requested went live as of 10:30AM PST today, 3/28.  Thank you for your contribution!

https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/operations/citool-commands

Thanks,
Aaron

**Comment by HotCakeX** [comment]
@valemieux awesome, thank you!
