### ISSUE TITLE
incorrect documentation

### ISSUE THREAD

**Issue by ipavlina** [MicrosoftDocs/windows-itpro-docs#11418]
following the documentation for Intune Shared PC configuration profile on your page does not reflect the actual options in Intune-Devices-Windows-Configuration profile-Settings catalog-Shared PC. In your documentation there is 18 settings wheras in the Intune console there is only 14 options. I am specificaly looking for Sleep settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3329b98-7e66-aa67-d27e-d14471cf63b3
* Version Independent ID: e6c88589-b252-4e9c-6016-8b53154dce96
* Content: [SharedPC CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/sharedpc-csp)
* Content Source: [windows/client-management/mdm/sharedpc-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/sharedpc-csp.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**
![sleep timout](https://user-images.githubusercontent.com/128408874/226415723-c1a7306e-2f53-4c9c-b70d-a526a8fb6337.JPG)

**Comment by paolomatarazzo** [comment]
@ipavlina thank you for the feedback. If the missing settings are not exposed in the settings catalog, you will have to create a separate custom policy or a different profile type that contains the configuration you need.
