### ISSUE TITLE
A problem with the windows defender

### ISSUE THREAD

**Issue by LtePrince** [MicrosoftDocs/windows-itpro-docs#11426]
[Enter feedback here]
Recently, I helped my friend to reinstall the system. But I found that I can not find the windows defender in the settings.
![image](https://user-images.githubusercontent.com/84253913/228275856-984c04d9-d6a3-4e94-aa28-00eaafb13d74.png)
![image](https://user-images.githubusercontent.com/84253913/228275597-f98e06f1-69f6-492e-8c21-77d9f76b22c6.png)
I tried to find a solution from all kinds of website. Many people suggest that it can be solved by the command line.
However, the "Get-AppPackage Microsoft.SecHealthUI"command didn't work.
Then I found that the Windows11 System do not have the Microsoft.SecHealthUI folder. How can I solve it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 542f27b2-fc93-e90d-be8c-cb749b6dbcb2
* Version Independent ID: 8633dd0d-8ba8-8aba-a474-84dcf01e678f
* Content: [The Windows Security app](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-security-center/windows-defender-security-center)
* Content Source: [windows/security/threat-protection/windows-defender-security-center/windows-defender-security-center.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-security-center/windows-defender-security-center.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @LtePrince for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. As previously noted, there are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
