### ISSUE TITLE
"Connect-MsolService" does not work

### ISSUE THREAD

**Issue by tenebreux** [MicrosoftDocs/windows-itpro-docs#11427]
I do not have a PC.

Tried running the code on cloud shell.

the line "Connect-MsolService" does not work.

I get the error below:

Connect-MsolService: Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
Connect-MsolService: Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aab824fb-b795-518a-8d52-7490975ab5ac
* Version Independent ID: aab824fb-b795-518a-8d52-7490975ab5ac
* Content: [Configure federation between Google Workspace and Azure AD - Windows Education](https://learn.microsoft.com/en-us/education/windows/configure-aad-google-trust)
* Content Source: [education/windows/configure-aad-google-trust.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/education/windows/configure-aad-google-trust.md)
* Product: **windows-client**
* Technology: **itpro-edu**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aab824fb-b795-518a-8d52-7490975ab5ac
* Version Independent ID: aab824fb-b795-518a-8d52-7490975ab5ac
* Content: [Configure federation between Google Workspace and Azure AD - Windows Education](https://learn.microsoft.com/en-us/education/windows/configure-aad-google-trust)
* Content Source: [education/windows/configure-aad-google-trust.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/education/windows/configure-aad-google-trust.md)
* Product: **windows-client**
* Technology: **itpro-edu**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @tenebreux you need to run the commands from PowerShell. Please try from a Windows OS, using a VM perhaps

**Comment by tenebreux** [comment]
Hi Paolo,
Thanks for your help. Why doesn’t it work in cloud shell?
So let me get this right, without a windows machine, there is no other way
to make this work. Correct?

T.

**Comment by paolomatarazzo** [comment]
@tenebreux it looks that you can use get- and set-MgDomainFederationConfiguration cmd-lets instead

**Comment by tenebreux** [comment]
Please help me out bro. Why doesn’t it work on cloud terminal? Is there ANY
other thing I can try? It’s really important I get this to work.

**Comment by paolomatarazzo** [comment]
it's a legacy module and I think some of the dependencies are missing. I tried the new-MgDomainFederationConfiguration and it works just fine. The syntax is very similar to the old cmdlet. Have you tried the new command?
