### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mtmcgrew** [MicrosoftDocs/windows-itpro-docs#1142]
LastProccesedTimeUtc should read LastProcessedTimeUtc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b835bf35-1614-2d8d-13ab-176c6d839047
* Version Independent ID: ed4653f3-e393-dd42-5960-87888c08ba40
* Content: [Pull Windows Defender ATP alerts using REST API](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/pull-alerts-using-rest-api-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/pull-alerts-using-rest-api-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/pull-alerts-using-rest-api-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by andreabichsel** [comment]
Fixed--thank you!
