### ISSUE TITLE
eslamashour1

### ISSUE THREAD

**Issue by eslamashour1** [MicrosoftDocs/windows-itpro-docs#11438]
[مفتاح استرداد BitLocker AFEE0332-4617-4A2A-AAD0-BB07CE054E7C.TXT](https://github.com/MicrosoftDocs/windows-itpro-docs/files/11152305/BitLocker.AFEE0332-4617-4A2A-AAD0-BB07CE054E7C.TXT)

[اكتب ملاحظاتك هنا]

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ learn.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: bd2d1007-2cbb-94a6-18aa-a0b879262ab1
* Version Independent ID: 625d9906-0cb0-23eb-3a56-a84ad774d291
* Content: [Guidelines for choosing an app for assigned access - Configure Windows](https://learn.microsoft.com/ar-sa/windows/configuration/guidelines-for-assigned-access-app)
* Content Source: [windows/configuration/guidelines-for-assigned-access-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/guidelines-for-assigned-access-app.md)
* Product: **windows-client**
* Technology: **itpro-configure**
* GitHub Login: @lizgt2000
* Microsoft Alias: **lizlong**

**Comment by aczechowski** [comment]
Apologies for responding in English; I used an online tool to translate your note from Arabic. I'm not sure what the BitLocker recovery key information screen has to to do with the referenced article, so I'm assuming you're having an issue and need assistance (or perhaps this feedback was mistakenly filed). I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

If you have more information about your feedback on this article, please share and reopen this issue.
