### ISSUE TITLE
administrative tools

### ISSUE THREAD

**Issue by harshithareddy7956** [MicrosoftDocs/windows-itpro-docs#11449]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1faa451a-3db7-72fa-9745-b1a898d83f4a
* Version Independent ID: 3cd11526-a379-ba90-f619-777ee45330a3
* Content: [Windows Tools/Administrative Tools - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/administrative-tools-in-windows-10)
* Content Source: [windows/client-management/administrative-tools-in-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/administrative-tools-in-windows-10.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
@harshithareddy7956 Did you forget to add your feedback?

**Comment by aczechowski** [comment]
I'm assuming it's an accident, so closing. As Vinay noted, if you any specific feedback on this article, please reopen and clarify.
