### ISSUE TITLE
OSManagedAuthLevel 0x5 . Why?

### ISSUE THREAD

**Issue by lexios** [MicrosoftDocs/windows-itpro-docs#1144]
Thank you Justinha, I saw your amendment.

"A value of 5 means discard the Full TPM owner authorization for TPM 1.2 but keep it for TPM 2.0."

The question is, how was this value populated as 5 and why is the TPM owner auth stored in the registry by default?

On 1607, this was supposedly changed as per below:
https://docs.microsoft.com/en-us/windows/security/hardware-protection/tpm/change-the-tpm-owner-password

"Starting with Windows 10, version 1607, Windows will not retain the TPM owner password when provisioning the TPM. The password will be set to a random high entropy value and then discarded."

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @mypil,
it looks like the issue is a duplicate of issue #1075 (the same question was asked in the comments)
i think you can close it as #1075 is already closed
Thank you

**Comment by mypil** [comment]
@officedocsbot close
