### ISSUE TITLE
PCmover not free

### ISSUE THREAD

**Issue by tym0niasty** [MicrosoftDocs/windows-itpro-docs#11445]
The PCmover is not free:
![image](https://user-images.githubusercontent.com/113236151/231126274-6839c5a8-affd-4946-aae3-680cf1765bcd.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cde8580a-bd82-ebd2-3767-f3ee662a904e
* Version Independent ID: 94323219-e4ed-8761-723e-06be33c3b9cc
* Content: [User State Migration Tool (USMT) overview - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/usmt/usmt-overview)
* Content Source: [windows/deployment/usmt/usmt-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/usmt/usmt-overview.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by aczechowski** [comment]
Closing. As Frank noted, if you can clarify the issue, please describe and reopen.
