### ISSUE TITLE
VAMT still fails to create database using SQL Server Express

### ISSUE THREAD

**Issue by rmeadinc** [MicrosoftDocs/windows-itpro-docs#11444]
Latest VAMT on a fresh WS 2022 build. Fresh SQL Server Express install. Going through the guide, the step to have VAMT create its own database fails with "The specified database is not a valid VAMT database".  This happens if the VAMT is run as administrator or not. This also happens with the same account that installed SQL. 

Apparently the fix is TWO YEARS OLD, but the software/deployment is still broken:
https://www.reddit.com/r/sysadmin/comments/oypsd8/vamt_database_not_a_valid_vamt_database/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01910332-8f6f-c844-6594-d9da807492c5
* Version Independent ID: 13b107a6-b139-671d-d3bd-d53b2de74fdd
* Content: [Install VAMT (Windows 10) - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/volume-activation/install-vamt)
* Content Source: [windows/deployment/volume-activation/install-vamt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/volume-activation/install-vamt.md)
* Product: **windows-client**
* Technology: **itpro-fundamentals**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thanks @rmeadinc  for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
