### ISSUE TITLE
The Intune configuration steps provided in "Configure and provision Windows Hello for Business - cloud Kerberos trust" are not available in the AAD user login scenario.

### ISSUE THREAD

**Issue by RayXiao-ops** [MicrosoftDocs/windows-itpro-docs#11440]
When we configure cloud Kerberos trust for "Account Protection" + Custom Policy. They will be under different registry paths on the device side and will not work. UseCloudTrustForOnPremAuth under PassportForWork - Device. If we are logged in device as an AAD user, the settings configured in the "Account Protection" policy always appear under the user SID path, which makes cloud Kerberos trust ineffective.
Same for multiple test tenants.
![image](https://user-images.githubusercontent.com/129918500/229991823-d4731124-ed46-4a84-a05e-0af7faeb7574.png)
[https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust-provision.md](url)
[https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust-provision?tabs=intune](url)

(admin edit - adding article metadata for proper linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 046ca470-8477-5ff1-7021-ad34489ed592
* Version Independent ID: 046ca470-8477-5ff1-7021-ad34489ed592
* Content: [Windows Hello for Business cloud Kerberos trust clients configuration and enrollment](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust-provision?tabs=intune)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust-provision.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust-provision.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @RayXiao-ops and thank you for the feedback. Can you please clarify if you are targeting both policies to the same security groups? Also, are you targeting device or user groups? The article needs an update regardless, now that the policy is available in Settings catalog, I'd recommend that route.

**Comment by RayXiao-ops** [comment]
Hi @paolomatarazzo They deploy to the same group, I've tried device groups and user groups, both are the same for "Account Protection", the settings always appear under the user SID path.

**Comment by paolomatarazzo** [comment]
Thank you for letting me know. I will test and update the article accordingly. In the meantime, I'd suggest using the settings catalog
