### ISSUE TITLE
Inaccurate / wrong

### ISSUE THREAD

**Issue by alroe118** [MicrosoftDocs/windows-itpro-docs#11448]
1st the path given for the policy can't possibly exist, under computer configuration are only two items, Policies and Preferences. Next the article doesn't state that any extra templates are required so one would normally assume that you're recommending a change to something that is available by default. "Manage updates offered from Windows Server Update Service" is not visible even with most normal templates installed and active... so?

(admin edit: add article metadata for proper linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e5e70e7-fd3f-bbb3-9c24-9f2552f94d6d
* Version Independent ID: 0e5e70e7-fd3f-bbb3-9c24-9f2552f94d6d
* Content: [Use Windows Update for Business and Windows Server Update Services (WSUS) together - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/wufb-wsus)
* Content Source: [windows/deployment/update/wufb-wsus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/wufb-wsus.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by vinaypamnani-msft** [comment]
@alroe118 What article is this feedback in reference to?

**Comment by aczechowski** [comment]
There are three possibilities that reference that string:
![image](https://user-images.githubusercontent.com/26784733/231528934-567935c9-a7fa-4f49-adfd-4fd7310066bc.png)
They all refer to something similar to `Computer Configuration\Administrative Templates\Windows Components\Windows Update\Manage updates offered from Windows Server Update Service\`
Which very much exists by default on Windows 11 at least:
![image](https://user-images.githubusercontent.com/26784733/231529432-cd63304b-3e63-4014-a4d2-46389bf6f4a9.png)

Unless you're referring to the registry path?
As Vinay noted, please clarify with which of the three articles and specifically what path you're referring to.

**Comment by alroe118** [comment]
I apologize I mistakenly assumed when I clicked the link for feedback that it would be linked to the page.

 

Here is the URL (Use Windows Update for Business and Windows Server Update Services (WSUS) together - Windows Deployment | Microsoft Learn <https://learn.microsoft.com/en-us/windows/deployment/update/wufb-wsus> )

 

Requires updated ADMX templates and the path information has two mistakes in it

As Stated

Computer Configuration\Administrative Templates\Windows Components\Windows Update\Manage updates offered from Windows Server Update Service\

Group Policy: Specify source service for specific classes of Windows Updates

 

Correct information (note there is no folder named “Manage updates offered from Windows Server Update Service”)

Computer Configuration\Policies\Administrative Templates\Windows Components\Windows Update

Group Policy: Specify source service for specific classes of Windows Updates

 



 

Regards,

Alvin Roe

25876 State Route 12

Watertown NY 13601

(585) 314-0946

**Comment by alroe118** [comment]
Actually not

Computer Configuration\Administrative Templates\Windows Components\Windows Update\Manage updates offered from Windows Server Update Service\
should be

Computer Configuration\Policies\Administrative Templates\Windows Components\Windows Update\Manage updates offered from Windows Server Update Service\



And the policy to be edited is in the Windows Update folder in the latest ADMX (22H2) that I downloaded yesterday

 

 

 

Regards,

Alvin Roe

25876 State Route 12

Watertown NY 13601

(585) 314-0946

**Comment by alroe118** [comment]
Actually not

Computer Configuration\Administrative Templates\Windows Components\Windows Update\Manage updates offered from Windows Server Update Service\
should be

Computer Configuration\Policies\Administrative Templates\Windows Components\Windows Update\Manage updates offered from Windows Server Update Service\

And the policy to be edited is in the Windows Update folder in the latest ADMX (22H2) that I downloaded yesterday

And here’s the screen shot from the most recent available ADMX’s from Microsoft



 

 

 

Regards,

Alvin Roe

**Comment by aczechowski** [comment]
Thanks @alroe118 for clarifying. We try to standardize with the _local_ paths not the Active Directory paths, which is what you're seeing there. If you open `gpedit.msc` locally, you'll see it doesn't have the **Policies** or **Preferences** folders.

While we've had that "unofficial" standard in the past, I'm formalizing it in our internal style guide. Once that private PR merges, this issue will automatically close. Still in draft for review from the team, but something like this:
![image](https://user-images.githubusercontent.com/26784733/231818743-7ae5bb3c-89f9-4c83-9aab-4924541d913e.png)

**Comment by alroe118** [comment]
Thank you for the clarification, makes sense now.

 

The bigger question is why is it different in the two places but not for me to argue.

 

 

 

Regards,

Alvin Roe

25876 State Route 12

Watertown NY 13601

(585) 314-0946
