### ISSUE TITLE
Microsoft Security Guidance Blog [LINK]

### ISSUE THREAD

**Issue by andrewn2000** [MicrosoftDocs/windows-itpro-docs#11450]
[Enter feedback here]

the link is incorrect in the "See alo"
Please update to 
https://techcommunity.microsoft.com/t5/microsoft-security-baselines/bg-p/Microsoft-Security-Baselines
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3deb045-565e-169b-ecd4-6f0f07c966e4
* Version Independent ID: 1bd84f68-4820-4d11-aafc-da1657bddc80
* Content: [Security baselines guide](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-security-configuration-framework/windows-security-baselines?source=recommendations)
* Content Source: [windows/security/threat-protection/windows-security-configuration-framework/windows-security-baselines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-security-configuration-framework/windows-security-baselines.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by RAJU2529** [comment]
Today I will add link
