### ISSUE TITLE
Should this doc be updated for new Microsoft 365 app instead of Office 365?

### ISSUE THREAD

**Issue by barbj** [MicrosoftDocs/windows-itpro-docs#11457]
Re: https://learn.microsoft.com/en-us/windows/client-management/add-an-azure-ad-tenant-and-azure-ad-subscription

I'm performing the steps under Register your free Azure Active Directory subscription

When I login to https://portal.office.com/, it looks absolutely nothing like the pictures on this page.
The instructions say to "Admin tools icon."  There is nothing on the page with the text "admin" on it anywhere.
The title on the pictures on the pages in the task say "_Office 365_" in the left corner.  The real page has "_Microsoft 365_" in the corner and there is this banner at the top of the page:

_The Office app is becoming the new Microsoft 365 app, your home to find, create, and share your content and ideas.
[Learn more]_(https://aka.ms/microsoft-365-faq)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 418463ae-ff0c-6ea2-9994-172206fd433e
* Version Independent ID: 418463ae-ff0c-6ea2-9994-172206fd433e
* Content: [Add an Azure AD tenant and Azure AD subscription - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/add-an-azure-ad-tenant-and-azure-ad-subscription)
* Content Source: [windows/client-management/add-an-azure-ad-tenant-and-azure-ad-subscription.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/add-an-azure-ad-tenant-and-azure-ad-subscription.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
Hi @barbj, this article is outdated and I've been working on some clean up (expecting the changes to be published by next week). If you're looking to create an Azure AD tenant, these articles should help:

- https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-whatis
- https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-access-create-new-tenant

**Comment by barbj** [comment]
I have an Azure tenant.  I've created an OIDC OP in the tenant and I am trying my best to figure out how to create a SAML IdP.  My next step is perhaps it requires a paid AD add-on and I was trying now to figure out how to add that to my free account that I created a long time ago.  Not making much headway.

**Comment by barbj** [comment]
@vinaypamnani-msft  BTW: thank you for the quick response.

Background: I write a SAML service provider and I frequently have customers that ask me questions about how to change settings in their AD IdP.  I was hoping to get some more knowledge so that I could answer their questions.

**Comment by vinaypamnani-msft** [comment]
@barbj I'm afraid I don't have any experience with SAML IdP, but I assume you've already looked at https://learn.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-saml-idp and https://learn.microsoft.com/en-us/azure/active-directory/manage-apps/add-application-portal-setup-sso so perhaps posting in the [Azure-Docs](https://github.com/MicrosoftDocs/azure-docs/issues) repo or opening a support ticket might help.
