### ISSUE TITLE
Use MBR2GPT on a non-system disk 

### ISSUE THREAD

**Issue by BenjaminChambersAFC** [MicrosoftDocs/windows-itpro-docs#11466]
Can you Use MBR2GPT on a non-system disk with out an OS?

(admin edit: add article for proper linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b73c22f0-cb0d-e34b-29d8-06829b86784f
* Version Independent ID: 083115ed-f1be-e962-5b0e-5079dec37353
* Content: [MBR2GPT - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/mbr-to-gpt)
* Content Source: [windows/deployment/mbr-to-gpt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/mbr-to-gpt.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by aczechowski** [comment]
Thanks @BenjaminChambersAFC for the question. As noted in the article:

> - Convert any attached MBR-formatted system disk to the GPT partition format. **You can't use the tool to convert non-system disks from MBR to GPT.**

(I added the bold format to help highlight the key point.)

Also, the tool's primary use is to convert the system disk from MBR to GPT without destroying the data on the drive (including the existing OS). If the disk has no data, then you can just repartition as GPT. And if it's a non-system data disk, then there's not a ton of benefit of having it GPT, except for more than four partitions or disk larger than 2 TB.

I'm closing this issue as I don't think there's anything actionable for docs. For further discussion of the scenario and a possible solution, I suggest starting a thread on [Windows Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
