### ISSUE TITLE
PauseFeatureUpdatesStartTime text appears to be wrong

### ISSUE THREAD

**Issue by isrbaral** [MicrosoftDocs/windows-itpro-docs#11469]
PauseFeatureUpdatesStartTime appears to be copied from PauseFeatureUpdates and no longer shows syntax

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91ca58bd-f279-7739-0140-c4bd56784768
* Version Independent ID: 1d2ecc90-58a3-6bcd-84ae-ef04d7a3b7b4
* Content: [Update Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update)
* Content Source: [windows/client-management/mdm/policy-csp-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-update.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
Thanks for reporting this issue @isrbaral. The CSP docs are automatically generated and used the GPO description. I've implemented a change for PauseFeatureUpdatesStartTime and PauseQualityUpdatesStartTime to use an alternative description. These changes will be live later this month when we refresh the CSP articles, so I'm closing this issue at this point.
