### ISSUE TITLE
        key = bytes.fromhex("71C54C3BCFFCE591A70C0B5BA6448327BC975D89F3021053125F1CB9A7C0AF72")

### ISSUE THREAD

**Issue by Afiq186** [MicrosoftDocs/windows-itpro-docs#11462]
https://github.com/avast/ioc/blob/master/ViperSoftX/extras/extraction_script/extract_files.py#L7-L9

**Comment by aczechowski** [comment]
I'm assuming this is a test or misfire or something, so closing.
