### ISSUE TITLE
Wrong type in Field TargetKBNumber at wufb-reports-schema-ucclientupdatestatus.md

### ISSUE THREAD

**Issue by dacool** [MicrosoftDocs/windows-itpro-docs#11478]
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/wufb-reports-schema-ucclientupdatestatus.md

UCClientUpdateStatus field TargetKBNumber says type int. But should be string after 2023-04-11 Security Update.

![image](https://user-images.githubusercontent.com/9551098/233960866-d7586738-c213-4096-9781-174a29c60a51.png)

(admin edit: adding article metadata for proper linkage)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee2f6d68-6b43-72da-e110-be1c7bec4988
* Version Independent ID: ee2f6d68-6b43-72da-e110-be1c7bec4988
* Content: [Windows Update for Business reports Data Schema - UCClientUpdateStatus - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/wufb-reports-schema-ucclientupdatestatus)
* Content Source: [windows/deployment/update/wufb-reports-schema-ucclientupdatestatus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/wufb-reports-schema-ucclientupdatestatus.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by StevybSC** [comment]
Hi, this is less about int vs string in my opinion, it is more the fact that TargetKBNumber has changed from simple "KBxxxx (version)" to a full descriptive text of the update.

Additionally, it looks like it's appending the value of TargetKBNumber to the Update DisplayName, effectively repeating the information.

![image](https://user-images.githubusercontent.com/39970719/234014011-3c3380f3-b426-44cd-b15d-2e73a07b6b36.png)

**Comment by mestew** [comment]
@dacool thanks. I'll get the type updated shortly.
@StevybSC I've reported the issue to the product team so they can take a peek to see what's up. Thanks.
