### ISSUE TITLE
dont have certificate templates

### ISSUE THREAD

**Issue by Ahmad1z1** [MicrosoftDocs/windows-itpro-docs#11477]
trying to follow the tutorial but i dont have certificate templates, i only have certificates when i "Add ireRemove Snap-ins"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20f487a0-5d22-9db1-67b8-b8e16aa07d23
* Version Independent ID: 14d72ae1-1b8c-4682-7226-f115b69061a8
* Content: [Get Started with Virtual Smart Cards - Walkthrough Guide (Windows 10)](https://learn.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-get-started)
* Content Source: [windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-get-started.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by RAJU2529** [comment]
@Ahmad1z1 , try in windiows server .

**Comment by Ahmad1z1** [comment]
im trying this on a win 10 machine, not a server.

**Comment by RAJU2529** [comment]
@Ahmad1z1, in windows 11 that option is not there till now.
