### ISSUE TITLE
InteractiveLogon_MachineInactivityLimit

### ISSUE THREAD

**Issue by gu1llaume-b** [MicrosoftDocs/windows-itpro-docs#11475]
Hi,

For the Machine Inactivity Limit policy, the documentation states that it should be specified in **seconds**. 
However, the " Minutes of lock screen inactivity until screen saver activates" policy description in Intune (Security Baselines (MDM Security Baseline for Windows 10 and later for November 2021 template)) states that it should be configured in **minutes**. Moreover, this Intune policy is redirecting to the InteractiveLogon_MachineInactivityLimit policy in that documentation page.
Finally, this setting is causing a conflict with another configuration profile, while the configured value is the same (tested in minutes and in seconds in the security baseline).

Which value (seconds or minutes) should be used in Intune? Why is it causing some conflicts with another policy enforcing the same value?

Thank you in advance,
Guillaume

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 773b74b2-7dc2-d0e5-1e3b-bd6445bceda4
* Version Independent ID: 34b55057-9078-6bd0-a9ac-2f6403b84be7
* Content: [LocalPoliciesSecurityOptions Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions#localpoliciessecurityoptions-interactivelogon-machineinactivitylimit)
* Content Source: [windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by gu1llaume-b** [comment]
Any insights on this?

**Comment by vinaypamnani-msft** [comment]
Hi @gu1llaume-b, the policy in question is defined in seconds in Intune (via Settings catalog or a Custom profile). The security baseline does however expose this setting in minutes, but I believe under the hood it converts it to seconds to apply it. 

For conflicts, you may have the same setting defined in multiple profiles (see https://learn.microsoft.com/en-us/mem/intune/protect/security-baselines#avoid-conflicts). If you continue to have problems, I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
