### ISSUE TITLE
Simplified view or release dates?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/windows-itpro-docs#1147]
Hello,
Can you please confirm if the "(Targeted)" nomenclature is now officially gone from Windows 10 servicing channels?  I was hoping to find a nice and easy table for discussions/presentations similar to the one found for Office here - https://docs.microsoft.com/en-us/deployoffice/overview-of-update-channels-for-office-365-proplus.

It's really hard to find anywhere on Docs the calendar or schedule of releases for Insider Preview, Semi-Annual (/Targeted), and LTSC.  Safe to say:

Insider Preview: Random release dates
Semi-Annual Targeted: March and September
Semi-Annual: 4 months delay from Targeted, so July and January
LTSC: Every 2-3 years

??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6957383-3bd9-eef9-6410-9c42f8a0b172
* Version Independent ID: a2090374-0fd1-8d67-66de-30c4cf2835f7
* Content: [Overview of Windows as a service (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-overview#servicing-channels)
* Content Source: [windows/deployment/update/waas-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-overview.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @JeremyTBradshaw ,
yes, you are correct, the "Targeted" nomenclature is now officially gone from Windows 10 servicing channels. This term is now used only within the scope of Windows Update for Business product and is not related to Windows 10 update releases.. As it is described in [this article](https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/Windows-10-and-the-disappearing-SAC-T/ba-p/199747): "If you are not using Windows Update for Business today, “targeted” has no impact on your devices other than to signify which phase the Windows 10 release deployment is in."

To understand it more clearly, I would recommend to read the article and the comments section under it.

Thank you

**Comment by JeremyTBradshaw** [comment]
Thanks and closed.  The documentation and products themselves are seeming to be getting better and better, and any confusion is now cleared up.
