### ISSUE TITLE
Calling multiple scripts in the package | Text makes no sense

### ISSUE THREAD

**Issue by jonconwayuk** [MicrosoftDocs/windows-itpro-docs#11473]
**Your provisioning package can include multiple CommandLines.

You are allowed one CommandLine per provisioning package**. The batch files shown above are orchestrator scripts that manage the installation and call any other scripts included in the provisioning package. The orchestrator script is what should be invoked from the CommandLine specified in the package

The first line and the first line of the second paragraph contradict each other.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e74438de-e454-3c41-0a8d-dfe951459a79
* Version Independent ID: ea43f6c5-8ef0-6a66-9620-d5cc32ad5e8c
* Content: [Use a script to install a desktop app in provisioning packages (Windows 10/11) - Configure Windows](https://learn.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-script-to-install-app)
* Content Source: [windows/configuration/provisioning-packages/provisioning-script-to-install-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/provisioning-packages/provisioning-script-to-install-app.md)
* Product: **windows-client**
* Technology: **itpro-configure**
* GitHub Login: @lizgt2000
* Microsoft Alias: **lizlong**

**Comment by vinaypamnani-msft** [comment]
I think the first line was meant to be "Your provisioning package can include multiple **CommandFiles**". There can only be a single CommandLine, and the orchestrator script can reference multiple files (other scripts/executables). We'll get the article updated.
