### ISSUE TITLE
Instructions do not connect with reality

### ISSUE THREAD

**Issue by ptpro-douglashahn** [MicrosoftDocs/windows-itpro-docs#11476]
Please check the instructions as they describe options that aren't there.  User Configuration does not have an option to enable windows hello for business, it only has PIN complexity.  Computer configuration has the option to enable windows hello for business.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ec90f64-9a12-fdf9-25db-0e83cf77b7a2
* Version Independent ID: fb68756c-2d0c-c28c-4bda-ef6a876576e7
* Content: [Configure Windows Hello for Business Policy settings in an on-premises certificate trust](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Thank you for the feedback, @ptpro-douglashahn . I'll verify the instructions and update the article as needed.

**Comment by paolomatarazzo** [comment]
I checked and the policy is documented correctly: 
![image](https://user-images.githubusercontent.com/74918781/234019882-db9b84ae-b9fd-42ad-8504-b3ed64cd5a73.png)
