### ISSUE TITLE
Secure Assessment Browser extension

### ISSUE THREAD

**Issue by StenPaal** [MicrosoftDocs/windows-itpro-docs#11485]
Hi!

I am trying to set up "Take a test" environment, like on this page https://learn.microsoft.com/en-us/education/windows/edu-take-a-test-kiosk-mode?tabs=powershell

I have everything working, web page opens up, but then a problem occurs. Students need to use smart card (ID-card) to log in into online testing site. This action requires browser extension called "Web eID" https://chrome.google.com/webstore/detail/web-eid/ncibgoaomkmdpilpocfeponihegamlic

I have tried to change KioskModeAUMID to Edge, but this seems not to be working at all.

How could this problem be solved? I am using powershell scripts to deploy and test things in our ecosystem.

(admin edit: added article metadata for proper linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3af13500-9626-be44-681b-0445c77191b6
* Version Independent ID: 3af13500-9626-be44-681b-0445c77191b6
* Content: [Configure Take a Test in kiosk mode - Windows Education](https://learn.microsoft.com/en-us/education/windows/edu-take-a-test-kiosk-mode?tabs=powershell)
* Content Source: [education/windows/edu-take-a-test-kiosk-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/education/windows/edu-take-a-test-kiosk-mode.md)
* Product: **windows-client**
* Technology: **itpro-edu**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @StenPaal I'm checking if it's possible to allow extensions with the secure browser. I'll update this thread as I find more information.

**Comment by paolomatarazzo** [comment]
@StenPaal we don't currently support extensions for the secure browser.
