### ISSUE TITLE
excludedextensions

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#11486]
Hello,

Under the "excludedextensions", there is a line "The value is not used and it is recommended that this be set to 0."
What exactly does it mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66b1ab2e-1964-5580-7c99-4bd4cd480075
* Version Independent ID: f7b5da46-04cb-3501-65fa-870a3c6f09b8
* Content: [Defender Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-Defender?WT.mc_id=Portal-fx#defender-excludedextensions)
* Content Source: [windows/client-management/mdm/policy-csp-defender.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-defender.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
The description for this policy is sourced from the GPO description, and the "The value is not used and it is recommended that this be set to 0." statement is not applicable for CSP article. I've updated our automation to fix this, the article will be addressed in the next refresh.
