### ISSUE TITLE
Cloud Kerberos Trust not mentionned

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/windows-itpro-docs#11498]
The planning guide does not mention the Cloud Kerberos Trust type, could you please update it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5739fab2-c6db-a7a9-b0e7-2bf4b85912a7
* Version Independent ID: 82c58053-c1d7-d938-1b0f-f3f7f70ada3b
* Content: [Planning a Windows Hello for Business Deployment](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-planning-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-planning-guide.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @Martony78 , the update to the planning guide is in our backlog. Thank you for the feedback.
