### ISSUE TITLE
The instructions to find the app publisher or product name reference the windows store for business which is deprecated.

### ISSUE THREAD

**Issue by jperry604** [MicrosoftDocs/windows-itpro-docs#11494]
[Enter feedback here]
The instructions to find the app publisher or product name reference the windows store for business which is deprecated.
Though, if you go into the store on a workstation and get the share link, and use that ID it seems to work.

_If you don't know the Store app publisher or product name, you can find them by following these steps.

Go to the [Microsoft Store for Business](https://go.microsoft.com/fwlink/p/?LinkID=722910) website, and find your app. For example, Power BI Mobile App.

Copy the ID value from the app URL. For example, the Power BI Mobile App ID URL is https://www.microsoft.com/store/p/microsoft-power-bi/9nblgggzlxn1, and you'd copy the ID value, 9nblgggzlxn1.

In a browser, run the Store for Business portal web API, to return a JavaScript Object Notation (JSON) file that includes the publisher and product name values. For example, run https://bspmts.mp.microsoft.com/v1/public/catalog/Retail/Products/9nblgggzlxn1/applockerdata, where 9nblgggzlxn1 is replaced with your ID value._

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7df27add-73fe-4f0b-7e30-face0f95cda3
* Version Independent ID: 3ec647d9-3470-8d8b-a941-d56f6522a35e
* Content: [Create a WIP policy in Intune](https://learn.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jperry604 for taking the time to share this information. See the note at the top of this article (and a few others in the WIP section) that WIP itself is deprecated. Because of that we're not making many investments to this content, but will maintain it through the end of the feature lifecycle. So I'm not going to make any changes to this article, but thank you for sharing the information in this public feedback so that others can refer to it if needed.
