### ISSUE TITLE
Dependency on PowerShell

### ISSUE THREAD

**Issue by rohde-januar** [MicrosoftDocs/windows-itpro-docs#11496]
I guess my question is quite simple. How do you do it without PowerShell? I know PowerShell is your product, you sell it, and some people also swear by it. Please do keep in mind that not everyone use PowerShell, nor do they want or intent to - this is too much when you only provide PowerShell documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aab824fb-b795-518a-8d52-7490975ab5ac
* Version Independent ID: aab824fb-b795-518a-8d52-7490975ab5ac
* Content: [Configure federation between Google Workspace and Azure AD - Windows Education](https://learn.microsoft.com/en-us/education/windows/configure-aad-google-trust)
* Content Source: [education/windows/configure-aad-google-trust.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/education/windows/configure-aad-google-trust.md)
* Product: **windows-client**
* Technology: **itpro-edu**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @rohde-januar and thank you for the feedback. If you don't want to use PowerShell, you can use alternative solutions, such as using the Microsoft Graph APIs (https://learn.microsoft.com/en-us/graph/overview) or using [CloudShell](https://azure.microsoft.com/en-us/get-started/azure-portal/cloud-shell).
Given the complexity of using the Micorosoft Graph API to configure federation, we opted to document the simplest solution, which works with both PowerShell and CloudShell. However, you can find documentation how to configure the tenant using APIs.
