### ISSUE TITLE
Insufficient detail on services

### ISSUE THREAD

**Issue by DavidRawling** [MicrosoftDocs/windows-itpro-docs#11502]
This page lists a subset of the per-user services (I can see on default installations of Windows 10 and Windows 11 that there are several not listed). Furthermore, the description of services is nonexistent.

For example, the service called "DevicePicker" apparently disables Device Picker. But what is it? What types of devices are visible in the "Device Picker"? Where is it found? What types of failures will occur if it's disabled? What's the security impact of enabling it? How do I test disabling it?

Another example is the OneSync Service. Which Microsoft applications use this service? Are they in-box or only from the Store? Is this only for specific account types within specific apps? Where are the logs so we can review what it does and which apps use it?

Or perhaps CDPUserSvc - what scenarios are part of this platform? Which applications or pieces of hardware? Where do I see this to test it?

Right now the only difference between the name and the purpose is as little as a single space, and that's not sufficient.

(admin edit: revising metadata)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aaa890d7-00c3-8e74-54af-3f3aa2aeb4c4
* Version Independent ID: 0ad75b5c-a4e1-a954-163a-fd8922b8f760
* Content: [Per-user services in Windows 10 and Windows Server - Windows Application Management](https://learn.microsoft.com/en-us/windows/application-management/per-user-services-in-windows)
* Content Source: [windows/application-management/per-user-services-in-windows.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/application-management/per-user-services-in-windows.md)
* Product: **windows-client**
* Technology: **itpro-apps**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @DavidRawling for the feedback. I'm refreshing this article and updating the list of services based on Windows 11 version 23H2. I also did some internal research on the services to provide further detail.

This issue will automatically close when my pull request is merged. Given the holiday break, the changes may not publish live for a few days.
