### ISSUE TITLE
i need to bypass that feature

### ISSUE THREAD

**Issue by come-raczy** [MicrosoftDocs/windows-itpro-docs#11504]
[Enter feedback here]
it doesn't give a quick solution to unstuck me from edge refusing to download and open a file. very frustrating

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4edaae97-455b-d25a-9228-5309e24b4aa3
* Version Independent ID: d38e56a7-d553-e519-95a9-dc93e2cdc771
* Content: [Microsoft Defender SmartScreen overview](https://learn.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview)
* Content Source: [windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @come-raczy for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
