### ISSUE TITLE
App-V sequencer is no longer included in the ADK

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/windows-itpro-docs#1151]
The sql server, assessment toolkits, and app-v sequencer options (four items) are apparently no longer included in the ADK.  I just took a fresh download of the download utility and they just aren't there to pick.  Tried it on a different computer to be sure.  The remaining options seem to work fine though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410b9952-998e-4564-78c1-62d92f778b57
* Version Independent ID: 8b4e065f-03bd-5911-e473-56420605090a
* Content: [Install the App-V Sequencer (Windows 10)](https://docs.microsoft.com/en-us/windows/application-management/app-v/appv-install-the-sequencer)
* Content Source: [windows/application-management/app-v/appv-install-the-sequencer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/app-v/appv-install-the-sequencer.md)
* Product: **w10**
* GitHub Login: @MaggiePucciEvans
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @jordanmills ,
could you please provide more details?
 which version of Windows 10 do you use? please also check this [blog article](https://msitproblog.com/2016/09/19/app-v-sequencer-missing-adk-10-v1607/)
Thank you

**Comment by mypil** [comment]
@jordanmills - We would like to follow up. Can you please respond to the query of MaratMussabekov?

**Comment by jordanmills** [comment]
I use several versions of windows 10.  But I experienced this issue on staging servers, i believe running windows server 2019.

**Comment by MaratMussabekov** [comment]
Dear @jordanmills ,
tried on WS2019 today (used the last ADK version), and saw following:
![image](https://user-images.githubusercontent.com/48041687/58231356-3ade1780-7d50-11e9-9e43-77f9462afb6d.png)
For sure, the list of available options differs from the one in the article, however, app-v sequencer presents. Do you have option to check it on some other installation?
Thank you

**Comment by mypil** [comment]
@jordanmills - Can you please respond to the query of MaratMussabekov?

**Comment by mypil** [comment]
@jordanmills - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by jordanmills** [comment]
Sorry this one got lost in the shuffle.  I haven't had time to verify on server 2019.
