### ISSUE TITLE
why some AD admin can't provision cloud trust to themselves

### ISSUE THREAD

**Issue by NagaCSC** [MicrosoftDocs/windows-itpro-docs#11513]
submitted pull request to update "Denied RODC password Replication Group" in the example, who can't provision cloud trust if they were member of. please check below as it shows no assigned reviewer 

https://github.com/MicrosoftDocs/windows-docs-pr/pull/8287/commits 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7739850a-a445-faf1-eec8-8aecb6de8b95
* Version Independent ID: 7739850a-a445-faf1-eec8-8aecb6de8b95
* Content: [Windows Hello for Business cloud Kerberos trust deployment](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by aczechowski** [comment]
Thanks @NagaCSC for the contribution, I just assigned the PR to Paolo for review, so no need to track separately with an issue, closing as a duplicate.
