### ISSUE TITLE
Update Policy CSP - Windows 10 applicability of Scan Source policies unclear

### ISSUE THREAD

**Issue by Skorfulose** [MicrosoftDocs/windows-itpro-docs#11525]
The [Update Policy CSP](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update#setpolicydrivenupdatesourcefordriverupdates) documentation states that any of the four `SetPolicyDrivenUpdateSourceFor<Update Type>` settings is only applicable to:
> ✔️ Windows 11, version 21H2 [10.0.22000] and later

In contrast, the [Use Windows Update for Business and WSUS together](https://learn.microsoft.com/en-us/windows/deployment/update/wufb-wsus) docs article states:
> Applies to
> 
> - Windows 10
> - Windows 11
> 
> [...]
> 
> We added the scan source policy starting with the [September 1, 2021—KB5005101 (OS Builds 19041.1202, 19042.1202, and 19043.1202) Preview](https://support.microsoft.com/help/5005101) update and it applies to Window 10, version 2004 and above and Windows 11.

So are those settings supported on Windows 10 or not? 😉
Please clarify and correct whichever article is wrong / incomplete. Thanks! 🙏

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91ca58bd-f279-7739-0140-c4bd56784768
* Version Independent ID: 1d2ecc90-58a3-6bcd-84ae-ef04d7a3b7b4
* Content: [Update Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update)
* Content Source: [windows/client-management/mdm/policy-csp-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-update.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
Applicability was fixed. Closing this now.
