### ISSUE TITLE
0x801C044F error is not listed

### ISSUE THREAD

**Issue by JohnLechner** [MicrosoftDocs/windows-itpro-docs#1153]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by UdoJet** [comment]
Same here. Updated to 17723.rs5.
Already disconnected from my org, rejoined AAD. 

Also Windows Hello with cam sign-in doesn't work like before.

**Comment by JohnLechner** [comment]
I got past this error on the MFA server.  I was receiving a conflict in IIS within web.config.  I had to rename a web.config to web.config.old in the c:\inetpub\wwwroot folder and force it to use the correct subdirectories.

**Comment by Lava2014** [comment]
Hi ...I am getting the same error...please guide me

**Comment by shortpatti** [comment]
@DaniHalfin, can you take a look at this one?  If it needs to be assigned to someone else, let me know :)

**Comment by Lava2014** [comment]
Dear Dani please help asap

**Comment by Lava2014** [comment]
Dear both

Please help

**Comment by shortpatti** [comment]
@MikeStephens-MS, can you take a look at this issue?

**Comment by Lava2014** [comment]
Dear Mike please help

**Comment by Lava2014** [comment]
Can anyone help on this please

**Comment by DaniHalfin** [comment]
Hi everyone,
For error codes unlisted here, in most cases those are transient error codes being surfaced by other services in the Windows Hello dependency chain.
We are working on something to improve the user experience in that regard, but that will not solve the issues you are experiencing.
If we find a reoccurring error codes that isn't covered here and should be (meaning, in most cases, it is coming from Windows Hello and not other components) we'll make sure to add it to this page.
For any issue you're seeing, please either file a problem through Feedback Hub, or reach out through our various support channels. Both avenues allow us to properly investigate the issue in ways we could never do through a comments section on a GitHub issue.
The feedback section in the topic is generally meant for feedback on the content, and we can't really use it for in-depth troubleshooting.
We thank you for taking the time to reach out, but we also want you to have the best time to resolution of the issue, and going through this feedback channel won't get us there.
I'll be closing this issue, but feel free to respond if you feel we missed something. We can always re-open.
