### ISSUE TITLE
Provide a download link to the XML file

### ISSUE THREAD

**Issue by timbrigham-oc** [MicrosoftDocs/windows-itpro-docs#11536]
This page is great, however I find it quite lacking there isn't a way to directly point to the latest version of the XML without copying and pasting out of a webpage.

If I am building the latest version of a block policy, I want to be able to wrap it into a devops pipeline. Requiring manual steps like this are counterproductive. There should be a download link for this XML document available, pointing to either a learn page or a github repository that backs it up.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d71055e-2b14-227b-0107-c8f150194d5b
* Version Independent ID: 0eab18a0-7e8f-05eb-b47f-e6913682d8e8
* Content: [Microsoft recommended block rules](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @jsuther1974
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
closing as a "duplicate" of #11535 - same basic request, different but related article
