### ISSUE TITLE
How to Audit Fast StartUp Power OFF event  in ring3？

### ISSUE THREAD

**Issue by ThouSandThorChang** [MicrosoftDocs/windows-itpro-docs#11537]
please tell me where can i know How to Audit Fast StartUp Power OFF event  in ring3？

**Comment by aczechowski** [comment]
Hi @ThouSandThorChang, I don't understand your question, and I don't see any references to those strings in any of the content in this repository for Windows client docs. 

I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time. If you have more information about your question that can help us identify an issue with the Windows client documentation, please let us know.
