### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by toxarisswe** [MicrosoftDocs/windows-itpro-docs#11543]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad59e7d-574d-7bd5-3fc9-a9656e186258
* Version Independent ID: e827f939-99b2-31e7-b65a-ee3ad499573e
* Content: [Configure the Group Policy settings for Microsoft Defender Application Guard - Windows Security](https://learn.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-application-guard/configure-md-app-guard)
* Content Source: [windows/security/threat-protection/microsoft-defender-application-guard/configure-md-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-application-guard/configure-md-app-guard.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
I'm assuming this is a misfire or test. If you have actionable feedback for this article, please reopen this issue and provide additional details.
