### ISSUE TITLE
pwdlessQA@microsoft.com generates NDR

### ISSUE THREAD

**Issue by stevenffrench** [MicrosoftDocs/windows-itpro-docs#11547]
The email address mentioned on the bottom of this page, pwdlessQA@microsoft.com, does not accept external emails and instead generates an NDR when you try to email it from outside of Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca080bd-ed37-60a8-ec22-b1929166ff0c
* Version Independent ID: d2742e0c-9d66-4b1f-8555-a1fb1546455b
* Content: [Password-less strategy - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/passwordless-strategy)
* Content Source: [windows/security/identity-protection/hello-for-business/passwordless-strategy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/passwordless-strategy.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Thank you for reporting this, @stevenffrench. Looking into this.

**Comment by paolomatarazzo** [comment]
@stevenffrench a new mailbox is gonna be created. It should be up and running within 48h. Closing this now, please reopen if the issue persist. I'll verify next Monday as well.

**Comment by stevenffrench** [comment]
@paolomatarazzo I'm still having issues, however now the NDR comes back with the following error:

Your message to pwdlessQA@microsoft.com couldn't be delivered.

pwdlessQA wasn't found at microsoft.com.

**Comment by paolomatarazzo** [comment]
@stevenffrench thank you again for checking. I reached out to the PG and they decided to turn off the alias. Customers should contact their account manager to share their questions/feedback and for other general feedback, while we’re in the process of setting up a Feedback Hub context. I will update the article today.
