### ISSUE TITLE
Requirements section contains incorrect KB article numbers

### ISSUE THREAD

**Issue by T8-N** [MicrosoftDocs/windows-itpro-docs#11546]
[Enter feedback here]
The KB articles in the requirements section of this article seem to be wrong...

-	For the 2016 server hotfix it lists KB3534307, however when you click on it the link goes to 4534307 which looks like a hotfix for Microsoft Word.  When I look for 3534307 on the Microsoft Update Catalog or anywhere else online it doesn’t seem to exist.

-	Also an odd issue with the client hotfix listed here, for Windows 11 21H2 it says you need KB5010414.  I do find that on the update catalog and it says it’s for Windows 11, however when you download it, it shows Windows 10 in the file name and fails to install saying “the update is not applicable to your computer”.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7739850a-a445-faf1-eec8-8aecb6de8b95
* Version Independent ID: 7739850a-a445-faf1-eec8-8aecb6de8b95
* Content: [Windows Hello for Business cloud Kerberos trust deployment](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust#prerequisites)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
thank you for the feedback, @T8-N . I'll take a look.

**Comment by paolomatarazzo** [comment]
Hello @T8-N, I checked the link to the first KB you pointed out, it's a correct link and I don't get the redirect to an hotfix for Microsoft Word.
Regarding the second item, which OS version do you have (it may already have the hotfix installed). Did you download the correct architecture (x64 or ARM)? 
![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/74918781/c9358863-872b-4da9-987b-0747283f6f1f).
Please reopen the issue if this comment doesn't help.

**Comment by T8-N** [comment]
Ok, thanks for checking on this.

It looks like the link is pointing to the correct article (4534307), I just didn't realize it because the "highlights" and description of the article seems to reference a Microsoft Word issue which seemed strange to me for a server/domain controller specific rollup.

***@***.***

In regards to the client update, I don't have that exact KB installed but I guess it's determining that I don't need it.  This one through me off because it's a fix for Win11 with the file name that starts with "windows10.0".  That's very confusing and when it failed to install I assumed it was the wrong file.

***@***.***

Thanks,
Tait
