### ISSUE TITLE
Suddenly not working

### ISSUE THREAD

**Issue by nerdhaze** [MicrosoftDocs/windows-itpro-docs#1155]
Greetings, I stumbled upon this doc late last week, and eagerly set about testing the new S Mode with one of my demo machines. It worked for me initially, but subsequent tests sometimes with the same device, and sometimes with a different device, end in a "There's something wrong" message at the end of the installer. It downloads, seemingly, the entire installer, verifies, says it's installing, and then ends with the error after about an hour of total time. I notice the installer's end result is a much lower build number of Windows than the current release. Has that suddenly become the issue? The devices I'm trying to use are running 1803 devices with either Home or Pro. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ce6147b-57c3-b40d-2d1e-3aa04a3d5606
* Version Independent ID: c453ea14-6842-4af7-42c0-6ef8e2336c6c
* Content: [Test Windows 10 in S mode on existing Windows 10 education devices](https://docs.microsoft.com/en-us/education/windows/test-windows10s-for-edu)
* Content Source: [education/windows/test-windows10s-for-edu.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/test-windows10s-for-edu.md)
* Product: **w10**
* GitHub Login: @MikeBlodge
* Microsoft Alias: **MikeBlodge**

**Comment by andreabichsel** [comment]
Did you use the latest links on https://www.microsoft.com/en-us/software-download/windows10 (linked to from this topic)? If not, please do. If you did, please contact Support https://support.microsoft.com/en-us.

**Comment by nerdhaze** [comment]
I don’t recall if the Windows 10 media itself came from that page, but the Windows10SInstaller5932.exe did. That’s what I’m running. I didn’t think the base OS origin mattered as long as it was one of the supported versions of Windows 10.
