### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by akilanGanesh** [MicrosoftDocs/windows-itpro-docs#11565]
[What you can configure](https://learn.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-packages#what-you-can-configure)

Assign device name, enter product key to upgrade Windows, configure **shared used**, remove pre-installed software

This "**shared used**" is not clear. Please update is.

Thanks

(admin edit: add article metadata for proper linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc6a7f82-c972-6aea-f045-08fb57a99ae6
* Version Independent ID: 384fe96b-ace9-3e34-e5e9-24bb7409e0e8
* Content: [Provisioning packages overview - Configure Windows](https://learn.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-packages#what-you-can-configure)
* Content Source: [windows/configuration/provisioning-packages/provisioning-packages.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/provisioning-packages/provisioning-packages.md)
* Product: **windows-client**
* Technology: **itpro-configure**
* GitHub Login: @lizgt2000
* Microsoft Alias: **lizlong**

**Comment by msbemba** [comment]
@akilanGanesh Thank you for your feedback. You have posted this is in the wrong repository, However I can answer this. 

Shared used is a Typo and should be Shared use (Allow multiple users to login on to the same device).

Hope this helps!

Thanks
Sri

**Comment by aczechowski** [comment]
@msbemba do you want to put in a PR to fix that typo?

**Comment by msbemba** [comment]
@aczechowski Here it is PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11577

Sorry, did not realize that I had access to itpro-configure documents.

Thanks
Sri
