### ISSUE TITLE
AllowLocalLogOn links to Windows XP/Server 2003 documentation

### ISSUE THREAD

**Issue by USCloud-EricWilborn** [MicrosoftDocs/windows-itpro-docs#11569]
The note at [https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-UserRights?WT.mc_id=Portal-fx#allowlocallogon](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-UserRights?WT.mc_id=Portal-fx#allowlocallogon) points to documentation for XP/2003.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b62d452-1910-d962-0ccc-9ac3f8135f15
* Version Independent ID: 5a4e6f0c-bcd4-8d8b-93f7-5bda7135b931
* Content: [UserRights Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-UserRights?WT.mc_id=Portal-fx#denylocallogon)
* Content Source: [windows/client-management/mdm/policy-csp-userrights.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-userrights.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @USCloud-EricWilborn for the feedback. Most of the CSP content is auto-generated from the DDF and/or ADMX XML, in this case that link is embedded in those strings. The target article references older versions of the OS, but from what I know of the topic, I think still technically relevant. (I don't think user rights assignment has fundamentally changed that much.) I'm not aware of a better target for that fwlink, and suspect the reason the support article persists is for this reason.
