### ISSUE TITLE
Set Up School PC's Failed Force Restart

### ISSUE THREAD

**Issue by M3rcena** [MicrosoftDocs/windows-itpro-docs#11579]
I am trying to add the package which I got from the set up school pcs app in every school pc and all the pcs shows the same problem, the force restart fails and that causes the installation to fail.

**Comment by aczechowski** [comment]
Thanks @M3rcena for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
