### ISSUE TITLE
Special characters in monospace indicate multiple duplicate characters

### ISSUE THREAD

**Issue by Pyro-Fox** [MicrosoftDocs/windows-itpro-docs#11588]
The new `monospace` font expressing the allowable characters shows duplicates. I like that `monospace` emphasizes the text, but the attempt to escape special characters seems to have gone as well for the last editor as it is for me in this issue report. Since Markdown in is NOT escaping characters in single-line form, I'm using monospace multi-line here.

Long story short, the special characters should be emphasized as
```
'-!"#$%&()*,./:;?@[\]^_`{|}~+<=>
```
and not 
```
(~!@#$%^&*_-+=`|\\(){}\[\]:;"'<>,.?/)
```
Since it has duplicated backslashes and parenthesis.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b5128d9a-e02a-df9b-24cc-32711ad37b54
* Version Independent ID: fecafb19-6b37-1f2e-ba3d-5e0bf0d49d09
* Content: [Password must meet complexity requirements - Windows Security](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements)
* Content Source: [windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by Pyro-Fox** [comment]
> The new `monospace` font expressing the allowable characters shows duplicates. I like that `monospace` emphasizes the text, but the attempt to escape special characters seems to have gone as well for the last editor as it is for me in this issue report. Since Markdown in is NOT escaping characters in singl-line form, I'm using monospace multi-line here.
> 
> Long story short, the special characters should be emphasized as
> 
> ```
> '-!"#$%&()*,./:;?@[\]^_`{|}~+<=>
> ```
> 
> and not
> 
> ```
> (~!@#$%^&*_-+=`|\\(){}\[\]:;"'<>,.?/)
> ```
> 
> ## Since it has duplicated backslashes and parenthesis.
> #### Document Details
> ⚠ _Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking._
> 
> * ID: b5128d9a-e02a-df9b-24cc-32711ad37b54
> * Version Independent ID: fecafb19-6b37-1f2e-ba3d-5e0bf0d49d09
> * Content: [Password must meet complexity requirements - Windows Security](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements)
> * Content Source: [windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md)
> * Product: **windows-client**
> * Technology: **itpro-security**
> * GitHub Login: @vinaypamnani-msft
> * Microsoft Alias: **vinpa**

FWIW, to get the "fixed" list, I just copied the original to my clipboard, then ran this:
``` powershell
$String = Get-Clipboard
($string -split '(.)' | sort -Unique ) -join ''
```

**Comment by aczechowski** [comment]
Thanks @Pyro-Fox for the feedback and clear suggested fix. I just did a quick pull request to make the edit; this issue will automatically close when the PR merges.
