### ISSUE TITLE
CSP for "SetAutoRestartNotificationDisable" issue

### ISSUE THREAD

**Issue by laurentdelosieresfact** [MicrosoftDocs/windows-itpro-docs#11580]
Hello,

We would like to show a notification to ther user everytime the computer is about to reboot so the user can save their current work. We are relying on the following policy "[SetAutoRestartNotificationDisable](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-Update?WT.mc_id=Portal-fx#setautorestartnotificationdisable)", but for every value we put (either 0 or 1), we see in the Windows Update Settings window that "Show a notification when your PC requires a restart to finish updating" is greyed out, but it is never enabled or disabled. We have tested it on Windows 10 version 10.0.19045.2006 and latest. Shall we enable another policy to make it work ?

Thank you in advance,

Best,
L.

**Comment by aczechowski** [comment]
Thanks @laurentdelosieresfact for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
