### ISSUE TITLE
Clarification around ADFS and small corrections in Hybrid Deployments

### ISSUE THREAD

**Issue by MHimken** [MicrosoftDocs/windows-itpro-docs#11591]
Hi everyone,

The table in Hybrid Deployments is already really helpful to answer some prerequisite questions, but I would like to clarify one thing: ADFS. ADFS is only required for Cert Trust as far as I understand. It's not required for "Cloud Kerberos trust", which is why it says N/A in the table(?). Could this be changed to "not required", just like it says "Azure AD Connect" is "required", to make it more consistent? It would also help to clarify that Certificate Trust is the only method that requires ADFS, while all others don't as far as I understand.

On that topic, in a *hybrid* deployment, AD Connect is always required to sync users with Azure AD, right? How can it now be required with Cloud Kerberos trust?

Also, it should read "**C**loud Kerberos trust", not "**c**loud Kerberos trust".

Best Regards
Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87e5f5f1-16cf-57e2-bdfc-b090d90437b1
* Version Independent ID: 1662c47f-12cb-147d-25f0-dee98b6c7722
* Content: [Windows Hello for Business Deployment Prerequisite Overview - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification#hybrid-deployments)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-identity-verification.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-identity-verification.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @MHimken and thank you for reaching out, good questions/feedback.
You can't use cloud Kerberos trust with AD FS, that's why it's flagged as "not applicable" (N/A).
Azure AD Connect is not always required, as you could use Azure AD Cloud Sync, but I understand that the table is not accurate. I'll double check how to improve it.
As far as the feature name goes, it's "cloud Kerberos trust". Only the `K` is capitalized.

**Comment by paolomatarazzo** [comment]
@MHimken I made the updates and they should be live later today. Thank you
