### ISSUE TITLE
Biometrics first, then PIN?

### ISSUE THREAD

**Issue by mrhls2312** [MicrosoftDocs/windows-itpro-docs#11590]
"Why do you need a PIN to use biometrics?" section incorrectly states "When you set up Windows Hello, you're asked to create a PIN first." 

During the enrollment process, Biometrics are enrolled first and then the PIN is created.

(At least, this is my findings after wiping and provisioning four or more times a day readying for a Windows Hello for Business deployment with a hardware refresh).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c34dbafa-df3c-a5a5-32d5-2ce152893534
* Version Independent ID: cebdd9a6-45d7-6306-373c-7d31121f9e16
* Content: [Why a PIN is better than an online password - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @mrhls2312 and thank you for catching it. I'll update the sentence.

**Comment by paolomatarazzo** [comment]
Fixed in https://github.com/MicrosoftDocs/windows-docs-pr/pull/8491
