### ISSUE TITLE
Does the client need clear sight to the domain controllers?

### ISSUE THREAD

**Issue by janeide75** [MicrosoftDocs/windows-itpro-docs#11603]
I have followed the guide, and it works well on my AADJ client as long as they have connectivity to the domain controllers. But when accessing RDS servers through the Remote Desktop Gateway from the internet I get a message that NLA cannot be performed because the domain controllers cannot be contacted (when I try with username/password it works). If I then connect a VPN client it works with cert / PIN code. Is this behavior by design, or is there something wrong in my RDS Gateway setup? I was hoping to get passwordless login to RemoteApp from anywhere. It can of course be worked around with "Always-on-VPN".

**Comment by aczechowski** [comment]
Thanks @janeide75 for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time. Also, I don't think we have any content under this Windows client repo for Remote Desktop Gateway. If you have more information about which specific article, that might help us determine if there's any documentation revisions necessary.
