### ISSUE TITLE
Autopatch: A3/A5 Licenses, Win 10/11 Education?

### ISSUE THREAD

**Issue by jmtread** [MicrosoftDocs/windows-itpro-docs#11604]
Hi There,

This page doesn't mention if Windows 10/11 for Education and A3 or A5 M365 licensing meet the minimum requirements for Autopatch.
I assume that they do but I don't like to guess about these things.
It would be great if they could be added in.

Thankyou

Jason

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b62318d9-188e-9895-7445-11c4770c7dbf
* Version Independent ID: b62318d9-188e-9895-7445-11c4770c7dbf
* Content: [Prerequisites - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/windows-autopatch/prepare/windows-autopatch-prerequisites)
* Content Source: [windows/deployment/windows-autopatch/prepare/windows-autopatch-prerequisites.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopatch/prepare/windows-autopatch-prerequisites.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @tiaraquan
* Microsoft Alias: **tiaraquan**

**Comment by tiaraquan** [comment]
Hi there, 

Thank you for reaching out.

A3/A5 and F3 licensing aren't supported in Windows Autopatch. This information can be found on the FAQ page https://learn.microsoft.com/en-us/windows/deployment/windows-autopatch/overview/windows-autopatch-faq#does-windows-autopatch-support-windows-education--a3-a5--or-windows-front-line-worker--f3--licensing

**Comment by aczechowski** [comment]
Closing this issue since @tiaraquan already addressed it.
