### ISSUE TITLE
windows security > account protection: can not set up, the windows hello does not able

### ISSUE THREAD

**Issue by mrgbgb** [MicrosoftDocs/windows-itpro-docs#11617]
[Enter feedback here]
 can not set up account protection , the windows hello does not able. to change the PIN is not able to change, and even 
though, when i start open the laptop, i write the password and it was correct or maybe not, but it show: This sign-in option is disables because of failed sign-in attempts or repeated shutdowns. Use a different sign-in option or keep your device powered on for at least 2 hours and then try again. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6db8ae96-98ad-1ad1-a40d-7b6f78287bfb
* Version Independent ID: 6db8ae96-98ad-1ad1-a40d-7b6f78287bfb
* Content: [Account protection in the Windows Security app - Windows Security](https://learn.microsoft.com/en-us/windows/security/operating-system-security/system-security/windows-defender-security-center/wdsc-account-protection)
* Content Source: [windows/security/operating-system-security/system-security/windows-defender-security-center/wdsc-account-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/operating-system-security/system-security/windows-defender-security-center/wdsc-account-protection.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**
```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/windows-itpro-docs/issues/11616
```

**Comment by aczechowski** [comment]
Thanks @mrgbgb for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
