### ISSUE TITLE
Clarification on initiation of communication. 

### ISSUE THREAD

**Issue by mikemagarelli** [MicrosoftDocs/windows-itpro-docs#11613]
Is communication always initiated from the client to the 'connection endpoints for Windows', or can there be scenarios where communication is initiated by the connection endpoints? I'm unable to find any documentation that clearly articulates expected behavior. Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ba43b5f-dd62-9634-fe8b-c10755456df8
* Version Independent ID: 1ba43b5f-dd62-9634-fe8b-c10755456df8
* Content: [Connection endpoints for Windows 10 Enterprise, version 21H2 - Windows Privacy](https://learn.microsoft.com/en-us/windows/privacy/manage-windows-21h2-endpoints)
* Content Source: [windows/privacy/manage-windows-21h2-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/manage-windows-21h2-endpoints.md)
* Product: **windows-client**
* Technology: **itpro-privacy**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@mikemagarelli   We checked with the team responsible for the information in that article. Their reply was: "For these documented endpoints, they’re initiated from the client."  Hope that helps.

**Comment by mikemagarelli** [comment]
Thanks so much, that's exactly what I needed!
