### ISSUE TITLE
More clarity needed for last step (for users)

### ISSUE THREAD

**Issue by NickDorak** [MicrosoftDocs/windows-itpro-docs#11611]
The last step "Use the certificate credential protected by your Windows Hello for Business gesture to authenticate", does not clearly explain what the user should expect. It shows that a certificate should be used, but hopefully the user doesn't know what a certificate is and just uses their Hello login. 
Please add some clarity of what is the expected behavior. Hopefully a screenshot or similar to share with end users. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e9cc344-d2c1-1f8b-232a-b2cccd8b32a3
* Version Independent ID: eb87d132-cc0b-8ab2-4417-51e1bc719c14
* Content: [Deploy certificates for remote desktop sign-in - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-deployment-rdp-certs.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello Nick and thank you for the feedback. The prompt will vary based on the credential providers configured on the device and the number of certificates issued. I'll put this request in the backlog and determine whether adding an animated gif or screenshot can be valuable.
