### ISSUE TITLE
on-premises

### ISSUE THREAD

**Issue by keithboesel** [MicrosoftDocs/windows-itpro-docs#11614]
premise is defined as "a proposition antecedently supposed or proved as a basis of argument or inference". The word you're looking for is premises. "the land and buildings owned by someone, especially by a company or organization"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06d983d1-8644-39b2-c3cf-00c182d65228
* Version Independent ID: 06d983d1-8644-39b2-c3cf-00c182d65228
* Content: [Windows Autopatch - Frequently Asked Questions (FAQ) - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/windows-autopatch/overview/windows-autopatch-faq)
* Content Source: [windows/deployment/windows-autopatch/overview/windows-autopatch-faq.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopatch/overview/windows-autopatch-faq.yml)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @tiaraquan
* Microsoft Alias: **tiaraquan**

**Comment by tiaraquan** [comment]
Thank you for catching that small typo and will be correcting it.

Polite and constructive feedback is always welcome. Please be mindful for your tone going forward when providing feedback. The [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/), which outlines the expectations for community interactions in and around docs.microsoft.com, is designed to help "provide a welcoming and inspiring community for all."
