### ISSUE TITLE
Possible Incorrect Description of Policy

### ISSUE THREAD

**Issue by 3DBarron** [MicrosoftDocs/windows-itpro-docs#11625]
I believe there's incorrect information in this page description. There are two sections:

DenyLocalLogOn and DenyLogOnAsService. For both of these, they have the description:

> Deny log on as a service -This security setting determines which service accounts are prevented from registering a process as a service.

Deny Local Log On seems like it should be for local log on, not for log on as a service- based on the name of the policy. However, I can't find anywhere that describes Deny Local Log On correctly. Can someone please verify that this is indeed incorrect information and validate the correct description for the policy? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b62d452-1910-d962-0ccc-9ac3f8135f15
* Version Independent ID: 5a4e6f0c-bcd4-8d8b-93f7-5bda7135b931
* Content: [UserRights Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-userrights)
* Content Source: [windows/client-management/mdm/policy-csp-userrights.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-userrights.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @3DBarron for the feedback. Much of the CSP content is now automated, for more information, see [Contributing to the CSP reference articles](https://learn.microsoft.com/windows/client-management/mdm/contribute-csp-reference). In looking at the markdown source for this policy, there's a comment: 

> KNOWN ISSUE: DenyLocalLogOn policy section from DDF has strings for 'Deny log on as a service'

I'm assuming that's a code bug that's filed back to OS engineering to resolve in the source DDF. Once that's fixed, it will pass through to the docs.

@vinaypamnani-msft to keep me honest 😉

**Comment by vinaypamnani-msft** [comment]
You're correct, a code bug has been filed to resolve this in the source DDF.

**Comment by 3DBarron** [comment]
Hi there- I wanted to follow up on this because it was closed but not resolved. Is there any solution in sight? 

I found reports of this going back to 2020: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8156
And also 2021: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10054

Nearing four years with incorrect documentation- and we really need the correct documentation/info to apply policy correctly. Thanks,

**Comment by aczechowski** [comment]
Hi @3DBarron - see my previous note. :) The docs are now auto-generated with strings from the OS, and the issue is in the underlying OS strings. There's a code bug into the engineering team to fix it, so once that's fixed and released to at least Insider Preview builds, the docs will be updated. You could file feedback to the engineering team via the Windows Feedback Hub and then might get more insight from them on the state of things.

**Comment by 3DBarron** [comment]
Thanks for the info- shame there's not any manual intervention or override available. It's challenging for us to get things wrong when we can't see accurate documentation. I'm trying to implement this in my org but cannot find the correct info on it anywhere.
