### ISSUE TITLE
Establish a pin, select and hold where ?

### ISSUE THREAD

**Issue by mckenzm** [MicrosoftDocs/windows-itpro-docs#11624]
[Enter feedback here]
https://learn.microsoft.com/en-us/windows/security/operating-system-security/data-protection/bitlocker/bitlocker-recovery-guide-plan#to-prevent-continued-recovery-due-to-an-unknown-pin

So selecting and holding in filemanager does nothing. Anywhere else to suggest?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe569796-58e6-4481-792e-5f8e8a7a7cb8
* Version Independent ID: fe569796-58e6-4481-792e-5f8e8a7a7cb8
* Content: [BitLocker recovery guide - Windows Security](https://learn.microsoft.com/en-us/windows/security/operating-system-security/data-protection/bitlocker/bitlocker-recovery-guide-plan)
* Content Source: [windows/security/operating-system-security/data-protection/bitlocker/bitlocker-recovery-guide-plan.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/operating-system-security/data-protection/bitlocker/bitlocker-recovery-guide-plan.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @mckenzm can you please elaborate your question? The link you provide is to a specific header in the recovery guide document. How do you currently manage your devices?

**Comment by mckenzm** [comment]
It's a personal device, but "organisationally compliant", so my organisation may control bitlocker. Bitlocker is enabled but it boots to a login screen. In addition I am booting Grub on the same physical disk, if that helps. I would expect to be using a bitlocker PIN for the windows partition but this might not be possible if there are multiple OS's installed. In any case it appears to have settled down.

**Comment by paolomatarazzo** [comment]
Alright, I'll close the documentation issue as this is not a common configuration. If you have specific issues I invite you to open a support case.
