### ISSUE TITLE
Document Details

### ISSUE THREAD

**Issue by icaffeid** [MicrosoftDocs/windows-itpro-docs#11639]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d32382c1-3ebf-f08b-9d28-2524d333b377
* Version Independent ID: d32382c1-3ebf-f08b-9d28-2524d333b377
* Content: [Trusted Platform Module Technology Overview - Windows Security](https://learn.microsoft.com/en-gb/windows/security/hardware-security/tpm/trusted-platform-module-overview)
* Content Source: [windows/security/hardware-security/tpm/trusted-platform-module-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/hardware-security/tpm/trusted-platform-module-overview.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
assuming a test or misfire, so closing
