### ISSUE TITLE
.ocx File behaviour not Documented

### ISSUE THREAD

**Issue by danielmustardEHU** [MicrosoftDocs/windows-itpro-docs#11636]
I have noticed my Audit mode WDAC policy blocking the .ocx file types resulting in issues launching certain applications.

The documentation does not reference this known issue with .ocx files or offer any workarounds or solutions.   

This blocking action appears to produce no Code integrity AppControl logs, but as soon as the audit mode WDAC policy is removed from the machine the application is able to run its associated .ocx file without issue.

**Comment by aczechowski** [comment]
Thanks @danielmustardEHU for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

You could also [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) to send a signal to engineering about the issue.
