### ISSUE TITLE
Page is incomplete

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/windows-itpro-docs#11633]
It seems like this page isn't displaying properly or is missing information as it just kind of stops...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f653dd9-bcf7-a5c6-8625-fbc25e9c8fcc
* Version Independent ID: 0f653dd9-bcf7-a5c6-8625-fbc25e9c8fcc
* Content: [Group Policy Management of Windows Firewall with Advanced Security - Windows Security](https://learn.microsoft.com/en-us/windows/security/operating-system-security/network-security/windows-firewall/open-the-group-policy-management-console-to-windows-firewall-with-advanced-security)
* Content Source: [windows/security/operating-system-security/network-security/windows-firewall/open-the-group-policy-management-console-to-windows-firewall-with-advanced-security.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/operating-system-security/network-security/windows-firewall/open-the-group-policy-management-console-to-windows-firewall-with-advanced-security.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @ngangulyms
* Microsoft Alias: **nganguly**

**Comment by HotCakeX** [comment]
You're right, it looks like it was cut off somehow

![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/118815227/ad4e9b66-8c6f-4617-9d2c-e24ba1d31014)

**Comment by aczechowski** [comment]
I think that's just how that article is. It's been like that for at least three years (I didn't go further back in its history), and if you compare to the partner article [Group Policy Management of Windows Defender Firewall](https://learn.microsoft.com/windows/security/operating-system-security/network-security/windows-firewall/open-the-group-policy-management-console-to-windows-firewall), it's just a very short procedure on how to find the policies.

If anything there would be a broader fix to the larger set of content to bring a bunch of these little procedural articles together into a single one, or even question whether it's needed at all. But that's a larger project for another day.
