### ISSUE TITLE
Please remove the "Allow All" Rules in "Microsoft recommended block rules" 

### ISSUE THREAD

**Issue by HC-7** [MicrosoftDocs/windows-itpro-docs#11635]
Hello,

we are using WDAC for whitelisting purpose, including the "Microsoft recommended block rules". This approach works quite well.
Since some time, there are new allow all rules included in the "recommended block rules" file.
This doesn't really make sense in our point of view, as this contradicst the approach of a "block rules" file.
It only complicates the deployment process, because we need to remove these allow all entries. 

We are hence recommending the allow all entries from the file. If there are use cases that require an allow all rule, these entries can be added by other means.

Thanks and Best Regards

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 371fa98b-72ff-1d86-0a42-84192c9a8c08
* Version Independent ID: 371fa98b-72ff-1d86-0a42-84192c9a8c08
* Content: [Microsoft recommended block rules - Windows Security](https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/design/microsoft-recommended-block-rules)
* Content Source: [windows/security/application-security/application-control/windows-defender-application-control/design/microsoft-recommended-block-rules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/application-security/application-control/windows-defender-application-control/design/microsoft-recommended-block-rules.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @jsuther1974
* Microsoft Alias: **jsuther**

**Comment by jsuther1974** [comment]
This was done intentionally so that the policy can be used as-is and so it conforms with our documentation on creating deny policies. Please refer to this paragraph of the article

> The blocklist policy that follows includes "Allow all" rules for both kernel and user mode that make it safe to deploy as a standalone WDAC policy. On Windows versions 1903 and above, Microsoft recommends converting this policy to multiple policy format using the Set-CiPolicyIdInfo cmdlet with the -ResetPolicyId switch. Then, you can deploy it as a Base policy side-by-side with any other policies in your environment. To instead add these rules to an existing Base policy, you can merge the policy that follows using the Merge-CIPolicy cmdlet. If merging into an existing policy that includes an explicit allowlist, you should first remove the two "Allow all" rules and their corresponding FileRuleRefs from the blocklist policy.

**Comment by vinaypamnani-msft** [comment]
Thanks @jsuther1974. I'll close this issue.
