### ISSUE TITLE
Typo in the page's sidebar

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/windows-itpro-docs#11632]
Manager instead of Manage

![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/118815227/63e9cb5a-831b-458f-9cdd-9d4f8743937c)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 92fdc530-003f-eb25-15a3-8622502e53d1
* Version Independent ID: 4c8edcb5-53c3-3242-6eca-5ac24f3f8c30
* Content: [Manage TPM lockout - Windows Security](https://learn.microsoft.com/en-us/windows/security/information-protection/tpm/manage-tpm-lockout)
* Content Source: [windows/security/information-protection/tpm/manage-tpm-lockout.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/tpm/manage-tpm-lockout.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
Thanks @HotCakeX! I've fixed the issue, changes will be live later today.
