### ISSUE TITLE
AAD joined devices and 3rd party CA (key trust)

### ISSUE THREAD

**Issue by LijuV-MSFT** [MicrosoftDocs/windows-itpro-docs#11642]
This page mentions Accessing on-premises resources from an Azure AD Joined device does require special configuration when using a third-party CA to issue domain controller certificates, and then refers to another page about smart card logon with 3rd party CAs.

Can someone please explain what the additional requirements are that are not covered by [Configure domain controller certificates](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-validate-pki#configure-domain-controller-certificates) and [Requirements for domain controller certificates from a third-party CA](https://learn.microsoft.com/en-us/troubleshoot/windows-server/windows-security/requirements-domain-controller) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f64c6e7-4002-fe69-b8a0-aa3539949ee6
* Version Independent ID: 3e71c3a7-6654-d31a-37eb-7cc84d0b8a72
* Content: [Windows Hello for Business known deployment issues - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-issues#azure-ad-joined-device-access-to-on-premises-resources-using-key-trust-and-third-party-certificate-authority-ca)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-deployment-issues.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-deployment-issues.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @LijuV-MSFT and thank you for the feedback. As we discussed offline, please follow up with Support to determine the accuracy of the statement and feel free to reopen the issue once we get more clarity about this scenario. Much appreciated!
