### ISSUE TITLE
The provisioned apps chart is missing

### ISSUE THREAD

**Issue by daniel-davila** [MicrosoftDocs/windows-itpro-docs#11646]
Built-in Provisioned content from this page "https://github.com/MicrosoftDocs/windows-itpro-docs/blob/fa1414a7716f274200e9b7829124b2afac29ac20/windows/application-management/provisioned-apps-windows-client-os.md" is no longer available in the current version

https://learn.microsoft.com/en-us/windows/application-management/provisioned-apps-windows-client-os. This page navigates to an overview page instead.

https://github.com/MicrosoftDocs/windows-itpro-docs/assets/79564896/59c2c6d3-e38d-4db7-b3a9-52d9a6b0e8d6

**Comment by aczechowski** [comment]
Thanks for the note @daniel-davila - that linked article was removed and redirected, so just need to adjust the link. I'll take care of that shortly. This issue will auto-close when the pull request merges, and then the change will go live within one day.
