### ISSUE TITLE
Missing data after 7/25 document update. 

### ISSUE THREAD

**Issue by rrice2004** [MicrosoftDocs/windows-itpro-docs#11640]
After the document update on 7/25, the following data is missing. Does this data no longer apply to the autopatch reports for troubleshooting purposes? Was training a co-worker on this and i copied the data from the document to my One Note, so I had it, but nowhere in the reports can we no longer find this data for unpatched devices.

Sub status | Description
-- | --

- Insufficient Usage | Devices must have   at least six hours of usage, with at least two hours being continuous.

- Low Connectivity | Devices must have   a steady internet connection, and access to Windows   update endpoints.

- Out of Disk Space | Devices must have   more than one GB (GigaBytes) of free storage space.

- Not Deployed | Windows Autopatch   doesn't update devices that haven't yet been deployed.

- Not On Supported   Windows Edition | Devices must be on   a Windows edition supported by Windows Autopatch. For more information, seeprerequisites.

- Not On Supported   Windows Build | Devices must be on   a Windows build supported by Windows Autopatch.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1434106d-6da6-bdbd-1429-ffdd90c0680e
* Version Independent ID: 1434106d-6da6-bdbd-1429-ffdd90c0680e
* Content: [Device alerts - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/windows-autopatch/operate/windows-autopatch-device-alerts)
* Content Source: [windows/deployment/windows-autopatch/operate/windows-autopatch-device-alerts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopatch/operate/windows-autopatch-device-alerts.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @tiaraquan
* Microsoft Alias: **tiaraquan**

**Comment by tiaraquan** [comment]
Hi @rrice2004

Yes, after GA, we changed what data the reports pull. You can find more information about quality and feature update reports in the
[Windows quality and feature update reports overview](https://learn.microsoft.com/en-us/windows/deployment/windows-autopatch/operate/windows-autopatch-groups-windows-quality-and-feature-update-reports-overview) article.

If you have more specific question or need more support, please [submit a support request](https://learn.microsoft.com/en-us/windows/deployment/windows-autopatch/operate/windows-autopatch-support-request).
