### ISSUE TITLE
FIPS for Windows 11

### ISSUE THREAD

**Issue by cyberguyusa** [MicrosoftDocs/windows-itpro-docs#11658]
[Enter feedback here]
I see in other places talking about the Windows11 FIPS validation being completed in July but don't see that OS listed here.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08ea20b1-bbb3-1249-e6b1-eb7e6721b641
* Version Independent ID: 08ea20b1-bbb3-1249-e6b1-eb7e6721b641
* Content: [Federal Information Processing Standard (FIPS) 140 Validation - Windows Security](https://learn.microsoft.com/en-US/windows/security/security-foundations/certification/fips-140-validation)
* Content Source: [windows/security/security-foundations/certification/fips-140-validation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/security-foundations/certification/fips-140-validation.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @cyberguyusa can you please provide the source?

**Comment by paolomatarazzo** [comment]
Closing the issue due to a lack of response.
