### ISSUE TITLE
Non of the methods applied for my windows 11 home 22H2

### ISSUE THREAD

**Issue by KDAM71** [MicrosoftDocs/windows-itpro-docs#11653]
[Enter feedback here]

Non of the methods applied for my windows 11 home 22H2.
I tried to disable credential guard on my computer. Neither the GP value nor the registry value exists on my computer.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @KDAM71 , Credential Guard doesn't apply to Home Edition as the device cannot be domain joined. Can you please clarify what you are trying to disable?

**Comment by KDAM71** [comment]
Hello @paolomatarazzo , I was trying to find a solution for a lot of 6155 events.
https://learn.microsoft.com/en-us/answers/questions/961608/event-id-6155-(the-lsa-package-is-not-signed-as-ex?orderBy=Helpful
