### ISSUE TITLE
Headless Miracast Devices

### ISSUE THREAD

**Issue by AgentMrQ** [MicrosoftDocs/windows-itpro-docs#1165]
I would like to Miracast over Infrastructure for some headless appliances, like projectors. Using native wireless Miracast it works like a champ. 4k 60fps. But because the device is off my enterprise network I can't manage it. Is there a method to allow Miracast over Infrastructure to Miracast supported devices without the Windows network operating system? Example, use the Miracast protocol on a Windows 10 supported device to discover and cast to projectors connected via Ethernet Intranet. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90f7e378-18d2-d2fc-e7f3-b7bd8c32d5b9
* Version Independent ID: 6d631120-af33-6ebc-d6fb-1d0431883bae
* Content: [Miracast on existing wireless network or LAN](https://docs.microsoft.com/en-us/surface-hub/miracast-over-infrastructure#feedback)
* Content Source: [devices/surface-hub/miracast-over-infrastructure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/miracast-over-infrastructure.md)
* Product: **surface-hub**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@AgentMrQ I checked with the engineering team, and they said this is possible. "We have published the protocol needed to perform this functionality on any device. They should make a request to their favorite projector vendor and request they add the functionality. "

The protocol: https://msdn.microsoft.com/en-us/library/mt796768.aspx

The "Building best-in-class Miracast solutions with Windows 10" guide: http://download.microsoft.com/download/3/F/9/3F9F0453-04AE-4E4B-87EF-729FF931C1F9/Building best-in-class Miracast solutions with Windows 10 .docx
