### ISSUE TITLE
Windows 11 Home

### ISSUE THREAD

**Issue by danieloateslee** [MicrosoftDocs/windows-itpro-docs#11654]
[Enter feedback here]
Do you need to update this page with Windows 11 Home edition? as home edition no supports the use of BitLocker.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bdbcfb77-db1e-3979-a7b0-d4885dc6ab05
* Version Independent ID: bdbcfb77-db1e-3979-a7b0-d4885dc6ab05
* Content: [BitLocker overview - Windows Security](https://learn.microsoft.com/en-us/windows/security/operating-system-security/data-protection/bitlocker/)
* Content Source: [windows/security/operating-system-security/data-protection/bitlocker/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/operating-system-security/data-protection/bitlocker/index.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @danieloateslee and thank you for the feedback. Currently, we don't track Windows Home edition applicability for Windows security features on Microsoft Learn. We may include that information in the future.
