### ISSUE TITLE
Please include two further importante info to this page

### ISSUE THREAD

**Issue by alexandreoorschot** [MicrosoftDocs/windows-itpro-docs#11659]
[Enter feedback here]

Please advise at page: https://learn.microsoft.com/en-us/windows/security/identity-protection/remote-credential-guard , that if the server your are login in has RDS licesing, it will not work unless you are in the local admin group, it will NOT work if you are only RDP user as usual, good source: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1483
more source:https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-vdi-supported-config#remote-credential-guard

Also, if you have at policies (remote desktop services/remote desktop session host/security) the setting "require use os specific security layer for remote (RDP) connections" to "enabled" it CANNOT be value "rdp", if so, in the etl trace you will see a TLS error,
hence go there and disable this setting, OR set to "negotiate" to fix the issue. usually the message says the follwing when you are trying to use Remote guard and this setting is to "rdp"
"the remote computer doesn't support restricted administration mode for remote guard" even if you already create the requeired dword "DisableRestrictedAdmin" value 0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c826587d-2e65-083f-254d-75f188158f08
* Version Independent ID: 746596b5-c1df-9ea0-abcc-f6ff97874e40
* Content: [Protect Remote Desktop credentials with Windows Defender Remote Credential Guard - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/remote-credential-guard)
* Content Source: [windows/security/identity-protection/remote-credential-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/remote-credential-guard.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @alexandreoorschot and thank you for the feedback. As we're updating the Remote Credential Guard article, we'll consider including the proposed changes.

**Comment by paolomatarazzo** [comment]
@alexandreoorschot regarding your 2nd feedback, I cannot repro the issue. I would suggest opening a support case for the 2nd item.
