### ISSUE TITLE
Cannot download Windows Device Recovery Tool

### ISSUE THREAD

**Issue by ahmed-wajid** [MicrosoftDocs/windows-itpro-docs#11655]
We need to reset our HoloLens Gen1 since the device password has expired, and we are unable to reset the password using the Device Portal, because it fails with an error `Unable to pair Device`. Hence, we prefer to reset the device, but we are no longer able to download the WDRT anymore, since the Storage account does not have Public Access enabled. 

```
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>
Public access is not permitted on this storage account. RequestId:52722389-401e-006d-6041-d06ef8000000 Time:2023-08-16T13:00:46.5452803Z
</Message>
</Error>
```

**Comment by aczechowski** [comment]
Thanks @ahmed-wajid for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by ahmed-wajid** [comment]
I posted in this repo, because the link in 
https://support.microsoft.com/en-us/windows/windows-device-recovery-tool-faq-2b186f06-7178-ed11-4cb6-5ed437f0855b

is misleading, and leads to a broken link and is similar to #5281

**Comment by aczechowski** [comment]
Thanks @ahmed-wajid - that SMC article probably needs to be retired. It hasn't been touched in 6 years and refers to Windows Mobile. The referenced [HoloLens recovery article](https://learn.microsoft.com/hololens/hololens1-recovery) doesn't refer to it anymore, and has other recovery options available.

**Comment by ahmed-wajid** [comment]
Thank you for your response @aczechowski 

I'm stuck with no other option other than to use WDRT as mentioned in the link you provided [recovery](https://learn.microsoft.com/en-us/hololens/hololens1-recovery#recover-your-hololens), which leads to the WDRT tool not being available.
