### ISSUE TITLE
Either alert text or fix the technology so Google Workspace works Configure federated sign-in for student assigned devices

### ISSUE THREAD

**Issue by l2g2h** [MicrosoftDocs/windows-itpro-docs#11668]
Please do one of the two following for both websites
https://learn.microsoft.com/en-us/education/windows/federated-sign-in?tabs=intune
https://learn.microsoft.com/en-us/education/windows/configure-aad-google-trust

1. update this documentation with a notice
2. update the technological solution so in some way this works such as getting windows login off of basic authentication ws-fed/ws-trust

I setup federation with Google Workspace https://learn.microsoft.com/en-us/education/windows/configure-aad-google-trust then set up the sign in https://learn.microsoft.com/en-us/education/windows/federated-sign-in?tabs=intune only to later find out it doesn't work. If there was an alert on the page others would be saved from the PITFA I just dealt with in then after thorough testing to roll everything back.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4889cf2-86cb-9607-32d5-2851f68f63f6
* Version Independent ID: d4889cf2-86cb-9607-32d5-2851f68f63f6
* Content: [Configure federated sign-in for Windows devices - Windows Education](https://learn.microsoft.com/en-us/education/windows/federated-sign-in?tabs=intune)
* Content Source: [education/windows/federated-sign-in.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/education/windows/federated-sign-in.md)
* Product: **windows-client**
* Technology: **itpro-edu**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Closing as this is a duplicate
