### ISSUE TITLE
Unable to complete consent at step 3.

### ISSUE THREAD

**Issue by yavordanev** [MicrosoftDocs/windows-itpro-docs#11669]
Clicking Accept at step 3 as per the section "Enable the Microsoft PIN Reset Service in your Azure AD tenant" goes nowhere. I can see the following error in the browser console:

**_Failed to launch 'ms-appx-web://microsoft.aad.brokerplugin/9115dd05... because the scheme does not have a registered handler._**

I'm using a global admin account and I've tried various browsers, but I haven't been able to complete the consent in any.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9dae9da-eaf0-c209-7c65-be8d2c1ada12
* Version Independent ID: 28b6788d-7982-23c2-5f19-f80690ebc0ce
* Content: [PIN reset - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset?tabs=gpo#confirm-that-pin-recovery-policy-is-enforced-on-the-devices)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @yavordanev, that is expected. You should see the two service principals registered in your Azure AD tenant. Can you please confirm?

**Comment by paolomatarazzo** [comment]
Verifying on my end the behavior, thanks for the heads up. In the past, it used to return a blank page so I misunderstood the issue.

**Comment by yavordanev** [comment]
> Hello @yavordanev, that is expected. You should see the two service principals registered in your Azure AD tenant. Can you please confirm?

Yes, I can see both.

**Comment by yavordanev** [comment]
> Verifying on my end the behavior, thanks for the heads up. In the past, it used to return a blank page so I misunderstood the issue.

OK, so I'm assuming that once the service principals show up in Entra ID that's a confirmation that the process has completed successfully, regardless of the second consent being "stuck"? It might be helpful to add a little note to the documentation, so people don't get confused and think that something's wrong. For me it didn't end with a blank page, but with the accept prompt slightly faded and the progress indicator at the top moving across in a loop:

![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/62838656/99f3c42f-284f-46c2-bfd9-52115a582195)

Thanks.

**Comment by paolomatarazzo** [comment]
@yavordanev I see the same in my test tenants. Correct, once the service principals are registered, you are good to go. However, that consent being stuck is a recent behavior. I'm trying to reach out internally to determine the behavior is expected (I hope it's not), then I will update the documentation. In the meantime, thank you for the feedback.
