### ISSUE TITLE
Either alert text or fix the technology so Google Workspace works Configure federated sign-in for student assigned devices

### ISSUE THREAD

**Issue by l2g2h** [MicrosoftDocs/windows-itpro-docs#11667]
Please do one of the two following for both websites
https://learn.microsoft.com/en-us/education/windows/federated-sign-in?tabs=intune
https://learn.microsoft.com/en-us/education/windows/configure-aad-google-trust

1. update this documentation with a notice
2. update the technological solution so in some way this works such as getting windows login off of basic authentication ws-fed/ws-trust

I setup federation with Google Workspace https://learn.microsoft.com/en-us/education/windows/configure-aad-google-trust then set up the sign in https://learn.microsoft.com/en-us/education/windows/federated-sign-in?tabs=intune only to later find out it doesn't work. If there was an alert on the page others would be saved from the PITFA I just dealt with in then after thorough testing to roll everything back.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aab824fb-b795-518a-8d52-7490975ab5ac
* Version Independent ID: aab824fb-b795-518a-8d52-7490975ab5ac
* Content: [Configure federation between Google Workspace and Azure AD - Windows Education](https://learn.microsoft.com/en-us/education/windows/configure-aad-google-trust)
* Content Source: [education/windows/configure-aad-google-trust.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/education/windows/configure-aad-google-trust.md)
* Product: **windows-client**
* Technology: **itpro-edu**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @l2g2h and thank you for the *constructive* feedback. Can you please elaborate what didn't work? The steps have been validated multiple times, so I would suggest you checking again. Without further information, I can't add any disclaimer or updates to the documentation. Also, you can open a support request to get assistance.

**Comment by l2g2h** [comment]
Thank you @paolomatarazzo for the clear request. I forgot to include it.

The federation with Google Workspace Education only works for SaaS. 
https://learn.microsoft.com/en-us/education/windows/configure-aad-google-trust

Does not work for Windows/Intune.
https://learn.microsoft.com/en-us/education/windows/federated-sign-in?tabs=intune
https://cloud.google.com/architecture/authenticating-corporate-users-in-a-hybrid-environment

M365 for Education/A3 & Google Workspace Education. 

Request:
Update both urls that this does not work with/for Windows sign in which is functionally unacceptable it prevents use of Windows machines.

If @paolomatarazzo  there are steps that have been validated multiple times then Microsoft needs to raise their quality of documentation to include the screenshots of the documentation. Without that proof I do not believe Microsoft got the Google Workspace federation to work with Windows until Microsoft updates the legacy auth login to Windows. Again. Microsoft needing to raise their own bar. Without this customers are thinking this works instead being lied to then having to cancel the licenses because of being mislead.
https://cloud.google.com/architecture/authenticating-corporate-users-in-a-hybrid-environment

**Comment by paolomatarazzo** [comment]
@l2g2h Both documentations contain an animated gif showing federation working between GW and AAD, I'm not sure which other "proof" you're asking for. It works with Windows and Intune. Please check the prerequisites in the documentation to determine whether the OS you're using is supported.

**Comment by paolomatarazzo** [comment]
here's the *proof*:
https://github.com/MicrosoftDocs/windows-itpro-docs/assets/74918781/f87d74bd-55ae-4e2a-aa15-9e449c2458e2

**Comment by l2g2h** [comment]
Thank you very much for the gif that is reassuring that it works/worked.

**Comment by l2g2h** [comment]
What I'm further requesting is screenshots re configurations for the mentioned Federations. 

I see some documentation shows admin side screenshots and some don't just instead text of the configurable pieces. Yes I understand technology changes the GUI may change. I've configured all the elements & not had success so I'm working to compare to what Microsoft configured on all sides because it's outright bewildering. 

Yes, I understand can use a support ticket; however, lately support takes in excess of 1 month to initially get started, an additional 3-4 months to get escalated and transferred to the right knowledgeable resource, then ultimately told to go work with the 3rd party because Microsoft support across all paid options (including Msft Partner support) doesn't resolve on any production timeline. 

It would be so much nicer if documentation was simply up to date & included screenshots because the support options aren't worth engaging. I had a 5 month partner ticket that got nowhere with all the escalation, transferring then being told it was on the 3rd party. There was a time when Microsoft support was worth engaging.

**Comment by paolomatarazzo** [comment]
what exactly are you "requesting"... or rather asking for? an output of a powershell command? in our documentation, we don't include screenshots of a 3rd party solution like GW. So if it could help, I can share how I configured the test tenant used for documentation purposes. I ask to be polite and courteous. Ultimately, I'm not part of support and trying to help out.

**Comment by paolomatarazzo** [comment]
this is all you see from entra.microsoft.com 
<img width="263" alt="image" src="https://github.com/MicrosoftDocs/windows-itpro-docs/assets/74918781/9a076075-31fd-41e6-84ba-82d5f61dc563">
