### ISSUE TITLE
Erros gramaticais de português.

### ISSUE THREAD

**Issue by gupdelf** [MicrosoftDocs/windows-itpro-docs#11666]
https://learn.microsoft.com/pt-br/windows/security/application-security/application-isolation/microsoft-defender-application-guard/faq-md-app-guard

no link em pt-br, há alguns erros de gramática:

Erro 1:
"Minha configuração de rede usa um proxy e estou executando um "Não é possível resolve URLs Externas do Navegador MDAG: Erro: err_connection_refused". Como fazer resolve isso?"

Erro 2:
"Como fazer confiar em um subdomínio na minha lista de sites?"

Erro 3:
"Estou encontrando problemas de fragmentação de TCP e não consigo habilitar minha conexão VPN. Como fazer corrigir esse problema?"

Não parei para analisar todos os erros gramaticais da página, mas apresentei os identificados. 
Obrigado!

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação de problema do learn.microsoft.com ➟ GitHub.*

* ID: fd297991-fd26-68b6-516d-7c25732daf07
* Version Independent ID: fd297991-fd26-68b6-516d-7c25732daf07
* Content: [Perguntas frequentes - Microsoft Defender Application Guard (Windows 10) - Windows Security](https://learn.microsoft.com/pt-br/windows/security/application-security/application-isolation/microsoft-defender-application-guard/faq-md-app-guard)
* Content Source: [windows/security/application-security/application-isolation/microsoft-defender-application-guard/faq-md-app-guard.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/application-security/application-isolation/microsoft-defender-application-guard/faq-md-app-guard.yml)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thank you @gupdelf for the feedback. My apologies for replying in English. I've filed a bug with your comments to our global services team (356020). I'm going to close this issue since there's nothing further we can do at this time. I really appreciate you taking the time to share this feedback, and trust that changes will be incorporated in the near future.
