### ISSUE TITLE
How to set non-SCCM application as trusted installer?

### ISSUE THREAD

**Issue by AHaugk** [MicrosoftDocs/windows-itpro-docs#1167]
I tried out the steps in this guide but my windows 10 won't accept the policies.
When I create a rule collection of the type "MangedInstaller", windows skips these rules during import.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07fdf27b-1ead-1b6e-c793-a2ad259a4f6a
* Version Independent ID: 8da1f371-73d4-c79f-a97b-80170e7860af
* Content: [Deploy Managed Installer for Windows Defender Device Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-managed-installer)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-managed-installer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-managed-installer.md)
* Product: **w10**
* GitHub Login: @mdsakibMSFT
* Microsoft Alias: **justinha**

**Comment by baramundi-ahaugk** [comment]
Is there any news on this subject?
The question has still not been answered and there is no useful documentation.

**Comment by AHaugk** [comment]
Is there any news on this subject?
The question has still not been answered and there is no useful documentation.

**Comment by Justinha** [comment]
@AHaugk sorry for delay. More information will be needed to help troubleshoot, such as what versions of Windows 10 are you trying this on, what applications are you trying to control, what events appear in AppLocker log in Event Viewer, and more. For expert help with this, I suggest you open a case with Customer Service and Support.

**Comment by AHaugk** [comment]
@Justinha Thanks for the quick answer.
I have tried to create my own (signed) EXE as Managed Installer. I created an AppLocker policy via console, exported it, deleted the entry in the console. Then I opened the export, changed the type to ManagedInstaller and imported it again. However, the entry is not taken over but ignored.

**Comment by Justinha** [comment]
To confirm, were you were able to set the audit only enforcement mode rule and enable the Managed installer option in the WDAC policy? Are you able to set the AppLocker filter driver to autostart? 

I'll ask our engineering partners if we can add some troubleshooting content to help readers investigate why it's not working. In the meantime, Customer Support will be a better option for you to get unblocked. They can set up a repro of your environment and so on.

**Comment by peterjlay** [comment]
No need to set this up on current branch for WDAC Policy, Managed Installer for SCCM is already setup.

See this statement: "Once a policy is successfully processed on a client PC, Configuration Manager is configured as a Managed Installer on that client. Software deployed through it, after the policy processes, is automatically trusted. Software installed by Configuration Manager before the Windows Defender Application Control policy processes is not automatically trusted."

Source: https://docs.microsoft.com/en-au/sccm/protect/deploy-use/use-device-guard-with-configuration-manager#before-you-start

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@AHaugk - From our understanding, the issue you raised has been answered by Justinha and peterjlay. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
