### ISSUE TITLE
For SCRIL Automatic Password Renewal - 2016 Domain or Forest Functional Level ?

### ISSUE THREAD

**Issue by SB-o-matic** [MicrosoftDocs/windows-itpro-docs#11679]
The article mentions that automatic rollover of 128-bit password is possible. But states that 2016 "domain forest" functional level is required. These are 2 different things combined into one statement. Is it 2016 Domain Functional Level or 2016 Forest Functional level that is required?

![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/44109318/52534c88-3d17-4b4d-a155-cd9141307375)

(admin edit: add article metadata for proper linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca080bd-ed37-60a8-ec22-b1929166ff0c
* Version Independent ID: d2742e0c-9d66-4b1f-8555-a1fb1546455b
* Content: [Password-less strategy - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/passwordless-strategy#configure-user-accounts-to-disallow-password-authentication)
* Content Source: [windows/security/identity-protection/hello-for-business/passwordless-strategy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/passwordless-strategy.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Thank you for the feedback @SB-o-matic, I'll adjust by removing `forest`.
