### ISSUE TITLE
ANONYMOUS LOGON on event id 4738

### ISSUE THREAD

**Issue by zbalkan** [MicrosoftDocs/windows-itpro-docs#11682]
In the [documentation](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4738.md), the subject is mentioned in high level. But in real life, we can see password reset events done by ANONYMOUS LOGON. It does not make sense when one sees the log.

What does that mean when ANONYMOUS LOGON resets a domain account's password?

(admin edit: add article metadata for proper linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ccd81722-4e7e-1da0-e3f0-73fafd0c0ac5
* Version Independent ID: 7899a9fa-e5b0-9563-de93-b3a40b3494ff
* Content: [4738(S) A user account was changed. - Windows Security](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4738)
* Content Source: [windows/security/threat-protection/auditing/event-4738.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4738.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @zbalkan for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as we're in the process of retiring the audit event articles, and don't have the resources to make any changes before doing so. (The articles will still be published but under the "[previous-versions](https://learn.microsoft.com/previous-versions/windows/)" area of Microsoft Learn.)
