### ISSUE TITLE
Irritating

### ISSUE THREAD

**Issue by ItsDuGuRu** [MicrosoftDocs/windows-itpro-docs#11690]
Where do I find this "stuff" on my Win 10 Pro, no domain, device. Hello, I've spent hours looking for policies that are allegedly contained in "Computer Configuration\Windows Settings\Security Settings\Local Policies\Security Options". I've only found success with regedit and certainly have little experience in understanding this tool. I have searched "Computer Management," created an MMC, and added random snapins searching for similar verbiage as presented in the text, and Nada. I understand the reading materials but relating them to the management tools on my system is for all intent and purpose nonexistent. Please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f003f92-700a-affd-ae96-7b57150f71d6
* Version Independent ID: 0e48a1a8-3e51-e65a-6da0-e63b1f183e44
* Content: [User Account Control Admin Approval Mode for the Built-in Administrator account - Windows Security](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-account-control-admin-approval-mode-for-the-built-in-administrator-account)
* Content Source: [windows/security/threat-protection/security-policy-settings/user-account-control-admin-approval-mode-for-the-built-in-administrator-account.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/user-account-control-admin-approval-mode-for-the-built-in-administrator-account.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @ItsDuGuRu for taking the time to share this with the Windows documentation team for IT pros. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time - this content is specific to system administrators that are managing Windows for an organization. (And we're actually in progress to retire this set of content to the Windows previous versions site.)
