### ISSUE TITLE
Confusing documentation about deferral policies

### ISSUE THREAD

**Issue by aurelschwitter** [MicrosoftDocs/windows-itpro-docs#1169]
Please specify why you chose 120 days deferral additional to using the SAC Branch, which would defer the upgrade to 8 Months. Why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa00c00e-b9e4-9f11-b553-519e51fb9cd0
* Version Independent ID: a5c45e00-23cc-8f0d-334d-45d8796e5220
* Content: [Build deployment rings for Windows 10 updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-deployment-rings-windows-10-updates)
* Content Source: [windows/deployment/update/waas-deployment-rings-windows-10-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-deployment-rings-windows-10-updates.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
@shortpatti please reassign to @jaimeo . Thanks!

**Comment by egallagh** [comment]
I forgot to add that this is covered in some ways in the previous topic: Prepare Servicing Strategy for Windows 10 Updates.

**Comment by aurelschwitter** [comment]
Dear @egallagh 

I fully understand your explanation, and yes, this has already been covered and explained pretty well on the docs page. 
If I understand you correctly, the long deferral time was intended and not a mistake.

While a period this long may be necessary for critical applications, I think you are giving out a wrong message to it-pro's wanting to implement windows update for business. 
When Microsoft releases a feature update to the "Semi-Annual Channel", Microsoft claims that it's ready for use (not "ready for testing") in organizations. In that case, adding more than 1-2 months of deferral to the feature update will not help you a lot for the broad deployment (pausing is always possible).

However, I know that providing an example that's helpful to everyone is challenging.

If you want to keep the example with 8 months deferral, I propose adding an additional column to the table to clarify how long a feature update will be deferred in total. (Semi Annual Channel 4 Months + Deferral Period). The following table is a draft of my proposal (see column in italics):

| Deployment ring | Servicing channel              | Deferral for feature updates | Deferral for quality updates | _Total deferral period for feature updates_ | Example                                                                                                                                   |
| --------------- | ------------------------------ | ---------------------------- | ---------------------------- | -------------------------------- |-------------------------------------------------------------------------------------------------------------------------------------------|
| Preview         | Windows Insider Program        | None                         | None                         | _None_                             | A few machines to evaluate early builds prior to their arrival to the semi-annual channel                                                 |
| Targeted        | Semi-annual channel (Targeted) | None                         | None                         | _None_                             | Select devices across various teams used to evaluate the major release prior to broad deployment                                          |
| Broad           | Semi-annual channel            | 120 days                     | 7-14 days                    | _8 Months_                         | Broadly deployed to most of the organization and monitored for feedback<br />Pause updates if there are critical issues                   |
| Critical        | Semi-annual channel            | 180 days                     | 30 days                      | _10 Months_                        | Devices that are critical and will only receive updates once they've been vetted for a period of time by the majority of the organization |

**Comment by egallagh** [comment]
Hi @aurelschwitter 
I understand your point, but I do disagree.
IMHO when Microsoft releases to the semi annual channel the OS is considered to be stable for business use, but that does not mean it is compatible with all the software you are using within your organization. You may have narrow market vertical apps or in house developed software that would be impossible for Microsoft to test against. You may also have a particular combination of commercial applications the exact combination of which has not been tested against. You could also have applications that may need their own upgrades to be compatible with the new OS build.
For example, I have a client that has some systems with older video subsystems that had no Windows 10 drivers. The 8.1 drivers worked fine. However the systems became unstable with Windows 10 1803.
Microsoft has always recommended testing their software against what you use in your organization.
Hope that helps.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@aurelschwitter - From our understanding, the issue you raised has been answered by egallagh. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by andrewwillett** [comment]
I agree with @aurelschwitter, clarity is needed and a total effective deferred period for updates should be added, as the stated deferral periods result in some extended deferral periods that may not be intended or desirable.
