### ISSUE TITLE
LetAppsRunInBackground: 0 (Default) is Empty .

### ISSUE THREAD

**Issue by MyklSandusky-XMS** [MicrosoftDocs/windows-itpro-docs#11693]
The exist line is
0 (Default): .

I suspect it should be:
0 (Default): User Control.

(admin edit: remove public repo link and add article metadata for proper linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d29cfe6-cd94-95d7-b635-80bf356829fd
* Version Independent ID: 699e70c4-bf24-1200-b6cb-451aa547437b
* Content: [Privacy Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-privacy#letappsruninbackground)
* Content Source: [windows/client-management/mdm/policy-csp-privacy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-privacy.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @MyklSandusky-XMS - the CSP reference docs are mostly automated now, see [Contributing to the CSP reference articles](https://learn.microsoft.com/windows/client-management/mdm/contribute-csp-reference). So the issue may exist in the underlying source DDF or ADMX. But I think it might be best for us to first review our automation to make sure, given there's a single period in that table cell.

**Comment by vinaypamnani-msft** [comment]
@MyklSandusky-XMS I reviewed this, and can confirm that the missing description for value 0 is indeed in the DDF file. Can you [Send feedback with the Feedback hub app](https://learn.microsoft.com/en-us/windows/client-management/mdm/contribute-csp-reference#send-feedback-with-the-feedback-hub-app) for this? It's best that you submit the feedback so you can get notified of any updates. I'll close this issue as the doc will be auto-updated once the DDF file is updated with the appropriate value.
