### ISSUE TITLE
Incorrect app name for Conditional Access exclusion

### ISSUE THREAD

**Issue by Wh00T** [MicrosoftDocs/windows-itpro-docs#11692]
When using Conditional Access, the article states:

_[...] Conditional Access policies to control access need to exclude the [Universal Store Service APIs and Web Application, AppID 45a330b1-b1ec-4cc1-9161-9f03992aa49f](https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/verify-first-party-apps-sign-in#application-ids-of-commonly-used-microsoft-applications), from their Conditional Access policies [...]_

But there is no app called "Universal Store Service APIs and Web Application".
In the article that is linked, the AppId "45a330b1-b1ec-4cc1-9161-9f03992aa49" belongs to "Windows Store for Business".
However, there is an app with a similar name called  "Universal Store Native Client" with AppId "268761a2-03f3-40df-8a8b-c3db24145b6b".

![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/1562582/ff1fe3d4-b40c-47c4-923b-f07b0fc55b7e)

Which one(s) do we need to exclude now?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6443e532-640d-81c0-8215-b711bd1977d4
* Version Independent ID: fc504984-91d7-b586-04ec-4c751fb48998
* Content: [Windows subscription activation - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **windows-client**
* Technology: **itpro-fundamentals**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @Wh00T and I apologize over the delay. After some research, we have determined that it could have either name and it just depends on the tenant. I have added both names to the instructions to provide clarity. It should be live either later today or tomorrow.
