### ISSUE TITLE
How to activate Windows Enterprise digital licence on device who is in Autopilot and installed with VLK iso 

### ISSUE THREAD

**Issue by EmirOmeragic** [MicrosoftDocs/windows-itpro-docs#11704]
We prepared bunch of laptops with VLK ISO and put them in AAD Autopilot group.
When new user with E3 licence logs into laptop about 25% of devices give error code activating windows 0x8007007b
Only thing that solves the problem is typing VLK Activation Key instead of picking up digital licence key from user M365 licence.

What is root solution? Reinstall with vanila Windows 10 ISO?
Run some version of slmgr?

**Comment by aczechowski** [comment]
Thanks @EmirOmeragic  for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
