### ISSUE TITLE
Reorder Policies Alphabetically

### ISSUE THREAD

**Issue by Brachus12** [MicrosoftDocs/windows-itpro-docs#11709]
Could these Policies please be reordered alphabetically to match what someone would actually see when viewing the policy settings for the GPO itself?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 035d52b5-656c-7296-6c4e-917e2da821b3
* Version Independent ID: 035d52b5-656c-7296-6c4e-917e2da821b3
* Content: [User Account Control settings and configuration - Windows Security](https://learn.microsoft.com/en-us/windows/security/application-security/application-control/user-account-control/settings-and-configuration?tabs=intune)
* Content Source: [windows/security/application-security/application-control/user-account-control/settings-and-configuration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/application-security/application-control/user-account-control/settings-and-configuration.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by RAJU2529** [comment]
@Brachus12, I will rearrange according to group policy, and give me one week time.
