### ISSUE TITLE
event-4625 without ip and port

### ISSUE THREAD

**Issue by ThouSandThorChang** [MicrosoftDocs/windows-itpro-docs#11701]
WinServer 2012 and below, NTLM login does not have IP and Port records. This issue has been fixed in 2016. May I know if there are any related patch packs for 2012 and below.

**Comment by aczechowski** [comment]
Thanks @ThouSandThorChang for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
We have an article on [Event 4625](https://learn.microsoft.com/windows/security/threat-protection/auditing/event-4625) but I don't see anything in it pertaining directly to your questions. And we're in the process to retire this article to the [Windows previous versions](https://learn.microsoft.com/previous-versions/windows/) site.

**Comment by ThouSandThorChang** [comment]
thanks
