### ISSUE TITLE
Windows Hello for Business Deployment Prerequisite Overview table is wrong

### ISSUE THREAD

**Issue by retogobat** [MicrosoftDocs/windows-itpro-docs#11705]
As of my understanding most part of the table listing the prerequisistes is wrong:
E.q: Cloud Kerberos trust Group Policy or Modern managed, needs at least Windows 10 21H2 or Windows 11
Domain Controller Version also needs to be on version 2016

Can someone update the docs and correct the information?

(admin edit: adding article metadata for proper linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87e5f5f1-16cf-57e2-bdfc-b090d90437b1
* Version Independent ID: 1662c47f-12cb-147d-25f0-dee98b6c7722
* Content: [Windows Hello for Business Deployment Prerequisite Overview - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification#hybrid-deployments)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-identity-verification.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-identity-verification.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @retogobat and thank you for the feedback. Can you please be more specific? The items that you point out are actually correct. Please check what are the currently supported Windows versions here: https://learn.microsoft.com/en-us/windows/release-health/supported-versions-windows-client

**Comment by retogobat** [comment]
Ok let's be more specific:
The table [here ](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification#hybrid-deployments)says, any supported version of Windows 10 and 11 is working with cloud trust. According to this [page](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust#prerequisites): only Windows 10 21H2 and 11 are supported. Therefore all LTSB/LTSC editions are not working, but in my understanding they are still supported...

Additionally, again, the mentioned table says, you can use any Domain Controller version for cloud trust, but on this [page](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-guide#deployment-and-trust-models): the docs clearly say: "have an adequate number of 2016 domain controllers".

And there are even more errors:
- The table states you need Server 2016 DCs for **certificate trust** model, but on this [page](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-guide#deployment-and-trust-models) the docs say, you do not need 2016 DCs: "The certificate trust model also supports enterprises which are not ready to deploy Windows Server 2016 Domain Controllers."

Or are my assumptions wrong?

**Comment by paolomatarazzo** [comment]
@retogobat you are correct WRT LTSC. We don't usually call those versions explicitly out in most of feature documentation, as they are meant to be used in highly specialized scenarios (e.g. kiosks, digital signs). So yes, we could update the table to exclude LTSC. Reality is, I don't see LTSC used commonly with WHFB outside of special scenarios as they don't get serviced. Please correct me if you think I'm wrong.

The 2nd page you point out needs to be refreshed. We'll update it with "have an adequate number of domain controllers" to make it more accurate. When the page was originally created, 2012/2012R2 were still supported.

3rd page, same as above.

Thanks again for pointing out the inconsistencies, we'll get to them.
