### ISSUE TITLE
Tweaker

### ISSUE THREAD

**Issue by govanyazer22** [MicrosoftDocs/windows-itpro-docs#11708]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47692487-0a0b-3b1b-6d34-790046c7cbc3
* Version Independent ID: 0f66cafe-2bff-4323-b3fc-01014b904b3a
* Content: [Windows Update log files - Windows Deployment](https://learn.microsoft.com/en-US/windows/deployment/update/windows-update-logs#generating-windowsupdatelog)
* Content Source: [windows/deployment/update/windows-update-logs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-logs.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
Closing issue as there is no actionable feedback for doc
