### ISSUE TITLE
Duplicated Certificate Template Names

### ISSUE THREAD

**Issue by seantsang-crypto** [MicrosoftDocs/windows-itpro-docs#11703]
I think there are some typos here. We use "WHFB Enrollment Agent" for 2 templates?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0e839ae-7beb-07fe-f0ea-560079f1f858
* Version Independent ID: af8e8903-fd5c-7210-768d-e0b5de67fe88
* Content: [Configure and validate the Public Key Infrastructure in an on-premises certificate trust model - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-pki)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-pki.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @seantsang-crypto and thank you for the feedback! Are you referring to the template name: *WHFB Enrollment Agent*?
In that case, you either create a template for a standard service account **or** a GMSA, not both, depending on your environment's setup. If you decide to configure both, then you can choose a different name.
