### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by dh-orko** [MicrosoftDocs/windows-itpro-docs#11712]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 192bc7af-26af-6a5e-ac99-ad133b1a4081
* Version Independent ID: 3d44ce52-c5c3-d506-925c-03aecee43201
* Content: [Deny access to this computer from the network - Windows Security](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/deny-access-to-this-computer-from-the-network?source=recommendations)
* Content Source: [windows/security/threat-protection/security-policy-settings/deny-access-to-this-computer-from-the-network.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/deny-access-to-this-computer-from-the-network.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Hi @dh-orko I'm not sure what's intended with this feedback, so I'm closing the issue. If you can share more details, please reopen
