### ISSUE TITLE
Why Microsoft?

### ISSUE THREAD

**Issue by Md-Kais** [MicrosoftDocs/windows-itpro-docs#11718]
![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/62563474/88394dad-e14b-4efa-8cfb-e12bb3c191bf)
### Questions:
Why windows 10 gets update where there are no visible updates?
We can't upgrade to windows 11 because I have AMD 2nd generation CPU?
what's the point of doing this, Microsoft?

### Impressions:
Just one thing update, IN 21h2 it's 21H2, now 22H2.
![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/62563474/c52a9f23-1c77-4be2-8dc5-f8066a4d958d)

### Appreciation:
NICE WORK, MICROSOFT.
TOTALLY WORTH IT.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26b9d6c3-b5bc-129c-e985-ca03b43b3235
* Version Independent ID: 26b9d6c3-b5bc-129c-e985-ca03b43b3235
* Content: [What's new in Windows 10, version 22H2 for IT pros - What's new in Windows](https://learn.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-22h2)
* Content Source: [windows/whats-new/whats-new-windows-10-version-22H2.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/whats-new-windows-10-version-22H2.md)
* Product: **windows-client**
* Technology: **itpro-fundamentals**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
The [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/), which outlines the expectations for community interactions in and around learn.microsoft.com, is designed to help "provide a welcoming and inspiring community for all." The content of this issue appears to be out of sync with the code of conduct, so we have closed it.

For product feedback, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).
