### ISSUE TITLE
Problem Driver Blocklist

### ISSUE THREAD

**Issue by M3ManuelGold** [MicrosoftDocs/windows-itpro-docs#11724]
Hello I am the owner of DIGITAL SERVICES OF MANUEL MUSARELLA, I have been partnering with you since 2020, I recently had a problem while signing my software.

I noticed that my driver is considered in blocklist https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/design/microsoft-recommended-driver-block-rules#vulnerable-driver-blocklist-xml "DIGITAL SERVICES OF MANUEL MUSARELLA"

I wanted to request if this can be resolved, as my software is widely used in the gaming world, and we care a lot about protecting our software.

PRODUCT ID: https://partner.microsoft.com/dashboard/hardware/driver/14307948452364312

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a58a715-458d-f016-f8d8-09ef8d4fbfb1
* Version Independent ID: 1a58a715-458d-f016-f8d8-09ef8d4fbfb1
* Content: [Microsoft recommended driver block rules - Windows Security](https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/design/microsoft-recommended-driver-block-rules#more-information)
* Content Source: [windows/security/application-security/application-control/windows-defender-application-control/design/microsoft-recommended-driver-block-rules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/application-security/application-control/windows-defender-application-control/design/microsoft-recommended-driver-block-rules.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @jsuther1974
* Microsoft Alias: **jsuther**

**Comment by aczechowski** [comment]
Hi @M3ManuelGold, you'll need to reach out to the Partner Center for support on this.

**Comment by goseecal99** [comment]
Hi Manuel,

This driver was escalated to the Microsoft Vulnerable Driver Team from a reputable third party anti-cheat contact. 

Upon investigation it was found:

•	This driver is being used to mimic an anti-cheat driver, but it is actually a cheat driver.
•	The file size of the impersonating driver is also quite different to the legitimate driver.
•	This driver is obfuscated. The legitimate anti-cheat driver is not

Due to the number of violations of Microsoft Terms and Conditions, the decision was made to block this driver.

Microsoft Vulnerable Driver Team  
Enterprise & Security - Platform Integrity Team

**Comment by M3ManuelGold** [comment]
Hello, I can reassure you that the driver being sent is not used to do such
things, but we had got reported some issues with it being used
illegitimately and we made sure to push a new version asap to solve the
vulnerabilities due to IOCTL requests not being carefully looked at, as you
can we have even tried uploading a new driver which is a rework of the old
one with the vulnerabilities fixed, i'm wondering if it's possible to pull
the digital signature from old driver files so we can push an update giving
the new driver out

Il giorno mer 27 set 2023 alle 21:09 goseecal99 ***@***.***>
ha scritto:
