### ISSUE TITLE
LOCALAPPDATA user context variable

### ISSUE THREAD

**Issue by ianmcl** [MicrosoftDocs/windows-itpro-docs#11725]
Missing under user context variables:

LOCALAPPDATA	Same as CSIDL_LOCAL_APPDATA.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72d479c1-cedc-05fc-2d73-45342b955037
* Version Independent ID: 8e91c2df-8405-3ec0-210e-1b97e86073cf
* Content: [Recognized environment variables - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/usmt/usmt-recognized-environment-variables)
* Content Source: [windows/deployment/usmt/usmt-recognized-environment-variables.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/usmt/usmt-recognized-environment-variables.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @ianmcl. Can you please be more specific as to what the problem is and what you would like to see changed/updated?

**Comment by frankroj** [comment]
Never heard back from submitter. Will reopen if I hear back from them.
