### ISSUE TITLE
Can't type on sign in page textboxes Take a Test app

### ISSUE THREAD

**Issue by Bearlyawakebear** [MicrosoftDocs/windows-itpro-docs#11729]
Hello,

After the latest update of September the Take a Test app is "broken"

Here is our workflow:

1. Get in Take a Test profile
2. Enter an exam url with keyboard (we do not use predefined profiles). The url is typically to an MS Forms Quiz
3. After typing and opening the page, the site prompts for login. Here comes the problem, the keyboard "seems" unresponsive- nothing typed in. We tested with build in laptop's keyboard, touch screen keyboard and an external USB one and none where able to enter text in the boxes.
4. The keyboard is in fact working - we can exit the session, or type in sign in boxes when we open other sites.
5. Our affected managed machines are running Windows 11 Education 64bit 22621.2283 build. 
6. We replicated the problem on a updated laptop with Windows 11 Pro which is not managed in an organization and is from a different OEM!
7. It seems after uninstalling some of the updates to get to version 22621.2134 the problem was solved! Also we found out that the touch keyboard is not present on the older build for us.

Original post https://answers.microsoft.com/en-us/windows/forum/windows_11-wintop_update/take-a-test-app-is-broken/a9a08bf7-5157-43b6-9a1f-2108c463f7c5 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c697a103-2704-d37e-759f-16b94f8ddcee
* Version Independent ID: 233054de-02ff-fe97-8af3-b917bf812fd5
* Content: [Take a Test app technical reference - Windows Education](https://learn.microsoft.com/en-us/education/windows/take-a-test-app-technical)
* Content Source: [education/windows/take-a-test-app-technical.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/education/windows/take-a-test-app-technical.md)
* Product: **windows-client**
* Technology: **itpro-edu**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @Bearlyawakebear and thank you for the feedback. The issue you're reporting is related to a bug in the Edge WebView2 runtime and the Edge team has identified a fix and will start rolling out a new stable runtime version on 9/28. You can track the bug here:

[[117 regression] Some UWP apps not getting keyboard input · Issue #3805 · MicrosoftEdge/WebView2Feedback (github.com)](https://github.com/MicrosoftEdge/WebView2Feedback/issues/3805)
