### ISSUE TITLE
Configure storage of Bitlocker recovery information to AD DS?????

### ISSUE THREAD

**Issue by RefleCs** [MicrosoftDocs/windows-itpro-docs#11720]
Since the Bitlocker profile change in Intune under Endpoint Security, I've been wondering.... why the .... is there absolutely nothing written on writing Bitlocker recovery key information to Azure AD????

Please update the article to include information If the settings that are sugesting recovery key information will be saved to AD DS are also the settings that need to be used for AzureAD Joined devices to write the keys to Azure AD.

The information in the Bitlocker CSP is outdated in my opinion.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a05802f-9d0f-9aeb-3c8e-8b92f1284202
* Version Independent ID: 1fd9efc2-8946-75e4-27f3-95ac43a9d987
* Content: [BitLocker CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp?WT.mc_id=Portal-fx)
* Content Source: [windows/client-management/mdm/bitlocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/bitlocker-csp.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by paolomatarazzo** [comment]
Thank you for the feedback, @RefleCs. As @aczechowski mentioned I'm working on refreshing the whole BDE documentation and I'll take your feedback. Closing the issue at the moment.
