### ISSUE TITLE
Questions regarding Kiosk set up

### ISSUE THREAD

**Issue by leslyvitier** [MicrosoftDocs/windows-itpro-docs#11736]
We are currently in the middle of implementing Take A Test in Kiosk mode using the Provisioning Package provided in the Microsoft article. 

1) Is there a comprehensive list we can refer to of all the system settings/policies this Provisioning Package changes when enabled? We are concerned it could interfere with existing settings/policies we already have.
For example, we noticed that it affects access to the C drive for all users that use the computer. 

2) When using the Powershell option, does it expect us to apply the necessary Group Policy changes before running the script or will the script adjust the necessary Group Policies?

3) Is it possible to set up a virtual machine specifically for this so that the changes applied as mentioned in my first question don't affect the physical machine that will running the hypothetical virtual machine? Ideally, we need the same Take-A-Test machine to be used for other purposes without the restrictions the provisioning package may apply. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3af13500-9626-be44-681b-0445c77191b6
* Version Independent ID: 3af13500-9626-be44-681b-0445c77191b6
* Content: [Configure Take a Test in kiosk mode - Windows Education](https://learn.microsoft.com/en-us/education/windows/edu-take-a-test-kiosk-mode?tabs=intune)
* Content Source: [education/windows/edu-take-a-test-kiosk-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/education/windows/edu-take-a-test-kiosk-mode.md)
* Product: **windows-client**
* Technology: **itpro-edu**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @leslyvitier , here are some feedbakc:

#1: please review https://learn.microsoft.com/windows/configuration/shared-pc-technical for a list of local GP settings that the options described in the article may configure
#2: PowerShell is an alternative tool. No need to configure other GP settings. You can use this option for testing the solution
#3: absolutely, I use VMs all the time! Take a snapshot before applying the ppkg or running the PS script and test it out. When done, just revert

Hope this helps!
Paolo
