### ISSUE TITLE
How to assign rings to business units

### ISSUE THREAD

**Issue by GitVali** [MicrosoftDocs/windows-itpro-docs#11733]
Hello,

In the documentation, we can see examples of groups that are named after business units and/or departments assigned to Autopatch rings.

How do you create & set up those groups knowing that we cannot assign groups of users to Autopatch rings and that we cannot create dynamic device groups based on the Job title/department of the owner of the devices?

Is there any workflow that I am missing from Intune or AAD?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1180ec6a-ea0e-af87-0e55-2f7f10736ea6
* Version Independent ID: 1180ec6a-ea0e-af87-0e55-2f7f10736ea6
* Content: [Windows Autopatch groups overview - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/windows-autopatch/deploy/windows-autopatch-groups-overview#common-ways-to-use-autopatch-groups)
* Content Source: [windows/deployment/windows-autopatch/deploy/windows-autopatch-groups-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopatch/deploy/windows-autopatch-groups-overview.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @tiaraquan
* Microsoft Alias: **tiaraquan**

**Comment by tiaraquan** [comment]
Hi there, 

You need to 9create the AAD groups yourself0[https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/how-to-manage-groups#create-a-basic-group-and-add-members] and then you use them to assign to deployment rings. How you create the membership of the group is up to you. However, they have to be device based groups.

**Comment by GitVali** [comment]
Hi, I understand that I have to create the AAD groups myself, however, how can we create a dynamic group that would contain the device per business unit as suggested in the example on the documentation page?

On the page we can see for instance:

Ring0 = IT, Ring1 = HR etc...

How do you accomplish this result? Do you manually add all devices from IT manually to an AAD group? Or is there a dynamic rule that can be used for this purpose? I have tried but could not find out

**Comment by tiaraquan** [comment]
You [populate your Azure Active Directory groups](https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/how-to-manage-groups#create-a-basic-group-and-add-members) however you wish. For example if there is a dynamic query that calls Azure object attributes for your devices to populate the group, then you can do that.  Unfortunately, we can't advise what they might be because each customer need/environment is different.
