### ISSUE TITLE
Best Practice recommendations for settings

### ISSUE THREAD

**Issue by jbrianmoss** [MicrosoftDocs/windows-itpro-docs#11739]
The default values are shown, but are there are best practice security recommendations? I didn't see any of these settings with values as part of the  Windows 10 or 11 Security Baselines.

Thanks,

Brian
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 789566d4-463a-4c64-bf89-fb963ac29f80
* Version Independent ID: 02946732-bb29-d8e6-cedd-7f5e508f8798
* Content: [Manage Windows Hello in your organization - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-manage-in-organization)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-manage-in-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-manage-in-organization.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
hello @jbrianmoss, there are no specific best practices when it comes to WHfB policies. You should configure the policy settings to adhere to your organization's security.

**Comment by jbrianmoss** [comment]
@paolomatarazzo are there no recommendations as far as PIN length, complexity, history lockout etc.? If there isn't, would you support me opening an issue to develop one? I quick look didn't point me to any recommendations in other baselines such as CIS or STIG, but there might be I didn't do a thorough search. If there is nothing, then potentially the settings for  iOS/Android device PINS could be used as a starting point.

**Comment by paolomatarazzo** [comment]
Length/complexity is something that your security department should dictate. Ultimately, there is anti-hammering logic that makes complexity kind of moot. The idea to implement WHfB is to increase security while increase complexity. I (personally) don't believe in creating complex PINs and trying to mimic password complexity/history/length. I also see PIN as a fallback mechanism. On physical devices, most likely users have access to bio like fingerprint reader or facial recognition. In that case, users are less likely to use a PIN and  be subject to *PIN surfing*. if you already have policies in place for iOS/Android, it could be a good idea to align to those.
