### ISSUE TITLE
Intune settings not defined in this page for excluding credential providers

### ISSUE THREAD

**Issue by sudeepg100** [MicrosoftDocs/windows-itpro-docs#11738]
In the section Excluding the password credential provider, there is no mention of how Intune managed devices can apply this setting. This is an ADMX backed policy and there is an Intune setting, this needs to be included in this article to make it complete

![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/24678671/b3aa5438-19fd-48f2-b0b7-96b20c58d675)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca080bd-ed37-60a8-ec22-b1929166ff0c
* Version Independent ID: d2742e0c-9d66-4b1f-8555-a1fb1546455b
* Content: [Password-less strategy - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/passwordless-strategy#the-process)
* Content Source: [windows/security/identity-protection/hello-for-business/passwordless-strategy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/passwordless-strategy.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
hello @sudeepg100 , we're gonna rewrite that article pretty soon, but thank you for the feedback!
