### ISSUE TITLE
Cortana policy update for 1803

### ISSUE THREAD

**Issue by anwara-ms** [MicrosoftDocs/windows-itpro-docs#1173]
Hi. Are you planning to update this to reflect cortana policy changes for 1803?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4568d58-3e3f-4984-464a-814ea5d14069
* Version Independent ID: 2ed023b5-e4e0-30ca-ca7d-c34eae9d3d2a
* Content: [Windows 10 editions for education customers](https://docs.microsoft.com/en-us/education/windows/windows-editions-for-education-customers#feedback)
* Content Source: [education/windows/windows-editions-for-education-customers.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/windows-editions-for-education-customers.md)
* Product: **w10**
* GitHub Login: @CelesteDG
* Microsoft Alias: **celested**

**Comment by andreabichsel** [comment]
@coreyp-at-msft can you look at this issue, or determine who the new owner is?

**Comment by e0i** [comment]
@mjcaparas Would you be able to provide clarifications as the recent author of the article? Thanks.

**Comment by mjcaparas** [comment]
Not sure sorry :(
