### ISSUE TITLE
Passkey backups?

### ISSUE THREAD

**Issue by kc8viq** [MicrosoftDocs/windows-itpro-docs#11731]
Great write up, thank you! But one thing was left unaddressed. Backups? How are passkeys backed up if the device is lost, stolen, or broken? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86356b2f-7238-d4dd-5872-57bb1e6f564a
* Version Independent ID: 86356b2f-7238-d4dd-5872-57bb1e6f564a
* Content: [Support for passkeys in Windows - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/passkeys/?tabs=windows)
* Content Source: [windows/security/identity-protection/passkeys/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/passkeys/index.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @kc8viq and thank you for the feedback. We are actively working on the ability to back up and restore as well as sync passkeys across your Microsoft devices. No ETA just yet
