### ISSUE TITLE
Configuration/DisableLocalAdminMerge Allowed Values Description wrong

### ISSUE THREAD

**Issue by BlakeMsft** [MicrosoftDocs/windows-itpro-docs#11744]
Configuration/DisableLocalAdminMerge Allowed values Description wrong

https://learn.microsoft.com/en-us/windows/client-management/mdm/defender-csp?WT.mc_id=Portal-fx#configurationdisablelocaladminmerge

States the Allowed value Description as **Yes** or **No**.

When you look at the policy in intune, your options are these:

Enable Local Admin Merge
Disable Local Admin Merge
Not configured

Pleease correct this.

Thank you,
Blake

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f65802b-f3e2-1c15-d972-b23e53ed7e72
* Version Independent ID: cc29ae16-e01e-aad1-3768-d6b8a0b60b1a
* Content: [Defender CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/defender-csp?WT.mc_id=Portal-fx#configurationdisablelocaladminmerge)
* Content Source: [windows/client-management/mdm/defender-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/defender-csp.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by Thuyaaung939** [comment]
***@***.***

**Comment by aczechowski** [comment]
Thanks @BlakeMsft for the feedback. The [CSP docs](https://learn.microsoft.com/windows/client-management/mdm/contribute-csp-reference) are mostly automated now, drawing content from the [DDF](https://learn.microsoft.com/windows/client-management/mdm/configuration-service-provider-ddf) and ADMX files directly out of the OS itself. The Intune settings catalog does something similar, drawing from the same DDF source. So we can check to see why there's this discrepancy, which I wouldn't expect. Alternatively, the policy description is in the editable region, so we could always just add a note there to further explain.

**Comment by vinaypamnani-msft** [comment]
Intune UI just has a toggle for this setting now in the Settings catalog, there's no "Not configured" value anymore and it's equivalent to "Yes/No". Closing this issue.
