### ISSUE TITLE
Out dated info and screenshots

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/windows-itpro-docs#11749]
I have already submitted a PR to remove references to Windows 10, specific VAMT versions and dead SQL Express links but this article still has outdated screenshots relating to the SQL Express installation.

This whole page should be reviewed to check it is still accurate for all the latest and supported OSs

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01910332-8f6f-c844-6594-d9da807492c5
* Version Independent ID: 13b107a6-b139-671d-d3bd-d53b2de74fdd
* Content: [Install VAMT - Windows Deployment](https://review.learn.microsoft.com/en-us/windows/deployment/volume-activation/install-vamt?branch=pr-en-us-8954)
* Content Source: [windows/deployment/volume-activation/install-vamt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/volume-activation/install-vamt.md)
* Product: **windows-client**
* Technology: **itpro-fundamentals**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by aczechowski** [comment]
Thanks @thommck for the feedback, I know @frankroj is working through a lot of content to refresh and this is on the list.

You said you submitted a PR...I don't see anything in [this repository](https://github.com/MicrosoftDocs/windows-itpro-docs/pulls?q=is%3Apr+is%3Aopen+thommck+) or the [associated private repo](https://github.com/MicrosoftDocs/windows-docs-pr/pulls?q=is%3Apr+is%3Aopen+thommck+). Can you share the link to the referenced PR that you submitted, then we can check to make sure your contribution is included.

**Comment by frankroj** [comment]
Found the PR:

https://github.com/MicrosoftDocs/windows-docs-pr/pull/8954/

**Comment by frankroj** [comment]
Several updates done through tagged PR. Additional changes will be done through freshness project.
