### ISSUE TITLE
Unable to assign permissions on Firewall folder

### ISSUE THREAD

**Issue by tbiles** [MicrosoftDocs/windows-itpro-docs#11758]
[Enter feedback here]
I have a Server 2022 instance that had no firewall logs despite them being turned on by GPO.  The GPO enables fireall logging just fine on older Windows versions.

I used this article to check for the folder and permissions which were both missing.  I ran all the scripts to create the folder and assign the acl, but even after a reboot, the ACL is not visible on the folder.  This is all that shows:
IdentityReference                                                            FileSystemRights AccessControlType IsInher
                                                                                                                   ited
-----------------                                                            ---------------- ----------------- -------
NT SERVICE\TrustedInstaller                                                       FullControl             Allow    True
NT SERVICE\TrustedInstaller                                                         268435456             Allow    True
NT AUTHORITY\SYSTEM                                                               FullControl             Allow    True
NT AUTHORITY\SYSTEM                                                                 268435456             Allow    True
BUILTIN\Administrators                                                            FullControl             Allow    True
BUILTIN\Administrators                                                              268435456             Allow    True
BUILTIN\Users                                                     ReadAndExecute, Synchronize             Allow    True
BUILTIN\Users                                                                     -1610612736             Allow    True
CREATOR OWNER                                                                       268435456             Allow    True
APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES            ReadAndExecute, Synchronize             Allow    True
APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES                            -1610612736             Allow    True
APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APPLICATION PACKAGES ReadAndExecute, Synchronize             Allow    True
APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APPLICATION PACKAGES                 -1610612736             Allow    True

The commands are not showing any errors but for what ever reason, it isn't assigning the ACL on the last step.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 03a6edc3-c8e0-801d-00d6-6005644de39e
* Version Independent ID: 03a6edc3-c8e0-801d-00d6-6005644de39e
* Content: [Configure the Windows Defender Firewall Log - Windows Security](https://learn.microsoft.com/en-us/windows/security/operating-system-security/network-security/windows-firewall/configure-the-windows-firewall-log)
* Content Source: [windows/security/operating-system-security/network-security/windows-firewall/configure-the-windows-firewall-log.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/operating-system-security/network-security/windows-firewall/configure-the-windows-firewall-log.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @ngangulyms
* Microsoft Alias: **nganguly**

**Comment by Littlemanbarnes** [comment]
I'm experiencing the same issue. I ran the script, and it finished with no errors. I go to check security settings to verify that mpssvc is added, and it's not. I've reviewed the folder's permissions and ensured Powershell was opened as administrator. I run this script for my Windows 2019 and 2022 servers. Windows 2016 accepts the GPO, as illustrated in the article. 

I can add mpssvc manually to the Firewall folder and set proper permissions. The log shows up shortly after. However, I have 100s of servers to apply this to and find it more efficient to have a script to be ran automatically. 

I look forward to see what the solution for this will be.

**Comment by paolomatarazzo** [comment]
Thank you for the feedback, @tbiles and @Littlemanbarnes . I'm in the process of refreshing some of the Windows Firewall documentation. I'll check this specific article and verify the behavior on Windows Server.

**Comment by paolomatarazzo** [comment]
I'll update the article with the following:

```powershell
$LogPath = Join-Path -path $env:windir -ChildPath "System32\LogFiles\Firewall"
$NewAcl = Get-Acl -Path $LogPath 

$identity = "NT SERVICE\mpssvc"
$fileSystemRights = "FullControl"
$inheritanceFlags = "ContainerInherit,ObjectInherit"
$propagationFlags = "None"
$type = "Allow"

$fileSystemAccessRuleArgumentList = $identity, $fileSystemRights, $inheritanceFlags, $propagationFlags, $type
$fileSystemAccessRule = New-Object -TypeName System.Security.AccessControl.FileSystemAccessRule -ArgumentList $fileSystemAccessRuleArgumentList

$NewAcl.SetAccessRule($fileSystemAccessRule)
Set-Acl -Path $LogPath -AclObject $NewAcl
```

Closing the issue as the article will be published by the end of next week.

**Comment by Littlemanbarnes** [comment]
It worked for me. Thank you for the support!
