### ISSUE TITLE
Improve Images and Supporting Captions

### ISSUE THREAD

**Issue by sambasile** [MicrosoftDocs/windows-itpro-docs#11752]
Could you please make an improvement to the images used in the page.  The detailed XML view doesn't match the capture from regedit making it more difficult to understand how the two are associated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: af311899-f53d-3716-d6ad-9e95f2fe38c8
* Version Independent ID: 1acb84ed-94c4-5128-ba2a-edd849f06256
* Content: [4957(F) Windows Firewall did not apply the following rule. - Windows Security](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4957)
* Content Source: [windows/security/threat-protection/auditing/event-4957.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4957.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Hi @sambasile thanks for the feedback. I understand that the graphics aren't ideal, but we're actually in process to retire this content to the [previous versions site](https://learn.microsoft.com/previous-versions/windows/). It's content that we want to persist on Microsoft Learn, but unfortunately don't have the resources to actively maintain and keep up to date. So I decided it would be better to just comment back and close this issue straight away to set expectations.
