### ISSUE TITLE
Provide full docs and a proper declarative scenario

### ISSUE THREAD

**Issue by apcsb** [MicrosoftDocs/windows-itpro-docs#11751]
1. Isn't copying a file imperative by its nature, thus kinda defeating the purpose of declarative management in the first place?
Could a registry sample be more fitting?

2. The example still only shows a part of the picture. OK, I have an MI provider built and somehow deployed to the device. What kind of OMA DM XML am I supposed to feed to it (or is it the one in https://learn.microsoft.com/en-us/windows/client-management/mdm/declaredconfiguration-csp ?) ?
Having a GitHub repo showing the entire process end-to-end (source code pre-codegen, full source code that actually implements the methods, baked compiled DLL/MOF, Intune App package, XML for Intune) would be extremely useful if we want proper adoption. 
I could help with that - I am interested in trying this tech out :)

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c1370cc-fc09-4930-4861-b898e52be92d
* Version Independent ID: 3c1370cc-fc09-4930-4861-b898e52be92d
* Content: [Declared configuration extensibility - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/declared-configuration-extensibility)
* Content Source: [windows/client-management/declared-configuration-extensibility.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/declared-configuration-extensibility.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Since Peter is tracking the effort separately, I'm going to close this issue. Thanks @apcsb for the feedback.
