### ISSUE TITLE
Security monitoring recommendation: PreAuthType 16 & TicketOptions

### ISSUE THREAD

**Issue by J3roen** [MicrosoftDocs/windows-itpro-docs#11765]
After doing some research (full write-up here: https://www.socstories.blog/detecting-adcs-attacks/ ) on ADCS attacks, I propose the following security monitoring recommendations:
- PreAuthType 16 (seen in ADCS ESC attacks) in environments where Windows Hello for Business is **not** enabled (according to https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3265#issuecomment-856543627 , Windows Hello for Business will use PreAuthType 16 as well. We did not observe any other activity triggering this PreAuthType)
- TicketOptions starting with 0x4080 (instead of 0x4081, 0x6081), we did not observe this value in legitimate traffic and it is hardcoded in multiple offensive tools, such as Rubeus, Impacket, Certipy, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94cebf1d-b16d-4ddc-b532-be829b858938
* Version Independent ID: 3707f457-98d5-e5b3-c749-99afe0d6d495
* Content: [4768(S, F) A Kerberos authentication ticket (TGT) was requested. - Windows Security](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4768#feedback)
* Content Source: [windows/security/threat-protection/auditing/event-4768.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4768.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
Thanks @J3roen for the feedback, however we're in progress to retire this "auditing" section to [Windows previous versions documentation](https://learn.microsoft.com/previous-versions/windows/). So we don't plan on making any substantive changes.
