### ISSUE TITLE
getting error while launching the exe file setupdiag.exe

### ISSUE THREAD

**Issue by zoerg** [MicrosoftDocs/windows-itpro-docs#1176]
Hi, i have a failing upgrade from windows 1709 to 1803 and i would like to use the setupdiag.exe but after downloading the app and trying to launch it, it always result in an error : "This app could not be started" 
When i click on "yes" i get the following page : https://support.microsoft.com/en-us/help/2715633/shim-errors-for-the-net-framework-version-and-platform-support

Altough i'm on version 1709 of windows and all .net framework are installed and activated (4.7 2.0 3.5)

if there's anything else i'm  missing to setup the app  ?
Thanks in advance

**Comment by andreabichsel** [comment]
You may be able to find answers on our Support site or contact Support for assistance: https://support.microsoft.com/en-us
