### ISSUE TITLE
Varying behaviors on different stations with the same setup

### ISSUE THREAD

**Issue by leslyvitier** [MicrosoftDocs/windows-itpro-docs#11764]
Hello, 

We have set up a desktop shortcut with our exam link following this template: 

ms-edu-secureassessment:<URL>#enforceLockdown

We also confirmed to follow the local group policy requirements listed here: 

https://learn.microsoft.com/en-us/education/windows/take-a-test-app-technical

Our issue is that we are having three different results

1) On a set of computers the link provided works perfectly. Once the shortcut is clicked, the Take A Test application opens and runs the exam as expected. 

2) On another set of computers, when the shortcut is clicked, the application logs the user out and once the user logs back in, the test runs as expected. 

3) On the last set of computers, when the shortcut is clicked we get the following error message: "Unable to open this internet shortcut. The protocol "ms-edu-secureassessment" does not have a registered program."
We tried manually entering the link into the browser and it just takes us to a google search of related topics. 

*Note: We applied the same shortcut with the same link to all mentioned groups of computers 

How can we make it so that all groups behave as the first group mentioned? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3095728-2d28-73d1-7db7-aaabc8be15ce
* Version Independent ID: e3095728-2d28-73d1-7db7-aaabc8be15ce
* Content: [Take tests and assessments in Windows - Windows Education](https://learn.microsoft.com/en-us/education/windows/take-tests-in-windows)
* Content Source: [education/windows/take-tests-in-windows.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/education/windows/take-tests-in-windows.md)
* Product: **windows-client**
* Technology: **itpro-edu**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @leslyvitier are the devices all at the same OS and patch level?

**Comment by leslyvitier** [comment]
> at the same OS and patch level?

Yes. they are all on Windows 11 10.0.22621.2070

**Comment by paolomatarazzo** [comment]
@leslyvitier I suggest opening a support case to take a closer look.
