### ISSUE TITLE
Nothing here works to fix a corrupt UEFI DBX file.

### ISSUE THREAD

**Issue by peterblaise** [MicrosoftDocs/windows-itpro-docs#11769]
Nothing here works to fix a corrupt UEFI DBX file.

Can someone kindly just write a program or boot ISO ( hahahaha - it can't boot, that's the prob;lem ) that fixes a corrupt UEFI DBX file?

Please?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7734ca5-0770-5bbd-7da5-dda4c1cf5ae0
* Version Independent ID: cb98ef23-d0c6-e62e-b72b-9b5f5d724e8e
* Content: [Update Windows installation media with Dynamic Update - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/media-dynamic-update)
* Content Source: [windows/deployment/update/media-dynamic-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/media-dynamic-update.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @peterblaise for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
