### ISSUE TITLE
Group policy path is incorrect for disabling CoPilot

### ISSUE THREAD

**Issue by buro9** [MicrosoftDocs/windows-itpro-docs#11763]
Currently is:

```User Configuration > Administrative Templates > Windows Copilot > Turn off Windows Copilot```

Should be:

```User Configuration > Administrative Templates > Windows Components > Windows Copilot > Turn off Windows Copilot```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c45da028-0e12-6c6e-e48e-48aab82fe911
* Version Independent ID: c45da028-0e12-6c6e-e48e-48aab82fe911
* Content: [Manage Copilot in Windows - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/manage-windows-copilot)
* Content Source: [windows/client-management/manage-windows-copilot.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/manage-windows-copilot.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by mestew** [comment]
@buro9 
D'oh! Fixing this now. Should be updated in a couple of hours. Thanks for reporting this!
