### ISSUE TITLE
LTSB --> LTSC upgrades

### ISSUE THREAD

**Issue by crp0908** [MicrosoftDocs/windows-itpro-docs#11766]
What's the upgrade path for older versions of LTSB to newer versions of LTSC?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08436cb0-d0b6-0961-9e57-291b24d73644
* Version Independent ID: 36264f52-d3ac-4e50-f8e8-b09d6b210490
* Content: [Windows 10 upgrade paths (Windows 10) - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/upgrade/windows-10-upgrade-paths)
* Content Source: [windows/deployment/upgrade/windows-10-upgrade-paths.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/windows-10-upgrade-paths.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Hello @crp0908. Please see the newer version of this article as noted at the top of this article:

https://learn.microsoft.com/en-us/windows/deployment/upgrade/windows-upgrade-paths

To answer the question though, there is nothing special upgrading between versions of LTSB/LTSC. It follows the normal upgrade path. You can't however upgrade between versions of LTSB/LTSC and Windows General Availability Channel. I hope this answers your question.
