### ISSUE TITLE
Error code 0x801c044f is not listed

### ISSUE THREAD

**Issue by BillClarkEarthPoint** [MicrosoftDocs/windows-itpro-docs#11772]
In settings, when i click Sorry, this PIN isn't working for your organization's resources.  Tap or click here to fix it.

The next screens say that my password is incorrect. And when I click "reset it" it just fades out and does nothing forever.

When I close the window, I get the error code

![ScreenShot](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/11196392/cf7b4f94-2ea6-4511-bb3d-8f965c57bf69)

(admin edit: moving image out of metadata into body)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello Bill,
from the description (*The next screens say that my password is incorrect.*), it doesn't appear to be an issue related to the WHFB PIN, rather an authentication issue. Can you access online resources with single sign-on? e.g. open a browser windows and go to https://portal.office.com, are you automatically authenticated? Check also in the notification pane if there's an indication that you may need to sign in again.
