### ISSUE TITLE
Security Baselines update Required!

### ISSUE THREAD

**Issue by epayneisladmin** [MicrosoftDocs/windows-itpro-docs#11773]
The Center for Internet Security (CIS) released v2.0.0 04-14-2023 of CIS Microsoft Windows Server 2022 Benchmark. These need to be updated in you GPO packages and spreadsheets here: https://www.microsoft.com/en-us/download/details.aspx?id=55319
Please update!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a1c8c0cc-cb14-776d-4006-b0887bbd47e3
* Version Independent ID: a1c8c0cc-cb14-776d-4006-b0887bbd47e3
* Content: [Security baselines guide - Windows Security](https://learn.microsoft.com/en-us/windows/security/operating-system-security/device-management/windows-security-configuration-framework/windows-security-baselines)
* Content Source: [windows/security/operating-system-security/device-management/windows-security-configuration-framework/windows-security-baselines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/operating-system-security/device-management/windows-security-configuration-framework/windows-security-baselines.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
thanks @epayneisladmin for sharing this, but our team doesn't own that content on the download center. I'll forward this along to who I think is involved with it.
