### ISSUE TITLE
More information ...

### ISSUE THREAD

**Issue by AreYouKiddingM3** [MicrosoftDocs/windows-itpro-docs#11778]
It would be nice if this document defined exactly what an Entra Joined Device is ... Azure AD joined + AD Joined = Entra Joined. 

Also, more contextual information around successfully configuring Intune and the Windows 11 device itself would be helpful, for instance, running dsregcmd /status for helpful information for success around enabling Web Sign-In.  Granted, this is a new feature, I have yet to successful set this up based on the limited documentation I see here.   I am opening a SEV B ticket with MS to further address as this documentation is anemic and doesn't go into great detail. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9be6d74c-9de9-6180-fded-2ddca8747141
* Version Independent ID: 9be6d74c-9de9-6180-fded-2ddca8747141
* Content: [Web sign-in for Windows - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/web-sign-in/?tabs=intune)
* Content Source: [windows/security/identity-protection/web-sign-in/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/web-sign-in/index.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @AreYouKiddingM3 and thank you for the feedback.

## Authentication feedback

Repeating the basic concepts of authentication for each feature would make every article long and complex to follow. Also, we recently rebranded Azure AD to Microsoft Entra ID, so all the terminology like *AADJ*, *HAADJ*, etc has been renamed. For reference, see   https://learn.microsoft.com/entra/fundamentals/new-name.

You are asking to document device registration and how to troubleshoot it (`dsregcmd.exe`), which is not the goal of this article.
To understand the basic concept of device registration, see https://learn.microsoft.com/entra/identity/devices/concept-directory-join

Web sign-in has pre-requisites, which include a specific device state (Microsoft Entra join). I'll add a link to the documentation, to make it clearer.

## Intune feedback

About the configuration with Intune, the documentation explains **what** to configure, not the *how*. Repeating how to use Intune for each feature, makes the article long and complex to follow (same as above). The article links to the Intune documentation, which explains the how. Specifically, how to create a settings catalog policy or a custom policy.

When you say *this documentation is anemic and doesn't go into great detail*, are you suggesting that I call out step-by-step what to click in Intune? Taking that approach means that if the Intune UI is updated, we need to update every step-by-step article. Linking a document that explains the *how* - step-by-step - once, is a more efficient way to create documentation.


Hope this helps.
