### ISSUE TITLE
Web Sign In information is not accurate

### ISSUE THREAD

**Issue by AreYouKiddingM3** [MicrosoftDocs/windows-itpro-docs#11777]
As of Windows 11 v22H2 >> https://learn.microsoft.com/en-us/windows/security/identity-protection/web-sign-in/?tabs=intune

Please revise the documentation for more accurate information. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 845fc177-23cf-0b2c-4b2b-5ac3966763a6
* Version Independent ID: ef4248eb-9b9f-24ec-631e-d65ae2ae3ecf
* Content: [Authentication Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-authentication)
* Content Source: [windows/client-management/mdm/policy-csp-authentication.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-authentication.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by paolomatarazzo** [comment]
@AreYouKiddingM3 can you please be more specific? what is not accurate in the article?
