### ISSUE TITLE
Document Feedback RE Licensing Requirements

### ISSUE THREAD

**Issue by mulhalljrK** [MicrosoftDocs/windows-itpro-docs#11771]
Windows 11 Home Edition also comes with Windows Defender Smart Screen ('reputation-based protection setting(s))

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 565ec50c-2314-41e1-6f8c-89fbc03cfffd
* Version Independent ID: 565ec50c-2314-41e1-6f8c-89fbc03cfffd
* Content: [Microsoft Defender SmartScreen overview - Windows Security](https://learn.microsoft.com/en-us/windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/)
* Content Source: [windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/index.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @mulhalljrK for the feedback, but this content is primarily intended for IT Pros that manage Windows client in a commercial environment, which generally doesn't include Home edition. The licensing requirements sections like in this article are automated, the same as what's in the [Commercial licensing article](https://learn.microsoft.com/windows/whats-new/windows-licensing), and at this time we're not including Home.
