### ISSUE TITLE
Option to allow Microsoft 365 Apps Updates does not mention channel switch in blurb.

### ISSUE THREAD

**Issue by matziq** [MicrosoftDocs/windows-itpro-docs#11781]
The Autopatch option to "Allow" "Microsoft 365 Apps Updates" does not mention in the blurb in Intune that it switches the channel to Monthly Enterprise Channel. This is a big change that customers need to know before they flip that switch.

![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/31866685/bd64420f-6d53-44e2-9c4c-2ace25c524bf)

Can a short blurb mentioning that change be added to the Intune description? i.e.:
When set to Allow, Windows Autopatch will move all Autopatch devices to the Monthly Enterprise Channel and begin managing updates automatically. To manage them yourself, select the switch to turn it off. You must be an Intune Administrator to make changes to the setting. [Learn more about Microsoft 365 apps updates.](https://learn.microsoft.com/windows/deployment/windows-autopatch/operate/windows-autopatch-microsoft-365-apps-enterprise)

Thanks!
John Rea

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec8a5572-1135-3c0b-06d1-b8e1f258c17a
* Version Independent ID: ec8a5572-1135-3c0b-06d1-b8e1f258c17a
* Content: [Microsoft 365 Apps for enterprise - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/windows-autopatch/operate/windows-autopatch-microsoft-365-apps-enterprise)
* Content Source: [windows/deployment/windows-autopatch/operate/windows-autopatch-microsoft-365-apps-enterprise.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopatch/operate/windows-autopatch-microsoft-365-apps-enterprise.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @tiaraquan
* Microsoft Alias: **tiaraquan**

**Comment by tiaraquan** [comment]
Thank you for your feedback. We've updated the documentation.
