### ISSUE TITLE
New PassKeys UI is annoying (mouse or keyboard needed)

### ISSUE THREAD

**Issue by jlpetz** [MicrosoftDocs/windows-itpro-docs#11784]
This new UI to select the security option is annoying. My organisation makes heavy use of u2f keys, and now I have to select that I want to use u2f key (not passKey) before getting prompted to physically press the key. Previously it just defaulted to the u2f key and prompted to physically press it straight away, because PassKeys didn't exist.

Could we either 
1. Provide information on how to disable Passkeys until the UI can be improved, this will hopefully restore the old behaviour of just asking for the security key to be physically pressed straight away.
OR
2. Enhance the UI to remember to use the u2f key for specific sites/etc..... Or have an order, to try one option first then fallback. ie. if you have a valid passkey, try it, then if it fails fallback to u2f press automatically without a UI to select which method.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86356b2f-7238-d4dd-5872-57bb1e6f564a
* Version Independent ID: 86356b2f-7238-d4dd-5872-57bb1e6f564a
* Content: [Support for passkeys in Windows - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/passkeys/?tabs=windows)
* Content Source: [windows/security/identity-protection/passkeys/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/passkeys/index.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
@jlpetz thank you for the feedback, which I'll pass to the PG. As far as I know, there are no options to disable the new passkeys experience, but I'll let you know and document it otherwise.
Option #2 seems like a good feature request, let's see where it goes 👍🏼

**Comment by jlpetz** [comment]
paolomatarazzo@, thanks for the quick response. Apologies that I could not raise this as a FR on Feedback Hub. My organisation has disabled/locked-down data logging to Microsoft, which seems to be required (basic logging is the minimum) to be able to use Feedback Hub.

Attaching screenshot of the new pop-up, for clarity.

![u2f_OR_passKey](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/16551502/06c1316d-e8df-4712-991f-2f3b8e828bc1)

**Comment by paolomatarazzo** [comment]
yep, I'm familiar with the behavior and I discussed internally already with PG. We're looking into it and hopefully we'll be able to improve the experience for your scenario soon. I'll keep the GitHub issue closed, since it's not a documentation problem. Thank you again for the feedback!
