### ISSUE TITLE
Which events to monitor

### ISSUE THREAD

**Issue by opoplawski** [MicrosoftDocs/windows-itpro-docs#11792]
The page should indicate which event codes to look at and why.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c857358c-2f04-950d-649e-4665eb63ca76
* Version Independent ID: f3f7bd4b-330a-081a-b00d-f9af4ee09184
* Content: [View the security event log - Windows Security](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/view-the-security-event-log)
* Content Source: [windows/security/threat-protection/auditing/view-the-security-event-log.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/view-the-security-event-log.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @opoplawski for the feedback, however we're in progress to retire this "auditing" section to [Windows previous versions documentation](https://learn.microsoft.com/previous-versions/windows/). So we don't plan on making any substantive changes.
