### ISSUE TITLE
Group mapping

### ISSUE THREAD

**Issue by jchapman3vG** [MicrosoftDocs/windows-itpro-docs#11796]
Hi,

The Microsoft 365 pre-created SAML App in Google Workspace has an option to map user group memberships. Google's own documentation even mentions this. However, they don't say what Attribute name on the Microsoft side to map this to:

https://support.google.com/a/answer/6363817?sjid=18372769738086397882-NA#zippy=%2Cstep-set-up-google-as-a-saml-identity-provider-idp
> 10. (Optional) To enter group names that are relevant for this app:
> a. For **Group membership (optional)**, click **Search for a group**, enter one or more letters of the group name, and select the group name.
> b. Add additional groups as needed (maximum of 75 groups).
> c. For **App attribute**, enter the service provider’s corresponding groups attribute name.

Could this Microsoft article have a note about the Google Group to Microsoft Group Mappings? What is the App Attribute from the Microsoft side I should map to so that group memberships are also carried over from Google Workspace to Microsoft 365?

Thanks,
Joe

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aab824fb-b795-518a-8d52-7490975ab5ac
* Version Independent ID: aab824fb-b795-518a-8d52-7490975ab5ac
* Content: [Configure federation between Google Workspace and Microsoft Entra ID - Windows Education](https://learn.microsoft.com/en-us/education/windows/configure-aad-google-trust)
* Content Source: [education/windows/configure-aad-google-trust.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/education/windows/configure-aad-google-trust.md)
* Product: **windows-client**
* Technology: **itpro-edu**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @jchapman3vG and thank you for the feedback. I think that what you're asking goes beyond the scope of this article. Can you provide a practical example that requires to add this mapping? I'm not sure if and how Microsoft Entra ID consumes the group mapping claim from the IdP.

**Comment by jchapman3vG** [comment]
Thanks for the quick reply @paolomatarazzo 

So my understanding is that in the Google Workspace Office 365 SAML app this Group Membership option can pass the user's group memberships on from Google as the IdP to Microsoft as the Service Provider. I can select which Google Groups I want to expose to the SAML application and that will map those group memberships to the service provider via the SAML protocol. But I need to know what the Service Provider's corresponding group membership attribute is called. I've not been able to find this information anywhere and I was thinking maybe it should be on this document since these are Microsoft's instructions.

It is an optional feature, I've got everything else working already, including the autoprovisioning part but it would be great if group memberships were also passed from Google to Microsoft so that I don't have to manually manage group memberships on both platforms. I want to be able to add/remove members to groups in Google Workspace and have that mapped to and match in Microsoft Office 365.

Maybe this is a question for Entra ID support then?

![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/149710297/f626dea7-7f69-48bf-90d6-745e248084ad)

**Comment by paolomatarazzo** [comment]
I don't think you need to pass the group claim then, you need to have a solution that syncs group memberships between GW and Entra ID. You must use Entra ID groups to assign access to resources, I don't think that the claim will help much. As far as I know, Microsoft doesn't a sync solution that suits your needs, but you can open a Support request to confirm.

Hope this helps!

**Comment by jchapman3vG** [comment]
Thanks for the help anyway. I did find a suggestion on reddit to schedule a script with GAM and Powershell commands to do the sync but I was hoping there was a more built-in and simpler solution. Guess I'll have to figure out how to write this script myself...

https://www.reddit.com/r/gsuite/comments/171cuti/google_groups_not_sync_with_azure_ad_google/k3tr9u2/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
