### ISSUE TITLE
Confusing recomandation for the max password length set to 14. 

### ISSUE THREAD

**Issue by razvan-b** [MicrosoftDocs/windows-itpro-docs#11807]
Hello,

I am confused by the statement in the article : A minimum password length greater than 14 isn't supported at this time. 
According to this article https://support.microsoft.com/en-us/topic/minimum-password-length-auditing-and-enforcement-on-certain-versions-of-windows-5ef7fecf-3325-f56b-cc10-4fd565aacc59 passwords can be longer than 14 characters.

Can you please provide more info in what context a password longer than 14 characters is not supported ?

Kind regards,
Razvan

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9bcaf30b-7304-6874-ba5d-791cc4d435d2
* Version Independent ID: 961def9f-094a-3d1e-82a4-bb152c2e5a1e
* Content: [Minimum password length - Windows Security](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/minimum-password-length)
* Content Source: [windows/security/threat-protection/security-policy-settings/minimum-password-length.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/minimum-password-length.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
The Minimum Password Length policy defines the minimum length that the password should have, so a value of 14 means the password must be over 14 characters. A password can be over 14 characters, but the value of the "Minimum Password Length" policy cannot be over 14. Hope that helps.

**Comment by razvan-b** [comment]
Thanks for your reply. Reading again my message I realize that I was not very clear. If I want to set a minimum password length higher than 14 characters this article mentions that it is not supported however the article https://support.microsoft.com/en-us/topic/minimum-password-length-auditing-and-enforcement-on-certain-versions-of-windows-5ef7fecf-3325-f56b-cc10-4fd565aacc59 states that the update can enforce passwords which have a minimum password length higher than 14 characters. Thank you for your help.
