### ISSUE TITLE
windows-10-subscription-activation | Conditional Access Exclusion instructions are incorrect based on tenant's age

### ISSUE THREAD

**Issue by v-aweber** [MicrosoftDocs/windows-itpro-docs#11801]
The app with ID 45a330b1-b1ec-4cc1-9161-9f03992aa49f was either renamed from Windows Store Business Application to Universal Store Service APIs or from Universal Store Service APIs to Windows Store for Business.

This change is not reflected in existing Enterprise apps, see https://learn.microsoft.com/en-us/entra/identity-platform/app-objects-and-service-principals?tabs=browser#consequences-of-modifying-and-deleting-applications

This causes the the app 45a330b1-b1ec-4cc1-9161-9f03992aa49f to be named differently depending on a tenant's age. Making following the instructions for excluding from conditional access incorrect as the app they need to search for to exclude will be Universal Store Service APIs OR Windows Store for Business depending on the tenant. This needs to be reflected in the instructions as it's impossible to search for the app ID directly in conditional access
![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/141368022/69acc951-7bf7-474d-8d33-717a4d56d682)
![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/141368022/d4abe4d6-132c-4ba7-aaea-37fa375d36b3)
![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/141368022/eabeec0a-0f40-4528-8732-97d4e4b4d7e4)

(admin edit: add article metadata for proper linkage)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6443e532-640d-81c0-8215-b711bd1977d4
* Version Independent ID: fc504984-91d7-b586-04ec-4c751fb48998
* Content: [Windows subscription activation - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **windows-client**
* Technology: **itpro-fundamentals**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by abitlegacy** [comment]
To expand on this, I had a sandbox tenant without Windows Store for Business or the Universal Store API on the tenant. I then logged into https://businessstore.microsoft.com to invite the application into the sandbox tenant. After logging in, I saw that the application was created with the Windows Store for Business name, not with the expected Universal Store Service APIs and Web Application name.
![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/7048561/eba6cc3f-a71e-41ca-b95b-9709aae16bdf)

**Comment by v-aweber** [comment]
@aczechowski, what was the date created on the tenant you looked at?

**Comment by aczechowski** [comment]
Hi @v-aweber - thanks for filing this as an issue. We'll need to investigate further and see if we can figure out someone that can help clarify.

> @aczechowski, what was the date created on the tenant you looked at?

In the tenant to which I have access, the **Created on** field for ID 45a330b1-b1ec-4cc1-9161-9f03992aa49f is null/blank. 🤷

**Comment by frankroj** [comment]
Related to https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11794
