### ISSUE TITLE
broken links 

### ISSUE THREAD

**Issue by akwitt** [MicrosoftDocs/windows-itpro-docs#11806]
Abschnitt: https://learn.microsoft.com/de-de/windows/security/operating-system-security/data-protection/bitlocker/faq#was-ist-der-unterschied-zwischen-einem-wiederherstellungskennwort--einem-wiederherstellungsschl-ssel--einer-pin--einer-erweiterten-pin-und-einem-systemstartschl-ssel

Die beiden Links 
[BitLocker-Schlüsselschutzvorrichtungen](https://learn.microsoft.com/de-de/windows/security/operating-system-security/data-protection/bitlocker/prepare-your-organization-for-bitlocker-planning-and-policies#bitlocker-key-protectors) und [BitLocker-Authentifizierungsmethoden](https://learn.microsoft.com/de-de/windows/security/operating-system-security/data-protection/bitlocker/prepare-your-organization-for-bitlocker-planning-and-policies#bitlocker-authentication-methods) 
funktionieren nicht mehr.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er wird für die Verknüpfung von learn.microsoft.com zum GitHub-Issue benötigt.*

* ID: 19f04ae6-e5cb-033f-efd9-c6c2eaade44c
* Version Independent ID: 19f04ae6-e5cb-033f-efd9-c6c2eaade44c
* Content: [Häufig gestellte Fragen zu BitLocker - Windows Security](https://learn.microsoft.com/de-de/windows/security/operating-system-security/data-protection/bitlocker/faq)
* Content Source: [windows/security/operating-system-security/data-protection/bitlocker/faq.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/operating-system-security/data-protection/bitlocker/faq.yml)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Thank you for the feedback, @akwitt ! I'll fix the broken links today.

**Comment by paolomatarazzo** [comment]
closing the issue as this appears to be a delay in the translation to de-de for the refreshed articles.
