### ISSUE TITLE
Windows Hello for Business | Network requirement

### ISSUE THREAD

**Issue by JohnKesko** [MicrosoftDocs/windows-itpro-docs#11800]
When I look at https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide
 - I cannot find which services WHfB rely on. 

When working with certain customers, we need to be able to specify the exact subnet ranges and URL's the service need.

Does anyone know where I can find such a list?

**Comment by aczechowski** [comment]
@paolomatarazzo can you help or redirect?

**Comment by paolomatarazzo** [comment]
Hello @JohnKesko can you please clarify what you mean with *which services WHfB rely on*? Assuming your devices are Microsoft Entra joined and you use Microsoft Entra MFA, then all the URLs required for Entra join are all you need (which are included in the document you linked). If you use a different MFA solution, or if you're federated, then different URLs may be needed.

**Comment by JohnKesko** [comment]
@paolomatarazzo Devices are Entra hybrid joined and using Entra MFA.

Well, what I mean with "what services WHfB rely on" was - are you saying everything in this section from the URL I included or something more?
"Microsoft 365 Common and Office Online"?

For context, I can't open up for internet for this particular customer, so I need to specify all URL's and subnets in the FW that WHfB needs.

**Comment by paolomatarazzo** [comment]
What I'm saying is that you don't need to open any additional ports than the ones you should already be using to make WHfB work. WHfB doesn't add any requirements in terms of ports/URLs. Makes sense?

**Comment by JohnKesko** [comment]
@paolomatarazzo 
Not sure if we're talking through each other here.

A client configured with WHfB need to talk to some endpoints in Azure to verify identity.
In my FW, I need set outgoing rules to allow traffic to these endpoints.

Which endpoints should I use? ie. which URL's/subnets within the list I included should I use to create my FW rules for outgoing traffic?

**Comment by paolomatarazzo** [comment]
I hope we are talking through each other, so I'll try one more time.

With WHfB you unlock a private key protected by gesture/bio/PIN. Then the client gets a new or refresh token to Microsoft Entra ID. The fact that you used WHfB or a password is irrelevant, the endpoints to obtain/refresh the tokens are the same. The URLs/IPs/Ports are documented here: https://learn.microsoft.com/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#microsoft-365-common-and-office-online

**Comment by JohnKesko** [comment]
Great, thanks! So back to my earlier question, is everything within this list needed for WHfB?

I know most customers don't care and have internet wide open, so this would never become an issue. However, with certain customers, they have specific needs for variety of reasons, hence my specific question.

**Comment by JohnKesko** [comment]
Great, thanks!
