### ISSUE TITLE
The setting of "Notify Malicious" is disabled by default on GPO and Intune, but this setting is enabled by Windows 11 default.

### ISSUE THREAD

**Issue by kash1064** [MicrosoftDocs/windows-itpro-docs#11811]
Could you add a note about the setting of "Notify Malicious" is enabled by Windows 11 default?

This page said the setting of "Notify Malicious" is disabled by default on GPO and Intune.
---
If you disable or don't configure this policy setting, Enhanced Phishing Protection doesn't warn users if they type their work or school password into one of the malicious scenarios described above.
---

However I know this setting is enabled by "Windows 11 default".
That is announced below official page.

Source: https://support.microsoft.com/en-us/topic/protect-your-microsoft-password-from-being-phished-e4e8e611-e4b3-4be9-914c-db1657c337cf
---
Once the app is open, scroll down to Phishing protection and select the settings you want. By default, you are only protected against entering your password into malicious content.
---

Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d860e9d3-0ead-86d4-c3b9-138cbd37ee62
* Version Independent ID: d860e9d3-0ead-86d4-c3b9-138cbd37ee62
* Content: [Enhanced Phishing Protection in Microsoft Defender SmartScreen - Windows Security](https://learn.microsoft.com/en-us/windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/enhanced-phishing-protection?tabs=intune)
* Content Source: [windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/enhanced-phishing-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/enhanced-phishing-protection.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
Hey @kash1064, "Notify malicious" is off by default for Commercial customers, but for consumers it is indeed on by default. I'll add a note to this document to clarify this further.
