### ISSUE TITLE
Unfinished sentence

### ISSUE THREAD

**Issue by davidpaMSFT** [MicrosoftDocs/windows-itpro-docs#1181]
This article has an unfinished sentence at the end of second paragraph in "Operations Management Suite or Azure Log Analytics" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7ce50b9-cb28-a5ba-58f9-010e69f4fde5
* Version Independent ID: a161fed8-151a-1eca-8663-93e9365877d2
* Content: [Upgrade Readiness requirements (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-requirements)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-requirements.md)
* Product: **w10**
* GitHub Login: @jaimeo

**Comment by andreabichsel** [comment]
@jaimeo, can you investigate?

**Comment by jaimeo** [comment]
I have been OOF, but will investigate now that I’m back.
vv
J.O.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jaimeo** [comment]
fixed
