### ISSUE TITLE
CSP for Copilot in Windows having path incomplete.

### ISSUE THREAD

**Issue by FlorinDoroftei** [MicrosoftDocs/windows-itpro-docs#11815]
Hi team,

I was presented by 2 clients that the OMA-URI for the CSP for Copilot in Windows is incomplete and is failing to apply correctly. So the path working for them is: ./User/Vendor/MSFT/Policy/Config/WindowsAI/TurnOffWindowsCopilot
Can we confirm that is correct? If that confirmed, Can we change it so not confusing other clients using the documentation?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dec48bfe-06ba-23ff-d25f-1cc3db4d86ae
* Version Independent ID: dec48bfe-06ba-23ff-d25f-1cc3db4d86ae
* Content: [Enterprise feature control in Windows 11 - What's new in Windows](https://learn.microsoft.com/en-us/windows/whats-new/temporary-enterprise-feature-control#windows-11-features-with-permanent-enterprise-feature-control)
* Content Source: [windows/whats-new/temporary-enterprise-feature-control.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/temporary-enterprise-feature-control.md)
* Product: **windows-client**
* Technology: **itpro-fundamentals**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Confirmed with Meghan - I'll fix this in another PR I have open.
