### ISSUE TITLE
Passkey settings

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/windows-itpro-docs#11829]
"Starting in Windows 11, version 22H2 with [KB5030310](https://support.microsoft.com/kb/5030310), you can use the Settings app to view and manage passkeys saved for apps or websites. Go to Settings > Accounts > Passkeys, or use the following shortcut:"

It's at Settings, Accounts, **Passkey settings** in Windows 11.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86356b2f-7238-d4dd-5872-57bb1e6f564a
* Version Independent ID: 86356b2f-7238-d4dd-5872-57bb1e6f564a
* Content: [Support for passkeys in Windows - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/passkeys/?tabs=windows)
* Content Source: [windows/security/identity-protection/passkeys/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/passkeys/index.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by aczechowski** [comment]
Thanks @BR77BE for the feedback...although I'm seeing the same as the doc, just **Passkeys**:
![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/26784733/cde2b217-4ada-475f-8e44-21e098a831db)
@paolomatarazzo any thoughts?

**Comment by BR77BE** [comment]
Strange:

<img width="542" alt="Passkey settings" src="https://github.com/MicrosoftDocs/windows-itpro-docs/assets/44044256/22f24e5a-c023-4df2-9bf3-850e2aa651bc">

**Comment by paolomatarazzo** [comment]
That's weird... which builld are you using @BR77BE ?
<img width="297" alt="image" src="https://github.com/MicrosoftDocs/windows-itpro-docs/assets/74918781/8db72f2d-6a9b-4491-a976-76f4c16e7a1f">

**Comment by BR77BE** [comment]
22631.2787

**Comment by paolomatarazzo** [comment]
That's an insider build. I take screenshots from production builds. It's possible that there are upcoming UI changes.
