### ISSUE TITLE
Web sign-in note outdated?

### ISSUE THREAD

**Issue by CBrasga** [MicrosoftDocs/windows-itpro-docs#11828]
The Web sign-in Warning under EnableWebSignIn that it only supports Temporary Access Pass as an authentication method may be outdated. The latest information on the Web sign-in page says the capabilities have been expanded with Windows 11:

"With the release of Windows 11, the supported scenarios and capabilities of Web sign-in are expanded.
For example, you can sign in with the Microsoft Authenticator app or with a SAML-P federated identity."
(https://learn.microsoft.com/en-us/windows/security/identity-protection/web-sign-in/)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 845fc177-23cf-0b2c-4b2b-5ac3966763a6
* Version Independent ID: ef4248eb-9b9f-24ec-631e-d65ae2ae3ecf
* Content: [Authentication Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-Authentication?WT.mc_id=Portal-Microsoft_Intune_Workflows#authentication-configurewebsigninallowedurls)
* Content Source: [windows/client-management/mdm/policy-csp-authentication.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-authentication.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @CBrasga for the feedback!
@paolomatarazzo and @vinaypamnani-msft can ya'll tag team to determine if this note is an [editable section of the CSP article](https://learn.microsoft.com/en-us/windows/client-management/mdm/contribute-csp-reference), and if so how it should be handled?

**Comment by paolomatarazzo** [comment]
@CBrasga thank you for the feedback, I'll update the CSP documentation.
