### ISSUE TITLE
2. Create a passkey from your account settings

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/windows-itpro-docs#11830]
"2. Create a passkey from your account settings"

What does this step mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86356b2f-7238-d4dd-5872-57bb1e6f564a
* Version Independent ID: 86356b2f-7238-d4dd-5872-57bb1e6f564a
* Content: [Support for passkeys in Windows - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/passkeys/?tabs=windows)
* Content Source: [windows/security/identity-protection/passkeys/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/passkeys/index.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @BR77BE, the steps described should be applicable to any application out there, so we can't be too specific. The idea is:
In step #1 you open a website or app that supports passkeys (for example `github.com`)
In step #2 you find the section of that app that has your *account settings*. If the app supports passkeys, you should see a dedicated section under the *account settings* where you can create a passkey.

Hope it helps.
