### ISSUE TITLE
Guidelines for choosing an app for assigned access (kiosk mode)

### ISSUE THREAD

**Issue by yueyuecompany23** [MicrosoftDocs/windows-itpro-docs#11837]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd2d1007-2cbb-94a6-18aa-a0b879262ab1
* Version Independent ID: 625d9906-0cb0-23eb-3a56-a84ad774d291
* Content: [Guidelines for choosing an app for assigned access - Configure Windows](https://learn.microsoft.com/en-us/windows/configuration/guidelines-for-assigned-access-app)
* Content Source: [windows/configuration/guidelines-for-assigned-access-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/guidelines-for-assigned-access-app.md)
* Product: **windows-client**
* Technology: **itpro-configure**
* GitHub Login: @lizgt2000
* Microsoft Alias: **lizlong**

**Comment by aczechowski** [comment]
This looks like maybe an issue filed by accident, so I'm closing it. If you do have some specific feedback on this article, please reopen and add more detail.
