### ISSUE TITLE
us/windows/security/hardware-security/tpm/switch-pcr-banks-on-tpm-2-0-devices)

### ISSUE THREAD

**Issue by asrhgf** [MicrosoftDocs/windows-itpro-docs#11836]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55b3bd7a-b069-ae6c-7ea3-257b8c78e2e0
* Version Independent ID: 55b3bd7a-b069-ae6c-7ea3-257b8c78e2e0
* Content: [UnderstandPCR banks on TPM 2.0 devices - Windows Security](https://learn.microsoft.com/en-us/windows/security/hardware-security/tpm/switch-pcr-banks-on-tpm-2-0-devices)
* Content Source: [windows/security/hardware-security/tpm/switch-pcr-banks-on-tpm-2-0-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/hardware-security/tpm/switch-pcr-banks-on-tpm-2-0-devices.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Assuming a misfire, closing
