### ISSUE TITLE
TPM using Windows PowerShell. For details, see 

### ISSUE THREAD

**Issue by asrhgf** [MicrosoftDocs/windows-itpro-docs#11835]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f424ce3a-a0fc-9c92-928b-8fdb40d6ac43
* Version Independent ID: f424ce3a-a0fc-9c92-928b-8fdb40d6ac43
* Content: [Manage TPM commands - Windows Security](https://learn.microsoft.com/en-us/windows/security/hardware-security/tpm/manage-tpm-commands)
* Content Source: [windows/security/hardware-security/tpm/manage-tpm-commands.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/hardware-security/tpm/manage-tpm-commands.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
I'm assuming this is an accidental feedback, so closing. If I'm incorrect, please reopen and provide more detail.
