### ISSUE TITLE
Sample Code to Configure Google Workspace as a Service Provider Does Not Work

### ISSUE THREAD

**Issue by john-craft** [MicrosoftDocs/windows-itpro-docs#11833]
**To reproduce**:

1. Copy the sample PowerShell code in [the help document](https://learn.microsoft.com/en-us/education/windows/configure-aad-google-trust) into a text file and save it with as `set-google-as-idp.ps1` to create a runnable PowerShell script.
2. Ensure the script is in the same directory as `GoogleIDPMetadata.xml` that was downloaded in the "Configure Google Workspace as an IdP for Microsoft Entra ID."
3. Run the PowerShell script from the command line, ex., `> .\set-google-as-id.ps1`.
4. When prompted to authenticate to Microsoft Entra ID, use the credentials of an account with the _Global Administrator_ role.
5. See the errors on the command line (below)

```sh
Connect-MgGraph: C:\Users\john\Downloads\set-google-as-idp.ps1:14
Line |
  14 |  Connect-MGGraph -Scopes "Domain.ReadWrite.All", "Directory.AccessAsUs …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The type initializer for 'Azure.Identity.AuthenticationRecord' threw an exception.

New-MgDomainFederationConfiguration_CreateExpanded: C:\Users\john\Downloads\set-google-as-idp.ps1:28
Line |
  28 |  New-MgDomainFederationConfiguration @domainAuthParams
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Authentication needed. Please call Connect-MgGraph.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aab824fb-b795-518a-8d52-7490975ab5ac
* Version Independent ID: aab824fb-b795-518a-8d52-7490975ab5ac
* Content: [Configure federation between Google Workspace and Microsoft Entra ID - Windows Education](https://learn.microsoft.com/en-us/education/windows/configure-aad-google-trust)
* Content Source: [education/windows/configure-aad-google-trust.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/education/windows/configure-aad-google-trust.md)
* Product: **windows-client**
* Technology: **itpro-edu**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @john-craft the commands have been validated more than once. However, not as a script. Can't you run it line by line? It's not code that require to be run on a regular basis, just once. I don't have a lab to test the steps that you describe at the moment. 

There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by john-craft** [comment]
Thanks for the quick response, @paolomatarazzo!

> Hello @john-craft the commands have been validated more than once. However, not as a script. Can't you run it line by line?

Yes, I will try that next.

> There are a couple of options available to provide the best level of support for this issue:

Good to know.

> I'm closing this issue as there's nothing actionable for docs at this time.

The docs could be a little more clear and there's a mistake in the reference to `$DomainName`, so I'd recommend making the changes below (**bold text** are suggested changes).

> **Once** the IdP metadata XML file **has been** downloaded from Google Workspace, modify the **$domainId** variable **in the code block below** to match your environment, and then run it **line by line** in a PowerShell session.

**Comment by john-craft** [comment]
Hi @paolomatarazzo, it looks like PowerShell 7 or above is needed. I updated the suggested docs changes below to reflect that requirement.

>  **Once** the IdP metadata XML file **has been** downloaded from Google Workspace, modify the **$domainId** variable **in the code block below** to match your environment, and then run it **line by line** in a PowerShell session. **Use the latest version of PowerShell 7+ as the runtime version**.
