### ISSUE TITLE
Discrepancy Between "Best practices" And Password Research

### ISSUE THREAD

**Issue by aakash-shah** [MicrosoftDocs/windows-itpro-docs#1185]
The "Best practices" section states to "Set Maximum password age to a value between 30 and 90 days, depending on your environment."  However, this conflicts with the information under "Considerations" as well as the linked Password Research Paper:
https://www.microsoft.com/en-us/research/wp-content/uploads/2016/06/Microsoft_Password_Guidance-1.pdf

This provides conflicting advice and causes confusion for IT departments looking for specific and direct information (since both sides of the argument can point to this same page but get different information).

Please reconcile these conflicts and provide more consistent guidance.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed5f0d1b-bfbb-c2a8-76e7-b4b0105160e8
* Version Independent ID: 13684860-a76b-5832-4376-22a585f63fd1
* Content: [Maximum password age (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/maximum-password-age#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/maximum-password-age.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/maximum-password-age.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by aakash-shah** [comment]
Hello!  The issue I see is that the Microsoft "Best practices" section listed on this page conflicts with Microsoft's own password research paper as well as the recently published NIST 800-63B (https://pages.nist.gov/800-63-3/sp800-63b.html) where periodic/arbitrary password changes are no longer recommended.  With these two large bodies of study and guidance, the "Best practice" section on this page should be changed to reflect this new information, and then under "Considerations", it can list any other nuances that need to be listed. 

With the way the page is currently written, the page reads that MS still recommends as its best practice to change the password every 30-90 days.  IT decision makers are likely to reference this solely and ignore the "Considerations" section.

**Comment by egallagh** [comment]
It is all about context. This page is not intended to address comprehensibly all the issues needed to properly address password security. It is not true that periodic password changes are no longer recommended. It is true that periodic password changes are no longer recommended when also addressed within the context of MANY other recommendations. For example, the inclusion of MFA into the authentication process, which is something that Windows 10, by itself, is not capable of implementing. Singling out one specific component of a new set of recommendations is not appropriate.

**Comment by Justinha** [comment]
@egallagh well stated, thanks. Others have also pointed out that there is no way to use Group Policy implement *all* of the recommendations in the research paper. Rather than selectively changing some of the related GP recommendations, we included the link to the research so admins are better informed.
