### ISSUE TITLE
Win 10 1803 - 17134 drivers?

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/windows-itpro-docs#1190]
Why is it that only the Surface 3 (non Pro) is the only model that has 17134 drivers released? Are the Pro 3 / 4 / 2017 going to get them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586d1246-6e18-b33c-2382-52a53bb392f5
* Version Independent ID: 0ec4aa1e-aac0-98dd-0a47-83e93d854086
* Content: [Download the latest firmware and drivers for Surface devices (Surface)](https://docs.microsoft.com/en-us/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices)
* Content Source: [devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md)
* Product: **w10**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by BRecords** [comment]
Surface driver and firmware packs are marked by a minimum OS requirement in the form of a Windows 10 build number. Which is to say that surface 3 is the only surface device that has drivers which require Windows 10 17134, where other surface devices have drivers which support both 16299 and 17134, or potentially even a single set of drivers for 15063, 16299, and 17134.

All Surface devices from Surface Pro 3 up support 17134 and have drivers that support 17134.

Brandon Records
Sr. Program Manager
Corporate Online Services

Sent from mobile, apologies for brevity.


-------- Original message --------
