### ISSUE TITLE
USB-C drivers?

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/windows-itpro-docs#1191]
There are only updated drivers for Pro (2017) for USB-C not for Laptop?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586d1246-6e18-b33c-2382-52a53bb392f5
* Version Independent ID: 0ec4aa1e-aac0-98dd-0a47-83e93d854086
* Content: [Download the latest firmware and drivers for Surface devices (Surface)](https://docs.microsoft.com/en-us/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices)
* Content Source: [devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md)
* Product: **w10**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by BRecords** [comment]
The Surface Laptop drivers have been available for about a month. See the Surface Blog for IT Pros for more information. The latest post covers this topic.


Brandon Records
Sr. Program Manager
Corporate Online Services

Sent from mobile, apologies for brevity.


-------- Original message --------
