### ISSUE TITLE
Drivers removed from Pro (2017)?

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/windows-itpro-docs#1192]
If you look at the driver packages for Pro (2017) of latest with USB-C and prior the newest one is 70 MB bigger but according to Readme in the files lots of drivers have been removed? Things like dock firmware and fingerprint or Bluetooth pairing? Are these no longer supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586d1246-6e18-b33c-2382-52a53bb392f5
* Version Independent ID: 0ec4aa1e-aac0-98dd-0a47-83e93d854086
* Content: [Download the latest firmware and drivers for Surface devices (Surface)](https://docs.microsoft.com/en-us/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices)
* Content Source: [devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md)
* Product: **w10**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by hoyty76** [comment]
Missing drivers:
SurfaceAccessoryBluetoothPairing
SurfaceDockFwUpdate
SurfaceDockIntegration
SurfaceKeyboardBluetoothFingerprintSensor
SurfaceKeyboardFingerprintIntegration
SurfaceKeyboardFingerprintSensor
SurfaceTypeCoverV3FwUpdate
USBAudio
SurfacePen
SurfacePenClickFilter
Chipset_LPSDHost
Chipset_LPSystemNorthpeak
Chipset_LPSystemThermal
DPTF_dptf_pch_RS4RS3RS2_
SerialIO_SPI
SurfacePowerMeter

**Comment by BRecords** [comment]
The Surface Pro driver and firmware pack recently released (6/29) is specifically to add the functionality for USB-C while we work to finalize release of the final USB-C driver package alongside many other updates for Surface Pro drivers and firmware in the next few weeks.

Full details are available in the Surface Connect to USB-C Adapter announcement blog post on the Surface Blog for IT Pros<https://blogs.technet.microsoft.com/surface/2018/06/29/announcing-availability-of-the-surface-connect-to-usb-c-adapter-for-surface-pro-and-surface-laptop/>.

Brandon Records
Senior Program Manager
Corporate Online Services
