### ISSUE TITLE
Logs? Troubleshooting?

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#1194]
I would like to see more on Logs, Troubleshooting the Windows Autopilot process when it fails.  Example 0x800705b4, you can choose "Reset device" which does work to reset.. and you can choose "Collect Logs" oddly enough the choice does not present you with the logical file path WHERE the logs can be seen/reviewed?  Where are the logs?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40564b31-c91f-2769-e3e0-0b72121a9951
* Version Independent ID: 2ad13ef4-41c5-3ce3-ddaa-827291fcc944
* Content: [Overview of Windows Autopilot](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-10-autopilot)
* Content Source: [windows/deployment/windows-autopilot/windows-10-autopilot.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-10-autopilot.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by andreabichsel** [comment]
@coreyp-at-msft can you investigate?

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by NeilPetersen** [comment]
I know there are other posts which explain collecting logs but correctly as @Tdiwestyguy has highlighted the collect logs will just open a windows explorer process. Maybe if the collect logs executed "MDMDIAGNOSTICSTOOL -area Autopilot -Cab C:\Temp\Auotpilot.cab" and gave you the option to save these to export the diagnostics information?

**Comment by greg-lindsay** [comment]
This is a really old issue. I only discovered it by running a custom query. We need better notification tools.  

I feel that https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/troubleshooting provides the answers to this question. This doc was written after the issue was created. Please comment if this doesn't resolve the issue, but I'm closing this issue for now.
