### ISSUE TITLE
CTRL+ALT+DELETE with Windows Helo \ Fingerprint login

### ISSUE THREAD

**Issue by scbates930** [MicrosoftDocs/windows-itpro-docs#1195]
I'd like to be able to not use CTRL+ALT+DELETE when logging on with finger print.  
I can do this on my Lenovo X1 - but on my Dell XPS 13 I need CTRL+ALT+DELETE first.  It is quicker with just the finger print and means I can unlock PC with just one hand.  The article states that not using CTRL+ALT+DELETE is less secure - but as the functionality I'm interested in requres my finger print I'm not convinced that this would be a step back in security.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37a73a55-d78f-64cc-4764-51f3e0a87d4c
* Version Independent ID: 68ee2547-18a5-ad1c-725d-c2a8960c7f54
* Content: [Interactive logon Do not require CTRL+ALT+DEL (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-do-not-require-ctrl-alt-del)
* Content Source: [windows/security/threat-protection/security-policy-settings/interactive-logon-do-not-require-ctrl-alt-del.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/interactive-logon-do-not-require-ctrl-alt-del.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by JGezels** [comment]
When enabling this feature (so people need to press control+alt+delete) it doesn't work when a machine is rebooted. I only get the "press-ctr-alt-delete" when I sign-out and return on the login screen.

**Comment by Justinha** [comment]
@JGezels It should persist after restart. There could be a few different factors that would cause this, including the policy being overwritten by another. Also, the wording for this policy is tricky, but if you enable this setting users do not need to press control+alt+delete.

**Comment by Justinha** [comment]
@scbates930 You're right, fingerprint is secure. You can set Windows Hello for fingerprint and sign in without pressing control+alt+delete

**Comment by xencon** [comment]
@Justinha, the guidance to disable this attempts to thwart password compromise by a rogue process. I agree that this doesn't have much value if you're using Windows Hello, but I am concerned that since Hello will allow password use as a backup, the setting should still be disabled (i.e. we should still require CAD before Hello or password entry). Are there possibly other articles to reference here for wider guidance as to the risk of enabling this policy?
