### ISSUE TITLE
Get not post

### ISSUE THREAD

**Issue by chbreakthrough** [MicrosoftDocs/windows-itpro-docs#1196]
Your initial example in the HTTP Request is a Post your actual (working) example is a GET. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee788645-f1a8-98c2-847e-cfb0009be958
* Version Independent ID: b64f1675-1b36-190b-f373-5d5bd2efb619
* Content: [Get package SAS URI API](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/get-package-sas-uri-windows-defender-advanced-threat-protection#example)
* Content Source: [windows/security/threat-protection/windows-defender-atp/get-package-sas-uri-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/get-package-sas-uri-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Thank you for your feedback. 

This has been updated and will be reflected in the documentation shortly.
