### ISSUE TITLE
ronald878787

### ISSUE THREAD

**Issue by ronald878787** [MicrosoftDocs/windows-itpro-docs#1198]
docs

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c7b0bed0-d344-9e32-f789-ddebb0309ecf
* Version Independent ID: 6c821f59-d507-df49-19c7-9a98dd162bf0
* Content: [Windows 10, version 1709 and newer diagnostic data for the Full level (Windows 10)](https://docs.microsoft.com/ja-jp/windows/privacy/windows-diagnostic-data#anon)
* Content Source: [windows/privacy/windows-diagnostic-data.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/windows-diagnostic-data.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by andreabichsel** [comment]
Closing for now. If you can elaborate on the issue, I'll reopen. Thanks!
