### ISSUE TITLE
404 for Link to TPM owner password

### ISSUE THREAD

**Issue by beanska** [MicrosoftDocs/windows-itpro-docs#1201]
"http://technet.microsoft.com/en-us/itpro/windows/keep-secure/change-the-tpm-owner-password" give a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e11e1beb-b1ed-8a2d-f3d9-810e777fe594
* Version Independent ID: e4f95ae3-0ac2-37b6-ba5e-d1ff67855109
* Content: [How to Enable BitLocker by Using MBAM as Part of a Windows Deployment](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/how-to-enable-bitlocker-by-using-mbam-as-part-of-a-windows-deploymentmbam-25)
* Content Source: [mdop/mbam-v25/how-to-enable-bitlocker-by-using-mbam-as-part-of-a-windows-deploymentmbam-25.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/how-to-enable-bitlocker-by-using-mbam-as-part-of-a-windows-deploymentmbam-25.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by egallagh** [comment]
The link target for "TPM owner password" does connect to the URL listed by the user beanska. That target redirects to https://docs.microsoft.com/en-us/windows/securityhardware-protection/tpm/change-the-tpm-owner-password which does lead to a 404 result. The redirect is missing a backslash between /security and hardware-protection/
The correct redirect should be https://docs.microsoft.com/en-us/windows/security/hardware-protection/tpm/change-the-tpm-owner-password

**Comment by andreabichsel** [comment]
Fixed link.
