### ISSUE TITLE
Windows spotlight picture titles.

### ISSUE THREAD

**Issue by MarkManley2017** [MicrosoftDocs/windows-itpro-docs#1227]
Is there a way, or add the ability, to display the Windows Spotlight picture titles, I'd like to know where these place are located.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0286c17f-aca8-c9bc-597c-86b70165c72e
* Version Independent ID: be2bdcde-8667-4ff5-c4e5-bd50696d9341
* Content: [Configure Windows Spotlight on the lock screen (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/windows-spotlight)
* Content Source: [windows/configuration/windows-spotlight.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/windows-spotlight.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@MarkManley2017 In the top right corner of your lockscreen showing Windows Spotlight, there should be "Like what you see?" If you hover on that, the name and source of the photo should be listed. In addition, there should be "hotspots" in various parts of the screen offering more information about the subject of the photo.

**Comment by MarkManley2017** [comment]
@jdeckerms Is there a way (key combination, etc.) to make the hover hints appear where they're not visible?

**Comment by jdeckerms** [comment]
@MarkManley2017 I don't know of one. If you're not able to make them appear, please let the product team know about the problem by using the Feedback Hub.

**Comment by jdeckerms** [comment]
@cgillespie-diobpt There isn't, but you can create a folder of the images you want, and selecting that folder for the "Photos" screensaver.

**Comment by ksobier** [comment]
What is the reason for this not to work on Pro anymore? As a company we have lots of Pro computers but now we lost ability to control couple of things using GPOs for no reason. How do you expect us to go to every PC to change settings?

**Comment by jdeckerms** [comment]
@ksobier Please use the Feedback Hub to provide your opinion on managing Pro so the engineering team receives it and can take it in account for product planning.
