### ISSUE TITLE
Auto Login

### ISSUE THREAD

**Issue by rogorek** [MicrosoftDocs/windows-itpro-docs#1228]
We are using a local admin account on a machine that isn't domain-joined. We have set up shared PC mode but by default the lock screen asks for a user name and password. A user would need to go to the bottom left and select Guest to login. Any way to make Guest the default logon account? Also any way to set up Auto Logon on the Guest account in shared PC mode?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14b376e2-39bd-faca-a76c-dd21bad8d8fd
* Version Independent ID: a76cabb0-59b9-7e97-6603-eec7d37f1fd4
* Content: [Set up a shared or guest PC with Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/set-up-shared-or-guest-pc)
* Content Source: [windows/configuration/set-up-shared-or-guest-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/set-up-shared-or-guest-pc.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@rogorek Sorry, making "Guest" the default sign-in account isn't possible at this time, but I encourage you to let the product team know that you're interested in having that feature by using the Feedback Hub.

It's possible to edit the registry to automatically sign in an account (see the instructions at https://docs.microsoft.com/en-us/windows/configuration/setup-kiosk-digital-signage#other-settings-to-lock-down) but that's documented for kiosk mode. I don't know what problems might occur if used with shared PC mode.
