### ISSUE TITLE
No data?

### ISSUE THREAD

**Issue by subdriven** [MicrosoftDocs/windows-itpro-docs#1230]
I don't see anything here in this article. It just says Applies to Windows 10, Windows Server then says Feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502022a2-ef69-a4e2-18b0-c08386ec942a
* Version Independent ID: 7879db2a-b200-3d69-407f-093c6c4a0265
* Content: [Administering AppLocker by using Mobile Device Management (MDM) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/administer-applocker-using-mdm)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/applocker/administer-applocker-using-mdm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/applocker/administer-applocker-using-mdm.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by jasongroce** [comment]
Thanks for pointing this out, @subdriven. @Justinha can you take a look?

**Comment by ManojKamath** [comment]
@Jasongroce @Justinha @subdriven - Was this article deeplinked somewhere else? There is still no content on this topic. <Sigh!>

**Comment by ManojKamath** [comment]
Or is it just possible that Administer AppLocker using MDM is a container object and the topic on MDM administration is actually articulated under Maintain AppLocker policies? Curious.

**Comment by ManojKamath** [comment]
Crazy that - how do we find official documentation that is directly related to a MS certification course that has no "official" course book but has skill testing om MDM, activation, (even RemoteApp but that is a thorny topic that no one at MS is willing to talk about currently) on a official examination. Sad state of affairs for sure.

**Comment by illfated** [comment]
If there is no relevant information (feel free to look for it) in any of the other chapters linked from the parent document (https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/administer-applocker), I suggest that someone from the tech team takes a look at it and checks if there is any available documentation to be provided in the [reported and linked page](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/administer-applocker-using-mdm) (see originating issue comment).

**Comment by shortpatti** [comment]
@Justinha, can you take a look at this one?

**Comment by Justinha** [comment]
Hey everyone, Thanks for reporting and I apologize for my delayed reply. I mistakenly published this placeholder topic and need to circle back with our engineering partners to get it completed.

**Comment by mypil** [comment]
@Justinha - Do you have any updates on the status or progress of this issue?

**Comment by Justinha** [comment]
@mypil sorry Joyce, no progress on this. I'm removing the blank placeholder topic until we can get this written. Applocker docs in general are lower priority than Windows Defender Application Control. That's where most new app control related content will go.
