### ISSUE TITLE
Set AllowDeviceNameInTelemetry Missing

### ISSUE THREAD

**Issue by cconrado** [MicrosoftDocs/windows-itpro-docs#1231]
Unable to set this value using mdm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 613a93fe-ef09-40aa-f088-a476c4de4214
* Version Independent ID: a9efe92b-dd9a-e4a3-9e99-cb16f5a1af11
* Content: [DMClient CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/dmclient-csp)
* Content Source: [windows/client-management/mdm/dmclient-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/dmclient-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by wadstromdev** [comment]
Any update on this setting?

**Comment by illfated** [comment]
@cconrado : I know this is a long, long time after you posted your issue, but have you been able to get any further with that problem or contact your local Microsoft Support department about it?

**Comment by VLG17** [comment]
@cconrado The CSP option (starting with 1809 and above) is named **System/AllowDeviceNameInDiagnosticData** . 

**./Vendor/MSFT/Policy/Config/System/AllowDeviceNameInDiagnosticData**

More details [here](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-system#system-allowdevicenameindiagnosticdata).

**Comment by nam31** [comment]
@cconrado  Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
