### ISSUE TITLE
Windows 10 1803

### ISSUE THREAD

**Issue by MrM40** [MicrosoftDocs/windows-itpro-docs#1233]
I assume this doesn't work on 1803, rigth!
I have not been able to change it using this XML file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cbbc03b-78ac-4464-0ec8-d7379db167f4
* Version Independent ID: 6188559c-859b-77b7-8fd7-ae4bd59c06b8
* Content: [Set the default browser using Group Policy (Internet Explorer 11 for IT Pros)](https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/set-the-default-browser-using-group-policy)
* Content Source: [browsers/internet-explorer/ie11-deploy-guide/set-the-default-browser-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/internet-explorer/ie11-deploy-guide/set-the-default-browser-using-group-policy.md)
* Product: **ie11**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by lochyw** [comment]
I have tested using local policy on 1709 that only putting the XML in user folder\downloads appears to work. All other locations including domain\netlogon do not appear to apply. 

Can MS assist on this one?

**Comment by Stingi** [comment]
If I activate this GPO would this affect PC with WIN 7? In our site there is mix with WIN 10 and 7 and I only want to affect PC with WIN 10

**Comment by arpierson** [comment]
Same here. Testing on 1803 changes some file association apps, but suspiciously fails to change the browser from Edge.

**Comment by csiebert11** [comment]
I also have an issue using this method. As it stands I cannot change Default applications.

**Comment by Shachar2like** [comment]
doesn't seems to work with 1803 (tried putting the file on the network)

Microsoft's article are becoming uncleared by the day, this article doesn't list to which version this setting applies to which leaves us guessing.

**Comment by Shachar2like** [comment]
ok yeah, there seems to be some weird bug of this part of the policy not being able or programmed to access the network. putting the file locally solves the issue, although when opening pdf files you get a prompt to what to open the file with with adobe reader dc as the first choice but that's not quite the "experience" I'm looking for.

there's some template file from adobe, maybe that will solve that...

**Comment by PrinceMarkieD** [comment]
Does not work in 1803

**Comment by vall3yv** [comment]
Appears to be working via UNC share on Win 10 1809 upon user login defaults are changed.

**Comment by markavenger** [comment]
Hi Vall3yv,    Can you please send me some instructions, links or documentation on how you got it working via UNC share on Win 10 1809 upon user login defaults are changed.  Thanks

**Comment by vall3yv** [comment]
Hey @markavenger its been a few weeks but from what i recall we did the following:

1. Setup a test Win 10 machine and set all default app associations
2. Run following command in elevated Powershell prompt on test machine(update export path):
`Dism /Online /Export-DefaultAppAssociations:\\Server\Share\AppAssoc.xml`
3. Make sure the file share is accessible for all users, for example we have a IT tools share that is available to all domain users. Or if you would like you can copy/import the default app XML file to the default location on Windows 10 and should have the same effect. (C:\WINDOWS\system32\defaultassociations.xml)

**Comment by markavenger** [comment]
Hey vall3yv,

Thank you very much for the instructions. I will give it a try.
My image done with Microsoft Deployment Toolkit is Windows 10 - 1803. I
guess I have to push 1809 with SCCM to the computers and then use GPO
unless there is an easier way.

Best Regards
 @markavenger <https://github.com/markavenger>
John

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
Hello @MrM40 , Thank you for your feedback on the document. Please note that setting up XML format is mentioned in the document (Export or Import Default Application Associations) which has all the necessary details at link https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-8.1-and-8/hh825038(v=win.10)

Thanks.

**Comment by mypil** [comment]
@MrM40 - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by MrM40** [comment]
Well, is the issues fixed or not? That's all that matters?
I reported this back in Jul. 3 2018 and it seem no real effort  has been made to actually solve the software bug or wrong information in the current document!
I critisable that your business customers cannot control the default browser through GPO. 
It's rather irrelevant if there are other documentation in other places (or whatever), it doesn't solve the software bug/wrong info in the current document.

**Comment by joinimran** [comment]
@MrM40 Thank you for your valuable feedback. We are committed to providing the best possible and updated documentation. I can understand your situation here. We value your input here to make the current doc better. If there are suggestions from your side to make this doc better, please do let us know. We will surely update accordingly. 

For your point related to a software bug, that issue can be raised by opening a support ticket with Microsoft technical team so that it can be routed to the concerned person.

@mypil can you please guide @MrM40 to open a support ticket or guide to User Voice Channel so that this request can be forwarded for the fix/addition in the tool.

Thanks.

**Comment by MrM40** [comment]
If any of my customers told me about a bug in my software, I would not tell him do a lot of "my" work to fix it/do furter testing . I would recieve the information he had, make a judement if it really is a bug, if so, the rest is my problem, not the customer.
This clearly is a bug or wrong documentation as I'm not the only one.
BUG: YOU should contact your responsible MS department!
Wrong documentation: YOU should contact the writter and tell him to redo his work, and this time correctly. 
I'll will not use more time on this.

**Comment by mypil** [comment]
@MrM40 - Sorry to hear that you are having issues. Please understand that this site is a product documentation site and not a support nor a feature request site.

As such, the feedback section here is intended for feedback that improves the content in the Microsoft documentation and not intended for user feedback on product features nor troubleshooting.

For user feedback on product feature requests, you can submit via User Voice - **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**. I know the product teams are always looking for user feedback on how to make Windows 10 better. You might find others have made a similar request that you can add to, or you can open a new one.

For troubleshooting, you can visit **support.microsoft.com**, **answers.microsoft.com** or open a support ticket- **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**.

I hope this gets you pointed in the right direction. Thank you.

**Comment by MrM40** [comment]
Fair enough ;-)
I'll make a ticket as it seems to be a bug.
Thanks for guidance.
