### ISSUE TITLE
WDATP cohabitation with Intune Endpoint Protection

### ISSUE THREAD

**Issue by jmrita** [MicrosoftDocs/windows-itpro-docs#1235]
Can WDATP cohabit with Intune Endpoint Protection, or with other words, can MMA for WDATP cohabit with System Center Management, or is MMA able to talk to WDATP as well as Intune ? Thanks in advance,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc8aadae-3a51-93c6-8079-cbd0933471ae
* Version Independent ID: c82444f6-186d-cbee-9b05-9d6d705f44b6
* Content: [Onboard previous versions of Windows on Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/onboard-downlevel-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/onboard-downlevel-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/onboard-downlevel-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Hi jmrita, 

Thank you for the question. I'm not sure I understand. Are you asking if Microsoft Monitoring Agent can be used with SCCM? Can you help me understand the question better?

Thank you
