### ISSUE TITLE
Windows To Go on Windows 10 Pro?

### ISSUE THREAD

**Issue by nick-morhun** [MicrosoftDocs/windows-itpro-docs#1236]
Windows 10 Pro contains the wizard for WTG but in the doc it says only Education and Enterprise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dec06a2d-679d-d3ab-7a22-60407edc4d92
* Version Independent ID: 82932881-c6a5-3f61-bb6c-f3e79f25c4e8
* Content: [Windows To Go frequently asked questions (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-to-go-frequently-asked-questions)
* Content Source: [windows/deployment/planning/windows-to-go-frequently-asked-questions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-to-go-frequently-asked-questions.md)
* Product: **w10**
* GitHub Login: @mtniehaus
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
Hello, @nick-morhun Thank you for submitting your query. Please note that the WTG wizard is available in Educational, Professional and Enterprise edition but you can only create the image for enterprise or education as this feature is available to enterprise and education version of Windows. This is mentioned in the document as well, please see https://docs.microsoft.com/en-us/windows/deployment/planning/windows-to-go-frequently-asked-questions#a-href-idwtg-faq-deployahow-can-windows-to-go-be-deployed-in-an-organization

"A Windows 10 Enterprise, Windows 10 Education or Windows 10 Professional host PC that can be used to provision new USB keys"

Thanks.

**Comment by mypil** [comment]
@nick-morhun - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
