### ISSUE TITLE
WIN 7

### ISSUE THREAD

**Issue by Stingi** [MicrosoftDocs/windows-itpro-docs#1237]
Hello. To a problem here: https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/set-the-default-browser-using-group-policy
If I activate this GPO, would this affect PCs with WIN 7 aswell? In our site there is mix with WIN 10 and 7 and I only want to affect PCs with WIN 10.
I don't want to enable this GPO, if it could mess up with our PCs with WIN 7.
Sorry, for my English, not my native language

**Comment by shortpatti** [comment]
Yes, as long as the Win 7 machines have at least SP1 installed.    Internet Explorer 11 group policies support both Windows 7 and Windows 10.
