### ISSUE TITLE
Characteristic Type for Root Certificate and User Certificate

### ISSUE THREAD

**Issue by sriram-kakarala** [MicrosoftDocs/windows-itpro-docs#1239]
The characteristic type should clearly mention that it is the EncodedRootCertHashInsertedHere instead of some random alpha-numeric key for both root and user certificates.
&lt;characteristic type="031336C933CC7E228B88880D78824FB2909A0A2F/EncodedRootCertHashInsertedHere"&gt;
&lt;parm name="EncodedCertificate" value="B64 encoded cert insert here"/&gt;

&lt;characteristic type="F9A4F20FC50D990FDD0E3DB9AFCBF401818D5462/EncodedRootCertHashInsertedHere"&gt;
&lt;parm name="EncodedCertificate" value="B64EncodedCertInsertedHere" /&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d06bf1eb-9ddd-b89c-866c-78f0d5f348a6
* Version Independent ID: 399fabc9-c643-afd3-354e-7b32cc1e4bc4
* Content: [Federated authentication device enrollment](https://docs.microsoft.com/en-us/windows/client-management/mdm/federated-authentication-device-enrollment)
* Content Source: [windows/client-management/mdm/federated-authentication-device-enrollment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/federated-authentication-device-enrollment.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by DaniHalfin** [comment]
Hi @sriram-kakarala, thanks for reaching out!
It might take us a while to get this change done, but it'll go a lot faster if you use the edit function on the page. That way you show up as a contributor, and we'll appreciate it a lot. If you want to give it a try, I can help out if you have any problems \ questions.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by illfated** [comment]
@sriram-kakarala : Thank you for reporting this issue. As you can see, it has been rectified and is visible on the docs.microsoft.com page.

(This issue ticket can now be closed.)

**Comment by mypil** [comment]
@officedocsbot close
