### ISSUE TITLE
How do we import the settings back in?

### ISSUE THREAD

**Issue by baodad** [MicrosoftDocs/windows-itpro-docs#1241]
This document tells how to export current start menu layout, but it looks like the resulting .xml file can only be deployed to Group Policy or using Windows Configuration Designer.  I'd like to be able to export my start menu layout, and be able to restore it in case something happens.  Would be great if there was an Import-StartLayout powershell cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79fccecd-5484-0304-d82b-9425f1889a22
* Version Independent ID: 4df6b138-c1b5-b551-22c9-19d3d1f9105d
* Content: [Customize and export Start layout (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/customize-and-export-start-layout)
* Content Source: [windows/configuration/customize-and-export-start-layout.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/customize-and-export-start-layout.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@baodad There is a cmdlet: https://docs.microsoft.com/en-us/powershell/module/startlayout/import-startlayout?view=win10-ps  

This blog post talks about the behavior you can expect if you use import-startlayout to apply a custom layout using the cmdlet: https://blogs.technet.microsoft.com/deploymentguys/2016/03/07/windows-10-start-layout-customization/  The key bit of information: "Applying a Start Layout through the Import-StartLayout cmdlet will not enforce the layout and users will have an option to perform changes. This will only apply to new user profiles created in the machine after applying the custom Start Layout."
