### ISSUE TITLE
How to apply this configuration?

### ISSUE THREAD

**Issue by samkshah** [MicrosoftDocs/windows-itpro-docs#1246]
Wondering how an individual user can implement above rule block? Do you have an example of scripts or an explanation about how to configure standalone windows 10 system?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d71055e-2b14-227b-0107-c8f150194d5b
* Version Independent ID: 0eab18a0-7e8f-05eb-b47f-e6913682d8e8
* Content: [Microsoft recommended block rules (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules.md)
* Product: **w10**
* GitHub Login: @jsuther1974
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@samkshah start by creating a CI policy here: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/create-initial-default-policy 

Then you can merge the block list policy as explained here: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/merge-windows-defender-application-control-policies 

We had all of these steps in one topic initially but we split it up bc the doc got really long.

**Comment by mypil** [comment]
@samkshah - From our understanding, the issue has been answered by Justinha. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
