### ISSUE TITLE
Regarding applying the provisioning package to hololens

### ISSUE THREAD

**Issue by JayaSaiSontineni** [MicrosoftDocs/windows-itpro-docs#1247]
Hi,
After successfully creating the provisional package, When I tried connecting my HoloLens to a PC via USB, It has not shown up the device in my PC's File Explorer.
Can you please provide more documentation on this step and also I would like to know whether the HoloLens need to be undergo reset before connecting to PC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24f7361-e06f-b282-0fef-ef541e648251
* Version Independent ID: 85d2c650-645d-7a6c-c366-7a70ba176184
* Content: [Unlock Windows Holographic for Business features (HoloLens)](https://docs.microsoft.com/en-us/hololens/hololens-upgrade-enterprise)
* Content Source: [devices/hololens/hololens-upgrade-enterprise.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/hololens/hololens-upgrade-enterprise.md)
* Product: **hololens**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by JayaSaiSontineni** [comment]
Can I use the same provisioning package for two different HoloLens devices or for every HoloLens I need to create independent provisioning package?

**Comment by jdeckerms** [comment]
@JayaSaiSontineni  The same provisioning package can be applied to multiple devices.

If you've already set up your HoloLens, you have to reset it so that it's on the first setup screen. (Notice in the first step for applying the provisioning package, it says "Connect the device via USB to a PC and start the device, but **do not continue past the fit page of the initial setup experience** (the first page with the blue box). ")

**Comment by JayaSaiSontineni** [comment]
Hi Jeanie,

When I tried applying the same package to multiple devices, It has popping up an Provisioning error ( Installation of provisional package failed. Please work with the package author to diagnose the problem ) after I click on trust, Add it button on the Hololens device.

Can you provide some solution to it.

Thanks,
Jaya Sai Sontineni
Holo Pundits | Systems Analyst
+1 8166168778  | www.holopundits.com<http://www.holopundits.com/>
*** HoloPundits is a Global Technology Company Specializing in developing AR, MR, and VR Applications***


[Logo]
ISO 9001:2015 & ISO 27001:2013 Certified Company

[mixed-reality_badge_side-by-side_blk-blu]
CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by jdeckerms** [comment]
@JayaSaiSontineni Does your provisioning package include a license file to upgrade to Business? I believe the license is for a single device. You would do a separate provisioning package for each upgrade so that each package has a different license file for the device. 

If you want all other settings to be the same, when you start a new provisioning project, you can import the existing provisioning package and then just change the license file in the new one.

**Comment by JayaSaiSontineni** [comment]
Yes it does have a license file to upgrade it to Business version.

Do you want me to use the same provisioning package, But different license file at runtime-settings and attach the package to Hololens Device? Is this what you are trying to say me?

And, I have received different xml files as well from the Microsoft support team. Using which I have created a new provisioning package and tried attaching it to the Hololens Device, Still it was popping up the same error.

Can you please help me out by providing an alternative or best solution to fix this.

Thanks,
Jaya Sai Sontineni
Holo Pundits | Systems Analyst
+1 8166168778  | www.holopundits.com<http://www.holopundits.com/>
*** HoloPundits is a Global Technology Company Specializing in developing AR, MR, and VR Applications***


[Logo]
ISO 9001:2015 & ISO 27001:2013 Certified Company

[mixed-reality_badge_side-by-side_blk-blu]
CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by jdeckerms** [comment]
@JayaSaiSontineni Sorry that I wasn't clear. Let's say you have two devices and two licenses for upgrade.

1. Create provisioning package #1, selecting one of the license files, and configuring all other settings that you want.
2. Start creating provisioning package #2 by choosing "Advanced provisioning". Enter a name for the project, click Next. Select "Windows 10 Holographic", click Next. On the "Import a provisioning package", select provisioning package #1. That will bring in all of the settings that you configured already. All you have to do then is replace the license file and then build the package.

-or-

You can create both packages using the wizard and selecting separate license files in each one.

**Comment by JayaSaiSontineni** [comment]
Hi Jennie,

I have followed the same steps you have suggested.

But, I got stucked up at attaching the package. Once I connect the Hololens device to PC using USB, I have copied .ppkg to Hololens internal storage and selected the button “Yes, Add it” on trust confirmation window  in Hololens device. After that, It is popping up an Provisioning error mentioning “Installation of provisional package failed. Please work with the package author to diagnose the problem”.

Can you please provide some solution on how to eradicate this error.

Thanks,
Jaya Sai Sontineni
Holo Pundits | Systems Analyst
+1 8166168778  | www.holopundits.com<http://www.holopundits.com/>
*** HoloPundits is a Global Technology Company Specializing in developing AR, MR, and VR Applications***


[Logo]
ISO 9001:2015 & ISO 27001:2013 Certified Company

[mixed-reality_badge_side-by-side_blk-blu]
CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by jdeckerms** [comment]
@JayaSaiSontineni I'm sorry, you'll need to work with Microsoft Support for troubleshooting your specific problem (https://support.microsoft.com/en-us/contactus/).

**Comment by scottcher** [comment]
1) I've been told that a single license file can be used for multiple devices (by the Microsoft person that responded to my ticket asking for the licensing file).  Can we get some verification here that this is actually the case?

2) I have been able to successfully deployed the license to upgrade to Business but I don't seem to see any indication that it was successfully implemented by the device.  Are there telltale signs that your device has been upgraded once the provisioning profile with the license file has been successfully deployed to the device?

Thank you

S-
