### ISSUE TITLE
1803 File Explorer is reset

### ISSUE THREAD

**Issue by kaweizz** [MicrosoftDocs/windows-itpro-docs#1249]
1709 File Explorer is normal，but 1803 File Explorer ico  is reset

1803 An error occurred, I mean File Explorer was configured, but File Explorer was reset and the location was moved to the front.

https://docs.microsoft.com/en-us/windows/configuration/configure-windows-10-taskbar

<?xml version="1.0" encoding="utf-8"?>
<LayoutModificationTemplate
    xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification"
    xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout"
    xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout"
    xmlns:taskbar="http://schemas.microsoft.com/Start/2014/TaskbarLayout"
    Version="1">
  <CustomTaskbarLayoutCollection>
    <defaultlayout:TaskbarLayout>
      <taskbar:TaskbarPinList>
        <taskbar:UWA AppUserModelID="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge" />
        <taskbar:DesktopApp DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\System Tools\File Explorer.lnk" />
      </taskbar:TaskbarPinList>
    </defaultlayout:TaskbarLayout>
 </CustomTaskbarLayoutCollection>
</LayoutModificationTemplate>

**Comment by jdeckerms** [comment]
@kaweizz I'm sorry, I don't understand exactly what problem you're seeing, could you give me more details?

**Comment by andreabichsel** [comment]
Closing for now until more details are provided.
