### ISSUE TITLE
How do I map this onto ConfigMgr implementation?

### ISSUE THREAD

**Issue by TechsUK** [MicrosoftDocs/windows-itpro-docs#1250]
When I implemented WDAG in group policy (using these docs) it worked like a dream, and I pulled the policy easily too. I setup via ConfigMgr and it hasn't worked right at all. Can ConfigMgr team do more detailed (including troubleshooting) rather than reference these docs that discuss group policy? It's clearly working differently.
I have tried wdagtool cleanup to reset my pc, but ConfigMgr is doing
could you add log file information regarding where ConfigMgr is recording what it is doing and applying policy? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfb9445a-681d-24b6-5241-4ebe311f5236
* Version Independent ID: aea60f74-212c-e24e-f164-28a555bc1727
* Content: [Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview.md)
* Product: **w10**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by eross-msft** [comment]
@andreabichsel  I'm no longer on this team, I believe someone else has taken over these articles. I've sent an email to @Justinha so he can either forward this issue or work on it himself.

**Comment by Justinha** [comment]
@TechsUK sorry for delay here. I don't see how to redirect your comment, so you might submit this feedback at the SCCM topic too: https://docs.microsoft.com/en-us/sccm/protect/deploy-use/create-deploy-application-guard-policy 

If you are still having trouble, here are other options:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
