### ISSUE TITLE
Incorrect Method

### ISSUE THREAD

**Issue by gsterk** [MicrosoftDocs/windows-itpro-docs#1252]
It would appear that this should actually be a DELETE method for reclaiming the licenses. The POST method is for assignment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4f5cf37-dc4b-149f-9e4d-40c07c230372
* Version Independent ID: fe9bdb3b-daf3-a3ad-b52b-85d283abca66
* Content: [Reclaim seat from user](https://docs.microsoft.com/en-us/windows/client-management/mdm/reclaim-seat-from-user)
* Content Source: [windows/client-management/mdm/reclaim-seat-from-user.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/reclaim-seat-from-user.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by illfated** [comment]
@gsterk : Thank you for reporting the issue. As you can see, it has now been rectified and the correct method is now visible on the docs.microsoft.com page.

**Comment by mypil** [comment]
@gsterk - Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
