### ISSUE TITLE
sdbinst command line doc missing parameters

### ISSUE THREAD

**Issue by deanwiles** [MicrosoftDocs/windows-itpro-docs#1259]
Running sdbinst /? reveals command line options that are missing from this documentation, including how to install an sdb file.

Usage: sdbinst [-?] [-q] [-u] [-g] [-p] [-n[:WIN32|WIN64]] myfile.sdb | {guid} | "name"

    -? - print this help text.
    -p - Allow SDBs containing patches.
    -q - Quiet mode: prompts are auto-accepted.
    -u - Uninstall.
    -g {guid} - GUID of file (uninstall only).
    -n "name" - Internal name of file (uninstall only).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fbb518-8e51-2225-b29d-4b3197a82d1d
* Version Independent ID: 2db08278-bc5a-4120-83d0-1cd56bb4aff5
* Content: [Using the Sdbinst.exe Command-Line Tool (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/planning/using-the-sdbinstexe-command-line-tool#command-line-options-for-deploying-customized-database-files)
* Content Source: [windows/deployment/planning/using-the-sdbinstexe-command-line-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/using-the-sdbinstexe-command-line-tool.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@deanwiles - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by greg-lindsay** [comment]
You're right there is an option that isn't displayed, but it is not how you would install an sdb file.  To install an sdb file you don't need to supply any options. The -q option is used however quite often so that prompts are suppressed.  The option that isn't listed here (-p) is rarely used, but it should be included for completeness.

**Comment by mypil** [comment]
@deanwiles - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by deanwiles** [comment]
The docs still do not match the command line usage shown when you run sdbinst /?, and they still do not describe how to install an sdb file.

**Comment by illfated** [comment]
May I suggest a PR (I can provide it) to add the output of the command the way it looks on a Windows Server 2016 (Standard)?
The way the output looks on my workplace server is like this:
(This command needs to run in an elevated command prompt, "Run as Administrator".)
```
Microsoft Windows [Version 10.0.17763.437]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>Sdbinst.exe /?
Usage: Sdbinst.exe [-?] [-q] [-u] [-g] [-p] [-n[:WIN32|WIN64]] myfile.sdb | {guid} | "name"

    -? - print this help text.
    -p - Allow SDBs containing patches.
    -q - Quiet mode: prompts are auto-accepted.
    -u - Uninstall.
    -g {guid} - GUID of file (uninstall only).
    -n "name" - Internal name of file (uninstall only).

C:\WINDOWS\system32>_
```
Maybe you can add what we need to have showing as an example of a useful command with the arguments?

**Comment by deanwiles** [comment]
Unfortunately, I don't have the time or resources to reverse-engineer sdbinst to make the documentation match its behavior. I did figure out that the way to install a file is simply "sdbinst <filepath>", but that is not covered in the documentation. Also, the command line syntax in the doc does not match the usage output, specifically -u and -n options.

**Comment by illfated** [comment]
OK, fair enough. I never expected anyone to reverse engineer the software in question to suggest improvements in the documentation. It is enough to suggest that only the command itself is enough (or that a file name can be specified).

I also tried to visualize if the command line example should be placed before or after the options, but I presume it will be OK to do it the same way as any other command with example is described.

**Comment by illfated** [comment]
For what it's worth: this is the output in Windows 10, using an elevated CMD window:
```
Microsoft Windows [Version 10.0.17763.437]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>Sdbinst.exe /?
Usage: Sdbinst.exe [-?] [-q] [-u] [-g] [-p] [-n[:WIN32|WIN64]] myfile.sdb | {guid} | "name"

    -? - print this help text.
    -p - Allow SDBs containing patches.
    -q - Quiet mode: prompts are auto-accepted.
    -u - Uninstall.
    -g {guid} - GUID of file (uninstall only).
    -n "name" - Internal name of file (uninstall only).

C:\WINDOWS\system32>_
```

**Comment by illfated** [comment]
Updated my comment https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1259#issuecomment-484176197 to show the actual output on a Windows Server 2016 (instead of the duplicated Windows 10 output).

**Comment by mypil** [comment]
@officedocsbot reopen

**Comment by greg-lindsay** [comment]
Hi Dean,
I don't have time to spend making updates to this page that require more changes in the future, so if there is a second update (we already added the -q option) please specificy exactly what is needed. I'll try to make that change and then we can close the issue again.

**Comment by mypil** [comment]
@deanwiles - From our understanding, the issue you raised has been answered by greg-lindsay. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by illfated** [comment]
@greg-lindsay Thank you for merging my suggested change.

@deanwiles : I hope the latest update will improve the doc from your perspective as well.

**Comment by mypil** [comment]
@officedocsbot close
