### ISSUE TITLE
Documentation inaccurate for Windows 10 Compatibility Administrator

### ISSUE THREAD

**Issue by deanwiles** [MicrosoftDocs/windows-itpro-docs#1260]
This documentation lists fixes (e.g. 8And16BitDXMaxWinMode) that are not available in the Windows 10 Compatibility Administrator; it is also missing documentation for some fixes (e.g. NoPaddedBorder) that do exist in the ACT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49489bee-b836-fa70-2278-03291a468c54
* Version Independent ID: 51f8425c-dc7a-5828-1df0-0116e30b1de6
* Content: [Compatibility Fixes for Windows 10, Windows 8, Windows 7, and Windows Vista (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/planning/compatibility-fixes-for-windows-8-windows-7-and-windows-vista#compatibility-modes)
* Content Source: [windows/deployment/planning/compatibility-fixes-for-windows-8-windows-7-and-windows-vista.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/compatibility-fixes-for-windows-8-windows-7-and-windows-vista.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
Hello @deanwiles Thank you for your feedback. Can you please share more details related to the error codes are mentioning above so that we can update the document accordingly. 

Thanks.

**Comment by mypil** [comment]
@deanwiles - We would like to follow up. Can you please respond to the query of joinimran? 

Thank you.

**Comment by mypil** [comment]
@deanwiles - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
