### ISSUE TITLE
VPN

### ISSUE THREAD

**Issue by DavidMarra** [MicrosoftDocs/windows-itpro-docs#1265]
Nothing here on VPN configuration...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d158d37-53b7-86dc-d6da-5c0d48862ead
* Version Independent ID: d886f240-d7b0-d458-dc44-6ed70193ca5b
* Content: [HoloLens in the enterprise requirements and FAQ (HoloLens)](https://docs.microsoft.com/en-us/hololens/hololens-requirements)
* Content Source: [devices/hololens/hololens-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/hololens/hololens-requirements.md)
* Product: **hololens**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@DavidMarra What specific information are you looking for?

**Comment by andreabichsel** [comment]
Closing for now. Will reopen if requested information is provided.
