### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by wow-6432** [MicrosoftDocs/windows-itpro-docs#1267]
Links to http://technet.microsoft.com/library/jj603116.aspx (TPM / PowerShell) are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805915dd-11ed-01bb-47b8-7cd715275703
* Version Independent ID: 5542a776-c895-b09b-d3eb-54cd8307b202
* Content: [View status, clear, or troubleshoot the TPM (Windows 10)](https://docs.microsoft.com/en-us/windows/security/hardware-protection/tpm/initialize-and-configure-ownership-of-the-tpm#feedback)
* Content Source: [windows/security/hardware-protection/tpm/initialize-and-configure-ownership-of-the-tpm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/hardware-protection/tpm/initialize-and-configure-ownership-of-the-tpm.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by lizap** [comment]
Yep, the correct link is https://docs.microsoft.com/en-us/powershell/module/trustedplatformmodule/?view=win10-ps. We'll get that updated.

**Comment by Justinha** [comment]
@wow-6432 Thanks for reporting this. The links are working again.
