### ISSUE TITLE
Missing option

### ISSUE THREAD

**Issue by shayan-seyedi** [MicrosoftDocs/windows-itpro-docs#1273]
I don't see "Onboard Configuration Package" in my panel. is it missing from my panel or it has been changed?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc98378-18c5-81bf-769e-d76d26852c91
* Version Independent ID: dd542381-071b-e583-f082-976e8fd91019
* Content: [Onboard Windows 10 machines using Mobile Device Management tools](https://docs.microsoft.com/en-gb/windows/security/threat-protection/windows-defender-atp/configure-endpoints-mdm-windows-defender-advanced-threat-protection#onboard-windows-10-machines-using-microsoft-intune)
* Content Source: [windows/security/threat-protection/windows-defender-atp/configure-endpoints-mdm-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/configure-endpoints-mdm-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by quilnux** [comment]
Hey Shayan-seyedi,

I had the same issue as you. Been trying to figure it out the last 2 days. Well, I found it!

Go into Intune (Be sure your using the Azure Portal not the classic portal) and go to "Device Compliance" Near the button of the menu on that blade you should see a section called "setup" and under that is "Windows Defender ATP". The first option, "Connect windows devices ** to Windows Defender ATP" turn that on. Then save. You should see "Connection status" at the top go green with "Enabled". That should get everything moving. It did take 6 hours for all the devices in my Azure AD to appear in my ATP list so give it a few.


I hope this helps!

**Comment by quilnux** [comment]
EDIT: Near the *bottom* of the menu on that blade you should see a section called "setup" and under that is "Windows Defender ATP".

**Comment by BigIve** [comment]
Have enabled that and see Defender ATP showing with a connection status as enabled.  But when used with a compliance and conditional access policy the PC is always showing as non compliant because ATP isn't installed locally.  Yet the PC shows in the Security Center portal and is reporting happily and all the manual checks show ATP is working.
It seems like the compliance and conditional access policies don't recognize this new ATP configuration.

**Comment by mjcaparas** [comment]
Thank you for your feedback. 
Checking with team to help clarify. For now see if this topic helps: https://docs.microsoft.com/en-us/intune/advanced-threat-protection
