### ISSUE TITLE
Guidance on transitioning from Windows 10 Enterprise KMS/MAK installations to Windows 10 E3 CSP

### ISSUE THREAD

**Issue by mtwelve** [MicrosoftDocs/windows-itpro-docs#1275]
Is there any guidance on transitioning from Windows 10 Enterprise KMS/MAK installations to Windows 10 E3 CSP?

We can check whether there is an embedded firmware key but if the device is already running Windows 10 Enterprise would it even check/activate with the CSP license?

Would the devices need to be rebuilt on Windows 10 Pro?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ecbc1-9c02-5681-7214-356be22ac7e8
* Version Independent ID: 73af82f6-079b-6c37-55c4-cb59e921457a
* Content: [Deploy Windows 10 Enterprise licenses](https://docs.microsoft.com/en-us/windows/deployment/deploy-enterprise-licenses)
* Content Source: [windows/deployment/deploy-enterprise-licenses.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-enterprise-licenses.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mtwelve** [comment]
Hello,

Can anyone advice on the above? If devices are already deployed using an Enterprise image from VLSC do the steps detailed in this article apply? Do the devices have to be reset to commercial/retail Windows 10 Pro?

**Comment by shawnmhart** [comment]
We also have the same question.  devices with a an embedded firmware key convert just fine, but ones that do not have a firmware key do not.  How has anyone gotten around this issue?

**Comment by cconrado** [comment]
Second this

**Comment by Kazzan** [comment]
The same question right now here.

**Comment by Martony78** [comment]
Same question

**Comment by Kazzan** [comment]
Just find out, that activating OEM key normally with standard activation tool works. If you have the sticker with original key.

**Comment by Martony78** [comment]
Unfortunately there is no such sticker on those laptops, I presume Dell had to change the motherboard and their technician did not reconfigured the new one properly...

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mtwelve** [comment]
Any updates on this...?

**Comment by MaratMussabekov** [comment]
Dear @mtwelve ,
**Is there any guidance on transitioning from Windows 10 Enterprise KMS/MAK installations to Windows 10 E3 CSP?** - please check [this article](https://docs.microsoft.com/windows/deployment/windows-10-enterprise-subscription-activation)

**We can check whether there is an embedded firmware key but if the device is already running Windows 10 Enterprise would it even check/activate with the CSP license?** -yes

**Would the devices need to be rebuilt on Windows 10 Pro?** - no, as it stated in the article above: "Product key-based Windows 10 Enterprise software licenses can be transitioned to Windows 10 Enterprise subscriptions"

Thank you

**Comment by mypil** [comment]
@mtwelve - Thank you for submitting this feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
