### ISSUE TITLE
Remove offline apps

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/windows-itpro-docs#1277]
Is there a way to remove offline apps from appearing in the Microsoft store? For example, we had an admin accidentally add an offline version of a Store app in our tenant, and now we can't remove it from appearing in Intune, making it difficult for Intune admins to know which version of the app to deploy. Even if we could remove it from Intune (which we can't), it would still sync from here into Intune again. There has to be a way to remove it from the company's inventory, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1a3b64b-ac3b-cc1c-ca70-ddc0eb486d71
* Version Independent ID: 182c6f9c-fa3f-b99e-fa4a-7ccc3db7551d
* Content: [App inventory management for Microsoft Store for Business and Microsoft Store for Education (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/app-inventory-management-microsoft-store-for-business)
* Content Source: [store-for-business/app-inventory-management-microsoft-store-for-business.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/app-inventory-management-microsoft-store-for-business.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by DanielNTX** [comment]
Yes you have to go into Order History and refund the purchase of the App.

**Comment by thedrum808** [comment]
Thanks Daniel. That did it!

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@thedrum808 - From our understanding, the issue has been resolved by DanielNTX. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
