### ISSUE TITLE
Filename of the Start Menu Layout file

### ISSUE THREAD

**Issue by jbyway** [MicrosoftDocs/windows-itpro-docs#1278]
It's not exactly clear on the above guide but the StartLayout xml you choose MUST be named LayoutModification.xml otherwise it will not apply via a PPKG. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98a8c769-f53b-9982-715c-9a9c0e86913d
* Version Independent ID: 8480b8b3-8dd7-7422-27be-f5480014d1b5
* Content: [Start (Windows 10)](https://docs.microsoft.com/en-au/windows/configuration/wcd/wcd-start#feedback)
* Content Source: [windows/configuration/wcd/wcd-start.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/wcd/wcd-start.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@jbyway Thanks for the feedback, I'll adjust the language in the topic to make that clearer.
