### ISSUE TITLE
Event volume

### ISSUE THREAD

**Issue by dkbriley** [MicrosoftDocs/windows-itpro-docs#1282]
The introduction to the article states "Event volume: Low", but then later, it states multiple times that "This subcategory typically generates huge amount of ... events."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 986f0d28-6df3-f44c-b500-dd6fe4b65bc1
* Version Independent ID: bd1b7ab1-2dbc-7c85-57d9-0dca8572537c
* Content: [Audit Logoff (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-logoff)
* Content Source: [windows/security/threat-protection/auditing/audit-logoff.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/audit-logoff.md)
* Product: **w10**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by nenonix** [comment]
@dkbriley Point taken, thanks for helping to improve the documentation. I will post back here when we have finished making changes.

**Comment by nenonix** [comment]
@mypil This issue can be closed https://github.com/MicrosoftDocs/windows-itpro-docs/commit/e72fc555d62ed74f72dc5fbf5a3effce5a41ea06#diff-f69222beb14c8028db01965f5d33a800

**Comment by mypil** [comment]
@dkbriley - Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
