### ISSUE TITLE
Success

### ISSUE THREAD

**Issue by dkbriley** [MicrosoftDocs/windows-itpro-docs#1283]
The introductory text says "Success audits record successful attempts", but later, the article states "This subcategory doesn’t have Success events"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14b78c8d-9064-a39a-d75e-6a2201b85397
* Version Independent ID: 59662c79-4b42-cfa9-37bb-009749a901a8
* Content: [Audit Account Lockout (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-account-lockout)
* Content Source: [windows/security/threat-protection/auditing/audit-account-lockout.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/audit-account-lockout.md)
* Product: **w10**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

**Comment by clma91** [comment]
In addition, the default setting is defined as "Success" (Explain tab), whereby only "Failure" events are thrown as described (4625(F)).

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by nenonix** [comment]
@dkbriley Thanks for the feedback. Your point is valid and I will do my best to amend the content to make it more clear,

**Comment by mypil** [comment]
@dkbriley - Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
