### ISSUE TITLE
Set AllowDeviceNameInTelemetry with Intune

### ISSUE THREAD

**Issue by mtwelve** [MicrosoftDocs/windows-itpro-docs#1285]
Is there a way other than PowerShell to set the value for AllowDeviceNameInTelemetry to enabled using Intune?

It is listed in the DM Client CSP as an option - https://docs.microsoft.com/en-gb/windows/client-management/mdm/dmclient-csp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4273a259-c3c7-dca7-6353-954068d740a7
* Version Independent ID: 1084ea77-95c4-4e4a-da6c-f4d8668f9ebf
* Content: [Enrolling devices in Windows Analytics (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started)
* Content Source: [windows/deployment/update/windows-analytics-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-get-started.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by shortpatti** [comment]
@jaimeo, can you take a look at this one?

**Comment by Illnasty** [comment]
Same.  What is the CSP and the value so my device names are not "#"?

**Comment by okieselbach** [comment]
Policy CSP has an option to configure it but only starting with 1809 devices. When using Intune, 1803 devices must be configured by PowerShell script for example and with 1809 you can configure the CSP.
https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-system#system-allowdevicenameindiagnosticdata

./Vendor/MSFT/Policy/Config/System/AllowDeviceNameInDiagnosticData

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@mtwelve -  Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by okieselbach. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
