### ISSUE TITLE
InTune Profile Save Error

### ISSUE THREAD

**Issue by Niglb** [MicrosoftDocs/windows-itpro-docs#1288]
I've created one Autologin multi-app kiosk profile, but on attempting to save another I get an error 'The UserAccountsConfiguration field is required' from looking at the logs. I am setting an AutoLogin account as the option, but save attempts still fail. On rechecking my settings, the user account field is not configured. Is this a known issue? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78038d67-04a1-f4ae-6a69-98e157688a31
* Version Independent ID: c86b4460-e8be-8537-a6c8-3cb094ef14a3
* Content: [Create a Windows 10 kiosk that runs multiple apps (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps#config-for-autologon-account)
* Content Source: [windows/configuration/lock-down-windows-10-to-specific-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/lock-down-windows-10-to-specific-apps.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@Niglb Intune Support should be able to help figure out the issue. Here are instructions for getting help with Intune: https://docs.microsoft.com/en-us/intune/get-support

**Comment by Niglb** [comment]
So I have to upgrade my subscription to submit an intune ticket. ...

**Comment by jdeckerms** [comment]
@Niglb You can post about your problem in the Intune forum: https://social.technet.microsoft.com/Forums/en-US/home?category=microsoftintune&filter=alltypes&sort=lastpostdesc

**Comment by Niglb** [comment]
ok thank you I've done so.
