### ISSUE TITLE
No devices in Update Compliance

### ISSUE THREAD

**Issue by rasldasl** [MicrosoftDocs/windows-itpro-docs#1289]
Device Health and Upgrade Readiness are populated. What troubleshooting steps should be taken? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5549abd-da28-5d11-49c6-e66ecf5cd0b6
* Version Independent ID: 0ad6a1a2-5c75-baeb-00de-a6649592ec69
* Content: [Get started with Update Compliance (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-get-started)
* Content Source: [windows/deployment/update/update-compliance-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/update-compliance-get-started.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Without more information, it's hard to advise in detail. Many common questions and troubleshooting steps are offered, however, in this topic: https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-faq-troubleshooting . Perhaps the "devices not showing up" section addresses your situation?

**Comment by rasldasl** [comment]
The devices are in the other two tools. What would specifically prevent them from showing up in Update Compliance?

Sent from my iPhone

On Jul 17, 2018, at 11:13 AM, jaimeo <notifications@github.com<mailto:notifications@github.com>> wrote:


Without more information, it's hard to advise in detail. Many common questions and troubleshooting steps are offered, however, in this topic: https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-faq-troubleshooting . Perhaps the "devices not showing up" section addresses your situation?

**Comment by jaimeo** [comment]
Are you saying you had the other solutions installed (and showing devices), and _then_ added the Update Compliance solution, but they're not in that solution? If so, how long since you added Update Compliance? OR, did you add all 3 solutions at the same time and the devices show up in two of them but not the third?

Have you tried the steps in https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-faq-troubleshooting#devices-not-showing-up ? That will generate detailed logs which will aid in diagnosis.

**Comment by cinglis-msft** [comment]
Are you subscribed to Update Compliance? When using the OMS portal, go to the gear icon in the upper-right corner, select Connected Sources, Windows Telemetry. Is Update Compliance subscribed?

**Comment by rasldasl** [comment]
Yes, all 3 subscribed. Just in case I unsubscribed Update Complicance, waited for the page to refresh, then clicked Subcribe again.

Commercial ID is 4927ca76-28fb-455a-804b-27578ca7aac5

Commercial ID Key
Regenerate
Solution
Upgrade Readiness

Unsubscribe

Device Health

Unsubscribe

Update Compliance

Unsubscribe


________________________________

**Comment by lizap** [comment]
(Deleted previous comment to make sure commercial ID protected)

**Comment by rasldasl** [comment]
All 3 were subscribed but only 3 populating. Unsubscribe then Subscribe again (on Update Compliance) seems to have done the trick.
