### ISSUE TITLE
Is the certutil command for the WHFBAuthentication tempate correct?

### ISSUE THREAD

**Issue by TrixM** [MicrosoftDocs/windows-itpro-docs#1290]
I'm attempting to run 'certutil -dsTemplate WHFBAuthentication msPKI-Private-Key-Flag +CTPRIVATEKEY_FLAG_HELLO_LOGON_KEY' on my Windows Server 2012 R2 CA and it is not executing correctly. It's repeating the help text as if there is a syntax error. Template name is definitely correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b063e00b-84e5-9da7-2229-e0e24da3b877
* Version Independent ID: da9f4867-2aa3-aefa-1603-ddb2ab1ed624
* Content: [Prepare and Deploy Windows Server 2016 Active Directory Federation Services (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by MikeBazMSFT** [comment]
I just went through this at a customer.  It's not necessarily stated clearly enough, but you run this from the AD FS 4.0 (2016) server, not the CA.

**Comment by MikeStephens-MS** [comment]
Added "Sign-in to an AD FS Windows Server 2016 computer with Enterprise Admin equivalent credentials." under section Mark the template as the Windows Hello Sign-in template
