### ISSUE TITLE
AllowStandardUserEncryption

### ISSUE THREAD

**Issue by okieselbach** [MicrosoftDocs/windows-itpro-docs#1291]
Hi,
please add to AllowStandardUserEncryption the supportability table. Currently it's a bit unclear from which version and SKU it's supported. Yes it's shown in the diagram above but I think it should also be available as a table.
best,
Oliver

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a05802f-9d0f-9aeb-3c8e-8b92f1284202
* Version Independent ID: 1fd9efc2-8946-75e4-27f3-95ac43a9d987
* Content: [BitLocker CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp)
* Content Source: [windows/client-management/mdm/bitlocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/bitlocker-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by krishnam7990** [comment]
Hello, Quick question. 

Document is stating "Starting in Windows 10, version 1809, it is also supported in Windows 10 Pro" but in the most of the policies under the title are stating the policies are not applicable in Windows 10 Pro. This is confusing. 

Does any of these policies can be applied to Windows 10 Pro devices? - Please help. Thanks.

**Comment by damigs** [comment]
Also agree.   Seems like being on Win10 Pro that some policies are not applicable.  One for instance is the 'Warning for other disk encryption’ setting in CSP.  Having the value disabled still prompts the standard user the message (still yields the warning message).

**Comment by bruun963** [comment]
Agree, the AllowWarningForOtherDiskEncryption doesn't apply to Windows 10 Pro, therefore the encryption won't automatically start under a standard user account.

**Comment by SoccerCore11** [comment]
Could we please get an official response on these questions?

**Comment by e0i** [comment]
@MariciaAlforque Can you suggest a way to move forward? We would like to follow up with this issue. Thanks.

**Comment by buhibu9** [comment]
It is important to be able to easily find out the corresponding platform version of each item.
This improvement is requested because the description "[AllowStandardUserEncryption] Added in Windows 10, version 1809" can not be searched for keywords because it is displayed as an image.

**Comment by illfated** [comment]
@e0i , I have not seen any replies from @MariciaAlforque this year. Easier to get feedback from @lomayor / @Dansimp in this case, seeing as they are listed as author/manager for this document, as well as noticing more involvement from their side.

**Comment by wbach82** [comment]
Did anything changed? My Win1809 Enterprise devices report that "AllowStandardUserEncryption" is "not aplicable"

**Comment by gutjahr** [comment]
I am seeing the same for both 1809 and 1903. All of a sudden, "Allow standard users to enable encryption during Azure AD Join" is showing as "Not applicable" in the detailed report of a device in the portal!

**Comment by e0i** [comment]
@lomayor Would you be able to advise with this issue? Thanks.

**Comment by ManikaDhiman** [comment]
Hi @e0i, I've reached out to the product team to provide inputs. I will update the doc as soon as I receive their inputs. Thanks!

**Comment by ManikaDhiman** [comment]
Hi @e0i, The BitLocker CSP topic has been updated with the SKU support table for AllowStandardUserEncryption.

Regarding the "not applicable" message, the product team would like to know on which report you see those settings as “not applicable” ? Can you provide the screenshot?

Thanks!

**Comment by illfated** [comment]
@wbach82 & @gutjahr : Are you able to respond to the question above, maybe provide a screenshot of the error message with its nearby environment details?

**Comment by e0i** [comment]
Closing via Manika's response,

> Hi @e0i, The BitLocker CSP topic has been updated with the SKU support table for AllowStandardUserEncryption.
> 

Regarding the "not applicable" message, please feel free to follow up with relevant screenshots for clarification.

Thank you.
