### ISSUE TITLE
 MSfB and MSfE do not support Subscriptions

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/windows-itpro-docs#1293]
The docs state that the MSfB and MSfE support Subscriptions:
"Microsoft Store for Business – Apps and subscriptions
Microsoft Store for Education – Apps and subscriptions"

While the Consumer Store support subscriptions, these organizational Stores do not support purchasing subscriptions or any other add-on through an organizational identity. The docs should not indicate that these Stores support subscriptions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeb9333f-07c0-9a51-93ee-90e1ebcaa52b
* Version Independent ID: 732c5d3c-bb82-7cf1-ce37-ea169f036051
* Content: [Microsoft Store for Business and Microsoft Store for Education overview (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/microsoft-store-for-business-overview)
* Content Source: [store-for-business/microsoft-store-for-business-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/microsoft-store-for-business-overview.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@mjfusa - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
