### ISSUE TITLE
Servicing Stack Updates - Clarity with CU

### ISSUE THREAD

**Issue by pchatham** [MicrosoftDocs/windows-itpro-docs#1295]
Can we have clarity on if SSU's are then combined into a Cumulative Update and the reasons why, if not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b706f0af-d504-a8ca-7c38-b8bb9283bfad
* Version Independent ID: 14f31acf-9f47-59a6-269f-62ab249fe560
* Content: [Servicing stack updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates#why-should-servicing-stack-updates-be-installed-and-kept-up-to-date)
* Content Source: [windows/deployment/update/servicing-stack-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/servicing-stack-updates.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by shortpatti** [comment]
@jaimeo, can you take a look at this one?

**Comment by jgledhill79** [comment]
We missed this update as part of our patching regime, because it isn't classified as "Critical" or "Important" so it failed to deploy as part of our automated patching. I would argue that as a pre-requisite for monthly cumulative updates, it is a fairly critical update??!! Spent half a day figuring out why our estate wasn't picking up the July W10 CUs :(

**Comment by jgledhill79** [comment]
KB4132216 for clarity!

**Comment by mnimocks** [comment]
Although the Servicing Stack Updates (SSU) are cumulative themselves, they are not part of the Operating System cumulative monthly patching for a good reason. The Servicing Stack needs to be serviced/updated separately from the OS, as it is the engine that performs the servicing for the OS. Another way of saying this is you cannot service the engine (Servicing Stack) that services the OS while it is servicing the OS (Applying cumulative updates). A bad analogy might be stating we can't change the fan belt or oil in a car while the engine is running. Another might be similar to flashing a BIOS. You'll need a reboot at some point to complete the process so the BIOS is not in use when certain aspects of the update take place. Frustrating on some level, but Servicing Stack Updates are historically rare outside of the recent rash seen in March, April, and May of 2018. If anything I think it has brought the important aspect of the Servicing Stack to light and educated more as to its purpose, importance, and relevancy when it comes to servicing and related issues. I'm certain the brains are working on getting SSU to be part of a Monthly Patching release, and it might be as cool as hot swapping usb attached devices. Remember when we were unable to do that?

**Comment by arkiados** [comment]
Hello, 
My organization has the same concern. We deployed security updates not knowing the servicing stack was a prerequisite. It doesn't sound like much of an issue but with a large global organization there is a lot of business process work done before a deployment. It would be wonderful if servicing stack and dependent update definitions could be updated to reflect this. We have an MS case open which I will send you.

Thanks

**Comment by BritV8** [comment]
Microsoft have recently changed how the servicing stack is categorised 
Future SSU releases, from October 2018 onward, will get marked "security" and "critical," https://redmondmag.com/articles/2018/09/21/windows-servicing-stack-updates.aspx

**Comment by BritV8** [comment]
Some people were only applying Security patches and not applying Critical patches
Unfortunately a number of security patches rely on the SSU being up to date, so patches were failing
Consequently, future SSU releases, from October 2018 onward, will get marked "security" 
http://britv8.com/october-servicing-stack-update-changes-in-classification/

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
@pchatham Thank you for your query on the doc. Please note the SSU's are not included in CU as SSU's are the updates that will update the Windows update service. CU's are handled by Windows update service and Windows update service got the update from SSU. So it is highly recommended that you should 1st update SSU and then run CU. This all information is also mentioned in the doc. 

Thanks.

**Comment by mypil** [comment]
@pchatham - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
