### ISSUE TITLE
Unclear how multifactor works

### ISSUE THREAD

**Issue by JonZeolla** [MicrosoftDocs/windows-itpro-docs#1297]
It is unclear how remote logins to an Azure AD-joined PC work when your account has multifactor enabled/enforced for AAD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc#feedback)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@JonZeolla Good question! The expert that I need to ask is on vacation, so I won't have an answer for you until after Aug 6.

**Comment by jdeckerms** [comment]
@JonZeolla I'll still check to see if there's any special consideration for MFA, but this topic isn't for your situation -- it's for connecting from a Win 10 device to a Win 10 device.  These docs might be more helpful: https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac

**Comment by JonZeolla** [comment]
Thanks @jdeckerms - yeah I reviewed the doc you linked to before opening this issue as well.  Primarily what I'm asking is how a destination AAD-joined Windows 10 box is expecting to authenticate a user (after the network connectivity/client setup was verified as correct, and I wouldn't expect it matters too much whether it's macOS, Windows, etc.) when the creds are AAD w/ MFA.  

I felt it made more sense to reach out on the article that more specifically discusses Azure AD as it would be more likely that I reach the right contact at Microsoft, but feel free to redirect me if you feel it's appropriate.

**Comment by jdeckerms** [comment]
@JonZeolla Thanks for clarifying. Expect to hear back from me in August. :)

**Comment by jdeckerms** [comment]
@JonZeolla I'm discussing your question with the product team, they'd like to know (1) what steps you followed to enable/enforce MFA, (2) which multi-factors you enabled.

**Comment by JonZeolla** [comment]
We have O365 and setup MFA via the "manage multi-factor authentication" link under an individual's account by setting the MULTI-FACTOR AUTH STATUS to Enforced.

**Comment by JonZeolla** [comment]
@jdeckerms any update on this?  Do you need more information from me?

**Comment by jdeckerms** [comment]
@JonZeolla I don't have any answer from the product team yet, sorry.

**Comment by ManfredH83** [comment]
@jdeckerms hello, is there maybe an update regarding MFA and RDP login? I'm currently facing the same problem.

**Comment by knutale** [comment]
@jdeckerms Hi, I'm currently also facing the same issues with MFA and RDP login. Is there a solution available in the meantime?

**Comment by mypil** [comment]
@jdeckerms - Do you have any updates on this. Thanks.

**Comment by Xmas13** [comment]
@jdeckerms Do you have any update on this? Thanks.

**Comment by mypil** [comment]
@jdeckerms - We would like to follow up. Do you have any updates on this? Thanks.

**Comment by kierenj** [comment]
@jdeckerms - have just set up a fresh Win 10 Pro using an Azure AD account with MFA enforced. Can't remote desktop to it with that same account.  As above can you or anyone advise?

**Comment by mypil** [comment]
@jdeckerms - We would like to follow up. Do you have any updates on this? Thanks.

**Comment by kierenj** [comment]
@jdeckerms please?

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by tp-seiso** [comment]
@jvsam This issue appears to persist. Please provide any available update at your earliest convenience.

**Comment by hanchoi** [comment]
Still no update on this issue?

**Comment by JonathanBasys** [comment]
@jdeckerms retired from Microsoft, as is visible on her github profile page. @JonZeolla have you found more info yet? Hope to hear!

**Comment by JonZeolla** [comment]
No update from me, still waiting on @microsoft

**Comment by joinimran** [comment]
Hello @JonZeolla - I would suggest you and others facing this issue to open up a support case with Microsoft. @nam31 - Can you please guide the user how to open up a support case with Microsoft. 

Opening a support case will help you to route to a correct team and will help you to fix this issue.

Thanks
Imran.

**Comment by nam31** [comment]
@JonZeolla Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)

Thank you.

**Comment by JonZeolla** [comment]
I opened this ticket with the hopes that the documentation would add a clarification with regard to multifactor use; it may be that it's not supported, etc.
