### ISSUE TITLE
BOZO

### ISSUE THREAD

**Issue by mikesharq** [MicrosoftDocs/windows-itpro-docs#1298]
Won't install update Windows 10 Insider Preview 10.0.17692.1004 (RS_PRERELEASE_FLT) on Surface Studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd88f752-60aa-95df-a7b3-ce3056e64a20
* Version Independent ID: aaf24bdd-548e-8049-8bbb-4911c23999a7
* Content: [Resolve Windows 10 upgrade errors - Windows IT Pro](https://docs.microsoft.com/en-us/windows/deployment/upgrade/resolve-windows-10-upgrade-errors#feedback)
* Content Source: [windows/deployment/upgrade/resolve-windows-10-upgrade-errors.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/resolve-windows-10-upgrade-errors.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by greg-lindsay** [comment]
Apologies for taking so long to see this. I'm afraid that the insider preview version is very far out of date now so the issue isn't worth documenting - however we would likely not update problems installing insider versions anyway as these are transient.
