### ISSUE TITLE
Taskbar customize xml does not work on 1803

### ISSUE THREAD

**Issue by terencengan** [MicrosoftDocs/windows-itpro-docs#1299]
This to confirm that the taskbar customization xml does not work on Windows 10 1803, The same xml file is working fine on 1709.
On the xml file, we use PinListPlacement="Replace" to remove remove default pinned app, it will only remove the Mail app, Edge, File Explorer and Store will remain there and the custom pin app like IE, File Explorer does not show up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140f038c-e307-78f0-5165-309e0cf34ca5
* Version Independent ID: b1011259-ee05-21a4-5308-aabc8b0dd74b
* Content: [Configure Windows 10 taskbar (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/configure-windows-10-taskbar#feedback)
* Content Source: [windows/configuration/configure-windows-10-taskbar.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/configure-windows-10-taskbar.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@terencengan I'm checking with the product team to see if there are any known issues or differences between 1709 and 1803, I'll let you know what I find out.

**Comment by hoyty76** [comment]
Did you try using DesktopApplicationID= instead of DesktopApplicationLinkPath= wonder if that is required now?

**Comment by kaweizz** [comment]
Taskbar only   UWA AppUserModelID  & DesktopApp DesktopApplicationLinkPath  

DesktopApplicationID  = Start layout

**Comment by hnewmanca** [comment]
Confirmed. This XML code worked on 1703, sort of works on 1803 but Edge gets left behind. Any ideas?
    <CustomTaskbarLayoutCollection PinListPlacement="Replace">
      <defaultlayout:TaskbarLayout>
        <taskbar:TaskbarPinList>
        <taskbar:DesktopApp DesktopApplicationLinkPath="#leaveempty"/>
		</taskbar:TaskbarPinList>
      </defaultlayout:TaskbarLayout>
    </CustomTaskbarLayoutCollection>

**Comment by pugmohone** [comment]
I just deployed this using SCCM and had zero issues with 1803.  I used the following code to display File Explorer, Google Chrome, and Snipping Tool

Can you copy your Taskbar section so we can take a look?

<CustomTaskbarLayoutCollection PinListPlacement="Replace">
      <defaultlayout:TaskbarLayout>
        <taskbar:TaskbarPinList>
          <taskbar:DesktopApp DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\System Tools\File Explorer.lnk" />
          <taskbar:DesktopApp DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Accessories\Snipping Tool.lnk" />
          <taskbar:DesktopApp DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk" />
        </taskbar:TaskbarPinList>
      </defaultlayout:TaskbarLayout>

I should note that I am in the beginning stages of building my Windows 10 Task sequence/ image and I have not removed any Windows 10 Apps yet and it still worked like a charm.

**Comment by pugmohone** [comment]
<CustomTaskbarLayoutCollection PinListPlacement="Replace">
      <defaultlayout:TaskbarLayout>
        <taskbar:TaskbarPinList>
          <taskbar:DesktopApp DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\System Tools\File Explorer.lnk" />
          <taskbar:DesktopApp DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Accessories\Snipping Tool.lnk" />
          <taskbar:DesktopApp DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk" />
        </taskbar:TaskbarPinList>
      </defaultlayout:TaskbarLayout>

**Comment by pugmohone** [comment]
Hmm - Cannot post my code.

**Comment by pugmohone** [comment]
CustomTaskbarLayoutCollection PinListPlacement="Replace"
      defaultlayout:TaskbarLayout
        taskbar:TaskbarPinList
          taskbar:DesktopApp DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\System Tools\File Explorer.lnk" /
          taskbar:DesktopApp DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Accessories\Snipping Tool.lnk" /
          taskbar:DesktopApp DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk" /
        /taskbar:TaskbarPinList
      /defaultlayout:TaskbarLayout

**Comment by pugmohone** [comment]
Removed the <>

**Comment by illfated** [comment]
If you want to post code containing special code and tags, use MarkDown:
https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code
Example: `This is a sample code text showing <tag> brackets as in <html>.`

**Comment by Shachar2like** [comment]
open the xml with a browser, if you get an error or the xml doesn't display in the browser you have an issue with the xml file. if this is the case make sure you copy the start of the file as well (the first few lines that define the xml. I missed that and had issues with it not applying)

**Comment by naplee** [comment]
I wanted to customize my TASKBAR on a new SERVER 2019 image (and not having to customize my START MENU) , so this was the code I used to get me quickly to the goal:

a) Used the two default START MENU items, but rest were  SYSTEM32 references (I didnt want to have to pin new items to START; I just used the defaults)

b) the logoff.exe.lnk (shortcut), was added, so that I could select my preferred DISPLAY ICON

c) set GPO  -- https://www.urtech.ca/2017/04/solved-customize-windows-10-start-menu-taskbar-using-a-gpo-in-6-easy-steps/
                         - To customize the Start Menu: section  #4,5,6

d) LOGoff and LOGin

e) VIOLA - it works as expected !

NOTE: after using XML approach to customize TASKBAR, the ability to Pin to START, seems broken to me.


Other helpful REFs:
============

http://www.scconfigmgr.com/2016/08/03/customize-pinned-items-on-taskbar-in-windows-10-1607-during-osd-with-configmgr/
https://www.makeuseof.com/tag/windows-10-taskbar-customization/
  - Pin Programs & (a specific) Folder

========================================
XML code:  I removed all <  and > , per comment above

 ?xml version="1.0" encoding="utf-8"? 
 LayoutModificationTemplate
    xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification"
    xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout"
    xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout"
    xmlns:taskbar="http://schemas.microsoft.com/Start/2014/TaskbarLayout"
    Version="1" 
   CustomTaskbarLayoutCollection PinListPlacement="Replace" 
     defaultlayout:TaskbarLayout 
       taskbar:TaskbarPinList 

         taskbar:DesktopApp DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\System Tools\File Explorer.lnk" / 

         taskbar:DesktopApp DesktopApplicationLinkPath="%WINDIR%\System32\cmd.exe" /  

         taskbar:DesktopApp DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\System Tools\Task Manager.lnk" / 
 
         taskbar:DesktopApp DesktopApplicationLinkPath="%WINDIR%\System32\diskmgmt.msc" /  

         taskbar:DesktopApp DesktopApplicationLinkPath="C:\TASKBAR\logoff.exe.lnk" /  


       /taskbar:TaskbarPinList 
     /defaultlayout:TaskbarLayout 
   /CustomTaskbarLayoutCollection 
 /LayoutModificationTemplate

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by nam31** [comment]
@terencengan Please let us know if you still have any question regarding the issue you have raised initially.
