### ISSUE TITLE
Apparent bad reference for registry value in document

### ISSUE THREAD

**Issue by bdonms** [MicrosoftDocs/windows-itpro-docs#1303]
https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization refers to configuring the registry value:

HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\DataCollection:AllowTelemetry

I tested this with a newly deployed Azure VM. From the Group Policy Management Console, I went to Computer Configuration > Administrative Templates > Windows Components > Data Collection and Preview Builds, changed the value, and found no change in above-mentioned registry setting. Instead, this setting changed:

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DataCollection:AllowTelemetry

This is the setting CIS specifies, and it works. Is the Microsoft document incorrect?

**Comment by shortpatti** [comment]
@Justinha and @DaniHalfin, can either one of you take a look at this one?

**Comment by mypil** [comment]
@bdonms - Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
