### ISSUE TITLE
Preview build 

### ISSUE THREAD

**Issue by spallison** [MicrosoftDocs/windows-itpro-docs#1307]
Preview build 17718? do you mean 17713?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce750351-c450-13d2-db04-3df88a4f4a9c
* Version Independent ID: de9bf9a8-c50f-52ef-6d92-e0ad69d4450e
* Content: [New Microsoft Edge Group Policies and MDM settings](https://docs.microsoft.com/en-us/microsoft-edge/deploy/new-policies)
* Content Source: [browsers/edge/new-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/new-policies.md)
* Product: **edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
Hi @spallison, the preview build number has been updated to 17713+and will appear in the documentation later this afternoon.

**Comment by spallison** [comment]
+1
