### ISSUE TITLE
In the "sideloading apps in windows 10" page, the steps for importing security certificates seem switched between the managed and unmanaged devices.

### ISSUE THREAD

**Issue by KevinKennedy** [MicrosoftDocs/windows-itpro-docs#131]
In: windows-itpro-docs/windows/deploy/sideload-apps-in-windows-10.md

The content for these sections seems switched:

To import the security certificate for managed devices
    Open the security certificate for the appx package, and select Install Certificate.
    On the Certificate Import Wizard, select Local Machine.
    Import the certificate to the Trusted Root Certification Authorities folder.
To import the security certificate for unmanaged devices
   You can use a runtime provisioning package to import a security certificate. For information about applying a provisioning package to a Windows 10 mobile device, see runtime instructions on Build and apply a provisioning package.

**Comment by TrudyHa** [comment]
Thanks for the feedback. I'll verify and update the topic.

**Comment by brianlic-msft** [comment]
@TrudyHa Was the topic updated? Can I close this issue?
