### ISSUE TITLE
Azure Active Directory part is not accurate

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/windows-itpro-docs#1312]
This documentation redirect us to the "O365 URLs and IP address ranges" page, containing dozen of URLs. I am sure we don't have to open all those URLs in order to make Windows Autopilot work but how do we know which ones? This document really needs to be more precise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aafc065-6ee6-e3cf-31ba-ab3dd277fb23
* Version Independent ID: 35d3102e-4ff7-9408-8dbd-513b7dfff5c0
* Content: [Windows Autopilot networking requirements](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-requirements-network)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-requirements-network.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-autopilot-requirements-network.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by greg-lindsay** [comment]
I think you are referring to the link that refers to a support article at https://support.office.com/en-us/article/Office-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2

The referral provided "As part of the Intune device configuration, installation of Office 365 ProPlus may be required."

I agree there are a lot of links on that page, but the page itself is precise. There is just a lot of information there because there are a lot of required URLs.

**Comment by Martony78** [comment]
Hi Greg,
Thank you for your reply but I still don't agree, the page itself is not precise when it comes to Azure AD registration. Indeed, it is mark as optional but it mandatory for Autopilot, and furthermore there is a bunch of FQDNs having nothing to do with Azure, how are we suppose to know those we need open?
The table has no separation between the below components so we have to figure out by ourself, some are obvious but some are not:
Graph.windows.net
Office 365 Management Pack for Operations Manager
SecureScore
Azure AD Device Registration
Forms
StaffHub
Application Insights
captcha services

 *.blob.core.windows.net
*.hockeyapp.net
*.sharepointonline.com
*.staffhub.office.com
api.office.com
enterpriseregistration.windows.net
dc.applicationinsights.microsoft.com
dc.services.visualstudio.com
forms.microsoft.com
forms.office.com
graph.windows.net
manage.office.com
mem.gfx.ms
office365servicehealthcommunications.cloudapp.net
securescore.office.com
signup.microsoft.com
staffhub.ms
staffhubweb.azureedge.net
staffhub.office.com
staffhub.uservoice.com
weu-000.forms.osi.office.net
wus-000.forms.osi.office.net
neu-000.forms.osi.office.net
eus2-000.forms.osi.office.net
ea-000.forms.osi.office.net
watson.telemetry.microsoft.com
wu.client.hip.live.com
