### ISSUE TITLE
Easy transfer wizard is not available in Windows 10

### ISSUE THREAD

**Issue by nclinch** [MicrosoftDocs/windows-itpro-docs#1313]
Easy transfer wizard is not available in Windows 10. This should be noted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8513655-c946-4a74-34ec-5c639b4021cc
* Version Independent ID: cd27cf77-45ab-95a0-f1e5-8549661f0740
* Content: [Windows Upgrade and Migration Considerations (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-upgrade-and-migration-considerations)
* Content Source: [windows/deployment/upgrade/windows-upgrade-and-migration-considerations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/windows-upgrade-and-migration-considerations.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@nclinch - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
