### ISSUE TITLE
Additional event ID 162

### ISSUE THREAD

**Issue by frobnitzz** [MicrosoftDocs/windows-itpro-docs#1320]
Hi,

I have an 1803 build which is showing an event not listed above, 162. The description is similar to 163, but instead of "device is already provisioned" it reads "device is not provisioned".

“AutoPilotManager determined download is not required and the device is not provisioned. Clean or reset the device to change this.” 

Thanks,
John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adcfcc02-d931-66e3-6f4f-c14b936358e6
* Version Independent ID: 8972647b-ba21-b68f-b698-5fb6e9e9f1fd
* Content: [Troubleshooting Windows Autopilot](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/troubleshooting)
* Content Source: [windows/deployment/windows-autopilot/troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/troubleshooting.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by frobnitzz** [comment]
Hi, why has this been closed? Thanks.

**Comment by shortpatti** [comment]
Hi @frobnitzz, the document has been completely rewritten.  If you still require an answer, I'll have the assigned author take another look.
