### ISSUE TITLE
Defender ATP File Extensions

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#1321]
[Enter feedback here]

The documentation mentions **file** and **attachment** extension names. 

- File extension names - Suspicious files except email attachments will be submitted for additional inspection
- Attachment extension names - Suspicious email attachments with these extension names will be submitted for additional inspection

However within the Defender ATP Portal 
https://securitycenter.windows.com/preferences2/advanced - Automation Uploads the help text is as following:

> 

Suspicious files, **except** e-mail attachments with these extension names will be submitted for additional inspection 

> 

I am a bit confused now whether e-mail attachments with these defined extensions are being submitted or not. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f49941fe-1ecf-d3ac-a9a4-36dd5b41788f
* Version Independent ID: 02698d5d-7606-1edf-9af8-35f626a8880c
* Content: [Manage automation file uploads](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/manage-automation-file-uploads-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/manage-automation-file-uploads-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/manage-automation-file-uploads-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Thank you for your feedback.

Topic has been updated to remove the Attachment extension names field.
