### ISSUE TITLE
"Privilaged Credentials" - Windows Hello works for "Run as Administrator" but not "run as different user"

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/windows-itpro-docs#1322]
After enabling the "Allow enumeration of smart card for all users" GPO setting, I have confirmed that I can use windows hello to authenticate as an administrator when using "run as administrator" or otherwise prompted for admin credentials.  However, when using "Run as different user" the dialog box that appears is simpler, with only 2 text boxes to enter a username and password.  This dialog does not have a 'more choices' option, nor any way to select biometric or pin authentication.  

You might want to verify that this is supposed to / actually does work with the "run as different user" option, and remove that from the documentation if it does not.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a146880-235b-a69c-3e9d-a3fa56a25389
* Version Independent ID: c2c226b4-17ef-8888-9e1b-e20cf3273c3a
* Content: [Windows Hello for Business Features](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-features#privileged-credentials)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-features.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by kjarrard** [comment]
I've been working towards WHfB for my Admin group in particular so this support is pretty important to us.  Should have last pre-req taken care of this weekend (CA upgrade/migrate).  Is there currently a way to work around this 'run as a different user' issue?

**Comment by MikeStephens-MS** [comment]
I'll need to look back at our testing to confirm.  Is there a reason why run as administrator is not sufficient for your scenario?  Have you tried runas.exe as provided in the docs.  We'll update after research.

**Comment by egallagh** [comment]
@MikeStephens-MS I can quickly think of a scenario where I would be logged into a management workstation with a non-privileged (domain) user account. I then need to run-as with a domain account that has some level of elevated privilege on a server but does not have domain admin or local admin privilege on the local machine.

**Comment by kjarrard** [comment]
Exactly the scenario egallagh layed out.  Very typical scenario.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by TimTheITGuy** [comment]
It appears that I am still unable to use Windows Hello for Run as a Different User. (Windows 1903)
Disappointing because I frequently need to execute tasks on a computer as myself without disconnecting the user who is currently on the system. For example, accessing utilities or editing files on the IT share.

**Comment by joinimran** [comment]
Hello @NeighborGeek - Did you get a chance to setup Dual Enrollment for Windows Hello. See how to implement dual enrollment here at https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-dual-enrollment

Thanks.
Imran.

**Comment by nam31** [comment]
@NeighborGeek The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
