### ISSUE TITLE
Whiteboard app

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/windows-itpro-docs#1326]
Any chance of adding the Whiteboard app into the "recommended apps" list? Seems like it might be appropriate now that it's in GA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ed0150-0172-f3ad-3c7f-3a7141efbe64
* Version Independent ID: 6a978d2b-a0ff-1052-ce00-06f02f30cfa1
* Content: [List of enlightened Microsoft apps for use with Windows Information Protection (WIP) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by thedrum808** [comment]
Nevermind - marking it as "Exempt" works, as it doesn't really access files on your PC, so it wouldn't need to be WIP-aware.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@thedrum808 - Thank you for submitting feedback. 

Based on your last comment, it appears that the issue you have has been fixed. Can we proceed to close this issue or is there anything in the article that you suggest to be edited? Please advise.

**Comment by mypil** [comment]
@officedocsbot close
