### ISSUE TITLE
More guidance on choosing certificate vs key trust - Advantages/disadvantages of each?

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/windows-itpro-docs#1331]
From the article, I understand that Key trust model requires at least some Server 2016 DC's, while Certificate trust does not.  I also understand from other articles that certificate trust is more complicated to deploy, requiring NDES among other things.  Beyond that, are there any advantages to one trust type over the other?  

Please add some guidance to help admins decide which deployment type is best for their environment, beyond just the initial requirements & deployment differences.  Explain what (if any) benefits there are to one deployment type over the other.  If there is no difference in capabilities and no reason to choose one type over the other once the feature has been deployed, say so explicitly.  

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3b8524-491d-7f49-0445-a34ed47d504c
* Version Independent ID: 1106b56a-45f9-9465-7c7c-2fa9a68ca807
* Content: [Windows Hello for Business Deployment Guide](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-guide)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-deployment-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-deployment-guide.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by MikeStephens-MS** [comment]
FIXED
There are a couple places that helps explain this.  We added this to our FAQ.  There is also a terms section coming in the how it works section that goes over key trust, cert trust and the trust types. It should be visible with our next update coming out very soon. 

Thank you for the feedback

Mike

**Comment by andrewwillett** [comment]
Can you show where the disadvantages of the Certificate Trust model are listed?
