### ISSUE TITLE
Please include in the documentaion about Domain Joind Machines Behaviour

### ISSUE THREAD

**Issue by vibeeshan025** [MicrosoftDocs/windows-itpro-docs#1332]
Please mention the following details in the docuemnt.
- Any fresh install of Windows 10 Creators updater higher will not support sync functionality of its under an Active Directory (but works for Azure AD).

https://www.itwire.com/the-wired-cio/79531-microsoft-breaks-windows-10-microsoft-account-sync-for-corporates.html 

![image](https://user-images.githubusercontent.com/10608733/43152297-d9716586-8f8b-11e8-90a0-9eb2ddc0f83f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce750351-c450-13d2-db04-3df88a4f4a9c
* Version Independent ID: de9bf9a8-c50f-52ef-6d92-e0ad69d4450e
* Content: [New Microsoft Edge Group Policies and MDM settings](https://docs.microsoft.com/en-us/microsoft-edge/deploy/new-policies)
* Content Source: [browsers/edge/new-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/new-policies.md)
* Product: **edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@vibeeshan025, thank you for the feedback and details to add to the content.  I added it to the FAQ.
