### ISSUE TITLE
Domain/ComputerName - Breaks AutoPilot

### ISSUE THREAD

**Issue by joaovitoriasilva** [MicrosoftDocs/windows-itpro-docs#1338]
A MDM policy was added to change the workstation name. To be more precise the policy added was this one: "./Device/Vendor/MSFT/Accounts/Domain/ComputerName" with the following String value "OS-%SERIAL%".

Then when the AutoPilot kicks in, I believe this policy makes the system to reboot and this breaks the process. A user named "defaultuser0" is created with an unknown password. When trying to log in with the Azure AD account, the AutoPilot process starts again and says that the device is already enrolled and cannot continue.

If I disable this policy, the AutoPilot runs with no problems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 309bae29-c769-5051-6c3f-aebeb455cd34
* Version Independent ID: bbdfad82-025e-8aee-b3fc-bcfb8b110674
* Content: [Accounts CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/accounts-csp)
* Content Source: [windows/client-management/mdm/accounts-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/accounts-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by xonaecom** [comment]
We were conducting more tests and the problem is only happening in build 17134.1. Windows 1709 and others Windows 1803 builds do not have this issue.

**Comment by dphuk** [comment]
Exactly the same issue on the same windows version, same renaming policy had been working perfection prior. Looking to deploy a new build on 1809 just now and will post the results back here.

**Comment by xonaecom** [comment]
Hello @dphuk ! I've doing some tests with 1809 build and I can confirm that it worked fine and as expected.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by nam31** [comment]
@joaovitoriasilva  Please let us know if you still have any question regarding the issue you have raised initially.
