### ISSUE TITLE
IOT

### ISSUE THREAD

**Issue by vartaxe** [MicrosoftDocs/windows-itpro-docs#1342]
What about Windows 10 IOT Enterprise LTSB (1607)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b48c394-863e-9a54-6d5b-5f31ff07849f
* Version Independent ID: f5ddf9f4-c449-360c-107e-582f7d9df7fd
* Content: [Windows 10 connection endpoints](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-endpoints#licensing)
* Content Source: [windows/privacy/manage-windows-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/manage-windows-endpoints.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by MoonGem** [comment]
A time limited URL huh?

**Comment by MoonGem** [comment]
He's probably looking for them because footprint.com isnt *.microsoft.com

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by joinimran** [comment]
Hello @vartaxe - Thank you for your query. Normally we only list the endpoints for the Enterprise version of Windows. If there you are looking for endpoints for IoT version of Windows please open up a support case with Microsoft where you will be provided with the required information. 

Thanks.

**Comment by nam31** [comment]
@vartaxe We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
