### ISSUE TITLE
Assign Importance broken?

### ISSUE THREAD

**Issue by partingtons** [MicrosoftDocs/windows-itpro-docs#1347]
Clicking Assign Importance is only displaying a blank page now? List and Table views are fine however but cannot modify importance in these views.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b1b04a5-df11-ec8c-d99c-d0a3e0de8672
* Version Independent ID: d570e4b2-8547-c7b1-9ab8-8e25022fa718
* Content: [Upgrade Readiness - Identify important apps (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-identify-apps)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-identify-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-identify-apps.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by PhillyUrbs** [comment]
This appears to be a larger issue affecting multiple environments.  I get a 500 internal server error when trying to load the "User Changes" view.  I'm sure the Microsoft team is aware of the issue and are working to address it.

**Comment by Voteax** [comment]
Is this fixed for anyone?
I cannot Assign any Importance. 
There is no Button for this.

**Comment by shortpatti** [comment]
@greg-lindsay, can you take a look at this issue?

**Comment by e0i** [comment]
@officedocsbot assign e0i

**Comment by e0i** [comment]
@greg-lindsay @jaimeo Any updates on this issue? We'd like to follow-up. Thanks.

**Comment by jaimeo** [comment]
@zdvorak can you advise?

**Comment by e0i** [comment]
@zdvorak Any updates with this issue?

**Comment by greg-lindsay** [comment]
Sorry for not seeing this issue for a long time. This issue was correctly routed to the product team but didn't get addressed. However Upgrade Readiness (and Device Health) are being retired on January 31, 2020 so there is no support to address this issue.
