### ISSUE TITLE
Event ID 171/172

### ISSUE THREAD

**Issue by thbch** [MicrosoftDocs/windows-itpro-docs#1348]
It's great to have this list with the codes. Now as 171 and 172 are errors and we have them on our machines, I'd like to know how we can solve these problems. Where do I find further information about these errors?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adcfcc02-d931-66e3-6f4f-c14b936358e6
* Version Independent ID: 8972647b-ba21-b68f-b698-5fb6e9e9f1fd
* Content: [Troubleshooting Windows Autopilot](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/troubleshooting)
* Content Source: [windows/deployment/windows-autopilot/troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/troubleshooting.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by aavdberg** [comment]
The page is updated with this information, so the issue can be closed it think.

**Comment by thbch** [comment]
Okay for me. Thank you.
