### ISSUE TITLE
Wrong tab

### ISSUE THREAD

**Issue by schnitz76** [MicrosoftDocs/windows-itpro-docs#1354]
7 should be `Cryptography` tab and not the `Request Handling` tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54caa849-b978-ca6c-c44f-dd043f25d1a2
* Version Independent ID: d7327f1d-f884-c2fd-b04d-d423142ee935
* Content: [Configure the Workstation Authentication Certificate Template (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/windows-firewall/configure-the-workstation-authentication-certificate-template)
* Content Source: [windows/security/identity-protection/windows-firewall/configure-the-workstation-authentication-certificate-template.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/windows-firewall/configure-the-workstation-authentication-certificate-template.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@schnitz76 Thanks, the topic has been corrected.
