### ISSUE TITLE
TPM 1.2 vs 2.0

### ISSUE THREAD

**Issue by Skorfulose** [MicrosoftDocs/windows-itpro-docs#1358]
The highlighted note says "The device must be running Windows 10 and it must support at least **TPM 2.0**."
The table of supported versions right below has a checkmark/cross on **both TPM 1.2 and TPM 2.0**.
So what is true now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 035a6270-8a60-2a3c-604f-506b58118b46
* Version Independent ID: 26a1102b-e201-42c2-212c-fd6726e2ca97
* Content: [Trusted Platform Module Technology Overview (Windows 10)](https://docs.microsoft.com/en-us/windows/security/hardware-protection/tpm/trusted-platform-module-overview#device-health-attestation)
* Content Source: [windows/security/hardware-protection/tpm/trusted-platform-module-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/hardware-protection/tpm/trusted-platform-module-overview.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by egallagh** [comment]
The highlighted note refers to TPM 2.0 or above as a requirement for the Device Health Attestation functionality.

**Comment by Skorfulose** [comment]
[Here](https://docs.microsoft.com/en-us/windows/security/threat-protection/protect-high-value-assets-by-controlling-the-health-of-windows-10-based-devices#a-href-idhardware-reqahardware-requirements) it says TPM 1.2 is supported for DHA since 1703. So my question remains: What is true now?

**Comment by egallagh** [comment]
Verifying...

**Comment by egallagh** [comment]
I have verified that 2.0 is required and has been since Windows 10 RS1. I have already clarified the documentation referenced in your first post and will follow up on the doc for your second post. Thank you for pointing this out.

**Comment by egallagh** [comment]
Hang on. Getting additional details and verifying...

**Comment by Skorfulose** [comment]
Hi Ed, I had an advisory case opened with our premier support in parallel. Check case 118073118689762. Feedback is: TPM1.2 and TPM 2.0 are supported for DHA in 1803. TPM 2.0 was ever since Win10 release. TPM1.2 support was added in some later release. TPM2.0 is recommended by MS though (no specific reasons given).
Advisory case answer is sufficient for me. Now if that was reflected in the docs I'd be totally happy...  😃 Thanks!

**Comment by egallagh** [comment]
Hello again. Yep. In my conversation with the product team members, TPM 1.2 was added in 1607. I've updated both docs you had links to. The updates have already been applied to the second one you mentioned. https://docs.microsoft.com/en-us/windows/security/threat-protection/protect-high-value-assets-by-controlling-the-health-of-windows-10-based-devices#a-href-idhardware-reqahardware-requirements

**Comment by egallagh** [comment]
BTW: TPM 2.0 (or later) is highly recommended because there were major security enhancements made to the design and implementation of TPM compared to 1.2. Other less important enhancements and broader industry support in 2.0 also.

**Comment by eldos-dl** [comment]
@egallagh Does the `X` mark in *Supported versions for device health attestation* mean that it is supported? Or does it mean its unsupported?

**Comment by egallagh** [comment]
X means it is supported. I will clarify that.

**Comment by egallagh** [comment]
Looks like this issue can be closed
