### ISSUE TITLE
Guest account

### ISSUE THREAD

**Issue by iWdGo** [MicrosoftDocs/windows-itpro-docs#1368]
The SID S-1-5-32-546 is referred as Guest account when it is the group of Guest accounts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74d32ee6-c7ff-9328-97d6-40ad82c73392
* Version Independent ID: 01f10cbb-4cae-077f-8245-7b0ada8305d7
* Content: [Local Accounts (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/local-accounts)
* Content Source: [windows/security/identity-protection/access-control/local-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/access-control/local-accounts.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@iWdGo Thanks for citing this. I made the correction.
