### ISSUE TITLE
 Proposal for URL link correction

### ISSUE THREAD

**Issue by cyblue9** [MicrosoftDocs/windows-itpro-docs#1369]
[フィードバックをこちらに入力してください]

In the Japanese page, the link URL of the "contribution guide" is "https://docs.microsoft.com/en-us/contribute/", but maybe it would be better for "https://docs.microsoft.com/ja-jp/contribute/"?
(I think that the link to ja-jp page is better than the link to en-us page.)

Probably the same phenomenon is occurring in pages of other languages.

It is a problem that the value of the loc variable property "disclaimer.machineTranslatedOnly" in the source of "https://docs.microsoft.com/_themes/docs.theme/master/ja-jp/_themes/global/js/4cf8db1.global.min.js" is "\<a href="https://docs.microsoft.com/en-us/contribute/">".

How about changing the value of "disclaimer.machineTranslatedOnly" depending on the language?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c34dbafa-df3c-a5a5-32d5-2ce152893534
* Version Independent ID: cebdd9a6-45d7-6306-373c-7d31121f9e16
* Content: [PIN がパスワードより安全な理由 (Windows 10)](https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by mypil** [comment]
@samanthaw @MollyMalone 

cc: @AndreaBarr

**Comment by DaniHalfin** [comment]
I believe this one should be closed for now.
Localized versions currently do not support contributions, therefore, the localized contribution guide isn't relevant. We'll see if we can remove it to avoid confusion.

**Comment by DaniHalfin** [comment]
@mypil

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.

**Comment by cyblue9** [comment]
Thank you.
