### ISSUE TITLE
About tuning Start Menu layout for user with mandatory user profile.

### ISSUE THREAD

**Issue by Yuri-01** [MicrosoftDocs/windows-itpro-docs#1371]
Hi.
Please explain, how can i tune and apply Start Menu Layout for user with mandatory user profile?

(i see, that start menu layout db settings located without roaming part user profile and i known, that mean applying to roaming user profile (by group policy) not work with mandatory user profile).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9ca7cb6-32cb-1517-a9de-c36046955d45
* Version Independent ID: 91041e39-007e-f481-0cd4-177b4039ae12
* Content: [Create mandatory user profiles (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/mandatory-user-profile#related-topics)
* Content Source: [windows/client-management/mandatory-user-profile.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mandatory-user-profile.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@Yuri-01 For instructions that combine Start layout and roaming mandatory user profile, please see https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-roaming-user-profiles

**Comment by Yuri-01** [comment]
Hi, @jdeckerms!

Thanks for your answer.
But, unfortunately this instraction (https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-roaming-user-profiles) not applying to user with MANDATORY profile.
(early i already try tuning start layout usage this approach)

---
Sorry, for my eng.lng.

**Comment by jdeckerms** [comment]
@Yuri-01 Actually you're correct -- per [https://docs.microsoft.com/en-us/windows/client-management/mandatory-user-profile#how-to-create-a-mandatory-user-profile](https://docs.microsoft.com/en-us/windows/client-management/mandatory-user-profile#how-to-create-a-mandatory-user-profile) you can't apply a Start and taskbar layout using a mandatory profile. Methods for applying a Start menu layout are [Group Policy](https://docs.microsoft.com/en-us/windows/configuration/customize-windows-10-start-screens-by-using-group-policy), [provisioning](https://docs.microsoft.com/en-us/windows/configuration/customize-windows-10-start-screens-by-using-provisioning-packages-and-icd), and [MDM](https://docs.microsoft.com/en-us/windows/configuration/customize-windows-10-start-screens-by-using-mobile-device-management).

**Comment by Yuri-01** [comment]
To @jdeckerms:
Thus, in Windows 10 no exist approaches for apply customization start layout for user with MANDATORY profile?

**Comment by antr67** [comment]
> To @jdeckerms:
> Thus, in Windows 10 no exist approaches for apply customization start layout for user with MANDATORY profile?

In my experience this seems to be the case - I have roaming profiles working acceptably with start menu and tiles but the minute you make a profile mandatory it all seems to fall apart. The amount of time I have wasted trying to get something that was trivial in Windows 7 working in Windows 10 is frightening. Please - if someone knows different - let us know,
