### ISSUE TITLE
Security Compliance via Intune at some point?

### ISSUE THREAD

**Issue by dcaddick** [MicrosoftDocs/windows-itpro-docs#1376]
Hi, unless I'm mistaken this is all based on GPO's? will there be something similar at some stage for Intune based policies?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 014ca19c-6ab8-6eec-321e-72fa22c8f2c3
* Version Independent ID: 948a95a8-cb4f-668a-1988-17830d51845b
* Content: [Microsoft Security Compliance Toolkit 1.0](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-compliance-toolkit-10)
* Content Source: [windows/security/threat-protection/security-compliance-toolkit-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-compliance-toolkit-10.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **sagaudre**

**Comment by Justinha** [comment]
@dcaddick You're right it's based on GPOs today. There is work in progress for Intune/MDM baselines, but no ETA to share at this point.
