### ISSUE TITLE
Error When importing

### ISSUE THREAD

**Issue by nathanallan-GeelongCollege** [MicrosoftDocs/windows-itpro-docs#1377]
Hi There,
I have been using these 2 commands for awhile and they work fine
Export-Startlayout –path C:\Temp\StartMenu.xml
Import-StartLayout –LayoutPath C:\Temp\StartMenu.xml -MountPath:C:\
I have changed the way we are using the StartMenu with stacked icons.
The export command works fine but the import command returns an error: Import-StartLayout : The file C:\temp\StartMenuLayout.xml is not a valid layout file.
This article doesn't mentioned that you cannot use stacked icons, is this an oversight, because this is a great feature and I'm sure other end users would follow. please contact me if you require more information.
Thanks

Nathan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79fccecd-5484-0304-d82b-9425f1889a22
* Version Independent ID: 4df6b138-c1b5-b551-22c9-19d3d1f9105d
* Content: [Customize and export Start layout (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/customize-and-export-start-layout#feedback)
* Content Source: [windows/configuration/customize-and-export-start-layout.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/customize-and-export-start-layout.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@nathanallan-geelongcollege What are "stacked icons"?

**Comment by nathanallan-GeelongCollege** [comment]
Hi Jeanie
When you move another icon on top of another icon you can stack them into a group/folder.
I have attached a screen shot.

Nathan

**Comment by jdeckerms** [comment]
@nathanallan-GeelongCollege What version of Windows 10 are you applying the Start layout to?

**Comment by nathanallan-GeelongCollege** [comment]
Hi Jennie
We are using version 1803 Enterprise
Thanks

**Comment by nathanallan-GeelongCollege** [comment]
Hi Jennie
Just wondering if you have any news as of yet?
Thanks


Nathan


From: Nathan Allan
Sent: Wednesday, 1 August 2018 8:12 AM
To: 'MicrosoftDocs/windows-itpro-docs' <reply@reply.github.com>
Subject: RE: [MicrosoftDocs/windows-itpro-docs] Error When importing (#1377)

Hi Jennie
We are using version 1803 Enterprise
Thanks

**Comment by jdeckerms** [comment]
@nathanallan-GeelongCollege Sorry, I don't have an answer yet but I'm still working on it.

**Comment by jdeckerms** [comment]
@nathanallan-GeelongCollege Did you name the folder of stacked icons in the XML?

**Comment by nathanallan-GeelongCollege** [comment]
Hi Jennie
Looks like I did not name the folder.
I have attached a copy on the startmenu export



Nathan

**Comment by jdeckerms** [comment]
@nathanallan-GeelongCollege  Nathan, I don't see an attachment, could you try again?

**Comment by nathanallan-GeelongCollege** [comment]
Hi Jennie
I have zipped the file and attached, if that has not worked here is the code for the file:



<LayoutModificationTemplate xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout" xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout" Version="1" xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification">
  <LayoutOptions StartTileGroupCellWidth="8" />
  <DefaultLayoutOverride>
    <StartLayoutCollection>
      <defaultlayout:StartLayout GroupCellWidth="8">
        <start:Group Name="">
          <start:DesktopApplicationTile Size="2x2" Column="2" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Accessories\Snipping Tool.lnk" />
          <start:Tile Size="4x2" Column="4" Row="0" AppUserModelID="Microsoft.BingWeather_8wekyb3d8bbwe!App" />
          <start:DesktopApplicationTile Size="2x2" Column="0" Row="0" DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\System Tools\computer.lnk" />
        </start:Group>
        <start:Group Name="">
          <start:Folder Size="2x2" Column="0" Row="0">
            <start:DesktopApplicationTile Size="2x2" Column="2" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\OneNote 2016.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="4" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\PowerPoint.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="2" Row="2" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Publisher.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="0" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Outlook.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="0" Row="2" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Word.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="4" Row="2" DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\OneDrive - Geelong College.lnk" />
          </start:Folder>
          <start:Folder Size="2x2" Column="2" Row="0">
            <start:DesktopApplicationTile Size="2x2" Column="0" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Accessories\Internet Explorer.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="2" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk" />
            <start:Tile Size="2x2" Column="4" Row="0" AppUserModelID="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge" />
            <start:DesktopApplicationTile Size="2x2" Column="6" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Firefox.lnk" />
          </start:Folder>
          <start:Folder Size="2x2" Column="4" Row="0">
            <start:DesktopApplicationTile Size="2x2" Column="2" Row="2" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe Acrobat DC.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="0" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe Premiere Pro CC 2018.lnk" />
            <start:Tile Size="2x2" Column="-1" Row="-1" AppUserModelID="Adobe.CC.XD_adky2gkssdxte!App" />
            <start:DesktopApplicationTile Size="2x2" Column="2" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe Photoshop CC 2018.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="6" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe Fireworks CS6.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="4" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe Illustrator CC 2018.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="0" Row="2" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe Captivate 9 (64 Bit).lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="4" Row="2" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe Animate CC 2018.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="6" Row="2" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe Lightroom Classic CC.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="-1" Row="-1" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe InDesign CC 2018.lnk" />
           <start:DesktopApplicationTile Size="2x2" Column="-1" Row="-1" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe InCopy CC 2018.lnk" />
          </start:Folder>
          <start:Folder Size="2x2" Column="6" Row="0">
            <start:Tile Size="2x2" Column="2" Row="0" AppUserModelID="Microsoft.Windows.Photos_8wekyb3d8bbwe!SecondaryEntry" />
            <start:Tile Size="2x2" Column="0" Row="0" AppUserModelID="Microsoft.WindowsCalculator_8wekyb3d8bbwe!App" />
            <start:Tile Size="2x2" Column="6" Row="2" AppUserModelID="Microsoft.MSPaint_8wekyb3d8bbwe!Microsoft.MSPaint" />
            <start:Tile Size="2x2" Column="4" Row="0" AppUserModelID="Microsoft.ZuneVideo_8wekyb3d8bbwe!Microsoft.ZuneVideo" />
            <start:Tile Size="2x2" Column="6" Row="0" AppUserModelID="Microsoft.WindowsCamera_8wekyb3d8bbwe!App" />
            <start:Tile Size="2x2" Column="2" Row="2" AppUserModelID="Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe!App" />
            <start:Tile Size="2x2" Column="0" Row="4" AppUserModelID="Microsoft.Windows.Photos_8wekyb3d8bbwe!App" />
            <start:Tile Size="2x2" Column="-1" Row="-1" AppUserModelID="microsoft.windowscommunicationsapps_8wekyb3d8bbwe!microsoft.windowslive.calendar" />
            <start:Tile Size="2x2" Column="4" Row="2" AppUserModelID="Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe!App" />
            <start:Tile Size="2x2" Column="-1" Row="-1" AppUserModelID="Microsoft.ZuneMusic_8wekyb3d8bbwe!Microsoft.ZuneMusic" />
            <start:Tile Size="2x2" Column="-1" Row="-1" AppUserModelID="microsoft.windowscommunicationsapps_8wekyb3d8bbwe!microsoft.windowslive.mail" />
            <start:Tile Size="2x2" Column="-1" Row="-1" AppUserModelID="Microsoft.WindowsMaps_8wekyb3d8bbwe!App" />
          </start:Folder>
        </start:Group>
      </defaultlayout:StartLayout>
    </StartLayoutCollection>
  </DefaultLayoutOverride>
</LayoutModificationTemplate>





[cid:logo4823.jpg]




Nathan Allan
IT Technical Systems & Support Officer


Phone: +613 5226 3150


PO Box 5, GEELONG VIC 3220


www.geelongcollege.vic.edu.au<http://www.geelongcollege.vic.edu.au/>

**Comment by jdeckerms** [comment]
@nathanallan-GeelongCollege Thanks, Nathan. I see two issues - one is StartTileGroupCellWidth being set to 8. If you look at the XML reference (https://docs.microsoft.com/en-us/windows/configuration/start-layout-xml-desktop), they're limited to 6 in the LayoutModification.xml. Also, a number of the tiles have a position of -1 for column and row -- I'm not sure how that happened in your export, but there isn't a -1 column or row in which to display the tile.

**Comment by nathanallan-GeelongCollege** [comment]
Hi Jeanie
So I have retried the setup/layout of the start menu on another laptop and the export and import process is now working fine.
Its still odd why the GroupCellWidth is still listing 8 when I have resized the menu to 4, I have attached a screen snip of the startmenu and below is the code of the xml.


<LayoutModificationTemplate xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout" xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout" Version="1" xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification">
  <LayoutOptions StartTileGroupCellWidth="8" />
  <DefaultLayoutOverride>
    <StartLayoutCollection>
      <defaultlayout:StartLayout GroupCellWidth="8">
        <start:Group Name="">
          <start:Folder Size="2x2" Column="2" Row="0">
            <start:Tile Size="2x2" Column="0" Row="2" AppUserModelID="Microsoft.WindowsCamera_8wekyb3d8bbwe!App" />
            <start:Tile Size="2x2" Column="2" Row="4" AppUserModelID="Microsoft.MSPaint_8wekyb3d8bbwe!Microsoft.MSPaint" />
            <start:Tile Size="2x2" Column="0" Row="4" AppUserModelID="Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe!App" />
            <start:Tile Size="2x2" Column="4" Row="4" AppUserModelID="Microsoft.Windows.Photos_8wekyb3d8bbwe!App" />
            <start:Tile Size="2x2" Column="4" Row="2" AppUserModelID="Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe!App" />
            <start:Tile Size="2x2" Column="0" Row="0" AppUserModelID="Microsoft.WindowsCalculator_8wekyb3d8bbwe!App" />
            <start:Tile Size="2x2" Column="2" Row="2" AppUserModelID="Microsoft.WindowsMaps_8wekyb3d8bbwe!App" />
            <start:Tile Size="2x2" Column="4" Row="0" AppUserModelID="Microsoft.ZuneVideo_8wekyb3d8bbwe!Microsoft.ZuneVideo" />
            <start:Tile Size="2x2" Column="2" Row="0" AppUserModelID="Microsoft.Windows.Photos_8wekyb3d8bbwe!SecondaryEntry" />
          </start:Folder>
          <start:Folder Size="2x2" Column="4" Row="0">
            <start:DesktopApplicationTile Size="2x2" Column="2" Row="2" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Publisher.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="0" Row="2" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Excel.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="6" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\PowerPoint.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="0" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Word.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="4" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\OneNote 2016.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="2" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Outlook.lnk" />
          </start:Folder>
          <start:Folder Size="2x2" Column="6" Row="0">
            <start:Tile Size="2x2" Column="0" Row="4" AppUserModelID="Adobe.CC.XD_adky2gkssdxte!App" />
            <start:DesktopApplicationTile Size="2x2" Column="4" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe Photoshop CC 2018.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="4" Row="2" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe After Effects CC 2018.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="6" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe Illustrator CC 2018.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="6" Row="2" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe Dreamweaver CC 2018.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="2" Row="2" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe InDesign CC 2018.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="0" Row="2" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe Acrobat DC.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="0" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe Creative Cloud.lnk" />
            <start:DesktopApplicationTile Size="2x2" Column="2" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Adobe Premiere Pro CC 2018.lnk" />
          </start:Folder>
          <start:DesktopApplicationTile Size="2x2" Column="0" Row="0" DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\System Tools\computer.lnk" />
        </start:Group>
        <start:Group Name="">
          <start:Tile Size="4x2" Column="0" Row="0" AppUserModelID="Microsoft.BingWeather_8wekyb3d8bbwe!App" />
          <start:Tile Size="2x2" Column="6" Row="0" AppUserModelID="microsoft.windowscommunicationsapps_8wekyb3d8bbwe!microsoft.windowslive.calendar" />
          <start:DesktopApplicationTile Size="2x2" Column="4" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Accessories\Snipping Tool.lnk" />
        </start:Group>
        <start:Group Name="">
          <start:DesktopApplicationTile Size="2x2" Column="6" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Firefox.lnk" />
          <start:DesktopApplicationTile Size="2x2" Column="2" Row="0" DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\Accessories\Internet Explorer.lnk" />
          <start:Tile Size="2x2" Column="0" Row="0" AppUserModelID="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge" />
          <start:DesktopApplicationTile Size="2x2" Column="4" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk" />
        </start:Group>
      </defaultlayout:StartLayout>
    </StartLayoutCollection>
  </DefaultLayoutOverride>
</LayoutModificationTemplate>

**Comment by jdeckerms** [comment]
@nathanallan-GeelongCollege Glad it's working now! I don't understand the width of 8 either, but if it's working now, obviously that wasn't the problem. It looks like getting rid of the -1 values helped.

**Comment by nathanallan-GeelongCollege** [comment]
Hi Jeanie
I know you closed the job, but I thought I would send this through.
Every now and then when you pin the icons, the icon will be placed very oddly I think that’s where the negative values are coming from.
I have attached a screen shot and the code is below.

Also I was wondering if you could point me the in correct direction with a SCCM question about activation the option “Show more tiles on Start” during a deployment sequence.
I have had no luck finding any information on this.
Thanks


<LayoutModificationTemplate xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout" xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout" Version="1" xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification">
  <LayoutOptions StartTileGroupCellWidth="6" />
  <DefaultLayoutOverride>
    <StartLayoutCollection>
      <defaultlayout:StartLayout GroupCellWidth="6">
        <start:Group Name="">
          <start:Folder Size="2x2" Column="2" Row="0">
            <start:Tile Size="2x2" Column="-1" Row="-1" AppUserModelID="Microsoft.ZuneVideo_8wekyb3d8bbwe!Microsoft.ZuneVideo" />
            <start:Tile Size="2x2" Column="2" Row="0" AppUserModelID="Microsoft.WindowsCamera_8wekyb3d8bbwe!App" />
            <start:Tile Size="2x2" Column="0" Row="0" AppUserModelID="Microsoft.WindowsCalculator_8wekyb3d8bbwe!App" />
          </start:Folder>
          <start:DesktopApplicationTile Size="2x2" Column="0" Row="0" DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\System Tools\computer.lnk" />
        </start:Group>
      </defaultlayout:StartLayout>
    </StartLayoutCollection>
  </DefaultLayoutOverride>
</LayoutModificationTemplate>






[cid:logo4823.jpg]




Nathan Allan
IT Technical Systems & Support Officer


Phone: +613 5226 3150


PO Box 5, GEELONG VIC 3220


www.geelongcollege.vic.edu.au<http://www.geelongcollege.vic.edu.au/>

**Comment by jdeckerms** [comment]
@nathanallan-GeelongCollege Sorry, I don't have any info on SCCM and didn't find anything specific to your question on search. You might try the IT Pro forum for Win10 deployment, others may have had a similar question or may have worked through it before: https://social.technet.microsoft.com/Forums/en-US/home?forum=win10itprosetup
