### ISSUE TITLE
Update for Version 2.22.139.0 version

### ISSUE THREAD

**Issue by Scottmca** [MicrosoftDocs/windows-itpro-docs#1380]
I can supply the text for that t.b.d section.  Bullets below

Increase Update reliability
Add support for Surface Go

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7b356e-3dbd-7f59-845e-a92e05865a52
* Version Independent ID: 711c5497-373f-662c-7fae-ba60f046e50c
* Content: [Microsoft Surface Dock Updater (Surface)](https://docs.microsoft.com/en-us/surface/surface-dock-updater)
* Content Source: [devices/surface/surface-dock-updater.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/surface-dock-updater.md)
* Product: **w10**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@Scottmca Thanks! I'll add those to the topic
