### ISSUE TITLE
Win10 activation was blocked by the Conditional access policies

### ISSUE THREAD

**Issue by JimmyLS110** [MicrosoftDocs/windows-itpro-docs#1384]
I have a customer who implemented Win10 subscription activation in his environment. However the devices will downgrade from ENT to PRO after 90 days when outside of corporate network. After troubleshooting we can confirm it was blocked by AAD CA policies (customer set block access outside of trusted IPs). And when devices were back to Corporate network they were activated again. 

From the whole document here, we cannot find any clues that CA policies will block win10 activation. It only says "Devices that have been upgraded will attempt to acquire licenses every 30 days, and must be connected to the Internet to be successful." 

May I know if indeed the Win10 Activation may be blocked by CA policies? If it is true, is there any way we can bypass the Activation service from CA evaluation? Thanks.

Jimmy Sun

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-subscription-activation)
* Content Source: [windows/deployment/windows-10-enterprise-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-enterprise-subscription-activation.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@greg-lindsay Could you clarify the relationship between CA policies and Windows 10 Enterprise versus Professional subscription upgrades?

We would like to folllow-up with this issue and provide relevant content updates if necessary.

Thanks.

**Comment by Kazzan** [comment]
Hi, do you use "All Apps" in CA?

**Comment by greg-lindsay** [comment]
Yes, CA will block activation if it blocks access to the Internet.
