### ISSUE TITLE
Apps "Full name" are wrong

### ISSUE THREAD

**Issue by oquno** [MicrosoftDocs/windows-itpro-docs#1385]
I found some apps' "Full name" are wrong.

✕Microsoft.Microsoft.Edge
○Microsoft.MicrosoftEdge

✕Microsoft.AAD.Broker.Plugin
○Microsoft.AAD.BrokerPlugin

Also, many apps' Full name includes space char like "Microsoft.Windows. Apprep.ChxApp" will not be correct strictly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce0131fb-6b3a-5905-1738-253cf37e3b2d
* Version Independent ID: cab448be-54ae-539e-22ba-3d202a468d4f
* Content: [Windows 10 - Apps](https://docs.microsoft.com/en-us/windows/application-management/apps-in-windows-10)
* Content Source: [windows/application-management/apps-in-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/apps-in-windows-10.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by Borkason** [comment]
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/1513 fixes this for provisioned app names

**Comment by oquno** [comment]
@shortpatti 

still not fixed for these problems

> ✕Microsoft.Microsoft.Edge
> ○Microsoft.MicrosoftEdge
> 
> ✕Microsoft.AAD.Broker.Plugin
> ○Microsoft.AAD.BrokerPlugin
