### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Lexy2** [MicrosoftDocs/windows-itpro-docs#1388]
It's "Hiberfil.sys", not "Hyberfil.sys"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99b874f5-7c0d-490f-f6d8-f8412743d329
* Version Independent ID: 5b6f9fa8-9762-f11c-296c-b7a89f58ef61
* Content: [Types of attacks for volume encryption keys (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/types-of-attacks-for-volume-encryption-keys)
* Content Source: [windows/security/information-protection/bitlocker/types-of-attacks-for-volume-encryption-keys.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/types-of-attacks-for-volume-encryption-keys.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by egallagh** [comment]
Thank you!
