### ISSUE TITLE
Set up School PC update

### ISSUE THREAD

**Issue by ramzavala** [MicrosoftDocs/windows-itpro-docs#1389]
Hello, i noticed some new steps where added to create the provisioning package. You now need to select the Windows 10 OS version and specify the time settings. I create the provisioning package but they now get stuck on Sway and Skydrive. I remember this was an issue in the past, any clue on how to bypass sway and skydrive?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2ca5807-f011-cdd1-eb80-c74655aa4738
* Version Independent ID: fe016307-69a4-ec63-4979-eac841d13c3c
* Content: [Use Set up School PCs app](https://docs.microsoft.com/en-us/education/windows/use-set-up-school-pcs-app)
* Content Source: [education/windows/use-set-up-school-pcs-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/use-set-up-school-pcs-app.md)
* Product: **w10**
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @ramzavala, thanks for reaching out. I'm checking in with the product team to get an answer for you. Look out for a message from me soon. Thanks!

**Comment by lenewsad** [comment]
Hi @ramzavala. Thanks for your patience. Yes, we did recently make some updates to the app and documentation. :) These new settings should not impact the apps you select. Unfortunately, there's no way to bypass those apps, unless you use Windows Configuration Designer (WCD) to create your package. When you run into this problem, are you able to still create the provisioning package successfully?

I recommend submitting feedback about the product experience here: https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app In the feedback, please share what OS version you select when you run into the problem. Also, elaborate on what you mean by "stuck on Sway and Skydrive."  If we see this problem reported repeatedly, I'll work with the product tream to create an appropriate recommendation/note in the docs.

**Comment by KeithMoonWestmount** [comment]
Each time I try and use this app, the default keyboard layout is English UK, is there an easy tool to edit the ppkg file or a way to override this?  thanks

**Comment by guttys** [comment]
Hi! We did the steps mentioned in the article, but the students PCs were without WIFI. Only FLYMODE as an option. Result- totally useless and we had to reset them again. What can be done?

**Comment by lenewsad** [comment]
Hi @guttys, thanks for your question! I forwarded this info to someone on our product team but need a little more info to figure out the best support route for you. First, during setup, did you choose the option to remove apps pre-installed by the device manufacturer?

**Comment by e0i** [comment]
Hello @ramzavala 

We are closing this issue since your questions seems to be partially answered and you have not followed-up with your second question.

Feel free to re-open this issue if you still experience difficulties.

Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by ScottStauffer** [comment]
I would like to add that there are some major issues here.  I've experienced the issues mentioned above,  but also, there are some major flaws that really bite the bottoms of our customers.  Yes, we have a large number fail on SkyDrive and occasionally on Yammer and it really is non-recoverable.  I have to do an OS install from USB to get the machine back to the OOBE.  And when sticking the Provisioning Package in, it does not do as instructions say, it does another complete Reset of the OS taking up 1 hour and 40 minutes!  this is incredibly inconvenient, unnecessary and makes people why they would use this App.  Plus the docs and blog post indicating the fact that you can import the Package into Windows Configuration Designer are now incorrect as it fail with errors when attempting to do so.  This product is tarnishing the EDU reputation.  I'd love to help bring forward some other roadblocks.  I WANT to use the Set up school PCs App, but can't use or recommend it in its current state.  I caution people against it at this point.  Also, it used to be able to add AutoPilot and that is no longer the case.  It also used to bundle the Office 365 ProPlus install on the USB to reduce the burden on the network and now it too is no longer available.  Talking with some of the Intune/SCCM/End Point Manager MVPs, they have some interesting insights too.  SUSPC has some good features, but some changes are REALLY needed to keep this a viable solution for Schools & School Districts.  Please feel free to reach out to me... I'd love to help.
