### ISSUE TITLE
KioskBrowser - Wildcards do not work in BlockedUrlExceptions and no way to specify list of urls in BlockedUrlExceptions 

### ISSUE THREAD

**Issue by DmytroKukharenko** [MicrosoftDocs/windows-itpro-docs#1390]
This is for KioskBrowser configured from Windows Configuration Designer at Policies -> KioskBrowser.
I declare default url, Blocked urls with wildcard * - block all.
When add host without anything - it works, but if I use wildcards for example *hostname* - doesn't work.
Why?
Also I can't add more than one host, I tried everything for separate hosts - . , ; | and space, even tried array ["hostname", "hostname"].
What I doing wrong?
Thank you.

**Comment by jdeckerms** [comment]
@DmytroKukharenko I just updated the content yesterday to explain the delimiter for multiple URLs, sorry that it wasn't there originally. Separate multiple URLs using **&#xF000;**

**Comment by DmytroKukharenko** [comment]
@jdeckerms Thanks for an update. I have tried that but unfortunately didn't work.

I tried hostname&#xF000;hostname as well as *hostname*&#xF000;*hostname*

Do you know what else I might to miss?

**Comment by jdeckerms** [comment]
@DmytroKukharenko Could you save the exact text you're entering in a text file and attach it here?

**Comment by DmytroKukharenko** [comment]
@jdeckerms text file is attached

[blockedurlsexeption.txt](https://github.com/MicrosoftDocs/windows-itpro-docs/files/2249761/blockedurlsexeption.txt)

**Comment by jdeckerms** [comment]
Did you try including .com with the hostname?

**Comment by DmytroKukharenko** [comment]
@jdeckerms  Same ;(

[blockedurlsexeption.txt](https://github.com/MicrosoftDocs/windows-itpro-docs/files/2249938/blockedurlsexeption.txt)

**Comment by jdeckerms** [comment]
I'll check with the app developers, maybe they'll see something I'm overlooking.

**Comment by jdeckerms** [comment]
@DmytroKukharenko Try this: 

1.	Create the ppkg. When ready to export, close the project in WCD.
2.	Open up the customizations.xml file in the project folder (e.g C:\Users\andyfu\Documents\Windows Imaging and Configuration Designer (WICD)\Project_18). 
3.	Insert the null character string in between each URL (e.g www.bing.com&#xF000;www.microsoft.com). 
4.	Save the XML file.
5.	Open the project again in WCD.
6.	Export the package. Ensure you do not revisit the created policies under Kiosk Browser or else the null character will be removed.

I'll update the topic with these steps today as well -- thanks for raising this issue!

**Comment by DmytroKukharenko** [comment]
@jdeckerms 

Thank you, it WORKS!!!

No problem, happy to help))
