### ISSUE TITLE
Surface Pro 3 updates?

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/windows-itpro-docs#1393]
Surface Pro, Pro 4 and 3 have gotten updates but not Pro 3? Any updates for it coming? Maybe some updated video drivers like 3?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586d1246-6e18-b33c-2382-52a53bb392f5
* Version Independent ID: 0ec4aa1e-aac0-98dd-0a47-83e93d854086
* Content: [Download the latest firmware and drivers for Surface devices (Surface)](https://docs.microsoft.com/en-us/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices)
* Content Source: [devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md)
* Product: **w10**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@hoyty76 Sorry, I don't have information on future plans for Surface. You could ask that team via Twitter: https://twitter.com/SurfaceSupport

**Comment by hoyty76** [comment]
That twitter account has been closed for almost a year. 😢 Check out the pinned tweet.

**Comment by jdeckerms** [comment]
Sorry, all I see on that page is "Only confirmed followers have access to @SurfaceSupport's Tweets and complete profile. Click the "Follow" button to send a follow request."
