### ISSUE TITLE
HoloLens Bitlocker Encryption Method

### ISSUE THREAD

**Issue by jjherman94** [MicrosoftDocs/windows-itpro-docs#1394]
The documentation on using Bitlocker with the HoloLens seems pretty vague. So for the HoloLens when enabling Bitlocker through provisioning packages, what encryption method is used? And is there any way to change the encryption method through either provisioning packages or MDM?
When the documentation says Bitlocker is silent on the HoloLens, what exactly does that mean? Are the files just decrypted when logging into the HoloLens?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f605e50-3184-f27d-36a8-b3cf608c6120
* Version Independent ID: d6bcd384-b494-43b3-e2e7-9ff46c6a513f
* Content: [Enable Bitlocker encryption for HoloLens (HoloLens)](https://docs.microsoft.com/en-us/hololens/hololens-encryption)
* Content Source: [devices/hololens/hololens-encryption.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/hololens/hololens-encryption.md)
* Product: **hololens**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@jjherman94 Correct, the setting is on or off.
