### ISSUE TITLE
Location field -- use is not well documented

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-itpro-docs#1398]
The use of Location information is not obvious.  If it is documented somewhere, please provide a link to that information in this (and other) pages. Is it  GUI-only information, i.e. it tells a user how to click-click-click his way to the appopriate input field/whatever?  Is it a path that can be used as a method in ... say, a WMI call or some other SDK call for programmatic access to relevant setting? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6aaa595-efab-ccfa-0c51-28673b499055
* Version Independent ID: 9a4746cc-aaed-32ca-5609-fc50fa03cfbf
* Content: [Enforce password history (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/enforce-password-history)
* Content Source: [windows/security/threat-protection/security-policy-settings/enforce-password-history.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/enforce-password-history.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@athulin What do you mean by Location information? How is it related to enforcing password history?

**Comment by e0i** [comment]
Closing the issue as the GitHub account of the person who had submitted this issue is no longer available and thus they cannot follow-up with the clarifying question.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
Looks like @officedocsbot can't make changes to issue tickets it has closed. Maybe it has not been programmed to deal with closed issues, or issues closed by itself?
