### ISSUE TITLE
You'll need to know the exact Linux distros and macOS X versions that are compatible with Windows Defender ATP for the integration to work

### ISSUE THREAD

**Issue by jonnyleigh** [MicrosoftDocs/windows-itpro-docs#1399]
I can't find anywhere the exact list of linux distros.  Can anyone help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f20412b-125c-3c56-7b31-32bcbaa1e098
* Version Independent ID: f7c3d311-eb14-da4b-9560-e01904fd7141
* Content: [Onboard non-Windows machines to the Windows Defender ATP service](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-endpoints-non-windows-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/configure-endpoints-non-windows-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/configure-endpoints-non-windows-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **justinha**

**Comment by mjcaparas** [comment]
Hi jonnyleigh, thank you for your feedback. You'll need to know the third-party integration that works with Windows Defender ATP. For example, Ziften integrates with Windows Defender ATP so that cyberthreats can be detected on macOS and Linux endpoints.
