### ISSUE TITLE
Credential Guard via Intune

### ISSUE THREAD

**Issue by tmguinn** [MicrosoftDocs/windows-itpro-docs#1400]
I think you should include Intune as a way to enable Credential Guard as well. You can enable Credential Guard easily with Intune via "Home-Microsoft Intune-Device configuration-Profiles-Create profile-Endpoint protection-Windows Defender Credential Guard". It will enable VBS and Secure Boot and you can do it with or without UEFI Lock.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by CanadianJeff** [comment]
I tried to start vmware workstation and it came up with an error to disable cred guard

Source: https://kb.vmware.com/s/article/2146361
Product: w10

**Comment by Justinha** [comment]
@CanadianJeff that could be by design. Even on Hyper-V, it only works with generation 2 VM: https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-requirements#requirements-for-running-windows-defender-credential-guard-in-hyper-v-virtual-machines

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by lindspea** [comment]
@tmguinn  @CanadianJeff @Justinha Please confirm if the above steps to include Intune should be added to the MS Doc and I will have it implemented soonest.

**Comment by Justinha** [comment]
@lindspea @tmguinn sorry to miss this. Yes, please add the Intune steps and we will review.

**Comment by lindspea** [comment]
Ok done. PR - https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3240
[image: Picture]

**Comment by e0i** [comment]
@tmguinn 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
