### ISSUE TITLE
Firewall Examples.

### ISSUE THREAD

**Issue by dfconroy** [MicrosoftDocs/windows-itpro-docs#1402]
Could someone provide some examples for the Firewall CSP?
E.G.
1. Block specific IP addresses.
2. Block all and Allow specific IP Addresses.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfea4e59-ec8c-cbdf-a039-23612c2266a5
* Version Independent ID: 7058544b-7ef2-a398-366a-cf71520aa9d8
* Content: [Firewall CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/firewall-csp)
* Content Source: [windows/client-management/mdm/firewall-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/firewall-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by nebulenz** [comment]
Some examples would be useful, we've had a go at configuring a bunch of custom rules and had no luck.

**Comment by tigeraaditya** [comment]
Hello! Please provide some examples of how to use Firewall CSP. It is very difficult to implement the policies. No support is provided on this CSP because it comes under customization.

**Comment by joinimran** [comment]
Hello, @dfconroy Hope, this will answer your query.

For the 1st scenario where you want to block a specific address:
Enter the rule name.
Select the protocol you want to block. Select Any if you want to block all traffic.
Enter the source IP address as * 
Enter the destination IP address (The IP address you want to block)
Enter port as * or any port separated by a comma.
For the 2nd scenario where you want to block All and allow the specific IP address
Enter the rule name.
Select the protocol you want to block. Select Any if you want to block all traffic.
Enter the source IP address as * 
Enter the destination IP address *, (The IP address you want to allow)
Enter port as * or any port separated by the comma.

**Comment by dfconroy** [comment]
> Hello, @dfconroy Hope, this will answer your query.
> 
> For the 1st scenario where you want to block a specific address:
> Enter the rule name.
> Select the protocol you want to block. Select Any if you want to block all traffic.
> Enter the source IP address as *
> Enter the destination IP address (The IP address you want to block)
> Enter port as * or any port separated by a comma.
> For the 2nd scenario where you want to block All and allow the specific IP address
> Enter the rule name.
> Select the protocol you want to block. Select Any if you want to block all traffic.
> Enter the source IP address as *
> Enter the destination IP address *, (The IP address you want to allow)
> Enter port as * or any port separated by the comma.

Thanks for the reply, however, this doesn't explain how to add the rule via the SyncML. For some reason Microsoft has failed to provide adequate examples on the Firewall CSP page.

**Comment by nebulenz** [comment]
From our dealings with a Microsoft PSS engineer custom rules aren't possible as there's no way to get the intune agent to understand the atomic blocks that are required for custom rules.

**Comment by e0i** [comment]
Hello, @dfconroy 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by e0i** [comment]
@officedocsbot open

**Comment by e0i** [comment]
Hello, @dfconroy 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
