### ISSUE TITLE
Totally useless

### ISSUE THREAD

**Issue by bleepazoid** [MicrosoftDocs/windows-itpro-docs#1403]
Someone that's never done this before will never be able to following these directions. So much is just assumed. How do I add Office to MDT? You just tell me to click on the Microsoft folder in Applications, but you never explain how to create one. I tried adding Office in the way that most makes sense, but nothing in the directions looks the same, or works properly. You need to have total noobs try this before publishing this unless crap. But then again, you are Microsoft, which would explain why installing the MDT leaves a totally useless application until you also install the ADT. Seriously?? You can't make one installer that installs and works without hours of additional installs and downloads? The time I have wasted trying to figure out what we could do in a day with Windows 7 is making so not worth our time to use Windows 10. Managed to convince the higher ups that you're a company with it's head still firmly planted in its own ass. We're buying our next round of computers from Apple and not Dell or HP. Couldn't be happier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0eb8c97-caa0-bb05-4b91-14ad2adc4aac
* Version Independent ID: 0cc541a3-8198-c029-d795-308e673ee2f4
* Content: [Create a Windows 10 reference image (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image)
* Content Source: [windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by egallagh** [comment]
I'm not a Microsoft employee, so please be patient if I add my 2 cents here. Over time, deployment has developed into a complex set of inter-related processes that provide an incredible amount of flexibility. This flexibility extends across the Microsoft product line and is interoperable in different ways with countless third party products. I look at the information included here as guidance for creating a test bed and platform to learn from. After all, a single given set of instructions may not be entirely appropriate for your given situation and will most probably need to be adapted you your scenario. There is no one shape fits all cookie cutter.
You would never expect someone to become a surgeon after reading a few pages in a text book or on the web. Similarly here, there is a lot of underlying knowledge about different procedures technologies that must be assumed in order keep the focus on the topic at hand. There is plenty of information and books about the deployment process and the related technologies available from Microsoft and third parties to help you extend your skillset. Have you checked out any of the related videos on Microsoft Virtual Academy or the Microsoft Mechanics content on YouTube for background knowledge?
Ed Gallagher

**Comment by e0i** [comment]
@officedocsbot close
