### ISSUE TITLE
Add instruction for how to write the login name

### ISSUE THREAD

**Issue by mosharafMS** [MicrosoftDocs/windows-itpro-docs#1404]
many people are facing issues with following this doc because they are using the account name as &lt;account&gt;@AzureADName.onmicrosoft.com or &lt;account&gt;@customDomain.com while they should use AzureAD\&lt;accountName&gt; if you can add this hint it will save folks lots of hassle. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@mosharafMS That is a great suggestion, thank you for pointing it out! I'll update the topic with your tip tomorrow.

**Comment by swiftPeter** [comment]
Hi there, it seems like this document still did not include to use AzureAD\Upn instead of using UPN directly.

**Comment by illfated** [comment]
What about the tip note in green, showing the following text:
> **Tip**
>
> When you connect to the remote PC, enter your account name in this format: `AzureAD UPN`. The local PC must either be domain-joined or Azure AD-joined. The local PC and remote PC must be in the same Azure AD tenant.

See also:
- https://github.com/MicrosoftDocs/windows-itpro-docs/commit/bf9867bed7ba556380510867cb6183d5e3278d6b#diff-135eca5f0835e3be485ae4186f910303
- https://github.com/MicrosoftDocs/windows-itpro-docs/commit/d487fcb110600da76cbc21e43ff597aa2293f4d1

**Comment by swiftPeter** [comment]
thanks for the information, may I know what the specific windows build version which does not need to add AzureAD prefix when connect to remote device?

**Comment by illfated** [comment]
> **Tip**
>
> Starting in Windows 10, version 1809, you can **[use biometrics to authenticate to a remote desktop session](https://docs.microsoft.com/windows/whats-new/whats-new-windows-10-version-1809#remote-desktop-with-biometrics)**.

> **[!Note]**
> In Windows 10, version 1709, the user does not have to sign in to the remote device first.
>
> In Windows 10, version 1709, you can add other Azure AD users to the Administrators group on a device in Settings and restrict remote credentials to Administrators. If there is a problem connecting remotely, make sure that both devices are joined to Azure AD and that TPM is functioning properly on both devices.

Other than that, it does not specify. I presume that you only get the choice between "Supported to connect" or "Not supported to connect", but then again, I have not worked with Azure yet.

I recommend contacting your Microsoft Azure support help line or Forums to get more info, because this site is for documentation improvement only.
