### ISSUE TITLE
Need to update location of SEMM Management scripts

### ISSUE THREAD

**Issue by Scottmca** [MicrosoftDocs/windows-itpro-docs#1405]
There are 2 references to SEMM Management scripts download on this page.  We have changed the location of where these are downloaded from

- Old location:  https://gallery.technet.microsoft.com/Sample-PowerShell-for-5eb5f03c
- New Location:  https://www.microsoft.com/en-us/download/details.aspx?id=46703.  Name of the file is SEMM_PowerShell.zip 

Need to change this sentence
You can download samples of the SEMM management scripts from the TechNet Gallery Script Center.

To this
You can download samples of the SEMM management scripts, SEMM_Powershell.zip from the [Surface Tools for IT Downloads](https://www.microsoft.com/en-us/download/details.aspx?id=46703).

Need to change this sentence
is to use the ShowSettingsOptions.ps1 script from SEMM management scripts for Configuration Manager in the TechNet Gallery Script Center.

To this
is to use the ShowSettingsOptions.ps1 script from SEMM_Powershell.zip from the [Surface Tools for IT Downloads](https://www.microsoft.com/en-us/download/details.aspx?id=46703)

**Comment by andreabichsel** [comment]
Looks like this is for https://docs.microsoft.com/en-us/surface/use-system-center-configuration-manager-to-manage-devices-with-semm.

**Comment by jdeckerms** [comment]
The changes were made in pull request 1421 and have been merged to master: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/1421

**Comment by Scottmca** [comment]
It looks like some of the changes were made but not all of them.  

This line says this currently
After Microsoft Surface UEFI Manager is installed on the client Surface device, SEMM is deployed and managed with PowerShell scripts. You can download samples of the SEMM management scripts from the Download Center.

It should say this
After Microsoft Surface UEFI Manager is installed on the client Surface device, SEMM is deployed and managed with PowerShell scripts. You can download sample of the SEMM management scripts(SEMM_Powershell.zip) from the Download Center.

**Comment by jdeckerms** [comment]
@harshithachidanand is making the updates, adding her to review this
