### ISSUE TITLE
Exec Command returns 200 but status returns 404. 

### ISSUE THREAD

**Issue by dfconroy** [MicrosoftDocs/windows-itpro-docs#1416]
Trying to install an MSI via the EnterpriseDesktopAppManagement CSP.

First one I tested worked fine. Was able to install and then query:
<Item>
            <Source>               <LocURI>./User/Vendor/MSFT/EnterpriseDesktopAppManagement/MSI/appName</LocURI>
            </Source>
            <Meta>
               <Format xmlns="syncml:metinf">node</Format>
            </Meta>            <Data>Version/Name/Publisher/InstallPath/InstallDate/DownloadInstall/Status/LastError/LastErrorDesc</Data>
</Item>

However, trying to install a different MSI and the Exec command returns a 200 - however, the status command is returning a 404. 

I see the AppName in the Registry:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\EnterpriseDesktopAppManagement\S-1-5-21-78471806-3201765522-4150244287-1001\MSI\NewDiffappName

However, the only entry under it is "DownloadInstall" : "Ready".

I've run the MSI on the machine locally and it installs fine - both with and without \quiet set. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c96f8e-b37d-843d-e788-d12b3906f4fb
* Version Independent ID: 4c6538e7-ba7c-98ae-6587-cd2792c571e2
* Content: [EnterpriseDesktopAppManagement CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/enterprisedesktopappmanagement-csp)
* Content Source: [windows/client-management/mdm/enterprisedesktopappmanagement-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enterprisedesktopappmanagement-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by dfconroy** [comment]
Had this:
<CommandLine>/quiet</ CommandLine>
the extra space in the closing tag was messing up the Exec.

**Comment by monishknair** [comment]
@dfconroy Is there a working example. I am not able to figure a way to make the app install.

**Comment by dfconroy** [comment]
> @dfconroy Is there a working example. I am not able to figure a way to make the app install.
In case you still needed this.
`
<Exec>
	<CmdID>ece3d0c2-04fb-43de-bd3f-ed0a0fb6befd|InstallApp</CmdID>
	<Item>
		<Target>
			<LocURI>./Device/Vendor/MSFT/EnterpriseDesktopAppManagement/MSI/RunitApp/DownloadInstall</LocURI>
		</Target>
		<Meta>
			<Format xmlns="syncml:metinf">xml</Format>
		</Meta>
		<Data>
			<MsiInstallJob id="{D36D6AF5-9AFB-4CAE-80DE-2A48F5587954}">
				<Product Version="1.0.0">
					<Download>
						<ContentURLList>
							<ContentURL>https://myurl.com/runit.EXE</ContentURL>
						</ContentURLList>
					</Download>
					<Validation>
						<FileHash>4031C................................................AB87192A892</FileHash>      
					</Validation>
					<Enforcement>
						<CommandLine>/q</CommandLine>
						<TimeOut>5</TimeOut>
						<RetryCount>3</RetryCount>
						<RetryInterval>5</RetryInterval>
					</Enforcement>
				</Product>
			</MsiInstallJob>
		</Data>
	</Item>
</Exec>
`
