### ISSUE TITLE
Merge with other page

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/windows-itpro-docs#1423]
I think this page should be updated with details from https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/customize-start-layout since they each have useful details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79fccecd-5484-0304-d82b-9425f1889a22
* Version Independent ID: 4df6b138-c1b5-b551-22c9-19d3d1f9105d
* Content: [Customize and export Start layout (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/customize-and-export-start-layout)
* Content Source: [windows/configuration/customize-and-export-start-layout.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/customize-and-export-start-layout.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@hoyty76 If you see any specific information in https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/customize-start-layout that isn't in Customize and export Start layout (this page), please call it out. Note that this topic is intended for IT administrators, and the other one is written specifically for OEMs.

**Comment by andreabichsel** [comment]
Closing for now.
