### ISSUE TITLE
Administrators need love too

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/windows-itpro-docs#1426]
Any instructions like this should include a link to how to administratively perform the tasks in an enterprise environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5149561d-359f-875d-73c8-f14b2cfa8f80
* Version Independent ID: d465734d-6480-b7ed-6ca0-168e7b989063
* Content: [Manage Surface UEFI settings (Surface)](https://docs.microsoft.com/en-us/surface/manage-surface-uefi-settings)
* Content Source: [devices/surface/manage-surface-uefi-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/manage-surface-uefi-settings.md)
* Product: **w10**
* GitHub Login: @MiladCA
* Microsoft Alias: **jdecker**

**Comment by egallagh** [comment]
Hi Eric. The Surface Enterprise Management Mode link is in the tree pane two items down from the link to this page.
Hope that helps

**Comment by FC-EricWeller** [comment]
Thanks Ed…..not on mobile.  Or at least, not on my mobile.  I do see that from my desktop.  I still think the general concept is legit.


Eric F. Weller, IS Applications Manager
300 S. Fourth Street, Suite 1400, Las Vegas, NV 89101
T:702.692.8060
eweller@fclaw.com



CONFIDENTIALITY NOTICE:
The information contained in this message may be protected by the attorney-client privilege. 
If you believe that it has been sent to you in error, do not read it. Please immediately reply 
to the sender that you have received the message in error. Then delete it. 
Thank you.
