### ISSUE TITLE
New Enrollment Process

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/windows-itpro-docs#1428]
How do you start a new enrollment process?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2748359b-273d-7faa-6a63-7a6ebea450d2
* Version Independent ID: f4885da5-9a83-13aa-789e-1751db586404
* Content: [Validate licensing provisioning and complete Windows Defender ATP set up](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/licensing-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/licensing-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/licensing-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @tbit0001
* Microsoft Alias: **v-tanewt**

**Comment by mjcaparas** [comment]
The best way is to sign up for a trial: https://www.microsoft.com/en-us/WindowsForBusiness/windows-atp

**Comment by AndySanchezVM** [comment]
Hi, is there an option to purchase this via CSP? or is it only available via a trial?
