### ISSUE TITLE
Hotfix Clarification

### ISSUE THREAD

**Issue by marc-denman** [MicrosoftDocs/windows-itpro-docs#1429]
As this article is slightly dated, it references some KB's which are all "Monthly Preview" type software updates.  Can I assume the "Cumulative Monthly Update" contains the same code that will allow the SAMR restriction or is there still a specific hotfix required?  I am looking for clarity on how best to determine if my legacy OS versions have the required code.  We regularly apply the "Cumulative Monthly Updates" to all our systems.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef8b6967-0e45-bcdd-6d70-54759d9f7ec8
* Version Independent ID: 6651ebc1-04f0-421f-891b-6957ca37da7c
* Content: [Network access - Restrict clients allowed to make remote calls to SAM](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@marc-denman Yes, the cumulative monthly update is a roll-up of all previously released updates. If your systems are running version 1607 or later they have the required code. But I don't think the KB updates remain the update history after you upgrade to the next version, eg 1709 or 1803.
