### ISSUE TITLE
To download an offline-licensed app

### ISSUE THREAD

**Issue by joef12345** [MicrosoftDocs/windows-itpro-docs#1434]
The "To download an offline-licensed app" section is either outdated or no longer works.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ee50db8-eb08-7af7-d499-cbcc148620bd
* Version Independent ID: 208e007d-dfc0-b1b1-dd2b-4c101d572e09
* Content: [Distribute offline apps (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/distribute-offline-apps)
* Content Source: [store-for-business/distribute-offline-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/distribute-offline-apps.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by joef12345** [comment]
Figured it out and the directions should be updated to reflect the change.
You need to goto manage\Shopping experience\Show offline apps: Show offline licensed apps to people shopping in the Microsoft Store.  Then when you download the apps, you can select the offline version.  Once purchased, you then select manage\products and services\apps & software.  Then you will be able to download the offline version.

**Comment by tylerswire** [comment]
Thx Joe. I was struggling to figure that one out. Here are the step-by-step based on the new layout / workflow.

Login @ https://businessstore.microsoft.com
Go to Manage tab
Go to Settings
Under Shopping Experience set Show offline apps to On  
Go to Shop for my group tab, search for the required inbox-app, select it, change the License type to: Offline and click the Get the app button which will add the app to your inventory
Click the Manage button. You now have access to download the appx bundle package metadata & license file.
Go to Products & services > Apps & software (list may be empty / ours was until after some time it auto-populated with a few office type apps)

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by lindspea** [comment]
@tylerswire @joef12345 please confirm if the wording after 'Click the Manage button...." must say appx bundle package, or app bundle package?

**Comment by e0i** [comment]
@joef12345 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thank you for your feedback.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by Mosik** [comment]
I can't find where i change the licens type to Offline in the "Shop for my school" tab. I can only do it with apps that ive bought earlier.

**Comment by illfated** [comment]
@Mosik : You may have to contact Microsoft Support in your region to get help with that issue.
Microsoft IT-pro Docs can assist with the documentation, if it needs updating or clarification.
