### ISSUE TITLE
broken link trying to get the the surface dock updater tool

### ISSUE THREAD

**Issue by scottewilson** [MicrosoftDocs/windows-itpro-docs#1437]
https://www.microsoft.com/en-us/download/confirmation.aspx?id=46703 is not loading

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7b356e-3dbd-7f59-845e-a92e05865a52
* Version Independent ID: 711c5497-373f-662c-7fae-ba60f046e50c
* Content: [Microsoft Surface Dock Updater (Surface)](https://docs.microsoft.com/en-us/surface/surface-dock-updater#feedback)
* Content Source: [devices/surface/surface-dock-updater.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/surface-dock-updater.md)
* Product: **w10**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by scottewilson** [comment]
no luck in either chrome or edge

**Comment by jdeckerms** [comment]
@scottewilson Sorry, I don't know what else to suggest -- the link is correct.

**Comment by scottewilson** [comment]
I should be more specific -- the link works, but then when I try to actually download the surface updater tool I get an error page in both edge and chrome.  could you try to actually download the utility using the page?

**Comment by jdeckerms** [comment]
@scottewilson It's a zip file. I can download it and extract all files. I chose "Save as" (rather than "Open").

**Comment by scottewilson** [comment]
nm, whatever you just did worked -- I was finally able to download Surface_Dock_Updater_v2.22.139.0.msi

**Comment by jdeckerms** [comment]
@scottewilson Glad it's working for you finally!
