### ISSUE TITLE
HoloLens First Experience Skip Wifi

### ISSUE THREAD

**Issue by jjherman94** [MicrosoftDocs/windows-itpro-docs#1438]
I'm creating a provision package for a HoloLens and I set it to skip wifi during the first experience, but it won't actually skip. Has there been a fix to this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a69caaa3-6fa7-6fcf-bfc3-2aa894f59401
* Version Independent ID: f0a3941f-6cdf-9881-e1c4-b62911fe6d24
* Content: [FirstExperience (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/wcd/wcd-firstexperience#hololens)
* Content Source: [windows/configuration/wcd/wcd-firstexperience.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/wcd/wcd-firstexperience.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@jjherman94 Please report your experience using the Feedback Hub -- that will allow the product team to gather logs and data to help figure out the problem.

**Comment by jdeckerms** [comment]
@jjherman94 How exactly did you configure the provisioning package? Did you use the "Provision HoloLens devices" wizard, and then switch to the advanced editor to configure FirstExperience? What other settings are included in your provisioning package?

**Comment by jjherman94** [comment]
@jdeckerms I used the Windows Configuration Designer selected "Provision HoloLens devices" and then switched to the advanced editor. I have configured a bunch of other settings in the provisioning packages and for the first experience section I'm able to successfully skip calibration, training, timezone, and region but am unable to skip the wifi setup. I've also just tried creating a provision package where the only change is the setting to skip wifi setup and after loading the package it doesn't skip it either.

**Comment by jdeckerms** [comment]
@jjherman94 I just got clarification on FirstExperience, and I'll be updating the documentation to make it clearer. 

HoloLens has to connect to Wifi during setup to verify the Microsoft account (MSA) or Azure Active Directory (Azure AD) account. (https://docs.microsoft.com/en-us/hololens/hololens-setup) 

You can configure the Wifi network in a provisioning package and also configure "skip wifi" so that the page in setup to connect to wifi is hidden (because the wifi connection was done in the provisioning package).

**Comment by riebling** [comment]
it's quite easy to get the FirstExperience so wrong that you cannot use your HoloLens. If you give a wrong WiFi and select "automatically connect", it will automatically fail every time when it gets to the stage of verifying Windows 10 license. There really needs to be a way to get out of this mode, else you're just plain stuck, unable to do a darn thing with HoloLens.
