### ISSUE TITLE
Update To Show The Azure Integrated Console

### ISSUE THREAD

**Issue by clconlin** [MicrosoftDocs/windows-itpro-docs#1439]
Should this be updated to show the Azure integrated console?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32ffd19a-b42a-2ed8-433a-e791d31bb16b
* Version Independent ID: 3dc309e7-dfd3-bbab-f95c-17d4794129bf
* Content: [Walkthrough use Intune to configure Windows Update for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-wufb-intune)
* Content Source: [windows/deployment/update/waas-wufb-intune.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-wufb-intune.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
I think the latest guidance is available through the intune library : https://docs.microsoft.com/en-us/intune/windows-update-for-business-configure

@jaimeo might be able to help here. 

Thanks for reaching out, @clconlin!

**Comment by jaimeo** [comment]
This topic has been superseded by https://docs.microsoft.com/en-us/intune/windows-update-for-business-configure -- we'll be updating this topic to direct readers there.

**Comment by clconlin** [comment]
Thanks for letting me know ??
________________________________

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello @clconlin ,

We are closing this issue since your question seems to be answered. Feel free to re-open this issue if you still experience problems.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
