### ISSUE TITLE
How about allow people to print 

### ISSUE THREAD

**Issue by IraDorman** [MicrosoftDocs/windows-itpro-docs#1441]
Not a hard thing to do can't print this document there appears to be only blank pages if I do. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71d85a90-230f-84b0-a024-88a8da36825d
* Version Independent ID: bf2db39e-16b3-f5a8-af07-91ed301a5ca7
* Content: [BitLocker How to deploy on Windows Server 2012 and later (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-how-to-deploy-on-windows-server)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-how-to-deploy-on-windows-server.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-how-to-deploy-on-windows-server.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by andreabichsel** [comment]
I was able to print these pages from Edge, so I'm not able to replicate the problem. You can also try downloading PDF (link at the bottom left in the TOC). If you're still having problems printing this out, you can try Microsoft Support https://support.microsoft.com/en-us. Thanks!
