### ISSUE TITLE
Settings/PageVisibilityList

### ISSUE THREAD

**Issue by dfconroy** [MicrosoftDocs/windows-itpro-docs#1442]
The add& replace commands come back with a 200 status code, however, I can still see the items in the control panel/settings page.

<details>

&lt;Item&gt;
&lt;Target&gt;
  &lt;LocURI&gt;./Vendor/MSFT/Policy/Config/Settings/PageVisibilityList&lt;/LocURI&gt;
&lt;/Target&gt;
  &lt;Meta&gt;&lt;Format xmlns=&quot;syncml:metinf&quot;&gt;chr&lt;/Format&gt;&lt;/Meta&gt;
  &lt;Data&gt;&lt;![CDATA[&lt;data id=&quot;SettingsPageVisibilityBox&quot; value=&quot;showonly:about;bluetooth;workplace&quot;/&gt; ]]&gt;&lt;/Data&gt;
&lt;/Item&gt;

Also tried with:

&lt;Data&gt;&lt;![CDATA[&lt;enabled/&gt;&lt;data id=&quot;SettingsPageVisibilityBox&quot; value=&quot;showonly:about;bluetooth;workplace&quot;/&gt; ]]&gt;&lt;/Data&gt;
</details>

The computer is Win 10 Pro, 1803.  

Am I using the correct ADMX code? Any help would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502b34cb-f410-94eb-80c0-87729cd29fb9
* Version Independent ID: 34336fed-e0f4-85bb-32e5-c41020037c1f
* Content: [Policy CSP - Settings](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-settings)
* Content Source: [windows/client-management/mdm/policy-csp-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-settings.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by dfconroy** [comment]
Also, I tried the data as below as well without success:

&lt;Data&gt;showonly:about;bluetooth;workplace&lt;/Data&gt;

Here are the Event logs:
<details>

MDM PolicyManager: Set policy string, Policy: (PageVisibilityList), Area: (Settings), EnrollmentID requesting merge: (190AB4A5-1770-481B-AA94-A13A208A5E00), Current User: (Device), String: (showonly:about;network-wifi), Enrollment Type: (0x0), Scope: (0x0).
<br/><br/><br/>

MDM ConfigurationManager: Command failure status. Configuraton Source ID: (190AB4A5-1770-481B-AA94-A13A208A5E00), Enrollment Type: (MDMFull), CSP Name: (Policy), Command Type: (Add: from Replace or Add), Result: (./Device/Vendor/MSFT/Policy/Config/Settings/PageVisibilityList).

</details>

**Comment by dbdmora** [comment]
@dfconroy, instead of <data> use <string>showonly:about;bluetooth;workplace</string> see if that works for you.

**Comment by dfconroy** [comment]
@dbdmora That'd be strange to switch from `<data>` to `<string>` since everything else that utilize SyncML utilizes the  `<data>`  element.

**Comment by dbdmora** [comment]
@dfconroy I am using the Intune Custom Profile to add this as an OMA-URI.  in the documentation it is showing as String value not data.  This is why I said to use String but if yo are doing something else, then ignore my comment.

The format of the PageVisibilityList value is as follows:

The value is a unicode string up to 10,000 characters long, which will be used without case sensitivity.
There are two variants: one that shows only the given pages and one which hides the given pages.
The first variant starts with the **string** "showonly:" and the second with the **string** "hide:".
Following the variant identifier is a semicolon-delimited list of page identifiers, which must not have any extra whitespace.
Each page identifier is the ms-settings:xyz URI for the page, minus the ms-settings: prefix, so the identifier for the page with URI "ms-settings:wi-fi" would be just "wi-fi".

**Comment by dfconroy** [comment]
Seems to only be working on Builds of 1809 and higher.
