### ISSUE TITLE
Transitional clarification

### ISSUE THREAD

**Issue by stusims** [MicrosoftDocs/windows-itpro-docs#1446]
Hi guys, a couple of points of clarification required I think:-

1. For customers with Windows 10 'Enterprise' clients actively being used in production environments using KMS or Active Directory for activation via a VL agreement, what are the technical steps required to disable KMS / AD Activation and implement Windows 10 Enterprise E3 in CSP in its place? The article above currently implies that you need to rebuild all your devices to Windows 10 Pro edition.

2. Where should Enterprise IT admins be obtaining the media for rolling out Windows 10 Enterprise in CSP for use with deployment tools such as MDT and SCCM, and does it have to be Pro edition for the activation to be successful?

Many thanks in advance. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ecbc1-9c02-5681-7214-356be22ac7e8
* Version Independent ID: 73af82f6-079b-6c37-55c4-cb59e921457a
* Content: [Deploy Windows 10 Enterprise licenses](https://docs.microsoft.com/en-us/windows/deployment/deploy-enterprise-licenses)
* Content Source: [windows/deployment/deploy-enterprise-licenses.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-enterprise-licenses.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by stusims** [comment]
So found this that covers point 1 above for SA subscriptions, would it work for CSP too: https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-subscription-activation#existing-enterprise-deployments

**Comment by stusims** [comment]
That said this would only appear to work for PC's with Firmware-embedded activation keys

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by Reeced40** [comment]
@stusims Thanks for reaching out and helping improve MS Doc. I'm working to find the solution to question 2. Thank you for solving question 1, I'll be sure to add it to the article soonest.

**Comment by mypil** [comment]
@stusims - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by Reeced40. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
