### ISSUE TITLE
Existing Enterprise deployments

### ISSUE THREAD

**Issue by stusims** [MicrosoftDocs/windows-itpro-docs#1447]
I think you need to cover this process within this article as well assuming it works for CSP as well?: https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-subscription-activation#existing-enterprise-deployments

Also I think you need to state what the process is for devices without a firmware-embedded product keys

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf22b00-1c7f-5fd8-7e21-f3a50da00a15
* Version Independent ID: f118fd3a-d0b3-ae53-0b59-a049fe18eb15
* Content: [Windows 10 Enterprise E3 in CSP](https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-e3-overview)
* Content Source: [windows/deployment/windows-10-enterprise-e3-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-enterprise-e3-overview.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by Kazzan** [comment]
Yes, same question right now. Not everyone has option to have the newest hardware in time of license switch.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by lindspea** [comment]
@stusims Thank you for reaching out.  Are you suggesting adding the information under existing enterprise deployments? Could you please advise what the process is for devices without a firmware-embedded product key?

**Comment by e0i** [comment]
@stusims We are closing this issue since we haven't got updates from your side.

Feel free to re-open it with your suggestions if you feel that the documentation is still not sufficient.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
