### ISSUE TITLE
Confusion/Typo: 

### ISSUE THREAD

**Issue by sceptapular** [MicrosoftDocs/windows-itpro-docs#1449]
https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt#a-href-idsec07astep-7-configure-the-mdt-production-deployment-share

It starts talking about configuring the Build Lab in the middle of the Production setup, and references some D:\Setup\Sample Files\MDT Production\Control repository out of the blue. 

Help?

**Comment by e0i** [comment]
@sceptapular Thank you for your feedback.

The same issue has been addressed at #2567 Feel free to re-open this issue if it is not the case.

Good day.

**Comment by e0i** [comment]
Duplicate of #2567 

@officedocsbot close

**Comment by sceptapular** [comment]
Sagolun, Onur Bey.
