### ISSUE TITLE
Clients aren't able to reach the Delivery Optimization cloud services....

### ISSUE THREAD

**Issue by mertongroup** [MicrosoftDocs/windows-itpro-docs#1451]
Someone please elaborate how or what is meant by "2. Run Get-DeliveryOptimizationStatus from an elevated window and share the output (by setting the DownloadMode field to 1")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb67e518-6f60-23e0-2545-c2839e2b4159
* Version Independent ID: e9a31629-e3cb-0367-31c4-5661284d89bf
* Content: [Configure Delivery Optimization for Windows 10 updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization)
* Content Source: [windows/deployment/update/waas-delivery-optimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-delivery-optimization.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by andreabichsel** [comment]
@jaimeo, can you clarify?

**Comment by jaimeo** [comment]
I am researching this.

Query though: do you not know what we mean by "elevated window" or how to set the DownloadMode parameter--or both?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @mertongroup ,
**We have group policy deploying the DownloadMode setting, but the statement on the document implies there is a way of manually setting a particular download to be  1 (Lan)?** - yes, there is a way to set downloadmode using registry keys, more details in [this article](https://www.ghacks.net/2016/08/17/windows-10-update-delivery-optimization/)
Thank you

**Comment by mypil** [comment]
@mertongroup - Thank you for submitting this feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
