### ISSUE TITLE
HoloLens Fails to Install Apps Through Provisioning Packages

### ISSUE THREAD

**Issue by jjherman94** [MicrosoftDocs/windows-itpro-docs#1454]
I'm trying to install my app (which isn't on the Microsoft Store) onto a HoloLens through provisioning packages, but the provisioning package fails to install using the UserContextApp. With the app package (appx/appxbundle file) and its dependencies I'm able to easily add the app through device portal, but not the provisioning packages. It doesn't even display errors when building the provisioning package. 

What is typically the cause of it failing to install? And since for the HoloLens, provision packages have to be added during OOBE, where can I see a log of the error messages to help diagnose the cause of it failing to install?

If it helps I included the portion of the provisioning package customizations.xml to show how I have it setup.
```xml
<UniversalAppInstall>
  <UserContextApp>
	<Application PackageFamilyName="Planetarium_pzq3xp76mxafg" Name="Planetarium_pzq3xp76mxafg">
	  <ApplicationFile>C:\Users\jjherman94\Documents\Planetarium\App\Planetarium\AppPackages\Planetarium_1.0.0.0_x86_Test\Planetarium_1.0.0.0_x86.appx</ApplicationFile>
	  <DependencyAppxFiles>
		<Dependency Name="Microsoft.NET.CoreRuntime.1.1">C:\Users\jjherman94\Documents\Planetarium\App\Planetarium\AppPackages\Planetarium_1.0.0.0_x86_Test\Dependencies\x86\Microsoft.NET.CoreRuntime.1.1.appx</Dependency>
		<Dependency Name="Microsoft.VCLibs.x86.14.00">C:\Users\jjherman94\Documents\Planetarium\App\Planetarium\AppPackages\Planetarium_1.0.0.0_x86_Test\Dependencies\x86\Microsoft.VCLibs.x86.14.00.appx</Dependency>
	  </DependencyAppxFiles>
	</Application>
  </UserContextApp>
</UniversalAppInstall>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34e97a46-9219-e0d5-b31e-04ba4f0bcbb1
* Version Independent ID: 693f6696-914d-7872-36de-00d06b84f376
* Content: [UniversalAppInstall (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/wcd/wcd-universalappinstall)
* Content Source: [windows/configuration/wcd/wcd-universalappinstall.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/wcd/wcd-universalappinstall.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@jjherman94 I will correct the UniversalAppInstall documentation. If you see the HoloLens documentation (https://docs.microsoft.com/en-us/hololens/hololens-provisioning#what-you-can-configure), it states "App installation (UniversalAppInstall) using a provisioning package is not currently supported for HoloLens."

**Comment by jjherman94** [comment]
@jdeckerms Is it planned to be supported in the future?

**Comment by jdeckerms** [comment]
@jjherman94 Sorry, I don't have any information on future changes or product roadmap for HoloLens.
