### ISSUE TITLE
https://youtu.be/IYgMEMdGkF8

### ISSUE THREAD

**Issue by Puppenrupp** [MicrosoftDocs/windows-itpro-docs#1456]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73209f6b-b5c0-39c7-8319-59054f3b12a6
* Version Independent ID: 5b9f9df6-1110-4f0e-82e3-00fef4650b38
* Content: [Cortana integration in your business or enterprise (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/cortana-at-work/cortana-at-work-overview)
* Content Source: [windows/configuration/cortana-at-work/cortana-at-work-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/cortana-at-work/cortana-at-work-overview.md)
* Product: **w10**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by shortpatti** [comment]
Closing. No issues reported; spam.
