### ISSUE TITLE
Unsure how Specify Deadline & specify Engaged works when combined

### ISSUE THREAD

**Issue by Shachar2like** [MicrosoftDocs/windows-itpro-docs#1457]
I'm unsure how the 'Specify deadline before auto-restart for update installation' policy works with the 'Specify Engaged restart transition and notification schedule for updates' works

if I set for example the specify deadline for 7 days and a restart will occur after working hours, why do I need or what is the specify engaged policy for?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184809a-63ff-ecc2-ab67-9c9f4df900f8
* Version Independent ID: ac25ee6c-4c57-58b3-1313-e4a53f53c5a1
* Content: [Manage device restarts after updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-restart)
* Content Source: [windows/deployment/update/waas-restart.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-restart.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
@jaimeo might be able to help out here. (@andreabichsel \ @shortpatti - please re-assign. Thanks :) )

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by Reeced40** [comment]
@Shachar2like Thanks for reaching out, I will get an answer for you as soon as possible.

**Comment by mypil** [comment]
@Shachar2like  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by Reeced40. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
