### ISSUE TITLE
Support for vanity or non standard SMTP addresses

### ISSUE THREAD

**Issue by dbaars** [MicrosoftDocs/windows-itpro-docs#1458]
Hi,

Our company uses firstname.lastname@company.co.nz as the default SMTP address for users. Is there a timeline for supporting this type of address for surface hub sign in using the Authenticator app?

Thanks,
Dylan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddbb85-f5df-b124-2783-0330d9da2e06
* Version Independent ID: aff516a2-3bb0-843d-5652-e25f90bab00f
* Content: [Sign in to Surface Hub with Microsoft Authenticator](https://docs.microsoft.com/en-us/surface-hub/surface-hub-authenticator-app)
* Content Source: [devices/surface-hub/surface-hub-authenticator-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/surface-hub-authenticator-app.md)
* Product: **surface-hub**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@dbaars Sorry, I don't have any information on future plans or product roadmap.
