### ISSUE TITLE
microsoft apps are missing

### ISSUE THREAD

**Issue by melon2** [MicrosoftDocs/windows-itpro-docs#1459]
Following all these instructions - very useful and it appears to work.  BUT when I try to implement a second .xml setup on the same machine ALL THE MICROSOFT apps tiles are missing !?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75fac9c3-5f88-0c2f-d95c-a47b58e49f19
* Version Independent ID: 9d26f74d-5f26-cfec-b9b6-5ed6a44a306f
* Content: [Customize Windows 10 Start and tasbkar with Group Policy (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/customize-windows-10-start-screens-by-using-group-policy)
* Content Source: [windows/configuration/customize-windows-10-start-screens-by-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/customize-windows-10-start-screens-by-using-group-policy.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@melon2 It shouldn't work that way. Please report it in the Feedback Hub, preferably on the device that you applied the second .xml layout on. Thanks!
