### ISSUE TITLE
No features for installation.

### ISSUE THREAD

**Issue by smelichar** [MicrosoftDocs/windows-itpro-docs#1460]
This solution not working, unfortunately I have no features for installation there. XPS viewer cannot be installed. What's now? Maybe this is because our computers are managed by the WSUS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecb7910b-900c-49cb-46ae-0c1de7cf3df6
* Version Independent ID: 5f7b8dba-d1df-95b0-8e54-32a729a5cf27
* Content: [Windows 10 - How to add apps from Apps & features](https://docs.microsoft.com/en-us/windows/application-management/add-apps-and-features#feedback)
* Content Source: [windows/application-management/add-apps-and-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/add-apps-and-features.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by ITDude1984** [comment]
The solution you have written up does not work.
Either adding via add remove option features (there is nothing listed) or via the DISM command. 
Have tried on both Pro and Education versions of Win10, same results.

Does anyone know if MS are aware of this or have a work around? I have a team which still use this and are now on 1803, as it stands the only option I have is to down grade them which is very undesirable to say the least.

**Comment by ShortOrderCookie** [comment]
ITDude,

I'm running the above script on my 1803 Enterprise to create a number of images.  No failures to download the XPS Writer yet.
Some thoughts on things to looks for that might be interfering.

At the time that you run the DISM command, can your system get out to the internet?   The DISM command will download the XPS writer from Microsoft.   My network is set up with a direct connection to the internet so I don't need a proxy server set.  If you needed a proxy server to get out to the internet, I'm not sure if you would need to set one in IE or in NETSH WINHTTP for the DISM connection to be made with MS.

Another snag I ran into when running the script on 1803 is that I had to make sure that I ran the script after applying one of the monthly Cumulative Updates for 1803.  It seems that when they released 1803 back in April, it was still buggy and MS highly recommended that you apply a CU before doing any customization.   This was a problem when running this script.   I also saw this problem when I ran the DISM command to remove some of the provisioned apps.  There were errors if the scripts were run before a CU was applied.  No issues if run after a CU was applied.

**Comment by ShortOrderCookie** [comment]
ITDude,
I kept referring to XPS writer...I meant XPS viewer.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by denisebmsft** [comment]
I think the original issue is now resolved, so I'm closing this. Kind regards!
