### ISSUE TITLE
"Event Ciewer" - presumably should be "Event Viewer"

### ISSUE THREAD

**Issue by KitPatterson** [MicrosoftDocs/windows-itpro-docs#1461]
"Event Ciewer" - presumably should be "Event Viewer"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5862cc7-3f36-5f2e-9ade-f7441f99f818
* Version Independent ID: b8bd1985-7b5b-ea79-976a-7d96ad69335c
* Content: [Use Windows Event Forwarding to help with intrusion detection (Windows 10)](https://docs.microsoft.com/en-gb/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection)
* Content Source: [windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md)
* Product: **w10**
* GitHub Login: @tedhardyMSFT
* Microsoft Alias: **justinha**

**Comment by andreabichsel** [comment]
Fixed--thank you! Changes should be live by eod.
