### ISSUE TITLE
Default Network Boundaries

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/windows-itpro-docs#1463]
The content above says:  "There are no default locations included with WIP, you must add each of your network locations."

However, if I go to the azure portal for my tenant and add an App Protection Policy, the Network Boundaries autopopulate an entry of type "Cloud Resources" and name "SharePoint", with some company SharePoint Online URLs. Obviously this causes issues if left default.

Is there a setting in my tenant that causes this to be autopopulated? Can I stop this? 

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ad3f92-24de-5eb5-8454-c72d85737183
* Version Independent ID: 900125eb-31ea-faf3-ac30-7c3d7b30f611
* Content: [Create a Windows Information Protection (WIP) policy with MAM using the Azure portal for Microsoft Intune (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-mam-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-mam-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/create-wip-policy-using-mam-intune-azure.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@thedrum808 Intune has a feature to add SharePoint sites discovered through the Graph API. I'll add this to the topic. Why does it cause issues? Can you remove it?

**Comment by Justinha** [comment]
@thedrum808 This is added now. Thanks for pointing this out.
