### ISSUE TITLE
Allowing Desktop App Dependencies

### ISSUE THREAD

**Issue by camlen92** [MicrosoftDocs/windows-itpro-docs#1464]
Hello! We are trying to see if Multi App Kiosk mode will work with our current situation. 

We have an in-house program that utilizes Java and possibly some other .exe's to run. We can only get the program launcher to work in multi app kiosk mode, the rest of the program doesn't load. Is there a way to use a wildcard in the address or add an entire directory to the AllowedApps element? Something like App DesktopAppPath="%SystemDrive%\MyProgram\*" /

Thanks!

**Comment by jdeckerms** [comment]
@camlen92 Multi-app kiosk configuration generates AppLocker rules to allow specific apps to run. The product team suggests viewing the AppLocker event logs to identify the process(es) that are being blocked, so you can add them to the AllowedApps configuration. (Info on using AppLocker event logs: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/using-event-viewer-with-AppLocker)
