### ISSUE TITLE
Honest FAQ

### ISSUE THREAD

**Issue by a688** [MicrosoftDocs/windows-itpro-docs#1469]
Can this be updated to be a bit more honest about IE 11? IE 11 does not support (all) modern web standards. If management at my company read this article, they would see that IE read that IE is "modern" but only read about stuff they honestly don't care about when they look a the Edge section. If you don't explicitly state that IE 11 is OLD and should not be targeted for new development if possible, then people who make decisions at companies but have no idea about browsers/technology are going to just ask for/force the development of technical debt platforms instead of helping move the web along by targeting and using modern browsers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3dd9c01-6d96-f3dd-c5fc-9565de8221bc
* Version Independent ID: 138ea771-3311-b31f-ccd1-2248871585a3
* Content: [Microsoft Edge and Internet Explorer 11 (Microsoft Edge for IT Pros)](https://docs.microsoft.com/en-us/microsoft-edge/deploy/enterprise-guidance-using-microsoft-edge-and-ie11)
* Content Source: [browsers/edge/enterprise-guidance-using-microsoft-edge-and-ie11.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/enterprise-guidance-using-microsoft-edge-and-ie11.md)
* Product: **edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **shortpatti**

**Comment by shortpatti** [comment]
@a688, Thank you for your feedback.  We are working on the update now, which will be ready for the next major release.
