### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by AnthonyBe** [MicrosoftDocs/windows-itpro-docs#1471]
"At the same time, we've kept the Standard User Analyzer tool, which helps you test your apps and to monitor API calls for potential compatibility issues, and the Compatiblility Administrator, which helps you to resolve potential compatibility issues."

Compatiblility -&gt; Compatibility

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd3bbc4c-2f86-d5a9-336c-93695ace49f2
* Version Independent ID: a7c51e81-2cb2-5ad0-a9b5-7fb89921a0be
* Content: [Application Compatibility Toolkit (ACT) Technical Reference (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/planning/act-technical-reference)
* Content Source: [windows/deployment/planning/act-technical-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/act-technical-reference.md)
* Product: **w10**
* GitHub Login: @eross-msft
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@AnthonyBe - From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
