### ISSUE TITLE
Lock a partrial start layout

### ISSUE THREAD

**Issue by pradosz** [MicrosoftDocs/windows-itpro-docs#1473]
Hi , 

Partial start layout lock not working for me, I did add the line &lt;DefaultLayoutOverride LayoutCustomizationRestrictionType="OnlySpecifiedGroups"&gt; to my xml and then import it, log in as new created user, all changes I did made in file like pinned apps and groups are there but groups are not locked, user can change tiles in them groups.
I did check modificationlayout.xml file in that user file and the line for restrictions is there. I'm using windows 10 Pro 1803

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79fccecd-5484-0304-d82b-9425f1889a22
* Version Independent ID: 4df6b138-c1b5-b551-22c9-19d3d1f9105d
* Content: [Customize and export Start layout (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/customize-and-export-start-layout)
* Content Source: [windows/configuration/customize-and-export-start-layout.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/customize-and-export-start-layout.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@pradosz Can you report the issue using the Feedback Hub? Thanks!

**Comment by pradosz** [comment]
Hi, No problem

done now

**Comment by pilgi3** [comment]
I have the same problem. There a new informations? Seems like the partial locked start meny layout works only with GPO?
