### ISSUE TITLE
Kiosk browser only supports a single tab

### ISSUE THREAD

**Issue by PanuSaukko** [MicrosoftDocs/windows-itpro-docs#1474]
Please add to the documentation about Kiosk browser that it supports only a single tab. If your web site has links that open a new tab, those links will not work with Kiosk browser

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd2d1007-2cbb-94a6-18aa-a0b879262ab1
* Version Independent ID: 625d9906-0cb0-23eb-3a56-a84ad774d291
* Content: [Guidelines for choosing an app for assigned access (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/guidelines-for-assigned-access-app#guidelines-for-web-browsers)
* Content Source: [windows/configuration/guidelines-for-assigned-access-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/guidelines-for-assigned-access-app.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@PanuSaukko I'll add that information today, thanks for bringing it to our attention.
