### ISSUE TITLE
Where are all the other game apps?

### ISSUE THREAD

**Issue by shazzamm** [MicrosoftDocs/windows-itpro-docs#1475]
Please include in your list all other appx apps packages that Windows 10 deploys automatically, as you are missing several.
Examples: Royal Revolt, Minecraft, Network speed test, facebook, twitter, candy crush, slingbox, netflix, password keeper, spotify, etc. etc.
We need the proper names to disable these from reinstalling themselves.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9c3129d-3c8d-b508-f298-3333499bb180
* Version Independent ID: 97b70720-82d8-60a4-3958-00ceed34aa1b
* Content: [How to keep apps removed from Windows 10 from returning during an update](https://docs.microsoft.com/en-us/windows/application-management/remove-provisioned-apps-during-update#registry-keys-for-provisioned-apps)
* Content Source: [windows/application-management/remove-provisioned-apps-during-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/remove-provisioned-apps-during-update.md)
* Product: **w10**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by OftKilted** [comment]
@shazzamm as mentioned in **https://github.com/MicrosoftDocs/windows-itpro-docs/pull/1513** by @borkason in https://github.com/MicrosoftDocs/windows-itpro-docs/pull/1513#issuecomment-415056396 the "Customer Experience" apps aren't actually provisioned. (They only show up if you haven't configured the appropriate 'Block Customer Experiences' or the applicable registry key.)

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @shazzamm did you get the information you need? In addition to what @OftKilted has provided, you may want to check the following documentations:

1. [Understand the different apps included in Windows 10](https://docs.microsoft.com/windows/application-management/apps-in-windows-10) - please see the *Provisioned Windows apps* list.
2. [How to keep apps removed from Windows 10 from returning during an update](https://docs.microsoft.com/windows/application-management/remove-provisioned-apps-during-update#registry-keys-for-provisioned-apps) - please see *Package names for apps provisioned in Windows 10, version 1709* and *Registry keys for provisioned apps* lists. 

We want users to have the best Windows 10 experience by ensuring the contents of the Microsoft Docs are useful, accurate and up-to-date, hence, if there is anything that needs to be added or edited in the documentation, please let us know. Thank you.

**Comment by jvsam** [comment]
Hi again @shazzamm. We haven't received any response from you. For now, we will close this issue, however, if you believe the documentation needs improvement, please re-open and provide recommendations on what needs to be changed or updated. Again, our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation. Thank you for engaging with the community!

**Comment by jvsam** [comment]
@officedocsbot close
