### ISSUE TITLE
Windows 1803

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/windows-itpro-docs#1482]
Joining a Windows 10 1709 device to Azure AD would work perfectly.
Since we upgraded to 1803 the package does not work anymore. Is this supported? Does the package must be created on a Win10 1803 workstation to work? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5d1da33-932c-e5cf-7a3c-8523d48a3a68
* Version Independent ID: bd16dcec-e38f-501d-22f4-735e50e93fa6
* Content: [Provisioning packages (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-packages)
* Content Source: [windows/configuration/provisioning-packages/provisioning-packages.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/provisioning-packages/provisioning-packages.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@janopurk I'm checking with the product team to verify whether a newer (1803) version of the Windows Configuration Designer is required. In the meantime though, could you check what the Azure AD bulk token expiration data was set for in the 1709 provisioning package?

**Comment by janopurk** [comment]
I did, packet was valid for 29 more days.


Op 20 aug. 2018 om 20:55 heeft Jeanie Decker <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@janopurk<https://github.com/janopurk> I'm checking with the product team to verify whether a newer (1803) version of the Windows Configuration Designer is required. In the meantime though, could you check what the Azure AD bulk token expiration data was set for in the 1709 provisioning package?

**Comment by jdeckerms** [comment]
@janopurk Could you collect and attach the provisioning and AAD event logs from the device that the package failed to apply to?

C:\Windows\System32\winevt\Logs\Microsoft-Windows-Provisioning-Diagnostics-Provider%4Admin.evtx

C:\Windows\System32\winevt\Logs\Microsoft-Windows-AAD%4Operational.evtx

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam
