### ISSUE TITLE
mstsc /remoteguard doesn't work if connecting to RDS servers

### ISSUE THREAD

**Issue by MumpekPumpa** [MicrosoftDocs/windows-itpro-docs#1483]
I just had a long case (118031817833720) opened regarding this feature.

After much testing using mstsc /remoteguard (no GPOs were set) and receiving "Access is denied" for non admin users (meaning that Restricted Admin was used for admins, but couldn't be for regular users) I received an answer from the Microsoft technician:

"It has been confirmed internally that: Mstsc.exe /remoteguard works only with administrators. This has been tested in RDS deployments and confirmed with RDS ETL tracing".

This only applies to servers part of a RDS deployment, we were able to connect just fine to other servers. Once we set the GPO on the clients we were able to connect to a RDS server as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c826587d-2e65-083f-254d-75f188158f08
* Version Independent ID: 746596b5-c1df-9ea0-abcc-f6ff97874e40
* Content: [Protect Remote Desktop credentials with Windows Defender Remote Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/remote-credential-guard)
* Content Source: [windows/security/identity-protection/remote-credential-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/remote-credential-guard.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by DaniHalfin** [comment]
Hi @MumpekPumpa - any improvement that you'd like to see in the current topic?
I'm not certain about your configuration, but if your RDS deployment is configured in restricted admin mode, it would make sense.

**Comment by DaniHalfin** [comment]
@shortpatti - please close this issue.
If there are any updates to the original feedback, please reply back. Thanks!

**Comment by MumpekPumpa** [comment]
@DaniHalfin, my apologies for not answering, I didn't see a reply was posted. Our RDS deployment was configured with:
`reg add HKLM\SYSTEM\CurrentControlSet\Control\Lsa /v DisableRestrictedAdmin /d 0 /t REG_DWORD`

So using mstsc /remoteguard should have worked for regular users as well, but it didn't. This was only the case for our RDS server, it worked without issue on all other servers.

As such, I think the documentation should be changed, that mstsc /remoteguard doesn't work in that scenario (RDS server), but the GPO settings do (they are usually the same thing, but not in this case it appears). The technician on the case didn't provide any reason for this apart from:

> "It has been confirmed internally that: Mstsc.exe /remoteguard works only with administrators. This has been tested in RDS deployments and confirmed with RDS ETL tracing".

**Comment by MumpekPumpa** [comment]
@DaniHalfin @shortpatti Could you please reopen this until we get a proper answer. The issue was probably closed because of a lack of response from my side, as mentioned, I missed the comment on 22nd of August from @DaniHalfin .

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by martyav** [comment]
I believe this was resolved with commit 0c54bc2
