### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by pedrr** [MicrosoftDocs/windows-itpro-docs#1486]
What is the requirement on the Windows 10 side to get the MAM Policy applied if I logged on with a personal account on the device? Does the device need to be registered in Azure AD?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ad3f92-24de-5eb5-8454-c72d85737183
* Version Independent ID: 900125eb-31ea-faf3-ac30-7c3d7b30f611
* Content: [Create a Windows Information Protection (WIP) policy with MAM using the Azure portal for Microsoft Intune (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-mam-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-mam-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/create-wip-policy-using-mam-intune-azure.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by Reeced40** [comment]
@pedrr Thanks for reaching out, I'll have an answer for you shortly.

**Comment by Reeced40** [comment]
@pedrr Yes, it needs to be registered in Azure AD, because when you set the MAM policy scope, you need to select AzureAD Users. It might also work externally, but the user needs to exist in AzureAD to apply the MAM policy. Please let me know if you need anymore help.

**Comment by mypil** [comment]
@pedrr - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by Reeced40. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
