### ISSUE TITLE
School pc setup: Guest account disappears 

### ISSUE THREAD

**Issue by Bozzl** [MicrosoftDocs/windows-itpro-docs#1487]
When I create a guest account with school pc (or even WCD), the guest account disappears...
First login I can choose user or guest, next login only users is available.
We need this guest account for the youngest kids.
Can you help me out?

**Comment by egallagh** [comment]
Can you explain what it is that you are trying to accomplish by using a guest account?

**Comment by Bozzl** [comment]
Hi

As I said, that account would be used by the youngest kids in our schools.

Van: Ed Gallagher <notifications@github.com>
Verzonden: maandag 20 augustus 2018 3:30
Aan: MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>
CC: Luk Van den Bossche <luk@olvts.be>; Author <author@noreply.github.com>
Onderwerp: Re: [MicrosoftDocs/windows-itpro-docs] School pc setup: Guest account disappears (#1487)


Can you explain what it is that you are trying to accomplish by using a guest account?

**Comment by egallagh** [comment]
I understand that. My question is what are you trying to accomplish by doing that? What is the reasoning?

**Comment by OftKilted** [comment]
@bozzl Is there group policy interacting with Guest accounts on the local system? 

The behavior sounds like it is matching the symptom. 

Or interacting with members of Guest Users on the local system.

**Comment by Bozzl** [comment]
No gpo’s as a school pc setup or provisioning package starts from an usb-stick

Van: OftKilted <notifications@github.com>
Verzonden: maandag 20 augustus 2018 19:09
Aan: MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>
CC: Luk Van den Bossche <luk@olvts.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [MicrosoftDocs/windows-itpro-docs] School pc setup: Guest account disappears (#1487)


@Bozzl<https://github.com/Bozzl> Is there group policy interacting with Guest accounts on the local system?

The behavior sounds like it is matching the symptom.

Or interacting with members of Guest Users on the local system.
