### ISSUE TITLE
LTI may fail if you follow the guide

### ISSUE THREAD

**Issue by PKGeorgiev** [MicrosoftDocs/windows-itpro-docs#1490]
If the MDT_BA account is not member of Administrators (or Domain Admins) LTI will fail. The reason is that the deployment share has share permissions: Administrators - Full Control. According to the guide MDT_BA is a simple user. To fix the issue one should add MDT_BA with at least read permissions at *share level* of the deployment share folder. Please update the guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0eb8c97-caa0-bb05-4b91-14ad2adc4aac
* Version Independent ID: 0cc541a3-8198-c029-d795-308e673ee2f4
* Content: [Create a Windows 10 reference image (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image)
* Content Source: [windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by nenonix** [comment]
@PKGeorgiev Thank you for helping to improve the content, I will work on this and post back here when changes are made.

**Comment by mypil** [comment]
@ojrb - As discussed, please work on this issue. Thank you.

**Comment by ojrb** [comment]
Working on it @mypil

**Comment by ojrb** [comment]
Hi @mypil the PR #3927 solved this issue ! Please review and Merge !

**Comment by greg-lindsay** [comment]
See https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image#configure-permissions-for-the-deployment-share 

These are the instructions for configuring permissions.

**Comment by mypil** [comment]
@PKGeorgiev - Thank you for submitting feedback.

From our understanding, the issue has been answered by greg-lindsay. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
