### ISSUE TITLE
Be practical

### ISSUE THREAD

**Issue by RolandLeFranc** [MicrosoftDocs/windows-itpro-docs#1491]
How do you set these policies on a practical level?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d2e7001-2014-c6a1-99ca-26b51950d4e3
* Version Independent ID: e9683068-96ac-500b-a068-32f98415933b
* Content: [Network access Sharing and security model for local accounts (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-sharing-and-security-model-for-local-accounts)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-access-sharing-and-security-model-for-local-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/network-access-sharing-and-security-model-for-local-accounts.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by egallagh** [comment]
What do you mean by "practical level"?
The section under "Policy Management" describes the use of Group Policy to control the settings.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by VLG17** [comment]
@RolandLeFranc As described in the article, you can set to the policy to Classic, Guest only or Not defined under Computer Configuration\Windows Settings\Security Settings\Local Policies\Security Options.

If you feel this information is not enough, please propose what should be added to it. Thanks in advance for helping!

**Comment by nam31** [comment]
@RolandLeFranc  Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
