### ISSUE TITLE
References to Server 2016 out of date

### ISSUE THREAD

**Issue by crompto** [MicrosoftDocs/windows-itpro-docs#1493]
Hi, the page at https://docs.microsoft.com/en-us/windows/deployment/update/waas-optimize-windows-10-updates has out-of-date info.

It refers to "Windows Server 2016 Technical Preview", however Windows Server 2016 has been out of Technical Preview for over 2 years now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61166e35-1ee0-3216-30d2-d1075e4a36c3
* Version Independent ID: de724ab5-ef94-bea1-9095-61a684a1f2a3
* Content: [Optimize update delivery for Windows 10 updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-optimize-windows-10-updates)
* Content Source: [windows/deployment/update/waas-optimize-windows-10-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-optimize-windows-10-updates.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by shortpatti** [comment]
Fixed and merged in #[1494](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/1494/files).
