### ISSUE TITLE
Link to enterprise store is not work

### ISSUE THREAD

**Issue by HaoHoo** [MicrosoftDocs/windows-itpro-docs#1495]
https://go.microsoft.com/fwlink/p/?LinkID=722910

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 4043626d-5475-cd46-e107-6077ff4701f7
* Version Independent ID: 59ffa7ff-97ca-2f34-3c92-a09ab10c0a4e
* Content: [使用 System Center Configuration Manager (Windows 10) 创建和部署 Windows 信息保护 (WIP) 策略](https://docs.microsoft.com/zh-cn/windows/security/information-protection/windows-information-protection/create-wip-policy-using-sccm)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-sccm.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/information-protection/windows-information-protection/create-wip-policy-using-sccm.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @OfficeGlobal

**Comment by mypil** [comment]
@OfficeGlobal - Do you have any updates on this issue? Kindly assist with this Translation (Localization) issue. Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@dongmicro - Can you assist with this Translation (Localization) issue?

Thank you.

**Comment by Justinha** [comment]
@mypil I submitted a fix on my side, ETa to publish is Monday morning. I just replaced the fwlink with a direct link to the Store for business at https://businessstore.microsoft.com/store

**Comment by Mark7even** [comment]
Any downsides to deploying WIP via SCCM vs. Intune? or full parity?

**Comment by mypil** [comment]
@HaoHoo - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot add label localization

**Comment by mypil** [comment]
@officedocsbot close
