### ISSUE TITLE
About GP Configure Automatic Updates Option 3

### ISSUE THREAD

**Issue by MsJinWong** [MicrosoftDocs/windows-itpro-docs#1496]
Hi, 
I established a client win10 and WSUS server. Approved cumulative updates in WSUS. It seems win10 1803 will auto download and install, then notify to restart even i have conifgured option 3. Checked registry, its value is 3. Is this the new feature of win10?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efb8dfd-971e-7257-f8b7-f80843989eb8
* Version Independent ID: d7808728-bb89-a06e-a103-ec1c74682f64
* Content: [Manage additional Windows Update settings (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-wu-settings#configure-automatic-updates)
* Content Source: [windows/deployment/update/waas-wu-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-wu-settings.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by MsJinWong** [comment]
Sorry, i made a mistake, i set option 4, then win10 1803 install immediately and notify to restart.

**Comment by DaniHalfin** [comment]
@jaimeo should be able to help out here (@andreabichsel \ @shortpatti - please re-assign. Thanks :) )

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam
