### ISSUE TITLE
Implementing start layout xml files on windows 10 domain machine using GPMC

### ISSUE THREAD

**Issue by melon2** [MicrosoftDocs/windows-itpro-docs#1497]
I have read, understood and followed all instructions here:
https://docs.microsoft.com/en-us/windows/configuration/customize-and-export-start-layout

The requirement is to make and apply two different xml startup files for two levels of user called:
User1 
User2 
within the domain.

The startup xml file for User1 works fine. However when the **different** startup xml file for User2 is applied the results are unpredictable with Start Tiles displaying incorrectly.. most of them being missing in fact.

New users accounts have been used to test issue so presumably it can't be anything to do with existing local profiles on the machine..

Reading the **gpreport.html** the group policies appear to be have applied OK.

Any solutions would be appreciated. Thank you

**Comment by jdeckerms** [comment]
@melon2 What is different between the two XML files?

**Comment by melon2** [comment]
thanks for replying the difference is that one xml file is designed to pin just three programs to the Start Tiles area and the second xml file has about nine Start Tiles.  Hope this answers your question ?

**Comment by jdeckerms** [comment]
@melon2 Have you verified that the apps specified in the XML for User2 are installed on the device? And also that User2 has read permissions to the location of the Start XML file?

**Comment by melon2** [comment]
hi @jdeckerms thanks yes definitely the Apps are installed on the machine.  The location of the xml file is as per Microsoft, advise ie in a local directory on the machine, not sure whether User2 needs to read the xml file?.. err please explain ? thanks

**Comment by jdeckerms** [comment]
@melon2 I just meant that User2 had read permissions to the network location of the file, but since it's in a local directory, never mind. :)

If you sign on as User2, can you run the apps that aren't showing up on the Start menu?

**Comment by e0i** [comment]
@melon2 From our understanding the issue has been resolved. Feel free to re-open the issue if you feel if it hasn't been resolved. Thanks.


@AndreaBarr The issue can be closed. Thanks.

**Comment by e0i** [comment]
@AndreaBarr The issue can be closed. Thanks.
