### ISSUE TITLE
When the Bill Gates Legover Edition might be unwelcome

### ISSUE THREAD

**Issue by jg2712** [MicrosoftDocs/windows-itpro-docs#1498]
Each time I hear LTSB/C discussed by Microsoft engineers it is treated with something akin to disdain: "Why would you want an operating system which doesn't get new features?" Here's an answer: time.
It is supposed to be used for critical applications, although these are not defined. Perhaps they mean cashpoints, assuming they ever get off Windows XP. Well, in the NHS, we have some critical applications of our own and they are the ones used by doctors to treat you. "Yes, you do seem a little purple in the face, and I appreciate that you feel like Giant Haystacks has just sat on your chest, but would you mind awfully coming back tomorrow when my PC has finished installing the latest features, about which I neither know nor care?"
By definition, a clinical application can be defined as a critical application and the idea that machines which run these applications could simply get security updates and nothing else is very appealing, especially when you consider the time it can take to install these features. And who has time to test all possible applications every few months?
As a techie at heart, I like the idea of new features but as someone whose primary responsibility is ensuring that healthcare professionals can actually do their job instead of sitting and waiting for the Legover Edition to install on their machines, anything other than LTSC is just a nuisance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08436cb0-d0b6-0961-9e57-291b24d73644
* Version Independent ID: 36264f52-d3ac-4e50-f8e8-b09d6b210490
* Content: [Windows 10 upgrade paths (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-upgrade-paths)
* Content Source: [windows/deployment/upgrade/windows-10-upgrade-paths.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/windows-10-upgrade-paths.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by Dansimp** [comment]
Appreciate your feedback here. It's not an easy task balancing stability with features and updates. But this GitHub issue platform is for specific documentation issues. For product feedback, please use the Windows Feedback Hub. Thank you.
