### ISSUE TITLE
Cloud vs Hybrid vs On-Premises

### ISSUE THREAD

**Issue by tsiddle** [MicrosoftDocs/windows-itpro-docs#1500]
Can we provide some clarity in this document as to what we mean by Cloud/Hybrid/On-Premises deployments.

I *think* what we mean by these is where the identity is sourced, not necessarily the device join state:

Cloud -&gt; Identity in Azure AD only (Born in the cloud organisation) -&gt; AAD Joined devices. Will never access on-premises AD joined resources.
Hybrid -&gt; Identity in On-Premises AD, Synchronised via AAD Connect or similar to Azure AD. Devices either AD joined, AAD Joined, or Hybrid Joined (or mix thereof) -&gt; May access on-premises resources too with sight of a domain controller
On-Premises -&gt; Identity in On-Premises AD only. Windows 10 devices joined to AD only (on-prem resources only)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e5f5f1-16cf-57e2-bdfc-b090d90437b1
* Version Independent ID: 1662c47f-12cb-147d-25f0-dee98b6c7722
* Content: [Windows Hello for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-identity-verification.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-identity-verification.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by MikeStephens-MS** [comment]
FIXED!!
We already have this in our planning guide but it could be better.  We will also have (in the next update) a technology page that has the buzz words and their meaning.  This is in the next update.  We need to update the planning guide, but that will not be published in the next update.

Thank you for the feedback. 
Mike
