### ISSUE TITLE
ADFS/Pass-through Auth

### ISSUE THREAD

**Issue by tsiddle** [MicrosoftDocs/windows-itpro-docs#1501]
Sorry - one more. A view of where Pass-through auth can be used, as this seems to be our 'go-to' solution now when looking to get customers to cloud services.

Seems to be in the wider deployment guide - Hybrid AADJ Key-Trust seems to support PTA, Certificate Trust doesn't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e5f5f1-16cf-57e2-bdfc-b090d90437b1
* Version Independent ID: 1662c47f-12cb-147d-25f0-dee98b6c7722
* Content: [Windows Hello for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-identity-verification.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-identity-verification.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by MikeStephens-MS** [comment]
PTA has not officially been tested with WHFB, so its uncertain what would or work not work.  In theory, I believe key trust should work( again not tested), and given that PTA would only be used for the initial sign-in to bootstrap provisioning.  Afterwards, the client would authenticate to Azure directly. So, I hypothesize that key-trust should work, but it has not been tested and therefore not in the deployment guidance (we are investigating).  Certificate trust is another story that I'm not sure would work (it too is under investigation).

Mike
