### ISSUE TITLE
The implications of encryption and backups

### ISSUE THREAD

**Issue by domyorker** [MicrosoftDocs/windows-itpro-docs#1504]
Please add a section to discuss how encrypting a drive impacts backups. For example, what happens if pre-encryption backups exist...can a non-encrypted backup be restored to a now encrypted drive? Any impact to an existing backup set when switching to encryption?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a2b6bec-05af-1e20-a22e-d2a0c71a7dca
* Version Independent ID: 5c644e57-ae1b-a510-ebdb-52391fb6407f
* Content: [BitLocker frequently asked questions (FAQ) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-deployment-and-administration-faq)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-deployment-and-administration-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-deployment-and-administration-faq.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by VLG17** [comment]
@domyorker could you please provide more information about the way you do the backup, especially if you're using Windows Backup or something else.

You can restore a non-encrypted backup to an encrypted drive - what will happen is that you will need to re-encrypt the drive after restore.

**Comment by mypil** [comment]
@domyorker - We would like to follow up. Can you please respond to the query of VLG17? Thanks.

**Comment by mypil** [comment]
@domyorker - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
