### ISSUE TITLE
Example is incorrect for Wifi

### ISSUE THREAD

**Issue by dbdmora** [MicrosoftDocs/windows-itpro-docs#1506]
The value for wifi is network-wifi in at least 1709 or greater builds of win10. Please change this so it reflects the correct info to end users.
This is where I found the correct value for WiFi visibility and it is working for me.
https://www.tenforums.com/tutorials/78214-settings-pages-list-uri-shortcuts-windows-10-a.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502b34cb-f410-94eb-80c0-87729cd29fb9
* Version Independent ID: 34336fed-e0f4-85bb-32e5-c41020037c1f
* Content: [Policy CSP - Settings](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-settings)
* Content Source: [windows/client-management/mdm/policy-csp-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-settings.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by MariciaAlforque** [comment]
Fixed the topic. Thanks for the feedback
