### ISSUE TITLE
Apply ProfileXML using Intune

### ISSUE THREAD

**Issue by Markt1891** [MicrosoftDocs/windows-itpro-docs#1507]
"Apply ProfileXML using Intune" section has incorrect example OMA-URI.  It should be ./user/vendor/MSFT/VPNv2/VPN profile name/ProfileXML

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79add4e0-6997-5b15-542c-be3f1c2b1baf
* Version Independent ID: 47bd5f53-cd36-3205-42b1-6d99c68e9b39
* Content: [VPN profile options (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-profile-options)
* Content Source: [windows/security/identity-protection/vpn/vpn-profile-options.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/vpn/vpn-profile-options.md)
* Product: **w10**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@Markt1891, thank you for catching.  I've have fixed the example OMA-URI and it will be published later today.
