### ISSUE TITLE
Configure kiosk account and app error

### ISSUE THREAD

**Issue by rysavfi1** [MicrosoftDocs/windows-itpro-docs#1514]
I'm trying to follow "[Set up a kiosk using the kiosk wizard in Windows Configuration Designer](https://docs.microsoft.com/cs-cz/windows/configuration/kiosk-single-app#set-up-a-kiosk-using-the-kiosk-wizard-in-windows-configuration-designer)" and I'm stuck at "Configure kiosk account and app" step.

"Finish" step informs me about validation errors and so I click the yellow icon in "Configure kiosk account and app" step. I don't see any errors or red text in this step. Is there a way to find out what is wrong? I can provide you with additional information if you specify them.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: f8f49c3f-ba5c-49e9-fad2-88cac155920a
* Version Independent ID: dc5e1f7e-61a8-bf2c-34b8-4046d024f4c2
* Content: [Set up a single-app kiosk (Windows 10)](https://docs.microsoft.com/cs-cz/windows/configuration/kiosk-single-app#set-up-a-kiosk-using-the-kiosk-wizard-in-windows-configuration-designer)
* Content Source: [windows/configuration/kiosk-single-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-single-app.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by rysavfi1** [comment]
![img1](https://user-images.githubusercontent.com/17282242/44462266-65aa0c80-a614-11e8-9209-37df2d2e530b.png)
![img2](https://user-images.githubusercontent.com/17282242/44462267-65aa0c80-a614-11e8-95fc-776dd8cd7d3e.png)

**Comment by jdeckerms** [comment]
@rysavfi1 I ran through the kiosk wizard and used the same settings that you have, and it validated. However, I was using the desktop version of WCD (from the ADK at https://go.microsoft.com/fwlink/?linkid=873065). If I use the Microsoft Store version of WCD, I have the same experience as you. 

If you would, please submit your experience in the Feedback Hub, attaching both of your screenshots, so the engineering team can be notified of the problem, and specify in your feedback that you're using the Microsoft Store version of Windows Configuration Designer. 

You can install the desktop version of WCD to complete your package. (https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-install-icd#install-windows-configuration-designer-1)

**Comment by rysavfi1** [comment]
I have experienced the error using the Microsoft Store version. I have no validation errors using the desktop version. Thanks.

**Comment by HunterDG** [comment]
This issue still exists on Windows 10 1803

**Comment by yosefsun** [comment]
Issue exists on windows 10 Home v. 1709

**Comment by gatornation11** [comment]
issue exists on windows 10 enterprise 1809.

**Comment by Marctwain-Marcellos** [comment]
Same issue using Store version of WICD 2019.314.0.0

**Comment by cadlebe** [comment]
Same issue on windows 10 Pro 1903

**Comment by duel007** [comment]
I have this issue on 1903.

**Comment by i-m-wisch** [comment]
In the latest version it gives details on the error, but it looks to me like a bad regex to filter the input. The regex is: `^[^\\\\]+$`

This will filter out any drive paths
