### ISSUE TITLE
Do shell extensions really require a global publish?

### ISSUE THREAD

**Issue by RSCobb8142** [MicrosoftDocs/windows-itpro-docs#1515]
According to this document:
Requirements for using shell extensions
Packages that contain embedded shell extensions must be published globally. The application requires no additional setup or configuration on the client to enable the shell extension functionality.

However, in my environment I see that when Notepad++ is deployed to an SCCM user collection, the right-click shell extension to "Open with Notepad++" is available.  I see this in the registry as well HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\AppV\Client\Packages\1DB8E2DE-6921-43FA-AEDE-BBF6FC3DDBF3\Versions\4480CD31-5C9D-4776-9685-3EA44BF8A1E8\REGISTRY\MACHINE\SOFTWARE\Classes\*\shellex\ContextMenuHandlers\ANotepad++64.

Has there been a change to the way shell extensions are handled in Win10 1607+?  Any other functionality that may be different in addition to shell extensions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 295453ec-f5db-01b6-ef31-9759d8ad26a0
* Version Independent ID: 71e26e47-ceae-f540-1f47-fdc92e2265d7
* Content: [Creating and managing App-V virtualized applications (Windows 10)](https://docs.microsoft.com/en-us/windows/application-management/app-v/appv-creating-and-managing-virtualized-applications)
* Content Source: [windows/application-management/app-v/appv-creating-and-managing-virtualized-applications.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/app-v/appv-creating-and-managing-virtualized-applications.md)
* Product: **w10**
* GitHub Login: @MaggiePucciEvans
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
Hello @RSCobb8142 , Thank you for your query, please note you need to ensure that package is same bit by bit that means if you are creating a package for the 64bit app, it should be created on 64bit OS and should be deployed on 64bit OS. You can see other support shell extensions features at https://docs.microsoft.com/en-us/windows/application-management/app-v/appv-creating-and-managing-virtualized-applications#requirements-for-using-shell-extensions

Thanks.

**Comment by mypil** [comment]
@RSCobb8142 - Thank you for submitting feedback.

From our understanding, the issue has been answered by joinimran. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
