### ISSUE TITLE
Hyperlink typo?

### ISSUE THREAD

**Issue by GrahamMcKendry** [MicrosoftDocs/windows-itpro-docs#1516]
Within the section _'Deploy the compatibility update and related updates'_ the last paragraph references KB3080149, however the paragraph lists and links to a different KB: "For more information about this update, see https://support.microsoft.com/kb/3150513". Should this line say "For more information about this update, see https://support.microsoft.com/kb/3080149"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4273a259-c3c7-dca7-6353-954068d740a7
* Version Independent ID: 1084ea77-95c4-4e4a-da6c-f4d8668f9ebf
* Content: [Enrolling devices in Windows Analytics (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started#feedback)
* Content Source: [windows/deployment/update/windows-analytics-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-get-started.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mypil** [comment]
-checked and found that the link has been updated to point to the correct KB3080149.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
