### ISSUE TITLE
Links to parts 1,2,3,5,6 point to the wrong guide. 

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/windows-itpro-docs#1517]
It looks like in the links at the end of this document, under "Follow the Windows Hello for Business Hybrid key trust deployment guide", all of the links except for #4 (Configure Directory Synchronization) point to the Certificate trust version of the guide, not the Key trust version.  
For Example, #2 (Prerequisites) points to:
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs

It should point to: 
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d45db5-5172-45cb-2c4d-d73a9e15d699
* Version Independent ID: fa08e81d-3307-514e-129a-843e812e97a9
* Content: [Hybrid Windows Hello for Business key trust Provisioning (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by MikeStephens-MS** [comment]
FIXED!!!
Good catch -- You should see this fixed in our next update toward the end of this week (we just published an major update where this is not fixed).  Thank you for the report and keeping us honest :)

**Comment by mypil** [comment]
@NeighborGeek - From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
