### ISSUE TITLE
Appears ti wipe out previous provisioning steps

### ISSUE THREAD

**Issue by csando** [MicrosoftDocs/windows-itpro-docs#1518]
As far as I can tell it runs the "reset this pc" procedure after it has done some other provisioning steps.  So, kind of useless in that regard.  Anyone else seeing this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f38c1219-3096-f435-13ae-1c325f9d2b82
* Version Independent ID: 8f0002e6-00e0-eb00-b6b9-dcd16034c949
* Content: [CleanPC CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/cleanpc-csp)
* Content Source: [windows/client-management/mdm/cleanpc-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/cleanpc-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by archmiguel** [comment]
Yes, I see this as well.   And there is little to no documentation on how this works behind the scenes, leaving admins to lots of trial and error.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by Reeced40** [comment]
@csando @archmiguel Thank you for pointing this out, is there anything you can suggest to add to the article or should I have the team look into this?

**Comment by mypil** [comment]
@csando @archmiguel - We would like to follow up. Can you please assist to respond to the query of Reeced40?

**Comment by mypil** [comment]
@csando @archmiguel - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by csando** [comment]
> 
> 
> @csando @archmiguel Thank you for pointing this out, is there anything you can suggest to add to the article or should I have the team look into this?

Hey sorry it's been awhile.
Well, in the documentation should probably say that the "remove preinstalled software" option actually resets the whole PC and is a binary option (IE, using it will render all the other options useless).
In Windows configuration designer itself it even makes it seem like it is just going to remove preinstalled software as part of the deployment.
