### ISSUE TITLE
IEDataOptIn

### ISSUE THREAD

**Issue by adamgourd** [MicrosoftDocs/windows-itpro-docs#1536]
It would be helpful to have some mention of the IEDataOptIn registry setting that specifically governs the collection of IE browsing data. IEDataOptIn is described here: https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started. Nonetheless, I think it's important to have in this article as well, since there does not appear to be any other information here regarding browsing history and how to control it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c364e-fcf4-8667-17d7-f9a3ec71e1a9
* Version Independent ID: f98f8870-d594-f5df-f6b6-44c9806db7d8
* Content: [Configure Windows diagnostic data in your organization (Windows 10)](https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization)
* Content Source: [windows/privacy/configure-windows-diagnostic-data-in-your-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/configure-windows-diagnostic-data-in-your-organization.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
Hi @adamgourd and thanks for reaching out.
Seemingly the IEDataOptIn is specific to WA data collection, and so not in scope of this topic. I will make sure of that and will reply back.

**Comment by mypil** [comment]
@DaniHalfin - Do you have any updates on this? Has this issue been fixed? Please advise. Thank you.

**Comment by DaniHalfin** [comment]
Hi again @adamgourd ,
We are planning on refreshing this content later this year, so the content surfaced here might change, and we'll take your comment into consideration. However, currently, IEDataOptIn is indeed out considered out of scope for this topic.

Issue can be closed.

**Comment by mypil** [comment]
@officedocsbot close
