### ISSUE TITLE
windows 10

### ISSUE THREAD

**Issue by muhamdali11000** [MicrosoftDocs/windows-itpro-docs#1538]
[اكتب ملاحظاتك هنا]

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ docs.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: 8b398a57-ce65-1f1f-1e3e-997b15157df3
* Version Independent ID: 13ee70cf-57de-a377-7c61-212ff436e7dc
* Content: [Set up School PCs app technical reference overview](https://docs.microsoft.com/ar-sa/education/windows/set-up-school-pcs-technical)
* Content Source: [education/windows/set-up-school-pcs-technical.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/set-up-school-pcs-technical.md)
* Product: **w10**
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by andreabichsel** [comment]
Closing for now. Please let us know if you have an issue with the topic. Thank you!
