### ISSUE TITLE
0x80090016 mitigation broken

### ISSUE THREAD

**Issue by mattpharris** [MicrosoftDocs/windows-itpro-docs#1540]
I am received this error code at sign-in, out of the blue, on my 2 month old HP laptop. I had to use passwords to reach the PC desktop. I then went into Sign-in Options, and removed my old PIN. When attempting to set up a new PIN, I again received this same error code. I was directed to this website, but the mitigation for this error code (and seemingly others) doesn't open to a useful page. My browser is Google Chrome. Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by csfarley** [comment]
I'm having the same exact issue on my 3 day old HP laptop. Issue started after some HP updated were downloaded and installed.

**Comment by jvgjvg77** [comment]
Hi, i'm having the same issue when trying to login in the microsoft to do windows (store) app, when logged in the domain not possible to login, when logged on local, no problem.

**Comment by DaniHalfin** [comment]
Hi everyone,
Please reach out to support to collect event logs and help resolve this issue.
We'll work to include additional error codes in future revisions of this topic.

Thanks.

**Comment by pmknowles** [comment]
![image](https://user-images.githubusercontent.com/37398451/48772862-89392d80-ecbd-11e8-9df0-3c7932ff0522.png)
I'm having the same issue on Windows 10 Home. PIN stopped working can only log in using password. Intel Z83 micro PC so not HP issue

**Comment by yoryimer17** [comment]
el mismo problema estoy presentando en mi Lenovo ideapad 330s. Gracias por alguna solución.

**Comment by e0i** [comment]
Hello, @mattpharris  thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

You might also keep us informed about the resolution of your ticket so that we can ensure this documentation is up to date with relevant information.

**Comment by e0i** [comment]
@officedocsbot close
