### ISSUE TITLE
Can I use MDT for this?

### ISSUE THREAD

**Issue by aperezny** [MicrosoftDocs/windows-itpro-docs#1543]
It appears SCCM is only used for the deployment of the scripts, can the same be accomplished with MDT?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ac548b-be6c-efba-76ee-67dd7af18891
* Version Independent ID: 947b62e7-1225-2f5e-14ba-fe5dccbbe124
* Content: [Use System Center Configuration Manager to manage devices with SEMM (Surface)](https://docs.microsoft.com/en-us/surface/use-system-center-configuration-manager-to-manage-devices-with-semm?ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-96qhCBM6WOwOCc6bFSk6Pg&epi=je6NUbpObpQ-96qhCBM6WOwOCc6bFSk6Pg&irgwc=1&OCID=AID681541_aff_7593_1243925&tduid=(ir_W35RAby6e1vX1S0S49yMSQddUkg0JuRupTvizQ0)(7593)(1243925)(je6NUbpObpQ-96qhCBM6WOwOCc6bFSk6Pg)()&irclickid=W35RAby6e1vX1S0S49yMSQddUkg0JuRupTvizQ0)
* Content Source: [devices/surface/use-system-center-configuration-manager-to-manage-devices-with-semm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/use-system-center-configuration-manager-to-manage-devices-with-semm.md)
* Product: **w10**
* GitHub Login: @KiranDavane
* Microsoft Alias: **jdecker**

**Comment by chiners68** [comment]
Yes, MDT will be able to deploy these scripts in the same method as SCCM.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @aperezny 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
Hello, @- 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
