### ISSUE TITLE
XML code blocks show raw markdown instead of copy-and-pasteable code.

### ISSUE THREAD

**Issue by ThubLives** [MicrosoftDocs/windows-itpro-docs#1545]
Code blocks should contain raw xml code snippets, but they appear to be in markdown, showing angle brackets as `&lt;` and `&gt;`.  For example:
```
&lt;Shortcut&gt;

  &lt;File&gt;\[{AppData}\]\\Microsoft\\Contoso\\Recent\\Templates.LNK&lt;/File&gt;

  &lt;Target&gt;\[{AppData}\]\\Microsoft\\Templates&lt;/Target&gt;

  &lt;Icon /&gt;

  &lt;Arguments /&gt;

  &lt;WorkingDirectory /&gt;

  &lt;AppUserModelId /&gt;

  &lt;Description /&gt;

  &lt;Hotkey&gt;0&lt;/Hotkey&gt;

  &lt;ShowCommand&gt;1&lt;/ShowCommand&gt;

  &lt;!-- Note the ApplicationId is optional --&gt;

&lt;/Shortcut&gt;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a761d98-2b6f-af69-7c49-deff27a03d92
* Version Independent ID: 69a558ef-8bb2-029f-465f-9aa8e2f4b59d
* Content: [About App-V 5.1 Dynamic Configuration](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/appv-v5/about-app-v-51-dynamic-configuration)
* Content Source: [mdop/appv-v5/about-app-v-51-dynamic-configuration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/appv-v5/about-app-v-51-dynamic-configuration.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by shortpatti** [comment]
@ThubLives,  Thank you for bringing the formatting issue to our attention.  I'm in the process of fixing it so that the topic can be easily scanned.

**Comment by shortpatti** [comment]
The formatting has been fixed and will be published later today.
