### ISSUE TITLE
Spotlight for Enterprises

### ISSUE THREAD

**Issue by FabianNiesen** [MicrosoftDocs/windows-itpro-docs#1548]
How are Spotlight for Enterprises in Azure configured?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0286c17f-aca8-c9bc-597c-86b70165c72e
* Version Independent ID: be2bdcde-8667-4ff5-c4e5-bd50696d9341
* Content: [Configure Windows Spotlight on the lock screen (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/windows-spotlight)
* Content Source: [windows/configuration/windows-spotlight.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/windows-spotlight.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
Hi @FabianNiesen I think you're referring to the checkbox option "Include content from Enterprise Spotlight" in the "Configure Spotlight on lock screen" Group Policy. That checkbox is in place for a feature that the product team is considering for a future release. It does nothing right now.

**Comment by FabianNiesen** [comment]
Yes, that is what I mean. In this policy setting, it sounds, that there is already something. And I was wondering why I can't find anything about this.

**Comment by jdeckerms** [comment]
It isn't documented because it's not available yet. The checkbox has been in the policy since Windows 10, version 1607, but I don't know when (or if ever) that will be available to enterprise customers.

**Comment by FabianNiesen** [comment]
I have understood. But then remove this setting from the GPO, before it crates more confusion at the customers.
