### ISSUE TITLE
Definition of what is considered Critical vs non-critical

### ISSUE THREAD

**Issue by CCDFischer** [MicrosoftDocs/windows-itpro-docs#1549]
Is there any place where the difference between the two types of notifications are defined? What is considered a critical notification? It is unclear from the documentation exactly what notifications will be allowed by the "Hide Non-Critical Notifications" policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65d57fa8-9c9b-63cc-7248-175242963432
* Version Independent ID: 9cd96c93-8f46-64db-a162-02da1e1f63cc
* Content: [Hide notifications from the Windows Defender Security Center app](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications)
* Content Source: [windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@CCDFischer - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@CCDFischer in my opinion the easiest way to understand what is critical and what is not is to check the Security Log (and Application Log) under Event Viewer -> Windows Logs in Windows 10.

@bitslacker i will request a change to address that. Thank you for your feedback!

**Comment by CCDFischer** [comment]
@VLG17 While you may be able to find that information in the event viewer, it is not documented anywhere what the difference is between these categories of notifications. As this is the documentation for the product I would expect to find at least an explanation if not an exhaustive listing here of what each category is. The point of documentation is that I should not need to discover this information through trial and error or log searching when clearly it is defined somewhere within MS. As such my request stands, please add in a section that at least explains what the types of alerts, and include examples if possible to make it easier for me and others to go to management and show them what will bee allowed and blocked with the difference GPO settings.

**Comment by mypil** [comment]
@dansimp - Can you please share your insights on this issue?

Thank you.

**Comment by mypil** [comment]
@Dansimp - We would like to follow up on this. Do you have any updates?

Thank you.

**Comment by mypil** [comment]
@Dansimp - We would like to follow up on this. Can you please share your insights on this issue?

Thank you.

cc: @AndreaBarr

**Comment by mypil** [comment]
@CCDFischer - The latest progress on the status is that the doc owner informed us that this topic will be updated.  Thank you.

cc: @Dansimp @AndreaBarr

**Comment by martyav** [comment]
We've addressed this with a PR in the private version of the repo. I recently added to the page a table listing which notifications are considered critical/non-critical -- it should go live soon.

**Comment by mypil** [comment]
@CCDFischer - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
