### ISSUE TITLE
(Solved) Raw-mode is unavailable courtesy of Hyper-V. (VERR_SUPDRV_NO_RAW_MODE_HYPER_V_ROOT)

### ISSUE THREAD

**Issue by DuggerConsulting** [MicrosoftDocs/windows-itpro-docs#1556]
Important steps missing to disable Hypervisor when Windows Defender - Credential Guard previously enabled...

First: If Bitlocker is running - launch "Manage Bitlocker" and suspend anytime you are dealing with security or BIOS updates! Also make sure you have an external copy of the Bitlocker recovery key - since it comes in handy if you ever get locked out...

Second: After spending a few hours trying to get a VM running on my PC, I found Hypervisor was still in use by Secure Boot, preventing me from installing a new VM OS, so the bcedit step did nothing to help get past the following VM error:

Error: Raw-mode is unavailable courtesy of Hyper-V. (VERR_SUPDRV_NO_RAW_MODE_HYPER_V_ROOT).

Prior to Step #3 (bcdedit's) - YOU MUST GO INTO THE BIOS AND TURN OFF "SECURE BOOT" & SAVE / REBOOT

Once I turned off Secure Boot and ran Step #3 (bcdedit's), System Information:  Virtual-based Security = "Not Enabled"

VMWare installation proceeded as it should and I was finally able to install the VM OS.

Update:

Noticed Secure Boot was not enabled as I thought, but when I enabled, it was still preventing my VM from starting...

Something was still active that I missed and it wasn't until I reran the Device Guard Readiness Tool and noticed the "-disable" option, which I ran from an elevated PowerShell window, this finally turned off what I had spent time enabling previously. Enabling Device Guard had prevented me from setting up a VM and it needed to be completely disabled as follows:

Command: DG_Readiness_Tool_v3.4.ps1 -disable

Get Device Guard Readiness Tool here: https://www.microsoft.com/en-us/download/details.aspx?id=53337

Best Regards,

Craig Dugger

Microsoft Windows 10 Pro
10.0.17134 Build 17134
VirtualBox 5.2.18r124319 (Qt5.6.2)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by DaniHalfin** [comment]
Hi @DuggerConsulting , Thanks for reaching out.
To follow up on this - what part exactly do you find that's missing from the topic. Is it specifically the BIOS part? 
Using the readiness tool to disable is already in the topic under "Disable Windows Defender Credential Guard by using the Windows Defender Device Guard and Windows Defender Credential Guard hardware readiness tool".

Just want to be clear on where improvements can be made.
Thanks!

**Comment by DaniHalfin** [comment]
@DuggerConsulting this issue is now marked as solved in the title. Does this mean that you consider the issue solved?
Thanks.

**Comment by vkumar85** [comment]
This one worked for me on Windows 10

Method 2: Disable Hyper-V in PowerShell

To disable Hyper-V by using Windows PowerShell, follow these steps:

    Open an elevated PowerShell Command Prompt window.
    At the command prompt, run the following command:

    Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-Hypervisor 

https://support.microsoft.com/en-ca/help/3204980/virtualization-applications-do-not-work-together-with-hyper-v-device-g

**Comment by AmyXuHouston** [comment]
TURN OFF "SECURE BOOT" worked for me. 
THANK YOU!

**Comment by junk-erikm** [comment]
I received this same error after enabling the Windows Defender Application Guard feature. Disabling it and rebooting resolved it.

**Comment by axovel** [comment]
This will work

STEP 1:
Open the command prompt as an Administrator.

STEP 2:
Run the command with no argument: bcdedit

After you run the above command, you will see that the property hypervisorlaunchtype is set Auto by default.

STEP 3:
Disable Hyper-V by running the command: bcdedit /set hypervisorlaunchtype off

STEP 4:
Restart your PC system to use VirtualBox.

To turn Hyper-V back on, run the command: bcdedit /set hypervisorlaunchtype auto
You will need to reboot the system to use Hyper-V.

**Comment by Hayderhj** [comment]
Thank you @axovel !

**Comment by LifeWireYT** [comment]
I've done all of steps provided above and still no luck. Hypervisor has been disabled through Command Prompt and it still gives me the error. Also, I'm a noob when it comes to this sort of thing.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @DuggerConsulting and @LifeWireYT, just reaching out to confirm if your issues have been resolved. If not, there were several suggestions mentioned in this issue that may be of help. Also, please check the following:

1. [1915](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1915) - Addressed some issues like *incorrect parameter* error and recommendation to *check BIOS switches*, etc.
2. [1776](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1776) - Addressed some issues like *mountvol X: /s, incorrect parameter* error, etc.
3. Other related issues compiled by @illfated - #[1984](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1984), #[2216](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2216), #[2327](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2327), #[2569](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2569), #[2612](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2612), #[2663](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2663), #[2705](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2705), #[2880](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2880), #[2971](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2971), #[3006](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3006), #[3108](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3108), #[3300](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3300)

Helpful resources shared by the community: 
- https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#review-windows-defender-credential-guard-performance
- https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mountvol

**Important reminder:** Please be informed that this Github site is intended for product documentation. We want users to have the best Windows 10 experience by ensuring the contents of the Microsoft Docs are useful, accurate and up-to-date, hence, if there is anything we need to add or edit in the documentation, please let us know and we'll have it reviewed. Thank you.

**Comment by jvsam** [comment]
Hi again @DuggerConsulting and @LifeWireYT we haven't heard or received any updates from you. We are hoping the suggestions and information shared here assisted in reaching the resolution of the issues you've raised. For now, we will close this issue, however, feel free to re-open if there is missing information or if you have suggestions to improve the quality of this documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by GabhanOLoughlin** [comment]
> 
> 
> This will work
> 
> STEP 1:
> Open the command prompt as an Administrator.
> 
> STEP 2:
> Run the command with no argument: bcdedit
> 
> After you run the above command, you will see that the property hypervisorlaunchtype is set Auto by default.
> 
> STEP 3:
> Disable Hyper-V by running the command: bcdedit /set hypervisorlaunchtype off
> 
> STEP 4:
> Restart your PC system to use VirtualBox.
> 
> To turn Hyper-V back on, run the command: bcdedit /set hypervisorlaunchtype auto
> You will need to reboot the system to use Hyper-V.

This was the only thing that worked for me (using the latest Windows 10 updates). Thanks a million!!
