### ISSUE TITLE
Registry path

### ISSUE THREAD

**Issue by TonyLongsonFJ** [MicrosoftDocs/windows-itpro-docs#1558]
Please can you add the registry path for this setting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 744990d3-6fb4-a085-de18-b0894c2dbda5
* Version Independent ID: f774568c-506c-cc5f-f6b2-2452cb408667
* Content: [Network security LAN Manager authentication level (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-lan-manager-authentication-level)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-security-lan-manager-authentication-level.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/network-security-lan-manager-authentication-level.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@TonyLongsonFJ sorry for delay. The registry path is listed in this section: https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-lan-manager-authentication-level#registry-location
