### ISSUE TITLE
ADMX files inconsistent

### ISSUE THREAD

**Issue by MVDB1984** [MicrosoftDocs/windows-itpro-docs#1564]
Hi,
Seems the reference described here is inconsistent with the latest ADMX-files which shipped with the 1803 update.
Some additional settings are added, and the policy names are slightly different.
When will the doc be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7221f66e-63ff-2abe-4340-4d31c53fdce4
* Version Independent ID: 7db1a9b2-26c7-b005-5e21-6742a76a93d7
* Content: [Configuring UE-V 2.x with Group Policy Objects](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/uev-v2/configuring-ue-v-2x-with-group-policy-objects-both-uevv2)
* Content Source: [mdop/uev-v2/configuring-ue-v-2x-with-group-policy-objects-both-uevv2.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/uev-v2/configuring-ue-v-2x-with-group-policy-objects-both-uevv2.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by shortpatti** [comment]
@MVDB1984, sorry for the delay.  I'm gathering the information and will update it soon.  Thank you for your patience.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by nam31** [comment]
@Dansimp PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by illfated** [comment]
(ref. https://github.com/MicrosoftDocs/mdop-docs/pull/3)

**Comment by illfated** [comment]
Should be resolved now via PR https://github.com/MicrosoftDocs/mdop-docs/pull/3 

#please-close
