### ISSUE TITLE
Enterprise Mode for modern web technologies?!

### ISSUE THREAD

**Issue by git-hub-user** [MicrosoftDocs/windows-itpro-docs#1565]
quote from above: 
"Use IE11 as your primary browser and use Enterprise Mode to open sites in Microsoft Edge that use modern web technologies."
In my experience this Enterprise Mode was designed to support sites that run old technology and breaks sites that use modern web technology.
E.g. when Enterprise Mode emulates IE8 in IE11, jQuery 2.x and 3.x fail to load.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 323ba492-8b70-b9d8-1787-68e8b90a2e84
* Version Independent ID: c444fc27-4f7d-f713-cc4d-ffdb209a126e
* Content: [Enterprise Mode and the Enterprise Mode Site List (Internet Explorer 11 for IT Pros)](https://docs.microsoft.com/en-gb/internet-explorer/ie11-deploy-guide/what-is-enterprise-mode#what-is-enterprise-mode)
* Content Source: [browsers/internet-explorer/ie11-deploy-guide/what-is-enterprise-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/internet-explorer/ie11-deploy-guide/what-is-enterprise-mode.md)
* Product: **ie11**
* GitHub Login: @shortpatti
* Microsoft Alias: **shortpatti**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@git-hub-user - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @git-hub-user , @mypil 
the issue was already resolved by https://github.com/MicrosoftDocs/windows-itpro-docs/commit/7b96a237eb0948611ea6399f9e6fc2e5da0d5f96#diff-5880b60d195f11eb084e4e2876425baa

Thank you

**Comment by mypil** [comment]
@git-hub-user - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by git-hub-user** [comment]
Thanks. It has indeed been resolved, in the meantime. I submitted the issue quite some time ago.
