### ISSUE TITLE
Win 10 on Arm

### ISSUE THREAD

**Issue by LivefromRaleighwood** [MicrosoftDocs/windows-itpro-docs#1566]
Please details to include that system running Snapdragon 635 are not supported with Win 10 Pro for Arm. At the time of this POST (8/2018) - there are only 4GB ram systems in the marketplace. By the way, my Lenovo Miix 630 with 4GB is running a number of Win32/x86 with zero issue. I have been ripping DVD, playing games & no drama. But it looks like no Application Guard support - but hey I get 22 hours on battery.  :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f43df7b-6ead-de5a-2e41-4d49978ab485
* Version Independent ID: 5497d300-cb21-55f3-7e80-98bc3592635c
* Content: [System requirements for Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@LivefromRaleighwood Thanks for your comment. Windows Defender Application Guard for ARM64 is on our roadmap, but we have no specific commitment or timing to share.
