### ISSUE TITLE
Should say "Computer Configuration" GPO setting

### ISSUE THREAD

**Issue by zniezelski** [MicrosoftDocs/windows-itpro-docs#1568]
This setting is a computer settings. The document doesn't say that and it should. 

Computer Configuration\Administrative Templates\Windows Components\File Explorer\Set a default associations configuration file

**Comment by zniezelski** [comment]
Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: 7cbbc03b-78ac-4464-0ec8-d7379db167f4

**Comment by zniezelski** [comment]
URL is https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/set-the-default-browser-using-group-policy

**Comment by shortpatti** [comment]
PR 1569
