### ISSUE TITLE
Error in test command

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/windows-itpro-docs#1575]
In order for the test command to work, you must create the "test-WDATP-test" folder first.  Either add that to the script or put it in the instructions.  This needs to be updated in the WDATP portal as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1a58ecc-aa01-3b7a-c1f7-a039063c7c38
* Version Independent ID: b1b9a0ef-fd7e-96e2-730d-01158fb93eee
* Content: [Run a detection test on a newly onboarded Windows Defender ATP machine](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/run-detection-test-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/run-detection-test-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/run-detection-test-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Thank you for your feedback. Updates to the page will be reflected soon.

**Comment by JoaoCMRibeiro** [comment]
Hello,

I don't get it. Why do I need to create a folder in first place? How creating a folder will change the result of running the test command?

Why not just open a command line with elevated priviledges and run the command? 🤷‍♂️
