### ISSUE TITLE
Please add a link to the lifecycle fact sheet

### ISSUE THREAD

**Issue by ilantz** [MicrosoftDocs/windows-itpro-docs#1576]
Please consider adding a link to https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet in pages which talk about the number of months and explain when support will end for builds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34937b5e-eda3-9c93-c31b-0701ea61198a
* Version Independent ID: 36f54d9f-503d-ea0a-bff2-3441571f8d44
* Content: [Quick guide to Windows as a service (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-quick-start)
* Content Source: [windows/deployment/update/waas-quick-start.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-quick-start.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by nenonix** [comment]
@ilantz Thank you for the helpful feedback. I have submitted the added link for review.
