### ISSUE TITLE
Dose the "S mode" support the BitLocker of Micro SD card?

### ISSUE THREAD

**Issue by yoshihirok** [MicrosoftDocs/windows-itpro-docs#1578]
I want to encrypt the Micro SD card by BitLocker on Windows 10 Home - S mode of Surface Go.
When the "S mode" can encrypt the Micro SD card, Please add the description on this page,
When can NOT, Please add the description too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bfdcb45-ac06-394c-6320-252f17f0eb71
* Version Independent ID: 7236e516-fe18-a336-78b4-ff42842619b8
* Content: [Windows 10 Pro in S mode](https://docs.microsoft.com/en-us/windows/deployment/windows-10-pro-in-s-mode)
* Content Source: [windows/deployment/windows-10-pro-in-s-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-pro-in-s-mode.md)
* Product: **w10**
* GitHub Login: @MikeBlodge
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
i think, memory card can be locked by the special tool used in android /.

or  else by using a memory card manufacturer tool to lock  via password  by installed windoiws software with card reader

**Comment by e0i** [comment]
Hello, @-

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by VLG17** [comment]
@yoshihirok Surface Go with Windows 10 Home in S mode has Bitlocker, or better said Device Encryption. In order to benefit from the full Bitlocker functionality (MicroSD card encryption included) you would need to upgrade to Windows 10 (S or not) Pro/Enterprise.

![surface go](https://user-images.githubusercontent.com/41186174/63326230-775fe600-c334-11e9-9e1a-aa4306ce004b.jpg)

**Comment by e0i** [comment]
Hello @yoshihirok  ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
