### ISSUE TITLE
MBAM 3.0?

### ISSUE THREAD

**Issue by Jeff-Jerousek** [MicrosoftDocs/windows-itpro-docs#1581]
Will there be a new version of MBAM? (3.0) Or will 2.5 SP1 be the last version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e5380a-53da-6df1-1952-1be89d9b5969
* Version Independent ID: 82af0c50-fb10-3ad3-1f1d-74a068ea6fa7
* Content: [BitLocker Management Recommendations for Enterprises (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises#related-articles)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@Jeff-Jerousek MBAM 2.5 with SP1 will be the last version.
