### ISSUE TITLE
Example seems to be incorrect

### ISSUE THREAD

**Issue by PaulSIsaac** [MicrosoftDocs/windows-itpro-docs#1582]
I was discussing this with a colleague and it seems the example has an extra set of tags: &lt;groupmembership&gt;, remove these tags and this CSP works.

 &lt;accessgroup desc="Administrators"&gt;
    &lt;member name="Contoso\Alice" /&gt;
    &lt;member name = "S-188-5-5666-5-688" / &gt;
  &lt;/accessgroup&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0c28c15-f0be-d732-4d9e-cf5df5e64e8b
* Version Independent ID: 17eba45f-d200-e656-42b9-e1a512931eea
* Content: [Policy CSP - RestrictedGroups](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-restrictedgroups)
* Content Source: [windows/client-management/mdm/policy-csp-restrictedgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-restrictedgroups.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by DeanBrighton** [comment]
How can this be a closed item? It is still wrong on the documentation.
