### ISSUE TITLE
No Surface Go Driver packages

### ISSUE THREAD

**Issue by lshunnarah77** [MicrosoftDocs/windows-itpro-docs#1583]
I've been looking for the Surface Go (NOT PRO, BUT GO) Drivers as I'm trying to deploy about 40, and I can not find the driver package for our imaging process.  Anyone have any clue?  This is really putting a wrench in getting things done quickly.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586d1246-6e18-b33c-2382-52a53bb392f5
* Version Independent ID: 0ec4aa1e-aac0-98dd-0a47-83e93d854086
* Content: [Download the latest firmware and drivers for Surface devices (Surface)](https://docs.microsoft.com/en-us/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices)
* Content Source: [devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md)
* Product: **w10**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by lshunnarah77** [comment]
I found a work-around for this.  I used the PS Export-windowsdriver command and then imported the results into MDT.  The result was a fresh image with all drivers loaded.  It would be nice to have a cleaner setup and obtain an actual driver package from MS.

**Comment by bealsao** [comment]
Just adding to this, I just reimaged a surface GO to find it has no drivers available via the USB image. Checking all sites on Microsoft provide no results for the drivers for the Surface GO despite saying they're avialable.

They all lead here: https://support.microsoft.com/en-au/help/4023482/surface-download-drivers-and-firmware-for-surface

Additional frustrations occur when trying to download the recovery image from here using my serial number and the download recovery image does not work:
https://support.microsoft.com/en-us/surfacerecoveryimage
"Surface Go - 128GB 4415Y 8GB M1824 - Windows 10 Version 1803"

Was able to inspect the page to get the URL for anybody else looking for this:
https://surfacecdn.support.services.microsoft.com/sg/SurfaceGo_BMR_31_1.011.2.zip?t=950d8e63-248e-4426-8470-f37c2a08adc4&e=1536560058&h=5991d52a28ef098948e70104292ef0c7ab97cc10ac80a15c7725bc29ed9f1dc8

**Comment by BrandonRecords** [comment]
The MSI for Surface GO is now available here: http://download.microsoft.com/download/8/2/E/82EEFB07-1AB3-4557-B654-B34D64C9DD94/SurfaceGo_Win10_17134_1802010_6.msi

**Comment by bealsao** [comment]
Thank you!

**Comment by mcolozzo** [comment]
MSI does not appear to have the storage driver. Trying to install our custom Win10, we can't load a disk. Anyone run into this?

**Comment by id1010** [comment]
This is exactly what happened to me also.
See my question I raised here.
https://forums.windowscentral.com/windows-10/478995-why-cant-i-install-fresh-installation-surface-go.html

If someone has a slution please share.
Thanks

**Comment by BRecords** [comment]
The MSI does contain the Surface NVM Express Controller, which should be injected into your WinPE and Windows images. If you continue to encounter difficulty using the MSI, please contact Surface support:
https://support.microsoft.com/en-us/products/surface-devices/surface-business

**Comment by sbala66** [comment]
My new Surface KeyBoard for Surface Go has a p7eculiar p7roblem... numbers 7 8 9  0 and letter p and a few other keys gives p7 [8 ]9 \0 p7 etc.  I am unable to up7date the surface typ7e cover filter as it does not show up7 in Device Manager.  Any help7 would be greatly ap7p7reciated.  Very frustrating

**Comment by jdeckerms** [comment]
@sbala66 Troubleshooting tips are here: https://support.microsoft.com/en-us/help/4023516 If none of the steps help, you'll need to contact Microsoft Support: https://support.microsoft.com/en-us/contactus/

**Comment by sbala66** [comment]
Thanks, but I couldn't find Surface Go related in that link...

**Comment by SmithPlatts** [comment]
So, is someone from Microsoft going to update the required Surface Driver pages to include the Surface Go MSI package?

**Comment by jdeckerms** [comment]
@SmithPlatts Thanks, we'll add a link to that download.

**Comment by lshunnarah77** [comment]
Looks like they added Surface Go!  Now I have to post another requesting the Surface Pro 6 drivers :(

**Comment by crkinard** [comment]
So why was this closed when the MSI still does not contain a storage driver for WinPE/Installing another Windows OS?

**Comment by tsicoupe** [comment]
> So why was this closed when the MSI still does not contain a storage driver for WinPE/Installing another Windows OS?
> 
> I am having the same problems as @mcolozzo.
> 
> @BRecords please test before commenting. Loading the "Surface SCSIAdapter SurfaceNVMExpressController.inf 11.0.4.0" that is in the MSI into a WinPE image does not allow one to see the internal storage drive.

Did you ever figure this out? I tried everything listed as well and am not having any luck. Thanks
