### ISSUE TITLE
Is there mistake in the web title?

### ISSUE THREAD

**Issue by MordochayK** [MicrosoftDocs/windows-itpro-docs#1592]
Device Guard is the combination of WDAC and HVCI (which is based on VBS)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19c8d2d2-3d96-c635-76da-c3b43afc1b45
* Version Independent ID: d7d79add-eadc-2e11-4bf7-eac48e4975d8
* Content: [Device Guard is the combination of Windows Defender Application Control and Virtualization-based security (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/introduction-to-device-guard-virtualization-based-security-and-windows-defender-application-control)
* Content Source: [windows/security/threat-protection/device-guard/introduction-to-device-guard-virtualization-based-security-and-windows-defender-application-control.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/device-guard/introduction-to-device-guard-virtualization-based-security-and-windows-defender-application-control.md)
* Product: **w10**
* GitHub Login: @mdsakibMSFT
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@MordochayK thanks for calling this out. I updated the title.
