### ISSUE TITLE
how about the GPO?

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/windows-itpro-docs#1595]
so are these steps enough? shouldn't you have the GPO for MDM autoenroll as well? I did this and my Hybrid-joined devices never showed up in Intune. only after GPO push I would see them in Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b95868d3-c141-0038-69b2-7a6a84d817d8
* Version Independent ID: b68e29a4-fe87-3c20-4abc-06ab815f33ee
* Content: [Azure AD and Microsoft Intune - Automatic MDM enrollment in the new Portal](https://docs.microsoft.com/en-us/windows/client-management/mdm/azure-ad-and-microsoft-intune-automatic-mdm-enrollment-in-the-new-portal)
* Content Source: [windows/client-management/mdm/azure-ad-and-microsoft-intune-automatic-mdm-enrollment-in-the-new-portal.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/azure-ad-and-microsoft-intune-automatic-mdm-enrollment-in-the-new-portal.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @sasanmcp ,
could you please provide more details?

Option, provided in this article are for autoenrollment during joining AD or Azure AD. It wouldn't work for already joined devices. For existing devices, you should use GPO.

Thank you

**Comment by mypil** [comment]
@sasanmcp - We would like to follow up on this. Can you please respond to the query of MaratMussabekov?

Thank you.

**Comment by sasanmcp** [comment]
we should be good to go. my main incentive was to make sure we are covering Hybrid-joined scenario as well. I see we do have a section for Windows 10 enrollment using GPO. we should be good to close this.

**Comment by mypil** [comment]
@officedocsbot close
