### ISSUE TITLE
test

### ISSUE THREAD

**Issue by phbatt** [MicrosoftDocs/windows-itpro-docs#1596]
test

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe78cdc5-d977-774d-3027-12a692212a55
* Version Independent ID: 8632de82-338f-aab7-cdf8-263726e83aea
* Content: [Set up and use Whiteboard to Whiteboard collaboration](https://docs.microsoft.com/en-us/surface-hub/whiteboard-collaboration)
* Content Source: [devices/surface-hub/whiteboard-collaboration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/whiteboard-collaboration.md)
* Product: **surface-hub**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by shortpatti** [comment]
Closing as no details of the issue were provided.
