### ISSUE TITLE
Reading MPLogs

### ISSUE THREAD

**Issue by dnysveen** [MicrosoftDocs/windows-itpro-docs#1598]
I am trying to interpret windows defender mplog log files and I can't find any information.  I'd really like to understand the meaning of lowfi sigs and some of the other entries.  Can you point me to some documentation on mplog log files?  Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95629861-d1e1-232c-5727-4ebc831f90d6
* Version Independent ID: f653f426-604c-30ed-b2c0-31b44c2f7117
* Content: [Monitor and report on Windows Defender Antivirus protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/report-monitor-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/report-monitor-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/report-monitor-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by andreabichsel** [comment]
Thank you for your question! These are logs used internally for bug investigation, the details of which we can't publish publicly.
