### ISSUE TITLE
Windows Defender mplog logs

### ISSUE THREAD

**Issue by dnysveen** [MicrosoftDocs/windows-itpro-docs#1599]
I am trying to interpret windows defender mplog log files and I can't find any information.  I'd really like to understand the meaning of lowfi sigs and some of the other entries.  Can you point me to some documentation on mplog log files?  Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cee01291-d40e-ad66-32b6-3d04e1f41d9a
* Version Independent ID: 4a069074-d372-0823-7a0c-a9692211094c
* Content: [Run and customize scheduled and on-demand scans](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/customize-run-review-remediate-scans-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/customize-run-review-remediate-scans-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/customize-run-review-remediate-scans-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by andreabichsel** [comment]
Thank you for your question! These are logs used internally for bug investigation, the details of which we can't publish publicly.
