### ISSUE TITLE
Product name mistake

### ISSUE THREAD

**Issue by JoshTech1** [MicrosoftDocs/windows-itpro-docs#1602]
I noticed in this article it refers to MBAM as "Microsoft BitLocker Administration and Management" but the product name is actually "Microsoft BitLocker Administration and Monitoring".
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e5380a-53da-6df1-1952-1be89d9b5969
* Version Independent ID: 82af0c50-fb10-3ad3-1f1d-74a068ea6fa7
* Content: [BitLocker Management Recommendations for Enterprises (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@JoshTech1 Thanks for reporting this, it's fixed now.
