### ISSUE TITLE
Pre-provision of encryption for cloud-based devices

### ISSUE THREAD

**Issue by Scoobysnax97** [MicrosoftDocs/windows-itpro-docs#1603]
Domain-joined computers can pre-provision and encrypt the device before deployment is complete using a SCCM task sequence, but cloud-managed devices are unencrypted until the user escrows their key to their Azure AD account?   Surely, this leaves the device in an unencrypted position?  How can a cloud-managed device replicate the secure, encrypted state of SCCM task sequence?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e5380a-53da-6df1-1952-1be89d9b5969
* Version Independent ID: 82af0c50-fb10-3ad3-1f1d-74a068ea6fa7
* Content: [BitLocker Management Recommendations for Enterprises (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises#managing-domain-joined-computers-and-moving-to-cloud)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@nenonix - As discussed, kindly assist to provide updates on the progress of this issue. Thank you.

**Comment by nenonix** [comment]
@Scoobysnax97 Thanks for the feedback. Does this link answer your question? https://docs.microsoft.com/sccm/core/plan-design/security/cryptographic-controls-technical-reference#cloud-based-distribution-points-and-certificates

**Comment by nenonix** [comment]
@Scoobysnax97 Has this issue been dealt with in more recent iterations of the content or can you provide any more information?

**Comment by mypil** [comment]
@Scoobysnax97 - From our understanding, the issue you raised has been answered by nenonix. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
