### ISSUE TITLE
Windows Defender Firewall with Advanced Security documentation library

### ISSUE THREAD

**Issue by TerryWa** [MicrosoftDocs/windows-itpro-docs#1604]
The link to 'Windows Defender Firewall with Advanced Security documentation library' is a dead link 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4c88cdf-2bf7-8abe-de14-6dba6a8daf07
* Version Independent ID: cda1e59c-ef42-f140-6c37-51e23dec8631
* Content: [Firewall and network protection in the Windows Defender Security Center app](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-security-center/wdsc-firewall-network-protection)
* Content Source: [windows/security/threat-protection/windows-defender-security-center/wdsc-firewall-network-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-security-center/wdsc-firewall-network-protection.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by Justinha** [comment]
@TerryWa Thanks for reporting the broken link. It's fixed now.
