### ISSUE TITLE
This browser doesn't support viewing PDFs natively?

### ISSUE THREAD

**Issue by onefanfare** [MicrosoftDocs/windows-itpro-docs#1605]
Hi, I just wanted to confirm that PDFs hosted online could not be viewed directly, even by an unconfigured Kiosk Browser session? Is this working as intended?

**Comment by onefanfare** [comment]
For more context, this is about the Microsoft App "Kiosk Browser". From the store, for support, it links to the documentation here: https://docs.microsoft.com/en-us/windows/configuration/guidelines-for-assigned-access-app#guidelines-for-web-browsers

**Comment by jdeckerms** [comment]
@onefanfare I apologize that it took me so long to reply. You're correct, PDFs aren't supported in Kiosk Browser. I'm updating  https://docs.microsoft.com/en-us/windows/configuration/guidelines-for-assigned-access-app#guidelines-for-web-browsers to mention that.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by nam31** [comment]
@onefanfare The article [https://docs.microsoft.com/en-us/windows/configuration/guidelines-for-assigned-access-app#guidelines-for-web-browsers](url) has been updated with a note
"Kiosk Browser supports a single tab. If a website has links that open a new tab, those links will not work with Kiosk Browser. Kiosk Browser does not support .pdfs."
Please let us know if you still have any question regarding the issue you have raised initially.
