### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by jmeyer1980** [MicrosoftDocs/windows-itpro-docs#1612]
please double-check the links made available in this document. I was unable to use the one for activating background apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a9f5f11-2586-b1a0-68ea-f433415941cc
* Version Independent ID: 4194c5ea-6bf8-f27e-2e2c-c721b7957994
* Content: [Set up and test custom voice commands in Cortana for your organization (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/cortana-at-work/cortana-at-work-voice-commands)
* Content Source: [windows/configuration/cortana-at-work/cortana-at-work-voice-commands.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/cortana-at-work/cortana-at-work-voice-commands.md)
* Product: **w10**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by shortpatti** [comment]
https://docs.microsoft.com/en-us/cortana/voice-commands/launch-a-foreground-app-with-voice-commands-in-cortana

**Comment by jmeyer1980** [comment]
While I appreciate the link for "foreground" apps... I did say "background" apps. Either way, this document should be updated with the link you provided here, as the link for foreground apps did not work either. 404 error.

**Comment by shortpatti** [comment]
https://docs.microsoft.com/en-us/cortana/voice-commands/launch-a-background-app-with-voice-commands-in-cortana

Both links have been fixed and will be published later today.

**Comment by jmeyer1980** [comment]
As it turns out, this page isn't going to help me do what I was thinking about doing. I was looking for a way to get cortana to recognize a voice command to send clip commands through my twitch chatbot. I'm not a dev, so doing this myself isn't really possible.
