### ISSUE TITLE
Documentation missing for Predefined sets of computers in Advanced Firewall

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/windows-itpro-docs#1613]
This issue was created by @CajH from https://github.com/MicrosoftDocs/feedback/issues/669
Link to article:
The feature is mentioned in the old article http://technet.microsoft.com/en-us/library/ee806447.aspx.
Problem:
It is unclear how the pre-defined sets are defined. It appears as if the groups can be edited. This needs documentation.
The issue is discussed here along with screenshots:
https://social.technet.microsoft.com/Forums/office/en-US/26125329-e4a6-4bdf-996d-8e69674056a4/firewall-how-to-defined-predefined-set-of-computers
https://serverfault.com/questions/773529/predefined-set-of-computers-where-to-define

**Comment by Justinha** [comment]
@Powerhelmsman I replied to @CajH in the feedback repo. The list is predefined according to https://msdn.microsoft.com/en-us/library/cc231500.aspx

**Comment by sergethedev17** [comment]
This issue still exists.

The **Scope** step in the rule creation wizard, allows one to apply a rule to specified IP addresses. One option is to select a set of IP addresses from a **predefined set of computers**. The predefined sets include these selections:

- Intranet
- Report Corp Network

There is no documentation anywhere describing which IP addresses are included in these definitions and how to update them. It is not clear if the **Intranet** option works on a computer that is not part of an AD domain.

Can we add some documentation about this functionality?

Also, can we enhance the rule wizard with a tooltip hint for the same?

The original post (above), refers to screenshots in https://social.technet.microsoft.com/Forums/office/en-US/26125329-e4a6-4bdf-996d-8e69674056a4/firewall-how-to-defined-predefined-set-of-computers. The screenshots appear broken in this thead. They are not visible.

![image](https://user-images.githubusercontent.com/8523760/77276837-b3668980-6d0f-11ea-84db-3e96db36e371.png)

**Comment by LeeiFrankJaw** [comment]
According to [FW_ADDRESSES][1] and [Message Processing Events and Sequencing Rules][2], the above [link][3] was simply misleading.  No you cannot define your own set of computers to be used with Windows Firewall.  There is no `RRPC_FWAddAddressSet` method on the list.  The predefined set is really just predefined and hard-coded in the program.

 [1]: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fasp/67b07a7f-8748-487e-8fd8-c75fe3b307e6
 [2]: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fasp/b0c93352-8371-4d63-abca-b0cc8dbcc3d7
 [3]: https://docs.microsoft.com/en-us/previous-versions/office/communications-server/ee806447(v=ocs.14)
