### ISSUE TITLE
<exclude> definition and example explanation contradict

### ISSUE THREAD

**Issue by PreetiChoudhry** [MicrosoftDocs/windows-itpro-docs#1615]
Refering to documentation on https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/enterprise-mode-schema-version-1-guidance ,
Following explanation of the example contradict (correct me if i am wrong, and please help me understand this in bit more detail).
************************************************************************************************
`<exclude>`
 | Specifies the domain or path that is excluded from getting the behavior applied. This attribute is supported on the <domain> and <path> elements.

`Example<emie>   <domain exclude="false">fabrikam.com     <path exclude="true">/products</path>   </domain> </emie>`

Where http://fabrikam.com doesn't use IE8 Enterprise Mode, but http://fabrikam.com/products does.
-- | --

***************************************************************************************************

Explanation what i understand should be- 
"Where http://fabrikam.com 
**does** use IE8 Enterprise Mode, but http://fabrikam.com/products **doesn't**."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64bbf506-7915-35e1-b31d-5696bbcb95cf
* Version Independent ID: a2064d88-a63f-361e-8f64-742dd38bcd5c
* Content: [Enterprise Mode schema v.1 guidance (Internet Explorer 11 for IT Pros)](https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/enterprise-mode-schema-version-1-guidance)
* Content Source: [browsers/internet-explorer/ie11-deploy-guide/enterprise-mode-schema-version-1-guidance.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/internet-explorer/ie11-deploy-guide/enterprise-mode-schema-version-1-guidance.md)
* Product: **ie11**
* GitHub Login: @shortpatti
* Microsoft Alias: **shortpatti**

**Comment by shortpatti** [comment]
@PreetiChoudhry, after looking at the logic of the example, you are correct in your understanding.  I will make the change to the document.  Thank you for your feedback :)
