### ISSUE TITLE
Central Page With All Current SSU's

### ISSUE THREAD

**Issue by anthony-fontanez** [MicrosoftDocs/windows-itpro-docs#1619]
Can https://docs.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates be updated with a list of all current SSU's for all active Windows 10 builds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b706f0af-d504-a8ca-7c38-b8bb9283bfad
* Version Independent ID: 14f31acf-9f47-59a6-269f-62ab249fe560
* Content: [Servicing stack updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates)
* Content Source: [windows/deployment/update/servicing-stack-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/servicing-stack-updates.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
A reasonable question--I'll ping our SMEs on that and find out.

**Comment by eponerine** [comment]
Is there an update to this request?

**Comment by jaimeo** [comment]
Per the PM I spoke to: SSU updates come down with the cumulative updates in one bundle if you use Windows Update. A list of SSUs would get stale very quickly. Windows Update will automatically offer the latest SSU, and those updates are cumulative.

**Comment by jaimeo** [comment]
Yes, I understand that. The SME's position is that if you are up to date with WU, you have the current SSU version. I will see if I can connect him directly with you for better engagement.

**Comment by eponerine** [comment]
@jaimeo being up to date with Windows Update's latest CU only _exposes_ the SSU upon next update scan. They're not bound together. You still need to install a second update.

**Comment by eponerine** [comment]
"A list of SSUs would get stale very quickly" - is that true, though? The last SSU for Server 2016 was 2018-05. The last SSU for 1803 was 2018-09 (I think?).

They don't seem to be released constantly. But again, without a list, how would we know :P

**Comment by anthony-fontanez** [comment]
My intent with this request was for IT professionals to have one page documenting the most recent SSU's for the purpose of offline servicing WIMs used via imaging deployments such as via ConfigMgr. I rebuild my base image each month and it's sometimes a challenge to confirm easily if there is a new SSU.

**Comment by hoyty76** [comment]
There is a page https://support.microsoft.com/en-us/help/4099479 that lists all the CU, why can't there be a similar page with all the SSU. The argument of information getting stale seems to apply there but yet it is maintained?

**Comment by eponerine** [comment]
I was just given this: https://portal.msrc.microsoft.com/en-us/security-guidance/advisory/ADV990001

**Comment by jaimeo** [comment]
@eponerine ; that's awesome! This is not something my SMEs ever shared with me. Now I can link to that out of this topic, an update I'll make forthwith. Thanks!

**Comment by Gtfinchy** [comment]
And ... as evidenced by #3390 above, the entire PAGE of SSU information has disappeared from docs.microsoft.com. My customer, an USA DoD entity, uses the latest SSU infomation to prepare an updated Reference Image for OS deployment across multiple enviroments. The REQUIREMENT to stay updated AT DEPLOY TIME includes current SSU. Please fix this resource so recently given.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@anthony-fontanez 

This issue has already been addressed with the following commit and content has been updated according to your feedback.

[[c5695fd ] added link to SSUs](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/c5695fda60f7c5a333099551e1f3e15a7591496c#diff-3ee0f2a2b6a1f9657ef38d13036c9d65)

We are thus closing this issue since it seems to be resolved.

Thank you for taking the time to provide feedback and following up.

**Comment by e0i** [comment]
@officedocsbot close
