### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by RyanBijkerk** [MicrosoftDocs/windows-itpro-docs#1621]
Please fix the links in this article, link for Project VRC is not correct and the "Automatic exclusions" link is giving a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84fc852e-4ce0-1d6d-fbc8-76732407e576
* Version Independent ID: 30d715c0-35f0-0b52-68da-75a5f85a619b
* Content: [Windows Defender Antivirus VDI deployment guide](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/deployment-vdi-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/deployment-vdi-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/deployment-vdi-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by andreabichsel** [comment]
Thank you for pointing this out! I've made the fixes and the changes should be live by eod.
