### ISSUE TITLE
Windows Defender AV for Server 2012 R2 - onboarding ATP

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#1628]
Hello, 

Can you provide more details about the scenario where the customer does not have System Center ConfigMgr with Endpoint protection, but still wants to onboard on premise servers in Defender ATP? I just onboarded a Server 2012 R2 in Defender ATP and the device appears in the Security Center console, however there is no Windows Defender AV Agent on the server. How can customers obtain Windows Defender AV if they are not using ConfigMgr? Is that scenario supported?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4ed2b3-0390-4d53-2450-14995ee8b0b0
* Version Independent ID: 91b5bb3e-55d4-6a8e-c16d-094f15c28ee7
* Content: [Onboard servers to the Windows Defender ATP service](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-server-endpoints-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/configure-server-endpoints-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/configure-server-endpoints-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **justinha**

**Comment by andreabichsel** [comment]
It's not a common ask, so I did a little digging. Here's what I found: SCEP is only included with the SCCM media, but there is a concept of SCEP standalone aka unmanaged. You need to have access to the SCCM media via the VLSC site, and then you can download SCCM (current branch) and pull SCEPInstall.exe from the client folder.

https://docs.microsoft.com/en-us/sccm/protect/deploy-use/endpoint-protection-configure-client#bkmk_manual-install provides the steps to manually install.

**Comment by cmcapellan** [comment]
@andreabichsel 
I'm glad I found this Github issue, although unfortunately your findings did not seem to make it into the docs in the end. While it is very helpful to know that we can run SCEP standalone without SCCM, what do we need to do to be licensed for this? Does the $15/mo we are paying for Azure Security Center Standard cover this scenario?
