### ISSUE TITLE
Delete Lockdown Mode VPN Profile

### ISSUE THREAD

**Issue by ericyew** [MicrosoftDocs/windows-itpro-docs#1629]
Is there a way to remove the lockdown mode VPN profile? I've tried everything with no luck.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2ed3176-900c-ddc6-b20c-25c8226ec8c5
* Version Independent ID: c0817834-930a-0b7a-5ba6-6d2bdbe8f72f
* Content: [VPN security features (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-security-features)
* Content Source: [windows/security/identity-protection/vpn/vpn-security-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/vpn/vpn-security-features.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **justinha**

**Comment by shortpatti** [comment]
@MihaiSP, can you take a look at this issue around VPN on the client?

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by nam31** [comment]
@ericyew Please let us know if you still have any question regarding the issue you have raised initially.
