### ISSUE TITLE
issue with get-wmiobject

### ISSUE THREAD

**Issue by officeninja415** [MicrosoftDocs/windows-itpro-docs#1630]
Hi, I'm currently scripting all computers in our domain to create a local account then set that account up for "take a test" but using your code I'm pulling no information when I go with "$obj = get-wmiobject -namespace root/cimv2/mdm/dmmap -class MDM_SecureAssessment -filter "InstanceID='SecureAssessment' AND ParentID='./Vendor/MSFT'";".  Is there something I'm doing wrong or is this code supposed to be different now?  Thanks for your time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0708bbcf-e210-23c2-518f-831598bbccce
* Version Independent ID: 7201313c-3cfb-4ef2-af4e-a6e7ed9dda86
* Content: [Set up Take a Test on multiple PCs](https://docs.microsoft.com/en-us/education/windows/take-a-test-multiple-pcs#create-a-link-using-schema-activation)
* Content Source: [education/windows/take-a-test-multiple-pcs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/take-a-test-multiple-pcs.md)
* Product: **w10**
* GitHub Login: @CelesteDG
* Microsoft Alias: **celested**

**Comment by jdeckerms** [comment]
@officeninja415 You're not doing anything wrong. I'm working with the product team to figure out how to fix the sample script. I'll let you know here what I find out.

**Comment by officeninja415** [comment]
Great to hear.  Thanks for your response!

**Comment by officeninja415** [comment]
Just seeing if there has been any updates on this.

**Comment by jdeckerms** [comment]
@officeninja415 I don't have an answer yet, sorry.

**Comment by officeninja415** [comment]
Ok.  Thank you for the update.

**Comment by jdeckerms** [comment]
@officeninja415 The team found that the script will only work if the account already exists (so the script is configuring an existing account to be a tester account, it isn't creating a tester account). I'll update the topic with that info.

**Comment by officeninja415** [comment]
I am indeed still having the same problem even with the account already created.  Like MeIQL, I'm not getting anything stored in the $obj variable, so there has to be a problem with that line.  I feel like this is a trivial thing to script but would be largely important in the county I work in.

**Comment by merusd** [comment]
Anyone got a setup for how to create an account and url for testing? We can create a domain account no problem but want to figure out how to setup the windows 10 pc account and testing URL.

**Comment by e0i** [comment]
@jdeckerms Any updates on this isse? We would like to follow up. Thanks.

**Comment by RUSDGUS** [comment]
I think this is one of those Microsoft apps that gets demoed when they try to sell you a bill of goods, then after you buy it you realize it is not a finished product. With more states testing digitally it boggles my mind that this is not more of a priority. It would be nice to deploy this via group policy or via PowerShell but I don't think this will ever work unless Google steps up and builds a competing product. No wonder Microsoft is loosing to google in education.

**Comment by stinkydiver** [comment]
Has anyone managed to get the powershell script to work? I have tried this on a Windows 10 1809, there is a local account called TestAccount but it doesn't work.

Running the script in powershell ISE as an admin gives me this output:

The property 'LaunchURI' cannot be found on this object. Verify that the property exists and can be set.
At line:2 char:1
+ $obj.LaunchURI='https://www.foo.com';
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
The property 'TesterAccount' cannot be found on this object. Verify that the property exists and can be set.
At line:3 char:1
+ $obj.TesterAccount='TestAccount';
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
You cannot call a method on a null-valued expression.
At line:4 char:1
+ $obj.put()
+ ~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by RUSDGUS** [comment]
The only way I have gotten it to work is manually going to settings > accounts > access work or school > set up an account for taking tests > then setting the URL and test account manually. The PowerShell script that is given on the feature page does not work. Microsoft wrote the script before creating the Powershell objects that it calls or uses.

**Comment by e0i** [comment]
Closing via # 8118
