### ISSUE TITLE
Technology Systems Architect

### ISSUE THREAD

**Issue by JeffreyWFox** [MicrosoftDocs/windows-itpro-docs#1631]
Do you have an updated document for version 2.8.136.0 of the Surface Deployment Accelerator?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b67dd6d3-d9ee-c306-4cef-2e25562317dc
* Version Independent ID: 55afc90b-ffe8-a0a5-ca52-1c27bccc1796
* Content: [Step by step Surface Deployment Accelerator (Surface)](https://docs.microsoft.com/en-us/surface/step-by-step-surface-deployment-accelerator)
* Content Source: [devices/surface/step-by-step-surface-deployment-accelerator.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/step-by-step-surface-deployment-accelerator.md)
* Product: **w10**
* GitHub Login: @MiladCA
* Microsoft Alias: **jdecker**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by nam31** [comment]
@JeffreyWFox Please let us know if you still have any question regarding the issue you have raised initially.
