### ISSUE TITLE
Documentation for a particular setting is missing words

### ISSUE THREAD

**Issue by brink668** [MicrosoftDocs/windows-itpro-docs#1633]
[Enter feedback here]
Under the "Event Throttling" Section

**Current Word Format**
Registry Path | System\CurrentControlSet\Control\Lsa\

**I believe the path should be**
Registry Path | _HKEY_LOCAL_MACHINE_\System\CurrentControlSet\Control\Lsa\

HKEY_LOCAL_MACHINE appears missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef8b6967-0e45-bcdd-6d70-54759d9f7ec8
* Version Independent ID: 6651ebc1-04f0-421f-891b-6957ca37da7c
* Content: [Network access - Restrict clients allowed to make remote calls to SAM](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls#policy-and-registry-names)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md)

**Comment by Justinha** [comment]
@brink668 Thanks for correcting the registry path. The topic has been updated.
