### ISSUE TITLE
Tpm-Clear doesn't affect windows hello 

### ISSUE THREAD

**Issue by pkuntal** [MicrosoftDocs/windows-itpro-docs#1636]
Hi,

I am using Windows 10 RS5 17713 build and setup windows hello(finger print and PIN) using my microsoft account, My device contains discrete TPM.
I did Clear-TPM to clear everything from TPM, but still i can use my registered fingerprint to login.
Does it mean Clear-TPM doesnt clear Windows Hello container from TPM or TPM is not at all used for windows hello even if device is TPM capable?

Regards,
Pooja

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e8d779-ec27-6dc4-5142-f97ca1db63d7
* Version Independent ID: e3f6b432-acc7-c5b0-dba0-18ab34eb65e8
* Content: [How Windows uses the TPM](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/how-windows-uses-the-tpm#windows-hello-for-business)
* Content Source: [windows/security/information-protection/tpm/how-windows-uses-the-tpm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/tpm/how-windows-uses-the-tpm.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by DaniHalfin** [comment]
@pkuntal thanks for your questions - 
1. Do Windows Hello TPM entries get restored or re-created following a reboot?
2. Do Windows Hello TPM entries get restored by the Passport container service?

Adding @MikeStephens-MS for comments.

**Comment by pkuntal** [comment]
Hi @DaniHalfin
1-Do Windows Hello TPM entries get restored or re-created following a reboot?
>> Not sure, restored or recreated, all we can observe is 'no issue in Finger print login'. We want to confirm the same from Microsoft.
2-Do Windows Hello TPM entries get restored by the Passport container service?
>> Again, When we disabled Passport container service and clear-TPM, Finger print login doesnt work but as soon as we restart this service, Finger print login starts working.
We need to confirm this with Microsoft.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment]
@pkuntal , Hey I have tested  by clearing  tpm . But   still I am able to login .
I think tpm stores the bitlocker password and  does not  stores fingerprints.  So  no use of  tpm with frientprint

**Comment by joinimran** [comment]
Hello @pkuntal - Please note that TPM has nothing to do with Fingerprints data. It only stores passwords, certificates, or encryption keys. While the passport services handle the identity keys to authenticate the users. 

Thanks.
Imran.

**Comment by nam31** [comment]
@pkuntal Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
