### ISSUE TITLE
share

### ISSUE THREAD

**Issue by Grigor88451201** [MicrosoftDocs/windows-itpro-docs#1640]
Share

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 08436cb0-d0b6-0961-9e57-291b24d73644
* Version Independent ID: 36264f52-d3ac-4e50-f8e8-b09d6b210490
* Content: [Windows 10 upgrade paths (Windows 10)](https://docs.microsoft.com/pl-pl/windows/deployment/upgrade/windows-10-upgrade-paths#upgrade-paths)
* Content Source: [windows/deployment/upgrade/windows-10-upgrade-paths.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/windows-10-upgrade-paths.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by greg-lindsay** [comment]
I believe the request here is to have this article human translated.

**Comment by greg-lindsay** [comment]
I will need to get human translation approved and change change the localization priority on the article. This is pending.

**Comment by greg-lindsay** [comment]
Closing this issue.
