### ISSUE TITLE
Enabling Device Registration Service in ADFS

### ISSUE THREAD

**Issue by xXxOlivierxXx** [MicrosoftDocs/windows-itpro-docs#1644]
After running the Initialize-ADDeviceRegistration command, aren't you supposed to run Enable-AdfsDeviceRegistration to enable DRS? I don't see any mention of this step anywhere in the WHFB implementation pages but when I look at other guides about enabling Device Authentication, they all mention the need of running "Enable-AdfsDeviceRegistration"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93cb286c-03a9-187a-77a3-771c1c672342
* Version Independent ID: 875bbfa3-7ee3-960e-9b1c-ff5216a62d8b
* Content: [Configure Device Registration for Hybrid Windows Hello for Business](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg#configure-azure-for-device-registration)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by xXxOlivierxXx** [comment]
Also, I don't see any mention of "Update-WebApplicationProxyDeviceRegistration" either, this command needs to be executed in all Web Application Proxy servers after DRS has been enabled in ADFS, otherwise the WAP servers won't forward those requests to ADFS

**Comment by MikeStephens-MS** [comment]
FIXED!!!
I believe you are thinking of configuring enterprise device registration for ADFS, which is not the case for hybrid certificate trust deployments.  This deployment uses Azure DRS for the initial device registration, not AD FS.  Thus, the service connection point navigates DRS to Azure, not to AD FS.  Certificate trust deployments require device authentication, which means AAD Connect (and AD FS) must be configured to support device writeback.  This is where AAD Connect write the device object back to the on-prem Active Directory and AD FS is enlightened to use the device object to enable device authentication and conditional access.  While AD FS device registration is configured, it works in a supporting role.

**Comment by xXxOlivierxXx** [comment]
So the only reason for running Initialize-ADDeviceRegistration is to create the DRS AD containers? Would enabling enterprise DRS in ADFS cause any problems with Windows Hello, or it doesn't matter because at the end of the day, the SCP will route users to Azure DRS?

**Comment by xXxOlivierxXx** [comment]
I had to deploy DRS today and just to be on the safe side, I tried to run Enable-ADFSDeviceRegistration after running Initialize-ADDeviceRegistration and got the following warning:

![capture](https://user-images.githubusercontent.com/21185516/45788081-ab6aec80-bc35-11e8-8178-ff2c04c4b9f3.JPG)

This tells me that while enabling DRS is needed, you no longer need to run this command manually because just the fact that you need to have a 2016 ADFS farm for WHFB means that DRS is pre-enabled by default.

Something else I did was running "Update-WebApplicationProxyDeviceRegistration" in all of my proxy servers. Not sure if that was needed but I rather be safe than sorry.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by joinimran** [comment]
Hello @xXxOlivierxXx  - all of the rquired information seems updated at https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg#create-ad-objects-for-ad-fs-device-authentication
I hope this clarifies your concerns.

Thanks.
Imran.

**Comment by MaratMussabekov** [comment]
Dear @xXxOlivierxXx ,
**After running the Initialize-ADDeviceRegistration command, aren't you supposed to run Enable-AdfsDeviceRegistration to enable DRS?** - Enable-AdfsDeviceRegistration cmdlet used in WS 2012R2 and earlier. It is not required in WS2016-2019. As deployment of WHfB requires WS2016 AD FS, this cmdlet is not mentioned in the article.

**Also, I don't see any mention of "Update-WebApplicationProxyDeviceRegistration" either, this command needs to be executed in all Web Application Proxy servers after DRS has been enabled in ADFS, otherwise the WAP servers won't forward those requests to ADFS** - there is no need to run it as WAP is not used in the described scenario (see Warning section in the [Configure issuance of claims](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg#configure-issuance-of-claims) part of the article).

Thank you

**Comment by xXxOlivierxXx** [comment]
@joinimran @MaratMussabekov I opened this topic in September 2018, over 2 years ago, so there's no purpose in posting any further suggestions at this point in time.
