### ISSUE TITLE
Outdated documentation on pin complexity gpo

### ISSUE THREAD

**Issue by esanumIT** [MicrosoftDocs/windows-itpro-docs#1645]
There are group policy options to specify pin complexity, now. So the article is not up to date. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feb93192-b78b-a16b-c174-f83e024aa4c4
* Version Independent ID: d7dd6ccd-f984-48d0-49ff-2f5383001fd9
* Content: [BitLocker Key Management FAQ (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-key-management-faq)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-key-management-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-key-management-faq.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@esanumIT Which policy controls PIN complexity? There is an enhanced PIN policy that allows Unicode characters. Do you mean that? It's already mentioned, but I can add a link to that policy and the PIN length policy.

**Comment by esanumIT** [comment]
Have a read? https://www.windowscentral.com/how-enable-pin-complexity-windows-10

**Comment by esanumIT** [comment]
Oops, that was my bad, indeed. but yea, to have that same set of policies for the bitlocker PIN would be good. I'll try to remember to submit that FR tomorrow.

**Comment by Justinha** [comment]
@esanumIT perfect, thank you.
