### ISSUE TITLE
Windows Defender Red X

### ISSUE THREAD

**Issue by bwaut353** [MicrosoftDocs/windows-itpro-docs#1646]
We are seeing an issue after updating to v1803 where the Windows Defender system tray icon is showing a red X. However, when we click in the Windows Defender Security center we are seeing green check marks for all of the settings. Is there a way to tell what is causing this Red X and what we can do to remidiate it? Or is this a glitch that Microsoft is aware of?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65d57fa8-9c9b-63cc-7248-175242963432
* Version Independent ID: 9cd96c93-8f46-64db-a162-02da1e1f63cc
* Content: [Hide notifications from the Windows Defender Security Center app](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications)
* Content Source: [windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by blooodorange** [comment]
+1

**Comment by andreabichsel** [comment]
I'm not aware of any bugs related to this. Please use https://support.microsoft.com to help resolve this problem. Thank you!
