### ISSUE TITLE
Office 365 Pro Plus 1808 and ProductName

### ISSUE THREAD

**Issue by ajgolia** [MicrosoftDocs/windows-itpro-docs#1649]
In 1808 version of Office 365 Pro Plus you updated the product name to "Microsoft Office" from "Microsoft Office 2016" which has resulted in previously working enlightened apps for WIP stopping to work if you leveraged template in ZIP..  XML linked in ZIP above also is not updated...  

The root cause of this problem is that in your XML, you have an explicit DENY for "Microsoft Office" while you chose to name the latest 1808 product to Microsoft Office.   For others who may have used the XML as a base template removing this DENY and updating references from Office 2016 to Office resolved any WIP issues. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ed0150-0172-f3ad-3c7f-3a7141efbe64
* Version Independent ID: 6a978d2b-a0ff-1052-ce00-06f02f30cfa1
* Content: [List of enlightened Microsoft apps for use with Windows Information Protection (WIP) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@ajgolia Thanks for reporting this. Our engineering team is working on a fix and the docs will be updated accordingly.

**Comment by Justinha** [comment]
@ajgolia This issue has been fixed. I updated the product names in the table and the download has been updated also. I think official communications have also been sent to Intune customers who may have been affected.
