### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by xXxOlivierxXx** [MicrosoftDocs/windows-itpro-docs#1650]
When you are creating the WHFB certificate template you ask the user to type the name "WHFB Authentication" but on the "Mark the template as the Windows Hello Sign-in template" steps for ADFS, you indicate the template name "WHFBAuthentication" in the powershell cmdlet. The blank space needs to be removed from the template name, or added to the PS command line

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd063d0c-8739-15bd-4f16-11b893029845
* Version Independent ID: cd3679fe-dd9c-44f9-04ed-c772a47ca4e4
* Content: [Configuring Hybrid Windows Hello for Business - Public Key Infrastructure (PKI)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by xXxOlivierxXx** [comment]
Nevermind, you are supposed to use the template name not display name for the PS cmdlet

**Comment by MikeStephens-MS** [comment]
FIXED!!
Correct-- template name and display name are different. If you don't use any special characters its just the display name without spaces
