### ISSUE TITLE
Sentence doesn't make sense

### ISSUE THREAD

**Issue by simoncrelling** [MicrosoftDocs/windows-itpro-docs#1651]
"If no value (blank) or zero (0) is present in the Machine will be locked after input field, then the policy setting is disabled and no action is taken on user-input inactivity for the session."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75ab75c2-3bfd-bde6-8341-65ba79e9fe65
* Version Independent ID: 7224910c-ac05-26b2-f712-9a5993432615
* Content: [Interactive logon Machine inactivity limit (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit)
* Content Source: [windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@simoncrelling Thanks for raising this. I revised that sentence to make it more clear. Feel free to re-open if you think it should be improved further.
