### ISSUE TITLE
Please Disable ‘Do not connect to any Windows Update Internet locations’ GPO/Registry key in order to upgrade to Windows Enterprise using CSP license.

### ISSUE THREAD

**Issue by kumaarrahul** [MicrosoftDocs/windows-itpro-docs#1652]
Please Disable ‘Do not connect to any Windows Update Internet locations’ GPO/Registry key.
 
GPO Location:
 
Configure the policy value for Computer Configuration -&gt; Administrative Templates -&gt; Windows Components -&gt; Windows Update -&gt; "Do not connect to any Windows Update Internet locations" to "Disabled".
 
Registry Key Location:
 
Registry Hive: HKEY_LOCAL_MACHINE 
Registry Path: \SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\
 
Value Name: DoNotConnectToWindowsUpdateInternetLocations
 
Value Type: REG_DWORD
Value: 0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ecbc1-9c02-5681-7214-356be22ac7e8
* Version Independent ID: 73af82f6-079b-6c37-55c4-cb59e921457a
* Content: [Deploy Windows 10 Enterprise licenses](https://docs.microsoft.com/en-us/windows/deployment/deploy-enterprise-licenses)
* Content Source: [windows/deployment/deploy-enterprise-licenses.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-enterprise-licenses.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by greg-lindsay** [comment]
Sorry for taking so long to get to this. I only saw this request today.

This reg key doesn't normally exist, and would only be created if needed to restrict communication to a local WSUS server, or had some other reason to block communication with WU. Are you saying that communication with WU is required to upgrade?

**Comment by greg-lindsay** [comment]
I found that there is a related bug that causes activation to be lost. I'm sure this is the same root cause and a patch will likely need to be released. In the meantime I am adding a note here as suggested.  The notice should appear later today.
