### ISSUE TITLE
Is ComputerAccount used for just adding the Computer to the domain?

### ISSUE THREAD

**Issue by somehowadev** [MicrosoftDocs/windows-itpro-docs#1653]
Was just wondering if the account specified for adding the computer to the domain is also used for installation of programs/edition upgrade etc or does it still carry on using whatever account OOBE uses? 

Since I've found UAC prompts pop up on what I believe is the edition upgrade setting, after the computer is joined to the domain. The computer account it uses to join the domain isn't part of the local admin group for computers. I had a suspicion that it's either due to LAPS or Group policy we have. 

Thanks,  
Z

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313b8527-ba38-682f-5291-7c56ef58b122
* Version Independent ID: 88d93eac-44d2-46d2-0763-4380dc8cfdb8
* Content: [Accounts (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/wcd/wcd-accounts#computeraccount)
* Content Source: [windows/configuration/wcd/wcd-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/wcd/wcd-accounts.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by TecumsehSamp** [comment]
I suspect it's due to `HideOOBE` not being set to `True`.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by joinimran** [comment]
Hello @somehowadev - Basically there is a difference between a computer account and a user account. Normally joining a domain is only allowed using a domain admin account. Each time you add a computer to the domain, a computer account is created for that computer in the Active Directory database so that you can apply the policies to the group of machines based on your requirements.

Thanks.
Imran.

**Comment by somehowadev** [comment]
Ha, thanks I guess? It was 2 years ago and I've moved on quite a bit since then. 

Not necessarily having a go as I do understand that this is _meant_ to be used for feedback on the docs but still it might have been better to just close and move on :)
