### ISSUE TITLE
Azure AD Login Format

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/windows-itpro-docs#1656]
Hi, the "AzureAD\FirstnameLastname" can be incorrect. It is local path of user profile in C:\Users\ which is created based on DisplayName attribute from Azure AD. So it can be a really different name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@Kazzan Thanks for your suggestion, I'll add that information to the topic.

**Comment by billgatesfan** [comment]
I am not sure the statement "FirstnameLastname is the name of the user profile in C:\Users, which is created based on DisplayName attribute in Azure AD." is really valid...

For me (note: I could only test with our ADFS synched infra), the name of folder in C:\Users, is based on the sAMAccountName LDAP AD attribute, not the AAD DisplayName.

**Comment by Kazzan** [comment]
Hi @billgatesfan, unfortunately this is not the case. Imagine full cloud only scenario. The sexy one. M365 Business or M365 Enterprise. Azure AD only, not sync with local AD. There is no such attribute to be used.

For that AAD Windows 10 using Display Name, in some builds it used FirstName, MiddleName, LastName and removing some special characters. Now it using Display Name and removing only some special like "," but not "(" or" )". And some programs have a big problems with that.

You can try it, or follow example at [Local username Windows 10 Azure AD Microsoft 365](https://serverfault.com/questions/910985/local-username-windows-10-azure-ad-microsoft-365) or [How can I configure the user profile / SAM account name in Azure AD that I got with Office 365 (or Microsoft 365 Business)?](https://serverfault.com/questions/925928/how-can-i-configure-the-user-profile-sam-account-name-in-azure-ad-that-i-got-w).

**Comment by billgatesfan** [comment]
Yeah, I suspected a difference here and wanted to highlight this explicitly, in the hope that Microsoft   not only focus on sexy and best-case scenarios, but also that they don't forget that people using ADFS are usually large enterprises... ;-)

**Comment by Kazzan** [comment]
Hi @billgatesfan, you can be assured that in these waters it will work the same. They had plenty of time to proof this in practice. I have one customer with 8k of users going to cloud only, but this also limiting him. So I mean also addressing these concerns need to be done from Microsoft.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by billspeers** [comment]
I fought with this for a few weeks and finally am able to connect. You must login with CASE SENSITIVE AzureAD\!!!!

Going against how we've logged into Windows for year where the case in the username didnt matter. Now it does. Use the proper case. 

And to verify your username run the command line command whoami /upn.

**Comment by billspeers** [comment]
For example:
AzureAD\emailadress@domain.com

**Comment by alokshan** [comment]
This documentation says "If the user who joined the PC to Azure AD is the only one who is going to connect remotely, no additional configuration is needed. "

What if the user has been made standard user through Intune Autopilot? Would they still be able to RDP?

**Comment by nam31** [comment]
Closing via #8507
