### ISSUE TITLE
On this Site are the "OLD" Silverlight screenshots

### ISSUE THREAD

**Issue by slaet** [MicrosoftDocs/windows-itpro-docs#1662]
Can you please update this Site with the new Azure Portal screenshots. This site is linked from the WDATP Portal and it makes no sense to show the people the old Portal stuff that is no more in use.
thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc98378-18c5-81bf-769e-d76d26852c91
* Version Independent ID: dd542381-071b-e583-f082-976e8fd91019
* Content: [Onboard Windows 10 machines using Mobile Device Management tools](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-endpoints-mdm-windows-defender-advanced-threat-protection#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-atp/configure-endpoints-mdm-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/configure-endpoints-mdm-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Thank you for your feedback. This topic will be updated to point to the Intune instructions.
