### ISSUE TITLE
Issues with BiLocker  Network Unlock

### ISSUE THREAD

**Issue by mlrankin** [MicrosoftDocs/windows-itpro-docs#1663]
Hello there,
I am working on enabling the network unlock for our domain systems.  However I am using a virtual server running Windows Server 2016 that is not the domain controller (or the DHCP).  I setup a DHCP and separate WDS server on this virtual server but how do I get to issue the certificates for LAN connected devices that get is IP address from the domain controller?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c13083-9b29-e54b-fd85-8033ec665fcd
* Version Independent ID: ce8c4647-69bc-95d4-2192-6e737d5ad5da
* Content: [BitLocker How to enable Network Unlock (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock#feedback)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@mlrankin One thing about your setup, can you confirm the DHCP server and WDS server are running on separate virtual machines?

**Comment by mlrankin** [comment]
Yes


Powered by Cricket Wireless



-------- Original Message --------
Subject: Re: [MicrosoftDocs/windows-itpro-docs] Issues with BiLocker Network Unlock (#1663)
From: Justin Hall
To: MicrosoftDocs/windows-itpro-docs
CC: Maurice Rankin ,Mention


@mlrankin<https://github.com/mlrankin> One thing about your setup, can you confirm the DHCP server and WDS server are running on separate virtual machines?

**Comment by mlrankin** [comment]
I just updated the BIOS on my test laptop.  I am using a Dell Latitude 3570.  I see one of the requirements is for the UEFI-based and is on firmware version is 2.3.1.  I am hoping updating to the latest firmware gets me closer to resolving this issue.  Will post back results.

**Comment by mlrankin** [comment]
Still no go.  Even with laptop connected to the LAN it wants the PIN.  Now it wants the bilocker recovery key and giving message about "boot configuration has changed" so I have to put in PIN and recovery key to get the proper boot.  I have checked the DHCP and WDS settings several times.  Has this process been tested in Windows Server 2016 with Windows 10 Machines?

**Comment by Justinha** [comment]
Does the laptop get an address from DHCP? You mentioned initially it gets an IP address from the domain controller but I don't understand that.

**Comment by mlrankin** [comment]
Yes. I tested it in NIC/PXE mode and I see the DHCP IP and the MAC and my workstation IP. But I can't tell if my laptop is sending the request to the WDS server.


Powered by Cricket Wireless



-------- Original Message --------
Subject: Re: [MicrosoftDocs/windows-itpro-docs] Issues with BiLocker Network Unlock (#1663)
From: Justin Hall
To: MicrosoftDocs/windows-itpro-docs
CC: Maurice Rankin ,Mention


Does the laptop get an address from DHCP? You mentioned initially it gets an IP address from the domain controller but I don't understand that.

**Comment by Justinha** [comment]
You might need to use Network Monitor for that. Were you able to enable WDS debug logging? You might need to review that and the BitLocker event log to troubleshoot.

**Comment by mlrankin** [comment]
Ok, I am looking at the event log.  It did process a request form my client machine but says there is no boot images installed for this architecture.  I see x64uefi so I am assuming I need to add that image to there sever correct?  Do I need to add it to the WDS server or my DHCP server?

**Comment by Justinha** [comment]
Image file muse be for WDS.

**Comment by Justinha** [comment]
But I'm not sure how the image file is related.

**Comment by mlrankin** [comment]
Not that I got the debugger working I should be able to narrow this down.  Let me test more and will let you know how it turns out. Thanks for the help so far.

**Comment by mlrankin** [comment]
In the BIOS what should my boot sequence be?  I have Windows Boot Manager, UEFI:Toshiba Partition 1, Onboard NIC(IPTV4) and OnBoard(IPTV6).  From the phase graph it should be Windows Boot Manager (I assume) to send the request to the WDS.

**Comment by Justinha** [comment]
I think the onboard nic needs to be first for WDS to work.

**Comment by mlrankin** [comment]
Yes, were getting somewhere now.  It seeing the DHCP and retrieving and IP address.  Let me check my WDS server properties to make sure its set properly.

**Comment by mlrankin** [comment]
MY WDSServer is listening on port 10.144.80.30.  If my clients are getting its IP address from the DHCP with address of different ranges how do I get the WDSServer to see the clients request?

**Comment by Justinha** [comment]
The Network Unlock provider on the WDS server recognizes the vendor-specific DHCP request that gets broadcasted by Windows Boot Manager. The request contains the network key and a session key for the reply. See the section titled "Network Unlock Sequence".

**Comment by Ankit198** [comment]
I am stuck at 
Choose the certificate template created for Network Unlock on the Domain controller and select Enroll. When prompted for more information, add the following attribute to the certificate:

Select the Subject Name pane and provide a friendly name value. It is suggested that this friendly name include information for the domain or organizational unit for the certificate. For example "BitLocker Network Unlock Certificate for Contoso domain"
Create the certificate. Ensure the certificate appears in the Personal folder.

I typed friendly name under general tab but under subject tab i typed as per documents but still it said enrollment pending.

so if you guys can help me please.

**Comment by groupwhere** [comment]
Can anyone answer which policy settings are actually required for BNU to work.  Specifically, is Allow network unlock at startup required. What else is required?  I am simply wondering if the missing policy settings are causing the machines to not make DHCP requests prior to showing the PIN dialog at boot.

**Comment by Ankit198** [comment]
![enrollment pending](https://user-images.githubusercontent.com/43585473/46087161-fb324200-c166-11e8-8479-0bad6d42f61d.PNG)

**Comment by Ankit198** [comment]
what should I do now?
no clue .....

**Comment by joestern** [comment]
@Ankit198 - "Pending Enrollment" means you need to go to your CA and approve the enrollment (recall in step 9 of the certificate template creation, you specified manager approval required.) After you do this, you can search for the cert on the client, and right-click it to perform the export functions.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @mlrankin and @Ankit198, I know it's been a while since this issue was opened so thank you both for your patience. Based on the discussion here, I will assume that your issues have already been resolved. If not, I recommend the following:

1. [Technet forums](https://social.technet.microsoft.com/Forums/home) and the [Tech Community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities) where you can ask questions and interact with other users, experts and also Microsoft engineers.
2. [Contact Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) if you need immediate assistance.

Also, please be informed that this Github site is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. If you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review. 

I will now close this issue. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by mlrankin** [comment]
Thank fine.

On Jul 28, 2019 3:04 PM, Jo <notifications@github.com> wrote:

Hello @mlrankin<https://github.com/mlrankin> and @Ankit198<https://github.com/Ankit198>, I know it's been a while since this issue was opened so thank you both for your patience. Based on the discussion here, I will assume that your issues have already been resolved. If not, I recommend the following:

  1.  Technet forums<https://social.technet.microsoft.com/Forums/home> and the Tech Community<https://techcommunity.microsoft.com/t5/Communities/ct-p/communities> where you can ask questions and interact with other users, experts and also Microsoft engineers.
  2.  Contact Windows 10 support<https://support.microsoft.com/hub/4338813/windows-help?os=windows-10> if you need immediate assistance.

Also, please be informed that this Github site is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. If you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review.

I will now close this issue. Thanks for being part of the Microsoft Docs community!
