### ISSUE TITLE
Recommend linking to the SCCM MSfB integration/troubleshooting reference

### ISSUE THREAD

**Issue by MSFTJerryAb** [MicrosoftDocs/windows-itpro-docs#1664]
https://support.microsoft.com/be-by/help/4010214/understand-and-troubleshoot-microsoft-store-for-business-integration-w

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 806bafee-0358-4654-08cf-f9a0bf3ea208
* Version Independent ID: 3223ab26-fe54-6eec-6f3c-9e75c0fdfd19
* Content: [Troubleshoot Microsoft Store for Business (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/troubleshoot-microsoft-store-for-business#feedback)
* Content Source: [store-for-business/troubleshoot-microsoft-store-for-business.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/troubleshoot-microsoft-store-for-business.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@MSFTJerryAb - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@MSFTJerryAb - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
