### ISSUE TITLE
Calculator?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/windows-itpro-docs#1666]
This guide seems almost insane when you compare it with the ADFS sizing calulators or the Exchange sizing calculators.   Couldn't Microsoft just come up with some rough baseline numbers for users+devices and 2016 DC's and state them?  This upgrade your DC's one by one, then monitor your event logs, then do calculations, rinse and repeat, etc., is fairly indirect guidance, in my opinion. 

Deploying Hybrid Windows Hello for Business is already a serious list of chores for customers to complete.  This one prerequisite planning piece could really handle some simplification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1da1ac4-4e67-5970-6d10-19aac6e853f6
* Version Independent ID: 4f4b45eb-d479-3699-1ef1-a1a20030d675
* Content: [Planning an adequate number of Windows Server 2016 Domain Controllers for Windows Hello for Business deployments](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by DaniHalfin** [comment]
Hi @JeremyTBradshaw , thanks for reaching out. 
There really isn't even a rough number we can point to. It really depends on too many variables, such as - What kind of servers are you using? How many requests are DCs receiving and at what frequency? Are there any other services running? What type of security software are you using? (and so on..)
That is only further complicated by the # of users and devices you have in your network. 

Sizing is a complicated task, and there isn't a rough number we can provide, hence we provide IT pros with guidance on how to observe current load and size appropriately.

**Comment by JeremyTBradshaw** [comment]
Fair enough.  Thanks for the response.  I suppose even at minimum, the DC's should be scaled according to whatever other dependencies there are then these counters could be monitored during this implementation..

Calculators are nice, but I do get it that DC's are up against more variables.

Thanks again.

**Comment by DaniHalfin** [comment]
Still thanks for the call out. We definitely have areas where we can simplify, unfortunately authentication is one area that is very hard to simplify.
