### ISSUE TITLE
Offline downloads sometimes only has a GUID for the file name and no extension

### ISSUE THREAD

**Issue by presleymark** [MicrosoftDocs/windows-itpro-docs#1674]
The download is very confusing and useless for most people since it has no file extension it cannot be installed.

**Comment by shortpatti** [comment]
@presleymark,  Can you tell me what topic this is referring to so that I can help you better?

**Comment by presleymark** [comment]
Hi Patti,

I was trying to report bugs on the business store specifically in regard to
offline downloads.

I clicked a link that was supposed to be for providing feedback on the
business store and it to me to this GitHub page so I entered the issue.
Then after I entered it I noticed it didn't seem like the right spot.  I
even went back and clicked on the link again and it took me to the same
place.

Sorry for any confusion if it went to the wrong place.

Mark

**Comment by e0i** [comment]
@TrudyHa Any updates regarding this issue? We would like to follow-up. Thanks.

**Comment by e0i** [comment]
@TrudyHa Any updates with this issue? Thanks.

**Comment by RAJU2529** [comment]
@presleymark. Normally  windows updates  come with  file name contains  guid with file extension.
By default , windows os  I  hides all extension , we need to enable through windows file explorer.
Open **windows explorer** , click on **view tab** , then put a tick mark in  **Filename extensions**

I hope with my reply , your issue will  solve

**Comment by e0i** [comment]
Hello @presleymark,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
