### ISSUE TITLE
Was Census.Security removed from 1703?

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#1678]
On August (14) Census.Security was part of the 1703 Basic level documentation. When I checked today it is missing. Is that correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58804632-6711-f8c2-4af8-6d34b0bfb913
* Version Independent ID: 48b4ba5b-d580-11e4-dbbc-caacd3483be7
* Content: [Windows 10, version 1703 basic diagnostic events and fields (Windows 10)](https://docs.microsoft.com/en-us/windows/privacy/basic-level-windows-diagnostic-events-and-fields-1703)
* Content Source: [windows/privacy/basic-level-windows-diagnostic-events-and-fields-1703.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/basic-level-windows-diagnostic-events-and-fields-1703.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by shortpatti** [comment]
@Justinha, I don't think this is you but I'm not sure.  If not, let me know and I'll assign it to the correct author.

**Comment by iadgovuser1** [comment]
OK, thanks for the info.
