### ISSUE TITLE
Enterprise Solution for Surface Dock firmware updating

### ISSUE THREAD

**Issue by IanDoesIT** [MicrosoftDocs/windows-itpro-docs#1679]
Hi,
This firmware updater is very easy to use however it is problematic in an enterprise environment. The organisation I work for made the decision to change its entire computer fleet to Surface Books and all desks have surface docks all up about 300.
This surface book firmware updater process does not cater to scaling out to many docks since you have to follow the prompts connect, check if up to date, start update process, disconnect part way through when prompted, reconnect, then wait 2-3 mins for it to complete the update and reboot the dock then confirm it has updated successfully.
Microsoft can you please look into providing a scalable way to update surface docks in an enterprise environment as doing this one by one is very time consuming and impractical. 
We have done what we can for instance any docks we hold in IT stock I update however for instance I updated 2/3 (200 docks) from the Jan 2018 update and now there is a July update and should now be doing this all again plus the other 100 that I didn't get to? I hope you can understand this situation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7b356e-3dbd-7f59-845e-a92e05865a52
* Version Independent ID: 711c5497-373f-662c-7fae-ba60f046e50c
* Content: [Microsoft Surface Dock Updater (Surface)](https://docs.microsoft.com/en-us/surface/surface-dock-updater)
* Content Source: [devices/surface/surface-dock-updater.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/surface-dock-updater.md)
* Product: **w10**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@IanDoesIT This is really important information, could you submit it through the Feedback Hub so it gets directly to the engineering team?

**Comment by IanDoesIT** [comment]
> @IanDoesIT This is really important information, could you submit it through the Feedback Hub so it gets directly to the engineering team?

Thank you @jdeckerms if you are referring to the Windows 10 feedback hub app in windows we have that disabled by group policy. Is there any other alternatives?

**Comment by jdeckerms** [comment]
@IanDoesIT I can pass it on, but it's more likely to get attention coming from customers through the app.

**Comment by jdeckerms** [comment]
@IanDoesIT The Surface engineering team has received your feedback so it can be considered in their future product plans.

**Comment by IanDoesIT** [comment]
@jdeckerms Thank you for submitting on my behalf. If they would like any further information I'm happy to provide and communicate with them to help.
