### ISSUE TITLE
Great but where is a copy of a sample completed Config.xml file for the start menu with comments suggested what is required and what is optional?

### ISSUE THREAD

**Issue by summone** [MicrosoftDocs/windows-itpro-docs#1680]
Sample config file would be useful instead of bit feeding us with, you can add this and that what about a completed sample with comments to help us out here!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78038d67-04a1-f4ae-6a69-98e157688a31
* Version Independent ID: c86b4460-e8be-8537-a6c8-3cb094ef14a3
* Content: [Set up a multi-app kiosk  (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps#add-xml)
* Content Source: [windows/configuration/lock-down-windows-10-to-specific-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/lock-down-windows-10-to-specific-apps.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@summone We provide a full XML sample for reference here: https://docs.microsoft.com/en-us/windows/configuration/kiosk-xml

**Comment by summone** [comment]
Yes that was exactly what I was looking for where is the link for this on
the page though?

**Comment by jdeckerms** [comment]
@summone We'll add a link.

**Comment by summone** [comment]
Perfect thanks for the help.

Please note some pages logic do not make sense also.

For instance I have been asked to lock down win 10 tabs for a group of
councillors. I have now followed the instructions made the start Config
file. Added it to intune created a profile.

Added the start file the apps it should access.

Registered the device on the network.

But its not configing the start menu as aspected when I try to sign into
the device. I still get the normal start menu.

It does not show under all devices but does show under Azure ad device.

Am I supposed to use the provisioning package to now locked down the start
menu seems a bit much. It's very manual process if I have to do this to 50
tablets?

Thanks for your advice and help in advance it is appreciated.

Kind regards Steven

**Comment by jdeckerms** [comment]
@summone If you're following the procedure for configuring a multi-app kiosk in Intune and not getting the results that you should, you'll need to contact Microsoft Support for assistance. (https://support.microsoft.com/en-us/contactus/)
