### ISSUE TITLE
Formatting corrections

### ISSUE THREAD

**Issue by milesgratz** [MicrosoftDocs/windows-itpro-docs#1681]
1. Header for Certificate templates is misspelled: https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki#certifcate-templates

2. Header for Publish Templates is inside the Note block, so it is not hyperlinked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd063d0c-8739-15bd-4f16-11b893029845
* Version Independent ID: cd3679fe-dd9c-44f9-04ed-c772a47ca4e4
* Content: [Configuring Hybrid Windows Hello for Business - Public Key Infrastructure (PKI)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki#certifcate-templates)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by milesgratz** [comment]
Also, forgot this one.

3. Misspelling on navigation links for guide on this md file [Prerequistes](hello-hybrid-cert-trust-prereqs.md)

**Comment by DaniHalfin** [comment]
Hi @milesgratz, thanks for reaching out.
While we work to fix the formatting issues, I'd like to suggest the "Edit" option, to actually send us a pull request with the changes. You can use this for this instance or for any future instances where you find formatting issues (or typos :) ).

**Comment by arshadkazmi42** [comment]
@DaniHalfin I would like to work on this.
