### ISSUE TITLE
\\server\profile

### ISSUE THREAD

**Issue by Curtmcgirt** [MicrosoftDocs/windows-itpro-docs#1682]
I've had \\server\profile in place for certain users for about a decade and a half. we just upgraded RDS servers from 2008 R2 to 2016 servers, and the roaming profile path \\server\profile is being ignored by the 2016 servers. users are getting a local profile only. where is this documented? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9ca7cb6-32cb-1517-a9de-c36046955d45
* Version Independent ID: 91041e39-007e-f481-0cd4-177b4039ae12
* Content: [Create mandatory user profiles (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/mandatory-user-profile)
* Content Source: [windows/client-management/mandatory-user-profile.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mandatory-user-profile.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@Curtmcgirt Information about roaming user profiles on Server is here: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/jj649079(v=ws.11)

**Comment by Curtmcgirt** [comment]
@jdeckerms that article includes approximately zero information about server 2016.

**Comment by jdeckerms** [comment]
https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-roaming-user-profiles

**Comment by hpbjthomas** [comment]
setting the CopyProfile parameter to True seems to break some stuff, like start menu search. is anyone else experiencing this?

**Comment by WaWi** [comment]
@hpbjthomas 
You need to modify permissions on the mandatory profile folder + all subfolders (checkbox).
Grant the group "All Application Packages" Full control on those

Then go to regedit and select  HKEY_USERS. In the menu, select "open structure" (or similiar, im on the German windows) and open your ntuser.man file. Enter any key name e.g. "Mandatory" and select "permissions" in the context menu.
Then Grant "Everyone" and "All Application Packages" Full control on the key + all sub elements.
Then mark the "Mandatory" Key and go to the menu, "remove structure"

Now start menu, search and tasbar should work.

source and screenshots:
https://www.windowspro.de/wolfgang-sommergut/anleitung-mandatory-user-profile-verbindliches-benutzerprofil-fuer-windows-10

**Comment by mypil** [comment]
@Curtmcgirt - From our understanding, the issue you raised has been answered by jdeckerms. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by Curtmcgirt** [comment]
Oh....my issue turned out to be a long-forgotten group policy that disabled roaming profiles on every computer in the domain except those 2008 R2 rds servers mentioned in the original post. Once I enabled roaming profiles on the 2016 rds servers, roaming profiles immediately started working on the 2016 rds servers.

:)

**Comment by illfated** [comment]
Thank you for the feedback and explanation. Speaking from my long experience as a support person, it can often be tricky to spot when an issue is caused by manual user configuration and not the software itself. At least this will be interesting to see for future readers looking for clues to solve problems with roaming profiles.
