### ISSUE TITLE
So what you're saying is basically copypasta something, then uninstall windows to get rid of candy crush saga.

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-itpro-docs#1686]
So what you're saying is basically copypasta something, then uninstall windows to get rid of candy crush saga.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b48c394-863e-9a54-6d5b-5f31ff07849f
* Version Independent ID: f5ddf9f4-c449-360c-107e-582f7d9df7fd
* Content: [Windows 10 connection endpoints](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-endpoints)
* Content Source: [windows/privacy/manage-windows-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/manage-windows-endpoints.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
Hi @MoonGem , thanks for reaching out. In order to remove Candy Crush Sage you'd need to uninstall the game. 
Feel free to reach out to us through any of our support channels if you need guidance on how to do that.

**Comment by mypil** [comment]
@officedocsbot close
