### ISSUE TITLE
AssignedAccessConfiguration AllowedApps support for wildcards

### ISSUE THREAD

**Issue by DirkMCar** [MicrosoftDocs/windows-itpro-docs#1689]
Is there a way to create an AllowedApps reference that targets all EXEs in a subfolder? I used the example below and it does not function. The reason why this is needed is that an app I am trying to add to my kiosk creates a randomized folder in the user temp folder and inside that folder there is an EXE that needs to run. The app is a old app and there is no consistent AMUID I can use.

Also, if wildcard is not supported, is there a way to whitelist an app by hash or app publisher?

&lt;AllAppsList&gt;
     &lt;AllowedApps&gt;
          &lt;App AppUserModelId="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge" /&gt;
          &lt;App DesktopAppPath="%TEMP%\*" /&gt;
     &lt;/AllowedApps&gt;
&lt;/AllAppsList&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8301897-dfa3-ef3b-744f-9e8334c17dc4
* Version Independent ID: d5751dd3-b0ae-49ef-75cd-d4113c4eed3d
* Content: [AssignedAccess CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/assignedaccess-csp)
* Content Source: [windows/client-management/mdm/assignedaccess-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/assignedaccess-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by jdeckerms** [comment]
@DirkMCar I checked with the engineering team and there isn't a way to do that with Assigned Access.

**Comment by fatherofinvention** [comment]
Thanks @jdeckerms. Does that mean we have to explicitly whitelist every executable? This can be very difficult for software with a lot external dependencies and the rule set can get unwieldy very fast.

**Comment by illfated** [comment]
@Heidilohr - will you be available to reply to the question?

**Comment by Heidilohr** [comment]
@illfated Unfortunately, I'm no longer the writer assigned to the CSP articles, so I can't answer your question, but I've forwarded it along to someone who can get the people who can involved.

**Comment by illfated** [comment]
Fair enough. Any help to get someone who knows this content to post a reply will be useful here.

**Comment by ManikaDhiman** [comment]
@fatherofinvention I checked with the engineering team and unfortunately the answer to your question is yes. You will need to explicitly whitelist every executable.

**Comment by illfated** [comment]
@ManikaDhiman : Thank you for your reply and for confirming what the bottom line answer is in this case.
Not sure if @DirkMCar will comment back, but I presume @fatherofinvention will be likely to notice it.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
@DirkMCar and @fatherofinvention I know it's been a while since this issue was opened so thank you both for your patience. I am sorry that the feature you are asking for is not yet available, but I do encourage you to submit this as a suggestion on [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). The Microsoft engineering team uses UserVoice feedback to learn what users are asking for or what they want to improve. I will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
