### ISSUE TITLE
Deploying Windows Analytics

### ISSUE THREAD

**Issue by nick-blair** [MicrosoftDocs/windows-itpro-docs#1691]
If the "HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\DataCollection" setting is configured with an AllowTelemetry value of "0" (Security) and Configuration Manager has client setting under "Windows Analytics" setting of "Yes" and Windows 10 Telemetry of "Full", which setting overwrites the order?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4273a259-c3c7-dca7-6353-954068d740a7
* Version Independent ID: 1084ea77-95c4-4e4a-da6c-f4d8668f9ebf
* Content: [Enrolling devices in Windows Analytics (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started)
* Content Source: [windows/deployment/update/windows-analytics-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-get-started.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
I believe Configuration Manager settings always override local registry settings, but I'll grab a PM to confirm.

**Comment by nick-blair** [comment]
Hi Jaimeo,

Is there is a confirmation for this? Thanks.

**Comment by jaimeo** [comment]
@dudeso : can you help with this question?

**Comment by dudeso** [comment]
Happy to help- the registry path above **is** the same path that we use to apply settings specified in our Windows Analytics client settings which means that yes, the registry value would be overwritten by SCCM. However, if the diagnostic data settings are specified via group policy then they are applied at a different registry path and in that case Group Policy configuration takes precedence over the settings in SCCM client settings.

**Comment by nick-blair** [comment]
Hi Dudeso,

Can you please provide/confirm the registry path that gets set if the telemetry is configured via group policy? These are two registry paths I am aware of:

GPO registry setting
-----------------------
**HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\DataCollection**
Allow Telemetry ==> 0x00000000(0) | Security

SCCM registry setting
-------------------------
**HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\DataCollection**

Allow Telemetry ==> 0x00000003(3) | FULL
CommercialId ==> "<<Org ID>>"

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment]
@nick-blair, I confirmed now I applied group policy enabled telemetry registry keys to be  applied 

You can use the following  registry key::

**[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DataCollection]
"AllowTelemetry"=dword:00000000    0 for Security 
"AllowTelemetry"=dword:00000001    1 for Basic
"AllowTelemetry"=dword:00000002    2 for Enhanced
"AllowTelemetry"=dword:00000003    3 for Full**


anyone value is  possible

**Comment by jvsam** [comment]
Hello @nick-blair hoping all is well. I know it's been a while since this issue was opened so thank you for your patience. I just wanted to follow up if you found the answer to your last question? @RAJU2529 also shared some information, I hope those helped as well. And since there is no specific request related to this documentation, we will now close this issue, however feel free to re-open if you have suggestions or ideas to make this doc better. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
