### ISSUE TITLE
Windows Server and WCF Features

### ISSUE THREAD

**Issue by jdtugit** [MicrosoftDocs/windows-itpro-docs#1694]
Please update the "Windows Server Features" section to more accurately represent present day Windows Server instances, which do not feature "Non-HTTP Activation" beneath the .NET 4.x node.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a072bd-02f8-bc2e-a69c-46cd1c30897d
* Version Independent ID: 8e64ed63-1905-fffd-c305-c5436617ba3d
* Content: [MBAM 2.5 Server Prerequisites for Stand-alone and Configuration Manager Integration Topologies](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/mbam-25-server-prerequisites-for-stand-alone-and-configuration-manager-integration-topologies)
* Content Source: [mdop/mbam-v25/mbam-25-server-prerequisites-for-stand-alone-and-configuration-manager-integration-topologies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/mbam-25-server-prerequisites-for-stand-alone-and-configuration-manager-integration-topologies.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by e0i** [comment]
@jdtugit 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.
