### ISSUE TITLE
This is kind of a meaningless page, don't you think? 

### ISSUE THREAD

**Issue by ChrisAtFCPS** [MicrosoftDocs/windows-itpro-docs#1695]
Shouldn't the individual parameters and their respective settings be displayed such as -autoload 0 / 1 -enablepackagescripts 0 / 1 etc?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54f396fd-7bd1-2f95-5ceb-19ace5981727
* Version Independent ID: b4b31211-5479-32f5-04f8-cc28cbaf83a4
* Content: [How to Modify Client Configuration by Using PowerShell](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/appv-v5/how-to-modify-client-configuration-by-using-powershell51)
* Content Source: [mdop/appv-v5/how-to-modify-client-configuration-by-using-powershell51.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/appv-v5/how-to-modify-client-configuration-by-using-powershell51.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by egallagh** [comment]
Hi ChrisAtFCPS. I believe this page presents a specific use example and is not intended to list all the command variants nor the syntax of those commands.

**Comment by ChrisAtFCPS** [comment]
I didn’t see a page where the additional commands would be located or a link to that page.  I’m only pointing out that it seems the generic page title doesn’t match the content.

jcl

Sent from my iPhone

On Sep 30, 2018, at 7:05 PM, Ed Gallagher <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi ChrisAtFCPS. I believe this page presents a specific use example and is not intended to list all the command variants nor the syntax of those commands.
