### ISSUE TITLE
Strange View in ICD after applying windows 10 baseline.

### ISSUE THREAD

**Issue by mathieudesjardins** [MicrosoftDocs/windows-itpro-docs#1700]
Hi, we are in a domain environment and after applying Microsoft Baseline Policies for Windows 10, the template available in ICD (Package for Surface Hub as an exemple) is displayed the wrong way and pictures are not clickable.
It must be due to certain restriction to Internet Explorer (execution of script or something like this). Is there a way to have an input on what is used by ICD (Java, VBS things like this) and on which zone is it interacting (intranet, internet, local computer).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bae35d21-83b8-2699-f200-2ccc45d5a155
* Version Independent ID: eabb7d11-9b54-dfdd-818e-80b23bdcce73
* Content: [Install Windows Configuration Designer (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-install-icd)
* Content Source: [windows/configuration/provisioning-packages/provisioning-install-icd.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/provisioning-packages/provisioning-install-icd.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@mathieudesjardins "How provisioning works" (https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-how-it-works) contains the information I have on what is used by Windows Configuration Designer.

For help with your issue, you can contact Microsoft Support: https://support.microsoft.com/en-us/contactus/

**Comment by mathieudesjardins** [comment]
The part explaining the settings required for a server SKU is missing something:
In order to enable the simplified authoring jscripts to work on a server SKU running Windows Configuration Designer, you need to explicitly enable Allow websites to prompt for information using scripted windows. Do this by opening Internet Explorer and then navigating to Settings > Internet Options > Security -> Custom level > Allow websites to prompt for information using scripted windows, and then choose Enable. 

After the security part, you have to select on which zone to configure that part, Internet, Intranet, Trusted, restricted, etc.

Even after having configured that part, in each zone, I still have my problem, so if someone could read de recommended baseline from MS regarding Internet Explorer and see if there is something else that is required along the said setting.

**Comment by jdeckerms** [comment]
@mathieudesjardins Could you attach a screenshot of what you're seeing when you run Windows Configuration Designer? Also, which version of WCD are you using? (Version should display in bottom left corner of the tool)

**Comment by mathieudesjardins** [comment]
Here is the screen shot:
![image](https://user-images.githubusercontent.com/41486657/46301332-0674db80-c574-11e8-8502-2689cc2dbf0e.png)

The release number is 10.0.17134.1.

I am running an insider preview of windows but it was the same behavior on any version of Windows I am trying it. The only part remaining the same is the GPOs applied.

**Comment by jdeckerms** [comment]
@mathieudesjardins Would you be willing to run GPRESULT.EXE ("grpresult /h currentpolicy.html") and send us the result? (Email it to jdecker at Microsoft.com rather than attach it in GitHub if you have any privacy concerns)

**Comment by mathieudesjardins** [comment]
Email sent!

**Comment by mathieudesjardins** [comment]
Here are the result of the GPResult.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jdeckerms** [comment]
@mathieudesjardins I didn't get an attachment. You might have to change the file extension to .txt (I'll rename it to html on receipt) so it doesn't get blocked by our filters.

**Comment by jdeckerms** [comment]
@mathieudesjardins Got it this time, thanks!

**Comment by jdeckerms** [comment]
@mathieudesjardins The engineering team is trying to figure out the problem. They need to know exactly which security baseline you applied -- just the name is fine. Thanks!

**Comment by mathieudesjardins** [comment]
Hi, we did used that one.
[Windows 10 Version 1709 Security Baseline.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/2450567/Windows.10.Version.1709.Security.Baseline.zip)

We probably had some custom as well. When I remove myself from the OU where the internet Explorer GPOs are applied, the wizard seem to work.

**Comment by jdeckerms** [comment]
@mathieudesjardins Thank you, I'll pass that on.

**Comment by jdeckerms** [comment]
@mathieudesjardins The team wants to know whether you applied all of the GPOs in the security baseline or just specific ones?

**Comment by mathieudesjardins** [comment]
I think that the desktop team applied all the GPOs that where in the baseline.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jdeckerms** [comment]
@mathieudesjardins Thanks for being so patient. The team thinks they've identified the setting in the baseline that is causing problems running WCD, and now we're contacting the security team to see what the ramifications of reversing the policy setting is, before we recommend that customers change it.

**Comment by mathieudesjardins** [comment]
Awesome, you guys are really quick!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mathieudesjardins** [comment]
Hi Jeanie, do you have any response from the security team?

I know that there was some updated guidance for GPO’s for build 1809 but I did not verify if there was any changes done to that part yet.

Thank you!

Mathieu

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mathieudesjardins** [comment]
@jdeckerms any news on your side from the security team?

**Comment by jdeckerms** [comment]
@mathieudesjardins They opened a bug to work on the issue, but haven't been able to get to it yet. I'll let you know when we have progress.

**Comment by jdeckerms** [comment]
@mathieudesjardins I apologize that it's taken so long. The engineer was able to confirm that one setting in the baseline (**Security Zones: Use only machine settings** = enabled) causes the problem with WCD. Right now, we have no fix for the issue except disabling that setting, which would mean the baseline policy will not be in place and the server will not be properly secured. I can't give any estimate for when the bug may be fixed or the fix make it to release.

I think your best option is to run WCD on a different device; your other option is to disable that setting on the server (not recommended).

**Comment by mathieudesjardins** [comment]
Thank you for the follow up on the issue.

Mathieu

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello @mathieudesjardins  ,

We are closing this issue since your support question seems to be answered. Feel free to re-open this issue if you still experience problems.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by bardbird74** [comment]
I have the very same display issue with the desktop windows 11 adk version and the Microsoft store version of the windows imaging and configuration designer
