### ISSUE TITLE
Windows pro 

### ISSUE THREAD

**Issue by Niglb** [MicrosoftDocs/windows-itpro-docs#1710]
This document states all features are available for Enterprise, while only some are for Pro. What limitations will we hit with a OEM Pro license? Are we able to assign a cloud Win10 Ent license to a Kiosk device only if required? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0bcdb8c-3424-6f65-ff3a-e47baaf25931
* Version Independent ID: bbd1e508-6d46-b9be-2f4f-a401b6cef71f
* Content: [Configure kiosks and digital signs on Windows desktop editions (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/kiosk-methods)
* Content Source: [windows/configuration/kiosk-methods.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-methods.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@Niglb The difference between Pro and Ent in this scenario is the method you can use to configure a single-app kiosk running a Win32 desktop app.

As far as I know, there are no conditional upgrade licenses.

**Comment by mypil** [comment]
@Niglb - From our understanding, the issue you raised has been answered by jdeckerms. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
