### ISSUE TITLE
Licensing requirements for Windows Server?

### ISSUE THREAD

**Issue by SteveBurkettNZ** [MicrosoftDocs/windows-itpro-docs#1715]
Lists the licensing for the client OS, but what about for Windows Server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/minimum-requirements-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/minimum-requirements-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/minimum-requirements-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by egallagh** [comment]
Hi @SteveBurkettNZ
This section of docs - docs.microsoft.com/windows documents Windows (desktop, etc.), not Windows server. The Windows server documentation is within docs.microsoft.com/windows-server
