### ISSUE TITLE
DisableAntiSpyware is repeated

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#1717]
"For example, in Group Policy there should be no entries such as the following values:" DisableAntiSpyware is repeated twice. I think the other value needs to be DisableAntiVirus.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13006cbf-ad22-e75a-bf3a-2a6d0b92f088
* Version Independent ID: c9a7a12f-2ef5-b5fa-b515-41ecce5fecd1
* Content: [Troubleshoot Windows Defender ATP onboarding issues](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/troubleshoot-onboarding-windows-defender-advanced-threat-protection#ensure-that-windows-defender-antivirus-is-not-disabled-by-a-policy)
* Content Source: [windows/security/threat-protection/windows-defender-atp/troubleshoot-onboarding-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/troubleshoot-onboarding-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Thank you for your feedback! Will fix it right away.

**Comment by iadgovuser1** [comment]
This was fixed and can be closed.
