### ISSUE TITLE
You uh.. published it

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/windows-itpro-docs#1720]
Ooops? Looking forward to seeing this feature launch though!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12823601-7426-a768-e72f-866b150baccd
* Version Independent ID: c1f993e3-a405-6860-8ab1-7b3d387b4631
* Content: [Hybrid AAD Join](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/user-driven-hybrid)
* Content Source: [windows/deployment/windows-autopilot/user-driven-hybrid.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/user-driven-hybrid.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by greg-lindsay** [comment]
The topic is blank, so it's not really a problem. I think the person who said "do not publish" meant that if there were content on the page, don't publish it yet.  It does look odd though, so I'll fix it this week when I publish some new content.

**Comment by shareonline** [comment]
Any word on when Autopilot will support hybrid joined devices?

**Comment by damigs** [comment]
Really looking forward to this.   Eagerly waiting.

**Comment by saimaddali** [comment]
Hi any idea when this will be available?

**Comment by greg-lindsay** [comment]
Content has been added to the page today. It should publish in an hour. It's possible that it might not go live until 11/8.
