### ISSUE TITLE
Kinda need to know: What exactly does "This option is not currently supported." mean?

### ISSUE THREAD

**Issue by arekfurt** [MicrosoftDocs/windows-itpro-docs#1723]
Four of the 16 policy configuration "options" currently have this statement where the descriptions of what they do would otherwise be.  Does that statement mean that the functionality might/will be included in future versions of Windows but isn't now?  Does it mean the functionality is sort-of there, but not ready for reliable production use?  Does it mean the functionality is there but Microsoft isn't ready to officially explain or support it through support channels yet?  Something else?

**Comment by shortpatti** [comment]
@synopsis19, can you tell me which topic?

**Comment by synopsis19** [comment]
For my own work, I'm primarily currently interested in "Disabled: Script Enforcement" and "Enabled: Inherit Default Policy". Although I'm sure everyone working with WDAC would appreciate any explanation that can be provided about the implementation statuses of "Enabled: Boot Menu Protection" and "Allowed: Debug Policy Augmented" as well.

**Comment by shortpatti** [comment]
@synopsis19, please provide the link to the topic so that I can assign it to the correct author for triaging.

**Comment by synopsis19** [comment]
Wait... if you're referring to what page is involved it's this one: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create
(I assumed GitHub would have linked these comments to that page when I clicked "Leave feedback directly on GitHub there.)

**Comment by synopsis19** [comment]
Apologies. I should have realized this was the overall page for doc issues, not specifically dedicated to that topic.

**Comment by shortpatti** [comment]
@Justinha, can you take a look at this issue?

**Comment by Justinha** [comment]
@arekfurt @shortpatti I've asked our engineering partners to share more details. I'll add that as it comes in.

**Comment by Justinha** [comment]
@arekfurt Sorry there's just not much more to share. Some don't function and never have, some are reserved for future use. But the only point we want to convey is they are not supported. If you try to use them, they may do nothing or they may cause a problem.

**Comment by arekfurt** [comment]
Appreciate you taking the time to look into the matter. Thanks.

Also, just maybe pass along that if we're not supposed to be using it putting the "Enabled: Inherit Default Policy" option in the starter policies that come with Windows is... confusing.  And leaves me wondering a bit about whether I'm supposed to keep it or remove it from my customizations.  

But, as I said, thanks.

**Comment by Justinha** [comment]
@arekfurt thanks for pointing that out. The engineering team said that is intentional. It's a reserved option that doesn't do anything today but they have a goal to do something with it.

**Comment by arekfurt** [comment]
Good to know. Since it's intentionally in the starter policies and as long as it doesn't have any disruptive consequences today I'll leave it in my customized policies then. Thanks.
