### ISSUE TITLE
Event Type information would be great

### ISSUE THREAD

**Issue by Jonathan0Doe** [MicrosoftDocs/windows-itpro-docs#1728]
This is a really nice overview of events associated with ipsec. It would be great, if the event type (like success or failure) information would be added to the event ids.

Best Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c4bff2b-72b1-930d-565d-48404424baf5
* Version Independent ID: a1b1eddb-96e4-f212-b6f5-cdf13a05753e
* Content: [Audit IPsec Quick Mode (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-ipsec-quick-mode)
* Content Source: [windows/security/threat-protection/auditing/audit-ipsec-quick-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/audit-ipsec-quick-mode.md)
* Product: **w10**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@Jonathan0Doe Thanks for the suggestion. I added S and F to IPSec events
