### ISSUE TITLE
IT

### ISSUE THREAD

**Issue by jeandamascenetuyizere** [MicrosoftDocs/windows-itpro-docs#1729]
IM A STUDENT I NEED YOUR HERP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 442b38a6-3431-6210-3a94-0b83efecd1e1
* Version Independent ID: 405676fe-d67e-3376-89ab-39a178076d97
* Content: [Top support solutions for Windows 10](https://docs.microsoft.com/en-us/windows/client-management/windows-10-support-solutions#solutions-related-to-wireless-networking-and-8021x-authentication)
* Content Source: [windows/client-management/windows-10-support-solutions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/windows-10-support-solutions.md)
* Product: **w10**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **elizapo**

**Comment by shortpatti** [comment]
Closing. No detail provided.
