### ISSUE TITLE
onedrive ondemand 

### ISSUE THREAD

**Issue by compie67** [MicrosoftDocs/windows-itpro-docs#1730]
Hi all, we have a few shared devices(max 2 persons on a device) and i am trying to get the onedrive on demand desktop tool to work.

These devices are Azure domain Joined.

Nothing wil work only the cloud Onedrive. It is importand that teacher can save a document from RDP to the OneDrive but for now this is not visible.

Is there a way to setup this with Windows Configurator designer?

with regards
Eric

**Comment by jdeckerms** [comment]
@compie67 I'm not clear on your question.

You said "Nothing wil work only the cloud Onedrive. It is importand that teacher can save a document from RDP to the OneDrive but for now this is not visible." Could you explain more? What have you done to get it working? What does Remote Desktop have to do with this?

**Comment by compie67** [comment]
Hi, offcourse wil try to explain.
We at school have to work with the Remote desktop connection for the LMS, the report generated must be saved localy and we want this in the OneDrive. Now thats the problem. From the RDP this is not visible. i am talking about the native Windows 10 onedrive app. When i want to install the onedrive for business program this wont work on the shared device. I hope this can be arranged with de windows configurator
Eric

**Comment by jdeckerms** [comment]
@compie67 It looks like there's an issue using RDP and OneDrive: https://techcommunity.microsoft.com/t5/OneDrive-for-Business/using-onedrive-from-Remote-Desktop-connection/td-p/212784

You can add your information to that post, to see if anyone has found a solution, or you can contact Microsoft Support (https://support.microsoft.com/en-us/contactus/) for assistance.

**Comment by compie67** [comment]
I think it would be the last one. The first link was also my post ;-)
Thank you for responding.
Eric

**Comment by mypil** [comment]
@compie67 - Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
