### ISSUE TITLE
Update for current versions of Office

### ISSUE THREAD

**Issue by CCDFischer** [MicrosoftDocs/windows-itpro-docs#1731]
This seems to indicate that Office 2016 and 2019 are not supported as App-V packages, though the article as not been updated since August 2016. Can we get clarification on modern supported versions for App-V deployment and coexistence?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5519c29a-61b3-fa01-cdd7-c27608e28bd2
* Version Independent ID: 3e0c7929-fb4a-6d7a-f995-37326d802f26
* Content: [Planning for Using App-V with Office](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/appv-v5/planning-for-using-app-v-with-office#bkmk-office-vers-supp-appv)
* Content Source: [mdop/appv-v5/planning-for-using-app-v-with-office.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/appv-v5/planning-for-using-app-v-with-office.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by MaratMussabekov** [comment]
Hello @CCDFischer, there is another article (up-to-date) that contains the same topics: [Planning for deploying App-V with Office](https://docs.microsoft.com/en-us/windows/application-management/app-v/appv-planning-for-using-appv-with-office)

Dear @e0i ,
could you please have a look? I think the original article should be deleted, as it contains outdated data only, and it could be replaced by article above

Thank you

**Comment by e0i** [comment]
Hello @CCDFischer  ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
