### ISSUE TITLE
CloudApp Security OS requirement 

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#1732]
The documentation mentiones that Windows 10 1809 is required, will we see this for lower versions as well in the near future? I.e. 1803? I am concerned that it will take a while until we see corporate adopt 1809 and it would be sad to not use this awesome capability 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d99de0-789d-3c71-4bd9-f45e62f82a7b
* Version Independent ID: d56d09f0-1f9a-563e-fee0-142bda27a99b
* Content: [Configure advanced features in Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/advanced-features-windows-defender-advanced-threat-protection#microsoft-cloud-app-security)
* Content Source: [windows/security/threat-protection/windows-defender-atp/advanced-features-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/advanced-features-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Hi alexverboon, 

Thank you for your feedback. At the moment, I'm not sure if this capability will be available for lower versions.
