### ISSUE TITLE
Package Accelerator on Windows 10

### ISSUE THREAD

**Issue by gmshebib** [MicrosoftDocs/windows-itpro-docs#1734]
Under the package accelerators section it says that Microsoft  provides accelerators for Windows 10, 8, and 7. Then it links to the accelerators for 7 and 8. Where is the Windows 10 package accelerator?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2315db43-4209-3daa-6865-9c4b952aaed5
* Version Independent ID: f7799da3-5b7c-3ad7-ed91-05fa0e831827
* Content: [Deploying Microsoft Office 2010 by Using App-V (Windows 10)](https://docs.microsoft.com/en-us/windows/application-management/app-v/appv-deploying-microsoft-office-2010-wth-appv)
* Content Source: [windows/application-management/app-v/appv-deploying-microsoft-office-2010-wth-appv.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/app-v/appv-deploying-microsoft-office-2010-wth-appv.md)
* Product: **w10**
* GitHub Login: @MaggiePucciEvans
* Microsoft Alias: **elizapo**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @gmshebib currently, there are only 2 package accelerators for creating Office 2010 available for download at TechNet Gallery. This information reflects on this documentation (*For Windows 7 & 8 only*). There is a link to the instructions on [How to Create a Virtual Application Package Using an App-V Package Accelerator](https://docs.microsoft.com/windows/application-management/app-v/appv-create-a-virtual-application-package-package-accelerator), which perhaps intended for users if they want to create a package accelerator for Windows 10. 

Anyhow, we want to make sure the contents of the Microsoft Docs are clear, so do you have any suggestions on how we can improve some of the *messaging* on this doc to avoid confusion? Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation. Suggestions, comments and feedback to improve the docs are always welcome. Thank you for engaging with the community!

**Comment by jvsam** [comment]
Hi @gmshebib. We haven't received any response from you, so for now, we will close this issue. If you believe the documentation needs improvement, please re-open and provide recommendations on what needs to be changed or updated. Thank you for your feedback and for engaging with the community!

**Comment by jvsam** [comment]
@officedocsbot close
