### ISSUE TITLE
Missing links?

### ISSUE THREAD

**Issue by reckstein** [MicrosoftDocs/windows-itpro-docs#1735]
Perhaps finish the lines that say "For more information, see"  ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9960b9e-e9e3-84b1-6171-37e5239a86aa
* Version Independent ID: 09ffca13-27be-b5d2-24a0-04161f62eb87
* Content: [Software developer resources](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/developer-resources)
* Content Source: [windows/security/threat-protection/intelligence/developer-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/intelligence/developer-resources.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by levinec** [comment]
Fixed!
