### ISSUE TITLE
Clarify EDU pricing 

### ISSUE THREAD

**Issue by nimojg-microsoft** [MicrosoftDocs/windows-itpro-docs#1736]
For example, does Windows Intune Education and/or Microsoft 365 Academic SKUs qualify for use with Windows Intune? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62fdc73a-2b65-bac9-907c-ac21e8653449
* Version Independent ID: 0929b1d6-d3f6-77cc-81dc-1183fb1c293b
* Content: [Windows Autopilot licensing requirements](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-requirements-licensing)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-requirements-licensing.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-autopilot-requirements-licensing.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by jurajgh** [comment]
yes - we're using it. you need to purchase Intune for Education Faculty (or Students). in case you license all faculty members, you get all students for free, no matter the size of the school. and yes, it's the full intune, not just a simplified version.

**Comment by VLG17** [comment]
@nimojg-microsoft Both Windows Intune Education and Microsoft 365 Academic SKUs let you manage Windows devices through Intune. I guess this was what you were asking, right?

**Comment by e0i** [comment]
Hello @nimojg-microsoft ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
