### ISSUE TITLE
out of date screenshot 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1742]
one of the screenshot  is  outdated under  virus and protection , date is  6/26/2018

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d6356b-87ff-8c3a-56ef-1270a823d3ab
* Version Independent ID: 4d6ae878-66cf-0e10-bdf3-bdd6054cbc9d
* Content: [What's new in Windows 10, version 1809](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1809.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1809.md)
* Product: **w10**
* GitHub Login: @dawnwood
* Microsoft Alias: **trudyha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@nenonix - As discussed, kindly assist to provide updates on the progress of this issue. Thank you.

**Comment by RAJU2529** [comment]
@mypil .when new screen shot is update. How do I add new sceen shot in this article

**Comment by nenonix** [comment]
@RAJU2529 please see https://aka.ms/officeart for visual content guidelines or use this convo channel to add screenshots for a member of our team to process and add.

**Comment by RAJU2529** [comment]
@nenonix . Thanking you sir. I have own screen shot in my laptop . But I want replace old pictures  to new pictures in Article.

But I dont know how to do. 
Can I attach all new screenshots in zip and creating PR  to author

**Comment by nenonix** [comment]
@RAJU2529 it is more complicated than that, as there is a new visual style for screenshots that you can download at https://go.microsoft.com/fwlink/?linkid=2002617  -- If you are able to contribute graphic content in this form,  you will need to consult the Microsoft Docs guide for contributors https://docs.microsoft.com/contribute for details on how to upload images via PR. I am busy working on applying these guidelines here, so please be patient and you will see what is involved. (It is not a simple process, so please bear with me a little longer).

**Comment by RAJU2529** [comment]
@nenonix .ok sir. I will wait for the right time. First I will try to create new style graphics screenshots. If possible only I try it. sir 
Thanking you for answering my questions without worrying.
Hats of to you sir

**Comment by mypil** [comment]
@RAJU2529 - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
