### ISSUE TITLE
enable cloud protection

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1744]
only works with windows defender 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f8ccc01-1b04-e443-ef75-6ffe6c866dd5
* Version Independent ID: fa2eaa0f-db04-785a-3894-8244947b9cd5
* Content: [Enable cloud-delivered protection in Windows Defender Antivirus](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by andreabichsel** [comment]
Closing for now. If you have a question or feedback, please let me know. Thank you!
