### ISSUE TITLE
Error Code: 0x80070490

### ISSUE THREAD

**Issue by rcooley77** [MicrosoftDocs/windows-itpro-docs#1748]
No it's not a Windows Update error! What's this one mean? Just updated to 1809, my PIN disappeared and now I get this error when trying to fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by neilfairall** [comment]
Same here. Pin and fingerprint are no longer options for signing in although when I swipe my finger I get a "not recognized" error. I'm able to create a PIN but receive the error "Sorry, this PIN isn't working for your organization's resources. Tap or click here to fix it."

Clicking as requested results in a dialog noting that "Your organization requires Windows Hello" and prompting me to set up a PIN - although I just did.

As soon as I click on the "Set up PIN" button, I get the error code noted (0x80070490) with correlation ID  7b049968-5b6e-0006-2796-057b6e5bd401

**Comment by petergeier** [comment]
Exactly same scenario here.

**Comment by CameronVetter** [comment]
Same here, any answer for this?

**Comment by nikrampi** [comment]
Having same error on machine testing for Intune policies (Microsoft 365).
Can't find helpful docs for troubleshooting...

**Comment by DaniHalfin** [comment]
Hi everyone,
Thanks for reaching out. It'll take us a while to get through all the errors not listed in this topic, however, this feedback is meant to address the content, rather than the issue.
Please report the issue through feedback hub, and if this is a blocking issue, please reach out to us through our support channels.
We'll try to get to all errors not listed in this topic, but it'll take us a while.

Thanks!

**Comment by CameronVetter** [comment]
So you are telling us to report this bug in the feedback hub and not the issues list in github?  That seems backward from the standard usage of each to me.

**Comment by rcooley77** [comment]
Seems to be a problem with every update... Happening again with 1809, but only with specific machines. Still trying to rule out O365 Enterprise/Education licensing and GPO, though.
I think the idea is that GITHUB is for commenting on documents themselves, not features. Feature comments, bugs and requests should be reported through Feedback. If so, that makes sense.
