### ISSUE TITLE
Article needs to be streamlined and checked for content

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#1750]
I am testing CSPs and going through this article.  

The style guides are off, and the content is jumbled.. look to:
Update/IgnoreMOUpdateDownloadLimit 

To validate, the text appears to be broken up in two places??

Some state Data type, like Integer, etc.. some do not.. A Style guide for each CSP is ideal. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ca58bd-f279-7739-0140-c4bd56784768
* Version Independent ID: 1d2ecc90-58a3-6bcd-84ae-ef04d7a3b7b4
* Content: [Policy CSP - Update](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update#update-activehoursend)
* Content Source: [windows/client-management/mdm/policy-csp-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-update.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by shortpatti** [comment]
@Heidilohr / @jdeckerms, it looks like that there are too many quotes or the quotes are not in the correct order in the command.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @Tdiwestyguy, thank you for your feedback. Since you've opened three issues related to the [Policy CSP - Update](https://docs.microsoft.com/windows/client-management/mdm/policy-csp-update) article, I am combining #[1774](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1774), #[1775](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1775) and #[1750](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1750) to the request that I will forward to the Windows writing team. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentations.

**Comment by Heidilohr** [comment]
Forwarding this along to @Dansimp so he can get you in touch with the writer currently responsible for CSP articles.

**Comment by ManikaDhiman** [comment]
@jvsam Issues #1774 and #1775 are now resolved. The Update/PauseFeatureUpdatesStartTime 
and Update/PauseQualityUpdatesStartTime policy descriptions now include syntax and examples.

For issue #1750, I am already in touch with the product team to get it resolved.

**Comment by jvsam** [comment]
Hi @ManikaDhiman that's great! Thank you and we appreciate the assistance as well @Heidilohr.

@Tdiwestyguy several updates were made on the [Policy CSP - Update](https://docs.microsoft.com/windows/client-management/mdm/policy-csp-update#update-pausequalityupdatesstarttime) documentation. Kindly review when you have the chance. We'll update this when issues with regard to *Update/IgnoreMOUpdateDownloadLimit* policy are resolved.

**NOTE**: Updated the statuses of issues #1174 and #1175.

**Comment by jvsam** [comment]
Hi @ManikaDhiman, have you heard from the product team? Are the updates applied on the Policy CSP doc includes *Update/IgnoreMOUpdateDownloadLimit* CSP? I am unable to track the commits and PRs since they are not linked. Please confirm. Thank you.

**Comment by ManikaDhiman** [comment]
Hi @jvsam, thanks for the follow up! The updates for Update/IgnoreMOUpdateDownloadLimit policy are still under discussion with the product team. I will update the doc and the status here as soon as it gets resolved.

**Comment by jvsam** [comment]
Got it, thanks @ManikaDhiman !

**Comment by jvsam** [comment]
Hi @ManikaDhiman similar to my inquiry here #1894, can you please provide an update? Much appreciated! Thanks.

**Comment by ManikaDhiman** [comment]
Hi jvsam, thanks for the follow up. I am still awaiting response from the product team on  Update/IgnoreMOUpdateDownloadLimit. I will update the docs as soon as I get any updates. Thanks!

**Comment by jvsam** [comment]
Thank you for staying on top of this @ManikaDhiman!

**Comment by jvsam** [comment]
Hi @ManikaDhiman I hope all is well. Do you have any update from the product team regarding this issue and #1894? Thanks and regards.

**Comment by ManikaDhiman** [comment]
Hi @jvsam, based on product team's feedback, I have created a PR to update the content of "Update/IgnoreMOAppDownloadLimit" and "Update/IgnoreMOUpdateDownloadLimit" policies. The updates will be available soon. Hope this helps in resolving the issue. Thanks!

**Comment by jvsam** [comment]
Great to hear that @ManikaDhiman! Thank you. Looking forward to the updates and then we can finally resolve and close this issue. As always, we appreciate all the help!

**Comment by jvsam** [comment]
Hello @Tdiwestyguy, I just checked the docs and the updates on the "Update/IgnoreMOAppDownloadLimit" and "Update/IgnoreMOUpdateDownloadLimit" policies made by @ManikaDhiman are displayed here at docs.microsoft.com. Like what was mentioned on #1894, it may take a while to get all the information for all the policies listed in the **Policy CSP - Update** documentation. I am sure as new information comes in, the doc will be updated as well. We will now close this issue. Feel free to re-open or create another issue through the doc's *feedback feature*, if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
