### ISSUE TITLE
Conflicting Themes

### ISSUE THREAD

**Issue by Vamork** [MicrosoftDocs/windows-itpro-docs#1759]
Had an initial problem with the searchbar in file explorer still being light themed when dark theme is active. It was changed when i reset my theme to default from my old pre-insider build theme. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d6356b-87ff-8c3a-56ef-1270a823d3ab
* Version Independent ID: 4d6ae878-66cf-0e10-bdf3-bdd6054cbc9d
* Content: [What's new in Windows 10, version 1809](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1809.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1809.md)
* Product: **w10**
* GitHub Login: @dawnwood
* Microsoft Alias: **trudyha**

**Comment by jdeckerms** [comment]
@Vamork That would be useful information for the product team, could you submit it in the Feedback Hub? Thanks!

**Comment by Vamork** [comment]
Will’ do

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
