### ISSUE TITLE
What is the difference between Autopilot profile under inTune blade and Microsoft store for business?

### ISSUE THREAD

**Issue by rajeshkhanikar** [MicrosoftDocs/windows-itpro-docs#1760]
The Autopilot profile we create under inTune blade don't appear under the Microsoft store for business portal and vice versa. What are they related? Which one should we use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc947476-4fc3-cbb1-26c2-1e7dedb7892f
* Version Independent ID: 16bf5a1f-00d8-ad55-f66f-a9a38f115bb6
* Content: [Manage Windows device deployment with Windows Autopilot Deployment](https://docs.microsoft.com/en-us/microsoft-store/add-profile-to-devices#manage-autopilot-deployment-profiles)
* Content Source: [store-for-business/add-profile-to-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/add-profile-to-devices.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by damigs** [comment]
I would like to also understand the difference as both have the same info.  But been noticing that Intune has limits when trying to remove devices where I have had to go into MSFB to remove.

**Comment by emphasismemorandum** [comment]
Threading my email. Turn the virus off...

**Comment by jabooakes** [comment]
Did anyone get an answer to this? Intune and WSFB seem to be tied together in some ways and in others, they are not. I have created AP profiles in Intune and they show up in WSFB

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @rajeshkhanikar thank you for bringing this to our attention. Thanks for your feedback as well @damigs and @jabooakes. This documentation is intended for Microsoft Store for Business, that is why there is no mention of Intune (*it has its own doc category*). In this [test lab example documentation for Windows Auitopilot](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm), there is a note that says:

> Even if you registered your device in MSfB, it will still appear in Intune, though you might have to sync and then refresh your device list first.

It suggests that if you add devices to the MSfB, sync it to Intune if you want to use Intune profiles. Also, Microsoft recommends creation and assignment of profiles through Intune, to quote:

> ...any MDM will work with Autopilot, but others probably won’t have the same full suite of Windows Autopilot features as Intune. You’ll get the best experience from Intune.

See [Autopilot FAQs](https://docs.microsoft.com/windows/deployment/windows-autopilot/autopilot-faq). The links provided may not answer your questions directly, but they provide insights on the behavior of profiles.

If you have more questions about Windows Autopilot for Intunes and MSfB and their differences, I would recommend contacting support and opening a [service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance. 

On the other hand, if there is anything in this documentation that you think should be added or edited, please let us know. We want users to have the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful and up-to-date.

**Comment by jvsam** [comment]
Hi @rajeshkhanikar. We haven't received any response from you, so for now, we will close this issue. If you believe the documentation needs improvement, please re-open and provide recommendations on what needs to be changed or updated. Again, our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation.

Thank you for your feedback and for engaging with the community!

CC: Thank you as well @damigs and @jabooakes !

**Comment by jvsam** [comment]
@officedocsbot close
