### ISSUE TITLE
Windows Autopilot - Self Deploying Mode 

### ISSUE THREAD

**Issue by nimojg-microsoft** [MicrosoftDocs/windows-itpro-docs#1767]
Wondering why Windows Autopilot, in particular Self Deploying Mode it is not mentioned here as an option? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e0c4be4-5e7b-5433-e1f6-58869677e176
* Version Independent ID: 2e7c086b-cb48-e086-4ac9-b43f13f09591
* Content: [Set up Windows devices for education](https://docs.microsoft.com/en-us/education/windows/set-up-windows-10)
* Content Source: [education/windows/set-up-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/set-up-windows-10.md)
* Product: **w10**
* GitHub Login: @CelesteDG
* Microsoft Alias: **celested**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @nimojg-microsoft just to clarify, are you suggesting that we add Windows Autopilot option in the [Set up Windows devices for education](https://docs.microsoft.com/education/windows/set-up-windows-10) document? In the Table of Contents on the left, there is a link to the [Deploy Windows 10 in a school](https://docs.microsoft.com/education/windows/deploy-windows-10-in-a-school) guide. [Windows Autopilot](https://docs.microsoft.com/windows/deployment/windows-autopilot/windows-autopilot), including other [deployment scenarios](https://docs.microsoft.com/windows/deployment/windows-autopilot/self-deploying) are on a separate document category, but the docs are also applicable for Windows 10 Education. Perhaps this [blog article](https://educationblog.microsoft.com/en-us/2019/03/adventures-with-microsoft-autopilot-on-education-shared-devices-part-1/) may help as well.

Of course, we want users to have the best Windows 10 experience by ensuring the contents of the Microsoft Docs are useful, hence, if there is anything that needs to be added or edited in the documentation, please let us know. Thank you.

**Comment by jvsam** [comment]
Hi @nimojg-microsoft. We haven't received any response from you, so for now, we will close this issue. If you believe the documentation needs improvement, please re-open and provide recommendations on what needs to be changed or updated. Again, our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation.

Thank you for your feedback and for engaging with the community!

**Comment by jvsam** [comment]
@officedocsbot close
