### ISSUE TITLE
Modern DECICE Management?

### ISSUE THREAD

**Issue by mattybrown1985** [MicrosoftDocs/windows-itpro-docs#1772]
There's a typo in the BitLocker section.
"Through a Modern Decice Management (MDM) policy..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d6356b-87ff-8c3a-56ef-1270a823d3ab
* Version Independent ID: 4d6ae878-66cf-0e10-bdf3-bdd6054cbc9d
* Content: [What's new in Windows 10, version 1809](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1809.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1809.md)
* Product: **w10**
* GitHub Login: @dawnwood
* Microsoft Alias: **trudyha**

**Comment by shortpatti** [comment]
Closing. No typo found.

**Comment by mattybrown1985** [comment]
I've never heard of a decise, I think you mean device.  How is this not a typo??

**Comment by shortpatti** [comment]
Thanks for giving feedback.  I'm sorry but I did not find the typo you indicated.  It looks like it's been fixed.  Try refreshing your browser and try again. Let us know if you still see it.
