### ISSUE TITLE
The parameter is incorrect.

### ISSUE THREAD

**Issue by damian123** [MicrosoftDocs/windows-itpro-docs#1776]
In Windows 10 v. 1809 I get an error
&gt;mountvol X: /s
The parameter is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Vahhab** [comment]
I had the same problem. It is not clear where X: is referring to.

**Comment by sonictimm** [comment]
According to the official documentation, mountvol X: /s is valid syntax,
but the /s parameter only works on Itanium-based systems (NOT normal x86-64 systems)

Itanium CPUs are not generally found in consumer products, so step 3 in this solution doesn't work for [pretty much any of] us.
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mountvol

**Comment by zhangbo-miuNEST** [comment]
I have the same problem with win10  10.0.18362.53.
Please fix it ASAP!

The latest mountvol.exe doesn't support "/s" parameter!

**Comment by botmoto** [comment]
This could be because you either have multiple EFI partitions or no EFI partition. Can you please output a list of your partitions.

**Comment by illfated** [comment]
Please note that the /S parameter works as intended on Windows Server (2016).
Also note: `mountvol` on Windows Server OS versus Windows 10 / Windows 8.x has different parameters.

Related open issue tickets: #1556, #1776, #1915, #1924, #1984, #2216, #3234

Closed tickets: #2327, #2569, #2612, #2663, #2705, #2880, #2971, #3006, #3108, #3300

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
Update on related open/closed issue tickets.
- open tickets: #1556, #1776, #1924, #3234
- closed: #1915, #1984, #2216, #2327, #2569, #2612, #2663, #2705, #2880, #2971, #3006, #3108, #3300

**Comment by jvsam** [comment]
Hi @damian123, @Vahhab and @zhangbo-miuNEST just following up if your issues have been resolved. If not, please check the following:

1. [1915](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1915) - Addressed some issues like *incorrect parameter* error and recommendation to *check BIOS switches*, etc.
2. [1776](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1776) - Addressed some issues like *mountvol X: /s, incorrect parameter* error, etc.
3. Other related issues compiled by @illfated - #[1984](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1984), #[2216](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2216), #[2327](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2327), #[2569](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2569), #[2612](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2612), #[2663](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2663), #[2705](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2705), #[2880](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2880), #[2971](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2971), #[3006](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3006), #[3108](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3108), #[3300](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3300)

Helpful resources shared by the community: 
- https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#review-windows-defender-credential-guard-performance
- https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mountvol

**Important reminder:** Please be informed that this Github site is intended for product documentation. We want users to have the best Windows 10 experience by ensuring the contents of the Microsoft Docs are useful, accurate and up-to-date, hence, if there is anything we need to add or edit in the documentation, please let us know and we'll have it reviewed. Thank you.

**Comment by jvsam** [comment]
Hi again @damian123, @Vahhab and @zhangbo-miuNEST! We haven't heard or received any updates from you. We are hoping the suggestions and information shared here assisted in reaching the resolution of the issues you've raised. For now, we will close this issue, however, feel free to re-open if there is missing information or if you have suggestions to improve the quality of this documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by Tatsinnit** [comment]
:bulb: @jvsam Please note: I think this still the case and hasn't been resolved, I will also add a new bug where similar error happens for `/p` when user try to unmount the drive using `mountvol`, thanks,
