### ISSUE TITLE
Actualization please

### ISSUE THREAD

**Issue by patgerber** [MicrosoftDocs/windows-itpro-docs#1777]
Can you please provide App Lists for 1803 and 1809 Builds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9c3129d-3c8d-b508-f298-3333499bb180
* Version Independent ID: 97b70720-82d8-60a4-3958-00ceed34aa1b
* Content: [How to keep apps removed from Windows 10 from returning during an update](https://docs.microsoft.com/en-us/windows/application-management/remove-provisioned-apps-during-update)
* Content Source: [windows/application-management/remove-provisioned-apps-during-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/remove-provisioned-apps-during-update.md)
* Product: **w10**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Arefu** [comment]
You can resolve this mostly by yourself by using the PowerShell command 
``Get-AppxProvisionedPackage -Online`` for the currently running operating system as per [this](https://docs.microsoft.com/en-us/powershell/module/dism/get-appxprovisionedpackage?view=win10-ps) article.

Here is a really basic script to get the information you need should be: (so long as nothing changed behind the scenes with registry fluff)

``Get-AppxProvisionedPackage -Online | ForEach-Object { Get-AppXPackage $_.DisplayName | Select-Object Name,PackageFamilyName }``

**Comment by mariuselix** [comment]
If you have a look at the "Registry keys for provisioned apps" you will see that their registry key (to keep them deprovisioned) does not contain any versioning. You should be able to use that for any W10 build.

e.g: 
App: Microsoft.XboxApp
Full name: Microsoft.XboxApp_39.39.21002.0_neutral_~_8wekyb3d8bbwe
Registry key (Family name) : ...\Deprovisioned\Microsoft.XboxApp_8wekyb3d8bbwe

P.S: I checked for 1809 and the Xbox app has the same family name as in the list provided my Microsoft in this article (1709).

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @patgerber, just following up if you were able to find the information you need? If not, in addition to @Arefu and @mariuselix's suggestions, you may want to check the following documentations:

1. [Understand the different apps included in Windows 10](https://docs.microsoft.com/windows/application-management/apps-in-windows-10) - please see the *Provisioned Windows apps* list.
2. [How to keep apps removed from Windows 10 from returning during an update](https://docs.microsoft.com/windows/application-management/remove-provisioned-apps-during-update#registry-keys-for-provisioned-apps) - please see *Package names for apps provisioned in Windows 10, version 1709* and *Registry keys for provisioned apps* lists. 

We want users to have the best Windows 10 experience by ensuring the contents of the Microsoft Docs are useful, accurate and up-to-date, hence, if there is anything that needs to be added or edited in the documentation, please let us know. Thank you.

**Comment by jvsam** [comment]
Hi again @patgerber. We haven't received any response from you, so for now, we will close this issue. If you believe the documentation needs improvement, please re-open and provide recommendations on what needs to be changed or updated. 

Thank you for your feedback and for engaging with the community!

**Comment by jvsam** [comment]
@officedocsbot close
