### ISSUE TITLE
good explanation 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1780]
thanks great explanation 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b77c5ee5-a3fa-229a-e41a-65d9c1824c0e
* Version Independent ID: c201973e-7588-3588-a60f-1e6eda2a68b3
* Content: [Microsoft Edge - Security and privacy group policies](https://docs.microsoft.com/en-us/microsoft-edge/deploy/group-policies/security-privacy-management-gp#help-protect-against-web-based-security-threats)
* Content Source: [browsers/edge/group-policies/security-privacy-management-gp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/group-policies/security-privacy-management-gp.md)
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@RAJU2529, thank you for the great feedback.  Please let us know how we can do better.
