### ISSUE TITLE
this is the new feature

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1781]
Thanks to Microsoft for  added this  features to modify via  policy amd thanks to the author for  giving configuration 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e25cdec-6b2f-2e44-6512-83b13d13ff51
* Version Independent ID: f97436ae-01fc-a3bb-d0e8-2b20265ebc56
* Content: [Microsoft Edge - Prelaunch and tab preload group policies](https://docs.microsoft.com/en-us/microsoft-edge/deploy/group-policies/prelaunch-preload-gp)
* Content Source: [browsers/edge/group-policies/prelaunch-preload-gp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/group-policies/prelaunch-preload-gp.md)
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@RAJU2529, thank you for the feedback.  I'll pass this on to the rest of the Microsoft Edge team :)

**Comment by shortpatti** [comment]
@RAJU2529, thank you for the great feedback.  Please let us know how we can do better.
