### ISSUE TITLE
missing  settingsync.admx and settingsync.adml

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1782]
i could not able to find those files inside C:\windows\policydefinations\

please upload those files via one drive and  share the link here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4bd9c2b-6605-02c2-7eaf-f6bf4aecc6f4
* Version Independent ID: 701e94e8-b8c7-7397-7041-631ec972ff5e
* Content: [Microsoft Edge - Sync browser settings](https://docs.microsoft.com/en-us/microsoft-edge/deploy/group-policies/sync-browser-settings-gp)
* Content Source: [browsers/edge/group-policies/sync-browser-settings-gp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/group-policies/sync-browser-settings-gp.md)
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@RAJU2529, I'll reach out to the team to find out where the files are located or if they are missing in error.

**Comment by RAJU2529** [comment]
thanks , i solved my self , i downloaded and  updated latest templates  to C:\windows\policydefinitions\ 
and the  searched  settingsync.admx and  settingssync.adml , both files are validated ,
