### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1783]
thanks a lot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 085b8631-b59e-cfc7-faef-de9068cddadf
* Version Independent ID: b37a709b-7ed6-8e6d-8f03-9f5c2230e0dc
* Content: [Microsoft Edge - Extensions group policies](https://docs.microsoft.com/en-us/microsoft-edge/deploy/group-policies/extensions-management-gp)
* Content Source: [browsers/edge/group-policies/extensions-management-gp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/group-policies/extensions-management-gp.md)
* Product: **edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@RAJU2529, thank you for the great feedback.  Please let us know how we can do better.
