### ISSUE TITLE
Which team is designed microsoft edge browser

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1787]
OS  development team or  this article published team ,  I  remembering  at firsr release of this  browser without extensions ,it was really fast at time . Nowadays  more extensions  are  added in the  microosft store for thisbrowser , i feel little bit slow . From 1803 edition onwards i never installed chrome browser , i love to use  microosft browsers inluding  internet explorer 11. 

Thanks a lot for designed team

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aa5c0a6-acd2-4ec3-275d-3a684b3faaf4
* Version Independent ID: 6b475925-ca66-d47f-e180-92988683b37a
* Content: [Group Policy and Mobile Device Management settings for Microsoft Edge (Microsoft Edge for IT Pros)](https://docs.microsoft.com/en-us/microsoft-edge/deploy/available-policies)
* Content Source: [browsers/edge/available-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/available-policies.md)
* Product: **edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@RAJU2529, thank you for the great feedback.  Please let us know how we can do better.
