### ISSUE TITLE
Where can i get a list of xml elements in <EventData>?

### ISSUE THREAD

**Issue by mclabman** [MicrosoftDocs/windows-itpro-docs#1788]
[Введите отзыв здесь]

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 08809caa-9634-e969-6d48-3427570c0200
* Version Independent ID: fc29de97-b4e5-4b43-1696-ccb8695cefc1
* Content: [4675 (S) идентификаторы безопасности были отфильтрованы. (Windows 10)](https://docs.microsoft.com/ru-ru/windows/security/threat-protection/auditing/event-4675)
* Content Source: [windows/security/threat-protection/auditing/event-4675.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/threat-protection/auditing/event-4675.md)
* Product: **w10**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
Do these links help?
https://docs.microsoft.com/en-us/windows/desktop/wes/eventschema-elements
https://docs.microsoft.com/en-us/windows/desktop/wes/eventschema-eventtype-complextype

**Comment by mclabman** [comment]
No.
There data type description. The my question is What kind of data in EventData element? What I have to expect in attribute "name" in Data elements for security events?
For example for event 4624 the same property named "TargetUserName" in xml view and "Account Name" in text view.

**Comment by Justinha** [comment]
@mclabman Unfortunately the original author is no longer with Microsoft so I'm not sure I can get this info. I can forward this question to a general security discussion group here internally, but it might help to provide them with some more context. Can you share any more about what you are trying to achieve?

**Comment by Justinha** [comment]
@mclabman Here is a reply from an expert:

Since the Security log uses a manifest, you can get all of the event schema from the workstation.

Run this from an elevated powershell prompt:

$secEvents = get-winevent -listprovider "microsoft-windows-security-auditing"

The .events property is a collection of all of the events listed in the manifest on the local machine.
For each event there is a .Template property for the XML template used for the event properties (if there are any.)

I tried pasting in a text file with an example. And I'll find a place to publish this as a standalone topic. 

[SecEventsExample.txt](https://github.com/MicrosoftDocs/windows-itpro-docs/files/2474237/SecEventsExample.txt)

**Comment by Justinha** [comment]
@mclabman We published a topic to explain this: https://docs.microsoft.com/windows/security/threat-protection/auditing/how-to-list-xml-elements-in-eventdata

**Comment by mclabman** [comment]
Thank You. 
It almost is what I expected.

Now I have to match " TargetUserName " and one of the properties described in docs for this event.

A security-enabled local group was deleted.
Subject:
   Security ID:  WIN-R9H529RIO4Y\Administrator
   Account Name:  Administrator
   Account Domain:  WIN-R9H529RIO4Y
   Logon ID:  0x1fd23
Group:
   Security ID:  S-1-5-21-3108364787-189202583-342365621-1001
   Group Name:  SalesReps
   Group Domain:  WIN-R9H529RIO4Y
Additional Information:
   Privileges:  -

I think it is  TargetUserName =  Account Name . May be.  O r not? ;)



>Понедельник, 15 октября 2018, 21:33 +03:00 от Justin Hall <notifications@github.com>:
>
>@mclabman We published a topic to explain this:  https://docs.microsoft.com/windows/security/threat-protection/auditing/how-to-list-xml-elements-in-eventdata
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением,

mclabman@mail.ru

**Comment by Justinha** [comment]
@mclabman great question. Ted has written up the answer and I will add it to the topic.

**Comment by Justinha** [comment]
@mclabman I added how to map the names.

**Comment by mclabman** [comment]
Thank You. It is exactly what I want.
