### ISSUE TITLE
Is RNGCryptoServiceProvider is FIPS 140-2 complaint? 

### ISSUE THREAD

**Issue by GauravLad12** [MicrosoftDocs/windows-itpro-docs#1789]
Is RNGCryptoServiceProvider is FIPS 140-2 complaint? Please Kindly provide feedback for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e93f07bf-c0dd-dd83-d7bf-8562e7f197c3
* Version Independent ID: a6c44187-8ff1-6519-5291-146b4c1bf46c
* Content: [FIPS 140 Validation](https://docs.microsoft.com/en-us/windows/security/threat-protection/fips-140-validation#_microsoft_fips_140)
* Content Source: [windows/security/threat-protection/fips-140-validation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/fips-140-validation.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by MaratMussabekov** [comment]
Hello @GauravLad12 , according to this article, only classes that end in "CryptoServiceProvider" or "Cng" are allowed by FIPS and FIPS-2, so yes, it is complaint.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @GauravLad12 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
