### ISSUE TITLE
Good  Knowledge 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1790]
Well trained  authours , Thanks for  FAQ, Keep it up 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfa8383d-f50f-28ac-3b24-8bf6836ebfe9
* Version Independent ID: 015be277-4f02-bf04-9956-0dea83372e57
* Content: [Microsoft Edge - Frequently Asked Questions (FAQs) for IT Pros](https://docs.microsoft.com/en-us/microsoft-edge/deploy/microsoft-edge-faq)
* Content Source: [browsers/edge/microsoft-edge-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/microsoft-edge-faq.md)
* Product: **edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@RAJU2529, thank you for the great feedback.  Please let us know how we can do better.
