### ISSUE TITLE
add new feature

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1791]
Allow the users to change FONTS with in the settings of  edge browser

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f21c3fcb-61b2-42e1-f6ff-cd1f88f6142f
* Version Independent ID: 418002b6-7714-3bb2-394b-1d7bb9bc0539
* Content: [Change history for Microsoft Edge (Microsoft Edge for IT Pros)](https://docs.microsoft.com/en-us/microsoft-edge/deploy/change-history-for-microsoft-edge?tabs=2018)
* Content Source: [browsers/edge/change-history-for-microsoft-edge.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/change-history-for-microsoft-edge.md)
* Product: **edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@RAJU2529, you can use the **Feedback Hub** to request this functionality.
