### ISSUE TITLE
So many languages 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1792]
I really  wonder , how  the edge browser is  designed because it supported more than 20 langauges. 
I knew only 3 langauges.  Thanks for the authors  to made to know these specifications 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0892b344-8fa6-2832-d513-749b4196f129
* Version Independent ID: 8c2bb059-195a-011d-6d28-48b1d22f90c4
* Content: [Microsoft Edge for IT Pros](https://docs.microsoft.com/en-us/microsoft-edge/deploy/about-microsoft-edge)
* Content Source: [browsers/edge/about-microsoft-edge.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/about-microsoft-edge.md)
* Product: **edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **shortpatti**

**Comment by shortpatti** [comment]
@RAJU2529, thank you for the great feedback.  Please let us know how we can do better.
