### ISSUE TITLE
Deployment status = Completed

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-itpro-docs#1802]
Hello,

On each report I have a lot of 'Update Completed' status which is normal but I have also some 'Completed' ones which makes no sense since it apparently does not exist. 

Would you kindly illuminate on this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f79b9a28-784d-dd79-d438-4dac6c5f21c9
* Version Independent ID: 89123cef-fc73-d9d9-47c1-ebf755b516b9
* Content: [Update Compliance - Perspectives](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-perspectives)
* Content Source: [windows/deployment/update/update-compliance-perspectives.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/update-compliance-perspectives.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
*Comment:* Original submitter's profile has been deleted. Original issue is unclear, and it *may* or *may not* pertain to the documentation. Closing this issue.

**Comment by jvsam** [comment]
@officedocsbot close
