### ISSUE TITLE
Data formatting

### ISSUE THREAD

**Issue by BigIve** [MicrosoftDocs/windows-itpro-docs#1803]
Hi,
I would love to see some data formatting examples for the policy "Printers/PointAndPrintRestrictions".  As trying to translate the ADMX values into the required formatting is a real nightmare.
Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db383394-fa70-dba2-1a62-00a246a74ca9
* Version Independent ID: 7f25bcea-4578-5661-df33-e12176cde814
* Content: [Policy CSP - Printers](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-printers#printers-pointandprintrestrictions)
* Content Source: [windows/client-management/mdm/policy-csp-printers.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-printers.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@BigIve - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @BigIve Can you please share the current XML data for formatting you already have so that I can help you accordingly. 

Thanks.

**Comment by BigIve** [comment]
Hi Joinimran,
Since I first posted this question, I've started to use the Administrative Templates option for this item.  So far "touch wood" the Admin Templates are actually working for me.
Wish I could say the same for various other Custom Intune based policies though.  As the data formatting for restrcited groups and enterprisemodernappmanagement is a nightmare.

**Comment by joinimran** [comment]
Thank you for sharing more details on this. Please note that this is in the evolution phase and things can be complex. I would suggest you please share your feedback using the feedback channel so that it can be addressed in the future. 

Thanks.

@mypil Please guide the user how the user can share feedback with Microsoft for the same.

**Comment by mypil** [comment]
@BigIve - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**
You might find others have made a similar request that you can add to, or you can open a new one.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by alokshan** [comment]
here is the exact string which worked for me.

Name: Point and Print Enable
Oma-URI: ./Device/Vendor/MSFT/Policy/Config/Printers/PointAndPrintRestrictions
Data type: String
Value:
<enabled/>
<data id="PointAndPrint_TrustedServers_Chk" value="true"/>
<data id="PointAndPrint_TrustedServers_Edit" value="Printserver1.Contoso.com"/>
<data id="PointAndPrint_TrustedForest_Chk" value="false"/>
<data id="PointAndPrint_NoWarningNoElevationOnInstall_Enum" value="1"/>
<data id="PointAndPrint_NoWarningNoElevationOnUpdate_Enum" value="2"/>

**Comment by alokshan** [comment]
<enabled/>
<data id="PointAndPrint_TrustedServers_Chk" value="true"/>
<data id="PointAndPrint_TrustedServers_Edit" value="test.best.com"/>
<data id="PointAndPrint_TrustedForest_Chk" value="false"/>
<data id="PointAndPrint_NoWarningNoElevationOnInstall_Enum" value="1"/>
<data id="PointAndPrint_NoWarningNoElevationOnUpdate_Enum" value="2"/>

**Comment by illfated** [comment]
For readability, repeating the string from previous comment, adding line breaks:
```
Name: Point and Print Enable Oma-URI: ./Device/Vendor/MSFT/Policy/Config/Printers/PointAndPrintRestrictions
Data type: String Value: <enabled/>
<data id="PointAndPrint_TrustedServers_Chk" value="true"/>
<data id="PointAndPrint_TrustedServers_Edit" value="Printserver1.Contoso.com"/>
<data id="PointAndPrint_TrustedForest_Chk" value="false"/>
<data id="PointAndPrint_NoWarningNoElevationOnInstall_Enum" value="1"/>
<data id="PointAndPrint_NoWarningNoElevationOnUpdate_Enum" value="2"/>
```

**Comment by mypil** [comment]
@officedocsbot reopen

**Comment by joinimran** [comment]
@BigIve , Thank you so much for sharing feedback. As suggested, I have forwarded the request based on your shared content to be added in the doc to doc owner. As soon as it gets approved, the changes will be reflected in the doc.

We really appreciate your feedback and making Microsoft documents helpful for the rest of the community. 

Thanks.

**Comment by mypil** [comment]
@BigIve @alokshan @illfated  - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
