### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by andrewbettany** [MicrosoftDocs/windows-itpro-docs#1804]
Link to the Encrypted Hard Drive redirects to BitLocker.  It should redirect to the Encrypted Hard Drive resource page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1bdee57-c525-2768-971c-235aa42658d5
* Version Independent ID: a8d801ed-f573-b9bf-84c4-57777c60fa95
* Content: [Information protection (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/)
* Content Source: [windows/security/information-protection/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/index.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@andrewbettany Thanks for reporting the link error. It's been fixed.
