### ISSUE TITLE
Status definition

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-itpro-docs#1805]
Hello,

We use 1607, 1703, 1709, 1803 and we have different states returned which aren't all evident:

Deployment Status: Unknown, In Progress, Progress Stalled, Failed, Update Completed, Completed, Deferred and Canceled.

Detailed Status: Download started, Download succeeded, Download hand off, Install hand off, Reboot pending, Service Stack Downloaded, Update offered, Update detected.

Would it be possible to point us to the information detailing each one of those?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f8910d-9d31-f51b-8bc1-82b5d547935e
* Version Independent ID: 100142bf-a6c3-f756-e275-9e64c78d2fde
* Content: [Update Compliance - Security Update Status report](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-security-update-status)
* Content Source: [windows/deployment/update/update-compliance-security-update-status.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/update-compliance-security-update-status.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by cinglis-msft** [comment]
The top states are in the documentation: https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-need-attention#update-issues

The bottom states are lower level “simplifications” of the actual state devices are in. There are many events in the download process, and we condense it to a simpler level while still giving more detailed deployment information than the above sets of states so there is greater context if things are stuck/go wrong.

**Comment by IWouldLikeToKnow** [comment]
@cinglis-msft My request is to know exactly what which state at it's lowest level means and the combinations between deployment and detailed status.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ojrb - As discussed, please work on this issue. Thanks.

**Comment by jaimeo** [comment]
@cinglis-msft can you advise here?

**Comment by ojrb** [comment]
Sure @mypil working on it !

**Comment by ojrb** [comment]
Hi @mypil  the PR #3839 solved this issue ! Please review and Merge !

**Comment by mypil** [comment]
@cinglis-msft -  Thank you for submitting feedback.

From our understanding, the issue has been answered by @jaimeo [here](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3839#issuecomment-499563764). If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
