### ISSUE TITLE
Windows 1709 and up??

### ISSUE THREAD

**Issue by Richard1959** [MicrosoftDocs/windows-itpro-docs#1807]
After installing full ADK onto Win 10 Pro 1803 We cannot find the MultiAppAssignedAccessSettings option in  Windows Configuration Designer. It seems we have to downgrade Windows to 1709, effectively a clean install.

We want a tool to configure a multi app kiosk across multiple Win 10 versions and do not want to downgrade this install to 1709 to design the tool, can you advise if its possible please.

**Comment by jdeckerms** [comment]
@Richard1959 MultiAppAssignedAccessSettings is available in Windows Configuration Designer for 1709, 1803, and 1809. When you start the provisioning project, make sure you're selecting "For all Windows **desktop** editions". If you select "All Windows editions", only settings that are common to desktop, mobile, Surface Hub, and HoloLens are shown.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @RicardoNiepel we just want to follow-up if you were able to successfully configure your multi app kiosk. As confirmed by @jdeckerms, "*MultiAppAssignedAccessSettings is available in Windows Configuration Designer for 1709, 1803, and 1809*."

You can also refer to this documentation:  [Set up a multi-app kiosk](https://docs.microsoft.com/windows/configuration/lock-down-windows-10-to-specific-apps). We want users to have the best Windows 10 experience by ensuring the contents of the Microsoft Docs are useful, accurate and up-to-date, hence, if there is anything we need to add or edit in the documentation, please let us know and we'll have it reviewed.

**Comment by jvsam** [comment]
Hi again @RicardoNiepel. We haven't received any response from you, so for now, we will close this issue. If you believe the documentation needs improvement, please re-open and provide recommendations on what needs to be changed or updated. Thank you for engaging with the community!

**Comment by jvsam** [comment]
@officedocsbot close
