### ISSUE TITLE
User

### ISSUE THREAD

**Issue by Billwzw** [MicrosoftDocs/windows-itpro-docs#1810]
Documentation would be improved if you indicate clearly that this software is portable and does not install as is typical for Microsoft.  Consequently it does not show up in the start menu under the proper name, nor does it show up as a desktop icon.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5bb1ce3-9128-5385-4417-d22eb5f8cb77
* Version Independent ID: cb6ba731-a2c2-e9b9-7c3e-db781b1b5222
* Content: [Microsoft Safety Scanner Download](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/safety-scanner-download#how-to-run-a-scan)
* Content Source: [windows/security/threat-protection/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/intelligence/safety-scanner-download.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by Dansimp** [comment]
Fixed. Added note to intro
