### ISSUE TITLE
policy-csp-eventlogservice.md

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#1813]
Can someone fix the event log CSP so we can change the event log control behaviour of all event log types (application, security, system and setup) instead of only the application as its setup on the CSP EventLogService/ControlEventLogBehavior

[https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-eventlogservice](url)

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @schenardie, we definitely want to help you but we need need more information from you.

1. Is it about the [Policy CSP - EventLogService](https://docs.microsoft.com/windows/client-management/mdm/policy-csp-eventlogservice) documentation? Please be informed that this Github site is intended for product documentation. We want users to have the best Windows 10 experience by ensuring the contents of the Microsoft Docs are useful, accurate and up-to-date, hence, if there is anything we need to add or edit in the documentation, please let us know and we'll have it reviewed. 

2. Are you experiencing issues in setting up policy controls?  If so, and the answer is not this [documentation](https://docs.microsoft.com/windows/client-management/mdm/policy-csp-eventlogservice), I suggest that you open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant for immediate assistance. 

3. Is the request something that is not yet supported? Please submit your feedback to the Windows 10 [User Voice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub) hub. You feedback goes directly to the engineering team of the selected feature or product.

Thank you and looking forward to getting an update from you.

**Comment by jvsam** [comment]
Hi again @schenardie. We haven't received any response from you, so for now, we will close this issue. If you believe the documentation needs improvement, please re-open and provide recommendations on what needs to be changed or updated. Thank you for engaging with the community!

**Comment by jvsam** [comment]
@officedocsbot close
