### ISSUE TITLE
Help Accessibility settings blocked

### ISSUE THREAD

**Issue by AntoinetteSp** [MicrosoftDocs/windows-itpro-docs#1823]
I work in a special needs classroom.   Our IT department blocks important accessibility settings.   How can I pursuade them to let my students have these helpful tools!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fd15a17-8d9e-88a2-c003-490f9883a418
* Version Independent ID: 4f3a0aae-a8a3-0057-3434-ae8a267e1809
* Content: [Windows 10 accessibility information for IT Pros (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/windows-10-accessibility-for-itpros)
* Content Source: [windows/configuration/windows-10-accessibility-for-ITPros.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/windows-10-accessibility-for-ITPros.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @AntoinetteSp thank you for your question. Please be informed that this Github site is intended for product documentation. We want users to have the best Windows 10 experience by ensuring the contents of the Microsoft Docs are useful, accurate and up-to-date, hence, if there is anything we need to add or edit in the documentation, please let us know and we'll have it reviewed. 

Now going back to your question, Windows 10 is loaded with accessibility features that would definitely help your students. These resources may help you in *selling the idea* to your IT department. 

1. [Accessibility resources at Microsoft](https://www.microsoft.com/accessibility).
2. [Customer accessibility stories](https://www.microsoft.com/accessibility/stories). More videos available [here](https://www.youtube.com/user/MSFTEnable).
3. [Accessibility blog](https://blogs.msdn.microsoft.com/accessibility/).

*Personally*, I believe showing them real stories about assistive technology and how it helps **all people** (*not just your students*) will make your *pitch* even more compelling. 

There is also the [Windows Disability Answer Desk](https://www.microsoft.com/Accessibility/disability-answer-desk) if you have product issues, accessibility questions or questions about the use of Assistive technology.

I hope the resources I've provided will help you. Thanks.

**Comment by jvsam** [comment]
Hi again @AntoinetteSp. We haven't received any response from you, so for now, we will close this issue. If you believe the documentation needs improvement, please re-open and provide recommendations on what needs to be changed or updated. Thank you for engaging with the community!

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by MamaDoc** [comment]
Thank you.    I have been with out a device due to hackers.   Lost All  info has been blocked from my Accessibility.

**Comment by MamaDoc** [comment]
Information about hackers just received from GitHub. Dating so far NOV. 2018.  Hackers have been blocking my accounts some time.   The help I needed was blocked
