### ISSUE TITLE
Good and great Explanation 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1824]
Thanks for the information about these policies, its really useful, just now i applied some of the policies.
Thanks for the authors and keep it up

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abd3113-b803-87b6-ef7f-6893bcc5ceb5
* Version Independent ID: 6f7ca1ee-d19c-42bb-7db5-6158fc160e32
* Content: [Manage connections from Windows operating system components to Microsoft services (Windows 10)](https://docs.microsoft.com/en-in/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services)
* Content Source: [windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by RAJU2529** [comment]
i downloaded the policies explanation in pdf format ,

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@RAJU2529 - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by RAJU2529** [comment]
Sorry sir,   I am unable use feedback hub on windows 10. From last onwards  I configured settings such that windows should not use diagnostics datas and feedback hub in group policy editor and in registry also.
But I am unable to use feedback hub, because I forgot those settings thats my problems.
Any way thanks for your information
