### ISSUE TITLE
link doesn't work

### ISSUE THREAD

**Issue by Shachar2like** [MicrosoftDocs/windows-itpro-docs#1825]
link on the top of the article "Looking for consumer information? See Customize the Start menu" doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 061157dc-8fc8-3f9d-c01f-37f22fbdf1c7
* Version Independent ID: 0b0b6797-9367-eb7c-22ef-5f2b8bbfe592
* Content: [Start layout XML for desktop editions of Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/start-layout-xml-desktop)
* Content Source: [windows/configuration/start-layout-xml-desktop.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/start-layout-xml-desktop.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@Shachar2like Thanks for letting us know, I'll get the link fixed today.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
