### ISSUE TITLE
Need more clarity on usage in Intune Azure portal

### ISSUE THREAD

**Issue by deshpandeguy** [MicrosoftDocs/windows-itpro-docs#1827]
Thanks for this article. Some feedback
The videos shows demo on the Intune classic portal, which is not existing anymore.
Could you update the videos for showing demo in Azure portal?
Azure portal do not have the option of String XML direct editing/adding the value.
It has either string or string (XML File). If I choose XML file, do I need to create an XML and upload it? or just adding the data value pairs as string would be sufficient?
One more question, while adding a OMA-URI setting in a custom profile, I will be mentioning the OMA-URI, then in the data field, do I need to just paste the data section of SynML (as example shown above) or whole SyncML syntax need to be pasted (which also contains LocURI)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14d97fd9-b060-7bd5-1bc1-57efa474f75f
* Version Independent ID: be3a74fc-cac8-9b2c-dcc8-edc83cdf111f
* Content: [Enable ADMX-backed policies in MDM](https://docs.microsoft.com/en-us/windows/client-management/mdm/enable-admx-backed-policies-in-mdm)
* Content Source: [windows/client-management/mdm/enable-admx-backed-policies-in-mdm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enable-admx-backed-policies-in-mdm.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by jdeckerms** [comment]
@deshpandeguy Thanks for the feedback, I'll use it to plan future improvements to this topic.

**Comment by mypil** [comment]
@officedocsbot close
