### ISSUE TITLE
RDP Access

### ISSUE THREAD

**Issue by joe-oli** [MicrosoftDocs/windows-itpro-docs#1828]
It is not clear whether this section applies to attempts to login using RDP or how does it relate to the registry entry.
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\RemoteAccess\Parameters\AccountLockout

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3974da73-1577-dbaf-00ec-f6fb6eee35df
* Version Independent ID: a562ec45-0c96-733b-2bef-c12f627dc02f
* Content: [Account Lockout Policy (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/account-lockout-policy)
* Content Source: [windows/security/threat-protection/security-policy-settings/account-lockout-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/account-lockout-policy.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@joe-oli They are managed separately. See https://support.microsoft.com/en-us/help/816118/how-to-configure-remote-access-client-account-lockout-in-windows-serve

**Comment by joe-oli** [comment]
@Justinha yes i thought that may be the case, only because i also stumbled upon the article which you referred to (which incorrectly states applies to Win Server 2003, no mention of Win 10). In any case both docs need updating.

**Comment by Justinha** [comment]
@joe-oli Thanks for the suggestion. I added a Note with a link to the support topic. The support topic itself has to be updated by another team, so I submitted a request for that.
