### ISSUE TITLE
OMS is depreciated

### ISSUE THREAD

**Issue by davisdre** [MicrosoftDocs/windows-itpro-docs#1830]
Can you upgrade step 1 to reflect the Azure portal now since OMS is/will be depreciated? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4273a259-c3c7-dca7-6353-954068d740a7
* Version Independent ID: 1084ea77-95c4-4e4a-da6c-f4d8668f9ebf
* Content: [Enrolling devices in Windows Analytics (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started#copy-your-commercial-id-key)
* Content Source: [windows/deployment/update/windows-analytics-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-get-started.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by chiners68** [comment]
Can you give example where to get the Comercial Key from the Log analytics portal not OMS.

**Comment by ewright049** [comment]
If you go the Azure Portal you can find it here Home
Solutions >
WaaSUpdateInsights(MDAssessment-PC-Analytics) > Update Compliance Settings

**Comment by mariuszo-at-microsoft-com** [comment]
Agree, this should be fixed ASAP, as it is rather misleading

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by illfated** [comment]
This issue has been resolved already, right?
Latest OMS removal in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/a7223d7a54edd7e046ef5c21aab324df5c73c285
(from what I can tell).

**Comment by mypil** [comment]
@davisdre -  Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
