### ISSUE TITLE
Error code 61

### ISSUE THREAD

**Issue by KwintenB** [MicrosoftDocs/windows-itpro-docs#1840]
About 10% of my pc's are reporting error code 61. This error is not mentioned in the docs. Please update the table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f029a728-1f53-4576-a6ca-8a19a92626e6
* Version Independent ID: 85f27ad5-84e2-0787-082f-59d2d66c99b5
* Content: [Upgrade Readiness deployment script (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-deployment-script#error-codes)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-deployment-script.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-deployment-script.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by jaimeo** [comment]
PM tells me that 61 means "CleanupOneSettings failed with an exception," if that's any help in the meantime. We're working together to flesh this out into the topic and also see if other exit codes (and explanations) are missing.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @KwintenB and @Argon0 , we appreciate your patience on this matter. Have you had a chance to look at the documentation recently? *Error 61* and *Error 63* are now added in the list of Exit Codes with suggested fixes. *Error 4* is also listed. We're now marking this issue as resolved.

We want users to have the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, relevant and up-to-date. Suggestions, comments and feedback to improve the docs are always welcome. Thank you for engaging with the community!

**Comment by jvsam** [comment]
Hi again @KwintenB and @Argon0. We haven't received any response from you, so for now, we will close this issue. If you believe the documentation needs improvement, please re-open and provide recommendations on what needs to be changed or updated. 

Thank you for your feedback and for engaging with the community!

**Comment by jvsam** [comment]
@officedocsbot close
