### ISSUE TITLE
Description for AUOptions = 2 partially in conflict with other Microsoft sources

### ISSUE THREAD

**Issue by illfated** [MicrosoftDocs/windows-itpro-docs#1841]
This page states that AUOptions = 2 means the following:
&gt; notify for download and automatically install updates

Other sources I have found, both Microsoft Technet & non-Microsoft, say that it means:
&gt; Notify for download and notify for install

That is a 50% difference in description, but because we are talking about system behaviour it becomes 100% different in effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184809a-63ff-ecc2-ab67-9c9f4df900f8
* Version Independent ID: ac25ee6c-4c57-58b3-1313-e4a53f53c5a1
* Content: [Manage device restarts after updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-restart)
* Content Source: [windows/deployment/update/waas-restart.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-restart.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by illfated** [comment]
Thank you for the issue edit.
I did not see the github environment when I commented on the doc page.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@illfated - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by jaimeo** [comment]
Looks good; I've requested it be merged (I do not have the perms to merge it myself.)

**Comment by illfated** [comment]
Thank you for your time and for following up on this. 👍 
I agree and accept the solution, so this issue is solved & closed.
