### ISSUE TITLE
Citrix in Kiosk Edge

### ISSUE THREAD

**Issue by A-Everson** [MicrosoftDocs/windows-itpro-docs#1843]
Hello I am working on delivering applications to end users via Citrix through Edge. In normal mode this runs smoothly, I would like to leverage the security advantage of kiosk in 1809. however in Kiosk mode I receive a .ica file error. Is there a way to allow the Edge Kiosk to load the .ica files? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f840fa14-a379-d297-c3f7-ada05ec299d6
* Version Independent ID: 81396f7b-7506-43cd-fd9a-4066719a6eb2
* Content: [Deploy Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/microsoft-edge/deploy/microsoft-edge-kiosk-mode-deploy#provide-feedback-or-get-support)
* Content Source: [browsers/edge/microsoft-edge-kiosk-mode-deploy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/microsoft-edge-kiosk-mode-deploy.md)
* Product: **edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
Hi @A-Everson, I'll reach out to the engineering team about your question.

**Comment by OftKilted** [comment]
@A-Everson Doesn't the .ICA file call the installation of the Citrix client? It's leveraging either ActiveX or a Plugin to use Citrix.

Here's a discussion directly referencing the issue:
https://discussions.citrix.com/topic/383915-windows-10-edge-browser-prompts-for-opening-ica-file/

Back in 2015 Citrix had a blog post talking about issues with Edge in Citrix and the article mentions that the workarounds that were suggested broke in 2017 due to additional security added to Edge.

https://www.citrix.com/blogs/2015/08/10/storefront-3-0-and-windows-10-edge-browser

**Comment by A-Everson** [comment]
You are correct, these options can fix the issue I am seeing however, how can they be applied to the Kiosk login? without the Kiosk enabled in Edge I am able to use Citrix seamlessly, but when using Kiosk Edge through Assigned Access I get this error. There must be some way to enable the plugins under Assigned Access

**Comment by shortpatti** [comment]
Are you trying single-app or multi-app?

**Comment by A-Everson** [comment]
Both

**Comment by shortpatti** [comment]
@A-Everson, I'll pass this on to the engineering team for assistance :)

**Comment by shortpatti** [comment]
Hi @A-Everson,

Single app as the name suggests only allows a single app to run. Citrix Receiver is a second app, hence not possible. This is by design.

It should work in multi-app. Can you give me specific details about what doesn't work with multi-app?

**Comment by A-Everson** [comment]
In both single and multi-app modes I receive the error:
![image](https://user-images.githubusercontent.com/44062296/47017554-8d9f8300-d120-11e8-9e96-99273570ecad.png)

I can click "Detect"

![image](https://user-images.githubusercontent.com/44062296/47017718-f850be80-d120-11e8-89db-785cb7f0efdd.png)

Then click "already installed" and it will load the storefront screen as usual

when attempting to run a app from storefront I receive:
![image](https://user-images.githubusercontent.com/44062296/47017766-2504d600-d121-11e8-83f3-3c27e854637c.png)

Presumably because kiosk mode will not allow the plugin to load.  

This all works outside of Kiosk in Edge. Is there a way to install the plugin under the Kiosk user so I can use this resource?

**Comment by shortpatti** [comment]
@A-Everson, try creating the kiosk user account and log into the account to install Citrix Receiver before setting up assigned access.

**Comment by shortpatti** [comment]
@A-Everson, the engineering team is aware of this issue and they are working to resolve it.

**Comment by bsod2k** [comment]
Is there any update to this?

**Comment by therealchrisrooney** [comment]
I would be interested in a solution to this also..

**Comment by DomiOder** [comment]
Any updates on this @shortpatti ? We would also be interested in this solution.

**Comment by A-Everson** [comment]
Still no fix or answer for this. Disappointing; my organization has begun looking into Linux based environments that can do this function. It would be nice if Microsoft had a fix for this.

**Comment by e0i** [comment]
@shortpatti Any updates on this issue, we would like to follow up. Thanks.

**Comment by DomiOder** [comment]
@e0i as always Microsoft (@shortpatti)  is just ignoring this. No updates, no solution...
So disappointing and bad customer service!

**Comment by andrefboliveira** [comment]
> @shortpatti Any updates on this issue, we would like to follow up. Thanks.

@e0i Please reach out to engineering team again. As @shortpatti is no longer working at Microsoft

**Comment by A-Everson** [comment]
There was no response to my query from Microsoft. I have given up utilizing Windows and purchased a Linux option to provide the desired desktop experience on the 3000+ endpoints. 8+ months without even an acknowledgement from Microsoft is unacceptable customer service experience.

**Comment by OftKilted** [comment]
@a-everson Did you ever try handling this via IE11 and Kiosk mode?

**Comment by andrefboliveira** [comment]
> There was no response to my query from Microsoft. I have given up utilizing Windows and purchased a Linux option to provide the desired desktop experience on the 3000+ endpoints. 8+ months without even an acknowledgement from Microsoft is unacceptable customer service experience.

@A-Everson did you try to contact  [Microsoft Support](https://support.microsoft.com/en-us/contactus/)? There is also [BusinessSupport ](https://support.microsoft.com/en-us/hub/4343728/support-for-business) for business scenarios as seems to be your case. I am sure that you would get a better Customer Service Experience there 😊.

**Comment by VLG17** [comment]
@A-Everson i know a lot of time has passed since you asked and according to the thread you did not receive an appropriate answer, but do you still want us to look into this/test it and come back to you?

**Comment by e0i** [comment]
Hello @A-Everson  ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
