### ISSUE TITLE
Scheduled task doesn't exist.

### ISSUE THREAD

**Issue by jeremyhagan** [MicrosoftDocs/windows-itpro-docs#1848]
I've implemented this on Hybrid Domain Joined W10 1709 and 1803 and the scheduled task shown in this document doesn't exist. There is a GUID subfolder under EnterpriseMgmt, but it still doesn't have a scheduled task with the listed name. However my device shows up in InTune as compliant. So I guess it is enrolled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by ermacia91** [comment]
The task disappears and gets replaced after device is MDM enrolled. So, if you enabled it and it succeeded enrollment, the task will not show up.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @jeremyhagan we appreciate your patience on this matter and thank you for your feedback. Is it working for you now? We want users to have the best Windows 10 experience by ensuring the contents of the Microsoft Docs are useful, accurate and up-to-date, hence, if there is anything we need to add or edit in the documentation, please let us know and we'll have it reviewed. 

Thanks @ermacia91 for your feedback. Your help is appreciated!

@SNFHI360 were you asking for a workaround regarding your issue? Or is your question related to the information in the document, e.g. inaccurate, lack information, etc.? This Github site is intended for product documentation, so if you have suggestions, comments and feedback to improve the docs, let us know. If you have issues related to Windows 10 features or products, you can contact [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10). Thank you.

**Comment by jvsam** [comment]
Hello again @jeremyhagan. We haven't received any response from you, so for now, we will close this issue. If you believe the documentation needs improvement, please re-open and provide recommendations on what needs to be changed or updated. 

Thank you for your feedback and for engaging with the community! 

CC: Thank you as well @SNFHI360 !

**Comment by jvsam** [comment]
@officedocsbot close
