### ISSUE TITLE
Upgrade Readiness blog url points to old URL

### ISSUE THREAD

**Issue by mm1nIPOVdDsu** [MicrosoftDocs/windows-itpro-docs#1850]
A link in the article [Getting Started with Upgrade Readiness](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-get-started#data-collection-and-privacy) for [blog entry at the current address](https://blogs.technet.microsoft.com/upgradeanalytics/2018/07/10/this-blog-has-moved/) details that the location of the blog has changed to https://aka.ms/blog/WindowsAnalytics (or https://techcommunity.microsoft.com/t5/Windows-Analytics-Blog/bg-p/WindowsAnalyticsBlog for the direct link).

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @mm1nIPOVdDsu thank you for bringing this to our attention and we appreciate your patience on this matter. You are correct, the link redirects to the new *[Windows Analytics Blog](https://techcommunity.microsoft.com/t5/Windows-Analytics-Blog/bg-p/WindowsAnalyticsBlog)* site. I will forward this issue to the Windows writing team to get the link updated.

Thank you for engaging with the community!

Content: https://docs.microsoft.com/windows/deployment/upgrade/upgrade-readiness-get-started
Content source: https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-get-started.md

**Comment by jvsam** [comment]
Hi again @mm1nIPOVdDsu, the suggested update to this documentation via Pull Request (PR) #4224 has been approved and merged. It will be displayed at docs.microsoft.com in the next scheduled publishing run. You can verify the changes at this URL: https://docs.microsoft.com/windows/deployment/upgrade/upgrade-readiness-get-started. We will now close this issue but we'll provide an update here to inform you when the changes are live.

Thank you for your feedback to help improve the contents of this document and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
