### ISSUE TITLE
English MDOP ADMX Template download is broken...

### ISSUE THREAD

**Issue by RolandDeschain17** [MicrosoftDocs/windows-itpro-docs#1854]
As of 10/12/18, the MDOP Group Policy Templates link gives you a working download location, but it's filled with ADML files for tons of languages - and they all just have numbers after them, with no corresponding way to determine language (such as EN-US for United States English), and that identifier isn't in the ADML files themselves. There are several that look like EN-US files with different numbers at the end, but you can't tell which one to use. Please fix this, Microsoft.....The list of files in it currently looks like this:

BitLockerManagement (153).adml
BitLockerManagement (154).adml
BitLockerManagement (155).adml
BitLockerManagement (156).adml

Etc...some of those are in English, some are in random other languages without a language identifier, etc.; so you're left to guess which ones are the right ones you need. There's no matrix document in it or anything telling you which number is which language, either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 758d5448-7062-2519-a47b-7763a595471e
* Version Independent ID: 4e966ec3-b088-604d-a8c5-15e89a398ded
* Content: [How to Download and Deploy MDOP Group Policy (.admx) Templates](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/solutions/how-to-download-and-deploy-mdop-group-policy--admx--templates)
* Content Source: [mdop/solutions/how-to-download-and-deploy-mdop-group-policy--admx--templates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/solutions/how-to-download-and-deploy-mdop-group-policy--admx--templates.md)
* Product: **w8**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by CCDFischer** [comment]
So I had this same issue, you MUST follow the instructions to expand the .cab file correctly to preserve the file structure and thus know what files are what language. I would suggest adding into this document how to expand the .cab file as most ADMX templates come as a self extracting executable, not as a .cab, so admins may not be familiar with how to correctly expand the file.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @RolandDeschain17 we appreciate your patience on this matter. Were you able to successfully download the cab file with the correct folder structure? Have you also tried @CCDFischer's suggestion? I tried downloading the file and extracted it using a decompressing tool and I have seen the correct folder structure. In each folder, the files are also grouped per language, e.g. en-us, etc.

@CCDFischer can you provide more information on your suggestion so we would know *what* and *how* to correctly add it to the documentation? Currently, expanding the downloaded .cab file is in the doc as well as in the *Install Instructions* from the download page. Thank you.

Looking forward to hearing from both of you!

**Comment by jvsam** [comment]
Hi again @RolandDeschain17. We haven't received any response from you, so for now, we will close this issue. If you believe the documentation needs improvement, please re-open and provide recommendations on what needs to be changed or updated. We want users to have the best Windows 10 experience by ensuring the contents of the Microsoft Docs are useful, accurate and up-to-date.

Thank you for your feedback and for engaging with the community!  

CC: Thank you too @CCDFischer!

**Comment by jvsam** [comment]
@officedocsbot close
