### ISSUE TITLE
Missing parts for VMWARE and HAXM users

### ISSUE THREAD

**Issue by Vahhab** [MicrosoftDocs/windows-itpro-docs#1862]
A very important part is missing which lead problems for me to launch VMWARE on my windows 10 pro due to presence of Credential Guard.
It was this part:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\HypervisorEnforcedCodeIntegrity
Should set to:
Enabled = 0

Thanks to  Ulises2k for his/her answer at https://social.technet.microsoft.com/Forums/windows/en-US/8004c3bd-7d57-40ce-93de-0b1a6babd64c/how-i-can-disable-credential-guard?forum=win10itprovirt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Vahhab** [comment]
This was the case for Disabling device guard/credential guard

**Comment by Justinha** [comment]
@Vahhab Thanks for sharing and sorry to hear you had trouble. As mentioned in the forum thread, the issue you are raising is not related to Credential Guard. Possibly you could look to add this somewhere in Hyper-V docs.

**Comment by Vahhab** [comment]
Thanks for your notice and attention
