### ISSUE TITLE
Mobile Apps is now Client Apps

### ISSUE THREAD

**Issue by jeremyhagan** [MicrosoftDocs/windows-itpro-docs#1864]
In the Intune portal the tile is now labelled Client Apps. Please update the doco

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e35d03-23d6-e006-b083-582bd33d4ae4
* Version Independent ID: 7ab70933-c45e-c601-548b-07ad0c89cd59
* Content: [| Microsoft Docs](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/wip-learning)
* Content Source: [windows/security/information-protection/windows-information-protection/wip-learning.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/wip-learning.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@jeremyhagan Thanks for the heads up. Those steps have been updated.
