### ISSUE TITLE
Link 404

### ISSUE THREAD

**Issue by gutjahr** [MicrosoftDocs/windows-itpro-docs#1869]
The link to "User Experience Virtualization feedback site" does not work (404)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdce558d-f9d0-87d9-ca4f-c9f20ffc64a4
* Version Independent ID: 4ee887ad-12e1-f9b6-fb26-3fb7af74c087
* Content: [User Experience Virtualization for Windows 10, version 1607](https://docs.microsoft.com/en-us/windows/configuration/ue-v/uev-for-windows)
* Content Source: [windows/configuration/ue-v/uev-for-windows.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/ue-v/uev-for-windows.md)
* Product: **w10**
* GitHub Login: @MaggiePucciEvans
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@gutjahr Thanks for letting us know, we'll remove the link.

**Comment by mypil** [comment]
@gutjahr - Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
