### ISSUE TITLE
PowerShell script link returns a 404 error.

### ISSUE THREAD

**Issue by chjone** [MicrosoftDocs/windows-itpro-docs#1885]
Looks like the link should point to: 'https://www.powershellgallery.com/packages/WindowsDefender_InternalEvaluationSettings/1.2/Content/WindowsDefender_InternalEvaluationSettings.ps1'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b674bf82-b910-2b06-86f4-f454dc74026f
* Version Independent ID: 7c8d5db0-107a-ced6-106e-ef11e80e5c7c
* Content: [Evaluate Windows Defender Antivirus](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/evaluate-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/evaluate-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/evaluate-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by illfated** [comment]
Good point, thanks for pointing it out. From the "Evaluate Windows Defender Antivirus" page:
> Download the PowerShell script to automatically configure the settings
https://www.powershellgallery.com/packages/WindowsDefender_InternalEvaluationSettings/1.2/DisplayScript

**Comment by andreabichsel** [comment]
Thank you for your comment. The page appears to be working now, and it lists different versions of the script. Version 1.31 is the latest.
