### ISSUE TITLE
Misspelled Word

### ISSUE THREAD

**Issue by PhillyUrbs** [MicrosoftDocs/windows-itpro-docs#1886]
Windows 10 includes the compatibility update, so you will automatically have the latest compatibility update so long as you continue to keep your Windows 10 devices up-to-date with cummulative updates.    Cumulative is spelled incorrectly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4273a259-c3c7-dca7-6353-954068d740a7
* Version Independent ID: 1084ea77-95c4-4e4a-da6c-f4d8668f9ebf
* Content: [Enrolling devices in Windows Analytics (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started)
* Content Source: [windows/deployment/update/windows-analytics-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-get-started.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Fixed.

**Comment by illfated** [comment]
This issue can be closed.

**Comment by mypil** [comment]
@PhillyUrbs - From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

Thank you for reporting and making the docs better. Much appreciated.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
