### ISSUE TITLE
Deployment values???

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#1894]
When publishing OMAURI/CSP values, Each "policy" must have have a name, description, values, explanation of what the policy does. 

and.. specifically Data type, as well as a supported Configuration value so an Admin may deploy with SCCM or Intune, or other MDM. (no secret there)

Why are there no Data values on most of these CSPS?

All policy pages also seem to be different and do not follow a writing guide. 

Can someone go through all policies, and assure these points are covered?

I need to write a test plan, and because tech writers didn't put this in there, it makes deployment a problem!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d29cfe6-cd94-95d7-b635-80bf356829fd
* Version Independent ID: 699e70c4-bf24-1200-b6cb-451aa547437b
* Content: [Policy CSP - Privacy](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-privacy)
* Content Source: [windows/client-management/mdm/policy-csp-privacy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-privacy.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by Tdiwestyguy** [comment]
Might someone kindly assist me with this request?  

The data is missing from many of the CSP listings makes usage and testing rather difficult.  

Thanks,
Alex

**Comment by Heidilohr** [comment]
@Tdiwestyguy Hi, Alex. I'm getting in touch with the dev teams to try to find the missing information for these articles.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @Heidilohr is there any update on the missing information that can be incorporated into this document? Thank you and looking forward to your feedback.

@Tdiwestyguy we really appreciate your patience on this matter. We hope to get this resolved by making sure the documentation contains all the information that you and other users will need. Thank you.

**Comment by jvsam** [comment]
Hi @Heidilohr and @Dansimp is there any update on the missing information? Referencing to the comment added on January 23, 2019. Thank you.

**Comment by Heidilohr** [comment]
Hi @jvsam. Unfortunately, the dev team never got back to me. I'm also no longer the writer for CSPs. @Dansimp should be able to redirect you to whoever is currently responsible for this article.

**Comment by Tdiwestyguy** [comment]
Couldn't he take over all relevant articles?

Seems odd you moved on, but the team didn't pickup your work/per these articles.

Thanks Heide.

Alex

________________________________

**Comment by Tdiwestyguy** [comment]
oops, Heidi! 🙂

________________________________

**Comment by jvsam** [comment]
Thank you for taking the time to update us @Heidilohr. Much appreciated. 

Hi @Dansimp. Hoping you could help us. Do you have have any information for us or advice on how we shall proceed? I could also assign this to a freelance tech writer if you can direct us to relevant resources. Looking forward to your feedback. Thank you very much.

**Comment by jvsam** [comment]
Hi @ManikaDhiman, there have been several updates to this documentation, however, some of the CSPs don't have any supported values. Is the update process still ongoing or is this document already *up-to-date*?

Hi @Tdiwestyguy have you had a chance to review the updates? Of course, the docs are considered *continuous work in progress*, so please continue to send your feedback.

**Comment by ManikaDhiman** [comment]
Hi @jvsam, Most of the recent updates were related to doc metadata. I will try to get in touch with the product team to add missing data types and values; however, this may take a while to get required info. Thanks!

**Comment by jvsam** [comment]
Looking forward to you updates @ManikaDhiman . Thank you.

**Comment by jvsam** [comment]
Hello @ManikaDhiman I just want to follow up if you have an update for us? I can see changes to the doc on this [commit ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/fa34c823613d94cec88cb78c45628c2887b15e74), I am not sure if that covers everything though. Again, we appreciate your help!

**Comment by jvsam** [comment]
Related to #1750

**Comment by jvsam** [comment]
Hi @ManikaDhiman, there had been several improvements to this documentation already, thank you so much. Are you still working on adding more soon? Thanks in advance for the updates.

**Comment by ManikaDhiman** [comment]
Hi @jvsam, thanks for the follow up. I will update this doc as and when more information comes in. Users can also refer to [Policy CSP DDF file](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-ddf-file) for any additional info. Thanks!

**Comment by nam31** [comment]
As per last conversations, it seems like we are good to close this issue.  @ManikaDhiman  Thank you!
