### ISSUE TITLE
Common PIN algorithm - constant delta query.

### ISSUE THREAD

**Issue by bmwilson1978** [MicrosoftDocs/windows-itpro-docs#1897]
Can someone explain why 0864 is classed as a common PIN, yet 8640 is not.   0864 = +8, -2, -2 and 8640 (-2, -2, -4), both don't have a constant delta or am I misunderstanding something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82ecd7ea-0ecb-cf7b-a1ab-9cda97e5cc0a
* Version Independent ID: 81acb0ad-2d46-bd0b-abb5-7c2e851d7a71
* Content: [Windows Hello for Business Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-faq)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-faq.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by illfated** [comment]
Speculation on my part: it could have something to do with hand/finger movement direction on a numeric keypad.

**Comment by bmwilson1978** [comment]
Yeah true, if so then it’d be ideal to have those  defined patterns/movements documented along with the algorithms.

**Comment by bchand** [comment]
is license required for using windows Hello, Windows Hello for business and if yes what sort of license cover the same

**Comment by mapalko** [comment]
Based on the documentation, 0864 would have diffs (8,8,8) and 8640 (8,8,6). The diff is not done using absolute differences. The example that shows this is: "1872 does not have a constant delta (7,9,5)" The diff between 8 and 7 is nine. You can think of it is a sequential count that maxes at 9 and then restarts at 0. So the difference between 8 and 1 would be 3 (9 -> 0 -> 1).

**Comment by illfated** [comment]
Thanks, nice to know more about what type of pattern is used to calculate the delta variations (0 ... 9, looping).

**Comment by spudw** [comment]
I agree with mapalko, that is my understanding as well.

**Comment by e0i** [comment]
Hello @bmwilson1978,

The issue is being closed since your question has been answered by the document author. 

Thanks.
