### ISSUE TITLE
Step5 in Use the Windows Device Portal to install apps on HoloLens needs update

### ISSUE THREAD

**Issue by chris-han** [MicrosoftDocs/windows-itpro-docs#1898]
In Install app, select an app package from a folder on your computer or network. If the app package requires additional software such as dependency frameworks, check the 'I want to specify framework packages'. (click Add dependency is for earlier windows device portal)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 108c471e-f724-8220-43a4-c3d3627f18b4
* Version Independent ID: 28d82e61-b7e9-f4ee-06fe-c4580d8706b8
* Content: [Install apps on HoloLens (HoloLens)](https://docs.microsoft.com/en-us/hololens/hololens-install-apps#feedback)
* Content Source: [devices/hololens/hololens-install-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/hololens/hololens-install-apps.md)
* Product: **hololens**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by J450NP13** [comment]
I’d like to know what folder or file am I supposed to upload?  All of them?  The vs solution?

**Comment by riebling** [comment]
Good question, I struggled to find an app package as well. It's not clearly documented where the resulting OUTPUT from build (or is it deploy?) should be found. I found one in a path C:\Users\er1k\Desktop\arena\App\AppPackages\ARENA\ARENA_1.0.0.0_x64_Debug_Test where the name of the Unity Project was "ARENA" (obviously). But I don't even know what action created this; was it from clicking "Build" in Unity? Or perhaps some other action in Visual Studio. And even then, I got errors about being the wrong architecture: x64 vs x86, and it didn't work

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@chris-han 

This issue has been addressed with the following commit and content has been updated according to your feedback.

[[f7c8c87]  Merged PR 12278: update HoloLens procedure (issue 1898)](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/f7c8c87b37364fe7f9b7906e602d1612d2bb2190)

We are thus closing this issue since it seems to be resolved. Feel free to re-open it if you feel it hasn't been resolved.

Thank you for taking the time to provide feedback.

**Comment by e0i** [comment]
@officedocsbot close
