### ISSUE TITLE
Release Offline documention 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1899]
Please offline documentation in .pdf format for the all the users in different languages 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aa5c0a6-acd2-4ec3-275d-3a684b3faaf4
* Version Independent ID: 6b475925-ca66-d47f-e180-92988683b37a
* Content: [Group Policy and Mobile Device Management settings for Microsoft Edge (Microsoft Edge for IT Pros)](https://docs.microsoft.com/en-us/microsoft-edge/deploy/available-policies)
* Content Source: [browsers/edge/available-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/available-policies.md)
* Product: **edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
That is great feedback.  I'll see what I can do to make this happen :)

**Comment by shortpatti** [comment]
@RAJU2529, I've provided feedback to the team via the Feedback Hub (Send feedback option under the More (...) menu).   I'm curious too about this because PDFs are quite portable and useful for adding notes.

**Comment by RAJU2529** [comment]
sorry actually my feedback hub not working, so I wrote suggestions and feedbacks here. please forgive me sir

**Comment by shortpatti** [comment]
No worries.  I was happy to pass this information on to the proper team to get this request on the list :)
