### ISSUE TITLE
not compatible

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1902]
Thanks for the given direct downloading link IEAK11, and  just now downloaded ieak 11 , then install3d on windows 10  1803.17134.345 64bit enterprise.I tried to create configuration for windows 10 os , target platform does not windows 10 OS .Its  drawback for windows  10 Users .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8e958d-60a7-ef70-4d61-d8962982007d
* Version Independent ID: f6024c93-22d8-8ab6-1c69-469f93f3d3cc
* Content: [Internet Explorer Administration Kit (IEAK) information and downloads](https://docs.microsoft.com/en-in/internet-explorer/ie11-ieak/ieak-information-and-downloads)
* Content Source: [browsers/internet-explorer/ie11-ieak/ieak-information-and-downloads.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/internet-explorer/ie11-ieak/ieak-information-and-downloads.md)
* Product: **ie11**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@RAJU2529, thank you for your feedback.  I'll look into the compatibility issues.

**Comment by shortpatti** [comment]
@RAJU2529, I'll reach out to the dev team for IEAK11.

**Comment by mypil** [comment]
@shortpatti - Do you have any updates on this. Thanks.

**Comment by mypil** [comment]
@RAJU2529 - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
