### ISSUE TITLE
Add  target platform

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1903]
Add  new  target platform to windows 10 x86 and x64  architectures , which is  really for  windows 10 enterprise customers. Thanking you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8e958d-60a7-ef70-4d61-d8962982007d
* Version Independent ID: f6024c93-22d8-8ab6-1c69-469f93f3d3cc
* Content: [Internet Explorer Administration Kit (IEAK) information and downloads](https://docs.microsoft.com/en-in/internet-explorer/ie11-ieak/ieak-information-and-downloads)
* Content Source: [browsers/internet-explorer/ie11-ieak/ieak-information-and-downloads.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/internet-explorer/ie11-ieak/ieak-information-and-downloads.md)
* Product: **ie11**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
Target OS has been added and it will show later today.

**Comment by shortpatti** [comment]
duplicate of #[1902](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1902)
