### ISSUE TITLE
Unable to create windows 10 configuration for IEAK11

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1904]
but i could  not able  create configuration for windows 10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6406ca95-5d88-9036-7d09-7514c880fe9d
* Version Independent ID: cd7588d6-125f-4292-c171-705556267aeb
* Content: [Hardware and software requirements for Internet Explorer 11 and the IEAK 11 (Internet Explorer Administration Kit 11 for IT Pros)](https://docs.microsoft.com/en-in/internet-explorer/ie11-ieak/hardware-and-software-reqs-ieak11)
* Content Source: [browsers/internet-explorer/ie11-ieak/hardware-and-software-reqs-ieak11.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/internet-explorer/ie11-ieak/hardware-and-software-reqs-ieak11.md)
* Product: **ie11**
* GitHub Login: @shortpatti
* Microsoft Alias: **shortpatti**

**Comment by illfated** [comment]
Maybe it would be useful to alter the issue title to say "**Unable to create  windows 10 configuration for IEAK11**".

**Comment by illfated** [comment]
Very well. I don't have edit rights to do so, but I presume one of the team members will.

**Comment by shortpatti** [comment]
Related to issue #1902. See this issue for more information.
