### ISSUE TITLE
Missing how to add ProPlus

### ISSUE THREAD

**Issue by cathyethoca** [MicrosoftDocs/windows-itpro-docs#1907]
The older version had steps on how to add ProPlus manually to the deployment

Just below this link:
https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image#add-the-microsoft-office-professional-plus-2013-x86-installation-files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0eb8c97-caa0-bb05-4b91-14ad2adc4aac
* Version Independent ID: 0cc541a3-8198-c029-d795-308e673ee2f4
* Content: [Create a Windows 10 reference image (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image#add-the-microsoft-office-professional-plus-2013-x86-installation-files)
* Content Source: [windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by msjbja** [comment]
Hello @cathyethoca. Thank you for your feedback. Could you clarify what you mean? There are currently instructions to add Proplus to the image in the document.

**Comment by illfated** [comment]
Maybe one of the 2 commits in 2019 made changes in order for the information to become visible, so the question is less relevant now?
(https://github.com/MicrosoftDocs/windows-itpro-docs/commits/master/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md)

**Comment by e0i** [comment]
@cathyethoca 

We are closing the issue as it already seems to be resolved. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
