### ISSUE TITLE
I have idea 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1910]
create windows 10 base image and install to test computer and then install all-time requested and essential applications with all the customized settings, once finished, using syspres cmd,  generalize the image, afterwards shutdown the pc, boot with windows 10 Pe captured image with fast compression.
 afterwards using MDT proceed as you like 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0eb8c97-caa0-bb05-4b91-14ad2adc4aac
* Version Independent ID: 0cc541a3-8198-c029-d795-308e673ee2f4
* Content: [Create a Windows 10 reference image (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image#add-the-microsoft-office-professional-plus-2013-x86-installation-files)
* Content Source: [windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @RAJU2529 can you please clarify what assistance your require from here related to the documentation? If you believe the documentation needs improvement, please provide recommendations on what needs to be changed or updated. We want users to have the best Windows 10 experience by ensuring the contents of the Microsoft Docs are accurate and up-to-date. Thank you.

**Comment by illfated** [comment]
I don't think this is about asking for assistance. I believe it is a suggestion for a deployment variant compared to the current content. Then again, it is not detailed enough for us to say for certain if the method is usable or an improvement over the existing methods in the documentation, or not specific enough regarding which parts of the suggestion is the improvement.

One concern regarding the lack of detail in the suggestion: it reads as if the suggested method is to install the base image directly onto the test computer without shielding it from the hardware layer (no mention of whether or not a VM is used on the targeted test computer), theoretically exposing the hardware drivers and related software (which the methods in the referenced article intends to avoid) to the SysPrep image resulting from the suggested method.

From what I have seen of @RAJU2529 's postings this year, I think he has increased his knowledge regarding Microsoft software management, so he may want to review this suggestion or add more details to make it a practical contribution.

**Comment by jvsam** [comment]
Thanks @illfated. If it is, then I agree with you, we will need more information from @RAJU2529.

@RAJU2529 If you can add more context to your, I'd say statement, it will greatly help. If you have found a better or another deployment option that you believe should be added to the docs, please let us know and provide as much information as possible. Thank you.

**Comment by RAJU2529** [comment]
please give me one day time. so that again I read the article completely and then I give my additions

**Comment by RAJU2529** [comment]
This article used server operating System. But some IT pros and normal users don't have server os to create referenced image.

Following suggestions.
01.I request to  add the link deployment options to for normal users.
02.Add the latest screenshots.
03.Remove Outdated screenshots.
04.use only latest Windows 10 v1809 or 1903 for deployment.
05. add the visual basics c++ direct downloading links.
06. add windows 10 v1903 download links for iso.

I read the article completely, some  features are I didNt seen it on my practical experience. Remaining all details are More explanations with details 

Thanking you @JVSAM for your patience and asking me to provide feedback. I am very happy to read the positive feedback about me.

**Comment by illfated** [comment]
OK, I see. Thank you for specifying your suggestion with more details.

You are requesting a server-less deployment strategy page, based only on using Windows 10 Pro and no servers, hence no virtualization.

I wonder if that sorts under a different category, or if it still belongs to the same page or subcategory.

**Comment by RAJU2529** [comment]
Thanks sir.its belongs to same category but different method.

**Comment by jvsam** [comment]
Hi again @RAJU2529, of course, your contributions are appreciated! I've seen quite a few already. 

Now with regard to your suggestion, I will forward it to the Windows writing team so they can review and propose the best way on how this can be incorporated to the documentation, whether it'll be on the same document or if it's more appropriate to add it on another page or category as mentioned by @illfated.

Thank you for engaging with the community and keep up the good work!

**Comment by jvsam** [comment]
Hi @RAJU2529 since the request falls under new content or *may* require extensive revision of the existing documentation, we are forwarding your suggestion to the document owner instead for r**eview and consideration**. 

**Summary:**
**New content suggestion (#1910) :** Creating a reference image using Windows 10 Pro with no server. 
**Additional requests from user:** (*copied verbatim*)
01.I request to add the link deployment options to for normal users.
02.Add the latest screenshots.
03.Remove Outdated screenshots.
04.use only latest Windows 10 v1809 or 1903 for deployment.
05. add the visual basics c++ direct downloading links.
06. add windows 10 v1903 download links for iso."

We value your feedback so please continue to send them to us. We will now close this issue but please feel free to re-open if you have additional suggestions or ideas to help improve this documentation. Thank you again for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
