### ISSUE TITLE
Add video demonstration 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1911]
Add the demonstration videos , for the users to get firsthand experience 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 773913b9-e98d-11cd-fd78-4a836fcb8bdf
* Version Independent ID: c221264e-926c-9414-1737-8a85085804ea
* Content: [Use Setup information (.inf) files to uninstall custom components (Internet Explorer Administration Kit 11 for IT Pros)](https://docs.microsoft.com/en-in/internet-explorer/ie11-ieak/create-uninstall-inf-files-for-custom-components)
* Content Source: [browsers/internet-explorer/ie11-ieak/create-uninstall-inf-files-for-custom-components.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/internet-explorer/ie11-ieak/create-uninstall-inf-files-for-custom-components.md)
* Product: **ie11**
* GitHub Login: @shortpatti
* Microsoft Alias: **shortpatti**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @RAJU2529 , thank you for your suggestion. I will get this issue over to the Windows writing team for review and hopefully this is something that can be added to the documentation to make it easier for the users.

Again, thank you for your contribution to make the docs better! We always welcome suggestions, comments or feedback to improve the docs.

**Comment by RAJU2529** [comment]
ThanKing you sir. I hope Windows tram will accept my ideas.

**Comment by jvsam** [comment]
You're welcome @RAJU2529 !

**Comment by TokyoScarab** [comment]
@RAJU2529 Hello and thank you for letting know your opinion on this page.  At a glance, it doesn't seem like creating a video showing the steps of the process on this page would seem necessary for how short the instructions are.  Are there things in the steps given that you think aren't clear enough?

**Comment by RAJU2529** [comment]
@TokyoScarab . its clear. But videos can be shared all over the world and it can listen without internet

**Comment by TokyoScarab** [comment]
@RAJU2529 I will forward this suggestion to Microsoft and if they find it necessary, we will update it.

**Comment by jvsam** [comment]
Hi @RAJU2529 with regard to the demo video, kindly use the feedback hub to suggest it, as what we have done. Please submit it on [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub), the product team would love to hear what you think. We will now close this issue, thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
