### ISSUE TITLE
It'd be good to see an update to this

### ISSUE THREAD

**Issue by shuurajou** [MicrosoftDocs/windows-itpro-docs#1912]
It's been quite a while since this has been updated, and with things like windows defender application guard around now, it'd be nice if this was refreshed as a one-stop page for folks to find out how to take full advantage of Windows 10's security stack.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 981c9ad4-d618-de21-4a79-0262b5d377d8
* Version Independent ID: 5657feb8-539d-90eb-0b81-3f461158e0dd
* Content: [Mitigate threats by using Windows 10 security features (Windows 10)](https://docs.microsoft.com/en-gb/windows/security/threat-protection/overview-of-threat-mitigations-in-windows-10)
* Content Source: [windows/security/threat-protection/overview-of-threat-mitigations-in-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/overview-of-threat-mitigations-in-windows-10.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@shuurajou thanks for the suggestion. New features like Windows Defender Application Guard will be added here: https://docs.microsoft.com/en-gb/windows/security/threat-protection/index and particularly under WD ATP node: https://docs.microsoft.com/en-gb/windows/security/threat-protection/windows-defender-atp/windows-defender-advanced-threat-protection

I could add a link to help redirect readers better. Would that help? This specific topic about mitigations was mainly intended to help EMET users transition to using similar features that are already built in to Windows 10.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @shuurajou I believe this issue can be considered as *resolved*. The links mentioned by @Justinha were added to the Table of Contents on the left for quick access. 

We will now close this issue. If you believe the documentation needs improvement, please re-open and provide recommendations on what needs to be changed or updated. We want users to have the best Windows 10 experience by ensuring the contents of the Microsoft Docs are accurate and up-to-date.

Thanks you for your feedback and for engaging with the community!

**Comment by jvsam** [comment]
@officedocsbot close
