### ISSUE TITLE
-SOLVED- It doesn't work for me

### ISSUE THREAD

**Issue by 2IRG-FB** [MicrosoftDocs/windows-itpro-docs#1915]
I followed all of the hints:

1 - The Policy is not configured
2 - I don't see the Keys
3 - I see "Incorrect parameter"

So it seems that I don't have this configuration, but I have this error from VMware Player after the installation of Docker...!
Can someone help me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#turn-off-with-hardware-readiness-tool)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@2IRG-FB What error are you referring to? You can use these steps to check if Credential Guard is running:
https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#review-windows-defender-credential-guard-performance

**Comment by 2IRG-FB** [comment]
@Justinha The error about incompatibility between VMware Player and Credential Guard, i just commented the page you linked through "Give a feedback".
However, i solved the problem with this cmd: "**_bcdedit /set hypervisorlaunchtype off_**". After that, VMware works, but Docker doesn't work anymore... I think they are incompatible...!

**Comment by ludwigschreier** [comment]
"bcdedit /set hypervisorlaunchtype off" didn't solve my problem. I noticed on my particular DELL notebook that there was a missing VT feature to be enabled in BIOS, which did the trick. However, Windows was already telling me "Virtualization is active" etc. Conclusion: Check BIOS switches first before torturing the software side.

**Comment by illfated** [comment]
@ludwigschreier : Thank you for the useful and vivid insight. 🖥

**Comment by DoublleW** [comment]
Solved!
As @ludwigschreier wrote, check the BIOS and turn on the VT.
In my case, I have disabled the option (yes, turn it off).
I started Windows and tried to start the VM or view the status in msinfo32.exe, closed everything and rebooted.
In BIOS enable VT and launched Windows.
VMWare works and does not issue a warning when creating x64 OS.

**Comment by illfated** [comment]
Thank you for the feedback. Based on your experience,
 would you say that the documentation needs improvements
 for other users to avoid the same issue?
 If yes, what do you recommend changing?

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @2IRG-FB reviewing the comments, I believe your issue has been resolved. 

We will now close this issue. If you believe the documentation needs improvement, please re-open and provide recommendations on what needs to change or to be updated based from your experience following the instructions in the doc. 

Thank you for engaging with the community!

**Comment by jvsam** [comment]
@officedocsbot close
