### ISSUE TITLE
shouldn't the steps be flipped?

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/windows-itpro-docs#1918]
in Config man section, shouldn't steps 3f and3g be swapped?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e53eec1-548f-701f-3bcb-3763d68e09a4
* Version Independent ID: 6d5926a0-8a73-f4b2-a000-a9245500cdeb
* Content: [Evaluating MBAM 2.5 in a Test Environment](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/evaluating-mbam-25-in-a-test-environment)
* Content Source: [mdop/mbam-v25/evaluating-mbam-25-in-a-test-environment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/evaluating-mbam-25-in-a-test-environment.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by shortpatti** [comment]
@sasanmcp, thank you for the feedback, you make a valid point and I've made the change.
