### ISSUE TITLE
Need more information

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#1919]
Compared to other CSPs, this CSP documentation does not use the same templated information broken down per CSP, and I am requesting enhancement/review of this policy.  

limited informatio makes creating a Test case rather tough.   Can someone please update this article with deployment information Per CSP?

Data types, and configurable values need to be available per CSP so Admins may deploy.

Use of whole words, INTEGER would be more acceptable than "int." 

Please provide examples on String values, and how you would input that into MDM or SCCM mdm. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fa54fab-72fa-5738-a0f0-7e02b72d93da
* Version Independent ID: cc6cf148-1b08-1bbe-732f-0495daa1a659
* Content: [NetworkProxy CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/networkproxy-csp)
* Content Source: [windows/client-management/mdm/networkproxy-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/networkproxy-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by Tdiwestyguy** [comment]
Example: ./Vendor/MSFT/NetworkProxy/ProxyServer
Node for configuring a static proxy for Ethernet and Wi-Fi connections. The same proxy server is used for all protocols - including HTTP, HTTPS, FTP, and SOCKS. These settings do not apply to VPN connections.
Supported operation is Get.

This does not appear to contain enough information to deploy using MDM.

**Comment by Tdiwestyguy** [comment]
Can someone confirm if this is right?

The article says, "ProxySettingsPerUser"
Added in Windows 10, version 1803. When set to 0, it enables proxy configuration as global, machine wide.
Supported operations are Add, Get, Replace, and Delete.
 Note
Per user proxy configuration setting is not supported.



Does the Note mean you cannot use this CSP, I was looking at what deployment options are available?

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by PrinceMarkieD** [comment]
This document needs to be updated. Use of this Proxy CSP may cause insecure configurations of endpoints. Does the NOTE imply that the per-user proxy settings should not be used because they do not work? or does it imply they no longer work on older versions of Windows 10? Maybe it is stating that they are unstable, and therefore not supported, but otherwise work? Is there a way to make a user based exception to the proxy settings?
thank you.

**Comment by e0i** [comment]
Hello, @Tdiwestyguy 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by ausamriyaz** [comment]
hi, 
I have been working on this, and I am having trouble adding the proxy configuration to the device. I am testing on a Windows 10 Enterprise 1803. Any update on this yet?

I formatted the SyncML as:

```syncml
<Replace>
<CmdID>744</CmdID>
<Item>
<Target>
<LocURI>./Vendor/MSFT/NetworkProxy/ProxyServer/ProxyAddress</LocURI>
</Target>
<Meta>
<Format xmlns="syncml:metinf">chr</Format>
</Meta>
<Data>192.168.8.160:8080</Data>
</Replace>
```

**Comment by illfated** [comment]
@ausamriyaz : I ran your SyncML through http://xmlbeautifier.com/ and got this result:
```xml
<Replace>
    <CmdID>744</CmdID>
    <Item>
        <Target>
            <LocURI>./Vendor/MSFT/NetworkProxy/ProxyServer/ProxyAddress</LocURI>
        </Target>
    </Item>
    <Meta>
        <Format xmlns="syncml:metinf">chr</Format>
    </Meta>
    <Data>192.168.8.160:8080</Data>
</Replace>
```
(I had to add the missing `</Item>` tag to get it parsed.)

**Comment by e0i** [comment]
@Tdiwestyguy 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
