### ISSUE TITLE
missing information on CSP

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#1921]
Start/HidePeopleBar is missing deployment values. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800fa3a7-e6c8-5525-401b-e69a6ccfa66d
* Version Independent ID: c2d24d10-a365-4720-ec22-57b2e12340b4
* Content: [Policy CSP - Start](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-start#start-hidepeoplebar)
* Content Source: [windows/client-management/mdm/policy-csp-start.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-start.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by Tdiwestyguy** [comment]
Start/DisableContextMenus also missing deployment data to be used.. ??

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by Malind19** [comment]
Created PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3166

**Comment by mypil** [comment]
@officedocsbot close
