### ISSUE TITLE
DOES NOTHING

### ISSUE THREAD

**Issue by cacodemon9000** [MicrosoftDocs/windows-itpro-docs#1924]
PS C:\Users\damir&gt; mountvol X: /s
PS C:\Users\damir&gt;
PS C:\Users\damir&gt; copy %WINDIR%\System32\SecConfig.efi X:\EFI\Microsoft\Boot\SecConfig.efi /Y
Copy-Item : A positional parameter cannot be found that accepts argument '/Y'.
At line:1 char:1
+ copy %WINDIR%\System32\SecConfig.efi X:\EFI\Microsoft\Boot\SecConfig. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Copy-Item], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
PS C:\Users\damir&gt;
PS C:\Users\damir&gt; bcdedit /create {0cb3b571-2f2e-4343-a879-d86a476d7215} /d "DebugTool" /application osloader
Invalid command line switch: /encodedCommand
Run "bcdedit /?" for command line assistance.
The parameter is incorrect.
PS C:\Users\damir&gt;
PS C:\Users\damir&gt; bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} path "\EFI\Microsoft\Boot\SecConfig.efi"
The set command specified is not valid.
Run "bcdedit /?" for command line assistance.
The parameter is incorrect.
PS C:\Users\damir&gt;
PS C:\Users\damir&gt; bcdedit /set {bootmgr} bootsequence {0cb3b571-2f2e-4343-a879-d86a476d7215}
bcdedit.exe : The command parameter was already specified.
At line:1 char:1
+ bcdedit /set {bootmgr} bootsequence {0cb3b571-2f2e-4343-a879-d86a476d ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], ParameterBindingException
    + FullyQualifiedErrorId : ParameterSpecifiedAlready
PS C:\Users\damir&gt;
PS C:\Users\damir&gt; bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} loadoptions DISABLE-LSA-ISO
The set command specified is not valid.
Run "bcdedit /?" for command line assistance.
The parameter is incorrect.
PS C:\Users\damir&gt;
PS C:\Users\damir&gt; bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} device partition=X:
The set command specified is not valid.
Run "bcdedit /?" for command line assistance.
The parameter is incorrect.
PS C:\Users\damir&gt;
PS C:\Users\damir&gt; mountvol X: /d

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#disable-windows-defender-credential-guard)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Kaydelon** [comment]
Absolute rubbish.  The poster should be ashamed of himself.
This "solution" has been posted around multiple sites for years, and hasn't worked in about as long.

**Comment by botmoto** [comment]
Those commands are meant to be run in "An Elevated Command Prompt" (cmd) not Powershell. If anyone else has these issues please use cmd.

**Comment by illfated** [comment]
@cacodemon9000 : Please take note of what botmoto has commented above.

@e0i : Looks like this issue can be closed (unless you know of a reason to keep it open).

**Comment by Kaydelon** [comment]
Please update the commands above to reflect the correct syntax and switches.  (i.e. mountvol’s depreciated /s)

**Comment by illfated** [comment]
I presume you mean _deprecated_ -- but which version(s) are affected? I tested it on an updated Windows Server 2016 a couple of weeks ago and it seemed to work OK then.

**Comment by illfated** [comment]
Please have a look at issue ticket #3234 for a closely related discussion on this topic.

**Comment by RAJU2529** [comment]
@cacodemon9000. I have an idea.   Copy the  secconfig.efi   to  C:\EFI\Microsoft\Boot\

and then boot the computer by using windows dvd  into windows RE mode.
Go to the command prompt ,  use diskpart, format the efi partition , assign drive letter .exit
use  bcdboot command  to copy required files to efi partition 

exit and restart the windows

**Comment by e0i** [comment]
> @cacodemon9000 : Please take note of what botmoto has commented above.
> 
> @e0i : Looks like this issue can be closed (unless you know of a reason to keep it open).

@officedocsbot close
