### ISSUE TITLE
Out of date references to Windows build

### ISSUE THREAD

**Issue by nimojg-microsoft** [MicrosoftDocs/windows-itpro-docs#1926]
We are on Windows 10, version 1809! Why reference Windows builds if we don't keep this up-to-date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c34addaf-0c0f-3138-610b-a21f25f7df2a
* Version Independent ID: f5685a73-2ddd-bf71-ddd2-97ff11ee6cf6
* Content: [Deploy and manage a full cloud IT solution with Microsoft Education](https://docs.microsoft.com/en-us/education/get-started/get-started-with-microsoft-education)
* Content Source: [education/get-started/get-started-with-microsoft-education.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/get-started/get-started-with-microsoft-education.md)
* Product: **w10**
* GitHub Login: @CelesteDG
* Microsoft Alias: **celested**

**Comment by e0i** [comment]
@nimojg-microsoft 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
