### ISSUE TITLE
InTune Custom OMA-URI Settings

### ISSUE THREAD

**Issue by Niglb** [MicrosoftDocs/windows-itpro-docs#1929]
Is there anyplace to get an example of deploying this via InTune Custom OMA-URI Settings in a recommended configuration for a public kiosk? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d409ed15-110a-12b2-45bc-b622d9aac256
* Version Independent ID: 99cf6b35-8654-c385-55a5-3b22450b0500
* Content: [UnifiedWriteFilter CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/unifiedwritefilter-csp)
* Content Source: [windows/client-management/mdm/unifiedwritefilter-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/unifiedwritefilter-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @Niglb were you able to successfully configure UnifiedWriteFilter CSP? I wasn't able to see any examples specifically for UnifiedWriteFilter CSP but these may be able to help:

[Use custom settings for Windows 10 devices in Intune](https://docs.microsoft.com/intune/custom-settings-windows-10)
[Introduction to configuration service providers (CSPs) for IT pros](https://docs.microsoft.com/windows/configuration/provisioning-packages/how-it-pros-can-use-configuration-service-providers)

If you believe the documentation needs improvement, what do you recommend that we change or update? We want users to have the best Windows experience so your feedback is definitely welcome!

**Comment by jvsam** [comment]
Hi again @Niglb , we haven't received any response or update from you so we will now close this issue. Please feel free to re-open it if you have comments or suggestions to help improve the contents of this document. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by Niglb** [comment]
No have not configured it successfully
