### ISSUE TITLE
Missing deployment variables/Data type for TenantId

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#1930]
TenantId
A globally unique identifier (GUID), without curly braces ( { , } ), that is used as part of Windows Hello for Business provisioning and management.

There is no Deployment data on this?  I used String and "guid" however that wont work.   

Can someone provide Syntax for this Passport for work CSP policy, TenantID?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4180b6e-2786-ffb0-8f92-e4456dc343c9
* Version Independent ID: 7722d866-c095-b806-1da8-17e00cfe9a0a
* Content: [PassportForWork CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/passportforwork-csp)
* Content Source: [windows/client-management/mdm/passportforwork-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/passportforwork-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by Tdiwestyguy** [comment]
Is there anyone who can return a response?

**Comment by illfated** [comment]
I presume the one who would be best qualified to give an answer would be the author (presumably @MariciaAlforque ?).
Failing that, perhaps the assignee @Heidilohr could offer some advice.

**Comment by Heidilohr** [comment]
@Tdiwestyguy I'm currently getting in touch with the project team responsible for this CSP. I will get back to you once we've figured out how to fix this issue.

**Comment by e0i** [comment]
@Heidilohr 

Any updates with this issue? We would like to follow up and assist with content updates if necessary.

Thanks.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@Heidilohr Any updates?

**Comment by illfated** [comment]
Not sure, but would it help to check with @brianlic-msft or @nickbrower if there are anyone else available for follow-up to this issue ticket?

**Comment by e0i** [comment]
@manikadhiman Would you be able to provide assistance and direction regarding this issue as the new owner of content? Thanks.

**Comment by ManikaDhiman** [comment]
Hi @e0i, I have reached out to the product team for this issue and issue#2522. I will update the status as soon as I hear from them. Thanks!

**Comment by ManikaDhiman** [comment]
Hi @e0i, Here's the response from the product team:
The CSP documentation has information on how to retrieve the GUID, and the examples at the bottom of the page show the GUID being used. The following section shows the GUID for this case.

<Add>
              <CmdID>2</CmdID>
              <Item>
                <Target>
                  <LocURI>
                    ./Vendor/MSFT/PassportForWork/5NEMDU42-45CC-8CBL-8BPF-D7092646325F
                  </LocURI>
                </Target>
              </Item>
           </Add>
            <Add>

 Hope this helps!

**Comment by e0i** [comment]
@ManikaDhiman Thank you for taking the time to follow-up.

@Tdiwestyguy 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
