### ISSUE TITLE
1810

### ISSUE THREAD

**Issue by Niglb** [MicrosoftDocs/windows-itpro-docs#1932]
Is this line a typo? 'In Windows 10, version 1810, Assigned Access runtime status supports monitoring....' or is 1809 being renamed when it is officially released? :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8301897-dfa3-ef3b-744f-9e8334c17dc4
* Version Independent ID: d5751dd3-b0ae-49ef-75cd-d4113c4eed3d
* Content: [AssignedAccess CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/assignedaccess-csp)
* Content Source: [windows/client-management/mdm/assignedaccess-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/assignedaccess-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by shortpatti** [comment]
@Niglb, thank you for catching that mistake, and sorry for the confusion.  I've fixed it and it should be 1809.
