### ISSUE TITLE
IE11 not support modern web technologies.

### ISSUE THREAD

**Issue by omonoe** [MicrosoftDocs/windows-itpro-docs#1933]
The following sentence is incorrect.
&gt;which help to ensure today's modern websites and apps work just as well as your old, legacy websites and apps.
IE 11 does not have the standard Web technology that became common after 2014.
For example, ES 2015 (ES 6) currently in popular use now does not work with IE11.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f19c0a2-75ff-0504-78af-205a5bd88da3
* Version Independent ID: b661ca31-6826-db16-5276-bdff91e3db75
* Content: [Use Enterprise Mode to improve compatibility (Microsoft Edge for IT Pros)](https://docs.microsoft.com/en-us/microsoft-edge/deploy/emie-to-improve-compatibility)
* Content Source: [browsers/edge/emie-to-improve-compatibility.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/emie-to-improve-compatibility.md)
* Product: **browser-edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @omonoe, thank you for your feedback. I will get this issue over to the Windows writing team for review. We want users to have the best Windows experience by ensuring the contents of the Microsoft Docs are accurate and up-to-date. 

I also requested the team to update this issue if additional information is needed or when the work is complete.

Thank you for engaging with the community!

**Comment by VLG17** [comment]
@omonoe the full sentence states that _"IE11 supports modern web technologies like HTML5, CSS3, and WebGL, which help to ensure today's modern websites and apps work just as well as your old, legacy websites and apps."_

It does not state that it supports **all** modern web technologies, but the ones that are described above are indeed supported. 

What exactly are you reffering to with "standard Web technology", which is not supported in IE11?

**Comment by jvsam** [comment]
@VLG17 I believe the request here is validate and update this part, which is not 100% accurate:

> Modern web standards. IE11 supports modern web technologies like HTML5, CSS3, and WebGL, which help to ensure today's modern websites and apps work just as well as your old, legacy websites and apps.

I think what is *contestable* is where it says *Modern web standards* and *like* so personally, it might be worth suggesting or adding a note in there on what it cannot support, for instance, IE11 doesn’t support a lot of modern [CSS properties, modern JavaScript](https://caniuse.com/#compare=ie+11), etc.. @nenonix any suggestion with regard to messaging? Thank you.

**Comment by nenonix** [comment]
@jvsam I think the update addresses the problem.

**Comment by jvsam** [comment]
Hello again @omonoe, thank you for your patience. I just want to inform you that there's already a suggested update to this documentation (see PR #4621) based on your feedback. PRs are normally reviewed/merged in the order of submission but once approved, they will be displayed here at docs.microsoft.com site in the next scheduled publishing run. I will let you know once the PR has been approved and merged.

**Comment by jvsam** [comment]
Hi @omonoe, the pull request has been approved and merged. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you again for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
