### ISSUE TITLE
EMIE's download link is dead.

### ISSUE THREAD

**Issue by omonoe** [MicrosoftDocs/windows-itpro-docs#1934]
The following links in the document are dead.

Enterprise Mode Site List Manager for Windows 10 download
https://www.microsoft.com/ja-JP/download/details.aspx?id=49974

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f19c0a2-75ff-0504-78af-205a5bd88da3
* Version Independent ID: b661ca31-6826-db16-5276-bdff91e3db75
* Content: [Use Enterprise Mode to improve compatibility (Microsoft Edge for IT Pros)](https://docs.microsoft.com/en-us/microsoft-edge/deploy/emie-to-improve-compatibility)
* Content Source: [browsers/edge/emie-to-improve-compatibility.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/emie-to-improve-compatibility.md)
* Product: **browser-edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@omonoe, thank you for the feedback.  I looked at the broken link and found that the topic no longer exists.  You can, however, click on one of the other links for a specific schema, either v.1 or v.2.
