### ISSUE TITLE
typo in picture

### ISSUE THREAD

**Issue by jkulbe** [MicrosoftDocs/windows-itpro-docs#1935]
The topmost box on the left in the picture for "Azure AD joined in Managed environments" reads "Cloud Experice Host" instead of "Cloud Experience Host". 

[https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-device-registration#azure-ad-joined-in-federated-environments](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96185909-5825-db9a-cc04-4045f6dc577e
* Version Independent ID: 9340a575-af61-9c73-7701-702fff99f524
* Content: [How Windows Hello for Business works - Device Registration](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-device-registration#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-how-it-works-device-registration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-how-it-works-device-registration.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot close
