### ISSUE TITLE
"retrive" instead of "retrieve" in two illustrations

### ISSUE THREAD

**Issue by jkulbe** [MicrosoftDocs/windows-itpro-docs#1936]
The illustrations for the following two topics says "retrive MDM terms of use" instead of "retrieve MDM terms of use"

[https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-device-registration#azure-ad-joined-in-federated-environments](url)

[https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-device-registration#azure-ad-joined-in-federated-environments](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96185909-5825-db9a-cc04-4045f6dc577e
* Version Independent ID: 9340a575-af61-9c73-7701-702fff99f524
* Content: [How Windows Hello for Business works - Device Registration](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-device-registration#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-how-it-works-device-registration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-how-it-works-device-registration.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jkulbe  -  Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
