### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by rbreneman** [MicrosoftDocs/windows-itpro-docs#1938]
Typo in the note, starting: Before proceeding, you should familiarize yourself with device regisration concepts such as:

Should be:
Before proceeding, you should familiarize yourself with device registration concepts such as:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d87ba3ab-d8a7-d038-2f7d-886bed956394
* Version Independent ID: cb2ea1fd-6a0d-8656-0bb4-0528c65ea03f
* Content: [Configure Device Registration for Hybrid key trust Windows Hello for Business](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-devreg)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-devreg.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-devreg.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@rbreneman - Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by mypil** [comment]
@officedocsbot close
