### ISSUE TITLE
What data is sent to Microsoft

### ISSUE THREAD

**Issue by nathanTYO** [MicrosoftDocs/windows-itpro-docs#1943]
Need detail on what specifically is sent to Microsoft when cloud-delivered protection is enabled.  What meta-data and what files?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f8ccc01-1b04-e443-ef75-6ffe6c866dd5
* Version Independent ID: fa2eaa0f-db04-785a-3894-8244947b9cd5
* Content: [Enable cloud-delivered protection in Windows Defender Antivirus](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by andreabichsel** [comment]
Thank you for your questions! For security reasons, we can't publicly publish this information.

**Comment by markste-in** [comment]
Could you give insights about the "security reasons" and the threat model behind it?

I am also curious how the concealment of what is exfiltrated from a PC is seen legally in the EU (GDPR).
