### ISSUE TITLE
Duplicate Attribute in XSD

### ISSUE THREAD

**Issue by tFable** [MicrosoftDocs/windows-itpro-docs#1950]
Hello,

Visual studio complains that the "maxOccurs" attribute is duplicate in this section:
 &lt;xs:element name="NativeProfile" minOccurs="0" maxOccurs="1"&gt;
          &lt;xs:complexType&gt;
            &lt;xs:sequence&gt;
&lt;xs:element maxOccurs="unbounded" name="CryptographySuite" minOccurs="0" maxOccurs="1"&gt;

Are you able to clarify if this is an issue with the doc?

Thanks,
t

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3032f094-c9b7-6f8c-5b66-2ba152d7c326
* Version Independent ID: 83047fc5-7020-be72-85d6-85fa0bfbf5b7
* Content: [ProfileXML XSD](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-profile-xsd)
* Content Source: [windows/client-management/mdm/vpnv2-profile-xsd.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/vpnv2-profile-xsd.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
@tFable : Thank you for providing feedback regarding this issue. I can only express my regret that it has taken so long to get back to you.

Yes, I see. That is clearly a duplicate and the doc page needs correction.
`maxOccurs` can only have 1 of the values `"0", "1" or "unbounded"` , but the line
```xml
              <xs:element maxOccurs="unbounded" name="CryptographySuite"minOccurs="0" maxOccurs="1">
```
seems to contain a copy-paste error or something similar, making `maxOccurs=`  appear twice.
There also appears to be missing at least 1 blank space before `minOccurs=` .

Let me post a correction PR to that page (via the Github source page).
(I will be needing verification of which of the 2 is the correct value, "1" or "unbounded".)
