### ISSUE TITLE
Windows Hello in combination with Assigned Access

### ISSUE THREAD

**Issue by devgaia** [MicrosoftDocs/windows-itpro-docs#1954]
Please explain how Assigned Access / Auto Login and Windows Hello interact. We seem to have a problem where the user is auto logged in but the "Enter PIN dialogue" is shown behind the app set up for assigned access.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8301897-dfa3-ef3b-744f-9e8334c17dc4
* Version Independent ID: d5751dd3-b0ae-49ef-75cd-d4113c4eed3d
* Content: [AssignedAccess CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/assignedaccess-csp)
* Content Source: [windows/client-management/mdm/assignedaccess-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/assignedaccess-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by lindspea** [comment]
@devgaia Thank you for reaching out.  I'll investigate further and have an answer for you soonest.

**Comment by devgaia** [comment]
Hello @lindspea, quite some time has passed since I first reported this and we've left Windows Hello as the base for this functionality. Nevertheless I want to clarify what the issue is as the original description is a bit misleading.

Our application runs in assigned access mode. When the app calls KeyCredentialManager.IsSupportedAsync and it returns false on the first run we try invoking the settings screen to have the user select a convenience PIN to use with Windows Hello. It was this settings screen that is hidden by the application running in assigned access mode. This means we can only use Windows Hello if we first leave Assigned Access, let the user select his/her convenience pin and then go into Assigned Access again.  This will be too cumbersome. For now we've left Windows Hello. For the future we might use Windows Hello for Business with a centralized management.
Thanks.

**Comment by e0i** [comment]
Hello, @devgaia

Thank you for taking the time to follow-up with clarification on this quite old issue. With the help of your feedback, we will follow-up with relevant content updates and keep you posted.

**Comment by e0i** [comment]
@devgaia 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thank you for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
