### ISSUE TITLE
InstantGo Devices

### ISSUE THREAD

**Issue by gutjahr** [MicrosoftDocs/windows-itpro-docs#1957]
Can you please add a section to this article that talks about how many of the settings in this CSP relate to InstantGo capable devices.
It is my understanding that InstantGo capable devices will automatically start Bitlocker encryption (even for standard users) upon first logon, before any of the CSPs have been processed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a05802f-9d0f-9aeb-3c8e-8b92f1284202
* Version Independent ID: 1fd9efc2-8946-75e4-27f3-95ac43a9d987
* Content: [BitLocker CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp)
* Content Source: [windows/client-management/mdm/bitlocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/bitlocker-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
I could be wrong, but I would presume that device specific information regarding almost any software should be posted on the device's own page, not the general software package page (unless other devices have already been included or referenced on the software package page).

**Comment by lindspea** [comment]
@gutjahr Thank you for reaching out and helping improve MS Docs.  Do you perhaps have any suggestions for the information that you think needs to be added? Once I receive this I can send to the team for approval.

**Comment by gutjahr** [comment]
It's been half a year since I wrote my original comment and the question is no longer relevant in its original form. Please feel free to close this item.

**Comment by e0i** [comment]
@officedocsbot close
