### ISSUE TITLE
"Applies to" section and licensing

### ISSUE THREAD

**Issue by joegasper** [MicrosoftDocs/windows-itpro-docs#1967]
The "Applies to" section on this page (and others) I believe could be clearer. I would recommend at a minimum:

Applies to:
Windows Defender, Windows Defender Advanced Threat Protection (Windows Defender ATP) 

PUA protection is available in Windows Defender (and previously in SCEP and FEP) and does not require the purchase of a Windows Defender ATP license. We talk with people running 3rd-party AV and looking to use just Windows Defender, but when they read the pages here their impression is that a number of basic features require purchasing a license. If the "Windows Defender Advanced Threat Protection" section could be split in 2, "Windows Defender" and "Windows Defender ATP" it would be clearer what features and configuration require a license. 
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b27975a-fa49-d9cd-d500-792448c57f9e
* Version Independent ID: 21c3eb7b-065a-b68a-8a88-dfce45571b0d
* Content: [Block potentially unwanted applications with Windows Defender Antivirus](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/detect-block-potentially-unwanted-apps-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/detect-block-potentially-unwanted-apps-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/detect-block-potentially-unwanted-apps-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@joegasper - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @joegasper,
the article is dedicated to Windows Defender Antivirus product, which is part of the Microsoft Defender Advanced Threat Protection, therefore, there is no need to change the "Applies to" section.
Please see the comments of mjcaparas in PR #3733 
Thank you

**Comment by mypil** [comment]
@joegasper - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
