### ISSUE TITLE
GPMC Policy not present

### ISSUE THREAD

**Issue by whatsupbuddy** [MicrosoftDocs/windows-itpro-docs#1977]
Hey Team,

Is there a minimum AD Functional Level or something that should be a pre-requisite? My devices are Hybrid domain joined and are present in AAD, however, i dont seem to have an option within GPMC to create an Intune Enrolment GPO.

Thanks in advance!

**Comment by shortpatti** [comment]
@whatsupbuddy, can you tell me which topic you are referring to so that I can help you get an answer?

**Comment by e0i** [comment]
@AndreaBarr _Recommended closure._
