### ISSUE TITLE
Problem with VM memory allocation

### ISSUE THREAD

**Issue by burke-martin** [MicrosoftDocs/windows-itpro-docs#1980]
For the VM use 4GB of memory. I had failures/errors applying the unattended file with 2GB and this is telling you to use 1GB for the VM....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0eb8c97-caa0-bb05-4b91-14ad2adc4aac
* Version Independent ID: 0cc541a3-8198-c029-d795-308e673ee2f4
* Content: [Create a Windows 10 reference image (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image)
* Content Source: [windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by robidog** [comment]
Full ack. 1 GB just won't be enough.

**Comment by illfated** [comment]
(Please note: personal speculation.)
I wonder if the suggested 1 GB VM size is a forgotten survivor from Windows 7 or older versions. From what I have read recently (I don't have much personal experience with this), it seems there are many IT pros asking for guidelines on how to build or already pre-built down-scaled images (low-priority features removed) to run on lower RAM requirements (for testing or temporary work) than the final deployed targets. I suspect the documentation needs to be reviewed in light of modern HW resource requirements.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @burke-martin, thank you for your feedback. I will get this issue over to the Windows writing team for review and to provide more clarity on the memory requirements. I also requested the team to update this issue if additional information is needed or when the work is complete.

We want users to have the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful and up-to-date. Suggestions, comments and feedback to improve the docs are always welcome!

P.S. Thanks @illfated for your input.

**Comment by jvsam** [comment]
Hi @burke-martin. Thank you again for bringing this to our attention. Please be informed that updates to the documentation (refer to this commit: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3967/commits) have been submitted, but it may make a while for the changes to reflect on live.

**Comment by illfated** [comment]
Looks like the update was rejected by Greg Lindsay on the basis of the documentation example being intended for a VM, not a physical machine.

**Comment by jvsam** [comment]
@illfated indeed, thanks. Thanks for your assistance as well @joinimran.

@burke-martin Burke, since the documentation is a test lab example with a virtual machine (as clarified by @greg-lindsay), then the settings/requirements are only specific to this test case. No changes are currently needed. Thank you for engaging with the community! I will now mark this issue as resolved.

**Comment by robidog** [comment]
Understood, but even as a lab test example with a VM, it will not work with only 1GB of RAM. It's as simple as that. I tried it. Is this really the intention of this otherwise excellent article?

**Comment by jvsam** [comment]
Hi @robidog I believe this conversation linked to the documentation will definitely help users in case they encounter any issues following the test lab example. Of course, we also want to ensure the doc is accurate, hence, where do you propose we add the information? Perhaps on another related documentation? Please let us know and thank you for your feedback. 

Thank you as well, @burke-martin!

For now, we will be closing this issue, but please feel free to re-open it if there is anything in this document that you think should edited or updated.

Thank you for engaging with the community!

**Comment by jvsam** [comment]
@officedocsbot close
