### ISSUE TITLE
Make everyone a Basic Purchaser

### ISSUE THREAD

**Issue by ghvanderweg** [MicrosoftDocs/windows-itpro-docs#1989]
According to these docs, the 'Make everyone a Basic Purchaser' setting is only available in Microsoft Store for Education, but I'm seeing it in our Microsoft Store for Business as well. Is this an error in the documentation or a bug in the Store for Business?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 3dae47ce-fb8d-1802-aace-b99a0f03598a
* Version Independent ID: 35039b4c-6b8e-ac14-6d69-29496589f635
* Content: [Settings reference Microsoft Store for Business and Education (Windows 10)](https://docs.microsoft.com/nl-nl/microsoft-store/settings-reference-microsoft-store-for-business)
* Content Source: [store-for-business/settings-reference-microsoft-store-for-business.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/settings-reference-microsoft-store-for-business.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by ghvanderweg** [comment]
Any update on this?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by illfated** [comment]
@ghvanderweg : Thank you for making us aware of the misleading text in the documentation.
According to the Pull Request #3151 it has been corrected now, but it may still take a couple of days
to migrate to the docs.microsoft.com version of the article.
We hope your question is answered by this change.

**Comment by ghvanderweg** [comment]
@illfated : Thank you, that answers my question! I'll go ahead and close this now.
