### ISSUE TITLE
Clarification on .url Links

### ISSUE THREAD

**Issue by WindyBinDay** [MicrosoftDocs/windows-itpro-docs#1994]
I've been trying to set a new image up for a client and they require .url links in the start menu. For ease of manageability I first tried putting the .url files on the Domain Controller along with the layout file. Within the layout file I was pointing to the UNC path for those .url files: &lt;start:DesktopApplicationTile Size="2x2" Column="3" Row="6" DesktopApplicationLinkPath="\\UNC\Path" /&gt;. This is hands down the best way to be able to deal with this. When our clients need to change the URLs in their start menu we can just push a new layout without messing around with files, but this does not work. The layout file will load fine and pins the applications that I've configured in the layout.xml, but the .url files are not showing up in the start menu.

Next I tried loading the .url files onto the windows image in various folders including %ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Links\Link.url and pointing to them like so: &lt;start:DesktopApplicationTile Size="2x2" Column="0" Row="2" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Links\mylink.url" /&gt; in the layout file but the .url files still do not show up in the start menu. As a side note when loading the start layout manually with the import-startlayout cmdlet there are no errors.

Lastly I've tried using this method: &lt;start:DesktopApplicationTile DesktopApplicationID="http://myurl/" Size="2x2" Row="2" Column="0"/&gt; and again the .url files are not showing up in my start menu.

I am testing on Windows 10 1803.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 061157dc-8fc8-3f9d-c01f-37f22fbdf1c7
* Version Independent ID: 0b0b6797-9367-eb7c-22ef-5f2b8bbfe592
* Content: [Start layout XML for desktop editions of Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/start-layout-xml-desktop#startsecondarytile)
* Content Source: [windows/configuration/start-layout-xml-desktop.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/start-layout-xml-desktop.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @WindyBinDay thank you for sharing your experience in customizing the Start menu. Were you able to successfully configure it? Would you mind letting us know of the status? The doc describes what's *supported* but if you have feedback or suggestions regarding the customized Start, or on things you'd like to be different, I encourage you to add your *voice* in the Windows 10 [User Voice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). You feedback goes directly to the engineering team of the selected feature or product. 

Thank you for engaging with the community!

**Comment by jvsam** [comment]
Hi again @WindyBinDay , we haven't received any response or update from you so we will now close this issue. Please feel free to re-open it if you have comments or suggestions to help improve the contents of this document. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
