### ISSUE TITLE
Link to compliance toolkit download produces "Bad request"

### ISSUE THREAD

**Issue by zuboje** [MicrosoftDocs/windows-itpro-docs#1995]
Link to download tools under Microsoft Security Compliance Toolkit 1.0 (windows-itpro-docs/windows/security/threat-protection/security-compliance-toolkit-10.md) produces:

Bad Request - Request Too Long
HTTP Error 400. The size of the request headers is too long.

To reproduce use following link from that page: https://www.microsoft.com/en-us/download/details.aspx?id=55319

**Comment by shortpatti** [comment]
Closing. Cannot reproduce in version Microsoft Edge 42.17134.1.0; Microsoft EdgeHTML 17.17134.
