### ISSUE TITLE
Supported Windows versions

### ISSUE THREAD

**Issue by chiners68** [MicrosoftDocs/windows-itpro-docs#2000]
This page dosent currently list Windows Server 2019 which is now supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfc0921d-e59b-5186-0dec-7c2facb66f1c
* Version Independent ID: 1fc0f7ba-f8cd-d071-75de-dc5a1af868c0
* Content: [Onboard machines to the Windows Defender ATP service](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/onboard-configure-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/onboard-configure-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/onboard-configure-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by shortpatti** [comment]
@chiners68, Thank you for the feedback :) I've made the suggested correction and it will be published later today.
