### ISSUE TITLE
Support for Windows 10 Education version

### ISSUE THREAD

**Issue by NJArcher** [MicrosoftDocs/windows-itpro-docs#2002]
We use Windows 10 Education. This has some subtle differences to the Enterprise edition that we find useful for our schools. Can you have a Windows 10 Education subscription in the same way as for Enterprise?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ecbc1-9c02-5681-7214-356be22ac7e8
* Version Independent ID: 73af82f6-079b-6c37-55c4-cb59e921457a
* Content: [Deploy Windows 10 Enterprise licenses](https://docs.microsoft.com/en-us/windows/deployment/deploy-enterprise-licenses)
* Content Source: [windows/deployment/deploy-enterprise-licenses.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-enterprise-licenses.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @NJArcher thank you for taking the time to share your suggestion. The product teams are always looking for user feedback to help improve your Windows 10 experience. They would love to hear your suggestion with regard to *Windows 10 Education* extended support. I encourage you to add your *voice* in [User Voice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub) to let the Product teams know. 

Also, please note that others may have already made a similar request or suggestion before, if so, you can add to it or open a new one. 

We will now close this issue. On the other hand, if there is anything in this article that you think should be added or edited, please let us know. We always welcome suggestions and feedback to improve the content of the Microsoft Docs.

**Comment by jvsam** [comment]
@officedocsbot close
