### ISSUE TITLE
Server 1803 /2019 Onvboarding

### ISSUE THREAD

**Issue by chiners68** [MicrosoftDocs/windows-itpro-docs#2003]
This artical dosent link or explain how to onboard using SCCM Policy. Also, can you use the same obnoading config file and deployment in sccm for windows 10 on Server 1803 /2019. Is the onboarding config download the same payload for the different OS's.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4ed2b3-0390-4d53-2450-14995ee8b0b0
* Version Independent ID: 91b5bb3e-55d4-6a8e-c16d-094f15c28ee7
* Content: [Onboard servers to the Windows Defender ATP service](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-server-endpoints-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/configure-server-endpoints-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/configure-server-endpoints-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **justinha**

**Comment by mjcaparas** [comment]
Hello, 
Thank  you for your feedback!

Onboarding using System Center Configuration Manager (current branch) version 1606 and later and MDM are not supported. The team is working on updating the UX on that.

Using System Center Configuration Manager 2012 / 2012 R2 / 1511 /1602 is supported and you can follow the same steps provided for Windows 10 machines. 

With regards to your question about the configuration file, I checked and the file for Windows 10 and the one for System Center Configuration Manager 2012 / 2012 R2 / 1511 /1602 appear to be the same, so yes you can use the same config file.

**Comment by chansolo** [comment]
Any updates on the issue? Thanks!
