### ISSUE TITLE
some laptops does have TPM , but does not have finger reader

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#2009]
Without Fingerprint reader or  face id sensor camera , then there is no use windows hello .
Eventhouth  the  laptops have  TPM , In this  case , users can lock the harddrive with bitlocker using tpm 

Thanks for your article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c34dbafa-df3c-a5a5-32d5-2ce152893534
* Version Independent ID: cebdd9a6-45d7-6306-373c-7d31121f9e16
* Content: [Why a PIN is better than a password (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by deth87** [comment]
Fido 2.0 security keys would be an option here :-) check out this article: https://www.microsoft.com/en-us/microsoft-365/blog/2018/04/17/windows-hello-fido2-security-keys/

**Comment by RAJU2529** [comment]
yes sir, I already read the tpm 2.0 article before posting here.  I concluded that without finger print reader, users still able to lock harddrive using bitlocker. I clearly mentioned.

Thanks for your reply

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @RAJU2529, thank you for engaging with the community here for the docs. 

The product teams are always looking for user feedback to help improve your Windows 10 experience. They would love to hear your suggestion with regard to *Windows Hello*.  Please add your *voice* in [User Voice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). 

Also, please note that others may have already made a similar request before, if so, you can add to it or open a new one. 

We will now close this issue. If there is anything in this article that you think should be added or edited, and is *supported by the current product*, please let us know or you can re-open this issue. We always welcome suggestions and feedback to improve the docs.

**Comment by jvsam** [comment]
officedocsbot close

**Comment by jvsam** [comment]
@officedocsbot close
