### ISSUE TITLE
My recomendationsa to use TPM

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#2010]
I would  recommend  microsoft  to Insist all the OEM manufacturers implement   at least TPM 2.0  on touchpad together  atleast   FIngerprint reader or Face ID camera sensor on the display monitor .on the  laptops .
 
Then only  windows hello is usefull  to users otherwise  , no use 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c34dbafa-df3c-a5a5-32d5-2ce152893534
* Version Independent ID: cebdd9a6-45d7-6306-373c-7d31121f9e16
* Content: [Why a PIN is better than a password (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @RAJU2529 I believe your suggestion here is similar to the other [issue you've opened](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2009). I encourage you to add your *voice* in [User Voice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub) to let the Product teams know. 

We will now close this issue. Thank you again for taking your time to share your feedback.

**Comment by jvsam** [comment]
@officedocsbot closed
