### ISSUE TITLE
What will happens  , if  device A is not connected to internet

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#2011]
So in this case , the user cant be  sign on device A ? , because  after changing the password on device B connected to internet , but device A is  not connected .
I think the user  still can be  sign on device A through offline

Please explain sir , sorry i am giving you much  work 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba665984-14d2-e5f1-a1a4-e8c28b61571d
* Version Independent ID: 4918b293-ce78-154b-a3ee-515557367d8c
* Content: [Windows Hello and password changes (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-and-password-changes)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-and-password-changes.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-and-password-changes.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by egallagh** [comment]
Yes, the offline device can sign in using previously cached credentials if it cannot connect online to verify the current new password.

**Comment by RAJU2529** [comment]
Thanks for the answer

**Comment by egallagh** [comment]
You are welcome.
I hope that helped.
Recommend closure.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot close
