### ISSUE TITLE
To unjoin a device running Windows 10 Mobile, you must reset the device , its not a solution

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#2012]
i think resettingthe device is  not a solution , because the users may have confidential  datas on his  mobile including messages and documents , once the device has reset , all datas are wiped out .

So windows mobile os engineers should reconsider the solution , if possible without reset device , find if any other solutions may have helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by egallagh** [comment]
Any data that is on the device should also be synced to the corporate environment and would persist there. When the device is un-joined it is no longer under corporate control and therefor all data that exists on the device should be deleted for compliance purposes.
I hope that helps.

**Comment by RAJU2529** [comment]
Your solution gives, If the  employer resigns or retired or fired from the organization. Then his smartpHone must be  unjoined  from the corporate network.
Is It

**Comment by egallagh** [comment]
Performing a remote reset of the device will unjoin it from AAD in addition to wiping the corporate data.

**Comment by e0i** [comment]
Hello, @RAJU2529 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot close
