### ISSUE TITLE
If we reinstalled the fingerprint reader driver

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#2013]
If we reinstalled the fingerprint reader driver means ,  after that we  need to  create windows hello setup  including PIN and  capture Fingerprint 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e8d779-ec27-6dc4-5142-f97ca1db63d7
* Version Independent ID: e3f6b432-acc7-c5b0-dba0-18ab34eb65e8
* Content: [How Windows uses the TPM](https://docs.microsoft.com/en-in/windows/security/information-protection/tpm/how-windows-uses-the-tpm)
* Content Source: [windows/security/information-protection/tpm/how-windows-uses-the-tpm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/tpm/how-windows-uses-the-tpm.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by andreabichsel** [comment]
That is my understanding. If you are having any problems, please use https://support.microsoft.com to help resolve them. Thank you!
