### ISSUE TITLE
i could not able to find on gpo

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#2014]
i could not be able to find on gpo
Computer Configuration\Administrative Templates\Windows Components\Windows Security\Device security

i am using windows 10 enterprise  1803 64 bit build no 17134.376 
Please include device secutity templates in coming weeks 
here is screenshot 
![gp3](https://user-images.githubusercontent.com/3296790/47804179-2c032980-dd5a-11e8-83e5-305db9837345.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d46fce78-6956-1b3a-124f-e8188d0412cd
* Version Independent ID: 5891df2d-6432-c5b4-0eff-49b520f59067
* Content: [TPM Group Policy settings (Windows 10)](https://docs.microsoft.com/en-in/windows/security/information-protection/tpm/trusted-platform-module-services-group-policy-settings)
* Content Source: [windows/security/information-protection/tpm/trusted-platform-module-services-group-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/tpm/trusted-platform-module-services-group-policy-settings.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by andreabichsel** [comment]
This is the path for Windows 10, version 1809. The path in previous versions is Computer Configuration\Administrative Templates\Windows Components\Windows Defender Security Center\Device security. Thank you!
