### ISSUE TITLE
Dedicated CA

### ISSUE THREAD

**Issue by wolfrium** [MicrosoftDocs/windows-itpro-docs#2016]
Can someone clarify the reason for needing a dedicated CA for SEMM?  "It is also recommended that the SEMM certificate be authenticated in a two-tier public key infrastructure (PKI) architecture where the intermediate certification authority (CA) is dedicated to SEMM, enabling certificate revocation. For more information about a two-tier PKI configuration, see Test Lab Guide: Deploying an AD CS Two-Tier PKI Hierarchy."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0d25836-4403-d111-9bd7-ca5f1ed56449
* Version Independent ID: 5219aa78-698c-926c-53d8-f02fdf36bb3b
* Content: [Surface Enterprise Management Mode (Surface)](https://docs.microsoft.com/en-us/surface/surface-enterprise-management-mode)
* Content Source: [devices/surface/surface-enterprise-management-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/surface-enterprise-management-mode.md)
* Product: **w10**
* GitHub Login: @jobotto
* Microsoft Alias: **jdecker**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
@wolfrium : There is no absolute requirement (does not say "required" or "needed"), it just says
> It is also recommended [ ... ]

My guess is that this is for safety/security/controllability reasons.

**Comment by e0i** [comment]
Hello, @wolfrium 

It seems that your question has been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
