### ISSUE TITLE
Add instead of Replace

### ISSUE THREAD

**Issue by bbetnar** [MicrosoftDocs/windows-itpro-docs#2018]
It would be nice to add Administrators instead of replacing the existing set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0c28c15-f0be-d732-4d9e-cf5df5e64e8b
* Version Independent ID: 17eba45f-d200-e656-42b9-e1a512931eea
* Content: [Policy CSP - RestrictedGroups](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-restrictedgroups)
* Content Source: [windows/client-management/mdm/policy-csp-restrictedgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-restrictedgroups.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by egallagh** [comment]
The idea behind a restricted group is to enforce membership to only those in the list. This enforces the removal of a group member that was added in through any other method in order to, in part, satisfy compliance needs.
Hope this helps

**Comment by bbetnar** [comment]
While I see your point, it doesn't help our use case in particular. In our use case we are using Intune as our MDM and we want to adjust the local admins on a small subset of computers. During Autopilot enrollment, the user is added as Local Admin (we like this). But we also want to add another user (the IT Admin who works at that office building). When we use this to set another user it clobbers the existing user which we don't want. The workaround I see for this would be to create a separate policy for every workstation, but that adds more overhead than we'd like to spend on this task.

**Comment by egallagh** [comment]
To my understanding, supporting a scenario like that is not the intent of this policy. Personal opinion: I would take a serious look at the wisdom of having users be admins.

**Comment by bbetnar** [comment]
I agree that having users as Admins isn't always Best Practice. But it's not a best fit for everybody and for our company it works best having them as Local Admins and we're not ready to make the change. 

But since that's not the intent of this policy I'll just go ahead and close this.
