### ISSUE TITLE
What about 1809?

### ISSUE THREAD

**Issue by nimojg-microsoft** [MicrosoftDocs/windows-itpro-docs#2021]
No guidance on Windows Build 1809

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45b5ec5c-d7ed-3aad-d27b-66f944a14c9f
* Version Independent ID: 87af0e5f-f817-10c1-cfff-6f47c35aedcc
* Content: [Switch to Windows 10 Pro Education in S mode from Windows 10 Pro in S mode](https://docs.microsoft.com/en-us/education/windows/s-mode-switch-to-edu)
* Content Source: [education/windows/s-mode-switch-to-edu.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/s-mode-switch-to-edu.md)
* Product: **w10**
* GitHub Login: @MikeBlodge
* Microsoft Alias: **celested**

**Comment by e0i** [comment]
@mjcaparas Are there any plans to include content for build 1809? Authoritative clarification needed. Thanks.

**Comment by e0i** [comment]
@mjcaparas Any updates with this query? Thanks.
