### ISSUE TITLE
Add "Enabled:Dynamic Code Security" option to list of policy rule options

### ISSUE THREAD

**Issue by morganbr** [MicrosoftDocs/windows-itpro-docs#2022]
The list of policy rule options should include "Enabled:Dynamic Code Security" (full documentation at https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-dynamic-code-security) with a description along the lines of "Enables policy enforcement for .NET applications and dynamically-loaded libraries." I'm not sure what the matching policy index is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d4ecadb-c54e-5da1-03ae-1301a35ef64a
* Version Independent ID: 69d28732-f557-9ae1-cec4-594a2ec097a2
* Content: [Select the types of rules to create  (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md)
* Product: **w10**
* GitHub Login: @jsuther1974
* Microsoft Alias: **justinha**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @morganbr , thank you for your submitting your feedback. I will get this issue over to the Windows writing team for review. I also requested the team to update this issue if additional information is needed or when the work is complete.

Thank you for your contribution to make the docs better! We always welcome suggestions, comments or feedback to improve the docs.

**Comment by jvsam** [comment]
Hi again @morganbr. Thank you for your feedback to help improve the contents of this document. We want users to have the best Windows 10 experience by ensuring the docs are accurate and up-to-date so your contribution is appreciated!

Please be informed that updates (refer to this commit: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3974/files) have been submitted, but it may make a while for the changes to reflect on live. Thank you!

**Comment by jvsam** [comment]
Hi @morganbr , we'd like to inform you that the document has been updated. We will now close this issue.

Thank you again for taking the time to share your feedback. Your contribution to make the docs better is appreciated and will definitely help other Windows 10 users!

**Comment by jvsam** [comment]
@officedocsbot close
