### ISSUE TITLE
Need Surface Laptop 2 drivers for Enterprise OSD

### ISSUE THREAD

**Issue by emeria** [MicrosoftDocs/windows-itpro-docs#2024]
Does anyone know where we can get the drivers for the Surface Laptop 2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586d1246-6e18-b33c-2382-52a53bb392f5
* Version Independent ID: 0ec4aa1e-aac0-98dd-0a47-83e93d854086
* Content: [Download the latest firmware and drivers for Surface devices (Surface)](https://docs.microsoft.com/en-us/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices)
* Content Source: [devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md)
* Product: **w10**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by shayan73** [comment]
I would like to know this as well.

**Comment by emeria** [comment]
Looks like they have been released quietly.  
https://www.microsoft.com/en-us/download/details.aspx?id=57515

**Comment by jdeckerms** [comment]
@emeria Thanks for updating the topic with the new links! I'm back from vacation and merged your pull request.
