### ISSUE TITLE
Update/EngagedRestartTransitionSchedule

### ISSUE THREAD

**Issue by bally-singh** [MicrosoftDocs/windows-itpro-docs#2026]
Update/EngagedRestartTransitionSchedule

Supported value range: 0 - 30 is incorrect. It is between 2-30.

"The period can be set between 2 and 30 days from the time the restart becomes pending."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ca58bd-f279-7739-0140-c4bd56784768
* Version Independent ID: 1d2ecc90-58a3-6bcd-84ae-ef04d7a3b7b4
* Content: [Policy CSP - Update](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update#update-activehoursmaxrange)
* Content Source: [windows/client-management/mdm/policy-csp-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-update.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by shortpatti** [comment]
@bally-singh, thank you for the feedback.  I've updated the supported value range and it will be published later this morning :)
