### ISSUE TITLE
Which Windows 10 features support WDAG?

### ISSUE THREAD

**Issue by Houndsong** [MicrosoftDocs/windows-itpro-docs#2031]
What additional Windows 10 features must be installed or enabled to support this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8927df09-e9aa-8c40-290d-0ca7d86ec4e2
* Version Independent ID: ca67bcfc-6120-d6ca-290b-1a7822494c73
* Content: [Frequently asked questions - Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Houndsong** [comment]
@shortpatti @Justinha More info and example: The screenshot of the selection dialog, Turn Windows Features on or off, shows Windows Defender Application Guard dimmed, and the tooltip says it's not available on this configuration. None of our other machines show WDAG as unavailable, and we have it turned on. Is there a group of settings or features that must be enabled simultaneously to support WDAG? P.S. I've learned a little more about WDAG since asking this question, and I suspect the hindrance on this machine is 4GB RAM against the recommended 8GB RAM.  

![20181116 0428 snip windows features wdag](https://user-images.githubusercontent.com/40254915/48616089-33305700-e958-11e8-802c-b06ff0b9ff30.png)

**Comment by Justinha** [comment]
@Houndsong sorry for delay. Yes, 8GB seems required: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard

That topic fell out of the table of contents on the left (my mistake). I'll fix that today. I'll check with engineering if there are any other requirements that are keeping WDAG unavailable. Can you confirm VBS is running (msinfo32)?

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
> I've learned a little more about WDAG since asking this question, and I suspect the hindrance on this machine is 4GB RAM against the recommended 8GB RAM.

Hi @Houndsong, @Justinha confirmed that 8GB RAM is the minimum requirement for hardware memory as indicated in the [system requirements](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard). The doc is also now visible in the WDAG Table of Contents on the left for easy access. Thank you for your question and we hope your issue has been resolved. 

We will now close this issue, but please feel free to re-open it if you have additional questions, comments or suggestions to help improve the docs. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
