### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by 0xVox** [MicrosoftDocs/windows-itpro-docs#2036]
Guys, think you messed the formatting on the CLI Options block there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71b277e6-1f71-cf05-0d21-d24e5d25591b
* Version Independent ID: 78a49db9-9652-b4a6-a059-2ee599e7c0bb
* Content: [How to Deploy the App-V Client](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/appv-v5/how-to-deploy-the-app-v-client-gb18030)
* Content Source: [mdop/appv-v5/how-to-deploy-the-app-v-client-gb18030.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/appv-v5/how-to-deploy-the-app-v-client-gb18030.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@0xVox - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@nenonix - as discussed, kindly assist with this issue. Thank you.

**Comment by mypil** [comment]
@0xVox - Pull Request #4087 has been created by @nenonix to fix and close this issue once the PR is merged.

Thank you for your contribution to make the docs better! Much appreciated!
