### ISSUE TITLE
Link was for help diagnosing provisioning package failures

### ISSUE THREAD

**Issue by whampt** [MicrosoftDocs/windows-itpro-docs#2038]
Not all provisioning package install failures come via mdm. Please write article on how to troubleshoot provisioning package failures when ppkg is applied via powershell, OOBE or double-click. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738225b2-66a4-e0dd-47fb-faf333ed52d1
* Version Independent ID: d9d3274c-3ee7-ed3a-6cd8-6b387027562c
* Content: [Diagnose MDM failures in Windows 10](https://docs.microsoft.com/en-us/windows/client-management/mdm/diagnose-mdm-failures-in-windows-10)
* Content Source: [windows/client-management/mdm/diagnose-mdm-failures-in-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/diagnose-mdm-failures-in-windows-10.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by whampt** [comment]
@jdeckerms There isn't one. Am asking for an article to be written on debugging provisioning without an mdm and a link to the article to be provided. Should be able to find out, for example, if provisioning failed due to malformed xml file. 

When I got an error message from my failed provision via double-click on ppkg, I clicked on the link for more information in the error message. It brought me to https://docs.microsoft.com/en-us/windows/client-management/mdm/diagnose-mdm-failures-in-windows-10, which was not relevant as my options for deploying ppkg files are OOBE, powershell, double-click on ppkg file in File Explorer or Settings app. 
Thank you for your time and attention

**Comment by jdeckerms** [comment]
@whampt I need to pinpoint where the link is that needs to be changed. Can you grab a screenshot of the error message where the link appears?

**Comment by whampt** [comment]
After attempted install of ppkg via double-click, I can navigate Settings->Accounts->Access Work or School->Add or Remove provisioning package
Then click provisioning package name, I get choice of Details and Remove. Selecting Details gives me the attached view, with link for “Troubleshoot Provisioning issues” at bottom.

The link takes me to the afore-mentioned MDM troubleshooting page.

My current employer is an American University. We are a Kace shop, so we don’t have an MDM. Thanks for your help with this. Am having issues with setting taskbar & default apps as the windows 7 ways to customize these no longer apply. Those topics are all I want the provisioning package to do.

**Comment by jdeckerms** [comment]
@whampt I'll work with the product team to provide more guidance on troubleshooting provisioning and then get the link updated. This will probably take some time.

It sounds like you're applying a Start/taskbar layout with your ppkg, in which case the content for troubleshooting Start layout might help: https://docs.microsoft.com/en-us/windows/configuration/windows-10-start-layout-options-and-policies#start-layout-configuration-errors

**Comment by jdeckerms** [comment]
@whampt I'm glad it helped. :)

**Comment by mypil** [comment]
@whampt - Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
