### ISSUE TITLE
SCRIL breaks WHfB provisioning

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/windows-itpro-docs#2039]
[Enter feedback here]
Step 3 sounds great but if you enable SCRIL Windows Hello for Business provisionning does not work anymore, because users can't first log in with their password. You have to disable SCRIL, set a new password, provision WHfB then reenable SCRIL. Is there another way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca080bd-ed37-60a8-ec22-b1929166ff0c
* Version Independent ID: d2742e0c-9d66-4b1f-8555-a1fb1546455b
* Content: [Password-less Strategy](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/passwordless-strategy)
* Content Source: [windows/security/identity-protection/hello-for-business/passwordless-strategy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/passwordless-strategy.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Martony78 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete

**Comment by joinimran** [comment]
Hello @Martony78 , There is no other way to set this up. The point you have mentioned looks like a good suggestion and I would like you to raise your voice using any of our feedback channels. 

@mypil Please guide @Martony78 how he can share feedback and request for the new feature with Windows Hello.

Thanks.

**Comment by mypil** [comment]
@Martony78 - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**

You might find others have made a similar request that you can add to, or you can open a new one.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
-------------------------------------
@officedocsbot close
