### ISSUE TITLE
Error code 45

### ISSUE THREAD

**Issue by 20floz** [MicrosoftDocs/windows-itpro-docs#2041]
It should be "Diagtrack.dll was not found". Not "Diagrack.dll was not found". Helps searching if it is listed correctly.

**Comment by jdeckerms** [comment]
@20floz Somehow your issue got opened without being associated to a topic. Could you add a link to the topic that you're referring to? Thanks.

Btw, anytime you find errors like that, we encourage you to fix them directly! Start by clicking "edit" in the upper right of the topic. For instructions, see https://docs.microsoft.com/en-us/contribute/

**Comment by lizap** [comment]
Fixed by a public contribution, which will go live on 1/14 PM.
