### ISSUE TITLE
Access Denied error and script exit 

### ISSUE THREAD

**Issue by ahcash** [MicrosoftDocs/windows-itpro-docs#2042]
Is it just me or any of you have the same issue.
I ran the script and it failed with Access Denied 0 files copied.
I think it failed on the following because this file cannot be replaced even if elevated command prompt.

Copy /Y %source%\powershell.exe.config %PowershellHome%\powershell.exe.config

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f029a728-1f53-4576-a6ca-8a19a92626e6
* Version Independent ID: 85f27ad5-84e2-0787-082f-59d2d66c99b5
* Content: [Upgrade Readiness deployment script (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-deployment-script)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-deployment-script.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-deployment-script.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ahcash - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @ahcash ,
by default, only "Trusted Installer" has access to modify powershell.exe.config file, that's why the error appear. Have you tried to "use ConfigMgr or other software deployment service to run RunConfig.bat as system" as it states in the step 6 in the article?

Thank you

**Comment by mypil** [comment]
@ahcash - From our understanding, the issue has been answered by MaratMussabekov. If you feel it hasn't been answered please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
