### ISSUE TITLE
There are no "Best Practices" for this setting

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/windows-itpro-docs#2044]
Kindly remove that note as there are no best practices with this setting,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4e0e95f-4b95-51ef-d881-43bd2245d2c1
* Version Independent ID: 7f414727-7e8b-939d-f40e-0636d2b33f1a
* Content: [System cryptography Use FIPS compliant algorithms for encryption, hashing, and signing (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/system-cryptography-use-fips-compliant-algorithms-for-encryption-hashing-and-signing)
* Content Source: [windows/security/threat-protection/security-policy-settings/system-cryptography-use-fips-compliant-algorithms-for-encryption-hashing-and-signing.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/system-cryptography-use-fips-compliant-algorithms-for-encryption-hashing-and-signing.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@StingyJack - Thank you for submitting this feedback.

From our understanding, the issue has already been resolved based on the commit ([cfbc209](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/cfbc2094b4fcdb999f3183a579776080ebcae449#diff-65a657acbce5acf94c69617891b57258)) made by the author.  If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
