### ISSUE TITLE
Content Advisor

### ISSUE THREAD

**Issue by tjvauthier** [MicrosoftDocs/windows-itpro-docs#2048]
Why did you remove content advisor? I can now no longer lock down internet access on domain computer. I need to be able to do this for some of my customers, and you have now made it almost impossible for some of my users to use Windows 10. Thanks for that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c274f8df-31da-f58a-36af-dc7eb6ace762
* Version Independent ID: 0e33637d-e094-edbc-04f9-e8d5e6c642c6
* Content: [Windows 10, version 1803 - Features that have been removed](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-1803-removed-features)
* Content Source: [windows/deployment/planning/windows-10-1803-removed-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-10-1803-removed-features.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by jdeckerms** [comment]
@tjvauthier I understand your frustration. Please submit your comments in the Feedback Hub so that your need for the feature is sent to the engineering team. That also enables other customers to upvote your comments.
