### ISSUE TITLE
Set-AdfsCertificateAuthority missing parameter

### ISSUE THREAD

**Issue by xXxOlivierxXx** [MicrosoftDocs/windows-itpro-docs#2050]
In your Set-AdfsCertificateAuthority command, make sure to include the parameter -WindowsHelloCertificateProxyEnabled $true 
If this parameter is not included, ADFS will not advertise as a registration authority through the Proxy Servers, which will cause the WHFB enrollment to fail to all users connecting through the proxy.

More information about this problem and resolution can be found here: https://social.technet.microsoft.com/Forums/projectserver/en-US/c5ff6ca6-7382-4cc9-b95e-c49e78422cb6/windows-hello-for-business-failed-to-locate-a-certificate-registration-authority?forum=win10itprosecurity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d7753d-30e1-db13-429a-c0b4eaf2c9c5
* Version Independent ID: 5be668ea-fc9d-0fb5-585d-4f5d5575b416
* Content: [Configuring Hybrid Windows Hello for Business - Active Directory Federation Services (ADFS)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-adfs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-adfs.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@xXxOlivierxXx - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@xXxOlivierxXx - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
