### ISSUE TITLE
The "Use exposed tables in Advanced hunting" section is missing the MachineNetworkInfo table

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#2055]
The "Use exposed tables in Advanced hunting" section is missing the MachineNetworkInfo table. This table was announced a while ago: https://techcommunity.microsoft.com/t5/What-s-New/Advanced-hunting-now-includes-network-adapters-information/td-p/224402

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7522c47-aa38-2cf3-34b7-e8ad36dc80eb
* Version Independent ID: 6f26550f-0d21-479d-8479-b7bd563a2302
* Content: [Query data using Advanced hunting in Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/advanced-hunting-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/advanced-hunting-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/advanced-hunting-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by lomayor** [comment]
Already fixed as of several days ago. @mjcaparas , kindly close please.
