### ISSUE TITLE
Query Language link points docs.loganalytics.io 

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#2056]
docs.loganalytics.io is no more. The Query Language link should probably link to https://docs.microsoft.com/en-us/azure/log-analytics/query-language/query-language

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7522c47-aa38-2cf3-34b7-e8ad36dc80eb
* Version Independent ID: 6f26550f-0d21-479d-8479-b7bd563a2302
* Content: [Query data using Advanced hunting in Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/advanced-hunting-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/advanced-hunting-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/advanced-hunting-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Thanks! Link should be updated shortly.
