### ISSUE TITLE
Missing descriptions of a few Advanced Hunting columns

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#2057]
The **Table**, **OsVersion**, and **AppGuardContainerId** columns are missing from the Advanced Hunting reference documentation.

- AlertEvents - Table
- MachineInfo - OsVersion
- MachineNetworkInfo - OsVersion
- ProcessCreationEvents - AppGuardContainerId, OsVersion
- NetworkCommunicationEvents - AppGuardContainerId, OsVersion
- FileCreationEvents  AppGuardContainerId, OsVersion
- RegistryEvents - AppGuardContainerId, OsVersion
- LogonEvents - AppGuardContainerId, OsVersion
- ImageLoadEvents - AppGuardContainerId, OsVersion
- MiscEvents - - AppGuardContainerId, OsVersion

EventType exists in the current documentation but it isn't in any of the tables. Perhaps EventType is actually Table?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 465c3bf3-a207-3113-1052-f237a224ebfb
* Version Independent ID: 733dac2c-2e47-8c0e-a0c1-fd925c3184ea
* Content: [Advanced hunting reference in Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/advanced-hunting-reference-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/advanced-hunting-reference-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/advanced-hunting-reference-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by iadgovuser1** [comment]
TunnelingProtocol is listed on that page. I can't find this in WDATP though. MachineNetworkInfo has a TunnelType column. I'm guessing that TunnelingProtocol should be changed to TunnelType.

**Comment by iadgovuser1** [comment]
DnsServers is listed on that page. I can't that column in WDATP though. MachineNetworkInfo has a DnsAddresses column. I'm guessing that DnsServers should be changed to DnsAddresses.

**Comment by iadgovuser1** [comment]
Protocol is missing from that page. It is part of the NetworkCommunicationEvents table. Known values are Tcp, Udp, and Unknown.

**Comment by iadgovuser1** [comment]
InitiatingProcessParentFileName is also missing from that page. It is in the NetworkCommunicationEvents table.

**Comment by iadgovuser1** [comment]
PreviousRegistryKey and PreviousRegistryValueType are listed on that page but neither are in the RegistryEvents table.

**Comment by mjcaparas** [comment]
Thank you for your feedback. We're actively looking at the content and will be making updates shortly.
