### ISSUE TITLE
No Surface Pro 6 Driver packages

### ISSUE THREAD

**Issue by lshunnarah77** [MicrosoftDocs/windows-itpro-docs#2061]
Hi, it would be nice if MS would make these driver packs available when the hardware is available.  I'm running in the same issue I ran into with the Surface Go.  I now see that the Surface Go has their own link to download the driver packs.  Does MS assume that we are going to use the factory image and not use our company images on these laptops?  Is that why there is a delay?  I'm a little confused on the logic behind this process.  If someone could please provide a link to the driver pack for the Surface Pro 6 I would really appreciate it.

Thanks,
Louis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586d1246-6e18-b33c-2382-52a53bb392f5
* Version Independent ID: 0ec4aa1e-aac0-98dd-0a47-83e93d854086
* Content: [Download the latest firmware and drivers for Surface devices (Surface)](https://docs.microsoft.com/en-us/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices)
* Content Source: [devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md)
* Product: **w10**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@lshunnarah77 We'll add a lnk to the Surface Pro 6 driver download as soon as it's available. I encourage you to add your comments on having driver packs available at the same time as new hardware is released, along with an explanation of your organization's need to use company images rather than factory images, in the Feedback Hub so that this issue goes directly to the engineering team that handles them.

**Comment by lshunnarah77** [comment]
I will do that.  Thanks for the advice.

**Comment by jdeckerms** [comment]
@lshunnarah77 The package is available now: https://www.microsoft.com/en-us/download/details.aspx?id=57514

I'll add the link to the topic today.
