### ISSUE TITLE
Update to include AppInstaller and MSIX

### ISSUE THREAD

**Issue by rido-min** [MicrosoftDocs/windows-itpro-docs#2062]
This doc should acknowledge that users can double click any APPX/MSIX and get the app installed without using the powershell script (that was provided for development and testing). 

We should link to the appinstaller file.

I'd rather recommend to deploy the certificate to the `Trusted People` instead of `Trusted Root Certification authorities`, since it reduces the surface attack in case the cert is compromised.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9325458-db83-c021-9ff3-ffe331896aa3
* Version Independent ID: 3912b3b0-6af4-1d3a-fd81-964357ce6434
* Content: [Sideload LOB apps in Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/application-management/sideload-apps-in-windows-10)
* Content Source: [windows/application-management/sideload-apps-in-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/sideload-apps-in-windows-10.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **elizapo**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by j0rt3g4** [comment]
Added a comment #3743

**Comment by e0i** [comment]
@rido-min 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
