### ISSUE TITLE
Wording doesn't make sense

### ISSUE THREAD

**Issue by brownmbg** [MicrosoftDocs/windows-itpro-docs#2064]
The wording here does not make sense, and should be corrected:

&gt; The Enable Windows Hello for Business Group Policy setting is the configuration needed for Windows to determine if a user should be attempt to enroll for Windows Hello for Business. A user will only attempt enrollment if this policy setting is configured to enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ec90f64-9a12-fdf9-25db-0e83cf77b7a2
* Version Independent ID: fb68756c-2d0c-c28c-4bda-ef6a876576e7
* Content: [Configure Windows Hello for Business Policy settings (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by illfated** [comment]
Draft / preliminary suggestion:
***
The Group Policy setting
"Enable Windows Hello for Business"
needs to be configured
in order for Windows to determine
if a user should attempt to enroll
for Windows Hello for Business.

User enrollment can only be attempted
if this policy configuration setting
is set to enabled.
***
I will take a look at the originating page and see if the context requires a different wording.

**Comment by illfated** [comment]
Judging by the originating page, it looks like focus is on making sure that the group policy is present, more so than configured.

Draft / suggestion 2:
***
The Enable Windows Hello for Business Group Policy configuration setting
needs to be present for Windows to determine if a user should attempt
enrollment for Windows Hello for Business.

Enrollment will only be attempted if this policy setting is configured to enabled.

**Comment by brownmbg** [comment]
Suggestion 2 looks like a winner!

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by illfated** [comment]
@mypil : Would you like a Pull Request for the suggested change in wording for that paragraph? (https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings.md#enable-windows-hello-for-business-group-policy)

If you or any of your colleagues have got a slightly different wording in mind, it can be posted to the PR asking for that change, in case my original suggestion from Nov 9, 2018 is less precise than what you require.

**Comment by mypil** [comment]
@illfated - Thank you for your valuable suggestion. I have assigned @nenonix to work on creating a PR for this issue. We appreciate your contribution in improving the docs as always.

**Comment by nenonix** [comment]
I propose:

"The Group Policy setting gives specified users the option to self-enroll in Windows Hello for Business. To configure user or device targeted Group Policy settings, the Windows Hello for Business Group Policy must be enabled." 

or 

"The Group Policy setting allows users to enroll themselves in Windows Hello for Business.  Enable the Windows Hello for Business Group Policy setting to configure this option for specific users."

**Comment by illfated** [comment]
Both versions look valid and explanatory to me, but I don't have direct working experience from this material. I think it will be more obvious for someone like the OP (@brownmbg ) to say which text works better as a single explanation for the Group Policy setting. (Having read the original and suggested alternatives so many times without having the need to use it in a Windows Hello for Business environment, they all seem to explain the scenario sufficiently to me, albeit from different angles of approach.)

**Comment by brownmbg** [comment]
> "The Group Policy setting gives specified users the option to self-enroll in Windows Hello for Business. To configure user or device targeted Group Policy settings, the Windows Hello for Business Group Policy must be enabled."

@nenonix @illfated Looks good to me!

**Comment by nenonix** [comment]
May I ask what or who is "the OP"?

**Comment by brownmbg** [comment]
> May I ask what or who is "the OP"?

@nenonix OP = original poster 👍

**Comment by nenonix** [comment]
about the version I pushed -auto-enrollment as that appears to be the technical term, and the doc uses computer rather than device, so I did too  The word "attempt" -- I understand the intention to convey that successful enrollment is not guaranteed, but I tried to improve on that as well. Thanks all.feel free to suggest changes..
