### ISSUE TITLE
I want to add some sentence to this article 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#2067]
I want to edit some sentence to this article , so How I add, please give steps how to edit .
I am waiting for your reply sir 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8dcd3ea-06e9-53de-5473-9c96fa979152
* Version Independent ID: 1ad84165-00f1-a2a6-b266-b1b0f70dfa00
* Content: [Microsoft Edge - Security and privacy group policies](https://docs.microsoft.com/en-in/microsoft-edge/deploy/group-policies/security-privacy-management-gp)
* Content Source: [browsers/edge/group-policies/security-privacy-management-gp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/group-policies/security-privacy-management-gp.md)
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by jdeckerms** [comment]
@RAJU2529 Instructions for contributing to the documentation are here: https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/CONTRIBUTING.md

**Comment by RAJU2529** [comment]
thanks madam,  today I editted two  topics and I sent pulled requests to author
