### ISSUE TITLE
Error Code 63

### ISSUE THREAD

**Issue by Argon0** [MicrosoftDocs/windows-itpro-docs#2068]
Some of my clients get error code 63... This also isn't in the table, please add (this is related to the UpgradeReadiness script).

**Comment by jdeckerms** [comment]
@Argon0 Somehow your issue got opened without being associated to a topic. Could you add a link to the topic that you're referrring to? Thanks.

**Comment by Nacimota** [comment]
I believe this issue refers to `windows/deployment/upgrade/upgrade-readiness-deployment-script.md`.

**Comment by illfated** [comment]
For readers unused to converting relative folder names, the URLs to the pages are:
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-deployment-script.md
- https://docs.microsoft.com/windows/deployment/upgrade/upgrade-readiness-deployment-script

**Comment by e0i** [comment]
@Argon0 Thank you for providing valuable feedback.

The changes you have suggested have been merged into the documentation.

[Link to commit](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/0fb93168e1242ac2a24142cf764d15796209b85d#diff-e1faf4d562cb1b3981113db7d3eecad6)

@AndreaBarr This issue can be closed as it has been resolved.
