### ISSUE TITLE
Link to best practices content gets 404

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/windows-itpro-docs#2070]
Looks like a broken link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 465c3bf3-a207-3113-1052-f237a224ebfb
* Version Independent ID: 733dac2c-2e47-8c0e-a0c1-fd925c3184ea
* Content: [Advanced hunting reference in Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/advanced-hunting-reference-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/advanced-hunting-reference-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/advanced-hunting-reference-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Oh. Right.
**https://docs.microsoft.com/en-us/advanced-hunting-best-practices-windows-defender-advanced-threat-protection.md**

The public link should normally not end in `.md` .
The link in the source file `advanced-hunting-reference-windows-defender-advanced-threat-protection.md` results in the 404 page too.

Is it possible that the link
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/advanced-hunting-best-practices-windows-defender-advanced-threat-protection
would be the correct page? Or is the correct "best practices" page simply missing?

**Comment by mjcaparas** [comment]
Hi illfated! You're absolutely right. It should be: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/advanced-hunting-best-practices-windows-defender-advanced-threat-protection 

I'll fix the link asap. 
Thank you for your feedback :)
