### ISSUE TITLE
True for later Feature updates?

### ISSUE THREAD

**Issue by mdashoff** [MicrosoftDocs/windows-itpro-docs#2071]
Is this information true for later Feature Updates? Such as 1709, 1803, etc...?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c91ae55-29b0-a5e1-b715-a72ac4270050
* Version Independent ID: a102db60-b94c-573a-6ba9-9970d9ac5b44
* Content: [Change the TPM owner password (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/change-the-tpm-owner-password#feedback)
* Content Source: [windows/security/information-protection/tpm/change-the-tpm-owner-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/tpm/change-the-tpm-owner-password.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by andreabichsel** [comment]
No, just for the versions mentioned. Thank you!
