### ISSUE TITLE
Error Importing the .csv

### ISSUE THREAD

**Issue by PJMarcum** [MicrosoftDocs/windows-itpro-docs#2079]
Followed the instructions to the letter on a hyperv guest and I get an error when I try to import the csv. Error Code: 802 - InvalidZtdHardwareHash

**Comment by jdeckerms** [comment]
@PJMarcum Somehow your issue got opened without being associated with a specific topic. Could you add a link to the topic you're referring to? Thanks.

**Comment by e0i** [comment]
@AndreaBarr _Recommended closure._
