### ISSUE TITLE
Pre-Launch Registry Key wrong location

### ISSUE THREAD

**Issue by roman-schraner** [MicrosoftDocs/windows-itpro-docs#2084]
Dear Edge Team,

It seems like the provided Registry Key Path in "Allow Microsoft Edge to pre-launch at Windows startup, when the system is idle, and each time Microsoft Edge is closed" is not correct. According to my own testing the path should be (the "Main" key should be included):
Path: HKLM\Software\Policies\Microsoft\MicrosoftEdge\Main
Value name: AllowPrelaunch

This is also indicated by: https://winaero.com/blog/disable-microsoft-edge-prelaunching-windows-10/

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e25cdec-6b2f-2e44-6512-83b13d13ff51
* Version Independent ID: f97436ae-01fc-a3bb-d0e8-2b20265ebc56
* Content: [Microsoft Edge - Prelaunch and tab preload group policies](https://docs.microsoft.com/en-us/microsoft-edge/deploy/group-policies/prelaunch-preload-gp)
* Content Source: [browsers/edge/group-policies/prelaunch-preload-gp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/group-policies/prelaunch-preload-gp.md)
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@roman-schraner - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@roman-schraner - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
