### ISSUE TITLE
Update video URL

### ISSUE THREAD

**Issue by kyjeeper** [MicrosoftDocs/windows-itpro-docs#2086]
The URL for a Secure Boot video is still pointing to https://technet.microsoft.com/windows/jj737995.aspx, which is no longer a valid link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c795c8ef-7caf-b8a7-4118-b00b1899eef8
* Version Independent ID: cd85b6b4-d160-0c44-15ea-4b7c02fbe0eb
* Content: [Secure the Windows 10 boot process](https://docs.microsoft.com/en-us/windows/security/information-protection/secure-the-windows-10-boot-process)
* Content Source: [windows/security/information-protection/secure-the-windows-10-boot-process.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/secure-the-windows-10-boot-process.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@kyjeeper Thanks for pointing that out. Unfortunately we don't have that video any longer, so I had to remove the link.
