### ISSUE TITLE
The "Important" note after Azure AD join

### ISSUE THREAD

**Issue by ferrety2006** [MicrosoftDocs/windows-itpro-docs#2092]
Is this accurate? " Important - If you join Surface Hub to Azure AD during first-run setup, single sign-on (SSO) for Office apps will not work properly. Users will have to sign in to each Office app individually."

This sounds like a bug - could it be confirmed that this is the intended behavior? Our current Surface Hubs are AD joined and the SSO makes for a very smooth experience. It seems very peculiar that it would be different for Azure AD joined hubs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77041701-3c1f-d1a7-51fe-c6f82ec52319
* Version Independent ID: 1d014d9d-6238-2b82-bde8-a8e88c3bd3fa
* Content: [First-run program (Surface Hub)](https://docs.microsoft.com/en-us/surface-hub/first-run-program-surface-hub#a-href-idsetup-adminsaset-up-admins-for-this-device-page)
* Content Source: [devices/surface-hub/first-run-program-surface-hub.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/first-run-program-surface-hub.md)
* Product: **surface-hub**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@ferrety2006 I checked with the product team, and they confirmed that the note is still accurate.

**Comment by jdeckerms** [comment]
@ferrety2006 I can't answer as to whether that's something that they're working on changing, or if it's by design, or if it's a technical limitation.

**Comment by ferrety2006** [comment]
Ok, thank you.
