### ISSUE TITLE
SQL Version support

### ISSUE THREAD

**Issue by RyanBijkerk** [MicrosoftDocs/windows-itpro-docs#2102]
Why is there only support for Microsoft SQL Server 2014 and not higher?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbe9b090-883b-ffce-5cc6-7ad4a21ad11c
* Version Independent ID: 14cd83b9-7568-8a3c-e262-3f322ea805c3
* Content: [App-V 5.1 Supported Configurations](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/appv-v5/app-v-51-supported-configurations)
* Content Source: [mdop/appv-v5/app-v-51-supported-configurations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/appv-v5/app-v-51-supported-configurations.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by illfated** [comment]
I would think that there could be unsupported features in the 2016 version (and newer)
and that there could be material in current databases which need those features.
See also https://docs.microsoft.com/en-us/sql/database-engine/install-windows/supported-version-and-edition-upgrades?view=sql-server-2017#unsupported-scenarios

**Comment by e0i** [comment]
@jamiejdt Could you clarify whether MS SQL versions above 2014 supported? We would like to follow-up with this issue and patch the document with relevant changes if necessary. Thanks.

**Comment by e0i** [comment]
@RyanBijkerk It seems that the issue has been addressed with the following commit and the document has been updated with the up-to-date support information.Thank you.

[[5931cb9 ] add new support for SQL server 2016 sp2 and SQL 2017 ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/5931cb9c89021511b9ffa642df213d6e7d3f3a25#diff-4861052cbba358aacf00fcf9caf7beca)

**Comment by illfated** [comment]
(commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/5931cb9c89021511b9ffa642df213d6e7d3f3a25)
(rich diff https://github.com/MicrosoftDocs/windows-itpro-docs/commit/5931cb9c89021511b9ffa642df213d6e7d3f3a25?short_path=4861052#diff-4861052cbba358aacf00fcf9caf7beca)
