### ISSUE TITLE
App-triggered VPNs on domain-members

### ISSUE THREAD

**Issue by 3ter** [MicrosoftDocs/windows-itpro-docs#2104]
The official book for the exam 70-741 states [something old (2013)](https://blogs.technet.microsoft.com/networking/2013/10/02/automatically-triggering-vpn-connections-and-vpn-diagnostics-enhancements-in-windows-8-1/):
> You cannot implement app-triggered VPNs on domain-member computers.

I'd like to know why :).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79add4e0-6997-5b15-542c-be3f1c2b1baf
* Version Independent ID: 47bd5f53-cd36-3205-42b1-6d99c68e9b39
* Content: [VPN profile options (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-profile-options)
* Content Source: [windows/security/identity-protection/vpn/vpn-profile-options.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/vpn/vpn-profile-options.md)
* Product: **w10**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by jdeckerms** [comment]
@3ter We welcome your feedback on the "VPN profile options" topic. For assistance with your question, I recommend the network forum for Windows 10 IT pros: https://social.technet.microsoft.com/Forums/en-US/home?forum=win10itpronetworking
