### ISSUE TITLE
EnableLUA=0 support statement

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/windows-itpro-docs#2106]
I miss here a clear support statement whether disabling UAC (EnableLUA=0) is actually not supported in Windows 10, as stated at https://blogs.msdn.microsoft.com/cjacks/2016/09/12/windows-10-app-compat-strategy/: "Disabling UAC on Windows 10 puts you into an untested and unsupported configuration"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 495688e2-ca8d-a005-19d2-5ee9138c86f2
* Version Independent ID: 760f236c-5eb0-00cd-9553-990f29ee5aa4
* Content: [How User Account Control works (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/how-user-account-control-works)
* Content Source: [windows/security/identity-protection/user-account-control/how-user-account-control-works.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/user-account-control/how-user-account-control-works.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by juanand** [comment]
Not really intended to disable UAC at all. Just seeking for a support statement on docs.microsoft.com to point customers to.
Thanks!

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@juanand - - Thank you for submitting this feedback.

From our understanding, the issue has been resolved based on the commit ([14cf506](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/14cf506a3f559d551e35389ac00723748a3b81f3#diff-0acfba9a515b38172a87fb67546f278e)) made by the author. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by jaayson** [comment]
>Warning: Universal Windows apps will not work when UAC is disabled.

It is not correct. Universal apps still work. Could you fix this?
