### ISSUE TITLE
Check UAC slider level

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/windows-itpro-docs#2107]
In the table, the "Check UAC slider level" row says "Never notify (Disable UAC)" but actually does not disables UAC, as described later. I would suggest saying "Never notify (Disable UAC prompts)".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 495688e2-ca8d-a005-19d2-5ee9138c86f2
* Version Independent ID: 760f236c-5eb0-00cd-9553-990f29ee5aa4
* Content: [How User Account Control works (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/how-user-account-control-works)
* Content Source: [windows/security/identity-protection/user-account-control/how-user-account-control-works.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/user-account-control/how-user-account-control-works.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@juanand great suggestion, this has been added.
