### ISSUE TITLE
data type

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#2108]
Please align to other style guides in 80% of all CSP guides? (remember this goes to a Global Audience)

A valid data point is published by Open Mobile Alliance (which Microsoft adopted MDM DM client formats from) as:

String
String (XML file)
Date and time
Integer
Floating point
Boolean
Base64 (file)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 167fe82b-002b-39a5-ffc4-e77e10e23302
* Version Independent ID: 6d416711-11b7-8231-0ced-343cbd7103f1
* Content: [SurfaceHub CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/surfacehub-csp)
* Content Source: [windows/client-management/mdm/surfacehub-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/surfacehub-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Tdiwestyguy - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Tdiwestyguy - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
