### ISSUE TITLE
Add to Private Store choice missing

### ISSUE THREAD

**Issue by mohitvij** [MicrosoftDocs/windows-itpro-docs#2109]
The store does not anymore has a Refine Results choice by License Type and ellipses against product do not provide a choice to add to Private store only to Add users. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01694043-55c6-fb74-c098-bee64eee69fa
* Version Independent ID: 45a58135-7f59-b5d9-fa28-ad3e9a8d3a01
* Content: [Distribute apps using your private store (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/distribute-apps-from-your-private-store)
* Content Source: [store-for-business/distribute-apps-from-your-private-store.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/distribute-apps-from-your-private-store.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by madhuramehendalewhatfix** [comment]
Is there a way to add an an app which is accessible only through direct link to the private store. If yes. how can this be achieved?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@mohitvij - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@mohitvij - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
