### ISSUE TITLE
Intune Connector Function

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/windows-itpro-docs#2110]
So devices need to be on the corporate LAN and able to ping a DC in order to Hybrid AAD Join? I had the impression that the Intune Connector was going to act like an app proxy of sorts and allow AD Join over the Internet. Too bad, that would have been pretty slick.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12823601-7426-a768-e72f-866b150baccd
* Version Independent ID: c1f993e3-a405-6860-8ab1-7b3d387b4631
* Content: [Hybrid AAD Join](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/user-driven-hybrid)
* Content Source: [windows/deployment/windows-autopilot/user-driven-hybrid.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/user-driven-hybrid.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by SolidKnight** [comment]
I assumed the same before reading this article. So now the question is, what happens when the device can't talk to the Domain Controller? Does it impede setup or does it move forward anyway?

**Comment by pyoungberg** [comment]
@SolidKnight In my experience it fails OOBE after 10 or so minutes but leaves the device AAD joined, no Intune. Cleanup is annoying. Works great when on the domain of course.

**Comment by byrusrikar** [comment]
I also assumed the same, I had raised the ticket with Microsoft on the same .. they have mentioned the Device should be in the Corp LAN for the machine to get connected to the Domain Controller.
Waiting for the VPN service which connects before OOBE.

**Comment by MariusWeiss** [comment]
I also don't understand that in a technical way. So, I assume that the Device connect to Intune. Intune establish a connection to the Intune Connector for Active Directory. This Connector creates a Device in the Active Directory. It uses the Offline Join Command Line Tool (djoin.exe), which will create an answer Blob-File. After that, the Blob-File will be sent to the Intune Cloud, via the Connector. Now the Client will download the Blob-File and use it to do the Domain Join. Why does this feature require AD Network connection? Is it because it's still in preview?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@pyoungberg - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@pyoungberg Thank you for your feedback on the doc. As of now for Hybrid AD join the machine should be on the corporate network. The mechanism you have mentioned totally makes sense and I would suggest you forward your feedback using feature request channel.

@mypil Can you please guide @pyoungberg how he can put a feature request.

Thanks.

**Comment by mypil** [comment]
@pyoungberg - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**

You might find others have made a similar request that you can add to, or you can open a new one.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
