### ISSUE TITLE
Requirements for Hybrid AAD Join

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/windows-itpro-docs#2111]
Please add the resources Hybrid AAD join needs to work as well, thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aafc065-6ee6-e3cf-31ba-ab3dd277fb23
* Version Independent ID: 35d3102e-4ff7-9408-8dbd-513b7dfff5c0
* Content: [Windows Autopilot networking requirements](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-requirements-network)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-requirements-network.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-autopilot-requirements-network.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by fergusstrachan** [comment]
I second this. In an environment with 802.1x, you need to create a separate secured VLAN for Autopilot deployment - it would be handy to have a definitive list of internet hosts they need to contact so we can lock this VLAN down accordingly.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@pyoungberg @fergusstrachan - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@pyoungberg - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
