### ISSUE TITLE
Hard Admin for IE

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/windows-itpro-docs#2112]
For those that have Hard Admin turned on for IE, you'll need to turn it off to get the Intune Connector to register. I turned it back on after it registered and haven't seen any issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e236055e-0b59-8a2e-ef79-1affb1bffcf2
* Version Independent ID: 79c51731-3159-6600-0f08-3ac3395c0e67
* Content: [Intune Connector (preview) requirements](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/intune-connector)
* Content Source: [windows/deployment/windows-autopilot/intune-connector.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/intune-connector.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by obrienstat** [comment]
Ahh thanks a lot. Took me two weeks to find this answer

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@pyoungberg - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @pyoungberg,
the issue you are talking about is out of scope of this article (this article is about language requirements, issue you have noted is about  Internet Explorer Enhanced Security Configuration), it is more related to [Deploy hybrid Azure AD-joined devices by using Intune and Windows Autopilot](https://docs.microsoft.com/en-us/intune/windows-autopilot-hybrid) article, and here it has been already noted:
"By default Windows Server has Internet Explorer Enhanced Security Configuration turned on. If you are unable to sign in to the Intune Connector for Active Directory then turn off IE Enhanced Security Configuration for the Administrator."

So I think no change is required in this article.

What do you think?

Thank you

**Comment by mypil** [comment]
@pyoungberg - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
