### ISSUE TITLE
BitLocker during OOBE

### ISSUE THREAD

**Issue by akmatthewsuk** [MicrosoftDocs/windows-itpro-docs#2117]
Please can a link with implementation documentation be added to the section "Delivering BitLocker policy to AutoPilot devices during OOBE". I have tried to implement this behavior and have been unable to set BitLocker policy during OOBE.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d6356b-87ff-8c3a-56ef-1270a823d3ab
* Version Independent ID: 4d6ae878-66cf-0e10-bdf3-bdd6054cbc9d
* Content: [What's new in Windows 10, version 1809](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809#security-improvements)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1809.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1809.md)
* Product: **w10**
* GitHub Login: @dawnwood
* Microsoft Alias: **trudyha**

**Comment by Justinha** [comment]
@akmatthewsuk I think another writer is planning to add this to the AutoPilot docs. In the meantime, does this blog post help? https://blogs.technet.microsoft.com/showmewindows/2018/01/18/how-to-enable-bitlocker-and-escrow-the-keys-to-azure-ad-when-using-autopilot-for-standard-users/

**Comment by akmatthewsuk** [comment]
Thanks. Some guidance would be helpful.

I have tried the settings in that blog post. And I have a Microsoft Support Call in progress. We will get this working somehow.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Justinha - Do you have any updates on the progress status of this issue?

Thanks.

**Comment by Justinha** [comment]
@mypil sorry, no updates. I'll follow up with new doc owners to get some traction.

**Comment by greg-lindsay** [comment]
https://docs.microsoft.com/windows/deployment/windows-autopilot/Bitlocker is the current topic in the Autopilot docs

**Comment by mypil** [comment]
@akmatthewsuk - Thank you for submitting feedback.

From our understanding, the issue has been answered by greg-lindsay. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
