### ISSUE TITLE
Clarification on update approval process

### ISSUE THREAD

**Issue by RichardB-22** [MicrosoftDocs/windows-itpro-docs#2118]
What I would like to see in this documentation is clear information that will answer this question: "If a client is configured with WSUS as described, will they then only ever receive feature updates that have been approved in WSUS?"

What I'm trying to determine is the possibility of, for example, remaining on 1709 for an indefinite amount of time for a deployment ring. I assume this would be possible by simply not approving any newer feature updates for that group of computers. However, there has been confusion in my organization as to whether machines will still automatically "check for updates directly from Microsoft" and install newer feature updates even when configured to use WSUS. This confusion has led to us resorting to the use of the LTSB edition of Windows 10 for a linked-clone VM pool of machines, but I would like to think that isn't actually necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe35c19c-fd29-8405-ad9f-441204812e6b
* Version Independent ID: fc0fe6ce-4b92-3cff-d6fa-c791ba2df466
* Content: [Deploy Windows 10 updates using Windows Server Update Services (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-manage-updates-wsus)
* Content Source: [windows/deployment/update/waas-manage-updates-wsus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-manage-updates-wsus.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@RichardB-22 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @RichardB-22 , Thank you for your query. You can manage Windows 10 features updates using WSUS server. Make sure you have WSUS 4.0 installed. This information is already available in the document. Please see https://docs.microsoft.com/en-us/windows/deployment/update/waas-manage-updates-wsus#requirements-for-windows-10-servicing-with-wsus

Thanks.

**Comment by mypil** [comment]
@RichardB-22 - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
