### ISSUE TITLE
Windows Security Missing from group policy

### ISSUE THREAD

**Issue by robp2175** [MicrosoftDocs/windows-itpro-docs#2122]
I download the adm templates from here and Windows Security is still missing.
https://www.microsoft.com/en-us/download/confirmation.aspx?id=56880

Where is this template?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65d57fa8-9c9b-63cc-7248-175242963432
* Version Independent ID: 9cd96c93-8f46-64db-a162-02da1e1f63cc
* Content: [Hide notifications from the Windows Security app](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications)
* Content Source: [windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by andreabichsel** [comment]
I think this is what you're looking for: https://blogs.technet.microsoft.com/secguide/2018/04/30/security-baseline-for-windows-10-april-2018-update-v1803-final/.
