### ISSUE TITLE
Disable Upgrade Readiness

### ISSUE THREAD

**Issue by ahcash** [MicrosoftDocs/windows-itpro-docs#2126]
OMS is deprecated.  Where can I disable Upgrade Readiness in the Azure Portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f20e3377-fdbc-ac87-239e-7184db24a685
* Version Independent ID: 0464da82-efa4-b147-bba9-d6802cf9d273
* Content: [Frequently asked questions and troubleshooting Windows Analytics](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-faq-troubleshooting#disable-upgrade-readiness)
* Content Source: [windows/deployment/update/windows-analytics-FAQ-troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-FAQ-troubleshooting.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
I'll work on an update for this topic; in the meantime, see https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-azure-portal

**Comment by jaimeo** [comment]
Also: https://docs.microsoft.com/en-us/azure/monitoring/monitoring-solutions#remove-a-management-solution

**Comment by e0i** [comment]
@ahcash It seems that your question has been answered by the community.

Note that the feedback section is intended for product documentation issues only.

Thus, should you have any further issues similar to this one, please consider opening a *product support* ticket here: [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you for feedback.

**Comment by e0i** [comment]
@AndreaBarr _Recommended closure_
