### ISSUE TITLE
Images, Descriptions, links

### ISSUE THREAD

**Issue by visions** [MicrosoftDocs/windows-itpro-docs#2127]
It would be helpful if you included images of what it looks like when you are carrying out various operations, with descriptions.  It would also be helpful if you provided links to descriptions or tutorials of how related features for example how to use a smart card with bitlocker to go.  etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae820097-c400-ff49-f28e-b784adfbf86a
* Version Independent ID: 5a5cf946-28ce-6ccd-a5cf-31c4fd09585f
* Content: [BitLocker To Go FAQ (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-to-go-faq)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-to-go-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-to-go-faq.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@visions - thank you for submitting feedback.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
