### ISSUE TITLE
Naming is confusing

### ISSUE THREAD

**Issue by Diagg** [MicrosoftDocs/windows-itpro-docs#2128]
Speaking of "LTSC feature updates" is just to much confusing. Something like "Next LTSC release" would be far more understandable. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93a89143-38dd-8bf0-d863-0edddc5b5c41
* Version Independent ID: 38bd4ff1-85dc-51ba-4ee7-243e131ac625
* Content: [Best practices and recommendations for deploying Windows 10 Feature updates to mission critical devices](https://docs.microsoft.com/en-us/windows/deployment/update/feature-update-mission-critical)
* Content Source: [windows/deployment/update/feature-update-mission-critical.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/feature-update-mission-critical.md)
* Product: **w10**
* GitHub Login: @MCureton
* Microsoft Alias: **mikecure**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Diagg- Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Diagg - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
