### ISSUE TITLE
Two CSP does not work

### ISSUE THREAD

**Issue by DeployWindowsCom** [MicrosoftDocs/windows-itpro-docs#2129]
The following CSP does not work in Windows 10 1809
System/AllowDeviceNameInDiagnosticData
System/ConfigureTelemetryOptInChangeNotification
Tried with some different naming and capitals, but the settings does not apply

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c833e5b-0fcf-2ace-a90a-3270286d23a9
* Version Independent ID: 64afbc38-e7cc-fc14-9d57-1cd119b2395d
* Content: [Policy CSP - System](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-system#system-configuretelemetryoptinchangenotification)
* Content Source: [windows/client-management/mdm/policy-csp-system.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-system.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by DeployWindowsCom** [comment]
I was to quick, it should be Windows 10 1803, with latest monthly updates.

**Comment by okieselbach** [comment]
AllowDeviceNameInDiagnisticData is working with 1809 see here: https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-system#system-allowdevicenameindiagnosticdata
but!
System/ConfigureTelemetryOptInChangeNotification isn't working for me either!
the admx backed policy maps to HKLM\Software\Policies\Microsoft\Windows\DataCollection\DisableTelemetryOptInChangeNotification=1 but I can't see any key created after applying the MDM policy. There policy itself is applied successful and creates an entry under HKLM\Software\Microsoft\PolicyManager\current\device\System\ConfigureTelemetryOptInChangeNotification = 1 (REG_DWORD) but not the corresponding key under HKLM\Software\Policies\Microsoft\Windows\DataCollection\DisableTelemetryOptInChangeNotification and therefore the ToastNotification is still displayed!

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@DeployWindowsCom - Thank you for submitting this feedback.

From our understanding, the issue you raised has been answered by okieselbach. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
