### ISSUE TITLE
Need Clarity - Restricted SAM not working how we expect.

### ISSUE THREAD

**Issue by brink668** [MicrosoftDocs/windows-itpro-docs#2130]
Would you please source some examples for both Domain Controller Hardening as well as for Password Management Solutions in which we want to restrict access to certain "Local SAM Databases" to a specific contoso\service_account from reading from the SAM Database.  (I reviewed the SAMRi10 Tool).

**Expected Working Steps**
--Enable Restricted SAM on Member Server (non domain controller) Server 2016
--Enable Restricted SAM for Local Group "Remote SAM Access Users" and SDDL Permissions
----Local Group "Remote SAM Access Users" contains domain account contoso\service_account

**Actual Working Steps**
For example in our testing setup.
--Enable Restricted SAM on Member Server (non domain controller) Server 2016
--Enable Restricted SAM for Local Group "Remote SAM Access Users" and SDDL Permissions
----Local Group "Remote SAM Access Users" contains domain account contoso\service_account
----Local Group "Remote SAM Access Users" contains local account “Administrator, Guest”

Based on the documentation we would think this would work.  However, we seem to be getting access denied unless we add the local user accounts to the local group we created above as well "Remote SAM Access Users".  Such as including "Administrator, local_account_1" etc..

In our testing we are seeing that the documentation seems to contradict what we are trying to accomplish.  Only when we also add local users to the local group with the inclusion of the domain\service account does it work.

Edited: with Expected vs Actual for clarity purposes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef8b6967-0e45-bcdd-6d70-54759d9f7ec8
* Version Independent ID: 6651ebc1-04f0-421f-891b-6957ca37da7c
* Content: [Network access - Restrict clients allowed to make remote calls to SAM](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@brink668 Thanks for raising this. I have forwarded your question and request for an example to our support engineers who helped write this topic, and I'll add anything they can suggest. But this is a complex policy setting and more info about your environment will be needed to help troubleshoot. For example, what OS versions, which corresponding hotfixes are installed (if any). Then after enabling audit mode, interpreting the script output of the audit events, and refining/editing the policy values based on that output is also really hard. To get the best experts to help in this case, please contact Microsoft Customer Support, and you might also need to request help from an escalation engineer.

**Comment by brink668** [comment]
Completely understand.  Thank you for your efforts.

**Comment by SquirrelAssassin** [comment]
After enabling the rule, full of the errors below.  How can we find out the ips of the 858 remote calls so we can start to troubleshoot?

858 remote calls to the SAM database have been denied in the past 900 seconds throttling window.
For more information please see http://go.microsoft.com/fwlink/?LinkId=787651.

**Comment by Justinha** [comment]
@SquirrelAssassin this is covered in the Policy Management section. You'll want to set Audit mode and then parse then related events. But that is a complex task in itself. For the best help with this setting, please open a case with Microsoft Customer Support.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@brink668 -Thank you for submitting this feedback.

From our understanding, the issue you raised has been answered by Justinha. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by SquirrelAssassin** [comment]
We opened a premier supper ticket on this as the logs do not show us where the errors originate from.  Will post after resolution.

**Comment by mypil** [comment]
@SquirrelAssassin - Do you have any updates? Could you please assist us by suggesting how this content could be edited to incorporate your feedback? If you could suggest what the appropriate text and where it should be placed, I could assign one of our team members to create a Pull Request to get it added or you may also create a Pull Request to add in your suggestion and just link this issue so I can have the doc owner review and merge the content. Thank you.

**Comment by mypil** [comment]
@SquirrelAssassin - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to open a new issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
