### ISSUE TITLE
Windows Updates

### ISSUE THREAD

**Issue by bally-singh** [MicrosoftDocs/windows-itpro-docs#2131]
Hi,

I am using Windows Update for Business and it appears that the service: "Microsoft Account Sign-in Assistant" - Service Name: wlidsvc is required for Windows Updates.

If this is not enabled I get the error message: 0x8024002e

This has also been posted here:

https://social.technet.microsoft.com/Forums/en-US/437b178a-b164-44ca-9ad4-7cfb297dd303/windows-update-issue-0x80070426?forum=win10itprogeneral

Any advice on why this would be the case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4cc6a1f-7cdf-22cd-4b26-b5535de7cae6
* Version Independent ID: 5b2cf033-52ba-651f-5ad9-1d9fa97b21a5
* Content: [Accounts Block Microsoft accounts (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/accounts-block-microsoft-accounts)
* Content Source: [windows/security/threat-protection/security-policy-settings/accounts-block-microsoft-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/accounts-block-microsoft-accounts.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@bally-singh  - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
