### ISSUE TITLE
ok button missing from 

### ISSUE THREAD

**Issue by Grinstb** [MicrosoftDocs/windows-itpro-docs#2133]
Step 4 the ok button does not show

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccbd089d-9353-2f74-08b4-f404e2f4a615
* Version Independent ID: c2ddd8b8-3d78-5203-2e60-f83970e9bc79
* Content: [Manage access to private store (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/manage-access-to-private-store)
* Content Source: [store-for-business/manage-access-to-private-store.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/manage-access-to-private-store.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Grinstb  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @Grinstb , each policy setting has a section at the bottom with "OK", "apply" and "cancel" buttons
![image](https://user-images.githubusercontent.com/48041687/59148009-12c30980-8a1c-11e9-9f1d-d6b0ec949650.png)
Thank you

**Comment by mypil** [comment]
@Grinstb - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by Grinstb** [comment]
This had nothing to do with the original notice, GP is a completely different product then the Web Store for Education

**Comment by MaratMussabekov** [comment]
Dear @Grinstb ,
could you please clarify, which "Step 4" you are talking about?
Thank you
