### ISSUE TITLE
Hardware requirements?

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/windows-itpro-docs#2135]
Are there any hardware requirements for AutoPilot, short of being able to run Windows 10?  Any TPM or UEFI requirements? I haven't seen anything on the above in this documentation (maybe I'm just missing it). Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc999894-2a0a-bc87-7fd7-97df5f1fd04e
* Version Independent ID: ad68f62a-6bf0-5f5f-bb07-f64afe68fd10
* Content: [Windows Autopilot requirements](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-requirements)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-autopilot-requirements.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by Tech-CF** [comment]
The line above states "There are no additional hardware requirements to use Windows 10 Autopilot, beyond the requirements to run Windows 10."

**Comment by illfated** [comment]
Looks like the document was last updated 12/13/2018 (December 13 2018), so it could have been added after this issue was opened.

**Comment by thedrum808** [comment]
@illfated is correct - that line was added after my question, but the comment was never closed. All good now. Thanks!

**Comment by illfated** [comment]
@thedrum808 : Feel free to close this issue, if you can (or any MS team member).

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@thedrum808 - Based on the comment, we will proceed to close this issue. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
