### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by yamanyon** [MicrosoftDocs/windows-itpro-docs#2138]
> Windows 10, version 1703 or 1607 with the April 2017 cumulative update.

In this way of writing it has been translated as follows in the Japanese version.
"Version 1703 or 1607 Windows 10 with the April 2017 cumulative update"

Please describe as follows so that translation will not fail.
ex. "Windows 10 Version 1703 or later, and Windows 10 Version 1607 with the April 2017 cumulative update."

**Comment by yamanyon** [comment]
https://docs.microsoft.com/en-us/windows/deployment/update/waas-optimize-windows-10-updates
The target document is this.

**Comment by jdeckerms** [comment]
@yamanyon Thanks, we'll get it fixed. Anytime you find errors like that, we encourage you to fix them directly! Start by clicking "edit" in the upper right of the topic. For instructions, see https://docs.microsoft.com/en-us/contribute/
