### ISSUE TITLE
Can't disable Credential Guard

### ISSUE THREAD

**Issue by tomneko** [MicrosoftDocs/windows-itpro-docs#2141]
・グループポリシー設定から無効
・指定のレジストリエントリをすべて削除
・bcdeditの一連のコマンドを実行（管理者権限CMDへコピペ）
・再起動

システム情報で確認すると実行中、変化なし・・・

あと何か、やるべきことはあるでしょうか？

---

OS 名	Microsoft Windows 10 Pro
バージョン	10.0.17134 ビルド 17134
OS の他の説明 	利用不可
OS 製造元	Microsoft Corporation
システム名	POTESI-1
システム製造元	BIOSTAR Group
システムモデル	TB350-BTC
システムの種類	x64-ベース PC
システム SKU	None
プロセッサ	AMD Ryzen 7 2700 Eight-Core Processor、3200 Mhz、8 個のコア、16 個のロジカル プロセッサ
BIOS バージョン/日付	American Megatrends Inc. 5.13, 2018/04/17
SMBIOS バージョン	3.1
埋め込みコントローラーのバージョン	255.255
BIOS モード	UEFI
BaseBoard メーカー	BIOSTAR Group
BaseBoard モデル	利用不可
BaseBoard 名	ベース ボード
プラットフォームの役割	デスクトップ
セキュア ブートの状態	無効
PCR7 構成	表示するためには昇格が必要です
Windows ディレクトリ	C:\WINDOWS
システム ディレクトリ	C:\WINDOWS\system32
ブート デバイス	\Device\HarddiskVolume4
ロケール	日本
ハードウェア アブストラクション レイヤー	バージョン = "10.0.17134.285"
ユーザー名	利用不可
タイム ゾーン	東京 (標準時)
インストール済みの物理メモリ (RAM)	16.0 GB
合計物理メモリ	16.0 GB
利用可能な物理メモリ	10.3 GB
合計仮想メモリ	18.3 GB
利用可能な仮想メモリ	9.66 GB
ページ ファイルの空き容量	2.38 GB
ページ ファイル	C:\pagefile.sys
カーネル DMA 保護	無効
仮想化ベースのセキュリティ	実行中
仮想化ベースのセキュリティの必須セキュリティ プロパティ	
仮想化ベースのセキュリティの利用可能なセキュリティ プロパティ	仮想化の基本サポート, DMA 保護, UEFI コード読み取り専用, SMM Security Mitigations 1.0
仮想化ベースのセキュリティの構成済みサービス	
仮想化ベースのセキュリティの実行中サービス	
デバイス暗号化のサポート	表示するためには昇格が必要です
ハイパーバイザーが検出されました。Hyper-V に必要な機能は表示されません。	

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Windows Defender Credential Guard の管理 (Windows 10)](https://docs.microsoft.com/ja-jp/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by MadIceTea** [comment]
英語なのですが、#2612でOFFにする方法があります。

それと一緒に、僕は「Turn Windows Features On or Off」で「Windows Defender Application Guard」をOFFにしました。

**Comment by Justinha** [comment]
I'm not fully sure why Credential Guard was not disabled in this case, but it is unnecessary to disable Application Guard in order to disable Credential Guard. They don't have any dependency on each other.
