### ISSUE TITLE
Missing Option for Start Menu height, limited ColumnCount

### ISSUE THREAD

**Issue by JimiDC** [MicrosoftDocs/windows-itpro-docs#2142]
Why is it not possible to set the height for the startmenu? Users are able to adjust the height for themselves and their userprofiles and when reapplying the menu via policy it gets shrinked again to the default height and all ApplicationGroups are scrambled :-(

Furthermore why is it only possible to define StartTileGroupsColumnCount attribute "1" or "2" and not more? Again the same issue when users increase their menu for lets say "3" and the policy get reapplied everything is scrambled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 061157dc-8fc8-3f9d-c01f-37f22fbdf1c7
* Version Independent ID: 0b0b6797-9367-eb7c-22ef-5f2b8bbfe592
* Content: [Start layout XML for desktop editions of Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/start-layout-xml-desktop)
* Content Source: [windows/configuration/start-layout-xml-desktop.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/start-layout-xml-desktop.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@JimiDC The documentation only describes what's supported. To give feedback on things you'd like to be different (such as column count and height), please submit your comments in the Feedback Hub.
