### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by Ronald-den-Os** [MicrosoftDocs/windows-itpro-docs#2143]
In the Configure a Production Public Key Infrastructure Section review is says: "Root certifcate authority certificate (Azure AD Joined devices)". Should be: "Root certificate authority certificate (Azure AD Joined devices)"

In the Azure MFA via ADFS Section Review it says: "Configure Azure Multufactor Authentiation features and settings". Should be: "Configure Azure Multifactor Authentication features and settings."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4784e8f-6d35-78d8-9160-7b39832a58d8
* Version Independent ID: 7f79559a-3a6d-473b-1ec1-66746c461318
* Content: [Windows Hello for Business Key Trust New Installation (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by Ronald-den-Os** [comment]
In tthe first lightblue box ist says: "Install the root certificate authority certificate for your organization in the user's trusted root **certifcate** store". Should be"Install the root certificate authority certificate for your organization in the user's trusted root **certificate** store."

**Comment by jdeckerms** [comment]
@Ronald-den-Os Thanks, we'll get it fixed. Anytime you find errors like that, we encourage you to fix them directly! Start by clicking "edit" in the upper right of the topic. For instructions, see https://docs.microsoft.com/en-us/contribute/
