### ISSUE TITLE
Typo in second header

### ISSUE THREAD

**Issue by Ronald-den-Os** [MicrosoftDocs/windows-itpro-docs#2144]
"Directory Syncrhonization" should be "Directory Synchronization"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdb237b7-6181-5638-8e9a-fa52fe5327d5
* Version Independent ID: 27b14b20-65f1-302a-cd74-3c1443d8a863
* Content: [Configuring Hybrid key trust Windows Hello for Business - Directory Synchronization](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-dir-sync)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-dir-sync.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-dir-sync.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by jdeckerms** [comment]
@Ronald-den-Os Thanks, we'll get it fixed. Anytime you find errors like that, we encourage you to fix them directly! Start by clicking "edit" in the upper right of the topic. For instructions, see https://docs.microsoft.com/en-us/contribute/
