### ISSUE TITLE
Windows 10, version 1809 missing

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/windows-itpro-docs#2145]
Hello.  Looking for 1809 to be called out as that is required for Windows Pro is my understanding to be used with Bitlocker.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93249da9-5a31-9936-9339-3d41126b2cb3
* Version Independent ID: f5ea9ba0-51f9-fff0-cefc-57f36b862039
* Content: [Policy CSP - Bitlocker](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-bitlocker)
* Content Source: [windows/client-management/mdm/policy-csp-bitlocker.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-bitlocker.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@adrianwells - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by adrianwells** [comment]
@mypil it looks like the footnote references remain by their references are no longer part of the document which is confusing. Will those be reviewed as well?

**Comment by MaratMussabekov** [comment]
Dear @adrianwells ,
**Hello. Looking for 1809 to be called out as that is required for Windows Pro is my understanding to be used with Bitlocker.** - this article is dedicated to Policy CSP, to read about the updates in Bitlocker CSP (including support of Windows PRO) please check [BitLocker CSP](https://docs.microsoft.com/windows/client-management/mdm/bitlocker-csp) article.
Thank you

**Comment by mypil** [comment]
@adrianwells - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@MaratMussabekov - please check if you can add the suggestion from @adrianwells  into the PR you created or please respond to this query. Thanks.

**Comment by MaratMussabekov** [comment]
Dear @adrianwells, I totally agree, there should be link to the Bitlocker CSP, I have added it to the PR
Thank you

**Comment by mypil** [comment]
@adrianwells - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by adrianwells** [comment]
@mypil , yes this looks completed so closing this issue. Thank you.
