### ISSUE TITLE
The 1803 update removes XPS Viewer from earlier Win10's

### ISSUE THREAD

**Issue by ShortOrderCookie** [MicrosoftDocs/windows-itpro-docs#2146]
This statement above regarding the XPS Viewer is not correct:  " If you have XPS Viewer and you update to Windows 10, version 1803, there's no action required. You'll still have XPS Viewer. "

We are rolling out the 1803 update in our environ.  The 1803 update removes the XPS Viewer from all previous Win10 versions.  We've seen this on 1511, 1607, 1703, and 1709 that have received the 1803 update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c274f8df-31da-f58a-36af-dc7eb6ace762
* Version Independent ID: 0e33637d-e094-edbc-04f9-e8d5e6c642c6
* Content: [Windows 10, version 1803 - Features that have been removed](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-1803-removed-features)
* Content Source: [windows/deployment/planning/windows-10-1803-removed-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-10-1803-removed-features.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@ShortOrderCookie 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
