### ISSUE TITLE
Bitlocker Turned Off, can't access BIOS

### ISSUE THREAD

**Issue by dougholtz** [MicrosoftDocs/windows-itpro-docs#2154]
Hope someone has an answer to this issue.  I wanted to put in a new SSD drive in my laptop.  The existing conventional drive was encrypted with bitlocker.  Originally the drive had Windows 7 Pro 64 bit; I upgraded to W10 during the free conversion dates.  To keep the old drive as a backup, I turned off bitlocker.  There was an error of some kind, asking for recovery key after it was decrypted.  I turned off the machine before finding that key.  I can't get into the BIOS to change to UEFI, etc. (if there even is this setting).  I can't install the new SSD because Western Digital says there is a setting in BIOS blocking the capability to find the driver (AHCI). It's an older Toshiba Tecra A11.  Toshiba says I have to take it to a Toshiba repair center. I didn't want to "short out" the CMOS, just in case the laptop would never boot again.  I flashed the BIOS to a previous version, which didn't help; I re-flashed the BIOS to the current version, which also didn't help. Any suggestions?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b00e133-662e-d11d-1b0e-c318b21f28f8
* Version Independent ID: 84574a8c-67e6-97bd-9dbf-11252997bc93
* Content: [BitLocker frequently asked questions (FAQ) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-frequently-asked-questions)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-frequently-asked-questions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-frequently-asked-questions.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by andreabichsel** [comment]
It would be best for you to either contact your Toshiba repair center or to try https://support.microsoft.com. Thank you!
