### ISSUE TITLE
Clarify SIEM REST API documentation

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#2159]
Under the **Request parameters** section it says _"Use optional query parameters to specify and control the amount of data returned in a response. If you call this method without parameters, the response contains all the alerts in your organization."_ If you read later on in the table for the sinceTimeUtc parameter it says _"NOTE: When not specified, all alerts generated in the last two hours are retrieved."_ 

The intro text misleading. I recommend it be changed to say _"If you call this method without parameters, the response contains all the alerts in your organization generated in the last two hours."_

Also there's a difference between what the API returns and what is displayed in the WDSC UI. The UI rolls up "duplicate" alerts and instead just updates the first seen/last seen times on one alert. The API will return all those individual alerts. Users who don't realize this behavior may think something is either wrong with the API or the WDSC UI. I'm not sure how to say it, but you might want to add clarification text to this page that the number of alerts returned by API may not be the same as what is displayed in WDSC due to WDSC alert roll up behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b835bf35-1614-2d8d-13ab-176c6d839047
* Version Independent ID: ed4653f3-e393-dd42-5960-87888c08ba40
* Content: [Pull Windows Defender ATP alerts using REST API](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/pull-alerts-using-rest-api-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/pull-alerts-using-rest-api-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/pull-alerts-using-rest-api-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Hi iadgovuser1, 
Thank you for your feedback.
There are different notes for each parameter, so modifying the intro might not apply for all parameters.

For the second comment, there's a note added in the introductory section: 

_Windows Defender Security Center merges similar alert detections into a single alert. This API pulls alert detections in its raw form based on the query parameters you set, enabling you to apply your own grouping and filtering._

**Comment by iadgovuser1** [comment]
@mjcaparas 

At a minimum remove "If you call this method without parameters, the response contains all the alerts in your organization." because it is wrong. That is not the default behavior when no parameters are specified.

**Comment by Ludwig1770** [comment]
A couple of issues in the code snippet:

AuthenticationContext context = new AuthenticationContext(string.Format("https://login.windows.net/{0}/oauth2", tenantId));
ClientCredential clientCredentials = new ClientCredential(clientId, clientSecret);
AuthenticationResult authenticationResult  = context.AcquireToken(resource, clientCredentials);

The AuthenticationContext.AcquireToken doesn't seem to exist any more - been replaced by AcquireTokenAsync it seems.
Also it would be useful to know what type "resource" is in the deprecated method.

thanks

**Comment by iadgovuser1** [comment]
@Ludwig1770 I ran into a similar issues. I think the issue depends on which version of Microsoft.IdentityModel.Clients.ActiveDirectory.dll and Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll that you have installed. I ended up doing everything in pure PowerShell with Invoke-WebRequest to avoid that problem.

**Comment by Ludwig1770** [comment]
Thanks @iadgovuser1; moved this discussion to a new comment on the originating documentation page rather than appending to an unrelated and closed issue.

Basically if there are going to be incompatible changes in APIs, the documentation should cite the versions required for the code snippet to work (the originating page seems to have been created in mid-November 2018 so not very long ago).
