### ISSUE TITLE
phật giáo toàn cầu

### ISSUE THREAD

**Issue by tethiendaithanh** [MicrosoftDocs/windows-itpro-docs#2162]
tạo ra nhân loại mới.siêu độ chúng sinh đi sư ông

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83582e61-22b0-fb99-43c7-65a6694affef
* Version Independent ID: 61cc2546-2074-08b2-a6ed-e73da4825bfd
* Content: [Overview of Windows Autopilot](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-autopilot.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by andreabichsel** [comment]
Our apologies, are you able to state your question in English, please? Thank you!
