### ISSUE TITLE
Data Formats?

### ISSUE THREAD

**Issue by BigIve** [MicrosoftDocs/windows-itpro-docs#2165]
I would like to know where we can find information on the data formats for these policies.
e.g. NetworkAccess_DoNotAllowAnonymousEnumerationOfSamAccountsAndShares
Is it an integer?  A string?  How do we find this out?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 773b74b2-7dc2-d0e5-1e3b-bd6445bceda4
* Version Independent ID: 34b55057-9078-6bd0-a9ac-2f6403b84be7
* Content: [Policy CSP - LocalPoliciesSecurityOptions](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions#localpoliciessecurityoptions-networkaccess-donotallowanonymousenumerationofsamaccountsandshares)
* Content Source: [windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@BigIve 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by BigIve** [comment]
@e0i,
This is a documentation question.  Or a lack thereof.  Because if the required documentation was in place I wouldn't need to be asking the question would I?  In general, the documentation for Intune based policies by Microsoft is horrendous, and I find it very annoying each time this is raised Microsoft does it's level best to avoid the questions.  The number of support tickets that are required to be raised to get to speak to someone who can provide basic formatting information for a published CSP is just ridiculous.  Looks like this repository is heading down the same useless path.
Thanks for your "help" with my question.

**Comment by Mike-Crowley** [comment]
Per secpol.msc the InteractiveLogon_MachineInactivityLimit integer should be supplied in seconds. Please update your documentation accordingly.

**Comment by MaratMussabekov** [comment]
Hello @BigIve 
**I would like to know where we can find information on the data formats for these policies.** - it is available [here](https://docs.microsoft.com/windows/client-management/mdm/policy-ddf-file)
**e.g. NetworkAccess_DoNotAllowAnonymousEnumerationOfSamAccountsAndShares Is it an integer? A string? How do we find this out?** - it is integer, you can see it in the "DFFormat" section in the article I provided above.

I will add the note to the original article and add the link.

Thank you

**Comment by e0i** [comment]
@BigIve 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
