### ISSUE TITLE
No SCCM client

### ISSUE THREAD

**Issue by rstenborg** [MicrosoftDocs/windows-itpro-docs#2170]
Is it possible to do this without installing the SCCM agent? We dont want to install the client since we are going full cloud (no co-mgmt). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17bfe927-f7b7-608b-8537-5c2274ccdced
* Version Independent ID: 5dd9abca-92d9-fbb2-6796-d1f6b9ab3c8b
* Content: [Windows Autopilot for existing devices](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/existing-devices#feedback)
* Content Source: [windows/deployment/windows-autopilot/existing-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/existing-devices.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by kbaker827** [comment]
I also would love to know the answer to this one?

**Comment by illfated** [comment]
I wouldn't get my hopes up for a positive answer to this question. Prerequisites (https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/existing-devices#prerequisites ) pretty much excludes any scenario without SCCM. I also have tried finding documentation elsewhere (regular internet searches), but all of them seem to describe how to use Windows Autopilot in tandem with SCCM to work.
(I assume this question is about automation, so a more manual procedure (visiting each device) could be available when not using SCCM. I just don't know.)

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@rstenborg 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
