### ISSUE TITLE
misspelling under the Modern Desktop Deployment Center

### ISSUE THREAD

**Issue by chjone** [MicrosoftDocs/windows-itpro-docs#2174]
'desktop' is misspelled. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d602e13e-c1af-958b-8574-a020c49a4b89
* Version Independent ID: f77197b5-cabd-25e7-473a-f4aa663ff6e9
* Content: [What's new in Windows 10 deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-whats-new)
* Content Source: [windows/deployment/deploy-whats-new.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-whats-new.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jdeckerms** [comment]
@chjone Thanks for catching that, it will be fixed today.
