### ISSUE TITLE
wrong sequence

### ISSUE THREAD

**Issue by alghaden** [MicrosoftDocs/windows-itpro-docs#2176]
under System Properties 
Click Start &gt; Settings &gt; Settings &gt; click About from the bottom of the left-hand menu
correct 
Click Start &gt; Settings &gt; system &gt; click About from the bottom of the left-hand menu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bc7c182-23ef-11f1-dca4-89fa189a6bdf
* Version Independent ID: 152c1c6a-0889-c898-03e1-52af322a36bb
* Content: [What version of Windows am I running?](https://docs.microsoft.com/en-us/windows/client-management/windows-version-search)
* Content Source: [windows/client-management/windows-version-search.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/windows-version-search.md)
* Product: **w10**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **MikeBlodge**

**Comment by jdeckerms** [comment]
@alghaden Thanks for catching that! It will be fixed today.
