### ISSUE TITLE
SSU use in offline servicing.

### ISSUE THREAD

**Issue by mistergitj** [MicrosoftDocs/windows-itpro-docs#2181]
This appears to be a really recent update on SSUs, but there is no guidance for SSU use in W10 1809 Offline Update Servicing.  Direction, please.  Thanks and enjoy, John.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b706f0af-d504-a8ca-7c38-b8bb9283bfad
* Version Independent ID: 14f31acf-9f47-59a6-269f-62ab249fe560
* Content: [Servicing stack updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates)
* Content Source: [windows/deployment/update/servicing-stack-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/servicing-stack-updates.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mjgar** [comment]
Agreed, I am currently applying the SSU before the LCU when offline servicing my W10 1809 image but would like to know whether this is a requirement or if it is enough to only install the LCU during offline servicing.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@mistergitj - Thank you for submitting this feedback.

From our understanding, the issue has been resolved based on the commit ([157db5d](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/157db5dcd1e98a0409ef859506b5d7947f4469b2#diff-3ee0f2a2b6a1f9657ef38d13036c9d65)) made by the author. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
