### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by xXxOlivierxXx** [MicrosoftDocs/windows-itpro-docs#2182]
"Windows Server 2016 update KB4088889 (14393.2155) provides synchronous certificate enrollment during hybrid certificate trust provisioning. With this update, users no longer need to wait for Azure AD Connect to sync their public key on-premises. Users enroll their certificate during provisioning and can use the certificate for sign-in immediately after completeling the provisioning."

While users can log in right away after creating their PIN, they still need to wait a maximum of 30min (unless your AD Connect sync frequency is larger) for seamless sign-on to work.

Also, the page doesn't mention where are you supposed to have the KB4088889 update installed. Is it on the ADFS Servers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 165d0e13-abec-36c2-08fd-af5596add322
* Version Independent ID: 998acd02-5964-155e-af3c-e5eb807b20e2
* Content: [Hybrid Windows Hello for Business Provisioning (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-provision)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-provision.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-provision.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@xXxOlivierxXx - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@xXxOlivierxXx - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
