### ISSUE TITLE
Erroneous link under "See Also" section 

### ISSUE THREAD

**Issue by jig1** [MicrosoftDocs/windows-itpro-docs#2183]
The last URL in the "See Also" section has a URL link "How to take a screenshot on pc without any app" that goes to a 3rd party website. It is unrelated to this article.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c880203c-6a5b-28e7-c74d-152890baa955
* Version Independent ID: 59c9eb13-dd44-358a-130d-ca1e020573ba
* Content: [What's new in Windows 10, version 1803](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1803)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1803.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1803.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by jdeckerms** [comment]
@jig1 You're right, thanks for pointing it out. The link will be removed today.
