### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by xXxOlivierxXx** [MicrosoftDocs/windows-itpro-docs#2184]
Where is this event ID 300 supposed to be? Is it in the "User Device Registration" logs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b57cce71-9a98-c735-d326-c6de0839e2e1
* Version Independent ID: e623f0be-ee94-b75d-e135-d1f1ef8de0cf
* Content: [Event ID 300 - Windows Hello successfully created (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-event-300)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-event-300.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-event-300.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by veryslothysloth** [comment]
Yes, it should be in the Event Viewer in User Device Registration.

Event Viewer > Applications and Service Logs\Microsoft\Window\User Device Registration\

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@xXxOlivierxXx - Thank you for submitting feedback.

From our understanding, the issue has been answered by veryslothysloth. If you feel it hasn't been answered, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
