### ISSUE TITLE
What is a "Subscription Activation-enabled user" in scenario 1

### ISSUE THREAD

**Issue by NJArcher** [MicrosoftDocs/windows-itpro-docs#2186]
Could you explain what users these are and how you make one of these users for scenario 1? I couldn't find the term "Subscription Activation-enabled user" elsewhere.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-subscription-activation)
* Content Source: [windows/deployment/windows-10-enterprise-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-enterprise-subscription-activation.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by heytechguy** [comment]
Correct me if I am wrong but I believe the "Subscription Activation-enabled user" is just simply a user that has an E3 or E5 licensed assigned to them and they are an enabled user.

**Comment by kumaarrahul** [comment]
Subscription Activation-enabled user is any Azure AD/Office 365 user who has been assigned Windows 10 E3/E5 or Microsoft 365 E3/E5 license since these subscriptions provide the Windows 10 Enterprise upgrade benefits.

**Comment by NJArcher** [comment]
Thanks.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@NJArcher - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by kumaarrahul. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
