### ISSUE TITLE
Feature without a use case

### ISSUE THREAD

**Issue by fergusstrachan** [MicrosoftDocs/windows-itpro-docs#2191]
I don't get it. This seems to enable you to join a device to a domain and to azure! We have this already, it's called joining a domain + having auto hybrid join configured on said domain.

If this was hybrid join from anywhere on the Internet, we would have a useful feature. 

Am I missing something? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12823601-7426-a768-e72f-866b150baccd
* Version Independent ID: c1f993e3-a405-6860-8ab1-7b3d387b4631
* Content: [Hybrid AAD Join](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/user-driven-hybrid)
* Content Source: [windows/deployment/windows-autopilot/user-driven-hybrid.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/user-driven-hybrid.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by egallagh** [comment]
This automates the hybrid join process with autopilot and Intune from a user driven perspective. As mentioned in the fifth bullet point, the Intune connector does the AD join so that the user does not need join rights.

**Comment by fergusstrachan** [comment]
No, I got that bit, and sorry if I sounded a bit cynical, it just seems strange that you need a proxy AND to be next to a DC, unless it's a stepping stone to full hybrid join from outside the office (which I hope it is). :-)

**Comment by SolidKnight** [comment]
That would definitely be nice.

The use case for this is that you can take any stock Windows 10 1809+ install and have it join the domain without having to set anything else up. All this occurs during OOBE setup.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@fergusstrachan - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by egallagh. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by fergusstrachan** [comment]
The reply was simply a clarification of the purpose of the connector.

What I was getting at in my 2nd para was that if the connector enabled hybrid join without the requirement to have the device on the same LAN as domain controllers (e.g. from a user's home or a guest network) this would be useful.
Is this a consideration for the next version?

**Comment by mypil** [comment]
@fergusstrachan - Thank you for your response. Let me loop in the doc owner to get their inputs.

@DulceMontemayor - Can you please share your insights on this issue?

Thank you.

**Comment by mypil** [comment]
@DulceMontemayor - We would like to follow up on this. Can you please share your insights on this issue?

Thank you.

cc: @Dansimp

**Comment by mypil** [comment]
@DulceMontemayor @greg-lindsay - We would like to follow up on this. Can you please share your insights on this issue?

Thank you.

cc: @Dansimp @AndreaBarr

**Comment by greg-lindsay** [comment]
Please see the notice at the bottom of the page when making comments. There is a choice: send feedback about 1) this product or 2) this page. Others have provided answers about the product even though the discussion should be about the content of the page. I'm sorry but we can't engage in a long discussion about the product on each page. If you have further questions, I suggest using the product feedback button. Thanks!
