### ISSUE TITLE
How to Activate

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#2192]
Hi can someone provide more context on how to enable this config via Custom Policy and how to choose which audit options can be enabled?? Or even if they cannot be chosen a list with all the ones which are enabled once this policy is enabled?
Tried using ./Vendor/MSFT/WindowsSecurityAuditing/ConfigurationSettings/EnableSecurityAuditing with boolean true but it doesnt work.  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09bbdaca-6d71-b6e7-2a98-b655d6226bed
* Version Independent ID: 5511fc3b-e6fb-feba-0898-a227d1945058
* Content: [WindowsSecurityAuditing CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/windowssecurityauditing-csp)
* Content Source: [windows/client-management/mdm/windowssecurityauditing-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/windowssecurityauditing-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by jenyalex80** [comment]
I have the same question. I tried deploying this CSP through Intune and get the error -2016345708 (Syncml(404): The requested target was not found.)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@schenardie  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @schenardie Schenardie, Thank you for submitting your query about the doc. Please note this CSP is only applicable on Windows 10 Mobile and Mobile Enterprises editions. To see which CSP is supported by which version of Windows 10, please see https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference#csp-support

Thanks.

**Comment by mypil** [comment]
@schenardie - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
