### ISSUE TITLE
Terms need updating

### ISSUE THREAD

**Issue by SusanBradley** [MicrosoftDocs/windows-itpro-docs#2193]
This page still refers to "Current Branch" and "Current branch for business" which are the older terms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c20d14-6dd5-69a7-b61f-809355e9dc24
* Version Independent ID: 659b4230-b990-145a-d138-4cc8e99fb13c
* Content: [Update Windows 10 in enterprise deployments (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/)
* Content Source: [windows/deployment/update/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/index.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mypil** [comment]
@SusanBradley - From our understanding, the issue has been answered by jaimeo. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
