### ISSUE TITLE
Scope for Experience/AllowWindowsConsumerFeatures changed

### ISSUE THREAD

**Issue by PeterKlapwijk** [MicrosoftDocs/windows-itpro-docs#2196]
The scope for Experience/AllowWindowsConsumerFeatures is set to device is this article, but I know this was in previous versions (1703) a user scope. Maybe worth mentioning.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e8ecbe3-ba72-ec44-0591-7f604d50b1e3
* Version Independent ID: 9d5ff118-d539-dd6e-ae3e-102392c22287
* Content: [Policy CSP - Experience](https://docs.microsoft.com/en-gb/windows/client-management/mdm/policy-csp-experience#experience-allowwindowsconsumerfeatures)
* Content Source: [windows/client-management/mdm/policy-csp-experience.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-experience.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@PeterKlapwijk  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @MariciaAlforque,
could you please advise, when you changed the scope from "User" to "Device" in the commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/bb35e048ca21d5625261d0b4788a6147e5429d96#diff-057a82152e980f834ecc81a9189ffdd7 , was it done because the scope was changed (in this case Note could be added to the article), or because previous information was incorrect? (in this case no change is needed)

Thank you!

**Comment by mypil** [comment]
@PeterKlapwijk - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
