### ISSUE TITLE
Educational Subscriptions

### ISSUE THREAD

**Issue by SeanBirdman** [MicrosoftDocs/windows-itpro-docs#2197]
Are there any plans to make an education subscription version available to educational institutions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-subscription-activation)
* Content Source: [windows/deployment/windows-10-enterprise-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-enterprise-subscription-activation.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by kumaarrahul** [comment]
Hi,

Yes the same is available as Microsoft 365 Education offering. Please refer to links below.

https://www.microsoft.com/en-us/education/buy-license/microsoft365/default.aspx

https://blogs.technet.microsoft.com/educloud/2017/10/20/microsoft-365-education/

https://docs.microsoft.com/en-us/education/

https://www.microsoft.com/en-us/education/how-to-buy

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@SeanBirdman - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by kumaarrahul. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
