### ISSUE TITLE
Question - Ingest Windows 10 ADMX files?

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/windows-itpro-docs#2198]
Is it possible to ingest Windows 10 ADMX files? Or can these OS built in group policies be used directly somehow?
I'm especially interested in 1809 "VolumeEncryption.admx" in order to disable hardware encryption.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f5ed380-12c6-ad56-3f3b-1a0fe190acc9
* Version Independent ID: ecdc3e8c-21e4-0a4c-6208-67905a4e57d4
* Content: [Win32 and Desktop Bridge app policy configuration](https://docs.microsoft.com/en-us/windows/client-management/mdm/win32-and-centennial-app-policy-configuration#ingesting-an-app-admx-file)
* Content Source: [windows/client-management/mdm/win32-and-centennial-app-policy-configuration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/win32-and-centennial-app-policy-configuration.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by schenardie** [comment]
Following.

While i dont think is possible would be nice to hear a confirmation. 

The exiting CSP are far away from covering everything and the fact that backed ADMX are blocked to change System, Software\Microsoft, and Software\Policies\Microsoft keys we cant implement anything that microsoft hasnt already done. Like change the auditing level of events because there is no CSP for it.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@o-l-a-v - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @o-l-a-v Thank you for your query on the doc. Please note this is not possible but you can always share your suggestions using the Microsoft feedback channel. 

@mypil Please guide the user how the user can forward the suggestion.

Thanks.

**Comment by mypil** [comment]
@o-l-a-v - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**

You might find others have made a similar request that you can add to, or you can open a new one.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by kistersr** [comment]
Looking to provide feedback/request to allow ADMX ingestion for the location: HKEY_CURRENT_USER\Software\Policies\Microsoft\Windows\Control Panel\Desktop . I need to specifically set the screensaver and screensaver timeout values for Azure AD/Intune managed devices.

**Comment by o-l-a-v** [comment]
> Looking to provide feedback/request to allow ADMX ingestion for the location: HKEY_CURRENT_USER\Software\Policies\Microsoft\Windows\Control Panel\Desktop . I need to specifically set the screensaver and screensaver timeout values for Azure AD/Intune managed devices.

You can control lockout in minutes of inactivity inside Device Restrictions at least

![image](https://user-images.githubusercontent.com/6450056/73438134-d008c580-434d-11ea-8cbc-a7d7261dee77.png)
