### ISSUE TITLE
Ungünstige Übersetzung im ersten Absatz

### ISSUE THREAD

**Issue by FabianNiesen** [MicrosoftDocs/windows-itpro-docs#2201]
Ungüstige Übersetzung im ersten Absatz: "indem aktuelle Angriffsmethoden gerendert werden." Besser: "indem aktuelle Angriffsmethoden veraltet sind."

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: dfb9445a-681d-24b6-5241-4ebe311f5236
* Version Independent ID: aea60f74-212c-e24e-f164-28a555bc1727
* Content: [Windows Defender Application Guard (Windows10)](https://docs.microsoft.com/de-de/windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@FabianNiesen Thanks for the suggestion. I changed rendering to making in the English version. the localized versions including German will get updated automatically to reflect the change but it may take some time for localized versions to coverage.

**Comment by mypil** [comment]
@FabianNiesen - From our understanding, the issue has been resolved by Justinha. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
