### ISSUE TITLE
Restore-UevBackup Parameter Incorrect

### ISSUE THREAD

**Issue by joshwright10** [MicrosoftDocs/windows-itpro-docs#2202]
The following command under the https://docs.microsoft.com/en-us/windows/configuration/ue-v/uev-manage-administrative-backup-and-restore#restore-settings-in-ue-v-when-a-user-adopts-a-new-device heading is incorrect: 

Restore-UevBackup -Machine <MachineName>

The correct parameter is:
Restore-UevBackup -ComputerName <ComputerName>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57fa9175-8f08-bbc1-552e-11b89b5765c1
* Version Independent ID: 83d0855c-96ff-c5f4-75b1-80a64c0a60cb
* Content: [Manage Administrative Backup and Restore in UE-V](https://docs.microsoft.com/en-us/windows/configuration/ue-v/uev-manage-administrative-backup-and-restore)
* Content Source: [windows/configuration/ue-v/uev-manage-administrative-backup-and-restore.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/ue-v/uev-manage-administrative-backup-and-restore.md)
* Product: **w10**
* GitHub Login: @MaggiePucciEvans
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@joshwright10 Thanks, we'll get that fixed. Btw, when you find things like that in the documentation, you're welcome to make the change yourself -- just click **Edit** in the upper right corner of the page, then the pencil (edit) icon.
