### ISSUE TITLE
Не восстанавливает файлы из карантина в Windows 10 

### ISSUE THREAD

**Issue by shaman1307** [MicrosoftDocs/windows-itpro-docs#2205]
Не восстанавливает файлы из карантина
Обновления системы Windows 10 Pro актуальные на сегодня

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: de416fda-04fb-6780-6675-020fdc2426ba
* Version Independent ID: ede7f3c1-ba3a-e331-80d8-c992b3d7f9a4
* Content: [Восстановление помещенные в карантин файлы в Защитник Windows](https://docs.microsoft.com/ru-ru/windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by cin1968** [comment]
Такая же история. Защитник показывает найденную "угрозу" пишет, что поместил её в карантин, но никаких действий с файлом произвести нет возможности (ни восстановить, ни удалить)
Обновления системы Windows 10 Pro актуальные на сегодня

**Comment by Gh0sTG0** [comment]
Присоединяюсь к проблеме. Microsoft настолько велик, что такие мелочи как возможность ложного срабатывания уходят в область ненаучной фантастики... Только вот откуда мне рабочий файл вытаскивать... Видимо из головы в свободное время... Спасибо Microsoft за потерянный вечер.
Win10SL обновления последние.

**Comment by mypil** [comment]
@samanthaw @MollyMalone 

cc: @AndreaBarr

**Comment by MollyMalone** [comment]
@mypil This does not look like a localization issue.   A rough translation to English of the comments are:

Does not restore files from quarantine in Windows 10

Same story. Defender shows the found  "threat " writes that quarantined it, but no action with the file to make it impossible (neither restore nor delete)
Updates to the Windows 10 Pro system are current for today

I'm joining the problem. Microsoft is so great that such trifles as the possibility of false positives go into the field of non-scientific fiction... Only that's where I get the working file to pull out... Apparently from his head in his spare time... Thank you Microsoft for the lost evening.
Win10SL update last.

**Comment by mypil** [comment]
@shaman1307 - спасибо за взаимодействие с сообществом здесь для документов.

Я знаю, что команды разработчиков всегда ищут отзывы пользователей о том, как сделать Windows 10 лучше. Они закрывают вкладку на отзывы пользователей, и было бы здорово, если бы вы могли добавить свой голос в User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**
Вы можете обнаружить, что другие сделали аналогичный запрос, который вы можете добавить, или вы можете открыть новый. Дайте нам знать, если вы это сделаете, мы можем проголосовать за ваш запрос.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
