### ISSUE TITLE
Is the statement about <meta> tags correct?

### ISSUE THREAD

**Issue by GlennInDC** [MicrosoftDocs/windows-itpro-docs#2206]
In the "Interoperability goals and enterprise guidance" section, the way the text reads, it says that you must continue using IE11 if web apps use &lt;meta&gt; tags. Is that statement correct? It implies that Edge does not support &lt;meta&gt; tags. That can't be correct, can it? Or is that statement supposed to be limited to &lt;meta&gt; tags that have "http-equiv= x-ua-compatible" in them?

Thanks,
Glenn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3dd9c01-6d96-f3dd-c5fc-9565de8221bc
* Version Independent ID: 138ea771-3311-b31f-ccd1-2248871585a3
* Content: [Use Enterprise Mode to improve compatibility (Microsoft Edge for IT Pros)](https://docs.microsoft.com/en-us/microsoft-edge/deploy/emie-to-improve-compatibility)
* Content Source: [browsers/edge/emie-to-improve-compatibility.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/emie-to-improve-compatibility.md)
* Product: **browser-edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@GlennInDC  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@GlennInDC - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
