### ISSUE TITLE
"Manage system settings" is not an available option in the WDSC Add a Role dialog

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#2207]
"Manage system settings" is not an available option in the WDSC Add a Role dialog. Everything else has an equivalent even though the wording for some options has changed.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b246db4-2ef2-fc54-8db1-7a75a4974304
* Version Independent ID: 57290170-ba72-9f26-5a9c-311f6980ea19
* Content: [Create and manage roles for role-based access control](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/user-roles-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/user-roles-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/user-roles-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Hi iadgovuser1, you're absolutely right. Fixing it right away!

**Comment by iadgovuser1** [comment]
@mjcaparas This issue has not been fixed yet in the documentation even though the issue was closed.

**Comment by mjcaparas** [comment]
@iadgovuser1 we've recently updated the labels and it's reflected on the doc. Thanks!

**Comment by iadgovuser1** [comment]
@mjcaparas Thank you

**Comment by iadgovuser1** [comment]
@mjcaparas Now I see a "Manage portal system settings" option

**Comment by iadgovuser1** [comment]
Ok, now that option isn't showing.

**Comment by iadgovuser1** [comment]
@mjcaparas I figured the subtly out. The "Manage portal system settings" option is ONLY available to those in the "Windows Defender ATP Administrator (default)" role. The only time that option shows up in the UI is when you click the Windows Defender ATP Administrator (default) role and the Edit role dialog appears. The description says:  configure storage settings, configure SIEM and threat intel API settings (globally), configure advanced settings, configure automated file uploads, and configure roles and machine groups.

**Comment by mjcaparas** [comment]
Ok, will highlight that subtlety out. Thanks!
