### ISSUE TITLE
More Clarity on reporting

### ISSUE THREAD

**Issue by deshpandeguy** [MicrosoftDocs/windows-itpro-docs#2209]
This article only says by which tools we can monitor and reporting on Windows Defender. But the links dont take us to anywhere apart from introduction of the tool.
Currently we are using Intune to apply Defender policies to co-managed devices. We have compliance policies set to monitor any non-compliance with Defender settings.
However, my question is, How should I be able to 
1. Create a weekly report on how many devices were infected with what malware
2. How should I ensure that all the devices are up-to-date
If we are moving to defender from an existing AV solution, then at least the defender should be able to give basic reporting ability that management wants in order to convince them to move to defender. This will also help to push it to more companies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95629861-d1e1-232c-5727-4ebc831f90d6
* Version Independent ID: f653f426-604c-30ed-b2c0-31b44c2f7117
* Content: [Monitor and report on Windows Defender Antivirus protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/report-monitor-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/report-monitor-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/report-monitor-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by jdarre** [comment]
Agree! Some basic reporting on infections are needed.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@deshpandeguy - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hell @deshpandeguy Thank you for your feedback. You can visit https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/deploy-manage-report-windows-defender-antivirus to see reporting options available for Windows Defender using Intune and SCCM. 

If you are looking for a customized report which is not available, you can contact the Microsoft support team to help you set up reports.

@mypil Please guide user how he can contact MS support team for reports. 

Thanks.

**Comment by mypil** [comment]
@deshpandeguy - I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
