### ISSUE TITLE
screensaver name also required?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/windows-itpro-docs#2213]
Previous group policy settings required a screensaver executable to also be defined for this to work. Is this required with this new setting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75ab75c2-3bfd-bde6-8341-65ba79e9fe65
* Version Independent ID: 7224910c-ac05-26b2-f712-9a5993432615
* Content: [Interactive logon Machine inactivity limit (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit)
* Content Source: [windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by cwmoriarty** [comment]
I had the same concern. The docs referencing 'screen saver' is a bit of a misnomer here. The observed behavior of this policy puts the computer at the 'lock screen' after the timeout.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
Hello @Mike-Crowley , Thank you for your feedback. I am looking into this and will update you accordingly.  If required we will update the doc for future references. 

Thanks.

**Comment by mypil** [comment]
@Mike-Crowley - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by illfated** [comment]
Ref. merged PR #3275

**Comment by mypil** [comment]
@officedocsbot close

**Comment by Mike-Crowley** [comment]
Thanks - can someone also explain when to use this vs DeviceLock/MaxInactivityTimeDeviceLock? they both have similar documentation and both claim to apply to Windows 10 Pro, for example.

https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-devicelock#devicelock-maxinactivitytimedevicelock
