### ISSUE TITLE
Any way to recreate the scheduled task?

### ISSUE THREAD

**Issue by toanyonebutyou** [MicrosoftDocs/windows-itpro-docs#2215]
Hello, 

Is there any way to recreate manually the scheduled task that the GPO creates? I have run into scenarios where it appears that the task completes but it does not actually mdm enroll or the task believes that the device is already MDM enrolled and in these specific cases the task deletes itself, as it is supposed to do once the enrollment is complete. 

Is there anyway to recreate this task? Reapplying the GPO does not seem to do the trick.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by bjiusc** [comment]
The task it creates is under Actions: "Start a program" with details: %windir%\system32\deviceenroller.exe /c /AutoEnrollMDM

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@toanyonebutyou - From our understanding, the issue you raised has been answered by bjiusc. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
