### ISSUE TITLE
[SOLVED] ERROR!! "The device is not valid as specified" !

### ISSUE THREAD

**Issue by ahmedbr** [MicrosoftDocs/windows-itpro-docs#2216]
I'm getting this error message when running the last line:

C:\WINDOWS\system32&gt;bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} device partition=X:
The device is not valid as specified.
Run "bcdedit /?" for command line assistance.
A device attached to the system is not functioning.

What's the solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by illfated** [comment]
Have you tried any of the suggested modifications in the other BCDedit issues in this repository?
-  #1915 ((" -SOLVED- It doesn't work for me"))
- #1556 (((Solved) Raw-mode is unavailable courtesy of Hyper-V. (VERR_SUPDRV_NO_RAW_MODE_HYPER_V_ROOT)))
- #1623 ((bcdedit missing DISABLE-VBS))

See all search results for "bcdedit" in this repository:
https://github.com/MicrosoftDocs/windows-itpro-docs/search?q=bcdedit&type=Issues

**Comment by ahmedbr** [comment]
> Have you tried any of the suggested modifications in the other BCDedit issues in this repository?
> 
> * #1915 ((" -SOLVED- It doesn't work for me"))
> * #1556 (((Solved) Raw-mode is unavailable courtesy of Hyper-V. (VERR_SUPDRV_NO_RAW_MODE_HYPER_V_ROOT)))
> * #1623 ((bcdedit missing DISABLE-VBS))
> 
> See all search results for "bcdedit" in this repository:
> https://github.com/MicrosoftDocs/windows-itpro-docs/search?q=bcdedit&type=Issues

Yup, none of them were beneficial.

**Comment by illfated** [comment]
That's a pity. Oh well, either there could be some forgotten/undocumented caveat in the example, or more error scenarios need to be documented.

**Comment by ahmedbr** [comment]
I've found the solution in the following video:
https://www.youtube.com/watch?v=ZAdc5-XJM_U

**Comment by illfated** [comment]
Good find, interesting. I notice that the procedure is related to what is described in the note beneath the script:
```
(i) Note

The PC must have one-time access to a domain controller to decrypt content, such as files that were encrypted with EFS.
If you want to turn off both Windows Defender Credential Guard and virtualization-based security,
run the following bcdedit command after turning off all virtualization-based security Group Policy and registry settings:
bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} loadoptions DISABLE-LSA-ISO,DISABLE-VBS
```
(Although far from as clear and detailed as the video procedure, it mentions the 3 main differences.)

While browsing through the article page again (I do not have personal, first-hand experience with modern enterprise networks), I notice that the main focus there is to enable TPM security before booting, so it will be (as near as) impossible for an external attacker to break in to your system during first boot & first logon. If you only enable those security features after, I guess the full security is less important to you.

On the other hand, if you and all the others who have been unsuccessful in using the information on the page [Manage Windows Defender Credential Guard](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage) are highly concerned with full security in enterprise environments, I would suggest doing more research (compare in detail your own environment with the scenario outlined in the article) and writing a more detailed report to this repository, specifically if you believe there are errors or omissions in the documentation.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ahmedbr @illfated - Is this issue already resolved? Can we proceed to close this issue or is there a need to update the document content? 

Thank you.

**Comment by illfated** [comment]
Oh. Right. There seems to be issues where the command 
```
C:\WINDOWS\system32>bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} device partition=X:
```
does not work as described. Some times, it happens because the device in question does not have UEFI BIOS or the user tries to run the command on a Windows 10 Pro computer where the `bcdedit` command has different parameters compared to a Windows Server 2016 or 2019, making it confusing to the end user why the command does not work like in the example.

I don't know exactly what the solution should look like, but I imagine it would be useful to have some kind of note in the description to clarify that there is a difference between how the `bcdedit` command  works in Windows 10 compared to Windows Server (2016/2019). Feedback from @ahmedbr (and others) would be helpful in this regard, because I am uncertain about how to clarify this distinction.

**Comment by ahmedbr** [comment]
> @ahmedbr @illfated - Is this issue already resolved? Can we proceed to close this issue or is there a need to update the document content?
> 
> Thank you.

**Comment by ahmedbr** [comment]
@mypil yeah, The issue was solved right here.

> I've found the solution in the following video:
> https://www.youtube.com/watch?v=ZAdc5-XJM_U

**Comment by illfated** [comment]
@ahmedbr : Thank you for posting again to confirm that you found the solution. Would you say that the solution needs to be implemented on the page linked in this issue ticket (the page where you posted your original feedback)?
