### ISSUE TITLE
MDM AutoEnrolling a Windows 10 PC via GPO fails with error code "0x80192ee2"

### ISSUE THREAD

**Issue by e-aldo** [MicrosoftDocs/windows-itpro-docs#2219]
Hello,

We started auto-enrollement of device via a computer GPO by setting ''Enable automatic MDM enrollment using default azure AD credentials'' to ''Enable''.

The GPO is correctly applied, but less than 9% of computers are enrolled. Auto-enrollment failed for remained workstation with error ''Auto MDM Enroll: Failed (Unknown Win32 Error code: 0x80192ee2)''

Thank you for your help.
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e-aldo** [comment]
Hi all,
Update about this topic, hoping it helps.

Maybe the error code "0x80192ee2" can hide others block point but in our case, it was a network issue.

Thanks

**Comment by kiranprakash912** [comment]
Could you exlpain what network issue you had? I am facing the same issue

**Comment by kiranprakash912** [comment]
@e-aldo  Could you exlpain what network issue you had? I am facing the same issue

**Comment by mvthul** [comment]
we having it too any solution

**Comment by mvthul** [comment]
> Hi all,
> Update about this topic, hoping it helps.
> 
> Maybe the error code "0x80192ee2" can hide others block point but in our case, it was a network issue.
> 
> Thanks

what is the issue? how did u resolve
