### ISSUE TITLE
Link to old .admx package

### ISSUE THREAD

**Issue by SteveBurkettNZ** [MicrosoftDocs/windows-itpro-docs#2223]
Download link for 'Administrative templates (.admx) for Windows 10 download' is for the original RTM package. It's now three years out-of-date?  Not sure if there's a summary page that lists the .admx available for each release of Windows 10?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b49ace1-d61d-e552-b8ff-8eaa69d2b1c8
* Version Independent ID: 894316b6-b70a-621f-9f83-4237a9e8051a
* Content: [Administrative templates and Internet Explorer 11 (Internet Explorer 11 for IT Pros)](https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/administrative-templates-and-ie11)
* Content Source: [browsers/internet-explorer/ie11-deploy-guide/administrative-templates-and-ie11.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/internet-explorer/ie11-deploy-guide/administrative-templates-and-ie11.md)
* Product: **ie11**
* GitHub Login: @shortpatti
* Microsoft Alias: **shortpatti**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@SteveBurkettNZ - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@SteveBurkettNZ - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
