### ISSUE TITLE
Product Comparison PDF

### ISSUE THREAD

**Issue by ThomasKur** [MicrosoftDocs/windows-itpro-docs#2224]
Is it correct, that with 1809 Azure Hybrid Join is only supported with Windows 10 Enterprise? Because according to the following page it's also supported with Windows 10 Professional?
https://www.microsoft.com/en-us/windowsforbusiness/compare

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbabaf85-a345-a91e-f4e2-09c2b7871375
* Version Independent ID: bab57f2f-249a-0fe9-4f4a-93d62ce71670
* Content: [Get started with Windows Defender Advanced Threat Protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/get-started)
* Content Source: [windows/security/threat-protection/windows-defender-atp/get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/get-started.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by ThomasKur** [comment]
Do you know already if Hybrid Join is really only available in the Enterprise version or is it just an incorrect information?

**Comment by mjcaparas** [comment]
Hi,
This page is related to Windows Defender ATP. For information on Azure related capabilities, see: https://docs.microsoft.com/en-us/azure/active-directory/devices/hybrid-azuread-join-plan

**Comment by ThomasKur** [comment]
Yes, the page is about WDATP, but on the Page you have a link to the PDF: https://wincom.blob.core.windows.net/documents/Windows10_Commercial_Comparison.pdf
In this document on page 7 at the bottom there starts a list of which domain join features are available in Win10 Pro. It has a check Mark on Active Directory Join, Azure Active Directory Join, but not on Azure AD Hybrid Join(First line on Page 8. 
And this statement ist different than on the Windows 10 page itself https://www.microsoft.com/en-us/windowsforbusiness/compare

So you link to a document with incorrect data or the page https://www.microsoft.com/en-us/windowsforbusiness/compare is incorrect.
