### ISSUE TITLE
Remove Online Apps

### ISSUE THREAD

**Issue by BigIve** [MicrosoftDocs/windows-itpro-docs#2225]
Trying to remove an app from the private store.  But when clicking on the ellipses the option "Remove from private store" isn't shown as described above.  
Has this process changed to remove an unwanted app from the private store? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1a3b64b-ac3b-cc1c-ca70-ddc0eb486d71
* Version Independent ID: 182c6f9c-fa3f-b99e-fa4a-7ccc3db7551d
* Content: [App inventory management for Microsoft Store for Business and Microsoft Store for Education (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/app-inventory-management-microsoft-store-for-business)
* Content Source: [store-for-business/app-inventory-management-microsoft-store-for-business.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/app-inventory-management-microsoft-store-for-business.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by clintoj** [comment]
Same here, no ability to remove an app from the private store

**Comment by adamfowlerit** [comment]
Same here, I've never seen the option to remove anything from the store. Just reminded me when I was adding To-Do for the company.

**Comment by aaronparker** [comment]
In the Business Store go to [Manage / Manage Apps](https://businessstore.microsoft.com/en-au/manage/inventory/apps-software), find the app and click **Private store availability**, under **Choose groups of people who can see this app** choose:
* No one
* Everyone
* Specific groups
Choose _No one_ for the app to be removed from the private store

**Comment by adamfowlerit** [comment]
> In the Business Store go to [Manage / Manage Apps](https://businessstore.microsoft.com/en-au/manage/inventory/apps-software), find the app and click **Private store availability**, under **Choose groups of people who can see this app** choose:
> 
> * No one
> * Everyone
> * Specific groups
> 
> Choose _No one_ for the app to be removed from the private store

That just hides it from the user experience, it doesn't remove it from Products & Services > Apps & Software

**Comment by aaronparker** [comment]
OK, semantics then ;). There used to be an option to [refund the app](https://vmlabblog.com/2018/10/how-to-remove-apps-from-microsoft-store-for-business-intune/), but that doesn't appear anymore. No idea why.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@BigIve  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @BigIve I have checked the reference doc and the information looks good. For your specific question  please see doc App inventory management for Microsoft Store for Business and Education (https://docs.microsoft.com/en-us/microsoft-store/app-inventory-management-microsoft-store-for-business) you can find the details to remove the apps at https://docs.microsoft.com/en-us/microsoft-store/app-inventory-management-microsoft-store-for-business#get-and-remove-private-store-apps

Thanks.

**Comment by adamfowlerit** [comment]
Hi,
The problem is maybe not a documentation problem then but a technical one - the "Remove from private store" option doesn't exist, and this is with a tenant administrator with others confirming the same issue. Not sure if my screenshot will come through but it's below, using the same account that can add and approve applications.

[cid:0b808179-1611-4039-9f6c-1ffa00b97b00]


Thanks

Adam Fowler

________________________________

**Comment by joinimran** [comment]
@adamfowlerit  This might be some other issue. I would suggest you, open a support ticket with Microsoft support team so that they can specifically look into your tenant to better help you.

@mypil Please guide @adamfowlerit how he can open a support ticket with Microsoft support team. 

Thanks.

**Comment by mypil** [comment]
@adamfowlerit - I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by adamfowlerit** [comment]
Will do, I have enterprise support and that usually gets a higher up tech.

Thanks
Adam Fowler

________________________________

**Comment by TrudyHa** [comment]
Confirm that **Remove from private store** isn't an option from the app in Products & services list - I'll update the docs to reflect that change. Removing an app from your private store can be done in a couple of ways:

- From app page, on Private store availability, select No one to remove the app from the private store. The app will still be available on Products & services | Apps & software. You're not returning the app, just removing it from your private store.
- From the private store collection that the app is in, select ... and Edit collection, and then select Remove for the app you want to remove. 

If you're asking about returning a store app, for a refund, those steps are here: https://docs.microsoft.com/en-us/microsoft-store/manage-orders-microsoft-store-for-business#refund-an-order

**Comment by mypil** [comment]
@adamfowlerit - From our understanding, the issue has been answered by TrudyHa. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by adamfowlerit** [comment]
@TrudyHa I've now gone through support - ticket number REG:119070324000267 - who have said the way to remove the app now is through this process rather than the existing documented process:

To complete remove the application from Products & services, please follow below steps:
=========================================================
1.	Sign in to the Microsoft Store for Business or Microsoft Store for Education.

2.	Click Manage, and then choose Products & services.

3.	Find the app you want to refund, click the ellipses, and then choose View license details.

4.	Select all the people in the list, click the ellipses, and then choose Reclaim licenses.

5.	Click Order history, click the order you want to refund, and click Refund order.

6.	Then the application will be disappear in Products & services.

I've confirmed this process works.

**Comment by illfated** [comment]
@adamfowlerit : Thank you for posting feedback with the results from your support ticket resolution.

I must admit that the current working process looks less intuitive than before, which should make it important enough to update the current documentation for that scenario.

**Comment by adamfowlerit** [comment]
@illfated Not a problem - yes it's a lot more clunky than the previously documented process, I'd rather that way still, and the previous option doesn't exist.

**Comment by illfated** [comment]
@mypil : Could you get in touch with the tech writing team to find out if this can be added to the documentation, possibly replacing the current non-working method?

**Comment by joinimran** [comment]
Yes, i can do that and i will update the content.
