### ISSUE TITLE
Insufficient information

### ISSUE THREAD

**Issue by pilcherd** [MicrosoftDocs/windows-itpro-docs#2226]
Would like to understand how to use this to start a background App automatically.  If this is the way to do it please.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a10d4123-a42e-5f4f-2c6a-741fe322b368
* Version Independent ID: 63d884d7-8c40-2ced-e327-1d693f32bcc8
* Content: [StartupBackgroundTasks (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/wcd/wcd-startupbackgroundtasks)
* Content Source: [windows/configuration/wcd/wcd-startupbackgroundtasks.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/wcd/wcd-startupbackgroundtasks.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@pilcherd That provisioning setting only applies to IoT devices, and there is no documentation currently available for it.

**Comment by pilcherd** [comment]
We are creating a Provisioning Package with the Windows Configuration Designer for an IoT device, hence the request for documentation.

**Comment by jdeckerms** [comment]
@pilcherd I don't have any information for that setting at this time.
