### ISSUE TITLE
Old Azure AD and Intune portal in above video

### ISSUE THREAD

**Issue by ajayverma111** [MicrosoftDocs/windows-itpro-docs#2227]
Above Modern management video need to be updated with New ebiza portal for Intune and Azure AD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2dbf610-169d-936a-28d7-f9b8710720b3
* Version Independent ID: ded12365-1392-17d6-6f73-23bbe49ab97b
* Content: [Manage Windows 10 in your organization - transitioning to modern management](https://docs.microsoft.com/en-us/windows/client-management/manage-windows-10-in-your-organization-modern-management#feedback)
* Content Source: [windows/client-management/manage-windows-10-in-your-organization-modern-management.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/manage-windows-10-in-your-organization-modern-management.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **dongill**

**Comment by jdeckerms** [comment]
@ajayverma111 There's a note with the video that lets customers know the Intune UI has changed since the video was recorded. There are no plans at this time to make a new video.
