### ISSUE TITLE
Not Working on Window server 2003 Anymore

### ISSUE THREAD

**Issue by AamirAz** [MicrosoftDocs/windows-itpro-docs#2228]
Hello,
I try to run this on window Server 2003 64-bit But it's not working anymore.
It's not compatible with window server 2003 Anymore?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5bb1ce3-9128-5385-4417-d22eb5f8cb77
* Version Independent ID: cb6ba731-a2c2-e9b9-7c3e-db781b1b5222
* Content: [Microsoft Safety Scanner Download](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/safety-scanner-download)
* Content Source: [windows/security/threat-protection/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/intelligence/safety-scanner-download.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Windows 2003 Server has been dead and unsupported since 2015, as far as I know.
The emergency security patch in May 2017 was only to protect
against the WannaCry ransomware crypto-worm.

**Comment by andreabichsel** [comment]
Correct, Windows Server 2003 went out of support in 2015: https://www.microsoft.com/en-us/cloud-platform/windows-server-2003.
