### ISSUE TITLE
Is it possible to increase the max value(240min) for "Configure auto-restart-reminder notifications for updates"?

### ISSUE THREAD

**Issue by jonasbartho** [MicrosoftDocs/windows-itpro-docs#2229]
Hi,

I really like the new policy "Configure auto-restart-reminder notifications for updates" in combination with "Configure auto-restart required notification for updates. -- 2 - User Action". Sadly enough the max value is here only 240 minutes... Is it possible to extend this to for example "720 minutes", then this would be perfect for our users... I tried to cheat here with setting the "AutoRestartNotificationSchedule" registry to "720" via a group policy...but this sadly didn't work as expected... :(

Any hints how to accomplish this or is this simply not possible yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184809a-63ff-ecc2-ab67-9c9f4df900f8
* Version Independent ID: ac25ee6c-4c57-58b3-1313-e4a53f53c5a1
* Content: [Manage device restarts after updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-restart)
* Content Source: [windows/deployment/update/waas-restart.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-restart.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @jonasbartho  thank you for providing feedback.

The issues section of this repository is intended for documentation feedback.

Please consider opening a support ticket via the following link for your question so that it gets answered quickly:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Feel free to re-open this ticket if you feel that documentation also needs to be updated.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by illfated** [comment]
@jonasbartho : Just in case you revisit this issue, I can only confirm that the reminder period cannot be extended. The only way to delay updates is to either A) set downloading of the updates to manual, or B) set installing the updates to manual (triggering a Windows reminder message to review & install updates when new updates appear), or C) configure Windows Update to not restart as long as a user is logged in.
