### ISSUE TITLE
WinHTTP and proxy autodetection

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/windows-itpro-docs#2230]
The article states "_The WinHTTP stack was designed for use in services and **does not support proxy autodetection, PAC scripts** or authentication_."

At https://docs.microsoft.com/en-us/windows/desktop/WinHttp/what-s-new-in-winhttp-5-1 states that "_To ease the configuration of proxy settings for WinHTTP-based applications, WinHTTP now implements the Web Proxy Auto-Discovery (WPAD) protocol, also referred to as autoproxy_"

At https://blogs.msdn.microsoft.com/ieinternals/2013/10/11/understanding-web-proxy-configuration/ is stated that "_The WinHTTP stack was designed for use in services and other contexts where WinINET would be inappropriate (e.g. because WinINET may show UI or not scale well for unattended use). WinHTTP offers a limited subset of proxy support-- generally speaking, the calling code is expected to set the proxy configuration settings directly on the session or request objects. The user may attempt to configure the "default" proxy for WinHTTP using the proxycfg.exe (XP) or netsh.exe (Vista+) tools, but **these tools only support fixed proxy settings (not autodetection or PAC script URLs)** and WinHTTP-based applications may or may not use those settings_"

Based on the above, it seems that WinHTTP stack itself *does* support proxy autodetection and therefore PAC scripts exposed through WPAD, and is the use of "netsh winhttp" command that requires to specify a fixed proxy and that cannot be a PAC script URL used in WPAD.

Could you clarify this point?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f58247e6-b6a8-e172-941d-b18ee3753a55
* Version Independent ID: b05fe5e8-3490-219a-d0dd-cdbd4c387886
* Content: [Upgrade Readiness data sharing](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-data-sharing)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-data-sharing.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-data-sharing.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@greg-lindsay

Any updates with this clarification question regarding documentation content? We would like to follow-up.

Thanks.

**Comment by e0i** [comment]
@juanand 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.
