### ISSUE TITLE
DisableEnterpriseAuthProxy=0 and Windows Defender ATP

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/windows-itpro-docs#2232]
"Logged-in user's Internet connection" scenario using DisableEnterpriseAuthProxy=0 seems incompatible with Windows Defender ATP, set by ATP onboarding script and ATP service. Also referred at https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-proxy-internet-windows-defender-advanced-threat-protection 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f58247e6-b6a8-e172-941d-b18ee3753a55
* Version Independent ID: b05fe5e8-3490-219a-d0dd-cdbd4c387886
* Content: [Upgrade Readiness data sharing](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-data-sharing)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-data-sharing.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-data-sharing.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@juanand 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
