### ISSUE TITLE
Missing link to IEInternals blog

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/windows-itpro-docs#2233]
"please take a look at this post in the ieinternals blog has no link" link is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f58247e6-b6a8-e172-941d-b18ee3753a55
* Version Independent ID: b05fe5e8-3490-219a-d0dd-cdbd4c387886
* Content: [Upgrade Readiness data sharing](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-data-sharing)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-data-sharing.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-data-sharing.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
> If you want to learn more about Proxy considerations on Windows, please take a look at this post in the ieinternals blog

Good point, it feels as if the sentence is unfinished, in addition to not having a link in any parts of the text.

I wonder if this page was intended in the text:
https://blogs.msdn.microsoft.com/ieinternals/2013/10/11/understanding-web-proxy-configuration/

**Comment by jdeckerms** [comment]
@juanand Thanks, we'll fix that. And thanks for finding the link, @illfated
