### ISSUE TITLE
Links not  available  

### ISSUE THREAD

**Issue by rramoscabral** [MicrosoftDocs/windows-itpro-docs#2234]
Links not available:
-  https://go.microsoft.com/fwlink/p/?LinkId=80347 [We are sorry, the page you requested cannot be found.] 
- https://go.microsoft.com/fwlink/?LinkId=272493  [Export functionality is no longer available] 
- 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2435ab4a-ddf7-d26d-d362-d7de3ff13b64
* Version Independent ID: c6354c18-4e1d-15aa-13c2-0c1dc3ce63b2
* Content: [Getting Started with DaRT 10](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/dart-v10/getting-started-with-dart-10)
* Content Source: [mdop/dart-v10/getting-started-with-dart-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/dart-v10/getting-started-with-dart-10.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by jdeckerms** [comment]
@rramoscabral Thanks for letting us know, we'll get that fixed.
