### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by thejeff28** [MicrosoftDocs/windows-itpro-docs#2236]
The last link for "Purchase Windows Enterprise Licensing" redirects to the local Microsoft home page.

https://www.microsoft.com/en-us/windows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8efb31f6-d09e-1db4-9e1b-baed18254b65
* Version Independent ID: b45f19dd-510d-1cd5-5e05-ce85690aab51
* Content: [MDOP Information Experience](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/index)
* Content Source: [mdop/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/index.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by jdeckerms** [comment]
@thejeff28 Thanks, we'll fix it.
