### ISSUE TITLE
Connector placement

### ISSUE THREAD

**Issue by fergusstrachan** [MicrosoftDocs/windows-itpro-docs#2237]
Any advice on where to place the connector? On a DC? On a member server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12823601-7426-a768-e72f-866b150baccd
* Version Independent ID: c1f993e3-a405-6860-8ab1-7b3d387b4631
* Content: [Hybrid AAD Join](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/user-driven-hybrid)
* Content Source: [windows/deployment/windows-autopilot/user-driven-hybrid.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/user-driven-hybrid.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by pramitib** [comment]
The Intune Connector for Active Directory needs to be installed on a computer running Windows Server 2016 that has access to the Internet and your Active Directory. 
https://docs.microsoft.com/en-us/intune/windows-autopilot-hybrid#install-the-intune-connector

**Comment by fergusstrachan** [comment]
I read that, but it has no advice on whether to use member server or DC, or the pros/cons of each. Hence the question.

**Comment by egallagh** [comment]
As a general principal and for a variety of reasons, you should avoid installing additional services on a DC.

**Comment by illfated** [comment]
I agree. The question has got more to do with the role of the DC server you refer to. If the DC server is a production server, you generally do not want to touch it, unless strictly necessary. A separate server is much more preferred for side tasks like maintenance, testing, changes and general access.

**Comment by egallagh** [comment]
And I would add that wherever possible, even your test environment should, at least architecturally, mimic your production environment.

**Comment by fergusstrachan** [comment]
No I get it, role separation and all that, but sometimes it isn't really practical (small businesses etc), so some guidance on at least supportability would be helpful.

**Comment by egallagh** [comment]
I'm not aware of any restrictions on placement.
I would also remind you that "small business" does not mean "do it the wrong way".
The cost of another VM compared to the potential damage to a small business when something goes wrong...
I always look to save my clients' money, but so much of my work revolves around undoing things that others never should have done.

**Comment by fergusstrachan** [comment]
I must be mistaken. I thought this was where to request clarification/modifications, not to put your d1ck on the table.

**Comment by egallagh** [comment]
Let me clarify. I am not aware of any restrictions on placement and there are none stated in the documentation as it exists. As such, I do not believe that there is a need to modify the documentation. Please excuse my attempt to inform and educate those that may read this as to my years of experiences with implementations that did not follow best practices.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@fergusstrachan - Thank you for submitting feedback.

From our understanding, the issue has been answered by egallagh and illfated. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
