### ISSUE TITLE
Incorrect Template Name 

### ISSUE THREAD

**Issue by torontojc** [MicrosoftDocs/windows-itpro-docs#2239]
The ADMX template Computer Configuration\Administrative Templates\Control Panel\Regional and Language Options\Allow input personalization is actually called Computer Configuration\Administrative Templates\Control Panel\Regional and Language Options\Allow users to enable online speech recognition services

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4662bf49-6fcd-6696-ba9d-33e573f79ea6
* Version Independent ID: b04f4b69-a99e-deb5-88ce-b4092738dead
* Content: [Use Group Policy and mobile device management (MDM) settings to configure Cortana in your organization (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/cortana-at-work/cortana-at-work-policy-settings)
* Content Source: [windows/configuration/cortana-at-work/cortana-at-work-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/cortana-at-work/cortana-at-work-policy-settings.md)
* Product: **w10**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by e0i** [comment]
@eross-msft There is a new PR #2923 available for this issue. Please review. Thanks.

**Comment by eross-msft** [comment]
@e01  I am no longer part of this team. Please re-assign this to @lizap

**Comment by illfated** [comment]
@officebot Assign @lizap

**Comment by illfated** [comment]
@officedocsbot assign @lizap

**Comment by jdeckerms** [comment]
see PR #2923
