### ISSUE TITLE
CommercialID if I use DeviceHealth, UpdateCompliance and UpradeReadiness

### ISSUE THREAD

**Issue by pedrr** [MicrosoftDocs/windows-itpro-docs#2242]
Hi, described in the steps above I should deploy my CommercialID to the devices. We plan to use all three solutions mentioned in the headline, but we see three different CommercialIDs. Which one should we use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c915a18c-ca9e-cf0e-7510-d8f6cca6e3ed
* Version Independent ID: e09ef5c0-6672-027a-c221-33631b602d65
* Content: [Get started with Device Health](https://docs.microsoft.com/en-us/windows/deployment/update/device-health-get-started)
* Content Source: [windows/deployment/update/device-health-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/device-health-get-started.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by zdvorak** [comment]
Your CommercialId is a function of your Log Analytics workspace.  In order to use all 3 Windows Analytics solutions, you'll need to add them to the same Log Analytics workspace -- then you will have a single CommercialId for all of Windows Analytics.

**Comment by pedrr** [comment]
my fault, seems to be the same CommercialID on all three tabs.
