### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by domcote** [MicrosoftDocs/windows-itpro-docs#2243]
https://msdn.microsoft.com/partner-center/createuseraccounts-and-set-permissions Leads to 404 Not Found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2be263b-5134-0e2d-ad25-101e55aeb85a
* Version Independent ID: 43593283-afe8-80d0-38d5-1be447cd50b4
* Content: [Windows Autopilot support](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/autopilot-faq)
* Content Source: [windows/deployment/windows-autopilot/autopilot-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/autopilot-faq.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@domcote - Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
