### ISSUE TITLE
OMS Workspaces no longer offer the "Free" pricing tier

### ISSUE THREAD

**Issue by hmhackmaster** [MicrosoftDocs/windows-itpro-docs#2245]
The documentation listed for creating a new OMS Workspace indicates that the pricing tier selected should be "Free". It looks like the pricing model for Azure's Log Analytics has changed and offers "Per GB" only (from https://azure.microsoft.com/en-us/blog/introducing-a-new-way-to-purchase-azure-monitoring-services/ ).

Since the free option is no longer available, it would be appreciated to update the screenshots and docs to reflect the new correct option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24771310-237e-adf7-be33-59355a87f243
* Version Independent ID: e2792588-8318-98a2-a5bd-ff5cbba75e0e
* Content: [Get started with Upgrade Readiness (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-get-started)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-get-started.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@hmhackmaster  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@officedocsbot reopen

**Comment by mypil** [comment]
@lomayor - Please assist to review and merge PR #3935 created for this issue. Otherwise, kindly share your insights on how this issue can be resolved prior to closing the issue.

**Comment by mypil** [comment]
@hmhackmaster - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
