### ISSUE TITLE
StopAndQuarantine via API

### ISSUE THREAD

**Issue by jmcadams-r7** [MicrosoftDocs/windows-itpro-docs#2246]
Is there a way to stop and quarantine a file via the API? It seems like there was in preview but I'm not sure if it made it to the final version or not. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dce2d9b-f59e-65bb-6ca2-0de4cd142cf2
* Version Independent ID: fc82b0f2-8add-863b-1af6-6c9ac8527c33
* Content: [Take response actions on a file in Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/respond-file-alerts-windows-defender-advanced-threat-protection#stop-and-quarantine-files-in-your-network)
* Content Source: [windows/security/threat-protection/windows-defender-atp/respond-file-alerts-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/respond-file-alerts-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Hi, please see if this is what you're looking for: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/stop-and-quarantine-file-windows-defender-advanced-threat-protection-new

**Comment by jmcadams-r7** [comment]
Thanks!!!
