### ISSUE TITLE
Is there an equivalent of this in the released version? 

### ISSUE THREAD

**Issue by jmcadams-r7** [MicrosoftDocs/windows-itpro-docs#2247]
Did this make it to the production build of Windows Defender ATP API? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db45c17a-a975-9f7e-6d21-bcbc9bc85f61
* Version Independent ID: 867a8109-6c82-354e-3893-a06077f65800
* Content: [Stop and quarantine file API](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/stop-quarantine-file-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/stop-quarantine-file-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/stop-quarantine-file-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Hello, as far as I know, this is in production.
