### ISSUE TITLE
Windows Hello MF Unlock - backdoor?

### ISSUE THREAD

**Issue by mennr1** [MicrosoftDocs/windows-itpro-docs#2251]
How do I prevent that users can still log in to their machines with one single password?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f8c2ce-8edb-60d3-ebf9-bdb625bf66dc
* Version Independent ID: ee1ed0a8-b05c-c499-6504-40b5b298c53b
* Content: [Multifactor Unlock](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/feature-multifactor-unlock)
* Content Source: [windows/security/identity-protection/hello-for-business/feature-multifactor-unlock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/feature-multifactor-unlock.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by robcmc** [comment]
Review the Passwordless strategy documentation. You get to the point where you disable passwords until then the password is the fall back. You should enable Multifactor Unlock as well.
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/passwordless-strategy

**Comment by rdejong1979** [comment]
It's still a valid point as Multifactor Unlock doesn't solve the "backdoor" as it allows you to log in with a single entity. You can disable the password Credential Provider however this will introduced new challenges. I'm more than happy to elaborate these offline.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@mennr1  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by robcmc and rdejong1979. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by rdejong1979** [comment]
No it’s definitely not solved. MFA applies for (SaaS) applications and doesn’t solves the login/unlock of an interactive Windows logon session. The response of @robcmc isn’t relative in the issue mentioned. Please reach out directly for further details.

**Comment by mypil** [comment]
@robcmc  - Thank you for your response. We appreciate your efforts to clarify the docs.

Could you please assist us by suggesting how this content could be edited to incorporate your feedback? If you could suggest what the appropriate text and where it should be placed, I could assign one of our team members to create a Pull Request to get it added or you may also create a Pull Request to add in your suggestion and just link this issue so I can have the doc owner review and merge the content. 

Thank you.

**Comment by mypil** [comment]
@rdejong1979 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to open a new issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
