### ISSUE TITLE
"Turn on BitLocker backup to Active Directory Domain Services" group policy setting has been removed from current versions of Windows

### ISSUE THREAD

**Issue by Conan1989** [MicrosoftDocs/windows-itpro-docs#2255]
Hi

"Turn on BitLocker backup to Active Directory Domain Services" group policy setting have been removed from current versions of Windows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d1e77d9-00eb-7907-08ba-ddb5557fa51e
* Version Independent ID: 5a0a4a51-0bea-a266-1796-f21918cd04e2
* Content: [Prepare your organization for BitLocker Planning and policies (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/prepare-your-organization-for-bitlocker-planning-and-policies#a-href-idbkmk-addsconsaactive-directory-domain-services-considerations)
* Content Source: [windows/security/information-protection/bitlocker/prepare-your-organization-for-bitlocker-planning-and-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/prepare-your-organization-for-bitlocker-planning-and-policies.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Conan1989  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @mypil , @Conan1989 ,
the issue was fixed in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/3b556ae012a3ec952df657f12e10082f3a1894f3#diff-1007e107caa3e991c7148cf07be47542,
I think now it can be closed.
Thank you

**Comment by mypil** [comment]
@officedocsbot close
