### ISSUE TITLE
Mistake in the definition of "Key Trust"

### ISSUE THREAD

**Issue by BartJocque** [MicrosoftDocs/windows-itpro-docs#2259]
"Key Trust"
"The key trust model uses the user's Windows Hello for Business identity to authenticate to on-premises Active Directory. The certificate trust model is supported in hybrid and on-premises deployments and requires Windows Server 2016 domain controllers."
-&gt; I though that for the "certificate trust" model only 2008 R2 DC's are required ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a63c1d-79e8-8e28-88b8-38b9984cdeda
* Version Independent ID: b88c3dc4-c4aa-4b98-e4b9-ab182975b4c0
* Content: [How Windows Hello for Business works - Technology and Terms](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-technology#key-trust)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-how-it-works-technology.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-how-it-works-technology.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by sasanmcp** [comment]
in the "key trust" section, the second sentence should say "The KEY trust model is supported in hybrid and on-premises deployments and requires Windows Server 2016 domain controllers"; but it says Certificate by mistake. please fix it.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by ojrb** [comment]
@mypil Please  check my PR #3174

**Comment by mypil** [comment]
@BartJocque - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
