### ISSUE TITLE
MBAM lifecycle

### ISSUE THREAD

**Issue by yannara** [MicrosoftDocs/windows-itpro-docs#2261]
I heard in october 2018 personally from David James (SCCM developer team leader), that MBAM end of life is suspendend or will be postponed far to the future, because MS realized that Intune+MDM policies are not good enough. Also, who really want to keep recovery keys in the Azure AD? Microsoft released last update to MBAM 2.5 SP1 in July 2018. Currently we still have many customer really interested in MBAM because it is the only platform offering 100% complete automation solution for Bitlocker. Please confirm MBAM end of life one more time, and update the article. If MBAM still will die soon, will the SCCM provide expandend Bitlocker management then?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e5380a-53da-6df1-1952-1be89d9b5969
* Version Independent ID: 82af0c50-fb10-3ad3-1f1d-74a068ea6fa7
* Content: [BitLocker Management Recommendations for Enterprises (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by jordanmills** [comment]
Seriously, there's no way I'd trust AAD with my bitlocker keys except as a secondary store.  If support for bitlocker key archival and MBAM on prem is discontinued, I can see a lot of clients discontinuing use of bitlocker.

**Comment by egallagh** [comment]
Hi Jordanmills. This feedback area is for feedback on the documentation. Any input you have regarding Microsoft products or features should be direct through with appropriate channel, like UserVoice, so that it reaches the appropriate people at Microsoft.
Hope that helps.

**Comment by jason4tw** [comment]
Specific to the documentation then, the line "Thus, over the next few years, a good strategy for enterprises will be to plan and move to cloud-based management for BitLocker." should absolutely be removed. This is in no way sufficient or comparable to managing BitLocker keys in MBAM and is woeful advice to give to customers. This is terrible strategy as key saving in Azure AD is not a good option for any Enterprise particualrily those that are cloud or Azure averse or who are interested in all of the capabilities in MBAM that Azure AD doesn;t have of which there are many which is why MBAM was created in the first place.

**Comment by Justinha** [comment]
Thanks for the comments everyone. I have shared them with engineering and as Ed suggested if you other means like UserVoice please use them also.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Justinha - Do you have any updates from the engineering team?

Thanks.

**Comment by mypil** [comment]
@DulceMontemayor @Justinha - We would like to follow up on this. Do you have any updates?

Thank you.

**Comment by yannara** [comment]
MBAM will be transformed to sccm. Tech preview already has it, I believe we could see this in production this year maybe.

**Comment by jason4tw** [comment]
Well, the 1905 TP has some, but not all of the functionality of MBAM. There is still engineering work going on for the rest of the functionality. See https://techcommunity.microsoft.com/t5/Enterprise-Mobility-Security/Microsoft-expands-BitLocker-management-capabilities-for-the/ba-p/544329.

**Comment by jordanmills** [comment]
Thanks, jason4tw.  That's disappointing but not unexpected.  I suppose I'd be surprised if they ever completely replaced the functionality of MBAM.

**Comment by jason4tw** [comment]
Sorry, not following. That is 100% the intention and direction and they will eventually get there. My point is that they just haven't gotten there yet and what's in TP1905 is just the beginning. The full incorporation almost certainly won't be in 1906 as there is still work going on but maybe, just maybe, it'll make it to 1910.

**Comment by yannara** [comment]
Thanks Jason for clearing this up. I have no time for TP, but saw some screens. MS talked to me last year when they started thinking about this, they interview me about most important capabilities.

**Comment by mypil** [comment]
@yannara - From our understanding, the issue you raised has been answered by jason4tw. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by yannara** [comment]
> @yannara - From our understanding, the issue you raised has been answered by jason4tw. If you feel it hasn't been answered, please re-open this issue.
> Thank you for your contribution to make the docs better! Much appreciated!

Not exactly, you should update the Bitlocker for Enterprice that MBAM features will be transformed to the SCCM.

**Comment by mypil** [comment]
@j0rt3g4 - as discussed, assigning this issue to you. Thank you.

**Comment by j0rt3g4** [comment]
![image](https://user-images.githubusercontent.com/5489996/59396619-3d300200-8d4f-11e9-9aa8-a49cb3bcb8fe.png)

MBAM = Microsoft BitLocker Administration and Monitoring 
Following this article: https://support.microsoft.com/en-us/help/4316957/products-reaching-end-of-support-for-2019

It ended of support on July 9th, 2019.
There's no further information related to it.

**Comment by yannara** [comment]
And there is MDOP may 2019 Servicing Release which has latest mbam client published...

**Comment by j0rt3g4** [comment]
Please define what is MDOP

**Comment by yannara** [comment]
Sorry, I don't have time teach Microsoft staff the Microsoft stuff. Use google.. ehh, sorry.. bing :D

**Comment by mypil** [comment]
@yannara - We appreciate your efforts to clarify the docs. As this site encourages collaboration, we would like to get your kind assistance. Could you please assist us by suggesting how this content could be edited to incorporate your feedback? If you could suggest what the appropriate text and where it should be placed, I could assign @j0rt3g4 to create a Pull Request to get it added. You also have the option to create a Pull Request to add in your suggestion and just link this issue so I can have the doc owner review and merge the content. Thank you.

**Comment by yannara** [comment]
We don't use feedback hub, because it requires full Windows 10 telemetry. We have turned it to lowest supported level (as I think most enterprices do with their Windows 10 enviroment).

I can't tell you guys directly what you should write in your docs based on any rumors, opinions or Twitter posts. From my side, I suggest you add a line there, that MBAM capabilities would be offered from SCCM in on-prem scenarios in a future.

I am supprised, that you really don't seek this kind of information inside your organization yourself. Good luck :)

**Comment by mypil** [comment]
@yannara - Thank you for the suggested information to add to the article. We are here to help the readers and the author/doc owner as a bridge to get your feedback addressed to improve the documentation. Hence, we do our best to be collaborative with the readers who submits their feedback via GitHub. I will have @j0rt3g4 assist to create the PR with your suggested note (_I suggest you add a line there, that MBAM capabilities would be offered from SCCM in on-prem scenarios in a future_.) However, please be informed that it will be the doc owner's call and decision whether they will merge the content or not.

**Comment by j0rt3g4** [comment]
Adding note PR #4011

**Comment by mypil** [comment]
@yannara - The PR to add the feedback that you suggested has been merged but it may take a few days for the merged content to appear in the live article. 

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
