### ISSUE TITLE
"Hide Ease of access feature on the sign-in screen" - how?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/windows-itpro-docs#2262]
Windows 10 1803; I can "Go to Control Panel &gt; Ease of Access &gt; Ease of Access Center", but ", and turn off all accessibility tools." doesn't mean anything.  Typically, they are inactive by default.  How can I disable them? According to "https://answers.microsoft.com/en-us/windows/forum/windows_10-desktop/delete-or-disable-completely-ease-of-access-in/f5763ba2-5ee3-486a-a0ae-589f499c592d", I can't.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cd1e023-65ae-0e1d-b031-c02f5fb1daf8
* Version Independent ID: 8053b30a-82b6-404e-5daa-2110fb56c20b
* Content: [Prepare a device for kiosk configuration (Windows 10)](https://docs.microsoft.com/en-gb/windows/configuration/kiosk-prepare)
* Content Source: [windows/configuration/kiosk-prepare.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-prepare.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@anwarmahmood1 This article gives our recommendations on configuring a device to be a kiosk, including hiding the Ease of Access features from the sign-in screen. If you want the functionality to completely disable accessibility tools, you can suggest that to the product team via the Feedback Hub. You might be interested in [Accessibility information for IT pros](https://docs.microsoft.com/en-us/windows/configuration/windows-10-accessibility-for-itpros).

**Comment by anwarmahmood1** [comment]
technique at 
http://www.mattdavies.gb.net/removing-ease-of-access-in-windows-7-via-gpo/

cacls %windir%\system32\utilman.exe /C /D Everyone


doesn't work; returns ACCESS_DENIED

**Comment by jdeckerms** [comment]
@anwarmahmood1 I'm not understanding you, obviously.

Are you saying that when you go to Control Panel > Ease of Access > Ease of Access Center, and turn off all accessibility tools, "Ease of Access" is still available on the kiosk sign-in screen?

**Comment by anwarmahmood1** [comment]
yes; in "ease of access centre", I can turn on features, such as Narrator, but they are off by default; there is also no way of preventing these features from being turned on, which is what this document recommends.

**Comment by jdeckerms** [comment]
@anwarmahmood1 Thanks for clarifying the problem, I'll check with the engineering team.

**Comment by jdeckerms** [comment]
@anwarmahmood1 Thanks for pointing out that the instructions in the topic weren't adequate. There is a registry key that you can set [to disable ease of access](https://docs.microsoft.com/en-us/windows-hardware/customize/enterprise/complementary-features-to-custom-logon). I will add this link to the topic as well.
