### ISSUE TITLE
Applications not showing up in Kiosk Start Menu

### ISSUE THREAD

**Issue by firedrow** [MicrosoftDocs/windows-itpro-docs#2264]
Can you clarify the statement that applications not installed for user will not show up on the Start Menu?  If I login to my Kiosk user before I apply the Provision Package, I can launch everything from Windows Start Menu.  Once I apply the Provision Package and log back into the Kiosk user, my Start Menu is empty except for the groups I've created.  So I know the applications work, but they were installed under an admin account, not the Kiosk account.

**Comment by jdeckerms** [comment]
@firedrow Are you configuring a single-app or multi-app kiosk? Is the app a Win32 app or UWP app? What version of Windows 10 is the device running? Is your kiosk user account a local standard user account, an Active Directory account, or an Azure AD account?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@firedrow -  May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@firedrow - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
