### ISSUE TITLE
This policy must be wrapped in an Atomic command.

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#2267]
Can some examples of atomic commands be made available?
Trying to set the DeviceLock/MinDevicePasswordLength option without success. 
trying to create an atomic command based on https://docs.microsoft.com/en-us/windows/client-management/mdm/devicelock-csp but it doens seems to work. 

Here is the example im using:

`     <Atomic>
		<CmdID>10</CmdID>
		<Replace>
         <CmdID>1</CmdID>
         <Item>
           <Target>
             <LocURI>./Device/Vendor/MSFT/Policy/Config/DeviceLock/MinDevicePasswordLength</LocURI>
           </Target>
		   	<Meta>
			<Format xmlns="syncml:metinf">int</Format>
			</Meta>
			<Data>14</Data>
         </Item>
       </Replace>
     </Atomic>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a3dde0-fe8d-25d3-3a7e-83acf9c394c6
* Version Independent ID: 2c654710-0be1-1d50-9972-6ccf9d072bf1
* Content: [Policy CSP - DeviceLock](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-devicelock#devicelock-mindevicepasswordlength)
* Content Source: [windows/client-management/mdm/policy-csp-devicelock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-devicelock.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by illfated** [comment]
Your example, via https://www.samltool.com/prettyprint.php ,
using MarkDown code block to keep indents and newlines:
```XSLT
<Atomic>
  <CmdID>10</CmdID>
  <Replace>
    <CmdID>1</CmdID>
    <Item>
      <Target>
        <LocURI>./Device/Vendor/MSFT/Policy/Config/DeviceLock/MinDevicePasswordLength</LocURI>
      </Target>
      <Meta>
        <Format xmlns="syncml:metinf">int</Format>
      </Meta>
      <Data>14</Data>
    </Item>
  </Replace>
</Atomic>
```
(in case someone with skills in Atomic finds this issue and knows enough to help)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@schenardie - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by illfated. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by illfated** [comment]
Just to clarify: I did not answer @schenardie's question as such, I merely posted a more readable version of his example, just in case someone else would know what to look for in order to solve the issue. I do not know enough about the topic to help @schenardie with the problem.

**Comment by mypil** [comment]
@illfated - Thanks for your response.

@schenardie - Could you please assist us by suggesting how this content could be edited to incorporate your feedback? If you could suggest what the appropriate text and where it should be placed, I could assign one of our team members to create a Pull Request to get it added or you may also create a Pull Request to add in your suggestion and just link this issue so I can have the doc owner review and merge the content. Thank you.

**Comment by mypil** [comment]
@schenardie - We would like to follow up on this. Thanks.

**Comment by mypil** [comment]
@schenardie - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
