### ISSUE TITLE
Kiosk Browser Cannot Be Configured

### ISSUE THREAD

**Issue by timedroid** [MicrosoftDocs/windows-itpro-docs#2270]
The documentation points to configuring the Kiosk Browser using "Policies &gt; KioskBrowser" in Windows Configuration Designer. However, Policies only has "Browser", not "KioskBrowser". There's a KioskBrowser configuration section elsewhere for Windows IoT only; it doesn't seem to work for Windows Pro.
Using Windows Configuration Designer 1000.17134.3.0 and Windows build 1709.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd2d1007-2cbb-94a6-18aa-a0b879262ab1
* Version Independent ID: 625d9906-0cb0-23eb-3a56-a84ad774d291
* Content: [Guidelines for choosing an app for assigned access (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/guidelines-for-assigned-access-app)
* Content Source: [windows/configuration/guidelines-for-assigned-access-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/guidelines-for-assigned-access-app.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@timedroid Kiosk Browser requires Windows 10, version 1803 or later.

**Comment by jdeckerms** [comment]
@timedroid Sorry, just realize by the version number that you're using WCD from Microsoft Store. You do have the latest version.

**Comment by jdeckerms** [comment]
@timedroid Could you verify that, when you started your provisioning package, you selected "All Windows desktop editions"? If you select "All Windows editions", you'll only see settings that are common across desktop, mobile, IoT, etc.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@timedroid - We would like to follow up. Can you please provide more details and respond to the query of jdeckerms?

**Comment by mypil** [comment]
@timedroid - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
