### ISSUE TITLE
LocalPoliciesSecurityOptions/MicrosoftNetworkServer_AmountOfIdleTimeRequiredBeforeSuspendingSession

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#2272]
This option doesn't work on Windows 1809.

The method does not exist on WMI
Result: (The system cannot find the file specified.).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 773b74b2-7dc2-d0e5-1e3b-bd6445bceda4
* Version Independent ID: 34b55057-9078-6bd0-a9ac-2f6403b84be7
* Content: [Policy CSP - LocalPoliciesSecurityOptions](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions#localpoliciessecurityoptions-microsoftnetworkserver-amountofidletimerequiredbeforesuspendingsession)
* Content Source: [windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@schenardie  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @schenardie,
could you please provide more details about your environment? I have checked it on 1809 and on 1903 and it worked fine
Thank you

**Comment by schenardie** [comment]
Hi Marat, 

Windows 10 1809 OS build 17763.529
Enterprise licensed
I'm deploying via custom csp
./Device/Vendor/MSFT/Policy/Config/LocalPoliciesSecurityOptions/MicrosoftNetworkServer_AmountOfIdleTimeRequiredBeforeSuspendingSession
I believe the field type is String but i also tested with Integer just to be sure
and a value of 15
Can you share how you configured yours??

**Comment by MaratMussabekov** [comment]
Dear @schenardie,
it is:
OMA-URI: ./Vendor/MSFT/Policy/Config/LocalPoliciesSecurityOptions/MicrosoftNetworkServer_AmountOfIdleTimeRequiredBeforeSuspendingSession
Data Type: Integer
Value: 15

to be sure whether it worked or not, check the following value in registry:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters\autodisconnect

Thank you

**Comment by mypil** [comment]
@schenardie - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by schenardie** [comment]
MDM ConfigurationManager: Command failure status. Configuration Source ID: (46885BE7-CBDC-4C45-B4F0-9DDCE352517A), Enrollment Name: (MDMDeviceWithAAD), Provider Name: (Policy), Command Type: (Add: from Replace or Add), CSP URI: (./Vendor/MSFT/Policy/Config/LocalPoliciesSecurityOptions/MicrosoftNetworkServer_AmountOfIdleTimeRequiredBeforeSuspendingSession), Result: (The system cannot find the file specified.).
That is the error i get from Device Management Enterprise Diagnostic Provider.
As i mentioned previously the method doesnt exist in WMI, therefore it doenst get implemented . 
And the Registry key is not getting created.
@MaratMussabekov  can you post a screenshot of the eventlog showing that the setting was implemented?

Thanks

**Comment by schenardie** [comment]
??

**Comment by illfated** [comment]
@mypil : From the comments directly above mine, it seems that schenardie's problem has not been resolved. Which steps you recommend for schenardie -- other external support options, or reopen this ticket to see if we may have additional replies from @MaratMussabekov ?

**Comment by MaratMussabekov** [comment]
Hello @schenardie ,
looks like you were correct, when I check it using eventlog I see the same error as you. I think the registry setting I was checking has been added before the system was updated to 1809/1903.
Dear @mypil, would it be possible to re-open this case? i think the content of the article should be updated.
Thank you

**Comment by MaratMussabekov** [comment]
Hello @schenardie,
the setting you are trying to deploy was deprecated according to [this source](https://blogs.technet.microsoft.com/secguide/2018/04/30/security-baseline-for-windows-10-april-2018-update-v1803-final/), thats why WMI method was missing.
Sorry for misinformation, PR to add this information to the article was created.
Thank you

**Comment by schenardie** [comment]
Not a problem. thanks for the update though. probably better remove from this page as well.

Thanks

**Comment by mypil** [comment]
@officedocsbot reopen

**Comment by mypil** [comment]
@schenardie - I have reopened this issue so we can track and update you on the PR status. 

Thank you for responding and sharing your additional findings.

**Comment by schenardie** [comment]
Not a problem, happy to help when i can. 👍

**Comment by mypil** [comment]
@schenardie - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
