### ISSUE TITLE
CloudAssignedOobeConfig has a 1024 bitmap to skip keyboard layout

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/windows-itpro-docs#2273]
1024 was added in 1809 I believe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adcfcc02-d931-66e3-6f4f-c14b936358e6
* Version Independent ID: 8972647b-ba21-b68f-b698-5fb6e9e9f1fd
* Content: [Troubleshooting Windows Autopilot](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/troubleshooting)
* Content Source: [windows/deployment/windows-autopilot/troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/troubleshooting.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
@russrimm Can you please confirm where do you think this information should be added?

**Comment by mypil** [comment]
@russrimm - We would like to follow up. Can you please respond to the query of joinimran? Thanks.

**Comment by russrimm** [comment]
Under the heading Windows 10 version 1709 and above where it says CloudAssignedOobeConfig, a new Bitmap value of 1024 was introduced when the self-deploying kiosk mode feature was added (1809). It would go after SkipCortanaOptIn = 1, OobeUserNotLocalAdmin = 2, SkipExpressSettings = 4, SkipOemRegistration = 8, SkipEula = 16.  Please check with Michael Niehaus for more details.

**Comment by joinimran** [comment]
@mtniehaus Can you please share your input and please confirm if there is missing information that needs to be added in the help doc.

**Comment by greg-lindsay** [comment]
The issue was discussed. This value does exist as part of the CloudAssignedOobeConfig bitmap, but the list isn't meant to be exhaustive.
