### ISSUE TITLE
To fix your apps by excluding processes

### ISSUE THREAD

**Issue by jesoj** [MicrosoftDocs/windows-itpro-docs#2274]
Seems to be missing some information in this section: "To fix your apps by excluding processes"
Simple creating a Reg key under HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ cannot be what is needed as iexplorer.exe is already there for me. So think something is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91a1567e-cc12-b203-65ac-5023aa3997f7
* Version Independent ID: 946c6dcf-3ee7-47c3-a973-edbf955da875
* Content: [Block untrusted fonts in an enterprise (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/block-untrusted-fonts-in-enterprise#fix-apps-having-problems-because-of-blocked-fonts)
* Content Source: [windows/security/threat-protection/block-untrusted-fonts-in-enterprise.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/block-untrusted-fonts-in-enterprise.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@jesoj Thanks for your feedback. I'm not sure I follow you. What processes do you want to exclude? Can you fix the app by installing the problematic font instead?

**Comment by jesoj** [comment]
I would like to have Blocking Untrusted Fonts set to enabled, and then exclude iexplorer.exe from the blocking.
The article describes that I need to do the following to exclude a process:
To fix your apps by excluding processes
On each computer with the app installed, open regedit.exe and go to HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\<process_image_name>.

But on all of our PCs iexplorer is already added here, so it does not seem to work. Would expect that we also are required to create some data under HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\iexplorer.exe

Hope it is more clear now what issue I am seeing 
Thanks

**Comment by Justinha** [comment]
@jesoj thanks for explaining and sorry for delay. An engineer here commented that Windows 10 loads untrusted fonts in a sandbox regardless, and doesn't actually recommend using this feature on Windows 10. I'm trying to confirm with others but I'll probably end up removing this topic from Windows 10 doc set. Thanks again for raising this issue.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jesoj - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by Justinha. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
