### ISSUE TITLE
No Battery Limit mode switch in UEFI

### ISSUE THREAD

**Issue by max-cw** [MicrosoftDocs/windows-itpro-docs#2275]
I cannot find the option in the UEFI setting for my Surface Book 2. This [page](https://support.microsoft.com/en-us/help/4464941/use-battery-limit-for-surface-devices-plugged-in-for-long-time) says that SB2 need no firmware update for this feature. Still, I have the latest firmware (October 2018) but this option still does not show up. Is there any condition which is not stated on this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a767ea0-4095-7a35-3828-4b3a17a0ea26
* Version Independent ID: 4ca4088c-1e98-c725-d46b-94cecfa123f2
* Content: [Battery Limit setting (Surface)](https://docs.microsoft.com/en-us/surface/battery-limit)
* Content Source: [devices/surface/battery-limit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/battery-limit.md)
* Product: **w10**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by andritolion** [comment]
It says that the feature is not currently available on that page...

**Comment by illfated** [comment]
@max-cw : from the page you linked (https://support.microsoft.com/en-us/help/4464941/use-battery-limit-for-surface-devices-plugged-in-for-long-time),
it is just as andritolion said:
> Surface Book 2 - Feature currently not available

Also, if you read the page https://docs.microsoft.com/en-us/surface/battery-limit , you should find this:
> Currently, Battery Limit is only supported on Surface Pro 4 and Surface Pro 3. However, the setting will be available in the future on other Surface device models.

**Comment by max-cw** [comment]
> Currently, Battery Limit is only supported on Surface Pro 4 and Surface Pro 3. However, the setting will be available in the future on other Surface device models.

Thank you both for pointing that out. I am almost sure that this part wasn't there when I created the ticket a month and a half ago, but I could be wrong.

**Comment by illfated** [comment]
Maybe close this issue then, since it appears that it has been solved?
