### ISSUE TITLE
All settings are also available in user configuration

### ISSUE THREAD

**Issue by NJArcher** [MicrosoftDocs/windows-itpro-docs#2276]
All the info for all the Edge settings here only show the setting for computer configuration and HKLM registry keys. Every policy is also available for the user configuration and HKCU registry keys. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dac404ef-2198-b628-080b-3bf44f93fd45
* Version Independent ID: 2c9e90ff-7cd3-93b5-0641-1ef9a2040930
* Content: [Microsoft Edge - Address bar group policies](https://docs.microsoft.com/en-us/microsoft-edge/deploy/group-policies/address-bar-settings-gp)
* Content Source: [browsers/edge/group-policies/address-bar-settings-gp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/group-policies/address-bar-settings-gp.md)
* Product: **edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@NJArcher - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello, @NJArcher Thank you for your feedback here. Please note that HKLM settings are applied on machine independent of user profiles. Whereas HKCU is applied for the current users. So to ensure that policy is applied for all users Microsoft has mentioned HKLM subsetting. 

Thanks.

**Comment by mypil** [comment]
@NJArcher - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
