### ISSUE TITLE
Link to password randomisation tool

### ISSUE THREAD

**Issue by banzaisi** [MicrosoftDocs/windows-itpro-docs#2281]
Please update the second bullet in the last section: 

Passwords can be randomized by: Configuring, customizing and implementing a free tool to accomplish this task

Link should now redirect to the Microsoft supported LAPS tool rather than the unsupported old version:
https://technet.microsoft.com/en-us/mt227395.aspx

The Note regarding lack of support can be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74d32ee6-c7ff-9328-97d6-40ad82c73392
* Version Independent ID: 01f10cbb-4cae-077f-8245-7b0ada8305d7
* Content: [Local Accounts (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/local-accounts#a-href-idsec-manage-accountsahow-to-manage-local-user-accounts)
* Content Source: [windows/security/identity-protection/access-control/local-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/access-control/local-accounts.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@banzaisi Thanks for the correction! This is published now.
