### ISSUE TITLE
Alert classification missing information

### ISSUE THREAD

**Issue by corinaf1** [MicrosoftDocs/windows-itpro-docs#2287]
Hi there, 

We are missing on this page under the "alert classification" a couple of important things:
* We should put more emphasis on providing the classification of true positive/false positive. Should stress that this classification is used to monitor alert quality on our end and we can tune alerts to be more accurate using this feedback.
* We should add a description about the "determination" field which defines additional fidelity for a "true positive" classification. Here we should mention that the determination contains values for "security testing" to address alerts triggered by intended suspect activity such as pen-testing, which are true positives from a detection perspective but it's intended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 578a2a0c-d8ec-de9f-0a2a-450d1087ecf7
* Version Independent ID: 14b80f24-ed8e-9b63-d3f6-85852467b679
* Content: [Manage Windows Defender Advanced Threat Protection alerts](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/manage-alerts-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/manage-alerts-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/manage-alerts-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by lindspea** [comment]
@corinaf1 Thank you for reaching out and helping improve MS Docs.  Could you perhaps suggest the information to be added in bullet point and I can have it approved and implemented.

**Comment by corinaf1** [comment]
Looks good to me. On the previous question, yes "security testing" and "security personnel" are similar in that they would both result in true detections but the activity is intended rather than malicious.

**Comment by corinaf1** [comment]
Thanks, I’ve commented back, the updated text looks good to me, thank you for following up!

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot close
