### ISSUE TITLE
DisableAntiVirus policy

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/windows-itpro-docs#2296]
Can't find DisableAntiVirus policy in Windows ADMX. How could that policy end up set?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13006cbf-ad22-e75a-bf3a-2a6d0b92f088
* Version Independent ID: c9a7a12f-2ef5-b5fa-b515-41ecce5fecd1
* Content: [Troubleshoot Windows Defender ATP onboarding issues](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/troubleshoot-onboarding-windows-defender-advanced-threat-protection#ensure-that-windows-defender-antivirus-is-not-disabled-by-a-policy)
* Content Source: [windows/security/threat-protection/windows-defender-atp/troubleshoot-onboarding-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/troubleshoot-onboarding-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Hello, 
The DisableAntivirus value is not supported by the built-in ADMX. 
It may however be set by other policy tools. In those cases, it should also be cleared using the same set of tools.
