### ISSUE TITLE
Key trust Group Policy managed Domain Controller Requirement

### ISSUE THREAD

**Issue by jricha34** [MicrosoftDocs/windows-itpro-docs#2297]
It says Windows Server 2016 Domain Controllers are required. Does this mean.... One domain controller? One domain controller per domain? All of the domain controllers in a domain? All of the domain controllers in the forest? If it is some number between 1 and all of the domain controllers in a domain or forest, how many? The fact that you require the domain controller level but don't require a domain or forest functional level opens up all sorts of questions on what exactly is needed. Normally if every domain controller in a domain or forest is needed, the functional level is required as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e5f5f1-16cf-57e2-bdfc-b090d90437b1
* Version Independent ID: 1662c47f-12cb-147d-25f0-dee98b6c7722
* Content: [Windows Hello for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-identity-verification.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-identity-verification.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by jricha34** [comment]
Note that it looks like https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers covers some of this but it still doesn't do it well. That document basically states how dc locator in general works with DNS SRV record priority/weight without actually discussing priority/weight. You just add in the DS_10 filter for the locator services to further filter the domain controllers available pool to implement priority/weight against. Still think this article needs some tweaking for people looking for summary of what is ahead of them perhaps with links to more detailed info.

Still need details on what is the actual difference in the load characteristics from a normal windows kerb request and these new key mapped requests. Is it one for one? Is it the same amount of data going in to and out of the domain controller for the request as it is for a normal kerb request? Is the query identical in perf/size? How is the mapping done in AD to match unique user to public key, so far I haven't stumbled upon that but then I can't currently dedicate time to completely research this all by itself so perhaps that is answered somewhere that I haven't stumbled across yet.  It would be cool if there was a document showing actual network packet trace of a client performing the new method with callouts on what various bits are doing. But I have thought it would be great to have network packet traces of clients doing most everything available in the MSFT docs so people could refer back to them when digging into issues. :D

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by j0rt3g4** [comment]
Added #3823 to solve this issue.

**Comment by e0i** [comment]
@officedocsbot unassign @mypil
@officedocsbot assign @e0i

**Comment by j0rt3g4** [comment]
@e0i  can you follow up on this one?

**Comment by e0i** [comment]
@jricha34 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
