### ISSUE TITLE
Wireless Control within MultiApp Kiosk Mode

### ISSUE THREAD

**Issue by tonyvaki** [MicrosoftDocs/windows-itpro-docs#2298]
after reviewing the MultiApp Kiosk Documentation and the Windows ICD, was there a method to allow the "kiosk user" the rights to control which wireless network he connects to? Using the Native Windows Wireless Control Panel?

**Comment by jdeckerms** [comment]
@tonyvaki I don't think so, but I'll need to check with my kiosk expert on the product team who is unfortunately away at this time, so it will be a few weeks before I get back to you with an answer.

**Comment by jdeckerms** [comment]
@tonyvaki It's possible, but implementing it is a bit complex. I'll be adding the steps to the topic, hopefully this week -- I'll let you know as soon as they're published.

**Comment by jdeckerms** [comment]
@tonyvaki I won't be adding the implementation steps to the topic, as they haven't been formally tested so I can't recommend them as a supported method. I'll tell you how an engineer got it working:

1. Create a shortcut called Network.lnk.
2. In the "Type the location of the item" field, enter **explorer.exe ms-availablenetworks:**, and click **Next** to create the shortcut.
3. Move Network.Ink to %AllUsersProfile%\Microsoft\Windows\Start Menu\Programs\Accessories\
4. In the XML for your multi-app kiosk configuration, in the **AllowedApps** section, include the following:
   <App AppUserModelId="windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel" />
    <App DesktopAppPath="C:\Windows\System32\cmd.exe" />

5. Be sure to include a tile for Network.Ink in the StartLayoutCollection section.

**Comment by illfated** [comment]
@jdeckerms : it looks like your step 4 does not show any code at all.
Maybe you could add an extra ``` line (MarkDown code block fence)
above & below that line so the code in step 4 becomes visible?
