### ISSUE TITLE
Extended codes section needs an update

### ISSUE THREAD

**Issue by td47** [MicrosoftDocs/windows-itpro-docs#2301]
The major phase error section (showing 1 to 5) needs an update. The article mentions it is only up to 1607 Anniversary Update. I beleive that 1703 onwards now has a Finalize phase, that is covered by codes beginning with 6 (e.g. 0x60015). Certainly 1809 upgrades can get  0x6nnnn errors in Finalise, I have had this.
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b70118b1-730b-8e97-20a1-1d8cf0f33d53
* Version Independent ID: b3db47a2-df6a-03d0-1cdf-3e90017e7824
* Content: [Upgrade error codes - Windows IT Pro](https://docs.microsoft.com/en-gb/windows/deployment/upgrade/upgrade-error-codes)
* Content Source: [windows/deployment/upgrade/upgrade-error-codes.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-error-codes.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@td47 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@td47 Thank you for sharing your query. Can you please share more details and information that is missing and required to be added in the doc. It would be great if you can share any of the above mention error codes screenshot (if you have) so that we can further look into this.

Thanks.

**Comment by td47** [comment]
Hello, thanks for your response. I did save some error information from an earlier run of the Microsoft setupdiag utility, that decoded the information below, from an 1809 Feature Upgrade installation attempt. As I found (after much research), that the root cause was an "invalid file handle" returned during a BCD export attempt by an install script, I needed to use a third-party utility (EasyRE from Neosmart that has EasyBCD fix functionality built-in) to fix this proir to the next attempt. I think the original cause was a bug in the 1709 FU install some time ago, that corrupted the BCD.

Here is MY log output taken at that time of the previous 1809 Fu install failure:

"Error: SetupDiag reports down-level failure, Operation: Finalize, Error: 0x80004005 - 0x60015
Refer to https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-error-codes for error information."

My understanding is that the 0x6 part of the 0x60015 secondary (sub-code) refers to the PHASE of the install, in this case, as documented: "Finalize". This is NOT documented in the docs link provided by the setupdiag utility, hence my reporting it.

It is NOT just me getting this, here is a report from another user below:

[]([](https://www.windowsphoneinfo.com/threads/upgrade-windows-10-failure-with-error-ox80004005-1803-to-1809.192467/))

**Comment by joinimran** [comment]
Thanks for sharing the details here.

@mypil Can you please engage doc owner to get the inputs so that we can see how this doc can be improved. 

Thanks.

**Comment by mypil** [comment]
@lomayor - Can you please share your insights on this issue?

Thank you.

**Comment by mypil** [comment]
@lomayor We would like to follow up on this. Can you please share your insights on this issue?

Thank you.

cc: @Dansimp

**Comment by mypil** [comment]
@td47 - We appreciate your effort and feedback that helps us improve the content. However, this request is related to some of the closed issues where Error codes that are unlisted in this topic are most likely transient and always too complex to be able to provide resolution through a help topic. Please see [here](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3317#issuecomment-485223650) for your reference.

Therefore, it may be best for you to either file a problem through [Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub), or open a [service ticket](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)  or reach out through other various support channels. These avenues allow us to properly investigate the issue in ways we could never do through a comments section on a GitHub issue.

Please understand that this site is a product documentation site and not a support nor a feature request site. I hope this gets you pointed in the right direction. Thank you.

**Comment by td47** [comment]
Hello @mypil I don't really understand your response.  I noted that @joinimran had asked for an example of one of the errors codes that I experienced, and so I provided feedback of the problem scenario that gave rise to the error code being output, so that you and your documentation team could see the proper context. I think you may have misconstrued this as a request for help with the problem. This is NOT the case, as I have already researched this in depth via OTHER forums, and used a third-party product to actually fix up the root cause already. I am MERELY asking that the OFFICIAL MicrosoftDocs document that is supposed to document the errors from FEATURE UPGRADES, is kept up to date, so that technical administrators and support personnel, can refer to it so they know HOW and WHERE to properly apply the diagnostic and support efforts to get a good outcome for the user, from a failed upgrade. It should be obvious, that the document in its current state, is not even aligned with Feature Upgrade 1809, let alone the newly deployed 1903 Feature Upgrade. For a supposed World Class Software company like Microsoft, this is disappointing.  Perhaps @lomayor is not the Doc owner anymore, as I see no input. Perhaps you can reach out to Dona Sarka, she may have contacts with the "internalists" who may know the Script Framework scripting language, and its new error references, from the source code comments.

**Comment by td47** [comment]
FYI: I see that [http://blogs.technet.com/yongrhee](url) (@yongrhee) has created some setupdiage.exe tool information (that refers to, and uses the Microsoft Document at issue), and so may have some internal knowledge on how the update errors should be updated.

**Comment by mypil** [comment]
@greg-lindsay - can you share your insights with this issue? Thanks.

**Comment by greg-lindsay** [comment]
Hi there, sorry it has taken a while for me to respond.

I am looking into this right now. You are right that the setupdiag tool references this page. I am also the author of that tool's documentation.  FYI, version 1.5 is set to release very soon.  

I think a new phase was added recently and I thank you very much for pointing out that this affects the extend codes!  I'm checking with someone right now to get complete information about this and I'll update the topic as soon as I have this.

**Comment by td47** [comment]
Hello @greg-lindsay thanks for your positive response, and the commitment to update in doc version 1.5.

The setupdiag tool has certainly been very useful, and seems popular with techs and admins, so it would be great to see the latest doc.

What is the correct protocol here - should I just keep this open for your team to document and book time and collaboration efforts, or should I close it off?

**Comment by mypil** [comment]
@td47 - We will keep this issue open as we are still awaiting further information from the product engineering team. Thank you.

**Comment by greg-lindsay** [comment]
I've been informed that the finalize phase with new codes is part of non-event objective (NEO) and unified update platform (UUP). I'm still communicating on whether or not this 'finalize' phase can be documented in the same way that we have entered the other phases.

**Comment by greg-lindsay** [comment]
I'm going to make an update to the page, but it's a little more complex than what I had anticipated.
There are three pages that need work based on changes that have occurred in how in-place upgrade works. The goal of all this is to reduce the number of reboots that are needed.

**Comment by mypil** [comment]
@td47 - From our understanding, the issue has been answered by greg-lindsay. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by greg-lindsay** [comment]
I'll provide a little more detail here. We can leave the issue open or close it, but either way I do plan to update the in-place upgrade steps.

Starting in 1709, NEO (non-even objective) is a new model used to install feature updates. The previous model remains as a fall-back method. However not all changes were immediate and I believe the new system wasn't fully in place until 1903. Many of the same steps are still being performed, they are just being done a little differently so as to make the process faster.

I have a lot of other work pending however. With Windows 7 end of life coming up I need to update some other docs and this particular one is not first in line, so please be patient and I'll get to the work in the next couple weeks.

**Comment by td47** [comment]
@mypil - from what I see from the input provided by @greg-lindsay there is still a lot of updating needed to this and related documentation surrounding the Windows Update framework and processes, that are in need of proper tracking with relevant documentation changes, that the document owner Greg Lindsay is in the middle of. As this is a lot of investigative and editing work, I suspect he will want this kept open for tracking and documenting WHAT documents need updating, and the work and time-lines involved, cross-referencing both documents, and the Feature Updates they refer to. This important document update work will help technical administrators support users better, and so I will be quite patient with this, and I am happy to await a good outcome, that will help both Microsoft and Technical users that need this updated information, so as to give users a better chance of problem solutions, by knowing where to concentrate testing and diagnostic efforts.

**Comment by mypil** [comment]
@td47 - This is noted. We will keep this issue open until the docs have been updated by @greg-lindsay .

Thank you for your patience and valuable feedback.

**Comment by greg-lindsay** [comment]
@td47 I'm closing this issue for now - sorry that I can't get the document updated just yet. As I mentioned it isn't a simple update, the entire process needs to be rewritten and right now we're very busy preparing for the next release of Windows 10. I'll need to return to this request in November or December I'm afraid.
