### ISSUE TITLE
Microsoft please try adding detailed progress bars to lengthy processes

### ISSUE THREAD

**Issue by aliadhillon** [MicrosoftDocs/windows-itpro-docs#2302]
On many lengthy processes just dots keep floating around on screen with no details on what is being installed, how much it has been installed or any other progress indicator.

**Comment by jdeckerms** [comment]
@aliadhillon Could you submit your comments in the Feedback Hub app? Your feedback is about how the product works, and it should go directly to the engineering team. Thanks!

**Comment by aliadhillon** [comment]
ok @jdeckerms. But I thought it was a real issue not a comment.

**Comment by jdeckerms** [comment]
@aliadhillon I'm not saying it's not a real issue! But it isn't about the documentation, and we can't help you here.

**Comment by aliadhillon** [comment]
ok @jdeckerms thank you. I will submit it over there.
