### ISSUE TITLE
missing extended information on "Weather updates for a specific city in a weather app"

### ISSUE THREAD

**Issue by Shachar2like** [MicrosoftDocs/windows-itpro-docs#2303]
am really interested on changing the default country the bing weather app has on windows 10 and it's just a shame that there's no link or more information on how to do it in this article...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50ad17a1-3dc3-9d2e-90ae-e6e3d054d4e5
* Version Independent ID: 89807489-f29f-7316-6a47-ee64330a4815
* Content: [Add image for secondary Microsoft Edge tiles (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/start-secondary-tiles)
* Content Source: [windows/configuration/start-secondary-tiles.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/start-secondary-tiles.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@Shachar2like You can change the default location for the Weather app in the settings for the Weather app. (Click the Settings icon in the lower right of the app.)
