### ISSUE TITLE
Retention Security and System

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#2306]
Hi there, can the retention (ControlEventLogBehavior) be configured for Security and System logs?

the EventLogService/ControlEventLogBehavior only configures the Application Event log and not the other 2.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dff6da0f-1424-9109-c7d4-751842850c5b
* Version Independent ID: 2f8bd8bf-8103-2b0b-9ec2-cf54687b23a2
* Content: [Policy CSP - EventLogService](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-eventlogservice)
* Content Source: [windows/client-management/mdm/policy-csp-eventlogservice.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-eventlogservice.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@schenardie - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@schenardie Thank you for sharing your feedback. Please note that ControlEventLogBehavior can only manage application logs and you can not configure this for security and system logs. 

Thanks.

**Comment by mypil** [comment]
@schenardie - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
