### ISSUE TITLE
Hide update notifications documentation issue

### ISSUE THREAD

**Issue by dieterv** [MicrosoftDocs/windows-itpro-docs#2309]
Looking at the WindowsUpdate.admx file (distributed with the "Administrative Templates (.admx) for Windows 10 October 2018 Update.msi" package, it would seem "SetUpdateNotificationLevel" and "UpdateNotificationLevel" have been swapped in this document. The admx file lists 0 and 1 as possible values for SetUpdateNotificationLevel and 0, 1 and 2 as possible values for UpdateNotificationLevel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cd1e023-65ae-0e1d-b031-c02f5fb1daf8
* Version Independent ID: 8053b30a-82b6-404e-5daa-2110fb56c20b
* Content: [Prepare a device for kiosk configuration (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/kiosk-prepare)
* Content Source: [windows/configuration/kiosk-prepare.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-prepare.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@dieterv Thanks for catching that, the settings and values do seem to be reversed in the doc. That will be fixed today.
