### ISSUE TITLE
MDM Bridge WMI Instructions - Requires SYSTEM context

### ISSUE THREAD

**Issue by cnvsccm** [MicrosoftDocs/windows-itpro-docs#2314]
Hi guys,

Was trying to set this up today on a test PC using these instructions:

"WMI bridge: Environments that use Group Policy can use the MDM Bridge WMI Provider to configure the MDM_SharedPC class. For example, open PowerShell as an administrator and enter the following..."

However, after an hour of digging around online, I found that configuring MDM Bridge WMI stuff via PowerShell for Device settings requires running the cmdlets as SYSTEM, as per this MS site:

https://docs.microsoft.com/en-us/windows/client-management/mdm/using-powershell-scripting-with-the-wmi-bridge-provider

Perhaps this could be noted on the "Configuring Shared PC Mode on Windows" documentation?

Thanks,
Andrew

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14b376e2-39bd-faca-a76c-dd21bad8d8fd
* Version Independent ID: a76cabb0-59b9-7e97-6603-eec7d37f1fd4
* Content: [Set up a shared or guest PC with Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/set-up-shared-or-guest-pc#configuring-shared-pc-mode-on-windows)
* Content Source: [windows/configuration/set-up-shared-or-guest-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/set-up-shared-or-guest-pc.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@cnvsccm Thanks for pointing that out, Andrew. I'll add a link to the scripting topic from the shared PC topic today.
