### ISSUE TITLE
Error Code 0xc000005e not listed

### ISSUE THREAD

**Issue by andy-vdg** [MicrosoftDocs/windows-itpro-docs#2317]
When joining Azure AD it enrols into Intune and Hello for business. It prompts for setup of PIN as well as face recognition or fingerprint depending on the device. However for each method the login doesn't work and instead "Your credentials could not be verified" is displayed. When the PIN is entered additionally the following error is displayed: "Something went wrong and your PIN isn't available (status: )xc000005e, substatus: 0x0). Click to set up your PIN again." Setting up the PIN again doesn't make a difference. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-nz/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by alexey-zhel** [comment]
0x80004005 not listed - PIN reset error.

**Comment by DaniHalfin** [comment]
Hi @andy-vdg, thanks for opening this issue.
For error codes unlisted here, in most cases those are transient error codes being surfaced by other services in the Windows Hello dependency chain.
We are working on something to improve the user experience in that regard, but that will not solve the issues you are experiencing.
If we find a reoccurring error codes that isn't covered here and should be (meaning, in most cases, it is coming from Windows Hello and not other components) we'll make sure to add it to this page.
By your description, we'll need some more information on how your environment is configured to understand what might be causing this. To protect your privacy and environment, please don't share this information here but rather please either file a problem through Feedback Hub, or reach out through our various support channels. Both avenues allow us to properly investigate the issue in ways we could never do through a comments section on a GitHub issue.
The feedback section in the topic is generally meant for feedback on the content, and we can't really use it for in-depth troubleshooting.
We thank you for taking the time to reach out, but we also want you to have the best time to resolution of the issue, and going through this feedback channel won't get us there.
I'll be closing this issue, but feel free to respond if you feel we missed something. We can always re-open.
