### ISSUE TITLE
New-AppVSequencerVM not working 

### ISSUE THREAD

**Issue by gprosch** [MicrosoftDocs/windows-itpro-docs#2318]
I have not been able to get this script to work.  When I looked at the log I saw a "Access is denied" message.  I tried logging into the AppVSequencerUser account using the encrypted password stored on the host after translating it to a human readable form.  That did not work so I modified the script to use a password that I set.  I double-checked that it matched what was in the file.  However, I am not able to login to the account even when I use a known password.  Something seems to be wrong with the provisioning when this password is set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 103f741d-146b-c1f7-ac14-093094a212b6
* Version Independent ID: e28f143b-6475-b4bf-8e19-2c0b0540b750
* Content: [Automatically provision your sequencing environment using Microsoft Application Virtualization Sequencer (App-V Sequencer) (Windows 10)](https://docs.microsoft.com/en-us/windows/application-management/app-v/appv-auto-provision-a-vm)
* Content Source: [windows/application-management/app-v/appv-auto-provision-a-vm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/app-v/appv-auto-provision-a-vm.md)
* Product: **w10**
* GitHub Login: @eross-msft
* Microsoft Alias: **elizapo**

**Comment by Reittier** [comment]
Convert-WindowsImage -SourcePath "<path_to_iso_image>" -VHDFormat "VHD" -VHDPartitionStyle "MBR"

Does not work for me. Getting in a boot error later when trying to boot ah VM (HyperV Host Windows 10 1809)

Connect-AppvSequencerVM -VMName "<name_of_vm>" -ADKPath "<path_to_adk_install_folder>"

Does'nt work either on 1809 because there is no Parameter "-ADKPath" in CMDlet Connect-AppVSequencerVM

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@gprosch - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@gprosch - I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
