### ISSUE TITLE
Surface Hub Recovery Tool through a corporate Proxy Server

### ISSUE THREAD

**Issue by NHSDRZN** [MicrosoftDocs/windows-itpro-docs#2320]
Hi

Can you advise on what URL and network ports need to be allowed through a proxy to enable this tool to work within our corporate estate?

Cheers

Richard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e78f073c-9f6b-b9d2-cd94-0a31998f10d9
* Version Independent ID: 5beaeca4-3d07-c65c-018b-a88cda5ceb9a
* Content: [Using the Surface Hub Recovery Tool](https://docs.microsoft.com/en-us/surface-hub/surface-hub-recovery-tool)
* Content Source: [devices/surface-hub/surface-hub-recovery-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/surface-hub-recovery-tool.md)
* Product: **surface-hub**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@NHSDRZN I checked with the engineering team, and they believe the only port that needs to be opened is 8080. They said the Surface Hub Recovery Tool contacts the service through port 8080 and the image URL is https://shubcloudrecoverystorage.blob.core.windows.net/image/SurfaceHubRecoveryImage.wim

**Comment by EricSP2** [comment]
@JDECSERMS Please provide an updated link.

Also once I have the WIM, from which folder does the recovery tool read from?

It's such a nuisance that MS is not providing direct link access to the files or make a complete offline installer available.

**Comment by EricSP2** [comment]
I've been trying to download the WIM through the recovery tool on a laptop connected straight up to the internet, it gets to 80% and then fails. The worse part is that your utility is not smart enough to offer a restart and RESUME download feature. Instead, once it fails the binaries are wiped and it retries from 0%

Who designed this? :/

**Comment by EricSP2** [comment]
@mypil 

This case should be re-opened and a permanent solution should be put in place with a static URL to the latest wim or modify the tool to resume instead of restarting a whole download.

Maybe even a torrent option?
