### ISSUE TITLE
CSP documentation comparison

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#2322]
This CSP reads oddly, does not appear to offer the same template of information as found in other CSPs. 

First, in describing the policy control, "Allows or Disallows" is not proper, you would say Enable/Disable this policy component. 

There is no Data type is presented.. (although 0 or 1 would be BOOLEAN) The admin is left guessing a bit.. vs other CSPs clearly listing the fact of what data type. 

No affirmation if GET is a supported Data type? so I am guessing it may be?

On Cyphersuite, A semicolon list is not a data type. I'm going to guess and say this should be listed as String, or String XML.  this also does not list if GET is supported function. 

Additionally, other CSPs provide specific SCOPE/Path information on each CSP, providing User, device, or vendor scope data,

That path is represented by:
./Device/Vendor/MSFT/Policy/

To confirm, does this CSP support "Device and Vendor", as Surface HUB natively does not support "user" I am confident that isn't going to be an option, but I am curious if either device and vendor may be used separately. 

Can someone please clarify the detail?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b290a291-ccb6-953f-0679-2a56a927620e
* Version Independent ID: 6a86d25c-12ea-1f8d-2758-4d13352e7718
* Content: [Policy CSP - Cryptography](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-cryptography)
* Content Source: [windows/client-management/mdm/policy-csp-cryptography.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-cryptography.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by Tdiwestyguy** [comment]
I would also add that all other CSPs follow SCOPE, providing User, device, or vendor scope data, 

That path is represented by:

./Device/Vendor/MSFT/Policy/

So, does this CSP support Device and Vendor???  Missing data.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
@Tdiwestyguy : Please notice that the first of the 2 Cryptography policies is named **AllowFipsAlgorithmPolicy** -- therefore the values [ 0 (default) – Not allowed. || 1– Allowed. ] works just OK for this specific policy.

(I don't know much about the rest of the page, but I presume that experienced admins will find the information sufficient for normal use.)

**Comment by e0i** [comment]
@Tdiwestyguy 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by e0i** [comment]
@Tdiwestyguy 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
