### ISSUE TITLE
Credential guard enabled but not running...

### ISSUE THREAD

**Issue by haseeb1986** [MicrosoftDocs/windows-itpro-docs#2327]
Credential guard enabled but not running...

I'm deploying Credential Guard to a VM for testing purpose but I'm having a hard time getting it working. I've enabled CG via GPO's and by using the hardware readiness tool, both giving me the same result.
Msinfo32 displays ‘Device Guard Virtualisation based security’ as ‘Enabled but not running’ and ‘Devices Guard Security Services Configured’ displays ‘Credential Guard’ Unfortunately I have no LsaIso.exe process running. 
Trawling through the event viewer I see 2 errors relating to CG;
Event ID 15: Windows Defender Credential Guard (LsaIso.exe) is configured but the secure kernel is not running; continuing without Windows Defender Credential Guard.
And
Event ID 14: Credential Guard (Lsalso.exe) configuration: 0x2, 0

Strangely after the odd reboot I’ll get a 0x0, 0 returned for Event ID 14 but still no Lsalso.exe process. Readiness tool gives me full green and passes everything when I do a ‘-GC –Capable’ and nothing gets highlighted when I run a ‘-GC –Enable’

I’m doing this on Win10 1607. Any ideas? Any help greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @haseeb1986  thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

**Comment by e0i** [comment]
@officedocsbot close
