### ISSUE TITLE
Hybrid AAD failing, not able to join On-Premises Domain.

### ISSUE THREAD

**Issue by byrusrikar** [MicrosoftDocs/windows-itpro-docs#2333]
Hi, 
We have configured Hybrid AAD profile & when the machine is trying to enroll and join the On-prem AD, we are getting an error:80004005.
It is working fine when connected to Organisation network. 
on Public network , on wi-fi it is failing.

**Comment by andreabichsel** [comment]
Please try https://support.microsoft.com/en-us to help resolve this issue.
