### ISSUE TITLE
Necessity of drivers support not clear

### ISSUE THREAD

**Issue by lexios** [MicrosoftDocs/windows-itpro-docs#2335]
It needs to be made cleared if a non-compliant driver would block the Kernel DMA Protection to be enabled.
As a reader, I understand that this is only a matter of:

1. OS version
2. Firmware

If both of the above are compliant, then the setting should show as ON irrespective of the drivers in use.

Is this correct?

Another thing that is not made clear is if a computer can be firmware updated to support this functionality or this if this functionality is hardware embedded and can't change.

This is needed so to prepare for the possible mitigation paths.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b83e95-63de-87c5-929c-d5f25e33d124
* Version Independent ID: 743ead3f-b4a5-1589-6577-e1d12aaa1b92
* Content: [Kernel DMA Protection for Thunderbolt™ 3 (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/kernel-dma-protection-for-thunderbolt)
* Content Source: [windows/security/information-protection/kernel-dma-protection-for-thunderbolt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/kernel-dma-protection-for-thunderbolt.md)
* Product: **w10**
* GitHub Login: @AaDake
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@lexios - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @lexios , Thank you for sharing feedback on the document. For settings to show as ON depends on the device drivers as well as it is not universally supported by all Devices. Please see https://docs.microsoft.com/en-us/windows/security/information-protection/kernel-dma-protection-for-thunderbolt#how-can-i-check-if-a-certain-driver-supports-dma-remapping for details.

For your second query, it's not only dependent on firmware. The devices drivers should be in compliance for this to work. 

Thanks.

**Comment by mypil** [comment]
@lexios - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
