### ISSUE TITLE
Incomplete Content

### ISSUE THREAD

**Issue by zakgodwin** [MicrosoftDocs/windows-itpro-docs#2337]
This content looks like the structure of an article and appears to be missing content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d745280-391c-4f6d-6a35-7125fa263548
* Version Independent ID: 0ccd8add-b5fb-469c-509e-e009c43a00ac
* Content: [Set up Delivery Optimization](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization-setup)
* Content Source: [windows/deployment/update/waas-delivery-optimization-setup.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-delivery-optimization-setup.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by e0i** [comment]
Hello, @zakgodwin The content you have mentioned has been removed. Thank you for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
