### ISSUE TITLE
Windows Hello is not two factor Authentication.

### ISSUE THREAD

**Issue by working4free** [MicrosoftDocs/windows-itpro-docs#2340]
How can anyone in the security field call Windows Hello as two factor authentication when the item you are authenticating on is being used at part of the definition?  Two factor authentication is defined by having two of the three of the the following:  1) something you have, something you are, something you know.  Microsoft (I suspect the Market Team) is trying to pass off that having the computer which is setup with Windows Hello is "something you have".  Windows Hello does create certificates between the computer and identify source (such as AzureAD).  Then it stores the private key for this trust in the hardware TPM of the computer.  This is all great as the TPM (2.0) is an ISO 11889 international standard for secure cryptoprocessor.  Microsoft is trying to say because of this certificate this is "something you have".  However this certificate, which is stored in the TPM of the local machine is simply protected by either a pin or a bio-metric login of a fingerprint or facial recognition.  They further like to make it seem like the "Pin" is not a password and that its way more secure then a user account password since its only stored on this computer and is useless in logging into a centralized authority like AzureAD.  So we now have a computer which can be successfully logged into if the user has the correct "PIN" or bio-metrics as that is all that is required  to allow the certificate which is stored in the TPM to be read and used by the computer to authenticate this user/device with an Identity server to allow access to resources / data both on this computer and in the cloud (O365).  The only real difference between this setup and logging in with a traditional username and password,  is that the password hash is not sent over the wire but instead a signed authorization signed by pre-established trusted certificate.  This is definitely a step in the right direction but this private key must be secured by two-factor authentication.  In my opinion this would be a great solution if Windows Hello required a "PIN" or bio-metrics and it utilized Microsoft Authentication app that lives on my smart phone.  This would fulfill the definition of two factor as Microsoft Authenticator is definitely something you have.  This is no different than your ATM card (with a smart chip) and your PIN.  You go to an ATM to get money and you must have both an Valid ATM card and your PIN.  You can't get money if all you have is the ATM machine and your PIN, you also need the ATM card.  Something you have and something you know.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f8d124-fd83-f3ab-8249-d11d5967460f
* Version Independent ID: eace54c8-04c9-a717-5ecd-2be8f485cc93
* Content: [Windows Hello for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-overview)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-overview.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@working4free  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@working4free  Thank you for your feedback on this document. I would suggest you to please pass your feedback using our feedback channels so that it can be routed to the right team. If you think there is any modification required in this document, please feel free to let us know. 

@mypil can help you with how you can share your feedback using our feedback channels. 

Thanks.

**Comment by mypil** [comment]
@working4free - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
