### ISSUE TITLE
Registry path does not exist

### ISSUE THREAD

**Issue by mathit1** [MicrosoftDocs/windows-itpro-docs#2342]
The registry path (HKLM\SOFTWARE\Policies\Microsoft\MicrosoftEdge\TabPreloader) does not exist in Windows 1809 17763.194  Please fix the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e25cdec-6b2f-2e44-6512-83b13d13ff51
* Version Independent ID: f97436ae-01fc-a3bb-d0e8-2b20265ebc56
* Content: [Microsoft Edge - Prelaunch and tab preload group policies](https://docs.microsoft.com/en-us/microsoft-edge/deploy/group-policies/prelaunch-preload-gp)
* Content Source: [browsers/edge/group-policies/prelaunch-preload-gp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/group-policies/prelaunch-preload-gp.md)
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by illfated** [comment]
It is also interesting to see that in Windows 10 version 1809, the local registry contains the following key:

`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\default\Browser\AllowTabPreloading\GPBlockingRegKeyPath` (REG_SZ)

Content: `Software\Policies\Microsoft\MicrosoftEdge\TabPreloader`

**Comment by mathit1** [comment]
I found a solution that works for me.  Here's a link to two registry hacks that will enable/disable Edge preloading: https://www.tenforums.com/tutorials/115545-enable-disable-microsoft-edge-pre-launching-windows-10-a.html

**Comment by strecz** [comment]
How to disable via the Windows Registry
(Recommended only for advanced users)

DISCLAIMER: This is for advanced PC users only and those who are experienced in editing the registry. You are editing your registry at your own risk. If you decide to follow the steps below, we recommend that your registry is backed up before proceeding.

1.) Click the Windows icon, type ‘regedit’ and hit enter to open the Registry Editor
2.) Confirm any UAC prompts that may be displayed
3.) To disable pre-loading of Microsoft Edge:
    a.) Navigate to the following location:
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\MicrosoftEdge\Main
    b.) Right-click on the ‘Main’ folder and select ‘New – DWORD (32-bit) Value’
    c.) Name it AllowPrelaunch
    d.) Double-click on ‘AllowPrelaunch’ and ensure its value is set to 0
4.) To disable pre-loading of New Tab Page and Start Content of Microsoft Edge:
    a.) Navigate to the following location:
        HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\MicrosoftEdge\TabPreloader
    b.) Right-click on the ‘TabPreloader’ folder and select ‘New – DWORD (32-bit) Value’
    c.) Name it AllowTabPreloading
    d.) Double-click on ‘Allow TabPreloading’ and ensure its value is set to 0
5.) Once complete, you will need to log out and back in again for the changes to take effect

Pasted from <From https://www.ccleaner.com/docs/ccleaner/troubleshooting/how-to-disable-pre-launching-and-pre-loading-so-ccleaner-can-fully-clean-edge>

**Comment by e0i** [comment]
@mathit1 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
