### ISSUE TITLE
Needs updating

### ISSUE THREAD

**Issue by HughR** [MicrosoftDocs/windows-itpro-docs#2343]
Window Update to 1809 failed with this code: 0x80244018
This does not seem to be covered.

I can tell that this is a Win32 code.  From hunting around elsewhere, I think that the facility is Windows Update, and that the code might be CO_E_CREATEPROCESS_FAILURE.

(This decoding doesn't really help me resolve the problem.  What process failed to start?  Why?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 528014e0-02e5-2d77-a229-4895731bb872
* Version Independent ID: 4f46b620-e345-c9e4-70fa-ae4f5a8e48b9
* Content: [Resolution procedures - Windows IT Pro](https://docs.microsoft.com/en-us/windows/deployment/upgrade/resolution-procedures#0x800xxxxx)
* Content Source: [windows/deployment/upgrade/resolution-procedures.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/resolution-procedures.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@HughR - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@HughR - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
