### ISSUE TITLE
SeDebugPrivilege should be granted to Administrators

### ISSUE THREAD

**Issue by AaronMargosis** [MicrosoftDocs/windows-itpro-docs#2344]
In the past we sometimes recommended that SeDebugPrivilege could be granted to no one. That hasn't been our recommendation for quite some time. We recommend that SeDebugPrivilege always be granted to Administrators, and only to Administrators.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c488fade-4ba4-5399-ef0f-09bb74c3ee6a
* Version Independent ID: 3a3b9670-9990-4498-60c0-e027c22384c3
* Content: [4672(S) Special privileges assigned to new logon. (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4672#security-monitoring-recommendations)
* Content Source: [windows/security/threat-protection/auditing/event-4672.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/event-4672.md)
* Product: **w10**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@AaronMargosis  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @AaronMargosis As suggested, i have checked and confirmed that you have instructed in the doc to assign SeDebugPrivilege to Administrators. Please see attached screenshot.

![image](https://user-images.githubusercontent.com/47118050/58208376-0b062400-7cfe-11e9-9054-c00cb1140fd5.png)

If there is any further suggestion, please feel free to let me know. I will be happy to add that up.

Thanks.

**Comment by mypil** [comment]
@AaronMargosis  - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
