### ISSUE TITLE
format

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#2346]
Hi, I am unsure/unclear and confused by the portrayal of "…" is about when looking at logical URI paths in this article. 

on URI #15-16 you guys deviate from standard URI template (A styleguide used in almost every Microsoft based CSP with URI paths). 

I'd say for readability, the "…" should be removed, and replaced with the actual path. If there is a grouping, then it is a logical one by subgroup of policy. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738435ba-71e3-0b74-b091-7d6f80c7ceb1
* Version Independent ID: 5c4c0d80-bea5-a015-cf50-5586887fe5d0
* Content: [EnterpriseModernAppManagement CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/enterprisemodernappmanagement-csp)
* Content Source: [windows/client-management/mdm/enterprisemodernappmanagement-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enterprisemodernappmanagement-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Tdiwestyguy - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @Tdiwestyguy Thank you for you feedback on the document. I have checked and confirmed that all of the URI paths are mentioned in the doc. 

If there is any additional feedback regarding doc improvement, please feel free to share. 

Thanks.

**Comment by mypil** [comment]
@Tdiwestyguy  - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
