### ISSUE TITLE
Does this work for anyone?

### ISSUE THREAD

**Issue by reduakm** [MicrosoftDocs/windows-itpro-docs#2347]
I set this policy for Windows 1803 and find that it makes no difference, along with most of the other defender "hiding" policies. Did these only work with 1709 or something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5470b81-f99b-d7d7-39fc-b18d2e845c9b
* Version Independent ID: a15e5508-fcfb-7a76-2c18-50e4d65268bc
* Content: [Family options in the Windows Security app](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-security-center/wdsc-family-options)
* Content Source: [windows/security/threat-protection/windows-defender-security-center/wdsc-family-options.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-security-center/wdsc-family-options.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@reduakm - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @reduakm , This policy works on all operating systems from 1709 onwards. Please ensure that you need to log off and login back or you need to run gpupdate /force command once you have applied the settings in group policy.

Thanks.

**Comment by mypil** [comment]
@reduakm - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
