### ISSUE TITLE
Using Groups

### ISSUE THREAD

**Issue by bmwilson1978** [MicrosoftDocs/windows-itpro-docs#2348]
Just a couple of points which I feel need to be added to the Kiosk mode documentation:

1. If you use an Azure Active Directory Group in the config for group accounts XML, the device must have internet access for those users contained within that group to sign-in on that device - if not they will be signed out immediately. 

2. If you use a Local Group, in the config for group accounts XML, Azure AD Accounts added to that Local Group will be ignored  and will not have the kiosk settings applied (even if you target the local Users group).

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78038d67-04a1-f4ae-6a69-98e157688a31
* Version Independent ID: c86b4460-e8be-8537-a6c8-3cb094ef14a3
* Content: [Set up a multi-app kiosk  (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps#configure-a-kiosk-in-microsoft-intune)
* Content Source: [windows/configuration/lock-down-windows-10-to-specific-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/lock-down-windows-10-to-specific-apps.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@bmwilson1978 Sorry for the delay in replying - the holidays made it challenging to contact folks. Finally I was able to get confirmation from the engineering team on your suggestions, and I'll be adding them to the topic. Thanks for taking the time to suggest these improvements!

**Comment by fergo99** [comment]
I have a similar issues using AD groups accounts.   The users signs on and then off immediately.  I have a case open with MS for over 2 months with no resolution.

**Comment by bmwilson1978** [comment]
@fergo99: Is your user is an AAD user and also a member of the group you specified in the Type="AzureActiveDirectoryGroup" XML?  If so, ensure the device has internet connectivity (i.e. airplane is not enabled).

**Comment by fergo99** [comment]
I have this issue with both an AAD group and an AD group.  In both cases the AD account has internet access.  

Sent from Yahoo Mail on Android 
 
  On Tue, Jan 8, 2019 at 12:08 PM, bmwilson1978<notifications@github.com> wrote:   
@fergo99: Is your user is an AAD user and also a member of the group you specified in the Type="AzureActiveDirectoryGroup" XML? If so, ensure the device has internet connectivity (i.e. airplane is not enabled).

**Comment by fcsbraveheart** [comment]
@fergo99 I have the exact same issue - did you ever get to the bottom of this one?
