### ISSUE TITLE
PowerShell Command for installing UE-V Templates

### ISSUE THREAD

**Issue by Theragus** [MicrosoftDocs/windows-itpro-docs#2349]
'Get-childItem c:\programdata\Microsoft\UEV\InboxTemplates*.xml
Returns no Items for me.

Shouldn't this be c:\programdata\Microsoft\UEV\InboxTemplates\*.xml ? (Backslash Missing)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f735c74e-f4aa-9839-81fe-050782e09e22
* Version Independent ID: 94ceabf5-70ec-8a81-6eee-8f9aa2671ad6
* Content: [Get Started with UE-V](https://docs.microsoft.com/en-us/windows/configuration/ue-v/uev-getting-started#step-1-confirm-prerequisites)
* Content Source: [windows/configuration/ue-v/uev-getting-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/ue-v/uev-getting-started.md)
* Product: **w10**
* GitHub Login: @MaggiePucciEvans
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@Theragus Thanks for catching that, I'll get it fixed.
