### ISSUE TITLE
There is no such global user or group: AzureAD\{user}

### ISSUE THREAD

**Issue by samyun** [MicrosoftDocs/windows-itpro-docs#2351]
&gt; net localgroup "Remote Desktop Users" /add "AzureAD\FirstnameLastname"

Is this still valid in 1809? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc#)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by billgatesfan** [comment]
I could not start anything with "AzureAD\FirstnameLastname" (I tested only in 1809).
But what worked, is following formatting : 

 /add "AzureAD\the-UPN-attribute-of-your-user"
 /add "the-UPN-attribute-of-your-user"
 /add "the-sAMAccountName-attribute-of-your-user"

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@samyun - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by leonbrag** [comment]
I cannot get it to work on 1809. VM is joined Azure AD:

C:\Users\foo>net localgroup "Remote Desktop Users" /add "AzureAD\testuser2@foo.onmicrosoft.com"

There is no such global user or group: AzureAD\testuser2@foo.onmicrosoft.com.

**Comment by illfated** [comment]
You may want to open a new issue ticket and link back to this one (although one of the Microsoft Docs team members will comment on that later, which ever they recommend).
