### ISSUE TITLE
CP10 Network Chanel

### ISSUE THREAD

**Issue by namlongtvmedia** [MicrosoftDocs/windows-itpro-docs#2352]
http://cp10.com
networkchanel@cp10.com
hoangnamlongip@gmail.com
nguyenhoangson041186@gmail.com
-----------------------------------------
Hoàng Nam Long

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d602e13e-c1af-958b-8574-a020c49a4b89
* Version Independent ID: f77197b5-cabd-25e7-473a-f4aa663ff6e9
* Content: [What's new in Windows 10 deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-whats-new#the-modern-desktop-deployment-center)
* Content Source: [windows/deployment/deploy-whats-new.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-whats-new.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
The above post does not appear to report any valid issue or request.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@namlongtvmedia - We would like to get some details from you so we can investigate. Can you please share what specific issue you have with this article? 

Thank you.

**Comment by illfated** [comment]
To be honest, the issue post from @namlongtvmedia does not appear to be a reasonable attempt to report anything at all, it looks a lot more like self-promoting spam to "leave his mark" on these pages on Github. There is not even an attempt to write something in Vietnamese or other localized language. Any other project would close this issue ticket and label it [invalid input] or [spam report] or something similar.

**Comment by mypil** [comment]
@illfated - Thanks for your inputs.

@namlongtvmedia - We will proceed to close this issue since it lacks details and we did not get any response from you.  Please feel free to open a new issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
