### ISSUE TITLE
Better way to share Windows release information

### ISSUE THREAD

**Issue by am11** [MicrosoftDocs/windows-itpro-docs#2353]
In order to programmatically get list of all Windows versions, one can parse the HTML from https://winreleaseinfoprod.blob.core.windows.net/winreleaseinfoprod/en-US.html (which [release-information.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/hub/release-information.md) references). Another was is to fetch it from unofficial source like https://buildfeed.net/rss/version/, where human manually creates entries via a [webpage](https://gitlab.com/buildfeed/BuildFeed/blob/master/BuildFeed/Views/front/editBuild.cshtml).

Is it possible that the official winreleaseinfoprod blob provide us an always-updated JSON version file which downstream tools can easily parse and answer the questions like "What is the latest insider build version of Windows 10?" (ans: `10.0.18298.1000`, the granularity which HTML page from winreleaseinfoprod blob does not provide today).

The list could also be maintained as fully automated [GitHub releases](https://help.github.com/articles/about-releases/), where the Windows build slave could create post-release entries by making a simple HTTP POST call to this GitHub REST API: https://developer.github.com/v3/repos/releases/#create-a-release. With this approach, downstream consumers would be able to retrieve the information from another GitHub API, for example:

```powershell
#!/usr/bin/env powershell

# get latest release version of microsoft/vswhere
~> $(Invoke-WebRequest https://api.github.com/repos/Microsoft/vswhere/releases/latest | `
    ConvertFrom-Json) | ForEach-Object { $_.tag_name }

2.5.2

# get latest release version of nodejs/node
~> $(Invoke-WebRequest https://api.github.com/repos/nodejs/node/releases/latest | `
    ConvertFrom-Json) | ForEach-Object { $_.tag_name }

v11.4.0

# get latest prerelease version of dotnet/cli
~> $(Invoke-WebRequest https://api.github.com/repos/dotnet/cli/releases | `
    ConvertFrom-Json) | Where-Object { $_.prerelease } | Sort-Object { $_.tag_name } `
    -Descending | Select-Object -First 1 | ForEach-Object { $_.tag_name }

v3.0.100-preview.18578.3
```

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@am11 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by am11** [comment]
Here is the MS document link: https://docs.microsoft.com/en-us/windows/release-information/ and the corresponding markdown file was moved (from `windows/hub/release-information.md` to) https://github.com/MicrosoftDocs/windows-itpro-docs/blob/30ab9bb02e/windows/release-information/index.md.
Thank you! :)

**Comment by joinimran** [comment]
@am11 What I understand from your question is that you want to pull the release information from the mentioned sources using JSON query so that it can be used for any other purposes. This entirely looks like a feature request and I would suggest you open a new feature request so that it can be routed to the correct team. 
If there is any modification required in the support doc, please feel free to let us know. We will be happy to help you out.

@mypil can guide you how you can open a feature request so that you can pull this information using JSON query.

Thanks.

**Comment by mypil** [comment]
@am11 - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
