### ISSUE TITLE
How to use "Microsoft Remote Desktop" for Mac in this context

### ISSUE THREAD

**Issue by Arash-Sabet** [MicrosoftDocs/windows-itpro-docs#2354]
I am using Microsoft Remote Desktop app for Mac to try to RDP to a Windows 10 which is connected to Azure AD. I am unable to establish the connection at all. Any links to guidelines to help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@Arash-Sabet I hope this might help you: https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac
