### ISSUE TITLE
unlock win 10

### ISSUE THREAD

**Issue by splendide2018** [MicrosoftDocs/windows-itpro-docs#2357]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05519993-ce58-9656-a7fa-fced61dda068
* Version Independent ID: 5186f2a1-4214-e419-b0e5-33b618afcbdb
* Content: [4801(S) The workstation was unlocked. (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4801)
* Content Source: [windows/security/threat-protection/auditing/event-4801.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/event-4801.md)
* Product: **w10**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

**Comment by illfated** [comment]
@splendide2018 : you may want to add a description in your issue text if you want this issue kept open. Otherwise, it looks like it should be closed due to no issue or request reported.
