### ISSUE TITLE
Great explanations

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#2358]
Thanks a lot sir,
Today I learnt new commands for mbr2gpt.exe, I noted your article into notepad for future reference

Sir will you able  to give  more command  which is  used convert validate, convert, logs enabled and allowfullos 

according to me, command like below 
Mbr2gpt.exe /Validate /Allowfullos /Disk:0 /Convert /Logs:D:\mbrconvert.log 

Please evaluate  above command , and tell  whether its  correct or not . If not  means, give correct  command.

Thanking you 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73c22f0-cb0d-e34b-29d8-06829b86784f
* Version Independent ID: 083115ed-f1be-e962-5b0e-5079dec37353
* Content: [MBR2GPT](https://docs.microsoft.com/en-us/windows/deployment/mbr-to-gpt)
* Content Source: [windows/deployment/mbr-to-gpt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/mbr-to-gpt.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@RAJU2529  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by RAJU2529** [comment]
Thanks madam. I keep waiting for reply from

**Comment by MaratMussabekov** [comment]
Dear @RAJU2529 ,
unfortunately this command is not correct, you cannot use both "/Validate" and "/Convert" operators in the single command, you need to choose one.
Also, /Logs:D:\mbrconvert.log is incorrect, as it is path to file, not to folder. Operator "/Logs" should be used to specify folder path, so I would recommend to use something like "/Logs:D:\MBRConvertLogs"

If you need to convert, please use
Mbr2gpt.exe /Convert  /Disk:0  /Logs:D:\MBRConvertLogs /Allowfullos

Thank you

**Comment by MaratMussabekov** [comment]
Also, I forgot to mention, that when you specify path for the logs folder, make sure that the path is already exists, it states in the article: "If specified, the directory must already exist, it will not be automatically created or overwritten"

Thank you

**Comment by mypil** [comment]
@RAJU2529 - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by RAJU2529** [comment]
issues has solved. moreover I don't have project conformed to check reality. At this time my suggestion is that Mr MaratMussabekov was given more commands and clear explanations, so I would request the authors to add his explanations in this article and allow him as a one of the contributor

**Comment by RAJU2529** [comment]
Now you can cLose this issue . I feel very happy to discuss those techNical article writers with different knowledge.  Here is the stage to express their kNowledge to  all over the world article writers and learning new things from them

**Comment by mypil** [comment]
@officedocsbot close
