### ISSUE TITLE
Is there any way to hide "Change Account" during setup?

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/windows-itpro-docs#2359]
I notice you can disable local admin capabilities on the device, but if the user chooses "Change account" on the sign-in page, they can choose to Azure AD-join the device, and then the device does not go through its normal AutoPilot setup - so the user is still a local admin on the box, and they see the EULA. 

Is there any way to hide the "Change Account" function during setup? It also would be helpful as an anti-theft measure for company devices. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ded38a54-e056-3af1-51ea-58b90607c45e
* Version Independent ID: 8c3e2f28-a8a8-2bf4-87cf-08d54c890ae2
* Content: [Configure Autopilot profiles](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/profiles)
* Content Source: [windows/deployment/windows-autopilot/profiles.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/profiles.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@thedrum808  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@thedrum808 There is a way to do that starting with Windows 10 1809 or later:

https://docs.microsoft.com/en-us/intune/enrollment-autopilot

"Hide change account options (requires Windows 10, version 1809 or later): Choose Hide to prevent change account options from displaying on the company sign-in and domain error pages. This option requires company branding to be configured in Azure Active Directory."

**Comment by mypil** [comment]
@thedrum808 - From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
