### ISSUE TITLE
Bitlocker Recovery - Re: Determine the root cause of the recovery

### ISSUE THREAD

**Issue by ricofox959** [MicrosoftDocs/windows-itpro-docs#2369]
This article is great, but it would be greater if some references were provided of Event Log EventIDs and Log Names worth reviewing. In my experience there are many to look at like TPM, Group Policy and of course MBAM. But I think a basic set to start with would be a good section to add. I myself have been looking a lot at the System log and am working to create a FilterHashTable and FilterXML for the Get-WinEvent PowerShell Command-let. Thank you for reading this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e21c26e-1320-04e1-d103-e64751235f9f
* Version Independent ID: 48b4da0f-2bb0-98d8-20f9-acd30a0e4a34
* Content: [BitLocker recovery guide (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-recovery-guide-plan#bkmk-planningpostrecovery)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-recovery-guide-plan.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-recovery-guide-plan.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ricofox959  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@ricofox959 I think what you are doing, meaning exploring what you can acomplish with Powershell is the best way forward. It's really hard to give a list of EvendIDs and Sources to look at in Event Viewer, keeping in mind the wide range of issues that you could encounter and the architectural differences between environments.

What i would advise is to look at **System Log** and **Application Log** (what i guess you are already doing) but also at **Application and Services Logs > Microsoft > Windows > BitLocker-API**

and to use the following cmdlet to filter these out after relevant keywords such as Bitlocker:

**Get-WinEvent -FilterHashtable @{LogName='System'} | Where-Object -Property Message -Match 'BitLocker'**

- replace System with the above mentioned logs.
- replace BitLocker with other relevant keywords.

**Comment by mypil** [comment]
@ricofox959 - From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
