### ISSUE TITLE
Kiosk Browser with assigned access starts new instances every few minutes without closing the old instance

### ISSUE THREAD

**Issue by linusbrolin** [MicrosoftDocs/windows-itpro-docs#2370]
I have tried to get the Kiosk Browser to work on Windows 10 with the latest 1809 update.
When I run the Kiosk Browser with assigned access, it will start a new instance of the Kiosk Browser every few minutes, but the old instance will not be closed.
After a while, this will cause the active instance to not load and instead be stuck with a blue background and white spinner.

This happens whether the "restart on idle" setting is in use or not.
It seems to have nothing to do with that.

**Comment by jdeckerms** [comment]
@linusbrolin You should report that as a bug for the Kiosk Browser app in the Feedback Hub.
