### ISSUE TITLE
SYSTEM account needs clarity

### ISSUE THREAD

**Issue by CThreadgill** [MicrosoftDocs/windows-itpro-docs#2371]
Need to clarify that the scheduled task must use the 'BUILTIN\SYSTEM' account.  By default it was trying to use 'NT AUTHORITY\SYSTEM' which did not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27dbd025-8239-9847-b07e-378ca87d2d75
* Version Independent ID: 4b0e4ac7-a608-7c62-dcd4-2db628b3f67a
* Content: [Onboard Windows 10 machines using Group Policy to Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-endpoints-gp-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/configure-endpoints-gp-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/configure-endpoints-gp-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Thank you for your feedback. We'll work on it.

**Comment by thesultan2019** [comment]
After loosing a lot of time i found this topic https://maddog2050.wordpress.com/2014/09/11/gpo-issue-deploying-a-scheduled-task-running-as-system/ 

I followed instructions but not better for me. I replace system account (builtin in for computers) by domain administrator and it seems to work

Hope it help

**Comment by egallagh** [comment]
I do not recommend the use of Domain Administrator accounts because of the security risks associated with its use in a distributed automated process.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@CThreadgill - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
