### ISSUE TITLE
Registry keys types

### ISSUE THREAD

**Issue by acepace** [MicrosoftDocs/windows-itpro-docs#2373]
Could you document the type of the registry values listed? DWORD, STRING?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8927df09-e9aa-8c40-290d-0ca7d86ec4e2
* Version Independent ID: ca67bcfc-6120-d6ca-290b-1a7822494c73
* Content: [Frequently asked questions - Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by zukedgwa** [comment]
The 3 regkeys are DWORDS

**Comment by Justinha** [comment]
sorry to miss this @acepace and thanks for the answer @zukedgwa. I added it just now and should publish later today.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@acepace 

We are marking this issue as resolved as it seems that the issue has been addressed via the following commit and has been published: https://github.com/MicrosoftDocs/windows-itpro-docs/commit/a58b52cbf560d040a6f4364b107b724cd4ecba97

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
