### ISSUE TITLE
AllowAzureRMSForEDP mandatory to set up Azure Rights Management with WIP?

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/windows-itpro-docs#2375]
If we enable the "Use Azure RMS for WIP" option, do we still have to deploy the AllowAzureRMSForEDP configuration policy? I don't see the point to enable it within WIP if you still have to enable it using an OMA-URI policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df27add-73fe-4f0b-7e30-face0f95cda3
* Version Independent ID: 3ec647d9-3470-8d8b-a941-d56f6522a35e
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure#choose-your-optional-wip-related-settings)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by lightupdifire** [comment]
@Martony78,
I did deploy WIP policy in 2x tenants, I see that "AllowAzureRMSForEDP" is applied automatically, so no need to set it up via OMA-URI.
You can check it via REGEDIT after you push WIP policy to clean PC:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\current\device\DataProtection

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @Martony78 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
