### ISSUE TITLE
i lose my bitlocker key recovery

### ISSUE THREAD

**Issue by randykun99** [MicrosoftDocs/windows-itpro-docs#2377]
can u help me...i cant open my folder because i lose my recovery key..
my id bitlocker is 7FE7A5BB-8D70-4720-8D5D-B8F6-7CB5903A

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6603248-9940-56fe-4aaf-80b4c4d6bf3f
* Version Independent ID: 50ee132c-ef6e-efa1-800b-de49df6a3c2e
* Content: [How to Configure the Self-Service Portal When Client Computers Cannot Access the Microsoft Content Delivery Network](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/how-to-configure-the-self-service-portal-when-client-computers-cannot-access-the-microsoft-content-delivery-network#feedback)
* Content Source: [mdop/mbam-v25/how-to-configure-the-self-service-portal-when-client-computers-cannot-access-the-microsoft-content-delivery-network.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/how-to-configure-the-self-service-portal-when-client-computers-cannot-access-the-microsoft-content-delivery-network.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by andreabichsel** [comment]
You can get a recovery key with your BitLocker ID here: https://bitlockerrecovery/SelfService
