### ISSUE TITLE
Windows build required

### ISSUE THREAD

**Issue by TylerRosolowski** [MicrosoftDocs/windows-itpro-docs#2382]
This documentation should really include the Windows 10 Build required for AutoPilot. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc999894-2a0a-bc87-7fd7-97df5f1fd04e
* Version Independent ID: ad68f62a-6bf0-5f5f-bb07-f64afe68fd10
* Content: [Windows Autopilot requirements](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-requirements)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-autopilot-requirements.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@TylerRosolowski Thank you for providing feedback.

It seems that the issue have been resolved by the following commits:

[3a0fcb2](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/3a0fcb21722f9d7572ab75793bd30ba6552f8a41#diff-9309861f761730800fcad5490f0a51e7R25), [7d2e76c](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/7d2e76cb263708b552cd519641b5f052e2502fb6#diff-9309861f761730800fcad5490f0a51e7R18)

Feel free to re-open this issue if you still cannot find what you are looking for.

**Comment by e0i** [comment]
@officedocsbot close
