### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by PSathwikV37** [MicrosoftDocs/windows-itpro-docs#2383]
I wan to build custom configuration service provider. This document should help me doing that.
However, I don't see any information on:
1. How to setup project?
2. What headers files to be used?
3. How to do it in .NET?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feef5e8e-d7a0-b88b-e55e-092ed2aea9a2
* Version Independent ID: 09abb3a6-853f-8c9a-5acf-81f7d965eaba
* Content: [Samples for writing a custom configuration service provider](https://docs.microsoft.com/en-us/windows/client-management/mdm/samples-for-writing-a-custom-configuration-service-provider)
* Content Source: [windows/client-management/mdm/samples-for-writing-a-custom-configuration-service-provider.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/samples-for-writing-a-custom-configuration-service-provider.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by jdeckerms** [comment]
@PSathwikV37 Thanks for your suggestion, I've added it to the list of improvements needed for this article.
