### ISSUE TITLE
Where is the prevention method

### ISSUE THREAD

**Issue by TimTCM** [MicrosoftDocs/windows-itpro-docs#2384]
Hi,

I read several times in this that "You can also configure Microsoft Edge to prevent from pre-launching" or the tab pre-loading. How? This doesn't say where, nor link to somewhere that does.

I'm trying to use CCleaner to clean my drive, and this is preventing it from working.

Thank you,
Tim
15,180 days

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e25cdec-6b2f-2e44-6512-83b13d13ff51
* Version Independent ID: f97436ae-01fc-a3bb-d0e8-2b20265ebc56
* Content: [Microsoft Edge - Prelaunch and tab preload group policies](https://docs.microsoft.com/en-us/microsoft-edge/deploy/group-policies/prelaunch-preload-gp)
* Content Source: [browsers/edge/group-policies/prelaunch-preload-gp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/group-policies/prelaunch-preload-gp.md)
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by egallagh** [comment]
Hi Tim.
The settings are in the Group Policies, Mobile Device Management (MDM) and registry settings listed in the document.
You also need to be running the appropriate version of Windows 10 and Edge as listed in the document.
You will need to use either the Group Policy Editor, appropriate Mobile Device Management configuration in Azure or the Registry Editor to make the modifications.
Hope that helps.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@TimTCM - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by egallagh. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
