### ISSUE TITLE
Encryption and signing in Windows Mail

### ISSUE THREAD

**Issue by bstordrup** [MicrosoftDocs/windows-itpro-docs#2385]
It  is simply not good enough only to support S/MIME for Exchange accounts. I have a computer with another desktop mail client (eM Client) configured to use my private gmail account, and that does perfectly handle S/MIME encryption and signing. So it is posssible.

Please make this possible with Windows Mail too!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45b6e3f6-bad4-80fe-3b83-f1cfd81324fe
* Version Independent ID: 4ae9fb8f-dfd6-f7db-d9cd-5d88a798681b
* Content: [Configure S/MIME for Windows 10 and Windows 10 Mobile (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/configure-s-mime)
* Content Source: [windows/security/identity-protection/configure-s-mime.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/configure-s-mime.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **justinha**

**Comment by jdeckerms** [comment]
@bstordrup You should submit this as a feature request in the Feedback Hub so that it goes directly to the engineering team for the app and so other customers can upvote it. Thanks!
