### ISSUE TITLE
Missing Checksums for Verification

### ISSUE THREAD

**Issue by barricade823** [MicrosoftDocs/windows-itpro-docs#2387]
It would be great if the executables had checksums that we could verify after the download. Thanks for providing this solution!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5bb1ce3-9128-5385-4417-d22eb5f8cb77
* Version Independent ID: cb6ba731-a2c2-e9b9-7c3e-db781b1b5222
* Content: [Microsoft Safety Scanner Download](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/safety-scanner-download)
* Content Source: [windows/security/threat-protection/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/intelligence/safety-scanner-download.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Even if I rarely see checksums for Microsoft downloads (if at all), I agree with your suggestion. Safety / security software should have checksums provided for their downloads for us to be able to verify that the downloaded software is authentic and not compromised in any way.

**Comment by Justinha** [comment]
@barricade823 @illfated Thanks for the suggestion and sorry for the delayed response. I'm not sure why we don't provide this for downloads but we've shared this suggestion with our engineering partners.

**Comment by barricade823** [comment]
Appreciate the support @illfated and thanks for the update @Justinha ! Later rather than never is good enough for me 😄

**Comment by Bullaa** [comment]
use of office365 office installed version ,particularly when Outlook or words is started ,causes initiation of Microsoft warning, covering the whole PC screen showing no signs of minimizing,(-) or (x) enabling minimizing or closing the page. Only recourse is use of Ctrl+Alt+Sel to generate options to initiate options to start the screen showing shut down, Task Manager where opting for task Manager opens the Task Manager from where Outlook or Word has to be ended the process to get out of the problem. Any help if available is welcome which can be sent either reply to email:nj@ispl.net.au or reply through the forum page if the link is still available to add comments.

**Comment by beerisgood** [comment]
@Justinha any news?
