### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by JGezels** [MicrosoftDocs/windows-itpro-docs#2388]
Hi

It seems there is an error in the following example:

Exclude all local users.                                  /ue:%computername%*

This should be: /ue:%computername%\*            =&gt; Missing backslash

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c7e6db2-1517-e9b9-cd9a-6a6aaf84ccc3
* Version Independent ID: daab80f9-640e-36c9-e60a-084901b11c05
* Content: [ScanState Syntax (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-scanstate-syntax#bkmk-useroptions)
* Content Source: [windows/deployment/usmt/usmt-scanstate-syntax.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/usmt/usmt-scanstate-syntax.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Thank you for pointing out the missing backslashes (either replaced by `<em>` or simply missing). Sorry for the delay in providing a solution. I will check for and provide a solution if nobody else have made it yet.
