### ISSUE TITLE
"On-Premise" Grammar

### ISSUE THREAD

**Issue by GalloTheFourth** [MicrosoftDocs/windows-itpro-docs#2393]
The proper way to say this is "On-Premises".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d01bd8e-2800-21f2-0042-35d2de7f402b
* Version Independent ID: c63d6d9b-5f71-03ed-c0c7-e2d778aed3d1
* Content: [On-premise authentication device enrollment](https://docs.microsoft.com/en-us/windows/client-management/mdm/on-premise-authentication-device-enrollment)
* Content Source: [windows/client-management/mdm/on-premise-authentication-device-enrollment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/on-premise-authentication-device-enrollment.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by Heidilohr** [comment]
@GalloTheFourth The article has been updated to correct the grammar. You can view the updated article [here](https://docs.microsoft.com/en-us/windows/client-management/mdm/on-premise-authentication-device-enrollment).

**Comment by GalloTheFourth** [comment]
Thank you!!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
