### ISSUE TITLE
can I get  separate iso 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#2394]
Sir I want to install windows 10 S  on laptop   so that I need separate iso file or install.wim.
Will you please give me direct downlaod link for windows 10 S.
Also I need product key, could you tell where I can purchase 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 693c3223-df7f-9fbb-ce68-d3fb1ec04d53
* Version Independent ID: 2e2a1281-750a-63f6-f412-c466f44d03c9
* Content: [Windows 10 Pro in S mode](https://docs.microsoft.com/en-in/windows/deployment/s-mode)
* Content Source: [windows/deployment/s-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/s-mode.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by egallagh** [comment]
Hi there. The docs explain how to enable S Mode (beginning with version 1803) here:
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-10-s-enable-s-mode
I hope that helps.

**Comment by RAJU2529** [comment]
thanks sir.  You given correct link to enable s mode
