### ISSUE TITLE
End of life

### ISSUE THREAD

**Issue by yannara** [MicrosoftDocs/windows-itpro-docs#2395]
If this is the MBAM main page, why its not written, that end of life is 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82546501-375e-1266-fceb-93b9fe5ceb14
* Version Independent ID: f3301a05-dc4e-43f8-d590-9ec0ad17988e
* Content: [Microsoft BitLocker Administration and Monitoring 2.5](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/)
* Content Source: [mdop/mbam-v25/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/index.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by jordanmills** [comment]
Apparently, the EOL is postponed.  But I can't find solid data on it.

**Comment by e0i** [comment]
@jamiejdt Could we get clarification on end of life for Microsoft BitLocker Administration and Monitoring product? We would like to follow up with this issue and commit necessary document changes if necessary. Thanks.

**Comment by e0i** [comment]
@jamiejdt Any updates with this question?

**Comment by baardhermansen** [comment]
You've probably seen this already, but to aid in the closure of this open issue:
Support have been extended to 14. april 2026. 
https://support.microsoft.com/en-us/lifecycle/search?alpha=bitlocker

@officedocsbot close
