### ISSUE TITLE
Can I Have more information on Blocking and allowing Sites in Edge Kiosk Mode

### ISSUE THREAD

**Issue by boivinx7** [MicrosoftDocs/windows-itpro-docs#2396]
Its Really not clear the For Mode Details : https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/windows-firewall-with-advanced-security-deployment-guide

There is no Information on how to Block/allow site in this page.
and all I can find is by Ip address's it would be preferable by URL's

Thanks

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@boivinx7 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @boivinx7 ,
blocking URL is out of the scope of Windows Firewall, it could block IP addresses
if you need to allow only certain websites, use kiosk built-in functionality - https://docs.microsoft.com/intune/kiosk-settings-windows
if you need to block several sites, use hosts file
if you need more functionality - you need to use third-party solutions

Thank you

**Comment by boivinx7** [comment]
So your original doc lied...
And it took 5 months to simply say thst you have nothing..... 
thanks il do it with chrome 
You should think about making it work thst same way it works on ios and android with intune and edge
