### ISSUE TITLE
Error: -2147467259

### ISSUE THREAD

**Issue by amandeep0498** [MicrosoftDocs/windows-itpro-docs#2398]
I am stuck at error 2147024809 in the recovery tool. The error says Could not write image to drive and disk part execution failed with error code 2147467259.
The Liteon L CH-128V2S is getting detected by PC and  has one single partition of 119.24 GB NTFS.

Kindly help to resolve the issue

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e78f073c-9f6b-b9d2-cd94-0a31998f10d9
* Version Independent ID: 5beaeca4-3d07-c65c-018b-a88cda5ceb9a
* Content: [Using the Surface Hub Recovery Tool](https://docs.microsoft.com/en-us/surface-hub/surface-hub-recovery-tool)
* Content Source: [devices/surface-hub/surface-hub-recovery-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/surface-hub-recovery-tool.md)
* Product: **surface-hub**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by amandeep0498** [comment]
I am stuck at error 2147467259* in the recovery tool. The error says Could not write image to drive and disk part execution failed with error code 2147467259.
The Liteon L CH-128V2S is getting detected by PC and has one single partition of 119.24 GB NTFS.

Kindly help to resolve the issue

**Comment by jdeckerms** [comment]
@amandeep0498 You should contact Microsoft Support for assistance: https://support.microsoft.com/en-us/contactus/

**Comment by amandeep0498** [comment]
Getting no response for request no. 119010219502165
