### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by nitemarened** [MicrosoftDocs/windows-itpro-docs#2400]
Step 8 - 
"These steps will walk you throug the process"

Also, I can't FIND the files referenced in step 7 - 
"On MDT01, using File Explorer, copy the following files from the D:\Setup\Sample Files\MDT Production\Control folder to E:\MDTProduction\Control. Overwrite the existing files."
It seems others have wondered about this, and there are no solutions to be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by nenonix** [comment]
@nitemarened I fixed the typo, and please could you check if this works before I change the content:  "the customsettings.ini should be copied from E:\MDTProduction\Control" - does that work?

**Comment by mypil** [comment]
@nitemarened - Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
