### ISSUE TITLE
Cannot Access Group Policy Management Console

### ISSUE THREAD

**Issue by PGrad** [MicrosoftDocs/windows-itpro-docs#2402]
Above. I try to run gpedit.msc from "Run" and it doesn't work. I even searched for gpedit.msc and got this error:
https://imgur.com/a/11S9uwq

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dfd2dce-335c-0e70-6898-766972c9fbf5
* Version Independent ID: e73181b1-a39d-1894-c86c-976316f16eee
* Content: [Configure always-on real-time Windows Defender Antivirus protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-real-time-protection-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-real-time-protection-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/configure-real-time-protection-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@PGrad - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
