### ISSUE TITLE
Disable 'Skip for now' option in OOBE environment 

### ISSUE THREAD

**Issue by ArunPandian1411** [MicrosoftDocs/windows-itpro-docs#2403]
Is there any way to disable or hide 'Skip for now' option for Windows hello for business setup in Windows 10 OOBE environment? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e5f5f1-16cf-57e2-bdfc-b090d90437b1
* Version Independent ID: 1662c47f-12cb-147d-25f0-dee98b6c7722
* Content: [Windows Hello for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-identity-verification.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-identity-verification.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by mapalko** [comment]
There is not a way to disable or hide the 'Skip for now' option for Windows Hello for Business if a user clicks on 'x' or an error occurs during provisioning. If Windows Hello for Business policy is set, they will be prompted to complete the provisioning experience every time they sign in until WHfB is set up.

**Comment by Jet-Mont** [comment]
I have the same question from a client. Followup on this, Microsoft product group had mentioned that it's in the road map for next version.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ArunPandian1411 - Thank you for submitting this feedback.

From our understanding, the issue you raised has been answered by mapalko. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by michaeldeblok** [comment]
We -as a company- need the option to disable the skip for now button. We do not allow users to create a local user, and we do not use AzureAD as our IdP, we have Okta. Okta does not pass on the password to windows, only the ticket. Using Okta and Autopilot the only way for the user to continuously log in is by leveraging Windows Hello's Pin code, Facial recognition, and/or Finger print. If this entire process is skipped and the endpoint were to reboot/logoff, the user will not be able to log back in again and a hard reset is necessary.
