### ISSUE TITLE
Intune required?

### ISSUE THREAD

**Issue by marcosmcampos** [MicrosoftDocs/windows-itpro-docs#2404]
In section WDAC System Requirements you can read:

"They can be applied to computers running any edition of Windows 10 or Windows Server 2016 and managed via Mobile Device Management (MDM), such as Microsoft Intune."

This may be interpreted as Intune being required for WDAC, but it's not. You can fully deploy and manage without Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 481aaad1-c3ed-3eb1-bd29-ebad8f264edd
* Version Independent ID: dc5d9c47-e4aa-22ab-cb41-dfed57c517ac
* Content: [Windows Defender Application Control (WDAC) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control.md)
* Product: **w10**
* GitHub Login: @jsuther1974
* Microsoft Alias: **justinha**

**Comment by egallagh** [comment]
Hi there.
I respectfully disagree. It clearly states "such as Intune" and does not imply that Intune is required.

**Comment by marcosmcampos** [comment]
> Hi there.
> I respectfully disagree. It clearly states "such as Intune" and does not imply that Intune is required.

Thanks for the feedback. I'll rephrase: I believe the sentence leads you to believing you need an MDM solution (agreed, doesn't necessarily say you need intune) but you don't need an MDM solution for WDAC. MDM is just one of the ways of deployment and managing WDAC, but so is Group Policy.

**Comment by Justinha** [comment]
@marcosmcampos @egallagh Thanks for the input! I added "optionally" manage with Intune to make that more clear.
