### ISSUE TITLE
Clicking on Password Synchronization with Azure AD Connect leads to a 404 error page

### ISSUE THREAD

**Issue by pretzelic** [MicrosoftDocs/windows-itpro-docs#2405]
Clicking on "Password Synchronization with Azure AD Connect" under "Federation with Azure" leads to "https://docs.microsoft.com/en-us/azure/active-directory/connect/active-directory-aadconnectsync-implement-password-synchronization" which is a page that doesn't exist. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c47de28c-e44b-ca73-efde-fae303e0d3f8
* Version Independent ID: 71202a24-5b2f-844a-acce-d48c46873f2b
* Content: [Hybrid Key trust Windows Hello for Business Prerequisites (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@pretzelic  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@pretzelic - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
