### ISSUE TITLE
Broken link at TPM Cmdlets in Windows Powershell

### ISSUE THREAD

**Issue by ericleigh007** [MicrosoftDocs/windows-itpro-docs#2407]
The link is broken and brings up a 404+search page.

Is it supposed to point here?
https://docs.microsoft.com/en-us/powershell/module/trustedplatformmodule/?view=win10-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 035a6270-8a60-2a3c-604f-506b58118b46
* Version Independent ID: 26a1102b-e201-42c2-212c-fd6726e2ca97
* Content: [Trusted Platform Module Technology Overview (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/trusted-platform-module-overview)
* Content Source: [windows/security/information-protection/tpm/trusted-platform-module-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/tpm/trusted-platform-module-overview.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **justinha**

**Comment by egallagh** [comment]
Good catch. I have submitted a request. Thanks!
