### ISSUE TITLE
Missing content

### ISSUE THREAD

**Issue by VincentK76** [MicrosoftDocs/windows-itpro-docs#2410]
The following chapters are not available anymore. I need the 5th.

4. Use PowerShell to configure Exchange properties of the account.
5. Enable the account with Skype for Business.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3f49206-2ef4-9c6d-1d3b-951c1440f1db
* Version Independent ID: 53f586ed-c5fb-1875-b67f-08d206921ec3
* Content: [Create a device account using UI (Surface Hub)](https://docs.microsoft.com/en-us/surface-hub/create-a-device-account-using-office-365#create-device-acct-o365-configure-exch-prop)
* Content Source: [devices/surface-hub/create-a-device-account-using-office-365.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/create-a-device-account-using-office-365.md)
* Product: **surface-hub**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@VincentK76 I need to check with the person who removed those sections, and he won't be back until next week (Jan 7). I'll let you know as soon as I have an explanation.

**Comment by jdeckerms** [comment]
@VincentK76 It wasn't actually removed, but a format mistake made it all appear to be part of the code sample. I'll get it fixed today so it displays properly. Thank you for bringing the problem to our attention!
