### ISSUE TITLE
Clarify whether password change is needed when disabling reversible encryption

### ISSUE THREAD

**Issue by rbsec** [MicrosoftDocs/windows-itpro-docs#2411]
The documentation around storing passwords with reversible encryption highlights the security problems with this setting, and recommends that it is disabled in order to prevent Windows storing passwords.

My understanding is that if reversible encryption has previously been enabled, disabling it will only prevent Windows from storing any future passwords with reversible encryption, but that it will not remove any reversibly stored passwords. This isn't mentioned in the documentation, and I couldn't find a definitive Microsoft source for this (although [ServerFault](https://serverfault.com/questions/895431/setting-store-passwords-using-reversible-encryption-to-disabled) agrees with it).

It would be useful if this document was explicit about whether a password change was required to remove these.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a421f9ba-160f-a394-1297-94143ecdc51f
* Version Independent ID: b30be967-331a-be20-45d8-12991445cbe7
* Content: [Store passwords using reversible encryption (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/store-passwords-using-reversible-encryption#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/store-passwords-using-reversible-encryption.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/store-passwords-using-reversible-encryption.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@rbsec  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@rbsec - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by rbsec** [comment]
Fantastic - thanks.

**Comment by mypil** [comment]
@officedocsbot close
