### ISSUE TITLE
Customize Windows 10 Start and taskbar

### ISSUE THREAD

**Issue by cannonwill** [MicrosoftDocs/windows-itpro-docs#2412]
NO!  We will not become coders so we can customize an enterprise Taskbar.  This should be a simple task for creating consistency.  What we WILL do is find registry hacks to just remove and restrict features.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 061157dc-8fc8-3f9d-c01f-37f22fbdf1c7
* Version Independent ID: 0b0b6797-9367-eb7c-22ef-5f2b8bbfe592
* Content: [Start layout XML for desktop editions of Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/start-layout-xml-desktop)
* Content Source: [windows/configuration/start-layout-xml-desktop.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/start-layout-xml-desktop.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@cannonwill It would be helpful if you submitted how you think it ~should~ work through the Feedback Hub so your input goes directly to the engineering team for that feature, thanks.
