### ISSUE TITLE
Usage guidelines

### ISSUE THREAD

**Issue by kexijano** [MicrosoftDocs/windows-itpro-docs#2414]
Is this the type of tool that can be used between lab sessions during the day? Assuming I have Ethernet connections to each lab PC and a local server, is it feasible/recommended to plan on using an approach like this multiple times a day? Or is this something that takes so long that you wouldn’t recommend that frequency?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 687baa4b-2e3b-e632-403f-546f7e1bbaf3
* Version Independent ID: eabccfdc-45ec-339d-a4c2-537f1387608d
* Content: [Reset devices with Autopilot Reset](https://docs.microsoft.com/en-us/education/windows/autopilot-reset)
* Content Source: [education/windows/autopilot-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/autopilot-reset.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **celested**

**Comment by Tdiwestyguy** [comment]
The remote task is pretty fast.  I saw it happen about as fast as the Remote restart.   Might want to try it out!  

I would say your main issue (based on your question, how long will it take) I think you're talking about how long does it take to get back to ready state for the next user..   The enrollment process for Self deploying profile is pretty quick however if you do things like adding Enrollment Status page, and if you're loading desired configurations you're piping, app deployment, or policy load is going to take a little bit.. but its still very quick.   on the other hand if you issue the command to make the device not ready until All policy, all apps.. and you have a hundred apps, it may take a while, just sayin.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by Reeced40** [comment]
@kexijano Thanks for reaching out, has @Tdiwestyguy answered your questions? Please let me know if you need any more information.

**Comment by mypil** [comment]
@kexijano - From our understanding, the issue has been answered by Tdiwestyguy. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
