### ISSUE TITLE
An Issue With .jar Files and .java Files

### ISSUE THREAD

**Issue by tank2008** [MicrosoftDocs/windows-itpro-docs#2417]
[在此处输入反馈]
The thing about cloud that I am worried about is if it is secure enough? This is not a commitment though, so please consider this as a comment. Also, I've tested a few times on my computer using ".jar" files and ".java" files, try to fix them. As you can see, the security system would problably think that if the hash (In fact I thought that they don't have hash strings) string is correct and it cant detect anything on the surface, it will say the file is safe to open and use--in fact it is not. So take this as a problem and plz fix it, because I play modded Minecraft...

PS: I am a Chinese twelve-year-old and I don't know much about grammar... So... 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9bd0fe29-5db5-b752-5bcf-5ac2581baa9a
* Version Independent ID: 52b8d4ca-54ea-7345-12b0-df4fdf633083
* Content: [启用“首次看到时阻止”在几秒内检测到恶意软件](https://docs.microsoft.com/zh-cn/windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@tank2008 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
