### ISSUE TITLE
Why are you suggesting Netmon?

### ISSUE THREAD

**Issue by jeffstokes72** [MicrosoftDocs/windows-itpro-docs#2418]
Microsoft Message Analyzer has been out for several years now. Netmon 3 was deprecated last I heard...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8823127-9a9b-141c-6096-e8d40ff6e22c
* Version Independent ID: 02332337-0981-36af-424e-9378487dd4d8
* Content: [Collect data using Network Monitor](https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-tcpip-netmon)
* Content Source: [windows/client-management/troubleshoot-tcpip-netmon.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/troubleshoot-tcpip-netmon.md)
* Product: **w10**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **kaushika**

**Comment by egallagh** [comment]
This is an explanation of the use of netmon, not necessarily a recommendation to use netmon.
Although deprecated, it is still available for download from Microsoft for use and works fine.

**Comment by jeffstokes72** [comment]
Didn't know they had MVP's writing articles. Cool. I am well aware netmon works. Seems pretty silly to highlight old tech on the docs page though.

I've given my feedback, do what you like I guess.
