### ISSUE TITLE
You should mention that until 2016/10, netstat was inaccurate.

### ISSUE THREAD

**Issue by jeffstokes72** [MicrosoftDocs/windows-itpro-docs#2419]
This blog post is better than the other two you reference I think, and newer;
https://blogs.technet.microsoft.com/yongrhee/2018/01/09/windows-server-2012-r2-ephemeral-ports-a-k-a-dynamic-ports-hotfixes/

please border your screenshot

Fixes for netstat were backported to 2012 R2

https://support.microsoft.com/en-us/help/3123245/update-improves-port-exhaustion-identification-in-windows-server-2012

About this update
Network reporting tools, such as Netstat and PowerShell-based Get-NetTcpConnection don't report Transport Control Protocol (TCP) or User Datagram Protocol (UDP) port usage correctly since Windows Vista because some new TCP/IP features are introduced. This update brings some changes to Netstat.exe and Get-NetTcpConnection so that they can correctly report the TCP or UDP port usage in Windows Server 2012 R2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c2ae54-4348-565f-ffbc-e9d95436ac8e
* Version Independent ID: f3c8b6f8-ed47-3628-f064-8773b91cd921
* Content: [Troubleshoot port exhaustion issues](https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-tcpip-port-exhaust)
* Content Source: [windows/client-management/troubleshoot-tcpip-port-exhaust.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/troubleshoot-tcpip-port-exhaust.md)
* Product: **w10**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **kaushika**

**Comment by jeffstokes72** [comment]
Been two months, any thoughts?

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @jeffstokes72 

The issue is under investigation and you will be updated with any changes on the go.

Thank you for providing feedback and following up.

**Comment by lindspea** [comment]
@jeffstokes72 Thanks Jeff. I'll work on getting the updated blog added as well as bordering the screenshot.  For the fixes for netstat, are you suggesting adding a note to the article about the update?

**Comment by jeffstokes72** [comment]
Yeah I think that's a good idea

**Comment by lindspea** [comment]
@jeffstokes72 Thanks Jeff.  I'm working with the team to have the changes made and approved soonest.

**Comment by e0i** [comment]
@jeffstokes72 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by imranbaloch** [comment]
I download Network Monitor but Wscore_MicrosoftWindowsWinsockAFD.AFD_EVENT_BIND.Status.LENTStatus.Code is not found
