### ISSUE TITLE
Usage is not possible with work or school account

### ISSUE THREAD

**Issue by Karl-WE** [MicrosoftDocs/windows-itpro-docs#2424]
"use the MSA login associated with your WIP credentials"

I am very sorry but I can solely sign in with a work or school account for the MSIX Packaging Tool Env, then when trying to install the app from the store I cannot sign in with the same but can only a consumer account? Please get your sign in requirements sorted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f021dd-9c78-4edb-8b5c-2ce70d5d7bbc
* Version Independent ID: 56ffd512-caa1-a2d4-94f6-3b4b2df40bd6
* Content: [Repackage your existing win32 applications to the MSIX format.](https://docs.microsoft.com/en-us/windows/application-management/msix-app-packaging-tool)
* Content Source: [windows/application-management/msix-app-packaging-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/msix-app-packaging-tool.md)
* Product: **w10**
* GitHub Login: @MikeBlodge
* Microsoft Alias: **mikeblodge**

**Comment by andreabichsel** [comment]
@MikeBlodge, can you take a look at this?

**Comment by e0i** [comment]
@MikeBlodge Any updates with this issue? We'd like to follow up on this.
Thanks.

**Comment by bmilbauer** [comment]
Putting an enterprise packaging tool like this behind an auth wall requiring a consumer Microsoft account is asinine and completely unacceptable. Many organizations have security policies preventing sign-in to computers with Microsoft accounts. So, how are administrations in those situations supposed to download and use this tool?

**Comment by e0i** [comment]
The issue has been noted for re-investigation.

**Comment by joinimran** [comment]
Hello, @Karl-WE Thank you for your query. Can you please confirm the document that you have pointing to. Because the associated document as of now doesn't mention anywhere about use the MSA login associated with your WIP credentials.

Thanks. 
Imran.

**Comment by Karl-WE** [comment]
Hello @joinimran I am not sure if I understood you correctly. 
The article does say that one needs an MSA Account for download from the Store.
When you install a MSIX VM via Hyper-V, however you may not logon to this MSIX VM with a MSA but only with a business account. 
It should be added as prerequisite, or, if possible at all cleared that MSIX VM is not limited and also can be used to login with a MSA.

**Comment by illfated** [comment]
The way I am reading that page, I only need my MSA to log on to the Microsoft Store web page, while still being logged in as a local domain account.

**Comment by Karl-WE** [comment]
Hi @illfated, I am not sure if I am misunderstood. I'd like to add the following to the docs section requirements: Work or school account. One can only login to the MSIX Hyper-V VM with this account type. MSA are not supported.

**Comment by illfated** [comment]
> [ ... ]  I'd like to add the following to the docs section requirements: Work or school account. One can only login to the MSIX Hyper-V VM with this account type. MSA are not supported.

Looks reasonable. I don't know why that should be something to object to. Not 100% sure about what the exact phrasing needs to be for the non-technical parts, though. I presume there are Microsoft code style samples for that, though.

**Comment by joinimran** [comment]
@Karl-WE - As per going through different documentations related to MSIX packaging I couldn't find anything where it says that Work or School account is required instead of MSA account. What I feel there might be something related to your package that needs Work/School account instead of MSA.

What I can do is to add a note in the document if you can share me the exact content that should be added. Rest will be dependent on the document owner to see if that fits in the doc then that will go live. 

Thanks.
Imran.

**Comment by illfated** [comment]
Any closing comment to share, @e0i ?

**Comment by Karl-WE** [comment]
@joinimran what you said is exactly my point of this PR.

Try your own here is the repro 
Have Windows Server with gui or Pro / Enterprise
Install Hyper-V, quick create a new VM from latest MSIX template
After setup you see a logon screen in the VM. 

It only accept work accounts. No MSA.

**Comment by e0i** [comment]
Sorry, I have misinterpreted Imran's comment as a resolution.  @joinimran I think we may proceed with the clarification of the issue reporter,

**Comment by Karl-WE** [comment]
any news here? @e0i

**Comment by joinimran** [comment]
@Karl-WE - Sorry it went out of my radar. I have checked and found your statement correct. I am creating PR for the same. 

@illfated - FYI Please. See attachment.
![Imran](https://user-images.githubusercontent.com/47118050/86772269-1e449200-c06d-11ea-85c6-d49702a9e545.png)

**Comment by illfated** [comment]
@joinimran : Thank you for your diligent work and for finding out what was going on here. I am happy to see that you made progress with your testing. Keeping my fingers crossed for your PR to become accepted and that the page will be updated to highlight the issue and its eventual resolve.

**Comment by Karl-WE** [comment]
Great news, why having a new PR instead of following this one? 
@joinimran

**Comment by illfated** [comment]
> Great news, why having a new PR instead of following this one?

Well, just in case there is any misunderstanding and to be clear about the details, this page is an issue ticket.
PR is a Pull Request, like #7100 (linked above).
An issue ticket (like this page) is only a reporting page, not a PR.

**Comment by Karl-WE** [comment]
Thanks for explaining me the terminology. You know I am quite new to github. Thanks for you patience!

**Comment by e0i** [comment]
Closing via the latest PR that has finally been merged, #7889. Thank you for the discussion.
