### ISSUE TITLE
small typo under section "2. Reduce user-visible password surface area"

### ISSUE THREAD

**Issue by Conan1989** [MicrosoftDocs/windows-itpro-docs#2426]
Hi,
small typo under section "2. Reduce user-visible password surface area"

sentence:
Users who rarely, **it** at all, use their password are unlikely to provide it.

suspect that intended word is "if"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca080bd-ed37-60a8-ec22-b1929166ff0c
* Version Independent ID: d2742e0c-9d66-4b1f-8555-a1fb1546455b
* Content: [Password-less Strategy](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/passwordless-strategy)
* Content Source: [windows/security/identity-protection/hello-for-business/passwordless-strategy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/passwordless-strategy.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by mypil** [comment]
@Conan1989 - Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
