### ISSUE TITLE
WHFB PIN sign in to RDweb/RDP

### ISSUE THREAD

**Issue by micahcastorina** [MicrosoftDocs/windows-itpro-docs#2429]
Is it possible to sign in to rdweb or rdp using whfb PIN in a key trust deployment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a146880-235b-a69c-3e9d-a3fa56a25389
* Version Independent ID: c2c226b4-17ef-8888-9e1b-e20cf3273c3a
* Content: [Windows Hello for Business Features](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-features#remote-desktop-with-biometrics)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-features.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by DaniHalfin** [comment]
Hi @veechee, Key Trust deployment support for RDP has no ETA currently.
(cc: @mapalko )

**Comment by DaniHalfin** [comment]
Hi @micahcastorina,
WHfB Key Trust deployments aren't supported for WHfB RDP functionallity as of right now.

**Comment by micahcastorina** [comment]
That is really dumb. They only pushed the benefits of Key trust and didn't mention any of the negatives.
