### ISSUE TITLE
SelfDeploying Profiles

### ISSUE THREAD

**Issue by Niglb** [MicrosoftDocs/windows-itpro-docs#2431]
Are SelfDeploying Profiles supported for offline JSON? I am having issues :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17bfe927-f7b7-608b-8537-5c2274ccdced
* Version Independent ID: 5dd9abca-92d9-fbb2-6796-d1f6b9ab3c8b
* Content: [Windows Autopilot for existing devices](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/existing-devices)
* Content Source: [windows/deployment/windows-autopilot/existing-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/existing-devices.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by rlawrimore** [comment]
yes, I would like to know this as well.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Niglb  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by Niglb** [comment]
Thank you very much! Self Deploying support would be ideal.

**Comment by joinimran** [comment]
Hello @Niglb Thank you for raising your query. Can you please share the details of the issue you are facing so that we can better help you. 

Thanks.

**Comment by mypil** [comment]
@Niglb - We would like to follow up. Can you please respond to the query of joinimran? Thank you.

**Comment by per-lind** [comment]
@mypil I think the main question is if this is supported for an autopilot profile set to SelfDeploying mode. I myself could not get it to work while a normal profile worked just fine. Hard to troubleshoot when it is unknown if it is supposed to work.

**Comment by Niglb** [comment]
This is my question as well - if it is supported and when will it be.

**Comment by mypil** [comment]
@Niglb @per-lind - let me try to get the inputs from the doc owner.

@greg-lindsay - can you please share your insights on this issue?

Thank you.

**Comment by mypil** [comment]
@Niglb @per-lind - I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by Edocsyl** [comment]
is there a update for this specific case? i was talking to the microsoft intune support but they have also trouble for searching an anwser.

**Comment by illfated** [comment]
Looks like nothing has happened regarding this question, so I would recommend posting on Feedback Hub and ask them if this question will be answered in the documentation or not.
