### ISSUE TITLE
A few typos to fix

### ISSUE THREAD

**Issue by dgcuff** [MicrosoftDocs/windows-itpro-docs#2434]
In the paragraph beginning "In the Semi-Annual servicing channel, feature updates are...", the word "modal" should read "model," the phrase "you choose" should read "you chose" and the phrase "it goes into" should read "it went into."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6957383-3bd9-eef9-6410-9c42f8a0b172
* Version Independent ID: a2090374-0fd1-8d67-66de-30c4cf2835f7
* Content: [Overview of Windows as a service (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-overview)
* Content Source: [windows/deployment/update/waas-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-overview.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
I could be wrong, but I read the sentence as if it is talking about a current scenario and not something from the past. Therefore, I suggest the following phrasing:

> Once the latest release **has gone** through pilot deployment and testing, you **will be able to** choose the timing at which it goes into broad deployment.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@dgcuff @illfated @tusharchandwani - From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
