### ISSUE TITLE
Formatting of the Events List is messed up

### ISSUE THREAD

**Issue by cronq** [MicrosoftDocs/windows-itpro-docs#2436]
Formatting of the Events List is messed up

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4aa2620-2efd-4c76-288d-8cb046ed71d6
* Version Independent ID: 4cd92a9c-6aa2-9c71-693a-94f2898f2c4a
* Content: [Audit Application Group Management (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-application-group-management)
* Content Source: [windows/security/threat-protection/auditing/audit-application-group-management.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/audit-application-group-management.md)
* Product: **w10**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@cronq Thanks for raising this one too. We'll share this with our engineering partners.
