### ISSUE TITLE
Formatting of events list is messed up

### ISSUE THREAD

**Issue by cronq** [MicrosoftDocs/windows-itpro-docs#2437]
Formatting of events list is messed up

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9cd4539-eb4d-9d25-47fa-9f93b2584836
* Version Independent ID: 3a63fc40-b2ee-a73b-fe9b-9affac85dee0
* Content: [Audit IPsec Extended Mode (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-ipsec-extended-mode)
* Content Source: [windows/security/threat-protection/auditing/audit-ipsec-extended-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/audit-ipsec-extended-mode.md)
* Product: **w10**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@cronq Thanks for the feedback, I see what you mean. There are several events that are missing details and screenshots, including this set unfortunately. We'll share your feedback with our engineering partners.
