### ISSUE TITLE
"Add Upgrade Readiness to OMS" sill on the page

### ISSUE THREAD

**Issue by mariuszo-at-microsoft-com** [MicrosoftDocs/windows-itpro-docs#2440]
Replace
"2. Add Upgrade Readiness to OMS.
with
"2. Add the Upgrade Readiness solution to your Azure subscription"
in 
"When you are ready to begin using Upgrade Readiness, perform the following steps:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24771310-237e-adf7-be33-59355a87f243
* Version Independent ID: e2792588-8318-98a2-a5bd-ff5cbba75e0e
* Content: [Get started with Upgrade Readiness (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-get-started#enroll-devices-in-windows-analytics)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-get-started.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@mariuszo-at-microsoft-com  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @mariuszo-at-microsoft-com , @mypil ,
the issue was resolved by commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/74701833b55995a52407c9a1f04acc4ecee7e855#diff-7d69df47d0443ddc8c8acf0d06db012c (it removes not only this reference to OMS, but also all the others within the article)
I think it could be closed now
Thank you

**Comment by mypil** [comment]
@officedocsbot close
