### ISSUE TITLE
No mention of Cloud Clipboard

### ISSUE THREAD

**Issue by pebbledavec** [MicrosoftDocs/windows-itpro-docs#2441]
As a systems admin this feature worries me; many password managers use the clipboard to pass passwords to apps. If users enable this feature, does that mean that their passwords will be stored in the cloud and shown in plain text on other devices via the cloud clipboard feature? I was hoping to find more information about this feature here but for some reason it's been omitted (even though it was in the video).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d6356b-87ff-8c3a-56ef-1270a823d3ab
* Version Independent ID: 4d6ae878-66cf-0e10-bdf3-bdd6054cbc9d
* Content: [What's new in Windows 10, version 1809](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1809.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1809.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by cfield80** [comment]
New GPO controls have been made available to disable this, but it should have much higher visibility in terms of what MS tout about what is new or not.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@pebbledavec 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by joinimran** [comment]
@pebbledavec Thank you for your feedback. The required section has been added in the article. Please note that if the password manager will hold the data in the clipboard that will also get synced if this feature is enabled. To keep it safe, you can select never automatically sync text that I copied. 
Thanks

**Comment by e0i** [comment]
@pebbledavec 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@pebbledavec 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
