### ISSUE TITLE
Copy on Write (CoW) file extension support 

### ISSUE THREAD

**Issue by Softgrider** [MicrosoftDocs/windows-itpro-docs#2442]
The blocked file extension have changed since App-V 5.1
Only .com .exe .dll .ocx are blocked.

See http://virtualvibes.co.uk/app-v-5-1-the-feature-run-down/ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 295453ec-f5db-01b6-ef31-9759d8ad26a0
* Version Independent ID: 71e26e47-ceae-f540-1f47-fdc92e2265d7
* Content: [Creating and managing App-V virtualized applications (Windows 10)](https://docs.microsoft.com/en-us/windows/application-management/app-v/appv-creating-and-managing-virtualized-applications)
* Content Source: [windows/application-management/app-v/appv-creating-and-managing-virtualized-applications.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/app-v/appv-creating-and-managing-virtualized-applications.md)
* Product: **w10**
* GitHub Login: @MaggiePucciEvans
* Microsoft Alias: **elizapo**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@Softgrider 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by lindspea** [comment]
@Softgrider Thank you for helping improve MS Docs.  I just need some clarity to update the article please.  Are you suggesting removing the revelant file extensions under "Copy on Write (CoW) file extension support"?

**Comment by Softgrider** [comment]
Hi,
since App-V 5.1 there are only 4 file extensions blocked by CoW.

Only .exe .com .dll and .ocx files can’t be changed (blocked) by CoW.
All other file extensions can be deleted.

Regards from Germany
Frank




Von: Lindsay <notifications@github.com>
Gesendet: Freitag, 10. Mai 2019 11:16
An: MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>
Cc: Frank Fette <frank@fette.name>; Mention <mention@noreply.github.com>
Betreff: Re: [MicrosoftDocs/windows-itpro-docs] Copy on Write (CoW) file extension support (#2442)


@Softgrider<https://github.com/Softgrider> Thank you for helping improve MS Docs. I just need some clarity to update the article please. Are you suggesting removing the revelant file extensions under "Copy on Write (CoW) file extension support"?

**Comment by e0i** [comment]
@Softgrider 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
