### ISSUE TITLE
Unenlightened app behavior

### ISSUE THREAD

**Issue by TomoharuMisawa** [MicrosoftDocs/windows-itpro-docs#2443]
適用可能です。列の自動暗号化の表記は原文では適用される。となっている。

この適用可能です。、必須ではありません。という翻訳も妥当ではないのではないかと思われます。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4a3a66e7-5463-ba93-dd43-b492a50ddfe4
* Version Independent ID: 27f65814-d9cd-597b-9f94-695dcb4f34e7
* Content: [Windows 情報保護 (WIP) を使用しているときの非対応アプリと対応アプリの動作 (Windows 10)](https://docs.microsoft.com/ja-jp/windows/security/information-protection/windows-information-protection/app-behavior-with-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/app-behavior-with-wip.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/information-protection/windows-information-protection/app-behavior-with-wip.md)
* Product: **w10**
* GitHub Login: @olprod
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@TomoharuMisawa sorry for delay and thanks for the feedback. Our goal is to have a solution where readers can improve the machine translation, but we don't have that at this time. 

@mypil this feedback is essentially asking us to confirm and correct the Japanese machine translation. Can you help route this?

**Comment by mypil** [comment]
@OfficeGlobal - can you possibly assist in fixing this issue? Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @OfficeGlobal

**Comment by mypil** [comment]
@OfficeGlobal - Do you have any updates on this issue? Kindly assist with this Translation (Localization) issue. Thank you.

**Comment by Justinha** [comment]
@mypil just a suggestion but maybe we should capture these localization requests in a formal way, share that data with our loc team, and close the related issue. I don't think we can realistically commit to fixing any loc issues at this time because we don't have resources to vet the changes.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Justinha - I checked and was informed that @dongmicro can help with Translation (Localization) issues. Unless, you have an email from your loc team where I can send the list to.. Can you share their email address? Thank you.

**Comment by mypil** [comment]
officedocsbot assigned mypil

**Comment by Justinha** [comment]
@mypil Sorry I don't have a different contact.

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Do you have any updates? Thanks.

cc: @AndreaBarr

**Comment by dongmicro** [comment]
This is Machine Translated, to fix it at this point we need to uplift the whole document for Human Translation, however, the repo that this doc is in is going to be migrated and the localization work is on hold till the migration is done, so the fix may need some time to implemented.

**Comment by mypil** [comment]
@officedocsbot add label localization

**Comment by mypil** [comment]
@TomoharuMisawa - please refer to the answer from dongmicro for this issue. We will proceed to close this issue for now. 

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
