### ISSUE TITLE
How do I go to Suceess, Failure from No auditing using AuditPolicyDcs

### ISSUE THREAD

**Issue by lpolyak68** [MicrosoftDocs/windows-itpro-docs#2446]
How do I go to "Suceess, Failure" from "No auditing" using AuditPolicyDcs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 869b9095-7ad6-9c02-674f-e53a79364da3
* Version Independent ID: f1bde893-20fc-0228-e4c3-21d2e06f8edc
* Content: [Audit object access (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/basic-audit-object-access)
* Content Source: [windows/security/threat-protection/auditing/basic-audit-object-access.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/basic-audit-object-access.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@lpolyak68 Sorry I don't know anything about AuditPolicyDcs.
