### ISSUE TITLE
"Note" should be "None"

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/windows-itpro-docs#2449]
Step 6-&gt;4-&gt;b-&gt;ii should be "None" rather than "Note". maybe "Note" belongs to the paragraph below it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by lizap** [comment]
I've changed the note formatting. Just testing and then will get published.

**Comment by illfated** [comment]
Looks very nice and defined now. Should not be possible to mistake the notes in this type of format. Good job.
