### ISSUE TITLE
Place a hint that internal NDES server url must match kerberos delegation name

### ISSUE THREAD

**Issue by nicolonsky** [MicrosoftDocs/windows-itpro-docs#2450]
In the bullet list "create-the-azure-application-proxy" a hint pointing out that the internal NDES Server URL must match the primary hostname of the server (AD computer account name) should be placed . Otherwise (if using a CNAME entry or A record in other DNS zone) the certificate distribution will not work because the kerberos delegation is configured for another hostname.
Everything else is well documented, I've successfully deployed WHFB for Azure AD joined devices multiple times.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f709fd4-0b5d-b238-4060-222d550cd538
* Version Independent ID: fb3f29da-2236-c47d-6bea-8efbcec8d7d3
* Content: [Using Certificates for AADJ On-premises Single-sign On single sign-on](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert#create-the-azure-application-proxy)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@nickbrower 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
