### ISSUE TITLE
Teams is not mentioned as top app

### ISSUE THREAD

**Issue by kunal191186** [MicrosoftDocs/windows-itpro-docs#2455]
Teams app is available on Surface Hub however in this documentation Teams is not mentioned as 'top app'. It would be good to modify this document for reflecting the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 324027ab-8e1b-045f-5904-e9e6c54e17d3
* Version Independent ID: 3a0b2c99-c013-867f-5517-89cc7cee451d
* Content: [Differences between Surface Hub and Windows 10 Enterprise](https://docs.microsoft.com/en-us/surface-hub/differences-between-surface-hub-and-windows-10-enterprise)
* Content Source: [devices/surface-hub/differences-between-surface-hub-and-windows-10-enterprise.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/differences-between-surface-hub-and-windows-10-enterprise.md)
* Product: **surface-hub**
* GitHub Login: @isaiahng
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@kunal191186 The article doesn't list "top apps", it lists pre-installed apps. At this time, Teams isn't pre-installed on Surface Hub, but thanks for the suggestion!

**Comment by kunal191186** [comment]
![image](https://user-images.githubusercontent.com/14099091/51403074-2f5db400-1b04-11e9-9c12-61acdcbecde5.png)

This is the screenshot from article where Skype for Business is mentioned as top app but not Teams.
