### ISSUE TITLE
Dual Enrollment Example Error

### ISSUE THREAD

**Issue by jbyway** [MicrosoftDocs/windows-itpro-docs#2459]
Both examples for the dual enrolment dscacls cmd examples are incorrect. 

dsacls "CN=AdminSDHolder,CN=System,**DC=domain,DC=com**" /g "**[domainName\keyAdminGroup]**":RPWP,msDS-KeyCredentialLink

dsacls "CN=AdminSDHolder,CN=System,DC=corp,DC=mstepdemo,DC=net /g "mstepdemo\Key Admins":RPWP,msDS-KeyCredentialLink

Correct Syntax for each is the replacement of the , and using ; instead at the point RPWP,msDS-KeyCredentialLink. The examples above both provide a syntax error.   Also the mstepdemo example is missing a " at the end of the DC=net

**Comment by illfated** [comment]
Do you have a page link (for easier lookup)?
