### ISSUE TITLE
Change History for Deploy Windows 10 - md links

### ISSUE THREAD

**Issue by computeronix** [MicrosoftDocs/windows-itpro-docs#246]
https://docs.microsoft.com/en-us/windows/deployment/change-history-for-deploy-windows-10

md links are not being adjusted properly on the production site (.md is supposed to be removed).  I think putting a ./ fixes it but I could be wrong as I am pretty new to this

as a result 14 links on this page return 404

**Comment by greg-lindsay** [comment]
Someone added .md in the links. This needs to be removed. Thanks for noticing the error!
