### ISSUE TITLE
Key Usage – Key Encipherment

### ISSUE THREAD

**Issue by chiners68** [MicrosoftDocs/windows-itpro-docs#2461]
This information is wrong. I removed all Key useage bar Key Usage – Key Encipherment and when creating the SEMM package it fails and states it could not be digitally signed.

If I regenerate the cert and leave in the default Key usege  of (digital Signature Key encipherment) then SEMM will succesfully generate the package.

So in your section 'Key Usage - ' you need to list both key Usage requirments

Key Usage – Digital signature, Key Encipherment

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0d25836-4403-d111-9bd7-ca5f1ed56449
* Version Independent ID: 5219aa78-698c-926c-53d8-f02fdf36bb3b
* Content: [Surface Enterprise Management Mode (Surface)](https://docs.microsoft.com/en-gb/surface/surface-enterprise-management-mode#surface-enterprise-management-mode-certificate-requirements)
* Content Source: [devices/surface/surface-enterprise-management-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/surface-enterprise-management-mode.md)
* Product: **w10**
* GitHub Login: @jobotto
* Microsoft Alias: **jdecker**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@chiners68 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
