### ISSUE TITLE
Scripts v Configuration Package

### ISSUE THREAD

**Issue by chiners68** [MicrosoftDocs/windows-itpro-docs#2462]
Configuring and deploying the scripts is a timely process, it also still requires the 2 digits for thumbprint to be manually entered. its far easier to use the configuration tool to generate and MSI for Deployment. this still requires 2 digits to be inputed but as either method requires this configuring the UEFI with this package is an easier process.

I have also found an issue for surface configuration. If you disable IPv6 PXE or USB boot to secure the device, either option or both seems to disable the ability to PXE over IPV4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ac548b-be6c-efba-76ee-67dd7af18891
* Version Independent ID: 947b62e7-1225-2f5e-14ba-fe5dccbbe124
* Content: [Use System Center Configuration Manager to manage devices with SEMM (Surface)](https://docs.microsoft.com/en-us/surface/use-system-center-configuration-manager-to-manage-devices-with-semm)
* Content Source: [devices/surface/use-system-center-configuration-manager-to-manage-devices-with-semm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/use-system-center-configuration-manager-to-manage-devices-with-semm.md)
* Product: **w10**
* GitHub Login: @KiranDavane
* Microsoft Alias: **jdecker**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@chiners68  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@chiners68 you are correct, it's easier to use the Configuration Manager to generate the MSI. If this is not clear from the article, please let us know what you would like to change/add.

Regarding the issue that you've encountered when disabling IPv6 PXE or USB boot, please reach out to the [Surface Community](https://answers.microsoft.com/en-us/surface/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1) or open a ticket with [support](https://support.microsoft.com/en-ca/contactus/).

**Comment by mypil** [comment]
@chiners68 - From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by chiners68** [comment]
Hi,
The answer took so long I forgot what the question was,lol

I have reported the other issues to the surface community.

**Comment by mypil** [comment]
@officedocsbot close
