### ISSUE TITLE
Basic security audit policy settings documentation uses old WIDs

### ISSUE THREAD

**Issue by scwxtsr** [MicrosoftDocs/windows-itpro-docs#2464]
The product in every subsection of 'Basic security audit policy settings' documentation is listed as Windows 10, but the documentation uses legacy/old Windows event IDs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8d03917-ca6d-d5e1-a45a-7efe22ca3258
* Version Independent ID: 8b79609a-397b-d60a-f790-9a69f62c39c8
* Content: [Basic security audit policy settings (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/basic-security-audit-policy-settings)
* Content Source: [windows/security/threat-protection/auditing/basic-security-audit-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/basic-security-audit-policy-settings.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@scwxtsr 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by VLG17** [comment]
@scwxtsr Thank you for pointing this out. Although the ["parent" article](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/basic-security-audit-policy-settings) which you linked does not need any updates itself, the majority of the articles linked in it do. I have made this known and all these articles will be handled independently:

https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/basic-audit-account-logon-events  

https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/basic-audit-account-management \

https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/basic-audit-directory-service-access 

https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/basic-audit-logon-events

https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/basic-audit-object-access  
 
https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/basic-audit-policy-change  

https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/basic-audit-privilege-use 

https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/basic-audit-process-tracking 

https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/basic-audit-system-events

**Comment by e0i** [comment]
Hello @scwxtsr,

The issue is being closed since your question seems to be answered by **VLG17** Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by marcnil815** [comment]
It's 2020.07.15 and the old WIDs are still in there.
Furthermore they do not only apply to Windows 10, but probably for everything after vista and also Server 2008 +

**Comment by RAJU2529** [comment]
@e0i . Look into this PR #7178

**Comment by illfated** [comment]
@RAJU2529 : #7178 is not a Pull Request, it is an issue ticket.
