### ISSUE TITLE
Detailed Tracking - Audit Token Right Adjusted

### ISSUE THREAD

**Issue by cronq** [MicrosoftDocs/windows-itpro-docs#2465]
Win10 includes the Audit Token Right Adjusted subcategory in Detailed Tracking. Please update this page/create a subpage for Audit Token Right Adjusted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 739bc932-12f0-9595-fbd2-d5b0df73fe93
* Version Independent ID: cd1f89ad-34db-bb96-e9ef-2137958c9403
* Content: [Advanced security audit policy settings (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/advanced-security-audit-policy-settings#detailed-tracking)
* Content Source: [windows/security/threat-protection/auditing/advanced-security-audit-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/advanced-security-audit-policy-settings.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by cronq** [comment]
Any update on this?

**Comment by Justinha** [comment]
@cronq sorry for delay and thanks for the suggestion. I'm searching for a SME who can help. Our auditing docs were contributed by a SME who can no longer contribute. Can you share what problem you are trying to solve? I'll pass along what I find.

**Comment by cronq** [comment]
I guess mostly I'm trying to determine if it's appropriate to turn the auditing on in my environment. The level of detail on these pages is great including written description, recommendations for server vs workstation, and all the event IDs that are created when this auditing is turned on. Just looking for this missing part of the documentation to be added.

**Comment by fate0521** [comment]
It would be nice to see this page added since MS had already done a blog on it in regards to credential theft.

https://blogs.technet.microsoft.com/nathangau/2018/01/25/security-monitoring-a-possible-new-way-to-detect-privilege-escalation/

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by Reeced40** [comment]
@cronq @fate0521 Thank you for the information, I will have the article updated soonest.

**Comment by mypil** [comment]
@cronq  - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by fate0521** [comment]
Thanks!

**Comment by cronq** [comment]
It's been 6 days and I don't see the update. Should I keep waiting?

![image](https://user-images.githubusercontent.com/36086463/58117724-350bf900-7bcd-11e9-971e-6bb30b0ddbf2.png)

**Comment by illfated** [comment]
Thank you for pointing that out. It is somewhat unusual to see the change not migrating to the public Docs page within 6 days after the merge, but in this case, we have to give it an extra day to see if the docs.microsoft.com page will update tomorrow or later today.

**Comment by cronq** [comment]
Well, it's been another couple days and no update is posted...

**Comment by mypil** [comment]
@cronq - The document content has been updated based on the changes added in the merged [PR](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3697/files) .

You can see the Note added under the Detailed Tracking section of the article.

**Comment by cronq** [comment]
I see. The reason I wasn't seeing it was because my request was for a linked page. **Literally** every other advanced audit policy has a separate page describing what it is, the event volume, audit recommendations for 'general' and 'stronger', and a list of event IDs (ok, some don't have all the details, but that all have at least a page to themselves). My 2 cents is create the linked page so the documentation is complete and add the blog as a reference inside of that page. 

Also, as the note doesn't call out 'audit token right adjusted' you can't search for it on the page to understand the 'security monitoring' link has details on this setting.

**Comment by mypil** [comment]
@officedocsbot reopen

**Comment by mypil** [comment]
@cronq - Thanks for the clarification and additional inputs. 

I'm reopening this issue and also discussed with @Reeced40 to help create another PR to incorporate your feedback.

**Comment by Reeced40** [comment]
@cronq Thank you for clarifying. Would this be the link that you would like added for the Audit Token Right Adjusted subcategory under Detailed Tracking? https://docs.microsoft.com/windows/security/threat-protection/auditing/event-4703.

**Comment by mypil** [comment]
@cronq - Can you please respond to the query of Reeced40? Thank you.

**Comment by cronq** [comment]
No. See this page on [Audit Credential Validation](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-credential-validation) as a good example of the content that's missing for Audit Token Right Adjusted. One of the questions I have that would be answered by such a page is if event 4703 is the only event associated with enabling Audit Token Right Adjusted. Thus, your link above would be a link on the page I'm looking for.

**Comment by Reeced40** [comment]
@cronq Thanks, I'll add it to the article soonest.

**Comment by mypil** [comment]
@cronq - The content has been updated to add the changes that you requested for. However, it may take a few days for the merged content to reflect in the document. For your reference, please check on [PR 3845](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3845/files) which contains the revision. Thank you.

**Comment by cronq** [comment]
I'll try and be more clear this time because PR 3845 doesn't hit the mark either. Line 65 of the PR should be this: [Audit Token Right Adjusted](https://docs.microsoft.com/windows/security/threat-protection/auditing/audit-token-right-adjusted)

The problem is the page it should link to (https://docs.microsoft.com/windows/security/threat-protection/auditing/audit-token-right-adjusted) does not exist and that's my point from the beginning. Someone needs to create the content.

**Comment by mypil** [comment]
@cronq - Your request would need the consideration and inputs from the author. Looping in @Justinha on this thread.
@Justinha - can you please share your insights on this?

Thank you.

**Comment by mypil** [comment]
@Justinha @DulceMontemayor - Can you please share your insights on this?

Thank you.

**Comment by mypil** [comment]
@cronq - For this additional feedback that you have in terms of creating the relevant content, kindly submit it via User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**

You might find others have made a similar request that you can add to, or you can open a new one.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by illfated** [comment]
New PR added:
[**Add page for Audit Token Right Adjusted**](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4822) #4822

PR #4822 introduces the following new page for this issue: `audit-token-right-adjusted.md`
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4822/files?short_path=7384bba#diff-7384bba5d82f9a90a54d1fcab927a8d8
The new page replaces the external TechNet blog content.

**Comment by illfated** [comment]
... and the PR has been merged into the `master` branch now, 45 minutes ago (as of the time of this comment).
