### ISSUE TITLE
Clarify "when Windows Defender Antivirus is not present"

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/windows-itpro-docs#2471]
It's not clear what "Initiate definition update on startup" means under "when Windows Defender Antivirus is not present" means.

How is Defender removed? Under what circumstances does that happen?
Why would you have a policy to update something that doesn't exist?
Why is it called "Initiate definition update on startup"?

This is the description in the Group Policy itself:
"This policy setting allows you to manage whether a check for new virus and spyware definitions will occur immediately after service startup."

This does not match up at all.
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c376152e-d0c8-288d-c5e1-2a7c7d4472b4
* Version Independent ID: 3d14560c-b351-86d0-3de4-a059c9cbf6d8
* Content: [Apply Windows Defender Antivirus updates after certain events](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/manage-event-based-updates-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/manage-event-based-updates-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/manage-event-based-updates-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by lindspea** [comment]
@SwiftOnSecurity Thank you for reaching out.  Please have a look at this article and let me know if you need further information - https://docs.microsoft.com/windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus.

**Comment by SwiftOnSecurity** [comment]
@lindspea After re-reading the information I am closing this issue. Thank you for your time.
