### ISSUE TITLE
Allow notifications to disable definitions based reports to Microsoft MAPS

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/windows-itpro-docs#2472]
Please enhance the documentation description of "Allow notifications to disable definitions based reports to Microsoft MAPS"
Additionally, the name does not seem to make sense to me, which implies you're disabling reports being uploaded to MAPS.

This is the description in the ADML:
"This policy setting allows you to configure the antimalware service to receive notifications to disable individual definitions in response to reports it sends to Microsoft MAPS. Microsoft MAPS uses these notifications to disable definitions that are causing false positive reports. You must have configured your computer to join Microsoft MAPS for this functionality to work."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c376152e-d0c8-288d-c5e1-2a7c7d4472b4
* Version Independent ID: 3d14560c-b351-86d0-3de4-a059c9cbf6d8
* Content: [Apply Windows Defender Antivirus updates after certain events](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/manage-event-based-updates-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/manage-event-based-updates-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/manage-event-based-updates-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by lindspea** [comment]
@SwiftOnSecurity Thank you for pointing this out.  If possible, please could you give your suggestions for the wording to be changed for improvement.  Any help is greatly appreciated.

**Comment by SwiftOnSecurity** [comment]
@lindspea Hi, thanks for your time. Something like;
"Allow Microsoft to disable local Defender virus definitions it has identified as causing false-positive detections, through the client's cloud connection to MAPS."

**Comment by Justinha** [comment]
@SwiftOnSecurity Thanks for the suggestions. Our engineering team opened a bug to revisit the name. I think @lindspea is helping submit the doc update in the interim. Thanks to everyone for the help!

**Comment by e0i** [comment]
@officedocsbot close
