### ISSUE TITLE
Install Application Guard URI

### ISSUE THREAD

**Issue by rramoscabral** [MicrosoftDocs/windows-itpro-docs#2476]
I think in line 49, "Install Application Guard, using the [installation]" the correct url is https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/install-wd-app-guard#install-application-guard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15d066f2-0726-bbf9-3425-756ce7dbadee
* Version Independent ID: 03501802-fb28-a89d-a463-e27d2fea7456
* Content: [Testing scenarios using Windows Defender Application Guard in your business or organization (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/test-scenarios-wd-app-guard)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/test-scenarios-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/test-scenarios-wd-app-guard.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@rramoscabral Thank you for your feedback. The link has been updated via referenced PR #2479

**Comment by e0i** [comment]
@officedocsbot close
