### ISSUE TITLE
We now need dual scan?

### ISSUE THREAD

**Issue by natiT** [MicrosoftDocs/windows-itpro-docs#2481]
"but starting with Windows 10, version 1809, language packs can only be installed from Windows Update." Do i understand it right that i cannot Deploy Feature on Demand and Language Packs via SCCM anymore? So i have to enable Dual Scan to install FoD on Clients Systems? That is something the most Companies will prevent because with Dual Scan you also get random Feature Upgrades on the Client Systems when the defer Grace Period ended. 

Can you not handle it otherwise? Via Store for Business for example ? or let us deside via SCCM as it was in the past?

this change is a HUGE Step back. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d423c0e-fd99-9ad5-a11a-45237c2149fc
* Version Independent ID: f30e4101-7a8e-bfa9-a7c0-de7c36499cf5
* Content: [Windows 10 - How to make FoDs and language packs available when you're using WSUS/SCCM](https://docs.microsoft.com/en-us/windows/deployment/update/fod-and-lang-packs)
* Content Source: [windows/deployment/update/fod-and-lang-packs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/fod-and-lang-packs.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by seamonkey420** [comment]
HUGE STEP BACK.  would rather deploy a msu and add manually than try to figure out our GPO to now...
1. ONLY get updates we approve from WSUS
2. But allow FOD to install via WU since we can't host said files on WSUS
3. or create another GPO and script the dism commands w/a wim file.. 

HOW THE FUCK IS THIS BETTER??? FIRE EVERYONE IN the WSUS and Windows Update team imo.

**Comment by GeoSimos** [comment]
@seamonkey420, there is no reason to use profanity or bad language to express your frustration, that way your comments will not be taken into account and may be deleted, what's the gain of it?
You have every right to be disappointed and frustrated as we (the other commentators) and many others in the world are from such poor practices but lets express it politely please.
P.S. Firing fine engineers is not the answer to the problem, there are mechanics and plumbing underneath the shell of Windows -we don't know- and are dictating a change that is irritating for us. Let's see what happens from the engineering team.

**Comment by GeoSimos** [comment]
BTW you may also vote and comment in my feedback item here: https://aka.ms/AA4qrrs

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
Hello @natiT , Thank you for your feedback. Please note you can enable the policy Specify settings for optional component installation and component repair located under Computer Configuration\Administrative Templates\System to allow installation of language packs live. Please note this will not disturb your other windows updates distributions. Like deploying via WSUS or SCCM.

You can also raise your voice and share user feedback option.

@mypil can share details how can you share your feedback.

Thanks.

**Comment by mypil** [comment]
@natiT - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**

You might find others have made a similar request that you can add to, or you can open a new one.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
