### ISSUE TITLE
Setupdiag 

### ISSUE THREAD

**Issue by rranivoson** [MicrosoftDocs/windows-itpro-docs#2484]
Hello, 
I am currently testing setupdiag to solve the upgrade problem. I simulated a full disk, and the upgrade failed. I launched Setupdiag and he finds the logs well. But he cannot detect this basic problem.
Is there another step i missed? 

SetupDiag was unable to match to any known failure signatures.
System Information:
	Machine Name = xxx
	Manufacturer = HP
	Model = HP ZBook 17 G3
	HostOSArchitecture = x64
	FirmwareType = UEFI
	BiosReleaseDate = 20180130000000.000000+000
	BiosVendor = N81 Ver. 01.23
	BiosVersion = N81 Ver. 01.23
	HostOSVersion = 10.0.15063
	HostOSBuildString = 15063.0.amd64fre.rs2_release.170317-1834
	TargetOSBuildString = 10.0.17134.1 (rs4_release.180410-1804)
	HostOSLanguageId = 1036
	HostOSEdition = Professional
	RegisteredAV = Symantec Endpoint Protection,Symantec Endpoint Protection,
	FilterDrivers = 
	UpgradeStartTime = 14/01/2019 17:24:11
	UpgradeEndTime = 14/01/2019 17:26:10
	UpgradeElapsedTime = 00:01:59

error in setupact.log:
2019-01-14 17:26:10, Info                  MOUPG  SetupNotify::Remapping disk full error [0x80070070] -> [0xC19001DF]
2019-01-14 17:26:10, Info                  MOUPG  SetupNotify::Leaving well-known error [0xC19001DF] as-is for WU/Store
2019-01-14 17:26:10, Info                  MOUPG  SetupHost: Reporting error event -> [0x80070070, 0xC19001DF]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ad81361-15d8-0e95-9d5f-090dbf270f10
* Version Independent ID: c0c32397-d5d6-cce1-79fd-c310bec05240
* Content: [SetupDiag](https://docs.microsoft.com/en-us/windows/deployment/upgrade/setupdiag)
* Content Source: [windows/deployment/upgrade/setupdiag.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/setupdiag.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by rranivoson** [comment]
[Logs.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/2756354/Logs.zip)
I forgot the logs file.

**Comment by davisdre** [comment]
Looking at the log entry, looks like your hard drive is full and you need more free space. I recommend you having at least 10GB and then try the upgrade to 1803 again.

**Comment by rranivoson** [comment]
thank you, but, that's not the problem. I simulated a disk full during the upgrade in place to test the setupdiag software. it has not detected the problem.

**Comment by davisdre** [comment]
So are you wanting the SetupDiag tool to identify the error for you? Cause I know not all errors will show up and the event log entry and the setuperror.log are to good resources. And for the Zbook 17 series I know if you are using the later driver pack, a outdated driver always cause some upgrade issues for some reason.

Very Respectfully,

Drew Davis

*Please ignore my incorrect spelling and grammar, via my phone*
~ Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rranivoson** [comment]
i need to integrate it in my task sequence because i have 12000 pcs to upgrade . There are 53 errors that it can detect and report. disk full is one of this. I need this tool to report correctly at least these errors.
thank you. 
i'm not good in english, so...

**Comment by davisdre** [comment]
Gotcha. I use the 'Check Readiness Upgrade' part of the task sequence template. That way, it catches it before the upgrade event starts.

Very Respectfully,

Drew Davis

*Please ignore my incorrect spelling and grammar, via my phone*
~ Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rranivoson** [comment]
I know, but the problem is: Why setupdiag didn't report this simple error ? can i rely on it ?

**Comment by davisdre** [comment]
I understand. I can tell you I went through two upgrades without even using the SetupDiag tool. I'm so use to just looking at the error that was reported in the windows event log or going by what SCCM client reported back; I guess I don't heavily rely on that tool since I already know the common error codes and what they are related too. I do know the SetupDiag tool has been improving.

Very Respectfully,

Drew Davis

*Please ignore my incorrect spelling and grammar, via my phone*
~ Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ScottHendrix-MSFT** [comment]
While I can certainly update SetupDiag with a  rule to catch this particular issue.  The reason it didn’t is because you’ve bypassed the standard compatibility checks that would have prevented you from upgrading in the first place (due to disk space issues) by specifying the /quiet command line parameter.  SetupDiag would have caught the compatibility disk space block and reported that as the issue, had you not specified the /quiet switch.  I’ll look into adding a generic catch all rule around early down-level failures like this one for v1.5 though.
-Thanks for reporting this!

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by RAJU2529** [comment]
@rranivoson, Tomorrow i give correct commands to get all details.

**Comment by VLG17** [comment]
@rranivoson as far as i can see, @ScottHendrix-MSFT already provided an explanation as to why this has happened and also mentioned that he will address this in a future version (which is already out).

I would advise you to test this again (with and without the /quiet switch)

**Comment by ScottHendrix-MSFT** [comment]
Pick up the new 1.5 release of [SetupDiag](https://docs.microsoft.com/en-us/windows/deployment/upgrade/setupdiag), I've added a rule to catch this type of failure.

**Comment by rranivoson** [comment]
Thank you, i'll test it.
