### ISSUE TITLE
TenantId CSP - need clarification!

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#2488]
Missing deployment variables/Data type for TenantId 
  
TenantId
A globally unique identifier (GUID), without curly braces ( { , } ), that is used as part of Windows Hello for Business provisioning and management.

There is no Deployment data on this? 

I used String and "guid" however that wont work.

Can someone provide Syntax for this Passport for work CSP policy, TenantID?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4180b6e-2786-ffb0-8f92-e4456dc343c9
* Version Independent ID: 7722d866-c095-b806-1da8-17e00cfe9a0a
* Content: [PassportForWork CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/passportforwork-csp)
* Content Source: [windows/client-management/mdm/passportforwork-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/passportforwork-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by Tdiwestyguy** [comment]
@andreabichsel Hi Andrea, can you comment on this article?  Seems Heidi is in a new role.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Tdiwestyguy - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @Tdiwestyguy ,
GUID should be entered without quotes.
Are you sure you have entered the correct GUID? The one that is returned by (Get-AzureAccount).ActiveDirectories.ActiveDirectoryTenantID ?

Thank you

**Comment by Tdiwestyguy** [comment]
Hi,

Thanks!

Customers should be clear how to obtain that.

Please place the value dependency (Format) and process to get that output for customers Tenant ID on the article, it would be very useful to many.

Thanks,
Alex

________________________________

**Comment by Tdiwestyguy** [comment]
It would be good to provide the article, https://docs.microsoft.com/en-us/powershell/module/servicemanagement/azure/get-azureaccount?view=azuresmps-4.0.0 and link it to the TenantID syntax command definition as Example, to obtain the ID, go here:
[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/powershell/module/servicemanagement/azure/get-azureaccount?view=azuresmps-4.0.0>
Get-AzureAccount (Azure) | Microsoft Docs<https://docs.microsoft.com/en-us/powershell/module/servicemanagement/azure/get-azureaccount?view=azuresmps-4.0.0>
The Get-AzureAccount cmdlet gets the Azure accounts that are available to Windows PowerShell. To make your accounts available to Windows PowerShell, use the Add-AzureAccount or Import-PublishSettingsFile cmdlets.
docs.microsoft.com


________________________________

**Comment by mypil** [comment]
@Tdiwestyguy - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
