### ISSUE TITLE
Screenshot is outdated

### ISSUE THREAD

**Issue by Leon99** [MicrosoftDocs/windows-itpro-docs#2489]
It looks very different these days

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@Leon99 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by VLG17** [comment]
@Leon99 the experience depends on the error that you get and also on the OS edition that you are using. What OS are you getting the error on and how does it look like for you?

**Comment by Leon99** [comment]
It's been a while, I can't reproduce it right now. I think I had it on Win10Pro. Would you be able to check it on your side?

**Comment by e0i** [comment]
> It's been a while, I can't reproduce it right now. I think I had it on Win10Pro. Would you be able to check it on your side?

cc @VLG17

**Comment by illfated** [comment]
@Leon99 : would it be practical to try deliberately forcing a PIN creation error by attempting to change the PIN while being disconnected from the network, or using a very slow connection?

**Comment by illfated** [comment]
I found a couple of images, but I am not in a position to verify the Windows version or type of machine:
- Github issue ticket page: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3092
- https://answers.microsoft.com/en-us/windows/forum/all/we-cant-connect-to-server-to-setup-you-pin-right/a0536687-7db8-4ab4-95e6-be2ff7d97dd7?auth=1

There was also a recent (14 days ago) comment regarding PIN code error format in https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2900#issuecomment-511874256 .

**Comment by illfated** [comment]
![6f409915-a504-44e2-b983-1b587c22d409](https://user-images.githubusercontent.com/38162891/62212383-e33bd800-b3a0-11e9-935c-986603f4492c.png)

**Comment by e0i** [comment]
@officedocsbot close
