### ISSUE TITLE
Miracast improvements 

### ISSUE THREAD

**Issue by archer1977** [MicrosoftDocs/windows-itpro-docs#2490]
I've been over the article and while there are some improvements to miracast listed, I have noticed since updating to 1809 that the reliability of getting a successful connection first time is almost 100% on our test laptops - sometimes users have to try 8-10 times before successfully connecting.  Most of these users are running 1709.  We would prefer to go to 1803 before 1809 as there are still some issues around 1809 (Trend AV and other driver related issues) but if you could advise of what improvements were made behind the scenes so we can present our findings to mgmt - it appears alot more has changed than just the connection bar.  Thanks

**Comment by illfated** [comment]
Could you please link the exact article, so the docs team has the correct documentation to work out a response?

**Comment by archer1977** [comment]
apologies this was forhttps://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809  
Under the Heading Wireless Projection

not sure on the details exactly we have been looking at miracast for the last few months, i'm sure there was something with drivers as one of our users is using a non standard laptop (HP Spectre V132TU) all others are HP Elitebook x360 1020 G2 laptops.  The Spectre connects flawlessly (running 1709).  But we've had all sorts of dramas with the Elitebooks.

I have been working with HP and after updating to the latest intel builds we went from approx 60% "first go" connection success rate to about 80%.  However this was still not acceptable to mgmt.  HP then suggested moving to 1803 however we saw no improvement.  Then as a complete guess I upgraded one of them to 1809 and it now connects 100% first go.  I have noticed on 2 or 3 occasions there is a delay in connecting to the external screen however it seems to keep re-trying or the timeout window may have been increased.  This is just based on my experience and other than results of numerous tests I have not technical data (packet captuers or similar) to back this up.

**Comment by illfated** [comment]
https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809
(seeing that the lost space in front of your URL did not cause the link to activate)

All you need to do now, is to wait for a response from one of the team members.
It may not be within the scope of their work, so you may want to post on the Feedback Hub (Windows Key + **F** ) too.

**Comment by archer1977** [comment]
Thanks for that.  this was the only way i could find to get in touch with anyone related to documentation who might be able to get some more detail on that.  I'll try to be patient :)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@archer1977 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@archer1977 Keeping in mind that it worked flawlessly with a standard desktop (only affects HP Elitebook x360 1020 G2 laptops) and that updating the Intel drivers rose the connection rate success on the first go, i would argue that there was something significant changed in Windows 1809 and above.

Have you updated the rest of the laptops in the meantime? Do you still see any issues?

**Comment by archer1977** [comment]
@VLG17 
We have a fleet of about 25 of the HP Elite book x360 1020 G2 laptops.  we consistantly see miracast connection rates of about 60% on first attempt.  Usually after 5 attempts we finally connect.
Since upgrading to 1809 (have updated about 12 of these so far - i am hoping to upgrade the remaining fleet by the end of July) we have seen connection success on first attempt up close to 75% and obtain a successful connection within 3 attempts in 99% of cases.
We have recently just purchased another group of laptops (same model laptop but the G3) which are running 1803 out of the box and have been unable to fault them.  I am certain the issue we are seeing is chipset based however based on my tests I am confident that something in 1809 has improved or increased the timeouts or similar within the OS which has seen an improvement in our miracast experience.

**Comment by mypil** [comment]
@archer1977 - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via [Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by illfated** [comment]
@archer1977 : Thank you for posting about your issue in the first place. Even if this did not lead to any immediate change in the documentation, I feel confident that others will find this page in web page searches at a later time and be able to draw at least some useful information from it.

**Comment by mypil** [comment]
@officedocsbot close
