### ISSUE TITLE
RemoteFX vGPU in Hyper-V is no longer supported on version 1809 and higher

### ISSUE THREAD

**Issue by GoldenHashtag** [MicrosoftDocs/windows-itpro-docs#2491]
Except for DDA, what are the replacements for it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5da56626-d2d9-ae41-3ebb-f4e75a1a9038
* Version Independent ID: 5963ceee-7398-f0b4-1649-6e744a424174
* Content: [Windows 10, version 1809 - Features that have been removed](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-1809-removed-features)
* Content Source: [windows/deployment/planning/windows-10-1809-removed-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-10-1809-removed-features.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@GoldenHashtag  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@GoldenHashtag there are no other supported alternatives at the moment, other than Discrete Device Assignment.

But do keep in mind the following (although not yet released, it is another future alternative):

![image](https://user-images.githubusercontent.com/41186174/60014511-daf9ca00-9689-11e9-9e2c-4a59240a252c.png)

You can find more online around GPU-P.

**Comment by mypil** [comment]
@GoldenHashtag - From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
