### ISSUE TITLE
GDPR impact

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/windows-itpro-docs#2492]
According to https://blogs.technet.microsoft.com/upgradeanalytics/2018/07/02/upgrade-readiness-re-enabled/, Windows 8.1 data, along with Windows 7 app usage and IE site discovery data is not available for EU devices. Will be nice to see those details here for EU customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4273a259-c3c7-dca7-6353-954068d740a7
* Version Independent ID: 1084ea77-95c4-4e4a-da6c-f4d8668f9ebf
* Content: [Enrolling devices in Windows Analytics (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started)
* Content Source: [windows/deployment/update/windows-analytics-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-get-started.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Thanks for that; checking on this.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jaimeo - Do you have any updates on this?

**Comment by VLG17** [comment]
@juanand Although i fully understand that it would be good to have visibility over those details, there has not been any change regarding this topic.

What i would recommend is to give official feedback on this topic by using [Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub).

**Comment by jaimeo** [comment]
@iceorbital or @zdvorak do you have any input on potential changes to this topic regarding this question?

**Comment by mypil** [comment]
@iceorbital @zdvorak - We would like to follow up. Can you please share your insights?  Thanks.

**Comment by mypil** [comment]
@jaimeo @iceorbital @zdvorak - Do you have any updates on this?

cc: @LauraWi

**Comment by jaimeo** [comment]
https://github.com/MicrosoftDocs/windows-docs-pr/pull/647

**Comment by jaimeo** [comment]
This PR is live.

**Comment by mypil** [comment]
@juanand - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
