### ISSUE TITLE
Multi Forest Support? 

### ISSUE THREAD

**Issue by JBines** [MicrosoftDocs/windows-itpro-docs#2493]
I think the title says it all... :)  Thank in advance. 

Multiple forests, single Azure AD tenant 
See: https://docs.microsoft.com/en-us/azure/active-directory/hybrid/plan-connect-topologies#multiple-forests-single-azure-ad-tenant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12823601-7426-a768-e72f-866b150baccd
* Version Independent ID: c1f993e3-a405-6860-8ab1-7b3d387b4631
* Content: [Hybrid AAD Join](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/user-driven-hybrid)
* Content Source: [windows/deployment/windows-autopilot/user-driven-hybrid.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/user-driven-hybrid.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by hammonjr** [comment]
Did you ever test this or find out an answer on this? I have the same question. Thanks!

**Comment by JBines** [comment]
the answer is.... i still need to test but I'm a bit short on time ATM. Also I haven't got a clear answer from Engineering if this could work or more importantly if it is supported. 

Sorry I can't be of more help if I get any more info I'll reply to this thread.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@JBines  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@JBines Although i am inclined to believe that multi-forest (on-premises) will work in an Azure AD Join scenario (given that they all sync to only one Azure AD tenant), i will have to confirm if this is also supported.

**Comment by mypil** [comment]
@greg-lindsay - can you please share your insights on this issue?

Thank you.

**Comment by greg-lindsay** [comment]
See https://docs.microsoft.com/en-us/azure/active-directory/hybrid/plan-connect-topologies#multiple-forests-single-azure-ad-tenant

This should work, but if I find out differently I will post here.

**Comment by JBines** [comment]
@greg-lindsay thank for the reply. As it's been a couple of months and the orginal page where I posted seems to have disappeared. 

The question was does the Intune Connector for Active Directory support Multi Forest? 

If so that's great news :) if not sorry for the confusion

**Comment by mypil** [comment]
@officedocsbot close

**Comment by JBines** [comment]
So... Does the Intune Connector for Active Directory support Multi Forest?

Answer: This should work

I guess we have to test. It would be nice if these requirements were clarified in a doc. But i'll reply when I test and find out more
