### ISSUE TITLE
Cannot not run sysprep on windows 10 version1607

### ISSUE THREAD

**Issue by martinl12** [MicrosoftDocs/windows-itpro-docs#2497]
I tried it on Windows 10 1607 LTSB but after sysprep it hangs at the setup screen. Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9ca7cb6-32cb-1517-a9de-c36046955d45
* Version Independent ID: 91041e39-007e-f481-0cd4-177b4039ae12
* Content: [Create mandatory user profiles (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/mandatory-user-profile)
* Content Source: [windows/client-management/mandatory-user-profile.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mandatory-user-profile.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
Hi @martinl12 You need to [contact Microsoft Support](https://support.microsoft.com/en-us/contactus/) for assistance, or you can [ask other users in the IT Pro forum for Windows 10](https://social.technet.microsoft.com/forums/en-us/home?category=windows10itpro).
