### ISSUE TITLE
Does WSUS really respect the clients channel/branch setting?

### ISSUE THREAD

**Issue by bigben386** [MicrosoftDocs/windows-itpro-docs#2499]
We use WSUS 2012 r2. All my clients are set to semi-annual channel in the wufb gpo but if I approve the 1809 update, then they will immediately install the 1809 update which is currently semi-annual (targeted). I have the "Do not allow update deferral policies to cause scans against Windows Update" gpo enabled. If i enable "Do not connect to any Windows Update Internet locations," then update scans fail on the clients.

These notes seem to be a bit contradictory
"WSUS respects the client’s servicing branch. If you approve a feature update while it is still Current Branch (CB), WSUS will install the update only on PCs that are in the CB servicing branch. When Microsoft releases the build for Current Branch for Business (CBB), the PCs in the CBB servicing branch will install it."
and
"WSUS does not honor any existing month/week/day deferral settings for CB or CBB. That said, if you’re using Windows Update for Business for a computer for which WSUS is also managing updates, when WSUS approves the update, it will be installed on the computer regardless of whether you configured Group Policy to wait."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe35c19c-fd29-8405-ad9f-441204812e6b
* Version Independent ID: fc0fe6ce-4b92-3cff-d6fa-c791ba2df466
* Content: [Deploy Windows 10 updates using Windows Server Update Services (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-manage-updates-wsus)
* Content Source: [windows/deployment/update/waas-manage-updates-wsus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-manage-updates-wsus.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
Hello @bigben386 , Thank you for your feedback on the doc. The statements you have mentioned are applicable only when you are setting up an automatic feature update and deploy option for Windows 10 (https://docs.microsoft.com/en-us/windows/deployment/update/waas-manage-updates-wsus#automatically-approve-and-deploy-feature-updates)

That being said, when you will setup auto feature update rule, an update is available following the rule that will be deployed on the selected group. If you have set up policies to defer the deployments that will not be applicable once WSUS auto feature update deployment rule has been set up.

Thanks.

**Comment by bigben386** [comment]
Right that has been my experience in practice but the note in that sections says quote

> WSUS respects the client’s servicing branch. If you approve a feature update while it is still Current Branch (CB), WSUS will install the update only on PCs that are in the CB servicing branch. When Microsoft releases the build for Current Branch for Business (CBB), the PCs in the CBB servicing branch will install it.

That simply is not the case in practice. Clients that pull the feature updates from wsus install the update immediately after it is approved regardless of the wufb brach settings. Also there is no auto approval option for channel/branch availability so that note should be removed or changed to say that wufb branch settings do not apply to feature updates through wsus.

**Comment by joinimran** [comment]
Thank you @bigben386 , I have updated the doc and forwarded this for approval to our team. Once its approved, the changes will reflect in the doc. 

Thanks.

**Comment by mypil** [comment]
@bigben386 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
