### ISSUE TITLE
Settings are not persistent across upgrades

### ISSUE THREAD

**Issue by gallan13** [MicrosoftDocs/windows-itpro-docs#2501]
Just upgraded to Windows 10 version 1809 and the restrict local storage policy is not being applied. Checked the registry and the key values are there, yet I have full access to the file system now. Not good!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14b376e2-39bd-faca-a76c-dd21bad8d8fd
* Version Independent ID: a76cabb0-59b9-7e97-6603-eec7d37f1fd4
* Content: [Set up a shared or guest PC with Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/set-up-shared-or-guest-pc)
* Content Source: [windows/configuration/set-up-shared-or-guest-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/set-up-shared-or-guest-pc.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
Hi @gallan13 Please report the problem using the Feedback Hub so the engineering team can be made aware of the issue, thanks!
