### ISSUE TITLE
Great response

### ISSUE THREAD

**Issue by Malibu7012** [MicrosoftDocs/windows-itpro-docs#2502]
Most people have no idea what they are talking about.  I will agree you have covered 85% of any issues possible and offer a salute and thanks for this expanded resolution you should copy and paste this too about 80% of these boards that default to format start over.  Now my question is i have the blue screen non of the options will fix the issue and I absolutely do not want to reinstall or alter windows at this time do to I am using optane memory.  My error is do to I did some updates using the restart later and now on boot I am getting a multiple irp instance error file error states "pnp0c33.devicedesc"  no way to start this windows but I do have is disc along with a honeypot shell windows 10 that boots.  I still have not been able to repair without having to alter files wich will inevitably give me optane or HD error initiating a secure lock and erase at that point even Intel has confirmed it's futile as the drive will lock until it has been formatted along with blocking any and all other os from starting.  Any ideas ?
Brandon Joseph Wysocki,
VR LLC. IT professional and lead programmer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc264df-cbd1-ac1f-3926-841fcab7dc31
* Version Independent ID: 67c2aea4-0d28-3d8e-e935-8af05291c94e
* Content: [Advanced troubleshooting for Windows boot problems](https://docs.microsoft.com/en-us/windows/client-management/advanced-troubleshooting-boot-problems)
* Content Source: [windows/client-management/advanced-troubleshooting-boot-problems.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/advanced-troubleshooting-boot-problems.md)
* Product: **w10**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **elizapo**

**Comment by e0i** [comment]
@Malibu7012

The issues section of this repository is intended for product documentation issues only.

Please consider opening a support ticket by the following link below for your question so that it gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot close

**Comment by RAJU2529** [comment]
for blue sceen issues, I can able to the find corrupted drivers by using windbg tool with memory dump
