### ISSUE TITLE
Why administrative credentials are required??

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/windows-itpro-docs#2503]
Your documentation for the prerequisites is not totally correct. You have not mentioned that local administrator credentials are required to run the tool. But instead of correcting the documentation, please fix the tool.
In year 2019 we should not have anymore tools which requires both: Local Administrator credentials AND internet access. I could not even see why the admin credentials are required to run the tool. Of course the installation requires that, but not making the image.
Or if by some reasons I need local admin rights to run the tool, I still should be able to run the tool (and download the offline copy for making the image) with my regular user account which do have access to internet, but not administrative credentials.
Welcome to a bit more secure world :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e78f073c-9f6b-b9d2-cd94-0a31998f10d9
* Version Independent ID: 5beaeca4-3d07-c65c-018b-a88cda5ceb9a
* Content: [Using the Surface Hub Recovery Tool](https://docs.microsoft.com/en-us/surface-hub/surface-hub-recovery-tool)
* Content Source: [devices/surface-hub/surface-hub-recovery-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/surface-hub-recovery-tool.md)
* Product: **surface-hub**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@Petri-X I checked with the product team, and they said the Surface Hub Recovery Tool doesn't require an admin account to run. If you're having problems running the tool, let them know via the Feedback Hub so they can investigate, thanks!
