### ISSUE TITLE
This document needs to be updated to reflect SCCM 1810

### ISSUE THREAD

**Issue by RPanick** [MicrosoftDocs/windows-itpro-docs#2506]
The document does not match what I see when I try running the process with SCCM 1810.  In particular there appear to be items in the documentation that are not in the wizard.  In particular the state migration portions appear to no longer exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17bfe927-f7b7-608b-8537-5c2274ccdced
* Version Independent ID: 5dd9abca-92d9-fbb2-6796-d1f6b9ab3c8b
* Content: [Windows Autopilot for existing devices](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/existing-devices)
* Content Source: [windows/deployment/windows-autopilot/existing-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/existing-devices.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by lindspea** [comment]
@RPanick Thank you for reaching out and helping improve MS Docs.  Please could you specify what is missing, or what should be removed from this article, and I can have it updated soonest.

**Comment by RPanick** [comment]
I’ve been through the page a couple of times and I can’t find where I had found a difference.  Please close the comment.

Bob Panick
734-925-1523

**Comment by e0i** [comment]
@RPanick Marking the issue as resolved via your suggestion. Thank you for following up.

@officedocsbot close
