### ISSUE TITLE
Bloatware or required

### ISSUE THREAD

**Issue by arcotek-ltd** [MicrosoftDocs/windows-itpro-docs#2508]
As you refuse to listen to your ENTERPRISE customers and provide a bloat-free enterprise version of Windows 10, would you kindly add the column "required" to your tables  above. An "X" would mean the app is required for system stability /compatibility, and no mark means it can be removed with no detrimental effect. This would at least remove some of the guesswork from the laborious task of creating a clean Windows image.

For instance, is OfficeHub required for the functionality of Office, or is it no more than an advert to get people to buy it. I bet more hours have been spent (wasted) by millions of admins across the globe making Windows 10 as "Enterprise-ready" as is possible, than Bill has cents in his bank account.

Most of these things, including Edge and Cortana should be an optional ADD-on, not an impossible remove.

I say again. "What on earth is Xbox doing in your flagship, ENTERPRISE product?"

If you don't believe me, just see how many hits Google returns on "Remove bloatware from Windows 10".

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce0131fb-6b3a-5905-1738-253cf37e3b2d
* Version Independent ID: cab448be-54ae-539e-22ba-3d202a468d4f
* Content: [Windows 10 - Apps](https://docs.microsoft.com/en-us/windows/application-management/apps-in-windows-10)
* Content Source: [windows/application-management/apps-in-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/apps-in-windows-10.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
Thanks for your feedback. We're not able to add a required column at this time. Thanks, Liza

**Comment by SuHwak** [comment]
Yet another sign that Microsoft is not listening to their enterprise customers.

**Comment by OmegatronX** [comment]
I would assume the "System Apps" being "integral" as it says are the ones you can't remove, however the Print 3D is in that list, and it can apparently be uninstalled via the UI.

Let's just compile the list ourselves. I'm going to assume anything that you can uninstall from the UI is not a problem to remove (that list is longer in 1903), and then we can go through and test the rest one by one and see if they cause any problems to remove.

https://github.com/OmegatronX/Windows-10-Bloatware-Can-Be-Removed/blob/master/List
