### ISSUE TITLE
The interface declarations such as IConfigServiceProvider2, ICSPNode do not exist in any header file

### ISSUE THREAD

**Issue by emrekanlikilicer** [MicrosoftDocs/windows-itpro-docs#2509]
Looks like they have been removed from Windows SDK. They were previously in cmgrcsp.h. Is creating a custom configuration service provider deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 393fcbf0-cfb3-e921-b96d-79abda94bd88
* Version Independent ID: 634fbc24-d5f3-70b6-3db1-76c0ad853977
* Content: [Create a custom configuration service provider](https://docs.microsoft.com/en-us/windows/client-management/mdm/create-a-custom-configuration-service-provider)
* Content Source: [windows/client-management/mdm/create-a-custom-configuration-service-provider.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/create-a-custom-configuration-service-provider.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by Danielramn1984** [comment]
Daniel Ramos Navarro
RAND840816AW0
danielramn17@gmail.com

**Comment by bmwilson1978** [comment]
I too can't find this, would you happen to have an example CSP you could share?

**Comment by emrekanlikilicer** [comment]
Hi, is there any update we can get on this?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@emrekanlikilicer  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@emrekanlikilicer @bmwilson1978 you can find here the list of supported CSPs in Windows 10: https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference

You can create customized CSPs with the help of [Windows Configuration Designer](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/how-it-pros-can-use-configuration-service-providers#csps-in-windows-configuration-designer)

**Comment by mypil** [comment]
@emrekanlikilicer @bmwilson1978 - From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by bmwilson1978** [comment]
> @emrekanlikilicer @bmwilson1978 you can find here the list of supported CSPs in Windows 10: https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference
> 
> You can create customized CSPs with the help of [Windows Configuration Designer](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/how-it-pros-can-use-configuration-service-providers#csps-in-windows-configuration-designer)

I think you're getting confused, a Custom Configuration Service Provider processes CSP settings it's responsibile/developed for.  If you wish to make your own custom CSP settings, you need to have a Custom Configuration Service Provider to process them on the device.   For example, say I have App123 and I want to define some settings for it, I need a Custom Configuration Service Provider install on the device to take those CSP settings I define and configure them appropriatley on the device so my App123 can leverage them.   Does this make sense?

That URL of the support CSPs for Windows 10 are based on the fact Windows 10 already has the process (a Custom Configuration Service Provider) for applying those settings of which the related components and features then utilise.

**Comment by bmwilson1978** [comment]
> @emrekanlikilicer @bmwilson1978 - From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been answered, please re-open this issue.
> 
> Thank you for your contribution to make the docs better! Much appreciated!

I don't think it has been answered - there appears to be some misunderstanding on the purpose of creating a Custom Configuration Service Provider.  See my previous response to @VLG17 .

**Comment by mypil** [comment]
@bmwilson1978 - Thank you for providing additional feedback. Let me loop in the doc owner to get more information to hopefully answer your query. 

@ManikaDhiman - Can you please share your insights on this issue? Can you please confirm if the Custom Custom Configuration Service Provider is deprecated in newer Windows 10 builds?

Thank you.

**Comment by ManikaDhiman** [comment]
@bmwilson1978 and @mypil: I checked with the product team and they confirmed that the management extensibility via CSPs is not currently supported. Hence, we are removing the articles related to custom configuration service provider from the CSP doc set. Hope this helps.

**Comment by mypil** [comment]
@bmwilson1978 - From our understanding, the issue has been answered by ManikaDhiman. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
