### ISSUE TITLE
"Update Readiness" in "Set diagnostic data levels" section

### ISSUE THREAD

**Issue by mariuszo-at-microsoft-com** [MicrosoftDocs/windows-itpro-docs#2510]
"Set diagnostic data levels" section mentions "Update Readiness" (twice) while it should say "Upgrade Readiness" or even better "Upgrade Readiness and Update Compliance" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4273a259-c3c7-dca7-6353-954068d740a7
* Version Independent ID: 1084ea77-95c4-4e4a-da6c-f4d8668f9ebf
* Content: [Enrolling devices in Windows Analytics (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started#set-diagnostic-data-levels)
* Content Source: [windows/deployment/update/windows-analytics-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-get-started.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Fixed.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Closing as the issue has been addressed via the commit: https://github.com/MicrosoftDocs/windows-itpro-docs/commit/a7223d7a54edd7e046ef5c21aab324df5c73c285#diff-377bb5873a1120a3604c39267a6d0e97R110

**Comment by e0i** [comment]
@officedocsbot close
