### ISSUE TITLE
What's new in Windows 10, version 1809

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/windows-itpro-docs#2511]
Where can one find the "What's new in Windows 10, version 1809" section now that 1809 is released?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e97678b-eaff-f61c-68d7-8af45f2b2396
* Version Independent ID: 1eb2afc3-9522-0330-a67e-826d7381fb8a
* Content: [Windows Defender Antivirus](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-in-windows-10)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-in-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-in-windows-10.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@adrianwells  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@adrianwells according to the change log for [1809](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1803) and [1903](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1903) there are no changes related to Windows Defender Antivirus.

There are of course changes related to ATP for example, but the article you mentioned is targeted at Windows Defender Antivirus.

**Comment by adrianwells** [comment]
@VLG17 thanks for the reply. Assumed there were changes to Windows Defender Antivirus with Windows 10 1903 which is why this issue was opened for this document. It is surprising to learn this as prior releases noted in this document contain a "What's new in Windows 10" section for each feature update. Maybe further explanation is needed on this document or references to Windows Defender ATP?

**Comment by mypil** [comment]
@Dansimp - Can you please share your insights on this issue?

Thank you.

**Comment by mypil** [comment]
@adrianwells - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
