### ISSUE TITLE
Description of different enrollment modes

### ISSUE THREAD

**Issue by skille** [MicrosoftDocs/windows-itpro-docs#2518]
Could you please describe the different ennrollment modes: “mdm”, "awa", "aadj" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39ae2ccd-9f3f-dcb5-3a20-46b1b4fd3d53
* Version Independent ID: b381c208-94b1-2d22-ef16-a57c138a7d72
* Content: [MDM enrollment of Windows-based devices](https://docs.microsoft.com/en-us/windows/client-management/mdm/mdm-enrollment-of-windows-devices)
* Content Source: [windows/client-management/mdm/mdm-enrollment-of-windows-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/mdm-enrollment-of-windows-devices.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by lindspea** [comment]
@skille Thank you for reaching out.  aadj - Azure Active Directory joined, mdm - Mobile Device Management. Have a look at this doc and let me know if you have any further questions - https://docs.microsoft.com/windows/client-management/mdm/new-in-windows-mdm-enrollment-management.

**Comment by e0i** [comment]
@skille 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
