### ISSUE TITLE
Clarify the requirements

### ISSUE THREAD

**Issue by tijs0289** [MicrosoftDocs/windows-itpro-docs#2521]
Please, clarify the requirements. What does this mean?
Enterprise has MDM service already configured (which steps are meant by this)? MDM authority set to Intune in Azure under Azure &gt; Intune &gt; MDM, with users set to ALL?
Enterprise AD must be registered with Azure AD
Does this mean AD connect? What in case of Azure AD DS?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy](https://docs.microsoft.com/nl-nl/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by jdeckerms** [comment]
@tijs0289 I checked with the product team, and they recommend this article for details: [Azure Active Directory integration with MDM](https://docs.microsoft.com/en-us/windows/client-management/mdm/azure-active-directory-integration-with-mdm). I will add the link to the topic.
