### ISSUE TITLE
UseBiometrics

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#2522]
Can someone please provide the correct Custom CSP for enabling the Biometrics and Enhanced Anti Spoofing?

i've tried 
./Vendor/MSFT/PassportForWork/Biometrics/FacialFeatureUseEnhancedAntiSpoofing
./Device/Vendor/MSFT/PassportForWork/Biometrics/FacialFeatureUseEnhancedAntiSpoofing
with boolean, integer (1 and 0) string (&lt;enabled/&gt;) and a few more combinations but all i get is catastrophic failure.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4180b6e-2786-ffb0-8f92-e4456dc343c9
* Version Independent ID: 7722d866-c095-b806-1da8-17e00cfe9a0a
* Content: [PassportForWork CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/passportforwork-csp)
* Content Source: [windows/client-management/mdm/passportforwork-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/passportforwork-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@Heidilohr Any updates with this issue? We would like to follow-up. Thanks.

**Comment by Heidilohr** [comment]
@e0i Unfortunately, I'm no longer the writer responsible for CSPs. However, I've forwarded this issue along to the team who currently updates CSP content. They should get back to you soon.

**Comment by sveinungre** [comment]
I'm also waiting for reply. Do we need to register support case?
There is also this link that gives the impression to use UsePassportForWork instead of PassportForWork:
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-manage-in-organization

**Comment by e0i** [comment]
@manikadhiman Would you be able to provide guidance with this issue? Thanks.

**Comment by ManikaDhiman** [comment]
Hi @e0i, Product team had suggested to refer to the PassportForWork CSP DDF for this issue. According to DDF, the supported value (allowed value) for "FacialFeaturesUseEnhancedAntiSpoofing" is True/False. 
Hope this helps!
