### ISSUE TITLE
Syntax error in example

### ISSUE THREAD

**Issue by DavidVerbruggen** [MicrosoftDocs/windows-itpro-docs#2527]
&lt;member name="Contoso\Alice"&gt;
should be &lt;member name="Contoso\Alice" /&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0c28c15-f0be-d732-4d9e-cf5df5e64e8b
* Version Independent ID: 17eba45f-d200-e656-42b9-e1a512931eea
* Content: [Policy CSP - RestrictedGroups](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-restrictedgroups)
* Content Source: [windows/client-management/mdm/policy-csp-restrictedgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-restrictedgroups.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @DavidVerbruggen 

The problem that you have mentioned has been addressed via the following commit and merged into documentation:  https://github.com/MicrosoftDocs/windows-itpro-docs/commit/1cc4a540a503203e542a85190e4bf2ba5b1bb3e7

Thank you for taking the time to provide feedback.

**Comment by e0i** [comment]
@officedocsbot close
