### ISSUE TITLE
Non-FQDN Resources

### ISSUE THREAD

**Issue by bwaut353** [MicrosoftDocs/windows-itpro-docs#2532]
Hi,

On our firewall, we are unable to use wildcards to create rules. I was wondering if there is a list of all the IPs or Subdomains for the following Non-FQDNs that are listed.

*.oms.opinsights.azure.com
*.blob.core.windows.net
*.azure-automation.net
*.ods.opinsights.azure.com 

Thanks,
Brian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4ed2b3-0390-4d53-2450-14995ee8b0b0
* Version Independent ID: 91b5bb3e-55d4-6a8e-c16d-094f15c28ee7
* Content: [Onboard servers to the Windows Defender ATP service](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-server-endpoints-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/configure-server-endpoints-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/configure-server-endpoints-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@mjcaparas Any updates with this request? We would like to follow-up. Thanks.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by mjcaparas** [comment]
Hi, please see if this topic helps: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet
