### ISSUE TITLE
odd text

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#2535]
Was this written correctly?

From this article, it says:

Starting with Windows 10, version 1709, "Windows Update for Business" was changed to correctly reflect its association to "Windows Update for Business"..

So, Starting Windows 10, WUFb was changed to reflect its association with, itself?

That's an odd statement. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2056993d-a700-fba6-8982-e645b182eeea
* Version Independent ID: fb38a86a-cdf6-6fc2-8eb6-fd54f1599f55
* Content: [Deploy updates using Windows Update for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-manage-updates-wufb)
* Content Source: [windows/deployment/update/waas-manage-updates-wufb.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-manage-updates-wufb.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Text is fixed.

**Comment by illfated** [comment]
Very well. Closed in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/7bd6b933d95542e5c9caa7d311c35e3c4f63ba6d then. 👍

**Comment by mypil** [comment]
@Tdiwestyguy - Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
