### ISSUE TITLE
Teams?

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#2536]
Teams is part of Win10 family, although not listed as supported??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6957383-3bd9-eef9-6410-9c42f8a0b172
* Version Independent ID: a2090374-0fd1-8d67-66de-30c4cf2835f7
* Content: [Overview of Windows as a service (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-overview#servicing-channels)
* Content Source: [windows/deployment/update/waas-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-overview.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
Maybe because Microsoft Teams is considered a "groupware" platform to supersede Skype and not considered to be an Operating System solution as such?

Browsing the linked page listing the 3 supported solutions, it looks like those 3 need considerations regarding Windows Update, while (I presume) Microsoft Teams is considered to be a stand-alone software package like an application.

(Please take my reply with a pinch of salt, I don't use any of these solutions, so my "educated" guesses may not "hit the mark" in this issue.)

**Comment by Tdiwestyguy** [comment]
Hi, Surface HUB OS is known as a teams device. This is an operating system, I test it. :)

Specifically users and admins cannot sign into the core OS. They sign into "Services" via Azure.

**Comment by Tdiwestyguy** [comment]
From, https://docs.microsoft.com/en-us/surface-hub/differences-between-surface-hub-and-windows-10-enterprise  This provides clarity on the OS being called Teams. 

The Surface Hub operating system, Windows 10 Team, is based on Windows 10 Enterprise, providing rich support for enterprise management, security, and other features. However, there are important differences between them. While the Enterprise edition is designed for PCs, Windows 10 Team is designed from the ground up for large screens and meeting rooms. When you evaluate security and management requirements for Surface Hub, it's best to consider it as a new operating system. This article is designed to help highlight the key differences between Windows 10 Team on Surface Hub and Windows 10 Enterprise, and what the differences mean for your organization.

**Comment by illfated** [comment]
Very well. So maybe it should be listed as a sub-module to Windows 10 Enterprise?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by greg-lindsay** [comment]
Sorry, what content is missing here exactly? What section has a list of supported apps where you think Teams should be included? This is a topic on keeping Windows up to date.

**Comment by illfated** [comment]
Thank you for raising that question, I admit that I lost sight of the issue some time after Easter. Looking back at this now, I think @Tdiwestyguy might be suggesting that Windows 10 Team should be listed alongside Windows 10, Windows 10 Mobile, and Windows 10 IoT Mobile, maybe something like this:
***
# Overview of Windows as a service

**Applies to**

- **Windows 10**
- **Windows 10 Team**
- **Windows 10 Mobile**
- **Windows 10 IoT Mobile**
***

**Comment by greg-lindsay** [comment]
While updates to surface hub are probably done similarly to Widows 10, we cannot apply all the content on this page to surface hub. For example, I don't believe there are different update delivery channels for surface hub. I could be wrong, but I'm very hesitant to apply all the guidance on this page to the surface hub product which might not be applicable.

**Comment by illfated** [comment]
Fair enough, thanks for the explanation. I don't have much of an opinion on the topic myself, so I will leave it to @Tdiwestyguy to post a reply concerning this.

**Comment by mypil** [comment]
@Tdiwestyguy - From our understanding, the issue you raised has been answered by greg-lindsay. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
