### ISSUE TITLE
issue with SSL VPN user

### ISSUE THREAD

**Issue by biren1234** [MicrosoftDocs/windows-itpro-docs#2545]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4969c03d-2c01-40f5-a9a8-fba2f91fb654
* Version Independent ID: da430ff8-74cd-b0fa-5867-f1238a7f58f2
* Content: [4692(S, F) Backup of data protection master key was attempted. (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4692)
* Content Source: [windows/security/threat-protection/auditing/event-4692.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/event-4692.md)
* Product: **w10**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

**Comment by biren1234** [comment]
we have issue with VPN user actually user connect Map drive with VPN  but when connect VPN after 2-3 second account got looked

**Comment by Justinha** [comment]
@biren1234 Sorry you are having trouble. More info will be needed to help troubleshoot and the best way to proceed with that is to contact Microsoft Support.

**Comment by biren1234** [comment]
my one user got locked when check with event there we found below Event 
actually user is roaming user and with old Password he tying to login but with Map drive we uses new password 
so how can we sync password 


Log Name:      Security
Source:        Microsoft-Windows-Security-Auditing
Date:          25/01/2019 15:31:36
Event ID:      4692
Task Category: DPAPI Activity
Level:         Information
Keywords:      Audit Failure
User:          N/A
Computer:      PIPL-HO-LPT073.parijat.in
Description:
Backup of data protection master key was attempted.

**Comment by biren1234** [comment]
@Justinha see blow 
Often, users start complaining about locking their domain accounts after changing their password. This suggests that the old (incorrect) password is saved in a certain program, script, or service that periodically tries to authenticate on a DC with a bad password. Consider the most common locations in which the user could save the old password:

**Comment by Justinha** [comment]
@biren1234 certainly you may be correct. This issue requires troubleshooting to confirm the cause and best resolution. Contact Microsoft Support or Customer Forums at https://social.microsoft.com/Forums/en-US/home.
