### ISSUE TITLE
Document needs updates

### ISSUE THREAD

**Issue by Field5555** [MicrosoftDocs/windows-itpro-docs#2548]
We should be recommending Windows Analytics for Application Compatibility and Laplink for user profile migration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8513655-c946-4a74-34ec-5c639b4021cc
* Version Independent ID: cd27cf77-45ab-95a0-f1e5-8549661f0740
* Content: [Windows Upgrade and Migration Considerations (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-upgrade-and-migration-considerations)
* Content Source: [windows/deployment/upgrade/windows-upgrade-and-migration-considerations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/windows-upgrade-and-migration-considerations.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@Field5555 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by lindspea** [comment]
@Field5555 Thank you for reaching out and helping improve MS Docs. Are you suggesting adding those recommendations to a note in this article?

**Comment by Field5555** [comment]
I think the article needs a pretty thorough edit to bring it up-to-date. Application Compatibility Toolkit has been deprecated for some time now. Windows Analytics is the recommended solution for Application Compatibility now. Also, while we still provide USMT, we are recommending Laplink for user profile migration, especially around the migration from Windows 7 to Windows 10.
Laplink could ne a note. ACT needs to be replaced with Windows Analytics.

**Comment by lindspea** [comment]
@Field5555 Thank you for the information.  I'm sending your suggestions over to the team and will revert soonest.  In the meantime would do you recommend this as the correct link to replace the Application Compatibility Toolkit - https://docs.microsoft.com/windows/deployment/update/windows-analytics-overview ?

**Comment by e0i** [comment]
@Field5555 Under investigation.

**Comment by greg-lindsay** [comment]
I am the assigned author and I'll try to address this.  If Field5555 would like to contact me directly in email please do so.  There are quite a few outdated articles that I'm working to update right now.
