### ISSUE TITLE
Defender status

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#2549]
Hi, So, I would like some clarification on Defender status. 

This says Intune and SCCM NO, but SyncML yes?  So, Both Intune and SCCM Admins use OMAURI (CSP policy) strands data type and value, which IS SyncML encoded.

Why would it say you cant do this via Intune or SCCM?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2b64fb-8c50-94a6-7c1a-9f9f79f1b06d
* Version Independent ID: 1fa4920c-6c59-1d49-03e7-0df75d21191b
* Content: [Manage settings with an MDM provider (Surface Hub)](https://docs.microsoft.com/en-us/surface-hub/manage-settings-with-mdm-for-surface-hub)
* Content Source: [devices/surface-hub/manage-settings-with-mdm-for-surface-hub.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/manage-settings-with-mdm-for-surface-hub.md)
* Product: **surface-hub**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by Tdiwestyguy** [comment]
Hi, Is there any update to this request?

**Comment by illfated** [comment]
Not sure why there has been a delay on feedback, but maybe it would be useful to describe an example scenario.
Otherwise, I presume @jdeckerms could contact a tech department to get relevant answers.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Tdiwestyguy  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by Tdiwestyguy** [comment]
Thanks!

________________________________

**Comment by VLG17** [comment]
@Tdiwestyguy The article was written before the release of Windows 1809, so it was correct at that time.

With the release of 1809, we can see that we have "ProductStatus" added to the CSP tree:

https://docs.microsoft.com/en-us/windows/client-management/mdm/defender-csp

![image](https://user-images.githubusercontent.com/41186174/60005647-95340600-9677-11e9-8ff4-0cb313e470b7.png)

I will create a request to update the article. Thank you for your feedback!

**Comment by mypil** [comment]
@Tdiwestyguy - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
