### ISSUE TITLE
Are the rampant Bluetooth issues caused by 1803 fixed with 1809?  

### ISSUE THREAD

**Issue by cheetah2k** [MicrosoftDocs/windows-itpro-docs#2557]
As the title suggests, are the bluetooth issues all resolved with 1809?  It is not mentioned it is fixed.  I constantly have this issue after 1803, and previously the only way to resolve was to fresh install Win10

https://answers.microsoft.com/en-us/windows/forum/windows_10-hardware/windows-update-1803-bluetooth-failure/1be91fe3-2d41-4c9f-9902-4f5c34f23f1a?auth=1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d6356b-87ff-8c3a-56ef-1270a823d3ab
* Version Independent ID: 4d6ae878-66cf-0e10-bdf3-bdd6054cbc9d
* Content: [What's new in Windows 10, version 1809](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1809.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1809.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@cheetah2k  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@cheetah2k According to the change log for 1809, the fix is included:

https://support.microsoft.com/en-us/help/4469342/november292018kb4469342osbuild17763167

**"Addresses an issue that stops Bluetooth® headsets from receiving audio input after several minutes of listening."**

**Comment by mypil** [comment]
@cheetah2k - From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
