### ISSUE TITLE
power settings ?

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#2558]
There is no options  to  create or modify power settings  in icd.exe 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44f09eb2-3111-bdd9-4a1f-1afa44322202
* Version Independent ID: b9d225ff-022f-92f2-e24f-41989fccf178
* Content: [Provision PCs with common settings (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provision-pcs-for-initial-deployment)
* Content Source: [windows/configuration/provisioning-packages/provision-pcs-for-initial-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/provisioning-packages/provision-pcs-for-initial-deployment.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@RAJU2529 Power options are not included in the **Provision desktop devices** wizard, that is correct.

**Comment by RAJU2529** [comment]
then how can I configure those settings

**Comment by jdeckerms** [comment]
@RAJU2529 In the next feature update to Windows 10, specific power settings will be added to the **Policies** node in Windows Configuration Designer. You'll be able to use advanced provisioning to configure those settings. (The instructions for advanced provisioning are at https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-create-package#configure-settings)

**Comment by RAJU2529** [comment]
Thanks for the information madam.  I am waiting for next future update.
 Thanks to earlier information.
