### ISSUE TITLE
Minor doc error: PC0003 vs PC0001 in the picture

### ISSUE THREAD

**Issue by johannrichard** [MicrosoftDocs/windows-itpro-docs#2560]
The doc speaks of `PC0003` where as figure 1 uses `PC0001`. 

Page: https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-to-windows-10-with-system-center-configuraton-manager

**Comment by illfated** [comment]
Which page are you referring to?

**Comment by johannrichard** [comment]
Added the page. But just realized I missed the correct way to open documentation issues. Shall I better close this issue and reopen a new the right way?
