### ISSUE TITLE
Local Share

### ISSUE THREAD

**Issue by zemblack** [MicrosoftDocs/windows-itpro-docs#2564]
So, you mention configuring GPO to download FOD from a local share, but I can't find a place to download the source to store on my local share. My organization does not have internet access, so cannot download directly from Windows Update. Now what?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d423c0e-fd99-9ad5-a11a-45237c2149fc
* Version Independent ID: f30e4101-7a8e-bfa9-a7c0-de7c36499cf5
* Content: [Windows 10 - How to make FoDs and language packs available when you're using WSUS/SCCM](https://docs.microsoft.com/en-us/windows/deployment/update/fod-and-lang-packs)
* Content Source: [windows/deployment/update/fod-and-lang-packs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/fod-and-lang-packs.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@zemblack  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@zemblack - I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
