### ISSUE TITLE
Step 7: Copy from D:\...

### ISSUE THREAD

**Issue by Sliminconcoova** [MicrosoftDocs/windows-itpro-docs#2567]
What is D:\ ? I do not recognize the file structure for this source?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
I can't verify it at the moment (have tried to browse and do Ctrl-F on a few linked pages), but I presume it could be the CD/DVD-ROM on **MDT01** (Windows Server 2012 R2 standard).
I also presume that the path **Setup\Sample Files\MDT Production\Control** is a folder structure on the Microsoft Deployment Toolkit (MDT) CD or DVD source (or image).
> 1. On MDT01, using File Explorer, copy the following files from the **D:\Setup\Sample Files\MDT Production\Control** folder to **E:\MDTProduction\Control**. Overwrite the existing files.

I further presume that drive E: is a **data** partition on **MDT01**.

I will appreciate if anyone else knows or can confirm the correct source/structure/scenario here.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by nenonix** [comment]
@illfated see https://github.com/MicrosoftDocs/windows-itpro-docs/issues/797 - does this shed any light?

**Comment by illfated** [comment]
@nenonix : Thank you for asking, even though this material is a bit new to me.
I have not delved into this material yet, but it seems very likely that the customsettings.ini should be copied from E:\MDTProduction\Control - just like @WLK33R said in ticket #797.
Thank you for following up on this question as well as #2400 and the aforementioned ticket.

@Sliminconcoova : Will the information provided in this issue ticket so far be of any help in answering your question?

**Comment by mypil** [comment]
@Sliminconcoova - We would like to follow up with you. Can you please respond to the question of illfated?

Thank you,

**Comment by mypil** [comment]
@Sliminconcoova - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
