### ISSUE TITLE
EnableAccountManager in text on Intune says that only for HoloLens devices

### ISSUE THREAD

**Issue by aavdberg** [MicrosoftDocs/windows-itpro-docs#2568]
When I go to the Shared Multi-user device in Device configuration Profiles in Intune at the configuration of options there is a text that is saying the following:

Configure access, account deletion, maintenance, and power management settings for your shared Windows 10 device used by multiple users in your organization.
In organizations where multiple OS versions are supported, these settings may not apply across all versions the same. Account manager settings are the only settings applicable to HoloLens devices. 

But on the doc's page I don't find anything about this so what is right the Intune portal or the docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3329b98-7e66-aa67-d27e-d14471cf63b3
* Version Independent ID: e6c88589-b252-4e9c-6016-8b53154dce96
* Content: [SharedPC CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/sharedpc-csp)
* Content Source: [windows/client-management/mdm/sharedpc-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/sharedpc-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by aavdberg** [comment]
Also on the following link I don't find anything about HoloLens:
https://docs.microsoft.com/en-us/windows/configuration/set-up-shared-or-guest-pc#shared-pc-mode-concepts

**Comment by aavdberg** [comment]
On the same settings page you can seconds before device go in sleep, but range that is allowed is only 1-100 or has here to stand minutes instead of seconds?

**Comment by DaniHalfin** [comment]
@jdeckerms - any chance you can help out here?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
@aavdberg Thank you for sharing your feedback. Can you please share more details and screenshots so that we can better help you and make the necessary changes in the doc.
For Hololens devices, please visit https://docs.microsoft.com/en-us/hololens/ for details. You will find details regarding hololens and managing it using MDM.

Thanks.

**Comment by mypil** [comment]
@aavdberg - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
