### ISSUE TITLE
Instructions for disabling not working...

### ISSUE THREAD

**Issue by darnocian** [MicrosoftDocs/windows-itpro-docs#2569]
mountvol X: /s
&gt; The parameter is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#disable-windows-defender-credential-guard)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by SelectFromT** [comment]
I have a secondary hard drive so this worked for me. 

copy %WINDIR%\System32\SecConfig.efi E:\EFI\Microsoft\Boot\SecConfig.efi /Y
bcdedit /create {0cb3b571-2f2e-4343-a879-d86a476d7215} /d "DebugTool" /application osloader
bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} path "\EFI\Microsoft\Boot\SecConfig.efi"
bcdedit /set {bootmgr} bootsequence {0cb3b571-2f2e-4343-a879-d86a476d7215}
bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} loadoptions DISABLE-LSA-ISO,DISABLE-VBS
bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} device partition=E:
bcdedit /set hypervisorlaunchtype off


I ran this at elevated cmd, fixed the vmware problem.

**Comment by zhangbo-miuNEST** [comment]
tested and works!

> 
> 
> I have a secondary hard drive so this worked for me.
> 
> copy %WINDIR%\System32\SecConfig.efi E:\EFI\Microsoft\Boot\SecConfig.efi /Y
> bcdedit /create {0cb3b571-2f2e-4343-a879-d86a476d7215} /d "DebugTool" /application osloader
> bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} path "\EFI\Microsoft\Boot\SecConfig.efi"
> bcdedit /set {bootmgr} bootsequence {0cb3b571-2f2e-4343-a879-d86a476d7215}
> bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} loadoptions DISABLE-LSA-ISO,DISABLE-VBS
> bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} device partition=E:
> bcdedit /set hypervisorlaunchtype off
> 
> I ran this at elevated cmd, fixed the vmware problem.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by e0i** [comment]
@darnocian 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Note that the issues section of this repository is intended for documentation feedback.

Please direct similar support questions via the following link so that it gets answered quickly:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot assign @e0i
