### ISSUE TITLE
OneNote in Kiosk Mode

### ISSUE THREAD

**Issue by rickgode** [MicrosoftDocs/windows-itpro-docs#2570]
We're trying to utilize the accessibility tools in OneNote specifically the dictate tool to provide needed accommodations to our students during testing. We're required to lock the computer down to a single app (onenote) and only the draw tab shows.

Is there any way that the all the features of the OneNote app can be enabled in Kiosk Mode?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd2d1007-2cbb-94a6-18aa-a0b879262ab1
* Version Independent ID: 625d9906-0cb0-23eb-3a56-a84ad774d291
* Content: [Guidelines for choosing an app for assigned access (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/guidelines-for-assigned-access-app)
* Content Source: [windows/configuration/guidelines-for-assigned-access-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/guidelines-for-assigned-access-app.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@rickgode Are you using the UWP (Microsoft Store) OneNote app or the desktop (Win32) app? Also, what method are you using to configure kiosk mode?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@rickgode - Can you please respond to the query of jdeckerms?

**Comment by mypil** [comment]
@rickgode - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to open a new issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
