### ISSUE TITLE
Access Violation when running VC_REDIST.x64 in provisioningpackage

### ISSUE THREAD

**Issue by PetervdZande** [MicrosoftDocs/windows-itpro-docs#2578]
Dear People,

Im currently tring to add Visual Studio 2015 Redistributables to the provisoning package.
I have consulted de following links with instructions on how to add a .exe to the WCD package.

https://technet.microsoft.com/en-us/mt703295(v=vs.71)

My configuration in WCD:

ProvisioningCommands/DeviceContext/CommandFiles
vc_redist.x64.exe
install_vcredistx642015.bat

ProvisioningCommands/DeviceContext/CommandLine
cmd /c install_vcredistx642015.bat

BAT File includes:

set LOGFILE=%SystemDrive%\vcredist_install.log
echo Installing Visual Studio 2015 Redistributables >> %LOGFILE%
vc_redist.x64.exe /install /quiet /norestart >> %LOGFILE%
echo result: %ERRORLEVEL% >> %LOGFILE%

De logfile after running the packages:

Installing Visual Studio 2015 Redistributables 
result: -1073741819 

I found an article that explains this error:
http://www.trytoprogram.com/batch-file-return-code/

3221225477
0xC0000005
-1073741819

Access violation.
Indicates that the executed program has terminated abnormally or crashed.

Anyone has any idea why it is not working?

**Comment by jdeckerms** [comment]
@PetervdZande I think you might get better results by posting on the [IT Pro forum](https://social.technet.microsoft.com/forums/en-us/home?category=windows10itpro) (this isn't a forum or discussion board). If that doesn't help, you can contact [Microsoft Support](https://support.microsoft.com/en-us/contactus/) for assistance.
