### ISSUE TITLE
article length

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#2579]
This article is very long, it would be better if it was separated into more articles, maybe one for the technical configuration and others for the background overview and legal information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c364e-fcf4-8667-17d7-f9a3ec71e1a9
* Version Independent ID: f98f8870-d594-f5df-f6b6-44c9806db7d8
* Content: [Configure Windows diagnostic data in your organization (Windows 10)](https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization#enterprise-management)
* Content Source: [windows/privacy/configure-windows-diagnostic-data-in-your-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/configure-windows-diagnostic-data-in-your-organization.md)
* Product: **w10**
* GitHub Login: @brianlic-msft

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by RAJU2529** [comment]
@DeanGross. This article  title itself it says "Configure Windows diagnostic data in your organization"

so all the required detailed steps are already explained by the authors.  This article is lengthy i agree, but those points are required by organization.
If you configure to windows 10 pro edition to home users means, then this article comes to half page

**Comment by VLG17** [comment]
@DeanGross Thank you for your feedback. I have checked the article and although lengthy, it has a clear structure and the provided information is relevant. 

I personally think that the overview on the right hand side helps and you can use that to better/faster navigate the article.

If you really want to get this addressed, i recommend reaching out to the Telemetry Team within MS (who created the article), as described in the article:

**_"We are always striving to improve our documentation and welcome your feedback. You can provide feedback by contacting telmhelp@microsoft.com."_**

**Comment by e0i** [comment]
@officedocsbot unassign @e0i

**Comment by mypil** [comment]
@DeanGross - From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
