### ISSUE TITLE
RSS Feed?

### ISSUE THREAD

**Issue by cconrado** [MicrosoftDocs/windows-itpro-docs#2581]
We need an rss feed for this to watch for releases.

And if you can see writes this site https://docs.microsoft.com/en-us/windows/windows-10/release-information

we need it there too.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b010f23d-6d7e-8ab0-8a16-0ddbbacc0528
* Version Independent ID: 929b988a-e7e4-b8b0-2a85-756c69085063
* Content: [What's new in Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/whats-new/)
* Content Source: [windows/whats-new/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/index.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **trudyha**

**Comment by lizap** [comment]
Hi, Carlos! We agree - we do need RSS feed ability. The best way to get that is to share your feedback with the team that builds Microsoft Docs, which you can do here: https://aka.ms/sitefeedback
