### ISSUE TITLE
How often are logs uploaded?

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/windows-itpro-docs#2585]
How real time is the data received from the ATP integration, when viewed in the CAS dashboard?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72a6f637-023b-2a83-ac08-10b8e72bbb61
* Version Independent ID: 8b3f80de-7b41-42da-46ce-7a0237ac5edd
* Content: [Microsoft Cloud App Security integration overview](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/microsoft-cloud-app-security-integration)
* Content Source: [windows/security/threat-protection/windows-defender-atp/microsoft-cloud-app-security-integration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/microsoft-cloud-app-security-integration.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Data is not real time. It can take a couple of hours for data to be processed and for the data to be reaggregated before actions are seen in the portal.
