### ISSUE TITLE
DOMinFileSizeToCache - no "unlimited" setting.

### ISSUE THREAD

**Issue by agressiv** [MicrosoftDocs/windows-itpro-docs#2586]
DOMinFileSizeToCache - "The value 0 means "unlimited" which means the cloud service set default value will be used." ---  Group policy will not allow a value of zero.  Perhaps it will work with a reg hack though, I do not know.  Group Policy documentation does not mention unlimited.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06745768-affe-c86a-2da6-7bd694e847c9
* Version Independent ID: e832ada1-5f0c-7809-b8a1-bb91cadb6975
* Content: [Policy CSP - DeliveryOptimization](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-deliveryoptimization#deliveryoptimization-dominfilesizetocache)
* Content Source: [windows/client-management/mdm/policy-csp-deliveryoptimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-deliveryoptimization.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by j0rt3g4** [comment]
What would be the group policy **article** that does not talk about unlimited?

You always need to make sure that you're using the correspondent ADMx version for all your devices inside your enterprise. (1809 --> https://www.microsoft.com/en-us/download/confirmation.aspx?id=57576)

**Comment by mypil** [comment]
@agressiv - We would like to follow up. Can you please respond to the query of j0rt3g4?

Thank you.

**Comment by agressiv** [comment]
1809 Templates are the same, and they are hard coded not to accept anything below 1.

Help Message:
"Specifies the minimum content file size in MB enabled to use Peer Caching.   Recommended values: 1 MB to 100000 MB."

Error Message when I put in 0:
"The number in this field was smaller than the minimum value of 1.  The number has been reset from 0 to the minimum value."

**Comment by j0rt3g4** [comment]
@agressiv the "unlimited" cache goes for attributes:
* DOAbsoluteMaxCacheSize
* DOMaxCacheAge
* DOMaxUploadBandwidth
* DOMonthlyUploadDataCap

There is no possible value 0 for any "min" value, they are 0 for "Max" properties.

**Comment by agressiv** [comment]
Correct, at the time (5 months ago), 0 was a choice for DoMinFileSizeToCache.  Guessing someone fixed it.

**Comment by j0rt3g4** [comment]
Yeah, I review it carefully :) 
Thank you for your inputs @agressiv 
Can we proceed to close this one?

**Comment by agressiv** [comment]
Sure thing!

**Comment by j0rt3g4** [comment]
Thank you very much, if you require any other change please let us know we will be pleased to fix it (now it's a bigger team so we shouldn't take long) 👍
