### ISSUE TITLE
Content corrections / suggestions

### ISSUE THREAD

**Issue by SoccerCore11** [MicrosoftDocs/windows-itpro-docs#2590]
https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises#managing-devices-joined-to-azure-active-directory
In this section, it should be mentioned that Hybrid Azure AD Joined devices are also applicable to this section. 

The second paragraph in the same section mentions that only Business and Enterprise editions of Windows 10 work with the Policy CSP and Bitlocker CSP. This is incorrect as documented in the first couple paragraphs here: https://docs.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp

It should also be mentioned that without Win10 v1809, only local administrative users can enable Bitlocker. Local users who are non-admins (which is becoming the new normal and has been a best practice for a long time) cannot enable Bitlocker via Intune policy. https://docs.microsoft.com/en-us/intune/whats-new#non-administrators-can-enable-bitlocker-on-windows-10-devices-joined-to-azure-ad

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e5380a-53da-6df1-1952-1be89d9b5969
* Version Independent ID: 82af0c50-fb10-3ad3-1f1d-74a068ea6fa7
* Content: [BitLocker Management Recommendations for Enterprises (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@SoccerCore11 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by Malind19** [comment]
@mypil  added PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3315

**Comment by mypil** [comment]
@SoccerCore11 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
