### ISSUE TITLE
Where? Can I upgrade to Windows 10 with BitLocker enabled?

### ISSUE THREAD

**Issue by matiyin** [MicrosoftDocs/windows-itpro-docs#2597]
I'm looking to upgrade my Windows 10 to a have access ti the Bitlocker feature.
I found this page through google and it answered my question, but it doesn't say how or where!
Now I have to google more just to find out how to buy a product from you?
--- you say : ---
Can I upgrade to Windows 10 with BitLocker enabled?
Yes.

I will find my way, just wanted to give you my experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06b660d4-be4e-c039-0edb-f08d7944add7
* Version Independent ID: 99c3bac3-6bd0-6b7a-e709-4a1924180cf3
* Content: [BitLocker Upgrading FAQ (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-upgrading-faq)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-upgrading-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-upgrading-faq.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by egallagh** [comment]
Hi matiyin. If you are using Windows 10 Home edition they you need to purchase an upgrade to Windows 10 Pro, apply the upgrade and then you should be able to activate BitLocker. This does assume that the computer you are using has the required hardware to support BitLocker.
This article refers to a different issue: If I already have BitLocker enabled, can I upgrade to Windows 10.
I hope this helps.

**Comment by egallagh** [comment]
I forgot to add that this page will show you the differences in major features between Windows 10 Home and Windows 10 Pro: https://www.microsoft.com/windows/compare

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by RAJU2529** [comment]
@matiyin. You need buy windows 10 pro edition, to use BitLocker features.

**Comment by e0i** [comment]
@matiyin 

It seems that your question has already been answered and thus we are marking this issue as resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
