### ISSUE TITLE
Pruning inactive clients

### ISSUE THREAD

**Issue by thetechguy86** [MicrosoftDocs/windows-itpro-docs#2599]
"If this is not pruned to remove inactive clients this set of registry keys can grow to an unmanageable size over time." 
What is the method to prune inactive clients?
What registry key needs to be pruned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5862cc7-3f36-5f2e-9ade-f7441f99f818
* Version Independent ID: b8bd1985-7b5b-ea79-976a-7d96ad69335c
* Content: [Use Windows Event Forwarding to help with intrusion detection (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection)
* Content Source: [windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md)
* Product: **w10**
* GitHub Login: @tedhardyMSFT
* Microsoft Alias: **justinha**

**Comment by SupremeBigPhil** [comment]
HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\EventCollector\Subscriptions

Each subscription is a key in the registry, and each key has the source listed in several sub keys. I use the script from ArcSight to prune my sources every so often.

Not sure if I'm allowed to post links, but this has a PowerShell script that you can start with and tailor to your needs

https://community.softwaregrp.com/dcvta86296/attachments/dcvta86296/arcsight-discussions/24729/1/Protect2015-WindowsEventForwarding.pdf

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @thetechguy86 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
