### ISSUE TITLE
Language restrictions

### ISSUE THREAD

**Issue by mortinious** [MicrosoftDocs/windows-itpro-docs#2600]
I have had lots of problems getting AssignedAccess to work on a swedish OS (ShellExperienceHost cannot start).
When applying on a english OS everything works fine.
Is there any documented problems with non-english OS? If so it should be stated somewhere here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78038d67-04a1-f4ae-6a69-98e157688a31
* Version Independent ID: c86b4460-e8be-8537-a6c8-3cb094ef14a3
* Content: [Set up a multi-app kiosk  (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps)
* Content Source: [windows/configuration/lock-down-windows-10-to-specific-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/lock-down-windows-10-to-specific-apps.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by tlange-tech2go** [comment]
Same here: Multi-app kiosk mode doesn't work anymore with German Windows 1809 installations. User is simply logged out after login :-(
With 1803 and 1709 it worked just fine.
Any ideas? We urgently need it for our customers so that they can update to 1809!

**Comment by mortinious** [comment]
> Same here: Multi-app kiosk mode doesn't work anymore with German Windows 1809 installations. User is simply logged out after login :-(
> With 1803 and 1709 it worked just fine.
> Any ideas? We urgently need it for our customers so that they can update to 1809!

I found the issue and a workaround.
It seems that AssignedAccess cannot understand localized groupnames and for some reason it needs to find "Administrators". This is still a problem that needs to be resolved but you can simple create the group during provisioning and add it to your localized administrators-group.
It's a dirty solution but it works.

**Comment by tlange-tech2go** [comment]
Wow - thanks a lot for your quick replay and the dirty solution that really does the trick!
Can't imagine how such a stupid bug for a software used world wide could make it into a release and I hope Microsoft fixes this asap. But at least we now know how to work around this until it is fixed.

**Comment by jdeckerms** [comment]
@mortinious and @tlange-tech2go  I've checked with the product team, and this issue has been fixed in the next feature update to Windows 10. I don't know if they'll push the fix to current and earlier versions of Windows 10 and when that might be, if I get additional info I'll let you know.
