### ISSUE TITLE
Documentation for FirewallRules/FirewallRuleName/Direction appears incorrect

### ISSUE THREAD

**Issue by JeffStong** [MicrosoftDocs/windows-itpro-docs#2601]
The documentation for FirewallRules/FirewallRuleName/Direction states "Comma separated list."  However, testing CSP on recent OS versions (OS Build 17134.523) shows that a comma separated list is not supported by the CSP.  Values accepted by the CSP are "IN" or "OUT" but not "IN,OUT"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfea4e59-ec8c-cbdf-a039-23612c2266a5
* Version Independent ID: 7058544b-7ef2-a398-366a-cf71520aa9d8
* Content: [Firewall CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/firewall-csp)
* Content Source: [windows/client-management/mdm/firewall-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/firewall-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@JeffStong - thank you for submitting feedback.

In reference to the other issues #2602 & #2735 you opened for this article, Could you please help us by suggesting how this content could be edited to incorporate your feedback?  What do you suggest is the best way to fix this?
