### ISSUE TITLE
Partners can use tuple

### ISSUE THREAD

**Issue by luriep** [MicrosoftDocs/windows-itpro-docs#2603]
Would love to see more information about how Partners can use the tuple in Partner Center and how this doesn't require people to open a box and gather the hash.  Happy to help write the blurb if necessary.  Thanks  --petl 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3243b015-5b5f-7a62-0d9d-767d729dc475
* Version Independent ID: ff8c0509-c075-8528-823f-c195ff4d2382
* Content: [Adding devices](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/add-devices#device-identification)
* Content Source: [windows/deployment/windows-autopilot/add-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/add-devices.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by VLG17** [comment]
@luriep I wanted to confirm if the level of details found in [this](https://docs.microsoft.com/en-us/partner-center/autopilot#add-devices-to-a-customers-account) article (which is referenced within the [article](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/add-devices#device-identification) you linked) is enough?

It provides a step by step guide and gives details about the tuple and HH.

If not, could you please write a few words on this topic?

**Comment by VLG17** [comment]
@luriep Just to be more clear, you can find all the details you need if you go under "Partner Center" in the table that talks about "Tuple":

![image](https://user-images.githubusercontent.com/41186174/66562596-a4768b00-eb64-11e9-9744-b69493df2621.png)

**Comment by e0i** [comment]
Hello @luriep ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
