### ISSUE TITLE
MpCmdRun.exe path is required

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/windows-itpro-docs#2607]
Please consider updating the documentation to provide the full path of where the MpCmdRun.exe is found. Otherwise, by following the documentation above, MpCmdRun.exe fails to run unless you first change directory into this folder: 
"C:\Program Files\Windows Defender"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86b0db3-f979-bd1f-78a4-41247510721a
* Version Independent ID: 5289bb5f-f015-7f38-05a1-26a615ae07aa
* Content: [Configure and validate Windows Defender Antivirus network connections](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus#validate)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by vboyev-MSFT** [comment]
Default path is %ProgramFiles%\Windows Defender\MpCmdRun.exe

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
The location of `MpCmdRun.exe` is mentioned on the page **"Configure and manage Windows Defender Antivirus with the mpcmdrun.exe command-line tool"**
(https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/command-line-arguments-windows-defender-antivirus).

To be honest, I would presume that any IT professional would know how to locate programs outside of the command path, but on the other hand I also see the usefulness of including the extra information to avoid confusion or misunderstanding.

**Comment by e0i** [comment]
Hello, @itguysocal 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by neumarke** [comment]
The problem I'm trying to solve is that the path keeps changing. Every month or so it changes. So if you are trying to configure a tool to use the command line scanner to check a file, the path keeps breaking. It would be nice to have a static location for the most recent "MpCmdRun.exe" or at least an environment variable or something to find it.

there is indeed a copy at
 %ProgramFiles%\Windows Defender\MpCmdRun.exe
But it is out of date.

The up to date version is here:
C:\ProgramData\Microsoft\Windows Defender\Platform \ _ever-changing-version-number_\MpCmdRun.exe
It doesn't always break when it is updated, but you will silently be running the older version and not know it.

**Comment by illfated** [comment]
Fair point. It may be a challenge to keep up with the latest version, at least when using the command-line tool.

Myself, I don't know what the solution would be. I hope someone may be able to suggest how to handle that.
