### ISSUE TITLE
Windows Sandbox Enables Windows Defender Credential Guard

### ISSUE THREAD

**Issue by hadeernd** [MicrosoftDocs/windows-itpro-docs#2612]
Please note that the windows sandbox (build 18305+)  enables windows credential guard.  You cannot use both windows sandbox and vmware workstation at the same time. To disable credential guard:

Do a search for "windows security settings" then choose windows security in the left menu:
windows Security --&gt;&gt; Device Security --&gt;&gt;  Core Isolation --&gt;&gt; Memory Integrity --&gt;&gt; Select Off 

for that search for "Run" and type "gpedit.msc" in that
Goto    Local Computer Policy - Computer Configuration - Administrative Templates - System - Device Guard - Turn on Virtualization 
Double click that .... and select "Disable" ...

Go to Control Panel - Uninstall a Program - Turn Windows features on or off - (uncheck/turn off) Hyper-V.
Click OK
Select Do not restart.

And then type the following cmds in cmd prompt.. to Delete the related EFI variables from the BCD file...
Launch cmd as admin...

bcdedit /create {0cb3b571-2f2e-4343-a879-d86a476d7215} /d "DebugTool" /application osloader
bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} path "\EFI\Microsoft\Boot\SecConfig.efi"
bcdedit /set {bootmgr} bootsequence {0cb3b571-2f2e-4343-a879-d86a476d7215}
bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} loadoptions DISABLE-LSA-ISO,DISABLE-VBS
bcdedit /set hypervisorlaunchtype off

Restart your system ... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by tpruvot** [comment]
tx for the help, ms one was useless

**Comment by abdias32** [comment]
Thanks @hadeernd!! I applied a little change to your script.

mountvol X: /s
copy %WINDIR%\System32\SecConfig.efi X:\EFI\Microsoft\Boot\SecConfig.efi /Y
bcdedit /create {0cb3b571-2f2e-4343-a879-d86a476d7215} /d "DebugTool" /application osloader
bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} path "\EFI\Microsoft\Boot\SecConfig.efi"
bcdedit /set {bootmgr} bootsequence {0cb3b571-2f2e-4343-a879-d86a476d7215}
bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} loadoptions DISABLE-LSA-ISO,DISABLE-VBS
bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} device partition=X:
bcdedit /set hypervisorlaunchtype off
mountvol X: /d

**Comment by illfated** [comment]
Do you have some recommended changes for this page, based on the suggested scripts?
If yes, how much would you recommend changing?
Would you like to have a Pull Request made for the changes too?
(Not sure how much verification is needed by MS internal techs before approval.)

**Comment by Justinha** [comment]
Thanks for the feedback. I'm checking with our engineering team.

**Comment by hadeernd** [comment]
I have listed the recommendations I am aware of.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Justinha - Do you have any updates on this?

Thank you.

**Comment by Justinha** [comment]
@mypil yes, sorry for delay but I added the script from @hadeernd to the topic. @hadeernd Thanks for the suggestion! Ideally we could list you as a contributor but I have no way to manually do that. If you would be kind enough to submit contributions like this as a pull request in the future, we will review with engineering, merge and publish the contribution and then you will be listed. If you want that in this case, I think you can still submit the script yourself.

Thanks for making the docs better!

**Comment by hadeernd** [comment]
Your welcome.  I will be contributing more in the future.

Thanks,
-Kareem

**Comment by mypil** [comment]
@officedocsbot close

**Comment by vysecurity** [comment]
How does one reverse this change?
