### ISSUE TITLE
Autopilot reset (preview) greyed-out

### ISSUE THREAD

**Issue by jmrita** [MicrosoftDocs/windows-itpro-docs#2613]
Which are the build requirements ? Running 1809, autopilot profile assigned. Do we need higher build ? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98a662f1-c2aa-33ad-0e71-d0cbb288d053
* Version Independent ID: 196f1c8d-3179-c173-194f-08bf3a6f82ca
* Content: [Reset devices with remote Autopilot Reset (Preview)](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-reset-remote)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-reset-remote.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-autopilot-reset-remote.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by pyoungberg** [comment]
Same question. All devices running 1809, already wiped, enrolled via user-driven hybrid AAD joined deployment using Windows Autopilot, and using enrollment status page - still no option for Autopilot Reset.

**Comment by rasmusan1** [comment]
same problem here - Autopilot reset (Preview) greyed out although all prereqs fulfilled !

**Comment by davejdyer** [comment]
Same +1

**Comment by pyoungberg** [comment]
Any update @greg-lindsay ?

**Comment by HartD92** [comment]
@jmrita @pyoungberg @rasmusan1 As mentioned in the documentation, Autopilot Reset is only available for devices that are Azure AD Joined. Devices that are joined to an on-premises AD, including those that are Hybrid Azure AD Joined, cannot use Autopilot Reset.

**Comment by philip-g** [comment]
@HartD92 I run solely on Azure AD, without any on-premises environment. I still have the Autopilot option greyed out.

**Comment by schenardie** [comment]
have you imported the device autopilot and assigned the device a deployment profile?? also if user driven a user needs to be assigned to the device

**Comment by Neckross** [comment]
This feature will stay grayed out unless you push a Wipe or Fresh Start request, after the completion you'll see the option becomes active.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by schenardie** [comment]
Needs Windows 1809 at least
Device need to be imported to AutoPilot, have a profile assigned and if that profile is deployed using User Driven mode it needs to have a user assigned to it.

**Comment by e0i** [comment]
@officedocsbot close
