### ISSUE TITLE
No edit button for French version?

### ISSUE THREAD

**Issue by KB4284848** [MicrosoftDocs/windows-itpro-docs#2614]
Hi, according to this banner, I should be able to see an Edit button for french version however I can't find it while it shows up for English version.
![image](https://user-images.githubusercontent.com/42769194/52207981-06188400-2877-11e9-908e-81957e546566.png)
![image](https://user-images.githubusercontent.com/42769194/52208044-2f391480-2877-11e9-93f8-3933f10a8fbb.png)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 19c8d2d2-3d96-c635-76da-c3b43afc1b45
* Version Independent ID: d7d79add-eadc-2e11-4bf7-eac48e4975d8
* Content: [Device Guard est la combinaison de Windows Defender Application Control et la protection basée sur la virtualisation de l’intégrité du code (Windows 10)](https://docs.microsoft.com/fr-fr/windows/security/threat-protection/device-guard/introduction-to-device-guard-virtualization-based-security-and-windows-defender-application-control)
* Content Source: [windows/security/threat-protection/device-guard/introduction-to-device-guard-virtualization-based-security-and-windows-defender-application-control.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/threat-protection/device-guard/introduction-to-device-guard-virtualization-based-security-and-windows-defender-application-control.md)
* Product: **w10**
* GitHub Login: @mdsakibMSFT
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@samanthaw @MollyMalone 

cc: @AndreaBarr

**Comment by illfated** [comment]
Testing other language versions, the same happens to the German and Spanish versions:
https://docs.microsoft.com/de-de/windows/security/threat-protection/device-guard/introduction-to-device-guard-virtualization-based-security-and-windows-defender-application-control
https://docs.microsoft.com/es-es/windows/security/threat-protection/device-guard/introduction-to-device-guard-virtualization-based-security-and-windows-defender-application-control
(The issue could be present in other localized languages, I stopped looking for examples after German, Spanish, Danish, Norwegian & Swedish.)

Switching to the Danish, Norwegian or Swedish pages, the toolbar translates properly with the Edit option available in the local language, although the document is only available in English.

**Comment by Justinha** [comment]
Thanks for raising this everyone. We are not accepting contributions to the localized Windows 10 topics at this time. We'll try to correct the banner text on those topics.

**Comment by KB4284848** [comment]
> Thanks for raising this everyone. We are not accepting contributions to the localized Windows 10 topics at this time. We'll try to correct the banner text on those topics.

@Justinha that's sad because as a French native speaker I can assure you that the automatic translation failed: the whole document is barely understandable both in terms of syntax and spelling. Hence the original point of opening that issue.

**Comment by Justinha** [comment]
@KB4284848 Thanks for adding this, and I recently learned of a similar problem with another topic and a different language. I've shared this feedback with our localization team. Ideally, we would provide a solution where everyone can contribute using their preferred language.
