### ISSUE TITLE
Tool version needs updated

### ISSUE THREAD

**Issue by czrik** [MicrosoftDocs/windows-itpro-docs#2622]
The newest version is v1.12.137.0 not v1.4.137.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e78f073c-9f6b-b9d2-cd94-0a31998f10d9
* Version Independent ID: 5beaeca4-3d07-c65c-018b-a88cda5ceb9a
* Content: [Using the Surface Hub Recovery Tool](https://docs.microsoft.com/en-us/surface-hub/surface-hub-recovery-tool)
* Content Source: [devices/surface-hub/surface-hub-recovery-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/surface-hub-recovery-tool.md)
* Product: **surface-hub**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by danieldhudson** [comment]
Now 1.14.137.0

**Comment by jdeckerms** [comment]
@czrik I checked the download site and the file is still SurfaceHub_Recovery_v1.14.137.0.msi. Where are you finding a download for v1.12.137.0? Thanks!

**Comment by czrik** [comment]
I had the old version installed (1.12 ). Still, it's 1.14 not 1.4 

To start the download, click Download, choose SurfaceHub_Recovery_v1.4.137.0.msi from the list, and click Next. From the pop-up, choose one of the following:

**Comment by jdeckerms** [comment]
@czrik Ack, I overlooked the difference between 1.4 and 1.14 -- so sorry! @egallagh has updated the topic, it should be fixed by end of day. Thanks for pointing it out!
