### ISSUE TITLE
Powershell Module

### ISSUE THREAD

**Issue by Chireven** [MicrosoftDocs/windows-itpro-docs#2624]
The documentation is missing a critical step.  Before you can convert an App-V 4 package, you must load the modele:

import-module AppVPkgConverter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 802e0781-4d15-f944-63dc-647994358853
* Version Independent ID: 1ae7ab44-044d-cf89-2bdb-e08aeeb21a07
* Content: [How to Convert a Package Created in a Previous Version of App-V](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/appv-v5/how-to-convert-a-package-created-in-a-previous-version-of-app-v)
* Content Source: [mdop/appv-v5/how-to-convert-a-package-created-in-a-previous-version-of-app-v.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/appv-v5/how-to-convert-a-package-created-in-a-previous-version-of-app-v.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by e0i** [comment]
@AndreaBarr The issue can now be closed as PR has been merged. Thanks.
