### ISSUE TITLE
SetupDiag Link does not work

### ISSUE THREAD

**Issue by chilleregeravi** [MicrosoftDocs/windows-itpro-docs#2631]
Setupdiag link throws a 404 Page not found error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d6356b-87ff-8c3a-56ef-1270a823d3ab
* Version Independent ID: 4d6ae878-66cf-0e10-bdf3-bdd6054cbc9d
* Content: [What's new in Windows 10, version 1809](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1809.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1809.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by Malind19** [comment]
Created PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3135

**Comment by mypil** [comment]
@officedocsbot close
