### ISSUE TITLE
Add additional products to page

### ISSUE THREAD

**Issue by Scottmca** [MicrosoftDocs/windows-itpro-docs#2633]
Can we add Surface Pro 6, Surface Laptop 2, and Surface Go under supported devices?  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51dd9415-9d0f-b23a-c6b8-73a08668eecd
* Version Independent ID: 9f1f8de8-9cdf-d0be-6dc6-c82c14c2ed03
* Content: [Wake On LAN for Surface devices (Surface)](https://docs.microsoft.com/en-us/surface/wake-on-lan-for-surface-devices)
* Content Source: [devices/surface/wake-on-lan-for-surface-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/wake-on-lan-for-surface-devices.md)
* Product: **w10**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by Scottmca** [comment]
Any update on getting these changes made?  Thanks

**Comment by illfated** [comment]
Do you mean only the list of supported devices, like this?

## **Supported devices**

The following devices are supported for WOL:

- Surface Book 2
- Surface Pro with LTE Advanced (Model 1807)
- Surface Pro (Model 1796)
- Surface Laptop 2
- Surface Laptop
- Surface Book
- Surface Pro 6
- Surface Pro 4
- Surface 3
- Surface Pro 3
- Surface Go
- Surface Ethernet adapter
- Surface Dock
- Surface Docking Station for Surface Pro 3

***
(Feel free to suggest a different ordering - I am contemplating opening a PR for the recommended change.)
BTW, have you verified that they are supported and the doc page needs updating to comply with other existing documentation?

**Comment by Scottmca** [comment]
Yep.  Made some changes to the list to get the product names in sync with how we refer to them.  I have verified with the product team that is supported list.  Let’s go with this order

Surface Ethernet adapter
Surface USB-C to Ethernet and USB Adapter
Surface Dock
Surface Docking Station for Surface Pro 3
Surface 3
Surface Pro 3
Surface Pro 4
Surface Pro (5th Gen)
Surface Pro (5th Gen) with LTE Advanced
Surface Book
Surface Laptop (1st Gen)
Surface Pro 6
Surface Book 2
Surface Laptop 2
Surface Go
Surface Go with LTE Advanced

Thanks
