### ISSUE TITLE
Windows language on device different from English

### ISSUE THREAD

**Issue by BiljanaJaneva** [MicrosoftDocs/windows-itpro-docs#2638]
Does this policy work if language on the device is not English? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0c28c15-f0be-d732-4d9e-cf5df5e64e8b
* Version Independent ID: 17eba45f-d200-e656-42b9-e1a512931eea
* Content: [Policy CSP - RestrictedGroups](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-restrictedgroups)
* Content Source: [windows/client-management/mdm/policy-csp-restrictedgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-restrictedgroups.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by chanderjeet** [comment]
Good question. I was just wondering that myself. Any update on this @e0i

**Comment by fadenb** [comment]
@e0i ping. Can you clarify this?

**Comment by mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh** [comment]
Dutch PC reports: "Cannot find name of group" when pushing 
`<groupmembership>
	<accessgroup desc = "Administrators">
		<member name = "Administrator" />
		<member name = "AzureAD\adminUPN" />
	</accessgroup>
	<accessgroup desc = "Users">
	</accessgroup>
</groupmembership>`

No issues with the following, so issue must be with "users" not being translated.
`<groupmembership>
	<accessgroup desc = "Administrators">
		<member name = "Administrator" />
	</accessgroup>
</groupmembership>`

And indeed, the following xml is executed with no issues. 
`<groupmembership>
	<accessgroup desc = "Administrators">
		<member name = "Administrator" />
		<member name = "AzureAD\adminUPN" />
	</accessgroup>
	<accessgroup desc = "Gebruikers">
	</accessgroup>
</groupmembership>`

@e0i, is it possible to filter on SID instead of name of the group?

**Comment by mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh** [comment]
> Dutch PC reports: "Cannot find name of group" when pushing
> `<groupmembership> <accessgroup desc = "Administrators"> <member name = "Administrator" /> <member name = "AzureAD\adminUPN" /> </accessgroup> <accessgroup desc = "Users"> </accessgroup> </groupmembership>`
> 
> No issues with the following, so issue must be with "users" not being translated.
> `<groupmembership> <accessgroup desc = "Administrators"> <member name = "Administrator" /> </accessgroup> </groupmembership>`
> 
> And indeed, the following xml is executed with no issues.
> `<groupmembership> <accessgroup desc = "Administrators"> <member name = "Administrator" /> <member name = "AzureAD\adminUPN" /> </accessgroup> <accessgroup desc = "Gebruikers"> </accessgroup> </groupmembership>`
> 
> @e0i, is it possible to filter on SID instead of name of the group?

I believe you have to check the SID that is added to the machine automatically and place those two SIDs (presumably from Global Administrator and Device Administrator) to the CSP, next to the Builtin\administrator account. 

So your CSP would look like the following to clear accounts added locally: 
`<groupmembership>
	<accessgroup desc = "Administrators">
		<member name = "Administrator" />
		<member name = "enter-SID-that-you-found-in-administrators-group-on-laptop" />
		<member name = "enter-SID-that-you-found-in-administrators-group-on-laptop" />
	</accessgroup>
</groupmembership>`

There seems to be an issue with accounts being added locally after the CSP has been processed. Not sure if Microsoft already fixed that.

**Comment by VLG17** [comment]
@BiljanaJaneva  The policy works also on devices which have another language, but you need to keep in mind to specify the actual name (not translated in English) as @mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh pointed out above.

@mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh I know you can use a SID for the <member name>. I don't know if you can do tat for the <accessgroup>. Would you be able to test that?

**Comment by e0i** [comment]
Hello @BiljanaJaneva  ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Comment by BiljanaJaneva** [comment]
Hi, Thanks you all for reply. However, my case is that when i push this policy on devices with dif. language it is not applied. In some cases i even have status succeeded, but on device side Admin group is not cleared. This is what i push: 

<accessgroup desc = "Administrators">
	        <member name = "Administrator" />
                <member name = "AzureADName\xxxxxxxx" />
 </accessgroup>
