### ISSUE TITLE
Applies To section incorrect

### ISSUE THREAD

**Issue by fillip1983** [MicrosoftDocs/windows-itpro-docs#2640]
The document title is "BitLocker: How to deploy on Windows Server 2012 and later", yet just beneath that it states:

Applies to
Windows 10

No mention of Server 2012 R2 or above. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71d85a90-230f-84b0-a024-88a8da36825d
* Version Independent ID: bf2db39e-16b3-f5a8-af07-91ed301a5ca7
* Content: [BitLocker How to deploy on Windows Server 2012 and later (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-how-to-deploy-on-windows-server#feedback)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-how-to-deploy-on-windows-server.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-how-to-deploy-on-windows-server.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by drgoldman** [comment]
Get-WindowsFeature Bit
doesn't work for me. Only
Get-WindowsFeature Bit*

**Comment by Justinha** [comment]
@fillip1983 I think you might have been looking at a different BitLocker topic. This one says Applies to: Windows Server 2012, Windows Server 2012 R2, Windows Server 2016, Windows Server 2019

**Comment by illfated** [comment]
I agree, it looks like the mixed-up documents are:
- https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10
- https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-how-to-deploy-on-windows-server

**Comment by mypil** [comment]
@officedocsbot close
