### ISSUE TITLE
WIP and OWA

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#2642]
Hi, 
How about outlook.office365.com? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cf748a5-ebfd-ca94-0492-7580094618ee
* Version Independent ID: b51e7663-6ef8-e1d3-6b68-7b897093c157
* Content: [Using Outlook on the web with Windows Information Protection (WIP) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/using-owa-with-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/using-owa-with-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/using-owa-with-wip.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@lightupdifire thanks for catching that. I added it to the table.
