### ISSUE TITLE
killall

### ISSUE THREAD

**Issue by Cirrius18** [MicrosoftDocs/windows-itpro-docs#2644]
Delivery feathflea
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f20412b-125c-3c56-7b31-32bcbaa1e098
* Version Independent ID: f7c3d311-eb14-da4b-9560-e01904fd7141
* Content: [Onboard non-Windows machines to the Windows Defender ATP service](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-endpoints-non-windows-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/configure-endpoints-non-windows-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/configure-endpoints-non-windows-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **justinha**

**Comment by Cirrius18** [comment]
🏍️

**Comment by andreabichsel** [comment]
Closing for now. If you have a documentation issue to report, please let us know!
