### ISSUE TITLE
Disable Bloom for Multi-app Kiosk

### ISSUE THREAD

**Issue by alexanderbhenry** [MicrosoftDocs/windows-itpro-docs#2645]
I'm trying to design a kiosk experience that would allow a user to take pictures using the HoloLens camera through the device portal, but still have the device UI to be locked to a single app. This seems like it would only be possible by configuring as a multi-app kiosk with the specific app autolaunched. However, in order to keep the user locked in the desired app, we would need to disable the bloom gesture, though I'm not seeing any documentation about how to disable the bloom gesture, other than in the single-app kiosk. Is it possible to disable the bloom with a provisioning profile or through other settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b569a503-23e1-1fb9-69d8-c2f2bbcea1da
* Version Independent ID: 07f39c07-8cb1-b1a1-bdf5-8964d77357f9
* Content: [Set up HoloLens in kiosk mode (HoloLens)](https://docs.microsoft.com/en-us/hololens/hololens-kiosk)
* Content Source: [devices/hololens/hololens-kiosk.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/hololens/hololens-kiosk.md)
* Product: **hololens**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@alexanderbhenry Sorry for the delay in responding, I was a jury duty for a very long trial. Now that I'm back, I've contacted the product team to get their input on whether the experience you're trying to configure is possible. I'll let you know as soon as I get an answer.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by joinimran** [comment]
@alexanderbhenry Thank you for your feedback but as per my research, this is not possible to do this in Kiosk mode. You can make a user voice regarding this. 

@e0i Please guide user how he can open a user voice request.

Regards,
Imran.

**Comment by e0i** [comment]
Hello @alexanderbhenry 

Thank you for providing feedback.

Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience,

[Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

Thanks.
