### ISSUE TITLE
One Device at a Time

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/windows-itpro-docs#2646]
I've noticed that I can only enroll one device via Hybrid AutoPilot at a time - otherwise all the devices except one error out with a 0x80070774 code. This must mean the DC connector is only able to process one enrollment at a time. Can you confirm?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12823601-7426-a768-e72f-866b150baccd
* Version Independent ID: c1f993e3-a405-6860-8ab1-7b3d387b4631
* Content: [Hybrid AAD Join](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/user-driven-hybrid)
* Content Source: [windows/deployment/windows-autopilot/user-driven-hybrid.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/user-driven-hybrid.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by torgro** [comment]
hi, 2 weeks since the question was posted. Any feedback on this? We have clients waiting on implementing this right now.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by joinimran** [comment]
Hello @torgo, Have you tried to troubleshoot this from information give at https://blogs.technet.microsoft.com/mniehaus/2018/11/22/trying-out-windows-autopilot-user-driven-hybrid-azure-ad-join/

Regards,
Imran

**Comment by e0i** [comment]
@pyoungberg Can you confirm that the answer provided by @joinimran clarifies your question? We would like to follow-up. Thanks.

**Comment by e0i** [comment]
@pyoungberg 

We are closing this issue as there hasn't been a response from your side regarding the answer provided.

Feel free to re-open this issue with clarifications and we'd be glad to come up with content updates.

Thank you for providing feedback.
