### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by jbrek** [MicrosoftDocs/windows-itpro-docs#2649]
The link to PCmover Express is ad and need to be label as that.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde8580a-bd82-ebd2-3767-f3ee662a904e
* Version Independent ID: 94323219-e4ed-8761-723e-06be33c3b9cc
* Content: [User State Migration Tool (USMT) Overview (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-overview)
* Content Source: [windows/deployment/usmt/usmt-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/usmt/usmt-overview.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jozefizso** [comment]
The advertisement should be removed.

**Comment by illfated** [comment]
I think the text itself explains it quite clearly: "PCmover Express is a tool created by Microsoft's partner, Laplink."
It also points at the difference between a large scale scenario (huge amount of users & computers) and just a few PCs.
Microsoft is of course a software vendor too, although it needs to be seen in a larger context.

**Comment by Justinha** [comment]
Thanks for the comments everyone. Ads should be removed no doubt, but I agree with @illfated in this case the link is more for convenience to cover a scenario that USMT does not cover as well. @jbrek if you want to submit a pull request with the text you want to see added, we can review and merge.
