### ISSUE TITLE
Section about provisioning package is no longer accurate

### ISSUE THREAD

**Issue by jacobsweany** [MicrosoftDocs/windows-itpro-docs#265]
Within this document: 

> customize-windows-10-start-screens-by-using-provisioning-packages-and-icd.md

In this section: 
> Create a provisioning package that contains a customized Start layout

WICD is mentioned as the method to import the start and taskbar layout configuration.
This is no longer accurate as this capability was taken out of WICD after Windows 10 1703.
See MSDN article about this change [here](https://msdn.microsoft.com/library/windows/hardware/dn898375?f=255&MSPPError=-2147217396).

This documentation should be updated to reflect the correct method.

**Comment by jdeckerms** [comment]
Hi jacobsweany -- yes, the **imaging** component of Windows Imaging and Configuration Designer was removed in 1703, and the MSDN article is explaining that you can't use WICD to create OS images anymore. However, Start/taskbar layout can be applied as a **runtime** setting in a provisioning package, applied during OOBE or after OOBE is complete.

**Comment by jacobsweany** [comment]
So I understand that it needs to be applied at runtime, but my point is that you cannot even create that package anymore in Windows Imaging and Configuration Designer. 

This specific setting:

> Expand Runtime settings > Policies > Start, and click StartLayout

is not available in the current build of WICD, regardless if you select "All Windows editions".

**Comment by jdeckerms** [comment]
That setting is there is you select "All Windows desktop editions".

**Comment by jacobsweany** [comment]
Thanks! Apparently I didn't see "All Windows **desktop** editions".

**Comment by jdeckerms** [comment]
Not a problem and glad we could figure it out. I appreciate you letting us know when you find issues in the docs -- thie one didn't need a fix, but others that you find might, so thank you!
