### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by trophywtf** [MicrosoftDocs/windows-itpro-docs#2651]
Can you please update this documentation to include what kind of permissions is needed to perform Autopilot Local Reset, or link to documentation describing roles that are needed. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ddb8fb-cc02-9821-d2d3-8bd724021e6f
* Version Independent ID: e003bcd6-b285-3b46-dbf3-1ee91eef2b1b
* Content: [Reset devices using local Windows Autopilot Reset](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-reset-local)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-reset-local.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-autopilot-reset-local.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@trophywtf - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
