### ISSUE TITLE
Legacy Terms

### ISSUE THREAD

**Issue by danjpadgett** [MicrosoftDocs/windows-itpro-docs#2652]
The content needs to be updated to remove references to old W10 servicing terms such as, current branch and current branch for business. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda43942-cce6-c093-0637-21b5c6e00335
* Version Independent ID: 03a1e0bd-83ac-666d-da6b-c47259fe8b02
* Content: [Windows 10 deployment considerations (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-deployment-considerations)
* Content Source: [windows/deployment/planning/windows-10-deployment-considerations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-10-deployment-considerations.md)
* Product: **w10**
* GitHub Login: @mtniehaus
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by illfated** [comment]
Relevant information:
- https://docs.microsoft.com/en-us/windows/deployment/update/waas-overview#naming-changes

> As part of the alignment with Windows 10 and Office 365 ProPlus, we are adopting common terminology to make it as easy as possible to understand the servicing process. Going forward, these are the new terms we will be using:
>
> - Semi-Annual Channel - We will be referring to Current Branch (CB) as "Semi-Annual Channel (Targeted)", while Current Branch for Business (CBB) will simply be referred to as "Semi-Annual Channel".

**Comment by illfated** [comment]
@danjpadgett : Could you help us by pointing out more keywords and phrases you find to be outdated in the article?

**Comment by mypil** [comment]
@danjpadgett - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
