### ISSUE TITLE
Add Custom App to be protected

### ISSUE THREAD

**Issue by dbznico** [MicrosoftDocs/windows-itpro-docs#2654]
Hello,

Can we add custom application to be protected by WIP ? Like Box Drive or other ?

Thanks,

Best regards, Nicolas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ad3f92-24de-5eb5-8454-c72d85737183
* Version Independent ID: 900125eb-31ea-faf3-ac30-7c3d7b30f611
* Content: [Create a Windows Information Protection (WIP) policy with MAM using the Azure portal for Microsoft Intune (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-mam-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-mam-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/create-wip-policy-using-mam-intune-azure.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@dbznico this seems like a dup of what we discussed in issue #2643
