### ISSUE TITLE
Malware Protection Center Portal URL

### ISSUE THREAD

**Issue by jayceke** [MicrosoftDocs/windows-itpro-docs#2656]
Does this URL need to be updated to https://www.microsoft.com/en-us/wdsi/filesubmission ??  The current URL [https://www.microsoft.com/security/portal/submission/submit.aspx], fails to resolve.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dce2d9b-f59e-65bb-6ca2-0de4cd142cf2
* Version Independent ID: fc82b0f2-8add-863b-1af6-6c9ac8527c33
* Content: [Take response actions on a file in Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/respond-file-alerts-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/respond-file-alerts-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/respond-file-alerts-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Hi jayceke, yes you are right. Will get this fixed.

Thanks!
