### ISSUE TITLE
Uservoice link is dead

### ISSUE THREAD

**Issue by adwilso** [MicrosoftDocs/windows-itpro-docs#2659]
The user voice link at the bottom of the page (text: Application Virtualization feedback site) points to a page that 404s.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b89731e0-2194-feae-50b5-867838a44ecd
* Version Independent ID: 7d2bc3b5-27e2-55ae-5e89-528c2ba55d3f
* Content: [Evaluating App-V (Windows 10)](https://docs.microsoft.com/en-us/windows/application-management/app-v/appv-evaluating-appv)
* Content Source: [windows/application-management/app-v/appv-evaluating-appv.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/app-v/appv-evaluating-appv.md)
* Product: **w10**
* GitHub Login: @MaggiePucciEvans
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
Thanks for raising this issue. The link is very dead, so I've removed it. You'll see the fix live on 3/18 by end of day. Thanks!
