### ISSUE TITLE
Server 2019

### ISSUE THREAD

**Issue by tjoycebrook** [MicrosoftDocs/windows-itpro-docs#2660]
This has not been updated since Windows server 2019 was released. Are 2019 DC supported as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1da1ac4-4e67-5970-6d10-19aac6e853f6
* Version Independent ID: 4f4b45eb-d479-3699-1ef1-a1a20030d675
* Content: [Planning an adequate number of Windows Server 2016 Domain Controllers for Windows Hello for Business deployments](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by ojrb** [comment]
@mypil The PR #3852 solved this Issue

**Comment by mypil** [comment]
@tjoycebrook - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
