### ISSUE TITLE
Thanks for Disable on Edge Pre-Load/Launch

### ISSUE THREAD

**Issue by strecz** [MicrosoftDocs/windows-itpro-docs#2661]
Thanks for giving option and instructions to disable -- pre-launch and pre-load are decent features I just discovered but actually nicer and more important to the experience was the ability to easily find how to turn off such features if I wanted to... and I I did immediately turn them off because Edge is not my primary browser as of now.

See, this is what you get when you give customers what they want. Still doesn't make up for the MS App Store driveby download of unwanted Twitter & Candy Crush Saga App purchases that earns you the F-You's yesterday.  Much better job today. (Still doesn't come close to making up for yesterday).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e25cdec-6b2f-2e44-6512-83b13d13ff51
* Version Independent ID: f97436ae-01fc-a3bb-d0e8-2b20265ebc56
* Content: [Microsoft Edge - Prelaunch and tab preload group policies](https://docs.microsoft.com/en-us/microsoft-edge/deploy/group-policies/prelaunch-preload-gp)
* Content Source: [browsers/edge/group-policies/prelaunch-preload-gp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/group-policies/prelaunch-preload-gp.md)
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by jdeckerms** [comment]
@strecz Thanks, we appreciate the feedback!
