### ISSUE TITLE
maybe an extra step is mentioned in the doc?

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/windows-itpro-docs#2663]
I am using 1803 Enterprise and the only thing I did was enabling virtualization support in UEFI and pushing the GPO. now both the script and the msinfo32.exe report that Virtualization Based Security and Credential Guard are working. 
does 1803 enable Hyper-V on its own just by enabling the GPO? I checked the installed component and no Hyper-V component is installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@sasanmcp yes, you only need to enable the GPO, or you can turn it on via Settings too. VBS support will be configured automatically. I think it installs Hyper-V platform? But not all of the Hyper_v feature.

**Comment by sasanmcp** [comment]
So the doc should be updated to reflect that. I guess the doc is still listing the steps required on an older release of Windows 10.

**Comment by Justinha** [comment]
there is this text:
Starting with Windows 10, version 1607 and Windows Server 2016, enabling Windows features to use virtualization-based security is not necessary and this step can be skipped.

But I agree at this point it might be better to remove the step to prevent further confusion.
