### ISSUE TITLE
Documentation / stability issues

### ISSUE THREAD

**Issue by Ludwig1770** [MicrosoftDocs/windows-itpro-docs#2667]
It's very frustrating when code snippets don't work; can versions of libraries be specified if the regular improvements lead to incompatibilities (and I'm very supportive of deprecating ineffective legacy code)?

A couple of issues in the code snippet above:

''''
AuthenticationContext context = new AuthenticationContext(string.Format("https://login.windows.net/{0}/oauth2", tenantId));
ClientCredential clientCredentials = new ClientCredential(clientId, clientSecret);
AuthenticationResult authenticationResult  = context.AcquireToken(resource, clientCredentials);
''''

The AuthenticationContext.AcquireToken doesn't seem to exist any more - been replaced by AcquireTokenAsync it seems.
Also it would be useful to know what type "resource" is in the deprecated method.

Given my inability to test the request parameters above, are these the only fields that can be used to filter event data i.e. the fields detailed in the Windows Defender ATP alert API fields page are not usable?

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b835bf35-1614-2d8d-13ab-176c6d839047
* Version Independent ID: ed4653f3-e393-dd42-5960-87888c08ba40
* Content: [Pull Windows Defender ATP alerts using REST API](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/pull-alerts-using-rest-api-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/pull-alerts-using-rest-api-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/pull-alerts-using-rest-api-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by mjcaparas** [comment]
Hi, thank you for your feedback. Checking with the engineering team.

**Comment by mjcaparas** [comment]
Updates to the code snippet will be published by this afternoon. Closing.
