### ISSUE TITLE
Provision after setup from something other than USB?

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/windows-itpro-docs#2675]
I'm using the provision "After setup, from a USB drive, network folder, or SharePoint site".  The only option 1809 offers is "Removable media".  Is there something else that has to be done to use a network share?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78038d67-04a1-f4ae-6a69-98e157688a31
* Version Independent ID: c86b4460-e8be-8537-a6c8-3cb094ef14a3
* Content: [Set up a multi-app kiosk  (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps#after-setup-from-a-usb-drive-network-folder-or-sharepoint-site)
* Content Source: [windows/configuration/lock-down-windows-10-to-specific-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/lock-down-windows-10-to-specific-apps.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by chjone** [comment]
You can use PowerShell to create an ISO file of your provisioning package directory. 

Grab the New-ISOFile function from the TechNet Gallery: https://gallery.technet.microsoft.com/scriptcenter/New-ISOFile-function-a8deeffd

Once you've loaded the function, run the following from an elevated PowerShell window: <path to provisioning package> | New-IsoFile -Path <full path file name.iso> 

Example: C:\temp\kiosk_provisioningpackage | New-IsoFile -Path c:\temp\kiosk.iso

Some things to note: make sure you've closed the WCD prior to running the cmd. Also make sure your provisioning package path is the dir where the .ppkg file resides.

Alternatively, you can just double-click on the .ppkg file to apply it.

**Comment by FC-EricWeller** [comment]
Okay - so that sounds to me like the section needs to be updated to remove the "Network folder or Sharepoint site" part?

**Comment by chjone** [comment]
Not necessarily. Those methods are still applicable. The problem comes in when you use the Settings app to add the package (like in the image under the "After setup, from a USB drive, network folder, or SharePoint site" step), that step will only allow you to install a provisioning package via removable media such as a USB drive or from a mounted ISO file/DVD, etc. It doesn't offer a way to navigate to a network share or URL, etc. So, some other options to add it would be to use PowerShell, DISM, copy locally and double-click the ppkg file to name a few.

**Comment by FC-EricWeller** [comment]
Alright - but the if we want the heading to say "...from a network share or SharePoint site" we need to have instructions here for applying from a network share or a SharePoint site.  The only instruction provided is using the Settings app, which doesn't do either of those things apparently.

**Comment by chjone** [comment]
[This site](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-apply-package#desktop-editions) has the following line added which would address it: _For a provisioning package stored on a network folder or on a SharePoint site, navigate to the provisioning package and double-click it to begin installation._  PowerShell method is available [here](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-powershell), if you were looking to add that.

**Comment by jdeckerms** [comment]
@FC-EricWeller Thanks for pointing out the problem, I'll update the topic by end of day.
