### ISSUE TITLE
404 - Content Not Found for link https://go.microsoft.com/fwlink/?linkid=832647 in EventID 360 - User Device Registration

### ISSUE THREAD

**Issue by mvaneijken** [MicrosoftDocs/windows-itpro-docs#2680]
The link in EventID 360 - User Device Registration "https://go.microsoft.com/fwlink/?linkid=832647" gives a 404 - Content Not Found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d45db5-5172-45cb-2c4d-d73a9e15d699
* Version Independent ID: fa08e81d-3307-514e-129a-843e812e97a9
* Content: [Hybrid Windows Hello for Business key trust Provisioning (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@mvaneijken - Thank you for submitting feedback.

When I checked on the article, I cannot find the EventID 360 link that you mentioned in this issue. This could mean that this link was removed from this article. 

Thank you.

**Comment by illfated** [comment]
@mypil : The link referred to by @mvaneijken is not a link in the article document, but the link appearing in Event Viewer in Windows 10.

![event358 1](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/images/event358.png)

The link referred to by @mvaneijken -- https://go.microsoft.com/fwlink/?linkid=832647 -- points to
- https://docs.microsoft.com/windows-server/identity/ad-fs/whats-new-active-directory-federation-services-windows-server

... which gives the 404 page.

**Comment by illfated** [comment]
See also this Technet page (from 1 year ago) for related info:
https://social.technet.microsoft.com/Forums/en-US/3860e01c-abe1-4957-9483-43f131aa5a7d/windows-hello-for-business-user-device-registration-error?forum=win10itprosetup

**Comment by mypil** [comment]
@illfated - Thanks for the clarification. 

@mvaneijken - I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by illfated** [comment]
@mvaneijken : If your Event ID 360 is on Windows Server 2016, the software may not be updated enough and the so-called "What's new" page may have been moved because of Windows Server 2019.

**Comment by mypil** [comment]
@officedocsbot close
