### ISSUE TITLE
Windows Analytics in Govt tenants

### ISSUE THREAD

**Issue by Mcclellange** [MicrosoftDocs/windows-itpro-docs#2681]
I wasn't able to find any information on whether or not Windows Analytics was available in the Govt Tenants.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21e82831-aa63-55a0-db06-b99d2de80875
* Version Independent ID: f7df6d20-df9b-b5a1-1a8b-1d50b9ead27d
* Content: [Windows Analytics and privacy](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-privacy)
* Content Source: [windows/deployment/update/windows-analytics-privacy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-privacy.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Could you be referring to Azure Government? If so, then Windows Analytics is not available there.
