### ISSUE TITLE
Inaccurate

### ISSUE THREAD

**Issue by egitdept** [MicrosoftDocs/windows-itpro-docs#2689]
This article ONLY applies to two versions of Windows 10.  All others are doomed if they try this.  You can configure policies that will not be observed.  The article should probably just be removed - lacking that it should be revised to show the actual versions of Win 10 that work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7f3a23f-069e-5c6c-0579-3ad3f86d7a0e
* Version Independent ID: 355f5770-895e-4d79-3aad-f5120b014f70
* Content: [Use AppLocker to create a Windows 10 kiosk that runs multiple apps (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-applocker#feedback)
* Content Source: [windows/configuration/lock-down-windows-10-applocker.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/lock-down-windows-10-applocker.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@egitdept Sorry, the documentation applies to Windows 10, version 1703 which is still in support through October 2019 (https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet). We won't remove it while it's still supported.
