### ISSUE TITLE
System account is missing

### ISSUE THREAD

**Issue by jinop** [MicrosoftDocs/windows-itpro-docs#2693]
"cn=System,cn=WellKnown Security Principals, cn=Configuration, dc=&lt;forestRootDomain&gt;"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 486e8a12-8230-6ae2-264f-73c76b266682
* Version Independent ID: 2f47f94f-b416-beac-c75d-8908e4000e66
* Content: [Special Identities (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/special-identities)
* Content Source: [windows/security/identity-protection/access-control/special-identities.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/access-control/special-identities.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jinop - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by jinop** [comment]
Thanks for your prompt response
