### ISSUE TITLE
OPENING NEW WINDOW AND IT SIGN ME OUT

### ISSUE THREAD

**Issue by Pestonskyrider** [MicrosoftDocs/windows-itpro-docs#2702]
It does not do this to me all the time. I will have a lot of windows open and jumping to from page to get the info I need. What I find at times that I find on one page I'm signed in and some of the others I'm signed out. I have not into any other site. I find that some sites have their own dashboard that you have to sign in to their site taking one out. But there are times that I have gone to a site were it just sign me out make a real pain. I might be trying to download or some other thing the site. Does anyone know why a site might what to sign you out.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5da56626-d2d9-ae41-3ebb-f4e75a1a9038
* Version Independent ID: 5963ceee-7398-f0b4-1649-6e744a424174
* Content: [Windows 10, version 1809 - Features that have been removed](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-1809-removed-features)
* Content Source: [windows/deployment/planning/windows-10-1809-removed-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-10-1809-removed-features.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
I don't really know what causes your issue, but I can only guess that it has got something to do with your browser (and possibly other unrelated software). At first I thought you might have forgotten to tell your browser to remember your password, but then again I don't know if you are using Microsoft Edge, Microsoft Internet Explorer or any other browser.

The only thing I can recommend is to do normal browser troubleshooting by resetting the browser to an empty state (use settings to empty cache, clear passwords and all other settings). If that does not help, remove any addons you might have installed in the browser. You should also test on a secondary computer or in a virtual machine.

Then again, this looks like something you should contact Microsoft Support about, if you are unable to solve it by regular troubleshooting.

**Comment by Pestonskyrider** [comment]
Thanks for replaying. I reset my router for all things and it all went away.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by illfated** [comment]
Very well. Not a Microsoft issue or missing documentation, but user configuration.
Please close this issue now that it has been solved.

**Comment by e0i** [comment]
@lizap The issue can now be closed.
