### ISSUE TITLE
new version is 3.6

### ISSUE THREAD

**Issue by timsmallwood** [MicrosoftDocs/windows-itpro-docs#2705]
command should be updated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#turn-off-with-hardware-readiness-tool)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by joinimran** [comment]
@timsmallwood Can you please share more details or specifics to the command which should be updated.

**Comment by e0i** [comment]
Relevant changes have been proposed at PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/2750
