### ISSUE TITLE
Multi-App-Kiosk Provisioning succeded but Local Standard User Logon loops

### ISSUE THREAD

**Issue by longgiangp** [MicrosoftDocs/windows-itpro-docs#2707]
I have been trying to lock two Win32 in an assigned access with a custom Start Layout. The provisioning succeded but if i switch to the local standard user, it loops in an logoff and logon screen to eternity. 

The Kiosk Machine is running Windows 10 Pro.

**Comment by illfated** [comment]
This may be a shot in the dark (no personal experience with this), but have you tried logging in as an administrator first, log out and then log in the standard user to see if it still happens?

**Comment by jdeckerms** [comment]
@longgiangp Sorry, there aren't enough details in your comment for me to know what the problem might be. You should contact Microsoft Support (https://support.microsoft.com/en-us/contactus/).
