### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by fumantsu** [MicrosoftDocs/windows-itpro-docs#2708]
The instructions on the Refresh Token via restutil are not working. Only the command gives error: Failed to process the request: Option value is missing for -config. Also step c. is not clear

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 250b790c-3309-2651-cefd-e94d3dd5bc11
* Version Independent ID: 54000705-40ce-d014-7bda-4296c1de2e29
* Content: [Configure HP ArcSight to pull Windows Defender ATP alerts](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-arcsight-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/configure-arcsight-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/configure-arcsight-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by joinimran** [comment]
@fumantsu To retrieve a refresh token, invoke the tool with the token command:
**arcsight restutil yourtoken <-proxy >**
For example: **arcsight restutil boxtoken -proxy proxy.location.hp.com:8080**

For your concern regarding point c, when you will enter the command it will launch the web browser for you to login to the portal using your admin account.

**Comment by e0i** [comment]
@mjcaparas Please review the fix is available for this issue via PR #2824 Thanks.

**Comment by joinimran** [comment]
Is there any update on this PR?

Regards
*Muhammad Imran Habib*

**Comment by mjcaparas** [comment]
Approved and merged.
