### ISSUE TITLE
CG Causes vmware (ver. 14 / 15 etc) to fail, Also causes memu app player to fail 

### ISSUE THREAD

**Issue by djlaserman** [MicrosoftDocs/windows-itpro-docs#2711]
I have been getting a dozen blue screens since last year around july whenever I tried to run memu app player or other android emulators. the only exception to this was that I could run a limited version of the android studio emulator (in the sense that I could not install intel haxm) I guess the answer to that is because of the "background usage of virtualization hardware resources" by Windows 10 in the name of "Credential Guard". So now vmware churns out an error leading to these pages, memu just quits as it loads or when you try to set up the virtualization. Am running latest (fast) insider version of Windows, always, on a Fujitsu Tx 120 Sp3 server, with all the correct VT-d and Hyperthreading BIOS settings. I do not get the insanely hard method of getting to tweak the CG option, or to turn it off, just the same as I do not see any innovation in so many years same issue, since Windows 8 you just can't run other VMs in peace without cracking your inner-peace in fury to find the bcedit, wp-shell, and cmd commands + using the registry just to try to disable this. It is an absolute pain in the ass for us programmers ever since! Can't someone with a degree or something at Microsoft just place one button to tweak this in the control panel or some other convenient place please!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f5b9ff0-c74a-81e0-d9c8-7f42a97e872b
* Version Independent ID: 5ab185fd-8de6-5481-829c-ae12022d836c
* Content: [Windows Defender Credential Guard - Known issues (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-known-issues)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-known-issues.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-known-issues.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by egallagh** [comment]
Hi djlaserman.
Sorry that you are having issues.
Please understand that this site is a product documentation site and not a support nor a feature request site. As such, the feedback section here is intended for feedback on the documentation and not intended for feedback on product features not troubleshooting. For product feature requests you can submit via User Voice. For troubleshooting you can visit support.microsoft.com or open a support ticket.
In hope of addressing your issue, please understand that not all Windows control is presented via a GUI, nor is it intended to be. If you have a configuration change that needs repeating, I would suggest creating a script to speed the repeated reconfiguration.
I would also suggest that the insider builds are not intended to be used as production systems for development or other production purposes. I would recommend that you look into using a production version of Windows 10 for that purpose. BTW, there is a separate feedback channel for Windows Insiders to report issues with the Insiders builds.
I hope this helps.
Recommend closure.

**Comment by xeongold** [comment]
> 
> 
> Hi djlaserman.
> Sorry that you are having issues.
> Please understand that this site is a product documentation site and not a support nor a feature request site. As such, the feedback section here is intended for feedback on the documentation and not intended for feedback on product features not troubleshooting. For product feature requests you can submit via User Voice. For troubleshooting you can visit support.microsoft.com or open a support ticket.
> In hope of addressing your issue, please understand that not all Windows control is presented via a GUI, nor is it intended to be. If you have a configuration change that needs repeating, I would suggest creating a script to speed the repeated reconfiguration.
> I would also suggest that the insider builds are not intended to be used as production systems for development or other production purposes. I would recommend that you look into using a production version of Windows 10 for that purpose. BTW, there is a separate feedback channel for Windows Insiders to report issues with the Insiders builds.
> I hope this helps.
> Recommend closure.

Hi mister Hero defender of MS, can you whisper me which "production" version should we/i use to avoid "3rd" party guests using my 1Gb fiber and CPU's(more expensive then its weight in gold ??)  will s2016 be ok for that? before i buy i want to know, cuz i need MS but i don't trust with that cash.
p.s. since i got 2 3ms ping with google there are a lot of "rats" running in and out the pipe, that thin clear pipe that's meant for completely something else that doesn't bring profit but instead helps ppl by being fast at communicating emergencies. when that happens it sends different messages and connects to different servers and sometimes there are some "rat" excrements on the pipe and if something is gonna happen, even tho delay it might be small they will blame the "cat" defending the Alarm room, and all the jargons in the world will not help

**Comment by e0i** [comment]
@officedocsbot close
