### ISSUE TITLE
Stop updating when I manually restart?

### ISSUE THREAD

**Issue by comet52a** [MicrosoftDocs/windows-itpro-docs#2712]
I support Win LTSB point of sale systems , have gp setup to install updates at a specific time during the night each week.   Problem occurs- updates "pile up" during the week as they download, and if a user needs to reset a workstation, they install during the reboot.   This is an issue when we are rebooting a terminal during busy lunch and now it is unavailable for 2 hours while updates run.   Is there a way to force it not do updates on a manual reboot, and only do them on the scheduled reboot?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184809a-63ff-ecc2-ab67-9c9f4df900f8
* Version Independent ID: ac25ee6c-4c57-58b3-1313-e4a53f53c5a1
* Content: [Manage device restarts after updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-restart#)
* Content Source: [windows/deployment/update/waas-restart.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-restart.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by egallagh** [comment]
I have not tried this recently, but instead of rebooting from the start button, use <CTRL> <ALT> <DEL> to access the security screen and use the power button in the lower right corner of the screen. Let me know if that works.
Hope it helps.

**Comment by egallagh** [comment]
Hmm. What I typed was interoperated by GitHub in a way I did not expect. Lets try again.
Use CTRL ALT DEL to access the security screen and use the power button in the lower right corner of the screen. Hope it helps. Let me know if it works.

**Comment by e0i** [comment]
@comet52a Can you confirm that your question has been answered? We would like to follow up. Thanks.

**Comment by e0i** [comment]
Hello @comet52a  ,

We are closing this issue since your support question seems to be answered. Feel free to re-open this issue if you still experience problems.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
