### ISSUE TITLE
How to change Bulk token expiration date 

### ISSUE THREAD

**Issue by jenyalex80** [MicrosoftDocs/windows-itpro-docs#2713]
It was mentioned in the uservoice that we can now set bulk token expiry to 180 days. https://microsoftintune.uservoice.com/forums/291681-ideas/suggestions/19419463-azure-ad-bulk-token-expiry-date-to-be-longer
However, we don't see a means to doing this through the UI. Can someone please update this article with that info. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44f09eb2-3111-bdd9-4a1f-1afa44322202
* Version Independent ID: b9d225ff-022f-92f2-e24f-41989fccf178
* Content: [Provision PCs with common settings (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provision-pcs-for-initial-deployment)
* Content Source: [windows/configuration/provisioning-packages/provision-pcs-for-initial-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/provisioning-packages/provision-pcs-for-initial-deployment.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@jenyalex80 The capability to extend the bulk token expiration will be added in the next major release of Windows Configuration Designer to correspond with the next feature update to Windows 10.  The documentation will be updated at the same time, thanks!

**Comment by petrozio** [comment]
Our 180 bulk token period has now expired. We still need to migrate more clients. Can the token validity date be extended, or is it better to create a new package with a new token?
