### ISSUE TITLE
FVE_NKP or FVENKP?

### ISSUE THREAD

**Issue by Lexy2** [MicrosoftDocs/windows-itpro-docs#2714]
The store name varies within the article. Sometimes you say that the network unlock certificate should be in FVE_NKP store, sometimes you say that the certificate should be in FVENKP store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c13083-9b29-e54b-fd85-8033ec665fcd
* Version Independent ID: ce8c4647-69bc-95d4-2192-6e737d5ad5da
* Content: [BitLocker How to enable Network Unlock (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by illfated** [comment]
Good point, although it looks like there is only 1 mention of `FVENKP` on the entire page (whereas there are 3 uses of `FVE_NKP`) and it could in theory be a typo in the single use of `FVENKP`. If it is indeed a typo, this has unfortunately emigrated to any external page using this documentation, as a search engine search result will show you (34 page hits for `FVENKP` / 35 page hits for `FVE_NKP` -- on www.bing.com ), suggesting that there are close to the same amount of pages referencing `FVENKP` as `FVE_NKP` (likely on the same page).

Feedback from someone well versed in this topic regarding if this is a typo or not, will be appreciated, although we could open a Pull Request to have the typo rectified.

**Comment by Lexy2** [comment]
I finally managed to configure the Network Unlock feature.
*On the clients* the certificate store should be *FVE_NKP*. Can't comment about the WDS server.
I will work on a PR tomorrow.

**Comment by Lexy2** [comment]
#2722 created

**Comment by illfated** [comment]
This issue ticket can be closed now.
