### ISSUE TITLE
For remote deployments will there ever be a possibility of application via email attachments? 

### ISSUE THREAD

**Issue by Nick-Shortal** [MicrosoftDocs/windows-itpro-docs#2719]
Our remote notebook users are heavy users of LTE services which are dependant on APN application.
Will it ever be possible to provide our staff provisioning packages that can be applied via an attachment?
I appreciate there may be security concerns with this, but this is just as much as concern of our remote users plugging in a random USB to apply the same package we supply to them.  nick.shortal@apiam.com.au 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 130f5d75-4b2b-5d1f-3505-6a5fb9cb00b8
* Version Independent ID: c594739e-bc96-720b-a667-1a62601bf49a
* Content: [Use Windows Configuration Designer to configure Windows 10 Mobile devices (Windows 10)](https://docs.microsoft.com/en-au/windows/configuration/mobile-devices/provisioning-configure-mobile)
* Content Source: [windows/configuration/mobile-devices/provisioning-configure-mobile.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/mobile-devices/provisioning-configure-mobile.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by mypil** [comment]
@Nick-Shortal - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
