### ISSUE TITLE
Clarification about the paths derivation in the exclusions, when they are referring to registry (like NTDS)

### ISSUE THREAD

**Issue by GeoSimos** [MicrosoftDocs/windows-itpro-docs#2721]
It is not clear to me if the exclusions are specific like the NTDS one or their paths are derived from the registry dynamically.
Although at the beginning of this document it is stated that the automatic exclusions apply to the default paths of the roles, later in their descriptions the registry path location is contradicting with the first statement.
Would you please clarify this, because in many implementations of Active Directory we use a best practice to move NTDS and SYSVOL to another drive and would like to know if we have to manually add the exclusions above.
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9b6379-e575-9819-eca1-a0952f66b655
* Version Independent ID: 34d81602-ffa2-5be6-67ef-b42b3b6f17ee
* Content: [Configure Windows Defender Antivirus exclusions on Windows Server 2016](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus#list-of-automatic-exclusions)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by mypil** [comment]
@AndreaBarr - please assign this issue to me. Thanks.

**Comment by mypil** [comment]
@GeoSimos -  Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by GeoSimos** [comment]
Thank you, I will be checking periodically for the content's update :)

**Comment by j0rt3g4** [comment]
Hello  @GeoSimos, I was not able to find any conflict, I've added a note if you change the default path of the NTDS and SYSVOL, it can be manually added to the exclusions since it's not the default path of the role.
The PR is #2942

**Comment by mypil** [comment]
@GeoSimos - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
