### ISSUE TITLE
Update required

### ISSUE THREAD

**Issue by kumaarrahul** [MicrosoftDocs/windows-itpro-docs#2723]
Hi,

The article mentions the requirement as Windows 10 installed.

"To take advantage of this offering, you must have the following:

Windows 10 Pro, version 1607 (also known as Windows 10 Anniversary Update) or later installed on the devices to be upgraded."

This creates confusion that Windows 10 E3 will activate Windows whereas it only offers Windows 10 Enterprise upgrade.

The other article clearly mentions the word 'Activated' as a pre-requisite.

https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-subscription-activation

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf22b00-1c7f-5fd8-7e21-f3a50da00a15
* Version Independent ID: f118fd3a-d0b3-ae53-0b59-a049fe18eb15
* Content: [Windows 10 Enterprise E3 in CSP](https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-e3-overview)
* Content Source: [windows/deployment/windows-10-enterprise-e3-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-enterprise-e3-overview.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@AndreaBarr  - please assign this issue to me. Thanks.

**Comment by mypil** [comment]
@kumaarrahul - Thank you for pointing this out.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by illfated** [comment]
From the enterprise subscription activation page:
> Windows 10 (Pro or Enterprise) version 1703 or later installed and activated on the devices to be upgraded.

Suggested improvement based on what @kumaarrahul indicated in the ticket:
> Windows 10 Pro, version 1607 (also known as Windows 10 Anniversary Update) or later installed **and activated** on the devices to be upgraded

**Comment by nenonix** [comment]
@illfated Thank you. We really appreciate helpful feedback that improves clarity and assists us to make accurate changes.
