### ISSUE TITLE
Choose to set up Azure Rights Management with WIP

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#2724]
Hello,
Please update article section "Choose to set up Azure Rights Management with WIP":

&lt;&lt;Optionally, if you don’t want everyone in your organization to be able to share your enterprise data, you can set the RMSTemplateIDForEDP MDM setting to the TemplateID of the Azure Rights Management template used to encrypt the data. You must make sure to mark the template with the EditRightsData option. &gt;&gt;

To make it clear, Azure RMS and WIP only applies if protected by WIP file were moved to external USB/disk. 
So if people, who use Azure RMS enabled in their Azure tenant, knows how "template id" with protection works, not get confused, that files, as example, if file saved from protected source and it is protected by WIP, that this file will receive Azure RMS protection from template ID, while file located on PC. Azure RMS protection from template ID will apply only if you copy file to external disk.

I would include a link to "testing scenarios" as follow:
If Azure RMS enabled with/without template, after file saved from protected source:
1. Run test on file using Azure RMS PS: Get-RMSFileStatus -File "C:\somefile.xxx"
Result should be Unprotected
2. Copy file as work protected to USB disk
3.  Run Azure RMS PS pointing to USB: Get-RMSFileStatus -File "E:\somefile.xxx" 
Result should show that file is Protected

To get Azure RMS PS, please install Azure Information Protection client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df27add-73fe-4f0b-7e30-face0f95cda3
* Version Independent ID: 3ec647d9-3470-8d8b-a941-d56f6522a35e
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@AndreaBarr - please assign this issue to me. Thanks.

**Comment by mypil** [comment]
@lightupdifire -  Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
hello, @lightupdifire 
as you can see in the other paragraph (the one above the paragraph you mentioned), there is a sentence "This setting tells WIP to encrypt files copied to **removable drives** with Azure Rights Management, so they can be shared amongst your employees..."
Doesn't it point to the same idea you are talking about?
Thank you

**Comment by lightupdifire** [comment]
@MaratMussabekov 
Yes, so this makes it point to that if file is copied to USB,
But then the next line says:
"Optionally, if you don’t want everyone in your organization to be able to share your enterprise data, you can set the RMSTemplateIDForEDP MDM setting to the TemplateID"

So "Optionally", is it still for "copy file to USB stick", or if we select solution in "Optionally" sentence, this will give us some Optional futures. 

Knowing Template ID with Azure Rights Management, we got confused with this :)
But with all tests we found out already that this whole paragraph "Choose to set up Azure Rights Management with WIP" it is only about copying file to USB disk or Network share.
So file saved to PC is encrypted with WIP only, no AzureRMS applied, as soon as file is copied to USB or Network share as Work protected file, then Azure RMS applies.

**Comment by MaratMussabekov** [comment]
hello @lightupdifire,
what do you think about the pull request above? would it make the situation more clear from your opinion?
Thank you

**Comment by lightupdifire** [comment]
@MaratMussabekov,
Looks great & approved! Thanks!
