### ISSUE TITLE
WIP | Azure RMS | Testing

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#2725]
Could be handy to include in "testing scenarios" as follow:
If Azure RMS enabled with/without template, after file saved from protected source:
1. Run test on file using Azure RMS PS: Get-RMSFileStatus -File "C:\somefile.xxx"
Result should be Unprotected
2. Copy file as work protected to USB disk
3.  Run Azure RMS PS pointing to USB: Get-RMSFileStatus -File "E:\somefile.xxx" 
Result should show that file is Protected

To get Azure RMS PS, please install Azure Information Protection client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c91b024a-9642-3823-360b-d657d2f1492b
* Version Independent ID: 0540cef6-7c8b-2b7d-f10a-4fb9729c1d5d
* Content: [Testing scenarios for Windows Information Protection (WIP) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/testing-scenarios-for-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/testing-scenarios-for-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/testing-scenarios-for-wip.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@AndreaBarr - please assign this issue to me. Thank you.

**Comment by mypil** [comment]
@lightupdifire - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@lightupdifire - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
