### ISSUE TITLE
Would be nice to have a Word version of the pdf so it can easily be edited

### ISSUE THREAD

**Issue by Absoblogginlutely** [MicrosoftDocs/windows-itpro-docs#2726]
Please provide a Word (or excel) version of the worksheet so it can be edited easily

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5739fab2-c6db-a7a9-b0e7-2bf4b85912a7
* Version Independent ID: 82c58053-c1d7-d938-1b0f-f3f7f70ada3b
* Content: [Planning a Windows Hello for Business Deployment](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-planning-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-planning-guide.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by illfated** [comment]
On one hand, I can see the charm of having the ability to edit the document. On the other, I am somewhat doubtful of a document which can be edited by anyone and where (in theory) the original author could still be kept as Microsoft, even if Microsoft is unable to verify that the content is still correct after changes have been made. My suggestion would be to either install the trial version of Adobe Acrobat Pro (lasts for 6 or 7 days) to convert the document (if you are unhappy about the result after opening the PDF in MS Word as there is a warning that a large PDF document with lots of graphics could be different from the original) or ask a friend who already has got Adobe Acrobat Pro to convert it for you.

I just opened the PDF in MS Word (part of Microsoft Office Home and Business 2016) and MS Word did complain about too many spelling errors to continue displaying them. Other than that, it looks fairly similar to the PDF source.

**Comment by Absoblogginlutely** [comment]
Thank illfated - It took about 10-15 minutes to knock up a Word document that looked similar to this. Not an onerous task but something that could be easily prevented. Microsoft have a lot of other word documents available for download so I'm not sure why this is not an option. Alternatively a pdf that can be filled in would be handy.

**Comment by egallagh** [comment]
You can open a PDF with modern versions of Word and it can be edited.
Recommend closing this feedback item.

**Comment by illfated** [comment]
Just a supplementary note about converting the document in Microsoft Word (instead of converting in Adobe Acrobat Pro):
The resulting document may end up increasing its number of pages from 330 in the originating PDF to about 400 pages in MS Word,
as well as needing editing and proofreading where MS Word may have mangled some of the text lines (e.g. image descriptions etc.).

**Comment by mypil** [comment]
@Absoblogginlutely - From our understanding the issue you raised has been answered. If you feel it hasn't been answered please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.

**Comment by Absoblogginlutely** [comment]
I agree - thanks to @egallagh for pointing out that the pdf can be opened in Word - I had totally forgotten that.
@Illfated - the document is only 1 page long - it was the worksheet referenced in the deployment, not the entire Docs site for Hello.

@mypil - yes we can complete this issue and I have done so. Thanks for the input everyone.
