### ISSUE TITLE
Dead URL to download 64-bit Microsoft Safety Scanner

### ISSUE THREAD

**Issue by mavaddat** [MicrosoftDocs/windows-itpro-docs#2728]
The URL to download the 64-bit version of Microsoft Safety Scanner leads to a error page. The **Download Microsoft Safety Scanner (64-bit)** above links to [fwlink](https://go.microsoft.com/fwlink/?LinkId=212732) that then resolves to [definitionupdates](
http://definitionupdates.microsoft.com/download/definitionupdates/safetyscanner/amd64/msert.exe), which gives the XML result:

```xml
<Error>
    <Code>BlobNotFound</Code>
    <Message>
        The specified blob does not exist. RequestId:b332057b-201e-002e-4264-c90178000000 Time:2019-02-20T21:34:30.5764846Z
    </Message>
</Error>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5bb1ce3-9128-5385-4417-d22eb5f8cb77
* Version Independent ID: cb6ba731-a2c2-e9b9-7c3e-db781b1b5222
* Content: [Microsoft Safety Scanner Download](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/safety-scanner-download)
* Content Source: [windows/security/threat-protection/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/intelligence/safety-scanner-download.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Thank you for your feedback. The download seems to be working intermittently, so I suggest trying again.

**Comment by mavaddat** [comment]
> Thank you for your feedback. The download seems to be working intermittently, so I suggest trying again.

I've been trying the downloading since this morning without success. I just tried again and got the same response. 

The 32-bit download works fine.

If the download is only working intermittently, I would think that itself would be a problem. Why would a file hosted on a central server not be reliably downloadable?
