### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by BenVlie** [MicrosoftDocs/windows-itpro-docs#2733]
@Hardware-based isolation (last word of alinea) "wbsites" should be websites.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae14bfa4-3c20-78bb-d086-69a5a91cc5c3
* Version Independent ID: bb5cbe43-a796-d231-c8c2-0c6031dc47dd
* Content: [Overview of attack surface reduction](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/overview-attack-surface-reduction)
* Content Source: [windows/security/threat-protection/windows-defender-atp/overview-attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/overview-attack-surface-reduction.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by Justinha** [comment]
@BenVlie Thanks for catching that. Correction should tomorrow.

**Comment by mypil** [comment]
@BenVlie - Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
