### ISSUE TITLE
Documentation for FirewallRules/FirewallRuleName/RemoteAddressRanges should note some tokens only work on RS5 (1809)

### ISSUE THREAD

**Issue by JeffStong** [MicrosoftDocs/windows-itpro-docs#2735]
The documentation for RemoteAddressRanges notes that the following tokens are supported - *,Defaultgateway,DHCP,DNS,WINS,LocalSubnet,Intranet,RmtIntranet,Internet,Ply2Renders.  However the tokens Intranet,RmtIntranet,Internet,Ply2Render appear to only be supported on RS5.  Any attempt to set these tokens on RS4 results in failure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfea4e59-ec8c-cbdf-a039-23612c2266a5
* Version Independent ID: 7058544b-7ef2-a398-366a-cf71520aa9d8
* Content: [Firewall CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/firewall-csp)
* Content Source: [windows/client-management/mdm/firewall-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/firewall-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@AndreaBarr - please assign this issue to me. Thank you.

**Comment by mypil** [comment]
@JeffStong - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by nenonix** [comment]
@JeffStong We appreciate your efforts to clarify the docs. Could you please assist me by suggesting how this content could be edited to incorporate your feedback? (I have noted all the other issues you have raised regarding this article and would like to work with you to improve the documentation.) What do you suggest is the best way to fix this?
