### ISSUE TITLE
A PIN *is* a password

### ISSUE THREAD

**Issue by bertfw** [MicrosoftDocs/windows-itpro-docs#2736]
It doesn't matter what happens after a PIN is used, you still enter it exactly like a password. So it's not even a password replacement, it *is* a password - the bar to entry is exactly the same. I don't know why MS insists on trying to sell the PIN like it's somehow more secure. A keylogger will record a PIN just the same as it would a password; writing a PIN down on a slip of paper is exactly the same as writing a password on a piece of paper; hiding a camera to record the entry of a PIN is exactly the same as recording a password.

To the end user it doesn't matter how tied to a device a PIN is, because the typical user isn't going to use a different PIN on every device, they're just going to use the same PIN on everything because people are fed up with having to remember so many passwords. Instead of pretending PIN somehow makes Windows more secure, why not actually improve security by making two-factor authentication the norm in Windows?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c34dbafa-df3c-a5a5-32d5-2ce152893534
* Version Independent ID: cebdd9a6-45d7-6306-373c-7d31121f9e16
* Content: [Why a PIN is better than a password (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by mypil** [comment]
@bertfw - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.

**Comment by zfdang** [comment]
can't agree more! stupid idea from PM, and simple brings confusions to customers.
