### ISSUE TITLE
PowerShell script better use of set-executionpolicy

### ISSUE THREAD

**Issue by gaknigge** [MicrosoftDocs/windows-itpro-docs#2739]
Hello. You include a PowerShell script in this document to obtain the hardware hash of computers so they can be loaded into Intune for Autopilot. One line of the script uses Set-ExecutionPolicy Unrestricted. This command doesn't only set execution policy for the script, but for all PowerShell scripts used on the computer. This lowers scripting security on computers unnecessarily. 
A better option would be this command. 
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Unrestricted
That will only change Execution Policy for this PowerShell session. It won't leave the computer in a more vulnerable state after the script is finished.
Thank you for your consideration and attention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3243b015-5b5f-7a62-0d9d-767d729dc475
* Version Independent ID: ff8c0509-c075-8528-823f-c195ff4d2382
* Content: [Adding devices](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/add-devices)
* Content Source: [windows/deployment/windows-autopilot/add-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/add-devices.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by mypil** [comment]
@AndreaBarr - please assign this issue to me. Thanks.

**Comment by mypil** [comment]
@gaknigge - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by illfated** [comment]
@mypil : would you like a PR submitted for the change, or do you prefer to wait for feedback from the team regarding what should be changed?

**Comment by Jcoetsee** [comment]
@illfated I have already created the PR for the change

**Comment by illfated** [comment]
Thanks, good job. I need to go to bed soon anyway. ;-)

**Comment by Jcoetsee** [comment]
@greg-lindsay Please review the PR when you have a moment, it relates to the unrestricted mode for the powershell command to be per session instead of changing the entire policy to run that one powershell command to get the hashID information

**Comment by greg-lindsay** [comment]
Hi, I agree this is a best practice so we should accept the change.  Just understand that the device here is getting prepped to have the OS overwritten anyway so it's not a huge risk to leave it in this state. Thanks though for the comment, I think that in general we overuse the unrestricted setting and leave a lot of computers like this.

**Comment by greg-lindsay** [comment]
The merge is complete. You should see the content updated in the next day.
