### ISSUE TITLE
Irrelevant information

### ISSUE THREAD

**Issue by Witchdoc59** [MicrosoftDocs/windows-itpro-docs#2741]
I came to this page from a page that talked about activating Office 2019 however this page has no information regarding this.  The VAMT that is downloaded from this page is horribly out of date.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db3d4459-a57d-a227-a9ee-47a9d25fd8e1
* Version Independent ID: 43374c7a-f5d7-8168-6a0d-285f8fb29693
* Content: [Volume Activation Management Tool (VAMT) Technical Reference (Windows 10)](https://docs.microsoft.com/en-ca/windows/deployment/volume-activation/volume-activation-management-tool)
* Content Source: [windows/deployment/volume-activation/volume-activation-management-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/volume-activation/volume-activation-management-tool.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Witchdoc59  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Witchdoc59 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
