### ISSUE TITLE
WDATP Skype Integration 

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#2743]
The documentation is:

Enabling the Skype for Business integration gives you the ability to communicate with users using Skype for Business, email, or phone. This can be handy when you need to communicate with the user and mitigate risks.

Can you please provide a bit more information how exactly this works, the conditions etc. does this relate to when the machine is isolated from the network?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d99de0-789d-3c71-4bd9-f45e62f82a7b
* Version Independent ID: d56d09f0-1f9a-563e-fee0-142bda27a99b
* Content: [Configure advanced features in Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/advanced-features-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/advanced-features-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/advanced-features-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@AndreaBarr - please assign this issue to me. Thank you.

**Comment by mypil** [comment]
@alexverboon - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by lindspea** [comment]
@alexverboon Please have a look at this article - https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/security/tls-and-mtls. If you need further information please let me know soonest.

**Comment by mypil** [comment]
@alexverboon - I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by alexverboon** [comment]
Why would I need to open a ticket to clarify unclear documentation?  If you expect people to help improve documentation don’t ask them to open a ticket please

**Comment by mypil** [comment]
Looping in the article owner @mjcaparas as she may have some information that she can share regarding your issue.

**Comment by mjcaparas** [comment]
Hi alexverboon, 

The Skype for Business integration can be better understood in the context of machine isolation: 

https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/respond-machine-alerts-windows-defender-advanced-threat-protection#isolate-machines-from-the-network 

When a machine is being isolated from the network, there's a pop-up (as seen on step 3 in the above link) where you can choose to enable Outlook and Skype communications which allows communications to the user while they are disconnected from the network.

Hope that helps.

**Comment by alexverboon** [comment]
Hello mjcaparas,

Many thanks, that clarifies my question and that is what I assumed. So this setting applies to Skype and outlook communication when machines are in isolation mode.

Can I suggest to make that reference in the documentation?


Many thanks 
Alex
