### ISSUE TITLE
Certificate and Key mixup

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/windows-itpro-docs#2745]
I believe the following phrase should be changed. See the crossed out word and my suggested word in bold instead.

> When using a certificate, the on-premises environment can use Windows Server 2008 R2 and later domain controllers, which removes the Windows Server 2016 domain controller requirement. However, single-sign on using a ~~key~~ **certificate** requires additional infrastructure to issue a certificate when the user enrolls for Windows Hello for Business.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aeacc06-dbfc-07d8-d181-41d08d89e04b
* Version Independent ID: 6f16be7a-f5b1-fbad-15a2-18a2bc1a0716
* Content: [Azure AD Join Single Sign-on Deployment Guides](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by mypil** [comment]
@AndreaBarr - please assign this issue to me. Thank you.

**Comment by mypil** [comment]
@JonesMikael - Thank you for pointing this out.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.
