### ISSUE TITLE
Clarify requirements on Domain Controller certificate

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/windows-itpro-docs#2746]
We just configured this and saw that to be able to get the domain controller certificate correct, you needed to use the **Kerberos Authentication** certificate template instead of the older **Domain Controller Authentication** template which did not work even if we added the added **KDC Authentication** in **Intended Purposes** since the the domain controller's certificate's subject alternate name doesn't have the DNS name of the domain.

Even though **Kerberos Authentication** template is for Windows Server 2008 and above, it's not default, not even when installing a greenfield Windows Server 2016 server/domain/CA. So maybe we should clarify that you should re-configure your CA to issue the **Kerberos Authentication** template to domain controllers instead of any other older template. This would at least have saved us a few hours of troubleshooting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c175ce-52a4-8b46-716f-106b4d55106c
* Version Independent ID: 374a7e9d-6e4f-f188-328b-4ca2651a9481
* Content: [Configure Azure AD joined devices for On-premises Single-Sign On using Windows Hello for Business](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by mypil** [comment]
@AndreaBarr - please assign this issue to me. Thanks.

**Comment by mypil** [comment]
@JonesMikael -  Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JonesMikael - From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
