### ISSUE TITLE
Event ID Failures

### ISSUE THREAD

**Issue by JonBrekhus** [MicrosoftDocs/windows-itpro-docs#2747]
Any information would be helpful in solving these errors. 

Event ID 7211 - The Secondary Account Primary Refresh Token prerequisite check failed.

Followed by 
Event ID 7206 - Windows Hello for Business failed to locate a certificate registration authority.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d45db5-5172-45cb-2c4d-d73a9e15d699
* Version Independent ID: fa08e81d-3307-514e-129a-843e812e97a9
* Content: [Hybrid Windows Hello for Business key trust Provisioning (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by egallagh** [comment]
Hi JonBrekhus.
Sorry that you are having issues.
Please understand that this site is a product documentation site and not a support nor a feature request site.
As such, the feedback section here is intended for feedback on the documentation and not intended for feedback on product features nor troubleshooting.
For product feature requests you can submit via User Voice.
For troubleshooting you can visit support.microsoft.com, answers.microsoft.com or open a support ticket.
I hope this gets you pointed in the right direction.
Recommend closure.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.

**Comment by JonBrekhus** [comment]
Stupid!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by JonBrekhus** [comment]
How the do i delete my post then?

**Comment by JonBrekhus** [comment]
This sucks!

**Comment by egallagh** [comment]
Hi Jon.
No need to delete.
This issue was closed and will slide into a different bucket.
Best of luck with your troubleshooting!
