### ISSUE TITLE
No support for refresh product key data online

### ISSUE THREAD

**Issue by bob-lockwood** [MicrosoftDocs/windows-itpro-docs#2749]
It seems a shortcoming that Volume Activation Management Tool (VAMT) Cmdlets in Windows PowerShell don't appear to provide a mechanism to "refresh product key data online".  I am trying to automate monitoring of our usage of bulk licenses for our embedded products and seems I can only query the DB, not force it to update.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd87fa3e-37e5-dfb4-2693-2892bc063f13
* Version Independent ID: de9cb0ae-bfc7-ddbe-5e9e-b4b2f960c361
* Content: [Use VAMT in Windows PowerShell (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/volume-activation/use-vamt-in-windows-powershell)
* Content Source: [windows/deployment/volume-activation/use-vamt-in-windows-powershell.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/volume-activation/use-vamt-in-windows-powershell.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@bob-lockwood - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.

**Comment by bobobobobovic** [comment]
Hi how can I get access to this functionality ? I have tried Get-VamtProductKey cmdlet but it is returning only status from DB not online refresh status as reported by bob-lockwood. Thx.
