### ISSUE TITLE
Duplicated documentation

### ISSUE THREAD

**Issue by zburtondbrs** [MicrosoftDocs/windows-itpro-docs#2751]
Why do you have both this page and https://docs.microsoft.com/en-us/windows/configuration/ue-v/uev-for-windows? Which is the source of truth?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e116fb5-cce0-33ad-b68c-6d3dced6a8e0
* Version Independent ID: c3e211c5-09d1-f868-1bd5-c6bd4abfbb15
* Content: [Microsoft User Experience Virtualization (UE-V) 2.x](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/uev-v2/)
* Content Source: [mdop/uev-v2/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/uev-v2/index.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by jdeckerms** [comment]
@zburtondbrs The version in the mdop library is for Windows 10, version 1607 and earlier, plus all earlier editions of Windows. It's older documentation that is retained for customers who haven't upgraded yet. The version in the Windows library is the newer content. Thanks for pointing out that it's very hard to figure that out by just looking at the docs. I'll figure out a way to make that clearer.
