### ISSUE TITLE
"Add or vote on suggestions on the User Experience Virtualization feedback site."

### ISSUE THREAD

**Issue by zburtondbrs** [MicrosoftDocs/windows-itpro-docs#2753]
UEV uservoice link (http://uev.uservoice.com/forums/280428-microsoft-user-experience-virtualization) is broken on this page and presumably every page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f735c74e-f4aa-9839-81fe-050782e09e22
* Version Independent ID: 94ceabf5-70ec-8a81-6eee-8f9aa2671ad6
* Content: [Get Started with UE-V](https://docs.microsoft.com/en-us/windows/configuration/ue-v/uev-getting-started)
* Content Source: [windows/configuration/ue-v/uev-getting-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/ue-v/uev-getting-started.md)
* Product: **w10**
* GitHub Login: @MaggiePucciEvans
* Microsoft Alias: **jdecker**

**Comment by mypil** [comment]
@AndreaBarr - please assign this issue to me. Thanks.

**Comment by mypil** [comment]
@MaggiePucciEvans - There is an Error: 404 -"This UserVoice instance is no longer available" when accessing the link for [User Experience Virtualization feedback site](http://uev.uservoice.com/forums/280428-microsoft-user-experience-virtualization).
Can you please advise on how this can be fixed? 

Thank you.

**Comment by mypil** [comment]
@MaggiePucciEvans - I would like to follow up on this issue. Do you happen to know the correct URL for the source article? Please advise so we can create a PR to get this fixed. Thank you.

**Comment by jdeckerms** [comment]
I'm removing the broken uservoice link.

**Comment by mypil** [comment]
@zburtondbrs - Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by AndreaBarr** [comment]
Testing: @officedocsbot re-open

**Comment by AndreaBarr** [comment]
@officedocsbot reopen

**Comment by yogkumgit** [comment]
@officedocsbot reopen

**Comment by yogkumgit** [comment]
@officedocsbot re-open

**Comment by yogkumgit** [comment]
@officedocsbot open

**Comment by illfated** [comment]
I don't know much about @officedocsbot , but maybe the issue needs to be assigned to a team member before **officedocsbot** will reopen the ticket?

**Comment by yogkumgit** [comment]
@officedocsbot open issue

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@officedocsbot open

**Comment by illfated** [comment]
@mypil Joyce, could you check if officedocsbot will respond to requests from you?

**Comment by mypil** [comment]
@officedocsbot reopen

**Comment by mypil** [comment]
@illfated - it does not work for me as well.. ☹️

**Comment by illfated** [comment]
Fair enough, the relevant user should be asked to open a new issue ticket if something like this happens again (or a forced re-open by a team member with ticket handling access, if needs be).
