### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Izaak99** [MicrosoftDocs/windows-itpro-docs#2756]
Clearly this is not working.  Refer to https://community.spiceworks.com/topic/2005761-1703-wsus-restart-reminder-options-group-policy or any other forum reporting these problems.  Also in this article the phrase "You can only choose one path for restart behavior." is extremely vague.  Which paths are you referring to here??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184809a-63ff-ecc2-ab67-9c9f4df900f8
* Version Independent ID: ac25ee6c-4c57-58b3-1313-e4a53f53c5a1
* Content: [Manage device restarts after updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-restart?f=255&MSPPError=-2147217396)
* Content Source: [windows/deployment/update/waas-restart.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-restart.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by Izaak99** [comment]
Even worse, same policy being applied to both Win versions.  1803 = "We'll show a reminder when we're going to restart.  If you want to see more notifications about restarting, turn this on." is not greyed out and can be toggled on or off.  1809 = "Show a notification when your PC requires a restart to finish updating" is greyed out and disabled.  Nothing in GPO has been able to reenable it.

**Comment by e0i** [comment]
@jaimeo Any updates with this issue? We would like to follow up and provide assistance if necessary. Thanks.

**Comment by MCPWiz** [comment]
As far as I can understand the text above, there are 3 times when a restart can still happen dispite No restart with logged on user:

1 No auto-restart with logged on users for scheduled automatic updates installations prevents automatic restart when a user is signed in. If a user schedules the restart in the update notification, the device will restart at the time the user specifies even if a user is signed in at the time. This policy only applies when Configure Automatic Updates is set to option 4-Auto download and schedule the install.

2 
Note

When using Remote Desktop Protocol connections, only active RDP sessions are considered as logged on users. Devices that do not have locally logged on users, or active RDP sessions, will be restarted.

3
You can also use Registry, to prevent automatic restarts when a user is signed in. Under HKLM\Software\Policies\Microsoft\Windows\WindowsUpdate\AU, set AuOptions to 4 and enable NoAutoRebootWithLoggedOnUsers. As with Group Policy, if a user schedules the restart in the update notification, it will override this setting.

**Comment by RAJU2529** [comment]
@lzzak99. I also enabled the same options in GPO.  But my machine already has updates on windows 10 v1903 64bit build no 18362.175.
I have to wait until the next update, for testing.
I keep monitoring this issue

**Comment by e0i** [comment]
Hello, @Izaak99 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
