### ISSUE TITLE
SSU, LCU with offline WIM

### ISSUE THREAD

**Issue by russbearl** [MicrosoftDocs/windows-itpro-docs#2758]
@jaimeo - I've read that the recommendation is to install SSUs before installing LCUs. 
Can we do something like the following using DISM with an offline WIM?
1. Mount WIM
2. Add SSU
3. Add LCU
4. Unmount/save WIM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b706f0af-d504-a8ca-7c38-b8bb9283bfad
* Version Independent ID: 14f31acf-9f47-59a6-269f-62ab249fe560
* Content: [Servicing stack updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates)
* Content Source: [windows/deployment/update/servicing-stack-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/servicing-stack-updates.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mypil** [comment]
@russbearl - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot close
