### ISSUE TITLE
Link to the OMA website is broken

### ISSUE THREAD

**Issue by vlad-MSFT** [MicrosoftDocs/windows-itpro-docs#2759]
Something like this should be used: http://www.openmobilealliance.org/wp/overviews/dm_overview.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de30f8b-0039-3cb5-0b38-8064d8fb2a3a
* Version Independent ID: f2968413-2951-5c42-dd5a-2a0b974338ca
* Content: [OMA DM protocol support](https://docs.microsoft.com/en-us/windows/client-management/mdm/oma-dm-protocol-support#oma-dm-standards)
* Content Source: [windows/client-management/mdm/oma-dm-protocol-support.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/oma-dm-protocol-support.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by illfated** [comment]
Good point. I wonder if what has been holding up that change is A) lack of correct URL suggestion, or B) too busy technicians handing out new `fwlink` IDs for the shortcut URL to go.microsoft.com (current link = https://go.microsoft.com/fwlink/p/?LinkId=267526). I could open a PR using your suggested working URL above, although I don't know who or where those `fwlink` IDs are handed out. It is not as easy to find as other sites like those created for use on twitter and social media.

BTW, same issue as [**Dead link found**](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2362) #2362 - but now with a suggested solution.
I can open a Pull Request with your suggestion, then see what the Doc team says.

**Comment by illfated** [comment]
Oh. I see. That page needs even more review and updating.
We actually need to update links to point to the documents, like
http://www.openmobilealliance.org/release/DM/V1_1_2-20031209-A/OMA-SyncML-DMRepPro-V1_1_2-20030613-A.pdf
... based on the `oma-dm-protocol-support.md` file content and reference
> see "SyncML Representation Protocol Device Management Usage (OMA-SyncML-DMRepPro-V1_1_2-20030613-A)"

**Comment by illfated** [comment]
Hmm, there are several versions and release Candidates in subfolders (A - Approved, C - Candidate, H - Historic).
See also http://www.openmobilealliance.org/release/DM/README.txt

I wonder if we should use the latest available document of its kind,
or if it is required to use the same document as the reference dates in the MS document page
(https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/oma-dm-protocol-support.md).

**Comment by vlad-MSFT** [comment]
Thanks for looking into this! Really impressed with the quick turnaround time AND on weekend! Well done!

**Comment by illfated** [comment]
😃 Thank you for the nice words.
Please note that I am not employed by Microsoft, I am doing this in my spare time.
