### ISSUE TITLE
-2016281112 (Remediation failed)

### ISSUE THREAD

**Issue by dzejzipl** [MicrosoftDocs/windows-itpro-docs#2760]
It's still this same issue.
I have Windows 10 Pro 1809 joined to Azure AD with deployed policy to create Local account.
It's working fine - account is created successful, but... On Intune I have still this same error: 	
-2016281112 (Remediation failed)
Is there any fix for that? I can provide logs for Engineers ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 309bae29-c769-5051-6c3f-aebeb455cd34
* Version Independent ID: bbdfad82-025e-8aee-b3fc-bcfb8b110674
* Content: [Accounts CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/accounts-csp)
* Content Source: [windows/client-management/mdm/accounts-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/accounts-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@dzejzipl - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
