### ISSUE TITLE
Showing **注: ** (Markdown notation)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#2761]
https://docs.microsoft.com/ja-jp/windows/deployment/update/waas-restart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184809a-63ff-ecc2-ab67-9c9f4df900f8
* Version Independent ID: ac25ee6c-4c57-58b3-1313-e4a53f53c5a1
* Content: [Manage device restarts after updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-restart)
* Content Source: [windows/deployment/update/waas-restart.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-restart.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by illfated** [comment]
I think you need to provide more details, if you want the Documentation team to answer your question.
(I have difficulties trying to understand what the question is. Not sure if it helps to read & speak Japanese.)

**Comment by hyoshioka0128** [comment]
English: https://docs.microsoft.com/en-us/windows/deployment/update/waas-restart
![waas-restart_en](https://user-images.githubusercontent.com/40815708/53300302-b252f680-3888-11e9-89fd-0af8daab7802.png)

Japanese: https://docs.microsoft.com/ja-jp/windows/deployment/update/waas-restart
![waas-restart_ja](https://user-images.githubusercontent.com/40815708/53300309-cac31100-3888-11e9-9106-761d6770641c.png)

**Comment by illfated** [comment]
OK, very well. If I understand it correctly, it looks like there should be proper code for **Bold Text** there instead of just `**注:**` to highlight the kanji character for "**Note:**".

I will have a look and see what can be done about the ja-jp page (I have yet to try finding the non-English pages in this repository to open a Pull Request for one of those).

**Comment by illfated** [comment]
Oh, right. I think I know what is wrong there.
```
**注: **無効に設定した場合、インストールを完了するためにコンピューターが 5 分以内に自動的に再起動されることがユーザーに通知されます。
```
The Japanese text source (`waas-restart.md`) does not have a space after the MarkDown asterisks,
but instead appears to have the space in front of the second pair of asterisks.
In MarkDown, the space character (and the placing of the space character) is important
in order for the formatted text to be shown correctly.

Therefore, the characters between the asterisks do not get the formatting code **Bold** assigned to them.
If I could have access to the Japanese text source, I could easily open a Pull Request to rectify this error.

**Comment by DaniHalfin** [comment]
Hi @hyoshioka0128 and @illfated, 
Thanks for reaching out.
Our localized content doesn't offer the ability to directly contirubte, however, I will pass this feedback along to the localization team. We appreciate you taking the time to point it out.
Can't tell when exactly we'll get it through to the live version, but we'll start working on it as soon as possible.
