### ISSUE TITLE
Win 10 pro is awesome.

### ISSUE THREAD

**Issue by Bormon007** [MicrosoftDocs/windows-itpro-docs#2764]
Widows 10 is perfect for work .Its fell vary sa to tell my free trial laicence out of date.i need more days for compleat my study,
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6957383-3bd9-eef9-6410-9c42f8a0b172
* Version Independent ID: a2090374-0fd1-8d67-66de-30c4cf2835f7
* Content: [Overview of Windows as a service (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-overview#servicing-tools)
* Content Source: [windows/deployment/update/waas-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-overview.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mypil** [comment]
@Bormon007 - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
