### ISSUE TITLE
Brightness Service vs Intel DPST adaptive brightness?

### ISSUE THREAD

**Issue by danchar4** [MicrosoftDocs/windows-itpro-docs#2765]
Is the Microsoft Brightness Control service intended to replace/bypass the Display Power Saving Technology (DPST) built into the Intel HD Graphics GPU drivers? Many customers complain about flickering on Book, Pro, and Go models related to Intel's adaptive brightness not having suitable parameters for the hysteresis model.

It would be great to know the intent of this service and whether it is designed to work with the Intel service or replace it.

Also what is the intended effect of manully setting the brightness via control panel or settings while this service is running? For example if the registry is set to 100%, but I manually set brightness to 50%, what is the intended outcome? For me, brightness snaps back to 100%. Is this intentional?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ac6c100-6e19-4cf6-2fd1-558a6751cc5d
* Version Independent ID: eec13586-5975-9ada-ec0f-9f53654eb73b
* Content: [Surface Brightness Control](https://docs.microsoft.com/en-us/surface/microsoft-surface-brightness-control)
* Content Source: [devices/surface/microsoft-surface-brightness-control.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/microsoft-surface-brightness-control.md)
* Product: **w10**
* GitHub Login: @CoveMiner
* Microsoft Alias: **jdecker**

**Comment by mypil** [comment]
@danchar4 - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
