### ISSUE TITLE
Does not work on Windows 10 as of 2/24/2019

### ISSUE THREAD

**Issue by CleverCoder** [MicrosoftDocs/windows-itpro-docs#2767]
I get "Access Denied" as an Administrator, even with UAC off, and using both methods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f6a1129-315e-8e98-e7f7-5eb85fb6f12c
* Version Independent ID: e6f2dc33-383c-afe0-08bd-8aa1c9d39fef
* Content: [Configure the Application Identity service (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/configure-the-application-identity-service)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/applocker/configure-the-application-identity-service.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/applocker/configure-the-application-identity-service.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@CleverCoder PowerShell option is working for me, I'm running Windows 10 version 1903 (beta). I ran in an elevated PS window:

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\WINDOWS\system32> sc.exe config appidsvc start= auto
[SC] ChangeServiceConfig SUCCESS
PS C:\WINDOWS\system32>

**Comment by CleverCoder** [comment]
You are correct. Setting start to "auto" worked as you indicated. I was attempting to disable the service:

```
C:\WINDOWS\system32>sc config appidsvc start= disabled
[SC] ChangeServiceConfig FAILED 5:

Access is denied.

```
Seeing as how I use no Windows 10 store apps, I wanted to lighten the runtime footprint, even though I'm sure some would say "why bother? This thing doesn't take up many resources!"

Cheers!
