### ISSUE TITLE
customer issue: script is incorrect

### ISSUE THREAD

**Issue by zjalexander** [MicrosoftDocs/windows-itpro-docs#277]
I recieved customer feedback on the following: 
>I am turning a windows 10 instance into a Kiosk, and for some reason this line fails. The code was taken from a Technet article explaining how to put windows 10 into a KIOSK mode using the Shell Launcher feature and specifying a custom shell  
$ShellLauncherClass.SetCustomShell($shell_SID, "C:\Program Files (x86)\...\xxx.exe”) ($null), ($null), ($Restart_shell)
the $restart shell is just a variable with a value of 0. for some reason the line does not like the parens with the null. the script fails at this point unless I remove the nulls.

>The article is at https://docs.microsoft.com/en-us/windows/configuration/set-up-a-kiosk-for-windows-10-for-desktop-editions#shell-launcher 
The code is in the section for setting up the shell launcher for classic mode. It is the lines to set the shell for the user account that gets the Classic launcher mode.

**Comment by jdeckerms** [comment]
I'm not a PowerShell expert, I'm just comparing the sample script to what you have. In the sample, there's a comma after the .exe, and no paren before $Restart_shell.
