### ISSUE TITLE
Availability of Windows 10 Team edition

### ISSUE THREAD

**Issue by c016smith** [MicrosoftDocs/windows-itpro-docs#2772]
Is the use of Windows 10 Team available in any other product other than Surface Hub? Is this something that can be bought and licensed with other large-screen devices and loaded similarly to Surface Hub user experience, such as with a Windows Collaboration Display? The use of the custom Team "Shell" is essential to the user experience of Surface Hubs but could be instrumental in extending access to other devices that need a consistent configuration, use of Welcome Screen/End Session, and a tightly configured user experience.  

Can you provide any further information on the availability of Windows 10 Team edition, if that can be purchased and licensed independently, or if OEMs have this availabiliy in specific hardware cases or if we can enable this feature set on specific devices by configuration only, such as on a Surface Studio or Surface Pro, or any other licensed Windows 10 Enteprise PC that is connected to a large display with touch/pen capabilities? 

I thought this was what the Windows Collaboration Device (WCD) standard was aiming for, but it appears it's just the screen and still needs a PC to be the brains. I'm hoping we can get the 'brains' loaded up and running this Windows 10 Team edition as the base configuration without Surface Hub being the _only_ way to achieve that. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 324027ab-8e1b-045f-5904-e9e6c54e17d3
* Version Independent ID: 3a0b2c99-c013-867f-5517-89cc7cee451d
* Content: [Differences between Surface Hub and Windows 10 Enterprise](https://docs.microsoft.com/en-us/surface-hub/differences-between-surface-hub-and-windows-10-enterprise)
* Content Source: [devices/surface-hub/differences-between-surface-hub-and-windows-10-enterprise.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/differences-between-surface-hub-and-windows-10-enterprise.md)
* Product: **surface-hub**
* GitHub Login: @isaiahng
* Microsoft Alias: **jdecker**

**Comment by c016smith** [comment]
Pinging on this question again, is someone at Microsoft actively developing this Team "shell" and is it something that will be made available to OEMs or individual IT departments to provide this kiosk-level experience for non-SurfaceHub devices?

**Comment by jdeckerms** [comment]
@c016smith Sorry, I can't answer questions about possible future developments or releases. Windows 10 Team is currently available on Surface Hub only.
