### ISSUE TITLE
Sign-in Questions

### ISSUE THREAD

**Issue by anujgoyal** [MicrosoftDocs/windows-itpro-docs#2775]
"When an Internet-connected Windows 10 device boots up, it will attempt to connect to the Autopilot service and download an Autopilot profile.... with Azure Active Directory sign-in"

1. Is the Autopilot service part of InTune? or a separate service?
2. Can another Credential Provider be added to the default system image for AutoPilot and given to the OEM?
3. Does Windows Autopilot support an OOBE with another Credential Provider?

**Comment by illfated** [comment]
Looks like you are referencing the MS Document
https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/profiles

One of the MS Doc team members will comment at a later time to inform you if this is something they can answer,
or whether you need to direct your questions to any of the other Microsoft resources.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@anujgoyal - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
