### ISSUE TITLE
Recommended App "Recommended-Denied-Office-365-ProPlus-1810.xml"

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/windows-itpro-docs#2778]
What is this application? Do we have to add it to our WIP policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df27add-73fe-4f0b-7e30-face0f95cda3
* Version Independent ID: 3ec647d9-3470-8d8b-a941-d56f6522a35e
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@Martony78 The Office engineering team recommended that Intune add that app to the recommended list. It denies older versions of Office and other unenlightened Office apps from getting even accidentally allowed through some other rule, as they could cause app compat problems and over-encrypt data if allowed.
