### ISSUE TITLE
Update Installed Windows apps for 1809

### ISSUE THREAD

**Issue by hoskinsm** [MicrosoftDocs/windows-itpro-docs#2779]
Can this reference be updated to include Installed Windows apps for 1809

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce0131fb-6b3a-5905-1738-253cf37e3b2d
* Version Independent ID: cab448be-54ae-539e-22ba-3d202a468d4f
* Content: [Windows 10 - Apps](https://docs.microsoft.com/en-us/windows/application-management/apps-in-windows-10)
* Content Source: [windows/application-management/apps-in-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/apps-in-windows-10.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Fair request, I would expect no less of any documentation for actively developed software for professionals.

**Comment by mypil** [comment]
@AndreaBarr - please assign this issue to me. Thank you.

**Comment by mypil** [comment]
@hoskinsm - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by Jcoetsee** [comment]
@lizap Can you possibly elaborate on this and confirm what the pre-installed apps are under update 1809 as I can see that field is not populated with 1809 and don't want to assume that it's the same as previous update. based on a quick review it does appear to be somewhat different.

**Comment by mypil** [comment]
@lizap - We would like to follow up on this issue. Can you please share your insights? Thanks.

**Comment by kenwith** [comment]
@Jcoetsee - can you research and come up with a Pull Request?

**Comment by Jcoetsee** [comment]
The content on the page has been updated.

**Comment by mypil** [comment]
@hoskinsm - the content has been updated to add the information that you requested for. Kindly check and let us know if your issue has been resolved. Thank you.

**Comment by hoskinsm** [comment]
Thank you for the update.

Should there also be reference to which Windows 10 sku's (Enterprise, Pro, Education, etc)  this article applies.

It is our understanding that depending  on which sku you are deploying, there are at least differences with regard to the Installed Windows Apps?  We only use Enterprise but there may be others viewing this article which deploy Professional or Education.

For example, we are working with a vendor who deploys both Pro and Enterprise for the testing and validation.  They have advised, on their Pro instances, the Microsoft.NET.Native.Framework.1.3 and the Microsoft.NET.Native.Runtime.1.4 are both included in the default Pro build.  Meanwhile as this article indicates, these are not included in the Enterprise build, which we discovered while working with our vendor.  This is just one example where it seems there are differences to be outlined between the sku's as well.
 
Since this article does not specifically call out which sku for which the information applies to, one would make the assumption of Enterprise.

thank you

**Comment by lizap** [comment]
@hoskinsm - the article addresses the Windows 10 Enterprise SKU, which is called out here: "The following tables list the system apps, installed Windows apps, and provisioned Windows apps in a standard Windows 10 Enterprise installation."  Thanks!

**Comment by hoskinsm** [comment]
@lizap - my apologies, you are correct, I did not catch that line... have gotten so use to seeing the "Applies To: " section at the bottom of KB articles over the years, I was looking at the end of the article rather than within the body of article.  Thank you!

**Comment by hoskinsm** [comment]
@lizap 
Hello again, is an update to this document in the works for Windows 10 Enterprise 1903?
Thank you
