### ISSUE TITLE
Fall back to direct when proxy not accessible

### ISSUE THREAD

**Issue by phillym** [MicrosoftDocs/windows-itpro-docs#2784]
Hey there! Would be good if you could update your docs to make it explicit that if TelemetryProxyServer is set (in reg or via GPO) that WDATP will fall-back to direct if it can't access the defined proxy. This is good by the way but good to documented too :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83207fc9-2c91-eb07-4237-6bb1f42e3778
* Version Independent ID: 5db33cf3-2dcb-bb33-a252-3a13ca9737f9
* Content: [Configure machine proxy and Internet connection settings](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-proxy-internet-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/configure-proxy-internet-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/configure-proxy-internet-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@AndreaBarr - please assign this issue to me. Thank you.

**Comment by nenonix** [comment]
@phillym I have added a note. I hope that resolves the issue. Thank you for your helpful contribution.
