### ISSUE TITLE
perhaps "SSTP" is missing?

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/windows-itpro-docs#2787]
VPNv2/ProfileName/NativeProfile/NativeProtocolType doesn't list SSTP as a possible value. is it missing from the doc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8b1b81d-3c35-0315-d149-f10af3a409b2
* Version Independent ID: c34e7acb-ece7-d76f-fb41-470e19119ee0
* Content: [VPNv2 CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp)
* Content Source: [windows/client-management/mdm/vpnv2-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/vpnv2-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by illfated** [comment]
I don't know this material, so I am going out on a limb here:
Maybe it is or will be classified as belonging to one of the SSL-VPN plug-in configurations?

**Comment by sasanmcp** [comment]
No I don’t think so. SSTP is native to Windows. It should have been mentioned here.

**Comment by illfated** [comment]
Very well, I bow to your knowledge. If someone could suggest a fitting description to be inserted into the documentation, I would be happy to open a Pull Request to have that part of the documentation improved.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
@sasanmcp SSTP is supported by Desktop versions only and can not be configured using MDM. Please see the following doc (https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-connection-type)
Thanks.

**Comment by sasanmcp** [comment]
Huh! That’s weird. Out of 4 protocols supported you can pick any of the other 3 in your CSP configuration but not this one! Something PG has to address, in my opinion.

They also need to put the feature there in the CSP to let the admin define the Order through which Automatic config will try the protocols. CMAK already has it.

**Comment by illfated** [comment]
@sasanmcp : It looks like your question has been answered.
Moreover, your feedback regarding suggested changes fits better
as a request to the Windows Feedback hub or the Forum pages.
This site is dedicated to improving the Docs.

Will it be OK to close this issue ticket now?

**Comment by sasanmcp** [comment]
Go ahead.

**Comment by illfated** [comment]
@officedocsbot Close

**Comment by mypil** [comment]
@officedocsbot close
