### ISSUE TITLE
the correct order through which protocols are tried?

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/windows-itpro-docs#2788]
VPNv2/ProfileName/NativeProfile/NativeProtocolType doesn't mention what would the order be if it is set to Automatic. will it be ikev2 then sstp then l2tp then pptp or pptp first or what?

also, is there a way to customize this order as you can in CMAK?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8b1b81d-3c35-0315-d149-f10af3a409b2
* Version Independent ID: c34e7acb-ece7-d76f-fb41-470e19119ee0
* Content: [VPNv2 CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp)
* Content Source: [windows/client-management/mdm/vpnv2-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/vpnv2-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@AndreaBarr - please assign this issue to me. Thank you.

**Comment by mypil** [comment]
@sasanmcp - Thank you for this inquiry.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.

**Comment by mypil** [comment]
@sasanmcp - From our understanding the issue you raised has been answered. If you feel it hasn't been answered please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
