### ISSUE TITLE
Win32 Apps

### ISSUE THREAD

**Issue by mr-fujnz** [MicrosoftDocs/windows-itpro-docs#2794]
Does the ESP support tracking 'Windows app (Win32)' applications? If not, is that on the roadmap?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5d94e38-75da-740c-d0cc-82bf27ba9c24
* Version Independent ID: 800a29d5-425c-7c32-b901-c425658ada81
* Content: [Windows Autopilot Enrollment Status page](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/enrollment-status)
* Content Source: [windows/deployment/windows-autopilot/enrollment-status.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/enrollment-status.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
@mr-fujnz As of now Autopilot doesn't support Win32 bit applications. As of now there is no update regarding this but as soon as it will be available, you will get an update on autopilot enrollment status page. Thanks.

**Comment by mypil** [comment]
@mr-fujnz - From our understanding, the issue has been answered by joinimran. 

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
