### ISSUE TITLE
Autopilot Bitlocker doesn't work on some models with supported hardware

### ISSUE THREAD

**Issue by TechTrooper** [MicrosoftDocs/windows-itpro-docs#2795]
We are having issues enabling Bitlocker on some Lenovo ThinkPad devices with the method described in this article.

This seems to be purely Intune / Autopilot issue as the devices can be encrypted normally with SCCM task sequences.

Some models tested:
ThinkPad T480s (20L8S11A00) Windows Autopilot Bitlocker doesn't start at all.
ThinkPad T460s will encrypt automatically.

It's not a good experience for us, if some models randomly won't work.
We'll have to consider deploying powershell scripts to get Bitlocker working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f28f994-ad0f-72e5-79d2-6898421cb2fd
* Version Independent ID: dbb83bbb-73cc-8233-15fb-1363b8ad1cd1
* Content: [Setting the BitLocker encryption algorithm for Autopilot devices](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/bitlocker)
* Content Source: [windows/deployment/windows-autopilot/bitlocker.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/bitlocker.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by mypil** [comment]
@TechTrooper - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
