### ISSUE TITLE
Unlisted: 0x80070490

### ISSUE THREAD

**Issue by SnakeMind** [MicrosoftDocs/windows-itpro-docs#2804]
Windows 10 Enterprise 1809, build 17763.316
After updates to this build, the PIN stopped working and gives error 0x80070490 when trying to set it. 
Machine is not connected to a domain, but after clicking "skip" another error appears stating the PIN will not work with sources in my organisation, even though it isn't connected to an organisation.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/nl-nl/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
Hi @SnakeMind and thanks for reaching out.
If your code isn't currently likely, it is most likely that the error is transient (which means we'll need more information to figure out what's going wrong).
Please file a problem through the [feedback hub app](feedback-hub:?contextid=3&tabid=2&newFeedback=true&feedbackType=2), which will allow you to send us the appropriate diagnostic logs (automatically collected). Make sure to select "Security and Privacy > Windows Hello PIN".
We are constantly looking at additional error codes we can add to this topic to help people troubleshoot PIN issues, so we appreciate you taking the time to report this issue.

I'll proceed to close the issue, but feel free to comment back.

**Comment by SnakeMind** [comment]
Sure, thanks, I'll do that now :)

**Comment by gillllllllll** [comment]
hi, i'm getting 0x80070490 also on my laptop.

**Comment by colemoine** [comment]
any idea what error 0x80070490 was, I'm also having this issue with Windows Hello?

**Comment by KaeptnHelmut** [comment]
Same problem here, is there any solution yet?

**Comment by sholek1** [comment]
Same issue with 0x80070490.  Going on for a couple of months.  MS support could not resolve.  I will provide any input I can for resolution.

**Comment by gillllllllll** [comment]
> Same issue with 0x80070490. Going on for a couple of months. MS support could not resolve. I will provide any input I can for resolution.

since it was an insider build, i had reinstalled windows, but on the new installation i hadn't joined the laptop to the on prem domain, but only to the azure ad domain. and anything worked ok.
