### ISSUE TITLE
404 - Page not found for "Windows Defender System Guard link"

### ISSUE THREAD

**Issue by Sherd21** [MicrosoftDocs/windows-itpro-docs#2813]
"Windows Defender System Guard" link is broken. Not sure where it should lead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f9f33e1-4a3d-0754-f8f7-ba9c9ef06170
* Version Independent ID: 9151513b-d9fa-6e1e-3a8c-7a02775ddb83
* Content: [Hardware-based isolation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/overview-hardware-based-isolation#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-atp/overview-hardware-based-isolation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/overview-hardware-based-isolation.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Sherd21** [comment]
Actually, i think i found a correct link: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-system-guard/how-hardware-based-root-of-trust-helps-protect-windows

**Comment by illfated** [comment]
Good job finding it. I tried searching for "Windows Defender System Guard", but I almost exclusively got search results for "Windows Defender Application Guard" and "Windows Defender Credential Guard".

**Comment by illfated** [comment]
BTW, I am planning a Pull Request to add this link correction later, something like 10-12 hours from now.

**Comment by illfated** [comment]
By the way, just to point out how the link does not work: the file named in the link 
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/how-hardware-based-containers-help-protect-windows.md
does not exist (so the 404 page is entirely correct).
The link indicates that the file `how-hardware-based-containers-help-protect-windows.md` is supposed to exist in the directory
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/ (but it does not).

**Comment by illfated** [comment]
Just a final comparison before pushing the PR changes to Github:
1. Path to the page containing the broken link:
```
../threat-protection/windows-defender-atp/overview-hardware-based-isolation.md
```
2. Path to the non-existing page:
```
../threat-protection/windows-defender-atp/how-hardware-based-containers-help-protect-windows.md
```
3. Path to the suggested (and most likely) existing page to be used as the link target:
```
../threat-protection/windows-defender-system-guard/how-hardware-based-root-of-trust-helps-protect-windows.md
```

**Comment by Justinha** [comment]
@illfated Thanks Trond. I want to improve the discoverability of this topic too, so it comes up better in search results. To that end, I've added keywords "system guard" to the topic description and I changed the file name to system-guard-how-hardware-based-root-of-trust-helps-protect-windows.md in the path you suggested:

../threat-protection/windows-defender-system-guard/system-guard-how-hardware-based-root-of-trust-helps-protect-windows.md

I submitted the pull request today and it should appear for you in a few hours. 

and thanks @Sherd21 for reporting this.

**Comment by Justinha** [comment]
@illfated I meant to add, my pull request was internal, I can't link to it from here.

**Comment by illfated** [comment]
Oh, OK, I see. I was preparing to amend my PR with your new information.

**Comment by Justinha** [comment]
You can, and we will merge it. There should be no conflict now that you know what I changed on my side. And you will be added as a contributor, which we want.

**Comment by illfated** [comment]
Very well. I notice that the page has not yet changed its name here on Github, but I presume it will do so, soon enough.
So the new file name is going to be `system-guard-how-hardware-based-root-of-trust-helps-protect-windows.md` in the same folder.

**Comment by Justinha** [comment]
you got it. ETA is about 2 hours,
