### ISSUE TITLE
Incorrect value for "Set sourcetype"

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#2826]
The value for **Set sourcetype** is listed as **From list** in the documentation. The actual downloaded file has it set to **Manual** so the page should be updated to Manual as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce7d6f5f-8a56-d5de-8105-637f19b2de6f
* Version Independent ID: 27e10f91-9cff-e044-a474-ce558e74b099
* Content: [Configure Splunk to pull Windows Defender ATP alerts](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-splunk-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/configure-splunk-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/configure-splunk-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@AndreaBarr - please assign this issue to me. Thank you.

**Comment by mypil** [comment]
@iadgovuser1 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by nenonix** [comment]
@iadgovuser1  Thanks for the feedback. Just to be clear, the value for "set sourcetype" should be "Manual" and not "From list"?

**Comment by iadgovuser1** [comment]
Correct. Here's a snippet from the file that gets downloaded from WDSC:

`"Response Type":"Json","Response Handler":"JSONArrayHandler","Polling Interval":60,"Set sourcetype":"Manual","Source type":"_json"}`
