### ISSUE TITLE
Developer Specifications

### ISSUE THREAD

**Issue by brink668** [MicrosoftDocs/windows-itpro-docs#2827]
Do you have a link to the developer specifications for RSAM for programming/developers? I am unable to find it unless this is all I need to send to our team.  Thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef8b6967-0e45-bcdd-6d70-54759d9f7ec8
* Version Independent ID: 6651ebc1-04f0-421f-891b-6957ca37da7c
* Content: [Network access - Restrict clients allowed to make remote calls to SAM](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@brink668 Unfortunately we have no other docs for this setting. You can start with this topic but the complexity of this setting requires expert help. I strongly recommend speaking with Microsoft support for this setting.

**Comment by mypil** [comment]
@officedocsbot close
