### ISSUE TITLE
Version 1.4.0

### ISSUE THREAD

**Issue by g4m3c4ck** [MicrosoftDocs/windows-itpro-docs#2834]
Fails to run and throws exception below:

1:12:58 - SetupDiag: Main() failed with an unhandled exception:
Value cannot be null.
Parameter name: name
Exception System.ArgumentNullException: Value cannot be null.
Parameter name: name
Source: mscorlib
Stack:    at System.Environment.ExpandEnvironmentVariables(String name)
   at Microsoft.Internal.Deployment.SetupDiag.CSetupDiag.FindParseLatestSetupLogs(SetupDiagParameters setupDiagParams)
   at Microsoft.Internal.Deployment.SetupDiag.CSetupDiag.RunDiag(String strRulesFile, String strlogsPath, String strMode, String strOutPut, String strFormat, String resLevel, Boolean fCreateLogs, Boolean fSendTelemetry, String strScenario, Boolean fAddRegInfo, Boolean isPipelineMode)
   at Microsoft.Internal.Deployment.SetupDiag.Program.Main(String[] args)

Wrong version of debugging tools installed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ad81361-15d8-0e95-9d5f-090dbf270f10
* Version Independent ID: c0c32397-d5d6-cce1-79fd-c310bec05240
* Content: [SetupDiag](https://docs.microsoft.com/en-us/windows/deployment/upgrade/setupdiag#feedback)
* Content Source: [windows/deployment/upgrade/setupdiag.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/setupdiag.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@g4m3c4ck - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot close

**Comment by g4m3c4ck** [comment]
I would have engaged with support if version 1.3.1.0 did not work without issue. But it still works fine. I should not have to have a premier support account to resolve this problem.

**Comment by JLMontignie** [comment]
CSetupDiag.FindParseLatestSetupLogs().
1:36:31 - SetupDiag: Main() failed with an unhandled exception:
La valeur ne peut pas être null.
Nom du paramètre : name
Exception System.ArgumentNullException: La valeur ne peut pas être null.
Nom du paramètre : name
Source: mscorlib
Stack:    à System.Environment.ExpandEnvironmentVariables(String name)
   à Microsoft.Internal.Deployment.SetupDiag.CSetupDiag.FindParseLatestSetupLogs(SetupDiagParameters setupDiagParams)
   à Microsoft.Internal.Deployment.SetupDiag.CSetupDiag.RunDiag(String strRulesFile, String strlogsPath, String strMode, String strOutPut, String strFormat, String resLevel, Boolean fCreateLogs, Boolean fSendTelemetry, String strScenario, Boolean fAddRegInfo, Boolean isPipelineMode)
   à Microsoft.Internal.Deployment.SetupDiag.Program.Main(String[] args)


where to find setupdiag v1.3.1?

**Comment by ScottHendrix-MSFT** [comment]
The best way to get help for SetupDiag is to submit Feedback via the Feedback Hub and include the word SetupDiag in the title.

This should be fixed in 1.6.0, let me know if it's not.
