### ISSUE TITLE
Unable to deploy from Intune

### ISSUE THREAD

**Issue by Geckojas** [MicrosoftDocs/windows-itpro-docs#2836]
Hi, I'm trying to install this via configuration profile from intune, and it says that although the application guard policy has applied, none of the other parts have. When I look on the machine (a Surface Pro 6), application guard does not install, despite several reboots. Even when I install it manually, none of the settings from Intune are taking. Please could we have a bit more information on how to troubleshoot this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb904674-d586-0a38-0e7c-7ac3e06cbcd9
* Version Independent ID: 549fbb52-6234-2a79-8604-85498e622f98
* Content: [Enable hardware-based isolation for Microsoft Edge (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/install-wd-app-guard)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/install-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/install-wd-app-guard.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@Geckojas - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
