### ISSUE TITLE
How to auth device when using certificate authentication?

### ISSUE THREAD

**Issue by jianggaocheng** [MicrosoftDocs/windows-itpro-docs#2843]
I have some question about certificate authentication:
1. Does certificate authentication only support enroll with ppkg file?
2. How to auth device? using 2-way ssl?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e4195fd-1278-2250-3645-bfb9f9d1cf82
* Version Independent ID: a1cb9c2f-1bec-1c45-94cb-788efe7202f0
* Content: [Certificate authentication device enrollment](https://docs.microsoft.com/en-us/windows/client-management/mdm/certificate-authentication-device-enrollment#feedback)
* Content Source: [windows/client-management/mdm/certificate-authentication-device-enrollment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/certificate-authentication-device-enrollment.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@AndreaBarr - please assign this issue to me. Thank you.

**Comment by mypil** [comment]
@jianggaocheng - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
