### ISSUE TITLE
OneDrive turned unavailable on Setup School PC provisioned devices

### ISSUE THREAD

**Issue by BFreddyLee** [MicrosoftDocs/windows-itpro-docs#2845]
One of my customer reported they provisioned school PCs with this tool and enabled One Drive initially. Device was managed by Intune. After getting windows updates they found OneDrive was disabled. They enabled it manually. However it got disabled again after another update. Is this a known issue?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2ca5807-f011-cdd1-eb80-c74655aa4738
* Version Independent ID: fe016307-69a4-ec63-4979-eac841d13c3c
* Content: [Use Set up School PCs app](https://docs.microsoft.com/en-us/education/windows/use-set-up-school-pcs-app#feedback)
* Content Source: [education/windows/use-set-up-school-pcs-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/use-set-up-school-pcs-app.md)
* Product: **w10**
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by mypil** [comment]
@BFreddyLee - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
