### ISSUE TITLE
How to connect to a VPN with Conditional Access from Command line

### ISSUE THREAD

**Issue by eldos-dl** [MicrosoftDocs/windows-itpro-docs#2847]
Using `rasdial` is raising Remote Access error 798 - A certificate could not be found that can be used with this Extensible Authentication Protocol. But I was able to connect to this VPN through Network Connections Pane

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b6faee7-5e59-c367-075d-5517d3af4f75
* Version Independent ID: e6d377d5-267e-ec54-3769-6d5863ef6936
* Content: [VPN and conditional access (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-conditional-access)
* Content Source: [windows/security/identity-protection/vpn/vpn-conditional-access.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/vpn/vpn-conditional-access.md)
* Product: **w10**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by mypil** [comment]
@eldos-dl - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot close

**Comment by eldos-dl** [comment]
@mypil I have contacted support at the link provided. They were of no help. I have raised a Support Request in Azure Portal. I will update here if get a solution.
