### ISSUE TITLE
What is "the URL encoding standard" for LocURI

### ISSUE THREAD

**Issue by jigargandhi** [MicrosoftDocs/windows-itpro-docs#2848]
If you are referring to specific RFC, please give RFC number

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de30f8b-0039-3cb5-0b38-8064d8fb2a3a
* Version Independent ID: f2968413-2951-5c42-dd5a-2a0b974338ca
* Content: [OMA DM protocol support](https://docs.microsoft.com/en-us/windows/client-management/mdm/oma-dm-protocol-support)
* Content Source: [windows/client-management/mdm/oma-dm-protocol-support.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/oma-dm-protocol-support.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by Malind19** [comment]
@e0i The article specifies the LocURI shall comply with the URL encoding standard, which is a universal thing, not specific to LocURI. So I do not think it is necessary to mention the URL encoding standards in this article.

**Comment by Malind19** [comment]
@jigargandhi , @e0i : Following is an article that explains universal standards for encoding URIs. 

https://tools.ietf.org/html/rfc7595

**Comment by e0i** [comment]
Hello, @jigargandhi  

It seems that your question has been answered and thus we are marking this issue as resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
