### ISSUE TITLE
Link to "roaming user profile guidelines" is broken

### ISSUE THREAD

**Issue by Borkason** [MicrosoftDocs/windows-itpro-docs#285]
Link to "roaming user profile guidelines" is broken: https://github.com/MicrosoftDocs/windows-itpro-docs/blame/master/browsers/internet-explorer/ie11-deploy-guide/browser-cache-changes-and-roaming-profiles.md#L17

**Comment by eross-msft** [comment]
Thank you for pointing this out. Do you have a recommendation for a replacement link?

**Comment by Borkason** [comment]
No, sorry. I don't know what exact guideline the author is referring to.

**Comment by eross-msft** [comment]
Thank you again for responding. I'll do a bit of digging and see if I can figure it out.

**Comment by brianlic-msft** [comment]
@JasonGerend Can you recommend a new target for roaming user profile guidance?

**Comment by JasonGerend** [comment]
Looks like this points to an old Windows Server 2003 topic that’s been archived. I’ll look into it a little.

**Comment by JasonGerend** [comment]
I couldn’t really figure out - the current link is owned by Liz, but points to Windows Server 2003 archived content. I looked around in that pdf but couldn't find an obvious target. Here is the latest guidance that I provide for roaming user profiles: https://technet.microsoft.com/library/jj649079(v=ws.11).aspx

**Comment by brianlic-msft** [comment]
@eross-msft Can you update the FWLink link to point to the link above?
