### ISSUE TITLE
Licensing is out of date

### ISSUE THREAD

**Issue by jambirk** [MicrosoftDocs/windows-itpro-docs#2850]
"Lync Online (Plan 2)" is out of date, there is no longer any such plan by that name.  https://docs.microsoft.com/en-us/SkypeForBusiness/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/skype-room-systems-v2 has a more up to date listing showing plan names and the features available for each plan in Skype for Business Online or Teams. I would generally assume that features available to Surface Hub are similar if not identical.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3f49206-2ef4-9c6d-1d3b-951c1440f1db
* Version Independent ID: 53f586ed-c5fb-1875-b67f-08d206921ec3
* Content: [Create a device account using UI (Surface Hub)](https://docs.microsoft.com/en-us/surface-hub/create-a-device-account-using-office-365)
* Content Source: [devices/surface-hub/create-a-device-account-using-office-365.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/create-a-device-account-using-office-365.md)
* Product: **surface-hub**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jambirk** [comment]
"LyncOnlineConnector" is also out of date as a module name.  see  https://docs.microsoft.com/en-us/skypeforbusiness/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot assign @MaratMussabekov

**Comment by mypil** [comment]
@jambirk - From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by jambirk** [comment]
The change has not yet gone live.

**Comment by mypil** [comment]
@jambirk - I believe the content has been updated to add the changes that you requested for. Kindly check and let us know if your issue has been resolved. Thanks.

**Comment by jambirk** [comment]
Looks good to me.

**Comment by mypil** [comment]
Great to know! I will proceed to close this issue then. 

We appreciate your valuable feedback in helping us improve the docs.

**Comment by mypil** [comment]
@officedocsbot close
