### ISSUE TITLE
Site to Zone Assignment List

### ISSUE THREAD

**Issue by guitarfreak58** [MicrosoftDocs/windows-itpro-docs#2851]
Is it possible for the SiteToZoneAssignmentList policy to accept generic entries without https or http? I realize www is the one option, but what about internal websites (int.site.com)? I'm also curious if there's any way to include wildcards as well - *.site.com makes the policy fail but http(s)://*.site.com allows it to push... but is the wildcard is really working there and is it only for the specific protocol I choose? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d7e46e1-7659-2efd-341d-9a0ba4adb4bd
* Version Independent ID: 4e032a82-36f1-f1c1-d8d4-8cce7e42799b
* Content: [Policy CSP - InternetExplorer](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-internetexplorer#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-internetexplorer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-internetexplorer.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by guitarfreak58** [comment]
Sorry I guess the asterisks got removed, should have been [ASTERISK].site.com and http(s)://[ASTERISK].site.com in my examples.

**Comment by mypil** [comment]
@AndreaBarr - please assign this issue to me. Thank you.

**Comment by mypil** [comment]
@guitarfreak58 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@guitarfreak58 - I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
