### ISSUE TITLE
The recommended Pin Reset flow is broken (Pin Reset Service/Needs Admin Approval)

### ISSUE THREAD

**Issue by nkwolf** [MicrosoftDocs/windows-itpro-docs#2852]
![pin_fail](https://user-images.githubusercontent.com/992432/53904469-05e8e100-3ffb-11e9-8f1c-47496614a6f5.png)

**Comment by mypil** [comment]
@nkwolf - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
