### ISSUE TITLE
Impossible to sign on

### ISSUE THREAD

**Issue by riebling** [MicrosoftDocs/windows-itpro-docs#2861]
Certain default settings are making it impossible to set up my HoloLens. There seems to be a timeout preventing me from entering the WiFi password, after numerous attempts, it just deletes the fields I typed before completion.
Because of this, setup cannot proceed, namely the next step: granting authorization to Microsoft... because that requires network as well.
Is there no possible way to enable people to set up important details about their HoloLens from a computer connected via USB, and if so, why isn't this clearly spelled out as an alternative?
Otherwise, looking at a dead-in-the-water situation here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc1a9fdc-4dc8-6beb-e487-4829c0bf5e88
* Version Independent ID: e33e9236-2898-a862-1a5d-916f4bb01e87
* Content: [Set up HoloLens (HoloLens)](https://docs.microsoft.com/en-us/hololens/hololens-setup#feedback)
* Content Source: [devices/hololens/hololens-setup.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/hololens/hololens-setup.md)
* Product: **hololens**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by mypil** [comment]
@riebling - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot close
