### ISSUE TITLE
Many BitLocker pages are rendering page metadata

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#2865]
Many of the BitLocker pages have the article metadata displayed as one text blob at the top of them. For example, the title, description, ms.assetid, ms.prod, etc. There are quite a few pages that have this problem under the BitLocker topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29116f85-264f-d031-be7b-e32a1816cd28
* Version Independent ID: 640478e6-a367-4e47-a177-3a10dd006d1c
* Content: [Prepare for drive and file encryption](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10.md)
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@iadgovuser1 @rbsec thanks for reporting this. I submitted a fix that will appear with next publishing cycle about six hours from now.

**Comment by mypil** [comment]
@iadgovuser1 - From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
