### ISSUE TITLE
Deploy updates using Windows Update for Business

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/windows-itpro-docs#2867]
says it was updated yesterday. How? (no change history)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ac5717f-e911-ac81-445d-6fbeb371b334
* Version Independent ID: 5e8e7627-d30e-d3ea-f673-c0093486cc99
* Content: [Change history for Update Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/change-history-for-update-windows-10)
* Content Source: [windows/deployment/update/change-history-for-update-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/change-history-for-update-windows-10.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by mypil** [comment]
@BR77BE - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by BR77BE** [comment]
My question was about the documentation, not Windows 10 itself. The date was changed on the page mentioned in the title, but I can't see what else was changed because you seem to have given up maintaining the change history for the documentation.

**Comment by mypil** [comment]
@BR77BE - Sorry to hear that you are having issues. Please understand that this site is a product documentation site and not a support nor a feature request site.

As such, the feedback section here is intended for feedback that improves the content in the Microsoft documentation and not intended for user feedback on product features nor troubleshooting.

For user feedback on product feature requests, you can submit via User Voice - **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**. I know the product teams are always looking for user feedback on how to make Windows 10 better. You might find others have made a similar request that you can add to, or you can open a new one.

For troubleshooting, you can visit **support.microsoft.com**, **answers.microsoft.com** or open a support ticket- **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**.

I hope this gets you pointed in the right direction. Thank you.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by BR77BE** [comment]
"the feedback section here is intended for feedback that improves the content in the Microsoft documentation"
That's what I'm trying to do!
Please read the title and the text.

**Comment by illfated** [comment]
Sorry to see that your feedback may have been misunderstood.
I am thinking maybe we need to see image snippets from the page where you say the information is wrong or misleading.
Do you think you could add a comment with image cut-outs and links to where the incorrect information is located?
