### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/windows-itpro-docs#2869]
Hi Team

it looks like the link is dead for: "Support Tip: Ingesting Office ADMX-backed policies using Microsoft Intune" https://techcommunity.microsoft.com/t5/Intune-Customer-Success/Support-Tip-Ingesting-Office-ADMX-Backed-policies-using/ba-p/354824

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14d97fd9-b060-7bd5-1bc1-57efa474f75f
* Version Independent ID: be3a74fc-cac8-9b2c-dcc8-edc83cdf111f
* Content: [Enable ADMX-backed policies in MDM](https://docs.microsoft.com/en-us/windows/client-management/mdm/enable-admx-backed-policies-in-mdm)
* Content Source: [windows/client-management/mdm/enable-admx-backed-policies-in-mdm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enable-admx-backed-policies-in-mdm.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by illfated** [comment]
The link https://techcommunity.microsoft.com/t5/Intune-Customer-Success/Support-Tip-Ingesting-Office-ADMX-Backed-policies-using/ba-p/354824 works OK for me, I don't see the problem.
Are you sure the problem is not only for your browser, computer or firewall?
Anyone else able to confirm if there is a problem to view that page?

**Comment by mypil** [comment]
@zlDev @illfated  - The link also works for me.

**Comment by mypil** [comment]
@zlDev - It appears that the link is working. If you are having problems with accessing the link in your computer, I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

**Comment by zlDev** [comment]
Hi. It does now. Thanks.
________________________________

**Comment by mypil** [comment]
@officedocsbot close
