### ISSUE TITLE
Correction required

### ISSUE THREAD

**Issue by kumaarrahul** [MicrosoftDocs/windows-itpro-docs#2871]
Hi,

In free trial account it is mentioned as free EMS 90 day trial. EMS only provides Intune related features. Ideally, it should be Microsoft 365 E3/E5 trial.

Extract from the article above:

"Obtain a free EMS 90-day trial by visiting the following link. Provide your email address and answer a few simple questions."

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d34316d0-bb07-27a0-046b-a2534115a176
* Version Independent ID: 7d358473-9967-2d62-10f2-ce761cc674b1
* Content: [Deploy Windows 10 with Microsoft 365](https://docs.microsoft.com/en-us/windows/deployment/deploy-m365#feedback)
* Content Source: [windows/deployment/deploy-m365.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-m365.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by egallagh** [comment]
Hi kumaarrahul.
Microsoft does not currently offer a Microsoft 365 E3/E5 trial.
The free trial for EMS mentioned allows someone that already has Windows and Office 365 (or is running an Office 365 trial) to explore what EMS, as a part of Microsoft 365, offers.
I hope that helps.
Recommend closure.

**Comment by kumaarrahul** [comment]
Hello egallagh,

I beg to differ on this one.

As per this article: https://docs.microsoft.com/en-us/office365/admin/try-or-buy-microsoft-365?view=o365-worldwide

"The following Microsoft 365 subscriptions are available in the admin center for you to try or buy now:

Microsoft 365 Business

Microsoft 365 Enterprise E3

(Coming soon!) Microsoft 365 Enterprise E5"

I agree there is no direct page/link to sign-up for Microsoft 365 trial but existing users can do the same from Admin Center.

**Comment by egallagh** [comment]
You are 100 percent correct, sir! New since last time I looked!
Thanks for the info. I will enter a correction.

**Comment by jamesosw** [comment]
Microsoft 365 Deployment Advisor doesn't seem to be ready. From the portal, there isn't any option even though I've applied for a trial on M365 E3. The wizard keeps looping back to Office 365 service offerings only

**Comment by greg-lindsay** [comment]
Hi James, I checked the deployment advisor and it's working for me. The UI has updated but the steps are essentially the same. It sounds like maybe the trial M365 E3 isn't active.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@kumaarrahul 

This issue has had been addressed with the following commit and content has been updated according to your feedback.

[d75866 Added info for Microsoft 365 trials ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/d758662d056186c937c075e3b1c87402f655b7f8)

We are thus closing this issue since it seems to be resolved. 

Thank you for taking the time to provide feedback.

**Comment by e0i** [comment]
@officedocsbot close
