### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by chjone** [MicrosoftDocs/windows-itpro-docs#2873]
'Folder' is misspelled in the following sentence: For a provisioning package stored on a network forlder or on a SharePoint site, navigate to the provisioning package and double-click it to begin installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6c9cfe6-6edc-36cf-8917-ffd9a9636a31
* Version Independent ID: 0849bdf4-c1b4-41ce-457c-aed7d4c5857a
* Content: [Apply a provisioning package (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-apply-package#desktop-editions)
* Content Source: [windows/configuration/provisioning-packages/provisioning-apply-package.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/provisioning-packages/provisioning-apply-package.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
Thanks @chjone I'll get that fixed.
