### ISSUE TITLE
Yuva Feedback

### ISSUE THREAD

**Issue by dyuvaraaj** [MicrosoftDocs/windows-itpro-docs#2876]
Yuva Feedback - To validate my feedback related to documents has been captured by MS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7b0bed0-d344-9e32-f789-ddebb0309ecf
* Version Independent ID: 6c821f59-d507-df49-19c7-9a98dd162bf0
* Content: [Windows 10, version 1709 and newer diagnostic data for the Full level (Windows 10)](https://docs.microsoft.com/en-us/windows/privacy/windows-diagnostic-data)
* Content Source: [windows/privacy/windows-diagnostic-data.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/windows-diagnostic-data.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
Hi @dyuvaraaj, is there an issue you want to address ?

**Comment by dyuvaraaj** [comment]
Hello Dani,

I don’t have issues with MS docs.

Thanks,
Yuvaraj

**Comment by illfated** [comment]
Feedback can also be given by using the Feedback Hub in Windows (Windows-Key + F) or via UserVoice for Office applications: https://blogs.technet.microsoft.com/o365guy/2018/01/02/submit-product-feedback-or-feature-requests-to-microsofts-virtual-suggestion-boxes/ .

Other than that, it looks like this issue ticket can be closed.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
