### ISSUE TITLE
BitLocker does not work, can't handle my TPM module

### ISSUE THREAD

**Issue by verdy-p** [MicrosoftDocs/windows-itpro-docs#2877]
BitLocker does not work at all. It can't detect and handle my TPM 2.0 module and the "required" encryption is simply IMPOSSIBLE to do!

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: cde8beb2-6800-cf3c-c927-91ed2827eb6c
* Version Independent ID: 7264f37a-e40a-3cd8-d28c-5b2b772eff15
* Content: [BitLocker (Windows10)](https://docs.microsoft.com/fr-fr/windows/security/information-protection/bitlocker/bitlocker-overview)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-overview.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/information-protection/bitlocker/bitlocker-overview.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@verdy-p - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot close

**Comment by verdy-p** [comment]
closed without ANY solution from Microsoft and from manufacturer!

**Comment by verdy-p** [comment]
In summary this just confirms what I said: BitLocker does NOT work, it has never been seriously tested, there's no support at all. Why do you require it then ?

**Comment by mypil** [comment]
@verdy-p - Sorry to hear that you are having issues. Please understand that this site is a product documentation site and not a support nor a feature request site.

As such, the feedback section here is intended for feedback that improves the content in the Microsoft documentation and not intended for user feedback on product features nor troubleshooting.

For user feedback on product feature requests, you can submit via User Voice - **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**. I know the product teams are always looking for user feedback on how to make Windows 10 better. You might find others have made a similar request that you can add to, or you can open a new one.

For troubleshooting, you can visit **support.microsoft.com**, **answers.microsoft.com** or open a support ticket- **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**.

I hope this gets you pointed in the right direction. Thank you.

**Comment by SharmaKartikay** [comment]
TPM 2.0 does not work when the BIOS Mode is set as Legacy. Please Ensure that the BIOS Mode is Native UEFI and CSM is disabled.

For machines that are running in Legacy mode, you may use MBR2GPT.exe to convert the Dusk Layout to GPT after which the BIOS Mode can be changed to UEFI Only.
