### ISSUE TITLE
link in Benefits section doesn't work

### ISSUE THREAD

**Issue by jurajgh** [MicrosoftDocs/windows-itpro-docs#2879]
the link in Benefits section in Store for Education doesn't work for our institution. clicking the link does nothing. tried various browsers/guest/incognito windows.. nothing helped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87760a66-0877-5a64-0b63-52495c3717ca
* Version Independent ID: c6d2091f-5ae6-1546-f0ed-6e506ec3e25e
* Content: [Change to Windows 10 Education from Windows 10 Pro](https://docs.microsoft.com/en-us/education/windows/change-to-pro-education#feedback)
* Content Source: [education/windows/change-to-pro-education.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/change-to-pro-education.md)
* Product: **w10**
* GitHub Login: @MikeBlodge
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
Sounds more like a firewall/routing/DNS issue than the link itself in the documentation.
BTW, do you mean the link https://educationstore.microsoft.com/ or something else?

**Comment by jurajgh** [comment]
it *used to* work some time before, that's why i am surprised. there are no relevant firewall/DNS rules that would affect browsing to that particular link.
and no, I mean this one: https://cl.ly/548d1de5995a
clicking on the link (as mentioned in the article I put feedback on) does nothing. it should allow me to opt-in for free Windows 10 Pro Education upgrade for my organization. but the section just isn't accessible.

**Comment by mypil** [comment]
@jurajgh - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot close

**Comment by dstrome** [comment]
@mypil - please try invoking the bot again

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot close
