### ISSUE TITLE
DG_Readiness_Tool_v3.5.ps1 -Enable -AutoReboot

### ISSUE THREAD

**Issue by jamilsaif** [MicrosoftDocs/windows-itpro-docs#2880]
This command is not running, followed all instructions, and it gives the error:

PS C:\WINDOWS\system32&gt; DG_Readiness_Tool_v3.5.ps1 -Enable -AutoReboot
DG_Readiness_Tool_v3.5.ps1 : The term 'DG_Readiness_Tool_v3.5.ps1' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that 
the path is correct and try again.
At line:1 char:1
+ DG_Readiness_Tool_v3.5.ps1 -Enable -AutoReboot
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (DG_Readiness_Tool_v3.5.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Any suggestions on how to run this PS?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#feedback)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jamilsaif - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by illfated** [comment]
@jamilsaif : Did you check to see if the cmdlet `DG_Readiness_Tool_v3.5.ps1` works if it is written with a dot + backslash in front (if it is located in the same directory as the command is inserted)?

```sql
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32>  .\DG_Readiness_Tool_v3.5.ps1 -Enable -AutoReboot
PS C:\WINDOWS\system32>_
```

If the cmdlet is stored somewhere else, you probably need to include the full path to where the cmdlet is stored, like
```sql
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> C:\MyPath\FolderName\DG_Readiness_Tool_v3.5.ps1 -Enable -AutoReboot`

**Comment by jinstrong** [comment]
HI,
Just a note, we may need to enable running scripts of powershell with below command:

`set-executionpolicy remotesigned`
