### ISSUE TITLE
Optional opt-in to WHfB

### ISSUE THREAD

**Issue by bally-singh** [MicrosoftDocs/windows-itpro-docs#2881]
Hi,

We are deploying Windows 10 devices via Microsoft AutoPilot.

When setting the option via: 
Dashboard > Microsoft Intune > Device enrollment - Windows enrollment > Windows Hello for Business - Properties > Settings

It appears that if WHfB is set to either "not configured" or "enabled", the user will be prompted to setup every time they sign-in. Is this correct?

Not configured will honour configuration done on client, which by default appears to enable Windows Hello.

Is there an option for the user to be able to manually configure by choice? i.e. if a user wants to use that they can go to settings > sign-in options and configure.

Or is this something that would need to be set to "disabled" during the Intune AutoPilot phase and then "enabled" by a policy filtered on an Azure AD group, and user would again be prompted during login...?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 789566d4-463a-4c64-bf89-fb963ac29f80
* Version Independent ID: 02946732-bb29-d8e6-cedd-7f5e508f8798
* Content: [Manage Windows Hello in your organization (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-manage-in-organization)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-manage-in-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-manage-in-organization.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by rkemna** [comment]
There is now the option to disable WH4B for everyone (see: device enrollment\windows enrollment\Windows Hello for business) and then to make a special profile for WH4B, attach a group to this profile and place the users in it. See an article of Per Larsen, How to start a pilot on Windows Hello with Intune.
https://osddeployment.dk/2018/09/02/how-to-start-a-pilot-on-windows-hello-with-intune/

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @bally-singh 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
