### ISSUE TITLE
Update Problem

### ISSUE THREAD

**Issue by IulianOriflame** [MicrosoftDocs/windows-itpro-docs#2882]
Hi,when i try to update my windows manually i need to try many times until it's works,why? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4e47c9-b470-be67-acc3-6a763746b854
* Version Independent ID: fdfb6514-3340-54a2-7743-9ce46b91c5e3
* Content: [Windows 10 and Windows 10 Mobile (Windows 10)](https://docs.microsoft.com/en-us/windows/windows-10/#feedback)
* Content Source: [windows/hub/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/hub/index.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **brianlic**

**Comment by illfated** [comment]
A bit difficult to say for certain. There can be several factors affecting the way Windows Update works, not to mention the computer itself and its network connection.
From my point of view, this needs ordinary troubleshooting from support, unless there is something specific you are testing related to Azure or Mobile devices.
Without a full description of the scenario, it is too difficult to find out what could cause your issue. I recommend contacting either Microsoft Support or a relevant computer support instance.

(This site is primarily meant for improvements on the Microsoft documentation for IT Professionals, does your issue relate to a specific part of the documentation?)

**Comment by IulianOriflame** [comment]
If it's making again like that for next update when i will have it,i will come back with some photos or video with the problem! Thank you for your help @illfated

**Comment by mypil** [comment]
@IulianOriflame - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by IulianOriflame** [comment]
Yes, I will write at the support you gave it to me if the problem persists! Thank you @mypil

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
