### ISSUE TITLE
This is not working on 1809

### ISSUE THREAD

**Issue by redog** [MicrosoftDocs/windows-itpro-docs#2883]
Using 1809 17763.316 Business Edition 

Neither method of using the CSP Custom policy or Device Restriction Start Menu file option work. The menu will revert to system default instead of applying any customizations. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79fccecd-5484-0304-d82b-9425f1889a22
* Version Independent ID: 4df6b138-c1b5-b551-22c9-19d3d1f9105d
* Content: [Customize and export Start layout (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/customize-and-export-start-layout)
* Content Source: [windows/configuration/customize-and-export-start-layout.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/customize-and-export-start-layout.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@redog "Business Edition" is Microsoft 365, this documentation is for Windows 10 Pro, Enterprise, and Education. Please contact Microsoft Support for assistance.

**Comment by redog** [comment]
Same exact thing in enterprise edition. Broken the taskbar changes apply but the Start menu reverts.
