### ISSUE TITLE
How many Win10 Enterprise Activations per user?

### ISSUE THREAD

**Issue by AndySanchezVM** [MicrosoftDocs/windows-itpro-docs#2887]
Hi, I would like to know how many devices per user can have the Win10 Enterprise upgrade? Is it like ProPlus, where you can have up to 5 devices per user?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d34316d0-bb07-27a0-046b-a2534115a176
* Version Independent ID: 7d358473-9967-2d62-10f2-ce761cc674b1
* Content: [Deploy Windows 10 with Microsoft 365](https://docs.microsoft.com/en-us/windows/deployment/deploy-m365#feedback)
* Content Source: [windows/deployment/deploy-m365.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-m365.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
You need an Enterprise licence for each machine. Costs approx. $300 per machine.
https://www.reddit.com/r/sysadmin/comments/8ujw8k/windows_10_enterprise_licensing_of_course/

**Comment by AndySanchezVM** [comment]
What about with the Enterprise license you get with Microsoft 365 E3/5? It is only 1 per machine/user?

**Comment by illfated** [comment]
According to the pages I found, it looks like it depends on if you choose license subscription per machine or per user.
Myself, I don't have any experience in this matter, so I would prefer if someone like @egallagh could chip in here.

**Comment by egallagh** [comment]
Hi there!
It is my understanding from previous conversations with Microsoft that each system where a user is the "primary user" of the PC, up to the 5 systems linked to that user via the Microsoft 365 subscription license, gets the enterprise upgrade. This does not mean that you can get 5 Microsoft 365 licenses and have 25 users on 25 machines. But is that user has a desktop PC, a laptop, a surface or other tablet, etc., they would all get Windows Enterprise. I'm heading to Redmond on Friday for 10 days and will verify when I am out there that this is still current info.
Hope this helps

**Comment by AndySanchezVM** [comment]
Thank you both for your answers. This most definitely helps and would greatly appreciate if you could confirm that while you are there.

**Comment by kumaarrahul** [comment]
The license info is mentioned in this article.

https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-subscription-activation

It is 5 devices/user. Also, to add, Microsoft 365 E3/E5 or Windows 10 E3/E5 only provides with Windows 10 Enterprise upgrade benefits & not activation rights.

Extract from the article:

"Licenses
The following policies apply to acquisition and renewal of licenses on devices:

Devices that have been upgraded will attempt to acquire licenses every 30 days, and must be connected to the Internet to be successful.
Licenses are valid for 90 days. If a device is disconnected from the Internet until its current license expires, the operating system will revert to Windows 10 Pro. As soon as the device is connected to the Internet again, the license will automatically renew assuming the device is still present on list of user devices.
Up to five devices can be upgraded for each user license.
The list of devices is chronological and cannot be manually modified.
If a device meets requirements and a licensed user signs in on that device, it will be upgraded.
If five devices are already on the list and a subscribed user signs in on a sixth device, then this new device is added to the end of the list and the first device is removed.
Devices that are removed from the list will cease trying to acquire a license and revert to Windows 10 Pro when the grace period expires.
Licenses can also be reallocated from one user to another user, allowing you to optimize your licensing investment against changing needs."

**Comment by egallagh** [comment]
@kumaarrahul Good find. This is exactly what I remember from my earlier talks with Microsoft staff. Thanks!

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@AndySanchezVM - Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
