### ISSUE TITLE
Table format need to be fixed

### ISSUE THREAD

**Issue by rathanga** [MicrosoftDocs/windows-itpro-docs#2891]
Operating system requirement table format is lost. Need to be fixed or realigned for readability

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f02c58f-4575-3991-8bee-ccea6c3b3d34
* Version Independent ID: 6b3f5a69-1425-8b36-9e7a-b965fc70a164
* Content: [Requirements to use AppLocker (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/requirements-to-use-applocker#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/applocker/requirements-to-use-applocker.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/applocker/requirements-to-use-applocker.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@rathanga Thanks for reporting. The publishing error is fixed now.
