### ISSUE TITLE
Dead link to MITRE analysis

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/windows-itpro-docs#2892]
Under the MITRE section (https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/top-scoring-industry-antivirus-tests?WT.mc_id=twitter#mitre-industry-leading-optics-and-detection-capabilities) there is a link to Analysis which is dead:
https://cloudblogs.microsoft.com/microsoftsecure/2018/12/03/insights-from-the-mitre-attack-based-evaluation-of-windows-defender-atp/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d814abdc-def2-b2fa-1fa3-a5b8cb5c7f29
* Version Independent ID: 2461d503-e076-43cb-7342-165cec6f58e4
* Content: [Top scoring in industry tests](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/top-scoring-industry-antivirus-tests?WT.mc_id=twitter#mitre-industry-leading-optics-and-detection-capabilities)
* Content Source: [windows/security/threat-protection/intelligence/top-scoring-industry-antivirus-tests.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/intelligence/top-scoring-industry-antivirus-tests.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Hi @npherson we had a temporary issue with links, it should be working now. Try again and let me know if it still doesn't work.
