### ISSUE TITLE
Authenticated Users group must have Read access

### ISSUE THREAD

**Issue by jngibert** [MicrosoftDocs/windows-itpro-docs#2893]
Probably need to update this article, because after the application of MS16-072 we need to have Read permissions (but not apply) for Authenticated Users on user policies - because the computer account is used to read the policies from the domain controller.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75240ad-db64-8d89-4d61-f789fd632e04
* Version Independent ID: f76f946c-7e33-5041-f442-92bd38886d85
* Content: [Assign Security Group Filters to the GPO (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/assign-security-group-filters-to-the-gpo#feedback)
* Content Source: [windows/security/threat-protection/windows-firewall/assign-security-group-filters-to-the-gpo.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-firewall/assign-security-group-filters-to-the-gpo.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@jngibert Thanks for the suggestion. Can you share any more about the change you suggest? Is the change specifically related Windows Firewall or more generally related to Group Policy?

**Comment by jngibert** [comment]
@Justinha 

The change is specific to the suggestion in the document to remove all permissions for "Authenticated Users" from a group policy.

If the group policy contains User settings, and the "Authenticated Users" group is removed, and new security filtering is added using a security group that only contains user accounts - this will break application of the group policy now that computer accounts are used to retrieve user policy from domain controllers.

Details and various workarounds are mentioned in this Microsoft blog:  https://techcommunity.microsoft.com/t5/Core-Infrastructure-and-Security/Who-broke-my-user-GPOs/ba-p/258781

Thanks!

**Comment by Justinha** [comment]
@jngibert thanks again and sorry for delay. I added what you wrote as a note after the steps to remove AU. Does this cover it? If you can submit a pull request with any other changes you want, I appreciate it.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jngibert - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
