### ISSUE TITLE
Using the 'footnote' for needed Windows version is difficult 

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/windows-itpro-docs#2896]
It is really difficult to use this documentation to determine what is/is not supported on a particular version of Windows 10, or to see what was added in the latest update. Using search in the document for a "5" to find things added in 1809 doesn't work so hot. The footnote is not a good way to handle this. Maybe just include the "Added in Windows 10, version XYZA" verbiage in the template for each setting instead of the footnote?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b1ab2e-1964-5580-7c99-4bd4cd480075
* Version Independent ID: f7b5da46-04cb-3501-65fa-870a3c6f09b8
* Content: [Policy CSP - Defender](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#defender-attacksurfacereductionrules)
* Content Source: [windows/client-management/mdm/policy-csp-defender.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-defender.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by npherson** [comment]
Some of the other parts of MDM documentation already include the version info in each setting section, like here: https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-education

That works much better for searching for things like "1809" on the page. Or being able to look at a setting and know what version is required without scrolling to the bottom of a very long page.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@npherson 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by lindspea** [comment]
@npherson Thank you for reaching out and helping improve MS Docs. Just to double check, are you suggesting replacing each note reading "This policy is only enforced in Windows 10 for desktop" with your verbiage "Added in Windows 10, version XYZA"?

**Comment by npherson** [comment]
>"Just to double check, are you suggesting replacing each note reading "This policy is only enforced in Windows 10 for desktop" with your verbiage "Added in Windows 10, version XYZA"?"

Thanks for double checking! No, not suggesting you replace that verbiage, just add the new. Take a look at the MDM link from above to see what I am suggesting. Each feature description area includes the "Added in Windows 10, version XYZA" verbiage.

And, I see that SOME of the entries on the Defender page actually do follow the same model - features released with 1607 or 1709 do have the "Added in Windows 10, version 1709" verbiage right at the start of their description.

This helps with 2 use cases: Someone came here looking for all the new things that came in the latest release can use search to find all the version 1903 features, and people looking at a particular feature will know the minimum version they need to be on to use it without having to scroll to the bottom to lookup the footnote.

**Comment by lindspea** [comment]
@npherson Thank you for clearing that up.  I'll have the team look into having the relevant information added soonest.

**Comment by e0i** [comment]
@npherson The issue is under investigation.

**Comment by e0i** [comment]
@npherson 

We have been informed that the CSP reference documentation are being updated for consistency and the use case you have brought up is being taken into consideration for improvements.

In the meantime, you may find the following document useful as an alternative,

[What's new in mobile device enrollment and management](https://docs.microsoft.com/en-us/windows/client-management/mdm/new-in-windows-mdm-enrollment-management)

Thank you for providing feedback and following up.

**Comment by e0i** [comment]
@officedocsbot close
