### ISSUE TITLE
Surface Hub PC Replacement Mode Drivers

### ISSUE THREAD

**Issue by vcabbage** [MicrosoftDocs/windows-itpro-docs#2899]
Hi,

I'm unclear whether this is the correct venue for this question, but perhaps you can point me in the right direction.

I setup a PC and installed the currently available `SurfaceHubReplacementPCDrivers.1.1.003.msi` drivers. All the devices appeared to work correctly except the touch screen and pen. I went as far as to reinstalled Windows entirely in an attempt to rule out any driver conflicts, but there's still no touch device listed in Device Manager.

We haven't used PC Replacement Mode in quite a while, but I'm fairly certain touch worked for us previously.

Since those drivers were published only a few days ago it seems conceivable that there's something amiss with the touch component, but I have no proof of this.

Any help would be appreciated. If there's a way to get a copy of the previous drivers so I can check my suspicion that would be quite helpful.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96007a4a-c958-1056-b567-0c0fe92e3bb7
* Version Independent ID: 58813bd5-9182-8850-2885-5f21177aa17b
* Content: [Connect other devices and display with Surface Hub](https://docs.microsoft.com/en-us/surface-hub/connect-and-display-with-surface-hub#replacement-pc-mode)
* Content Source: [devices/surface-hub/connect-and-display-with-surface-hub.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/connect-and-display-with-surface-hub.md)
* Product: **surface-hub**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@vcabbage You should contact Microsoft Support for assistance troubleshooting the problem you're having.
