### ISSUE TITLE
Step 5 under enterprise mode has more options

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#2902]
Step 5 (Click Enabled and click OK.) under the enterprise mode section has a screenshot that is out of date and the text makes no mention of the currently available options. There are a number of options to choose from now in Group Policy:

0. Disable Windows Defender Application Guard
1. Enable Windows Defender Application Guard for Microsoft Edge ONLY
2. Enable Windows Defender Application Guard for Microsoft Office ONLY
3. Enable Windows Defender Application Guard for Microsoft Edge AND Microsoft Office

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15d066f2-0726-bbf9-3425-756ce7dbadee
* Version Independent ID: 03501802-fb28-a89d-a463-e27d2fea7456
* Content: [Testing scenarios using Windows Defender Application Guard in your business or organization (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/test-scenarios-wd-app-guard)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/test-scenarios-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/test-scenarios-wd-app-guard.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Dmarch28** [comment]
[An angel with a rainbow over his head and the colors of it was liken with power.docx](https://github.com/MicrosoftDocs/windows-itpro-docs/files/2964933/An.angel.with.a.rainbow.over.his.head.and.the.colors.of.it.was.liken.with.power.docx)
[Angel one Os latter part.pdf](https://github.com/MicrosoftDocs/windows-itpro-docs/files/2964936/Angel.one.Os.latter.part.pdf)
#GodwithUs24-e_use@hotmail.com

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@iadgovuser1 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by Justinha** [comment]
Thanks folks! I submitted  a new screenshot and it should appear later today.

**Comment by Justinha** [comment]
@iadgovuser1 @mypil I added the new image but it's a little too large. I resized it and submitted again. ETA is Monday. 

Thanks again for the correction!

**Comment by iadgovuser1** [comment]
Thanks!
