### ISSUE TITLE
Deployment/images: uppercase PNG file extension names on Github

### ISSUE THREAD

**Issue by illfated** [MicrosoftDocs/windows-itpro-docs#2909]
This is only about internal Github files, the public doc image files are already stored in lowercase .png
and do not need changing (images are named and linked correctly).

- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-m365.md

**Current behaviour:**
Images with UPPERCASE extension names like .PNG are not shown in the Github version of the page.
This is most likely caused by the case-sensitive underlying OS running the Github pages.
For some reason, a number of PNG images are stored with UPPERCASE extension names instead of lowercase,
`*.PNG` instead of `*.png`
(see the following example from https://github.com/MicrosoftDocs/windows-itpro-docs/tree/master/windows/deployment/images):

        windows-itpro-docs/windows/deployment/images/m365da.PNG
        windows-itpro-docs/windows/deployment/images/wada.PNG

This causes the following behaviour on the Github page [**deploy-m365.md**](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-m365.md#microsoft-365-deployment-advisor-example) :

![image](https://user-images.githubusercontent.com/38162891/54247147-1851a600-4538-11e9-889e-2f989850150e.png)

The same does not happen on the public official Docs page, because the files have been saved as lowercase *.png files:
(https://docs.microsoft.com/windows/deployment/deploy-m365#microsoft-365-deployment-advisor-example)

![image](https://user-images.githubusercontent.com/38162891/54247281-a0d04680-4538-11e9-9e7c-d6cdffc93c15.png)

Checking the HTML source both on the docs.microsoft.com page and the github.com page, the image links are the same.
(I tried creating a Pull Request to rename the files, but on Windows 10 the change does not register in Git Extensions.)

**Notes:**
This issue can easily be the case for more than just these 2 files, but I thought it prudent to start with a limited sample.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@illfated - Thank you for submitting this feedback.

Is this a bug that you've discovered?

**Comment by illfated** [comment]
Thank you for looking into this issue, your time is appreciated.
Yes, I noticed this bug specifically on the page [windows/deployment/deploy-m365.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-m365.md) while looking at the results from earlier merges, whereby the page looked somewhat different on Github compared to the https://docs.microsoft.com/windows/deployment/deploy-m365#microsoft-365-deployment-advisor-example page (see my first post for details about the images).

This specific issue is only visible on Github, because the `PNG` files I mentioned have been uploaded to Github with their extension names (.PNG) in `CAPS` instead of `lowercase`.

For some unknown reason, the files have migrated to the docs.microsoft.com site with their names properly converted to lowercase, thereby making the links work as expected & intended there. This issue is therefore only visible on Github, in the source code. I tried to create a PR to rectify this issue by renaming them locally on my Windows 10 computer, but Windows does not differentiate between UPPERCASE and lowercase extensions in the file names. It only becomes visible in UNIX-like file systems where filename case makes a difference.

I can only hope I was able to clarify the issue. If not, feel free to ask for a better description.
I am uncertain about what the best solution will be if you want to fix the image file names on Github.

Unfortunately, I don't know if it is possible to rename the files directly on Github or if it will be necessary to upload the images again from a file system where the image file extension names are exclusively in lowercase. Maybe @Justinha knows more about this, I don't know.

**Comment by illfated** [comment]
Oh, and by the way: I am pretty sure this goes for _all_ of the image files in https://github.com/MicrosoftDocs/windows-itpro-docs/tree/master/windows/deployment/images (maybe even some of the other image folders, I haven't checked all of them yet).

**Comment by mypil** [comment]
@illfated - this is a good discovery. Thank you for reporting this to help improve the docs. 

@kenwith - this is a possible bug found in Github, Who can we reach out to get this investigated and resolved?

Thank you.

**Comment by Justinha** [comment]
@illfated Thanks for reporting this. My guess is we have a publishing script that changes the extension to lower case, @DaniHalfin would you know?

**Comment by DaniHalfin** [comment]
1. You can rename files on GH, although I'm not sure that upper-to-lower case change will register as a name change.
2. The build engine renders all extensions as lowercase, as far as I remember (the files remain the same, meaning - it uses the same source).

**Comment by illfated** [comment]
I see what you are saying, but I think it depends on the underlying OS where the file system lives. Like Justin said, it is very likely that the publishing script solves the issue for the public docs site, but the issue with the uppercase file name extensions remains here on Github. My foremost guess is that Github runs on a *NIX operating system with a case-sensitive file system, hence the missing images when displaying the Github source pages.

On a Windows computer, Git Extensions (which I use to create Pull Requests) does not see any changes when the image files are renamed from uppercase to lowercase extension names, therefore not seeing the required change to create a pull request (and hence no PR material to push to my fork here on Github). That is why I suggested either A) file extensions renamed directly on Github, or B) create a PR on a UNIX-like (e.g. Linux) OS where the change will be noticed, and push the changes from there.

That is about how far I got. I don't have a ready Linux setup to provide the solution, that is mostly why I opened this issue -- so those of you on the Docs team could choose what kind of solution to pick.

**Comment by DaniHalfin** [comment]
You might be right here. However, it feels like a GH platform issue, than an issue in our content.
I guess we can fix it in our repo, so I'll check with the other admins, to see how we tackle this further.
Thanks for bringing it to our attention.

**Comment by illfated** [comment]
Hang on. I think I may have solved my local issue of not being able to differentiate between uppercase and lowercase file names. Let me try to create a PR now and reference this issue to solve the specific page I mentioned above ([deploy-m365.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-m365.md#microsoft-365-deployment-advisor-example))

**Comment by DaniHalfin** [comment]
@ mention me please (on the PR) :)

**Comment by illfated** [comment]
Will do. Thanks. 👍 😃

**Comment by mypil** [comment]
@illfated - The PR you requested for has been merged. Kindly check and let us know if your issue has been resolved. Thank you.

**Comment by illfated** [comment]
Thank you for "pinging" me, sure thing. The page https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-m365.md is now displayed as it should be. Renaming the files from uppercase .PNG  to lowercase .png file name extensions was a success and I don't think it should trigger any update of the docs.microsoft.com pages (seeing that those pages work as expected anyway).

If you want to, you can choose to consider this specific issue resolved, even though I would like a confirmation from @DaniHalfin whether he wants a new issue ticket for the remaining 80 uppercase .PNG files in the folder https://github.com/MicrosoftDocs/windows-itpro-docs/tree/master/windows/deployment/images , or if you have got any other means of keeping tabs on the local Github uppercase name extension issue.

**Comment by DaniHalfin** [comment]
We're currently experiencing a bit of an issue due to the renames, so we might end up reverting it. We'll consider how to approach this issue going forward. As of right now, we're not going to continue with the renames.

**Comment by illfated** [comment]
Very well, thank you for the information update.
Sorry for the trouble and thank you for your time.
