### ISSUE TITLE
Windows Hypervisor Requirement

### ISSUE THREAD

**Issue by jonconwayuk** [MicrosoftDocs/windows-itpro-docs#2912]
One of the Hardware and software requirements listed in this article states that "Windows Hypervisor" is required. This is confusing as it seems that this is not required to be able to use Device/Credential Guard. Can this be clarified to avoid confusion? As it currently reads, it looks like you need to install the "Hyper-V" Windows Feature - in my testing this has not been required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0238a73f-da06-ae17-c61d-85ae54e0f7cb
* Version Independent ID: e5bb4a25-a7c3-3a16-bd95-d6f2513402e0
* Content: [Windows Defender Credential Guard Requirements (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-requirements#feedback)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-requirements.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by DaniHalfin** [comment]
Hi @jonconwayuk , installing Hyper-V isn't required, however, these security features operate through the Hypervisor layer, meaning Windows will occupy that layer, similar to when you install Hyper-V is a feature.
The implication here is that if you want to use any other solution that needs to occupy that layer, aside for the built-in Windows features that rely on it (such as Hyper-V), you won't be able to.
This is why we don't call out Hyper-V, but rather say "Windows Hypervisor".

**Comment by jonconwayuk** [comment]
I just feel that clarification on the Hyper-V Feature not being required would help make this more obvious as a statement from Microsoft.

There are many 3rd party articles around on forums and blogs which describe the Hyper-V Feature as being a prerequisite for using Device/Credential Guard which adds to the confusion.

Is it possible to amend the documentation to the following or something similar?: 

"Windows Hypervisor (does not require Hyper-V Windows Feature to be installed)"

Or alternatively, just add a summary of what you have said in your response to me in your previous message as that would make it very clear what the requirements are.

**Comment by mypil** [comment]
@jonconwayuk - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
