### ISSUE TITLE
XSD Errors

### ISSUE THREAD

**Issue by andrewwillett** [MicrosoftDocs/windows-itpro-docs#2914]
Please validate your XSD! There are many errors.

Missing a space between attributes: name="CryptographySuite"minOccurs="0"
q1:EapHostConfig cannot be resolved to an element declaration component

As tFable has raised, maxOccurs="unbounded" looks incorrect on xs:element name="CryptographySuite"

This will validate your revised XSD: https://www.liquid-technologies.com/online-xsd-validator

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3032f094-c9b7-6f8c-5b66-2ba152d7c326
* Version Independent ID: 83047fc5-7020-be72-85d6-85fa0bfbf5b7
* Content: [ProfileXML XSD](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-profile-xsd)
* Content Source: [windows/client-management/mdm/vpnv2-profile-xsd.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/vpnv2-profile-xsd.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by dotps1** [comment]
any chance this is going to get fixed so I can validate my xml config and actually use the always on vpn product?

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by angrymrtom** [comment]
wow, moving fast over there, takes 2 months just to assign the tickets.

**Comment by e0i** [comment]
@andrewwillett @angrymrtom 

Apologies for the delay.

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback and following up.

**Comment by e0i** [comment]
@andrewwillett 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.
