### ISSUE TITLE
Example Request SyncML for Disabling Control Panel

### ISSUE THREAD

**Issue by dfconroy** [MicrosoftDocs/windows-itpro-docs#2916]
I'm able to disable specific 'pages' in the Settings screen of a Windows 10 machine - however, I can't seem to disable either specific sections or the entire Control Panel (old style). So users can still access the control panel.

Is this even possible using SyncML vs Group Policy Editor? 

Here is the Request SyncML I'm currently using. 

```xml
<Replace>
			<CmdID>45e33624-e5ee-40bb-b9da-0fea0452506bdisDevice:17</CmdID>
			<Item>
				<Target>
					<LocURI>./Device/Vendor/MSFT/Policy/Config/Explorer/NoControlPanel</LocURI>
				</Target>
				<Meta>
					<Format xmlns="syncml:metinf">chr</Format>
				</Meta>
				<Data><![CDATA[<enabled/>]]></Data>
			</Item>
		</Replace>```

**Comment by jdeckerms** [comment]
@dfconroy When you entered your comments, they didn't get associated with a specific topic, not sure why. Could you please link to the topic your feedback is about? Thanks.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@dfconroy 

Somehow your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by e0i** [comment]
@dfconroy 

We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.

Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
