### ISSUE TITLE
KioskModeApp with a Win32 desktop application

### ISSUE THREAD

**Issue by Banthaf0dder** [MicrosoftDocs/windows-itpro-docs#2918]
This documentation only outlines how to use KioskModeApp with a UWP app using AppUserModelId. Can DesktopAppPath be used instead to use a Win32 desktop application with KioskModeApp?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78038d67-04a1-f4ae-6a69-98e157688a31
* Version Independent ID: c86b4460-e8be-8537-a6c8-3cb094ef14a3
* Content: [Set up a multi-app kiosk  (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps#feedback)
* Content Source: [windows/configuration/lock-down-windows-10-to-specific-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/lock-down-windows-10-to-specific-apps.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@Banthaf0dder As you can see in the XML reference (https://docs.microsoft.com/en-us/windows/configuration/kiosk-xml#xsd-for-assignedaccess-configuration-xml), kioskmodeapp only accepts AUMID. 

You can see the options for running a single-app kiosk using a Win32 application here: https://docs.microsoft.com/en-us/windows/configuration/kiosk-methods#methods-for-a-single-app-kiosk-running-a-windows-desktop-application
