### ISSUE TITLE
Confusion is this Windows Autopilot can run on Win 10 IoT Core?

### ISSUE THREAD

**Issue by lyemeeki** [MicrosoftDocs/windows-itpro-docs#2921]

**Comment by mypil** [comment]
@lyemeeki - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@lyemeeki - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
