### ISSUE TITLE
provisioning package during first-run

### ISSUE THREAD

**Issue by sccmfan** [MicrosoftDocs/windows-itpro-docs#2924]
could you clarify which configurations are applicable during the first-run setup with the current image version for Surface HUB? can we for example apply Azure AD configuration?

thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf0f0af-2ca4-8705-fa1a-4fa34fff0d99
* Version Independent ID: 75dd473c-f64d-bb3c-67ac-60831e397395
* Content: [Create provisioning packages (Surface Hub)](https://docs.microsoft.com/en-us/surface-hub/provisioning-packages-for-surface-hub#feedback)
* Content Source: [devices/surface-hub/provisioning-packages-for-surface-hub.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/provisioning-packages-for-surface-hub.md)
* Product: **surface-hub**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@sccmfan Good question, the topic isn't very clear on that, is it? 

Under "Apply a provisioning package during first run", there's an "important" note that says "Only use provisioning packages to install certificates during first run. Use the Settings app to install apps and apply other settings." 

What that means (and I'll be rewriting the note to be clearer), is that a provisioning package that you apply during first-run can only contain client certificates. For any other settings, you need to complete first-run setup first, and then you can apply a provisioning package through the Settings app for other configurations and settings.
