### ISSUE TITLE
Tip Question

### ISSUE THREAD

**Issue by sadjadbp** [MicrosoftDocs/windows-itpro-docs#2936]
Where you mentioned `AzureADName\YourAccountName` do you mean something like 'contoso.com\username' or `username@contoso.com` 

Since neither one is working for me and I have to use what's explained here

https://morgansimonsen.com/2015/11/06/connecting-to-an-azure-ad-joined-machine-with-remote-desktop/

and AzureAD\UPN and use a special rdp file that has `enablecredsspsupport:i:0` with NTLM off on the server!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc#feedback)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by sadjadbp** [comment]
Can someone explain why we have to create special RDP file like explained 

https://www.niallbrady.com/2017/08/23/how-can-i-rdp-to-an-azure-ad-joined-windows-10-device/

and

https://morgansimonsen.com/2015/11/06/connecting-to-an-azure-ad-joined-machine-with-remote-desktop/

Isn't the future to have AAD Joined PCs, then why there is no easy way to RDP to a AAD joined machine. Any work in progress?
and

**Comment by mypil** [comment]
@sadjadbp - For the first issue you opened, a Pull Request (PR #2950)  has been created to address that but it may take a few days for the merged content to appear in the article. As for your follow up question, let me loop in the doc owner. 

@jdeckerms - Can you please share your insights on this? 

Thank you,

**Comment by mypil** [comment]
@jdeckerms - We would like to follow up on this. Can you please share your insights on the 2nd query from sadjadbp?  Thanks.

**Comment by mypil** [comment]
@jdeckerms - We would like to follow up on this. Can you please share your insights on the 2nd query from sadjadbp? Thanks.

**Comment by mypil** [comment]
@jdeckerms - We would like to follow up on this. Can you please share your insights on the 2nd query from sadjadbp? Thanks.

**Comment by mypil** [comment]
@jdeckerms - We would like to follow up on this. Can you please share your insights on the 2nd query from sadjadbp? Thanks.

**Comment by illfated** [comment]
@DaniHalfin : Could you assist in answering the question from mypil/Joyce ?
( jdecker seems to be unresponsive for the time being )

**Comment by DaniHalfin** [comment]
I'll try looking for the right resource. Also, @jdeckerms won't be responsive going forward.

**Comment by mypil** [comment]
@DaniHalfin - Do you have any updates on this?

Thank you.

**Comment by mypil** [comment]
@DaniHalfin @Dansimp - We would like to follow up on this. Do you have updates on this? Or Please let us know who we can reach out to get this issue addressed. 

Thank you.

**Comment by mypil** [comment]
@sadjadbp - For your 2nd query, I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via [Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
