### ISSUE TITLE
Note says Win 10 only - What about Server 2019?

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/windows-itpro-docs#2943]
Are current versions of Server 2019 or the Server semi-annual channel supported for response actions? If not, it would be better to explicitly say so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ad120c9-3c66-475a-4bc4-ee69ec11b581
* Version Independent ID: 943de88c-0152-9aba-8415-d9c8b5709c13
* Content: [Take response actions on files and machines in Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/response-actions-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/response-actions-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/response-actions-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@npherson - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@npherson - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
