### ISSUE TITLE
Link missing, editor's note left in

### ISSUE THREAD

**Issue by amp64** [MicrosoftDocs/windows-itpro-docs#2947]
It says "(add link to OEM documentation)" - suggest replacing this with an actual link to OEM documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b83e95-63de-87c5-929c-d5f25e33d124
* Version Independent ID: 743ead3f-b4a5-1589-6577-e1d12aaa1b92
* Content: [Kernel DMA Protection for Thunderbolt™ 3 (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/kernel-dma-protection-for-thunderbolt)
* Content Source: [windows/security/information-protection/kernel-dma-protection-for-thunderbolt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/kernel-dma-protection-for-thunderbolt.md)
* Product: **w10**
* GitHub Login: @AaDake
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by msbemba** [comment]
@amp64  Thank you for the feedback. OEM link is not available at the moment and it depends on the device in use. We have made the necessary changes in the document to reduce ambiguity.  PRhttps://github.com/MicrosoftDocs/windows-itpro-docs/pull/3029

**Comment by mypil** [comment]
@amp64 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
