### ISSUE TITLE
Prereq

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/windows-itpro-docs#2952]
".... Update Compliance only provides data for the standard Desktop Windows 10 version and is not currently compatible with Windows Server, Surface Hub, IoT, etc."

What is not compatible, is this information update to date? If yes, any ETA when it might be available ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5549abd-da28-5d11-49c6-e66ecf5cd0b6
* Version Independent ID: 0ad6a1a2-5c75-baeb-00de-a6649592ec69
* Content: [Get started with Update Compliance (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-get-started)
* Content Source: [windows/deployment/update/update-compliance-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/update-compliance-get-started.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by cinglis-msft** [comment]
Hey Niklas, Windows 10 Professional, Enterprise, Education for Desktop (laptop/desktop) are supported. There are not currently plans to include the other SKUs in Update Compliance, but we hear the feedback that such analytics would be valuable.

**Comment by xNiklasJern** [comment]
@cinglis-msft thanks for the quick reply. I'll be looking forward for the new features
