### ISSUE TITLE
typo in "Install Windows ADK for Windows 10" - should be 'User State Migration Tool (USMT)'

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/windows-itpro-docs#2953]
see title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ab08370-69ab-d025-cea2-c41c3aa4b908
* Version Independent ID: 9f5603f8-10e6-2651-3120-6d5627217cc9
* Content: [Prepare for deployment with MDT (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt#feedback)
* Content Source: [windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jdeckerms** [comment]
@anwarmahmood1 Good catch and thanks for bringing that to our attention! I'll get it fixed.
