### ISSUE TITLE
You can't do a feature update if you've already done the feature update

### ISSUE THREAD

**Issue by bigbadstevo** [MicrosoftDocs/windows-itpro-docs#2955]
"You're now ready to update your computer. After the update..." After *what* update? The feature update has already been done, as stated previously in the article: 
"When you update a computer running Windows 10, version 1703 or 1709, you might see provisioned apps that you previously removed return post-update." To see the problem stated, you must have *already* have done the feature update. Windows 10 will not ask again to do the same feature update. So this makes no sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9c3129d-3c8d-b508-f298-3333499bb180
* Version Independent ID: 97b70720-82d8-60a4-3958-00ceed34aa1b
* Content: [How to keep apps removed from Windows 10 from returning during an update](https://docs.microsoft.com/en-us/windows/application-management/remove-provisioned-apps-during-update#feedback)
* Content Source: [windows/application-management/remove-provisioned-apps-during-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/remove-provisioned-apps-during-update.md)
* Product: **w10**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@bigbadstevo - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @bigbadstevo , as you can see in the article:
"To prevent these apps from reappearing at the next update, manually create a registry key for each app, then update the computer."
So the article is about creation of registry key **before** the update. 

I mean, this article does not contain recommendations what to do when the removed apps reappear, it contains recommendations how to avoid this situation.

What do you think?

Thank you

**Comment by illfated** [comment]
I agree. I also think it is worth remembering that this topic is more useful to IT professionals who need to figure out a way to avoid unwanted changes on more than just a couple of PCs, if changes happen to a lot of computers in their care.

**Comment by mypil** [comment]
@bigbadstevo - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
