### ISSUE TITLE
Education SKU

### ISSUE THREAD

**Issue by mattwak** [MicrosoftDocs/windows-itpro-docs#2956]
Is Application Guard supported on the education SKU as most other fearures of the enterprise SKU are? Please clarify in the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f43df7b-6ead-de5a-2e41-4d49978ab485
* Version Independent ID: 5497d300-cb21-55f3-7e80-98bc3592635c
* Content: [System requirements for Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@mattwak - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@mattwak - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
