### ISSUE TITLE
What does No Internet refer to?

### ISSUE THREAD

**Issue by nimojg-microsoft** [MicrosoftDocs/windows-itpro-docs#2958]
Before introducing the table we write "The following table describes the Set up School PCs app features and lists each type of Intune subscription. An X indicates that the feature is available with the specific subscription."..... Can you clarify what "No Internet" refers to in this case? I think this needs to be rewritten entirely as it makes NO sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b398a57-ce65-1f1f-1e3e-997b15157df3
* Version Independent ID: 13ee70cf-57de-a377-7c61-212ff436e7dc
* Content: [Set up School PCs app technical reference overview](https://docs.microsoft.com/en-us/education/windows/set-up-school-pcs-technical)
* Content Source: [education/windows/set-up-school-pcs-technical.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/set-up-school-pcs-technical.md)
* Product: **w10**
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by jdeckerms** [comment]
@nimojg-microsoft "No internet" means features that are available when there is no internet connection.
