### ISSUE TITLE
App uninstall

### ISSUE THREAD

**Issue by nimojg-microsoft** [MicrosoftDocs/windows-itpro-docs#2959]
Is this enabled by default - or is this only enabled when someone chooses the Uninstall OEM apps in the Setup School PCs flow? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46b1d03f-ac88-46ca-0b93-d695d97f6974
* Version Independent ID: d76084ab-4129-d77a-a68d-40f9fa3b471f
* Content: [What's in Set up School PCs provisioning package](https://docs.microsoft.com/en-us/education/windows/set-up-school-pcs-provisioning-package)
* Content Source: [education/windows/set-up-school-pcs-provisioning-package.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/set-up-school-pcs-provisioning-package.md)
* Product: **w10**
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by jdeckerms** [comment]
@nimojg-microsoft When you use the Setup School PCs app, the resulting package uninstalls the apps listed here: https://docs.microsoft.com/en-us/education/windows/set-up-school-pcs-provisioning-package#apps-uninstalled-from-windows-10-devices 

The option to uninstall OEM/device manufacturer apps in the Setup School PC app is its own option, on top of the apps that are automatically uninstalled.

**Comment by nimojg-microsoft** [comment]
Great - any plans to clarify this in the documentation?
