### ISSUE TITLE
WPAD required?

### ISSUE THREAD

**Issue by sneakernuts** [MicrosoftDocs/windows-itpro-docs#2965]
We have been told by a PFE that WPAD has to be enabled in order for WDAG to work. We were also recommended by our security auditors to turn off WPAD for security reasons. Can we get some more clarification within the documentation? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f43df7b-6ead-de5a-2e41-4d49978ab485
* Version Independent ID: 5497d300-cb21-55f3-7e80-98bc3592635c
* Content: [System requirements for Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@sneakernuts I'm not familiar with WPAD. Is It Web Proxy Auto Discovery?

**Comment by sneakernuts** [comment]
@Justinha that's correct.

**Comment by Justinha** [comment]
@sneakernuts App Guard does not have any dependency on WPAD. Correct me if i'm missing this but whether to turn on or off WPAD for security seems like an issue to cover in WPAD docs. Let me know what you want to see added with respect t WDAG system requirements.

**Comment by sneakernuts** [comment]
What's what we thought. Until we disabled it. WDAG stops working until we re-enable WPAD. According to our PFE from our support call it needs WPAD. Here's what they said verbatim:

"The WinHTTP Web Proxy Auto-Discovery Service is required for the functionality of WDAG and other inbox services.  As such, stopping or disabling this service is not supported."

**Comment by Justinha** [comment]
Ok thanks Otto. I wasn't aware but I've asked engineering to comment.

**Comment by sneakernuts** [comment]
Thanks for looking into this!

**Comment by ermacia91** [comment]
I would also like to know an answer to this. Currently working on this feature with a customer and this might be a blocker in their deployment.

**Comment by Justinha** [comment]
@sneakernuts @ermacia91 here is what I learned:

The actual service itself cannot be disabled. If you disable the service a lot of things will break.
However, you can disable WDAP without disabling the service at Settings > Network & Internet > Proxy > Automatically detect settings (turn it off). 

This registry key  work to disable system accounts on devices running Windows 10 version 1809 or later:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp
DisableWpad=1 (DWORD)

With these settings WDAG will work.

Thanks very much for raising this guys! I'll add this to the system requirements.

**Comment by sneakernuts** [comment]
This is great. Thanks @JustinHa

**Comment by sneakernuts** [comment]
Have one more question. What’s the solution for disabling WPAD on machines that are Windows 10 1709 & 1803?

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@Justinha

Any updates with including WPAD as a software dependency in this article? 

We would like to assist with content updates if needed.

Thank you.

**Comment by Justinha** [comment]
@e0i no updates are required. Here is more info from engineering:
There is no WDAG dependency on WPAD and it can be turned of. 
On 1709 or 1803, WPAD can be disabled for the User in UI: “Settings > Network & Internet > Proxy > Automatically detect settings (turn it off).” 
However, the registry key doesn’t exist on 1803 and below, and there isn’t an easy way to disable it for System Accounts.

WinHTTP Web Proxy Auto-Discovery Service is required for Windows in general. It's not a requirement specifically for WDAG.

**Comment by e0i** [comment]
Closing as the original issue question has been answered.

**Comment by e0i** [comment]
@officedocsbot close
