### ISSUE TITLE
Clarfication for Account Deletion

### ISSUE THREAD

**Issue by Still34** [MicrosoftDocs/windows-itpro-docs#2967]
In the docs, it is noted that...

```
When a PC is set up in shared PC mode with the default deletion policy, accounts will be cached automatically until disk space is low. 
...
Any accounts created through Guest and Kiosk will also be deleted automatically at sign out.
```

In the first sentence, it notes that the accounts are cached, then the latter sentences mention how guest accounts are deleted upon sign out. Does that mean by default the guest accounts are cached or not? And isn't the default deletion policy "delete immediately"? This seems contradicting, or at the very least, unclear. 

Additionally, after I've deployed computers using the default deletion policy and after signing in and signing out as a guest user, the user's profile remains under `C:\Users` - is this the intended behaviour? 

EDIT: Discovered why, `AccountManagement` was set to `false`. Though I feel like clarification could be made in the paragraph, still.

EDIT2: That still doesn't fix it for me 🙃, accounts are still there and remain disabled with each signin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14b376e2-39bd-faca-a76c-dd21bad8d8fd
* Version Independent ID: a76cabb0-59b9-7e97-6603-eec7d37f1fd4
* Content: [Set up a shared or guest PC with Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/set-up-shared-or-guest-pc#feedback)
* Content Source: [windows/configuration/set-up-shared-or-guest-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/set-up-shared-or-guest-pc.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@Still34 I'll need to get clarification from the product group, I'll get back to you when I have more information, thanks!

**Comment by Still34** [comment]
Excuse me, could I get an ETA on this? Thanks!

**Comment by jdeckerms** [comment]
@Still34 I don't have an answer yet, I'll post here as soon as I do.

**Comment by jdeckerms** [comment]
@Still34 In the bullet that you asked about, it specifies that the caching under default deletion is for Active Directory and Azure AD accounts: "Both Azure AD and Active Directory domain accounts are managed in this way. Any accounts created through Guest and Kiosk will also be deleted automatically at sign out." (I don't think the "also" helps with clarity, I'll get that removed)

If the feature isn't working correctly for you (guest accounts not being deleted), you should notify the product team via the Feedback Hub, and/or contact Microsoft Support for assistance (https://support.microsoft.com/en-us/contactus/).
