### ISSUE TITLE
Как быть с Windows 10 home?

### ISSUE THREAD

**Issue by Fixlix** [MicrosoftDocs/windows-itpro-docs#2971]
У меня windows 10 home.
Начну с того что тут по умолчанию вообще нет настройки групповой политики.
Получается я ни одной виртуальной машины что ли теперь не могу запустить?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Управление Credential Guard в Защитнике Windows (Windows 10)](https://docs.microsoft.com/ru-ru/windows/security/identity-protection/credential-guard/credential-guard-manage#feedback)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by illfated** [comment]
As far as I know, Windows 10 Home does not have native support for Virtual Machines because it does not support or include Microsoft Hyper-V.
For some, upgrading from Home to Pro may not include Microsoft Hyper-V as well.
https://answers.microsoft.com/en-us/windows/forum/all/virtual-machine-in-windows-10-home/593d2c19-fae2-4091-92c9-6abb30f071db

in Russian, via Google Translate:
Насколько я знаю, Windows 10 Home не имеет встроенной поддержки виртуальных машин, потому что она не поддерживает или не включает Microsoft Hyper-V.
Для некоторых обновление с Home на Pro также может не включать Microsoft Hyper-V.

**Comment by Fixlix** [comment]
Мне не нужен hyper-v. Допустим даже если я хочу запустить обычную виртуальную машину, без поддержки hyper-v, то все равно получаю эту ошибку. Это не правильно! Получается я не могу ни одно машины запустить...

**Comment by illfated** [comment]
Sorry that I cannot help you with this. I have not done any labs or work on Virtual Machines yet.
Unless you have got suggestions to change some of the documentation, I recommend that you report your problem to your local Microsoft Support or use the Microsoft Forum pages to get more help.
***
Извините, что я не могу помочь вам с этим. Я еще не проводил никаких лабораторных работ или работ на виртуальных машинах.
Если у вас нет предложений изменить какую-либо документацию, я рекомендую вам сообщить о своей проблеме в местную службу поддержки Microsoft или использовать страницы форума Microsoft для получения дополнительной помощи.

**Comment by Fixlix** [comment]
Спасибо за попытку помочь! Дальше я и правда попробую задать вопрос на форумах

**Comment by illfated** [comment]
You are very welcome, especially if you come across typos or factual errors. 😃
@mypil : Please close this issue, the problem will be resolved in a different forum.
***
Добро пожаловать, особенно если вы сталкиваетесь с опечатками или фактическими ошибками. 😃
@mypil: Пожалуйста, закройте эту проблему, проблема будет решена на другом форуме.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@illfated - this is noted. I will proceed to close this then. Thank you for your assistance with this.

**Comment by mypil** [comment]
@officedocsbot close
