### ISSUE TITLE
Table 1 should be updated to reflect Windows 10 SAC-T changes

### ISSUE THREAD

**Issue by mkesler80** [MicrosoftDocs/windows-itpro-docs#2972]
Table 1 shows that the Targeted deployment ring should use the Semi-Annual Channel(Targeted) Servicing Channel.  [With SAC-T being retired](https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/Windows-Update-for-Business-and-the-retirement-of-SAC-T/ba-p/339523) this table should be updated to reflect that.

**Comment by illfated** [comment]
Thank you for referencing the Microsoft source for your statement. Which page & table are you referring to?
- https://docs.microsoft.com/en-us/windows/deployment/update/wufb-onboard
- https://docs.microsoft.com/en-us/windows/deployment/update/wufb-autoupdate
- https://docs.microsoft.com/en-us/windows/deployment/update/wufb-manageupdate
- https://docs.microsoft.com/en-us/windows/deployment/update/waas-manage-updates-wufb
- https://docs.microsoft.com/en-us/windows/deployment/update/wufb-basics
- https://docs.microsoft.com/en-us/windows/deployment/update/waas-configure-wufb

(Maybe you could post the request in the #Feedback section of the relevant page.)

**Comment by mkesler80** [comment]
Apologies, the link to view on Github took me to issues filtered by this id a5c45e00-23cc-8f0d-334d-45d8796e5220

I assumed that I was linked to the file and not just the root of the docs site.  I'll leave feedback on the article.
