### ISSUE TITLE
Add details on new suppression rule capabilities

### ISSUE THREAD

**Issue by markwoMSFT** [MicrosoftDocs/windows-itpro-docs#2974]
It would be good to add documenation or the file name, hash and file path suppression rules that were added to the portal.
It's covered inthis blog post:
https://techcommunity.microsoft.com/t5/Windows-Defender-ATP/What-s-new-in-the-WDATP-Portal-June-6th-2017/ba-p/104099

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 578a2a0c-d8ec-de9f-0a2a-450d1087ecf7
* Version Independent ID: 14b80f24-ed8e-9b63-d3f6-85852467b679
* Content: [Manage Windows Defender Advanced Threat Protection alerts](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/manage-alerts-windows-defender-advanced-threat-protection#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-atp/manage-alerts-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/manage-alerts-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@markwoMSFT - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
