### ISSUE TITLE
IConfigServiceProvider2 - removed from Windows SDK?

### ISSUE THREAD

**Issue by vpopescu** [MicrosoftDocs/windows-itpro-docs#298]
It appears the header file containing the definition for IConfigServiceProvider2 (cmgrcsp.h) has been removed from the Windows SDK. Does that indicate it will be contained in a separate SDK, deprecated, or... ?

**Comment by nickbrower** [comment]
This appears to be an issue with the Windows SDK, and not directly related to documentation.  Please report your issue with the [Feedback Hub](https://www.microsoft.com/en-us/store/p/feedback-hub/9nblggh4r32n) under the "Developer Platform" category for further assistance.
