### ISSUE TITLE
formatting issue

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/windows-itpro-docs#2982]
Step 1-&gt;bullet point 3:
the word "syntax" should not become part of the PowerShell command. I can see that in other instances it is correctly the title of the frame but here it is actually leaked to the body of the frame.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt#feedback)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Good catch, thanks for locating the cause of that issue.
HTML source snippet from https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt
```
<li>In an elevated Windows PowerShell prompt (run as Administrator), run the following commands and press <strong>Enter</strong> after each command:
--
  | <code>syntax
  | Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force
  | Set-Location C:\Setup\Scripts
  | .\Set-OUPermissions.ps1 -Account MDT_JD
  | -TargetOU &quot;OU=Workstations,OU=Computers,OU=Contoso&quot;</code></li>
```
Github Flavored Markdown snippet from https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md
```markdown
3.  In an elevated Windows PowerShell prompt (run as Administrator), run the following commands and press **Enter** after each command:
    ``` syntax
    Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force
    Set-Location C:\Setup\Scripts
    .\Set-OUPermissions.ps1 -Account MDT_JD 
    -TargetOU "OU=Workstations,OU=Computers,OU=Contoso"
    ```
```


I wonder if I should make a PR to rectify this to replace the (in this situation) impractical keyword `syntax`
- https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L5588-L5611

with `powershell` or one of its aliases:
- https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3794-L3799
(I have not seen much relevant color highlighting for PowerShell yet, but at least it is one of the valid keywords.)

**Comment by illfated** [comment]
BTW, I could be wrong, but it looks like the last 2 lines in the PS script belong to the same line.
```posh
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force
Set-Location C:\Setup\Scripts
.\Set-OUPermissions.ps1 -Account MDT_JD -TargetOU "OU=Workstations,OU=Computers,OU=Contoso"
```
