### ISSUE TITLE
delivery optimization windows update MPLS traffic gets chocked 

### ISSUE THREAD

**Issue by biren1234** [MicrosoftDocs/windows-itpro-docs#2987]
we have our Two site which connected through the MPLS connection 
both site have two different WSUS Server for update client take update for their respective server 

now issue is client taking update peer to peer which is called (delivery optimization windows update), client PC taking update different site client PC due to this our MPLS traffic gets chocked due to this user having problem HO connectivity too much slow

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@biren1234 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
