### ISSUE TITLE
Error in PreventInstallationOfDevicesNotDescribedByOtherPolicySettings Example

### ISSUE THREAD

**Issue by haydnbyrne** [MicrosoftDocs/windows-itpro-docs#2988]
Under the PreventInstallationOfDevicesNotDescribedByOtherPolicySettings section, the Example SyncML and the screenshot of the example Intune Custom policy both have an error. The LOCURI and OMA-URI are set to "./Device/Vendor/MSFT/Policy/Config/PreventInstallationOfDevicesNotDescribedByOtherPolicySettings" but should be "./Device/Vendor/MSFT/Policy/Config/DeviceInstallation/PreventInstallationOfDevicesNotDescribedByOtherPolicySettings"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c30e8535-b5d1-da85-117d-bcfd78c7e826
* Version Independent ID: 6189b9b2-f3ff-8ad0-1963-66c93bb061b1
* Content: [Policy CSP - DeviceInstallation](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-deviceinstallation#deviceinstallation-preventinstallationofdevicesnotdescribedbyotherpolicysettings)
* Content Source: [windows/client-management/mdm/policy-csp-deviceinstallation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-deviceinstallation.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by illfated** [comment]
Quite so, it even says exactly that in the precursor "**DeviceInstallation policies**" on top of the page:
> DeviceInstallation/AllowInstallationOfMatchingDeviceIDs
DeviceInstallation/AllowInstallationOfMatchingDeviceSetupClasses
DeviceInstallation/PreventDeviceMetadataFromNetwork
DeviceInstallation/PreventInstallationOfDevicesNotDescribedByOtherPolicySettings
DeviceInstallation/PreventInstallationOfMatchingDeviceIDs
DeviceInstallation/PreventInstallationOfMatchingDeviceSetupClasses

All the other SyncML samples on that page use the correct path `<LocURI>./Device/Vendor/MSFT/Policy/Config/DeviceInstallation/` as their path to the key.
This is also documented in https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-configuration-service-provider (**Policy CSP**).

I will open a PR to request the correction, although I am uncertain if this omission has spread to other documents.
(Feel free to keep me updated if you find any other documents where this omission occurs.)

**Comment by mypil** [comment]
@officedocsbot assign @mypil
