### ISSUE TITLE
MIssing section header

### ISSUE THREAD

**Issue by mikerodrick** [MicrosoftDocs/windows-itpro-docs#2991]
The last policy setting is missing a section header...
"User Account Control: Virtualize file and registry write failures to per-user locations"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c137da7-0dee-f7cd-d7af-39df9b7c7d50
* Version Independent ID: 06e5ff89-9392-d259-e431-da13e6134be0
* Content: [User Account Control security policy settings (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/user-account-control-security-policy-settings#feedback)
* Content Source: [windows/security/identity-protection/user-account-control/user-account-control-security-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/user-account-control/user-account-control-security-policy-settings.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@mikerodrick  - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
