### ISSUE TITLE
Table 1 should be updated to reflect Windows 10 SAC-T changes

### ISSUE THREAD

**Issue by mkesler80** [MicrosoftDocs/windows-itpro-docs#2992]
Table 1 shows that the Targeted deployment ring should use the Semi-Annual Channel(Targeted) Servicing Channel. With SAC-T being retired ( https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/Windows-Update-for-Business-and-the-retirement-of-SAC-T/ba-p/339523 ) this table should be updated to reflect that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa00c00e-b9e4-9f11-b553-519e51fb9cd0
* Version Independent ID: a5c45e00-23cc-8f0d-334d-45d8796e5220
* Content: [Build deployment rings for Windows 10 updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-deployment-rings-windows-10-updates#feedback)
* Content Source: [windows/deployment/update/waas-deployment-rings-windows-10-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-deployment-rings-windows-10-updates.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Updates coming soon.

**Comment by illfated** [comment]
@mkesler80 : Thanks for posting again in the correct page. 👍
That makes it a lot easier to see the page you refer to for all of us.

**Comment by e0i** [comment]
@jaimeo Any updates with this issue?

**Comment by jaimeo** [comment]
We will be updating all of these references in conjunction with the forthcoming Semi-Annual Channel release. That date is not public yet.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@jaimeo Any further updates?

**Comment by jaimeo** [comment]
This work is underway.

**Comment by e0i** [comment]
@jaimeo Following up for updates.

**Comment by jaimeo** [comment]
PR is in review w/ SMEs.

**Comment by denisebmsft** [comment]
It looks like this issue has been resolved, so I'm closing this with kind regards.
