### ISSUE TITLE
Multiple OU

### ISSUE THREAD

**Issue by ml58158** [MicrosoftDocs/windows-itpro-docs#2993]
Is there a way to support multiple OUs ?

**Comment by jdeckerms** [comment]
@ml58158 What topic are you referring to? Could you provide a link? Thanks.

**Comment by illfated** [comment]
@ml58158 : I think your question fits better in one of the Microsoft Forums, like
- https://social.technet.microsoft.com/Forums/en-US/home
- https://answers.microsoft.com/en-us/

You could also try a Bing search & Google search to see which results gives you the most relevant hits:
- https://www.bing.com/search?q=Multiple+OU
- https://www.bing.com/search?q=Multiple+OU+site%3Amicrosoft.com
- https://www.google.com/search?q=Multiple+OU
- https://www.google.com/search?q=Multiple+OU+site:microsoft.com

**Comment by Justinha** [comment]
@illfated thanks for the suggestion and @ml58158 please re-open as needed with a link to the topic you want updated.
