### ISSUE TITLE
The 'H' is missing from 'whether' on SkipDeviceStatusPage and SkipUserStatusPage

### ISSUE THREAD

**Issue by KennyLogin** [MicrosoftDocs/windows-itpro-docs#2995]
As the title suggests, just a slight typo for those 2 settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 613a93fe-ef09-40aa-f088-a476c4de4214
* Version Independent ID: a9efe92b-dd9a-e4a3-9e99-cb16f5a1af11
* Content: [DMClient CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/dmclient-csp#feedback)
* Content Source: [windows/client-management/mdm/dmclient-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/dmclient-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by jdeckerms** [comment]
@KennyLogin Thanks for catching that, I'll get it fixed.
