### ISSUE TITLE
Incorrect information regarding SSU categorizations

### ISSUE THREAD

**Issue by CJRicard** [MicrosoftDocs/windows-itpro-docs#2999]
This statement is incorrect as SSUs were recategorized as security updates and should be available for synchronization in WSUS/SCCM:  The following link https://docs.microsoft.com/en-us/windows/deployment/update/waas-servicing-differences 
indicates that the Windows 10 SSU are not synchronized with WSUS:
“Servicing Stack Updates (SSU) are available for download from the Update Catalog and can be imported through WSUS, but will not be automatically synced.”

In addition, this article has a reference stating that "For more information on Servicing Stack Updates, please see this blog."  It appears the intended blog is not linked here, but should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a38a423b-1b80-21ff-fe10-9383c2227d7c
* Version Independent ID: ccca23b0-97e5-5f14-ee58-1eafed9e4615
* Content: [Servicing differences between Windows 10 and older operating systems](https://docs.microsoft.com/en-us/windows/deployment/update/waas-servicing-differences#feedback)
* Content Source: [windows/deployment/update/waas-servicing-differences.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-servicing-differences.md)
* Product: **w10**
* GitHub Login: @KarenSimWindows
* Microsoft Alias: **karensim**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@CJRicard  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@CJRicard  - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
