### ISSUE TITLE
BULK unenrollment

### ISSUE THREAD

**Issue by Neckross** [MicrosoftDocs/windows-itpro-docs#3001]
is that on roadmap?
not currently available for ADJ or HDJ.
For tenant to tenant Intune migrations, we see this becomes a manual individual disconnect/connect process for the device.
Any news on that topic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d8375f-a60e-dbad-453b-80c933249b1b
* Version Independent ID: 2b233d8a-6eda-ce21-9da5-6a2ccee81372
* Content: [Disconnecting from the management infrastructure (unenrollment)](https://docs.microsoft.com/en-us/windows/client-management/mdm/disconnecting-from-mdm-unenrollment)
* Content Source: [windows/client-management/mdm/disconnecting-from-mdm-unenrollment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/disconnecting-from-mdm-unenrollment.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Neckross - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
