### ISSUE TITLE
Does Cred guard and device guard supported in Azure PAAS and VMSS

### ISSUE THREAD

**Issue by infosecrk** [MicrosoftDocs/windows-itpro-docs#3006]
It would be great if we can have details regarding support for PAAS and VMSS servers.
Is it possible to enable secure boot in Azure IAAS VMs as it is requirement for cred guard and device guard. 
Does Azure VM Support UEFI booting ?
It would be great if we have deployment mechanisms for in Azure, like DSC or Policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#feedback)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by VLG17** [comment]
@infosecrk It's not possible at the moment, because we don't have Gen 2 IaaS VMs in Azure. The closest thing to that are the new DC-series VMs, but even those don't offer secure boot/UEFI booting.

**Comment by mypil** [comment]
@infosecrk - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
