### ISSUE TITLE
Set custom limit

### ISSUE THREAD

**Issue by JoelDiller** [MicrosoftDocs/windows-itpro-docs#3007]
It would be really nice if I could set the limit to whatever I want, rather than 50% being the only option.  I would love to set mine to 80% or 85% to increase battery lifespan, but also have plenty of juice left when I'm not around an outlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a767ea0-4095-7a35-3828-4b3a17a0ea26
* Version Independent ID: 4ca4088c-1e98-c725-d46b-94cecfa123f2
* Content: [Battery Limit setting (Surface)](https://docs.microsoft.com/en-us/surface/battery-limit#feedback)
* Content Source: [devices/surface/battery-limit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/battery-limit.md)
* Product: **w10**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@JoelDiller That would be useful information for the product team to be aware of, would you suggest it in the Feedback Hub? Thanks!

**Comment by JoelDiller** [comment]
@jdeckerms Yep, sorry.  Realized I posted in the wrong place soon after I posted.  Thanks.
