### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by bangiebindy** [MicrosoftDocs/windows-itpro-docs#3009]
This SyncML does not work.  Looking at the PolicyManager registry keys on my 1809 device, WindowsSecurityAuditing does not appear in the defaults.  I understand that it may not be designed to show up there (similar to Firewall and AppLocker) but generally speaking, the defaults not showing up in the PolicyManager registry keys means that the policy is not supported on the OS version.  This article states that the policy is available on 1511.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09bbdaca-6d71-b6e7-2a98-b655d6226bed
* Version Independent ID: 5511fc3b-e6fb-feba-0898-a227d1945058
* Content: [WindowsSecurityAuditing CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/windowssecurityauditing-csp#feedback)
* Content Source: [windows/client-management/mdm/windowssecurityauditing-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/windowssecurityauditing-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@bangiebindy  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by TokyoScarab** [comment]
Hello @bangiebindy !  Thanks for bringing this up.  Would you be able to tell me more about the device you were running this on?  I'm unable to provide further assistance without a little more information on the device and the method you used.  Thanks!

**Comment by bangiebindy** [comment]
Hello - here is some info about my PC:

Edition: Windows 10 Enterprise
Version: 1809
Installed on: 11/14/2018
OS Build: 17763.379

We are using MDM policies in place of group policies for all of our Windows 10 PCs.  Hence why I am familiar with the PolicyManager registry keys.  I attempted to push this particular policy.  The policy failed every time.  To further verify I performed the following actions:

1. Reviewed the MDM Diagnostics Report on my PC
2. Check the PolicyManager registry keys for a default policy setting
3. I opened the command prompt and typed auditpol /get /category:* to further verify that no settings were applied.  

Here is the syncml that I attempted to apply:


  <Replace>
    <CmdID>1</CmdID>
    <Item>
      <Target>
        <LocURI>
            ./Vendor/MSFT/WindowsSecurityAuditing/ConfigurationSettings/EnableSecurityAuditing
          </LocURI>
      </Target>
      <Meta>
        <Format xmlns="syncml:metinf">bool</Format>
        <Type>text/plain</Type>
      </Meta>
      <Data>true</Data>
    </Item>
  </Replace>

**Comment by TokyoScarab** [comment]
@bangiebindy After doing some digging and testing, I have found something that should be helpful.  At least according to the information you provided, I don't believe that would work on your set up.  If you consult the CSP reference page [here](https://docs.microsoft.com/windows/client-management/mdm/configuration-service-provider-reference), it seems that the WindowsSecurityAuditing CSP isn't yet supported for Windows 10 Enterprise unless that version is Mobile or Mobile Enterprise. I will update the document to point out this page and make it clear on the wording.  If you have any other questions, I would be happy to answer them.  If you have questions that are more support type questions about getting this up and running on your machines, I would suggest visiting [Microsoft Support](https://support.microsoft.com) as we only handle the updating of the documentation here.  If you do find that it is a documentation error though, feel free to comment back and we'll gladly look into fixing it. Thanks!

**Comment by mypil** [comment]
@bangiebindy - From our understanding, the issue you raised has been answered by TokyoScarab. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by bangiebindy** [comment]
Thank you!  That makes sense now.  It is now clear that the policy is not supported on Windows 10 Enterprise.
