### ISSUE TITLE
How to identify which TPM 2.0 PCR Bank is being used

### ISSUE THREAD

**Issue by alrosado** [MicrosoftDocs/windows-itpro-docs#3012]
On https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/switch-pcr-banks-on-tpm-2-0-devices, there is no documented way to identify which PCR Bank is being used. For example, if you have a TPM 2.0 machine with SHA-1 and SHA-256 PCR Banks, it would be good to document how you can identify which one is being used.

Example text:

### How can I identify which PCR bank is being used?

You can identify which PCR bank is currently used by Windows by looking at the registry.

**Registry information**

Registry key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\IntegrityServices

DWORD: TPMActivePCRBanks

Defines which PCR banks are currently active

Registry key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\IntegrityServices

DWORD: TPMDigestAlgID

Algorithm ID of the PCR bank that Windows is currently using. (For the full list of supported algorithms, see the [TCG Algorithm Registry](https://trustedcomputinggroup.org/resource/tcg-algorithm-registry/).)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@alrosado  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by Justinha** [comment]
@alrosado Thanks for the suggestion. We've shared this with our engineering team. We will follow up on the best way to document this missing info.

**Comment by mypil** [comment]
@alrosado - We would like to follow up. Can you please respond to the query of Justinha? Thank you.

**Comment by alrosado** [comment]
The issue I have is I am being asked how to identify if TPM 2.0 is using SHA 256 and nowhere in the documentation does it specify how to query that.

**Comment by Justinha** [comment]
@alrosado I see, thanks. Can you share any more about your scenario? This issue is shared with engineering so any info you can provide to help understand the business scenario should help. 
@mypil we will need some time to consider this request because it depends on input and resources from multiple teams.

**Comment by mypil** [comment]
@alrosado - We would like to follow up. Can you please respond to the question of Justinha? Thank you.

**Comment by mypil** [comment]
@alrosado - Do you have any updates on this?

**Comment by alrosado** [comment]
My customer has taken the security posture that they want to eliminate the use of SHA1 as much as possible. My customer has over a million Windows 10 machines distributed across the globe and dozens of different models/manufacturers. 

Originally my customer was under the assumption that if a Windows 10 machine was using a TPM 2.0 chip, that would automatically mean that the TPM chip is using SHA256. However, this is not the case. After doing some extensive research, it turns out that the TPM 2.0 specification allows for different algorithms to be used. We also found that this registry key indicated whether the TPM chip was using SHA256 or SHA1. However, this registry key is not documented anywhere on Windows docs to show that it determines what algorithm is being used.

**Comment by RonaldAi** [comment]
@Justinha and @alrosado: how about this language?

### How can I identify which PCR bank is being used?

A TPM can be configured to have multiple PCR banks active. When BIOS is performing measurements it will do so into all active PCR banks, depending on its capability to make these measurements. BIOS may chose to deactivate PCR banks that it does not support or "cap" PCR banks that it does not support by extending a separator. The following registry value identifies which PCR banks are active.

Registry key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\IntegrityServices

DWORD: TPMActivePCRBanks

Defines which PCR banks are currently active, This is a bitmap defined in the TCG Algorithm Registry.

Windows checks which PCR banks are active and supported by the BIOS. Windows also checks if the measured boot log supports measurements for all active PCR banks. Windows will prefer the use of the SHA-256 bank for measurements and will fallback to SHA1 PCR bank if one of the pre-conditions is not met.

You can identify which PCR bank is currently used by Windows by looking at the registry.

Registry information

Registry key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\IntegrityServices

DWORD: TPMDigestAlgID

Algorithm ID of the PCR bank that Windows is currently using. (For the full list of supported algorithms, see the TCG Algorithm Registry.)

Windows only uses one PCR bank to continue boot measurements. All other active PCR banks will be extended with a separator to indicate that they are not used by Windows and measurements that appear to be from Windows should not be trusted.

**Comment by Justinha** [comment]
@alrosado @RonaldAi @mypil Thanks for the contribution!

**Comment by mypil** [comment]
@alrosado - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
