### ISSUE TITLE
BitLocker CSP

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#3013]
Hello,
Is it possible to integrate "OSEnablePrebootInputProtectorsOnSlates" ?
Surface Pro devices cannot be encrypted if this option is off in Group Policy, because display keyboard cannot be loaded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a05802f-9d0f-9aeb-3c8e-8b92f1284202
* Version Independent ID: 1fd9efc2-8946-75e4-27f3-95ac43a9d987
* Content: [BitLocker CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp)
* Content Source: [windows/client-management/mdm/bitlocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/bitlocker-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by joinimran** [comment]
@lightupdifire Can you please share some more details what exactly you are looking for. Do you want to enable this policy with BitLocker?

**Comment by lightupdifire** [comment]
@joinimran Yes, because if this policy is not enabled, the Windows Recovery Environment must be enabled on tablets to support the entry of the BitLocker recovery password. When the Windows Recovery Environment is not enabled and this policy is not enabled, you cannot turn on BitLocker on a device that uses the Windows touch keyboard.
So we cannot turn on encryption on tablets if this is disabled or not configured.

**Comment by joinimran** [comment]
@lightupdifire Thanks for sharing the details. So what I understand is that you are looking for this feature to get integrated with Bitlocker CSP? So that this can be enabled when you are going to encrypt a device which is using Windows touch keyboard. Am I getting this correct?

**Comment by lightupdifire** [comment]
@joinimran Yes, I also opened "Product feedback" too. 
Else, if you buy tablet, you try encrypt your hard disk using Intune Endpoint profile or custom policy or manually via computer, you have error, and we need guide user how to enable this option "OSEnablePrebootInputProtectorsOnSlates" via local GPO or use PowerShell script via Intune.. but we try avoid using PS in our environment.

**Comment by mypil** [comment]
@lightupdifire - Thank you for submitting feedback.

From our understanding, the issue has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by lightupdifire** [comment]
@mypil, Not sure what you mean "issue has been answered by joinimran", so far I got only questions :)

**Comment by mypil** [comment]
@lightupdifire - Thank you for your response. Is there something within this article that you suggest to be added or edited? If yes, please share the appropriate text and where it should be placed, so we can have @joinimran create a Pull Request to get it added.

Otherwise, if your issue is more of a feature request then for user feedback on product feature requests, you can submit via User Voice - **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**.

Please understand that this site is a product documentation site and not a support nor a feature request site. I hope this gets you pointed in the right direction. Thank you.

**Comment by mypil** [comment]
@lightupdifire - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
