### ISSUE TITLE
Windows Analytics uninstallation

### ISSUE THREAD

**Issue by Kofl** [MicrosoftDocs/windows-itpro-docs#3015]
Hello,

how can the Windows Analytics client be uninstalled or disabled on the clients?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Kofl - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by Kofl** [comment]
Sorry, but that wont help out. Windows Anlaytics is no software which can be uninstalled by a default way for Windows 10. If you have a look at the installation script, uninstall can only be provied by the product team of Windows Anlaytics.

**Comment by mypil** [comment]
@officedocsbot open

**Comment by mypil** [comment]
@officedocsbot open

**Comment by mypil** [comment]
@Kofl - May we know which Microsoft document link you used in reference to this issue? Please share it with us so we can investigate further. Thank you.

**Comment by Kofl** [comment]
Hi,

 https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10 wont help on uninstalling the software. We need a script from the product team to clean out the changes to disable Windows Anlaytics.

**Comment by mypil** [comment]
@Kofl - Sorry to hear that you are having issues. Please understand that this site is a product documentation site and not a support nor a feature request site.

As such, the feedback section here is intended for feedback that improves the content in the Microsoft documentation and not intended for user feedback on product features nor troubleshooting.

So, with this said, what is the Microsoft article that you are referring to? Can you please share the link so we can have it investigated? 

Thank you.

**Comment by Kofl** [comment]
Sure, thats clear. The documentation is missing how to uninstall/disable Windows analytics, its not mentioned under the FAQs https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-faq-troubleshooting nor mentioned elsewhere.
A complete documentation should could installation AND uninstallation/disabling of the service.

**Comment by mypil** [comment]
@jaimeo - We need your insights on this issue. Do you have any information that we can share with @Kofl to answer his query?

Thank you.

**Comment by mypil** [comment]
@AndreaBarr - please assist to re-open this issue. thank you.

**Comment by jaimeo** [comment]
Is this not what you're looking for? https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-faq-troubleshooting#disable-upgrade-readiness

**Comment by mypil** [comment]
@Kofl - kindly check on the response and confirm if the link shared by jaimeo helps to resolve your issue. Thank you.

**Comment by Kofl** [comment]
Thanks, that clarified it. The confusing part is " Disable Upgrade Readiness" and "Enrolling" for the installation.

**Comment by mypil** [comment]
@Kofl - Is there something within this article that you suggest to be added or edited? 

If yes, please share the appropriate text and where it should be placed, so that a Pull Request can be created to get it added. Thank you!

**Comment by Kofl** [comment]
I think we can stick to the original text, thanks for asking.
