### ISSUE TITLE
Recommendation still valid?

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#3026]
The article states the following:

> We recommend that you install the 32-bit version of Microsoft Office for both 32-bit and 64-bit operating systems.

This seems to be outdated, since Microsoft has moved to 64 bit as the default. https://support.office.com/en-us/article/choose-between-the-64-bit-or-32-bit-version-of-office-2dee7807-8f95-4d0c-b5fe-6c6f49b8d261?ui=en-US&rs=en-US&ad=US#32or64Bit=Newer_Versions

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca28e71-fc3b-e587-4147-3159e1341673
* Version Independent ID: c97ec5b6-9d95-14cf-649d-57922599dbfd
* Content: [Microsoft User Experience Virtualization (UE-V) 2.0 Release Notes](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/uev-v2/microsoft-user-experience-virtualization--ue-v--20-release-notesuevv2)
* Content Source: [mdop/uev-v2/microsoft-user-experience-virtualization--ue-v--20-release-notesuevv2.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/uev-v2/microsoft-user-experience-virtualization--ue-v--20-release-notesuevv2.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by j0rt3g4** [comment]
This issue have been solved at #3036

**Comment by TokyoScarab** [comment]
Thank you for pointing this out!  This change will be updated in the documentation

**Comment by mypil** [comment]
@alexverboon - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
