### ISSUE TITLE
Broken Hyperlinks

### ISSUE THREAD

**Issue by sympleconfigmgr** [MicrosoftDocs/windows-itpro-docs#3027]
In the Secure Boot section, both Microsoft hyperlinks appear to be broken. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c795c8ef-7caf-b8a7-4118-b00b1899eef8
* Version Independent ID: cd85b6b4-d160-0c44-15ea-4b7c02fbe0eb
* Content: [Secure the Windows 10 boot process](https://docs.microsoft.com/en-us/windows/security/information-protection/secure-the-windows-10-boot-process)
* Content Source: [windows/security/information-protection/secure-the-windows-10-boot-process.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/secure-the-windows-10-boot-process.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
Thanks for flagging them. I think the Dashboard is now at https://partner.microsoft.com/en-us/dashboard and for the other link it would be more stable to link to dreamwidth.org rather than a specific page.

@mypil would you like to submit a PR or should I just do it from my side?

**Comment by mypil** [comment]
@Justinha - Sure, I can assign someone to create a PR for this.  Thanks.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@lindspea - please assist to create a PR for this issue. Thank you.

**Comment by lindspea** [comment]
@mypil @Justinha Thank you.  Will fix soonest.

**Comment by mypil** [comment]
@sympleconfigmgr - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by sympleconfigmgr** [comment]
Thank you all!

**Comment by mypil** [comment]
@officedocsbot close
