### ISSUE TITLE
Use default recovery message and URL.

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#3028]
Hello,
When setting up "1 = Use default recovery message and URL."
If go for this option, what should be set then in:
yy= & zz= ? Can use 0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a05802f-9d0f-9aeb-3c8e-8b92f1284202
* Version Independent ID: 1fd9efc2-8946-75e4-27f3-95ac43a9d987
* Content: [BitLocker CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp)
* Content Source: [windows/client-management/mdm/bitlocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/bitlocker-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@lightupdifire  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@lightupdifire If you go with "1 = Use default recovery message and URL.", you don't need to specify anything else, because you will be using the defaults.

The example listed in the article applies only for values "2" and "3", and in this case "yy" and "zz" will correspond to the custom recovery message and URL that you choose to display.

**Comment by lightupdifire** [comment]
@VLG17,
How then example will be?
Will it be:
<<<
<enabled/><data id="PrebootRecoveryInfoDropDown_Name" value="1"/><data id="RecoveryMessage_Input" value=""/><data id="RecoveryUrl_Input" value=""/>
>>>
Or simply first part?
<<<
<enabled/><data id="PrebootRecoveryInfoDropDown_Name" value="1"/>
>>>

**Comment by VLG17** [comment]
@lightupdifire just the first part. You don't need the second part, because value="1" implies that you will be using the default recovery message and URL.

**Comment by illfated** [comment]
@lightupdifire : if you want to include 1 line of code, you can either use the "insert code" button (looks like **`<>`** ) on the Github Write comment toolbar, or you could simply add 1 back tick ` before & after the code.

The formatting code is called [MarkDown](https://en.wikipedia.org/wiki/Markdown) (or even [Github Flavored MarkDown](https://github.github.com/gfm/)), which you can look up and learn more about for improved use of formatting text in Github comments.
If you need to include more lines than 1, consider using a "code block fence" made from 3 back ticks **```** , inserted on a blank line before & after the multi-line code you insert in your comment.
See also [**Markdown Cheatsheet**](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) by Adam Pritchard for easy reference.

**Comment by lightupdifire** [comment]
@illfated,
Thanks for help :) `<coding in life-time change coding>` :p

@VLG17,
Thanks for info, may be wise to make it clear in article?

**Comment by VLG17** [comment]
@lightupdifire i'll take care of updating the article to reflect this.

**Comment by mypil** [comment]
@lightupdifire - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
