### ISSUE TITLE
PowerShell example clarification

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/windows-itpro-docs#303]
Under "PowerShell example" section, the script line beginning with PsExec.exe contains an unmatched single quote near the end of my_powershell_script.ps1.  Is this a mistake?

PsExec.exe -accepteula -i -s cmd.exe /c powershell.exe my_powershell_script.ps1' >> %LOGFILE%

**Comment by eross-msft** [comment]
Thank you for taking the time to add this issue; however, I need to know the article in which it was found so I can route it to the proper person. Thank you!!

**Comment by Skatterbrainz** [comment]
I used the comment box at the bottom of the document.  I submit quite a few comments each week on different documents.  I assumed it was passing along the document references with the comments.  I have no way to know which document this was related to unless I search my browser history from October 6. :(  I will try.

**Comment by brianlic-msft** [comment]
@Skatterbrainz Unfortunately, it doesn't pass through the file name. Were you able to track this down?
