### ISSUE TITLE
ChangeProductKey

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#3041]
Hi there,
Can you provide an example of the changeproductkey setting introduced on 1703?

Im trying to use 

&lt;SyncML xmlns="SYNCML:SYNCML1.2"&gt;
  &lt;SyncBody&gt;
    &lt;Exec&gt;
    &lt;CmdID&gt;$CmdID$&lt;/CmdID&gt;
    &lt;Item&gt;
      &lt;Target&gt;
      &lt;LocURI&gt;./Device/Vendor/MSFT/WindowsLicensing/ChangeProductKey&lt;/LocURI&gt;
      &lt;/Target&gt;
      &lt;Meta&gt;
        &lt;Format xmlns="syncml:metinf"&gt;chr&lt;/Format&gt;
      &lt;/Meta&gt;
      &lt;Data&gt;xxxxx-xxxxx-xxxxx-xxxxx-xxxxx&lt;/Data&gt; 
    &lt;/Item&gt;
   &lt;/Exec&gt;
   &lt;Final/&gt;
  &lt;/SyncBody&gt;
&lt;/SyncML&gt;

But is coming back with an error 
(Syncml(405): The requested command is not allowed on the target.)

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b01a2e6-e105-d3b8-decc-4a26ee1abaf9
* Version Independent ID: 40b419f6-0a39-369d-1d76-5308eb77b202
* Content: [WindowsLicensing CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/windowslicensing-csp)
* Content Source: [windows/client-management/mdm/windowslicensing-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/windowslicensing-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@schenardie  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@schenardie Can you please confirm if you were trying to upgrade Windows 10 Pro to Windows 10 Enterprise? Currently, this is only applicable for edition upgrade from Windows 10 Pro to Windows 10 Enterprise. And the error code says that you are trying to write where you only have read permissions. Please see https://docs.microsoft.com/en-us/windows/client-management/mdm/oma-dm-protocol-support#syncml-response-status-codes to get more details about the error code.
Thanks.

**Comment by schenardie** [comment]
@joinimran Confirmed, was trying from Pro to Ent.

yeah i saw that page but i need more info then what is the right node to write to.

The 
<LocURI>./Device/Vendor/MSFT/WindowsLicensing/ChangeProductKey</LocURI>
is following the current documentation

**Comment by joinimran** [comment]
@schenardie Can you please try the following code. Please note this is already available in the doc with example name **UpgradeEditionWithProductKey**

<SyncML xmlns="SYNCML:SYNCML1.2">
  <SyncBody>
    <Exec>
    <CmdID>$CmdID$</CmdID>
    <Item>
      <Target>
        <LocURI>./Device/Vendor/MSFT/WindowsLicensing/UpgradeEditionWithProductKey</LocURI>
      </Target>
      <Meta>
        <Format xmlns="syncml:metinf">chr</Format>
      </Meta>
      <Data>XXXXX-XXXXX-XXXXX-XXXXX-XXXXX</Data> 
    </Item>
   </Exec>
   <Final/>
  </SyncBody>
</SyncML>

**Comment by mypil** [comment]
@schenardie - We would like to follow up with you. Can you please respond to the query of joinimran? Thanks.

**Comment by mypil** [comment]
@schenardie -  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by schenardie** [comment]
Sorry I didnt have time to get back to this until now.

I'd like to see an example of the string which goes into the custom CSP.
i've tried with the upgrade but its still not working

**Comment by mypil** [comment]
@officedocsbot reopen

**Comment by joinimran** [comment]
@schenardie , Please share screenshots where you are applying the settings and the error you are getting. Then I can better guide you on this. 

Thanks.

**Comment by mypil** [comment]
@schenardie - We will proceed to close this issue since we did not get any response from you. Please create a new issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by schenardie** [comment]
Custom CSP
Name: UpgradeEditionWithProductKey
Description: Not Configured
OMA-URI:./Device/Vendor/MSFT/WindowsLicensing/UpgradeEditionWithProductKey
Data Type: String
Value: `<SyncML xmlns="SYNCML:SYNCML1.2">
  <SyncBody>
    <Exec>
    <CmdID>1</CmdID>
    <Item>
      <Target> 
		<LocURI>./Device/Vendor/MSFT/WindowsLicensing/UpgradeEditionWithProductKey</LocURI>
      </Target>
      <Meta>
        <Format xmlns="syncml:metinf">chr</Format>
      </Meta>
      <Data>XXXXX-XXXXX-XXXXX-XXXXX-XXXXX</Data> 
    </Item>
   </Exec>
   <Final/>
  </SyncBody>
</SyncML>`

Get an error on the Device Configuration Policy as described before
-2016345707 (Syncml(405): The requested command is not allowed on the target.)

**Comment by schenardie** [comment]
@officedocsbot reopen

**Comment by mypil** [comment]
@officedocsbot reopen

**Comment by mypil** [comment]
@joinimran - please assist with this. Thanks.

**Comment by joinimran** [comment]
@schenardie Can you please confirm that you are not using the VL key for upgradation?

**Comment by schenardie** [comment]
Hi joinimran 
Im not sure which kind of key is that.  Im testing with the key provided on our Microsoft Action Pack.

If i use the same key deploying with the Edition upgrade and mode switch Profile it works so im not sure is a key problem.

I think is more about getting the Custom CSP Right.

**Comment by joinimran** [comment]
@schenardie Thank you for sharing this info. It looks like you need to open a support case with Microsoft technical support team as Microsoft Action Packs keys are a volume license keys as you can use those keys with multiple machines. As of now, CSP doesn't support volume license keys. 

Please see other methods for upgradation if required at https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-edition-upgrades#upgrade-using-a-command-line-tool

@mypil Please guide @schenardie to open a support case with Technical support team.

Thanks.

**Comment by schenardie** [comment]
Hi  Joininram,

Can you explain to me how does the same key work if i use it in the Edition Upgrade profile instead of the Custom one??  Thanks

**Comment by joinimran** [comment]
@schenardie Your query can better be answered by Microsoft technical support team. The tech support team can better route you to the concerned team at Microsoft and they will better help you creating custom CSP and will surely your all queries. If required, they will surely update the document or request the doc team (Me) to update the content of doc.

Thanks.

**Comment by mypil** [comment]
@officedocsbot close
