### ISSUE TITLE
Wrong event description in the documentation

### ISSUE THREAD

**Issue by mhale1982** [MicrosoftDocs/windows-itpro-docs#3043]
The error hex codes look to be wrong. 

0x1b is 27, which in the RFC is:

   KDC_ERR_MUST_USE_USER2USER            27  Server principal valid for
                                               user2user only

The documentation, however, is it listed as:

0x1B | KDC_ERR_SVC_UNAVAILABLE | KDC is unavailable | No information.

https://tools.ietf.org/html/rfc4120#section-5.9.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b88b81e4-6524-2c4e-fb58-bee2887b62d9
* Version Independent ID: 16ca6708-358b-21f8-2623-76f2651cc80c
* Content: [4769(S, F) A Kerberos service ticket was requested. (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4769#feedback)
* Content Source: [windows/security/threat-protection/auditing/event-4769.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/event-4769.md)
* Product: **w10**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@mhale1982  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@mhale1982 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
