### ISSUE TITLE
Office 2019

### ISSUE THREAD

**Issue by dotraphael** [MicrosoftDocs/windows-itpro-docs#3048]
please, add a Office 2019 baseline tool. currently the baseline is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 014ca19c-6ab8-6eec-321e-72fa22c8f2c3
* Version Independent ID: 948a95a8-cb4f-668a-1988-17830d51845b
* Content: [Microsoft Security Compliance Toolkit 1.0](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-compliance-toolkit-10)
* Content Source: [windows/security/threat-protection/security-compliance-toolkit-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-compliance-toolkit-10.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **sagaudre**

**Comment by Justinha** [comment]
Thanks for the feedback. There isn't an Office 2019 baseline yet, but we'll update the docs after one is added to the download package.
