### ISSUE TITLE
Update doc with latest information

### ISSUE THREAD

**Issue by dotraphael** [MicrosoftDocs/windows-itpro-docs#3049]
the current doc does not have the information for Azure RMS. it also has the information to Show the Personal option in the File ownership menus of File Explorer and the Save As dialog box that is not available on latest version of SCCM (1810 at the moment). 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4043626d-5475-cd46-e107-6077ff4701f7
* Version Independent ID: 59ffa7ff-97ca-2f34-3c92-a09ab10c0a4e
* Content: [Create and deploy a Windows Information Protection (WIP) policy using System Center Configuration Manager (Windows 10)](https://docs.microsoft.com/en-gb/windows/security/information-protection/windows-information-protection/create-wip-policy-using-sccm)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-sccm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/create-wip-policy-using-sccm.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@dotraphael  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Hi @dotraphael  specifically what is the missing part of the documentation that you want to be added? because I don't see any way to update that info without doing the whole implementation.

**Comment by TokyoScarab** [comment]
Yes, @dotraphael , if you comment back and elaborate a little more on what you think is missing, we can better assist you.

**Comment by dotraphael** [comment]
Hi @TokyoScarab, updating the doc with latest info would be great and maybe some links to external content like RMS stuff. i don't expect a full re-write of the doc, but just the addition of whats new and remove of what is no longer applicable

**Comment by mypil** [comment]
@Justinha - I would like to get your insights on this issue. Can you please assist how we can proceed with this?

Thank you.

**Comment by Justinha** [comment]
@mypil I have a fix going out this afternoon. I updated all of the screenshots and removed the outdated option named Show the Personal option in the File ownership menus of File Explorer and the Save As dialog box.

**Comment by j0rt3g4** [comment]
@Justinha  @mypil  Yeah, the thing is that the issue is not clear in what the author expects from the documentation, he wants to get it to update but there's no reference at all on what he wants so a quick check would be useful when you have the time 👍  and thank you!

**Comment by mypil** [comment]
@dotraphael - From our understanding, the issue you raised has been answered by Justinha. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by Justinha** [comment]
@mypil I'll add a description for the RMS setting today.

**Comment by dotraphael** [comment]
@mypil great content thanks for updating. the only think missing now is the RMS stuff but i see @Justinha will be updating it. @Justinha, a link to a RMS documentation on how to set it up and how to get the RMS template GUID would be great as well :)

**Comment by mypil** [comment]
@Justinha - Do you have any updates on this? Thank you.

**Comment by Justinha** [comment]
@mypil yes a link to how to setup RMS with WIP appears now. I just added another link to the PS cmdlet to use to get the template ID. After that appears later today, this should be ready to close, and we can all ask for a raise :). Thanks to @dotraphael and everyone else for their help. It's great to get the SCCM steps updated.

**Comment by mypil** [comment]
@dotraphael - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
