### ISSUE TITLE
SCP for Device Registration Service

### ISSUE THREAD

**Issue by flippyboy** [MicrosoftDocs/windows-itpro-docs#3053]
There is no info in the guide about creating the Service Connection Point in AD for ADFS Device Registration Service. There is a mention about it in the planning guide (https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide#deployment-model) but nothing in this guide. When i followed the instructions, this wasn't added automatically when configuring DRS in ADFS. I did not get it to work before adding the SCP manually. If it should be added automatically, please add a guide for verifying it and for fixing it.
This script fixed it for me:
$enrollmentService = "enterpriseregistration.contoso.com" # Replace this with your Device Registration Service endpoint
$configNC = "CN=Configuration,DC=corp,DC=contoso,DC=org" # Replace this with your Active Directory configuration naming context
 
$de = New-Object System.DirectoryServices.DirectoryEntry
$de.Path = "LDAP://CN=Device Registration Configuration,CN=Services," + $configNC
 
$deSCP = $de.Children.Add("CN=62a0ff2e-97b9-4513-943f-0d221bd30080", "serviceConnectionPoint")
$deSCP.Properties["keywords"].Add("enterpriseDrsName:" + $enrollmentService)
 
$deSCP.CommitChanges()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b063e00b-84e5-9da7-2229-e0e24da3b877
* Version Independent ID: da9f4867-2aa3-aefa-1603-ddb2ab1ed624
* Content: [Prepare and Deploy Windows Server 2016 Active Directory Federation Services (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@flippyboy  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Added information on PR #3133

**Comment by mypil** [comment]
@flippyboy - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
