### ISSUE TITLE
"Applies to" section may be misleading

### ISSUE THREAD

**Issue by gaknigge** [MicrosoftDocs/windows-itpro-docs#3055]
This article indicates the content applies to Windows Defender Advanced Threat Protection (ATP), but the content may actually only apply to Windows Defender.
In my experience, Windows Defender exclusions, however they are created, are not used by ATP. See, for example, https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/defender-compatibility-windows-defender-advanced-threat-protection. "Windows Defender ATP does not adhere to the Windows Defender Antivirus Exclusions settings."
I think the Applies to link in this article should point to the Windows Defender product, and not to Windows Defender ATP. If my understanding is correct, then there are also articles in this section with the same Applies To reference, including the article at https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-process-opened-file-exclusions-windows-defender-antivirus/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c0eddd-98ca-1e7a-bddb-36c7037850fe
* Version Independent ID: 6afa98e8-a402-4ef9-2189-8ecc111c3dba
* Content: [Configure and validate exclusions based on extension, name, or location](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-extension-file-exclusions-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-extension-file-exclusions-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/configure-extension-file-exclusions-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@gaknigge  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
@mypil  I consider that the links are correct and no changes are required. Please confirm with the author.

**Comment by mypil** [comment]
@andreabichsel @Justinha - can you please share your insights on this issue? 

Thank you.

**Comment by Justinha** [comment]
@gaknigge Thanks you raise a great point. We've been using WD ATP as Applies to value for many Windows 10 security topics. Our goal is to present our security offerings as one comprehensive set of capabilities, all available with WD ATP and an E5 license, and we want the Applies to value to help reinforce that message. 
So we could add inline with the text that WD ATP does not support WDAV exclusions, and add the link. But we'd want to retain the Applies to as WD ATP for the reasons I mentioned. I hope that makes sense. 
@mypil can you assist with the change I suggested?

**Comment by j0rt3g4** [comment]
@justinha what is the links and where it should be pointed to? I'd need specifics so I can directly add the note to a pr.

**Comment by Justinha** [comment]
@j0rt3g4 I was thinking we could add what @gaknigge suggested in his comment:
Windows Defender exclusions, however they are created, are not used by ATP. See, for example, https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/defender-compatibility-windows-defender-advanced-threat-protection. "Windows Defender ATP does not adhere to the Windows Defender Antivirus Exclusions settings." 

I haven't looked where it might best to add it, but does it make sense?

**Comment by j0rt3g4** [comment]
Adding link on PR #3414

**Comment by mypil** [comment]
@gaknigge - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
