### ISSUE TITLE
Enable for everyone?

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/windows-itpro-docs#3058]
Is there a way to enable this feature org-wide? A reg key edit? A script we can run? It's not scaleable to manually enable this feature PC by PC, user by user. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 192c6282-8795-78d7-1b1f-c2e2fac833a0
* Version Independent ID: 653498e2-435b-519d-c198-94d8e74523da
* Content: [Set up and test Cortana with Office 365 in your organization (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/cortana-at-work/cortana-at-work-o365)
* Content Source: [windows/configuration/cortana-at-work/cortana-at-work-o365.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/cortana-at-work/cortana-at-work-o365.md)
* Product: **w10**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@pyoungberg - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@pyoungberg keeping in mind the prerequisites and the fact that you need to input your Office 365 credentials, bulk enablement would lead to, in my opinion, a potential attack vector.

Nevertheless, please share this feedback on the official channel for Cortana: https://cortana.uservoice.com/forums/249009-general-cortana-feedback

**Comment by mypil** [comment]
@pyoungberg - From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
