### ISSUE TITLE
Incorrect Information

### ISSUE THREAD

**Issue by haselton** [MicrosoftDocs/windows-itpro-docs#3059]
The following information is incorrect:

&gt;If this bit is set, then a cross-forest trust to a domain is to be treated as an external trust for the purposes of SID Filtering. Cross-forest trusts are more stringently filtered than external trusts. This attribute relaxes those cross-forest trusts to be equivalent to external trusts. For more information on how each trust type is filtered, see [MS-PAC] section 4.1.2.2.

There is nothing in [MS-PAC] section 4.1.2.2 to indicate that cross-forest trusts are more stringently filtered than external trusts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2087986-5e1b-bf86-099a-5511f527a3a9
* Version Independent ID: 65196e47-4d59-f510-f486-63f2ef9bf963
* Content: [4716(S) Trusted domain information was modified. (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4716)
* Content Source: [windows/security/threat-protection/auditing/event-4716.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/event-4716.md)
* Product: **w10**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@haselton - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by Jcoetsee** [comment]
@Justinha Can you please see the information above. Is there another section/article that has the information that is being requested and as stated is not available in the above article/reference?

**Comment by Justinha** [comment]
@Jcoetsee Thanks for raising this. Unfortunately I cannot confirm with the original author. I think the stringent filtering reference is to SID filtering for forest trust, which is enabled by default to help prevent SID history attacks. There is a great explanation from an AD MVP at https://blogs.msmvps.com/acefekay/2016/11/02/active-directory-trusts/ 

Does that make sense?

**Comment by Jcoetsee** [comment]
@haselton Does the above reference help answer the question for you?

**Comment by Jcoetsee** [comment]
@hasleton based on the article mentioned above, would you review it and see if there is valid information in there and let me know if there is a piece in that blog article you would want to consider adding to the original article if it answers the question you had?

**Comment by haselton** [comment]
@Jcoetsee I will do so…give me a day or two to review the article

**Comment by haselton** [comment]
@Jcoetsee and @Justinha The article referenced has information about SID filtering, but nothing that supports the claim that the forest-trust filtering is more stringent than an external trust.

**Comment by Justinha** [comment]
@haselton are you referring to the MVP article or [MS-PAC] section 4.1.2.2? My understanding is SID filtering is more stringent filtering than without it. Maybe I'm misunderstanding your feedback. What change do you want to see made to this topic specifically?

**Comment by Jcoetsee** [comment]
@haselton please see the above response.

**Comment by haselton** [comment]
@Justinha To the MVP article you referenced; it contains information about trusts and SID filtering.  It doesn't say that SID filtering for forest trusts is more stringent than SID filtering for external trusts.

From the original post:

> >If this bit is set, then a cross-forest trust to a domain is to be treated as an external trust for the purposes of SID Filtering. **Cross-forest trusts are more stringently filtered than external trusts.** **This attribute relaxes those cross-forest trusts to be equivalent to external trusts**. For more information on how each trust type is filtered, see [MS-PAC] section 4.1.2.2.

From: https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/event-4716.md

[MS-PAC] section 4.1.2.2 contains detailed information about SID filtering and how it works, but nothing that supports the Microsoft Docs statement that cross-forest trusts are more stringently filtered than external trusts.

If there is information that supports this, the reference should be changed.  If there isn't information that supports this, then the documentation needs to be changed.

**Comment by mypil** [comment]
@Justinha - Do you have any updates on how to proceed with this issue? Thank you.

**Comment by Justinha** [comment]
Yes, I will relay input from engineering soon.

**Comment by Justinha** [comment]
@haselton Our engineering team reviewed the source code for these trust attributes and found there is a difference in the filtering, but we have not documented it. The link to the relevant protocol description is https://docs.microsoft.com/openspecs/windows_protocols/ms-adts/e9a2d23c-c31e-4a6f-88a0-6646fdb51a3c 

I added that link to this event topic and it will publish tomorrow. 

Is there a problem you are trying to solve, or any other reason you are asking? That info could help prioritize work to publish the specific filtering differences.

**Comment by haselton** [comment]
No specific problem per-se…just needed to confirm something.

**Comment by Jcoetsee** [comment]
@haselton @Justinha If the article and content has been updated would it be okay to say we can close this item out?

**Comment by haselton** [comment]
@Justinha The attribute link you posted (https://docs.microsoft.com/openspecs/windows_protocols/ms-adts/e9a2d23c-c31e-4a6f-88a0-6646fdb51a3c) does say that cross-forest trusts are more stringently filtered than external trusts...

> If this bit is set, then a cross-forest trust to a domain is to be treated as an external trust for the purposes of SID Filtering. Cross-forest trusts are more stringently filtered than external trusts. This attribute relaxes those cross-forest trusts to be equivalent to external trusts. 

...but it links back to [MS-PAC] section 4.1.2.2 for information about how external and cross-forest trusts are filtered and that section doesn't have info on how cross-forest trusts are filtered differently than external trusts.  

>  For more information on how each trust type is filtered, see [MS-PAC] section 4.1.2.2

If there's a definitive link on how filtering differs between external/cross-forest trusts, it should be used in both places if possible to avoid circular referencing.

**Comment by Jcoetsee** [comment]
@justinha please see response above

**Comment by Justinha** [comment]
@haselton you're right, but our engineering team indicates we don't have a definitive link on how the filtering differs. I have shared this issue with the protocol documentation team. Better to cover it there than in this Auditing topic. 

Given that we don't have the definitive link, how else would like you this resolved?

**Comment by haselton** [comment]
@Justinha Given that info I think the best way would be to remove this part from both articles, if possible

> For more information on how each trust type is filtered, see [MS-PAC] section 4.1.2.2

Although now I am extremely curious as to how the SID-filtering differs between the two trust types.

**Comment by Jcoetsee** [comment]
@Justinha I think in light of the situation it might not be a bad idea to remove the above reference that links to that article. I can put in a PR request for that. what do you think?

**Comment by egallagh** [comment]
Personally, I think it is fine like it is.
The statement of differences in trusts in this article is fine.
The linked article also contains good info about the processing.
Just because the linked article does not address the specific trust stringency differences is not really relevant.

**Comment by Jcoetsee** [comment]
@Justinha and @haselton should we then consider that we treat this as a separate item and possibly close this particular request since it relates more to the sub-article and not directly to the article at hand? also see the response above. I agree with that as well but still, believe we could make reference to this just not in this particular case or this article?

**Comment by Justinha** [comment]
I agree with @egallagh but I have no objection to removing the link.

**Comment by Jcoetsee** [comment]
@Justinha I have made the PR to get it removed, With regards to your question if that subsection doesn't have the ability for somebody to open an issue against it then I am not sure what we can do there, to be honest.

**Comment by mypil** [comment]
@haselton - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by edgarol** [comment]
@Haselton, 
In the future please contact dochelp < at > microsoft < dot> com to raise any question or comment you may have regarding the open specifications. 
Please let me know whether the following helps.
The description of the [MS-PAC] SID pattern “S-1-5-21-<Domain>-R where R >= 1000” has a sentence “Not filtered at domain and external trust boundaries.”, which is one specific example that supports the “Cross-forest trusts are more stringently filtered than external trusts” statement in MS-ADTS.
See table of SID patterns in MS-PAC Section 4.1.2.2:

S-1-5-21-<Domain>-R   R >= 1000 | Identifiers for end user-created domain identities and   domain groups. | Not   filtered at domain and external trust boundaries. Can be filtered at member,   quarantined, and cross-forest boundaries.
-- | -- | --

**Comment by haselton** [comment]
I'll review when I have a minute @edgarol
