### ISSUE TITLE
Incorrect status reported when reset is interrupted

### ISSUE THREAD

**Issue by jflieben** [MicrosoftDocs/windows-itpro-docs#3063]
If I interrupt device reset after it reboots, during the reset phase ('configuring...'), the device will not be reset, but the Intune portal will report that the reset was successfull: "AutoPilot Reset (preview): Completed"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69506375-4eb8-1d54-e406-dfd5a1376d0e
* Version Independent ID: bf30cefa-d9ae-d490-9746-c652412b5e6c
* Content: [Windows Autopilot Reset](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-reset)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-autopilot-reset.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jflieben - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
