### ISSUE TITLE
Dead link for Multi Homing support

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/windows-itpro-docs#3066]
..."Windows Defender ATP workspace through Multi Homing support." The link to multi homing support is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4ed2b3-0390-4d53-2450-14995ee8b0b0
* Version Independent ID: 91b5bb3e-55d4-6a8e-c16d-094f15c28ee7
* Content: [Onboard servers to the Windows Defender ATP service](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-server-endpoints-windows-defender-advanced-threat-protection#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-atp/configure-server-endpoints-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/configure-server-endpoints-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@npherson -  Thank you for pointing this out.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@mjcaparas @Justinha - I checked on the Multi Homing support link and it redirects to a Page not found error stating that "This page has been disabled." Here's the link URL - **https://blogs.technet.microsoft.com/msoms/2016/05/26/oms-log-analytics-agent-multi-homing-support/**
Please let us know what is the correct URL link for this so a PR can be created or please advise on how to proceed with this. Thank you.

**Comment by npherson** [comment]
All of the MSDN and TechNet blogs are either being decommissioned or moved over to TechCommunity. It might be worth doing a search for links to MSDN/TechNet blogs on all of the docs… I imagine a ton of blog content we’re referencing is about to disappear.

**Comment by mypil** [comment]
@mjcaparas @Justinha - I would like to follow up on this. Do you have any updates. Thank you.

**Comment by mjcaparas** [comment]
Still investigating on where the new multi homing support link has gone to.

**Comment by mjcaparas** [comment]
Based on investigation, Operations Management Suite (OMS) is now Azure Monitor. OMS has now been retired. 
I'll be updating the topic to point to general Log analytics topic where it states in the 5th paragraph that "The Windows agent can report up to four Log Analytics workspaces".
