### ISSUE TITLE
Windows 10 Enterprise 2019 LTSC - misnomer

### ISSUE THREAD

**Issue by LarryLACa** [MicrosoftDocs/windows-itpro-docs#3069]
Windows 10 Enterprise 2019 LTSC should be 
Windows 10 Enterprise 2018 LTSC since this is the 1809 build.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684ab805-b732-043b-9d4c-e8c02660557a
* Version Independent ID: 5c288d08-f2cb-3927-93cb-acb2412fc62c
* Content: [Windows 10 Enterprise LTSC](https://docs.microsoft.com/en-us/windows/whats-new/ltsc/#feedback)
* Content Source: [windows/whats-new/ltsc/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/ltsc/index.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@LarryLACa - Thank you for submitting feedback.

I will get this issue over to the  Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@LarryLACa - Windows 10 Enterprise 2019 LTSC really was based on build 1809 but as you might be aware that build 1809 got a delay because of a bug and Microsoft pull the release. This was then released after approximately three months. Because of this delay it hits the end users in 19H1 and that is the reason it is listed as Windows 10 Enterprise 2019 LTSC.
Thanks.

**Comment by mypil** [comment]
@LarryLACa - From our understanding, the issue has been answered by joinimran. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
