### ISSUE TITLE
Troubleshooting local/remote autopilot reset

### ISSUE THREAD

**Issue by mkuenzie** [MicrosoftDocs/windows-itpro-docs#3071]
When an autopilot reset fails, either from the Intune portal or from a local reset, limited information is available in the status messages.  Any additional troubleshooting information/steps would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adcfcc02-d931-66e3-6f4f-c14b936358e6
* Version Independent ID: 8972647b-ba21-b68f-b698-5fb6e9e9f1fd
* Content: [Troubleshooting Windows Autopilot](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/troubleshooting)
* Content Source: [windows/deployment/windows-autopilot/troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/troubleshooting.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@mkuenzie - Thank you for submitting feedback.

I will get this issue over to the  Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @mkuenzie - Windows Autopilot is evolving and we are adding more and more information as we learn more about it. If there is any information that you think can be added in the document, please feel free to let us know so that we can add that accordingly. 
Normally, when we add new features or receives issues, we update the docs. 
Thanks.

**Comment by mkuenzie** [comment]
Hi @joinimran  I had an issue where local autopilot reset failed immeidately with the 'ran into trouble.  Please sign-in with an administrator account to see why and reset manually'.  No event logs I searched had any relevant details.  I learned via troubleshooting that WinRE (reagentc /info) needs to be enabled with a recovery partition for autopilot reset to function.   It would be nice if this was documented explicitly.  The device I was working with did not come with a Recovery partition from the vendor and I had to create one.

**Comment by joinimran** [comment]
@mkuenzie - Thanks for your details answer, please note this information is already available at https://docs.microsoft.com/en-us/education/windows/autopilot-reset#troubleshoot-autopilot-reset

We really appreciate your feedback here. Thanks.

**Comment by mypil** [comment]
@officedocsbot close
