### ISSUE TITLE
"Block File" feature on by default

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/windows-itpro-docs#3073]
> This feature is only available if your organization uses Windows Defender Antivirus as the active antimalware solution and that the cloud-based protection feature is enabled. 
> 
> If your organization satisfies these conditions, the feature **is enabled by default**.

Just enabled ATP in a tenant and Block File was Off. Is the documentation correct? How does ATP check if we satisfy these conditions? I also think we could link to this article that describes this feature in a little bit more detail: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/respond-file-alerts-windows-defender-advanced-threat-protection#block-files-in-your-network

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d99de0-789d-3c71-4bd9-f45e62f82a7b
* Version Independent ID: d56d09f0-1f9a-563e-fee0-142bda27a99b
* Content: [Configure advanced features in Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/advanced-features-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/advanced-features-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/advanced-features-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@JonesMikael - Thank you for submitting feedback.

I will get this issue over to the  Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@JonesMikael - Thank you for sharing the details. We have forwarded your request to embed the detailed document related to blocking the file with the current document. 
Regarding your 1st question, Can you please confirm when you have enabled the ATP, have you made Windows Defender Antivirus as your antimalware solution as well? 
Thanks.

**Comment by JonesMikael** [comment]
How do you actually make Windows Defender Antivirus my antimalware solution? Except for simply making sure I have clients with Windows Defender Antivirus installed in my environment - is there any switch somewhere?

**Comment by joinimran** [comment]
Thank you for your messages @JonesMikael , Please review https://docs.microsoft.com/en-us/azure/security/azure-security-antimalware to see if this helps you. Thanks.

**Comment by mypil** [comment]
@JonesMikael - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
