### ISSUE TITLE
Link under "Use the TPM cmdlets" is broken

### ISSUE THREAD

**Issue by RonaldAi** [MicrosoftDocs/windows-itpro-docs#3080]
The link behind "TPM Cmdlets in Windows PowerShell" points to an error page. It should instead point to https://docs.microsoft.com/en-us/powershell/module/trustedplatformmodule/.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6639730-cd8c-70c4-281c-1f11f95b34e6
* Version Independent ID: 6f59cc97-8d25-bd6a-59b9-0cdf6f932614
* Content: [Manage TPM lockout (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/manage-tpm-lockout#feedback)
* Content Source: [windows/security/information-protection/tpm/manage-tpm-lockout.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/tpm/manage-tpm-lockout.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@RonaldAi - Thank you for pointing this out.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by illfated** [comment]
Seeing that the OP provided the PR, I am fairly sure this issue ticket can be closed too.

**Comment by Justinha** [comment]
Thanks everyone!
