### ISSUE TITLE
WIndows Server 2019 Domain Controller?

### ISSUE THREAD

**Issue by MariusWeiss** [MicrosoftDocs/windows-itpro-docs#3082]
It says Windows Server 2016 Domain Controllers are required. What about Windows Server 2019 Domain Controllers? Is this supported?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@MariusWeiss - Thank you for submitting feedback.

May we know which Microsoft document link you used in reference to this issue? Please share it with us so we can investigate further. Thank you.

**Comment by MariusWeiss** [comment]
@mypil 
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification#prerequisites

**Comment by illfated** [comment]
## [Hybrid Deployments](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification#hybrid-deployments)

> The table shows the minimum requirements for each deployment.

As long as you have got Windows Server 2016 Domain Controllers _**or better**_ , it will be supported.

**Comment by Malind19** [comment]
Created the PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3136

**Comment by illfated** [comment]
@MariusWeiss : As you can see above, an improvement has been made to the source for the docs page. It may take a few days before the change migrates to the page on docs.microsoft.com, but you can consider your question answered and followed up with the added improvement. Thank you for making us aware of the uncertainty the old version might present to the users.

**Comment by mypil** [comment]
@MariusWeiss - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
