### ISSUE TITLE
Removed

### ISSUE THREAD

**Issue by billgatesfan** [MicrosoftDocs/windows-itpro-docs#3085]
Hi,  it seems you removed some keys 
according to https://docs.microsoft.com/en-us/graph/changelog#january-2019 :

"Removed the localSecurityOptionsEnableAdministratorAccount, localSecurityOptionsEnableGuestAccount and lanManagerWorkstationEnableInsecureGuestLogons properties from the windows10EndpointProtectionConfiguration entity".

Why are these keys (like localSecurityOptionsEnableAdministratorAccount) then still populated in this article?

And does it make sense to say that "Default: Disabled." when the key is a boolean, that tells me if the account is disabled or not? If this is sth being "queried" as opposed to "set", then there should be no default value, correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 773b74b2-7dc2-d0e5-1e3b-bd6445bceda4
* Version Independent ID: 34b55057-9078-6bd0-a9ac-2f6403b84be7
* Content: [Policy CSP - LocalPoliciesSecurityOptions](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions#localpoliciessecurityoptions-accounts-enableguestaccountstatus)
* Content Source: [windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by illfated** [comment]
From what I can see, that is the _**beta**_ version of Microsoft Intune API, indicating that not even the documentation may be complete yet.

**Comment by billgatesfan** [comment]
You are correct... 
As 99,99% of the API calls made by Intune portal (at time of writing) are made against /beta/ endpoint anyway, customers have no choice than to deal permanently with beta features ;-). 

But now that MS announced the removal of "localSecurityOptionsEnableAdministratorAccount" in their Change Log, then I suggest to no longer document this (now) non-existing feature, as it is also not existing in the /v1.0/ endpoint.

**Comment by illfated** [comment]
Very well. I will leave your additional information to be followed up by the Docs team members (I don't have the required skill to provide the necessary information).

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@billgatesfan 

We are investigating this issue and will follow-up with updates.

Thank you for your feedback.

**Comment by e0i** [comment]
@billgatesfan 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
