### ISSUE TITLE
b

### ISSUE THREAD

**Issue by saud11ml** [MicrosoftDocs/windows-itpro-docs#3090]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a97de48f-e863-7786-5958-c76a831486e5
* Version Independent ID: b0dc0baf-e3d0-fba5-e2ac-9c6de32e4aab
* Content: [Submit Windows 10 upgrade errors using Feedback Hub](https://docs.microsoft.com/en-us/windows/deployment/upgrade/submit-errors)
* Content Source: [windows/deployment/upgrade/submit-errors.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/submit-errors.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@saud11ml  - we would like to get more details from you. Can you please share what specific issue you have with this article?

**Comment by illfated** [comment]
Looks like an unintentional or experimental post without any reporting intended.

**Comment by mypil** [comment]
@saud11ml - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
