### ISSUE TITLE
LOCKSCREEN PIN ERROR 

### ISSUE THREAD

**Issue by crystalh3** [MicrosoftDocs/windows-itpro-docs#3092]
I tried to enter my pin on the lock screen but got error code: (0xd00000e5) and the screen read "Click to set up pin" so I did entered a new pin, but just got another error code and website which didn't have the error code listed and wouldn't retrieve anything when entered in the search bar on the website.
WEB ADDRESS: https://aka.ms/PINErrors
ERROR CODE: 0X90284001
CORRELATION ID: ee30fd8e-e43c-0001-2539-32ee3ce4d401
TIMESTAMP: 2019-03-28T22:04:35.056Z

![NEW PIN ERROR 0X90284001](https://user-images.githubusercontent.com/49045217/55197421-8c1ec000-5180-11e9-960d-1c67e9bb569c.JPG)

![PIN ERROR 0xd00000e5](https://user-images.githubusercontent.com/49045217/55197423-8fb24700-5180-11e9-813f-83bc43b82689.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@crystalh3 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by crystalh3** [comment]
I had a missing file and a Microsoft technician helped me fix it.
