### ISSUE TITLE
Error code 0xcaa6000a

### ISSUE THREAD

**Issue by spankin** [MicrosoftDocs/windows-itpro-docs#3097]
Windows Hello for Business PIN setup and - Error code 0xcaa6000a - what is it?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@spankin - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by spankin** [comment]
@mypil I looked for error code here - https://aka.ms/pinerrors however it's not there. We get Windows Hello for Business welcome page, but then it's 'Something went wrong' - 'We weren't able to set up your PIN. Sometimes it helps to try again or you can skip for now and do this later.' And there's this error code - 0xcaa6000a.

we did try several times over few days and restarted computer several times too. Dsregcmd /status says 'PreReqResult : WillProvision' and other users are enrolling using same environment. So no idea what's going on.

**Comment by mypil** [comment]
@spankin - Thank you for your response.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
