### ISSUE TITLE
Network security: Restrict NTLM: NTLM authentication in this domain

### ISSUE THREAD

**Issue by BigB7v1** [MicrosoftDocs/windows-itpro-docs#3098]
This security features does a great things to break the normal operations of network operations.  By simply disabling NTLM, you can stop the ability of Multi-function printers from being able to scan to network folders.  You can stop VPN users from being able to access SMB shares.  Local users still access SMB, but user across the VPN will not be able to see the shared folders at all.
We recently had this happen to one of our networks. An unknown administrator made a change in the group policy and broke everything.  It took us over a month to find the problem with Microsoft Support.  I would not make any changes to Group Policy that will block NTLM communications.  User/Admin be warned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f343712d-894d-1cbe-793a-00c2c7a6a5a2
* Version Independent ID: 34ff1caf-163c-38a6-7ff4-3fa9c520dd0f
* Content: [Network security Restrict NTLM NTLM authentication in this domain (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-restrict-ntlm-ntlm-authentication-in-this-domain#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-security-restrict-ntlm-ntlm-authentication-in-this-domain.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/network-security-restrict-ntlm-ntlm-authentication-in-this-domain.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
Thanks for the input. You should try this policy in audit mode first, which is a diff setting https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-restrict-ntlm-audit-ntlm-authentication-in-this-domain

This is mentioned in the best practices section now but we could add a link and possibly mention in it in the Intro section too.

**Comment by egallagh** [comment]
Hi @BigB7v1. I strongly disagree regarding disabling legacy NTLM.
It is important to understand that applying security controls, by their very nature, will prevent some things from happening and likely result in "breaking" existing functionality. Proper controls, documentation, testing and implementation of more secure alternative technologies prior to applying a security control can minimize or eliminate any negative repercussions. @Justinha has a great suggestion about implementing audit mode first.
Hope that helps.
Recommend closure.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot close
