### ISSUE TITLE
Allow App Requests Location

### ISSUE THREAD

**Issue by rygrimm** [MicrosoftDocs/windows-itpro-docs#3100]
The App request setting is managed under "Settings - Shop", not "Settings - Distribute".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dae47ce-fb8d-1802-aace-b99a0f03598a
* Version Independent ID: 35039b4c-6b8e-ac14-6d69-29496589f635
* Content: [Settings reference Microsoft Store for Business and Education (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/settings-reference-microsoft-store-for-business#feedback)
* Content Source: [store-for-business/settings-reference-microsoft-store-for-business.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/settings-reference-microsoft-store-for-business.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@rygrimm - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by illfated** [comment]
@rygrimm : Thank you for pointing out the issue.
According to the Pull Request #3121 it has been corrected now,
but it may still take a couple of days to migrate
to the docs.microsoft.com version of the article.
We hope you find it to be properly followed up.

**Comment by mypil** [comment]
@officedocsbot close
