### ISSUE TITLE
Applying different layouts for 1809 and 1803

### ISSUE THREAD

**Issue by edcion** [MicrosoftDocs/windows-itpro-docs#3102]
Our domain uses 1809 and 1803 builds, without putting these computers into different OUs can we edit the xml file to change both 1809 and 1803? Currently we have it so that the layout is correctly applied to 1809 but for 1803 it is simply locking the previous layout that the user had (All their start pins are fixed and can not be removed and nothing else can be added) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79fccecd-5484-0304-d82b-9425f1889a22
* Version Independent ID: 4df6b138-c1b5-b551-22c9-19d3d1f9105d
* Content: [Customize and export Start layout (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/customize-and-export-start-layout#feedback)
* Content Source: [windows/configuration/customize-and-export-start-layout.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/customize-and-export-start-layout.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@edcion I'm checking on whether that's possible, I'll let you know when I get an answer.

**Comment by edcion** [comment]
Actually I should have included 1607 in my versions as well. We have pc's running 1607 LTSB and those also experience locked up start menus when i push the xml in GP

**Comment by jdeckerms** [comment]
@edcion I've been told that a single layout XML should work on both builds. Since it isn't working for you, we recommend that you open a support case (https://support.microsoft.com/en-us/contactus/) so they can help you resolve the issues.
