### ISSUE TITLE
Missing How to List Virtual Smart Cards

### ISSUE THREAD

**Issue by camlen92** [MicrosoftDocs/windows-itpro-docs#3104]
The documentation is missing how to list virtual smart cards in case you need to see available VSCs or destroy them.

I don't believe this is a feature of TpmVscMgr as well.

You can list available VSCs by running the follow WMIC in CMD: wmic path win32_PnPEntity where "DeviceID like '%smartcardreader%'" get DeviceID,Name,Status

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 458fb7f8-3f6f-9111-2982-f6300268b935
* Version Independent ID: 936138f5-f85b-a049-2a93-a7b2b238f90b
* Content: [Tpmvscmgr (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-tpmvscmgr#feedback)
* Content Source: [windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-tpmvscmgr.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-tpmvscmgr.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@camlen92 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @camlen92 ,
Listing of smart cards is not the feature of Tpmvscmgr tool, so it is out of the scope of the article.

Also, for listing, following command worked better for me:
wmic path win32_PnPEntity where "ClassGuid like '{50DD5230-BA8A-11D1-BF5D-0000F805F530}'" get DeviceID,Name,Status

Do you have any other questions or we can close your request?

Thank you

**Comment by camlen92** [comment]
@MaratMussabekov, is that ClassGuid static or dynamic? How is it working "better" for you? My command still listed all virtual smart cards that I had stored on the machine so I'm just curious how you can say it is better without an explanation. 

Other than that, no, I don't have any other questions. It just seemed like Tpmvscmgr should included a /list switch since it is the included tool in Windows for virtual smart card _management_.

**Comment by MaratMussabekov** [comment]
Hello @camlen92 ,
**is that ClassGuid static or dynamic?** - it is static, more details here [System-Defined Device Setup Classes Available to Vendors](https://docs.microsoft.com/windows-hardware/drivers/install/system-defined-device-setup-classes-available-to-vendors)

**How is it working "better" for you?** - from my experience, filter "DeviceID like '%smartcardreader%'" doesn't work sometimes.

Thank you

**Comment by mypil** [comment]
@camlen92 - We would like to follow up on this. Can you please respond to the query of MaratMussabekov?

Thank you.
