### ISSUE TITLE
Broken link to removed KB article

### ISSUE THREAD

**Issue by ralish** [MicrosoftDocs/windows-itpro-docs#3107]
The guidance in the Countermeasure section references Microsoft KB312571, however, the link text is incorrect and the article itself has been removed. It should either be restored to the knowledge base or the link updated to the appropriate up-to-date documentation. In either case the link text is incorrect and needs updating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb8f614-1c7e-0386-dfa0-c44316196828
* Version Independent ID: 015cb786-ff36-4f83-87ca-99057a3a1142
* Content: [Audit Audit the use of Backup and Restore privilege (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/audit-audit-the-use-of-backup-and-restore-privilege#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/audit-audit-the-use-of-backup-and-restore-privilege.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/audit-audit-the-use-of-backup-and-restore-privilege.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by illfated** [comment]
Oh, right. You are referring to the text
> For more information about configuring this key, see Microsoft Knowledge Base article [100879](https://go.microsoft.com/fwlink/p/?LinkId=100879).

Not only is the text misleading, because the text says that the Knowledge Base article ID is supposed to be **100879**, but the link ID tries to open https://support.microsoft.com/en-us/help/312571 (which does not exist, hence the 404 error).

**Comment by illfated** [comment]
After some searching, I found this Desktop-related page:
https://docs.microsoft.com/en-us/windows/desktop/eventlog/eventlog-key
It only describes the registry key itself, not necessarily the same level of detail you would find in a dedicated KB article.

**AutoBackupLogFiles**
> This value is of type REG_DWORD, and is used by the event log service to determine whether an event log should be automatically saved. The default value is 0, which disables auto-backup. The service will back up the log file only if the retention value is -1 (0xFFFFFFFF). Other values will be ignored.Windows Server 2003: Retention can be set to -1 (0xFFFFFFFF) or 1 (0x00000001) for AutoBackupLogFiles to work. Other values will be ignored.

**Comment by ralish** [comment]
@illfated: Sounds good, or at least certainly an improvement on a deadlink!

I've actually noticed a number of KB articles of late have been removed which are linked to by (often lots of) other MSFT documentation, and in some cases via Windows itself (supported versions). If you're able to assist with that I'd be happy to send you some examples I've noticed.

**Comment by illfated** [comment]
The Docs team members prefer to receive reports of errors, wrong or missing information etc. from individual posts on the related page, just like the one you posted yesterday. All reports are welcome, so we hope it is OK with you to put each report on their respective https://docs.microsoft.com/ pages where the error can be found, making the report automatically contain links to the related docs page and its Github version.

**Comment by ralish** [comment]
@illfated: I meant with regards to KB articles where that facility is sadly not available.

**Comment by illfated** [comment]
Well, thank you for having faith in my abilities, but I only have got access to the same tools as you have (search engines and forums). I sometimes spend more time at work or in other forums (or just enjoying my spare time with YouTube entertainment, so it may not be as productive as one could hope for. I would have posted questions in forums directly related to the KB list in question to ask where the KB article has gone and if it has been replaced with any form of new documentation. (I presume it can be quite a chore to continuously churn out new documentation alongside all the new software and its updates, but notes should be made when old documents are removed for being outdated or when new versions have taken their place.)

**Comment by Justinha** [comment]
@ralish Thanks for reporting and @illfated thanks for the find! That docs topic is then best we can do in this case because that original KB is no longer published, though I'm not sure why. I'll update the link.

**Comment by ralish** [comment]
@Justinha: Thanks!

@illfated: Whoops, sorry, I had it in my head you were an MSFT employee :)
