### ISSUE TITLE
Neither the steps worked and nor the tool worked :-(

### ISSUE THREAD

**Issue by sachinmar** [MicrosoftDocs/windows-itpro-docs#3108]
The provided steps were followed word to word 
the tool was downloaded and used via cmd and powershell in administrator mode and still did not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#feedback)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
Could you provide some details on what you were trying to do and didn't work?

**Comment by mypil** [comment]
@sachinmar -  we would like to follow up and get more details on the issue that you have so we can help you further. Could you please answer the question of DaniHalfin?

Thank you.

**Comment by mypil** [comment]
@sachinmar - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
