### ISSUE TITLE
0x801c0541 Not listed

### ISSUE THREAD

**Issue by WagoL** [MicrosoftDocs/windows-itpro-docs#3123]
This error code is not listed.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/nl-nl/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@WagoL - Thank you for submitting feedback.

This is related to the closed issue #2941. 

Please refer to the doc owner's (DaniHalfin) response below:

> Hi everyone,
> For any error code not listed in this topic, please file a problem through the feedback hub app.
> Error codes that are unlisted in this topic are most likely transient and always too complex to be able to provide resolution through a help topic.
> Please report these issues through the feedback hub app, and reach out to us through our official support channels.

**Comment by mypil** [comment]
@officedocsbot close
