### ISSUE TITLE
WU log generator app?

### ISSUE THREAD

**Issue by seamonkey420** [MicrosoftDocs/windows-itpro-docs#3125]
Why isn't there a link to the actual WU log creator that MS support offers that will find all files and create a zip of them?  And why can't all of these logs reside in a single directory? Seems like very bad coding and lack of collaboration between depts responsible for various parts of the upgrade/updating process.  Just my .02 as a Windows admin since Windows NT 4.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47692487-0a0b-3b1b-6d34-790046c7cbc3
* Version Independent ID: 0f66cafe-2bff-4323-b3fc-01014b904b3a
* Content: [Windows Update log files](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-logs)
* Content Source: [windows/deployment/update/windows-update-logs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-logs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **elizapo**

**Comment by MaratMussabekov** [comment]
Hello @seamonkey420 ,
**Why isn't there a link to the actual WU log creator that MS support offers that will find all files and create a zip of them?** - could you please provide more details about this application?

Thank you

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@seamonkey420 - We would like to follow up on this. Can you please respond to the query of MaratMussabekov?

Thanks.

**Comment by seamonkey420** [comment]
certainly. it’s the WU log creator that microsoft support will have you download and run that basically finds all failed upgrade logs and makes a zip of them along with a log file that usually gives one a better idea on why it failed. i got the utility after putting a Premiere support ticket with my company and feel it should be publicly available to help trackdow issues. actual file name is: SetupDiag.exe

**Comment by mypil** [comment]
@seamonkey420 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
