### ISSUE TITLE
Hybrid Azure AD joined Autopilot devices not supported.

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/windows-itpro-docs#3129]
The documentation should be updated to say that Autopilot Reset does not support Hybrid Azure AD joined Autopilot devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69506375-4eb8-1d54-e406-dfd5a1376d0e
* Version Independent ID: bf30cefa-d9ae-d490-9746-c652412b5e6c
* Content: [Windows Autopilot Reset](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-reset#feedback)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-autopilot-reset.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@nhogarth86 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
