### ISSUE TITLE
Source and Destination IPs

### ISSUE THREAD

**Issue by BigIve** [MicrosoftDocs/windows-itpro-docs#3130]
What options are there to be able to specify Source and Destination IPs for a QoS rule?  As the above doesn't appear to cover this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bb8b93e-0c1a-8b47-472f-effef5f9209e
* Version Independent ID: 8a2615e2-a77b-c08e-b91c-3ce33e0539b2
* Content: [NetworkQoSPolicy CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/networkqospolicy-csp)
* Content Source: [windows/client-management/mdm/networkqospolicy-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/networkqospolicy-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by MaratMussabekov** [comment]
Dear @BigIve,
as you can see in the beginning of the article:
**The following conditions are supported:

- Network traffic from a specific application name
- Network traffic from specific source or destination ports
- Network traffic from a specific IP protocol (TCP, UDP, or both)**

so it looks like this CSP doesn't support applying values to the traffic from/to a specific IP address.

Thank you

**Comment by e0i** [comment]
Hello, @BigIve 

It seems that your question has already been answered by @MaratMussabekov and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
