### ISSUE TITLE
Spelling mistake "Assing roles"

### ISSUE THREAD

**Issue by chazwoza** [MicrosoftDocs/windows-itpro-docs#3131]
spelling mistake down the bottom on "Assing roles", should be Assign role.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e62232-54ab-fa9d-1e31-7a65e7506a12
* Version Independent ID: 51a94f92-9ff4-12e7-2f97-1bbe34855400
* Content: [Roles and permissions in Microsoft Store for Business and Education (Windows 10)](https://docs.microsoft.com/en-gb/microsoft-store/roles-and-permissions-microsoft-store-for-business#feedback)
* Content Source: [store-for-business/roles-and-permissions-microsoft-store-for-business.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/roles-and-permissions-microsoft-store-for-business.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@chazwoza - Thank you for pointing this out.

PR #3134 has been created to resolve this typo issue.  

We appreciate your effort and feedback that helps us improve the content.

**Comment by mypil** [comment]
@officedocsbot reopen

**Comment by mypil** [comment]
@officedocsbot close
