### ISSUE TITLE
Additional info for unexpected errors

### ISSUE THREAD

**Issue by buildbod** [MicrosoftDocs/windows-itpro-docs#3137]
We've found that before you perform the update make sure any additional screens are off and the Surface is only projecting to its own screen otherwise the update may fail with the 'Encountered an unexpected error' message and you'll have to perform a 'power-cycle'. The update takes less than 10 minutes and for Enterprise users it needs local device administration rights. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7b356e-3dbd-7f59-845e-a92e05865a52
* Version Independent ID: 711c5497-373f-662c-7fae-ba60f046e50c
* Content: [Microsoft Surface Dock Updater (Surface)](https://docs.microsoft.com/en-us/surface/surface-dock-updater)
* Content Source: [devices/surface/surface-dock-updater.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/surface-dock-updater.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@buildbod Thanks for sharing that tip. I'll have to run it past the engineering team before I can add it to the documentation, but I'm glad you found something that works for your org.
