### ISSUE TITLE
Multi-App Kiosk .lnk to Powerpoint file not working

### ISSUE THREAD

**Issue by SinoKey** [MicrosoftDocs/windows-itpro-docs#3140]
Hi,
I made a startlayout with 4 tiles. 2 are .exe and 2 are powerPoint. But the powerPoint .lnk won't show in kiosk mode? Is this even possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78038d67-04a1-f4ae-6a69-98e157688a31
* Version Independent ID: c86b4460-e8be-8537-a6c8-3cb094ef14a3
* Content: [Set up a multi-app kiosk  (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps#provision)
* Content Source: [windows/configuration/lock-down-windows-10-to-specific-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/lock-down-windows-10-to-specific-apps.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@SinoKey Did you follow the instructions for .lnk shortcuts? https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps#lnk-files

**Comment by SinoKey** [comment]
Yes I did. The 2 .ppsx files are placed under C:\folder. The shortcuts are in "%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Powerpoint.lnk"

**Comment by jdeckerms** [comment]
@SinoKey Thanks, I wanted to be sure you saw that part of the instructions. If they aren't working properly for you, you'll need to contact Microsoft Support for assistance troubleshooting your issue (https://support.microsoft.com/en-us/contactus/).

**Comment by SinoKey** [comment]
I tried the same .ppkg on a virtual machine. There it worked. Is this a bug? Could you test it?
