### ISSUE TITLE
Typo:  Purchase spelled incorrectly (However, they can't purhcase apps directly from Microsoft Store for Business and Education.)

### ISSUE THREAD

**Issue by CJRicard** [MicrosoftDocs/windows-itpro-docs#3143]
Typo:  Purchase spelled incorrectly (However, they can't purhcase apps directly from Microsoft Store for Business and Education.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeb9333f-07c0-9a51-93ee-90e1ebcaa52b
* Version Independent ID: 732c5d3c-bb82-7cf1-ce37-ea169f036051
* Content: [Microsoft Store for Business and Microsoft Store for Education overview (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/microsoft-store-for-business-overview)
* Content Source: [store-for-business/microsoft-store-for-business-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/microsoft-store-for-business-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
