### ISSUE TITLE
Profile system performance: Incorrect default value

### ISSUE THREAD

**Issue by ralish** [MicrosoftDocs/windows-itpro-docs#3155]
The default value for this user right is stated to be *Administrators* but the correct default value is *Administrators* **and** *NT SERVICE\WdiServiceHost*. I've verified this on Windows Server 2012 R2, Windows Server 2016, and Windows 10, but believe this is the default value as far back as Windows Vista and Server 2008? It presumably also still holds true for Windows Server 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f767b9ed-281b-97cf-b59c-5bdd7f2c10b5
* Version Independent ID: 6e9ec3c3-62eb-f71c-f74f-75a61a53a9d5
* Content: [Profile system performance (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/profile-system-performance#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/profile-system-performance.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/profile-system-performance.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
@ralish This is confirmed that this value holds for Windows Server 2019 as well.

**Comment by mypil** [comment]
@ralish - Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
