### ISSUE TITLE
Increase scheduling priority: Incorrect default value

### ISSUE THREAD

**Issue by ralish** [MicrosoftDocs/windows-itpro-docs#3156]
The default value for this user right is stated to be *Administrators* and *Window Manager/Window Manager Group* but this appears to only be true on desktop SKUs. On Windows Server the *Window Manager/Window Manager Group* SID is not granted this right by default. I've verified this on Windows Server 2012 R2, and Windows Server 2016, but believe this is the correct default value as far back as Windows Server 2008? It presumably also still holds true for Windows Server 2019.

Nitpick: The forward slash in *Window Manager/Window Manager Group* should be a back slash.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f26917db-f3e1-eb86-7b8f-090018f5d4d7
* Version Independent ID: f5d2f03c-7e77-ff58-9726-258f9a541f11
* Content: [Increase scheduling priority (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/increase-scheduling-priority)
* Content Source: [windows/security/threat-protection/security-policy-settings/increase-scheduling-priority.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/increase-scheduling-priority.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@ralish Thanks for raising this. I think we actually need to remove the Default values section in each of these GP topics. I need to check some things on my side first. For ex, I think default values were removed from the Windows security baselines because we don't have a way to track if/when the default values change between releases. There might be other problems. I'll follow up here.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Justinha - Do you have any updates on this?

Thank you.

**Comment by Justinha** [comment]
@mypil can you submit a pull request? Changes to make:
1. remove the default values section 
2. remove the reference to the actual value in the Best practices section
3. For Windows Server 2012 and earlier, add a link to previous versions of this same policy: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn221960(v%3dws.11). You can add this link to the See Also section at the bottom.

**Comment by mypil** [comment]
@Justinha - sure, assigning the PR creation to @nenonix.

@nenonix  - please assist in creating a PR for this issue. 

Thank you!
