### ISSUE TITLE
Step 7

### ISSUE THREAD

**Issue by sonabit** [MicrosoftDocs/windows-itpro-docs#3157]
On Windows Server 2016 (Version 1607) the command should be "netsh winsock reset"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources#feedback)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Microsoft Windows [Version 10.0.14393] (OS Build 14393.2879)
(c) 2016 Microsoft Corporation. All rights reserved.

Not only that, I am fairly certain that the order is strict and needs to be `netsh winsock reset` (unless the command has been re-programmed in later versions to accept a random order).

Check the general help text output from the command `netsh /?` in the details sections below:

<details>

```
C:\Users\Administrator>netsh /?

Usage: netsh [-a AliasFile] [-c Context] [-r RemoteMachine] [-u [DomainName\]UserName] [-p Password | *]
             [Command | -f ScriptFile]

The following commands are available:

Commands in this context:
?              - Displays a list of commands.
add            - Adds a configuration entry to a list of entries.
advfirewall    - Changes to the `netsh advfirewall' context.
branchcache    - Changes to the `netsh branchcache' context.
bridge         - Changes to the `netsh bridge' context.
delete         - Deletes a configuration entry from a list of entries.
dhcp           - Changes to the `netsh dhcp' context.
dhcpclient     - Changes to the `netsh dhcpclient' context.
dnsclient      - Changes to the `netsh dnsclient' context.
dump           - Displays a configuration script.
exec           - Runs a script file.
firewall       - Changes to the `netsh firewall' context.
help           - Displays a list of commands.
http           - Changes to the `netsh http' context.
interface      - Changes to the `netsh interface' context.
ipsec          - Changes to the `netsh ipsec' context.
ipsecdosprotection - Changes to the `netsh ipsecdosprotection' context.
lan            - Changes to the `netsh lan' context.
namespace      - Changes to the `netsh namespace' context.
netio          - Changes to the `netsh netio' context.
nps            - Changes to the `netsh nps' context.
ras            - Changes to the `netsh ras' context.
routing        - Changes to the `netsh routing' context.
rpc            - Changes to the `netsh rpc' context.
set            - Updates configuration settings.
show           - Displays information.
trace          - Changes to the `netsh trace' context.
wfp            - Changes to the `netsh wfp' context.
winhttp        - Changes to the `netsh winhttp' context.
winsock        - Changes to the `netsh winsock' context.

The following sub-contexts are available:
 advfirewall branchcache bridge dhcp dhcpclient dnsclient firewall http interface ipsec ipsecdosprotection lan namespace netio nps ras routing rpc trace wfp winhttp winsock

To view help for a command, type the command, followed by a space, and then
 type ?.

C:\Users\Administrator>_
```

</details>

Notice in particular that the command `netsh` uses `context` and `sub-context`, which means it needs to have the `context` specified first.
See the following details for `winsock`-specific `context` :

<details>

```
C:\Users\Administrator>netsh winsock /?

The following commands are available:

Commands in this context:
?              - Displays a list of commands.
audit          - Displays a list of Winsock LSPs that have been installed and removed.
dump           - Displays a configuration script.
help           - Displays a list of commands.
remove         - Removes a Winsock LSP from the system.
reset          - Resets the Winsock Catalog to a clean state.
set            - Sets Winsock options.
show           - Displays information.

To view help for a command, type the command, followed by a space, and then
 type ?.


C:\Users\Administrator>_
```

</details>

When trying to specify `reset` before `winsock`, an error is displayed (as expected):
```
C:\Users\Administrator>netsh reset winsock
The following command was not found: reset winsock.

C:\Users\Administrator>_
```

**Comment by illfated** [comment]
Notice also that the command context order is correct on the linked page "This script":
> ### [How do I reset Windows Update components?](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources#how-do-i-reset-windows-update-components)
> [This script](https://gallery.technet.microsoft.com/scriptcenter/Reset-WindowsUpdateps1-e0c5eb78) will completely reset the Windows Update client settings. It has been tested on Windows 7, 8, 10, and Windows Server 2012 R2. It will configure the services and registry keys related to Windows Update for default settings. It will also clean up files related to Windows Update, in addition to BITS related data.

- (https://gallery.technet.microsoft.com/scriptcenter/Reset-WindowsUpdateps1-e0c5eb78)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by illfated** [comment]
@sonabit : As you can see, the Pull Request #3194 has been merged and the Github page is updated. It may take a few days before the change migrates to the docs.microsoft.com page, but you can consider your feedback responded to and followed up by the Microsoft Docs team.
