### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by palpster** [MicrosoftDocs/windows-itpro-docs#3160]
The "Learn how to get the SID" link at the bottom of the "Set up a kiosk using Windows PowerShell" section  links to a page that does not (or no longer) exist(s).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f49c3f-ba5c-49e9-fad2-88cac155920a
* Version Independent ID: dc5e1f7e-61a8-bf2c-34b8-4046d024f4c2
* Content: [Set up a single-app kiosk (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/kiosk-single-app#feedback)
* Content Source: [windows/configuration/kiosk-single-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-single-app.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@palpster Thanks for pointing that out, I'll get that fixed.
