### ISSUE TITLE
Surface Hub 84 replacement PC screen issue

### ISSUE THREAD

**Issue by conversy** [MicrosoftDocs/windows-itpro-docs#3162]
Hello,

we updated the nvidia drivers to the latest, and we could not achieve to get replacement PC mode to work with 4k@120hz: the screen is split in half, with the left part working and the right one completely black. The screen works with one displayport link only, @ 30hz though.
On another machine, it seems that there are two 'virtual' screens that overlap...

I was working with a previous version of the drivers. Since surface hub is advertized as being suitable for nvidia cards, I was wondering if you were aware of any similar issue.

Cheers,

Stéphane

**Comment by jdeckerms** [comment]
@conversy You should contact Microsoft Support for assistance, they may be aware of known issues but I haven't heard of any. (https://support.microsoft.com/en-us/contactus/)

**Comment by conversy** [comment]
for the record: we bissected the nvidia drivers, the culprit seems to be 390.65 (388.71 works fine)

**Comment by illfated** [comment]
Thank you for providing extra feedback. Sort of happy to see that it was not a Microsoft issue.
