### ISSUE TITLE
One slight correction

### ISSUE THREAD

**Issue by jcs23576** [MicrosoftDocs/windows-itpro-docs#3167]
We just noticed the last name parsing will drop 3 character fields as well.  the documentation says less than 3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5128d9a-e02a-df9b-24cc-32711ad37b54
* Version Independent ID: fecafb19-6b37-1f2e-ba3d-5e0bf0d49d09
* Content: [Password must meet complexity requirements (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@jcs23576 I see, thanks for the feedback. I'll try to confirm if the tokens are "less than three characters" or should be "three characters or less" instead.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Justinha - Do you have any updates on this? Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @jcs23576 ,
could you please provide more details? I just have tested it in windows 10 (1709 and 1809), and it doesn't skip last names 3 characters long...
Thank you

**Comment by mypil** [comment]
@jcs23576  - We would like to follow up. Can you please respond to the query of MaratMussabekov?

Thank you.

**Comment by mypil** [comment]
@jcs23576 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
