### ISSUE TITLE
Cant access subfolders on phone.

### ISSUE THREAD

**Issue by zeonos** [MicrosoftDocs/windows-itpro-docs#317]
We use the Set up school PCs without intunes and use Azure only to login to 365 accounts.

We set it up so we allow USB keys, and they seem to work perfectly, but if you insert a phone you wont be able to access subfolders on that phone, it will just say its blocked.

How can we remove that single block and allow it?

We have tested with both android and apple, and its the same on both, we need to allow students to access their camera folder so they can use images and movies captured so they can edit it on the computers.

**Comment by CelesteDG** [comment]
Hello. Thank you for your question. Can you please provide more info as to what kind of external storage the devices are reporting themselves as?

You can use the RestrictLocalStorage policy in the SharedPC CSP (https://docs.microsoft.com/en-us/windows/client-management/mdm/sharedpc-csp) to unblock all storage options. This will unblock you right away. We'd like to investigate a bit further so if you can provide us with the type of storage that the devices are reporting themselves, we can investigate, 

Thank you.

**Comment by CelesteDG** [comment]
Hello. Please let us know if you have additional information so we can help with any issues. If we don't hear back by Dec 1st, we'll close the issue. Thank you.
