### ISSUE TITLE
AllowWindowsConsumerFeatures and ConfigureWindowsSpotlightOnLockScreen Remediation Failed

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#3171]
Hi there, can these 2 settings be changed so when the policy is deployed to unsupported SKUs it comes back as not applicable instead of failed?
It really hard to get Device configuration report properly done because these 2 settings come back as failed on all non Enterprise Windows version. 
I dont want to have 2 separate policies because a few are only applicable on Enterprise SKU.

That should work similarly to what occur when you deploy settings to older branches which are not supported, they come back and not applicable instead of remediation failed. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e8ecbe3-ba72-ec44-0591-7f604d50b1e3
* Version Independent ID: 9d5ff118-d539-dd6e-ae3e-102392c22287
* Content: [Policy CSP - Experience](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-experience)
* Content Source: [windows/client-management/mdm/policy-csp-experience.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-experience.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by jdeckerms** [comment]
@schenardie That's good input, thank you. If you wouldn't mind, could you submit it via the Feedback Hub? Your suggestion is about the product rather than the documentation, and using the Feedback Hub, it will go directly to the engineering team. Thanks!
