### ISSUE TITLE
[LOC] "USB サム ドライブの選択" needs to be replaced with "USBドライブの選択"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3173]
https://docs.microsoft.com/ja-jp/surface/microsoft-surface-data-eraser

related issue: #3159

**Comment by mypil** [comment]
@officedocsbot assign @OfficeGlobal

**Comment by mypil** [comment]
@OfficeGlobal - Kindly assist with this Translation (Localization) issue. Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@dongmicro - Can you assist with this Translation (Localization) issue?

Thank you.

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Do you have any updates? Thanks.

cc: @AndreaBarr

**Comment by mypil** [comment]
@officedocsbot add label localization

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Can you please assist with this Translation (Localization) issue? Thanks.

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Can you please assist with this Translation (Localization) issue? Thanks.

**Comment by mypil** [comment]
@dongmicro - Any updates on this?

**Comment by mypil** [comment]
@officedocsbot unassign @OfficeGlobal

@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@officedocsbot unassign @mypil

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @MollyMalone
@officedocsbot add label localization

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
私は人間の翻訳のためにこの記事を送った。 約2週間かかります。 (I sent this article to be human translated.  It should take approximately 2 weeks.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by illfated** [comment]
Not sure if it is 100% fixed, because there is 1 line on that page with the current content

_図 2. USB サム ドライブの選択_

The text can be found under the image in step 4. , just before step 5.
Waiting for @hyoshioka0128 to verify if this text also needs to be changed.

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #3173.
Thanks.
