### ISSUE TITLE
[LOC] Windows Error Reporting

### ISSUE THREAD

**Issue by kemiyaza** [MicrosoftDocs/windows-itpro-docs#3177]
The following URL is not uneditable.
https://docs.microsoft.com/ja-jp/windows/deployment/upgrade/windows-error-reporting

Could you change the document editable? I'll update as the following text.

---

Windows Error Reporting

適用対象
・Windows10

注意
これは 300 レベルのある程度高度なトピックです。
この記事の見出しについては、Windows 10 のアップグレード エラーの解決を参照してください。

Windows のセットアップが失敗したとき、結果コードと拡張コードは Windows Error Reporting の イベント ID: 1001 の “情報” のイベントで記録されます。イベント名は WinSetupDiag02 です。イベントビューアーや Windows PowerShell でこのイベントを参照できます。

Windows PowerShell を利用する場合、管理者特権の Windows PowerShell のプロンプトで以下のコマンドを実行してください。

$events = Get-WinEvent -FilterHashtable @{LogName="Application";ID="1001";Data="WinSetupDiag02"}
$event = [xml]$events[0].ToXml()
$event.Event.EventData.Data

イベントビューアーの場合、以下の手順で実施します。

1. イベントビューアーを実行し、Windows ログ/アプリケーション を開きます。
2. [検索] をクリックし、"winsetupdiag02" を検索します。
3. 強調表示されているイベントをダブルクリックします。

注: 従来のオペレーティング システムでは、このイベント名は WinSetupDiag01 でした。

このイベントには 10 個のパラメーターが含まれています。

P1: セットアップの方法 (1=メディア,5=WindowsUpdate,7=Media Creation Tool)
P2: セットアップのモード (x=デフォルト,1=ダウンレベル,5=ロールバック)
P3: ターゲット OS のアーキテクチャ (x=default,0=X86,9=AMD64)
P4: インストールの結果 (x=default,0=成功,1=失敗,2=キャンセル,3=ブロック)
P5: 結果コード (例: 0xc1900101)
P6: 拡張コード (例: 0x20017)
P7: ソース OS のビルド番号 (例: 9600)
P8: ソース OS のブランチ (通常は利用しません)
P9: ターゲット OS のビルド番号 (例: 16299)
P10: ターゲット OS のブランチ (例: rs3_release)

イベントはエラーの詳細を診断するために用いられるログ ファイルのパスを示すリンク情報が含まれます。以下にアップグレードが成功した場合のイベントの例を示します。

**Comment by mypil** [comment]
@officedocsbot assign @OfficeGlobal

**Comment by mypil** [comment]
@OfficeGlobal - Kindly assist with this Translation (Localization) issue. Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@dongmicro - Can you assist with this Translation (Localization) issue?

Thank you.

**Comment by kemiyaza** [comment]
@mypil Thanks. But, @dongmicro hasn't done.

**Comment by mypil** [comment]
@kemiyaza - I will follow up to get the issue addressed. Thanks.

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Do you have any updates? Thanks.

cc: @AndreaBarr

**Comment by dongmicro** [comment]
To enable to "edit" we would need to setup a structure supporting the "edit" including a group of people can monitor/review/approve/implement the suggestions. We need to work on this and it will take some time. Also currently the repo hosting this doc is going to be migrated and this migration effort is putting localization on hold till the migration is done.

**Comment by kemiyaza** [comment]
I will assist the localization for ja-jp under deployment URL path. 
https://docs.microsoft.com/ja-jp/windows/deployment/
I wait for your update. Thank you very much.

**Comment by mypil** [comment]
@officedocsbot Add label Translation (Localization)

**Comment by kenwith** [comment]
@officedocsbot add label hello

**Comment by mypil** [comment]
@officedocsbot add label localization

**Comment by mypil** [comment]
@kemiyaza - please refer to the answer from dongmicro for this issue. We will proceed to close this issue for now.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
