### ISSUE TITLE
Set without GPO?

### ISSUE THREAD

**Issue by seilermi** [MicrosoftDocs/windows-itpro-docs#3178]
It would be nice to know how to enable this setting via Registry or PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e54fd0e4-8388-8c8d-6e0b-aa24fc6449b4
* Version Independent ID: 14f950fd-3333-d362-af35-a313854fab9a
* Content: [Create global objects (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-global-objects#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/create-global-objects.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/create-global-objects.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@seilermi - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by Malind19** [comment]
@mypil , I could not find an example for PowerShell or Registry edit online. Can we please ask from the MS team?

**Comment by get-itips** [comment]
Hello @seilermi
**Thanks for your feedback. We really appreciate it.**
Currently, is not possible to perform the actions described in the article using Ps or Registry.
The reason behind this is that _security information is stored in templates (.inf files) or in the Secedit.sdb database_.

I encourage you to look into this resources

https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/security-policy-settings

https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/secedit

**Hope this information helps you.**

**Comment by mypil** [comment]
@seilermi - From our understanding, the issue you raised has been answered by get-itips. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by seilermi** [comment]
Thank you for answering very quickly.
