### ISSUE TITLE
Location Slightly Incorrect?

### ISSUE THREAD

**Issue by nitvit610** [MicrosoftDocs/windows-itpro-docs#3180]
Believe Location section should be changed as it missing Policies section
Before: 
Computer Configuration\Windows Settings\Security Settings\Local Policies\Security Options
After:
Computer Configuration\Policies\Windows Settings\Security Settings\Local Policies\Security Options

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75ab75c2-3bfd-bde6-8341-65ba79e9fe65
* Version Independent ID: 7224910c-ac05-26b2-f712-9a5993432615
* Content: [Interactive logon Machine inactivity limit (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by nitvit610** [comment]
Have had another look, I believe that when creating a GPO it requires the extra policy bit mentioned above, however when looking in GPEdit it does not require it.

**Comment by Justinha** [comment]
@nitvit610 thanks for the correction! Would you be kind enough to submit a pull request with the change? I'm happy to fix on my side too but we also want to encourage reader contributions like this.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Justinha - Let me assign @joinimran to help create the PR for this issue. 

@joinimran - As discussed, kindly review this issue and please assist to create the PR. Thank you.

**Comment by mypil** [comment]
@nitvit610 - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
