### ISSUE TITLE
jamf Uninstall Script

### ISSUE THREAD

**Issue by lyonheart14** [MicrosoftDocs/windows-itpro-docs#3183]
The example jamf uninstall script refers to the app as "Microsoft Defender.app" instead of "Microsoft Defender ATP.app"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7a3b63b-afc5-1b25-3a30-e75c788f4a93
* Version Independent ID: 85498c85-fe13-fead-3bac-44db5614db0d
* Content: [Microsoft Defender ATP for Mac](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
OK, have you verified that the actual file name is `Microsoft Defender ATP.app` so both the text example and the preceding image needs to be updated with the correct app file name? (I don't have access to those resources, so I am unable to verify this myself.) Web search returns `Microsoft Defender.app` , but the results are mostly from Microsoft Docs pages in various languages. Searching only for "`Microsoft Defender ATP.app`" returns no search results.

**Comment by lyonheart14** [comment]
I have verified it by attempting to run the jamf script and failing.  Then, I saw the command under the "Uninstallation" section.  I have also verified it by checking that the full application name is 'Microsoft Defender ATP.app' on Microsoft Defender Preview build 100.26.34.

**Comment by illfated** [comment]
Thanks, that is a step closer to a solution. Do you know if there is any online source for the install files where the actual install file name can be verified?

Anyway, to me it looks like there will be material here for opening a Pull Request to update and correct the `.app` package name, both in the installation script and the rest of the documentation (including images).

**Comment by lyonheart14** [comment]
As the product is in Limited Preview, access to the installation files is not publicly available.

**Comment by illfated** [comment]
Fair enough, very well. Thank you for confirming that side of the issue.

Based on all the above, I would like to hear from @mjcaparas or @DaniHalfin to confirm the next step to improve the documentation.

**Comment by maximvelichko** [comment]
@lyonheart14 , Thanks for reporting it! I'll fix the issue

**Comment by illfated** [comment]
Ref. PR #3235 (as above).

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@lyonheart14 

With the help of your feedback, an update to the documentation has been published.

Thank you for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
