### ISSUE TITLE
Cannot complete provisioning

### ISSUE THREAD

**Issue by GuilioM** [MicrosoftDocs/windows-itpro-docs#3186]
I am using the **Set up school PCs** for multiple tenants. We experience that at times, when installing and provisioning a device using the flashdrive prepared by the **Set up school PCs** app, devices does not automatically connect to the internet and update Intune with the device enrollment nor is it able to collect device/user policies.

**Comment by jdeckerms** [comment]
@GuilioM I'm sorry you're having trouble with the provisioning packages from the app. Please contact Support for assistance, so they can help identify the problem and find a solution for you. (https://support.microsoft.com/en-us/contactus/)
