### ISSUE TITLE
Wrong registry key for setting telemetry level

### ISSUE THREAD

**Issue by chrymsft** [MicrosoftDocs/windows-itpro-docs#3188]
Please use this path for reg key for diagnostic data level: 
HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\DataCollection

Do not use: 
HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\DataCollection (AllowTelemetry)

The incorrect path is being used in the section "Distribute the deployment script at scale"

**Comment by jdeckerms** [comment]
hi @cy10038 Which topic is this in regards to?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@chrymsft - We would like to follow up on this. May we know which Microsoft document link you used in reference to this issue? Please share it with us so we can investigate and make the necessary changes to improve the MS document for accuracy.

Thank you.

**Comment by mypil** [comment]
@chrymsft - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
