### ISSUE TITLE
Traduction illisible !

### ISSUE THREAD

**Issue by AlexLaforge** [MicrosoftDocs/windows-itpro-docs#3192]
La traduction automatique est LAMENTABLE : cet article est inutile en l'état actuel.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: cea461b2-8bc5-3ed2-3178-5fe0cd7249f3
* Version Independent ID: d2ded07c-2b8b-3223-44c6-0c8be3bd0214
* Content: [Accès réseau ne pas autoriser l’énumération anonyme des comptes SAM et des partages (Windows 10)](https://docs.microsoft.com/fr-fr/windows/security/threat-protection/security-policy-settings/network-access-do-not-allow-anonymous-enumeration-of-sam-accounts-and-shares#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-access-do-not-allow-anonymous-enumeration-of-sam-accounts-and-shares.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/threat-protection/security-policy-settings/network-access-do-not-allow-anonymous-enumeration-of-sam-accounts-and-shares.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@AlexLaforge - Merci d'avoir envoyé vos commentaires.

Y a-t-il quelque chose dans cet article que vous suggérez d'être ajouté ou édité?

S'il vous plaît aider en fournissant plus de détails sur ce qui devrait être changé et / ou inclus. Nous vous saurions gré de partager le texte approprié et où il devrait être placé de sorte qu'un PR puisse être créé.

**Comment by AlexLaforge** [comment]
Bonjour, Je suggère de payer un traducteur. Ce n’est pas mon métier. Mon métier consiste à lire des textes mal traduits par des robots sur le site de Microsoft.

Le 8 avr. 2019 à 11:43, Joyce Y. <notifications@github.com<mailto:notifications@github.com>> a écrit :


@AlexLaforge<https://github.com/AlexLaforge> - Merci d'avoir envoyé vos commentaires.

Y a-t-il quelque chose dans cet article que vous suggérez d'être ajouté ou édité?

S'il vous plaît aider en fournissant plus de détails sur ce qui devrait être changé et / ou inclus. Nous vous saurions gré de partager le texte approprié et où il devrait être placé de sorte qu'un PR puisse être créé.

**Comment by mypil** [comment]
@AlexLaforge - Laissez-moi transmettre cette problème à notre équipe de traduction (localisation), qui pourrait peut-être vous aider à la résoudre. Je vous remercie.

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

Thank you.

**Comment by mypil** [comment]
@officedocsbot add label localization

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this.  Can you please assist with this Translation (Localization) issue?

Thank you.

**Comment by PawelFronczak** [comment]
Under investigation

**Comment by mypil** [comment]
@PawelFronczak @dongmicro - Any updates on this?

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@officedocsbot unassign @mypil

**Comment by mypil** [comment]
@officedocsbot unassign @mypil

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @MollyMalone
@officedocsbot add label localization

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by e0i** [comment]
@TinaMcN Would you be able to assist with this French localization issue that seems to be MT based?

**Comment by e0i** [comment]
@TinaMcN Following up for updates.

**Comment by TinaMcN** [comment]
Je m'excuse pour le retard à agir sur cette rétroaction.  L'article a maintenant été envoyé à la traduction humaine, il faudra quelques semaines pour être complété.

**Comment by TinaMcN** [comment]
@AlexLaforge L'article est maintenant traduit par l'homme.  Pouvez-vous confirmer la qualité est ok maintenant?

**Comment by AlexLaforge** [comment]
Bonjour @TinaMcN , bien que cette traduction présente une niveau inférieur à ce qui était en vigueur les 10 dernières années dans la documentation de Microsoft, je pense que le niveau de compréhension, moyennement quelques efforts du lecteur, est suffisant. Il va sans dire que contrairement à la précédente traduction effectuée par le traducteur automatique, c'ets beaucoup mieux. Merci pour cet effort !
