### ISSUE TITLE
SCCM vs. Intune for WIP

### ISSUE THREAD

**Issue by Mark7even** [MicrosoftDocs/windows-itpro-docs#3196]
Any downsides to deploying WIP through SCCM, or does it have feature parity with deployment through Intune?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4043626d-5475-cd46-e107-6077ff4701f7
* Version Independent ID: 59ffa7ff-97ca-2f34-3c92-a09ab10c0a4e
* Content: [Create and deploy a Windows Information Protection (WIP) policy using System Center Configuration Manager (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-sccm)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-sccm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/create-wip-policy-using-sccm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by Jcoetsee** [comment]
@Mark7even I wouldn't say there are any downsides if configured and setup correctly, SSCM has the capability to do that. Although Intune is very well structured in order to also apply app protection policies, conditional access etc... Just for context, are you considering a platform you want to use for an environment? In my personal experience, Intune is great for high-level Windows/app policies

**Comment by mypil** [comment]
@Mark7even - Thank you for this inquiry.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Mark7even - From our understanding, the issue you raised has been answered by Jcoetsee. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
