### ISSUE TITLE
0xc0290905 not listed

### ISSUE THREAD

**Issue by ArindamPaulJU** [MicrosoftDocs/windows-itpro-docs#3199]
![Screenshot](https://user-images.githubusercontent.com/49384760/55698765-1834b100-59e5-11e9-934d-ff3beaa4be47.jpg)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ArindamPaulJU - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
