### ISSUE TITLE
Alert on SCEP Installation

### ISSUE THREAD

**Issue by satish860** [MicrosoftDocs/windows-itpro-docs#3201]
The documentation mentions that after the SCEP installation there is an alert will be sent. Can you please provide an example for the alert and which release of windows it is supported.

**Comment by illfated** [comment]
@satish860 : Seeing that you have opened this issue here on Github instead of posting the comment on the related docs page, could you provide the correct link for the documentation in question? This information is needed to follow up your request.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@satish860 - We would like to follow up on this. May we know which Microsoft document link you used in reference to this issue? Please share it with us so we can investigate and make the necessary changes to improve the MS document for accuracy.

**Comment by illfated** [comment]
@satish860 : Are you talking about https://docs.microsoft.com/en-us/windows/client-management/mdm/clientcertificateinstall-csp

> **ClientCertificateInstall/SCEP**
>
> Node for SCEP.
>
> > **Note** An alert is sent after the SCEP certificate is installed.
>

or are you referring to a different page?

Please notice that the [docs.microsoft.com IT Pro Github site](https://github.com/MicrosoftDocs/windows-itpro-docs/) is primarily contributing improvements to the Microsoft IT Pro documentation.

If we do not see any feedback from you within a reasonable amount of days, we may presume that you are no longer following this issue.

**Comment by mypil** [comment]
@satish860 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
