### ISSUE TITLE
Four Seasons Logo Permission?

### ISSUE THREAD

**Issue by totesfawkward** [MicrosoftDocs/windows-itpro-docs#3204]
The screenshot for "Kiosk setup experience" uses the Four Seasons Hotels logo (or something extremely similar) with the Contoso name. Do we have permission from them to use their logo in our documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d6356b-87ff-8c3a-56ef-1270a823d3ab
* Version Independent ID: 4d6ae878-66cf-0e10-bdf3-bdd6054cbc9d
* Content: [What's new in Windows 10, version 1809](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809#feedback)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1809.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1809.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@totesfawkward  - Thank you for submitting this feedback.

I will get this over to @greg-lindsay for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by mypil** [comment]
@greg-lindsay - Can you please assist to answer the question in this issue?

Thank you.

**Comment by mypil** [comment]
@greg-lindsay - I would like to follow up on this. Can you please assist to answer the question in this issue?

Thank you.

**Comment by mypil** [comment]
@greg-lindsay - Do you have any updates on this?

Thank you.

**Comment by mypil** [comment]
@greg-lindsay - I would like to follow up on this.  Do you have any updates on this?

Thank you.

**Comment by illfated** [comment]
Just to make it slightly easier to look up the images in question:
- https://www.bing.com/images/search?q=Four+Seasons+Hotels+logo&qpvt=Four+Seasons+Hotels+logo&FORM=IGRE
- https://docs.microsoft.com/en-us/windows/whats-new/images/singleapp_contosohotel_inframe%402x.png
- https://docs.microsoft.com/en-us/windows/whats-new/images/multi-app_kiosk_inframe.png

**Comment by mypil** [comment]
@totesfawkward - Thank you for pointing this out.

I have coordinated with the doc owner and the Four Seasons Logo has been removed from the screenshots. From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
