### ISSUE TITLE
Event log folder location?

### ISSUE THREAD

**Issue by AbfSailor** [MicrosoftDocs/windows-itpro-docs#3205]
Which event log folder would one expect to find these logs in? Can you please provide this information in the technical reference?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 883a052a-0ef9-2ced-fc36-046ff19b4dd4
* Version Independent ID: 5d98571c-11f2-fdba-d7d5-be42822394b3
* Content: [Client Event Logs](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/client-event-logs#feedback)
* Content Source: [mdop/mbam-v25/client-event-logs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/client-event-logs.md)
* Product: **w10**
* Technology: **mdop**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@AbfSailor - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by AbfSailor** [comment]
Thank you Joyce! :)

**Comment by Malind19** [comment]
@mypil Created PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3254

**Comment by mypil** [comment]
@AbfSailor - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by AbfSailor** [comment]
Thank you Joyce! :)

**Comment by mypil** [comment]
@officedocsbot close
