### ISSUE TITLE
Where's the "what's new" for non-IT pros?!

### ISSUE THREAD

**Issue by schroedey** [MicrosoftDocs/windows-itpro-docs#3210]
I was looking for a list of feature changes and bug and security fixes, in one well-organized place, for users of Windows 10.  That is, something that will tell me what I need to know to keep up with user interface changes, new policies, etc.  This page may be great for IT admins, and as a technology professional with a lot of Windows experience, I can understand it... but what about for someone like my dad, who just wants to make sense of the changes that keep happening when Windows installs updates and suddenly screens are reorganized, things are renamed, etc.?  Where does *he* go?  If there's a good entry point into Microsoft's official documentation that describes that, it sure isn't easy to figure out how to get there.  I get that there's lots of 3rd-party press coverage by a whole list of websites that cover the tech industry, but I'm not looking for that.  I'm looking for an ad-free, from-the-source, description for regular users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d6356b-87ff-8c3a-56ef-1270a823d3ab
* Version Independent ID: 4d6ae878-66cf-0e10-bdf3-bdd6054cbc9d
* Content: [What's new in Windows 10, version 1809](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809#feedback)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1809.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1809.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by jdeckerms** [comment]
@schroedey Documentation for "regular users" is on support.microsoft.com and in the Tips app on Windows 10. Here's their "What's new" topic: https://support.microsoft.com/en-us/help/4043948
