### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/windows-itpro-docs#3211]
You can now check on the status of your computers within hours of running the deployment script link is broken.  Can the steps on checking the status be included here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f20e3377-fdbc-ac87-239e-7184db24a685
* Version Independent ID: 0464da82-efa4-b147-bba9-d6802cf9d273
* Content: [Frequently asked questions and troubleshooting Windows Analytics](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-faq-troubleshooting#feedback)
* Content Source: [windows/deployment/update/windows-analytics-FAQ-troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-FAQ-troubleshooting.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
Looks like the page has moved to the following page: https://techcommunity.microsoft.com/t5/Windows-Analytics-Blog/You-can-now-check-on-the-status-of-your-computers-within-hours/ba-p/187213

Unless the OMS page has started a deprecation process and is to be removed soon™ in favor of the Azure Portal, I will offer a Pull Request to restore the link to a working state.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by illfated** [comment]
@russrimm : when creating a  Pull Request to resolve a ticket, it is very useful to link from the PR back to the open issue ticket so other users who read this ticket are made aware of the PR to avoid multiple Pull Requests with the same content. Ref. your PR #3218 and my PR #3221.

**Comment by mypil** [comment]
@russrimm - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
