### ISSUE TITLE
copy ppkg from network share then execute during OOBE

### ISSUE THREAD

**Issue by dbdmora** [MicrosoftDocs/windows-itpro-docs#3223]
Are we not able to copy a provisioning package from a network drive to the local PC and execute the ppkg during OOBE?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f207b491-f262-43cf-1002-8f3fb2a052c6
* Version Independent ID: 5358ed30-928c-e397-04e7-7f4c602777e2
* Content: [How provisioning works in Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-how-it-works#feedback)
* Content Source: [windows/configuration/provisioning-packages/provisioning-how-it-works.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/provisioning-packages/provisioning-how-it-works.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@dbdmora No, only at runtime.
