### ISSUE TITLE
Missing column descriptions on some Advanced Hunting columns

### ISSUE THREAD

**Issue by hwayouhsu** [MicrosoftDocs/windows-itpro-docs#3230]
Missing description for 
* AlertEvents - Category
* AlertEvents - Severity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 465c3bf3-a207-3113-1052-f237a224ebfb
* Version Independent ID: 733dac2c-2e47-8c0e-a0c1-fd925c3184ea
* Content: [Advanced hunting reference in Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/advanced-hunting-reference-windows-defender-advanced-threat-protection#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-atp/advanced-hunting-reference-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/advanced-hunting-reference-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by hwayouhsu** [comment]
Missing description for 
* MachineInfo - ClientVersion
* MachineInfo - OsVersion
* MachineInfo - RegistryMachineTag

**Comment by hwayouhsu** [comment]
I will add other ones as I go through them

**Comment by illfated** [comment]
Oh, I see. At first I thought that you meant that the descriptions were missing from existing points in the schema, but I noticed that those you listed also are missing **Column name** entries as well as the **Description** part.

It looks like the **Data type** will for the most part be _string_ , but you are welcome to specify the Data type to get it correct right away.

Please also note: The Microsoft Docs team will appreciate source references for your information.

**Comment by hwayouhsu** [comment]
I am comparing the document https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/advanced-hunting-reference-windows-defender-advanced-threat-protection against schema in https://securitycenter.windows.com/hunting

I am commenting on the docs.microsoft.com page. I guess from which page I made the comments is not apparent in GitHub.

**Comment by hwayouhsu** [comment]
MachineNetworkInfo has a TunnelType column. Is that the same as TunnelingType described on https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/advanced-hunting-reference-windows-defender-advanced-threat-protection  ?

**Comment by hwayouhsu** [comment]
These are missing also
FileCreationEvents->IsAzureInfoProtectionApplied 
FileCreationEvents->IsWindowsInfoProtectionApplied
FileCreationEvents->SensitivityLabel
FileCreationEvents->SensitivitySubLabel

**Comment by illfated** [comment]
> I am comparing the document https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/advanced-hunting-reference-windows-defender-advanced-threat-protection against schema in https://securitycenter.windows.com/hunting
> 
> I am commenting on the docs.microsoft.com page. I guess from which page I made the comments is not apparent in GitHub.

Thank you for posting your reference document link. The Microsoft Docs page is linked in your original post, but the securitycenter.windows.com page needed a manually posted reference link.
***
As you can see in the commit links above, several of your suggested changes have been merged via Pull Requests from a private (internal) repository:
- https://github.com/MicrosoftDocs/windows-itpro-docs/commit/d6d4a0d289979fc41db31c75ededda8e1ad8268d
- https://github.com/MicrosoftDocs/windows-itpro-docs/commit/5f9cee3e392a408d5da115a47cc629521e501976

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@hwayouhsu 

From our understanding, the mentioned problems have already been addressed by document authors via the commits referenced above.

Thank you for bringing this issue to attention.

**Comment by e0i** [comment]
@officedocsbot close
