### ISSUE TITLE
Intranet URLs not accessible in Chrome when targeted by WIP

### ISSUE THREAD

**Issue by ankush271017** [MicrosoftDocs/windows-itpro-docs#3237]
My devices are hybrid Azure AD join.
Have targeted a WIP Policy with Enrollment.
Even added /*AppCombat*? in Cloud resouces.

When trying to access organization Internal websites it's getting blocked in Chrome & when trying to access the same by IE or EDGE which are marked as managed apps, it's working fine.

Want to know, is it possible to access Intranet sites by Google Chrome when targeted by WIP.

Came across below add-in, does it can help me to access Intranet websites from chrome.

https://chrome.google.com/webstore/detail/windows-10-accounts/ppnbnpeolgkicgegkbkbjmhlideopiji?hl=en

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ankush271017 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by illfated** [comment]
@ankush271017 : At first, I thought that this question should be asked in one of the Google Chrome forum pages, but then I remembered that Microsoft has launched a Chromium-based version of Edge and that this might become very relevant to Microsoft too.
- https://www.microsoftedgeinsider.com/en-us/download/

Could you perhaps, in addition to telling us which Microsoft Docs page is in need of improvement as a reference page for your issue, also test if the insider builds of Microsoft Edge Chromium will face the same issue as you have found using Google Chrome?

**Comment by ankush271017** [comment]
In my case, Google Chrome is added in exempt apps list.
But the intranet links are getting blocked for version Windows 1803 & the same is working for 1809 version.
I'm unable to understand the difference in behavior.

I've added the intranet URLs in Cloud resources.

Just wanted to understand the behavior & how exactly it should work.

If we try to access internal links on Edge or IE, it's working for both the versions.

I think now Chrome has capability of understanding Conditional Access.

https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/app-behavior-with-wip

https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip

**Comment by mypil** [comment]
@ankush271017 - Thank you for providing additional details.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
