### ISSUE TITLE
missing % in the section on facial recognition

### ISSUE THREAD

**Issue by dugates** [MicrosoftDocs/windows-itpro-docs#3239]
The section on facial recognition needs to be updated to be False Accept Rate (FAR): &lt;0.001% rather than False Accept Rate (FAR): &lt;0.001 as including the % sign makes the FAR the expected less than 1 in 100,000 without it, it is less than 1 in 1,000 

 Facial recognition sensors
To allow facial recognition, you must have devices with integrated special infrared (IR) sensors and software. Facial recognition sensors use special cameras that see in IR light, letting them tell the difference between a photo and a living person while scanning an employee’s facial features. These sensors, like the fingerprint sensors, must also include anti-spoofing measures (required) and a way to configure them (optional).
False Accept Rate (FAR): &lt;0.001

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59c4b7fc-8a91-5d34-d483-f644c248ad30
* Version Independent ID: 1f14bf28-71e0-121d-7890-c2d3b921c106
* Content: [Windows Hello biometrics in the enterprise (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-biometrics-in-enterprise#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-biometrics-in-enterprise.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-biometrics-in-enterprise.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by illfated** [comment]
Good point, the documentation should be consistent in format and usage of data values and references.
Whenever a value is repeated, its denomination or type should also be included to avoid confusion.
See both occurrences of `0.001` below:

Specific reference link: **[Fingerprint sensor requirements](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-biometrics-in-enterprise#fingerprint-sensor-requirements)**
(https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-biometrics-in-enterprise#fingerprint-sensor-requirements)

> **Acceptable performance range for small to large size touch sensors**
> 
> -   False Accept Rate (FAR): &lt;0.001 – 0.002%
> 
> -   Effective, real world FRR with Anti-spoofing or liveness detection: &lt;10%
> 
> **Acceptable performance range for swipe sensors**
> 
> -   False Accept Rate (FAR): &lt;0.002%
> 
> -   Effective, real world FRR with Anti-spoofing or liveness detection: &lt;10%
> 
> ### Facial recognition sensors
> To allow facial recognition, you must have devices with integrated special infrared (IR) sensors and software. Facial recognition sensors use special cameras that see in IR light, letting them tell the difference between a photo and a living person while scanning an employee’s facial features. These sensors, like the fingerprint sensors, must also include anti-spoofing measures (required) and a way to configure them (optional).
> 
> -   False Accept Rate (FAR): &lt;0.001
> 
> -   False Reject Rate (FRR) without Anti-spoofing or liveness detection: &lt;5%
> 
> -   Effective, real world FRR with Anti-spoofing or liveness detection: &lt;10%

**Comment by illfated** [comment]
There is a PR opened for this issue: **[Updating typo for face FAR](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3245)** #3245

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@dugates - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by dugates** [comment]
> @dugates - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.
> Thank you for your contribution to make the docs better! Much appreciated!

Thank you, I will watch for the update in the near term.

**Comment by mypil** [comment]
@officedocsbot close
