### ISSUE TITLE
EnableIEHosting: Incorrect registry key references and poor wording

### ISSUE THREAD

**Issue by ralish** [MicrosoftDocs/windows-itpro-docs#3246]
&gt; **For x86 systems or for 32-bit processes on x64 systems**: Go to the `HKLM\SOFTWARE\MICROSOFT\.NETFramework` registry key and change the **EnableIEHosting** value to **1**.
For *32-bit processes on x64 systems* the correct registry key is surely: `HKLM\Software\Wow6432Node\Microsoft\.NETFramework`

&gt; **For x64 systems or for 64-bit processes on x64 systems**: Go to the `HKLM\SOFTWARE\Wow6432Node\MICROSOFT\.NETFramework` registry key and change the **EnableIEHosting** value to **1**.
The phrasing *For x64 systems or for 64-bit processes on x64 systems* is redundant given you can't run a 64-bit process on an x86 system. The correct registry key is also surely: `HKLM\Software\Microsoft\.NETFramework`

**Proposed Rewrite**
1. **For x86 systems or for 64-bit processes on x64 systems**: Go to the `HKLM\Software\Microsoft\.NETFramework` registry key and change the **EnableIEHosting** value to **1**.
2. **For 32-bit processes on x64 systems**: Go to the `HKLM\Software\Wow6432Node\Microsoft\.NETFramework` registry key and change the **EnableIEHosting** value to **1**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57b128fb-0c11-2016-e098-45a3cb80c921
* Version Independent ID: a3befa01-4a58-c409-33fa-0eb0f5f90ada
* Content: [.NET Framework problems with Internet Explorer 11 (Internet Explorer 11 for IT Pros)](https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/net-framework-problems-with-ie11)
* Content Source: [browsers/internet-explorer/ie11-deploy-guide/net-framework-problems-with-ie11.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/internet-explorer/ie11-deploy-guide/net-framework-problems-with-ie11.md)
* Product: **ie11**
* Technology: **internet-explorer**
* GitHub Login: @shortpatti
* Microsoft Alias: **shortpatti**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ralish - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @ralish , pull request was created
Dear @mypil , looks like [Managed hosting controls are disabled in Internet Explorer from the .NET Framework 4](https://support.microsoft.com/help/2996039/managed-hosting-controls-are-disabled-in-internet-explorer-from-the-ne) should be changed as well

Thank you

**Comment by mypil** [comment]
@MaratMussabekov - for the other article, we will have to discuss that further in another forum. Thank you for pointing it out.

**Comment by mypil** [comment]
@ralish  - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
