### ISSUE TITLE
Scenarios - Is KMS at parity with AD activation?

### ISSUE THREAD

**Issue by kyjeeper** [MicrosoftDocs/windows-itpro-docs#3250]
In the scenarios, it speaks of KMS & MAK easily rolling over to CSP when detected. If customer has AD Activation in place instead of KMS, is the workflow the same? Will known machines in the field that are AD Activated just rollover to subscription activated Enterprise based on logged on user & assigned license in the portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-subscription-activation#inherited-activation)
* Content Source: [windows/deployment/windows-10-enterprise-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-enterprise-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
Hello @kyjeeper , Yes, Machines activated with AD based activations will roll over to subscription-based enterprise edition when users with the assigned license will sign-in to the machine. 

Thanks.

**Comment by mypil** [comment]
@kyjeeper - Thank you for submitting feedback.

From our understanding, the issue has been answered by joinimran. If you feel it hasn't been answered please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
