### ISSUE TITLE
SECCON

### ISSUE THREAD

**Issue by rvanstone** [MicrosoftDocs/windows-itpro-docs#3252]
a good concept. Are there any sample configurations to help illustrate the framework's effectiveness.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3fa1093-f014-b19a-0a3f-621bb239b23d
* Version Independent ID: eaf6cb9a-9d2a-5ea0-71ba-0801e073d49e
* Content: [Windows security configuration framework](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-security-configuration-framework/windows-security-configuration-framework#feedback)
* Content Source: [windows/security/threat-protection/windows-security-configuration-framework/windows-security-configuration-framework.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-security-configuration-framework/windows-security-configuration-framework.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @appcompatguy
* Microsoft Alias: **appcompatguy**

**Comment by appcompatguy** [comment]
We validated the configurations and approaches with several preview customers, if that's what you're asking.

**Comment by illfated** [comment]
I think the OP meant to ask if there are any written configuration examples which could be added to the documentation page for viewing and testing (e.g. try before buy samples). Considering the scope of this topic, though, I imagine that such examples would include so much work that it might not be feasible to create any stand-alone examples for the public to view and test.

**Comment by csharmath** [comment]
+1 for a better documentation explaining what is this about and how to use so it's more approachable on first visit.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by Dergib** [comment]
Has there been a follow up to level 1 and level 2 (SECCON frameworks) - Level 2 and Level 1 guidance is coming soon apparently but this article appears to be over a year old?

**Comment by appcompatguy** [comment]
> Has there been a follow up to level 1 and level 2 (SECCON frameworks) - Level 2 and Level 1 guidance is coming soon apparently but this article appears to be over a year old?

The dates didn't get updated in the template we started with (will be fixed when the next update is published so they're accurate) - the article is only about a month old. We are working on it, but there are a number of initiatives to align to in order to drive the right outcome. We recently published this for Azure - https://docs.microsoft.com/en-us/azure/active-directory/devices/concept-azure-managed-workstation - and are working with multiple teams to ensure that everyone is providing the same information in a usable way!

**Comment by Dergib** [comment]
Ah ok, that makes more sense. Thanks for the reply

**Comment by e0i** [comment]
@rvanstone 

We are closing this issue since your question seems to be answered. Feel free to re-open this issue if you feel it hasn't been answered.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
