### ISSUE TITLE
New-CIPolicyRule fails on Win10 1809 Professional Edition

### ISSUE THREAD

**Issue by limpidweb** [MicrosoftDocs/windows-itpro-docs#3255]
I am attempting to configure an Application Control policy on Win10 1809 Professional. According to this doc it is supported but when I run the command in PowerShell I get the following:

New-CIPolicy : Device Guard is not available in this edition of Windows.

Here is some information regarding the OS environment:
PS C:\users\User\Downloads\dgreadiness_v3.6\dgreadiness_v3.6&gt; .\DG_Readiness_Tool_v3.6.ps1 -Ready
###########################################################################
Readiness Tool Version 3.4 Release.
Tool to check if your device is capable to run Device Guard and Credential Guard.
###########################################################################
Running on a Virtual Machine. DG/CG is supported only if both guest VM and host machine are running with Windows 10, version 1703 or later with English localization.
###########################################################################
OS and Hardware requirements for enabling Device Guard and Credential Guard
 1. OS SKUs: Available only on these OS Skus - Enterprise, Server, Education, Enterprise IoT, Pro, and Home
 2. Hardware: Recent hardware that supports virtualization extension with SLAT
To learn more please visit: https://aka.ms/dgwhcr
###########################################################################

Credential-Guard is enabled and running.
HVCI is enabled and running.
Config-CI is enabled and running. (Audit mode)
HVCI, Credential-Guard, and Config-CI are enabled and running.
PS C:\users\User\Downloads\dgreadiness_v3.6\dgreadiness_v3.6&gt; Get-WindowsEdition -Online

Edition : Professional

PS C:\users\User\Downloads\dgreadiness_v3.6\dgreadiness_v3.6&gt; [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 481aaad1-c3ed-3eb1-bd29-ebad8f264edd
* Version Independent ID: dc5d9c47-e4aa-22ab-cb41-dfed57c517ac
* Content: [Windows Defender Application Control (WDAC) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jsuther1974
* Microsoft Alias: **justinha**

**Comment by ErVaDy** [comment]
I'm no expert but I guess the problem is axactly what the error says: that it is not supported by the OS.

I don't know what doc you refer to but at docs.microsoft.com you can read: 'WDAC policies can only be created on computers beginning with **Windows 10 Enterprise** or Professional editions or Windows Server 2016'. So if you use Windows 10 you need at least Enterprise, not Professional. The 'Professional editions'-part in the sentence is about Windows Server 2016.

**Comment by limpidweb** [comment]
Thanks for taking the time to post ErVaDy. The document that I was referring to was https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control.md

The quote that you included is from the correct document, but I do not agree with your conclusion. There are no 'Professional editions' of Windows Server, but there is a 'Professional Edition' of Windows 10.

Here are the desktop editions: https://www.microsoft.com/en-us/WindowsForBusiness/Compare
Here are the server editions: https://www.microsoft.com/en-us/cloud-platform/windows-server-pricing

The first link above seems to indicate that Application Control is not available in Windows 10 Pro as well, so I am thinking that the documentation is incorrect.

**Comment by ErVaDy** [comment]
I thought the article in question said '... or Professional editions **of** Windows Server 2016.' (and was thus indeed kind of confused by the term _professional edition of a server OS_, but I blamed that on a lack of knowledge of terminology on my part). By reading your reply I noticed my incorrect reading and thus interpretation.

You're absolutely right that it appears the documentation is incorrect. But as I mentioned I'm no expert (I just started reading about WDAC as I'm planning to start testing with it) so don't take my word for it.

**Comment by marcosmcampos** [comment]
I'm having the exact behavior on my fresh install of Win10 Pro. It also throws a message saying it's not supported on that version of Windows 10.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Thank you, @limpidweb @ErVaDy @marcosmcampos for your valuable comments.

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

**Comment by deletehead** [comment]
I was about to open up an issue: the documentation does not clearly state that it requires the Win10 Enterprise. Requesting clarification on this, as it required a lot of research. Third-party sources were much clearer on the requirement of Enterprise edition.

**Comment by dstreefkerk** [comment]
Just adding my support to this issue, the documentation needs to clarify that New-CIPolicy can only be executed on Win 10 Enterprise. Please scrap all mention of "Professional" versions of Windows from this article as it's not relevant and just leads to confusion!

**Comment by e0i** [comment]
@limpidweb 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
