### ISSUE TITLE
More specific URLs please?

### ISSUE THREAD

**Issue by Ry5ter** [MicrosoftDocs/windows-itpro-docs#3256]
Can we please be more specific than *.microsoft.com? I want to open up Microsoft Store for Business for users without internet access, but don't want them downloading all and sundry from download.microsoft.com etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 651b0b21-e639-2814-ebc6-94303a00ca2d
* Version Independent ID: 4587f785-d841-fd0e-7ec6-7ad895a0d4a7
* Content: [Prerequisites for Microsoft Store for Business and Education (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/prerequisites-microsoft-store-for-business#feedback)
* Content Source: [store-for-business/prerequisites-microsoft-store-for-business.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/prerequisites-microsoft-store-for-business.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@TrudyHa Could you kindly advise which sub-domains in specific would be listed for the proxy configuration in the article? 

We'd like to follow-up with content updates if necessary.

Thanks.

**Comment by H4DDSTER** [comment]
Could also do with details about what access is required e.g. we use an authenticating proxy with SSL Inspection for most categories so simply unblocking the website domains might not enable access e.g. proxy authentication breaks access

**Comment by computeronix** [comment]
To further surface this; I noticed this page: https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1903-endpoints

Which lists the following URLs for Microsoft Store
*.wns.windows.com
	storecatalogrevocation.storequality.microsoft.com
	img-prod-cms-rt-microsoft-com*
	store-images.microsoft.com
	.md.mp.microsoft.com
	*displaycatalog.mp.microsoft.com
	pti.store.microsoft.com
	storeedgefd.dsx.mp.microsoft.com
	markets.books.microsoft.com
	share.microsoft.com

Which ones are needed compared to the pre-reqs page and which ones are not needed?  Are they all needed?  Is that wildcard (*.microsoft.com) needed?  Is the wildcard *.wns.windows.com needed?

If so, could the appropriate URLs for Store for Business also be added to the connection endpoints page with a tag for Store for Business which would further surface and mention Store for Business on these pages (https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1903-endpoints)?
