### ISSUE TITLE
inactive machines

### ISSUE THREAD

**Issue by adzamri** [MicrosoftDocs/windows-itpro-docs#3258]
last line under "inactive machines" - 
expected text: Open a support ticket.
current text: Open a support ticket ticket.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5e07681-222a-ca3c-20f3-c98dabd935fa
* Version Independent ID: 6a9262d1-911f-bd4b-5366-7e6a0e31ca13
* Content: [Fix unhealthy sensors in Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/fix-unhealhty-sensors-windows-defender-advanced-threat-protection#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-atp/fix-unhealhty-sensors-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/fix-unhealhty-sensors-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
👍 Nice catch. I will open a PR to get it fixed.

**Comment by illfated** [comment]
BTW, even though the typo may have been ha simple copy-paste error (copy once, paste twice),
it still made me think of Monty Python's Life of Brian and the scene
"What have the Romans ever done for us":
- https://www.youtube.com/watch?v=Qc7HmhrgTuQ
 (... and from our father's father's father's fathers)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by adzamri** [comment]
LOL
