### ISSUE TITLE
Invalid schema

### ISSUE THREAD

**Issue by klishb** [MicrosoftDocs/windows-itpro-docs#3260]
Any of the examples provided do not validate properly against the XSD. Export-StartLayout also doesn't validate against the provided XSD.  See validation error:

Validation of current file using XML schema:

ERROR: Element '{http://schemas.microsoft.com/Start/2014/LayoutModification}LayoutModificationTemplate': No matching global declaration available for the validation root.

**Comment by illfated** [comment]
That looks like an issue you should contact Microsoft Support to get help solving.
- https://support.microsoft.com/contactus/

(unless you are a registered user of other existing Microsoft support services)

Please notice that this site is primarily focused on improving the Microsoft docs,
more specifically https://docs.microsoft.com/windows/#pivot=it-pro
and its subsidiary pages.

Did any of the Microsoft doc pages cause the issue you have posted?
If yes, which page can we work on improving based on your results?

**Comment by klishb** [comment]
I see.  Sorry I arrived here searching for the Start Menu Layout schema file.  I posted too quickly and didn't realize what this repo was or that my search led me to a schema file for taskbar instead.  Upon further investigation I believe the schema file may be valid for the taskbar portion of the layout xml file.

https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/configure-windows-10-taskbar.md

The documentation below states that you can add the taskbar configuration to the layout file so I assumed they used the same schema, but I'm now thinking they don't.  Not sure where that schema definition would be, but it could come in handy as I'm trying to troubleshoot an issue with a layout xml file.  Again, sorry about the confusion.  My mistake.

https://docs.microsoft.com/en-us/windows/configuration/customize-and-export-start-layout

**Comment by illfated** [comment]
Fair enough. I don't know enough about this specific topic to present an answer, but we can wait a few days to see if any of the Microsoft Docs team members can help out in any way or say if there is anything in the docs might be improved in some way to clarify your situation.

Let us check with @Justinha or @jdeckerms how to proceed from here, if the question can be answered here or if it is better to contact Microsoft Support. (Could take a day or so before we get some answers.)

**Comment by jdeckerms** [comment]
@klishb You might check out [Start layout XML reference](https://docs.microsoft.com/en-us/windows/configuration/start-layout-xml-desktop) to see if that helps with your questions. We don't have the XSD for Start layout in the library, but I'll suggest it to the product team.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@klishb - Thank you for submitting feedback.

From our understanding, the issue has been answered by illfated and jdeckerms. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
