### ISSUE TITLE
GPO doesn't make sense

### ISSUE THREAD

**Issue by CoMMyCZ** [MicrosoftDocs/windows-itpro-docs#3262]
"Turn off auto-restart notifications for update installations" - the default setting is not to show any notification, when you enable it, it doesn't show any notification, when you disable the setting, it doesn't show any notification again... When you leave it undefined, I guess  you know what happens 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184809a-63ff-ecc2-ab67-9c9f4df900f8
* Version Independent ID: ac25ee6c-4c57-58b3-1313-e4a53f53c5a1
* Content: [Manage device restarts after updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-restart#feedback)
* Content Source: [windows/deployment/update/waas-restart.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-restart.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@CoMMyCZ - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @CoMMyCZ ,
the GPO works following way:
enabled: notifications do not appear.
disabled or not configured: notifications for auto-restart appear.

if you experience different behavior, I would recommend following: run rsop.msc to check the resulting policy and make other GPOs are not affecting this setting.

Thank you

**Comment by mypil** [comment]
@CoMMyCZ - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
