### ISSUE TITLE
Intune Enrollment Status Page

### ISSUE THREAD

**Issue by bally-singh** [MicrosoftDocs/windows-itpro-docs#3263]
For Shared Devices the ESP will run for every user who is logging on. Is this supposed to be the case as this is causing delays to logon.

And is it possible to filter on ESP rather than having it on for all users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5d94e38-75da-740c-d0cc-82bf27ba9c24
* Version Independent ID: 800a29d5-425c-7c32-b901-c425658ada81
* Content: [Windows Autopilot Enrollment Status page](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/enrollment-status)
* Content Source: [windows/deployment/windows-autopilot/enrollment-status.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/enrollment-status.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by cloudtroll** [comment]
I would also like to know this answer. Also, my SCCM imaged Co-Managed devices get stuck at Account Setup stage and never go past that even though there are no policies assigned

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@bally-singh - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by cloudtroll** [comment]
@mypil To add to my comment. Not only do SCCM imaged Hybrid Azure joined machines receive the Enrollment page, but the reason they get stuck is because the users dont have an Intune license. This entirely defeats the purpose of have "Co-managed" machines where your workloads are split. 

Now I cant simply have an on-premise AD authenticated user sign into a machine without being stuck at this page.

**Comment by jseerden** [comment]
@bally-singh I published a blog post yesterday explaining how you can create a device configuration profile that allows your shared devices to skip the account setup phase of the enrollment status page. Might be of use to you: https://srdn.io/2019/05/fast-sign-in-experience-on-windows-autopilot-enrolled-shared-devices/

**Comment by Malind19** [comment]
@jseerden Thank you for your article. @bally-singh Since Windows 10, version 1803, you can opt-out of the account setup phase. When it is done, the settings will be applied for the users when they access their desktop for the first time. @mypil shall I add this to the article?

**Comment by mypil** [comment]
@Malind19 - Please proceed to create a PR for this then we will get the doc owner to review it for merging. Thanks.

**Comment by Malind19** [comment]
@mypil Created PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3515

**Comment by mypil** [comment]
@bally-singh - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
