### ISSUE TITLE
Missing PreAuthType value 16

### ISSUE THREAD

**Issue by mschrisran** [MicrosoftDocs/windows-itpro-docs#3265]
PreAuthValue 16 is missing from the table.
Type 15 is SmartCard, and Type 17 is "not expected", but Type 16 is missing, but is currently used in our production environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94cebf1d-b16d-4ddc-b532-be829b858938
* Version Independent ID: 3707f457-98d5-e5b3-c749-99afe0d6d495
* Content: [4768(S, F) A Kerberos authentication ticket (TGT) was requested. (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4768#feedback)
* Content Source: [windows/security/threat-protection/auditing/event-4768.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/event-4768.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@mschrisran - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @mschrisran ,
Kerberos PreAuthType value 16 is [PA-PK-AS-REQ](https://tools.ietf.org/html/rfc4556#section-3.2.1), but it is presented in event 4768, so this information is out of the article's scope.
Or i missing something and you have seen "Pre-Authentication type: 16" in event 4768 in your environment?

Thank you

**Comment by mypil** [comment]
@mschrisran - We would like to follow up. Can you please respond to the question of MaratMussabekov?

Thank you.

**Comment by mypil** [comment]
@mschrisran - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by jokezone** [comment]
I stumbled on this issue when researching PreAuthType 16 showing up in our 4768 Kerberos events. It appears to be more common than PreAuthType 15 and both types only occur in conjunction with smart card logon. I definitely think PreAuthType 16 should be added to this table.

**Comment by illfated** [comment]
@jokezone : Do you happen to know more about PreAuthType 16, so you could reply to the question above, from MaratMussabekov ? This issue might be stuck until someone adds useful information to add to the article.

**Comment by jannispinter** [comment]
We see PreAuthType 16 for **Windows Hello for Business** based logins (which uses certificate based logins internally) and PreAuthType 15 for smartcard based logins. The difference is clearly visible based on the CertIssuerName field.
