### ISSUE TITLE
Endpoints listed dont match other doc

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/windows-itpro-docs#3271]
At https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-data-sharing list is different. Will love to see consistency across docs. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4273a259-c3c7-dca7-6353-954068d740a7
* Version Independent ID: 1084ea77-95c4-4e4a-da6c-f4d8668f9ebf
* Content: [Enrolling devices in Windows Analytics (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started#feedback)
* Content Source: [windows/deployment/update/windows-analytics-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-get-started.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Keep in mind that Windows Analytics altogether includes three different solutions, not just Upgrade Readiness. So the endpoint list in "Enrolling devices" is comprehensive for all Windows Analytics solutions and various corner cases. However, the list in this topic might very well be out of date nevertheless, so we'll either update it or just eliminate it altogether and refer to the master list in "Enrolling devices." I'll check w/ the PM on what they want to do. Thanks!

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jaimeo - Do you have any updates on this? Thank you.

**Comment by jaimeo** [comment]
We are working on it.

**Comment by jaimeo** [comment]
I've just pushed a PR that takes the old endpoint list out of the Upgrade Readiness topic. We're double-checking the master endpoint list in "Enrolling devices" to make sure it's current as well.

**Comment by mypil** [comment]
@juanand - From our understanding, the issue you raised has been answered by jaimeo. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by juanand** [comment]
Awesome, thanks!
