### ISSUE TITLE
What is Cloud Experience Host?

### ISSUE THREAD

**Issue by robmacf** [MicrosoftDocs/windows-itpro-docs#3276]
The flow diagrams in Device Registration, Provisioning and Authentication all reference "Cloud Experience Host" but the term is not defined anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a63c1d-79e8-8e28-88b8-38b9984cdeda
* Version Independent ID: b88c3dc4-c4aa-4b98-e4b9-ab182975b4c0
* Content: [How Windows Hello for Business works - Technology and Terms](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-technology#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-how-it-works-technology.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-how-it-works-technology.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by illfated** [comment]
Oh, I see. You are referencing the sub-pages
- https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-device-registration
- https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-provisioning
- (https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-authentication)
***
I guess you would like to see a doc page containing images like https://www.anoopcnair.com/connect-cloud-option-windows-10/
***
I will wait for feedback from the Microsoft Docs team to hear if these details may be some kind of work in progress.

**Comment by robmacf** [comment]
Thanks for the followup. Not sure screenshots are needed, even just an explanation like "Cloud Experience Host Windows 10 software component that handles...<fill in correct info here>". I'm not sure what the correct info is though!

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@robmacf - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
