### ISSUE TITLE
./Vendor/MSFT/DiagnosticLog/EtwLog/Collectors/CollectorName/Providers/ProvderGUID/Keywords

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#3277]
Your example and name of the URI, 

./Vendor/MSFT/DiagnosticLog/EtwLog/Collectors/CollectorName/Providers/ProvderGUID/Keywords

I am curious because it appears "Provider", is mis-spelled at /ProvderGuid/?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a84b842f-150d-f006-0563-db5a0f01a64f
* Version Independent ID: 7dd55cbe-abc2-9c33-3fef-843b87f26312
* Content: [DiagnosticLog CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/diagnosticlog-csp#feedback)
* Content Source: [windows/client-management/mdm/diagnosticlog-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/diagnosticlog-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by illfated** [comment]
Looks like an obvious typo to me, especially if I compare with contents in the page
https://docs.microsoft.com/en-us/windows/client-management/mdm/diagnosticlog-ddf

Both [DiagnosticLog CSP version 1.2](https://docs.microsoft.com/en-us/windows/client-management/mdm/diagnosticlog-ddf#a-href-idversion-1-2adiagnosticlog-csp-version-12) and [DiagnosticLog CSP version 1.3](https://docs.microsoft.com/en-us/windows/client-management/mdm/diagnosticlog-ddf#a-href-idversion-1-3adiagnosticlog-csp-version-13)
lists `<DFTitle>ProviderGuid</DFTitle>` as valid code.

Looking back at the page in question, I think it is cosmetic and simply a placeholder name,
but should be corrected for clarification to avoid confusion for any future readers.
