### ISSUE TITLE
What happens to enabled Enterprise features like Credential Guard on Downgrade?

### ISSUE THREAD

**Issue by PiKappZ746** [MicrosoftDocs/windows-itpro-docs#3279]
In the documentation above it states: 
"The Windows 10 Enterprise device reverts seamlessly to Windows 10 Pro edition, after a grace period of up to 90 days"

If we have policies that turn on Enterprise features like Credential Guard, what happens when the PC downgrades to Pro?  Will the credentials continue to be stored in Credential Guard, or will something happen the will force the representation of the credentials to be stored outside of the TPM?  This is our primary concern with enabling some of the Enterprise features since only some of our environment is covered by W10 Enterprise subscriptions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-subscription-activation#feedback)
* Content Source: [windows/deployment/windows-10-enterprise-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-enterprise-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@PiKappZ746 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@PiKappZ746 Credential guard does not store any credentials itself, it uses VBS (Virtualization based security) to protect and isolate the LSASS secrets (password hashes and Kerberos TGTs) into a separate container. 

So by reverting back to Windows 10 Pro and turning off Credential Guard, you will no longer be protected, and the LSASS secrets can be dumped again very easy.

I recommend this article for deeper insights into this matter: https://www.blackhat.com/docs/us-15/materials/us-15-Moore-Defeating%20Pass-the-Hash-Separation-Of-Powers-wp.pdf

**Comment by mypil** [comment]
@PiKappZ746 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
