### ISSUE TITLE
Typo correction

### ISSUE THREAD

**Issue by tolarianNZ** [MicrosoftDocs/windows-itpro-docs#3283]
WDAP should read WPAD (Windows Proxy Autodetection Protocol) in the final bullet point:

- If using Proxy, WDAP Proxy settings option must be enabled and configured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12823601-7426-a768-e72f-866b150baccd
* Version Independent ID: c1f993e3-a405-6860-8ab1-7b3d387b4631
* Content: [Hybrid AAD Join](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/user-driven-hybrid)
* Content Source: [windows/deployment/windows-autopilot/user-driven-hybrid.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/user-driven-hybrid.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by illfated** [comment]
Good point. At first, I thought WDAP meant something related to Windows Defender, but that one is apparently WDATP (Windows Defender Advanced Threat Protection). Unless someone else picks this up during the day, I will post a PR to get it sorted.
