### ISSUE TITLE
Please clarify this information?

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#3289]
It talks about SCOPE of the URIs:

"./Device/Vendor/MSFT and ./User/Vendor/MSFT
Required. The root node for the NodeCache object. Supported operation is Get. This configuration service provider is used for enterprise device management only. This is a predefined MIME type to identify this managed object in OMA DM syntax. Starting in Windows 10, version 1607 the value is com.microsoft/&lt;version&gt;/MDM/NodeCache."

What specifically do you mean by this last sentence, is it misplaced entirely?

Starting in Windows 10, version 1607 the value is com.microsoft/&lt;version&gt;/MDM/NodeCache.

This needs to be clarified. The data does not appear to match the listing in the article. Value? Value of what?!  The preface of the paragraph is talking about SCOPE of the URI,and then talks about value, but seems to intimate a path update??

Lost. 

Help!? thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8acbb6a2-add6-98e1-7670-472b114f7e42
* Version Independent ID: 787a0834-ec2b-2dfb-3b41-d31830a8c49d
* Content: [NodeCache CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/nodecache-csp)
* Content Source: [windows/client-management/mdm/nodecache-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/nodecache-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Tdiwestyguy - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Tdiwestyguy - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
