### ISSUE TITLE
What about specific steps and requirements for WDAC ONLY scenario

### ISSUE THREAD

**Issue by marcosmcampos** [MicrosoftDocs/windows-itpro-docs#3293]
Hey team,

If we get here in a "WDAC only" scenario, this page and links don't really help much. At this point and if we follow the previous articles in the deployment guide for WDAC, you could already have a validated (audited) policy and you're now playing with this option to enable managed installed in the WDAC policy. However it's not obvious what steps you need to take, since we only mention in the article that a section of Applocker need to be added to enable this feature. Question: where do you apply that? into what XML? If you got here by starting with WDAC, you have no Applocker policy at this point. The link for "https://cloudblogs.microsoft.com/enterprisemobility/2016/06/20/configmgr-as-a-managed-installer-with-win10/" doesn't to anything since it doesn't explain how to create the Applocker policy you need to effectively enable the managed installed in WDAC. 

Question 2: assuming we need to create an applocker policy to enable managed installed in WDAC, is it implied that the applocker policy can be just audit mode? As in, WDAC takes the primary role of whilelist/blacklist and Applocker is only here to enable the managed installed capability?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07fdf27b-1ead-1b6e-c793-a2ad259a4f6a
* Version Independent ID: 8da1f371-73d4-c79f-a97b-80170e7860af
* Content: [Deploy Managed Installer for Windows Defender Device Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-managed-installer)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-managed-installer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-managed-installer.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mdsakibMSFT
* Microsoft Alias: **justinha**

**Comment by marcosmcampos** [comment]
Rephrasing as I might have sounded a bit harsh: the entire deployment guide is done in a way that it's somewhat easy to get to the end stage of having WDAC policy enforced, however when we get to the managed installer part, you're introduced to the Applocker policy which up to this point you didn't work with (again, if you're starting with a WDAC only scenario and didn't start playing with application whitelisting with AppLocker before).

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by Reeced40** [comment]
@marcosmcampos Thank you, I will have the team look into this.

**Comment by mypil** [comment]
@marcosmcampos - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by Reeced40** [comment]
@marcosmcampos https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-control/applocker/deploy-applocker-policies-by-using-the-enforce-rules-setting Please let me know if this answers your question.

**Comment by mypil** [comment]
@marcosmcampos - From our understanding, the issue you raised has been answered by Reeced40. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
