### ISSUE TITLE
MFA Licensing Clarification

### ISSUE THREAD

**Issue by arourke** [MicrosoftDocs/windows-itpro-docs#3296]
To clarify, if we are deploying a Hybrid Azure AD Joined Key Trust Deployment in a non-federated environment, we do not need Azure AD Premium licenses for our users, so long as we perform MFA directly against Azure, correct? Does the MFA included in our Office 365 Azure AD license suffice in this case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c47de28c-e44b-ca73-efde-fae303e0d3f8
* Version Independent ID: 71202a24-5b2f-844a-acce-d48c46873f2b
* Content: [Hybrid Key trust Windows Hello for Business Prerequisites (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by Malind19** [comment]
Hy @mypil , According to the following article, what the reporter says is true. I will adjust the article accordingly. 
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install

**Comment by Malind19** [comment]
@mypil Created PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3348

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@arourke - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
