### ISSUE TITLE
Interactive logon: Do not require CTRL+ALT+DEL

### ISSUE THREAD

**Issue by ronnieharper** [MicrosoftDocs/windows-itpro-docs#3299]
The text in Intune reads: Require CTRL + ALT + DEL to log on.  So confusing!

I'm going to set it to enable to test it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 773b74b2-7dc2-d0e5-1e3b-bd6445bceda4
* Version Independent ID: 34b55057-9078-6bd0-a9ac-2f6403b84be7
* Content: [Policy CSP - LocalPoliciesSecurityOptions](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by illfated** [comment]
(For easier reading - direct links to the section in question)
- https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions#localpoliciessecurityoptions-interactivelogon-donotrequirectrlaltdel
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md#localpoliciessecurityoptions-interactivelogon-donotrequirectrlaltdel

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
@ronnieharper : Have you managed to test what the actual result is when you are using Intune where that text appears?

**Comment by RAJU2529** [comment]
@ronnieharper. I have tested on two machines on windows 10 pro and windows 10 ent .
I enabled that particular setting,  whenever i make changes to programs. setting asked me to enter ctrl+alt+del and asked me to enter the password.
If i disabled that setting, programs does not ask  anything.
 I would recommend if you are the only user on windows 10 machine, then don't enable. Otherwise  enable it

**Comment by illfated** [comment]
@ronnieharper & @RAJU2529 & @e0i -- as you might have seen, there is a new comment from @ManikaDhiman in the pull request reasoning why there will be no need for any additional note in the CTRL+ALT+DELETE policy docs page.

From https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4349#discussion_r302153798:
> No, it’s not just for single-user systems. We explained why we dropped it from our baselines a while ago:
> https://blogs.technet.microsoft.com/secguide/2015/11/18/changes-from-the-windows-8-1-baseline-to-the-windows-10-th11507-baseline/
>
> Excerpt from the blog:
> Removed settings
> This section summarizes some of the 122 settings that went from a configured value to “Not Configured.” For many of these settings, such as Windows Update settings, specific configuration is best left to the organization. For others, organizations can continue enforcing settings, but we do not consider their enforcement to be necessary.
> •	[…]
> •	Enforcement of Ctrl+Alt+Del at logon to protect credentials from theft. This is not particularly strong protection. First, it depends on a user that’s looking at a spoofed logon screen remembering that he or she hadn’t pressed Ctrl+Alt+Del before typing a password. Second, so many apps prompt the user for the same credentials on the user’s desktop that the credentials can easily be stolen there. Third, if the adversary has gained administrative control of the computer, the “secure desktop” is no longer a protected space. Finally, with devices offering more keyboard-free logon experiences such as facial recognition, Ctrl+Alt+Del becomes an annoying interference.
> 
> So, there is no need to add any note in the docs for this policy. Hope this resolves the issue. Thanks!

**Comment by e0i** [comment]
@ronnieharper As quoted by *illfated*, It has been suggested by the product team that no further changes necessary for the article in question.

Link to original comment from the product team: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4349#discussion_r302153798

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
