### ISSUE TITLE
Would be nice to document what is the Security Compliance Toolkit and how to use it with example scenarios

### ISSUE THREAD

**Issue by csharmath** [MicrosoftDocs/windows-itpro-docs#330]
I was looking at the various blog posts, docs links and can't find a single high level overview of how to use these security baselines or the security compliance toolkit. 
There is this doc
https://docs.microsoft.com/en-us/windows/device-security/security-compliance-toolkit-10#what-is-the-security-compliance-toolkit-sct

But it simply fails to explain what is the toolkit really for and how to use it.
I would love to read more about this so I better understand it.

So I would appreciate if there were few scenarios, like suppose you have a new domain setup in your lab, this is how you apply the microsoft security baseline.
Or with an existing domain, this is how you analyze / compare your settings against the microsoft baseline.

Thanks for checking!

**Comment by Justinha** [comment]
@csharmath thanks for this feedback. Sorry for my delayed reply here. What you suggest makes perfect sense. There is some related info in the parent topic at 
https://docs.microsoft.com/en-us/windows/device-security/windows-security-baselines 
 and that topic has a link to a related Ch 9 video at https://channel9.msdn.com/Shows/Defrag-Tools/Defrag-Tools-174-Security-Baseline-Policy-Analyzer-and-LGPO 

I just want to be sure you saw those resources too. Do you suggest we also add an example of a fictitious company applying the security baseline, or something similar?

**Comment by csharmath** [comment]
Thanks for pointing out the channel9 video, it's definitely related and useful although the link text of Defrag Tools is a bit misleading for the naive reader, hence I didn't even click...
Also the video touches on some of the history and some intro, but it would be still better to have some docs with walk throughs.

So yes, I still feel that it would benefit the community if there is a reference howto for applying best practices to contoso's existing or new domain or just compare baseline against existing domains.
So one for a green field ( simpler use case ) and another one for existing.

As a kind of related note: I would love to see some thoughts on how one should version control and automate these settings on a Server Core only environment as I really don't like the click based management / lack of scriptability, and it seems that most guides are gui based.

Thanks

**Comment by Justinha** [comment]
I shared this issue with the engineering team that publishes the security baselines. They really appreciated the feedback and will look to add examples for the next Windows 10 release. They mentioned for GP version control, there are third-party GP add-ons.

Thanks,
Justin

**Comment by tjcdw** [comment]
Windows 10’s Spring Creators update is coming soon. Will there be any examples available?

Kind regards,
Thomas
