### ISSUE TITLE
Explain it with The turn windows features on/off method

### ISSUE THREAD

**Issue by kevincrans** [MicrosoftDocs/windows-itpro-docs#3300]
This article explains it on every way, except the normal one, Turn windows features on or off.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
HI @kevincrans . Thanks for reaching out.
The intent here is to describe usage for admin scenarios. Do you find the device-specific instructions valuable as well? What's your scenario?

**Comment by kevincrans** [comment]
Dear DaniHalfin,

My scenario is .net framework being broken by turning on/off Windows Features.
An example of what Turn Windows Features On/Off looks like for me is [this](https://1drv.ms/u/s!Avqi6Pt1BGP3gbp9pMe2l8IlVfSJnw); .

Wen I try to run PaintDotNet and Discord, I get error (0xc0000135), When I start Trouble Shooter of Windows Network Diagnostics, which is working fine, I get error 0x8007007E and when I run the Windows Features installer for .Net Framework 3.5, I get error 0x800F080C.

I also get the first error with an amount of applications, which run on startup.

The problem is, I don't know how to revert, the Checkbox of Net Framework is gone, if that was the problem.

I hope you'll be able to help me out and thank you for your response!

Sincerely,

Kevin Crans

**Comment by illfated** [comment]
@kevincrans : I tried to find Windows Defender Credential Guard in Control Panel ->  Turn Windows Features On/Off in Windows 10 Pro on the computer at my workplace, but it does not appear to be available as a package in that list. It may be that the package can only be installed as described in the documentation page.

I am also guessing that it might only be available in an Enterprise environment, not in a stand-alone Windows 10 Pro setup as such (I could be mistaken, though).

**Comment by DaniHalfin** [comment]
@kevincrans - when you reference turning Windows features on and off, are you talking specifically about Credential Guard, or generally about the ability to do that?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@kevincrans - We would like to follow up. Can you please respond to the query of DaniHalfin?

Thank you.

**Comment by mypil** [comment]
@kevincrans - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
