### ISSUE TITLE
WDAG was not available in Windows 10 Education (1809 or ealier)

### ISSUE THREAD

**Issue by yamauchikazu** [MicrosoftDocs/windows-itpro-docs#3302]
WDAG was not available in Windows 10 Education and Pro Education version 1809 or earlier. 
Even if I try to enable this feature from the control panel, it says "Windows Defender Application Guard は Windows 10 Enterprise Edition でのみサポートされています。"（ja-jp) and can not be enabled.
Is this feature planned to be supported in Education and Pro Education from version 1903?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f43df7b-6ead-de5a-2e41-4d49978ab485
* Version Independent ID: 5497d300-cb21-55f3-7e80-98bc3592635c
* Content: [System requirements for Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by yamauchikazu** [comment]
I have confirmed that I can enable WDAG in Windows 10 Education 1903 (18362.30) .

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
The issue seems to be resolved.

@yamauchikazu  feel free to re-open the issue if you feel it hasn't been resolved. Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by yamauchikazu** [comment]
The issues in this document have not been resolved. Attempting to enable this feature in Education version 1809 is still blocked.

**Comment by e0i** [comment]
@officedocsbot reopen

**Comment by yamauchikazu** [comment]
In version 1809, WDAG is available in Pro Education but not in Education.
In version 1803, WDAG is available in Pro Education but not in Education.
I think that WDAG is available Pro Education 1803 or higher, and will be available Education 1903 or higher.

**Comment by yamauchikazu** [comment]
I coud enable WDAG by DISM /Online /Enable-Feature or Enable-WindowsOptionalFeature in Education ver 1809 or ealier, but after reboot WDAG not work with error event ID 200 and 205 in Microsoft-Windows-WDAG-Service/Operational log. Event ID 200 means "Hvsi feature is not enabled on this sku".

**Comment by illfated** [comment]
@Justinha : May we have some feedback with regards to the referenced page [System requirements for Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard) and its list of supported operating system versions in the section [**Software requirements**](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard#software-requirements), whether it needs updating and if so, what will a recommended change look like?

**Comment by yamauchikazu** [comment]
OS requirements should be as follows.

---
Windows 10 Enterprise edition, version 1709 or higher
Windows 10 Pro edition, version 1803 or higher
Windows 10 Pro for Workstations edition, version 1803 or higher
Windows 10 Pro Education edition, version 1803 or higher
Windows 10 Education edition, version 1903 or higher
---
or
---
Windows 10 Enterprise edition, version 1709 or higher
Windows 10 Pro, Pro for Workstations, or Pro Education editions, version 1803 or higher
Windows 10 Education edition, version 1903 or higher
---

Install WDAG, Test scenarios, and FAQ pages are also need to fix.

**Comment by illfated** [comment]
> Install WDAG, Test scenarios, and FAQ pages are also need to fix.

Feel free to post suggestions for the required changes directly on the related page(s). If you know how to create a Pull Request, you could do that as well. Otherwise, you could just ask existing Github PR contributors to PR a suggested change.

**Comment by e0i** [comment]
@yamauchikazu 

Thank you for following up and providing a draft for suggested changes.

We are passing this issue to editing team and will keep you posted on changes.

Kind regards

**Comment by lindspea** [comment]
@yamauchikazu Thank you for helping improve MS Docs.  I'll work on having the changes implemented soonest with a PR.

**Comment by e0i** [comment]
@yamauchikazu 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
