### ISSUE TITLE
Domain misspelling

### ISSUE THREAD

**Issue by beerisgood** [MicrosoftDocs/windows-itpro-docs#3304]
**fe3..mp.microsoft.com** 	TLSv1.2/HTTPS 	Enables connections to Windows Update, Microsoft Update, and the online services of Microsoft Store.
-> Is that double dot right?

**mscrl.micorosoft.com** 		Certificate Revocation List related traffic.
-> micorosoft is wrong isn't it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a536a609-8ee6-5ac4-9fd1-d8d459fedfd9
* Version Independent ID: ac6433b8-548c-4876-088f-088eea5c48e1
* Content: [Windows 10, version 1809, connection endpoints for non-Enterprise editions](https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1809-non-enterprise-editions)
* Content Source: [windows/privacy/windows-endpoints-1809-non-enterprise-editions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/windows-endpoints-1809-non-enterprise-editions.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by illfated** [comment]
Thank you for pointing out the typos in that article. I will open a pull request to make the necessary corrections ASAP.

**Comment by illfated** [comment]
Feel free to comment or add feedback in the PR #3305 , or just have a look at the resulting Github file view:
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/a86ebba32d16a352c9a7cbc62e4febfa6ff35818/windows/privacy/windows-endpoints-1809-non-enterprise-editions.md

You are more than welcome to tell me if there is something I have missed or overdone by adding backslash as escape code for the asterisks.

**Comment by illfated** [comment]
Sorry for the commit update noise, I am not familiar enough with verifying where asterisks need to be escaped and where they can be left alone in MarkDown tables, on a daily or weekly basis.

**Comment by illfated** [comment]
New & updated preview of the Github version of the page (revision hash changed from a86ebba to 33cb1fc):
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/33cb1fc48603821b47e28278503420c57e3ea3df/windows/privacy/windows-endpoints-1809-non-enterprise-editions.md

**Comment by beerisgood** [comment]
Looks good!

**Comment by illfated** [comment]
Thanks. I was slightly worried for a moment, seeing that the bing.com and www.bing.com URLs had changes when they did not need any.

**Comment by illfated** [comment]
@beerisgood : As you can see, the PR [**Windows/Privacy: change formatting code to text**](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3305) #3305 has been accepted, hopefully solving the issues you pointed out in your original comment. The changed page may take a few days to migrate to the docs.microsoft.com site, but we can consider your request for improvements accepted and dealt with as far as I can see, but feel free to open a new issue ticket if there are other issues to solve in a similar manner. 👍

**Comment by beerisgood** [comment]
I can confirm that the website issues are fixed.
Thanks guys

**Comment by illfated** [comment]
Thank you for replying back. I just revisited the page and found 1 line I missed in
https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1809-non-enterprise-editions#windows-10-pro
> *.tlu.dl.delivery.mp.microsoft.com/*

Looks like I need to make a small PR to solve that one as well, there must be an unescaped asterisk before & after that line. 
The tell-tale indication is that this URL is in cursive text, whereas the rest of the URLs are not.
