### ISSUE TITLE
Great article with technical programming knowledge 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#3307]
Today only I came  to know  the  how are windows update works in background . To  understand  this  article  I need  programming language  . But  with  the  graphical  screenshots  . Somehow  I got  the points .
Authors  are having plenty of  knowledge. This knowledge  is equivalent  to Mathematics  (all branches ).

It will be more usefull , if  authors will add more   graphical  screenshots  in all the  coming articles.

Thanks and Wish you all the best.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a8126d-2552-97a3-6bb4-c24fd32ffc1f
* Version Independent ID: 82afb372-5fee-e0c9-56b0-3e8276401e23
* Content: [How Windows Update works](https://docs.microsoft.com/en-us/windows/deployment/update/how-windows-update-works#feedback)
* Content Source: [windows/deployment/update/how-windows-update-works.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/how-windows-update-works.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@RAJU2529 - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by RAJU2529** [comment]
Submitted feedback through hub
