### ISSUE TITLE
Thanks for Registry key

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#3310]
I have  configured my windows laptop through GPO , and the new  registry shortcuts came to know .
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU] 
"UseWUServer"=dword:00000001       

Thanks to all authors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349d337e-ca0f-a40a-a522-bd1ae71c7d1e
* Version Independent ID: 50f0c3b0-eaad-89c0-eb3c-878e7564d6f6
* Content: [Windows Update troubleshooting](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-troubleshooting)
* Content Source: [windows/deployment/update/windows-update-troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-troubleshooting.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@RAJU2529 - Thank you for submitting feedback.

We are happy to know that this MS article was able to help you with your issue. 

Is there something within this article that you suggest to be added or edited? OR Is this feedback intended to commend the MS article authors? Please advise.

Thank you.

**Comment by illfated** [comment]
My interpretation tells me that only commending the authors was intended here.

**Comment by RAJU2529** [comment]
No issues. I am very to this article

**Comment by RAJU2529** [comment]
After reading this article, I came to know  new registry key .
I don't have practical knowledge with windows server and its functions 

Thanks sir . I am happy with this article

**Comment by mypil** [comment]
@officedocsbot close
