### ISSUE TITLE
Hats off to the authors

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#3311]
Wonderful website from Microsoft , to modify exact  required  settings  by group policy editor.
Highlights of this  article  is  mentioned  
01.the steps of  avoiding high usage of windows  server 
02.Steps by using GPO 
03. Links are  mentioned and those links  are trusted  from Microsoft 

https://gpsearch.azurewebsites.net/#13329

Really thanks to all the Authors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349d337e-ca0f-a40a-a522-bd1ae71c7d1e
* Version Independent ID: 50f0c3b0-eaad-89c0-eb3c-878e7564d6f6
* Content: [Windows Update troubleshooting](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-troubleshooting)
* Content Source: [windows/deployment/update/windows-update-troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-troubleshooting.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@RAJU2529 - Thank you for this positive feedback. We are glad to hear that you are pleased with the MS authors. 

Is there something within this article that you suggest to be added or edited? OR Is this feedback intended to commend the MS article authors? Please advise.

Thank you.

**Comment by RAJU2529** [comment]
I can't able to comment on authors, because they are very intelligent and they have practical knowledge about their topics.
I ama  teacher , teaching higher mathematics.

Within two days I inform to add certain topics in this MS articles.

**Comment by mypil** [comment]
@RAJU2529 - Thank you for your valuable feedback and commendation. I'm sure the authors are appreciative of with this as well. I will proceed to close this issue then.

**Comment by mypil** [comment]
@officedocsbot close
