### ISSUE TITLE
Windows 10 Group Policy admin templates and WUDO not working for updates from more than one place

### ISSUE THREAD

**Issue by biren1234** [MicrosoftDocs/windows-itpro-docs#3316]
I've followed the direction in Technet and another how-To to download the Windows 10 Administrative templates and apply them to the server so I can change the default WUDO (Windows Update Delivery Optimization) settings for our Windows 10 Clients. 

https://support.microsoft.com/en-us/kb/3088114

https://4sysops.com/archives/windows-update-delivery-optimization-wudo-in-windows-10/

When I look at the RSOP (Resultant Set Of Policies) tool in Windows on one of the clients it shows that the policy to Disable WUDO has been applied and is set to Disabled.  

When I look in the Windows update settings on the Client it looks like the setting is still enabled. 

So is WUDO Actually disabled or is it ignoring the Group Policy setting ? 

I've run gpudate /force and rebooted the PC with no changes to the results. 

![wdeo](https://user-images.githubusercontent.com/39988820/56453772-b3724280-6364-11e9-8321-b6e369177dca.PNG)

**Comment by illfated** [comment]
Do you have a Microsoft Docs page this is directly related to?

Please keep in mind that this issue tracker intends to solve 
issues in the documentation pages built from the repository 
https://github.com/MicrosoftDocs/windows-itpro-docs 
and that this issue tracker usually receives feedback from 
the https://docs.microsoft.com/windows/#pivot=it-pro pages 
where users can post feedback in the articles when there are 
issues regarding wrong or incomplete information.

It may very well be that one of the Microsoft Docs team members 
or one of the experienced users can answer your question, 
but that usually depends on correlation to the docs pages.

**Comment by illfated** [comment]
By the way, just to indicate what kind of page I am asking for, these pages are the closest match I could find to your issue description, with a minimal amount of searching:
- [**Optimize Windows 10 update delivery**](https://docs.microsoft.com/en-us/windows/deployment/update/waas-optimize-windows-10-updates)
  (https://docs.microsoft.com/en-us/windows/deployment/update/waas-optimize-windows-10-updates)
- [**Walkthrough: use Group Policy to configure Windows Update for Business**](https://docs.microsoft.com/en-us/windows/deployment/update/waas-wufb-group-policy)
  (https://docs.microsoft.com/en-us/windows/deployment/update/waas-wufb-group-policy)

(You may need to search for other pages, in case these pages don't match your scenario.)

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@biren1234 

It seems that your question has been answered by the community.

Note that the issues section of this repository is intended for documentation and content issues only.

Should you have any further issues similar to this one, please consider opening a product support ticket here:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
