### ISSUE TITLE
Missing 0x80090010

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/windows-itpro-docs#3317]
Missing 0x80090010 error code for pin creation...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by illfated** [comment]
As you can see in the [**Closed**](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation#tabpanel-issues-closed) part of the [**Feedback**](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation#feedback) section, there are already 10 similar issues closed with the almost the same explanation.

List of closed issues:
- 0x801c0541 Not listed #3123 opened 3 weeks ago by WagoL
- LOCKSCREEN PIN ERROR #3092 opened 3 weeks ago by crystalh3
- 0x801c0451 not listed #2941 opened a month ago by jonnydcakes
- 0x801c004d Not Listed #2900 opened a month ago by GenericUser321
- Unlisted: 0x80070490 #2804 opened 2 months ago by SnakeMind
- Unlisted error code: 0x80070520 #2685 opened 2 months ago by wireznak
- 0x801c044f not listed #2684 opened 2 months ago by spankin
- 0xc0290904 not listed #2676 opened 2 months ago by juanheraclio
- 0xc0290101 not listed #2421 opened on Jan 5, 2019 by ikonane
- 0x80070490 not listed #2409 opened on Jan 2, 2019 by demialucard

A couple of reply alternatives for this type of issue (like yours):
***
DaniHalfin wrote:
> For error codes unlisted here, in most cases those are transient error codes being surfaced by other services in the Windows Hello dependency chain.
> We are working on something to improve the user experience in that regard, but that will not solve the issues you are experiencing.
> If we find a reoccurring error codes that isn't covered here and should be (meaning, in most cases, it is coming from Windows Hello and not other components) we'll make sure to add it to this page.
> For any issue you're seeing, please either file a problem through [Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub), or reach out through our various support channels. Both avenues allow us to properly investigate the issue in ways we could never do through a comments section on a GitHub issue.
> The feedback section in the topic is generally meant for feedback on the content, and we can't really use it for in-depth troubleshooting.
> We thank you for taking the time to reach out, but we also want you to have the best time to resolution of the issue, and going through this feedback channel won't get us there.
***
Joyce Y. wrote:
> Thank you for submitting feedback.
> I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.
> Please follow this link to contact support for Windows 10 products: https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10
> If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
***
From my own point of view, I recommend checking out the other 10 issue tickets to see if any of the other users have posted helpful comments, like "broken file, replaced, fixed" or "timeout problem" or "user interrupted".

**Comment by hkusulja** [comment]
Ok, thank you for the answer, however still think that Microsoft should provide documentation, in mean of list of all possible codes (that are in programmed into software) and provide at least some explanation for the start. That way, you will lower the number for support ticket requests, and educate Microsoft 1st level support and other IT Pro and be more open. Putting info on feedback hub is just community with no reply very often or long wait for more information on specific issue.

**Comment by illfated** [comment]
Fair point. I can only hope for progress in documentation production for this section
and reference one of the important parts of Dani Halfin's post:
> We are working on something to improve the user experience in that regard, but that will not solve the issues you are experiencing.
If we find a reoccurring error codes that isn't covered here and should be (meaning, in most cases, it is coming from Windows Hello and not other components) we'll make sure to add it to this page.
