### ISSUE TITLE
Baselines for download and import

### ISSUE THREAD

**Issue by ARF1** [MicrosoftDocs/windows-itpro-docs#3321]
For building Privileged Access Workstations Microsoft provides the security baselines for download. This makes the securing machines with levels 1-2 much easier.

Are similar "baselines", e.g. level-5-baseline, level-4-baseline, etc also available for download? Or are administrators supposed to copy each policy setting, etc. from the webpage by hand? - What workflow is envisaged?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3fa1093-f014-b19a-0a3f-621bb239b23d
* Version Independent ID: eaf6cb9a-9d2a-5ea0-71ba-0801e073d49e
* Content: [Windows security configuration framework](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-security-configuration-framework/windows-security-configuration-framework#feedback)
* Content Source: [windows/security/threat-protection/windows-security-configuration-framework/windows-security-configuration-framework.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-security-configuration-framework/windows-security-configuration-framework.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @appcompatguy
* Microsoft Alias: **appcompatguy**

**Comment by illfated** [comment]
Although I don't have a definitive or blueprint answer, I would like to offer my view of it.
"Security baseline" can be interpreted exactly as it says, a complete and standard baseline to start off with.

Reading the articles gives me the impression that higher level security measures 
need to be applied manually to avoid errors and unintended blocking of features.

`#include <std_disclaimer.h>`
This is my personal view and does not necessarily reflect anyone else's opinion (neither my employer nor Microsoft).

**Comment by appcompatguy** [comment]
With the initial release, we hope to get broader validation of the experiences we had in our private preview, developing the guidance in an open-source way. We want to ensure that we're meeting the many needs of our customers who are looking for this guidance. As it continues to evolve, we will build more tooling and automation around it to simplify implementation.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ARF1 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by appcompatguy. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
