### ISSUE TITLE
How about Windows 10 Pro for Workstations

### ISSUE THREAD

**Issue by yamauchikazu** [MicrosoftDocs/windows-itpro-docs#3324]
I can enable and use WDAG in Windows 10 Pro for Workstations ver 1809. WDAG is probably available for 1803 and higher.

**Comment by illfated** [comment]
That should already be covered in https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard#software-requirements
(https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard.md#software-requirements)

## Software requirements
Your environment needs the following software to run Windows Defender Application Guard.

Software | Description
-- | --
 | Operating system | Windows 10 Enterprise edition, version 1709 or higher | 
 |  | Windows 10 Professional edition, version 1803 or higher | 
 |  | Windows 10 Education edition, version 1709 or higher | 
 |  | Windows 10 Pro Education edition, version 1803 or higher |

**Comment by yamauchikazu** [comment]
Did you mean "Windows 10 Professional edition, version 1803 or higher" include "Pro for Workstations"?
Pro (48) and Pro for Workstations (161) are different OperatingSystemSKU. I think it should be divided separately.

This document has another big mistake. 

In fact, WDAG is not available in the Education edition version 1709 to 1809. Add or remove Windows Feature wizard does not allow enable WDAG feature. You can enable by using DISM or Enable-WindowsOptionalFeature WDAG, but WDAG service does not allow WDAG container (Event ID 200: feature is not enabled on this sku). 

WDAG will be available 1st in Education from version 1903.

**Comment by illfated** [comment]
OK, fair enough, I am no expert in this field. I just assumed, but apparently I am wrong.
Then again, does not this feedback belong in issue ticket #3302 , since it is about the same page?

Anyway, it is important enough to document which Microsoft Docs page this is about and what the requested change looks like.
