### ISSUE TITLE
Update "Copy To" Window Explanation

### ISSUE THREAD

**Issue by reschrei** [MicrosoftDocs/windows-itpro-docs#3326]
Can we get an explanation of the "Mandatory Profile" Checkbox that shows up in this window on build 1803 and up? Step 6 doesn't show this Checkbox (or step 9 viewing the article in Github, must be a markdown bug).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9ca7cb6-32cb-1517-a9de-c36046955d45
* Version Independent ID: 91041e39-007e-f481-0cd4-177b4039ae12
* Content: [Create mandatory user profiles (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/mandatory-user-profile#feedback)
* Content Source: [windows/client-management/mandatory-user-profile.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mandatory-user-profile.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@reschrei - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @reschrei , Thank you for posting the query. Mandatory Profiles are kind of Roaming profiles. The main purpose of Mandatory Profiles is to discard any changes/modifications happened in the profile during a user-login session. Those change will be deleted. These are ideal for educational institutes and Kiosks.

Thanks.

**Comment by reschrei** [comment]
@joinimran ,

Thanks for your reply, but I understand the concept of a Mandatory Profile. My question is geared specifically to a checkbox in the "Copy to" Window. There is now a checkbox that says "Mandatory Profile". So far my personal experience with this checkbox has been nothing but trouble. When checking that box, I am unable load the profile, logins fail every time. I am able to make a usable mandatory profile when that box is unchecked.

I'm simply requesting some explanation of what this checkbox does.
![image](https://user-images.githubusercontent.com/9450819/57303185-cac26700-70aa-11e9-94ca-eab001da25d1.png)

Thanks!

**Comment by joinimran** [comment]
@reschrei The purpose of this check box is to make the profile a Mandatory profile. If this is not working as expected, you can contact the product support team so that this can be escalated to the corresponding team.

@mypil Please guide the user to the product support team to open up a case for this.

Thanks.

**Comment by mypil** [comment]
@reschrei - I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
