### ISSUE TITLE
must and Optionally

### ISSUE THREAD

**Issue by gitmarecki** [MicrosoftDocs/windows-itpro-docs#3328]
First paragraph says that "On-premises deployments must use the On-premises Azure MFA Server using the AD FS adapter model Optionally, you can use a third-party MFA server that provides an AD FS Multifactor authentication adapter. " - it is confusing - is it a must or not? If there is an optional setting, then first sentence should not say that deployment must use On-Premises Azure MFA server. I believe the proper statement should be that the deployment must use ADFS, while there are multiple choices as to how to solve MFA design dilemma - whether to use Azure MFA server or 3rd party. Also there i no further documentation on 3rd party MFA connector here, which could be added to complete the picture (since it is supported and optional). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08552f2d-5920-7a9b-a96b-6d3518b1a11a
* Version Independent ID: e6e8ac42-46ea-475c-016c-2b0931a72862
* Content: [Configure or Deploy Multifactor Authentication Services (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-deploy-mfa#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-deploy-mfa.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-cert-trust-deploy-mfa.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by illfated** [comment]
Good point. To me, it does look like someone left the text unfinished and skipped review or proofreading by someone else. There needs to be a better separation between the sentences, maybe even a paragraph spacing between, to achieve a better readability.

> On-premises deployments must use the On-premises Azure MFA Server using the AD FS adapter model
>
> Optionally, you can use a third-party MFA server that provides an AD FS Multifactor authentication adapter.

Even so, like you wrote above, the current wording seems to be inconsistent or slightly contradictory.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@gitmarecki - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by illfated** [comment]
@gitmarecki : I have re-read the lines and to me, it now looks like the intention of the first sentence is 
that you cannot perform an On-premises deployment _**without**_ an MFA Server 
(Microsoft offers Azure MFA Server as their preferred alternative).

Following this, the second sentence suggests the alternative of using
> a third-party MFA server that provides an AD FS Multifactor authentication adapter.

... as an option, in case you are able to use some alternative MFA server. 

But again, I conclude that a clarification is needed, seeing how easy it is to be confused.

**Comment by mypil** [comment]
@gitmarecki - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
