### ISSUE TITLE
Active Directory joined with Azure AD Connect - ambiguous terminology

### ISSUE THREAD

**Issue by SteveHernou** [MicrosoftDocs/windows-itpro-docs#3342]
We have been struggling getting our Win10Pro to Win10Ent. In the requirements it's stated devices must be either Azure AD joined or Active Directory joined with Azure AD Connect. 
MS support however told us our devices must be Hybrid Azure AD joined which time is not the same as Active Directory joined with Azure AD Connect. We have all our computers in Active Directory and we have Azure AD Connect but that just makes them Azure AD Registered devices. Maybe the wording should be different so it's clear the requirement is having your devices Hybrid Azure AD Joined and being Azure AD Registered is not enough.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-subscription-activation#feedback)
* Content Source: [windows/deployment/windows-10-enterprise-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-enterprise-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@SteveHernou - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@SteveHernou - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
