### ISSUE TITLE
Out of date screenshots

### ISSUE THREAD

**Issue by Scriptimus** [MicrosoftDocs/windows-itpro-docs#3345]
The portal has changed so this page is no longer current. The steps to get to this in the Azure portal need to be updated above. This page is very difficult to follow if you are new to this solution.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cba076c-90ab-62bf-dcac-0c4c528d250d
* Version Independent ID: eab2ef6b-1854-0859-199c-04fc9cc864c5
* Content: [Use Upgrade Readiness to manage Windows upgrades (Windows 10)](https://docs.microsoft.com/en-gb/windows/deployment/upgrade/use-upgrade-readiness-to-manage-windows-upgrades#feedback)
* Content Source: [windows/deployment/upgrade/use-upgrade-readiness-to-manage-windows-upgrades.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/use-upgrade-readiness-to-manage-windows-upgrades.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
Thank you for your feedback. Good point, the documentation needs to be updated when changes are made in the working environment. Your feedback will be reviewed and followed up by someone from the Microsoft Docs team members. We hope to see the documentation updated as soon as possible.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Scriptimus - - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by Reeced40** [comment]
@Scriptimus Thank you, I will look to update this as soon as I can.

**Comment by mypil** [comment]
@Scriptimus - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
