### ISSUE TITLE
Superseded Windows 7 Compatibility Update KB2952664 causes diagtrack.dll warning

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/windows-itpro-docs#3347]
KB2952664, containing diagtrack.dll v10.0.10586.3 shows as superseded in Windows Update Catalog by March'19/April'19 Monthly Quality Rollups (KB4489878, KB4493472), containing diagtrack.dll v10.0.10586.10007.

Organizations that deploy security-only updates to Windows 7 will not get updated diagtrack.dll, and Upgrade Readiness script will complain about it in the log:
"warning : CheckUTCKB The Diagnostics and Telemetry tracking service (diagtrack.dll version 10.0.10586.3) is old. 10.0.10586.10007 enables faster processing of insights and reduces overall latency for devices enrolled in Analytics. Learn more at https://go.microsoft.com/fwlink/?linkid=2011593&clcid=0x409"

FWLink in log file is dead, and this article does not notice the warning above, and if it can be safely ignored. Windows 7 devices also show up in "outdated KB" bucket in the Upgrade Readiness portal.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4273a259-c3c7-dca7-6353-954068d740a7
* Version Independent ID: 1084ea77-95c4-4e4a-da6c-f4d8668f9ebf
* Content: [Enrolling devices in Windows Analytics (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started)
* Content Source: [windows/deployment/update/windows-analytics-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-get-started.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Thanks for letting us know! I'll get with @zdvorak and get this corrected.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jaimeo @zdvorak - Do you have any updates on this?

Thank you.

**Comment by MaratMussabekov** [comment]
Dear @juanand , 
**and this article does not notice the warning above** - as you can see in the article, in the "Deploy the compatibility update and related updates" section: "We also recommend installing the latest Windows Monthly Rollup on Windows 7 and Windows 8.1 devices.", so the organizations that use only security updates should deploy monthly updates before deploying Windows Analytics. The warning means that the recommendations were ignored, I think that in this case it shouldn't be noticed in the article separately. What do you think?
**FWLink in log file is dead** - dear @mypil , the broken link issue should be addressed to the team responsible for Upgrade Readiness 

Thank you

**Comment by jaimeo** [comment]
I've looked up the owner of the FWlink and let them know. @zdvorak did you have any input on the other question?

**Comment by mypil** [comment]
@jaimeo @zdvorak - We would like to follow up. Do you have any updates on this?

Thanks.

**Comment by mypil** [comment]
@jaimeo @zdvorak - Any updates on this?

**Comment by mypil** [comment]
@jaimeo @zdvorak @lomayor - We would like to follow up on this. Do you have any updates on how we can fix broken link issue(FWLink in log file is dead)?

Thank you.

**Comment by jaimeo** [comment]
I thought we fixed that link already. I've looked up an owner for it and send them this issue again.

**Comment by zdvorak** [comment]
I've also created a PR for the other issue mentioned above (KB 2952664 being superseded).

**Comment by jaimeo** [comment]
Albert is redirecting the FWlink to windows-analytics-get-started where we've added some explanation about diagtrack.

**Comment by mypil** [comment]
@juanand - Thank you for submitting feedback.

From our understanding, the issue has been answered by jaimeo, zdvorak & MaratMussabekov. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
