### ISSUE TITLE
Public Key Infrastructure requirements unclear for key-trust deployments

### ISSUE THREAD

**Issue by robmacf** [MicrosoftDocs/windows-itpro-docs#3351]
In the Public Key Infrastructure section, I believe there should be explicit direction for what to do about Certificate Templates for Key Trust deployments. Perhaps after this sentence, "If box 1b on your planning worksheet reads key trust, write N/A in box 5b on your planning worksheet" one could add "No additional certificate templates are required for key trust deployments. Skip to the Cloud section" or something like that. Currently it's not totally clear that the RA and additional templates don't apply for key trust.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5739fab2-c6db-a7a9-b0e7-2bf4b85912a7
* Version Independent ID: 82c58053-c1d7-d938-1b0f-f3f7f70ada3b
* Content: [Planning a Windows Hello for Business Deployment](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-planning-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-planning-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@robmacf - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@robmacf - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
