### ISSUE TITLE
404 Links - .md Suffix

### ISSUE THREAD

**Issue by FreeTheTech101** [MicrosoftDocs/windows-itpro-docs#3352]
The first two links under the "[More Information](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/prepare-your-organization-for-bitlocker-planning-and-policies#more-information)" header result in a 404 error message. This is the result of the accidental inclusion of the .md suffix on both links.

Current Link | Correct Link
------------ | -------------
https://docs.microsoft.com/en-us/windows/security/hardware-protection/tpm/trusted-platform-module-overview.md|https://docs.microsoft.com/en-us/windows/security/hardware-protection/tpm/trusted-platform-module-overview
https://docs.microsoft.com/en-us/windows/security/hardware-protection/tpm/trusted-platform-module-services-group-policy-settings.md|https://docs.microsoft.com/en-us/windows/security/hardware-protection/tpm/trusted-platform-module-services-group-policy-settings

As a side note, there also seems to be a discrepancy in the displayed 404 error message:

![firefox_2019-04-24_13-38-29](https://user-images.githubusercontent.com/7614507/56681042-78d71580-6696-11e9-949e-ed4ef62d86b7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d1e77d9-00eb-7907-08ba-ddb5557fa51e
* Version Independent ID: 5a0a4a51-0bea-a266-1796-f21918cd04e2
* Content: [Prepare your organization for BitLocker Planning and policies (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/prepare-your-organization-for-bitlocker-planning-and-policies#feedback)
* Content Source: [windows/security/information-protection/bitlocker/prepare-your-organization-for-bitlocker-planning-and-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/prepare-your-organization-for-bitlocker-planning-and-policies.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by illfated** [comment]
Thank you for reporting this issue. It is just as you described, the first 2 links incorrectly include the `.md` suffix from the Github page:
```
## More information

- [Trusted Platform Module](/windows/security/hardware-protection/tpm/trusted-platform-module-overview.md)
- [TPM Group Policy settings](/windows/security/hardware-protection/tpm/trusted-platform-module-services-group-policy-settings.md)
- [BitLocker frequently asked questions (FAQ)](bitlocker-frequently-asked-questions.md)
- [BitLocker](bitlocker-overview.md)
- [BitLocker Group Policy settings](bitlocker-group-policy-settings.md)
- [BitLocker basic deployment](bitlocker-basic-deployment.md)
```
Even though the links are relative to the repository and are using the linked pages so they should work on Github (`.md` suffix), only the first 2 links seem to have missed the migration conversion to the docs.microsoft.com site.

If the issue had been with direct links (https://docs.microsoft.com/ [ ... ]) in the Github source, I could have helped out by writing a Pull Request to solve the issue. Currently, this is not the case, so we need one of the internal Microsoft technicians with write access to the official page to look at why the 2 links were not converted correctly and maybe apply the changes manually to the docs.microsoft.com page.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@FreeTheTech101 - Thank you for submitting feedback.

I will get this issue over to theWin10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Justinha - We need your insights on this issue. Please advise on how to proceed. Thank you.

**Comment by Justinha** [comment]
@mypil I think it's fixed now.

**Comment by illfated** [comment]
Confirmed. The links in https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/prepare-your-organization-for-bitlocker-planning-and-policies#more-information are now showing the correct URLs.

@FreeTheTech101 : Thank you for reporting the issue. Hope you enjoy the working links. 🕺

**Comment by mypil** [comment]
@FreeTheTech101 - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
