### ISSUE TITLE
Thanks for the information

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#3353]
from last year onwards , I used  windows powershell  cmd , to  export the custom startmenu layout.
Before exporting , I did pinned some applications  and  unpinned some  apps for my  custom design.
I will ask  another question after two days .
Thanks for the detailed explanation . Thanks to the  authors 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79fccecd-5484-0304-d82b-9425f1889a22
* Version Independent ID: 4df6b138-c1b5-b551-22c9-19d3d1f9105d
* Content: [Customize and export Start layout (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/customize-and-export-start-layout)
* Content Source: [windows/configuration/customize-and-export-start-layout.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/customize-and-export-start-layout.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@RAJU2529 - Thank you for submitting feedback. 

Is there something within this article that you suggest to be added or edited? Please share more details.

Thank you.

**Comment by RAJU2529** [comment]
Yes madam. Tomorrow I post with certain doubts.

**Comment by mypil** [comment]
@RAJU2529 - I would like to follow up on this. Is there something within this article that you suggest to be added or edited? Please share more details.

Thank you.

**Comment by RAJU2529** [comment]
Default location of Start menu layout 

C:\Users\Default\AppData\Local\Microsoft\Windows\Shell\
C:\Users\username\AppData\Local\Microsoft\Windows\Shell\

I would  like to like  add the  full command  like this for exporting
Export-StartLayout -Path C:\StartMenuLayout.xml

I would  like to like  add the  full command  like this for importing m open the cmd prompt run as admin 
copy /y C:\StartMenuLayout.xml C:\Users\Default\AppData\Local\Microsoft\Windows\Shell\

copy /y C:\StartMenuLayout.xml C:\Users\RAJU\AppData\Local\Microsoft\Windows\Shell\

After exported .xml file , I clearly analysis  using notepad  , I found the  following  the shortcuts links  are also pinned  in Start menu 

%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\
%APPDATA%\Microsoft\Windows\Start Menu\Programs\
%APPDATA%\Microsoft\Windows\Start Menu\Programs\System Tools\

I  have screenshots  of  exported and  imported . If you give permission to add those pics , I will pull requests.

**Comment by Malind19** [comment]
Hi @RAJU2529 , 
Thank you very much for your feedback. I would like to list your suggestions with my comments before I edit the article. 

1. Mention the default location of the Start Menu Layout. - I will add this to the article. 
2. Specify full command for export. - The link to the detailed command is included. So as a policy, we should not duplicate. If a user wishes to understand much deeper, the Export-StartLayout specific article link explains it best. 
3. Adding copy command. - This is a default copy command. Which I believe as a command prompt command for copying a file. I also believe a manual copy and paste will work as well. Kindly let me know if not. 
4. Additional short cut menus on Start Menu - Kindly clarify whether you suggest this as a Windows issue related to the export command?

**Comment by RAJU2529** [comment]
All the mentioned conditions are correct. You can those into article.
Point 4 is export command. It's not an Windows issues.
I think its hidden secrets.

**Comment by Malind19** [comment]
@RAJU2529 Thank you very much for quick response. @mypil As we discussed here I see #1 of my previous comment should be in the article. But I could not find #4 mentioned in anywhere else. So shall I consider adding it? or ignore it as it is not mentioned in any guidelines as a feature of the command? #2 and #3 will not be added as there are different reference articles for them that clarifies them to a better extent.

**Comment by RAJU2529** [comment]
#4 You can add as extra informations

**Comment by Malind19** [comment]
@mypil Created PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3821

**Comment by mypil** [comment]
@RAJU2529 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by RAJU2529** [comment]
ok madam. you can cLose now. I keep waiting for merged content. thanks a lot

**Comment by mypil** [comment]
@officedocsbot close
