### ISSUE TITLE
Impossible to restore quarantined files on networksshare

### ISSUE THREAD

**Issue by peteringemann** [MicrosoftDocs/windows-itpro-docs#3355]
The guide does not work if you want to restore files that was located on network-share. This is absolutely pure bullshit.
Thanks for eating my files and giving me no opportunities to restore them again.

**Comment by illfated** [comment]
It would be more helpful if you could link the docs.microsoft.com page in question. 
Do you have a suggestion for improving the docs page? 
If you can provide a suggestion, it would help for future readers of the document page.

**Comment by peteringemann** [comment]
Sure. 
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus

Defender just ate my files and tried to restore them using the above guide. No luck. The files flickers in GUI as like they are being restored from quarantine to my NAS (FreeNAS) and therefor removed from the list. But then they reappears in the quarantine list and are never restored. Fortunately I had a copy stored elsewhere. 
It is so frustrating that Defender is just eating my files without asking - usually antivirus gives you a toast message with options. 

Sorry for not including the link to begin with.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@peteringemann - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
