### ISSUE TITLE
Is WDAG available on Windows 10 Enterprise LTSC 2019?

### ISSUE THREAD

**Issue by yamauchikazu** [MicrosoftDocs/windows-itpro-docs#3356]
I was able to install WDAG on LTSC 2019 as described in this document.

However, since there is no Edge in the host OS, there is no way to use it in stand-alone mode. Even configuring enterprise mode failed with error 0x80070512 after multiple loops of initializing 50% to starting 90% and autorestart container.

I think that the cause is that the base image does not contain MicrosoftEdge.exe same as host os.

There is no binary at "C:\ProgramData\Microsoft\Windows\Containers\BaseImages\XXXXXXXXXXXXXX\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe" in LTSC 2019. This location is not empty for the Enterprise version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c696c9ed-b095-68ff-d50d-df345daf8a4a
* Version Independent ID: 50ad3b26-8e9b-6a56-7b3c-56c1374c4747
* Content: [What's new in Windows 10 Enterprise 2019 LTSC](https://docs.microsoft.com/en-us/windows/whats-new/ltsc/whats-new-windows-10-2019)
* Content Source: [windows/whats-new/ltsc/whats-new-windows-10-2019.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/ltsc/whats-new-windows-10-2019.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by VLG17** [comment]
@yamauchikazu One of the prerequisites for WDAG is Edge, and Windows 10 Enterprise 2019 LTSC does not have Edge installed, as you correctly observed.

WDAG was not designed for a version of windows that remains the same for 10 years such as LTSC (it won't be able to keep up with the modern security needs).

Even if you would get it to work, you won't be in a supported scenario, meaning if something goes wrong, Microsoft won't be able to help you solve that issue, nor would any fixes be created for that specific issue, should any be needed.

**Comment by yamauchikazu** [comment]
It is quite strange that an unsupported usage scenario is introduced in What's new 2019 LTSC.

**Comment by VLG17** [comment]
@yamauchikazu I understand what you mean and will try to get the article to reflect this.

**Comment by mypil** [comment]
looping in @greg-lindsay on this issue to get his insights.

**Comment by mypil** [comment]
@yamauchikazu - Thank you for submitting feedback. 

The content has been updated to reflect the changes that you requested for. From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
