### ISSUE TITLE
家庭版win10中如何关闭此功能

### ISSUE THREAD

**Issue by datongwzh** [MicrosoftDocs/windows-itpro-docs#3361]
家庭版中没有组策略管理，此页面不适用

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9bd0fe29-5db5-b752-5bcf-5ac2581baa9a
* Version Independent ID: 52b8d4ca-54ea-7345-12b0-df4fdf633083
* Content: [启用“首次看到时阻止”在几秒内检测到恶意软件](https://docs.microsoft.com/zh-cn/windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by illfated** [comment]
[From Google Translate]
> There is no Group Policy Management in the Home Edition. This page is not applicable.

@datongwzh : Please notice that most of the site is dedicated to Windows IT Pro. The targeted audience is IT Professionals using at least Windows 10 Pro and often Windows 10 Enterprise (E3 or E5).
***
请注意，该网站的大部分内容专用于Windows IT Pro。 目标受众是至少使用Windows 10 Pro和Windows 10企业版（E3或E5）的IT专业人员。

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@datongwzh - From our understanding, the issue you raised has been answered by illfated. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
