### ISSUE TITLE
Restrict DHCP option to known values

### ISSUE THREAD

**Issue by Artfoul** [MicrosoftDocs/windows-itpro-docs#3365]
Hi,

I'm using D.O. with DODownloadMode set to "2" (private group mode) and DOGroupIdSource set to "3" (DHCP scope mode). On my DHCP servers, I implemented several value of option ID 234 per my DHCP scopes. This seems to work fine.
However, I want my computers only to get/share updates only when at the office. I don't want them to get/share updates in public places.

Is there any way to perform this? Maybe by pushing a list of whitelisted values for Option ID 234? Or turning off local firewall rules on Public profile?

It seems tricky...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06745768-affe-c86a-2da6-7bd694e847c9
* Version Independent ID: e832ada1-5f0c-7809-b8a1-bb91cadb6975
* Content: [Policy CSP - DeliveryOptimization](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-deliveryoptimization#deliveryoptimization-docachehost)
* Content Source: [windows/client-management/mdm/policy-csp-deliveryoptimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-deliveryoptimization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by j0rt3g4** [comment]
All you can do in here is try to set up on the IPv4 and filter them by MAC
https://www.dell.com/support/article/mx/es/mxdhs1/sln288870/how-to-allow-or-deny-dhcp-server-leases-by-mac-address?lang=en

The point is that you won't have control over the devices when they left the branch, and DHCP is a promiscuous protocol, it will be continually asking for an IP it won't just "be aware" if the device is inside the network or outside it.

**Comment by mypil** [comment]
@Artfoul - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by j0rt3g4. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@Artfoul - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by <freelancer>. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
