### ISSUE TITLE
Convert-WindowsImage does not work as described and Connect-AppvSequencer also

### ISSUE THREAD

**Issue by Reittier** [MicrosoftDocs/windows-itpro-docs#3366]
Convert-WindowsImage -SourcePath "&lt;path_to_iso_image&gt;" -VHDFormat "VHD" -VHDPartitionStyle "MBR"

Does not work for me. Getting in a boot error later when trying to boot the VM (on a HyperV Host with OS Windows 10 1809)

Connect-AppvSequencerVM -VMName "&lt;name_of_vm&gt;" -ADKPath "&lt;path_to_adk_install_folder&gt;"

Does'nt work either on 1809 because there is no Parameter "-ADKPath" in CMDlet Connect-AppVSequencerVM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 103f741d-146b-c1f7-ac14-093094a212b6
* Version Independent ID: e28f143b-6475-b4bf-8e19-2c0b0540b750
* Content: [Automatically provision your sequencing environment using Microsoft Application Virtualization Sequencer (App-V Sequencer) (Windows 10)](https://docs.microsoft.com/en-us/windows/application-management/app-v/appv-auto-provision-a-vm)
* Content Source: [windows/application-management/app-v/appv-auto-provision-a-vm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/app-v/appv-auto-provision-a-vm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **elizapo**

**Comment by get-itips** [comment]
Hello @Reittier 
Thanks for your feedback, I created a PR to correct the documentation.
About the error you are experiencing whilte booting the Image, I encourage you to please follow this link to contact support for Windows 10 products: https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10

Thank you!

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Reittier - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
