### ISSUE TITLE
Log Analytics has been renamed to Log Analytics workspaces.

### ISSUE THREAD

**Issue by jwojan** [MicrosoftDocs/windows-itpro-docs#3367]
Under the "Navigation and permissions in the Azure portal" the document states:
"To check the Log Analytics workspaces you can access, select Log Analytics."

The entry in Azure Portal has been renamed to Log Analytics Workspaces". 

As a result the text and several screenshots are no longer current/accurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9dadd7a-2a10-0330-5e3b-8736ee37d0b0
* Version Independent ID: 5ebbfa1e-097d-0624-49d3-334d2625d806
* Content: [Windows Analytics in the Azure Portal](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-azure-portal?wt.mc_id=4039827#feedback)
* Content Source: [windows/deployment/update/windows-analytics-azure-portal.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-azure-portal.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jwojan - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@MaratMussabekov - As discussed, kindly assist to work on this issue. Thank you.

**Comment by mypil** [comment]
@jwojan - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
