### ISSUE TITLE
How to unset proxy

### ISSUE THREAD

**Issue by ggbce** [MicrosoftDocs/windows-itpro-docs#3372]
This page explain how to set machine proxy with "netsh", but Nothing explain to remove (return to default) the proxy. The old Microsoft help page had these informations. Please add sample to explain how to set "no proxy" when a proxy was previoulsy added.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83207fc9-2c91-eb07-4237-6bb1f42e3778
* Version Independent ID: 5db33cf3-2dcb-bb33-a252-3a13ca9737f9
* Content: [Configure machine proxy and Internet connection settings](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-proxy-internet-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/configure-proxy-internet-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/configure-proxy-internet-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by iadgovuser1** [comment]
netsh winhttp reset proxy

**Comment by illfated** [comment]
Should be pretty straight-forward, but I guess it would be nice to have the reset command mentioned on the page as well (even if it is available in the help function).
Windows Support page describing the related command line options:
- https://support.microsoft.com/en-us/help/900935/how-the-windows-update-client-determines-which-proxy-server-to-use-to

Command-line options in a CMD console:
```
C:\WINDOWS\system32>netsh /?

Usage: netsh [-a AliasFile] [-c Context] [-r RemoteMachine] [-u [DomainName\]UserName] [-p Password | *]
             [Command | -f ScriptFile]

The following commands are available:

Commands in this context:
?              - Displays a list of commands.
add            - Adds a configuration entry to a list of entries.
advfirewall    - Changes to the `netsh advfirewall' context.
bridge         - Changes to the `netsh bridge' context.
delete         - Deletes a configuration entry from a list of entries.
dhcpclient     - Changes to the `netsh dhcpclient' context.
dnsclient      - Changes to the `netsh dnsclient' context.
dump           - Displays a configuration script.
exec           - Runs a script file.
firewall       - Changes to the `netsh firewall' context.
help           - Displays a list of commands.
http           - Changes to the `netsh http' context.
interface      - Changes to the `netsh interface' context.
ipsec          - Changes to the `netsh ipsec' context.
lan            - Changes to the `netsh lan' context.
mbn            - Changes to the `netsh mbn' context.
namespace      - Changes to the `netsh namespace' context.
netio          - Changes to the `netsh netio' context.
p2p            - Changes to the `netsh p2p' context.
ras            - Changes to the `netsh ras' context.
rpc            - Changes to the `netsh rpc' context.
set            - Updates configuration settings.
show           - Displays information.
trace          - Changes to the `netsh trace' context.
wcn            - Changes to the `netsh wcn' context.
wfp            - Changes to the `netsh wfp' context.
winhttp        - Changes to the `netsh winhttp' context.
winsock        - Changes to the `netsh winsock' context.
wlan           - Changes to the `netsh wlan' context.

The following sub-contexts are available:
 advfirewall bridge dhcpclient dnsclient firewall http interface ipsec lan mbn namespace netio p2p ras rpc trace wcn wfp winhttp winsock wlan

To view help for a command, type the command, followed by a space, and then
 type ?.

C:\WINDOWS\system32>netsh winhttp /?

The following commands are available:

Commands in this context:
?              - Displays a list of commands.
dump           - Displays a configuration script.
help           - Displays a list of commands.
import         - Imports WinHTTP proxy settings.
reset          - Resets WinHTTP settings.
set            - Configures WinHTTP settings.
show           - Displays currents settings.

To view help for a command, type the command, followed by a space, and then
 type ?.


C:\WINDOWS\system32>netsh winhttp reset /?

The following commands are available:

Commands in this context:
reset proxy    - Resets WinHTTP proxy setting to DIRECT.
reset tracing  - Use netsh trace stop.

C:\WINDOWS\system32>_
```
- Question 1: Would it be necessary (for admins & IT Pro users) to have the example added in the documentation page, seeing that the command line options are available in most versions of Windows 10 (including Windows 10 Home)?
- Question 2: Would it be enough to add only 2 lines, one descriptive line saying "To remove a non-functional proxy configuration and reset its settings to default, use the following command:" and the other line simply containing the code box with the command example? Or does it need its own full section, like the existing section [**Configure the proxy server manually using netsh command**](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-proxy-internet-windows-defender-advanced-threat-protection#configure-the-proxy-server-manually-using-netsh-command) ?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ggbce - Thank you for submitting this feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by illfated** [comment]
Looks good to me. The update has now been migrated to https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-proxy-internet-windows-defender-advanced-threat-protection#configure-the-proxy-server-manually-using-netsh-command
Should be OK to close this issue now.

**Comment by mypil** [comment]
@officedocsbot close
