### ISSUE TITLE
Provide additional information about the built-in MDATP admin role

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#3375]
At the very end of the "Create roles and assign the role to an Azure Active Directory group" section, it would be useful to call out how "special" the default admin role is. Example code snippet:

```
>[!NOTE]
>The Windows Defender ATP administrator (default) role has administrator permissions. The administrator permissions cannot be assigned to any other role. Only user groups assigned to the Windows Defender ATP administrator role can manage permissions using RBAC. User groups assigned the Windows Defender ATP administrator role have access to **all** machine groups.
```

Or something similar to above. The admin role does not behave like any of the other roles which is important to call out. The language I used above is mostly taken from the WDSC UI (e.g. "Add machine group" dialog's "User access" section). Text would render similar to below.

>[!NOTE]
>The Windows Defender ATP administrator (default) role has administrator permissions. The administrator permissions cannot be assigned to any other role. Only user groups assigned to the Windows Defender ATP administrator role can manage permissions using RBAC. User groups assigned the Windows Defender ATP administrator role have access to **all** machine groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b246db4-2ef2-fc54-8db1-7a75a4974304
* Version Independent ID: 57290170-ba72-9f26-5a9c-311f6980ea19
* Content: [Create and manage roles for role-based access control](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/user-roles-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/user-roles-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/user-roles-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@iadgovuser1 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by ojrb** [comment]
Hi @mypil  the PR #3676 solved this issue ! Please review and Merge !

**Comment by mypil** [comment]
@iadgovuser1 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
