### ISSUE TITLE
bootmgr file name and path

### ISSUE THREAD

**Issue by vanderl2796** [MicrosoftDocs/windows-itpro-docs#3377]
In the summary, it shows bootmgr (UEFI) as bootmgfw.efi and the path as  \EFI\Microsoft\Boot\bootmgfw.efi  but on my 1806 version of Windows 10 the file is "bootmgr.efi" and is in the root of the system partition.   There is no bootmgrw.efi?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc264df-cbd1-ac1f-3926-841fcab7dc31
* Version Independent ID: 67c2aea4-0d28-3d8e-e935-8af05291c94e
* Content: [Advanced troubleshooting for Windows boot problems](https://docs.microsoft.com/en-us/windows/client-management/advanced-troubleshooting-boot-problems#feedback)
* Content Source: [windows/client-management/advanced-troubleshooting-boot-problems.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/advanced-troubleshooting-boot-problems.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@vanderl2796 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello @vanderl2796 ,
**but on my 1806 version of Windows 10 the file is "bootmgr.efi" and is in the root of the system partition. There is no bootmgrw.efi?** - there should be bootmgrw.efi, but it is not located in system partition, it is located in motherboard NVRAM. You can read more [here](https://docs.microsoft.com/windows-hardware/manufacture/desktop/bcd-system-store-settings-for-uefi)
Thank you

**Comment by mypil** [comment]
@vanderl2796 - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by RAJU2529** [comment]
But I have found that file bootmgrfw.efi in windows PE addson.
I think I also found in efi partition, only if Windows booted in uefi Mode
