### ISSUE TITLE
Missing screenshot in WDATP offboarding doc

### ISSUE THREAD

**Issue by amirsc3** [MicrosoftDocs/windows-itpro-docs#3381]
The doc shows 
"![Image of server onboarding](images/atp-server-offboarding-workspaceid.png)" 

Location of the doc bug:
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-server-endpoints-windows-defender-advanced-threat-protection#run-a-powershell-command-to-remove-the-configuration

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@amirsc3 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro  writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by Reeced40** [comment]
@amirsc3 Thank you for reaching out and helping improve MS docs. I'll investigate further and let you know.

**Comment by mypil** [comment]
@amirsc3  - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
