### ISSUE TITLE
Impossible to audit data

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/windows-itpro-docs#3383]
Data is encoded, encrypted or in some other way made unreadable for normal human beings.
Exactly what conclusions, information or understanding should I get from data like this?
0x4D5445314F5441354E6A49334D7A63344D4463334D6A51314F4449354F5451344F544D334F4467334D6A63304F544D784D7A63774D6A63344F4459314E44637A4D5451334E5441784F5455310A4E5445324D6A59314D54557A4E5441314E5441304E7A63334E7A51784D5449324D5467334E5451344E4459324D6A51794F5441774E544D354F5451324E5441354D6A59334D4449344D6A4D300A4D7A51784D446B794D7A41774E7A59334E5459314D6A67334D7A49324F5451324E54497A4F4445784F444D774D6A67774F4445794E7A63314D4441324D7A4D314E4467784E5459784E4445320A4D444D354F5463324E444D304F5459784F4459334D544D304E4455774E6A677A4E4445324E6A6B304D4449354D54637A4D4459784F4459314E7A55344D4441344D4449774F544D324D5467350A4D4459314D5451784D5463314D54637943676F3D

If the intention is that a user should be able to see which data you collect, and your ambition is to be transparent and open with what data you collect, then do you think data like in the example above make you appear more open and transparent, or do you think it make you look like you are collecting something you don't want users to see and be aware of?

Exactly what is it you are trying to hide? And why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54254070-539b-6cf2-f988-c80ad685c5fa
* Version Independent ID: 5bbe5140-eee5-abc3-1a26-1c0d13eab358
* Content: [Diagnostic Data Viewer Overview (Windows 10)](https://docs.microsoft.com/en-us/windows/privacy/diagnostic-data-viewer-overview)
* Content Source: [windows/privacy/diagnostic-data-viewer-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/diagnostic-data-viewer-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
Hi @Bartolomeus-649, 
To the best of my knoweldge, not all data that's sent appears in DDV this way. Could you specify which event or service was showing you this data?

**Comment by Bartolomeus-649** [comment]
it is ll over the place, don't remember exactly where, but I know for sure data like this is present in the "browser category" .

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @Bartolomeus-649 thank you for providing feedback.

The issues section of this repository is intended for product documentation issues.

Please consider opening a product support ticket by the following link below for your question so that it gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by robertmizani** [comment]
Without magistrate one can simply use GDP (Good Documentation Practices) for audit purposes with print-ed documents and sign-ed change controls. Please have a good day. Thank you.

**Comment by illfated** [comment]
@e0i : Looks like @officedocsbot did not obey your command above. 😞
