### ISSUE TITLE
Clarifications needed

### ISSUE THREAD

**Issue by ohadschn** [MicrosoftDocs/windows-itpro-docs#3384]
Hi,

1. There seem to be various names for this feature, is it true that "Secure Launch" = "System Guard" = "Firmware Protection"?
2. The overview says "This topic explains how to configure System Guard Secure Launch and System Management Mode (SMM) protection" but then the rest of the document is about Secure Launch and SMM is not mentioned.
3. "Requirements Met by System Guard Enabled Machines, Any machine with System Guard enabled will automatically meet the following low-level hardware requirements" - this sentence is very confusing. Does the table that follow constitute the prerequisites for enabling the feature? Specifically, is this feature only supported starting Intel® vPro™ processors starting with Intel® Coffeelake, Whiskeylake, or later silicon (or Qualcomm® processors with SD850 or later chipsets)?

Thanks,
Ohad

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31d623d9-316c-0ef1-b6be-c3773d77ca21
* Version Independent ID: 83ddb59d-0cfc-34f2-e666-8927d86a04a7
* Content: [System Guard Secure Launch and SMM protection (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ohadschn - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro  writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@ohadschn Please see my comments for each of the points you raised:

1. Windows Defender System Guard is the name given for a family of security features, amongst which we find "Secure Lauch" and "Firmware Protection", two independent security features.

2. Although not very intuitive, the first sentence "This topic explains how to configure [System Guard Secure Launch and System Management Mode (SMM) protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-system-guard/system-guard-how-hardware-based-root-of-trust-helps-protect-windows) to improve the startup security of Windows 10 devices." contains a link to an article where SMM is described in depth.

3. Correct, these are the hardware requirements. You can couple this information with what is here, under VBS (which is a must) hardware requirements:  https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-vbs

**Comment by ohadschn** [comment]
@VLG17 thank you for clarifying here, but ideally these would also be clear in the actual doc text.

**Comment by mypil** [comment]
@ohadschn - Could you please assist us by suggesting how this content could be edited to incorporate your feedback? If you could suggest what the appropriate text and where it should be placed, I could assign one of our team members to create a Pull Request to get it added or you may also create a Pull Request to add in your suggestion and just link this issue so I can have the doc owner review and merge the content.   Thank you.

**Comment by mypil** [comment]
@ohadschn - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to open a new issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
