### ISSUE TITLE
Application Usage Data for Windows 7, 7SP1 for Upgrade Readiness Management Solution

### ISSUE THREAD

**Issue by balait01** [MicrosoftDocs/windows-itpro-docs#3386]
Home
 
Search the community
Home
Upgrade Readiness
Application Usage Data for Windows 7,7SP1 Machines : Upgrade Readiness Management Solution
 Balasubramanian Murugesan
Balasubramanian Murugesan CONTRIBUTOR
54m ago

Hi,

 

Whether Upgrade Readiness Management Solution collects Application Usage Data for Windows 7,7SP1 Operating Systems? under Monthly Active computers and Percent Active Computers in Total Application in Upgrade Readiness Overview Dashboard?

 

This is enabled by following Microsoft documentation. But we are unable to see the Application Usage data, i.e,  App Usage Data for Windows 7, 7SP1 OS.

And how a scheduled Scan(for Upgrade Readiness Management Solution) run for an Desktop when its in shutdown or not connected to internet state.

After once connected next day, then now telemetry data gets collected for previous day and for an existing day and now the data gets resembled while querying via Advanced Analytics.

Thanks & Regards,
Balasubramanian.Murugesan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d314758-3fa1-0d3d-829f-f74c4fabf7e0
* Version Independent ID: 3cc3212c-bde7-9566-ecd9-7417843d4b96
* Content: [Upgrade Readiness - Upgrade Overview (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-upgrade-overview#feedback)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-upgrade-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-upgrade-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
Hello @balait01 , Thank you for posting your query. Can you please summarize your question so that we can better understand your query and help you accordingly and update the doc if required.

**Comment by mypil** [comment]
@balait01 - We would like to follow up. Can you please respond to the query from joinimran? Thank you.

**Comment by mypil** [comment]
@officedocsbot close
