### ISSUE TITLE
Latest Servicing Stack Updates

### ISSUE THREAD

**Issue by alexfreu** [MicrosoftDocs/windows-itpro-docs#3390]
What about the list at https://portal.msrc.microsoft.com/en-us/security-guidance/advisory/ADV990001
The page shows nothing. Could you please fix the list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b706f0af-d504-a8ca-7c38-b8bb9283bfad
* Version Independent ID: 14f31acf-9f47-59a6-269f-62ab249fe560
* Content: [Servicing stack updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates#feedback)
* Content Source: [windows/deployment/update/servicing-stack-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/servicing-stack-updates.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by Gtfinchy** [comment]
As Alex noted & bugged - The entire PAGE of SSU information has disappeared from docs.microsoft.com. My customer, an USA DoD entity, uses the latest SSU infomation to prepare an updated Reference Image for OS deployment across multiple enviroments. The REQUIREMENT to stay updated AT DEPLOY TIME includes current SSU. Please fix this resource so recently given. They cannot wait for WU, SCCM, or other patch engine to offer the requisite update as staying current includes the ability to actually GO TO THE NEXT CU that a lack of a servicing engine update may prevent. The very definition of a required SSU is that it can't be bundled w/an update that expects it to be there!

**Comment by jaimeo** [comment]
We have reported this to the people who own that page.

**Comment by Gtfinchy** [comment]
thank you!

/** Glenn Fincher -  gfincher@live.com<mailto:gfincher@live.com> - (256) 565-9958 **/  <mailto:gfincher@live.com>



________________________________

**Comment by jaimeo** [comment]
We believe this is fixed. Do let us know if it's still not loading for you.

**Comment by alexfreu** [comment]
Looks good. Thanks a lot!

**Comment by hmcmtg** [comment]
The links for Windows Server 2016 and 2019 are broken

**Comment by jaimeo** [comment]
I'll let the owners of that page know about the broken links.

**Comment by jaimeo** [comment]
We believe this is now fixed.

**Comment by hmcmtg** [comment]
Yes, thank you.

**Comment by mypil** [comment]
@alexfreu - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by SwooshyCueb** [comment]
It looks like the link is dead again. ADV990001 is completely blank.

**Comment by jaimeo** [comment]
Thanks for letting us know--I've alerted the contact that helped us last time.

**Comment by Gtfinchy** [comment]
Is there tracks on the file? Perhaps the same person keeps whacking it?

- Glenn Fincher

Tiny screen, fat fingers.., sent from iOS


On May 23, 2019, at 9:03 PM, jaimeo <notifications@github.com<mailto:notifications@github.com>> wrote:


Reopened #3390<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindows-itpro-docs%2Fissues%2F3390&data=02%7C01%7C%7C9ce7042eea4344b6161b08d6dfb1641f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636942350306560437&sdata=6BaCCOLsZdVHDI1YDxPFrc9nAgeKYiPGuSI2QaRE6BU%3D&reserved=0>.

**Comment by jaimeo** [comment]
We believe this is fixed.

**Comment by mypil** [comment]
@alexfreu - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
