### ISSUE TITLE
Undo SharedPC Mode?

### ISSUE THREAD

**Issue by tigeraaditya** [MicrosoftDocs/windows-itpro-docs#3391]
Is it possible to turn 'OFF' shared PC Mode by changing the Boolean value of OMA-URI policy to 'False'? Because in my experience pushing such a policy didn't disable all the rest of the policies pushed on the device from Intune. For example all the policies listed in this article: https://docs.microsoft.com/en-us/windows/configuration/set-up-shared-or-guest-pc#policies-set-by-shared-pc-mode were still active on the device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14b376e2-39bd-faca-a76c-dd21bad8d8fd
* Version Independent ID: a76cabb0-59b9-7e97-6603-eec7d37f1fd4
* Content: [Set up a shared or guest PC with Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/set-up-shared-or-guest-pc)
* Content Source: [windows/configuration/set-up-shared-or-guest-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/set-up-shared-or-guest-pc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@tigeraaditya - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by Malind19** [comment]
@mypil All the articles are showing how to enable SharedPC mode. No mention on how to disable. Even according to the following article. https://www.scconfigmgr.com/2018/10/27/building-a-shared-pc-mode-kiosk-with-microsoft-intune/

Appreciate if we can get author support.

**Comment by mypil** [comment]
@tigeraaditya - From our understanding, the issue you raised has been answered by Malind19. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
