### ISSUE TITLE
[LOC]Showing "**[ファイルの削除のみ行う] **" (extra asterisks appears)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3394]
https://docs.microsoft.com/ja-jp/education/windows/use-set-up-school-pcs-app

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e2ca5807-f011-cdd1-eb80-c74655aa4738
* Version Independent ID: fe016307-69a4-ec63-4979-eac841d13c3c
* Content: [学校用 PC のセットアップ アプリを使用する](https://docs.microsoft.com/ja-jp/education/windows/use-set-up-school-pcs-app)
* Content Source: [education/windows/use-set-up-school-pcs-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/use-set-up-school-pcs-app.md)
* Product: **w10**
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by mypil** [comment]
officedocsbot assign @mypil
@officedocsbot add label localization

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by illfated** [comment]
Looks like the translation (script?) has made a mistake in the 4. line in the second section of "Prepare existing PC account for new setup":

https://docs.microsoft.com/ja-jp/education/windows/use-set-up-school-pcs-app#%E6%97%A2%E5%AD%98%E3%81%AE-pc-%E3%82%A2%E3%82%AB%E3%82%A6%E3%83%B3%E3%83%88%E3%82%92%E6%96%B0%E3%81%97%E3%81%84%E3%82%BB%E3%83%83%E3%83%88%E3%82%A2%E3%83%83%E3%83%97%E3%82%92%E6%BA%96%E5%82%99%E3%81%97%E3%81%BE%E3%81%99

(https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/use-set-up-school-pcs-app.md#prepare-existing-pc-account-for-new-setup)

The asterisks (2 before the text, 2 after) should be read as formatting characters and converted to the code for **bold** (`<strong> </strong>`)
Unfortunately, I have been unable, so far, to find out why that happened to only that single line and not any of the other lines.

**Comment by mypil** [comment]
@officedocsbot unassign @mypil

**Comment by illfated** [comment]
Follow-up to my comment https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3394#issuecomment-488260618 : It looks like the Machine Translation script added an unwanted space between the Japanese characters and the second set of asterisks (as well as removing the space after the second set of asterisks), making them not work as formatting characters. This is what the text should have looked like:
1. **[トラブルシューティング]** をクリックして、**[この PC を初期状態に戻す]** を選びます。
2. **[すべて削除する]** を選びます。
3. このオプションが表示された場合は、 **Windows がインストールされているドライブのみ** を選択します。
4. **[ファイルの削除のみ行う]** をクリックします。
5. **[初期状態に戻す]** をクリックします。

(The 4. line is the reported issue, referenced in the issue title.)

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @MollyMalone
@officedocsbot add label localization

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
Thank you for the feedback.  This is a problem with the MT tool.  I have reported the problem to the tool owners.   I don't expect this issue to be fixed quickly.  I will update when we have a fix.
フィードバックをありがとうございました。 これは MT ツールの問題です。 私はツールの所有者に問題を報告しました。  この問題がすぐに解決されるとは思いません。 修正が必要になったときに更新します。

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated. Please verify that it is fixed. Thanks again for the feedback)

**Comment by illfated** [comment]
Sorry to disappoint you, but the original issue persists: https://docs.microsoft.com/ja-jp/education/windows/use-set-up-school-pcs-app#追加の領域用に-usb-ドライブを構成する

***

**[スタート]** > **[電源]** アイコンに移動することもできます。 Shift キーを押しながら **[再起動]** をクリックして、Windows ブート ユーザー エクスペリエンスを読み込みます。 そこから、次の手順に従います。

1. **[トラブルシューティング]** をクリックして、**[この PC を初期状態に戻す]** を選びます。
2. **[すべて削除する]** を選びます。
3. オプションが表示された場合は、**[Windows がインストールされているドライブのみ]** を選びます。
4. **[ファイルの削除のみ行う] **をクリックします。
5. **[初期状態に戻す]** をクリックします。

***
Notice that line number 4 still contains a space character between the text and the following 2 asterisks, breaking the MarkDown **bold** formatting.

**Comment by hyoshioka0128** [comment]
@TinaMcN - It's not Corrected as @illfated  says.
![use-set-up-school-pcs-app](https://user-images.githubusercontent.com/40815708/72034786-56932f80-32d9-11ea-8a0b-d7877f327e35.png)

**Comment by TinaMcN** [comment]
そのことについてお詫び申し上げます。  私は翻訳者に問題を調査し、修正するように頼みました。 (I apologise about that.   I have asked the translators to investigate and fix the issue.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 これで問題が修正されました。 フィードバックをありがとう。 (The issue has now been fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN  - Corrected.
Closed  #3394.
Thanks
