### ISSUE TITLE
[パーソナル設定] needs to be replaced with [個人用設定] 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3395]
https://docs.microsoft.com/ja-jp/windows/configuration/windows-10-start-layout-options-and-policies

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2af6b2fc-a4ad-bed9-1e52-e0591559626e
* Version Independent ID: 841feed2-bb25-0348-bd8f-be7d4c70a405
* Content: [Windows 10 のスタート画面とタスク バーのレイアウトを管理する (Windows 10)](https://docs.microsoft.com/ja-jp/windows/configuration/windows-10-start-layout-options-and-policies)
* Content Source: [windows/configuration/windows-10-start-layout-options-and-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/windows-10-start-layout-options-and-policies.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by mypil** [comment]
officedocsbot assign @mypil
@officedocsbot add label localization

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by PawelFronczak** [comment]
Investigating in VSO Bug 21440047

**Comment by mypil** [comment]
@officedocsbot unassign @mypil

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @MollyMalone
@officedocsbot add label localization

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
私は人間の翻訳のためにこの記事を送った。 約2週間かかります。 (I sent this article to be human translated.  It should take approximately 2 weeks.)

**Comment by TinaMcN** [comment]
記事は現在、人間が翻訳されています。 問題が解決したことを確認してください。 フィードバックをありがとう。
(The article is now human translated.  Please verify that the issue is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN  - Not Fixed.

![windows-10-start-layout-options-and-policies](https://user-images.githubusercontent.com/40815708/69796067-b0033b80-1210-11ea-99d1-2bcd631dde5a.png)

![windows-10-start-layout-options-and-policies_2](https://user-images.githubusercontent.com/40815708/69796078-b4c7ef80-1210-11ea-92f6-b6b892fd1a29.png)

**Comment by illfated** [comment]
Unfortunately, I am still unable to read kanji, but if this issue ticket title 
> **[パーソナル設定] needs to be replaced with [個人用設定]** 

refers to any and all occurrences of the text **パーソナル設定** in the page and that it should be replaced with **個人用設定** for all those occurrences, I can only conclude that there are still **8 occurrences** of the text 
> パーソナル設定

on the affected page (windows-10-start-layout-options-and-policies).

**Comment by TinaMcN** [comment]
@hyoshioka0128 そのことについてお詫び申し上げます。  私は翻訳者に問題を調査し、修正するように頼みました。 (I apologise about that.   I have asked the translators to investigate and fix the issue.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 これで問題が修正されました。 フィードバックをありがとう。 (The issue has now been fixed.  Thanks again for the feedback.)

**Comment by illfated** [comment]
Confirmed, the article now contains 8 occurrences of 個人用設定 and none of パーソナル設定 .

**Comment by hyoshioka0128** [comment]
@TinaMcN  - Corrected.
Closed #3395.
Thanks.
