### ISSUE TITLE
[よく使われるアプリを表示する]  needs to be replaced with [よく使うアプリを表示する]

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3396]
https://docs.microsoft.com/ja-jp/windows/configuration/windows-10-start-layout-options-and-policies

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2af6b2fc-a4ad-bed9-1e52-e0591559626e
* Version Independent ID: 841feed2-bb25-0348-bd8f-be7d4c70a405
* Content: [Windows 10 のスタート画面とタスク バーのレイアウトを管理する (Windows 10)](https://docs.microsoft.com/ja-jp/windows/configuration/windows-10-start-layout-options-and-policies)
* Content Source: [windows/configuration/windows-10-start-layout-options-and-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/windows-10-start-layout-options-and-policies.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by mypil** [comment]
officedocsbot assign @mypil
@officedocsbot add label localization

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by PawelFronczak** [comment]
Investigating in VSO Bug 21440047

**Comment by mypil** [comment]
@officedocsbot unassign @mypil

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @MollyMalone
@officedocsbot add label localization

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
私は人間の翻訳のためにこの記事を送った。 約2週間かかります。 (I sent this article to be human translated.  It should take approximately 2 weeks.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 問題が解決したことを確認してください。 フィードバックをありがとう。
(The article is now human translated.  Please verify that the issue is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN  - Not Fixed.
Add " [パーソナル設定]"→"[個人用設定]"

![windows-10-start-layout-options-and-policies](https://user-images.githubusercontent.com/40815708/69795865-484cf080-1210-11ea-992d-3b64fe8e55c2.png)

![windows-10-start-layout-options-and-policies_2](https://user-images.githubusercontent.com/40815708/69795881-50a52b80-1210-11ea-8c78-be4e19baf655.png)

**Comment by TinaMcN** [comment]
@hyoshioka0128 ご不便をおかけして申し訳ありません。 ローカリゼーションベンダーに問題を解決するよう依頼しました。 (Sorry for the inconvenience.  I asked the localization vendors to fix the issue.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 これで問題が修正されました。 フィードバックをありがとう。 (The issue has now been fixed.  Thanks again for the feedback.)

**Comment by illfated** [comment]
Confirmed, the text よく使うアプリを表示する has now been inserted as requested:
![image](https://user-images.githubusercontent.com/38162891/72124017-87b84200-3363-11ea-9aa0-b95f22768639.png)

The text よく使われるアプリを表示する no longer appears in the document article.

**Comment by hyoshioka0128** [comment]
@TinaMcN  - Corrected.
Closed #3396.
Thanks.
