### ISSUE TITLE
So you run MpCmdRun -ValidateMapsConnection

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/windows-itpro-docs#3411]
and you get a strange error code with no explanation (like 80058015) and no where to figure out what it means, no references for errors, let alone how to fix it.

Can we publish common error codes and how to fix them or what to check? Please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86b0db3-f979-bd1f-78a4-41247510721a
* Version Independent ID: 5289bb5f-f015-7f38-05a1-26a615ae07aa
* Content: [Configure and validate Windows Defender Antivirus network connections](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@vboyev-MSFT - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
