### ISSUE TITLE
Cut and paste error in the article

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#3416]
Cut and paste error in "Maximum Background Download Bandwidth".
The text does not actually explain what Background and Foreground bandwidth are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df445cda-3b0a-2ad7-e3cc-23e159013530
* Version Independent ID: a6bb5f97-d350-f7b7-77f7-b0093322289d
* Content: [Delivery Optimization reference](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization-reference#feedback)
* Content Source: [windows/deployment/update/waas-delivery-optimization-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-delivery-optimization-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @Air-Git 

Thank you for taking the time to provide feedback.

The issue is under investigation and you'll be notified on the go as the content gets updated.

Have a nice day.

**Comment by illfated** [comment]
More or less obvious that there is a typo in this sentence:
> - Maximum Foreground Download Bandwidth specifies the maximum **background** download bandwidth that Delivery Optimization uses across all concurrent download activities as a percentage of available download bandwidth.

(unexpected word highlighted in **bold** text)

**Comment by illfated** [comment]
@Air-Git : Would it help if you look at other pages, like https://www.windowscentral.com/how-limit-foreground-downloads-bandwidth-windows-10-april-2018-update ?
I can quote the paragraph I think is the most relevant:
> What's the difference between the two? Foreground downloads are those you start manually. For instance, when you click the Check for updates button on Windows Update, or the Get button to download an app from the Microsoft Store. On the other hand, background downloads are those downloads that are triggered automatically, such as when updates for Windows 10 download without user interaction.

Other than that, I personally think that the difference between Background and Foreground bandwidth is a technical term which is assumed to be known by IT Professionals.

**Comment by Air-Git** [comment]
I have never heard of foreground bandwidth. I have heard of foreground downloads, and download bandwidth, but never foreground download bandwidth, or foreground bandwidth.



________________________________

**Comment by no-identd** [comment]
This seems like a taxonomical issue:

Maximum {Fore⊻Back}ground Download Bandwidth
🆚
{Fore⊻Back}ground Download Bandwidth Maximum

Mathematically & strictly speaking, neither seems correct, instead, it should read SOMETHING LIKE this:

{Fore⊻Back}ground Download Bandwidth Limiting Filter Interval Maximum

However, that seems like both a mouthful and STILL very inaccurate, so, I had an idea:

@lemmy: please, might you consider providing some better phrasing? I figured, while this doesn't sound like a job for TLA+ as such, one of MS' in-house TLA+ experts could almost certainly come up with a phrase which describes what this ACTUALLY does, instead of just providing some seemingly clearly, but actually very unclear, phrasing.

**Comment by illfated** [comment]
PR #3511 created for
> Cut and paste error in "Maximum Background Download Bandwidth".

**Comment by jaimeo** [comment]
I agree that we should do a better job of explaining what exactly "foreground" and "background" are supposed to mean (we'll be updating all of the Delivery Optimization content soon for a forthcoming release, so there's a good opportunity to improve the explanation)--but as for the names themselves, there's nothing documentation can do to change that, as that's what the values are named in Group Policy (and MDM). Changing those names would be a code change, but we can certainly pass that request along.

**Comment by lemmy** [comment]
@no-identd Unfortunately, without being familiar with the semantics of waas it is impossible to come up with a precise specification.  That said, [Azure Cosmos DB](https://azure.microsoft.com/en-us/services/cosmos-db/) has indeed successfully demonstrated how to use the [TLA+ specification language](https://github.com/tlaplus/) to provide [user documentation](https://github.com/Azure/azure-cosmos-tla).

**Comment by Air-Git** [comment]
"Optimization" is a noun referring to the process of selecting the most effective or desirable way to do something. But "Delivery Optimization" appears to be the name of a process that controls or throttles downloads from Microsoft Updates. Perhaps "Delivery Control" would be a better term.
"Bandwidth" refers to the nominal or practical capacity of a link. "Rate" or "Speed" refers to the actual rate or speed of an individual transfer of data over the link. 
A rate may be expressed in absolute terms (e.g. Kb/s) or in percentage terms (e.g. 10% of the bandwidth).
In the policy itself, the "maximum foreground download" can be set as an absolute rate, or as a percentage.
"Foreground" seems to mean interactive; and "Background" seems to mean non-interactive or scheduled. The meaning in this case is not absolutely clear because, if I run updates from the GUI, then I would normally leave them to complete in the background. And they would indeed complete in the background. If I restarted the computer, the update task would continue.
I don't know what "across all concurrent download activities" means. I don't know if it means the sum of all Microsoft update activities; or the sum of all downloads (e.g. Netflix). I think it must be a redundant term, since "Delivery Optimization" already refers to a process that controls the collection of Microsoft updates.

So how about:
"Maximum Foreground Rate"
"Starting in Windows 10, version 1803, specifies the maximum rate of foreground (interactive) updates, as a percentage of available bandwidth. The default value of 0 means that foreground updates adjust dynamically to use all available bandwidth. This setting does not apply to downloads from LAN peers."

I appreciate that the document is actually a copy of the GPO ADML. But that is not a Reference. In a reference document I am expecting to find the most accurate and detailed description of the operation. In a GPO ADML I am expecting to find a quick explanation of how to use the setting. I would expect to go to the Reference documentation if the quick explanation were unclear.

**Comment by illfated** [comment]
Interesting, thank you for sharing the ideas.

**Comment by jaimeo** [comment]
@Air-Git, you are welcome to file your own PR with proposed changes. We will run that by the appropriate PM for their review of accuracy and will publish with their approval.

**Comment by j0rt3g4** [comment]
PR #3842  The article has already the corrections for this issue.

**Comment by e0i** [comment]
@Air-Git 

Upon your feedback, The content has been updated with additional changes. Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by Air-Git** [comment]
How strange. The cut and paste error remains exactly as before.

**Comment by e0i** [comment]
@Air-Git

The changes made to the repository are pushed to live by a Continuous Integration system and it might sometimes take a few days for the system to be triggered. Thank you for following-up.

**Comment by illfated** [comment]
@Air-Git : Maybe you need to refresh or clean your browser cache to see the updated page correctly. From what I can see, it appears to be corrected now. If you still see something you are certain is still incorrect, please copy & paste that part (or link the section, if possible) in a new comment here in this issue page.
