### ISSUE TITLE
If we configure from DC 2016 or Win 10 older version 1709, GPO settings under User Configuration not available

### ISSUE THREAD

**Issue by NagaCSC** [MicrosoftDocs/windows-itpro-docs#3420]
if you don't find the options in GPO they have to load "policy definition" folders - This is missing in our doc guidence
	https://support.microsoft.com/en-us/help/3087759/how-to-create-and-manage-the-central-store-for-group-policy-administra

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b38868db-0835-79e0-e37e-63fa1b0933ac
* Version Independent ID: de4f1a9f-b174-6cd8-0789-0d184cc8dc19
* Content: [Configuring Hybrid key trust Windows Hello for Business - Group Policy](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-policy)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@NagaCSC 

Thank you for taking providing feedback.

The issue is under investigation and you'll be notified on the go as the content gets updated.

**Comment by e0i** [comment]
@NagaCSC A PR is being worked out for this issue.

**Comment by j0rt3g4** [comment]
Solving issue with a note on #3841
