### ISSUE TITLE
[LOC] "Microsoft Intune でソフトウェア更新プログラムを管理します。" needs to be replaced with "Intune でのソフトウェア更新プログラムの管理"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3423]
https://docs.microsoft.com/ja-jp/hololens/hololens-updates

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5a78d719-bf9a-13e4-81ee-4133eb38c4f8
* Version Independent ID: a2955339-7086-7b42-f588-31ee7a53cf3c
* Content: [HoloLens (HoloLens) への更新プログラムを管理します。](https://docs.microsoft.com/ja-jp/hololens/hololens-updates)
* Content Source: [devices/hololens/hololens-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/hololens/hololens-updates.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@dongmicro Would you kindly review this Japanese localization issue?  Thanks.

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
Thanks for the feedback @hyoshioka0128
Set the topic to be human translated, will take 2-3 weeks to process

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間翻訳されており、問題は修正されているようです。 修正済みであることを確認してください。 フィードバックをありがとうございました。
(The article is now human translated and the issue appears to be fixed.  Please verify that it is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Fixed.
Closed #3423
Thanks.
