### ISSUE TITLE
wrong zh-cn translation in https://docs.microsoft.com/zh-cn/windows/configuration/wcd/wcd-policies

### ISSUE THREAD

**Issue by fadingflower** [MicrosoftDocs/windows-itpro-docs#344]
the Description of 
"Do not allow update deferral policies to cause scans against Windows Update."
should be
"不允许更新延期策略对 Windows 更新执行扫描"
the doc in docs.microsoft.com translated to 
"不允许更新延迟策略对 Windows 更新执行扫描。"

**Comment by eross-msft** [comment]
Hi @fadingflower, thank you for pointing this out. I've created a bug for our localization team to address this problem.
