### ISSUE TITLE
Showing "* https://graph.windows.net/myorganization/users/[userid]、 **[userid]*" (extra asterisks appears) 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3451]
https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert#prepare-active-directory-certificate-authority

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 9f709fd4-0b5d-b238-4060-222d550cd538
* Version Independent ID: fb3f29da-2236-c47d-6bea-8efbcec8d7d3
* Content: [AADJ オンプレミス シングル サインオンのシングル サインオンの証明書の使用](https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert#prepare-active-directory-certificate-authority)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@dongmicro Could you assist in resolving this localization issue? Thank you.

Similar issues:

#3159 #3394 #3453 #3452

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by illfated** [comment]
@TinaMcN : We may want to schedule the linked Docs page for a test run of automated translation after the en-us version of the document has been updated (in about a week's time?) to see if this issue ticket and its directly related ticket #3453 can be closed, if the change successfully removes the formatting problem.
