### ISSUE TITLE
Broken link "ドメイン コント ローラーの証明書を再発行します。"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3459]
https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base
![LINK_](https://user-images.githubusercontent.com/40815708/57059283-8ff9b100-6cef-11e9-8b7a-9118d702dac3.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 43c175ce-52a4-8b46-716f-106b4d55106c
* Version Independent ID: 374a7e9d-6e4f-f188-328b-4ca2651a9481
* Content: [Windows Hello for Business を使用して Azure AD に参加しているデバイスをオンプレミスのシングル サインオン用に構成する](https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
See: #3458

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 この問題は、機械翻訳に使用されるツールに関連しています。 私はツールを担当するチームにエスカレートしました。 (Thank you for the feedback.  The issue is related to the tool used for machine translating.  I have escalated to the team who are responsible for the tool.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Thank you.

**Comment by TinaMcN** [comment]
私は人間の翻訳のためにこの記事を送った。 約3週間かかります。 (I sent this article to be human translated.  It should take approximately 3 weeks.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated. Please verify that it is fixed. Thanks again for the feedback)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Not Corrected.

ja-jp:
``` html
<li><a href="#reissue-domain-controller-certificates" data-linktype="self-bookmark">ドメイン コントローラー証明書を再発行する</a></li>

<h3 id="ドメイン-コントローラー証明書を再発行する">ドメイン コントローラー証明書を再発行する</h3>
```
↑"id" is Translated.

Thanks.

**Comment by illfated** [comment]
Same issue as in #3455 & #3457 , mixed ASCII & kanji link information (link pointer & target mismatch).

**Comment by TinaMcN** [comment]
そのことについてお詫び申し上げます。  私は翻訳者に問題を調査し、修正するように頼みました。 (I apologise about that.   I have asked the translators to investigate and fix the issue.)

**Comment by e0i** [comment]
```html
<h3 id="インターネット-インフォメーション-サービスが-crl-配布ポイントをホストするように構成するconfigure-internet-information-services-to-host-crl-distribution-point" class="heading-anchor">
...
```

This time, the `id` field seems to have *both* the translation and the original, while the relevant link still points to the link with the original hash ID.

cc @TinaMcN

**Comment by e0i** [comment]
See: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3459#issuecomment-654912262
Similar to the comment above, the `id` field seems to have both the translation and the original, while the relevant link still points to the link with the original hash ID.

cc @TinaMcN

**Comment by illfated** [comment]
@hyoshioka0128 : May I ask you to check the page links again, to see if any improvements can be found there?
- https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base

Thanks in advance for any feedback. 🙂

**Comment by e0i** [comment]
It seems like the link in question has been fixed and it’s title has been changed as well. Thanks.
