### ISSUE TITLE
[LOC] " 年 11 月 2018" needs to be replaced with "2018 年 11 月" 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3464]
https://docs.microsoft.com/ja-jp/hololens/change-history-hololens

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6c020076-03b6-4f41-0494-22c4a6cc07c7
* Version Independent ID: 43c53ffe-4849-47e9-4dab-60c036fe5547
* Content: [Microsoft HoloLens ドキュメントの変更履歴](https://docs.microsoft.com/ja-jp/hololens/change-history-hololens)
* Content Source: [devices/hololens/change-history-hololens.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/hololens/change-history-hololens.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@dongmicro Could you assist in resolving this localization issue? Thank you.

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by hyoshioka0128** [comment]
Fixed.
Closed #3464
