### ISSUE TITLE
How to set null

### ISSUE THREAD

**Issue by Niglb** [MicrosoftDocs/windows-itpro-docs#3471]
For ./Vendor/MSFT/Reboot/Schedule/DailyRecurrent – if I wanted to clear the schedule, the documentation states to set it empty / null. How can I do this in the InTune custom policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a473300-e8f4-8c49-5ac7-d81956f55adf
* Version Independent ID: 7db8e493-d48b-bee9-61af-de601cfc8216
* Content: [Reboot CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/reboot-csp)
* Content Source: [windows/client-management/mdm/reboot-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/reboot-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by illfated** [comment]
The page content reads as follows:
> **Schedule/Single**
>
> This node will execute a reboot at a scheduled date and time. Setting a null (empty) date will delete the existing schedule. The date and time value is ISO8601, and both the date and time are required. 
> Example to configure: 2018-10-25T18:00:00
>
> The supported operations are Get, Add, Replace, and Delete.
>
> **Schedule/DailyRecurrent**
>
> This node will execute a reboot each day at a scheduled time starting at the configured starting time and date. Setting a null (empty) date will delete the existing schedule. The date and time value is ISO8601, and both the date and time are required. The CSP will return the date time in the following format: 2018-06-29T10:00:00+01:00. 
Example to configure: 2018-10-25T18:00:00
>
> The supported operations are Get, Add, Replace, and Delete.

Based on what I can read here (I don't have access to Enterprise Device Management), I presume that the required format dictates the following empty date & time input:

0000-00-00T00:00:00+00:00

Furthermore, if the date & time field is a text string, I would check if it is possible to remove all of it, leaving it completely empty, to see if that is a valid method. Then again, I don't have the required scenario available for testing.

**Comment by illfated** [comment]
BTW, I am fairly certain that 2x NewLine (or CarriageReturn/LineFeed pairs) is missing from the following section:
> The supported operations are Execute and Get. **Schedule**
>
> The supported operation is Get.

I will take a closer look at the Github source page and see if I can sort out why it looks OK on Github, but not on the docs.microsoft.com page.

**Comment by e0i** [comment]
Hello, @Niglb 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot close

**Comment by Niglb** [comment]
Thank you everyone! I will test '0000-00-00T00:00:00+00:00' as the InTune configuration does not allow for an empty String.
