### ISSUE TITLE
Deployment steps | future

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#3475]
Hello,
Are there any plans to optimize this solution and replace/remove script deployment?
Else it looks like we do step back, while we try drive only forward using new solutions from MS products.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f029a728-1f53-4576-a6ca-8a19a92626e6
* Version Independent ID: 85f27ad5-84e2-0787-082f-59d2d66c99b5
* Content: [Upgrade Readiness deployment script (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-deployment-script)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-deployment-script.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-deployment-script.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by jaimeo** [comment]
@zdvorak for comment

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@zdvorak Any updates on this?
