### ISSUE TITLE
tdlrecover.exe - Windows 10.0.18362.XXX - TileDataLayer is deprecated

### ISSUE THREAD

**Issue by NeoBeum** [MicrosoftDocs/windows-itpro-docs#3478]
tdlrecover.exe is not present in 1903

https://support.microsoft.com/en-us/help/4014193/features-that-are-removed-or-deprecated-in-windows-10-creators-update

Also the following -- needs to get forwarded to the Extensible Storage Engine Team
```

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="ESENT" /> 
  <EventID Qualifiers="0">455</EventID> 
  <Level>2</Level> 
  <Task>3</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2019-05-03T05:19:29.754223300Z" /> 
  <EventRecordID>2509</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>NB-G751JY</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>svchost</Data> 
  <Data>4628,R,98</Data> 
  <Data>TILEREPOSITORYS-1-5-18:</Data> 
  <Data>C:\WINDOWS\system32\config\systemprofile\AppData\Local\TileDataLayer\Database\EDB.log</Data> 
  <Data>-1023 (0xfffffc01)</Data> 
  </EventData>
  </Event>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00912925-8922-8c5e-fc36-d00fb992114c
* Version Independent ID: 1dd2bc12-d31b-dcd8-a2fb-c279adfa81a5
* Content: [Troubleshoot Start menu errors](https://docs.microsoft.com/en-us/windows/configuration/start-layout-troubleshoot)
* Content Source: [windows/configuration/start-layout-troubleshoot.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/start-layout-troubleshoot.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **kaushika**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@NeoBeum - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by NeoBeum** [comment]
@mypil 

no problem.

I'm trying to get as much information as possible, as I've had issues since 2015 with installations, so I'm trying to get all correct api, sdk references correct so the current pending releases have up to date information available to public, as all msdn, techbench and partners documents all end up linking docs.microsoft.com

**Comment by MaratMussabekov** [comment]
Dear @NeoBeum ,
**tdlrecover.exe is not present in 1903** - yes, it was deprecated in 1703. However, I think that the article shouldn't be updated, since part "Windows 10, version 1507 through the release of version 1607 uses a database for the Tile image information. This is called the Tile Data Layer database." makes clear that this issue could be faced only by users of Windows 10 prior to 1703.
What do you think?

**about the error,**  it could be avoided by going to C:\Windows\System32\config\systemprofile\AppData\Local, and creation of TileDataLayer directory, and then Database directory (so the path becomes existing).
It looks like preview version bug, dear @mypil, as it was recommended by NeoBeum, could it be reported to ESE team?

thank you

**Comment by NeoBeum** [comment]
@MaratMussabekov 

it just needs to be highlighted that it had been deprecated, however executable is not present in 1903.
keeping the information there is good, as previous builds are still currently supported.

**Comment by NeoBeum** [comment]
@MaratMussabekov 
Creating the TileDataLayer directory does clear the error, however could cause some artifact for cleaning if TrustedInstaller or System doesn't own it during servicing stack updates

**Comment by mypil** [comment]
@NeoBeum - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
