### ISSUE TITLE
[LOC] "HKEY_ローカル_MACHINE" needs to be replaced with "HKEY_LOCAL_MACHINE"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3481]
https://docs.microsoft.com/ja-jp/windows/configuration/kiosk-single-app

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f8f49c3f-ba5c-49e9-fad2-88cac155920a
* Version Independent ID: dc5e1f7e-61a8-bf2c-34b8-4046d024f4c2
* Content: [シングル アプリ キオスク (Windows 10) の設定します。](https://docs.microsoft.com/ja-jp/windows/configuration/kiosk-single-app)
* Content Source: [windows/configuration/kiosk-single-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-single-app.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@dongmicro It looks like the translation software has interpreted the word _local_ within the keyword as a proper noun.

Would you review and follow-up with this generalized issue?

Thanks.

**Comment by e0i** [comment]
See: #3481

**Comment by e0i** [comment]
@hyoshioka0128 It has been officially confirmed that this issue, and the referenced issues have now been fixed.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
