### ISSUE TITLE
Purpose of Key Admins group

### ISSUE THREAD

**Issue by revikor** [MicrosoftDocs/windows-itpro-docs#3493]
Looking at the previous doc here: https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-dir-sync - it seems like important aspect got left out - such as not needing to do this step at all if you already have a 2016 DC which is a prerequisite for this deployment. For example my MSOL_ that runs ADConnect already had the necessary permissions. This seems like an obsolete step at this point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdb237b7-6181-5638-8e9a-fa52fe5327d5
* Version Independent ID: 27b14b20-65f1-302a-cd74-3c1443d8a863
* Content: [Configuring Hybrid key trust Windows Hello for Business - Directory Synchronization](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-dir-sync#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-dir-sync.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-dir-sync.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@revikor 

The issue is being routed to Windows IT Pro writing team for investigation. You'll be notified with relevant updates as content gets updated.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by j0rt3g4** [comment]
Solving this Issue on PR #3757

**Comment by j0rt3g4** [comment]
@e0i Can you follow up this one?

**Comment by e0i** [comment]
@revikor 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
