### ISSUE TITLE
Missing network connectivity requirements

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/windows-itpro-docs#3499]
Defender is a cloud service and requires network connectivity to function. Please include and make clear it needs computer-level (not user-level) proxy access to its backend services and what those are.

https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/minimum-requirements-windows-defender-advanced-threat-protection#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-atp/minimum-requirements-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/minimum-requirements-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by SwiftOnSecurity** [comment]
I know I opened this topic before, but this result comes up prominently when you search for "defender requirements."
Please add a note to this page that network connection is needed and where to get more information.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @SwiftOnSecurity 

The issue is under investigation and you'll be notified with changes as the document goes through review and updates.

Thank you for providing feedback and following-up with clarification.

**Comment by e0i** [comment]
@SwiftOnSecurity 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published.

Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
