### ISSUE TITLE
Dangerous ambiguity 

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/windows-itpro-docs#3500]
Windows Defender requires network connectivity for proper operation, but it does not require unfiltered internet access.

This URL: "*.blob.core.windows.net" should NOT be excluded from ANY kind of network inspection, as it's usable to host arbitrary files by customers. If customers whitelist this, they will potentially allow malware binaries into their network through their inspecting proxies and firewalls.

Please clarify this text very prominently to say that inspection for *.blob.core.windows.net should NOT be turned off.

"The following table lists the services and their associated URLs that your network must be able to connect to. You should ensure there are no firewall or network filtering rules that would deny access to these URLs, or you may need to create an allow rule specifically for them:"

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86b0db3-f979-bd1f-78a4-41247510721a
* Version Independent ID: 5289bb5f-f015-7f38-05a1-26a615ae07aa
* Content: [Configure and validate Windows Defender Antivirus network connections](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Similar to: #3499

**Comment by e0i** [comment]
@Justinha Would you be able to offer immediate resolution for this potentially dangerous error in the article? Thanks.

**Comment by Justinha** [comment]
@e0i I've shared with engineering for their input. Please stay tuned.

**Comment by e0i** [comment]
@Justinha Any updates from the engineering?

**Comment by e0i** [comment]
@SwiftOnSecurity 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published.

Thank you for your taking the time to provide feedback. Much appreciated.

**Comment by e0i** [comment]
@officedocsbot close
