### ISSUE TITLE
[LOC] "HKEY_ローカル_MACHINE" needs to be replaced with "HKEY_LOCAL_MACHINE"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3501]
https://docs.microsoft.com/ja-jp/windows/configuration/kiosk-prepare

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5cd1e023-65ae-0e1d-b031-c02f5fb1daf8
* Version Independent ID: 8053b30a-82b6-404e-5daa-2110fb56c20b
* Content: [キオスク構成 (Windows 10) のためのデバイスを準備します。](https://docs.microsoft.com/ja-jp/windows/configuration/kiosk-prepare)
* Content Source: [windows/configuration/kiosk-prepare.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-prepare.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@dongmicro It looks like the translation software has interpreted the keyword, "local" within the registry path as a literal common word. Please review. Thanks.

**Comment by e0i** [comment]
See: #3481

**Comment by e0i** [comment]
@officedocsbot close
