### ISSUE TITLE
Differences

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#3504]
Two things:
- Can you clarify (or refer to page that does this) what the differences are between "BitLocker Device Encryption" aka "Device Encryption" and "standard BitLocker encryption"? My impression is that it is a simplified version without options. Is that correct? Would it be correct to think of them as standard BitLocker and advanced BitLocker?
- You say that the OOBE transparent device encryption is equivalent to the standard BitLocker suspend state. With suspend, the command to encrypt is Resume-BitLocker. What is the command to trigger device encryption with key protectors for a device that has not done it, and is still in a transparent encryption state? Is it Resume-BitLocker; or Enable-BitLocker, or something else? I know it is supposed to be automatic, but sometimes it fails. If it fails, is there any "try again" command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29116f85-264f-d031-be7b-e32a1816cd28
* Version Independent ID: 640478e6-a367-4e47-a177-3a10dd006d1c
* Content: [Overview of BitLocker Device Encryption in Windows 10](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by lindspea** [comment]
@Air-Git Thank you for reaching out and helping improve MS Docs.  I'll have the team look into this and revert soonest.

**Comment by e0i** [comment]
@Air-Git 

We are closing this issue as there hasn't been a response from your side regarding the issue.

Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by Air-Git** [comment]
Sorry, I missed the previous response.
No, the link does not answer the questions.  I raise the questions, not to ask how BitLocker works, but because the documentation is not clear on these point. 
To restate:
1) "Device Encryption" is a term that refers to something distinct from "BitLocker Encryption". What is the distinction? I think I know, but I don't see any documentation for it.
2) Transparent encryption is the state of a device after OOBE, equivalent to Suspended. If that is the case, then is "Resume" the correct command to move from Transparent to full (protected) encryption? I suspect it is not. In which case it is not "Equivalent". It may be "similar" or "analogous" but not equivalent.
I am requesting that the terms are clarified,

**Comment by illfated** [comment]
@lindspea - could we have a comment from you on this response from the issue author?

**Comment by lindspea** [comment]
@Air-Git thank you for clarifying.  I'm investigating with the team and will revert soonest.

**Comment by e0i** [comment]
@officedocsbot reopen

**Comment by biren1234** [comment]
is there any issue with Lenovo Laptop 
we buy some lenovo laptop and someone said with Lonovo laptop bitlocker encryption by default enabled
now what happend when we joined system in domain our bitlocker key lost and system locked

**Comment by lindspea** [comment]
@biren1234 After some research it seems there are issues with Lenovo. I did some research and a possible solution could be to run recovery media after your devices battery has been drained.

**Comment by e0i** [comment]
The issue is still under investigation.

**Comment by Van-Fouran** [comment]
This issue has also been verified in the Microsoft TechNet Forum: https://social.technet.microsoft.com/Forums/en-US/536b1613-22e6-4190-9b9a-d159b536146d/bitlocker-device-encryption-vs-device-encryption?forum=win10itprosecurity

**Comment by Van-Fouran** [comment]
I created a change suggestion for Microsoft in this case. I furthermore made a few suggestions on how to make clearer what the device encryption does. I would appreciate feedback.

https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4913

**Comment by Van-Fouran** [comment]
A new pull request regarding this topic is available: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/6244
I would appreciate feedback.
