### ISSUE TITLE
Where's the What's New in Windows 10 1903 page? Seems desperately missing 

### ISSUE THREAD

**Issue by no-identd** [MicrosoftDocs/windows-itpro-docs#3505]
[no seriously, does this need any explanation besides the title?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b010f23d-6d7e-8ab0-8a16-0ddbbacc0528
* Version Independent ID: 929b988a-e7e4-b8b0-2a85-756c69085063
* Content: [What's new in Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/whats-new/index#feedback)
* Content Source: [windows/whats-new/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/index.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @TrudyHa
* Microsoft Alias: **trudyha**

**Comment by illfated** [comment]
The documentation will likely be made available when 1903 (19H1) is released.
The May 2019 Update is expected to be released at the end of May.
So far, only Preview builds have been made available, for testing.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@no-identd - Thank you for submitting feedback.

From our understanding, the issue has been answered by illfated. If you feel it hasn't been answered please re-open this issue.

Thank you for engaging with the community here for the docs.
