### ISSUE TITLE
Possible doc bug regarding feature capability on Wildcards

### ISSUE THREAD

**Issue by amirsc3** [MicrosoftDocs/windows-itpro-docs#3509]
The below statement seems incorrect based on input from MDATP devs...
"You can use wild cards so that all files under the directory is skipped by the automated investigation. "

From: 
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/manage-automation-folder-exclusions-windows-defender-advanced-threat-protection

I was told wildcards are unsupported in the context of automated investigation exclusions...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 832f2751-9e80-2d78-685a-d984bc66003c
* Version Independent ID: 32793f0f-87f3-c3ea-a327-3f62de523f0b
* Content: [Manage automation folder exclusions](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/manage-automation-folder-exclusions-windows-defender-advanced-threat-protection#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-atp/manage-automation-folder-exclusions-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/manage-automation-folder-exclusions-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by lindspea** [comment]
@amirsc3 Thank you for reaching out.  I'll look into this with the team and revert soonest.

**Comment by lindspea** [comment]
@amirsc3 Wild cards can be used, but there are some limitations as mentioned here: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-extension-file-exclusions-windows-defender-antivirus

**Comment by amirsc3** [comment]
@lindspea > the doc you shared is regarding Windows Defender AV itself.
The doc I mentioned which needs correcting is regarding "Microsoft Defender Advanced Threat Protection" - a different product which was told does not support wildcard at this time.
The doc below needs to be fixed:
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/manage-automation-folder-exclusions

**Comment by lindspea** [comment]
@amirsc3 Would it help if I added an important note to the article with this link about wild cards? https://docs.microsoft.com/windows/security/threat-protection/windows-defender-antivirus/configure-extension-file-exclusions-windows-defender-antivirus#use-wildcards-in-the-file-name-and-folder-path-or-extension-exclusion-lists

**Comment by amirsc3** [comment]
@lindspea > sorry but that would not help. The article you mention already has the note below:
"Windows Defender Advanced Threat Protection  does not adhere to Windows Defender Antivirus exclusion settings. This means that any Windows Defender exclusions, no matter how you created them, are not applied by Windows Defender ATP."
From: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-extension-file-exclusions-windows-defender-antivirus#use-wildcards-in-the-file-name-and-folder-path-or-extension-exclusion-lists

What is needed is to fix the Defender ATP article below:
"You can use wild cards so that all files under the directory is skipped by the automated investigation."
From: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/manage-automation-folder-exclusions

**Comment by lindspea** [comment]
@amirsc3 Okay, thank you, I understand now.  Perhaps I should remove that sentence about wild cards?

**Comment by amirsc3** [comment]
Removing the above text might work, but perhaps a mention that it is not (yet?) supported is better to avoid customer confusion.

**Comment by e0i** [comment]
@amirsc3 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
