### ISSUE TITLE
MDM_AssignedAccess | MultiAppKiosk

### ISSUE THREAD

**Issue by go4matthias** [MicrosoftDocs/windows-itpro-docs#351]
Hi,

refering to the following article
https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps

When running the Powershell script, I'm missing the "configuration" of Namespace "MDM_AssignedAccess" even in Window10 Version 1709

Test (Get-CimClass -Namespace "MDM_AssignedAccess") reflect just the propertiess   {InstanceID, KioskModeApp, ParentID}    

Tested with several devices, but no "configuration" for AssingedAccess

Please have a look at

Regards
Matthias

**Comment by jdatms** [comment]
Hi Matthias,

Which script isn't working for you? I'm not a PowerShell expert so I'll have to pass this on to our product team for assistance, but none of the PowerShell examples in the topic use Get-CimClass so I'm not sure which one has the problem.

thanks,
Jeanie

**Comment by go4matthias** [comment]
Hi Jeanie,

we wanna configure an Windows10 MultiApp Kiosk, as described in the URLs below.

https://docs.microsoft.com/en-us/windows/configuration/multi-app-kiosk-xml
https://docs.microsoft.com/en-us/windows/client-management/mdm/assignedaccess-csp

Single App Kiosk is working with AssignedAccess, but can not configure new varable «configuration»


[cid:image001.png@01D36D0B.7FE4DF50]
Please assist with
Matthias

Von: jdatms<mailto:notifications@github.com>
Gesendet: Donnerstag, 30. November 2017 16:46
An: MicrosoftDocs/windows-itpro-docs<mailto:windows-itpro-docs@noreply.github.com>
Cc: Matthias Mader<mailto:Matthias.Mader@go4mobile.ch>; Author<mailto:author@noreply.github.com>
Betreff: Re: [MicrosoftDocs/windows-itpro-docs] MDM_AssignedAccess | MultiAppKiosk (#351)


Hi Matthias,

Which script isn't working for you? I'm not a PowerShell expert so I'll have to pass this on to our product team for assistance, but none of the PowerShell examples in the topic use Get-CimClass so I'm not sure which one has the problem.

thanks,
Jeanie

**Comment by jdatms** [comment]
Hi Matthias, it looks like you included a screenshot ([cid:image001.png@01D36D0B.7FE4DF50]) but it didn't come through. Could you paste the script that you're trying to run?

**Comment by go4matthias** [comment]
Hi,

want to run the script from this side, referred to the picture with"configuration"

https://docs.microsoft.com/en-us/windows/client-management/mdm/assignedaccess-csp

When running an WMI explorer, can not find the property "configuration"

Beste Grüße
Matthias Mader

-------- Originalnachricht --------
Betreff: Re: [MicrosoftDocs/windows-itpro-docs] MDM_AssignedAccess | MultiAppKiosk (#351)
Von: jdatms
An: MicrosoftDocs/windows-itpro-docs
Cc: Matthias Mader ,Author


Hi Matthias, it looks like you included a screenshot ([cid:image001.png@01D36D0B.7FE4DF50]) but it didn't come through. Could you paste the script that you're trying to run?

**Comment by jdatms** [comment]
Hi Matthias,

There are several scripts in that topic. Please paste the script that you are using here. Thanks.

**Comment by go4matthias** [comment]
Hello,

we want to configure ./Device/Vendor/MSFT/AssignedAccess/Configuration

when searching in WMI Explorer, the property is not displayed even with Windows 10 Version 1709

Thats why the code attached fails

===========CODE===============
<?xml version="1.0" encoding="utf-8" ?>
<AssignedAccessConfiguration xmlns="http://schemas.microsoft.com/AssignedAccess/2017/config">
  <Profiles>
    <Profile Id="{9A2A490F-10F6-4764-974A-43B19E722C23}">
      <AllAppsList>
        <AllowedApps>
          <App AppUserModelId="Microsoft.ZuneMusic_8wekyb3d8bbwe!Microsoft.ZuneMusic" />
          <App AppUserModelId="Microsoft.ZuneVideo_8wekyb3d8bbwe!Microsoft.ZuneVideo" />
          <App AppUserModelId="Microsoft.Windows.Photos_8wekyb3d8bbwe!App" />
          <App AppUserModelId="Microsoft.BingWeather_8wekyb3d8bbwe!App" />
          <App AppUserModelId="Microsoft.WindowsCalculator_8wekyb3d8bbwe!App" />
          <App DesktopAppPath="%windir%\system32\mspaint.exe" />
          <App DesktopAppPath="C:\Windows\System32\notepad.exe" />
        </AllowedApps>
      </AllAppsList>
      <StartLayout>
        <![CDATA[<LayoutModificationTemplate xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout" xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout" Version="1" xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification">
                      <LayoutOptions StartTileGroupCellWidth="6" />
                      <DefaultLayoutOverride>
                        <StartLayoutCollection>
                          <defaultlayout:StartLayout GroupCellWidth="6">
                            <start:Group Name="Group1">
                              <start:Tile Size="4x4" Column="0" Row="0" AppUserModelID="Microsoft.ZuneMusic_8wekyb3d8bbwe!Microsoft.ZuneMusic" />
                              <start:Tile Size="2x2" Column="4" Row="2" AppUserModelID="Microsoft.ZuneVideo_8wekyb3d8bbwe!Microsoft.ZuneVideo" />
                              <start:Tile Size="2x2" Column="4" Row="0" AppUserModelID="Microsoft.Windows.Photos_8wekyb3d8bbwe!App" />
                              <start:Tile Size="2x2" Column="4" Row="4" AppUserModelID="Microsoft.BingWeather_8wekyb3d8bbwe!App" />
                              <start:Tile Size="4x2" Column="0" Row="4" AppUserModelID="Microsoft.WindowsCalculator_8wekyb3d8bbwe!App" />
                            </start:Group>
                            <start:Group Name="Group2">
                              <start:DesktopApplicationTile Size="2x2" Column="2" Row="0" DesktopApplicationID="{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\mspaint.exe" />
                              <start:DesktopApplicationTile Size="2x2" Column="0" Row="0" DesktopApplicationID="{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\notepad.exe" />
                            </start:Group>
                          </defaultlayout:StartLayout>
                        </StartLayoutCollection>
                      </DefaultLayoutOverride>
                    </LayoutModificationTemplate>
                ]]>
      </StartLayout>
      <Taskbar ShowTaskbar="true"/>
    </Profile>
  </Profiles>
  <Configs>
    <Config>
      <Account>MultiAppKioskUser</Account>
      <DefaultProfile Id="{9A2A490F-10F6-4764-974A-43B19E722C23}"/>
    </Config>
  </Configs>
</AssignedAccessConfiguration>
===============CODE===============

Beste Regads
Matthias

Von: jdatms [mailto:notifications@github.com]
Gesendet: Donnerstag, 7. Dezember 2017 18:22
An: MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>
Cc: Matthias Mader <Matthias.Mader@go4mobile.ch>; Author <author@noreply.github.com>
Betreff: Re: [MicrosoftDocs/windows-itpro-docs] MDM_AssignedAccess | MultiAppKiosk (#351)


Hi Matthias,

There are several scripts in that topic. Please paste the script that you are using here. Thanks.

**Comment by jdatms** [comment]
Thanks, Matthias, the engineering team is looking into this. It may take some time before I have an answer for you.

**Comment by go4matthias** [comment]
Hi,

is there any way to assit,
or may I talk to an engenner/devloper.

Thanks in advance
Matthias

Video: Unterwegs einfach und sicher auf Firmendokumente zugreifen<http://bit.ly/2A4Maa6>

[Beschreibung: Mailfuss_Reto_neu]

                     Matthias Mader

                     Senior Mobile Consultant
                     Stauffacherstrasse 72
                     3014 Bern
                     Tel.  +41 31 914 18 18<tel:+41319141818>
                     Fax. +41 31 914 18 19<+41%2031%20914%2018%2019>
                     Mail matthias.mader@go4mobile.ch<mailto:matthias.mader@go4mobile.ch>
                     Web www.go4mobile.ch



Von: jdatms [mailto:notifications@github.com]
Gesendet: Dienstag, 12. Dezember 2017 22:22
An: MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>
Cc: Matthias Mader <Matthias.Mader@go4mobile.ch>; Author <author@noreply.github.com>
Betreff: Re: [MicrosoftDocs/windows-itpro-docs] MDM_AssignedAccess | MultiAppKiosk (#351)


Thanks, Matthias, the engineering team is looking into this. It may take some time before I have an answer for you.

**Comment by go4matthias** [comment]
Hello,

best wishes for 2018.

Are there any news about MDM_AssignedAccess

Best Regards
Matthias

Video: Unterwegs einfach und sicher auf Firmendokumente zugreifen<http://bit.ly/2A4Maa6>

[Beschreibung: Mailfuss_Reto_neu]

                     Matthias Mader

                     Senior Mobile Consultant
                     Stauffacherstrasse 72
                     3014 Bern
                     Tel.  +41 31 914 18 18<tel:+41319141818>
                     Fax. +41 31 914 18 19<+41%2031%20914%2018%2019>
                     Mail matthias.mader@go4mobile.ch<mailto:matthias.mader@go4mobile.ch>
                     Web www.go4mobile.ch



Von: jdatms [mailto:notifications@github.com]
Gesendet: Dienstag, 12. Dezember 2017 22:22
An: MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>
Cc: Matthias Mader <Matthias.Mader@go4mobile.ch>; Author <author@noreply.github.com>
Betreff: Re: [MicrosoftDocs/windows-itpro-docs] MDM_AssignedAccess | MultiAppKiosk (#351)


Thanks, Matthias, the engineering team is looking into this. It may take some time before I have an answer for you.

**Comment by go4matthias** [comment]
Hi,

could you provide some update about this feature,
otherwise please forward to a responsible contact.

Regards
Matthias

Von: Matthias Mader
Gesendet: Mittwoch, 6. Dezember 2017 13:35
An: MicrosoftDocs/windows-itpro-docs <reply@reply.github.com>
Betreff: AW:[MicrosoftDocs/windows-itpro-docs] MDM_AssignedAccess | MultiAppKiosk (#351)

Hi,

want to run the script from this side, referred to the picture with"configuration"

https://docs.microsoft.com/en-us/windows/client-management/mdm/assignedaccess-csp

When running an WMI explorer, can not find the property "configuration"

Beste Grüße
Matthias Mader

-------- Originalnachricht --------
Betreff: Re: [MicrosoftDocs/windows-itpro-docs] MDM_AssignedAccess | MultiAppKiosk (#351)
Von: jdatms
An: MicrosoftDocs/windows-itpro-docs
Cc: Matthias Mader ,Author

Hi Matthias, it looks like you included a screenshot ([cid:image001.png@01D36D0B.7FE4DF50]) but it didn't come through. Could you paste the script that you're trying to run?

-

**Comment by jdeckerms** [comment]
That's your version -- could you check the build number ("OS Build")?

**Comment by go4matthias** [comment]
I'm available to check a my client in a websession, maybe language related (swiss german)

Regards
Besten Gruß
Matthias Mader

-------- Originalnachricht --------
Betreff: Re: [MicrosoftDocs/windows-itpro-docs] MDM_AssignedAccess | MultiAppKiosk (#351)
Von: Jeanie Decker
An: MicrosoftDocs/windows-itpro-docs
Cc: Matthias Mader ,Author


They have not been able to replicate this, so they want the build number as data to help them investigate.

**Comment by jagadishmurugan** [comment]
Mathias,
This is the dev working on the issue. I was not able to replicate the issue on 1709 (i always see the Configuration node). Could you provide additional details about your system?
=> Is it a fresh install of 1709? or an upgrade from a previous OS? In case of upgrade, can you please provide the base version? I will follow up over email...

Thanks,
Jagadish

**Comment by go4matthias** [comment]
Hi,

checked all windows in our office, no configuration, your available to check this remote tomorrow 9am CET?

regards
Matthias

Send from GMail, secured with Android Enterprise

Am 30.01.2018 22:16 schrieb Jagadish Murugan <notifications@github.com>:

Mathias,
This is the dev working on the issue. I was not able to replicate the issue on 1709 (i always see the Configuration node). Could you provide additional details about your system?
=> Is it a fresh install of 1709? or an upgrade from a previous OS? In case of upgrade, can you please provide the base version? I will follow up over email...

Thanks,
Jagadish

**Comment by jagadishmurugan** [comment]
Mathias,
I have a solid repro (update from 1703 to 1709) of the issue (no need to remote debug). Will get back as soon as i have some update on the issue. 

Regards,
Jagadish

**Comment by go4matthias** [comment]
Ah, probably that we all updated
Good that you could find it, looking forward to test the feature.
Thanks for your effort

Besten Gruß
Matthias Mader

-------- Originalnachricht --------
Betreff: Re: [MicrosoftDocs/windows-itpro-docs] MDM_AssignedAccess | MultiAppKiosk (#351)
Von: Jagadish Murugan
An: MicrosoftDocs/windows-itpro-docs
Cc: Matthias Mader ,Author


Mathias,
I have a solid repro (update from 1703 to 1709) of the issue (no need to remote debug). Will get back as soon as i have some update on the issue.

Regards,
Jagadish

**Comment by jagadishmurugan** [comment]
Mathias,
Can you try the following workaround and see if it fixes the issue:
In admini prompt, 
1) cd c:\windows\system32\wbem
2) mofcomp.exe DMWMIBridgeProv.mof

Thanks,
Jagadish

**Comment by go4matthias** [comment]
HI,

that seams to be worked so far.
[cid:image002.jpg@01D39F17.22D401E0]

Is there a easy way to list the CSP Features, check if it worked - btw test the kiosk config locally ?

Thanks in advance
Matthias

Von: Jagadish Murugan [mailto:notifications@github.com]
Gesendet: Freitag, 2. Februar 2018 00:53
An: MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>
Cc: Matthias Mader <Matthias.Mader@go4mobile.ch>; Author <author@noreply.github.com>
Betreff: Re: [MicrosoftDocs/windows-itpro-docs] MDM_AssignedAccess | MultiAppKiosk (#351)


Mathias,
Can you try the following workaround and see if it fixes the issue:
In admini prompt,

  1.  cd c:\windows\system32\wbem
  2.  mofcomp.exe DMWMIBridgeProv.mof

Thanks,
Jagadish

-

**Comment by jagadishmurugan** [comment]
Hi Mathias,
Not sure I understand your request. Here's an attempt:
=> You can query/apply the AssignedAccess CSP features using:
        1) WMIBridge
        2) Deploy through MDM server (not sure you have this setup. if you already have this might be easier since u don't need to care about launching psexec..).
=> To test it, after applying the config, login as MultiAppKioskUser (or the user account you have used) and check the following:
        1) TABLET mode is enabled for the account
        2) START menu has only the apps configured in StartLayout section in syncml
        3) Can run only those apps that are in the MultiAppKioskUser  profile allowed apps list 

Please let me know if you have further questions.

Thanks,
Jagadish

**Comment by andreabichsel** [comment]
Is it ok to mark this issue as closed?

**Comment by jdeckerms** [comment]
Yes, let's close it.
