### ISSUE TITLE
Problem with Windows defender if you do this

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#3520]
You can do this in Intune but, in my testing, it will block Windows Defender Definition updates, and it will cause a regular prompt to restart the device (with a prompt but no reason given).
If that is correct, you probably do not want to use this setting in isolation from other WDAC policies. And, since you can implement this in a WDAC policy also, it is hard to see a reason for implementing it in Intune.
Happy to be corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80b64219-4814-f414-e5fb-4bfa9be9a55f
* Version Independent ID: b1b2f9e2-912b-80e0-bee7-be41eaf9690f
* Content: [Deploy Windows Defender Application Control (WDAC) policies by using Microsoft Intune (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/deploy-windows-defender-application-control-policies-using-intune)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/deploy-windows-defender-application-control-policies-using-intune.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/deploy-windows-defender-application-control-policies-using-intune.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @Air-Git 

Would you be able to clarify what needs to be updated in the documentation? Is the document misleading?

We would like to follow-up with content updates accordingly.

Thank you for providing this thoughtful feedback.

**Comment by Air-Git** [comment]
I think what is not clear is the impact of implementing this policy. The implication (and documentation) is that you can implement this policy and the computer will function with a) all Windows services, b) all Microsoft Store apps, and c) all apps of good reputation (through ISG). In my testing, Windows Defender definition updates were blocked., so this would be unusable. I am happy to be corrected if that is wrong.

**Comment by e0i** [comment]
@Air-Git Thank you again for following-up with clarification.

The issue has been noted and the document will be revised in the light of your feedback.

**Comment by lindspea** [comment]
@Air-Git Thank you once again for helping improve MS Docs.  As per issue #3518, I'll investigate this as well.  If there is anything you could suggest that could be added to the article in the meantime, please let me know.

**Comment by lindspea** [comment]
@Air-Git please see new information regarding enhancements to WDAC. Let me know if it helps in any way. https://www.microsoft.com/security/blog/2019/07/01/delivering-major-enhancements-in-windows-defender-application-control-with-the-windows-10-may-2019-update/

**Comment by Air-Git** [comment]
The new Path rule is great. It makes it much more practical to implement a WDAC policy.

**Comment by e0i** [comment]
@Air-Git 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
