### ISSUE TITLE
Typo under 'Connection through the WinHTTP proxy' heading

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#3523]
Typo at the end of this sentence under the **Connection through the WinHTTP proxy** heading: 

> The WinHTTP scenario is most appropriate for customers who use a single proxy or f.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f58247e6-b6a8-e172-941d-b18ee3753a55
* Version Independent ID: b05fe5e8-3490-219a-d0dd-cdbd4c387886
* Content: [Upgrade Readiness data sharing](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-data-sharing)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-data-sharing.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-data-sharing.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@jaimeo Would you be able to review this PR that fixes a minor typo? Thanks.
