### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/windows-itpro-docs#3538]
This section is confusing ... the If and Otherwise sections don't blend together in a paragraph.  If you use AD Connect and sync (usernames only,) and have ADFS on Prem, which you redirect users to can you still use Azure MFA Cloud Service?  Or do we have to use the MFA Adapter?

If your Azure AD Connect is configured to synchronize identities (usernames only), then your users are redirected to your local on-premises federation server for authentication and then redirected back to the Azure MFA cloud service. Otherwise, your Azure AD Connect is configured to synchronize credentials (username and passwords), which enables your users to authenticate to Azure Active Directory and use the Azure MFA cloud service. If you choose to use the Azure MFA cloud service directly, write Azure MFA in box 1f on your planning worksheet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5739fab2-c6db-a7a9-b0e7-2bf4b85912a7
* Version Independent ID: 82c58053-c1d7-d938-1b0f-f3f7f70ada3b
* Content: [Planning a Windows Hello for Business Deployment](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-planning-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-planning-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by SquirrelAssassin** [comment]
maybe better fill in the blank ...

If your Azure AD Connect is configured to synchronize identities (usernames only), then your users are redirected to your local on-premises federation server for authentication and then redirected back to the Azure MFA cloud service <can I use Azure MFA cloud service directly?>

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Thank you for providing feedback, @SquirrelAssassin 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Have a nice day.

**Comment by e0i** [comment]
@SquirrelAssassin A PR will be delivered to address this issue within a few days. Thanks.

**Comment by VLG17** [comment]
@SquirrelAssassin There are 3 possible scenarios:

1. You have AD connect and sync identities only (no credentials) to Azure + ADFS - in this case your users authenticate against your on-premises ADFS and then once authenticated they can take advantage of the Azure MFA Cloud Service -> here you would use either **ADFS with Azure MFA cloud adapter** or **ADFS with Azure MFA server adapter** to establish a channel between your ADFS and Azure MFA Cloud Service. 

2. You have AD Connect and sync usernames and credentials to Azure, meaning users will authenticate directly agains Azure Active Directory, hence will be able to use Azure MFA Cloud Service directly (**Azure MFA**)

3. ADFS with third party -> which i don't think interests you at the moment

**Comment by e0i** [comment]
Hello @SquirrelAssassin,

We are closing this issue since your support question seems to be answered. Feel free to re-open this issue if you still feel it hasn't been answered or that there are further suggestions to the documentation itself.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
