### ISSUE TITLE
Spelling Typo

### ISSUE THREAD

**Issue by roninator2** [MicrosoftDocs/windows-itpro-docs#3539]
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/volume-activation/activate-using-key-management-service-vamt.md

At the bottom.
Number 4 has in it slmrg.vbs
it should be slmgr.vbs

**Comment by illfated** [comment]
A.K.A. the Docs page https://docs.microsoft.com/en-us/windows/deployment/volume-activation/activate-using-key-management-service-vamt

**Comment by e0i** [comment]
@officedocsbot assign @e0i
