### ISSUE TITLE
Marks Missing Within CSP Support Section

### ISSUE THREAD

**Issue by SEYiWeng** [MicrosoftDocs/windows-itpro-docs#3540]
Hello there, I was spending time reviewing this page, and I found there are a lot of marks missing under CSP support section. Just by looking under Windows Business and some Windows Mobile. The yes or no mark is missing and it is really hard to tell if it is supported or not. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162c8434-b3ab-e235-43ce-ed435d6cd06e
* Version Independent ID: 18b29b82-f1ad-81b8-2ea4-f7bebc506487
* Content: [Configuration service provider reference](https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference)
* Content Source: [windows/client-management/mdm/configuration-service-provider-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/configuration-service-provider-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @SEYiWeng 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.

**Comment by e0i** [comment]
@SEYiWeng It seems that the concerns that you have raised have been addressed by the document author via the following commits,

[[6e854b6] Added enrollmentstatustracking CSP ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/6e854b67b7b882ededbccf85c148659f104fec7e#diff-4850e5c45e8668ec15845f92795f12ab)
[[fb48588] Updated SKU for EnrollmentStatusTracking CSP ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/fb4858802f09f0c8160dc265ffa251d447bd568b#diff-4850e5c45e8668ec15845f92795f12ab)
[[2d9ca2d] Updated HoloLens table ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/2d9ca2d58f0ae108f8a564e4ac9c898e13f976cb#diff-4850e5c45e8668ec15845f92795f12ab)

Thank you for bringing this issue to attention.
