### ISSUE TITLE
Replace command on Office CSP

### ISSUE THREAD

**Issue by satish860** [MicrosoftDocs/windows-itpro-docs#3549]
In the office CSP its mentioned Id properties can accept replace command.

![image](https://user-images.githubusercontent.com/817360/57280314-b1c7af00-70c6-11e9-9b50-b35b2c9462d1.png)

When we try it we are getting a 405 on the command then we looked into DDF to confirm. It has 2 nodes.

` <NodeName></NodeName>
            <DFProperties>
              <AccessType>
                <Add />
                <Delete />
                <Get />
                <Replace />
              </AccessType>
              <Description>A unique identifier which represents the instalation instance id.</Description>
              <DFFormat>
                <node />
              </DFFormat>
              <Occurrence>
                <ZeroOrMore />
              </Occurrence>
              <Scope>
                <Dynamic />
              </Scope>
              <DFTitle>id</DFTitle>
              <DFType>
                <DDFName></DDFName>
              </DFType>
            </DFProperties>`

and another 
`<Node>
            <NodeName>id</NodeName>
            <DFProperties>
              <AccessType>
                <Add />
                <Delete />
                <Get />
              </AccessType>
              <Description>A unique identifier which represents the instalation instance id.</Description>
              <DFFormat>
                <node />
              </DFFormat>
              <Occurrence>
                <ZeroOrMore />
              </Occurrence>
              <Scope>
                <Dynamic />
              </Scope>
              <DFTitle>id</DFTitle>
              <DFType>
                <DDFName></DDFName>
              </DFType>
            </DFProperties>`
Which one is a correct way to look

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@satish860 

Your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Also note that the issues section of this repository is intended for documentation and content feedback.

For your  _support_ related questions or feedback, please visit, [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10).

Any documentation feedback is welcome.

Thanks.

**Comment by e0i** [comment]
@satish860

We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.

Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by illfated** [comment]
@satish860 : if you had published your comment in the feedback section of the related page, it would have been easier to follow up on your question, based on authors of the page.

Based on a web search, I presume this is about the page
- https://docs.microsoft.com/en-us/windows/client-management/mdm/office-ddf
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/office-ddf.md

The issue seems likely, but it would be good to hear from someone familiar with the content (I am unfamiliar with it).
