### ISSUE TITLE
Deploying the script

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/windows-itpro-docs#3550]
Hi -

I've downloaded the configuration script, which once extraced is actually a folder with a couple of files. The documentation states that it's possible to deploy the script using Intune and then refers to the documentation about deploying PowerShell scripts with Intune. Does this mean that only deploying the PS1 script should be sufficient, and we should use the CSP to configure it's settings, or should we modify the .bat file, then package the files into a .intunewin file and deploy the script as a Win32 Application in Intune?

How about scheduling the script? 

I'm a little bit confused, can someone clearify this?

/Kenneth

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4273a259-c3c7-dca7-6353-954068d740a7
* Version Independent ID: 1084ea77-95c4-4e4a-da6c-f4d8668f9ebf
* Content: [Enrolling devices in Windows Analytics (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started)
* Content Source: [windows/deployment/update/windows-analytics-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-get-started.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@kennethvs  

Your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Also note that the issues section of this repository is intended for documentation and content feedback.

For your  _support_ related questions or feedback, please visit, [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10).

Any documentation feedback is welcome.

Thanks.

**Comment by kennethvs** [comment]
Hi @e0i,

I'm referring to the documentation on this page: https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started

**Comment by jaimeo** [comment]
@zdvorak, can you advise here?

**Comment by kennethvs** [comment]
So, to give some more context based on my experiences so far. I'm deploying Windows Analytics for AzureAD joined machines managed by Intune. In order to do this I've enabled a Log Analytics workspace in the free plan, added the Update and Upgrade Readiness solutions. Deployed the commercial id and other settings to the devices using custom device settings in Intune. Used the following article as a reference: https://www.scconfigmgr.com/2019/03/27/windows-analytics-onboarding-with-intune/

After 2 days, data started flowing into the solution so conclusion is that the script is not needed, it doesn't have to be deployed either. So my main question is, what the use case for the script is - is it to speed up the data collection towards the Log Analytics workspace?

If so, why would you need to schedule the script? And also my other comment is still valid, if the script is downloaded you get a bunch of files, which cannot be deployed using the scripts function in Intune, neither can Intune "schedule" the execution of the script, while SCCM can using its Packages functionality. This needs to be corrected IMHO. Also some clear explantion on the use case for the script would really clearify things.

**Comment by e0i** [comment]
@zdvorak Any updates on this?

**Comment by joinimran** [comment]
Hello @kennethvs - Can you please confirm the reference document is the correct one as there is no information found regarding the script installation etc.

@e0i - FYI & A Please.
