### ISSUE TITLE
Wrong URI path to allow flash

### ISSUE THREAD

**Issue by mariopenterman** [MicrosoftDocs/windows-itpro-docs#3553]
According to this page, the URI to enable / disable flash should be:
./Vendor/MSFT/Policy/Config/Browser/AllowAdobeFlash

While in fact the correct path is:
./Vendor/MSFT/Policy/Config/Browser/AllowFlash

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7fe2c9-aae2-5095-fe96-9699de018300
* Version Independent ID: cfc2c4e1-dd70-0e39-4d39-beb5c8ca270b
* Content: [Microsoft Edge - Adobe Flash group policies](https://docs.microsoft.com/en-us/microsoft-edge/deploy/group-policies/adobe-settings-gp#feedback)
* Content Source: [browsers/edge/group-policies/adobe-settings-gp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/group-policies/adobe-settings-gp.md)
* Product: **edge**
* Technology: **microsoft-edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@mariopenterman 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by e0i** [comment]
@mariopenterman 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
