### ISSUE TITLE
Valid Characters for registry key

### ISSUE THREAD

**Issue by br549v** [MicrosoftDocs/windows-itpro-docs#3556]
What characters are allowed for the registry key? Most of the values I have tried in the registry never show up in the console. Are there limits on length or special characters?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b42e708-e334-d434-bcc9-e1860ebb36b3
* Version Independent ID: 92e251c5-8613-ce97-9569-02404c9a466a
* Content: [Create and manage machine tags](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/machine-tags-windows-defender-advanced-threat-protection#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-atp/machine-tags-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/machine-tags-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by Malind19** [comment]
@e0i I could not find any supportive answers for this. Can we please get some tech help?

**Comment by e0i** [comment]
@mjcaparas Would you be able to provide assistance in the right direction for a PR as the time permits? Thank you.

**Comment by mjcaparas** [comment]
Ack. Checking with team.

**Comment by e0i** [comment]
@mjcaparas Any updates?

**Comment by Malind19** [comment]
Hi @e0i , 
Following are the specifications found on Microsoft Docs. 
https://docs.microsoft.com/en-us/windows/win32/sysinfo/registry-element-size-limits

Not sure this article is the right place to duplicate them. But probably, can add this as a reference.

**Comment by mjcaparas** [comment]
Not getting response. But I think the above link provided by malind19 is general reference that we can cross-reference to.

**Comment by e0i** [comment]
Hello @br549v,

As mentioned, registry keys can consist of printable ASCII characters with maximum size of 255 bytes.

Find below links to relevant articles,
https://docs.microsoft.com/en-us/windows/win32/sysinfo/registry-element-size-limits
https://docs.microsoft.com/en-us/windows/win32/sysinfo/structure-of-the-registry

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
