### ISSUE TITLE
MBAM Support Ending July 2019?

### ISSUE THREAD

**Issue by craigblake** [MicrosoftDocs/windows-itpro-docs#3557]
Although this document was written in February of 2019 I have read several article about mainstream support for MBAM ending in July 2019. Is this true and should it still be recommended as I feel it is in this document to use it? If not is there a new best practice in 2019 you can recommend for implementation? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29116f85-264f-d031-be7b-e32a1816cd28
* Version Independent ID: 640478e6-a367-4e47-a177-3a10dd006d1c
* Content: [Overview of BitLocker Device Encryption in Windows 10](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10#feedback)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @craigblake  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@Justinha Would you be able to follow-up with clarification regarding MBAM Support as the time permits? Thank you.

**Comment by illfated** [comment]
Search result information from Microsoft support and help pages:
- https://support.microsoft.com/en-us/lifecycle/search?alpha=BitLocker%20Administration%20and%20Monitoring
- https://support.microsoft.com/en-us/help/17138/service-pack-lifecycle-policy
- https://support.microsoft.com/en-us/lifecycle/search/18037

| Products Released | Lifecycle Start Date | Mainstream Support End Date | Extended Support End Date | Service Pack Support End Date | Notes |
| ----------------- | -------------------- | --------------------------- | ------------------------- | ----------------------------- | ----- |
| BitLocker Administration and Monitoring 2.5                | 5/1/2014 | Not Applicable | Not Applicable | 10/11/2016 | See the latest Service Pack listing for this product for the end of support dates. |
| BitLocker Administration and Monitoring 2.5 Service Pack 1 | 8/3/2015 | 7/9/2019       | 7/9/2024       |            | Support ends 12 months after the next service pack releases or at the end of the product's lifecycle, whichever comes first. For more information, please see the service pack policy (https://support.microsoft.com/help/17138) . |

**Comment by e0i** [comment]
Hello, @craigblake 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
