### ISSUE TITLE
Broken Link - Join Windows 10 Mobile to Azure Active Directory

### ISSUE THREAD

**Issue by computeronix** [MicrosoftDocs/windows-itpro-docs#356]
Azure AD Join on Windows 10 devices link points to https://go​.microsoft​.com/fwlin​k/p/?LinkI​D=616791 which then redirects to https://cloudblogs.microsoft.com/enterprisemobility/archive/2015/05/28/azure-ad-join-on-windows-10-devices.aspx which is not valid

Proposed new link for it to redirect you to: https://cloudblogs.microsoft.com/enterprisemobility/2015/05/28/azure-ad-join-on-windows-10-devices/

**Comment by jdatms** [comment]
Thanks for pointing that out. I've fixed the fwlink, it may take a little while for the change to be live.
