### ISSUE TITLE
fixed inappropriate japanese 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3565]
[LOC] "Windows コマンド プロンプトを開きます。 コマンド プロンプトを開き、 _gt 実行の開始をクリックします。 "needs to be replaced with "Windowsのコマンドプロンプトを開きます。 コマンドプロンプトを開くには、[スタート]> [ファイル名を指定して実行]の順にクリックします。 "

https://docs.microsoft.com/ja-jp/windows/deployment/update/windows-update-resources
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - その他のリソース](https://docs.microsoft.com/ja-jp/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **elizapo**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@dongmicro Would you be able to follow-up with this Japanese translation issue most likely stemming from automated translation?

Thank you.

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
Thanks for the feedback @hyoshioka0128 
Set the topic to be human translated, will take 2-3 weeks to process

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間翻訳されており、問題は修正されているようです。 修正済みであることを確認してください。 フィードバックをありがとうございました。
(The article is now human translated and the issue appears to be fixed.  Please verify that it is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Fixed.
Closed #3565
Thanks.
