### ISSUE TITLE
[LOC] Back-Translation 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3567]
・Ren %systemroot%\SoftwareDistribution\DataStore *.bak お
・Ren %systemroot%\SoftwareDistribution\Download *.bak お
・Ren %systemroot%\system32\catroot2 *.bak お
　↓
・Ren %systemroot%\SoftwareDistribution\DataStore *.bak
・Ren %systemroot%\SoftwareDistribution\Download *.bak
・Ren %systemroot%\system32\catroot2 *.bak

https://docs.microsoft.com/ja-jp/windows/deployment/update/windows-update-resources

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - その他のリソース](https://docs.microsoft.com/ja-jp/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **elizapo**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@dongmicro It looks like translated strings are mixed with executable command strings that are not written within code blocks but in bullet points. See a list of similar issues referenced to this issue below and please follow-up. Thanks.

**Comment by illfated** [comment]
An alternative workaround would be to encapsulate the command strings in code blocks in the English version of the documents and let the translation script handle it as before, but that code block solution might not be in line with current Microsoft Docs code style.

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間翻訳されており、問題は修正されているようです。 修正済みであることを確認してください。 フィードバックをありがとうございました。
(The article is now human translated and the issue appears to be fixed.  Please verify that it is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Fixed.
Closed #3567
Thanks.
