### ISSUE TITLE
[LOC] Back-Translation 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3568]
・sc.exe sdset ビット d: (A です。CCLCSWRPWPDTLOCRRC;;SY) (A です。CCDCLCSWRPWPDTLOCRSDRCWDWO;;バー) (A です。CCLCSWLOCRRC;;AU) (A です。CCLCSWRPWPDTLOCRRC;;PU)
・sc.exe sdset wuauserv d: (A です。CCLCSWRPWPDTLOCRRC;;SY) (A です。CCDCLCSWRPWPDTLOCRSDRCWDWO;;バー) (A です。CCLCSWLOCRRC;;AU) (A です。CCLCSWRPWPDTLOCRRC;;PU)
　↓
・sc.exe sdset bits D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;AU)(A;;CCLCSWRPWPDTLOCRRC;;;PU)
・sc.exe sdset wuauserv D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;AU)(A;;CCLCSWRPWPDTLOCRRC;;;PU)

https://docs.microsoft.com/ja-jp/windows/deployment/update/windows-update-resources

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - その他のリソース](https://docs.microsoft.com/ja-jp/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **elizapo**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
See: #3567

**Comment by illfated** [comment]
The error excerpt above looks like it could do with code block fencing in the English version too.

Feedback on this idea is welcome -- although I suspect that the MS engineers might not be too thrilled with the workaround solution to implement code block fencing in the English version of the Docs for each and every command string to avoid translation issues.

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
@hyoshioka0128 フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 完了までに数週間かかる場合があります。(![image](https://user-images.githubusercontent.com/53281468/63063843-2fb00900-beb3-11e9-8a3f-5b15408a7367.png).
@illfated it's a good idea to fence code blocks and we may be able to do that in future using the new "noloc" extension.  The extension has not yet been tested so in this case it's easier to just upgrade the article to human translation.

**Comment by hyoshioka0128** [comment]
Hi, @TinaMcN .
It was updated in MT, but there was a part that has not been fixed yet.
![windows-update-resources_j](https://user-images.githubusercontent.com/40815708/63071845-e36cd380-bf5b-11e9-8676-729dd0948318.png)

Wait for it to be fixed.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間翻訳されており、問題は修正されているようです。 修正済みであることを確認してください。 フィードバックをありがとうございました。
(The article is now human translated and the issue appears to be fixed.  Please verify that it is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Fixed.
Closed #3568
Thanks.
