### ISSUE TITLE
Wrong SID for RDS 'Endpoint Servers'-group

### ISSUE THREAD

**Issue by Cubercoding** [MicrosoftDocs/windows-itpro-docs#3585]
The SID for the 'RDS Endpoint Servers'-group is wrong in the article. It says 'S-1-5-21-<domain>-553', which is the SID for the 'RAS and IAS Servers'-group. The Correct SID is S-1-5-32-576.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44e911d3-219e-19b8-4870-07514d9a94a1
* Version Independent ID: 960a7388-560b-90eb-e0ff-d8d2bb6f9a7a
* Content: [Active Directory Security Groups (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/active-directory-security-groups#bkmk-gpcreatorsowners)
* Content Source: [windows/security/identity-protection/access-control/active-directory-security-groups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/access-control/active-directory-security-groups.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@Cubercoding 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by Malind19** [comment]
@e0i Created PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3894

**Comment by e0i** [comment]
@Cubercoding 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
