### ISSUE TITLE
Traduccion

### ISSUE THREAD

**Issue by DrCaos** [MicrosoftDocs/windows-itpro-docs#3586]
Protección de rayos y otros puertos DMA
Seria 
Protección puertos Thunderbolt y DMA

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 92097f05-4310-827c-2781-5756b959a56c
* Version Independent ID: 770f3f11-afec-a956-bf77-dfbbcaf74249
* Content: [Contramedidas de BitLocker (Windows 10)](https://docs.microsoft.com/es-es/windows/security/information-protection/bitlocker/bitlocker-countermeasures#feedback)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-countermeasures.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-countermeasures.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@dongmicro Would you be able to help with this Spanish translation issue? Thanks.

**Comment by DrCaos** [comment]
you have translated "thunderbolt" in English by rayo in Spanish. the correct translation is thunderbolt, because is a name of technology.

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
I set the topic to be human translated, this may take 2-3 weeks to complete.

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
@DrCaos Este problema parece ser solucionado ahora, por favor confirme.  Gracias por reportarlo.

**Comment by e0i** [comment]
Manually verified to be resolved with the fixed content: _"Protección de Thunderbolt y otros puertos DMA"_
