### ISSUE TITLE
Typo in Object Access Section

### ISSUE THREAD

**Issue by poolmanjim** [MicrosoftDocs/windows-itpro-docs#3587]
In the second sentence of the section, third line on my screen it has the following: "Aaccess auditing subcategory for success and/or failure events." Access is spelled wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 739bc932-12f0-9595-fbd2-d5b0df73fe93
* Version Independent ID: cd1f89ad-34db-bb96-e9ef-2137958c9403
* Content: [Advanced security audit policy settings (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/advanced-security-audit-policy-settings#feedback)
* Content Source: [windows/security/threat-protection/auditing/advanced-security-audit-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/advanced-security-audit-policy-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Would you be able to create a PR to address a typo for this issue? Thanks.
