### ISSUE TITLE
Windows 10 Enterprise subscription is not valid

### ISSUE THREAD

**Issue by tommy1520** [MicrosoftDocs/windows-itpro-docs#3591]
Recently i have a few of our users' machine reverted itself from Windows 10 Enterprise to Pro

I have checked the requirements needed in order for Windows 10 Pro machine getting upgraded to Enterprise via M365 E3 license. I can verify that the machine is

1. AAD-Joined
2. Windows 10 1803
3. Valid M O365 E3 license assigned to the user

Not sure what else i need to check or do. Please help? Kind Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ecbc1-9c02-5681-7214-356be22ac7e8
* Version Independent ID: 73af82f6-079b-6c37-55c4-cb59e921457a
* Content: [Deploy Windows 10 Enterprise licenses](https://docs.microsoft.com/en-us/windows/deployment/deploy-enterprise-licenses#feedback)
* Content Source: [windows/deployment/deploy-enterprise-licenses.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-enterprise-licenses.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
Hello, @tommy1520  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by tommy1520** [comment]
oh ok, sorry my bad

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot close

**Comment by MFurqhan** [comment]
Hi tommy1520,

Did you find any solution for your downgrade issue, please share me if you find the solution because I am also facing the same down gradation issue from Windows 10 Enterprise to Pro.
Please reply asap.

Thanks.

**Comment by illfated** [comment]
@MFurqhan -- if we don't see a reply from @tommy1520 within a week's time or so, it may indicate that @tommy1520 is not a frequent user of Github and hence will not notice your question. Granted, it would have been nice and useful to get some feedback regarding what the outcome from the support case was, just in case it could be used as a solution to other IT Pro users as well. Even so, if you yourself end up contacting Microsoft Support in your area, please consider posting some feedback regarding the solution for the related issue here on Github, just in case it could be added to one of the troubleshooting pages in the documentation.

**Comment by tommy1520** [comment]
> Hi tommy1520,
> 
> Did you find any solution for your downgrade issue, please share me if you find the solution because I am also facing the same down gradation issue from Windows 10 Enterprise to Pro.
> Please reply asap.
> 
> Thanks.

Dis-joining and re-joining the machine to AD seems to have worked but the thing is i don't know if that fixes the issue permanently. As you can see in my original post, i met all the criterias required but that didn't stop the machine from reverting from Ent to Pro

No issues so far for the AD re-joined machines. Will need to check again in the coming months in case its one of those grace period things

**Comment by illfated** [comment]
Thank you very much for getting back to us on this one. I am also looking forward to hear if there will be any other feedback regarding this, and if that could possibly result in some form of addition or change in the docs pages.

**Comment by aumthanki** [comment]
@tommy1520 when you next have this problem. Check event logs>User Registration and check for the errors. If you're running 1803 or later, it might be a TPM issue. TPM is required to enable Microsoft to pull activation keys directly from the device. 

Also, post your "dsregcmd /status" result from the machine.
