### ISSUE TITLE
[LOC] TOC for Windows security guidance for enterprises ja-jp document is not translated. 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3594]
https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-security-configuration-framework/windows-security-compliance

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c34a668a-c82a-fa50-fe22-0313dfab7003
* Version Independent ID: 300c5eeb-fd77-7e3e-6aad-2a66c053cb44
* Content: [企業向けの Windows セキュリティ ガイダンス](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-security-configuration-framework/windows-security-compliance)
* Content Source: [windows/security/threat-protection/windows-security-configuration-framework/windows-security-compliance.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-security-configuration-framework/windows-security-compliance.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @appcompatguy
* Microsoft Alias: **appcompatguy**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@dongmicro Would you be able to review this issue regarding Japanese localization? Thank you.

**Comment by hyoshioka0128** [comment]
https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-security-configuration-framework/windows-security-compliance
![windows-security-compliance](https://user-images.githubusercontent.com/40815708/57564834-e9e43000-73ed-11e9-9300-49b77005bbd7.png)

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by hyoshioka0128** [comment]
Fixed.
Close #3594

![windows-security-compliance_j2](https://user-images.githubusercontent.com/40815708/62229305-5aea2100-b3fa-11e9-80a2-b64abac79477.png)
ja-jp:https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-security-configuration-framework/windows-security-compliance
