### ISSUE TITLE
Windows 10 Enterprise 1809 Does Not Have "EnableVirtualizationBasedSecurity"

### ISSUE THREAD

**Issue by SEYiWeng** [MicrosoftDocs/windows-itpro-docs#3596]
Hi there, I have generated a couple VMs, and as this article stated, "EnableVirtualizationBasedSecurity" is supported from Windows 10 1709. But my Windows 10 Enterprise 1809 build 17763 does not have such entry under either Registry Editor or Group Policy Editor. 

Please kindly let me know what is causing this and how can I find it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329b43eb-db67-4458-730a-65e21a5d95c2
* Version Independent ID: 3bb2c84f-60db-0512-c44c-e6c011c36285
* Content: [Policy CSP - DeviceGuard](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-deviceguard#deviceguard-enablevirtualizationbasedsecurity)
* Content Source: [windows/client-management/mdm/policy-csp-deviceguard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-deviceguard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by RAJU2529** [comment]
@SEYiWeng here is the  registry key 
normally this below key does not exits ,  you must create 

**[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceGuard]
"EnableVirtualizationBasedSecurity"=dword:00000001**

or else you can able to  configure  via  gpo

![vbs](https://user-images.githubusercontent.com/3296790/59552346-4dd8b600-8fa3-11e9-9eb8-7b1461325b57.JPG)

**Comment by e0i** [comment]
@SEYiWeng Does the response provided by the community answers your question? We would like to follow-up. Thanks.

**Comment by RAJU2529** [comment]
its my community answer

**Comment by e0i** [comment]
Hello, @SEYiWeng 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
