### ISSUE TITLE
Requirements to use AppLocker

### ISSUE THREAD

**Issue by Crypt32** [MicrosoftDocs/windows-itpro-docs#360]
The table has a number of issues in regards to Windows 8/8.1 family:
1) Windows 8 Pro **can be used to configure policies**, but not to enforce. First column must be set to **YES**.
2) Only Windows 8.1 Pro and Enterprise editions can be used to configure policies.
3) Only Windows 8.1 Enterprise can be used to enforce policies

2-3 -- Windows 8.1 and Windows 10 family must be split in two separate rows:
```
Windows 8.1 Pro        -- YES -- NO
Windows 8.1 Enterprise -- YES -- YES
```

And there should be a note in regards to Windows 10 Enterprise and Windows Server 2016. It appears that on workgroup machines Applocker cannot be enforced anymore, it works on domain members only.

**Comment by brianlic-msft** [comment]
@Justinha Can you take a look?

**Comment by Justinha** [comment]
@Crypt32 Thanks for the corrections. We confirmed with our engineering team and the table has been updated. They indicated AppLocker can be enforced on workgroup machines; there has been no change in that respect.

**Comment by Crypt32** [comment]
> They indicated AppLocker can be enforced on workgroup machines

unfortunately, it is incorrect statement, or additional information is missing. Reference: https://docs.microsoft.com/en-us/windows/device-security/applocker/configure-the-application-identity-service

> Starting with Windows 10, the Application Identity service is now a protected process. Because of this, you can no longer manually set the service Startup type to Automatic. 

Applocker relies on Application Identity service and you can't change its start type via services.msc on a standalone machine. If you start the service, Applocker rules won't apply until the server reboots. Since service start type is Manual (by default) and cannot be changed via services.msc, after reboot the service is stopped. The configuration process described in the referenced doc is applicable for domain members only. GPMC is not available in workgroup environments. I made several tests on Windows Server 2016 and all failed to apply Applocker rules. Therefore, I concluded that it is not possible and should be mentioned in requirements unless there will be a note on how to enable Applocker in workgroup environments.

**Comment by Justinha** [comment]
@Crypt32 Thanks for explaining. I shared with engineering again and will follow up.
