### ISSUE TITLE
Set metric and exclusionRoute using VPN profile XML config file

### ISSUE THREAD

**Issue by emchj** [MicrosoftDocs/windows-itpro-docs#3600]
Hello,
I configured Always-on VPN using Force-Tunnel but Skype for business doesn't work properly over the VPN. Is it possible to bypass the skype traffic? My idea: Configuring Split-Tunnel -&gt; add a default route 0.0.0.0/0 such as Force-Tunnel sets automatically and add an exclusion for the Servers used for S4B. Is it possible to make these settings through the XML config file?
VPNv2/ProfileName/RouteList/routeRowId/Metric:

Added in Windows 10, version 1607. The route's metric.
Value type is int. Supported operations include Get, Add, Replace, and Delete.

VPNv2/ProfileName/RouteList/routeRowId/ExclusionRoute

Added in Windows 10, version 1607. A boolean value that specifies if the route being added should point to the VPN Interface or the Physical Interface as the Gateway. Valid values:
False (default) - This route will direct traffic over the VPN
True - This route will direct traffic over the physical interface.
Supported operations include Get, Add, Replace, and Delete.

https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3032f094-c9b7-6f8c-5b66-2ba152d7c326
* Version Independent ID: 83047fc5-7020-be72-85d6-85fa0bfbf5b7
* Content: [ProfileXML XSD](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-profile-xsd#feedback)
* Content Source: [windows/client-management/mdm/vpnv2-profile-xsd.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/vpnv2-profile-xsd.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@emchj 

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your question so that it gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
