### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by JoeRainero** [MicrosoftDocs/windows-itpro-docs#3601]
Microsoft sites, services, and properties, as well as computers running Windows 10, can use a Microsoft account as a mean of identifying a user.

Should say "Microsoft sites, services, and properties, as well as computers running Windows 10, can use a Microsoft account as a means of identifying a user."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fff77d32-6e10-ad01-b32d-14b0f3861e6a
* Version Independent ID: 466fdc6d-cde8-b981-7926-97aecc11de21
* Content: [Microsoft Accounts (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/microsoft-accounts#feedback)
* Content Source: [windows/security/identity-protection/access-control/microsoft-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/access-control/microsoft-accounts.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Would you kindly create a PR for the grammar error described? Thank you.

**Comment by illfated** [comment]
This is a small typo correction. I volunteer to create the PR for this small change.
