### ISSUE TITLE
Windows Hello for Business vs. Virtual Smart Card

### ISSUE THREAD

**Issue by robmacf** [MicrosoftDocs/windows-itpro-docs#3602]
Virtual Smart Card is being superseded by Windows Hello for Business. It would be a good idea to include that information on this Virtual Smart Cards topic.

Refer to this page: https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-faq

Specifically this statement: "Microsoft recommends new Windows 10 deployments to use Windows Hello for Business. Virtual smart card remain supported for Windows 7 and Windows 8."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263e05e9-23b3-40bb-0db2-cf215414457e
* Version Independent ID: 8e32b5ef-93dc-4573-0ed6-a941cf1186fb
* Content: [Virtual Smart Card Overview (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-overview)
* Content Source: [windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@robmacf 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by e0i** [comment]
@robmacf 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
