### ISSUE TITLE
Silent Printing for Edge Kiosk Mode

### ISSUE THREAD

**Issue by joordan** [MicrosoftDocs/windows-itpro-docs#3604]
I enjoyed the easiness of setting up the kiosk mode with the Edge browser (Windows 10, version 1809).  However, I was wondering if there is a way to lock/limit the printer settings, or to remove the print dialog options in order to print directly / silent print? I'm planning to using kiosk mode in a business setting where our customers are able to print, but they can see the print dialog box before they are able to print, where they can change printers or amount of copies to print.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f49c3f-ba5c-49e9-fad2-88cac155920a
* Version Independent ID: dc5e1f7e-61a8-bf2c-34b8-4046d024f4c2
* Content: [Set up a single-app kiosk (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/kiosk-single-app#instructions-for-windows-10-version-1809)
* Content Source: [windows/configuration/kiosk-single-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-single-app.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by e0i** [comment]
@joordan 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot close
