### ISSUE TITLE
Windows Server 2019 Info

### ISSUE THREAD

**Issue by rondls4** [MicrosoftDocs/windows-itpro-docs#3605]
Can we get an updated Windows Defender Antivirus compatibility document that includes Windows Server 2019? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b88aee4-6727-fa98-1180-29708eea027e
* Version Independent ID: 374c671b-b21c-6eac-d887-892491357eb2
* Content: [Windows Defender Antivirus compatibility with other security products](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-compatibility#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-compatibility.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-compatibility.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by jeffreymcclain** [comment]
@e0i  Any update on this? I'd like to know whether Windows Defender on Server 2019 automatically disables itself if a 3rd party AV is installed.

**Comment by denisebmsft** [comment]
Greetings! I have updated this article and the changes should be live before noon today. On Windows Server 2016 and Windows Server 2019, Windows Defender Antivirus does not automatically disable itself when you install another antivirus solution; you would have to uninstall or manually disable Windows Defender Antivirus in those cases. I hope this helps!
