### ISSUE TITLE
[LOC] Showing "**\system\currentcontrolset\services\fontcache\parameters**" (extra asterisks appears)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3612]
https://docs.microsoft.com/ja-jp/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 9abd3113-b803-87b6-ef7f-6893bcc5ceb5
* Version Independent ID: 6f7ca1ee-d19c-42bb-7db5-6158fc160e32
* Content: [Windows オペレーティング システムのコンポーネントから Microsoft サービスへの接続の管理 (Windows 10)](https://docs.microsoft.com/ja-jp/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services)
* Content Source: [windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
Comparing the Japanese page with the English (US) page, the affected paragraph does not exist on the English page:
https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services#6-font-streaming
> - In Windows 10, version 1703, you can apply the System/AllowFontProviders MDM policy from the Policy CSP where:
>
>     - False. Font streaming is Disabled.
>
>     - True. Font streaming is Enabled.

https://docs.microsoft.com/ja-jp/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services#6-%E3%83%95%E3%82%A9%E3%83%B3%E3%83%88-%E3%82%B9%E3%83%88%E3%83%AA%E3%83%BC%E3%83%9F%E3%83%B3%E3%82%B0
> - Windows 10 バージョン 1703 ではポリシー CSP で System/AllowFontProviders MDM ポリシーを、次のように適用することができます。
>
>   - false。 フォント ストリーミングを無効にします。
>
>   - true。 フォント ストリーミングを有効にします。
>
> Windows 10 バージョン 1507 または Windows 10 バージョン 1511 を実行している場合に**HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\FontCache\Parameters**で**\system\currentcontrolset\services\fontcache\parameters**という名前の reg _dword レジストリ設定を作成します。1 の値。

The extra paragraph on the Japanese page, from Google Translate:
> **HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\FontCache\Parameters** and reg_dword registry settings named ** \system\currentcontrolset\services\fontcache\parameters** when running Windows 10 version 1507 or Windows 10 version 1511 Create A value of 1.

The same paragraph in Bing Translator:
> **HKEY_LOCAL_MACHINESystemCurrentControlSetServices** If you are running Windows 10 version 1507 or Windows 10 version 1511 Create a Reg _dword registry setting that is named * * systemlogrentsetrootserversfontca.credentials * * in the Foncatheparameters A value of 1.

(I am unable to read Kanji/Hiragana/Katakana or speak Japanese. I only know a few words based on Rōmaji.)

**Comment by e0i** [comment]
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
See: #3519

**Comment by hyoshioka0128** [comment]
related: #3159

**Comment by hyoshioka0128** [comment]
related issue: #3159

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by e0i** [comment]
Manually verified to be fixed.
