### ISSUE TITLE
Clarifications

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#3614]
The AppLocker "ManagedInstaller" rule is an example for SCCM. I assume that, for a different installer (e.g. Intune) it is necessary only to identify the signed Product Name or Binary Name.
For the Rule Collection Extensions, for services, the example given is a dummy Deny rule in an Audit Only rule collection. If we already have real rules in an Enforced rule collection, can I assume we just add the same extensions?
Is there any dependency for implementing the extensions. I don't see any documentation of them. What happens if we enable the extensions in an enforced policy, if we are not using WDAC at that time? 
And lastly, is it necessary to set the AppLocker filter driver to autostart, if we are already implementing AppLocker policies; or is this the case only when implementing WDAC without AppLocker?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07fdf27b-1ead-1b6e-c793-a2ad259a4f6a
* Version Independent ID: 8da1f371-73d4-c79f-a97b-80170e7860af
* Content: [Deploy Managed Installer for Windows Defender Device Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-managed-installer)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-managed-installer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-managed-installer.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mdsakibMSFT
* Microsoft Alias: **justinha**

**Comment by anthony-yates** [comment]
Last point (AppLocker filter driver autostart) is clarified in the section on ISG: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-intelligent-security-graph. "For WDAC policies deployed over MDM using the AppLocker CSP this step is not required as the CSP will enable the necessary components."

**Comment by anthony-yates** [comment]
The Managed Installer rule collection is not documented in the AppLocker CSP.  Does that mean it is not supported over OMA-URI, or just not documented?

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by VLG17** [comment]
@Air-Git 

>The AppLocker "ManagedInstaller" rule is an example for SCCM. I assume that, for a different installer (e.g. Intune) it is necessary only to identify the signed Product Name or Binary Name.

 For Intune, i think the best approach is to leverage the Intelligent Security Graph integration with WDAC. More details [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-intelligent-security-graph).

"**Other mechanisms like managed installer** and explicit rules will help cover internal applications. Both System Center Configuration Manager (SCCM) and **Microsoft Intune can be used to create and push a WDAC policy to your client machines.**"

> For the Rule Collection Extensions, for services, the example given is a dummy Deny rule in an Audit Only rule collection. If we already have real rules in an Enforced rule collection, can I assume we just add the same extensions?

Correct, you just need to edit the enforced rule collection and add the extension part.

> Is there any dependency for implementing the extensions. I don't see any documentation of them. What happens if we enable the extensions in an enforced policy, if we are not using WDAC at that time?

IMO the best approach would be to set the enforcement mode to AuditOnly after implementing the extensions, confirm that what gets logged is what you want and afterwards change the policy enforcement back to Enabled.

**Comment by e0i** [comment]
Hello @Air-Git,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Comment by Air-Git** [comment]
Not remotely answered.
The outcome of my investigation is that Intune cannot support the Managed Installer WDAC rule option.
