### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#3617]
I appreciate it is hard to keep up with the pace of change. But the WDAC documentation refers to two items in the AppLocker CSP that are not documented here:
- the ManagedInstaller rule collection
- the Rule Collection Extensions for Services and System Apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa7dd86-8bcc-bb92-0a66-86e24701e5a4
* Version Independent ID: 277e194c-0fa3-7da6-1814-f6951e440df6
* Content: [AppLocker CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/applocker-csp)
* Content Source: [windows/client-management/mdm/applocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/applocker-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by Reeced40** [comment]
@Air-Git Thank you for pointing this out.  Please see this link for new enhancements coming soon. https://www.microsoft.com/security/blog/2019/07/01/delivering-major-enhancements-in-windows-defender-application-control-with-the-windows-10-may-2019-update/.

**Comment by Air-Git** [comment]
Thanks. Curiously, the May documentation refers to an Application Control CSP, but I can find no documentation of it.

**Comment by Reeced40** [comment]
@Air-Git. Thank you, I spoke with the team. This is still in roll-out and there should be documentation for it soon.

**Comment by e0i** [comment]
Hello @- ,

The issue is being closed since your support question seems to be answered. Feel free to re-open this issue if you still feel it hasn't been answered.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by Air-Git** [comment]
I am pleased that the omissions in the documentation will be rectified.
