### ISSUE TITLE
No FAQ?

### ISSUE THREAD

**Issue by jdanderson54** [MicrosoftDocs/windows-itpro-docs#3625]
I guess there are no Frequently Asked Questions...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae820097-c400-ff49-f28e-b784adfbf86a
* Version Independent ID: 5a5cf946-28ce-6ccd-a5cf-31c4fd09585f
* Content: [BitLocker To Go FAQ (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-to-go-faq#feedback)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-to-go-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-to-go-faq.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jdanderson54 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@nenonix - As discussed, kindly assist to provide updates on the progress of this issue. Thank you.

**Comment by nenonix** [comment]
@jdanderson54 Thanks for your feedback, and your patience. I did forward your query (along with other specific queries about BitLocker To Go) to the BitLocker team and they explained that most questions about BitLocker To Go are answered in the general BitLocker FAQ. They have noted all the queries and content addressing these should follow, but please note that BitLocker To Go signals a removable device and is not a separate product (see https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1188). I am going to ask @mypil to close this issue for now (you can reopen it in the future if you feel that your query has not been dealt with adequately).

**Comment by mypil** [comment]
@jdanderson54 - From our understanding, the issue you raised has been answered by nenonix. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
