### ISSUE TITLE
Cryptographic Service Provider

### ISSUE THREAD

**Issue by fightingsibuyas** [MicrosoftDocs/windows-itpro-docs#3630]
Twice in this article that CSP was defined as Credential Service Providers which I think is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01db3c4c-a866-d367-72fb-86866a9ff2c6
* Version Independent ID: 5bc85899-f203-fd08-e6d8-deb9736fb17e
* Content: [Smart Card Architecture (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/smart-cards/smart-card-architecture#implications-for-csps-in-windows)
* Content Source: [windows/security/identity-protection/smart-cards/smart-card-architecture.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/smart-cards/smart-card-architecture.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @fightingsibuyas 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.

**Comment by Malind19** [comment]
@e0i Created OR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3893

**Comment by e0i** [comment]
@fightingsibuyas 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by fightingsibuyas** [comment]
Hi, CSP should be Cryptograhic Service Provider, it was not corrected on this article.
