### ISSUE TITLE
Out-Of-Date

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/windows-itpro-docs#3631]
This content is completely out of date, please update it to show the current supported process for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a3b18ac-f556-8986-e13b-22cdcda3e31f
* Version Independent ID: d8f9e0d0-a162-0e0a-abe7-8e878510995f
* Content: [Sign up for Microsoft Store for Business or Microsoft Store for Education (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/sign-up-microsoft-store-for-business#feedback)
* Content Source: [store-for-business/sign-up-microsoft-store-for-business.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/sign-up-microsoft-store-for-business.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by AdamGrossTX** [comment]
FYI @e0i I have a blog about this with the updated process. 

https://www.asquaredozen.com/2019/05/12/deploying-microsoft-store-for-business-apps-from-configmgr/

**Comment by e0i** [comment]
Hello, @AdamGrossTX 

Thank you for following-up with your write-up to improve this document.

The issue has been noted and the document will be revised in the light of your feedback.

Note that public contributions are welcome and thus you may also create a PR to address any defects that you have found in a documentation.

**Comment by illfated** [comment]
As much as I would like to offer assistance in the form of opening a PR for the needed changes, I prefer that someone more familiar with the topic posts the actual changes. I am still available for technical support regarding the pull request, though.

**Comment by nenonix** [comment]
@illfated I will happily try but may need some help from you (and @e0i may have assigned this already) 😄

**Comment by e0i** [comment]
@AdamGrossTX A PR is under delivery for this issue. Thanks.

**Comment by illfated** [comment]
Sounds good. Could we have the PR linked back here or link the PR page from here?

**Comment by nenonix** [comment]
@illfated I am working on it, will link PR when done 😄

**Comment by nenonix** [comment]
Apologies for the delay, PR coming soon

**Comment by illfated** [comment]
Thanks for the feedback. I know that feeling. There are always more things to do than time permits these days.
