### ISSUE TITLE
Release Date

### ISSUE THREAD

**Issue by jamestmace** [MicrosoftDocs/windows-itpro-docs#3637]
When will this be available in Tenants to use? As you can understand without this feature being available we can't control the firewall rules at present which is very frustrating so we are having to stick with GPO instead of Intune at present. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b84a77a5-54c7-22c7-b699-c1414c7cd6a1
* Version Independent ID: f78d7bc3-97c8-d8e9-d4f7-5ea82680c738
* Content: [Create Windows Firewall rules in Intune (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/create-windows-firewall-rules-in-intune#feedback)
* Content Source: [windows/security/threat-protection/windows-firewall/create-windows-firewall-rules-in-intune.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-firewall/create-windows-firewall-rules-in-intune.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @tewchen
* Microsoft Alias: **justinha**

**Comment by tewchen** [comment]
this feature is current in private preview, and will be release in public review/GA very soon. If you want to try the feature before public review, you can join the private preview. We may need some information from you. You can contact me offline or contact Microsoft field.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @jamestmace 

It seems that your question has already been answered and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by natodogg** [comment]
Can you please advise how I would join the Private Preview as it would be very useful for my organisation to be able to manage Defender FW rules via this Device Config profile.  I'm looking at having to use PowerShell in the interim to add rules.

**Comment by johanvjr** [comment]
Can you please add me to the private preview..? We would love to test this one. @tewchen

**Comment by bvorland** [comment]
@tewchen Can you please advise how I would join the Private Preview as it would be very useful for my organisation to be able to manage Defender FW rules via this Device Config profile. I'm looking at having to use PowerShell in the interim to add rules.

**Comment by tewchen** [comment]
> @tewchen Can you please advise how I would join the Private Preview as it would be very useful for my organisation to be able to manage Defender FW rules via this Device Config profile. I'm looking at having to use PowerShell in the interim to add rules.

Hi bvorland, this is feature is now in public preview! Please let me know if you are still unable to see this feature. 

I'm looking at having to use PowerShell in the interim to add rules. -> we are now investigating to develop a tool that allow customers to import and deploy FW rules through script, we should be able to share more detail in Oct, but no timeline for now yet.

**Comment by tewchen** [comment]
> Can you please add me to the private preview..? We would love to test this one. @tewchen

Hi johanvjr, sorry for replying so late! This feature is now in public preview. You should be able to see the feature in Intune now. Please let me know if you are still unable to see.
