### ISSUE TITLE
Note that Basic Purchaser Role is only for Microsoft Store for Education

### ISSUE THREAD

**Issue by gsterk** [MicrosoftDocs/windows-itpro-docs#3641]
I believe this page used to include a note that the Basic Purchaser role only applied to the Store for Education and NOT for the Store for Business. This note is still included on the Overview (https://docs.microsoft.com/en-us/microsoft-store/microsoft-store-for-business-overview), however when the Store permissions page indicated a change and linked directly to here and the note was not here, so we believed that that restriction had been lifted. I would suggest the note be included on this page as well so people coming from the store are aware of the restriction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e62232-54ab-fa9d-1e31-7a65e7506a12
* Version Independent ID: 51a94f92-9ff4-12e7-2f97-1bbe34855400
* Content: [Roles and permissions in Microsoft Store for Business and Education (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/roles-and-permissions-microsoft-store-for-business#feedback)
* Content Source: [store-for-business/roles-and-permissions-microsoft-store-for-business.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/roles-and-permissions-microsoft-store-for-business.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @gsterk 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.

**Comment by TrudyHa** [comment]
Basic purchaser is available for both Microsoft Store for Business and Microsoft Store for Education.

**Comment by gsterk** [comment]
Based on https://docs.microsoft.com/en-us/microsoft-store/microsoft-store-for-business-overview and the support ticket I just closed it’s not really. The role exists for Store for Business, but it does not enable the ability to purchase apps, at least not for us.

**Comment by e0i** [comment]
Hello, @gsterk 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
@TrudyHa Would you be able to provide further clarifications to move forward with a possible PR for this issue? Thanks.

**Comment by e0i** [comment]
@TrudyHa Any updates with this query? We would like to follow-up. Thanks.
