### ISSUE TITLE
Ambiguity

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#3642]
"Beginning with the March 2019 quality update, each version of Windows requires blocking a specific version of the following files:"
Does this mean that (for example) on Windows 1803, I only block the files commented as &lt;! -- RS4 Windows 1803 --&gt;? In that case, what do I do if I need a policy that works on both Windows 1803 and 1809? The implication is that I need two policies. But why not just block all versions of those files?
Please explain more clearly what the block list should contain for these three files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d71055e-2b14-227b-0107-c8f150194d5b
* Version Independent ID: 0eab18a0-7e8f-05eb-b47f-e6913682d8e8
* Content: [Microsoft recommended block rules (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jsuther1974
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@Justinha Would you kindly advise how to move forward with this issue? We would like to follow-up with PRs if necessary. Thanks.

**Comment by Kofl** [comment]
Would be also interested in that topic.

And what about Windows Server 2019, should we also block the files there?

**Comment by Justinha** [comment]
@Air-Git sorry to miss this. You can create two diff policies in that case, or merge them into one broader policy. 
@Kofl yes, WDAC is applicable to Windows Server 2019 in the same way as WS 2016.

@e0i can you have someone add this to the topics?

**Comment by illfated** [comment]
Unless one of the Microsoft internals have already started working on this, I will gladly offer a PR to add the extra statements to the page. My initial thought is that the statements could be in form of a Note "bubble" (maybe 2 notes?) at the end of the page, directly after the long XML code block. Maybe something like this:

> [!Note]
> To create a policy that works on both Windows 1803 and 1809, you can create two diff policies, or merge them into one broader policy.
>
> WDAC is applicable to Windows Server 2019 in the same way as for Windows Server 2016.

Maybe the last line should have its own Note "bubble", where the previous one could be placed above the XML code block and the second line at the end, after the XML. Any recommendations?

**Comment by Justinha** [comment]
@illfated thanks very much! You can add Windows Server 2019 to the Applies to list at the top. There is a topic that explains how to merge, you can add a link to that as well: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/merge-windows-defender-application-control-policies
