### ISSUE TITLE
Document(ja-jp) is not translated.

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3648]
ja-jp:https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus
![windows-defender-security-center-antivirus_ja](https://user-images.githubusercontent.com/40815708/57683357-6e44e600-766e-11e9-9ace-af39112e62c3.png)

en-us:https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus
![windows-defender-security-center-antivirus_en](https://user-images.githubusercontent.com/40815708/57683378-79981180-766e-11e9-8393-2e191a5674e3.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8141d691-eee8-8861-4d04-24a78c7636b0
* Version Independent ID: 47c49eef-0812-2224-e8c4-fa4385df0789
* Content: [Windows Defender ウイルス対策、Windows セキュリティ センター アプリ](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@dongmicro The referenced document is not translated. Would you be able to review this issue?

**Comment by illfated** [comment]
Copied some of the text in here, in case anyone wants to search for the relevant text on the page (no direct link to the paragraph).
***
**ReviewthreatdetectionhistoryintheWindowsDefenderSecurityCenterapp**1。
OpentheWindowsDefenderSecurityCenterappbyclickingtheshieldiconinthetaskbarorsearchingthestartmenufor**Defender**します。

1. クリックVirus&threatprotectiontile(ortheshieldiconontheleftmenubar) します。

3.**Threathistory**をクリックします。

1. クリックして**Seefullhistory**undereachofthecategories (**Currentthreats**、**Quarantinedthreats**、**Allowedthreats**)。
***

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by illfated** [comment]
At a glance, it looks like the machine translation removed too many spaces, including the normal single spaces between words.
In my opinion, the the originating en-us page needs to be fed through the translation script again, to see if any improvement appears.
If no immediate improvement appears this time, it needs manual review or translation.

**Comment by hyoshioka0128** [comment]
Hi, @illfated. It has been updated, but not fixed.

![windows-defender-security-center-antivirus](https://user-images.githubusercontent.com/40815708/62228641-0b572580-b3f9-11e9-871d-e679caed6f19.png)
ja-jp:https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus

Thank you.

**Comment by TinaMcN** [comment]
I set the topic to be human translated, this may take 2-3 weeks to complete.

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間翻訳されており、問題は修正されているようです。 修正済みであることを確認してください。 フィードバックをありがとうございました。
(The article is now human translated and the issue appears to be fixed.  Please verify that it is fixed.  Thanks again for the feedback.)
![image](https://user-images.githubusercontent.com/53281468/68062088-713b9d80-fcc5-11e9-80df-0bbc96c6959e.png)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Fixed.
Closed #3648
Thanks.
