### ISSUE TITLE
[LOC] "ウイルス & 脅威の保護の更新" needs to be replaced with "ウイルスと脅威の防止の更新"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3649]
https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8141d691-eee8-8861-4d04-24a78c7636b0
* Version Independent ID: 47c49eef-0812-2224-e8c4-fa4385df0789
* Content: [Windows Defender ウイルス対策、Windows セキュリティ センター アプリ](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
See: #3487

**Comment by illfated** [comment]
(Ampersand (`&`) issue)

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 問題が解決したことを確認してください。 フィードバックをありがとう。
(The article is now human translated.  Please verify that the issue is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Fixed.
Closed #3649.
