### ISSUE TITLE
[LOC] "ウイルス & 脅威の保護" needs to be replaced with "ウイルスと脅威の防止"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3653]
https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: de416fda-04fb-6780-6675-020fdc2426ba
* Version Independent ID: ede7f3c1-ba3a-e331-80d8-c992b3d7f9a4
* Content: [Windows Defender AV で検疫されたファイルを復元します。](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
See: #3487

**Comment by illfated** [comment]
(Ampersand (`&`) issue)

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
私は人間の翻訳のためにこの記事を送った。 約3週間かかります。 (I sent this article to be human translated.  It should take approximately 3 weeks.)

**Comment by e0i** [comment]
@TinaMcN Hello Tina, The document seems not to have been updated. Could you verify? Thanks.

**Comment by TinaMcN** [comment]
@e0i it is currently in localization but taking a bit longer than expected, hope it will be done soon.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated. Please verify that it is fixed. Thanks again for the feedback)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #3653.
Thanks.
