### ISSUE TITLE
[LOC]Showing "**警告: **", "**ブロック: **", "**オフ: **" (extra asterisks appears)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3662]
https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-set-individual-device

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: bf8c7d37-cdf5-e892-dd6b-03fcb0413e77
* Version Independent ID: 62d3dd5b-4c8b-4e14-c659-01c8d8248e6f
* Content: [個々のデバイスで Windows Defender SmartScreen を設定および使用する (Windows 10)](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-set-individual-device)
* Content Source: [windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-set-individual-device.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-set-individual-device.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
See: #3159

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
Thank you for the feedback.  This is a problem with the MT tool.  I have reported the problem to the tool owners.   I don't expect this issue to be fixed quickly.  I will update when we have a fix.
フィードバックをありがとうございました。 これは MT ツールの問題です。 私はツールの所有者に問題を報告しました。  この問題がすぐに解決されるとは思いません。 修正が必要になったときに更新します。

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated. Please verify that it is fixed. Thanks again for the feedback)

**Comment by illfated** [comment]
Unfortunately, the issue persists. There are 8 pairs of double asterisks ( `**` ) where the second double asterisk is consistently preceded by a space character, breaking the MarkDown **bold** formatting:

https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-set-individual-device#従業員が-windows-セキュリティを使って-windows-defender-smartscreen-を設定する方法

![image](https://user-images.githubusercontent.com/38162891/72022748-83136100-3271-11ea-9307-8e32c57987e2.png)

(To see this for yourself, go to the page in the issue ticket description, or the link directly above in this comment, and use Ctrl+F to search for the double asterisks `**`.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Not Corrected.
Thanks.

**Comment by TinaMcN** [comment]
@hyoshioka0128 そのことについてお詫び申し上げます。  私は翻訳者に問題を調査し、修正するように頼みました。 (I apologise about that.   I have asked the translators to investigate and fix the issue.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 これで問題が修正されました。 フィードバックをありがとう。 (The issue has now been fixed.  Thanks again for the feedback.)

**Comment by illfated** [comment]
Confirmed, the issue is now resolved. No more visible asterisks ( ** ) in the article document.

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #3662.
Thanks
