### ISSUE TITLE
[LOC]Showing "**フィッシング詐欺対策およびマルウェア対策のサポート: **" (extra asterisks appears)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3665]
https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-overview

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fb097945-c324-9797-b3a7-9d41b05bec66
* Version Independent ID: f67b7c1b-1d59-3869-b380-44f695356839
* Content: [Windows Defender SmartScreen の概要 (Windows 10)](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-overview)
* Content Source: [windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
See: #3159

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
Thank you for the feedback.  This is a problem with the MT tool.  I have reported the problem to the tool owners.   I don't expect this issue to be fixed quickly.  I will update when we have a fix.
フィードバックをありがとうございました。 これは MT ツールの問題です。 私はツールの所有者に問題を報告しました。  この問題がすぐに解決されるとは思いません。 修正が必要になったときに更新します。

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated. Please verify that it is fixed. Thanks again for the feedback)

**Comment by illfated** [comment]
Unfortunately, the issue persists. There are 5 pairs of double asterisks ( ** ) where the second double asterisk is consistently preceded by a space character, breaking the MarkDown bold formatting:

https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-overview#windows-defender-smartscreen-の利点

![image](https://user-images.githubusercontent.com/38162891/72023292-a2f75480-3272-11ea-9766-960ed6ff23b0.png)

(To see this for yourself, go to the issue ticket page, or use the link above in this comment, then use Ctrl+F to search for double asterisks ** .)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Not Corrected.
Thanks.

**Comment by TinaMcN** [comment]
@hyoshioka0128 そのことについてお詫び申し上げます。  私は翻訳者に問題を調査し、修正するように頼みました。 (I apologise about that.   I have asked the translators to investigate and fix the issue.)
@illfated thank you for the very helpful summary of the issue!

**Comment by TinaMcN** [comment]
@hyoshioka0128 これで問題が修正されました。 フィードバックをありがとう。 (The issue has now been fixed.  Thanks again for the feedback.)

**Comment by illfated** [comment]
Confirmed, the issue is now resolved. No more visible asterisks ( ** ) in the article document.

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #3665.
Thanks
