### ISSUE TITLE
MDATP onboard servers doc leading to customer confusion

### ISSUE THREAD

**Issue by amirsc3** [MicrosoftDocs/windows-itpro-docs#3673]
The statement In the document below is causing some confusion:
“To onboard Windows Server, version 1803 or Windows Server 2019, use the same method used when onboarding Windows 10 machines.”

The supported list of SCCM versions for server 2019 goes up to 1602, but Win10 supports more recent versions.

https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-server-endpoints-windows-defender-advanced-threat-protection#windows-server-version-1803-and-windows-server-2019

So specifically the "use the same method used when onboarding Windows 10 machines" is somewhat misleading given the fact that the exact supported SCCM version list is not appearing in the MDATP portal itself when looking into Deployment methods for Windows Server 1803 and 2019.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@amirsc3 

Somehow your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by amirsc3** [comment]
Hi, 
I provided the link to the documentation in the comment:
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints#windows-server-version-1803-and-windows-server-2019

From feedback I've received this is misleading:
"use the same method used when onboarding Windows 10 machines" - as not all supported version of SCCM which work for Win10 also work for WS2019.

**Comment by e0i** [comment]
Hello, @amirsc3 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by lindspea** [comment]
@amirsc3 Thank you for your feedback in helping improve MS Docs.  Would you suggest removing that statement from the article and replacing it with 'The supported list of SCCM versions for server 2019 goes up to 1602, but Win10 supports more recent versions."?

**Comment by amirsc3** [comment]
To make the statement consistent with what we present in the portal itself I would suggest changing simply to this:
“To onboard Windows Server, version 1803 or Windows Server 2019, please refer to the supported methods and versions below:"

What do you think?

**Comment by e0i** [comment]
@amirsc3 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
