### ISSUE TITLE
ATP available as a stand-alone sku?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/windows-itpro-docs#3674]
This page states ATP is available as part of the E5 licensing levels only, yet there is an option to trial ATP by itself. Am I to understand that while it is available in a trial, its not available for purchase outside of E5?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/minimum-requirements-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/minimum-requirements-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/minimum-requirements-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@mjcaparas Would you kindly advise how to proceed with this issue? We would like to follow-up with content updates if necessary. Thanks.

**Comment by mjcaparas** [comment]
Yes. Only available for purchase on E5.
