### ISSUE TITLE
Other Microsoft products?

### ISSUE THREAD

**Issue by KjetilEVRY** [MicrosoftDocs/windows-itpro-docs#3677]
What about other MS products? For instance you can create a new VM in Azure with both Win2016 and SQL 2017 Server, which comes preinstalled in the VM (and gives other benefits like automated patching and backup). I assume you have to manually setup exclusions for SQL server after you onboard a VM like this with Azure Security Center. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9b6379-e575-9819-eca1-a0952f66b655
* Version Independent ID: 34d81602-ffa2-5be6-67ef-b42b3b6f17ee
* Content: [Configure Windows Defender Antivirus exclusions on Windows Server 2016](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by MaratMussabekov** [comment]
Dear @KjetilEVRY ,
Microsoft Defender ATP predefined exclusions are only for Windows Server roles and features, not for separate products.
For example, there is no need to configure exclusions manually for DNS server, as it is role, but you need to manually set all the exclusions for SQL server, as it is a separate product.
Thank you

**Comment by KjetilEVRY** [comment]
Thanks, maybe you should make that more clearer in the docs. And it would be great if the Product Group would include common Server products, like SQL, Exchange etc.

**Comment by MaratMussabekov** [comment]
Hello @KjetilEVRY ,
as it is stated in the article "In Windows Server 2016, the predefined exclusions delivered by Security intelligence updates only exclude the default paths for a role or feature. "

for other products, the exclusions are the same as for other antiviruses, and most of the products have dedicated articles, for example:
sql: [How to choose antivirus software to run on computers that are running SQL Server](https://support.microsoft.com/help/309422/choosing-antivirus-software-for-computers-that-run-sql-server)
exchange:[Running Windows antivirus software on Exchange servers](https://docs.microsoft.com/exchange/antispam-and-antimalware/windows-antivirus-software?view=exchserver-2019)
SfB:[Antivirus scanning exclusions for Skype for Business Server](https://docs.microsoft.com/skypeforbusiness/plan-your-deployment/security/antivirus)
etc.
Thank you

**Comment by e0i** [comment]
Hello @KjetilEVRY,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
