### ISSUE TITLE
recommendation in: planning-settings-for-a-basic-firewall-policy

### ISSUE THREAD

**Issue by mattiasborg82** [MicrosoftDocs/windows-itpro-docs#368]
Section:
Apply local firewall rules: 
MS recommendation:
Yes. We recommend that you allow users to create and use local firewall rules. If you set this to No, then when a user clicks Allow on the notification message to allow traffic for a new program, Windows does not create a new firewall rule and the traffic remains blocked.
If you and the IT staff can create and maintain the list of firewall rules for all permitted applications and deploy them by using GPOs then you can set this value to No.
--
I would like to change this recommendation to initially be that users should not be allowed to create and use local firewall rules. This should be managed centrally by IT.
And if the organisation requires the users to make changes then it should be allowed.

So my point is that first recommendation should be not allow users rather than the opposit

regards
Mattias

**Comment by brianlic-msft** [comment]
@Justinha Can you take a look?

**Comment by Justinha** [comment]
@mattiasborg82 thanks for the suggestion. This has been shared with the engineering team for consideration.

**Comment by mattiasborg82** [comment]
Thanks for the quick response! Let me know if you need anything else   Best regards Mattias Borg Sent from E-post for Windows 10 Från: Justin HallSkickat: den 14 december 2017 22:36Till: MicrosoftDocs/windows-itpro-docsKopia: Mattias Borg; MentionÄmne: Re: [MicrosoftDocs/windows-itpro-docs] recommendation in: planning-settings-for-a-basic-firewall-policy (#368) @mattiasborg82 thanks for the suggestion. This has been shared with the engineering team for consideration.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MicrosoftDocs/windows-itpro-docs","title":"MicrosoftDocs/windows-itpro-docs","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MicrosoftDocs/windows-itpro-docs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Justinha in #368: @mattiasborg82 thanks for the suggestion. This has been shared with the engineering team for consideration. "}],"action":{"name":"View Issue","url":"https://github.com/MicrosoftDocs/windows-itpro-docs/issues/368#issuecomment-351843229"}}}
