### ISSUE TITLE
Windows 10 Enterprise LTSC 2019 not listed

### ISSUE THREAD

**Issue by J1mbo** [MicrosoftDocs/windows-itpro-docs#3680]
Windows 10 Enterprise LTSC 2019 "What's new" page states that Windows Defender ATP is included:

https://docs.microsoft.com/en-us/windows/whats-new/ltsc/whats-new-windows-10-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/minimum-requirements-windows-defender-advanced-threat-protection#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-atp/minimum-requirements-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/minimum-requirements-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by computeronix** [comment]
WDATP is built-in to Windows 10.  However, to activate it you need a separate license (Windows E5).  The page is stating what are the new capabilities in WDATP that are built-in to Windows 10.

As the threat landscape changes, new ATP capabilities are rolled out within newer releases of Windows 10.  The What's New pages show what are the new capabilities of ATP that are built-in with Windows 10 and what are supported in the newest release of the OS.   Licensing these capabilities are a separate matter and as long as you have the appropriate license then you can take advantage of these capabilities.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello @J1mbo,

We are closing this issue since your support question seems to be answered. Feel free to re-open this issue if you still feel that the content needs to be updated.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
