### ISSUE TITLE
Odd character in section heading for "Add machine tags by setting a registry key value" heading

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#3681]
The **Add machine tags by setting a registry key value** has an odd character between **tags** and **by** that is rendering as a diamond/question mark.

Add machine tags�by setting a registry key value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b42e708-e334-d434-bcc9-e1860ebb36b3
* Version Independent ID: 92e251c5-8613-ce97-9569-02404c9a466a
* Content: [Create and manage machine tags](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/machine-tags-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/machine-tags-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/machine-tags-windows-defender-advanced-threat-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by martyav** [comment]
I just went in and made a quick edit to the header.
