### ISSUE TITLE
Does LTSC license actually include Defender ATP?

### ISSUE THREAD

**Issue by J1mbo** [MicrosoftDocs/windows-itpro-docs#3683]
Text is fairly ambiguous,

"In this version of Windows, Windows Defender ATP includes powerful analytics, security stack integration, and centralized management for better detection, prevention, investigation, response, and management."

Is this the full version of ATP? In which case does perpetual license also include Windows Defender ATP Portal access?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c696c9ed-b095-68ff-d50d-df345daf8a4a
* Version Independent ID: 50ad3b26-8e9b-6a56-7b3c-56c1374c4747
* Content: [What's new in Windows 10 Enterprise 2019 LTSC](https://docs.microsoft.com/en-us/windows/whats-new/ltsc/whats-new-windows-10-2019#feedback)
* Content Source: [windows/whats-new/ltsc/whats-new-windows-10-2019.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/ltsc/whats-new-windows-10-2019.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by computeronix** [comment]
LTSC does not include the license for Windows Defender ATP.  LTSC however supports WDATP if you have a license.

The What's New document is showing what is new with Windows Defender ATP in Windows 10 Enterprise LTSC 2019 but it doesn't mention the license needed which is Windows E5 to use it.

**Comment by J1mbo** [comment]
Thank you. Can LTSC be deployed with a Windows 10 Enterprise E3 license (e.g. via CSP)?

**Comment by computeronix** [comment]
There is no E5 version of Windows (as far as a special edition). What happens is when you purchase a Windows E5 license you assign it to a user in Azure AD.  From there you get access to the Windows Security Center portal which allows you to download the package needed to activate ATP inside the OS.  Here is the article for how to on-board a Windows 10 device to Windows Defender ATP: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/onboard-configure-windows-defender-advanced-threat-protection

**Comment by J1mbo** [comment]
Thank you so much. So my only question is how to license LTSC.

Machines have Win10-Pro OEM of course. Then we add Win1-Ent-E5 per-user in CSP, re-image from the LTSC image, and activate WDATP?

In other words, there is no need to buy the VL SKU LTSC itself (WINENTLTSC 2019 Sngl Upgrade OLP)?

**Comment by computeronix** [comment]
Licensing is outside my expertise area but you should be able to get with your LAR/VAR to discuss your licensing concerns and they should be able to assist with getting the right license to fit what you are needing

**Comment by J1mbo** [comment]
I'm here because nobody knows unfortunately. Thanks again for your help.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by xNiklasJern** [comment]
I've having the same questions as @J1mbo . I'm having a really hard time trying to figure out how to license this + Windows Defender ATP, even with when in direct contact with Microsoft officials were I live.

**Comment by e0i** [comment]
Hello @J1mbo ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
