### ISSUE TITLE
Application Guard and Office 365 Ransomware Detection Surely Not Compatible

### ISSUE THREAD

**Issue by J1mbo** [MicrosoftDocs/windows-itpro-docs#3684]
LTSC specifically does not support either Edge or Office 365 apps, therefore surely cannot include Application Guard (controls for Edge) or the Office 365 Ransonware Detection (since it's can't run Office 365 apps).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c696c9ed-b095-68ff-d50d-df345daf8a4a
* Version Independent ID: 50ad3b26-8e9b-6a56-7b3c-56c1374c4747
* Content: [What's new in Windows 10 Enterprise 2019 LTSC](https://docs.microsoft.com/en-us/windows/whats-new/ltsc/whats-new-windows-10-2019#feedback)
* Content Source: [windows/whats-new/ltsc/whats-new-windows-10-2019.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/ltsc/whats-new-windows-10-2019.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @J1mbo 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
@greg-lindsay Would you be able to provide clarifications regarding the mentioned features?  We cannot find relevant information as the features have just came out. Thank you in advance.

**Comment by greg-lindsay** [comment]
I've removed the section about ransomware detection. I don't see anything about Application Guard. Note that Application Control is a different feature.
