### ISSUE TITLE
it's a stupid idea to have pin / password 

### ISSUE THREAD

**Issue by zfdang** [MicrosoftDocs/windows-itpro-docs#3686]
why make things so complicated? why stop people from using windows?

**Comment by illfated** [comment]
Ref. **A PIN *is* a password** #2736 (closed)

- Content: [Why a PIN is better than a password (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password)
- Content Source: [windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md)
- Product: w10
- GitHub Login: @DaniHalfin
- Microsoft Alias: daniha

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @zfdang 

The issues section of this repository is intended for documentation and content related issues.

Would you be able to clarify what needs to be updated in the documentation? Is the document misleading?

We would like to follow-up with content updates accordingly.

Thank you for providing feedback.
