### ISSUE TITLE
AutoPilot SDP

### ISSUE THREAD

**Issue by PrinceMarkieD** [MicrosoftDocs/windows-itpro-docs#3689]
During the SDP the company logo that is displayed does not appear correctly. it is stretched, and not sized properly. this does not happen in other scenarios outside of SDP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6867cc8c-868d-d472-8aa5-1ed5b94ced2c
* Version Independent ID: 6822e12d-7474-9e49-1e8b-88f7eec3b22c
* Content: [Windows Autopilot Self-Deploying mode (Preview)](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/self-deploying)
* Content Source: [windows/deployment/windows-autopilot/self-deploying.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/self-deploying.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro
@officedocsbot remove label localization

**Comment by e0i** [comment]
@PrinceMarkieD 

The issues section of this repository is intended for documentation issues only.

Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience. Find the link to Feedback Hub below:

[Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
