### ISSUE TITLE
[LOC] "困難な脅威を削除します。" needs to be replaced with "マルウェアの検出と削除に関する問題のトラブルシューティング"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3692]
https://docs.microsoft.com/ja-jp/windows/security/threat-protection/intelligence/safety-scanner-download

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f5bb1ce3-9128-5385-4417-d22eb5f8cb77
* Version Independent ID: cb6ba731-a2c2-e9b9-7c3e-db781b1b5222
* Content: [Microsoft Safety Scanner のダウンロード](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/intelligence/safety-scanner-download)
* Content Source: [windows/security/threat-protection/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/intelligence/safety-scanner-download.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by illfated** [comment]
Translation by web tool: "Deleting difficult threats." needs to be replaced with "Troubleshooting Malware Detection and Removal Issues"

**Comment by hyoshioka0128** [comment]
https://docs.microsoft.com/ja-jp/windows/security/threat-protection/intelligence/safety-scanner-download
![safety-scanner-download](https://user-images.githubusercontent.com/40815708/57825114-7882f380-77d8-11e9-8530-815c45bd5a8e.png)

https://support.microsoft.com/ja-jp/help/4466982/windows-10-troubleshoot-problems-with-detecting-and-removing-malware
![windows-10-troubleshoot-problems-with-detecting-and-removing-malware](https://user-images.githubusercontent.com/40815708/57825192-c861ba80-77d8-11e9-808f-85fa9b2b2ae4.png)

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@dongmicro Would you be able to assist with this Japanese localization issue? Thanks.

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot unassign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
Thanks for the feedback @hyoshioka0128
Set the topic to be human translated, will take 2-3 weeks to process

**Comment by TinaMcN** [comment]
記事は現在、人間翻訳されており、問題は修正されているようです。 修正済みであることを確認してください。 フィードバックをありがとうございました。
(The article is now human translated and the issue appears to be fixed.  Please verify that it is fixed.  Thanks again for the feedback.)

**Comment by illfated** [comment]
Looks like the link text 
困難な脅威を削除します。has been replaced by
困難な脅威の削除 (https://support.microsoft.com/help/4466982/windows-10-troubleshoot-problems-with-detecting-and-removing-malware)
although I don't know Japanese kanji well enough to see if it is correct.

I hope @hyoshioka0128 can provide feedback whether this is correct now.

**Comment by hyoshioka0128** [comment]
@TinaMcN  @illfated -  This is correct .
The translation of "Removing difficult threats" is okay because it is "困難な脅威の削除".
Closed #3692.
Thanks.
