### ISSUE TITLE
ADK - 19H1 - Known Issues Section (ADK 10.0.18362.1 + KB4497936 18362.113)

### ISSUE THREAD

**Issue by NeoBeum** [MicrosoftDocs/windows-itpro-docs#3699]
The Deployment Section for IT Pro Docs may require a detailed Release Info page, and have Known Issues expanded.

https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install

https://docs.microsoft.com/en-us/windows-hardware/get-started/what-s-new-in-kits-and-tools

ADK is currently failing installing the 14/MAY/2019 LCU KB4497936 on the Windows Recovery Image.
**It is also operating dangerously**, as it unmounts the Working Image, and continues Add-Package operation using the Host System Registry Hive.

DISM.log (Pt I)
https://pastebin.com/0gWMcaLT

DISM.log (Pt II) Registry Overlap
https://pastebin.com/RrGTdBU0

DISM.log (Pt III)
https://pastebin.com/Y6tQnyax

```
PS E:\WinROG> DISM /Mount-Image /ImageFile:winre.wim /Index:1 /MountDir:mount\RE                                                                                                                                                             
Deployment Image Servicing and Management tool
Version: 10.0.18362.1

Mounting image
[==========================100.0%==========================]
The operation completed successfully.
PS E:\WinROG> DISM /Image:mount\RE /Add-Package /PackagePath:"\\Nb-domain-hq\hq-hdd\1903\2019-05\windows10.0-kb4500109-x64_b727d70aacc30ac3522c02b285164d908e818ad6.msu"                                                                     
Deployment Image Servicing and Management tool
Version: 10.0.18362.1

Image Version: 10.0.18362.30

Processing 1 of 1 - Adding package \\Nb-domain-hq\hq-hdd\1903\2019-05\windows10.0-kb4500109-x64_b727d70aacc30ac3522c02b285164d908e818ad6.msu
[==========================100.0%==========================]
The operation completed successfully.
PS E:\WinROG> DISM /Image:E:\WinROG\mount\RE /Add-Package /PackagePath:"E:\WinROG\windows10.0-kb4497936-x64_4ac9328bb1376d2cadb09f56ba95ac9b08b88fba.msu"                                                                                    
Deployment Image Servicing and Management tool
Version: 10.0.18362.1

Image Version: 10.0.18362.30

Processing 1 of 1 - Adding package E:\WinROG\windows10.0-kb4497936-x64_4ac9328bb1376d2cadb09f56ba95ac9b08b88fba.msu
[==========================100.0%==========================]
E:\WinROG\windows10.0-kb4497936-x64_4ac9328bb1376d2cadb09f56ba95ac9b08b88fba.msu: An error occurred applying the Unattend.xml file from the .msu package.
For more information, review the log file.
 Error: 0x80070002

Error: 2

The system cannot find the file specified.

The DISM log file can be found at C:\WINDOWS\Logs\DISM\dism.log

PS E:\WinROG> DISM /Image:E:\WinROG\mount\RE /Add-Package /PackagePath:"E:\WinROG\windows10.0-kb4497936-x64_4ac9328bb1376d2cadb09f56ba95ac9b08b88fba.msu"                                                                                    
Deployment Image Servicing and Management tool
Version: 10.0.18362.1


Error: 50

DISM does not support servicing a Windows Vista RTM or earlier operating system.
If the operating system is supported check that SSShim.DLL is present.

The DISM log file can be found at C:\WINDOWS\Logs\DISM\dism.log

```

The concerning error code: DISM does not support servicing a **Windows Vista RTM** or earlier operating system.

This may possibly have adverse effect for online installation scheduled maintenance, where Winre.wim is required for component cleanup.
```
DISM /Online /Cleanup-Image /StartComponentCleanup /ResetBase
```

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@NeoBeum Thank you for providing details about the problem that you are experiencing.

Could you clarify the subject of your request regarding associated documentation? 

The issues section of this repository is intended for documentation and content related issues and any documentation feedback is welcome.

**Comment by NeoBeum** [comment]
@e0i 

The ADK Documents would benefit from having a release information section, similar to the OS Release Info pages: https://docs.microsoft.com/en-au/windows/release-information/

This will give a better overview of issues for the ADK.
From memory, ADK 1703 had an update after the initial release, however it wasn't mentioned at the download pages at the time, and also hidden away in a dev post on technet.
.. found the post..
https://techcommunity.microsoft.com/t5/Configuration-Manager-Archive/Known-Issue-with-the-Windows-ADK-for-Windows-10-version-1703/ba-p/274213
.. and the 1703 page...
[Imgur](http://i.imgur.com/9uTFnER.jpg)

No reference for it.

I hope I explained the suggestion. I can give more examples if not

**Comment by e0i** [comment]
@NeoBeum 

This feedback seems to be related to [Windows Hardware](https://docs.microsoft.com/en-us/windows-hardware/) documentation rather than IT Pro. The repository for Windows Hardware documentation is currently not open to public edits and commentary via GitHub in a way similar to this repository.

I have nonetheless shared your feedback via appropriate channels and I hope your valuable feedback gets addressed. Thank you.
