### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by joejony** [MicrosoftDocs/windows-itpro-docs#3701]
Here, in this text, is a broken link: see Protect your enterprise data using Windows Information Protection (WIP). It is missing a /

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca51bc21-babf-9810-e26a-360e53cfbac2
* Version Independent ID: c24d6198-d249-3331-5460-5472bcbfe31e
* Content: [Configure information protection in Windows](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/information-protection-in-windows-config#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-atp/information-protection-in-windows-config.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/information-protection-in-windows-config.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
This is the text & link from the page:
> Define a WIP policy and assign it to the relevant devices. For more information, see [Protect your enterprise data using Windows Information Protection (WIP)](https://docs.microsoft.com/windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip). If WIP is already configured on the relevant devices, skip this step.

- https://docs.microsoft.com/windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip

The link works just fine for me, I don't see the problem.
According to you, where is the "missing" slash ( `/` ) needed?

**Comment by nenonix** [comment]
Link works for me too

**Comment by joejony** [comment]
The defective link is: 

Your tenant needs to be onboarded to Azure Information Protection analytics, for more information see, Configure a Log Analytics workspace for the reports

https://docs.microsoft.comazure/information-protection/reports-aip#configure-a-log-analytics-workspace-for-the-reports

The correct should be: 
https://docs.microsoft.com/azure/information-protection/reports-aip#configure-a-log-analytics-workspace-for-the-reports

Was missing a / between docs.microsoft.com and azure in the link

**Comment by illfated** [comment]
Thank you, that is a different link (and it is indeed broken).

> ### [**Prerequisites**](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/information-protection-in-windows-config#prerequisites)
>- Endpoints need to be on Windows 10, version 1809 or later
>- You'll need the appropriate license to leverage the Microsoft Defender ATP and Azure Information Protection integration
>- Your tenant needs to be onboarded to Azure Information Protection analytics, for more information see, [Configure a Log Analytics workspace for the reports](https://docs.microsoft.comazure/information-protection/reports-aip#configure-a-log-analytics-workspace-for-the-reports)

**Comment by e0i** [comment]
@mjcaparas Would you be able to merge this PR that contains a minor URL fix that is contributed by community? Thanks.

**Comment by e0i** [comment]
@illfated As always, Thank you for your generous contributions Trond. Much appreciated.

**Comment by illfated** [comment]
Please note that the **Github link** in the [first issue comment](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3701#issue-444511286) is wrong, it is based on the old name "Windows Defender ATP" which has been renamed to Microsoft Defender ATP:
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/information-protection-in-windows-config.md (404 - page not found)
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/information-protection-in-windows-config.md (current working page)
