### ISSUE TITLE
Some confusion about reasoning to enable Device Writeback

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/windows-itpro-docs#3713]
Hope I can ask a question on functionality and some confusion from my part after reading the documentation here:

The document above states: "Hybrid certificate trust deployments need the device write back feature. Authentication to the Windows Server 2016 Active Directory Federation Services needs both the user and the computer to authenticate. Typically the users are synchronized, but not devices. This prevents AD FS from authenticating the computer and results in Windows Hello for Business certificate enrollment failures. For this reason, Windows Hello for Business deployments need device writeback, which is an Azure Active Directory premium feature."

What I understand now, is that in order for WHfB to work on Hybrid AD joined devices (AD joined/AAD registred) you must configure Certificate Trust. So far, so good. The documentation is unclear to me on some parts.

1. Authentication to the Windows Server 2016 Active Directory Federation Services needs both the user and the computer to authenticate. 

In a Hybrid AD joined device, the computer we are talking about is already AD joined correct? Why would we need Device writeback then? There is already a computer object in the AD, which as far as I can understand should be able to authenticate against ADFS - or is this assumption wrong?

2. Typically the users are synchronized, but not devices
Users are synchronized from AD to AAD, devices can be registered making them available as an object in AAD. This sentense is very confusing since users are synchronized in a Hybrid scenario (which makes sense) and devices are registred directly in AAD, or must they be synchronized first using AzureAD connect before you can register them in the Hybrid join scenario?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02eda72c-ccd2-e8d8-4f7e-6edf95b79408
* Version Independent ID: be08aee5-2403-c131-0f39-005e1271d5f1
* Content: [Hybrid Windows Hello for Business Prerequistes (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by lindspea** [comment]
@kennethvs Thank you for reaching out and helping improve MS Docs.  Please have a look at this article and let me know if it provides some clarity on your questions - https://docs.microsoft.com/azure/active-directory/devices/hybrid-azuread-join-federated-domains. If you have any suggestions to improving the document for clarity please let me know as well.

**Comment by kennethvs** [comment]
Hi @lindspea, thanks for you comment. After reading the link you provided and re-reading the page again I came to the conclusion that it **didn't** answer my questions unfortunately.

**Comment by nickekallen** [comment]
See my other feedback aswell, however:
WHfB is tied between a user and a device. As both the user and the device needs to be synchronized between AAD and AD - the device write back is used to update the msDS-KeyCredentialLink on the computer object.

**Comment by kennethvs** [comment]
Thanks @nickekallen, would be great to have this reflected in the documentation.

Regards,

Kenneth

**Comment by lindspea** [comment]
Thank you, @nickekallen.. I have added it to the documentation, thanks @kennethvs. It will take a few days to reflect.
