### ISSUE TITLE
Testing steps | Adjust WIP protection policy

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#3714]
Hello,
Seems using Microsoft Monitoring Agent we can retrieve event log: "Microsoft-Windows-EDP-Application-Learning/Admin",
From AAD joined or ADD registered + MDM Enrolled devices, some discussion in: https://github.com/MicrosoftDocs/azure-docs/issues/31097

Maybe could be added here as alternative solution like: "Use Microsoft Monitoring Agent and Intune to adjust WIP protection policy".

During tests I see that Device Health is more complicated setup than installing "Log Workspace and Microsoft Monitoring Agent"

Is it possible that we initialize review from product team, to see if using Microsoft Monitoring Agent solution, can be really used here for adjusting WIP protection policy / WIP Learning?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e35d03-23d6-e006-b083-582bd33d4ae4
* Version Independent ID: 7ab70933-c45e-c601-548b-07ad0c89cd59
* Content: [Fine-tune Windows Information Protection (WIP) with WIP Learning](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/wip-learning)
* Content Source: [windows/security/information-protection/windows-information-protection/wip-learning.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/wip-learning.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @lightupdifire 

Would you be able to clarify what needs to be updated in the documentation? Is the document misleading?

We would like to follow-up with content updates accordingly.

Thank you for providing feedback.

**Comment by lightupdifire** [comment]
Hello @e0i,

This document explains "how to adjust WIP protection policy using Device Health",
But there is an alternative way to do so, using Log Analytics Workspace and Microsoft Monitoring Agent..

So do you want to deploy Device Health that require Device Reliability, Upgrade Readiness, Update Compliance, Windows 10 E3/E5 license etc. to get WIP logs for adjusting WIP policy?
Or deploy only Workspace and MMA?

**Comment by joinimran** [comment]
@lightupdifire  the link you have mentioned has still not under working. That being said is there any specific contents that you want to be added in this document. Let me know and if required I can update the content and send your suggestion to the doc owner.

Regards
Imran

**Comment by lightupdifire** [comment]
@joinimran 
Using Microsoft tools, I found alternative way, how to retrieve WIP data from devices, so without Device Health.
I could also set a monitoring and trigger alert, when WIP protection removed from more than 100 files.
If you think this information shouldn't be available, then yes, we shouldn't update this document.
