### ISSUE TITLE
MS 365 E3 With E5 Security Add-on

### ISSUE THREAD

**Issue by rstgermain** [MicrosoftDocs/windows-itpro-docs#3718]
For licensing requirements couldn't you also have Microsoft 365 E3 with the E5 security add-on? This would help me convince our licensing people.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by jimhill10** [comment]
I agree. We too use the Security E5 add on and already have Windows 10 Enterprise for every user.   Moving to an enterprise license for Windows E5 does not make sense for us.  So for now we will live without the Defender ATP.

**Comment by e0i** [comment]
@rstgermain 

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience. Find the link to Feedback Hub below:

[Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by jonwbstr** [comment]
Why was this closed? The feedback is for a page containing a section titled "License Requirements" which reads as follows:

>  Microsoft Defender Advanced Threat Protection requires one of the following Microsoft Volume Licensing offers:
>
>  - Windows 10 Enterprise E5
>  - Windows 10 Education E5
>  - Microsoft 365 E5 (M365 E5) which includes Windows 10 Enterprise E5

This section of the article where feedback is being submitted is incorrect. Please update the section as follows:

>  Microsoft Defender Advanced Threat Protection requires one of the following Microsoft Volume Licensing offers:
>
>  - Windows 10 Enterprise E5
>  - Windows 10 Education E5
>  - Microsoft 365 E5 (M365 E5) which includes Windows 10 Enterprise E5
>  - Microsoft 365 E3 with Microsoft 365 E5 Security Add-on (which includes WIndows 10 Enterprise E5?)

Here's the official annoucement
https://www.microsoft.com/en-us/microsoft-365/blog/2019/01/02/introducing-new-advanced-security-and-compliance-offerings-for-microsoft-365/

And here's a translation that is a bit easier to read and digest
https://thirdspace.net/blog/microsoft-365-licensing-update-e5-level-security/

**Comment by jonwbstr** [comment]
Hmm, I'm finding multiple closed issues related to this. #5001 was merged 2 months ago and the change committed is not reflected on the live page for me.

**Comment by e0i** [comment]
> Why was this closed? The feedback is for a page containing a section titled "License Requirements" which reads as follows:
> 
> > Microsoft Defender Advanced Threat Protection requires one of the following Microsoft Volume Licensing offers:
> > 
> > * Windows 10 Enterprise E5
> > * Windows 10 Education E5
> > * Microsoft 365 E5 (M365 E5) which includes Windows 10 Enterprise E5
> 
> This section of the article where feedback is being submitted is incorrect. Please update the section as follows:
> 
> > Microsoft Defender Advanced Threat Protection requires one of the following Microsoft Volume Licensing offers:
> > 
> > * Windows 10 Enterprise E5
> > * Windows 10 Education E5
> > * Microsoft 365 E5 (M365 E5) which includes Windows 10 Enterprise E5
> > * Microsoft 365 E3 with Microsoft 365 E5 Security Add-on (which includes WIndows 10 Enterprise E5?)
> 
> Here's the official annoucement
> https://www.microsoft.com/en-us/microsoft-365/blog/2019/01/02/introducing-new-advanced-security-and-compliance-offerings-for-microsoft-365/
> 
> And here's a translation that is a bit easier to read and digest
> https://thirdspace.net/blog/microsoft-365-licensing-update-e5-level-security/

@mjcaparas It seems that you have reverted the merged contents that you have approved. Would you be able to provide clarifications or suggest a way to move forward with this issue? Thanks.



See also comments via follow-up issue: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5454

*jonwbstr* commented:
> The License Requirements section was updated to include a licensing change that happened earlier this year. I see that the change was committed several months ago and reverted recently.
> 
> [2b66253#diff-6701b7a2e1253d31a8b2d4eae1e26628](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/2b66253419958a0ce03431b885290a05f1faa43e#diff-6701b7a2e1253d31a8b2d4eae1e26628)
> 
> Please re-add the M365 E3 with Security Addon licensing option to this page. I added additional comments to issue #3718.
> 
> The official announcement calls it the "Identity & Threat Protection" add-on available for M365 E3. The product catalog has it listed as "Microsoft 365 E5 Security" and it is an add-on to the M365 E3 product.
> 
> This page really should include the most recently introduced method for licensing Microsoft Defender ATP.

**Comment by woodyard** [comment]
I fail to understand the requirements. It says that Windows 10 Enterprise E5 is required - but the part about supported Windows versions, says that Windows 10 Pro, Windows 8.1 and Windows 7 are supported. Please explain :-)

**Comment by jonwbstr** [comment]
Hi Henrik,

Microsoft Defender ATP is a licensed product available in several licenses.
It's not a question of supported versions.
