### ISSUE TITLE
Update needed for Automatic Redeployment wording

### ISSUE THREAD

**Issue by tidoel** [MicrosoftDocs/windows-itpro-docs#372]
https://docs.microsoft.com/en-us/education/windows/windows-automatic-redeployment

OMA-URI: ./Vendor/MSFT/Policy/Config/CredentialProviders/DisableAutomaticReDeploymentCredentials
Data type: Boolean
Value: 1

Needs to be updated so that "Data type: Integer" & "Value: 0"

It does not currently work with the Boolean values.

**Comment by CelesteDG** [comment]
Reviewed Tim's comments. Thank you for the feedback, Tim.

**Comment by CelesteDG** [comment]
Hi Tim - I don't see a PR from you so I'll go ahead and make this change on our end.

**Comment by brianlic-msft** [comment]
@CelesteDG Let me know when the change is live and I'll close this issue.

**Comment by brianlic-msft** [comment]
@tidoel This should be fixed now. Thanks!
