### ISSUE TITLE
GP setting "Prevent enterprise websites from loading non-enterprise content..." in 1809 does not match docs

### ISSUE THREAD

**Issue by joestern** [MicrosoftDocs/windows-itpro-docs#3720]
The documentation above mentions a setting named "Block enterprise websites to load non-enterprise content in IE and Edge" that also seems to have an "Allowed Apps" list. The setting that comes with the 1809 ADMX/ADML has a different name (beginning with "Prevent" instead of "Block") and it does not have an allowed apps list. There is no obvious way to add sites to an enterprise list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41a8c802-79ca-1593-c045-2ed150e9ce40
* Version Independent ID: 3dabd613-2eee-7c65-6f30-6746c8fb5bdf
* Content: [Configure the Group Policy settings for Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/configure-wd-app-guard#application-specific-settings)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/configure-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/configure-wd-app-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by lindspea** [comment]
@joestern Thank you for pointing this out.  Are you suggesting changing/removing something in this doc or are you referring to another article?  I see the setting regarding 'Block enterprises...' in this doc, but can't see the reference to 1809.

**Comment by e0i** [comment]
@joestern  We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.

Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by e0i** [comment]
@officedocsbot reopen

**Comment by e0i** [comment]
@joestern 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
