### ISSUE TITLE
ConsentPromptBehaviorUser

### ISSUE THREAD

**Issue by tunnelofsludge** [MicrosoftDocs/windows-itpro-docs#3724]
On Windows 10 1809 Pro, this setting is set to 1 instead of 3 if the slider in the UAC Control Panel applet is set at the Default level. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38066882-5022-1f08-3565-c13041b10921
* Version Independent ID: 30a904f6-64ce-2d03-f9b1-721f75b8a106
* Content: [User Account Control Group Policy and registry key settings (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/user-account-control-group-policy-and-registry-key-settings#feedback)
* Content Source: [windows/security/identity-protection/user-account-control/user-account-control-group-policy-and-registry-key-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/user-account-control/user-account-control-group-policy-and-registry-key-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by RAJU2529** [comment]
This  registry key   ConsentPromptBehaviorUser   1 = Prompt for credentials on the secure desktop  is  correct . I was enabled and checked in  gpo and in registry setted to 1

**Comment by e0i** [comment]
Hello, @tunnelofsludge 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.

**Comment by Malind19** [comment]
@e0i , What is mentioned in the article is correct for the other versions as per this article. The reporter mentions this is specific to a one version. Can we get some team support?

https://www.ghacks.net/2013/06/20/how-to-configure-windows-uac-prompt-behavior-for-admins-and-users/

**Comment by e0i** [comment]
Hello @tunnelofsludge  ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
