### ISSUE TITLE
Firewall or proxy? 

### ISSUE THREAD

**Issue by PrinceMarkieD** [MicrosoftDocs/windows-itpro-docs#3727]
Should this be used instead of the proxy with exceptions to control web traffic and network access? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfea4e59-ec8c-cbdf-a039-23612c2266a5
* Version Independent ID: 7058544b-7ef2-a398-366a-cf71520aa9d8
* Content: [Firewall CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/firewall-csp#feedback)
* Content Source: [windows/client-management/mdm/firewall-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/firewall-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @PrinceMarkieD 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by Malind19** [comment]
@e0i , Use of Proxy and Firewall serves different purposes. So cannot really say Firewall can replace a proxy.

**Comment by Malind19** [comment]
@PrinceMarkieD the firewall CSP has certain features for controlling web traffic as well. Still the purpose of both are different. Please refer the Network Proxy CSP article [here](https://docs.microsoft.com/en-us/windows/client-management/mdm/networkproxy-csp).

**Comment by e0i** [comment]
Hello @PrinceMarkieD,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
