### ISSUE TITLE
Incorrect URL Redirection

### ISSUE THREAD

**Issue by aamer-s** [MicrosoftDocs/windows-itpro-docs#3728]
The URL to "Implementing Windows Hello For Business" leads to https://www.microsoft.com/en-us/itshowcase which is incorrect.
THe URL itself is: https://www.microsoft.com/itshowcase/Article/Content/830/Implementing-Windows-Hello-for-Business-at-Microsoft but it doesn't seemt o find the relevcant article and ends up at https://www.microsoft.com/en-us/itshowcase

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f8d124-fd83-f3ab-8249-d11d5967460f
* Version Independent ID: eace54c8-04c9-a717-5ecd-2be8f485cc93
* Content: [Windows Hello for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-overview#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
Looks like the URL target page has been removed or renamed:
- https://www.microsoft.com/en-us/itshowcase/implementing-windows-hello-for-business-at-microsoft
(https://www.microsoft.com/itshowcase/Article/Content/830/Implementing-Windows-Hello-for-Business-at-Microsoft)

Can you confirm if the page I found looks like the correct new target for the "broken" link, so we can open a PR to repair it?

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by dongmicro** [comment]
Is this about the localization or about URL? I contacted the Showcase people, the URL I got is https://www.microsoft.com/en-us/itshowcase/implementing-windows-hello-for-business-at-microsoft, and I was told that they don't have localization for the pages for Showcase.

**Comment by illfated** [comment]
Thank you for the useful feedback, that cleared up my doubts about what seems to be only a wrong URL for the Showcase page. Would it be approvable if I create a PR for using the en-us page only ([**Implementing Windows Hello for Business at Microsoft**](https://www.microsoft.com/en-us/itshowcase/implementing-windows-hello-for-business-at-microsoft) / https://www.microsoft.com/en-us/itshowcase/implementing-windows-hello-for-business-at-microsoft)?

**Comment by dongmicro** [comment]
I am not sure since I am not the member for itshowcase. You can give it a try, I think.
