### ISSUE TITLE
Testing Steps

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#3730]
Hello,
If we deploy Upgrade Readiness, does it block any current Windows Updates process?
As example now updates set on Windows 10 PC's to run automatically, used Intune Delivery Optimization profile & Software Update rings,
If we will deploy Upgrade Readiness, does all updates stop work until we follow steps and go to "Step 3 Deploy updates"?
Or all current Windows Updates will be continue working process as they are now (using automatic update settings) and then Upgrade Readiness is more like optional solution to control Windows Updates issues?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6dc80d9-7606-664b-d292-9909c7793484
* Version Independent ID: 096e6a8d-600f-dae6-57fe-a8509cabbf4e
* Content: [Manage Windows upgrades with Upgrade Readiness (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/manage-windows-upgrades-with-upgrade-readiness)
* Content Source: [windows/deployment/upgrade/manage-windows-upgrades-with-upgrade-readiness.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/manage-windows-upgrades-with-upgrade-readiness.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by lindspea** [comment]
@lightupdifire Thank you for reaching out and helping improve MS Docs.  Please see this latest article on Upgrade Readiness and let me know if it helps answer your questions.  I can have the link added to this article for other users if you think it would help them as well - https://docs.microsoft.com/windows/deployment/upgrade/use-upgrade-readiness-to-manage-windows-upgrades.

**Comment by lightupdifire** [comment]
@lindspea Thanks for information, let me try ask in a different way:
If we deploy Upgrade Readiness and stop use it after it is deployed, is it possible that updates will be stopped on devices until someone follow all steps 1-2-3 from Upgrade Readiness ?
Or all updates continue works as they were before Upgrade Readiness deployment in a tenant?

Asking because we plan deployment of Device Health, that could give us information regards WIP, but in Device Health article, the Upgrade Readiness is in perquisites.. So idea is to deploy Upgrade Readiness for Device Health, but for Windows Updates delivery we just want to keep for a moment solution with standard options:
1. Intune policy to apply update release and settings -> Software Rings
2. Intune policy for delivery optimization

**Comment by lindspea** [comment]
@lightupdifire I'll investigate some more with the team and get back to you as soon as possible.

**Comment by lindspea** [comment]
@lightupdifire Sorry for the delay, I'm still investigating with the team to help answer your questions. In the meantime here is a new article that was added recently. https://docs.microsoft.com/windows/deployment/upgrade/upgrade-readiness-get-started.

**Comment by e0i** [comment]
> @lindspea Thanks for information, let me try ask in a different way:
> If we deploy Upgrade Readiness and stop use it after it is deployed, is it possible that updates will be stopped on devices until someone follow all steps 1-2-3 from Upgrade Readiness ?
> Or all updates continue works as they were before Upgrade Readiness deployment in a tenant?
> 
> Asking because we plan deployment of Device Health, that could give us information regards WIP, but in Device Health article, the Upgrade Readiness is in perquisites.. So idea is to deploy Upgrade Readiness for Device Health, but for Windows Updates delivery we just want to keep for a moment solution with standard options:
> 
>     1. Intune policy to apply update release and settings -> Software Rings
> 
>     2. Intune policy for delivery optimization

@greg-lindsay Would you be able to shed light on this question if possible? Thank you.

**Comment by jaimeo** [comment]
@Deepamdubey is the person who can actually answer this question.

**Comment by Deepamdubey** [comment]
No, it doesn't. You have complete control of your deployments and they work as configured within your organization. So your windows updates or Intune delivery settings will not be impacted if you onboard to Windows or Desktop Analytics. As, mentioned none of the deployments will happen automatically until initiated.

**Comment by lightupdifire** [comment]
Thanks for info! Will proceed with deployment.
