### ISSUE TITLE
Secure Score Update Frequency

### ISSUE THREAD

**Issue by AndrewEmmett** [MicrosoftDocs/windows-itpro-docs#3738]
It would be useful to know what the expected update schedule of Secure Score is. It seems to sometimes be 1 day, but on other occasions up to 3 days. When I comes to updates, the currency of this information would be really helpful. Guidance for admins would be helpful...

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e17e8994-077f-4042-b478-edbbc23a5687
* Version Independent ID: 847bfd6e-eaf0-acf3-d57e-f5c1fbcdad70
* Content: [Overview of Secure score in Microsoft Defender Security Center](https://docs.microsoft.com/en-gb/windows/security/threat-protection/microsoft-defender-atp/overview-secure-score#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/overview-secure-score.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/overview-secure-score.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by schenardie** [comment]
Second that

**Comment by e0i** [comment]
Hello, @AndrewEmmett 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by ojrb** [comment]
This issue is solved by the PR #4439 please @e0i review and merge !

**Comment by e0i** [comment]
@AndrewEmmett 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
