### ISSUE TITLE
Step 1: Create an application in Azure Active Directory (Azure AD) - needs rewriting due to portal makeover

### ISSUE THREAD

**Issue by rwx-mrx** [MicrosoftDocs/windows-itpro-docs#3739]
This step does not reflect current UI in AAD portal anymore. I tried to figure out the right steps myself but subsequent steps fail and now i'm not sure if i've done anything wrong :)

https://docs.microsoft.com/nl-nl/windows/security/threat-protection/microsoft-defender-atp/configure-mssp-support#step-1-create-an-application-in-azure-active-directory-azure-ad

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 79be1cc1-eaf6-15b7-d2fa-696fc4c5a709
* Version Independent ID: 66a6394c-a351-dee8-6f7d-81cf2634d1ef
* Content: [Configure managed security service provider support](https://docs.microsoft.com/nl-nl/windows/security/threat-protection/microsoft-defender-atp/configure-mssp-support#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-mssp-support.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/configure-mssp-support.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @rwx-mrx 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.

**Comment by e0i** [comment]
@rwx-mrx 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
