### ISSUE TITLE
Cmdlets contain undefined variables

### ISSUE THREAD

**Issue by czrik** [MicrosoftDocs/windows-itpro-docs#3746]
Set-Mailbox $acctUpn -Type Regular
Set-CASMailbox $acctUpn -ActiveSyncMailboxPolicy $easPolicy
Set-Mailbox $acctUpn -Type Room
Set-Mailbox $credNewAccount.UserName -RoomMailboxPassword $credNewAccount.Password -EnableRoomMailboxAccount $true

These variables have been copied from the script: https://docs.microsoft.com/en-us/surface-hub/appendix-a-powershell-scripts-for-surface-hub#create-on-premises-ps-scripts
If a user would like to run the cmdlets by hand, copying them from this article, cmdlets will not work. 

Please update by mentioning the variables or full cmdlets that will work 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dda01aa0-b7f1-6cdb-44c8-56fe240e4a16
* Version Independent ID: 75948a94-880f-036b-d293-94dcaf146cda
* Content: [On-premises deployment single forest (Surface Hub)](https://docs.microsoft.com/en-us/surface-hub/on-premises-deployment-surface-hub-device-accounts#feedback)
* Content Source: [devices/surface-hub/on-premises-deployment-surface-hub-device-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/on-premises-deployment-surface-hub-device-accounts.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @czrik 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
@czrik 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
