### ISSUE TITLE
WIP and OWA

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#3747]
Hello,
I guess need add ".office.net" / "attachments.office.net" into Enterprise Cloud Resources.
If we deploy Exchange Conditional Access policy, then on Compliant device, if try save file from OWA, file will be saved from "attachments.office.net", then no WIP applied.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 255d1c9b-6b79-cb49-c230-84570daae489
* Version Independent ID: a2dcf5fd-c20d-c219-13f9-3e936036b368
* Content: [Recommended Enterprise Cloud Resources and Neutral Resources network settings with Windows Information Protection (WIP) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/recommended-network-definitions-for-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/recommended-network-definitions-for-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/recommended-network-definitions-for-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @lightupdifire 

Would you be able to clarify what needs to be updated in the documentation? Is the document misleading?

We would like to follow-up with content updates accordingly.

Thank you for providing feedback.

**Comment by lightupdifire** [comment]
Hello @e0i,
Not sure if this will be for this article or maybe for:
https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/using-owa-with-wip

But situation is:
1. If you deploy Exchange Conditional Access Policy, then when you try save file from Outlook Web Access from Compliant device, file will be saved from: "attachments.office.net"
2. If this DNS not added to *Enterprise Cloud Resources* then file will be not Encrypted

So in this doc I would add maybe additional 2x parts:

1. Recommended  *Enterprise Cloud Resources* if SharePoint Online Conditional Access applied in tenant, then recommended to add: |.svc.ms|.officeapps.live.com|
This is because if device is Compliant, saving option is allowed, then if you open file via Office Online, you can select option "Save as" with options Save as PDF, Save as ODT etc. or select multiple files and save as ZIP, using those saving options it will generate files from DNS: .svc.ms or .officeapps.live.com

2. Recommended  *Enterprise Cloud Resources* if Exchange Online Conditional Access applied in tenant, 
then recommended to add: |attachments.office.net|
This is because if device is Compliant, saving option is allowed, when save file from Outlook Web Access it will be saved from this DNS: attachments.office.net

Or can have completely separate article like *Exchange & SharePoint Online Conditional Access policy works with WIP*

**Comment by lightupdifire** [comment]
Hello @e0i,
Updated my comment, I see now added part regards SharePoint Online, so removed from comment ;)

**Comment by illfated** [comment]
The PR has been merged into the master branch 8 hours ago (as of the time of this comment).
I presume this means the docs.microsoft.com pages will be updated within a few days.
I also presume this allows for this issue ticket to be closed, unless disputed.

**Comment by e0i** [comment]
@lightupdifire 

With the help of your feedback, the content has been updated with relevant changes accordingly. 

As **illfated** has mentioned, it will take a few days changed content to go live.

Thanks.
