### ISSUE TITLE
Block inheritance

### ISSUE THREAD

**Issue by SirJewDanielBerg** [MicrosoftDocs/windows-itpro-docs#3748]
Hi.

What this article doesn't clarify is whether setting "Block inheritance" on a OU will then block any other GPOs outside that OU, for example, a user logon script GPO applied to a user in a completely different parent OU that logs into a machine located in an OU that has block inheritance turned on. I would think that every other GPO would be blocked from that OU going up, and even any other GPOs from any other OUs that are at the same level as the parent OU of the sub-OU that has blocked inheritance turned on.

Is that correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9530a35b-23e4-fcc9-bb1f-b4954bb597d0
* Version Independent ID: e4e678b7-3d27-8cd2-a3a7-0c14056e8f79
* Content: [Security policy settings (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/security-policy-settings)
* Content Source: [windows/security/threat-protection/security-policy-settings/security-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/security-policy-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@Justinha Would you be able to provide directions in clarifying this questions if the time permits? Thank you.

**Comment by Justinha** [comment]
@SirJewDanielBerg Thanks for the feedback and sorry for delay. Yes, you are right. If you want to submit a pull request for this, we can review and merge. To my mind, the point you are raising is more relevant to a topic about how GP works rather than any specific Security Option policy. Maybe add a link to https://blogs.technet.microsoft.com/musings_of_a_technical_tam/2012/02/15/group-policy-basics-part-2-understanding-which-gpos-to-apply/ for example?

**Comment by lindspea** [comment]
@SirJewDanielBerg Thank you for reaching out to help improve MS Docs.  Please let me know if the link from @Justinha helps answer your questions, and I will have the link added to the article.

**Comment by e0i** [comment]
@SirJewDanielBerg 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
