### ISSUE TITLE
Set-CimInstance fails

### ISSUE THREAD

**Issue by euphoric85** [MicrosoftDocs/windows-itpro-docs#3750]
Doing exactly as described here on a Win10 Pro 1809 machine results in error:

Set-CimInstance : A general error occurred that is not covered by a more specific error code.
At ******
+ Set-CimInstance -CimInstance $obj
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MDM_AssignedAcc..../Vendor/MSFT"):CimInstance) [Set-CimInstance], CimException
    + FullyQualifiedErrorId : MI RESULT 1,Microsoft.Management.Infrastructure.CimCmdlets.SetCimInstanceCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f536979-dfd7-317d-2da7-c40935d85c7f
* Version Independent ID: c23737a1-c71e-3d9c-3915-c6929a23602e
* Content: [Use MDM Bridge WMI Provider to create a Windows 10 kiosk (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/kiosk-mdm-bridge#feedback)
* Content Source: [windows/configuration/kiosk-mdm-bridge.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-mdm-bridge.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
I wonder if the code content has been created in some form of HTML editor, converting any special characters like ` < `, ` " ` and ` > ` to shorthand names for those codes.
Would it be reasonable to presume that the content should look like the code block below, with any modified characters reverted to the intended ones?
```xml
$nameSpaceName="root\cimv2\mdm\dmmap"
$className="MDM_AssignedAccess"
$obj = Get-CimInstance -Namespace $namespaceName -ClassName $className
$obj.Configuration = @"
<?xml version="1.0" encoding="utf-8" ?>
<AssignedAccessConfiguration xmlns="http://schemas.microsoft.com/AssignedAccess/2017/config">
  <Profiles>
    <Profile Id="{9A2A490F-10F6-4764-974A-43B19E722C23}">
      <AllAppsList>
        <AllowedApps>
          <App AppUserModelId="Microsoft.ZuneMusic_8wekyb3d8bbwe!Microsoft.ZuneMusic" />
          <App AppUserModelId="Microsoft.ZuneVideo_8wekyb3d8bbwe!Microsoft.ZuneVideo" />
          <App AppUserModelId="Microsoft.Windows.Photos_8wekyb3d8bbwe!App" />
          <App AppUserModelId="Microsoft.BingWeather_8wekyb3d8bbwe!App" />
          <App AppUserModelId="Microsoft.WindowsCalculator_8wekyb3d8bbwe!App" />
          <App DesktopAppPath="%windir%\system32\mspaint.exe" />
          <App DesktopAppPath="C:\Windows\System32\notepad.exe" />
        </AllowedApps>
      </AllAppsList>
      <StartLayout>
        <![CDATA[<LayoutModificationTemplate xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout" xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout" Version="1" xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification">
                      <LayoutOptions StartTileGroupCellWidth="6" />
                      <DefaultLayoutOverride>
                        <StartLayoutCollection>
                          <defaultlayout:StartLayout GroupCellWidth="6">
                            <start:Group Name="Group1">
                              <start:Tile Size="4x4" Column="0" Row="0" AppUserModelID="Microsoft.ZuneMusic_8wekyb3d8bbwe!Microsoft.ZuneMusic" />
                              <start:Tile Size="2x2" Column="4" Row="2" AppUserModelID="Microsoft.ZuneVideo_8wekyb3d8bbwe!Microsoft.ZuneVideo" />
                              <start:Tile Size="2x2" Column="4" Row="0" AppUserModelID="Microsoft.Windows.Photos_8wekyb3d8bbwe!App" />
                              <start:Tile Size="2x2" Column="4" Row="4" AppUserModelID="Microsoft.BingWeather_8wekyb3d8bbwe!App" />
                              <start:Tile Size="4x2" Column="0" Row="4" AppUserModelID="Microsoft.WindowsCalculator_8wekyb3d8bbwe!App" />
                            </start:Group>
                            <start:Group Name="Group2">
                              <start:DesktopApplicationTile Size="2x2" Column="2" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Accessories\Paint.lnk" />
                              <start:DesktopApplicationTile Size="2x2" Column="0" Row="0" DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\Accessories\Notepad.lnk" />
                            </start:Group>
                          </defaultlayout:StartLayout>
                        </StartLayoutCollection>
                      </DefaultLayoutOverride>
                    </LayoutModificationTemplate>
                ]]>
      </StartLayout>
      <Taskbar ShowTaskbar="true"/>
    </Profile>
  </Profiles>
  <Configs>
    <Config>
      <Account>MultiAppKioskUser</Account>
      <DefaultProfile Id="{9A2A490F-10F6-4764-974A-43B19E722C23}"/>
    </Config>
  </Configs>
</AssignedAccessConfiguration>
"@

Set-CimInstance -CimInstance $obj
```
Note: the page seems to list the code block content as **"ps**" -- which could refer to either PowerShell or PostScript -- which is ambiguous to say the least. The content clearly states that the format is XML, so I presume we need to change `ps -> xml` in the code block syntax tag as well (like I have done in my code block above).

**Comment by e0i** [comment]
@illfated It seems like you have commented under the wrong issue.

**Comment by e0i** [comment]
Hello, @euphoric85 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by illfated** [comment]
@euphoric85 : Could you test if my corrected XML above works any better than the one currently on the Docs page? Or did you manage to sort that out yourself, making it look like my posted suggestion, before testing the XML in your environment?

**Comment by euphoric85** [comment]
@illfated I get the same error

**Comment by illfated** [comment]
That's a pity, sorry I don't know enough about this topic to help you.

@Dansimp or @lizap , are there any available options to have the page content tested in-house on Windows 10 Pro, version 1809, to confirm whether this issue is reproducible?

**Comment by Niglb** [comment]
Same error here - even with the example code.

**Comment by Niglb** [comment]
I have been able to get the configuration to apply only by escaping the XML: 

"&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
&lt;AssignedAccessConfiguration xmlns=&quot;http://schemas.microsoft.com/AssignedAccess/2017/config&quot;&gt;
    &lt;Profiles&gt;
        &lt;Profile Id=&quot;{5B328104-BD89-4863-AB27-4ED6EE355485}&quot;&gt;
      &lt;AllAppsList&gt; 
      &lt;AllowedApps&gt; 
		&lt;App AppUserModelId=&quot;Microsoft.BingWeather_8wekyb3d8bbwe!App&quot; /&gt;
		&lt;App AppUserModelId=&quot;Microsoft.WindowsCalculator_8wekyb3d8bbwe!App&quot; /&gt;
"

As an example - is this expected?

**Comment by Niglb** [comment]
Is there a way we can confirm this encoding requirement? I am staging a project for a thin client replacement and want to use Powershell to set the kiosk mode / assigned access. Encoding to HTML \ Escaped characters does allow setting, but I am getting inconsistent results in my configuration.

**Comment by illfated** [comment]
Good question, wish I knew or could check that for you. Unfortunately, I don't have access to any of the required environment nor the spare hardware to download trial versions to test it. I can only hope someone will be able to follow up on your questions and check if your issues with HTML tags like ` < > ` in PowerShell can be confirmed.

**Comment by cra3yk** [comment]
Simple add:
$obj.Configuration = $obj.Configuration -replace "<", "&lt;"
$obj.Configuration = $obj.Configuration -replace ">", "&gt;"

before "Set-CimInstance -CimInstance $obj"

**Comment by cra3yk** [comment]
ah - this forum engine has converted the original code:
it should look like this:
https://i.imgur.com/NxDs8JC.png

**Comment by illfated** [comment]
Oh. So according to your experience, it should look like it originally was before the change I made in my PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3955 (**Windows/Configuration: correct HTML code to XML tags**) , based on the translation issue #3819 **[LOC]"&lt;"needs to be replaced with"<", "&gt;"needs to be replaced with">"**

Does it look like an incorrect decision to submit that change, that the XML actually needs `&lt;` + `&gt;` instead of the angle (HTML tag) brackets?

**Comment by cra3yk** [comment]
I'd prefer the the original XML syntax (clean, nice look), then "convert" it "in the fly" to for powershell syntax.

**Comment by illfated** [comment]
So... maybe a combination of both code forms (XML + PowerShell) in separate code blocks could be a plausible solution here?

**Comment by cra3yk** [comment]
I did this and I split this script into 3 files: 
- launcher (to give admin and system rights) - lockdownuser.bat,
- main script - lockdownuser.ps1
- an xml file with config - lockdownuser.xml

I attached version for lockdown group (named "LockdownGroup").

[Lockdown user.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/3487366/Lockdown.user.zip)
[Lockdown group.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/3487371/Lockdown.group.zip)

PS: You have to create user/group, before launch this script.

PPS: When You want to clear/disable kiosk mode, run clear.bat
[Lockdown clear.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/3487386/Lockdown.clear.zip)

**Comment by NigelbrownIBM** [comment]
Nice one cra3yk! 

I have now implemented this in a StartUp script set by GPO for a RDS thin client project I am working on with the escaped charaters. So far it is working well. Eventually I would like to be able to compare the current config to the desired config XML and only re-set if need be. The compare doesn't see ever see them as the same, but re-setting on each start up seems not to be harmful.

**Comment by illfated** [comment]
Well done, @cra3yk. I must admit that I don't know the topic well enough to judge if this will be an acceptable solution to be added to the page in question, but I hope maybe @e0i or @martyav can suggest if it is usable or possibly ask one of the owners of the document to check if it is worth implementing on the page.

**Comment by cra3yk** [comment]
Please feel free and use/edit these scripts as You wish :-)

**Comment by NigelbrownIBM** [comment]
In my solution a Powershell Startup script worked without the requirement for the bat / psexe. I also enclosed the XML information in the PS script by assigning a variable @"XML content"@. In my project the workstation is domain joined but we are using the local autologon user created by the assigned access profile to launch the RDS session to function like a thin client. Interesting we do not have assigned access available to us in traditional GPO.

**Comment by cra3yk** [comment]
I needed one-click solution to set/clear policy with separated xml file (easy to change without messing script code) for standalone workstations, so this was the main reason form me to create 3-file solution for my needs :-)

**Comment by NigelbrownIBM** [comment]
Absolutely - it's excellent!

**Comment by MaratMussabekov** [comment]
Dear @illfated, there is also a class in PowerShell (System.Web) for this kind of html encoding, like:

$nameSpaceName="root\cimv2\mdm\dmmap"
$className="MDM_AssignedAccess"
$obj = Get-CimInstance -Namespace $namespaceName -ClassName $className
Add-Type -AssemblyName System.Web
$obj.Configuration = [System.Web.HttpUtility]::HtmlEncode(@"
XML Body
"@)
Set-CimInstance -CimInstance $obj

it worked well with this "<" ">" issue.

Would it be OK to replace the example in this article with this solution?

Thank you

**Comment by illfated** [comment]
@MaratMussabekov : Thank you for asking, even though I am far from experienced in this topic. I believe @cra3yk & @NigelbrownIBM will be able to answer that question far better than me.

**Comment by illfated** [comment]
@MaratMussabekov : Your amending looks good to me, even though I don't know PowerShell syntax well enough to know that it works.

@euphoric85 & @Niglb : Could you take a look at the suggested change in the PR (#4805 ) to see if it solves this issue?

**Comment by e0i** [comment]
@euphoric85 @Niglb 

The content has been updated with relevant changes accordingly with the PR #4805. Thanks.

**Comment by Elis150** [comment]
maybe can someone help me with AD user. 

https://techdirectarchive.com/2020/01/31/kiosk-mode-deployment-on-windows-10-with-an-ad-domain-account/
made everything by this munual and still doesn't open kiosk with AD user. 
this script creating local user, but i need with AD and open some program from file server

**Comment by sukusuma** [comment]
> 
Everything should be same except provide AD User like mentioned below!
https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps#config-for-individual-accounts
