### ISSUE TITLE
Formating the whole Article Issue #2693 related

### ISSUE THREAD

**Issue by j0rt3g4** [MicrosoftDocs/windows-itpro-docs#3751]
This issue is related to the format of this file, removing HTML and adding back using GitHub markdown.

https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/access-control/special-identities.md
Related to #2693

**Comment by j0rt3g4** [comment]
PR #3754

**Comment by mypil** [comment]
@j0rt3g4- Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
