### ISSUE TITLE
Cloud Protection Intune Setting Contradiction

### ISSUE THREAD

**Issue by joebartlett94** [MicrosoftDocs/windows-itpro-docs#3762]
To enable cloud-delivered protection in Intune, the article here states that we should:
> On the Cloud-delivered protection switch, select Enable.

However, the [Intune documentation](https://github.com/MicrosoftDocs/IntuneDocs/blob/master/intune/device-restrictions-windows-10.md) states:

> Cloud protection: Not configured (default) allows the Microsoft Active Protection Service to receive information about malware activity from devices that you manage. Enable blocks this feature.

Please can you confirm which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f8ccc01-1b04-e443-ef75-6ffe6c866dd5
* Version Independent ID: fa2eaa0f-db04-785a-3894-8244947b9cd5
* Content: [Enable cloud-delivered protection in Windows Defender Antivirus](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **v-anbic**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @joebartlett94 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by Malind19** [comment]
@e0i Created PR https://github.com/MicrosoftDocs/IntuneDocs/pull/2656

**Comment by e0i** [comment]
Hello @joebartlett94 

Based on our investigation, the Intune documentation is correct. Find the quote below,

> The settings documented are correct. This Cloud Protection setting uses the Defender/AllowCloudProtection CSP. The CSP description states:

> 0 – Not allowed.
> 1 (default) – Allowed.

> In Intune, Not configured is the default, which means this setting is allowed. The use of the word "Enable" in the UI definitely makes it confusing.

Please let us know whether this information clarifies your query. Thanks.

**Comment by joebartlett94** [comment]
Hi @e0i, 

Thanks for getting back to me. I have raised a PR to align the documentation here with the Intune docs.

I know that this is beyond your purview, but it would be great if the Intune UI were updated with clearer wording. What's the best way to raise this issue with them?

Thanks,
Joe

**Comment by e0i** [comment]
@joebartlett94 Thank you for taking the initiative to create a PR based on our findings. The PR is being rolled into review.

**Comment by e0i** [comment]
@joebartlett94 The PR has been merged. Thank you for your contributions. Much appreciated.

**Comment by e0i** [comment]
@officedocsbot close
