### ISSUE TITLE
Increase sub list indents for RBAC live response role lists

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#3769]
It would help readability to increase the list levels below the Basic and Advanced live response lists so the indent is increased. Example below.

```
- **Live response capabilities** - Users can take basic or advanced live response commands. 			 
    - Basic commands allow users to:
        - Start a live response session 
        - Run read only live response commands on a remote machine 
    - Advanced commands allow users to:
        - Run basic actions
        - Download a file from the remote machine
        - View a script from the files library
        - Run a script on the remote machine from the files library take read and write commands. 
```

- **Live response capabilities** - Users can take basic or advanced live response commands. 			 
    - Basic commands allow users to:
        - Start a live response session 
        - Run read only live response commands on a remote machine 
    - Advanced commands allow users to:
        - Run basic actions
        - Download a file from the remote machine
        - View a script from the files library
        - Run a script on the remote machine from the files library take read and write commands. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b246db4-2ef2-fc54-8db1-7a75a4974304
* Version Independent ID: 57290170-ba72-9f26-5a9c-311f6980ea19
* Content: [Create and manage roles for role-based access control](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/user-roles)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/user-roles.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/user-roles.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @iadgovuser1 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.
