### ISSUE TITLE
[Feedback & Questions] BitLocker: How to enable Network Unlock (https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock)

### ISSUE THREAD

**Issue by m4t7h3w** [MicrosoftDocs/windows-itpro-docs#3770]
Hello Bitlocker Experts,

I'm new to Bitlocker and I wanna have a deeper understanding on how the "Network Unlock" work.

Made reference to the:

    1) BitLocker: How to enable Network Unlock
    2) [MS-NKPU]: Network Key Protector Unlock Protocol

and draw a very simple diagram to try to get a more clear understanding:

![Bitlocker Network Unlock v0 1](https://user-images.githubusercontent.com/50902505/58153339-576f4680-7ca1-11e9-9481-13bb43eccfab.png)

It would be nice if Microsoft could provide an official diagram to depict the whole unlock process in details.

Questions:

1. Are the "Network Key" in the "How-to" and the "Client Key" in the MS-NKPU both refer to the same key?

2. Seems the Network Unlock Provider would simply decrypt the Client / Network Keys & the Session Keys sent from clients by using private keys, encrypt the Client / Network Keys using the Session Keys, and then send the encrypted Client / Network Keys back to clients via DHCP replies.  The Network Unlock Provider would return the very same Client / Network Keys, the only difference is, it will be encrypted by the Session Keys sent by clients rather than using private keys.  Am I correct?

3. If my understand is correct, then, seems the primary purpose for the "Network Unlock" is to check if user connected to a trusted network, and if so, Bitlocker will automatically unlock the locked drives.  Is it correct?

4. When using the Bitlocker Network Unlock, all key materials for decrypting the data are stored in clients' machines only, including the: 1.) Client / Network Keys; 2) IK in TPM; 3) VMK; and 4) FVEK.

Looking forward for your reply.

Thank you!

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@Justinha Would you kindly advise how to proceed with this issue? We'd like to follow-up with a PR if needed. Thank you.
