### ISSUE TITLE
Endpoints with SSL errors

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/windows-itpro-docs#3771]
The endpoints https://www.msftconnecttest.com and https://www.msftncsi.com have issues with SSL certificates (ERR_CERT_COMMON_NAME_INVALID). 
Are actual connections performed over SSL?
Don't certificates need to be fixed then?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4273a259-c3c7-dca7-6353-954068d740a7
* Version Independent ID: 1084ea77-95c4-4e4a-da6c-f4d8668f9ebf
* Content: [Enrolling devices in Windows Analytics (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started)
* Content Source: [windows/deployment/update/windows-analytics-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-get-started.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @juanand 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
Hello, @juanand 

It has been found that the mentioned domains have never been connected to via SSL, but only HTTP; and that WER is no longer dependent on these endpoints to check connectivity.

The document has thus been updated accordingly via the following commit,

[[d23376d] removing two endpoints per Albert ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/d23376d88aeb51564ae635466bfdbb9d04267a43#diff-377bb5873a1120a3604c39267a6d0e97)

Thank you for bringing this issue to attention.

**Comment by e0i** [comment]
@officedocsbot close
