### ISSUE TITLE
WTF does 'Confirm you authored Group Policy settings using the latest ADMX/ADML files (from the Windows 10 Creators Editions)' mean?

### ISSUE THREAD

**Issue by inbay** [MicrosoftDocs/windows-itpro-docs#3772]
'Confirm you authored Group Policy settings using the latest ADMX/ADML files (from the Windows 10 Creators Editions)'
~ How exactly?
This page does not describe the use of ADMX/ADML files, nor does it specify what they are, nor how to use them.
I suspect this comes from a precursor page, which SHOULD have that step attached to it, NOT here.
~At the least please provide a description for this step, as administrators may have no reference as to what this entails; For instance, I am attempting to prototype 'Windows Hello', but this is a road-block for me, as this confirmation makes no logical sense in the location it is without references.
~The logical flow for your documentation could be to provide your documentation experts the opportunity to write a quick how-to, and then configure said steps themselves.  If the steps are inadequate they can see this first hand and understand how to alter them to be suitable to the audience.
~This flow expects a minimum of advance knowledge by the documentation writers which should be standardized so as to avoid misleading advance knowledge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ec90f64-9a12-fdf9-25db-0e83cf77b7a2
* Version Independent ID: fb68756c-2d0c-c28c-4bda-ef6a876576e7
* Content: [Configure Windows Hello for Business Policy settings (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by inbay** [comment]
For instance;
The second paragraph begins with 'Alternatively, you can create copy the .ADMX and .ADML files from a Windows 10, version 1703 to their respective language folder' which lead me to believe that this was a secondary approach, not a necessary one, and I used the primary one;
'Install the Remote Server Administration Tools for Windows 10 on a computer running Windows 10, version 1703.'
Though in hind sight I have no idea how these steps are correlative and 'double-down' that this document needs to be modified.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @inbay 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by RAJU2529** [comment]
I have  new policies templates which includes  windows hello for business , so download  and copy to C drive

[PolicyDefinitions.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/3293139/PolicyDefinitions.zip)

**Comment by SquirrelAssassin** [comment]
BTW its not Administrative Templates > Windows Component, and select Windows Hello for Business.  Unless your on some old version of windows.  

Its Administrative Templates > Windows Component, and select Microsoft Passport for work.

**Comment by SquirrelAssassin** [comment]
RAJU2529 looks totally legit btw we should all download stuff from a college that the India government owns ... I totally trust code from government entities ....... (please know I'm being sarcastic)

**Comment by RAJU2529** [comment]
@SquirrelAssassin . I have collected the new policies from Microsoft and from Google, Firefox and adobe. I combined and I allowed in C drive. Those policies are not from government. But US defence govt might give policy settings to make your computer secured

**Comment by e0i** [comment]
@inbay 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.
