### ISSUE TITLE
The following line does not flow with the following lines, as the 'Add' button should be pressed, not the OK (which closes the the properties window).

### ISSUE THREAD

**Issue by inbay** [MicrosoftDocs/windows-itpro-docs#3775]
The line; 'From the Add Superseded Template dialog, select the Domain Controller Authentication certificate template and click OK.' should be prefixed with 'Add' not 'OK'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0e839ae-7beb-07fe-f0ea-560079f1f858
* Version Independent ID: af8e8903-fd5c-7210-768d-e0b5de67fe88
* Content: [Validate Public Key Infrastructure (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-pki)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-pki.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by inbay** [comment]
#7 just below this has the same error, as the descriptive text still describes completion/observation of the 'Domain Controller Authentication (Kerberos) Properties' window, and this window is not closed until the configuration is completed in step 9 which DESCRIBES clicking the OK button verbosely.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@inbay

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by e0i** [comment]
@officedocsbot reopen

**Comment by e0i** [comment]
Re-opening as a PR is under delivery for this issue.

**Comment by e0i** [comment]
@inbay 

Upon your feedback, We have updated the content with relevant changes accordingly.

The PR #4641 has been merged.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
