### ISSUE TITLE
Why no reference to the Your Phone app?

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/windows-itpro-docs#3777]
"Due to this change, you will only be able to access messages from the device that received the message."
But the Your Phone app JUST acquired the ability to sync text messages over mobile data AND MMS support with 1903.
It's as if the left hand doesn't know what the right hand is doing!
https://twitter.com/bojorchess/status/1129537505584340992
https://twitter.com/bojorchess/status/1130680611016851456

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b94821-cd7a-2c3a-4957-ec9e560201d1
* Version Independent ID: 35348ca8-01db-5cb5-ed40-fd0105e2aec2
* Content: [Windows 10, version 1903 - Features that have been removed](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-1903-removed-features)
* Content Source: [windows/deployment/planning/windows-10-1903-removed-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-10-1903-removed-features.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @BR77BE 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.

**Comment by rbbrittain** [comment]
The text was just changed yesterday so it might not be exactly what the OP was looking at, but it specifically refers to "(t)he messaging app on Desktop" and "Windows Mobile"; it's not surprising that it's being deprecated. That is a different app *and* mobile OS from Your Phone, which syncs texts with Android phones running the Your Phone Companion app. I have both Your Phone & Messaging on my PC with 1903; my Android texts appear in Your Phone but not Messaging, consistent with announced 1903 support for both apps. Perhaps that paragraph needs clarification, but it's NOT inconsistent with the enhancements to Your Phone; indeed it may be very consistent as Microsoft moves its mobile strategy to Android.

**Comment by Reeced40** [comment]
@BR77BE  @rbbrittain Thank you for reaching out and helping improve MS Docs. I'm looking into the issue.  In the meantime if you have any suggestions for improving the article/wording please let me know.

**Comment by Reeced40** [comment]
@BR77BE @rbbrittain If there is anything you could suggest to be added/changed in the article please could you let me know, but please be advised that this topic relates to Windows 10 (Mobile) and not Android.

**Comment by rbbrittain** [comment]
Perhaps add: "Note: This concerns messages from Windows Phone devices in the Messaging app. It does NOT apply to messages from Android devices in the separate Your Phone app."

**Comment by greg-lindsay** [comment]
The message by rbbrittain is accurate. This isn't about the Your Phone app. I can add a clarification but all the text on this page is reviewed by legal and it's difficult to change anything.
