### ISSUE TITLE
Step 4 missing instruction

### ISSUE THREAD

**Issue by phgray** [MicrosoftDocs/windows-itpro-docs#3790]
Step 4 should have at the beginning to open Group Policy Management console and navigate to the 'Change Control' folder beneath your domain

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04053f4b-5eb8-6146-6256-14205459a503
* Version Independent ID: 8ca210bf-e27f-a8ce-f296-585f28a50a39
* Content: [Step-by-Step Guide for Microsoft Advanced Group Policy Management 4.0](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/agpm/step-by-step-guide-for-microsoft-advanced-group-policy-management-40#feedback)
* Content Source: [mdop/agpm/step-by-step-guide-for-microsoft-advanced-group-policy-management-40.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/agpm/step-by-step-guide-for-microsoft-advanced-group-policy-management-40.md)
* Product: **w10**
* Technology: **mdop**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @phgray 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.

**Comment by e0i** [comment]
@phgray 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.
