### ISSUE TITLE
Video link is no longer valid

### ISSUE THREAD

**Issue by Scriptimus** [MicrosoftDocs/windows-itpro-docs#3796]
MVA course in the link is retired.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87ec66f8-6598-5751-a10f-55951c08b3ff
* Version Independent ID: c3bb99fb-ec6f-638f-fb26-af3142f5d49c
* Content: [Protect derived domain credentials with Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard#feedback)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
The linked page says:
***
### Sorry, you've reached a retired course.
Unfortunately, no replacement course is available.
***
I will open a PR soon to have the whole text line removed.

**Comment by illfated** [comment]
@Scriptimus : Thank you for the report. Feel free to report any other pages where the same issue appears.

**Comment by e0i** [comment]
@Scriptimus

This is a known issue under investigation.

Related: #3513

We'll follow-up with updates during the resolution of the issue.

Thank you for providing feedback.

**Comment by illfated** [comment]
Related to #3818 ([**All links broken on this page**](https://www.linkedin.com/learning/search?keywords=Deep+Dive+into+Windows+Defender+Credential+Guard)) and #3513 ([**Deep dive references point to Microsoft Virtual Academy**](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3513))

**Comment by e0i** [comment]
See: #3513

**Comment by e0i** [comment]
@officedocsbot add label mva-links

**Comment by e0i** [comment]
@officedocsbot add label "broken link/type/formatting"
