### ISSUE TITLE
White Glove feature enablement

### ISSUE THREAD

**Issue by jmrita** [MicrosoftDocs/windows-itpro-docs#3799]
When can we expect White Glove to move from private to preview ? Just tried it and got red screen. Event log says "White Glove not supported". Is it part of 1905 Service Release ? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5b57d1-61b3-39d4-34ff-d6dcb858c250
* Version Independent ID: 42609104-815f-9e7a-39aa-38d92cc910c9
* Content: [Windows Autopilot for white glove deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove)
* Content Source: [windows/deployment/windows-autopilot/white-glove.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/white-glove.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @jmrita  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your question so that it gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by greg-lindsay** [comment]
Insert a USB key, click the “View diagnostics” button, and specify the USB as the location – the files will be generated in the background on that location, so don’t remove the USB key too quickly.  Then view the files on the USB to troubleshoot.

**Comment by e0i** [comment]
Hello @jmrita  ,

We are closing this issue since your question seems to be answered. 

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
