### ISSUE TITLE
Unable to land on Federated domain 

### ISSUE THREAD

**Issue by NagaCSC** [MicrosoftDocs/windows-itpro-docs#3803]
If I click on 
Hybrid Azure AD joined provisioning in a Certificate Trust deployment in a Federated environment
it takes to Managed Environment

However there is another link similar (synchronous)
Hybrid Azure AD joined provisioning in a synchronous Certificate Trust deployment in a Federated environment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f170bfe-711d-f875-8d5f-a49d3d5113b2
* Version Independent ID: a75c9aa8-b47b-51dd-9b84-c63bb5c6b782
* Content: [How Windows Hello for Business works - Provisioning](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-provisioning#hybrid-azure-ad-joined-provisioning-in-a-certificate-trust-deployment-in-a-managed-environment)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-how-it-works-provisioning.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-how-it-works-provisioning.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@NagaCSC 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by martyav** [comment]
Closing because the "Hybrid Azure AD joined provisioning in a Certificate Trust deployment in a Federated environment" section was removed. Note that the similarly named section relating to synchronous deployment is still up.

Btw, in between the issue being opened and the section being removed, commit 4dfdeec had updated the name of the section from "Managed" to "Federated".
