### ISSUE TITLE
[LOC]"設定 > の更新 & セキュリティ" needs to be replaced with "設定 > 更新とセキュリティ"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3804]
"設定>の更新 & セキュリティ>のアクティブ化"
↓
"設定 > 更新とセキュリティ > ライセンス認証"

related issue: #3487

https://docs.microsoft.com/ja-jp/education/windows/change-to-pro-education

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 87760a66-0877-5a64-0b63-52495c3717ca
* Version Independent ID: c6d2091f-5ae6-1546-f0ed-6e506ec3e25e
* Content: [Windows 10 Pro から Windows 10 エデュケーションに変更する](https://docs.microsoft.com/ja-jp/education/windows/change-to-pro-education)
* Content Source: [education/windows/change-to-pro-education.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/change-to-pro-education.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
From web translator:
"Settei > no kōshin & sekyuriti" needs to be replaced with "Settei > kōshin to sekyuriti"

(Ampersand ( **&** ) issue again, as referenced above)

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
See: #3487

**Comment by e0i** [comment]
Ampersand issue.

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot unassign @TinaMcN

**Comment by illfated** [comment]
@e0i : Uhmm, did you mean to assign the issue to @TinaMcN instead of unassigning it?

**Comment by TinaMcN** [comment]
Thanks for the feedback @hyoshioka0128
Set the topic to be human translated, will take 2-3 weeks to process

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間翻訳されており、問題は修正されているようです。 修正済みであることを確認してください。 フィードバックをありがとうございました。
(The article is now human translated and the issue appears to be fixed.  Please verify that it is fixed.  Thanks again for the feedback.)

**Comment by e0i** [comment]
Manually verified to be fixed. Thanks.
