### ISSUE TITLE
Typo: "begging" should be "beginning"

### ISSUE THREAD

**Issue by jeffreymcclain** [MicrosoftDocs/windows-itpro-docs#3809]
"In the begging..."

https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/passwordless-strategy#the-process

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca080bd-ed37-60a8-ec22-b1929166ff0c
* Version Independent ID: d2742e0c-9d66-4b1f-8555-a1fb1546455b
* Content: [Password-less Strategy](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/passwordless-strategy#the-process)
* Content Source: [windows/security/identity-protection/hello-for-business/passwordless-strategy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/passwordless-strategy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
@jeffreymcclain : Thank you for pointing out the typo. If you find any other typos or misprints in that page, feel free to post your findings here as soon as you can.
