### ISSUE TITLE
Requirements to use AppLocker: workgroup environment

### ISSUE THREAD

**Issue by Crypt32** [MicrosoftDocs/windows-itpro-docs#381]
Based on this issue: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/360

Original quote:
> They indicated AppLocker can be enforced on workgroup machines

unfortunately, it is incorrect statement, or additional information is missing. Reference: https://docs.microsoft.com/en-us/windows/device-security/applocker/configure-the-application-identity-service

> Starting with Windows 10, the Application Identity service is now a protected process. Because of this, you can no longer manually set the service Startup type to Automatic. 

Applocker relies on Application Identity service and you can't change its start type via services.msc on a standalone machine. If you start the service, Applocker rules won't apply until the server reboots. Since service start type is Manual (by default) and cannot be changed via services.msc, after reboot the service is stopped. The configuration process described in the referenced doc is applicable for domain members only. GPMC is not available in workgroup environments. I made several tests on Windows Server 2016 and all failed to apply Applocker rules. Therefore, I concluded that it is not possible and should be mentioned in requirements unless there will be a note on how to enable Applocker in workgroup environments.

Either, update article on applocker requirements or provide information about Applocker configuration in workgroup envrionments, where GPMC is not available.

**Comment by Justinha** [comment]
@Crypt32 Sorry for delay here. As I posted for https://github.com/MicrosoftDocs/windows-itpro-docs/issues/398, I'm relaying the same reply from Aaron Margosis here too:

There is something weird about trying to change the configuration of appidsvc, at least using the Services.msc snap-in. Try one of these methods:

1) From an elevated Cmd or PowerShell:
sc.exe config appidsvc start= auto
2) Create a security template that configures appidsvc to be automatic start, and apply it using secedit.exe or LGPO.exe.

**Comment by Crypt32** [comment]
Then this information should be documented somewhere in more official manner.

**Comment by Justinha** [comment]
@Crypt32 added here: https://docs.microsoft.com/en-us/windows/security/threat-protection/applocker/configure-the-application-identity-service

**Comment by samuelg78** [comment]
Hi, i had successfully set Applocker start mode to automatic using elevated cmd. However, i cannot set the start mode back to manual, i had tried to run sc.exe config appidsvc start= demand using elevated cmd but the access is denied. I had also tried to stop the process but the process is locked. How can set back the start mode to manual?

**Comment by K3myt** [comment]
> Hi, i had successfully set Applocker start mode to automatic using elevated cmd. However, i cannot set the start mode back to manual, i had tried to run sc.exe config appidsvc start= demand using elevated cmd but the access is denied. I had also tried to stop the process but the process is locked. How can set back the start mode to manual?

Maybe

**Comment by samuelg78** [comment]
Try to change the Enforcement options to Audit Only for all to install apps.

If the above failed, then try to following:

    Stop the enforcement of AppLocker Policies by unchecking the “Configured” option.

Then reboot the machine.

Clear the Applocker policy.

Create a file clear.xml with the following content:

<AppLockerPolicy Version="1">

<RuleCollection Type="Exe" EnforcementMode="NotConfigured" />

<RuleCollection Type="Msi" EnforcementMode="NotConfigured" />

<RuleCollection Type="Script" EnforcementMode="NotConfigured" />

<RuleCollection Type="Dll" EnforcementMode="NotConfigured" />

</AppLockerPolicy>

Run powershell as administrator with the following commands;

import-module AppLocker

Set-AppLockerPolicy -XMLPolicy .\clear.xml

Go to %windir%\System32\AppLocker\ and delete all the files but AppCache.dat cannot be deleted.

Reboot the machine.




Sent from my iPhone

On 23 Jun 2022, at 4:18 PM, K3myt ***@***.***> wrote:

﻿

Hi, i had successfully set Applocker start mode to automatic using elevated cmd. However, i cannot set the start mode back to manual, i had tried to run sc.exe config appidsvc start= demand using elevated cmd but the access is denied. I had also tried to stop the process but the process is locked. How can set back the start mode to manual?

Maybe
