### ISSUE TITLE
Thanks for information 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#3815]
I just want to try to create application rules, after reached to home.

If I get any doubts, then I will ask for solutions. Only these authors can give  solutions and other articles authors also given solutions 
Thanking you 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f23b1d4-2cfa-10ec-e3b1-fdd71238548e
* Version Independent ID: b5f5241d-0afa-94e7-7fc1-c9f6b81d953b
* Content: [Configure access to Microsoft Store (Windows 10)](https://docs.microsoft.com/en-in/windows/configuration/stop-employees-from-using-microsoft-store)
* Content Source: [windows/configuration/stop-employees-from-using-microsoft-store.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/stop-employees-from-using-microsoft-store.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @TrudyHa
* Microsoft Alias: **Trudyha**

**Comment by illfated** [comment]
Thank you for the nice words. I am sure they appreciate your feedback.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by RAJU2529** [comment]
Please give me two days to time to reach my home

**Comment by RAJU2529** [comment]
Please give me two days to time to reach my home

**Comment by RAJU2529** [comment]
Today 29-05-2019  @8.05PM >For testing purposes 
i created application policy rule  to deny access of microsoft store app , i added administartor local account  for deny access.  

Thanks for the information ,  Please add the video lecturers keeping in  mind with different rules with categories . I am looking a video lecturers  for future the  interactive  voices.

**Comment by e0i** [comment]
@RAJU2529 You feedback regarding addition of video lectures has been noted. Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
