### ISSUE TITLE
Another Broken link

### ISSUE THREAD

**Issue by Scriptimus** [MicrosoftDocs/windows-itpro-docs#3817]
2 more broken links on this page 

"Protecting network passwords with Windows Defender Credential Guard" Please review the remainder of the links
"Credentials protected by Windows Defender Credential Guard"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87ec66f8-6598-5751-a10f-55951c08b3ff
* Version Independent ID: c3bb99fb-ec6f-638f-fb26-af3142f5d49c
* Content: [Protect derived domain credentials with Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
Unless you refer to the content of the links in **[Related topics](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard#related-topics)**, I am fairly certain that this is covered by https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3796 as well as the content in my PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3816 and my suggestion to find one of the LinkedIn videos to replace the removed video on the MVA pages (https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3816#issuecomment-496302489).

Please also note https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3513 and https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3818.

**Comment by e0i** [comment]
@Scriptimus

This is a known issue under investigation.

We'll follow-up with updates during the resolution of the issue.

Thank you for providing this valuable feedback.

**Comment by e0i** [comment]
See: #3513

**Comment by e0i** [comment]
@officedocsbot add label mva-links
