### ISSUE TITLE
All links broken on this page

### ISSUE THREAD

**Issue by Scriptimus** [MicrosoftDocs/windows-itpro-docs#3818]
All links on this page are broken. I have listed them below:

Deep Dive into Windows Defender Credential Guard: Related videos
Credential Theft and Lateral Traversal
Virtualization-based security
Credentials protected by Windows Defender Credential Guard

Please not only remove them but add links to newer content. Also raise the greater issue in Microsoft that there are a lot of Virtual Academy Documents links that will need to be updated all over Microsoft Docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77f8afd0-78e2-b866-196e-7068fd3743fe
* Version Independent ID: 94338ba3-90f0-eb4c-54e8-d3de22d8647b
* Content: [How Windows Defender Credential Guard works](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-how-it-works)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-how-it-works.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-how-it-works.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
Related to #3513 ([**Deep dive references point to Microsoft Virtual Academy**](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3513))

**Comment by e0i** [comment]
@Scriptimus

This is a known issue under investigation.

We'll follow-up with updates during the resolution of the issue.

Thank you.

**Comment by e0i** [comment]
See: #3513

**Comment by e0i** [comment]
@officedocsbot add label mva-links
