### ISSUE TITLE
[LOC]"&lt;"needs to be replaced with"<", "&gt;"needs to be replaced with">"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3819]
https://docs.microsoft.com/ja-jp/windows/configuration/kiosk-mdm-bridge
![kiosk-mdm-bridge](https://user-images.githubusercontent.com/40815708/58407092-f206c580-80a5-11e9-9dbb-3bf6272faa3f.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7f536979-dfd7-317d-2da7-c40935d85c7f
* Version Independent ID: c23737a1-c71e-3d9c-3915-c6929a23602e
* Content: [MDM ブリッジ WMI プロバイダーを使用して、Windows 10 キオスク (Windows 10) を作成するには](https://docs.microsoft.com/ja-jp/windows/configuration/kiosk-mdm-bridge)
* Content Source: [windows/configuration/kiosk-mdm-bridge.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-mdm-bridge.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
I wonder if the code content has been created in some form of HTML editor, converting any special characters like ` < `, ` " ` and ` > ` to shorthand names for those codes.
Would it be reasonable to presume that the content should look like this, with the modified characters reverted back like this:
```xml
$nameSpaceName="root\cimv2\mdm\dmmap"
$className="MDM_AssignedAccess"
$obj = Get-CimInstance -Namespace $namespaceName -ClassName $className
$obj.Configuration = @"
<?xml version="1.0" encoding="utf-8" ?>
<AssignedAccessConfiguration xmlns="http://schemas.microsoft.com/AssignedAccess/2017/config">
  <Profiles>
    <Profile Id="{9A2A490F-10F6-4764-974A-43B19E722C23}">
      <AllAppsList>
        <AllowedApps>
          <App AppUserModelId="Microsoft.ZuneMusic_8wekyb3d8bbwe!Microsoft.ZuneMusic" />
          <App AppUserModelId="Microsoft.ZuneVideo_8wekyb3d8bbwe!Microsoft.ZuneVideo" />
          <App AppUserModelId="Microsoft.Windows.Photos_8wekyb3d8bbwe!App" />
          <App AppUserModelId="Microsoft.BingWeather_8wekyb3d8bbwe!App" />
          <App AppUserModelId="Microsoft.WindowsCalculator_8wekyb3d8bbwe!App" />
          <App DesktopAppPath="%windir%\system32\mspaint.exe" />
          <App DesktopAppPath="C:\Windows\System32\notepad.exe" />
        </AllowedApps>
      </AllAppsList>
      <StartLayout>
        <![CDATA[<LayoutModificationTemplate xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout" xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout" Version="1" xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification">
                      <LayoutOptions StartTileGroupCellWidth="6" />
                      <DefaultLayoutOverride>
                        <StartLayoutCollection>
                          <defaultlayout:StartLayout GroupCellWidth="6">
                            <start:Group Name="Group1">
                              <start:Tile Size="4x4" Column="0" Row="0" AppUserModelID="Microsoft.ZuneMusic_8wekyb3d8bbwe!Microsoft.ZuneMusic" />
                              <start:Tile Size="2x2" Column="4" Row="2" AppUserModelID="Microsoft.ZuneVideo_8wekyb3d8bbwe!Microsoft.ZuneVideo" />
                              <start:Tile Size="2x2" Column="4" Row="0" AppUserModelID="Microsoft.Windows.Photos_8wekyb3d8bbwe!App" />
                              <start:Tile Size="2x2" Column="4" Row="4" AppUserModelID="Microsoft.BingWeather_8wekyb3d8bbwe!App" />
                              <start:Tile Size="4x2" Column="0" Row="4" AppUserModelID="Microsoft.WindowsCalculator_8wekyb3d8bbwe!App" />
                            </start:Group>
                            <start:Group Name="Group2">
                              <start:DesktopApplicationTile Size="2x2" Column="2" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Accessories\Paint.lnk" />
                              <start:DesktopApplicationTile Size="2x2" Column="0" Row="0" DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\Accessories\Notepad.lnk" />
                            </start:Group>
                          </defaultlayout:StartLayout>
                        </StartLayoutCollection>
                      </DefaultLayoutOverride>
                    </LayoutModificationTemplate>
                ]]>
      </StartLayout>
      <Taskbar ShowTaskbar="true"/>
    </Profile>
  </Profiles>
  <Configs>
    <Config>
      <Account>MultiAppKioskUser</Account>
      <DefaultProfile Id="{9A2A490F-10F6-4764-974A-43B19E722C23}"/>
    </Config>
  </Configs>
</AssignedAccessConfiguration>
"@

Set-CimInstance -CimInstance $obj
```
Note: the page seems to list the code block content as **"ps**" -- which could refer to either PowerShell or PostScript -- which is ambiguous to say the least. The content clearly states that the format is XML, so I presume we need to change `ps -> xml` in the code block syntax tag as well (like I have done in my code block above).

Please also note: possibly related to issue **[Set-CimInstance fails](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3750)** **#3750** , from the en-us version of the same page.

**Comment by e0i** [comment]
Quotes and other special HTML keywords have been transformed as well. It looks like the HTML generator could not differentiate code blocks as exceptions where HTML transformations need not to happen.

cc @dongmicro

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
See: #3405

**Comment by e0i** [comment]
@officedocsbot close

**Comment by lovettchris** [comment]
Note: the reason the original poster has HTML is because this page:
https://docs.microsoft.com/en-us/windows/configuration/kiosk-mdm-bridge
tells us to `[System.Web.HttpUtility]::HtmlEncode` the XML.  Perhaps the page should be updated?
