### ISSUE TITLE
Extension for Windows 10 1903

### ISSUE THREAD

**Issue by troyphil** [MicrosoftDocs/windows-itpro-docs#3820]
Please specify mandatory profile extension for Windows 10 1903

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9ca7cb6-32cb-1517-a9de-c36046955d45
* Version Independent ID: 91041e39-007e-f481-0cd4-177b4039ae12
* Content: [Create mandatory user profiles (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/mandatory-user-profile#feedback)
* Content Source: [windows/client-management/mandatory-user-profile.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mandatory-user-profile.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@troyphil 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by e0i** [comment]
@troyphil 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
