### ISSUE TITLE
Note on the console

### ISSUE THREAD

**Issue by SusanBradley** [MicrosoftDocs/windows-itpro-docs#3828]
When you have a Lenovo laptop that recommends a 200% scaling, the settings icon is off the view and cannot be accessed.  Is there any way to make the console react to different monitor settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81afe8a2-3504-d628-4228-28118c2416d4
* Version Independent ID: 8d0bedb0-3142-941f-8067-77d499c90d41
* Content: [Microsoft Defender Advanced Threat Protection portal overview](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/portal-overview)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/portal-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/portal-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @SusanBradley thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by illfated** [comment]
Out of curiosity, which "settings icon" is this about? Is it the Windows 10 Settings icon on the Windows Start menu, or are you referring to something else entirely?

**Comment by lindspea** [comment]
@SusanBradley thank you for reaching out.  Please could you let me know if @illfated helped answer your question or if this still needs further investigation.

**Comment by SusanBradley** [comment]
No, I'm specifically talking about  the gear/settings icon for Windows Defender ATP.  I was following the instructions and couldn't figure out where the gear/settings was.  I realized because my DPI was set at 200% scaling the "Microsoft Defender Advanced Threat Protection portal " wouldn't show the settings icon. Is there any way the portal can scale based on the settings of the laptop?  I couldn't find any other location to give feedback.

**Comment by SusanBradley** [comment]
P.S. because cloud platforms change, for a while I thought the issue was that the console had changed and that documentation hasn't been updated.  I finally realized that it was the DPI scaling of my computer causing the inability to see the settings icon in the Defender portal.

**Comment by illfated** [comment]
Very well, fair enough. Thank you for your update and feedback. Based on your feedback, I would recommend that you use the Feedback Hub feature to raise that issue with the developers, hoping that they will consider implementing support for high resolution DPI scaling for the Windows Defender ATP interface. Seeing that this is not actually a documentation issue, I recommend closing this ticket and get the attention of the developers via the Feedback Hub.

(@lindspea : if there are any other ways of making the developers aware of the high res DPI scaling issue, please add any suggestions for the recommended way to get this feature request over to the developers.)

**Comment by SusanBradley** [comment]
But the feedback hub is for Windows 10.  This isn't a problem with Window per se, it's a problem with the console of ATP not redrawing appropriately.

**Comment by illfated** [comment]
Thank you for pointing that out. Sorry for not knowing this topic well enough to provide adequate answers. I defer to the MS Docs team members to give you appropriate feedback on how to proceed.

**Comment by lindspea** [comment]
@SusanBradley Thank you for getting back to me.  I'll address this issue with the Product team.  In the meantime you could try the following: You could override the default application scaling. You can right-click on the application (or a shortcut), select properties and look in the compatibility tab. There, you'll see an option to override default scaling. Here is another article with other possible solutions - https://support.microsoft.com/help/3025083/windows-scaling-issues-for-high-dpi-devices. I will have this link added to the article in a note.

**Comment by e0i** [comment]
@SusanBradley 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
