### ISSUE TITLE
Wrong value for registering devices in Intune

### ISSUE THREAD

**Issue by hemetz** [MicrosoftDocs/windows-itpro-docs#3829]
Its current 500 devices

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4775bcf-978a-f992-31e6-9c15333541e1
* Version Independent ID: 662e95c4-8252-9341-e5be-3111cd3a2299
* Content: [Administering Autopilot](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/administer#feedback)
* Content Source: [windows/deployment/windows-autopilot/administer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/administer.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by martyav** [comment]
Just hopped in to doublecheck, and 500 does appear to be the correct value
