### ISSUE TITLE
SignInLastInteractiveUserAutomaticallyAfterASystemInitiatedRestart

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#3840]
Can you guys please not removed old features or replace them without proper documentation??

There was a CSP similar to AllowAutomaticRestartSignOn named SignInLastInteractiveUserAutomaticallyAfterASystemInitiatedRestart which is not showing at this page anymore. And all the current ones are marked as 1903 compatible only. Funny enough SignInLastInteractiveUserAutomaticallyAfterASystemInitiatedRestart was compatible with 1809 and it doesn't exist on 1903 so it fails the deployment of the device profile i had. Would be good to have a history on this things and not just rip and replace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 533975df-3376-6d9f-5233-19056ee4516b
* Version Independent ID: ed33304c-fbb2-10d8-7943-8eaac10797b3
* Content: [Policy CSP - WindowsLogon](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-windowslogon)
* Content Source: [windows/client-management/mdm/policy-csp-windowslogon.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-windowslogon.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@manikadhiman Would you be able to provide directions on this matter? We would like to follow-up with PR updates if necessary. Thanks.

**Comment by ManikaDhiman** [comment]
@e0i The WindowsLogon/SignInLastInteractiveUserAutomaticallyAfterASystemInitiatedRestart policy has been removed because it's no longer supported. This policy is replaced by WindowsLogon/AllowAutomaticRestartSignOn. The "Change history in MDM documentation", "May 2019" section is updated to reflect this change. Hope this helps.

**Comment by e0i** [comment]
Hello @schenardie,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
