### ISSUE TITLE
Third-party AV

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/windows-itpro-docs#3844]
If device is using third-party AV, does this blade consider up-to-date WDAV signatures (for takover purposes in case of third-party AV problems), or simply shows everything as 0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32665050-e816-b1a9-225f-0fea575e3e1f
* Version Independent ID: a975c054-a956-99a4-679c-7ffccd205cd0
* Content: [Update Compliance - Windows Defender AV Status report](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-wd-av-status)
* Content Source: [windows/deployment/update/update-compliance-wd-av-status.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/update-compliance-wd-av-status.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@cinglis-msft can you advise?

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by CharlesMcquade** [comment]
Devices not using WDAV are not evaluated or considered in the WDAV section. For example, if you have 10 devices, 1 of which uses WDAV and has an up to date signature, 100% of your devices within the WDAV section should show has having an up to date signature.

**Comment by GitMaggie** [comment]
Can you please add the requirement of WDAV solution in this page ?It's difficult to find the requirement when configuring the solution . 
 https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/troubleshoot-reporting#confirm-pre-requisites

**Comment by e0i** [comment]
Hello, @juanand 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
