### ISSUE TITLE
Microsoft Virtual Academy video links

### ISSUE THREAD

**Issue by Scriptimus** [MicrosoftDocs/windows-itpro-docs#3860]
There are 2 dead MVA links above. "You've reached a retired course". The ones at the very top and bottom.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b1f3ae7-79ed-fc75-4f36-ad5537d5f928
* Version Independent ID: bdd1e434-0825-7220-9e97-ee4cdd10b897
* Content: [Considerations when using Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-considerations)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-considerations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-considerations.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by illfated** [comment]
Related to #3513, #3796, #3817 and #3818 .

**Comment by martyav** [comment]
Perhaps all the broken link issues should be given their own Github label.

**Comment by illfated** [comment]
> Perhaps all the broken MVA link issues should be given their own Github label.

Good idea, I agree. I would have started working on PRs for the reported pages containing the links to those retired courses, but I find it a bit challenging to be certain of which LinkedIn video matches the individual pages.

**Comment by martyav** [comment]
I can take the ones related to security topics

**Comment by illfated** [comment]
Thank you. I'm glad to hear that.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot add label mva-links
