### ISSUE TITLE
GPO enrollment with MFA

### ISSUE THREAD

**Issue by tigeraaditya** [MicrosoftDocs/windows-itpro-docs#3861]
[Enter feedback here]

GPO enrollment with MFA fails with Error code 0x8018002b. Does GPO enrollment support Multi-factor authentication or not?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@tigeraaditya - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by flotpg** [comment]
Hi Team,
I hope you're all doing well.

This is still an issue and affects all tenants where MFA is turned on. It can take up to hours and hundreds of reboots until a message appears that an account needs to be fixed. Then the user is able to enter his MFA codes and the device gets enrolled.
But the time that passes by is totally unpredictable. Sometimes it takes 5-10 minutes and two reboots, sometimes you spend ours.

**Comment by illfated** [comment]
@flotpg : Please open a new ticket by clicking the button **[[ :octocat: This page ]]** at the bottom of the document page:

![image](https://user-images.githubusercontent.com/38162891/98600445-dc0eb400-22dd-11eb-9f95-a536c26c8974.png)

https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy#feedback
