### ISSUE TITLE
Failure code 0x1b is not correct; missing 0x1d

### ISSUE THREAD

**Issue by repton-infinity** [MicrosoftDocs/windows-itpro-docs#3863]
This doc says 0x1b is KDC_ERR_SVC_UNAVAILABLE. Other information on the internet says that KDC_ERR_SVC_UNAVAILABLE is 0x1d, and that 0x1b is KDC_ERR_MUST_USE_USER2USER

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94cebf1d-b16d-4ddc-b532-be829b858938
* Version Independent ID: 3707f457-98d5-e5b3-c749-99afe0d6d495
* Content: [4768(S, F) A Kerberos authentication ticket (TGT) was requested. (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4768)
* Content Source: [windows/security/threat-protection/auditing/event-4768.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/event-4768.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@repton-infinity 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
