### ISSUE TITLE
Why not create a script or GUI action in server management? 

### ISSUE THREAD

**Issue by wayyt** [MicrosoftDocs/windows-itpro-docs#3865]
Too many steps to config Windows Hello for business. Why not create a script or GUI action in server management?

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@wayyt 

Somehow your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by e0i** [comment]
@wayyt 

We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.

Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by MamaDoc** [comment]
I apologize for this communication breach.  Tech support told me this was possible.  A lot of emails, messages, etc could be blocked or very late to receive.  I am very sorry to take your time and 18 days wow.  Please excuse my communication breach. It explains why accusations of conduct and more have been filed against me.  I do not have complete access to my accounts.     Thank You for much clarification.  Handling with priority.
