### ISSUE TITLE
RDP to AAD-joined PC from workgroup PC

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/windows-itpro-docs#3866]
Hello, just wondering if it is on the radar to add this capability?  The restrictions of the source, or connecting, PC are more restrictive than ever before based on having to be joined to AAD or just AD if integrated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by lindspea** [comment]
@JeremyTBradshaw Thank you for reaching out and helping improve MS Docs.  Please have a look at this TechNet article and let me know if it helps sort out this issue. https://social.technet.microsoft.com/Forums/22f7f5aa-a1ad-42d2-b98b-39979d1db9ce/rdp-to-azure-ad-joined-computer?forum=winserverTS

**Comment by JeremyTBradshaw** [comment]
@lindspea thanks for the response but no that article doesn't help, thanks.  This article, which we're in the comments for, states what is possible, and it doesn't include the ability to initiate RDP (to an Azure-AD-joined device) from a Workgroup / non-AD/non-AAD-joined device.

**Comment by lindspea** [comment]
@JeremyTBradshaw Thank you for clearing that up Jeremy.  Are you unable to initiate RDP or are you suggesting adding information to the article on how it's done.  As far as I know it is possible to do, but it entirely depends on if RDP isn't disabled on the guest machine. You would need to ask the system administrator regarding this.

**Comment by JeremyTBradshaw** [comment]
> @JeremyTBradshaw Thank you for clearing that up Jeremy. Are you unable to initiate RDP or are you suggesting adding information to the article on how it's done. As far as I know it is possible to do, but it entirely depends on if RDP isn't disabled on the guest machine. You would need to ask the system administrator regarding this.

Hi again, I'm not suggesting anything actually, just asking the question of if Microsoft plan to make this possible.  It isn't possible today, and this article is accurately written, in that it states all of the supported source computer configurations for RDP'ing to an Azure AD joined PC (workgroup PC's aren't in the list, and they cannot (tried/tested/confirmed)).

In the nicest way, I can't understand how I'm being understood.  I would say let's just move on and it's seemingly unlikely that workgroup PC's will be added to the list of allowed source computers.

Btw, the article has a clear section concerning exactly the topic that I'm asking about.  But we might as well just start taking about something else :|.
