### ISSUE TITLE
Virtual Machines NOT supported!

### ISSUE THREAD

**Issue by Neckross** [MicrosoftDocs/windows-itpro-docs#3868]
really??? how do you expect us to test White Glove... using a "neanderthal" physical device?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5b57d1-61b3-39d4-34ff-d6dcb858c250
* Version Independent ID: 42609104-815f-9e7a-39aa-38d92cc910c9
* Content: [Windows Autopilot for white glove deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove)
* Content Source: [windows/deployment/windows-autopilot/white-glove.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/white-glove.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by hkusulja** [comment]
I think this is due to TPM 2.0 from Hyper-V is not supported, technical limitation of Hyper-v?

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello @Neckross 

Thank you for providing feedback.

The issues section of this repository is intended for documentation problems.

Please consider opening a product feedback ticket for any of your product feedback or feature requests to help Microsoft improve your experience. Find the link to Feedback Hub below:

[Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

Thanks.

**Comment by pminnebach** [comment]
@hkusulja The documentation only mention that in self-deploying it is required to have the TPM 2.0. Nowhere is this requirement stated for white-glove.

@e0i In that case, consider changing the docs to reflect the actual limitations (VM?) and considerations for testing the white-glove feature w/o having to use physical devices.

**Comment by greg-lindsay** [comment]
Under the requirements section in the white glove documentation (this page) it says:

"Physical devices that support TPM 2.0 and device attestation; virtual machines are not supported."
