### ISSUE TITLE
Unknown OS architecture when runnig on non-english OS

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#3869]
Got the following error when running on non-English OS

Machine is not Device Guard / Credential Guard compatible because of the following:
Unknown OS, OS Architecture failure..

Reason: the script expects '64-bit' with a lower b, on a German client, the result is '64-Bit' with a capital B

**Solution**

Change the code in the CheckOSArchitecture function in the \DG_Readiness_Tool_v3.6.ps1 script as following

from 
$OSArch = $(gwmi win32_operatingsystem).OSArchitecture

to 

$OSAch = $((gwmi win32_operatingsystem).OSArchitecture).tolower()

then the script just works fine. 

Details here:
https://www.verboon.info/2019/05/the-case-of-running-the-device-and-credential-guard-hardware-readiness-tool-and-unknown-architecture/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
@alexverboon thanks for raising this issue.
This sounds like it might be a product issue more than a doc issue, however, it's good that we're aware so that we can address it properly.

@SteveSyfuhs - should I add a note here?

**Comment by SteveSyfuhs** [comment]
Yep, that should be noted as an issue. I'll open an internal bug too.

________________________________

**Comment by DaniHalfin** [comment]
Note added. Thanks again, @alexverboon .

**Comment by illfated** [comment]
Ref. #4084
