### ISSUE TITLE
SSU: ADK requires a dedicated Technet and MSDN subforum & category, external from "Insiders"

### ISSUE THREAD

**Issue by NeoBeum** [MicrosoftDocs/windows-itpro-docs#3882]
The SSU documentation and ADK documentation should be and have more dependency on each other as well as a dedicated ADK community section where bugs can be reported publicly in real time, as the Feedback hub is inadequate, and the Insiders hub is next to useless.

The SSU from 18362.1 and KB4500109 (18362.116) had a **SEVERE** issue where components were not reinstalled during offline servicing of the recovery image.

KB4498523 attempted to resolve this - however the Operating System image encountered errors with DISM instead.

KB4500109 ISSUE: https://answers.microsoft.com/en-us/windows/forum/windows_10-update/windows-1903-dear-microsoft-please-remember-to/e9e9e28a-c3f6-4e24-a900-f48a85b20431?tm=1558465537818

KB4498523 ISSUE: https://answers.microsoft.com/en-us/windows/forum/windows_10-update/dear-microsoft-please-ensure-that-windows-10-1903/d8d5492b-af07-4544-a37b-e76ac101e91f?tm=1559325739960

## The Windows Feedback hub is inadequate due to the fact that there is no acknowledgement that the Feedback has been received by the correct team, nor if there is even acknowledgement of feedback being read.

This is not the first time the SSU has permanently removed critical component packages. 

The ADK testing should be a foundation and pinnacle... ASSESSMENT AND DEPLOYMENT.
Debugging and Tracing through the DISM log, I am willing to place money on the fact that a bulk of the issues stem from bandaid solutions set in place by people who do not want to take the blame for the error and faults in the existing ecosystem.

Both of the SSU KB pages quote fixes, that I have explicitly tested  and given evidence to support that the fixes haven't fixed the underlying issue.

Unattended.xml still causing issues: https://support.microsoft.com/en-us/help/4500109/windows-10-update-kb4500109
Proof: https://techcommunity.microsoft.com/t5/WinHEC-Online/ADK-18362-1-DISM-Fails-Offline-Install-for-kb4497936-kb4505057/m-p/569470?search-action-id=89024127053&search-result-uid=569470
> E:\WinROG\windows10.0-kb4497936-x64_4ac9328bb1376d2cadb09f56ba95ac9b08b88fba.msu: An error occurred applying the Unattend.xml file from the .msu package.
> For more information, review the log file.

ResetBase Still Fails: https://support.microsoft.com/en-us/help/4498523/windows-10-update-kb4498523
Proof: https://techcommunity.microsoft.com/t5/System-Center-Configuration/Windows-10-0-18362-145-KB4498523-DISM-fails-offline-ResetBase/td-p/661335
> PS E:\WinROG> DISM /Image:mount\OS /Cleanup-Image /StartComponentCleanup 
> Deployment Image Servicing and Management tool
> Version: 10.0.18362.1
> 
> Image Version: 10.0.18362.145
> 
> Error: 0x800f0806

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b706f0af-d504-a8ca-7c38-b8bb9283bfad
* Version Independent ID: 14f31acf-9f47-59a6-269f-62ab249fe560
* Content: [Servicing stack updates (Windows 10)](https://docs.microsoft.com/en-au/windows/deployment/update/servicing-stack-updates#why-should-servicing-stack-updates-be-installed-and-kept-up-to-date)
* Content Source: [windows/deployment/update/servicing-stack-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/servicing-stack-updates.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
