### ISSUE TITLE
[LOC] 英語 (米国)  米国  "ja-JP" needs to be replaced with "en-US"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3883]
https://docs.microsoft.com/ja-jp/microsoft-edge/deploy/about-microsoft-edge
![about-microsoft-edge_j](https://user-images.githubusercontent.com/40815708/58750317-b87df200-84cb-11e9-8058-97e25d6d743b.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: d47bd063-dbf5-f628-3a13-4602583fb750
* Version Independent ID: 9dad7d24-7e1b-73ec-819b-9760a23f33db
* Content: [IT 担当者向け Microsoft Edge](https://docs.microsoft.com/ja-jp/microsoft-edge/deploy/about-microsoft-edge)
* Content Source: [browsers/edge/about-microsoft-edge.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/about-microsoft-edge.md)
* Product: **edge**
* Technology: **microsoft-edge**
* GitHub Login: @eavena
* Microsoft Alias: **eravena**

**Comment by illfated** [comment]
Nothing in the source to explain why that column content is wrong on that line. 
The preceding text is "| English (US) | US | "
Could be a copy-paste mistake, but I don't know how the translation script works. 
Looks like it only needs a manual edit for the ja-jp page.

**Comment by hyoshioka0128** [comment]
en-us:"https://docs.microsoft.com/en-us/micros
![about-microsoft-edge_e](https://user-images.githubusercontent.com/40815708/58757010-940f2d80-853e-11e9-880d-8d66a9fbc0dc.png)
oft-edge/deploy/about-microsoft-edge"

**Comment by illfated** [comment]
Yes, that is more or less what I tried to say. Let us hope that @dongmicro can take a look at this localization issue.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot unassign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
私は人間の翻訳のためにこの記事を送った。 約2週間かかります。 (I sent this article to be human translated.  It should take approximately 2 weeks.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by illfated** [comment]
(excerpt from the table)

言語 | 国/地域 | コード
-- | -- | --
英語 (英国) | 英国 | en-GB
英語 (米国) | 米国 | en-US

Looks like it has been resolved to me. Thanks.

**Comment by hyoshioka0128** [comment]
@TinaMcN @illfated  - Corrected.
Closed #3883.
Thanks.
