### ISSUE TITLE
[LOC] Showing "指定可能な値: **","0**" (extra asterisks appears)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3884]
https://docs.microsoft.com/ja-jp/microsoft-edge/deploy/microsoft-edge-kiosk-mode-deploy

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f840fa14-a379-d297-c3f7-ada05ec299d6
* Version Independent ID: 81396f7b-7506-43cd-fd9a-4066719a6eb2
* Content: [Microsoft Edge キオスク モードの展開](https://docs.microsoft.com/ja-jp/microsoft-edge/deploy/microsoft-edge-kiosk-mode-deploy)
* Content Source: [browsers/edge/microsoft-edge-kiosk-mode-deploy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/microsoft-edge-kiosk-mode-deploy.md)
* Product: **edge**
* Technology: **microsoft-edge**
* GitHub Login: @eavena
* Microsoft Alias: **eravena**

**Comment by illfated** [comment]
See also #3159 for details.
Similar issues: #3394 #3407 #3408 #3451 #3452 #3453 #3612 #3662 #3663 #3665 #3691

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @TinaMcN
@officedocsbot add label localization

**Comment by e0i** [comment]
Manually verified to be fixed.

**Comment by TinaMcN** [comment]
@e0i this issue is not fixed yet.  In the ConfigureKioskResetAfterIdleTimeout section the following unwanted asterisks appear
指定可能な値: **
0** -アイドルタイマーがありません

![image](https://user-images.githubusercontent.com/53281468/67046343-e9f70300-f0e4-11e9-972f-8f834e250721.png)

This is a problem with the MT tool.  I have reported the problem to the tool owners.   I don't expect this issue to be fixed quickly.  I will update when we have a fix.
 これは MT ツールの問題です。 私はツールの所有者に問題を報告しました。  この問題がすぐに解決されるとは思いません。 修正が必要になったときに更新します。

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 問題が解決したことを確認してください。 フィードバックをありがとう。
(The article is now human translated. Please verify that the issue is fixed. Thanks again for the feedback.)

**Comment by illfated** [comment]
There are still 4 occurrences of 2 asterisks in combination with the text `指定可能な値: **`
so it does not appear to be corrected yet. This is the result when I looked at the page
- https://docs.microsoft.com/ja-jp/microsoft-edge/deploy/microsoft-edge-kiosk-mode-deploy

... and I used Ctrl+F to find the text combination.

The page contains 9 occurrences in total where 2 asterisks `**` are showing up where they should be formatting characters to render the text as **bold**.

**Comment by hyoshioka0128** [comment]
@TinaMcN  - Not Fixed. (Same as 18 Oct)
![microsoft-edge-kiosk-mode-deploy](https://user-images.githubusercontent.com/40815708/69840956-ae815400-12a0-11ea-8403-33938634ab52.png)

**Comment by TinaMcN** [comment]
@hyoshioka0128 ご不便をおかけして申し訳ありません。 ローカリゼーションベンダーに問題を解決するよう依頼しました。 (Sorry for the inconvenience.  I asked the localization vendors to fix the issue.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 これで問題が修正されました。 フィードバックをありがとう。 (The issue has now been fixed.  Thanks again for the feedback.)

**Comment by illfated** [comment]
Yes, this issue is resolved now. I did not find any more double asterisks ( ** ) in the document article.

**Comment by hyoshioka0128** [comment]
@TinaMcN  - Corrected.
Closed #3884.
Thanks.
