### ISSUE TITLE
[LOC] "AllowFullscreen スクリーン" needs to be replaced with "AllowFullscreen"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3886]
https://docs.microsoft.com/ja-jp/microsoft-edge/deploy/microsoft-edge-kiosk-mode-deploy
![microsoft-edge-kiosk-mode-deploy_j2](https://user-images.githubusercontent.com/40815708/58750549-d731b800-84ce-11e9-96d8-f9b3142367c1.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f840fa14-a379-d297-c3f7-ada05ec299d6
* Version Independent ID: 81396f7b-7506-43cd-fd9a-4066719a6eb2
* Content: [Microsoft Edge キオスク モードの展開](https://docs.microsoft.com/ja-jp/microsoft-edge/deploy/microsoft-edge-kiosk-mode-deploy)
* Content Source: [browsers/edge/microsoft-edge-kiosk-mode-deploy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/microsoft-edge-kiosk-mode-deploy.md)
* Product: **edge**
* Technology: **microsoft-edge**
* GitHub Login: @eavena
* Microsoft Alias: **eravena**

**Comment by illfated** [comment]
See #3885 (same issue & same page) - this issue could be merged into #3885 .

**Comment by hyoshioka0128** [comment]
@illfated I understand "update this page by adding comments". 

I'm poor English. Thank you for commenting exactly that I did not write in English.

**Comment by hyoshioka0128** [comment]
Add the same page & same table
 1 "AllowPrelaunch 起動*"→"AllowPrelaunch*"
 2 "AllowTabPreloading 事前読み込み*"→"AllowTabPreloading*"
 3 "エクスペリエンス/機能の同期設定\ * とエクスペリエン/PreventTurningOffRequiredExtensions*"→
    "Experience/DoNotSyncBrowserSettings* と Experience/PreventTurningOffRequiredExtensions*" 
 4 "LockdownFavorites お気に入り"→"LockdownFavorites"

Mistranslations occur with or without an asterisk at the end of the sentence.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot unassign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 問題が解決したことを確認してください。 フィードバックをありがとう。
(The article is now human translated.  Please verify that the issue is fixed.  Thanks again for the feedback.)

**Comment by illfated** [comment]
The MDM Setting `AllowFullscreen` is now only followed by an asterisk ( `*` ) .
This issue looks resolved to me.

**Comment by hyoshioka0128** [comment]
@TinaMcN @illfated - Fixed.
Closed #3886.
