### ISSUE TITLE
Version numbers?

### ISSUE THREAD

**Issue by KjetilEVRY** [MicrosoftDocs/windows-itpro-docs#3889]
Please include version numbers and dates, so we can keep a track of new versions. Since the last update date of this page was 05.31.19, did you just released a new preview version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7a3b63b-afc5-1b25-3a30-e75c788f4a93
* Version Independent ID: 85498c85-fe13-fead-3bac-44db5614db0d
* Content: [Microsoft Defender ATP for Mac](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by annerajb** [comment]
I am on 100.42.86 and it's showing that I will stop recieving protection in  58 days and to update.

The typo on protection is also in the app...So far I haven't found a new update package available.

**Comment by robhardman** [comment]
Same.

**Comment by martyav** [comment]
We're trying to keep it short and sweet on that page, but I'll check to see if there's another appropriate page for listing more complete details and dates

**Comment by robhardman** [comment]
Just a note to say that mine updated this morning to 100.45.69 all by itself (no re-deployment with Intune required, at least.)

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@martyav Any updates with this issue? We would like to follow-up. Thanks.

**Comment by maximvelichko** [comment]
The original request was addressed with [the whatsnew page](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-whatsnew), this issue can be closed now.

**Comment by illfated** [comment]
There has been more than 10 updates to the page since this issue ticket was opened, also the file path of the page updated, both with the change from the `master` branch to the `public` branch, and the name change to Microsoft Defender ATP.

#please-close
