### ISSUE TITLE
Now I came to know the reason 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#3890]
From many months I have thinking that why Microsoft released Ssu  and clu together. After reading this article, I come to know background benefits of SSU.
thanks to all authors for explaining details.
I would happy ,  if authors will proVide video lecturers..

I love  reading articles from this site 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b706f0af-d504-a8ca-7c38-b8bb9283bfad
* Version Independent ID: 14f31acf-9f47-59a6-269f-62ab249fe560
* Content: [Servicing stack updates (Windows 10)](https://docs.microsoft.com/en-in/windows/deployment/update/servicing-stack-updates)
* Content Source: [windows/deployment/update/servicing-stack-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/servicing-stack-updates.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@RAJU2529 

Thank you for providing positive feedback about the articles. Much appreciated.

**Comment by e0i** [comment]
@officedocsbot close
