### ISSUE TITLE
Wrong setting for Java permission

### ISSUE THREAD

**Issue by My-userid** [MicrosoftDocs/windows-itpro-docs#3896]
Windows Components / Internet Explorer / Internet Control Panel / Security Page / Locked-Down Trusted Sites Zone | Java permissions |

You have the setting: 
Enabled: Enable

It should be Enabled | and one of the Java security settings:  High, medium,low, custom, Disable

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@My-userid 

Somehow your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by My-userid** [comment]
Link is:

https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-security-configuration-framework/level-5-enterprise-security

**Comment by e0i** [comment]
@My-userid 

Thank you.

The issue has been noted and the document will be revised in the light of your feedback.

**Comment by Malind19** [comment]
@e0i The link provided seems broken.

**Comment by martyav** [comment]
I couldn't access the url, either. 

There is https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-security-configuration-framework/level-5-enterprise-administrator-security -- note "administrator" in the url.

But...that page does not include settings.

**Comment by illfated** [comment]
@My-userid : it would be most helpful if you could provide a working link to the page you refer to. Or better still, if you post the same statement as you wrote in your opening comment, but in the Feedback section of the correct page, it would be very useful with regards to getting the changes you requested applied to the correct page.

**Comment by e0i** [comment]
@My-userid 
We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.

Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
