### ISSUE TITLE
What is the meaning of error code: 0x80070490?

### ISSUE THREAD

**Issue by sdabbiru** [MicrosoftDocs/windows-itpro-docs#3897]
What is the meaning of error code: 0x80070490?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by sholek1** [comment]
I have had this issue for a while now, without resolution.  Likely, this is what you are experiencing:
https://answers.microsoft.com/en-us/windows/forum/all/we-cant-connect-to-server-to-setup-you-pin-right/a0536687-7db8-4ab4-95e6-be2ff7d97dd7

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@sdabbiru 

Would you confirm that the response provided by community answers your question? Thanks.

**Comment by sdabbiru** [comment]
No, because the thread referenced just captured the issue and has no resolution.

**Comment by e0i** [comment]
@sdabbiru 

Thank you for submitting feedback.

In our understanding the error code that you have noted might actually have surfaced from other services rather than Windows Hello itself, and thus is not listed in this page.

Find below a quoted reply from a Content Developer:

DaniHalfin wrote:

>   For error codes unlisted here, in most cases those are transient error codes
>   being surfaced by other services in the Windows Hello dependency chain.

>   We are working on something to improve the user experience in that regard,
>   but that will not solve the issues you are experiencing.

>   If we find a reoccurring error codes that isn't covered here and should be
>   (meaning, in most cases, it is coming from Windows Hello and not other
>   components) we'll make sure to add it to this page.

We are closing this issue but feel free to re-open it if you feel that we might have missed something.

Have a nice day.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by andrePKI** [comment]
Mmm, don't really care where the error comes from. It is displayed when setting up the WHfB PIN, hence I would like to have an explanation HERE so I can find ways to resolve it.
And yes, screenshot is outdated.
I experience 0x80070490 (We can't connect to the server) too, and I have no idea where to look.

**Comment by illfated** [comment]
Regarding the outdated image: Would you be able to provide an updated example by posting one or more images here?

**Comment by andrePKI** [comment]
RESOLVED: As it turns out, just waiting to several sync jobs have run in the background resolves this after a reboot.
So just wait (could be up to 90 minutes) then try again. Error message and information around it is not very helpful IMHO.

**Comment by andrePKI** [comment]
correct screen shot is in this thread: [https://answers.microsoft.com/en-us/windows/forum/all/we-cant-connect-to-server-to-setup-you-pin-right/a0536687-7db8-4ab4-95e6-be2ff7d97dd7?auth=1&rtAction=1564563317231](url)

**Comment by illfated** [comment]
Fair enough. Thank you for the feedback.

![6f409915-a504-44e2-b983-1b587c22d409](https://user-images.githubusercontent.com/38162891/62212308-bdaece80-b3a0-11e9-8151-72a12b432a02.png)
