### ISSUE TITLE
Broken MVA Video lnk

### ISSUE THREAD

**Issue by Scriptimus** [MicrosoftDocs/windows-itpro-docs#3898]
I already reported this issue and it was closed, yer there is still a broken link on this page. "Credentials protected by Windows Defender Credential Guard"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87ec66f8-6598-5751-a10f-55951c08b3ff
* Version Independent ID: c3bb99fb-ec6f-638f-fb26-af3142f5d49c
* Content: [Protect derived domain credentials with Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by Scriptimus** [comment]
There are actually 2 MVA links on this page that I can see.

**Comment by martyav** [comment]
The correction was made, but it looks like the new version of the page hasn't been published yet...

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @Scriptimus 

Relevant modifications to the issue(s) you have submitted have been made and it make a while for repository changes to go live.

We are marking this issue as resolved as it has been addressed via the following commit:

[[f6acb1a ] addressing broken mva links, #3817 ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/f6acb1a1c6070620a799acd30fbb7aedcd8ecf1f)

See the reference issue: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3513

Thank you for bringing the problems to attention.

**Comment by e0i** [comment]
@officedocsbot close
