### ISSUE TITLE
Microsoft Edge section - non-relevent info

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/windows-itpro-docs#3899]
"You can silently enable BitLocker for standard Azure Active Directory-joined users. You can also more easily manage the entire Microsoft 365 experience for users with the Microsoft 365 Admin Center." I don't think we mean to have those two sentences under the Edge title.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 095d9daa-2d4e-7442-13a1-79d15b313ad7
* Version Independent ID: c33e2393-9f53-d896-e154-42058ecf4dbf
* Content: [What's new in Windows 10, version 1903](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1903)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1903.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1903.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by GenieInfoDZ** [comment]
Bonjour,
J'ai le message d'erreur 0x800736cc lors de l'installation de la mise à jour 1903 de Windows 10.
C'est quoi le problème et la solution a appliquée ?

**Comment by illusivebubble** [comment]
My laptop, shuts down during the connection to ethernet

**Comment by illfated** [comment]
@npherson & @e0i : This issue was resolved in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/0b265caa5968f690d6e41f5b7bcd9be1e3d4fc51#diff-8123aa7ecc5772e2b319fa002a9121c3 , so this ticket can be closed. The 2 comments above mine are completely unrelated to the original issue.

**Comment by Reeced40** [comment]
@illfated Thank you.

**Comment by e0i** [comment]
@npherson 

This issue has been addressed with the following commit and content has been updated according to your feedback.

[[0b265ca ] fix edge and add system guard ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/0b265caa5968f690d6e41f5b7bcd9be1e3d4fc51)

We are thus closing this issue since it seems to be resolved. Feel free to re-open it if you feel it hasn't been resolved.

Thank you for taking the time to provide feedback.

**Comment by e0i** [comment]
@officedocsbot close
