### ISSUE TITLE
Running the connectivity troubleshooting script

### ISSUE THREAD

**Issue by msandbu** [MicrosoftDocs/windows-itpro-docs#3901]
There needs to be a bit more clearer in these ATP endspoints needs to be configured on the OMS Gateway as allowed hosts. And secondly, the endpoint winatp-gw-aus.microsoft.com is not published in Public DNS anymore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3b2994c-534b-7b08-78de-49e099cb18ac
* Version Independent ID: 33183a2c-fac9-8f53-028c-f5f05700107b
* Content: [Onboard servers to the Microsoft Defender ATP service](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @msandbu 

Would you be able to clarify what needs to be updated in the documentation? Is the document misleading?

We would like to follow-up with content updates accordingly.

Thank you for providing feedback.

**Comment by e0i** [comment]
@msandbu 

We are closing this issue as there hasn't been a response from your side regarding the specific details of the issue.

Feel free to re-open this issue by clarifying the details and we'd be glad to come up with content updates.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
