### ISSUE TITLE
Subscription Activation on devices without firmware-embedded keys

### ISSUE THREAD

**Issue by aseflova** [MicrosoftDocs/windows-itpro-docs#3904]
What is correct scenario for devices without firmware-embedded keys, but with Win 10 licence from MAK key? As far I was able to test it (Win10 1809), those devices will not automatically activate Win10 from subscription, but remain on MAK key/KMS. Is there a way to activate them manually? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-subscription-activation#feedback)
* Content Source: [windows/deployment/windows-10-enterprise-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-enterprise-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@asefl

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by stusims** [comment]
Hi guys, I think it's really important to address this issue in this document. I think you just need to add some guidance under Scenario 3 in the last paragraph talking about Windows 7 wipe-and-load as this is the exact scenario that is causing many people lots of confusion. I believe what is required is a statement around which product key should be loaded with the Win 10 image that is used in the wipe-and-load scenario for devices without firmware-embedded keys.

**Comment by illfated** [comment]
Fair point. Could you suggest how that text should be formulated to fit the existing text on this page?

**Comment by scerazy** [comment]
Being education I have KMS, abundance of MAK keys, O365 A3/A5 subscriptions. But existing Dell Latitude 7400 do come oddly with W10 Home key firmware embedded. All devices are on 1909 Education KMS activated. No matter what, I cannot get Subscription to show up in Activation (it is only KMS via your organization). I do login with A5 enabled user (could it be that my test user account exceeded the allowed activation count?)
