### ISSUE TITLE
PowerShell - Windows Defender - Lack of documentation

### ISSUE THREAD

**Issue by methodbox** [MicrosoftDocs/windows-itpro-docs#3906]
[Enter feedback here]

Normally, Microsoft documentation for PowerShell commands for common products usually includes actual examples of using the commands, not just a link to the cmdlet.

This page seems like a waste of space if it's just a reference to the cmdlet.

There's even this enticing line at the top, "You can use PowerShell to perform various functions in Windows Defender." ... Yes, but what functions, and how, and where are the examples? And why am I even on this page if I just need to go read the cmdlet docs? Just redirect me there instead of wasting two paragraphs of my time to link me there. It goes on to say nothing about how exactly you can do that except generically referencing PowerShell.

I can figure it out, it's just crappy documentation, IMHO.

It would be helpful to maybe expand upon this like other modules.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f5f37f-9e03-eac1-715b-4a01acfff33e
* Version Independent ID: b7e76481-3859-c8d1-c22d-ee238fadd1e9
* Content: [Use PowerShell cmdlets to configure and run Windows Defender AV](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/use-powershell-cmdlets-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/use-powershell-cmdlets-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/use-powershell-cmdlets-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by methodbox** [comment]
I'm kind of tired of seeing this on my profile and it's taking long enough that I just don't really care at this point so I'm closing it.
