### ISSUE TITLE
This page is out of date

### ISSUE THREAD

**Issue by A55imilat0r** [MicrosoftDocs/windows-itpro-docs#3912]
This page is out of date and missing what's new for 1803 , 1809 and 1903

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c3e60ec-cf61-c34b-db79-74b13e3ee867
* Version Independent ID: fc5079f7-a563-c627-3a3e-eb84a99e4fd3
* Content: [New policies for Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/new-policies-for-windows-10#feedback)
* Content Source: [windows/client-management/new-policies-for-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/new-policies-for-windows-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by RAJU2529** [comment]
Authors please update this article  for 1903 changed policy

**Comment by e0i** [comment]
@A55imilat0r 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by illfated** [comment]
Well, there are downloadable spreadsheets for 1803 and 1809, but I haven't checked yet if they contain enough information to build a complete new list for the docs page.
- 1803: https://www.microsoft.com/en-us/download/details.aspx?id=56946
- 1809: https://www.microsoft.com/en-us/download/details.aspx?id=57464

I have no idea if the 1903 spreadsheet is available yet.

**Comment by e0i** [comment]
@illfated Yes, The spreadsheet for 1903 is not yet available.

**Comment by e0i** [comment]
@A55imilat0r 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.
