### ISSUE TITLE
Understand the different apps included in Windows 10

### ISSUE THREAD

**Issue by hoskinsm** [MicrosoftDocs/windows-itpro-docs#3913]
Can the following doc be updated to include app information related to Windows 10 version 1903

https://docs.microsoft.com/en-us/windows/application-management/apps-in-windows-10

I attempted to add feedback requesting a 1903 update via GitHub but the reference appears to be closed and unable to add additional feedback.

thank you

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @hoskinsm 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
Similar: #4118

**Comment by illfated** [comment]
@hoskinsm : Feel free to join in on the discussion of the Pull Request material in #4153 if you have got useful opinions on how the 1903 tables should be presented.

**Comment by e0i** [comment]
Closing the issue as discussion happens through #4118 via #4153.
