### ISSUE TITLE
Express Updates

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/windows-itpro-docs#3921]
It appears Express Updates are no longer supported in favor of a "New Model" starting with 1809. Should the SCCM docs be updated to reflex this so the community has awareness.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb67e518-6f60-23e0-2545-c2839e2b4159
* Version Independent ID: e9a31629-e3cb-0367-31c4-5661284d89bf
* Content: [Configure Delivery Optimization for Windows 10 updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization)
* Content Source: [windows/deployment/update/waas-delivery-optimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-delivery-optimization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Addressed via PR #3921 that is part of a mass update. Thanks.

**Comment by illfated** [comment]
@e0i : I believe you got the # number from this ticket instead of the PR you mentioned. Not quite sure which commit hash or PR # that should have been.
