### ISSUE TITLE
Missing -quietinstall switch in Add-ProvisioningPackage

### ISSUE THREAD

**Issue by jeffdfield** [MicrosoftDocs/windows-itpro-docs#3922]
The Add-ProvisioningPackage section is missing the quietinstall option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9d3111-a801-5fbd-51fd-182c9fcde05d
* Version Independent ID: b6515ca3-15f5-5a24-0aea-612c0f5867ab
* Content: [PowerShell cmdlets for provisioning Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-powershell)
* Content Source: [windows/configuration/provisioning-packages/provisioning-powershell.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/provisioning-packages/provisioning-powershell.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@jeffdfield 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by e0i** [comment]
@jeffdfield  Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
