### ISSUE TITLE
Video is unavailable

### ISSUE THREAD

**Issue by thohun** [MicrosoftDocs/windows-itpro-docs#3924]
The video at the beginning of the page is unavailable

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d6356b-87ff-8c3a-56ef-1270a823d3ab
* Version Independent ID: 4d6ae878-66cf-0e10-bdf3-bdd6054cbc9d
* Content: [What's new in Windows 10, version 1809](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809#feedback)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1809.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1809.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by martyav** [comment]
For reference, the title of the missing video was, "What's new in Windows 10, version 1809 for IT Pros"

**Comment by greg-lindsay** [comment]
Thanks for noticing this! The issue has been fixed.
