### ISSUE TITLE
Doesn't Work With 1809

### ISSUE THREAD

**Issue by pstenger** [MicrosoftDocs/windows-itpro-docs#3937]
This process doesn't seem to work on Windows 10 1809 as the update now goes through the app store, which is blocked per WSUS. Is there another work around?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d4c6ca-ae3c-7750-f58b-0df996e41402
* Version Independent ID: 0d05fd22-b761-6fb4-8686-a2021573e542
* Content: [Enable or block Windows Mixed Reality apps in the enterprise (Windows 10)](https://docs.microsoft.com/en-us/windows/application-management/manage-windows-mixed-reality#feedback)
* Content Source: [windows/application-management/manage-windows-mixed-reality.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/manage-windows-mixed-reality.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@pstenger - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @pstenger Thank you for your query. Can you please elaborate your query in more detail so that I can better guide you.

Thanks.

**Comment by mypil** [comment]
@pstenger - We would like to follow up. Can you please respond to the query of joinimran?

**Comment by alltheRealities** [comment]
Hello. I am having the same issue. Here is what cmd spits out when I try to run the 1809 package:

C:\WINDOWS\system32>Dism /Online /add-package /packagepath:C:\Users\awilsonx097533\Downloads\microsoft-windows-holographic-desktop-fod-package31bf3856ad364e35amd64_1.cab

Deployment Image Servicing and Management tool
Version: 10.0.17763.1

Image Version: 10.0.17763.529

Processing 1 of 1 - Adding package Microsoft-Windows-Holographic-Desktop-FOD-Package~31bf3856ad364e35~amd64~~10.0.17763.1
[==========================100.0%==========================]
An error occurred - Microsoft-Windows-Holographic-Desktop-FOD-Package Error: 0x800f0954

Error: 0x800f0954

DISM failed. No operation was performed.
For more information, review the log file.

The DISM log file can be found at C:\WINDOWS\Logs\DISM\dism.log

**Comment by mypil** [comment]
@alltheRealities - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by pstenger** [comment]
Sorry I just saw these responses come through. How would I bypass the WSUS server?

**Comment by joinimran** [comment]
@pstenger You can exclude the test machine from WSUS Server and then try running the command to see how it goes.
