### ISSUE TITLE
HTML broken into code snippet

### ISSUE THREAD

**Issue by bashenk** [MicrosoftDocs/windows-itpro-docs#3938]
Everything from the end of Step 7 to the end is presented in a code snippet.
I assume line 523 from the present source HTML should be preceded by '&lt;pre&gt;&lt;code&gt;'
and current line 531 should close the above '&lt;/code&gt;&lt;/pre&gt;'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b67dd6d3-d9ee-c306-4cef-2e25562317dc
* Version Independent ID: 55afc90b-ffe8-a0a5-ca52-1c27bccc1796
* Content: [Step by step Surface Deployment Accelerator (Surface)](https://docs.microsoft.com/en-us/surface/step-by-step-surface-deployment-accelerator#feedback)
* Content Source: [devices/surface/step-by-step-surface-deployment-accelerator.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/step-by-step-surface-deployment-accelerator.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@bashenk - Thank you for submitting feedback. 

Pull Request #3941 has been created by @martyav to help fix this issue.
