### ISSUE TITLE
Hybrid Azure AD joined provisioning in a Certificate Trust deployment in a Managed environment

### ISSUE THREAD

**Issue by NagaCSC** [MicrosoftDocs/windows-itpro-docs#3942]
HCT - is always Federated domain with ADFS 2016. as far as I know HCT can not be implemented with managed domain. it has to be federated domain. we may need to correct the title as below
From: Hybrid Azure AD joined provisioning in a Certificate Trust deployment in a Managed environment
To: Hybrid Azure AD joined provisioning in a Certificate Trust deployment in a Federated environment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f170bfe-711d-f875-8d5f-a49d3d5113b2
* Version Independent ID: a75c9aa8-b47b-51dd-9b84-c63bb5c6b782
* Content: [How Windows Hello for Business works - Provisioning](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-provisioning#hybrid-azure-ad-joined-provisioning-in-a-certificate-trust-deployment-in-a-managed-environment)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-how-it-works-provisioning.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-how-it-works-provisioning.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@NagaCSC - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@NagaCSC - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
