### ISSUE TITLE
Intune now supports Windows 10 2019 LTSC?

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/windows-itpro-docs#3943]
Does this include all Intune features?  When configuring Windows Update for Business in Intune, LTSC is not a selectable channel on the servicing channel dropdown menu.  Is it not possible to deploy quality updates to Win10 2019 LTSC via Intune?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c696c9ed-b095-68ff-d50d-df345daf8a4a
* Version Independent ID: 50ad3b26-8e9b-6a56-7b3c-56c1374c4747
* Content: [What's new in Windows 10 Enterprise 2019 LTSC](https://docs.microsoft.com/en-us/windows/whats-new/ltsc/whats-new-windows-10-2019)
* Content Source: [windows/whats-new/ltsc/whats-new-windows-10-2019.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/ltsc/whats-new-windows-10-2019.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@russrimm - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@russrimm , Thank you for your query. With Semi-Anual Channel, LTSC will receive quality updates.  Please see this article https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/LTSC-What-is-it-and-when-should-it-be-used/ba-p/293181 

![image](https://user-images.githubusercontent.com/47118050/59248448-de2d9880-8c3b-11e9-9e3e-c2577e7f3b3a.png)

Thanks.

**Comment by mypil** [comment]
@russrimm - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by mypil** [comment]
@officedocsbot close

**Comment by xNiklasJern** [comment]
Hi @joinimran @mypi
Am I understanding this correctly if I sait that Intune supports Win10 2019 LTSC, BUT if you want to manage the update rings, you can only use SCCM?

**Comment by PhilipHaglund** [comment]
So if an Update Ring is configured (SAC) in Intune with 10 days deferred for Quality Updates and a target Windows 10 LTSC (2019). That machine will still receive Quality Updates on day 0? Reason for the question is that "Supported doesn't mean that it doesn't work."
