### ISSUE TITLE
Can't add AAD user

### ISSUE THREAD

**Issue by leonbrag** [MicrosoftDocs/windows-itpro-docs#3944]
As I commented on the closed issue, this does not work on 1809. 

Windows running in Azure VM is joined AAD (via add Connection to Work or School). But I can't add AAD user to allow RDP:

C:\Users\foo&gt;net localgroup "Remote Desktop Users" /add "AzureAD\testuser2@foo.onmicrosoft.com"

There is no such global user or group: AzureAD\testuser2@foo.onmicrosoft.com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc#feedback)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@leonbrag  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by SquirrelAssassin** [comment]
Same issue here.

**Comment by leonbrag** [comment]
Even after following  https://docs.microsoft.com/en-us/azure/active-directory/user-help/user-help-join-device-on-network#to-join-an-already-configured-windows-10-device and ensuring that machine is AAD join, I can add user using command line (but not normal UI, it seems normal UI in step 2 is not aware of AzureAD\UPN format.

But still cannot login using RDP

**Comment by joinimran** [comment]
@leonbrag Can you please share the screenshot of issues you are facing Like when AzureAD\UPN format is not recognizing. 

Thanks

**Comment by mypil** [comment]
@leonbrag - We would like to follow up. Can you please respond to the query of joinimran?

**Comment by SquirrelAssassin** [comment]
computer management -> groups-> administrators -> add -> enter in your format = not found

**Comment by leonbrag** [comment]
Yes, this is an error I got.
It’s the same error whether user is added via UI or via command line.

It’s worth mentioning that:

  1.  Connection to AAD was establish using credentials of user A
  2.  User A can be added via command prompt, while UI give Not found error
  3.  AAD has other users (B, C). These users cannot be added to due Not Found error (either via UI or command line)

**Comment by joinimran** [comment]
@leonbrag , Sorry for the inconvenience caused. I would suggest you open a support ticket with Microsoft to further address this issue ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:
https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

Thanks

**Comment by mypil** [comment]
@officedocsbot close
