### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by BroadcastMonsoon** [MicrosoftDocs/windows-itpro-docs#3945]
-The process for allow custom plugins has changed in the new version, you now do so from the security tab.
-The Secure Score tab is no longer present in the report and the tabs have changed from the ones in the article. Bonus points: give me back the secure score!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c94f17bc-9075-8816-0087-a58388c94266
* Version Independent ID: c024d528-b4bf-b069-c54f-764a04f27aa5
* Content: [Create and build Power BI reports using Microsoft Defender ATP data](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/powerbi-reports#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/powerbi-reports.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/powerbi-reports.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@BroadcastMonsoon  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @BroadcastMonsoon Thank you for your feedback. Can you please share the details of the new tabs or the information required to update this so that I can update the document accordingly.

Thanks.

**Comment by mypil** [comment]
@BroadcastMonsoon - We would like to follow up. Can you please respond to the query of joinimran?

**Comment by mypil** [comment]
@BroadcastMonsoon - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
