### ISSUE TITLE
Defender updates for Server 2019

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/windows-itpro-docs#3946]
This document says (below) Question is where to download from?
"You have non-Internet-connected devices (such as VMs). You can use your Internet-connected VM host to download the updates to a network share"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c033d14-427d-26d5-eca8-facf190da87d
* Version Independent ID: 624d52e5-6cf5-534e-83c3-66925292ddcd
* Content: [Manage how and where Windows Defender AV receives updates](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/manage-protection-updates-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/manage-protection-updates-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/manage-protection-updates-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@DSPatrick - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by DSPatrick** [comment]
Thank you. Is the Win10 ITPro the correct team? We're asking about manual download of defender updates for Server 2019

**Comment by joinimran** [comment]
@DSPatrick You can download updates from many sources mentioned in the document.
Microsoft Update
Windows Server Update Service (WSUS)
System Center Configuration Manager
A network file share
The Microsoft Malware Protection Center Security intelligence page (MMPC)

The last is on the internet. Where you will download the updates manually and then update Windows Defender. Once you have placed the downloaded files on any non-internet-connected VM and from there on you can file share those updates using procedure mentioned in the doc, like group policy or using powershell.

Thanks.

**Comment by DSPatrick** [comment]
"The last is on the internet. Where you will download the updates manually and then update Windows Defender."
This was the original question; where to manually download defender updates for Server 2019?

**Comment by joinimran** [comment]
@DSPatrick Please visit https://www.microsoft.com/en-us/wdsi/definitions and select the version of your Windows Defender to download the security updates. 

![image](https://user-images.githubusercontent.com/47118050/59212460-f239b180-8bcb-11e9-8a13-2b173b9d85e7.png)

Thanks.

**Comment by DSPatrick** [comment]
Thanks, I've been there but nothing listed for Server 2019

**Comment by joinimran** [comment]
@DSPatrick , I have checked and found that there is no option available to update Windows Server 2019 Windows Defender by manual updates. Please open a support ticket with Microsoft to address this issue.

@mypil , please guide the user how can he open a support ticket. 

Thanks.

**Comment by mypil** [comment]
@DSPatrick - I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by DSPatrick** [comment]
Thanks, but I'm asking on behalf of TechNet forums users. Users are wanting to download definitions for Server 2019 deployed in isolated / quarantined environment.

**Comment by joinimran** [comment]
@DSPatrick As of now, I was not able to find any info for the same. 

@mypil Can you please engage doc owner to see if there is any feedback from doc owner. Or maybe doc owner can find someone/team relevant to this request.

Thanks.

**Comment by mypil** [comment]
@Dansimp - Can you please share your insights on this issue?

Thank you.

**Comment by mypil** [comment]
@DSPatrick - If you have questions that are more support type questions about getting this up and running on your machines, I would suggest visiting [Microsoft Suppor](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)t for Windows 10 as we only handle the updating of the documentation here. If you do find that it is a documentation error though, feel free to comment back and we'll gladly look into fixing it. Thanks!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by DSPatrick** [comment]
I'm confused?? Why would I reach out to Windows 10 support for a Windows Server 2019 question? Its not that the document is in error it the simple fact we are missing a download source for Server 2019 Windows Defender updates.

**Comment by mypil** [comment]
@DSPatrick - Please understand that this site is a product documentation site and not a support nor a feature request site.

As such, the feedback section here is intended for feedback that improves the content in the Microsoft documentation and not intended for user feedback on product features nor troubleshooting.

For user feedback on product feature requests, you can submit via Feedback Hub - **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**. I know the product teams are always looking for user feedback on how to make Windows 10 better. You might find others have made a similar request that you can add to, or you can open a new one.

For technical queries or troubleshooting, you can visit **support.microsoft.com**, **answers.microsoft.com** or open a [support ticket](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10).

I hope this gets you pointed in the right direction. Thank you.

**Comment by DSPatrick** [comment]
Thanks, but I'm not asking for product support or a feature request. This document has links for defender updates for all operating systems *except* Server 2019. Wouldn't it make sense to add it here *if it exists*? If it doesn't exist or there are no plans for it then please spell that out here so users can stop looking.
