### ISSUE TITLE
Invalid XML provided

### ISSUE THREAD

**Issue by jeremyhagan** [MicrosoftDocs/windows-itpro-docs#3947]
The XML comment tags between line 60 and 87 of the XML file are malformed. There is a space between "&lt;!" and "--" meaning that this cannot be used programmaticaly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d71055e-2b14-227b-0107-c8f150194d5b
* Version Independent ID: 0eab18a0-7e8f-05eb-b47f-e6913682d8e8
* Content: [Microsoft recommended block rules (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jeremyhagan  - Thank you for submitting this feedback.

From our understanding, the issue has already been resolved based on the commit ([01558dc](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/01558dc28b9595c4ac702cf146ce7e091a6832b1)) made by @martyav. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
