### ISSUE TITLE
Broken "phishing attacks" link

### ISSUE THREAD

**Issue by ralish** [MicrosoftDocs/windows-itpro-docs#3958]
The link in the below bullet point is broken:
&gt; Users can inadvertently expose their passwords due to phishing attacks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e5f5f1-16cf-57e2-bdfc-b090d90437b1
* Version Independent ID: 1662c47f-12cb-147d-25f0-dee98b6c7722
* Content: [Windows Hello for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-identity-verification.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-identity-verification.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by ralish** [comment]
Same issue is also present on the Overview page:
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-overview

**Comment by illfated** [comment]
I tried to look for a page similar to the working link in the text
- Passwords are subject to [replay attacks](https://go.microsoft.com/fwlink/p/?LinkId=615674).

, but it may have been removed due to the development of Microsoft ATP and Office 365.

I wonder if this Docs page could be a practical replacement for the broken link:
https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/phishing

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @ralish 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by ojrb** [comment]
Hi @e0i the PR #4312 solved this issue, please review and Merge !

**Comment by illfated** [comment]
Fair enough, thank you for following up on my suggested link. Now we just need to see if this will be accepted by the Docs team authors and reviewers as a valid solution.

**Comment by e0i** [comment]
@ralish 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
