### ISSUE TITLE
Numerous grammar issues

### ISSUE THREAD

**Issue by ralish** [MicrosoftDocs/windows-itpro-docs#3959]
There's a lot of minor grammar issues throughout this page. A general review by an editor would be worthwhile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca080bd-ed37-60a8-ec22-b1929166ff0c
* Version Independent ID: d2742e0c-9d66-4b1f-8555-a1fb1546455b
* Content: [Password-less Strategy](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/passwordless-strategy)
* Content Source: [windows/security/identity-protection/hello-for-business/passwordless-strategy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/passwordless-strategy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by illfated** [comment]
Could you provide a few examples, just so we know what to look for? I have tried reading through the page, but I often find myself a bit tired or not quite prepared to detect minor grammar issues, unless they are obvious and blatant.

**Comment by ralish** [comment]
There's quite a lot. I spotted at least several dozen while reading through the article and wasn't actively searching for mistakes. A bunch of quick examples:

> With Windows Hello for Business deployed, it coexists with password nicely.

Bad grammar. Recommended rewrite:
*Windows Hello for Business co-exists with existing password-based security.**

> **THe** first step to password-less is providing an alternative to passwords.

Typo.

> Work with third-party software vendors to update their software to support federated identities or Windows integrated **authenticate**.

Should be _authentication_.

The article basically is sound but needs a good proofreading to fix various minor errors and add some polish.

**Comment by illfated** [comment]
Very well, thanks for the update. I will start a pull request with the current known issues and work from there. I usually spot more details while scanning the text to perform known changes.

**Comment by ralish** [comment]
Thanks @illfated. Not trying to be unhelpful here, just doing a thorough proofreading of a long document like this one takes quite a bit of time which I don't really have right now, but thought I'd at least flag it!

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Thanks for the PR, @illfated Much appreciated.

**Comment by illfated** [comment]
For those of you still following this issue, please consider taking a look at the current result file linked in my comment https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3973#issuecomment-507859950 .
