### ISSUE TITLE
[LOC] "用" needs to be replaced with "ATP"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3963]
ja-jp:https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac
![microsoft-defender-atp-mac_j](https://user-images.githubusercontent.com/40815708/59160225-a4ab3f00-8b0e-11e9-94f0-8e8c01fc148d.png)

en-us:https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac
![microsoft-defender-atp-mac_e](https://user-images.githubusercontent.com/40815708/59160219-99f0aa00-8b0e-11e9-8e95-9474eabecf11.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: d7a3b63b-afc5-1b25-3a30-e75c788f4a93
* Version Independent ID: 85498c85-fe13-fead-3bac-44db5614db0d
* Content: [Microsoft Defender ATP for Mac](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Looks reasonable. I agree with the suggestion above.
The current kanji seems to represent "use/need/apply/take" instead of being a _useful_ translation of "ATP".
I also presume it is preferred to use the full name of the Windows software service instead of using "サービス".

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot unassign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
@hyoshioka0128 英語と日本語の記事を更新しました。 ATP への参照は含まれていません。 翻訳された記事がOKかどうかを確認してください。 (The English and Japanese articles have been updated.  They do not contain the reference to ATP any more.  Please check if the translated article is ok now.)

**Comment by illfated** [comment]
Yes, the reported section was replaced with a different table layout 
for the service URLs in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/1a5b8386472ea6cebe910664687fd05543685bbd#diff-b4ccda4d2538c7de1e948b4327cb50bc 
on 2019-07-12 (but may have been reworked in an internal PR earlier).

**Comment by hyoshioka0128** [comment]
@TinaMcN @illfated Thanks.
ATP has been removed.
Closed #3963
