### ISSUE TITLE
InstallWindowsDefenderApplicationGuard

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#3971]
Can someone please inform the correct Custom CSP for InstallWindowsDefenderApplicationGuard??

Install or Uninstall as Strings it does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a60ddc1-46b6-0e0e-c51c-4d8daf13b8a3
* Version Independent ID: 76543649-84f0-c371-3a8d-4f8d87c7d859
* Content: [WindowsDefenderApplicationGuard CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/windowsdefenderapplicationguard-csp)
* Content Source: [windows/client-management/mdm/windowsdefenderapplicationguard-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/windowsdefenderapplicationguard-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **v-madhi**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by RAJU2529** [comment]
@schenardie click settings --windows security-apps and browser control -- install windows defender application guard.

i dont know about CSP . but above solution might help to you
I think this options will be available in enterprise

**Comment by schenardie** [comment]
Thanks for the help @RAJU2529 but that woks well for a handful of devices, i need to deploy more than 200 so its kind of a lot of work to do it manually.

**Comment by RAJU2529** [comment]
@schenardie . Try this method.  Mount the  windows  baseimage  say like   windows 10 1903  install.wim 
to a  another  directory .

mount the  image   install.wim with index to  directory add language packs  ,
add device drivers  .inf   only
add  windows update packs  like  clu and  ssu  in .msu  or  cab  files
set  required  edition 
install product key 
add  registry keys  by  loading registry hives 
then use  dism online  command  enable the windows defender application guard features.
reset the system components
make  default language 
then unmount the  image
export the  image to reduce and  optimize

AT last  take  modified windows 10 image say    masterimageinstall.wim  and  apply the image  by using 
boot  the computer with  windows 10 PE 1903  cd , apply the image to  desired computer. boot the computer  with audit mode ,  recheck all required  features  are  enabled , do some changes as you like .
after finished , do  sysperp  generalize image , shutdown the computer.
boot  the computer with  windows 10 PE  , recapture the  image say  install1903.wim   and save it to the   64GB pendrive .

again boot  the computer with  windows 10 PE 1903  cd , apply the image to  desired computers.

**Comment by schenardie** [comment]
Hi @RAJU2529 i dont have an image. All these devices are Azure AD only. There is no OSD, no image and no USB deployment happening.
Given the CSP is documented it should work. Sorry but i dont need alternate methods, only need to know how i can get the documented CSP working.

Thanks

**Comment by RAJU2529** [comment]
@schenardie,I  am sorry  . I dont use azure service.
let wait for days,  azure users might help with CSP  methods

**Comment by lindspea** [comment]
@schenardie Thank you for reaching out and helping improve MS Docs. Please have a look at this link and let me know if it answers your question regarding custom CSP - https://docs.microsoft.com/intune/endpoint-protection-windows-10.

**Comment by schenardie** [comment]
Hi @lindspea, i'm completely aware there is a method of deploying the same setting via endpoint-protection. I currently need to use the CSP to deploy the setting manually as documented. The only problem is it doesn't work following the recommendations above. The simple fact the endpoint protection profile works and these profiles are based on CSPs makes me believe there is just something wrong with this specific setting and there has to be a way to make it work via CSP. So this currently doesn't answer my question. But thanks for the effort.

**Comment by e0i** [comment]
Hello, @schenardie  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
