### ISSUE TITLE
What about setting access permissions on auditing entries?

### ISSUE THREAD

**Issue by rpremuz** [MicrosoftDocs/windows-itpro-docs#3975]
Steps 4 and 5 of this article do not say anything about setting access permissions while adding an auditing entry. By default "read & execute" access is given. What is the meaning of access permissions for auditing entries?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9794457c-74fc-bb69-b3d9-071becdfbda4
* Version Independent ID: 532a2e78-0acd-7b53-9bb1-e90f33788eba
* Content: [Apply a basic audit policy on a file or folder (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/apply-a-basic-audit-policy-on-a-file-or-folder#feedback)
* Content Source: [windows/security/threat-protection/auditing/apply-a-basic-audit-policy-on-a-file-or-folder.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/apply-a-basic-audit-policy-on-a-file-or-folder.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@rpremuz 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.
