### ISSUE TITLE
BCDBOOT Bios Switches not preserving order

### ISSUE THREAD

**Issue by schweizera** [MicrosoftDocs/windows-itpro-docs#3979]
any help on preserving bios settings. I have changed so the NIC is the first boot. after imageing it defaults back to windowboot manager at the top. 

Problem Area Preserving boot order
rem == Copy boot files to the System partition == 
W:\Windows\System32\bcdboot W:\Windows /s S:  /p

I have tried these switches in place of the /p above /d /addlast, /d, /addlast

Full job 
rem Deploy Windows 10 via DISM

set image=M:\Images\Windows\Win10\2019\install.wim
set partition_file=M:\Images\Windows\create_partitions_win10_ueifi.txt

rem == Partition Disk as UEFI ==
diskpart /s %partition_file%

rem == These commands deploy a specified Windows 
rem    image file to the Windows partition, and configure 
rem    the system partition. 
 
rem == Set high-performance power scheme to speed deployment == 
call powercfg /s 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c 
 
rem == Apply the image to the Windows partition == 
dism /Apply-Image /ImageFile:%image% /Index:1 /ApplyDir:W:\ 
 
rem == Copy boot files to the System partition == 
W:\Windows\System32\bcdboot W:\Windows /s S:  /p
 
rem == Copy the Windows RE image to the 
rem    Windows RE Tools partition == 
md R:\Recovery\WindowsRE 
xcopy /h W:\Windows\System32\Recovery\Winre.wim R:\Recovery\WindowsRE\ 
 
rem == Register the location of the recovery tools == 
W:\Windows\System32\Reagentc /Setreimage /Path R:\Recovery\WindowsRE /Target W:\Windows 
 
rem == Verify the configuration status of the images. == 
W:\Windows\System32\Reagentc /Info /Target W:\Windows

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@schweizera 

Your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Also note that the issues section of this repository is intended for documentation and content feedback.

For your  _support_ related questions or feedback, please visit, [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10).

Any documentation feedback is welcome.

Thanks.

**Comment by RAJU2529** [comment]
@schweizera 

 APPLY  IMAGE  TO HARDDISK

copy modified install.wim  and WinRE.wim  to  USB drive  F:\
go to bios
disable securemode , disable uefi boot , enable legacy boot mode , enable  CSM boot.
Boot with windows PE disk or usb pendrive 
diskpart  and enter

goto command prompt,
type diskpart

select disk 0
clean   (this will deletes  all partitions in Disk 0)
convert gpt
create partition efi size=1024
format fs=fat32 quick label="EFI"
assign letter="S"
create partition msr size=128
create partition primary size=211968
format fs=ntfs quick label="WINDOWS10_ENT"
assign letter="W"
create partition primary size=20480
format fs=ntfs quick label="RECOVERY"
assign letter="R"
exit

mkdir R:\Recovery\WindowsRE
mkdir R:\Sources


DISM.exe /Apply-Image /ImageFile:F:\install.wim /Index:1 /ApplyDir:W:\ /Name:Windows /CheckIntegrity /Verify /EA
or 
DISM.exe /Apply-Image /ImageFile:F:\install.wim /Index:1 /ApplyDir:W:\ /Name:Windows /CheckIntegrity 
or
DISM.exe /Apply-Image /ImageFile:F:\install.wim /Index:1 /ApplyDir:W:\ /

copy all the  contents to  R:\

delete default winre.wim from W:\

del W:\Windows\System32\Recovery\winre.wim 

xcopy /h F:\WinRE.wim R:\Recovery\WindowsRE\
xcopy /h F:\WinRE.wim R:\Sources\
register  bcdboot 
w:\Windows\System32\bcdboot C:\Windows /l en-us /s S: /f ALL

Register receovery environment                                                   
w:\Windows\System32\Reagentc.exe /setreimage /path R:\Recovery\WindowsRE /target W:\Windows /bootkey 3b00

W:\Windows\System32\reagentc.exe /setosimage /path R:\Sources\install.wim /index 1 /target w:\Windows


If error gets then try below 

W:\Windows\System32\Reagentc.exe /disable /target W:\windows


W:\Windows\System32\reagentc.exe /setosimage /path R:\Sources\install.wim /index 1 /target W:\Windows

find  bcd of  windows os guid for example
type BCDEDIT.EXE -V -ENUM  ALL

Windows Boot Manager
--------------------
identifier              {a9bc596c-b6c5-11e8-99fe-88566792d937}
device                  partition=\Device\HarddiskVolume10
path                    C:\WINDOWS\SYSTEM32\WINLOAD.EFI
description             Windows Boot Manager


find the identifier and then enter  below commands 

W:\Windows\System32\reagentc.exe /enable /osguid {a9bc596c-b6c5-11e8-99fe-88566792d937}
W:\Windows\System32\Reagentc.exe /info /target W:\windows

if windows re is registered then , type commands 
w:\Windows\System32\bcdboot C:\Windows /l en-us /s S: /f ALL

close and exit.
remove  windows PE and usb pendrive

i created windows 10 pe re 1903 , 
you can download  and use for personal 

for windows 10 1903 RE 64bit
https://drive.google.com/file/d/1-5_U479025_C_k7vajtOlbeRcFeAjUQr/view?usp=drivesdk

for windows 10 1903 PE 64bit
https://drive.google.com/file/d/1-1D0PLZ9bmN4N2Sw1wykSR8MIwXWsrjL/view?usp=drivesdk

**Comment by e0i** [comment]
@officedocsbot close
