### ISSUE TITLE
Requirements to use AppLocker: Windows 10

### ISSUE THREAD

**Issue by Crypt32** [MicrosoftDocs/windows-itpro-docs#398]
Reference article: https://docs.microsoft.com/en-us/windows/device-security/applocker/requirements-to-use-applocker

The table is incorrect in regards to Windows 10. Table says that Applocker can be configured and enforced on Windows 10. It is partially correct. Applocker can be **enforced** only on **Windows 10 Enterprise** SKU. It **cannot** be enforced on **Windows 10 Pro** or Home SKUs.

**Comment by Justinha** [comment]
@Crypt32 Sorry for delay. I confirmed with engineering Windows Pro can be managed via MDM.

**Comment by Crypt32** [comment]
Any relevant link on how to do that with MDM?

**Comment by Justinha** [comment]
I'll confirm with engineering but I think any MDM that can use the AppLocker CSP: https://docs.microsoft.com/en-us/windows/client-management/mdm/applocker-csp 
Also here is a third-party blog I found: https://www.petervanderwoude.nl/post/managing-applocker-on-windows-10-via-oma-dm/

**Comment by Crypt32** [comment]
Ok, this makes more sense. This means that it is impossible to use Applocker in workgroup without MDM.

**Comment by Justinha** [comment]
Can you use local security policy (SecPol.msc) for workgroup?

**Comment by Justinha** [comment]
@Crypt32 I'm relaying a reply from Aaron Margosis, a security expert here at Microsoft: 

There is something weird about trying to change the configuration of appidsvc, at least using the Services.msc snap-in. Try one of these methods:

1. From an elevated Cmd or PowerShell:
sc.exe config appidsvc start= auto
2. Create a security template that configures appidsvc to be automatic start, and apply it using secedit.exe or LGPO.exe.
