### ISSUE TITLE
System/AllowStorageCard

### ISSUE THREAD

**Issue by JasonG-IT** [MicrosoftDocs/windows-itpro-docs#3980]
The description for "System/AllowStorageCard" first says it prevents programmatic access to the storage card, then a few lines later does it does NOT prevent programmatic access. Which is it?

Also, what exactly is considered a storage card? Is it any SD card, SIM (since they can store some data), an arbitrary mix, or is it defined by method of storage access?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c833e5b-0fcf-2ace-a90a-3270286d23a9
* Version Independent ID: 64afbc38-e7cc-fc14-9d57-1cd119b2395d
* Content: [Policy CSP - System](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-system#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-system.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-system.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **v-madhi**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by Reeced40** [comment]
@JasonG-IT Thank you for reaching out and helping improve MS Docs.  As far as I understand it's referring to an SD card.  The programmatic access is referring to the various values of the SD card, if I understand correctly.  Let me know if you agree or if you have any suggestions to make the article clearer.

**Comment by e0i** [comment]
Hello @JasonG-IT 

The issue is being closed since your support question seems to be answered. Feel free to re-open this issue if you still feel it hasn't been answered.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
