### ISSUE TITLE
[LOC] "時間" needs to be replaced with "時刻"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3982]
https://docs.microsoft.com/ja-jp/windows/configuration/wcd/wcd-time#provisionsettimezone
same page : #3961
![wcd-time_j3](https://user-images.githubusercontent.com/40815708/59241143-78440f80-8c41-11e9-959e-c52fd04f2c2f.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1c382e76-7804-b1a4-5df8-698c74d9c669
* Version Independent ID: 659759e4-80a7-2236-76fa-b3032adf1970
* Content: [時刻 (Windows 10)](https://docs.microsoft.com/ja-jp/windows/configuration/wcd/wcd-time)
* Content Source: [windows/configuration/wcd/wcd-time.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/wcd/wcd-time.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by illfated** [comment]
Definitely a Machine Translation issue. Translation of Japanese kanji is very much dependent on context.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone
@officedocsbot add label localization

**Comment by TinaMcN** [comment]
@hyoshioka0128 Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。

**Comment by TinaMcN** [comment]
@hyoshioka0128  記事は現在、人間が翻訳されています。 問題が解決したことを確認してください。 フィードバックをありがとう。 (The article is now human translated.  Please verify that the issue is fixed.  Thanks again for the feedback.)

**Comment by illfated** [comment]
時間 does not seem to appear on this page except for in the title of this issue ticket and in some hidden text (maybe in the metadata? - I don't know) and now also in this comment sentence.

Total: 3 occurrences, none of them in the openly visible page article.

**Comment by hyoshioka0128** [comment]
@TinaMcN  @illfated  - Corrected.
Closed #3982.
Thanks.
