### ISSUE TITLE
Thanks for the list 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#3985]
I say thanks to the authors for listing alMost all the apps and categories in to different groups.
I like to add more points here 

01. whenever users installs new or existing updating applications from the Microsoft store. those apps are  installed into  Windowsapps folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce0131fb-6b3a-5905-1738-253cf37e3b2d
* Version Independent ID: cab448be-54ae-539e-22ba-3d202a468d4f
* Content: [Windows 10 - Apps](https://docs.microsoft.com/en-us/windows/application-management/apps-in-windows-10)
* Content Source: [windows/application-management/apps-in-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/apps-in-windows-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Thank you for your feedback.

**Comment by e0i** [comment]
@officedocsbot close
