### ISSUE TITLE
Thanks to shortorder cookie 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#3986]
I appreciate Mr shortorder cookie 
He has given registry key for enabling XPS  viewer.
I Noted into notepad and saved for future references. 
I believe this site must and should reach all the Microsoft Windows users.
Also I say to thanks to all authors for contriButes 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecb7910b-900c-49cb-46ae-0c1de7cf3df6
* Version Independent ID: 5f7b8dba-d1df-95b0-8e54-32a729a5cf27
* Content: [Windows 10 - How to add apps from Apps & features](https://docs.microsoft.com/en-us/windows/application-management/add-apps-and-features)
* Content Source: [windows/application-management/add-apps-and-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/add-apps-and-features.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @RAJU2529 

The issues section of this repository is intended for product documentation problems only 

Closing the issue as it is unclear what needs to be updated in the documentation.

**Comment by e0i** [comment]
@officedocsbot close
