### ISSUE TITLE
Wrong Powershell commands to install the Active Directory Certificate Services

### ISSUE THREAD

**Issue by WayneYangsa** [MicrosoftDocs/windows-itpro-docs#3987]
In this original document, 
The Powershell commands is "Add-WindowsFeature Adcs-Cert-Authority -IncludeManageTools" and "Install-AdcsCertificateAuthority". But they don't work as they are not correct.

The correct Powershell commands should be "add-windowsfeature adcs-cert-authority -IncludeManagementTools" and "Install-AdcsCertificationAuthority". Please kindly revise it .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c2db23f-22e0-de33-fb4a-31e33c75f7d0
* Version Independent ID: dc31a7da-9496-a0dd-0304-ec48e56e8557
* Content: [Windows Hello for Business Trust New Installation (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-new-install#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-new-install.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-new-install.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by WayneYangsa** [comment]
May I know why you close this issue? @martyav ?

**Comment by e0i** [comment]
@WayneYangsa The referenced commit, https://github.com/MicrosoftDocs/windows-itpro-docs/commit/0725bf71d6c2ddec851ca04e134cabbabbcb26d1 solves this issue. Thanks.
