### ISSUE TITLE
Mistake in steps

### ISSUE THREAD

**Issue by hrrysckr** [MicrosoftDocs/windows-itpro-docs#3988]
"Move the Recovery Database from Server A to Server B
Use Windows Explorer to move the MBAM Compliance Status Database Data.bak file from Server A to Server B."

The wrong file name has been used in this section. Presumably should be 'MBAM Recovery Database Data.bak' instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08f2f70e-6ccd-61ac-9431-d9b16022bdc5
* Version Independent ID: 7083e1c4-46f8-d2a1-0105-6dacb37e626f
* Content: [How to Move the MBAM 2.5 Databases](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/how-to-move-the-mbam-25-databases#feedback)
* Content Source: [mdop/mbam-v25/how-to-move-the-mbam-25-databases.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/how-to-move-the-mbam-25-databases.md)
* Product: **w10**
* Technology: **mdop**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
Good catch, that looks like a copy-paste mistake. Using Ctrl-F on the page reveals that there are 4 occurrences of `MBAM Recovery Database Data.bak` and 6 occurrences of `MBAM Compliance Status Database Data.bak` , making it very likely that there should be an equal amount (5 of each) of the 2 separate file names. The first appearance of "MBAM Compliance Status Database Data.bak" also shows up before it has even been mentioned as target of its own procedure further down on the page.

I will open a Pull Request to have that changed, based on 1 instance of a copy-paste mistake.
