### ISSUE TITLE
Updates for hololens-upgrade-enterprise.md

### ISSUE THREAD

**Issue by barlanmsft** [MicrosoftDocs/windows-itpro-docs#399]
Hi @jdeckerms - the Intune content in windows-itpro-docs/devices/hololens/hololens-upgrade-enterprise.md under **Edition upgrade using MDM** refers to the process in the Intune Classic portal. These steps have been relocated to Intune on Azure.

**Comment by jdatms** [comment]
Thanks, Barry, I've opened a task to update the procedure. I can't give an estimate of when it will happen - it will depend on the priority of other work items.
