### ISSUE TITLE
ADD LINKS AND SUGGESTIONS 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#3993]
I would like to add download links for 
01. windows 10 ADK 1903
http://download.microsoft.com/download/B/E/6/BE63E3A5-5D1C-43E7-9875-DFA2B301EC70/adk/adksetup.exe

02. Windows 10 PEAdds 1903
https://download.microsoft.com/download/E/F/A/EFA17CF0-7140-4E92-AC0A-D89366EBD79E/adkwinpeaddons/adkwinpesetup.exe

Suggestions 
01. I think , information about internet explorer administartion kit is not required in this article. 
02. Instead add  information microsoft edge deployment.
03. Please include the links about UEFI organisation link and wikipedia link
https://uefi.org/
https://en.wikipedia.org/wiki/Unified_Extensible_Firmware_Interface

After reading this article , i conformed UEFI Class 2 firmware is  embededed in my asus laptop. Thanks for the information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8147691b-a894-a315-2611-3972ea2bce4b
* Version Independent ID: 0244d044-157d-e588-7fe9-4d4eb7042a88
* Content: [Windows 10 deployment tools (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/windows-deployment-scenarios-and-tools)
* Content Source: [windows/deployment/windows-deployment-scenarios-and-tools.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-deployment-scenarios-and-tools.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Suggestion for the issue title (please avoid using ALL CAPS when writing an issue title):
**Add links and suggestions**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @RAJU2529 

Open Source contributions are always welcome. Feel free to create a PR for suggested improvements and we'll have it pass through technical review.

Thank you for taking the time to help improve the documentation. Much appreciated.

**Comment by e0i** [comment]
@officedocsbot close
