### ISSUE TITLE
CREATED  WINDOWS 10 PE AND  WINDOWS RE 1903

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#3994]
I successfully created  windows 10 PE 1903 bootable iso and  windows 10 RE 1903  bootable iso.
I want to contribute  those iso  as free of  cost .
I used only windows adk and peadds tools  to create and i included some applications  for personal use.
If anyone needs  those iso , users can download from online storage.

Thanks for the article and i wish all the authors to export their knowledge to docs.microsoft.com.
Thanks a lot .i love docs.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3354f6b4-1316-8af6-c7d9-0c2f9681b3f0
* Version Independent ID: 1efc63fe-8380-2113-7985-1775bcccd3be
* Content: [Windows ADK for Windows 10 scenarios for IT Pros (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/windows-adk-scenarios-for-it-pros)
* Content Source: [windows/deployment/windows-adk-scenarios-for-it-pros.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-adk-scenarios-for-it-pros.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Suggestion for the issue title (please avoid using ALL CAPS when writing an issue title):
**Created Windows 10 PE and Windows RE 1903**

**Comment by RAJU2529** [comment]
Ok sir, I will take care sir. Thanks for pointing out

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot close

**Comment by illfated** [comment]
@RAJU2529 : Thank you for the nice words regarding the documentation.

About the ISO files you offered to upload free of cost:
I recommend posting those in one of the community forum pages instead,
after finding the right forum thread/section and talking to the users there.

**Comment by RAJU2529** [comment]
@illfated. Will you give me the links sir , so i can able to post

**Comment by illfated** [comment]
I was mostly thinking about sites like https://answers.microsoft.com/ and https://social.microsoft.com/Forums/ .

**Comment by illfated** [comment]
OK, fair enough. Then I don't have much else to recommend. Maybe you could look around and see if there are any related threads on the Microsoft Technet Forum pages (https://social.technet.microsoft.com/Forums/en-US/home)?
