### ISSUE TITLE
GPO Item Does Not Exist

### ISSUE THREAD

**Issue by vscurtis** [MicrosoftDocs/windows-itpro-docs#3995]
Expand Administrative Templates &gt; Windows Component, and select Windows Hello for Business.
In the content pane, double-click Use Windows Hello for Business. Click Enable and click OK. -&gt; there is nothing here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77ab668a-e750-0503-7c17-093d0ea43644
* Version Independent ID: 37e38b31-4599-3b00-230b-7a488ee71fb2
* Content: [Configure Windows Hello for Business Policy settings (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-key-trust-policy-settings)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-key-trust-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-key-trust-policy-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by RAJU2529** [comment]
@vscurtis Hey download and copy the latest administrative templates  to   C:\windows\policydefinations\

i have attached latest 1903 policies in en-US language

[PolicyDefinitions.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/3293083/PolicyDefinitions.zip)

**Comment by e0i** [comment]
@vscurtis Does this response provided by the community answer your question? We would like to follow-up. Thank you.

**Comment by RAJU2529** [comment]
its my community answer to Mr vscurtis

**Comment by e0i** [comment]
Hello, @vscurtis 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
@vscurtis 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
