### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by 1trevor** [MicrosoftDocs/windows-itpro-docs#3996]
How do I upload an ADMX file to Intune and use it to configure Intune-managed PCs? This is apparently the article that is supposed to explain that, but it doesn't explain how/where to create the policy in Intune. The article mentions building a "SyncML" payload, but I can't find any information on what a SyncML payload is or how to use that in Intune....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14d97fd9-b060-7bd5-1bc1-57efa474f75f
* Version Independent ID: be3a74fc-cac8-9b2c-dcc8-edc83cdf111f
* Content: [Enable ADMX-backed policies in MDM](https://docs.microsoft.com/en-us/windows/client-management/mdm/enable-admx-backed-policies-in-mdm#feedback)
* Content Source: [windows/client-management/mdm/enable-admx-backed-policies-in-mdm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enable-admx-backed-policies-in-mdm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
@1trevor : Have you read the content of the previous page,
https://docs.microsoft.com/en-us/windows/client-management/mdm/understanding-admx-backed-policies
and checked if you can find anything helpful to you there?

I noticed a tip one paragraph above this section (https://docs.microsoft.com/en-us/windows/client-management/mdm/understanding-admx-backed-policies#admx-files-and-the-group-policy-editor)
> 💡 **Tip**
>
> Intune has added a number of ADMX-backed administrative templates in public preview. Check if the policy settings you need are available in a template before using the SyncML method described below. Learn more about Intune's administrative templates.

**Comment by 1trevor** [comment]
Yes I have read that article as well. It doesn't have any details on how to configure this in Intune either. There are many places that point to these articles to get information on how to configure custom ADMX settings in Intune....but that information doesn't seem to be contained in these articles or anywhere else within the Microsoft documentation sites I can find.
The administrative templates in public preview do not contain the settings I need.

**Comment by illfated** [comment]
Fair enough. Would it help to read other pages to find out if there is any vital information missing in the current article page, for example https://osddeployment.dk/2019/01/02/how-does-a-custom-set-of-admx-based-policies-work-with-intune/ ?

**Comment by 1trevor** [comment]
Yeah I found that blog post and a few others, but they are very confusing and only give a few examples that don't cover enough scenarios. After spending several hours going through all the documentation and several 3rd party blog posts, I haven't been able to piece together enough information to migrate a single ADMX setting to Intune...

**Comment by illfated** [comment]
Well, unfortunately I don't know much about Intune or Enterprise scenarios myself, since it is mostly beyond my working experience, which is mostly direct user support. Have you tried checking with any of the Microsoft Support lines yet to ask for help with your problem?

**Comment by TomFromVA** [comment]
I'd like to add my voice to 1trevor's on this issue.  I'm trying to set configure Windows 10 1809 clients using Intune and want to manage settings that can only be managed via Group Policy.  I've reviewed all the documentation and blogs I can find, and cannot for the life of me figure out how to set this up.  Clearly the capability is there, but the "how to" is not documented, at least in a way that is understandable to customer administrators like me.

It would be super helpful is the documentation team and the Intune MDM team could get together with an admin who manages GPOs and doesn't program or generally even make his own XML files, teach the admin how to do this, and then write the documentation accordingly.  Then folks like myself could use this feature, which to be honest, we really need.

Thank you!

**Comment by Reeced40** [comment]
@1trevor @TomFromVA Thank you for reaching out and helping improve MS Docs.  I found a Technet article relating to this issue.  Please have a look and let me know if it helps at all. https://blogs.technet.microsoft.com/senthilkumar/2018/05/21/intune-deploying-admx-backed-policies-using-microsoft-intune/

**Comment by e0i** [comment]
@1trevor 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
