### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ryanprosser** [MicrosoftDocs/windows-itpro-docs#4000]
The shopping experience is not availalbe
Should be - available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e87bcd5-b9a2-b6b5-28c5-be13cc433732
* Version Independent ID: b204d5ef-fc3a-e77d-c1d1-137188acbcea
* Content: [Acquire apps in Microsoft Store for Business (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/acquire-apps-microsoft-store-for-business#feedback)
* Content Source: [store-for-business/acquire-apps-microsoft-store-for-business.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/acquire-apps-microsoft-store-for-business.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by illfated** [comment]
Thank you. That typo should be easy to fix. Please comment again if you find anything else on the same page.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @ryanprosser thank you for your feedback to help improve the contents of this document. We want users to have the best Windows 10 experience by ensuring the docs are accurate and free or errors! Your contribution is appreciated!

Please be informed that the typo fix (refer to this [commit](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4002/commits)) has already been submitted by @illfated , but it may make a while for the change to reflect on the document. For now, I will mark this issue as resolved. Thank you again.
