### ISSUE TITLE
Broken link: The Network Connection Status Icon

### ISSUE THREAD

**Issue by amandeepmand** [MicrosoftDocs/windows-itpro-docs#4003]
Broken link in section 14: The Network Connection Status Icon blog post on Technet was not migrated to the new Tech Community site
http://blogs.technet.com/b/networking/archive/2012/12/20/the-network-connection-status-icon.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abd3113-b803-87b6-ef7f-6893bcc5ceb5
* Version Independent ID: 6f7ca1ee-d19c-42bb-7db5-6158fc160e32
* Content: [Manage connections from Windows operating system components to Microsoft services (Windows 10)](https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services#feedback)
* Content Source: [windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @amandeepmand , thank you for letting us know about the broken link. I will get this issue over to the Windows writing team for correction. 

We want users to have the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, up-to-date and error-free. Suggestions, comments and feedback to improve the docs are always welcome!

**Comment by jvsam** [comment]
Hello @amandeepmand ! The link has been updated on the site and it's now redirecting to the new Networking blog (main page). We're checking if the old content has been migrated to the blog site, if so, we will request for the new URL to be added. Thank you again for taking the time to share your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hi again @amandeepmand, a *new* update to this documentation via Pull Request (PR) #4298 has been approved and merged. It will be displayed at docs.microsoft.com in the next scheduled publishing run. You can verify the changes at this URL: https://docs.microsoft.com/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services. We will now close this issue but we'll provide an update here to inform you when the changes are live.

Thank you for your feedback to help improve the contents of this document and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by jvsam** [comment]
Hi @amandeepmand, we'd like to inform you that the changes are now displayed at docs.microsoft.com. You can verify by visiting this URL: https://docs.microsoft.com/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services. Thank you for being part of the Microsoft Docs community!
