### ISSUE TITLE
White Glove Autopilot support?

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/windows-itpro-docs#4004]
"Windows 10 Enterprise LTSC 2019 builds on Windows 10 Pro, version 1809 adding premium features ",  Might white glove be one of these premium features that this build support?

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c696c9ed-b095-68ff-d50d-df345daf8a4a
* Version Independent ID: 50ad3b26-8e9b-6a56-7b3c-56c1374c4747
* Content: [What's new in Windows 10 Enterprise 2019 LTSC](https://docs.microsoft.com/en-us/windows/whats-new/ltsc/whats-new-windows-10-2019#windows-autopilot)
* Content Source: [windows/whats-new/ltsc/whats-new-windows-10-2019.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/ltsc/whats-new-windows-10-2019.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by greg-lindsay** [comment]
I will ask the product team to verify, but LTSC corresponds to 1809 as you've said, and white glove requires 1903 so given that, it would not be supported on LTSC until the next version of LTSC is released.

**Comment by greg-lindsay** [comment]
I have verified that white glove is not supported on LTSC 2019. It will be supported when the next version of LTSC is released.
