### ISSUE TITLE
[LOC]Hexadecimal number(16進数) is broken

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#4010]
![upgrade-error-codes_j](https://user-images.githubusercontent.com/40815708/59401732-a73fba00-8dd6-11e9-8bc5-4759eb914127.png)
"件" needs to be replaced with "1"
"両面" needs to be replaced with "2"

https://docs.microsoft.com/ja-jp/windows/deployment/upgrade/upgrade-error-codes
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b70118b1-730b-8e97-20a1-1d8cf0f33d53
* Version Independent ID: b3db47a2-df6a-03d0-1cdf-3e90017e7824
* Content: [アップグレードエラーコード-Windows IT Pro](https://docs.microsoft.com/ja-jp/windows/deployment/upgrade/upgrade-error-codes)
* Content Source: [windows/deployment/upgrade/upgrade-error-codes.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-error-codes.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by hyoshioka0128** [comment]
en-us:https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-error-codes
![upgrade-error-codes_e](https://user-images.githubusercontent.com/40815708/59402670-677ad180-8dda-11e9-867c-41b4dac967a3.png)

**Comment by hyoshioka0128** [comment]
Same page:(ja-jp)
![upgrade-error-codes_j2](https://user-images.githubusercontent.com/40815708/59402686-7eb9bf00-8dda-11e9-8892-cc3161ef7e59.png)
![upgrade-error-codes_j2](https://user-images.githubusercontent.com/40815708/59402730-a7da4f80-8dda-11e9-9f83-6e5d7464749e.png)

(en-us):
![upgrade-error-codes_e2](https://user-images.githubusercontent.com/40815708/59402739-ae68c700-8dda-11e9-9acd-f8c6a1dbceb2.png)

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by hyoshioka0128** [comment]
related issue: #3930

**Comment by e0i** [comment]
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
@hyoshioka0128 フィードバックをありがとうございました。 これは MT ツールの問題です。 私はツールの所有者に問題を報告しました。  この問題がすぐに解決されるとは思いません。 修正が必要になったときに更新します。(Thank you for the feedback.  This is a problem with the MT tool.  I have reported the problem to the tool owners.   I don't expect this issue to be fixed quickly.  I will update when we have a fix.)

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated. Please verify that it is fixed. Thanks again for the feedback)

**Comment by illfated** [comment]
Looks better, the value columns now contain valid hexadecimal notation. I don't know Japanese kanji well enough to say if the column title needs to be different:

![image](https://user-images.githubusercontent.com/38162891/72024657-26ff0b80-3276-11ea-9998-05814ce1c86e.png)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected. 
Closed #4010.
Thanks.
