### ISSUE TITLE
誤訳

### ISSUE THREAD

**Issue by KeikoSawada** [MicrosoftDocs/windows-itpro-docs#4012]
１、現在の表記「Windows 自動操縦」→正しい表記「Windows Autopilot」
２、「デバイスの登録」＞「各プラットフォームの機能の概要を以下に示します。」以下の表中、Intuneのプロファイル割り当て「うん*」→正しい表記「使用可能\*」

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8f8d5ab4-0b18-4f81-f579-a4fca2298a5f
* Version Independent ID: 252e3d58-27c5-6636-cf7f-e9e19067d0a2
* Content: [デバイスの追加](https://docs.microsoft.com/ja-jp/windows/deployment/windows-autopilot/add-devices#feedback)
* Content Source: [windows/deployment/windows-autopilot/add-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/add-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @KeikoSawada, we appreciate your feedback. @dongmicro please review. Thank you.

**Translation using online tool:**
1. The current notation "Windows autopilot" → correct notation "Windows Autopilot" 
**Comment:** From Windows 自動操縦 to Windows Autopilot

2. "Registering Devices" > "Here is an overview of the features of each platform: In the following table, Intune profile Assignment "Yes *" → correct notation "available *"
**Comment:** Refer to the platform's capabilities table, Intune row.

**Comment by jvsam** [comment]
@officedocsbot assign @dongmicro

**Comment by jvsam** [comment]
@officedocsbot assign @TinaMcN

**Comment by jvsam** [comment]
Hi @TinaMcN assigning this to you. Thank you.

**Comment by jvsam** [comment]
@officedocsbot unassign @dongmicro

**Comment by illfated** [comment]
@jvsam : Just a practical detail -- You can choose to assign + unassign in the same comment, if you want to. :-)

**Comment by TinaMcN** [comment]
@KeikoSawada フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 完了までに数週間かかる場合があります。

**Comment by TinaMcN** [comment]
@KeikoSawada 記事は現在、人間翻訳されており、問題は修正されているようです。 修正済みであることを確認してください。 フィードバックをありがとうございました。
(The article is now human translated and the issue appears to be fixed.  Please verify that it is fixed.  Thanks again for the feedback.)

**Comment by jvsam** [comment]
@TinaMcN shall we close this issue now?

**Comment by illfated** [comment]
Should be OK to close it, with a notice to the ticket author that the issue can be reopened if there are any unsolved details from the original report. (Uncertain if the ticket author will reply, seeing how long time ago it was reported and that this user has no Github activity since then.)

**Comment by jvsam** [comment]
@illfated since the original issue has been resolved, I agree. Thank you so much for your assistance @TinaMcN.

@KeikoSawada, thank you again for your feedback. We will now close this issue. Feel free to re-open or create another issue through the *feedback feature* if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
