### ISSUE TITLE
Supported Windows versions - Server 2008-R2 missing

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#4015]
The Supported Windows versions list does not include Server 2008-R2, however withn the MDATP Console, under the onboarding node, Windows Server 2008 R2 is listed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @alexverboon , thank you for bringing this to our attention. I will get this issue over to the Windows writing team for review and to investigate if Windows Server 2008 R2 indeed needs to be added to the documentation. I also requested the team to update this issue if we need additional information from you.

We want users to have the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, accurate and up-to-date. Suggestions, comments and feedback to improve the docs are always welcome!

**Comment by mjcaparas** [comment]
@alexverboon it's been updated. also check out: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints#windows-server-2008-r2-sp1--windows-server-2012-r2-and-windows-server-2016

**Comment by jvsam** [comment]
Awesome, thank you @mjcaparas !

Hi @alexverboon, again, thank you for your feedback and for helping us make the docs better!
