### ISSUE TITLE
Small change to help find

### ISSUE THREAD

**Issue by pilcherd** [MicrosoftDocs/windows-itpro-docs#4022]
Page here says:

Sign In -&gt; Click Manage. -&gt;Under Shopping Experience, set Show offline apps to On.

Offline apps has moved to Manage/Settings/Shop Settings. Which then has a Shopping Experience section.  Was confusing to find as there is no Shopping Experience from Manage.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ee50db8-eb08-7af7-d499-cbcc148620bd
* Version Independent ID: 208e007d-dfc0-b1b1-dd2b-4c101d572e09
* Content: [Distribute offline apps (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/distribute-offline-apps)
* Content Source: [store-for-business/distribute-offline-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/distribute-offline-apps.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @pilcherd , thank you for bringing this to our attention. I will get this issue over to the Windows writing team to verify the accuracy of the instructions. I also requested the team to update this issue if we need additional information from you.

We want users to have the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful and up-to-date. Suggestions, comments and feedback to improve the docs are always welcome!

**Comment by Reeced40** [comment]
@pilcherd Thank you for helping improve MS Docs, I will investigate further.

**Comment by jvsam** [comment]
Hi again @pilcherd, this is to inform you that the suggested update to this documentation via Pull Request (PR) #4404 has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
