### ISSUE TITLE
Got a suggestion link broken

### ISSUE THREAD

**Issue by giterdn** [MicrosoftDocs/windows-itpro-docs#4028]
The article suggests visiting http://mbam.uservoice.com/forums/268571-microsoft-bitlocker-administration-and-monitoring to add or vote on suggestions.  This link is broken (404: This UserVoice instance is no longer available.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13d23ed4-22a6-f0e3-d01f-a76e5fe04b20
* Version Independent ID: 859bf7a7-286f-010c-e315-15e1b6f59408
* Content: [About MBAM 2.5](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/about-mbam-25)
* Content Source: [mdop/mbam-v25/about-mbam-25.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/about-mbam-25.md)
* Product: **w10**
* Technology: **mdop**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @giterdn , thanks for bringing this to our attention. I will forward this issue to the Windows writing team to get the link updated.

And we would definitely love to hear your feedback regarding MBAM. Please submit your *voice* via the **new** Windows 10 [User Voice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub) hub. You feedback goes directly to the engineering team of the selected feature or product. 

Thank you for engaging with the community!

**Comment by jvsam** [comment]
Hi @giterdn I'd like to inform you that there's already a suggested update to this document via this [Pull Request](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4185). Once the suggestion gets approved, it will be displayed on the site.

Thank you again for taking the time to share your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hi again @giterdn. We will now close this issue. However, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation. Regarding the content update, we cannot confirm how long until it reflects on the site, it may depend on the volume of submissions but it will be there. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
