### ISSUE TITLE
Add WDAV requirement part in this page

### ISSUE THREAD

**Issue by GitMaggie** [MicrosoftDocs/windows-itpro-docs#4030]
Can you please add the requirement of WDAV solution in this page ?
https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-wd-av-status#windows-defender-data-latency
It's difficult to find the requirement when configuring the solution . Requirement can be found from troubleshooting part. But this should be pert of setup guide.
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/troubleshoot-reporting#confirm-pre-requisites

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32665050-e816-b1a9-225f-0fea575e3e1f
* Version Independent ID: a975c054-a956-99a4-679c-7ffccd205cd0
* Content: [Update Compliance - Windows Defender AV Status report](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-wd-av-status#windows-defender-data-latency)
* Content Source: [windows/deployment/update/update-compliance-wd-av-status.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/update-compliance-wd-av-status.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@GitMaggie - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by RAJU2529** [comment]
@GitMaggie .
I think  it  needed windows 10 enterprise  edition with paid  subscriptions of  
Microsoft Defender Advanced Threat Protection. And also  i think windows azure AD is needed .

In windows 10 home and pro this particularly this advanced feature is not available.

**Comment by mypil** [comment]
@GitMaggie - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
