### ISSUE TITLE
"両面" needs to be replaced with "2"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#4031]
related issue: #3930

ja-jp:https://docs.microsoft.com/ja-jp/windows/deployment/update/waas-configure-wufb
![waas-configure-wufb_j1](https://user-images.githubusercontent.com/40815708/59501597-d76e8200-8ed6-11e9-89a3-a00dc1f7c0f5.png)
"件" needs to be replaced with "1"
"両面" needs to be replaced with "2"

en-us:https://docs.microsoft.com/en-us/windows/deployment/update/waas-configure-wufb
![waas-configure-wufb_e1](https://user-images.githubusercontent.com/40815708/59501620-e35a4400-8ed6-11e9-85fa-766db9b86e4c.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1684b30a-3187-85ce-0cf7-10d1b8298b7f
* Version Independent ID: 9b7170fc-2b39-8e46-7898-894a45de8623
* Content: [Windows Update for Business の構成 (Windows 10)](https://docs.microsoft.com/ja-jp/windows/deployment/update/waas-configure-wufb)
* Content Source: [windows/deployment/update/waas-configure-wufb.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-configure-wufb.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by hyoshioka0128** [comment]
same page:
ja-jp:
![waas-configure-wufb_j2](https://user-images.githubusercontent.com/40815708/59548898-380dc580-8f90-11e9-8bcf-a51eaf718713.png)

en-us:
![waas-configure-wufb_e2](https://user-images.githubusercontent.com/40815708/59548902-40fe9700-8f90-11e9-916b-81fdd26769d1.png)

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot unassign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
@hyoshioka0128 フィードバックをありがとうございました。 これは MT ツールの問題です。 私はツールの所有者に問題を報告しました。  この問題がすぐに解決されるとは思いません。 修正が必要になったときに更新します。(Thank you for the feedback.  This is a problem with the MT tool.  I have reported the problem to the tool owners.   I don't expect this issue to be fixed quickly.  I will update when we have a fix.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 フィードバックをありがとうございました。 これは MT ツールの問題です。 私はツールの所有者に問題を報告しました。  この問題がすぐに解決されるとは思いません。 修正が必要になったときに更新します。(Thank you for the feedback.  This is a problem with the MT tool.  I have reported the problem to the tool owners.   I don't expect this issue to be fixed quickly.  I will update when we have a fix.)

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated. Please verify that it is fixed. Thanks again for the feedback)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #4031.
Thanks.
