### ISSUE TITLE
PowerShell examples - referencing protectors by array index

### ISSUE THREAD

**Issue by Sizzl** [MicrosoftDocs/windows-itpro-docs#4032]
Can I recommend updating the PowerShell examples to avoid referencing the keyprotector by array index (in this case [0]), as the required keyprotector is not always in that position.

I know these are just examples, but the code could be improved (in each instance) to be more immediately usable, as follows:

---
```
PS C:\>Add-BitLockerKeyProtector -MountPoint "C:" -RecoveryPasswordProtector

PS C:\>$BLV = Get-BitLockerVolume -MountPoint "C:"

PS C:\&gt;BackupToAAD-BitLockerKeyProtector -MountPoint "C:" -KeyProtectorId $(@($BLV.KeyProtector | Where-Object {$_.KeyProtectorType -eq "RecoveryPassword"}) | Select-Object KeyProtectorId).KeyProtectorId

```
---

```
PS C:\>Add-BitLockerKeyProtector -MountPoint "C:" -RecoveryPasswordProtector

PS C:\>$BLV = Get-BitLockerVolume -MountPoint "C:"

PS C:\>Backup-BitLockerKeyProtector -MountPoint "C:" -KeyProtectorId $(@($BLV.KeyProtector | Where-Object {$_.KeyProtectorType -eq "RecoveryPassword"}) | Select-Object KeyProtectorId).KeyProtectorId

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e5380a-53da-6df1-1952-1be89d9b5969
* Version Independent ID: 82af0c50-fb10-3ad3-1f1d-74a068ea6fa7
* Content: [BitLocker Management Recommendations for Enterprises (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises#feedback)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Sizzl - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @Sizzl, thank you for your valuable feedback.

I have been verifying your example and it's not totally applicable. If you have more than one RecoveryPassword it won't work because parameter type is String and not an array (e.g. String[]).
So you should specify the element using $BLV.KeyProtector[x]. More information and examples:
https://docs.microsoft.com/powershell/module/bitlocker/backup-bitlockerkeyprotector

My testing:
![image](https://user-images.githubusercontent.com/33589238/59955504-f9c94800-9460-11e9-831d-6f624befa5bd.png)

**Comment by Sizzl** [comment]
Yes - good shout, hadn't considered that there could be more than one recovery password... 

I'm still not sure why recommending an index would be the best approach though. The linked article gives an example using index 1; but the article this was raised against gives an example using index 0 (either of which may not even be of RecoveryPassword type in all instances).

I'm guessing in the example where there'd be multiple RecoveryPassword KeyProtectors, it'd make more sense to simply back them all up? Otherwise it seems a bit odd to just pick one ([0] or [1]); in this scenario would both be able to unlock the volume?

If so, I suppose a working script could simply iterate through each one instead.
 
`
PS C:\> @($BLV.KeyProtector | Where-Object {$_.KeyProtectorType -eq "RecoveryPassword"}) | ForEach-Object { BackupToAAD-BitLockerKeyProtector -MountPoint "C:" -KeyProtectorId $_.KeyProtectorId }
`

... Understand This has strayed quite a bit from the intention of the doc "example"; but I just wanted to emphasize that there are other types of KeyProtector which don't support backup and may fall into the example indexes (this was the reason I raised this - as index 0 per OP wasn't even a RecoveryPassword).

**Comment by dariomws306** [comment]
I think it's not a good idea to add this kind of complexity to an example. We should leave it as simple as possible.

To know the index number you should use you can run this command:
(Get-BitLockerVolume -MountPoint "C:").KeyProtector

**Comment by mypil** [comment]
@Sizzl - From our understanding, the issue you raised has been answered by dariomws306. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
