### ISSUE TITLE
Any method to prevent KMS rollover to Subscription Activation?

### ISSUE THREAD

**Issue by robhardman** [MicrosoftDocs/windows-itpro-docs#4034]
Consider the following scenario, a number of laptops in the enterprise are AAD joined and use subscription activation and it works fine. However, their users also occasionally hot desk to desktop machines, which are licensed separately with Win E3 Device and activate via KMS.

The desktop machines are mostly used by users within the enterprise who do not have cloud-based user licenses. At the first cloud-blessed user sign in, the activation type will transition to Subscription Activation. After 30 days, the machine will revert back to Pro, even though it is legitimately licensed for E3 Device.

How does one stop this happening? There appears to be no way to prevent the transition to Subscription Activation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-subscription-activation)
* Content Source: [windows/deployment/windows-10-enterprise-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-enterprise-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@robhardman - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by MamaDoc** [comment]
Thank you sincerely.   Confused a little,   I am sure simple answer.   I
continue to see windows 7 mentioned.   All my PC are less than 6 months
old.  Desktop now 4. Weeks. All windows 10.   I appreciate all your advice
& feedback.

**Comment by mypil** [comment]
@officedocsbot close
