### ISSUE TITLE
Can I use convenience PIN with Azure AD? - Yes

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/windows-itpro-docs#4037]
To quote from above - "No. If you want to use PIN or biometrics with Azure Active Directory identities on Azure AD registered, Azure AD joined, or hybrid Azure AD joined devices, then you must deploy Windows Hello for Business."

This is incorrect. I have Hybrid Azure AD joined devices using convenience PIN and Windows Hello (not for business) since they are children who can't verify themselves via the currently available methods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82ecd7ea-0ecb-cf7b-a1ab-9cda97e5cc0a
* Version Independent ID: 81acb0ad-2d46-bd0b-abb5-7c2e851d7a71
* Content: [Windows Hello for Business Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-faq)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-faq.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@hoyty76 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by TBBle** [comment]
Per [Can't configure a PIN when Convenience PIN and Hello for Business policies are enabled in Windows 10](https://support.microsoft.com/en-au/help/3201940/can-t-configure-a-pin-when-convenience-pin-and-hello-for-business-poli) and based on my experience hitting exactly this issue, you can *use* a Windows Hello PIN (and hence biometrics) that was configured before joining to Azure AD, but on Windows 10 1607 and later, you cannot set up a PIN while joined to Azure AD, nor can you change the PIN that was set.

The same "existing-Convenience-PINs-still-work" behaviour is present for Active Directory Domain-joined clients, but in Active Directory it's possible to use Group Policy to re-allow Convenience PIN support.

Clients that are both Domain-joined and AD-registered cannot set or change a PIN, but an existing PIN will continue to work.

**Comment by hoyty76** [comment]
That is correct but the key is this phrase "a user cannot create a convenience PIN in Windows 10 Version 1607 and later version when the Use Convenience PIN and Use Windows Hello for Business policies are both enabled". In Intune (yes you need Intune) you can set Windows Hello for Business to Not Configured. This was a recent change, previously it was only Enabled or Disabled.
<img width="791" alt="WHfB Settings" src="https://user-images.githubusercontent.com/39065296/59552709-4b447500-8f3f-11e9-820f-d3943376d24f.png">
When you set disabled it also disabled local Convenience PIN, but with Not Configured GPO settings still work. I know this works up to 1903 as I deploy Surface Pro with Hello this way currently. They are all Hybrid-AAD joined as well.

**Comment by MamaDoc** [comment]
Thank you.  I have been trying to get all PC’s restored from hack.   Oldest
device 6 months.

**Comment by mypil** [comment]
@hoyty76 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
