### ISSUE TITLE
Here is the download links

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#4041]
for windows 10 1903 RE 64bit

https://drive.google.com/file/d/1-5_U479025_C_k7vajtOlbeRcFeAjUQr/view?usp=drivesdk

for  windows 10  1903 PE 64bit

https://drive.google.com/file/d/1-1D0PLZ9bmN4N2Sw1wykSR8MIwXWsrjL/view?usp=drivesdk

Please download at free of cost and use for personal only.
and send the feedback or comments to me 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3354f6b4-1316-8af6-c7d9-0c2f9681b3f0
* Version Independent ID: 1efc63fe-8380-2113-7985-1775bcccd3be
* Content: [Windows ADK for Windows 10 scenarios for IT Pros (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/windows-adk-scenarios-for-it-pros)
* Content Source: [windows/deployment/windows-adk-scenarios-for-it-pros.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-adk-scenarios-for-it-pros.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thanks for sharing @RAJU2529 , I would assume you are merely sharing the download links and this is not a request for any update in the documentation? If so, we will now close this issue but please feel free to re-open it if there is anything in this document that you think should edited or updated.

Thank you for engaging with the community!

**Comment by jvsam** [comment]
@officedocsbot close
