### ISSUE TITLE
There needs to be some explanation on how to interpret device Install log.

### ISSUE THREAD

**Issue by Sumitdhiman** [MicrosoftDocs/windows-itpro-docs#4043]
[Enter feedback here]

Hi Team,
Some explanation on how to interpret device Install log for Install failure for Error code 0xC1900101 would be quite handy.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 528014e0-02e5-2d77-a229-4895731bb872
* Version Independent ID: 4f46b620-e345-c9e4-70fa-ae4f5a8e48b9
* Content: [Resolution procedures - Windows IT Pro](https://docs.microsoft.com/en-us/windows/deployment/upgrade/resolution-procedures)
* Content Source: [windows/deployment/upgrade/resolution-procedures.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/resolution-procedures.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @Sumitdhiman thank you for your feedback. I will get this issue over to the Windows writing team for review. I also requested the team to update this issue and tag you if additional information or clarification is needed. 

Thank you for your contribution to make the docs better! We want users to have the best Windows 10 experience by ensuring the contents of the Microsoft Docs are useful, accurate and up-to-date.

**Comment by RAJU2529** [comment]
I never seen those errors. This is the first time I seeing those. 
Why Windows os gives error free installations. Setup

**Comment by jvsam** [comment]
Hi again @Sumitdhiman I just want to ask more information from you before we can move forward. 

> interpret device Install log for Install failure for Error code 0xC1900101

May I please know what specific details you are looking for? The current documentation contains several variants of the said error, with causes and mitigation options. It will help a lot if we know the specific improvement you want to see (*Is it new content? Perhaps you can provide an example for clarity?*). Thanks for understanding and we look forward to hearing from you.

**Comment by Sumitdhiman** [comment]
Hi jvsam,

On the log files page, I see an explanation of only Setupact and Setuperr.log files. No mention of how to interpret device install log which can be particularly helpful in case of 0xC1900101. 
[https://docs.microsoft.com/en-us/windows/deployment/upgrade/log-files
](url)

**Comment by jvsam** [comment]
Just to clarify @Sumitdhiman, so you are looking for more information related to the device install log *($Windows.~bt\Sources\Rollback\setupapi\setupapi.dev.log)* in this documentation, is that correct? Anyway, I will forward this to the Windows content writing team for review. Please continue to share your suggestions or ideas to help improve the quality of the technical documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hi again @Sumitdhiman I just want to circle back on this while waiting for update. So, Windows setup log files are stored in different locations depending on the setup phase. By default, the [SetupAPI.dev.log](https://docs.microsoft.com/windows-hardware/drivers/install/setupapi-logging--windows-vista-and-later-) is located in the Windows INF file directory (*C:\WINDOWS\INF\setupapi.dev.log*), but for rollback (*successfully rolled back the installation to the previous OS*), the SetupAPI.dev.log is found at *C:\$WINDOWS.~BT\Sources\Panther\setupapi\setupapi.dev.log*. For [0xC1900101](https://docs.microsoft.com/windows/deployment/upgrade/resolution-procedures#0xc1900101)—a generic rollback code—you can use the log in troubleshooting Plug and Play devices and driver installation.. 

> The device install log is particularly helpful if rollback occurs during the sysprep operation (extend code 0x30018). To resolve a rollback due to driver conflicts, try running setup using a minimal set of drivers and startup programs by performing a clean boot before initiating the upgrade process.

There is an '[Interpreting a Sample SetupAPI Log File](https://docs.microsoft.com/windows-hardware/drivers/install/interpreting-a-sample-setupapi-log-file) doc, although the example is for Windows XP, but you can use it as a reference. I am not sure where specifically that will fit in this documentation. What do you think?

**Comment by Sumitdhiman** [comment]
Hi Jo,

I compared a sample logfile from the rollback folder to one with on the
Interpreting a SetupAPI file and could not find similarities. However,
sometimes the error is as easy as you can interpret. Here is the last part
which clearly indicates a failure.

[image: image.png]

What I am trying to say is the documentation page should have information
about this and what to do if you are not able to find any relevant
information. Here is an example of Setupact documented:

https://docs.microsoft.com/en-us/windows/deployment/upgrade/log-files


   1. To find the last occurrence of the result code:
      1. Scroll to the bottom of the file and click after the last
      character.
      2. Click Edit.
      3. Click Find.
      4. Type the result code.
      5. Under Direction select Up.
      6. Click Find Next.
   2. When you have located the last occurrence of the result code, scroll
   up a few lines from this location in the file and review the processes that
   failed just prior to generating the result code.
   3. Search for the following important text strings:
      - Shell application requested abort
      - Abandoning apply due to error for object




Regards
Sumit

**Comment by jvsam** [comment]
> What I am trying to say is the documentation page should have information about this and what to do if you are not able to find any relevant information. Here is an example of Setupact documented.

Thanks for checking and comparing the log files @Sumitdhiman. We appreciate the effort. All right, let me follow-up if that information is available, and if it is, we will propose updates to this and the [Log files](https://docs.microsoft.com/windows/deployment/upgrade/log-files) docs.

**Comment by jvsam** [comment]
Hello @Sumitdhiman, we really appreciate your patience and thank you again for sharing your feedback. We will now close this issue since the main issue has been resolved. Thank you for being part of the community!

**Comment by jvsam** [comment]
@officedocsbot close
