### ISSUE TITLE
Auto-enroll Windows 10 devices without GPO

### ISSUE THREAD

**Issue by RR13000** [MicrosoftDocs/windows-itpro-docs#405]
Hi,
Can we auto-enroll Windows 10 devices without GPO? Apparently, with windows 10 1709 & AD Connect, it’s possible.. Do you know something about that?

Thanks you

**Comment by shortpatti** [comment]
@RR13000 -- I apologize for the delay in responding.  I will take a look at this further and find out if you can or not.
