### ISSUE TITLE
Intune ignores ownership

### ISSUE THREAD

**Issue by djboy64800** [MicrosoftDocs/windows-itpro-docs#4064]
I have tried every possible combination (mdm, awa, aadj with ownership 1, 2 and 3) but no matter what I do the Device always shows up as "Personal" in Intune. Is there something else I have to configure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39ae2ccd-9f3f-dcb5-3a20-46b1b4fd3d53
* Version Independent ID: b381c208-94b1-2d22-ef16-a57c138a7d72
* Content: [MDM enrollment of Windows-based devices](https://docs.microsoft.com/en-us/windows/client-management/mdm/mdm-enrollment-of-windows-devices#feedback)
* Content Source: [windows/client-management/mdm/mdm-enrollment-of-windows-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/mdm-enrollment-of-windows-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@djboy64800 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by djboy64800** [comment]
There is a Workaround! No perfect but usable.

Only MDM Managed Devices can have a Ownership.
RUN: ms-device-enrollment:?mode=awa&ownership=3
(only works with awa selected even though we want to enroll mdm)
When the window pops up click on "Join this device in Azure Active Directory" and continue this way. Now the Ownership gets assigned correctly.

I hope this helps someone else :)

**Comment by djboy64800** [comment]
PS:
1 = Unknown
2 = Private
3 = Company
