### ISSUE TITLE
Asterisks are not rendering in the wildcard examples table

### ISSUE THREAD

**Issue by swickera** [MicrosoftDocs/windows-itpro-docs#4068]
The asterisk character is not rendering within the table prefaced with "The following table describes how the wildcards can be used and provides some examples."  Example use "C:\Serv\\\Backup"  should render "C:\Serv\&lt;asterisk char&gt;\&lt;asterisk char&gt;\Backup", etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c0eddd-98ca-1e7a-bddb-36c7037850fe
* Version Independent ID: 6afa98e8-a402-4ef9-2189-8ecc111c3dba
* Content: [Configure and validate exclusions based on extension, name, or location](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-extension-file-exclusions-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-extension-file-exclusions-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/configure-extension-file-exclusions-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
OK, I see. There seems to be have been some sort of weird HTML conversion, where the **`*`** character has been replaced by `<em>` (no idea why) as well as a couple of other oddities like random appearances of `&gt;` or &gt; in the text.
I will see what I can do to edit and correct the table in that page and open a PR if I manage to get it right.
See also: https://guides.github.com/features/mastering-markdown/

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@swickera - Thank you for submitting feedback.

PR #4075 has been created by @illfated to fix and close this issue once the PR is merged.

Thank you for your contribution to make the docs better! Much appreciated!
