### ISSUE TITLE
Confusing terminology in Windows Hello for Business docs

### ISSUE THREAD

**Issue by PJMarcum** [MicrosoftDocs/windows-itpro-docs#4071]
The section "The difference between Windows Hello and Windows Hello for Business" makes a clear distinction between "windows hello" and "windows hello for business" however the term "windows hello for business" is rarely used in the documentation. Without the proper terminology being used in the docs I can't decide if a section is only relevant to "Windows Hello" or if it is indeed relevant to "windows hello for business" or both.  https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-overview#the-difference-between-windows-hello-and-windows-hello-for-business

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f8d124-fd83-f3ab-8249-d11d5967460f
* Version Independent ID: eace54c8-04c9-a717-5ecd-2be8f485cc93
* Content: [Windows Hello for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-overview#the-difference-between-windows-hello-and-windows-hello-for-business)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@PJMarcum - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Solving at PR #4241

**Comment by j0rt3g4** [comment]
@mypil  Could you follow up this?

**Comment by mypil** [comment]
@PJMarcum - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
