### ISSUE TITLE
Remote desktop with biometrics - Cloud deployment?

### ISSUE THREAD

**Issue by jurajgh** [MicrosoftDocs/windows-itpro-docs#4072]
will the Remote Desktop with Biometrics functionality (ability to remote desktop into a windows machine using just PIN or fingerprint) available for cloud-only deployments - i.e. no PKI, no on-premise AD ?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jurajgh - We would like to get some details from you. Can you please share what specific issue you have and for which article? Kindly provide the article link as well so we can investigate.

Thank you.

**Comment by jurajgh** [comment]
sorry - thought this issue would be attached to the article where I clicked "view on github" (or something).
it's regarding this article: https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-features#remote-desktop-with-biometrics
and it's not an issue per se, more like not-yet-supported feature. basically, we'd like to use WhdB PIN for remote desktop login into a VM joined to Azure AD Domain Services (*not* the on-premise directory - we're all-cloud).

**Comment by mypil** [comment]
@jurajgh - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via [Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
