### ISSUE TITLE
EnableFastFirstSignIn - Candidate account

### ISSUE THREAD

**Issue by BHoggs** [MicrosoftDocs/windows-itpro-docs#4073]
Could it please be clarified what the doco means by "pre-configured candidate local account" in the following statement:
- It works by automatically connecting new non-admin Azure Active Directory (Azure AD) accounts to the pre-configured candidate local accounts.

What is this local account, and where do you configure it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 845fc177-23cf-0b2c-4b2b-5ac3966763a6
* Version Independent ID: ef4248eb-9b9f-24ec-631e-d65ae2ae3ecf
* Content: [Policy CSP - Authentication](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-authentication#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-authentication.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-authentication.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@BHoggs - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Solving issue With PR #4244

**Comment by j0rt3g4** [comment]
Added new PR #4244

**Comment by illfated** [comment]
The new substitution is PR number #4272 .

**Comment by j0rt3g4** [comment]
@mypil  Could you follow up this?

**Comment by illfated** [comment]
@BHoggs : As you can see, the Pull Request has been committed to the Github source for the docs.microsoft.com page. It may take a few days for the changes to migrate to the Docs page, but in the meantime, feel free to give us feedback if this clarifies your questions a bit more. If you still feel that there are common questions to be answered from the related page, please post more feedback regarding this and your suggestions on what specifically needs more attention (and possibly suggest what should be added or changed on the page).

**Comment by mypil** [comment]
@officedocsbot close

**Comment by Siva-Github** [comment]
`Pre-configured candidate local accounts are any local accounts (pre-configured or added) in your device.`

Hi there, I think this still needs additional clarification. 

What if the machine has multiple user profiles? How do we pre-configured a profile for this purpose?
