### ISSUE TITLE
this article says "and taskbar" but does not discuss taskbar customization with mdm

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/windows-itpro-docs#4076]
this article says "and taskbar" but does not discuss taskbar customization with mdm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c81a606d-98ac-fa9c-8dd9-b48bd654f605
* Version Independent ID: 9740f98b-e0b8-65cb-2f38-5dfbc773c32b
* Content: [Customize Windows 10 Start and taskbar with mobile device management (MDM) (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/customize-windows-10-start-screens-by-using-mobile-device-management#feedback)
* Content Source: [windows/configuration/customize-windows-10-start-screens-by-using-mobile-device-management.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/customize-windows-10-start-screens-by-using-mobile-device-management.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Mike-Crowley - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
The solution is at PR #4240

**Comment by j0rt3g4** [comment]
Substituted PR #4240 for #4273

**Comment by j0rt3g4** [comment]
@mypil  Could you follow up this?

**Comment by mypil** [comment]
@Mike-Crowley - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
