### ISSUE TITLE
The meaning of "...Externally transactioned nodes..." in the context of the node operation for a given ICSPNode is not clear

### ISSUE THREAD

**Issue by asilverman** [MicrosoftDocs/windows-itpro-docs#408]
Document - [Design a custom configuration service provider](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/design-a-custom-windows-csp.md)

In the section "Determine node operations", it is unclear what the definition and meaning for "...Externally transactioned nodes..." is missing. As a consequence it is impossible to understand the appropriate use and meaning semantics of the "Execute" node operation.

Is it possible to clarify this subject?

Thanks!
-Ariel

**Comment by shortpatti** [comment]
@MariciaAlforque  -- Can you take a look at this issue?

**Comment by mypil** [comment]
@MariciaAlforque - We would like to follow up on this. Do you have any updates? 

Thanks.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by nenonix** [comment]
@asilverman Does this article help answer your question? https://msdn.microsoft.com/library/ms703934(v=vs.85).aspx

**Comment by asilverman** [comment]
Unfortunately it doesn’t 

Regards,
Ariel Silverman

**Comment by nenonix** [comment]
@asilverman I don't know that this is something we can address with changes or edits to content. I think that perhaps your query can best be answered if you pose it in a technet forum:  https://social.technet.microsoft.com/Forums/home. Perhaps when you have clarified the meaning for yourself you could let us know where or how the docs content could be edited for greater accuracy?

**Comment by asilverman** [comment]
I am looking for an example of the use of externally transaction es csp noses, unfortunately there is no document to be found that defines and shows examples on how to use this construct. Since this document mentions it, I would ask that it would be addressed in the document. 

Regards,
Ariel Silverman

**Comment by nenonix** [comment]
@asilverman Thanks. I am consulting with the team to address the points you raise.

**Comment by nenonix** [comment]
@illfated can you assist here?

**Comment by illfated** [comment]
Thank you for asking. I don't know the material in question more than superficially.
Even though I might have ideas about what the intentions in the documentation could be,
I could easily find myself in deep water if I try to explain anything I don't know much about.

@asilverman : have you looked at **MS DTC External Transactions** (https://msdn.microsoft.com/en-us/library/windows/desktop/ms705306(v=vs.85).aspx)
to see if there is anything in that document that could answer your question, like e.g.
> Microsoft® Distributed Transaction Coordinator (MS DTC) external transactions are used when the transaction includes more actions than simply sending or retrieving Message Queuing messages (more than one resource manager is enlisted). In this case, the application must ask MS DTC for a transaction object and explicitly reference that object each time it sends a message, retrieves a message, or executes an action of another resource manager.

I will chance a ping to @egallagh to ask if this is something he is familiar with.

BTW, regarding the "semantics of the "Execute" node operation" in the first post above,
I think it will be necessary to know the material well enough to be able to distinguish all the nodes involved.
It is important for developers working in this field, but I don't do enough developing to know this.

My only conclusion so far is that it would be good to have feedback from developers familiar with this material, in order to determine if actual developer information belongs in the article referenced above, or if the developer information is expected to be found somewhere else in the MSDN libraries (or somewhere else outside the scope of this article).

**Comment by nenonix** [comment]
@asilverman does the link below provide the answers you seek? I am a writer/editor so cannot weigh in on technical issues but to my mind this page provides a very clear explanation:
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tpsod/648a3ca8-8a88-4904-bbe2-e2b4a4bf38dc

**Comment by asilverman** [comment]
Unfortunately no, maybe we can get a technical person involved?

Regards,
Ariel Silverman

**Comment by asilverman** [comment]
The technical query has to do with the document. Can I get an example in the document please?

Regards,
Ariel Silverman

**Comment by MaratMussabekov** [comment]
Dear @asilverman ,
**In the section "Determine node operations", it is unclear what the definition and meaning for "...Externally transactioned nodes..."** - internal transactioned node is a node with its own transactioning scheme defined, while external transactioned - has the node's transactioning  automatically handled by ConfigManager2. It is described by the other article in the same section: [ICSPNodeTransactioning](https://docs.microsoft.com/windows/client-management/mdm/icspnodetransactioning)

**it is impossible to understand the appropriate use and meaning semantics of the "Execute" node operation.** - each node operation is described in the article [ICSPNode](https://docs.microsoft.com/en-us/windows/client-management/mdm/icspnode). The original article has link to it too.

**I am looking for an example of the use of externally transaction es csp noses, unfortunately there is no document to be found that defines and shows examples on how to use this construct.** - example of using externally transactioned CSP: [Samples for writing a custom configuration service provider](https://docs.microsoft.com/windows/client-management/mdm/samples-for-writing-a-custom-configuration-service-provider)
I would also recommend to check this: [Configuration service provider reference](https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference)

Thank you

**Comment by mypil** [comment]
@asilverman - Thank you for submitting feedback.

From our understanding, the issue has been answered by MaratMussabekov. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
