### ISSUE TITLE
variable is incorrect

### ISSUE THREAD

**Issue by lengthmin** [MicrosoftDocs/windows-itpro-docs#4084]
重要
在非英语操作系统上运行 Windows Defender Device Guard 和 Windows Defender 凭据防护硬件准备工具时, 请改*$OSArch = $(gwmi win32_operatingsystem).OSArchitecture为$OSAch = $((gwmi win32_operatingsystem).OSArchitecture).tolower()改为使用该工具, 以使该工具正常工作。 这是一个已知问题。

应该改为：$OSArch = $((gwmi win32_operatingsystem).OSArchitecture).tolower()

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [管理 Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/zh-cn/windows/security/identity-protection/credential-guard/credential-guard-manage#feedback)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by lengthmin** [comment]
translate:
```
 Important

When running the Windows Defender Device Guard and Windows Defender Credential Guard hardware readiness tool on a non-English operating system, within the script, change *$OSArch = $(gwmi win32_operatingsystem).OSArchitecture to be $OSAch = $((gwmi win32_operatingsystem).OSArchitecture).tolower() instead, in order for the tool to work. This is a known issue.
```
the english page has the same problem:
$OSArch = $((gwmi win32_operatingsystem).OSArchitecture).tolower()

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @lengthmin , thank you for bringing this to our attention. Based from the information you've provided, the issue is also happening on English operating system (OS). Since this Github site is intended for product documentation, I recommend contacting Windows 10 support and opening a [service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance. 

Please keep us posted here on the resolution or information that can be called out in the docs, e.g. *the known issue also affects EN OS, etc.*. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation. Looking forward to hearing from you! 

Thank you for engaging with the community!

**Comment by jvsam** [comment]
Hi @lengthmin , thank you for bringing this to our attention. I will forward this issue to the Windows writing team for review. I also requested the team to update this issue and tag you if additional information or clarification is needed. If you have the correct and working script, please share as well.

Thank you for engaging with the community!

NOTE: Please disregard the previous comment. You may have received a notification email about it.

**Comment by illfated** [comment]
Please notice issue ticket #3869 + PR #3881 related to the reported problem.

**Comment by lengthmin** [comment]
I'm sorry about my poor english. I mean the code has a typo...
![image](https://user-images.githubusercontent.com/13938334/59963282-90f6d400-9523-11e9-85d4-85485e273197.png)

**Comment by illfated** [comment]
Oh. Right. I did not notice that. So the asterisk (` * `) is missing from the second line (recommended change) in the current version, I presume?

**Comment by alexverboon** [comment]
No second variable should also be
$OSArch

Sorry that was my typo

**Comment by illfated** [comment]
Thank you for confirming. I wonder if it will be enough to correct the surplus & redundant asterisk (`*`) in the [En-US version of the document](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage) and wait for the updated document to be parsed through the Machine Translation script. (https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)

**Comment by jvsam** [comment]
Hi again @lengthmin we appreciate your patience. The suggested update to this documentation to *fix the typo in the script* (See pull request #4436) has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
