### ISSUE TITLE
MFA Server no longer available for new customers

### ISSUE THREAD

**Issue by Ronald-den-Os** [MicrosoftDocs/windows-itpro-docs#4085]
Does this option makes sense now Microsoft has announced retirement of the MFA server?

"As of July 1, 2019, Microsoft will no longer offer MFA Server for new deployments. New customers who would like to require multi-factor authentication from their users should use cloud-based Azure Multi-Factor Authentication. Existing customers who have activated MFA Server prior to July 1 will be able to download the latest version, future updates and generate activation credentials as usual."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c2ca3e-9d15-5a4a-971a-bc1eb3cb2637
* Version Independent ID: ca1f6f75-8129-24d1-2426-21effa0ab151
* Content: [Validate and Deploy Multifactor Authentication Services (MFA) (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-key-trust-validate-deploy-mfa)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-key-trust-validate-deploy-mfa.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-key-trust-validate-deploy-mfa.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @Ronald-den-Os thanks for bringing this to our attention. We want to make sure the docs are accurate and up-to-date to provide the best Windows 10 experience to users, so your feedback is appreciated. I will forward this issue to the Windows writing team so they can review this doc and identify ways on how to incorporate that messaging.

Thank you for engaging with the community!

**Sample reference with the MFA Server update:** https://docs.microsoft.com/azure/active-directory/authentication/howto-mfaserver-deploy#install-and-configure-the-azure-multi-factor-authentication-server

**Comment by jvsam** [comment]
Hi again @Ronald-den-Os, we appreciate your patience. The suggested update to this documentation to include the *discontinuation of MFA Server for new deployments* announcement (See pull request #4383) has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
