### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by kyjeeper** [MicrosoftDocs/windows-itpro-docs#4088]
Scenario 2:  user signs in iwth a local account

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c34b8c-44b9-b3d3-9894-5a7fd68e2309
* Version Independent ID: ea643c8f-e92d-b90e-4e90-f338cea39e79
* Content: [Configure VDA for Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/vda-subscription-activation#feedback)
* Content Source: [windows/deployment/vda-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/vda-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@kyjeeper - Thank you for pointing this out.

Created Pull Request #4089 to fix the spelling error and close this issue once the PR is merged.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@kyjeeper - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for reporting and making the docs better!

**Comment by mypil** [comment]
@officedocsbot close
