### ISSUE TITLE
Missing example

### ISSUE THREAD

**Issue by asilverman** [MicrosoftDocs/windows-itpro-docs#409]
Document - [Design a custom configuration service provider](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/design-a-custom-windows-csp.md)

Issue: Missing examples for internode dependencies
-----
Section "Shape the configuration service provider's subtree" reads:
>Note that the process of shaping the configuration service provider’s subtree influences the choice of transactioning schemes for each node. If possible, peer nodes should not have dependencies on each other. Internode dependencies other than parent/child relationships create mandatory groups of settings, which makes configuration service provider development more difficult.

I would like to understand  through an example and further detail how to shape the configuration schema when internode dependedencies exist. More specifically how does one structure a schema when the configuration state (i.e. configured/unconfigured) depends on a subset of lead ICSPNodes

**Comment by shortpatti** [comment]
@MariciaAlforque  -- Can you take a look at this issue?

**Comment by mypil** [comment]
@MariciaAlforque - We would like to follow up on this. Do you have any updates? Thanks.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by asilverman** [comment]
Is anyone ever going to provide the resolution for this? It’s been open for over a year and I still would like to know how to do it

**Comment by mypil** [comment]
@asilverman - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by TokyoScarab** [comment]
@brianlic-msft I would love your thoughts on this as one of the page contributors, thanks!

**Comment by mypil** [comment]
@ManikaDhiman - Can you please share your insights on this issue?

Thank you.

**Comment by ManikaDhiman** [comment]
@mypil I checked with the engineering team and they informed that management extensibility via CSPs is not currently supported.

**Comment by mypil** [comment]
@asilverman - From our understanding, the issue you raised has been answered by ManikaDhiman. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
