### ISSUE TITLE
Backup of a device that has biometrics

### ISSUE THREAD

**Issue by GreggRevak** [MicrosoftDocs/windows-itpro-docs#4092]
What happens when a backup is taken of the hard drive of a device that has Windows Hello biometrics enabled? Is the biometric data present in the backup copy? If so, can it be used on another device? Some discussion and clarification of this scenario should be added to this document so administrators understand where the data is stored when backed up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f8d124-fd83-f3ab-8249-d11d5967460f
* Version Independent ID: eace54c8-04c9-a717-5ecd-2be8f485cc93
* Content: [Windows Hello for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-overview#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @GreggRevak thank you for your suggestion. I will get this issue over to the Windows writing team for review and investigation (*if the scenario—backup the biometrics file and use it on another device, etc.⁠—is currently supported or feasible*). Although, if you need to perform this on your device and you need an immediate answer, I recommend contacting Windows 10 support and opening a [service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant.

Thank you for engaging with the community!

**Comment by RAJU2529** [comment]
@GreggRevak.  i think not possible, because computer A is configured brand A biometric device and the fingerprint is stored in  C drive in the hard disk.
But the same hard drive is connected with another computer B is connected brand B biometric device, so in this case, users cannot able to login.

I have not tested when both computers are configured with same biometric device. Even i cannot test this case, Because  our college does not  two computers

**Comment by GreggRevak** [comment]
> Hi @GreggRevak thank you for your suggestion. I will get this issue over to the Windows writing team for review and investigation (if the scenario—backup the biometrics file and use it on another device, etc.⁠—is currently supported or feasible). Although, if you need to perform this on your device and you need an immediate answer, I recommend contacting Windows 10 support and opening a service ticket in your tenant.
> Thank you for engaging with the community!

I want to clarify my question. My question is driven by privacy regulations that require us to be able to delete all private data. So I need to know if the biometrics are copied by a normal backup process (say, if you back up the OS drive, or the C:\ drive or take an image of the entire hard drive). Is the biometric data contained in these copies? Where is it stored on the source computer? Can I exclude the location from the backup so the biometric data is not backed up?

**Comment by jvsam** [comment]
Thanks for clarifying your question @GreggRevak, this helps!

>[Where is Microsoft Hello data stored](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-biometrics-in-enterprise#where-is-microsoft-hello-data-stored)
The biometric data used to support Windows Hello is stored on the local device only. It doesn’t roam and is never sent to external devices or servers. This separation helps to stop potential attackers by providing no single collection point that an attacker could potentially compromise to steal biometric data. Additionally, even if an attacker was actually able to get the biometric data, it still can’t be easily converted to a form that could be recognized by the biometric sensor.

> Windows stores biometric data that is used to implement Windows Hello securely on the local device only. The biometric data doesn’t roam and is never sent to external devices or servers. Because Windows Hello only stores biometric identification data on the device, there’s no single collection point an attacker can compromise to steal biometric data. See: [Biometric sign-in](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-overview#biometric-sign-in)

> When you set up Windows Hello, it takes the data from the face or iris sensor or fingerprint reader and creates a data representation—not an image; it’s more like a graph—that is then encrypted before it’s stored on your device. See: [What data is collected, and why](https://support.microsoft.com/help/4468253/windows-hello-and-privacy-microsoft-privacy)

Hello @DulceMontemayor, can you please help us with this? Since the data is stored locally, is it something that can be copied, if so, do you have any information on where it resides? Thank you and hoping to hear from you.

**Comment by RAJU2529** [comment]
I want add more points in this article.  I hope , points are very useful.
Afternoon I will create PR request

**Comment by RAJU2529** [comment]
@jvsam. Sir, just now I created new PR to the author for added points about windows hello, location of fingerprint data .

here is the link of PR 
**https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4307**

**Comment by jvsam** [comment]
Thank you for submitting a pull request @RAJU2529. We'll have it reviewed.

**Comment by jvsam** [comment]
Hi again @GreggRevak, thank you for your patience. The suggested update to this documentation via Pull Request (PR) #4307 has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!"

**Comment by jvsam** [comment]
@officedocsbot close
