### ISSUE TITLE
SO CONFUSING!

### ISSUE THREAD

**Issue by jt980** [MicrosoftDocs/windows-itpro-docs#4094]
Your table makes NO sense. Why would someone upgrade from Windows 10 Home to Windows 10 Home? MS makes so much money, but their documentation is the WORST on the internet!  Event the table itself has no title or explanation on how to read!  What is "Windows 10 semi-annual ?" What is N/KN ??? Nothing but slop here!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08436cb0-d0b6-0961-9e57-291b24d73644
* Version Independent ID: 36264f52-d3ac-4e50-f8e8-b09d6b210490
* Content: [Windows 10 upgrade paths (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-upgrade-paths#feedback)
* Content Source: [windows/deployment/upgrade/windows-10-upgrade-paths.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/windows-10-upgrade-paths.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @jt980 thank you for your feedback. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation. I will get this issue over to the Windows writing team for review. Thank you again for engaging with the community!

**Comment by RAJU2529** [comment]
Windows 10 semi-annual means  , update  releases once in six months.
windows 10 N  edition have no multimedia player with windows.
windows 10 KN edition country specific  KN stands for Korean

**Comment by jvsam** [comment]
Hi again @jt980 we appreciate your patience. The suggested update to improve this documentation based on your feedback (See pull request #4350) has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
