### ISSUE TITLE
Distinguish between devices enrolled through AAD join or Add work account

### ISSUE THREAD

**Issue by sashutosh** [MicrosoftDocs/windows-itpro-docs#4096]
Is there a way for MDM to identify if the device enrollment happened due to Azure AD join or adding a work account. The documentation above mentions to ignore the user and send both user device policies if the enrollment is through adding a work account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f06aa-8465-821f-6ad8-9c04f9be5291
* Version Independent ID: 0f2f73e7-8154-4f7f-a24b-841785c05dd6
* Content: [Azure Active Directory integration with MDM](https://docs.microsoft.com/en-us/windows/client-management/mdm/azure-active-directory-integration-with-mdm#feedback)
* Content Source: [windows/client-management/mdm/azure-active-directory-integration-with-mdm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/azure-active-directory-integration-with-mdm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @sashutosh thank you for your question. We definitely want to help you, however, this Github site is intended for product documentation. To get an immediate answer, I recommend that you contact support and open a [service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant.

And please, do keep us posted here on the resolution or any relevant information from the support team  that can be called out in the docs. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation. Looking forward to hearing from you!

**Comment by jvsam** [comment]
Hi @sashutosh were you able to contact Windows 10 support for assistance? We're very interested to know the answer to your question. Again, if it's something that can be incorporated to the existing documentation, please keep us informed and we will be happy to assist you in updating the contents of this document. Thank you.

**Comment by jvsam** [comment]
Hi again @sashutosh, we hope all is well. We haven't received any response from you, so for now, we will close this issue. However, feel free to re-open if you have suggestions to improve the quality of this documentation and we will submit them for review. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
