### ISSUE TITLE
Without user knowledge

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#4097]
Without users knowledge  ,  trojans  or  viruses  are  installs  which comes with bundle softwares . various  internet  sites . Those  sites  are  not  trusted .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35cc84b-ddd3-dff4-0c4e-7fd5ebe95ee6
* Version Independent ID: d7fba10f-479b-abbd-2608-a8739137ce7c
* Content: [Trojan malware](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/trojans-malware)
* Content Source: [windows/security/threat-protection/intelligence/trojans-malware.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/intelligence/trojans-malware.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **levinec**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
@RAJU2529 : I am uncertain what your suggestion is here. Is there something you think should be changed or added on the related page (https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/trojans-malware)?

**Comment by RAJU2529** [comment]
@illfated. Yes, sir ,i want to add, give me one day time, to get related points to add .

**Comment by jvsam** [comment]
@RAJU2529 thank you in advance for your contribution. If there are relevant information that you wish to add to this documentation, you have the option to make the suggested changes via pull requests. Or you can also let us know and we can forward your suggestions to the Windows writing team for review. Please keep us posted.

**Comment by jvsam** [comment]
Hi @RAJU2529  we haven't received any response from you, so for now, we will close this issue. However, feel free to re-open if you have suggestions to improve the quality of this documentation and we will submit them for review. Thanks for being part of the Microsoft Docs community!

Your contributions are appreciated!

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by illfated** [comment]
@RAJU2529 : if you had linked this issue ticket (#4097) in the comment section of your PR #4216 , it would have been a lot easier to notice the development in this case.
