### ISSUE TITLE
it-client folder appears as submodule of repo but no gitsubmodule file

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/windows-itpro-docs#4110]
Noticed when trying to clean-out Thumbs.db file by running `git rm -rf --cached .` and `git add .`. The it-folder was cleared out since it looks like it got added in https://github.com/MicrosoftDocs/windows-itpro-docs/commit/47e6746cd43e4b4c96adad4e99d40ecd2d4d6d98 without the corrisponding `.gitsubmodule` file.

/cc @mjcaparas since it was your commit

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @nschonni just want to ask if this has been resolved? Also, please advise on what to do with this open issue. Perhaps it's better if the comment is added to the PR or to the commit page for documentation purposes? Let us know please. Thank you.

**Comment by nschonni** [comment]
Nothing has been resolved, I mentioned the author that originally added it and the commit, so it probably makes more sense for them to be assigned

**Comment by nschonni** [comment]
FYI, looking at the merge history it looks like "it-client" might be your internal repo name https://github.com/MicrosoftDocs/windows-itpro-docs/search?q=it-client&type=Commits
Maybe it got accidentally added as a submodule, but that might be something you need to confirm internally

**Comment by jvsam** [comment]
Hi @nicolonsky thank you for the clarification. Appreciate it!.

Hi @mjcaparas , is this something that you can help up with? Do you have time to check? Thank you very much in advance for your assistance.

Related content: https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-non-windows
Content Source: https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-non-windows.md

**Comment by jvsam** [comment]
Hi @mjcaparas just a follow-up on this. Can you please advise on how to proceed so we would know how to manage this open issue? I also added a comment on this commit [47e6746](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/47e6746cd43e4b4c96adad4e99d40ecd2d4d6d98). Thank you very much.

**Comment by jvsam** [comment]
Hi again @mjcaparas and @nschonni I will now close this issue but will monitor commit [47e6746](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/47e6746cd43e4b4c96adad4e99d40ecd2d4d6d98) for updates. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by nschonni** [comment]
@jvsam tracking a commit discussion instead of an issue seems backwards, unless it's for stats reasons

**Comment by mjcaparas** [comment]
I'm not really sure what to do with the gitsubmodule file. Would it be better if I just scrap the commit and do a pr from it-client? I think I might have accidentally committed to master.

**Comment by mjcaparas** [comment]
Looking at this more closely, my update to this file can be ignored.

**Comment by nschonni** [comment]
@mjcaparas i'm still not clear. Is there supposed to be a submodule added, or should the reference be removed through another PR?

**Comment by mjcaparas** [comment]
it-client was an old folder. I think I accidentally checked in a change in the wrong folder which then made the submodule. 
The submodule and my PR on this topic an be disregarded.

**Comment by mjcaparas** [comment]
so no, a submodule should not be added. i'm not sure how to remove the commit though :(

**Comment by nschonni** [comment]
No problem, the commit probably can't be removed safely through Rebase, since it's on the master branch. I'll do a quick PR just to remove the dangling reference to the submodule instead

**Comment by mjcaparas** [comment]
phew! thanks @nschonni
