### ISSUE TITLE
Setup PRMerger bots in repo

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/windows-itpro-docs#4113]
These bots can auto-assign reviewers to PRs based on the `author` metadata of the affected files. EX: https://github.com/MicrosoftDocs/azure-docs/pull/33564 the authour is assigned along with labels

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@nschonni - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via [Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by nschonni** [comment]
This is more a suggestion to make contributions to the docs flow better. It isn't really a Windows 10 thing, but feedback as a contributor to a bunch of the MicrosoftDocs repos.

**Comment by nschonni** [comment]
There are also the validation hooks that can be setup to catch some things https://docs.microsoft.com/en-us/contribute/validation-reference/
Might need to talk to @meganbradley about that though, since I'm not sure how that gets wired in

**Comment by illfated** [comment]
@mypil : This is a suggestion about bots like @officedocsbot, so maybe @msdocsprbot could be a useful name for a bot handling Pull Requests like Nick has suggested?

**Comment by mypil** [comment]
@nschonni - Perhaps it is best for you to raise this suggestion to the GitHub admins. Let me loop in @DaniHalfin @dstrome as they may be able to help with this.

**Comment by nschonni** [comment]
Found the other bot I was looking for https://github.com/apps/docs-content-validation
This is used over on the dotnet/docs repo for those validation-reference checks I linked to above

**Comment by dstrome** [comment]
hi @nschonni 

Thanks for the feedback.  We evaluate the performance of the repo constantly and are considering several ways to improve the experience for contributors. PRMerger is among the options we're looking at, however, there are several considerations regarding whether it makes sense to enable it on a given repo. 

I'd be interested in understanding what functions of the PRMerge bot you find most useful. Same question for the docs-content-validation bot. I'm familiar with the bots but would like a contributor's viewpoint on their benefits.

Thanks!
David.

**Comment by nschonni** [comment]
> what functions of the PRMerge bot you find most useful

Just speaking to the ones that do the assignment/sign-off parts, it means the PRs get routed to the author right away, rather than relying on an admin to assign them. That leaves the editors and admins to concentrate on the reviews and landing of PRs.

>  Same question for the docs-content-validation bot

It catches lots of easy to miss parts for contributors (and authors, but I'm not sure if it's used internally currently). I always believe it's better for a machine to complain to a developer/author, because it isn't taken personally. In the case of false positives, admins/editors can always override and land anyway.

I'll say i'm not the biggest fan of the OpenBuild setup, but that's mostly because the output is pretty verbose, and relys on review.docs.microsoft.com, which isn't accessible to outside contributors.

**Comment by mypil** [comment]
@dstrome - Do you have any updates on this?

**Comment by dstrome** [comment]
No further updates. We'll definitely take the feedback and include it in our discussions around repo and content management. Thanks all!
