### ISSUE TITLE
To which server does this document refer?

### ISSUE THREAD

**Issue by Therion69** [MicrosoftDocs/windows-itpro-docs#4115]
There can be up to 5 MBAM servers in a normal environment: 2 database servers, 1 reporting server and 2 IIS servers. In our case we have configured only 2 servers: 1 SQL server with 2 databases and a reporting service; 1 IIS server (with 2 websites). Do we need to apply above information on all servers seperatly? And if so, wich is the preferred order?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67626969-2854-3925-fc2d-9d8a09183796
* Version Independent ID: f442462e-6e55-406d-9a77-4e98e6dc036f
* Content: [Applying hotfixes on MBAM 2.5 SP1](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/apply-hotfix-for-mbam-25-sp1#feedback)
* Content Source: [mdop/mbam-v25/apply-hotfix-for-mbam-25-sp1.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/apply-hotfix-for-mbam-25-sp1.md)
* Product: **w10**
* Technology: **mdop**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @Therion69, I am sorry that we don't have the information that you need. This site is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. If you have suggestions related to this documentation, please let us know here and we will submit them for review. 

As for your question, we believe it will be best addressed by the support team. Please open a [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) ticket in your tenant so you can get immediate assistance. If you have feature suggestions, you can also use the [MBAM TechNet Forum](https://social.technet.microsoft.com/Forums/en-US/home?forum=mdopmbam&filter=alltypes&sort=lastpostdesc) or submit it through the  [User Voice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub) hub.

Thanks for being part of the Microsoft Docs community!

**Comment by RAJU2529** [comment]
@Therion69.  I think windows  server  2012 R2 or  windows server 2016 64bit.

**Comment by jvsam** [comment]
Thanks for that information @RAJU2529.

Hi again @Therion69 we haven't received any response from you, so for now, we will close this issue. If you believe this documentation needs to improve, please re-open and provide recommendations on how we can make it better. We value users feedback, so please don't hesitate to let us know.

**Comment by jvsam** [comment]
@officedocsbot close
