### ISSUE TITLE
1903

### ISSUE THREAD

**Issue by codaamok** [MicrosoftDocs/windows-itpro-docs#4118]
May this be updated for 1903 please? :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce0131fb-6b3a-5905-1738-253cf37e3b2d
* Version Independent ID: cab448be-54ae-539e-22ba-3d202a468d4f
* Content: [Windows 10 - Apps](https://docs.microsoft.com/en-us/windows/application-management/apps-in-windows-10#feedback)
* Content Source: [windows/application-management/apps-in-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/apps-in-windows-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by jvsam** [comment]
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4115

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @codaamok, good news. There was already a suggested update to this document via this [Pull Request](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4153) contributed by @RAJU2529, one of the active members of the community. Once the suggestion gets approved, it will be displayed on the site.

Thanks for being part of the Microsoft Docs community!

P.S. Thanks @illfated for referencing the PR to this issue.

**Comment by nam31** [comment]
@codaamok Seems like details related to 1903 has already been updated here: https://docs.microsoft.com/en-us/windows/application-management/apps-in-windows-10#feedback

Please check and feel free to contact if you will still have any question.
