### ISSUE TITLE
Taskbar Pinning Behavior Changed in 1903

### ISSUE THREAD

**Issue by jwmurraycmu** [MicrosoftDocs/windows-itpro-docs#4123]
It appears there was an undocumented change of behavior in 1903. Per the !IMPORTANT box on this page, a partial start layout should allow users to make changes to the taskbar. That's true, however the taskbar is now reset to the MDM-specified layout at every reboot (previously if a user unpinned an app it stayed unpinned). Is that intended?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140f038c-e307-78f0-5165-309e0cf34ca5
* Version Independent ID: b1011259-ee05-21a4-5308-aabc8b0dd74b
* Content: [Configure Windows 10 taskbar (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/configure-windows-10-taskbar#feedback)
* Content Source: [windows/configuration/configure-windows-10-taskbar.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/configure-windows-10-taskbar.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @jwmurraycmu, at the moment, we cannot confirm if this is a new behavior of *version 1903*. To get immediate assistance, we recommend opening a [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) ticket in your tenant. If it's a bug, then you can directly report it to the Support team. Please keep us posted here on any updates that can be called out in this documentation. Thank you.

Hello @Dansimp hoping you can help us, if time permits. Are there any upcoming updates to the documentation related to 1903, particularly related to the *taskbar* behavior? Thank you.

**Comment by jvsam** [comment]
Hi @jwmurraycmu I just want to follow-up on this. Is the issue still happening? If so, were you able to contact support to confirm if it was a normal behavior? We'd like to know because it *may* be something that can be called out in this documentation. Please keep us posted; we want to make sure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation.

**Comment by jwmurraycmu** [comment]
Still following up at the moment. The issue is still happening, and it's not clear if it's by design just yet. I'll provide another update when the case is closed.

**Comment by jvsam** [comment]
Thanks for the update @jwmurraycmu! Keep us posted. Thanks.

**Comment by jvsam** [comment]
Hi @jwmurraycmu do you have anything for us from Support? Also, it seems to be an issue on Windows 10, 1903. I've checked the Technet forum and there are some questions asked pertaining to the Windows taskbar behavior, although some users' issues may not be entirely similar to what you are experiencing. Examples:  

[Windows 10 1903 Taskbar Configuration Issues](https://social.technet.microsoft.com/Forums/ie/en-US/da789a73-c229-4a45-ac0a-896dc43e7cd3/windows-10-1903-taskbar-configuration-issues?forum=win10itprosetup)
[Win10 Start Menu not working](https://social.technet.microsoft.com/Forums/en-US/45d30309-cb50-410f-8998-16e56db1903a/win10-start-menu-not-working?forum=win10itprogeneral)

We're hoping though, that your issue has been resolved already.

**Comment by jvsam** [comment]
Hi again @jwmurraycmu we haven't received any updates from you. We hope your issue has been resolved. For now we will close this, however, feel free to re-open if you have suggestions or ideas to help improve the quality of this documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
