### ISSUE TITLE
[LOC] Not fixed #3407 "アプリ & 機能"→"アプリと機能" 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#4126]
Not fixed: #3407
![unwanted-software_j](https://user-images.githubusercontent.com/40815708/59817061-5e00e480-9359-11e9-834b-3a1fc8ff0457.png)

https://docs.microsoft.com/ja-jp/windows/security/threat-protection/intelligence/unwanted-software

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 88462c9b-1c48-c9aa-b376-dec60af94941
* Version Independent ID: f8914b77-3c94-9814-b944-9d7deed9660e
* Content: [望ましくないソフトウェア](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/intelligence/unwanted-software)
* Content Source: [windows/security/threat-protection/intelligence/unwanted-software.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/intelligence/unwanted-software.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **levinec**

**Comment by illfated** [comment]
Ampersand ( & ) issue again, MT problem (similar to #3487).

- & needs to be replaced with と

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot unassign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
![image](https://user-images.githubusercontent.com/53281468/67133142-690d3980-f1c0-11e9-9f79-12122765dfef.png)

**Comment by TinaMcN** [comment]
私は人間の翻訳のためにこの記事を送った。 約3週間かかります。 (I sent this article to be human translated.  It should take approximately 3 weeks.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated. Please verify that it is fixed. Thanks again for the feedback)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected. 
Closed #4126.
Thanks.
