### ISSUE TITLE
[LOC] Not fixed #3593 "Windows こんにちは"→"Windows Hello"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#4127]
Not fixed: #3593
![level-5-enterprise-security_j](https://user-images.githubusercontent.com/40815708/59817339-76253380-935a-11e9-9fdd-0dd5e92a67ec.png)

https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-security-configuration-framework/level-5-enterprise-security

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a6d4df3f-ba2f-c45d-58bc-790d79c449a3
* Version Independent ID: 6210761c-668f-29f4-c50d-feec32bddbf4
* Content: [レベル 5 エンタープライズ セキュリティの構成](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-security-configuration-framework/level-5-enterprise-security)
* Content Source: [windows/security/threat-protection/windows-security-configuration-framework/level-5-enterprise-security.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/threat-protection/windows-security-configuration-framework/level-5-enterprise-security.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @appcompatguy
* Microsoft Alias: **appcompatguy**

**Comment by illfated** [comment]
We may have to wait until Tina (xuachen ?) has taken over all cases and responsibilities from @dongmicro .

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot unassign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は削除されたようです。(The article appears to have been deleted.)

**Comment by illfated** [comment]
Yes, indeed. **404 - ページが見つかりません** (404 - Page not found)

**Comment by hyoshioka0128** [comment]
@TinaMcN @illfated Thanks.
article has been removed.
Closed #3593
