### ISSUE TITLE
[LOC] Not fixed #3928 "Windows こんにちは"→"Windows Hello"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#4147]
Not fixed: #3928
![identity-protection_j](https://user-images.githubusercontent.com/40815708/59857187-6128be80-93b3-11e9-80c8-af6449685ef6.png)

https://docs.microsoft.com/ja-jp/windows/security/identity-protection/

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: bee434fc-f456-02b7-b4b7-60e36f8130dd
* Version Independent ID: a63a8d30-2a27-b2d4-147d-c1e799bd56f2
* Content: [Id およびアクセス管理 (Windows 10)](https://docs.microsoft.com/ja-jp/windows/security/identity-protection/)
* Content Source: [windows/security/identity-protection/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/index.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot unassign @TinaMcN

**Comment by illfated** [comment]
I guess you meant to assign TinaMcN and unassign dongmicro (unless I have missed something).

**Comment by illfated** [comment]
"U~indōzu kon'nichiwa" -- one of the best nerdy jokes I have come across in public documentation this year. 😄

**Comment by e0i** [comment]
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
@hyoshioka0128 これは今修正されているように見えます。 確認してください。(this appears to be fixed now.  Please verify.)

**Comment by illfated** [comment]
Nice. Looks like the issue is resolved from my perspective, when looking at the public page
(https://docs.microsoft.com/ja-jp/windows/security/identity-protection/)

**Comment by hyoshioka0128** [comment]
Fixed.
Close #4147
