### ISSUE TITLE
LTSC chipset section on this page references nonexistent section on Lifecycle Support Policy FAQ

### ISSUE THREAD

**Issue by amelvill** [MicrosoftDocs/windows-itpro-docs#4148]
From this page:

>Note:
>
>Windows 10 LTSB will support the currently released processors and chipsets at the time of release of the LTSB. As future CPU &gt; generations are released, support will be created through future Windows 10 LTSB releases that customers can deploy for those systems. For more information, see Supporting the latest processor and chipsets on Windows in Lifecycle support policy FAQ - Windows Products.

Ctrl+F for "chip" on https://support.microsoft.com/en-us/help/18581/lifecycle-faq-windows-products returns 0 hits and the FAQ page no longer seems to cover anything related to this for LTSC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6957383-3bd9-eef9-6410-9c42f8a0b172
* Version Independent ID: a2090374-0fd1-8d67-66de-30c4cf2835f7
* Content: [Overview of Windows as a service (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-overview#feedback)
* Content Source: [windows/deployment/update/waas-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @amelvill, thank you for bringing this to our attention. Although the FAQ page doesn't contain the texts *Supporting the latest processor and chipsets on Windows*, it does provide a link that goes directly  to the [Windows Processor Requirements](https://docs.microsoft.com/windows-hardware/design/minimum/windows-processor-requirements) document—which at this time still remains up-to-date.

>A device might not be able to receive updates if the device hardware is incompatible, lacking current drivers, or otherwise outside of the Original Equipment Manufacturer's (“OEM”) support period.

Anyhow, we understand how this may create some confusion, not just for you but for other users as well. I will get this over to the Windows writing team so they can review this document and suggest ways on how to improve it, e.g. *update some messaging*. If you do have specific suggestions on, e.g. how it should be written, please let us know. Thank you again. 

Additional reference:
- [Windows lifecycle fact sheet](https://support.microsoft.com/help/13853/windows-lifecycle-fact-sheet)

**Comment by jvsam** [comment]
Hi again @amelvill, we appreciate your patience. The suggested update to this documentation to include a link to the *Windows Processor Requirements* content page for easy access (See pull request #4343) has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
