### ISSUE TITLE
Heading not displayed properly

### ISSUE THREAD

**Issue by Allatez** [MicrosoftDocs/windows-itpro-docs#4155]
The first heading ("How do I install the Insider builds?") isn't displaying correctly. The markdown for the heading is showing in cleartext (##) and the first paragraph is appended to the heading. But in the file, I can't find any errors or make any changes that will fix the display.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dafbb989-d1f4-0411-81ce-f761e83bdeba
* Version Independent ID: e8fdf590-c7f0-6b07-9407-33bdf2ca7453
* Content: [Insider preview for Microsoft HoloLens (HoloLens)](https://docs.microsoft.com/en-us/hololens/hololens-insider#feedback)
* Content Source: [devices/hololens/hololens-insider.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/hololens/hololens-insider.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment]
I think this issue is solved

**Comment by illfated** [comment]
See also https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4182/files to discover why the heading is not displayed properly.

**Comment by jvsam** [comment]
@illfated thanks for promptly correcting the problem with the markdown.

@Allatez thank you as well for letting us know about this. Update to this documentation has been suggested, please see committed changes in this [Pull Request (PR)](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4182/files). Once the PR gets approved, you should expect to see this implemented on the site. We cannot confirm how long though, it may depend on the volume of submissions.

Thanks for being part of the Microsoft Docs community!

**Comment by illfated** [comment]
Thanks, but the PR belongs to @RAJU2529 .
I just linked it here for everyone to notice it.

**Comment by jvsam** [comment]
My mistake, thanks for pointing that out @illfated. Kudos @RAJU2529 for your initiative! Keep it up and thank you.

**Comment by illfated** [comment]
@Allatez : As you can see, the PR #4182 (**Insider preview for Microsoft HoloLens: display section headings correctly**) has been merged, so the page should start working once the change has migrated to the docs.microsoft.com page. This may take a few days to complete, but it should solve the issue you have reported. Thank you for reporting the issue and keep up the good work. 👍

**Comment by jvsam** [comment]
Hi @Allatez we'd like to inform you that the changes are now displayed at docs.microsoft.com. You can verify by visiting this URL: https://docs.microsoft.com/en-us/hololens/hololens-insider.

We will now close this issue. Thanks again for being part of the Microsoft Docs Community and for helping improve the quality of the technical documentation!

**Comment by jvsam** [comment]
@officedocsbot close
