### ISSUE TITLE
More sample - VBS to CS.ini (One way)

### ISSUE THREAD

**Issue by ggbce** [MicrosoftDocs/windows-itpro-docs#4186]
Hi,

Your sample is veryuseful, but it explain only how to add our personal VBscript inside CS.ini using a existing value in CS.ini to transform it. 

In CS.ini:
UserExit=Setname.vbs
OSDComputerName=#SetName("%MACADDRESS%")#

Where we push the MAC Address (%MACADDRESS%) to the VBScript and also retrieve it via SetName.

How I could just retrieve a value from the VBScript without pushing a variable ?

I tested:
OSDComputerName=#SetName()#

And also inside the VBScript I modified it (for testing purpose):

Function SetName()
  SetName = "PCTESTNAME"
 ' When it will work... I will call my PC Name from a SQL Database or a serach in AD to known the next available name in order...
End Function

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef5e1984-c560-2c16-a57b-0d4494527e68
* Version Independent ID: f4a99c70-b851-c6a5-5d54-f18cf792df2d
* Content: [Configure MDT for UserExit scripts (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/configure-mdt-for-userexit-scripts)
* Content Source: [windows/deployment/deploy-windows-mdt/configure-mdt-for-userexit-scripts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/configure-mdt-for-userexit-scripts.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by ggbce** [comment]
Hi, 

I finally found how to !!!

Inside "CS.ini":

UserExit=SetMyPCName.vbs
OSDComputerName=#SetName("")#

Inside "SetMyPCName.vbs" (To generate a random PC name... purpose test only):

Function SetName(sPCNameToSet)
Dim rdmpc,max,min
max=10000
min=99999
Randomize
rdmpc=(Int((max-min+1)*Rnd+min))
SetName = "PC" & rdmpc
End Function

--> Now I just can work on a solution to put a variable for "SetName" from SQL or AD or any other database !!!

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ggbce - Thank you for engaging with the community here for the docs.

Based on your comment, it appears that you have found a resolution to your issue. Is there something within the documentation that you would suggest to be edited? Or are you just providing feedback? 

If everything has been resolved and there's no need to make changes to the current documentation then please feel free to close this issue.

**Comment by ggbce** [comment]
Hi Mypil,

In my case, I found my answer, but sharing this information with the world could be interesting. I Don't kown if these comments still visible when you close the case. If yes, Nothing more is necessary because interested people could find my sample here.

**Comment by mypil** [comment]
@ggbce - Yes, I believe the comments here is still visible even if the issue will be closed. I will proceed to close this issue now. 

Thank you for taking the time to share this resolution. We value your feedback and your contribution to make the docs better.

**Comment by mypil** [comment]
@officedocsbot close
