### ISSUE TITLE
block the sites 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#4217]
Block the fake flash player websites in hosts file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dea73d5-6cf6-3b6d-b1cd-14a67672d55e
* Version Independent ID: 1db9d496-4942-01e6-4550-1a5cb6a770e5
* Content: [Prevent malware infection](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/prevent-malware-infection)
* Content Source: [windows/security/threat-protection/intelligence/prevent-malware-infection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/intelligence/prevent-malware-infection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **levinec**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @RAJU2529 happy top help here but can you please provide more information? Is this a suggestion related to this documentation? Thanks and looking forward to hearing from you.

**Comment by RAJU2529** [comment]
@jvsam.Yes sir its required in this document. I have experienced while browsing, the fake flash player update website tries to convience user to install viruses and Trojans .
For this action, I added the those websites in the hosts file. Whenever I get fake sites accessed by the browsers. Then immediately I block it.

**Comment by jvsam** [comment]
I see, thank you @RAJU2529. So basically, you are suggesting to add the use of the windows hosts file to block deceptive, malicious or other unwanted sites, for instance in the [Other safety tips](https://docs.microsoft.com/windows/security/threat-protection/intelligence/prevent-malware-infection#other-safety-tips) section. Thank you for your suggestion, though please note that the documentation sets this expectation at the beginning:

>***simple** tips below to stay protected and minimize threats to your data and accounts*

Modifying the windows hosts file may be easy for technically savvy users, but it *may not be* for novice users. The tip can help other users as well, how about adding this at https://answers.microsoft.com with more emphasis on security? This is an [example](https://answers.microsoft.com/windows/forum/windows_10-other_settings-winpc/how-to-edit-host-file-in-windows-10/7696f204-2aaf-4111-913b-09d6917f7f3d).

Hi @levinec kindly check this suggestion from the community if it's something that we can add to this documentation. Happy to help create a PR with the suggestion. Thank you.

**Comment by levinec** [comment]
I agree with @jvsam that the suggestion is too technical for the purpose of this docs page. It is supposed to be more simple, general tips and the suggestion does not fit with the content. Thanks for the suggestion @RAJU2529!
