### ISSUE TITLE
Not clear how to view events

### ISSUE THREAD

**Issue by voldemarz** [MicrosoftDocs/windows-itpro-docs#4222]
I am having issue with SmartScreen eating 20% cpu constantly and wanted to check events, but not clear where. Is it supposed to be in Application, Security or System category in EventViewer? What does "Microsoft-Windows-SmartScreen/Debug" mean? Event source?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb097945-c324-9797-b3a7-9d41b05bec66
* Version Independent ID: f67b7c1b-1d59-3869-b380-44f695356839
* Content: [Windows Defender SmartScreen overview (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-overview#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **mjcaparas**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
@voldemarz : You are looking at the wrong subsection of the Event Viewer logs. You need to go to

![image](https://user-images.githubusercontent.com/38162891/59990596-ffcb4e80-9643-11e9-921e-1ee03f88762c.png)

**Comment by RAJU2529** [comment]
@voldemarz. Smart screen means  the  new feature  belongs to windows defender . SmartScreen blocks potentially malware sites.

there is a policy available in gpo 
under Computer configuration\administrative templates\system\file exporer\Configure windows defender smart screen.
screenshot
![conwdsc](https://user-images.githubusercontent.com/3296790/60004986-48f2c100-968b-11e9-860f-e21de7c20efa.JPG)


smart screen Does not  to do  display smart screen.

**Comment by voldemarz** [comment]
@illfated Thanks. Found it, but there's not logged events. It's still constantly grinding 15-20% of cpu. Only thing I could do I restart, but I have work in progress open that I can't disrupt...

@RAJU2529 Not really sure how that policy would help me with diagnosing SmartScreen. Also I don't have that policy available. I am on Windows 10 version 1809.
![image](https://user-images.githubusercontent.com/1264210/60030264-f6bd9a00-96a2-11e9-9ae8-404cec43f66c.png)

**Comment by voldemarz** [comment]
@RAJU2529 This lists correct policy paths depending on Win version https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-available-settings.md
Doesn't seem relevant for me though.

Technically my question of were to find logs is addressed. To avoid such confusion for others I think the document should state that one should look in "Application and Services Logs" category.

Now the next problems is to actually get some useful logs...

**Comment by voldemarz** [comment]
Oh. Reopening the issue for consideration to clarify regarding "Application and Services Logs" category.

**Comment by RAJU2529** [comment]
@voldemarz 
I am attaching latest policy definitions .zip format, extract and copy the files to respective folders
i don't know about log category. Let experienced uses might  help 

[PolicyDefinitions.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/3321518/PolicyDefinitions.zip)

**Comment by voldemarz** [comment]
@RAJU2529 What? Why? How are those policy settings relevant in diagnosing what SmartScreen is doing with current settings? Doesn't seem relevant for me at all.

**Comment by illfated** [comment]
@voldemarz : Maybe it would be more useful to look into the direct purpose of SmartScreen instead of digging too much into the OS configuration bits before testing if it is active.
- check https://www.tenforums.com/antivirus-firewalls-system-security/64542-how-test-smartscreen.html
- consider the information in https://support.microsoft.com/en-us/help/17443/windows-internet-explorer-smartscreen-filter-faq in relation to Group Policy and Business IT Management.

**Comment by voldemarz** [comment]
@illfated It's active, by default, never changed any of its settings. The problem is that it is doing something all the time and crunching CPU without providing any info even in logs (I enabled logging) what the hell it is doing. Btw, I am not using MS Edge.

For reference https://twitter.com/voldemarz/status/1142862945518542850

**Comment by illfated** [comment]
Fair enough. Maybe there is something else going on in the background, or maybe it is just reacting to file changes in general? I don't know. There are too many unknown factors "in the calculation" for me to suggest anything specific to troubleshoot.

**Comment by jvsam** [comment]
Hi @voldemarz thanks for this feedback.

> Technically my question of were to find logs is addressed. To avoid such confusion for others I think the document should state that one should look in "Application and Services Logs" category.

I will forward your suggestion to the Windows writing team for review. Your help to improve the quality of the technical documentation is appreciated!

Also, I just want to add that you also have the option to contact [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in the future if you need technical assistance. 

P.S. Thanks @RAJU2529 and @illfated for your help here.

**Comment by TokyoScarab** [comment]
Hi @voldemarz !  I'm from the Docs Team.  I hope you are doing well.  Were you still having trouble with the issues you were mentioning above?  I will be updating the documentation to address the issue you brought up.

**Comment by voldemarz** [comment]
@TokyoScarab I am having trouble in the sense that I can't get insights on what exactly SmartScreen is consuming CPU cycles for at times. With the help of other I found the right place in EvenViewer, but there was nothing there. I still think that part in documentation is poor. Either is should be more explicit or link to some EvenViewer dedicated info page which describes organization of logs there. Just saying it's in "Microsoft-Windows-SmartScreen/Debug" is not clear enough as it is not clear if it's category, filter name, even source or what.

**Comment by TokyoScarab** [comment]
@voldemarz Thanks for the feedback.  I'll see what I can do about updating the page to be more user friendly.

**Comment by jvsam** [comment]
Thank you for your patience @voldemarz. We just want to inform you that the suggested update to this documentation via Pull Request (PR) #4442 has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
