### ISSUE TITLE
Applies To is ambiguous 

### ISSUE THREAD

**Issue by wmhussain** [MicrosoftDocs/windows-itpro-docs#4225]
Hi Team 
Heading for this article says "Network Security: Configure encryption types allowed for Kerberos Win7 only" however "Applies to" section of the document says "Windows 10". 
In the whole document, there is discussion for Kerberos encryption for Win7 & Win 2k8.

Is this anyhow related to Win 10?

Regards
Hussain 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d05d447-1cc1-1eeb-3c4d-74591874f4e1
* Version Independent ID: 020b4d09-5ce9-e636-0545-1ce27029a921
* Content: [Network security Configure encryption types allowed for Kerberos Win7 only (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@wmhussain. Those policies are included In windows 10  in gpo under.
 Computer Configuration\ Windows Settings\ Security Settings\ Local Policies\ Security Options
screenshot. From my side  windows 10  definitely  supported 

![gpo1](https://user-images.githubusercontent.com/3296790/60003768-ff08db80-9688-11e9-88e3-64decb916762.JPG)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@wmhussain - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by ojrb** [comment]
Hi @mypil  the PR #4309 solved this issue ! Please Review and Merge !

**Comment by mypil** [comment]
@wmhussain - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
