### ISSUE TITLE
Why does Microsoft leave the free upgrade path from Windows 7 to Windows 10 open?

### ISSUE THREAD

**Issue by TheRink** [MicrosoftDocs/windows-itpro-docs#4226]
Why does Microsoft leave the free upgrade path from Windows 7 to Windows 10 open today in 2019?  Is this Microsoft giving tacit consent to it or is it an illegal hack?  The following are two links that show how to do it.

https://www.zdnet.com/article/heres-how-you-can-still-get-a-free-windows-10-upgrade/

https://www.howtogeek.com/272201/all-the-ways-you-can-still-get-windows-10-for-free/

Thanks for your help.
TheRink

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08436cb0-d0b6-0961-9e57-291b24d73644
* Version Independent ID: 36264f52-d3ac-4e50-f8e8-b09d6b210490
* Content: [Windows 10 upgrade paths (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-upgrade-paths#feedback)
* Content Source: [windows/deployment/upgrade/windows-10-upgrade-paths.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/windows-10-upgrade-paths.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@TheRink. That windows free upgrade offer is  decided by  Microsoft inc , so  as a end user we cant comment

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@TheRink - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello, @TheRink,
all the free upgrades from windows 7/8.1 to windows 10 should have been completed by 11:59 PM UTC-10 (Hawaii) on July 29, 2016 (source: [Upgrade to Windows 10: FAQ](https://support.microsoft.com/help/12435/windows-10-upgrade-faq)).
So, despite the fact that it is technically possible to use windows 7 key to install windows 10, it is illegal.

Thank you

**Comment by mypil** [comment]
@TheRink - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
