### ISSUE TITLE
why Credential-Guard is enabled after reboot win10?

### ISSUE THREAD

**Issue by geoffreyzj** [MicrosoftDocs/windows-itpro-docs#4227]
hi, 
      After running the dgreadiness_v3.6 script and reboot, the Credential-Guard is disabled correctly. 
    However, when I reboot the laptop again, the Credential-Guard is enabled.  How to make the  Credential-Guard disabled  permanently？

Tks
Geoffrey

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@geoffreyzj - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by RAJU2529** [comment]
@geoffreyzj.  Did you enable Device guard in Group policy editor? 
If yes means then go to the command prompt with admin rights, type
**gpedit.msc**
browse  under 
**computer configuration \administrative templates \system\device guard**  
on right side , click "turn on virtualization-based security" --set  to not configured
.
screenshot
![disablecrredentialguardgpo](https://user-images.githubusercontent.com/3296790/60024513-7d7b7280-96b5-11e9-8d86-de817783a53e.JPG)

merge registry key file


then open the command prompt  with admin rights 
type the following 
**gpupdate /force**

**Comment by geoffreyzj** [comment]
@RAJU2529 
   Thanks for your answer.  I tried your steps.  The device Gard is still working after reboot. 
   I tested twice.  Maybe some other 


![Capture1](https://user-images.githubusercontent.com/43167103/60071033-5c656100-974b-11e9-8a0c-783805fd1019.JPG)

**Comment by RAJU2529** [comment]
@geoffreyzj . try to disable HVSI  and  retry it

**Comment by geoffreyzj** [comment]
ok, thank you, RAJU2529 anyway.

**Comment by mypil** [comment]
@officedocsbot close
