### ISSUE TITLE
Policy for WDAG symbolic proxy

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#4233]
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard.md and https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview both mention: 

> WDAG requires proxies to have a symbolic name, not just an IP address. IP-Literal proxy settings such as “192.168.1.4:81” can be annotated as “itproxy:81” or using a record such as “P19216810010” for a proxy with an IP address of 192.168.100.10. This applies to Windows 10 Enterprise edition, 1709 or higher.

However, the specific policy to configure the symbolic proxy is not mentioned. What policy is it and can it be added to the documentation? I assume it is one of the Network Isolation policies but none of the documentation for those policies mention anything about supporting a symbolic format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8927df09-e9aa-8c40-290d-0ca7d86ec4e2
* Version Independent ID: ca67bcfc-6120-d6ca-290b-1a7822494c73
* Content: [Frequently asked questions - Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@iadgovuser1 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Dansimp - Can you please share your insights on this issue?

Thank you.

**Comment by carstenhagemann** [comment]
Hi,
any update on this? Where and how to define proxy specific for WDAG (Application Guard) ?

**Comment by mypil** [comment]
@carstenhagemann - We are still coordinating with the Product team to get the relevant information to address this issue. Thank you for your patience.

**Comment by MWegner-MA** [comment]
Hi @mypil - Any update on this?

**Comment by illfated** [comment]
Even though I am not affected by this issue in my work, I am still curious to see the rationale behind this part of the documentation. At first glance, I thought it could be a requirement of some form of DNS alias or local DNS name in addition to the IP address. Reading these issue comments as well as the whole document, it looks open to more interpretations or alternatives.

**Comment by mypil** [comment]
@MWegner-MA - The doc owner @Dansimp is still working with the Product team to get the necessary information. We are awaiting their findings and feedback.  We have sent a follow up already and we will keep you informed of any updates. Thank you.

**Comment by illfated** [comment]
Pull Request #4988 has been merged into the `master` branch a bit more than 4 hours ago (as of the time of this comment).
@iadgovuser1 : Does this resolve your issue ticket, or is more needed before your issue is resolved?

**Comment by iadgovuser1** [comment]
@illfated By "symbolic name", is a DNS or NetBIOS name meant instead?

"_WDAG requires proxies to have a symbolic name, not just an IP address_" would be translated to:

"_WDAG requires proxies to be specified by DNS or NetBIOS name rather than an IP address_"

I don't get this part: "_"192.168.1.4:81" can be annotated as "itproxy:81"_"  _itproxy_ would be translated to _192.168.1.4_ if there was an entry in the host's lmhosts file, a DNS entry on a DNS server, or a NetBIOS name on the network segment that resolves to "itproxy" (assuming NetBIOS is enabled).

I've also looked through all the Network Isolation policy documentation available online and none of the other resources mentioned the 'P' syntax (e.g. P19216810010 for 192.168.100.10). Maybe that's why the "symbolic name" language was used? Still, this syntax isn't mentioned in any other Network Isolation policy documentation so it seemed questionable to me.

**Comment by illfated** [comment]
Thank you for your thorough reply. I agree with you regarding this odd "symbolic name" usage, which should indicate that some form of DNS or NetBIOS name is needed to translate the name to an IP address. Then again, I have been pondering if there could be some other form of alias naming convention in WDAG, but you are far more knowledgeable than me on that topic. I simply don't know at this time which one it actually is, so unfortunately I am at a loss when it comes to providing a reasonable explanation for this conundrum.

**Comment by mypil** [comment]
@iadgovuser1 - PR #4988 was created to address the issue that you opened. For the additional feedback that you provided, let me loop in the PM who created this PR.

@qrscharmed  - Can you possibly share your insights on this - https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4233#issuecomment-534255273 ?

Thank you.

cc: @Dansimp @kenwith

**Comment by qrscharmed** [comment]
Apologies for the delay for this one. The proxy that should be defined in this case is the host Proxy settings that can be found in the Settings app: 


![Proxy](https://user-images.githubusercontent.com/38082753/83486639-754bbb80-a45e-11ea-8bbc-c335e192e708.PNG)

**Comment by mypil** [comment]
@iadgovuser1 - From our understanding, the issue has been answered by @qrscharmed and has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/a381e8b4c1b9e419eec0849007c57974c0fee4b1. 


Thank you for your contribution to make the docs better! Much appreciated!
