### ISSUE TITLE
Log Snippets  - Need name and location of log

### ISSUE THREAD

**Issue by jandreacola** [MicrosoftDocs/windows-itpro-docs#4235]
Please add the name and location of the log(s) where the snippets are from

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a8126d-2552-97a3-6bb4-c24fd32ffc1f
* Version Independent ID: 82afb372-5fee-e0c9-56b0-3e8276401e23
* Content: [How Windows Update works](https://docs.microsoft.com/en-us/windows/deployment/update/how-windows-update-works#feedback)
* Content Source: [windows/deployment/update/how-windows-update-works.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/how-windows-update-works.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jandreacola - hank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@greg-lindsay - Can you please share your insights on this issue? 

Thank you.

**Comment by greg-lindsay** [comment]
I'll add a link in here, but if you look to the left you'll see a topic immediately below this one in the table of contents called "Windows Update log files" that gives all that information.

**Comment by mypil** [comment]
@jandreacola - From our understanding, the issue you raised has been answered by greg-lindsay. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
