### ISSUE TITLE
Hundreds of megabytes of logs...

### ISSUE THREAD

**Issue by David263** [MicrosoftDocs/windows-itpro-docs#4238]
This feature, as well as others (such as Sleep Studies), creates log files in a dedicated log directory without ever deleting older logs. This feature and others needs to delete old log files, to avoid filling the user's disk drive with garbage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ddcd0ab-2e6e-e6cd-f217-03ebde8cd9a8
* Version Independent ID: 09bb184c-357e-6fb5-bbe9-7ae558bfc509
* Content: [Windows 10, version 1803 basic diagnostic events and fields (Windows 10)](https://docs.microsoft.com/en-us/windows/privacy/basic-level-windows-diagnostic-events-and-fields-1803#feedback)
* Content Source: [windows/privacy/basic-level-windows-diagnostic-events-and-fields-1803.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/basic-level-windows-diagnostic-events-and-fields-1803.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@David263.  , In event viewer   You can disable  log event for particular functions

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@David263 - Thank you for submitting feedback.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via [Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
