### ISSUE TITLE
Bad link in article "Basic Firewall Policy Design (Windows 10)" for Next article

### ISSUE THREAD

**Issue by michalzobec** [MicrosoftDocs/windows-itpro-docs#4239]
Hello,

in this article you have bad link. this is estetic problem only.

### actual code
`**Next: **[Domain Isolation Policy Design](domain-isolation-policy-design.md)`

### expected code
`**Next:** [Domain Isolation Policy Design](domain-isolation-policy-design.md)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b90732e6-ee7b-cb24-242a-38eafa5f6b05
* Version Independent ID: f39f3c93-fb61-de69-312c-64088eb568bb
* Content: [Basic Firewall Policy Design (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/basic-firewall-policy-design)
* Content Source: [windows/security/threat-protection/windows-firewall/basic-firewall-policy-design.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-firewall/basic-firewall-policy-design.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@michalzobec.  i checked the code actually it is correct. 
Inserting before word **  the word makes appears BOLD

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@michalzobec - Thank you for pointing this out.

PR #4246 has been created to fix and close this issue once the PR is merged.

Thank you for your contribution to make the docs better! Much appreciated!
