### ISSUE TITLE
This sample policy xml file really usefull in organisation 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#4247]
I  read the article, i conformed that sample policy XML file belongs to windows server OS    to  configure the firewall to the Windows client OS .
The author is given good sample policy xml file . I hope organization can take use of this xml file.

Thanks to xml file 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba0d9f8d-6aee-0ea0-89f5-999d36977749
* Version Independent ID: 1c5927f6-5ad3-0876-1c02-3cc015b51c33
* Content: [Appendix A Sample GPO Template Files for Settings Used in this Guide (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/appendix-a-sample-gpo-template-files-for-settings-used-in-this-guide)
* Content Source: [windows/security/threat-protection/windows-firewall/appendix-a-sample-gpo-template-files-for-settings-used-in-this-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-firewall/appendix-a-sample-gpo-template-files-for-settings-used-in-this-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@RAJU2529 -  Thank you for your valuable feedback.  It is greatly appreciated.

**Comment by mypil** [comment]
@officedocsbot close
