### ISSUE TITLE
Missing from TOC

### ISSUE THREAD

**Issue by skycommand** [MicrosoftDocs/windows-itpro-docs#4255]
This page (titled "Applying hotfixes on MBAM 2.5 SP1") is missing from the Microsoft Docs table of contents, which appears to the left side of this page. However, this page is clearly in the same GitHub repo as the rest of the MBAM pages. All one has to do is to add it to the TOC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67626969-2854-3925-fc2d-9d8a09183796
* Version Independent ID: f442462e-6e55-406d-9a77-4e98e6dc036f
* Content: [Applying hotfixes on MBAM 2.5 SP1](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/apply-hotfix-for-mbam-25-sp1#feedback)
* Content Source: [mdop/mbam-v25/apply-hotfix-for-mbam-25-sp1.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/apply-hotfix-for-mbam-25-sp1.md)
* Product: **w10**
* Technology: **mdop**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @skycommand, thank you for bringing this to our attention. I'll request the Windows writing team to propose an update to include *Applying hotfixes on MBAM 2.5 SP1* topic to the *Microsoft BitLocker Administration and Monitoring 2.5* Table of Contents (TOC). 

Thanks for being part of the Microsoft Docs Community and for helping improve the quality of the technical documentation!

**Comment by TokyoScarab** [comment]
Hello @skycommand and thank you for posting this!  I will take a look at this and correctly update the documentation

**Comment by jvsam** [comment]
We appreciate your patience @skycommand. Please be informed that the suggested update to this documentation via Pull Request (PR) #4438 has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!"

**Comment by jvsam** [comment]
@officedocsbot close
