### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#4257]
This page says it is a reference for the Start layout XML. But the syntax of RequiredStartGroups is different from the syntax given in other examples, and different from an export. In these, the syntax is StartLayoutCollection.
Also, if I use the XML given on this page, it does not work in Intune; whereas if I use exported XML, or the examples given (with the different syntax), they do work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 061157dc-8fc8-3f9d-c01f-37f22fbdf1c7
* Version Independent ID: 0b0b6797-9367-eb7c-22ef-5f2b8bbfe592
* Content: [Start layout XML for desktop editions of Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/start-layout-xml-desktop#feedback)
* Content Source: [windows/configuration/start-layout-xml-desktop.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/start-layout-xml-desktop.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @Air-Git thank you for your feedback. If you don't mind, I'd like to clarify if there is a specific section, instruction, reference or messaging that is not accurate, particularly related to the examples? The more information you can provide, the more helpful it will be so that we will know what specific improvements we can suggest in this documentation. Our goal here is to ensure the contents of the Microsoft Docs are useful, accurate and up-to-date. Looking forward to hearing from you.

Also, for the *LayoutModification.xml*, in this [related doc](https://docs.microsoft.com/en-us/windows/configuration/customize-windows-10-start-screens-by-using-mobile-device-management), it says "*In Microsoft Intune, you select the Start layout XML file and add it to a device configuration profile.*" Is that how you are doing it? Though I'd like to emphasize that the provided LayoutModification.xml is just an example.

**Comment by Air-Git** [comment]
It is a little complicated to explain, but clear when you see what I am talking about. If we start with the question: "how do I configure the Start and taskbar layout in Intune?": in the Device Restrictions template it says you upload an XML file. So where do we get the XML? In the page: [Customize Windows 10 Start and taskbar with mobile device management (MDM)](https://docs.microsoft.com/en-us/windows/configuration/customize-windows-10-start-screens-by-using-mobile-device-management) the procedure is to export a Start layout. That page refers to this page: [Customize and export Start layout](https://docs.microsoft.com/en-us/windows/configuration/customize-and-export-start-layout), and that page refers to this page: [Configure Windows 10 taskbar](https://docs.microsoft.com/en-us/windows/configuration/configure-windows-10-taskbar) and this page: [Start layout XML for desktop editions of Windows 10 (reference)](https://docs.microsoft.com/en-us/windows/configuration/start-layout-xml-desktop).
So, the implication is that I can export an XML file and customise it using anything in the reference (the last page referred to above). The exported XML does not contain a taskbar layout, so it is fairly fundamental whether you can further modify the exported XML or not. 
Now the problems (assuming that the reference page is the reference).
1) The example given: [Sample LayoutModification.xml](https://docs.microsoft.com/en-us/windows/configuration/start-layout-xml-desktop#sample-layoutmodificationxml) does not work in Intune (assuming you modify it for your apps. It has a syntax of "RequiredStartGroupsCollection" which is not obtained if you export a Start, and which is not used in examples given on any other page. Conversely, the syntax "StartLayoutCollection". is used in all the other examples, but is not defined in the reference.
2) The example here: [Sample taskbar configuration added to Start layout XML file](Sample taskbar configuration added to Start layout XML file) has the xmlns referenced in two different places. Does that mean that, to customise the taskbar, the xmlns reference in the "StartLayoutCollection" is required? I don't think it is. In the reference document the xmlns is given at the top, in the "LayoutModificationTemplate" section, which makes sense.
It seems that, in practice, you can customise the exported XML and import it into Intune, but you cannot use the "RequiredStartGroups" syntax given in the reference, and instead need to use the "StartLayoutCollection" syntax that is not given in the reference.
Happy to be corrected. This is just what I have found in practice.

**Comment by jvsam** [comment]
Hi @Air-Git thank you for the explanation. It would be too easy to get distracted by the different reference links in the docs, but generally, majority of the contents are available. The docs are designed to be readable, hence, various sub-topics are arranged in a certain way to facilitate learning while still maintaining cohesiveness (*See the Table of Contents*). It will be inefficient to create the same content for another topic, hence, the interlinking. The same thing can be said for contents that cater to Windows 10 in general, so going back to your original feedback⁠—and thank you for testing⁠—there are details that are not applicable for Intune. 

If I may, I would like to suggest the following:
1. Please open a Github issue on the specific content page where your suggestions are best applied, like adding a tip or a disclaimer that, e.g. some of the xml attributes will not work for intune or they need to be customized, etc.. Should it be [here](https://docs.microsoft.com/en-us/windows/configuration/customize-windows-10-start-screens-by-using-mobile-device-management) instead?
2. Please tag me on the new issues so I can easily track your suggestions and coordinate with the Writing team. 
3. **Recommendation**: Creating a pull request with specific suggestions. We always welcome contributions and who can communicate or add suggestions better than the community user? If you will create a PR, please tag me as well so I can coordinate with the Editors for copy editing.

I believe this is the best way to capture all of your suggestions in a manner that can reinforce that they are valid improvements (*and perhaps increase the likelihood of them getting approved by the Microsoft authors*). I hope you're okay with this. Again, thank you so much. The docs are a '*continuous work in progress*' and we really appreciate your feedback.

**Comment by Air-Git** [comment]
Hi Jo,
I appreciate your response. I was trying to give a full explanation for the content authors. The fact is that there seems to be some confusion or fault in the inclusion of the `RequiredStartGroupCollection` and `AppendGroup` syntax in the Reference page. This syntax is not used anywhere else in the documentation. The best I can find is that it applies ONLY to the `Import-StartLayout` method that is used ONLY for imaging. Whereas the syntax used throughout the rest of the documentation, of  `StartLayoutCollection` is NOT included in the reference. It is a documentation mistake, not a clarification. 
I will do as you suggest and create a separate issue with the requested change.

**Comment by jvsam** [comment]
Awesome, thanks @Air-Git. I can see that the suggested updates were already merged, although it'll take some time for them to reflect on the documentation. Are you satisfied with that or do you have other suggestions? If none, I believe we can close this issue. Please let me know.

**Comment by Air-Git** [comment]
Yes thanks, the other issue  has the changes

**Comment by jvsam** [comment]
All right. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you @Air-Git for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
