### ISSUE TITLE
Missing deployment documentation

### ISSUE THREAD

**Issue by nluck** [MicrosoftDocs/windows-itpro-docs#4258]
There is no section on deploying multiple simultaneous code integrity policies. As I understand this is not possible via GPO (you can only select one code integrity policy), and the PowerShell deployment guide has not been updated either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d643fd44-756e-de45-47c8-e9d8e7d77d9a
* Version Independent ID: 273a1d3c-f7d9-2c32-16f3-8be3180147b4
* Content: [Deploy multiple Windows Defender Application Control Policies  (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/deploy-multiple-windows-defender-application-control-policies#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/deploy-multiple-windows-defender-application-control-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/deploy-multiple-windows-defender-application-control-policies.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mdsakibMSFT

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @nluck thank you for your feedback. Can you please clarify if your question is about deploying multiple simultaneous code integrity policies via [Group Policy](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-control/deploy-windows-defender-application-control-policies-using-group-policy)? Is the information insufficient or inaccurate? The more details you can provide, the more helpful it will be so that we will know what specific improvements we can suggest in this documentation.

Support on multiple simultaneous code integrity policies for one device is a new feature on Windows 10, version 1903 as indicated in the documentation, with a caveat that information may be *substantially modified*. Hence, it's safe to assume there will be more updates to this doc in the future 
 from the authors. Looking forward to hearing from you.

**Comment by nluck** [comment]
Thank you for your reply, I'll clarify gladly.

> Can you please clarify if your question is about deploying multiple simultaneous code integrity policies via Group Policy? Is the information insufficient or inaccurate? 

I mean that I don't see any information about actually deploying multiple simultaneous code integrity policies (despite the title of the documentation section). It clearly shows how to create base/supplemental policies (which works on Windows 10 1903, `New-CiPolicy` even recommends it), but not how to deploy them on any machine.

**Comment by jvsam** [comment]
Thank you for the clarification @nluck. The documentation introduces and explains one of the major updates on 1903 for threat protection, which is the multiple simultaneous code integrity policies support. There is also a section—*albeit short and general but on point*—on [deploying policies](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-control/deploy-multiple-windows-defender-application-control-policies#deploying-policies). Then there's the detailed [deployment guide](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control-deployment-guide) under the main topic, along with other sub-topics related to deployment, e.g. via GPO, etc. How about suggesting to revise the title to avoid confusion, for example, removing the word *deploy*. Will this be enough based on the current intent of this documentation, which is generally, informational? Thank you. 

**NOTE**: If you're suggesting an entirely new content, we can inform the authors here for consideration. However, we can't guarantee that it will be prioritized. But this is what this site is for, to provide feedback!

**Comment by jvsam** [comment]
Hi again @nluck I just want to ask if you have questions with regard to the information I've shared. If none, I believe we can close this issue. Thank you again.

I am also tagging the author here regarding your suggestion on creating contents related to deploying multiple simultaneous code integrity policies on any machine. Hi @mdsakibMSFT, here's a community feedback for your consideration. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
