### ISSUE TITLE
MBAM 2.5 SQL Server SP Supported Levels

### ISSUE THREAD

**Issue by richhudson** [MicrosoftDocs/windows-itpro-docs#4259]
Hi

Please could you confirm whether SQL Server 2014 SP3 is supported to host MBAM 2.5  SP1 databases.

The date stamp on the supported configurations page indicates that it was last updated prior to the release of SQL Server 2014 SP3 hence asking for clarification:
https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/mbam-25-supported-configurations

Thanks

Rich

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @richhudson, thank you for taking the time to open this issue. The content of this documentation remains up-to-date, hence, only Microsoft SQL Server 2014 SP1 & SP2 are supported for the MBAM Server features. If you are using Windows 10, we would definitely love to hear your feedback so I encourage you to submit your feature suggestions and ideas via [User Voice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub) hub. Your feedback goes directly to the Microsoft engineering teams responsible for building features and products for Windows 10.

Also, if you have issues with MBAM, I would recommend asking question on the [TechNet Forum](https://social.technet.microsoft.com/forums/home).

Thank you for engaging with the community!

**Comment by jvsam** [comment]
Hi again @richhudson, we haven't heard or received any updates from you. We are hoping that the information we shared helped. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
