### ISSUE TITLE
Unexpected BitLocker encryption Lonovo laptop windows 10 Version 1703

### ISSUE THREAD

**Issue by biren1234** [MicrosoftDocs/windows-itpro-docs#4262]
is there any issue with Lenovo Laptop
we buy some lenovo laptop and someone said with Lonovo laptop bitlocker encryption by default enabled
now what happend when we joined system in domain our bitlocker key lost and system locked

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment]
@biren1234. I think you must contact Lenovo support site or  contact Lenovo customer care number

**Comment by jvsam** [comment]
Hi @biren1234 thanks for your question. With this, it's best to contact [Windows 10 Support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) to get immediate assistance regarding MBAM. Perhaps Lenovo customer service can also help if it's something *pre-configured* on their machines. I would also recommend *asking your question* on the [TechNet Forum](https://social.technet.microsoft.com/forums/home).

Thank you for engaging with the Microsoft Docs community!

**Important**: Please be informed that site is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. If you have suggestions related to this documentation, please let us know here and we will submit them for review.

**Comment by jvsam** [comment]
Hi again @biren1234, we haven't heard or received any updates from you, but we are hoping you were able to contact Windows 10 or Lenovo support. For now we will close this issue, however, feel free to re-open it if you have suggestions to improve the quality of this documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
