### ISSUE TITLE
Updates for current Surface models and current MDT versions?

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/windows-itpro-docs#4267]
This page is 2 years and many different models out of date. Can it be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b04fea0-6da2-523f-0d7a-5545d8088ae8
* Version Independent ID: 13b39a29-418a-9072-1f00-6348132be6cf
* Content: [Deploy Windows 10 to Surface devices with Microsoft Deployment Toolkit (Surface)](https://docs.microsoft.com/en-us/surface/deploy-windows-10-to-surface-devices-with-mdt)
* Content Source: [devices/surface/deploy-windows-10-to-surface-devices-with-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/deploy-windows-10-to-surface-devices-with-mdt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @hoyty76 we appreciate you taking the time to open this issue and providing your feedback. This is what this site is for. Thanks for being part of the Microsoft Docs community!

Hi @Dansimp how are you? Can you please advise if updates to the "[Deploy Windows 10 to Surface devices with Microsoft Deployment Toolkit](https://docs.microsoft.com/surface/deploy-windows-10-to-surface-devices-with-mdt)" documentation will be forthcoming? Thank you.

**Comment by jvsam** [comment]
Hi @Dansimp how are you? Can you please advise if update to this documentation is forthcoming? Or it's still *accurate*? We appreciate the assistance, thanks.

**Comment by jvsam** [comment]
Hi again @hoyty76 so far we haven't received any update on this or if there is already an ongoing work related to this documentation. Do you have specific suggestions or do you see inaccuracies in the current doc? If you see any, what I will recommend for now is to identify those issues (_if there are_) and inform us about them and I can request someone to create a pull request and propose the amendments. Of course, they'll still be subject for review. Does this sound good? If there are no issues, I believe we can close this issue. We really appreciate your feedback.

**Comment by jvsam** [comment]
Hi @hoyty76 we didn’t hear from you so we will now close this issue. Again, if you see any problems with this documentation, e.g. inaccurate information, etc., feel free to re-open and let us know.  Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
