### ISSUE TITLE
GPO Path Name is Incorrect

### ISSUE THREAD

**Issue by artimob** [MicrosoftDocs/windows-itpro-docs#4274]
The article says expand "Windows components &gt; Windows Security &gt; Notifications" which is incorrect, starting from Windows 10, version 1709 and later the actual GPO path is "Windows components &gt; Windows Defender Security Center &gt; Notifications"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65d57fa8-9c9b-63cc-7248-175242963432
* Version Independent ID: 9cd96c93-8f46-64db-a162-02da1e1f63cc
* Content: [Hide notifications from the Windows Security app](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
Curious to see it reported like that, because as of version 1903 (OS build 18362.175) Windows 10 Pro is back to the using the policy path exactly as described in the article.

**Comment by artimob** [comment]
I don't have 1903 at hands, but on 1709 and 1803 (screen shot attached) branches it is definitely "Windows components > Windows Defender Security Center > Notifications". 

I believe, the article then should state "Windows components > Windows Defender Security Center > Notifications" or "Windows components > Windows Security > Notifications" as it refers to Windows 10, version 1709 and later

![2019-06-28-Image-winver-0i](https://user-images.githubusercontent.com/52269201/60306750-ccaaf700-9984-11e9-8c08-624678760aac.png)

**Comment by illfated** [comment]
Very well, fair enough. I presume it will be enough to get someone else with 1709 / 1803 to confirm that the GPO path is different from the article for the 1709 and 1803 releases, then decide on whether the page should separate into sections the specific releases 1709+1803 and the rest remaining as is, or if the page itself should be a Y-split link from the parent page.

**Comment by jvsam** [comment]
Hi @artimob, let me get this over to the Windows writing team for review and testing. We really appreciate your feedback and thank you for being part of the Microsoft Docs Community and for helping improve the quality of the technical documentation!

**Comment by jvsam** [comment]
@nenonix and @JohanFreelancer9 for copy review please. Thank you.

**Comment by JohanFreelancer9** [comment]
Copy Review - copy is fine.

**Comment by jvsam** [comment]
@JohanFreelancer9 it was my fault, I accidentally added the request on this issue (*and then deleted it*) rather than the in the PR's comment section :-D Thanks for reviewing!

**Comment by jvsam** [comment]
Hi @artimob good news, the suggested update to this documentation via Pull Request (PR) #4452 has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
