### ISSUE TITLE
Thumbnail images not available on "Deploy Microsoft Edge kiosk mode" page

### ISSUE THREAD

**Issue by andrefboliveira** [MicrosoftDocs/windows-itpro-docs#4275]
The images (https://docs.microsoft.com/en-us/images/Picture1.png) linked in this page give a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f840fa14-a379-d297-c3f7-ada05ec299d6
* Version Independent ID: 81396f7b-7506-43cd-fd9a-4066719a6eb2
* Content: [Deploy Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/microsoft-edge/deploy/microsoft-edge-kiosk-mode-deploy)
* Content Source: [browsers/edge/microsoft-edge-kiosk-mode-deploy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/microsoft-edge-kiosk-mode-deploy.md)
* Product: **edge**
* Technology: **microsoft-edge**
* GitHub Login: @eavena
* Microsoft Alias: **eravena**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
I think I can see why that happens, although my HTML reading skills may be a bit rusty:
```HTML
**Single-app**
<p>
  <a href="/images/Picture1.png"
      alt="Full-sized view single-app digital/interactive signage"
      target="_blank">![thumbnail](../images/Picture1-sm.png)
  </a>
<p>
```
Looks like the parent directory dots ( `../` ) are missing from the first link
(please correct me if I have misunderstood the direction).

**Comment by andrefboliveira** [comment]
Seems to be fixed now

**Comment by illfated** [comment]
The image can be seen (just as before) on the page https://docs.microsoft.com/en-us/microsoft-edge/deploy/microsoft-edge-kiosk-mode-deploy ,
but the link connected to the image is still broken. If you click the image, it still goes to an invalid URL:
- https://docs.microsoft.com/en-us/images/Picture1.png
- https://docs.microsoft.com/en-us/images/Picture2.png
- https://docs.microsoft.com/en-us/images/Picture5.png
- https://docs.microsoft.com/en-us/images/Picture6.png

All the links above point to a non-existing combination of file + directory (folder).

The affected actual Github page (include link) is as follows:
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/includes/configure-kiosk-mode-supported-values-include.md
This is the page from where we can open a Pull Request to fix the invalid links.

**Comment by jvsam** [comment]
Hi @andrefboliveira and @illfated, thank you. I'll ask the Windows writing team to create a Pull Request (PR) to correct the image links.

Correct image URLs (*original images, which should be used as image link attributes*). The thumbnail images are rendering correctly. 
https://docs.microsoft.com/microsoft-edge/deploy/images/Picture1.png
https://docs.microsoft.com/microsoft-edge/deploy/images/Picture2.png
https://docs.microsoft.com/microsoft-edge/deploy/images/Picture5.png
https://docs.microsoft.com/microsoft-edge/deploy/images/Picture6.png

**NOTE**: Languages and region codes are removed from URL since those are dynamic based on location.

Thanks for bringing this to our attention @andrefboliveira and for being part of the Microsoft Docs Community!

**Comment by illfated** [comment]
Fair enough. I am fairly certain that it will be enough to add relative directory dots before the existing path, which themselves are relative and don't contain the full path. I The text is also fairly short, although not arranged in an easy readable layout, but I should be able to open a pull request myself for the necessary changes.

**Comment by jvsam** [comment]
> The text is also fairly short, although not arranged in an easy readable layout, but I should be able to open a pull request myself for the necessary changes.

Thanks @illfated . So shall I just wait for your Pull Request (PR) then?

**Comment by illfated** [comment]
I was just about to make the recommended changes yesterday, but I ran into a temporary issue of overheating on my computer due to hot summer weather. I will make a new attempt this evening and link it back here when posting the PR.

**Comment by illfated** [comment]
There you go. Sorry for not answering your question more directly yesterday, thinking that I was going to post this change then.

**Comment by jvsam** [comment]
Thanks for creating the pull request, @illfated!

**Comment by illfated** [comment]
@andrefboliveira : Just to keep you informed, the Pull Request to solve the issue has been merged into the GitHub source text for the docs.microsoft.com pages, but it may take a few days more before it migrates to the docs.microsoft.com page, (Yes, I just noticed that it has already been 4 days, but let's give it at least a full week before it is anything to worry about.)
