### ISSUE TITLE
Typo: SignatureDefinitionUpdateFileSharesSouce 

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#4276]
Typo of SignatureDefinitionUpdateFileSharesSouce. It is missing the letter 'r' in Source. SignatureDefinitionUpdateFileSharesSouce  is used 3 times on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c033d14-427d-26d5-eca8-facf190da87d
* Version Independent ID: 624d52e5-6cf5-534e-83c3-66925292ddcd
* Content: [Manage how and where Windows Defender AV receives updates](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/manage-protection-updates-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/manage-protection-updates-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/manage-protection-updates-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
I would   like  to add two more points in this article.
01. For home user, in windows 10 professional edition,  setting location   as  Microsoft Update  Server is recommended.

02. Corresponding registry key should be added in this article .

So i like to create pull request tomorrow for changes

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for bringing this to our attention @iadgovuser1. I will get this over to the Windows writing team for review and correction (See: [-SignatureDefinitionUpdateFileSharesSources](https://docs.microsoft.com/powershell/module/defender/set-mppreference?view=win10-ps#-signaturedefinitionupdatefilesharessources)). Thanks again for being part of the Microsoft Docs Community and for helping improve the quality of the technical documentation! 

@RAJU2529 we appreciate your initiative. Please do not forget to reference this issue to your Pull Request (PR) and tag me. Thank you.

**Comment by RAJU2529** [comment]
@jvsam. Sir just now I sent  PR to author , issue no 4299.
Please assign Freelauncher to review and check spelling mistake , and then to forward to author for merging content.

Thanking you sir

**Comment by jvsam** [comment]
Hi @RAJU2529 can you please reference or link the Pull Request (PR) here so I can check? Thank you.

**Comment by RAJU2529** [comment]
@jvsam. 
**https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4299**

**Comment by jvsam** [comment]
Thank you for your contribution @RAJU2529. I've asked @MaratMussabekov to review your PR (#4299) then we'll submit it for copy review.

**Comment by jvsam** [comment]
Hi @iadgovuser1 the suggested updates to this documentation via Pull Request (PR) #4340 are approved and merged. The changes are displayed at docs.microsoft.com and you can verify by visiting this URL: https://docs.microsoft.com/windows/security/threat-protection/windows-defender-antivirus/manage-protection-updates-windows-defender-antivirus. We will now close this issue. Thank you for your feedback to help improve the contents of this document and for being part of the Microsoft Docs community!

@RAJU2529 the original feedback on this issue has been resolved. Your pull request with your suggestions is still in review. Please track the updates here - #4299. Thanks.

**Comment by jvsam** [comment]
@officedocsbot close
