### ISSUE TITLE
The table after the "TIP" is broken

### ISSUE THREAD

**Issue by pkellner** [MicrosoftDocs/windows-itpro-docs#4281]
Check the formatting, it's showing raw markdown in chrome at least.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3dd9c01-6d96-f3dd-c5fc-9565de8221bc
* Version Independent ID: 138ea771-3311-b31f-ccd1-2248871585a3
* Content: [Use Enterprise Mode to improve compatibility (Microsoft Edge for IT Pros)](https://docs.microsoft.com/en-us/microsoft-edge/deploy/emie-to-improve-compatibility)
* Content Source: [browsers/edge/emie-to-improve-compatibility.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/emie-to-improve-compatibility.md)
* Product: **browser-edge**
* Technology: **microsoft-edge**
* GitHub Login: @eavena
* Microsoft Alias: **eravena**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
@pkellner : Could you describe in what way the table is broken, or maybe post a screen shot of the issue you are seeing? I am looking at the page(s) and I don't see any broken tables, using Chrome 75.0.3770.100 (64 bit), Microsoft Edge 44.18362.1.0, Edge Chromium Version 77.0.197.1 (Official build) dev (64-bit), and Mozilla Firefox 67.0.4 (64-bit). I am at a loss for what I should be looking for.

**Comment by pkellner** [comment]
Looks good now. Not sure what was wrong last night. It was showing the raw table markdown.
