### ISSUE TITLE
2 subsection headings missing preceding blank lines

### ISSUE THREAD

**Issue by illfated** [MicrosoftDocs/windows-itpro-docs#4286]
The following 2 headings don't work as intended, most likely because there is no preceding blank line before the headings:
```
## Enable Windows Mixed Reality in WSUS
```
```
## Block the Mixed Reality Portal
```
On Github, this (en-us) page contains a preceding blank line before the headings, but I am uncertain if there is some added whitespace between the hashtags (##) and the text, creating this issue. (This is more or less a note to self, unless anyone else want to open a PR to solve this ticket before I manage to get around to create the PR myself.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d4c6ca-ae3c-7750-f58b-0df996e41402
* Version Independent ID: 0d05fd22-b761-6fb4-8686-a2021573e542
* Content: [Enable or block Windows Mixed Reality apps in the enterprise (Windows 10)](https://docs.microsoft.com/en-us/windows/application-management/manage-windows-mixed-reality#feedback)
* Content Source: [windows/application-management/manage-windows-mixed-reality.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/manage-windows-mixed-reality.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by illfated** [comment]
Follow-up background info: the page contains the following raw text, creating the aforementioned issue:
```
<span id="enable" />
## Enable Windows Mixed Reality in WSUS
```
```
<span id="block" />
## Block the Mixed Reality Portal
```
Looks like I was onto something back when I posted my question on whether or not those HTML tags need to be there at all. I guess I should have recommended the removal of those HTML tags because all the rest of the page is purely MarkDown code on Github.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by illfated** [comment]
Oh, and by the way: Ref. old and closed issue ticket #3805 which led to this discovery.

**Comment by mypil** [comment]
@illfated - It would be amazing if you could create the PR for this issue. Please let me know the related PR so I can tag the doc owner to review and merge the PR content. 

We appreciate your effort and feedback that helps us improve the content. Thank you!

**Comment by illfated** [comment]
Very well, I am also hoping to create the necessary PR for this change. I just need to do it from my workplace instead of from home (I moved to a new address last night, removing myself from my existing home internet connection). Unless it takes more than an hour to complete the install of Git + Git Extensions + clone the MS Docs IT Pro repository to my company computer, I will create a PR for this issue.

**Comment by illfated** [comment]
Thankfully, I was able to install Git Extensions + Git + kdiff3 as well as sign in with my correct credentials (had to look up the fine details in my own profile, been a while since I last configured this at home). See you again on Monday, I will be offline during most of the weekend. 👋 🌞

**Comment by illfated** [comment]
(just rebased my PR commit to keep it on top of my local cloned fork of `windows-itpro-docs` -- no changes)
