### ISSUE TITLE
Add section the documents WDAG functionality differences in Pro vs Enterprise

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#4288]
It would be useful to add a section to this page that describes the functionality difference of WDAG when on Windows 10 Pro versus Windows 10 Enterprise. One difference is mentioned in the FAQ. WDAG Enterprise mode is only available with Enterprise edition (the name implies this but is not explicitly documented anywhere). Pro only has Standlone mode available. I'm sure there are other small differences.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfb9445a-681d-24b6-5241-4ebe311f5236
* Version Independent ID: aea60f74-212c-e24e-f164-28a555bc1727
* Content: [Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thanks for the suggestion @iadgovuser1. I will forward this to the Windows writing team for review and consideration. Please continue to share your suggestions or ideas on how to improve the docs. Thanks for being part of the Microsoft Docs community!

**Comment by TokyoScarab** [comment]
Hello and thank you for the suggestion @iadgovuser1 !  I will be reviewing this suggestion and editing the documentation to better suit this suggestion.

**Comment by TokyoScarab** [comment]
@iadgovuser1 There is a section in a later page of the WDAG documentation that does explain these differences between WDAG on Pro vs Enterprise.  The main difference is that you have Standalone Mode (which is on Pro and Enterprise) and Enterprise Mode (which is only for Enterprise).  That page of documentation is located [here](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-guard/install-wd-app-guard#prepare-for-windows-defender-application-guard).  I will update the FAQ to show that a difference exists as well as what it is.

**Comment by iadgovuser1** [comment]
Thanks. I wasn't sure if there more unknown/undocumented differences not captured in the docs already.

**Comment by jvsam** [comment]
Hi @iadgovuser1 I would assume you were able to review pull request #4532, so far that is the only information that we can verify, hence, it has been approved and merged. This update will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue since we consider this as *resolved*. Feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation, particularly if you find new information related to *WDAG differences between Windows 10 Pro and Windows 10 Enterprise*.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by iadgovuser1** [comment]
Thanks!
