### ISSUE TITLE
[LOC]"_Local_machine" need to be replaced with "HKEY_LOCAL_MACHINE"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#4295]
ja-jp:https://docs.microsoft.com/js-jp/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services
![manage-connections-from-windows-operating-system-components-to-microsoft-services_j4](https://user-images.githubusercontent.com/40815708/60391117-74116080-9b22-11e9-94ec-defca83164e0.png)

en-us:https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services
![manage-connections-from-windows-operating-system-components-to-microsoft-services_e4](https://user-images.githubusercontent.com/40815708/60391118-770c5100-9b22-11e9-8057-e9c8ed487c4f.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 9abd3113-b803-87b6-ef7f-6893bcc5ceb5
* Version Independent ID: 6f7ca1ee-d19c-42bb-7db5-6158fc160e32
* Content: [Windows オペレーティング システムのコンポーネントから Microsoft サービスへの接続の管理 (Windows 10)](https://docs.microsoft.com/ja-jp/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services)
* Content Source: [windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@dongmicro An issue similar to the previously addressed issue, #3481 is available for investigation. Thank you.

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot unassign @TinaMcN

**Comment by illfated** [comment]
@e0i : Sorry that I missed this issue ticket earlier. You need to assign instead of unassign @TinaMcN to this issue, as well as unassigning @dongmicro . Thank you.

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
@hyoshioka0128 
![image](https://user-images.githubusercontent.com/53281468/67132933-7249d680-f1bf-11e9-953a-d43692850a96.png)

**Comment by illfated** [comment]
`HKEY_LOCAL_MACHINE` occurrences: 105
`_LOCAL_MACHINE` occurrences: 105 (same)
`HKEY_Current_User` occurrences: 15
`_Current_User` occurrences: 15 (same)

Looks resolved to me. 👍

**Comment by hyoshioka0128** [comment]
@TinaMcN @illfated _Fixed.
 Closed #4295
Thanks.
