### ISSUE TITLE
Proxy Config for MDATP for MacOS

### ISSUE THREAD

**Issue by phillym** [MicrosoftDocs/windows-itpro-docs#4297]
Hi there,
I can't see anywhere to configure proxy config for MDATP for MacOS. Does MDATP honour OS X secure web proxy config in 'System Preferences/Network/Proxies' or does it need an environment variable set?
Keep up the good work!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5c929d-414f-70b8-c687-e9a60ef709e3
* Version Independent ID: a3cde3f5-e7a1-e0cc-aeae-fd6123f696c5
* Content: [Set preferences for Microsoft Defender ATP for Mac](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac-preferences#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac-preferences.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac-preferences.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@phillym - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
