### ISSUE TITLE
Windows 10 1903 links 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#4300]
Sir  I want to add direct download link page in this article. 
Microsoft windows 10 page is not available , once I get correct link .I will update
After that  I will create PR  to author.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0eb8c97-caa0-bb05-4b91-14ad2adc4aac
* Version Independent ID: 0cc541a3-8198-c029-d795-308e673ee2f4
* Content: [Create a Windows 10 reference image (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image#add-the-microsoft-office-professional-plus-2013-x86-installation-files)
* Content Source: [windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@RAJU2529 - Thank you for submitting feedback. Please let me know once you have created the PR so I can help to engage the doc owner to review it for merging.

**Comment by RAJU2529** [comment]
i am closing this issue. because my previous 3 PR are closed without telling reason . I felt really bad. If I create new PR with additions, then future PR might will close without merging.

**Comment by mypil** [comment]
@RAJU2529 - Sorry to hear that the previous PRs you created were closed but there must be a reason stated why it was closed. It is really the discretion of the doc owner whether they will merge the PR or not. 

We still appreciate your valuable feedback that could help improve the docs.

**Comment by mypil** [comment]
@officedocsbot close
