### ISSUE TITLE
Is it possible to activate Win10 with MS365 E3 sub without Win10 Pro Key?

### ISSUE THREAD

**Issue by char-iot** [MicrosoftDocs/windows-itpro-docs#4305]
I've got a Intel NUC kit and MS365 E3 subscription. Is there Windows 10 Enterprise ISO?

Can I activate Win10 Enterprise without Win10 Pro Activation Key? The description in this docu doesn't really tell.

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ecbc1-9c02-5681-7214-356be22ac7e8
* Version Independent ID: 73af82f6-079b-6c37-55c4-cb59e921457a
* Content: [Deploy Windows 10 Enterprise licenses](https://docs.microsoft.com/en-gb/windows/deployment/deploy-enterprise-licenses)
* Content Source: [windows/deployment/deploy-enterprise-licenses.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-enterprise-licenses.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by RAJU2529** [comment]
Yes there is  Windows  10 enterprise iso separately is available from Volume licensing site.or MSDN site.
if you enter windows 10 pro key is  used to activate only for windows 10 pro.
To activate windows 10 enterprise, you need volume license key or  standard key ent key.
But i dont know  about  E3 or E5 subscription

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@char-iot - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by char-iot** [comment]
@mypil I thought you guys are MS.

anyway.

I opened a ticket and MS support anwsered quickly that Win 10 pro activation is a requirement for Win 10 Enterprise activation.

**Comment by illfated** [comment]
Thank you for the valuable feedback. Just to provide some information about this site: This is the Github issue tracker for the Windows 10 IT Pro documentation, meaning that errors, omissions and requests for updates on new features can be posted here, to improve the existing documentation for Microsoft Docs (Windows 10 IT Pro Docs). Beyond this scope, questions are better answered directly by Microsoft Support in your local operational area.
