### ISSUE TITLE
This article makes it seem as if Windows Server 2019 is the minimum version for a Domain Controller for WHfB

### ISSUE THREAD

**Issue by rickengle** [MicrosoftDocs/windows-itpro-docs#4306]
The documentation is confusing on this page:
Planning an adequate number of Windows Server 2019 Domain Controllers for Windows Hello for Business deployments
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers

I think Windows Server 2016 was globally renamed to Windows Server 2019 but by doing that it makes it less clear that in fact Windows Serer 2016 and greater are fine as domain controllers for Windows Hello for Business.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1da1ac4-4e67-5970-6d10-19aac6e853f6
* Version Independent ID: 4f4b45eb-d479-3699-1ef1-a1a20030d675
* Content: [Planning an adequate number of Windows Server 2019 Domain Controllers for Windows Hello for Business deployments](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@rickengle - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @rickengle ,Thank you for your query on the doc. Please note that Windows Server 2019 is not a rename of Windows Server 2016. Please see https://www.microsoft.com/en-us/cloud-platform/windows-server-comparison to get a detailed comparison of Windows Server editions. 

Thanks.

**Comment by rickengle** [comment]
What I meant by a rename is that in that document, it looks like the name Windows Server 2016 was replaced with a search and replace to Windows Server 2019.  That doc makes it seem now that Windows Server 2019 is the server version required.  It should in fact state that Windows Server 2016 and higher are supported rather than only mentioning Windows Server 2019.

Rick

**Comment by joinimran** [comment]
Thanks @rickengle , I have updated the doc and sent for approval. Once approved, changes will reflect in the doc.

**Comment by rickengle** [comment]
That is wonderful!
  Rick

**Comment by mypil** [comment]
@rickengle -  From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by rickengle** [comment]
That’s super, good job, I’ll check it out after it propagates.

Rick

**Comment by mypil** [comment]
@officedocsbot close
