### ISSUE TITLE
Add another action item for Event ID 29

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#4311]
Under the **Review events and errors using Event Viewer** section, add another item to check under the Action column for Event ID 29: Ensure the offboarding package has not expired.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 418cf225-ff48-aa75-5079-6fa46600c700
* Version Independent ID: 05fc334c-f9a3-4836-dbf2-f3864463fa10
* Content: [Review events and errors using Event Viewer](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/event-error-codes)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/event-error-codes.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/event-error-codes.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@iadgovuser1 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@iadgovuser1 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
