### ISSUE TITLE
Local Administrator Rights Required?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/windows-itpro-docs#4314]
In a scenario where a user has an M365 license - must they also be local administrators on their machine? We are encountering issues where activation fails to "contact the server" until they are added to this group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation#requirements)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Mike-Crowley - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by Mike-Crowley** [comment]
Lol, the reason I read the documentation is because I don't want to waste all day talking to someone across the globe who barley understands my language, let alone how subscription activation works in M365 Business. Do you not have a more efficient internal channel you can use to see if this is a requirement?

**Comment by mypil** [comment]
@Mike-Crowley - Sorry to hear that you are having issues. Please understand that this site is a product documentation site and not a support nor a feature request site.

As such, the feedback section here is intended for feedback that improves the content in the Microsoft documentation and not intended for user feedback on product features nor troubleshooting.

For user feedback on product feature requests, you can submit via [Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). I know the product teams are always looking for user feedback on how to make Windows 10 better. You might find others have made a similar request that you can add to, or you can open a new one.

For technical queries or troubleshooting, you can visit **support.microsoft.com**, **answers.microsoft.com** or open a [support ticket](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10).

I hope this gets you pointed in the right direction. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
