### ISSUE TITLE
Does suspend terminate write-lock?

### ISSUE THREAD

**Issue by freakynl** [MicrosoftDocs/windows-itpro-docs#4320]
Hi,

we have a customer where we migrated the fileserver from 2008 -&gt; 2016.

When they were on 2008 and a user opened an excelsheet and did nothing with it for hours at an end, other users still couldn't open it (would get a message it was in use by user A and that they can only open it read-only).

Since the migration to 2016 this no longer happens after some time (somewhere in the 1-4 hours range). User B can then just open the file eventhough A still has it open. This doesn't happen if A is active or opened it recently.

The client is a terminal server, it doesn't go to sleep.

Could SMB suspend be the cause of this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2291e02c-6e5b-e9b9-b8d0-1ce2d71ad32d
* Version Independent ID: 0ee07415-d973-44c1-2b7f-f0f36a96276f
* Content: [Microsoft network server Amount of idle time required before suspending session (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/microsoft-network-server-amount-of-idle-time-required-before-suspending-session#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/microsoft-network-server-amount-of-idle-time-required-before-suspending-session.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/microsoft-network-server-amount-of-idle-time-required-before-suspending-session.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@freakynl - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
