### ISSUE TITLE
References to Windows 8, XP and 2003 serve no purpose

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/windows-itpro-docs#4323]
There are references to how some settings behave in Windows 8, XP and 2003, but this is inaccurate, as those operating systems don't support CSP anyway. I arrived at this page after searching for "clipboard csp" only to find this erroneous information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9211a7fc-f4e9-564a-fdd1-087d0c200c81
* Version Independent ID: 0aff48dd-a1a7-39a3-4c0b-17135d1c8401
* Content: [Policy CSP - RemoteDesktopServices](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-remotedesktopservices)
* Content Source: [windows/client-management/mdm/policy-csp-remotedesktopservices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-remotedesktopservices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Mike-Crowley - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by RAJU2529** [comment]
under footnote. These csp policy settings are added in windows 10 v1607 or later version.

Windows xp   server 2003 does not supported. 
Nowadays Microsoft only concentrates for windows 10 1903 and server 2019 version to make secured OS.

**Comment by ojrb** [comment]
hi @mypil ! the PR #4428 solved this issue. Please review and merge !

**Comment by mypil** [comment]
@Mike-Crowley - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
