### ISSUE TITLE
Microsoft 365 Business, E3 ou E5

### ISSUE THREAD

**Issue by aymenkalboussi** [MicrosoftDocs/windows-itpro-docs#4337]
Activation impossible de Windows 10 sur une nouvelle machine (free DOS).

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Activation d’abonnement Windows10](https://docs.microsoft.com/fr-fr/windows/deployment/windows-10-subscription-activation#feedback)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Online translation:
> Windows 10 cannot be activated on a new machine (free DOS).

Hi @aymenkalboussi thanks for bringing this to our attention. From the information you have provided, I   understand that you are on E3/E5 and is trying to use the Subscription Activation feature but it doesn't work? If that's the case and your issue doesn't have anything to do about the content of this documentation, I suggest that you please open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance.

This site is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. If you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review.

**Comment by jvsam** [comment]
Hi again @aymenkalboussi, I just want to follow-up if you were able to contact Windows 10 Support regarding your concern? Let us know if the resolution is something that can be called out in the docs. If your issue is related to the content of this documentation, please provide more information. We always strive to give users the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, accurate and up-to-date. Thank you.

**Comment by jvsam** [comment]
Hi again @aymenkalboussi, we haven't heard or received any updates from you. We are hoping that the information we shared helped point you to the right direction to get assistance. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
