### ISSUE TITLE
affected OS missing at the top of the page

### ISSUE THREAD

**Issue by AndreasDiet** [MicrosoftDocs/windows-itpro-docs#4345]
[Enter feedback here]
please add server 2019 as affected OS at the beginning of
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f316427f-86b4-1b53-727b-64b49cd0e16f
* Version Independent ID: 834aaa0f-ede0-9819-e4b3-ba49217da5da
* Content: [Allow COM object registration in a Windows Defender Application Control policy (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mdsakibMSFT

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment]
@AndreasDiet . affected OS  are 
windows 10 pro.
windows 10 enterprise.
server 2016.
server 2019.
windows 10 home ( connected to server and configured).
because WDAC  policy confiGured by GPO.

**Comment by AndreasDiet** [comment]
Sir,

to be honest: pro is not affected by this
see: https://social.technet.microsoft.com/wiki/contents/articles/33557.windows-10-editions-skus-and-features.aspx

better would be : all Windows 10 versions for x86 and x64, with the exception of Home, Pro, and S version SKUs, as well as IoT Core.

**Comment by jvsam** [comment]
Hi @AndreasDiet thank you so much for your suggestion. Let me get this over to the Windows content writing team for review and to suggest the addition of all applicable Windows editions. We really appreciate your feedback and thank you again for being part of the Microsoft Docs Community and for helping improve the quality of the technical documentation! ﻿

**Comment by jvsam** [comment]
Hi again @AndreasDiet the suggested update that adds *Windows Server 2019* to this documentation via Pull Request (PR) #4437 has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
