### ISSUE TITLE
I don't think the syntax is correct for autolaunch

### ISSUE THREAD

**Issue by tschuyler99** [MicrosoftDocs/windows-itpro-docs#4356]
I have tried for months on TechNet to get an answer to this problem. I have never been able to get any program to auto-launch, which was supposed to be included in build 1809. Until Someone proves that it works, I will continue to post everywhere that I can, that this promised feature doesn't work.

I get this error every time I try to include an autolauch of any program. I see other people struggling with this error as well on forums with no answers. 

: 0__AssignedAccess_MultiAppAssignedAccessSettings.provxml
                        Category:UxLockdown
                        LastResult:Error -1072898027 (0xC00CE015)
                        Message:Provisioning failed
I am using the XML full example from the link on this page. If I take out the rs5:AutoLaunch="true" I can make provisioning packages that work fine with multiple apps in the proper grid formation for a particular user.

Here is the command from the full xml reference:
~~~
"<App DesktopAppPath="%SystemRoot%\system32\notepad.exe" rs5:AutoLaunch="true" rs5:AutoLaunchArguments="123.txt"/>"
~~~
I have not been able to get anyone to prove to me that this feature has ever worked. I am looking for an example xml from someone that works to auto launch a program like paint or notepad. Anyone...
I have done this on many different laptops with different OS versions and it never works with auto launch. **This is unusable in a business environment**. One main reason for using kiosk mode is to load an app at login.
Thanks

Currently using Windows 10 enterprise build 1809.
Here is the XML I am using. 
This is right off the full xml reference guide. I narrowed it to one profile and one user account. I changed the GUID lines with a different GUID. **This package loads fine as it is below.** If I put back the rs5:AutoLaunch="true" rs5:AutoLaunchArguments="123.txt" on the notepad app, **like it is in the full reference guide**, it fails with the same error. I have tried many different XML files and PPKG configs. I have tried many programs other than notepad and nothing works with auto launch. 

~~~
<?xml version="1.0" encoding="utf-8" ?>
<AssignedAccessConfiguration 
    xmlns="http://schemas.microsoft.com/AssignedAccess/2017/config"
    xmlns:rs5="http://schemas.microsoft.com/AssignedAccess/201810/config"
    >
    <Profiles>    
 <Profile Id="{33C27E03-5055-459C-990C-79AF47B05B1D}">
            <AllAppsList>
                <AllowedApps>
                    <App AppUserModelId="Microsoft.BingWeather_8wekyb3d8bbwe!App" />
                    <App AppUserModelId="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!BCHost" />
                    <App AppUserModelId="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!ContentProcess" />
                    <App AppUserModelId="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!F12" />
                    <App AppUserModelId="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge" />
                    <App AppUserModelId="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!PdfReader" />
                    <App DesktopAppPath="%SystemRoot%\system32\notepad.exe" />
                </AllowedApps>
            </AllAppsList>
            <StartLayout>
                <![CDATA[<LayoutModificationTemplate xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout" xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout" Version="1" xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification">
                      <LayoutOptions StartTileGroupCellWidth="6" />
                      <DefaultLayoutOverride>
                        <StartLayoutCollection>
                          <defaultlayout:StartLayout GroupCellWidth="6">
                            <start:Group Name="Life at a glance">
                              <start:Tile Size="2x2" Column="0" Row="0" AppUserModelID="Microsoft.BingWeather_8wekyb3d8bbwe!App" />
                              <start:Tile Size="4x2" Column="0" Row="4" AppUserModelID="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge" />
                              <start:DesktopApplicationTile Size="2x2" Column="2" Row="0" DesktopApplicationLinkPath="%AppData%\Microsoft\Windows\Start Menu\Programs\Accessories\notepad.lnk" />
                            </start:Group>
                          </defaultlayout:StartLayout>
                        </StartLayoutCollection>
                      </DefaultLayoutOverride>
                    </LayoutModificationTemplate>
                ]]>
            </StartLayout>
            <Taskbar ShowTaskbar="false"/>
        </Profile>
    </Profiles>
    <Configs>
        <Config>
            <Account>user</Account>
            <DefaultProfile Id="{33C27E03-5055-459C-990C-79AF47B05B1D}"/>
        </Config>
    </Configs>
</AssignedAccessConfiguration>
~~~
"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78038d67-04a1-f4ae-6a69-98e157688a31
* Version Independent ID: c86b4460-e8be-8537-a6c8-3cb094ef14a3
* Content: [Set up a multi-app kiosk  (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps)
* Content Source: [windows/configuration/lock-down-windows-10-to-specific-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/lock-down-windows-10-to-specific-apps.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by tschuyler99** [comment]
I am not sure why but it took out some of my post including the sections showing any xml. If anyone picks up on this, I can provide the needed information

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
@tschuyler99 : To include code like HTML, XML or other tag-based code,
it is necessary to use MarkDown code fencing with back ticks **```**
or tilde **~~~** before & after the code you want displayed.
See also
https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown
for reference.

**Comment by tschuyler99** [comment]
Thank you very much. I was able to add that to my post so the XML is showing now. I hope someone can do some testing and prove me wrong or come up with a solution to the auto-launch issue.

**Comment by illfated** [comment]
Good job. Also, if you want to see Syntax Highlighting, you can always apply the code language tag to the starting code block fence, e.g. ```xml
or uppercase XML -- check yourself by using comment preview to see if there is any difference between them.

**Comment by chandde** [comment]
@tschuyler99 : This is Chandler from Microsoft engineering team working on Assigned Access. I just tried WCD with custom xml for multi-app Assigned Access, I was able to configure auto-launch using the same xml without issue, on Windows 10 1809 (17763.1).

Can you share more information of your environment, e.g. the detailed version of Windows (by running "winver.exe")? 

Thanks
Chandler

**Comment by tschuyler99** [comment]
After many different attempts I finally have an XML that has the auto-launch working. I was able to launch notepad or mspaint. I have no idea what changed, but at least I have a working XML and proof that the feature works now. That was all I was asking for was someone to show me a working XML. I have been on 1809 for all this testing. 

Anyone know how to make Google Chrome work in kiosk mode in the multi-app environment? If I put the --kiosk http://website information in the shortcut, kiosk mode works under administrator. But the --kiosk doesn't seem to carry through to the multi-app assigned access user.
Thanks

**Comment by illfated** [comment]
@tschuyler99 : Closing your issue is OK if you don't want anything more to be added to this discussion. But reading your last comment, it looks like you would like to have additional answers regarding kiosk and Chrome. Are you planning to open a new issue ticket for this?

**Comment by tschuyler99** [comment]
It is no longer a problem with the XML websites where I posted my complaints. I will not open another ticket. I might try TechNet and other places. It looks like chrome is not really supported in assigned access. Thanks for the help

**Comment by illfated** [comment]
Very well, fair enough. Your ticket closure seems acceptable.
