### ISSUE TITLE
Autolaunch does not seem to work

### ISSUE THREAD

**Issue by tschuyler99** [MicrosoftDocs/windows-itpro-docs#4357]
I have tried for months on TechNet to get an answer to this problem. I have never been able to get any program to auto-launch, which was supposed to be included in build 1809. Until Someone proves that it works, I will continue to post everywhere that I can, that this promised feature doesn't work.

I get this error every time I try to include an auto-launch of any program. I see other people struggling with this error as well on forums with no answers. 

: 0__AssignedAccess_MultiAppAssignedAccessSettings.provxml
                        Category:UxLockdown
                        LastResult:Error -1072898027 (0xC00CE015)
                        Message:Provisioning failed
I am using the XML full example from this site. If I take out the rs5:AutoLaunch="true" I can make provisioning packages that work fine with multiple apps in the proper grid formation for a particular user.

Here is the command from the full xml reference:
~~~
"<App DesktopAppPath="%SystemRoot%\system32\notepad.exe" rs5:AutoLaunch="true" rs5:AutoLaunchArguments="123.txt"/>"
~~~
I have not been able to get anyone to prove to me that this feature has ever worked. I am looking for an example xml from someone that works to auto launch a program like paint or notepad. Anyone...
I have done this on many different laptops with different OS versions and it never works with auto launch. **This is unusable in a business environment**. One main reason for using kiosk mode is to load an app at login.
Thanks

Currently using Windows 10 enterprise build 1809.
Here is the XML I am using. 
This is right off the full xml reference guide. I narrowed it to one profile and one user account. I changed the GUID lines with a different GUID. **This package loads fine as it is below.** If I put back the rs5:AutoLaunch="true" rs5:AutoLaunchArguments="123.txt" on the notepad app, **like it is in the full reference guide**, it fails with the same error. I have tried many different XML files and PPKG configs. I have tried many programs other than notepad and nothing works with auto launch. 

~~~
<?xml version="1.0" encoding="utf-8" ?>
<AssignedAccessConfiguration 
    xmlns="http://schemas.microsoft.com/AssignedAccess/2017/config"
    xmlns:rs5="http://schemas.microsoft.com/AssignedAccess/201810/config"
    >
    <Profiles>    
 <Profile Id="{33C27E03-5055-459C-990C-79AF47B05B1D}">
            <AllAppsList>
                <AllowedApps>
                    <App AppUserModelId="Microsoft.BingWeather_8wekyb3d8bbwe!App" />
                    <App AppUserModelId="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!BCHost" />
                    <App AppUserModelId="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!ContentProcess" />
                    <App AppUserModelId="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!F12" />
                    <App AppUserModelId="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge" />
                    <App AppUserModelId="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!PdfReader" />
                    <App DesktopAppPath="%SystemRoot%\system32\notepad.exe" />
                </AllowedApps>
            </AllAppsList>
            <StartLayout>
                <![CDATA[<LayoutModificationTemplate xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout" xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout" Version="1" xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification">
                      <LayoutOptions StartTileGroupCellWidth="6" />
                      <DefaultLayoutOverride>
                        <StartLayoutCollection>
                          <defaultlayout:StartLayout GroupCellWidth="6">
                            <start:Group Name="Life at a glance">
                              <start:Tile Size="2x2" Column="0" Row="0" AppUserModelID="Microsoft.BingWeather_8wekyb3d8bbwe!App" />
                              <start:Tile Size="4x2" Column="0" Row="4" AppUserModelID="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge" />
                              <start:DesktopApplicationTile Size="2x2" Column="2" Row="0" DesktopApplicationLinkPath="%AppData%\Microsoft\Windows\Start Menu\Programs\Accessories\notepad.lnk" />
                            </start:Group>
                          </defaultlayout:StartLayout>
                        </StartLayoutCollection>
                      </DefaultLayoutOverride>
                    </LayoutModificationTemplate>
                ]]>
            </StartLayout>
            <Taskbar ShowTaskbar="false"/>
        </Profile>
    </Profiles>
    <Configs>
        <Config>
            <Account>user</Account>
            <DefaultProfile Id="{33C27E03-5055-459C-990C-79AF47B05B1D}"/>
        </Config>
    </Configs>
</AssignedAccessConfiguration>
~~~

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by tschuyler99** [comment]
After many different attempts I finally have an XML that has the auto-launch working. I was able to launch notepad or mspaint. I have no idea what changed, but at least I have a working XML and proof that the feature works now. That was all I was asking for was someone to show me a working XML. I have been on 1809 for all this testing.

Anyone know how to make Google Chrome work in kiosk mode in the multi-app environment? If I put the --kiosk http://website information in the shortcut, kiosk mode works under administrator. But the --kiosk doesn't seem to carry through to the multi-app assigned access user.
 Thanks

**Comment by jvsam** [comment]
We're glad that you were able to resolve your issue @tschuyler99 and thanks for updating us here and and on issue #4356. As you have stated on *4356*, asking the community via TechNet might be the best course of action if you have questions or concerns related to features or products. You also have an option to contact [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) if you need technical assistance. 

Also, since this Github site is intended to help improve the quality of the technical documentation, if you have suggestions or ideas to make the docs better, please let us know and we will submit them for review. Thanks for being part of the Microsoft Docs community!

**Comment by sccmentor** [comment]
> After many different attempts I finally have an XML that has the auto-launch working. I was able to launch notepad or mspaint. I have no idea what changed, but at least I have a working XML and proof that the feature works now. That was all I was asking for was someone to show me a working XML. I have been on 1809 for all this testing.
> 
> Anyone know how to make Google Chrome work in kiosk mode in the multi-app environment? If I put the --kiosk http://website information in the shortcut, kiosk mode works under administrator. But the --kiosk doesn't seem to carry through to the multi-app assigned access user.
> Thanks

Could you explain what your fix was? I cannot get autolaunch to work successfully.
