### ISSUE TITLE
ServicesAllowedList Supported Versions

### ISSUE THREAD

**Issue by terickson81** [MicrosoftDocs/windows-itpro-docs#4363]
The document does not clearly state what versions of Windows 10 support the ServicesAllowedList feature. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9596a57e-365e-2809-1f8d-8aebbda5bc36
* Version Independent ID: 4a287709-2466-93eb-cc2f-9f7566277abb
* Content: [Policy CSP - Bluetooth](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-bluetooth#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-bluetooth.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-bluetooth.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign

**Comment by RAJU2529** [comment]
I seen Bluetooth group policy settings in windows 10 pro 1809 or later editions. 
normally specified article csp , will support server 2012 or sever 2016 or sever 2019.
for client Windows10 pro or enterprise or education

**Comment by jvsam** [comment]
Hi @terickson81 we appreciate your feedback. Thank you.

@ManikaDhiman is this something that you can add to the documentation? Can you please confirm that *ServicesAllowedList* supports Windows 10 Home, Pro, Enterprise, and Education for desktop as well as Windows 10 Mobile? Kindly let us know. I can also request one of the freelance tech writers to check and create a pull request, but you're the expert here, so I've opted to ask you first. Thank you.

**Comment by terickson81** [comment]
Thanks @jvsam,
It would be helpful to know the editions (Home, Pro, Enterprise) as well as the build releases (1709, 1803, 1809, 1903) that supports the feature.

**Comment by ManikaDhiman** [comment]
Hi @jvsam, product team confirmed that the SKU table under Bluetooth/ServicesAllowedList policy description provides the correct SKU info. And, this policy was added in Windows 10, version 1511. Hope this answers all your questions. Thanks!

**Comment by terickson81** [comment]
Thanks @ManikaDhiman and @jvsam! We've been trying to disable the Bluetooth file transfer service for a long time, and hoping this feature will provide that option.

**Comment by jvsam** [comment]
Hi again @terickson81, this documentation has been updated (Refer: commit [829aac7](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/829aac7ed672388cd8cdd15213133bd01323b25b) added by @ManikaDhiman), and it now includes Windows 10, version 1511. See https://docs.microsoft.com/windows/client-management/mdm/policy-csp-bluetooth, *Bluetooth/ServicesAllowedList* section. As confirmed, the SKU information is also accurate. We will now close this issue. Thank you for your feedback to help improve the contents of this documentation and for being part of the Microsoft Docs community!

Hi @ManikaDhiman your assistance is appreciated. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
