### ISSUE TITLE
What is the difference between win10 Pro and Win10 Enterprise?

### ISSUE THREAD

**Issue by mode86** [MicrosoftDocs/windows-itpro-docs#4364]
I have a question about the "Professional editions are only supported for non-managed devices."
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard#software-requirements

Does this "non-managed devices" mean devices not managed by Intune or MDM?
In the case of Windows 10 Pro, does it mean that it can not be used together with Intune or MDM?
What is the difference between win10 Pro and Win10 Enterprise?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f43df7b-6ead-de5a-2e41-4d49978ab485
* Version Independent ID: 5497d300-cb21-55f3-7e80-98bc3592635c
* Content: [System requirements for Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@mode86 . here is the website which differentiate windows 10 editions.
please visit beLow link.
https://www.microsoft.com/en-us/WindowsForBusiness/Compare

**Comment by RAJU2529** [comment]
@mode86 . MDM means mobile device management that means, organisation system administrator can configure the device by applying group policy settings.
intune also doing same thing , but it requires license with device must be joined 

Windows 10 pro for workstation is supported. This edition is Not available for normal users.

**Comment by RAJU2529** [comment]
@jvsam . @illfated. I want to add few more points as per request issue 4364. so I like to create PR tomorrow after getting certain points

**Comment by mode86** [comment]
@RAJU2529 .  Thank you very much for this kind reply.
I'm sorry that my question wasn't clear.

What I want to know is when using WDAG (Windows Defender Application Guard) in Windows 10 Professional edition.
(Not a Windows 10 pro for workstation edition or a Windows 10 Enterprise edition.)

and, I did not understand the meaning of the content described below.
--
Professional editions are only supported for non-managed devices; 
Intune or any other 3rd party mobile device management (MDM) solutions are not supported with WDAG for Professional editions.
---

I first thought as follows,
If my device is Windows 10 Professional edition and is managed by Intune or MDM, it means that I can not use WDAG.

But I think as follows now, 
Windows 10 Professional edition's WDAG can be used in WDAG's "stand-alone" mode but does not support WDAG's "enterprise mode".
So, It can not be managed with Intune or MDM.

Is my understanding correct?

**Comment by RAJU2529** [comment]
@mode86 . Sir I don't have intune or azure subscription and no practical experience in this regard.Only practical experienced can give real difference.. .
@jsvam  @illfated both are able to give answer

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@mode86 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by Reeced40** [comment]
@mode Thank you for helping improve MS Docs, I will investigate further.

**Comment by Reeced40** [comment]
@mode86 Please have a look at this new doc and let me know if this helps answer your question and I can have it added to the article. https://docs.microsoft.com/intune/whats-new

**Comment by mypil** [comment]
@mode86 - From our understanding, the issue has been answered by Reeced40. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by illfated** [comment]
@mode86 : Maybe you are on vacation/holiday or some other leave, but feel free to post back if and when you have got more feedback to share in this case.

**Comment by mode86** [comment]
@Reeced40, @mypil, @illfated Thanks all and I'm sorry for the late reply
The answer to my question was not listed in the URL that I received from Reeced40.

However, my question was solved.

At first, when I browsed the following URL, it was difficult to understand the contents.
I did not know what “unmanaged device” means that in the description of WDAG.
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard#software-requirements

If possible, I think it would be better if there is a more detailed explanation.
--- For example,
Windows 10 Professional edition's WDAG can be used in WDAG's "stand-alone" mode but does not support WDAG's "enterprise mode".
So, It can not be managed with Intune or MDM.

**Comment by illfated** [comment]
Thank you for replying again. I can see that documentation can be somewhat confusing sometimes,
especially if you are trying to find a solution to an unsolved problem in your work flow.

@Reeced40 : Do you have any opinion on whether or not this part of the docs need to be de-obfuscated?
