### ISSUE TITLE
Non association of user with a device

### ISSUE THREAD

**Issue by gerrynicol** [MicrosoftDocs/windows-itpro-docs#4366]
Can you please provide more detailed informnation around this statement

As a result, some Azure AD and Intune capabilities (such as BitLocker recovery, installation of apps from the Company Portal, or Conditional Access) may not be available to a user that signs into the device.

Does this mean you cannot set up Bitlocker in self-deploying mode?
Also will no conditional policies work at all?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6867cc8c-868d-d472-8aa5-1ed5b94ced2c
* Version Independent ID: 6822e12d-7474-9e49-1e8b-88f7eec3b22c
* Content: [Windows Autopilot Self-Deploying mode](https://docs.microsoft.com/en-gb/windows/deployment/windows-autopilot/self-deploying#feedback)
* Content Source: [windows/deployment/windows-autopilot/self-deploying.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/self-deploying.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@gerrynicol - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by Reeced40** [comment]
@gerrynicol Thank you for your feedback, I will investigate further.

**Comment by Reeced40** [comment]
@gerrynicol Please have a look at this article and let me know if this information helps. https://docs.microsoft.com/windows/deployment/windows-autopilot/self-deploying

**Comment by gerrynicol** [comment]
@Reeced40. This is the document I want more information on. Its not clear what the impacts of conditional access, Bitlocker and Device compliance when using self-deploying mode.

**Comment by Reeced40** [comment]
@gerrynicol Apologies I pasted the correct link.  Please see correct one here - https://docs.microsoft.com/windows/configuration/kiosk-single-app#set-up-a-kiosk-or-digital-sign-in-intune-or-other-mdm-service

**Comment by mypil** [comment]
@gerrynicol - From our understanding, the issue has been answered by Reeced40. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by gerrynicol** [comment]
Apologies, I was on annual Leave. Can this be re-opened please. I'm still not clear on this. It doesn't indicate on the documents whether or not Bitlocker is supported when using Autopilot in Self-deploying mode. I understand that the device is not associated with a user, but does this translate to mean that you cannot use Bitlocker to encrypt local drives?

**Comment by mypil** [comment]
@officedocsbot reopen

**Comment by mypil** [comment]
@Reeced40 - Please assist with the additional question from @gerrynicol. Thank you.

**Comment by Reeced40** [comment]
@gerrynicol With Windows Autopilot, you can configure the BitLocker encryption settings to be applied before automatic encryption is started. I found 2 recently updated articles that will help clarify your question. I'll have them added to the article. https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-scenarios & https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/bitlocker

**Comment by mypil** [comment]
@gerrynicol - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by nhogarth86** [comment]
If you use self-deploying mode with BitLocker, you can still get the recovery key from Intune > Devices > select the device > Recovery keys. Regarding Conditional Access, I think it means that Conditional Access isn't supported if you configure the device to auto login with a local user account or guest account, because the user needs to have an appropriate license. The documentation doesn't explain it very well.
