### ISSUE TITLE
Registry Keys are Missing Data, with No Explanation as to Why

### ISSUE THREAD

**Issue by MikhailCompo** [MicrosoftDocs/windows-itpro-docs#4367]
The instructions above state "Use this list of Windows 10, version 1709 registry keys as your starting point". However, the following apps are missing from "Registry keys for provisioned apps" listed above:

Microsoft.3DBuilder
Microsoft.HEVCVideoExtension
Microsoft.Messaging

So if the *starting list* you have documented does not include 3DBuilder, HEVCVideoExtension or Messaging, does this mean they cannot be removed, you recommend they are not removed, the registry keys do not work for those apps, or what??

Or is it just that the "Registry keys for provisioned apps" is not accurate?

There is a mistake somewhere......

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9c3129d-3c8d-b508-f298-3333499bb180
* Version Independent ID: 97b70720-82d8-60a4-3958-00ceed34aa1b
* Content: [How to keep apps removed from Windows 10 from returning during an update](https://docs.microsoft.com/en-us/windows/application-management/remove-provisioned-apps-during-update#registry-keys-for-provisioned-apps)
* Content Source: [windows/application-management/remove-provisioned-apps-during-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/remove-provisioned-apps-during-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@MikhailCompo - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by RAJU2529** [comment]
@MikhailCompo .I am adding 3 new registry keys via creating PR .

**Comment by Reeced40** [comment]
@MikhailCompo Done. Thank you

**Comment by mypil** [comment]
@MikhailCompo - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
