### ISSUE TITLE
Intune OMA-URI Setting not working on Win10 1903?

### ISSUE THREAD

**Issue by Apemantus** [MicrosoftDocs/windows-itpro-docs#4368]
I have a custom OMA-URI profile with this as one of many settings, set to ‘enabled’. The profile works fine on 1809 test VMs but not on 1903. ‘Remediation failed’ 0x87d1fde8. I have replicated this on 2 separate tenants & clients. The setting does indeed fail & the registry entry is not created. (It is on 1809 VMs). HKLM\SOFTWARE\Policies\Microsoft\Windows\Powershell\ScriptBlockLogging - The PowerShell key is not there on 1903. If you manually set it using gpedit.msc - it IS there. What have I missed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c416bc4c-5c04-50ec-ae04-c9c9b3e9d1bc
* Version Independent ID: 282621e2-2586-e9a0-c9db-9f67bbd06051
* Content: [Policy CSP - WindowsPowerShell](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-windowspowershell#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-windowspowershell.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-windowspowershell.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Apemantus - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by NigelClarkExient** [comment]
I'm seeing this same issue on 1903. IT would be good to have the resolution posted here to save others time escalating through support.
