### ISSUE TITLE
Editing the Default Domain Policy

### ISSUE THREAD

**Issue by Mrkuff** [MicrosoftDocs/windows-itpro-docs#4370]
In step one : Define your network it's written: 

To configure a GPO that defines your intranet address space

    Open the Group Policy Management snap-in (gpmc.msc) and edit the Default Domain Policy.

Best practice is to NEVER edit the default Domain Policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2309112b-8c2d-02fb-d797-d28c87ca0b63
* Version Independent ID: 575ae0dd-122a-fdf8-0157-9d3180589751
* Content: [Isolating Microsoft Store Apps on Your Network (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/isolating-apps-on-your-network#feedback)
* Content Source: [windows/security/threat-protection/windows-firewall/isolating-apps-on-your-network.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-firewall/isolating-apps-on-your-network.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Mrkuff - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.
