### ISSUE TITLE
Mpcmdrun -validatemapsconnection

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#4371]
The article states the following:

> This command will only work on Windows 10, version 1703 or higher.

however today i was able to successfully run the command on Windows 10 1607 LTSB, can you please clarify?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86b0db3-f979-bd1f-78a4-41247510721a
* Version Independent ID: 5289bb5f-f015-7f38-05a1-26a615ae07aa
* Content: [Configure and validate Windows Defender Antivirus network connections](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@alexverboon. Because you used  1607 LTSB and might gives supported Windows defender advanced features.I  am happy to hear that particular command is also worked in earlier version.
Will you upload the proof run commands.
so that I can create new request to add window's 1607 LTSB.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@alexverboon - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by alexverboon** [comment]
I will send the proofing results later tomorrow

**Comment by ojrb** [comment]
@mypil this issue is solved by the PR #4429 please review and merge !

**Comment by mypil** [comment]
@alexverboon - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
