### ISSUE TITLE
Update information on required URLS

### ISSUE THREAD

**Issue by phillym** [MicrosoftDocs/windows-itpro-docs#4372]
Hi

The documentation here is slightly misleading. MDATP for Mac requires access to sub-domains of x.cp.wd.microsoft.com (for example unitedstates.x.cp.wd.microsoft.com) and different FQDNs for CDN (for example) eu-cdn.x.cp.wd.microsoft.com. These domains and sub-domains must have proxy auth disabled and TLS interception disabled. 

You can document this in the following two ways. Explicitly state the required FQDNs e.g:
unitedstates.x.cp.wd.microsoft.com
europe.x.cp.wd.microsoft.com (if indeed this is a valid MDATP for Mac endpoint)
us-cdn.x.cp.wd.microsoft.com (if indeed this is a valid MDATP for Mac endpoint)
eu-cdn.x.cp.wd.microsoft.com
etc
Or you can advise wildcard in proxy bypass:
*.x.cp.wd.microsoft.com

Either way, adding only the FQDNs advised in this document is not sufficient to allow bypassing proxy auth and TLS intercept and will result in broken connectivity to MDATP for Mac clients.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7a3b63b-afc5-1b25-3a30-e75c788f4a93
* Version Independent ID: 85498c85-fe13-fead-3bac-44db5614db0d
* Content: [Microsoft Defender ATP for Mac](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@phillym - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by phillym** [comment]
You're welcome Joyce. The Microsoft online documentation is so good these
days it's a pleasure to provide any input I can to help make it even better.

Keep up the good work!

Phil

**Comment by Dansimp** [comment]
This is fixed: https://github.com/MicrosoftDocs/windows-docs-pr/pull/663#pullrequestreview-260246077
