### ISSUE TITLE
EnableAppInstallControl can be bypassed by going offline if SmartScreen isn't also enabled

### ISSUE THREAD

**Issue by read-0nly** [MicrosoftDocs/windows-itpro-docs#4373]
The setting "SmartScreen/EnableAppInstallControl" blocks installing user-context apps when the device is online, as expected, however if the installer is downloaded then the device is taken offline, the user can proceed with the installation. This seems to come from a dependence on SmartScreen that isn't clearly documented either here

If we pull up the GPO info for the underlying setting, we get this from getadmx: https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.SmartScreen::ConfigureAppInstallControl 
As defined, "SmartScreen must be enabled for this feature to work properly."
Testing suggests App Install Control behaves as expected online, but defers to SmartScreen when offline. SmartScreen should warn/block offline execution because it can't verify the hash. If SmartScreen isn't enabled, execution simply continues unhindered, instead of failing.

The CSP-flavored fix then, to make sure the policy behaves as defined and blocks any install that doesn't come from the store even when the device is offline, is to also enable set the following CSP:
SmartScreen/EnableSmartScreenInShell =  1
SmartScreen/PreventOverrideForFilesInShell = 1

Otherwise, this setting can be bypassed by downloading the installer, going offline, and running the installer.

Please update the documentation to reflect this requirement. This was also reported here two months ago: https://github.com/MicrosoftDocs/IntuneDocs/issues/2379

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6af7069-ddf7-3f4e-f9fa-75139c92fd0a
* Version Independent ID: c07db982-c7d2-82bd-560b-9d13b4eca026
* Content: [Policy CSP - SmartScreen](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-smartscreen#smartscreen-enableappinstallcontrol)
* Content Source: [windows/client-management/mdm/policy-csp-smartscreen.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-smartscreen.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@read-0nly - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@read-0nly - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by read-0nly** [comment]
Many thanks, I'm glad this could finally be noted somewhere.

**Comment by mypil** [comment]
@officedocsbot close
