### ISSUE TITLE
Firewall Rules

### ISSUE THREAD

**Issue by bvorland** [MicrosoftDocs/windows-itpro-docs#4375]
The rules option shown in the picture is still not available in the portal and not working when assigning manual OMA-URI values, any plans to make this available soon?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b84a77a5-54c7-22c7-b699-c1414c7cd6a1
* Version Independent ID: f78d7bc3-97c8-d8e9-d4f7-5ea82680c738
* Content: [Create Windows Firewall rules in Intune (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/create-windows-firewall-rules-in-intune#feedback)
* Content Source: [windows/security/threat-protection/windows-firewall/create-windows-firewall-rules-in-intune.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-firewall/create-windows-firewall-rules-in-intune.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@bvorland - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via [Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
