### ISSUE TITLE
Ambiguous -u

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#4379]
The -u in the first example of a path based rule is ambiguous. Does it refer to -UserPE or to -UserWriteablePaths referred to below.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d4ecadb-c54e-5da1-03ae-1301a35ef64a
* Version Independent ID: 69d28732-f557-9ae1-cec4-594a2ec097a2
* Content: [Select the types of rules to create  (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create#create-path-based-rules)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Air-Git - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by greg-lindsay** [comment]
In this context, -u means -UserPE. If it meant -UserWriteablePaths then it would have to appear where -ScanPath appears (shortened to just -s here). I agree that the full parameter name should be used to avoid confusion.  This is not my topic, I just thought I would comment.

**Comment by illfated** [comment]
Thank you for the insight and feedback. I presume this will be useful feedback for the document owner (Daniel Simpson) or any of the other tech writers (Liza Poggemeyer, Andrea Bichsel, Justin Hall), in case they got time to look into this and choose what needs to be done to make the documentation less ambiguous.

**Comment by mypil** [comment]
@Air-Git - From our understanding, the issue has been resolved based on the merged commit [d978da4](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/d978da490dc14ba2022c9736d4acdf3fc57a9262) but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
