### ISSUE TITLE
Ping URL is Malformed

### ISSUE THREAD

**Issue by LanceMcCarthy** [MicrosoftDocs/windows-itpro-docs#4381]
In the sentence describing the required URLs, the ping hyperlink's URL is malformed.

It is currently:

`https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/%5Bhttps://cdn.x.cp.wd.microsoft.com/ping`

When it should be 

`https://cdn.x.cp.wd.microsoft.com/ping`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7a3b63b-afc5-1b25-3a30-e75c788f4a93
* Version Independent ID: 85498c85-fe13-fead-3bac-44db5614db0d
* Content: [Microsoft Defender ATP for Mac](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@LanceMcCarthy - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@LanceMcCarthy - PR #4403 has been created to fix and close this issue once the PR is merged.

Thank you for your contribution to make the docs better! Much appreciated!
