### ISSUE TITLE
Assigned Access lockdown

### ISSUE THREAD

**Issue by bmho1** [MicrosoftDocs/windows-itpro-docs#4385]
Added some clarification...
When using Assigned Access.. we have been successful using AssignedAccessConfiguration/Configs/Config/Account to Lockdown a device to a local machine user profile.  However, doing so also locks down the device for all other "normal" users (regardless if they are defined in the Config/Account configuration).  Therefore, our normal domain users cannot access any applications when they logon the machine if AssignedAccess has been applied.  Is there a way to bypass the lockdown for a group of users not defined in the AssignedAccessConfiguration/Configs/Config/Account section?  We do not want to apply a separate profile for normal domain users and we cannot add all of our domain users to the machine Administrators group to bypass the Lockdown.  Our use case involves having normal domain users share a tablet device with 3rd Party Users who will be logging in with the lockdown profile.

  <Configs>
      <Config>
          <Account>.\MachineAccount</Account>
          <DefaultProfile Id="{AFF9DA33-AE89-4039-B646-3A5706E92921}"/>
      </Config>
  </Configs>

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@bmho1 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by bmho1** [comment]
Hi Joyce,

I added some clarification on the post...  Also the articles referenced are below..
When using Assigned Access.. we have been successful using AssignedAccessConfiguration/Configs/Config/Account to Lockdown a device to a local machine user profile. However, doing so also locks down the device for all other "normal" users (regardless if they are defined in the Config/Account configuration). Therefore, our normal domain users cannot access any applications when they logon the machine if AssignedAccess has been applied. Is there a way to bypass the lockdown for a group of users not defined in the AssignedAccessConfiguration/Configs/Config/Account section? We do not want to apply a separate profile for normal domain users and we cannot add all of our domain users to the machine Administrators group to bypass the Lockdown. Our use case involves having normal domain users share a tablet device with 3rd Party Users who will be logging in with the lockdown profile.

Articles referenced:
https://docs.microsoft.com/en-us/windows/client-management/mdm/assignedaccess-csp
https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps
https://docs.microsoft.com/en-us/windows/configuration/kiosk-prepare

Thanks,
Brian

**Comment by joinimran** [comment]
Hi @bmho1 , Thank you for sharing the details and your query. I would recommend you to forward your case to the Microsoft support team to help you in the configuration of Access Lockdown based on your use case. 

@mypil Please guide user how a support case can be open.

Imran.

**Comment by mypil** [comment]
@bmho1 - You can open a service ticket so this can get resolved ASAP. Based on outcome let us know if it is something that can be called out in the documentation.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you do find that it is a documentation error,  please do not hesitate to comment back and we'll gladly look into fixing it. Thank you!

**Comment by mypil** [comment]
@officedocsbot close
