### ISSUE TITLE
Некоторые английские слова лучше не переводить

### ISSUE THREAD

**Issue by kartavenko** [MicrosoftDocs/windows-itpro-docs#4393]
Ниже приведены сочетания клавиш для%Аллусерспрофиле%\микрософт\виндовс\старт Мену\програмс,%Аппдата%\микрософт\виндовс\старт Menu\Programs и%APPDATA%\Microsoft\Windows\Start Menu\Programs\System Tools.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 79fccecd-5484-0304-d82b-9425f1889a22
* Version Independent ID: 4df6b138-c1b5-b551-22c9-19d3d1f9105d
* Content: [Настройка и экспорт макета начального экрана (Windows10)](https://docs.microsoft.com/ru-ru/windows/configuration/customize-and-export-start-layout#feedback)
* Content Source: [windows/configuration/customize-and-export-start-layout.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/customize-and-export-start-layout.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Using online translation tool:

**Title:** Some English words are better not to translate
**Issue Description:** Below are the shortcuts for %ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs, %APPDATA%\Microsoft\Windows\Start Menu\Programs, and %APPDATA%\Microsoft\Windows\Start Menu\Programs\System Tools.

Thank you for your feedback @kartavenko. I don't have a Russian version of Windows 10, but are the paths indicated in this documentation not the localized equivalent in Windows 10 RU? If so, your suggestion is not to auto-translate the paths/shortcuts, right? 

Hi @dongmicro is there a way to exclude specific shortcuts or file paths from the translation? If not, kindly look into this feedback. Thank you.

**Refer:**

English:
![image](https://user-images.githubusercontent.com/18371314/61170394-81b0e800-a51d-11e9-9f15-844b0f112266.png)

Russian:

![image](https://user-images.githubusercontent.com/18371314/61170405-8e354080-a51d-11e9-9f40-0bf270099dfd.png)

**Comment by jvsam** [comment]
@officedocsbot assign @dongmicro

**Comment by jvsam** [comment]
@officedocsbot assign @TinaMcN

**Comment by jvsam** [comment]
Hi @TinaMcN assigning this to you. Thank you.

**Comment by jvsam** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
@kartavenko Спасибо за обратную связь.  Статья была переведена машиной.  Я послала его для человеческого перевода.  Это может занять несколько недель. (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  This may take a few weeks to complete.)

**Comment by TinaMcN** [comment]
@kartavenko Статья теперь переведена человеком.  Пожалуйста, проверьте, исправлена ли проблема сейчас. (The article is now translated by a human.  Please verify if the issue is fixed now.)

**Comment by illfated** [comment]
Looks good to me.

> [!Note] Примечание
> 
> На всех клиентах, к которым применяется макет начального экрана, должны быть установлены приложения и другие ярлыки в локальной системе в том же месте, что и в исходной системе для макета начального экрана.
>
> Для правильной работы сценариев и закреплений плиток приложений следуйте этим правилам:
>
> - Исполняемые файлы и сценарии должны быть указаны в \Program Files или в любом другом месте, куда их помещает установщик приложения.
>
> - Ярлыки, которые будут закреплены на начальном экране, должны размещаться в **\ProgramData\Microsoft\Windows\Start Menu\Programs**.
>
> - Если вы размещаете исполняемые файлы или сценарии в папке **\ProgramData\Microsoft\Windows\Start Menu\Programs**, они не будут закреплены на начальном экране.
>
> - Начальный экран в Windows 10 не поддерживает вложенные папки. Поддерживается только одна папка. Например, **\ProgramData\Microsoft\Windows\Start Menu\Programs\Folder**. Если используется глубина более одной папки, в меню "Пуск" будет выполнено сжатие содержимого всех вложенных папок до верхнего уровня.
>
> - Три дополнительных ярлыка закреплены в меню "Пуск" после экспорта. Это ярлыки для **%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs**, **%APPDATA%\Microsoft\Windows\Start Menu\Programs** и **%APPDATA%\Microsoft\Windows\Start Menu\Programs\System Tools**.

**Comment by jvsam** [comment]
@kartavenko, thank you again for your feedback. We will now close this issue since it has been resolved and the documentation has been updated. Please continue to send your feedback and suggestions to improve the quality of the Microsoft documentation. Thanks for being part of the Microsoft Docs community!

Thank you so much for your assistance @TinaMcN.

**Comment by jvsam** [comment]
@officedocsbot close
