### ISSUE TITLE
Max concurrent users

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/windows-itpro-docs#4394]
I can't find anywhere what the maximum number of users that can draw on a whiteboard simultaneously, either on the hub or from the apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe78cdc5-d977-774d-3027-12a692212a55
* Version Independent ID: 8632de82-338f-aab7-cdf8-263726e83aea
* Content: [Set up and use Microsoft Whiteboard](https://docs.microsoft.com/en-us/surface-hub/whiteboard-collaboration#feedback)
* Content Source: [devices/surface-hub/whiteboard-collaboration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/whiteboard-collaboration.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @thommck I understand that there is no indicated maximum number of concurrent users for the Microsoft Whiteboard 2016 collaborative session in this documentation, however, this [community Q & A](https://techcommunity.microsoft.com/t5/Surface-Hub/How-many-concurrent-sessions-are-allowed-for-whiteboarding/td-p/143757) might help. One user indicated that it worked with 24 people in one session. 

Hi @levinec do you have any information on the maximum users allowed for collaborative session so we can create a pull request so it can be added to this documentation? Thank you in advance for your assistance.

**Comment by levinec** [comment]
Hi Jo,

I have no idea as to the maximum number. That would be a question for the engineering team, but I don't know who they are. I was just assigned the Surface Hub topics but have no real knowledge of them.

Best,
Beth

**Comment by jvsam** [comment]
We appreciate your input @levinec, thank you.

Hi @thommck, unfortunately at the moment, we do not have the information. I have tried looking for public references, but there is none so far except for community discussions (*and no concrete information related to max limit*). What I would suggest is to utilize the Tech Community or to contact  [support](https://support.microsoft.com/hub/4295210/surface-pro-help). In case you get a confirmation from an expert or someone from Microsoft, kindly let us know here so we can request for it to be incorporated in the docs. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
