### ISSUE TITLE
Remove Terminal Prompt Text

### ISSUE THREAD

**Issue by Chad-Campus** [MicrosoftDocs/windows-itpro-docs#4396]
Can you remove the terminal (BASH) prompt text from your commands.  When you click copy and then paste into Terminal (BASH) the commands do not work because of the "mavel-mojave:~ testuser$" text in them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff5d81fd-4b34-c63b-a4ec-40d2f0a1f350
* Version Independent ID: 7c68d6c4-7d4b-73d0-126c-b3c2bebebfbe
* Content: [Installing Microsoft Defender ATP for Mac manually](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac-install-manually#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac-install-manually.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac-install-manually.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @Chad-Campus this documentation has been updated by @martyav as per your feedback. You can verify the changes at this URL: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac-install-manually.

Thanks for being part of the Microsoft Docs Community and for helping improve the quality of the technical documentation!
