### ISSUE TITLE
Remove Terminal Prompt Text

### ISSUE THREAD

**Issue by Chad-Campus** [MicrosoftDocs/windows-itpro-docs#4397]
Remove "mavel-mojave:wdavconfig testuser$" from the commands

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07f72a75-ca85-0651-1512-8ffb62d0ab7b
* Version Independent ID: 6e15dd30-1db2-4a18-a18c-c343e1d508cd
* Content: [Microsoft Defender ATP for Mac Resources](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac-resources#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
**NOTE**: Duplicate of #4396. See related commits: [50f7d39](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/50f7d394eda4200e83cc64fa9614f05027907045) and [568900c](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/568900cedfa24fe1d2e82190feb9786fac5d375f).
