### ISSUE TITLE
Mixed up wording

### ISSUE THREAD

**Issue by CodyBatt** [MicrosoftDocs/windows-itpro-docs#4398]
In section 18.11:

> In the Email area, you can choose which apps have **can** access and send email.

In the Email area, you can choose which apps have access and **can** send email.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
@CodyBatt : Thank you for pointing out the wording or syntax error there
(and also for the chuckle I got from trying to make sense of the wrong wording).

**Comment by CodyBatt** [comment]
@illfated it kind of sounded like a lolcat wrote it!

**Comment by jvsam** [comment]
Hi @CodyBatt this documentation has been updated by @martyav as per your feedback. You can verify the changes at this URL: https://docs.microsoft.com/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.

Thanks for being part of the Microsoft Docs Community and for helping improve the quality of the technical documentation!
