### ISSUE TITLE
Autoenrollment bitlocker with GPO

### ISSUE THREAD

**Issue by AlekseySokol** [MicrosoftDocs/windows-itpro-docs#4399]
Hello!
Do I'm able to initiate a Bitlocker encryption process with GPO?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5476099c-9d70-97df-8ee6-bc442605cfbd
* Version Independent ID: 49ca0628-bd88-e05b-b705-3b361b57512d
* Content: [BitLocker Group Policy settings (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-group-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by artimob** [comment]
No from what I know, you can only define BitLocker policy via GPO, but encryption has to occur during OS build process (SCCM, MDT) or via script for existing OS.

**Comment by RAJU2529** [comment]
@AlekseySokol .    I think its possible, visit below site.

https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-deployment-and-administration-faq

**Comment by jvsam** [comment]
Hi @AlekseySokol as stated in this doc, *Group Policy setting is used to manage BitLocker Drive Encryption*. And you can use [BitLocker Drive Encryption Tools](https://docs.microsoft.com/windows/security/information-protection/bitlocker/bitlocker-use-bitlocker-drive-encryption-tools-to-manage-bitlocker) to manage/configure BitLocker, e.g. using Manage-bde to fully encrypt a volume or by using Windows PowerShell's scripting. I am not sure if this (*along with the community suggestions/comments*) fully answered your question, if not, can you please clarify and provide more information? You can also check some posts/conversations and blogs at the [Microsoft Security community](https://techcommunity.microsoft.com/t5/Enterprise-Mobility-Security/ct-p/EMS).

Also, this Github site is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. If you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review. Thank you.

**Comment by jvsam** [comment]
Hi again @alekseys we haven't heard or received any updates from you. We are hoping the suggestions we've shared can help you find the information you need. For now, we will close this issue, however, feel free to re-open if there is missing information or if you have suggestions to improve the quality of this documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot assign
