### ISSUE TITLE
Dir Sync - device

### ISSUE THREAD

**Issue by nickekallen** [MicrosoftDocs/windows-itpro-docs#4401]
Under the dir sync section it states that users should be synchronized. In addition it is required that devices that are to be setup with WBfH are synchronized aswell. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02eda72c-ccd2-e8d8-4f7e-6edf95b79408
* Version Independent ID: be08aee5-2403-c131-0f39-005e1271d5f1
* Content: [Hybrid Windows Hello for Business Prerequisites (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @nickekallen can you please clarify what assistance you need? Are you pertaining to this part of the documentation?

> The two directories used in hybrid deployments must be synchronized. You need Azure Active Directory Connect to synchronize user accounts in the on-premises Active Directory with Azure Active Directory.

Is it inaccurate? The more information you can provide, the better. If this is a feedback regarding this documentation, it will help if we will know what specific improvements you are suggesting. Our goal here is to ensure the contents of the Microsoft Docs are useful, accurate and up-to-date though user feedback and contributions. 

Thanks for understanding and we look forward to hearing from you.

**Comment by nickekallen** [comment]
Yeah, it says that user accounts needs to be synchronized - however the devices are required aswell. If the OU structure of devices in AD is not sync to AAD WHfB will not allow a user to enroll a specific device.

**Comment by jvsam** [comment]
Thank you so much for the additional information @nickekallen, so basically you are suggesting amendments to this documentation to emphasize that devices need to be synced as well. But the information is already available in this doc under Device Registration:

> Hybrid certificate trust deployments need the device write back feature. Authentication to the Windows Server 2016 Active Directory Federation Services needs both the user and the computer to authenticate. Typically the users are synchronized, but not devices. This prevents AD FS from authenticating the computer and results in Windows Hello for Business certificate enrollment failures. **For this reason, Windows Hello for Business deployments need device writeback, which is an Azure Active Directory premium feature.**

Or are you suggesting to add similar messaging under the *Directory Synchronization* section? To ensure the Device writeback is enabled to synchronize devices to Active Directory?

Thank you again.

**Comment by nickekallen** [comment]
Yes, exactly

**Comment by jvsam** [comment]
Got it! We appreciate the clarification @nickekallen and thanks for the prompt response.

I will forward this to the Windows content writing team for review. Please continue to share your suggestions or ideas to help improve the quality of the technical documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hi again @nickekallen, we'd like to inform you that the suggested update to this documentation to emphasize users and devices synchronization (See pull request #4535) has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
