### ISSUE TITLE
Clarification Needed

### ISSUE THREAD

**Issue by frasercarter** [MicrosoftDocs/windows-itpro-docs#4402]
1. Enterprise has MDM service already configured -&gt; What does this mean? perhaps link to page on configuring Intune for Azure at a bare minimum, 3rd party mdm does not need to be linked (but would be good)
2. Enterprise AD must be registered with Azure AD -&gt; This is vague, what is the definition of registration between Azure AD and Enterprise AD, link to document involving steps for connection/registration so they understand this statement better.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @frasercarter thank you for your suggestions to help improve the quality of the technical documentation  of Microsoft Docs. We always strive to give users the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, accurate and up-to-date.  

Hi @ManikaDhiman hoping you can help us. Will you be able to make the updates or do you want us to create the pull request instead with suggestions to add link references? Also, is this a correct reference?

https://docs.microsoft.com/en-us/intune/windows-enrollment-methods

Thank you in advance.

**Comment by jvsam** [comment]
Hi again @frasercarter, what about the [Azure Active Directory integration with MDM](https://docs.microsoft.com/windows/client-management/mdm/azure-active-directory-integration-with-mdm) link in the doc? Does it not address the issues you've raised. It is also under the MDM topic with a lot of useful sub-topics in the TOC.

> 1. Enterprise has MDM service already configured -> What does this mean? perhaps link to page on configuring Intune for Azure at a bare minimum, 3rd party mdm does not need to be linked (but would be good)
> 2. Enterprise AD must be registered with Azure AD -> This is vague, what is the definition of registration between Azure AD and Enterprise AD, link to document involving steps for connection/registration so they understand this statement better.

Same goes for this URL https://docs.microsoft.com/en-us/azure/active-directory/devices/hybrid-azuread-join-plan for registering devices for Azure AD.

Hi again @ManikaDhiman how are you? If you are not busy, are there any other useful links that can be added in this doc? Or perhaps expand the explanation of the requirements? Thank you, as always.

**Comment by ManikaDhiman** [comment]
Hi @jvsam, This doc is now expanded to include additional reference links as you suggested and the following two new topics:
Verify auto-enrollment requirements and settings, Troubleshoot auto-enrollment of devices.
Hope these changes will bring more clarity to the content. Thanks!

**Comment by jvsam** [comment]
That's great @ManikaDhiman. Just reviewed the updates, kudos! We really appreciate your help on this. 

Hi again @frasercarter, this documentation has been updated by Manika as per your feedback. You can verify the changes at this URL: https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.

We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation. Thanks for being part of the Microsoft Docs Community!

**Comment by jvsam** [comment]
@officedocsbot close
