### ISSUE TITLE
Remove FAQ content and merge with existing dedicated WDAG FAQ page

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#4409]
The main WDAG page has a FAQ and the bottom. There is also a separate FAQ page at https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard Please consider moving the FAQ content from the main page to the dedicated, existing FAQ page. Please consolidate the FAQ content as well as there is some duplicate and some unique content between the two. Leaving these two different FAQs existing with slightly different content is confusing. Retaining a link on this page to the "new" consolidated, separate FAQ could also be beneficial but not required since there's a link in the left hand navigation already.

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfb9445a-681d-24b6-5241-4ebe311f5236
* Version Independent ID: aea60f74-212c-e24e-f164-28a555bc1727
* Content: [Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@iadgovuser1 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
This will be resolved by PR #4470

**Comment by iadgovuser1** [comment]
Thanks!
