### ISSUE TITLE
Remove system requirements content and merge with existing dedicated WDAG requirements page

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#4410]
This page has requirements under the **Review system requirements** section and there is also a separate [requirements page](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard). Move this content to the existing, dedicated requirements page and consolidate the content. They appear to be identical so are likely duplicate. The **Review system requirements**  heading could be retained and then there could be a link to the "new" consolidated, separate requirements page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb904674-d586-0a38-0e7c-7ac3e06cbcd9
* Version Independent ID: 549fbb52-6234-2a79-8604-85498e622f98
* Content: [Enable hardware-based isolation for Microsoft Edge (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/install-wd-app-guard)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/install-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/install-wd-app-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@iadgovuser1 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@iadgovuser1 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by iadgovuser1** [comment]
Looks good. Thanks!

**Comment by mypil** [comment]
@officedocsbot close
