### ISSUE TITLE
Translated commands

### ISSUE THREAD

**Issue by UspAN** [MicrosoftDocs/windows-itpro-docs#4413]
Commands are translated into russian

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: f8c6bee9-e792-395d-0b9c-b46b90e45843
* Version Independent ID: 72c4ca50-76ac-6663-3cf6-b5fac1b348ef
* Content: [Примеры команд Live Response](https://docs.microsoft.com/ru-ru/windows/security/threat-protection/microsoft-defender-atp/live-response-command-examples#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/live-response-command-examples.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/live-response-command-examples.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@UspAN - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@officedocsbot add label localization

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this translation/localization issue?

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @Mollymalone

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
@UspAN Спасибо за обратную связь. Статья была переведена машиной. Я послала его для человеческого перевода. Это может занять несколько недель. (Thank you for the feedback. The article was machine translated. I sent it for human translation. This may take a few weeks to complete.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on this?

Thank you.

cc: @kenwith

**Comment by TinaMcN** [comment]
Hmmm, this file does not seem to have been sent to the localization vendors as expected.  I retriggered a handoff and asked them to confirm when they receive it.

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on this?

Thank you.

**Comment by TinaMcN** [comment]
@mypil the article is now human translated and the commands are in English.  @UspAN пожалуйста, проверьте, исправлена ли проблема.

**Comment by mypil** [comment]
@UspAN - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
