### ISSUE TITLE
Avoid malware

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/windows-itpro-docs#4426]
Why no mention of not using old binary / 2003 file formats, use the new 2007 X-file formats.
No mention of not using RTF format

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c1cf16e-b893-5928-bab5-18dab0435316
* Version Independent ID: 25af1ac9-b386-1b11-4954-b246e4a20ef1
* Content: [Macro malware](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/macro-malware#feedback)
* Content Source: [windows/security/threat-protection/intelligence/macro-malware.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/intelligence/macro-malware.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **levinec**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi again @Ronsss since you have the same suggestion as #4425, perhaps the most fitting topic is [Prevent malware infection](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/prevent-malware-infection) since this documentation already contains malware protection tips, or do you have specific requests in mind related to this *Macro malware* documentation? Please let us know. Thank you.

**Comment by Ronsss** [comment]
The Macro Malware page is very brief, I was thinking some more information would help.  At the end you have
<snip>
For more general tips, see prevent malware infection<https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/prevent-malware-infection>.
</snip>
Since much macro malware is delivered as part of Phishing attempts, I was thinking if you added a link to the phishing page would help shorten the users search for specific information ie
<snip>
For more specific tips see https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/phishing
</snip>


On Sat, Jul 13, 2019 at 2:18 PM Jo <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi again @Ronsss<https://github.com/Ronsss> since you have the same suggestion as #4425<https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4425>, perhaps the most fitting topic is Prevent malware infection<https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/prevent-malware-infection> since this documentation already contains malware protection tips, or do you have specific requests in mind related to this Macro malware documentation? Please let us know. Thank you.

**Comment by jvsam** [comment]
> I was thinking if you added a link to the phishing page would help shorten the users search for specific information...

Great suggestion @Ronsss. There's already a suggested update to this documentation via Pull Request (PR) #4462 . PRs are normally reviewed/merged in the order of submission but once approved, they will be displayed here at docs.microsoft.com site in the next scheduled publishing run. 

Thanks for your feedback and for being part of the Microsoft Docs community!
