### ISSUE TITLE
More detail regarding the statement "Most licensing actions and events are recorded in the Event log."

### ISSUE THREAD

**Issue by philkloose** [MicrosoftDocs/windows-itpro-docs#4441]
It would be great to get some detail as to which event logs, event sources, and event IDs are relevant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bee31674-8d3f-2a11-03ad-a12be40332cc
* Version Independent ID: 855565bd-a278-6fd9-2138-ec836508e478
* Content: [Monitor activation (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/volume-activation/monitor-activation-client)
* Content Source: [windows/deployment/volume-activation/monitor-activation-client.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/volume-activation/monitor-activation-client.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@philkloose - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via [Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by philkloose** [comment]
I'm not asking for new features.  I'm pointing out the fact that the documentation detailing how one might monitor the activation of a new client would be much better if had actual details.  As it sits right now, we basically have a page stating that "logs are probably generated - go find them!"

**Comment by mypil** [comment]
@philkloose - Let me loop in the doc owner @greg-lindsay to get his inputs.

@greg-lindsay - Can you please share your insights on this issue?

Thank you.

**Comment by greg-lindsay** [comment]
You're right this is vague. After some searching myself I found this article which seems pretty helpful:
https://www.systemcenterdudes.com/windows-10-kms-activation-and-management-using-volume-activation-management-tool/

Look down about 4/5 of the way to the bottom and it discusses the Event Log, in particular the Application Logs and events number 12288, 12289, and I believe there is also a 12290 event.

Also see https://docs.microsoft.com/en-us/windows-server/get-started/activation-error-codes

I will go ahead and include this detail in the article. Thanks for pointing out the less than helpful statement.
