### ISSUE TITLE
USMT migrates hidden files when it should not

### ISSUE THREAD

**Issue by TheDragonBall0** [MicrosoftDocs/windows-itpro-docs#4446]
USMT migrates hidden files, even though Microsoft Docs clearly states that it does not.
Below is original quote from Microsoft Docs.
"The default MigDocs.xml file will not migrate the following:
Files tagged with both the hidden and system attributes."

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@TheDragonBall0 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by TheDragonBall0** [comment]
Sure. I was using the original MigApp.xml and MigDocs.xml without any modifications.

**Comment by mypil** [comment]
@TheDragonBall0 - We would like to follow up on this. Can you please provide the URL of the specific Microsoft document?

**Comment by mypil** [comment]
@TheDragonBall0 -  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to open a new issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
