### ISSUE TITLE
2016 LTSB will not do in-place upgrade to Enterprise, LTSC, Pro, ...

### ISSUE THREAD

**Issue by emt29165** [MicrosoftDocs/windows-itpro-docs#4467]
Is this information really correct? 
" Windows 10 Enterprise 2016 LTSB can be upgraded to Windows 10 Enterprise version 1607 or later. Upgrade is supported using the in-place upgrade process (using Windows setup)."
I have been trying to upgrade my LTSB laptops so they can run Adobe XD for days now and can only get the message "Upgrade path not available".
I think that I have tried every combination and permutation so there must be a factor that is critical that is left out of the documentation. Please provide complete information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08436cb0-d0b6-0961-9e57-291b24d73644
* Version Independent ID: 36264f52-d3ac-4e50-f8e8-b09d6b210490
* Content: [Windows 10 upgrade paths (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-upgrade-paths#feedback)
* Content Source: [windows/deployment/upgrade/windows-10-upgrade-paths.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/windows-10-upgrade-paths.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @emt29165 thank you for your question.

**Comment by jvsam** [comment]
Hi @emt29165 thank you for your question. I just want to mention that the *note* section includes this information:

> ...This was corrected in the Windows 10 LTSC 2016 release, *which will now only allow data-only and clean install options*.

In-place upgrade is possible **but** you will need do a clean reinstall or full OS deployment. Are you upgrading from Windows 10 Enterprise 2016 LTSB to [Windows 10 Enterprise 2019 LTSC](https://docs.microsoft.com/windows/whats-new/ltsc/whats-new-windows-10-2019)? These are also good references:

[Windows 10 Enterprise (2016 LTSB) - unable to update with build 1809](https://social.technet.microsoft.com/Forums/security/en-US/2d16b745-771a-4fc7-a409-4cfe3041edca/windows-10-enterprise-2016-ltsb-unable-to-update-with-build-1809?forum=win10itprogeneral)
[Windows 10 Enterprise LTSB 2016 upgrade to 1709](https://social.technet.microsoft.com/Forums/office/en-US/cf4ef85d-9320-45c0-bc7f-a34ac71a57f3/windows-10-enterprise-ltsb-2016-upgrade-to-1709?forum=win10itprosetup)

If my understanding is wrong, kindly clarify and provide more information. If it's correct but the documentation is still confusing for you, can you also let us know what information you want to add to this documentation so we can forward it for review? Thanks and looking forward to your feedback.

**Comment by emt29165** [comment]
Yes, we are updating from Windows 10 Enterprise 2016 LTSB (1607) to Windows 10 Enterprise 2019 LTSC (1809) using .iso file running inside of the existing windows installation. (all file are directly downloaded from MVLS). Both options for either Upgrade keeping apps and files and Full/Custom install are available. I did not try the custom install as we want only to upgrade the current install.

**Comment by jvsam** [comment]
Thanks for the additional information @emt29165. I believe in this case, the best course of action if you are still experiencing problems is to contact Windows Support. You can open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance. Again, if there are issues in this documentation, e.g. inaccurate information, etc., please let us know. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hi again @emt29165 I hope you were able to contact Windows support and resolved your concern. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation. Thank you again for your feedback.

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by cagnulein** [comment]
Let's have a look here http://robertoviola.cloud/2020/07/28/upgrading-windows-10-2016-ltsb-to-windows-10-2019-ltsc/
Long story short, you need the ISO of Windows LTSC and you need to run it over the 2016

**Comment by Tyler-H** [comment]
This is pretty bad; we had Enterprise 2016 LTSB machines forced to upgrade today and they went to 20H2 Pro. No upgrade from LTSB to LTSC?
