### ISSUE TITLE
MDT01 E: Drive

### ISSUE THREAD

**Issue by PrometheanHeir** [MicrosoftDocs/windows-itpro-docs#4469]
Where is the E: Drive referenced in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ab08370-69ab-d025-cea2-c41c3aa4b908
* Version Independent ID: 9f5603f8-10e6-2651-3120-6d5627217cc9
* Content: [Prepare for deployment with MDT (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt#feedback)
* Content Source: [windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you @PrometheanHeir. To fully assist you, can you please clarify or provide more information regarding your question? This is a test lab guide for deploying Windows 10 using MDT, if there are inconsistencies or missing information, please let us know. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation. Looking forward to hearing from you!

**Comment by illfated** [comment]
I seem to remember someone asking something similar in an earlier issue ticket, but I couldn't find it within a few minutes.
As a temporary solution, If I may draw your attention to the following sentence:
> These steps assume that you have the **MDT01 member server** installed and configured and that you have downloaded [Windows ADK for Windows 10](https://go.microsoft.com/fwlink/p/?LinkId=526803) to the E:\Downloads\ADK folder.

I am fairly certain that the E:\ drive is a network drive mounted from the member server **MDT01** on the Windows 10 computer **PC1** (or **PC0001** - depending on which manual page you are on).

A more direct link to the exact share folder setup and configuration in some other part of the Microsoft Deployment Toolkit would be quite helpful on this page.

**Comment by jvsam** [comment]
> I am fairly certain that the E:\ drive is a network drive mounted from the member server MDT01 on the Windows 10 computer PC1 (or PC0001 - depending on which manual page you are on).

Yes, external drive or maybe partition drive? @PrometheanHeir what do you think of @illfated's comment? Does it answer your question, if not, we appreciate if you can provide more information. 

> A more direct link to the exact share folder setup and configuration in some other part of the Microsoft Deployment Toolkit would be quite helpful on this page.

Did you find a reference doc with that information @illfated? So far I haven't seen one.

**Comment by illfated** [comment]
Sorry, I haven't had time to search more for that information than what I did that day. I thought I had seen something about it some months ago (earlier this year) somewhere else in the tutorial setup, but I have completely forgotten where it would be located. Then again, that could be a false memory, since I haven't actually used the tutorial pages to set up any lab from these pages, since I don't have a real Enterprise scenario available at work.

**Comment by jvsam** [comment]
That's fine, thank you @illfated.

We haven't heard from you @PrometheanHeir. We hope the information shared in this issue can help you. For now, we will close this issue, however, feel free to re-open if you believe your main concern is not yet addressed and if it relates to improving the quality or accuracy of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by illfated** [comment]
@PrometheanHeir : I know this might be a long shot, but if you have got time to go through the entire lab setup procedure, maybe you will find the reference to the E: drive and where it is located. I would have liked to do that myself, but I neither have the equipment required nor time to go through the setup myself, so I hope you or someone else may be able to do it and post feedback which may very well be useful to add to the documentation. Good luck with your endeavours and hope to hear from you again.

**Comment by PrometheanHeir** [comment]
Thank you, everyone. Your feedback has helped me with trying to understand the Microsoft documentation. I think that the important takeaway is that the E drive can refer to the location of the resources whether they are located locally on the machine or it is connected as a network resource or it could be connected by an external drive.
Again, thank you all for your help.
