### ISSUE TITLE
BuildMyPinnedSite is Unavailable

### ISSUE THREAD

**Issue by nathanmaslin** [MicrosoftDocs/windows-itpro-docs#4474]
Hi Team, 

When I click the link for the BuildMyPinnedSite (http://www.buildmypinnedsite.com/) I am getting the following error:

Error 403 - This web app is stopped.
The web app you have attempted to reach is currently stopped and does not accept any requests. Please try to reload the page or visit it again soon.

If you are the web app administrator, please find the common 403 error scenarios and resolution here. For further troubleshooting tools and recommendations, please visit Azure Portal.

Can someone fix/update please

Thanks

Nathan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50ad17a1-3dc3-9d2e-90ae-e6e3d054d4e5
* Version Independent ID: 89807489-f29f-7316-6a47-ee64330a4815
* Content: [Add image for secondary Microsoft Edge tiles (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/start-secondary-tiles#feedback)
* Content Source: [windows/configuration/start-secondary-tiles.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/start-secondary-tiles.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
> A quick method for getting appropriately sized images for each tile size is to upload your image at BuildMyPinnedSite and then download the resized tile images.

Hi @nathanmaslin thank you for bringing this to our attention. It *appears* that the service has already been discontinued and the site is no longer live. I will get this over to the Windows content writing team for investigation and if confirmed, to suggest the removal of the link to avoid confusion.

We really appreciate your feedback and thank you for being part of the Microsoft Docs Community and for helping improve the quality of the technical documentation!

**Comment by illfated** [comment]
I can only confirm that the page/site is not available and that I get the same error code (403). I don't know if it has been discontinued permanently and intentionally, so it would be good to get that part confirmed by MS internal techs.

**Comment by nenonix** [comment]
@illfated this [zdnet article](https://www.zdnet.com/article/microsoft-loses-control-over-windows-tiles-subdomain) gives some interesting context to what happened.

**Comment by illfated** [comment]
Wow. I was unaware of that fact and how much things can go south if online services get out of hand. Thank you for that information, appreciated.

**Comment by jvsam** [comment]
Hi again @nathanmaslin, thank you for your patience.  The removal of the dead link from this documentation, based on your feedback, has been approved and merged (see #4701). The update will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!
