### ISSUE TITLE
There's a typo in the workarounds command

### ISSUE THREAD

**Issue by toxicbubble** [MicrosoftDocs/windows-itpro-docs#4476]
The reagent dlls missing from winpe is ridiculous in itself, but you've also typoed both the copy commands for the workarounds. The commands should be:
ReAgent*
Not
ReAgnet*

Nets aren't Ents. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73c22f0-cb0d-e34b-29d8-06829b86784f
* Version Independent ID: 083115ed-f1be-e962-5b0e-5079dec37353
* Content: [MBR2GPT](https://docs.microsoft.com/en-us/windows/deployment/mbr-to-gpt#feedback)
* Content Source: [windows/deployment/mbr-to-gpt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/mbr-to-gpt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
Nice find, thank you for pointing them out for us.
I will make a quick Pull Request for the typo correction.

**Comment by jvsam** [comment]
Hi again @toxicbubble, we'd like to inform you that the changes (*typo errors fix*) are now displayed here at docs.microsoft.com. You can verify by visiting this URL: https://docs.microsoft.com/en-us/windows/deployment/mbr-to-gpt. Thank you for your feedback to help improve the contents of this documentation and for being part of the Microsoft Docs community!
