### ISSUE TITLE
Acronym for group manages service accounts is incorrect in a section of this document

### ISSUE THREAD

**Issue by admingst** [MicrosoftDocs/windows-itpro-docs#4486]
Should be GMSA, but displayed as GSMA here: GSMA uses the Microsoft Key Distribution Service that is located on Windows Server 2012 or later domain controllers. Windows uses the Microsoft Key Distribution Service to protect secrets stored and used by the GSMA. Before you can create a GSMA, you must first create a root key for the service. You can skip this if your environment already uses GSMA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b063e00b-84e5-9da7-2229-e0e24da3b877
* Version Independent ID: da9f4867-2aa3-aefa-1603-ddb2ab1ed624
* Content: [Prepare and Deploy Windows Server 2016 Active Directory Federation Services (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
Interesting typo, seeing that the acronym GMSA (for "Group Managed Service Accounts") is written correctly both before & after that paragraph.

**Comment by jvsam** [comment]
Hi @admingst we appreciate your feedback. The typo errors are fixed via this commit [f1a4df4](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/f1a4df41e95a578eddf5414ec3928ac1e910b525) added by @martyav. The changes will be displayed here at docs.microsoft.com in the next scheduled publishing run. 

Thanks for being part of the Microsoft Docs Community and for helping improve the quality of the technical documentation!
