### ISSUE TITLE
My PR was merged 2 days ago, yet the docs are still not updated

### ISSUE THREAD

**Issue by chandde** [MicrosoftDocs/windows-itpro-docs#4487]
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4445

How long it takes from merging the changes till user sees the updated content?

Thanks!

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
Please be patient. 2 days is not much waiting time
for your merged PR to migrate to
https://docs.microsoft.com/en-us/windows/client-management/mdm/assignedaccess-csp .

Just to give you an idea, I will mention that I have seen merged pull requests take up to a week
to migrate to the docs.microsoft.com site, which suggests that the wait time can be arbitrary.
Please also consider that vacation season could also play a role in the delay.
My recommendation is not to worry, unless you are part of a Microsoft team
needing the changes to be made public before you can post other changes.

As a rule of thumb, you don't need to make inquiries before a week has passed.

**Comment by jvsam** [comment]
Hi @chandde I can now see the updates displayed on the following content pages:

https://docs.microsoft.com/windows/client-management/mdm/assignedaccess-csp
https://docs.microsoft.com/windows/configuration/kiosk-xml
https://docs.microsoft.com/windows/configuration/lock-down-windows-10-to-specific-apps

We will now close this issue. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
