### ISSUE TITLE
Pre-req information for MDT integartion missing in Doc

### ISSUE THREAD

**Issue by SudheeshGH** [MicrosoftDocs/windows-itpro-docs#4497]
If we do MDT integrated with SCCM and try creating a bootable media it crashing with error Microsoft.BDD.ElevatedProxy.exe stopping. The reason for the same is powershell 2.0 engine missing from the server features. So we would need to add this as a part of the documentation.

Steps To add the Windows PowerShell 2.0 Engine feature
In Server Manager, from the Manage menu, select Add Roles and Features.
Or Server Manager, click All Servers, right-click a server name, and then select Add Roles and Features.
On the Installation Type page, select Role-based or feature-based installation.
On the Features page, expand the Windows PowerShell (Installed) node and select Windows PowerShell 2.0 Engine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d8f960c-f554-3a48-1ebe-527638ba5c10
* Version Independent ID: 5b523d29-6b9c-abb5-344d-93f39bd08426
* Content: [Integrate Configuration Manager with MDT (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/integrate-configuration-manager-with-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/integrate-configuration-manager-with-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/integrate-configuration-manager-with-mdt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@SudheeshGH  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@SudheeshGH - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. Furthermore, please take note that this entire doc set is being rewritten and should be published with new information this month as indicated [here](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4521#issuecomment-517813683).  If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
