### ISSUE TITLE
Enabled_Version1000 doesn't exists anymore

### ISSUE THREAD

**Issue by Dan-Fink** [MicrosoftDocs/windows-itpro-docs#4499]
Hi,
the Detection Method of this Example Application and which is called inside the documentation on Lines 352-363 doesn't exist anymore could you please update this article for other admins. The new Surface Deployment Powershell Scripts are updated with other RegistryKeys.
Thx and Regards,
Daniel

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c7ac548b-be6c-efba-76ee-67dd7af18891
* Version Independent ID: 947b62e7-1225-2f5e-14ba-fe5dccbbe124
* Content: [Use System Center Configuration Manager to manage devices with SEMM (Surface)](https://docs.microsoft.com/de-de/surface/use-system-center-configuration-manager-to-manage-devices-with-semm#feedback)
* Content Source: [devices/surface/use-system-center-configuration-manager-to-manage-devices-with-semm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/use-system-center-configuration-manager-to-manage-devices-with-semm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Dan-Fink - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Dan-Fink - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by aurelgodin** [comment]
Hello,
I have the same problem, this has not been corrected

**Comment by beeeeswax** [comment]
Indeed, I've just gone through my first attempt at getting SEMM to work in an SCCM Task Sequence and followed this guide.  It still references the registry key **Enabled_Version1000** which the script does not actually create.
