### ISSUE TITLE
Open Value Agreement

### ISSUE THREAD

**Issue by eduardok** [MicrosoftDocs/windows-itpro-docs#4500]
To activate the Windows 10 Subscription my reseller is saying the Open Value is not included in the $0 SKU trick. When you say Enterprise Agreement, is Open Value included? We have Open Value with Software Assurance. Should they be able to place the $0 SKU order?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation#feedback)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@eduardok - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by eduardok** [comment]
I was told by my reseller that the part # can only be ordered under an
Enterprise Agreement. Microsoft's ordering tools do not allow them to order
it for an Open Value customer. They have specific part numbers for
different programs, and no part # exists for this item (SKU AAA-51069)
under Open Value. I need it to be able to activate a Windows 10
Subscription (as part of Microsoft 365 E3).

**Comment by mypil** [comment]
@eduardok - I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
