### ISSUE TITLE
Autlogon not working

### ISSUE THREAD

**Issue by djc6103** [MicrosoftDocs/windows-itpro-docs#4509]
I can't get auto logon working in 1903 using the XML in this article. This is what I've got:
```xml
<Configs>
        <Config>
            <AutoLogonAccount rs5:DisplayName="Test"/>
            <DefaultProfile Id="{9A2A490F-10F6-4764-974A-43B19E722C23}"/>
        </Config>   
</Configs>
```
A KioskUser0 user is created, but it's not auto logging on. Is there anything additional required like creating the user as part of the provisioning package?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78038d67-04a1-f4ae-6a69-98e157688a31
* Version Independent ID: c86b4460-e8be-8537-a6c8-3cb094ef14a3
* Content: [Set up a multi-app kiosk  (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps#feedback)
* Content Source: [windows/configuration/lock-down-windows-10-to-specific-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/lock-down-windows-10-to-specific-apps.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @djc6103 thank you for bringing this to our attention. We're happy to assist you with your concern, however, this Github site is used as a feedback system to help improve the quality of the technical documentation. We recommend that you open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance, or you can also check related posts/conversations at the [Microsoft community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities). These resources may be of help:

1. [Kiosk Mode not logging in - "kioskUser0 the user name or password is incorrect"](https://techcommunity.microsoft.com/t5/Microsoft-Intune/Kiosk-Mode-not-logging-in-quot-kioskUser0-the-user-name-or/td-p/377762)
2. [Autologin to kiosk not working as expected](https://techcommunity.microsoft.com/t5/Microsoft-Intune/Autologin-to-kiosk-not-working-as-expected/td-p/310482)

Please keep us posted here on the resolution or information that can be called out in the docs. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation.

**Comment by jvsam** [comment]
Hi again @djc6103 we hope you were able to resolve your concern, either by contacting support or utilizing the information found on the Microsoft Tech Community. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
