### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by uk-gadget** [MicrosoftDocs/windows-itpro-docs#4511]
Any idea when White Glove will feature caching of Store Apps ect?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@uk-gadget - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by uk-gadget** [comment]
Attached link to White Glove Presentation @ time 4:40: http://tgi3dev:8080/v2/autodeployadmin/acecodemanagement.php

FYI just got or first rollout of White Glove Deploymeny of 2,000 systems

**Comment by uk-gadget** [comment]
https://youtu.be/nE5XSOBV0rI

Correct Link ^^

**Comment by mypil** [comment]
@uk-gadget - Thank you for engaging with the community here for the docs.

This issue that you have is better suited for the Feedback Hub.
I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via [Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

**Comment by mypil** [comment]
@officedocsbot close
