### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#4512]
Please add the `StartLayoutCollection` syntax to this reference. The syntax is used throughout the rest of the documentation on this topic, yet does not appear in the reference.
Please also put a note or clarification on the sections for `RequiredStartGroupsCollection` and `AppendGroup`. This syntax does NOT appear anywhere else in the documentation, and it appears likely that it applies only to the special case of the `Import-StartLayout` method used for building and deploying Windows images.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Air-Git - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by Air-Git** [comment]
Hi, sorry, don't know what happened there. It is this page: [Start layout XML for desktop editions of Windows 10 (reference)](https://docs.microsoft.com/en-us/windows/configuration/start-layout-xml-desktop)

**Comment by mypil** [comment]
@Air-Git - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by Air-Git** [comment]
Is it resolved? What changes were agreed?

**Comment by mypil** [comment]
@Air-Git - You can find the changes made to the doc from this commit [f6abc20 ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/f6abc2013d4cb3940352dd73dd96e66db900b425) based on the merged PR created for this issue.

**Comment by mypil** [comment]
@officedocsbot close
