### ISSUE TITLE
Can you use SID instead of names?

### ISSUE THREAD

**Issue by StevenProvo** [MicrosoftDocs/windows-itpro-docs#4514]
Using SID would solve the language issue.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@StevenProvo - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@StevenProvo - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to open a new issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
