### ISSUE TITLE
Ensuring 'Devices: Prevent users from installing printer drivers' is set to enabled via the registry?

### ISSUE THREAD

**Issue by Jnchi** [MicrosoftDocs/windows-itpro-docs#4515]
Even with the following applied, it is still not being set correctly on our workstations; this must be the wrong key.

```
MACHINE\System\CurrentControlSet\Control\Print\Providers\LanMan Print Services\Servers\AddPrinterDrivers=4,1
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac1f46e-dad3-81cb-90ab-837a6dc7c9d0
* Version Independent ID: 84d7b3d7-f807-c21f-fd20-9e5cdc0bd296
* Content: [Devices Prevent users from installing printer drivers (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/devices-prevent-users-from-installing-printer-drivers)
* Content Source: [windows/security/threat-protection/security-policy-settings/devices-prevent-users-from-installing-printer-drivers.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/devices-prevent-users-from-installing-printer-drivers.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Jnchi - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@Jnchi - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
