### ISSUE TITLE
Error code 67

### ISSUE THREAD

**Issue by Capissen38** [MicrosoftDocs/windows-itpro-docs#4517]
I'm seeing error code 67 when running Pilot/RunConfig.bat as system account. It says "CheckUtcCsp failed with unexpected exception. HResult: -2146233088 ExceptionMessage: Invalid class". Win10 Enterprise 1809 64-bit fully up-to-date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f029a728-1f53-4576-a6ca-8a19a92626e6
* Version Independent ID: 85f27ad5-84e2-0787-082f-59d2d66c99b5
* Content: [Upgrade Readiness deployment script (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-deployment-script#feedback)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-deployment-script.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-deployment-script.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Capissen38 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
