### ISSUE TITLE
Update for new portal

### ISSUE THREAD

**Issue by matthilt** [MicrosoftDocs/windows-itpro-docs#4527]
Can this be updated to for the new portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c43e091a-bd6e-82ef-a801-fa6fd04dec38
* Version Independent ID: f1e49860-8e09-1975-a872-8924f0a831c6
* Content: [Management tool for the Microsoft Store for Business](https://docs.microsoft.com/en-us/windows/client-management/mdm/management-tool-for-windows-store-for-business#feedback)
* Content Source: [windows/client-management/mdm/management-tool-for-windows-store-for-business.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/management-tool-for-windows-store-for-business.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@matthilt - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@matthilt - From our understanding, the issue has been resolved based on the merged commit [[a0e6e6a](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/a0e6e6a137e5a75040f6bc9bcd780584c9556f18)] but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
