### ISSUE TITLE
Code sample is incompatible with strict CSP policy

### ISSUE THREAD

**Issue by newsoft** [MicrosoftDocs/windows-itpro-docs#4529]
The following code snippet will prevent the server from serving a strict Content Security Policy:
```
      &lt;script&gt;
         function formSubmit() {
            document.forms[0].submit();
         }
           window.onload=formSubmit;
      &lt;/script&gt;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d06bf1eb-9ddd-b89c-866c-78f0d5f348a6
* Version Independent ID: 399fabc9-c643-afd3-354e-7b32cc1e4bc4
* Content: [Federated authentication device enrollment](https://docs.microsoft.com/en-us/windows/client-management/mdm/federated-authentication-device-enrollment#feedback)
* Content Source: [windows/client-management/mdm/federated-authentication-device-enrollment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/federated-authentication-device-enrollment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@newsoft - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@newsoft Strict CSPs require making some changes to the HTML template (among other places), which is not covered by the refferenced article. I will create a PR and add a note explicitely stating this. Hope this is ok.

**Comment by mypil** [comment]
@newsoft - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
