### ISSUE TITLE
Missing ClickOnce deployed applications

### ISSUE THREAD

**Issue by Lechus** [MicrosoftDocs/windows-itpro-docs#4539]
ClickOnce deployed applications are not listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69202cf2-6553-c950-dc75-750a50226571
* Version Independent ID: d80652ad-4aae-00c9-fdd8-7294e9453cef
* Content: [Find the Application User Model ID of an installed app](https://docs.microsoft.com/en-us/windows/configuration/find-the-application-user-model-id-of-an-installed-app)
* Content Source: [windows/configuration/find-the-application-user-model-id-of-an-installed-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/find-the-application-user-model-id-of-an-installed-app.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @Lechus are you trying to find the AUMID of ClickOnce applications? Kindly refer to this [old issue](https://github.com/MicrosoftDocs/windows-uwp/issues/361) raised in another repository, it may be of help. And this may be the correct Topic to request for that information since the process is different for ClickOne. How about here? https://docs.microsoft.com/en-us/visualstudio/deployment/clickonce-security-and-deployment

Another reference: https://docs.microsoft.com/en-us/windows/win32/shell/appids

Now if my understand is incorrect, kindly provide more information so we will know how to assist you better. Thank you.

**Comment by Lechus** [comment]
@jvsam found the solution, added as a message on the referred old issue link https://github.com/MicrosoftDocs/windows-uwp/issues/361. So for the click once apps AppIds are in diff registry place. And that is missing.

**Comment by illfated** [comment]
@Lechus : First of all, thanks for posting in both places. Secondly, to avoid confusing myself, are you recommending a change to the UWP page or to the IT-Pro page (as linked above)?

If the IT-Pro page is the one you recommend updating, may I ask you to tell me in more detail what the necessary changes are?

**Comment by jvsam** [comment]
That's great to hear @Lechus. Thanks for sharing that information. So, to follow-up on @illfated's question, is there anything in this doc that needs to be updated? Information that is relevant like the deployment framework scenario [here](https://docs.microsoft.com/windows/win32/shell/appids), perhaps? If it's not applicable, then I think we can close this issue and consider it as resolved. It might also worth noting that you can share the information in the [Technet forums](https://social.technet.microsoft.com/Forums/home) and the [Tech Community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities) with other users and experts. Thank you.

**Comment by jvsam** [comment]
Hi again @Lechus, we didn’t hear back from you so I will close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
