### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by tlamothe** [MicrosoftDocs/windows-itpro-docs#4540]
The Link download the tools which references https://www.microsoft.com/download/details.aspx?id=55319 rdirects to a page with 
"We are sorry, the page you requested cannot be found.1"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 014ca19c-6ab8-6eec-321e-72fa22c8f2c3
* Version Independent ID: 948a95a8-cb4f-668a-1988-17830d51845b
* Content: [Microsoft Security Compliance Toolkit 1.0](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-compliance-toolkit-10#feedback)
* Content Source: [windows/security/threat-protection/security-compliance-toolkit-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-compliance-toolkit-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
The link works fine for me, so maybe your browser redirects to a page locale different from en-us?
https://www.microsoft.com/en-us/download/details.aspx?id=55319 is online, I don't see anything wrong there.
The only conundrum would be if there is a different redirect for you when clicking the link
https://www.microsoft.com/download/details.aspx?id=55319 .

**Comment by tlamothe** [comment]
Yep, just checked the link, it is working for me now and I was able to download the files.
