### ISSUE TITLE
Качество перевода

### ISSUE THREAD

**Issue by FckThLgn** [MicrosoftDocs/windows-itpro-docs#4541]
Господа, какой поц додумался переводить имена системных переменных? ОСДРИВЕ, это надо же... Я понимаю, что переводит не человек, но настроить эту консерву хотя бы можно? Или вычитывать переводы.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: beea27a0-0b22-84fa-be80-8eddf0c0f292
* Version Independent ID: 935d3b82-f737-c4a6-f61c-c93675ace781
* Content: [Работа с правилами AppLocker (Windows 10)](https://docs.microsoft.com/ru-ru/windows/security/threat-protection/windows-defender-application-control/applocker/working-with-applocker-rules#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/applocker/working-with-applocker-rules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/applocker/working-with-applocker-rules.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for your feedback @FckThLgn. I can see that some of the path variables are translated and they shouldn't be. For example:

RU: % ОСДРИВЕ%
EN: %OSDRIVE%

We appreciate you informing us about this. I am assigning this to you @dongmicro, thanks.

**Using Bing Translator:**
> Gentlemen, what's the idea of translating the names of system variables? OSDRIE, it's necessary... I understand that he is not a person, but at least it is possible to adjust this can? Or subtract translations.

**Comment by jvsam** [comment]
@officedocsbot assign @dongmicro

**Comment by illfated** [comment]
@jvsam : I don't know exactly how the responsibilities are ordered, but there was a change from @dongmicro to @MollyMalone (@TinaMcN) for several of the East Asian (Japanese & Chinese) translation issues. I don't know if all of the cases previously assigned to @dongmicro should be reassigned, so it would be useful to know which areas of responsibility are currently assigned to either of them.

**Comment by TinaMcN** [comment]
Yes, all cases that were previously assigned to @dongmicro should now be assigned to me (@TinaMcN)

**Comment by jvsam** [comment]
@officedocsbot assign @TinaMcN

**Comment by jvsam** [comment]
Hi @TinaMcN assigning this to you. Thank you.

**Comment by jvsam** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
Эта проблема вызвана ошибкой в инструменте машинного перевода.  Было сообщено владельцам инструментов, но, как это не будет исправлено в ближайшее время я послал его, чтобы быть человеком переведены.
This issue is caused by a bug in the machine translation tool.  It has been reported to the tool owners but as it will not be fixed soon I have sent it to be human translated.

**Comment by TinaMcN** [comment]
@FckThLgn Статья теперь человек переведен.  Пожалуйста, убедитесь, что проблема исправлена.  Еще раз спасибо за обратную связь.
(The article is now human translated.  Please verify that the issue is fixed.  Thanks again for the feedback.)

**Comment by illfated** [comment]
All 12 pairs of percent character ( % ) (24 found when using Ctrl-F on the page) now show untranslated English system variables on the page.
This issue looks resolved to me.

**Comment by jvsam** [comment]
Hello @FckThLgn we really appreciate your patience and thank you again for sharing your feedback. We will now close this issue since it has been resolved and updates are now displayed here at docs.microsoft.com. Please continue to send your feedback and suggestions to help improve the quality of the technical documentation of Microsoft Docs. Thank you for being part of the community!

**Comment by jvsam** [comment]
@officedocsbot close
