### ISSUE TITLE
Conflicting information regarding managing Surface Drivers and Firmware with SCCM

### ISSUE THREAD

**Issue by jrosser1221** [MicrosoftDocs/windows-itpro-docs#4546]
Beginning in SCCM 1710, we can deploy Surface Drivers and Firmware updates through SCCM without using an application deployment:

https://support.microsoft.com/en-us/help/4098906/manage-surface-driver-updates-in-configuration-manager

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be733d41-3006-2d0c-ec8b-5438ecf76121
* Version Independent ID: 7fcdb3fb-b0fc-db95-bda1-b20d352ca664
* Content: [Considerations for Surface and System Center Configuration Manager (Surface)](https://docs.microsoft.com/en-us/surface/considerations-for-surface-and-system-center-configuration-manager#feedback)
* Content Source: [devices/surface/considerations-for-surface-and-system-center-configuration-manager.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/considerations-for-surface-and-system-center-configuration-manager.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @jrosser1221 thank you for providing that information. I will forward your suggestion to the Windows content writing team for review and _suggest an amendment or update specifically on the **Updating Surface device drivers and firmware** section to include the new method to deploy Surface driver and firmware updates_.

We really appreciate your feedback and thank you for being part of the Microsoft Docs Community and for helping improve the quality of the technical documentation!

**Comment by illfated** [comment]
( back reference to #5626 )

**Comment by jvsam** [comment]
Hello @jrosser1221, we really appreciate your patience and thank you again for sharing your feedback. Please be informed that the pull request (See PR #5626) that contains suggestions based from your feedback has been approved and merged. This documentation will be updated in the next scheduled publishing run. We will now close this issue, thank you for being part of the community!

**Comment by jvsam** [comment]
@officedocsbot close
