### ISSUE TITLE
Hybrid Azure AD Join and Domain Join device configuration 

### ISSUE THREAD

**Issue by JuGhithub** [MicrosoftDocs/windows-itpro-docs#4549]
For Hybrid Azure AD Join scenario, is it necessary to deploy a domain join device on all devices If I create a dynamic group with ZtdCorrelationId for existing devices ? ( like described in the blog of michael niehaus https://blogs.technet.microsoft.com/mniehaus/2018/12/17/revisiting-windows-autopilot-for-existing-devices/ )

Regards, 
julien

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17bfe927-f7b7-608b-8537-5c2274ccdced
* Version Independent ID: 5dd9abca-92d9-fbb2-6796-d1f6b9ab3c8b
* Content: [Windows Autopilot for existing devices](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/existing-devices#feedback)
* Content Source: [windows/deployment/windows-autopilot/existing-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/existing-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@JuGhithub - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello @JuGhithub ,
yes, you still need to deploy a domain join device. Method described in the blog article is only for registration of deployed devices in Autopilot.
Thank you

**Comment by mypil** [comment]
@JuGhithub - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
