### ISSUE TITLE
[Preview] Folder Access sample xml

### ISSUE THREAD

**Issue by Niglb** [MicrosoftDocs/windows-itpro-docs#4552]
Do we know the build of Windows 10 Prerelease this is applicable to? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7479ec95-228f-8f08-4b24-0a7b7a5314ec
* Version Independent ID: f4d42c2f-17a2-52b2-6daa-cc7cecacfdc7
* Content: [Assigned Access configuration kiosk XML reference (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/kiosk-xml#preview-folder-access-sample-xml)
* Content Source: [windows/configuration/kiosk-xml.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-xml.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Niglb - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Niglb - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
