### ISSUE TITLE
How do we get an Evaluation Lab environment?

### ISSUE THREAD

**Issue by cw123williams** [MicrosoftDocs/windows-itpro-docs#4554]
My assumption is we need to start with a free trial first?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12e5744d-46dd-7f90-e42e-70caf9dd56d2
* Version Independent ID: 1a627400-9585-e482-3820-e58f6c172a87
* Content: [Microsoft Defender ATP evaluation lab](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/evaluation-lab#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/evaluation-lab.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/evaluation-lab.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@cw123williams - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @cw123williams , evaluation lab is a part Windows Defender ATP, sot the requirements are the same: [Minimum requirements for Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
**My assumption is we need to start with a free trial first?** - yes, sure, you just need to get [WD ATP free trial](https://www.microsoft.com/en-us/microsoft-365/windows/microsoft-defender-atp)
Thank you

**Comment by mypil** [comment]
@cw123williams - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
