### ISSUE TITLE
Where is Microsoft Hello data stored?

### ISSUE THREAD

**Issue by andrewwillett** [MicrosoftDocs/windows-itpro-docs#4557]
This should read 'Where is **Windows** Hello data stored?'

**Comment by mypil** [comment]
@andrewwillett - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by andrewwillett** [comment]
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-biometrics-in-enterprise#where-is-microsoft-hello-data-stored

**Comment by mypil** [comment]
@andrewwillett - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@andrewwillett - PR #4559 has been created to fix and close this issue once the PR is merged.

Thank you for your contribution to make the docs better! Much appreciated!
