### ISSUE TITLE
Section on Policy is garbled and incorrect

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#4558]
The section on Policy (under "Each of the previous nodes contains one or more of the following leaf nodes:") is garbled and incorrect. The whole section should actually read as follows:
"Policy nodes define the policy for launching executables, Windows Installer files, scripts, store apps, and DLL files. The contents of a given Policy node is precisely the XML format for a RuleCollection node in the corresponding AppLocker XML policy.

Data type for AppLocker policies is string. Supported operations are Get, Add, Delete, and Replace.

Data type for Code Integrity policy is Base64. Supported operations are ???? However, you should enter the binary representation of the policy generated by ConvertFrom-CIPolicy, and not a Base64 encoded version of it. The Base64 data type is just the vehicle for uploading and delivering the binary file."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa7dd86-8bcc-bb92-0a66-86e24701e5a4
* Version Independent ID: 277e194c-0fa3-7da6-1814-f6951e440df6
* Content: [AppLocker CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/applocker-csp)
* Content Source: [windows/client-management/mdm/applocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/applocker-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Air-Git - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by illfated** [comment]
The PR #4585 is as good as complete, we are only waiting for @lomayor (or any other relevant MDM admin contributor, like @lizap ) for final review & merge of the PR content.

**Comment by mypil** [comment]
@Air-Git - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
