### ISSUE TITLE
LTSC to SAC requires a product key to keep apps. I have edited the post via github.

### ISSUE THREAD

**Issue by andrewjohnporter** [MicrosoftDocs/windows-itpro-docs#4561]
You will need to use the Product Key switch if you want to keep your apps. If you don't use the switch the option 'Keep personal files and apps' will be grayed out. The command line would be: setup.exe /pkey xxxxx-xxxxx-xxxxx-xxxxx-xxxxx using your relevant Windows 10 SAC product key. For example, if using a KMS, the command line would be setup.exe /pkey NPPR9-FWDCX-D2C8J-H872K-2YT43

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08436cb0-d0b6-0961-9e57-291b24d73644
* Version Independent ID: 36264f52-d3ac-4e50-f8e8-b09d6b210490
* Content: [Windows 10 upgrade paths (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-upgrade-paths#feedback)
* Content Source: [windows/deployment/upgrade/windows-10-upgrade-paths.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/windows-10-upgrade-paths.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @andrewjohnporter from my understanding, you've suggested an update to this documentation. Is there a pull request made to this commit [0787b37](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/9c23fbbc18260d3ca2abd2108ffa25444a128c2f#diff-9b42230e713b999e4b678c36e193e003) so we can track? Thank you.

**Comment by illfated** [comment]
@jvsam : That would be PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4548 (from the commit page, in the parenthesis)
***
![image](https://user-images.githubusercontent.com/38162891/62174908-eea8e800-b33b-11e9-82ce-ece88580ed74.png)
***
![image](https://user-images.githubusercontent.com/38162891/62174896-ddf87200-b33b-11e9-82b0-b0873f79b610.png)
***

**Comment by jvsam** [comment]
Awesome, thank you @illfated 

Hi again @andrewjohnporter, the changes have been merged and will be displayed at docs.microsoft.com in the next scheduled publishing run, so please monitor this doc. We will now close this issue and consider it resolved, thank you.

**Comment by jvsam** [comment]
@officedocsbot close
