### ISSUE TITLE
Replace any "Sprint" and "T-Mobile" references with "New T-Mobile."

### ISSUE THREAD

**Issue by jebeld17** [MicrosoftDocs/windows-itpro-docs#4564]
With T-Mobile now owning Sprint in the United States, any references to either company should be replaced with the new merger's name of "New T-Mobile."

This will help Sprint or T-Mobile customers find the right product to utilize Microsoft's resources correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de75f7d-a749-ec5f-435b-62bc163a2b72
* Version Independent ID: 8d221f64-7c6b-d604-3dfa-51d8b9163a3f
* Content: [Surface System SKU reference](https://docs.microsoft.com/en-us/surface/documentation/surface-system-sku-reference#feedback)
* Content Source: [devices/surface/documentation/surface-system-sku-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/documentation/surface-system-sku-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @CoveMiner
* Microsoft Alias: **v-jokai**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thanks for letting us know about this @jebeld17. Although the *approved deal between the two* is all over the news today, there is no official announcement yet, except for [this](https://www.t-mobile.com/news/t-mobile-sprint-merger-doj-clearance) and it does not indicate that it's a done deal (_or officially closed_). 

> ...today announced they have taken an important step toward completing their proposed merger to create the New T-Mobile by entering into a consent decree with the U.S. Department of Justice (DOJ). The DOJ action moves the merger one step closer to closing, pending other regulatory approvals and the satisfaction of other closing conditions...

> ...The completion of the T-Mobile and Sprint combination remains subject to remaining regulatory approvals and certain other customary closing conditions. T-Mobile and Sprint expect to receive final federal regulatory approval in Q3 and currently anticipate that the merger will be permitted to close in the second half of 2019...

Once it's official that it's going to be the *New T-Mobile*, I am sure the Microsoft authors will be making the appropriate updates to the docs. Personally, it's not just simple branding change, I would assume this will need to go through legal first. FYI @CoveMiner 

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
