### ISSUE TITLE
Hotlinks missing

### ISSUE THREAD

**Issue by SpinmanUK** [MicrosoftDocs/windows-itpro-docs#4569]
"Configure Microsoft Threat Protection integration" and "Management and API support" don't have hotlinks associated with them, even though they are valid pages.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30b548d4-79f8-5ac4-70fc-b1bffe591d65
* Version Independent ID: 41d11827-6cdc-df28-3932-28bfcf3c2a2f
* Content: [Configure and manage Microsoft Defender ATP capabilities](https://docs.microsoft.com/en-gb/windows/security/threat-protection/microsoft-defender-atp/onboard#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/onboard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/onboard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **mjcaparas**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@SpinmanUK - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@spinmanuk Can you please share the links for the pages you have mentioned.

**Comment by SpinmanUK** [comment]
So I’m guessing that the links aren’t there because the top level links for these topics aren’t clickable.
Ideally each section should have a header page.
This screenshot shows what I mean:
[A screenshot of a cell phone  Description automatically generated]


[cid:image004.png@01D5461B.8D6F98A0]
Steve Newby
Senior Program Manager
Windows Cyber Defense (CxE)

• e-mail: steve.newby@microsoft.com<mailto:steve.newby@microsoft.com>
• Tel: +44 (0) 118 9092754
[cid:image005.jpg@01D5461B.8D6F98A0]


Sign Up At - https://aka.ms/windows-atp<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fwindows-atp&data=02%7C01%7C%7C8605493de9274284246108d61e2be776%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636729571242695807&sdata=b8Zrf59iJc1%2BQrP46ejXFk54VltpcFbllvpsTeT32wI%3D&reserved=0>
Technical Information - https://aka.ms/technet-wdatp<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Ftechnet-wdatp&data=02%7C01%7C%7C8605493de9274284246108d61e2be776%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636729571242705819&sdata=3Ds%2BFtwKl0X7f1lYam92Jnrr5E1FqQKmPDIEy4sV%2B58%3D&reserved=0>
Video Demo - https://aka.ms/build-wdatp1<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fbuild-wdatp1&data=02%7C01%7C%7C8605493de9274284246108d61e2be776%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636729571242705819&sdata=9dKeyt8YyCR2rnZd7JLy0pui%2FhcaB%2B%2Fu7uiaNtjAamY%3D&reserved=0>

**Comment by mypil** [comment]
@SpinmanUK - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
