### ISSUE TITLE
User Account Type

### ISSUE THREAD

**Issue by JonesOne** [MicrosoftDocs/windows-itpro-docs#4573]
For self-deploying mode, should a User Account Type of Administrator allow all users who log in to be local admins?

During our test, on a 1903 deployment, setting this to Administrator did NOT result in the logged on user having local administrator rights.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6867cc8c-868d-d472-8aa5-1ed5b94ced2c
* Version Independent ID: 6822e12d-7474-9e49-1e8b-88f7eec3b22c
* Content: [Windows Autopilot Self-Deploying mode](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/self-deploying#feedback)
* Content Source: [windows/deployment/windows-autopilot/self-deploying.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/self-deploying.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@JonesOne - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @JonesOne , When you are deploying the device and need to provide local users admin access then you need to add the local users or the local groups as an administrator to work this as expected. 

Regards,
Imran.

**Comment by mypil** [comment]
@JonesOne - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by JonesOne** [comment]
Hi @joinimran ,

Ah I see - but when deploying the device in a Self-Deploy profile, no accounts appear to have local admin to do this, except for those specified in Azure as either global admins or device administrators (neither of which are currently granted to help desk personnel in our organization).

Could I ask what the function of the 'User Type' toggle is on the Self-Deploy profile, if not to make user Admin? It's function in this context doesn't appears to be documented.

**Comment by joinimran** [comment]
@JonesOne Please note that self-deploying mode doesn't support Active Directory or Hybrid AD Users and Groups. If you want to give them the admin rights then those users or groups should be on Azure AD.

You can also share your feedback and request for this feature. 

@mypil Please guide user how he can request for new features.

Regards,
Imran.

**Comment by mypil** [comment]
@JonesOne - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via [Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by JonesOne** [comment]
Hi Imran,

To note – the user logging in IS in Azure AD. From our experimentation the user does not get Admin regardless of how the User Account Type toggle is set on the deployment profile.

My question is not one of a new feature, but clarification on the function of the User Account type toggle for the deployment profile in the context of Self-Deploying. Our observation is that this toggle presently makes no difference to account privileges.

**Comment by joinimran** [comment]
@JonesOne Thank you for sharing the details. I have checked for any relevant documentation related to this but couldn't find anything to better help you.

In this case, I would suggest you open a support case with Microsoft support team to the immediate resolution of this issue.

@mypil Please guide user a support case can be open with Microsoft.

Regards,
Imran.

**Comment by mypil** [comment]
@JonesOne - You can open a service ticket so this can get resolved ASAP. Based on outcome let us know if it is something that can be called out in the documentation.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If in case you find that it is a documentation error, feel free to comment back here and we'll be glad to help fix it. Thank you!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by nhogarth86** [comment]
@JonesOne this is because the local admin option is not supported on the self-deploying autopilot profile. Probably because its a shared device and no user is assigned to the device. Microsoft need to remove this option from the profile. I have logged a support request.
