### ISSUE TITLE
Hotfix link is outdated

### ISSUE THREAD

**Issue by CaptainUnlikely** [MicrosoftDocs/windows-itpro-docs#4574]
The link "Desktop Optimization Pack" goes to the July 2018 servicing release.
MABM version chart here - https://blogs.technet.microsoft.com/dubaisec/2016/05/23/mbam-version-chart/ - states there is a May 2019 release now - https://support.microsoft.com/en-gb/help/4505175/may-2019-servicing-release-for-microsoft-desktop-optimization-pack

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67626969-2854-3925-fc2d-9d8a09183796
* Version Independent ID: f442462e-6e55-406d-9a77-4e98e6dc036f
* Content: [Applying hotfixes on MBAM 2.5 SP1](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/apply-hotfix-for-mbam-25-sp1)
* Content Source: [mdop/mbam-v25/apply-hotfix-for-mbam-25-sp1.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/apply-hotfix-for-mbam-25-sp1.md)
* Product: **w10**
* Technology: **mdop**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
Very well, so the old link https://www.microsoft.com/en-us/download/details.aspx?id=57157
needs to be replaced with https://www.microsoft.com/en-us/download/details.aspx?id=58345
unless I have missed something. Would you like me to open a PR for it?

**Comment by jvsam** [comment]
Thank you for bringing this to our attention @CaptainUnlikely. We always strive to improve the quality of the technical documentation of Microsoft Docs so your feedback is appreciated.

Hi @illfated can you please proceed in creating a PR to correct the *Desktop Optimization Pack* link? As always, thank you very much for your assistance.

**Comment by illfated** [comment]
There you go. PR #4592 ready for review (only 1 change, like in my comment links above).
Feel free to suggest other changes on the same page, if there are any at all.

**Comment by jvsam** [comment]
Hi again @CaptainUnlikely, the pull request (see #4592) submitted by @illfated has been approved and merged. The link update will be displayed here at docs.microsoft.com in the next scheduled publishing run. Thank you again for your feedback and for being part of the Microsoft Docs community!
