### ISSUE TITLE
Clarify "might impact client performance"

### ISSUE THREAD

**Issue by Alex-Brooks** [MicrosoftDocs/windows-itpro-docs#4577]
Hi,

In the "Warning" box at the bottom of this page, the text says "The High + setting might impact client performance.".  It also says "setting this switch to High might cause some legitimate files to be detected".

As there are four levels (Default, High, High +, and Zero Tolerance) the assumptions would be:

- If "high" may cause false positives, this also applies (possibly even more so) for High + and Zero Tolerance
- If "high +" may impact client performance, this also applies (possibly even more so) to Zero Tolerance.

However, the page is not clear if this is the case (it **may** be that High + is the only setting that impacts performance for example, and Zero Tolerance is fine, and it **may** be that High is the only setting that increases the risk of false positives, and High + and Zero Tolerance do not do this)

I would suggest that this is clarified.

My two suggested ways of doing this would be to either:

- expand the text in the warning box, e.g. "The High + and Zero Tolerance settings might impact client performance" or "The High + setting might impact client performance, Zero Tolerance and other settings should not impact performance)

- insert a table:

| **Setting** | **Increases risk of false positives** | **May impact client performance** |   |   |
|---|---|---|---|---|
| Default | No | No |   |   |
| High | Yes | No |   |   |
| High + | Yes | Yes |   |   |
| Zero Tolerance | Significantly more than any other level | Significantly more than any other level |   |   |

Thanks for looking into and clarifying these settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f0f5a3-f095-3fa4-90dd-7dee8ccb49ad
* Version Independent ID: 1bec5d66-a92a-4b0d-b9d8-f43c9eab4a50
* Content: [Specify cloud-delivered protection level in Windows Defender Antivirus](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/specify-cloud-protection-level-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/specify-cloud-protection-level-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/specify-cloud-protection-level-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for your feedback to help improve the quality of the technical documentation of Microsoft Docs, @Alex-Brooks!

> As there are four levels (Default, High, High +, and Zero Tolerance) the assumptions would be:
If "high" may cause false positives, this also applies (possibly even more so) for High + and Zero Tolerance
If "high +" may impact client performance, this also applies (possibly even more so) to Zero Tolerance.

Hello @Dansimp, if time permits, can you please clarify if the above is accurate? If yes, we can then create a pull request with the suggestions from Alex. Appreciate the assistance, thanks.

**Comment by jvsam** [comment]
Hi again @Dansimp, just following up to get your input regarding the feedback from a community user before we create a pull request. Thank you so much.

**Comment by jvsam** [comment]
> If "high" may cause false positives, this also applies (possibly even more so) for High + and Zero Tolerance
> If "high +" may impact client performance, this also applies (possibly even more so) to Zero Tolerance.

Hi again @Dansimp if you are not busy, can you please look into this community suggestion? Kindly confirm if the assumptions are correct. Thank you.

**Comment by jvsam** [comment]
Hello again @Alex-Brooks , thank you for your patience. Please be informed that the suggested updates to this documentation as per your feedback (see pull request #5068) have already been merged, and displayed here at docs.microsoft.com. Although we did not add a table, the descriptions are clearer particularly the *High + blocking level* and how it *may impact client performance and increase risk of false positives*. 

We will now close this issue. Feel free to re-open or create another issue through the *feedback feature* if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
