### ISSUE TITLE
mbr2gpt:  workaround for sysprepped images

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/windows-itpro-docs#4578]
Sysprepped images in the bcd have the osdevice set to "locate=\Windows".  So then mbr2gpt can't find the os.  This bcdedit command seems to get things working:  

```batchfile
bcdedit /set {default} osdevice partition=C:
```

Might have to do:

```batchfile
bcdedit /store c:\boot\bcd /set {default} osdevice partition=C:  
```

I would think this command would work with sysprep without any intervention?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73c22f0-cb0d-e34b-29d8-06829b86784f
* Version Independent ID: 083115ed-f1be-e962-5b0e-5079dec37353
* Content: [MBR2GPT](https://docs.microsoft.com/en-us/windows/deployment/mbr-to-gpt)
* Content Source: [windows/deployment/mbr-to-gpt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/mbr-to-gpt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @jszabo98 thank you for your question. 

> Sysprepped images in the bcd have the osdevice set to "locate=\Windows". So then mbr2gpt can't find the os. This bcdedit command seems to get things working:
bcdedit /set {default} osdevice partition=C:
I would think this command would work with sysprep without any intervention?

Hi @greg-lindsay, if time permits, can you please review this and provide some insight on @jszabo98's question? Thank you in advance for your assistance.

**Comment by jvsam** [comment]
Hi again @greg-lindsay, just following up to get your input regarding the feedback from a community user. Thank you so much.

**Comment by jvsam** [comment]
Hi @jszabo98 may I also suggest that you [contact support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) to confirm the information? And then please keep us posted here on the resolution or information that can be called out in the docs. Looking forward to hearing from you!

**Comment by jvsam** [comment]
Hi again @jszabo98 I just want to follow-up if you were able to contact support and if the answer to your question is something that we can incorporate in this doc? Please keep us updated here, thank you very much.

**Comment by jszabo98** [comment]
Does that cost anything?

**Comment by jvsam** [comment]
It depends @jszabo98, there is a premium [Assisted software support](https://support.microsoft.com/help/4467230/assisted-software-support-options-assure-premium) and general product support which is free. For the latter, you can call one of the toll-free numbers or chat with an agent (initially, it will be a virtual agent). Then you have the option to ask questions or troubleshooting feedback from our worldwide community. Please try and explore those options.

![image](https://user-images.githubusercontent.com/18371314/62839720-96210580-bcc0-11e9-8ee4-9f04c2cb3c18.png)

**Comment by jonconwayuk** [comment]
Is the known issue regarding MBR2GPT.exe going to be rectified in future releases, or is this removal of required dll and associated files a permanent change?

**Comment by jvsam** [comment]
Hi @jonconwayuk, if you are pertaining to the known issue with Windows PE, unfortunately, we do not have that information available at the moment. But rest assured the the docs will be updated once it's resolved. If you need immediate answer to your question, I would recommend contacting [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10). Right now, please follow the recommended workaround if you are experiencing the issue. 

Also, please be informed that this Github site is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. If you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review. 

I will now close this issue. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
