### ISSUE TITLE
Wrong Link? :  How to configure hybrid Azure Active Directory joined devices 

### ISSUE THREAD

**Issue by SteveBurkettNZ** [MicrosoftDocs/windows-itpro-docs#4582]
In the 'Configure Azure for Device Registration' section, it links to 'How to configure hybrid Azure Active Directory joined devices' (https://docs.microsoft.com/azure/active-directory/device-management-hybrid-azuread-joined-devices-setup) but this link looks to have changed and currently takes you to 'How To: Plan your hybrid Azure Active Directory join implementation' (https://docs.microsoft.com/en-nz/azure/active-directory/devices/hybrid-azuread-join-plan).

Means the following text ('In the Configuration steps section, identify your configuration at the top of the table (either Windows current and password hash sync or Windows current and federation) and perform only the steps identified with a check mark.') doesn't fit with what's on the linked to page. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d87ba3ab-d8a7-d038-2f7d-886bed956394
* Version Independent ID: cb2ea1fd-6a0d-8656-0bb4-0528c65ea03f
* Content: [Configure Device Registration for Hybrid key trust Windows Hello for Business](https://docs.microsoft.com/en-nz/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-devreg#configure-azure-for-device-registration)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-devreg.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-devreg.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @SteveBurkettNZ thank you for bringing this to our attention. 

The link should go [here instead](https://docs.microsoft.com/azure/active-directory/devices/hybrid-azuread-join-manual) and to check at the *Verify configuration steps* section. 

![image](https://user-images.githubusercontent.com/18371314/62266239-64fd2700-b3dc-11e9-99d6-55985d50b9b8.png)

I will get this over to the Windows content writing team to suggest correcting the link.  We always strive to improve the quality of the technical documentation of Microsoft Docs so your feedback is appreciated.

Thank you for being part of the Microsoft Docs Community!

**Comment by jvsam** [comment]
Hello again @SteveBurkettNZ. thank you for your patience. The update to correct one of the links on this documentation, has been approved and merged (see #4703). The update will be displayed here at docs.microsoft.com in the next scheduled publishing run. 

Thank you for your feedback and for being part of the Microsoft Docs community!
