### ISSUE TITLE
Unclear definition in the documentation

### ISSUE THREAD

**Issue by KC-Syd** [MicrosoftDocs/windows-itpro-docs#4583]
When the definitions mention "as a percentage of available download bandwidth", how is this total calculated/gathered? I'm connected to the router with Gb speed, but my internet speed is limited to 20Mbps. Does Windows do an internet download speed test regularly to check my actual speed and base the percentage on that?
As a suggestion, it would be good if absolute values in Kb/s could be set for every option where a percentage is currently used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df445cda-3b0a-2ad7-e3cc-23e159013530
* Version Independent ID: a6bb5f97-d350-f7b7-77f7-b0093322289d
* Content: [Delivery Optimization reference](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization-reference#feedback)
* Content Source: [windows/deployment/update/waas-delivery-optimization-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-delivery-optimization-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @KC-Syd thank you for your questions. The [Windows Update Delivery Optimization and privacy](https://support.microsoft.com/help/4468254/windows-update-delivery-optimization-faq) article may provide some insight, particularly on the bandwidth usage, which at the moment utilizes percentage and dynamically adjusts based on what's set.

More information [here](https://docs.microsoft.com/windows/deployment/update/waas-delivery-optimization) - "You can use Delivery Optimization to reduce bandwidth consumption by sharing the work of downloading these packages among multiple devices in your deployment." Here's a rather interesting discussion on [TechNet](https://social.technet.microsoft.com/Forums/windows/en-US/b94d8e74-58de-451a-b137-7ec2028adc27/delivery-optimization-service-downloading-something-and-using-all-my-bandwidth?forum=win10itprogeneral).

> As a suggestion, it would be good if absolute values in Kb/s could be set for every option where a percentage is currently used.

For the above, I encourage you to submit your suggestion on [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). The Microsoft engineering team uses UserVoice feedback to learn what users are asking for or what they want to improve.

Also, please be informed that this Github site is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. If you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review. 

I hope the information I've provided will help. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hi again @KC-Syd, we didn’t hear back from you but we hope the information we've provided helped. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
