### ISSUE TITLE
White glove: device context user targeted apps

### ISSUE THREAD

**Issue by 3flex** [MicrosoftDocs/windows-itpro-docs#4584]
Doc says:

> Any apps (Win32 or LOB) that are configured to install in the device context and targeted to the user that has been pre-assigned to the Autopilot device will also be installed.

But Intune Windows 10 App Deployment doc (https://docs.microsoft.com/en-us/intune/apps-windows-10-app-deploy#installing-apps-on-windows-10-devices) says:

> If an app is deployed in device context and targeted to a user, the installation will fail

Not sure how to reconcile those statements?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5b57d1-61b3-39d4-34ff-d6dcb858c250
* Version Independent ID: 42609104-815f-9e7a-39aa-38d92cc910c9
* Content: [Windows Autopilot for white glove deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove)
* Content Source: [windows/deployment/windows-autopilot/white-glove.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/white-glove.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by nhogarth86** [comment]
I think its because if you assign the user to the device, it will install as part of the white glove process before the device is sealed. If you don't assign the user to the device, then it will install when the user first powers on the device after it has been installed during the enrollment status page in the user context (and then fail)

**Comment by jvsam** [comment]
Hello @3flex thanks for bringing this to our attention. What do you think about the information provided by @nhogarth86? Did it clarify this for you? If not, please provide more information. Also, if there is anything in this documentation that needs to improve, please let us know and we will submit it for review. Thanks and looking forward to hearing from you. 

Thanks for the assistance @nhogarth86!

**Comment by 3flex** [comment]
It's still confusing to read in Intune doc for win 10 app deployment that device context user targeted installs will fail, but the autopilot doc says that during autopilot white glove they'll succeed.

If that's the behaviour then ok, but since the two docs seem to contradict each other then there should be an explanatory note added because it's confusing otherwise.

**Comment by jvsam** [comment]
@3flex although if you will read the entire paragraph on this doc, part of the context is the pre-provisioning process which is what white glove is all about, which makes this different from the Intune doc. However, if you have any suggestion or a better messaging in mind, please let us know and we will submit it to the Microsoft author for review. Thank you.

**Comment by 3flex** [comment]
Thank you both. If each scenario works as described there's nothing to do here.

**Comment by jvsam** [comment]
You're welcome @3flex. Thank you again for taking the time to share your feedback and for being part of the Microsoft Docs community!
