### ISSUE TITLE
Update history missing for June and July 2019

### ISSUE THREAD

**Issue by danieldhudson** [MicrosoftDocs/windows-itpro-docs#4586]
Before the update page was moved to docs, details for June's CU were published which are missing from this page still. Also no update information has been given for July's CU (assuming of course there were Surface Hub specific updates).

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c83a996d-3a4e-33d4-82f9-f4112f42d6a1
* Version Independent ID: 69d3e586-1a9d-9a20-8ea0-54f356b5693a
* Content: [Surface Hub update history](https://docs.microsoft.com/en-gb/surface-hub/surface-hub-update-history)
* Content Source: [devices/surface-hub/surface-hub-update-history.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/surface-hub-update-history.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @v-miegge
* Microsoft Alias: **v-miegge**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@danieldhudson - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@danieldhudson - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by ducttapecoder-vt** [comment]
@mypil can you confirm that 1703 is the latest available for Surface Hub (Windows 10 Team)?

**Comment by danieldhudson** [comment]
Yes, 1703 is still the latest feature release available.
