### ISSUE TITLE
Run the script once every 30 days

### ISSUE THREAD

**Issue by ricky-lewis** [MicrosoftDocs/windows-itpro-docs#4595]
My question is why?

We assumed that once the script has been deployed and ran on a machine that it configured some kind of service or process in the background that will periodically report into the Analytics on azure (Certainly looks that way, as machines are showing recent LastScan dates that were deployed to weeks ago).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f029a728-1f53-4576-a6ca-8a19a92626e6
* Version Independent ID: 85f27ad5-84e2-0787-082f-59d2d66c99b5
* Content: [Upgrade Readiness deployment script (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-deployment-script#feedback)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-deployment-script.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-deployment-script.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thanks for your question @ricky-lewis! Here's an explanation from [Microsoft on their blog](https://blogs.technet.microsoft.com/askpfeplat/2018/07/02/deploying-upgrade-readiness-without-sccm/):

> We recommend using the deployment script and further recommend scheduling it to run monthly. Doing so ensures a full inventory is sent monthly and includes various tests to help alert you, through the Upgrade Readiness solution, to potential issues. This is frequently accomplished by creating a package in SCCM and deploying that package to your collection(s).

More information [here](https://docs.microsoft.com/windows/deployment/update/windows-analytics-get-started#automate-data-collection) regarding its impact on data collection.

> Schedule the Upgrade Readiness deployment script to automatically run monthly. Scheduling the script ensures that full inventory is sent monthly even if devices were not connected or had low battery power at the time the system normally sends inventory. Make sure to run the production version of the script, which is lighter weight and non-interactive. The script also has a number of built-in error checks, so you can monitor the results. If you can't run the deployment script at scale, another option is to configure things centrally via Group Policy or Mobile Device Management (MDM). Although we recommend using the deployment script, both options are discussed in the sections below.

And an interesting discussion in one of the [Tech Communities](https://techcommunity.microsoft.com/t5/Upgrade-Readiness/Clarification-on-Deploying-Upgrade-Readiness/td-p/181716).

I hope the information I've provided clarified this for you. Let me also get this over to the Windows content writing team for review and to suggest adding more details on this documentation. 

Thanks for being part of the Microsoft Docs community!

**Comment by ricky-lewis** [comment]
Hello,

Thank you for getting back to me so soon.

I'm still a little misty as to why the script has to be ran again after 30 days. Do the machines not regularly report into the analytics (We use Upgrade Readiness and Device Health) once the script has run? Or do you have to run the script every 30 days for this to happen?

We reason I'm confused about this is because when we first ran the script we had a number of machines reporting error code 63, which points to the telemetry reg value not being set to 2 or 3. We found this out about a week after the script had been run and fixed it with group policy. We thought we would have to re-deploy the script, but the machines starting to report in to analytics without us doing that.

**Comment by jvsam** [comment]
Hi again @ricky-lewis were you able to check the links that I've sent, including the Tech Community discussion? Like this comment from another user:

> It is the supported way to on-board machines to analytics as it makes sure that the machines are sending the telemetry also it performs some checks to make sure data is uploaded correctly. You can find more information in this article:
https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started#automate-da...
Without the script it sometimes can take weeks for machines to send data and you cannot guarantee all the machines will send data.

If you need more information, I would recommend the following:

1. [Technet forums](https://social.technet.microsoft.com/Forums/home) and the [Tech Community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities) where you can ask questions and interact with other users, experts and also Microsoft engineers.
2. [Contact Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) if you need immediate assistance.

Thank you.

**Comment by ricky-lewis** [comment]
Hello,

Ok I think that clears up the 30 script run reason. To confirm:

The script is run every 30 days to make sure machines report in even if they couldn't at the time the system would normally. Makes perfect sense to me now.

Finally, how should the script be set to run monthly?

**Comment by jvsam** [comment]
@ricky-lewis one of the links that I've provided contains deployment instructions, though without SCCM. But the instructions⁠—I would assume⁠—for adding recurring scheduled tasks are the same. Please check: https://blogs.technet.microsoft.com/askpfeplat/2018/07/02/deploying-upgrade-readiness-without-sccm/

Thanks.

**Comment by ricky-lewis** [comment]
Great stuff. Thanks for clarifying all this. Happy for this to be closed.

**Comment by jvsam** [comment]
You're welcome @ricky-lewis. Thanks for being part of the Microsoft Docs community!
