### ISSUE TITLE
Tiles / Tiles' groups overlay each other

### ISSUE THREAD

**Issue by mrfx** [MicrosoftDocs/windows-itpro-docs#4596]
Clean installation of Windows 10 (1903, 18362.239) and there are issues with full screen start menu. New tiles and tiles groups overlay each other and it cannot be fixed by drag & drop. Occasionally after close and reopen start menu then tiles positions are moved that not overlay each other anymore. I have dual screen setup: 4k 100% scale external display and 4k 200% built-in noteboook display.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00912925-8922-8c5e-fc36-d00fb992114c
* Version Independent ID: 1dd2bc12-d31b-dcd8-a2fb-c279adfa81a5
* Content: [Troubleshoot Start menu errors](https://docs.microsoft.com/en-us/windows/configuration/start-layout-troubleshoot#feedback)
* Content Source: [windows/configuration/start-layout-troubleshoot.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/start-layout-troubleshoot.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @mrfx thank you for bringing this to our attention. We're happy to assist you with your concern, however, this Github site is used as a feedback system to help improve the quality of the technical documentation. If the troubleshooting steps suggested in this doc did not fix the problem for you, we recommend that you open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance. You can also check related posts/conversations at the [Microsoft Tech community](https://techcommunity.microsoft.com/t5/forums/searchpage/tab/message?advanced=false&allow_punctuation=false&q=start%20menu) where you can ask questions and interact with other users, experts and also Microsoft engineers.

Please keep us posted here on the resolution, information or improvements that can be called out in the docs. We want users to have the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, relevant and up-to-date.

**Comment by jvsam** [comment]
Hi again @mrfx we didn’t hear back from you but we hope your issue has been resolved.  We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
