### ISSUE TITLE
MacOS onboarding status seems not matching between local machine and dashboard

### ISSUE THREAD

**Issue by ken5scal** [MicrosoftDocs/windows-itpro-docs#4606]
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac-install-with-jamf

says onboarding can be checked by a command `mdatp --health healthy`, and when the output is `1`, then it's not yet in the status of onboard.

However, my machine seems to be on board as it detects a detection test `curl -o ~/Downloads/eicar.com.txt http://www.eicar.org/download/eicar.com.txt`.

![image](https://user-images.githubusercontent.com/9734362/62342249-29b84080-b521-11e9-9341-ee650f0680eb.png)

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @ken5scal, to confirm the onboarding status, kindly check via the onboarding section of the Microsoft Defender Security Center. If it says onboarding is completed, then yes, you're good to go. If no machine is appearing in the machines list and there was no error in the onboarding process, this might indicate an onboarding or connectivity problem. I would suggest [reviewing the events and errors using Event Viewer](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/event-error-codes). More troubleshooting steps for onboarding issues are available [here](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-onboarding#troubleshoot-onboarding-issues-on-the-machine). 

The Microsoft Defender ATP for Mac is now in public preview and if you have feedback regarding the product, you can [submit it](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub) by opening Microsoft Defender ATP for Mac on your device or submit feedback via Microsoft Defender Security Center. 

**Note:** This Github site is used as a feedback system to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. If you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review. Thank you.

**Comment by jvsam** [comment]
Hi again @ken5scal I, just wanted to follow up if you were able to successfully onboard your machine? If  you are having problems, please check the links that I've provided. I will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
