### ISSUE TITLE
missing software

### ISSUE THREAD

**Issue by sebhe** [MicrosoftDocs/windows-itpro-docs#4607]
Is there a possibility to report missing software so that it gets detected and analyzed as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc646df4-fc3c-9a3d-7f17-b12777c4a659
* Version Independent ID: 1b37afc4-6615-e88a-d9d4-6cb29e26059e
* Content: [Software inventory](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/tvm-software-inventory)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/tvm-software-inventory.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/tvm-software-inventory.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by mypil** [comment]
@officedocsbot assign @mypil@officedocsbot assign @mypil

**Comment by mypil** [comment]
@sebhe - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello @sebhe ,
unfortunately no, it only can detect vulnerabilities for existing soft
Thank you

**Comment by mypil** [comment]
@sebhe  - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
