### ISSUE TITLE
Difference in behavior with on-premises AD and SSO O365 logon.

### ISSUE THREAD

**Issue by AlexAftanas** [MicrosoftDocs/windows-itpro-docs#4611]
When on a on-premises AD and the user is using O365 and you set the minimum password age setting to 1 or more then as an administrator you reset a password in AD and check "must change password at next logon" the behavior is different than what is listed on this page.

The behavior is that a user authenticating through O365 still is limited by the minimum password age setting. In other words the O365 user will need to wait a day before resetting the password if the minimum password age is 1 day. Even if the admin checks the "must change password at next logon" when resetting the password.  This is different than what is indicated on this page: 
"If you set a password for a user and you want that user to change the administrator-defined password, you must select the User must change password at next logon check box. Otherwise, the user will not be able to change the password until the number of days specified by Minimum password age."

Again this behavior is when there is a on-premises AD using SSO with O365 and the user is logging in through O365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f30760-4999-dcb1-26da-097477dc31bc
* Version Independent ID: 6cef6a81-a4aa-bb3b-4f1c-78cf98aba958
* Content: [Minimum password age (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/minimum-password-age#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/minimum-password-age.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/minimum-password-age.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thanks for creating this issue via the feedback section of the docs @AlexAftanas. I closed #4609 since it's a duplicate of this. What I will do is to forward this to the Windows content writing team to suggest adding a note in this documentation that if there's a minimum password age set, user will not be able to change the password until it reaches the specified age (applicable to on-premises AD using SSO; using O365).

We really appreciate your feedback @AlexAftanas and thank you for being part of the Microsoft Docs Community and for helping improve the quality of the technical documentation!

**Comment by joinimran** [comment]
Hello @AlexAftanas , Thank you for your feedback. Can you please confirm if your user is log in to windows using Office365 account? 

When there is SSO enabled and you changed the user password from AD it gets synced and timeouts the users to forcefully re-login. 

Thanks.

**Comment by jvsam** [comment]
Hi again @AlexAftanas thank you so much for your patience and feedback. Please be informed that the documentation has been updated to include more details about the *Minimum password age policy setting*. We will now close this issue, but please continue to send your feedback and suggestions to help improve the quality of the technical documentation of Microsoft Docs. Thank you for being part of the community!

**Comment by jvsam** [comment]
@officedocsbot close
