### ISSUE TITLE
Diagnostic Logs

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/windows-itpro-docs#4614]
Please improve the instructions for collecting diagnostic logs: "Diagnostic logs can be gathered from the device, and then it can be reset to start the process over again."

Read in the comments that this involves selecting "View Diagnostics" &gt; inserting a USB drive &gt; selecting the USB drive &gt; selecting "Select Folder" and it copies these diagnostic files in the background. 

Wish there was some sort of visual indication that the logs had completed copying, but that's more feedback for the product team than anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5b57d1-61b3-39d4-34ff-d6dcb858c250
* Version Independent ID: 42609104-815f-9e7a-39aa-38d92cc910c9
* Content: [Windows Autopilot for white glove deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove)
* Content Source: [windows/deployment/windows-autopilot/white-glove.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/white-glove.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by pyoungberg** [comment]
Collecting logs didn't work for me so I'm going to open a support case, but the instructions could be clearer - thanks!

**Comment by jvsam** [comment]
Hello @pyoungberg thank you for your feedback. There is a related documentation on this topic (_See TOC on the left side_) on [Troubleshooting Windows Autopilot](https://docs.microsoft.com/windows/deployment/windows-autopilot/troubleshooting) that contains instructions in viewing event log entries including registry and ETW trace options. You may also use Windows [MDM Diagnostics Tool](https://docs.microsoft.com/windows/client-management/mdm/diagnose-mdm-failures-in-windows-10) which can gather Windows Autopilot related events. 

We always strive to improve the quality of the technical documentation of Microsoft Docs, so what specific instructions or information do you want to see added to the docs? If you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review. Thank you.

**Comment by jvsam** [comment]
Hi again @pyoungberg, we didn’t hear back from you but we hope you were able to contact Support and resolve whatever issues you may have. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by ang216** [comment]
Please reopen this, there is no clear documentation in this article or any of the articles in the previous comment indicating a USB drive is required to pull diagnostic logs.

**Comment by illfated** [comment]
@ang216 : if you are invested in this issue, I would recommend opening a new ticket on the page, https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove#feedback , to start a new conversation (unless you have got specific suggestions on how to improve the documentation page based on the existing comments in this ticket).

**Comment by pyoungberg** [comment]
Here's some followup on what I've been doing as a workaround, for those that are interested:
If you'd like to grab logs > Shift+F10 will give you a CMD prompt > type 'eventvwr' to launch Event Viewer > go to Apps and Service Logs/Microsoft/Windows/ModernDeployment-Diagnostics-Provider > from here you can get some good info on why things might have failed. 

If troubleshooting post-WhiteGlove provisioning or just regular Autopiloting: I also recommend using the CMD window to open up an 'explorer.exe' shell and checking the netsetup.log file under C:\Windows\debug. My man Anoop posted a pretty good guide for troubleshooting all kinds of hybrid Autopilot errors here as well: https://www.anoopcnair.com/windows-autopilot-hybrid-azure-ad-join-trouble/

**Comment by illfated** [comment]
@MaratMussabekov : Since you have answered some questions and made some Pull Requests regarding similar topics, does the feedback above look useful in such a way that it can be used to improve the related documentation page?

**Comment by MaratMussabekov** [comment]
hello @illfated , @pyoungberg ,
in my opinion, feedback above is very useful.
may be links to the following articles could be added as well:
[Diagnose MDM failures in Windows 10](https://docs.microsoft.com/windows/client-management/mdm/diagnose-mdm-failures-in-windows-10)
[Troubleshooting Windows Autopilot](https://docs.microsoft.com/windows/deployment/windows-autopilot/troubleshooting)
What do you think?
Thank you

**Comment by illfated** [comment]
I am all for it. Anything that can be done to improve the current documentation, especially when users have provided feedback about missing or incorrect content, is a welcome change in my book. Feel free to suggest how it needs to be phrased in any upcoming Pull Request to add the content.
