### ISSUE TITLE
RDP to AAD-joined PC from non-joined PC

### ISSUE THREAD

**Issue by nickwalkmsft** [MicrosoftDocs/windows-itpro-docs#4616]
I'm looking for a couple things related to RDPing to an AAD-joined remote computer from a local computer that is not joined to AAD or any domain:

1. https://morgansimonsen.com/2015/11/06/connecting-to-an-azure-ad-joined-machine-with-remote-desktop/ has pretty old instructions about RDPing to an AAD-joined machine. It looks like things have improved since then, except for the scenario where the local computer is not AAD-joined. In that case, those instructions appear to still be the only way you can make it work. It requires disabling the NLA requirement on the remote machine and setting `enablecredsspsupport:i:0` in the RDP file. Can anyone confirm that this is still the only way to connect in this scenario? I'd prefer to re-enable NLA if I could.
2. Either way, can content be added to this page addressing this scenario that either explains how to do it or declares that it's unsupported?

#3866 had the same topic as this but was closed without a resolution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @Dansimp I believe you own this topic so I am tagging you here. Kindly see @nickwalkmsft's feedback. Is this something that can be incorporated to this doc? Or do you want me to ask someone from the team to create a pull request to include the suggestions? Looking forward to hearing from you. Thank you.

**Comment by jvsam** [comment]
> Either way, can content be added to this page addressing this scenario that either explains how to do it or declares that it's unsupported?

Hello again @Dansimp I just want to follow-up if you had a chance to look into this and if changes need to be made on the content as per the information provided? Thank you.

**Comment by celeroll** [comment]
I think it is very important to add the scenario described in the first post. Here is also a good description.
Especially the part if you want to join from WORKGROUP computer.
https://www.niallbrady.com/2017/08/23/how-can-i-rdp-to-an-azure-ad-joined-windows-10-device/

**Comment by jvsam** [comment]
Thank you for sharing that reference link @celeroll. This is currently under review and we will update the status of this issue soon.

**Comment by CpBobette** [comment]
It seems the initial setup of windows has an impact on the ability to use RDP. I have 2 machines, once setup exclusively using AAD (machine 1) and the other one added later on to the Directory (machine 2). 
I can RDP, using my AAD logins, from machine 1 to machine 2 without any issues, but the other way around requires the little hacks mentioned earlier. I looked into Windows Defender Credential Guard but it's not turned on.

**Comment by jvsam** [comment]
Hello again @nickwalkmsft, thank you for your patience. Please be informed that the suggested updates to this documentation as per your feedback (See pull request #5344) have already been merged. Please expect the changes to be displayed here at docs.microsoft.com in the next scheduled publishing run. 

Again, thank you for your feedback!

**Comment by jvsam** [comment]
Hi @CpBobette, we believe in your case, it will be best to contact [Windows 10 Support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) to get immediate assistance. There are also other support resources that you can explore like the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can post your question and get help from the community.

Kindly keep us informed if you find any relevant information that can be incorporated into this documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by awakecoding** [comment]
Any chance of actually getting a good solution to this problem? I've been searching for a way to connect to an AAD-joined PC *without* resorting to disabling NLA. It's great that additional security can be enforced in such cases, but the requirements are too restrictive for a lot of use cases, which is why all you can find online are blogs on how to "Connect to an Azure AD joined PC" where the first step is to flat out disable NLA as the "solution". Ok, it works if I disable NLA, but then can we get better security than that? NLA was there was a reason, it's not made to be disabled.

**Comment by illfated** [comment]
@awakecoding : You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The MS Docs team members might not have time to answer your question, unless this is something they would want to add to the existing documentation.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

Try the following resources to get in touch with users who might be able to help you :
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/
