### ISSUE TITLE
Prompt for consent on secure desktop domain policy is failing to override locally applied 1809 baseline

### ISSUE THREAD

**Issue by havealoha** [MicrosoftDocs/windows-itpro-docs#4619]
A domain gpo is set to prompt for consent on the secure desktop. The 1809 security baseline is applied as a local gpo with the -domainjoined argument. The domain policy is not overriding the local policy. This is LTSC 1809.

https://blogs.technet.microsoft.com/secguide/2018/11/20/security-baseline-final-for-windows-10-v1809-and-windows-server-2019/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71477b24-bdbd-489d-9919-96ed8e534898
* Version Independent ID: 67f985b1-90d5-7c68-9ec9-6b65055adc72
* Content: [User Account Control Behavior of the elevation prompt for administrators in Admin Approval Mode (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-account-control-behavior-of-the-elevation-prompt-for-administrators-in-admin-approval-mode#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/user-account-control-behavior-of-the-elevation-prompt-for-administrators-in-admin-approval-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/user-account-control-behavior-of-the-elevation-prompt-for-administrators-in-admin-approval-mode.md)
* Product: **ws10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @havealoha based on the information you have provided, the best course of action is to [contact Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) to get immediate assistance. Also, the TechNet article has been migrated to [Tech Community](https://techcommunity.microsoft.com/t5/Microsoft-Security-Baselines/Security-baseline-FINAL-for-Windows-10-v1809-and-Windows-Server/ba-p/701082) and I suggest that you post the question in there to communicate directly with the author.

I am sorry but that's all the assistance we can provide at this time. Please note that this Github site is used as a feedback system to help improve the quality of the technical documentation. If you have suggestions or ideas to make the docs better, you can open an issue on a specific content page by using the feedback feature so it can easily be tracked.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hi again @havealoha, we hope you were able to contact support and resolve your concern. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation. We always strive to give users the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, accurate and up-to-date. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
