### ISSUE TITLE
Information regarding update of LOB apps through offline licensing distribution

### ISSUE THREAD

**Issue by madhuramehendalewhatfix** [MicrosoftDocs/windows-itpro-docs#4625]
Are offline licensed apps updated automatically, or the updates need to explicitly pushed. If they do get updated, do they need to access to just Microsoft store or specifically to the private store in which the extension was published. How long does the update take? What happens if the update is pushed only to certain stores. Please provide information regrading these points.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@madhuramehendalewhatfix - May we know which Microsoft document link you used in reference to this issue?

Please share it with us so we can investigate further. Thank you.

**Comment by madhuramehendalewhatfix** [comment]
https://docs.microsoft.com/en-us/microsoft-store/distribute-offline-apps

**Comment by mypil** [comment]
@madhuramehendalewhatfix - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @madhuramehendalewhatfix Thank you for your query. Please note the following.

Offline license files do not get updated automatically. Devs need to push the updates. There are multiple methods to update the files see sections https://docs.microsoft.com/en-us/microsoft-store/distribute-offline-apps#download-an-offline-licensed-app

Update duration depends on the update settings you have setup for your app. Once app update is available in store, you can update the app.

If the update is pulled for certain stores it will only be available to those stores.

Regards,
Imran.

**Comment by madhuramehendalewhatfix** [comment]
@joinimran thanks alot for the response. I just have one more query regarding LOB apps, if I push an update to a specific private store(even though the app has been published to other stores), it is visible only to that specific store right?
If that's true, we recently had an incident where the it was pushed to other stores as well, could you direct me to a place where I would get some support regarding the issue faced.

**Comment by joinimran** [comment]
Thanks for your reply, 

@mypil Please guide @madhuramehendalewhatfix how a support case can be open so that the support team can address the issue. 

Regards

**Comment by mypil** [comment]
@madhuramehendalewhatfix - You can open a service ticket so this can get resolved ASAP. Based on outcome let us know if it is something that can be called out in the documentation.

Please follow this link to contact support for Windows 10 products:
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you do find that it is a documentation error,  please do not hesitate to comment back and we'll gladly look into fixing it. Thank you!

**Comment by mypil** [comment]
@officedocsbot close
