### ISSUE TITLE
Clarify Documentation

### ISSUE THREAD

**Issue by BigHatte** [MicrosoftDocs/windows-itpro-docs#4634]
Is this Configuration applied each user logon or only once. So if the User makes some Changes to his default configuration are they overwritten next logon by policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cbbc03b-78ac-4464-0ec8-d7379db167f4
* Version Independent ID: 6188559c-859b-77b7-8fd7-ae4bd59c06b8
* Content: [Set the default browser using Group Policy (Internet Explorer 11 for IT Pros)](https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/set-the-default-browser-using-group-policy#feedback)
* Content Source: [browsers/internet-explorer/ie11-deploy-guide/set-the-default-browser-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/internet-explorer/ie11-deploy-guide/set-the-default-browser-using-group-policy.md)
* Product: **ie11**
* Technology: **internet-explorer**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@BigHatte  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@BigHatte , Thank you for your query, Please note that if the user has changed the default settings, those will be overwritten on next logon.

Regards,
Imran.

**Comment by mypil** [comment]
@officedocsbot close
