### ISSUE TITLE
GP Settings Combinations

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/windows-itpro-docs#4637]
How do these settings interact with the much older GP settings of: 
System/Internet Communication Management/Internet Communication settings &gt; "Turn off access to all Windows Update features".

and also newer:
System/Specify settings for optional component installation and component repair &gt;
"Download repair content and optional features directly from Windows Update instead of Windows Server Update Services (WSUS)"
 
Is there a combination of the old & new, plus this pages Windows settings that let's you specify use the internal WSUS Server for the list of what to install but you can use WSUS or Windows Update to get the updates?  i.e don't just go ahead and grab 1903 from the internet but you can get the "client-side targeting policy list of approved updates" from either WSUS or Windows Update?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efb8dfd-971e-7257-f8b7-f80843989eb8
* Version Independent ID: d7808728-bb89-a06e-a103-ec1c74682f64
* Content: [Manage additional Windows Update settings (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-wu-settings)
* Content Source: [windows/deployment/update/waas-wu-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-wu-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @mattatmsft, I believe the best way to get your questions answered quickly is to contact [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10), unless you have concerns regarding the accuracy of this documentation? 

You can also check the [Technet forums](https://social.technet.microsoft.com/Forums/home) and the [Tech Community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities) where you can ask questions and interact with other users, experts and also Microsoft engineers.

> Is there a combination of the old & new, plus this pages Windows settings that let's you specify use the internal WSUS Server for the list of what to install but you can use WSUS or Windows Update to get the updates? i.e don't just go ahead and grab 1903 from the internet but you can get the "client-side targeting policy list of approved updates" from either WSUS or Windows Update?

For the above questions, please check the following resources, they may help.

- [Demystifying “Dual Scan”](https://blogs.technet.microsoft.com/wsus/2017/05/05/demystifying-dual-scan/)
- [Improving Dual Scan on 1607](https://blogs.technet.microsoft.com/wsus/2017/08/04/improving-dual-scan-on-1607/)
- [Using ConfigMgr With Windows 10 WUfB Deferral Policies](https://techcommunity.microsoft.com/t5/Configuration-Manager-Archive/Using-ConfigMgr-With-Windows-10-WUfB-Deferral-Policies/ba-p/274278)
- [Windows 10 Updates and Store GPO behavior with DualScan disabled and SCCM SUP/WSUS managed](https://blogs.technet.microsoft.com/swisspfe/2018/04/13/win10-updates-store-gpos-dualscandisabled-sup-wsus/)

Again, if there is any relevant information that can be incorporated to this documentation, please keep us informed here and we will be happy to assist. This Github site's main goal is to help improve the quality of the Microsoft docs. Thank you.

**Comment by jvsam** [comment]
Hello again @mattatmsft, we will now close this issue since it's similar to #4645 which will remain open until we get feedback from the doc author or, if you've already contacted Support and you have information that is relevant or can be called out on this documentation, please reopen this issue or you can also add that update on #4645. Thank you again.

**Comment by jvsam** [comment]
@officedocsbot close
