### ISSUE TITLE
Delivery Optimization

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/windows-itpro-docs#4638]
May want to include some language around Delivery Optimization in the case that updates are pulled from HTTPS endpoint (internet).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cfd6413-90f7-040b-04be-9662ddfac827
* Version Independent ID: 1b931a7c-deb3-6384-0c3b-3492fd720b6f
* Content: [Best practices - deploy feature updates during maintenance windows](https://docs.microsoft.com/en-us/windows/deployment/update/feature-update-maintenance-window)
* Content Source: [windows/deployment/update/feature-update-maintenance-window.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/feature-update-maintenance-window.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you so much for your feedback @SLeuthold! Do you have specific suggestions when it comes to messaging so we would know what you wish to *see/read* about [Delivery Optimization](https://docs.microsoft.com/windows/deployment/update/waas-delivery-optimization)? Is it about enabling it to reduce Internet bandwidth and speed up the downloads or how it works in general? Or just adding a note with overview and outgoing link? On my end, I will get this over to the Windows content writing team, but we also want to make sure we have a clear understanding of your request. 

We appreciate you taking the time to share your feedback and for helping improve the quality of the technical documentation!

**Comment by SLeuthold** [comment]
Hi @jvsam ! In the enterprise, content delivery optimization via caching and peering solutions is imperative to mitigate the risk of interrupting business operations. It is important when downloading large payloads from the cloud (feature updates, quality updates, etc.) Most smaller organizations may have this enabled by default but larger enterprises may need to plan an implementation to logically group different sites via AD Site or SCCM boundary group as the egress/ingress point may be a data center in another location rather than an internet connection local to them. Otherwise they will peer with clients potentially not in the same physical location.

**Comment by jvsam** [comment]
Thanks for your valuable input @SLeuthold! @nenonix kindly take note of Stephen's suggestion.

**Comment by illfated** [comment]
Seeing no follow-up here, I would like to volunteer my time to write a PR for added the suggested text.
May I have some recommendation as to where on the page adding the text will be most suited?

**Comment by jvsam** [comment]
Hi @illfated sure, it has been assigned but if you have time, please go ahead. As to where, it depends on the context, step 3? As always, appreciate the assistance.

**Comment by jvsam** [comment]
Hi @SLeuthold, please be informed that the pull request (See PR #5120) that contains your suggestion has been approved and merged. The update will be displayed here at docs.microsoft.com ([Deploy feature updates during maintenance windows](https://docs.microsoft.com/windows/deployment/update/feature-update-maintenance-window)) in the next scheduled publishing run. Thank you again for your feedback and for being part of the Microsoft Docs community!
