### ISSUE TITLE
Quick Access not in Navigation Pane. Is this intended?

### ISSUE THREAD

**Issue by MStormW** [MicrosoftDocs/windows-itpro-docs#4642]
Hi, we have set up 2 shared pc's in our organization and our users are complaining that the Quick Access is no longer available in the Navigation Pane of Explorer. Is this intended? I have found that Quick Access is in fact still there, if you have set Explorer to open to Quick Access, you can still get there. But for some reason it is no longer visible in Navigation Pane. This feels like a bug to me. I have tried several combinations of shared pc settings but none have made Quick Access reappear in Navigation Pane. Also the multitude of "Quick Access fixes" (registry edit: adding HubMode) to be found on the Internet do not help. Hope someone can clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14b376e2-39bd-faca-a76c-dd21bad8d8fd
* Version Independent ID: a76cabb0-59b9-7e97-6603-eec7d37f1fd4
* Content: [Set up a shared or guest PC with Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/set-up-shared-or-guest-pc#feedback)
* Content Source: [windows/configuration/set-up-shared-or-guest-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/set-up-shared-or-guest-pc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for bringing this to our attention @MStormW. We're happy to assist you with your concern, however, this Github site is used as a feedback system to help improve the quality of the technical documentation. We recommend that you open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance, or you can also check related posts/conversations at the [Technet forums](https://social.technet.microsoft.com/Forums/home) and the [Tech Community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities), where you can ask questions and interact with other users, experts and also Microsoft engineers.

Here are also some links that you can check, hopefully they can help or provide more troubleshooting information.

- [Quick Access not working in Windows 10](https://answers.microsoft.com/windows/forum/all/quick-access-not-working-in-windows-10/f63e9ce8-4ea4-4551-866d-d16a9c93ca24)
- [How do I repair corrupt Quick Access?](https://answers.microsoft.com/windows/forum/windows_10-files/how-do-i-repair-corrupt-quick-access/713331d2-e01e-4fef-87fe-e19703ec9860)
- [Use the System File Checker tool to repair missing or corrupted system files](https://support.microsoft.com/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system)

Please keep us posted here on the resolution, information or improvements that can be called out in the docs. We want users to have the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, relevant and up-to-date.

**Comment by illfated** [comment]
I have not looked up any proof of this yet, but Quick Access is a personal user feature and not a shared environment feature. Note that in some scenarios, accounts will be automatically deleted and re-created on login (Guest account and Kiosk Mode), so Quick Access will be pretty empty for each user logging in. Also, from a privacy viewpoint, it is better not to focus on what other people before you have been working on or doing, unless you are a sysadmin, who will already know how to track changes on the computer by using other tools.

**Comment by MStormW** [comment]
> I have not looked up any proof of this yet, but Quick Access is a personal user feature and not a shared environment feature. Note that in some scenarios, accounts will be automatically deleted and re-created on login (Guest account and Kiosk Mode), so Quick Access will be pretty empty for each user logging in. Also, from a privacy viewpoint, it is better not to focus on what other people before you have been working on or doing, unless you are a sysadmin, who will already know how to track changes on the computer by using other tools.

Thanks for your reply. I suspect the same, but also have not been able to find any more detailed documentation about this than what is on docs.microsoft.com. The shared computer is not behaving as I was hoping it would, so I will stop using it altogether. It was never my intention to have userprofiles automatically deleted (I did not enable the account management and storage cleanup options), just to have a PC that is used by a small group of users because it has one shared application. The power policies and fast sign in would have been nice. I still wanted them to have their normal named profiles, but I found out now that that is not possible with this feature.

Also for anyone considering using it, beware, there is no easy going back from it in my experience. You can only set it back to not configured, but unfortunately this does not undo most of the settings, users will still be logged in with defaultuser10000x in stead of their normal userprofiles. So I'm afraid I will have to re-image these computers.

**Comment by jvsam** [comment]
> Note that in some scenarios, accounts will be automatically deleted and re-created on login (Guest account and Kiosk Mode), so Quick Access will be pretty empty for each user logging in. 

Thanks for that information @illfated.

@MStormW, we always strive to improve the quality of the technical documentation of Microsoft Docs (*including information architecture*). I don't have a complete understanding of what you want to do but if you are planning on deploying a kiosk, you may also want to look at the [Deployment](https://docs.microsoft.com/windows/deployment/) docs, specifically related to [Windows Autopilot](https://docs.microsoft.com/windows/deployment/windows-autopilot/windows-autopilot). I hope you'll be able to find the right configuration for your environment. Thanks.

*Note*: Some of the deployment docs are currently being updated.

**Comment by jvsam** [comment]
Hello again @MStormW, we didn’t hear back from you. We hope you were able to resolve any issues you may have. Please let us know if you have feedback specific to this documentation, otherwise, I believe we can close this issue. Looking forward to hearing from you. Thank you.

**Comment by MStormW** [comment]
Issue can be closed, thanks all that replied.

**Comment by illfated** [comment]
Fair enough. This is a problematic topic where some of the end user questions can not be answered other than from personal experience.
