### ISSUE TITLE
Enterprise Mode doc needs review 

### ISSUE THREAD

**Issue by andrefboliveira** [MicrosoftDocs/windows-itpro-docs#4643]
Enterprise Mode documentation needs review. It needs to be checked what tags are available in what  Windows version.
Pull request bellow was merged without checking.

----
Hi @AndreaBarr 
This should not have been merged without checking the issues raised in the comment section.
It seems that only the "allow-redirect" is available on Windows 10 versions greater than v1709.

It is not the same for the other tags.
This page needs be revised by the engineering team, to make sure that availability of every tag is clear.

@e0i and @lomayor can you help review the change?

Thanks in advance.

_Originally posted by @andrefboliveira in https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4248#issuecomment-518015887_

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @andrefboliveira since this is related to a pull request that was merged (#4248), I recommend that you continue the discussion on the PR page. Reverting a pull request will need to be done by the author or specific people from Microsoft with the appropriate access. Thanks for understanding.

**Comment by jvsam** [comment]
Hi @martyav I hope all is well. I'm wondering if you can help with this? Please refer to #4248. Appreciate the help, thank you.

**Comment by e0i** [comment]
@officedocsbot assign @e0i
