### ISSUE TITLE
Is there any way to retrieve the initiated anti virus scan results? 

### ISSUE THREAD

**Issue by bakatzir** [MicrosoftDocs/windows-itpro-docs#4649]
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b874bba7-6480-e24c-a25c-ff1f2c8b3187
* Version Independent ID: 558bb983-0a1f-d477-bb59-bc880ef0492e
* Content: [Run antivirus scan API](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/run-av-scan#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/run-av-scan.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/run-av-scan.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
Do you mean "retrieve anti virus scan results, either Successful or Failed"?
- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/get-machineactions-collection#http-request

**Comment by bakatzir** [comment]
@illfated
Yes, but preferably more data.

Let me elaborate on the customer use case.
an analyst investigates a possibly infected endpoint. So he want to:
1.initate an av scan in atp via demisto
2.be able to get the scan status finished/failed/pending
3. When finished, get dome data from the scan. If endpoint is ok - great. If not, malicious hashes/processes/yara signatures, whatever the scan found and can be used to further investigate the threat.

Thanks for the swift reply,
Bar.

**Comment by illfated** [comment]
Very well, fair enough. Please be advised that this site is primarily for improvement of the Microsoft IT-pro Docs documentation pages, meaning that the primary task is to find out if the docs pages can be improved by editing, changing or adding missing information to the pages. This question needs feedback from someone who is more experienced in the topic than I am (maybe @MaratMussabekov ?), and if the question gets its answer, it will be very useful to find out if this is something that should be documented in this page (or any other directly related page).

**Comment by jvsam** [comment]
Thanks for sharing that @illfated.

@bakatzir I am not 100% sure if this will address your use case but this blog contains good information in running anti-virus scans and collecting data. 

- [Automating Security Operations Using Windows Defender ATP APIs with Python and Jupyter Notebooks](https://techcommunity.microsoft.com/t5/Microsoft-Defender-ATP/Automating-Security-Operations-Using-Windows-Defender-ATP-APIs/ba-p/294434)

Now, if you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review. Thank you.

**Comment by bakatzir** [comment]
@illfated @jvsam
I might've posted in the wrong site then.
We have reviewed the docs, and were missing the functionalities i listed above in the API.
What do I need to do in order to submit our customer's request to the development queue?

Would appreciate your guidance.

**Comment by illfated** [comment]
Not sure if you "posted in the wrong site" as such, this could be useful if there is a chance that the documentation page needs more information to solve your type of issue, depending on if it is a common enough case for most users of Microsoft Defender ATP. Any feedback you can give to what would be expected in this documentation page, if it is the correct place for that information, would be helpful for the docs team.

To resolve your issue, I recommend that you check out the link posted by @jvsam above as well as consider contacting the Microsoft Support tenant for ATP in your area to get any useful suggestions on how to proceed, then post any related feedback here when your problem has been resolved.

**Comment by jvsam** [comment]
@bakatzir just to add, in case the feature or functionality you are looking for is not yet available, I encourage you to submit your suggestion on [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). The Microsoft engineering team uses UserVoice feedback to learn what users are asking for or what they want to improve.

Let me know if you need assistance with anything else, otherwise, we can close this issue. Thank you.
