### ISSUE TITLE
Key Trust and Remote Desktop with Biometric 

### ISSUE THREAD

**Issue by alevere** [MicrosoftDocs/windows-itpro-docs#4652]
Just checking to see if there is a plan for supporting the topic above. See https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-guide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a146880-235b-a69c-3e9d-a3fa56a25389
* Version Independent ID: c2c226b4-17ef-8888-9e1b-e20cf3273c3a
* Content: [Windows Hello for Business Features](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-features#remote-desktop-with-biometrics)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-features.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @alevere, thanks for your inquiry. At the moment, remote desktop with biometrics feature only works with certificate trust deployments (see: [Remote Desktop with Biometrics](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-features#remote-desktop-with-biometrics)). But I do encourage you to submit your suggestion on [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). The Microsoft engineering team uses UserVoice feedback to learn what users are asking for or what they asked to improve

Also, this Github site is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. If you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review. Thank you.

**Comment by alevere** [comment]
Thanks Jo
________________________________

**Comment by jvsam** [comment]
You're very much welcome @alevere! I will now close this issue. Thanks for being part of the Microsoft Docs community.

**Comment by jvsam** [comment]
@officedocsbot close
