### ISSUE TITLE
correction of necessary diagnostic data level

### ISSUE THREAD

**Issue by tgrisel** [MicrosoftDocs/windows-itpro-docs#4656]
https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/What-s-new-in-Windows-Update-for-Business-in-Windows-10-version/ba-p/622064 :
"Beginning with Windows 10, version 1903, Windows Update for Business no longer requires a diagnostic data level of Basic or higher to enforce configured policies. Instead, privacy-sensitive organizations can utilize Windows Update for Business policies, regardless of the diagnostic data level chosen, for any devices running Windows 10, version 1607 or later."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1684b30a-3187-85ce-0cf7-10d1b8298b7f
* Version Independent ID: 9b7170fc-2b39-8e46-7898-894a45de8623
* Content: [Configure Windows Update for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-configure-wufb)
* Content Source: [windows/deployment/update/waas-configure-wufb.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-configure-wufb.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
Would it be practical to expand the existing note bubble to include the 1903 specific change, maybe even changing the word "Important" to "Note",
to indicate that there are differences between 1903 and previous versions? Is it reasonable to presume that the 1903 info should precede the existing?

![image](https://user-images.githubusercontent.com/38162891/62757806-b8c2dc80-ba7c-11e9-9c25-b63d53793e8d.png)
https://docs.microsoft.com/en-us/windows/deployment/update/waas-configure-wufb

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
Thanks to @PatCat-MSFT & @jaimeo for the PR #4644 and its commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/798241bf01d4a735990513ece647fb7cbb9ab3ce .

**Comment by jvsam** [comment]
Awesome, thanks for linking that @illfated!

Hi @tgrisel, the pull request (see #4644) that clarifies the changes to diagnostic data requirements has been merged and will be displayed at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
