### ISSUE TITLE
Page outdated

### ISSUE THREAD

**Issue by kimoppalfens** [MicrosoftDocs/windows-itpro-docs#4660]
May I suggest taking this page offline and redirecting it to the SCCM page, as the onboarding wizard already does that? This page is hopelessly outdated and no longer aligns with the actual procedure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c500256-8bbd-fe0c-32e3-c3193652e5cd
* Version Independent ID: 838f93f8-7e0f-e693-f7cf-eac1569f75c8
* Content: [Onboard Windows 10 machines using System Center Configuration Manager](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-sccm#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-sccm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-sccm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@kimoppalfens - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by kimoppalfens** [comment]
Joyce,

You’re welcome. The least I can do in return for the trial subscription.

Best,
Kim

**Comment by joinimran** [comment]
@kimoppalfens Thank you for your feedback, can you please share the link of the page you are referring to. So that we can setup redirection or note in this doc.

Regards
Imran

**Comment by kimoppalfens** [comment]
This is the url in question.
https://docs.microsoft.com/en-us/sccm/protect/deploy-use/windows-defender-advanced-threat-protection

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mypil** [comment]
@kimoppalfens - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by alexverboon** [comment]
The content of this page is definitely outdated and should be updated, especially since recently configmgr updated it's built-in Windows ATP policy wizards.
