### ISSUE TITLE
In hybrid deployment: Win10 Pro + Key trust model ≠ PIN-reset feature... If on W10 Pro, you need to implement Cert trust model to use the PIN-reset feature...!

### ISSUE THREAD

**Issue by greytone** [MicrosoftDocs/windows-itpro-docs#4662]
This table above, and the planning guide (https://docs.microsoft.com/sv-se/windows/security/identity-protection/hello-for-business/hello-planning-guide), should include the (important) detail that it is a pre-requisite, in hybrid deployments with the key-trust model, to have Win 10 Enterprise to be able to use the PIN-reset feature. As I understand, you will not be able to use PIN-reset at all if you use Win 10 Professional and have deployed the key-trust-model in a hybrid deployment... Quite important information when choosing trust model for the hybrid deployment.

That´s anyway my understanding of the answer in the FAQ to the question "What is the difference between non-destructive and destructive PIN reset?", https://docs.microsoft.com/sv-se/windows/security/identity-protection/hello-for-business/hello-faq. To break it down it says:
Windows 10 Enterprise in hybrid deployment (Key and Cert trust model): non-destructive PIN-reset
Windows 10 Professional in hybrid deployment: only destructive PIN reset (which requires Certificate trust model)

If that is correct I suggest that you update the information when choosing trust-model.

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 87e5f5f1-16cf-57e2-bdfc-b090d90437b1
* Version Independent ID: 1662c47f-12cb-147d-25f0-dee98b6c7722
* Content: [Windows Hello for Business (Windows 10)](https://docs.microsoft.com/sv-se/windows/security/identity-protection/hello-for-business/hello-identity-verification#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-identity-verification.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-identity-verification.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for your feedback @greytone. Yes, the [Microsoft PIN Reset service only works with Windows 10, version 1709 or later Enterprise Edition](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-features#pin-reset). The feature does not work with the Pro edition and it's only applicable for hybrid deployments as of this time (*non-destructive PIN reset*). From the [FAQ](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-faq#what-is-the-difference-between-non-destructive-and-destructive-pin-reset), hybrid deployments also support destructive PIN reset but can only work for certificate trust model. But overall, hybrid deployment supports both [Certificate trust](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs) and [Key trust](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs)

For on-premises deployments using Windows 10, version 1709, Professional, users can reset forgotten PINs either through the settings page or from the user's lock screen (*destructive PIN reset*). 

More information [here](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-videos#windows-hello-for-business-forgotten-pin-user-experience):

> For on-premises deployments, devices must be well connected to their on-premises network (domain controllers and/or certificate authority) to reset their PINs. Hybrid customers can on-board their Azure tenant to use the Windows Hello for Business PIN reset service to reset their PINs without access to their corporate network.

What I'd like to clarify is with regard to your suggestion. Is this the correct page where the information should be added? The [Windows Hello for Business](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-identity-verification) content page displays the deployment requirements and there are other sub-topics that talk about Windows Hello features including PIN reset. Thank you for the clarification.

**Comment by jvsam** [comment]
> What I'd like to clarify is with regard to your suggestion. Is this the correct page where the information should be added? The Windows Hello for Business content page displays the deployment requirements and there are other sub-topics that talk about Windows Hello features including PIN reset. Thank you for the clarification.

Hello again @greytone, I just want to follow-up if you have suggestions related to the contents of this specific doc? If so, can you please let us know what is it so we can submit it for review? If it pertains to another documentation, I would recommend going directly to the actual content page and submit the feedback from there for easy tracking.

![image](https://user-images.githubusercontent.com/18371314/63476937-6b4f6200-c4b5-11e9-9763-7f6809421bc1.png)

Looking forward to hearing from you.

**Comment by greytone** [comment]
Hi @jvsam, thank you for your reply. I enclose a word-document for your review of my suggestion. It contains the section with the headline "Hybrid Deployments" followed by a table with four columns. You will see my suggestion of the notes that I think is important information when choosing trust-model.
[Hybrid Deployments_change_suggestion.docx](https://github.com/MicrosoftDocs/windows-itpro-docs/files/3537172/Hybrid.Deployments_change_suggestion.docx)

**Comment by jvsam** [comment]
> I am confirming the scenario behavior to make sure that the documentation is accurate. A note on the differences in deployment type and license type should be included on this page...

Thank you @mapalko! We really appreciate your help on this matter. Please verify if my understanding is correct. So a note can say something like below (*just for context*):

*Windows Hello for Business enables users to reset their forgotten PINs. There are two types of PIN reset, non-destructive and destructive.*

*1. Hybrid deployments support non-destructive PIN reset through the Microsoft PIN Reset service. This feature only works with Windows 10, version 1709 or later Enterprise edition and is only supported with certificate trust model and the latest updates to Active Directory Federation Services.*
*2. On-premises deployments support destructive PIN reset and users can reset forgotten PINs either through the settings page or from above the user's lock screen. This feature works with Windows 10, version 1703 or later Professional edition.*

*Learn more about the [difference between non-destructive and destructive PIN reset](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-faq#what-is-the-difference-between-non-destructive-and-destructive-pin-reset).*

@mapalko how about for Pro, does the PIN Reset support both trust models (*Key trust or certificate trust*)?

@greytone what do you think? Will adding a note, e.g. under the Trust Type section helps? Do you have a better suggestion on how it should be written instead of adding a table? Thanks for sending that over, by the way, much appreciated!

**Comment by mapalko** [comment]
@jvsam sorry for the delay. According to the dev team the enterprise edition requirement was removed. I am still working with them to confirm the exact release where the requirement was removed. 

For Pro with the on-premises model, both key and cert trust support destructive PIN reset.

**Comment by jvsam** [comment]
> According to the dev team the enterprise edition requirement was removed.

Thank you @mapalko. We'll wait for further updates from you. 

> *UPDATED: On-premises deployments support destructive PIN reset and users can reset forgotten PINs either through the settings page or from above the user's lock screen. This feature works with Windows 10, version 1703 or later Professional edition and is supported with both certificate trust and key trust models.*

**Comment by mapalko** [comment]
@jvsam the licensing requirement for PIN reset was removed in 1903. With 1903 the service can be used with Pro sku.

**Comment by jvsam** [comment]
Thank you for the updates @mapalko. Are you pertaining to this - [Streamlined Windows Hello PIN reset experience](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-videos#windows-hello-for-business-forgotten-pin-user-experience)? So on 1903, whether it's cloud, hybrid or on-premise deployment, users can now reset their PIN above the lock screen (*I forgot my PIN* link)? Let me try to summarize the information gathered from this thread, kindly confirm: 

1. Hybrid deployments support non-destructive PIN reset that only works with certificate trust model. 
**Requirements:**
Microsoft PIN Reset Service - Windows 10, version 1709 or later, Enterprise Edition
Reset above lock screen (*I forgot my PIN* link) - Windows 10, version 1903

2. On-premises deployments support destructive PIN reset that works with both certificate trust and key trust models.
**Requirements:**
Reset from settings - Windows 10, version 1703, Professional
Reset above lock screen - Windows 10, version 1709, Professional
Reset above lock screen (*I forgot my PIN* link) - Windows 10, version 1903

We really appreciate the assistance @mapalko. Thank you again.

**Comment by jvsam** [comment]
Hi @mapalko, we'll go ahead and submit a pull request for your review. Thank you.

**Comment by illfated** [comment]
Unless you or the ticket author have planned to create the PR yourself (you are more than welcome to do so), I am willing to create it if you want me to.

**Comment by jvsam** [comment]
Sure @illfated, thank you.

**Comment by jvsam** [comment]
Hi @illfated, good week? I hope so! Will you be creating a PR for this issue?

**Comment by illfated** [comment]
Oh. Right. Sorry that I forgot about this. It has been quite a busy week.
Thank you for reminding me about this one. Just to make sure we are on the same page:
Which page is the recommended one to make the changes to?
- https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide (referenced by mapalko)
- https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-videos#windows-hello-for-business-forgotten-pin-user-experience (your suggestion)
- https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification (issue page)

**Comment by jvsam** [comment]
The original request was to add the information about PIN Reset on the following content pages:

1. [Planning a Windows Hello for Business Deployment](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-planning-guide).
2. [Windows Hello for Business](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-identity-verification).

The main intent is to giver users a head's up that the trust model will affect Pin Reset. I am not sure what will be the best format to incorporate the confirmed information on the above docs. Maybe add an important note? Something user friendly that is easier to digest. What do you think @illfated?

**Comment by illfated** [comment]
Thank you very much for that follow-up. Seeing that the intention is to add the information on more than 1 page, it certainly explains why I felt confused, thinking that only one page was intended.

Adding a `[!Note]` would be my first reaction, so I agree with your suggestions. Thank you. I will start working on it and open a PR for the change shortly.

**Comment by jvsam** [comment]
Hi @illfated, I know you've been busy assisting with the other issues in the repo. Do you have any update on the pull request related to this? Thanks again for the help.

**Comment by illfated** [comment]
Thank you for reminding me. Looks like I commented at quite a late hour in my previous comment and needed to go to bed after that. It is a far more opportune time to get started now. Thank you again and apologies for the significant delay in getting started on the suggested PR change.

**Comment by jvsam** [comment]
No problem at all, @illfated. Take your time :)

**Comment by illfated** [comment]
There you go. Feel free to comment and make notes of anything in need of a change, be it Note placement or detail wording in the PR content. This is for all of you, including @greytone and @mapalko .

**Comment by jvsam** [comment]
Hi @greytone, thank you for your patience. I just want to inform you that the pull request (See PR #5286) that contains suggestions based from your feedback has been approved and merged. The documentation will be updated in the next scheduled publishing run. 

Please continue to send your feedback and suggestions to help improve the quality of the technical documentation of Microsoft Docs. Thank you for being part of the community!
