### ISSUE TITLE
Server Requirements should be documented here

### ISSUE THREAD

**Issue by leandmilo** [MicrosoftDocs/windows-itpro-docs#4670]
Good morning, guys
May you upload the server requirements for this deployment, please?
We have Workstation requirements but not the server requirements.
This is essential for us the administrators to continue doing the right things on this.
Thanks so much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy#feedback)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
@leandmilo : First of all, thank you for checking out the documentation and using it as a basis for your work. Secondly, and I don't have any personal experience with this topic, have you come across any difficulties using this documentation with any currently supported Microsoft Server OS versions? I only noticed MDM, Intune and Azure AD joined Enterprise environments. I would imagine that this should limit the available server versions to pretty much only supported versions, but I could be wrong or mistaken.
> Requirements:
> - AD-joined PC running Windows 10, version 1709
> - Enterprise has MDM service already configured
> - Enterprise AD must be registered with Azure AD

I agree that it would be nice to be able to read that the actual supported server versions verified, but if all currently supported versions of Microsoft Windows Server OS are supported for this scenario, maybe it is implied by virtue of either Azure AD joined Enterprise or the use of MDM + MS Intune already registered in Azure AD. (Maybe this is too much guesswork and not enough facts, but I am trying to suggest a way to use reason as a logic tool to get closer to the answer.)

**Comment by leandmilo** [comment]
We have seen previously in other scenarios that in order for Hybrid GPO Enrollment to complete successfully it requires at least a Windows Server 2016 running 1709 version or plus. Otherwise, we should have problems. That is the main reason we are asking for an update on this article. If possible so we can have accurate information. In addition, the last supported LTSC on windows server 2016 is 1607 and after that it is windows server 2019 https://docs.microsoft.com/en-us/windows/whats-new/ltsc/ and our Environment is not prepared/planned to migrate.
Thanks and please engage a team that may give more information to this, if required

**Comment by illfated** [comment]
Very well, fair enough. Thank you for the precise clarification feedback.

@jvsam : I will not be able to provide any facts here, so I presume we need to ask @ManikaDhiman or @Dansimp to verify and inform us what the Windows Server requirements are in for this document.

**Comment by jvsam** [comment]
>...but if all currently supported versions of Microsoft Windows Server OS are supported for this scenario, maybe it is implied by virtue of either Azure AD joined Enterprise or the use of MDM + MS Intune already registered in Azure AD.

Hi @ManikaDhiman can you help us with this, please? Can you confirm the supported Microsoft server versions for clarity? If the version is dependent on the requirements e.g. *The enterprise AD must be registered with Azure Active Directory (Azure AD)* and *Windows 10*, then following the same logic as @illfated (*well if my understanding is correct*), it's safe to assume that it can only support [Windows current devices](https://docs.microsoft.com/en-us/azure/active-directory/devices/hybrid-azuread-join-plan), such as Windows Server 2016 & 2019? Or maybe I'm way off base so your expertise on this topic will definitely help. It would be great if you can provide clarification on this. As always, thanks in advance for your help!

**Comment by ManikaDhiman** [comment]
Hi @jvsam, I have reached out to the product team to provide guidance. I will keep you informed of any updates here. Thanks!

**Comment by jvsam** [comment]
Thank you for that update @ManikaDhiman. Much appreciated.

**Comment by jvsam** [comment]
Hi @ManikaDhiman, I hope all is well. Did you get any update from the product team regarding the requirements? Thank you again.

**Comment by ManikaDhiman** [comment]
Hi @jvsam, thanks for the follow up. The PR with the note is now merged, updates will be live soon. Thanks!

**Comment by illfated** [comment]
Commit pushed to the Github source: https://github.com/MicrosoftDocs/windows-itpro-docs/commit/fe1a87868eb1dc75ec972742d80653e768d53d0e#diff-4c3b03ffd3d552578430f86d8182022c

**Comment by jvsam** [comment]
Thank you so much @ManikaDhiman! As always, your help is appreciated.

Hello again @leandmilo, we just want to let you know that this documentation has been updated. There is now a link that points to the [content page](https://docs.microsoft.com/azure/active-directory/devices/hybrid-azuread-join-plan) that provides information on the *minimum Windows Server version requirement*. You can verify the changes at this URL: https://docs.microsoft.com/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy. 

We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation. Thanks again for being part of the Microsoft Docs Community!

**Comment by jvsam** [comment]
@officedocsbot close
