### ISSUE TITLE
DG_Readiness_Tool_v3.6.ps1 on Non-English OS

### ISSUE THREAD

**Issue by sanso2010** [MicrosoftDocs/windows-itpro-docs#4679]
Hey everyone,

no, this is not about the architecture alone. Here are some suggestions that would immensely help working with the readiness tool:

- Let $path be a param
- For Non-English OS: Avoid DISM completely. String comparison on Non-English OS will never work. Instead use something like `Enable-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All` or `Get-WindowsOptionalFeature -Online  | select featurename | where {$_ -like "*Hyper-V*"}` (ofc don't use "like" I was just lazy here)
- For Non-English OS: CheckDriverCompat and all following functions (ListDrivers, ListCIStats, CheckFailedDriver) need to be adjusted to make it work on Non-English OS (see next for an example)
- For Non-English OS: `$verifier_state.ToString().Contains("No drivers are currently verified.")` could be `!$verifier_state.ToString().Contains("[X] 0x02000000")` I do not have a machine to doesn't do code signing rn
- For Non-English OS: If you already know about the architecture issue and you already fixed this for "CheckOSSKU" why not do this same for "CheckOSArchitecture"?

Why suggest all this? Because I want this to work on every language and I want to have it signed, which should be done by MS. I realize there are many ways to manage and/or activate DG/CG/HVCI, but for testing alone these changes would be worth it. I think the overall quality of the script can be improved be a few adjustments as described. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@sanso2010 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by illfated** [comment]
Ref. #3234

**Comment by mypil** [comment]
@sanso2010 - The Win10 ITPro writing team is working on getting the fixed script to be published. Please standby for further updates. Thank you for your patience.

**Comment by get-itips** [comment]
Hello everyone.
The script has been updated by the product team behind it, I created a pull request to update the document references, you should be able to see the changes soon.
Thank you

**Comment by illfated** [comment]
@sanso2010 : Hope to hear back from you again some time. Also hope everything is OK with you.

**Comment by sanso2010** [comment]
@illfated Yes, I'm fine now -  I was actually sick for about 2 weeks now with Influenza B - no fun. If there's anything I can help with (test for example) I'll gladly do so. I have multiple international customers, so I have Windows 10 in a variety of languages at hand. 
I'm already really happy this got picked up as quick as it did. Thank you!

**Comment by mypil** [comment]
@sanso2010 - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
