### ISSUE TITLE
Does network service really have the SeRestorePrivilege by default

### ISSUE THREAD

**Issue by zigfig21** [MicrosoftDocs/windows-itpro-docs#4681]
Does network service really have the SeRestorePrivilege by default?
It seems like a to powerful privilege for the network service account

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 486e8a12-8230-6ae2-264f-73c76b266682
* Version Independent ID: 2f47f94f-b416-beac-c75d-8908e4000e66
* Content: [Special Identities (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/special-identities#network-service)
* Content Source: [windows/security/identity-protection/access-control/special-identities.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/access-control/special-identities.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@zigfig21 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@zigfig21 - From our understanding, the issue has been resolved based on the merged commit [[c28e46e](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/c28e46e708eaa08aff82b63718bc38bf535a8f73)] but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
