### ISSUE TITLE
Win32 apps converted with the Desktop Converter Application

### ISSUE THREAD

**Issue by Cirnohalo** [MicrosoftDocs/windows-itpro-docs#4689]
Assigned Access mode doesn’t support Win32 apps yet, including Win32 apps converted with the Desktop Converter.
When can it be supported?
(https://stackoverflow.com/questions/40492539/windows-10-assigned-access-app-fails-to-start-due-to-not-registered-for-windows)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Cirnohalo - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by Cirnohalo** [comment]
> @Cirnohalo - May we know which Microsoft document link you used in reference to this issue?
> Please share it with us so we can investigate further. Thank you.
I have a win32 app and use Desktop Converter to get UWP appx, but Assigned Access mode doesn’t support this appx. (Assigned Access mode doesn’t support. (https://docs.microsoft.com/en-us/windows/configuration/kiosk-single-app)

**Comment by mypil** [comment]
@Cirnohalo - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via **[Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
