### ISSUE TITLE
Tools Update and Offline Installer - for Microsoft Surface Hub

### ISSUE THREAD

**Issue by EricSP2** [MicrosoftDocs/windows-itpro-docs#4690]
All morning I have been attempting to download the recovery image through your tool.

The tool does initiate the download, however after 15 minutes or 80%-ish of the progress, it times out and mentions **Progress Download Failed OK**.

My biggest pet peeve is that once it does fail, there is ***NO RESUME*** option and whatever binary it downloaded at that point is deleted and the app does not attempt to resume the file download but instead completely wipes the binaries and restarts from 0%

Considering the amount of money we've invested in your surface hub, this is a sub-par experience.

Would it be possible to modify your recovery tool to **RESUME** and *NOT RESTART* after a failure.

Or simply provide direct links to the WIM file and location to cram it in so it can be downloaded manually.

So far I have wasted 4 hours of my precious time trying to get the WIM. :/

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@EricSP2 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by EricSP2** [comment]
This is the primary documentation

https://docs.microsoft.com/en-us/surface-hub/surface-hub-recovery-tool

In the comments section see "**_Surface Hub Recovery Tool through a corporate Proxy Server_**"

**Comment by EricSP2** [comment]
Essentially since my proxy does not allow the traffic through and my network guy is away, I've installed the software on a burner laptop directly connected to an unfeathered internet access.

**Comment by EricSP2** [comment]
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2320

**Comment by EricSP2** [comment]
I also see this:

https://support.microsoft.com/en-us/surfacerecoveryimage?productId=110668454

However, there's no image download available for Gen1 :/

**Comment by mypil** [comment]
@EricSP2 - Thank you for engaging with the community here for the docs. 

We're sorry to hear that you are having issues. Please understand that this site is a product documentation site and not a support nor a feature request site.

As such, the feedback section here is intended for feedback that improves the content in the Microsoft documentation and not intended for user feedback on product features nor troubleshooting.

For user feedback on product feature requests, you can submit via **[Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)**. I know the product teams are always looking for user feedback on how to make Windows 10 better. You might find others have made a similar request that you can add to, or you can open a new one.

For technical queries or troubleshooting, you can visit **support.microsoft.com**, **answers.microsoft.com** or open a **[support ticket](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)**.

I hope this gets you pointed in the right direction. Thank you.

**Comment by EricSP2** [comment]
then fix your documentation ;)

**Comment by EricSP2** [comment]
microsoft fails again...
