### ISSUE TITLE
Recovery Image not available

### ISSUE THREAD

**Issue by fabianseither** [MicrosoftDocs/windows-itpro-docs#4691]
This page links to https://support.microsoft.com/en-us/surfacerecoveryimage?devicetype=surfacehub2s for downloading recovery image of Surface Hub 2S. After entering the serialnumber of our device this page only shows "The recovery image for your device isn't available for download through its page. For help, please contact-us"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6435b14-27da-d10e-4919-b3194ca03a07
* Version Independent ID: b181319b-1bb4-010a-eeab-64ac199fb24c
* Content: [Reset and recovery for Surface Hub 2S](https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-recover-reset#feedback)
* Content Source: [devices/surface-hub/surface-hub-2s-recover-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/surface-hub-2s-recover-reset.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@fabianseither - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@fabianseither - Thank you for engaging with the community here for the docs.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by riverar** [comment]
@fabianseither Did this get fixed for you? Can you confirm the filename?
