### ISSUE TITLE
Please update the screenshots to not show the public preview

### ISSUE THREAD

**Issue by andrewbettany** [MicrosoftDocs/windows-itpro-docs#4697]
Please update the screenshots to not show the public preview.
Also please update the Azure screenshots as these have now been re-designed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9dadd7a-2a10-0330-5e3b-8736ee37d0b0
* Version Independent ID: 5ebbfa1e-097d-0624-49d3-334d2625d806
* Content: [Windows Analytics in the Azure Portal](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-azure-portal#feedback)
* Content Source: [windows/deployment/update/windows-analytics-azure-portal.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-azure-portal.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for your suggestions to help improve the quality of the technical documentation, @andrewbettany. We always strive to give users the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, accurate and up-to-date. I will get this over to the Windows content writing team and request for updated screenshots. 

Thank you for being part of the Microsoft Docs Community!

**Comment by jvsam** [comment]
Hello again @andrewbettany, thank you for your patience. Please be informed that the suggested updates to this documentation as per your feedback (See pull request #4996) have already been merged. Please expect the changes to be displayed here at docs.microsoft.com in the next scheduled publishing run. 

We will now close this issue. Feel free to re-open or create another issue through the *feedback feature* if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
