### ISSUE TITLE
Need Multifactor Unlock CSP instructions

### ISSUE THREAD

**Issue by PiKappZ746** [MicrosoftDocs/windows-itpro-docs#4700]
I've added the following UserVoice item.  Until that is done, it would be very helpful to document creating a custom ADMX backed CSP to configure Multifactor Unlock in Intune.
https://microsoftintune.uservoice.com/forums/291681-ideas/suggestions/38381962-add-multifactor-unlock-configuration-to-whfb-windo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f8c2ce-8edb-60d3-ebf9-bdb625bf66dc
* Version Independent ID: ee1ed0a8-b05c-c499-6504-40b5b298c53b
* Content: [Multifactor Unlock](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/feature-multifactor-unlock#create-the-multifactor-unlock-group-policy-object)
* Content Source: [windows/security/identity-protection/hello-for-business/feature-multifactor-unlock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/feature-multifactor-unlock.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@PiKappZ746 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@mapalko - Can you please share your insights on this issue?

Thank you.

**Comment by mapalko** [comment]
The multifactor unlock feature is supported via the Passport for Work CSP. https://docs.microsoft.com/en-us/windows/client-management/mdm/passportforwork-csp

This needs to be updated in the Multi factor auth documentation.

**Comment by mypil** [comment]
@PiKappZ746 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by SoccerCore11** [comment]
@mypil - Looks like Intune configuration settings for enabling Multifactor Unlock are still missing.

**Comment by PeterKlapwijk** [comment]
@SoccerCore11 have a look at this article https://www.inthecloud247.com/enable-windows-hello-multifactor-device-unlock-with-microsoft-intune/
