### ISSUE TITLE
What role is required?

### ISSUE THREAD

**Issue by spaelling** [MicrosoftDocs/windows-itpro-docs#4706]
My user has all roles assigned, but still do not have permission to click "add machine"? Next step is global adminstrator in the tenant which seems silly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12e5744d-46dd-7f90-e42e-70caf9dd56d2
* Version Independent ID: 1a627400-9585-e482-3820-e58f6c172a87
* Content: [Microsoft Defender ATP evaluation lab](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/evaluation-lab#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/evaluation-lab.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/evaluation-lab.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@spaelling - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mjcaparas** [comment]
@spaelling - it's likely that you have used up all 3 machines. 

Please note:
Each environment is provisioned with only three test machines. 
Each machine will be available for only three days from the day of activation. 

When you've used up these three machines, no new machines are provided. 
Deleting a machine does not refresh the available test machine count. 

Given the limited resources, it’s advisable to use the machines carefully.

**Comment by mjcaparas** [comment]
@spaelling as long as the user has "Manage portal system settings" role, they should be able to add a machine.

**Comment by mypil** [comment]
@spaelling - From our understanding, the issue has been answered by mjcaparas. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by spaelling** [comment]
> 
> 
> @spaelling as long as the user has "Manage portal system settings" role, they should be able to add a machine.

Good to know. Incidently that was the role I was missing.

It does not look like the documentation has been updated with this fairly important piece of information?

I do think that there should be a dedicated role for this function. The `Manage portal system settings` role is a fairly privileged role. It could likely be that some dedicated personnel would be assigned to work with just the lab.
