### ISSUE TITLE
Connection to Offline CA

### ISSUE THREAD

**Issue by vrdse** [MicrosoftDocs/windows-itpro-docs#4707]
Can you please clarify this hint:

> For organizations that use an offline root in their PKI infrastructure, Microsoft Surface UEFI Configurator must be run in an environment connected to the root CA to authenticate the SEMM certificate. The packages generated by Microsoft Surface UEFI Configurator can be transferred as files and therefore can be transferred outside the offline network environment with removable storage, such as a USB stick.

What's exactly meant by "connected to the root CA". Is it, that the AIA and CDP must be accessible to check revocation status? How is the "authenticate the SEMM certificate" process implemented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0d25836-4403-d111-9bd7-ca5f1ed56449
* Version Independent ID: 5219aa78-698c-926c-53d8-f02fdf36bb3b
* Content: [Surface Enterprise Management Mode (Surface)](https://docs.microsoft.com/en-us/surface/surface-enterprise-management-mode#surface-enterprise-management-mode-certificate-requirements)
* Content Source: [devices/surface/surface-enterprise-management-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/surface-enterprise-management-mode.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@vrdse - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by illfated** [comment]
@vrdse : I am not fluent in this topology, but my immediate interpretation of that text is that "connected to the root CA" means that Microsoft Surface UEFI Configurator must be connected to the same network as the root CA, but I am uncertain if this means the same LAN, same subnet or any network distance as long as it is connected and has got a persistent connection with the root CA computer.

**Comment by vrdse** [comment]
I understand your interpretation, but that's exactly why I opened the issue. 

> For organizations that use an **offline** root in

> as long as it is connected and has got a **persistent connection** with the root CA computer

This doesn't work out well.

Please note, that Offline Root CA is a common term in PKI, where you have a 2-tier hierarchy and the top level is offline. You refer to that as recommended on the same page. I have the feeling that, in the paragraph I quoted initially, you mean something else. Maybe where the clients are in disconnected environments?

**Comment by MaratMussabekov** [comment]
Hello @vrdse ,
yes, that means that  AIA and CDP must be accessible, because the validity of certificate must be confirmed by the CA when you signing the SEMM package.
**How is the "authenticate the SEMM certificate" process implemented** - it checks expiration and revocation status of the certificate
Thank you

**Comment by mypil** [comment]
@vrdse - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
