### ISSUE TITLE
Please translate it correctly

### ISSUE THREAD

**Issue by NetBUG** [MicrosoftDocs/windows-itpro-docs#4708]
THe header should be "выход из учетной записи был выполнен"

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 1221d706-bc1a-f842-1439-d0ea32e20225
* Version Independent ID: 276a7268-75e7-713e-7b2d-688fc90cef8e
* Content: [4634 (-а) об отключении учетной записи. (Windows 10)](https://docs.microsoft.com/ru-ru/windows/security/threat-protection/auditing/event-4634#feedback)
* Content Source: [windows/security/threat-protection/auditing/event-4634.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/event-4634.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by mypil** [comment]
@NetBUG - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@TinaMcN - Please assist with this Translation/Localization issue. 

Thank you.

**Comment by illfated** [comment]
@NetBUG : Your suggested text is instead of "учетная запись была удалена"
-- is that correct? (**4634 (-а): учетная запись была удалена.**)

**Comment by NetBUG** [comment]
Hi @illfated, the text you suggested means `The account has been deleted`. This is incorrect and misleading (this description is correct for code 4726).

AFAIK 4634 means `An account was logged off`, which should be translated as `Выход из учетной записи [был выполнен]`

Or check how it is translated in Russian MUI of Windows, I have not used it for years.

**Comment by illfated** [comment]
Thank you for confirming. I just wanted to verify that
`Выход из учетной записи [был выполнен]`'
should replace
`учетная запись была удалена` .

**Comment by TinaMcN** [comment]
@NetBUG Спасибо за обратную связь.  Статья была переведена машиной.  Я послала его для человеческого перевода.  Это может занять несколько недель.
(Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  This may take a few weeks to complete.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates if this issue has been fixed?

Thank you.

**Comment by illfated** [comment]
The page title still reads

## 4634 (-а): учетная запись была удалена.
(The account has been deleted.)
***
According to the issue ticket author, it should instead read as follows:

##  4634 (-а): выход из учетной записи был выполнен
(An account was logged off -- or -- logout was completed)

**Comment by TinaMcN** [comment]
The file was stuck being handed off to translation.  I tried sending it again and the asked the localizers to confirm when they receive it.

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on this?

Thank you.

**Comment by TinaMcN** [comment]
@mypil the article is now human translated.  The title is now "4634(S): Осуществлен выход учетной записи из системы."  @NetBUG can you please confirm if this translation is acceptable?  And thanks again for reporting it.

**Comment by NetBUG** [comment]
@TinaMcN @mypil Yep, that seems correct, that means that the user was logged off.
Thanks, and I am quite surprised how much discussion happened around this tiny fix)

**Comment by illfated** [comment]
Thanks to all of you for the feedback and for following up on this topic.
