### ISSUE TITLE
My computer is hang 

### ISSUE THREAD

**Issue by rajh4873** [MicrosoftDocs/windows-itpro-docs#4731]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47692487-0a0b-3b1b-6d34-790046c7cbc3
* Version Independent ID: 0f66cafe-2bff-4323-b3fc-01014b904b3a
* Content: [Windows Update log files](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-logs)
* Content Source: [windows/deployment/update/windows-update-logs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-logs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@rajh4873 - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by illfated** [comment]
@mypil : To me, it looks like the author's problem is fairly unrelated to the page where he posted that single line. Then again, if the problem occurred while researching the content of the page, we can only hope to hear back from the user regarding this topic.

**Comment by mypil** [comment]
@officedocsbot close
