### ISSUE TITLE
Provisioning a Windows device for users who are not allowed to join devices to Azure AD

### ISSUE THREAD

**Issue by rajeshkhanikar** [MicrosoftDocs/windows-itpro-docs#4737]
We were expecting White Glove to add the device to Azure AD and make it ready for an end-user to sign in after it is sealed. But it doesn't seem to work like that.

White-Glove seems to only work for end-users who are allowed to join a device to Azure AD. This is our experience -
1. Provision a device (White Glove)
2. Seal the device
3. Restart the device
4. Sign in to the device as the end-user (the user is not allowed to join devices to Azure AD)
This is what we see as the error:
-----------------------------------
Something went wrong.
This user is not authorised to enrol. You can try to do this again or contact your system administrator with the error code 801c0003
Server message: Administrator policy does not allow this user ..... to device join.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5b57d1-61b3-39d4-34ff-d6dcb858c250
* Version Independent ID: 42609104-815f-9e7a-39aa-38d92cc910c9
* Content: [Windows Autopilot for white glove deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove)
* Content Source: [windows/deployment/windows-autopilot/white-glove.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/white-glove.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@rajeshkhanikar - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by ZubairRiaz007** [comment]
Hey Guys,
I goes through all your conversation, my issue is resolved by setting up the following options.
![image](https://user-images.githubusercontent.com/33540048/142911217-400a24ae-9ca6-473e-bffb-005b179f8cd4.png)
