### ISSUE TITLE
Testing steps | Logs query

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#4740]
Hello,

Would like to confirm information about "DHOSReliability" for "computer name" field.

Current setup build as:
1. Created log analytics workspace with pricing tier per GB 2018
2. Added Device Health to tenant
3. Deployed id and logs settings via Intune and devices do onboard fine

But when query logs for devices or apps info or "DHOSReliability", the Computer name shown as "unknown".
Any ideas why?

![image](https://user-images.githubusercontent.com/39700914/63337085-a3816400-c340-11e9-9dac-95ed2eb0eb8a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af1d6af3-9530-fd12-cd25-52c904c5ac58
* Version Independent ID: 8d5d6869-1ea9-05e3-76e9-4970fe1e7871
* Content: [Using Device Health](https://docs.microsoft.com/en-us/windows/deployment/update/device-health-using)
* Content Source: [windows/deployment/update/device-health-using.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/device-health-using.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@lightupdifire -  Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by jaimeo** [comment]
@MatthewMWR , @Deepamdubey , is this something you can address? Let me know if there is a doc edit need here.

**Comment by MatthewMWR** [comment]
To enhance consumer privacy, recent versions of Windows 10 no longer include the device name in Windows Diagnostic Data by default. By extension, the device names are not available in Windows Analytics solution by default.
To enable the devices to send their device name, you need to configure allowdevicenameintelemetry via the UR deployment script or Group Policy, etc. For reference:
https://gpsearch.azurewebsites.net/#13763

**Comment by lightupdifire** [comment]
@MatthewMWR 
As far understood, Device Health presented as "new solution", that can exist without UR deployment..
And we try to avoid any script deployment.
Thanks for guide for "allowdevicenameintelemetry", I see CSP policy exist, can play with that.

Regards "Device Health" article, maybe it is good to explain that if you deploy "Device Health" as standalone, without UR deployment, then there is limitation, or create an FAQ article for "Device Health" and explain what limitation could be?

**Comment by mypil** [comment]
@MatthewMWR - We would like to follow up. Do you have any information on the additional question from @lightupdifire?

Thanks.

**Comment by MatthewMWR** [comment]
I'm not 100% sure I understand the question. Is it essentially "would a Device Health customer lose out on any Device Health features if they don't also use UR and/or UR deployment script?". I'll try to answer that question for now.
There are no hard dependencies between the solutions (there are shared dependencies like deploying CommercialID, but no dependencies between the actual solutions in Log Analytics). If a customer is not using UR then DH deployment is typically best done via simple configuration like deploying the policies via MDM or GP (no need for deployment script).
I can imagine some specific cases where deploying DH together with either UR or UR deployment script could add value, for example:
You could have a connectivity issue between your PCs and the Microsoft endpoints used by UR and DH, and the UR deployment script would help to find these sooner.
You could have a custom Log Analytics query which cross-references UR and DH data.

**Comment by lightupdifire** [comment]
@MatthewMWR ,
Thanks for you answer, this confirm that DH can exist as standalone solution,
Then please add to this article (or create FAQ) about limitations or like "fine-tuning required", like computer name will be not shown in logs and required to add CSP policy via Intune. 
I could fix computer name using Intune CSP policy:
OMA-URI: ./Vendor/MSFT/Policy/Config/System/AllowDeviceNameInDiagnosticData
Data type: Integer
Value: 1
![image](https://user-images.githubusercontent.com/39700914/64230198-6692a100-ceec-11e9-9e97-84690efd84e4.png)

**Comment by mypil** [comment]
@lightupdifire - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
