### ISSUE TITLE
Where does the GPO stores removable drives recovery information?

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/windows-itpro-docs#4744]
Where can we find removable drives recovery information in ADDS when the "Store BitLocker recovery information in Active Directory Domain Services" GPO setting is enabled? Within the computer object from where the drive was encrypted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5476099c-9d70-97df-8ee6-bc442605cfbd
* Version Independent ID: 49ca0628-bd88-e05b-b705-3b361b57512d
* Content: [BitLocker Group Policy settings (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings#bkmk-rec3)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-group-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Martony78 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@Martony78 You are correct, it's stored within the computer object, and you can use the BitLocker Recovery Password Viewer to view this info.

https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-use-bitlocker-recovery-password-viewer

"Using this tool, you can examine a **computer object's** Properties dialog box to view the corresponding BitLocker recovery passwords. "

**Comment by mypil** [comment]
@Martony78 - From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
