### ISSUE TITLE
1903 ADK - Sharedpc Mode Gone?

### ISSUE THREAD

**Issue by brockettc** [MicrosoftDocs/windows-itpro-docs#4747]
I don't see this setting anywhere anymore.

Thanks,

Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 224aec81-9c13-e3d2-4d35-8ea281ecf341
* Version Independent ID: 7272ee19-5f63-f18d-5cbc-aa1f9e0397ed
* Content: [SharedPC (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/wcd/wcd-sharedpc)
* Content Source: [windows/configuration/wcd/wcd-sharedpc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/wcd/wcd-sharedpc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@brockettc . Actually this page article explains the windows 10 settings. not for ADK.
ADK tool is used to create Windows pe re iso

**Comment by e0i** [comment]
@officedocsbot assign @mypil

**Comment by e0i** [comment]
@officedocsbot assign @mypil

**Comment by brockettc** [comment]
> @brockettc . Actually this page article explains the windows 10 settings. not for ADK.
> ADK tool is used to create Windows pe re iso

I put the issue on two pages, but if you follow the link on this page 'set up shared or guest PC'. In this page it states 'Shared PC mode exposes a set of customizations to tailor the behavior to your requirements. These customizations are the options that you'll set either using MDM or a provisioning package as explained in Configuring shared PC mode on Windows. The options are listed in the following table.'

Which it looks like it is gone from the 1903 ADK to create a provisioning package with.

**Comment by RAJU2529** [comment]
@broçkettc. I read your reply. I am not  an expert in this scene  so I will wait  some expert users will answer your issue. Keep calm sir.

**Comment by mypil** [comment]
@brockettc - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
