### ISSUE TITLE
Windows Defender - Turn off Periodic Scanning once enabled

### ISSUE THREAD

**Issue by Kadafi-Hub** [MicrosoftDocs/windows-itpro-docs#4748]
It's all good and well turning on periodic scanning in windows defender, but how on earth are you meant to turn it off again?

*EDIT* Link to *.DOC
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/limited-periodic-scanning-windows-defender-antivirus

**Comment by illfated** [comment]
Did you come here from a specific page where you expected to find that information?
If yes, could you link the page, in case it needs clarification for general improvement of the docs.microsoft.com pages?

**Comment by RAJU2529** [comment]
@kadafi-Hub .periodic scanning can be turned off via group policy editor

**Comment by e0i** [comment]
@officedocsbot assign @mypil

**Comment by e0i** [comment]
@officedocsbot assign @mypil

**Comment by Kadafi-Hub** [comment]
@illfated  https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/limited-periodic-scanning-windows-defender-antivirus

Apologies, I found it here, I assumed when I clicked to view the article on GitHub it would have linked back to it.

**Comment by Kadafi-Hub** [comment]
> @Kadafi-Hub .periodic scanning can be turned off via group policy editor

Can you be more specific? I'd already checked all the group policies under "Windows Defender Antivirus" > Scan  and there is nothing that seems relevant.

**Comment by Kadafi-Hub** [comment]
> Did you come here from a specific page where you expected to find that information?
> If yes, could you link the page, in case it needs clarification for general improvement of the docs.microsoft.com pages?

https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/limited-periodic-scanning-windows-defender-antivirus

Apologies, I found it here, I assumed when I clicked to view the article on GitHub it would have linked back to it.

**Comment by RAJU2529** [comment]
@Kadafi-Hub. i found  that settings in Microsoft defender antivirus in gpo

see below screenshots
![0011](https://user-images.githubusercontent.com/3296790/63420042-896c8200-c423-11e9-9988-1d9ff69f02bc.JPG)
![0012](https://user-images.githubusercontent.com/3296790/63420109-a6a15080-c423-11e9-8cff-8f394438de55.JPG)

**Comment by Kadafi-Hub** [comment]
> @Kadafi-Hub. i found that settings in Microsoft defender antivirus in gpo
> 
> see below screenshots
> ![0011](https://user-images.githubusercontent.com/3296790/63420042-896c8200-c423-11e9-9988-1d9ff69f02bc.JPG)
> ![0012](https://user-images.githubusercontent.com/3296790/63420109-a6a15080-c423-11e9-8cff-8f394438de55.JPG)

Is turning off Windows Defender Anti Virus the same as "turning off periodic scanning"?

**Comment by illfated** [comment]
@Kadafi-Hub : I don't think the suggested answers from @RAJU2529 are usable for your question, because those examples look like turning off the entire service or feature to me, not specifically the scheduled scans. Guys, grab a bigger shovel, we need to dig deep to find the answer here.

**Comment by Kadafi-Hub** [comment]
For additional information:
Build 1809
17763.720

I don't think the ability to do as via the GUI. When you turn the slider to ON, then the option to turn the slider disappears.....

![Periodic Scanning ON](https://user-images.githubusercontent.com/54334182/63456531-0e1cc780-c447-11e9-85a5-fa13bb2857ee.JPG)

**Comment by illfated** [comment]
Follow-up: I think maybe we could try digging into the PowerShell cmdlets, but I was also trying to figure out how you enabled the periodic scans in the first place.
Have a look at https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/security-malware-windows-defender-scan (**Scan**). It lists
- ScanParameters
- ScheduleDay
- ScheduleTime

There is also the XML at the bottom of the page, which could in theory be used to reset the current schedule by using zero-size values ( `0` ).

**Comment by Kadafi-Hub** [comment]
OK so, @RAJU2529 suggestion checks out...
When you TURN OFF Windows Defender Antivirus via group policy... the Slider to turn it ON again re-appears..... Definitely think Microsoft need to stop making the slider disappear when you turn the slider ON.

**Comment by illfated** [comment]
Nice find. I did not expect that. Feels almost like an Easter egg in terms of logic thinking. I also agree with your statement, it is far from obvious or given that the GUI option should become hidden when enabled.

**Comment by RAJU2529** [comment]
only antivirus product must be used in windows machine. By default Microsoft defender antivirus is turned on automatically. But when we installed second party antivirus which includes anti-malware features , then Microsoft defender is turned off automatically. If defender does not turned off meàns, we can stop the entire action by modifying registry key or  disabling by configuring in GPO.

**Comment by Kadafi-Hub** [comment]
Yea I already understand that installing a 3rd party AV disables the native OS windows defender. My annoyance is the fact the when you enable periodic scanning, the "ON/OFF" slidet dissapears. Then to re enable you have to modify the gpo to enable "turn windows defender antivirus off". The on and off slider needs to remain on the gui

**Comment by illfated** [comment]
From my experience with issue tickets here on this page, it is normally recommended that you post that request on Microsoft Feedback Hub to submit your views to the developers (that is what I would have done in this case, if I had been in your situation -- where an obvious software behavioral issue should be discussed with the developers by someone with the personal experience of that software event).

**Comment by mypil** [comment]
@Kadafi-Hub - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via **[Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by danbu** [comment]
> Yea I already understand that installing a 3rd party AV disables the native OS windows defender. My annoyance is the fact the when you enable periodic scanning, the "ON/OFF" slider dissapears. Then to turn off periodic scanning you have to modify the gpo to enable "turn windows defender antivirus off". The on and off slider needs to remain on the gui

I'm on 21H1 and you can turn this off when the "Virus & threat protection" refreshes it adds 4 new sections "Current threats", "Virus & threat protection settings" and "Virus & threat protection updates", and "Ransomware protection" below all of those there is a "Microsoft Defender Antivirus options" collapsible section you can expand and turn the setting back off.  It prompts a UAC then refreshes the settings and it is now off.
