### ISSUE TITLE
Please add RSS feed for this page

### ISSUE THREAD

**Issue by eculturedk** [MicrosoftDocs/windows-itpro-docs#4753]
Pretty please :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9d6b543-3693-7771-9cd1-b8f57e304310
* Version Independent ID: 5ba25ca7-32ac-2d28-cc69-e6bf53dede66
* Content: [What's new in Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/whats-new-in-microsoft-defender-atp#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/whats-new-in-microsoft-defender-atp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/whats-new-in-microsoft-defender-atp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@mjcaparas Would you be able to provide an official response to this feedback regarding integrating an RSS feed to "What's new" pages? Thank you in advance.

**Comment by mjcaparas** [comment]
Unfortunately it is not supported.

**Comment by NotTheVacuum** [comment]
"What's New in InTune" has an RSS feed: 
https://docs.microsoft.com/en-us/intune/fundamentals/whats-new

Why can't this be done for ATP?
