### ISSUE TITLE
Example XML has format issue 

### ISSUE THREAD

**Issue by etonline** [MicrosoftDocs/windows-itpro-docs#4755]
The example has format issue, will result in not able to parse XML error.

Should be:
```
<groupmembership>
    <accessgroup desc="Administrators">
        <member name="AzureAD\CSPTest@contoso.com" />
        <member name="CSPTest22306\administrator" />
        <member name = "AzureAD\patlewis@contoso.com" />
    </accessgroup>
    <accessgroup desc = "testcsplocal">
        <member name = "CSPTEST22306\patlewis" />
        <member name = "AzureAD\CSPTest@contoso.com" />
    </accessgroup>
</groupmembership>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0c28c15-f0be-d732-4d9e-cf5df5e64e8b
* Version Independent ID: 17eba45f-d200-e656-42b9-e1a512931eea
* Content: [Policy CSP - RestrictedGroups](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-restrictedgroups#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-restrictedgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-restrictedgroups.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
@etonline : Sorry for the delay in checking out your issue.
Your suggested version is identical to the page example.
Have you possibly copy-pasted the wrong text unintentionally?

**Comment by e0i** [comment]
@etonline 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
