### ISSUE TITLE
Possible doc bug on Defender ATP for MAC

### ISSUE THREAD

**Issue by amirsc3** [MicrosoftDocs/windows-itpro-docs#4756]
According to this article:
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac-resources#microsoft-defender-atp-portal-information

MDATP for MAC which is currently released is able to show the following in addition to alerts:
"Device information, including: 
Machine identifier
Tenant identifier
App version
Hostname
OS type
OS version
Computer model
Processor architecture
Whether the device is a virtual machine"

However, I believe we can't see a lot of the above information (besides hostname, Processor architecture, and machine id) at least until the EDR portion of MDATP for MAC is released...

For now I believe the following is not applicable yet:
- App version
- OS type
- OS version
- Computer model
- Whether the device is a virtual machine

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @amirsc3 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by VLG17** [comment]
@amirsc3 Did you also turn on the [preview features](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/preview)?

I have not tested this, but some of them could help with providing that missing piece of information.

**Comment by amirsc3** [comment]
I have access to a MAC machine in my lab environment (with all public preview features enabled).
I don't see such information in MDATP portal (App version, OS type, OS version, Computer model, Whether the device is a virtual machine) - can you clarify where this info is expected to be found as I don't see it when going to the specific machine's URL page.

**Comment by e0i** [comment]
@amirsc3 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
