### ISSUE TITLE
Table in article at the Reference section is broken

### ISSUE THREAD

**Issue by mtamayoo** [MicrosoftDocs/windows-itpro-docs#4760]
The table is broken and it's almost unreadable. I'm talking here about the table that goes right after "The following table lists and explains the allowed encryption types."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d05d447-1cc1-1eeb-3c4d-74591874f4e1
* Version Independent ID: 020b4d09-5ce9-e636-0545-1ce27029a921
* Content: [Network security Configure encryption types allowed for Kerberos Win7 only (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @mtamayoo

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.
