### ISSUE TITLE
Documentation must be update

### ISSUE THREAD

**Issue by paulyrg38** [MicrosoftDocs/windows-itpro-docs#4761]
I followed the steps described in the section "Build a custom Microsoft Defender ATP dashboard in Power BI Desktop" 

Step 4. The correct directory is [Documents]\Power BI Desktop\Custom. 
Step 8. Power BI Desktop last versions don't have the preview features options described in the documentation. You must enable Data extension in Security option.

Here is the reference: https://docs.microsoft.com/en-us/power-bi/desktop-connector-extensibility.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@paulyrg38 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by VLG17** [comment]
@paulyrg38 I assume [this](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/powerbi-reports) is the article you followed.

Step 4, although it does not give the complete path, it tells us where to create the folder "Create a new directory Microsoft Power BI Desktop\Custom Connectors **under the user's Documents folder.**"

But i will create a PR for this and change the path.

Step 8 - i will add a note for that. Thanks for the feedback.

**Comment by e0i** [comment]
@paulyrg38 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
