### ISSUE TITLE
Settings for installing desktop apps need to be expanded

### ISSUE THREAD

**Issue by geoken** [MicrosoftDocs/windows-itpro-docs#4763]
That section is a bit unclear. i wasn't sure if it could run the MSI direct or needed to be called through msiexec /i and also, if I needed to structure the target path in any specific way.

Fortunately the basic installer shows the command its going to run once you add the MSI so you can pull it from there. For reference, it's;

msiexec /i "your_installer.msi" /qn /norestart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de181258-2f52-9e47-04e1-f3488d21efc8
* Version Independent ID: c358316f-9d73-fed2-6f55-99814630ede6
* Content: [Provision PCs with apps  (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provision-pcs-with-apps#feedback)
* Content Source: [windows/configuration/provisioning-packages/provision-pcs-with-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/provisioning-packages/provision-pcs-with-apps.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@geoken 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
