### ISSUE TITLE
Sample Configuration XML missing <Config> Element

### ISSUE THREAD

**Issue by j1mmyfever** [MicrosoftDocs/windows-itpro-docs#4765]
&lt;Configs&gt;
    &lt;Config&gt;
        &lt;v3:DefaultProfile....&gt;
    &lt;/Config&gt;
&lt;/Configs&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78038d67-04a1-f4ae-6a69-98e157688a31
* Version Independent ID: c86b4460-e8be-8537-a6c8-3cb094ef14a3
* Content: [Set up a multi-app kiosk  (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps#feedback)
* Content Source: [windows/configuration/lock-down-windows-10-to-specific-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/lock-down-windows-10-to-specific-apps.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
@j1mmyfever : I am not an expert on this topic, but from just browsing this page, it looks to me as if that specific piece of information is described pretty well from the section https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps#configs and below. Are there any particular XML examples you find that won't work without the `<Configs>` section in them, even as examples?

**Comment by j1mmyfever** [comment]
This one doesn't have the inner <Config> element, which is the combination of most of the other samples on the page, and most likely to be copied, which is what I did.  It won't run with it.  AssignedAccess shoots XML parsing errors expecting the node.  Granted, I did add <Account> there as well, but I believe <v3:DefaultProfile> needs to be in <Config> as well.  Maybe my confusion, not positive now.  I'll have to retest.
https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps#preview-global-profile

**Comment by illfated** [comment]
Very well, I hope you will be able to find some useful results from your testing. Whenever you post back with material you find worth updating, please include the direct links to the relevant section. Anchor links can be found by pointing to the relevant section title to see if any link bubble appears at the end of the text. From there you will be able to right-click and copy the link, regardless if the section heading is part of the main anchor link list on the right hand side of the screen.

Also, please consider posting the full example code that you think should be corrected to be a fully working example and add the MarkDown code block fence ```XML (3 back ticks followed by the name of the type of code within the code block). See also https://guides.github.com/features/mastering-markdown/ for more information on how to use MarkDown in Github comments.

BTW, if you want to write more regular text after a code block, remember to add 3 back ticks ( **```** ) on a blank line after the code, to stop the scope of the code block. This is what is referred to as "code block fencing" in MarkDown .

**Comment by j1mmyfever** [comment]
Let me try to word this right one more time.  

The <Config></Config> section is missing in this example.

```XML
<?xml version="1.0" encoding="utf-8" ?>
<AssignedAccessConfiguration
    xmlns="http://schemas.microsoft.com/AssignedAccess/2017/config"
    xmlns:v2="http://schemas.microsoft.com/AssignedAccess/201810/config"
    xmlns:v3="http://schemas.microsoft.com/AssignedAccess/2020/config"
>
    <Profiles>
        <Profile Id="{9A2A490F-10F6-4764-974A-43B19E722C23}">
            <AllAppsList>
                <AllowedApps>
                    <App AppUserModelId="Microsoft.Microsoft3DViewer_8wekyb3d8bbwe!Microsoft.Microsoft3DViewer" v2:AutoLaunch="true" v2:AutoLaunchArguments="123"/>
                    <App AppUserModelId="Microsoft.BingWeather_8wekyb3d8bbwe!App" />
                    <App AppUserModelId="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge" />
                    <App DesktopAppPath="%SystemRoot%\system32\notepad.exe" />
                </AllowedApps>
            </AllAppsList>
            <StartLayout>
                <![CDATA[<LayoutModificationTemplate xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout" xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout" Version="1" xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification">
                      <LayoutOptions StartTileGroupCellWidth="6" />
                      <DefaultLayoutOverride>
                        <StartLayoutCollection>
                          <defaultlayout:StartLayout GroupCellWidth="6">
                            <start:Group Name="Life at a glance">
                              <start:Tile Size="2x2" Column="0" Row="0" AppUserModelID="microsoft.windowscommunicationsapps_8wekyb3d8bbwe!microsoft.windowsLive.calendar" />
                              <start:Tile Size="4x2" Column="0" Row="4" AppUserModelID="Microsoft.WindowsStore_8wekyb3d8bbwe!App" />
                              <!-- A link file is required for desktop applications to show on start layout, the link file can be placed under
                                   "%AllUsersProfile%\Microsoft\Windows\Start Menu\Programs" if the link file is shared for all users or
                                   "%AppData%\Microsoft\Windows\Start Menu\Programs" if the link file is for the specific user only 
                                   see document https://docs.microsoft.com/windows/configuration/start-layout-xml-desktop
                              -->
                              <!-- for inbox desktop applications, a link file might already exist and can be used directly -->
                              <start:DesktopApplicationTile Size="2x2" Column="2" Row="0" DesktopApplicationLinkPath="%AllUsersProfile%\Microsoft\Windows\Start Menu\Programs\Accessories\paint.lnk" />
                              <!-- for 3rd party desktop application, place the link file under appropriate folder -->
                              <start:DesktopApplicationTile Size="2x2" Column="4" Row="0" DesktopApplicationLinkPath="%AppData%\Microsoft\Windows\Start Menu\Programs\MyLOB.lnk" />
                            </start:Group>
                          </defaultlayout:StartLayout>
                        </StartLayoutCollection>
                      </DefaultLayoutOverride>
                    </LayoutModificationTemplate>
                ]]>
            </StartLayout>
            <Taskbar ShowTaskbar="true"/>
        </Profile>
    </Profiles>
    <Configs>
<!-- ITS MISSING HERE-- >
        <v3:GlobalProfile Id="{9A2A490F-10F6-4764-974A-43B19E722C23}"/>
<!-- ITS MISSING HERE -->
    </Configs>
</AssignedAccessConfiguration>

**Comment by illfated** [comment]
Very good, thank you for the full inclusion. I very much enjoy seeing MarkDown being utilized for what it is worth here on Github.

@e0i : Do you think we can check with the document author if a PR with this change can be accepted for the missing items mentioned above?

**Comment by e0i** [comment]
@illfated As always, Thank you for engaging with the community to make the docs better. Much appreciated.

> @e0i : Do you think we can check with the document author if a PR with this change can be accepted for the missing items mentioned above?

With the given scope, the best way to find out is to create a PR.

@j1mmyfever (or @illfated) Feel free to create a PR with the XML contents mentioned in the comments so that we roll it into review.

Note that we already would like to come up with a PR for this issue yet I am asking you first in case you are interested in doing the honor yourself. :smiley:

**Comment by illfated** [comment]
Looks good to me.

@j1mmyfever : Are you up for a Pull Request to the page, using your suggested XML inclusion?

**Comment by e0i** [comment]
The issues has been noted to be assigned. Thanks.

**Comment by Dansimp** [comment]
fixed in https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4998

**Comment by dacabdi** [comment]
There is no issue here. The schema in https://docs.microsoft.com/en-us/windows/configuration/kiosk-xml#xsd-for-assignedaccess-configuration-xml specifies that `<v3:GlobalProfile>` is a special case, it does not nest under a `<Config>` but directly under the configurations list (`<Configs>` tag). Consider the following extract from the schema:

```xml
<xs:complexType name="config_list_t">
  <xs:sequence minOccurs="1" >
    <xs:element ref="v3:GlobalProfile" minOccurs="0" maxOccurs="1"/>
    <xs:element name="Config" type="config_t" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>
<xs:complexType name="config_t">
  <xs:sequence minOccurs="1" maxOccurs="1">
    <xs:choice>
      <xs:element name="Account" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="AutoLogonAccount" type="autologon_account_t" minOccurs="1" maxOccurs="1"/>
      <xs:element name="UserGroup" type="group_t" minOccurs="1" maxOccurs="1"/>
      <xs:element name="SpecialGroup" type="specialGroup_t" minOccurs="1" maxOccurs="1" />
    </xs:choice>
    <xs:element name="DefaultProfile" type="profileId_t" minOccurs="1" maxOccurs="1"/>
  </xs:sequence>
</xs:complexType>
```

**Comment by illfated** [comment]
Fair point. @j1mmyfever , would you be able to give feedback to that comment?

**Comment by dacabdi** [comment]
I have applied the configuration myself and it works without nesting the `<v3:GlobalProfile>` inside a `<Config>` tag. In any case, the criteria for correctness should be the schema, which is the common agreement item. Another team member came to me asking why her configuration was not applying correctly and it was due to the confusion introduced by this change. I would recommend reverting this change.

**Comment by illfated** [comment]
I see. Good point. @Dansimp , do you concur with the suggestion above?

**Comment by j1mmyfever** [comment]
I want to say the problem actually occurs when you have an <Account> tag in the <Configs> section, I'll have to look at my examples at the office that I'm using.

**Comment by illfated** [comment]
Fair point, thank you for chiming in. Looking forward to your updated reply.

**Comment by MaratMussabekov** [comment]
Hello everyone, 
Looks like I was wrong, **GlobalProfile Id** must not be nested into **Config**, these two are at the same level under the **Configs**.
@dacabdi, thank you for clarification
