### ISSUE TITLE
How to offboard a Windows 10 machine that is no longer in operation

### ISSUE THREAD

**Issue by NigelClarkExient** [MicrosoftDocs/windows-itpro-docs#4768]
Please provide instructions on how to remove / clean up the machine list of those machines that are no longer actively in operation.  Leaving them skews the reports making it hard to see the inactive machines that need attention over those that do not.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25f5ab5a-e755-9139-83c5-d6192b9a3e91
* Version Independent ID: 6e93cf86-0e83-5282-f659-e535c4ac35e2
* Content: [Offboard machines from the Microsoft Defender ATP service](https://docs.microsoft.com/en-gb/windows/security/threat-protection/microsoft-defender-atp/offboard-machines)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/offboard-machines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/offboard-machines.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @NigelClarkExient, we believe your question will be best answered by Windows 10 support. The available documentation right now is only for offboarding machines but that will not delete machines from your list. You can open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance. You can also check related posts/conversations at the [Technet forums](https://social.technet.microsoft.com/Forums/home) and the [Tech Community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities), and ask questions, interact with other users, experts and also Microsoft engineers. For example, there is this [ongoing discussion](https://social.technet.microsoft.com/Forums/ie/en-US/e76ef514-9b52-4e1a-aaf6-451b7d26476c/how-to-delete-a-machine-client-in-windows-defender-atp?forum=WindowsDefenderATPPreview) on how to delete machines, but so far, it appears that there is no way. A latest post from the community says;

> Machines that were not offboarded and are not in use anymore for whatever reason, disappear after your data retention passes. This is 30 to 180 days depending on your setting.

If you contact support, please keep us posted here on the resolution, information or improvements that can be called out in the docs. We want users to have the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, relevant and up-to-date.

**Comment by jvsam** [comment]
Hello again @NigelClarkExient, we didn’t hear back from you but we hope your issue has been resolved or at least, you've found a way on how to manage/remove inactive machines in Windows Defender ATP.  We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
