### ISSUE TITLE
Connectivity Policy CSP

### ISSUE THREAD

**Issue by optomux** [MicrosoftDocs/windows-itpro-docs#477]
There seems to be a bug in Windows 10 Enterprise N 1709 regarding Connectivity Policy CSP.
It says clearly "Added in Windows 10, version 1703." So it should work well it doesn't.
Does someone at Microsoft actually test this? 

Yet it works on the latest Preview builds 17083 etc. 

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\current\device\Connectivity]
"AllowConnectedDevices"=dword:00000000
```

It will not restrict the Shared Experiences page in System.
![shared](https://user-images.githubusercontent.com/10778276/35972582-4f5f379c-0c87-11e8-8682-62f2b52470b8.PNG)

**Comment by mypil** [comment]
@MariciaAlforque - We would like to follow up on this. Do you have any updates?

Thanks.

**Comment by mypil** [comment]
@optomux -  May we know which Microsoft document link you used in reference to this issue? 
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@optomux - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
