### ISSUE TITLE
Typo mistake in this document

### ISSUE THREAD

**Issue by rjbutt** [MicrosoftDocs/windows-itpro-docs#4770]
Hi Team, 

We have typo mistakes under "Skype for Business" section of this page. Please see below typo mistakes. there is an additional 's' after "the Skype for Business integration provides s " and we have o added after through and i believe it should be device owner through a simple button" instead of device owner through ao simple button.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cdec3d1-2aa7-c1c5-003f-a938ae32cd6f
* Version Independent ID: 84a60c18-6188-4712-f94c-e64a2a92d666
* Content: [Microsoft Defender ATP in Microsoft Threat Protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/threat-protection-integration#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/threat-protection-integration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/threat-protection-integration.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign jvsam

**Comment by rjbutt** [comment]
I also modified the github and submitted the change for approval.

**Comment by e0i** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
Ref. #4767

**Comment by jvsam** [comment]
Thank you for bringing this to our attention @rjbutt. The good news is, there was already a submitted pull request that fixes the same issue you have identified (see PR #4767) prior to your [commit](https://github.com/rjbutt/windows-itpro-docs/commit/0e2247d6ef0fa0f2f1bae0c48eb938cda8b397ec). But thanks as well for proactively creating one. PRs are normally reviewed/merged in the order of submission but once approved, they will be displayed here at docs.microsoft.com site in the next scheduled publishing run. 

We always strive to give users the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, accurate and up-to-date. Again, thank you for your feedback

**Comment by rjbutt** [comment]
Thanks @Jvsam. I appreciate you guys are doing a phenomenal job. I raised this issue on MVP distribution group and I was being told by fellow MVP to submit here:) I didn't know someone has already submitted this. Long story short, it's fixed and that what we need :)

**Comment by jvsam** [comment]
You're welcome @rjbutt. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation. Thank you for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
close

**Comment by jvsam** [comment]
close #4770

**Comment by jvsam** [comment]
@officedocsbot close
