### ISSUE TITLE
Error Event ID is invalid

### ISSUE THREAD

**Issue by damochiz** [MicrosoftDocs/windows-itpro-docs#4775]
The translation of the error event ID into Japanese is strange and cannot be understood.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 13006cbf-ad22-e75a-bf3a-2a6d0b92f088
* Version Independent ID: c9a7a12f-2ef5-b5fa-b515-41ecce5fecd1
* Content: [Microsoft Defender ATP のオンボードの問題のトラブルシューティング](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-onboarding#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/troubleshoot-onboarding.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-onboarding.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
@damochiz : Are you referring to the **イベント ID** column, which should read

Event ID |
:---|
 5 |
10 |
15 |
15 |
30 |
35 |
40 |
65 |

... but instead shows this?

イベント ID |
:---|
 個 |
常用 |
マート |
マート |
求める |
35 |
40 |
65 |

**Comment by jvsam** [comment]
Hi again @damochiz, thank you and your clarification will greatly help. Can you please confirm @illfated's question? This will help the Localization team identify immediately where the issue is. 

@officedocsbot assign @TinaMcN

**Comment by jvsam** [comment]
@officedocsbot assign @TinaMcN

**Comment by damochiz** [comment]
Hi @TinaMcN<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTinaMcN&data=02%7C01%7Cdamochiz%40microsoft.com%7C683ed699de4f458277cf08d728eac561%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637022861112584662&sdata=OIUAjl4c7FhOfDfZELlGMTnZOayCoBgG1jxjrCMH8GE%3D&reserved=0>,

Sorry to late response. Yes, I want you to change it as you suggested!

Thanks,
Daigo Mochizuki

**Comment by illfated** [comment]
Very well, fair enough. Even though this helps pointing out the issue, I still presume it is going to need human translation to verify the quantity of translation issues for that page, seeing that the Event ID column is affected in more than 1 table and that it could affect the other table columns as well, particularly the internal table references between the columns.

**Comment by damochiz** [comment]
Okay, next I'll give you feedback with the table name and Japanese translation. Thank you for your immediate confirmation.

Best Regards,
Daigo Mochizuki

**Comment by illfated** [comment]
Oh. Sorry for not being clear enough. Even though the information from you helps us pointing out what exactly is wrong, the assigned Microsoft Docs team member will inform us within a few days that this page needs to be sent for human translation (the machine translation clearly missed out on a few details). I presume she will send along the related information to point out the incorrect parts, but I also presume the human translation will be performed by someone who knows Japanese well. The translation could take some time, though.

In contrast to the English (US) pages, localized pages are not yet released on Github, so the localized pages will be handled internally (until further notice some time in the future).

**Comment by damochiz** [comment]
Hi Trond,
I understood what you mentions. There is no need to rush to fix it, but I'm looking forward.
Thank you so much.

Best Regards,
Daigo

**Comment by TinaMcN** [comment]
@damochiz 記事は現在、人間翻訳されており、問題は修正されているようです。 修正済みであることを確認してください。 フィードバックをありがとうございました。
(The article is now human translated and the issue appears to be fixed.  Please verify that it is fixed.  Thanks again for the feedback.)

**Comment by jvsam** [comment]
Thank you so much for the update @TinaMcN. 

Hi @damochiz, since this issue is now resolved, we can close it. Please continue to send your feedback and suggestions to improve the quality of the Microsoft documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by AmadorM** [comment]
I have encountered the same problem comparing the Spanish version of the article with the English version. In the event table for script execution.
![E](https://user-images.githubusercontent.com/51479071/82042284-eb53d280-96a9-11ea-8bd3-0ea3d5a3953a.png)
![S](https://user-images.githubusercontent.com/51479071/82042293-edb62c80-96a9-11ea-9967-590bc301acbf.png)
