### ISSUE TITLE
Confusing and misleading steps around setting up Device registration with the powershell command.

### ISSUE THREAD

**Issue by RobG-MSFT** [MicrosoftDocs/windows-itpro-docs#4776]
Service Connection Point (SCP) in Active Directory for ADFS Device Registration Service

The above section, where it is giving a powershell script to create a AD object within the configuration container for Device Registration seems to actually not be needed.

Following the directions it seems that AD FS 2016 when enabling Device Registration via the AD FS Management console it creates the object that powershell tries to create and actually also creates the keyword value with the DNS name used on the ADFS Service.  So I am not sure that this section is even needed, or at best it should probably be stated to validate that the device registration container and object exists and that they keyword attribute has the proper data in it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b063e00b-84e5-9da7-2229-e0e24da3b877
* Version Independent ID: da9f4867-2aa3-aefa-1603-ddb2ab1ed624
* Content: [Prepare and Deploy Windows Server 2016 Active Directory Federation Services (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
> The above section, where it is giving a powershell script to create a AD object within the configuration container for Device Registration seems to actually not be needed.

Hi @RobG-MSFT, thank you so much for that information. Just to clarify, do you mean the entire *[Service Connection Point (SCP) in Active Directory for ADFS Device Registration Service](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs#service-connection-point-scp-in-active-directory-for-adfs-device-registration-service)* section is not needed in deploying Windows Server 2016 ADFS? Or as you have suggested, add a messaging (*perhaps a note?*) that informs user about this:

"*...at best it should probably be stated to validate that the device registration container and object exists and that they keyword attribute has the proper data in it.*

Hello @mapalko, hope all is well. Can you please assist us in validating the requested content change? Thank you.

**Comment by jvsam** [comment]
Hello again @mapalko how are you? I just want to follow-up if you had a chance to review and validate the proposed content changes? If valid, we can create a PR with the changes and submit them to you for review. Thank you and looking forward to your feedback.

**Comment by jvsam** [comment]
Hello again @mapalko apologies for another follow-up. If time permits, can you please look at the proposed updates to this documentation? Thank you again.

**Comment by jvsam** [comment]
Hi @mapalko, do you have any feedback regarding this request? Thank you.

**Comment by jvsam** [comment]
Hello again @mapalko, following up if you have feedback on the proposed content changes? If it's accurate, we can create a PR that you can review? Thank you.

**Comment by RobG-MSFT** [comment]
Hey Jvsam,

So yes I was referring to the whole SCP content.  I would agree that a customer should know about the existence of the SCP object within AD, and if missing be shown how to Troubleshoot that, however When I set this up in my lab the SCP was already created and the when I ran the script it was failing so it really needs to be state that the script should realistically not be needed in normal situations.  As far as the proposed content, I am not seeing this in the comment section.  I am an MS CSS employee so if you hopefully can figure out my alias internally if you would like to send me a copy via mail.

**Comment by jvsam** [comment]
> I set this up in my lab the SCP was already created and the when I ran the script it was failing so it really needs to be state that the script should realistically not be needed in normal situations. 

Hi @RobG-MSFT, thanks for the explanation, that helps. We don't have the proposed content amendments yet, but will tag you here or I'll email you for confirmation.

@illfated, is this a topic that you are familiar with? Otherwise, I can forward this to the Windows content writing team for review. Let me know, thank you.

**Comment by illfated** [comment]
Thank you for asking, but I must admit that my field experience is only comparable to "helpdesk" level 1 & 2, mainly planning and managing incidents affecting users directly. I will only be able to provide Github contributions in this matter, be it creating a PR based on suggested content, or helping out others who are already working on a PR to resolve this issue ticket.

**Comment by jvsam** [comment]
That's fine, just wondering if you could assist with content creation :-) Thanks @illfated. Anyway, this issue has been forwarded to the Windows content writing team for review and investigation.

**Comment by jvsam** [comment]
Hi again @RobG-MSFT, I just want to inform you that the pull request (See PR #5305) that contains suggestions based from your feedback has been approved and merged. The documentation will be updated in the next scheduled publishing run. We will now close this issue, thank you again for feedback!

**Comment by jvsam** [comment]
@officedocsbot close
