### ISSUE TITLE
WIP for Domain Joined

### ISSUE THREAD

**Issue by iffarrukh** [MicrosoftDocs/windows-itpro-docs#4779]
Hi
so we can configure WIP for BYOD devices using Intune..
How we can configure WIP for domain joined/Hybrid AD devices?? would SCCM be the way and the only option?

**Comment by e0i** [comment]
@officedocsbot assign @jvsam

**Comment by iffarrukh** [comment]
Hi 
Any  update on this?

**Comment by illfated** [comment]
Please note that this issue tracker is first and foremost dedicated to improving the quality of the Microsoft Windows IT Pro Docs pages. Secondly, issues posted on the Docs pages should usually be linked to the page your question originated from, meaning that something went wrong when you posted your question directly in the issue tracker instead of opening a page issue.

**Comment by jvsam** [comment]
Thanks for your question @iffarrukh. To reiterate what @illfated have said, this Github site is used as a feedback system to help improve the quality of the technical documentation of Microsoft Docs. If you have concerns related to specific Microsoft products, features or services, we recommend that you open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance. You can also check the [Technet forums](https://social.technet.microsoft.com/Forums/home) and the [Tech Community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities) where you can ask questions and interact with other users, experts and also Microsoft engineers.

> How we can configure WIP for domain joined/Hybrid AD devices?? would SCCM be the way and the only option?

As per the docs, you can run WIP in your enterprise using [Microsoft Intune](https://docs.microsoft.com/ewindows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure), [SCCM](https://docs.microsoft.comwindows/security/information-protection/windows-information-protection/create-wip-policy-using-sccm) or supported MDM solutions. Here's the [doc set](https://docs.microsoft.com/windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip) for Windows Information Protection (WIP). Here's an interesting [blog post](https://www.microsoft.com/security/blog/2018/05/15/use-windows-information-protection-wip-to-help-make-accidental-data-leakage-a-thing-of-the-past/) that provides more information:

> WIP policy can be deployed in a few clicks in Microsoft Intune for MAM-only (“without enrollment”) targeting, MDM (“with enrollment”), or both. Being able to apply MAM-only policy will help you finally enable BYOD in regions and situations where fully managing the personal device is unacceptable. For companies that are not yet fully in the cloud, WIP policy can also be set on domain-joined computers using System Center Configuration Manager. Then, when you’re ready for co-management, you can move the WIP policy management authority to Microsoft Intune.

We always welcome feedback to improve the docs. If you have suggestions, please utilize the *Feedback* section on the content page moving forward to easily track Github issues. Thank you!

![image](https://user-images.githubusercontent.com/18371314/64073563-7c2c7e80-ccd2-11e9-8d8d-e69cd926111c.png)

**Comment by jvsam** [comment]
Hi again @iffarrukh, we didn’t hear back from you but we hope you were able to find the information you need. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
