### ISSUE TITLE
USB Copy

### ISSUE THREAD

**Issue by iffarrukh** [MicrosoftDocs/windows-itpro-docs#4780]
Hi

I have a WIP policy with RMS. The files are protected within one drive . If I copy a file to any other location (e.g. c:\test} it says encrypted but when I copy the file to a USB drive, it become unencrypted.. Why is this behaviour and how I can prevent it?

**Comment by e0i** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
@iffarrukh : Please notice that this issue tracker is used for improving the Microsoft Docs pages. The assigned Microsoft Docs team member will get back to you with recommendations for Microsoft Support instances worth contacting to get your issue resolved. In the meanwhile, feel free to refer to the related document page where you tried to post your question and whether the page can be improved upon to answer questions like yours.

**Comment by jvsam** [comment]
Hi again @iffarrukh, similar to my response on #4779, it's better to contact the experts, they're equipped with the technical knowledge necessary to resolve your concern or answer any questions you may have. Kindly refer to these recommendations:

1. Ask question in the [Technet forums](https://social.technet.microsoft.com/Forums/home) and the [Tech Community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities).
2. [Contact Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10).

Also, have you had a chance to look at the [Windows Information Protection (WIP) doc set](https://docs.microsoft.com/windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip)? The[ WIP testing scenarios](https://docs.microsoft.com/windows/security/information-protection/windows-information-protection/testing-scenarios-for-wip) and [limitations](https://docs.microsoft.com/windows/security/information-protection/windows-information-protection/limitations-with-wip) may provide more insights. 

Thank you.

**Comment by jvsam** [comment]
Hi @iffarrukh, we hope that you were able to contact Windows 10 Support and get the answers to your questions. If you have suggestions or ideas to improve the quality of this documentation, please let us know or use the Feedback feature on the docs. We will now close this issue, thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
