### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by marcorpsa** [MicrosoftDocs/windows-itpro-docs#4784]
First link in See Also
What's New in Windows Server, version 1903: New and updated features in Windows Server.
Gives 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 095d9daa-2d4e-7442-13a1-79d15b313ad7
* Version Independent ID: c33e2393-9f53-d896-e154-42058ecf4dbf
* Content: [What's new in Windows 10, version 1903](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1903#feedback)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1903.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1903.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay

**Comment by e0i** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
OK, am fairly sure I can see what is wrong about the link:
- https://docs.microsoft.com/windows-server/get-started/whats-new-in-windows-server-1903 (404)
- https://docs.microsoft.com/windows-server/get-started-19/whats-new-in-windows-server-1903 (OK)

**Comment by jvsam** [comment]
Thanks for letting us know about this @marcorpsa. And yes, that's the correct link @illfated, thank you.

Anyway, I will forward this to the Windows content writing team for correction. @marcorpsa, we always strive to improve the quality of the technical documentation of Microsoft Docs so your feedback is appreciated! Thank you again.

**Comment by illfated** [comment]
Thank you for confirming my assumption, @jvsam . Would you like me to open a PR to amend that first link in the section https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1903#see-also ?

**Comment by jvsam** [comment]
Hi @marcorpsa, we'd like to inform you that the pull request (see PR #4830) that *fixes the broken link* has been approved and merged. The update will be displayed here at docs.microsoft.com in the next scheduled publishing run. Thank you again for your feedback and for being part of the Microsoft Docs community!
