### ISSUE TITLE
Taskbar Layout

### ISSUE THREAD

**Issue by jeffdfield** [MicrosoftDocs/windows-itpro-docs#4787]
This cmdlet works just fine but I wish there was a switch to also export the taskbar layout since the XML supports this functionality but the cmdlet doesn't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79fccecd-5484-0304-d82b-9425f1889a22
* Version Independent ID: 4df6b138-c1b5-b551-22c9-19d3d1f9105d
* Content: [Customize and export Start layout (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/customize-and-export-start-layout)
* Content Source: [windows/configuration/customize-and-export-start-layout.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/customize-and-export-start-layout.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by e0i** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jeffdfield - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via **[Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by Typhoon87** [comment]
In case anyone else finds this:
I actually just submitted such a request a few days ago to have an optional switch when exporting the start menu to have it also export the custom taskbar. https://aka.ms/AA6f388
