### ISSUE TITLE
Deployment Guidance

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#4790]
Hello, 

Is my understanding correct that all the settings that are described in "Level 1 Basic Enterprise Security"  https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-security-configuration-framework/level-1-enterprise-basic-security are those settings that we find in the current Windows 10 1903 security baseline that can be downloaded from here
https://www.microsoft.com/en-us/download/details.aspx?id=55319

and that all the additional settings described in  Level 2 - 5 must be configured manually on top of level 1 as currently these profiles are not yet included in the security compliance toolkit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3fa1093-f014-b19a-0a3f-621bb239b23d
* Version Independent ID: eaf6cb9a-9d2a-5ea0-71ba-0801e073d49e
* Content: [Windows security configuration framework](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-security-configuration-framework/windows-security-configuration-framework)
* Content Source: [windows/security/threat-protection/windows-security-configuration-framework/windows-security-configuration-framework.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-security-configuration-framework/windows-security-configuration-framework.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@alexverboon - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @alexverboon, no, Level 1 Basic Enterprise Security and Security Baseline are different sets of rules.
You can check it by comparing the values in "GP reports" folder in Security Baseline and values in [Level 1](https://docs.microsoft.com/windows/security/threat-protection/windows-security-configuration-framework/level-1-enterprise-basic-security).
For example, Security Baseline contains User Policies, that are not presented in Level 1 (they are part of Level 2 configuration)
Thank you

**Comment by mypil** [comment]
@alexverboon - From our understanding, the issue has been answered by MaratMussabekov. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by alexverboon** [comment]
This is the response I received from @appcompatguy Chris Jackson

The *policies* for Level 3 represent the entirety of the Security Baselines. Levels 1 and 2 are a subset. All levels supplement policies with controls and behaviors. Make sense?
