### ISSUE TITLE
May 2019 MBAM servicing release

### ISSUE THREAD

**Issue by jandreacola** [MicrosoftDocs/windows-itpro-docs#4796]
This documentation doesn't mention the May 2019 servicing release that adds support for Win10 1903

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 604e3922-8536-4cb7-5df7-beb0b7087e58
* Version Independent ID: 4c824538-1e43-8779-63e3-7f2183a9c95a
* Content: [Upgrading to MBAM 2.5 SP1 from MBAM 2.5](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/upgrading-to-mbam-25-sp1-from-mbam-25)
* Content Source: [mdop/mbam-v25/upgrading-to-mbam-25-sp1-from-mbam-25.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/upgrading-to-mbam-25-sp1-from-mbam-25.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jandreacola - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by illfated** [comment]
Oh. I see. I updated the link to MDOP May 2019 Servicing Release in my PR #4592, but nobody mentioned references to the 2018 vs 2019 version in other documentation pages.
See also:
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/apply-hotfix-for-mbam-25-sp1.md
- https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/apply-hotfix-for-mbam-25-sp1

I don't have personal experience from using this software in a work environment, so would you be able to verify if it would be enough to update the 3 links ([Desktop Optimization Pack](https://www.microsoft.com/download/details.aspx?id=57157) + https://www.microsoft.com/download/details.aspx?id=57157) and change the occurrences of **Download the July 2018 servicing release** to **Download the May 2019 servicing release**, something like the following?
***
# Upgrading to MBAM 2.5 SP1 from MBAM 2.5
This topic describes the process for upgrading the Microsoft BitLocker Administration and Monitoring (MBAM) Server 2.5 and the MBAM Client from 2.5 to MBAM 2.5 SP1.

### Before you begin
#### Download the May 2019 servicing release
[Desktop Optimization Pack](https://www.microsoft.com/download/details.aspx?id=58345)

#### Verify the installation documentaion
Verify you have a current documentation of your MBAM environment, including all server names, database names, service accounts and their passwords.

### Upgrade steps
#### Steps to upgrade the MBAM Database (SQL Server)
1. Using the MBAM Configurator; remove the Reports role from the SQL server, or wherever the SSRS database is hosted. Depending on your environment, this can be the same server or a separate one.
   Note: You will not see an option to remove the Databases; this is expected.
2. Install 2.5 SP1 (Located with MDOP - Microsoft Desktop Optimization Pack 2015 from the Volume Licensing Service Center site:  <https://www.microsoft.com/Licensing/servicecenter/default.aspx>
3. Do not configure it at this time
4. Install the May 2019 Rollup: https://www.microsoft.com/download/details.aspx?id=58345
5. Using the MBAM Configurator; re-add the Reports role
6. This will configure the SSRS connection using the latest MBAM code from the rollup
7. Using the MBAM Configurator; re-add the SQL Database role on the SQL Server.
8. At the end, you will be warned that the DBs already exist and  weren’t created, but this is expected.
9. This process updates the existing databases to the current version  being installed

#### Steps to upgrade the MBAM Server (Running MBAM and IIS)
1. Using the MBAM Configurator; remove the Admin and Self Service Portals from  the IIS server
2. Install MBAM 2.5 SP1
3. Do not configure it at this time
4. Install the May 2019 Rollup on the IIS server (https://www.microsoft.com/download/details.aspx?id=58345)
5. Using the MBAM Configurator; re-add the Admin and Self Service Portals to the IIS server
6. This will configure the sites using the latest MBAM code from the May 2019 Rollup
7. Open an elevated command prompt, Type: **IISRESET** and Hit Enter.

#### Steps to upgrade the MBAM Clients/Endpoints
1. Uninstall the 2.5 Agent from client endpoints
2. Install the 2.5 SP1 Agent on the client endpoints
3. Push out the May 2019 Rollup Client update to clients running the 2.5 SP1 Agent
4. There is no need to uninstall the existing client prior to installing the May 2019 Rollup.

***
(I would have made a more condensed sample, if it was not for the fact that the changes span from the first link (5. line of text) and all the way down to the last line.)

**Comment by MaratMussabekov** [comment]
Dear @illfated, I do not have experience with that product too, but according to [release notes](https://support.microsoft.com/help/4505175/may-2019-servicing-release-for-microsoft-desktop-optimization-pack), update process shouldn't been changed, so I think your suggestion fits perfect.
What do you think?
Thank you

**Comment by illfated** [comment]
Thank you for your comment. I was a bit uncertain about the difference between Microsoft BitLocker Administration and Monitoring (MBAM) and Microsoft Desktop Optimization Pack (MDOP), but I see that you have already opened a PR to resolve this ticket. Thank you for doing the job, it saved me from still being insecure about that change.

**Comment by illfated** [comment]
The PR was merged into the master branch 50 minutes ago
(as of the time of this comment).

**Comment by mypil** [comment]
@jandreacola - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
