### ISSUE TITLE
RunAs Account

### ISSUE THREAD

**Issue by woodrum** [MicrosoftDocs/windows-itpro-docs#4797]
Not sure if there's any difference, but for Server 2019, I needed to manually modify the XML file after creating it to run as "NT AUTHORITY\SYSTEM".  Using anything else gave me application log error 4098 and error code 0x80070534 (no mapping between account names and security ID's).  I did stumble on the same articles mentioned in the other closed notice and had no luck with them either.  Once I got this configured the GPO applied appropriately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27dbd025-8239-9847-b07e-378ca87d2d75
* Version Independent ID: 4b0e4ac7-a608-7c62-dcd4-2db628b3f67a
* Content: [Onboard Windows 10 machines using Group Policy to Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-gp)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-gp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-gp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@woodrum - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@woodrum - We appreciate your efforts to clarify the docs.

Could you please assist us by providing more details on how this content could be edited to incorporate your feedback? If you could suggest what the appropriate text and where it should be placed, I could assign one of our team members to create a Pull Request to get it added or you may also create a Pull Request to add in your suggestion and just link this issue so I can have the doc owner review and merge the content. 

Thank you.

**Comment by woodrum** [comment]
Sure… basically I had to modify the XML file created in GP Preferences for the scheduled task to be run by “NT AUTHORITY\SYSTEM” (2 places in the XML I updated).  By default, it creates the job with “NT AUTHORITY\WELL-KNOWN-SYSTEM-ACCOUNT-ID” (or something similar to that).

**Comment by joinimran** [comment]
@woodrum Can you please confirm what type of modification you have made in the file so that it can run using NT Authority\SYSTEM so that we can add a note in the document.

**Comment by woodrum** [comment]
Yes, in the XML file that the GP Preference creates in the scheduled task folder, replace the NT AUTHORITY\Well-Known-System-Account with NT AUTHORITY\SYSTEM.  It’s in 2 locations inside that XML file.

**Comment by mypil** [comment]
@woodrum - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
