### ISSUE TITLE
What has replaced Windows To Go?

### ISSUE THREAD

**Issue by RobertDAllen** [MicrosoftDocs/windows-itpro-docs#4799]
The note about deprecation lacks any actionable information. What has replaced Windows To Go?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93868b54-1342-6a97-ea84-ab75066c837b
* Version Independent ID: 8ee0f61c-67cd-9df6-a8e9-b854d8134587
* Content: [Windows To Go feature overview (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-to-go-overview#feedback)
* Content Source: [windows/deployment/planning/windows-to-go-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-to-go-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@RobertDAllen - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@greg-lindsay - Can you please share your insights on this issue?

Thank you.

**Comment by RobertDAllen** [comment]
My expectation is that I can install Windows on a USB drive, equivalent in
all ways to Linux Live.

My intention is to have my personal computer on a 256gb USB drive which is
hardware agnostic, hosting my Office, Dropbox, and Adobe CS. This prevents
me from having files stranded on 'my other computer'.

My alternative right now is using a Chromebook, accessing my 'master
device' via Chrome Remote Desktop. This has worked for years, but the
allure of having a PC on USB remains.

Notes:
Windows To Go requires a HDD, barring USB drives, which is prohibitive on
form factor and seems highly unnecessary.
The asserted requirement of otherwise-specialized hardware seems wildly
unnecessary.

**Comment by greg-lindsay** [comment]
There is no 1:1 replacement solution for WTG. You can use WVD (Windows Virtual Desktop) if a cloud-based solution is acceptable. There are also some non-Microsoft solutions available - I can't recommend any but you can research them, and I have heard it's possible to use DISM to install Windows on a USB drive. This isn't something I've done but I can try it and provide the steps if you are interested in that.

Also note that if you use WTG to install (for example) Windows 10 Enterprise 2019 LTSC then that version is supported for the lifetime of the OS which is 2024 for LTSC (https://docs.microsoft.com/en-us/windows/release-information).

**Comment by mypil** [comment]
@RobertDAllen - From our understanding, the issue you raised has been answered by greg-lindsay. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
