### ISSUE TITLE
RegistrarPool suggestion

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/windows-itpro-docs#4801]
I was having trouble with the RegistrarPool command with the error "Cannot move user in enable operation. Use the Move user cmdlet instead." I started digging around to see if other people had solutions, and I found from this docs page ("https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/with-exchange-online") a different method of finding the Registrar value. It seemed that the RegistrarPool value running the command was a different pool than the one my user account was in. Once I pulled it from the below command, it worked:

Get-CsOnlineUser -Identity 'alice@contoso.com'| fl *registrarpool*

Maybe update this doc with that line, if that is a valid way of finding it. Helped me a bit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d162274-cb93-ae64-d648-5a44fa3c710d
* Version Independent ID: c1ebb6f7-81ab-7eea-42da-18c2898b933e
* Content: [Online deployment with Office 365 (Surface Hub)](https://docs.microsoft.com/en-us/surface-hub/online-deployment-surface-hub-device-accounts#feedback)
* Content Source: [devices/surface-hub/online-deployment-surface-hub-device-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/online-deployment-surface-hub-device-accounts.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
Just to be precise, quoting the command you wrote looks like this
(MarkDown code block used to avoid asterisks being read as formatting characters) :
```PowerShell
Get-CsOnlineUser -Identity 'alice@contoso.com'| fl *registrarpool*
```

**Comment by MaratMussabekov** [comment]
fixed mentioned issue and also changed section with the variable

**Comment by e0i** [comment]
@thedrum808 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.
