### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by kyjeeper** [MicrosoftDocs/windows-itpro-docs#4806]
Technician is spelled incorrectly: Technican Flow

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5b57d1-61b3-39d4-34ff-d6dcb858c250
* Version Independent ID: 42609104-815f-9e7a-39aa-38d92cc910c9
* Content: [Windows Autopilot for white glove deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove)
* Content Source: [windows/deployment/windows-autopilot/white-glove.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/white-glove.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
