### ISSUE TITLE
Reboot-csp.md needs clearer guidance on removing scheduled nightly reboots

### ISSUE THREAD

**Issue by lanatmwan** [MicrosoftDocs/windows-itpro-docs#4810]
The doc states you should input a null or empty date to get it to remove the scheduled reboot. The InTune UI doesn't let you input a null value. From another post, someone indicated that the right value is '0000-00-00T00:00:00+00:00'. If that is correct, it should be replace the advice to input a null date.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
Ref. #4811 - this ticket should also have been reported from the related document page instead of being opened as a ticket with no reference.

**Comment by e0i** [comment]
@lanatmwan

Somehow your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by illfated** [comment]
Intended references to the following document page(s):
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/reboot-csp.md
- https://docs.microsoft.com/en-us/windows/client-management/mdm/reboot-csp


|category|content|
|:---:|---|
|title:|Reboot CSP|
|description:|Reboot CSP|
|ms.assetid:|4E3F1225-BBAD-40F5-A1AB-FF221B6BAF48|
|ms.reviewer:|   |
|manager:|dansimp|
|ms.author:|dansimp|
|ms.topic:|w10|
|ms.prod:|article|
|ms.technology:|windows|
|author:|manikadhiman|
|ms.date:|06/26/2017|
