### ISSUE TITLE
Three servicing channels ?

### ISSUE THREAD

**Issue by qiexxii** [MicrosoftDocs/windows-itpro-docs#4813]
In [this page](https://docs.microsoft.com/en-us/windows/deployment/update/waas-overview),it said: *Windows 10 has three servicing channels*.

```text
To align with this new update delivery model, Windows 10 has three servicing channels, each of which provides different levels of flexibility over when these updates are delivered to client computers. 
```

But apparently there is only **2** servicing channels now. [Windows 10 and the “disappearing” SAC\-T \- Microsoft Tech Community \- 199747](https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/Windows-10-and-the-disappearing-SAC-T/ba-p/199747)

Preventing misunderstanding, change "three" to "two" in the article plz.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6957383-3bd9-eef9-6410-9c42f8a0b172
* Version Independent ID: a2090374-0fd1-8d67-66de-30c4cf2835f7
* Content: [Overview of Windows as a service (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-overview#servicing-channels)
* Content Source: [windows/deployment/update/waas-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by qiexxii** [comment]
My misunderstanding, there is three servicing channels now.

```text
With that in mind, Windows 10 offers three servicing channels. The Windows Insider Program provides organizations with the opportunity to test and provide feedback on features that will be shipped in the next feature update. ...
```
