### ISSUE TITLE
policies problem

### ISSUE THREAD

**Issue by fubolong** [MicrosoftDocs/windows-itpro-docs#4814]
I have got the error message "There was a problem applying your organization policies to your device.(0x82AA0001)". Which step might be wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d01bd8e-2800-21f2-0042-35d2de7f402b
* Version Independent ID: c63d6d9b-5f71-03ed-c0c7-e2d778aed3d1
* Content: [On-premises authentication device enrollment](https://docs.microsoft.com/en-us/windows/client-management/mdm/on-premise-authentication-device-enrollment#feedback)
* Content Source: [windows/client-management/mdm/on-premise-authentication-device-enrollment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/on-premise-authentication-device-enrollment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@fubolong 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by illfated** [comment]
A simple web search should give you an idea.
- https://www.bing.com/search?q=0x82AA0001

https://social.msdn.microsoft.com/Forums/azure/en-US/580afdbf-6b05-4f0d-a21c-b85be995e851/windows-phone-81-enrollment-rstr-contents?forum=developingmdmsolutions
error 0x82AA0001 indicates an XML parsing error, check to make sure you are sending well formed XML using UTF-8 encoding. (Tip: Use a binary editor to view the payload to make sure there are no hidden or unprintable characters.)
***
Eric Fleck, Windows Store and Windows Phone Developer Support. If you would like to provide feedback or suggestions for future improvements to the Windows Phone SDK please go to http://wpdev.uservoice.com/ where you can post your suggestions and/or cast your votes for existing suggestions.

**Comment by e0i** [comment]
Hello, @fubolong 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.
