### ISSUE TITLE
Can you please update the documentation ?

### ISSUE THREAD

**Issue by TheOtherBillGates** [MicrosoftDocs/windows-itpro-docs#4815]
AD FS with Azure MFA Server, Azure MFA Server has been deprecated and is unavailable since 1st July 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e5f5f1-16cf-57e2-bdfc-b090d90437b1
* Version Independent ID: 1662c47f-12cb-147d-25f0-dee98b6c7722
* Content: [Windows Hello for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-identity-verification.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-identity-verification.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by TheOtherBillGates** [comment]
Azure Multi-Factor Authentication Server provides a way to secure resources with MFA capabilities. As of July 1, 2019, Microsoft will no longer offer MFA Server for new deployments. New customers who would like to require multi-factor authentication from their users should use cloud-based Azure Multi-Factor Authentication. Existing customers who have activated MFA Server prior to July 1 will be able to download the latest version, future updates and generate activation credentials as usual.
Source: https://www.microsoft.com/en-us/download/details.aspx?id=55849

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by poortom1004** [comment]
Also Windows 10 build 1511 isn't supported anymore.

**Comment by poortom1004** [comment]
And Windows 10 build 1703 isn't supported anymore.

**Comment by e0i** [comment]
@mapalko Any plans to update the document in accordance with the developments? Let us know of any help in coming up with a PR if needed. Thank you.

**Comment by mapalko** [comment]
I do not plan on removing 1511 or 1703. Those are referenced as min builds which is still accurate. We updated the on-prem specific documentation around MFA server but not the table. I've submitted a PR to remove MFA server references.

**Comment by e0i** [comment]
Marking as resolved via document author's comment.
