### ISSUE TITLE
Reporting in Powerbi does not permit to 'sign in a different user'

### ISSUE THREAD

**Issue by simorjay** [MicrosoftDocs/windows-itpro-docs#4821]
Hi I have different user credentials for my Defender ATP, than my local user. For your dashboard I can use securitycenter using a private browser.

However I've been trying to use your PowerBi connector and it does not seem to honor the ability to change credentials. 
I've tried isolate the issue but the provided PowerBi reporting and desktop connector does not provide a means to use a different user that the currently logged in user. I've had a chance to test your connector both online, and in the powerbi desktop and the behavior is the same. 
When trying to connect incongnito - or inprivate the connector will not honor the privacy, and use the current logged in credentials for the connection.  Is there an update to the connector that will be released that will fix the data source / permission snag? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c94f17bc-9075-8816-0087-a58388c94266
* Version Independent ID: c024d528-b4bf-b069-c54f-764a04f27aa5
* Content: [Create and build Power BI reports using Microsoft Defender ATP data](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/powerbi-reports#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/powerbi-reports.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/powerbi-reports.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@simorjay 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
