### ISSUE TITLE
Linux distros, Android, and macOS version support

### ISSUE THREAD

**Issue by sinupeter** [MicrosoftDocs/windows-itpro-docs#4823]
Please mention in the page exact Linux distros, Android, and macOS versions that are compatible with Microsoft Defender ATP for the integration to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @sinupeter, thank you for your suggestion. However, I'd like to clarify if are you pertaining to the supported 3rd party platforms for the integrated endpoint protection? 

> You'll need to know the exact Linux distros, Android, and macOS versions that are compatible with Microsoft Defender ATP for the integration to work.

The above **note** on the doc will depend on the 3rd party partner *security service* that you would like to integrate. For example, Bitdefender’s GravityZone Cloud's supported endpoint operating systems are available [here](https://www.bitdefender.com/business/end-point-security-linux-mac.html) (see *Requirements* or download the *Datasheet*) or on their [FAQ](https://www.bitdefender.com/site/KnowledgeBase/viewarticle2012/1994) page. In short, it varies and we cannot guarantee that the information will not change, hence it's better to check the requirements on the website of the service that you would like to integrate with Microsoft WDATP.

Now, if my understanding of your request is incorrect, kindly provide more information. Thank you.

Reference: [Microsoft partners extend Windows Defender ATP across platforms](https://www.microsoft.com/microsoft-365/blog/2017/11/08/microsoft-partners-extend-windows-defender-atp-across-platforms/)

**Comment by jvsam** [comment]
Hi again @sinupeter, we didn’t hear back from you but we hope the information we've provided helped. We will now close this issue, however, feel free to re-open if you have relevant suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by sinupeter** [comment]
Well, that should be mentioned in the documentation thst 3rd Party support is required.

I am looking to know which operating system versions this agent can reside on - MacOS, Linux

Regards
Sinu

Sent from mobile so excuse any typos

________________________________
