### ISSUE TITLE
Diagnostics level requirements

### ISSUE THREAD

**Issue by jevgenij-martynenko** [MicrosoftDocs/windows-itpro-docs#4824]
The article states requirement to have diagnostics service running, but requirements of diagnostic level settings are not obvious (Basic, Enchanced, Full). 
What level of diagnostics settings is required for Defender ATP to work correctly? In case Defender ATP does not depend on diagnostics level, it could still help to state this fact.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
> What level of diagnostics settings is required for Defender ATP to work correctly? In case Defender ATP does not depend on diagnostics level, it could still help to state this fact.

Hello @jevgenij-martynenko, thank you for taking the time to open this issue and provide feedback regarding this documentation. 

Hi @mjcaparas, if you are not busy, can you please confirm if there is a required diagnostic data setting for Microsoft Defender ATP? Or the default level with at least the minimum set of data collection will suffice, as long as diagnostic data service is enabled?

- Basic - Default on Windows 10, version 1903 and later
- Enhanced - Default on Windows Server

We appreciate your help. Thank you in advance.

**Comment by jvsam** [comment]
Hello again @mjcaparas, hope all is well. Do you have any update on this? Thank you.

> Can you please confirm if there is a required diagnostic data setting for Microsoft Defender ATP? Or the default level with at least the minimum set of data collection will suffice, as long as diagnostic data service is enabled?

**Comment by mjcaparas** [comment]
Apologies for the delay. Checking with the team.

**Comment by jvsam** [comment]
No worries @mjcaparas, thank you for updating us.

**Comment by mjcaparas** [comment]
Hello, the team has verified that Microsoft Defender ATP doesn't require any specific diagnostic level. @jvsam the page can be updated to state this.

**Comment by jvsam** [comment]
Awesome, thank you so much for this update @mjcaparas . We'll create a PR and submit it for your review and approval.

**Comment by jvsam** [comment]
Hi again @jevgenij-martynenko, we'd like to inform you that the pull request (See PR #5067) that *clarifies the diagnostic level* has been approved and merged. The update will be displayed here at docs.microsoft.com in the next scheduled publishing run. Thank you again for your feedback and for being part of the Microsoft Docs community!
