### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by Sbarozzi** [MicrosoftDocs/windows-itpro-docs#4826]
Ciao, l orario dei log da chi viene attribuito ? Abbiamo dei server con l orario ok ma sui log l orario è futuro. Grazie

**Comment by e0i** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
**Translation using Bing Translator:**
> *Hello, the log time by whom is it attributed? We have servers with ok time but on the logs the time is future. Thank you*

Hello @Sbarozzi, unfortunately, this Github site is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. If you have questions or concerns regarding Microsoft products, features or services, we recommend that you open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance. 

If you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review. Thank you.

P.S. I am not sure if this [help doc](https://support.microsoft.com/help/271196/iis-log-file-entries-have-the-incorrect-date-and-time-stamp) will help, but please check it out.

**Comment by jvsam** [comment]
Hello again @Sbarozzi, we didn’t hear back from you but we hope your issue has been resolved. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
