### ISSUE TITLE
Currently no setting in Intune available

### ISSUE THREAD

**Issue by wbach82** [MicrosoftDocs/windows-itpro-docs#4827]
Is the setting in Intune Endpoint protection profile available right now? I dont see it in thress different tenants. Alle have E5 licenses

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a2f0402-82fb-83ff-122a-2f19c5288eeb
* Version Independent ID: 52f80b09-0e90-464d-0c4d-00479361fa9b
* Content: [Protect security settings with Tamper Protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection?lc=1031)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by e0i** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @wbach82, as stated on this doc, Windows 10 Enterprise E5 customers can manage the *Tamper Protection* setting from Intune (and it's currently in preview). There are conditions that must be met first for it to be available in the Intune management console which are listed on this doc. If you've met all of them and still, you are unable to see *Tamper Protection* under Windows Defender Security Center, I would recommend that you [contact Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10). Interestingly, there is a [question in the TechNet forum](https://social.technet.microsoft.com/Forums/forefront/en-US/889cf365-f071-48b7-84df-e5c5f53c5516/defender-tamper-protection-missing-from-gui-after-it-is-enabled?forum=win10itprosecurity) that provides some insights. A community user shared an external link (*we cannot confirm or guarantee its accuracy though*) where another user contacted support and this was the explanation:

> “…On Enterprise SKU the feature is disabled by default and is expected to be managed by GPO, SCCM, and Intune etc. However GPO and SCCM functionality has not been enabled as of yet, and only Intune works. It also must be a machine onboarded by Defender ATP, so it needs Intune, WDATP, and be an enterprise SKU to use with an E5 license if you wish to preview it. Without all 3, you cannot even turn it on yet on the Enterprise SKU if the client is managed...

It will be best to confirm the information from Windows 10 support. I am using *Pro* not *Enterprise* and it does not show.

![image](https://user-images.githubusercontent.com/18371314/64253432-e140d800-cf4f-11e9-9665-f61bc6faedcc.png)

Also, kindly keep us informed on the resolution or any relevant information you may find that can be incorporated into this documentation. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation. Thank you so much!

**Comment by wbach82** [comment]
Thanks a lot for the insights... my problem is that i cannot see the intune setting mentioned in this article. My windows 1903 devices met all the requirments (Intune managed, ATP Onboarded, E5 license). But regardless of the device the setting in intune should already be there?! Here is nothing listed regarding Tamper protection:

![image](https://user-images.githubusercontent.com/41477614/64254806-6b714800-cf20-11e9-9c28-4a2dbb21e546.png)

**Comment by jvsam** [comment]
Thanks for the update @wbach82, I am seeing the same screen as well, with no *Tamper Protection* option.  My recommendation is still to contact Windows 10 support to get immediate assistance. You can also visit the [Technet forums](https://social.technet.microsoft.com/Forums/home) and the [Tech Community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities) where you can ask questions and interact with other users, experts and also Microsoft engineers.

I am sorry that we cannot assist with the troubleshooting. This Github site is used as a feedback system, and is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. If you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review. Thank you.

**Comment by wbach82** [comment]
ok, i don't feel like hitting an issue but instead it looks like you are describing a feature which is still not yet released in intune? i checked a lot of tenants regarding this setting but never found the setting. all tenants are located in europe. maybe it is not released here yet.

**Comment by jvsam** [comment]
Well, it's still in preview. I am not sure if it's region-specific though, @wbach82. But good point.

Hi @denisebmsft, will you be able to help us with this? If it's a limited preview release, or if there are other requirements that we need to take note of? Appreciate the assistance.

**Comment by jvsam** [comment]
Hello again @denisebmsft, if you are not busy, can you please provide some insights on the status of *Tamper Protection's* availability in the Intune management console? It's indicated on the docs that it's still *in preview*, but is it a limited release and only available to select users? Or perhaps audience from specific locales or regions? Looking forward to hearing from you. Thank you in advance.

@wesback did you get a chance to contact Windows 10 support to verify this? If so, we would appreciate if you can keep us posted here. Thanks.

**Comment by jvsam** [comment]
Thank you for the prompt action @denisebmsft. I can see the updates now. 

@wesback, we appreciate your patience. This documentation has been updated to clarify the current availability of *Tamper Protection*.

> ..."In preview" means this feature is rolling out to business customers who have Microsoft Defender ATP and who have agreed to participate in the preview program.

I believe we can consider this issue *resolved*. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
