### ISSUE TITLE
Get started hyperlink is broken

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/windows-itpro-docs#4832]
Not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bdb99e4-289a-c09a-c35c-2774fc52a402
* Version Independent ID: 4d325389-c9b8-2601-0ff4-c7b6bf5a6c28
* Content: [Microsoft Defender Advanced Threat Protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
assign @jvsam

**Comment by illfated** [comment]
Confirmed. Both the docs.microsoft.com link and the Github source link is broken.
- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/get-started
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/get-started.md

The file `get-started.md` does not exist in the directory https://github.com/MicrosoftDocs/windows-itpro-docs/tree/master/windows/security/threat-protection/microsoft-defender-atp (and hence no such file in the matching docs.microsoft.com directory).

**Comment by illfated** [comment]
Looking at the page **What's new in Microsoft Defender ATP** (https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/whats-new-in-microsoft-defender-atp), it looks like there is no page named "Get started" (only a subsection with other pages underneath) in the menu list on the left side, so maybe the page has moved, or even been removed completely, forgetting to change or remove the above mentioned link to that page.

**Comment by jvsam** [comment]
Thank you for bringing this to our attention @xNiklasJern. 

I believe this page is more likely it, since in the description it says *'Learn about the requirements of the platform and the initial steps you need to take to get started with Microsoft Defender ATP.'* It's also available in the TOC on the left.

https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements

Verifying if the machine or device meets the minimum requirements is the first step when onboarding. 

What do you think @illfated? Would you mind creating the PR? Thank you.

**Comment by illfated** [comment]
Sure thing, I can do that. Looks like the most reasonable thing is to put the same name on the link text as the page itself, so it should look more or less like this:

## In this section
To help you maximize the effectiveness of the security platform, you can configure individual capabilities that surface in Microsoft Defender Security Center. 

Topic | Description
:---|:---
[Overview](overview.md) | Understand the concepts behind the capabilities in Microsoft Defender ATP so you take full advantage of the complete threat protection platform. 
[Minimum requirements](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md) | Learn about the requirements of the platform and the initial steps you need to take to get started with Microsoft Defender ATP.
[Configure and manage capabilities](onboard.md)| Configure and manage the individual capabilities in Microsoft Defender ATP. 
[Troubleshoot Microsoft Defender ATP](troubleshoot-mdatp.md) | Learn how to address issues that you might encounter while using the platform.

A pull request for this change will be available shortly.

**Comment by jvsam** [comment]
@illfated thanks for creating the pull request, appreciate it!

**Comment by jvsam** [comment]
Hello again @xNiklasJern, we'd like to inform you that the changes are now displayed here at docs.microsoft.com. You can verify by visiting this URL: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection. Thank you again for your feedback and for being part of the Microsoft Docs community!

Thanks again too @illfated.
