### ISSUE TITLE
Password only for BitLocker works, too

### ISSUE THREAD

**Issue by Van-Fouran** [MicrosoftDocs/windows-itpro-docs#4836]
Its seems like there are not all available options listet on this side. Please have a look at: https://social.technet.microsoft.com/Forums/en-US/c666e22b-f03e-421a-85e4-60468c7663f0/password-only-for-bitlocker?forum=win10itprosecurity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde8beb2-6800-cf3c-c927-91ed2827eb6c
* Version Independent ID: 7264f37a-e40a-3cd8-d28c-5b2b772eff15
* Content: [BitLocker (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-overview#system-requirements)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by mypil** [comment]
@Van-Fouran - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Added PR #4903 (and important note)

**Comment by mypil** [comment]
@Van-Fouran  - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by Van-Fouran** [comment]
@mypil Thank you for your help. I watched the merging process and the changes look great from my perspective. Looking forward seeing the change in the documentation.
