### ISSUE TITLE
windows 10 Azure joined RDP disapointing. suggest installing VNC instead.

### ISSUE THREAD

**Issue by MightyGargantuan** [MicrosoftDocs/windows-itpro-docs#4837]
its seems microsofts solution to security issues is to break functionallity like RDP.  i have only recently moved to windows 10 from windows 7 (I wont talk about windows 8) .  windows 7 to spite not having bruite force protection on IP address and a multitude of other vunrablities (which could be mitigated with VPN, DUO, RDPGuard and other software). i could still remote in from different devices and RDP applications and domains.  i have been using RDP since 1999 from different devices like Compaq Ipac, Linux to do work.  the whole point of Remote desktop is to allow a user to connect remotely from different envionments. Windows 10 RDP on Azure AD is an epic fail.  i will now install linux based software on microsoft as a workaround.  (if i keep replacing key components of Microsoft OS with linux components, eventually i would have replaced windows completely with linux).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc#feedback)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@MightyGargantuan - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via [Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
