### ISSUE TITLE
MDM Discovery Service url

### ISSUE THREAD

**Issue by bvduijn** [MicrosoftDocs/windows-itpro-docs#4841]
What is the correct url for the MDM discovery Service? This document mentions https://enrollment.manage.microsoft.com/enrollmentserver/discovery however all other documentation and our Intune config says https://enrollment.manage.microsoft.com/enrollmentserver/discovery.svc

**Comment by mypil** [comment]
@bvduijn - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. 

Thank you.

**Comment by bvduijn** [comment]
Other documentation is for instance https://docs.microsoft.com/nl-nl/intune/windows-enroll#enable-windows-10-automatic-enrollment or https://docs.microsoft.com/en-us/windows/client-management/mdm/federated-authentication-device-enrollment 

Document that mentions the url without .svc is https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy#verify-auto-enrollment-requirements-and-settings under bullet 5

Just FYI. After I changed back the url to include .svc enrollment started working.

**Comment by mypil** [comment]
@bvduijn - Thank you for submitting feedback.

You mentioned that after you changed back the url to include .svc enrollment started working. Does this mean that your issue has been resolved? OR is there a portion of the doc that you suggest to be edited? If there is, kindly assist to provide more details.

**Comment by bvduijn** [comment]
@mypil This page mentions the wrong service URL It is bullet 5 under https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy#verify-auto-enrollment-requirements-and-settings 

PS. Or should I have created a pull request to address the issue? Haven't been working with Git that much..

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@bvduijn - Yes, it would be awesome if you could create a Pull Request to add in your suggestion and just link this issue so I can have the doc owner review and merge the content.

Thank you.

**Comment by mypil** [comment]
Reopening issue until PR is merged.

**Comment by mypil** [comment]
@bvduijn - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
