### ISSUE TITLE
Move remaining Q and A to WDAG FAQ page

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#4843]
The question and answer for #4288 should be moved to the FAQ page that is intended to be the single source of FAQs for WDAG FAQ (see #4409).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfb9445a-681d-24b6-5241-4ebe311f5236
* Version Independent ID: aea60f74-212c-e24e-f164-28a555bc1727
* Content: [Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@iadgovuser1 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
These topics are on the section **Frequently Asked Questions** with a link, I'd ask @mypil  to join the author and get its opinion prior to proceeding with this change.

**Comment by mypil** [comment]
@Dansimp - Can you please share your insights on this issue?

Thank you.

**Comment by Dansimp** [comment]
This was fixed and the change is now live: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/wd-app-guard-overview.
