### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by DennisT1** [MicrosoftDocs/windows-itpro-docs#4846]
Thanks for making a usable log system totally unusable.  WTH is the matter with you people?  I've just spent over an hour trying to remotely access the log on a client PC.  Tried running downloaded scripts to run remote PS commands, and still nothing.  I could load a Linux OS faster than this.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47692487-0a0b-3b1b-6d34-790046c7cbc3
* Version Independent ID: 0f66cafe-2bff-4323-b3fc-01014b904b3a
* Content: [Windows Update log files](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-logs#feedback)
* Content Source: [windows/deployment/update/windows-update-logs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-logs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@DennisT1 - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by illfated** [comment]
@DennisT1 : We would very much like to get constructive criticism, containing suggestions of what the documentation should look like and what it needs to contain.
If you would be so kind as to get back to us with comments on what is wrong in the documentation and what it needs to contain instead, we are happy to open a Pull Request to have the page changed.

Looking forward to hearing back from you. Hope you will find your required information.
