### ISSUE TITLE
Policy Definitions folder name

### ISSUE THREAD

**Issue by woodyard** [MicrosoftDocs/windows-itpro-docs#4850]
The name of the folder when you download the admx files as msi-file is "Policy Definitions" you can't just copy this folder to the Policies folder. The name has to be "PolicyDefinitions" without space in order for the GPO Editor to detect the admx files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Thank you for the insight. Maybe it will be helpful to add an extra line in the **[!IMPORTANT]** note section to tell the users to rename the folder accordingly.

```diff
  > [!IMPORTANT]
  > If you do not see the policy, it may be because you don’t have the ADMX installed for Windows 10, version 1803 or version 1809. To fix the issue, follow these steps:        
  >   1. Download:  
  >   1803 -->[Administrative Templates (.admx) for Windows 10 April 2018 Update (1803)](https://www.microsoft.com/download/details.aspx?id=56880) or  
  >   1809 --> [Administrative Templates for Windows 10 October 2018 Update (1809)](https://www.microsoft.com/download/details.aspx?id=57576).
  >   2. Install the package on the Primary Domain Controller (PDC).
  >   3. Navigate, depending on the version to the folder:
  >   1803 --> **C:\Program Files (x86)\Microsoft Group Policy\Windows 10 April 2018 Update (1803) v2**, or  
  >   1809 --> **C:\Program Files (x86)\Microsoft Group Policy\Windows 10 October 2018 Update (1809) v2**
- >   4. Copy policy definitions folder to **C:\Windows\SYSVOL\domain\Policies**.
+ >   4. Rename the extracted Policy Definitions folder to **PolicyDefinitions**.
+ >   5. Copy PolicyDefinitions folder to **C:\Windows\SYSVOL\domain\Policies**.
- >   5. Restart the Primary Domain Controller for the policy to be available.
+ >   6. Restart the Primary Domain Controller for the policy to be available.
  >   This procedure will work for any future version as well.
```
The end result could look like this:

> [!IMPORTANT]
> If you do not see the policy, it may be because you don’t have the ADMX installed for Windows 10, version 1803 or version 1809. To fix the issue, follow these steps:        
>   1. Download:  
>   1803 -->[Administrative Templates (.admx) for Windows 10 April 2018 Update (1803)](https://www.microsoft.com/download/details.aspx?id=56880) or  
>   1809 --> [Administrative Templates for Windows 10 October 2018 Update (1809)](https://www.microsoft.com/download/details.aspx?id=57576).
>   2. Install the package on the Primary Domain Controller (PDC).
>   3. Navigate, depending on the version to the folder:
>   1803 --> **C:\Program Files (x86)\Microsoft Group Policy\Windows 10 April 2018 Update (1803) v2**, or  
>   1809 --> **C:\Program Files (x86)\Microsoft Group Policy\Windows 10 October 2018 Update (1809) v2**
>   4. Rename the extracted Policy Definitions folder to **PolicyDefinitions**.
>   5. Copy PolicyDefinitions folder to **C:\Windows\SYSVOL\domain\Policies**.
>   6. Restart the Primary Domain Controller for the policy to be available.
>
>   This procedure will work for any future version as well.

Feel free to comment and suggest changes to this section before a Pull Request is made to the master branch.

**Comment by woodyard** [comment]
Hi there,

Maybe you should consider including a link to download Administrative Templates for Windows 10 1903 as well..

br,
Henrik Skovgaard
________________________________

**Comment by illfated** [comment]
Sounds like a good idea, although I will wait for more feedback from the MS Docs team regarding that part (also regarding which download source to use and where the link should be located in the page.

**Comment by e0i** [comment]
@woodyard  Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.
