### ISSUE TITLE
Inconsistent availability 

### ISSUE THREAD

**Issue by gkens** [MicrosoftDocs/windows-itpro-docs#4852]
Tamper protection is currently available on windows 10 pro build 1903 even if it is not joined to azure active directory and/or managed by inTune.  However a machine added to azure active directory as part of microsoft 365 business and managed by Intune does not have this feature. I hope Microsoft will address this in the very Future

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a2f0402-82fb-83ff-122a-2f19c5288eeb
* Version Independent ID: 52f80b09-0e90-464d-0c4d-00479361fa9b
* Content: [Protect security settings with Tamper Protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by e0i** [comment]
@gkens 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by denisebmsft** [comment]
Hello @gkens, and thank you for the feedback. You've raised a great point that I will pass along to the product team. In the meantime, I have added a note to the article clarifying that the ability to manage Tamper Protection in Intune is in preview at this time. The article is slated to be republished later this afternoon, and you can see the changes there. In the meantime, if you still have questions, please let us know. And thanks again for your feedback - it helps us improve the quality of our documentations. All the best, denise.

**Comment by gkens** [comment]
Is it possible to get a preview version access for Intune as part of 365 business?

Thanks

Glenn

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
