### ISSUE TITLE
No information about  "how to actually configure this setting"

### ISSUE THREAD

**Issue by olofhellman** [MicrosoftDocs/windows-itpro-docs#4860]
So this page has a lot of information about this particular setting, but there's no information about how to actually configure it.  Is there a checkbox in a control panel somewhere? If so, which one?  Is this a windows registry thing?  If so, how do I edit the registry?  tl;dr:  the information in this page is not actionable without a pointer to some way to actually configure the setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad4dcf82-8d1c-79cd-3eb2-0b549394a30d
* Version Independent ID: f36b4278-9614-0056-64fc-732f0cdb0e74
* Content: [Enable computer and user accounts to be trusted for delegation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/enable-computer-and-user-accounts-to-be-trusted-for-delegation#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/enable-computer-and-user-accounts-to-be-trusted-for-delegation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/enable-computer-and-user-accounts-to-be-trusted-for-delegation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
To be honest, I haven't done this kind of work myself, I have only browsed the security list of users while doing simpler changes elsewhere.
@olofhellman : Have you looked at the Security list for computers while being logged in as Administrator?

Meh. I have forgotten to start up TeamViewer on my work computer before I left my workplace, so I don't have access to the domain controller at the moment.
I will make sure to enable it tomorrow, so I can check this when I get back home (also tomorrow).

**Comment by olofhellman** [comment]
@illfated I do not know what is meant by "the Security list for computers".

**Comment by Dansimp** [comment]
@olofhellman, would it help to link to this page? https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/how-to-configure-security-policy-settings. This shows you how to edit the security policies.

**Comment by illfated** [comment]
Thank you very much for the follow-up. My time has been too limited lately to check up on this topic, so your suggestion helps a lot by pointing to how to use `secpol.msc` similar to how we run `gpedit.msc` to get the Group Policy Editor.

**Comment by Dansimp** [comment]
Will do

**Comment by e0i** [comment]
@olofhellman 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
