### ISSUE TITLE
MAM and MDM

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#4861]
Hello,
Can we use same certificate for MAM and for MDM?
What is best recommended?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16e6e551-830e-f69e-31bc-e109e5b594f4
* Version Independent ID: 3396045c-8295-b801-aba5-11a11dd62dc0
* Content: [Create and verify an Encrypting File System (EFS) Data Recovery Agent (DRA) certificate (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-and-verify-an-efs-dra-certificate)
* Content Source: [windows/security/information-protection/windows-information-protection/create-and-verify-an-efs-dra-certificate.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/create-and-verify-an-efs-dra-certificate.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by MaratMussabekov** [comment]
hello @lightupdifire ,
**Can we use same certificate for MAM and for MDM?** - yes sure, it is OK to use the same certificate
**What is best recommended?** - There is no recommendation about usage the same or different certificate, so it is up to you. You only must to store the PFX file carefully, as it can be used to decrypt any data.
Thank you

**Comment by lightupdifire** [comment]
@MaratMussabekov Thanks for info! Maybe good to add some FAQ about it for future?

**Comment by e0i** [comment]
@lightupdifire 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
