### ISSUE TITLE
Licensing Requirements

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/windows-itpro-docs#4862]
Isn't this also licensed through the M365 E5 Security add-on?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Not sure what you mean by "add-on". But as long as you have Microsoft 365 E5 - you have access to Microsoft Defender ATP.

**Comment by MaratMussabekov** [comment]
Hello, @OffColour,
you are correct, Microsoft Defender ATP is also licensed by 'Identity and Threat Protection" package, I will create a PR to add this information to the article

**Comment by illfated** [comment]
@e0i : You may want to reopen this issue ticket and close it again when PR #5001 is closed.

**Comment by e0i** [comment]
@OffColour 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
