### ISSUE TITLE
MAM policy | Revoke access to protected data when the device enrolls to MDM

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#4864]
Hello,
When creating MAM policy, there is this option, can you please explain this:
"revoke access to protected data when the device enrolls to MDM"
![image](https://user-images.githubusercontent.com/39700914/64331638-72a55e00-cfd3-11e9-975b-9994e6757527.png)

And then for this MAM policy, with the option above to ON, which DRA certificate need to use, the one created for MDM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ad3f92-24de-5eb5-8454-c72d85737183
* Version Independent ID: 900125eb-31ea-faf3-ac30-7c3d7b30f611
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by j0rt3g4** [comment]
Hello @lightupdifire 

I think that this link would help you to understand how the MDM and how intune works together to protect the data:
https://www.microsoft.com/security/blog/2018/08/02/protect-your-data-in-files-apps-and-devices/

 * **"revoke access to protected data when the device enrolls to MDM"**
This means that if you add a new device using MDM the access to all the data protected in your policy will be lost for such a device.
* **And then for this MAM policy, with the option above to ON, which DRA certificate need to use, the one created for MDM?**
Yes the one created on MDM

**Comment by e0i** [comment]
Hello @lightupdifire 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Comment by lightupdifire** [comment]
@j0rt3g4 ,
Regards "revoke access to protected data when the device enrolls to MDM",
Can you please explain why this should be used?
If my PC under MAM -> data protected, device not managed.
If my PC goes from MAM to MDM -> device managed, but then cannot access data anymore? why that?

**Comment by illfated** [comment]
Well, that is something you chose to do, wasn't it? Didn't you choose to "Revoke access to protected data when the device enrolls to MDM" ?

Maybe you need to find a different protection under MDM and turn off protection under MAM ?

**Comment by j0rt3g4** [comment]
Hello @lightupdifire is not a "should be" used.
That really depends on the way you want to secure the "Protected data",  you decide if you want these devices to be able to access or not such data. So that's uppon you.

**If my PC goes from MAM to MDM -> device managed, but then cannot access data anymore? why that?**

The device managed, yeah, but you can't access "PROTECTED DATA" anymore, it's your choice to select it or not, is not a MUST. Please read carefully, it's Protected data, not ALL DATA, and the protected data you defined it.

**Comment by lightupdifire** [comment]
Hello @j0rt3g4 , thanks for the info, I needed this "is not a MUST", just confusing option :)

**Comment by j0rt3g4** [comment]
@lightupdifire Np! I'm glad to help you!
