### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by jessiegouw** [MicrosoftDocs/windows-itpro-docs#4866]
Underneath the subtitle **Install** stands _initates_, but it should be _initiates_.

**Comment by illfated** [comment]
Hmm, looks like you landed here from clicking the link to the MS Docs issue tracker instead of reporting the issue on the page you were looking at.
Could I have the link to the page you refer to?

**Comment by jessiegouw** [comment]
[How does Windows Update work?](https://docs.microsoft.com/en-us/windows/deployment/update/how-windows-update-works#feedback)

**Comment by illfated** [comment]
OK, thanks. I see.
- https://docs.microsoft.com/en-us/windows/deployment/update/how-windows-update-works
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/how-windows-update-works.md

Presently opening a Pull Request to have it amended.
