### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by Henrikcj** [MicrosoftDocs/windows-itpro-docs#4868]
Acording to this Windows 7 is not suportet for device tag. But when i have used this metohed on windows 7, and it works. It looks like an error in this doc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b42e708-e334-d434-bcc9-e1860ebb36b3
* Version Independent ID: 92e251c5-8613-ce97-9569-02404c9a466a
* Content: [Create and manage machine tags](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/machine-tags#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/machine-tags.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/machine-tags.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Some Microsoft software may work on older versions of Windows, like Windows 7.
But it does not mean that the solution is supported.
When Microsoft says that some versions or software combinations are not supported,
it simply means that you may not get documentation or any help with those versions.

"Not supported" also means that the available documentation will not be updated for those versions.

**Comment by jvsam** [comment]
assign @jvsam

**Comment by jvsam** [comment]
Hi @Henrikcj did the information provided by @illfated answer your question?

Also, this documentation is part of the Microsoft Defender ATP doc set. Is your Windows 7 machine [fully onboarded](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/onboard-downlevel) to MDATP and does it show in the machines list? Even if you can use the registry key to add tags, there's a possibility that it may not appear in the machine information report or certain [response actions](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/respond-machine-alerts) will not work. The best way to verify this is to contact [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10).  And if you do, kindly keep us informed on the resolution or any relevant information that can be incorporated into this documentation. Thank you.

**NOTE:**  You can also check out the The [Microsoft Defender ATP Community Center](https://techcommunity.microsoft.com/t5/Microsoft-Defender-Advanced/ct-p/MicrosoftDefenderAdvanced). It's a place where community members can learn, collaborate, and share experiences about the product. Feel free to start a conversation.
