### ISSUE TITLE
Source-initiated subscription with computer OU?

### ISSUE THREAD

**Issue by nick405060** [MicrosoftDocs/windows-itpro-docs#4871]
Hi, is there a way to create a source-initiated subscription except use a computer OU instead of a security group? We could copy our dynamic computer OU to a security group, but then the security group would be static (we’d have to write a PS script or something to continue to dynamically copy over which is not desirable)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5862cc7-3f36-5f2e-9ade-f7441f99f818
* Version Independent ID: b8bd1985-7b5b-ea79-976a-7d96ad69335c
* Content: [Use Windows Event Forwarding to help with intrusion detection (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection#feedback)
* Content Source: [windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @nick405060 thank you for opening this issue, however, please be informed that this Github site is used as a feedback system to help improve the quality of the technical documentation of Microsoft Docs. So if you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review. 

Now, with regard to your question, we believe it will be best addressed by contacting [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10). You can also check the [Microsoft Defender ATP Community Center](https://techcommunity.microsoft.com/t5/Microsoft-Defender-Advanced/ct-p/MicrosoftDefenderAdvanced). It's a place where community members can learn, collaborate, and share experiences about the product. It's the best place to ask your question and engage with the community. Also, kindly keep us informed on the resolution or any relevant information you will learn that can be incorporated into this documentation.

Thank you for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hello again @nick405060, we didn’t hear back from you regarding this issue but we're hoping you were able to contact support to resolve your concern. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
