### ISSUE TITLE
Federation term used incorrectly

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/windows-itpro-docs#4873]
The concept of "federated" that is thrown around on this page and other pages assumes that the customer is only using AD FS.  There are other federation services, like Okta, that federate Azure AD to a federation service using WS-Fed.  I think a lot of the documentation on this product needs to be re-written.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5739fab2-c6db-a7a9-b0e7-2bf4b85912a7
* Version Independent ID: 82c58053-c1d7-d938-1b0f-f3f7f70ada3b
* Content: [Planning a Windows Hello for Business Deployment](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-planning-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-planning-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @poortom1004 thank you for your feedback. The primary focus of the documentation at docs.microsoft.com is Microsoft⁠—its products and services. If there is any mention of a third-party service or application, that definitely means that it went through a rigorous process of validation, testing, and I would assume, even legal. But we do appreciate your suggestion and it is noted.  Now going back to this doc, there is a reference to another doc regarding *[third-party additional authentication methods](https://docs.microsoft.com/windows-server/identity/ad-fs/operations/configure-additional-authentication-methods-for-ad-fs#microsoft-and-third-party-additional-authentication-methods)*, although limited to Windows Server 2012 R2.

Thank you again.

**Comment by poortom1004** [comment]
All that I was saying is that there are many sentences where the term federation is being used and the writer assumed that the consumer is using AD FS, and I was just pointing out that it's possible to federate with other services, which makes the statements about federation in the document incorrect.  What I am suggesting is updating the terminology in the docs to be reworded like  "federation with AD FS" instead of just "federated".

**Comment by jvsam** [comment]
@poortom1004 thanks for the clarification. If you have time, would you mind listing those sentences (*or samples*) so we can ask the Doc author to review and verify? Thanks.

Hi @mapalko your feedback on this is definitely welcome. Thank you.

**Comment by jvsam** [comment]
Hi @mapalko hoping you can provide some insights. I understand that the content of this document went through a rigorous process to ensure the content, specifically the technical part, is accurate. Looking forward to your feedback, thank you.

**Comment by jvsam** [comment]
Hi again @mapalko kindly confirm is the suggestion is acceptable and won't change the purpose of this documentation. Hoping to hear from you.

**Comment by mapalko** [comment]
I do not think the references on this specific page are incorrect. For a pure on-prem deployment the only federation server that is supported is AD FS because it supports key registration role for WHFB. I cannot make statements of support for third party Federation servers with regards to that functionality.

In general, I think that modifying the statements with federation to "federation with AD FS" would be clearer but we would need to go through the documents to verify each usage to verify whether it is necessary in the context of that page.

**Comment by jvsam** [comment]
> In general, I think that modifying the statements with federation to "federation with AD FS" would be clearer but we would need to go through the documents to verify each usage to verify whether it is necessary in the context of that page.

My thoughts exactly. Thank you @mapalko. 

@poortom1004, as pointed out by the author, although you are right that 'federation with AD FS' will provide more clarity, it's not going to be a simple change. On a high-level, the term used is still correct considering the purpose of this documentation. Even though there won't be any immediate changes on this doc, other users who may have the same concern can still see this in the *feedback* section. Anyway, this is a very interesting discussion and thank you so much for taking the time to share your ideas and suggestions. Please continue to send your feedback to improve the quality of the Microsoft documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hello @poortom1004 we will now close this issue. Again, please continue to send your feedback to help improve the quality of the technical documentation of Microsoft Docs. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
