### ISSUE TITLE
Planning worksheet

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/windows-itpro-docs#4874]
Can the planning worksheet be provided in some format other than pdf?  Excel or Word would be far better alone, or perhaps some sort of simple web form.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5739fab2-c6db-a7a9-b0e7-2bf4b85912a7
* Version Independent ID: 82c58053-c1d7-d938-1b0f-f3f7f70ada3b
* Content: [Planning a Windows Hello for Business Deployment](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-planning-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-planning-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
As mentioned in the closed issue ticket https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2726, comment https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2726#issuecomment-466835220, modern versions of Word are able to open PDF files for editing.

**Comment by jvsam** [comment]
Thank you for sharing that information @illfated. 

@poortom1004 thank you for your feedback. At the moment, that is the only format available for the planning worksheet. Your understanding is appreciated.

**Comment by poortom1004** [comment]
How can I request that a word version be provided?  Since there's been others asking for the same thing, there's clearly a desire from others for one to be provided.  The format that is currently provided just doesn't make much sense.

**Comment by jvsam** [comment]
> How can I request that a word version be provided? 

@mapalko is the request possible? 

@poortom1004 I converted the [Planning Worksheet](https://go.microsoft.com/fwlink/?linkid=852514) that is on this documentation (*pdf was last updated on 2017-07-05*). Though these links are not on the doc, some users *may* stumble upon this specific issue that you have opened (Open and closed issues are available on the *Feedback* section of this documentation). 

https://1drv.ms/w/s!AgqYDMeP_2-2ggzRcQpAUlyCapoU (doc)
https://1drv.ms/w/s!AgqYDMeP_2-2ggvMgGjgc2TnCdDv (docx)
https://1drv.ms/x/s!AgqYDMeP_2-2ghFSsNVcWv4Ku4wq (spreadsheet)

**Disclaimer:** The converted documents are not owned by Microsoft, please use at your own risk. The links may change without notice. Always refer to the *official* **Planning Worksheet** on the doc.

**Comment by jvsam** [comment]
Hello again @poortom1004, it would appear that the *pdf* file is really the only available format at this time. I am sure the document author has taken note of your suggestion and when a new format becomes available from the Microsoft Download Center, it'll be added to the docs. We will now close this issue. Feel free to re-open or create another issue through the doc's *feedback feature*, if you have other suggestions or ideas to improve the quality of this documentation.

Thank you again for your feedback.

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by make4fun** [comment]
This link used to point to an excel sheet may be a year or two ago. Not everyone may be using the latest version of word or have a different tool to edit PDFs. Also, the original excel file used to prepopulate certain cells in the sheet based on selections that were made in other cells. I should have the old version of the sheet somewhere and can find and upload it, if someone needs it.

**Comment by make4fun** [comment]
I checked and found the excel sheet. Apparently, I was mistaken about the prepopulating of stuff. It is a manual entry for everything by referencing the information in this article, so basically any editable format will work I guess. This can be a suggestion though that if an excel sheet can be provided which does prepopulate items based on other selections, it'll make the job of filling this up and coming up with the required config, so much easier. More than that, it can eliminate the possibility of errors while doing this manually! :)
