### ISSUE TITLE
Unsupported Windows 10 versions

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/windows-itpro-docs#4875]
All versions of Windows 10 being referenced in this document (1511 and 1703) are not supported anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5739fab2-c6db-a7a9-b0e7-2bf4b85912a7
* Version Independent ID: 82c58053-c1d7-d938-1b0f-f3f7f70ada3b
* Content: [Planning a Windows Hello for Business Deployment](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-planning-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-planning-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
HI @poortom1004 just to clarify, are you saying that Windows 10 1511 and 1703 do not support Windows Hello for Business? Windows 10 1511 supports [Microsoft Passport](https://docs.microsoft.com/windows/whats-new/whats-new-windows-10-version-1507-and-1511#microsoft-passport), which was the former name of Windows Hello for Business. Please provide more information about this issue. Thank you.

**Comment by mapalko** [comment]
@jvsam, I think he is referring to the WIndows lifecycle support statement: https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet a

**Comment by jvsam** [comment]
I see, thanks @mapalko. 

@poortom1004 can you please check @mapalko's comment? What exactly is your request here? Or do you have any specific suggestions? Looking forward to hearing from you.

P.S: You have opened several issues related to this doc. For documentation, I'm listing them all here. 

1. 4875 (this issue) - Unsupported Windows 10 version.
2. #4874 - Request for different planning worksheet formats.
3.  #4873 - Clarity on the usage of the *federation* term.
4. #4872 - Legacy pricing plans/options terminology. 

FYI @mapalko

**Comment by jvsam** [comment]
Hello again @poortom1004, just following up regarding your request. Can you please clarify your suggestion? It would help a lot if we understand what change are you proposing, so we can determine if it's something that can be incorporated into the docs. Thanks again.

**Comment by jvsam** [comment]
Hello again @poortom1004, we didn’t hear back from you and we need more information regarding your main issue (*Unsupported Windows 10 versions*). Thanks for understanding and we look forward to hearing from you.

**Comment by illfated** [comment]
Even though I don't know for certain, I can offer an educated guess that @poortom1004 (Thomas) is suggesting to have the unsupported version numbers replaced with the current supported Windows 10 version numbers, just to have the documentation up to date and relevant.

I don't know the exact numbers, but it should be easy to create a PR to make the changes, provided a confirmation of which version numbers should be replaced (due to out of date) and which version numbers to put there instead.

**Comment by poortom1004** [comment]
It could be something really simple like removing the language about specific versions of Windows 10, and just change it to "all supported versions of Windows 10", since those older versions are unsupported now.

**Comment by illfated** [comment]
Fair enough, that looks like a practical solution to me. Then again, I presume it will be best to check with the document author (@mapalko) or the manager (Daniel Simpson) if this will be a valid solution.

@jvsam : As the assigned team member, your thoughts are welcome too. 😉

**Comment by mapalko** [comment]
I would recommend removing the statement at the top on version. I think it is unnecessary.

The versioning in the document is to specify when support for specific functionality was added. It is not a statement of Windows support. I do not think those need to be removed since they are not excluding newer versions.

**Comment by illfated** [comment]
Very well, thank you for the precise feedback. I presume you recommend removing this sentence,

> This guide only applies to Windows 10, version 1511 or higher.

and to keep the rest of the document as it is.

**Comment by poortom1004** [comment]
So 5 years down the line, you will continue to reference Windows 10 build 1511 in your doc?

**Comment by jvsam** [comment]
Thank you @mapalko.

@illfated yes, please go ahead and submit a PR :-) Thank you!

> So 5 years down the line, you will continue to reference Windows 10 build 1511 in your doc?

The docs are a continuous work in progress. There *may* still be users who are using that specific build and retaining it for now, provides clarity. My two cents :-)
