### ISSUE TITLE
Incorrect statement about federation

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/windows-itpro-docs#4876]
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs#federation

"Windows Hello for Business hybrid certificate trust requires Active Directory being federated with Azure Active Directory and needs Windows Server 2016 Active Directory Federation Services or newer"

This statement is not true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02eda72c-ccd2-e8d8-4f7e-6edf95b79408
* Version Independent ID: be08aee5-2403-c131-0f39-005e1271d5f1
* Content: [Hybrid Windows Hello for Business Prerequisites (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs#federation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by poortom1004** [comment]
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification#hybrid-deployments

AD FS isn't listed on the certificate trust hybrid model.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
> Windows Hello for Business hybrid certificate trust requires Active Directory being federated with Azure Active Directory and needs Windows Server 2016 Active Directory Federation Services or newer. 
> This statement is not true.

Hi @poortom1004, can you please provide more information on why you've mentioned that the statement above is incorrect? If this is related to your feedback on #4873—and you believe it would work with other Federation Services—please note that this documentation contains details that are approved by the product team (*and by other groups or teams under Microsoft who are responsible in ensuring the content is accurate*). If this is not what you're talking about, please clarify so we'll understand it better. Thank you.

**Comment by poortom1004** [comment]
Did you take a look at the link I provided?
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification#hybrid-deployments

Under Certificate trust Mixed managed and the Certificate trust Modern managed models, they state:

Azure MFA tenant, or
AD FS w/Azure MFA adapter, or
AD FS w/Azure MFA Server adapter, or
AD FS w/3rd Party MFA Adapter 

So reading this to me says that if you have Azure MFA tenant, you don't need AD FS.  If this is incorrect, then it would seem that document needs to be updated to reflect correct information.

**Comment by jvsam** [comment]
I see, I missed that link @poortom1004. Thanks for clarifying the issue for us. 

@mapalko can you please confirm? As always, appreciate the help. Thanks.

**Comment by mapalko** [comment]
The statement in this document is for Hybrid Azure Ad Joined devices. The certificate trust mixed managed deployment model requires AD FS for this join type.

The certificate trust modern managed deployment model is only supported today for SSO to on-prem resources with Azure AD Joined devices. 

The chart on https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification#hybrid-deployments should be updated in the managed section to specify that it is for AADJ devices.

**Comment by jvsam** [comment]
Thank you so much for the update @mjcaparas. We will create a pull request and submit it to you for review.

**Comment by joinimran** [comment]
@jvsam as per recommendation, PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5336 has been created.

**Comment by jvsam** [comment]
Hi again @poortom1004, please be informed that the pull request (See PR #5336) that contains suggestions based from your feedback has been approved and merged. This documentation will be updated in the next scheduled publishing run. 

We will now close this issue, but please continue to send your feedback and suggestions to help improve the quality of the technical documentation of Microsoft Docs. Thank you for being part of the community!

**Comment by jvsam** [comment]
@officedocsbot close
