### ISSUE TITLE
Device registration

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/windows-itpro-docs#4877]
Don't devices need to be joined to AAD, and not registered?
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg#configure-azure-for-device-registration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93cb286c-03a9-187a-77a3-771c1c672342
* Version Independent ID: 875bbfa3-7ee3-960e-9b1c-ff5216a62d8b
* Content: [Configure Device Registration for Hybrid Windows Hello for Business](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg#configure-azure-for-device-registration)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @poortom1004,  the [prerequisites](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs#device-registration) section contains all the information you need with regard to hybrid certificate trust deployments. If there are inaccuracies or misleading information on the documentation, please let us know. If the information you seek is not available, it may be best to contact the experts. You can do this by opening a [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) ticket in your tenant. Thank you.

**Comment by jvsam** [comment]
Hi @poortom1004, we didn’t hear back from you but we hope the information we have provided helped clarify this issue for you. We will now close this, but if there is any part of this documentation that is inaccurate or misleading, feel free to re-open this issue. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
