### ISSUE TITLE
Device Writeback

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/windows-itpro-docs#4878]
All of the content about needing to do device writeback is only applicable if implementing AD FS.  AD FS is not required in hybrid scenarios.  It's only required for On-Prem-only scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93cb286c-03a9-187a-77a3-771c1c672342
* Version Independent ID: 875bbfa3-7ee3-960e-9b1c-ff5216a62d8b
* Content: [Configure Device Registration for Hybrid Windows Hello for Business](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg#configure-azure-for-device-registration)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
> AD FS is not required in hybrid scenarios. It's only required for On-Prem-only scenarios.

Hi @poortom1004, can you please specify, exactly which part of the documentation is misleading? This doc is under *Hybrid Azure AD joined Certificate Trust Deployment* and serves as a guide for professionals who want to familiarize themselves with Windows Hello for Business by deploying a lab environment. It showcases two scenarios that provide a baseline from which you can begin your deployment ([New deployment baseline](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust#new-deployment-baseline) & [federated baseline](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust#federated-baseline)). I am sure the contents of this guide are vetted and tested, but if there is incorrect information or if you find issues after following the guide, please let us know, or you can contact [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) support for technical assistance. Thank you.

**Comment by jvsam** [comment]
Hello again @poortom1004, we didn’t hear back from you but we hope the information we have provided helped clarify this issue for you. We will now close this, but if there is any part of this documentation that is inaccurate or misleading, feel free to re-open this issue. 

If you have other suggestions or ideas to improve the quality of this documentation, please create another issue through the doc's *feedback feature*. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
