### ISSUE TITLE
Provisioning Package giving error

### ISSUE THREAD

**Issue by seamajr** [MicrosoftDocs/windows-itpro-docs#4880]
I have followed the entire page and references to configure my MultiApp Kiosk.  First off, looks like the instructions for Adding XML file to Configuration Package is out dated or just wrong.  However, I cannot tell if that is making the difference.

The instruction says open ICD and select Advanced Provisioning, All Windows Desktop editions..... Finish.  When opening the Project expand Runtime Settings > AssignedAccess...  Using the Advanced Provisioning template, there is no AssignedAccess available or MultiApp in a search.  I uninstalled the ADK and re-installed the 1809 ADK in case it was version specific.  Same thing.  I eventually found the AssignedAccess when using the Provision Kiosk devices template.  I don't know if that is adding more to the underlying configuration than I need.

So, past that.  The provisioning package gets created and when trying to apply it to two different test 1809 Ent systems with the Elevated Powershell command Add-ProvisioningPackage, it gives an error:

2_AssignedAccess_multiAppAssignedAccessSettings.provxml
    Category:UxLockdown
    **LastResult:Error -1072896680 (0xC00CE558)**
    Message:Provisioning failed
    NumberOfFailures:1 (0x1)

All of the other configurations worked:

AllowTrustedApps
TabletMode
HideOOB
HideAutoLogon
NoLockScreen

Thinking I had some out of bounds XML configuration due to all the version differences, I made an XML file with just a single app and profile.

<?xml version="1.0" encoding="utf-8" ?>
<AssignedAccessConfiguration
    xmlns="http://schemas.microsoft.com/AssignedAccess/2017/config"
    xmlns:r1809="http://schemas.microsoft.com/AssignedAccess/201810/config"
>
    <Profiles>
        <Profile Id="{79ef68b5-400b-41e5-bc17-578f18996090}">
            <AllAppsList>
                <AllowedApps>
                    <App DesktopAppPath="%SystemRoot%\system32\notepad.exe" r1809:AutoLaunch="true" />
					<App DesktopAppPath="%SystemRoot%\explorer.exe" />
                </AllowedApps>
            </AllAppsList>
            <StartLayout/>
            <Taskbar ShowTaskbar="false"/>
        </Profile>
    </Profiles>
    <Configs>
        <Config>
            <Account>Charlie</Account>
            <DefaultProfile Id="{79ef68b5-400b-41e5-bc17-578f18996090}"/>
        </Config>
    </Configs>
</AssignedAccessConfiguration>

The local account has been logged onto the systems several times prior to this.  Ultimately, I will be using domain accounts and groups.  Not Azure accounts or local accounts.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @seamajr, I am sorry that you're experiencing problems when applying provisioning package to your device. In this case, I recommend that you open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance and to verify the correct steps. You can also check related posts/conversations at [Technet forums](https://social.technet.microsoft.com/Forums/home) and [Microsoft Tech community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities) where you can ask questions about the product and collaborate with community members, experts and also Microsoft engineers.

Please keep us informed on the resolution or any relevant information that can be incorporated into this documentation. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation. Thank you.

**Comment by jvsam** [comment]
Hello again @seamajr, we didn't hear back from you. We hope you were able to contact support and resolve your concern. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation. We always strive to give users the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, accurate and up-to-date. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by seamajr** [comment]
Hello Jo,

 

I would like to re-open this case.  How do I do that?

 

I have been working though our Microsoft support system and am getting NOTHING.  The only thing they have confirmed is, the XML/XSL examples from the docs site DO NOT validate and DO NOT work.

 

How do I interface with real time users successfully utilizing the multi-app kiosk configuration solution?  I thought I was contributing to a conversation, but this incident is hidden from group contribution.

 

How do I get help here?

 

Thanks,

 

Jim

 

From: Jim Seaman [mailto:jseaman@jimswyfe.com] 
Sent: Wednesday, October 23, 2019 9:39 PM
To: 'MicrosoftDocs/windows-itpro-docs' <reply@reply.github.com>; 'MicrosoftDocs/windows-itpro-docs' <windows-itpro-docs@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/windows-itpro-docs] Provisioning Package giving error (#4880)

 

Hello Jo,

 

Sorry, I did not notice that you were looking for a response.  Here is the cool thing.  I opened a case with our TAM and have not received a fix yet.  They are VERY poor in responding and have yet to offer any assistance.  I have sent them everything I can regarding my problems, even all my event logs.  I asked them to build a test system in their lab and they still have not responded to that.

 

Is there anything you can do from your end?

 

I have followed the instructions exactly on the Docs sites.  I have even cut and pasted the XML/XSD files exactly from the docs site and they do not validate.  The reference XSD file errors on a missing element declaration.  I cannot see how anyone is building Multi-app Kiosks if following the instructions on the web site.

 

Thanks,

 

Jim
