### ISSUE TITLE
"Best Practices" are inconsistent

### ISSUE THREAD

**Issue by arourke** [MicrosoftDocs/windows-itpro-docs#4883]
In the "Best Practices" section, guidance to both disable and enable "Microsoft network server: Digitally sign communications (always)." is present. The two options are mutually exclusive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc307f2f-f441-5e2b-16cc-9b3aaf90857c
* Version Independent ID: ce8122f6-892d-5c3e-84e2-e00327ae8ad7
* Content: [SMBv1 Microsoft network server Digitally sign communications (if client agrees) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/smbv1-microsoft-network-server-digitally-sign-communications-if-client-agrees#best-practices)
* Content Source: [windows/security/threat-protection/security-policy-settings/smbv1-microsoft-network-server-digitally-sign-communications-if-client-agrees.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/smbv1-microsoft-network-server-digitally-sign-communications-if-client-agrees.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @arourke thank you for your feedback. Could you please provide the correct or recommended settings so we can submit a request for it to be reviewed? Right now, this is the list and I noticed that the  2nd and 3rd are the same. 

1. Disable Microsoft network client: Digitally sign communications (always).
2. Disable Microsoft network server: Digitally sign communications (always).
3. Enable Microsoft network server: Digitally sign communications (always).
4. Enable Microsoft Network Server: Digitally Sign Communications (If Client Agrees).

I am not very familiar with this topic, but should the 3rd one be replaced with this?

Enabled Microsoft network client: Digitally sign communications (if server agrees)

Looking forward to your suggestion to help improve the quality of this technical documentation.

**Comment by jvsam** [comment]
Hello again @arourke, hope all is well. I want to follow-up regarding your feedback. Can you please clarify so we would know what amendments to suggest to the doc authors? Thank you.

**Comment by arourke** [comment]
I believe the suggestion you’ve provided is correct, given the context. However, I referred to this article for best practice guidance specifically because I didn’t know the best setting to choose, and was looking for Microsoft’s guidance on this. Accordingly, I’m probably not well qualified to say what the correct option with any certainty.

**Comment by jvsam** [comment]
Thank you @arourke, I did some research and found bits and pieces of information from the Technet forums and non-Microsoft sites, but still, I cannot confirm.

@Dansimp, if time permits, can you please provide some insights on this or confirm the proposed corrections so we can create a PR? Thank you so much.

> this is the list and I noticed that the 2nd and 3rd are the same.

> Disable Microsoft network client: Digitally sign communications (always).
> Disable Microsoft network server: Digitally sign communications (always).
> Enable Microsoft network server: Digitally sign communications (always).
> Enable Microsoft Network Server: Digitally Sign Communications (If Client Agrees).

> I am not very familiar with this topic, but should the 3rd one be replaced with this?

> Enabled Microsoft network client: Digitally sign communications (if server agrees)

**Comment by jvsam** [comment]
Hello again @arourke, thank you for your patience. Please be informed that the suggested updates to this documentation based on your feedback (*see pull request #5069*) have already been merged. Please expect the changes to be displayed here at docs.microsoft.com in the next scheduled publishing run. 

We will now close this issue. Feel free to re-open or create another issue through the *feedback feature* if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
