### ISSUE TITLE
Global Profile

### ISSUE THREAD

**Issue by jjchaos** [MicrosoftDocs/windows-itpro-docs#4886]
When will the Global Profile feature be available? Are there any other methods to apply a profile to all users except Domain Admins to use in the mean time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78038d67-04a1-f4ae-6a69-98e157688a31
* Version Independent ID: c86b4460-e8be-8537-a6c8-3cb094ef14a3
* Content: [Set up a multi-app kiosk  (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps#feedback)
* Content Source: [windows/configuration/lock-down-windows-10-to-specific-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/lock-down-windows-10-to-specific-apps.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @jjchaos, good question. At the moment, the *Global Profile*, including [assigned access](https://docs.microsoft.com/windows/configuration/kiosk-xml) and folder access are currently supported in Windows 10 Insider Preview ([19H2](https://blogs.windows.com/windowsexperience/2019/09/05/announcing-windows-10-insider-preview-build-18362-10019-19h2/), [20H1](https://blogs.windows.com/windowsexperience/2019/09/11/announcing-windows-10-insider-preview-build-18980/) builds). As for your other question, we believe it will be best addressed by contacting [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10). You can also check the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where community members can learn, collaborate, and share experiences about Microsoft products. You can ask your question and start a conversation with other users, experts and also Microsoft engineers. Kindly keep us informed if you find any relevant information that can be incorporated into this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hello @jjchaos, we didn’t hear back from you but we hope the information we've provided helped.  We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
