### ISSUE TITLE
Deployment with Autopilot

### ISSUE THREAD

**Issue by GlennMillerNZ** [MicrosoftDocs/windows-itpro-docs#4893]
Are there plans to implement this or make it functional to deploy with Microssoft Intune and Autopilot?
Admin or User input requirements are useless when using Autopilot.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ac548b-be6c-efba-76ee-67dd7af18891
* Version Independent ID: 947b62e7-1225-2f5e-14ba-fe5dccbbe124
* Content: [Use System Center Configuration Manager to manage devices with SEMM (Surface)](https://docs.microsoft.com/en-nz/surface/use-system-center-configuration-manager-to-manage-devices-with-semm)
* Content Source: [devices/surface/use-system-center-configuration-manager-to-manage-devices-with-semm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/use-system-center-configuration-manager-to-manage-devices-with-semm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello again @GlennMillerNZ! At the moment, that's the only available information we have in the docs (via SCCM and also [powerwshell](https://techcommunity.microsoft.com/t5/Core-Infrastructure-and-Security/How-to-Manage-Surface-Pro-3-UEFI-Through-PowerShell/ba-p/257822)). Here's the latest update from Microsoft so far: 

[Introducing Surface Enterprise Management Mode and System Center Configuration Manager Support for SEMM](https://techcommunity.microsoft.com/t5/Surface-IT-Pro-Blog/Introducing-Surface-Enterprise-Management-Mode-and-System-Center/ba-p/328937)

I do encourage you to submit this as a feature suggestion on [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). Your feedback goes directly to the Microsoft engineering team and they would love to hear what you think. 

Thank you for being part of the Microsoft Docs Community!

**Comment by jvsam** [comment]
Hello @GlennMillerNZ, we didn’t hear back from you but we hope the information we've provided clarified this issue for you. Please do not forget to utilize [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub) to share your feedback. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
