### ISSUE TITLE
KIOSK - XML access to directories

### ISSUE THREAD

**Issue by JordyBe** [MicrosoftDocs/windows-itpro-docs#4895]
Hi
First of all, sorry for my English
I'm calling to the community, i have a problem with KIOSK XML.
I wish i could in my file give access to C:\....

My XML :

```
</AllAppsList>
			<rs5:FileExplorerNamespaceRestrictions>
                <rs5:AllowedNamespace Name="Downloads"/>
            </rs5:FileExplorerNamespaceRestrictions>
<StartLayout>
```

How to adapt my code ?
Thx for your help.

**Comment by mypil** [comment]
@JordyBe - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by JordyBe** [comment]
Microsoft document link : https://docs.microsoft.com/fr-fr/windows/configuration/kiosk-xml

Sorry 👍

**Comment by mypil** [comment]
@JordyBe - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)** for Windows 10 products so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
