### ISSUE TITLE
Fyi

### ISSUE THREAD

**Issue by dnsss90** [MicrosoftDocs/windows-itpro-docs#4896]
Just wanted to let you know that the policy is defined by default on member server GPOs if you use MSFT security baseline, both on server 2016 & 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f61291ba-e3db-de54-d408-3cd1eb07f744
* Version Independent ID: 57f2b881-c7b7-e41d-c692-308100658a23
* Content: [Lock pages in memory (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/lock-pages-in-memory#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/lock-pages-in-memory.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/lock-pages-in-memory.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by dnsss90** [comment]
It is defined but empty (no accounts, but not managable on the servers where the GPOs apply).

**Comment by mypil** [comment]
@dnsss90  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@dnsss90 Can you please elaborate what changes are required in the document? At which portion so that we can make the require changes.

**Comment by mypil** [comment]
@dnsss90  - We would like to follow up. Can you please assist to answer the question of joinimran?

Thank you.

**Comment by mypil** [comment]
@dnsss90 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by illfated** [comment]
Sorry for the late follow-up from my side. I can only contribute with how I interpreted the description by the issue ticket author, which seems to point to the following section:

https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/lock-pages-in-memory#default-values

### Default values

The following table lists the actual and effective default policy values for the most recent supported versions of Windows. Default values are also listed on the policy’s property page.

| Server type or GPO | Default value |
| - | - |
| Default Domain Policy | Not defined| 
| Default Domain Controller Policy | Not defined| 
| Stand-Alone Server Default Settings | Not defined| 
| Domain Controller Effective Default Settings | Not defined| 
| Member Server Effective Default Settings | Not defined| 
| Client Computer Effective Default Settings | Not defined| 

I am fairly certain that his intended feedback is that at least one of the rows needs to be updated for
> the policy is defined by default, but empty (no accounts, but not manageable on the servers where the GPOs apply) on member server GPOs if you use MSFT security baseline, both on server 2016 & 2019.

The following change would correlate to that statement:

| Server type or GPO | Default value |
| - | - |
| Member Server Effective Default Settings | Defined (empty) |

**Comment by illfated** [comment]
Caveat: I don't know this topic well enough to vouch for its validity, I also do not have the necessary scenario to test and verify the content above.
