### ISSUE TITLE
Missing Data Export Settings guide for Storage and Event Hubs

### ISSUE THREAD

**Issue by naqash11** [MicrosoftDocs/windows-itpro-docs#4898]
I am searching for quite a while for Data Export Settings but could not find. All i found was for Advance Hunting. I need for Storage and Event Hubs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bdb99e4-289a-c09a-c35c-2774fc52a402
* Version Independent ID: 4d325389-c9b8-2601-0ff4-c7b6bf5a6c28
* Content: [Microsoft Defender Advanced Threat Protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@naqash11  - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mjcaparas** [comment]
Please see if this is what you're looking for: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/raw-data-export-event-hub

**Comment by mypil** [comment]
@naqash11 - We hope that the additional information provided by mjcaparas will help to address your issue. 

Please feel free to open a new issue if you find any documentation error or if there is a specific area of the docs that we can improve on and we will be glad to help fix it. Thank you.
