### ISSUE TITLE
Update Documentation to use different names for the service account cert and the GMSA cert

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/windows-itpro-docs#4900]
In both section you are telling the users to use "WHFB Enrollment Agent" for the template name.   You cannot have two templates with the same name.  Please Update.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd063d0c-8739-15bd-4f16-11b893029845
* Version Independent ID: cd3679fe-dd9c-44f9-04ed-c772a47ca4e4
* Content: [Configuring Hybrid Windows Hello for Business - Public Key Infrastructure (PKI)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mypil** [comment]
@SquirrelAssassin - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by illfated** [comment]
I wonder if it would be enough to specify some kind of acronym or initialization for the variable part of the template name, e.g.
- WHFB Enrollment Agent (GMSA)
- WHFB Enrollment Agent (TSA)

Then again, I don't know this topic well enough or have a test scenario available, so I don't know the implication or consequences for the rest of the guide when the names change.

**Comment by joinimran** [comment]
@SquirrelAssassin Thanks for your query, There is a note mentioned in the doc 
![image](https://user-images.githubusercontent.com/47118050/64949537-d876cd00-d892-11e9-9110-4841436f3985.png)
This all depends on user needs regarding naming.

Imran.

**Comment by mypil** [comment]
@SquirrelAssassin - From our understanding, the issue has been answered by joinimran. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.
