### ISSUE TITLE
Code snippets in this page

### ISSUE THREAD

**Issue by sirdurable** [MicrosoftDocs/windows-itpro-docs#4906]
At the top, you provide snippets in PowerShell. In the middle, you provide snippets listed as "PS", which is also PowerShell (not sure why you couldn't spell it out there). Then at the bottom, you provide snippets in DOS command-line for getting the status of a service, which you could EASILY continue to provide in PowerShell. It would be much more consistent.
Get-Service -Name windefend
Get-Service -Name mpssvc

Just some feedback...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d1dee2b-d86a-0019-f689-81483fab31f5
* Version Independent ID: 02722ca2-1dde-aafb-22e3-67259c4ece37
* Content: [Windows Defender Antivirus on Windows Server 2016](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-on-windows-server-2016#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-on-windows-server-2016.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-on-windows-server-2016.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Hello @sirdurable, and thank you for the feedback. I'm working on this, and I'll post an update here soon.

**Comment by denisebmsft** [comment]
Hello again! I've updated the article and it'll be republished soon. If you still have questions after the changes go live later today, please let us know. I'm going to close this issue for now. Thank you very much for the feedback, as it helps us improve the quality of our content. Have a great day!
