### ISSUE TITLE
MFA Option

### ISSUE THREAD

**Issue by SB-o-matic** [MicrosoftDocs/windows-itpro-docs#4911]
Hello and thank you for your time.
The wording of the section on MFA confuses me a little. 
I have AADConnect. PHS is enabled as backup to AD FS

1. "... if your Azure AD Connect is configured to synchronize credentials (username and passwords..." Does this mean PHS is turned on? Does it matter if it is turned on just as a backup but federation is actually being used?
2. In my scenario, can I user Azure MFA cloud service directly or do I need to use AD FS 2016 MFA adapter?

**Comment by mypil** [comment]
@SB-o-matic - May we know which Microsoft document link you used in reference to this issue?

Please share it with us so we can investigate further. 

Thank you.

**Comment by mypil** [comment]
@SB-o-matic - We would like to follow up on this. May we know which Microsoft document link you used in reference to this issue? 

Please share it with us so we can make the necessary changes to improve the MS document for accuracy.

**Comment by mypil** [comment]
@SB-o-matic - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
