### ISSUE TITLE
registry setting incorrect for 18.23 Voice Activation - Let Windows apps activate with voice while the system is locked

### ISSUE THREAD

**Issue by mchaudoir** [MicrosoftDocs/windows-itpro-docs#4915]
registry setting incorrect for 18.23 Voice Activation - Let Windows apps activate with voice while the system is locked
replace "Create a REG_DWORD registry setting named PublishUserActivities in HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\AppPrivacy with a value of 0 (zero)" with "Create a REG_DWORD registry setting named LetAppsActivateWithVoiceAboveLock in HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\AppPrivacy with a value of 2 (Force Deny)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abd3113-b803-87b6-ef7f-6893bcc5ceb5
* Version Independent ID: 6f7ca1ee-d19c-42bb-7db5-6158fc160e32
* Content: [Manage connections from Windows 10 operating system components to Microsoft services](https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services#feedback)
* Content Source: [windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by medgarmedgar** [comment]
thanks, fixing this in an upcoming publish

**Comment by e0i** [comment]
Hello @mchaudoir  ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
