### ISSUE TITLE
Tags do not work if they contain parentheses

### ISSUE THREAD

**Issue by Jeremy919** [MicrosoftDocs/windows-itpro-docs#4920]
If a tag name contains parentheses - e.g. Servers (SCCM) - then it does not work for filtering in the Defender ATP machine list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b42e708-e334-d434-bcc9-e1860ebb36b3
* Version Independent ID: 92e251c5-8613-ce97-9569-02404c9a466a
* Content: [Create and manage machine tags](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/machine-tags#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/machine-tags.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/machine-tags.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Hi Jeremy919, 

I will add a note to the documentation, but feel you it might better to send a frown through the portal so that the product team is aware of this bug and address the issue better.

Thanks!
