### ISSUE TITLE
Incorrect Product Reference: HP vs. Micro Focus ArcSight

### ISSUE THREAD

**Issue by ephemeraldrive** [MicrosoftDocs/windows-itpro-docs#4925]
ArcSight has been acquired by Micro Focus in 2017. We are in 2019. Reference to HP ArcSight must be severely out of date

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 250b790c-3309-2651-cefd-e94d3dd5bc11
* Version Independent ID: 54000705-40ce-d014-7bda-4296c1de2e29
* Content: [Configure HP ArcSight to pull Microsoft Defender ATP detections](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-arcsight#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-arcsight.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/configure-arcsight.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Topic updated.
