### ISSUE TITLE
Missing some information

### ISSUE THREAD

**Issue by bencorley** [MicrosoftDocs/windows-itpro-docs#4926]
AGPM v3 SP3 work with Windows Server 2016. Please add this information. The product will be supported until 14th of April 2026 ! Thank you.

https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/New-extended-support-dates-for-MDOP-tools/ba-p/837312

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71008c16-65b9-7a91-e994-dd6f47ed85cf
* Version Independent ID: a2a4502a-18f3-db59-b4e0-ad2650b980bc
* Content: [Advanced Group Policy Management](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/agpm/)
* Content Source: [mdop/agpm/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/agpm/index.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@bencorley 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
