### ISSUE TITLE
Cannot remove long tags

### ISSUE THREAD

**Issue by Jeremy919** [MicrosoftDocs/windows-itpro-docs#4928]
If a tag is long enough (due to upper-case letters, or number of characters) to be truncated by the GUI, then it becomes impossible to remove.  Here's an example of a tag which cannot be removed: TKQRUGBNMWEOPXZDSTU

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b42e708-e334-d434-bcc9-e1860ebb36b3
* Version Independent ID: 92e251c5-8613-ce97-9569-02404c9a466a
* Content: [Create and manage machine tags](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/machine-tags)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/machine-tags.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/machine-tags.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
For issues related product, please submit a frown from the portal.
