### ISSUE TITLE
Missing Error Code

### ISSUE THREAD

**Issue by arlight1** [MicrosoftDocs/windows-itpro-docs#4929]
Error code 0x80070490 is missing from this list of definitions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mikeatms** [comment]
I am getting error code 0x801c0451, which is also missing

**Comment by nicksal21** [comment]
I am getting 0x801C044F, which is also missing (stops at E).

**Comment by oliversalzburg** [comment]
0x801c004d is also missing

**Comment by oliversalzburg** [comment]
Seems like this was already reported in https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2900 :(
If the error code is surfaced by an underlying component, this documentation should still include it or point to other documentation. Leaving a dead-end on an error is just frustrating.

Even better would be to handle errors in the application and provide useful information instead.

**Comment by e0i** [comment]
Hello, @arlight1 

This is a known issue that has also been addressed in #3123 #3092 #2941 #2900 #2804 #2685 #2684 #2676 #2421 and #2409.

The error code in question might actually have surfaced from external services _rather_ than Windows Hello itself.

Find below a quoted reply from Content Developer:

**DaniHalfin** wrote:

>     For error codes unlisted here, in most cases those are transient error codes
>     being surfaced by other services in the Windows Hello dependency chain.
> 
>     We are working on something to improve the user experience in that regard,
>     but that will not solve the issues you are experiencing.
> 
>     If we find a reoccurring error codes that isn't covered here and should be
>     (meaning, in most cases, it is coming from Windows Hello and not other
>     components) we'll make sure to add it to this page.

We are closing this issue but feel free to re-open it if you feel that we might have missed something.

Have a nice day.

**Comment by oliversalzburg** [comment]
@e0i I understand your reasoning, but you should also realize that there is an error dialog in Windows (Hello) that sends people to specifically this page in the documentation. This page feels incomplete, because it doesn't address an error code that is displayed in said dialog.

You have a dialog with an error code, you send people to a documentation page that claims to provide assistence with error codes in the area associated with the error dialog. It should be obvious why this is a potentially frustrating situation for users.

Closing these tickets, without addressing the underlying cause is further frustrating users. Microsoft is in the best position to resolve these issues. At the very least, maybe start listing the most commonly reported error codes, note that it's surfaced from an underlying component and what people can do to reach a solution.

**Comment by illfated** [comment]
I see what you are saying. I agree that it will be frustrating to be given a link to a Microsoft resource whenever the error code is undocumented. I also think this is something the developers need to address, given that the offending application is the error reporting part of Windows Hello itself. I am fairly certain that we need to use **Windows Feedback** or **Feedback Hub** to report this behaviour as less than satisfying when it comes to the amount of undocumented error codes. The developers should address the situation by not directing the users to a Microsoft resource whenever a non-documented error occurs.

@e0i : Could you suggest the proper Feedback instance to use for Windows Hello for Business?
