### ISSUE TITLE
Recommend change "...but not date at this time" to "...but no date is set at this time."

### ISSUE THREAD

**Issue by robhurt** [MicrosoftDocs/windows-itpro-docs#4932]
Recommend change this...
Microsoft will be deprecating virtual smart cards in the future but not date at this time.
to...
Microsoft will be deprecating virtual smart cards in the future but no date is set at this time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82ecd7ea-0ecb-cf7b-a1ab-9cda97e5cc0a
* Version Independent ID: 81acb0ad-2d46-bd0b-abb5-7c2e851d7a71
* Content: [Windows Hello for Business Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-faq)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-faq.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by jvsam** [comment]
assign @jvsam

**Comment by jvsam** [comment]
Hello @robhurt, thank you for bringing this to our attention. I will get this over to the Windows content writing team for correction. We always strive to improve the quality of the technical documentation of Microsoft Docs so your feedback is appreciated!

Thank you for being part of the Microsoft Docs Community!

**Comment by jvsam** [comment]
Hello @robhurt we'd like to inform you that the updates are now displayed here at docs.microsoft.com. You can verify by visiting this URL: https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-faq. Thank you again for your feedback, much appreciated!

As always, thank you as well @illfated for proactively creating the PR to fix this. Regards to you!
