### ISSUE TITLE
Set what information is shared in Search - policy not supported on Win10

### ISSUE THREAD

**Issue by amandeepmand** [MicrosoftDocs/windows-itpro-docs#4948]
Per screenshot below, this policy appears to not be supported on Windows 10

![image](https://user-images.githubusercontent.com/44652176/65008211-8bb4e580-d8d6-11e9-9c4c-5e79c2005057.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abd3113-b803-87b6-ef7f-6893bcc5ceb5
* Version Independent ID: 6f7ca1ee-d19c-42bb-7db5-6158fc160e32
* Content: [Manage connections from Windows 10 operating system components to Microsoft services](https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services#feedback)
* Content Source: [windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @medgarmedgar
* Microsoft Alias: **v-medgar**

**Comment by medgarmedgar** [comment]
Correct, I will be removing the mention of this policy from the article very soon. Thanks.

**Comment by mypil** [comment]
@amandeepmand - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the doc owner- medgarmedgar. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
