### ISSUE TITLE
Do not allow web search - Policy not supported on Win10

### ISSUE THREAD

**Issue by amandeepmand** [MicrosoftDocs/windows-itpro-docs#4949]
Per the screenshot below, this policy appears to not be supported on Windows 10

![image](https://user-images.githubusercontent.com/44652176/65009749-cff6b480-d8db-11e9-9942-c79e9161301a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abd3113-b803-87b6-ef7f-6893bcc5ceb5
* Version Independent ID: 6f7ca1ee-d19c-42bb-7db5-6158fc160e32
* Content: [Manage connections from Windows 10 operating system components to Microsoft services](https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services#feedback)
* Content Source: [windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @medgarmedgar
* Microsoft Alias: **v-medgar**

**Comment by medgarmedgar** [comment]
Hi, this is supported, it states "or later" in the description.

**Comment by amandeepmand** [comment]
Thanks for the clarification.  Based on the phrasing I was under the impression it referred to later versions of "Windows Search."

**Comment by medgarmedgar** [comment]
That GP description could be improved, but I checked internally and it is still a valid GP.

**Comment by Dansimp** [comment]
Closing issue
