### ISSUE TITLE
Incorrect Discovery URL?

### ISSUE THREAD

**Issue by learningdaily** [MicrosoftDocs/windows-itpro-docs#4951]
Within the documentation, you reference this URL:

(Step 5 under verify Auto Enrollment)
Verify that the MDM discovery URL during auto-enrollment is https://enrollment.manage.microsoft.com/enrollmentserver/discovery.

The URL within the console is the following: https://enrollment.manage.microsoft.com/enrollmentserver/discovery.svc

Notice no 'SVC' extension in documentation.

Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy#feedback)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@learningdaily - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@ManikaDhiman - Can you please share your insights on this issue?

Thank you.

**Comment by ManikaDhiman** [comment]
Hi @mypil, this issue is fixed via PR [#4923](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4923). Thanks!

**Comment by illfated** [comment]
@learningdaily : The documentation will be updated with the `.svc` ending, we just need to wait a few days for the migration from Github to docs.microsoft.com to take place.
Your issue was already reported in issue ticket #4841 .

**Comment by mypil** [comment]
@learningdaily - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
