### ISSUE TITLE
Missing 1903 Documentation Updates

### ISSUE THREAD

**Issue by miketheitguy** [MicrosoftDocs/windows-itpro-docs#4957]
It seems there have been some large changes to WDAC in 1903, which involves new multiple policy formats, some new folders in C:\Windows\System32\CodeIntegrity ; as well as the creation of a DriverSiPolicy.p7b file in that folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63d0bf1f-f22a-7c43-59a2-595c7c0a75dc
* Version Independent ID: 3917f746-07f4-cb69-7a21-535c875d6c2c
* Content: [Planning and getting started on the Windows Defender Application Control deployment process (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control-deployment-guide)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control-deployment-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control-deployment-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@Dansimp Would you be able to share any plans to update the documentation in compliance with version 1903? Let us know in any ways we could help in coming up with relevant changes. Thank you for your time.
