### ISSUE TITLE
Unable to remove Enterprise Domain Controller Group from the policy

### ISSUE THREAD

**Issue by yckwan** [MicrosoftDocs/windows-itpro-docs#4961]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26371c81-f040-cb55-43d3-c923ae5f5f6a
* Version Independent ID: bdfe2a76-c085-cfae-e676-6bc037e74fea
* Content: [Access this computer from the network - security policy setting (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/access-this-computer-from-the-network)
* Content Source: [windows/security/threat-protection/security-policy-settings/access-this-computer-from-the-network.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/access-this-computer-from-the-network.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@yckwan

Your feedback is missing content. Would you be able to clarify the product documentation issue in relation to the associated article? We would like to follow up. Thanks.
