### ISSUE TITLE
SMB Shares

### ISSUE THREAD

**Issue by peterpantheking** [MicrosoftDocs/windows-itpro-docs#4962]
In the article it's stated that you are able to access smb shares and mark it as company data. But I am not able o figure it out. I added my file-server where the share is loacated as a netowork domain and I added IP ranges which include the mentioned file-server. Data from the fileshare is still myrked as personal data. Do I need to activate WIP on the file-server? Can you create a more detailed guide on smb shares?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ad3f92-24de-5eb5-8454-c72d85737183
* Version Independent ID: 900125eb-31ea-faf3-ac30-7c3d7b30f611
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by j0rt3g4** [comment]
@Dansimp Since on the docs are missing some data about this issue, is it possible to add any kind of lights on this issue?

For this one, if you haven't done a MAM policy you're not in a position to answer this one accurately. I

**Comment by martin-rublik** [comment]
+1 also would be interested

**Comment by VLG17** [comment]
@peterpantheking Could you give some examples of data from the SMB share which is not market as company data?

I don't understand what you mean with "Do I need to activate WIP on the file-server?". Adding the file servers of the SMB Share **is part of the WIP policy configuration**.

As the article states, the steps are:

1. Create a WIP Policy and declare your protected apps (Office, Notepad, IE11 for example)

2. After you've added the apps you want to protect with WIP, you'll need to apply a management and protection mode. 

3. Choose where apps can access enterprise data - **in your case the SMB share, which you've added.**

So if you declare your protected apps correctly and the file servers are added to the WIP Policy, there should be no issue. 

Also, could you use [this method](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/wip-app-enterprise-context) to check the Enterprise Context of the apps/data on your file servers?

If you still exibit the issue after checking the WIP policy configuration, i would suggest oppening a case with [Azure Support](https://azure.microsoft.com/en-us/support/create-ticket/).

**Comment by e0i** [comment]
Hello @peterpantheking,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
