### ISSUE TITLE
windows 10 1903

### ISSUE THREAD

**Issue by aldoeri** [MicrosoftDocs/windows-itpro-docs#4966]
WINDOWS DEPLOYMENT TOOLKIT  IS HAVING PROBLEMS WITH POWER SHELL HOW CAN I FIX THEM

**Comment by illfated** [comment]
@aldoeri : This site is first and foremost a place to give feedback on existing Microsoft Documentation, suggest improvements or point out something outdated, maybe even incorrect in the Docs.

Your problem should be handled by a Microsoft Support entity in your region or area.

**Comment by Dansimp** [comment]
Closing issue as it's not specific to documentation
