### ISSUE TITLE
Image from step 5 is missing

### ISSUE THREAD

**Issue by danieldhudson** [MicrosoftDocs/windows-itpro-docs#4967]
The image for step 5 is missing

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e78f073c-9f6b-b9d2-cd94-0a31998f10d9
* Version Independent ID: 5beaeca4-3d07-c65c-018b-a88cda5ceb9a
* Content: [Using the Surface Hub Recovery Tool](https://docs.microsoft.com/en-gb/surface-hub/surface-hub-recovery-tool#feedback)
* Content Source: [devices/surface-hub/surface-hub-recovery-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/surface-hub-recovery-tool.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Took me a few moments to understand what you meant, but then I saw the image link surrounded by a code block fence, instead of being accessible as an image. That is sort of funny. Should be easy to fix, though.
