### ISSUE TITLE
The wording

### ISSUE THREAD

**Issue by MichaelFirsov** [MicrosoftDocs/windows-itpro-docs#4971]
"To see that the operation was performed, check “4663(S): An attempt was made to access an object.”" - I think the word "what" or "which" would be more appropriate here.
"To see what/which operation was performed, check “4663(S): An attempt was made to access an object.”"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2286d366-a0ef-e224-2b74-782a80a4820e
* Version Independent ID: 36ebd64c-e558-26a2-658f-929b87c3990b
* Content: [4656(S, F) A handle to an object was requested. (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4656)
* Content Source: [windows/security/threat-protection/auditing/event-4656.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/event-4656.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Fair enough, but I think you might have missed the meaning of the preceding sentence. Please notice the text I have highlighted in **bold** :

> This event shows that access was requested, and the results of the request, **but it doesn’t show that the operation was performed**.

> To see **that the operation was performed**, check “4663(S): An attempt was made to access an object.”

**Comment by MichaelFirsov** [comment]
_" _I think you might have missed the meaning of the preceding sentence._"_ - yes, I have... Agree - please excuse me for the disturbance!

**Comment by illfated** [comment]
No problem at all. Happy to hear that you find it agreeable.

@e0i : May we get this issue ticket closed?

**Comment by MichaelFirsov** [comment]
"_May we get this issue ticket closed_?" - sure!

**Comment by illfated** [comment]
Very well, then. Feel free to close this issue whenever you can find the **[Close]** or **[Close and comment]** button.
