### ISSUE TITLE
JSON gets deleted after sysprep in Windows 10 1903 builds

### ISSUE THREAD

**Issue by sebassem** [MicrosoftDocs/windows-itpro-docs#4972]
When going through the steps outlined above using a 1903 image the JSON file gets deleted after the sysprep step so the device never gets the autopilot OOBE experience. The only workaround around this is to use the steps outlined in the "Speeding up the deployment process" URL. The steps needs to be reflect new steps to go around this till a fix is available for 1903

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17bfe927-f7b7-608b-8537-5c2274ccdced
* Version Independent ID: 5dd9abca-92d9-fbb2-6796-d1f6b9ab3c8b
* Content: [Windows Autopilot for existing devices](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/existing-devices#feedback)
* Content Source: [windows/deployment/windows-autopilot/existing-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/existing-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
There will be an addition to the page soon with details on how to work around this issue. You can also use the 'speeding up' process, but there is a simpler method also. I will publish those details soon.

**Comment by greg-lindsay** [comment]
OK the addition should publish today. You can also read Michael Niehaus' blog about this at https://oofhours.com/2019/09/19/a-challenge-with-windows-autopilot-for-existing-devices-and-windows-10-1903/

**Comment by sebassem** [comment]
Thanks for the swift reply, waiting for the addition to share with my customer :)
________________________________
