### ISSUE TITLE
The Configuration Service Provider Page has duplicate <!--StartCSP--> tags

### ISSUE THREAD

**Issue by tr5tn** [MicrosoftDocs/windows-itpro-docs#4974]
The [Configuration Service Provider Page](https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference) has duplicate  tags on rows 2680/2681 (between the "windowsadvancedthreatprotection-csp" and "windowsdefenderapplicationguard-csp" CSP links.

**Comment by illfated** [comment]
Thanks, I will post a fix for that. Interesting find, BTW. 👍
From your experience, does the duplicate tag cause anything interesting to happen?

**Comment by tr5tn** [comment]
> Thanks, I will post a fix for that. Interesting find, BTW. 👍
> From your experience, does the duplicate tag cause anything interesting to happen?

@illfated it causes a problem with my script, which scrapes the page.

**Comment by illfated** [comment]
Thank you for your feedback. I was curious as to whether you would get back to this issue at all, so thanks for following up. 😉

**Comment by tr5tn** [comment]
@illfated no worries, and thanks for your help with this.
