### ISSUE TITLE
Diagnostic logs

### ISSUE THREAD

**Issue by ang216** [MicrosoftDocs/windows-itpro-docs#4975]
Please elaborate on how diagnostic logs can be gathered. I am currently troubleshooting a failed white glove provisioning, and I cannot figure out how to gather and view diagnostic logs. I cannot find this documentation on this page or the page for Troubleshooting Windows Autopilot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5b57d1-61b3-39d4-34ff-d6dcb858c250
* Version Independent ID: 42609104-815f-9e7a-39aa-38d92cc910c9
* Content: [Windows Autopilot for white glove deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove#feedback)
* Content Source: [windows/deployment/windows-autopilot/white-glove.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/white-glove.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Let's see if I can post the example image here..

![diagnotics](https://user-images.githubusercontent.com/19394290/65281278-12d8a800-dae7-11e9-820a-820396000d93.png)

**Comment by greg-lindsay** [comment]
Also, you can go to a command prompt and run the following:
mdmdiagnosticstool.exe -area Autopilot;TPM -cab c:\autopilot.cab
