### ISSUE TITLE
Microsoft Surface Dock Updater Doesn't Exist

### ISSUE THREAD

**Issue by novarichuffman** [MicrosoftDocs/windows-itpro-docs#4984]
Microsoft Surface Dock Updater doesn't exist anymore so this should be taken out of the steps for checking on the update process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4841f8c9-98e1-7d39-d4fc-39f034e9f534
* Version Independent ID: 3df9714b-c602-0825-d70c-2971e37c1987
* Content: [Microsoft Surface Dock Firmware Update](https://docs.microsoft.com/en-us/surface/surface-dock-firmware-update#feedback)
* Content Source: [devices/surface/surface-dock-firmware-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/surface-dock-firmware-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by Typhoon87** [comment]
It looks like it still does but unless there the newest version dumps the build number back to the 1.X line? 

Is this a mistake or is Microsoft just being Microsoft with the confusion?

**Comment by novarichuffman** [comment]
It doesn't, if you download the latest version all you can do is check the registry for update information and the dock updater tool does not exist. Downloads for it has also been removed entirely.

**Comment by Typhoon87** [comment]
https://techcommunity.microsoft.com/t5/Surface-IT-Pro-Blog/Modernized-updating-for-your-Surface-Dock/bc-p/868105

So they have updated the file to support MSI but it is still a dock firmware updater.

**Comment by novarichuffman** [comment]
If you continue to the to click the links the updater happens in the background while you work. The tool, where it says to use Microsoft Surface Dock Updater does not exist for download anymore.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for bringing this to our attention @novarichuffman. And thanks for sharing the Tech Community link @Typhoon87. Reading through the ongoing conversation, it seems that it's only applicable to certain versions.

> The firmware (MSI) is only installable on Windows 10 1803 and beyond (any edition). o In Windows 10 S mode, the previous tool didn’t work and it this one won’t since it’s a MSI package (no executables were able to run)...

Can you please confirm? It would help if you can let us know what specific information you want us to suggest to the doc author. Isn't the *note* added at the beginning of the doc enough? Should we add *Requires Surface devices running at least Windows 10 version 1803 or later*? The more information you can provide, the faster we can create a PR and submit it for review. Looking forward to your suggestions.

**Comment by LtCmdrKeene** [comment]
It seems that the instructions are wrong, you will never find anything in your Start Menu > All Apps after installing the new MSI.

**Comment by novarichuffman** [comment]
@jvsam  Say I had the old Dock Updater, the Microsoft Surface Dock Updater would exist on my devices. This new version (.msi) which runs in the background would not have any such application installed on these devices. The suggestion is to remove that part from the doc and instead refer to the regedit where you can see the status of your dock update. 
I didn't look into it but the part where you can check a log of the installation seems like it could use more clear instruction.

**Comment by LtCmdrKeene** [comment]
The instructions recommend uninstalling the old updater first (which I did from control panel using appwiz.cpl), so no Start menu entry is found at all.  I know it said no reboot was required, but I rebooted in an effort to get it to show up so I could find it.

**Comment by novarichuffman** [comment]
@LtCmdrKeene Yes, that is because the author must have been confused and modified an old version of this doc where that would apply. If you had used the old updater in the past, thats exactly how it processed the fw update but since its now a background process it should basically just be removed from the doc.

**Comment by LtCmdrKeene** [comment]
Got ya.  Well I can at least confirm it worked as expected otherwise. I opened regedit, looked at the key values and they were outdated. Unplugged my Surface Book 2 for around 30 seconds, plugged it back in, and nearly immediately the registry updated with the new values as described in the doc.

**Comment by novarichuffman** [comment]
Can confirm as well, I have updated a few of the surfaces at our office via this new method.

**Comment by LtCmdrKeene** [comment]
I was hoping this would resolve a bug where my external monitor continuously turns on/off when the PC tries to put the monitor into standby mode. Is there an appropriate forum to post feedback about the dock itself?  Maybe just the feedback hub, I'm not sure.

**Comment by novarichuffman** [comment]
Likely the feedback hub, numerous surfaces of all types have docking issues that require a combination of enabling external montiors and restarting the surface while docked. It is a huge pain!

**Comment by jvsam** [comment]
Hello @LtCmdrKeene and @novarichuffman, thank you so much for the clarification. This has been an interesting discussion. We always want to engage community users in improving the quality of the technical documentation, hence, the creation of this Github feedback system. 

>  If you had used the old updater in the past, thats exactly how it processed the fw update but since its now a background process it should basically just be removed from the doc.

Which part of the doc you recommend removing or changing (*perhaps restating*) so we can assist in creating a pull request and submit it to the author for review? If you have a preferred *messaging*, please let us know. If you are familiar with the [doc contribution process](https://docs.microsoft.com/contribute/), I would also recommend you doing that. 

As for submitting feedback or suggestions related to Microsoft Surface, yes you can submit it on [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)/Feeddback Hub. Your feedback goes directly to the Microsoft engineering team and they would love to hear what you think.

**Comment by novarichuffman** [comment]
Hey, @jvsam 
Looks like the change has been made, if im not mistaken.

**Comment by jvsam** [comment]
That's great @novarichuffman. To confirm, are you talking about the change on step 2?

> 2. After you connect Surface Dock to your Surface device, the tool checks the firmware status while running in the background.

Here are the [recent updates](https://github.com/MicrosoftDocs/windows-itpro-docs/commits/public/devices/surface/surface-dock-firmware-update.md) to this doc.

**Correct md file:** https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-dock-firmware-update.md

**Comment by novarichuffman** [comment]
Yes that change is appropirate, the logging should be mentioned as part of the MSI execution. I see some comments that it is convoluted  @jvsam

**Comment by jvsam** [comment]
> the logging should be mentioned as part of the MSI execution.

Thanks for the confirmation @novarichuffman. For the logging, specifically which information? Are you pertaining to this?

> 4. If unable to verify, review Event logging and Troubleshooting tips in the next section.

Do you have any suggestions on how it should be written that will make it easier for Surface users to understand (or follow the steps)?

**Comment by novarichuffman** [comment]
@jvsam I believe it should accurately tell the reader to declare those parameters during the installation. 

/l*v %windir%\logs\ SurfaceDockFWI.log
--

Noting that the user can declare this as additional parameters upon installing the .msi

**Comment by jvsam** [comment]
Thanks for the suggestion @novarichuffman. Make sense to provide more clarity.

If you are not busy @illfated, do you want to review this and create a PR with the recommended update? On a related issue (see #5046), a user mentioned that the log file is not created by default. Let me know, thanks as always!

**Comment by illfated** [comment]
Sure, I can do that. Thank you for the suggestion.

**Comment by illfated** [comment]
Sorry for the delay, I have not been well enough to do any constructive work lately. I will do my best to follow up this week.

**Comment by jvsam** [comment]
No worries @illfated.  You've been helping the community a lot, you deserve a break! :-)

**Comment by jvsam** [comment]
@illfated, a gentle follow-up. Only if you are not busy! :-)

**Comment by illfated** [comment]
Thank you for the reminder. Yes, it has been quite some time where I have had less surplus to be able to make any effort to contribute with much more than just comments and obvious PR content. I have also noticed some other tickets related to this issue, so there may have been some changes to the documentation lately, in light of the issue discussed above.

**Comment by jvsam** [comment]
@illfated thanks. I see one that may be related, I'll get into that. The suggested update here with regard to logging will clear some of the confusion.

**Comment by illfated** [comment]
Thank you. I noticed that there is at least 1 existing PR for this page, so maybe we could ask @j0rt3g4 if this is something he could add to his existing PR.

**Comment by illfated** [comment]
There is also https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5274 by @VLG17 related to this.

**Comment by jvsam** [comment]
Thanks @illfated, #5274 suggests to delete the location path, but here, it's recommending to add or call out */l*v %windir%\logs\ SurfaceDockFWI.log* when installing the .msi update. #5098 is also a different update.

@j0rt3g4 will you be able to assist and add this update on your PR? Thank you in advance.

**Comment by jvsam** [comment]
@illfated do you have any recommended messaging so @j0rt3g4 can add it to his PR?

**Comment by j0rt3g4** [comment]
@jvsam  sure thing I'd do it

**Comment by jvsam** [comment]
Thank you so much @j0rt3g4!

**Comment by jvsam** [comment]
Hi @novarichuffman, there have been a couple of approved changes to this documentation that will address the issues raised here. The content updates will be displayed here at docs.microsoft.com in the next scheduled publishing run. Feel free to re-open or create another issue through the doc's *feedback feature*, if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
