### ISSUE TITLE
Table 1. Event logging for Surface Dock Firmware Update

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/windows-itpro-docs#4987]
Surface Dock Firmware Update log Location	/l*v %windir%\logs\SurfaceDockFWI.log
What's the /l*v doing there? Isn't that part of the command to create the log?
I've verified completion of firmware update in the registry, but I have no SurfaceDockFWI.log anywhere on my Surface.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4841f8c9-98e1-7d39-d4fc-39f034e9f534
* Version Independent ID: 3df9714b-c602-0825-d70c-2971e37c1987
* Content: [Microsoft Surface Dock Firmware Update](https://docs.microsoft.com/en-us/surface/surface-dock-firmware-update)
* Content Source: [devices/surface/surface-dock-firmware-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/surface-dock-firmware-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @BR77BE, thanks for your question.

**Comment by RAJU2529** [comment]
@BR77BE . l means logging . v means verbose output.
/l*v this used while installing .msi or .exe file with  detailed logs . IT pro and advanced users uses normally command prompt

**Comment by BR77BE** [comment]
You managed to miss both of my points completely:
1) Why do those four characters /l*v appear under LOCATION in Table 1? Are they part of a location?
2) Why do I have no SurfaceDockFWI.log anywhere on my Surface after updating dock firmware?

**Comment by RAJU2529** [comment]
@BR77BE . two meanings are there , 1. used for command  prompt.
2. simply added to better understand

**Comment by BR77BE** [comment]
You didn't answer either of my questions.

**Comment by jvsam** [comment]
Hello @BR77BE thank you for your question. Perhaps this comment in #5046 may provide some insights. 

> The "/l*v" [plus a path] should be appended to the msiexec command to create a log file, it's not created by default. I have already logged a doc bug for this.

We hope that helps. Thanks too @RAJU2529 for engaging with the community. Appreciate it.

**Comment by jvsam** [comment]
Hello again @BR77BE, we didn’t hear back from you but we hope the information we've provided helped. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
