### ISSUE TITLE
Issue when installing Surface_Dock_FwUpdate that was released on 9/18

### ISSUE THREAD

**Issue by madhoun** [MicrosoftDocs/windows-itpro-docs#4989]
I installed the new firmware updater for surface dock - no errors once i completed the installation.

Registry showing the following:
Component10CurrentFwVersion = 4ac3970
Component20CurrentFwVersion = 499a170

But it appears the installation is failing silently. Looking at the logs in setupapi.dev.log file under C:\Windows\INF, I am seeing the following:

>>>  [Device Install (DiInstallDriver) - C:\WINDOWS\System32\DriverStore\FileRepository\surfacedockintegration.inf_amd64_97a6bac9a2c2eb00\surfacedockintegration.inf]
>>>  Section start 2019/09/21 01:12:13.222
      cmd: "C:\WINDOWS\system32\pnputil.exe" -i -a "C:\Program Files\SurfaceUpdate\SurfaceDockIntegration\SurfaceDockIntegration.inf"
     ndv: Flags: 0x00000000
     ndv: INF path: C:\WINDOWS\System32\DriverStore\FileRepository\surfacedockintegration.inf_amd64_97a6bac9a2c2eb00\surfacedockintegration.inf
     inf: {SetupCopyOEMInf: C:\WINDOWS\System32\DriverStore\FileRepository\surfacedockintegration.inf_amd64_97a6bac9a2c2eb00\surfacedockintegration.inf} 01:12:13.224
     inf:      Copy style: 0x00000000
     inf:      Driver Store Path: C:\WINDOWS\System32\DriverStore\FileRepository\surfacedockintegration.inf_amd64_97a6bac9a2c2eb00\surfacedockintegration.inf
     inf:      Published Inf Path: C:\WINDOWS\INF\oem39.inf
     inf: {SetupCopyOEMInf exit (0x00000000)} 01:12:13.227
     ndv: {Update Device Driver - HID\VID_045E&PID_0904&COL05\7&2C78944B&0&0004}
     ndv:      Search options: 0x00000081
     ndv:      Searching single INF 'C:\WINDOWS\System32\DriverStore\FileRepository\surfacedockintegration.inf_amd64_97a6bac9a2c2eb00\surfacedockintegration.inf'
     dvi:      {Build Driver List} 01:12:13.244
     dvi:           Searching for hardware ID(s):
     dvi:                hid\vid_045e&pid_0904&rev_7007&col05
     dvi:                hid\vid_045e&pid_0904&col05
     dvi:                hid\vid_045e&up:ff08_u:0060
     dvi:                hid_device_up:ff08_u:0060
     dvi:                hid_device_upr:ff00-ffff
     dvi:                hid_device
     dvi:           Created Driver Node:
     dvi:                HardwareID   - HID\VID_045E&PID_0904&Col05
     dvi:                InfName      - c:\windows\system32\driverstore\filerepository\surfacedockintegration.inf_amd64_97a6bac9a2c2eb00\surfacedockintegration.inf
     dvi:                DevDesc      - Surface Dock Integration
     dvi:                Section      - SurfaceDockIntegration.NT
     dvi:                Rank         - 0x00ff0001
     dvi:                Signer Score - WHQL
     dvi:                DrvDate      - 03/01/2017
     dvi:                Version      - 2.0.303.0
     dvi:      {Build Driver List - exit(0x00000000)} 01:12:13.261
     ndv:      Searching currently installed INF
     dvi:      {Build Driver List} 01:12:13.262
     dvi:           Searching for hardware ID(s):
     dvi:                hid\vid_045e&pid_0904&rev_7007&col05
     dvi:                hid\vid_045e&pid_0904&col05
     dvi:                hid\vid_045e&up:ff08_u:0060
     dvi:                hid_device_up:ff08_u:0060
     dvi:                hid_device_upr:ff00-ffff
     dvi:                hid_device
     dvi:           Created Driver Node:
     dvi:                HardwareID   - HID\VID_045E&PID_0904&Col05
     dvi:                InfName      - C:\WINDOWS\System32\DriverStore\FileRepository\surfacedockintegration.inf_amd64_97a6bac9a2c2eb00\surfacedockintegration.inf
     dvi:                DevDesc      - Surface Dock Integration
     dvi:                Section      - SurfaceDockIntegration.NT
     dvi:                Rank         - 0x00ff0001
     dvi:                Signer Score - WHQL
     dvi:                DrvDate      - 03/01/2017
     dvi:                Version      - 2.0.303.0
     dvi:      {Build Driver List - exit(0x00000000)} 01:12:13.275
     dvi:      {DIF_SELECTBESTCOMPATDRV} 01:12:13.276
     dvi:           Default installer: Enter 01:12:13.277
     dvi:                {Select Best Driver}
     dvi:                     Class GUID of device changed to: {745a17a0-74d3-11d0-b6fe-00a0c90f57da}.
     dvi:                     Selected Driver:
     dvi:                          Description - Surface Dock Integration
     dvi:                          InfFile     - c:\windows\system32\driverstore\filerepository\surfacedockintegration.inf_amd64_97a6bac9a2c2eb00\surfacedockintegration.inf
     dvi:                          Section     - SurfaceDockIntegration
     dvi:                {Select Best Driver - exit(0x00000000)}
     dvi:           Default installer: Exit
     dvi:      {DIF_SELECTBESTCOMPATDRV - exit(0x00000000)} 01:12:13.283
     ndv:      Currently Installed Driver:
     ndv:           Inf Name       - oem39.inf
     ndv:           Driver Date    - 03/01/2017
     ndv:           Driver Version - 2.0.303.0
     ndv: {Update Device Driver - exit(00000103)}
<<<  Section end 2019/09/21 01:12:13.297
<<<  [Exit status: FAILURE(0x00000103)]

Application event logs showing 2 errors when I try to unplug/plug back the surface dock connector to my surface book:

The description for Event ID 2007 from source SurfaceDockFwUpdate cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

surfacedockfwupdate
Firmware update finished. hr=-2147418113 DriverTelementry EventCode = 2007

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for bringing this to our attention @madhoun. We believe this will be best addressed by contacting [Support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10). You can also check the [Troubleshooting tips](https://docs.microsoft.com/surface/surface-dock-firmware-update#troubleshooting-tips) related to the Microsoft Surface Dock firmware update.

Other support resources include the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where community members can learn, collaborate, and share experiences about Microsoft products. You can ask your question and start a conversation with other users, experts and also Microsoft engineers. 

We hope your issue will get resolved soon. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hi again @madhoun, we didn’t hear back from you but we hope you were able to contact support (*or checked out the other support resources*) and resolved your concern. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
