### ISSUE TITLE
Correction for Win10 Pro & M365B

### ISSUE THREAD

**Issue by davebirr** [MicrosoftDocs/windows-itpro-docs#4993]
Article incorrectly states Windows 10 Enterprise is required.  ASR is included in Windows 10 Pro and Windows 10 Business when used with Microsoft 365 Business.  ASR is part of the Windows value in M365B, configurable by the Device Policies in M365B,  and it's also listed as part of Win 10 Pro standalone here.  https://www.microsoft.com/en-us/WindowsForBusiness/Compare

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9de2e9a-c4c1-3763-6160-9427556291f1
* Version Independent ID: 74160e2f-0f99-a37f-7123-81a31a6fab61
* Content: [Use attack surface reduction rules to prevent malware infection](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for your feedback @davebirr. We appreciate it.

> To use attack surface reduction rules, you need a Windows 10 Enterprise license.

Hello @levinec, hope all is well. Can you please confirm *Attack surface reduction rules* availability on Microsoft 365 Business subscription so we can request for content amendment? I have Microsoft 365 Business subscription and is using [Windows 10 Pro](https://docs.microsoft.com/en-us/microsoft-365/business/support/microsoft-365-business-faqs#what-is-windows-10-business) and I can enable ASR rules. Thank you in advance. 

![image](https://user-images.githubusercontent.com/18371314/65836818-d138d000-e324-11e9-935f-40538904e4c0.png)

**Comment by jvsam** [comment]
Hello again @levinec, I'd like to follow-up on this issue. Can you please confirm if *Attack surface reduction rules* are *officially* available on Microsoft 365 Business subscription + Windows 10 Pro? Thank you so much.

**Comment by levinec** [comment]
Hi @jvsam,

 This is from the PM: 
"This statement is accurate. While you can configure ASR in consumer and E3 Windows version, you won’t have the reporting/monitoring/response capabilities that are only available in E5 (and are needed to use ASR effectively).  I guess it depends on your definition of “use”."

She then suggested an update to the doc so it says:
"To use the entire feature set of attack surface reduction rules, you need a Windows 10 Enterprise license."

I'll make the change tomorrow.

**Comment by levinec** [comment]
The topic has been updated!

**Comment by illfated** [comment]
That is quick work. Good job. The live page is updated already:
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction
(paragraph 2 from the top, just below the [**important**] note)

**Comment by jvsam** [comment]
Awesome, thank you @levinec!

Hi @davebirr, I hope the information provided helped. Please continue to send your feedback and suggestions to improve the quality of the Microsoft documentation. Thanks for being part of the Microsoft Docs community!
