### ISSUE TITLE
JA machine translation of numbers is incorrect

### ISSUE THREAD

**Issue by takondo** [MicrosoftDocs/windows-itpro-docs#4995]
The machine translated version's Logon Type table is terrible. It doesn't seem to recognize the numbers, as the text for Logon Type is jibberish that makes no sense. 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: aefbbdcc-606c-276c-47ee-fe2b2cb65c61
* Version Independent ID: e0979867-e6bc-7fb9-1279-646b319823b0
* Content: [4624アカウントが正常にログオンしました。 (Windows 10)](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/auditing/event-4624)
* Content Source: [windows/security/threat-protection/auditing/event-4624.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/event-4624.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Looks like the English version of that table can be improved with code block fences (or simply MD code markers (back ticks)) to keep the numbers from being translated.

At the same time, should column 2 (**Logon Title**) also retain the original English names as code, not to be translated?
***
| Logon Type | Logon Title       | Description                                                                                                                                                                                                                                                                                                                |
|:----------:|-------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|  `2`       | Interactive       | A user logged on to this computer.                                                                                                                                                                                                                                                                                         |
|  `3`       | Network           | A user or computer logged on to this computer from the network.                                                                                                                                                                                                                                                            |
|  `4`       | Batch             | Batch logon type is used by batch servers, where processes may be executing on behalf of a user without their direct intervention.                                                                                                                                                                                         |
|  `5`       | Service           | A service was started by the Service Control Manager.                                                                                                                                                                                                                                                                      |
|  `7`       | Unlock            | This workstation was unlocked.                                                                                                                                                                                                                                                                                             |
|  `8`       | NetworkCleartext  | A user logged on to this computer from the network. The user's password was passed to the authentication package in its unhashed form. The built-in authentication packages all hash credentials before sending them across the network. The credentials do not traverse the network in plaintext (also called cleartext). |
|  `9`       | NewCredentials    | A caller cloned its current token and specified new credentials for outbound connections. The new logon session has the same local identity, but uses different credentials for other network connections.                                                                                                                 |
| `10`       | RemoteInteractive | A user logged on to this computer remotely using Terminal Services or Remote Desktop.                                                                                                                                                                                                                                      |
| `11`       | CachedInteractive | A user logged on to this computer with network credentials that were stored locally on the computer. The domain controller was not contacted to verify the credentials.                                                                                                                                                    |

**Comment by mypil** [comment]
@takondo - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@TinaMcN - Can you please assist with this Translation/Localization issue?

Thank you.

cc: @kenwith

**Comment by illfated** [comment]
I would like to offer an update (Pull Request) to the `/en-us/` version of the page, surrounding numbers and keywords which should not be translated in that table.

I just need to know how much of the table information should be kept unchanged, before I prepare the PR.

**Comment by kenwith** [comment]
@illfated - very good idea, I had not thought of that and I will share it around with the other writers. Thank you for that. Yes, I believe the Logon Title is like code so it doesn't get translated, we can get @TinaMcN to confirm. Thanks again for this idea! For some reason my brain never thought of it. :)

**Comment by illfated** [comment]
Thanks for the positive reply. I was, as you probably knew already, referring to MarkDown code blocks (back ticks), because code block fences or even simple, single markers around single words have often proved effective against translations in other documents.

**Comment by TinaMcN** [comment]
Yes, the Logon Type numbers and Logon Title values should not be localized.  It's a good idea to block those strings from being localized.  At the same time it's also a bug with the machine translation tool that should know not to localize these items - this has been brought to the attention of the MT tool owners who are currently investigating multiple bugs with the tool.  The MT tool probably won't be fixed for a while so it would be great if you can add the code block to the source content.

**Comment by illfated** [comment]
Very well, thank you for the clarification and additional background information. I will provide a PR for the table content to have MarkDown back ticks around the Logon Type numbers and Logon Title values (presuming that @kenwith has not started working on any change to that document already).

**Comment by illfated** [comment]
There you go. PR #5026 is ready for review.

**Comment by illfated** [comment]
@kenwith : As already mentioned in the PR, thank you for your quick response and merge. I am looking forward to see if this change manages to achieve the expected results after migration to docs.microsoft.com and its translated pages.

**Comment by kenwith** [comment]
@illfated - thank you for the idea and quick PR. It is much appreciated!

**Comment by mypil** [comment]
@takondo - From our understanding, the issue has been resolved based on the merged commit [[c3b5d54](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/c3b5d549465cc314341cbe38918841344a2d4d9c)]. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by TinaMcN** [comment]
I see that the Japanese table looks correct now.  Thanks @takondo for reporting it and thanks to @illfated and @kenwith for your help in fixing it!

**Comment by takondo** [comment]
Thanks all for working on this!

**Comment by illfated** [comment]
It is my pleasure to contribute. You are welcome. 😃
