### ISSUE TITLE
Any news?

### ISSUE THREAD

**Issue by RichardvanNuland** [MicrosoftDocs/windows-itpro-docs#5004]
Hi,

When will there be any updates on these two levels?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f87391fb-1bf8-dc2c-559b-380eb70ab0b9
* Version Independent ID: c4335198-2698-90b2-dfef-a15f8f2591e9
* Content: [Level 5 enterprise administrator workstation security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-security-configuration-framework/level-5-enterprise-administrator-security#feedback)
* Content Source: [windows/security/threat-protection/windows-security-configuration-framework/level-5-enterprise-administrator-security.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-security-configuration-framework/level-5-enterprise-administrator-security.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@RichardvanNuland - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@RichardvanNuland - Can you please share more details on how this content could be edited to incorporate your feedback?

Thank you.

**Comment by RichardvanNuland** [comment]
Hi Joyce,

The documents describe at this moment for the two most secure configurations that this is still being defined. This status is there now for almost half a year. While Microsoft is recommending the deployment of PAWs we are missing actual details on how we should further harden these environments.
Similar to the information for the other 3 levels, I would like to see the details on what must be done to reach this level.

Regards,
Richard

**Comment by mypil** [comment]
@Dansimp - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by Dansimp** [comment]
product team is still working through this. Closing out this issue as we'll update when the information is ready.
