### ISSUE TITLE
Network QOS Policy via Intune

### ISSUE THREAD

**Issue by juicekim** [MicrosoftDocs/windows-itpro-docs#5010]
This is a little abstract for a network guy - examples would be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bb8b93e-0c1a-8b47-472f-effef5f9209e
* Version Independent ID: 8a2615e2-a77b-c08e-b91c-3ce33e0539b2
* Content: [NetworkQoSPolicy CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/networkqospolicy-csp#feedback)
* Content Source: [windows/client-management/mdm/networkqospolicy-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/networkqospolicy-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@juicekim - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
PR #5094

**Comment by mypil** [comment]
@juicekim  - From our understanding, the issue has been resolved based on the merged commit [[34fec09](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/34fec095825de1b94b3af72fe896606d91a8eee5)] but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
