### ISSUE TITLE
Log upload missing details.

### ISSUE THREAD

**Issue by lanatmwan** [MicrosoftDocs/windows-itpro-docs#5012]
The help for diagnostic uploads is lacking some important details for the Command node. 
What is the execution context, local system?
What restrictions are there, if any, on what executable can be run? Can it run powershell.exe?
Is there any timeout?
Inferring from %variable% style, is the process being started from cmd.exe?
If you have multiple Command nodes are they run sequentially? In guaranteed order?

https://docs.microsoft.com/en-us/windows/client-management/mdm/diagnosticlog-csp#diagnosticlog-csp-for-triggering-devices-to-upload-files-to-cloud

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a84b842f-150d-f006-0563-db5a0f01a64f
* Version Independent ID: 7dd55cbe-abc2-9c33-3fef-843b87f26312
* Content: [DiagnosticLog CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/diagnosticlog-csp#feedback)
* Content Source: [windows/client-management/mdm/diagnosticlog-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/diagnosticlog-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@lanatmwan - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Hello @lanatmwan, actually on the line: <command> is the actual command:
```
<Command HRESULT="-2147024637">%windir%\system32\mdmdiagnosticstool.exe -out c:\ProgramData\temp\</Command>
```

And there is more information on the links below:
https://docs.microsoft.com/windows/client-management/mdm/diagnose-mdm-failures-in-windows-10

**Comment by lanatmwan** [comment]
@j0rt3g4 I think you may be responding to the wrong thread?

**Comment by j0rt3g4** [comment]
Ohh @lanatmwan  I don't think so... but if you think so you'll have your reasons :)
Probably we should start over, can you expand more about what you would like to see on the documentation?

**Comment by lanatmwan** [comment]
The docs for DiagnosticLog CSP (linked in my original post here) shows it can run commands now via the <Command> element as you noted. What the doc doesn't tell you is the details about what the capabilities/limitations of said command element are. 

The most basic thing is what user context the command gets run in. I would presume its run as local system and is therefore elevated. 

Next would be whether there are any blocked executables? Can you run powershell.exe from <Command>?

What is the parent process that launches the command? Is it cmd.exe and one can expect other batch file commands/syntaxes like %variableNameToExpand% to work?  For instance, could I optionally run a command by putting an if statement?
`<Command>if [%PROCESSOR_ARCHITECTURE%]==[AMD64] %windir%\system32\ipconfig.exe</Command>`

If I run a command that for some reason doesn't exit, will it eventually time out and kill the command? If so, what is that timeout length? 

If I have defined multiple Command elements, are they run sequentially?

**Comment by j0rt3g4** [comment]
Hello @mypil  Could you please add the author to know their thoughts about this one? (thank you in advance)

**Comment by mypil** [comment]
@ManikaDhiman - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by ManikaDhiman** [comment]
Hi @mypil, I've reached out to the product team to provide guidance. I will update the status/doc as soon as I hear from them. Thanks!

**Comment by mypil** [comment]
@ManikaDhiman - We would like to follow up. Do you have any updates from the Product Team?

Thank you.

**Comment by ManikaDhiman** [comment]
@mypil: No update yet. I will update this doc as soon as I get any input from them. Thanks for the follow up!

**Comment by ManikaDhiman** [comment]
Hi @mypil, substantial content updates have been done to the DiagnosticLog CSP doc, including those that resolve the issue raised here. All the updates are now available in live doc. Hope this helps. Thanks!

**Comment by illfated** [comment]
@lanatmwan , @j0rt3g4 : The page has been updated 11/19/2019 (2 days ago, as of the time of this comment).
Can you confirm that the page now contains the requested information or the answers to your questions?

**Comment by mypil** [comment]
@lanatmwan @j0rt3g4 - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
