### ISSUE TITLE
Wrong path to autologon registry key

### ISSUE THREAD

**Issue by dacabdi** [MicrosoftDocs/windows-itpro-docs#5014]
The reg key for autologon `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsNT\CurrentVersion\Winlogon` should be `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon`, notice the space in `Windows NT`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cd1e023-65ae-0e1d-b031-c02f5fb1daf8
* Version Independent ID: 8053b30a-82b6-404e-5daa-2110fb56c20b
* Content: [Prepare a device for kiosk configuration (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/kiosk-prepare#feedback)
* Content Source: [windows/configuration/kiosk-prepare.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-prepare.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
I concur. There are several keys under `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\` 
which contain 1 space in their name, `\Windows NT\` being one of them.
Should be easy to fix. Do you want to do it yourself, or would you like me to create the PR?

**Comment by dacabdi** [comment]
I'll take it. Thanks!

**Comment by mypil** [comment]
@dacabdi - Thank you for submitting this feedback and for creating the PR.

I will get this PR to the doc owner for review, approval and merging.


Thank you and we appreciate your contribution to make the docs better!

**Comment by mypil** [comment]
@dacabdi - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
