### ISSUE TITLE
Wrong URL

### ISSUE THREAD

**Issue by In-FinIT** [MicrosoftDocs/windows-itpro-docs#5015]
Under "Will there be an alert about Tamper Protection status changing in the Microsoft Defender Advanced Threat Protection portal?", the URL is incorrect - microsoft.securitycenter.com doesn't exist. The domain is owned by a non-Microsoft entity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a2f0402-82fb-83ff-122a-2f19c5288eeb
* Version Independent ID: 52f80b09-0e90-464d-0c4d-00479361fa9b
* Content: [Protect security settings with Tamper Protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by mypil** [comment]
@In-FinIT - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@In-FinIT - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by In-FinIT** [comment]
Hi, the link is still incorrect. Someone has corrected the text, but the link itself is still pointing to the wrong domain!

**Comment by illfated** [comment]
Oh. Right. I missed out on the double URL (visible text + link URL) in the PR. Sorry, I should have noticed that and suggested that both need to be changed.
