### ISSUE TITLE
Server OS support

### ISSUE THREAD

**Issue by RichardvanNuland** [MicrosoftDocs/windows-itpro-docs#5018]
This document mentiones a couple of times a dependency on Windows 10 versions. What is the status for the Server OS? We have a Server Based Computing environment that is used for Communication and Collaboration and the Information Protection requirements also apply to this environment that is based on the Server OS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca51bc21-babf-9810-e26a-360e53cfbac2
* Version Independent ID: c24d6198-d249-3331-5460-5472bcbfe31e
* Content: [Configure information protection in Windows](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/information-protection-in-windows-config)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/information-protection-in-windows-config.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/information-protection-in-windows-config.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@RichardvanNuland - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@mjcaparas - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by mjcaparas** [comment]
Topics will be updated when support becomes available. No timeline status can be shared prior to that.
