### ISSUE TITLE
Improved Logging advice

### ISSUE THREAD

**Issue by ceaton001** [MicrosoftDocs/windows-itpro-docs#5023]
The information in the event logging section could be improved as follows -

In Table 1, the Surface Dock Firmware Update log is not created unless you specify a log location in the Msiexec command. So the location field should say "none unless specified" and the notes field should say something like "To create a log file, specify the path in the Msiexec command. For example, append /l*v %windir%\logs\ SurfaceDockFWI.log".

In Table 2, make it clear that the events are logged in Windows Logs\Application.

**Comment by mypil** [comment]
@ceaton001 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by ceaton001** [comment]
Hi!

Sorry, I thought that info would have carried through to the Github site.
The page is https://docs.microsoft.com/en-us/surface/surface-dock-firmware-update

Regards,
Christine

**Comment by mypil** [comment]
@ceaton001 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@ceaton001  - From our understanding, the issue has been resolved based on the merged commit 
https://github.com/MicrosoftDocs/windows-itpro-docs/commit/18ca6736c666f69ba9d78b4a36f69bcf1589f56a but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
