### ISSUE TITLE
Logo URI Path

### ISSUE THREAD

**Issue by mellolr1** [MicrosoftDocs/windows-itpro-docs#5027]
The path "ms-appx:///Assets/MicrosoftEdgeSquare150x150.png" is not working on Surface Hub S2. It causes the tile to not initialize and event log ID 17 in Microsoft-Windows-ShellCommon-StartLayoutPopulation%4Operational with parameter is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69882e91-6bef-d524-7059-20ba67129f4e
* Version Independent ID: ee0f2eb3-97da-4306-5cd1-2b6ae1858ed9
* Content: [Configure Surface Hub Start menu](https://docs.microsoft.com/en-us/surface-hub/surface-hub-start-menu#feedback)
* Content Source: [devices/surface-hub/surface-hub-start-menu.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/surface-hub-start-menu.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by illfated** [comment]
Hmm, if you intended to close this issue, what is the reason for closing it (just out of curiosity)?

**Comment by mellolr1** [comment]
I screwed up… I was using ms-appdata:/// instead of ms-appx:///
