### ISSUE TITLE
Pages removed or moved

### ISSUE THREAD

**Issue by Anton2020** [MicrosoftDocs/windows-itpro-docs#5033]
http://schemas.microsoft.com/Start/2014/TaskbarLayout and http://schemas.microsoft.com/Start give the following error:
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
Do you happen to know the new locations? Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140f038c-e307-78f0-5165-309e0cf34ca5
* Version Independent ID: b1011259-ee05-21a4-5308-aabc8b0dd74b
* Content: [Configure Windows 10 taskbar (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/configure-windows-10-taskbar#feedback)
* Content Source: [windows/configuration/configure-windows-10-taskbar.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/configure-windows-10-taskbar.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
@nenonix : Is this related to the news you linked to me sometime earlier this year, regarding templates and a hijacked Microsoft site?

**Comment by e0i** [comment]
Hello, @Anton2020 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.
