### ISSUE TITLE
Export-StartLayout -UseDesktopApplicationID

### ISSUE THREAD

**Issue by tylerswire** [MicrosoftDocs/windows-itpro-docs#5034]
Yesterday I came across an update which I’d not been aware of previously, (**-UseDesktopApplicationID**) and am wondering if 1) what the change is for 2) does it pertain to >1809? 3) if so, the page content might should be updated.

https://docs.microsoft.com/en-us/windows/configuration/customize-and-export-start-layout#export-the-start-layout

![export](https://user-images.githubusercontent.com/39066915/65604974-f10b7500-df6d-11e9-9ab9-60ae9da6bc32.jpg)

**Comment by j0rt3g4** [comment]
Hello, @e0i  Please contact the author about this. Thank you.
I'd suggest that this should be valid for 1809+ but I'm not sure.

**Comment by tylerswire** [comment]
Reference https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5133
