### ISSUE TITLE
Step 4 of Use Group Policy to disable local list merging is incorrect

### ISSUE THREAD

**Issue by douglasos** [MicrosoftDocs/windows-itpro-docs#5035]
The instructions are suggesting to set the option to Enabled.
If the desired result is to disable local merge, this option should be set to Disabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcbd9d0e-c614-6a48-e70d-4daedcb9a670
* Version Independent ID: e2c5a8e5-9beb-6e3f-a566-6b134dd1885f
* Content: [Configure local overrides for Windows Defender AV settings](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-local-policy-overrides-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-local-policy-overrides-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/configure-local-policy-overrides-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@douglasos 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
