### ISSUE TITLE
Misleading information

### ISSUE THREAD

**Issue by onkeljoz** [MicrosoftDocs/windows-itpro-docs#5037]
This article seems to refer to System Center Configuration Manager, but this isn't mentioned anywhere in the title or the navigation tree.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad932bb-d57d-1ce9-3cd9-2f6ad13ef756
* Version Independent ID: 1732b30e-aef0-0ba3-3d35-15c3ed9c6593
* Content: [Best practices - deploy feature updates for user-initiated installations](https://docs.microsoft.com/en-us/windows/deployment/update/feature-update-user-install#feedback)
* Content Source: [windows/deployment/update/feature-update-user-install.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/feature-update-user-install.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
I've just changed the authorship on this article to reflect the correct author. 

This seems like a minor issue. The very first paragraph talks about using Configuration Manager. Other articles also take the same approach. See https://docs.microsoft.com/en-us/windows/deployment/update/feature-update-mission-critical - I wouldn't call this misleading it's only a bit imprecise in description or title. The meta data on the topic probably should include System Center Configuration Manger, but I don't think it's necessary to rework the topic title (and all the other topics in this node)

**Comment by onkeljoz** [comment]
Thanks Greg,

 

> The very first paragraph talks about using Configuration Manager.

Yes, but this doesn’t mean that the whole article is about CM, right?

 

> I wouldn't call this misleading

At least it misled me…

 

> The meta data on the topic probably should include System Center Configuration Manger

Yes, why not „Applies to: Windows 10, System Center Configuration Manger“?

 

Kind regards

Johannes Zwirner

 

Von: Greg Lindsay <notifications@github.com> 
Gesendet: Mittwoch, 25. September 2019 19:26
An: MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>
Cc: Johannes Zwirner <zwirner@netzabteilung.de>; Author <author@noreply.github.com>
Betreff: Re: [MicrosoftDocs/windows-itpro-docs] Misleading information (#5037)

 

I've just changed the authorship on this article to reflect the correct author.

This seems like a minor issue. The very first paragraph talks about using Configuration Manager. Other articles also take the same approach. See https://docs.microsoft.com/en-us/windows/deployment/update/feature-update-mission-critical - I wouldn't call this misleading it's only a bit imprecise in description or title. The meta data on the topic probably should include System Center Configuration Manger, but I don't think it's necessary to rework the topic title (and all the other topics in this node)

**Comment by e0i** [comment]
Hello @onkeljoz  ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
