### ISSUE TITLE
Server 2012 Support

### ISSUE THREAD

**Issue by johnjohnjohn87** [MicrosoftDocs/windows-itpro-docs#5038]
Is Server 2012 supported? I see that 2008 R2 and 2012 R2 are, but didn't see 2012 explicitly listed in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4ed2b3-0390-4d53-2450-14995ee8b0b0
* Version Independent ID: 91b5bb3e-55d4-6a8e-c16d-094f15c28ee7
* Content: [Onboard servers to the Microsoft Defender ATP service](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Only the ones listed are supported.
