### ISSUE TITLE
如果文件的状态为“已删除”，应该怎么办呢？

### ISSUE THREAD

**Issue by VVVinegar** [MicrosoftDocs/windows-itpro-docs#5041]
一些在u盘中的重要文件，被检测出特洛伊木马，警告级别为严重，状态为已删除，并且标注“此威胁或应用已被允许，将来不会修正”，应该怎么办呢？这些文件比较重要。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: de416fda-04fb-6780-6675-020fdc2426ba
* Version Independent ID: ede7f3c1-ba3a-e331-80d8-c992b3d7f9a4
* Content: [在 Windows Defender AV 中还原隔离的文件](https://docs.microsoft.com/zh-cn/windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
如果出现病毒/木马/恶意软件感染，则应在本地寻求帮助。 确保仅在具有良好防病毒软件的干净，隔离的计算机上访问这些文件，而不必担心会传播感染。
(In case of a virus / Trojan / malware infection, you should seek help locally. Make sure to only access those files on an clean, isolated computer with good anti-virus software where you do not risk spreading the infection.)

**Comment by VVVinegar** [comment]
Thank you! But it had told me that the files had been deleted, can i still find them after establishing a secure environment?

**Comment by illfated** [comment]
Not sure if they are 100% deleted or if they are locked inside some vault or hidden files. If you want to try to restore files, you should definitely shut down the computer in question, before any more changes are done to it, then ask for help for someone to perform data retrieval on either the hard drive or the entire computer (depending on type of device), using a separate OS (Linux or something else than the original Windows OS) and also have access to repair, scan and file recovery tools for your situation. This is very much a hands-on operation, so you need help from local expertise.

**Comment by VVVinegar** [comment]
All right, it sounds not easy to do. Thank you!

**Comment by illfated** [comment]
Correct, the file data and drive(s) in question should be treated with respect and great care. I can only wish you good luck in recovering your data.

**Comment by VVVinegar** [comment]
I will and I'll close the question, thank u again.
