### ISSUE TITLE
API methods for incidents

### ISSUE THREAD

**Issue by tessem** [MicrosoftDocs/windows-itpro-docs#5042]
So, listing and editing of Alerts is possible. But what about Incidents? How to list/fetch them, how to close them via API ?

Regards, 
TT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05bf8ffd-adfb-4de7-872e-237e644dba3e
* Version Independent ID: 5be0b95f-ed9c-c424-64d2-8617ebbe5bf2
* Content: [List alerts API](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/get-alerts)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/get-alerts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/get-alerts.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Hi tessem, it is not supported at this time.
