### ISSUE TITLE
Surface Dock Firmware Update log

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/windows-itpro-docs#5046]
Why do the four characters "/l*v" appear under LOCATION in Table 1? Are they part of a location?
Why do I have no SurfaceDockFWI.log anywhere on my Surface after updating the dock firmware?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7b356e-3dbd-7f59-845e-a92e05865a52
* Version Independent ID: 711c5497-373f-662c-7fae-ba60f046e50c
* Content: [Microsoft Surface Dock Firmware Update](https://docs.microsoft.com/en-us/surface/surface-dock-firmware-update)
* Content Source: [devices/surface/surface-dock-firmware-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/surface-dock-firmware-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by ceaton001** [comment]
The "/l*v" [plus a path] should be appended to the msiexec command to create a log file, it's not created by default. I have already logged a doc bug for this.

**Comment by gchirlin** [comment]
There are additional Event ID values not listed in Table 2 of this article. Some of them include:
2007: Firmware update finished
2008: BEGIN dock telemetry
2011: END dock telemetry.

Although the description for the events (in the Event Viewer for Level: Information, Source: SurfaceDockFwUpdate) begins with "cannot be found", the interpretation is provided at the end of the General tab text.

**Comment by gchirlin** [comment]
Although there are no Event error messages, and Event 2007 says that the Firmware update finished. hr=0, the registry does not indicate the update is complete. This is after several power cycles and two days. I am using a Surface 6 with Windows 10 Pro v1903. The registry entry for Component10CurrentFwVersion is correct (and matches that of Component10OfferFwVersion). However, the registry entry for Component20CurrentFwVersion is incorrect: 0x0499a170, not matching the (correct) Component20OfferFwVersion of 0x04a1d570 per the table in this article. It seems to have stalled without actually making the update (or at least updating the registry). Any advice?

**Comment by e0i** [comment]
Hello, @BR77BE It is to our understanding that the PR #5093 addresses this issue. The PR has been created in response to same feedback provided by @ceaton001.

Additional feedback provided by @gchirlin is under investigation and content updates will provided as necessary.

Thank you all for providing valuable feedback and engaging with the community. Much appreciated.

**Comment by Justin-DynamicD** [comment]
There are additional error codes missing (beyond those identified above)

2006: Failed to send offer/payload pairs

**Comment by Denjiki** [comment]
@gchirlin had the same exact issue as I had. According to the setupapi.dev.log file, the firmware updated successfully. I also show Event ID 2007 in Event Viewer. However, the registry shows Component20CurrentFWVersion is 0x04915a70 (76634736) and not the same as the OfferFwVersion, which is 0x04a1d570. For what it's worth, my Component10CurrentFwVersion is correct & the same as the OfferFwVersion as well. So exactly as @gchirlin described. I am using a Surface Laptop 1.

**Comment by MateuszZiolek** [comment]
> @gchirlin had the same exact issue as I had. According to the setupapi.dev.log file, the firmware updated successfully. I also show Event ID 2007 in Event Viewer. However, the registry shows Component20CurrentFWVersion is 0x04915a70 (76634736) and not the same as the OfferFwVersion, which is 0x04a1d570. For what it's worth, my Component10CurrentFwVersion is correct & the same as the OfferFwVersion as well. So exactly as @gchirlin described. I am using a Surface Laptop 1.

Same on Surface Book 1

**Comment by e0i** [comment]
@gchirlin @Justin-DynamicD The missing error codes that you have mentioned are now part of the documentation.
