### ISSUE TITLE
Unable to import fields

### ISSUE THREAD

**Issue by corsen55** [MicrosoftDocs/windows-itpro-docs#5049]
Only certain fields are available for importing bulk lists.  For example, the field rbacGroupNames are not available when using the CSV to import.  This is important if you want to assign the indicators to a specific group.  Maybe this will be available in the public release?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef05866-969b-5c37-8a49-f316d4165101
* Version Independent ID: 9c81d2d1-e216-1cef-c511-9daacde024b4
* Content: [Indicator resource type](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/ti-indicator#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/ti-indicator.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/ti-indicator.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@mjcaparas @levinec Would you be able to provide clarifications for this question? Authoritative input might be needed. Thanks.

**Comment by mjcaparas** [comment]
Hi, checking with team.

**Comment by mjcaparas** [comment]
Response from the team indicates that it's not supported.

**Comment by corsen55** [comment]
Will this be a future release?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by illfated** [comment]
@corsen55 : I recommend using the Feedback Hub to influence the developers in adding your suggestion to their future feature list.
