### ISSUE TITLE
Get started link is broken with Page 404 error

### ISSUE THREAD

**Issue by bstockbrugger** [MicrosoftDocs/windows-itpro-docs#5053]
Get started link is broken with Page 404 error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593263a4-3a35-4547-8504-9d0bb89585a8
* Version Independent ID: b38a2662-21a8-5083-7ebd-61c5cc260849
* Content: [Evaluate Microsoft Defender Advanced Threat Protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/evaluate-atp#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/evaluate-atp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/evaluate-atp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for bringing this to our attention @bstockbrugger, much appreciated. 

I will forward this to the Windows content writing team for correction. The link should go to the [Microsoft Defender Advanced Threat Protection](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection) topic (*which is also available in the TOC on the left side*). Please continue to share your suggestions or ideas to help improve the quality of the technical documentation. Thanks for being part of the Microsoft Docs community!

**Comment by illfated** [comment]
Oh. I see. Another one of these. There is an index section named "Get started", but it does not exist as a link or page. The link content needs to be replaced with one of the existing pages. See for example the links on the left side of the page when you go to https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/whats-new-in-microsoft-defender-atp .

**Comment by jvsam** [comment]
@illfated yes, you are right. You have also updated one of the links on the topic section of the main MDATP overview content page. In this case, the link should go to the main overview page of MDATP, that contains the summary of features and the recommended configuration steps. Do you want to correct the link?

**Comment by illfated** [comment]
Sure, I can do that. BTW, thank you for providing the recommended target link, I was a bit uncertain which one to pick. Also, would it be better to rename the link as well, to something like "Microsoft Defender Advanced Threat Protection overview" or "Microsoft Defender Advanced Threat Protection main page" instead of "Get started with Microsoft Defender Advanced Threat Protection" ?

**Comment by jvsam** [comment]
I personally agree with the proposed changes. Thank you again @illfated.

**Comment by jvsam** [comment]
Hi again @bstockbrugger, we'd like to inform you that the pull request (See PR #5073) that *fixes the broken link* has been approved and merged. The update will be displayed here at docs.microsoft.com in the next scheduled publishing run. Thank you again for your feedback and for being part of the Microsoft Docs community!
