### ISSUE TITLE
Surface Dock Updater does not update Component20 (display port firmware)

### ISSUE THREAD

**Issue by gchirlin** [MicrosoftDocs/windows-itpro-docs#5054]
[Dock Update Registry.pdf](https://github.com/MicrosoftDocs/windows-itpro-docs/files/3663044/Dock.Update.Registry.pdf)
[Dock Update Event Viewer.pdf](https://github.com/MicrosoftDocs/windows-itpro-docs/files/3663051/Dock.Update.Event.Viewer.pdf)

I am using a Surface Pro 6 with Windows 10 Pro v1903 and the latest dock.  After running the new Microsoft Surface Dock Updater software from https://docs.microsoft.com/en-us/surface/surface-dock-firmware-update, the Event Viewer shows several entries including 2001, 2004, 2004 again, 2007 (Firmware Update completed), 2008 (BEGIN dock telemetry), and 2011 (END dock telemetry). All are informational. Interestingly, the Events 2004 indicate the component version that was provided during update, and for Component20 the value is 77177200 in Event 2004 (see attached pdf). Likewise, the registry entry for Component20CurrentFwVersion is 0x0499a170 (77177200), which matches the Event info (See attached pdf). Significantly, this value does NOT match the registry value shown in the cited article Versions Reference (0x04a1d570 (77714800)) that would signal a successful update of the display port firmware. This suggests that the updater did what it said it was going to do in the Event Viewer, but that is not what it should have done according to the Microsoft article. Another curiosity: that correct Component20 update value of 0x04a1d570 (7714800) that should have appeared in registry entry Component20CurrentFwVersion does indeed appear in registry entry Component20OfferFwVersion. Is the update failed? Any advice?

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
I am sorry that you are experiencing problems in running Surface Dock Firmware update @gchirlin. We believe this will be best addressed by contacting [Support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10). You can also check the [Troubleshooting tips](https://docs.microsoft.com/surface/surface-dock-firmware-update#troubleshooting-tips) related to the Microsoft Surface Dock firmware update.

Other support resources include the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where community members can learn, collaborate, and share experiences about Microsoft products. You can ask your question and start a conversation with other users, experts and also Microsoft engineers. 

We hope your issue will get resolved soon. Thanks for being part of the Microsoft Docs community!

**Comment by gchirlin** [comment]
Lo and behold, I just checked the registry and the update has successfully completed. It took several days, but all is now well based on the new value of Component20CurrentFwVersion (now 0x04a1d570 (77714800)).

**Comment by jvsam** [comment]
Awesome, thanks for letting us know @gchirlin! 

Thanks again for being part of the Microsoft Docs community!

**Comment by weymankwong** [comment]
I'm having the exact same issue. Do you regularly disconnect your dock? I'm wondering if disconnecting the dock and/or power cycling the Surface and/or the Dock is what got it to trigger. Might be useful info to the next person that stumbles upon this thread.

**Comment by illfated** [comment]
Sounds like it should be noted that a device & dock power cycle + dock disconnect & reconnect might be required to trigger the update.

**Comment by Corben78** [comment]
Having the same issue, this is was did the trick for me:
Checking the event log (run: eventvwr), below Windows Protocols: not Application but **System** and not entering SurfaceDockFwUpdate but **selecting** it from the drop down.
(https://docs.microsoft.com/en-us/surface/surface-dock-firmware-update describes to filter below Applications and to enter SurfaceDockFwUpdate)
After reconnecting the dock to my Surface Pro 3, it showed up several 200x events, e.g. 2001 (starting firmware update) and twice 2004 (checking for Component10CurrentFwVersion and Component20CurrentFwVersion), 2007 stated firmware update finished, but Component20CurrentFwVersion did not match Component20OfferFwVersion. 2008 began telemetry retrieval, followed by 2012, which not described on the link above:
```
Dock telemetry message from firmware. 

SurfaceDockFwUpdate FIRMWARE RECORD: 
TelemetryEvent : 1
        HostID : 0
      ConfigID : 0
         Data1 : 4915a70
         Data2 : 4a1d570
     Timestamp : 1093322
    SequenceID : 1d
 Dock UniqueID : <someid>
```
This was the not updated Component 20 firmware.  
But that was followed by a 2011 event: Dock firmware end of telemetry.  
Checking the registry still showed, that Component 20 (Display-port firmware) still wasn't updated.  
I tried to power cycle the Surface Dock, the Surface Pro 3, but still, the Component 20 firmware wasn't updated. Finally [this link](https://www.thurrott.com/mobile/microsoft-surface/216991/microsoft-issues-new-surface-dock-firmware-update-tool) gave the correct hint: Unplug the Dock from your Surface, but do **not** unplug it from power. Maybe unplug Ethernet as well, and if you Ethernet port LED still flashes, then the update is being applied. This takes a few minutes, but when it stops flashing the Display-port firmware got updated as well.

I needed this update, to mitigate the issue, as with Linux my new Surface Pro 7 the two monitors that are connected via Display-port to HDMI adapters where constantly flickering. It happened to my Surface Pro 3 as well, but less than once a day. Before the Display-port firmware upgrade it was happening like once per minute, with the update it's way less (but still not gone, and not happening on Windows). The real solution was to upgrade to a Surface Dock 2 with USB-C to HDMI adapters.

**Comment by KnoxCameron** [comment]
Thanks everyone, this fixed the issue for me! Key thing was to disconnect the dock from the Surface laptop, but leave it connected to power, and give it some time to apply the update internally. When I reconnected it, it then reported the updated version number for Component20 (4a1d570 instead of 499a170 which it had been stuck on).

**Comment by Bun-Bun** [comment]
> Finally [this link](https://www.thurrott.com/mobile/microsoft-surface/216991/microsoft-issues-new-surface-dock-firmware-update-tool) gave the correct hint: Unplug the Dock from your Surface, but do **not** unplug it from power. Maybe unplug Ethernet as well, and if your Ethernet port LED still flashes, then the update is being applied. This takes a few minutes, but when it stops flashing the Display-port firmware got updated as well.

OMG I am saying so many curse words right now. Have a user whose new studio laptop is causing flickering on their monitors so wanted to try this update. No where in the documentation does it explain that the MCU update happens while connected and that the displayport update happens while disconnected. Terrible design aside, the documentation needs to be improved. 

Thanks for this info.
