### ISSUE TITLE
Cleanly separate user from IT docs

### ISSUE THREAD

**Issue by grbury** [MicrosoftDocs/windows-itpro-docs#5065]
The upper topics (guides) are primarily user focused, and the bottom ones are more IT and deployment focused.  Perhaps move the "Deploy HoloLens in a commercial environment" to the lower section for a clean divide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb70c2a8-dcb0-2425-8d72-da180d05c2e1
* Version Independent ID: 7504c800-b203-0d18-9049-98005dd9a8b5
* Content: [Microsoft HoloLens (HoloLens)](https://docs.microsoft.com/en-us/HOLOLENS/)
* Content Source: [devices/hololens/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/index.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for your feedback @grbury. I will forward this to the Windows content writing team for review. Please continue to share your suggestions or ideas to help improve the quality of the technical documentation. Thanks for being part of the Microsoft Docs community!

**Comment by illfated** [comment]
I can create a PR to make that change, but I also had a feeling that the "Deploy HoloLens in a commercial environment" is less of a Quick Reference and more of a Guide document. Oh well. I presume it will be a lot easier to get a direct response regarding that view in a PR compared to this issue ticket.

**Comment by scooley** [comment]
Thoughts on pivoting the other direction?  I think I'll make the quick ref more user focused instead.  As always, happy to adjust with feedback :)

**Comment by illfated** [comment]
The document page has changed, so I could not move forward with my already running Pull Request (too many conflicting lines). 

By all means, feel free to suggest any new changes based on the new content (which I was unable to change).

**Comment by jvsam** [comment]
The revised quick reference topics are better, in my opinion. Makes more sense rather than separating topics based on who the intended audience is. Thank you @scooley.

**Comment by jvsam** [comment]
@grbury there have been improvements done on this doc. I hope you're ok with the updates. We will now close this issue, but feel free to re-open or create another issue through the doc's *feedback feature*, if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
