### ISSUE TITLE
Scantype parameter info

### ISSUE THREAD

**Issue by KimRechnagel** [MicrosoftDocs/windows-itpro-docs#5070]
How come you don't include the scan types in this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f25443de-57f4-c8f2-fecb-f58714467894
* Version Independent ID: 1d783d00-ae0d-3eea-9a32-b42dd32e73c2
* Content: [Use the command line to manage Windows Defender Antivirus](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/command-line-arguments-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/command-line-arguments-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/command-line-arguments-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@KimRechnagel - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by KimRechnagel** [comment]
Thank you very much for the swift response and action. Much appreciated.

**Comment by Dansimp** [comment]
Looking into it

**Comment by Dansimp** [comment]
Hi @KimRechnagel, to clarify, are you looking for the different values accepted in:
-Scan [-ScanType **#**]?

We can update the docs with that info, apologies it was missing.

- 0 Default, according to your configuration
- 1 Quick scan
- 2 Full system scan
- 3 File and directory custom scan

**Comment by RichardMeadowsTC** [comment]
I am struggling with this also. Based on the docs, I figured this would run a full scan
\MpCmdRun.exe -Scan 2

Expect:  Full scan it ran.
Actual: Bad Command line - Command Line - Option should start with '-' or '/' 2

CmdTool: Failed with hr = 0x80070667. Check C:\Users\v-ricmea\AppData\Local\Temp\MpCmdRun.log for more information
CmdTool: Invalid command line argument

**Comment by Dansimp** [comment]
Yes, good call. I updated the topic with a short example and added the "-" characters before the values in the table.

**Comment by denisebmsft** [comment]
Noticed the table is incorrectly formatted. Fixed that today. Hoping changes render on the live site later today or tomorrow. I think we can close this issue now.
