### ISSUE TITLE
Intune Deployment

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/windows-itpro-docs#5072]
Hi, the section for SCCM does also apply for Intune, or is possible to still deploy this updates from Windows Update as additional updates? Is need to reinstall the tool every time when new version is available or it can do also automatically itself? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7b356e-3dbd-7f59-845e-a92e05865a52
* Version Independent ID: 711c5497-373f-662c-7fae-ba60f046e50c
* Content: [Microsoft Surface Dock Firmware Update](https://docs.microsoft.com/en-us/surface/surface-dock-firmware-update)
* Content Source: [devices/surface/surface-dock-firmware-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-dock-firmware-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@Kazzan - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Hi @Kazzan 

I would think that basically this update is integrated as a windows update download as long as the device is connected to a windows 10 machine.

https://docs.microsoft.com/en-us/surface/surface-dock-firmware-update

Also, I've added this link into the documentation
https://support.microsoft.com/en-us/help/4023478/surface-update-your-surface-dock

**Comment by j0rt3g4** [comment]
PR #5098

**Comment by Kazzan** [comment]
Hi @j0rt3g4, it seems to be still little bit unclear.

The KB mention like "to get automatic updates for Dock (firmware) we need to download and install the tool".
 
But the tool page say, that only new version of tool supports new firmware versions like "To update a Surface Dock to the latest firmware, you must use the latest version of Surface Dock Firmware Update."

But nowhere is stated if updates of this tool are on Windows Update itself. So it is like one-time install and it magically run, update itself and update firmware or we need to distribute each new version with Intune or SCCM?

Thanks for clarification of this process.

**Comment by j0rt3g4** [comment]
KB says go to download [Download Surface tools for IT](https://www.microsoft.com/download/details.aspx?id=46703) and then when you execute the tool that you select the latest. Download the newest version of the Surface tool to get the newest version of the firmware.

You're right in the fact that nowhere says that you can use Windows Update itself to get the updates, but in nowhere says as well that "you can't," @mypil can you please add the author so we can get a line about this?.

Related to **SCCM and Intune**, not sure because if it's a windows update, you can do the push it on WSUS. Let's wait for the author's comments, and at the end of it's a windows update, then you can distribute it like you usually would do over SCCM, but I don't think you could use Intune for this.

**Comment by mypil** [comment]
@Dansimp - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by Dansimp** [comment]
Following up with engineering team

**Comment by j0rt3g4** [comment]
Hello @Dansimp  Any update on this?

**Comment by j0rt3g4** [comment]
PR #5098  has been substituted for #5328 which contains PR  #4984  +  old #5098
Suggestions are done by @JohanFreelancer9 also applied to this.

 @jvsam It's done.

**Comment by mypil** [comment]
@Kazzan - From our understanding, the issue has been resolved based on the merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/8bf2645000efd6ec6f1fae970d2d523b36603507 but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
