### ISSUE TITLE
Where is user centric

### ISSUE THREAD

**Issue by NFCES** [MicrosoftDocs/windows-itpro-docs#5075]
AutoPilot is great, but lack a User Centric option. Not all environments are based on devices. One example with AutoPilot is the ability to set up the user as a local Administrator of their device prior to delivering it to the user. Azure does give an option to makes the user a local administrator but that is across all devices. Not sure that the CTO would be happy to know that the Help Desk staff has full administrative rights to his/her device.

With the current AutoPilot model, we have to manually add devices to a security group that the AutoPilot (Local Administrator) is assigned to, then assign that device to the user prior to delivery so that only that user can Azure AD join and Intune enroll that device. The way it should work is that AutoPilot is not even involved. You should be able to select either a user or a device and select which user has local administrator rights to that device and/or from the device which user/s should be listed as a local administrator.

Also, the current AutoPilot design does not allow more than one profile to be assigned to a security group. Well, is does but conflicts will occur. So AutoPilot does not have any logic bulletin to handle multiple profiles per security group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20fef169-ec92-ae95-38fd-44b2f9d9c98f
* Version Independent ID: c96cf391-2e64-155b-6980-aeb22c7eaf1c
* Content: [Windows Autopilot what's new](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-whats-new#feedback)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-whats-new.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/windows-autopilot-whats-new.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@NFCES - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via **[Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
