### ISSUE TITLE
Autopilot TPM Requirement

### ISSUE THREAD

**Issue by sringler** [MicrosoftDocs/windows-itpro-docs#5076]
Autopilot only requires TPM 2.0 and UEFI firmware in Whiteglove and Self-Deploying Scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 535e3b58-7e16-f593-00a5-f779d4284a21
* Version Independent ID: e7944e4e-3879-4830-45a5-20946df0fb7e
* Content: [TPM recommendations (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/tpm-recommendations#feedback)
* Content Source: [windows/security/information-protection/tpm/tpm-recommendations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/tpm/tpm-recommendations.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@sringler - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@sringler  - From our understanding, the issue has been resolved based on the `merged commit d6be289` but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
