### ISSUE TITLE
1903 template is out

### ISSUE THREAD

**Issue by cconrado** [MicrosoftDocs/windows-itpro-docs#5078]
There's a note saying that the 1903 template isnt out yet but it is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
OK, so about 5 weeks ago, the following download was published:

**Administrative Templates (.admx) for Windows 10 May 2019 Update (1903) v3.0**
- https://www.microsoft.com/en-us/download/details.aspx?id=58495

I can make a PR for removing the note, but I would also like to provide an update to the ℹ️ **Important** note further down as well, with the link (as above) and the folder path to the installed ADMX templates. I can only presume it needs to look something like this:

>[!IMPORTANT]
>If you do not see the policy, it may be because you don’t have the ADMX installed for Windows 10, version 1803 or version 1809. To fix the issue, follow these steps:        
>   1. Download:  
>   1803 -->[Administrative Templates (.admx) for Windows 10 April 2018 Update (1803)](https://www.microsoft.com/download/details.aspx?id=56880) or  
>   1809 --> [Administrative Templates for Windows 10 October 2018 Update (1809)](https://www.microsoft.com/download/details.aspx?id=57576) or
>   1903 --> [Administrative Templates for Windows 10 May 2019 Update (1903)](https://www.microsoft.com/en-us/download/details.aspx?id=58495)
>   2. Install the package on the Primary Domain Controller (PDC).
>   3. Navigate, depending on the version to the folder:
>   1803 --> **C:\Program Files (x86)\Microsoft Group Policy\Windows 10 April 2018 Update (1803) v2**, or  
>   1809 --> **C:\Program Files (x86)\Microsoft Group Policy\Windows 10 October 2018 Update (1809) v2** or
>   1903 --> **C:\Program Files (x86)\Microsoft Group Policy\Windows 10  May 2019 Update (1903) v3**
>   4. Copy policy definitions folder to **C:\Windows\SYSVOL\domain\Policies** .
>   5. Restart the Primary Domain Controller for the policy to be available.
>   This procedure will work for any future version as well.

**Comment by mypil** [comment]
@cconrado - Thank you for submitting this feedback. PR #5086 has been created to fix and close this issue. 

@illfated - Thank you for creating the PR. 


We truly appreciate your contribution to make the docs better!  Keep it coming!
