### ISSUE TITLE
Automated enrollment for OnPrem AD? 

### ISSUE THREAD

**Issue by almertes** [MicrosoftDocs/windows-itpro-docs#5079]
Would like to automate the enrollment of the Surface Hub 2 device in to Intune.  The manual steps to do so work: 
•	Click settings and log in as admin (domain)
•	Click surface hub device account management
•	Click device management
•	Click + device management
•	Enter an email address
•	Login as admin (domain)
•	Done

If it’s not part of a PPKG file but needs to be a powershell script or something that the PPKG runs that is acceptable. 
Can this be done? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cea2c3b-a954-cd64-de40-388c6b58974c
* Version Independent ID: 22367150-b368-3917-cc6a-3c55d028f451
* Content: [Manage Surface Hub 2S with Intune](https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-manage-intune#feedback)
* Content Source: [devices/surface-hub/surface-hub-2s-manage-intune.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/surface-hub-2s-manage-intune.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@almertes - thanks for the heads up and suggestion.
@CoveMiner - John, can you take a look at this and incorporate as part of your updates?

**Comment by mypil** [comment]
@robmazz @CoveMiner - We would like to follow up. Do you have any updates on this?

Thank you.

**Comment by greg-lindsay** [comment]
Have you seen https://docs.microsoft.com/en-us/intune/enrollment/windows-enrollment-methods ?

It should not be necessary to use a Windows PowerShell script since there are other automated methods. However, a script is always an option. You can do just about anything with a PowerShell script.

Does this answer the question? Are you looking to add to the documentation here?

**Comment by CoveMiner** [comment]
Thanks Greg. I've added that link to devices/surface-hub/surface-hub-2s-manage-intune.md. Should go live tomorrow.

**Comment by mypil** [comment]
@almertes - From our understanding, the issue has been resolved based on the merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/8ed471ce091a722fe543884c5f236586a7dbc0f5#diff-a18cbba172f8d398d7231a19118d4b49. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
