### ISSUE TITLE
What about huge ram?

### ISSUE THREAD

**Issue by trevorl3124** [MicrosoftDocs/windows-itpro-docs#5087]
I read and understood everything in this article, my older computer had four gigs of RAM and I put the page file at 6144 and 18 432. I built two new machines to do my stuff today, one has sixTeen Gigs of RAM and the other has 32.  According to those numbers my minimum should be a 24576  and max out at 73 728. Show me a note through github and let me know what you think. Because I just don’t know. Thanks Trevor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b0674a-7bd1-6f30-9e7a-d258ab559138
* Version Independent ID: c1d5e93a-42cb-d29d-bb91-9c38d3a8647f
* Content: [How to determine the appropriate page file size for 64-bit versions of Windows](https://docs.microsoft.com/en-us/windows/client-management/determine-appropriate-page-file-size#feedback)
* Content Source: [windows/client-management/determine-appropriate-page-file-size.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/determine-appropriate-page-file-size.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by illfated** [comment]
@Deland-Han : Are you available for commenting on this question, either to clarify or refer to any specific part of the documentation?

**Comment by trevorl3124** [comment]
I guess I’m asking, do you always follow the equation of physical ram x 1.5? Is there a  point where the largest page file that the computer can utilize efficiently is say “16384”, any larger and the machine would have to work to hard. Losing the processor power required for the larger PF wouldn’t be any more beneficial a gsin than a smaller one

**Comment by e0i** [comment]
@trevorl3124 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
