### ISSUE TITLE
Group Policy Editor doesn't allow setting numerical values for policies...

### ISSUE THREAD

**Issue by Nicholas-Steel** [MicrosoftDocs/windows-itpro-docs#5088]
I can only choose "Not Configured", "Enabled" and "Disabled". It is not possible to configure "Send file samples when further analysis is required" to a value of 0, 1, 2 or 3.

Windows 10 Pro.

(I'd like it if ATP can be made to always prompt me with a choice to make an exception after it successfully blocks something)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bd0fe29-5db5-b752-5bcf-5ac2581baa9a
* Version Independent ID: 52b8d4ca-54ea-7345-12b0-df4fdf633083
* Content: [Enable Block at First Sight to detect malware in seconds](https://docs.microsoft.com/en-au/windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @Nicholas-Steel ,
You need to set its state to "Enabled", then you can select the value from the drop down list:
![5088](https://user-images.githubusercontent.com/48041687/69324507-6a6fcd00-0c6a-11ea-8a3c-8a1b52358492.png)

Thank you

**Comment by Nicholas-Steel** [comment]
Derp, I don't know how I missed that. Thank you.
