### ISSUE TITLE
Certutil command wrong

### ISSUE THREAD

**Issue by Digiroka** [MicrosoftDocs/windows-itpro-docs#5089]
The certutil command below is incorrect, it should use commas instead of spaces:
 certutil -dsTemplate WHFBAuthentication msPKI-Private-Key-Flag +CTPRIVATEKEY_FLAG_HELLO_LOGON_KEY

THe correct command is below:
certutil -dsTemplate WHFBAuthentication,msPKI-Private-Key-Flag,+CTPRIVATEKEY_FLAG_HELLO_LOGON_KEY

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd063d0c-8739-15bd-4f16-11b893029845
* Version Independent ID: cd3679fe-dd9c-44f9-04ed-c772a47ca4e4
* Content: [Configuring Hybrid Windows Hello for Business - Public Key Infrastructure (PKI)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
Wish I had a relevant scenario to test your statement in. Using internet search engines instead, nobody else have mentioned this before. I find that more than a little bit strange. The concept of separating command parameters or command line arguments with commas (especially when not mentioned in the program's own internal documentation) looks very, very unusual to me.

**Comment by Digiroka** [comment]
I agree, but the specified command resulted in a ‘too many arguments’ response, which yielded this thread - https://social.technet.microsoft.com/Forums/windowsserver/en-US/847c13d5-a32e-4799-bb83-2f8ead98a069/certutil-too-many-arguments?forum=winserversecurity

They aren’t command parameters, it’s a string.

**Comment by illfated** [comment]
Very good. Nice. That is actually a very useful reference for your statement. I feel less urged to burden myself with getting my hands on the proper scenario to test this (although I do suggest that anyone who has got access to a relevant scenario should test it).

I will go as far as to say that the document needs to be updated to include those findings, although I would like to have a confirmation from one of the MS Docs team members before I open a PR to do so.

**Comment by Digiroka** [comment]
Again, I agree with your comments.
If this issue could be confirmed or rejected by a product team member it would be useful.

**Comment by illfated** [comment]
Oh well. I will go ahead and create the PR anyway. I presume this topic will attract feedback faster that way.

**Comment by Digiroka** [comment]
Thanks for this, I only tested the versions I posted I’m afraid.
