### ISSUE TITLE
Advanced hunting

### ISSUE THREAD

**Issue by JakKAaj** [MicrosoftDocs/windows-itpro-docs#5101]
[Enter feedback here]

Hi, I have problem with my advanced hunting quires. 
For example quire:
FileCreationEvents 
| where EventTime > ago(40d)
| where MD5 == "9655d95b611bff033d3360899bf7cdad77c3af43"
| project ComputerName, FileName, MachineId, ReportId 
| top 100 by ComputerName 

not giving any result and I am searching for hash from one of the alerts. 
Can you help ?
Michal 
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88b10778-0203-5e62-911a-62781a5147ab
* Version Independent ID: 55213ba9-a050-5b98-4453-57258b1df352
* Content: [Overview of advanced hunting capabilities](https://docs.microsoft.com/en-gb/windows/security/threat-protection/microsoft-defender-atp/overview-hunting)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/overview-hunting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/overview-hunting.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by JakKAaj** [comment]
Sorry should be:
ProcessCreationEvents
| where EventTime > ago(40d)
| where MD5 == "9655d95b611bff033d3360899bf7cdad77c3af43"
| project ComputerName, FileName 
| top 100 by ComputerName

**Comment by lomayor** [comment]
Sorry, but this is not a doc issue. The query appears valid, so it's possible you have the wrong MD5 or the file really does not exist. 

Please contact your support provider if you need further assistance. You can contact Microsoft Support from the Help (?) link in Microsoft Defender Security Center.
