### ISSUE TITLE
Ramifications are unclear 

### ISSUE THREAD

**Issue by jeremyBass** [MicrosoftDocs/windows-itpro-docs#5102]
I am left unclear if i do the license update form PRO as it "strongly" suggests, and I need to exit the program or when it end's, my perfectly valid license is seeming subject to "Your Windows 10 Enterprise license will not be renewed if your device is not connected to Olympia." and then what?   What happens to my regular daily but doing this updated license that would move me from PRO to ENTERPRISE? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e9dd8f-c968-5708-06a1-0bcb588ce969
* Version Independent ID: f965dfcb-6546-8e4f-8622-d809a9140013
* Content: [Olympia Corp enrollment guidelines](https://docs.microsoft.com/en-us/windows/deployment/update/olympia/olympia-enrollment-guidelines#feedback)
* Content Source: [windows/deployment/update/olympia/olympia-enrollment-guidelines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/olympia/olympia-enrollment-guidelines.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
I'm fairly sure that if you have a Pro license and upgrade temporarily to Enterprise via the Olympia program, that after you are done using Olympia and the Enterprise license deactivates, that your computer will step-down to Pro again and still have a valid Pro license.

However, I'll verify this with the developers and also add this detail to the article so that it isn't unclear. Thanks for pointing out the vagueness. I will report back here when I am 100% sure this is how it works.

**Comment by jeremyBass** [comment]
Roger, thank you i will hold for word before I op'd in.  This is my only
production machine, and don't want to get it locked up :)

Thank you -Jeremy Bass

**Comment by greg-lindsay** [comment]
Hi Jeremy, I am told that it's a good idea to write down your PRO license key before upgrading to Enterprise. I'm afraid I don't know if the device will automatically re-activate the Pro license or not and I couldn't find out this information. But, it will always be possible to re-activate with the Pro key manually if it doesn't happen automatically. See https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-edition-upgrades#upgrade-by-manually-entering-a-product-key and there is also a command line method documented there if that's preferred.

If I can find some time to test this with a VM, I'll try enrolling myself and then un-enrolling and see exactly what happens.

**Comment by jeremyBass** [comment]
Roger that, I will hold off for just a moment(next week), I just transitioned out of my job, and it may be wise not to lock up my machine just yet lol.  I will complete this opening quest as soon as I pull in my dev environment then I can do it there with my other build and not worry about it lol.  Unless you know of any reason that foul the test here?  I didn't send data that would be bad.

**Comment by e0i** [comment]
Hello @jeremyBass,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Comment by jeremyBass** [comment]
Hello, @e0i ,
My question was, but I didn't see an edit tagged to this.  I would have figured that was why @greg-lindsay didn't clear it?  the issue was that it was not there, not that i was needing to know.  

But yes i am all good here, thank you for the help - Jeremy

**Comment by illfated** [comment]
Thank you for your feedback. We are "all ears" for editing and improving the documentation, especially if you have got a somewhat good description of how you envision any needed change to the document page in question.

**Comment by jeremyBass** [comment]
Hello @illfated ,
I hadn't thought about what to be honest.  The causes for me to raise a flag of confusion was that simple statement @greg-lindsay had made

> I am told that it's a good idea to write down your PRO license key before upgrading to Enterprise. I'm afraid I don't know if the device will automatically re-activate the Pro license or not and I couldn't find out this information. But, it will always be possible to re-activate with the Pro key manually if it doesn't happen automatically. See https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-edition-upgrades#upgrade-by-manually-entering-a-product-key and there is also a command line method documented there if that's preferred.

so maybe some as simple as 

>[!Note]
>Keep your PRO license key saved **before upgrading** to Enterprise.  Although every effort to have it smooth running and a clear re-activation of the Pro license is made, this is still beta testing.  It will always be possible to re-activate with the Pro key manually if it doesn't happen automatically. See [Docs](https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-edition-upgrades#upgrade-by-manually-entering-a-product-key) and there is also a command-line method documented there if that's preferred.

But you guys would know best I have not gotten a chance to read this repo's guidelines fully yet, I have been kept on another issue 😄 I just know what he brought back cleared up my confusion.

**Comment by illfated** [comment]
Fair enough, it is a start. I will wait and see what Greg says, when he gets back from testing or talking with the tech team about this. before creating a PR to add the text (just to be on the safe side).

**Comment by greg-lindsay** [comment]
It's doubtful I'll have time to test this myself. If someone would like to write a note that advises to write down the PRO license before upgrading and submit a PR I'll approve it.

**Comment by e0i** [comment]
@greg-lindsay Thanks, We'll take it from there.

@jeremyBass @illfated A PR will be created based on your suggestions. Thank you for the productive discussion.

**Comment by jeremyBass** [comment]
super, appreciate the the work ya'll do - Cheers - Jeremy

-- sent from phone, please excuse oddities

**Comment by illfated** [comment]
👍 Very good, thank you to all of you for the feedback and follow-up.

@e0i : in case there are any delays in getting the PR started to add the note text, feel free to ping me regarding this.

**Comment by e0i** [comment]
@jeremyBass 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.

**Comment by jeremyBass** [comment]
@e0i rockin, a positive effect on something is a good way to end the week ahah.   have a good weekend ya'll 👊🤘
