### ISSUE TITLE
.bat with switches

### ISSUE THREAD

**Issue by brockettc** [MicrosoftDocs/windows-itpro-docs#5104]
c:\Users\risevision\AppData\Local\rvplayer\scripts\start.bat --unattended

Trying to run the following command through kiosk mode. I create the provisioning packaged and imaged the machine with it in place. It autologins to the kiosk account (risevision) and then sits on a black screen. If I pop task manager open and run a new task 'c:\Users\risevision\AppData\Local\rvplayer\scripts\start.bat -unattended' it works perfectly fine...

Even with removing --unattended from the shell it doesn't seem to work. 'c:\Users\risevision\AppData\Local\rvplayer\scripts\start.bat' But that command also runs through task manager.

Thanks,

Chris

**Comment by illfated** [comment]
May we know which page you came from, what part of the documentation needs to be updated or corrected?

**Comment by e0i** [comment]
@brockettc 

We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.

Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.

Thank you for providing feedback.
