### ISSUE TITLE
gpedit.msc is absent in Windows 10 Home

### ISSUE THREAD

**Issue by AlexeiSL** [MicrosoftDocs/windows-itpro-docs#5106]
gpedit.msc is absent in Windows 10 Home

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: c34dbafa-df3c-a5a5-32d5-2ce152893534
* Version Independent ID: cebdd9a6-45d7-6306-373c-7d31121f9e16
* Content: [Почему ПИН-код лучше пароля (Windows 10)](https://docs.microsoft.com/ru-ru/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password?redirectedfrom=MSDN#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
Please note that https://docs.microsoft.com/windows/ is intended to be used by Windows IT Professionals using Windows 10 Pro, Windows 10 Education and Windows 10 Enterprise licenses.

The documentation pages are not intended for Windows Home users (and yes, we know that Windows 10 Home does not contain the Professional tools).

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @AlexeiSL, thank you for using the *Feedback* feature of Microsoft Docs. @illfated is right with regard to the intended audience of the docs. 

Also, please be informed that gpedit.msc is only available in Professional and Enterprise editions of the Windows 10.  Although we are unable to provide you more information, I recommend that you check related posts/conversations at [Technet forums](https://social.technet.microsoft.com/Forums/home) and [Microsoft Tech community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities) for possible workaround or information, here's an [example](https://social.technet.microsoft.com/Forums/cf88731e-c624-4fce-859c-33f5d2d58a6e/gpeditmsc-not-run-on-windows-10-home-os?forum=win10itprogeneral). You can can ask questions about Windows products and collaborate with community members, experts and also Microsoft engineers.

**Comment by jvsam** [comment]
Hi again @AlexeiSL, we didn't hear from you but we hope the information we've provided helped. We will now close this issue, but feel free to re-open or create another issue via the *feedback feature* if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
