### ISSUE TITLE
Use Windows Hello for Business as smart card certificates

### ISSUE THREAD

**Issue by alexey-zhel** [MicrosoftDocs/windows-itpro-docs#5108]
Is enabling "Use Windows Hello for Business as smart card certificates" mandatory in case if Windows 2012 R2 used as RD session host ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e456736-63a3-672a-814f-047cc66f0f98
* Version Independent ID: 80cd84e4-6ea5-c707-f362-98fd507fcbfa
* Content: [Remote Desktop](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-remote-desktop)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-feature-remote-desktop.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-feature-remote-desktop.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @alexey-zhel, thank you for opening this issue, however, please be informed that this Github site is used as a feedback system to help improve the quality of the technical documentation of Microsoft Docs. So if you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review. 

Now, with regard to your question, we believe it will be best addressed by contacting [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10). You can also check the [Hybrid Deployments Minimum Requirements](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-identity-verification#hybrid-deployments) and please note that RDP with Windows Hello for Business is currently only supported with [certificate based deployments](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-faq#can-i-use-windows-hello-for-business-key-trust-and-rdp).

Other support resources include the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where community members can learn, collaborate, and share experiences about Microsoft products. You can ask your question and start a conversation with other users, experts and also Microsoft engineers. Here are some discussions that may be helpful:

- [Biometrics with Windows Server 2012 R2 and Windows 10](https://social.technet.microsoft.com/Forums/en-US/b303210c-99f6-45be-bcc7-9cf98d72767b/solved-biometrics-with-windows-server-2012-r2-and-windows-10?forum=winserverDS)
- [Enable Windows Hello on a domain joined PC](https://social.technet.microsoft.com/Forums/windows/en-US/d2dbdd0f-2d14-4e95-96e3-cee9251e40a1/enable-windows-hello-on-a-domain-joined-pc?forum=win10itprohardware)
- [PIN and Fingerprint Sign-in options unavailable (greyed out) in Windows 10 1709 Enterprise](https://social.technet.microsoft.com/Forums/en-US/15d0a491-feed-49fe-811d-8d8248bf9e15/pin-and-fingerprint-signin-options-unavailable-greyed-out-in-windows-10-1709-enterprise?forum=win10itprogeneral)
- [Windows Hello for Business](https://social.technet.microsoft.com/Forums/en-US/da02f88b-3147-4fa5-a720-f173505fd3b7/windows-hello-for-business?forum=win10itprosecurity)


Kindly keep us informed if you find any relevant information that can be incorporated into this documentation.

Thank you for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hello again @alexey-zhel, we haven't heard or received any updates from you. We are hoping that you were able to contact support or have engaged with the community to find the answer to your question. For now, we will close this issue, however, feel free to re-open if you find relevant information that can be incorporated into this documentation. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
