### ISSUE TITLE
Unclear whether pre-existing KMS or MAK activation is necessary to activate Windows 10 E3/5 Subscription

### ISSUE THREAD

**Issue by cap273** [MicrosoftDocs/windows-itpro-docs#5111]
For the section under "Existing Enterprise Deployments", the following section is written:

"...you want to move away from depending on KMS servers and MAK keys for Windows client machines, you can seamlessly transition as long as the computer has been activated with a firmware-embedded Windows 10 Pro product key."

My computer is installed with Windows 10 Enterprise, but is not activated against any KMS servers. My Azure AD user account does have a Windows 10 Enterprise E5 license. I'm unsure if this means that my inability to successfully activate my Windows 10 instance is because I do not have a pre-existing activation against my organization's KMS servers.

More context:
https://social.technet.microsoft.com/Forums/windows/en-US/8888338c-28df-4c0e-a8af-39951d3ea451/cannot-activate-windows-10-enterprise-subscription-license-for-azure-ad-joined-device?forum=win10itprosetup#4ca6aade-d6b7-4ae4-87f8-bf0d86936cb1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation#subscription-activation-for-windows-10-education)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
> My computer is installed with Windows 10 Enterprise, but is not activated against any KMS servers. My Azure AD user account does have a Windows 10 Enterprise E5 license. I'm unsure if this means that my inability to successfully activate my Windows 10 instance is because I do not have a pre-existing activation against my organization's KMS servers.

Hi @cap273, thank you for your question. How did you activate your Windows 10 Enterprise? Interesting scenario, your situation somehow falls under [scenario 1](https://docs.microsoft.com/windows/deployment/windows-10-subscription-activation#how-it-works) where it says *...devices that are already running Windows 10 Enterprise will migrate from KMS or MAK activated Enterprise edition to Subscription activated Enterprise edition when a Subscription Activation-enabled user signs in to the device*." Or it can be **scenario 3**, where in if you already have Windows 10 Enterprise E3 license in Azure AD, then ensure that the license is assigned to your Azure AD user account. When you sign on to the Pro device (device needs to be AAD or Hybrid AD joined)—in your case you are already using Enterprise—it's automatically converted to Enterprise device.

Anyway, I believe it will be best to contact [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) to get immediate assistance. You may also want to check this [Ignite video](https://youtu.be/c8X1HTzDglo) that shows an actual demo of Subscription Activation. An important information shared in the video is that, you need to have internet connectivity so the system will know what subscription is assigned to a user at any given point in time. 

Kindly keep us informed on the resolution or any relevant information that can be incorporated into this documentation. Thank you for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hello again @cap273, we haven't heard or received any updates from you. We are hoping that you were able to contact support or have engaged with the Tech community. For now, we will close this issue, however, feel free to re-open if you have suggestions or ideas to help improve the quality of the technical documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by cap273** [comment]
The following MSDN post is relevant to this topic:
https://social.technet.microsoft.com/Forums/windows/en-US/8888338c-28df-4c0e-a8af-39951d3ea451/cannot-activate-windows-10-enterprise-subscription-license-for-azure-ad-joined-device?forum=win10itprosetup#2fc6c344-3ad8-424c-a3cd-cc8398c47437

In particular, the answer:
"I ended up having to activate my computer with a valid Windows 10 Pro license key before being able to activate my Windows 10 Enterprise license.

It is not clear *at all* that buying a Windows 10 Enterprise license in Azure AD is not enough to activate a Windows license, and that additionally need to have an valid Windows 10 Pro license prior."

**Comment by LamyaMusa** [comment]
The same goes for me with this unclear MAK activation

**Comment by BlankaRazovaja** [comment]
Windows 10 Enterprise E3/E5 need KMS or MAK activation. It is possible that your organization's KMS servers are not configured properly or the activation server is down, which is causing the activation to fail.
