### ISSUE TITLE
Web sign-in to Windows 10 - does this work on Hybrid Azure AD joined devices?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/windows-itpro-docs#5122]
With regards to...
Web sign-in to Windows 10
https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809#web-sign-in-to-windows-10

I have hybrid Azure AD joined a device (so, it is joined to both AD DS and AAD; they are synchronised).  "DSREGCMD /STATUS" confirms the computer is Azure Ad Joined.

I then installed Windows 10 ADK, then Configuration Designer, then created a provisioning package to set "EnableWebSignIn" to "Enabled".  (no expertise in InTune, so applying the setting this way).

I do not get the "Web Sign-In" option.

Is this working correctly?  The page says "Web sign-in is only supported on Azure AD Joined PCs", but that leaves ambiguity for "Hybrid Azure AD joined devices".

My objective is to use Azure AD authentication with MFA, to log on to Windows 10.  But there is also a massive on premises infrastructure, so this should remain operational, too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d6356b-87ff-8c3a-56ef-1270a823d3ab
* Version Independent ID: 4d6ae878-66cf-0e10-bdf3-bdd6054cbc9d
* Content: [What's new in Windows 10, version 1809](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809#feedback)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1809.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/whats-new-windows-10-version-1809.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
> Web sign-in is only supported on Azure AD Joined PCs

Hi @anwarmahmood1, thank you for your question. Please be informed that the *Web sign-in* feature is currently in preview, as indicated on this doc. Preview features are features that aren’t complete, but are made available on a “preview” basis so customers can get early access and provide feedback. Preview features:

- Are subject to separate Supplemental Terms of Use.
- Are not supported by Microsoft Support.
- May have limited or restricted functionality.
- Aren’t meant for production use.
- May be available only in selected geographic areas.

Although not supported, you can still contact [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) to confirm the status of this feature, or you can also check with [Azure Support](https://azure.microsoft.com/en-us/support/options/).

Other support resources include the [Azure Community Support](https://azure.microsoft.com/en-us/support/community/), [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where community members can learn, collaborate, and share experiences about Microsoft products. You can ask your question and start a conversation with other users, experts and also Microsoft engineers. Kindly keep us informed if you find any relevant information that can be incorporated into this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hello again @anwarmahmood1, we haven't heard from you but we hope the information we've provided helped. We will now close this issue, however, feel free to re-open if you have suggestions related to this documentation or ideas to make it better for users. Thank you for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
