### ISSUE TITLE
Automatically button click

### ISSUE THREAD

**Issue by thhan** [MicrosoftDocs/windows-itpro-docs#5123]
I write a program with electron wich klick at a button on a website automatically.

On Windows 10 (Build 18362.356) it works perfectly, but at Build 18362.387 it doesn't work.

If this is the wrong project to report bugs, pleas let it me know in wich I can open an issue.

**Comment by mypil** [comment]
@thhan - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by illfated** [comment]
@thhan : It is likely that your problem is caused by your programming tool not being supported on new releases of Windows 10.
Contact your programming tool user forum to get help with your issue.
