### ISSUE TITLE
GPO Flux d'actualité / My FEED

### ISSUE THREAD

**Issue by GowaP** [MicrosoftDocs/windows-itpro-docs#5125]
Bonjour, je ne trouve pas pour les GPO (ADMX) le choix pour le flux d'actualité ; comment "masquer le flux" ?
When choice for "about:start" into Top Sites, Top Sites And News Feeds, Blank Page ? where the GPO attribut ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9aa5c0a6-acd2-4ec3-275d-3a684b3faaf4
* Version Independent ID: 6b475925-ca66-d47f-e180-92988683b37a
* Content: [Paramètres de Stratégie de groupe et de Gestion des périphériques mobiles pour MicrosoftEdge (MicrosoftEdge pour les professionnels de l’informatique)](https://docs.microsoft.com/fr-fr/microsoft-edge/deploy/available-policies)
* Content Source: [browsers/edge/available-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/available-policies.md)
* Product: **edge**
* Technology: **microsoft-edge**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@GowaP - Merci pour cette rétroaction.

Je pense que la meilleure façon d'aller de l'avant est si vous pouvez contacter le support et ouvrir un **[billet de service](https://support.microsoft.com/fr-fr/hub/4338813/windows-help?os=windows-10)** pour les produits Windows 10 afin que cela puisse être résolu dès que possible. Sur la base des résultats, laissez-moi savoir si c'est quelque chose qui peut être appelé dans les documents.

Si cela ne vous dérange pas s'il vous plaît nous tenir au courant de la résolution et je veux vraiment obtenir cette information que vous découvrez de nouveau dans les documents.
