### ISSUE TITLE
WDAC Requirements Change??

### ISSUE THREAD

**Issue by arekfurt** [MicrosoftDocs/windows-itpro-docs#5129]
I just noticed that this page was corrected to remove inaccurate info about being able to create new policies on Windows 10 Pro. That's a good thing.  However, I also noticed that at the same time the page was changed to say that WDAC policies can only be *applied* to Windows 10 Enterprise editions as well.

If that's true, that would be a quite significant, very negative, otherwise unannounced change to WDAC. 

I have Pro devices running 1904 right now where WDAC is still effective. However, I also know sometimes things work even if they're technically outside licensing. Or, perhaps WDAC will be so limited in versions to come? (I hope not.)

Or someone made an error and didn't really mean to change what the doc says about which versions of Windows 10 can have WDAC policies applied to them.

I really hope it's the latter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 481aaad1-c3ed-3eb1-bd29-ebad8f264edd
* Version Independent ID: dc5d9c47-e4aa-22ab-cb41-dfed57c517ac
* Content: [Windows Defender Application Control (WDAC) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@arekfurt - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello @arekfurt ,
for it looks like some kind of a mistake.
there is only restriction for creating of policies, not for deployment
Dear @ShenLanJohn 
Could you please have a look?

Thank you

**Comment by mypil** [comment]
@arekfurt  - From our understanding, the issue has been resolved based on the merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/b7078b3ca74e5fea5e558f24165c56f1e18b9e55 but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
