### ISSUE TITLE
No Network Requirements???

### ISSUE THREAD

**Issue by MikhailCompo** [MicrosoftDocs/windows-itpro-docs#5131]
There is absolutely no information about network requirements in an DaRT documentation.
Nothing about which dynamic ports are used.
Nothing about TCP/UDP.

Your documentation is incompletem, please update it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 023e78cb-1fd7-c881-7476-5770269a68db
* Version Independent ID: b7be7dce-3779-c37e-1dd6-b1a0cbe9c609
* Content: [DaRT 10 Supported Configurations](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/dart-v10/dart-10-supported-configurations)
* Content Source: [mdop/dart-v10/dart-10-supported-configurations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/mdop/dart-v10/dart-10-supported-configurations.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@MikhailCompo - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Dansimp - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by lindspea** [comment]
@MikhailCompo thank you for reaching out. Please have a look at this link and let me know if you think I should add it to the article to help other users as well - https://docs.microsoft.com/microsoft-desktop-optimization-pack/dart-v10/

**Comment by MikhailCompo** [comment]
It's been a year, I have no idea what this is about any longer. Please
resend the link to the article I was querying.

**Comment by lindspea** [comment]
@MikhailCompo https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5131

**Comment by nam31** [comment]
@MikhailCompo  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
