### ISSUE TITLE
Export-StartLayout -UseDesktopApplicationID

### ISSUE THREAD

**Issue by tylerswire** [MicrosoftDocs/windows-itpro-docs#5133]
For <-UseDesktopApplicationID> can it be explained what the change is for & does it pertain to >1809? If so, the page content might should be updated.

https://docs.microsoft.com/en-us/windows/configuration/customize-and-export-start-layout#export-the-start-layout

![update](https://user-images.githubusercontent.com/39066915/66428241-51250100-e9db-11e9-97f5-4cdf26d079aa.jpg)

**Comment by mypil** [comment]
@tylerswire - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hello @tylerswire 

Thanks for your feedback.
You can get full details of that parameter in the documentation for the cmdlet, [here](https://docs.microsoft.com/en-us/powershell/module/startlayout/export-startlayout?view=win10-ps) and you can see the [pr](https://github.com/MicrosoftDocs/windows-powershell-docs/pull/948/files) that added this information. 

I will create a pull request proposing to specify that it applies to versions >= 1809 to the article you referenced.

**Thank you**

**Comment by mypil** [comment]
@tylerswire  - From our understanding, the issue has been resolved based on the merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/08776acb733b6b1465dab008a6f21306ae084dad but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by tylerswire** [comment]
@mypil @get-itips - Thank you for looking into this. I do not see the updated content. How long should the merge promotion take?

**Comment by illfated** [comment]
Looks like the migration process has not included the commit from 12 days ago (commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/08776acb733b6b1465dab008a6f21306ae084dad). 
Maybe someone could check why that commit has not migrated yet?

**Comment by get-itips** [comment]
> Looks like the migration process has not included the commit from 12 days ago (commit [08776ac](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/08776acb733b6b1465dab008a6f21306ae084dad)).
> Maybe someone could check why that commit has not migrated yet?

@kenwith Can you?

**Comment by kenwith** [comment]
Yes, will ask right now.

**Comment by kenwith** [comment]
Evidently there was a merge conflict with another repo that syncs with this repo.. someone is resolving it now and then this PR should go live.

**Comment by get-itips** [comment]
> Evidently there was a merge conflict with another repo that syncs with this repo.. someone is resolving it now and then this PR should go live.

Thank you

**Comment by tylerswire** [comment]
I'm seeing the update now. Thx all!
