### ISSUE TITLE
FileExplorerNamespaceRestrictions - NoRestrictions - on Win 10 Pro - shows regular windows ui

### ISSUE THREAD

**Issue by moorthi07** [MicrosoftDocs/windows-itpro-docs#5134]
OS: Windows 10 Pro 
Build: 1903
If add these lines in Config Designer,
 <v2:FileExplorerNamespaceRestrictions>
                <v3:NoRestriction />
            </v2:FileExplorerNamespaceRestrictions>
It shows regular Start menu and Task bar when 'Kiosk' user logs in instead of the 'Kiosk mode' tiles.
It works right on the Win 10 Enterprise.

My Use case , FYI. 
Lab operators should be able to run only two applications from Kiosk mode. 
The applications need to select 'Task' files from FileDialog to  run tasks on the Factory machines.

Is there any perfect solution than Kiosk mode?

**Comment by mypil** [comment]
@moorthi07 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by moorthi07** [comment]
Sure. 
https://docs.microsoft.com/en-us/windows/configuration/kiosk-xml#preview-folder-access-sample-xml

**Comment by mypil** [comment]
@moorthi07 - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by moorthi07** [comment]
why is this closed? can you point me where to report the product bugs? Thanks

**Comment by mypil** [comment]
@moorthi07 - Please understand that this site is a product documentation site and not a support nor a feature request site. As such, the feedback section here is intended for feedback that improves the content in the Microsoft documentation and not intended for support type issues or user feedback on product features.

Please follow this link to contact support for Windows 10 products:
**[](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)**

If you do find that it is a documentation error,  please do not hesitate to comment back and we'll gladly look into fixing it. Thank you!
