### ISSUE TITLE
"Turn on Windows Defender Application Guard in Enterprise Mode" description is out of date

### ISSUE THREAD

**Issue by weiss-gal** [MicrosoftDocs/windows-itpro-docs#5136]
This setting was changed from enabled/disabled to a bitmask in v1809, see diff here (look for AllowAppHVSI_ProviderSet): 
https://github.com/mxk/win10-secure-baseline-gpo/commit/ccda26687a1e067b8e7c6b2da82eb45e4e7054fd?diff=split

In addition - The name has changed later, in v1903
from: Turn on Windows Defender Application Guard in Enterprise Mode
to: Turn on Windows Defender Application Guard in Managed Mode

See change in https://github.com/mxk/win10-secure-baseline-gpo/commit/b15ef9aff782645938b7278a165d0b983b1c50f1#diff-8be91b5c46ef5705c155b6a18bccfd24
look for PolicyDefinitions/en-US/AppHVSI.adml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41a8c802-79ca-1593-c045-2ed150e9ce40
* Version Independent ID: 3dabd613-2eee-7c65-6f30-6746c8fb5bdf
* Content: [Configure the Group Policy settings for Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/configure-wd-app-guard#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/configure-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-guard/configure-wd-app-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@weiss-gal - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@weiss-gal - From our understanding, the issue has been resolved based on the merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/6009dbbe4c9c9a964f861d95c11a5bbd3f8312df. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by weiss-gal** [comment]
just had a look at https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/configure-wd-app-guard
looks good
