### ISSUE TITLE
URL wrong under requirements

### ISSUE THREAD

**Issue by vstrj** [MicrosoftDocs/windows-itpro-docs#5138]
Under VMs must hosted by a Qualified Multitenant Hoster (QMTH). It links to https://www.microsoft.com/CloudandHosting/licensing_sca.aspx 
It should probably be:
https://www.microsoft.com/en-us/CloudandHosting/licensing_sca.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c34b8c-44b9-b3d3-9894-5a7fd68e2309
* Version Independent ID: ea643c8f-e92d-b90e-4e90-f338cea39e79
* Content: [Configure VDA for Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/vda-subscription-activation#feedback)
* Content Source: [windows/deployment/vda-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/vda-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@vstrj 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
