### ISSUE TITLE
macOS license requirements

### ISSUE THREAD

**Issue by SRE93** [MicrosoftDocs/windows-itpro-docs#5139]
Hey there, could you please add more details or clarify which license we need for using Defender ATP on macOS? is it also the Win10 E5 or higher packages? Is there a "smaller" subscriptions which doesn't include a Windows license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Yes, it is the Win 10 E5. No smaller subscriptions. Thanks.

**Comment by SRE93** [comment]
Hey, there is a new dedicated add-on license available through EA or CSP just to enable the Defender ATP function. Could you add it here as well?
