### ISSUE TITLE
Support for MacOS Catalina Unclear

### ISSUE THREAD

**Issue by SpencerLN** [MicrosoftDocs/windows-itpro-docs#5140]
The article states "The three most recent major releases of macOS are supported. Beta versions of macOS are not supported.", but in the supported versions listed immediately below, Catalina is not included in the list. Can you please either add Catalina to the supported product list or clarify that it is not currently supported? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7a3b63b-afc5-1b25-3a30-e75c788f4a93
* Version Independent ID: 85498c85-fe13-fead-3bac-44db5614db0d
* Content: [Microsoft Defender ATP for Mac](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Hello, @SpencerLN It has only been a few days since Catalina has been released and it might take a while for relevant articles to be updated. Your feedback has been noted and been passed to technical writing team for investigation.

Thank you for providing feedback.

cc @Dansimp
