### ISSUE TITLE
Missing information on how to deal with PC that is already domain-joined to on-premise AD

### ISSUE THREAD

**Issue by bob-pctest** [MicrosoftDocs/windows-itpro-docs#5141]
How do you deploy Win10 Enterprise on a PC that has Win10 Pro and is domain-joined to an on-premise AD?
Does the PC become joined to BOTH the on-premise AD AND Azure AD?
Please provide sufficient explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ecbc1-9c02-5681-7214-356be22ac7e8
* Version Independent ID: 73af82f6-079b-6c37-55c4-cb59e921457a
* Content: [Deploy Windows 10 Enterprise licenses](https://docs.microsoft.com/en-us/windows/deployment/deploy-enterprise-licenses#feedback)
* Content Source: [windows/deployment/deploy-enterprise-licenses.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-enterprise-licenses.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by bob-pctest** [comment]
P.S. - our on-premise AD is synced with Azure AD Connect.

**Comment by e0i** [comment]
@bob-pctest 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
Hello, @bob-pctest 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by MaratMussabekov** [comment]
Hello @bob-pctest ,
**How do you deploy Win10 Enterprise on a PC that has Win10 Pro and is domain-joined to an on-premise AD** - in case on-premise AD is synced with Azure AD Connect (your case) the device will be considered as Hybrid Azure AD joined and will be licensed.
In case it is just on-premise AD (without Azure AD) - this scenario is not supported.
More details in same article in the [Review requirements on devices](https://docs.microsoft.com/windows/deployment/deploy-enterprise-licenses#review-requirements-on-devices) section.
Thank you

**Comment by e0i** [comment]
Hello @bob-pctest  ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
