### ISSUE TITLE
Does not work in 1903

### ISSUE THREAD

**Issue by AquinoN** [MicrosoftDocs/windows-itpro-docs#5142]
Hello, I've read through and tested various ways with the code... especially after reading through the comments.

I cannot, for the life of me, modify the configuration and set it.  I've tried with the code above, i've tried with user commented code, I've even tried replacing a single character in the xml and set the instance and I constantly get the "A general error occurred that is not covered by a more specific error code." message.  I literally tried $obj.configuration.replace("oldEXE","newEXE") and it fails.  

Can this be updated with tested code on 1903?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f536979-dfd7-317d-2da7-c40935d85c7f
* Version Independent ID: c23737a1-c71e-3d9c-3915-c6929a23602e
* Content: [Use MDM Bridge WMI Provider to create a Windows 10 kiosk (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/kiosk-mdm-bridge)
* Content Source: [windows/configuration/kiosk-mdm-bridge.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/kiosk-mdm-bridge.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
@AquinoN - Thank you for your feedback. Can you please share the output of the code execution so that can better help to understand the issue and help modify the code.
