### ISSUE TITLE
Firmware TPM limitations (with respect to Surface Pro X)

### ISSUE THREAD

**Issue by luriep** [MicrosoftDocs/windows-itpro-docs#5147]
It would be great if this doc also included info on what's possible with the Firmware TPM in Surface Pro X... specifically in this table: https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/tpm-recommendations#tpm-and-windows-features 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 535e3b58-7e16-f593-00a5-f779d4284a21
* Version Independent ID: e7944e4e-3879-4830-45a5-20946df0fb7e
* Content: [TPM recommendations (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/tpm-recommendations#feedback)
* Content Source: [windows/security/information-protection/tpm/tpm-recommendations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/tpm/tpm-recommendations.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@luriep. Surface pro contains  Firmware TPM , i think tpm 2.0 
for more details view below official site 

https://www.microsoft.com/en-us/p/surface-pro-x/8vdnrp2m6hhc?activetab=techspecs

**Comment by joinimran** [comment]
@luriep - Thank you for your query. Please note that Firmware TPM is software-only solutions and runs in a CPU's trusted execution environment and these can be vulnerable to software bugs. Because of this MS recommends hardware-based TPMs and because of this reason, these are not mentioned in the document. 

Thanks.

**Comment by e0i** [comment]
Hello @luriep,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
