### ISSUE TITLE
Univeral conversion to Domain Local

### ISSUE THREAD

**Issue by matt-kit** [MicrosoftDocs/windows-itpro-docs#5148]
I believe the scope conversion for Universal to Domain Local should be amended to read 'Can be converted to Domain Local scope if the group is not a member of any other Universal groups'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44e911d3-219e-19b8-4870-07514d9a94a1
* Version Independent ID: 960a7388-560b-90eb-e0ff-d8d2bb6f9a7a
* Content: [Active Directory Security Groups (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/active-directory-security-groups#feedback)
* Content Source: [windows/security/identity-protection/access-control/active-directory-security-groups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/access-control/active-directory-security-groups.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@matt-kit 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.

**Comment by illfated** [comment]
Ref. PR #5333 (for future readers)

**Comment by matt-kit** [comment]
Sorry, but I don't believe the update has been completed correctly. I was referring to the Universal to Domain Local conversion but it looks like the text has been updated for the Universal to Global conversion which I believe was correct to begin with.

The text for Scope Conversion for Universal groups currently reads:
Can be converted to Domain Local scope
Can be converted to Global scope if the group is not a member of any other Universal groups

I believe this should be as follows:
Can be converted to Domain Local scope if the group is not a member of any other Universal groups
Can be converted to Global scope if the group does not contain any other Universal groups
