### ISSUE TITLE
Inactive machines, after 30 days, are ignored

### ISSUE THREAD

**Issue by anvascon** [MicrosoftDocs/windows-itpro-docs#5150]
There are several customers that do not know that after 30 days of inactivity, a devices data is no longer contributing towards the Exposure Score of TVM.
We should have a small note (marked as important), in this page (for example), explaining just that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d1b587-1f0b-4922-63fc-3d732ca6a739
* Version Independent ID: 8a6787b7-9a54-d27b-6fe4-a7012c115ca9
* Content: [What's in the dashboard and what it means for my organization's security posture](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/tvm-dashboard-insights#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/tvm-dashboard-insights.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/tvm-dashboard-insights.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by VLG17** [comment]
@anvascon This information is available in the public documentation of ATP.

https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/machines-view-overview

"The Machines list shows a list of the machines in your network where alerts were generated. **By default, the queue displays machines with alerts seen in the last 30 days.**"

I will nevertheless add a note as you requested.

**Comment by anvascon** [comment]
Thanks for the feedback, but this is not related to the Alert or Machine page.

This is related to TVM data processing and all the indicators offered within like the exposure score, the security recommendations, etc..

TVM data will account for inactive machines, that were “seen” during the last 30 days.

Is essence, we want to make sure customers understand what is the criteria for TVM, so that they don’t falsely think that after a machine becomes inactive (5 days), it is not part of the data processing.

Thanks,
António
