### ISSUE TITLE
Network issues should be better organized

### ISSUE THREAD

**Issue by zjalexander** [MicrosoftDocs/windows-itpro-docs#5154]
I frequently deal with customers who are getting errors about being unable to download updates. This is frequently caused by:
1) Not being aware a WSUS server is configured which is unreachable
2) Having corporate firewall rules that are blocking WSUS

It would be helpful to have a single scenario that lists out:
- How to check if a WSUS server is configured and how to ensure it is reachable/operable if so
- How to check if WU/MU is reachable
- What URLs need to be accessible to ensure access to WU/MU. 
Right now this is cobbled across the Configure Windows Update topic, Windows Update error code reference, and this document. It would be very helpful if this was all organized in a single place. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349d337e-ca0f-a40a-a522-bd1ae71c7d1e
* Version Independent ID: 50f0c3b0-eaad-89c0-eb3c-878e7564d6f6
* Content: [Windows Update troubleshooting](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-troubleshooting#issues-related-to-firewall-configuration)
* Content Source: [windows/deployment/update/windows-update-troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-troubleshooting.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
The author on this article is not set correctly. It should be jaimeo

**Comment by e0i** [comment]
Hello, @zjalexander 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
@zjalexander 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
