### ISSUE TITLE
Wrong code

### ISSUE THREAD

**Issue by pilcherd** [MicrosoftDocs/windows-itpro-docs#5155]
I believe this entry is wrong:

0x8007002 - 0x20009

The first number is likely missing a digit. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 528014e0-02e5-2d77-a229-4895731bb872
* Version Independent ID: 4f46b620-e345-c9e4-70fa-ae4f5a8e48b9
* Content: [Resolution procedures - Windows IT Pro](https://docs.microsoft.com/en-us/windows/deployment/upgrade/resolution-procedures#0x800xxxxx)
* Content Source: [windows/deployment/upgrade/resolution-procedures.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/resolution-procedures.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Fair point, hexadecimal numbers are usually grouped in pairs, as are the preceding and succeeding groups:
```cpp
0x80073BC3 - 0x20009
0x8007002 - 0x20009
0x80073B92 - 0x20009
```
Question is: which number should it be instead?
A number between `0x80073B92` and `0x80073BC3` -- or something else?

**Comment by e0i** [comment]
@pilcherd 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
