### ISSUE TITLE
Azure AD joing Hub 2S

### ISSUE THREAD

**Issue by Shinoku1987** [MicrosoftDocs/windows-itpro-docs#5158]
"Currently, you cannot use Microsoft Authenticator to sign in to Surface Hubs that are joined to Azure AD."

does above also applies to the Surface hub 2S?

We have one and currently i can use the same account to login with password. But i get a out of policy from intune when i try with password less. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddbb85-f5df-b124-2783-0330d9da2e06
* Version Independent ID: aff516a2-3bb0-843d-5652-e25f90bab00f
* Content: [Sign in to Surface Hub with Microsoft Authenticator](https://docs.microsoft.com/en-us/surface-hub/surface-hub-authenticator-app#feedback)
* Content Source: [devices/surface-hub/surface-hub-authenticator-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/surface-hub-authenticator-app.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @Shinoku1987, we would love to help you with your concern, however, this Github site is intended to help improve the quality of the technical documentation through user contributions and feedback. We recommend that you open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance or you can also check with [Azure Support](https://azure.microsoft.com/en-us/support/options/). 

Other support resources include the [Azure Community Support](https://azure.microsoft.com/en-us/support/community/) or the [Microsoft Authenticator app forum](https://social.technet.microsoft.com/Forums/en-us/home?forum=MicrosoftAuthenticatorApp) where you can post your question and get help from the community. Kindly **keep us informed** if you find any relevant information that can be incorporated into this documentation. Thank you.

**Comment by illfated** [comment]
My immediate response, based on the document quote, is that the answer to "does above also applies to the Surface hub 2S?" is "Yes". Then again, it is better to get a verified answer in one of the Microsoft Surface forums, to be absolutely sure if it will be "Yes" or "No".

**Comment by jvsam** [comment]
Hello again @Shinoku1987 we haven't heard from you but we hope the information we've provided helped. We will now close this issue, however, feel free to re-open if you have suggestions related to this documentation or ideas to make it better for users. Thank you for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
