### ISSUE TITLE
DomainNameInformation or DomainNameInformationlist ?

### ISSUE THREAD

**Issue by Ingenieur-Juju** [MicrosoftDocs/windows-itpro-docs#5161]
Hello, 

In the "[sample plug-in VPN profile](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-profile-xsd#native-profile-example)" we can see a "DomainNameInformation" section.

But in the "[VPNv2 configuration service provider](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp)" we can only see a "DomainNameInformationlist" section.

In my Always On VPN XML file, do I must use "DomainNameInformation" or "DomainNameInformationlist" ?

Thank you

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @Ingenieur-Juju, thank you for bringing this to our attention. We appreciate you taking the time to share your feedback. In the future though, we recommend going directly to the actual content page and submit your feedback from there (You'll notice *Open* and *Closed* issues are displayed). This new feedback system at docs.microsoft.com leverages the GitHub platform so we can easily manage contents, and track changes submitted via Pull Requests (PR).

Hello @ManikaDhiman, we'd like to confirm if the *DomainNameInformationList* node is supposed to be used [on this doc](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections) similar to the others (e.g. [VPNv2 CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp) with issue #1330). So far, with the available information and approved changes, *DomainNameInformation* appears to have been deprecated. Again, thanks in advance for your assistance.

**Comment by jvsam** [comment]
Hi again @ManikaDhiman, just following up if you had a chance to look into this community inquiry. Looking forward to your feedback.

@officedocsbot assign @ManikaDhiman

**Comment by jvsam** [comment]
Hi @ManikaDhiman, just a friendly follow-up. Hoping you have information for us regarding this issue. Thank you.

**Comment by ManikaDhiman** [comment]
Hi @jvsam, Thanks for the follow up. I have reached out to the product team to confirm this. I will update the doc as soon as I hear back anything. Thanks!

**Comment by jvsam** [comment]
As always, thank you @ManikaDhiman.

**Comment by jvsam** [comment]
Hello @ManikaDhiman, how are you? Do you have any update from the product team related to this issue? Thanks and regards!

**Comment by ManikaDhiman** [comment]
Hi @jvsam, here's the update from the product team:

The answer is that both are valid, but in different areas:
•	DomainNameInformationList is used in the CSP proper ([VPNv2 CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp))
•	DomainNameInformation is used in the VPNProfile XML

This is an inconsistency that unfortunately happened and we would like to fix in the future. 

Hope this helps. Thanks!

**Comment by jvsam** [comment]
Thank you for the update @ManikaDhiman. Your help is very much appreciated.

@Ingenieur-Juju, please see the information from the Product team. Since we can now consider this issue resolved, we will now close it. Please continue to send your feedback and suggestions to help improve the quality of the technical documentation of Microsoft Docs. Thank you for being part of the community!

**Comment by jvsam** [comment]
@officedocsbot close
