### ISSUE TITLE
Has Data Export been retired?

### ISSUE THREAD

**Issue by dancs85** [MicrosoftDocs/windows-itpro-docs#5166]
The Data Export button doesn't exist under Partners & API, and the link https://securitycenter.windows.com/interoperability/dataexport redirects to the dashboard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d7c9a2b-c6a2-0c0b-3718-a9c0d2cbbf05
* Version Independent ID: 86974870-2d23-e7e0-e7fb-9a58e4957b00
* Content: [Stream Microsoft Defender Advanced Threat Protection events.](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/raw-data-export-storage)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/raw-data-export-storage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/raw-data-export-storage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by dancs85** [comment]
I discovered that Data Export does not show up unless Preview Features are enabled. This should be reflected in the doco

**Comment by jvsam** [comment]
Hi @dancs85, thank you for bringing this to our attention. I was able to replicate the issue as per your feedback. Turning off '**Preview Features**' under *Settings > Advanced Features > Preview features*, disabled some of the options under the *Partners & APIs* tab on the side panel, including *Data Export Settings*. 

**Reference:** Disabled

![image](https://user-images.githubusercontent.com/18371314/67167820-697c1f00-f3d0-11e9-842f-3277ecad0e29.png)

**Reference:** Enabled

![image](https://user-images.githubusercontent.com/18371314/67167873-d1326a00-f3d0-11e9-8df5-ca4ea6da4d13.png)

Again, thank you and please continue to share your suggestions or ideas to help improve the quality of the technical documentation. 

@illfated if time permits, do you want to take this on and create a pull request to add, perhaps a note, to ensure Advanced Features is enabled? As always, thanks for your assistance.

**Comment by illfated** [comment]
Good point, that looks like a fairly important note to make in the document.

Reading the document page again, it looks like that setting may need to be part of the steps under "**Before you begin:**", presumably as a Step 3.

A pull request will be available shortly (along with description noting that the placement and format is open to change, given proper feedback from the author or manager.

**Comment by illfated** [comment]
Wow, that was a quick response. There was not even any time to get feedback within the PR, so please feel free to tell me if more than the merged change is needed to make the document as useful as you think it should be.
