### ISSUE TITLE
Looks like a UI mistake 'TypeScript' as box title?

### ISSUE THREAD

**Issue by viky293** [MicrosoftDocs/windows-itpro-docs#5171]
Looks like that boxes title on this page mistakenly says TypeScript, it's out of the context on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b41a4b6-f36c-6a1e-9cc9-aefe020dbd22
* Version Independent ID: 743761cb-d648-ebd2-fcc6-054118b81bef
* Content: [Troubleshoot TCP/IP connectivity](https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-tcpip-connectivity#feedback)
* Content Source: [windows/client-management/troubleshoot-tcpip-connectivity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/troubleshoot-tcpip-connectivity.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam
