### ISSUE TITLE
this page bears no resemblance to Windows 10 V1903 and Configuration Designer

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/windows-itpro-docs#5175]
In Windows 10, Settings &gt; Family & other users &gt; Set up a kiosk, if I choose Microsoft Edge, the kiosk mode [descriptions] are
 - As a digital sign or interactive display
 - As a public browser

I have no idea how this maps to "single-app" and "multi-app".

Then, in configuration designer, I find Policies/Browser/ConfigureKioskMode, the options are
"For single app assigned access: full screen digital signage and interactive display. For multi-app assigned access: Normal Microsoft Edge running in assigned access"
"For single app and multi-app assigned access: InPrivate public browsing (limited features)."

When you actually choose an option, the resulting "customizations.xml" file shows
            &lt;ConfigureKioskMode&gt;For single app assigned access: Full-screen digital signage and interactive display. For multi-app assigned access: Normal Microsoft Edge running in assigned access.&lt;/ConfigureKioskMode&gt;
ie it *literally* has the description; not "0" or "1" that is described here.

This makes it needlessly difficult to decipher that this page is saying - badly - and what Windows 10 V1903 and Configuration Designer *actually* say.

Then, in Configuration Designer, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f840fa14-a379-d297-c3f7-ada05ec299d6
* Version Independent ID: 81396f7b-7506-43cd-fd9a-4066719a6eb2
* Content: [Deploy Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/microsoft-edge/deploy/microsoft-edge-kiosk-mode-deploy#feedback)
* Content Source: [browsers/edge/microsoft-edge-kiosk-mode-deploy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/browsers/edge/microsoft-edge-kiosk-mode-deploy.md)
* Product: **edge**
* Technology: **microsoft-edge**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@anwarmahmood1 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @anwarmahmood1 Can you please explain your use case so that we can better help and see what changes are required to in the doc.

Thanks.

**Comment by anwarmahmood1** [comment]
The article is MDM/InTune focussed.  Which is kind-of OK.  But that isn't the only way.  Based on the page, I decided to use Configuration Designer [which lets you apply MDM policies, without setting up the entire MDM infrastructure].  It works fine for small-scale scenarios.  Have a look at Configuration Designer - the settings it offers don't match the description.  That isn't helpful.

Then, the Configuration Designer creates a customizations.XML file.  I explained in my original message that I'm not certain this is working correctly.  The XML shows the long, descriptive description.  I would have expected it to be "1" or "0".

Finally, I ended up looking at group policy.  It turns out that these particular settings [for Edge] are available there, too.  In the end, I didn't need MDM, I didn't need Configuration Designer, I could do everything I needed through group policy editor.  There's no mention of this on the page!

I understand Microsoft now considers group policy legacy/deprecated technology, so Microsoft doesn't want to promote it.  But, it would have been helpful that you can actually configure by group policy if you wish.

**Comment by joinimran** [comment]
@anwarmahmood1 Can you please share the path of the policies you have implemented on your system. Can you please also confirm your OS like 1903 or 1803 etc. 
There are few group policies related to Kiosk mode configuration which are available at https://docs.microsoft.com/en-us/windows/configuration/kiosk-policies

**Comment by mypil** [comment]
@anwarmahmood1 - We would like to follow up. Can you please respond to the query of joinimran?

Thank you.

**Comment by mypil** [comment]
@anwarmahmood1 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
