### ISSUE TITLE
Windows 10 Enterprise V1903 English (English International) also exposes these settings using group policy;

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/windows-itpro-docs#5176]
you dont' have to use MDM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f840fa14-a379-d297-c3f7-ada05ec299d6
* Version Independent ID: 81396f7b-7506-43cd-fd9a-4066719a6eb2
* Content: [Deploy Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/microsoft-edge/deploy/microsoft-edge-kiosk-mode-deploy#feedback)
* Content Source: [browsers/edge/microsoft-edge-kiosk-mode-deploy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/browsers/edge/microsoft-edge-kiosk-mode-deploy.md)
* Product: **edge**
* Technology: **microsoft-edge**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@anwarmahmood1 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@anwarmahmood1 Can you please explain this issue where do we need to apply changes in the document.  Or you wanted to say that these settings are available in Windows 10 Enterprise by default?

Thanks.

**Comment by mypil** [comment]
@anwarmahmood1 - We would like to follow up. Can you please respond to the question of joinimran?

Thank you.

**Comment by illfated** [comment]
Please note that the referenced page states that the supported Windows 10 version is 1809 and that it is for Microsoft Edge version 45 and earlier.
> Applies to: Microsoft Edge on Windows 10, version 1809
Professional, Enterprise, and Education

> [!NOTE] You've reached the documentation for Microsoft Edge version 45 and earlier. To see the documentation for Microsoft Edge version 77 or later, go to the [Microsoft Edge documentation landing page](https://docs.microsoft.com/DeployEdge/).

If this page should be updated to describe what is supported in Windows 10 version 1903 as well, it probably needs more extra material than we typically put in our normal Pull Requests. For all I know, it could make more sense to create a new page for "Deploying Microsoft Edge kiosk mode in Windows 10, version 1903". Feedback from the document author & manager could be useful here.

**Comment by mypil** [comment]
@Dansimp - Can you please share your insights on this issue?

Thank you.

**Comment by mypil** [comment]
@anwarmahmood1 - We need more details from you on what you suggest to be added/edited in this doc but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
