### ISSUE TITLE
Concepts and Terminology are Muddled

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#5177]
What is a "reminder"? What is a "notification"? What is an "engaged deadline" as distinct from an "engaged restart"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44aabe97-360e-0655-09ec-5d1e352bdb1a
* Version Independent ID: 1c729c42-741d-ecb7-6490-a4bfdd029263
* Content: [Enforce compliance deadlines with policies in Windows Update for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/wufb-compliancedeadlines#prior-to-windows-10-version-1903)
* Content Source: [windows/deployment/update/wufb-compliancedeadlines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/wufb-compliancedeadlines.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mypil** [comment]
@Air-Git - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by jaimeo** [comment]
Notifications are UI elements that appear on the screen of a user. The topic shows you pictures of all of the various notifications. "Reminder" does not appear in this topic as noun--only as an adjective modifying "notification." There are _reminder notifications_: those you can dismiss. There are _warning notifications_: those you cannot dismiss--they persist until you do what the notification is telling you to do, or until the device takes action by itself.

A deadline is the usual meaning of the word: a point in time by which you must complete an action. An "engaged restart" is as is defined in the topic: "If the device can't find an idle moment to restart, then the device will go into engaged-restart. The end user, at this point, can select a time that they would like the device to try to restart." So the engaged restart is one which still allows the user the opportunity to "engage" with this process by choosing a time when they'd like it to happen. So the "engaged deadline" is the _deadline_ (i.e. the limit of allowed time) for the user to take advantage of the opportunity to control when the restart happens. If they do reschedule the restart, that's the "engaged restart."

**Comment by Air-Git** [comment]
### Version 1903
For the first few days, the user receives a toast notification. A toast notification offers the user an opportunity to restart, or to schedule a restart, but the user is not required to respond. For how many days does the notification appear?  Is the number of days the same as the deadline period, or is it an arbitrary number of days? In my testing it actually appears only once, but it is signalled by an icon in the system tray for the rest of the pending restart.
At a given point (what point?) the user receives a new-style Big Blue Box notification, with an opportunity to restart now, remind again later, or pick a time for the restart. Unlike the toast notification, this notification locks the screen until the user responds.
If the user selects "Remind me later", the notification will appear again daily (configurable?) until (when?). 
If the user picks a time, the device will restart at that time with no further warning (in my testing). If the user does not pick a time, towards the end of the period (when? configurable?) the user will receive a warning notification that a restart is imminent. I only see two Big Blue Box notifications: "Your organisation requires you to restart in x days" (a reminder) and "You're getting an update" (a warning). I don't see the other two dialogs in the document.
Is the grace period included in the deadline, or is it in addition? I think it must be in addition. In which case, the deadline is the date at which a restart will occur if the user does not schedule an alternative. And the grace period is the additional time available if the user picks a time to restart.
Different durations can be set before a deadline for feature updates and for quality updates.
### Windows 1809
The device will attempt to restart outside active hours (configurable). If the device is unable to restart outside of active hours, the user will receive a toast notification. The toast notification offers the opportunity to restart, pick a time, or be reminded again later. The user is not required to respond. If the user does not respond, there is no further toast notification. The notification does not remain in the system tray.
I am unable to understand from the documentation what further notifications the user receives. Is there a Big Blue Box notification before the restart? How long before the restart? Is there a warning before the restart occurs? Is the timing configurable?
### Policy CSP
We should assume, perhaps, that the Policy CSP provides the definition of the configurable elements of the restart process. But the policy CSP does not mention a distinction between toast notifications (ignorable) and Big Blue Box notifications (not ignorable).
The update and restart behaviour seems to depend first on which of the four options is selected for the auto-update behaviour. The restart behaviour is then controlled by whether a forced restart can occur outside active hours or not.
An "auto-restart" seems to mean a restart that takes place without the user intervening to schedule a time. An "engaged restart" appears to mean one where the user has intervened to schedule a time.
The circumstances when an auto-restart can and cannot occur are very unclear.
It seems that the restart can transition from "auto" to "engaged" without the user intervening. But in this meaning of "engaged" the user can continue to ignore, in which case the restart is "auto" and not "engaged".
### Intune
In Intune, the "Engaged restart" settings are deprecated, and replaced by the Deadline settings, with no mention of a dependency on 1903.

**Comment by jaimeo** [comment]
Fantastic! These are great questions I can take to the PM to get clarifications on. Thanks!

**Comment by jaimeo** [comment]
I have forwarded this issue to the PM. I know they are drafting a number of updates to the WUfB material for Ignite, and I will ask if they want to address some of these questions as part of that.

**Comment by Air-Git** [comment]
Rather strangely, the toast notifications mentioned are not the ones we see. We get this one, with a choice to "Pick a time", "Restart tonight" and "Restart now". This is for a regular monthly update, not a feature update.
<img width="274" alt="Your Organisation required" src="https://user-images.githubusercontent.com/31771283/67479531-2f23b380-f656-11e9-9a65-def238e269a6.png">

**Comment by jaimeo** [comment]
How odd! I've forwarded this to the PM. Just for clarity, are you running 1903?

**Comment by Air-Git** [comment]
We have the same toast notification on 1809 and 1903. It used to be as shown in the first example (just the black box, no blue screen, cable and plug). But it changed recently to this more colourful one.

**Comment by jaimeo** [comment]
I'll schedule something with the PM to see which of these issues they want to address, how, and when.

**Comment by mypil** [comment]
@jaimeo - Do you have any updates on this? Thanks.

**Comment by jaimeo** [comment]
Meeting w/ PM next week.

**Comment by arcarley** [comment]
Hello @Air-Git, thank you for your feedback and for calling out some open issues in the documentation. I will be working to update the documentation with the correct screenshots and to better clarify the expected behavior! :) 

_(Please be aware, given the month of December has many folks out for various holidays the changes may not be live until early 2020)._

**Comment by mypil** [comment]
@Air-Git - We will close this issue now. As per @arcarley, this doc will be updated and the changes may not be live until early 2020.

Thank you for your contribution to make the docs better! Much appreciated!
