### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by shaun-lee-uk** [MicrosoftDocs/windows-itpro-docs#5179]
the ST: Microsoft Windows 10 (April 2018 Update) above if v0.03, the version on the Common Criteria portal is v0.05 and dated some 6 months later

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe7d3c1c-e45e-a6d9-59e9-ba5dc9e72884
* Version Independent ID: e45d6465-dd18-e63a-7e13-f0714f7beeeb
* Content: [Common Criteria Certifications](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-platform-common-criteria#feedback)
* Content Source: [windows/security/threat-protection/windows-platform-common-criteria.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-platform-common-criteria.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@shaun-lee-uk  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@shaun-lee-uk - Can you please confirm what changes are required to be added in the document?

**Comment by shaun-lee-uk** [comment]
I don't know what the detailed changes are, just that there is a later version posted on the official Common Criteria Website  (https://www.commoncriteriaportal.org), and that is supposed to be the definitive document.  Your Security Evaluations team should know what to do.

**Comment by joinimran** [comment]
@DulceMontemayor Can you please look into this request and confirm what is required from my side so that I can update the document.

**Comment by mypil** [comment]
@DulceMontemayor - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by DulceMontemayor** [comment]
Dani Halfin already asked SME Garrett Burk to respond....let's hear it from him....

**Comment by shaun-lee-uk** [comment]
Folks, in the 7 months it's taken you to get this far, someone's already resolved it.

I'll just point out that when you had a dedicated security evaluations mailbox - this would have been fixed in a couple of weeks max.  Poor service if I can rely on a third party's website (OK, it's the US govt, but the principle ...) more than the vendor's own.
