### ISSUE TITLE
Needs method for AUMIDs for HoloLens.

### ISSUE THREAD

**Issue by evmill** [MicrosoftDocs/windows-itpro-docs#5180]
These methods don't worry especially well for HoloLens 1 as you can't directly view your apps or use PowerShell. 
So far my best method for getting an AUMID is to go to Device Portal, and then modify the PackageFullName and remove the version number and architecture information in it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69202cf2-6553-c950-dc75-750a50226571
* Version Independent ID: d80652ad-4aae-00c9-fdd8-7294e9453cef
* Content: [Find the Application User Model ID of an installed app](https://docs.microsoft.com/en-us/windows/configuration/find-the-application-user-model-id-of-an-installed-app#feedback)
* Content Source: [windows/configuration/find-the-application-user-model-id-of-an-installed-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/find-the-application-user-model-id-of-an-installed-app.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@evmill  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@evmill I don't know any other way of finding out the AUMID other than the one you already mentioned or publishing your app to Windows Store and afterwards using the methods described in the article.

You could also open a dedicated support ticket with [Hololens Support](https://support.microsoft.com/en-us/supportforbusiness/productselection?sapid=3ec35c62-022f-466b-3a1e-dbbb7b9a55fb)

**Comment by mypil** [comment]
@evmill - From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
