### ISSUE TITLE
This setting can negatively impact Exchange if not deployed correctly

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/windows-itpro-docs#5184]
Perhaps a link to https://support.microsoft.com/en-us/help/4055652/access-checks-fail-because-of-authz-access-denied-error-in-windows-ser
and a note about Exchange for this policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef8b6967-0e45-bcdd-6d70-54759d9f7ec8
* Version Independent ID: 6651ebc1-04f0-421f-891b-6957ca37da7c
* Content: [Network access - Restrict clients allowed to make remote calls to SAM](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@vboyev-MSFT  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@vboyev-MSFT - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/c9d9547f0db84b8cf133497f75a9fd2bd7a58ab6. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
