### ISSUE TITLE
There should be a similar page for Antivirus on Windows Server 2019.

### ISSUE THREAD

**Issue by huuducle** [MicrosoftDocs/windows-itpro-docs#5187]
Especially the 'Windows Defender Antivirus' feature on Windows 2019, there is no more sub-feature, the 2 sub-features below are merged to have a single one.
. Windows Defender
. GUI for Windows Defender

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d1dee2b-d86a-0019-f689-81483fab31f5
* Version Independent ID: 02722ca2-1dde-aafb-22e3-67259c4ece37
* Content: [Windows Defender Antivirus on Windows Server 2016](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-on-windows-server-2016#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-on-windows-server-2016.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-on-windows-server-2016.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by e0i** [comment]
@denisebmsft Would you be able to shed light on this matter? Any plans to release the 2019 version of the article? Thank you.

**Comment by shivakakarla** [comment]
I'm having trouble with Ansible for this feature in the 2019 server. Confirming the details about 2019 version would be helpful.

**Comment by denisebmsft** [comment]
@e0i, @huuducle, and @shivakakarla, I'm looking into this, and will post an update as a new comment here.

**Comment by denisebmsft** [comment]
Hello! The article has been updated, so I am going to close this issue for now. Please let us know if you run into any issues!
