### ISSUE TITLE
Threat & Vulnerability Management vs Security Center vulnerability

### ISSUE THREAD

**Issue by mzafzal1** [MicrosoftDocs/windows-itpro-docs#5188]
Whats the difference b/w the two? are they same? Which OS will support Threat & vulnerability management?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8c96555-66eb-129e-24e9-fc1e93c77009
* Version Independent ID: 1494fde2-57ed-979f-cbe9-315aeb214bb2
* Content: [Threat & Vulnerability Management](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/next-gen-threat-and-vuln-mgt)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/next-gen-threat-and-vuln-mgt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/next-gen-threat-and-vuln-mgt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by RAJU2529** [comment]
@mzafzal1. Reason is simple. Threats management relates to finding the threats from various files, from various sites and naming according to behaviors.
Security management relates to how to avoids all those threats and giving proper precautions . like installing firewall, antivirus, antimalwares.

**Comment by e0i** [comment]
Hello, @mzafzal1 

It seems that your question has been answered by the community and thus we are marking this issue as resolved.

Please note that the issues section of this repository is intended for documentation feedback.

Should you have any further issues similar to this one, please consider opening a product support ticket here:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Feel free to re-open this issue if you feel that there are further suggestions to improve the documentation itself.

Thank you for providing feedback.
