### ISSUE TITLE
Disabling Windows Defender Credential Guard is not working with Windows 10 1803

### ISSUE THREAD

**Issue by ealfan** [MicrosoftDocs/windows-itpro-docs#5190]
Hi, I need to use VMware VM's but  Windows Defender Credential Guard prevents me to use these VMs. If I tried to use these steps to disable, it did not work. 

Following errors were observed when we tried to run the rule. Previous Windows version 1703, it was working properly.

PS D:\dgreadiness_v3.6&gt; .\DG_Readiness_Tool_v3.6.ps1 -Disable
###########################################################################
Readiness Tool Version 3.4 Release.
Tool to check if your device is capable to run Device Guard and Credential Guard.
###########################################################################
Disabling Device Guard and Credential Guard
Deleting RegKeys to disable DG/CG
ERROR: The system was unable to find the specified registry key or value.
del : Cannot find path 'C:\WINDOWS\System32\CodeIntegrity\SIPolicy.p7b' because it does not exist.
At line:1 char:1
+ del  "$env:windir\System32\CodeIntegrity\SIPolicy.p7b"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\WINDOWS\Syst...ty\SIPolicy.p7b:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Disabling Hyper-V and IOMMU
Disabling Hyper-V and IOMMU successful
Copy-Item : Cannot find drive. A drive with the name 'Z' does not exist.
At D:\dgreadiness_v3.6\DG_Readiness_Tool_v3.6.ps1:1246 char:22
+ ... CmdOutput = Copy-Item "$env:windir\System32\SecConfig.efi" $FreeDrive ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Z:String) [Copy-Item], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Please reboot the machine, for settings to be applied.
PS D:\dgreadiness_v3.6&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#feedback)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
add the corresponding registry key will fix the issue.
I am able to disable device gaurd and to enable the same via group policy or in registry

**Comment by e0i** [comment]
Hello, @ealfan 

_DG Readiness Tool_ has recently been updated to version 3.7. You may try that again with the newest version, which can be found here: https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg_readiness_tool

However, Please note that the issues section of this repository is intended for documentation feedback.

Therefore, Should you have any similar questions or problems in the future the future, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you for providing feedback.

**Comment by illfated** [comment]
Link updated:
- https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg-readiness-tool
