### ISSUE TITLE
Please provide a way to find CSPs that do or do not support Intune

### ISSUE THREAD

**Issue by tr5tn** [MicrosoftDocs/windows-itpro-docs#5193]
On [the CSP Reference landing page](https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference) there are a set of lists that refine CSPs to specific operating systems or devices. It would be extremely useful if the CSPs could be filtered by those that are or are not supported in Intune. Those that _are not_ would actually be the more useful view. 

Per [the Intune custom settings documentation](https://docs.microsoft.com/en-us/intune/configuration/custom-settings-windows-10#find-the-policies-you-can-configure), Intune only supports the CSPs that support the Add, Replace, and Get operations, and the documentation instructs you to review any given CSP to find out if it is supported, which clearly puts the labour on the user. 

> Intune doesn't support all the settings listed in Configuration service provider reference. To find out if Intune supports the setting you want, open the article for that setting. Each setting page shows its supported operation. To work with Intune, the setting must support the Add, Replace, and Get operations. If the value returned by the Get operation doesn't match the value supplied by the Add or Replace operations, then Intune reports a compliance error.

**Comment by e0i** [comment]
Hello, @tr5tn 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
@tr5tn Through independent contributor's investigation it has been found that the documentation would not merit from applying suggested changes because "the sorting process looks very complex and cannot be handled by minor modifications." The whole page would need to be recreated for modifications. Thank you for your understanding.
