### ISSUE TITLE
Lien de version entre AGPM et MDOP

### ISSUE THREAD

**Issue by GowaP** [MicrosoftDocs/windows-itpro-docs#5195]
Bonjour, vous indiquez dans ce document que le AGPM 4.0 est intégré dans le MDOP, mais vous n'indiquez pas la version du MDOP ?
Pour ma part, sur VLSC, je trouve le MDOP 2015 datant du 30 aout 2018 et il n'y a pas de précision de version dans la description.
Merci d'apporter plus de précisons.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: ee6d1383-50f7-28ca-73ee-f649a412df10
* Version Independent ID: 4df40f0d-a0a2-951c-04bf-e5ca9fcc2193
* Content: [Nouveautés d'AGPM4.0SP3](https://docs.microsoft.com/fr-fr/microsoft-desktop-optimization-pack/agpm/whats-new-in-agpm-40-sp3#obtention-de-technologies-mdop)
* Content Source: [mdop/agpm/whats-new-in-agpm-40-sp3.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/agpm/whats-new-in-agpm-40-sp3.md)
* Product: **w10**
* Technology: **mdop**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Bonjour, @GowaP 

Le problème fait l'objet d'une enquête et vous serez informé de tout changement en cours de route.

Merci pour vos commentaires.

**Comment by e0i** [comment]
@GowaP 

Avec l'aide de vos commentaires, le contenu a été mis à jour avec les modifications pertinentes en conséquence. Il faudrait quelques semaines pour que le contenu localisé soit publié en ligne. Merci.
