### ISSUE TITLE
Additional settings to enable RDP from server OS editions

### ISSUE THREAD

**Issue by maweeras-msft** [MicrosoftDocs/windows-itpro-docs#5199]
If attempting to RDP from a hybrid Azure AD joined server such as Windows Server 2016/2019 to a Windows 10 Azure AD joined PC then the authentication will fail unless "Network security: Allow PKU2U authentication requests to this computer to use online identities" security setting is enabled on the RDP client side (hybrid Azure AD joined 2016/2019 server). PKU2U is disabled by default on server SKU unless this setting is configured. This requirement should be listed on the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc#feedback)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@maweeras-msft 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by MaratMussabekov** [comment]
Dear @maweeras-msft ,
could you please have a look at the PR I have created?
Thank you

**Comment by maweeras-msft** [comment]
@MaratMussabekov  this is not enough. I suggest adding a comment that if the RDP client is a server SKU such as Windows Server 2016/2019, then the PKU2U related security option must be enabled.

**Comment by MaratMussabekov** [comment]
Dear @maweeras-msft ,
Could you please have a look now?
Thank you

**Comment by e0i** [comment]
@maweeras-msft The mentioned changes have been applied via the following commit:

[[7962234 ] Update connect-to-remote-aadj-pc.md ](https://github.com/MaratMussabekov/windows-itpro-docs/commit/79622347cc376e39e88863d27e211775dc40c4f4#diff-135eca5f0835e3be485ae4186f910303R86)

Thank you for providing feedback and following up.
