### ISSUE TITLE
How does a Client locate a DC

### ISSUE THREAD

**Issue by pedrr** [MicrosoftDocs/windows-itpro-docs#5201]
in the Section "Azure AD join authentication to Active Directory using a Certificate" part B you mentioned that "The Kerberos provider sends the signed pre-authentication data and user's certificate, which includes the public key, to the Key Distribution Center (KDC) service running on the domain controlle".
How does a client identify his DC? what is the specific Query? Is this through DNS, which specific Name?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10fcf686-1781-8a62-16bb-b26b3f5982fd
* Version Independent ID: 37d733ad-e809-1674-ffbc-ae3d0c495423
* Content: [How Windows Hello for Business works - Authentication](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-authentication#azure-ad-join-authentication-to-active-directory-using-a-certificate)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-how-it-works-authentication.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-how-it-works-authentication.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@pedrr 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
