### ISSUE TITLE
Navigation is inconsistent between deployment types and missing information

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/windows-itpro-docs#5203]
I began working on trying to update the docs but I'm in over my head. We began trying to use the docs to walk through using Hybrid Key trust for AAD Joined devices to enabled SSO with Windows Hello for Business to allow access to on-premises domain resources. Through the process, we found that several areas are confusing or incomplete.

1. The use of the word Hybrid throughout the docs seems to be getting mixed between Hybrid identity and Hybrid Azure AD Join. There needs to be some clarification throughout the docs when these words are used. Considering you can have a Hybrid Key trust for Hybrid Azure AD Joined devices and Hybrid Key trust for AAD Joined devices, this can get very confusing.

2. The Azure AD Join Single Sign-on Deployment Guides should be broken into the same separate doc structure that the other 2 guides above it are in.
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso

3. Azure AD Join Single Sign-on Deployment Guides - this name is confusing. This is really the guide for Hybrid Key trust for AAD Joined devices and Hybrid Certificate trust for AAD Joined devices.

3. The Azure AD Join Single Sign-on Deployment Guides should include the same (or similar) pages as are included here - using the blue navigation on the bottom. 
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-ad
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-dir-sync
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-policy

Hopefully this makes sense. Please let me know if you need clarification on these issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e5f5f1-16cf-57e2-bdfc-b090d90437b1
* Version Independent ID: 1662c47f-12cb-147d-25f0-dee98b6c7722
* Content: [Windows Hello for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-identity-verification.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-identity-verification.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@mapalko Would you be able to follow-up with this editorial issue? It seems the problem is beyond the capacity of our team. Let us know in any ways that we can help. Thanks.

**Comment by AdamGrossTX** [comment]
Any update on this issue? This whole topic needs to be reorganized and have more consistent language and navigation. Several sub pages aren’t available from the  TOC either.

**Comment by drunkrhin0** [comment]
Any update on this?

**Comment by AdamGrossTX** [comment]
Is there anyone even monitoring these issues? This is absurd. The topic is HUGELY important and a large key to enabling enterprises to be successful with Windows Hello for Business and on-premises AD resources. Yet no one has responded or updated these docs to help improve their usability. I have spent countless hours trying to make sense of this and attempt to update the docs but it’s such a mess that I’m in over my head. Please have someone make this a priority.
