### ISSUE TITLE
Access denied when trying to copy ReAgent.dll

### ISSUE THREAD

**Issue by TonitoDux** [MicrosoftDocs/windows-itpro-docs#5204]
Having a lot of troubles when copying the files to system32 folder. I always get access denied, especially with reagent.dll. Tried to change the owner of the file but no dice. Any thoughts?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73c22f0-cb0d-e34b-29d8-06829b86784f
* Version Independent ID: 083115ed-f1be-e962-5b0e-5079dec37353
* Content: [MBR2GPT](https://docs.microsoft.com/en-us/windows/deployment/mbr-to-gpt#feedback)
* Content Source: [windows/deployment/mbr-to-gpt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/mbr-to-gpt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by TonitoDux** [comment]
also reagent.dll.mui from de-de folder throws the same error.

**Comment by TonitoDux** [comment]
My fault, I was injecting the files into the windows.wim, not the boot.wim. in the boot.wim everything works like described.

**Comment by RAJU2529** [comment]
@TonitoDux.  I have injected lots of files including third party .exe and .dll files in system32 under windows.wim and under boot.wim.
actually I taken ownership of all files using  registry

**Comment by illfated** [comment]
Please note that this site is used to report documentation issues on docs.microsoft.com .
Errors relating to end user computers can be reported to Microsoft Support, but are usually results of local software problems.
