### ISSUE TITLE
About Trust Type

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/windows-itpro-docs#5205]
The documentation states: "Hybrid Azure AD joined devices managed by Group Policy need the Windows Server 2016 AD FS role to issue certificates. Hybrid Azure AD joined devices and Azure AD joined devices managed by Intune or a compatible MDM need the Windows Server NDES server role to issue certificates."

This is confusing and should be explained, since in a normal situation not the ADFS server but the Registration Authority issues the certificates. Is this needed because the ADFS server will do this on behalf of the user, and in that case I still asume a Registration Authority is still needed. And what about a company which doesn't have ADFS? Do they need to install ADFS to implement this scenario?

"Hybrid Azure AD joined devices and Azure AD joined devices managed by Intune or a compatible MDM need the Windows Server NDES server role to issue certificates" - Does this also count for Co-Managed devices? (so both Intune and Configuration Manager), ConfigMgr also has a feature to deploy certificates, can that be used as well?

I think this needs some rephrasing because for me this raises more questions than that it answers them.

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5739fab2-c6db-a7a9-b0e7-2bf4b85912a7
* Version Independent ID: 82c58053-c1d7-d938-1b0f-f3f7f70ada3b
* Content: [Planning a Windows Hello for Business Deployment](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-planning-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-planning-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by johnjohnjohn87** [comment]
I’m also interested in how/if co-management could impact planning. If there was a way to leverage co-management to simplify going passwordless it would really help drive adoption of both technologies.

**Comment by VLG17** [comment]
@kennethvs AD FS is the certificate registration authority that issues the authentication certificates in this scenario (Hybrid Azure AD joined devices managed by Group Policy). More info [here](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs#public-key-infrastructure)

To answer your second question, yes it also counts for co-managed devices. More details [here](https://docs.microsoft.com/en-us/azure/active-directory/devices/concept-azure-ad-join-hybrid)

![image](https://user-images.githubusercontent.com/41186174/68859926-0ccf0400-06f1-11ea-865c-42a353d4c79c.png)

**Comment by e0i** [comment]
Hello @kennethvs

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
