### ISSUE TITLE
Ports required to access these url

### ISSUE THREAD

**Issue by mzafzal1** [MicrosoftDocs/windows-itpro-docs#5206]
It is not mentioned anywhere which ports need to be opened? http(80), https(433) or both? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86b0db3-f979-bd1f-78a4-41247510721a
* Version Independent ID: 5289bb5f-f015-7f38-05a1-26a615ae07aa
* Content: [Configure and validate Windows Defender Antivirus network connections](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@mzafzal1 

The issue has been noted and the document will be revised in the light of your feedback.

Thanks.

**Comment by joinimran** [comment]
@mzafzal1  - All communications are done using secure channels and you need to unblock port 443 for these URLs.
Adding the same info in the doc as well.

Thanks

**Comment by e0i** [comment]
@mzafzal1 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
