### ISSUE TITLE
Does WIM command need to run for each CIP files under C:\Windows\System32\CodeIntegrity\CiPolicies\Active?

### ISSUE THREAD

**Issue by Eddddeee** [MicrosoftDocs/windows-itpro-docs#5212]
For the section of Deploying policies, it mentioned to copy both the baseline and the supplemental policy files to C:\Windows\System32\CodeIntegrity\CiPolicies\Active and then run the WIM command to refresh the policy without rebooting. Does WIM command (Invoke-CimMethod -Namespace root\Microsoft\Windows\CI -ClassName PS_UpdateAndCompareCIPolicy -MethodName Update -Arguments @{FilePath = 'C:\Windows\System32\CodeIntegrity\CiPolicies\Active\{A6D7FBBF-9F6B-4072-BF37-693741E1D745}.cip'}) need to run for each CIP files under C:\Windows\System32\CodeIntegrity\CiPolicies\Active?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d643fd44-756e-de45-47c8-e9d8e7d77d9a
* Version Independent ID: 273a1d3c-f7d9-2c32-16f3-8be3180147b4
* Content: [Deploy multiple Windows Defender Application Control Policies  (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/deploy-multiple-windows-defender-application-control-policies#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/deploy-multiple-windows-defender-application-control-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/deploy-multiple-windows-defender-application-control-policies.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mdsakibMSFT
* Microsoft Alias: **mdsakib**

**Comment by Eddddeee** [comment]
BTW, what's the "-foo" and "-bar" mean in command "New-CIPolicy -MultiplePolicyFormat -foo –bar"?
Seems this command "Set-RuleOption -FilePath <string> Enabled:Allow Supplemental Policies" is wrong, need to use "Set-RuleOption -FilePath <string> -Option 17" instead.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
> Does WIM command (Invoke-CimMethod -Namespace root\Microsoft\Windows\CI -ClassName PS_UpdateAndCompareCIPolicy -MethodName Update -Arguments @{FilePath = 'C:\Windows\System32\CodeIntegrity\CiPolicies\Active{A6D7FBBF-9F6B-4072-BF37-693741E1D745}.cip'}) need to run for each CIP files under C:\Windows\System32\CodeIntegrity\CiPolicies\Active?

Hi @Eddddeee, for immediate assistance, we recommend contacting [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10). Other support resources include the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can post your question and get help from the community. Kindly keep us informed on the resolution or any relevant information you may find that can be incorporated into this documentation. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation. Thank you.

> BTW, what's the "-foo" and "-bar" mean in command "New-CIPolicy -MultiplePolicyFormat -foo –bar"?Seems this command "Set-RuleOption -FilePath Enabled:Allow Supplemental Policies" is wrong, need to use "Set-RuleOption -FilePath -Option 17" instead.

Hi @isbrahm, not sure if you took ownership of this doc, if yes, can you please provide some insights on the question above regarding the placeholders? If you also know the answer to the original question, kindly share. Thank you in advance for your assistance.

**Comment by jvsam** [comment]
Hi @Eddddeee I just want to let you know that this doc has been updated (*added a better example of powershell command*). Regarding your other question, I hope you were able to find the answer by utilizing the available support resources. We will now close this issue, but please continue to send your feedback and suggestions to improve the quality of the Microsoft documentation through the doc's *feedback feature*.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
