### ISSUE TITLE
Better describe the update status / better logging

### ISSUE THREAD

**Issue by DennisGaida** [MicrosoftDocs/windows-itpro-docs#5214]
I was happy with the legacy Surface Dock Updater. You start an exe, you see progress. Logging is done in Event Log. I totally don't understand the new Updater. Please don't take this as a rant, but from a user that actually wants to update the dock and fails due to lack of documentation and progress bars. So here are my concerns:

Under "**_To Run Surface Dock Firmware Update_**" it says:
_2. After you connect Surface Dock to your Surface device, the tool checks the firmware status while running in the background_

Please document how I can check that the software is doing the checking. "While running in the background" means that a new Windows Service is installed that is running in the background? When I use the msi logging command documented further below - is that how I can check if it's doing its job? The event log seems to be deprecated.

_3. After several seconds, disconnect your Surface Dock from your device and then wait for 5 seconds before reconnecting. The Surface Dock Firmware Update will normally update the dock silently in background after you disconnect from the dock and reconnect. The process can take a few minutes to complete and will continue even if interrupted._

"After several seconds". What does that mean? How do I know it is finished? There is no progress bar or anything. Same goes for "a few minutes to complete" - how do I know it is complete? I guess the flashing LED in the ethernet port? Is there a signal like multiple flashes? No flashes?

Heading "**_Manual installation_**"
I am supposed to reconnect "for 2 minutes". Do I need to time this? Why 2 minutes? Is there some progress bar somewhere I can check that whatever did it's thing?

Heading "**_Event logging_**"
Since the current version doesn't log to the event log, shouldn't the heading be "logging"?
Why are the event log IDs documented here if only relevant for the legacy versions? I suggest removing everything legacy, and putting that under a "Legacy" heading.

I currently have Component10CurrentFwVersion = 4a26d70, Component20CurrentFwVersion=4a1d570. Display port version looks good, MCU seems "different". Now I have no clue what to do and the documentation doesn't help. I'll do some more of the troubleshooting: Uninstalling the update and randomly unplugging/pluggin back in the dock, but that doesn't seem like a smart process. ([Actually it is the same in this unanswered comment](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5046#issuecomment-535937604))

I would love a step-by-step documentation. First do this, than that. All the IT-Pro stuff (network deployment & Intune) needs to be way lower since that won't be the primary use case. I can gladly help improving the documentation with a pull request but right now I don't actually understand the process that needs to happen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7b356e-3dbd-7f59-845e-a92e05865a52
* Version Independent ID: 711c5497-373f-662c-7fae-ba60f046e50c
* Content: [Microsoft Surface Dock Firmware Update](https://docs.microsoft.com/en-us/surface/surface-dock-firmware-update)
* Content Source: [devices/surface/surface-dock-firmware-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-dock-firmware-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @DennisGaida, thank you for taking the time to share your feedback, we appreciate it. There are multiple suggestions to this doc that are currently in review. Some of them might address your issues. You can see on #5046 several linked issues and PRs.

> I can gladly help improving the documentation with a pull request...

That would be great! I would suggest monitoring the status of the open issues and hopefully once the proposed amendments are approved and merged, the documentation will be easy to understand. From there, you can help by submitting pull requests with your suggestions. Here's the [Microsoft Docs contributor guide](https://docs.microsoft.com/en-us/contribute/) for reference. 

I also encourage you to submit your feedback on [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). Your feedback goes directly to the Microsoft product team and they would love to hear what you think. If there's already a request or suggestion similar to yours, you can add your vote to the request. Thank you.

**Comment by StuBeck32** [comment]
Agree completely. While this is great for large organizations to potentially push updates remotely, this shouldn't be the default option for everyone. The previous firmware updater made it very clear you can't remove the dock from your PC at certain points, either that was misleading or we are now all in a situation where we might destroy our docks because we disconnect at the wrong time.

**Comment by DennisGaida** [comment]
@jvsam Thanks for reply! I can't help improving the documentation since, the process isn't clear right now. As you can tell there are multiple issues with the documentation and your linked issue #5046 does not address them. I did file feedback via the Windows Feedback Hub, but you say there is a UserVoice? You link to feedback hub.

Please help improve the documentation and forward this to the surface hub product team.

**Comment by jvsam** [comment]
> I did file feedback via the Windows Feedback Hub, but you say there is a UserVoice? You link to feedback hub.

Great and yes, they're the same. Thank you for submitting your feedback. Also, have you tried collaborating with the community? There is a dedicated [Microsoft Tech Community](https://techcommunity.microsoft.com/t5/Surface-Devices/ct-p/SurfaceDevices) for Surface devices. It's the best place to post your questions, if you have any, and to get help from the experts or other community users. For one, you can engage with them on this ongoing [discussion](https://techcommunity.microsoft.com/t5/Surface-IT-Pro-Blog/Modernized-updating-for-your-Surface-Dock/ba-p/867432). And if there is any relevant information that can be incorporated into this documentation, please let us know or if you are ready, start contributing to make this doc better. Hope this helps.

**Comment by jvsam** [comment]
Hi again @DennisGaida, since there are no requests for content updates/changes, we will close this issue for now. Feel free to reopen if you have feedback or suggestions to help improve the quality of this technical documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by DennisGaida** [comment]
> since there are no requests for content updates/changes

The initial issue is exactly about this. Requests for content changes. You did not reply to these requests, but in all requests referred to external sources such as feedback hub, tech community etc. The documentation itself was not touched, but should be updated as per the initial request.

**Comment by illfated** [comment]
@jvsam : Would it be possible to get a comment from the document owner or someone from the Microsoft Surface Dock Firmware team?

**Comment by MJBu** [comment]
@DennisGaida I have exactly the same issue with the same version numbers as you.  The documentation says that the Component10CurrentFwVersion should be updated to 4ac3970 but has remained at 4a26d70. My situation has got worse recently, after a windows update, the dock no longer detects the external monitor.
Please can the document owner improve the instructions so that it is clear when to connect/ disconnect the dock in relation to running the software.  E.g at the start, do we install the firmware upgrade with or without the dock connected?  I've tried every combination and nothing seems to make any difference.

**Comment by mypil** [comment]
@DennisGaida - As requested, reopening this issue to get more clarity in improving this doc. 

Let me loop in the doc owner to get his insights on this issue. 

@Dansimp - Can you please share your insights on this issue? Or is there a way that we can engage the Product Engineering team to help clarify the feedback? 

Thank you.

cc: @kenwith

**Comment by MJBu** [comment]
@mypil, after more restarts, the firmware is now showing the correct version and detects the external monitor. I am happy for you to close the issue.

**Comment by illfated** [comment]
@MJBu : Thank you for the feedback. You seem to have a particularly slow responding Surface Dock & computer combination, but it is good to hear that you were able to resolve the situation.

Not quite certain who is deeply invested in this issue ticket now, so I will ask Dennis.

@DennisGaida : What is the status of this ticket from your viewpoint? Close it or continue to keep it open?

**Comment by DennisGaida** [comment]
@illfated Technically I got my Suface Dock to update by leveraging several restarts and updating multiple times.

The issues with the documentation remain the same as per original post.

- The new and old version of the dock updater are intermingled in the doc (e.g. event log location for the old/new version).
- Network & Intune Deployment seem out of place, since non-commercial users wouldn't particularly know what this is.
- The lack of visual progress in the new dock updater is very frustrating and the documentation doesn't explain where progress is actually shown, besides "it takes a few minutes"
- Manual installation doesn't explain what to do besides "reconnect your dock" - I suppose one should install the MSI before reconnecting the dock - otherwise reconnecting the dock wouldn't do anything? Maybe manual installation replaces step 2&3 of the installation process? Nobody knows.

If you are happy with the documentation, please close the issue. I, as a user, am not and I do read a lot of Microsoft documentation,

**Comment by illfated** [comment]
(ref. #5832 )

**Comment by mypil** [comment]
@DennisGaida @illfated - Thank you for providing more details on how we can improve and for linking the related issues for this topic. 

@Dansimp - Can we get the Product Engineering team involved in this issue? 
This is so they can shed light on the best approach to address the mentioned concerns for this topic. 

Thank you.

**Comment by greg-lindsay** [comment]
I'm looking at this.

**Comment by StuBeck32** [comment]
This type of intervention by Dennis shouldn't be necessary. He already clarified what his issues were and someone at Microsoft closed the issue because they didn't properly read the comments and thought it was a technical support request. 

Documentation has gone down hill considerably in the last few years with Microsoft, and this entire thread is a prime example of where the issues are. The core issue is that when documentation is updated, there is not a full review of the entire document or chain of documents related to the software. This means one part of a document is often not updated when needed, or these threads have helpful information but the document is not updated for some reason. I greatly preferred when MS documentation was allowed to be the "rapid fire not fully tested" system and not this multi-tiered one we have today.

**Comment by greg-lindsay** [comment]
I was hoping that I could update this topic by deciphering the instructions myself, but I'm not having much luck. If I can get a reply from the product team at least I should be able to test what they tell me.

**Comment by greg-lindsay** [comment]
See https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5756 for an update. I'm going to use that issue as the main one and close this one.
