### ISSUE TITLE
Change wording - PKU2U is needed to use RDP between Hybrid Azure AD joined devices

### ISSUE THREAD

**Issue by maweeras-msft** [MicrosoftDocs/windows-itpro-docs#5215]
When using RDP between Azure AD joined devices as outlined in https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc with NLA enabled, CredSSP uses PKU2U with SPNego. PKU2U is disabled by default on server SKUs and thus RDP from a hybrid Azure AD joined server to a Azure AD joined Windows 10 device or Hybrid Azure AD joined domain member Windows 10 device fails. To resolve this PKU2U needs to be enabled on server SKU. Customers wanting to do this will be confused by the current wording here implying a security risk.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7aabd37-6d2e-a8f2-5fa5-01c9cb4eccce
* Version Independent ID: d683500b-1602-ecad-4fe3-e80238aad24c
* Content: [Network security Allow PKU2U authentication requests to this computer to use online identities (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-allow-pku2u-authentication-requests-to-this-computer-to-use-online-identities)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-security-allow-pku2u-authentication-requests-to-this-computer-to-use-online-identities.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-security-allow-pku2u-authentication-requests-to-this-computer-to-use-online-identities.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for sharing that information @maweeras-msft. I will get this over to the Windows content writing team for review.  If you have suggestions on how it should be written so users can better understand, please let us know.

**Comment by jvsam** [comment]
Hi again @poortom1004, please be informed that the pull request (See PR #5336) that contains suggestions based from your feedback has been approved and merged. This documentation will be updated in the next scheduled publishing run. 

We will now close this issue, but please continue to send your feedback and suggestions to help improve the quality of the technical documentation of Microsoft Docs. Thank you for being part of the community!"

**Comment by jvsam** [comment]
Hi again @maweeras-msft , I just want to inform you that the pull request (See PR #5373) that contains suggestions based from your feedback has been approved and merged. The documentation will be updated in the next scheduled publishing run. We will now close this issue, thank you again for feedback!

**Comment by jvsam** [comment]
@officedocsbot close
