### ISSUE TITLE
Contradiction in the docs

### ISSUE THREAD

**Issue by ShrCaJesmo** [MicrosoftDocs/windows-itpro-docs#5219]
This document states the following:

> The Windows Autopilot for white glove deployment pre-provisioning process will apply all device-targeted policies from Intune. That includes certificates, security templates, settings, apps, and more – anything targeting the device. Additionally, any apps (Win32 or LOB) that are configured to install in the device context and targeted to the user that has been pre-assigned to the Autopilot device will also be installed.

Of importance is this part: _any apps (Win32 or LOB) that are configured to install in the device context and targeted to the user_

[Install Apps on Windows 10 Devices](https://docs.microsoft.com/en-us/intune/apps/apps-windows-10-app-deploy#install-apps-on-windows-10-devices) however states the following:

> If an app is deployed in device context and targeted to a user, the installation fails. The following status and error appears in the admin console:
	Status: Failed.
	Error: A user can’t be targeted with a device context install.

Which is correct, then? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5b57d1-61b3-39d4-34ff-d6dcb858c250
* Version Independent ID: 42609104-815f-9e7a-39aa-38d92cc910c9
* Content: [Windows Autopilot for white glove deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove#preparation)
* Content Source: [windows/deployment/windows-autopilot/white-glove.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/white-glove.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Thanks for noticing this - I am checking to see exactly what is correct and the clarification that should be added.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
@officedocsbot assign @greg-lindsay

**Comment by greg-lindsay** [comment]
FYI, this is still under investigation. I have continued to ask but no answer yet.

**Comment by ShrCaJesmo** [comment]
Thank you for validating this hasn't been forgotten. I've tried to get an answer through other channels and found them to be similarly unforthcoming.

**Comment by greg-lindsay** [comment]
Hi there I have a response. It is detailed. See below - this information will be added to the Intune documentation.

Apps can only be installed in the Device Context when supported by the device and the Intune app type. The following app types support device-context installation. You can assign these apps to a device group:
•	Win32 Apps
•	Microsoft Store for Business (Offline licensed apps only)
•	LOB Apps (MSI, APPX and MSIX)
•	Office 365 ProPlus
•	Windows LOB Apps (specifically APPX and MSIX) and Microsoft Store for business (Offline apps) that you’ve selected to install in device context need to be assigned to a device group.  If one of these apps is targeted to a user, the installation fails. The following status and error appears in the admin console:
o	Status: Failed.
o	Error: A user can’t be targeted with a device context install.

**NOTE:** The above restriction on Windows LOB apps and MSFB apps having to be device-group targeted does not exist when used in combination with an AutoPilot WhiteGlove provisioning scenario. During device white-glove technician flow, All apps that are assigned to the device group, as well as those apps targeted at the user group will be installed as per the white glove documentation.

**Comment by greg-lindsay** [comment]
If this is satisfactory, please close the issue. Thanks!

**Comment by ShrCaJesmo** [comment]
Thank you! So my understanding then is that if Device-context LOB and MSfB apps are targeted to a user group, if the software attempts to install during the technician flow they'll succeed, but if they instead tried to install on an existing Windows instance it'd fail? Does this mean this type of targeting should only be set up for users that only have autopilot WG devices, and only targeted to the user the moment when WG is initiated on the device?
