### ISSUE TITLE
Please include specific examples of compatible security keys

### ISSUE THREAD

**Issue by thinklad** [MicrosoftDocs/windows-itpro-docs#5226]
It would really be more valuable if there were at least a couple of examples of keys that have been tested to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aacf4c87-5c77-1d03-0c60-bc608fabe2f8
* Version Independent ID: 70d65968-6f5e-8013-0b0b-6d5d660969e0
* Content: [Microsoft-compatible security key](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/microsoft-compatible-security-key#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/microsoft-compatible-security-key.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/microsoft-compatible-security-key.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by RAJU2529** [comment]
@thinklad. Testing of all keys are impossible, Some  users  are already using USB security keys.
here is the  examples of security keys 

Yubico
Rohos Logon key
Predator
USB Raptor
KeyLock

you can buy from amazon online or any other stores

**Comment by thinklad** [comment]
I know how to buy a security, but the reality is that not all Yubikeys are supported in this Azure AD context (e.g. O365 support just told me that Yubikey 5C and 5 NFC _should_ work).

I was not suggesting to test every single model under the sun, but to at least provide a list of 3-5 specific models that are known to work.

**Comment by RAJU2529** [comment]
@thinklad. Wait for some days,Might security keys used by users will provide answers

**Comment by mypil** [comment]
@thinklad - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by Romiko** [comment]
Yes, I agree we need a list of devices.
Please can you point me in the right direction for the following
1. We want users to login on our SPA Apps running on Android with Chrome version 76 Browser.
2. Does Azure AD preview support logging in SPA applications (React JS)?
3. What device is passive (No Battery) that supports FIDO2, AAD, Webauth, CTP and NFC?
4. Is there support in Cordova, so can we use existing Fido2, webauthN libraries against MS AAD?

**Comment by mypil** [comment]
@thinklad - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/5071bf495c76389933d48048648a12ecbaf9cf0b. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by thinklad** [comment]
> @thinklad - From our understanding, the issue has been resolved based on this merged commit [5071bf4](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/5071bf495c76389933d48048648a12ecbaf9cf0b). If you feel it hasn't been resolved, please re-open this issue.
> 
> Thank you for your contribution to make the docs better! Much appreciated!

Not exactly, the issue is that even if Yubico for instance does provide compatible security key, not all of their keys support the requirements from AAD/Hello. My original request was to specifically point out a few security key models that are known to work with the AAD implementation.

**Comment by skipmeister123** [comment]
I came here looking for precisely the same thing.  I am disappointed that there's no list of previously tested and compatible keys.
