### ISSUE TITLE
Windows Defender Firewall section wrongly implys URLs could be blocked/allowed in WFAS

### ISSUE THREAD

**Issue by msarcletti** [MicrosoftDocs/windows-itpro-docs#5229]
Please add more context to this section or remove it completely.
https://docs.microsoft.com/en-us/microsoft-edge/deploy/microsoft-edge-kiosk-mode-deploy#supported-policies-for-kiosk-mode

browsers/edge/microsoft-edge-kiosk-mode-deploy.md
----
*Windows Defender Firewall
To prevent access to unwanted websites on your kiosk device, use Windows Defender Firewall to configure a list of allowed websites, blocked websites or both. For more details, see Windows Defender Firewall with Advanced Security Deployment.
-----
Windows Defender Firewall Block/Allow/ConSec rules can be configured with IP addresses only. There is no way to configure URLs in WFAS.
Issue [2396](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2396) talks about the same.

**Comment by mypil** [comment]
@msarcletti - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by RAJU2529** [comment]
@msarcletti. Good question sir. The team will update soon after reviewing this issues

**Comment by mypil** [comment]
@msarcletti - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/d78b8c5526ba85e45896cbffdf4a112a5011be28. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
