### ISSUE TITLE
File Explorer Namespace Restrictions

### ISSUE THREAD

**Issue by degoa** [MicrosoftDocs/windows-itpro-docs#5232]
Hi,

I try to configure the "NoRestriction" option in "File Explorer Namespace Restrictions"
But PPKG installation fail and I receive this error in event viewer:
"
FileExplorerNameSpaceRestrictions" cannot be empty according to the DTD/Schema.
ErrorCode(0xC00CE011)
"
I try to directly copy the xml sample "[Preview] Folder Access sample xml"
https://docs.microsoft.com/en-us/windows/configuration/kiosk-xml#preview-folder-access-sample-xml

But I received the same error message.

I use Windows build 1903 and I try with 1909 but same error...

Below, XML line

![image](https://user-images.githubusercontent.com/56832813/67264619-ea5c1900-f4ab-11e9-91de-95c6bbcdc0dd.png)

When i try with "Download" it works...

Thanks

Degoa

**Comment by mypil** [comment]
@degoa - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
