### ISSUE TITLE
Endpoints for Defender ATP

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#5233]
The article mentions that the endpoint for Defender ATP are country specific and shows an example with de.....

However on the official Defender ATP documentation the service endpoints are listed by region and not by country. 

https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet

Suggest to review this with the product team and update accordingly so we have one message towards IT admins. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c364e-fcf4-8667-17d7-f9a3ec71e1a9
* Version Independent ID: f98f8870-d594-f5df-f6b6-44c9806db7d8
* Content: [Configure Windows diagnostic data in your organization (Windows 10)](https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization)
* Content Source: [windows/privacy/configure-windows-diagnostic-data-in-your-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/configure-windows-diagnostic-data-in-your-organization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@alexverboon - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@alexverboon - Thank you for your query and suggestion. This topic https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization covers diagnostics data and used for telemetry services in Azure Analytics. While this https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet explains the URLs required for ATP services to work properly. These two are different and based on this the URLs are specified differently. 
Thanks.

**Comment by mypil** [comment]
@alexverboon - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
