### ISSUE TITLE
Link about Kiosk and Device configuration policys 

### ISSUE THREAD

**Issue by evmill** [MicrosoftDocs/windows-itpro-docs#5236]
Hello,
I believe this link here:Set up kiosk mode using Microsoft Intune or MDM (Windows 10, version 1803) ---- For create a device profile
Instead of going here: https://docs.microsoft.com/en-us/intune/configuration/device-profile-create
Should go here: https://docs.microsoft.com/en-us/intune/configuration/kiosk-settings
Because that link is not only more relevant to this page, but also displays how to set up a device configuration. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b569a503-23e1-1fb9-69d8-c2f2bbcea1da
* Version Independent ID: 07f39c07-8cb1-b1a1-bdf5-8964d77357f9
* Content: [Set up HoloLens in kiosk mode (HoloLens)](https://docs.microsoft.com/en-us/hololens/hololens-kiosk#set-up-kiosk-mode-using-microsoft-intune-or-mdm-windows-10-version-1803)
* Content Source: [devices/hololens/hololens-kiosk.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/hololens-kiosk.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@evmill - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @evmill, thank you for your feedback. As per my analysis, links are correctly placed as the 1st link creating a device profile can help users to know how they can create a device profile and then proceed with Kiosk settings. 

We really appreciate your feedback and keep looking forward for more.

Thanks.

**Comment by mypil** [comment]
@evmill - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
