### ISSUE TITLE
OTP PIN

### ISSUE THREAD

**Issue by SMBowen** [MicrosoftDocs/windows-itpro-docs#5238]
First: pwdless@microsoft.com (the email listed to contact you for feedback doesn't receive external email)

I recognize the PIN strength features, but was wondering if there was a way to incorporate Microsoft Authenticator (or other OTP) instead of PIN. Basically if fingerprint or facial authentication is not available for some reason, require OTP PIN as a backup rather than a standard PIN. I think this would help prevent the PIN from being easily guessable, while not requiring PIN Complexity.

Thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca080bd-ed37-60a8-ec22-b1929166ff0c
* Version Independent ID: d2742e0c-9d66-4b1f-8555-a1fb1546455b
* Content: [Passwordless Strategy](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/passwordless-strategy)
* Content Source: [windows/security/identity-protection/hello-for-business/passwordless-strategy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/passwordless-strategy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mypil** [comment]
@SMBowen - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by RAJU2529** [comment]
@SMBowen. your idea is good, normally I enabled second verification setup in Microsoft account and in Github account.

Second verification send  OTP to registered mobile when we tries to login

**Comment by SMBowen** [comment]
> @SMBowen. your idea is good, normally I enabled second verification setup in Microsoft account and in Github account.
> Second verification send  OTP to registered mobile when we tries to login

I don't think we necessarily need second OTP for general login using Windows Hello Biometric. I was originally thinking just a replacement for the PIN if someone chooses not to or something prevents them (injury, etc.) from using biometrics; but I guess it could be in addition to the Windows Hello PIN. This is more about staying in line with avoiding unnecessarily complex PINs that users hate trying to comply with/remember, but also not allowing easily guessable PINs.

**Comment by beerisgood** [comment]
@RAJU2529 using mobile phone for 2FA over SMS is a bad idea.
It's cleartext and attacker can read it (SS7 problem)

**Comment by mypil** [comment]
@mapalko - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by mapalko** [comment]
There is not a supported way to use an OTP or the Authenticator App in place of the Windows Hello for Business PIN.

**Comment by SMBowen** [comment]
> There is not a supported way to use an OTP or the Authenticator App in place of the Windows Hello for Business PIN.

@mapalko 
I understand that there is not currently a supported way to use an OTP. This was more of a suggestion to add this feature. The ability to have the OTP number sync calculated locally on an encrypted machine similar to in the Authenticator App would allow for the Business PIN to be more secure.

**Comment by RAJU2529** [comment]
I welcome  this idea from  @SMBowen.  I hope the Microsoft team will look into this feature in coming next windows update

**Comment by mypil** [comment]
@SMBowen - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via **[Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
