### ISSUE TITLE
Where to apply XML via Intune?

### ISSUE THREAD

**Issue by evmill** [MicrosoftDocs/windows-itpro-docs#5239]
Looking at this section here: https://docs.microsoft.com/en-us/hololens/hololens-kiosk#start-layout-file-for-mdm-intune-and-others
I can see that it says "You will select this file when you configure the kiosk in Microsoft Intune" however at no point did I end up needing an XML file to create my own Kiosk mode via Intune either with Single or Multi App Kiosk mode.
Could there be clarity created around this either stating either how and when it is used, or that it is not used with Intune?
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b569a503-23e1-1fb9-69d8-c2f2bbcea1da
* Version Independent ID: 07f39c07-8cb1-b1a1-bdf5-8964d77357f9
* Content: [Set up HoloLens in kiosk mode (HoloLens)](https://docs.microsoft.com/en-us/hololens/hololens-kiosk#start-layout-file-for-mdm-intune-and-others)
* Content Source: [devices/hololens/hololens-kiosk.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/hololens-kiosk.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by evmill** [comment]
I see now it is here: https://docs.microsoft.com/en-us/intune/configuration/kiosk-settings-holographic#multi-app-kiosks 
Use alternative Start layout: Choose Yes to enter an XML file that describes how the apps appear on the start menu, including the order of the apps. Use this option if you require more customization in your start menu. Customize and export start layout provides some guidance, and includes a specific XML file for Windows Holographic for Business devices.

**Comment by mypil** [comment]
@evmill - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@evmill - Could you please assist us by providing more details on how this content could be edited to incorporate your feedback? If you could suggest what the appropriate text and where it should be placed, I could assign one of our team members to create a Pull Request to get it added or you may also create a Pull Request to add in your suggestion and just link this issue so I can have the doc owner review and merge the content. Thank you.

**Comment by evmill** [comment]
Right now what it says is 
"Start layout for HoloLens
If you use MDM, Microsoft Intune, or a provisioning package to configure a multi-app kiosk, the procedure requires a Start layout. **Start layout customization isn't supported in Holographic for Business, so you'll need to use a placeholder Start layout.**
 Note
Because a single-app kiosk launches the kiosk app when a user signs in, there is no Start screen displayed.
Start layout file for MDM (Intune and others)
Save the following sample as an XML file. **You will select this file when you configure the kiosk in Microsoft Intune** (or in another MDM service that provides a kiosk profile).."

However the only time you CAN use a XML file during setting up a Multi App Kiosk to customize your start layout. Which means something here is conflicting. Honestly I haven't been creating my own XML files and making a custom start menu for Windows Holographic for Business. Perhaps someone who has would know better what to say. 
FYI @scooley

**Comment by mypil** [comment]
@evmill - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/9dd3ae847b75e66f81d7ef56723cfc629c8de21e. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
