### ISSUE TITLE
Why can't I download A file I uploaded?

### ISSUE THREAD

**Issue by JustCallMePizza** [MicrosoftDocs/windows-itpro-docs#5241]
So I've been trying to open a .exe file I uploaded to GitHub and when ever I try to open it Windows SmartScreen says that it stopped a potentially harmful file. I just want people to be able to run my app and not have to buy the $130 USD Publishing app Windows has!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb097945-c324-9797-b3a7-9d41b05bec66
* Version Independent ID: f67b7c1b-1d59-3869-b380-44f695356839
* Content: [Windows Defender SmartScreen overview (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-overview#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@JustCallMePizza - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by RAJU2529** [comment]
@JustCallMePizza. Please send a link of the uploaded file, I will check two windows computers.
1.  Installed second party antivirus software -disabled windows defender
2. Using built-in Windows defender -no second party antivirus.


for your kind information, under windows security under apps & browser control,
disable checks apps and files
adjust to OFF in SmartScreen for Microsoft edge

**Comment by JustCallMePizza** [comment]
Alright here `mate how do want me to send it?

**Comment by JustCallMePizza** [comment]
@RAJU2529 heres the file

> @ECHO OFF
REM BFCPEOPTIONSTART
REM Advanced BAT to EXE Converter www.BatToExeConverter.com
REM BFCPEEXE=E:\PizzaOS\RunPizzaOS.bat\PizzaOSV1.1.1.exe
REM BFCPEICON=
REM BFCPEICONINDEX=-1
REM BFCPEEMBEDDISPLAY=0
REM BFCPEEMBEDDELETE=1
REM BFCPEADMINEXE=0
REM BFCPEINVISEXE=0
REM BFCPEVERINCLUDE=1
REM BFCPEVERVERSION=1.0.0.0
REM BFCPEVERPRODUCT=PizzaOS
REM BFCPEVERDESC=This the Windows 10 version of PizzaOS
REM BFCPEVERCOMPANY=(Unoffical)Chicken Health Society
REM BFCPEVERCOPYRIGHT=This is property of CHS's IT
REM BFCPEOPTIONEND
@ECHO ON
@echo off
title PizzaOS V.1 By JustCallMEPizZAa_
color 1c

:menu
cls
echo WELCOME TO PizzA OS V.1.1
echo -------------------------
echo Applications:
echo --------------------------
echo.
echo 1. FileCopy
echo 2. Information
echo 3. Games
echo 4. Shutdown
pause

set /p filemenuchoice=

if %menuchoice% == 1 goto filecopy
if %menuchoice% == 2 goto info
if %menuchoice% == 3 goto games
if %menuchoice% == 4 goto SHUTDOWN
goto menu

:filecopy
title filecopy
color 1c
C:
echo.
echo 1. Desktop
echo 2. Pictures
echo 3. Documents
echo 4. Downloads
echo 5. Information On FileCopy
pause

set /p menuchoice=

if %filemenuchoice% == 1 copy Desktop
if %filemenuchoice% == 2 copy Pictures
if %filemenuchoice% == 3 copy Documents
if %filemenuchoice% == 4 copy Downloads
if %filemenuchoice% == 5 goto filecopyinfo
goto filecopied

:filecopied
cls
echo.
echo.
echo              Copy finished 
echo -------------------------------------------
echo Press Any key to go to menu
pause <nul
goto menu

:filecopyinfo
cls
color 0b
echo ~~~~~THIS WAS MADE BY JustCallMePizZAa_ #1195 on Discord 
echo --------------------------------------------------------
echo File copy is intended for copy files. I am not 
echo Responsible for what you copy and who you copy it from.
cls
pause 
goto filecopy

:info
cls
title INFO
echo --------------------------------------------------
echo .bat OS
echo VERSION: 1.1
echo Creator: JustCallMePizZAa_ #1195 on discordapp.com
echo --------------------------------------------------
echo WARNING: Misuse or deleting this part of this file is considered plagerism.
echo WARNING: I AM NOT LIABLE FOR ANYTHING YOU DO WITH THIS SOFTWARE!
echo Warning: Damage to your computer is not my fault, It is yours for misusing this software!
echo.
echo Have a good day!
pause
goto menu

:games
cls
title Games
echo Games
echo.
echo 1. QuizGame
echo 2. GuessMyNumber
pause <nul

set /p gamechoice=

if %gamechoice% == 1 goto Quizame
if %gamechoice% == 2 goto GuessMyNumber
goto games


:quizmenu
title QUIZ GAME!
color 0a
cls
echo     WELCOME QUIZ MENU
echo -------------------------
pause
echo From here you can ........
echo --------------------------
echo.
echo 1. Start Quiz
echo 2. Quiz Info
echo 3. Main Menu
pause

set /p quizmenuchoice=

if %quizmenuchoice% == 1 goto startquizgame
if %quizmenuchoice% == 2 goto info
if %quizmenuchoice% == 3 menu
goto quizmenu

:quizinfo
cls
title Info 
color 0a
pause
echo This quiz is to see how many chicken facts you know! You can do it! Quiz made by R.J.C
echo Continue using this...
echo NOTE: I AM NOT RESPONSIBLE FOR ANY DAMAGE DONE TO COMPUTER DURING INSTALLATION!!!
pause
cls
goto menu

:startquizgame
cls
title Prepear... To start the Quiz!
color 0a
echo PLease enter your name
echo.
set /p player=
echo.
echo Hi %player%! Press any button to start!
pause >nul
goto q1

:q1
cls
title Question 1!
cls
echo Question 1
echo ----------
echo.
echo What is the main thing you must do after touching a chicken?
echo.
echo A) Eat
echo B) Go in your house
echo C) Wash your hands with cold water
echo D) Wash your hands with hot water
echo.
set /p ans1=

if %ans1% == a goto wr1
if %ans1% == b goto wr1
if %ans1% == c goto wr1
if %ans1% == d goto cr1
goto q1

:wr1
cls
title Incorrect!
color 0a
echo Sorry %player%! Chickens carry many illnesses!
echo.
echo Press any key to return to menu
pause >nul
goto menu

:cr1
cls
title Correct!
color 0a
echo Good job %player% Good job!
echo.
echo Press any key to continue...
pause >nul
goto q2

:q2
cls
title Question 2!
cls
echo Question 2
echo ----------
echo.
echo Where should you go to report chicken abuse?
echo.
echo A) No one
echo B) CHS's Offical Website
echo C) Your Mom
echo D) McDonald's
echo.
set /p ans2=

if %ans2% == a goto wr2
if %ans2% == b goto cr2
if %ans2% == c goto wr2
if %ans2% == d goto wr2
goto q2

:wr2
cls
title Incorrect!
color 0a
echo Sorry %player%! Always report to CHS's offical website!
echo.
echo Press any key to return to menu
pause >nul
goto menu

:cr2
cls
title Correct!
color 0a
echo Good job %player% you did it!
echo.
echo Press any key to continue...
pause >nul
goto q3

:q3
cls
title Question 3!
cls
echo Question 3
echo ----------
echo.
echo Which of these is a chicken's favorite dessert?
echo A) Green potatoes
echo B) Cottage Cheese
echo C) Raw beans
echo D) Chocolate
echo.
set /p ans3=

if %ans3% == a goto wr3
if %ans3% == b goto cr3
if %ans3% == c goto wr3
if %ans3% == d goto wr3
goto q3

:wr3
cls
title Incorrect!
color 0a
echo Sorry %player%! Thats deadly to chickens!
echo.
echo Press any key to return to menu
pause >nul
goto menu

:cr3
cls
title Correct!
color 0a
echo Good job %player% You should own a chicken!
echo.
echo Press any key to continue...
pause >nul
goto win

:win
cls
title Congrats!
color 0f
cls
echo.
echo                     Congrats, %player%! See admin for score!
echo THis test was made by JustCallMePizZAa_ #1195
echo.
pause
cls
echo Return to menu (y/n)
set /p rtn2menu=

if %rtn2menu% == y goto menu
if %rtn2menu% == n goto quizgame
goto win


:SHUTDOWN
Shutdown.exe -s -t 10
cls
msg * Bye!

**Comment by RAJU2529** [comment]
I am able to download successfully in zip format.
and PizzaOSV1.1.1.exe  is does not work in windows 10,  because  application is  16bit app


![Capture](https://user-images.githubusercontent.com/3296790/67366603-6c723d80-f591-11e9-9d6b-6c5b768fe95c.JPG)

**Comment by mypil** [comment]
@JustCallMePizza - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
