### ISSUE TITLE
KeyCredential Admins - KeyAdmins - EnterpriseKeyAdmins

### ISSUE THREAD

**Issue by rrsit** [MicrosoftDocs/windows-itpro-docs#5243]
The article mentions creating a new group "KeyCredential Admins". In a 2016 domain two groups with similar names already exist (Key Admins and Enterprise Key Admins). Are they intended for something else, or can we skip creating "KeyCredential Admins" and use the existing groups?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c400ea-f52d-b45b-a871-31c94262084d
* Version Independent ID: 9465e043-990f-cb8b-2d4b-33dc8d3c21bf
* Content: [Validate Active Directory prerequisites (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-ad-prereq)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-ad-prereq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-ad-prereq.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mypil** [comment]
@rrsit  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by rrsit** [comment]
update. i checked the permissions that "Key Admins" has per default on users in the domain (properties->Security->Advanced->Effective Access

the two properties "Read msDS-KeyCredentialLink" and "Write msDS-KeyCredentialLink" are checked, exactly what the documentation suggests to enable for "KeyCredential Admins".
so i am pretty confident on a win2016 domain the creation and delegation of the extra group is not necessary, the result will be the same.

i'd be happy to have this confirmed from your end.
![image](https://user-images.githubusercontent.com/39527333/67401651-c255de00-f5af-11e9-9dfe-7e6c0a1f6b8f.png)

![image](https://user-images.githubusercontent.com/39527333/67401614-b10cd180-f5af-11e9-9739-cd90c1a914cf.png)

**Comment by MaratMussabekov** [comment]
Hello @rrsit ,
I think that there is no need to add any change to the article since it states at the beginning:
**If you already have a Windows Server 2016 domain controller in your forest, you can skip the next step.**
So the article is not applicable for the WS2016 domains. In prior versions (for example, I have Windows Server 2012 R2) groups you have listed do not exist
Thank you

**Comment by rrsit** [comment]
Hello Marat,
i respectfully disagree. the "next step" after the introduction is discovering and extending the schema. directly after "create the keycredential admins security global group" is "create the windows hello for business users security global group" (which is clearly required on every domain level). so where does the reader draw the line to "skip the next step"? 

also. the next chapter (https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs) specifically mentions this group in step "Add the AD FS Service account to the KeyCredential Admin group and the Windows Hello for Business Users group" and in step "Configure Permissions for Key Registration".
and here it gets really weird, because the description says "this is required to be added manually" directly in the same sentece where WS2016 is mentioned:

![image](https://user-images.githubusercontent.com/39527333/67486179-d7904280-f66b-11e9-8096-543d8aeca98c.png)

so to me, until implementing this whole thing yesterday, it was far from clear what to do exactly.

**Comment by MaratMussabekov** [comment]
Hello @rrsit ,
yeah, it seems kind of unclear
As I understand, if you have Domain Controller running Windows Server 2016:
1. in [Validate Active Directory prerequisites](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-ad-prereq) steps to update schema and to create new group could be skipped
2. in [Prepare and Deploy Windows Server 2016 Active Directory Federation Services](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs) step to **configure permissions for Key Registration** can be skipped, and in **Add the AD FS Service account to the KeyCredential Admin group and the Windows Hello for Business Users group** step Key Admins group must be used

Similar situation could be seen in the article [Configure Hybrid Windows Hello for Business: Directory Synchronization](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-dir-sync)

Dear @mapalko, could you please confirm that the statements above are correct? I will create PR to add the clarification notes.

Thank you

**Comment by mapalko** [comment]
The Key Admins group has the right read and write properties for msDs-KeyCredentialLink and can be used in place of the KeyCredential Admins group as you've both stated. 

I agree with the changes that you've proposed. 

Thanks!

**Comment by mypil** [comment]
@rrsit - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
