### ISSUE TITLE
WDAV Cloud Protection URL - Which ones are needed for Cloud Protection?

### ISSUE THREAD

**Issue by computeronix** [MicrosoftDocs/windows-itpro-docs#5246]
In the Configure and validate Windows Defender Antivirus network connections page, the age describes the following network connections are needed to be allowed for Cloud Protection to work

*.wdcp.microsoft.com *.wdcpalt.microsoft.com *.wd.microsoft.com

Page: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus

On Windows 10 1903 Connection Endpoints page, it shows these networks are needed to allow for Cloud Protection to work.

wdcp.microsoft.com

Page: https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1903-endpoints

Which one is accurate and is the wildcard needed?

**Comment by mypil** [comment]
@computeronix  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
hello @computeronix ,
from my experience, wildcard is not required, and wd.microsoft.com record is not required either.
wdcp.microsoft.com - is a primary cloud protection URL and wdcpalt.microsoft.com is alternative one (i think it will be used only if wdcp.microsoft.com is unavailable).
Thank you

**Comment by mypil** [comment]
@computeronix - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/8d402147b567dd1286aae4807196ce7aa62b1b82 but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
