### ISSUE TITLE
Disperse and inconsistent endpoints details

### ISSUE THREAD

**Issue by juanandmsft** [MicrosoftDocs/windows-itpro-docs#5247]
The endpoints section does not match with the endpoints listed at:
https://docs.microsoft.com/en-us/sccm/desktop-analytics/enable-data-sharing and
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet#enable-access-to-microsoft-defender-atp-service-urls-in-the-proxy-server

I would suggest to either consolidate all endpoints here and point DA/ATP/other documentation here, providing details of what service uses what endpoint and what for, or maybe better, just providing links here to specific products documentation.

Also, as the article focuses on diagnostics data, I would also suggest moving the "Functional" and "Settings" endpoints to https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1903-endpoints and similar documentation. 

Maybe something like this would work??

### Endpoints
The Microsoft Data Management Service routes data back to our secure cloud storage. Only Microsoft personnel with a valid business justification are permitted access.

Solutions like Desktop Analytics or Microsoft Defender Advanced Threat Protection need Windows devices to reach diagnostics endpoints to enable organizations leverage solutions based on diagnostics data. These solutions leverage Windows components like the Connected User Experiences and Telemetry service, Windows Defender Advanced Threat Protection service, Windows Error Reporting, and Online Crash Analysis.

For a complete list of diagnostics endpoints leveraged by **Desktop Analytics**, see [here](https://docs.microsoft.com/en-us/sccm/desktop-analytics/enable-data-sharing).
For a complete list of diagnostics endpoints leveraged by **Microsoft Defender Advanced Threat Protection**, see [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet#enable-access-to-microsoft-defender-atp-service-urls-in-the-proxy-server).

The following table defines **additional diagnostics endpoints** not covered by services in the links above: 

| Service | Endpoint |
|---|---|
| OneDrive app for Windows 10 | `https://vortex.data.microsoft.com/collect/v1`|

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c364e-fcf4-8667-17d7-f9a3ec71e1a9
* Version Independent ID: f98f8870-d594-f5df-f6b6-44c9806db7d8
* Content: [Configure Windows diagnostic data in your organization (Windows 10)](https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization#additional-resources)
* Content Source: [windows/privacy/configure-windows-diagnostic-data-in-your-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/configure-windows-diagnostic-data-in-your-organization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@juanandmsft  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Added information on PR #5475

**Comment by mypil** [comment]
@juanandmsft - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/c605e338e41ba54d002b6a184906f37aecb5e386. 

Thank you for your contribution to make the docs better! Much appreciated!
