### ISSUE TITLE
GlobalProfile is not available in 19H2 

### ISSUE THREAD

**Issue by dacabdi** [MicrosoftDocs/windows-itpro-docs#5248]
19H2 is a service release of 19H1 and will not contain the GlobalProfile feature. The feature is available in 20H1. We should remove 19H2 from the list of supported releases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7479ec95-228f-8f08-4b24-0a7b7a5314ec
* Version Independent ID: f4d42c2f-17a2-52b2-6daa-cc7cecacfdc7
* Content: [Assigned Access configuration kiosk XML reference (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/kiosk-xml)
* Content Source: [windows/configuration/kiosk-xml.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/kiosk-xml.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@dacabdi -  Thank you for submitting feedback and for creating the PR for this issue.

I will get the doc owner to review, approve and merge the PR you created.  

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@dacabdi - From our understanding, the issue has been resolved based on the merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/82a1a00496e9c48a8711911d4d7ba8fe6881c8b3 but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@dacabdi - From our understanding, the issue has been resolved based on the merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/82a1a00496e9c48a8711911d4d7ba8fe6881c8b3 but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
