### ISSUE TITLE
cannot find "Use Windows Hello for business" in "user configuration", it should be in computer configuration

### ISSUE THREAD

**Issue by swiftPeter** [MicrosoftDocs/windows-itpro-docs#5251]
under the "Create the Windows Hello for Business Group Policy object" section:

In the navigation pane, expand Policies under **User Configuration**.
Expand Administrative Templates > Windows Component, and select Windows Hello for Business.
In the content pane, double-click **Use Windows Hello for Business**. Click Enable and click OK. Close the Group Policy Management Editor.

cannot find "Use Windows Hello for business" in "user configuration", it should be in computer configuration

**Comment by illfated** [comment]
There are 28 pages related to the search "Create the Windows Hello for Business Group Policy object".

Could you link the exact page you refer to, so we know where to make the suggested change?

**Comment by e0i** [comment]
@swiftPeter Your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by swiftPeter** [comment]
Hi @e0i , thanks for your reply, the document is https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-policy#follow-the-windows-hello-for-business-hybrid-key-trust-deployment-guide

I notice if I edit the group policy on DC, 'Use Windows Hello for business' is in 'computer configuration'

**Comment by e0i** [comment]
Hello, @swiftPeter 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by illfated** [comment]
Very well. https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-policy#create-the-windows-hello-for-business-group-policy-object (Github: https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-policy.md#create-the-windows-hello-for-business-group-policy-object) it is, then.

> #### Create the Windows Hello for Business Group Policy object
> 
> The Group Policy object contains the policy setting needed to trigger Windows Hello for Business provisioning.
> 
> Sign-in a domain controller or management workstations with _Domain Admin_ equivalent credentials.
> 
> 1. Start the **Group Policy Management Console** (gpmc.msc)
> 2. Expand the domain and select the **Group Policy Object** node in the navigation pane.
> 3. Right-click **Group Policy object** and select **New**.
> 4. Type *Enable Windows Hello for Business* in the name box and click **OK**.
> 5. In the content pane, right-click the **Enable Windows Hello for Business** Group Policy object and click **Edit**.
> 6. In the navigation pane, expand **Policies** under **User Configuration**.
> 7. Expand **Administrative Templates > Windows Component**, and select **Windows Hello for Business**.
> 8. In the content pane, double-click **Use Windows Hello for Business**. Click **Enable** and click **OK**. Close the **Group Policy Management Editor**.

**Comment by illfated** [comment]
I just confirmed that the GPO "Enable Windows Hello for Business" only exists under
**Computer Configuration > Policies > Administrative Templates > Windows Component > Windows Hello for Business >**

(the **User Configuration** section only contains the subfolder "[PIN Complexity]" and no stand-alone GPOs at that stage.

**Comment by swiftPeter** [comment]
@illfated I just found if I install group policy management tool in Windows 10 1903 version, I can see '**enable windows hello for business**' under **user configuration**. My DC version is 1607 and there only has **PIN complexity** under **user configuration**

so it seems like in the lower windows version, there has only PIN complexity, in the new windows version, there has 'enable windows hello for business' under user configuration

**Comment by illfated** [comment]
OK, thank you for the feedback. When you say
> [ ... ] if I install group policy management tool in Windows 10 1903 version, [ ... ]

are you referring to Windows 10 Professional or is it any other edition of Windows 10?

Myself, I had to use Windows Server 2016 (Version 1607) to run `gpmc.msc` and see what it looked like.
Anyway, I hope my Pull Request content may be disproved or rejected if the content change is incorrect.

**Comment by swiftPeter** [comment]
@illfated The document shows '**You need a Windows 10, version 1703 workstation to run the Group Policy Management Console, which provides the latest Windows Hello for Business and PIN Complexity Group Policy settings. To run the Group Policy Management Console, you need to install the Remote Server Administration Tools for Windows 10. You can download these tools from the Microsoft Download Center. Install the Remote Server Administration Tools for Windows 10 on a computer running Windows 10, version 1703**.' 

I guess it refers to 1703 and the above version has **the lastest windows hello for business group policy setting**.  It can also confirm why windows server 1607 version did not have 'enable windows hello for business' under user setting because group policy is not the latest version. 

thanks for keeping monitor this thread, really appreciate at this part

**Comment by illfated** [comment]
OK, so are you saying that I should close the Pull Request and declare this issue as non-existing, meaning that this was not an issue to begin with and that this has mostly been a misunderstanding?

Please forgive me if this response is unexpected, but I am more than a little bit confused now. 😕 ❔

**Comment by swiftPeter** [comment]
@illfated Yes, in the 'new version' of group policy management console, both **user configuration** and **computer configuration** have 'enable windows hello for business'

**Comment by illfated** [comment]
OK, very well. Turns out that I wrote my previous reply at a time when I was more than just a little tired, hence being so slow to understand this. I do see it now. Thank you.
