### ISSUE TITLE
Why MSFT Rec Intune vs. Partner Center? 

### ISSUE THREAD

**Issue by luriep** [MicrosoftDocs/windows-itpro-docs#5253]
on the table at https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/add-devices#registering-devices that lists different ways of registering devices, why do we say that Intune is recommend vs. PartnerCenter?  Shouldn't we be pushing PartnerCenter equally since that's how we're going to validate for DFCI management? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3243b015-5b5f-7a62-0d9d-767d729dc475
* Version Independent ID: ff8c0509-c075-8528-823f-c195ff4d2382
* Content: [Adding devices](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/add-devices#registering-devices)
* Content Source: [windows/deployment/windows-autopilot/add-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/add-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
What is DFCI?

**Comment by greg-lindsay** [comment]
I'm still waiting on a response from the engineering team.

**Comment by greg-lindsay** [comment]
Looking at this again.

**Comment by greg-lindsay** [comment]
I've updated this table based on feedback from the product team. It should publish today.
