### ISSUE TITLE
The download for 64bit does not work

### ISSUE THREAD

**Issue by semipro1337** [MicrosoftDocs/windows-itpro-docs#5254]
Just downloads a 0kb file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5bb1ce3-9128-5385-4417-d22eb5f8cb77
* Version Independent ID: cb6ba731-a2c2-e9b9-7c3e-db781b1b5222
* Content: [Microsoft Safety Scanner Download](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/safety-scanner-download#feedback)
* Content Source: [windows/security/threat-protection/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/safety-scanner-download.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by illfated** [comment]
I recommend that you try downloading it again. the problem is likely temporary.

I just downloaded both files, each taking ≈ 60 seconds to download on a 10 Mbps connection.

This info is for the 64-bit version:

![image](https://user-images.githubusercontent.com/38162891/67436583-07e5cb80-f5ef-11e9-8c3f-f60472709fa4.png)

(The 32-bit version is ≈ 119 MB in size.)

**Comment by drsutherin** [comment]
Follow-up: the file came downloaded was 121MB using Edge, but 0B using Firefox or Chrome

**Comment by illfated** [comment]
Thank you for the feedback, interesting browser difference. Are the other browsers too junked down?
I used Chrome and had no issues there. I have not customized MS Edge to my use at home.
I have not tested if it makes any difference to be logged in with my Microsoft account or not.

**Comment by e0i** [comment]
Hello, It seems like a temporary issue. I have been able to download both files with _Firefox_, _Safari_ and also `wget`. 

We'd like to follow-up if the problem continues. 

Thank you all for your feedback.
