### ISSUE TITLE
Configure Registration Authority template - 2012/gmsa

### ISSUE THREAD

**Issue by rrsit** [MicrosoftDocs/windows-itpro-docs#5259]
in section "Configure Registration Authority template" subsection "Windows 2012 or later domain controllers", step 10 and 11 the name of the service account is listed as adfssvc, but following all the previous steps in the article, this should be the name of the managed service account (gmsa)

in general it is pretty confusing to have seperate sections for servers 2012+ and earlier. the steps are always exactly the same, just the service account name is different. why not skip all the redundancy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b063e00b-84e5-9da7-2229-e0e24da3b877
* Version Independent ID: da9f4867-2aa3-aefa-1603-ddb2ab1ed624
* Content: [Prepare and Deploy Windows Server 2016 Active Directory Federation Services (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@rrsit 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by joinimran** [comment]
Hello @rrsit , Thank you for your feedback. There is a note stating "Group Managed Service Accounts (GMSA) do not support the Build from this Active Directory information option and will result in the AD FS server failing to enroll the enrollment agent certificate. You must configure the certificate template with Supply in the request to ensure that AD FS servers can perform the automatic enrollment and renewal of the enrollment agent certificate."

![image](https://user-images.githubusercontent.com/47118050/69786636-a4961d00-11dc-11ea-81aa-5a378b859824.png)

Thanks.

**Comment by e0i** [comment]
Hello @rrsit,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Comment by frazeraccount** [comment]
I apologize, but I believe @rrsit was referring to steps 10 and 11 in the document, which come after the section referenced above.  I'm not seeing how @joinimran's comments are pertinent.  Can you please explain?
