### ISSUE TITLE
Service Connection Point (SCP) in Active Directory for ADFS Device Registration Service

### ISSUE THREAD

**Issue by rrsit** [MicrosoftDocs/windows-itpro-docs#5260]
this section is highly confusing. 
suddenly we are introduced to a completely new dns name (enterpriseregistration.contoso.com), which is never mentioned before and after in the article. what to do with this? shall we register a dns record for it? shall we input it somewhere? what is this and why is it suddenly required?

strangely enough, this SCP section is followed by "additional federation servers" and "load balance ad fs federation servers" (two completely different topics), and suddenly we are back with "Configure DNS for Device Registration" - which relates to the SCP section. but here only "name of the federation service" (step 5) is mentioned. no mentioning of "enterpriseregistration".  this needs a thorough rewrite.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b063e00b-84e5-9da7-2229-e0e24da3b877
* Version Independent ID: da9f4867-2aa3-aefa-1603-ddb2ab1ed624
* Content: [Prepare and Deploy Windows Server 2016 Active Directory Federation Services (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by rrsit** [comment]
addendum: this link https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn614658(v=ws.11)?redirectedfrom=MSDN explains the "enterpriseregistration" dns name in great detail and may be linked to the SCP section.
also, it mentions registering "enterpriseregistration.contoso.com" as a SAN in the AD FS SSL Certificate.  this part is missing from this documentation in step "Enroll for a TLS Server Authentication Certificate".

**Comment by e0i** [comment]
@rrsit 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
