### ISSUE TITLE
Bulk enrollment 

### ISSUE THREAD

**Issue by MSLuke** [MicrosoftDocs/windows-itpro-docs#5261]
I’m looking for information on how to change the 20 devices limit that the Windows Configuration Designer advises of. I can’t find anything in the MSDocs articles for bulk enrollment or provisoning packages that advises on how to actually change this limit. I am not sure if it is related to the token itself or the account used to generate the token.

If anyone has any answer to this, if you could help that would be appreciated. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8c7ef37-60ce-464e-a2ce-88a074280220
* Version Independent ID: 844aa895-64a9-72f5-bd94-09c9089acc3c
* Content: [Bulk enrollment](https://docs.microsoft.com/en-us/windows/client-management/mdm/bulk-enrollment-using-windows-provisioning-tool#feedback)
* Content Source: [windows/client-management/mdm/bulk-enrollment-using-windows-provisioning-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/bulk-enrollment-using-windows-provisioning-tool.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Hello, @MSLuke 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
@MSLuke 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
