### ISSUE TITLE
Documentation of IntegrityServices registry key

### ISSUE THREAD

**Issue by lookpl** [MicrosoftDocs/windows-itpro-docs#5266]
Hi, I'm missing a description of `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\IntegrityServices`. The only documented entry I found is [TPMActivePCRBanks](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/switch-pcr-banks-on-tpm-2-0-devices). It would be helpful to have other values documented as well.

My exact question is at the moment is what method of last TPM log name retrieval (from an offline system) without external tools is recommended. For example: is PlatformLogFile entry guaranteed to be up to date and available?

**Comment by e0i** [comment]
@lookpl  Your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by lookpl** [comment]
@e0i this is TPM related topic so I'd expect it here https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/trusted-platform-module-top-node
You can see one value of the registry mentioned here https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/switch-pcr-banks-on-tpm-2-0-devices but others are undocumented.

**Comment by e0i** [comment]
@lookpl The linked document contains a list of articles. Could you point to the exact article where the mentioned registry key is missing? We would like to follow-up with content updates. Thanks for taking the time to provide feedback.

**Comment by e0i** [comment]
@lookpl 

We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.

Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.

Thank you for providing feedback.
