### ISSUE TITLE
Configuration in tenant that doesn't meet prereq

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/windows-itpro-docs#5271]
I'm well aware of the E5 requirements of this feature. However I noticed that this feature is available for configuration in tenants who doesn't match the E5 requirements. Normally within Intune, if you're not applicable for a feature, the feature isn't available for configuration within Intune.

I configured the setting and could successfully push this feature to a device, however I couldn't verify cause the setting isn't available on on Virus & Threat protection &gt; Virus & Threat protection settings &gt; Tamper protections &lt;---- doesn't exist.

So what actually happens on the device, and why can I push it from Intune? Even if lacking the licenses

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a2f0402-82fb-83ff-122a-2f19c5288eeb
* Version Independent ID: 52f80b09-0e90-464d-0c4d-00479361fa9b
* Content: [Protect security settings with Tamper Protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
Maybe the license requirement and activation can only be verified from the client computer's own interface?

Could there be a "Preview" setting to enable some features, as if they were in some form of Trial state in the client?

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @xNiklasJern, please be informed that *Tamper Protection* is currently in preview for business customers who have Microsoft Defender ATP, and who are participating in the preview program.

A personal recommendation is to participate in this [conversation](https://techcommunity.microsoft.com/t5/Microsoft-Defender-ATP/Tamper-protection-in-Microsoft-Defender-ATP/bc-p/842797#M470) and request to try the feature in preview mode. I requested and now Tamper Protection is showing on my Intune account and also on the *Virus & Threat Protection settings*.

**Intune:**

![image](https://user-images.githubusercontent.com/18371314/68084791-750e2200-fe75-11e9-93b3-a08379097d9b.png)

**Virus & Threat Protection settings:**

![image](https://user-images.githubusercontent.com/18371314/68084784-632c7f00-fe75-11e9-8dab-0c2aa346b9be.png)

Goodluck and thanks!

**Comment by jvsam** [comment]
Hi again @xNiklasJern, we will now close this issue, but if you have feedback or suggestions to help improve the quality of the technical documentation of Microsoft Docs, please let us know or use the doc's feedback feature.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
