### ISSUE TITLE
Issue with DisplayPort resolution

### ISSUE THREAD

**Issue by jansppenrade2** [MicrosoftDocs/windows-itpro-docs#5273]
Maximum available resolution for an external DisplayPort display connected to Surface Dock is 3840x1080.
With the old firmware I got 5120x1440! Connecting the monitor directly to the Surface Pro 6 is a workaround for the moment.

I hope Microsoft will fix this issue.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment]
@jansppenrade2. Please send  feedback, report the issue from your laptop or desktop

**Comment by jvsam** [comment]
Thank you for taking the time to share your feedback @jansppenrade2, we appreciate it. I  encourage you to submit this on [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). This way, your feedback goes directly to the Microsoft product team and I assure you, they would love to hear what you think. If there's already a request, suggestion or feedback similar to yours, you can add your vote to the request. Thank you.

**Comment by illfated** [comment]
@jansppenrade2 : Please note that this site is made for reporting issues in the Microsoft documentation pages. From my experience, it is much better to report software issues using the Feedback feature on your Desktop or via [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub) as **jvsam** recommended. Wishing you all the best.

**Comment by jvsam** [comment]
Hi again @jansppenrade2, we will now close this issue, but if you have feedback or suggestions to help improve the quality of the technical documentation of Microsoft Docs, please inform us or use the doc's feedback feature.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
