### ISSUE TITLE
Incorrect records due to extra space in the URLs

### ISSUE THREAD

**Issue by meditadvisors** [MicrosoftDocs/windows-itpro-docs#5275]
URLs with extra space:
ussuk1southprod. blob.core.windows.net
ussuk1westprod. blob.core.windows.net
wsuk1southprod. blob.core.windows.net
wsuk1westprod. blob.core.windows.net

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83207fc9-2c91-eb07-4237-6bb1f42e3778
* Version Independent ID: 5db33cf3-2dcb-bb33-a252-3a13ca9737f9
* Content: [Configure machine proxy and Internet connection settings](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment]
@jvsam. Here is the PR website 
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5323/commits/67996ef6ca9272b93a5a9ab0964e16997c2127f6

**Comment by jvsam** [comment]
Thank you for informing us about this @meditadvisors. Much appreciated!

@RAJU2529, is there a pull request associated with your commit? If none, can you please create one so we can easily track it? I can see it linked [cb885c3](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/cb885c3a88a9c7a0996c8ceefec2deda2b29f154) but can't find a PR. Thank you for your assistance here.

**Comment by RAJU2529** [comment]
PR no 5323

**Comment by RAJU2529** [comment]
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5333

**Comment by illfated** [comment]
Your comment https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5275#issuecomment-549145062 was correct, 
but is missing the hashtag # in front of the PR number link the correct page:
- **Incorrect records due to extra space in the URLs** #5323

Please note that the issue numbers in the title does not link anywhere.
It may be a practical way for you to keep track of them, but no link is created.

**Comment by jvsam** [comment]
Thank you again for contributing to the docs @RAJU2529. Since the PR has been merge, we will now close this issue.

**Comment by jvsam** [comment]
@officedocsbot close
