### ISSUE TITLE
Please update the confirmation page to no longer say "You can now use your PIN to login"

### ISSUE THREAD

**Issue by pstakuu** [MicrosoftDocs/windows-itpro-docs#5278]
Every user I help setup with this I have to explain the 30 minute delay, immediately after they see the prompt from the confirmation page that they can now sign in with the PIN.  To the user, it looks like its an issue with our environment, rather than the intentional configuration of the product.  Perspective: They see the product saying they can use it now, we interject and say it doesn't really work that way.  We are the ones delivering the news - they think it's our environment.  Either way, it looks like the product isn't working right or the environment the users are in is flawed.. Both can be fixed by having the correct indication that using the PIN login method will be available after the next directory syncronization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d45db5-5172-45cb-2c4d-d73a9e15d699
* Version Independent ID: fa08e81d-3307-514e-129a-843e812e97a9
* Content: [Hybrid Windows Hello for Business key trust Provisioning (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
> Please update the confirmation page to no longer say "You can now use your PIN to login"

Thank you for bringing this to our attention @pstakuu. This GitHub-based documentation feedback system is intended to help improve the quality of the technical documentation of Microsoft Docs. The best place to send your feedback is through the feedback hub. Please utilize [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub) and submit your request to the Microsoft product team. Thank you.

**Comment by pstakuu** [comment]
Thanks for the update Jo!

Have an awesome day!

**Comment by jvsam** [comment]
Hi again @pstakuu, we will now close this issue, and again, if you have feedback or suggestions to help improve the quality of the technical documentation of the Microsoft Docs, please use the doc's feedback feature to easily track content improvement requests. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
