### ISSUE TITLE
Windows 10  version 1709

### ISSUE THREAD

**Issue by Mariaap84392498** [MicrosoftDocs/windows-itpro-docs#5282]
[Insira comentários aqui]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 5aaec57b-10cb-3954-8230-1fef012f26bb
* Version Independent ID: 205bce72-9a4b-cbc5-8d3f-5971b85ab1f9
* Content: [Novidades no Windows 10, versão 1709](https://docs.microsoft.com/pt-br/windows/whats-new/whats-new-windows-10-version-1709?wt.mc_id=mkto_EM408655A1LA1&ls=email&mkt_tok=eyJpIjoiTXpjMFptWmxOek15TUdFMCIsInQiOiJYdmZud1ZrQ0FGRjB4eEFITnBoNFRqM21hZ3puWHBZUmY2UnZaK0JON1VZSkVOTm92SUhrOWFMZHV3M0o4ckkrVlpUaW82VDlnUUVcL1NKQm1sNmVPbCtrNExCQ3BrNHVmYVpyQzJhcVZKXC96U2NMbEh1TzRCcXVxNGxBelhydUE2Rk1jMmd2MnVSa0xhWTlqZU1DRFwvUHc9PSJ9)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1709.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1709.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2861

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by Mariaap84392498** [comment]
Office open and Windows 10 Enterprise version 1709 show the Tecnologia Inovadora.

**Comment by Mariaap84392498** [comment]
________________________________
De: Jo <notifications@github.com>
Enviado: domingo, 27 de outubro de 2019 01:50
Para: MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>
Cc: Maria Aparecida Da Silva <consultoriolhyadasilva@outlook.com>; Author <author@noreply.github.com>
Assunto: Re: [MicrosoftDocs/windows-itpro-docs] Windows 10 version 1709 (#5282)


@officedocsbot<https://github.com/officedocsbot> assign @jvsam<https://github.com/jvsam>

**Comment by Mariaap84392498** [comment]
Hello GitHub,


Very good day, Microsoft Docs. Repositório services
online LinkedIn and Twitter, Public  Informático.

Subscreve
Maria Aparecida da Silva
Administrar Gerenciar Global
ID 5082238

________________________________
De: Maria Aparecida Da Silva <consultoriolhyadasilva@outlook.com>
Enviado: domingo, 27 de outubro de 2019 22:22
Para: MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>; MicrosoftDocs/windows-itpro-docs <reply@reply.github.com>
Cc: Author <author@noreply.github.com>
Assunto: RE: [MicrosoftDocs/windows-itpro-docs] Windows 10 version 1709 (#5282)


________________________________
De: Jo <notifications@github.com>
Enviado: domingo, 27 de outubro de 2019 01:50
Para: MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>
Cc: Maria Aparecida Da Silva <consultoriolhyadasilva@outlook.com>; Author <author@noreply.github.com>
Assunto: Re: [MicrosoftDocs/windows-itpro-docs] Windows 10 version 1709 (#5282)


@officedocsbot<https://github.com/officedocsbot> assign @jvsam<https://github.com/jvsam>

**Comment by jvsam** [comment]
Hello @Mariaap84392498, it appears that you may have inadvertently opened an issue through the feedback section of this [doc](https://docs.microsoft.com/windows/whats-new/whats-new-windows-10-version-1709). Your can find and follow your original issue here - [https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2861](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2861)?

We will now close this, thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
