### ISSUE TITLE
Rule Level "FilePath" description is incorrect.

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#5284]
The description of the File Rule Level "FilePath" is incorrect. The "Level" parameter takes a FilePath value. This is an alternative to file name, file publisher etc. The "Level" parameter is followed by a "ScanPath" parameter, which determines what path to scan for files. If a value of "FilePath" is used for the level, then the scan identifies all the file in the folder or directory that is scanned, by fully qualified path name. As a result those files, identified by fully qualified path, will be allowed. The ScanPath parameter does not take wildcards. By default it scans all files and folders under a directory root. The "OmitPath" parameter can be used to make exceptions.
The text about wildcards and macros belongs in a different document. The text relates to a different type of rule: not a File Rule, but a File Path Rule. A FilePathRule is a different type of rule that can be added to a policy, using New-CIPolicyRule. In this rule, you can specify a path to allow. ANY file in that path will be allowed, not just the named files discovered in a scan. The rule uses wildcards and macros to define the path. C:\foo allows only files in that folder. C:\foo\* allows all files and folders under a root folder. Using the macro, %WINDIR%\* allows all files in the Windows Directory.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d4ecadb-c54e-5da1-03ae-1301a35ef64a
* Version Independent ID: 69d28732-f557-9ae1-cec4-594a2ec097a2
* Content: [Select the types of rules to create  (Windows 10)](https://docs.microsoft.com/en-gb/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment]
@Air-Git. Sir, I am a little bit confused, after reading your comments. Half sentences i understood clearly

**Comment by Air-Git** [comment]
The document needs to be reviewed by someone who knows how the WDAC feature works.

**Comment by jsuther1974** [comment]
I have submitted changes to the topic to add clarity. Once that is merged in, the issue should be resolved based on my understanding of the concerns @air-git is raising.

**Comment by jvsam** [comment]
Thanks @jsuther1974. Do you have the PR or the commit so we can track and link it to this issue?

**Comment by jvsam** [comment]
@officedocsbot assign @jsuther1974

**Comment by jsuther1974** [comment]
@jvsam - https://github.com/MicrosoftDocs/windows-docs-pr/pull/1487

**Comment by jvsam** [comment]
Thank you @jsuther1974 for promptly updating the doc.

**Comment by jvsam** [comment]
Hi @Air-Git, kindly review the updates made on the doc. They're already live. 

Thank you again for your feedback and in your continuous effort to make the docs better for users.

**Comment by jvsam** [comment]
@officedocsbot close
