### ISSUE TITLE
This document confuses two distinct things

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#5285]
"FilePath" is a new value for the "Level" parameter of the New-CIPolicy cmdlet.
"FilePathRule" is a new parameter for the New-CIPolicyRule cmdlet.
The text on usage, wildcards, macros, belongs to New-CIPolicyRule and not to New-CIPolicy. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94cfbb2d-7562-dd7a-ce15-a3e30ad88544
* Version Independent ID: 535b2189-c7c3-ae3c-b939-62bfdaf8d28d
* Content: [Windows Defender Application Control path-based rules (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/create-path-based-rules)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/create-path-based-rules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/create-path-based-rules.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @jsuther1974, will your updates on #5285 address the issues raised here as well?

**Comment by jsuther1974** [comment]
@jvsam - yes, it does

**Comment by jvsam** [comment]
Hi @Air-Git, similar to the other issue you've opened (see: #5284), this doc has been updated and the doc set reorganized. 

Please continue to send your feedback and suggestions to improve the quality of the Microsoft documentation through the doc's *feedback feature*.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
