### ISSUE TITLE
Select the source of Group IDs

### ISSUE THREAD

**Issue by martinkupka** [MicrosoftDocs/windows-itpro-docs#5287]
Option 5 (AAD) is missing from the description. From this reference: https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization#set-up-delivery-optimization

"Starting with Windows 10, version 1903, you can use the Azure Active Directory (AAD) Tenant ID as a means to define groups. To do this set the value for DOGroupIdSource to its new maximum value of 5."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df445cda-3b0a-2ad7-e3cc-23e159013530
* Version Independent ID: a6bb5f97-d350-f7b7-77f7-b0093322289d
* Content: [Delivery Optimization reference](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization-reference#feedback)
* Content Source: [windows/deployment/update/waas-delivery-optimization-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-delivery-optimization-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jaimeo** [comment]
Fixed.

**Comment by jvsam** [comment]
Hi @martinkupka, this documentation has been updated by @jaimeo. We will now close this issue since it's already resolved. Thank you so much for your feedback.

**Comment by jvsam** [comment]
@officedocsbot close
