### ISSUE TITLE
DeliveryOptimization/DOGroupIdSource

### ISSUE THREAD

**Issue by martinkupka** [MicrosoftDocs/windows-itpro-docs#5288]
Option 5 (AAD) is missing from the description. From this reference: https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization#set-up-delivery-optimization

"Starting with Windows 10, version 1903, you can use the Azure Active Directory (AAD) Tenant ID as a means to define groups. To do this set the value for DOGroupIdSource to its new maximum value of 5."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06745768-affe-c86a-2da6-7bd694e847c9
* Version Independent ID: e832ada1-5f0c-7809-b8a1-bb91cadb6975
* Content: [Policy CSP - DeliveryOptimization](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-deliveryoptimization#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-deliveryoptimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-deliveryoptimization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for creating this issue (and #5287) @martinkupka. 

Hi @ManikaDhiman, kindly confirm the update for the *DOGroupIdSource* policy. Thank you.

> Starting with Windows 10, version 1903, you can use the Azure Active Directory (AAD) Tenant ID as a means to define groups. To do this set the value for DOGroupIdSource to its new maximum value of 5.

**Comment by jvsam** [comment]
@officedocsbot assign @ManikaDhiman

**Comment by jvsam** [comment]
Hi again @ManikaDhiman, if you have time, kindly look into the issue raised by the user. Thank you.

**Comment by ManikaDhiman** [comment]
Hi @jvsam, thanks for the follow up. I have reached out to the product team to provide update on this. I will update the doc as soon as I hear from them. Thanks!

**Comment by jvsam** [comment]
Thank you so much @ManikaDhiman!

**Comment by ManikaDhiman** [comment]
Hi @jvsam, option 5 is now included in the DeliveryOptimization/DOGroupIdSource policy description. Updates are available in the live doc. Hope this helps. Thanks!

**Comment by jvsam** [comment]
Hello @martinkupka thank you again for your feedback. We will now close this issue since it has been resolved and the documentation has been updated. Please continue to send your feedback and suggestions to help improve the quality of the technical documentation of Microsoft Docs.

Thank you @ManikaDhiman for your assistance!

**Comment by jvsam** [comment]
@officedocsbot close
