### ISSUE TITLE
Is "Network Device Enrollment Service" correct for the exposed scenarios?

### ISSUE THREAD

**Issue by cmdrr** [MicrosoftDocs/windows-itpro-docs#5293]
Per Microsoft documentation in https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/hh831740(v=ws.11) "Network Device Enrollment Service" is for "allowing routers and other network devices that do not have domain accounts to obtain certificates.". 

Since we're speaking about client computer that will be either hybrid joined of no members of the domain at all, I understand "Certificate Enrollment Web Service" and the "Certificate Enrollment Policy Web Service" will be a clearer requirement than NDES.

Since both services "enable policy-based certificate enrollment for
- domain member computers not connected to the domain
- computers that are not domain members"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e5f5f1-16cf-57e2-bdfc-b090d90437b1
* Version Independent ID: 1662c47f-12cb-147d-25f0-dee98b6c7722
* Content: [Windows Hello for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-identity-verification.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-identity-verification.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mypil** [comment]
@cmdrr - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by cmdrr** [comment]
Hello, seems that for SSO; NDES with an application proxy is needed as described here: https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert#prepare-the-network-device-enrollment-services-ndes-service-account ; so seems that the initial table it's ok as currently redacted.

**Comment by j0rt3g4** [comment]
Actually it is Ok as currently redacted.

We stand for hybrid (Azure AD and on-premises AD), the way to go is NDES instead of "Certificate Enrollment Web Service" and the "Certificate Enrollment Policy Web Service" for *domain member computers that are not connected to the domain* and *computers that are not domain members*.

Not sure if this comment fits your query. if not, please let us know @cmdrr

**Comment by mypil** [comment]
@cmdrr - From our understanding, the issue you raised has been answered by j0rt3g4. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
