### ISSUE TITLE
automated device registration

### ISSUE THREAD

**Issue by rrsit** [MicrosoftDocs/windows-itpro-docs#5295]
after setting up the device registration service and the AD FS server including all certificates and dns names, devices can be joined manually with "DESREGCMD /debug" in a SYSTEM context. however devices do not auto-register themselves.

after a bit of digging i found that there is a group policy called
Computer Configuration -&gt; Policies -&gt; Administrative Templates -&gt; Windows Components -&gt; Device Registration -&gt; "Register Domain Joined Computers As Devices"
if this is set to Enabled, the registration happens automatically.

is this the intended way to go? because the description of the GPO setting refers to Azure AD ("When you enable this setting, domain joined computers automatically and silently get registered as devices with Azure Active Directory.") and we are doing a on-premise installation here. 
if yes, it might be helpful to add information to the article and save other people some time figuring out why no registration happens.... ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b063e00b-84e5-9da7-2229-e0e24da3b877
* Version Independent ID: da9f4867-2aa3-aefa-1603-ddb2ab1ed624
* Content: [Prepare and Deploy Windows Server 2016 Active Directory Federation Services (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mypil** [comment]
@rrsit - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@rrsit - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/1bdd21aaeb27926da6d2616325c521a446ddb987. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
