### ISSUE TITLE
O365 xml not working

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/windows-itpro-docs#5296]
Seems like the latest O365 version is not WIP protected, even if you apply the "recommended app" from Intune or the ZIP applocker file from this article. I don't see the wallet on Office apps and the EDP event viewer categorize Office apps as NULL instead of protected.
Has anything changed lately in O365 versionning?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ed0150-0172-f3ad-3c7f-3a7141efbe64
* Version Independent ID: 6a978d2b-a0ff-1052-ce00-06f02f30cfa1
* Content: [List of enlightened Microsoft apps for use with Windows Information Protection (WIP) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@Martony78 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@DulceMontemayor - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by HolgerRadecke** [comment]
I have the same issue here. Any updates on this matter?
@mypil  @DulceMontemayor 

cc: @Martony78

**Comment by HolgerRadecke** [comment]
@Martony78  
It seems, that I had a same same but different problem.
I opened a ticket last friday and got the result yesterday. Currently, there is a bug with WIP via SCCM with co-managed clients.
So, the XML didn't work **and** there is a bug in SCCM which is said to be fixed with 1910
What I can recommend as a workaround is to create your own AppLocker policy. That takes some time but you are in full control
cc: @DulceMontemayor @mypil @kenwith

**Comment by mypil** [comment]
@Martony78 @HolgerRadecke - Have you already tried to contact MS support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP? 

Please let me know what is the outcome and if it is something that can be called out in the docs.

**Comment by mypil** [comment]
@Martony78 - Please try the workaround shared by @HolgerRadecke or if you still encounter some technical issues then it would be best for you to open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products so they can help resolve your technical concern.

I will close this issue now. If in case you find that it is a documentation error, feel free to comment back here and let us know which portion of the doc you suggest to be edited so we can help fix it. 

Thank you!

**Comment by Martony78** [comment]
So ask me to apply a workaround provided by an end user instead of fixing the issue? This is a workaround, not a resolution, you shouldn't have closed the ticket until this problem is really fixed.

**Comment by HolgerRadecke** [comment]
hi @Martony78  - do you still have the same issue with the currently available Office-365-ProPlus-1810-allowed.xml and Recommended-Denied-Office-365-ProPlus-1810.xml ?
Are your devices enrolled or do you use MAM policies?
