### ISSUE TITLE
Spelling Mistakes

### ISSUE THREAD

**Issue by helloitsliam** [MicrosoftDocs/windows-itpro-docs#5298]
There are spelling mistakes in the table:

"preprare" should be "prepare"
"softeware" should be "software"
"potect" should be "protect"
"acces" should be "access"

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80883345-8679-79e3-a851-4143d4a4e3e7
* Version Independent ID: d1772c97-6839-51d3-f1ef-33ee9ed27d63
* Content: [Configure attack surface reduction](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-attack-surface-reduction#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-attack-surface-reduction.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Thank you for pointing out those typos. The page is fairly short too, so it should be a simple task to review and correct the bad spelling.

**Comment by mypil** [comment]
@helloitsliam - PR #5301  has been created by illfated to fix and close this issue once the PR is merged.

Thank you and we appreciate your contribution to make the docs better! 

@illfated - Thanks for creating the PR to fix the typo errors.

**Comment by helloitsliam** [comment]
Thank you to you guys for updating it so quickly. :-)
