### ISSUE TITLE
Missing Surface Pro 7 and Surface Laptop 3

### ISSUE THREAD

**Issue by asjimene** [MicrosoftDocs/windows-itpro-docs#5299]
Entries for the Surface Pro 7 and AMD and Intel variants of the Surface Laptop 3 are missing. This is needed especially for the Surface Laptop 3 because it seems as the Model for both variants is the same, with the only difference being the SKU (and there are specific drivers for each variant).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84214a7c-c350-e7df-b096-8509be06d4fe
* Version Independent ID: a07d3fed-001f-4230-c5f7-c3a6caad3223
* Content: [System SKU reference (Surface)](https://docs.microsoft.com/en-us/surface/surface-system-sku-reference#feedback)
* Content Source: [devices/surface/surface-system-sku-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-system-sku-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by asjimene** [comment]
Based on the driver MSIs, I found the following:
Intel Surface Laptop 3:
- Surface_Laptop_3_1867:1868
- Surface_Laptop_3_1872
AMD Surface Laptop 3:
- Surface_Laptop_3_1873

**Comment by mypil** [comment]
@asjimene  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by ktapics** [comment]
Also Surface Pro 4 is missing for those of us that still have old hardware.

**Comment by ktapics** [comment]
And Book 1 and Pro 3 are missing.

**Comment by mypil** [comment]
@asjimene - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/d0b1761e7307ea7d520b85bb576cba375e4ec45d. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
