### ISSUE TITLE
Localization Priority + Author metadata mixed up.

### ISSUE THREAD

**Issue by TinaMcN** [MicrosoftDocs/windows-itpro-docs#5300]
Right-click on the page to View Source.
Notice this metadata which seems to be a mix up between the author and loc priority metadata.
<meta name="ms.localizationprioauthor" content="jaimeo" />

Localization metadata should be in the following format (value is usually medium or high)
<meta name="ms.localizationpriority" content="medium" />

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f76d96ac-5343-20e2-9d99-9c1cea7ccc2e
* Version Independent ID: a95c9b39-4a66-d726-4404-de5af60ac982
* Content: [Windows Update error code list by component](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-error-reference#feedback)
* Content Source: [windows/deployment/update/windows-update-error-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-error-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@TinaMcN  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@jaimeo - The metadata shows the below info in line 9.  What should be the localization_priority for this doc?  Please let us know so we can create a PR to fix this. Thank you.

![image](https://user-images.githubusercontent.com/47188252/68078919-4b281180-fe1b-11e9-8273-6069db78b5a6.png)

**Comment by jaimeo** [comment]
Whatever the standard priority is. I think it's "normal"?

**Comment by TinaMcN** [comment]
For Windows content the value for standard priority is "medium".    Office content has other values (e.g. Normal) - I'm working to get that standardized soon.

**Comment by mypil** [comment]
@TinaMcN - I created PR #5356 to fix and close this issue once it is merged.

Thank you for your contribution to make the docs better! We greatly appreciate it!

**Comment by jaimeo** [comment]
Ah I see! I didn’t know the standard was different for Office vs. Windows. “Medium” is fine—whatever the baseline is.

vv
J.O.
