### ISSUE TITLE
Update for Server 2019 

### ISSUE THREAD

**Issue by ChrisFryer** [MicrosoftDocs/windows-itpro-docs#5303]
Please update to include Server 2019
Thank you :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f02c58f-4575-3991-8bee-ccea6c3b3d34
* Version Independent ID: 6b3f5a69-1425-8b36-9e7a-b965fc70a164
* Content: [Requirements to use AppLocker (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/requirements-to-use-applocker#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/applocker/requirements-to-use-applocker.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/applocker/requirements-to-use-applocker.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@ChrisFryer  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@mjcaparas - Can you please share your insights on this issue?

Thank you.

**Comment by mjcaparas** [comment]
@ChrisFryer Do you mind providing more details on where server 2019 information is needed?

I see that it's on the table - first column second row.


Windows Server 2019Windows Server 2016Windows Server 2012 R2Windows Server 2012 | Yes | Yes | Packaged appsExecutableWindows InstallerScriptDLL
-- | -- | -- | --

**Comment by illfated** [comment]
@ChrisFryer , @mjcaparas : Please note that the updated information was added 7 days ago (December 6, 2019) in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/95e511e41b9a2b92b4118a21462e454e748a492b based on the PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5624 .

I don't have any information whether or not this change was promoted by this issue ticket or not.

**Comment by mypil** [comment]
@ChrisFryer - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
