### ISSUE TITLE
could you provide the GPO backup to import settings (instead of doing a GPO manually)?

### ISSUE THREAD

**Issue by rafalfitt** [MicrosoftDocs/windows-itpro-docs#5307]
similar to security baseline .ZIP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cb63b99-28cc-14d5-69d9-45fd01407e7f
* Version Independent ID: 676cbbfe-034f-f837-bf4c-a4587a8017f0
* Content: [Level 1 enterprise basic security configuration](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-security-configuration-framework/level-1-enterprise-basic-security)
* Content Source: [windows/security/threat-protection/windows-security-configuration-framework/level-1-enterprise-basic-security.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-security-configuration-framework/level-1-enterprise-basic-security.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @appcompatguy
* Microsoft Alias: **cjacks**

**Comment by mypil** [comment]
@rafalfitt  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by appcompatguy** [comment]
Hi @rafalfitt - we are definitely looking to simplify the deployment! This initial release is to gather feedback on where we've drawn up the levels and to collaborate with the community on getting the right definitions for each. There's been a lot of confusion by it being in docs, so we're in the process of moving back to pure GitHub to remove that confusion. But given the response, it looks like we should look at going faster!

**Comment by rafalfitt** [comment]
Hi @appcompatguy @mypil I am a (semi) patient/lazy guy, but I have a feeling that the wait is over and I need to implement you guidance ;-) so a ready-made GPOs (like MS security baselines) would be nice to have ;-)

**Comment by RAJU2529** [comment]
@rafalfitt. Sir Microsoft releases  administrative templates for every windows 10 updates like
1809, 1903.
But all the .admx , .adml files  are comes with unmodified settings

**Comment by mypil** [comment]
@rafalfitt - From our understanding, the issue you raised has been answered by appcompatguy. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
