### ISSUE TITLE
DRS Service Account object creation quota reached

### ISSUE THREAD

**Issue by kylecweeks** [MicrosoftDocs/windows-itpro-docs#5318]
As per the documentation to enable the device registration service using the gMSA - this account quickly reached the default 10K object limit of Active Directory device creation. This needs to be noted, and a solution to add the ntds custom quota limit added. Sadly, dsadd was still the easiest way to quickly add a quota to resole registration issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b063e00b-84e5-9da7-2229-e0e24da3b877
* Version Independent ID: da9f4867-2aa3-aefa-1603-ddb2ab1ed624
* Content: [Prepare and Deploy Windows Server 2016 Active Directory Federation Services (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by VLG17** [comment]
@kylecweeks Could you please share a source for "default 10K object limit of Active Directory device creation quota". I could not find this unfortunately.

**Comment by kylecweeks** [comment]
Hi,

Apologies, perhaps this is not actually set by default. The NTDS Quota container as documented here

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/d55ca655-109b-4175-902a-3e9d60833012

Which if set, you would need to modify the quota on the gMSA for doing device registration since it creates objects in Active Directory. Using dsadd was the only way I found to be able to set this for gMSAs.

**Comment by e0i** [comment]
Closing via #8058.
