### ISSUE TITLE
How often is data exported to Storage?

### ISSUE THREAD

**Issue by grnadav** [MicrosoftDocs/windows-itpro-docs#5321]
Hi
What is the frequency that data is exported to the Storage Account?
Or does it export on every new alert? if so, at what delay?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d7c9a2b-c6a2-0c0b-3718-a9c0d2cbbf05
* Version Independent ID: 86974870-2d23-e7e0-e7fb-9a58e4957b00
* Content: [Stream Microsoft Defender Advanced Threat Protection events.](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/raw-data-export-storage#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/raw-data-export-storage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/raw-data-export-storage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
I think at least every  15days , i simply guessed

**Comment by grnadav** [comment]
I think that guess is not very accurate... I've seen data exported within minutes. I was hoping to get a more concrete, official, response on how many minutes exactly.

**Comment by e0i** [comment]
@grnadav 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
