### ISSUE TITLE
No further updates.. ?

### ISSUE THREAD

**Issue by MatthewCKelly** [MicrosoftDocs/windows-itpro-docs#5342]
This page lists updates to December 2018 however nothing since ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193e0a5f-0323-3728-23d4-f96bbeaf85e0
* Version Independent ID: e1cefa3a-1841-e6c3-3752-f1086af5ba7e
* Content: [Change history for Client management (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/change-history-for-client-management#feedback)
* Content Source: [windows/client-management/change-history-for-client-management.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/change-history-for-client-management.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @MatthewCKelly, thanks for the question. Do you have a specific content request or is there any information that you believe is missing from this documentation so we can submit your feedback for review? We always strive to improve the quality of the technical documentation of Microsoft Docs so if you have suggestions related to this documentation (or any docs in the *Client management* doc set) or ideas to make it better for users, please let us know here and we will submit them for review. We are not aware of the Microsoft authors' priority backlog, but rest assured that they are doing their best. 

Also, Microsoft put in place this feedback system to also allow user contributions and feedback. If you want to be a contributor, please check the [Microsoft Docs contributor guide](https://docs.microsoft.com/en-us/contribute/). Thank you for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hi again @mattatmsft we didn't hear from you. We hope the information we've provided helped. We will now close this issue, however, feel free to re-open if you have specific suggestions related to this documentation or ideas to make it better for users. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
