### ISSUE TITLE
Azure KMS Activation?

### ISSUE THREAD

**Issue by BRobertsGPH** [MicrosoftDocs/windows-itpro-docs#5346]
I'm trying to understand this sentance:

" Alternatively, a KMS activation server on your corporate network can be used if you have configured a private connection, such as ExpressRoute or VPN Gateway"

Are you saying there's an Azure KMS server we can use (that has the subscription W10 licenses loaded) that we can use the activate Active Directory joined machines over a VPN?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c34b8c-44b9-b3d3-9894-5a7fd68e2309
* Version Independent ID: ea643c8f-e92d-b90e-4e90-f338cea39e79
* Content: [Configure VDA for Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/vda-subscription-activation#feedback)
* Content Source: [windows/deployment/vda-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/vda-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@BRobertsGPH  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by greg-lindsay** [comment]
No this is saying that if you have a VPN connection to your corporate network where there is a KMS server, that could be used for activation.

**Comment by BRobertsGPH** [comment]
That doesn't make sense? Why would you do that in scenario 3? Do you need a KMS loaded with W10 VL for the GVLK to activate?

**Comment by illfated** [comment]
Just as a side note: the link (https://www.microsoft.com/CloudandHosting/licensing_sca.aspx) in the text
> [ ... ]  or the hoster is not an authorized [QMTH](https://www.microsoft.com/CloudandHosting/licensing_sca.aspx) partner.

is broken. The resulting page says:
>We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available.

**Comment by greg-lindsay** [comment]
@BRobertsGPH you would activate this way if you happened to have ExpressRoute configured to your corporate network and a KMS server on that network, and no other method for activation was available. Typically this wouldn't be an ideal method, but I'm just saying this is possible. I think you could also just activate manually on each VM.

The link appears to not be properly localized. I'll have to go in and add the "en-us" into it.

https://www.microsoft.com/en-us/CloudandHosting/licensing_sca.aspx

**Comment by BRobertsGPH** [comment]
There's a step missing in scenario 3. There needs to be a way for W10 subcription owners to access and activate a W10 KMS key on our own KMS server.
At the moment the only way around it is to purchase W10 Ent license with SA?

**Comment by greg-lindsay** [comment]
Managing a KMS server isn't within the scope of this topic. We are just saying that KMS is something that could be used if you have it available and you can't use the preferred methods which are described in scenarios 1 and 2.  Options in scenario 3 are limited. This is one reason why the options in the other scenarios were created, but they weren't back-ported to older versions of Windows.

**Comment by greg-lindsay** [comment]
I will ping the product team and find out what the ideal method is for someone in scenario 3, and try to spell that out in the documentation so it isn't as vague.

**Comment by BRobertsGPH** [comment]
Thanks Greg, that's a huge help. Otherwise I'd argue that (in the specific conext of Subscription license VDA activation) Scenario 3 isn't possible/achievable. You would need volume licenses which renders the subscription licenses moot - and Scenrio 3 just becomes "Activating a W10 VDA with volume licensed KMS" which doesn't need to be on this page.

**Comment by greg-lindsay** [comment]
@BRobertsGPH Are you able to use Active Directory based activation?  If not, what issues are there?

**Comment by BRobertsGPH** [comment]
Active Directory-Based Activation still required a KMS host key.

**Comment by greg-lindsay** [comment]
I've sent your question back again, but no reply yet. Also I'm going to be out of the office for a while so I've asked the activation experts to reply directly here on this thread.

**Comment by mypil** [comment]
@greg-lindsay - Do you have any updates on this? Thanks.

**Comment by greg-lindsay** [comment]
I asked the product team to take over answering this thread while I was out of the office in November, but they didn't answer.  From what I can gather at this point, there simply isn't a good option if you are running Windows 10 version 1703 or 1709.  

I'll ping the product team yet again and ask them if I should change this article to say that 1803 is required rather than 1703 because of the activation issues with 1703 and 1709.

**Comment by greg-lindsay** [comment]
@BRobertsGPH I am sorry this issue has dragged on. 

Can you clarify exactly what puts you into scenario 3? Are you using Azure with Windows 10 version 1703 or 1709?  Or is it not Azure?  I'm trying to understand the exact issue so I can get a better answer for you.

**Comment by mypil** [comment]
@BRobertsGPH - We would like to follow up. Can you please respond to the query of greg-lindsay?

Thank you.

**Comment by BRobertsGPH** [comment]
Hi @greg-lindsay and @mypil we're running 1903 in our own private cloud - so not a QMTH.

**Comment by greg-lindsay** [comment]
Hi, sorry to have let this issue languish so long. I have gotten some additional information recently and I will update the article.  Activation only requires that you are able to access the KMS host in your region. https://docs.microsoft.com/en-us/azure/virtual-machines/troubleshooting/troubleshoot-activation-problems

**Comment by greg-lindsay** [comment]
I'm updating the note in this article today to say that you need to point to a KMS server in Azure.
