### ISSUE TITLE
Education and Server versions of Windows

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/windows-itpro-docs#535]
on "Getting Started with App-V for Windows 10". The opening descriptions on this topic (and possibly title) need to be expanded to cover additional versions of the operating system.  To be honest I not even sure if the right terms would be editions or skus, but this should get worked in to clarify where the client components exist.  Also use on the server (RDS/RDMI) operating system should be included here.

**Comment by shortpatti** [comment]
@nickbrower  -- Can you take a look at this issue?

**Comment by mypil** [comment]
@nickbrower - We would like to follow up on this. Do you have any updates? 

Thanks.

**Comment by mypil** [comment]
@TimMangan - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by TimMangan** [comment]
I think it was this one: https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/appv-v5/creating-and-managing-app-v-51-virtualized-applications.md 

I see there is a 50 version of it also.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by nenonix** [comment]
@TimMangan  We appreciate the feedback. It appears to me you are referring to https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/app-v/appv-getting-started.md  (and possibly https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/appv-v5/getting-started-with-app-v-50--rtm) but I do not understand how you would like the content to be changed.  Could you suggest any specific edits that could provide more clarity, or could you assist me by pointing out any errors that need to addressed?

**Comment by mypil** [comment]
@TimMangan - can you please assist to give updates on the clarification question from nenonix? Thank you.

**Comment by TimMangan** [comment]
I took a fresh look today; the docs seem to be different from when I posted this a year ago, but the concept behind the issue is the same..  The basic issue is that it seems like everything under https://github.com/MicrosoftDocs/windows-itpro-docs/tree/master/windows/application-management/app-v is now only referring to Windows 10.  The product is also supported on Windows 7 and server operating systems (especially with RDS/RDMI) [and I guess WVD in the future].  

So it might start with https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/app-v/appv-about-appv.md which appears to be likely starting point, but there are probably many articles only talking about Windows 10.

**Comment by nenonix** [comment]
@TimMangan I see your point but unfortunately we don't have the power to make those kind of widespread changes to the content. We can bring your point to the attention of the authors, but does this article not deal with your concern ito the other OS versions: https://docs.microsoft.com/microsoft-desktop-optimization-pack/index ?

**Comment by mypil** [comment]
@TimMangan - We would like to follow up with you. Please assist to check and respond to the query from nenonix. Thank you.

**Comment by TimMangan** [comment]
The article mentioned covers the options.  My point was just that the obvious starting point for someone might lead them to conclude it is only a Windows 10 thing. 

I was asked by the MVP program to participate in a documentation improvement exercise over a year ago.  This process doesn't seem to be worth my time or yours.  Drop it.

**Comment by mypil** [comment]
@TimMangan - We apologize and understand your frustration, our work is restricted to making specific changes to docs so your suggestion might get more traction in the User Voice channel.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**

You might find others have made a similar request that you can add to, or you can open a new one.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
