### ISSUE TITLE
Latest Servicing Stack Updates target page missing again

### ISSUE THREAD

**Issue by nascar3000** [MicrosoftDocs/windows-itpro-docs#5350]
https://portal.msrc.microsoft.com/security-guidance/advisory/ADV990001 link rediredcts to 
https://portal.msrc.microsoft.com/en-us/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b706f0af-d504-a8ca-7c38-b8bb9283bfad
* Version Independent ID: 14f31acf-9f47-59a6-269f-62ab249fe560
* Content: [Servicing stack updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates)
* Content Source: [windows/deployment/update/servicing-stack-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/servicing-stack-updates.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mypil** [comment]
@nascar3000  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by illfated** [comment]
@nascar3000 : Your observation is correct, but it could look like that change is by design, because of the javascript button on that page.
That button loads the page https://portal.msrc.microsoft.com/en-us/security-guidance , which is a list of 1362 items.
That is more or less what the the link text indicates:

> ### Latest servicing stack updates

Do we have any indications that the link should go directly to a specific document?

**Comment by mypil** [comment]
@jaimeo - Can you please share your insights on this issue?

Thank you.

**Comment by nascar3000** [comment]
@illfated "You can find a list of servicing stack updates at Latest servicing stack updates." that's the note in the document, I was using this one daily to check SSU's for the different OS so don't have to be tracked if the last one I used superseded or not.

 The previous link was https://portal.msrc.microsoft.com/security-guidance/advisory/ADV990001 and the page was showing a table with only OS name version and SSU KB number with a link to KB page. My guess sec guys removed/moved this page so site redirecting to home when can't find the ADV990001.

**Comment by jaimeo** [comment]
Checking with a contact who can advise.

**Comment by get-itips** [comment]
What is not working here is the localization redirection

this link works
https://portal.msrc.microsoft.com/en-us/security-guidance/advisory/ADV990001

this, present in the article, does not redirect correctly

https://portal.msrc.microsoft.com/security-guidance/advisory/ADV990001

@mypil do you want me to change the link including with the working _en-us_ version even though we always prefer not to do that? at least until the team fixes that redirection.

**Comment by jaimeo** [comment]
@get-itips: yes go ahead and fix that link. Could you also please show us where this anchor text (the version w/o en-us) is appearing? We seem to still have something to fix on the back end and we need to see where that appears to fix it.

**Comment by get-itips** [comment]
Hello @jaimeo created the pr, did a quick search in the repo and it seems it only appeared on this article.

**Comment by jaimeo** [comment]
which article?

**Comment by illfated** [comment]
Document info from the ticket opening comment links https://docs.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates
***
**Document Details**

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

- ID: b706f0af-d504-a8ca-7c38-b8bb9283bfad
- Version Independent ID: 14f31acf-9f47-59a6-269f-62ab249fe560
- Content: [Servicing stack updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates)
- Content Source: [windows/deployment/update/servicing-stack-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/servicing-stack-updates.md)

**Comment by mypil** [comment]
@nascar3000 - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/01e588d16a2a80b496874e3d96957b583b0967b9. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
