### ISSUE TITLE
Text in an image

### ISSUE THREAD

**Issue by tmlyon** [MicrosoftDocs/windows-itpro-docs#5354]
The image for Cortana includes the text "Hey Cortana" which doesn't get localized correctly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f29d313-070b-df7e-7a46-a175af7d9f45
* Version Independent ID: 53298953-2745-3b52-7db9-8322306be1a8
* Content: [Use your voice with HoloLens](https://docs.microsoft.com/en-us/hololens/hololens-cortana?source=docs)
* Content Source: [devices/hololens/hololens-cortana.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/hololens-cortana.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @v-miegge
* Microsoft Alias: **v-miegge**

**Comment by mypil** [comment]
@tmlyon  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by illfated** [comment]
Very good point. Those words are part of the image, so no separate text to edit or manipulate there.
Looks like that page needs a language filter for individual images, specific to the relevant translation.

**Comment by mypil** [comment]
@TinaMcN - Can you please share your insights on this issue? This appears to be a translation/localization issue but it is on the image within the doc (please see below image). What do you recommend so the image within the doc will be translated?

![image](https://user-images.githubusercontent.com/47188252/68206438-a4ed2f00-0007-11ea-9532-a6bc477b103c.png)

Thank you.

cc: @kenwith

**Comment by illfated** [comment]
Hmm, well now. I forgot another possible scenario. Say that the image gets cut right above the text and the text is replaced by a separate text field, then it would be possible to expose the text to translation (or make sure that the text is translated like the software is translated).

**Comment by TinaMcN** [comment]
We currently don't localize images for Windows/Hololens content.   I'm considering to enable that but it will have impact on all Windows content and will require budget approval.   In the meantime for the Cortana image it would be ideal if the "Hey Cortana" text could be separated from the Cortana logo.

**Comment by illfated** [comment]
Fair enough, thank you for the explanation. 
@tmlyon , does the comment above answer your reported issue sufficiently?

**Comment by tmlyon** [comment]
Fyi @scooley

**Comment by mypil** [comment]
@tmlyon - From our understanding, the issue you raised has been answered by TinaMcN. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
