### ISSUE TITLE
MBAM group description needs clarification

### ISSUE THREAD

**Issue by jason4tw** [MicrosoftDocs/windows-itpro-docs#536]
For https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/planning-for-mbam-25-groups-and-accounts:

The description for the "Reports read-only domain access group" and the "MBAM Report Users access group" is nearly identical above; both say "whose members have read-only access to the reports in the ... Administration and Monitoring Website." If you are going to have two groups, they should have different descriptions. It should also be clarified what the ramifications are (if any) for using the same domain group for both.

**Comment by shortpatti** [comment]
@jason4tw -- I've reached out the someone for clarification 👍
