### ISSUE TITLE
"Do not connect to any Windows Update Internet locations" please add a note: this policy disables Windows Store download

### ISSUE THREAD

**Issue by carloreggiani** [MicrosoftDocs/windows-itpro-docs#5361]
Please add any information about how to configure a intranet WSUS service to distribute Windows Updates without disable Windows Store download functionality!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efb8dfd-971e-7257-f8b7-f80843989eb8
* Version Independent ID: d7808728-bb89-a06e-a103-ec1c74682f64
* Content: [Manage additional Windows Update settings (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-wu-settings#do-not-connect-to-any-windows-update-internet-locations)
* Content Source: [windows/deployment/update/waas-wu-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-wu-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by Typhoon87** [comment]
Also in 1809+ it seems to prevent features on demand from working now that they are not in WSUS anymore :(

**Comment by joinimran** [comment]
@carloreggiani - Thank you for your query. Please note that you can enable WSUS updates and it and enable the policy Turn off Access to all Windows Update Features. This information is also available in the document here at Turn off Access to all Windows Update Features.

Thanks.

@e0i  FYI Please.

**Comment by carloreggiani** [comment]
Sorry @joinimran, not sure to understand: I'm still looking for any viable policy to enable Microsoft Store (Business version in my case) downloads AND control the client update via our internal WSUS service, not from a direct internet connection from each client.

I opened also support tickets regarding this problem, it seems not possible to disable internet download for windows updates AND keep working any Store download. In my opinion it is a big BUG, but really, let me know if there is any other configuration possible.

Thanks

Carlo

**Comment by jaimeo** [comment]
@arcarley would you have any helpful info for this issue?

**Comment by itsrlyAria** [comment]
Hi @carloreggiani have you tried simply setting ONLY specify a WSUS server? (Make sure you don't configure deferrals, disable dual scan or disable all Windows Update UX features). Then you should be scanning WSUS and getting Store updates (which do have their own set of policies as well you should reference)
