### ISSUE TITLE
Windows 10 version

### ISSUE THREAD

**Issue by gerrynicol** [MicrosoftDocs/windows-itpro-docs#5362]
Hi there,

Can you confirm the Windows 10 version required for self-deploying mode. If the vendor ships the device with windows 10 pro will this work? Or does it need to be Windows 10 Enterprise version 1903?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6867cc8c-868d-d472-8aa5-1ed5b94ced2c
* Version Independent ID: 6822e12d-7474-9e49-1e8b-88f7eec3b22c
* Content: [Windows Autopilot Self-Deploying mode](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/self-deploying)
* Content Source: [windows/deployment/windows-autopilot/self-deploying.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/self-deploying.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Looks like nobody has found time to answer this question in almost 4 weeks, so maybe I am posting in vain. I do not have access to a relevant scenario with Enterprise subscription or Azure Active Directory, but after reading the page this question was posted from, I am tempted to turn the question on its head:


**Which Windows 10 editions will be accepted in your Azure Active Directory organization structure as a self-adding member device?**

**Comment by hambranch** [comment]
I've not tested with Enterprise, but Win10Pro 1903 works with both self-deploying and user driven.

**Comment by illfated** [comment]
> I've not tested with Enterprise, but Win10Pro 1903 works with both self-deploying and user driven.

Thank you for posting your reply. I presume @gerrynicol is looking for an answer from one of the Microsoft team members or an authoritative addition to the documentation.
