### ISSUE TITLE
Mauvaise information dans les exemples pour l'aide

### ISSUE THREAD

**Issue by ggbce** [MicrosoftDocs/windows-itpro-docs#5365]
Dans votre exemple pour obtenir de l'aide, on voit "get-help get-VamtProduct -all"... mais cette commande Powershell est invalide, nous devrions plutôt retrouver les commandes :

Get-Help Get-VamtProduct -examples (Exemples)
Get-Help Get-VamtProduct -detailed (Informations supplémentaires)
Get-Help Get-VamtProduct -full (Informations techniques complètes)
Get-Help Get-VamtProduct -online (Aide en ligne)

La commande Get-Help Get-VamtProduct -all sous PowerShell 5.1 retourne le message d'erreur:

PS C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\VAMT3&gt; get-help get-vamtProduct -all
Get-Help : Impossible de trouver un paramètre correspondant au nom « all ».
Au caractère Ligne:1 : 26
+ get-help get-vamtProduct -all
+                          ~~~~
    + CategoryInfo          : InvalidArgument : (:) [Get-Help], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetHelpCommand

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: fd87fa3e-37e5-dfb4-2693-2892bc063f13
* Version Independent ID: de9cb0ae-bfc7-ddbe-5e9e-b4b2f960c361
* Content: [Utiliser VAMT dans Windows PowerShell (Windows 10)](https://docs.microsoft.com/fr-fr/windows/deployment/volume-activation/use-vamt-in-windows-powershell#pour-obtenir-de-laide-sur-les-cmdlets-powershell-vamt)
* Content Source: [windows/deployment/volume-activation/use-vamt-in-windows-powershell.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/volume-activation/use-vamt-in-windows-powershell.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
Il s'agit d'un problème connu lié à PowerShell. Veuillez faire le suivi de votre préoccupation via la [Communauté PowerShell](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Merci.
