### ISSUE TITLE
Documentation about interaction with Dual Scan

### ISSUE THREAD

**Issue by Typhoon87** [MicrosoftDocs/windows-itpro-docs#5367]
Currently I made the changes here however there is another GPO interaction I believe its "Do Not Connect with Any Windows Update Internet Locations" that does not seem to be documented, If I disable that I believe based on reading it could cause Windows to go to WU instead of WSUS for feature updates say 1709 to 1809. This is not desirable but I have 1809 machines that need RSAT.

Can you please add information disuccing how these interface and thier affect on how dual scan is impacted? Basically to ignore WU and WUFB and only look at WSUS/SCCM. 

The matrix created by the team at ask woody.com (https://www.askwoody.com/2018/the-unholy-mess-that-has-emerged-from-win10-wsus-dual-scan/)  of GPO's needed for the desired effect of WSUS/SCCM, WU, WBUF is so convoluted and has further changed in 1809. In addtion the most recent WSUS team blog post on the issue is now also outdated (https://blogs.technet.microsoft.com/wsus/2017/05/05/demystifying-dual-scan/) that its difficult to understand. Up through 1803 features on demand could be done through WSUS but now 1809+ they can't, this is a step backwards not forwards.

What can be done to better document this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d423c0e-fd99-9ad5-a11a-45237c2149fc
* Version Independent ID: f30e4101-7a8e-bfa9-a7c0-de7c36499cf5
* Content: [Windows 10 - How to make FoD and language packs available when you're using WSUS/SCCM](https://docs.microsoft.com/en-us/windows/deployment/update/fod-and-lang-packs)
* Content Source: [windows/deployment/update/fod-and-lang-packs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/fod-and-lang-packs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
I've forwarded this to the PM owner as a request to address these issues.

**Comment by Typhoon87** [comment]
Wow that was fast, I look forward to it.

**Comment by jaimeo** [comment]
I hope to get you actual answers and updates reasonably fast as well!

**Comment by Typhoon87** [comment]
So the first link I posted was actually pulled from a technet blog   https://blogs.technet.microsoft.com/swisspfe/2018/04/13/win10-updates-store-gpos-dualscandisabled-sup-wsus/

**Comment by Typhoon87** [comment]
Can I please ask why this was closed with no notes? The page I referenced has not been updated since March 2019 so it does not appear this doc was updated at all.
