### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/windows-itpro-docs#5374]
"Microsoft product updates (on/off): Computer configuration &gt; Administrative Templates &gt; Windows Components &gt; Windows Update &gt; Get updates for other Microsoft Products"

This is not in the latest ADMX

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2e692b1-8354-6b09-dfd7-252585320aac
* Version Independent ID: d1c99e74-66df-760a-39e9-23e5ed2bcfec
* Content: [Walkthrough use Group Policy to configure Windows Update for Business - Windows 10](https://docs.microsoft.com/en-us/windows/deployment/update/waas-wufb-group-policy)
* Content Source: [windows/deployment/update/waas-wufb-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-wufb-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment]
I think, configuration only configured running windows server 2019 OS  which should have Domain and the clients system running windows 10.
I have running windows 10 insider preview enterprise os with the standard alone computer. So the above configuration is not possible

**Comment by jaimeo** [comment]
Heard back from the PM, who reports that this setting is here: 

Computer Configuration > Administrative Templates > Windows Components > Windows Update > Configure Automatic Updates > Install updates for other Microsoft products. 

Confirmed this is present on my Win10 Ent device....

**Comment by OffColour** [comment]
@jaimeo thanks. Found it.
Small doc update required then by the look of it.

**Comment by e0i** [comment]
@OffColour Relevant updates will be performed accordingly. Thank you for providing feedback.

**Comment by jaimeo** [comment]
Fixed in https://github.com/MicrosoftDocs/windows-docs-pr/pull/1566
