### ISSUE TITLE
Is it possible to add 3rd Party Security Actions?

### ISSUE THREAD

**Issue by sravan-goud** [MicrosoftDocs/windows-itpro-docs#5375]
Hi,

Is it possible to add custom 3rd party "Security Actions" to graph API. If yes, could you please point me to the docs. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7522c47-aa38-2cf3-34b7-e8ad36dc80eb
* Version Independent ID: 6f26550f-0d21-479d-8479-b7bd563a2302
* Content: [Learn the Advanced hunting query language](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-query-language)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-query-language.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-query-language.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by lomayor** [comment]
Apologies for the late reply. Your org might need to look into a SIEM, such as Azure Sentinel, to make this happen. There are currently no third-party security events collected for advanced hunting.

https://docs.microsoft.com/en-us/azure/sentinel/connect-data-sources
