### ISSUE TITLE
Correct typo s/wndows/windows

### ISSUE THREAD

**Issue by PierrickV** [MicrosoftDocs/windows-itpro-docs#5376]
There is a typo on this page : 
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/b1a7d49de9d57ac60ce0eac79dc04421a711ca4a/windows/security/information-protection/kernel-dma-protection-for-thunderbolt.md

Windows is spelled *Wndows*

**Comment by RAJU2529** [comment]
@e0i. Created PR 5391
**https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5391**

**Comment by e0i** [comment]
@PierrickV  Thanks to your feedback, the issue has been addressed by the community contributor, **RAJU2529** and the associated PR has been merged. Thanks for your providing feedback.
