### ISSUE TITLE
Language support link

### ISSUE THREAD

**Issue by tmlyon** [MicrosoftDocs/windows-itpro-docs#5380]
Once the new language support article that Teresa is working on gets published for HL2, we should update the link in this page to that instead. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f29d313-070b-df7e-7a46-a175af7d9f45
* Version Independent ID: 53298953-2745-3b52-7db9-8322306be1a8
* Content: [Use your voice with HoloLens](https://docs.microsoft.com/en-us/hololens/hololens-cortana?source=docs)
* Content Source: [devices/hololens/hololens-cortana.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/hololens-cortana.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @v-miegge
* Microsoft Alias: **v-miegge**

**Comment by Teresa-Motiv** [comment]
Created PR [1528](https://github.com/MicrosoftDocs/windows-docs-pr/pull/1528) in windows-docs-pr to change the link.

**Comment by scooley** [comment]
Fixed!  Just checked to be sure too.
