### ISSUE TITLE
GPO setting - Accounts: Block Microsoft accounts - blocks windows store use

### ISSUE THREAD

**Issue by Retoxx** [MicrosoftDocs/windows-itpro-docs#5383]
The GPO Setting **Accounts: Block Microsoft accounts** , when enabled, also blocks the ability for a user to log into the Microsoft store and download apps.

Is this by design, or is this a flaw in the logic of this policy?

I assumed this would only block logins with MS Azure accounts, but it also blocks them from signing into the windows store and downloading apps...  

<img width="956" alt="MS account blocking " src="https://user-images.githubusercontent.com/9939365/68422054-4b464b00-0154-11ea-87c4-bb1458253c2b.png">

**Comment by RAJU2529** [comment]
@Retoxx.  Normal users cant able to download the apps from Microsoft store.
Microsoft store needs Microsoft account to download apps. 
 therefore the policy is correct
