### ISSUE TITLE
Dual Scan

### ISSUE THREAD

**Issue by Typhoon87** [MicrosoftDocs/windows-itpro-docs#5384]
It would be useful if this documentation was updated with current information about setting up or blocking dual scan.  I know in the old ticket for this page 4637 there was a link  to the "Improving Dual Scan on 1607” but that information is now outdated as it was written for 1607 and is not really formal documentation anyway. That document does not cover the changes that have been made with moving features on demand out of WSUS, how do I disable dual scan but get features on demand 1809+ working?

A formal note of which policy(s) actually affect dual scan or not, maybe some kind of decision tree type thing, Do you want only WSUS/SCCM only, WU only, dual scan WSUS/WU, WSUS/SCCM only but with Features on demand working for 1809+, and for all of those do you want the store to work or not. This is really becoming too complicated to keep track especially as additional GPO's have been added.

I have also added a ticket for similar document on another docs page its github ticket 5367. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efb8dfd-971e-7257-f8b7-f80843989eb8
* Version Independent ID: d7808728-bb89-a06e-a103-ec1c74682f64
* Content: [Manage additional Windows Update settings (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-wu-settings#do-not-connect-to-any-windows-update-internet-locations)
* Content Source: [windows/deployment/update/waas-wu-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-wu-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by jaimeo** [comment]
Thanks very much. I'll be referring this to the PM so we can formulate an update strategy together as soon as they're back from Ignite.

**Comment by Typhoon87** [comment]
It has been almost a month I just wanted to swing back around on this?

**Comment by jaimeo** [comment]
PM is working on some updates for the update content generally--we'll include this info in that.

**Comment by Typhoon87** [comment]
Is there an estimate on the time table? I am working on getting FOD with 1809 working am hoping to have this information to assist.

**Comment by jaimeo** [comment]
@arcarley is there some info we could share to help this person out in the meantime while we edit the docs?

**Comment by Typhoon87** [comment]
I just wanted to swing around on this again. I know we hit a couple weeks with the holiday but now that we are on the backside of that I wanted to follow up again.

**Comment by jaimeo** [comment]
It is included in the big glob of updates we're working on. @arcarley is there some info we could share to help this person out in the meantime?

**Comment by arcarley** [comment]
Apologies for the delayed response. The new documenation will contain a page specifically about dual scan and how to manage with it (or disable it). Currently, if you have set any Windows Update for Business policy (ex. deferrals) your device by default will scan both Windows Update and Windows Server Update Service (WSUS). 

Here is a list of policies related to Windows Server Update Service (WSUS):  
- Policy Name: Update Service Url  
- Policy Name: Update Service Url Alternate 
- Policy Name: Allow MU Update Service  
- Policy Name: Allow Non Microsoft Signed Update  
- Policy Name: Allow Update Service  
- Policy Name: Set Disable UX WU Access 
- Policy Name: Disable Dual Scan 

Please let me know if you have any other questions in the mean time while we complete the documentation update. :)

**Comment by Typhoon87** [comment]
Thank you for getting back to me on this this is a great start but not my core question. I am still unsure how to install Features on Demand such example RSAT tools (AD, GP, ect.) in 1809 and higher while maintaining dual scan stay disabled. What group of policies need to be used to achieve that?

Microsoft has multiple times changed how to accomplish this in Windows 10 and part of the reason I have asked about this doc update.

**Comment by Typhoon87** [comment]
Additional info on my root question. Check this reddit thread (https://www.reddit.com/r/SCCM/comments/bselnk/some_clarification_on_dual_scan_store_updates_and/?utm_source=BD&utm_medium=Search&utm_name=Bing&utm_content=PSR1) Specifically the reply from MVP and moderator  bdam55

**Comment by Typhoon87** [comment]
Just wanted to check in again on this one. Are we close to getting this document update out there?

**Comment by e0i** [comment]
@Typhoon87 Thank you for following up. Maybe one of the community contributors is able to help with your question in the meantime the document authors get back with an answer. Passing your request accordingly. Stay healthy.

**Comment by Typhoon87** [comment]
I wanted to check up on this again. Its now been about a year since I opened the request and have not asked for an update since April. What is a reasonable estimate of when this documentation will go live?

**Comment by jaimeo** [comment]
@arcarley I believe you had some content in process for this?

**Comment by Typhoon87** [comment]
Checking for any other updates in this one? Has such a doc been released yet?

**Comment by e0i** [comment]
Hello, @Typhoon87 

According to the internal sources, there are planned changes coming up this Summer that are going to be documented and hence the current article is already going to be depreciated.

Thank you for your feedback and following up on this.
