### ISSUE TITLE
included page "Improve request performance" title format & placement

### ISSUE THREAD

**Issue by illfated** [MicrosoftDocs/windows-itpro-docs#5400]
This page contains an include link to a separate page for the title
# Improve request performance
and the note text
***
For better performance, you can use server closer to your geo location:

- api-us.securitycenter.windows.com
- api-eu.securitycenter.windows.com
- api-uk.securitycenter.windows.com
***
This note text could preferably be moved into this page instead of existing with its own page only for the note, because the page title does not generate a link in the URL list **[In this article]** on the right hand side of the page.

In my opinion, the note also belongs after the Request Example, not before it, because the text reads as if the request example code block should appear directly after the text
> Here is an example of the request.

If my opinion looks reasonable, I will volunteer to create a PR to make the above mentioned changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91e975e6-ad08-1f45-7503-d63b8949bb0a
* Version Independent ID: 0306852c-5c3a-183b-e4af-cbde734114ec
* Content: [Find machines by internal IP API](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/find-machines-by-ip)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/find-machines-by-ip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/find-machines-by-ip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Here is a Github preview of what I have in mind for the suggested change to this page:
***
## Example

**Request**

Here is an example of the request.
```
GET https://api.securitycenter.windows.com/api/machines/findbyip(ip='10.248.240.38',timestamp=2018-09-22T08:44:05Z)
```
## Improve request performance

> [!NOTE]
> For better performance, you can use server closer to your geo location:
> - api-us.securitycenter.windows.com
> - api-eu.securitycenter.windows.com
> - api-uk.securitycenter.windows.com

***
Please note: my suggested change uses MarkDown **H2** heading for both of the section titles instead of using a **H1** title heading for **Improve request performance** .

(This is in addition to my suggestion of removing the linked include file.)

**Comment by mypil** [comment]
@illfated - Thank you for submitting feedback.

It would be great if you can help to create a PR for this issue. Please let me know once you've created the PR and kindly link it to this issue so I can let the doc owner review it for merging. 

Thank you for your contribution to make the docs better! It is greatly appreciated!

**Comment by illfated** [comment]
@mypil : Thank you for the positive feedback. My pull request is ready for review.
I have already invited nenonix & JohanFreelancer9 to perform a copy review.
