### ISSUE TITLE
Documentation Translation

### ISSUE THREAD

**Issue by OpaSieben** [MicrosoftDocs/windows-itpro-docs#5401]
The KQL commands in the table "Learn common query operators for Advanced hunting", are also covered by translation. 
In german the command "project" is translated to "projizieren" which will surely not work.

**Comment by mypil** [comment]
@OpaSieben - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@OpaSieben  - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
