### ISSUE TITLE
EDR command syntax

### ISSUE THREAD

**Issue by aminah-amino** [MicrosoftDocs/windows-itpro-docs#5402]
EDR enabling Command should be : 
mdatp --edr --earlyPreview [true/false]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07f72a75-ca85-0651-1512-8ffb62d0ab7b
* Version Independent ID: 6e15dd30-1db2-4a18-a18c-c343e1d508cd
* Content: [Resources for Microsoft Defender ATP for Mac](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-resources)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@aminah-amino  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
fixed in mentioned and related article

**Comment by illfated** [comment]
Please note the discussions and feedback from the document author in the following pages:
- **#5368** **Command shown is incorrect** (closed issue)
- **#5369** Update endpoint-detection-response-mac-preview.md (PR)
- **#5378** Corrected the command line flag (PR)

**Comment by illfated** [comment]
Ref. #5507

**Comment by levinec** [comment]
I'm updating documentation to address this confusion. Will be live tomorrow.
