### ISSUE TITLE
1909 is required

### ISSUE THREAD

**Issue by dugatlin** [MicrosoftDocs/windows-itpro-docs#5403]
See https://oofhours.com/2019/09/15/windows-autopilot-known-issues-in-windows-10-1903/ which states 1903 along with the Sept 26, 2019 cumulative update. Nearly all 1903 images do not have that cumulative update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5b57d1-61b3-39d4-34ff-d6dcb858c250
* Version Independent ID: 42609104-815f-9e7a-39aa-38d92cc910c9
* Content: [Windows Autopilot for white glove deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove#feedback)
* Content Source: [windows/deployment/windows-autopilot/white-glove.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/white-glove.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@dugatlin  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by greg-lindsay** [comment]
We have this information here: https://docs.microsoft.com/windows/deployment/windows-autopilot/known-issues

But this doesn't mean that 1909 is required.  It means that 1903 works, but you also might have an issue until you apply the update.
