### ISSUE TITLE
Shows machines that aren't covered by Defender ATP

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/windows-itpro-docs#5405]
The machine list page shows machines that haven't been onboarded to Defender ATP and are running other AV software.
This seems to be because the CommercialID has been set on them for Windows Updates for Business monitoring in the WaaSUpdates Solution in LogAnalytics.
This gives an odd cross-contamination of data making it impossible to see from the Defender Security Center which machines have actually been onboarded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18da4497-3712-ac71-4643-5e49b531716a
* Version Independent ID: e46cd2be-d129-2255-4be1-4567911a3d12
* Content: [View and organize the Microsoft Defender ATP machines list](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/machines-view-overview)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/machines-view-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/machines-view-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@OffColour  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by OffColour** [comment]
You can close this. GPO msitake on my part.
