### ISSUE TITLE
logical typo [DLP related]

### ISSUE THREAD

**Issue by ahm3dhany** [MicrosoftDocs/windows-itpro-docs#5406]
[Enter feedback here]

> For example, the **more** detailed the rule set, the **more** false positives are created

I think you meant the less detailed the rule set, the more false positives are created. (i.e. if the rule set is general so that it covers more than the target cases, then if may generate false positives) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d016c711-b1f4-668e-adbc-ff6911965851
* Version Independent ID: 64b2a1a4-1efe-35da-721e-7cbb0b1c684e
* Content: [Protect your enterprise data using Windows Information Protection (WIP) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Even though I am not an expert or master of this topic, I am able to see that the sentence makes sense in its current form, particularly in its context of complexity when it comes to adding several types of rules to the combined rule set. I read the sentence content "the more detailed the rule set, the more false positives are created" to mean that when more rules are added to the rule set, more and more data is added to the total amount of data to be scanned, filtered, and verified before being safe for the end users. In my view, this makes sense just fine as it is.

You may want to wait for feedback from the MS Docs team and not just take my word for it. I just wanted to share my view that it can be interpreted differently, depending on context.

**Comment by mypil** [comment]
@ahm3dhany  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello @ahm3dhany, @illfated ,
For me, the current wording sounds like logically incorrect.
The detailed rules set would better identify the data that must be prevented from sharing (which means less false positives)

**"the more detailed the rule set, the more false positives are created" to mean that when more rules are added to the rule set, more and more data is added to the total amount of data to be scanned, filtered, and verified** - not sure that the rules set that contains a lot of conditions and few exceptions could be called "detailed"

Dear @dulcemontemayor, could you please advise?

Thank you

**Comment by mypil** [comment]
@ahm3dhany - As mentioned by MaratMussabekov & illfated, the doc is fine as it is. 

Please feel free to open a new issue if you find any documentation error or if there is a specific area of the docs that we can improve on and we will be glad to help fix it. Thank you.

**Comment by illfated** [comment]
@mypil : Please note that @MaratMussabekov actually disagrees with my view, but said that he does not know enough to interpret the sentence correctly, therefore asking the document author for advice.

Maybe we could ask the doc manager (Daniel Simpson) for advice or check if the page should reference a new author for future requests?

**Comment by mypil** [comment]
@illfated - Reopening this issue to get insights from the author/manager. Sorry to have missed the difference in your views with MaratMussabekov.

@DulceMontemayor @Dansimp - Can you please share your insights on this issue?

Thank you.
