### ISSUE TITLE
USMT skips orphaned domain users 

### ISSUE THREAD

**Issue by damtrx** [MicrosoftDocs/windows-itpro-docs#5411]
USMT scanstate tries to open NTUser.dat registry for every person found in ProfileList registry.
Then it tries to match the SID of this user to one in the Active Directory(if the machine is joined)

The problem is that if the user found in ProfileList regystry was orphaned domain user (those users were in different Domain but there is not trust between old and new), the tool skips these profiles with Warning message. Not error but warning. When using HardLink migration those users are deleted and all the data inside is lost. 

0x00000534[gle=0x00000534] 2019-11-05 16:33:58, Warning [0x0803ba] Found valid profile but can't get user credentials. Will ignore due to error code: 0x00000534 User SID: S-1-5-21-91555185-1181623535-1233803906-1640[gle=0x000000cb]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde8580a-bd82-ebd2-3767-f3ee662a904e
* Version Independent ID: 94323219-e4ed-8761-723e-06be33c3b9cc
* Content: [User State Migration Tool (USMT) Overview (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-overview#feedback)
* Content Source: [windows/deployment/usmt/usmt-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/usmt/usmt-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@damtrx  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello @damtrx ,
I have created a PR related to this issue to the article dedicated to Hard-Link migration.
Could  you please have a look?
Thank you

**Comment by damtrx** [comment]
Thanks. 
There is a workaround for this problem. Include C:\Users with exceptions for NTuser.dat and NtUser*.dat and some of the \Microsoft folders inside the user folder. After scanstate the user info is preserved . The profile can't be used but the data is there.

**Comment by illfated** [comment]
@damtrx : PR #5503 has been merged in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/dce53f6a7dc3af0273cd48825eb4ac8f00f8e77b . 
Are there any remaining issues in the article, to be resolved?

**Comment by damtrx** [comment]
I think that my issue is correctly resolved so you can close this PR.

Thanks

Поздрави,
Марто

________________________________

**Comment by illfated** [comment]
@mypil : You are welcome to close this issue ticket, as confirmed above.
