### ISSUE TITLE
18.21 Inking & Typing - wrong registry settings

### ISSUE THREAD

**Issue by livestrong91** [MicrosoftDocs/windows-itpro-docs#5412]
18.21 Inking & Typing can not be disabled with the given values in Win 10 1809. 
I had luck with the following values:

HKCU\Software\Microsoft\InputPersonalization\TrainedDataStore	HarvestContacts	REG_DWORD	0x00000000 (0)
HKCU\Software\Microsoft\Personalization\Settings	AcceptedPrivacyPolicy	REG_DWORD	0x00000000 (0)

Can you please check that?

https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services#feedback

**Comment by mypil** [comment]
@livestrong91  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by RAJU2529** [comment]
@livestrong91. Just now I checked that the registry settings that you have provided website. 
!8.21 clearly says disable of ink and typing data collection only with registry keys.
But you taking about the disabling if ink and typing function.
and I checked on 1903 windows 10 home edition.

**Comment by livestrong91** [comment]
Just to clarify:
I want to disable the Inking & typing personalization in the privacy settings. I would prefer via GPO, but Microsoft don't provide it here.
![image](https://user-images.githubusercontent.com/51318313/68742956-a616f100-05f1-11ea-914d-2f6419f0060b.png)

MS says 

> Set RestrictImplicitTextCollection registry REG_DWORD setting in HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\InputPersonalization to a value of 1 (one)

to do the following: 

> In the UI go to Settings -> Privacy -> Diagnostics & Feedback -> Inking and typing and turn Improve inking & typing to Off

This don't work on Win 10 1809 as promised in the ITdocs!

**Comment by RAJU2529** [comment]
@livestrong91. Again MS says clearly  that registry key belong to disabling of data collection from inking and typing.
MS does not said for disabling I of inking and typing

**Comment by livestrong91** [comment]
This topic belongs to the data collection section. I thought that was clear, with the link I provided:

https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services#bkmk-priv-ink

However, the listed registry setting do not work in Win 10 1809!

**Comment by RAJU2529** [comment]
@livestrong91. Wait for some days, let 1809 users will check on their system

**Comment by VLG17** [comment]
@livestrong91 I have tested on Windows 10 Enterprise build 1909 and i can confirm the the regkey path provided in the article is incorrect.

I have found the parameter RestrictImplicitTextCollection under: HKCU\Software\Microsoft\InputPersonalization
![image](https://user-images.githubusercontent.com/41186174/69705165-aa690100-10fd-11ea-848f-4eded7a9c693.png)

I will create a PR to address this. I did not see any distinction in terms of windows 10 builds so i would take into consideration how it is in the latest one (1909).

**Comment by illfated** [comment]
Very good & fair point.
The doc text even says "**(note: there is no Group Policy for this setting)**",
so it is only reasonable to document that the registry part of the setting
does not belong within the hive branch **`HKLM\Software\Policies\Microsoft\`** .

**Comment by medgarmedgar** [comment]
We are actually missing the Inking regkey in the article as well.  

1. These 2 regkeys need to be added to the article

RestrictImplicitTextCollection registry REG_DWORD setting in HKEY_CURRENT_USER\Software\Microsoft\InputPersonalization needs to be set 1 (one)

RestrictImplicitInkCollection registry REG_DWORD setting in HKEY_CURRENT_USER\Software\Microsoft\InputPersonalization needs to be set 1 (one) 

2. The downloadable script also needs to be updated to remove them from machine.txt and add them to user.txt

**Comment by illfated** [comment]
Restructured / rephrased for extended understanding, before someone opens the next PR :

`HKEY_CURRENT_USER\Software\Microsoft\InputPersonalization` Registry Keys must be set to :
- `RestrictImplicitTextCollection` `REG_DWORD` = 1
- `RestrictImplicitInkCollection` `REG_DWORD` = 1

**Comment by VLG17** [comment]
@medgarmedgar @illfated The regkeys are present, am i missing something? 

![image](https://user-images.githubusercontent.com/41186174/70889999-9e7daa00-1fec-11ea-8d02-2fccc16aaea6.png)

**Comment by illfated** [comment]
Sorry, I don't know more than what @medgarmedgar wrote, so I can only defer to his comment and ask for more details.

Maybe the confusion could have something to do with this issue ticket being incorrectly reported, missing the links for both the docs.microsoft.com page and the github source page.

**Comment by medgarmedgar** [comment]
It’s fixed now, no further work needed at this point.

**Comment by medgarmedgar** [comment]
It’s fixed now, no further work needed at this point.

**Comment by illfated** [comment]
@mypil : I believe this issue ticket is resolved now, if I have understood the reply from Mike Edgar correctly.

**Comment by medgarmedgar** [comment]
Yes, please Resolve/Close it.

**Comment by mypil** [comment]
@livestrong91 - Thank you for submitting this feedback.

From our understanding, the issue has been resolved so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
