### ISSUE TITLE
Base64

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#5414]
There is a strange and persistent error in the WDAC documentation, relating to Base64 encoding.
"Value type is b64. Supported value is any well-formed WDAC policy, i.e. the base64-encoded content output by the ConvertFrom-CIPolicy cmdlet." and "If you are using ...... Intune, ensure that you are using Base64 as the Data type when using Custom OMA-URI functionality to apply the Code Integrity policy."
ConvertFrom-CIPolicy produces a binary file, not a Base64 encoded file. In Intune, you do indeed need to specify the data type as Base64 (file), but you need to upload the binary file, not a Base64-encoded version of it.
This has been escalated to the top in a long MS Premier Support ticket, and confirmed. It's confusing, because a Base64-encoded version of the binary will be accepted, will be reported as successfully delivered by Intune, and will appear on the client as the default SIPolicy.p7b but it does not actually work. It will only work if the file is uploaded to Intune as a binary file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f773e835-33eb-e04d-340b-4d1215b05ea7
* Version Independent ID: 0eec228f-e523-396b-2cc2-43291a5ae5f8
* Content: [ApplicationControl CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/applicationcontrol-csp)
* Content Source: [windows/client-management/mdm/applicationcontrol-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/applicationcontrol-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@Air-Git  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Air-Git - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/2da7d0580071050d99175248780650f726dadd23.


Thank you for your contribution to make the docs better! Much appreciated!
