### ISSUE TITLE
Clarify reboot requirement for SSU

### ISSUE THREAD

**Issue by ChadMcCaffery** [MicrosoftDocs/windows-itpro-docs#5416]
### Please clarify if Servicing Stack Updates require a reboot

There seems to be conflicting information.

I just read that an LCU categorized as "Security Update" requires a reboot: [Source](https://docs.microsoft.com/en-us/windows/deployment/update/waas-servicing-differences#windows-10--next-generation):

> ... The security classification, by definition, requires a reboot of the device to complete installation of the update.

Then I read about SSUs, in this section: [When are they released?](https://docs.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates#when-are-they-released)

> ... Starting in November 2018 new servicing stack updates will be classified as "Security" with a severity rating of "Critical."

... and [further down in the same topic](https://docs.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates#installation-notes):

> Installing servicing stack update does not require restarting the device, so installation should not be disruptive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b706f0af-d504-a8ca-7c38-b8bb9283bfad
* Version Independent ID: 14f31acf-9f47-59a6-269f-62ab249fe560
* Content: [Servicing stack updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates#feedback)
* Content Source: [windows/deployment/update/servicing-stack-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/servicing-stack-updates.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mypil** [comment]
@ChadMcCaffery  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by RAJU2529** [comment]
@ChadMcCaffery.  LCU and CLU needs system should be restarted or needs rebooted after update.
SSU does not need reboot or restarted

**Comment by MaratMussabekov** [comment]
Hello @ChadMcCaffery, 
@RAJU2529 is correct, there is no need for restart after the installation of servicing stack updates. I believe that the article about LCU must be updated to be less confusing.
Thank you

**Comment by ChadMcCaffery** [comment]
Thanks for the follow up.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by illfated** [comment]
The PR #5518 content has been merged into [`MicrosoftDocs:public`](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/public) in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/3e9f4c147cfbb8e6dbc348b12a13a1d4e460fd4b .
