### ISSUE TITLE
MBAM client on the servers?

### ISSUE THREAD

**Issue by bahnjee** [MicrosoftDocs/windows-itpro-docs#5417]
Both items #4 to be done on the servers instruct to install the MBAM client on the servers.  Is this correct?  Why do I need the agent on the server?  I'm not encrypting the servers.  Seems odd and I don't recall doing that before...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 604e3922-8536-4cb7-5df7-beb0b7087e58
* Version Independent ID: 4c824538-1e43-8779-63e3-7f2183a9c95a
* Content: [Upgrading to MBAM 2.5 SP1 from MBAM 2.5](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/upgrading-to-mbam-25-sp1-from-mbam-25)
* Content Source: [mdop/mbam-v25/upgrading-to-mbam-25-sp1-from-mbam-25.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/mdop/mbam-v25/upgrading-to-mbam-25-sp1-from-mbam-25.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@bahnjee  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello @bahnjee ,
this step is required for update of the report role on SQL server and Self Service Portals on the IIS server
Thank you

**Comment by nascar3000** [comment]
@mypill, did you have the chance to check with the team why we are recommending install Client update to servers ?

**Comment by mypil** [comment]
@bahnjee - From our understanding, your issue was answered by MaratMussabekov.

@nascar3000 - For your issue, I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products so they can answer your technical queries. 

Please feel free to open a new issue if you find any documentation error or if there is a specific area of the docs that we can improve on and we will be glad to help fix it. Thank you.

**Comment by nascar3000** [comment]
@mypil I ve been already confirmed internally, the information provided on the page is wrong. Can you please contact the product team or SME to get the correct information. (BTW I am already a support engineer :) 

@bahnjee No need to install client software to servers you are right.

**Comment by MaratMussabekov** [comment]
Hello @nascar3000,
could you please have a look at the PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5728 ?
Thank you

**Comment by mypil** [comment]
Reopening issue until PR #5728 is merged.

**Comment by mypil** [comment]
@bahnjee - The PR has been merged based on https://github.com/MicrosoftDocs/windows-itpro-docs/commit/7f373dc25bd8ff72f62fc8665dafb94e37dac6c6. We will close this issue now.

Thank you for your contribution to make the docs better! Much appreciated!
