### ISSUE TITLE
Pin complexity location is outdated.

### ISSUE THREAD

**Issue by aaroneg** [MicrosoftDocs/windows-itpro-docs#5418]
The "Pin Complexity" setting is no longer under the "Windows Hello for Business" location. it is under System. see https://msitproblog.com/2017/09/05/pin-complexity-missing-windows-hello-business-gpo/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 789566d4-463a-4c64-bf89-fb963ac29f80
* Version Independent ID: 02946732-bb29-d8e6-cedd-7f5e508f8798
* Content: [Manage Windows Hello in your organization (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-manage-in-organization#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-manage-in-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-manage-in-organization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mypil** [comment]
@aaroneg  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by RAJU2529** [comment]
@aaroneg. I have found "Pin complexity"under Computer Configuration>>Administrative Templates>>System>>Pin Complexity
![now01](https://user-images.githubusercontent.com/3296790/68762380-12b6dd80-063c-11ea-9cb6-f3552b7bac87.JPG)

![now02](https://user-images.githubusercontent.com/3296790/68762413-22362680-063c-11ea-93bb-a4f52d642693.JPG)

**Comment by mypil** [comment]
@aaroneg - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/558304c326e89ed5a9232839dd1e7f5529a18a71. 


Thank you for your contribution to make the docs better! Much appreciated!
