### ISSUE TITLE
Does ISG feature needs Internet access? If that so, any network requirements, such as URLs?

### ISSUE THREAD

**Issue by Eddddeee** [MicrosoftDocs/windows-itpro-docs#5419]
Does ISG feature needs Internet access? If that so, any network requirements, such as URLs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2586cc9a-d449-97cf-8164-c2e4bbed7c1e
* Version Independent ID: d606e2a2-465e-6d45-62dd-d57ff85b6a1a
* Content: [Deploy Windows Defender Application Control with Intelligent Security Graph (ISG) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-intelligent-security-graph)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-intelligent-security-graph.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-intelligent-security-graph.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@Eddddeee. I think internet access is needed to control

**Comment by denisebmsft** [comment]
Hello @Eddddeee, thank you for your question. And thank you, @RAJU2529, for your response. I've made some updates to this article to include a link to the Microsoft Intelligent Security Graph content. Hope this helps!
