### ISSUE TITLE
Can Routes list be modified when Vpn is already connected using VpnNativeProfile?

### ISSUE THREAD

**Issue by rsuwp** [MicrosoftDocs/windows-itpro-docs#5420]
I am able to configure routes while creating VpnNativeProfile.
But can i add/delete routes when the connection is already established?
It looks like if we create a VpnPluginProfile, runtime modification of routes list can be done, correct me if i am wrong. Can this be achieved for a VpnNativeProfile?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad2d82ab-4fdd-5cdd-247e-7cf3fb2a237d
* Version Independent ID: 3f88b62a-ffac-20b5-a0d7-87bb62f894c1
* Content: [VPN routing decisions (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-routing?source=docs)
* Content Source: [windows/security/identity-protection/vpn/vpn-routing.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/vpn/vpn-routing.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by rsuwp** [comment]
Just found a method "UpdateProfileFromObjectAsync", going to try it.

**Comment by RAJU2529** [comment]
@rsuwp. According to me, don't modify while running

**Comment by rsuwp** [comment]
Should "UpdateProfileFromObjectAsync" not do what i am trying to accomplish here? It's not working though. Any idea?

**Comment by rsuwp** [comment]
Hi Steve, Did you get a chance to look into this? Awaiting for the reply, it's really urgent.

**Comment by VLG17** [comment]
@rsuwp did you get to test this further and maybe found a solution?

Have you tried using the [VPNv2 CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp?redirectedfrom=MSDN)? According to [this article](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-routing) it should be possible to edit the routes at connect time.

> Routes can also be added at connect time through the server for UWP VPN apps.
