### ISSUE TITLE
Feedback Hub never returns any status

### ISSUE THREAD

**Issue by Alexees** [MicrosoftDocs/windows-itpro-docs#5422]
I reported this here because the regular reporter is the problem and I don't know where to put this really.

I reported a couple of issues in the Feedback Hub.
The oldest is probably from over a year ago.
I never heard anything about any of the issues I've reported. Are the even looked at? What is their status? Nothing.

I know from Sarah Sexton, Microsoft Staff, that a few of them got taken care of on the internal issue tracker. With her Microsoft Account she could even see that in the Feedback Hub directly while I couldn't.

[This page](https://docs.microsoft.com/en-us/hololens/hololens-feedback#feedback) explained how to give feedback, so I did, a couple of times.

I talked to Sarah on an event and we went over this and she was shocked how poor the hub experience was from a regular developer point of view. No info, no responses, nothing.

I don't think this is a situation anyone wants to be in. There are a couple of bugs in the Mixed Reality Portal that have never been addressed and in addition to the lack of "feedback" from the "Feedback Hub" this gives me the impression that it's dead too.

**Comment by RAJU2529** [comment]
@Alexees. you can see all your submitted feedback under Myfeedback option
here is the proof
![now03](https://user-images.githubusercontent.com/3296790/68763288-164b6400-063e-11ea-8839-574437e250f0.JPG)

**Comment by Alexees** [comment]
@RAJU2529 Thanks for the answer.
I know I can view my feedback there, that's not the point.
First of all feedback entries are linked with issues in Azure DevOps that I cannot follow (I saw that on Sarah's login).
And secondly I didn't ever receive anything for any of them.
There is bug reports in there and either those are being taken care of without me seeing it, or nobody cares, which is not how customers should be treated.
If votes are the only mechanism to get them heard at all then the Mixed Reality Portal must be dead.

**Comment by RAJU2529** [comment]
@Alexees.Then wait for some days, let windows expert users will answer.
If not solved means you can post a question in answers.microsoft.com

**Comment by Alexees** [comment]
@RAJU2529 Issues range from 2 months to over a year and I don't think the community should solve problems that Microsoft should solve.
answers.microsoft.com seems to be a community page with anything close to a Mixed Reality topic nowhere to be found

**Comment by illfated** [comment]
I am fairly sure that your issue is real and that it needs to be looked into.
Just out of curiosity, are you able to find anything useful on MSDN/TechNet ?

**Comment by denisebmsft** [comment]
@Alexees my hope is that by now you have received a response to your feedback. If not, your best option is to contact technical support. As this is a product issue and not so much a documentation issue, I am going to close this GitHub item for now. And thank you @RAJU2529 and @illfated for your help!
