### ISSUE TITLE
Batching support for Push Notification

### ISSUE THREAD

**Issue by kamalmaheshwari** [MicrosoftDocs/windows-itpro-docs#5425]
Is there a way to batch the notifications that are send to the windows mdm clients? Currently the channelURI that is received is specific to a device and I don't see any way apart from calling one by one if I need to send to multiple devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663b7682-f766-a141-e4f9-81c607eb8308
* Version Independent ID: 16c14d60-188b-a49c-4112-ef25f4ef1e9b
* Content: [Push notification support for device management](https://docs.microsoft.com/en-us/windows/client-management/mdm/push-notification-windows-mdm#feedback)
* Content Source: [windows/client-management/mdm/push-notification-windows-mdm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/push-notification-windows-mdm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
@kamalmaheshwari - Looks like this is not supported but I would suggest you send a request for this feature.

@e0i can guide you on how you can request the feature using user voice channel. 

Thanks
Imran.

**Comment by e0i** [comment]
You may send your input via the Feedback Hub in order for that to be addressed via the proper channels:

[Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

The issue tracker of this repository is for content fixes.

Thank you.
