### ISSUE TITLE
How does Windows 10 locate WS2016/WS2019 DC's?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/windows-itpro-docs#5426]
Could you please add a note that states how Windows 10 clients are finding the correct domain controllers in the environment?  If you could also add a comment about how AD sites with and/or without WS2016/WS2019 DC's behave, that'd be great.

From experience, sites without WS2016+ DC's is not a problem as long as Windows 10 has connectivity to a WS2016+ DC in any other site.  But how and why this is working is undocumented currently.

Thanks,
Jeremy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1da1ac4-4e67-5970-6d10-19aac6e853f6
* Version Independent ID: 4f4b45eb-d479-3699-1ef1-a1a20030d675
* Content: [Planning an adequate number of Windows Server 2019 Domain Controllers for Windows Hello for Business deployments](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by jkdevore** [comment]
Jeremy - Take a look at https://docs.microsoft.com/en-us/windows/win32/api/dsgetdc/nf-dsgetdc-dsgetdcnamea.  It explains that DS_DIRECTORY_SERVICE_8_REQUIRED specifies that the DSGETDCAPI  API should return a DC which is 2012 or higher.  I believe DS_DIRECTORY_SERVICE_9_REQUIRED would return a 2012 R2 DC and DS_DIRECTORY_SERVICE_10_REQUIRED would be used to located a 2016 or higher DCs.  However, I have been able to locate documentation to confirm that.

**Comment by JeremyTBradshaw** [comment]
@jkdevore thanks very much, that is good info that I haven't seen before.  That satisfies all I needed so feel free to close the issue.  I could have closed it but wasn't sure if you'll be adding the reference to the page, so left it.
