### ISSUE TITLE
 or to stream music from OneDrive.

### ISSUE THREAD

**Issue by LivefromRaleighwood** [MicrosoftDocs/windows-itpro-docs#5431]
We ended the Groove streaming music service and music track sales through the Microsoft Store in 2017. The Groove app is being updated to reflect this change. You can still use Groove Music to play the music on your PC or to stream music from OneDrive. You can use Spotify or other music services to stream music on Windows 10, or to buy music to own. ....... :or to stream music from OneDrive" = has pulled as well folks. Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215fea14-a9f3-6ed1-8aa3-8cbb4cbfc398
* Version Independent ID: ea54caae-1d90-fe54-217d-c43221cfce09
* Content: [Windows 10 - Features that have been removed](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-removed-features?source=docs#feedback)
* Content Source: [windows/deployment/planning/windows-10-removed-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/planning/windows-10-removed-features.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@LivefromRaleighwood. If you think those should be added means , then create new PR

**Comment by e0i** [comment]
Closing via #6687
