### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/windows-itpro-docs#5432]
It says "Also verify that the MAM user scope is set to None. Otherwise, it will have precedence over the MDM scope that will lead to issues.". But in https://docs.microsoft.com/en-us/intune/enrollment/windows-enroll it says "For corporate devices, the MDM user scope takes precedence if both scopes are enabled. The devices get MDM enrolled".  As enrolling through GPO qualifies the device as corporate (see https://docs.microsoft.com/en-us/intune/enrollment/enrollment-restrictions-set#blocking-personal-windows-devices), the documentation should be updated with the correct info as both links say two different outcomes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy?source=docs#feedback)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@nhogarth86 

With the help of your feedback, the content has been updated with relevant changes via the PR #5884. Thanks.
