### ISSUE TITLE
Custom detections via the API?

### ISSUE THREAD

**Issue by slw07g** [MicrosoftDocs/windows-itpro-docs#5435]
Is there a way to create custom detections via the API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42a8958f-0166-8f3c-6402-6ca022d089a8
* Version Independent ID: 78c76282-dbf1-bf18-c223-21da6678ae64
* Content: [Advanced Hunting API](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/run-advanced-query-sample-python#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/run-advanced-query-sample-python.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/run-advanced-query-sample-python.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
Hello,

Looks like this question can best be answered via relevant [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channels. 

Please consider checking with [Microsoft Community](https://answers.microsoft.com/en-us/windows/forum/windows_10) or [contacting support](https://support.microsoft.com/contactus) for your problem; The issues section of this repository is for content fixes in documentation.

If you feel that the associated article also needs to be updated for any reason feel free to re-open this issue or [contribute with a pull request](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/CONTRIBUTING.md).

Thank you.

**Comment by slw07g** [comment]
The question has nothing to do with Windows 10.

**Comment by e0i** [comment]
The appropriate discussion channel would then be the ["Security & Privacy" section](https://answers.microsoft.com/en-us/windows/forum/windows_10-security?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=all&isFilterExpanded=false&page=1) under the community discussion channel, where Windows Defender topics are also being discussed.
