### ISSUE TITLE
Wrong link for Win32_VideoController

### ISSUE THREAD

**Issue by MA-Maddin** [MicrosoftDocs/windows-itpro-docs#5436]
**Win32_VideoController** from list has href="https://msdn.microsoft.com/library/windows/hardware/aa394505" which is redirecting to **Win32_USBControllerDevice class** ( https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-usbcontrollerdevice ).

I don't know if the MSDN link is wrong or the redirect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04405438-4b80-b996-3421-a831353be2f7
* Version Independent ID: 5c0bf4d4-fa8b-85d4-41dd-3267534f3217
* Content: [WMI providers supported in Windows 10](https://docs.microsoft.com/en-us/windows/client-management/mdm/wmi-providers-supported-in-windows?source=docs#feedback)
* Content Source: [windows/client-management/mdm/wmi-providers-supported-in-windows.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/wmi-providers-supported-in-windows.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@MA-Maddin. Issue is conformed from my side, so tommorow I will create PR to add

**Comment by RAJU2529** [comment]
@jvsam. Just now i created PR # 5441.

**https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5441**
Please approve if it correct

**Comment by e0i** [comment]
@MA-Maddin Thanks to your feedback, the issue has been addressed by the community contributor, **RAJU2529** and the associated PR has been merged. Thanks for your providing feedback.
