### ISSUE TITLE
Error on the Registry location?

### ISSUE THREAD

**Issue by MichaelRybicki** [MicrosoftDocs/windows-itpro-docs#5437]
I found this Key here instead of where this document suggests. I'm assuming that's an error on the page?

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Surface\Surface Brightness Control

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ac6c100-6e19-4cf6-2fd1-558a6751cc5d
* Version Independent ID: eec13586-5975-9ada-ec0f-9f53654eb73b
* Content: [Surface Brightness Control](https://docs.microsoft.com/en-us/surface/microsoft-surface-brightness-control#feedback)
* Content Source: [devices/surface/microsoft-surface-brightness-control.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/microsoft-surface-brightness-control.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@MichaelRybicki I guess this got fixed. It's showing the following now:

> Run regedit from a command prompt to open the Windows Registry Editor.

> Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Surface\Surface Brightness Control\

> If you're running an older version of Surface Brightness control, run the following command instead:

> Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Surface\Surface Brightness Control\

**Comment by illfated** [comment]
Yes, the issue described in this ticket was resolved in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/8ee324fb0fd4f686bef88f99d5fa23a90fe3f985 .
