### ISSUE TITLE
policy-csp-search.md refers to nonexistent footnote

### ISSUE THREAD

**Issue by anthonypants** [MicrosoftDocs/windows-itpro-docs#544]
The policies `AllowCortanaInAAD` and `DoNotUseWebResults` on this page refer to a secret, mysterious fourth footnote, of which only three exist. Should these policies refer to one of the existing footnotes? Does someone need to write a fourth footnote?

**Comment by shortpatti** [comment]
@nickbrower -- Can you take a look at this issue?

**Comment by nickbrower** [comment]
This has been fixed.
