### ISSUE TITLE
Windows Defender firewall stops logging

### ISSUE THREAD

**Issue by micahdaniels** [MicrosoftDocs/windows-itpro-docs#5442]
Hi

Thank you in advance for any help offered. :)

I enabled logging for Domain, Public and private profiles, and i generally look at logs once or twice a month (sometimes more frequently). During and after month 1 logs were available. However at the end of month 2 the logs were gone. I needed to go into Windows defender, Click on "customise" button under "logging" dialog pane section and then on "Ok" again. after a few minutes the "pfirewall.log" appeared in the "%systemroot%\system32\LogFiles\Firewall\" folder again. Why did it disappear in the first place and why did logging stop?

Kind regards
Micah

**Comment by RAJU2529** [comment]
@micahdaniels. You have issues in wondows defender firewall, so better to post question in answers.microsoft.com forum.

**Comment by micahdaniels** [comment]
Will do, thanks for the input :)
