### ISSUE TITLE
Missing line-break in PowerShell snippet

### ISSUE THREAD

**Issue by hammar** [MicrosoftDocs/windows-itpro-docs#5444]
I believe there is a line break missing in the PowerShell code at https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-account#connect-to-exchange-online-powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9d48034-4b29-c10c-6e14-ecf14ca12f70
* Version Independent ID: 7794a57a-0db1-6420-68e9-0d1592a57b60
* Content: [Create Surface Hub 2S device account](https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-account#feedback)
* Content Source: [devices/surface-hub/surface-hub-2s-account.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/surface-hub-2s-account.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
@hammar : Can you confirm that the cmdlet should look like my suggestion below?

```powershell
$365Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.outlook.com/powershell -Credential (Get-Credential) -Authentication Basic –AllowRedirection
$ImportResults = Import-PSSession $365Session
```

As you have read this page more intently than me, have you noticed any of the other cmdlets in need of added line breaks?

**Comment by hammar** [comment]
@illfated correct on both counts; the line break in your first suggestion is where I think it should be, and the fourth line on the subsequent example should indeed be commented out (that makes more sense than introducing a new title, as line 5 is a direct continuation of lines 1-3).

**Comment by illfated** [comment]
Thanks a lot for the useful feedback. Based on what you have told me, I guess it could look something like this instead:

```powershell
Import-Module LyncOnlineConnector
$SfBSession = New-CsOnlineSession -Credential (Get-Credential)
Import-PSSession $SfBSession -AllowClobber

# Enable the Skype for Business meeting room
Enable-CsMeetingRoom -Identity account@YourDomain.com -RegistrarPool(Get-CsTenant).Registrarpool -SipAddressType EmailAddress
```
(I added a blank line for readability, but you are welcome to tell me if that kind of detail is less useful in this case.

**Comment by hammar** [comment]
Looks good to me.

**Comment by illfated** [comment]
Very well, looks good to me too. I will get back to this later tonight.
For now, I need to get some delayed support tasks off my schedule.

**Comment by jvsam** [comment]
That's great @illfated. Were you able to test the commands? Looking forward to your PR.

Thanks as well @hammar for this feedback, much appreciated. We always strive to give users the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, accurate and up-to-date.

**Comment by illfated** [comment]
Thank you for asking. Unfortunately, I don't have a test scenario where these commands will be of any practical use.
For now, I can only use logic and reason to see what needs to be done.

If anyone else would like to confirm that the suggested changes work as expected, I am all for it.

**Comment by illfated** [comment]
There you go. To see the full differences, view the Github document pages:
- **PR:** https://github.com/MicrosoftDocs/windows-itpro-docs/blob/c258c808b802e99d332e31e3ffb6914de6201e2f/devices/surface-hub/surface-hub-2s-account.md#connect-to-exchange-online-powershell
- **original:** https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/surface-hub-2s-account.md#connect-to-exchange-online-powershell

**Comment by illfated** [comment]
😲 ... and there it is merged already. @hammar : Thanks for the assistance,
I must admit, I have rarely seen such quick response as this evening/night.
