### ISSUE TITLE
Typo in supported OS versions "Windows Server 2016, version 1803"

### ISSUE THREAD

**Issue by amirsc3** [MicrosoftDocs/windows-itpro-docs#5445]
There is no such thing as "Windows Server 2016, version 1803".
It should probably say "Windows Server, version 1803 and later"
https://docs.microsoft.com/en-us/windows/release-information/status-windows-10-1803

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
@amirsc3 : Could you check the page again and see if it is still there? If it is, please provide a screenshot of that part of the page where you can find it.

I have tried searching the page using Ctrl+F , looking for all occurrences of "Windows Server 2016", but none of them are paired with ", version 1803".

**Comment by amirsc3** [comment]
Please see below screenshot:
![image](https://user-images.githubusercontent.com/42802974/69124296-2b941880-0aac-11ea-9191-0c3d88ec4022.png)
The location of the typo is here:
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements#hardware-and-software-requirements

**Comment by illfated** [comment]
OK, right. I see. Thank you. It was quite futile of me to search the page
https://docs.microsoft.com/en-us/windows/release-information/status-windows-10-1803
to find what you mentioned, so it makes quite the difference.

**Comment by amirsc3** [comment]
Yes - sorry I forgot to add the actual doc where the issue was :)

**Comment by illfated** [comment]
Fair enough. I will just put a handful of links here for later use, when I need some backup material as reference for PR changes:
- https://docs.microsoft.com/en-us/windows-server/get-started/whats-new-in-windows-server-1803
- https://docs.microsoft.com/en-us/windows-server/get-started/server-1803-release-notes
- https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-1803-removed-features

**Comment by nam31** [comment]
@amirsc3 Please let us know if you still have any question regarding the issue you have raised initially.

**Comment by illfated** [comment]
(As referenced above, see PR #6207 , commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/4c7c6dc8adb4432fd984ebaba44c8b63d20ef100 , for details on the correction.)
