### ISSUE TITLE
[LOC]Back-Translation "[Time]"→"[時刻]"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#5447]
ja-jp:"https://docs.microsoft.com/ja-jp/windows/configuration/wcd/wcd-time#provisionsettimezone"

![wcd-time_j3](https://user-images.githubusercontent.com/40815708/68989742-15107600-088e-11ea-9c17-d17b64c804e9.png)

same page : #3982 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1c382e76-7804-b1a4-5df8-698c74d9c669
* Version Independent ID: 659759e4-80a7-2236-76fa-b3032adf1970
* Content: [時刻 (Windows 10)](https://docs.microsoft.com/ja-jp/windows/configuration/wcd/wcd-time#provisionsettimezone)
* Content Source: [windows/configuration/wcd/wcd-time.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/wcd/wcd-time.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @TinaMcN, assigning this to you. Kindly review, thanks.

@officedocsbot assign @TinaMcN.

**Comment by TinaMcN** [comment]
@hyoshioka0128 私は人間の翻訳のためにこの記事を送った。 約3週間かかります。 (I sent this article to be human translated. It should take approximately 3 weeks.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 これは変更が必要な項目ですか? (Is this the item that needs to be changed?)
![image](https://user-images.githubusercontent.com/53281468/70081148-d8968700-15bc-11ea-927c-41221cfc57c3.png)

**Comment by illfated** [comment]
Based on this issue ticket title and the image in the opening comment, I would say yes.
Still, I will wait for @hyoshioka0128 to confirm that it is correct.

**Comment by hyoshioka0128** [comment]
@TinaMcN @illfated - It was not necessary to change [Time].
Thanks.

**Comment by hyoshioka0128** [comment]
It is my mistake.
 It was not necessary to change [Time].
Close #5447

**Comment by TinaMcN** [comment]
@hyoshioka0128 ご確認ありがとうございました。 頑張ってください。(thank you for much for confirming it)
