### ISSUE TITLE
[LOC] "時間" needs to be replaced with "時刻"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#5448]
https://docs.microsoft.com/ja-jp/windows/configuration/wcd/wcd-changes
same as : #3982 

![wcd-changes](https://user-images.githubusercontent.com/40815708/68989991-155e4080-0891-11ea-9ab9-6a775825fa57.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6a2a0071-ee73-f332-cc8d-3010e77937c6
* Version Independent ID: f6f814fd-ad69-36e8-b7f9-fb8302963b4a
* Content: [Windows 構成デザイナーでの設定の変更 (Windows 10)](https://docs.microsoft.com/ja-jp/windows/configuration/wcd/wcd-changes)
* Content Source: [windows/configuration/wcd/wcd-changes.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/wcd/wcd-changes.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @TinaMcN, assigning this to you. Kindly review, thanks.

@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
@hyoshioka0128 私は人間の翻訳のためにこの記事を送った。 約3週間かかります。 (I sent this article to be human translated.  It should take approximately 3 weeks.)

**Comment by hyoshioka0128** [comment]
@TinaMcN . - It is my mistake.
Need to change [Time] instead of [時間](Back-Translation).
Close #5448

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated. Please verify that it is fixed. Thanks again for the feedback)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #5608 | #5448.
Thanks.
