### ISSUE TITLE
Cloud-delivered protection 

### ISSUE THREAD

**Issue by spaelling** [MicrosoftDocs/windows-itpro-docs#5451]
To enable Cloud-delivered protection  one must select "Not configured". The alternative setting is "Enable". I assume that "Not configured" means using the out-of-the-box setting which is enabled (which could have been changed by a GPO)? But from a documentation standpoint it seems a bit backwards an non-intuitive that in order to enable Cloud-delivered protection not to pick enable.
Or does the "Enable" option somehow disable Cloud-delivered protection?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f8ccc01-1b04-e443-ef75-6ffe6c866dd5
* Version Independent ID: fa2eaa0f-db04-785a-3894-8244947b9cd5
* Content: [Enable cloud-delivered protection in Windows Defender Antivirus](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by HarrisburgUSysAdmin** [comment]
I agree with your comment.  I'm confused. Enable would make sense.  

Please clarify....

**Comment by mypil** [comment]
@spaelling - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/0d53576742445631ae8eded2787c30da7bf65067. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
