### ISSUE TITLE
CodeIntegrity compatible option

### ISSUE THREAD

**Issue by mschrisran** [MicrosoftDocs/windows-itpro-docs#5452]
We need a powershell native option for environments with AppLocker / CodeIntegrity deployed. .cmd's are blocked, as they can't be signed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27dbd025-8239-9847-b07e-378ca87d2d75
* Version Independent ID: 4b0e4ac7-a608-7c62-dcd4-2db628b3f67a
* Content: [Onboard Windows 10 machines using Group Policy to Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-gp)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-gp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-gp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@mschrisran - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via **[Feedback Hub](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
