### ISSUE TITLE
Standard hardware security not supported, if  SystemGuard is enabled

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#5453]
Today I have tested many options creating of new registry key , removing key  with device guard enabled with dTPM 2.0,
After many tests, i conformed that "Standard hardware security not supported" under device security is displayed. That happens only if add systemguard key with enabled is set to 1.

But if delete "Enabled" value, then the laptop shows Your device exceeds the requirements for enhanced hardware security. I have  reported this  problem through feedback HUB 

![Capture](https://user-images.githubusercontent.com/3296790/69077829-87cf4c00-0a5c-11ea-9912-d72374261d3d.JPG)

![Capture02](https://user-images.githubusercontent.com/3296790/69077833-8b62d300-0a5c-11ea-8798-feea50514bd0.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31d623d9-316c-0ef1-b6be-c3773d77ca21
* Version Independent ID: 83ddb59d-0cfc-34f2-e666-8927d86a04a7
* Content: [System Guard Secure Launch and SMM protection (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@RAJU2529 - Thank you for submitting feedback.

Can you please share what specific issue you have with this doc? Or are you having some technical issues which requires technical support?

If you have some issues with this doc, we would really appreciate if you are able to help by providing more details as to what should be edited and/or included. Thank you!

**Comment by RAJU2529** [comment]
@mypil . Points should be added if system gaurd enabled in registry key , then standard  hardware security  not available for Intel i5 7200U processor

**Comment by j0rt3g4** [comment]
Hello @RAJU2529 
Once again you need to be a bit more specific. Please recommend that part/items should be modified on the given article so we can proceed to add/discard the changes. thank you.

**Comment by RAJU2529** [comment]
@j0rt3g4. the below point should be added only , after other windows users should check in their laptops or desktop with atleast  intel 7th generation processors
point is 
**"if system gaurd enabled in registry key , then standard hardware security not available for Intel i5 7200U processor"**

**Comment by mypil** [comment]
@RAJU2529 - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/dc5ef67ba54687655f973d9c7aa490fca8f772c0. 

Thank you for your contribution to make the docs better! Much appreciated!
