### ISSUE TITLE
Monitor compliance before assigning a group or device

### ISSUE THREAD

**Issue by emgstabilis** [MicrosoftDocs/windows-itpro-docs#5456]
As an administrator I would like to monitor a device or group's compliance before assigning the security baseline to it. How can I do this ?

It would be useful to know the discrepancy beforehand, so as to better plan for the impact that setting the baseline will have on end users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2246e9c-193b-a110-ca52-2110a6e63631
* Version Independent ID: 7328d4a4-1944-c199-db72-a7e3cd350ae9
* Content: [Increase compliance to the Microsoft Defender ATP security baseline](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-machines-security-baseline#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-machines-security-baseline.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-machines-security-baseline.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by mypil** [comment]
@emgstabilis  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@emgstabilis When you configure the Security Baseline Profile you can select what gets applied and what does not, in order to meet your organizational requirements. Why would you not want the setting to be applied? 

![image](https://user-images.githubusercontent.com/41186174/69904789-99491a00-13b3-11ea-9d0f-e3565cbabae6.png)

Nevertheless, you could leverage the [MDM Diagnostic Information Log](https://docs.microsoft.com/en-us/windows/client-management/mdm/diagnose-mdm-failures-in-windows-10) to get more information about specific machines in terms of their security posture.

**Comment by emgstabilis** [comment]
Hi,

Thanks for your reply. Yes, it is indeed possible (and we appreciate it) to
customize the baseline. What I suggested, would be to highlight to the
administrator the places where the baseline differs from existing
configuration. And this, before assigning the baseline.

Best regards,

Evan Monroig

>

**Comment by VLG17** [comment]
Hi Evan,

i understand what you mean now. You want to know in advance who will be affected by the baseline and highlight their current configuration (in regards to what you selected in the baseline to get applied).

I think it's a really good feedback and would recommend to post it under the UserVoice Feedback Forums for [Azure](https://feedback.azure.com/forums/34192--general-feedback) and [ATP](https://microsoftsecurity.uservoice.com/forums/905791-azure-advanced-threat-protection-ata-in-the-cloud).

It's the best approach to get this feedback to the Product Group.

**Comment by mypil** [comment]
@emgstabilis - From our understanding, the issue you raised has been answered by VLG17 so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
