### ISSUE TITLE
Powershell command doesn't work

### ISSUE THREAD

**Issue by IJustKnowStuff** [MicrosoftDocs/windows-itpro-docs#5459]
Running the "Get-VpnConnection -Name Test" command doesn't any results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90843710-ba95-4eba-a69b-473e013877be
* Version Independent ID: 4a41937a-d268-8503-1860-16a25e327cc1
* Content: [EAP configuration](https://docs.microsoft.com/en-us/windows/client-management/mdm/eap-configuration#feedback)
* Content Source: [windows/client-management/mdm/eap-configuration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/eap-configuration.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Nothing wrong with that command -- it works as intended & expected. There must be something wrong on your end. Not a documentation issue.

![image](https://user-images.githubusercontent.com/38162891/69198726-f9c79400-0b35-11ea-940e-c7c7307cab04.png)

**Comment by mypil** [comment]
@IJustKnowStuff - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by illfated** [comment]
@IJustKnowStuff : You may want to make sure to save your EAP configuration before opening the PowerShell window and check that you open PowerShell as Administrator.
That is mostly what I did in addition to following this document procedure as direct as possible.
For me this worked, even on my Windows 10 Home edition computer.

**Comment by jaypatrick** [comment]
Same issue, calling InnerXml displays nothing. This is a saved and working profile we've been using for years. No Xml is displayed, but the info is displayed if just calling the variable itself, e.g. $a.

**Comment by illfated** [comment]
Again, I fail to see how to reproduce your issue. Here is my output (and I have not done anything 
related to this issue, only updated Win10 Home x64 to the newest build, since November):

![image](https://user-images.githubusercontent.com/38162891/76131426-adce2b80-600e-11ea-83c6-1097b330bfed.png)

This is my Win10 build info:

![image](https://user-images.githubusercontent.com/38162891/76131463-dbb37000-600e-11ea-8ced-bb7860ecb6d4.png)

**Comment by andy-vdg** [comment]
The command only works if you select: "Microsoft Secured password (EAP-MSCHAP v2) (encryption enabled)" in the Security settings under Authentication for an existing VPN connection. My existing VPN connection just had "Allow these protocols" selected in the Authentication section which resulted in no output when running $a.EapConfigXmlStream.InnerXml.

**Comment by illfated** [comment]
Thank you for your feedback. Even though that point is **already listed in step 7 and 8**, do you think there is something more we could do to make sure that others don't miss that important part of the procedure? In your opinion, should we add extra information to make sure users don't use a different setting than "**Microsoft Secured password (EAP-MSCHAP v2) (encryption enabled)**" in that part of the procedure, unless they actually want to use a different setting, knowing full well that a different choice at that point will make the result behave differently?

**Comment by itjhowe** [comment]
Not sure why this is closed, I've seen this issue on a number of computers and versions of PowerShell as well.

**Comment by IJustKnowStuff** [comment]
Sorry I should have come back and updated. Seems I forgot I asked this question. My issue here is because I had AllUserConnection tunnels connected. They were not being outputted in my command because I was not using the -AllUserConnection switch.

Using just "Get-VPNConnection" will ONLY display tunnels configured under the current user's profile.
Using "Get-VPNConnection -AllUserConnection" will show tunnels configured for all users on the device, and not tunnels configured under individual user accounts.
