### ISSUE TITLE
Computers with static IP address assignments?

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/windows-itpro-docs#5460]
While testing out in a network environment without DHCP service, I realise the Windows 10 initial setup procedure does NOT offer an interface to configure existing ethernet adapter with a static IP address/network setting in order to reach the Internet. All it showed was the useless screen listing the ethernet adapter and complaining it has not Internet access. I had branch into a separate flow to create a local user account and manually sign into Windows to configure the ethernet adapter.

Isn't that too late for Windows Autopilot to jump in and take care of the auto provisioning?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aafc065-6ee6-e3cf-31ba-ab3dd277fb23
* Version Independent ID: 35d3102e-4ff7-9408-8dbd-513b7dfff5c0
* Content: [Windows Autopilot requirements](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-requirements)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/windows-autopilot-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@icelava - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via **[Feedback Hub](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by icelava** [comment]
Had to do it the command-line method, https://social.technet.microsoft.com/Forums/windows/en-US/55e79e92-3c59-465a-9396-32cbfeee98ee/no-static-ip-address-config-for-initial-setup?forum=win10itprosetup#69529554-ad78-46fb-bae7-008c9c4c380d
