### ISSUE TITLE
Computers with static IP addresses?

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/windows-itpro-docs#5461]
"Connect it to a wireless or wired network with internet access."

During testing in an environment without any DHCP service, I realise Windows 10 initial setup only listed an unusable ethernet network adapter with no Internet access; and no option to configure it statically to get networking running.

How is Windows Autopilot supposed to work in this scenario?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2434dfb6-ac9a-4ba1-a681-88786c87010a
* Version Independent ID: 47e7470e-ab97-9917-04aa-4ec08a178af5
* Content: [Windows Autopilot User-Driven Mode](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/user-driven)
* Content Source: [windows/deployment/windows-autopilot/user-driven.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/user-driven.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@icelava - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via **[Feedback Hub](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by icelava** [comment]
Had to do it the command-line method, https://social.technet.microsoft.com/Forums/windows/en-US/55e79e92-3c59-465a-9396-32cbfeee98ee/no-static-ip-address-config-for-initial-setup?forum=win10itprosetup#69529554-ad78-46fb-bae7-008c9c4c380d
