### ISSUE TITLE
Option 18 is ambiguous

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#5462]
Option 18: Disabled:Runtime FilePath Rule Protection, The description is ambiguous.
Does it refer to files identified in a scan by their fully qualified path (the FilePath value of the -Level parameter of the New-CIPolicy cmdlet)? Or does it refer to the separate File Path Rule (the -FilePathRule parameter of the New-CIPolicyRule cmdlet)? Or both?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d4ecadb-c54e-5da1-03ae-1301a35ef64a
* Version Independent ID: 69d28732-f557-9ae1-cec4-594a2ec097a2
* Content: [Select the types of rules to create  (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@Air-Git  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello @Air-Git,
according to (Delivering major enhancements in Windows Defender Application Control with the Windows 10 May 2019 Update)[https://www.microsoft.com/security/blog/2019/07/01/delivering-major-enhancements-in-windows-defender-application-control-with-the-windows-10-may-2019-update/] it applies to the path specified in the FilePathRule parameter of the New-CIPolicyRule cmdlet.

**Comment by Air-Git** [comment]
I am afraid this is only repeating the ambiguity.
I think the answer is that it applies to both individual files (specified by file path) and to files specified by a path with wildcard.

**Comment by MaratMussabekov** [comment]
Dear @Air-Git, 
thank you, but don't you think this kind of clarifications belong to the article dedicated to [New-CIPolicyRule](https://docs.microsoft.com/powershell/module/configci/new-cipolicyrule) cmdlet, not to this article?

Dear @Dansimp,
could you please advise?

Thank you

**Comment by Air-Git** [comment]
The reason I comment on the documentation is to help make it as accurate as possible, for other engineers like myself. Otherwise we may spend hours or days experimenting to find out how the features actually work.

**Comment by mypil** [comment]
@Air-Git -  Thank you for submitting feedback.

From our understanding, the issue has been addressed based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/cd760b87d5ab7387f4c45fb8e28f61421ea27a7a. 


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by Air-Git** [comment]
The wording is now precise, but not accurate. An accurate statement is as follows:
"Disable default FilePath rule protection (apps and executables allowed based on file path rules must come from a file path that’s only writable by an administrator) for any FileRule that allows a file based on FilePath."

**Comment by illfated** [comment]
As you can see, I opened PR #5844 to add your suggested end part of the sentence "[ ... ] **for any FileRule that allows a file based on FilePath.**" to make it accurate, as you wrote above.

**Comment by Air-Git** [comment]
"FileRules" and "FilePath" are the terms used in the XML schema. "FilePathRule" is the name of the PowerShell parameter for New-CIPolicyRule, but this is only one of two ways to create a FileRule with a FilePath. That is the crux of the original ambiguity.
