### ISSUE TITLE
KQL table command list translated to German

### ISSUE THREAD

**Issue by illfated** [MicrosoftDocs/windows-itpro-docs#5463]
As described in issue ticket #5401 (**Documentation Translation**), the following table contains Kusto query operators which get translated to German (and perhaps other languages), when they should be ignored and kept as is:

- https://docs.microsoft.com/de-de/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-query-language#kennenlernen-allgemeiner-abfrageoperatoren-f%C3%BCr-erweitertes-jagen

|  English  |   German    |
| :-------  | :---------- |
| where     | where       |
| summarize | fassen      |
| join      | beitreten   |
| count     | Anzahl      |
| top       | top         |
| limit     | Limit       |
| project   | projizieren |
| extend    | Erweitern   |
| makeset   | makeset     |
| find      | find        |

The data types in English in the table below the problematic one (Grundlegendes zu Datentypen) stay untranslated, maybe because they are common international keywords (datetime, string, bool, int, long).

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b7522c47-aa38-2cf3-34b7-e8ad36dc80eb
* Version Independent ID: 6f26550f-0d21-479d-8479-b7bd563a2302
* Content: [Erlernen der erweiterten Jagd Abfragesprache](https://docs.microsoft.com/de-de/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-query-language)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-query-language.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-query-language.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by illfated** [comment]
Thanks to @OpaSieben for reporting the translation issue in the first ticket, even though it was posted on Github instead of from the Docs page.

**Comment by illfated** [comment]
This is another case where using MarkDown back ticks (code tags) could close off the affected text from being translated.

Feel free to suggest if I should create a PR to update the originating `EN-US` version of the page with MD code back ticks.

**Comment by mypil** [comment]
@illfated  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@tinamcn - Can you please assist with this Translation (Localization) issue?

Thank you.

**Comment by illfated** [comment]
Fair enough, my previously mentioned PR is now merged, 
making the originating en-us language version of the document 
available for editing regarding this issue, if desired. 
See https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5463#issuecomment-555505370.

**Comment by TinaMcN** [comment]
@illfated is there a way to lock those terms?   This topic is machine translated and the MT tool is looking at each individual word and translating it.  The same issue is happening on other languages.  I could send the topic for human translation but it would be better if we can find a solution to just block these terms.

**Comment by illfated** [comment]
Thank you for asking. Seeing that these data types are just regular English words, it is natural to assume that they would be translated automatically in the first place. (My detail-focused brain struggles to understand why some of them were not translated, but that is beyond the scope of our goal here.)

My immediate response would be to suggest enclosing all the data types in back ticks (code tags) to separate them from regular document text. Based on that, as well as your excellent point that this happens to more than one localized page (making the translation correction a multiplicative job), I find it very reasonable to open a PR to suggest enclosing the data types (keywords) to make a best effort to exclude these words from being translated by MT.

**Comment by illfated** [comment]
Interesting technical local detail in this issue: When I created this issue ticket from the de-de (localized German) page, it created a link to the Github page in the `master` branch instead of `public`. The interesting part is that the source page does not exist in the `master` branch, so I will edit the opening issue ticket comment to point the link to the `public` branch instead of `master`.

**Comment by illfated** [comment]
There you go, PR created and documented. Only the MD code tags (back ticks) were added inside the **`bold text`** formatting code.

**Comment by TinaMcN** [comment]
@illfated thank you for your help with this issue.  Once the updated English topic is updated the machine translated topics should be fixed within a day.    I share your puzzlement over why some of the terms were MT'd and others left in English!

**Comment by lomayor** [comment]
@illfated, thanks for this. I'll check my topics to ensure data types, operators, etc are enclosed in backticks.

**Comment by mypil** [comment]
@illfated - Please see this resolution comment https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5513#issuecomment-568569800 from the author. We hope this helps to resolve your issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by illfated** [comment]
Sure, no problem. Looking forward to when the updated public branch migrates to docs.microsoft.com .
