### ISSUE TITLE
Create a Surface Hub mobile device mailbox policy 

### ISSUE THREAD

**Issue by simonallisonuk** [MicrosoftDocs/windows-itpro-docs#5465]
Addition :- 

Set-CASMailbox "surfacehub@contoso.com"  -ActiveSyncMailboxPolicy "SurfaceHubDeviceMobilePolicy"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f34941d-2d96-fe83-57c5-405c97b565e1
* Version Independent ID: 9802b28b-21d9-60ef-e812-d469ad9ed1db
* Content: [Configure Surface Hub 2S on-premises accounts with PowerShell](https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-onprem-powershell#feedback)
* Content Source: [devices/surface-hub/surface-hub-2s-onprem-powershell.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/surface-hub-2s-onprem-powershell.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@simonallisonuk  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hello @simonallisonuk 
Thanks for your feedback and contribution, however I do not see a need to edit the current article to add this specific example, but your contribution will show up at the bottom of the article on the Article's feedback.
Thank you

**Comment by mypil** [comment]
@simonallisonuk - From our understanding, the issue you raised has been answered by get-itips. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
