### ISSUE TITLE
Outlook Web App URL's

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/windows-itpro-docs#5466]
Hello,
previously this web page, also stated URL for Outlook Web Access:
 - outlook.office.com

However it was missing, the attachments.office.net (which is resolved in #3747)

However, still outlook.office.com needs to be protected (attachments are going through other URL, however, we also protect things like copy/paste, taking screenshoots etc).

Another issue is that outlok.office.com is not enough since URL sometimes can also be outlook.office365.com 

Please check with product group and fix/update this documentation page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 255d1c9b-6b79-cb49-c230-84570daae489
* Version Independent ID: a2dcf5fd-c20d-c219-13f9-3e936036b368
* Content: [Recommended Enterprise Cloud Resources and Neutral Resources network settings with Windows Information Protection (WIP) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/recommended-network-definitions-for-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/recommended-network-definitions-for-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/recommended-network-definitions-for-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@hkusulja  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@hkusulja - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/56b69eca546af734fec32e808a0dfe416f50313d. 


Thank you for your contribution to make the docs better! Much appreciated!
