### ISSUE TITLE
"Upload file to library" option requires specific (tenant-level) permissions

### ISSUE THREAD

**Issue by s207307** [MicrosoftDocs/windows-itpro-docs#5469]
The "Upload file to library" function is not available to those with only delegated permissions via DATP RBAC roles.
Therefore, the "Put a file in the library" section of this document should reflect some sort of note that the account attempting to "Upload file to library" will need to have the appropriate tenant-level access--otherwise the "Upload file to library" button will be grayed-out since they do not have the necessary permissions to create a file at the tenant level.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6975a06a-6038-3d5e-30c4-7a31269359b8
* Version Independent ID: 2fdb3ee6-32d6-f0bd-55e5-d0c3b0fa44f0
* Content: [Investigate entities on machines using live response in Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/live-response?source=docs#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/live-response.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/live-response.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@s207307 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Hello, @s207307 This is a programmatic error that should be translated into support/direct feedback on the ATP product group.

https://office365.uservoice.com/forums/264636-general/suggestions/37756213-windows-defender-atp-standalone

**Comment by s207307** [comment]
Agreed. However, the current implementation of Live Response within Defender ATP has this issue, so the documentation here should reflect this limitation so that necessary workarounds can be established (until this specific roles/permissions shortcoming is fixed).

**Comment by j0rt3g4** [comment]
@s207307  agreed as well, Added note on PR #5604

**Comment by mypil** [comment]
@s207307 - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/d85ece3a95fb8f10d98c97b5b3867dec32037972. 


Thank you for your contribution to make the docs better! Much appreciated!
