### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by NoahGo-us** [MicrosoftDocs/windows-itpro-docs#5470]
after first paragraph above it says: "Ues the following information to get started with Windows Update:."   "Ues" should be "Use"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcc8a7ec-75d7-894c-9499-cbb4c3807ea7
* Version Independent ID: a4c97095-7c09-1bff-690d-90c8cdeee6c2
* Content: [Get started with Windows Update](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-overview)
* Content Source: [windows/deployment/update/windows-update-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by jaimeo** [comment]
Thanks for noticing this! BTW, you can actually help us make quick changes like this directly by using the Edit button on the live topic.

**Comment by illfated** [comment]
@NoahGo-us : Would you like to create the PR to fix that typo, or would you like me to do it? I don't mind at all, I am already in writing a different PR content for a different page. I just thought I should ask first, in case you felt like contributing beyond informing us of the typo (which in and of itself is a good start).

**Comment by NoahGo-us** [comment]
Ok, I went in and edited it myself. I don’t know if I did it correctly so please review as this is my first ever edit/usage of GitHub. 😊

**Comment by mypil** [comment]
@NoahGo-us - Can we ask for the PR # that you created for this so we can let jaimeo review and merge it? 

You can use this [Microsoft Docs contributor guide overview](https://docs.microsoft.com/en-us/contribute/index#quick-edits-to-existing-documents) as a reference in creating a Pull Request (PR). 

Thank you,

**Comment by NoahGo-us** [comment]
Well, maybe you guys should do the edit because I have no idea what a PR# is. I created a fork and edited it but like I said before, I’m new to GitHub so I have no clue what I’m doing.

**Comment by mypil** [comment]
@NoahGo-us - No worries. I created PR #5472 to fix and close this issue once the PR is merged.

Thank you for pointing out this typo error and we appreciate your contribution to make the docs better!
