### ISSUE TITLE
Defender ATP API Field Documentation is missing many fields

### ISSUE THREAD

**Issue by GeneCupstid** [MicrosoftDocs/windows-itpro-docs#5477]
[Microsoft Defender ATP detections API fields](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/api-portal-mapping) document is missing definitions for properties returned by ATP API.

I've attached a table of comparing fields returned by the API, and the corresponding field in documentation, if it exists (blank = missing in documentation)

In API | In Documentation
-- | --
Actor | Actor
AlertId | AlertId
AlertPart |  
AlertTime | AlertTime
AlertTitle | AlertTitle
Category | Category
CloudCreatedMachineTags |  
CommandLine |  
ComputerDnsName | ComputerDnsName
CreatorIocName |  
CreatorIocValue |  
Description |  
DeviceCreatedMachineTags |  
DeviceID |  
ExternalId |  
FileHash |  
FileName | FileName
FilePath | FilePath
FullId |  
IncidentLinkToWDATP |  
InternalIPv4List | InternalIPv4List
InternalIPv6List | InternalIPv6List
IoaDefinitionId |  
IocName |  
IocUniqueId |  
IocValue |  
IpAddress | IpAddress
LastProcessedTimeUtc | LastProcessedTimeUtc
LinkToWDATP | LinkToWDATP
LogOnUsers | LogOnUsers
MachineDomain | MachineDomain
MachineGroup |  
MachineName | MachineName
Md5 | Md5
RemediationAction |  
RemediationIsSuccess | RemediationIsSuccess
ReportID |  
Severity | Severity
Sha1 | Sha1
Sha256 | Sha256
Source |  
ThreatCategory |  
ThreatFamily |  
ThreatName | ThreatName
Url | Url
UserDomain | UserDomain
UserName | UserName
WasExecutingWhileDetected | WasExecutingWhileDetected

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e9ec713-7d81-465c-e7e0-9ecb4fc5024e
* Version Independent ID: 2c2f1ed7-4211-5e8c-ce7a-624a92edecd2
* Content: [Microsoft Defender ATP detections API fields](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/api-portal-mapping#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/api-portal-mapping.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/api-portal-mapping.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
As soon as the required information becomes available (somewhere else?), it should be an easy task to add it to this documentation page.

For now, I can only mention that the following cells on the same row as the missing fields need accompanying information:

|  Portal label  |      SIEM field name      | ArcSight field | Example value | Description |
| :------------: | ------------------------- | :------------: | ------------- | :---------- |
| (if available) | (from the API list above) |   (required)   | (recommended) | (required)  |

**Comment by akefallonitis** [comment]
Also fields like status and classification should be available in order to retrieve those that are active alerts
e.g unresolved + true alerts

Is it possible ?

**Comment by illfated** [comment]
@e0i ; I had forgotten about this ticket, do you think we should ask the document author if the table needs updating with more information?

**Comment by mjcaparas** [comment]
I have reached out to the dev team and some updates to the document are in the pipeline.

**Comment by aczechowski** [comment]
Doing some repo cleanup...I'm going to close this issue for two reasons:

1. There was a pull request that referenced this issue in August 2021 (although I'll be honest, I didn't dig into the details)
2. More importantly, this article isn't in this repo anymore. If you still have feedback on the article, please file feedback against the current version: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/configure-siem
