### ISSUE TITLE
bad link in https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/deployment-vdi-windows-defender-antivirus#additional-resources

### ISSUE THREAD

**Issue by amirsc3** [MicrosoftDocs/windows-itpro-docs#5485]
The link on "SignatureDownloadCustomTask PowerShell script" should be pointing to 
https://www.powershellgallery.com/packages/SignatureDownloadCustomTask/1.4 

Current link leads to:
https://www.powershellgallery.com/packages/SignatureDownloadCustomTask/1.4/DisplayScript 
Which ends up as 404 error:
https://www.powershellgallery.com/Errors/404?aspxerrorpath=/packages/SignatureDownloadCustomTask/1.4/DisplayScript

**Comment by illfated** [comment]
Adding the link in comment text, just to be able to click and go to that page easier than copy-pasting it:
- https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/deployment-vdi-windows-defender-antivirus#additional-resources

```diff
- https://www.powershellgallery.com/packages/SignatureDownloadCustomTask/1.4/DisplayScript
+ https://www.powershellgallery.com/packages/SignatureDownloadCustomTask/1.4
```
Slightly weird URL behaviour noticed: if you go to the existing linked page (`DisplayScript`) and remove that part of the URL so it looks exactly like the working one, my web page refuses to open the working page.
Odd behaviour, but this sometimes happens with 404 pages.

**Comment by illfated** [comment]
Thank you for pointing out the 404 link and also for providing the working link.

To get the related content linked automatically. post directly on the doc page.
(I am aware that this may limit the editing options for URLs & rich text)
