### ISSUE TITLE
graphical diagram looks great

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#5493]
I love graphical diagram which explains the unexplained thoughts in some situations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9295da4-794f-85fa-0268-5f9632334ae8
* Version Independent ID: d36f3802-e631-7415-87cc-c5abeafdc5ca
* Content: [Windows Defender System Guard How a hardware-based root of trust helps protect Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-system-guard/system-guard-how-hardware-based-root-of-trust-helps-protect-windows)
* Content Source: [windows/security/threat-protection/windows-defender-system-guard/system-guard-how-hardware-based-root-of-trust-helps-protect-windows.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-system-guard/system-guard-how-hardware-based-root-of-trust-helps-protect-windows.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thank you @RAJU2529 for your feedback!
