### ISSUE TITLE
Missing Microsoft Download Center links for some Surface models

### ISSUE THREAD

**Issue by vukelich** [MicrosoftDocs/windows-itpro-docs#550]
Some of the older devices have links directly to the download center. It's missing for Surface Pro, Pro with LTE, Laptop, and Book 2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586d1246-6e18-b33c-2382-52a53bb392f5
* Version Independent ID: 0ec4aa1e-aac0-98dd-0a47-83e93d854086
* Content: [Download the latest firmware and drivers for Surface devices (Surface) | Microsoft Docs](https://docs.microsoft.com/en-us/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices)
* Content Source: [devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md)
* Service: **unspecified**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by shortpatti** [comment]
@jdeckerms -- Can you take a look at this issue?

**Comment by jdeckerms** [comment]
@BRecords for Surface issues

**Comment by jdeckerms** [comment]
@vukelich The links will be added and published later today, thanks for pointing it out!

**Comment by sazzaria** [comment]
Another one missing: 
Surface 2 
Surface Pro 2 has full windows, while Surface 2 has Windows 8.1 RT.

Please add?
Here's the specs...
Windows 8.1 RT 32bit for ARM devices
CPU: Nvidia Tegra 4 (ARM v7-A, Cortex A15)
https://support.microsoft.com/en-us/help/4037663/surface-surface-2-specifications
