### ISSUE TITLE
Requesting additional details regarding the Live Response library

### ISSUE THREAD

**Issue by s207307** [MicrosoftDocs/windows-itpro-docs#5500]
Is there more information and detail regarding the "library"? For example, what (if any) is the capacity for each file size? Does the entire library have a size limit? A number of files within the library limit? Where on the 365 tenant does the actual library (the file store) exist? Is the library accessible via API or other means (such as the Azure tenant)? ETC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6975a06a-6038-3d5e-30c4-7a31269359b8
* Version Independent ID: 2fdb3ee6-32d6-f0bd-55e5-d0c3b0fa44f0
* Content: [Investigate entities on machines using live response in Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/live-response?source=docs#put-a-file-in-the-library)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/live-response.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/live-response.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by vboyev-MSFT** [comment]
The library is MDATP Tenant specific and it resides within. Not sure about the API questions, I can try to find out.
