### ISSUE TITLE
Intune not listed as a servicing tool?

### ISSUE THREAD

**Issue by make4fun** [MicrosoftDocs/windows-itpro-docs#5502]
I would like to see Intune listed here as a servicing tool here and relevant guidance provided for it on this page. That in my view, would complete this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6957383-3bd9-eef9-6410-9c42f8a0b172
* Version Independent ID: a2090374-0fd1-8d67-66de-30c4cf2835f7
* Content: [Overview of Windows as a service (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-overview#feedback)
* Content Source: [windows/deployment/update/waas-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment]
@make4fun. I welcome your idea, intune should be added in this article.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by okbus** [comment]
Do we need a premier support from Microsoft to go through SAC serving channel ?

**Comment by jvsam** [comment]
Hi @make4fun, there is a separate *technical doc set* for Intune to *[Manage Windows 10 software updates](https://docs.microsoft.com/intune/protect/windows-update-for-business-configure)*. Intune related docs are consolidated to avoid confusion. Also, there is a related link that redirect users to the Intune doc set. If you believe that's not enough, let us know what specific information (*or messaging or sample copy*) you want to see on this doc—keeping in mind that Intune related topics are separate—so we can submit for consideration. 

> Do we need a premier support from Microsoft to go through SAC serving channel ?

As for your question, have you tried contacting [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) to confirm? You may want to check these content pages - [Windows lifecycle fact sheet](https://support.microsoft.com/help/13853/windows-lifecycle-fact-sheet), [Modern Lifecycle Policy](https://support.microsoft.com/help/30881/modern-lifecycle-policy) and [FAQs](https://support.microsoft.com/help/14085/fixed-lifecycle-policy). There are also other support resources that are available for you like the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can post your question and get help from the community. Thank you.

**Comment by make4fun** [comment]
@jvsam - The purpose to put it all in one place is completeness and better understanding. As customers and implementers of MS products, we expect to find documentations that are in one place and not broken up into multiple articles and that too with no links to the other. Structured documentation will go a long way to help customers make more sense of MS products' functionalities.

`Do we need a premier support from Microsoft to go through SAC serving channel ?` - This comment was added by someone else. Probably better to direct the response to him.

Thanks.

**Comment by jvsam** [comment]
Hi @make4fun we appreciate your feedback. Please note that the docs are a continuous work in progress and the MS authors have a documentation and style guide that they follow on how to organize and write contents for MS users. What I recommend is for you to submit your feedback on [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub) and give your suggestions on how the docs can be better. 

Also, this GitHub-based documentation feedback system is designed to allow community contributions. If you have suggestions or ideas and you want the MS authors to review and apply (*if approved*) the changes immediately, I suggest that you create a Pull Request (PR) and start contributing to Microsoft Docs, if you are familiar with the process. You can check and read the [Microsoft Docs contributor guide](https://docs.microsoft.com/en-us/contribute/), if you are interested. The content page contains information on working with GitHub repositories, Markdown tools, etc. You can also let us know what specific content you want to add, how it should be written, etc. and and we can have a community user or someone from the content writing team create the PR on your behalf. Thank you again.

By the way, in the *Overview of Windows as a service* document, there is a related link that directs the user to the Intune doc. Please see the *Related Topics* at the bottom of the page.

![image](https://user-images.githubusercontent.com/18371314/71320420-07ca5500-24e6-11ea-8b49-e142b5e7ceaf.png)

**P.S.** Missed the question about the premier support. @okbus, please see my [comment](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5502#issuecomment-565721948).

**Comment by denisebmsft** [comment]
Thanks all for your feedback and help. It looks like there isn't a specific documentation issue here, so I'm closing this out with kind regards.
