### ISSUE TITLE
typo in manual execution

### ISSUE THREAD

**Issue by emarana** [MicrosoftDocs/windows-itpro-docs#5507]
mdatp --edr --earlyPreview true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c91a5cfb-d32d-3864-c1d5-aec39558f66f
* Version Independent ID: dbd2647e-88a6-ff22-4eab-ef628ac2e605
* Content: [Enable Microsoft Defender ATP Insider Machine](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/endpoint-detection-response-mac-preview#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/endpoint-detection-response-mac-preview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/endpoint-detection-response-mac-preview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
See also issue ticket #5368
and PR #5378 (rejected).

See also issue ticket #5402
plus PR #5473 & #5474 .

**Comment by levinec** [comment]
I'm updating documentation to address this confusion. Will be live tomorrow.
