### ISSUE TITLE
Problematic instructions for SCCM's device report

### ISSUE THREAD

**Issue by aceoforder** [MicrosoftDocs/windows-itpro-docs#5510]
Hi, there are some amendments needed to instructions for SCCM's AutoPilot export report.

Your instructions note that the Autopilot Report from SCCM can be exported as a .CSV file and then uploaded directly into Intune. This does not work and results in an "Incorrect Headers" error by Intune.

The following instructions were taken from a TechNet support post. THESE instructions properly format the .CSV file from SCCM into something consumable by Intune:

It looks like the report from SCCM exports with a header from the report viewer as well as a row that sort of describes each of the columns. Columns A, B, and C are going to be the same on all rows. That is actually what you need to have as your headers for Columns D, E, and F.

I opened it in Excel to make it easier. 

Once in Excel, I deleted rows 1-3 and cleared the values from the new row 1 (formerly row 4).

Copy the values of A2, B2, and C2. Paste them to D1, E1, and F1 respectively. Then delete columns A, B, and C.

Save that and you should be able to upload it to Intune without issue.

Proposed as answer by Socratio Tuesday, November 19, 2019 8:45 PM
Marked as answer by zolabus Wednesday, November 20, 2019 8:18 AM

https://social.technet.microsoft.com/Forums/en-US/3d82e372-2386-4233-96f2-25087ade6e52/autopilot-csv-from-sccm-report

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3243b015-5b5f-7a62-0d9d-767d729dc475
* Version Independent ID: ff8c0509-c075-8528-823f-c195ff4d2382
* Content: [Adding devices](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/add-devices#feedback)
* Content Source: [windows/deployment/windows-autopilot/add-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/add-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @aceoforder, thank you for bringing this to our attention. Let me get this over to the Windows content writing team for review. We always strive to improve the quality of the technical documentation of Microsoft Docs so your feedback is appreciated.

Thank you for being part of the Microsoft Docs Community!

**Comment by e0i** [comment]
@aceoforder 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
