### ISSUE TITLE
Surface Laptop 3, Pro 7, Pro X

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/windows-itpro-docs#5512]
This page is missing guidance on the latest (now released) Surface hardware. The following statement is now incorrect: "Information about MSI files for the newest Surface devices such as Surface Pro 7, Surface Pro X, and Surface Laptop 3 will be available from this page upon release."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586d1246-6e18-b33c-2382-52a53bb392f5
* Version Independent ID: 0ec4aa1e-aac0-98dd-0a47-83e93d854086
* Content: [Deploy the latest firmware and drivers for Surface devices (Surface)](https://docs.microsoft.com/en-us/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices?source=docs)
* Content Source: [devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @CHDAFNI-MSFT thank you for your feedback. The documentation has been updated to avoid confusion. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
