### ISSUE TITLE
Outdated CAS information

### ISSUE THREAD

**Issue by nchambe** [MicrosoftDocs/windows-itpro-docs#5514]
The Cloud Discovery dashboard no longer resembles the screenshots and does not offer continuous report &gt; Win10 Endpoint Users as an option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70acebee-16af-18f5-4069-1e4ae0d71fc6
* Version Independent ID: 1dfed329-80c0-b9aa-f168-31f15b43866d
* Content: [Configure Microsoft Cloud App Security integration](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-cloud-app-security-config#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-cloud-app-security-config.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-cloud-app-security-config.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for bringing this to our attention @nchambe. I will get this over to the Windows content writing team for review and to suggest updating the screenshots and instructions similar to this [related doc](https://docs.microsoft.com/cloud-app-security/wdatp-integration). We always strive to improve the quality of the technical documentation of Microsoft Docs so your feedback is appreciated!

Thank you for being part of the Microsoft Docs Community!

**Comment by jvsam** [comment]
Hello @nchambe, thank you again for sharing your feedback. We will now close this issue since it has been resolved and updates are now displayed here at docs.microsoft.com. Please continue to send your feedback and suggestions to help improve the quality of the technical documentation of Microsoft Docs. Thank you for being part of the community!

**Comment by jvsam** [comment]
@officedocsbot close
