### ISSUE TITLE
confusing phrasing about requirements

### ISSUE THREAD

**Issue by marypcbuk** [MicrosoftDocs/windows-itpro-docs#5515]
"Requirements Met by System Guard Enabled Machines
Any machine with System Guard enabled will automatically meet the following low-level hardware requirements"
this doesn't make sense: it would mean that turning it on would magically give you the right hardware! clearer to say that you will only be able to enable System Guard if these requirements are met.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31d623d9-316c-0ef1-b6be-c3773d77ca21
* Version Independent ID: 83ddb59d-0cfc-34f2-e666-8927d86a04a7
* Content: [System Guard Secure Launch and SMM protection (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection)
* Content Source: [windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by marypcbuk** [comment]
it would also be helpful to note which of these requirements are for organizations to check their PCs against and which are information for OEMs building PCs for System Guard.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you @marypcbuk. We always strive to improve the quality of the technical documentation of Microsoft Docs so your feedback is appreciated!

@illfated, do you want to take this and create the PR with Mary's suggestion? Thanks, as always!

**Comment by illfated** [comment]
Sure, I can at least say that I agree that the first sentence looks like the logic is reversed, at least when it comes to talking about hardware requirements. My initial idea is that the sentence should instead say something to the effect of already being able to meet the low-level hardware requirements. In this case, I would say something like
> Any machine with System Guard enabled has already met the following low-level hardware requirements:

When it comes to the part of differentiating between OEM requirements and requirements for organizations (if different), I would need a pointer for if this is a known and practical separation, and what the difference is (if this is documented elsewhere).

**Comment by illfated** [comment]
Oh well. I can always start with suggesting the sentence change in a PR, then simply wait for feedback from either @marypcbuk or you in the PR regarding if there are sources for the OEM separation out there.

**Comment by RAJU2529** [comment]
I appose  the statement, because in some computers enabled with system guard does not meets low level hardware requirements . I have tested on my laptop when system guard is enabled , then standard security does not supported

**Comment by marypcbuk** [comment]
OK rather than saying 'any PC that has System Guard enabled must have met the requirements to run System Guard' which isn't helpful to the reader, maybe I can make some more concrete suggestions for what would be clearer

Requirements Met by System Guard Enabled Machines
->
System Requirement for enabling System Guard

Any machine with System Guard enabled will automatically meet the following low-level hardware requirements:
->
In order to enable System Guard, your hardware will need to meet the following low-level hardware requirements:

to the wider point about admin/OEM: the page appears to be aimed at admins telling them how they can enable and manage System Guard. but some of the requirements look as if they're more instructions to OEMs (eg Platform firmware must set up a TPM NV index for use by the OS with:  Handle: 0x01C101C0, All SMM communication buffers must be implemented in EfiRuntimeServicesData ,EfiRuntimeServicesCode , EfiACPIMemoryNVS, or EfiReservedMemoryType memory types, Must NOT contain any mappings to EfiConventionalMemory (e.g. no OS/VMM owned memory). 
Must NOT contain any mappings to code sections within EfiRuntimeServicesCode. 
Must NOT have execute and write permissions for the same page 
Must allow ONLY that TSEG pages can be marked executable and the memory map must report TSEG EfiReservedMemoryType. 
BIOS SMI handler must be implemented such that SMM page tables are locked on every SMM entry etc). I was just thinking it might be useful to cover when these are things that admins will be able to check and when they're things OEMs need to know, to make it clearer for the reader if they're the target audience.

**Comment by RAJU2529** [comment]
@marypcbuk.  did you tested on your desktop or on laptop. For testing  purposes just add registry key for system guard.

and then restart the windows. you will see the difference.

Could you tell me the model number  of intel processor is embedded in  your computer

**Comment by marypcbuk** [comment]
I haven't done any testing; I'm just talking about the clarity of the document

**Comment by illfated** [comment]
@JohanFreelancer9 : May I ask you for a comment regarding the comment above, containing additional suggestions for changes to the document? If you have got time to take a look, would it be useful to suggest those changes in my current PR? In case you don't know the topic well enough, should we ask someone else on the tech writing team to comment on the suggestions?

**Comment by JohanFreelancer9** [comment]
@illfated Unfortunately I do not know the topic well enough to be of any help here. On the face of it, it makes a lot of sense to include these additional suggestions in your PR, but I would rather suggest you ask someone on the tech writing team to comment.

**Comment by illfated** [comment]
Very well, I will do that. Thank you for commenting and replying to my questions.
@jvsam : I will ask @VLG17 for now, but feel free to suggest others if you know who on the tech writing team would be in a good position to confirm the suggestions.

@VLG17 : Would you be able to verify or validate the suggestions from marypcbuk in comment https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5515#issuecomment-566082006 ?

**Comment by illfated** [comment]
I have decided to close my PR #5694 and defer to #5734 by joinimran .

**Comment by jvsam** [comment]
Hello @marypcbuk, thank you again for sharing your feedback. We will now close this issue since the document has been updated. Please continue to send your suggestions to help improve the quality of the technical documentation of Microsoft Docs. Thank you for being part of the community!

**Comment by jvsam** [comment]
@officedocsbot close
