### ISSUE TITLE
Windows Firewall Log issues

### ISSUE THREAD

**Issue by MichaelFirsov** [MicrosoftDocs/windows-itpro-docs#5519]
Hello,
Based on my experience, configuring firewall loging using domain GPO according to this article - https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/configure-the-windows-firewall-log - leads to one of these problems (all settings are at their defaults, logging is enabled for both dropped and allowed packets):

1) Windows Firewall folder AND the log get created, for some time the log gets populated with log records  then logging stops - for example it may have been logging till 20.11.2019 and after 20.11.2019 no additional log records can be seen in the log,

2) Windows Firewall folder AND the log get created but the log file contains only the field names  - no dropped or allowed packet is ever registered in the log,

3) Windows Firewall folder is created but the log file is not

4) Windows Firewall folder does not get created.

In fact I failed to have correctly working firewall logging in my Windows Server 2008R2 and Windows Server 2019 domains.

On the other hand I haven't yet had  any issues configuring firewall logging locally - without using domain-based GPOs.

**Comment by mypil** [comment]
@MichaelFirsov - Thank you for submitting feedback.

Can you please share what specific issue you have with this doc? Or are you having some technical issues which requires technical support?

If you have some issues with this doc, we would really appreciate if you are able to help by providing more details as to what should be edited and/or included. Thank you!

**Comment by mypil** [comment]
@MichaelFirsov - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.

**Comment by MichaelFirsov** [comment]
I must apologize for delaying the answer - please excuse me for this! "Or are you having some technical issues which requires technical support?" - I just wanted to point out that configuring firewall logging in strict accordance with this article may lead to not working logging in many cases and (providing I have tested several different domains) I can't say for sure whether the article lacks some information or this "feature" just not works as expected.

**Comment by illfated** [comment]
I noticed your comment in issue ticket #2015 -- is that ticket directly related to this one here? Are there any comments in that ticket which may be useful for your issue?

Maybe it would be more useful to reopen a ticket from the feedback section https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/configure-the-windows-firewall-log#feedback to get the ticket linked directly back to the page in question, for easier referencing.

**Comment by MichaelFirsov** [comment]
_"is that ticket directly related to this one here?"_ - not sure... That issue arises when the logging had been working for some time but then has stopped. The new one (#5519) describes a situation when the logging never starts working at all. 
Frankly speaking I don't know whether I should open tickets in the "documentation sections" here as I think that's really not the documentation issue(s) but rather the technical problems as mypil pointed out above. For me that's the only way to say something is not working in Windows because I can't open a support case on each issue I see.

**Comment by illfated** [comment]
OK, fair enough. You may want to use the TechNet forum pages instead to get a broader feedback from tehcnical users who might be able to help you with detailed suggestions for troubleshooting.

**Comment by MichaelFirsov** [comment]
Yes, I understand - thank you!
