### ISSUE TITLE
Could you please provide an example? I am interested in Surface GO uefi settings from intune.

### ISSUE THREAD

**Issue by loriand71** [MicrosoftDocs/windows-itpro-docs#5520]
[Ide írja be a visszajelzését]

---
#### A dokumentum adatai

⚠ *Ezt a szakaszt ne szerkessze. A szakasz a docs.microsoft.com ➟ GitHub-problémák hivatkozásaihoz szükséges.*

* ID: fd336518-8c61-8497-3881-890e8653da5e
* Version Independent ID: e6aee767-8226-64fe-5756-1a698df24154
* Content: [UEFI CSP](https://docs.microsoft.com/hu-hu/windows/client-management/mdm/uefi-csp#feedback)
* Content Source: [windows/client-management/mdm/uefi-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/uefi-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by loriand71** [comment]
Especially to turn on the "battery limit".

**Comment by j0rt3g4** [comment]
Added PR #5564

**Comment by illfated** [comment]
Ref. #5530

**Comment by illfated** [comment]
PR #5578 has been merged into the public branch here on Github. 
It may take a few days before the content is available on docs.microsoft.com .

**Comment by mypil** [comment]
@loriand71 - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/eb5d6fa7437fa05d5a35d611480a7d300933e691. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
