### ISSUE TITLE
Event ID 4625 is missing!

### ISSUE THREAD

**Issue by robertstrom** [MicrosoftDocs/windows-itpro-docs#5521]
I used this as a resource when configuring WEC and several months later I discovered that I was not collecting EventID 4625: An account failed to log on.

It would seem that this is a MUST have event ID and that is was a definite oversight. Please update this so that others don't have the same (huge) gap in their log collection.

Thanks, Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5862cc7-3f36-5f2e-9ade-f7441f99f818
* Version Independent ID: b8bd1985-7b5b-ea79-976a-7d96ad69335c
* Content: [Use Windows Event Forwarding to help with intrusion detection (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection#feedback)
* Content Source: [windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@robertstrom  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Added information on PR #5572

**Comment by mypil** [comment]
@robertstrom - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/ded7bd9524d1052bbdc9801a148add93ee700dfe. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
