### ISSUE TITLE
The content of the comparison is duplicate, incorrect

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/windows-itpro-docs#5522]
"The following is an example of a good connection setup:..."
and
"The following is an example of a failed connection setup:..."

The content of the comparison is duplicate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 270b90db-95ba-da60-5559-4f6f3a3bd51c
* Version Independent ID: 8c7dca99-967f-13af-bc15-26d4434f4936
* Content: [Advanced Troubleshooting Wireless Network Connectivity](https://docs.microsoft.com/en-us/windows/client-management/advanced-troubleshooting-wireless-network-connectivity)
* Content Source: [windows/client-management/advanced-troubleshooting-wireless-network-connectivity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/advanced-troubleshooting-wireless-network-connectivity.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@goxia - Thank you for submitting feedback.

Upon checking the doc, the content of the comparison does not appear to have any duplication. Please see the below screenshot on the difference in the Authenticating to State portion.

![image](https://user-images.githubusercontent.com/47188252/69636629-fbdba680-1091-11ea-807c-8f19bbce72a2.png)

**Comment by goxia** [comment]
@mypil - Thank you a lot.
