### ISSUE TITLE
OPAL support

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-itpro-docs#5523]
What about the support for OPAL disks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1bca5a-6ce4-a102-3093-6b13618a062e
* Version Independent ID: dd1301a5-401b-5b64-2604-54565c77e650
* Content: [Using BitLocker with other programs FAQ (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-using-with-other-programs-faq#feedback)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-using-with-other-programs-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-using-with-other-programs-faq.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@LuigiBruno   - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
