### ISSUE TITLE
Windows Restricted Traffic Limited Functionality Baseline - Domain Controller

### ISSUE THREAD

**Issue by epon** [MicrosoftDocs/windows-itpro-docs#5525]
Hi,

What is the correct approach for applying the Windows Restricted Traffic Limited Functionality Baseline across an Active Directory network with a domain controller?

The package nor the online docs don't seem to document this kind of setup. 

Is the LGPO script supposed to be executed locally on each machine or is there a way to use the central store and network group policy to automatically roll out the settings to all machines/domain controllers?

The Server and Enterprise folders would seem to contain different ADMX/ADML files although they are identically named; this would cause conflicts if trying to put them in the central store.

Regards.

**Comment by mypil** [comment]
@epon - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by epon** [comment]
https://docs.microsoft.com/en-gb/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services

**Comment by mypil** [comment]
@epon - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  https://support.microsoft.com/hub/4338813/windows-help?os=windows-10

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
