### ISSUE TITLE
Footnotes fon't refer to any footnotes

### ISSUE THREAD

**Issue by tr5tn** [MicrosoftDocs/windows-itpro-docs#5526]
The Footnotes on this page https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-appruntime and (I think) many other Policy CSP pages seem to have been copied from another page, as there are not footnotes in the body text, just the references at the bottom. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3d74533-84c9-2610-88f5-13342a0073e1
* Version Independent ID: f3538e4a-2986-b46a-e03c-de84143a45d6
* Content: [Policy CSP - AppRuntime](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-appruntime#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-appruntime.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-appruntime.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@tr5tn  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by illfated** [comment]
PR #5680 has been created to resolve this issue ticket.

**Comment by mypil** [comment]
@tr5tn  - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/4c21ab4 but it may take a few days for the merged content to appear in the article. 

Thank you for your contribution to make the docs better! Much appreciated!
