### ISSUE TITLE
More examples please

### ISSUE THREAD

**Issue by JoshTech1** [MicrosoftDocs/windows-itpro-docs#5527]
What bit value would represent Windows' default options?
What bit value would represent running: bcdedit /set {current} nx OptOut
What bit value would represent running: bcdedit /set {current} nx OptIn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f776e86a-0390-f26a-167e-f782cb137b33
* Version Independent ID: 149f955c-3927-487e-20fe-7d7e7df27131
* Content: [Override Process Mitigation Options to help enforce app-related security policies (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/override-mitigation-options-for-app-related-security-policies#feedback)
* Content Source: [windows/security/threat-protection/override-mitigation-options-for-app-related-security-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/override-mitigation-options-for-app-related-security-policies.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@JoshTech1  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello, @JoshTech1,

**What bit value would represent Windows' default options?** - there is no such value. However, in most situations, "?"  could be used (it represents the existing value)
**What bit value would represent running: bcdedit /set {current} nx OptOut/OptIn** - the policy “Process Mitigation Options” is configuring behavior for individual files, while "bcdedit /set" configures DEP for classes of processes (more details [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/bcdedit--set)). So it is impossible to achieve the same result as bcdedit /set {current} nx OptOut/OptIn using this policy.

Thank you
