### ISSUE TITLE
why can't I enter the error code and get the info on that.

### ISSUE THREAD

**Issue by Romney57** [MicrosoftDocs/windows-itpro-docs#5528]
As the title explains, I want a facility to enter the error code and get the info and any fixes or workaround related to that error code number.  The error code I have is not listed in this article despite it beginning with 0x800???   Where do I go from here???   Poor show from such an almighty company.   Maybe including a read me file on the installation USB with some general information on what to do before installation to avoid all of these common pitfalls??

So what do I do to rectify a 0x8007001F - 0x20006  The installation failed in the SAFE_OS phase with an error during REPLICATE-OC operation   ?????????  

This is meaningless technobabble that one of your engineers might understand, but even for someone computer savvy like me it is still meaningless.   So why wasn't the remedy included on the infographic when the error flagged up on my screen???

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 528014e0-02e5-2d77-a229-4895731bb872
* Version Independent ID: 4f46b620-e345-c9e4-70fa-ae4f5a8e48b9
* Content: [Resolution procedures - Windows IT Pro](https://docs.microsoft.com/en-gb/windows/deployment/upgrade/resolution-procedures#feedback)
* Content Source: [windows/deployment/upgrade/resolution-procedures.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/resolution-procedures.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@Romney57 - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
