### ISSUE TITLE
The header for section "Profile extension for each Windows version" is incorrectly formatted

### ISSUE THREAD

**Issue by andresaltamiranom** [MicrosoftDocs/windows-itpro-docs#5529]
Instead of seeing the header bold and in a larger size, it shows as regular text, preceded by two hash symbols and a space: "## Profile extension for each Windows version".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9ca7cb6-32cb-1517-a9de-c36046955d45
* Version Independent ID: 91041e39-007e-f481-0cd4-177b4039ae12
* Content: [Create mandatory user profiles (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/mandatory-user-profile#feedback)
* Content Source: [windows/client-management/mandatory-user-profile.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mandatory-user-profile.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@jvsam. just now I created PR #5539

**Comment by mypil** [comment]
@andresaltamiranom - Thanks for submitting feedback.

PR #5539 has been created by @RAJU2529 to fix and close this issue once the PR is merged.

@RAJU2529 - Thanks for creating the PR for this issue.


We appreciate your contribution to make the docs better!

**Comment by illfated** [comment]
Also, as I mentioned in my comment in the PR:

The hidden HTML code <span id="extension"/> directly preceding the heading line causes this MD section H2 heading formatting to break.

**Comment by RAJU2529** [comment]
@illfated. Sir do you require any changes from my side in PR?

**Comment by illfated** [comment]
No, nothing to worry about. The PR is just fine as it is, straight forward and to the point.

I simply wrote my previous comment here, in case someone else would read this issue page without visiting your PR content.

**Comment by mypil** [comment]
@andresaltamiranom - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/c0a80644fb66c10ee1748837c6fe57dc6d4cbf60. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
