### ISSUE TITLE
certutil typo?

### ISSUE THREAD

**Issue by brianmulford** [MicrosoftDocs/windows-itpro-docs#5532]
Based on testing - the certutil command should have spaces not commas
Current doc: certutil -dsTemplate WHFBAuthentication,msPKI-Private-Key-Flag,+CTPRIVATEKEY_FLAG_HELLO_LOGON_KEY
When running that as is in lab, it doesnt add the flag to the template.
Running this: certutil -dsTemplate WHFBAuthentication msPKI-Private-Key-Flag +CTPRIVATEKEY_FLAG_HELLO_LOGON_KEY
Updates the key and shows that it updated in the window

Once I re-ran the command with spaces, my windows 10 machines started the provisioning process

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd063d0c-8739-15bd-4f16-11b893029845
* Version Independent ID: cd3679fe-dd9c-44f9-04ed-c772a47ca4e4
* Content: [Configuring Hybrid Windows Hello for Business - Public Key Infrastructure (PKI)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by MaratMussabekov** [comment]
Fixed by https://github.com/MicrosoftDocs/windows-itpro-docs/commit/77de958be555c779c29a44b8338754759ca275cf#diff-226bfeb1bd9d43422f555e11649463c0

**Comment by illfated** [comment]
Commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/77de958be555c779c29a44b8338754759ca275cf confirmed. Issue ticket resolved.

**Comment by robmacf** [comment]
Can confirm that spaces, not commas are correct. Note that certutil reports "CertUtil: -dsTemplate command completed successfully" even when the certutil -dstemplate command did not complete succesfully. (Opened another issue to help distinguish success vs. failure.

**Comment by illfated** [comment]
Thanks, found it. #5869 (**Add verification info for certutil -dsTemplate command**)
