### ISSUE TITLE
Contradicting Documentation

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/windows-itpro-docs#5533]
This documentation page says to enable Block at First site, the following setting must be enabled:
Cloud-delivered protection: Enable
However, there is another Microsoft documentation page that contradicts this and says it must be set to "Not Configured" - and then in the GitHub closed cases, if it is set to Enabled, that it actually means Cloud-delivered protection is Disabled 
"On the Cloud-delivered protection switch, select Not configured"
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus
see the GitHub case https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3762
I also raised this question on Twitter to @HeikeRitter here: https://twitter.com/ITguySoCal/status/1199488449562075136

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bd0fe29-5db5-b752-5bcf-5ac2581baa9a
* Version Independent ID: 52b8d4ca-54ea-7345-12b0-df4fdf633083
* Content: [Enable Block at First Sight to detect malware in seconds](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus#confirm-block-at-first-sight-is-enabled-with-intune)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by thedrum808** [comment]
@itguysocal - I left feedback on the page about the "Disabled" behavior being wrong, and they have since fixed it. Use "Enabled" for this feature to work.

**Comment by itguysocal** [comment]
Thank you! We sincerely appreciate your assistance with this.

**Comment by MaratMussabekov** [comment]
Hello, it was also updated in https://github.com/MicrosoftDocs/windows-itpro-docs/commit/013b884b81a229feeffd19a5e87c8dcf7ae67409#diff-e005977fddffcd799314f7b459488ab9
Also was discussed in #5451
