### ISSUE TITLE
Forgot an important detail

### ISSUE THREAD

**Issue by trboomer** [MicrosoftDocs/windows-itpro-docs#5534]
When you want to use a USB stick to do an offline deployment, you must split the wim. The control folder contains settings.xml that has a setting call skipsplitwim and it is enabled by default. USB's must use fat32 to be bootable, and the wim file cannot exceed 4 GB, otherwise it must be split. MDT has the ability and so does dism. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt#feedback)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Thanks, I didn't see this comment for a long time. I'll add this detail.

**Comment by greg-lindsay** [comment]
Thanks, I've added this detail.
