### ISSUE TITLE
Change in content

### ISSUE THREAD

**Issue by evachen96** [MicrosoftDocs/windows-itpro-docs#5535]
This optional protection, available to enterprises, helps deliver more productive, performant, and delightful Windows experiences. 

-should be-

 This optional protection helps deliver more productive, performant, and delightful Windows experiences.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b16da7d1-e552-e274-9406-5390252b0c04
* Version Independent ID: d0c9b8a8-4fba-4ea8-cfdd-6ae6d67a2e19
* Content: [How Microsoft identifies malware and potentially unwanted applications](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/criteria#feedback)
* Content Source: [windows/security/threat-protection/intelligence/criteria.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/criteria.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by RAJU2529** [comment]
@evachen96. Create new PR and add your contributions

**Comment by levinec** [comment]
Changes have been made per email thread! Will update later today
