### ISSUE TITLE
W1809 - Assigned Access Single App problems

### ISSUE THREAD

**Issue by tda90** [MicrosoftDocs/windows-itpro-docs#5542]
Hello everyone,
I'm trying to deploy a KIOSK with the help of a provisioning package (built with Configuration Designer ADK)
I was able to create an apply the ppkg but it doesn't work as expected.
What I'm trying to accomplish with the ppkg:
- Create a local user
- Autologin
- Start a standard Windows Application
- Key Combination blocked (as described here, it should happen automatically:
[Key sequences blocked by assigned access](https://docs.microsoft.com/en-us/windows/configuration/kiosk-prepare#interactions-and-interoperability)

What is working/not working:
- Autologon working like expected
- Application autostart after login is also working
- Key sequence blocked by Assigned Access: NOT WORKING; all combinations listed in the article I posted above are still working.
As per my understanding those should be blocked as soon as you configure ASSIGNED ACCESS.
- Automatically relogin if trying to switch user as described [HERE](https://docs.microsoft.com/en-us/windows/configuration/kiosk-single-app#sign-out-of-assigned-access) isn't working, after 30sec nothing happen at all.

Thank you for helping :-)

**Comment by e0i** [comment]
Hello,

Looks like this question can best be answered via relevant [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channels. 

Please consider checking with [Microsoft Community](https://answers.microsoft.com/en-us/windows/forum/windows_10) or [contacting support](https://support.microsoft.com/contactus) for your problem; The issues section of this repository is for content fixes in documentation.

If you feel that the associated article also needs to be updated for any reason feel free to re-open this issue or [contribute with a pull request](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/CONTRIBUTING.md).

Thank you.
