### ISSUE TITLE
Is device credential as a method to enroll into Intune supported?

### ISSUE THREAD

**Issue by desmondkung** [MicrosoftDocs/windows-itpro-docs#5543]
Getting conflicting messages here. GPO has an option to allow device credential to be used for MDM enrollment (for clients 1903 and after), and there's a second note to say that "Device credential group policy setting is not supported for enrolling into Microsoft Intune." Which is which?

I'm on 1909 and still getting "MDM Enroll: Server Returned Fault/Code/Subcode/Value=(MessageFormat) Fault/Reason/Text=(Device based token is not supported for enrollment type OnPremiseGroupPolicyCoManaged)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy#feedback)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MrSpritey** [comment]
You really need to choose Option: User Credentials, when arranging the GPO. Otherwise you will receive Error 76 in the Eventlog.

**Comment by AwakeGitten** [comment]
Have noticed the same error. Was the registration of shared hybrid devices "By Device" no longer supported after 1903?

**Comment by mardahl** [comment]
They removed the note that said "Device credential group policy setting is not supported for enrolling into Microsoft Intune".
Why do I ask? Why?!
The issue has not been fixed. please avoid using Device Credentials. you are asking for a world of pain.
It will seem to work if you have the Intune Connector installed, but in reality, it's just falling back to User Credentials.
