### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by bled1982** [MicrosoftDocs/windows-itpro-docs#5548]
The link to "Defender cmdlets" is broken https://technet.microsoft.com/library/dn433280.aspx 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f5f37f-9e03-eac1-715b-4a01acfff33e
* Version Independent ID: b7e76481-3859-c8d1-c22d-ee238fadd1e9
* Content: [Use PowerShell cmdlets to configure and run Windows Defender AV](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/use-powershell-cmdlets-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/use-powershell-cmdlets-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/use-powershell-cmdlets-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
The redirect link onhttps://docs.microsoft.com/en-us/powershell/windows/get-started is also broken.

There is a link named "defender" in the dynamic tree index on the left side of the page, but it only returns the same **404 - Page not found** error:
- https://docs.microsoft.com/en-us/powershell/module/defender/?view=win10-ps

There are working PowerShell cmdlet links, but none of them are written to be a general overview page with links to the other cmdlets.

The following cmdlet links work as intended, but without any obvious content summarizing page:
1. https://docs.microsoft.com/en-us/powershell/module/defender/add-mppreference
2. https://docs.microsoft.com/en-us/powershell/module/defender/get-mpcomputerstatus
3. https://docs.microsoft.com/en-us/powershell/module/defender/get-mppreference
4. https://docs.microsoft.com/en-us/powershell/module/defender/get-mpthreat
5. https://docs.microsoft.com/en-us/powershell/module/defender/get-mpthreatcatalog
6. https://docs.microsoft.com/en-us/powershell/module/defender/get-mpthreatdetection
7. https://docs.microsoft.com/en-us/powershell/module/defender/remove-mppreference
8. https://docs.microsoft.com/en-us/powershell/module/defender/remove-mpthreat
9. https://docs.microsoft.com/en-us/powershell/module/defender/set-mppreference
10. https://docs.microsoft.com/en-us/powershell/module/defender/start-mpscan
11. https://docs.microsoft.com/en-us/powershell/module/defender/start-mpwdoscan
12. https://docs.microsoft.com/en-us/powershell/module/defender/update-mpsignature

**Comment by RAJU2529** [comment]
@illfated. Sir You have done wonderful work.

**Comment by VLG17** [comment]
@bled1982 The [defender cmdlets](https://docs.microsoft.com/en-us/powershell/module/defender/index?redirectedfrom=MSDN&view=win10-ps) link is working now and is pointing to the page containing all the cmdlets.

**Comment by illfated** [comment]
Yes, thank you. The redirect is working as intended and expected now:
> For a list of the cmdlets and their functions and available parameters, see the [Defender cmdlets](https://technet.microsoft.com/library/dn433280.aspx) topic.

(https://technet.microsoft.com/library/dn433280.aspx redirects to https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/use-powershell-cmdlets-windows-defender-antivirus as you said.)

I think we can ask for this issue to be closed now.

**Comment by denisebmsft** [comment]
@illfated thank you so much for the great work. I'm opening a bug for me to come back to this page and make some improvements. Really appreciate your good work on this.
