### ISSUE TITLE
Incorrect registry key for the AD DS transaction log files

### ISSUE THREAD

**Issue by KamilSzafarczyk** [MicrosoftDocs/windows-itpro-docs#5550]
Incorrect:
HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\NTDS\Parameters\Database Log Files
Correct:
HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\NTDS\Parameters\Database Log Files Path

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9b6379-e575-9819-eca1-a0952f66b655
* Version Independent ID: 34d81602-ffa2-5be6-67ef-b42b3b6f17ee
* Content: [Configure Windows Defender Antivirus exclusions on Windows Server 2016](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by joinimran** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by JohanFreelancer9** [comment]
Looks good. Done.

**Comment by denisebmsft** [comment]
@JohanFreelancer9, @joinimran, and @nenonix thank you for taking care of this! I'm closing this issue, with kind regards.
