### ISSUE TITLE
Link to Download and Install Debugging Tools for Windows is bad

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windows-itpro-docs#5552]
The link to Download and Install Debugging Tools for Windows goes to an incorrect page. Please fix this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29ea594a-9e2c-134b-1247-d8eed794cfd7
* Version Independent ID: 656063ef-57bf-6bb6-30f1-9bdab293b029
* Content: [Planning to Create the DaRT 10 Recovery Image](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/dart-v10/planning-to-create-the-dart-10-recovery-image)
* Content Source: [mdop/dart-v10/planning-to-create-the-dart-10-recovery-image.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/mdop/dart-v10/planning-to-create-the-dart-10-recovery-image.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@rossmpersonal. Sir debugging tools are not available separately, but the tools are included in windows WDK  version

**Comment by rossmpersonal** [comment]
Then the link needs to be updated to point to the Windows WDK version.

--
 Michael Ross
 rossmdummy@fastmail.fm

**Comment by RAJU2529** [comment]
@rossmpersonal. I already created PR, to replace the link

**Comment by rossmpersonal** [comment]
Thank you. Also, what is the roadmap for DaRT? Is it dead after 4/14/2026 ? Is there a replacement? If not, what replaces the functionality of DaRT?

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment]
@rossmpersonal. I don't know about roadmap DART. A few years back Dart is available to download MSDN subscriptions

**Comment by jvsam** [comment]
Thank you @RAJU2529 for creating the PR. 

@rossmpersonal the doc has been updated. Thank you so much for your feedback. As for your question, DaRT is part of the Microsoft Desktop Optimization Pack and you are right, the end of extended support for DaRT 10.0 is until [April 14, 2026](https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/New-extended-support-dates-for-MDOP-tools/ba-p/837312) (MDOP). So far from, there is no replacement specified on [related docs](https://support.microsoft.com/en-us/help/4521973).

We will now close this issue. Thank you for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
