### ISSUE TITLE
Machine Tag regkey

### ISSUE THREAD

**Issue by MVDB1984** [MicrosoftDocs/windows-itpro-docs#5553]
Hi,

The regkey information has wrong naming according to my tests.
Now it is stating:
Registry key: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Advanced Threat Protection\DeviceTagging\
Registry key name: Group
Registry key value (REG_SZ): Name of the tag you want to set

I think this should become:
Registry key: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Advanced Threat Protection\DeviceTagging\
Registry key value (REG_SZ): Group
Registry key data: Name of the tag you want to set

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b42e708-e334-d434-bcc9-e1860ebb36b3
* Version Independent ID: 92e251c5-8613-ce97-9569-02404c9a466a
* Content: [Create and manage machine tags](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/machine-tags)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/machine-tags.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/machine-tags.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @MVDB1984, are you getting an error when adding the *value data*? The value is REG_SZ so it should either be a Unicode or an ANSI string. Have you tried adding text only in the value field? There is an [open question](https://techcommunity.microsoft.com/t5/Microsoft-Defender-ATP/Device-Tagging-Registry-Key/m-p/505718) in the Tech Community where the user mentioned using simple text tag and it worked.

**Comment by MVDB1984** [comment]
Hey, Sorry for the late answer...
no error, but information just is not entirely correct...
It is not a key with the name group, but a register value with the name group... and the data of that value should be the name of the tag you want to set....
can be confusing....

**Comment by jvsam** [comment]
No worries @MVDB1984, thank you for the clarification. I will get this over to the Windows content writing team for review. We always strive to improve the quality of the technical documentation of Microsoft Docs so your feedback is appreciated.

**Comment by e0i** [comment]
@MVDB1984 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
