### ISSUE TITLE
Microsoft Defender ATP for Mac - license requirements

### ISSUE THREAD

**Issue by mtrneny** [MicrosoftDocs/windows-itpro-docs#5557]
It is really unclear for me if I need one of the Microsoft Volume Licensing options mentioned in this page to operate legally Microsoft Defender ATP for Mac client (n-users with macOS devices -&gt; n-licenses?)?

It is a little bit ridiculous to pay for Windows 10 Enterprise license and others if I want to use only Microsoft Defender ATP service for Mac devices, isn't it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements?source=docs)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @mtrneny, we appreciate your feedback. Right now, those are the licensing requirements for Microsoft Defender Advanced Threat Protection (ATP). The good news is, Microsoft Defender ATP [endpoint and detection response (EDR) capabilities](https://techcommunity.microsoft.com/t5/Microsoft-Defender-ATP/EDR-capabilities-for-macOS-have-now-arrived/ba-p/1047801) for macOS devices are now generally available, which adds value to what you will be paying for. Still, we would love to hear from you so I encourage you to submit your feedback on [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). The Microsoft engineering team uses UserVoice feedback to learn what users are asking for or what they want to improve.

**Comment by jvsam** [comment]
Hi again @mtrneny, we hope the information we've provided helped. We will now close this issue, and again, please let us know if you have feedback or suggestions to help improve the quality of the Microsoft Docs technical documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
