### ISSUE TITLE
Faute de frappe

### ISSUE THREAD

**Issue by Efflamm** [MicrosoftDocs/windows-itpro-docs#5560]
"ont été réglés de façon à ce qu’ils s’exécutent de façon à ce qu’ils s’exécutent sous Windows 7"

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 93868b54-1342-6a97-ea84-ab75066c837b
* Version Independent ID: 8ee0f61c-67cd-9df6-a8e9-b854d8134587
* Content: [Présentation de la fonctionnalité Windows to Go (Windows 10)](https://docs.microsoft.com/fr-fr/windows/deployment/planning/windows-to-go-overview#feedback)
* Content Source: [windows/deployment/planning/windows-to-go-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-to-go-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you @Efflamm for letting us know about this.

@TinaMcN, as per the online translation, the concern is a *typo* in the *Hardware considerations for Windows To Go* section (2nd in the list). Assigning this to you for verification. If there's an error, please let us know the correct *word* so we can create a PR and with the correction. Thank you.

@officedocsbot assign @TinaMcN.

**Comment by jvsam** [comment]
@officedocsbot assign @TinaMcN.

**Comment by TinaMcN** [comment]
Merci pour les commentaires. L'article a été traduit par machine. Je l'ai envoyé pour la traduction humaine. Il faudra jusqu'à 4 semaines pour compléter la traduction. (Thank you for the feedback. The article was machine translated. I sent it for human translation. It will take up to 4 weeks to complete the translation.)

**Comment by TinaMcN** [comment]
@Efflamm L'article est maintenant traduit par l'homme.  Veuillez vérifier qu'il est réparé.  Merci encore pour les commentaires. (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)
