### ISSUE TITLE
Etourderie

### ISSUE THREAD

**Issue by Efflamm** [MicrosoftDocs/windows-itpro-docs#5561]
Les liens &lt;a&gt;&lt;/a&gt; ne sont pas a la bonne place, merci de corriger :

Espace de travail IronKeyhttp://www.ironkey.com/windows-to-go-drives/ironkey-workspace-w700.htmlW700 ()
Espace de travail IronKeyhttp://www.ironkey.com/windows-to-go-drives/ironkey-workspace-w500.htmlW500 ()
Espace de travail IronKeyhttp://www.ironkey.com/windows-to-go-drives/ironkey-workspace-w300.htmlW300 ()
Espace de travail DataTraveler Kingston pour Windows tohttp://www.kingston.com/wtg/Go ()

Cordialement.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 93868b54-1342-6a97-ea84-ab75066c837b
* Version Independent ID: 8ee0f61c-67cd-9df6-a8e9-b854d8134587
* Content: [Présentation de la fonctionnalité Windows to Go (Windows 10)](https://docs.microsoft.com/fr-fr/windows/deployment/planning/windows-to-go-overview#feedback)
* Content Source: [windows/deployment/planning/windows-to-go-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-to-go-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @TinaMcN , assigning this to you for the correction of how the links are added in the local FR page. Thank you.

@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
Merci pour les commentaires.  L'article a été traduit par machine.  Je l'ai envoyé pour la traduction humaine.  Il faudra jusqu'à 4 semaines pour compléter la traduction.  (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by TinaMcN** [comment]
@Efflamm L'article est maintenant traduit par l'homme.  Veuillez vérifier qu'il est réparé.  Merci encore pour les commentaires. (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by illfated** [comment]
https://docs.microsoft.com/fr-fr/windows/deployment/planning/windows-to-go-overview#a-href-idwtg-hardwareaconsid%C3%A9rations-mat%C3%A9rielles-pour-windows-to-go :
- IronKey Workspace W700 ([http://www.ironkey.com/windows-to-go-drives/ironkey-workspace-w700.html](https://go.microsoft.com/fwlink/p/?LinkId=618714))
- IronKey Workspace W500 ([http://www.ironkey.com/windows-to-go-drives/ironkey-workspace-w500.html](https://go.microsoft.com/fwlink/p/?LinkId=618717))
- IronKey Workspace W300 ([http://www.ironkey.com/windows-to-go-drives/ironkey-workspace-w300.html](https://go.microsoft.com/fwlink/p/?LinkId=618718))
- Kingston DataTraveler Workspace pour Windows To Go ([http://www.kingston.com/wtg/](https://go.microsoft.com/fwlink/p/?LinkId=618719))

(Please note that the link updates in the EN-US page version are not applied in the FR-FR version of the page.)
