### ISSUE TITLE
Missing a Troubleshooting secion

### ISSUE THREAD

**Issue by OriginalDonSolo** [MicrosoftDocs/windows-itpro-docs#5565]
I cannot get Application Guard to determine a URL is untrusted and redirect the request to the hardware-isolated environment.

Wish there were some diagnostic information available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15d066f2-0726-bbf9-3425-756ce7dbadee
* Version Independent ID: 03501802-fb28-a89d-a463-e27d2fea7456
* Content: [Testing scenarios using Windows Defender Application Guard in your business or organization (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/test-scenarios-wd-app-guard#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/test-scenarios-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-guard/test-scenarios-wd-app-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @OriginalDonSolo, have you installed Windows Defender Application Guard extension for Google Chrome or Mozilla Firefox?

**Comment by jvsam** [comment]
Hi @OriginalDonSolo, we're sorry to hear that you're having issues. Please ensure that your device [meets the requirements](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard) before [turning on](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-guard/install-wd-app-guard#install-application-guard) Windows Defender Application Guard and defining the [network isolation settings](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-guard/configure-wd-app-guard#network-isolation-settings). If you've met the requirements and followed the instructions and you still can't get it to work,  I recommend that you contact [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) for assistance. There are also other support resources that are available for you like the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can post your question and get help from the community. Thank you and kindly keep us informed if you find any relevant information that can be incorporated into this documentation.

**Comment by OriginalDonSolo** [comment]
Here's what I learned.

I had the setting 'Turn on Windows Defender Application Guard in Managed Mode' set to a value of 3, which is 'Enable Windows Defender Application Guard for Microsoft Edge AND Microsoft Office.'

With that setting, AG would ignore ALL its settings.  When I changed that setting to a value of 1, which is 'Enable Windows Defender Application Guard for Microsoft Edge ONLY', then AG works properly.  Change the setting back to 3 and it will ignore all its settings.  Back to 1, and it will work properly.

Now, I do not know why or what that means, just that Office in AG does not work properly and that enabling it prevents AG from processing its Group Policy settings.

**Comment by jvsam** [comment]
Thank you for that additional information @OriginalDonSolo. I am sorry that I can't be of much help, it would be best if you ask the question at [Technet forums](https://social.technet.microsoft.com/Forums/home) or [Microsoft Tech community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities) so that other community members, or even Microsoft engineers can provide answers or some insights. This GitHub-based documentation feedback system is intended to help improve the quality of the technical documentation of Microsoft Docs so if you have feedback or suggestions related to this documentation, please let us know and we will submit it for review. Thank you.

**Comment by denisebmsft** [comment]
Thank you @jvsam for your help with this! I'm going to close this issue out for now, with kind regards.
