### ISSUE TITLE
MDATPAnalyzer misconfigured

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/windows-itpro-docs#5567]
Hello, the "MDATPAnalyzer" tool is preconfigured with a list of internet endpoints for European customers. It doesn't not appear to be correct for American customers.

These are the only endpoints included, which is dramatically deficient.

https://winatp-gw-neu.microsoft.com/test
https://winatp-gw-weu.microsoft.com/test
https://settings-win.data.microsoft.com/qos
https://eu.vortex-win.data.microsoft.com/health/keepalive
http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab
https://eu-v20.events.data.microsoft.com/ping

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83207fc9-2c91-eb07-4237-6bb1f42e3778
* Version Independent ID: 5db33cf3-2dcb-bb33-a252-3a13ca9737f9
* Content: [Configure machine proxy and Internet connection settings](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment]
@SwiftOnSecurity. Two days before I checked mdatp tool,  i found that there sites are configured for United States region

**Comment by SwiftOnSecurity** [comment]
Sorry for the misunderstanding, I think I may have downloaded an old version. This is fixed.

**Comment by SwiftOnSecurity** [comment]
Hello I have found the issue. 
endpoints.txt starts off with many entries.

However, running "MDATPClientAnalyzer.cmd" replaces the content of endpoint.txt and it's not complete.
The tests it runs are then incomplete.

Please test and reproduce this on your side.

**Comment by SwiftOnSecurity** [comment]
Ping @jvsam and @RAJU2529 see above comment about my findings about the file being corrupted during run.
It appears the Powershell is not functioning correctly in its find-replace routine.

**Comment by nam31** [comment]
@SwiftOnSecurity 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)

Thank you.
