### ISSUE TITLE
Dramatically outdated, duplicate internet endpoint data 

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/windows-itpro-docs#5568]
Please de-duplicate this page's connectivity recommendations and point/add to your existing article here:
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet

You are recommending opening *.blob.core.windows.net which is an Azure customer domain, not a Microsoft-controlled service. The page above has the correct, secure endpoints.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4ed2b3-0390-4d53-2450-14995ee8b0b0
* Version Independent ID: 91b5bb3e-55d4-6a8e-c16d-094f15c28ee7
* Content: [Onboard servers to the Microsoft Defender ATP service](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by mjcaparas** [comment]
This page has been updated as suggested.

**Comment by illfated** [comment]
(ref. #5569 )
