### ISSUE TITLE
Duplicate, incorrect Internet endpoints

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/windows-itpro-docs#5569]
Please de-duplicate this page's connectivity recommendations and point/add to your existing article here:
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet

You are recommending opening *.blob.core.windows.net which is an Azure customer domain, not a Microsoft-controlled service. The page above has the correct, secure endpoints.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc8aadae-3a51-93c6-8079-cbd0933471ae
* Version Independent ID: c82444f6-186d-cbee-9b05-9d6d705f44b6
* Content: [Onboard previous versions of Windows on Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/onboard-downlevel)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/onboard-downlevel.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/onboard-downlevel.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment]
@jvsam . The user  @SwiftOnSecurity has already created issue #5568. So close this issue

**Comment by illfated** [comment]
Good point. I concur with @RAJU2529 's suggestion, this is a duplicate issue ticket.

**Comment by illfated** [comment]
Withdrawing my previous comment, there are 2 separate pages, therefore 2 separate tickets with the same opening comment content.:
- [**5568: Onboard servers to the Microsoft Defender ATP service**](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints)
- [**5569: Onboard previous versions of Windows**](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/onboard-downlevel)

**Comment by illfated** [comment]
@mjcaparas : May we have the same solution for this ticket & doc page as for the previous issue ticket #5568 , as outlined in the opening comment?

**Comment by mjcaparas** [comment]
ok

**Comment by jvsam** [comment]
Hi @mjcaparas will you be updating this doc as well or do you want us to create a PR to remove the *Agent Resource* list? Thank you.

**Comment by jvsam** [comment]
@officedocsbot assign @mjcaparas

**Comment by mjcaparas** [comment]
@jvsam - yes ok pls do a pr.
