### ISSUE TITLE
Local Group Policy vs GPME

### ISSUE THREAD

**Issue by suzywager** [MicrosoftDocs/windows-itpro-docs#557]
"Data Collection and Preview Builds" in GPME, does not list "Configure the Commercial ID" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5549abd-da28-5d11-49c6-e66ecf5cd0b6
* Version Independent ID: 0ad6a1a2-5c75-baeb-00de-a6649592ec69
* Content: [Get started with Update Compliance (Windows 10) | Microsoft Docs](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-get-started)
* Content Source: [windows/deployment/update/update-compliance-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/update-compliance-get-started.md)
* Service: **unspecified**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by shortpatti** [comment]
@jaimeo -- Has this issue been addressed?

**Comment by jaimeo** [comment]
No--it's unclear to me what actual the issue is. Can you clarify? What is GPME?

**Comment by suzywager** [comment]
GPME is the Group Policy Management Editor. I'm trying to set up a GPO to deploy to the entire domain. I can only find the Configure Commercial ID under the Local Group Policy

**Comment by R2D2components** [comment]
Hi in response to this email on this day the original owner of the computer did not authorize this action. The nefarious user at the time some hos gained access and some other issues are also being analyzed. Could you be kind to tell me the interaction that was requested by this individual please and reverse any and all process that said individual had take. At the time. 

Jason Robertson 
Thank you for your time and help.
