### ISSUE TITLE
Weird #a0 strings in text

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/windows-itpro-docs#5573]
There are several occurrences of the string '#a0' within the text/page. I think this is some kind of invalid markdown issue.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2bdb99e4-289a-c09a-c35c-2774fc52a402
* Version Independent ID: 4d325389-c9b8-2601-0ff4-c7b6bf5a6c28
* Content: [Microsoft Defender Advanced Threat Protection](https://docs.microsoft.com/de-de/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by GiantCrocodile** [comment]
This issue is within the German translation of the docs. I don't know why the feedback option of the German docs is partially broken and refers to the English version of the docs. Sorry for posting this to the English docs and I hope someone can investigate this. I wasn't aware the Github integration will post this to the wrong repo.

**Comment by illfated** [comment]
Thank you for posting in the en-us version page to report an issue, especially if you find that the original language page seems to be malfunctioning in the #feedback area.

**Comment by GiantCrocodile** [comment]
Indeed, I checked this with current version of Edge browser and the feedback form does work. I did find out that this is an Adblock Plus issue. I reported the bug to them. Thanks for your comment @illfated!

**Comment by illfated** [comment]
Affected lines in the originating page:
- [Threat & Vulnerability Management (beneath first image)](https://docs.microsoft.com/de-de/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection#microsoft-defender-atp)
- Threat & Vulnerability Management (first section below the Tip blob)
- Threat & Vulnerability Management (Note blob in the **Secure score** section)

Common denominator: the Ampersand character **(&)**
```
UNICODE     : U+00026
HEX CODE    : &#x26;
HTML CODE   : &#38;
HTML ENTITY : &amp;
```
https://www.toptal.com/designers/htmlarrows/punctuation/

Unfortunately, there is no indicator on the **en-us** page showing us that the ampersand character `&` should be converted to `#a0`, only ` &amp; ` for a handful appearances.
It does not appear to be an issue with the Fr-Fr or Es-Es pages, so I am uncertain why only the De-De page is affected.

@TinaMcN : Do you have any suggestions for this issue?

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by TinaMcN** [comment]
@GiantCrocodile thanks for reporting this and @illfated thanks for the investigation.   This is an issue caused by the Machine Translation tool.   We switched to a neural MT engine a few months ago which generally produces better quality MT but there are a number of issues like this.   I see this particular issue is occurring on numerous German articles.  I reported it to the MT tool team, it may take them weeks or months to get to it as they have a big backlog of issues.

**Comment by illfated** [comment]
Oh. I see. Thank you for your very informative reply. 
I wish this issue could have been easier to resolve, 
but as you indicated, it is probably too difficult to solve 
from our side here in the Github repository.

**Comment by GiantCrocodile** [comment]
Thank you to both of you for your effort and informative responses here.

**Comment by TinaMcN** [comment]
@GiantCrocodile this article has been human translated and the issue is fixed.  The underlying issue is not yet fixed so it may occur in other articles but I think we can close this issue now.

**Comment by GiantCrocodile** [comment]
Thank you for your great support @TinaMcN. I wish you and your team happy/merry holidays!
