### ISSUE TITLE
Difference between "Allow", "Clean," "Block", "Remove"...

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/windows-itpro-docs#5574]
Can there be descriptions for each of the actions that can be taken on files? For example, it is not clear what the difference between "Remove" and "Clean" is, assuming cleaning the file removes any malicious components or files. More clarification here would benefit the docs greatly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b1ab2e-1964-5580-7c99-4bd4cd480075
* Version Independent ID: f7b5da46-04cb-3501-65fa-870a3c6f09b8
* Content: [Policy CSP - Defender](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#defender-threatseveritydefaultaction)
* Content Source: [windows/client-management/mdm/policy-csp-defender.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-defender.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @thedrum808, I think actions 1, 8 and 10 are not applicable here.

Dear @ManikaDhiman   
could you please have a look at the PR #5740 ?

Thank you

**Comment by ManikaDhiman** [comment]
Hi @MaratMussabekov, @mypil, 

Per inputs from product team, I have added descriptions for possible actions in Defender/ThreatSeverityDefaultAction policy setting. The updates are available in live docs: [Defender/ThreatSeverityDefaultAction](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#defender-threatseveritydefaultaction).  
I have closed PR #5740 as the required updates are already live. Hope this helps. Thanks!

**Comment by mypil** [comment]
@thedrum808 -  Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by ManikaDhiman and MaratMussabekov  so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
