### ISSUE TITLE
Ref from Key Trust deployment to this page means this page needs clarification

### ISSUE THREAD

**Issue by mossywell** [MicrosoftDocs/windows-itpro-docs#5575]
There is a comment on the key trust deployment (https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-dirsync) that says "If you installed Azure AD Connect prior to upgrading the schema, you will need to re-run the Azure AD Connect installation and refresh the on-premises AD schema to ensure the synchronization rule for msDS-KeyCredentialLink is configured". A search on how to to that leads here. What that means is that key trust deployment people could end up reading this page. The second "Important" section on this page takes that into account. However, the first "Important" section  should also take that into account because it talks about using the "KeyCredentials Admins" group. But, in key trust, the group is called "Key Admins". Therefore, I suggest lifting the second "Important" section and merging it with the first. That way, key admin deployers will not say "oh, I don't actually have a group called "KeyCredential Admins".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47038bf5-6fcf-46be-3e72-49bd40be3d60
* Version Independent ID: 7e850cee-96cc-3902-6c5f-bebaa836fb24
* Content: [Configuring Hybrid Windows Hello for Business - Directory Synchronization](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-dir-sync#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-dir-sync.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-dir-sync.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
Thank you for the detailed issue ticket. As you can see, a Pull Request has been opened to add your suggested change to the page.

**Comment by mypil** [comment]
@mossywell -  Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/717392d28d499e7722830653dae0d889b166ec05. 


Thank you for your contribution to make the docs better! Much appreciated!
