### ISSUE TITLE
AutomaticRedeployment errors out with 405 - Not Allowed

### ISSUE THREAD

**Issue by harishankar-gopalan** [MicrosoftDocs/windows-itpro-docs#558]
I am trying the Automatic Redeployment exec node for checking the behavior of the new remote wipe option. I am trying it on a surface pro device running Windows 10 Pro 1803 (17115.1) in the fast ring preview 17115.rs4_release.180302-1642.
My request and response sync ml is shown below:
`<SyncML xmlns="SYNCML:SYNCML1.2">
  <SyncHdr>
    <Target>
      <LocURI>4A065FD4D8B96D4C944134A5C88B3A7A</LocURI>
    </Target>
    <Source>
      <LocURI>
       https://mdm-server-url</LocURI>
      <LocName>MEMDM</LocName>
    </Source>
    <MsgID>1</MsgID>
    <VerDTD>1.2</VerDTD>
    <SessionID>3</SessionID>
    <VerProto>DM/1.2</VerProto>
  </SyncHdr>
  <SyncBody>
    <Atomic>
      <CmdID>EraseDevice</CmdID>
      <Exec>
        <CmdID>EraseDevice</CmdID>
        <Item>
          <Target>
            <LocURI>./Vendor/MSFT/RemoteWipe/AutomaticRedeployment/doAutomaticRedeployment</LocURI>
          </Target>
        </Item>
      </Exec>
    </Atomic>
    <Final></Final>
  </SyncBody>
</SyncML>`

`<SyncML xmlns="SYNCML:SYNCML1.2">
  <SyncHdr>
    <VerDTD>1.2</VerDTD>
    <VerProto>DM/1.2</VerProto>
    <SessionID>3</SessionID>
    <MsgID>2</MsgID>
    <Target>
      <LocURI>
      https://mdm-server-url</LocURI>
    </Target>
    <Source>
      <LocURI>4A065FD4D8B96D4C944134A5C88B3A7A</LocURI>
    </Source>
  </SyncHdr>
  <SyncBody>
    <Status>
      <CmdID>1</CmdID>
      <MsgRef>1</MsgRef>
      <CmdRef>0</CmdRef>
      <Cmd>SyncHdr</Cmd>
      <Data>200</Data>
    </Status>
    <Status>
      <CmdID>2</CmdID>
      <MsgRef>1</MsgRef>
      <CmdRef>EraseDevice</CmdRef>
      <Cmd>Atomic</Cmd>
      <Data>507</Data>
    </Status>
    <Status>
      <CmdID>3</CmdID>
      <MsgRef>1</MsgRef>
      <CmdRef>EraseDevice</CmdRef>
      <Cmd>Exec</Cmd>
      <Data>405</Data>
    </Status>
    <Final />
  </SyncBody>
</SyncML>`

Any help on whether the issue is known and being worked upon will be very useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bce891c-a489-48af-74cb-258713a7bcbd
* Version Independent ID: 6ce5a361-3207-2c5f-9595-4f77cf397d73
* Content: [RemoteWipe CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/remotewipe-csp)
* Content Source: [windows/client-management/mdm/remotewipe-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/remotewipe-csp.md)
* Service: **unspecified**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by harishankar-gopalan** [comment]
Team is there any update on the above query ?

**Comment by sbowl-msft** [comment]
Have you queried ./Device/Vendor/MSFT/RemoteWipe/AutomaticRedeployment/LastError value? It may tell you the underlying Windows error that caused the failure. One common source of errors is when the device already has a reboot pending when you attempt the doAutomaticRedeployment command.

**Comment by sbowl-msft** [comment]
Also, make sure your Windows Recovery Environment (WinRE) is properly configured. See "Troubleshoot..." section in  https://docs.microsoft.com/en-us/education/windows/windows-automatic-redeployment.

**Comment by subsequent2** [comment]
What value should I apply when I assign this in a custom profile with intune?

**Comment by harishankar-gopalan** [comment]
I am checking on the same.  Will update the error code returned by Monday. Can you also help me with any specific event viewer logs that can be checked ?

**Comment by harishankar-gopalan** [comment]
sbowl-msft : I have tested it again and the error code obtained is as below: -2046820335. This is the value obtained when querying ./Device/Vendor/MSFT/RemoteWipe/AutomaticRedeployment/LastError value. Any help on the above will be of great use.

**Comment by harishankar-gopalan** [comment]
sbowl-msft : I find that the AutomaticRedeployment nodes are suddenly removed from the documentation. Is there any known issue with that part in the current releases of 1803 Windows 10 OS release ?

**Comment by harishankar-gopalan** [comment]
sbowl-msft : Any update on the above ?

**Comment by MariciaAlforque** [comment]
I just updated the docs and AutomaticRedeployment is coming back for the next release.
