### ISSUE TITLE
Inbound rule for a specific program

### ISSUE THREAD

**Issue by jaegerfe** [MicrosoftDocs/windows-itpro-docs#5580]
I'm trying to open an inbound rule using this tutorial and if I try to create the rule specifying the program/service, it doesn't work. However, if I select the option 'All programs that meet the specified conditions' the rule works and I can access the service from outside the host machine. We already looked at the firewall logs and if the rule is assigned to the program/service the connections are being dropped.

Our service runs as Local Service or Managed Service Account (MSA) and in both scenarios we see that the firewall rule drops the connection every time it is referencing an application or a service. The moment we remove the application or the service from the rule and leave it only with the ports the rule works and the connection goes through.

I'm using Windows 10 Pro, Version 1809 (Build 17763.864).

Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df1d6ca4-d733-03f6-7c5a-d0bd584fb805
* Version Independent ID: 4d3a7607-cdbf-72d8-0cf0-d3b173eca352
* Content: [Create an Inbound Program or Service Rule (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/create-an-inbound-program-or-service-rule)
* Content Source: [windows/security/threat-protection/windows-firewall/create-an-inbound-program-or-service-rule.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/create-an-inbound-program-or-service-rule.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@jaegerfe  - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  https://support.microsoft.com/hub/4338813/windows-help?os=windows-10

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
