### ISSUE TITLE
 Kerberos Pre-Authentication type #16 missing

### ISSUE THREAD

**Issue by xXxOlivierxXx** [MicrosoftDocs/windows-itpro-docs#5583]
I have several events on my DC logs showing event ID 4771 and Pre-Authentication Type:	16, however, this Pre-Auth type is not listed on this table

https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4771#kerberos-preauthentication-types

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14d2a428-b754-3fc5-da89-1b360e21a95b
* Version Independent ID: 3469c4e7-3a2b-0741-96a3-3547883e82b9
* Content: [4771(F) Kerberos pre-authentication failed. (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4771#feedback)
* Content Source: [windows/security/threat-protection/auditing/event-4771.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4771.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@xXxOlivierxXx -  Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/bd39376a75bc8b858d12a8d19af655da8994ea78. 


Thank you for your contribution to make the docs better! Much appreciated!
