### ISSUE TITLE
Conflicting security advice

### ISSUE THREAD

**Issue by technion** [MicrosoftDocs/windows-itpro-docs#559]
In 2016, Microsoft released this whitepaper: https://www.microsoft.com/en-us/research/publication/password-guidance/
in which the position given is "Password expiration policies do more harm than good".

Microsoft also provides this recommendation guide for Office 365:
https://support.office.com/en-us/article/Password-policy-recommendations-for-Office-365-9fa2539a-2211-41fd-85a0-bc37b9619ca4
Which provides the recommendation: Don't require mandatory periodic password resets for user accounts

These two peices of advise are consistent with advice from UK's NCSC: https://www.ncsc.gov.uk/articles/problems-forcing-regular-password-expiry
And the new NIST guidelines.

However, this document, under the section "threat protection" describes non-expiring passwords as a "major security risk". The countermeasure proposed contradicts previously quoted Microsoft advise.

Although I've logged this under "Windows 10", an identical setting exists under Windows Server 2016 Group Policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed5f0d1b-bfbb-c2a8-76e7-b4b0105160e8
* Version Independent ID: 13684860-a76b-5832-4376-22a585f63fd1
* Content: [Maximum password age (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/maximum-password-age#)
* Content Source: [windows/security/threat-protection/security-policy-settings/maximum-password-age.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/maximum-password-age.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@technion Thanks for opening this issue. Other readers have also commented about this research. I've reached out to the author of the whitepaper to help reconcile the guidance. In the meantime, we can add a link to the whitepaper along with other additions you proposed. But I don't want to remove the existing guidance in this topic before our engineering team has the chance to reconcile it with the whitepaper. I'll submit a pull request to our private repo that includes your commit.

**Comment by technion** [comment]
@Justinha  Thanks for this response.

I just want to note it's not one Microsoft whitepaper with a contradicting view. You can see a listing of references here:

https://gist.github.com/technion/65c652194fb1427e6828ea23ff46d280
