### ISSUE TITLE
the worksheet mentioned in the top of this doc does not appear to exist

### ISSUE THREAD

**Issue by eckermike** [MicrosoftDocs/windows-itpro-docs#5590]
in the second paragraph of the 'using this document' section there is a link to 'Windows Hello for Business planning worksheet'.  when clicked this link does nothing.  Here is the URL the link points to currently: https://go.microsoft.com/fwlink/?linkid=852514

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5739fab2-c6db-a7a9-b0e7-2bf4b85912a7
* Version Independent ID: 82c58053-c1d7-d938-1b0f-f3f7f70ada3b
* Content: [Planning a Windows Hello for Business Deployment](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-planning-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-planning-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by eckermike** [comment]
upon further inspection this is only an issue on OSX

**Comment by eckermike** [comment]
upon further inspeciton again this only an issue for firefox on mac

**Comment by RAJU2529** [comment]
@eckermike. I too tried and clicked on Microsoft edge browser, soon i received pdf file is downloaded via internet download manager.

here is the direct downloading link
**http://download.microsoft.com/download/E/3/9/E39F3E40-8AE2-46A8-8500-25F1A15D108E/WhfbPlanningWorksheet.pdf**

i hope your issue or query is completed

**Comment by ssnitily** [comment]
I experienced this issue on w/ chrome on Windows. Using the link posted by RAJU2529 works.

**Comment by RAJU2529** [comment]
@ssnitily .That's good

**Comment by mypil** [comment]
@eckermike - From our understanding, the issue you raised has been answered by RAJU2529. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
