### ISSUE TITLE
Access to Microsoft Defender ATP

### ISSUE THREAD

**Issue by myoungster** [MicrosoftDocs/windows-itpro-docs#5593]
If a user is granted access to MDATP through the role (e.g. with View data permission) but is not a member of any AAD groups assigned to machine groups, can this user access (sign in to) MDATP at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0c70c9-d302-7375-aaed-eb6a2087fee2
* Version Independent ID: 15f40eca-1ab9-2558-4768-b1dd9c5b70a5
* Content: [Use role-based access control to grant fine-grained access to Microsoft Defender Security Center](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/rbac)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/rbac.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/rbac.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by VLG17** [comment]
@myoungster Granting access to MDATP via RBAC implies assigning the Role to an AAD group, thus giving the group members access to MDATP. If you don't want to further scope it to a Machine Group, the members of the AAD group won't be able to "see" these machines, but will be able to sign in to MDATP.

Are you seeing a different behaviour?

Also, if the Machine Groups are not assigned any AAD groups, they will be visible to all users with MDATP Portal access.

**Comment by mypil** [comment]
@myoungster -  Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17 so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
