### ISSUE TITLE
Azure MFA no longer available. Do we need to buy AAD Premium or O365?

### ISSUE THREAD

**Issue by arcotek-ltd** [MicrosoftDocs/windows-itpro-docs#5594]
Please confirm whether we now need AAD Premium or if MFA in O365 will suffice?
 
Under "Cloud", paragraph 6, you say "additional costs needed for multi-factor authentication", but according to the note (https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-mfa-licensing#available-versions-of-azure-multi-factor-authentication), MFA is only available as a feature of AAD premium or O365 (Business).

Is the MFA in O365 (Business) suitable for Hello modern management?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5739fab2-c6db-a7a9-b0e7-2bf4b85912a7
* Version Independent ID: 82c58053-c1d7-d938-1b0f-f3f7f70ada3b
* Content: [Planning a Windows Hello for Business Deployment](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-planning-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-planning-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by arcotek-ltd** [comment]
According to the following:
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs#multifactor-authentication

There is a single sentence at the end of the second paragraph that reads:

> The MFA enabled by an Office 365 license is sufficient for Azure AD.

I'll let you confirm, but I guess that answers my question. It might be worth updating the referenced docs to remove ambiguity for other readers.

P.S. @Microsoft, when will you support RDP authentication using WHfB "Key trusts" as opposed to "Certificate trusts"???

**Comment by arcotek-ltd** [comment]
@e0i any chance you can give some input to this, please?

**Comment by e0i** [comment]
Forwarding to document author @mapalko for review. Thank you for bringing this issue to attention.

**Comment by illfated** [comment]
(ref. #6086, #6087, #6088, #6089)
