### ISSUE TITLE
Server 2019 support?

### ISSUE THREAD

**Issue by PeteHaigh-MSFT** [MicrosoftDocs/windows-itpro-docs#5595]
Hi there - can we add info re support (or not) for Server 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81aad94a-961c-7327-c42d-573166ddf588
* Version Independent ID: 01e76168-2b46-acfc-dd5d-063dda49c99a
* Content: [Choosing Which Version of AGPM to Install](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/agpm/choosing-which-version-of-agpm-to-install)
* Content Source: [mdop/agpm/choosing-which-version-of-agpm-to-install.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/mdop/agpm/choosing-which-version-of-agpm-to-install.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Hello, @PeteHaigh-MSFT The content for Server 2019 has not been published and we have been informed by Sean Wheeler that the content is under development.
