### ISSUE TITLE
No Code:801c004d

### ISSUE THREAD

**Issue by okhash** [MicrosoftDocs/windows-itpro-docs#5599]
No Error Code:801c004d

**Comment by denisebmsft** [comment]
Hello @okhash, does your comment pertain to this article: https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation

**Comment by illfated** [comment]
There seems to be solutions on this Microsoft Community page for this undocumented error:
https://answers.microsoft.com/en-us/windows/forum/all/windows-hello-error-0x801c004d/874a8f3c-aa9e-4173-8c07-a69c11349fd9?auth=1&page=2 (maybe page 3 is of interest too)

One possible cause seems to be that an Office 365 account is interfering with your Windows account's sign in security setting. Other cases involve fingerprint access not being enabled by the administrator. It is anyone's guess which of the cases @okhash has experienced, but we can't know until we get some feedback. Anyway, there is possibly some form of account management crossover issue that needs to be adressed, as well as documented, if this is at all feasible with the scattered information we are seeing.

**Comment by e0i** [comment]
Hello, @okhash 

It seems that your question has already been answered by the community and thus we are marking this issue as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.
