### ISSUE TITLE
Incorrect definition for CSVLK

### ISSUE THREAD

**Issue by wesk-ms** [MicrosoftDocs/windows-itpro-docs#560]
@kaushika-msft, in the KMS section., CSVLK is defined as "Customer Support Volume License Key".  This is incorrect.  It should read "Customer Specific Volume License Key".

Thanks!
Wesk

**Comment by shortpatti** [comment]
@kaushika-msft -- Can you take a look at this issue?

**Comment by jdeckerms** [comment]
That will be updated later today. Thanks for your feedback.
