### ISSUE TITLE
Update text

### ISSUE THREAD

**Issue by drunkrhin0** [MicrosoftDocs/windows-itpro-docs#5600]
`On the Subject tab, select the Build from this Active Directory information button`

Should be  changed to `Subject Name tab` as below

`On the Subject Name tab, select the Build from this Active Directory information button`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0e839ae-7beb-07fe-f0ea-560079f1f858
* Version Independent ID: af8e8903-fd5c-7210-768d-e0b5de67fe88
* Content: [Validate Public Key Infrastructure (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-pki)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-pki.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
I assume that if there had been an example image on that page, the text would have been correct.

![Kerberos Authentication Properties](https://www.ldap389.info/wp-content/uploads/2010/08/superseded-template.jpg)

**Comment by drunkrhin0** [comment]
I'm currently redeploying I'll screenshot it when I get to that stage again

**Comment by drunkrhin0** [comment]
![image](https://user-images.githubusercontent.com/9085313/70214870-2c4cd000-1777-11ea-914f-67965614ac44.png)

**Comment by illfated** [comment]
Thank you for posting an updated screenshot. I will create a Pull Request to have that text amended as soon as I find the time, either around lunch time or this afternoon.
