### ISSUE TITLE
Specific steps for Home --> Pro --> Enterprise

### ISSUE THREAD

**Issue by sethrhoades** [MicrosoftDocs/windows-itpro-docs#5601]
Hello, a work computer was recently purchased with Windows 10 Home. We have an office 365 e5 account, with Windows 10 Enterprise. Is there any way to activate Enterprise other than purchasing Pro first, then upgrading? Thanks

**Comment by illfated** [comment]
You will need to change the Windows 10 Home Product Key to a Windows 10 Pro key as your primary step to be able to activate an Enterprise license. The procedure should be reasonably easy to find as long as you have got a Windows 10 Professional Product Key to start off.

**Comment by sethrhoades** [comment]
Got it, thanks
