### ISSUE TITLE
USMT XML Ref typo - File.txt => file].txt

### ISSUE THREAD

**Issue by ChadMcCaffery** [MicrosoftDocs/windows-itpro-docs#5603]
In this bulleted-text, the file name **File.txt** should be **file].txt** to match the example:

> - File names with brackets
> 
>   If you are migrating a file that has a bracket character ([ or ]) in the file name, you must insert a carat (^) character directly before the bracket for the bracket character to be valid. For example, if there is a file named File.txt, you must specify `<pattern type="File">c:\documents\mydocs [file^].txt]</pattern>` instead of `<pattern type="File">c:\documents\mydocs [file].txt]</pattern>`.
> 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c22a184d-6043-a0b7-f8a0-6fb7b9d79cf7
* Version Independent ID: 0e1914e7-850c-2362-a688-4816f7c39167
* Content: [General Conventions (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-general-conventions?source=docs)
* Content Source: [windows/deployment/usmt/usmt-general-conventions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/usmt/usmt-general-conventions.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Fair point, the sentence
> For example, if there is a file named **File.txt**, you must specify [...]

could do with a bracket character added to the file name in order to be a real example.

I will open a Pull Request to have this added to the list of suggested fixes.
