### ISSUE TITLE
Prevents virtualization environments from launching

### ISSUE THREAD

**Issue by BeanJuice** [MicrosoftDocs/windows-itpro-docs#5605]
Due to Core Isolation Memory Integrity setting's use of hypervisor platform (Windows 10 Home) booting VM's gives error out of startup.  For VirtualBox (booting xubuntu) I got something like VERR_NEM_VM_CREATE_FAILED Result Code: 0x80004005 
Error persists after using appropriate cmd admin commands and multiple resets. Ideally, I should have remembered that there was a virtualization component to this setting seeing as I built this particular machine. However, settings should be able to be prompted to override from cmd/PowerShell for such scenarios. Hopefully this helps someone though. Logs available if needed

**Comment by denisebmsft** [comment]
Hello @BeanJuice. Can you tell me to which article your question/feedback pertains? This will help us route it to the correct writer(s). Thanks!

**Comment by e0i** [comment]
Closing as there hasn't been a response from your side regarding the specific article where the issue stems from.

Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.

Thank you for providing feedback.
