### ISSUE TITLE
Revoked certificates text

### ISSUE THREAD

**Issue by drunkrhin0** [MicrosoftDocs/windows-itpro-docs#5606]
Remove `revoked certificates` and `update pending certificates` check box doesn't exist.

> Select the Renew expired certificates, update pending certificates, and remove revoked certificates check box.

OS: Windows Server 2016 DC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0e839ae-7beb-07fe-f0ea-560079f1f858
* Version Independent ID: af8e8903-fd5c-7210-768d-e0b5de67fe88
* Content: [Validate Public Key Infrastructure (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-pki)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-pki.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by MaratMussabekov** [comment]
Hello @drunkrhin0 ,
it is one single checkbox:
![image](https://user-images.githubusercontent.com/48041687/81634629-c8ff5200-9428-11ea-8189-a2d9eff96be2.png)
Thank you

**Comment by drunkrhin0** [comment]
Interesting i can seem to replicate the issue anymore. Will reopen if necessary.
