### ISSUE TITLE
[LOC]Back-Translation [時刻]→[Time]

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#5608]
ja-jp:https://docs.microsoft.com/ja-jp/windows/configuration/wcd/wcd-changes
related:#5448

![68989991-155e4080-0891-11ea-9ab9-6a775825fa57](https://user-images.githubusercontent.com/40815708/70224203-38915700-1790-11ea-838a-d24a401ec4ba.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1c382e76-7804-b1a4-5df8-698c74d9c669
* Version Independent ID: 659759e4-80a7-2236-76fa-b3032adf1970
* Content: [時刻 (Windows 10)](https://docs.microsoft.com/ja-jp/windows/configuration/wcd/wcd-time#provisionsettimezone)
* Content Source: [windows/configuration/wcd/wcd-time.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/wcd/wcd-time.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Let me see if I have understood this correctly.

Your example image is from the page you linked, https://docs.microsoft.com/ja-jp/windows/configuration/wcd/wcd-changes :
***
# Windows 構成デザイナーの設定を変更
2019/06/01
 
## Windows 10 バージョン1903で追加された設定
- [DeviceUpdateCenter](https://docs.microsoft.com/ja-jp/windows/configuration/wcd/wcd-deviceupdatecenter)
- [プライバシー](https://docs.microsoft.com/ja-jp/windows/configuration/wcd/wcd-privacy)
- [時間](https://docs.microsoft.com/ja-jp/windows/configuration/wcd/wcd-time)

***
This issue ticket (#5608) is posted on the page https://docs.microsoft.com/ja-jp/windows/configuration/wcd/wcd-time (linked by the last bullet point in my example above, [時間](https://docs.microsoft.com/ja-jp/windows/configuration/wcd/wcd-time) )
***
# 時刻
2019/11/12
 
**[時刻]** を使用して、Windows 10 バージョン (未定) 以降のタイムゾーンのセットアップの設定を構成します。
***
Your recommendation is to replace the kanji **時刻** with the English word **Time** _in both places_, in the link text in `wcd-changes` and in the `wcd-time` page title (proper name of the feature).
***
@TinaMcN : I presume this ticket will be on your table.

**Comment by TinaMcN** [comment]
@illfated yes that is my understanding that 時刻 should be changed to the English word "Time" as I assume it's not translated in the Windows Configuration Designer.  I'll get the topic human translated so they can fix it.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated. Please verify that it is fixed. Thanks again for the feedback)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #5608.
Thanks.
