### ISSUE TITLE
0x801C044D might be wrong.

### ISSUE THREAD

**Issue by sjldk** [MicrosoftDocs/windows-itpro-docs#5609]
I have noticed that the error code 0x801C004D (note 04D at the end) is missing from the list. The solution for this error code is the same as with the listed 0x801C044D.

You might want to re-check if the 0x801C044D is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by colemoine** [comment]
un-joining and rejoining Azure AD hasn't resolved this issue for me
