### ISSUE TITLE
clean up wording of Recover from USB drive section steps 1-3

### ISSUE THREAD

**Issue by luriep** [MicrosoftDocs/windows-itpro-docs#5611]
Existing instructions are not clear... end users get stuck down the generic Surface Recovery website path and don't make it back to this page.  Suggestions for editing "Recover from USB drive" steps 1-3 (and making it into 1-5) below. 
https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-recover-reset#recover-from-usb-drive
Recover from USB drive
1.  Begin with a USB 3.0 drive with 8 GB or 16 GB of storage, formatted as FAT32.
2.  From a separate PC, download the zip file recovery image from the Surface Recovery website, and then return to these instructions. 
3.  Unzip the downloaded file onto the root of the USB drive.  
4.  Connect the USB drive to any USB-C or USB-A port on the Surface Hub 2S.
5.  Turn off the device. While holding down the Volume down button, press the Power button. Keep holding both buttons until you see the Windows logo appear. Release the Power button but continue to hold the Volume until the Install UI begins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6435b14-27da-d10e-4919-b3194ca03a07
* Version Independent ID: b181319b-1bb4-010a-eeab-64ac199fb24c
* Content: [Reset and recovery for Surface Hub 2S](https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-recover-reset?source=docs#feedback)
* Content Source: [devices/surface-hub/surface-hub-2s-recover-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/surface-hub-2s-recover-reset.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by joinimran** [comment]
@luriep Thank you for your feedback but it looks like the document is clearly mentions the required step. For step 1 that you have suggested is mentioned at Note in the document.

Thanks.
Imran.

**Comment by luriep** [comment]
Yes it does.  I had a tech writer edit it the day I made the request.
Thanks for following up and this is ok to close.


Pete
