### ISSUE TITLE
Server 2019

### ISSUE THREAD

**Issue by staynik** [MicrosoftDocs/windows-itpro-docs#5612]
Are there any changes to how this can be deployed in Hybrid mode with Server 2019? I notice the AD Schema is not 2016 or later, will it not work with 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5739fab2-c6db-a7a9-b0e7-2bf4b85912a7
* Version Independent ID: 82c58053-c1d7-d938-1b0f-f3f7f70ada3b
* Content: [Planning a Windows Hello for Business Deployment](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-planning-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-planning-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mapalko** [comment]
2019 schema can be used. 2016 schema is the min version to support the changes for WHFB. Changes to the documentation for including 2016 and later schema are now live.
