### ISSUE TITLE
Software Restriction Policies (SRP) alternative for normal users

### ISSUE THREAD

**Issue by beerisgood** [MicrosoftDocs/windows-itpro-docs#5614]
As SRP is [no longer supported](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-deprecated-features) since 1803 i wonder what we normal users can use if it would removed someday - hopefully not.

As AppLocker or Windows Defender Application Control isn't a alternative for normal, non-company users, nor a option for home / pro users

**Comment by RAJU2529** [comment]
@beerisgood. just now I seen the software restriction policy is available in 1909. Under security settings in GPO

**Comment by beerisgood** [comment]
@RAJU2529 sure. For now. And i'm use it without problems.

But as i say as you can read in my posted link, SRP is abandoned.
Of course it works but it wouldn't get any support/ updates anymore. I also wouldn't surprised if it got removed, even if i don't whish that!

**Comment by RAJU2529** [comment]
@beerisgood. Thanks for your reply.  You seeking any another way to block the software with new blocker.
Last week I came to know Aaron blocker is used for alternative to app blocker

**Comment by beerisgood** [comment]
@RAJU2529 any info about that? Can't find something "Aaron blocker"

**Comment by RAJU2529** [comment]
@beerisgood. Sorry I mentioned the wrong name, actual name is "AaronLocker"

**Comment by beerisgood** [comment]
@RAJU2529 
[AaronLocker](https://blogs.msdn.microsoft.com/aaron_margosis/2018/06/26/announcing-application-whitelisting-with-aaronlocker/) works on all supported versions of Windows that can provide AppLocker.

[AppLocker](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/applocker-overview) is included with enterprise-level editions of Windows.

So sadly no solution for this issue here as it's for normal users, which doesn't have a enterprise Windows.

**Comment by RAJU2529** [comment]
@beerisgood.  Currently, i am using Enterprise edition of windows 10 1909 64bit.

**Comment by beerisgood** [comment]
@RAJU2529 that's fine but no option for us normal end users which can't get a enterprise edition

**Comment by RAJU2529** [comment]
@beerisgood. I will look in College desktop computers running in windows Pro edition

**Comment by denisebmsft** [comment]
Thank you for the feedback and discussion. It does not look like we have any documentation issues here, so I'm going to close this one out with kind regards.

**Comment by beerisgood** [comment]
@denisebmsft Please re-open. Issue is not fixed.

@RAJU2529 Any updates?

**Comment by illfated** [comment]
@beerisgood : When you say "Issue is not fixed.", which page do we need to update and correct to solve this documentation issue?

**Comment by beerisgood** [comment]
> 
> 
> @beerisgood : When you say "Issue is not fixed.", which page do we need to update and correct to solve this documentation issue?

Please read my [first post](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5614#issue-533592353)
This issue isn't about changing docs, it's just a question.

The current state is that Microsoft restrict Enduser (Home + Pro edition) security features like SRP (this issue) but only provide newer/ alternatives for higher editions, like Enterprise.

It's good and important that SRP is still present and i realy hope that don't change unless a real alternative is possible for home user.

So i was just looking here if any other methods exist, but doesn't looks like.
If you know any @illfated or you, @RAJU2529 please post.

But if no other solutions exist, i agree with close this issue.

Thanks for reading

**Comment by illfated** [comment]
Thank you for pointing out the details I had missed. I am fairly sure you need to look for answers in the community forums.

**Comment by RAJU2529** [comment]
@beerisgood . I came to know the software naame  "Appsamvid_ from C-DAC  india, produced this software, which used for  whitelisting the  available  .exe  files and  java files

Already installed executable  files can be whitelisted  for  executions  on windows baaed pc.  
You can try above  software .
For more information visit official site

**https://cdac.in/index.aspx?id=cs_eps_appsamvid**

**Comment by beerisgood** [comment]
> 
> 
> @beerisgood . I came to know the software naame "Appsamvid_ from C-DAC india, produced this software, which used for whitelisting the available .exe files and java files
> 
> Already installed executable files can be whitelisted for executions on windows baaed pc.
> You can try above software .
> For more information visit official site
> 
> **https://cdac.in/index.aspx?id=cs_eps_appsamvid**

Sadly a third-party solution and even not downloadable over HTTPS.
Thanks anyway

**Comment by RAJU2529** [comment]
@beerisgood . download in android mobile , then copy to pc , then, install

**Comment by beerisgood** [comment]
> 
> 
> @beerisgood . download in android mobile , then copy to pc , then, install

What? Why should i do that?
Also that doesn't change the fact that this program isn't available over HTTPS. Only the website is.
The download go over unencrypted HTTP site which is highly not recommend for security!

**Comment by RAJU2529** [comment]
@beerisgood .That software is developed by the team of cyber security of officers from the government of india. 
If you having doubt , then dont download

**Comment by illfated** [comment]
@RAJU2529 : it is recommended to avoid referencing non-Microsoft sources, even on these issue ticket pages.
The only acceptable non-Microsoft material and links is direct partners of Microsoft.
Non-Microsoft material and discussions thereof belongs to forum pages, not these issue tickets.

**Comment by RAJU2529** [comment]
@illfated . Ok fine .I will take care of that
