### ISSUE TITLE
number of machines is incorrect

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windows-itpro-docs#5615]
At top, it says four machines are used. However, only three machines are actually used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042d10ec-8f56-909c-9f66-f4c1363373b9
* Version Independent ID: 3b72e026-16ea-e9bf-a48b-abb42382ddab
* Content: [Perform an in-place upgrade to Windows 10 with MDT (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-to-windows-10-with-the-microsoft-deployment-toolkit)
* Content Source: [windows/deployment/upgrade/upgrade-to-windows-10-with-the-microsoft-deployment-toolkit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/upgrade-to-windows-10-with-the-microsoft-deployment-toolkit.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@rossmpersonal A PR that addresses this issue has been merged. Thank you for the feedback.
