### ISSUE TITLE
Usage Scenario in Branch

### ISSUE THREAD

**Issue by zublifier** [MicrosoftDocs/windows-itpro-docs#562]
Insightful article, thanks. Couple of considerations and questions:

In branch scenario where Windows 10 Hello for Business is on entry level desktops, PINS may be the only option as these device dont have any embedded bio readers etc...

In the event of the desktops being shared by multiple users, what mechanisms can we put in place to prevent guessing of pins and sharing of pins. Note that some of these branches may be rurally remote , so there is no data access to consider using a cell phone for an out of band approval mechanism via push or SMS.

Let me know thoughts

Kind Regards
  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c34dbafa-df3c-a5a5-32d5-2ce152893534
* Version Independent ID: cebdd9a6-45d7-6306-373c-7d31121f9e16
* Content: [Why a PIN is better than a password (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md)
* Service: **unspecified**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by MikeStephens-MS** [comment]
You can deploy the Use Hardware Windows Hello for Business policy that requires the enrollment to use the computer's TPM.  The TPM provides anti-hammering as described in the PIN is backed by hardware section of the page.  For remote locations, you can use their desk phones combined with a user PIN for out-of-band approvals.
