### ISSUE TITLE
Powershell cmdlet for cache summary does not work

### ISSUE THREAD

**Issue by CharlesBaldridge-MS** [MicrosoftDocs/windows-itpro-docs#5620]
This document states "Starting in Window 10, version 1903, get-DeliveryOptimizationPerfSnap has a new option -CacheSummary which provides a summary of the cache status."  I have attempted to use this switch to verify cache information on both Windows 10 Enterprise x64 1903 and 1909 but the switch does not function on either:  "Get-DeliveryOptimizationPerfSnap : A parameter cannot be found that matches parameter name 'CacheSummary'."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d745280-391c-4f6d-6a35-7125fa263548
* Version Independent ID: 0ccd8add-b5fb-469c-509e-e009c43a00ac
* Content: [Set up Delivery Optimization](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization-setup#feedback)
* Content Source: [windows/deployment/update/waas-delivery-optimization-setup.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-delivery-optimization-setup.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@narkissit can you advise?

**Comment by RAJU2529** [comment]
@CharlesBaldridge-MS. Just now i entered the following command on PowerShell with admin rights, even though i received the same error on 1909 64bit.

**Get-DeliveryOptimizationPerfSnap -CacheSummary**


![powershell](https://user-images.githubusercontent.com/3296790/70345525-4b845400-1882-11ea-95bc-68bd61acb120.JPG)

**Comment by illfated** [comment]
Tested the command on both Windows 10 Pro 1903 and Windows 10 Home 1909, both gave me the following output:

```powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\WINDOWS\system32> Get-DeliveryOptimizationPerfSnap -CacheSummary
Get-DeliveryOptimizationPerfSnap : A parameter cannot be found that matches parameter name 'CacheSummary'.
At line:1 char:34
+ Get-DeliveryOptimizationPerfSnap -CacheSummary
+                                  ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-DeliveryOptimizationPerfSnap], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Windows.DeliveryOptimization.AdminCommands.GetDeliveryOptimizationPerfSnap

PS C:\WINDOWS\system32> Get-Help Get-DeliveryOptimizationPerfSnap

NAME
    Get-DeliveryOptimizationPerfSnap

SYNTAX
    Get-DeliveryOptimizationPerfSnap  [<CommonParameters>]


ALIASES
    None


REMARKS
    None



PS C:\WINDOWS\system32>_
```

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by nam31** [comment]
@CharlesBaldridge-MS  Can you please check this updated documentation and let me know if all good now :  https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization-setup#feedback

**Comment by CharlesBaldridge-MS** [comment]
Looks good now thank you!


Charles Baldridge

Customer Engineer

MICROSOFT


Office: 813-868-8107

Charles.Baldridge@microsoft.com<mailto:Charles.Baldridge@microsoft.com>

[Twitter]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FMicrosoft&data=02%7C01%7Cchbaldri%40microsoft.com%7Cbdc2cdd073604a6d280608d79b55f0ce%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637148665716966029&sdata=ort22B0Nx1gxyDkYU7a2%2FwNH0OTwXzL1C7aGy0nvYLs%3D&reserved=0>    [Facebook] <https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FMicrosoft&data=02%7C01%7Cchbaldri%40microsoft.com%7Cbdc2cdd073604a6d280608d79b55f0ce%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637148665716976025&sdata=or7hEeznK4s3ATTriAeoRFN3I7%2FO2Z428UIn033irhY%3D&reserved=0>     [Linkedin] <https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fmicrosoft&data=02%7C01%7Cchbaldri%40microsoft.com%7Cbdc2cdd073604a6d280608d79b55f0ce%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637148665716976025&sdata=JbGqn%2Fh1W%2F%2BF4sjLiatPAYHK5aVX3%2F7UE17%2BxCdJ90A%3D&reserved=0>     [Youtube] <https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FMicrosoft&data=02%7C01%7Cchbaldri%40microsoft.com%7Cbdc2cdd073604a6d280608d79b55f0ce%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637148665716986029&sdata=I1igICOA4kzU3rPQaaZ8URMntDo6mHuaxB%2By5pTSDB0%3D&reserved=0>

[MSFT_logo]<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.microsoft.com%2F&data=02%7C01%7Cchbaldri%40microsoft.com%7Cbdc2cdd073604a6d280608d79b55f0ce%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637148665716986029&sdata=bszgHjG5sJ7Vty%2ByP4wPUuYZVhocRSHKsLMWy4N7JXk%3D&reserved=0>

One Microsoft Way, Redmond, WA 98052 USA | Privacy Statement<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D248681&data=02%7C01%7Cchbaldri%40microsoft.com%7Cbdc2cdd073604a6d280608d79b55f0ce%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637148665716996011&sdata=DmgtPLAwnqTgWjwjW1iFnjJuf0bHmIAxiUa3Id2v4R0%3D&reserved=0>

Note: This email may contain confidential information. If you are not named on the addressee list, please take no action in relation to this email, do not open any attachment and please contact the sender (details above) immediately.


________________________________

**Comment by illfated** [comment]
- Document history: https://github.com/MicrosoftDocs/windows-itpro-docs/commits/public/windows/deployment/update/waas-delivery-optimization-setup.md
- Most recent commit as of now: https://github.com/MicrosoftDocs/windows-itpro-docs/commit/b0e6671ccc3b523ce436b631830e781f70645ec5 (Pull Request #8281)
- Specific commit resolving this issue ticket: https://github.com/MicrosoftDocs/windows-itpro-docs/commit/bea4fc3ef606da2dfa0c8eb6dedef316bff319de (PR #7908)
