### ISSUE TITLE
apps and UAC

### ISSUE THREAD

**Issue by jaayson** [MicrosoftDocs/windows-itpro-docs#5621]
> Warning: Universal Windows apps will not work when UAC is disabled.

It is not correct. Universal apps still work. Could you fix this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 495688e2-ca8d-a005-19d2-5ee9138c86f2
* Version Independent ID: 760f236c-5eb0-00cd-9553-990f29ee5aa4
* Content: [How User Account Control works (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/how-user-account-control-works#feedback)
* Content Source: [windows/security/identity-protection/user-account-control/how-user-account-control-works.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/user-account-control/how-user-account-control-works.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@jaayson. could you tell me name of the universal app, that you tested

**Comment by jaayson** [comment]
Microsoft Store, MSN Weather and etc. Windows apps.

**Comment by jaayson** [comment]
> @jaayson. could you tell me name of the universal app, that you tested

Microsoft Store, MSN Weather and etc. Windows apps.

**Comment by RAJU2529** [comment]
@jaayson. Today I will test with recommended gpo setting.

**Comment by RAJU2529** [comment]
@jvsam.  @illfated. Today i confromed, what @jaayson said is correct. Let more expert users should check before creating PR or modifying content.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by ryanries** [comment]
Please be careful with how you word this. It was the original design that UWP apps would only work when UAC was enabled. The design was later changed to allow UWP to run even when UAC was disabled. However, there are still many outstanding bugs that can arise when a user attempts to run UWP apps that were originally written assuming that UAC was enabled when UAC is disabled.

**Comment by illfated** [comment]
Maybe we could add a Note saying something similar to this phrasing:

> [!NOTE]
>  The original design was to have UWP apps only work when UAC is enabled. The design has later been changed to allow UWP to run even when UAC is disabled. However, unforeseen bugs might still arise when a user attempts to run UWP apps which were originally written assuming that UAC is enabled, when UAC is in fact disabled.

Feel free to suggest a more precise phrasing, in case my suggestion is incorrect or not precise enough. You may also suggest in which part of the document the note should be added, or indeed if the text format should be different as well, like not being a Note blob.

**Comment by nam31** [comment]
Closing via #8443. Thanks
