### ISSUE TITLE
Instructions no longer valid

### ISSUE THREAD

**Issue by RPanick** [MicrosoftDocs/windows-itpro-docs#5622]
I've been trying to set this up for the better part of the day.  I finally get through everything else that has changed to this page.  But Step 2 is impossible because Upgrade Readiness can't be found when trying to add the resource.  Honestly Microsoft please stop changing things for the sake of changing them.  My job is hard enough without everything changing constantly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24771310-237e-adf7-be33-59355a87f243
* Version Independent ID: e2792588-8318-98a2-a5bd-ff5cbba75e0e
* Content: [Get started with Upgrade Readiness (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-get-started#feedback)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/upgrade-readiness-get-started.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RPanick** [comment]
I just figured out why.  The !@#$%^&* function has been dropped.  I'm going to have a field day crucifying my Microsoft account team on this since they have been pushing hard to get this implemented.

**Comment by jaimeo** [comment]
@iceorbital has Upgrade Readiness already been removed from the Azure Portal? From what RPanick is saying it seems like we need to do some education with the account teams.

@RPanick it's being _replaced_ by Desktop Analytics: https://docs.microsoft.com/en-us/configmgr/desktop-analytics/overview .

**Comment by RPanick** [comment]
Thanks Jaimeo, I'll check it out Monday.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by nam31** [comment]
@RPanick  Please let us know if you still have any question regarding the issue you have raised initially.
