### ISSUE TITLE
Connect-AutopilotIntune removed from module

### ISSUE THREAD

**Issue by JordIntune** [MicrosoftDocs/windows-itpro-docs#5627]
Did you notice "Connect-AutopilotIntune" is removed from the WindowsAutopilotIntune PowerShell module? Retrieving the Autopilot profile is not possible anymore, it throws an error. Please update this page?

**Comment by mypil** [comment]
@JordIntune - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@JordIntune - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
