### ISSUE TITLE
MountVol uses wrong syntax

### ISSUE THREAD

**Issue by Roadrunner67** [MicrosoftDocs/windows-itpro-docs#5628]
C:\WINDOWS\system32&gt; mountvol X: /s
The parameter is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@Roadrunner67.   Just now i run the command. command works fine

i think, in your hard drive, system partition is missing.
boot into recovery mode , go to command prompt, then run diskart ,conform EFI is created and  using

**Comment by mypil** [comment]
@Roadrunner67 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by RAJU2529  so we will close this issue.

We appreciate your contribution to make the docs better!
