### ISSUE TITLE
No new Group Policies in Windows 10, version 1903 and 1909

### ISSUE THREAD

**Issue by cas77** [MicrosoftDocs/windows-itpro-docs#5629]
There is no information about the new Group Policies in Windows 10, version 1903 and 1909.
If there are no new/different Group Policies in Windows 10, version 1903 and 1909 one should drop a short info about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c3e60ec-cf61-c34b-db79-74b13e3ee867
* Version Independent ID: fc5079f7-a563-c627-3a3e-eb84a99e4fd3
* Content: [New policies for Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/new-policies-for-windows-10#feedback)
* Content Source: [windows/client-management/new-policies-for-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/new-policies-for-windows-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by timothyd09** [comment]
Please update documentation!

**Comment by joinimran** [comment]
@Dansimp , Can you please share your insight as I have tried to find the required information from Microsoft docs but couldn't find anything.

**Comment by joinimran** [comment]
@Dansimp Waiting for your feedback.

@mypil FYI Please.

**Comment by nam31** [comment]
@cas77 

As of September 2020 This page will no longer be updated. To find the Group Polices that ship in each version of Windows, refer to the Group Policy Settings Reference Spreadsheet. You can always locate the most recent version of the Spreadsheet by searching the Internet for "Windows Version + Group Policy Settings Reference".

For example, searching for "Windows 2004" + "Group Policy Settings Reference Spreadsheet" in a web browser will return to you the link to download the Group Policy Settings Reference Spreadsheet for Windows 2004.

[The latest group policy reference for Windows 10 version 2004 is available here.](https://www.microsoft.com/en-us/download/101451)
