### ISSUE TITLE
The link "Download the complete set of Administrative Template (.admx) files for Windows 10" is out of date. 

### ISSUE THREAD

**Issue by cas77** [MicrosoftDocs/windows-itpro-docs#5630]
Hi,
the link "Download the complete set of Administrative Template (.admx) files for Windows 10" is out of date. The current is the set for Windows 10, version 1909.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c3e60ec-cf61-c34b-db79-74b13e3ee867
* Version Independent ID: fc5079f7-a563-c627-3a3e-eb84a99e4fd3
* Content: [New policies for Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/new-policies-for-windows-10#feedback)
* Content Source: [windows/client-management/new-policies-for-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/new-policies-for-windows-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
I already created PR

**Comment by mypil** [comment]
@cas77 - Thank you for pointing this out. @RAJU2529 - Thank you for creating the PR to fix this issue.

- From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/1a93b58f551bf426f706a9db8de48b46b00b0131. 


Thank you for your contribution to make the docs better! Much appreciated!
