### ISSUE TITLE
Performing Simulations in Eval Environment

### ISSUE THREAD

**Issue by themichaelbender** [MicrosoftDocs/windows-itpro-docs#5632]
Scenario 1 and Scenario 3 from the Simulations & Tutorials page cannot be performed in the Eval Environment Windows 10 VM as deployed. Both scenarios use Microsoft Word documents with embedded macros, and the Test VMs deployed in the lab environment do not have Microsoft Word installed. You should include a note that Office needs to be installed for all the simulations to work.

**Comment by mypil** [comment]
@themichaelbender  - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by themichaelbender** [comment]
Here is the document: 
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/evaluation-lab#simulate-attack-scenarios

**Comment by VLG17** [comment]
@themichaelbender according to @mjcaparas MS Office is installed on the VMs, so there is no need to add this statement. Are you seeing something different? Could you provide more details?

**Comment by themichaelbender** [comment]
When I tested this in December there were no office apps in any of the evaluation VMs. I will be running through this again next week so I will report back.

**Comment by mypil** [comment]
@themichaelbender - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/7fa53e5555edfc8d48919e29220c53a50cf53781.

 If you have some other technical issues, we would suggest for you to can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products so technical support can help resolve it.


Thank you for your contribution to make the docs better! Much appreciated!
