### ISSUE TITLE
these instructions haven't been valid for years

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/windows-itpro-docs#5634]
that azure ad button no longer triggers this workflow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a882e5a-3c13-b9dc-7471-c5c0858c3bce
* Version Independent ID: 73c24bc3-5a83-ada3-609b-5949af484eaa
* Content: [Register your free Azure Active Directory subscription](https://docs.microsoft.com/en-us/windows/client-management/mdm/register-your-free-azure-active-directory-subscription?source=docs)
* Content Source: [windows/client-management/mdm/register-your-free-azure-active-directory-subscription.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/register-your-free-azure-active-directory-subscription.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Just to confirm which part of the document you are referring to: are you saying that the page needs to be rewritten from step 3 onward, for it to be up to date with the actual Office 365 feature?
***
3. On the **Admin center** page, hover your mouse over the Admin tools icon on the left and then click **Azure AD**. This will take you to the Azure Active Directory sign-up page and brings up your existing Office 365 organization account information.
***
As I don't have access to any Premium Business service, I will not directly be able to confirm or contribute with images, text or workflow for that page, unless there is a template and existing images to submit in a Pull Request to update & correct the page content.

**Comment by Mike-Crowley** [comment]
It looks like step 4+ is what doesn't happen anymore.

**Comment by mypil** [comment]
@Mike-Crowley - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/798ce8f97a0242df14fa6ac91e67fd1cc319da77. 


Thank you for your contribution to make the docs better! Much appreciated!
