### ISSUE TITLE
Instructions don't work

### ISSUE THREAD

**Issue by nthexwn** [MicrosoftDocs/windows-itpro-docs#5635]
In gpedit.msc I am trying to rollback the "Specify intranet Microsoft update service location" (Computer_Configuration-&gt;Administrative_Templates-&gt;Control_Panel-&gt;Windows_Components-&gt;Windows_Update) settings to their previous values since I don't remember what they were.  I do NOT want to reset this setting to the defaults since this erases all the values.

This page seems to be the closest thing I could find to instructions on how to do this.

Unfortunately, I could not find a program called "Group Policy Management Console".  Typing this into Cortana opens the "Local Group Policy Editor" instead (AKA: gpedit.msc).  Inside this editor I also could not find a "Change Control" option anywhere for the settings which I would like to rollback.

It is still unclear how to accomplish what I'm trying to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23272aaf-f2b5-00e5-b1de-1424296dd0cd
* Version Independent ID: b7e41ff6-6fd0-1a3a-c742-f7177fafb337
* Content: [Roll Back to a Previous Version of a GPO](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/agpm/roll-back-to-a-previous-version-of-a-gpo#feedback)
* Content Source: [mdop/agpm/roll-back-to-a-previous-version-of-a-gpo.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/mdop/agpm/roll-back-to-a-previous-version-of-a-gpo.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@nthexwn.      Particular AGPM  feature offered in   Windows 2016 or 2019 server only, Not available in clients. I hope your question will be answered by me

**Comment by F5-jansen** [comment]
I believe what you're saying is that we can't rollback individual group policy settings on standard versions of Windows 10.  Is that correct?

**Comment by CCDFischer** [comment]
That is correct. This functionality requires AGPM (Advanced Group Policy Management) which is a part of the MDOP (Microsoft Desktop Optimization Pack). You would need to have setup AGPM before you made the change, controlled the GPO you are working with, and then made the change. Only in that scenario would you be able to roll it back. Group Policy does not on its own keep a history of settings.

**Comment by mypil** [comment]
@nthexwn - From our understanding, the issue you raised has been answered by RAJU2529 and CCDFischer so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by nthexwn** [comment]
Indeed, thank you for clearing this up.
