### ISSUE TITLE
Conflicts between MDATP June 2019 v1 and MDM May 2019

### ISSUE THREAD

**Issue by Sculpin90** [MicrosoftDocs/windows-itpro-docs#5636]
"Deploying both baselines to the same machine will not result in conflicts."

This is not true. When I deploy [Defender ATP Baseline June 2019 v1] and  [MDM Security Baseline for May 2019] there is multiple conflicts. One is Clipboard behaviour/application guard another one is "type of system scan to perform". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2246e9c-193b-a110-ca52-2110a6e63631
* Version Independent ID: 7328d4a4-1944-c199-db72-a7e3cd350ae9
* Content: [Increase compliance to the Microsoft Defender ATP security baseline](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-machines-security-baseline)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-machines-security-baseline.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-machines-security-baseline.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by lomayor** [comment]
Looking into this...

**Comment by torvalstrom** [comment]
+1 for this error - can someone from Microsoft provide an update? Super weird we have to waste time troubleshooting conflicts between **default** Intune policies.

**Comment by mypil** [comment]
@lomayor - Do you have any updates on this?

**Comment by aidbish** [comment]
+1 to this issue appearing. Any updates?

**Comment by 3Moonboi** [comment]
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5636#issuecomment-577115581

**Comment by iuriiieroshenko** [comment]
same issue
