### ISSUE TITLE
Defender Advanced Threat Protection app is not available

### ISSUE THREAD

**Issue by BurgerhoutJ** [MicrosoftDocs/windows-itpro-docs#5637]
The Microsoft / Windows Defender Advanced Threat Protection app is not available anymore in the AppSource. At least, I can't find it.
Is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c94f17bc-9075-8816-0087-a58388c94266
* Version Independent ID: c024d528-b4bf-b069-c54f-764a04f27aa5
* Content: [Create and build Power BI reports using Microsoft Defender ATP data](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/powerbi-reports#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/powerbi-reports.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/powerbi-reports.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@BurgerhoutJ  You said is correct. Because its not free to download.. instead you must sign up to get trail with organization email or with personal email.

**Comment by BurgerhoutJ** [comment]
@RAJU2529 What's not free? PowerBI or the app that I want?

**Comment by RAJU2529** [comment]
@BurgerhoutJ. If you want real experience and need to use  DATP then you must sign in with work email id.
here is the link
**https://www.microsoft.com/en-in/microsoft-365/windows/microsoft-defender-atp?ocid=docs-wdatp-powerbireports-abovefoldlink&rtc=1**

moreover, you can download free and use  Power Bi app from Microsoft store

**https://powerbi.microsoft.com/en-us/get-started/**

**Comment by RAJU2529** [comment]
@BurgerhoutJ . You can download  as standalone power bi desktop setup file from Microsoft official website 
**https://www.microsoft.com/en-us/download/details.aspx?id=58494**

i hope i answered your queries

**Comment by mypil** [comment]
@BurgerhoutJ - From our understanding, the issue you raised has been answered by RAJU2529 so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
