### ISSUE TITLE
SCEP is required for Windows 7

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/windows-itpro-docs#5640]
The SCEP client is required for Windows 7, and its not stated so on this page. Or if its not required, its not stated. Defender in Windows 7 was not AV, so I would think that SCEP is required to onboard W7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc8aadae-3a51-93c6-8079-cbd0933471ae
* Version Independent ID: c82444f6-186d-cbee-9b05-9d6d705f44b6
* Content: [Onboard previous versions of Windows on Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/onboard-downlevel)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/onboard-downlevel.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/onboard-downlevel.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by VLG17** [comment]
@vboyev-MSFT Is the following information not enough?

> To onboard down-level Windows client endpoints to Microsoft Defender ATP, you'll need to:

>   **Configure and update System Center Endpoint Protection clients.**

The article applies to Win 7 SP1 Enterprise and Pro, so that implies that you need SCEP clients for Win 7. If i'm missing something please let me know.

**Comment by mypil** [comment]
@vboyev-MSFT -  Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17 so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
