### ISSUE TITLE
Small error

### ISSUE THREAD

**Issue by bgolinvaux** [MicrosoftDocs/windows-itpro-docs#5646]
“FIPS 140 validated” means that the cryptographic module, or a product that embeds the module, has been validated (“certified”) by the CMVP as meeting as meeting the FIPS 140-2 requirements.

"as meeting as meeting" should be replaced by "as meeting".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e93f07bf-c0dd-dd83-d7bf-8562e7f197c3
* Version Independent ID: a6c44187-8ff1-6519-5291-146b4c1bf46c
* Content: [FIPS 140 Validation - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/threat-protection/fips-140-validation#feedback)
* Content Source: [windows/security/threat-protection/fips-140-validation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/fips-140-validation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
@RAJU2529 : As you can see directly above my comment, you have opened 2 identical Pull Requests for this resolution.
I assume you will follow up by closing your duplicate PR (#5649 ) and keep open the first one (#5648 ).

**Comment by RAJU2529** [comment]
@illfated. Yes sir you are right, after creating the first PR, i seen  commit and pull request on top page in the green button, so i thought of something went wrong in earlier PR , so I pulled request. Thats why two PR is created

**Comment by e0i** [comment]
@bgolinvaux The issue has been addressed by PR #5648 via community contributor, **RAJU2529**. Thank you for providing feedback.
