### ISSUE TITLE
aka.ms/sdt4b is old version and don't support Laptop 3...

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/windows-itpro-docs#5647]
Please check aka.ms/sdt4b, It's old version and don't support Surface Holiday 2019 Products.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 865af2c0-8e9a-c02d-b618-541af19f9e87
* Version Independent ID: f8eaf72b-bfea-697a-12d6-5a17d3defbc0
* Content: [Fix common Surface problems using the Surface Diagnostic Toolkit for Business - Surface](https://docs.microsoft.com/en-us/surface/surface-diagnostic-toolkit-for-business-intro#feedback)
* Content Source: [devices/surface/surface-diagnostic-toolkit-for-business-intro.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-diagnostic-toolkit-for-business-intro.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Sorry for noticing this issue ticket this late. Should it be replaced with the following link?
- https://www.microsoft.com/en-us/download/details.aspx?id=46703
(**Surface Tools for IT**)

**Comment by goxia** [comment]
> Sorry for noticing this issue ticket this late. Should it be replaced with the following link?
> 
> * https://www.microsoft.com/en-us/download/details.aspx?id=46703
>   (**Surface Tools for IT**)

Yes, thanks a lot.

**Comment by e0i** [comment]
@goxia The issue has been noted for revision and should be updated within a few days. Thank you for providing feedback.

**Comment by illfated** [comment]
@goxia : Thank you for reporting this issue, which should be resolved now in Pull Request #6329 by @MaratMussabekov . It will take a few days for the update to migrate to the docs.microsoft.com page.
