### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by tju-pwsh** [MicrosoftDocs/windows-itpro-docs#5654]
"Enteprise" should be "Enterprise"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24796ccb-a3a7-c8c5-829d-ede6e06ff7c4
* Version Independent ID: 1282c601-0457-f28a-7ad1-c373739d7004
* Content: [Mobile device management MDM for device updates - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/device-update-management)
* Content Source: [windows/client-management/mdm/device-update-management.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/device-update-management.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
@tju-pwsh : Thank you for notifying the community about this typo. This one is solved as of the PR #5658 and its commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/9639b3dd972a795fb828eb96a25ef5c9c7cf0c10 . The change will appear on the docs.microsoft.com page after some days, when the next sync from Github to the public pages is done.
