### ISSUE TITLE
NTAuth store certificate type incorrect

### ISSUE THREAD

**Issue by andrewwillett** [MicrosoftDocs/windows-itpro-docs#5656]
"The Domain Controller Certificate must be present in the NTAuth store."
Domain Controller certificates are not added to the NTAuth store themselves. When Enterprise CAs are installed AD CS adds the CA certificates to the NTAuth stores.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800b8090-65a9-da9f-a930-1f80dc9f2c2d
* Version Independent ID: b4495b6a-4ca5-7aa1-7964-ef6e19275c4e
* Content: [Configure Hybrid key trust Windows Hello for Business - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by MrAzureAD** [comment]
This „Note“ is confusing and just wrong. Afaik the issuing CA of the DC cert must be in NTAuth store. In case of a self-signed DC cert, it is the DC cert. But in case of a PKI, it is the issuing CA cert.
As NTAuth store is replicated following this note will lead to a bloated NTAuth store in a large AD environment (containing all DC certs).

**Comment by MaratMussabekov** [comment]
this note was added recently via https://github.com/MicrosoftDocs/windows-itpro-docs/commit/a163d35183cbfa1b7cd3fcb8f24e223f916d77e1

**Comment by MaratMussabekov** [comment]
Added PR to change this information

**Comment by e0i** [comment]
Closing via #5922. Note that it might take a while for changes to be published online. Thank you for the feedback.

**Comment by Skorfulose** [comment]
The merge still got it wrong. It‘s not the root CA certificate that needs to go into the NTAuth container. It‘s the certificate of the CA issuing the DC certs. That‘s important, because that’s a different CA/certificate in multi-tier PKIs.
