### ISSUE TITLE
Certificate request has vs Certificate hash

### ISSUE THREAD

**Issue by andrewwillett** [MicrosoftDocs/windows-itpro-docs#5657]
"Select SHA256 from the Request hash list."
Whilst recommended, the certificate *request* hash may have been mistaken for the certificate hash here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800b8090-65a9-da9f-a930-1f80dc9f2c2d
* Version Independent ID: b4495b6a-4ca5-7aa1-7964-ef6e19275c4e
* Content: [Configure Hybrid key trust Windows Hello for Business - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by VLG17** [comment]
@andrewwillett Looking at the Cryptography tab, request hash is correct:

![image](https://user-images.githubusercontent.com/41186174/73176075-415d3400-4114-11ea-8fbc-268a3fafb6da.png)

Are you seeing something different?

**Comment by andrewwillett** [comment]
UI is correct. I see customers mistaking the _request_ hash algorithm for the hash algorithm of the _certificate_, some text for clarity would be good here.

**Comment by VLG17** [comment]
@andrewwillett got it, will add a note on that. Thank you for providing this feedback!

**Comment by e0i** [comment]
@andrewwillett The relevant note has been added to the documentation thanks to your feedback. Have a nice day.
