### ISSUE TITLE
Registry key availability?

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/windows-itpro-docs#5660]
For systems not managed by MDM or domain joined (i.e. AAD joined instead) - What is the registry key for setting the protection level?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f0f5a3-f095-3fa4-90dd-7dee8ccb49ad
* Version Independent ID: 1bec5d66-a92a-4b0d-b9d8-f43c9eab4a50
* Content: [Specify cloud-delivered protection level in Windows Defender Antivirus - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/specify-cloud-protection-level-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/specify-cloud-protection-level-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/specify-cloud-protection-level-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by joinimran** [comment]
@CHDAFNI-MSFT - Thank you for your query, please see https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/enable-cloud-protection-microsoft-defender-antivirus to enable cloud protection in Azure. This document cover all the available options to enable the cloud-protection. 

Thanks.
Imran.

**Comment by CHDAFNI-MSFT** [comment]
Hello,

I take it by your response that there isn’t a registry key available that performs the same action? (for Azure Docs documentation)

-------
(internal only) If I helped you, please take this 1-minute survey – https://aka.ms/chdafni-feedback

Chase Dafnis
Sr. Premier Field Engineer
US Public Sector
Microsoft Corporation
Office: 646.225.4724
Chase@microsoft.com<mailto:Chase@microsoft.com>
[Twitter]<https://twitter.com/Microsoft>    [Facebook] <https://www.facebook.com/Microsoft>     [Linkedin] <https://www.linkedin.com/company/microsoft>     [Youtube] <https://www.youtube.com/user/Microsoft>
[Microsoft Logo]

If you have any feedback about my work, please let either myself or my manager Dawn Spina know at Dawn.Spina@microsoft.com<mailto:Dawn.Spina@microsoft.com>

**Comment by joinimran** [comment]
There is no exact information available anywhere on the Microsoft doc repo regarding this. The 3rd party information cannot be added in the docs. 

Thanks 
Imran.

**Comment by CHDAFNI-MSFT** [comment]
Point of clarity, there’s nothing 3rd party related in my quest or response. Everything is under the Microsoft umbrella.

-------
(internal only) If I helped you, please take this 1-minute survey – https://aka.ms/chdafni-feedback

Chase Dafnis
Sr. Premier Field Engineer
US Public Sector
Microsoft Corporation
Office: 646.225.4724
Chase@microsoft.com<mailto:Chase@microsoft.com>
[Twitter]<https://twitter.com/Microsoft>    [Facebook] <https://www.facebook.com/Microsoft>     [Linkedin] <https://www.linkedin.com/company/microsoft>     [Youtube] <https://www.youtube.com/user/Microsoft>
[Microsoft Logo]

If you have any feedback about my work, please let either myself or my manager Dawn Spina know at Dawn.Spina@microsoft.com<mailto:Dawn.Spina@microsoft.com>

**Comment by joinimran** [comment]
@CHDAFNI-MSFT - Looks like I was not able to clear my point. Actually, I found on 3rd party website about reg key but we are not supposed to add the information available on the 3rd party websites. But if you have any information regarding or wanted to add any content in the document, please feel free to let me know. I will do that.

Hopes this clarifies this. 

Thanks
Imran.
