### ISSUE TITLE
Intune licensing possibly not included - clarify

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/windows-itpro-docs#5661]
This line 
"If you are an organization using Microsoft Defender ATP E5, you should be able to manage Tamper Protection in Intune similar to how you manage other endpoint protection features. See Turn Tamper Protection on (or off) for your organization using Intune." 
gives the impression that Windows 10 E5 includes an Intune license which I believe isn't the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a2f0402-82fb-83ff-122a-2f19c5288eeb
* Version Independent ID: 52f80b09-0e90-464d-0c4d-00479361fa9b
* Content: [Protect security settings with Tamper Protection - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello! I have updated this article to clarify the Intune requirement. Changes should render live sometime tomorrow. I will keep this issue open until then. Thanks very much for the feedback.

**Comment by denisebmsft** [comment]
Changes are rendering live, so I'm closing this issue.

**Comment by illfated** [comment]
Document updated: 01/15/2020 -- looks good to me. Thank you.
