### ISSUE TITLE
Gawd.

### ISSUE THREAD

**Issue by VashJuan** [MicrosoftDocs/windows-itpro-docs#5663]
How is a typical user getting a "Your admin requires a security scan" to deal with this?! 1st, I'm the admin (home user) and I sure didn't approve any such thing. 2) this is WAY COMPLEX - when all I expect is a "Proceed" or "Ignore" button, not some 30 minute to comply with article without even a "Make It So" button!  Geeze.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bd0fe29-5db5-b752-5bcf-5ac2581baa9a
* Version Independent ID: 52b8d4ca-54ea-7345-12b0-df4fdf633083
* Content: [Enable Block at First Sight to detect malware in seconds - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
Your complaint seems misdirected, this page is intended for IT Pro employees working in an IT department managing many users. How come you are dealing with cloud management configuration from your Windows Home computer?

**Comment by VashJuan** [comment]
Just installed Win 10 Pro from MS Vol Licensing a few days ago.

 

Now I’m getting these messages that direct me to this admin level web page:



 

No idea what would have caused this. I have installed Office 2019 and some developer tools (VS 2019 & VS Code) but not that much else.

 

Puzzled as you, on Vashon

 

- john

**Comment by illfated** [comment]
Very well, fair enough. I still think this is better suited as feedback to the Feedback Hub than reporting it here in the Microsoft Docs repository. I can only suggest that we wait for a comment or reply from one of the Microsoft Docs team members to recommend a suitable course of action for your feedback. We just need to be a little patient with the follow-up.

**Comment by VashJuan** [comment]
Sorry I don’t know the ins & out of the process these days. I’m just delighted someone saw the comment. Good on you for responding!  Appreciated.

 

- j

**Comment by Dansimp** [comment]
Sounds like there's a link in the product that should be pointing to an end-user page instead of an admin-focused page. I'll follow up with the product team about this

**Comment by denisebmsft** [comment]
Bug opened internally, so I'm going to close this issue.
