### ISSUE TITLE
Frequency of Definition Updates Released to WSUS

### ISSUE THREAD

**Issue by bryandam** [MicrosoftDocs/windows-itpro-docs#5664]
Can you clarify the frequency of which definition updates are released to the WSUS/ConfigMgr channel?  Historical and tribal knowledge says it's 3 times a day but I can't find that documented anywhere.  I'm being pressed (gently) to explain why I'm making the recommendation I am (sync 3 times a day).
I know the cloud-server side releases it more than 3 times a day but I'm not sure what if the WSUS side matches that or not.  I can also appreciate that you can't promise X releases a day.  However, something along the lines of 'We target X releases to the WSUS channel per day starting at time Y' would help people set appropriate sync schedules.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c033d14-427d-26d5-eca8-facf190da87d
* Version Independent ID: 624d52e5-6cf5-534e-83c3-66925292ddcd
* Content: [Manage how and where Windows Defender AV receives updates - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/manage-protection-updates-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/manage-protection-updates-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/manage-protection-updates-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@bryandam, updates are released several times per day.

**Comment by bryandam** [comment]
Yes, that I know.  I just wanted to confirm:
A) That they're specifically released to the WSUS channel
B) Is there any specific schedule that we should base our synchronizations upon?

If it's truly just 'we publish however and whenever we  feel the need to' that's perfectly fine.  If not then knowing the 'normal' schedule would help enterprise customers align their syncs and get the definitions out there even faster.

**Comment by denisebmsft** [comment]
Hi again,

Updates are released to the WSUS channel, and there isn't a specific schedule that I can share because it's subject to change. 

I hope this helps!
