### ISSUE TITLE
Activation Method "MAM"?

### ISSUE THREAD

**Issue by jamesonley** [MicrosoftDocs/windows-itpro-docs#5665]
For "Number of computers that do not connect to the network at least once every 180 days (or if no network meets the activation threshold)" the indicated activation method is "MAM". MAM is not discussed any where in this article. Should the activation method be "MAK"? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a980d182-aa7c-da78-4bb0-ada3e391d060
* Version Independent ID: c323e437-fcff-1949-85fa-1355e6c6d441
* Content: [Plan for volume activation (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/volume-activation/plan-for-volume-activation-client#feedback)
* Content Source: [windows/deployment/volume-activation/plan-for-volume-activation-client.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/volume-activation/plan-for-volume-activation-client.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Yes, that's a typo. Thanks for catching this.
