### ISSUE TITLE
Apps not downloading after Autopilot reset

### ISSUE THREAD

**Issue by dbdmora** [MicrosoftDocs/windows-itpro-docs#5668]
I enrolled a PC via AutoPilot, everything enrolled without issues.  I did an AutoPilot Reset to see what this does compare to a wipe.  It took me back to logon screen.  I logged on with same user but a few managed apps are not installing or uninstalling.  For example, since it is the same user and device name, it thinks that Chrome is already installed but it is not after the autopilot reset.   Does anyone have a fix or workaround for this? is Autopilot reset only good when giving device to another user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98a662f1-c2aa-33ad-0e71-d0cbb288d053
* Version Independent ID: 196f1c8d-3179-c173-194f-08bf3a6f82ca
* Content: [Windows Autopilot Reset - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-reset)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/windows-autopilot-reset.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@dbdmora . checkim your configuration .xml file once again in  winter.wim  or in recovery partition. You get clues to solve your self.
  if chrome is there with same version means , reset does not wiped fully

**Comment by dbdmora** [comment]
@RAJU2529 This is a surface pro 7, i am doing OOBE and it does not have Chrome installed.  This is not a custom installation or custom winre.wim file.  I am using Intune to download Chrome.

**Comment by RAJU2529** [comment]
@dbdmora . Is your surface pro 7 is connected to organization ,if yes means , then contact to system administrator of your organization

**Comment by e0i** [comment]
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
