### ISSUE TITLE
Should clarify

### ISSUE THREAD

**Issue by lucasititeam** [MicrosoftDocs/windows-itpro-docs#567]
I think it would be good idea to specifically point out User Portal Installation. In the above document, you are using mfa.corp.contoso.com as MFA server, MFAweb as SAN on MFA server. A configuration where in both MFA server and Portal will be installed on same server. But  then in user portal configuration  you are referring the same portal as https://mfaportal.corp.contoso.com/mfa. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08552f2d-5920-7a9b-a96b-6d3518b1a11a
* Version Independent ID: e6e8ac42-46ea-475c-016c-2b0931a72862
* Content: [Configure or Deploy Multifactor Authentication Services (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-deploy-mfa#enroll-for-server-authentication)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-deploy-mfa.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-cert-trust-deploy-mfa.md)
* Service: **unspecified**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by lucasititeam** [comment]
Test AD FS with the Multifactor Authentication connector - is incorrect named. This is connectivity between MFA and users. ADFS Adapter connectivity with MFA must be explicitly mentioned. It is as this precise step I'm stuck.

**Comment by MikeStephens-MS** [comment]
Sorry, I cannot follow what you are asking her.  In a production environment, the user portal would NOT be installed on the MFA server.  It would be an highly-available web application that would be load balanced accordingly.

Good call on the title, we'll update the title to reflect testing MFA.  To test the adapter, complete the remaining portion of the deployment and user provisioning will be your test for the adapter

**Comment by zerocarbthirty** [comment]
In Enroll for Server Authentication step 6 says choose the 'Internal Web Server' certificate template but that doesn't appear to be published, furthermore it's not listed in the template store. Where do you discuss the creation of that template?
