### ISSUE TITLE
Incorrect Field listed

### ISSUE THREAD

**Issue by 1800Zeta** [MicrosoftDocs/windows-itpro-docs#5670]
Hi, when describing the Event Data fields, you list 
Transited Services [Type = UnicodeString]: this field contains list of SPNs which were requested if Kerberos delegation was used.

I believe this should be Transmitted Services not Transited

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b88b81e4-6524-2c4e-fb58-bee2887b62d9
* Version Independent ID: 16ca6708-358b-21f8-2623-76f2651cc80c
* Content: [4769(S, F) A Kerberos service ticket was requested. (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4769)
* Content Source: [windows/security/threat-protection/auditing/event-4769.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4769.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by 1800Zeta** [comment]
Never mind, just realised in the rendered EventLog it's Transited, however the underlying XML is transmitted.

**Comment by illfated** [comment]
@1800Zeta : Are you saying that the current XML content should not be changed at all ??

**Comment by 1800Zeta** [comment]
> @1800Zeta : Are you saying that the current XML content should not be changed at all ??

Correct. There is a discrepancy between the XML and Display when looking at the Event Log. The documentation is correct.

**Comment by illfated** [comment]
OK, fair enough. Well. I guess we need to inform @MaratMussabekov that PR #5862 can be closed, then.

**Comment by e0i** [comment]
Thank you, closing the issue as well.
