### ISSUE TITLE
Table in article at the Reference section needs update

### ISSUE THREAD

**Issue by JonasBK** [MicrosoftDocs/windows-itpro-docs#5672]
Hi,
The Table in article at the Reference section has been updated with Win 10 but not Win 8, Win 8.1, Server 2012, and Server 2012 R2. Very confusing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d05d447-1cc1-1eeb-3c4d-74591874f4e1
* Version Independent ID: 020b4d09-5ce9-e636-0545-1ce27029a921
* Content: [Network security Configure encryption types allowed for Kerberos - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@JonasBK . Currently ,Microsoft concentrates for windows 10 edition only.

**Comment by e0i** [comment]
@JonasBK The associated PR #5944 has been merged. Thank you for the feedback.
