### ISSUE TITLE
The location is not Computer Configuration > Administrative Templates > System > PIN Complexity. 

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/windows-itpro-docs#5673]
Hi
At least in Group Policy Management, the location is NOT Computer Configuration &gt; Administrative Templates &gt; System &gt; PIN Complexity. 
The location is
Computer Configuration &gt; Administrative Templates &gt; System &gt; Logon .
- Then "Turn on Convenience pin sign-in"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 789566d4-463a-4c64-bf89-fb963ac29f80
* Version Independent ID: 02946732-bb29-d8e6-cedd-7f5e508f8798
* Content: [Manage Windows Hello in your organization (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-manage-in-organization#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-manage-in-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-manage-in-organization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by RAJU2529** [comment]
@blouwagie. I checked on windows 10 1909 64bit with latest 1909 administrative templates. 
Those settings are mentioned by you are currently located 

![upload1](https://user-images.githubusercontent.com/3296790/70728971-5595cf00-1d28-11ea-9945-364919de4355.JPG)
![upload2](https://user-images.githubusercontent.com/3296790/70728972-562e6580-1d28-11ea-954f-9c5b9899eb36.JPG)

**Comment by blouwagie** [comment]
You need to also document this HOW to locate it as a AD (domain) Group
Policy not just on a windows 10 Local Policy. Documentation should also
work for domain administrators, not just doing things one machine at a
time. And in the domain GPO that location does not exist, or it should at
least be documented that there is another location possible
Bart

Bart Louwagie

**Comment by RAJU2529** [comment]
@blouwagie. my laptop has standardalone and does not connected with  AD domain..
Thanks for reply

**Comment by illfated** [comment]
From **Windows Server 2016 Standard**, Version 1607 (OS Build 14393.3384):

![image](https://user-images.githubusercontent.com/38162891/72733922-2715da00-3b99-11ea-8c93-9477d6298a91.png)

**Comment by illfated** [comment]
For Your Information (FYI), here is a more inclusive image, with detailed policy information shown for the policy above:

![image](https://user-images.githubusercontent.com/38162891/73189332-838e7180-4124-11ea-9aff-117b8cef88ec.png)

**Comment by e0i** [comment]
The recent version of the article shows the path of PIN complexity for both old and new versions of Windows 10. Thank you.
