### ISSUE TITLE
Is 2012 R2 CA version really necessary?

### ISSUE THREAD

**Issue by mikeelliottuk** [MicrosoftDocs/windows-itpro-docs#5674]
Hi, the article describes the need to generate the Kerberos Authentication cert from a Server 2012 R2 CA.  Is the version of the CA really relevant if the template and resulting cert are created to the correct specification?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800b8090-65a9-da9f-a930-1f80dc9f2c2d
* Version Independent ID: b4495b6a-4ca5-7aa1-7964-ef6e19275c4e
* Content: [Configure Hybrid key trust Windows Hello for Business - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by VLG17** [comment]
@mikeelliottuk According to [this article](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs#public-key-infrastructure), yes it is:

> The minimum required enterprise certificate authority that can be used with Windows Hello for Business is Windows Server 2012.

**Comment by mikeelliottuk** [comment]
thanks @VLG17
