### ISSUE TITLE
WindowsDefenderATPCustomerTiConnector references are outdated

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#5675]
I believe Threat Intel API app was removed so references to WindowsDefenderATPCustomerTiConnector on this page are no longer valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70803311-0b38-8cbc-8566-d399b9280be2
* Version Independent ID: 2fbd7a65-951b-42fe-fb6a-97ad04edc621
* Content: [Troubleshoot SIEM tool integration issues in Microsoft Defender ATP - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-siem)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/troubleshoot-siem.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-siem.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
I presume you are referring to the sections containing the following numbered point:
***
4. Click **App registrations**. Then in the applications list, select the application:
    - For SIEM: `https://WindowsDefenderATPSiemConnector`
    - For Threat intelligence API: `https://WindowsDefenderATPCustomerTiConnector`
***
Point 4 appears in 2 consecutive sections:
- [**Learn how to get a new client secret**](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-siem#learn-how-to-get-a-new-client-secret) 
- [**Error when getting a refresh access token**](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-siem#error-when-getting-a-refresh-access-token).

If the second bullet point under point 4 is removed, using a bullet point for the remaining line seems redundant, so we should probably find a new phrasing for point 4 as soon as the removal of `WindowsDefenderATPCustomerTiConnector` is validated.

**Comment by iadgovuser1** [comment]
@illfated Yeah, WindowsDefenderATPCustomerTiConnector is used twice on that page both times under item 4 in a numbered list.

**Comment by illfated** [comment]
Very well. I think we should come up with a sufficient rephrasing of those 2 sections before moving on to a PR to suggest a practical change to the content.

**Comment by illfated** [comment]
(see PR #5981 concerning removal of the outdated information)

**Comment by e0i** [comment]
Closing via #5981. @iadgovuser1 Thank you for providing feedback.
