### ISSUE TITLE
Assigned Access Mode not support Windows.FullTrustApplication in MSIX

### ISSUE THREAD

**Issue by Cirnohalo** [MicrosoftDocs/windows-itpro-docs#5678]
I've tried to convert Win32 MSI to MSIX, and install it in the local account, set up a single-app kiosk.
When the user logs in, Windows attempts to run the application (the blue window appears with the loading spinner). The whole screen flickers for a minute or so and then an error message appears stating:

"We weren't able to start your app. Press Ctrl + Alt + Del to sign out or contact your system admin. For more info, search online for error code: 0x80270254".

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @Cirnohalo, our apologies for the inconvenience. We would love to help you with your concern, however, this GitHub-based documentation feedback system is intended to help improve the quality of the technical documentation of Microsoft Docs. What we recommend is to open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance. There are also other support resources that you can explore like the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can post your question and get help from the community. 

If you do have concerns about the technical documentation of Microsoft Docs, please use the feedback feature available on the content page to easily track content improvement requests. Thank you.

![image](https://user-images.githubusercontent.com/18371314/71547089-7f145300-29d6-11ea-8141-0977546d6d84.png)
