### ISSUE TITLE
Build a Web Farm with IIS Servers hyperlink is not working

### ISSUE THREAD

**Issue by santoshseth** [MicrosoftDocs/windows-itpro-docs#568]
In prerequisites section, Build a Web Farm with IIS Servers hyperlink is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42a0d794-1057-a599-1696-036207b2ce39
* Version Independent ID: 3e6535d2-b8af-4583-ca28-937aeb7f4520
* Content: [Planning for MBAM 2.5 High Availability](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/planning-for-mbam-25-high-availability#bkmk-load-balance)
* Content Source: [mdop/mbam-v25/planning-for-mbam-25-high-availability.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/planning-for-mbam-25-high-availability.md)
* Service: **unspecified**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by shortpatti** [comment]
@jamiejdt -- Can you take a look at this issue?

**Comment by andreabichsel** [comment]
Issue appears to be resolved, link is working.
