### ISSUE TITLE
Video hosting - Something other than YouTube?

### ISSUE THREAD

**Issue by lXbalanque** [MicrosoftDocs/windows-itpro-docs#5682]
Is there any way to host video content on something other than YouTube? Many corporate policies block YouTube. There are some other videos hosted on Microsoft's own services that aren't blocked so it would be nice to have an alternative.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83582e61-22b0-fb99-43c7-65a6694affef
* Version Independent ID: 61cc2546-2074-08b2-a6ed-e73da4825bfd
* Content: [Overview of Windows Autopilot - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/windows-autopilot.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Yes, Microsoft has a video hosting service. I'll try to get this video uploaded for you.

**Comment by lXbalanque** [comment]
Hi Greg, I appreciate that. Thanks for the prompt reply.

**Comment by RAJU2529** [comment]
How to find the user belongs to Microsoft.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
@officedocsbot assign @greg-lindsay

**Comment by greg-lindsay** [comment]
I don't own this video and the owners haven't replied. I imagine it'll have to wait until after the new year for people to get back and respond.

**Comment by greg-lindsay** [comment]
I have the original file, sorry it has taken so long. I'll see about uploading this to our video hosting service.

**Comment by lXbalanque** [comment]
No worries, Greg. I appreciate you staying on top of this! Its tough
when I'm at work since so much of this gets blocked but I should just
be more proactive and look at this stuff at home. Thanks for the
update.

**Comment by greg-lindsay** [comment]
This is still taking a long time, partly because I have to wait for replies from someone else and partly because I'm working on this on the back burner.  I made a little more progress today and hopefully it won't be too much longer until the video is copied to a place other than YouTube.

**Comment by lXbalanque** [comment]
No worries, no rush on this its just nice to know you're able to host
it somewhere else for those of us that can't use YouTube at work.

**Comment by greg-lindsay** [comment]
Sorry this took so long. The video is now also hosted here: https://www.microsoft.com/en-us/videoplayer/embed/RE4ATOx

I will add a link to this on the page also.
