### ISSUE TITLE
Emulator issue with AMD Ryzen CPU

### ISSUE THREAD

**Issue by Losmoges** [MicrosoftDocs/windows-itpro-docs#5683]
The Emulator does not seem to work well with AMD Ryzen CPUs as discussed on this GitHub issue: https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3198 

The suggested workaround to set the Emulator configuration to ProcessorCount: "1" works for my hardware configuration, which runs on AMD Ryzen Threadripper 1950X 16-Core Processor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c438ca41-3410-b203-52c3-80cd2cb307b1
* Version Independent ID: 83192241-5451-bd17-65bb-260f7d1b21c7
* Content: [HoloLens known issues](https://docs.microsoft.com/en-us/hololens/hololens-known-issues#feedback)
* Content Source: [devices/hololens/hololens-known-issues.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/hololens-known-issues.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by scooley** [comment]
I'll get that documented in known issues!  Mostly expect people to hit that dev side but never hurts to cross reference.

Thanks!

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
@officedocsbot assign @scooley
