### ISSUE TITLE
"Enable the custom threat intelligence application" text no longer relevant

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#5688]
Custom TI app was removed so that text is no longer relevant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c443d8dd-5e54-c255-d3fd-6a60b5188ee9
* Version Independent ID: 7c1c9819-e92a-d364-ee79-7129a73912ce
* Content: [Overview of management and APIs - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/management-apis)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/management-apis.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/management-apis.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thanks for the feedback @iadgovuser1. Much appreciated!

Hi @mjcaparas, can you please confirm or provide some insights on this? Thank you so much!

@officedocsbot assign @mjcaparas

**Comment by mjcaparas** [comment]
content updated
