### ISSUE TITLE
completly wrong

### ISSUE THREAD

**Issue by alouko** [MicrosoftDocs/windows-itpro-docs#569]
how people write docs here?
aoslotly wron, no gpo tab since 2012
no windows defender firewall in Network Connections

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68262173-057b-e0ec-03a4-54045e7a8bb8
* Version Independent ID: a0bb0dbb-e9e1-0e0c-cbac-0f6718c59ece
* Content: [Open the Group Policy Management Console to Windows Defender Firewall with Advanced Security (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/windows-firewall/open-the-group-policy-management-console-to-windows-firewall#feedback)
* Content Source: [windows/security/identity-protection/windows-firewall/open-the-group-policy-management-console-to-windows-firewall.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/windows-firewall/open-the-group-policy-management-console-to-windows-firewall.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by shortpatti** [comment]
@alouko -- I will take a look at this issue and provide clearer details in the content.

**Comment by Justinha** [comment]
@alouko Thanks for the feedback. I corrected how to open the GPO. I confirmed location for Windows Defender Firewall under Network Connections.
