### ISSUE TITLE
There is a v3.7.x of the 'DG & DC Readiness tool'

### ISSUE THREAD

**Issue by HenkPoley** [MicrosoftDocs/windows-itpro-docs#5690]
'Windows Defender Device Guard and Windows Defender Credential Guard hardware readiness tool' v3.7 is found here:

https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg_readiness_tool

Edit: There is now a v3.7.1 at: https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg-readiness-tool (note "_" --> "-")

At the top of https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage there is still a link to v3.6 as a "convenient" but old download. 

> Windows Defender Credential Guard can be enabled either by using Group Policy, the registry, or the Hypervisor-Protected Code Integrity and Windows Defender Credential Guard >>>hardware readiness tool<<<. 

Microsoft should update that download.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#disable-windows-defender-credential-guard)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by beerisgood** [comment]
So this fix my issue?:
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5558

**Comment by HenkPoley** [comment]
Related:

* Why is the v3.7 download not at/near the older download location. So the page could show you a related downloads (other versions) selector.
* Why is the PowerShell script not in a repo that can accessed with Install-Module ?

**Comment by jvsam** [comment]
Thank you so much for bringing this to our attention @HenkPoley.

Hi @DulceMontemayor, is this [content page](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg_readiness_tool) the official *Windows Defender Device Guard and Windows Defender Credential Guard hardware readiness tool v3.7* version? And will this https://www.microsoft.com/en-us/download/details.aspx?id=53337 be updated? 

@ManikaDhiman sorry to tag you here. I have checked the commit history and noticed you have updated the Readiness tool link to point to this new page - https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg_readiness_tool. Can you please assist 

@officedocsbot assign @HenkPoley

**Comment by jvsam** [comment]
@officedocsbot assign @ManikaDhiman

**Comment by illfated** [comment]
> Hi @DulceMontemayor, is this [content page](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg_readiness_tool) the official _Windows Defender Device Guard and Windows Defender Credential Guard hardware readiness tool v3.7_ version? And will this page - https://www.microsoft.com/en-us/download/details.aspx?id=53337 - be updated?

Based on my own experience, the most common practice is to create a new download ID link (a new page) for any new version of a downloadable package on https://www.microsoft.com/download/.

It would be very good if the download page & link could be generated and placed at the bottom of that page each time the script is updated. I also presume it would be risky to automate that process (for various editorial & security reasons).

**Comment by illfated** [comment]
- https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg-readiness-tool

***

I am going to open a PR to make a couple of improvement changes to that page. Also note that the discussion is still going on in the closed issue ticket https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5972

**Comment by JasonHershey** [comment]
I'm a bit confused.  Is the script at https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg-readiness-tool the 3.7.1  version?  Should we use that or the 3.6 one -- or go to the ticket above to pick up the 3.7 version.

**Comment by HenkPoley** [comment]
There is a 3.7.2 version with 'proposed' patches: https://github.com/illfated/windows-itpro-docs/commit/e25231e6ffc23ef6109b9a9bd5e791902c95f6d6

'the file' is in here: https://github.com/illfated/windows-itpro-docs/blob/e25231e6ffc23ef6109b9a9bd5e791902c95f6d6/windows/security/identity-protection/credential-guard/dg-readiness-tool.md

**Comment by HenkPoley** [comment]
There is still a link called "hardware readiness tool" to the old v3.6 at the top of: https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage

**Comment by beerisgood** [comment]
We should provide the latest version to end user without the need to search at GitHub.

And not again with too much time, as even this issue here is open long enough.
Can't this be build automatic?

**Comment by HenkPoley** [comment]
It also should just be a file to download, not this weird copy pasting from a website stuff like it's PHP from the '90s.

**Comment by e0i** [comment]
Seems like the issue has been addressed via merged commit, #6575. Thank you.

**Comment by beerisgood** [comment]
@e0i sadly the first link on https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage still provide old 3.6 version: https://www.microsoft.com/en-us/download/details.aspx?id=53337

**Comment by illfated** [comment]
The main difficulty with the link https://www.microsoft.com/download/details.aspx?id=53337 is that the www.microsoft.com links and their content is handled elsewhere, external to the MS Docs area of responsibility.

**Comment by beerisgood** [comment]
Sadly on https://www.microsoft.com/en-us/download/details.aspx?id=53337 still the old 3.6 version from 10/26/2018 is listed.
I don't understand why nobody can change that to latest version.

Should end user's really first search and then manually copy the code from https://docs.microsoft.com/de-de/windows/security/identity-protection/credential-guard/dg-readiness-tool ?
Doesn't make sense for me

**Comment by illfated** [comment]
Seems a bit odd, now that you mention it. I wonder what the rationale is for keeping the old version.

**Comment by HenkPoley** [comment]
I made a pull request here to remove the link to the ancient deprecated version: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8076
