### ISSUE TITLE
Cant Login

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#5692]
After entering the credentials i'm getting the message "That username looks like it belongs to another organization. Try signing in again or start over with a different account" with the offline profile. With online it works normally. Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17bfe927-f7b7-608b-8537-5c2274ccdced
* Version Independent ID: 5dd9abca-92d9-fbb2-6796-d1f6b9ab3c8b
* Content: [Windows Autopilot for existing devices - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/existing-devices#feedback)
* Content Source: [windows/deployment/windows-autopilot/existing-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/existing-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by schenardie** [comment]
Can be closed. Fixed. Thanks

**Comment by DecimalZero** [comment]
I'm having the same issue. What was the fix?

**Comment by illfated** [comment]
@DecimalZero : I believe @schenardie will be the only one who knows the answer to your question here, as there were no troubleshooting performed in this ticket. Any luck checking issue ticket #6399 ?

**Comment by benrfinn** [comment]
Hi, I had to open a ticket with Microsoft. I don't want to be rude but they are wasting time and proving useless so far. Ticket is being worked on for two weeks.

**Comment by schenardie** [comment]
In my case when copying the tenant id to the offline file i Missed the last character. Double check everything would be my advice.
