### ISSUE TITLE
Wrong sub-title

### ISSUE THREAD

**Issue by homoSapiensSapiens** [MicrosoftDocs/windows-itpro-docs#5695]
In all of the guide parts, the last section reads "Follow the Windows Hello for Business on premises certificate trust deployment guide" instead of "Follow the Windows Hello for Business on premises *key* trust deployment guide"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a2341a7-208e-b60b-c8d2-041bab39a630
* Version Independent ID: c790a99e-fcde-e9d5-1514-9c2bd328053f
* Content: [Validate Public Key Infrastructure - key trust model (Windows Hello for Business) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-key-trust-validate-pki#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-key-trust-validate-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-key-trust-validate-pki.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mypil** [comment]
@homoSapiensSapiens -  Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/02c5ed93e666f79c20828abc8113789fb42ba4fe. 


Thank you for your contribution to make the docs better! Much appreciated!
