### ISSUE TITLE
Screensaver & lockscreen in kiosk mode

### ISSUE THREAD

**Issue by Andreiyw** [MicrosoftDocs/windows-itpro-docs#5697]
Hello! the problem is that the kiosk account does not inherit the administrator account settings such as splash screen, lock screen, etc. Or, I would like to know how I can configure these two settings for the restricted account separately.

**Comment by mypil** [comment]
@Andreiyw - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@Andreiyw - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
