### ISSUE TITLE
Why SIEM REST API is not supporting query per status and/or classification ?

### ISSUE THREAD

**Issue by akefallonitis** [MicrosoftDocs/windows-itpro-docs#5699]
This way All rest api connectors to retrieve alert are suffering duplicated and no support for advanced querying 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b835bf35-1614-2d8d-13ab-176c6d839047
* Version Independent ID: ed4653f3-e393-dd42-5960-87888c08ba40
* Content: [Pull Microsoft Defender ATP detections using REST API - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/pull-alerts-using-rest-api#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/pull-alerts-using-rest-api.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/pull-alerts-using-rest-api.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by joinimran** [comment]
Hello @akefallonitis Can you please explain in details what exact information is missing in the document so that we can make necessary changes.

**Comment by mypil** [comment]
@akefallonitis - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. 

Thank you.
