### ISSUE TITLE
Versions of Configuration Manager that MBAM supports

### ISSUE THREAD

**Issue by clconlin** [MicrosoftDocs/windows-itpro-docs#570]
I noticed on the MBAM Supported Configurations page it states that it supports Configuration Manager 1610 but no mention of higher versions. Should we be requesting this be updated to state “version 1610 and later”?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bd86f5e-6388-d226-2460-997fc24945d9
* Version Independent ID: aa827a7d-725a-a5d0-f6aa-3f1df8cc310a
* Content: [MBAM 2.5 Supported Configurations](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/mbam-25-supported-configurations#feedback)
* Content Source: [mdop/mbam-v25/mbam-25-supported-configurations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/mbam-25-supported-configurations.md)
* Service: **unspecified**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by shortpatti** [comment]
@jamiejdt -- Can you take a look at this issue?
