### ISSUE TITLE
add link and cleanup language

### ISSUE THREAD

**Issue by luriep** [MicrosoftDocs/windows-itpro-docs#5701]
on https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-account?source=docs#finalize-setup-via-powershell  it is not clear that Set Calendar Auto processing is required for bothe Teams and Skype environments. 

Suggest changing: 
Calendar: Set Calendar Auto processing for this account.

to say
Microsoft Teams and Skype for Business Calendar: Set Calendar Auto processing for this account.

and make "Set Calendar Auto processing" a hyperlink to https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-account?source=docs#set-calendar-auto-processing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9d48034-4b29-c10c-6e14-ecf14ca12f70
* Version Independent ID: 7794a57a-0db1-6420-68e9-0d1592a57b60
* Content: [Create Surface Hub 2S device account - Surface Hub](https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-account?source=docs#feedback)
* Content Source: [devices/surface-hub/surface-hub-2s-account.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/surface-hub-2s-account.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@luriep -  Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/2fc0145b5f0321885ff1f059b08e932dbce2675b. 


Thank you for your contribution to make the docs better! Much appreciated!
