### ISSUE TITLE
Configured BitLocker base settings but status shows: Used Space Only Encrypted

### ISSUE THREAD

**Issue by lXbalanque** [MicrosoftDocs/windows-itpro-docs#5707]
I have a need for the disk to be FULLY ENCRYPTED. Unfortunately, while the configuration worked it shows that the Conversion Status: Used Space Only Encrypted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f28f994-ad0f-72e5-79d2-6898421cb2fd
* Version Independent ID: dbb83bbb-73cc-8233-15fb-1363b8ad1cd1
* Content: [Setting the BitLocker encryption algorithm for Autopilot devices - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/bitlocker)
* Content Source: [windows/deployment/windows-autopilot/bitlocker.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/bitlocker.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
What Windows 10 version are you using?

**Comment by lXbalanque** [comment]
Hi Greg, this is 1903 - 18362.239.

**Comment by greg-lindsay** [comment]
I've researched it a bit and haven't found a solution yet.  I've just sent a message internally to see if others have run into this or have some ideas.

**Comment by lXbalanque** [comment]
Hi Greg, I appreciate the prompt replies and you looking into this. The correct settings have been applied (XTS-AES 256) but I don't know how to make it full disk encryption vs. used space only. Anything you can provide would be greatly appreciated.

**Comment by RAJU2529** [comment]
@lXbalanque . Will you make video and share the video so that expert users will watch and give exact solution..make sure that your disk is completely matched with bitlocker requirements..

**Comment by lXbalanque** [comment]
![Annotation 2019-12-17 080234](https://user-images.githubusercontent.com/26438193/71012335-d4319a00-20a3-11ea-90bd-2bf0609200ab.jpg)
I didn't have a way to record any video from the laptop that I'm testing Windows Autopilot on so I hope this screenshot will suffice.

It is a Dell Latitude 5490
Intel Core i5 / 16GB RAM / 250GB SSD

The screenshot shows the BitLocker encryption status as well as the TPM/Security Processor information. I'm certain that Full Disk Encryption is possible as I can manually run the commands to get it there but need this to be done as part of the Autopilot deployment to help us streamline our process.

**Comment by greg-lindsay** [comment]
Can you try creating some logs with “mdmdiagnosticstool.exe -area Autopilot -cab c:\autopilot.cab” and sharing these?  Also please look in the Windows Event Logs (Application and Services Logs –> Microsoft –> Windows –> ModernDeployment-Diagnostics-Provider –> AutoPilot) for anything related to BitLocker.

**Comment by lXbalanque** [comment]
[symm_autopilot.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/3975156/symm_autopilot.zip)
Hopefully this contains the information you need. I looked into the event logs for ModernDeployment etc->AutoPilot but didn't see anything specifically calling out the BitLocker policy. Initially, when I first got into the system and checked the Intune portal, the configuration policy said that it succeeded (albeit not fully encrypted). Let me know if there's any additional troubleshooting information I can provide.

**Comment by greg-lindsay** [comment]
I'm beginning to think that this is the default setting and can't be changed without a workaround of some kind. See this customer request made in 2018: https://microsoftintune.uservoice.com/forums/291681-ideas/suggestions/36004525-bitlocker-full-drive-encryption-setting

Still looking into it.

**Comment by lXbalanque** [comment]
Bummer. Of course, the UserVoice hasn't had any action on it in nearly a year. Is there any kind of documentation from the Microsoft detailing the difference between Used Space Only and Full Disk Encryption? At the very least, I can provide documentation on the validity of used space only vs. FDE. That would be helpful.

**Comment by greg-lindsay** [comment]
I'm still waiting to verify that this is indeed the only option. My request has been forwarded a few times to get to the right people.  If it turns out this is the only method, I'll provide some details about what exactly this setting means in a practical sense.

**Comment by RAJU2529** [comment]
@lXbalanque .  you have not chosen this option, while enabling BitLocker 

![add](https://user-images.githubusercontent.com/3296790/71106403-54abe400-21e5-11ea-9129-65032b347b38.JPG)

**Comment by RAJU2529** [comment]
@lXbalanque. Disable BitLocker, then re enable BitLocker choose above screenshot option

**Comment by lXbalanque** [comment]
Hi @RAJU2529, there might be some misunderstanding about what's going on here. I've defined a configuration policy within Intune (Intune Portal -> Device Configuration -> Profiles). In this screen, I've configured a Windows 10: BitLocker policy

![image](https://user-images.githubusercontent.com/26438193/71108423-e846cb80-2177-11ea-9c9a-354bf85681e8.png)

![image](https://user-images.githubusercontent.com/26438193/71108438-f268ca00-2177-11ea-9a99-be53e1de0948.png)

I'm only concerned with full disk encryption for the root/OS drive. We block access to USB devices and don't allow for any other devices to be connected to the machine.

The policy should be applied during AutoPilot setup (if my understanding of the product is correct). I'm trying to avoid as much manual configuration as possible so what your screenshot shows is one of the steps I'm trying to eliminate. I'm fully aware of the options in Windows to manually enable BitLocker, we've also already gone through the process of doing this via command prompt (manage-bde -on c: -em xts_aes256) but the whole idea of AutoPilot is to push down all of these policies "automagically" to automate as much of this process as possible.

I hope this elucidates the issue I'm running into. Happy to provide more information if you need anything.

**Comment by greg-lindsay** [comment]
@lXbalanque I understand the issue :)

I've confirmed that the MDM stack (Intune profile settings) currently supports only used space encryption.  You can probably see that by going through all the settings that you've shown above. There is no available choice for "encrypt entire drive" or "full encryption" even though there are a lot of other settings.

The thing is, this setting will make no difference at all for a Windows Autopilot device because the device is new and doesn't have any old data in the 'free' space. You can read a little about what this setting means here: https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10#used-disk-space-only-encryption

As you might know, when you delete files or when you format a disk, the files do not actually get deleted. They are only marked as unused space.  The data will remain there until it is overwritten. If you have a device that never encrypted but was used for a period of time, then you decide to encrypt used space only, then you will have some old data on the drive that is not encrypted.  When new data is written to the drive that data will be lost, but until that time it is recoverable.

The Windows Autopilot device is a new device, so there should not be any data in the free space and choosing to encrypt those disk sectors will take a significantly longer time because most of the drive is free space.

Does this resolve the issue?

**Comment by lXbalanque** [comment]
@greg-lindsay I figured you and I were on the same page but just in case anyone else came along and maybe I wasn't clear enough, I figured I'd try to lay out some more detail :)

Thanks for your reply. I don't know if there's anyone you can pass this onto but we have audit/CIS controls that require devices to show as fully encrypted. We might be able to provide the current MS documentation on used space encryption and that might suffice but it would be helpful to be able to confidently say that when a device goes through AutoPilot and is assigned a BitLocker policy, that it performs full disk encryption (it doesn't seem too difficult to be able to implement this but I won't pretend to know the complexities in implementing a policy that does this).

Thanks for your help in answering my questions.

**Comment by greg-lindsay** [comment]
Understood. I am still waiting on a reply from someone on whether there is a workaround to change the setting somewhow before encryption begins  I'll continue to let you know what I find out even though the issue is closed.

Note: I am heading out for the holidays tomorrow but I'll be checking email while on vacation.

**Comment by lXbalanque** [comment]
Much appreciated, Greg. Have a great holiday.

**Comment by greg-lindsay** [comment]
FYI, I didn't get any answer before everyone headed out for the holidays. I'll continue to look into this when people are back in the office in 2020.

**Comment by greg-lindsay** [comment]
Looking at this again. I'm trying to determine if there is a way to change from 'used space' to 'full encryption' without decrypting the entire drive. It seems rather short sighted if this option isn't available.

**Comment by greg-lindsay** [comment]
I confirmed that if you must have the setting at Full Encryption then the only way to do this is to decrypt and then re-encrypt the device after it is up and running.  In general there isn't a reason to use Full Encryption on a new device because Used Space Only is more efficient and is the same from a security perspective.

**Comment by lXbalanque** [comment]
> I confirmed that if you must have the setting at Full Encryption then the only way to do this is to decrypt and then re-encrypt the device after it is up and running. In general there isn't a reason to use Full Encryption on a new device because Used Space Only is more efficient and is the same from a security perspective.

Greg, I appreciate you looking into this again. I have to agree that it is shortsighted. Not all computers are going to be new out of box or come with encryption enabled. The scenario is one that's common across all organizations and that is when we recover a laptop from a user that has left, we reimage the laptop. However, this doesn't zero out the hard drive. In this case, the data that was previously written to a potentially unencrypted drive remains unencrypted. I would be surprised if organizations start off thinking they want to run full disk encryption from the get-go. I don't know if this can be pushed up the chain but it seems like something that should really be available. 

At any rate, thanks again, Greg. I'll have to run the decrypt and then full encryption for consistent results.

**Comment by greg-lindsay** [comment]
I'll make sure to restate this. What I've been told by more than one person is to run manage-bde -w C: (or any other involved volume) to clean up free space. I also posted to a thread about this here: https://social.technet.microsoft.com/Forums/windows/en-US/060c3b89-4b38-4217-b3a0-823331bd3030/bitlocker-how-to-change-quotused-space-only-encryptedquot-to-full?forum=win10itprosecurity

You can read the response there. There's also mention of the command **cipher /w:c:\**

**Comment by illfated** [comment]
(Ref. #5755 )
