### ISSUE TITLE
Maybe a "not" in there?

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/windows-itpro-docs#571]
The following section from https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install#public-key-infrastructure: 

"Configure a Production Public Key Infrastructure
If you do have an existing public key infrastructure, please review Certification Authority Guidance from Microsoft TechNet to properly design your infrastructure. Then, consult the Test Lab Guide: Deploying an AD CS Two-Tier PKI Hierarchy for instructions on how to configure your public key infrastructure using the information from your design session.
Important
For Azure AD joined device to authenticate to and use on-premises resources, ensure you:
Install the root certificate authority certificate for your organization in the user's trusted root certifcate store.
Publish your certificate revocation list to a location that is available to Azure AD joined devices, such as a web-based url.
Section Review
Miniumum Windows Server 2012 Certificate Authority.
Enterprise Certificate Authority.
Functioning public key infrastructure.
Root certifcate authority certificate (Azure AD Joined devices).
Highly availalbe certificate revoication list (Azure AD Joined devices)."

Are we certain it meant "If you do have an existing public key infrastructure" or "If you do NOT have an existing public key infrastructure"?

Also, there are some typos here and there. Otherwise, great documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4784e8f-6d35-78d8-9160-7b39832a58d8
* Version Independent ID: 7f79559a-3a6d-473b-1ec1-66746c461318
* Content: [Windows Hello for Business Key Trust New Installation (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install#public-key-infrastructure)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install.md)
* Service: **unspecified**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by MikeStephens-MS** [comment]
Fixed-- Thanks for the feedback. Should be published soon.
