### ISSUE TITLE
Incorrect title

### ISSUE THREAD

**Issue by kStarbe** [MicrosoftDocs/windows-itpro-docs#5714]
3) Confirm that Cloud-based Protection and Automatic sample submission are switched to On.
should read 
3) Confirm that Cloud-delivered Protection and Automatic sample submission are switched to On.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bd0fe29-5db5-b752-5bcf-5ac2581baa9a
* Version Independent ID: 52b8d4ca-54ea-7345-12b0-df4fdf633083
* Content: [Enable Block at First Sight to detect malware in seconds - Windows security](https://docs.microsoft.com/en-gb/windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
And as an extension of that correction, I assume this correction is also needed for the sentence above the image:

> Block at first sight is automatically enabled as long as **Cloud-based protection** and **Automatic sample submission** are both turned on.

The name "Cloud-delivered Protection" is present in Windows 10 Home 1909 18363.535, but regarding Windows 10 Professional, I need to change my GUI language to see if this is the case there too.

**Comment by denisebmsft** [comment]
@kStarbe thank you for your feedback, and @illfated thank you for your help. You are helping us improve the quality of our documentation. I have updated the article to fix the incorrect phrases, and the changes should be live soon. Closing this issue, but please feel free to reach out if you have more questions or additional feedback.
