### ISSUE TITLE
v1.6.0.0 - /Output flag returns help text

### ISSUE THREAD

**Issue by MrEnigmamgine** [MicrosoftDocs/windows-itpro-docs#5716]
Hi,

So it turns out in this version if you try to use the output flag it just pretends that your syntax is wrong.  I even tried using the exact command from Example 2 of the help text and still got the error.

```
PS D:\Downloads>
PS D:\Downloads> .\SetupDiag.exe /Output:C:\SetupDiag\Results.xml /Format:xml

SetupDiag v1.6.0.0
Copyright (c) Microsoft Corporation. All rights reserved.



Usage:
/Output:[Full path and file name for output log file] - Optional - Specifies the name and location for the results log file.
/LogsPath:[Full path to logs]- Optional - Specifies the location of logs to parse. Defaults to checking the current system for logs.
/ZipLogs:[True | False] - Optional - Tells SetupDiag.exe to create a zip file containing the results and all the log files that were parsed. The default value is true.
/Format:[xml | json] - Optional - Specifies the output format for log files to be XML or JSON. If not specified, text format is used.
/Scenario:[Recovery] - Optional - Instructs SetupDiag.exe to look for and process reset and recovery logs and ignore setup/upgrade logs.
/Verbose - Optional - Creates a diagnostic log in the current directory, with debugging information and details about SetupDiag.
/NoTel - Optional - Tells SetupDiag.exe not to send diagnostic telemetry.
/RegPath - Optional - Instructs SetupDiag.exe to add failure information to the registry under the given path.
        Registry paths should start with HKEY_LOCAL_MACHINE or HKEY_CURRENT_USER and be accessible at the elevation level SetupDiag is executed under.
/AddReg - Optional - Instructs SetupDiag.exe to add failure information to the registry on the executing system.
        SetupDiag will by default add failure information to the registry in Online mode only.
        Registry data will go to HKEY_LOCAL_MACHINE\SYSTEM\Setup\MoSetup\Volatile\SetupDiag unless otherwise specified.

Examples:
Example 1 - Offline Mode
SetupDiag.exe /Output:C:\SetupDiag\Results.txt /LogsPath:D:\Temp\Logs\Logs1 /RegPath:HKEY_CURRENT_USER\SYSTEM\SetupDiag
Instructs SetupDiag to parse setup/upgrade log files in the LogsPath directory and output the results to C:\Setupdiag\Results.txt.

Example 2 - Online Mode
SetupDiag.exe /Output:C:\SetupDiag\Results.xml /Format:xml
Instructs SetupDiag to look for setup/upgrade logs on the current system and output its results in XML format to C:\SetupDiag\Results.xml.

Example 3 - Online Mode, no parameters needed
SetupDiag.exe
Instructs SetupDiag to look for setup/upgrade logs on the current system and output the results to the same directory where SetupDiag is located.

Example 4 - Reset/Recovery Offline Mode
SetupDiag.exe /Output:C:\SetupDiag\RecoveryResults.log /LogsPath:D:\Temp\Cabs\PBR_Log /Scenario:Recovery
Instructs SetupDiag to look for reset/recovery logs in the specified LogsPath location and output the results to the directory specified by the /Output parameter.

Example 5 - Reset/Recovery Online Mode
SetupDiag.exe /Scenario:Recovery /Format:xml
Instructs SetupDiag to look for reset/recovery logs on the current system and output its results in XML format.
PS D:\Downloads>
```

**Comment by illfated** [comment]
Which of the docs pages is this related to? Maybe this one, linked below?
- https://docs.microsoft.com/windows/deployment/upgrade/setupdiag
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/setupdiag.md

BTW, if that is the correct page, did you read through the old & closed issue tickets to see if there is anything useful there to help finding out more?
- https://docs.microsoft.com/nb-no/windows/deployment/upgrade/setupdiag#tabpanel-issues-closed

I noticed that one of the comments suggested that SetupDiag requires existing and/or failed setup install logs to work (maybe I misunderstood something).

**Comment by RAJU2529** [comment]
@MrEnigmamgine. I have sorted the problem and found the solution 
go tothe  command prompt with administrator rights
then type below command

**md "C:\Tools\SetupDiag\SetupDiag Results"**

and copy the file to **SetupDiag.exe** to **C:\Windows\System32\**

and then type the command

SetupDiag.exe /Output:C:\Tools\SetupDiag\Results.xml /Format:xml

this software will work when windows upgrade is failed  from the existing version

**Comment by e0i** [comment]
It seems that your question has been answered by the community and thus we are marking this issue as resolved.

Please note that the issues section of this repository is intended for documentation feedback.

Should you have any further issues similar to this one, please consider opening a product support ticket here:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Feel free to re-open this issue if you feel that there are further suggestions to improve the documentation itself.

Thank you for providing feedback.
