### ISSUE TITLE
Missing codes

### ISSUE THREAD

**Issue by dbutcheratrenet** [MicrosoftDocs/windows-itpro-docs#5718]
My windows Update is failing (repeatedly) with codes:
0x80070020
0x800f0845
Please add them

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f76d96ac-5343-20e2-9d99-9c1cea7ccc2e
* Version Independent ID: a95c9b39-4a66-d726-4404-de5af60ac982
* Content: [Windows Update error code list by component - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-error-reference#feedback)
* Content Source: [windows/deployment/update/windows-update-error-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-error-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
I think your request would stand a better chance of making it into the documentation if the error codes you refer to could be documented better in this ticket. Then again, I do not know if the 0x800... and 0x801... series belong in this exact page. We may need to wait until any developer can comment on whether the error code series 0x800... and 0x801... contain any related description or base causes.

**Comment by illfated** [comment]
(see also tickets #6324 and #6337 for similar (minimalistic) reports)

**Comment by greg-lindsay** [comment]
Hi, the troubleshooting article was created prior to the publishing of the SetupDiag tool.  This tool is now the preferred method to analyze failed upgrades.  https://docs.microsoft.com/en-us/windows/deployment/upgrade/setupdiag

Can you please try this tool?  We don't have the ability to provide a custom description for every error code at this time.
