### ISSUE TITLE
PlugInComplianceBlock is mentioned two times 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#5720]
PlugInComplianceBlock  is  mentioned two  times  and I have verified with  rules embedded in  .text file in setupdiag.exe  file. In that file  PlugInComplianceBlock was mentioned three times 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ad81361-15d8-0e95-9d5f-090dbf270f10
* Version Independent ID: c0c32397-d5d6-cce1-79fd-c310bec05240
* Content: [SetupDiag - Windows Deployment](https://docs.microsoft.com/en-in/windows/deployment/upgrade/setupdiag#feedback)
* Content Source: [windows/deployment/upgrade/setupdiag.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/setupdiag.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
I'll look into this and clarify, however I'm going to be out for the holiday for about a week starting tomorrow.

**Comment by ScottHendrix-MSFT** [comment]
The best way to get help for SetupDiag is to submit Feedback via the Feedback Hub and include the word SetupDiag in the title.

There are many compliance plug-ins that can all trigger a block.  SetupDiag exposes any and all of them in a single execution if they are applicable to the system/update.  The plug-ins should all be named and have a unique message, if they don't, please let me know.
