### ISSUE TITLE
Is it possible to configure different policy to unsuccessful login with different passwords and same password?

### ISSUE THREAD

**Issue by linyinghuan** [MicrosoftDocs/windows-itpro-docs#5725]
Try to login with different password could be a kind of attack. But login fail with same password mostly caused by an auto-login system with an error or expired password.  Is there any way to ignore the failure with same password?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3974da73-1577-dbaf-00ec-f6fb6eee35df
* Version Independent ID: a562ec45-0c96-733b-2bef-c12f627dc02f
* Content: [Account Lockout Policy (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/account-lockout-policy#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/account-lockout-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/account-lockout-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@linyinghuan.    disable the auto-login feature by using GPO  or by a registry key
**https://www.securicy.com/blog/how-to-disable-automatic-login-in-windows-10**


Configure the accounts related policies under computer configuration by group policy editor

 Computer Configuration\Windows Settings\Security Settings\Account Policies\Password Policy\
Computer Configuration\Windows Settings\Security Settings\Account Policies\Account Lockout Policy\

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by linyinghuan** [comment]
@RAJU2529  Thanks a lot. 
In our company environment, there are lots of virtual machines and test devices. Some of them needs auto-login feature. I'm just trying help our IT administrator get out of unlocking account everyday and ignore same password failure sounds make sense :)

**Comment by jvsam** [comment]
Hello @linyinghuan, please note that you can always contact [Windows 10 Support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) to get answers to your questions. You can also explore the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can collaborate and discuss any issues or concerns with the community (*and post questions, if you want*). Thank you. 

**NOTE:** This GitHub-based documentation feedback system is intended to help improve the quality of the technical documentation of Microsoft Docs. If you have feedback, suggestions related to this documentation, or ideas to make it better for users, you can open an issue on a specific content page by using the feedback feature so it can easily be tracked.
