### ISSUE TITLE
Troubleshooting - Add GPOs

### ISSUE THREAD

**Issue by Jlentz4** [MicrosoftDocs/windows-itpro-docs#5726]
Peer discovery appears to be affected by GPO settings (such as the "Minimum disk size allowed to use peer caching" setting) and should be added as Troubleshooting steps to ensure GPO is not being too strict and preventing machines from being peers or discovering peers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb67e518-6f60-23e0-2545-c2839e2b4159
* Version Independent ID: e9a31629-e3cb-0367-31c4-5661284d89bf
* Content: [Configure Delivery Optimization for Windows 10 updates (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization#feedback)
* Content Source: [windows/deployment/update/waas-delivery-optimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-delivery-optimization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @Jlentz4, we appreciate you taking the time to share your feedback. Do you have any suggestion on the exact messaging that you want to see on the the documentation so we can assist in creating a Pull Request (PR), and submit it to the author for review and approval? And if this is the topic (*Delivery Optimization for Windows 10 updates*) where update should be added? Also, there is already information under [More detail on Delivery Optimization settings](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization-reference#more-detail-on-delivery-optimization-settings) regarding requirements and best practices. Thank you.

**NOTE:** This GitHub-based documentation feedback system is designed to allow community contributions. If you have suggestions or ideas that you want the MS authors to review and apply (*if approved*) to the docs, you can create a Pull Request (PR) and start contributing to Microsoft Docs. You can check and read the [Microsoft Docs contributor guide](https://docs.microsoft.com/en-us/contribute/), if you are interested. The content page contains information on working with GitHub repositories, Markdown tools, etc.

**Comment by jvsam** [comment]
Just to add, this MS Video provides a great explanation when it comes to *Custom Device Settings* and *Peer Caching*.

https://techcommunity.microsoft.com/t5/Configuration-Manager-Blog/Peer-Caching-Part-1-Caching-Understanding-the-options/ba-p/657036

**Comment by Jlentz4** [comment]
Hi,

Yes, this is where it should be added. Specifically I think it would be a good idea to add a section in troubleshooting to double-check existing GPO and Local GPO settings to ensure they aren’t set too strict which would prevent clients from becoming peers. For instance, if the minimum disk drive size is set too large, devices may not become peers. Does this answer your question?

Thanks,

Joe Lentz
IT Infrastructure Engineer
Corporate Workstation Engineering
