### ISSUE TITLE
Service Surface Brightness Control failed to start

### ISSUE THREAD

**Issue by Klausoleum** [MicrosoftDocs/windows-itpro-docs#5727]
I tried to install SurfaceBrightnessControl. 
Unfortunately, the service could not be started during the installation. 

`Service Microsoft Surface Brightness Service failed to start. Verify that you have sufficient privileges to start system services.`

Hardware: Surface Pro 7
Windows 10 Pro Version 1909 Build 18363.535

The installation is new and no other programs have been installed yet.
Windows 10 download from MS using the Media Creation Tool.

What's the problem and why couldn't the service be started on my Surface?
![Surface Brightness Control priviileges](https://user-images.githubusercontent.com/36627883/71291216-3a534100-2372-11ea-810a-dfb552898519.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ac6c100-6e19-4cf6-2fd1-558a6751cc5d
* Version Independent ID: eec13586-5975-9ada-ec0f-9f53654eb73b
* Content: [Surface Brightness Control - Surface](https://docs.microsoft.com/en-us/surface/microsoft-surface-brightness-control#feedback)
* Content Source: [devices/surface/microsoft-surface-brightness-control.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/microsoft-surface-brightness-control.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment]
@Klausoleum . Before  installing the application,  make sure you should take ownership of the file. Install the application with adminstration right..
method 1.
installing the application by setup.exe or setup.msi

method 2.
by using command script.

**Comment by Klausoleum** [comment]
my user is administrator and also the owner of the file

I tried to install via msiexec. same problem
![via msiexec Admin](https://user-images.githubusercontent.com/36627883/71305993-6656dc80-23db-11ea-9bf8-1284e4ca4175.JPG)

**Comment by RAJU2529** [comment]
@Klausoleum . I told you to  command prompt should be in administrator rights.
I seen your screenshot, you tried to install as normal user

**Comment by Klausoleum** [comment]
Why do you think I didn't have admin rights?

Please look at the title of the window
I had changed the path for simplicity.

But also with the standard path as shown in the next screenshot it does not work.

![SharedScreenshot](https://user-images.githubusercontent.com/36627883/71307692-336c1300-23f2-11ea-8db1-e3a74f011e7e.jpg)

**Comment by RAJU2529** [comment]
@Klausoleum . now I confirmed that you have problems. so below things
use sfc scannow
use dism  online cleanup 
use dism online restorehealth

**Comment by Klausoleum** [comment]
I tried. Attention spoiler: Didn't work 

Here chronologically my procedure:

![sfc scannow](https://user-images.githubusercontent.com/36627883/71308867-c496b600-2401-11ea-89a5-385f2880eb3d.JPG)
(the windows resource protection has found corrupted files and successfully repaired)

![dsim](https://user-images.githubusercontent.com/36627883/71308871-cc565a80-2401-11ea-9fa7-2c46e1bcc6cc.JPG)

and then retested:


![nach sfc](https://user-images.githubusercontent.com/36627883/71308879-e09a5780-2401-11ea-9fb6-498acecd3c12.JPG)

**Comment by RAJU2529** [comment]
go to services.msc  see  servicebrightnessservice and make it startup type as automatic.
if you can't find. download windows all in one repair from majorgeeks.com
and then run, check restore  permission of Windows services

**Comment by Klausoleum** [comment]
I have had all in one repair repaired all 44 points in safe mode. 
The result of repairing permissions is the following: 

`ERROR: Writing SD to <machine\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Perflib\CurrentLanguage> failed with: Das Handle ist ungültig.

ERROR: Writing SD to <machine\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Perflib\009> failed with: Das Handle ist ungültig.

ERROR: Writing SD to <machine\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Perflib\CurrentLanguage> failed with: Das Handle ist ungültig.

ERROR: Writing SD to <machine\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Perflib\009> failed with: Das Handle ist ungültig.
`
_Das Handle ist ungültig = The handle is invalid.
[21.12.2019_22.10.13.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/3992248/21.12.2019_22.10.13.zip)
_

and unfortunately it still does not work

I have all log-FIles added as zip.

**Comment by RAJU2529** [comment]
@Klausoleum . windows all in one software is manufactured by tweaking.com is it ?

**Comment by Klausoleum** [comment]
Yes that is it

**Comment by RAJU2529** [comment]
i think some of the windows files are corrupted.
try to create a new user account as administrator right, then try to install the software

**Comment by Klausoleum** [comment]
I had already tried that. unfortunately it didn't :(
When I now reinstall windows, what should I pay special attention to?

Normally, the installation of brightness control should not be a problem on a surface, right?
I couldn't find any more information about problem at google

**Comment by RAJU2529** [comment]
first take  capture image  install.wim to  your pendrive or harddrive  uisng by  windows PE Aand  then try to reset the windows

**Comment by Klausoleum** [comment]
I'm totally frustrated before Christmas :(

In the meantime, I have now reinstalled Windows komolett with USB stick and deletion of all partitions.

I only installed the driver package for Surface

Unfortunately, it is still not possible to install the "Surface Brightness Control". 

Is there another way to set the time when inactive until the screen gets darker?
And then the time until the BIldschirm then switches off?

**Comment by RAJU2529** [comment]
@Klausoleum . sorry I don't have earlier version. if am using  surface pro then I would have been given solutions

**Comment by jvsam** [comment]
We're sorry to hear that you're still having problems @Klausoleum, hopefully, you'll be able to resolve it soon. Please note that you can always contact [Windows 10 Support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) for assistance. You can also explore the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can collaborate and discuss any issues or concerns with the community (*and post questions, if you want*). Kindly keep us informed if you find any relevant information that can be incorporated into this documentation.

@RAJU2529, as always, thank you very much for your contributions to the community. Please continue helping other users. 

**NOTE:** This GitHub-based documentation feedback system is intended to help improve the quality of the technical documentation of Microsoft Docs. If you have feedback, suggestions related to this documentation, or ideas to make it better for users, you can open an issue on a specific content page by using the feedback feature so it can easily be tracked.
