### ISSUE TITLE
Hotfix link missing and a clarification

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [MicrosoftDocs/windows-itpro-docs#5732]
Please include the hotfix link in this article:
https://support.microsoft.com/en-us/help/3127165/hotfix-package-1-for-microsoft-advanced-group-policy-management-4-0-sp

Also, it may be nice to note that although the hotfix package is labeled as "AGPM4.0SP1_Server_X64_KB4014009", it is indeed the correct package for the hotfixing of AGPM SP3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 467f971b-4c7b-b940-2f20-04d429bf0a6f
* Version Independent ID: 5ca4821a-dbef-9921-15b7-58948e5e0168
* Content: [Troubleshooting AGPM Upgrades - Microsoft Desktop Optimization Pack](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/agpm/troubleshooting-agpm40-upgrades#feedback)
* Content Source: [mdop/agpm/troubleshooting-agpm40-upgrades.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/mdop/agpm/troubleshooting-agpm40-upgrades.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
do you think that update should be installed. do you have own experience

**Comment by FMCUSystemAdmins** [comment]
Yes, the hotfix package that is labeled as “SP1” installed successfully and did fix the issue when AGPM SP3 was already installed.

**Comment by RAJU2529** [comment]
@illfated @jvsam , please review the changes , if you think links are essential and needed then only approve it , make changes as you like .
Thanking you

**Comment by FMCUSystemAdmins** [comment]
Something I just discovered.

After applying the hotfix package, the next time I went to attempt to check in a controlled GPO, I was met with an error: Unable to cast object of type 'System.DBNull' to type 'Microsoft.Agpm.GroupPolicy.Interop.GPMBackup'

The fix I found was to grant the AGPM service account Full Control on the AGPM archive located at “C:\ProgramData\Microsoft\AGPM”. After this, I was able to check in controlled GPOs again.

Before
[cid:image002.png@01D5B80A.8AAF5DB0]

After
[cid:image001.png@01D5B80A.F70C9B80]

**Comment by illfated** [comment]
Thanks for your PR #5735, I hope my suggestions will be useful.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @FMCUSystemAdmins, thank you again for sharing your valuable feedback. We will now close this issue since the document has been updated. Please continue to send your suggestions to help improve the quality of the technical documentation of Microsoft Docs. Thank you for being part of the community!

Thank you @RAJU2529 for creating the PR!

**Comment by jvsam** [comment]
@officedocsbot close
