### ISSUE TITLE
Discovery.svc is not working as mentioned

### ISSUE THREAD

**Issue by MrJunaidShahid** [MicrosoftDocs/windows-itpro-docs#5736]
Hi, 
I'm trying to implement MDE, as stated in the document I have created the Discover URI and added in On-premises MDM Discovery. When I try to add Azure AD User of On-premises MDM its returning:

aadsts50001 

https://enterpriseenrollment.{domain}.com/EnrollmentServer/Discovery.svc

I'm trying to resolve this can you guide me what actually missing?
because I'm not getting GET request in the URL.

![image](https://user-images.githubusercontent.com/34840914/71313929-1ff89080-2462-11ea-9a15-c3b5a4b16665.png)

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @MrJunaidShahid our apologies for the inconvenience. We would love to help you with your concern, however, this GitHub-based documentation feedback system is intended to help improve the quality of the technical documentation of Microsoft Docs. What we recommend is to open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance. There are also other support resources that you can explore like the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can post your question and get help from the community. 

If you do have concerns about the accuracy of the technical documentation of Microsoft Docs, please let us know. Thank you.
