### ISSUE TITLE
screensaver active requirement

### ISSUE THREAD

**Issue by jmjust** [MicrosoftDocs/windows-itpro-docs#5737]
The article says "...then the user’s session locks by invoking the screen saver (screen saver should be active on the destination machine)."  If having the screensaver active is a requirement for the Interactive logon: Machine inactivity limit to work, then you should include instructions on how to make the screensaver active using GPO. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75ab75c2-3bfd-bde6-8341-65ba79e9fe65
* Version Independent ID: 7224910c-ac05-26b2-f712-9a5993432615
* Content: [Interactive logon Machine inactivity limit (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @jmjust, thank you for bringing this to our attention. I will forward your suggestion to the Windows content writing team for review. We always strive to improve the quality of the technical documentation of Microsoft Docs so your feedback is appreciated!

**Comment by e0i** [comment]
@jmjust 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
