### ISSUE TITLE
Miracast device discovery

### ISSUE THREAD

**Issue by bochun317** [MicrosoftDocs/windows-itpro-docs#5739]
In MS-MICE, it indicates the Miracast over Infrastructure session start with P2P device discovery.
Is it possible that Win10 laptop discover the other Miracast device only by DNS/mDNS (without P2P device discovery)?
[Use case]
User Miracast Win10 laptop to TV. (Laptop & TV are in the local LAN, laptop connect to LAN by wifi, and TV connect to LAN by ethernet)

**Comment by mypil** [comment]
@bochun317 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by bochun317** [comment]
@mypil Thanks for your response.
MS-MICE P24
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-mice/9598ca72-d937-466c-95f6-70401bb10bdb?redirectedfrom=MSDN

**Comment by mypil** [comment]
@bochun317 - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by bochun317** [comment]
How to open a service ticket for Windows 10 products?

**Comment by mypil** [comment]
@bochun317 - Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/hub/4338813/windows-help?os=windows-10**

Hope this helps.
