### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by HjoshM** [MicrosoftDocs/windows-itpro-docs#5742]
Press and for hold 5s  =&gt;  Press and hold for 5s

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa9cc734-aea5-0908-39a0-ebe924a6ae74
* Version Independent ID: 0f900a81-0196-e3f1-d64b-2cd8aaf45c1e
* Content: [Prepare a new HoloLens 2](https://docs.microsoft.com/en-us/hololens/hololens2-setup#feedback)
* Content Source: [devices/hololens/hololens2-setup.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/hololens2-setup.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mypil** [comment]
@HjoshM - PR #5743 has been created to fix and close this issue once the PR is merged.

Thank you and we appreciate your contribution to make the docs better!

**Comment by RAJU2529** [comment]
@mypil. Great Job
