### ISSUE TITLE
added extra registry keys

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#5745]
created PR #5744

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af0ec4a3-6f79-33d7-adab-0000742fc992
* Version Independent ID: db89d5e2-f49f-bf65-f583-a9545e6fe0bb
* Content: [Security identifiers (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/security-identifiers)
* Content Source: [windows/security/identity-protection/access-control/security-identifiers.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/access-control/security-identifiers.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@RAJU2529 - Thank you for submitting feedback and for creating the PR to resolve this issue.

The PR is now merged so we will close this issue. 

We appreciate your help in making the docs better.  Keep it coming!
