### ISSUE TITLE
Bitlocker Full Disk Encryption vs. Used Space Only

### ISSUE THREAD

**Issue by lXbalanque** [MicrosoftDocs/windows-itpro-docs#5755]
I've asked this question on another page but feel like the information is pertinent. While the information here is good, it needs to be expanded on at length. I have a need to force Full Disk Encryption and this page only details the encryption method. Is there a way to force the policy to use full disk encryption? I want to have the machine enable full disk encryption during the autopilot process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93249da9-5a31-9936-9339-3d41126b2cb3
* Version Independent ID: f5ea9ba0-51f9-fff0-cefc-57f36b862039
* Content: [Policy CSP - Bitlocker - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-bitlocker)
* Content Source: [windows/client-management/mdm/policy-csp-bitlocker.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-bitlocker.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
>... I have a need to force Full Disk Encryption and this page only details the encryption method. Is there a way to force the policy to use full disk encryption? 

Thank you for your question @lXbalanque.

Hi @ManikaDhiman is this something that you can help with? Thank you so much. 

@officedocsbot assign @ManikaDhiman

**Comment by jvsam** [comment]
@officedocsbot assign @ManikaDhiman

**Comment by illfated** [comment]
(Ref. #5754 )

**Comment by ManikaDhiman** [comment]
Hi @jvsam, Here's the response I received from the product team: Full disk encryption is not available in autopilot scenarios. The reason is that autopilot deployment should be quick and easy and thus requires used-space encryption.

Hope this helps! Thanks!

**Comment by illfated** [comment]
@denisebmsft : Would you like to remind us of the current status of **jvsam** with regards to the Microsoft repositories?

**Comment by illfated** [comment]
@lXbalanque : I hope the comment above my last 2 ones is of help to you. Feel free to close this issue ticket if your question has been answered.

**Comment by illfated** [comment]
(Ref. #5707 )

**Comment by mypil** [comment]
@lXbalanque - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by ManikaDhiman so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
