### ISSUE TITLE
Device Guard missing at "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows"

### ISSUE THREAD

**Issue by MRZ0123** [MicrosoftDocs/windows-itpro-docs#5757]
|GER|
Ich würde gerne eine VM mit VMware auf meinem PC laufen lassen. Allerdings scheitere ich daran, den Device Guard zu deaktivieren, da ich bei Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows keinen Device Guard finde.
Ich bin für alle Vorschläge offen, vielen Dank schon mal im Vorraus!

|ENG|
I would like to have a VM running on my PC (with VMware). I failed on editing a few registry-values  because I couln't find Device Guard in regedit at Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows

![no Guard](https://user-images.githubusercontent.com/40590467/71544940-64fe5480-2985-11ea-8e37-d568bb69e403.png)

 I appreciate your help!

**Comment by RAJU2529** [comment]
@MRZ0123 . if you modified the device gaurd policy by using gpedit.msc  application and then only device guard is visible in registry

**Comment by MRZ0123** [comment]
So... should i change it to 0?
![reg key](https://user-images.githubusercontent.com/40590467/71557580-50cf5b80-2a48-11ea-907e-b8ad93a60fa1.png)

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you @RAJU2529 for your assistance here, much appreciated!

@MRZ0123 Please note that you can always contact [Windows 10 Support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) if you require help, especially when troubleshooting. You can also explore the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can collaborate and discuss any issues or concerns with the community (*and post questions, if you want*). 

**NOTE:** This GitHub-based documentation feedback system is intended to help improve the quality of the technical documentation of Microsoft Docs. If you have feedback, suggestions or ideas to make the docs better for users, you can open an issue on a specific content page by using the feedback feature so it can easily be tracked. Thank you.

**Comment by illfated** [comment]
(just adding a more concise Registry Editor image for those who stumble upon this ticket later)

![image](https://user-images.githubusercontent.com/38162891/71565998-1dc2b180-2ab4-11ea-8036-213486c650c6.png)

**Comment by RAJU2529** [comment]
@MRZ0123. I have own experiences. many applications do not work properly when the device guard is enabled.
for example Kaspersky total security will have limited functions when the Device guard is enabled.

Virtual machine not enable or not work if device guard

**Comment by MRZ0123** [comment]
Im sorry @jvsam , I'll do that next time if I've got another question!
And thank you for your help and patience!

**Comment by illfated** [comment]
@MRZ0123 : Thank you for your feedback regarding this issue.
Feel free to close this ticket if your questions are answered.
