### ISSUE TITLE
Confusing Create Profile for Trusted Cert (8.1 not 10)

### ISSUE THREAD

**Issue by D-Jeffrey** [MicrosoftDocs/windows-itpro-docs#5758]
Create and Assign a Trust Certificate - After saving the Cert, the platform type changes to 8.1 or later.  This is confusing after the fact when re-checking for configuration errors or steps missed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c175ce-52a4-8b46-716f-106b4d55106c
* Version Independent ID: 374a7e9d-6e4f-f188-328b-4ca2651a9481
* Content: [Configure Azure AD joined devices for On-premises Single-Sign On using Windows Hello for Business - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mypil** [comment]
@D-Jeffrey - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/789684e36383ec5f71b9529a96558f5b1bc0dc4e. 


Thank you for your contribution to make the docs better! Much appreciated!
