### ISSUE TITLE
How to Validate and test and troubleshoot

### ISSUE THREAD

**Issue by D-Jeffrey** [MicrosoftDocs/windows-itpro-docs#5760]
When these steps are completed, please include a link to what the functionality and experience should be.  Should we be able to access a on-prem service from a Azure Joined workstation and get a PIN prompt?  What happened when we get a message such as:

- "The Security System detected an authentication error for the server cifs/server.domain.local. The failure code from authentication protocol Kerberos was "The revocation status of the domain controller certificate used for authentication could not be determined. There is additional information in the system event log.
 (0xc000040c)".
- The client has failed to validate the domain controller certificate for Server.domain.local. The following error was returned from the certificate validation process: The revocation function was unable to check revocation because the revocation server was 
-The Distinguished Name in the subject field of your smart card logon certificate does not contain enough information to identify the appropriate domain on an non-domain joined computer. Contact your system administrator.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c175ce-52a4-8b46-716f-106b4d55106c
* Version Independent ID: 374a7e9d-6e4f-f188-328b-4ca2651a9481
* Content: [Configure Azure AD joined devices for On-premises Single-Sign On using Windows Hello for Business - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by D-Jeffrey** [comment]
Here is some Critical information which was not included in the explanation of how this works.  
All server connections need to made with a FQDN not the short name.
\\server\netlogon will not work.  \\server.domain.local\netlogon will work and you will get a Hello PIN prompt to complete this connection the first time which will cache for ??? minutes.

**Comment by VLG17** [comment]
@D-Jeffrey  i think [this article](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-authentication) provides a very detailed description of how it should look like after everything is configured. I'll add a note referencing it.

The 2 errors that you mentioned point in my opinion to an issue related to the CRL and how/if it's published. A few things to keep in mind:

> For Azure AD joined device to authenticate to and use on-premises resources, ensure you:

> Install the root certificate authority certificate for your organization in the user's trusted root certificate store.
> **Publish your certificate revocation list to a location that is available to Azure AD joined devices**, such as a web-based URL.

If you cannot find a solution for it, i advise [opening a support ticket to get it looked at and fixed](https://support.microsoft.com/en-us/contactus/). 

Related to the critical information about FQDN calls that is missing, where would you see that being added in the article? Thank you in advance for your feedback.

**Comment by D-Jeffrey** [comment]
I have solved the problem, it actual was caused or at least related to the FQDN issue (and I did not open a ticket, just banged by head trying stuff for several days).  Once I had that tiny bit of info it was magical.

Thanks for the very rich flow diagram, it is very meaty. (in a positive way)  It brings back memories of "TCP/IP Fundamentals for Microsoft Windows" - all 536 pages, I actually loved that, very helpful for explaining all the critical foundational components).    I guess it is implied within "Azure AD join authentication to Active Directory using a Key" with the micro-hint of Phase C that SAN matches the domain (which means we need to include a domain with the server name).   The challenge with that thought process is, that for most small-midsize businesses, we have been using non-FQDN (short names) for 20 years and we hate using the non-routable domain name (such as .company.local).   Additionally, when we hit an error, we Bing for an answer using an error code (and unhelpful social. answers appear).   Kerberos continue to be a place we need additional knowledge to understand how to troubleshoot and resolve issues on.  klist docs page could be more rounded to explained it as a tool for troubleshooting RC4 vs AES security improvements or other authentication issues.  But we as IT don't know how to use it for our smaller shops.

This does raise a question, if my DHCP packet had 015 Domain Name attribute, would that be used with the short name to determine the FQDN.  I assume not, since I have that set already.

For the FQDN, I would expect to see the within the How it Works, near the end of the 3rd paragraph or within the numbered point below that paragraph.

**Comment by VLG17** [comment]
@D-Jeffrey thank you for taking the time to provide all these insights. It's nice to be able to understand the background of these questions and one's way of thinking about these things.

Regarding your question, from my understanding, RFC 2132 015 tells us that we'll resolve the host name (not FQDN). I have to admin i'm no expert on this...

I'll add the part related to the FQDN in the article, where you mentioned.

**Comment by D-Jeffrey** [comment]
Wow, I not sure I remember all this content here.  Thanks for adding all the other context.  I would suggest one more step which is showing that users can access `\\server.domain.local\sharename`

We can close.

**Comment by mypil** [comment]
@D-Jeffrey - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/373d60fde6dce38ae41b37a60dc9ddebb61b4079. 


Thank you for your contribution to make the docs better! Much appreciated!
