### ISSUE TITLE
Fantastic Summary

### ISSUE THREAD

**Issue by jsraethe** [MicrosoftDocs/windows-itpro-docs#5763]
I am coming back to Linux after a long-hiatus and, wouldn't you know, I corrupted Windows 10 MBR attempting to establish dual-boot options. While I am just starting the process above, the clarity and style of this page is fantastic. 

Thank you for your contribution. If you are a volunteer contributor, you should get paid. If you are doing this for money, you should get paid more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc264df-cbd1-ac1f-3926-841fcab7dc31
* Version Independent ID: 67c2aea4-0d28-3d8e-e935-8af05291c94e
* Content: [Advanced troubleshooting for Windows boot problems - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/advanced-troubleshooting-boot-problems#feedback)
* Content Source: [windows/client-management/advanced-troubleshooting-boot-problems.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/advanced-troubleshooting-boot-problems.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Thank you for the nice words. Well stated. I can only speak for myself when I say "I almost exclusively contribute to use my OCD-like tendency for a good cause, to try to get spelling typos and grammar errors resolved". I can only assume that those who actually contributed with technical content are either Microsoft employees or at least are a lot more involved in the technical content than me.

**Comment by RAJU2529** [comment]
@jsraethe. Thanks for your feedback. All contributors have  well experienced with practical knowledge. At first they will test on their machines, once they  gets confirmations , then only they will publish.
If you have any suggestions to improve this article, you can contribute

**Comment by mypil** [comment]
@jsraethe - Thank you for your wonderful commendation. 

We really appreciate your feedback and the MS docs team will strive hard to consistently provide great documentation.
