### ISSUE TITLE
0x800980046

### ISSUE THREAD

**Issue by TaxLee** [MicrosoftDocs/windows-itpro-docs#5769]
Hi, there

I forget my PIN and try to find it. But I see this after verifying my identity.

Error code: 0x800980046
ID: 20b1fb0a-b64e-0007-5d1a-b3204eb6d501
Time: 2019-12-30T15:40:55.592Z

Could you please help me to solve this problem?

Thank you very much in advance.

Best,

Lee

**Comment by RAJU2529** [comment]
@TaxLee. which  PIN you forgotted 
windows login PIN or
GitHub login PIN

**Comment by TaxLee** [comment]
> @TaxLee. which PIN you forgotted
> windows login PIN or
> GitHub login PIN

windows login PIN

**Comment by RAJU2529** [comment]
@TaxLee. login using your email and password. moreover this site only for documentation purposes.
So you  came to the wrong place, post your  questions  in answers.microsoft.com

techcommunity.microsoft.com

**Comment by mypil** [comment]
@TaxLee - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  https://support.microsoft.com/hub/4338813/windows-help?os=windows-10

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
