### ISSUE TITLE
WDAC and AppLocker deep example

### ISSUE THREAD

**Issue by SergioCalderonR** [MicrosoftDocs/windows-itpro-docs#577]
There is not a doc that shows how to configure WDAC and AppLocker side-by-side, and that's a really nice scenario. Please share some content about it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19c8d2d2-3d96-c635-76da-c3b43afc1b45
* Version Independent ID: d7d79add-eadc-2e11-4bf7-eac48e4975d8
* Content: [Introduction to Windows Defender Device Guard - virtualization-based security and code integrity policies (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/introduction-to-device-guard-virtualization-based-security-and-windows-defender-application-control#windows-defender-device-guard-with-applocker)
* Content Source: [windows/security/threat-protection/device-guard/introduction-to-device-guard-virtualization-based-security-and-windows-defender-application-control.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/device-guard/introduction-to-device-guard-virtualization-based-security-and-windows-defender-application-control.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@SergioCalderonR Thanks for the suggestion. We are working on doc revisions for WDAC now and will ask our engineering partners to help with prioritizing this.

**Comment by hereCOMESlappy** [comment]
Did this ever happen? Also I can't find any docunetation whatsoever that shows how to enable managed installers using AppLocker CSP.
