### ISSUE TITLE
-2016281112 (Remediation failed) Error Code: 0x87d1fde8

### ISSUE THREAD

**Issue by felixcruz3** [MicrosoftDocs/windows-itpro-docs#5771]
Policy applies but State in Endpoint Manager reports -2016281112 (Remediation failed) Error Code: 0x87d1fde8. Endpoint is Windows 1909; Azure AD Joined via AutoPilot.

I have 2 OMA-URI Settings:

I. Account Type
   OMA-URI: ./Device/Vendor/MSFT/Accounts/Users/&lt;AccountName&gt;/LocalUserGroup
   Integer
   2

II. Account PWD
   ./Device/Vendor/MSFT/Accounts/Users/&lt;AccountName&gt;/Password
   String
  desired-password

Profile is targeting a isolated dynamic device group.

Additionally: Device configuration profile - Endpoint Protect policy is targeting All AutoPilot Devices [dynamic device group]. FYI; Local device security options &gt; Accounts [All set to block and renaming Admin and Guest]. Going to open an case, not sure what is conflicting as the syntax seems correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 309bae29-c769-5051-6c3f-aebeb455cd34
* Version Independent ID: bbdfad82-025e-8aee-b3fc-bcfb8b110674
* Content: [Accounts CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/accounts-csp#feedback)
* Content Source: [windows/client-management/mdm/accounts-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/accounts-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Have you looked for solutions on other pages by using search engines?
- https://www.bing.com/search?q=-2016281112+%28Remediation+failed%29+Error+Code%3A+0x87d1fde8&qs=n&form=QBLH&sp=-1&pq=-2016281112+%28remediation+failed%29+error+code%3A+0x87d1fde8&sc=0-55&sk=&cvid=6E85502F80AA40728A00468D012605C8
- https://www.google.com/search?q=-2016281112+(Remediation+failed)+Error+Code%3A+0x87d1fde8

**Comment by felixcruz3** [comment]
Yes, no luck. Under one of the closed submissions [https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1753] If I understand this correctly having the policy apply but not reporting correctly is expected behavior due to the operation Add vs Get. That's sad. I guess I would have to use powershell or a 3rd party PAM to manage a local admin password. I'd rather not even implement one just a requirement for End User Support team and their remote tool LogMeIn Restart Applet as System Service. I'll see if simply adding them in AAD Devices - Device settings is feasible and look into Intune Remote Assistance with TeamViewer. Thanks.

**Comment by illfated** [comment]
Fair enough. Unfortunately, there is no guarantee that this ticket will result in the solution you are looking for, unless it is directly related to any necessary updates in the documentation article. We will have to wait and see what the other users and MS Docs team will suggest to you. Wishing you the best of luck and a prosperous new year. 😃

**Comment by mypil** [comment]
@felixcruz3 Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products: https://support.microsoft.com/hub/4338813/windows-help?os=windows-10

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
