### ISSUE TITLE
Connect-MSGraph no longer accepts the -user parameter

### ISSUE THREAD

**Issue by gaknigge** [MicrosoftDocs/windows-itpro-docs#5772]
Please change the following line in this documentation page from:
Connect-MSGraph -user admin@M365x373186.onmicrosoft.com
to:
Connect-MSGraph -ForceInteractive

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17bfe927-f7b7-608b-8537-5c2274ccdced
* Version Independent ID: 5dd9abca-92d9-fbb2-6796-d1f6b9ab3c8b
* Content: [Windows Autopilot for existing devices - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/existing-devices#feedback)
* Content Source: [windows/deployment/windows-autopilot/existing-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/existing-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
OK, so this is based on the recent changes from issue ticket #5443 (**Connect-AutopilotIntune' is not recognized**) and its related PRs #5765 (**Command Upgrade**) & #5768 (**Updated PowerShell command**).

I will wait for more feedback from the MS Docs team before I suggest the change in a new Pull Request.

**Comment by illfated** [comment]
BTW, would you be able to reference any site or external documentation for this change?
( I guess https://github.com/Microsoft/Intune-PowerShell-SDK/issues/6 is somewhat related.)

**Comment by gaknigge** [comment]
I haven't been able to find examples in Microsoft documentation in a search, but from the powershell prompt itself, if I do
Get-Help Connect-MSGraph
One can see that-user is no longer a valid parameter of the function. But using the example I gave, one is able to connect to the tenant successfully.
Regards, Gary

On Jan 1, 2020 2:43 PM, "Trond B. Krokli" <notifications@github.com> wrote:

BTW, would you be able to reference any site or external documentation for this change?
( I guess microsoft/Intune-PowerShell-SDK#6<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FIntune-PowerShell-SDK%2Fissues%2F6&data=02%7C01%7C%7Cfa6a403afd0145d105a708d78efb4483%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637135082137791249&sdata=IKbC1PAeQyQDn2oqRrVAu1sTIbLG1zSDk8vUM5fES40%3D&reserved=0> is somewhat related.)

**Comment by illfated** [comment]
I am trying to get hold of the output from `Get-Help Connect-MSGraph` , but all I have access to is Windows 10 Professional as a Windows Server 2016 Domain member. I can't seem to access that information, not even running PowerShell as an administrator. Would you mind posting the output from
```powershell
Get-Help Connect-MSGraph
```
in a new comment box, possibly using a code block like **```powershell** for syntax highlighting?

**Comment by get-itips** [comment]
Hello @gaknigge thanks for reporting, I created a pull request to update the article with a working Ps line.
More info [here](https://github.com/microsoft/Intune-PowerShell-SDK/blob/master/README.md)

**Comment by gaknigge** [comment]
Hi. Unfortunately I am on vacation away from my computer until the 13th. But if you put in the commands from earlier in the article, then the Get-Help command will work.
Gary

On Jan 1, 2020 10:51 PM, "Trond B. Krokli" <notifications@github.com> wrote:

I am trying to get hold of the output from Get-Help Connect-MSGraph , but all I have access to is Windows 10 Professional as a Windows Server 2016 Domain member. I can't seem to access that information, not even running PowerShell as an administrator. Would you mind posting the output from

Get-Help Connect-MSGraph

in a new comment box, possibly using a code block like ```powershell for syntax highlighting?

**Comment by mypil** [comment]
@gaknigge -  From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/6787778d9f0e4f0bf79b6542340a227f4486f972. 


Thank you for your contribution to make the docs better! Much appreciated!
