### ISSUE TITLE
Typo in command to enable Insider for macOS mdatp ver. >= 100.78.0

### ISSUE THREAD

**Issue by andrewpong** [MicrosoftDocs/windows-itpro-docs#5773]
The command to enable Insider for Microsoft Defender ATP for macOS is incorrect for mdatp versions &gt;= 100.78.0 — the only working command is now `mdatp --edr --early-preview true`.

The older command `mdatp --edr --earlypreview true` no longer works at all - is this a regression, or outdated documentation? The older command is still listed when running `mdatp --edr` under `deprecated options`, and @levinec's [comment](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5378#issuecomment-552580165) on #5378 sounds like the intention was for both to work until everyone updates to versions that include the newer syntax.

Am I misunderstanding the definition of deprecated? I thought it meant something that will be pulled in the future, but still works at the moment.

I hope this is useful — I don't use GitHub much, and I apologize in advance if I did anything incorrectly!

**Older command syntax is now unrecognised:**
```
❯ mdatp --edr --earlypreview true
unrecognised option '--earlypreview'
```

**Only the new command works:**
```
❯ mdatp --edr --early-preview true
Configuration updated successfully
```

**Unrecognized syntax still listed, albeit under deprecated:**
```
❯ mdatp --edr
EDR option categories:

--edr options:
  --groupids arg             Configure group Ids for the device
  --early-preview arg        Enable/disable EDR early preview
  --set-tag tag name, value  Set device tags, specify the tag name and its
                             desired value, Current supported tags:Group -
                             allows to set machine tag (reflected in the
                             portal)
  --remove-tag arg           Remove device tag, specify the tag to remove

--edr deprecated options:
  --earlyPreview arg         Enable/disable EDR early preview
```

**After enabling Insider:**
```
❯ mdatp --health
cloudAutomaticSampleSubmission          : true
cloudDiagnosticEnabled                  : true
cloudEnabled                            : true
definitionsUpdated                      : "1577820288793"
definitionsUpdatedMinutesAgo            : 29
definitionsVersion                      : 79319
edrDeviceTags                           : []
edrEarlyPreviewEnabled                  : "enabled"
edrMachineId                            : "000000000000000000000000000000000000000"
healthy                                 : true
licensed                                : true
logLevel                                : "info"
machineGuid                             : "00000000-0000-0000-0000-000000000000"
orgId                                   : "00000000-0000-0000-0000-000000000000"
realTimeProtectionAvailable             : true
realTimeProtectionEnabled               : true
releaseRing                             : "InsiderFast"
versionEngine                           : "100.80.42"
```

**Related issues/PRs re. this I checked before submitting this:**

- Command shown is incorrect #5368
- Update endpoint-detection-response-mac-preview.md #5369
- Corrected the command line flag #5378
- EDR command syntax #5402
- fix typo #5473
- fix typo #5474
- typo in manual execution #5507 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c91a5cfb-d32d-3864-c1d5-aec39558f66f
* Version Independent ID: dbd2647e-88a6-ff22-4eab-ef628ac2e605
* Content: [Enable Microsoft Defender ATP Insider Machine - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/endpoint-detection-response-mac-preview#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/endpoint-detection-response-mac-preview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/endpoint-detection-response-mac-preview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Well documented ticket, thank you for basing your issue ticket on existing information. 👍

**Comment by MaratMussabekov** [comment]
Thank you @andrewpong, please have a look at #5797

**Comment by levinec** [comment]
I don't know how that dash between early and preview got removed, approved the pull request to add it back in!
