### ISSUE TITLE
How this interacts with Windows Update for Business

### ISSUE THREAD

**Issue by loosus456** [MicrosoftDocs/windows-itpro-docs#5776]
How does the "Specify deadlines for automatic updates and restarts" policy (the policy introduced in 1903) interact with Windows Update for Business deferral policies?

Example: let's say that a feature update is released January 1. You have set a WUfB deferral policy of 180 days for feature updates. You have set an update deadline of 30 days for feature updates (which is the max).

In this example, what would be the earliest dates and the latest dates that the feature update would be installed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44aabe97-360e-0655-09ec-5d1e352bdb1a
* Version Independent ID: 1c729c42-741d-ecb7-6490-a4bfdd029263
* Content: [Enforce compliance deadlines with policies in Windows Update for Business (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/wufb-compliancedeadlines#feedback)
* Content Source: [windows/deployment/update/wufb-compliancedeadlines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/wufb-compliancedeadlines.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by loosus456** [comment]
Was anyone ever able to figure out how these two policies interact?

**Comment by sdxfuj** [comment]
My tests show that it's 180 days + uour update deadline. I haven't been able to verify that it actually looks at publication dates at all in the WUFB scenario. It seems to start the countdown after installation/pending reboot. We have both GPO's set in order to enforce deadlines for pre-1903 machines as well. Would be great if someone else could test this as well.

**Comment by e0i** [comment]
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
