### ISSUE TITLE
Grouping devices in AutoPilot deployment groups

### ISSUE THREAD

**Issue by koeneijken** [MicrosoftDocs/windows-itpro-docs#578]
We have multiple logical groups of Corporate owned devices, I want to assign specific policies and content to a an azure dynamic group of devices that was enrolled using a specific AutoPilot deployment profile. A Dynamic group in Azure only allows to query the deployment profile that works for Apple Devices, please make it work for Windows devices as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc947476-4fc3-cbb1-26c2-1e7dedb7892f
* Version Independent ID: 16bf5a1f-00d8-ad55-f66f-a9a38f115bb6
* Content: [Manage Windows device deployment with Windows AutoPilot Deployment](https://docs.microsoft.com/en-us/microsoft-store/add-profile-to-devices)
* Content Source: [store-for-business/add-profile-to-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/add-profile-to-devices.md)
* Service: **unspecified**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by shortpatti** [comment]
@TrudyHa -- Can you take a look at this issue?

**Comment by mypil** [comment]
@koeneijken - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
