### ISSUE TITLE
Incorrect info

### ISSUE THREAD

**Issue by NancyFolsom** [MicrosoftDocs/windows-itpro-docs#5781]
There is no "Scan history" label anywhere. There is a Threat History, but it don't show a history of scans and the results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84b48087-97c2-e6c2-2080-e5fcdb662268
* Version Independent ID: 6f1caca8-c986-7364-bd2c-7975c9509ff6
* Content: [Review the results of Windows Defender AV scans - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/review-scan-results-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/review-scan-results-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/review-scan-results-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by e0i** [comment]
Hello, @NancyFolsom 

Sending the article for cross-checks. Thank you for bringing the issue to attention.

**Comment by e0i** [comment]
@NancyFolsom The associated PR #5982 for this issue has been merged and the content has been updated. Thank you for providing feeedback.
