### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#5783]
I consider removing broken link of 
Enable Controlled Folder  Access.
and adding Microsoft support link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcbd9d0e-c614-6a48-e70d-4daedcb9a670
* Version Independent ID: e2c5a8e5-9beb-6e3f-a566-6b134dd1885f
* Content: [Configure local overrides for Windows Defender AV settings - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-local-policy-overrides-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-local-policy-overrides-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/configure-local-policy-overrides-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@illfated. today afternoon i will create new PR

**Comment by RAJU2529** [comment]
@illfated. Please review the changes in PR #5785

**Comment by mypil** [comment]
@RAJU2529 - Thank you for submitting feedback and for creating the PR #5785.

I will get the author to review the PR for their approval in merging. 

Your contribution to help improve the docs is greatly appreciated! Keep it coming!

Happy New Year!

**Comment by mypil** [comment]
@RAJU2529 - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/c6fc803ec4d8a52b35f6ce8c353ace5d1a8f661f. 


Thank you for your contribution to make the docs better! Much appreciated!
