### ISSUE TITLE
Blue Screen Enabling DG/CG with DG Readiness Tool

### ISSUE THREAD

**Issue by ourichermath** [MicrosoftDocs/windows-itpro-docs#5787]
I recently tried re-enabling Device Guard (DG) and Credential Guard (CG) with the DG Readiness Tool located at:

https://www.microsoft.com/en-us/download/details.aspx?id=53337

and ended up with nothing but a constantly repeating blue screen of death (BSOD) after the reboot.  Several months ago, I'd used the same tool to disable DG/CG so I could run Ryzen Master (RM - which won't run with Virtualization Based Security (VBS) active).  Since I didn't need RM any more, I uninstalled it and ran  through the DG/CG enabling process without issue until the final reboot:

1) I used the Ready flag:
DG_Readiness_Tool_v3.6.ps1 -Ready

2) then the Capable flag:
.\DG_Readiness_Tool_v3.6.ps1 -Capable

3) followed by a reboot/rerun, and then the Enable flag:
.\DG_Readiness_Tool_v3.6.ps1 -Enable

Besides some yellow text with the Capable flag stating:

"The following additional qualifications, if present, can enhance the security of Device Guard / Credential Guard on this system:
HSTI is absent
NX Protector is absent
SMM Mitigation is absent"

there were no issues prior to that final reboot.  After the Enable reboot, the machine repeatedly gave me that BSOD, tried to automatically repair it, couldn't, and gave me the option to use a restore point.  Multiple attempts to reboot got the same thing.  I finally used the restore point (which, from the time stamp this process created on its own (thank you for that, otherwise I'd have been in a world of hurt)) and got back up and running.  Since I remember the Disable process asking to turn something off in the BIOS, I'll add that I never got a prompt to turn anything back on in the BIOS with the Enable process.

I don't know what else to give you since the logs confirm everything was supposedly fine.  Two side notes, though:  1) even though I was running version 3.6 (which is apparent from the command lines), everything on screen and in the logs said version 3.4, and 2) the instructions say the command should look like DG_Readiness.ps1 -[Capable/Ready/Enable/Disable] (i.e., no initial ".\" and no trailing version number.

Sorry if this isn't the place to report this problem.

**Comment by RAJU2529** [comment]
some device drivers are not compatible with device guard. so thats why you getting blue sceen of death.
disable the driver verification.
and I suspect the AMD some processor models are not compatible with HVSI and DG and CG

**Comment by RAJU2529** [comment]
@ourichermath  After reading your post, I tried on my laptop with intel i5  7200U processor with windows 10 enterprise  1909 build no 18363.535.

i  tried your said commands on PowerShell , and then I restarted, no blue screen of death, Laptop running fine.

here is the proof.


![upload1](https://user-images.githubusercontent.com/3296790/71735446-78715a00-2e74-11ea-9d23-c00c4e0ea9d6.JPG)

![upload2](https://user-images.githubusercontent.com/3296790/71735465-80c99500-2e74-11ea-8b42-a6d49af7df86.JPG)

![upload3](https://user-images.githubusercontent.com/3296790/71735474-8921d000-2e74-11ea-9557-692e0d6bd6e5.JPG)

![upload4](https://user-images.githubusercontent.com/3296790/71735643-fa618300-2e74-11ea-9d69-f0efb2adedf8.JPG)

![upload5](https://user-images.githubusercontent.com/3296790/71735653-00576400-2e75-11ea-88ba-345548e9772b.JPG)


![upload6](https://user-images.githubusercontent.com/3296790/71735669-0baa8f80-2e75-11ea-9aeb-6bc910364aae.JPG)

**Comment by RAJU2529** [comment]
@illfated . I configured the Windows 10 OS with available hardware, This configuration is enough or not. I need  your  advice

**Comment by ourichermath** [comment]
Whatever the problem is on my system, I don't think it's with the drivers.  According to what I can see in the log, it checked all of them in the "-Capable" phase and they're all good.  Here's the summary information from that phase of the logs:

`Completed scan. List of Compatible Modules can be found at C:\DGLogs\DeviceGuardCheckLog.txt
No Incompatible Drivers found
 ====================== Step 2 Secure boot present ====================== 
True
Secure Boot is present
Executing: REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard\Capabilities\" /v "SecureBoot" /t REG_DWORD /d 2 /f 
Output: The operation completed successfully.


 ====================== Step 3 MS UEFI HSTI tests ====================== 
Copying HSTITest.dll

Kernel32::LoadLibrary   64bit --> 0x00007FFF9DC80000
HstiTest2::QueryHSTIdetails  64bit --> 0x00007FFF9DC81120
HSTI Duple Count: 0
HSTI Blob size: 0
String: 
HSTIStatus: False
HSTI is absent
 ====================== Step 4 OS Architecture ====================== 
64-bit
64 bit arch.....
 ====================== Step 5 Supported OS SKU ====================== 
OSNAME:microsoft windows 10 pro|c:\windows|\device\harddisk0\partition4
Role=0
Standalone Workstation
This PC edition is Supported for DeviceGuard
Executing: REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard\Capabilities\" /v "OSSKU" /t REG_DWORD /d 2 /f 
Output: The operation completed successfully.


 ====================== Step 6 Virtualization Firmware ====================== 
VMMonitorModeExtensions True
VirtualizationFirmwareEnabled True
HyperVisorPresent False
Virtualization firmware check passed
Executing: REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard\Capabilities\" /v "Virtualization" /t REG_DWORD /d 2 /f 
Output: The operation completed successfully.


 ====================== Step 7 TPM version ====================== 
TPM 2.0 is present.
Executing: REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard\Capabilities\" /v "TPM" /t REG_DWORD /d 2 /f 
Output: The operation completed successfully.


 ====================== Step 8 Secure MOR ====================== 
DG_obj 
DG_obj.AvailableSecurityProperties.length .AvailableSecurityProperties.length
isSecureMOR= 1 
Secure MOR is available
Executing: REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard\Capabilities\" /v "SecureMOR" /t REG_DWORD /d 2 /f 
Output: The operation completed successfully.


 ====================== Step 9 NX Protector ====================== 
DG_obj 
DG_obj.AvailableSecurityProperties.length .AvailableSecurityProperties.length
isNXProtected= 0 
NX Protector is absent
Executing: REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard\Capabilities\" /v "UEFINX" /t REG_DWORD /d 0 /f 
Output: The operation completed successfully.


 ====================== Step 10 SMM Mitigation ====================== 
DG_obj 
DG_obj.AvailableSecurityProperties.length .AvailableSecurityProperties.length
isSMMMitigated= 0 
SMM Mitigation is absent
Executing: REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard\Capabilities\" /v "SMMProtections" /t REG_DWORD /d 0 /f 
Output: The operation completed successfully.


 ====================== End Check ====================== 
 ====================== Summary ====================== 
Device Guard / Credential Guard can be enabled on this machine.

The following additional qualifications, if present, can enhance the security of Device Guard / Credential Guard on this system:
HSTI is absent
NX Protector is absent
SMM Mitigation is absent

Executing: REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard\Capabilities\" /v "CG_Capable" /t REG_DWORD /d 1 /f 
Output: The operation completed successfully.


Executing: REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard\Capabilities\" /v "DG_Capable" /t REG_DWORD /d 1 /f 
Output: The operation completed successfully.


Executing: REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard\Capabilities\" /v "HVCI_Capable" /t REG_DWORD /d 1 /f 
Output: The operation completed successfully.`

I wish I'd kept the logs from when I Disabled DG/CG.  I'm almost positive both of them were on initially.  So, it seems odd that now they won't re-enable.  And, in case it's a hardware thing, here's my system:

`CPU:           AMD Ryzen 7 3700X (Matisse, MTS-B0)
               3600 MHz (36.00x100.0) @ 3518 MHz (35.25x99.8)
Motherboard:   ASUS ROG CROSSHAIR VIII HERO
BIOS:          1201, 11/18/2019
Chipset:       AMD X570 (Bixby)
Memory:        16384 MBytes @ 1597 MHz, 14-14-14-28
               - 8192 MB PC25600 DDR4 SDRAM - G Skill F4-3200C14-8GTZ
               - 8192 MB PC25600 DDR4 SDRAM - G Skill F4-3200C14-8GTZ
Graphics:      EVGA GTX 1080 FTW2 Gaming iCX (08G-P4-6686)
               NVIDIA GeForce GTX 1080, 8192 MB GDDR5X SDRAM
Drive:         Samsung SSD 970 EVO Plus 1TB, 976.8 GB, NVMe
Sound:         NVIDIA GP104 - High Definition Audio Controller
Sound:         AMD Starship/Matisse/Vermeer - HD Audio Controller
Network:       Intel I211AT Copper (Pearsonville) Network Adapter
OS:            Microsoft Windows 10 Professional (x64) Build 18363.535 (1909/November 2019 Update)`

**Comment by ourichermath** [comment]
According to your screenshots, you're running version 3.7.  I've only been able to find 3.6.  Where can I get 3.7?

**Comment by RAJU2529** [comment]
@ourichermath  here is version 3.7 

[DG_Readinessv3.7.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/4020040/DG_Readinessv3.7.zip)

**Comment by ourichermath** [comment]
I looked around the files area here and found:

https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/dg_readiness_tool.md

Since it says version 3.7 within that code, I'll assume it's the same as what you pointed to.  Do you have any idea why the newer version isn't available on the Microsoft download page I referenced in my first post?

**Comment by RAJU2529** [comment]
@ourichermath .uploading of new version 3.7 to Microsoft download center, the decision should be  be taken by Microsoft.

I am trying to solve the Bluescreen of death.  
use driver verifier tool and checks all drivers are signed and compatible with windows 10 1909.
**https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/driver-verifier**

Try to enable NX  feature  in BIOS

**Comment by ourichermath** [comment]
Well, that was an experience.  I ran the Driver Verifier, rebooted, signed in, and the computer kept rebooting (and I kept signing in).  Never got a report.  Didn't get an error or blue screen.  Just sign in and reboot.  I finally got back into the Verifier and had it delete the current settings.  That got me out of it.

I guess I'm done with this.  I'll just live with DG/CG being off until I get up the gumption to do another Fresh Start and have it turned on by default.  Thanks, anyway.

**Comment by illfated** [comment]
@RAJU2529 : Thank you for asking, but I have been too occupied in my daily work to find time to get involved in this scenario. I recommend asking the tech writing team to suggest what can be done with this issue.

**Comment by RAJU2529** [comment]
@ourichermath . I hope your issue has been solved by my  given ideas So you can close this issue if you agrees.

**Comment by ourichermath** [comment]
The people running this site can, of course, handle this however they want.  But, regardless of whether I got things working (which I did not), the DG Readiness Tool still went through its whole process without complaint and then ended up with the system in a BSOD loop.  So, the tool really needs to be checking for something else before saying the system is Ready or Capable.  Thus, I'd say this issue should not be closed.

**Comment by RAJU2529** [comment]
@ourichermath . But in my case  BSOD does  not occur

**Comment by illfated** [comment]
@RAJU2529 : I think we should let the MS Docs team decide if this discussion has provided useful suggestions for the documentation or if it should be brought to the attention of the developers.

**Comment by RAJU2529** [comment]
@illfated . So my side what should I do sir

**Comment by illfated** [comment]
I recommend to wait for more feedback from @mypil (Joyce Y.) and find out what will be the next step.

**Comment by RAJU2529** [comment]
@ourichermath . if still you getting after enabling Device guard with AMD processor, then you must post the queries in answers.microsoft.com and techcommunity.microsoft.com with Sharing  memory  dump files. In that forum windowws users will analyze the file

**Comment by mypil** [comment]
@ourichermath - Thank you for submitting feedback. 

Have you already tried to contact technical support to report this issue? If not, I think it would be best for you to open a service ticket so they can help troubleshoot and resolve your issue. 

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/hub/4338813/windows-help?os=windows-10**

However, if you see some doc errors, please share the doc link and provide more details on which portion of the doc needs to be edited.
