### ISSUE TITLE
Doesn't appear

### ISSUE THREAD

**Issue by LXSTLXVEE** [MicrosoftDocs/windows-itpro-docs#5788]
When I open Turn Windows features on or off the option for Windows Defender Application Guard does not appear

**Comment by mypil** [comment]
@LXSTLXVEE - We would like to get some details from you. Can you please share what specific issue you have and for which doc? Or are you having some technical issues which requires technical support?

Kindly provide the doc link so we can investigate. Thank you!

**Comment by RAJU2529** [comment]
@LXSTLXVEE . Windoes defender application guard requires at least Professional or Enterprises or Education editions of windows 10.

**Comment by mypil** [comment]
@LXSTLXVEE - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
