### ISSUE TITLE
MDATP Advanced Hunting DeviceAlertEvents table changes

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#5790]
AlertEvents table name was changed to DeviceAlertEvents.

Field names changed too:
- EventTime is now Timestamp
- MachineId is now DeviceId
- ComputerName is now DeviceName

Ref: https://techcommunity.microsoft.com/t5/microsoft-defender-atp/advanced-hunting-data-schema-changes/ba-p/1043914

Pretty much every page documenting an Advanced Hunting table needs updating according to the reference link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8a86cf-9d93-f9bd-85c5-fbcc25032c29
* Version Independent ID: 985ce505-ad68-4991-98c1-4c53e5fa89fb
* Content: [AlertEvents table in the Advanced hunting schema - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-alertevents-table)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-alertevents-table.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-alertevents-table.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by mypil** [comment]
@iadgovuser1 -  Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/RAJU2529/windows-itpro-docs/commit/688c5f429389f77a0dedf6a7ef14a9112006bc2d. 


Thank you for your contribution to make the docs better! Much appreciated!
