### ISSUE TITLE
enable network protection must be in main article

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#5793]
This article title says "protect your network" , so  Enable Network Protection and its description must be in the same article included in Main 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71064247-63c3-cb57-5f05-a1ea40b01d97
* Version Independent ID: 684863fb-0302-945d-d42e-ed35f5e6269d
* Content: [Use network protection to help prevent connections to bad sites - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/network-protection#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/network-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/network-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by e0i** [comment]
Hello, @RAJU2529

Would you please clarify your request? Which article are you referring to with "Main?" Thanks.

**Comment by RAJU2529** [comment]
@e0i . we should add about Enable Network protection in the main , comes after the title .
It should not contain in related topics

**Comment by illfated** [comment]
( ref. #5996 )

**Comment by e0i** [comment]
Closing via #5996
