### ISSUE TITLE
Password with no TPM

### ISSUE THREAD

**Issue by Rob190** [MicrosoftDocs/windows-itpro-docs#5794]
"Manage passwords and PINs" only covers the TPM case. How are passwords/PINs mananged if the PC doesn't have a TPM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29116f85-264f-d031-be7b-e32a1816cd28
* Version Independent ID: 640478e6-a367-4e47-a177-3a10dd006d1c
* Content: [Overview of BitLocker Device Encryption in Windows 10 - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10#feedback)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
If TPM does not in PC  means you can't able to enable bitlocker. 
I had own experience

**Comment by beerisgood** [comment]
> 
> 
> If TPM does not in PC means you can't able to enable bitlocker.
> I had own experience

That's wrong. It works without TPM and i do that on my Laptop.
See also https://blogs.technet.microsoft.com/hugofe/2010/10/29/bitlocker-without-tpm/

**Comment by RAJU2529** [comment]
@beerisgood. Thanks for the information, once i had TPM device driver is missing, so that time I could not able to enable BitLocker,  after reading the article link provided by you,i will  try  with another computer modifying by  via GPO

**Comment by e0i** [comment]
@Rob190 The issue has been noted for clarification. Thanks.

**Comment by VLG17** [comment]
@Rob190 the answer to your questions is in the article provided by @beerisgood (thanks for that).

https://docs.microsoft.com/en-us/archive/blogs/hugofe/bitlocker-without-tpm

In summary, because you don’t have a TPM, you must choose to either enter a password each time your PC boots, or provide a USB flash drive.

![bitlocker](https://user-images.githubusercontent.com/41186174/77346427-e5dbab00-6d3e-11ea-971b-f961d33cc716.png)

**Comment by e0i** [comment]
Closing via the above answer. Thank you all for participating.
