### ISSUE TITLE
command doesnot work

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#5795]
below command does not work in powershell 
Set-MpPreference -PUAProtection

correct commands are as follows 
Set-MpPreference -PUAProtection disable
Set-MpPreference -PUAProtection enable
Set-MpPreference -PUAProtection auditmode

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b27975a-fa49-d9cd-d500-792448c57f9e
* Version Independent ID: 21c3eb7b-065a-b68a-8a88-dfce45571b0d
* Content: [Block potentially unwanted applications with Windows Defender Antivirus - Windows security](https://docs.microsoft.com/en-gb/windows/security/threat-protection/windows-defender-antivirus/detect-block-potentially-unwanted-apps-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/detect-block-potentially-unwanted-apps-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/detect-block-potentially-unwanted-apps-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@illfated .Please review the changes of PR #5796

**Comment by illfated** [comment]
I presume these command parameters have been tested in their appropriate scenario, so my review is based on that presumption.

**Comment by e0i** [comment]
Closing the issue as the PR has been merged. Thank you for your continued engagement with the community, @RAJU2529. Much appreciated.
