### ISSUE TITLE
Reopen #5214

### ISSUE THREAD

**Issue by DennisGaida** [MicrosoftDocs/windows-itpro-docs#5798]
Issue #5214 was closed even though no action was taken for improving the documentation. #5214 states specific issues with existing and non-existing documentation that can be improved.

The request to reopen the issue is now almost 30 days old.

**Comment by mypil** [comment]
@DennisGaida - Thank you for submitting feedback.

Issue #5241 was closed as the issue reported was more of Product Support so the user was referred to open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** to contact technical support to get that issue fixed. 

We value collaboration and appreciate your efforts to clarify the docs. Could you please assist us by providing more details on how this content could be edited to incorporate your feedback? If you could suggest what the appropriate text and where it should be placed, I could assign one of our team members to create a Pull Request to get it added or you may also create a Pull Request to add in your suggestion and just link this issue so I can have the doc owner review and merge the content. 

Thank you.

**Comment by mypil** [comment]
@DennisGaida - Is it issue #5214 or #5241 that you wish to reopen? Please confirm. The issue subject and the content of your issue request are different.

**Comment by DennisGaida** [comment]
> 
> 
> @DennisGaida - Is it issue #5214 or #5241 that you wish to reopen? Please confirm. The issue subject and the content of your issue request are different.

Thanks for replying! I'm sorry I meant #5214 - I edited the original issue to state so.

**Comment by mypil** [comment]
@DennisGaida - Thanks for the confirmation. I will just close this issue and re-open issue #5214 since the details are found on the comments thread there.
