### ISSUE TITLE
Blog post link 

### ISSUE THREAD

**Issue by czrik** [MicrosoftDocs/windows-itpro-docs#5799]
The URL to Y0av's blogpost is dead. Looks like the article has been taken down

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69882e91-6bef-d524-7059-20ba67129f4e
* Version Independent ID: ee0f2eb3-97da-4306-5cd1-2b6ae1858ed9
* Content: [Configure Surface Hub Start menu - Surface Hub](https://docs.microsoft.com/en-us/surface-hub/surface-hub-start-menu#feedback)
* Content Source: [devices/surface-hub/surface-hub-start-menu.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/surface-hub-start-menu.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
I create PR to remove invalid link and I add a similar corresponding information link

**Comment by greg-lindsay** [comment]
The link will be deleted for now. A new blog link is pending.
