### ISSUE TITLE
API Reference for Recommendations

### ISSUE THREAD

**Issue by onpremcloudguy** [MicrosoftDocs/windows-itpro-docs#5804]
Hi can you please provide documentation for the Recommendations API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fa8feaf-4173-4c3e-e4bb-e43ff05445d0
* Version Independent ID: fcf8ffb0-ddb4-23bc-7f5d-a94970ab0d6d
* Content: [Supported Microsoft Defender Advanced Threat Protection APIs - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/exposed-apis-list#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/exposed-apis-list.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/exposed-apis-list.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by rockyknows** [comment]
No all information like 

Windows Defender   AV - Definitions out of date

are not available. I wish we can grab that from the API. is there a way?

**Comment by onpremcloudguy** [comment]
from what i can see the endpoints that are missing are: https://api.securitycenter.windows.com/api/recommendations and https://api.securitycenter.windows.com/api/aadusers 
A sample on how to use the mostprevilantuser on the computers form recommendations would be awesome too :)

**Comment by VLG17** [comment]
@onpremcloudguy All the APIs presented in the article you mentioned, including the Recommendation API are described in the underlying articles which you can see in the article tree:

![image](https://user-images.githubusercontent.com/41186174/74320527-7494f980-4d89-11ea-81f2-176e2e919b49.png).

Could you provide more info regarding "**_mostprevilantuser_** on the computers form recommendations"? I cannot find this within the API related articles.

**Comment by mypil** [comment]
@onpremcloudguy  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
