### ISSUE TITLE
So can a user use a PIN in Windows Hello for Business?

### ISSUE THREAD

**Issue by jwilleke** [MicrosoftDocs/windows-itpro-docs#5805]
The title at the top is "Windows Hello for Business"
Yet the article States: 
"_In Windows 10, Windows Hello for Business replaces passwords with strong two-factor authentication on PCs and mobile devices. This authentication consists of a new type of user credential that is tied to a device and uses a biometric or PIN._"

This implies Windows Hello for Business users CAN use a PIN.

Then Under the section 
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-overview#the-difference-between-windows-hello-and-windows-hello-for-business

- The difference between Windows Hello and Windows Hello for Business
Individuals can create a PIN or biometric gesture on their personal devices for convenient sign-in. This use of **Windows Hello** is unique to the device on which it is set up, but can use a simple password hash depending on an individual's account type. This configuration is referred to as Windows Hello convenience PIN and it is **not backed by asymmetric (public/private key) or certificate-based authentication**.

- Windows Hello for Business, which is configured by Group Policy or mobile device management (MDM) policy, always uses key-based or certificate-based authentication. This makes it much more secure than Windows Hello convenience PIN.

So first it says the "Windows Hello for Business" uses a PIN, but then it says:
"Individuals can create a PIN or biometric gesture ....is **not backed by asymmetric (public/private key) or certificate-based authentication**.

"Windows Hello for Business...always uses key-based or certificate-based authentication. This makes it much more secure than Windows Hello convenience PIN."

This implies Windows Hello for Business users **CAN NOT** use a PIN.

The two statements appear to be contradictory.
So can a user use a PIN in Windows Hello for Business?

Very confusing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f8d124-fd83-f3ab-8249-d11d5967460f
* Version Independent ID: eace54c8-04c9-a717-5ecd-2be8f485cc93
* Content: [Windows Hello for Business Overview (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-overview)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by RAJU2529** [comment]
@jwilleke  Last year i used  USB fingerprint device and  PIN  to used for windows 10 login process.

Sometimes i used  USB fingerprint   for windows 10 login 
Sometimes i used PIN for windows 10 login

So windows 10 for business  able to use  either  Fingerprint device or  PIN

**Comment by mapalko** [comment]
Windows Hello for Business users can use a PIN. The statement is supposed to be about the credential that the PIN is used to unlock. When using Windows Hello for Business, the PIN is always tied to a key based credential. There are certain configurations where a user can set up a PIN and biometric gestures, but they are tied to a password hash and not a key. This is scenario is referred to as convenience PIN and we do not consider it to be Windows Hello for Business. 

Allowing the creation of a convenience PIN on a domain joined device requires the admin set specific policy.

**Comment by mypil** [comment]
@jwilleke - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by mapalko so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
