### ISSUE TITLE
Status/DeviceEncryptionStatus What does the integer returned from device mean?

### ISSUE THREAD

**Issue by Pushparajkvp** [MicrosoftDocs/windows-itpro-docs#5807]
I assume there is a reasoning behind the code sent from the device, i get 514 for devices in which no drives have bitlocker turned on. Can anyone eloborate on what this code means?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a05802f-9d0f-9aeb-3c8e-8b92f1284202
* Version Independent ID: 1fd9efc2-8946-75e4-27f3-95ac43a9d987
* Content: [BitLocker CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp)
* Content Source: [windows/client-management/mdm/bitlocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/bitlocker-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@Pushparajkvp - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by illfated** [comment]
Based on the document content, I am thinking that this could be a compound value. Consider the following:
> **Note**
> When you enable EncryptionMethodByDriveType, you must specify values for all three drives (operating system, fixed data, and removable data), otherwise it will fail (**500 return status**). For example, if you only set the encryption method for the OS and removable drives, you will get a **500 return status**.

I have not figured out what the remaining value of 14 consists of, but I imagine it could contain 8+4+2 or other combinations of values. Would have been great to have a complete table for the hex values.
