### ISSUE TITLE
Unable to boot the Surface Data Eraser Tool on Surface Pro X

### ISSUE THREAD

**Issue by FabledDugong** [MicrosoftDocs/windows-itpro-docs#5809]
Hi everyone,
Please, I am trying to boot to the Microsoft Surface Data Eraser Tool (v3.28.137.0) from a flash drive connected to Surface Pro X (config: SQ1, 8GB, 256GB; SKU: KHL-00003) via USB-C to A dongle, but so far without success.

Both UEFI Alternate boot sequence and Boot from USB devices settings are enabled on the device. I also tried manually alter the boot sequence so that the USB storage is the first and only available option. Yet, I am unable to boot to the tool via the standard "Surface" way of holding the 'Volume Down' button and pressing the 'Power Button'.

The issue is definitely not with a faulty USB-C to A dongle or the flash drive, both tested on other devices.

The Surface Pro X is the only device from Surface Devices portfolio I encountered a problem with.

Any insights or solutions are welcome. Thank you very much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93a0e269-be9b-781a-b9b4-52b94e68618b
* Version Independent ID: 725c2d4a-5397-6c67-7605-93a8cd40cf08
* Content: [Microsoft Surface Data Eraser (Surface) - Surface](https://docs.microsoft.com/en-us/surface/microsoft-surface-data-eraser)
* Content Source: [devices/surface/microsoft-surface-data-eraser.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/microsoft-surface-data-eraser.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@FabledDugong . I don't have surface x or pro.  But as experienced with other people laptop's, so I give idea.
go to bios
disable secure boot  or
disable UEFI boot
save and exit ,  and go to bios
enable CSM 
save and exit and then go to bios
adjust the boot device as USB device first.
save and exit.

**Comment by FabledDugong** [comment]
Hi @RAJU2529 , thank you for your reply. Unfortunately the Surface Pro X UEFI does not have a Compatibility Support Module available. Anyway I tried disabling the Secure Boot, but it didn't resolve the problem.

**Comment by mypil** [comment]
@FabledDugong - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
