### ISSUE TITLE
"digits between 1 and 10"?

### ISSUE THREAD

**Issue by luis-castro** [MicrosoftDocs/windows-itpro-docs#5811]
I guess you meant "and then press any of the digits between 0 and 9" (in paragraph about "upper-row" symbols).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5128d9a-e02a-df9b-24cc-32711ad37b54
* Version Independent ID: fecafb19-6b37-1f2e-ba3d-5e0bf0d49d09
* Content: [Password must meet complexity requirements (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Funny how inconsistent that page is when it comes to phrasing a variation on "all the numbers from 0 to 9":
- Base 10 digits (0 through 9)
- [ ... ] and typing any of the digits from 1 through 10. (_this one is misleading, 10 is not a single digit_)
- and then press any of the digits between 1 and 0.)  (_this is technically closer, but 0 should be allowed too_)

Only the first one of those 3 lines is a good and conclusive phrasing, the 2 other ones should be rewritten to concur with the first one.

I am more than willing to open a pull request to suggest improvements for those 2 sentences, but it would help a lot to have some good suggestions for the correct phrasing first.

**Comment by RAJU2529** [comment]
@illfated . Will you  create a PR for this issue. 
I am not compatible with this issue

**Comment by illfated** [comment]
It is not yet clear how the sentence should be rephrased, so this needs more proper feedback until we can say with certainty how the text can be improved.

**Comment by illfated** [comment]
Maybe the phrasing needs to include "1, 2, 3 .... all the way through 8, 9, 0" -- but I am not sure yet.

**Comment by luis-castro** [comment]
> edit 3: Hmm, maybe not as easy as I thought when it comes to describing the top row of the keyboard. It usually starts with 1 and ends with 0. The phrasing "from 1 to 0" looks a bit odd, especially taken out of context, unless the focus is 100% on a computer keyboard.
> 
> Well, if someone can provide a good way of describing the top row (number row) on a computer keyboard, I will gladly post a PR for it.

I think that is a good way to describe it. Specially because that paragraph is talking specifically about the keyboard upper row. Perhaps rephrasing it as "...press and hold the SHIFT key and then press any of the keys between [1] and [0]" could work.

**Comment by MaratMussabekov** [comment]
Hello, please have a look at #5900 
Thank you

**Comment by illfated** [comment]
Rich diff, for easier overview of the changes:
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5900/files?short_path=93c6abe#diff-93c6abe573fca2d86fad77f7ef4033e1

I am still thinking that maybe the phrase "between 1 and 0" could be changed to something more logical, like for example this:
***
> [...] typed by pressing and holding the SHIFT key and then pressing any of the keys on the number row of the keyboard **(from 1 through 9 and 0)**
***
> (Upper-row symbols are those that require you to press and hold the SHIFT key and then press any of the keys on the number row of the keyboard, **from 1 through 9 and 0**.)
***

**Comment by MaratMussabekov** [comment]
Hello @illfated , that looks likes much better, thank you!

**Comment by mypil** [comment]
@luis-castro - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/cfe27847f4e20a5435554d340206b1ad79eb4ca2. 


Thank you for your contribution to make the docs better! Much appreciated!
