### ISSUE TITLE
Operating System Requirements

### ISSUE THREAD

**Issue by laolive382** [MicrosoftDocs/windows-itpro-docs#5818]
Can you please update the Operating System Requirements to reflect Server 2008 R2 or later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 987a771b-1edd-2c26-5330-8c422146543b
* Version Independent ID: 382d1672-f6b9-f53e-4aa3-748556b37088
* Content: [VAMT Requirements (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/volume-activation/vamt-requirements#feedback)
* Content Source: [windows/deployment/volume-activation/vamt-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/volume-activation/vamt-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
That page needs an edit anyway, to restore the last row of the table you refer to.

## System Requirements

The following table lists the system requirements for the VAMT host computer.

|Item |Minimum system requirement |
|-----|---------------------------|
|Computer and Processor |1 GHz x86 or x64 processor |
|Memory |1 GB RAM for x86 or 2 GB RAM for x64 |
|Hard Disk |16 GB available hard disk space for x86 or 20 GB for x64 |
|External Drive|Removable media (Optional) |
|Display |1024x768 or higher resolution monitor |
|Network |Connectivity to remote computers via Windows® Management Instrumentation (TCP/IP) and Microsoft® Activation Web Service on the Internet via HTTPS |
|Operating System |Windows 7, Windows 8, Windows 8.1, Windows 10, Windows Server 2008 R2, or Windows Server 2012. |
|Additional Requirements |<ul><li>Connection to a SQL Server database. For more info, see [Install VAMT](install-vamt.md).</li><li>PowerShell 3.0: For Windows 8, Windows 8.1, Windows 10, and Windows Server® 2012, PowerShell is included in the installation. For previous versions of Windows and 
Windows Server, you must download PowerShell 3.0. To download PowerShell, go to [Download Windows PowerShell 3.0](https://go.microsoft.com/fwlink/p/?LinkId=218356).</li><li>If installing on Windows Server 2008 R2, you must also install .NET Framework 3.51.</li></ul> |

***
Funny detail: The download page for [VAMT 2.0 (Date Published: 12/20/2019)](https://www.microsoft.com/en-us/download/details.aspx?id=11936) contains the following information in the System Requirements section:

**Supported Operating System**

Windows 7, Windows Server 2003 Service Pack 2, Windows Server 2008 R2, Windows Server 2008 Service Pack 2, Windows Vista, Windows XP Service Pack 3
***
I am considering, as a compromise, to phrase the Operating System _Minimum system requirement_  similar to this:

| Item | Minimum system requirement |
| ---- | -------------------------- |
| Operating System | Windows 7, Windows 8, Windows 8.1, Windows 10, Windows Server 2008 R2, Windows Server 2012, or later. |

Caveat: There is a chance that a new Windows Server OS version could be configured (by default or customized) to block x86 applications, which will prevent the VAMT installer from running.
