### ISSUE TITLE
Differentiation between 'Protected Domains' and 'Network Domains'

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/windows-itpro-docs#5821]
How do the two fields 'Protected Domains' and 'Network Domains' differ? It's not clear what sorts of domains belong in each & (for example) if we have an internal Active Directory domain, which should it go into?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ad3f92-24de-5eb5-8454-c72d85737183
* Version Independent ID: 900125eb-31ea-faf3-ac30-7c3d7b30f611
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-gb/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure#manage-your-advanced-settings)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Hello @ChrisAtMAF 

An independent contributor will comment on this ambiguity with a clarification soon. Thank you for your feedback.

**Comment by VLG17** [comment]
@ChrisAtMAF further down in the article you mentioned it says:

Protected domains
**Specify the domains used for identities in your environment**. All traffic to the fully-qualified domains appearing in this list will be protected. Separate multiple domains with the "," delimiter.

exchange.contoso.com,contoso.com,**region.contoso.com**


Network domains
**Specify the DNS suffixes used in your environment**. All traffic to the fully-qualified domains appearing in this list will be protected. Separate multiple resources with the "," delimiter.

corp.contoso.com,**region.contoso.com**

From the examples given, i understand that one does not exclude the other. You could have an AD child domain (region.contoso.com - like in the example), which also contains identities (users).

**Comment by ChrisAtMAF** [comment]
Sorry - what I was after was in particular an explanation of how these fields ***differ***. Why should I put a domain into 'Protected Domains' but not 'Network Domains'? If I put a domain in 'Protected Domains' but NOT 'Network Domains' - or the other way round - what behaviour can I expect to see?

At present the documentation talks about 'specify the domains used' and 'specify the DNS suffixes used' as if that's the distinction. But it goes on to say 'All traffic to the fully-qualified domains appearing in this list will be protected' which implies they do the same thing.

**Comment by e0i** [comment]
@ChrisAtMAF Under investigation.

**Comment by new-kirte** [comment]
any progress here?

**Comment by joinimran** [comment]
@ChrisAtMAF - Thank you for your query. Please note that as it is mentioned in Protected Domain are the domains that are used to  deal with identities in your environment. Any domain that deals with identity management will go into protected domains. So for example the Active Directory is used for Identity management so the AD domain will go into protected domains. 

Network domains are used to specify the DNS suffix used in your environment. So DNS network domains will have a record for dns suffixes.

To make is simple, all identities management related domains will go into Protected Domains and your environment suffixes will go into Network Domains.

Thanks.
Imran.
