### ISSUE TITLE
PXE Compatibility

### ISSUE THREAD

**Issue by davidh258** [MicrosoftDocs/windows-itpro-docs#5826]
Network Booting (PXE) for the Surface Pro X is listed page as being compatible, however this contradicts "windows-itpro-docs/devices/surface/ethernet-adapters-and-surface-device-deployment.md" which states "PXE boot is not supported on Surface Pro X."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8801006e-0612-0d68-18fc-fe5f198c8136
* Version Independent ID: 0a9c5b49-fbfe-f81e-e0db-70da3e1629ba
* Content: [Deploying, managing, and servicing Surface Pro X - Surface](https://docs.microsoft.com/en-us/surface/surface-pro-arm-app-management)
* Content Source: [devices/surface/surface-pro-arm-app-management.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-pro-arm-app-management.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @davidh258 ,
this contradiction was fixed by https://github.com/MicrosoftDocs/windows-itpro-docs/commit/4c4fafce93a7a2f42fe0bbab7228384eb9f2ebef#diff-305040c324dc2e1590b5cc22ad8c332e
Thank you

**Comment by Kai88Kai** [comment]
hi, will it in future be possible to get an pxe support? 

i tries to install via pxe für 100 devices, but no one workes.

**Comment by mypil** [comment]
@davidh258 - Thank you for submitting feedback.

From our understanding, the issue has been resolved so we will close this issue.

@Kai88Kai - I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.


Thank you for your contribution to make the docs better! Much appreciated!
