### ISSUE TITLE
Incorrect path in 0xC1900101 - 0x4000D

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/windows-itpro-docs#5827]
Under '0xC1900101 - 0x4000D', it states:

'Check supplemental rollback logs for a setupmem.dmp file, or event logs for any unexpected reboots or errors.
Review the rollback log and determine the stop code.
The rollback log is located in the C:$Windows.~BT\Sources\Panther folder.'

The rollback log is located under C:\$Windows.~BT\Sources\Rollback, not C:\$Windows.~BT\Sources\Panther folder

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 528014e0-02e5-2d77-a229-4895731bb872
* Version Independent ID: 4f46b620-e345-c9e4-70fa-ae4f5a8e48b9
* Content: [Resolution procedures - Windows IT Pro - Windows Deployment](https://docs.microsoft.com/en-gb/windows/deployment/upgrade/resolution-procedures#0xc1900101)
* Content Source: [windows/deployment/upgrade/resolution-procedures.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/resolution-procedures.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
These logs change location depending on when the rollback occurs.  I can add some clarification, but there are times when the rollback log will be located in the Panther folder.

**Comment by RAJU2529** [comment]
@ChrisAtMAF @greg-lindsay .    According to the support.microsoft.com,

**https://support.microsoft.com/en-us/help/928901/log-files-that-are-created-when-you-upgrade-to-a-new-version-of-window**

The following log files are created when an upgrade fails, and the installation rollback is initiated:
C:\$Windows.~BT\Sources\Rollback\setupact.log
C:\$Windows.~BT\Sources\Rollback\setupact.err

**Comment by greg-lindsay** [comment]
The support article isn't very clear.  When upgrade fails, there is always a rollback - and there's also a phase called rollback with it's own file locations.  It's a little more clear here: https://docs.microsoft.com/en-us/windows/deployment/upgrade/log-files but the whole process is a bit complicated.  

Based on the code '0xC1900101 - 0x4000D' **I think you are probably right though**.  This is what is referred to as a "generic rollback" and the log files are indeed at $Windows.~BT\Sources\Rollback

I'll get that changed. Thanks for the catch!

**Comment by greg-lindsay** [comment]
The PR to change this is merged. It might not actually publish until tomorrow.

**Comment by ChrisAtMAF** [comment]
Can't see this? Do you know when it will be published?

**Comment by ChrisAtMAF** [comment]
I can see it now - thank you :)
