### ISSUE TITLE
Change from SCCM to ECM ? 

### ISSUE THREAD

**Issue by jwillis44** [MicrosoftDocs/windows-itpro-docs#5828]
With the rebranding of SCCM in Version 1910, should the &lt;ProductName="SYSTEM CENTER CONFIGURATION MANAGER"&gt;
be changed to &lt;ProductName="ENDPOINT CONFIGURATION MANAGER"&gt; ?
That is how it is listed in the details of CcmExec.exe I see that when deploying WDAC with SCCM the policy provided is still  referencing the "SYSTEM CENTER CONFIGURATION MANAGER" It's not working for me so I can't determine if that is the reason or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07fdf27b-1ead-1b6e-c793-a2ad259a4f6a
* Version Independent ID: 8da1f371-73d4-c79f-a97b-80170e7860af
* Content: [Authorize apps deployed with a WDAC managed installer (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-managed-installer?source=docs#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-managed-installer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-managed-installer.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@jwillis44 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by illfated** [comment]
May also be worth while using the Feedback dialog app to contact the developers about these details & changes in SCCM / ECM.

**Comment by mypil** [comment]
Thanks for suggesting that @illfated.  

@jwillis44 - As suggested, you may also consider opening a product feedback ticket for any of your feedback or feature requests to help Microsoft improve your experience. Please click on this
Microsoft Windows 10 Feedback Hub link - **https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**

We hope this gets you pointed in the right direction to help resolve your issue! Thank you.
