### ISSUE TITLE
Add location of crash file

### ISSUE THREAD

**Issue by MSFTEfeedback** [MicrosoftDocs/windows-itpro-docs#5829]
This page describes how to create a crash dump, but doesn't tell you where to find the dump file. Seems like a pretty obvious thing to include.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae826aa0-3286-7044-27aa-501e6c265b53
* Version Independent ID: 5109af1f-465a-8f0b-cfe0-82e8de22fd70
* Content: [Generate a kernel or complete crash dump - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/generate-kernel-or-complete-crash-dump#feedback)
* Content Source: [windows/client-management/generate-kernel-or-complete-crash-dump.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/generate-kernel-or-complete-crash-dump.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by RAJU2529** [comment]
@MSFTEfeedback .  location of the crash dump is mentioned in the article under the note.
%SystemRoot%\Memory.dmp

**Comment by illfated** [comment]
Confirmed, this is documented on the page you posted from:
- https://docs.microsoft.com/en-us/windows/client-management/generate-kernel-or-complete-crash-dump

![image](https://user-images.githubusercontent.com/38162891/72208633-521b7200-34a5-11ea-9482-3ee0faa632d3.png)

You can also use the following Windows Run command on your own Windows computer to see the what is in use: **`SystemPropertiesAdvanced`**

![image](https://user-images.githubusercontent.com/38162891/72208657-9149c300-34a5-11ea-86e7-5dadc7fa9a23.png)

![image](https://user-images.githubusercontent.com/38162891/72208653-85f69780-34a5-11ea-97d2-20d11dca1cad.png)

**Comment by mypil** [comment]
@MSFTEfeedback -  Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by RAJU2529 and illfated so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
