### ISSUE TITLE
But how can I invoke the admin tools from other means?

### ISSUE THREAD

**Issue by gabefair** [MicrosoftDocs/windows-itpro-docs#5831]
How can I start the administrative tools from powershell? Also what is the name of the .exe that will start the administrative tools, and where is this located? Right now I can't even open the start menu and I need to be able to run this from a powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1faa451a-3db7-72fa-9745-b1a898d83f4a
* Version Independent ID: 3cd11526-a379-ba90-f619-777ee45330a3
* Content: [Administrative Tools in Windows 10 (Windows 10) - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/administrative-tools-in-windows-10#feedback)
* Content Source: [windows/client-management/administrative-tools-in-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/administrative-tools-in-windows-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@gabefair .  I will check and give the .exe

**Comment by RAJU2529** [comment]
@gabefair 
List of commands which can be executed in Powershell with  Administrator rights

comexp.msc /s
compmgmt.msc
dfrgui.exe
cleanmgr.exe
eventvwr.msc /s
iscsicpl.exe
secpol.msc
odbcad32.exe
perfmon.msc
printmanagement.msc
RecoveryDrive.exe
regedit.exe
perfmon.exe /res
services.msc
msconfig.exe
msinfo32.exe
taskschd.msc /s
WF.msc
MdSched.exe

**Comment by RAJU2529** [comment]
@illfated . Created PR #5833  . So review it If you found  correct then approve

**Comment by RAJU2529** [comment]
@illfated . I accepted commit

**Comment by illfated** [comment]
Fair enough. I just want to wait for a reply from @JohanFreelancer9 first, just to see if there is room for more improvement first.

**Comment by JohanFreelancer9** [comment]
@illfated @RAJU2529 Copy Review done.

**Comment by RAJU2529** [comment]
@JohanFreelancer9 . completed

**Comment by illfated** [comment]
Not quite. There is 1 more review pending, not yet committed. Link: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5833#pullrequestreview-341558384

**Comment by illfated** [comment]
OK, so now the PR is updated. I have commented that it looks good to me. Will ask the document manager and one of the MS Docs team members for a final review & merge.

**Comment by e0i** [comment]
Closing via #5833. Thank you.
