### ISSUE TITLE
The registry mentioned in the document is invalid

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/windows-itpro-docs#5834]
I installed this tool, but these key values were not found in the registry and the manual addition is invalid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ac6c100-6e19-4cf6-2fd1-558a6751cc5d
* Version Independent ID: eec13586-5975-9ada-ec0f-9f53654eb73b
* Content: [Surface Brightness Control - Surface](https://docs.microsoft.com/en-us/surface/microsoft-surface-brightness-control)
* Content Source: [devices/surface/microsoft-surface-brightness-control.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/microsoft-surface-brightness-control.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
wiil you  show screenshots of the registry key

reg query "HKLM\SOFTWARE\Microsoft\Surface\Surface Brightness Control\"

**Comment by goxia** [comment]
Error: The system could not find the specified registry key or value.

Referring to the documentation, I created these key values by hand, but found that they didn't work.

**Comment by illfated** [comment]
@goxia : Does this issue happen on English Windows 10 or non-English Windows 10?
Is your Surface device running its original Windows setup, or a re-image with customized drivers?
Did you try installing the Surface Tools for IT package on your Surface device?

**Comment by illfated** [comment]
(ref. #5832 & #5839)

**Comment by goxia** [comment]
> （参考号[＃5832](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5832)和[＃5839](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/5839)）

Thanks a lot.

**Comment by illfated** [comment]
(also ref. #5214 , #5756 )
