### ISSUE TITLE
Defender ATP Onboarding for VDI - does this apply to Server 2016/19 RDSH Sessions?

### ISSUE THREAD

**Issue by dcaddick** [MicrosoftDocs/windows-itpro-docs#5835]
Can someone confirm if this would apply to Shared RDSH sessions on Server 2016/2019?
This doc is specifically calling out Windows 10, no mention of the server.

If we look at onboarding Windows Server from the Defender ATP Console &gt; Settings &gt; Onboarding it does seem like the two are separate? The other question is license - is this simply a case that the Server get's onboarded thru the ASC and then needs to be covered that way?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804f2883-5de4-9d54-d0b4-e64b04984aa8
* Version Independent ID: 0ab9ee92-c5e1-0455-92ba-ed07ed7bd140
* Content: [Onboard non-persistent virtual desktop infrastructure (VDI) machines - Windows security](https://docs.microsoft.com/en-gb/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by joinimran** [comment]
@dcaddick - Thank you for your query, please see Onboard servers to the Microsoft Defender ATP service here at https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints where it also includes license-related information as well. 

Thanks.
Imran.

**Comment by mypil** [comment]
@dcaddick - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
