### ISSUE TITLE
Conflict of information

### ISSUE THREAD

**Issue by pstakuu** [MicrosoftDocs/windows-itpro-docs#5837]
This page indicates Microsoft uses 24 hours for content cache.  This IT showcase published ~30 days after the last update to this page indicates Microsoft uses seven days as max cache age (https://www.microsoft.com/en-us/itshowcase/keeping-windows-10-devices-up-to-date-with-microsoft-intune-and-windows-update-for-business)
Which is it? I'm trying to mirror the Microsoft setup.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb67e518-6f60-23e0-2545-c2839e2b4159
* Version Independent ID: e9a31629-e3cb-0367-31c4-5661284d89bf
* Content: [Configure Delivery Optimization for Windows 10 updates (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization#feedback)
* Content Source: [windows/deployment/update/waas-delivery-optimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-delivery-optimization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@narkissit can you help out here?

**Comment by mypil** [comment]
@jaimeo @narkissit - Do you have any updates on this?

Thank you.

cc: @kenwith

**Comment by jaimeo** [comment]
@narkissit  can you help us with this information?

**Comment by VLG17** [comment]
@pstakuu Did you get to find a suitable value for Max Cache Age?

Regarding your initial ask, i don't think we're comparing the same thing. One article refers to Microsoft CSEO (Core Services Engineering and Operations) and the other one refers to Microsoft IT. In my understanding they are not one and the same entity, hence the differences that you spotted in terms of bandwidth utilization.

**Comment by nam31** [comment]
@pstakuu Please let us know if you still have any question regarding the issue you have raised initially.

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
