### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by v-sbsjom** [MicrosoftDocs/windows-itpro-docs#5838]
I tried, and an FTE tried, and we both got you don't have permission on the Microsoft 365 Admin site.  The site we tried is admin.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9d48034-4b29-c10c-6e14-ecf14ca12f70
* Version Independent ID: 7794a57a-0db1-6420-68e9-0d1592a57b60
* Content: [Create Surface Hub 2S device account - Surface Hub](https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-account#feedback)
* Content Source: [devices/surface-hub/surface-hub-2s-account.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/surface-hub-2s-account.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
@EzraWard , @PixelStroke , would you be able to offer any suggestions here?

**Comment by mypil** [comment]
@v-sbsjom - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
