### ISSUE TITLE
Support for Hybrid Azure Active Directory Join

### ISSUE THREAD

**Issue by hugemc** [MicrosoftDocs/windows-itpro-docs#5846]
Up the top it says "Support for Hybrid Azure Active Directory Join (with devices joined to an on-premises Active Directory domain) will be available in a future Windows 10 release." but just below it it says "Hybrid Azure Active Directory join is available for devices that must be joined to both Azure Active Directory and your on-prem Active Directory domain."

Pretty sure this was introduced in 1809. Might need a small update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2434dfb6-ac9a-4ba1-a681-88786c87010a
* Version Independent ID: 47e7470e-ab97-9917-04aa-4ec08a178af5
* Content: [Windows Autopilot User-Driven Mode - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/user-driven?source=docs#feedback)
* Content Source: [windows/deployment/windows-autopilot/user-driven.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/user-driven.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Good catch, I think the article was edited when Hybrid capability was added and the introduction paragraph never got changed.

**Comment by greg-lindsay** [comment]
Assigning to me

**Comment by greg-lindsay** [comment]
This has been updated and PR merged. The content will change later today.
