### ISSUE TITLE
Spacing issues in translated (german) article

### ISSUE THREAD

**Issue by d-Rickyy-b** [MicrosoftDocs/windows-itpro-docs#5849]
Hey there, while reading some documentation on the MS safety scanner I found that the (auto generated?) German translation had some issues with the spacing. There are two places (see screenshot) where there is no space after a link where there should be one.

A bit later where the text is talking about the executable name, there is an additional space, that separates the file name and its extension. I'd say it's a rather minor issue, but it might help to get the spacing right, especially when searching for that executable name for example.

![grafik](https://user-images.githubusercontent.com/5798157/72469154-1fdc7e00-37df-11ea-8b66-1b1e7252329c.png)

Thank you for having a look!
---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f5bb1ce3-9128-5385-4417-d22eb5f8cb77
* Version Independent ID: cb6ba731-a2c2-e9b9-7c3e-db781b1b5222
* Content: [Microsoft Safety Scanner-Download](https://docs.microsoft.com/de-de/windows/security/threat-protection/intelligence/safety-scanner-download)
* Content Source: [windows/security/threat-protection/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/intelligence/safety-scanner-download.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by illfated** [comment]
True, those spacing issues are visible on the page.

Odd detail: while using Google Chrome and letting the browser translate the page back to English, the links are at the end of the sentence, but with an extra space between the links and the sentence period . ( . )

**Comment by e0i** [comment]
Hello, @d-Rickyy-b 

Yes, The translations are indeed performed automatically and formatting problems are common among localization issues. Your feedback is being routed to the Localization team for investigation.

Thank you for bringing this issue to attention.

cc @TinaMcn

**Comment by TinaMcN** [comment]
@d-Rickyy-b thanks for reporting this.  The spacing problem is a bug in our machine translation tool which the tool owners are actively investigating.   The article has been human translated since you reported the issue so it's fixed in this article now.  I hope we'll have a fix soon to correct the issue in other articles that have the same problem.

**Comment by illfated** [comment]
Looks good to me, from what I can see by comparing the reported spacing issues to the current page.

**Comment by TinaMcN** [comment]
@d-Rickyy-b as you have previously provided excellent feedback on the German Docs content I wanted to let you know that we are starting a pilot project to enable community Editing (PR's) and Feedback (Issues) on the German Microsoft Teams content https://docs.microsoft.com/de-de/microsoftteams/teams-overview. We have a German linguist on standby to review any suggestions during December and January.  
If you have any time to look at the translation quality of the German Teams content we would love to get your feedback. Note that the content is a mixture between human translated and partially-machine-translated articles - the MT ones have a purple banner at the top. The editing feature will only be enabled on the human translated articles. If you know of anyone else that might be interested to help us out feel free to share.
Best wishes
Tina
Localization manager for Docs content for Teams, M365, Windows, SharePoint, Exchange, Edge, Surface etc.
