### ISSUE TITLE
MBAM troubleshooting

### ISSUE THREAD

**Issue by prashanthmiryala** [MicrosoftDocs/windows-itpro-docs#585]
we have scenario where TPM PIN is not accepting even we enter correct one, after several attempts TPM is getting locked, we are unable to get the TPM owner password from the web console neither from DB.
there are no clear documents how MBAM works and which log needs to be checked and how to troubleshoot the issues in above scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9334111a-4265-ffbb-cb51-94e7282881ea
* Version Independent ID: 3c477f76-a1dd-e8ad-a679-2a9472d4de98
* Content: [How to Reset a TPM Lockout](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v2/how-to-reset-a-tpm-lockout-mbam-2)
* Content Source: [mdop/mbam-v2/how-to-reset-a-tpm-lockout-mbam-2.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v2/how-to-reset-a-tpm-lockout-mbam-2.md)
* Service: **unspecified**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by prashanthmiryala** [comment]
we are not able to find the TPM owner password, how can we get that..

**Comment by Justinha** [comment]
Please see MBAM docs at https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/

**Comment by prashanthmiryala** [comment]
HI Justin,


thank you, i could not find it over there.

please help me with the specific document.

________________________________

**Comment by Justinha** [comment]
@prashanthmiryala unfortunately we are no longer adding new content for MBAM. This blog post may help you troubleshoot TPM owner password, and explains where it is stored: https://blogs.technet.microsoft.com/dubaisec/2017/02/28/tpm-owner-password/ 

You can also search the Microsoft Knowledge base or open a case with Customer Support.
