### ISSUE TITLE
TPM required or preferred?

### ISSUE THREAD

**Issue by ChadSimmons** [MicrosoftDocs/windows-itpro-docs#5853]
The requirements section states 
> TPM 1.2 or 2.0, either discrete or firmware (preferred - provides binding to hardware)

It is unclear if it is a TPM that is preferred or a firmware based TPM that is preferred.  Suggest clarifying language such as
> TPM 1.2 or 2.0 (preferred - provides binding to hardware), either discrete or firmware

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0238a73f-da06-ae17-c61d-85ae54e0f7cb
* Version Independent ID: e5bb4a25-a7c3-3a16-bd95-d6f2513402e0
* Content: [Windows Defender Credential Guard Requirements (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-requirements)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@ChadSimmons   Firmware based TPM not supported I read on Microsoft docs. only discrete tpm is supported

**Comment by e0i** [comment]
@ChadSimmons 

The suggested clarifications have been merged via the PR #6012. Thank you for the feedback.
