### ISSUE TITLE
broken links, credential-guard-considerations 

### ISSUE THREAD

**Issue by ChadSimmons** [MicrosoftDocs/windows-itpro-docs#5854]
The link is dead
> See this video: Credentials Protected by Windows Defender Credential Guard

Please remove or replace with 
> [What is virtualization-based security?](https://www.linkedin.com/learning/microsoft-cybersecurity-stack-advanced-identity-and-endpoint-protection/what-is-virtualization-based-security)

Related to #3860 and commit 39c4110
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0238a73f-da06-ae17-c61d-85ae54e0f7cb
* Version Independent ID: e5bb4a25-a7c3-3a16-bd95-d6f2513402e0
* Content: [Windows Defender Credential Guard Requirements (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-requirements#feedback)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@ChadSimmons The link has been updated via the corresponding PR #5864. Thank you for your feedback.
