### ISSUE TITLE
Remote Scan

### ISSUE THREAD

**Issue by pabloescognar** [MicrosoftDocs/windows-itpro-docs#5855]
All of these resources are great. Just wondering if you have any instruction on running a remote scan on Mac devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8845474-23fa-dc90-1edb-cfdab46eb342
* Version Independent ID: 35f6cb66-51d7-14af-ba52-7d28125ac968
* Content: [Privacy for Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-privacy#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-privacy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-privacy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@pabloescognar Glad that you have found the article useful.

@levinec @Dansimp Would you be kind to share with the community whether there are any plans to publish instructions for remote scanning on Mac devices?

Feel free to ping me with guidance if any independent contributions are going to be useful for this topic. Thank you.

**Comment by maximvelichko** [comment]
@pabloescognar , can you please elaborate on your scenario ("running a remote scan")? Do you want to e.g. initiate a scan on all MDM enrolled machines centrally? a single machine, or something else?
