### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by greg-lindsay** [MicrosoftDocs/windows-itpro-docs#5859]
This is a test for automating feedback retrieval.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9819be6d-7a38-09a8-d17c-a3c8cb7a1b4d
* Version Independent ID: 75140c0e-30f7-36c4-bc1b-8dfef592cb77
* Content: [Windows Autopilot and Surface devices - Surface](https://docs.microsoft.com/en-us/surface/windows-autopilot-and-surface-devices)
* Content Source: [devices/surface/windows-autopilot-and-surface-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/windows-autopilot-and-surface-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Will additional comments be useful here, or is that discouraged?

**Comment by greg-lindsay** [comment]
It can help me see if notifications work for every comment :)  I am trying out settings described here: https://help.github.com/en/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-repositories

**Comment by greg-lindsay** [comment]
Closing this issue.
