### ISSUE TITLE
Error in 'Important Notice'

### ISSUE THREAD

**Issue by pcdiks** [MicrosoftDocs/windows-itpro-docs#5867]
The important notice is: To fully enable controlled folder access, you must set the Group Policy option to Enabled and also select Enable in the options drop-down menu. This 'Enable' is also mentioned in Step 4 but again, this is not a viable option.

However, there is no 'Enable' in the options drop-down menu. The available options are visible in the screenshot on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed9a3e1-b570-01a6-252b-f4a291c7f2be
* Version Independent ID: 27a09993-2f35-e38c-b5be-3b364fd4acb2
* Content: [Turn on the protected folders feature in Windows 10 - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/enable-controlled-folders#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/enable-controlled-folders.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/enable-controlled-folders.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by mypil** [comment]
@pcdiks - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/0cbe1d5cfd166f5e0a15735237be479c10726ca9. 


Thank you for your contribution to make the docs better! Much appreciated!
