### ISSUE TITLE
2020 LDAP channel binding and LDAP signing requirement

### ISSUE THREAD

**Issue by rohitgaikwad09** [MicrosoftDocs/windows-itpro-docs#5868]
Hi Team,

This is related to **document :** [2020 LDAP channel binding and LDAP signing requirement for Windows](https://support.microsoft.com/en-us/help/4520412/2020-ldap-channel-binding-and-ldap-signing-requirement-for-windows)

The value "**Require signature**" of Domain controller: LDAP server signing requirements 
**Reference :** https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/domain-controller-ldap-server-signing-requirements, will be set as a default value after the March 2020 update.

Following are my questions:
1) Whether a client using a (LDAP **without** TLS/SSL configured) and server-signing-requirement set to **none** will fail to connect to LDAP after enforcement of this 2020 update?

2) When "**Require signature**" is set as a value of domain controller's LDAP server signing requirement, Then can a client will be able connect to LDAP where LDAP is **not** configured with TLS/SSL?

3) The definition of value "**Require signature**" states that _the LDAP data-signing option must be negotiated unless Transport Layer Security/Secure Sockets Layer (TLS/SSL) is in use._
Here, what exactly the _LDAP data-signing option must be negotiated_  means?

This issue maybe somewhat similar to issue #5386 

Thanks,
           --Rohit

**Comment by rohitgaikwad09** [comment]
Hi Joyce,

Thanks for assigning this issue to yourself. 

Can you please expedite this forward as the security update 2020 may create a blocking issue for our products that uses a (LDAP configured **without** TLS/SSL) and server-signing-requirement set to **none**.

Adding a question on this issue:
Does the [security update 2020](https://support.microsoft.com/en-us/help/4520412/2020-ldap-channel-binding-and-ldap-signing-requirement-for-windows) states that the LDAP must be configured with TLS/SSL to avail the benefit of security update? If LDAP is not configured with TLS/SSL then clients will not be able to connect LDAP with "**Require signature**" as a set value for domain controllers?

Thanks,
           --Rohit

**Comment by mypil** [comment]
@rohitgaikwad09 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Dansimp - Can you please share your insights on this issue related to  #5386? 

Please refer to below doc details:

Content: [Domain controller LDAP server signing requirements (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/domain-controller-ldap-server-signing-requirements#feedback)
Content Source: [windows/security/threat-protection/security-policy-settings/domain-controller-ldap-server-signing-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/domain-controller-ldap-server-signing-requirements.md)

Thank you.

cc: @kenwith

**Comment by lindspea** [comment]
@rohitgaikwad09 thank you for reaching out. Please have a look at this article I found regarding - https://docs.microsoft.com/windows/security/threat-protection/security-policy-settings/domain-controller-ldap-server-signing-requirements

**Comment by nam31** [comment]
@rohitgaikwad09 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
