### ISSUE TITLE
Add verification info for certutil -dsTemplate command

### ISSUE THREAD

**Issue by robmacf** [MicrosoftDocs/windows-itpro-docs#5869]
Certutil -dstemplate fails silently (and deceptively.) If one makes an error in the certutil -dsTemplate command (section "Mark the template as the Windows Hello Sign-in template") certutil actually reports success. An incorrect certutil -dstemplate command produces this result: "[Version]
Signature = "$Windows NT$"

CertUtil: -dsTemplate command completed successfully."

A *correct* certutil -dsTemplate command produces the following response:

"CN=Certificate Templates,CN=Public Key Services,CN=Services,CN=Configuration,DC=[yourdomain]:
  WHFBAuthentication

Old Value:
  msPKI-Private-Key-Flag REG_DWORD = 5050080 (84213888)
    CTPRIVATEKEY_FLAG_REQUIRE_SAME_KEY_RENEWAL -- 80 (128)
    CTPRIVATEKEY_FLAG_ATTEST_NONE -- 0
    TEMPLATE_SERVER_VER_WINBLUE&lt;&lt;CTPRIVATEKEY_FLAG_SERVERVERSION_SHIFT -- 50000 (327680)
    TEMPLATE_CLIENT_VER_WINBLUE&lt;&lt;CTPRIVATEKEY_FLAG_CLIENTVERSION_SHIFT -- 5000000 (83886080)
New Value:
  msPKI-Private-Key-Flag REG_DWORD = 5250080 (86311040)
    CTPRIVATEKEY_FLAG_REQUIRE_SAME_KEY_RENEWAL -- 80 (128)
    CTPRIVATEKEY_FLAG_ATTEST_NONE -- 0
    TEMPLATE_SERVER_VER_WINBLUE&lt;&lt;CTPRIVATEKEY_FLAG_SERVERVERSION_SHIFT -- 50000 (327680)
    CTPRIVATEKEY_FLAG_HELLO_LOGON_KEY -- 200000 (2097152)
    TEMPLATE_CLIENT_VER_WINBLUE&lt;&lt;CTPRIVATEKEY_FLAG_CLIENTVERSION_SHIFT -- 5000000 (83886080)
CertUtil: -dsTemplate command completed successfully."

It would be great if the page could reproduce the "successful" result text and instruct the reader to verify that they see it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd063d0c-8739-15bd-4f16-11b893029845
* Version Independent ID: cd3679fe-dd9c-44f9-04ed-c772a47ca4e4
* Content: [Configuring Hybrid Windows Hello for Business - Public Key Infrastructure (PKI) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@robmacf 

Upon your feedback, the content has been updated with relevant changes accordingly via the PR #5950. Thanks.
