### ISSUE TITLE
404 Not Found - Advanced Group Policy Management 4.0 documents

### ISSUE THREAD

**Issue by sanitybit** [MicrosoftDocs/windows-itpro-docs#5870]
The link titled Advanced Group Policy Management 4.0 documents which redirects to `https://www.microsoft.com/downloads/details.aspx?FamilyID=58fd6cda-0210-4da0-91d2-8c3cc2817df8` returns a 404 response. The correct URL appears to be `https://www.microsoft.com/en-us/download/details.aspx?id=13975`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a026a631-2805-4692-fbc1-6158010a4697
* Version Independent ID: 4bbcfb99-09ec-577e-70d3-5ce24033ced3
* Content: [Resources for AGPM - Microsoft Desktop Optimization Pack](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/agpm/resources-for-agpm#feedback)
* Content Source: [mdop/agpm/resources-for-agpm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/mdop/agpm/resources-for-agpm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
### Documents for download

-   [Advanced Group Policy Management 4.0 documents](https://go.microsoft.com/fwlink/?LinkID=158931)

(Broken link; https://go.microsoft.com/fwlink/?LinkID=158931 -- points to https://www.microsoft.com/downloads/details.aspx?FamilyID=58fd6cda-0210-4da0-91d2-8c3cc2817df8 as shown above.)
***
https://www.microsoft.com/download/details.aspx?id=13975 is the correct link, as shown in the document linked below:
***
### [Group Policy, Advanced Group Policy Management (AGPM), and Internet Explorer 11](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/browsers/internet-explorer/ie11-deploy-guide/group-policy-and-advanced-group-policy-mgmt-ie11.md)

(https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/browsers/internet-explorer/ie11-deploy-guide/group-policy-and-advanced-group-policy-mgmt-ie11.md)

**Comment by mypil** [comment]
@sanitybit -  Thank you for pointing this out.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/ecdd8296eb7e69e0efb8c9cf5e14814fa7897ca7. 


Thank you for your contribution to make the docs better! Much appreciated!
