### ISSUE TITLE
Azure MFA integration with ADFS required?

### ISSUE THREAD

**Issue by pmeuser** [MicrosoftDocs/windows-itpro-docs#5871]
PIN reset from Windows login screen works for me only after enabling Azure MFA on ADFS (2019) for a federated domain. Is this an official prerequisite?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9dae9da-eaf0-c209-7c65-be8d2c1ada12
* Version Independent ID: 28b6788d-7982-23c2-5f19-f80690ebc0ce
* Content: [Pin Reset - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by MaratMussabekov** [comment]
Hello @pmeuser ,
Hybrid Windows Hello for Business deployment is official prerequisite for Pin reset.
Windows Hello for Business in turn requires MFA deployment (it could be Azure MFA or third-party MFA)
More detail are in [Windows Hello for Business](https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-identity-verification)
Thank you

**Comment by mypil** [comment]
@pmeuser - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov  so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
