### ISSUE TITLE
Registry Location

### ISSUE THREAD

**Issue by mdcaddic** [MicrosoftDocs/windows-itpro-docs#5872]
Please verify the registry location. I am showing HKLM\Software\Policies\Microsoft\Windows Defender\Policy Manager\EnableNetworkProtection = DWORD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71868539-63d8-b250-f9d4-83a4052f4f74
* Version Independent ID: ed5658cf-173f-47bf-ed76-a68d89ea5c4b
* Content: [Turn on network protection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/enable-network-protection#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/enable-network-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/enable-network-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by joinimran** [comment]
Hi @mdcaddic - The policy location mention in the document is correct.

![image](https://user-images.githubusercontent.com/47118050/73154241-85dad680-40f8-11ea-94e8-90de82750557.png)

**Comment by mdcaddic** [comment]
![Annotation 2020-01-27 174435](https://user-images.githubusercontent.com/21952481/73154814-bd637600-412c-11ea-82cd-6e92e21b5b18.png)

**Comment by mdcaddic** [comment]
Obviously we need to do some further fault finding. Mine has Win10 1909 18363.592 Enterprise.
MS Defender ATP Security Baseline, MDM Security Baseline for May 2019, Preview: Microsoft Edge baseline, Win 10 Endpoint Protection profile.

**Comment by RAJU2529** [comment]
@mdcaddic 
i am using windows 10  64bit 1909 18363.592 enterprise , I conformed  that registry location is correct.
If will be created if you have enabled in group policy editor. Or by adding  regsitry key manually 

![now](https://user-images.githubusercontent.com/3296790/73264950-eef64300-41f9-11ea-95fe-29abd2c84db0.JPG)

**Comment by joinimran** [comment]
@mdcaddic , I have checked on Windows 10 1809 and 1909 and found that the documented location is correct. There is no other reference found which points to the location you have mentioned. This concludes that the documented location for reg value is correct.

Thanks.

@mypil FYI Please.

**Comment by mypil** [comment]
@mdcaddic - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by joinimran so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
