### ISSUE TITLE
Full conditions for automatic BitLocker activation?

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/windows-itpro-docs#5873]
"If the device is not domain joined, a Microsoft account that has been granted administrative privileges on the device is required."

In my experience with my own personal laptop, and colleagues who setup their laptops with their own personal Microsoft accounts initially, BitLocker does not get activated for the internal drives. A separate explicit action is required on the administrator's (i.e. us) part to activate BitLocker. (Also, our computers are just AAD-registered.)

However, for the few AAD-joined computers, be it joined manually or through the Windows Autopilot procedure, we noted the internal drive does automatically get encrypted by BitLocker.

Looks like BitLocker only happens on its own accord when a computer joins an AD or AAD domain, isn't that correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29116f85-264f-d031-be7b-e32a1816cd28
* Version Independent ID: 640478e6-a367-4e47-a177-3a10dd006d1c
* Content: [Overview of BitLocker Device Encryption in Windows 10 - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10#bitlocker-device-encryption)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@icelava . In  my own experiences , my windows 10 laptop not a domain joined , not connected to AAD .

i can able to activate bitlocker for  internal drives , i checked for  c drive with SSD

**Comment by mypil** [comment]
@icelava - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by RAJU2529 so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
