### ISSUE TITLE
Minor mistake in the text

### ISSUE THREAD

**Issue by VincentGuigui** [MicrosoftDocs/windows-itpro-docs#5874]
Hello,
In the HoloLens2 section, it says "...hold the Volume Up button until the third LED is lit. It will the the only lit LED."
The last sentence need a rewrite or be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd4de184-bdeb-2611-8d75-28376e30b0fc
* Version Independent ID: 7b330f9a-d1c0-72f9-0d00-d7fac13e7e00
* Content: [Reset or recover your HoloLens](https://docs.microsoft.com/en-us/hololens/hololens-recovery#feedback)
* Content Source: [devices/hololens/hololens-recovery.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/hololens-recovery.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by mypil** [comment]
@VincentGuigui - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/5a3e76f587cfa7a76c46784bddbf05ed9e310fc0. 


Thank you for your contribution to make the docs better! Much appreciated!
