### ISSUE TITLE
Enabled_Version1000 doesn't exists anymore

### ISSUE THREAD

**Issue by aurelgodin** [MicrosoftDocs/windows-itpro-docs#5876]
Hello,

I am having the same problem described in ticket # 4499...

the Detection Method of this Example Application and which is called inside the documentation on Lines 352-363 doesn't exist anymore could you please update this article for other admins. The new Surface Deployment Powershell Scripts are updated with other RegistryKeys.
Thx and Regards,

Aurelien

**Comment by aurelgodin** [comment]
Hello,
do you have any feedback, because we are blocked for the deployment of pro surfaces

**Comment by illfated** [comment]
(Ref. #5979)

**Comment by illfated** [comment]
@aurelgodin : The necessary changes by PR #5979 have now been merged into the public branch. It will take a few days before the changes are migrated to the docs.microsoft.com page.

Feel free to close this issue, or comment if there is anything else you would like to mention.

**Comment by mypil** [comment]
@aurelgodin - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/b3c830299b71e872967fb4bffeef6ecc544bda7c. 


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by aurelgodin** [comment]
Thank you for your intervention.
