### ISSUE TITLE
Where are these alleged tools?

### ISSUE THREAD

**Issue by anonymous234** [MicrosoftDocs/windows-itpro-docs#5879]
I think the documentation of a tool should include some sort of hint on where the tool is found. Some [older documentation](https://docs.microsoft.com/en-us/windows/win32/win7appqual/application-compatibility-toolkit--act-?redirectedfrom=MSDN) has a download link, but it leads to a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd3bbc4c-2f86-d5a9-336c-93695ace49f2
* Version Independent ID: a7c51e81-2cb2-5ad0-a9b5-7fb89921a0be
* Content: [Application Compatibility Toolkit (ACT) Technical Reference (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/planning/act-technical-reference#feedback)
* Content Source: [windows/deployment/planning/act-technical-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/planning/act-technical-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
I think maybe this tool has retired. I'll ask our engineering folks and see.

**Comment by greg-lindsay** [comment]
You can still get the ADK version 6 bundled with the ADK for Windows 8. https://www.microsoft.com/en-us/download/details.aspx?id=30652

However I believe that the recommendation here will be to move to desktop analytics https://docs.microsoft.com/en-us/configmgr/desktop-analytics/overview and most of this documentation will be archived.  I'm checking on this now however.

**Comment by e0i** [comment]
The issue is being closed since your question seems to be answered by the article author.

Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
