### ISSUE TITLE
Directions for use

### ISSUE THREAD

**Issue by MIHSssweeny** [MicrosoftDocs/windows-itpro-docs#588]
You link to this page to use it to validate my xml but you don't give instructions on how to do so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7479ec95-228f-8f08-4b24-0a7b7a5314ec
* Version Independent ID: f4d42c2f-17a2-52b2-6daa-cc7cecacfdc7
* Content: [Multi-app kiosk XML reference (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/multi-app-kiosk-xml#feedback)
* Content Source: [windows/configuration/multi-app-kiosk-xml.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/multi-app-kiosk-xml.md)
* Service: **unspecified**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
There are a number of ways and tools that you can use to validate XML against XSD. Here is one method: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-hpc-server-2008/dd430099(v=ws.10)
