### ISSUE TITLE
Bitlocker csp not applying to the device

### ISSUE THREAD

**Issue by ausamriyaz** [MicrosoftDocs/windows-itpro-docs#5881]
I have constructed the SyncML according to the specifications but it doesn't seem to apply to the device. this is the SyncML I tested with. I'm using windows 10 enterprise as a test device.

 &lt;Add&gt;
      &lt;CmdID&gt;933&lt;/CmdID&gt;
      &lt;Item&gt;
         &lt;Target&gt;
            &lt;LocURI&gt;./Device/Vendor/MSFT/BitLocker/EncryptionMethodByDriveType&lt;/LocURI&gt;
         &lt;/Target&gt;
         &lt;Meta&gt;
            &lt;Format xmlns="syncml:metinf"&gt;chr&lt;/Format&gt;
         &lt;/Meta&gt;
         &lt;Data&gt;&lt;enabled/&gt;&lt;data id="EncryptionMethodWithXtsOsDropDown_Name" value="3"/&gt;&lt;data id="EncryptionMethodWithXtsFdvDropDown_Name" value="4"/&gt;&lt;data id="EncryptionMethodWithXtsRdvDropDown_Name" value="6"/&gt;&lt;/Data&gt;
      &lt;/Item&gt;
   &lt;/Add&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a05802f-9d0f-9aeb-3c8e-8b92f1284202
* Version Independent ID: 1fd9efc2-8946-75e4-27f3-95ac43a9d987
* Content: [BitLocker CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp)
* Content Source: [windows/client-management/mdm/bitlocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/bitlocker-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@ausamriyaz  These repositories are for the docs themselves (i.e. out of date info, incorrect formatting, and so forth). For actual product issues, those need to be addressed via the proper support channels. I recommend [opening a case with support](https://support.microsoft.com/en-ae/contactus/) for them to look into why the policy is not applying in your case.

If it's determined that it's indeed an issue in the documentation (with the provided syntax example), we will be able to change that.
