### ISSUE TITLE
Network configuration

### ISSUE THREAD

**Issue by AntoineJo** [MicrosoftDocs/windows-itpro-docs#5886]
I think it worth explaining the WDAV urls to whitelist as well 
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1adce021-95d3-a946-5e9d-d818a88d3b0b
* Version Independent ID: ff73e733-ce22-e37c-7e9b-6f477260dbca
* Content: [Microsoft Defender ATP production deployment - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/production-deployment)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/production-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/production-deployment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
Closing via merged PR #6793.
