### ISSUE TITLE
Which ATP Plan is required? Why ATP and not AIP?

### ISSUE THREAD

**Issue by ssccaavvookk** [MicrosoftDocs/windows-itpro-docs#5887]
Is it ATP Plan 1 or ATP Plan 2 required to apply WIP policy based on sensitivity label? Is that capability going to be remain within ATP in the long term, or is there a chance it will be moved to the AIP license where the other sensitivity label capabilities such as encryption and scenarios of protection based on labels are better aligned?

Also, it's really confusing to use "endpoint DLP" and "WIP" interchangably when "DLP" is its own thing within O365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 561d91d8-458d-bc0c-45af-c0a9ccacee93
* Version Independent ID: 7c1fd8f1-74b6-f7d4-fcb0-0e41a0d6ff42
* Content: [How Windows Information Protection (WIP) protects files with a sensitivity label (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/how-wip-works-with-labels#feedback)
* Content Source: [windows/security/information-protection/windows-information-protection/how-wip-works-with-labels.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/how-wip-works-with-labels.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by ssccaavvookk** [comment]
Oh I was confusing Office 365 ATP with Windows Defender ATP. Purchasing Microsoft 365 E5 would more than double the cost compared to subscribing to O365 BP + AAD P1 + AIP+ Intune where every other feature of sensitivity labels are available. That's an extremely substantial cost for small businesses to pay for tons of unnecessary/overkill enterprise security features just to enforce WIP on sensitive labels. Surely that isn't intentional?

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation and content-related problems and fixes.

[Windows Community](https://answers.microsoft.com/en-us/windows/forum/windows_10-security?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=all&isFilterExpanded=false&page=1) would be a better channel to seek answers to your query.

Thank you.
