### ISSUE TITLE
Unable to use XML on page to import rules

### ISSUE THREAD

**Issue by rp53** [MicrosoftDocs/windows-itpro-docs#5889]
The format of the XML doesn't match what I can export from either GPO or Server 2019 local gpedit.msc. 

I made a few test entries and exported and get a completely different schema that doesn't match the XML above.

Error on import: The specified AppLocker policy cannot be imported. Verify that the policy file is valid and import the policy again. use the error message below to troubleshoot the problem.
Error: The XML policy is invalid for the following reason: The XML root does not match the proper AppLocker policy schema.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d71055e-2b14-227b-0107-c8f150194d5b
* Version Independent ID: 0eab18a0-7e8f-05eb-b47f-e6913682d8e8
* Content: [Microsoft recommended block rules (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@rp53, Will you post the screenshots  of the commands or  editing gpo

**Comment by RAJU2529** [comment]
@rp53 ,  you must the .xml file  in to  .bin file , then only you should  add in gpo

**Comment by MaratMussabekov** [comment]
Hello @rp53 ,
**The format of the XML doesn't match what I can export from either GPO or Server 2019 local gpedit.msc.** - the provided XML has nothing to do with GPO, it is a WDAC policy file. I would recommend to read [this section](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control-deployment-guide) of Microsoft docs for more details.
Thank you
