### ISSUE TITLE
Information about Wifi MFA unlock needs to be corrected

### ISSUE THREAD

**Issue by Matt-C22** [MicrosoftDocs/windows-itpro-docs#5890]
Hi,

I've lost some time on this since in the documentation there's a typo in the example for the Wifi configuration (example #4)

Current version:
"&lt;rule version="1.0"&gt; 
  &lt;signal type="wifi"&gt; 

Correct version should be:
"&lt;rule schemaVersion="1.0"&gt; 
  &lt;signal type="wifi"&gt; 

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f8c2ce-8edb-60d3-ebf9-bdb625bf66dc
* Version Independent ID: ee1ed0a8-b05c-c499-6504-40b5b298c53b
* Content: [Multifactor Unlock - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/feature-multifactor-unlock#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/feature-multifactor-unlock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/feature-multifactor-unlock.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by Matt-C22** [comment]
Any update on this minor change which impacts deployments for users that are unaware of this error in the documentation?
Thanks

**Comment by e0i** [comment]
Closing via merged PR #6823
