### ISSUE TITLE
Pleas eremove reference to ProPlus

### ISSUE THREAD

**Issue by dugatlin** [MicrosoftDocs/windows-itpro-docs#5897]
The Microsoft Office OPK requirements specify that ProPlus only be installed for customers who know they will have an E3 or E5 volume license. The only difference between the default required installation of Home Premium and Pro Plus is the installation of Teams / Skype for Business.

Customers who are using Autopilot with another volume license should not be confused by having a non-applicable icon on the desktop for Teams or Skype for Business. Having those icons present would only confuse the customers.

Please update the page to conform with the Microsoft Office OPK licensing requirements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02d429b1-aae0-6a88-18c0-64fb0f44a655
* Version Independent ID: 46a16877-cc5a-ac92-40b7-5235459d3ea7
* Content: [Windows Autopilot device guidelines - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/autopilot-device-guidelines)
* Content Source: [windows/deployment/windows-autopilot/autopilot-device-guidelines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/autopilot-device-guidelines.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
We want to keep information that Office software is possible and advisable to install if it is a customer need.  I've changed the way this is presented and the topic will update later this afternoon. Let me know if you still think we need to make further changes.

Here is the new text that will publish later today:

Software best practice guidelines for Windows Autopilot

- The Windows Autopilot device should be preinstalled with only a Windows 10 base image plus drivers.
- You can preinstall your licensed version of Office, such as [Office 365 ProPlus](https://docs.microsoft.com/deployoffice/about-office-365-proplus-in-the-enterprise).
- Unless explicitly requested by the customer, no other preinstalled software should be included.
  - Per OEM Policy, Windows 10 features, including built-in apps, should not be disabled or removed.

**Comment by e0i** [comment]
Closing via Greg's commit,

[[324c994 ] editing ProPlus info ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/324c994b186f87cf074265f7b95148c375d2bcd8#diff-e0369febe6cb2cb3a7754bbdbdc76994)

Thank you.
