### ISSUE TITLE
Multiple small updates

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/windows-itpro-docs#5899]
ISSUE 1.) This sentence doesn't make sense:
"This may result in content being either incorrectly."

ISSUE 2.) Please note this page also applies to Win10 1909.

ISSUE 3.) Please move www.microsoft.com to under go.microsoft.com. Go uses www as an intermediary when forwarding clients, and BOTH need to be allowed.

Also, if more description could be added to some of the URLs that would be appreciated. Thanks for your thankless work on this, I've found it very helpful at my employer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d22f6a68-3356-c480-1d1c-05dfa475bc25
* Version Independent ID: 1a96efa2-b98d-cea3-cba0-77a698eabcff
* Content: [Connection endpoints for Windows 10 Enterprise, version 1903 - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1903-endpoints)
* Content Source: [windows/privacy/manage-windows-1903-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/manage-windows-1903-endpoints.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **v-medgar**

**Comment by DaniHalfin** [comment]
@medgarmedgar could you please take a look?
Thanks!

**Comment by illfated** [comment]
> 1. This sentence doesn't make sense: "This may result in content being either incorrectly."

I have looked through the page history here on GitHub. Looks like this issue has been present ever since this page got transferred from the previous location or repository.

https://www.bing.com/search?q=%22This+may+result+in+content+being+either+incorrectly.%22

Search results indicate that other users have deduced the following to be the complete sentence:

> **This may result in content being either incorrectly downloaded or not downloaded at all.**

**Comment by illfated** [comment]
(Ref. #5930 )

**Comment by e0i** [comment]
@SwiftOnSecurity Passing the issue to an independent technical writer for revision. Thank you for providing feedback.

**Comment by illfated** [comment]
(ref. #6331 )

**Comment by illfated** [comment]
Well, that is one door shut for the attempt to say "this page also applies to Win10 1909."

See the comments from 2020-03-08 in https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5930#issuecomment-596158509  and https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5930#issuecomment-596257263 to read more why #6331 was rejected (in addition to the same closing comment without links).

**Comment by e0i** [comment]
Closing via #6418
