### ISSUE TITLE
New and changed functionality

### ISSUE THREAD

**Issue by dcaddick** [MicrosoftDocs/windows-itpro-docs#590]
From my understanding, two of the new functions are: Managed Installer + ISG?
I have found the details on the Managed Installer at:
[https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/deploy-managed-installer-for-device-guard](url)
But so far none on the ISG side - or is this just a case where it ONLY comes into play when the Policy is deployed via SCCM or Intune? It would still be good to get a better technical understanding of how this works... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 481aaad1-c3ed-3eb1-bd29-ebad8f264edd
* Version Independent ID: dc5d9c47-e4aa-22ab-cb41-dfed57c517ac
* Content: [Windows Defender Application Control (WDAC) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control#new-and-changed-functionality)
* Content Source: [windows/security/threat-protection/windows-defender-application-control.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control.md)
* Service: **unspecified**
* GitHub Login: @jsuther1974
* Microsoft Alias: **justinha**

**Comment by jsuther1974** [comment]
We are working on a major revision to WDAC content and that will include a new topic on ISG.

**Comment by ckuchinski** [comment]
Has there been any update on the WDAC revision?

**Comment by Justinha** [comment]
Sorry, the new ISG topic is still being drafted by our engineering partners.

**Comment by ckuchinski** [comment]
When can we expect the new WDAC revision or any new information related to WDAC?

**Comment by Justinha** [comment]
@ckuchinski we published another ISG topic, using PS and come conceptual info about ISG too: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-intelligent-security-graph

**Comment by Justinha** [comment]
@dcaddick sorry I  meant to added you too. fyi on a new topic, link above.

**Comment by dcaddick** [comment]
@Justinha Just curious if this has had any changes?

**Comment by Justinha** [comment]
@dcaddick there are a couple new topics: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-dynamic-code-security and https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/querying-application-control-events-centrally-using-advanced-hunting 

We also plan to cover how to block Store apps and upcoming improvements like multiple policies per device and support for rules based on file path.

**Comment by dcaddick** [comment]
@Justinha Is there a TAP (Technology Adoption Program) for Application Control?
I could be wrong, but my concern is that while it is possible to drive the policy via ISG *or* Managed Installer *or* a manual policy it does not appear to be able to incorporate 2 or all 3 methods - you can only choose one?
Happy to be proved wrong - but this means that you cannot make allowances for In-House apps while using ISG - and that is just the easiest example...
