### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by Soqotra91** [MicrosoftDocs/windows-itpro-docs#5901]
Hello,

I have followed the tutorial to setup Windows Hello for Business for Azure AD Joined machines and used the certificates way to do so. I followed every single step from page: https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base

I'm getting the following error on my laptop:
![image](https://user-images.githubusercontent.com/56262303/72966084-46418100-3dbe-11ea-841c-4a057c295959.png)

Does anyone know what the problem could be here?

Sincerely,

Stefan

**Comment by RAJU2529** [comment]
if possible  export the certificate from the smart card , and then view details in the certificate , 

Domain details are not available

**Comment by Soqotra91** [comment]
Hi RAJU, 

Thank you, my issue has been solved. The connectivity to the DC was not fully working.
