### ISSUE TITLE
Ignoring/closing notifications by pressing escape

### ISSUE THREAD

**Issue by sdxfuj** [MicrosoftDocs/windows-itpro-docs#5902]
I've noticed that it is possible to dismiss these notifications by pressing escape, including the last one that requires immediate restart. If those notifications are dismissed by pressinc Esc, when will a restart actually take place? Also, these notifications happen repeatedly every few minutes while the computer is plugged in, but not if the computer is running on battery power. Please describe/clarify the behavior in both AC and battery power scenarios. So far I've managed to dismiss these messages for approx 2 hours without a forced restart actually taking place by just pressing Esc every time a notification pops up. Version 1909 - build 18363.535 is the version that I'm testing with.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44aabe97-360e-0655-09ec-5d1e352bdb1a
* Version Independent ID: 1c729c42-741d-ecb7-6490-a4bfdd029263
* Content: [Enforce compliance deadlines with policies in Windows Update for Business (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/wufb-compliancedeadlines)
* Content Source: [windows/deployment/update/wufb-compliancedeadlines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/wufb-compliancedeadlines.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by e0i** [comment]
Hello, @- thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
