### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by DTGitRepository** [MicrosoftDocs/windows-itpro-docs#5904]
The destination of the link "How to Use The Same External Ethernet Adapter For Multiple SCCM OSD" is dead, would this be updated to an archived version or to a more recent source please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cd6c1f5-529c-4b6a-6d70-6a091df10f3e
* Version Independent ID: df97fced-4167-f5d8-8643-50cbb1ba69e4
* Content: [Ethernet adapters and Surface deployment (Surface) - Surface](https://docs.microsoft.com/en-us/surface/ethernet-adapters-and-surface-device-deployment#feedback)
* Content Source: [devices/surface/ethernet-adapters-and-surface-device-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/ethernet-adapters-and-surface-device-deployment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
**Bing search for "How to Use The Same External Ethernet Adapter For Multiple SCCM OSD":**
- https://www.bing.com/search?q=%22How+to+Use+The+Same+External+Ethernet+Adapter+For+Multiple+SCCM+OSD%22

**Promising result:**
- https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/how-to-use-the-same-external-ethernet-adapter-for-multiple-sccm/ba-p/257374

Old & broken link:
> https://blogs.technet.microsoft.com/askpfeplat/2014/07/27/how-to-use-the-same-external-ethernet-adapter-for-multiple-sccm-osd/

**Comment by RAJU2529** [comment]
@illfated , i think author will not merge if i  add techcommunity.microsoft.com link in PR

**Comment by illfated** [comment]
Fair point. Your assumption may be correct. We may have to wait for feedback regarding what needs to be done here. I mostly commented because I wanted to point the OP to a page with a possible solution if needed, even though it may not be a useful solution to the issue of the broken link.

**Comment by e0i** [comment]
An independent contributor will publish a PR for the dead link. Thank you.

**Comment by VLG17** [comment]
@illfated @RAJU2529 i don't see any issue with adding the link you found as replacement. It's on a official Microsoft domain, written by a Microsoft employee and it addresses the issue. I'll create a PR and ad it.

**Comment by RAJU2529** [comment]
@VLG17 . I wll be waiting for the result. If the new link is merged means, if I create on coming PR , I will consider techcommunity also.

**Comment by illfated** [comment]
(Ref. PR #6722 )

**Comment by e0i** [comment]
Closing via #6722. Thank you.
