### ISSUE TITLE
Is "Key Storage Provider" a requirement for domain controller certificates for windows hello for business to work?

### ISSUE THREAD

**Issue by Neenisharma** [MicrosoftDocs/windows-itpro-docs#5918]
for windows hello for business to work, it is a requirement to have the domain controller certificates to use a cryptography that is "Key Storage Provider". will windows hello for business not work with "legacy cryptography service provider "?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a2341a7-208e-b60b-c8d2-041bab39a630
* Version Independent ID: c790a99e-fcde-e9d5-1514-9c2bd328053f
* Content: [Validate Public Key Infrastructure - key trust model (Windows Hello for Business) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-key-trust-validate-pki)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-key-trust-validate-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-key-trust-validate-pki.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by MaratMussabekov** [comment]
Hello @Neenisharma ,
yes, it is a requirement, as Windows Hello for Business uses Microsoft Software Key Storage Provider and Microsoft Smart Card Key Storage Provider, which are provides from "Key Storage Provider" category.
Thank you
