### ISSUE TITLE
Adoption Order Rank

### ISSUE THREAD

**Issue by pieterhancke** [MicrosoftDocs/windows-itpro-docs#5919]
I am curious about the Not applicable comment for AIR and MTE in the Adoption Order Rank. For AIR you still need to consider which Machine Groups you want to enable automation for and to what level you are going to allow automatic responses. Does not applicable imply that AIR should not be considered for adoption? My preference is to enable early on, but in semi (approval) automation. Similarly MTE - my view is this can be used as soon as you have adopted EDR. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7903e2a8-2f3d-daf0-27c4-7397631d96e3
* Version Independent ID: 4ca86831-6873-c391-1fe6-fb13914ee104
* Content: [Prepare Microsoft Defender ATP deployment - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/prepare-deployment#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/prepare-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/prepare-deployment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by joinimran** [comment]
Hello @pieterhancke - Thank you for your feedback these are recommended as the best practices. If the organization feels that these should be implemented during the adoption phase they can implement these. For some organizations, it becomes complex to adopt this during the adoptions and make things more complex.

Imran.

**Comment by mypil** [comment]
@pieterhancke - From our understanding, the issue you raised has been answered by joinimran so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
