### ISSUE TITLE
ASR settings in Audit only mode?

### ISSUE THREAD

**Issue by dcaddick** [MicrosoftDocs/windows-itpro-docs#5920]
What about the use of applying ASR settings in Audit only mode to ensure less disruption?
We have issues where applying Cred Guard can break Forms - so the understanding is that those settings that can be enabled in Audit Only mode should be - then reviewed after 2 weeks and then be applied...?

We are assuming that the settings are available  in Audit Only mode for a reason?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7903e2a8-2f3d-daf0-27c4-7397631d96e3
* Version Independent ID: 4ca86831-6873-c391-1fe6-fb13914ee104
* Content: [Prepare Microsoft Defender ATP deployment - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/prepare-deployment)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/prepare-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/prepare-deployment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by joinimran** [comment]
Hello @dcaddick You are right, the Audit mode is available to evaluate how the ASR will impact your organization. If things are satisfied and not breaking something, then you can proceed to enable these functions. You can see more details at https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/enable-attack-surface-reduction

Thanks.
Imran.

**Comment by mypil** [comment]
@dcaddick - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by joinimran so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
