### ISSUE TITLE
Multiple Autopilot Profiles for same device

### ISSUE THREAD

**Issue by MaxSCCM** [MicrosoftDocs/windows-itpro-docs#5923]
Hello,
From the documentation it is not clear what will happen if more than one profile targeted to a device. Which profile will take priority?

**Comment by mypil** [comment]
@MaxSCCM - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by MaxSCCM** [comment]
Hi, thank you for your attention. There is no link, because this situation is not explained in the documentation. Or I wasn't able to find the explanation. It would be good if situation with multiple Autopilot profiles was explained somewhere in the docs. I suppose it should be there https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/profiles
Thank you.

**Comment by VLG17** [comment]
@MaxSCCM I must say that adding the same device to multiple Autopilot profiles is not something one should be doing. Although possible, that should be avoided.

As far as i know, there is no rule in place for applying a certain profile. After establishing internet connectivity, the device will download the Windows Autopilot profile from the Autopilot deployment service, but there is no logic in place to specify which profile to download.

For an official statement, i recommend [opening a support ticket](https://support.microsoft.com/en-us).

**Comment by mypil** [comment]
@MaxSCCM  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
