### ISSUE TITLE
clarification needed

### ISSUE THREAD

**Issue by Cweber42** [MicrosoftDocs/windows-itpro-docs#5925]
Please clarify where you find the EAP menu, with steps and screenshots. This will help with troubleshooting the certificate verification on the NPS server side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52fa26a8-efe0-9d8d-eef8-eb8fa7b2e640
* Version Independent ID: f217d015-3ccb-decd-ad07-29e07c4d2760
* Content: [Advanced Troubleshooting 802.1X Authentication - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/advanced-troubleshooting-802-authentication#feedback)
* Content Source: [windows/client-management/advanced-troubleshooting-802-authentication.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/advanced-troubleshooting-802-authentication.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@Cweber42 - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/5192ecd97f08a9f7d3c22e205d4bfaf4e9b3437f. 


Thank you for your contribution to make the docs better! Much appreciated!
