### ISSUE TITLE
Potentially unwanted app blocking not available on new Edge

### ISSUE THREAD

**Issue by jim-liu** [MicrosoftDocs/windows-itpro-docs#5928]
In Edge 79.0.309.71, there is no **Potentially unwanted app blocking** under Settings > Privacy and services > Services. Only available toggles are **Use a web service to help resolve navigation errors** and **Microsoft Defender SmartScreen**.

**Comment by beerisgood** [comment]
Isn't that included in Smartscreen?

Maybe you need enable PuP protection in defender (with Powershell)

**Comment by jim-liu** [comment]
Obviously not included in SmartScreen, as Edge downloaded the fake PUA from https://demo.smartscreen.msft.net/ just fine.

From [Microsoft Edge - Policies](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#smartscreenpuaenabled), it seems that the UAP option is only available in version 80 or later.

**Comment by RAJU2529** [comment]
I am using version 80. Today I will check

**Comment by RAJU2529** [comment]
@jim-liu .  You said feature is available  on Version 80.0.361.48 (Official build) (64-bit)

here is the screenshot
![Capture](https://user-images.githubusercontent.com/3296790/74239787-8e3d2f00-4cfe-11ea-948f-ea2a4ea75420.JPG)

**Comment by e0i** [comment]
It seems that the question has already been answered by the community and thus the is being marked as resolved.

Feel free to re-open the issue if you feel it hasn't been resolved.

Thank you for providing feedback.
