### ISSUE TITLE
 Virus #a0 Bedrohungsschutz

### ISSUE THREAD

**Issue by milbrandt** [MicrosoftDocs/windows-itpro-docs#5932]
https://docs.microsoft.com/de-de/windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus

Bei 2. Klicken Sie auf Virus **&** Bedrohungsschutz, und klicken Sie dann auf **B**edrohungsprotokoll.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: de416fda-04fb-6780-6675-020fdc2426ba
* Version Independent ID: ede7f3c1-ba3a-e331-80d8-c992b3d7f9a4
* Content: [Wiederherstellen von in Quarantäne befindlichen Dateien in Windows Defender AV](https://docs.microsoft.com/de-de/windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
Ampersand (&) issue, converted to #a0 in the German page. Please note: there are also a handful of spacing issues in the nearby text:

![image](https://user-images.githubusercontent.com/38162891/73143396-ba6b7580-4099-11ea-86f7-39a4e6692df8.png)

Notice the redundant space before the comma (which by itself is not needed in this sentence in Germanic languages) in line 2.
Line 3: Missing space between "Bedrohungen" and "auf".
Line 4: Missing space between the last 2 words, "Entfernen" and "klicken".

**Comment by TinaMcN** [comment]
@milbrandt @illfated Wir danken Ihnen für die Mitteilung und zusätzlichen Erläuterungen. Das Problem, bei dem das „&“ durch das „#a0“ ersetzt wurde, ist ein bekannter Fehler in unserem maschinellen Übersetzung-Tool, der sich auf mehrere deutsche Artikel ausgewirkt hat. Das MT-Tool-Team hat einen Fix für den Fehler gefunden und wir hoffen, ihn bald in den deutschen Artikeln zu korrigieren.
Das MT-Tool-Team untersucht auch das bekannte Problem der fehlenden Abstände nach fettgedrucktem Text.
(Thank you for reporting this.  Thank you for the extra explanations.  The issue with "&" being replaced by "#a0" is a known issue with our machine translation tool which has been affecting multiple German articles.  The MT tool team has a fix for the issue and we hope to correct it in the German articles soon.     The issue with the missing spacing following bolded text is also known and the MT tool team is investigating.)

**Comment by e0i** [comment]
The issue seems to have been fixed. Thank you.
