### ISSUE TITLE
MakeFolderAvailableOfflineDisabled option

### ISSUE THREAD

**Issue by davidpaMSFT** [MicrosoftDocs/windows-itpro-docs#5936]
This page has a reference to "MakeFolderAvailableOfflineDisabled option". It would be helpful if it included the explanation on how to set this option, e.g. the "Do not automatically make specific redirected folders available offline" group policy setting and/or other(s).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f23c9b6-81aa-b06d-5c19-196ac933b6ff
* Version Independent ID: 0c7eb396-4274-c546-6063-6d38382b956d
* Content: [Limitations while using Windows Information Protection (WIP) (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/limitations-with-wip#feedback)
* Content Source: [windows/security/information-protection/windows-information-protection/limitations-with-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/limitations-with-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@davidpaMSFT  - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/8691efd90870ddf13ffe4e49378c0e1668712b63. 


Thank you for your contribution to make the docs better! Much appreciated!
