### ISSUE TITLE
1st General Question about Wipe

### ISSUE THREAD

**Issue by KingDrewcifer** [MicrosoftDocs/windows-itpro-docs#5937]
The question "If I wipe the machine and restart, will I still receive Windows Autopilot?" According to Intune support, after 30 days of them spinning their wheels, if using hybrid AAD join this is not true. They tell me that it's normal to have to remove the device record from AP and and re-add it using the hash again. This makes no sense but this is what support tells me. Either way, maybe adding a note to this about its relevance to the two scenarios, native and hybrid AAD for Re-Enrollment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2be263b-5134-0e2d-ad25-101e55aeb85a
* Version Independent ID: 43593283-afe8-80d0-38d5-1be447cd50b4
* Content: [Windows Autopilot FAQ - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/autopilot-faq#feedback)
* Content Source: [windows/deployment/windows-autopilot/autopilot-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/autopilot-faq.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by KingDrewcifer** [comment]
You can disregard and close this, someone from the community was able to figure this out for me, its how the domain join profile was deployed. Once I updated it to all devices then the problem went away. Support just gave up and passed the buck as I assumed.

**Comment by mypil** [comment]
@KingDrewcifer - Thank you for submitting feedback and for the confirmation that this issue can be closed. 

If there is a specific area of the docs that we can improve on or if you find any documentation error, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page.
