### ISSUE TITLE
Migrating existing enterprise deployments (1809+)

### ISSUE THREAD

**Issue by plangone22** [MicrosoftDocs/windows-itpro-docs#5939]
It's unclear how newer Win 10 Enterprise activations, done via KMS, should be migrated to Subscription Activation. It doesn't seem to be happening automagically and the only way I can force it is to install a Win 10 Pro Retail KMS key, which I don't think should be required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation#feedback)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by plangone22** [comment]
We've also had success pulling the OEM key and installing it, but that shouldn't be required on 1809 at least based on how I read the above. The retail key seems to no longer be working. Regardless, this should all be automatic.

**Comment by joinimran** [comment]
@plangone22 The details are already mentioned in the document in scenario 2. Please see details at https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation#scenarios

You need to run the mentioned command on all computers or you can create a batch file and run it on the computer via GPO.

**Comment by plangone22** [comment]
I'm asking more about the "Existing Enterprise Deployments" section: https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation#existing-enterprise-deployments
It says for 1803 and later, it's automatic, but I still have a lot of devices on 1803 or later "stuck" using KMS.

**Comment by joinimran** [comment]
@plangone22 - If this is not working as expected and as you have mentioned that there are multiple machines I would suggest you open up a support case with Microsoft. 
Thanks.
@mypil Please share the process to open up a support case with Microsoft.

**Comment by mypil** [comment]
@plangone22 - Thank you for submitting feedback.

Please contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
