### ISSUE TITLE
Update link is for client, not server

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/windows-itpro-docs#5940]
"Before you begin, download the latest hotfix of Microsoft BitLocker Administration and Monitoring (MBAM) **Server** 2.5 SP1"
Note it says server.
The link below is to the **client** updates, not the server updates. `https://www.microsoft.com/download/details.aspx?id=58345`

There is a different link to the latest **server** updates here:
`https://support.microsoft.com/en-us/help/4340040/july-2018-servicing-release-for-microsoft-desktop-optimization-pack`

Can you please have both links and explain how to update an environment since the server and clients are different versions?

Thank you!

**Additional request**: Can we get the MBAM version matrix imported into docs?
`https://docs.microsoft.com/en-us/archive/blogs/dubaisec/mbam-version-chart`
(not a complaint about him maintaining it for free, it's been there for years. Love DubaiSec's blog posts)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67626969-2854-3925-fc2d-9d8a09183796
* Version Independent ID: f442462e-6e55-406d-9a77-4e98e6dc036f
* Content: [Applying hotfixes on MBAM 2.5 SP1 - Microsoft Desktop Optimization Pack](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/apply-hotfix-for-mbam-25-sp1)
* Content Source: [mdop/mbam-v25/apply-hotfix-for-mbam-25-sp1.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/mdop/mbam-v25/apply-hotfix-for-mbam-25-sp1.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by MaratMussabekov** [comment]
Dear @SwiftOnSecurity ,
please have a look at the PR #6026 
Thank you

**Comment by MaratMussabekov** [comment]
I added the link for the chart and replaced the download link (I do not think that old link should be preserved as article is about server update)
Thank you

**Comment by mypil** [comment]
@SwiftOnSecurity - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/d7c55abbeab83598dcc3eac0ce9b3485ae8a0d18. 


Thank you for your contribution to make the docs better! Much appreciated!
