### ISSUE TITLE
This page is incorrect - Separate Intune License Required

### ISSUE THREAD

**Issue by marksburgess** [MicrosoftDocs/windows-itpro-docs#5941]
Under Licensing Requirements it says: "Microsoft 365 Enterprise E3 or E5 subscriptions, which include all Windows 10, Office 365, and EM+S features (Azure AD and Intune)." Enterprise E3 in fact does not provide Intune sufficient to assign a user with an Office365 E3 license to a device under Endpoint Management: Home/Devices/Enroll devices - Windows enrollment/Windows Autopilot devices.  .  The error is "Assignment Failed: XXX@domain.com is not licensed to use Intune."  A separate Intune or Mobility E3 license is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aafc065-6ee6-e3cf-31ba-ab3dd277fb23
* Version Independent ID: 35d3102e-4ff7-9408-8dbd-513b7dfff5c0
* Content: [Windows Autopilot requirements - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-requirements#feedback)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/windows-autopilot-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by MaratMussabekov** [comment]
Hello @marksburgess,

**Enterprise E3 in fact does not provide Intune sufficient to assign a user with an Office365 E3 license to a device under Endpoint Management: Home/Devices/Enroll devices - Windows enrollment/Windows Autopilot devices. . The error is "Assignment Failed: XXX@domain.com is not licensed to use Intune."** - yes, Office 365 E3 license is not enough, you need add both Office 365 E3 and EMS (it is not stated in the article that Office 365 E3 would be enough)
**A separate Intune or Mobility E3 license is required.** - no need for any separate licenses, EMS is a part of Microsoft 365 E3

It also applicable for Microsoft 365 E5 - you need to assign user both Office 365 and EMS licenses

I will add a note to the article to make it less confusing.

Thank you

**Comment by illfated** [comment]
(Ref. PR **added note** #5980 )

**Comment by mypil** [comment]
@marksburgess - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/289dfd546da66f29e397f09dbddd70398db8ee44. 


Thank you for your contribution to make the docs better! Much appreciated!
