### ISSUE TITLE
Any instructions for config required for "Share with multiple people, all using the same account" section?

### ISSUE THREAD

**Issue by Wes777** [MicrosoftDocs/windows-itpro-docs#5948]
The section on "Share with multiple people, all using the same account" doesn't show any configuration required to enable this. Is there any config required?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611f8602-39dc-0572-624a-5dff681ec8c1
* Version Independent ID: be00b186-0bf0-713b-4034-397f8b9c5fae
* Content: [Share your HoloLens with multiple people](https://docs.microsoft.com/en-us/hololens/hololens-multiple-users#feedback)
* Content Source: [devices/hololens/hololens-multiple-users.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/hololens-multiple-users.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by joinimran** [comment]
Hello @Wes777 Please see https://docs.microsoft.com/en-us/hololens/hololens-identity#setting-up-multi-user-support-aad-only where it is describing to setup multiple-user support.

Thanks.
Imran.

**Comment by mypil** [comment]
@Wes777 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by joinimran so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
