### ISSUE TITLE
Typos in the Adoption section

### ISSUE THREAD

**Issue by chhatley** [MicrosoftDocs/windows-itpro-docs#5949]
There are a lot of typos in the adoption section of this page. I didn't read the other sections, but I think it could use some proofreading. Here is an example: 

In many cases**_,_**organizations will have existing endpoint security products in place...…. But in some cases an organization might also already **_implanted_** an EDR solution.

**Comment by illfated** [comment]
OK, I see. You are talking about the page
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/prepare-deployment.md
(same as the Microsoft Docs page https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/prepare-deployment).

**Comment by illfated** [comment]
Very well. I see what you mean. The section 
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/prepare-deployment#adoption-order
may have been the result of the author writing down what he or she was "thinking aloud", so to speak. It is factual, of course, but not necessarily the best text flow, readability-wise.

I will open a Pull Request to have that page text amended, so feel free to add suggestions for improvements to the same page as the PR develops.
