### ISSUE TITLE
Create the BitLocker Group Policy - Step 3c not clear

### ISSUE THREAD

**Issue by yatesa** [MicrosoftDocs/windows-itpro-docs#5951]
Under Create the BitLocker Group Policy, Step 3c is not completely clear as it says: -

Enable the Configure TPM platform validation profile for native UEFI firmware configurations policy. **Computer Configuration / Policies / Administrative Templates / System / Trusted Platform Module Services**

The first sentence is clear, but it then just goes on and lists another GPO path. What are we meant to do in this path "Computer Configuration / Policies / Administrative Templates / System / Trusted Platform Module Services" if anything? If not why is the path even shown?

**Comment by RAJU2529** [comment]
@yatesa . Could you tell me , on which content you finding issues

**Comment by yatesa** [comment]
Sorry must have click wrong link, thought it automatically linked to the page in question.
It's this page: -
https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/set-up-mdt-for-bitlocker

**Comment by RAJU2529** [comment]
@yatesa . That article belongs windows server , So  i am not a server user. So wait for few days , Let windows server expert users will  give clarification.

**Comment by e0i** [comment]
Closing via merged PR #6792
