### ISSUE TITLE
Timeline for Windows 10 Fall Creators Update for Surface Hub (Build 16299)?

### ISSUE THREAD

**Issue by naresh1990** [MicrosoftDocs/windows-itpro-docs#5952]
What is the timeline to get Windows 10 Fall Creators Update for Surface Hub (Build 16299)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c83a996d-3a4e-33d4-82f9-f4112f42d6a1
* Version Independent ID: 69d3e586-1a9d-9a20-8ea0-54f356b5693a
* Content: [Surface Hub update history - Surface Hub](https://docs.microsoft.com/en-us/surface-hub/surface-hub-update-history#feedback)
* Content Source: [devices/surface-hub/surface-hub-update-history.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/surface-hub-update-history.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @v-miegge
* Microsoft Alias: **v-miegge**

**Comment by MaratMussabekov** [comment]
Hello @naresh1990,
Windows 10 1709 is not released for Surface Hub yet, you may follow release announcements on [Microsoft blog](https://blogs.microsoft.com/)
Thank you

**Comment by mypil** [comment]
@naresh1990 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
