### ISSUE TITLE
FQC-09478 WinPro 10 SNGL OLP NL Legalization GetGenuine

### ISSUE THREAD

**Issue by alsolaih** [MicrosoftDocs/windows-itpro-docs#5954]
If this license in title installed on a PC and after few months customer needs to replace that the whole PC, or replace HDD, IS Windows can be installed again with same license?

**Comment by MaratMussabekov** [comment]
Hello @alsolaih,
yes, you can use this license to reinstall OS on the new PC, as it is retail, not OEM license.
Thank you

**Comment by mypil** [comment]
@alsolaih - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
