### ISSUE TITLE
Out of scope

### ISSUE THREAD

**Issue by jdoles** [MicrosoftDocs/windows-itpro-docs#5955]
Since this is out of scope - could a link to where additional information be provided?  I can't seem to find much digging around the internet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8588429-f942-5930-5db5-2f6f9e4a8139
* Version Independent ID: 3bf4dabe-0f58-2566-a131-14916e645f16
* Content: [Audit Filtering Platform Policy Change (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-filtering-platform-policy-change#feedback)
* Content Source: [windows/security/threat-protection/auditing/audit-filtering-platform-policy-change.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/audit-filtering-platform-policy-change.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @jdoles,
You can use [Windows Server 2008 R2](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd349801(v=ws.10))  section, it contains description of all the events (you can search by entering event id in "filter by title" field)

Also, i think these notes "This subcategory is outside the scope of this document" should be removed (I will create the PR), as they carry no meaning.

Thank you

**Comment by mypil** [comment]
@jdoles - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/1eb8ed20e7ca74052724149f43ea908e0cd94656. 


Thank you for your contribution to make the docs better! Much appreciated!
