### ISSUE TITLE
Invalid Link

### ISSUE THREAD

**Issue by JWeavis** [MicrosoftDocs/windows-itpro-docs#5957]
Microsoft Desktop virtualization site = https://www.microsoft.com/server-cloud/products/virtual-desktop-infrastructure/
We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available.

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84fc852e-4ce0-1d6d-fbc8-76732407e576
* Version Independent ID: 30d715c0-35f0-0b52-68da-75a5f85a619b
* Content: [Windows Defender Antivirus VDI deployment guide - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/deployment-vdi-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/deployment-vdi-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/deployment-vdi-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @JWeavis. Sorry you ran into a broken link. Thank you so much for letting us know about this. The correct link is https://docs.microsoft.com/azure/virtual-desktop. I've updated the article but it might take a day or three for the changes to render.
