### ISSUE TITLE
Asset Tag link is 404

### ISSUE THREAD

**Issue by Typhoon87** [MicrosoftDocs/windows-itpro-docs#5958]
At the top of this page the "Asset Tag – The asset tag is assigned to the Surface device with the Asset Tag Tool." link does not exist goes to a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5149561d-359f-875d-73c8-f14b2cfa8f80
* Version Independent ID: d465734d-6480-b7ed-6ca0-168e7b989063
* Content: [Manage Surface UEFI settings (Surface) - Surface](https://docs.microsoft.com/en-us/surface/manage-surface-uefi-settings)
* Content Source: [devices/surface/manage-surface-uefi-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/manage-surface-uefi-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@Typhoon87 - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/38112790d236491ce7d0c03025321cd65c065631. 


Thank you for your contribution to make the docs better! Much appreciated!
