### ISSUE TITLE
Alerts for different versions of Windows

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#5961]
will we get the same alerts for Win 10 1507 LTSB as for 1909? If so, please state this, if not, please provide a table that shows us what to alerts to expect for the various releases. We don't want to waste time looking for something on an old system that won't get generated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c994c48-0f75-bbb5-165a-b8272ba49596
* Version Independent ID: 5e8b885c-e070-0f60-98f0-34611c8967b2
* Content: [Investigate machines in the Microsoft Defender ATP Machines list - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/investigate-machines)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/investigate-machines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/investigate-machines.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@mjcaparas - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by mjcaparas** [comment]
The team is actively working on back porting detection capabilities to supported versions.
