### ISSUE TITLE
Microsoft Access documentation?

### ISSUE THREAD

**Issue by ssccaavvookk** [MicrosoftDocs/windows-itpro-docs#5962]
I cannot find any documentation on Microsoft Access database application. It's a part of the Office 365 ProPlus package, but it is not mentioned on this page or included in the xml files. I'm using the "Office-365-ProPlus-1810-Allowed.xml" recommended app rule that's listed in Intune. I'm not having any success manually adding it as a protected desktop app using the information provided by powershell Get-AppLockerFileInformation (O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US\MICROSOFT OFFICE\MSACCESS.EXE,16.0.12430.20184). It's also not getting logged in the "App learning report for WIP" even when it's getting blocked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ed0150-0172-f3ad-3c7f-3a7141efbe64
* Version Independent ID: 6a978d2b-a0ff-1052-ce00-06f02f30cfa1
* Content: [List of enlightened Microsoft apps for use with Windows Information Protection (WIP) (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip#feedback)
* Content Source: [windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Does this library have what you need: https://docs.microsoft.com/en-us/office/client-developer/access/access-home

**Comment by ssccaavvookk** [comment]
> Does this library have what you need: https://docs.microsoft.com/en-us/office/client-developer/access/access-home

No, that is for software development purposes to gain access to data within an Access database. My issue is getting Access as a desktop application to function in an enterprise context so "work" databases can be accessed on devices with a Windows Information Protection policy being applied.

**Comment by ssccaavvookk** [comment]
Access works when the Get-AppLockerFileInformation info is added to the exempt list. So maybe it needs to be listed in this documentation with Skype for Business? Or with Visio and Project?

**Comment by mypil** [comment]
@ssccaavvookk - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/68b1546dcc4d3cffd01f5637512646206fcd1485. 


Thank you for your contribution to make the docs better! Much appreciated!
