### ISSUE TITLE
On Access Protection

### ISSUE THREAD

**Issue by nathanmcnulty** [MicrosoftDocs/windows-itpro-docs#5964]
This is very unclear, and in InTune, the option is Block or Not Configured. Could someone please spend some time clarifying this?

Allows or disallows Windows Defender On Access Protection functionality.

ADMX Info:

    GP English name: Monitor file and program activity on your computer
    GP name: RealtimeProtection_DisableOnAccessProtection
    GP path: Windows Components/Windows Defender Antivirus/Real-time Protection
    GP ADMX file name: WindowsDefender.admx

The following list shows the supported values:

    0 – Not allowed.
    1 (default) – Allowed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b1ab2e-1964-5580-7c99-4bd4cd480075
* Version Independent ID: f7b5da46-04cb-3501-65fa-870a3c6f09b8
* Content: [Policy CSP - Defender - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-defender.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-defender.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @nathanmcnulty,
could you please clarify which intune option you are talking about?
as far as I can see "Monitor file and program activity on your computer" has values "yes" or "no"
Thank you

**Comment by nathanmcnulty** [comment]
Hey @MaratMussabekov , there are two settings in InTune:

![image](https://user-images.githubusercontent.com/6653432/74097096-e684ee80-4abc-11ea-8578-632d5e176b97.png)
![image](https://user-images.githubusercontent.com/6653432/74097102-fc92af00-4abc-11ea-8243-8a3062c20a9e.png)

On the [docs](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#defender-allowonaccessprotection), I see this for the On Access Protection section:
![image](https://user-images.githubusercontent.com/6653432/74097112-3663b580-4abd-11ea-9d48-1adb73673bdd.png)

Are the two settings in the images combined into the one On Access Protection CSP, or is the ADMX Info - English name information incorrect and the actual "Monitor file and program activity on your computer" CSP is missing from the page?

Also, in the On Access Protection image, I have an option of Block or Not Configured... What exactly am I blocking? And to make it more confusing, the docs for the [defender security baselines](https://docs.microsoft.com/en-us/intune/protect/security-baseline-settings-defender-atp) says it sets it to Enabled with a default of Yes...
![image](https://user-images.githubusercontent.com/6653432/74097246-c22a1180-4abe-11ea-8b92-1aeabc118a0f.png)

**Comment by MaratMussabekov** [comment]
Hello @nathanmcnulty,
this naming is kind of confusing )
"Monitor file and program activity" feature from your first screenshot is [RealTimeScanDirection](https://docs.microsoft.com/windows/client-management/mdm/policy-csp-defender#defender-realtimescandirection) from the original article, and is named "Configure monitoring for incoming and outgoing file and program activity" in GP

"On Access Protection" feature from your second screenshot is [AllowOnAccessProtection](https://docs.microsoft.com/windows/client-management/mdm/policy-csp-defender#defender-allowonaccessprotection) from the original article, and is named "Monitor file and program activity on your computer" in GP

So yes, second screen shows it correctly. According to [this article](https://docs.microsoft.com/intune/configuration/device-restrictions-windows-10):
_On Access Protection: **Block** prevents scanning files that have been accessed or downloaded. Users can't turn it on.
When set to **Not configured** (default), Intune doesn't change or update this setting. If you block the setting and then change it back to Not configured, Intune leaves the setting in its previously OS-configured state. By default, the OS enables this feature and allows users to change it.
Intune doesn't turn on this feature. To enable it, use a custom URI._

According to this, using intune configuration policy you can only turn this feature off or leave it as it was pre-configured.

Thank you

**Comment by mypil** [comment]
@nathanmcnulty  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by icelava** [comment]
I am confused how [On Access Protection] relates to [Real-time monitoring] ? Isn't the act of accessing a file (and protecting against it) part of real-time monitoring work Windows Defender must perform?
