### ISSUE TITLE
Still seeing secure score

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#5965]
I am still seeing the secure score page, it has been 5 months, which is much longer than the few weeks mentioned above. Has something changed in the plans to deprecate that page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e17e8994-077f-4042-b478-edbbc23a5687
* Version Independent ID: 847bfd6e-eaf0-acf3-d57e-f5c1fbcdad70
* Content: [Overview of Secure score in Microsoft Defender Security Center - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/overview-secure-score)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/overview-secure-score.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/overview-secure-score.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@mjcaparas - Can you please share your insights on this issue?


Thank you.

cc: @kenwith

**Comment by mjcaparas** [comment]
@DulceMontemayor please see comments

**Comment by nam31** [comment]
@DeanGross The article has been updated.
The issue is being closed since your question seems to be answered. Feel free reach out again if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
