### ISSUE TITLE
Edge option name

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/windows-itpro-docs#5970]
Is "Block potentially unwanted apps"  not "Potentially unwanted app blocking".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b27975a-fa49-d9cd-d500-792448c57f9e
* Version Independent ID: 21c3eb7b-065a-b68a-8a88-dfce45571b0d
* Content: [Block potentially unwanted applications with Windows Defender Antivirus - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/detect-block-potentially-unwanted-apps-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/detect-block-potentially-unwanted-apps-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/detect-block-potentially-unwanted-apps-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
I can't find any of those settings, but I have most likely overlooked something important. Are those settings only visible while  using MSDATP or Enterprise environments?

![image](https://user-images.githubusercontent.com/38162891/73613554-3b28f500-45f7-11ea-944d-1dbe7cd93f56.png)

![image](https://user-images.githubusercontent.com/38162891/73613542-10d73780-45f7-11ea-9299-417b0d88fbd6.png)

**Comment by BR77BE** [comment]
It's present in the Dev channel build (for everyone, I presume).

**Comment by illfated** [comment]
Thank you for your reply. I am thinking that maybe the Dev channel version might not be considered official enough as reference to what the official documentation should contain. Then again, I could easily be wrong with this assumption. I will wait for feedback from other users in more direct contact with this topic.

**Comment by RAJU2529** [comment]
@BR77BE . I have already enabled  that option  in edge browser.

**Comment by BR77BE** [comment]
The "Block potentially unwanted apps" option is now available in Microsoft Edge for all channels, so can this documentation be corrected please?

**Comment by RAJU2529** [comment]
@illfated . Please review the PR #6041

**Comment by illfated** [comment]
PR #6041 is now merged into the public branch and will appear on the docs.microsoft.com page within a week from now (maybe sooner).

#please-close

**Comment by e0i** [comment]
Closing via #6041 

cc: @mypil
