### ISSUE TITLE
Preference to exclude process is missing

### ISSUE THREAD

**Issue by stalsberg** [MicrosoftDocs/windows-itpro-docs#5974]
You can exclude processes from Defender, but the example preferences doesn't contain an example for that exclusion type. Is that missing in the documentation or is it not supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5c929d-414f-70b8-c687-e9a60ef709e3
* Version Independent ID: a3cde3f5-e7a1-e0cc-aeae-fd6123f696c5
* Content: [Set preferences for Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-preferences)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-preferences.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-preferences.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Dear @stalsberg,
The article was updated (https://github.com/MicrosoftDocs/windows-itpro-docs/commit/bfc106698511cacfc914ff3eb742ffdfb4eea809#diff-c95fbcec3822346b56035939615d02a1), you can exclude processes by using "excludedFileName":
```
 <dict>
    <key>$type</key>
    <string>excludedFileName</string>
    <key>name</key>
    <string>cat</string>
</dict>
```
Thank you

**Comment by mypil** [comment]
@stalsberg - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
