### ISSUE TITLE
Bad Characters in Powershell Example about E:\MigData

### ISSUE THREAD

**Issue by joyel24** [MicrosoftDocs/windows-itpro-docs#5976]
X : New-SmbShare ?Name MigData$ ?Path E:\MigData -ChangeAccess EVERYONE
✓ : New-SmbShare -Name MigData$ -Path E:\MigData -ChangeAccess EVERYONE  
It appears to the same for all Languages

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 02b1bc65-2fe1-1345-bc9b-350941a1f24f
* Version Independent ID: 323c1e71-b684-0162-c0f8-a618d91c05c0
* Content: [Remplacer un ordinateur Windows7 par un ordinateur Windows10 (Windows10)](https://docs.microsoft.com/fr-fr/windows/deployment/deploy-windows-mdt/replace-a-windows-7-computer-with-a-windows-10-computer#feedback)
* Content Source: [windows/deployment/deploy-windows-mdt/replace-a-windows-7-computer-with-a-windows-10-computer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/replace-a-windows-7-computer-with-a-windows-10-computer.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
The dashes are correct.  
I don't know how the question marks got in the topic.

All topics in this article are currently being rewritten.  It will take another couple days to republish.  I'll fix this question mark for now.

**Comment by greg-lindsay** [comment]
FYI, the English version will republish right away, the localized versions will take longer.
