### ISSUE TITLE
Doc needs updating for HoloLens 2

### ISSUE THREAD

**Issue by KevinKennedy** [MicrosoftDocs/windows-itpro-docs#5978]
HoloLens 2 only shows up as an option in the store version of the Windows Configuration Designer.  The other download option should be removed or noted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3248f36b-deaf-9562-a030-f3d28ae7e215
* Version Independent ID: 39b1ac9b-fa52-b52d-e970-de1c19ed1c81
* Content: [Configure HoloLens using a provisioning package (HoloLens)](https://docs.microsoft.com/en-us/hololens/hololens-provisioning)
* Content Source: [devices/hololens/hololens-provisioning.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/hololens-provisioning.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
@KevinKennedy Can you please explain what do you mean by "The other download option should be removed or noted."

Or can you please confirm what portion of the document needs updating. This is true that HoloLens 2 only shows as an option in the App to select and continue further. 

Thanks.
Imran.

**Comment by mypil** [comment]
@KevinKennedy   - Can you please respond to the query of joinimran?

Thank you.

**Comment by KevinKennedy** [comment]
Option 2 in the text below will give you a Windows Configuration Designer without HoloLens 2 capabilities.  It should just be downloaded from the store.


1. Install Windows Configuration Designer on your PC. (There are two ways to do this).
Option 1: From Microsoft Store
Option 2: From the Windows Assessment and Deployment Kit (ADK) for Windows 10. If you install Windows Configurations Designer from the Windows ADK, select Configuration Designer from the Select the features you want to install dialog box.

**Comment by mypil** [comment]
@KevinKennedy - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/a3885940c41393f5b502f164ee0f969a1a764171.


Thank you for your contribution to make the docs better! Much appreciated!
