### ISSUE TITLE
 ADFS typo

### ISSUE THREAD

**Issue by grex86** [MicrosoftDocs/windows-itpro-docs#598]
Under "Device Registration" Active Directory Federation Services should be shortned ADFS and not AFFS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5739fab2-c6db-a7a9-b0e7-2bf4b85912a7
* Version Independent ID: 82c58053-c1d7-d938-1b0f-f3f7f70ada3b
* Content: [Planning a Windows Hello for Business Deployment](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-planning-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-planning-guide.md)
* Service: **unspecified**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by MikeStephens-MS** [comment]
Fixed-- thanks for the call out. Should publish soon
