### ISSUE TITLE
Device owner consent should always override Device user consent

### ISSUE THREAD

**Issue by sebastiannielsen** [MicrosoftDocs/windows-itpro-docs#5987]
I personally think this should be reworded:
"Software should not include an option that configures it to hide activities associated with storing or transmitting your data."

to:
"Software may include options for hiding activities associated with storing or transmitting data, but these options must be manually activated by the user and may never be pre-checked or pre-enabled at software installation. An example of acceptable behaviour is to have a non-checked checkbox "Do not show this dialog again", which, upon checking it, will store the choice ("Consent" or "No Consent" to data collection) and always apply that choice, and never show the dialog again."

I do understand that this means a computer owner could install a spyware, and then potentially spy on other people that uses the same computer, but if you use a computer which is not yours, you cannot demand to software developers to have to consent to data collection. You can sometimes require it from the computer owner (if the computer owner is an organization and are bound by GDPR) but not directly from the software owner.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b16da7d1-e552-e274-9406-5390252b0c04
* Version Independent ID: d0c9b8a8-4fba-4ea8-cfdd-6ae6d67a2e19
* Content: [How Microsoft identifies malware and potentially unwanted applications - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/criteria#feedback)
* Content Source: [windows/security/threat-protection/intelligence/criteria.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/criteria.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by RAJU2529** [comment]
If the user purposely install malwares on other computers which does not protected by windows defender or antivirus softwares. then the data will be compromised. 
So that's why Microsoft Gives safety precautions to all administrators , should restrict the users to installing softwares by giving only guest account.
As

**Comment by levinec** [comment]
Hi, thank you for your suggestion. According to the PM, we understand the feedback. However, this scenario was considered when defining this criteria and this is what we wanted. We do not allow apps that collect and transmit your activities or data to have a “stealth” or “hidden” mode option.
