### ISSUE TITLE
Kernel DMA Protection for Thunderbolt™ 3 - Where is the "Memory Access Protection" option ?

### ISSUE THREAD

**Issue by PierrickV** [MicrosoftDocs/windows-itpro-docs#5988]
Hello,

I can't found the **Memory access protection**  option in **Core Isolation**.

The documentation has the following picture:
![kernel-dma-protection-security-center](https://user-images.githubusercontent.com/8960084/73768933-2cb71680-477a-11ea-971b-049fc3118cea.png)

However, this option does not appear in my Windows installation :

![Annotation 2020-02-04 171943](https://user-images.githubusercontent.com/8960084/73769192-8ddeea00-477a-11ea-89b2-a8233b1d4d5b.jpg)

I tried to find this option on several recent and fully updated Windows 10 computers without success.

In **System Information**, **Kernel DMA Protection** is off on the computer I'm playing with

![Annotation 2020-02-04 173107](https://user-images.githubusercontent.com/8960084/73770262-67ba4980-477c-11ea-85c8-0dc0c8dbd2c9.jpg)

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b83e95-63de-87c5-929c-d5f25e33d124
* Version Independent ID: 743ead3f-b4a5-1589-6577-e1d12aaa1b92
* Content: [Kernel DMA Protection for Thunderbolt™ 3 (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/kernel-dma-protection-for-thunderbolt#frequently-asked-questions)
* Content Source: [windows/security/information-protection/kernel-dma-protection-for-thunderbolt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/kernel-dma-protection-for-thunderbolt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@PierrickV.    First install the certified and verified device driver to thunderblot 3. 
then enable dma protection in GPO. 
You must enable UEFI or secure boot in bios.
you need windows 10 professional or enterprise 64bit 1903 or 1909 edition OS.

please change the language as English in your computer and take and post the corresponding screenshots

**Comment by beerisgood** [comment]
@RAJU2529 
So DMA protection doesn't work without thunderbolt driver? Does windows doesn't install that by default ?

**Comment by RAJU2529** [comment]
@PierrickV . I think you must install the certified  driver , download from the system manufacturer .

**Comment by beerisgood** [comment]
@RAJU2529 your quote go to wrong person again ;)

Also I never see any company which provide such a driver. Any infos?
Also where did you read that the driver is necessary?

**Comment by RAJU2529** [comment]
@PierrickV . I have seen the asus company , which provides thunderbolt 3 certified driver fro laptop. 
Driver is  necessary , because the  driver is modified  such way that , compatible with dma protection and  also depends upon the Intel Processor model with highend chipset

**Comment by PierrickV** [comment]
@beerisgood 

Documentation about Windows DMA protection that I am aware of:

- Kernel DMA Protection for Thunderbolt™ 3 : https://docs.microsoft.com/en-us/windows/security/information-protection/kernel-dma-protection-for-thunderbolt#frequently-asked-questions
- BitLocker Countermeasures : https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-dmaguard#dmaguard-deviceenumerationpolicyecurity/information-protection/bitlocker/bitlocker-countermeasures
- Policy CSP - DmaGuard : https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-dmaguard#dmaguard-deviceenumerationpolicy

**Comment by PierrickV** [comment]
@RAJU2529

**Comment by MaratMussabekov** [comment]
Dear @PierrickV, 
**In System Information, Kernel DMA Protection is off on the computer I'm playing with** - it means you need to enable Intel Thunderbolt Security in BIOS, as it is described [here](https://docs.microsoft.com/windows/security/information-protection/bitlocker/bitlocker-countermeasures) (second article that you provided)

Thank you

**Comment by mypil** [comment]
@PierrickV - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by PierrickV** [comment]
So I finally found one computer that had the protection enabled (sorry it's in french, I don't own the computer).

<img width="960" alt="dma-protection-ok" src="https://user-images.githubusercontent.com/8960084/74922280-45a50600-53cf-11ea-8e16-1d20b708f161.png">

The computer has the following configuration :
- Secureboot on
- VT-d on
- Admin password on the BIOS/UEFI
- Intel Thunderbolt Security set to User Authorization in BIOS settings
- (+ it's a very recent computer?)

Thank you @RAJU2529 for your help

@MaratMussabekov : Thunderbolt is off on the computer that has the protection enabled (did you mean "*intel thunderbolt sercurity set to user authorization in bios settings*" ?)

**Comment by MaratMussabekov** [comment]
Hello @PierrickV,
yes, sorry for being unclear
Thank you

**Comment by umair-mirza** [comment]
You can also go to the System Information and check if the **Kernel DMA Protection** is ON or OFF.
![Kernel-DMA-Protection](https://user-images.githubusercontent.com/42217546/82117752-d8193380-978b-11ea-8966-1c9baaff2940.png)
[Here's](https://www.helpmegeek.com/check-if-windows-supports-kernel-dma-protection/) a quick step-by-step guide on how to check it and how to enable it if it's OFF.
