### ISSUE TITLE
Exclusion Route Woes

### ISSUE THREAD

**Issue by pcs504** [MicrosoftDocs/windows-itpro-docs#599]
Having a very difficult time getting the Exclusion Routes to work as there is very little documentation on this feature.  We want to do 1 of 2 things:

1) Utilize Forced Tunnel and do an Exclusion Route to ensure traffic to certain IP addresses go over the open internet, OR
2) Utilize Split Tunnel and specifying widely scoped routes that force traffic internally + utilizing an exclusion route to force specific traffic out the open internet.  i.e.  8.0.0.0/8 as a tunneled route + 8.10.10.10/32 as an excluded route that forces only traffic destined for that IP to go over the open internet.

I have been unsuccessful at implementing either technique.  My goal is to have 99.9% of all traffic flow through the VPN but I want to exclude 5-6 IP addresses so that they go over the open internet for latency-sensitive applications such as Citrix and Skype for Business.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad2d82ab-4fdd-5cdd-247e-7cf3fb2a237d
* Version Independent ID: 3f88b62a-ffac-20b5-a0d7-87bb62f894c1
* Content: [VPN routing decisions (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-routing)
* Content Source: [windows/security/identity-protection/vpn/vpn-routing.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/vpn/vpn-routing.md)
* Service: **unspecified**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **justinha**

**Comment by shortpatti** [comment]
@pcs504 I will investigate more and work on refreshing the content 👍

**Comment by pcs504** [comment]
Let me know... If you saw what my routing tables looked like to make the entire public internet go through the VPN except 5 /32's, you'd understand :)

**Comment by shortpatti** [comment]
@MihaiSP, is this something you can answer?

**Comment by shortpatti** [comment]
@pcs504, here's the most current information on Exclusion routes: 

>  **Exclusion routes** 
> Always On VPN supports the ability to specify exclusion routes that specifically control routing behavior to define which traffic should traverse the VPN only and not go over the physical network interface.<p>_**Note.**_ Exclusion routes currently work for traffic within the same subnet as the client, for example, LinkLocal.<p>**Important.** Exclusion routes only work in a Split Tunnel setup.

**Comment by KenLee123** [comment]
Are there any further developments on this, as one of our clients is in the same boat. They require a mechanism whereby they can specify the routes that should go over the physical interface, with all remaining traffic defaulting to going over the VPN interface.

From my understanding, this is the reverse of what exclusion routes currently do.

The motivation for this is so that they can forward all Office 365 Optimize and Allow traffic directly across the Internet. If this traffic is sent down the VPN tunnel, they are finding that the resulting latency causes many of the services to stop functioning or have inadequate performance.

**Comment by mypil** [comment]
@shortpatti - We would like to follow up on this. Do you have any updates? 

Thanks.

**Comment by mypil** [comment]
@pcs504 - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by stevep4** [comment]
Hi @pcs504 I wondered if you ever opened a support ticket on this and had any further advice from MS you could share? We're in the same boat, we would like all traffic to go over VPN, except for 365 things.

@mypil this seems to be a valid question from at least 3 of us, it's disappointing the thread has been closed with no answers or documentation updates. Can the product group respond outside of the logging a support job process please?

**Comment by mikenor** [comment]
I know this is old and closed, but since lots of people have chimed here in over a long period with issues, let me explain what I have found and suggest a workaround...

Microsoft's implementation of ExclusionRoute idiotically creates all its routes as "on-link" routes (i.e. no next-hop), even for destination addresses where anybody with even basic rudimentary knowledge of IP subnetting could glance at the routing table and plainly see that the destination is not on-link and needs to have a next-hop defined. (Better OSes do not even allow having such an obviously-invalid entry in the routing table.)

In Windows Task Scheduler, you can create a scheduled task that is triggered by Application log RasClient Event ID 20225. It will run whenever the VPN client connects. I use PowerShell to examine routing table entries for "on-link" routes whose destination addresses do not fall within subnet of the interface they are on, and change them to have a next-hop. Or less fancy, you could simply forget about ExclusionRoute altogether and just define the routes you need right here in the scheduled task.

Would love to know what use case Microsoft thought that they were making something useful for... if they were even thinking.

**Comment by stevep4** [comment]
Hi mikenor... That sounds really interesting... I'm already 80% there as I have a scheduled task to trap VPN connections to kick off a GPUpdate (we had some weird requirement that needed it). If that just needs some tweaking to do what you suggest, then that sounds awesome. Would you be happy to share your PowerShell at all? (Cheeky I know, but it would help save some development time). Thanks!

**Comment by stevep4** [comment]
@mikenor - should have tagged you with above comment, oops.

**Comment by stevep4** [comment]
@mikenor - Also, assuming the next-hop is different to what you might want to use on a corporate network, do you think also have a scheduled task to monitor connections to a corp wireless network and then reset the routing accordingly?

**Comment by mikenor** [comment]
@stevep4 - 

> Would you be happy to share your PowerShell at all? (Cheeky I know, but it would help save some development time).

I can't share it directly as it contains organization-specific stuff that wouldn't make sense for a general context. This is **untested code** off the top of my head just to give an example of the general idea of how I do it.

```
# Gather info about the default gateway
$defRoute = Get-NetRoute -AddressFamily IPv4 -DestinationPrefix "0.0.0.0/0"
$defGwAddr = $defRoute.NextHop
$ifaceNum = $defRoute.ifIndex

# VPN client creates its "Exclusion Routes" on the same interface
# as the default gateway and with no next-hop (0.0.0.0).

# Gather info about those routes
Get-NetRoute -AddressFamily IPv4 -InterfaceIndex $ifaceNum -NextHop "0.0.0.0" | ForEach-Object {
	$routePrefix, $routePrefixLen = $_.DestinationPrefix.Split("/")

	# *** YOU'RE ON YOUR OWN TO COME UP WITH YOUR OWN LOGIC FOR THIS PART: ***
	# if $routePrefix/$routePrefixLen is multicast, global broadcast, or falls
	# within the address range of the on-link subnet, then ignore.

	# else, fix the route to have next-hop
	# have to resort to using route.exe because Set-NetRoute can't modify next-hop
	& ROUTE.EXE CHANGE $_.DestinationPrefix $defGwAddr IF $ifaceNum
}
```

> Also, assuming the next-hop is different to what you might want to use on a corporate network, do you think also have a scheduled task to monitor connections to a corp wireless network and then reset the routing accordingly?

I don't understand what scenario you're asking about... but as long as you only **change** existing Exclusion Routes created by the VPN client, then the VPN client will still take care of cleaning them up when it disconnects.

**Comment by Kilo1977** [comment]
> **Important.** Exclusion routes only work in a Split Tunnel setup.

This is not true at all. In fact, I do not see what purpose exclusion routes would even have in a split tunnel setup.
True you can define routes so that you ensure they go THROUGH the tunnel, but that would in all logic make them Inclusion routes.

Exclusion routes are determined when using Force Tunnel and you explicitly want traffic NOT to go through the (forced) tunnel.

https://docs.microsoft.com/en-gb/windows/security/identity-protection/vpn/vpn-office-365-optimization

**Comment by Kilo1977** [comment]
> Having a very difficult time getting the Exclusion Routes to work as there is very little documentation on this feature. We want to do 1 of 2 things:
> 
> 1. Utilize Forced Tunnel and do an Exclusion Route to ensure traffic to certain IP addresses go over the open internet, OR
> 2. Utilize Split Tunnel and specifying widely scoped routes that force traffic internally + utilizing an exclusion route to force specific traffic out the open internet.  i.e.  8.0.0.0/8 as a tunneled route + 8.10.10.10/32 as an excluded route that forces only traffic destined for that IP to go over the open internet.
> 
> I have been unsuccessful at implementing either technique. My goal is to have 99.9% of all traffic flow through the VPN but I want to exclude 5-6 IP addresses so that they go over the open internet for latency-sensitive applications such as Citrix and Skype for Business.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: ad2d82ab-4fdd-5cdd-247e-7cf3fb2a237d
> * Version Independent ID: 3f88b62a-ffac-20b5-a0d7-87bb62f894c1
> * Content: [VPN routing decisions (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-routing)
> * Content Source: [windows/security/identity-protection/vpn/vpn-routing.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/vpn/vpn-routing.md)
> * Service: **unspecified**
> * GitHub Login: @jdeckerms
> * Microsoft Alias: **justinha**



> I have been unsuccessful at implementing either technique. My goal is to have 99.9% of all traffic flow through the VPN but I want to exclude 5-6 IP addresses so that they go over the open internet for latency-sensitive applications such as Citrix and Skype for Business.

https://docs.microsoft.com/en-gb/windows/security/identity-protection/vpn/vpn-office-365-optimization

**Comment by Bstan28** [comment]
I'm trying to implement this exact thing @Kilo1977 . I want my tunnel to stay a Forced tunnel but I want to exclude the routes of my choosing. This is the PowerShell script I'm currently using but something is not working correctly. Any advice?

`
   $ProfileName = 'VPN02'
   $ProfileNameEscaped = $ProfileName -replace ' ', '%20'

   $ProfileXML = @'
<VPNProfile> 
	<ProfileName>VPN02</ProfileName>
	<RememberCredentials>true</RememberCredentials>
	<AlwaysOn>false</AlwaysOn>
	<NativeProfile>
		<Servers>vpn02.net</Servers>
		<RoutingPolicyType>ForceTunnel</RoutingPolicyType>
		<NativeProtocolType>SSTP</NativeProtocolType>
		<Authentication>
			<UserMethod>MsChapv2</UserMethod>
			<Eap>
			<Configuration>
				<EapHostConfig xmlns='http://www.microsoft.com/provisioning/EapHostConfig'>
					<EapMethod>
						<Type xmlns='http://www.microsoft.com/provisioning/EapCommon'>26</Type>
						<VendorId xmlns='http://www.microsoft.com/provisioning/EapCommon'>0</VendorId>
						<VendorType xmlns='http://www.microsoft.com/provisioning/EapCommon'>0</VendorType>
						<AuthorId xmlns='http://www.microsoft.com/provisioning/EapCommon'>0</AuthorId>
					</EapMethod>
					<Config xmlns='http://www.microsoft.com/provisioning/EapHostConfig'>
						<Eap xmlns='http://www.microsoft.com/provisioning/BaseEapConnectionPropertiesV1'>
							<Type>26</Type>
							<EapType xmlns='http://www.microsoft.com/provisioning/MsChapV2ConnectionPropertiesV1'>
								<UseWinLogonCredentials>false</UseWinLogonCredentials>
							</EapType>
						</Eap>
					</Config>
				</EapHostConfig>
			</Configuration>
		  </Eap>
		</Authentication>
	</NativeProfile>
	<Route>
		<Address>204.79.197.215</Address>
		<PrefixSize>32</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>104.146.128.0</Address>
		<PrefixSize>17</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>13.107.128.0</Address>
		<PrefixSize>22</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>13.107.136.0</Address>
		<PrefixSize>22</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>13.107.18.10</Address>
		<PrefixSize>31</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>13.107.6.152</Address>
		<PrefixSize>31</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>13.107.64.0</Address>
		<PrefixSize>18</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>131.253.33.215</Address>
		<PrefixSize>32</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>132.245.0.0</Address>
		<PrefixSize>16</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>150.171.32.0</Address>
		<PrefixSize>22</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>150.171.40.0</Address>
		<PrefixSize>22</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>23.103.160.0</Address>
		<PrefixSize>20</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>40.104.0.0</Address>
		<PrefixSize>15</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>40.108.128.0</Address>
		<PrefixSize>17</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>40.96.0.0</Address>
		<PrefixSize>13</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>52.104.0.0</Address>
		<PrefixSize>14</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>52.112.0.0</Address>
		<PrefixSize>14</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>52.120.0.0</Address>
		<PrefixSize>14</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>52.96.0.0</Address>
		<PrefixSize>14</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>13.107.60.1</Address>
		<PrefixSize>32</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>104.146.128.0</Address>
		<PrefixSize>17</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>13.107.128.0</Address>
		<PrefixSize>22</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>13.107.136.0</Address>
		<PrefixSize>22</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>13.107.18.10</Address>
		<PrefixSize>31</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>13.107.6.152</Address>
		<PrefixSize>31</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>13.107.64.0</Address>
		<PrefixSize>18</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>131.253.33.215</Address>
		<PrefixSize>32</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>132.245.0.0</Address>
		<PrefixSize>16</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>150.171.32.0</Address>
		<PrefixSize>22</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>150.171.40.0</Address>
		<PrefixSize>22</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>23.103.160.0</Address>
		<PrefixSize>20</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>40.104.0.0</Address>
		<PrefixSize>15</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>40.108.128.0</Address>
		<PrefixSize>17</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>40.96.0.0</Address>
		<PrefixSize>13</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>52.104.0.0</Address>
		<PrefixSize>14</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>52.112.0.0</Address>
		<PrefixSize>14</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>52.120.0.0</Address>
		<PrefixSize>14</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>52.96.0.0</Address>
		<PrefixSize>14</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
	<Route>
		<Address>13.107.60.1</Address>
		<PrefixSize>32</PrefixSize>
		<ExclusionRoute>true</ExclusionRoute>
	</Route>
</VPNProfile>
'@

   $ProfileXML = $ProfileXML -replace '<', '&lt;'
   $ProfileXML = $ProfileXML -replace '>', '&gt;'
   $ProfileXML = $ProfileXML -replace '"', '&quot;'

   $nodeCSPURI = "./Vendor/MSFT/VPNv2"
   $namespaceName = "root\cimv2\mdm\dmmap"
   $className = "MDM_VPNv2_01"

   try
   {
   $username = $Env:USERNAME
   $objuser = New-Object System.Security.Principal.NTAccount($username)
   $sid = $objuser.Translate([System.Security.Principal.SecurityIdentifier])
   $SidValue = $sid.Value
   $Message = "User SID is $SidValue."
   Write-Host "$Message"
   }
   catch [Exception]
   {
   $Message = "Unable to get user SID. User may be logged on over Remote Desktop: $_"
   Write-Host "$Message"
   exit
   }

   $session = New-CimSession
   $options = New-Object Microsoft.Management.Infrastructure.Options.CimOperationOptions
   $options.SetCustomOption("PolicyPlatformContext_PrincipalContext_Type", "PolicyPlatform_UserContext", $false)
   $options.SetCustomOption("PolicyPlatformContext_PrincipalContext_Id", "$SidValue", $false)

   try
   {
  $deleteInstances = $session.EnumerateInstances($namespaceName, $className, $options)
  foreach ($deleteInstance in $deleteInstances)
  {
      $InstanceId = $deleteInstance.InstanceID
      if ("$InstanceId" -eq "$ProfileNameEscaped")
      {
          $session.DeleteInstance($namespaceName, $deleteInstance, $options)
          $Message = "Removed $ProfileName profile $InstanceId"
          Write-Host "$Message"
      } else {
          $Message = "Ignoring existing VPN profile $InstanceId"
          Write-Host "$Message"
      }
  }
   }
   catch [Exception]
   {
  $Message = "Unable to remove existing outdated instance(s) of $ProfileName profile: $_"
  Write-Host "$Message"
  exit
   }

   try
   {
  $newInstance = New-Object Microsoft.Management.Infrastructure.CimInstance $className, $namespaceName
  $property = [Microsoft.Management.Infrastructure.CimProperty]::Create("ParentID", "$nodeCSPURI", "String", "Key")
  $newInstance.CimInstanceProperties.Add($property)
  $property = [Microsoft.Management.Infrastructure.CimProperty]::Create("InstanceID", "$ProfileNameEscaped", "String",      "Key")
  $newInstance.CimInstanceProperties.Add($property)
  $property = [Microsoft.Management.Infrastructure.CimProperty]::Create("ProfileXML", "$ProfileXML", "String", "Property")
  $newInstance.CimInstanceProperties.Add($property)
  $session.CreateInstance($namespaceName, $newInstance, $options)
  $Message = "Created $ProfileName profile."

  Write-Host "$Message"
   }
   catch [Exception]
   {
  $Message = "Unable to create $ProfileName profile: $_"
  Write-Host "$Message"
  exit
   }

   $Message = "Script Complete"
   Write-Host "$Message"
`
