### ISSUE TITLE
Add reference about service dependency

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#5990]
When enabling this policy it will only have effect when the service: smart card removal policy is running and set to automatic startup

Suggest to add this to the article

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06964e42-cae0-d58b-027f-8feab6cbecbb
* Version Independent ID: 271a595a-eef6-0ea9-7b41-b1abcbca356b
* Content: [Interactive logon Smart card removal behavior (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-smart-card-removal-behavior)
* Content Source: [windows/security/threat-protection/security-policy-settings/interactive-logon-smart-card-removal-behavior.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/interactive-logon-smart-card-removal-behavior.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@alexverboon . you can check in the windows services menu and check the corresponding registry key

**Comment by mypil** [comment]
@alexverboon- Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/b895600e5eb2751c7b0753caa700036cbe6191d1. 


Thank you for your contribution to make the docs better! Much appreciated!
