### ISSUE TITLE
Does WEF have a Native way to send a  SEM, SQL or MapReduce system?

### ISSUE THREAD

**Issue by luisfeliz79** [MicrosoftDocs/windows-itpro-docs#5992]
Does WEF have a native way to send events to a  SEM, SQL or MapReduce system?

Or is the assumption that an Agent/PowerShell Script can be used on the WEF Collector?

**Comment by mypil** [comment]
@luisfeliz79 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by luisfeliz79** [comment]
Hi! I was referring to this page:
https://docs.microsoft.com/en-us/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection

**Comment by joinimran** [comment]
Hello @luisfeliz79 - WEF clients are configured by using a GPO and the built-in forwarding client is activated.  But you can also use Agent/Powershell.

Thanks
Imran.

**Comment by mypil** [comment]
@luisfeliz79 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by joinimran  so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
