### ISSUE TITLE
AllowFipsAlgorithmPolicy is misleading

### ISSUE THREAD

**Issue by dancs85** [MicrosoftDocs/windows-itpro-docs#5994]
I think this policy should be called "EnableFipsAlgorithmPolicy", as the behaviour I've experienced by enabling the policy within InTune (Device Config Profiles --&gt; Win10 Device Restriction --&gt;Properties --&gt; Settings --&gt; Password --&gt; "Federal Information Processing Standard (FIPS) policy) when I set it to "Allow" seemed to set the registry key "HKLM\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy:MDMEnabled" to 1.
Setting the policy to 'Not configured' does not set the corresponding registry key to 0, and FIPS mode stays on.

Also note that the Group Policy setting "Windows Settings/Security Settings/Local Policies/Security Options/System cryptography: Use FIPS-compliant algorithms for encryption, hashing, and signing" corresponds to a different registry key: "HKLM\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy:Enabled".

FIPS mode will be on if either of the keys is set to 1 (and in fact there are 2 other keys that do the same)

I suggest the Policy is renamed, the settings are change to Enable and Disable, and that when set to Disable the corresponding registry key is set to 0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b290a291-ccb6-953f-0679-2a56a927620e
* Version Independent ID: 6a86d25c-12ea-1f8d-2758-4d13352e7718
* Content: [Policy CSP - Cryptography - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-cryptography#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-cryptography.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-cryptography.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@dancs85 I agree with your points. but renaming I have doubt

**Comment by e0i** [comment]
This feedback seems to be better suitable for [Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub) platform.

The issues section of this repository is intended for content fixes.

Please [send the feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

Feel free to re-open this issue if for further suggestions to improve the documentation itself.

Thanks.
