### ISSUE TITLE
Using CSP to clear administrator group of the device

### ISSUE THREAD

**Issue by mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh** [MicrosoftDocs/windows-itpro-docs#5995]
To clear the administrator group of the device for security purpose, SIDs should be included into the CSP for management purpose by the Global Administrator and Device Administrator. 

You'll have to check the SID that is automatically added to the workstations group BUILTIN\Administrators and place those two SIDs (presumably from Global Administrator and Device Administrator) to the CSP, next to the Builtin\administrator account. In this way, any accounts added to the administrator group will be removed. 

So your CSP would look like the following to clear accounts added locally from the Global administrator group: 
`&lt;groupmembership&gt;
	&lt;accessgroup desc = "Administrators"&gt;
		&lt;member name = "Administrator" /&gt;
		&lt;member name = "enter-SID-that-you-found-in-administrators-group-on-laptop" /&gt;
		&lt;member name = "enter-SID-that-you-found-in-administrators-group-on-laptop" /&gt;
	&lt;/accessgroup&gt;
&lt;/groupmembership&gt;`

This addition of SIDs wasn't neccesary until recently, but Microsoft fixed an issue where this CSP used to be applied once, and seems now to be applied continuously. Although undocumented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0c28c15-f0be-d732-4d9e-cf5df5e64e8b
* Version Independent ID: 17eba45f-d200-e656-42b9-e1a512931eea
* Content: [Policy CSP - RestrictedGroups - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-restrictedgroups)
* Content Source: [windows/client-management/mdm/policy-csp-restrictedgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-restrictedgroups.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by madmouse256** [comment]
You are writing that "Microsoft fixed an issue where this CSP used to be applied once, and is now applied continuously"
How did you achieve this? I have an issue now as policy applies once and do not reapply.

**Comment by mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh** [comment]
I'll test this again, so let me get back to you on this. Which Windows 10 version and Intune Service version are you on? 

Workaround: Create and deploy a Powershell script to all your machines which will create a scheduled task as NT AUTHORITY\SYSTEM to update the local administrators group according to your needs. If necessary, I could write a tutorial once I have some time off work.

**Comment by PeterKlapwijk** [comment]
@madmouse256 You need to run Windows 10 1903 or later for this.

**Comment by e0i** [comment]
It seems that the question has already been answered by the community (via **PeterKpawijk** and thus the issue is being marked as resolved. 

Thank you for providing feedback.
