### ISSUE TITLE
Broken on some DPs but not others?

### ISSUE THREAD

**Issue by DavieH** [MicrosoftDocs/windows-itpro-docs#5997]
This worked beautifully first time I tried it, but recently I've had the strangest error. It works from one of our DPs without issue, but on two of them it fails at the copy autopilot config stage. The xcopy command returns a 4 and the log has weird Chinese characters in it. Anyone else found this or found a solution? Tried removing the package and re-adding it, tried a few things, but nada. Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17bfe927-f7b7-608b-8537-5c2274ccdced
* Version Independent ID: 5dd9abca-92d9-fbb2-6796-d1f6b9ab3c8b
* Content: [Windows Autopilot for existing devices - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/existing-devices#feedback)
* Content Source: [windows/deployment/windows-autopilot/existing-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/existing-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by DavieH** [comment]
Update: Tried creating a new package but the same result. Checked the local log on a failed install and saw an error for UNC path not supported and file not found, but the file is there. Log for the deployment looks totally different on the machine that did work

**Comment by e0i** [comment]
Hello,

Looks like this question can best be answered via relevant [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channels. 

Please consider checking with [Microsoft Community](https://answers.microsoft.com/en-us/windows/forum/windows_10) or [contacting support](https://support.microsoft.com/contactus) for your problem; The issues section of this repository is for content fixes in documentation.

If you feel that the associated article also needs to be updated for any reason feel free to re-open this issue or [contribute with a pull request](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/CONTRIBUTING.md).

Thank you.
