### ISSUE TITLE
FIPS 201-2 Compliance for Windows 10 Enterprise v 1903

### ISSUE THREAD

**Issue by datocrats-org** [MicrosoftDocs/windows-itpro-docs#6000]
Please update this article to include the newer release of Windows 10 Enterprise (v 1903) and reference the specific NIST certificates.  This info is necessary to remain in compliance with FIPS requirements, without it the rest of the great info and content you provide will not be useful because the NIST certification behind them cannot be easily referenced.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e93f07bf-c0dd-dd83-d7bf-8562e7f197c3
* Version Independent ID: a6c44187-8ff1-6519-5291-146b4c1bf46c
* Content: [Federal Information Processing Standard (FIPS) 140 Validation - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/fips-140-validation#feedback)
* Content Source: [windows/security/threat-protection/fips-140-validation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/fips-140-validation.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by datocrats-org** [comment]
https://docs.microsoft.com/en-us/windows/security/threat-protection/fips-140-validation

**Comment by e0i** [comment]
@Dansimp Forwarding the issue as it looks like a legal case.

Please let me know in any way that we could help. Thank you.

**Comment by paolomatarazzo** [comment]
The current list is up to date. We are in the process of refreshing the page and completing the certification process of newer versions.
