### ISSUE TITLE
Prevent Uninstall

### ISSUE THREAD

**Issue by macmillernz** [MicrosoftDocs/windows-itpro-docs#6002]
Is there setting to prevent users from uninstalling?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5c929d-414f-70b8-c687-e9a60ef709e3
* Version Independent ID: a3cde3f5-e7a1-e0cc-aeae-fd6123f696c5
* Content: [Set preferences for Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-preferences#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-preferences.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-preferences.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
@GlennMillerNZ : I am pretty sure that needs to be sorted out in MacOS locally, by managing what the local users have access to do on that computer. Seeing that the uninstall method is as trivial as described on the page https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-resources#uninstalling , I don't see how you would be able to block the uninstalling other than to set restrictions on what local users are allowed to do in MacOS.

**Comment by GlennMillerNZ** [comment]
There are plenty of applications that require a master password to uninstall, just need to look at Symantec, Crowdstrike, Zscaler applications for example.

**Comment by illfated** [comment]
Fair enough. I think we may have to wait for a reply from someone more knowledgeable than me on this topic. I also do not have access to a relevant test scenario.

**Comment by RAJU2529** [comment]
I not used MAC . I think the guest user accounts does not have administrator rights to install or uninstall.

I think add the folder of " windows defender atp"  in controlled folder access, then enable it. So the files from the folders will be protected by modifying

**Comment by illfated** [comment]
@RAJU2529 : You might be interested in the manual install procedure for MacOS on this page:
- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-install-manually

Fair point about Guest user accounts, because I forgot to ask what kind of users there will be in the scenario related to the question from OP.

**Comment by RAJU2529** [comment]
@illfated. I don't have MAC os , so I can't Give exact solution

**Comment by illfated** [comment]
Fair enough. I just thought you should know that MacOS is a Unix-like (or Linux-like) OS with graphical user interface (GUI). When installing **Microsoft Defender ATP for Mac**, the file/folder/user access security depends on Unix format access rights, so I don't think Windows Controlled Folder Access is helpful in this case.

The original question remains: Can the installed software be locked (e.g. by password) from being uninstalled by local users on the Macintosh computer? Or does it solely depend on Local user access management in MacOS, by giving or denying users access to install & uninstall software?

**Comment by RAJU2529** [comment]
@illfated . ok fine. Actually I understand that question asked by the user. moreover when I come across the mac os I Will check this case particularly.

**Comment by illfated** [comment]
Very well. I would have liked to test that myself, but I do not have any easy way to connect a reasonably updated Mac to a Windows AD Domain or Azure. I also usually find that my days are too cluttered with other things to follow up, so it is very unlikely that I will find time to test this scenario. It would have been nice to have a comment from the developers, though. Then again, the Feedback Hub is supposed to be a more direct way to get response from the developers.

**Comment by RAJU2529** [comment]
@illfated. ok fine

**Comment by Dansimp** [comment]
Following up on this

**Comment by maximvelichko** [comment]
If a user is a local root then they can always easily uninstall a pin-protected application (reboot into the OS recovery mode with raw terminal and no 3rd party software, and remove anything from the disk, see e.g. an article on [sonicwall](https://www.sonicwall.com/support/knowledge-base/uninstalling-sentinelone-mac-agent-through-recovery-mode/180817075834733/))

The suggested solution is to monitor machines for the presence and health of Defender and red flag a machine that misses it. (You can setup it with e.g. JAMF).

**Comment by GlennMillerNZ** [comment]
@maximvelichko That would be true if our MDM didn't set a firmware password and start-up security.

**Comment by maximvelichko** [comment]
Fair point
