### ISSUE TITLE
Missing Changelog 

### ISSUE THREAD

**Issue by mradders** [MicrosoftDocs/windows-itpro-docs#6005]
Previously there was a changelog on the site, so that you could understand which changes were made when and for which major release. This changelog is gone. As a consequence, this means that we really would have to go through every setting over and over again (there are a lot of settings) and would have to compare it permanently with the existing settings. This cannot be automated, costs enormous resources and time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abd3113-b803-87b6-ef7f-6893bcc5ceb5
* Version Independent ID: 6f7ca1ee-d19c-42bb-7db5-6158fc160e32
* Content: [Manage connections from Windows 10 operating system components to Microsoft services - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services#feedback)
* Content Source: [windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @medgarmedgar
* Microsoft Alias: **v-medgar**

**Comment by medgarmedgar** [comment]
Ok, I think it is OK, since we don't seem to have a choice :).

Is the new changelog up and running going forward?
Will there be regular backups taken going forward?

-Mike

**Comment by e0i** [comment]
Closing based on the author's response. Thank you.

**Comment by beerisgood** [comment]
@e0i where is that response?

@mradders

**Comment by mradders** [comment]
Do we have the changelog now or not?
