### ISSUE TITLE
How do you enable Tamper Protection via powershell / cmd / registry?

### ISSUE THREAD

**Issue by jeremycolby** [MicrosoftDocs/windows-itpro-docs#6009]
With 1909, MDT / Sysprep seems to disable this feature even though it is supposed to be enabled by default.

The registry key is protected
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Features\TamperProtection

Another summation of the issue:
https://www.reddit.com/r/sysadmin/comments/ew661q/enabling_tamperprotection_1903_beyond_thru_imaging/

Right now, it seems the only way to enable this when imaging is to manually turn it on for each newly imaged machine.

How do you enable Tamper Protection via powershell / cmd / registry?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a2f0402-82fb-83ff-122a-2f19c5288eeb
* Version Independent ID: 52f80b09-0e90-464d-0c4d-00479361fa9b
* Content: [Protect security settings with tamper protection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
tamper protection can also Turned off when the secure boot is disabled in bios. 
today afternoon I will check

**Comment by MaratMussabekov** [comment]
Hello @jeremycolby,
**The registry key is protected HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Features\TamperProtection** - have you tried to update this registry key using GPO? if yes, which error was registered in event logs?
Thank you

**Comment by RAJU2529** [comment]
@MaratMussabekov . I tried to change the value , but it gives access denied

**Comment by MaratMussabekov** [comment]
Then the only option to change it in bulk - using Intune
If you do not have Intune deployed in your organization, you need to change it manually (no PowerShell command exist to enable/disable it).
However, tamper protection should be enabled by default (as it was announced by Microsoft), so if it doesn't work the way it should, i would recommend to create a [support request](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) 
Thank you

**Comment by mypil** [comment]
@jeremycolby @RAJU2529 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov  so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
