### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ShrCaJesmo** [MicrosoftDocs/windows-itpro-docs#6014]
```
The following is a sample for reference, using **GUID values for ASR rules** .
```

This link in the [mdm section](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/enable-attack-surface-reduction#mdm) seems to be broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4144ff8c-3d92-d2d7-27ad-4a37843a1008
* Version Independent ID: 43cc32fc-6e2f-5c30-b758-666a53c0052b
* Content: [Enable ASR rules individually to protect your organization - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/enable-attack-surface-reduction#mdm)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/enable-attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/enable-attack-surface-reduction.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
You are right! It should go here: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction#attack-surface-reduction-rules

Will fix the link.

**Comment by levinec** [comment]
Made a pr (along with some other link changes) https://github.com/MicrosoftDocs/windows-docs-pr/pull/2012
