### ISSUE TITLE
Double 0 typo

### ISSUE THREAD

**Issue by vainkop** [MicrosoftDocs/windows-itpro-docs#6017]
Hello.
There's a double 0 typo, after word "Server" in
"In Windows 10 and Windows Server 20016, Windows setup disables the built-in Administrator account and creates another local account"

**Comment by vainkop** [comment]
![IMG_20200208_000553](https://user-images.githubusercontent.com/28118190/74079544-d579a600-4a06-11ea-8892-a6609b54d37b.jpg)

**Comment by illfated** [comment]
OK, so this is about the page
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/access-control/local-accounts.md
and its resulting page
- https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/local-accounts

I will open up a Pull Request to have that typo resolved.

**Comment by illfated** [comment]
```
---
title: Local Accounts (Windows 10)
description: Local Accounts
ms.prod: w10
ms.mktglfcycl: deploy
ms.sitesec: library
ms.pagetype: security
audience: ITPro
author: dulcemontemayor
ms.author: dansimp
manager: dansimp
ms.collection: M365-identity-device-management
ms.topic: article
ms.localizationpriority: medium
ms.date: 02/28/2019
ms.reviewer: 
---
```

**Comment by e0i** [comment]
@vainkop The associated PR that has been provided by **illfated** is under review. Thank you for the feedback.
