### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by andrewwillett** [MicrosoftDocs/windows-itpro-docs#6018]
[You should consider and devise a deployment strategy for updates before you make changes to the Windows Update for Business settings. See] ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2e692b1-8354-6b09-dfd7-252585320aac
* Version Independent ID: d1c99e74-66df-760a-39e9-23e5ed2bcfec
* Content: [Configure Windows Update for Business via Group Policy (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-wufb-group-policy#feedback)
* Content Source: [windows/deployment/update/waas-wufb-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-wufb-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by andrewwillett** [comment]
Also some missing formatting tags (**) under 'Set up a ring'

**Comment by jaimeo** [comment]
You'll be pleased (I hope) to hear that my colleagues and I are in the process of completely reorganizing and rebuilding everything under https://docs.microsoft.com/en-us/windows/deployment/ from the ground up. To include a "prepare" phase such as you suggest. Stay tuned!

**Comment by illfated** [comment]
Yay, Good News, everyone! 😄

... I almost got a sore spot on the top of my head from scratching while looking around for a possible option where the missing text & link was supposed to be... ^^

**Comment by andrewwillett** [comment]
Its in the first paragraph:

**Overview**
You can use Group Policy through the Group Policy Management Console (GPMC) to control how Windows Update for Business works. You should consider and devise a deployment strategy for updates before you make changes to the Windows Update for Business settings. See **[missing link]**

An IT administrator can set policies (...)

**Comment by e0i** [comment]
> You'll be pleased (I hope) to hear that my colleagues and I are in the process of completely reorganizing and rebuilding everything under https://docs.microsoft.com/en-us/windows/deployment/ from the ground up. To include a "prepare" phase such as you suggest. Stay tuned!

Closing via document author's response. Thank you for the feedback.

**Comment by jaimeo** [comment]
I've provided a link target that should work in the meantime while we work on the rebuild (https://github.com/MicrosoftDocs/windows-docs-pr/pull/2029) and also fixed the formatting issues. Thanks for letting us know.

BTW, you are welcome to directly submit edits yourself, especially for things like that formatting issue. See https://docs.microsoft.com/en-us/contribute/index#quick-edits-to-existing-documents for more.

**Comment by illfated** [comment]
> Its in the first paragraph:
> 
> **Overview**
> You can use Group Policy through the Group Policy Management Console (GPMC) to control how Windows Update for Business works. You should consider and devise a deployment strategy for updates before you make changes to the Windows Update for Business settings. See **[missing link]**
> 

Yes, sorry. I meant to say that I did not know what linked page resource to look for, what the actual link name content is supposed to be. I was trying to narrow down which of the related documents it was supposed to point the reader to.
