### ISSUE TITLE
Using this script breaks WMIC

### ISSUE THREAD

**Issue by ArthurHNL** [MicrosoftDocs/windows-itpro-docs#6023]
After running this script as admin with the flags -Enable and -AutoReboot, executing the command "wmic os get caption" results in an "Unspecified error".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e100360b-b872-d0d6-ea4b-c5b999b1849a
* Version Independent ID: bf6d4bb9-d4d1-8b67-a4b8-bf00b174f6b7
* Content: [Windows Defender Device Guard and Windows Defender Credential Guard hardware readiness tool - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg_readiness_tool#feedback)
* Content Source: [windows/security/identity-protection/credential-guard/dg_readiness_tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/dg_readiness_tool.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @SteveSyfuhs
* Microsoft Alias: **stsyfuhs**

**Comment by ArthurHNL** [comment]
Script version was 3.6. I disabled credential guard and the stated command works again.

**Comment by beerisgood** [comment]
Maybe that's the reason or one at least, why the output of
`wmic /?`
display a **red** "WMIC is outdated" message in commandline window

**Comment by ArthurHNL** [comment]
@beerisgood I completely agree but when you need to use tools (in my case Apache Cordova) that depend on wmic, it still won't help. I'll file an issue at Cordova but stuff shouldn't just break.

**Comment by e0i** [comment]
@ArthurHNL 

The broken script is being passed to independent contributors for investigation. Thank you for the feedback.

**Comment by VLG17** [comment]
@ArthurHNL I see you said script version 3.6 breaks WMIC functionality. [The article you mentioned](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg_readiness_tool#feedback) contains script version 3.7. Were you able to reproduce the issue also with 3.7? 

> LogAndConsole "Readiness Tool **Version 3.7 Release**. `nTool to check if your device is capable to run Device Guard and Credential Guard.

Also, were you able to file an issue with Cordova? What was their answer about this?

**Comment by ArthurHNL** [comment]
I have not tried reproducing this with the new version of the script and, since my system is stable now, I am not planning on testing it. I already found an issue at cordova: https://github.com/apache/cordova-cli/issues/434 and I filed an issue at the underlying Node.js module used by cordova that depends on wmic: https://github.com/sindresorhus/windows-release/issues/14.

**Comment by VLG17** [comment]
@ArthurHNL thank you for you answer.
