### ISSUE TITLE
MS ATP Mac Catalina (10.15.x) slows O365 Apps to almost unusable

### ISSUE THREAD

**Issue by Wicked-Weasel** [MicrosoftDocs/windows-itpro-docs#6027]
Office for Mac 2019 becomes unusably slow with macOS Catalina (MacOS 10.15.x) and “Real Time Protection” being enabled in Microsoft ATP. This does not affect MacOS 10.14.x (Mojave) or 10.13.x (High Sierra) or 10.12.x (Sierra) as far as my testing shows...
When you disable the above feature – speed of operation of the apps returns to normal. ATP is all but useless at this point mind! Is there a fix for this?

I had in issue with my MacBook Book Pro (it went back to Apple for the Keyboard Recall). As this would take an estimated 10 days - I erased my old 2015 11" MacBook Air (2.2GHz i7, 8GB RAM, 500GB SSD), installed 10.15 clean on to it and setup Apps from scratch. I have all my docs in iCloud Drive / OneDrive so enabled, sync'd and all working well. then I installed ATP. At this point all O365 Apps (only these as far as I can tell) slow to a crawl. Outlook is especially bad. Moving from one folder to another takes 10s minimum and the beachball comes up. Turn off Real-Time Protection and folder come up in 1-2s depending on size as you would expect. Opening and working on Word / Excel docs also stops the hanging / beach balling issues. This is a clean install so not sure what more I could do. 
I have raised with Outlook support who, having looked into it, suggested I raise the issue here.

Many thanks

**Comment by mypil** [comment]
@Wicked-Weasel - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by Wicked-Weasel** [comment]
Hi there

Hi Oli, just want to send update that the issue is with Microsoft Defender ATP for macOS and was also published here: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-mac#how-to-install-microsoft-defender-atp-for-mac
Please reach out to ATP support team for further assistance.


All the best,
Oli
--
Oli Saunders
DBMC Ltd
m. +44 (0)7973 626556

**Comment by mypil** [comment]
@Wicked-Weasel - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
