### ISSUE TITLE
URI Syntax Unclear

### ISSUE THREAD

**Issue by Cloudsystemsit** [MicrosoftDocs/windows-itpro-docs#6028]
Hello, 

The example is rather confusing. How about One XML example, with an explanation?

Can you improve the Example of how you wish an Admin to use this URI?

This example is unclear to me, and does not work as indicated. 

Can you please update the example to be more implicit?

Thanks, 
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0c28c15-f0be-d732-4d9e-cf5df5e64e8b
* Version Independent ID: 17eba45f-d200-e656-42b9-e1a512931eea
* Content: [Policy CSP - RestrictedGroups - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-restrictedgroups#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-restrictedgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-restrictedgroups.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello, it looks like the example is incorrect, as it was stated in #1582, **groupmembership** tag shouldn't be located in this place. Dear @Dansimp, is it possible to check it with the team?
I believe that this XML should be something like following:
```
    <accessgroup desc = "Custom group">
    <!--Where "Custom group" is the name of the group you want to set members for-->
        <member name = "AzureAD\CSPTest@contoso.com" />
        <member name = "AzureAD\patlewis@contoso.com" />
        <!--Where "AzureAD\CSPTest@contoso.com" and "AzureAD\patlewis@contoso.com" are members to be added to "Custom group" -->
    </accessgroup>
    <groupmembership desc = "Custom group">
    <!--Where "Custom group" is the name of the group you want to set membership for-->    
	<accessgroup name = "Administrators" />
        <!--Where "Administrators" is the name of the group where "Custom group" will be added as a member -->  
    </groupmembership>
```
The point is that the GPO has [two settings](https://support.microsoft.com/en-us/help/279301/description-of-group-policy-restricted-groups) - **Members** (here presented as **accessgroup** tag) and **Member Of** (here presented as **groupmembership** tag).
So I think that **groupmembership desc** and  **accessgroup desc** tags must be on the same level of XML.
Thank you

**Comment by mypil** [comment]
@ManikaDhiman - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by ManikaDhiman** [comment]
Hi @mypil, in addition to the recent doc updates, a note is also added to address the confusion between the on-prem Restricted Groups policy and the RestrictedGroups/ConfigureGroupMembership policy. Hope this helps. Thanks!

**Comment by mypil** [comment]
@ManikaDhiman - Thanks for your help with this.

@Cloudsystemsit - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov and  ManikaDhiman so we will close this issue. Also, a note was added to the doc based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/142072d.



Thank you for your contribution to make the docs better! Much appreciated!
