### ISSUE TITLE
"When using Windows Pro and Windows Enterprise"

### ISSUE THREAD

**Issue by rafalfitt** [MicrosoftDocs/windows-itpro-docs#6029]
"and" should be changed to "or"

"When using Windows Pro or Windows Enterprise"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8927df09-e9aa-8c40-290d-0ca7d86ec4e2
* Version Independent ID: ca67bcfc-6120-d6ca-290b-1a7822494c73
* Content: [FAQ - Windows Defender Application Guard (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard?source=docs#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by mypil** [comment]
@rafalfitt - Thank you for pointing this out.

PR #6030 has been created by @Potapy4 to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
