### ISSUE TITLE
HideFirstLogonAnimation is invaild

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/windows-itpro-docs#6031]
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/wcd/wcd-smisettings.md

the HideFirstLogonAnimation is invaild. this one is different from EnableFirstLogonAnimation (https://docs.microsoft.com/en-us/windows/configuration/wcd/wcd-policies#windowslogon), the document should be noted, and the current document does not contain a description of EnableFirstLogonAnimation.

**Comment by RAJU2529** [comment]
@goxia . article is correct, according to me,. Show or hide first signin animation is in GPO. description of hidefisrtlogonanimation  is true or false is correct.

moreover enablefirstlogonanimation is in registry key only

**Comment by goxia** [comment]
> @goxia . article is correct, according to me,. Show or hide first signin animation is in GPO. description of hidefisrtlogonanimation is true or false is correct.
> 
> moreover enablefirstlogonanimation is in registry key only

But in fact, adding this "HideFirstLogonAnimation" to PPKG does not enable the first animation to be disabled, and the document is insufficient.

**Comment by RAJU2529** [comment]
@goxia . sorry I don't have knowledge about ppkg

**Comment by goxia** [comment]
> @goxia . sorry I don't have knowledge about ppkg

But this article is for PPKG.

**Comment by VLG17** [comment]
@goxia You create a provisioning package and set "HideFirstLogonAnimation" to False and still see the animation during the first sign-in? I recommend [contacting support](https://support.microsoft.com/en-us/contactus/) in order for an engineer to check the package you used and try to reproduce the issue.

What do you mean with "document is insufficient."? What would you add to it?

**Comment by goxia** [comment]
@VLG17 Thank you. I think the documentation should go into more detail about the differences between "HideFirstLogonAnimation" and "EnableFirstLogonAnimation".

**Comment by mypil** [comment]
@Dansimp - Can you please share your insights on this issue?

Thanks.

**Comment by joinimran** [comment]
@goxia - I have gone through the document and see that https://docs.microsoft.com/en-us/windows/configuration/wcd/wcd-policies#windowslogon doesn't mention to support HideFirstLogonAnimation or EnableFirstLogonAnimation. This concludes this as in PPKG you can not use this policy. 

For EnableFirstLogonAnimation see document https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-windowslogon#windowslogon-enablefirstlogonanimation

If there is anything else that needs to be added to the document, please feel free to let me know. 

Thanks.
Imran.

**Comment by goxia** [comment]
> @goxia - I have gone through the document and see that https://docs.microsoft.com/en-us/windows/configuration/wcd/wcd-policies#windowslogon doesn't mention to support HideFirstLogonAnimation or EnableFirstLogonAnimation. This concludes this as in PPKG you can not use this policy.
> 
> For EnableFirstLogonAnimation see document https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-windowslogon#windowslogon-enablefirstlogonanimation
> 
> If there is anything else that needs to be added to the document, please feel free to let me know.
> 
> Thanks.
> Imran.

@joinimran , Thank you.
