### ISSUE TITLE
Set value is invalid for DisplayOffTimeoutOnBattery and more 

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/windows-itpro-docs#6034]
The correct value used to disable this option is not mentioned in the document, and when the WICD help document is configured to &lt;disabled/&gt; the value, there is no failure during configuration execution, but it does not actually take effect. If the value is configured to 0, a failure occurs during configuration execution.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: efe2ec03-bfd6-c13b-0e5a-a11129342f3e
* Version Independent ID: 8151028c-e9a1-c8a4-3f5e-26d62b14b3de
* Content: [策略 CSP-Power](https://docs.microsoft.com/zh-cn/windows/client-management/mdm/policy-csp-power#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-power.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-power.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@goxia . normally display timeout start from 1 second to maximum no limit.
 I added  600 or 120 seconds in GPO

**Comment by goxia** [comment]
> @goxia . normally display timeout start from 1 second to maximum no limit.
> I added 600 or 120 seconds in GPO

To disable the timeout, write 0 is misformed and write <disabled/> according to the documentation does not take effect.

**Comment by e0i** [comment]
Thank you for the productive discussion. An indoependent contributor will follow up with a solution proposal within few days.

**Comment by VLG17** [comment]
@goxia You're using Windows Imaging and Configuration Designer to build a provisioning package and when setting the DisplayOffTimeoutOnBattery to 0 you get an error? What is the error that you are getting?

[Creating an OMA URI](https://www.prajwaldesai.com/configure-power-management-options-intune-oma-uri/) using the value 0 works, so i think it could be something specific to the ICD package or process.

> The value numbers are the time in seconds, **where “0” is never**.

Regarding disabling it, yes **_disabled_** is the correct value. If this does not work, i recommend [opening a case with support](https://support.microsoft.com/en-us/contactus/) so they can look into your deployment package .xml and into the process that you are using to deploy the package.

**Comment by goxia** [comment]
> @goxia You're using Windows Imaging and Configuration Designer to build a provisioning package and when setting the DisplayOffTimeoutOnBattery to 0 you get an error? What is the error that you are getting?
> 
> [Creating an OMA URI](https://www.prajwaldesai.com/configure-power-management-options-intune-oma-uri/) using the value 0 works, so i think it could be something specific to the ICD package or process.
> 
> > The value numbers are the time in seconds, **where “0” is never**.
> 
> Regarding disabling it, yes **_disabled_** is the correct value. If this does not work, i recommend [opening a case with support](https://support.microsoft.com/en-us/contactus/) so they can look into your deployment package .xml and into the process that you are using to deploy the package.

If set to 0, the value is not recognized when PPKG is applied.

**Comment by VLG17** [comment]
> If set to 0, the value is not recognized when PPKG is applied.

Do you mean nothing happens? As i said, setting it to 0 = never, meaning if nothing happens that expected. If you **want** tu turn off the display, you need to set a minimum of 1s.

**Comment by e0i** [comment]
Closing as the discussion seems to have been concluded. Thank you.
