### ISSUE TITLE
MFA licensing changes

### ISSUE THREAD

**Issue by JBWCowling** [MicrosoftDocs/windows-itpro-docs#6049]
Hi folks, Please update this to reflect the broader availability of Azure MFA, given that it helps this scenario - if it is freely available, perhaps the statement "some dependencies require AADP" is no longer applicable, which would remove a customer objection... KUTGW

J

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5739fab2-c6db-a7a9-b0e7-2bf4b85912a7
* Version Independent ID: 82c58053-c1d7-d938-1b0f-f3f7f70ada3b
* Content: [Planning a Windows Hello for Business Deployment - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-planning-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-planning-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@mapalko It seems like insider information is needed to address this issue. Please let me know in any way that we could help. Thanks.

**Comment by JBWCowling** [comment]
I don't want to make a mystery of it: here (https://azure.microsoft.com/en-gb/pricing/details/active-directory/) it says that MFA is free. This doc refers to the old licensing where AADP or other licences were required for MFA, so that could be changed. Also, the rather vague "there may be prerequisites which require AADP" probably refers to MFA, so this could be examined as well... HTH

J

**Comment by e0i** [comment]
@JBWCowling 
Thank you for “demystifying” the situation and let’s see what one of the independent contributors has to say about the issue.

**Comment by libbro2006** [comment]
Came here to file this issue as well. Azure MFA using Microsoft Authenticator is free as part of security defaults now. https://techcommunity.microsoft.com/t5/azure-active-directory-identity/introducing-security-defaults/ba-p/1061414

**Comment by VLG17** [comment]
@JBWCowling @libbro2006 Could you please let us know exactly which paragraph(s) you are reffering to? I don't want to assume something, that's why i want to confirm with you first.

What i see in the article is:

"_Windows Hello for Business does not require an Azure AD premium subscription. However, some dependencies do._" -> in my understanding, these dependencies do not imply MFA, but rather things like MDM auto-enrollment, Conditional Access, which require Azure AD P1/P2 subscription.

What exactly do you want to be changed?

**Comment by e0i** [comment]
The article has been revised in accordance with your feedback via #6416. Thank you.
