### ISSUE TITLE
Possibilities on HoloLens Developer Edition

### ISSUE THREAD

**Issue by SocialBrothersDEV** [MicrosoftDocs/windows-itpro-docs#605]
Hi There! Is it possible to do this on the HoloLens Developer Edition? We are in a corporate environment where we want to use the Business Store but do not know how to do this. 

I hope you can help me,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 108c471e-f724-8220-43a4-c3d3627f18b4
* Version Independent ID: 28d82e61-b7e9-f4ee-06fe-c4580d8706b8
* Content: [Install apps on HoloLens (HoloLens)](https://docs.microsoft.com/en-us/hololens/hololens-install-apps)
* Content Source: [devices/hololens/hololens-install-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/hololens/hololens-install-apps.md)
* Service: **unspecified**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
HoloLens Developer Edition can install apps through Microsoft Store or the Windows Device Portal (https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-device-portal#setting_up_hololens_to_use_windows_device_portal). Windows Holographic for Business can install apps from Microsoft Store for Business.  Your Microsoft Store for Business admin can obtain apps for offline licensing (https://docs.microsoft.com/en-us/microsoft-store/distribute-offline-apps) and add them to the Windows Device Portal to install on HoloLens Developer (https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal#install-an-app).
