### ISSUE TITLE
Surface-hub-2s-repack-12.png Image missing

### ISSUE THREAD

**Issue by ThatRobson** [MicrosoftDocs/windows-itpro-docs#6053]
Step 10 images/surface-hub-2s-repack-12.png is missing

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c79ba628-2ab2-f4ae-4171-0c0c3cfa4089
* Version Independent ID: c240bf70-39c1-c1af-4ae4-e18083959c08
* Content: [How to pack and ship your Surface Hub 2S for service - Surface Hub](https://docs.microsoft.com/en-gb/surface-hub/surface-hub-2s-pack-components#feedback)
* Content Source: [devices/surface-hub/surface-hub-2s-pack-components.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/surface-hub-2s-pack-components.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
Closing via #6303
