### ISSUE TITLE
Outdated information

### ISSUE THREAD

**Issue by wrooot** [MicrosoftDocs/windows-itpro-docs#6054]
Screenshot and text is missing new setting - Secure Launch Configuration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by wrooot** [comment]
![image](https://user-images.githubusercontent.com/7195609/74481065-b40f3300-4eba-11ea-9231-501570fef8af.png)

**Comment by e0i** [comment]
Hello, @wrooot 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.

**Comment by e0i** [comment]
@wrooot, Although late, The PR #6299 addressing this issue is still under review. Thank you for your patience with the process.

**Comment by e0i** [comment]
#6299 Has been merged. Thank you.
