### ISSUE TITLE
Broken link in "Go back to previous version - HoloLens 2"

### ISSUE THREAD

**Issue by sPoss678** [MicrosoftDocs/windows-itpro-docs#6058]
The link in step 3 of the section "Go back to previous version - HoloLens 2" downloads an empty zip file, 0 bytes. 
Link URI: "https://aka.ms/hololens2download" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dedee10f-ed03-2db2-6606-fdc546ac5308
* Version Independent ID: c9d023d1-17a5-e47a-ea5f-2c4d0c214632
* Content: [Update HoloLens](https://docs.microsoft.com/en-us/hololens/hololens-update-hololens#feedback)
* Content Source: [devices/hololens/hololens-update-hololens.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/hololens-update-hololens.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by illfated** [comment]
I think your problem is temporary, because I am currently downloading 150 MB of 3.8 GB -- 1 hour left.
(My home internet connection is via the local cable TV company.)

**Comment by sPoss678** [comment]
Agreed. I’m also able to download it now.

Sent from my iPhone

On Feb 15, 2020, at 18:07, Trond B. Krokli <notifications@github.com> wrote:

﻿

I think your problem is temporary, because I am currently downloading 150 MB of 3.8 GB -- 1 hour left.
(My home internet connection is via the local cable TV company.)

**Comment by illfated** [comment]
@e0i or @mypil 

#please-close
