### ISSUE TITLE
Autopilot reset Important text

### ISSUE THREAD

**Issue by WoutVergauwen** [MicrosoftDocs/windows-itpro-docs#6063]
This sentence makes no sense to me: "The feature for Autopilot Reset will stay grayed out, unless you reset the device using Autopilot (either using Fresh Reset or manually sysprep the device)."
Maybe it's trying to clarify that Autopilot Reset is only available for devices that have an actual Autopilot device object in Intune?
Also, Fresh Reset should be Fresh Start, but I don't see just executing that or syspreping it does not magically create an Autopilot device object (at least, not in all scenario's).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98a662f1-c2aa-33ad-0e71-d0cbb288d053
* Version Independent ID: 196f1c8d-3179-c173-194f-08bf3a6f82ca
* Content: [Windows Autopilot Reset - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-reset)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/windows-autopilot-reset.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Thank you for pointing out the possible misinterpretation of the document text.

Have I understood you correctly, that you would like to see the text below added somewhere in the page?
"Autopilot Reset is only available for devices that have an actual Autopilot device object in Intune."

Do you have a suggestion or recommendation where on the page that text should be placed?

**Comment by WoutVergauwen** [comment]
I’d prefer not to have to be the one to choose that, it’s not completely clear to me what the original intention of that remark is, so I would prefer not to make the same mistake 😊
Maybe PG can help out?

**Comment by illfated** [comment]
> I’d prefer not to have to be the one to choose that, it’s not completely clear to me what the original intention of that remark is, so I would prefer not to make the same mistake 😊 Maybe PG can help out?

Fair enough. I am not sure what "PG" means, but I am guessing it is similar to PM in the Microsoft Docs teams. Very well, I will wait for more feedback.

**Comment by WoutVergauwen** [comment]
Product Group 😊

**Comment by greg-lindsay** [comment]
Hi, I'm getting clarification now about this comment. You're right it doesn't make sense.

**Comment by greg-lindsay** [comment]
The original author of the comment is no longer with the company and nobody understand what is being conveyed here so I'm removing the statement.  I've read about the reset option being greyed out, but only when the OS version is not sufficient, and there is a note about that already.
