### ISSUE TITLE
Resolution is referring to multiple users each with their own AAD account, as opposed to multiple users with a single account

### ISSUE THREAD

**Issue by Wes777** [MicrosoftDocs/windows-itpro-docs#6064]
Previous ticket was closed incorrectly

**Comment by denisebmsft** [comment]
Hello @Wes777, is the issue that was closed incorrectly this one: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5948

**Comment by Wes777** [comment]
Yes

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by e0i** [comment]
@Wes777

Somehow your issue has been opened without being associated with a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.
