### ISSUE TITLE
Cleanup of old terminology needed

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/windows-itpro-docs#6067]
This page refers to CB and CBB multiple times, so a "cleanup" of old terminology is needed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e93c801e-9b6e-7629-7095-d4c1acc8f42e
* Version Independent ID: c75dda9d-50b2-4c11-f1af-91d1c29f7934
* Content: [Deploy Windows 10 updates via Microsoft Endpoint Configuration Manager - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-manage-updates-configuration-manager)
* Content Source: [windows/deployment/update/waas-manage-updates-configuration-manager.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-manage-updates-configuration-manager.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
yes, it is the last outlier of the antique terms. We are in the process of a complete overhaul of everything to do with Deploy and Update Windows 10 and this particular topic will be retired as part of that.

**Comment by mypil** [comment]
@baardhermansen - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author jaimeo so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by illfated** [comment]
(Ref. #6068 Update waas-manage-updates-configuration-manager.md )
