### ISSUE TITLE
These UAC options do not exist in secpol.msc (WinVer 1909 build 18363.657)

### ISSUE THREAD

**Issue by C0missar** [MicrosoftDocs/windows-itpro-docs#6069]
There are no major headers/folders, and no sub items within Local Security Policy that related to any UAC feature.  The closest items are Security Settings/Local Policies/User Rights Assignment and Security Settings/Local Policies/Security Options, neither of which address any of the UAC features discussed in this article.

The Control Panel 'User Account Control Settings' panel has a single slider to specify when the user is notified of account elevation, and it is set to "Never notify", but I still get UAC elevation prompts.

In all cases, I am using a local account with administrator privileges, and the machine is not domain joined.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c137da7-0dee-f7cd-d7af-39df9b7c7d50
* Version Independent ID: 06e5ff89-9392-d259-e431-da13e6134be0
* Content: [User Account Control security policy settings (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/user-account-control-security-policy-settings)
* Content Source: [windows/security/identity-protection/user-account-control/user-account-control-security-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/user-account-control/user-account-control-security-policy-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@C0missar . I am using windows 10 1909 18363.657 .  You said UAC options ARE STILL available  under 
 **Security Settings/Local Policies/Security Options**

here is the screenshot of GPO

![Uac01](https://user-images.githubusercontent.com/3296790/74674899-563f5b80-51d8-11ea-803c-6f8ce287085c.JPG)
![Uac02](https://user-images.githubusercontent.com/3296790/74674914-5dff0000-51d8-11ea-9647-4eddd1b20b29.JPG)

**Comment by C0missar** [comment]
Thank you, RAJU2529.  I was apparently up too late and couldn't read, looking for "Account Control: xxx" rather than "User Account Control: xxx", or (least likely) a related registry tweak I tried made them disappear.  Thanks for the screen shot; It was really helpful, as things are easy to overlook in deep menu trees - at least for me.

Thanks again.
- Stan.
