### ISSUE TITLE
Windows Defender ATP on Shared Devices

### ISSUE THREAD

**Issue by slrattan** [MicrosoftDocs/windows-itpro-docs#6070]
With the Defender ATP licensing, how does that work in regards to licensed users who access a shared device? Are we able to configure Defender ATP for that machine ?

**Comment by mypil** [comment]
@slrattan - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by slrattan** [comment]
I have an education customer that has A5 Security & Compliance Suite assigned to their M365 A3 users, however a few users share the 1 device.  The A5 Security & Compliance Suite includes Windows Defender ATP.  They have asked how this works in shared device scenario.

**Comment by mypil** [comment]
@slrattan - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
