### ISSUE TITLE
VDI hosted on Windows 2019

### ISSUE THREAD

**Issue by huuducle** [MicrosoftDocs/windows-itpro-docs#6072]
Hello, is this article applied as well for VDI hosted on Windows 2019 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84fc852e-4ce0-1d6d-fbc8-76732407e576
* Version Independent ID: 30d715c0-35f0-0b52-68da-75a5f85a619b
* Content: [Windows Defender Antivirus Virtual Desktop Infrastructure deployment guide - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/deployment-vdi-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/deployment-vdi-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/deployment-vdi-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by VLG17** [comment]
@huuducle According to the [whitepaper](https://demo.wd.microsoft.com/Content/wdav-testing-vdi-ssu.pdf), it applies also for Windows Server 2019.

> The security intelligence update is delivered as a compressed binary-similar package. Each
> individual endpoint must unpackage the update before it can apply it. This requires CPU and
> memory usage.
> With the shared security intelligence feature, the update is instead downloaded and unpackaged
> by a management machine, which could be running Windows 10, version 1903 **or Windows
> Server 2019**. Individual endpoints can then obtain the already-expanded bits and apply them
> directly to Windows Defender AV.

**Comment by mypil** [comment]
@huuducle - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17 so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
