### ISSUE TITLE
Device tags (`tags`) dictionary not listed in full config profile example

### ISSUE THREAD

**Issue by apizz** [MicrosoftDocs/windows-itpro-docs#6073]
The `tags` preference is listed as a dictionary and has associated keys `key` and `value`.  While these contained keys are listed as string values, it is uncertain whether these preferences are supposed to be able to be listed multiple times, similar to the `exclusions` preference, or only once.  While the `exclusions` preference is listed as a dictionary in the documentation, the example profile has `exclusions` as an array with contained dictionaries.

Because the `tags` preference is not listed in the full config profile example, it is unclear as to the required format for the profile.

Can the `tags` preference be added to the config profile example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5c929d-414f-70b8-c687-e9a60ef709e3
* Version Independent ID: a3cde3f5-e7a1-e0cc-aeae-fd6123f696c5
* Content: [Set preferences for Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-preferences#device-tags)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-preferences.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-preferences.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by Dansimp** [comment]
Following up on this

**Comment by rustymyers** [comment]
Can there be an example of multiple tags, too?

**Comment by apizz** [comment]
Any updates here?

**Comment by apizz** [comment]
hellooooo .... ? 👋

**Comment by rustymyers** [comment]
I don't believe it supports multiple tags at this point, so I guess we're still waiting for someone to look at it and decide if they can support it or not.

**Comment by lindspea** [comment]
@apizz Thank you for reaching out. I've been assigned this issue and will be looking into it. On a quick glace I see the article has been updated at the end of September. Please let me know if the information is still missing and if you still need assistance.

**Comment by apizz** [comment]
@lindspea it's just not totally clear what the possible values are.  The Intune example profile does lead in the right direction, but I'd like to see this documentation be more in line with the Edge enterprise docs where each listed preference has it's own example XML portion rather than having to a single big example at the bottom for admins to parse through.

```
                <key>edr</key>
                <dict>
                    <key>tags</key>
                    <array>
                        <dict>
                            <key>key</key>
                            <string>GROUP</string>
                            <key>value</key>
                            <string>ExampleTag</string>
                        </dict>
                    </array>
                </dict>
```

**Comment by apizz** [comment]
It's also not clear if there were more than one item how this should be formatted, as there's only 1 example.  Should it be something like:

```
                <key>edr</key>
                <dict>
                    <key>tags</key>
                    <array>
                        <dict>
                            <key>key</key>
                            <string>GROUP</string>
                            <key>value</key>
                            <string>ExampleTag</string>
                            <key>key</key>
                            <string>GROUP2</string>
                            <key>value</key>
                            <string>ExampleTag2</string>
                        </dict>
                    </array>
                </dict>
```

OR

```
                <key>edr</key>
                <dict>
                    <key>tags</key>
                    <array>
                        <dict>
                            <key>key</key>
                            <string>GROUP</string>
                            <key>value</key>
                            <string>ExampleTag</string>
                        </dict>
                        <dict>
                            <key>key</key>
                            <string>GROUP2</string>
                            <key>value</key>
                            <string>ExampleTag2</string>
                        </dict>
                    </array>
                </dict>
```

Either, I don't understand the design logic behind having separate key/value pairs for defining the key and value in separate keys.  It would be a lot simpler to have something like:

```
                <key>edr</key>
                <dict>
                    <key>tags</key>
                    <array>
                        <dict>
                            <key>GROUP</key>
                            <string>ExampleTag</string>     
                            <key>GROUP2</key>
                            <string>ExampleTag2</string>
                        </dict>
                    </array>
                </dict>
```

**Comment by rustymyers** [comment]
I don't think multiple tags are supported at this time, but that the later format with an array would be my preference for groups.

**Comment by apizz** [comment]
And if it is the latter format with keys and values within a dictionary, why is the `tags` key an array?  An dictionary within an array as it is now would assume that you would specify multiple dictionaries for different items.  But again, if the formatting is simplified to just use the below for separate items, then the need to have this be an array goes away:

So this:
```
                <key>edr</key>
                <dict>
                    <key>tags</key>
                    <array>
                        <dict>
                            <key>GROUP</key>
                            <string>ExampleTag</string>     
                            <key>GROUP2</key>
                            <string>ExampleTag2</string>
                        </dict>
                    </array>
                </dict>
```

Could become this:
```
                <key>edr</key>
                <dict>
                    <key>tags</key>
                    <dict>
                        <key>GROUP</key>
                        <string>ExampleTag</string>     
                        <key>GROUP2</key>
                        <string>ExampleTag2</string>
                    </dict>
                </dict>
```

**Comment by lindspea** [comment]
@Dansimp please could you assist here.

**Comment by lindspea** [comment]
@Dansimp please could you help?

**Comment by apizz** [comment]
Thank you for reviving this @lindspea

**Comment by apizz** [comment]
I'm confused why this has once again gone stale

**Comment by aczechowski** [comment]
Hi @apizz I'm doing repo cleanup and am closing this issue, mainly because the article was moved to a new repository. Check out the current article, perhaps there have been revisions since you filed this? If not, you can file new feedback in that repository to get on the radar of the current content owner. https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-preferences?view=o365-worldwide#device-tags
