### ISSUE TITLE
The details of the description timeout in the content of this document are not clear

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/windows-itpro-docs#6074]
windows/configuration/provisioning-packages/provisioning-script-to-install-app.md

> The runtime provisioning component will attempt to run the scripts from the provisioning package at the earliest point possible, depending on the stage when the PPKG was added. For example, if the package was added during the Out-of-Box Experience, it will be run immediately after the package is applied, while the out of box experience is still happening. This is before the user account configuration options are presented to the user. A spinning progress dialog will appear and “please wait” will be displayed on the screen.

> Note There is a timeout of 30 minutes for the provisioning process at this point. All scripts and installs need to complete within this time.

**The details in this document describing the timeout are not clear, and the "PrimaryContext" implementation of the app installation was added during the actual test, which took longer to take more than 30 minutes overall, but did not experience a time-out interruption.**

**Comment by MaratMussabekov** [comment]
Dear @Dansimp,
could you please have a look?
The information about 30 min timeout is not confirmed by any other source (at least publicly accessible ones). 
Also, in [this article](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-how-it-works#device-provisioning-during-oobe) it states "When the provisioning engine applies provisioning packages in the %ProgramData%\Microsoft\Provisioning folder, certain runtime setting applications, such as the setting to install and configure Windows apps, may be extended past the OOBE pass and continually be processed in the background when the device gets to the desktop."
Thank you

**Comment by mypil** [comment]
@Dansimp - Can you please share your insights on this issue?

Thank you. 

cc: @kenwith

**Comment by VLG17** [comment]
@goxia Could you please share exactly what your script is doing? Installing and configuring a certai Windows app?

I think @MaratMussabekov already provided the answer, meaning that it may be extended past the OOBE and procesed in the background, meaning what you saw, that it did not hit the 30 minutes provisioning process timeout.

**Comment by goxia** [comment]
> @goxia Could you please share exactly what your script is doing? Installing and configuring a certai Windows app?
> 
> I think @MaratMussabekov already provided the answer, meaning that it may be extended past the OOBE and procesed in the background, meaning what you saw, that it did not hit the 30 minutes provisioning process timeout.

Yes, I install applications at this stage, such as antivirus software, Windows Update patches. The actual installation time was more than 30 minutes without any timeout or abnormal interruption.

**Comment by VLG17** [comment]
@goxia

> > @goxia Could you please share exactly what your script is doing? Installing and configuring a certai Windows app?
> > I think @MaratMussabekov already provided the answer, meaning that it may be extended past the OOBE and procesed in the background, meaning what you saw, that it did not hit the 30 minutes provisioning process timeout.
> 
> Yes, I install applications at this stage, such as antivirus software, Windows Update patches. The actual installation time was more than 30 minutes without any timeout or abnormal interruption.

So you found yourself in **the scenario** identified by @MaratMussabekov, correct? In that case it's normal that you don't see the timeout. 

> "When the provisioning engine applies provisioning packages in the %ProgramData%\Microsoft\Provisioning folder, certain runtime setting applications, **such as the setting to install and configure Windows apps, may be extended past the OOBE** pass and continually be processed in the background when the device gets to the desktop."

**Comment by nam31** [comment]
@goxia The issue is being closed since your question seems to be answered. 
Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
