### ISSUE TITLE
'applies to' is listing the wrong information

### ISSUE THREAD

**Issue by AndreasDiet** [MicrosoftDocs/windows-itpro-docs#6075]
at the top of the page you can find
Windows 10
Windows Server 2016 and above

at least wrong for option 16, which can be used starting with version 1709
Server 2016 (Gui version ) is version 1607 - and therefore option 16 cannot be used here

would be good to have availability information for the single options based on version information

Windows 10 and Server 2016 is missleading for those dealing with Server with GUI or LTSB/C versions
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d4ecadb-c54e-5da1-03ae-1301a35ef64a
* Version Independent ID: 69d28732-f557-9ae1-cec4-594a2ec097a2
* Content: [Understand WDAC policy rules and file rules (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@AndreasDiet - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/17cbe48c1727bef184e25b64ae06c4e7c8c20b41. 


Thank you for your contribution to make the docs better! Much appreciated!
