### ISSUE TITLE
Syncml(500): The recipient encountered an unexpected condition which prevented it from fulfilling the request

### ISSUE THREAD

**Issue by afield1235** [MicrosoftDocs/windows-itpro-docs#6077]
Why do we have this error all of a sudden after successful encryption and device previously marked as "succeeded" Support said go to this page but the error isn't even listed here.

ERROR CODE
0x87d101f4

ERROR DETAILS
Syncml(500): The recipient encountered an unexpected condition which prevented it from fulfilling the request

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbcf9add-51a3-5275-1747-0904b061e82a
* Version Independent ID: 6fe2aba3-4c6c-4b94-1940-6169c17a3722
* Content: [Enforcing BitLocker policies by using Intune  known issues - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/ts-bitlocker-intune-issues)
* Content Source: [windows/security/information-protection/bitlocker/ts-bitlocker-intune-issues.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/ts-bitlocker-intune-issues.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by mypil** [comment]
@afield1235 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by illfated** [comment]
Likely a common problem with BitLocker + Intune Device Compliance Evaluation. Too many factors can trigger this type of error, whether it is within Windows Firewall, more than 1 user logged in on the same device, 3rd party AV software or even just trouble getting the update status from Windows Defender. For many users, the common issue seems to be how long it takes to achieve a new compliance status.

Forum thread on UserVoice:
https://microsoftintune.uservoice.com/forums/291681-ideas/suggestions/36815068-intune-device-compliance-evaluation-not-stable-fa

TechNet post with suggested solution (based on 1 user experience)
https://social.technet.microsoft.com/Forums/en-US/9aa794a9-4889-4629-bc28-acf16823cb3c/2016345612-syncml500-the-recipient-encountered-an-unexpected-condition-which-prevented-it-from?forum=microsoftintuneprod

Search for other possible answers: https://www.bing.com/search?q=0x87d101f4+SyncML+500

**Comment by afield1235** [comment]
@mypil I already opened a support ticket, they haven't resolved it yet. This should be documented in this article and should be fixed.

@illfated Thanks, User Feedback is graveyard. Seems like it exists simply to placate customers. Nothing on their is ever taken seriously or implemented.

**Comment by illfated** [comment]
@afield1235 : Thanks for the feedback. I am happy to see that you have opened a support ticket. Unfortunately, I don't know enough about this scenario, but if your computer environment is small enough, I would suggest using manual updating on the non-compliant device, or at least try to narrow down what causes the status to fall out of compliance.

I hope your efforts result in a solution and that the solution could have some or any effect on the existing documentation. If so, I would appreciate additional feedback here.

Best of luck to all of you.
