### ISSUE TITLE
Quarantine Location for Mac

### ISSUE THREAD

**Issue by phillym** [MicrosoftDocs/windows-itpro-docs#6078]
Hi there, can you please add more information on where the on-device quarantine location is for Mac?

/Library/Application Support/Microsoft/Defender/quarantine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07f72a75-ca85-0651-1512-8ffb62d0ab7b
* Version Independent ID: 6e15dd30-1db2-4a18-a18c-c343e1d508cd
* Content: [Resources for Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-resources#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by Dansimp** [comment]
Following up on this
