### ISSUE TITLE
Using MDM Bridge Provider programmatically causes permanent bluescreen on boot

### ISSUE THREAD

**Issue by thlac** [MicrosoftDocs/windows-itpro-docs#6081]
I've been trying to use your documentation, for deploying these MDM configurations programmatically, and I'm also using the samples found [here](https://github.com/microsoft/Windows-iotcore-samples/blob/master/Samples/ShellLauncherV2/SampleBridgeWmiScripts/README.md) to create a kiosk using it.

Whatever I do, as long as I do it, interactively, and as the Local System user, everything works beautifully, but as soon as I try to deploy this using our deployment tool of choice, it seems to work fine, but as soon as the system reboots, I get the BugCheck 0xC000021A (WINLOGON_FATAL_ERROR).

The documentation specifically mentions needing to be run as System, and the agent service of our deployment tool, does run as system, so I've tried the following scenarioes:

1. Run the script "as-is", so in the context the agent service is already in. Results in BSOD on reboot
2. Run the script with `psexec -i -s` to elevate to system. Works fine manually, but results in BSOD on reboot if run using the deployment tool
3. Run the script with `psexec -s` (non-interactive) to elevate to system. Works fine manually, but results in BSOD on reboot if run using the deployment tool
4. Create a task, that runs as system, with Highest Privileges option set, that runs the script. Works fine manually, but results in BSOD on reboot if run using the deployment tool

Now, considering what I can gather about 0xC000021A, to me it sounds like I've hit an intended security barrier, and the system is refusing to boot because security was compromised, but the problem I am facing is that is not documented anywhere if that is the case, and if that is the case, how does one work around it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed1e8edd-933d-9ad1-01e7-24d27ec01963
* Version Independent ID: 105c55b2-95eb-a78d-2b63-989fa9a99b7e
* Content: [Using PowerShell scripting with the WMI Bridge Provider - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/using-powershell-scripting-with-the-wmi-bridge-provider)
* Content Source: [windows/client-management/mdm/using-powershell-scripting-with-the-wmi-bridge-provider.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/using-powershell-scripting-with-the-wmi-bridge-provider.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Hello,

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) would be a more appropriate channel for this question.

The issues section of this repository is used for article corrections.

Thank you.

**Comment by thlac** [comment]
Ok, thanks anyways.
