### ISSUE TITLE
Partially investigated

### ISSUE THREAD

**Issue by mzafzal1** [MicrosoftDocs/windows-itpro-docs#6083]
please elaborate it more on how to restart or complete the investigation or why it failed to investigate. this informatio is not enough.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c29309d2-562b-7136-b5a8-cade9a2bc90f
* Version Independent ID: 7c460f4c-8808-9c39-9a49-61982cbc02ea
* Content: [Learn about the automated investigations dashboard in Microsoft Defender Security Center - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/manage-auto-investigation)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/manage-auto-investigation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/manage-auto-investigation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
It has been suggested to check _investigation logs_ for partially investigated actions.

This is suggested in the second article at the bottom of this one at the left navigation panel: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/auto-investigation-action-center#automated-investigation-status
