### ISSUE TITLE
MFA: Please clarify your position

### ISSUE THREAD

**Issue by arcotek-ltd** [MicrosoftDocs/windows-itpro-docs#6086]
Hi,
In your "hybrid" table of requirements: https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification#hybrid-deployments

You list:
Azure MFA tenant, or
AD FS w/Azure MFA adapter, or
AD FS w/Azure MFA Server adapter, or
AD FS w/3rd Party MFA Adapter

These all require AD Premium P1 / P2. I don't see any mention of Office 365 MFA in your table.

In fact, the only place O365 MFA is mentioned is here: https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs#multifactor-authentication

I'm still waiting for someone to pick up issue #5594 where I'm essentially asking the same thing.

Basically, can we get WHfB to work without buying Azure resources?

TIA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e5f5f1-16cf-57e2-bdfc-b090d90437b1
* Version Independent ID: 1662c47f-12cb-147d-25f0-dee98b6c7722
* Content: [Windows Hello for Business (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-identity-verification#hybrid-deployments)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-identity-verification.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-identity-verification.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by MaratMussabekov** [comment]
Hello,

**These all require AD Premium P1 / P2.** - AD FS w/3rd Party MFA Adapter doesn't require Azure AD Premium

**I don't see any mention of Office 365 MFA in your table.** - there is no such thing as Office 365 MFA. Some Microsoft 365 subscriptions include Azure AD Premium, which allows using MFA.

**Basically, can we get WHfB to work without buying Azure resources?** - Yes, using Azure AD Free, AD FS and third-party MFA

Thank you
