### ISSUE TITLE
Office 365 MFA

### ISSUE THREAD

**Issue by arcotek-ltd** [MicrosoftDocs/windows-itpro-docs#6087]
What about Office 365 MFA?
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install#multifactor-authentication-services

Please see issues #5594 and #6086?
TIA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4784e8f-6d35-78d8-9160-7b39832a58d8
* Version Independent ID: 7f79559a-3a6d-473b-1ec1-66746c461318
* Content: [Windows Hello for Business Key Trust New Installation - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install#multifactor-authentication-services)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
Have you tried looking for the info in the Office 365 category (https://docs.microsoft.com/Office365/)?

I would think that the page https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication should offer some help, but I could be mistaken.

**Comment by MaratMussabekov** [comment]
Hello, MFA used in Office 365 is not a separate product, Azure MFA is used for multi-factor authentication for Office products, therefore it is not mentioned here.
Thank you

**Comment by illfated** [comment]
Looks like a good answer to me. I presume this concludes the question in this ticket.
