### ISSUE TITLE
Not possible to add new MFA providers

### ISSUE THREAD

**Issue by arcotek-ltd** [MicrosoftDocs/windows-itpro-docs#6088]
Please clarify your position on:

&gt; If your organization uses Azure MFA on a per-consumption model (no licenses), then review the Create a Multifactor Authentication Provider section to create an Azure MFA Authentication provider and associate it with your Azure tenant.

https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install#azure-mfa-provider

This was disabled in 01/09/2018.

TIA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4784e8f-6d35-78d8-9160-7b39832a58d8
* Version Independent ID: 7f79559a-3a6d-473b-1ec1-66746c461318
* Content: [Windows Hello for Business Key Trust New Installation - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install#azure-mfa-provider)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
Addressed via https://github.com/MicrosoftDocs/windows-itpro-docs/commit/95a3cfe486f29d7d8439c25150b4435d1e1bc9bc#diff-59741a45c92ac2c1d148832941b0334d24ec841b519c4a0fc37b75fa0b8feb04 Thanks.

**Comment by illfated** [comment]
( commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/95a3cfe486f29d7d8439c25150b4435d1e1bc9bc )
