### ISSUE TITLE
A new alert will appear... where?

### ISSUE THREAD

**Issue by tonydowler** [MicrosoftDocs/windows-itpro-docs#6091]
The instructions say "a new alert will appear in the portal". Can you be more specific? Would this be in the Microsoft Defender ATP blade in Device Compliance in Intune? Is it the Machine List in Microsoft Defender Security Center? In the Alerts Queue? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1a58ecc-aa01-3b7a-c1f7-a039063c7c38
* Version Independent ID: b1b9a0ef-fd7e-96e2-730d-01158fb93eee
* Content: [Run a detection test on a newly onboarded Microsoft Defender ATP machine - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/run-detection-test#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/run-detection-test.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/run-detection-test.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@tonydowler  I think alert will appear in  Microsoft windows  Defender ATP portal

**Comment by bled1982** [comment]
Yes a new alert will appear in Defender ATP portal  (securitycenter.windows.com) under "Alerts Queue"
