### ISSUE TITLE
Query current version of Windows Defender Signatures with MpCmdRun.exe

### ISSUE THREAD

**Issue by tysonflint** [MicrosoftDocs/windows-itpro-docs#6092]
I'd like to be able to use a parameter on MpCmdRun.exe to perform a query for the currently installed definitions.  Currently I can get this with the following command, but it reverts my signatures.  A parameter that returns just the top portion, without the signature rollback is desired.

MpCmdRun.exe -removedefinitions

Service Version: 4.18.2001.7
Engine Version: 1.1.16700.3
AntiSpyware Signature Version: 1.309.1299.0
AntiVirus Signature Version: 1.309.1299.0

Starting engine and signature rollback to last known good signature...
Done!

Service Version: 4.18.2001.7
Engine Version: 1.1.16700.3
AntiSpyware Signature Version: 1.309.1295.0
AntiVirus Signature Version: 1.309.1295.0

After the above command, I have to undo the rollback with:
MpCmdRun.exe -SignatureUpdate
which also does not list the Signature Version that was just downloaded and installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f25443de-57f4-c8f2-fecb-f58714467894
* Version Independent ID: 1d783d00-ae0d-3eea-9a32-b42dd32e73c2
* Content: [Use the command line to manage Windows Defender Antivirus - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/command-line-arguments-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/command-line-arguments-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/command-line-arguments-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
Yes it will not show the updates

**Comment by manuelhauch** [comment]
Why don't you use _Get-MpComputerStatus_ in PowerShell? Specific use case for MpCmdRun.exe?

**Comment by denisebmsft** [comment]
Thank you @tysonflint for posting this question, and @RAJU2529 and @manuelhauch for the help. Adding on to what manuelhauch indicates, can you use Get-MpComputerStatus for what you need? https://docs.microsoft.com/en-us/powershell/module/defender/get-mpcomputerstatus?view=win10-ps

**Comment by mcbsys** [comment]
I use a batch script to call mpcmdrun.exe to update signatures. Now I have to write another script in PowerShell to show the signature versions? That is a cumbersome workaround at best. If, as documented, the tool for managing Windows Defender from the command line is an .exe program, please enhance that program to support a "-Status" parameter.

**Comment by illfated** [comment]
@mcbsys : To the best of my knowledge, I believe you should feel free to open a new ticket the regular way (from the Feedback button **[ This page ]** at the end of the page), and then reference this issue ticket in the new issue ticket. At least that is what I find the more productive way to move forward with a new issue (or continue an old one), in case you find that this is something you believe would be an improvement to the documentation.

**Comment by mcbsys** [comment]
@illfated Thanks for the reply. I believe @tysonflint's original post, as well as my comment, are requesting an enhancement to the software, not to the documentation, so this may technically be the wrong platform. Through this GitHub link, Microsoft has made it pretty easy to comment on the docs, and more importantly, an MS rep usually sees the comments and replies. One hopes that the doc authors can pass along feedback to the responsible development team. In my experience, enhancement requests submitted through Microsoft's generic feedback portals, if one can even find the right one, do not get the same attention.

**Comment by illfated** [comment]
Very well, @mcbsys, I presume that the better option to ask for improvement in Microsoft software is to use the Feedback Hub, via the Feedback Hub site, or  Microsoft Windows 10 Feedback Hub: https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app (how to use your OS Feedback Hub app).

Sorry that I could not find the GitHub Feedback Hub site on short notice, or its docs.microsoft.com Feedback Hub page equivalent.
