### ISSUE TITLE
关于“Surface 设备的 LAN 唤醒”无法实现

### ISSUE THREAD

**Issue by Axiang666** [MicrosoftDocs/windows-itpro-docs#6097]
[在此处输入反馈]
我按照官方文档“Surface 设备的 LAN 唤醒”都进行设置了，还是无法发送幻数据包使SurfaceGO从睡眠中唤醒。设置记录：https://answers.microsoft.com/zh-hans/surface/forum/all/%E5%85%B3%E4%BA%8Esurface/268ddcc6-a631-41ed-a8fe-48d556404a3e

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 51dd9415-9d0f-b23a-c6b8-73a08668eecd
* Version Independent ID: 9f1f8de8-9cdf-d0be-6dc6-c82c14c2ed03
* Content: [用于 Surface 设备（Surface）的 LAN 唤醒](https://docs.microsoft.com/zh-cn/surface/wake-on-lan-for-surface-devices)
* Content Source: [devices/surface/wake-on-lan-for-surface-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/wake-on-lan-for-surface-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
> ( from web translation engine ) :
> [Enter feedback here]
> I set it up according to the official document "Wake on LAN of Surface Device", still can't send the magic packet to make SurfaceGO wake up from sleep. Setting up records

Please note that this repository is used to improve the existing documentation pages on https://docs.microsoft.com/ when there is incorrect or missing information on the documentation pages.

For your issue, we recommend that you contact your local Microsoft Support tenant or use the Microsoft Community forum or Help pages:
- https://answers.microsoft.com/zh-CN/surface/forum
- https://support.microsoft.com/zh-CN/hub/4346532/surface-go-help

***

请注意，当文档页面上的信息不正确或丢失时，该存储库用于改进 https://docs.microsoft.com/ 上的现有文档页面。

对于您的问题，我们建议您与本地Microsoft支持租户联系，或使用Microsoft社区论坛或“帮助”页面：

https://answers.microsoft.com/zh-CN/surface/forum
https://support.microsoft.com/zh-cn/hub/4346532/surface-go-help
