### ISSUE TITLE
Where to obtain Windows 10 Enterprise ISO

### ISSUE THREAD

**Issue by simps100** [MicrosoftDocs/windows-itpro-docs#6099]
Hi,

We have Office 365 licences through a CSP which includes Windows 10 Enterprise edition.

We need to build a new Windows 10 Image to deploy through SCCM Endpoint manager, for this I require a Windows 10 Enterprise ISO, the Windows 10 media creation tool does not seem to include Enterprise, the only ISO download i can find is the Evaluation edition - can you let me know the correct way to obtain the latest Windows 10 Enterprise ISO for people licenced with Office 365 E3 CSP?

Thanks

**Comment by denisebmsft** [comment]
Hello @simps100, and thank you for your question. Your best bet is to contact the CSP where you purchased your licenses. They should be able to help you get your ISO. As this is more of a product question and not a documentation issue, I am going to close this issue out. However, please let us know if you run into any problems with our help content. Kind regards!
