### ISSUE TITLE
Missing settings group

### ISSUE THREAD

**Issue by mrolle45** [MicrosoftDocs/windows-itpro-docs#610]
This product now has a Power settings group, which is not documented currently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03e7b1f-7262-a90e-9832-a22827f1ae56
* Version Independent ID: e8de256d-1181-cc4a-e57a-a6bb197b1bf1
* Content: [Windows Configuration Designer provisioning settings (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/wcd/wcd)
* Content Source: [windows/configuration/wcd/wcd.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/wcd/wcd.md)
* Service: **unspecified**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
The power settings node is not to be used, and will not be included in future versions of the tool.
