### ISSUE TITLE
Credential Guard and virtualization base security disabling not persistent over reboots.

### ISSUE THREAD

**Issue by whoatemyjam** [MicrosoftDocs/windows-itpro-docs#6100]
https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage
tried everything from above to disabled but comes back after reboot 
What would one do to remove it or disable permanently 

Thanks

**Comment by RAJU2529** [comment]
try to  delete relative registry keys ,  and configure GPO as not configue  for the  device gaurd.

then run gpupdate  /force   in cmd .
upload the screenshots

**Comment by whoatemyjam** [comment]
hi Raju 
I guess you wanted  me to delete  these keys, as you did not specify
#########
HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\LSA\LsaCfgFlags
HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\DeviceGuard\LsaCfgFlags
HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\DeviceGuard\EnableVirtualizationBasedSecurity
HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\DeviceGuard\RequirePlatformSecurityFeatures
 #########
I did the rest  GPO setting and gpupdate 
Again i am not sure which screen shots you want but I will paste below the output of the  gpupdate command 
#######

C:\WINDOWS\system32>gpupdate /force
Updating policy...

Computer Policy update has completed successfully.
User Policy update has completed successfully.
######

The delete keys are not there after gpupdate but the error is still there 

Thanks

**Comment by RAJU2529** [comment]
@whoatemyjam . also delete all keys under  
**HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceGuard**

also tell me clearly .
you want to disable credential guard and  disable  virtualization base security ?
is your windows 10 is able to boot in normal mode ?

**Comment by mypil** [comment]
@whoatemyjam - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
