### ISSUE TITLE
Offboarding dead PC

### ISSUE THREAD

**Issue by kevintaber** [MicrosoftDocs/windows-itpro-docs#6101]
How do we offboard a PC that is no longer functioning, or stolen? I don't see a place to remove a machine from the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90534181-66c6-388c-4b09-2f358e864c78
* Version Independent ID: 927e8fa6-72c9-ff10-bd6b-ec044593da18
* Content: [Onboard Windows 10 machines using a local script - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-script#offboard-machines-using-a-local-script)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-script.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-script.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@kevintaber - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by Kongcecil** [comment]
@kevintaber 
Did you ever receive a answer from Microsoft, I have the exact same question

Thanks.
