### ISSUE TITLE
Release Version Dates

### ISSUE THREAD

**Issue by DrTeej** [MicrosoftDocs/windows-itpro-docs#6102]
Could we get the Dates of the release added to this article? It would be helpful to track in general.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 287292d6-355f-5ad8-b29d-3fcc4b2604ca
* Version Independent ID: 1bcc491b-3736-6a85-3551-7aade2ff5f8a
* Content: [What's new in Microsoft Defender Advanced Threat Protection for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-whatsnew#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-whatsnew.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-whatsnew.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by DrTeej** [comment]
Bump?

**Comment by mypil** [comment]
@Dansimp - Can you please share your insights of this issue?

Thank you.

**Comment by joinimran** [comment]
Hello @DrTeej - Thank you for your query here. As of now, this information is not available but If you want to request to add this information, please open a request using the user voice channel. 

The corresponding teams will look into this and add the required information if required. 

Thanks,
Imran.

**Comment by nam31** [comment]
@DrTeej Thank you for providing feedback.
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
