### ISSUE TITLE
Sample EMIEsitelist has mistake

### ISSUE THREAD

**Issue by lychichem** [MicrosoftDocs/windows-itpro-docs#6105]
In sample EMIESitelist, the note in XML files should start with `<!--` and ends with `-->`. No three "-" is allowed, otherwise edge will not parse this XML file.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 1d48450d-970b-bdeb-2d66-8a3a13bcd365
* Version Independent ID: cee96402-3bd8-0088-6529-af928de99df9
* Content: [使用文件和 Enterprise Mode Site List Manager（架构 v.2）将多个站点添加到企业模式站点列表（适用于 IT 专业人员的 Internet Explorer 11）](https://docs.microsoft.com/zh-cn/internet-explorer/ie11-deploy-guide/add-multiple-sites-to-enterprise-mode-site-list-using-the-version-2-schema-and-enterprise-mode-tool#feedback)
* Content Source: [browsers/internet-explorer/ie11-deploy-guide/add-multiple-sites-to-enterprise-mode-site-list-using-the-version-2-schema-and-enterprise-mode-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/internet-explorer/ie11-deploy-guide/add-multiple-sites-to-enterprise-mode-site-list-using-the-version-2-schema-and-enterprise-mode-tool.md)
* Product: **ie11**
* Technology: **internet-explorer**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Ref. #6134 **Make fix to EMIEsitelist be public** (correct branch this time)
Ref. #6106 **Fix type error in EMIESitelist sample** (first attempt)

**Comment by lychichem** [comment]
The issue was confirmed fixed on en-us page but not localized pages.

**Comment by illfated** [comment]
Hm, OK. There might be a delay in the update migrating to the translated pages, but maybe we should ask one of the localization team members about it. Even though the document page states that it was updated last time on 2017/10/24 (both for the en-us originating page and the zh-cn page using Machine Translation), the en-us page has been updated with the PR changes. (I also wonder if the removal of the blank lines at the bottom may have had some form of negative effect on the Feedback section, which seems to be missing on the en-us page now.)

@TinaMcN : Do you have any detailed insight regarding the time it takes for the changes on the en-us page to migrate to the translated pages, like the zh-cn version of the page?

**Comment by illfated** [comment]
Also, just in case the last update caused it, @Dansimp : Do you think the latest commit where 5 of 6 blank lines at the end of the page were removed may have caused the Feedback section to disappear on the en-us page?

**Comment by TinaMcN** [comment]
@illfated it usually takes up to a day for machine translated pages to be updated and up to 3 days for human translated pages.
