### ISSUE TITLE
Ambiguity in account used for Azure AD

### ISSUE THREAD

**Issue by hammar** [MicrosoftDocs/windows-itpro-docs#6107]
Hi,

I find the phrasing under https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-setup#configuring-device-admin-accounts a little unclear, specifically that which concerns setting up Surface Hub 2S for use with Azure AD -- should I in this step use an administrator account or the device account?

Best,

Karl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 307fb120-8ef9-e824-2f04-08912734c2bb
* Version Independent ID: e13b105c-6f4e-e8b7-ef13-d4e87e8cd6a5
* Content: [First time Setup  for Surface Hub 2S - Surface Hub](https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-setup#feedback)
* Content Source: [devices/surface-hub/surface-hub-2s-setup.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/surface-hub-2s-setup.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by sharkless** [comment]
I am with Karl on this one we have been fighting with this for a while now.  If we use a normal account or the device account it fails.  We can use one admin account to join these because I believe there is a limit on how many devices one user can have.  Please help!!!!

**Comment by illfated** [comment]
Maybe an outsider's perspective could be of some help here, so I will offer my take on the document and its description of first time setup (OOBE):
1. Do not run through the setup before you have decided which type of user account you have planned to use as the only device admin.
2. Whichever account type you have chosen to set as the device configuration, you can only set that user during the OOBE procedure.
3. Pick the one of the three user categories that matches your selected user account type to be your device admin.
4. Complete the setup as planned. Remember, you can not add other device admin accounts after that step is complete.

**Comment by e0i** [comment]
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
