### ISSUE TITLE
Confusing screenshot

### ISSUE THREAD

**Issue by arcotek-ltd** [MicrosoftDocs/windows-itpro-docs#6109]
This section is for "Hybrid Azure AD Joined *KEY* trust deployment", however, in your event viewer screenshot under "Provisioning", the setting "User certificate for on premise auth policy is enabled: Yes".
For key trust, should this not be set to No?

TIA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d45db5-5172-45cb-2c4d-d73a9e15d699
* Version Independent ID: fa08e81d-3307-514e-129a-843e812e97a9
* Content: [Hybrid Windows Hello for Business key trust Provisioning (Windows Hello for Business) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
Closing via #7128
