### ISSUE TITLE
When is the domain root certificate installed?

### ISSUE THREAD

**Issue by arcotek-ltd** [MicrosoftDocs/windows-itpro-docs#6110]
Hi,
I've gone through all your documentation on the subject of "*Hybrid* Azure AD Joined *Key Trust* Deployment" and I cannot find any reference to installing the domain controller's root certificate on the client?

Please confirm at what point this should be done, and the correct store. From reading third-party articles, it needs to be in the Personal User store, however, it would be good to have your official input.

Also, how do we do this when there are 1000's of client devices that require this certificate or is it a case that WHfB doesn't scale?

TIA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d45db5-5172-45cb-2c4d-d73a9e15d699
* Version Independent ID: fa08e81d-3307-514e-129a-843e812e97a9
* Content: [Hybrid Windows Hello for Business key trust Provisioning (Windows Hello for Business) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-provision.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by VLG17** [comment]
The information you are saerching for can be found in the [article about prerequisites](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs)

![image](https://user-images.githubusercontent.com/41186174/88539813-91ad4400-d01a-11ea-8be5-0cb5bf4c2790.png)
