### ISSUE TITLE
Incorrect Link

### ISSUE THREAD

**Issue by D4-AzIdentity** [MicrosoftDocs/windows-itpro-docs#6111]
The New Installation Baseline link on this page is wrong. It links over to certificate trust documentation. 
Incorrect
New Installation Baseline {"https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-new-install"}

Correct 
New Installation Baseline {"https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d87ba3ab-d8a7-d038-2f7d-886bed956394
* Version Independent ID: cb2ea1fd-6a0d-8656-0bb4-0528c65ea03f
* Content: [Configure Device Registration for Hybrid key trust Windows Hello for Business - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-devreg#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-devreg.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-devreg.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by D4-AzIdentity** [comment]
I have submitted a change request

**Comment by RAJU2529** [comment]
@D4-AzIdentity  . Please provide the  PR no for viewing the changes

**Comment by illfated** [comment]
@RAJU2529 : The PR has not been created, only a PR branch with the change applied locally: https://github.com/D4-AzIdentity/windows-itpro-docs/commit/d3cfb05e54b88324a7995356abb61593eadd1730

You can also observe the recent Pull Requests in this repository here:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pulls (default sort by: most recent)

**Comment by D4-AzIdentity** [comment]
#6111

**Comment by illfated** [comment]
Well, #6111 is this page. If you go to https://github.com/MicrosoftDocs/windows-itpro-docs there should be an extra line saying that you can compare the changes and make a pull request.

( I understand that it can be somewhat confusing when you have not used the GitHub Pull Request feature before, so ask for help if you find it too difficult.)

**Comment by RAJU2529** [comment]
@illfated Looks good to me , just now i verified the  PR for viewing

**Comment by illfated** [comment]
Well, unless you just want the MS Docs team to copy-paste and create a direct commit in the https://github.com/MicrosoftDocs/windows-itpro-docs/tree/public branch, a PR still needs to be created for that commit to be available for merging. What you commented in, is only the commit in https://github.com/D4-AzIdentity/windows-itpro-docs/tree/patch-1

 @D4-AzIdentity : You need to go to the following page to start creating the Pull Request based on your commit in your patch-1 branch:
- https://github.com/MicrosoftDocs/windows-itpro-docs/compare/public...D4-AzIdentity:patch-1 (`https://github.com/MicrosoftDocs/windows-itpro-docs/compare/public...D4-AzIdentity:patch-1`)

**Comment by ChrisKibble** [comment]
This one just caught me, too, and I noticed no PR submitted since issue was opened in April.  PR #6411 opened to resolve.
