### ISSUE TITLE
How to map custom OMA URIs for 3rd-party ADMX settings?

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/windows-itpro-docs#6112]
Ouch it took me a very long to realise from [Sample SyncML for various ADMX elements] section on how Windows "magically" translates OMA URIs to the relevant Registry key path - an _internal manifest_ ?

How is this supposed to work for ADMX files from 3rd parties with their custom software?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d3e3340-f744-af16-bfd2-3964d585e1e1
* Version Independent ID: dd074932-c941-ce52-29ce-1ec637fda651
* Content: [Understanding ADMX-backed policies - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/understanding-admx-backed-policies)
* Content Source: [windows/client-management/mdm/understanding-admx-backed-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/understanding-admx-backed-policies.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@icelava . I have seen  some companies like Adobe, google chrome have   separate policy templates which are available in their official website. I have already downloaded and added to windows 10

**Comment by icelava** [comment]
Looks like 3rd-party software don't get these "magic" black-box OMA URIs, they have to see a pathing format of

./Device/Vendor/MSFT/Policy/Config/{AppName}~{SettingType}~{CategoryPathFromADMX}/{SettingFromADMX}

with careful concatentation of all parent categories (as per categories in the .admx) between the tildes ~

**Comment by mypil** [comment]
@icelava - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
