### ISSUE TITLE
Outbound Predefined Firewall Rules insufficient for action 'block'

### ISSUE THREAD

**Issue by MustQ** [MicrosoftDocs/windows-itpro-docs#6113]
When you set the default behavior to 'block', the existing predefined firewall rules for core networking do not contain all the basic requirements to enable basic network connectivity. Network location awareness will not work correctly, and some networking features will not work. Please update the documentation to provide instructions on what is required to bring windows up to a basic functionality level or update the predefined firewall rules to contain the true minimum requirements

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fafdef5-905d-7c0f-6ff4-92b243bed80e
* Version Independent ID: 328f73c3-7276-6d2e-b5d1-0d0b31674549
* Content: [Enable Predefined Outbound Rules (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/enable-predefined-outbound-rules)
* Content Source: [windows/security/threat-protection/windows-firewall/enable-predefined-outbound-rules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/enable-predefined-outbound-rules.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
@MustQ - Thank you for your feedback. I have evaluated your request it is suggested to log a feature request so that this can be taken care of by the development team to make things better. @mypil can guide you on how to share feedback to Microsoft regarding this. 

Thanks.
Imran.

**Comment by mypil** [comment]
@MustQ - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via **[Feedback Hub](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
