### ISSUE TITLE
Do not use Intune in your examples

### ISSUE THREAD

**Issue by arcotek-ltd** [MicrosoftDocs/windows-itpro-docs#6114]
Hi,
You are using Intune in your examples. Until Intune is free, please document how certificates are published without it.

TIA

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c175ce-52a4-8b46-716f-106b4d55106c
* Version Independent ID: 374a7e9d-6e4f-f188-328b-4ca2651a9481
* Content: [Configure Azure AD joined devices for On-premises Single-Sign On using Windows Hello for Business - Microsoft 365 Security](https://docs.microsoft.com/en-gb/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base#export-enterprise-root-certificate)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by MaratMussabekov** [comment]
Hello @arcotek-ltd ,
**please document how certificates are published without it** - you cannot add certificate as trusted to AAD joined computers without intune. There is an option to add certificate manually to each computers' "Trusted root certification authorities" container, but it obviously is not appropriate for enterprises.
Thank you

**Comment by mypil** [comment]
@arcotek-ltd - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
