### ISSUE TITLE
Certificate format type missing

### ISSUE THREAD

**Issue by arcotek-ltd** [MicrosoftDocs/windows-itpro-docs#6115]
Hi,
In the section [Export Enterprise Root Certificate](https://docs.microsoft.com/en-gb/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base#export-enterprise-root-certificate) , step 8, you're missing the step on specifying the file format of the exported certificate.
DER or BASE64.

![image](https://user-images.githubusercontent.com/26305145/75198422-759a3380-5758-11ea-81c2-5961ac7bdbd8.png)

TIA

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c175ce-52a4-8b46-716f-106b4d55106c
* Version Independent ID: 374a7e9d-6e4f-f188-328b-4ca2651a9481
* Content: [Configure Azure AD joined devices for On-premises Single-Sign On using Windows Hello for Business - Microsoft 365 Security](https://docs.microsoft.com/en-gb/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base#export-enterprise-root-certificate)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by RAJU2529** [comment]
@arcotek-ltd . Add the same photo by creating PR

**Comment by MaratMussabekov** [comment]
Hello, it is not missed, it is on the Step 7: **On the Export File Format page of the wizard, click Next.**

On this step, no need to change anything, just leave it as is (DER format) and press Next

Thank you

**Comment by mypil** [comment]
@arcotek-ltd - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
