### ISSUE TITLE
Copy command is broken

### ISSUE THREAD

**Issue by laughingman42** [MicrosoftDocs/windows-itpro-docs#6117]
Remove the $ in the commands provided since clicking the copy button copies the prompt also and cannot be pasted directly to the terminal. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2197cba-30ac-1749-e25a-6f39c9ee9d20
* Version Independent ID: bcd14f13-ab59-8e69-5c83-42fee6e51f87
* Content: [Deploy Microsoft Defender ATP for Linux manually - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Hello @laughingman42. Thank you so much for letting us know about this. It's fixed, and the updates will render live soon.
