### ISSUE TITLE
Cumulative Updates

### ISSUE THREAD

**Issue by deanellerby** [MicrosoftDocs/windows-itpro-docs#6119]
In "points to consider" for Win10, it's stated:
"Windows 10 does not have the concept of a Security-Only or Monthly Rollup for updates"

Yet February 2020 saw the release of a "standalone security update".
https://support.microsoft.com/en-us/help/4524244/security-update-for-windows-10-february-11-2020

Which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a38a423b-1b80-21ff-fe10-9383c2227d7c
* Version Independent ID: ccca23b0-97e5-5f14-ee58-1eafed9e4615
* Content: [Servicing differences between Windows 10 and older operating systems - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-servicing-differences#feedback)
* Content Source: [windows/deployment/update/waas-servicing-differences.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-servicing-differences.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by jaimeo** [comment]
What it's trying to say is that there is no _cumulative_ update that contains _only_ security updates. There are, of course, cumulative updates, but they do not contain solely security updates. The very next sentence after the one you quote reads "All updates are an LCU package, which includes the last release _plus anything new_." [i.e., not just security updates; emphasis mine]

So yes, separate standalone security updates occur, like the one you cite, You can either install those by themselves as they come along or catch it in the next cumulative update (which will _also_ include updates other than security updates)--but there isn't going to be an update that is an accumulation of just the security updates.

**Comment by deanellerby** [comment]
ok, thanks, however I still think it's very misleading. 

The sentence you refer to states "**All updates** are an LCU package", which is simply not true. All Patch Tuesday updates may be LCU package, but there are some separate standalone security updates that occur which will be included in the next LCU. This is not made clear (or even acknowledged) anywhere in the document.

**Comment by jaimeo** [comment]
Fair point. Much of the topic is...suboptimally written. It's about to get replaced in a major overhaul that is underway. Would you like to propose a clarifying edit in the meantime?

**Comment by mypil** [comment]
@deanellerby - We would like to follow up. Can you please respond to the query of jaimeo?

Thank you.

**Comment by mypil** [comment]
@deanellerby - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page.
