### ISSUE TITLE
More specific whitelisting

### ISSUE THREAD

**Issue by kengoodwin** [MicrosoftDocs/windows-itpro-docs#6120]
Is it possible to be more specific in the whitelisting as I'd prefer not to have to allow access to the entirety of Azure blob storage. Can you specify the Defender ATP specific blobs, rather than just everyone's Azure storage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef3b1143-53ee-892c-59c8-5cfa12e017c2
* Version Independent ID: 29f6c231-15bd-296b-cca9-7ef6ba8192df
* Content: [Microsoft Defender ATP for Linux - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-linux#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-linux.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-linux.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by phillym** [comment]
They’re still recommending the same for Mac clients too. Got fixed for Windows a while back and so far no issues with our Mac clients: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4942

**Comment by MaratMussabekov** [comment]
Hello @kengoodwin,
as @phillym noticed, more detailed URLs could be found [here](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet).
Also, you can use the list of IP addresses published [here](https://www.microsoft.com/en-us/download/details.aspx?id=56519), for example, to whitelist blob storage for Australia SE, you can use IP addresses name "Storage.AustraliaSoutheast" 

Thank you

**Comment by phillym** [comment]
> Hello @kengoodwin,
> as @phillym noticed, more detailed URLs could be found [here](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet).
> Also, you can use the list of IP addresses published [here](https://www.microsoft.com/en-us/download/details.aspx?id=56519), for example, to whitelist blob storage for Australia SE, you can use IP addresses marked with name "Storage.AustraliaSoutheast".
> 
> Thank you

kengoodwins point, like mine before it is that it is unwise to exclude all of Azure blob storage from TLS interception and proxy auth, if those are controls you have in place already. Microsoft have specific buckets for these services and we need these to be explicitly documented so we only need to exclude the bucket DNS name and not every possible Azure Blob bucket.

**Comment by MaratMussabekov** [comment]
Dear @Dansimp,
could you please assist?
Thank you

**Comment by mypil** [comment]
@kengoodwin @phillym - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/26b93c9. 


Thank you for your contribution to make the docs better! Much appreciated!
