### ISSUE TITLE
Precedence for provisioning packages issues

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/windows-itpro-docs#6121]
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/provisioning-packages/provisioning-how-it-works.md

In this document, "Precedence for the "for the package packages" is described, where "package owner type" is only used for prioritization? Also, is the rank level of value range a higher value, the more priority it takes?

Thanks.

**Comment by joinimran** [comment]
@goxia - Thank you for your query. Please note that when there is a conflict, the provisioning are decided based on owner value and the rank number. Owner value has highest priority and then the rank value is considered. For packages with the same owner type, the package rank level determines the package from which the setting values get provisioned on the device.

Thanks.
Imran

@e0i FYI Please.

**Comment by goxia** [comment]
> @goxia - Thank you for your query. Please note that when there is a conflict, the provisioning are decided based on owner value and the rank number. Owner value has highest priority and then the rank value is considered. For packages with the same owner type, the package rank level determines the package from which the setting values get provisioned on the device.
> 
> Thanks.
> Imran
> 
> @e0i FYI Please.

Thank you. So, when the Owner value is 10, it's a higher priority than the Owner value is 20, right?

**Comment by joinimran** [comment]
@goxia - The priority affects from IT-Admin to Microsoft in descending order and within these user classes from 0 to 99. For example if you do any changes as IT Admin it always overrides settings from Microsoft no matter which priority was set. But within the same user class the rank takes effect from 0 to 99.

**Comment by goxia** [comment]
> @goxia - The priority affects from IT-Admin to Microsoft in descending order and within these user classes from 0 to 99. For example if you do any changes as IT Admin it always overrides settings from Microsoft no matter which priority was set. But within the same user class the rank takes effect from 0 to 99.

Thank you. 
I'm not good at English. So I feel it's a word game :-P
I'll change the way, which of the following will be applied.
1. IT-Admin 0
2. IT-Admin 10

**Comment by joinimran** [comment]
@goxia - In this case IT-Admin 10 will have high priority and will be considered.

**Comment by goxia** [comment]
> @goxia - In this case IT-Admin 10 will have high priority and will be considered.

At a glance, thank you.
