### ISSUE TITLE
M365 Enterprise licenses valid for local admin sign-in?

### ISSUE THREAD

**Issue by testad** [MicrosoftDocs/windows-itpro-docs#6124]
Maybe I have missed something, but I cannot find details around if the W10 Enterprise activation from a M365 E3/E5 user will license that device, or just that user? For example, will we be able to access the Enterprise features via a local admin after the device has been licensed for E3/E5 with a standard user? This is a very common scenario for occasional user support without having the user present.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation - Windows Deployment](https://docs.microsoft.com/en-gb/windows/deployment/windows-10-subscription-activation#feedback)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
The license renews every 30 days. In order for that to happen, it must be connected to the Internet and a licensed user must be signed in.  Once the license is renewed, you can sign out and sign in with a local account and Enterprise will be available.

**Comment by testad** [comment]
Many thanks @greg-lindsay. Based on your feedback I understand it this way: if the E3/E5 licence is assigned to domain user A, Windows is activated under user A’s account and the 30 day cycle is active, local user B (e.g a local admin), can sign in and access all E3/E5 settings.
