### ISSUE TITLE
[LOC] "両面" needs to be replaced with "2" (re-open issue: #4039)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#6127]
re-open issue: #4039
related issue: #3930

ja-jp:https://docs.microsoft.com/ja-jp/microsoft-edge/deploy/available-policies
![59548999-c9316c00-8f91-11e9-9930-c642d73a26a5_1](https://user-images.githubusercontent.com/40815708/75434591-2260f480-5995-11ea-954d-346ee921a6ab.png)

"件" needs to be replaced with "1"
"両面" needs to be replaced with "2"

en-us:https://docs.microsoft.com/en-us/microsoft-edge/deploy/available-policies
![59549001-d0f11080-8f91-11e9-9060-8411b12a85f0_1](https://user-images.githubusercontent.com/40815708/75434552-12e1ab80-5995-11ea-8954-cc3b2686394d.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 9aa5c0a6-acd2-4ec3-275d-3a684b3faaf4
* Version Independent ID: 6b475925-ca66-d47f-e180-92988683b37a
* Content: [Microsoft Edge のグループ ポリシーとモバイル デバイス管理の設定 (IT 担当者向けの Microsoft Edge)](https://docs.microsoft.com/ja-jp/microsoft-edge/deploy/available-policies)
* Content Source: [browsers/edge/available-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/available-policies.md)
* Product: **edge**
* Technology: **microsoft-edge**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
This issue (see also https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4039#issuecomment-606094599) seems to be resolved now.
All the tables show the values 0, 1, 2, 3 (as applicable).

**Comment by hyoshioka0128** [comment]
@TinaMcN - Fixed.
Closed #6127.
Thanks.
