### ISSUE TITLE
File has unexpected size

### ISSUE THREAD

**Issue by kazukiigeta** [MicrosoftDocs/windows-itpro-docs#6131]
## Issue
I can't install mdatp in Ubuntu19.10 with following error response. Could you tell me how can avoid it?

## This may be the cause
The expected size of mdatp is defined as 12622224 in /ubuntu/19.10/prod/dists/insiders-fast/main/binary-amd64/Packages.
However, the actual size of the mdatp package is 12622214 in /ubuntu/19.10/prod/pool/main/m/mdatp/mdatp_100.87.33.amd64.deb.

## Response
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Ubuntu 19.10"

$ sudo apt install -y  mdatp
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  mdatp
0 upgraded, 1 newly installed, 0 to remove and 132 not upgraded.
Need to get 12.6 MB of archives.
After this operation, 39.6 MB of additional disk space will be used.
Get:1 https://packages.microsoft.com/ubuntu/19.10/prod insiders-fast/main amd64 mdatp amd64 100.87.33 [12.6 MB]
Err:1 https://packages.microsoft.com/ubuntu/19.10/prod insiders-fast/main amd64 mdatp amd64 100.87.33
  File has unexpected size (12622214 != 12622224). Mirror sync in progress? [IP: 13.75.127.55 443]
  Hashes of expected file:
   - SHA512:e2c401e7152aa5b41e968f08da09c9a2abeb599c2ead4277ed4aeff5443a9b748b1625c0993e5830625a2a8a233b4341b20a52ab86593981dae894448cce347f
   - SHA256:4b1b08f952808c2b1ab0a48d1f373bcb80d595e594fc680085b8972288417353
   - SHA1:1d8283b0cae4de8ff6e87f99355bd2e2eda22ef3 [weak]
   - MD5Sum:111ab2d47864f97f4e7ecc6a5b19ab85 [weak]
   - Filesize:12622224 [weak]
E: Failed to fetch https://packages.microsoft.com/ubuntu/19.10/prod/pool/main/m/mdatp/mdatp_100.87.33.amd64.deb  File has unexpected size (12622214 != 12622224). Mirror sync in progress? [IP: 13.75.127.55 443]
   Hashes of expected file:
    - SHA512:e2c401e7152aa5b41e968f08da09c9a2abeb599c2ead4277ed4aeff5443a9b748b1625c0993e5830625a2a8a233b4341b20a52ab86593981dae894448cce347f
    - SHA256:4b1b08f952808c2b1ab0a48d1f373bcb80d595e594fc680085b8972288417353
    - SHA1:1d8283b0cae4de8ff6e87f99355bd2e2eda22ef3 [weak]
    - MD5Sum:111ab2d47864f97f4e7ecc6a5b19ab85 [weak]
    - Filesize:12622224 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2197cba-30ac-1749-e25a-6f39c9ee9d20
* Version Independent ID: bcd14f13-ab59-8e69-5c83-42fee6e51f87
* Content: [Deploy Microsoft Defender ATP for Linux manually - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by annerajb** [comment]
I got a hash mismatch on ubuntu 18.04 using fast insider track. Fix missing didn't do anything

**Comment by xlZeroAccesslx** [comment]
Something is wrong with the repository server. Try this:

```
wget https://packages.microsoft.com/ubuntu/19.10/prod/pool/main/m/mdatp/mdatp_100.87.33.amd64.deb
sudo apt install ./mdatp_100.87.33.amd64.deb
sudo apt install libproxy1v5
mdatp --health
```

**Comment by annerajb** [comment]
installing package directly works without issue.

**Comment by konstruktoid** [comment]
Verified on Ubuntu Bionic, but installing package directly works without issue.

```
~$ sudo apt-get -y update && apt-get -y upgrade
[...]
Hit:7 https://packages.microsoft.com/ubuntu/18.04/prod insiders-fast InRelease
[...]
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://packages.microsoft.com/ubuntu/18.04/prod insiders-fast InRelease' doesn't support architecture 'i386'
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  flume linux-firmware mdatp unattended-upgrades
4 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 156 MB of archives.  
After this operation, 506 kB of additional disk space will be used.
[...]
Get:2 https://packages.microsoft.com/ubuntu/18.04/prod insiders-fast/main amd64 mdatp amd64 100.87.33 [12.6 MB]
Err:2 https://packages.microsoft.com/ubuntu/18.04/prod insiders-fast/main amd64 mdatp amd64 100.87.33
  File has unexpected size (12622216 != 12622224). Mirror sync in progress? [IP: 10.7.71.35 8080]
  Hashes of expected file:
   - SHA512:e2c401e7152aa5b41e968f08da09c9a2abeb599c2ead4277ed4aeff5443a9b748b1625c0993e5830625a2a8a233b4341b20a52ab86593981dae894448cce347f
   - SHA256:4b1b08f952808c2b1ab0a48d1f373bcb80d595e594fc680085b8972288417353
   - SHA1:1d8283b0cae4de8ff6e87f99355bd2e2eda22ef3 [weak]
   - MD5Sum:111ab2d47864f97f4e7ecc6a5b19ab85 [weak]
   - Filesize:12622224 [weak]
[...]
Fetched 143 MB in 2s (62.5 MB/s) 
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/m/mdatp/mdatp_100.87.33.amd64.deb  File has unexpected size (12622216 != 12622224). Mirror sync in progress? [IP: 10.7.71.35 8080]
   Hashes of expected file:
    - SHA512:e2c401e7152aa5b41e968f08da09c9a2abeb599c2ead4277ed4aeff5443a9b748b1625c0993e5830625a2a8a233b4341b20a52ab86593981dae894448cce347f
    - SHA256:4b1b08f952808c2b1ab0a48d1f373bcb80d595e594fc680085b8972288417353
    - SHA1:1d8283b0cae4de8ff6e87f99355bd2e2eda22ef3 [weak]
    - MD5Sum:111ab2d47864f97f4e7ecc6a5b19ab85 [weak]
    - Filesize:12622224 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
~$ sudo wget https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/m/mdatp/mdatp_100.87.33.amd64.deb
--2020-03-02 14:06:36--  https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/m/mdatp/mdatp_100.87.33.amd64.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 13.80.10.205
Connecting to packages.microsoft.com (packages.microsoft.com)|13.80.10.205|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12622216 (12M) [application/octet-stream]
Saving to: 'mdatp_100.87.33.amd64.deb'

mdatp_100.87.33.amd64.deb                         100%[==========================================================================================================>]  12.04M  6.87MB/s    in 1.8s

2020-03-02 14:06:38 (6.87 MB/s) - 'mdatp_100.87.33.amd64.deb' saved [12622216/12622216]

~$ sha256sum mdatp_100.87.33.amd64.deb
5cdb3b95045b6bded3e0de60644af1c9f7f4f0ec3652e0dae940064f8a4fe452  mdatp_100.87.33.amd64.deb
~$ sudo dpkg -i mdatp_100.87.33.amd64.deb
(Reading database ... 121367 files and directories currently installed.)
Preparing to unpack mdatp_100.87.33.amd64.deb ...
Unpacking mdatp (100.87.33) over (100.87.13) ...
Setting up mdatp (100.87.33) ...
~$ sudo mdatp --health
cloudAutomaticSampleSubmission          : true
cloudDiagnosticEnabled                  : true
cloudEnabled                            : true
definitionsUpdated                      : "1583153412532"
definitionsUpdatedMinutesAgo            : 18
definitionsVersion                      : 79917
edrDeviceTags                           : []
edrEarlyPreviewEnabled                  : "disabled"
[...]
```

**Comment by annerajb** [comment]
16.04 installed from apt-get fine seems only 18.04 is the one having this sort of issues.

**Comment by xlZeroAccesslx** [comment]
19.10 as well per kazukiigeta (submitter).

**Comment by robertknutzen** [comment]
Still seeing this today on 18.04. Yea I probably could download the package and install it manually. I just sort of have a problem with my antivirus not matching the hash and going 'eh it's probably fine' and installing it anyway.

**Comment by annerajb** [comment]
It seems to now be working. did a apt-get update and was able to install on 16.04 and 18.04

**Comment by robertknutzen** [comment]
> It seems to now be working. did a apt-get update and was able to install on 16.04 and 18.04

same works for me now as well

**Comment by shawnharry** [comment]
Under Ubuntu sudo mv ./microsoft.list /etc/apt/sources.list.d is the correct path for copying the "microsoft.list" file - NOT sudo mv ./microsoft.list /etc/apt/sources.list.d/microsoft-[channel].list

**Comment by robertknutzen** [comment]
> Under Ubuntu sudo mv ./microsoft.list /etc/apt/sources.list.d is the correct path for copying the "microsoft.list" file - NOT sudo mv ./microsoft.list /etc/apt/sources.list.d/microsoft-[channel].list

It really doesn't matter. As long as its a file in the /etc/apt/sources.list.d/ directory it will work.

**Comment by mypil** [comment]
@kazukiigeta - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
