### ISSUE TITLE
If the user purposely install malwares on other computers which does not protected by windows defender or antivirus softwares. then the data will be compromised.

### ISSUE THREAD

**Issue by jemito131517** [MicrosoftDocs/windows-itpro-docs#6135]
If the user purposely install malwares on other computers which does not protected by windows defender or antivirus softwares. then the data will be compromised. 
So that's why Microsoft Gives safety precautions to all administrators , should restrict the users to installing softwares by giving only guest account.
As

_Originally posted by @RAJU2529 in https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5987#issuecomment-585071228_

**Comment by jemito131517** [comment]
> If the user purposely install malwares on other computers which does not protected by windows defender or antivirus softwares. then the data will be compromised.
> So that's why Microsoft Gives safety precautions to all administrators , should restrict the users to installing softwares by giving only guest account.
> As
> 
> _Originally posted by @RAJU2529 in [#5987 (comment)](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5987#issuecomment-585071228)_

Ma

**Comment by illfated** [comment]
#please-close (incorrect use of issue tickets)

**Comment by mypil** [comment]
@jemito131517 - Please open a new issue if you have some feedback on a particular area of the docs that we can improve on by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. 

Thank you.
