### ISSUE TITLE
Outdated Git Link

### ISSUE THREAD

**Issue by danbu** [MicrosoftDocs/windows-itpro-docs#6139]
The link to "IntuneWinAppUtil.exe command-line tool." in Appendix B (https://github.com/Microsoft/Intune-Win32-App-Packaging-Tool) is out dated the repository is now at https://github.com/Microsoft/Microsoft-Win32-Content-Prep-Tool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc63299-cc1c-e031-deb7-915914b8f94e
* Version Independent ID: 356eaba5-16b0-952f-fc19-c8d5be5feb5f
* Content: [Demonstrate Autopilot deployment - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm#appendix-b-adding-apps-to-your-profile)
* Content Source: [windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Thank you for pointing out this change. I will post a PR to have that link updated.
