### ISSUE TITLE
DynamicManagement CSP: Please include some more detailed documentation

### ISSUE THREAD

**Issue by domcote** [MicrosoftDocs/windows-itpro-docs#614]
Thanks for the XML examples, but they aren't helping me. Please provide: accepted values, syntax and description for each node. But specifically: ContextID, SignalDefinition, SettingsPack and Altitude. Most of the other CSPs are much better documented...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 482379e4-551a-fa09-9b8e-2dff29df7708
* Version Independent ID: 4982635e-c3fa-afef-e4d8-3941f391c4a1
* Content: [DynamicManagement CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/dynamicmanagement-csp)
* Content Source: [windows/client-management/mdm/dynamicmanagement-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/dynamicmanagement-csp.md)
* Service: **unspecified**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by shortpatti** [comment]
Hi @MariciaAlforque, can you take a look at this doc issue?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by TokyoScarab** [comment]
@MariciaAlforque I would love to work with you on helping expand some of these descriptions.  After looking, I found that the descriptions given in the documentation are exactly the same as what is listed in the actual DDF files.  I can edit the doc to update this, but this one area is where I'm coming into problems.  Any input you can offer would be helpful, thanks!

**Comment by mypil** [comment]
@ManikaDhiman - Can you please share your insights on how we can address this issue? Thank you.

**Comment by mypil** [comment]
@domcote - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via [Feedback Hub](https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
