### ISSUE TITLE
Typo in German Windows Security Support Contact Details

### ISSUE THREAD

**Issue by migatt** [MicrosoftDocs/windows-itpro-docs#6141]
I have found a typo in the german version of the app "Windows Security". If you click on the right bottom corner, you get the support contact details (configurable via GPO).

> wenden Sie sich an**d** den IT-Helpdesk

should be corrected to

> wenden Sie sich an den IT-Helpdesk

see screenshot

![Windows Security](https://i.imgur.com/3CK7b6N.png)

**Comment by illfated** [comment]
Knowing that this repository is only meant to deal with issues in the Microsoft Docs documentation pages, I think maybe Feedback Hub (or its web page equivalent) is a better place to report this software typo.

**Comment by migatt** [comment]
@illfated I know it sounds strange, but I didn't find a URL to give feedback normally in the browser (I don't want to use the Feedback Hub app).

**Comment by illfated** [comment]
@e0i : Would you be able to point the issue author in the right direction regarding developer feedback and software localization?

**Comment by TinaMcN** [comment]
@migatt thanks for reporting it.  I passed on to the software localization team.

**Comment by illfated** [comment]
Sounds good. Thanks for passing it on to those who can do something about it.

**Comment by migatt** [comment]
Thanks!

**Comment by TinaMcN** [comment]
@migatt the software localization team let me know that the bug is now fixed.  Thanks again for reporting it, we appreciate it!

**Comment by migatt** [comment]
You're welcome, I have also noticed that the bug has been fixed!

**Comment by TinaMcN** [comment]
@migatt thank you for confirming you can also see the fix.  If possible can you close this issue (I don't have access to do that)?
