### ISSUE TITLE
Unclear on the purpose of sending and receiving the network key encrypted by session key

### ISSUE THREAD

**Issue by TarunBarthwal** [MicrosoftDocs/windows-itpro-docs#6143]
In the section 'Phases in the Network Unlock process', the server is responding with the network key encrypted with session key (both of which the client node already has). Is there anything additional that the server is doing with those keys (that the client node could not have done)? If not, then everything that is needed to unlock the drive is already on the client node, correct?
So what is it that the client-server interaction doing specifically? Is the purpose to validate the holder of RSA private key? Is the client node verifying the network key returned by server is the same network key sent out in the DHCP request? Or does it use the encrypted intermediate key as-is in subsequent processing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c13083-9b29-e54b-fd85-8033ec665fcd
* Version Independent ID: ce8c4647-69bc-95d4-2192-6e737d5ad5da
* Content: [BitLocker How to enable Network Unlock (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock?source=docs#feedback)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @TarunBarthwal,
the error here is in the phase 3.
"Both of these keys are encrypted using the 2048-bit RSA Public Key of the Network Unlock certificate from the WDS server." - no, it contains Network Key encrypted by Public Key and a session key (which is not encrypted)
so, in fact:
1. client has a network key which is encrypted and cannot be used
2. sends it to WDS server
3. server decrypts it, and sends back
4. client uses decrypted key to unlock the volume
The core thing here is that client cannot decrypt the network key by itself as it doesn't have the private key
Thank you

**Comment by mypil** [comment]
@TarunBarthwal - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/aaa11b8b91c94933ea9687983ee0a3fc4acce0a2. 


Thank you for your contribution to make the docs better! Much appreciated!
