### ISSUE TITLE
License and organization ID not obtained

### ISSUE THREAD

**Issue by kahoso** [MicrosoftDocs/windows-itpro-docs#6145]
If you execute it with the contents described now, a problem will occur that the license and organization ID are not entered correctly. So, could you consider modifying the following?

▼Correction request details
Currently, it is the procedure to deploy "Package" after "Create JAMF policies". Problems arise with this order.
Therefore, consider distributing "Create JAMF policies" after distributing "Package". This step has already been verified. We kindly ask for your cooperation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f067243-d029-ec35-cb1d-cc271b00d0a1
* Version Independent ID: 121d2480-5bbc-9a8e-68a6-17f708dc21d4
* Content: [JAMF-based deployment for Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-install-with-jamf#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-install-with-jamf.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-install-with-jamf.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by rustymyers** [comment]
I do not understand your problem. The Jamf Policy is what deploys the package, so your wording is confusing to me. The ideal steps would be to deploy the configuration profile for licensing, then the policy to deploy the package. The reverse order will cause the Defender app to be unregistered when installed, which is not ideal for the end user experience.

**Comment by mypil** [comment]
@kahoso - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by rustymyers so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
