### ISSUE TITLE
Inactivity limit locks the device when the screensaver activates

### ISSUE THREAD

**Issue by nuttz0r** [MicrosoftDocs/windows-itpro-docs#6147]
When this setting is active, regardless of the set timeout period the device locks when the screensaver activates or when the display power timeout shuts off the display. For testing I set the screensaver to not password protected and activates after 60s with the machine inactivity limit set to 90s. The result is the screen locking after 60s. Is this expected behaviour? It's not documented here.

**Comment by mypil** [comment]
@nuttz0r - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by nuttz0r** [comment]
https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit

**Comment by MaratMussabekov** [comment]
@nuttz0r,
yes, I checked, have the same experience
I will create a PR to add it to the documentation
Thank you

**Comment by mypil** [comment]
@nuttz0r - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/5b69f422b2d5d115b64ee7106e18d8c074f37fc5. 


Thank you for your contribution to make the docs better! Much appreciated!
