### ISSUE TITLE
 Branch server

### ISSUE THREAD

**Issue by alexrangel18** [MicrosoftDocs/windows-itpro-docs#6148]
Is it possible to use a domain controller as a branch server for the MDT?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: cb440d06-32d1-c982-7736-0588cb4d8718
* Version Independent ID: 37cfa729-ee6d-3af4-dbbd-547797e37397
* Content: [Compilar um ambiente distribuído para uma implantação do Windows 10 (Windows 10)](https://docs.microsoft.com/pt-br/windows/deployment/deploy-windows-mdt/build-a-distributed-environment-for-windows-10-deployment#feedback)
* Content Source: [windows/deployment/deploy-windows-mdt/build-a-distributed-environment-for-windows-10-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/build-a-distributed-environment-for-windows-10-deployment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
I think it should be fine but I have not tried this. I do know that there are impacts on the SYSVOL folder depending on what version of Windows Server you are running, so you should read about this.

**Comment by alexrangel18** [comment]
My secondary domain controller does not have DHCP. I would like to use this only due to the fact of having storage space to synchronize the MDT directory

**Comment by mypil** [comment]
@alexrangel18 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by greg-lindsay so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
