### ISSUE TITLE
Misleading Titles "Jamf Profile" and "Configuration Profile"

### ISSUE THREAD

**Issue by rustymyers** [MicrosoftDocs/windows-itpro-docs#6153]
Just a small comment on the titles for the "Jamf Profile" and "Configuration Profile", what is shown on this page is neither. You are displaying a "Preference File" for WDAV, which can be used in a "Custom Settings Configuration Profile". It can be confusing to some when they are labeled incorrectly, which may lead to misunderstanding in deploying through Jamf. 
Once the preference file is customized to the organizations needs, it is then uploaded to Jamf into a Configuration Profile.
It is very minor, but I wanted to point out the difference for anyone confused.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5c929d-414f-70b8-c687-e9a60ef709e3
* Version Independent ID: a3cde3f5-e7a1-e0cc-aeae-fd6123f696c5
* Content: [Set preferences for Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-preferences)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-preferences.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-preferences.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @rustymyers ,
please have a look at the PR I created.
**You are displaying a "Preference File" for WDAV, which can be used in a "Custom Settings Configuration Profile"** - shouldn't it be a "Property list"?
Thank you

**Comment by mypil** [comment]
@rustymyers - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/a55054771d0f424bb38bfb371509ef35aeadd396. 


Thank you for your contribution to make the docs better! Much appreciated!
