### ISSUE TITLE
The procedure does not work for ATP Linux Onboarding 

### ISSUE THREAD

**Issue by jose-lima2011** [MicrosoftDocs/windows-itpro-docs#6154]
After doing all the steps in the document I got this error

python WindowsDefenderATPOnboarding.py
Generating /Library/Application Support/Microsoft/Defender/com.microsoft.wdav.atp.plist ... (You may be required to enter sudos password)
sudo: plutil: command not found

when typing the command mdatp --health

cloudAutomaticSampleSubmission          : true
cloudDiagnosticEnabled                  : true
cloudEnabled                            : true
definitionsUpdated                      : "1583247251971"
definitionsUpdatedMinutesAgo            : 24
definitionsVersion                      : 79924
edrDeviceTags                           : []
edrEarlyPreviewEnabled                  : "disabled"
edrMachineId                            : null
healthy                                 : false
licensed                                : false
logLevel                                : "info"
machineGuid                             : "XXXXXXXXXXXX-8f85-6ff956d7e663"
orgId                                   : null
realTimeProtectionAvailable             : true
realTimeProtectionEnabled               : true
releaseRing                             : "Production"
versionEngine                           : "100.87.66"

I run the connectivity test and everything is fine:

 mdatp --connectivity-test
Running connectivity test
Testing connection with https://cdn.x.cp.wd.microsoft.com/ping ... [OK]
Testing connection with https://eu-cdn.x.cp.wd.microsoft.com/ping ... [OK]
Testing connection with https://wu-cdn.x.cp.wd.microsoft.com/ping ... [OK]

how can I recommend a service that doesn't work for customers? I inform that I tested in all distros of the azure environment and nothing done the onboard does not happen.

the procedure and the troubleshooting is very poor let's improve this !

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: e2197cba-30ac-1749-e25a-6f39c9ee9d20
* Version Independent ID: bcd14f13-ab59-8e69-5c83-42fee6e51f87
* Content: [Implantar manualmente o Microsoft defender ATP para Linux](https://docs.microsoft.com/pt-br/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by konstruktoid** [comment]
Hi @jose-lima2011, could you include you distribution and distribution version?
I'm _guessing_ you're using RedHat due to the `plutil` error, and you'll need to install `yum-utils`.

**Comment by jose-lima2011** [comment]
> Hi @jose-lima2011, could you include you distribution and distribution version?
> I'm _guessing_ you're using RedHat due to the `plutil` error, and you'll need to install `yum-utils`.

Dear Thomas, I believe that if the solution were simple like this we would not need to post here, I did it before but here is the result: Package yum-utils-1.1.31-52.el7.noarch already installed and latest version
Nothing to do

Cent-OS version 7.7 reinforcing that Azure images are not public images

**Comment by jose-lima2011** [comment]
sudo python WindowsDefenderATPOnboarding.py
Generating /Library/Application Support/Microsoft/Defender/com.microsoft.wdav.atp.plist ... (You may be required to enter sudos password)
sudo: plutil: command not found

Ubuntu 18.04

sudo apt-get install python
Reading package lists... Done
Building dependency tree
Reading state information... Done
python is already the newest version (2.7.15~rc1-1).
The following packages were automatically installed and are no longer required:
  grub-pc-bin linux-headers-4.15.0-88
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
protlauser@SL-H-EUS-WAA01:~$ sudo apt-get install python-psutil
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-psutil is already the newest version (5.4.2-1ubuntu0.1).
The following packages were automatically installed and are no longer required:
  grub-pc-bin linux-headers-4.15.0-88
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

**Comment by konstruktoid** [comment]
Can you verify the `fanotify` isn't enabled?
`grep -i fanotify /boot/config* /proc/config*`
`for p in $(pgrep wdavdaemon); do sudo grep -R 'notify' /proc/$p/fdinfo/; done`

**Comment by jose-lima2011** [comment]
> Can you verify the `fanotify` isn't enabled?
> `grep -i fanotify /boot/config* /proc/config*`
> `for p in $(pgrep wdavdaemon); do sudo grep -R 'notify' /proc/$p/fdinfo/; done`

/boot/config-5.0.0-1032-azure:CONFIG_FANOTIFY=y
/boot/config-5.0.0-1032-azure:CONFIG_FANOTIFY_ACCESS_PERMISSIONS=y

**Comment by konstruktoid** [comment]
So I dont believe `fanotify` is disabled on your server, see my output below.

What does `sudo mdatp --threat --list --pretty` after you tried downloading the test file, `curl -o ~/eicar.com.txt http://www.eicar.org/download/eicar.com.txt`? 

I also noticed `licensed : false`, perhaps an issue?

```
$ grep -i fanotify /boot/config-$(uname -r)*
CONFIG_FANOTIFY=y
CONFIG_FANOTIFY_ACCESS_PERMISSIONS=y
$ sudo mdatp --health 
cloudAutomaticSampleSubmission          : true
cloudDiagnosticEnabled                  : true
cloudEnabled                            : true
definitionsUpdated                      : "1583323429305"
definitionsUpdatedMinutesAgo            : 47
definitionsVersion                      : 79932
edrDeviceTags                           : []
edrEarlyPreviewEnabled                  : "disabled"
edrMachineId                            : "825e75a801111f20608f0c7724468e660b42a1b3"
healthy                                 : true
licensed                                : true
logLevel                                : "info"
...
realTimeProtectionAvailable             : true
realTimeProtectionEnabled               : true
releaseRing                             : "Dogfood"
versionEngine                           : "100.87.66"
```

**Comment by jose-lima2011** [comment]
> So I dont believe `fanotify` is disabled on your server, see my output below.
> 
> What does `sudo mdatp --threat --list --pretty` after you tried downloading the test file, `curl -o ~/eicar.com.txt http://www.eicar.org/download/eicar.com.txt`?
> 
> I also noticed `licensed : false`, perhaps an issue?
> 
> ```
> $ grep -i fanotify /boot/config-$(uname -r)*
> CONFIG_FANOTIFY=y
> CONFIG_FANOTIFY_ACCESS_PERMISSIONS=y
> $ sudo mdatp --health 
> cloudAutomaticSampleSubmission          : true
> cloudDiagnosticEnabled                  : true
> cloudEnabled                            : true
> definitionsUpdated                      : "1583323429305"
> definitionsUpdatedMinutesAgo            : 47
> definitionsVersion                      : 79932
> edrDeviceTags                           : []
> edrEarlyPreviewEnabled                  : "disabled"
> edrMachineId                            : "825e75a801111f20608f0c7724468e660b42a1b3"
> healthy                                 : true
> licensed                                : true
> logLevel                                : "info"
> ...
> realTimeProtectionAvailable             : true
> realTimeProtectionEnabled               : true
> releaseRing                             : "Dogfood"
> versionEngine                           : "100.87.66"
> ```

mdatp --health
Failed to connect to the daemon. Reason: No such file or directory
["Error connecting to server socket"]

sudo apt-get  autoremove mdatp
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  grub-pc-bin libatomic1 libproxy1v5 linux-headers-4.15.0-88 mdatp
0 upgraded, 0 newly installed, 5 to remove and 4 not upgraded.
After this operation, 119 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 74586 files and directories currently installed.)
Removing grub-pc-bin (2.02-2ubuntu8.14) ...
Removing mdatp (100.87.66) ...


mdatp --health
cloudAutomaticSampleSubmission          : true
cloudDiagnosticEnabled                  : true
cloudEnabled                            : true
definitionsUpdated                      : null
definitionsUpdatedMinutesAgo            : null
definitionsVersion                      : null
edrDeviceTags                           : []
edrEarlyPreviewEnabled                  : "disabled"
edrMachineId                            : null
healthy                                 : false
licensed                                : false
logLevel                                : "info"
machineGuid                             : "624599b2-8090-244b-966e-084c9b79f050"
orgId                                   : null
realTimeProtectionAvailable             : true
realTimeProtectionEnabled               : true
releaseRing                             : "Production"
versionEngine                           : "100.87.66"

 curl -o ~/eicar.com.txt http://www.eicar.org/download/eicar.com.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    68  100    68    0     0     39      0  0:00:01  0:00:01 --:--:--    39

 sudo mdatp --threat --list --pretty

"nothing happens"



Hello Thomas tell me what does unlicensed mean? Are your tests being performed with the root user? my user is based on sudo (user created when the virtual machine was deployed)
I managed to do the onboarding of windows machines, how does mdatp verify this license? is an impediment? if so why can I access the ATP portal and join windows machines? and how can new users test the feature? shouldn't that be reported? I believe that there is a lot to be reviewed, procedures with the least privilege, troubleshooting, licensing, it is not clear what are the technical requirements and the level of product license (the trial?) Can be used. In fact I will have to wait for this product to mature and I will not be able to test its effectiveness.

**Comment by konstruktoid** [comment]
From https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-onboarding and https://docs.microsoft.com/en-us/configmgr/protect/deploy-use/windows-defender-advanced-threat-protection.

```
Prerequisites
* Subscription to the Microsoft Defender Advanced Threat Protection online service
```
```
Licensing requirements

Microsoft Defender Advanced Threat Protection requires one of the following Microsoft Volume Licensing offers:

    Windows 10 Enterprise E5
    Windows 10 Education E5
    Microsoft 365 Enterprise E5 which includes Windows 10 Enterprise E5
```

**Comment by maximvelichko** [comment]
Can you please confirm that you downloaded a **Linux server** onboarding package?
`plutil` is from the **macOS** onboarding script

**Comment by jose-lima2011** [comment]
> Can you please confirm that you downloaded a **Linux server** onboarding package?
> `plutil` is from the **macOS** onboarding script

Hello Max, thanks for asking, so we have a problem, the published document shows linux servers, on my onboard it shows the option (linux, MacOs, IOs and Android) and the options installation package and onboard package which one is correct and which command? thanks !

**Comment by maximvelichko** [comment]
@jose-lima2011 , if you don't see a Linux server option then it most probably means that your tenant is not enrolled for preview features. You/Your ATP tenant administrator needs to enable preview features for your tenant first. 

This documentation is correct. Onboarding package for other platforms would not work.

**Comment by jose-lima2011** [comment]
> @jose-lima2011 , if you don't see a Linux server option then it most probably means that your tenant is not enrolled for preview features. You/Your ATP tenant administrator needs to enable preview features for your tenant first.
> 
> This documentation is correct. Onboarding package for other platforms would not work.

Well, if this information were explicit in the documentation, we might not have had this long discussion and spent time there so there is documentation to enable the preview? Thank you again.

**Comment by jose-lima2011** [comment]
> @jose-lima2011 , if you don't see a Linux server option then it most probably means that your tenant is not enrolled for preview features. You/Your ATP tenant administrator needs to enable preview features for your tenant first.
> 
> This documentation is correct. Onboarding package for other platforms would not work.

Well, if this information were explicit in the documentation, we might not have had this long discussion and spent time there so there is documentation to enable the preview? Thank you again

**Comment by jose-lima2011** [comment]
Hello folks after a lot of discussion and also patience on the part of you, I managed to test the product, but I stress that the detail of enabling the insider option should be made explicit in the implementation documentation so we would not waste this time, thank you all!

**Comment by illfated** [comment]
Thank you for this feedback and for keeping up with the issue. 👍

**Comment by rcmpgi** [comment]
I just had this too. The GUI design is not exactly very intuitive because the dropdown list option on the onboarding page says "**Linux, macOS, iOS and Android**. So then you click the button to download the onboarding package and completely miss that the section is titled _Onboard MacOS devices..._
So that is the root of the problems - it gives you an option that looks like you're getting some kind of magic onboarding package that'll do "everything that's not Windows" but then actually only gives you stuff for macOS.

Now I admit that if you follow the link from https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually and look at the prereqs then that does say that it's in preview for linux, but the linux onboarding page itself does not - further adding to the confusion. Yes of course everyone should read prereqs first, but quite evidently several of us didn't... ;-)

So i would suggest that you please change the onboarding dropdown so that it has macOS on it's own line, and then Linux, iOS and Android on a separate line - and when you choose that option it tells you that you need to enable the preview setting.
