### ISSUE TITLE
Encountered Error Couldn't load the type  'OpenQA.Selenium.Internal.IWrapsElement' from assembly 'WebDriver Edge Chromium

### ISSUE THREAD

**Issue by thugsmca** [MicrosoftDocs/windows-itpro-docs#6158]
I'm working in multiple browser testing. It was working code with chrome browser. Recently I have installed "Install-Package Selenium.WebDriver -Version 4.0.0-alpha04".

MSedge Chromium and chrome working in setup method, But while navigate/return back to actual [Test] test method encountered the below error.

Error:Message: System.TypeLoadException : Could not load type 'OpenQA.Selenium.Internal.IWrapsElement' from assembly 'WebDriver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

Is this dll/package confused

    [SetUp]
    public void Setup()
    {
       string Browsername = "Chrome";
       switch (Browsername)
       {
          case "Chrome":
          driver = new ChromeDriver();
       }
    }

    [Test]
    [Obsolete]
    public void XXXX()
    {
        try
        {
           driver.Navigate().GoToUrl(UrlList.XXXX_Login);
           driver.Manage().Timeouts().ImplicitWait (TimeSpan.FromSeconds(200));
           driver.Manage().Window.Maximize();
           Login login = new Login(driver);
           login.PerformLogin(Login.email_id1, Login.pswd1);
        }
    }

**Comment by mypil** [comment]
@thugsmca - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
