### ISSUE TITLE
Unclear

### ISSUE THREAD

**Issue by wolskyr** [MicrosoftDocs/windows-itpro-docs#616]
It is not completely clear if this is four separate scenarios or if all are applicable from the top down.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb62871d-73d9-76d1-7afe-b580f0aa517c
* Version Independent ID: d2dd9496-47e0-4ed2-f3f0-2e01a3b4f6dd
* Content: [Hybrid deployment (Surface Hub)](https://docs.microsoft.com/en-us/surface-hub/hybrid-deployment-surface-hub-device-accounts)
* Content Source: [devices/surface-hub/hybrid-deployment-surface-hub-device-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/hybrid-deployment-surface-hub-device-accounts.md)
* Service: **unspecified**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
There are two major divisions: Exchange on-premises and Exchange online. For each of those environments, there are instructions for the three types of Skype for Business: online, on-premises, or hybrid.

**Comment by wolskyr** [comment]
And for Exchange hybrid ... unclear. Easy enough to work out, but still
unclear.

**Comment by jdeckerms** [comment]
If you have any suggestions for making it clearer, I'd be glad to hear them. :)

**Comment by mdlister** [comment]
The documentation isn't clear on the last part of the hybrid process. From what I've understood, you can't move a csmeetingroom and only csusers can be moved to Skype Online and you need to use the moveCSUser cmdlet. 
But it doesn't mention if you need to change it back to a CSMeetingRoom once it is in Skype Online as it states in the same paragraph that "The Surface Hub requires skype account of the type "meetingroom".

**Comment by wolskyr** [comment]
Yes, the documentation mentions all but an Exchange Hybrid scenario, which is probably the most common! We found that we had to provision both Lync and Exchange on-prem and then migrate both services to the cloud in order to get everything working. This is not mentioned in the docs at all.

**Comment by jdeckerms** [comment]
Thanks for the suggestions! I checked with the engineering team and found that Move-CsMeetingRoom is now supported, so the topic will be updated today with that information as well as some guidance they provided for Exchange Hybrid.

**Comment by mdlister** [comment]
That's great, I'll try that in the office tomorrow.
