### ISSUE TITLE
solution: "To fix your apps by installing the problematic fonts (recommended)" is not worked for me

### ISSUE THREAD

**Issue by hello-chenchen** [MicrosoftDocs/windows-itpro-docs#6167]
there is a demo code for this problem:
```html
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=Edge">
    <title>Demo</title>
    <link rel="stylesheet" href="https://appsforoffice.microsoft.com/fabric/2.1.0/fabric.min.css">
    <link rel="stylesheet" href="https://appsforoffice.microsoft.com/fabric/2.1.0/fabric.components.min.css">
    <script src="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/js/fabric.min.js"></script>
</head>
<body>
    <div class="ms-Grid">
        <div class="ms-Grid-row" style="padding-top:20px">
            <div class="ms-ChoiceField" style="padding-left: 8px; padding-right: 8px;">
                <input id="keepSignIn" class="ms-ChoiceField-input" type="checkbox">
                <label for="keepSignIn" class="ms-ChoiceField-field" style="line-height : 18px">
                    <span class="ms-Label">Can't checked</span>
                </label>
            </div>
        </div>
    </div>
</body>
</html>
```

and this is the error screenshot:
![image](https://user-images.githubusercontent.com/1878089/74697843-dbf1f400-5236-11ea-863f-4ec4eb5be92f.png)

The error said that the "office365Icons" is untrusted, so i installed "office365Icons.ttf", but it seams not worked for me, the error log is still here.

![image](https://user-images.githubusercontent.com/1878089/74629572-831d4f80-5193-11ea-98e2-7960f035417c.png)

So, do you have any suggestion for this error?

the seam error is happened on office365 outlook online, for more details you can see the link: https://github.com/OfficeDev/office-js/issues/989
thanks a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91a1567e-cc12-b203-65ac-5023aa3997f7
* Version Independent ID: 946c6dcf-3ee7-47c3-a973-edbf955da875
* Content: [Block untrusted fonts in an enterprise (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/block-untrusted-fonts-in-enterprise)
* Content Source: [windows/security/threat-protection/block-untrusted-fonts-in-enterprise.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/block-untrusted-fonts-in-enterprise.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by hello-chenchen** [comment]
hi @lindalu-MSFT, there isn't have any update about this problem. At the same time, I really don’t know who to contact for this issue. Could you please help me to contact some one who knows this problem or change the label to  Needs: attention?
thank you so much.

**Comment by e0i** [comment]
Hello, @hello-chenchen The sample code is under investigation. Thank you for providing feedback.

**Comment by joinimran** [comment]
@hello-chenchen - Thank you for your query. I have tested the code on both internet explorer and Microsoft Edge and the code is executing fine. There is no error showing by running this code. 

![image](https://user-images.githubusercontent.com/47118050/77459702-f284ff80-6e21-11ea-9b2b-6e336ee35a62.png)

![image](https://user-images.githubusercontent.com/47118050/77459703-f31d9600-6e21-11ea-93a7-1777f107a035.png)

As you can see that there is no error showing for the code execution. Can you please try to run this code on any other machine or try updating your Windows OS to the latest release. I have tested this on Windows 10 1909 release. 

Thanks.

**Comment by hello-chenchen** [comment]
hi @joinimran , thank you for your reply.
so, did you block the untrusted fonts?
my question is under this document for [block-untrusted-fonts-in-enterprise](https://docs.microsoft.com/en-us/windows/security/threat-protection/block-untrusted-fonts-in-enterprise)

![image](https://user-images.githubusercontent.com/1878089/77508058-c5c5fc00-6ea4-11ea-9162-488ff8bdd928.png)

my windows 10 version are 1903 and 1703 release, both have this problem.
So you mean, when i update my windows 10 version to 1909, it will be fixed?

**Comment by joinimran** [comment]
I have enabled blocked untrusted fonts settings via GPO and its still working fine for me. No errors on the console. You can test it using VM running Windows 10 version 1909. This may help. Here are latest screenshots.

![image](https://user-images.githubusercontent.com/47118050/77540139-61b33000-6ec4-11ea-85e5-610ca008d44e.png)


![image](https://user-images.githubusercontent.com/47118050/77540171-6d9ef200-6ec4-11ea-8050-56547470d350.png)

If there is still an issue after upgrading to 1909, please open a support case with Microsoft.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@e0i FYI Please.

**Comment by hello-chenchen** [comment]
hi @joinimran , thank you so much. I have tested on 1909, and it worked for me, this can fix my problem. You guys are amazing.

And a last question, Is there a patch package for the versions below 1909? such as 1903 and 1703?
Thanks a lot.

**Comment by joinimran** [comment]
@hello-chenchen - Its good that it worked for you. I am not sure about any patch for previous versions. Please go ahead and open a support case that will surely help you to get more details from the product teams.

Thanks.

**Comment by e0i** [comment]
@hello-chenchen 

Closing via *jonimran's* comments.

Please find the appropriate support channel here:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
