### ISSUE TITLE
Deployment Models

### ISSUE THREAD

**Issue by 404cruX** [MicrosoftDocs/windows-itpro-docs#6168]
3 Deployment models: Cloud, Hybrid, On-prem "Windows Hello for Business has two deployment models: Hybrid and On-premises." 

Cloud deployment is missing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3b8524-491d-7f49-0445-a34ed47d504c
* Version Independent ID: 1106b56a-45f9-9465-7c7c-2fa9a68ca807
* Content: [Windows Hello for Business Deployment Guide - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-guide)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-deployment-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-deployment-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mypil** [comment]
@404cruX - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/e5fe25d20a02a216ab586c77f4925c622e584335. 


Thank you for your contribution to make the docs better! Much appreciated!
