### ISSUE TITLE
Applocker requires win10 ENT or EDU, not just "Windows 10"

### ISSUE THREAD

**Issue by jeffstokes72** [MicrosoftDocs/windows-itpro-docs#617]
Please fix in the doc when you can.

Thanks,
jeff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f02c58f-4575-3991-8bee-ccea6c3b3d34
* Version Independent ID: 6b3f5a69-1425-8b36-9e7a-b965fc70a164
* Content: [Requirements to use AppLocker (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/applocker/requirements-to-use-applocker#feedback)
* Content Source: [windows/security/threat-protection/applocker/requirements-to-use-applocker.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/applocker/requirements-to-use-applocker.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by shortpatti** [comment]
@Justinha -- Can you take a look at this issue?

**Comment by jeffstokes72** [comment]
Hi @justinha how you doing? The official doc for this that I found https://www.microsoft.com/en-us/WindowsForBusiness/Compare is clear, but all the docs.microsoft.com never specify this. Hope that helps.

**Comment by Justinha** [comment]
Hi @jeffstokes72 I am well, thanks. Hope you are too! Thanks for opening this issue too. I confirmed with engineering Win10 Pro is supported when managed via MDM. The Notes column for Windows 10 row is correct. I'll submit a request to add a check to Po column in compare editions topic, with footnote regarding management via MDM. Does that work?

**Comment by jeffstokes72** [comment]
Ah interesting, so Pro with MDM is good, but not the traditional GPO? Yeah
that's a good call out if that's the case.

**Comment by jeffstokes72** [comment]
Doing well by the way, thanks for asking :)

**Comment by Justinha** [comment]
You're right, any edition supported by MDM. I'll add that to the table. Reference Windows 10 Pro was to the AppLocker row here: https://www.microsoft.com/en-us/WindowsForBusiness/Compare. It should have a check mark with a footnote that says Win10 Pro is supported when managed via MDM. I'm told that https://www.microsoft.com/en-us/WindowsForBusiness/Compare will soon be updated (or more likely replaced with a new page).

**Comment by aaronssh** [comment]
It is still not clear to my when Applocker is supported. There is mention here of "MDM" but when a google search on Microsoft MDM returns the mobile device manager. Please add enough info to this page so that we can understand whether we need Win10Ent to use applocker or whether we can use it with Win10Pro
