### ISSUE TITLE
Link to SCCM Blog are broken

### ISSUE THREAD

**Issue by aperally** [MicrosoftDocs/windows-itpro-docs#6174]
The articles refers to these URLs for details on the subject, they are both broken:
https://go.microsoft.com/fwlink/p/?LinkId=620205
https://go.microsoft.com/fwlink/p/?LinkId=620206

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b219752-5b81-09d4-80fc-3001bbb94ce8
* Version Independent ID: 8353d70e-3f35-bf29-a266-6d50c4648b50
* Content: [Perform in-place upgrade to Windows 10 via Configuration Manager - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-to-windows-10-with-system-center-configuraton-manager)
* Content Source: [windows/deployment/upgrade/upgrade-to-windows-10-with-system-center-configuraton-manager.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/upgrade-to-windows-10-with-system-center-configuraton-manager.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@aperally - Thank you for submitting feedback.

According to the author greg-lindsay, this entire doc set has been rewritten as shown on this https://github.com/MicrosoftDocs/windows-itpro-docs/pull/6281#issuecomment-601791395.


Thank you for your contribution to make the docs better! Much appreciated!
