### ISSUE TITLE
ADK Installation Info Missing/Incorrect

### ISSUE THREAD

**Issue by iUnknwn** [MicrosoftDocs/windows-itpro-docs#6181]
Depending on what components of the ADK are selected when installed, it is possible ReAgent.dll and the associated files will not be included (on my ADK install, for example, there was no 'Windows Setup' folder under the ADK root, nor in the WinPE root. 

Please expand the Workaround to state which components of the ADK must be installed to get the ReAgent.dll (there isn't a Windows Setup component in the linked 1903 ADK). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73c22f0-cb0d-e34b-29d8-06829b86784f
* Version Independent ID: 083115ed-f1be-e962-5b0e-5079dec37353
* Content: [MBR2GPT - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/mbr-to-gpt#feedback)
* Content Source: [windows/deployment/mbr-to-gpt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/mbr-to-gpt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
It appears that the Windows Setup\amd64\Sources is added when you install USMT.  I'll add this detail.

**Comment by e0i** [comment]
@greg-lindsay Assigning this to an independent contributor. Thank you for the hint.

**Comment by e0i** [comment]
Closing via #6315. Thank you.
