### ISSUE TITLE
First Class Setting section for each CSP to remove potential for CSP setting conflicts

### ISSUE THREAD

**Issue by robdwhitehead** [MicrosoftDocs/windows-itpro-docs#6184]
It would be nice if there was a section within each CSP to advise if the CSP has been surfaced within the Intune MDM and can be configured as a First Class Setting rather than configured  as a Custom OMA-URI setting.  This would then save considerable time checking the Intune MDM settings within the UI to see if the setting has already surfaced.  Just a section to indicate if the setting has already surfaced within the Intune MDM e.g. Yes/No and it would be great if the setting location within the Intune MDM was detailed as well.  This way, it prevents duplication/conflicts when you configure a First Class Setting within the Intune MDM UI and then add it in as well as a custom OMA-URI setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 393fcbf0-cfb3-e921-b96d-79abda94bd88
* Version Independent ID: 634fbc24-d5f3-70b6-3db1-76c0ad853977
* Content: [Configuration service provider reference - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference)
* Content Source: [windows/client-management/mdm/configuration-service-provider-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/configuration-service-provider-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@ManikaDhiman Please advise whether independent contributors could be of any help in resolving this issue. Thank you.

**Comment by robdwhitehead** [comment]
@e0i Thank you.

**Comment by ManikaDhiman** [comment]
Hi @Dansimp, could you advise if independent contributors can handle the updates for this issue?

Thanks!

**Comment by e0i** [comment]
@ManikaDhiman We are going to give it a try, then :)

**Comment by joinimran** [comment]
Hello @robdwhitehead - Thank you for your feedback here. Please note that it is not possible to make this information available on this document. This document presents the bigger picture of the CSP applications. These CPS are introduced and made available in different editions and versions of Windows. As new versions released, new CSPs are introduced and some are even deprecated. Providing all this information here will make it more difficult for users to understand these CSPs.

Thanks.

**Comment by robdwhitehead** [comment]
Thanks folks for looking at this for me.  Appreciate your efforts in this.
