### ISSUE TITLE
Monitor update Compliance

### ISSUE THREAD

**Issue by jeffa36** [MicrosoftDocs/windows-itpro-docs#6186]
Should we still be referencing Windows Analytics on this page as a way to monitor DO?  WA was deprecated on January 30th 2020.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d745280-391c-4f6d-6a35-7125fa263548
* Version Independent ID: 0ccd8add-b5fb-469c-509e-e009c43a00ac
* Content: [Set up Delivery Optimization - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization-setup#feedback)
* Content Source: [windows/deployment/update/waas-delivery-optimization-setup.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-delivery-optimization-setup.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
You are right--we should not. I'll do a scour of the whole repo in case we missed others. BTW, WA was *removed* or *retired* on 30 January. It was deprecated prior to that.

**Comment by jaimeo** [comment]
Fixed in https://github.com/MicrosoftDocs/windows-docs-pr/pull/2229. Thanks for pointing this out!

**Comment by e0i** [comment]
@jeffa36 As mentioned by the document author, **jaimeo**, closing via the following merged commit,

[[f9aa991] removed stray references to Windows Analytics ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/f9aa9911147c47f12eee98f9da0b57bf73d26959#diff-0dc51ebf293bfdee046538d293306c41)

Thank you for taking the time to provide feedback.
