### ISSUE TITLE
Surface Laptop 3 15" AMD Based and 1809 drivers

### ISSUE THREAD

**Issue by seamonkey420** [MicrosoftDocs/windows-itpro-docs#6190]
WTF?? why can't i find the 1809 drivers for our Surface Laptop 3 15" based on AMD? i can find 1903 and 1909 but no 1809.  also why are the MSI's requiring a specific build of Win10 to install??? drivers on 1909 should work on 1803 and 1809 unless you don't know how to make drivers.  guess i'll be forced to use ORCA to hack your msi so it won't check the win10 build version.  again, why do you make things so hard when it should be SO EASY.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b195b1b-81bf-310e-3ff4-e520826e7e94
* Version Independent ID: fb399be5-9fb5-a3f9-f912-ed3fde235f05
* Content: [How to enable the Surface Laptop keyboard during MDT deployment - Surface](https://docs.microsoft.com/en-us/surface/enable-surface-keyboard-for-windows-pe-deployment)
* Content Source: [devices/surface/enable-surface-keyboard-for-windows-pe-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/enable-surface-keyboard-for-windows-pe-deployment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by seamonkey420** [comment]
btw.. https://www.microsoft.com/en-us/download/details.aspx?id=100428
says it should work on all win10 but when trying to install in win10 1809; OS is not supported.

**Comment by seamonkey420** [comment]
btw.. here is how to install drivers for the Surface Laptop 3 15" with AMD cpu/gpu that is running Windows 10 1809 enterprise.
1. extract contents of MSI using the msiexec /a nameofsurfacemsi targetdir=c:\surface3
2. open up command prompt as admin and then cd to C:\surface3 where drivers were extracted.
3. run this command in command prompt: cmd.exe /c start /wait /min cmd /c "pnputil.exe /add-driver *.inf /install /subdirs & exit /b 0"
4. this will install all inf / drivers in sub dirs (this is what the official msi will run if you are on 1903 or above)
5. go into device manager and then scan for new hardware.
6. smile as you can finally use the touchscreen, keyboard and touchpad on the surface without having to be on 1903 or above.
7. complain to microsoft since they didn't need to force the build version of win10 os since all drivers work fine on 1809.

**Comment by seamonkey420** [comment]
ok, i lied, not all drivers work but most do. still have 7 unknown devices. microsoft does realize that enterprises can run 1809 for another year at least and some of us may have surface devices (well, we won't be after this experience w/the surface laptop 15" AMD based).

**Comment by mypil** [comment]
@seamonkey420 - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice via **[Feedback Hub](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
