### ISSUE TITLE
BitLocker and offloading encryption.

### ISSUE THREAD

**Issue by Kristof-Mattei** [MicrosoftDocs/windows-itpro-docs#6191]
&gt; BitLocker supports offloading encryption to encrypted hard drives.

Is this still the case? 

https://portal.msrc.microsoft.com/en-us/security-guidance/advisory/ADV180028
and
https://support.microsoft.com/en-us/help/4516071/windows-10-update-kb4516071

Quote from second link:
&gt; Changes the default setting for BitLocker when encrypting a self-encrypting hard drive. Now, the default is to use software encryption for newly encrypted drives. For existing drives, the type of encryption will not change. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29116f85-264f-d031-be7b-e32a1816cd28
* Version Independent ID: 640478e6-a367-4e47-a177-3a10dd006d1c
* Content: [Overview of BitLocker Device Encryption in Windows 10 - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10#feedback)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @Kristof-Mattei ,
yes, it is still supported.
it is not recommended (as it is stated in your first link), but it is still an option, so I think as the article is an overview of features, there is no need to change anything here.
What do you think?
Thank you

**Comment by Kristof-Mattei** [comment]
While this is indeed still supported, it is not clear in the first link that the default is Software, hence my confusion.

**Comment by mypil** [comment]
@Kristof-Mattei - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
