### ISSUE TITLE
DG_Readiness_Tool - missing download link

### ISSUE THREAD

**Issue by igpit** [MicrosoftDocs/windows-itpro-docs#6195]
1. this page is missing a download link
2. the download page https://www.microsoft.com/en-us/download/details.aspx?id=53337 seems to show an outdated version 3.6?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#feedback)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by beerisgood** [comment]
Yes this was already post several times

**Comment by RAJU2529** [comment]
@igpit , download link is already mentioned in this article .
check below sentence in this article 

You can also disable Windows Defender Credential Guard by using the Windows Defender Device Guard and Windows Defender Credential Guard hardware readiness tool.

**Comment by illfated** [comment]
Compare with the following issues from the same page:
- #5690 **There is a v3.7 of the 'DG & DC Readiness tool**
- #5972 **Typo in "Review Windows Defender Credential Guard performance"**
- #6054 **Outdated information**
- #6055 **Limited information**

**Comment by illfated** [comment]
See the updated page 
- https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg-readiness-tool
(Readiness Tool Version 3.7 Release)

**Comment by mypil** [comment]
@igpit - Thank you for submitting feedback.

From our understanding, the issue has already been resolved. 


Thank you for your contribution to make the docs better! Much appreciated!
