### ISSUE TITLE
url

### ISSUE THREAD

**Issue by Swatchel** [MicrosoftDocs/windows-itpro-docs#6196]
url http://download.microsoft.com/download/WindowsInstaller/Install/2.0/W9XMe/EN-US/InstMsiA.exe is unreachable now.
Please fix this url in your code

**Comment by denisebmsft** [comment]
Hello @Swatchel, thank you for the feedback! Can you please tell us which article has this link? It will help us route the issue to the correct team/writer.

**Comment by illfated** [comment]
@Swatchel : We are happy to oblige, as long as you tell us which page this is about, so we can make the necessary changes.

**Comment by illfated** [comment]
Oh well. Seems this is not based on any Microsoft Docs page at all, but instead a software package linking that file for download.

See also https://github.com/ddavison/greenshot/issues/1 for the originating issue. I don't think there is much we can do here from any of the MS Docs pages.

**Comment by illfated** [comment]
#please-close
