### ISSUE TITLE
deutsche Übersetzung des Artikels

### ISSUE THREAD

**Issue by schnadoslin** [MicrosoftDocs/windows-itpro-docs#6197]
Kapitel Richtlinienverwaltung
Paragraph Befehlszeilentools
Original: "Für weitere Informationen geben Sie fsutil Verhaltens Satz symlinkevalution/? ein. an der Eingabeaufforderung aus."
Der Befehl sollte nicht übersetzt werden: fsutil behavior set symlinkEvaluation /?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7509570d-b0f5-9719-5105-577af3969fd0
* Version Independent ID: 5867d113-fcbc-6005-2f13-eb7a942f8f80
* Content: [Erstellen symbolischer Links (Windows 10) - Windows security](https://docs.microsoft.com/de-de/windows/security/threat-protection/security-policy-settings/create-symbolic-links#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/create-symbolic-links.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/create-symbolic-links.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by TinaMcN** [comment]
@RCHST Vielen Dank, dass Sie über dieses Problem berichtet haben.   Es scheint ein Problem mit unserem maschinellen Übersetzungstool zu sein.  (Thank you for reporting this issue.   It appears to be a problem with our machine translation tool.)  @OfficeGlobal Bitte Menschen übersetzen diesen Artikel.  (Please human translate this article.)

**Comment by OfficeGlobal** [comment]
Working on it

**Comment by illfated** [comment]
A practical way to avoid translating a typical command like that, would be to enclose it in MarkDown back ticks to separate it from ordinary freetext.
Feel free to comment on if you would like that to be used in the English article.

**Comment by mypil** [comment]
@OfficeGlobal - Do you have any updates on this?

Thank you.

**Comment by illfated** [comment]
The reported section seems to be correct now: https://docs.microsoft.com/de-de/windows/security/threat-protection/security-policy-settings/create-symbolic-links#befehlszeilentoolscommand-line-tools
> **Befehlszeilentools**
>
> Diese Einstellung kann in Verbindung mit einer Dateisystemeinstellung für symbolische Verknüpfungen verwendet werden, die mit dem Befehlszeilentool bearbeitet werden kann, um die auf dem Gerät zulässigen Arten von symbolischen Verknüpfungen zu steuern. Geben Sie **fsutil behavior set symlinkevalution /?** ein, um weitere Informationen zu erhalten. an der Eingabeaufforderung ein, um weitere Informationen zu erhalten.

Unless there is anything else to be addressed here, closing this ticket should be in order.

**Comment by mypil** [comment]
@schnadoslin - Vielen Dank für die Einreichung von Feedback.

Nach unserem Verständnis ist das Problem gelöst, so dass wir dieses Problem schließen werden. 

Vielen Dank für Ihren Beitrag, um die Dokumente besser zu machen! Sehr geschätzt!

[Thank you for submitting feedback. From our understanding, the issue has been resolved so we will close this issue.  Thank you for your contribution to make the docs better! Much appreciated!]
