### ISSUE TITLE
MacOs and Linux are supported

### ISSUE THREAD

**Issue by josephka3** [MicrosoftDocs/windows-itpro-docs#6198]
Mac and Linux are supported, it still shows planning in this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 034ffda3-6ef7-13f4-6341-82ac3c11f455
* Version Independent ID: 5527ef3f-6361-b037-d9c3-3d520cf2ef2c
* Content: [Threat & Vulnerability Management supported operating systems - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/tvm-supported-os)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/tvm-supported-os.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/tvm-supported-os.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by mypil** [comment]
@josephka3 - Thank you for submitting feedback.

Here's the response from one of the authors based on this https://github.com/MicrosoftDocs/windows-itpro-docs/pull/6200#issuecomment-598334278 - 
"Unfortunately, the TVM support for MacOS and Linux are not available at this point. For MacOS and Linux, we have Microsoft Defender ATP (which is the next gen protection, antivirus, and other capabilities). But at this point in time, Threat and Vulnerability Management for these platforms is not yet available."

Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience,  you could add your feedback via the **[Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by josephka3** [comment]
@mypil Noted. Thanks!
