### ISSUE TITLE
Unique ID

### ISSUE THREAD

**Issue by toanyonebutyou** [MicrosoftDocs/windows-itpro-docs#620]
What exactly is required in the [Unique ID] field?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba73a4d0-cfe2-e988-58ba-ead197ea2e30
* Version Independent ID: 3070acc3-ea72-f425-3179-b4d26baf7027
* Content: [ClientCertificateInstall CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/clientcertificateinstall-csp)
* Content Source: [windows/client-management/mdm/clientcertificateinstall-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/clientcertificateinstall-csp.md)
* Service: **unspecified**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by shortpatti** [comment]
@MariciaAlforque -- Can you take a look at this issue?

**Comment by trfleming3745** [comment]
@mariciaalforque @shortpatti I am also interested in what the [Unique ID] field is suppose to be.

**Comment by shortpatti** [comment]
A certificate has a unique ID, which is the *\[UniqueID\]* for this configuration, and each client certificate must have different UniqueIDs for the SCEP enrollment request.
