### ISSUE TITLE
Windows Activation URL

### ISSUE THREAD

**Issue by AndrewStalkerAU** [MicrosoftDocs/windows-itpro-docs#6202]
I have seen on multiple pages that the requirements for Windows activation always link to a support article on support.microsoft.com how to resolve an issue with activation. Whilst this information is correct, it should have its own page listing the URLs and port numbers on docs.microsoft.com so customers can refer to articles of the same 'type'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aafc065-6ee6-e3cf-31ba-ab3dd277fb23
* Version Independent ID: 35d3102e-4ff7-9408-8dbd-513b7dfff5c0
* Content: [Windows Autopilot requirements - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-requirements#feedback)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/windows-autopilot-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by AndrewStalkerAU** [comment]
Similar to the link for the O365 URLs and IP addresses

**Comment by e0i** [comment]
Hello, @AndrewStalkerAU 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by joinimran** [comment]
@AndrewStalkerAU  - thank you for engaging with the community here for the docs. 

I know the product teams are always looking for user feedback and how to make support documents better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://sharepoint.uservoice.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

If there is any other improvements required in this specific document, please let me know.

Thank you for your contribution to make the docs better! Much appreciated!

Imran.
