### ISSUE TITLE
Missing details about the process exclusion

### ISSUE THREAD

**Issue by tbolon** [MicrosoftDocs/windows-itpro-docs#6205]
The Windows 10 dialog prompt with "Enter process name" when adding exclusion. The ["Learn More" link](https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-security) does not give details about what should be set as a value :

- Only the process name ("sqlservr")
- Executable name ("sqlservr.exe")
- Full executable path ("C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\Binn\sqlservr.exe")

The only place where I could find a hint is in this page, in the section "Exclusion lists" where the last row seems to suggest that the full path should be set.

My suggestion should be to clarify what is expected to be set in this prompt.

1. at least in this doc page
2. or better, in the support page
3. or even better, in the windows defender dialog itself

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c0eddd-98ca-1e7a-bddb-36c7037850fe
* Version Independent ID: 6afa98e8-a402-4ef9-2189-8ecc111c3dba
* Content: [Configure and validate exclusions based on extension, name, or location - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-extension-file-exclusions-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-extension-file-exclusions-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/configure-extension-file-exclusions-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@tbolon , to exclude a particular file, we need to use  -ExclusionPath
in powershell we need to use  below command 
**Add-MpPreference -ExclusionPath "C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\Binn\sqlservr.exe"**

**Comment by tbolon** [comment]
@RAJU2529 So you are saying that in the UI we should also set the full path ?

![image](https://user-images.githubusercontent.com/127185/76541828-6fa89000-6484-11ea-927e-469b11131dcb.png)

**Comment by RAJU2529** [comment]
No . i  given for  exclusionpath ., not for process 
and the excluded lists can be seen in registry  if  configured by group policy.

normally the process  excutable files   will be settled in   system32 folder. if process .exe files are in above folder , then entering name is  correct . But some times , process are  not system32 folder , so i have doubt

**Comment by denisebmsft** [comment]
Thank you @tbolon for posting this issue, and @RAJU2529 for your help. We are looking into this, and as soon as I have an update, I'll share it here.

**Comment by denisebmsft** [comment]
Hello again! To exclude a process, you use either its executable name or its full path. Please see [Configure exclusions for files opened by processes](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-antivirus/configure-process-opened-file-exclusions-windows-defender-antivirus). In addition, several updates were made to this article. Changes should be live either later today or tomorrow. Thank you again for the feedback/help, and I wish you a great rest of the week!

**Comment by RAJU2529** [comment]
@tbolon .  Author @denisebmsft  given the solution  to exclude the process .exe files using group policy Editor. So  try the solution.
