### ISSUE TITLE
Certificate configuration cause certificate warnings, potentially errors

### ISSUE THREAD

**Issue by homoSapiensSapiens** [MicrosoftDocs/windows-itpro-docs#6206]
Hi, I was following that guide tightly, and when configuring the ADFS role I was getting the following warnings:

The SSL certificate subject alternative names do not support host name 'certauth.fs.domain.com'. Configuring certificate authentication binding on port '49443' and hostname 'fs.domain.com'.
The SSL certificate does not contain all UPN suffix values that exist in the enterprise.  Users with UPN suffix values not represented in the certificate will not be able to Workplace-Join their devices.  For more information, see http://go.microsoft.com/fwlink/?LinkId=311954.

After that, devices could not join the ADFS, but I can't tell if that is related.
Anyway, I would suggest maybe to include the "coreauth" alternative name in the instructions, to avoid misconfiguration of the certificate, and how to make sure we include all UPN suffixes? could be very helpful.
Thank you all for that helpfull documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b3d124f-6dc2-03bd-0b30-06a9c4306940
* Version Independent ID: bfd8c4ff-4b61-5cd4-858d-6b35255343d0
* Content: [Prepare & Deploy Windows Active Directory Federation Services with key trust (Windows Hello for Business) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-key-trust-adfs#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-key-trust-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-key-trust-adfs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
Hello, @homoSapiensSapiens thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
