### ISSUE TITLE
TPM 1.2 vs 2.0

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/windows-itpro-docs#6208]
This page has missing detail around TPM versions. Autopilot requires TPM 2.0 and UEFI firmware for white glove and self-deploying scenarios. TPM 2.0 is also needed to automatically encrypt the local drive when joining a device to Azure Active Directory. If those aren't required then TPM 1.2 can be used (which is the only option on a lot of existing hardware still under support).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aafc065-6ee6-e3cf-31ba-ab3dd277fb23
* Version Independent ID: 35d3102e-4ff7-9408-8dbd-513b7dfff5c0
* Content: [Windows Autopilot requirements - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-requirements)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/windows-autopilot-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
Hello, @thommck 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
The missing link has been included via the attached PR. Thank you for reaching out for feedback.
