### ISSUE TITLE
KB4550735

### ISSUE THREAD

**Issue by iDolmatov** [MicrosoftDocs/windows-itpro-docs#6209]
> You can find a list of servicing stack updates at Latest servicing stack updates.

Don't find 2020-03 (March 2020) KB4550735
In list February 2020 KB 4537829

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b706f0af-d504-a8ca-7c38-b8bb9283bfad
* Version Independent ID: 14f31acf-9f47-59a6-269f-62ab249fe560
* Content: [Servicing stack updates (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates?source=docs#feedback)
* Content Source: [windows/deployment/update/servicing-stack-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/servicing-stack-updates.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
The problem isn't with this topic, but with the one we're linking to. I'll get hold of the people who own that and get them to investigate. Thanks!

**Comment by iDolmatov** [comment]
Agree with You. 
Don't find report link about another page.
Need close or after fix?

**Comment by jaimeo** [comment]
Nah let's leave this open so we'll have a record of working on it and when it's fixed. I've pinged someone who has helped with this before. Thanks very much for letting us known.

**Comment by RAJU2529** [comment]
@iDolmatov , ssu  KB4550735 for windows 7 os . link for kb4550735 is
**http://www.catalog.update.microsoft.com/search.aspx?q=kb4550735**

link for kb4537829 is
**http://www.catalog.update.microsoft.com/Search.aspx?q=kb4537829**

**Comment by iDolmatov** [comment]
> @iDolmatov , ssu KB4550735 for windows 7 os . link for kb4550735 is
> **http://www.catalog.update.microsoft.com/search.aspx?q=kb4550735**
> 
> link for kb4537829 is
> **http://www.catalog.update.microsoft.com/Search.aspx?q=kb4537829**

I know. 
Note report about **Latest servicing stack updates**, but ADV990001 have old information for Win7/2008. As variant, need string in table for Windows 7 ESU.

**Comment by iDolmatov** [comment]
![image](https://user-images.githubusercontent.com/19782385/76543090-cf646280-64a7-11ea-931d-367d7919c568.png)

**Comment by iDolmatov** [comment]
Thanks. Fixed.
![image](https://user-images.githubusercontent.com/19782385/76629039-866fe500-655f-11ea-907f-3a9933028a44.png)
