### ISSUE TITLE
Surface Pro X + Microsoft Surface Dock Firmware Update

### ISSUE THREAD

**Issue by Seb0380** [MicrosoftDocs/windows-itpro-docs#6213]
Hello,

Again the same issue, Surface Prox X can't run this program.
Microsoft product incompatible with microsoft product???
Why Microsoft is killing the surface pro X?

Kind regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7b356e-3dbd-7f59-845e-a92e05865a52
* Version Independent ID: 711c5497-373f-662c-7fae-ba60f046e50c
* Content: [Microsoft Surface Dock Firmware Update - Surface](https://docs.microsoft.com/en-us/surface/surface-dock-firmware-update#feedback)
* Content Source: [devices/surface/surface-dock-firmware-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-dock-firmware-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@Seb0380 

The issues section of this repository is intended for product documentation issues.

Please consider opening a product support ticket by the following link below for your problem,

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
