### ISSUE TITLE
TPM

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/windows-itpro-docs#6214]
The link "TPM requirements in Windows 10" goes to a 404 page not found.
Also, it's not clear from the documentation if you are saying TPM 2.0 is required or if it is just prefered. The TPM docs (https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/tpm-recommendations) say that 1.2 is supported, which will enable older hardware to use Hello)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a63c1d-79e8-8e28-88b8-38b9984cdeda
* Version Independent ID: b88c3dc4-c4aa-4b98-e4b9-ab182975b4c0
* Content: [How Windows Hello for Business works - Technology and Terms - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-technology)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-how-it-works-technology.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-how-it-works-technology.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@thommck it seems that the broken link has been updated by a community contributor.

 Another contributor will follow-up regarding your second concern about TPM requirements.

Thank you for the feedback.

**Comment by joinimran** [comment]
@thommck - Thank you for your query. TPM 2.0 is preferred but minimum TMP 1.2 is required which is also mentioned in the document https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/tpm-recommendations#tpm-and-windows-features

For more details see minimum hardware requirements at https://docs.microsoft.com/en-us/windows-hardware/design/minimum/minimum-hardware-requirements-overview

Thanks.

@e0i FYI Please.
