### ISSUE TITLE
TelClientSynthetic.HeartBeat_5 - clarification about data analysts and trusted meaning

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/windows-itpro-docs#6216]
Hello,

I refer to this paragraph:

```
TelClientSynthetic.HeartBeat_5

This event sends data about the health and quality of the diagnostic data from the given device, to help keep Windows up to date. It also enables data analysts to determine how 'trusted' the data is from a given device.
```

I would like to have clarification about:

1. To which data analysts does this refer? Data analysts of Microsoft?
2. What does 'trusted' mean in this context? Did you mean 'reliable'? If not, please explain how the trustworthiness is determined and what it is used for.

Thank you!

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43f50265-384b-fe61-c722-8c736878fc02
* Version Independent ID: e715c498-6512-7823-32ce-483130a68af1
* Content: [Windows 10, version 1903 and Windows 10, version 1909 basic diagnostic events and fields (Windows 10) - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/basic-level-windows-diagnostic-events-and-fields-1903#feedback)
* Content Source: [windows/privacy/basic-level-windows-diagnostic-events-and-fields-1903.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/basic-level-windows-diagnostic-events-and-fields-1903.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
@GiantCrocodile

Thank you for pointing out this ambiguity.

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

**Comment by joinimran** [comment]
Hello @GiantCrocodile - Thank you for your query. 

1. To which data analysts does this refer? Data analysts of Microsoft?
This refers to the Microsoft Data Analyst. This is also mentioned in the 2nd paragraph that these data sets are using by Microsoft to fix the operating system or app problems.

"The Basic level helps to identify problems that can occur on a particular device hardware or software configuration. For example, it can help determine if crashes are more frequent on devices with a specific amount of memory or that are running a particular driver version. This helps Microsoft fix operating system or app problems."

2. What does 'trusted' mean in this context? Did you mean 'reliable'? If not, please explain how the trustworthiness is determined and what it is used for.

This trusted term in this context refer to reliability to the data. This is ensured by the different fields mentioned in the event.

Thanks.

**Comment by GiantCrocodile** [comment]
Hello @joinimran! Thank you for answering my questions.

Question 1 is clearly answered now.

Regarding question 2: Am I right in my understanding that the data of this `TelClientSynthetic.HeartBeat_5` event is used to validate/ensure the reliability/trustworthiness of the data collected by the other events of the Basic Level?

Best Regards,

**Comment by brianlic-msft** [comment]
@GiantCrocodile this event is used as a heartbeat to assess the health of the Connected User Experience and Telemetry component and the data collection pipeline.

**Comment by GiantCrocodile** [comment]
That makes sense @brianlic-msft, although it sounds misplaced to talk about keeping `Windows up to date` by this if it's relatex to the Connected User Experience, Telemetry component and data collection pipeline.

Can I read more about the data collection pipeline somewhere? A quick research returned no useful results about that term in context of Office 365.

**Comment by GiantCrocodile** [comment]
Hi @e0i! Why did you close this? There's still two questions left as per my comment https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6216#issuecomment-603352168

**Comment by illfated** [comment]
@GiantCrocodile : Maybe @brianlic-msft would be able to answer that as a closing comment.

**Comment by brianlic-msft** [comment]
@GiantCrocodile this event is used to monitor the health of the Connected User Experience and Telemetry component. It sends back data to ensure the service is still running. Windows diagnostic data is used to keep Windows up to date. Hope this helps.

**Comment by GiantCrocodile** [comment]
Thank you for your help @illfated and @brianlic-msft! Your explanation makes sense and is understandable.

Sorry for keeping you busy @brianlic-msft: Can you tell me if and where I can find more details about the previously mentioned collection pipeline? I tried to find documentation with this term to get an overview of all of this but I wasn't able to find helpful documents.

I really appreciate your help, very good support!

**Comment by brianlic-msft** [comment]
@GiantCrocodile we don't have any specific documentation around the data collection pipeline. We talk about it here though [https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization#how-microsoft-handles-diagnostic-data](https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization#how-microsoft-handles-diagnostic-data)
