### ISSUE TITLE
Hyper-V Component

### ISSUE THREAD

**Issue by merwindz** [MicrosoftDocs/windows-itpro-docs#6217]
could you please confirm if we need to install the Hyper-V components in Windows 10 (1909) to enable to application and credential guard?

Thanks

**Comment by e0i** [comment]
@merwindz 

Please ask [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) for clarification as the issues section of this repository is intended for product documentation issues.

If there is something needs to be updated or clarified within the documentation, please follow-up with a link to the article URL for further investigation.

Thank you for providing feedback.
