### ISSUE TITLE
Why volume E?

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/windows-itpro-docs#6218]
"If a drive is pre-provisioned with BitLocker, a status of "Waiting for Activation" displays with a yellow exclamation icon on volume E."

I don't understand why this line specifies "E". I think that would be uncommon for most people, and therefore a mistake.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f6b62a2-d4bf-f680-3cb8-f67769ab27c4
* Version Independent ID: 17c6e5c3-36cf-4bc8-5ff2-5a9527471012
* Content: [BitLocker basic deployment (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-basic-deployment)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-basic-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-basic-deployment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@BR77BE Would it be because of the example above that mentions `E:` drive letter?

https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-basic-deployment#data-volume-2

**Comment by BR77BE** [comment]
> @BR77BE Would it be because of the example above that mentions `E:` drive letter?
> 
> https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-basic-deployment#data-volume-2

It should not be related to that example of encrypting a **Data volume**, because **Checking BitLocker status** also applies to an **Operating system volume**.

**Comment by illfated** [comment]
This issue appears to be resolved.
