### ISSUE TITLE
NMI for Azure

### ISSUE THREAD

**Issue by v-chkinn** [MicrosoftDocs/windows-itpro-docs#6223]
You may want to include  NMI instructions for Azure using the SAC (Serial Console)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae826aa0-3286-7044-27aa-501e6c265b53
* Version Independent ID: 5109af1f-465a-8f0b-cfe0-82e8de22fd70
* Content: [Generate a kernel or complete crash dump - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/generate-kernel-or-complete-crash-dump#feedback)
* Content Source: [windows/client-management/generate-kernel-or-complete-crash-dump.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/generate-kernel-or-complete-crash-dump.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by e0i** [comment]
@v-chkinn 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.
