### ISSUE TITLE
Clarification on data type

### ISSUE THREAD

**Issue by Cloudsystemsit** [MicrosoftDocs/windows-itpro-docs#6224]
When using Intune or another mdm, what is the data type used for Reboot CSP, both Schedule/Single, or Schedule/DailyRecurrent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a473300-e8f4-8c49-5ac7-d81956f55adf
* Version Independent ID: 7db8e493-d48b-bee9-61af-de601cfc8216
* Content: [Reboot CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/reboot-csp#feedback)
* Content Source: [windows/client-management/mdm/reboot-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/reboot-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@Cloudsystemsit 

The document is about to be updated with a clarification on data types. Thank you for the feedback.

Thank you.

**Comment by e0i** [comment]
Closing via #6137

**Comment by illfated** [comment]
(Ref. #6317 & https://github.com/MicrosoftDocs/windows-itpro-docs/commit/8106a2afee1d9950197a38c463491a16f5215c97 )
