### ISSUE TITLE
Typo: centratlized

### ISSUE THREAD

**Issue by bruun365** [MicrosoftDocs/windows-itpro-docs#6227]
Typo: centratlized configuration and administration, APIs (top page)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbabaf85-a345-a91e-f4e2-09c2b7871375
* Version Independent ID: bab57f2f-249a-0fe9-4f4a-93d62ce71670
* Content: [Threat Protection (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/#apis)
* Content Source: [windows/security/threat-protection/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/index.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Thanks. This typo will be resolved when my PR #6228 gets merged into the [`MicrosoftDocs:public`](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/public) branch
