### ISSUE TITLE
Bug in this documentation?

### ISSUE THREAD

**Issue by untilted-document** [MicrosoftDocs/windows-itpro-docs#623]
"Possible values" section says: "If th Account lockout duration is set to 0, the account will remain locked until an administrator unlocks it manually.
It is advisable to set Account lockout duration to approximately 30 minutes. To specify that the account will never be locked out, set the value to 0"

So which is it? Setting 0 means it's locked forever, or never locked? These are very different things..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 403fdccd-6988-3a5d-d175-c8f30ffddf31
* Version Independent ID: 5fd127aa-d224-559a-c7ad-00a1257397b7
* Content: [Account lockout duration (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/account-lockout-duration)
* Content Source: [windows/security/threat-protection/security-policy-settings/account-lockout-duration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/account-lockout-duration.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by shortpatti** [comment]
@Justinha -- Can you take a look at this issue?

**Comment by Justinha** [comment]
@untilted-document thanks for opening this. That should say set Account Lockout Threshold to 0 if you don't want any account to get locked out. Also, our security baselines recommend 15 mins for the duration. I submitted both corrections. They should appear on 04/02/18.

**Comment by Justinha** [comment]
This is fixed
