### ISSUE TITLE
Intune Deployment using line-of-business app instead windows app (Win32)

### ISSUE THREAD

**Issue by ekalweit** [MicrosoftDocs/windows-itpro-docs#6231]
Why is it necessary to convert the MSI file to the .intunewin format for rollout? Intune can also install the MSI using line-of-business app.
What are the differences in using those procedures?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7b356e-3dbd-7f59-845e-a92e05865a52
* Version Independent ID: 711c5497-373f-662c-7fae-ba60f046e50c
* Content: [Microsoft Surface Dock Firmware Update - Surface](https://docs.microsoft.com/en-gb/surface/surface-dock-firmware-update#feedback)
* Content Source: [devices/surface/surface-dock-firmware-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-dock-firmware-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by VLG17** [comment]
@ekalweit converting the MSI to .intunewin format gives you the ability (which many have been asking for) to package the application (or more than one) together with command line installation and uninstall commands, but also dependencies.

"App dependencies are applications that must be installed before your Win32 app can be installed. You can require that other apps are installed as dependencies. Specifically, the device must install the dependent app(s) before it installs the Win32 app."

If we are talking about just one MSI, sure you can go the LOB app road, but in that case you need to take care of the whole management lifecycle.

**Comment by mypil** [comment]
@ekalweit - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17 so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
