### ISSUE TITLE
Curly quotes in PowerShell script prevent it from working

### ISSUE THREAD

**Issue by hsehestedt** [MicrosoftDocs/windows-itpro-docs#6241]
The PowerShell script as posted here will note work. Somewhere along the way some of the double quote marks became "curly quotes". To correct this, all open and closing curly quotes (these are two different items) need to be changed to straight quotes. After making that change the script will function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7734ca5-0770-5bbd-7da5-dda4c1cf5ae0
* Version Independent ID: cb98ef23-d0c6-e62e-b72b-9b5f5d724e8e
* Content: [Update Windows 10 media with Dynamic Update - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/media-dynamic-update#feedback)
* Content Source: [windows/deployment/update/media-dynamic-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/media-dynamic-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @SteveDiAcetis
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
Thanks for pointing out this hidden issue. I will start a Pull Request to have that corrected.

**Comment by e0i** [comment]
@hsehestedt The Pull Requests #6264 has been rejected by document author via the following feedback,

> @illfated I'm going to go with #6275 b/c that PR is from the SME for the topic--he specifically did not want the PowerShell identifier for the code block b/c it was rendering strangely (we should probably file a bug on that). That's why we went with the plain generic rendering.

Thank you.
