### ISSUE TITLE
hololens insiders windows&github mij

### ISSUE THREAD

**Issue by infinitoparra** [MicrosoftDocs/windows-itpro-docs#6242]
[フィードバックをこちらに入力してください]

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7e67982e-6e73-e5cd-04eb-3c80568a99be
* Version Independent ID: 75498529-c75a-cdb8-43aa-7a87aa523aa3
* Content: [フィードバックをお寄せください](https://docs.microsoft.com/ja-jp/hololens/hololens-feedback#feedback)
* Content Source: [devices/hololens/hololens-feedback.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/hololens/hololens-feedback.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by e0i** [comment]
Closing as the issue seems to be submitted by mistake (via literal translation: _"Enter feedback here."_).
