### ISSUE TITLE
Incorrect Directions when configuring ADFS Certificate

### ISSUE THREAD

**Issue by D4-AzIdentity** [MicrosoftDocs/windows-itpro-docs#6252]
Per our documentation above:
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs#enroll-for-a-tls-server-authentication-certificate
The server authentication certificate should have the following names included in the certificate if you are requesting an individual certificate for each node in the federation farm:

Subject Name: The internal FQDN of the federation server (the name of the computer running AD FS)
Subject Alternate Name: Your federation service name, such as fs.corp.contoso.com (or an appropriate wildcard entry such as *.corp.contoso.com)
Subject Alternate Name: Your device registration service name, such as enterpriseregistration.contoso.com

However, when requesting a certificate from the internal web server. It was never specified to add the enterpriseregistration SAN to the request.

https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs#internal-web-server-authentication-certificate-enrollment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b063e00b-84e5-9da7-2229-e0e24da3b877
* Version Independent ID: da9f4867-2aa3-aefa-1603-ddb2ab1ed624
* Content: [Prepare & Deploy Windows AD FS certificate trust (Windows Hello for Business) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs#deploy-the-active-directory-federation-service-role)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@D4-AzIdentity 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.

**Comment by MaratMussabekov** [comment]
Hello @D4-AzIdentity ,
yes, device registration service name is required as a subject alternative name, I created a PR to add it.
Thank you

**Comment by nam31** [comment]
Closing via #6310
