### ISSUE TITLE
Ошибки машинного перевода. 

### ISSUE THREAD

**Issue by gr1mm3r** [MicrosoftDocs/windows-itpro-docs#6253]
Оставьте на английском или переведите в теги кода пожалуйста следующие пункты:
Переименуйте следующие папки в *. BAK
%системрут%\софтваредистрибутион\датасторе
%systemroot%\SoftwareDistribution\Download
%systemroot%\system32\catroot2
Для этого введите в командной строке указанные ниже команды. После ввода каждой команды нажимайте клавишу ВВОД.
Ren%Системрут%\софтваредистрибутион\датасторе *. bak
Ren%Системрут%\софтваредистрибутион\довнлоад *. bak
Ren%systemroot%\system32\catroot2 *. bak
Сброс службы BITS и службы центра обновления Windows в дескриптор безопасности по умолчанию. Для этого введите в командной строке указанные ниже команды. После ввода каждой команды нажимайте клавишу ВВОД.
SC. exe сдсет биты D: (A;; ККЛКСВРПВПДТЛОКРРК;;; SY) (A;; ККДКЛКСВРПВПДТЛОКРСДРКВДВО;;; БА) (A;; ККЛКСВЛОКРРК;;; AU) (A;; ККЛКСВРПВПДТЛОКРРК;;; ОБЩЕДОСТУПНОЕ обновление за
SC. exe сдсет вуаусерв D: (A;; ККЛКСВРПВПДТЛОКРРК;;; SY) (A;; ККДКЛКСВРПВПДТЛОКРСДРКВДВО;;; БА) (A;; ККЛКСВЛОКРРК;;; AU) (A;; ККЛКСВРПВПДТЛОКРРК;;; ОБЩЕДОСТУПНОЕ обновление за
В командной строке введите следующую команду и нажмите клавишу ВВОД.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update — дополнительные ресурсы - Windows Deployment](https://docs.microsoft.com/ru-ru/windows/deployment/update/windows-update-resources#feedback)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by jaimeo** [comment]
Sorry--I ran this through a translator, but I'm still having trouble understanding what issue are reporting or change you are suggesting. Can you clarify?

**Comment by jaimeo** [comment]
@TinaMcN it seems like this is pointing out a bad translation. Can you investigate?

**Comment by TinaMcN** [comment]
@gr1mm3r Благодарим Вас за сообщение об этой проблеме.
@OfficeGlobal please human translate this article.

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@gr1mm3r , @TinaMcN the article was HumanTranslated and published live

**Comment by e0i** [comment]
Noted for closure upon verification of live content.

**Comment by gr1mm3r** [comment]
> Sorry--I ran this through a translator, but I'm still having trouble understanding what issue are reporting or change you are suggesting. Can you clarify?

it look like that:
_____
Переименуйте следующие папки в *. BAK
```
%systemroot%\SoftwareDistribution\DataStore
%systemroot%\SoftwareDistribution\Download
%systemroot%\system32\catroot2
```
Для этого введите в командной строке указанные ниже команды. После ввода каждой команды нажимайте клавишу ВВОД.
```
Ren%systemroot%\SoftwareDistribution\DataStore *. bak
Ren%systemroot%\SoftwareDistribution\Download *. bak
Ren%systemroot%\system32\catroot2 *. bak
```
Сброс службы BITS и службы центра обновления Windows в дескриптор безопасности по умолчанию. Для этого введите в командной строке указанные ниже команды. После ввода каждой команды нажимайте клавишу ВВОД.
_____

And this part of text nobody can understand:
```
SC. exe сдсет биты D: (A;; ККЛКСВРПВПДТЛОКРРК;;; SY) (A;; ККДКЛКСВРПВПДТЛОКРСДРКВДВО;;; БА) (A;; ККЛКСВЛОКРРК;;; AU) (A;; ККЛКСВРПВПДТЛОКРРК;;; ОБЩЕДОСТУПНОЕ обновление за
SC. exe сдсет вуаусерв D: (A;; ККЛКСВРПВПДТЛОКРРК;;; SY) (A;; ККДКЛКСВРПВПДТЛОКРСДРКВДВО;;; БА) (A;; ККЛКСВЛОКРРК;;; AU) (A;; ККЛКСВРПВПДТЛОКРРК ОБЩЕДОСТУПНОЕ обновление за;;; 
```

**Comment by illfated** [comment]
@gr1mm3r : 
Для меня, это выглядит как страница была обновлена и нежелательный перевод удалены. Пожалуйста, проверьте еще раз.
Мне кажется, что страница была обновлена, а нежелательный перевод удален. Пожалуйста, проверьте еще раз.
(To me, it looks like the page has been updated and the unwanted translation removed. Please verify again.)

**Comment by e0i** [comment]
Closing as confirmed. Thank you.
