### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by kerimhanif** [MicrosoftDocs/windows-itpro-docs#6255]
There is a typo ("Centratlized" configuration and administration, APIs) right below on the link below the Microsoft Defender ATP graph 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bdb99e4-289a-c09a-c35c-2774fc52a402
* Version Independent ID: 4d325389-c9b8-2601-0ff4-c7b6bf5a6c28
* Content: [Microsoft Defender Advanced Threat Protection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by denisebmsft** [comment]
Hello @kerimhanif and thank you for catching this! It is now fixed, although it might take a few hours for the changes to render on the live site. Thank you for helping us improve our content!!
