### ISSUE TITLE
Mention that AppLocker is not a security boundary and reference WDAC

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/windows-itpro-docs#6258]
[Servicing Criteria](https://www.microsoft.com/en-us/msrc/windows-security-servicing-criteria)

[Choose when to use WDAC or AppLocker](
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control#choose-when-to-use-wdac-or-applocker).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b86092-6dfd-e280-8cb3-fb1b2f0f5f10
* Version Independent ID: 517c2146-bdf4-ecf3-b629-f88f29cac5e2
* Content: [AppLocker (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/applocker-overview)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/applocker/applocker-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/applocker/applocker-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@fowl2     According to you whats your opinion about applocker. I already tried it.

**Comment by VLG17** [comment]
@fowl2 Thank you for providing this feedback, i will add a note on that.

**Comment by RAJU2529** [comment]
@VLG17 . Merged content is not available

**Comment by illfated** [comment]
@RAJU2529 : May I ask where you are looking for the merged content to be available (where it "is not available"), or in other words, where did you expect to find it?

If you are talking about the docs.microsoft.com page (just before the last paragraph in the section https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/applocker-overview#when-to-use-applocker), please remember that it may take anything between 1-2 days and a week before the migration process has been completed and the merged content in the public branch here on GitHub is available in the docs.microsoft.com page.

**Comment by RAJU2529** [comment]
@illfated , i saw his @VLG17  PR, I checked he has edited the article.

**Comment by mypil** [comment]
@fowl2 - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/dbe895c87720178e5687a8a1470f2cc81699d1e0. 


Thank you for your contribution to make the docs better! Much appreciated!
