### ISSUE TITLE
"Multi factor authentication" spelling correction

### ISSUE THREAD

**Issue by theBrendeny** [MicrosoftDocs/windows-itpro-docs#6259]
https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation#muti-factor-authentication

Currently seen as 'Muti-factor authentication', also included in URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation#muti-factor-authentication)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@theBrendeny - Thank you for pointing this out.


From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/105b77f5c938d2c7affc18c55da060645d0a59ed. 


Thank you for your contribution to make the docs better! Much appreciated!
