### ISSUE TITLE
Additional clarification on w32 apps - Technician flow

### ISSUE THREAD

**Issue by albozadz** [MicrosoftDocs/windows-itpro-docs#6260]
The phrase does no provide sufficient clarification on whether the apps need to be targeted to both device and user. 

"Additionally, any apps (Win32 or LOB) that are configured to install in the device context and targeted to the user that has been pre-assigned to the Autopilot device will also be installed."

As an additional note we can add the following:

"The white glove technician phase will install all device-targeted apps as well as any user-targeted, device-context apps that are targeted to the assigned user.  If there is no assigned user, then it will only install the device-targeted apps."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5b57d1-61b3-39d4-34ff-d6dcb858c250
* Version Independent ID: 42609104-815f-9e7a-39aa-38d92cc910c9
* Content: [Windows Autopilot for white glove deployment - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove#feedback)
* Content Source: [windows/deployment/windows-autopilot/white-glove.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/white-glove.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@albozadz 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by e0i** [comment]
@albozadz 

Upon your feedback, The content has been updated with relevant changes accordingly. Thanks.
