### ISSUE TITLE
configure-security-policy-settings french translation space after '.' in secpol.msc

### ISSUE THREAD

**Issue by christianruffenach** [MicrosoftDocs/windows-itpro-docs#6261]
Hi,

It is about the page :
https://docs.microsoft.com/fr-fr/windows/security/threat-protection/security-policy-settings/how-to-configure-security-policy-settings
In the french translation there is a space after the dot : "secpol. msc" 
it is just a little annoying.

French
Pour ouvrir la stratégie de sécurité locale, dans l’écran d' Accueil , tapez secpol. msc, puis appuyez sur entrée.
English
To open Local Security Policy, on the Start screen, type secpol.msc, and then press ENTER.

Best regards

**Comment by TinaMcN** [comment]
@christianruffenach thank you for reporting it.   It is caused by an issue with our machine translation tool which is under investigation.  @OfficGlobal please human translate this article and check that the issue is fixed.

**Comment by RAJU2529** [comment]
@TinaMcn . There is no edit option in french artice

**Comment by TinaMcN** [comment]
@RAJU2529 I am hoping to enable the edit option in French articles later this year.  It will require native speaker moderators and internal tools to manage the workflow which takes time to set up.  In the meantime you are welcome to leave feedback about the French articles via the English articles and I will pass on your feedback to the translators.

**Comment by RAJU2529** [comment]
@TinaMcN . Thanks for the reply. I will feedback.

**Comment by mypil** [comment]
@TinaMcN @officeglobal - Do you have any updates if this issue has been fixed?

Thank you.

**Comment by illfated** [comment]
From the French page (https://docs.microsoft.com/fr-fr/windows/security/threat-protection/security-policy-settings/how-to-configure-security-policy-settings) :

## Configurer un paramètre à l’aide de la console Stratégie de sécurité locale
1. Pour ouvrir la Stratégie de sécurité locale, dans l’écran de **Démarrage**, tapez **secpol.msc**, puis appuyez sur ENTRÉE.

***
This single character (space) issue has been resolved, therefore this ticket can be closed.

Thank you to @TinaMcN and @OfficeGlobal for the work done.
