### ISSUE TITLE
VDA rights Activation with CSP

### ISSUE THREAD

**Issue by montereyharris** [MicrosoftDocs/windows-itpro-docs#6263]
Windows 10 E3 with VDA rights is available in CSP. This article should address that scenario. What can or can't be done with that license and VDA activation is needed information. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c34b8c-44b9-b3d3-9894-5a7fd68e2309
* Version Independent ID: ea643c8f-e92d-b90e-4e90-f338cea39e79
* Content: [Configure VDA for Windows 10 Subscription Activation - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/vda-subscription-activation#feedback)
* Content Source: [windows/deployment/vda-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/vda-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
That scenario is here: https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-e3-overview
