### ISSUE TITLE
problems with the "Create a bootable USB stick" section

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/windows-itpro-docs#6265]
Splitting the wim file to E:\sources\install.swm doesn't really make sense.  You would put it under E:\Deploy\Operating Systems\W10EX64RTM\REFW10X64-001.swm, and then modify E:\Deploy\Control\OperatingSystems.xml to point to it.  

Also, I had to comment out the SLShare in customsettings.ini, since I'm offline.

Also, watch out for setting the osdcomputername in customsettings.ini with a userexit script.  If you're offline, the computername in unattend.xml will end up being blank, and windows setup will fail at the specialize section.

Also, windows doesn't normally let you format a usb drive larger than 32gb as fat32, except at the cmd prompt, but only long format, "format /fs:fat32 e:" (25 min).  I ended using Rufus to format it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt#create-a-bootable-usb-stick)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jszabo98** [comment]
Also if SkipWimSplit value set to False in D:\MDTProduction\Control\Settings.xml, MDT will automatically split the wim when making the media.  But there's a bug where the "name" of the Operating System in the MDT interface has to end in ".wim", not just the filename itself.

**Comment by greg-lindsay** [comment]
Thanks for all the hints, I will get these into the document. Sorry it has taken so long to get to this. I didn't see the issue and it wasn't assigned to me. I have assigned it now.

**Comment by greg-lindsay** [comment]
This content was rewritten in August of 2020 I forgot to close this bug. I am also adding a note about SLShare if you are using an offline setup.
