### ISSUE TITLE
Out-dated Images

### ISSUE THREAD

**Issue by bt-kamindit** [MicrosoftDocs/windows-itpro-docs#6266]
Images reference old UI for APP for Windows 10. Please update to use the new images for Intune and APP for Windows 10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78dc4a8b-91b6-20ef-ab43-8ddb0174a9a7
* Version Independent ID: 94478252-0b56-010b-d625-2e1ee479ad96
* Content: [Deploy your Windows Information Protection (WIP) policy using the Azure portal for Microsoft Intune (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/deploy-wip-policy-using-intune-azure?source=docs#feedback)
* Content Source: [windows/security/information-protection/windows-information-protection/deploy-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/deploy-wip-policy-using-intune-azure.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
@bt-kamindit Thank you for your feedback. Can you please share an update image here so that I can replace the content with the new GUI.

Thanks.

**Comment by b137** [comment]
Hello, I am the same individual (Different Account). Here is the Azure Portal side:
![image](https://user-images.githubusercontent.com/54907198/77361385-67661580-6d0c-11ea-811e-7d1e061b7776.png)

And here is the M365 Portal Side: 
![WIP_MEMPortal_Example](https://user-images.githubusercontent.com/54907198/77361654-ec512f00-6d0c-11ea-8379-2005a631d12f.png)

**Comment by joinimran** [comment]
I have created the PR to update the image. Thank you for your feedback. 

Thanks 
Imran.

**Comment by mypil** [comment]
@bt-kamindit - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/d73a5e78e0388c4c94fc772eabb9fdf69f63b2a8 but it may take a few days for the merged content to appear in the doc.  

Thank you for your contribution to make the docs better! Much appreciated!
