### ISSUE TITLE
Kontakt Feature im Datei-Explorer - nie gesehen - Nachfolger nicht vorhanden (Contact Feature in File Explorer - Never Seen - Successor Not Present)

### ISSUE THREAD

**Issue by ATR-Master** [MicrosoftDocs/windows-itpro-docs#6269]
https://docs.microsoft.com/de-de/windows/deployment/planning/windows-10-deprecated-features 
Die Information zum Punkt "Kontakt Feature im Datei-Explorer" scheint nicht korrekt zu sein:
+ in meinem Windows 10 v1909 Enterprise existiert die Kontakte App noch (Teil der Taskleiste)
+ gleiches gilt für v1909 Home und v1909 Pro
+ im Datei-Explorer existiert (noch existierte dort jemals) eine Kontakte App oder eine App Person
+ im Startmenü ist nirgends eine App Personen zu finden
+ In der Liste "Features hinzufügen" der Settings App existiert keine App "Personen"
+ inder Systemsteuerung unter "Programme und Features\Features aktivieren bzw. deaktivieren" ist ebenfalls keine App "Personen" zu finden
wo soll diese App also sein?
Wie soll / sollte sie auf die Windows-Installation gekommen sein? (händisch aus dem Microsoft Store laden, per Feature-Update, per Patch via Patchday, ....??
Solche Listen / Übersichten wie diese hier, sollten richtig und vollständig sein. Da ist eine solche Fehlinformation irgendwie deplaziert.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 89b6fda3-06b5-15be-9021-c8126f721c9b
* Version Independent ID: 5a8ff7c5-ed5f-6c18-211c-4af5397b1a17
* Content: [Windows 10-Features, die nicht mehr entwickelt werden - Windows Deployment](https://docs.microsoft.com/de-de/windows/deployment/planning/windows-10-deprecated-features#feedback)
* Content Source: [windows/deployment/planning/windows-10-deprecated-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-10-deprecated-features.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by denisebmsft** [comment]
Per Bing Translator:

https://docs.microsoft.com/de-de/windows/deployment/planning/windows-10-deprecated-features
The information about the "Contact Feature in File Explorer" point does not appear to be correct:

in my Windows 10 v1909 Enterprise the Contacts app still exists (part of the taskbar)
the same applies to v1909 Home and v1909 Pro
in File Explorer there exists (still existed there) a Contacts app or an app person
in the Start menu there is nowhere to find an app people
There is no people app in the "Add Features" list of the Settings app
in the Control Panel under "Enable or disable programs and features" there is also no "people" app
So where should this app be?
How should it have come to the Windows installation? (manually load from the Microsoft Store, via feature update, via patch day, ....??
Such lists/overviews like this one, should be correct and complete. Such misinformation is somehow misplaced.

**Comment by illfated** [comment]
To me, this looks like a misunderstanding. The referenced page (Windows 10-Features, die nicht mehr entwickelt werden) does not state that the feature has been removed, but simply states that it is no longer in development. From my point of view, where I only have access to Windows 10 Pro at work and Windows 10 Home where I live, the app "People" has been visible for at least 2 years now and it seems that this app may be part of the Windows 10 Operating System. Please note that you have to start the app at least once and go through some few preliminary / initial steps to see the app in the "Apps & features" list.

The "People" app does not have a Control Panel entry in the list `Control Panel\Programs\Programs and Features` (Uninstall or change a program), so I presume the same would be the case for the deprecated (seemingly not yet removed) Contacts app (when still present in the Windows 10 system files). Please note that the availability of the Contacts app may depend on the major version / build of Windows 10.

**Comment by e0i** [comment]
@ATR-Master 

Translation of comment via Bing:

> Für mich ist das ein Missverständnis. Die referenzierte Seite (Windows 10-Features, die nicht mehr entwickelt werden) gibt nicht an, dass das Feature entfernt wurde, sondern lediglich, dass es sich nicht mehr in der Entwicklung befindet. Aus meiner Sicht, wo ich nur Zugriff auf Windows 10 Pro bei der Arbeit und Windows 10 Home, wo ich lebe, ist die App "Menschen" seit mindestens 2 Jahren sichtbar und es scheint, dass diese App Teil des Windows 10 Betriebssystems sein kann. Bitte beachten Sie, dass Sie die App mindestens einmal starten müssen und einige erste Schritte durchlaufen müssen, um die App in der Liste "Apps & Features" zu sehen.

> Die App "Menschen" hat keinen Systemsteuerungseintrag in der Liste Systemsteuerung, Programme und Features (Ein Programm deinstallieren oder ändern), daher gehe ich davon aus, dass dies auch für die veraltete (scheinbar noch nicht entfernte) KoBitte teilen Sie uns mit, ob die Antwort des Community-Mitwirkenden Ihre Frage klärt. Danke.ntakte-App der Fall wäre (wenn sie noch in den Windows 10-Systemdateien vorhanden ist). Bitte beachten Sie, dass die Verfügbarkeit der Kontakte-App von der Hauptversion / dem Build von Windows 10 abhängen kann.


@ATR-Master,

Bitte teilen Sie uns mit, ob die Antwort des Community-Mitwirkenden Ihre Frage klärt. Danke. (Translation)

**Comment by ATR-Master** [comment]
Hallo e0i
Ja es handelt sich tatsächlich um ein Mißverständnis, aber ein anderes als das Beschriebene. Hätte ich eigentlich gleich drauf kommen sollen, erwähne es in meinen Schulungen immer wieder, aber manchmal sieht man einfach den Wald vor lauter Bäumen nicht.
Worin liegt das "Mißverständnis"?
+ Die automatisierte Übersetzung hatte fehlerhaft übersetzt: für den englisch-amerikanischen begriff "People" gibt es verschiedene Übersetzungen, u.a. Personen, menschen, Leute oder auch Kontakte
+ Hier wurde im Artikel "Pewople" mit "Personen" übersetzt und eine App gleichen namens in Windows 10 hineingedichtet. 
+ Die betreffende Windows 10 App heisst auf Deutsch "Kontakte" und nicht Personen!
+ der Name der App im System ist aber auf Englisch - wie alle Systemdateien, Systempfade und Apps mit ihren englischen Bezeichnungen im System geführt und vom System auch so aufgerufen werden.
+ Scriptaufrufe mit den deutschen Namen (oder äquivalent französischen, spanischen oder portugiesischen Namen) führt fast immer zu Fehlermeldungen a la "Befehl oder Dateiname nicht gefunden", weil Windows 10 nur englisch "spricht" und uns Dinge nur auf der Oberfläche in unserer Lokalisierungssprache (hier: Deutsch) anzeigt.
+ Die Kontakte-App wird im Windows 10 System also als "Microsoft.People.xxxxx" im betreffenden Ordner für die Apps geführt, auf der deutschen benutzeroberfläche aber als "Kontakte" bezeichnet.
+ Letztliche bleibt ein fehler auf der Webseite aber bestehen: Die App befindet sich nicht wie angegeben im Datei-Explorer, sondern ist als Icon in der Taskleiste eingeblenet gewesen (rechte Seite vor dem "Systray" = alte Bezeichnung). Mittlerweile wurde die App aber defaultmäßig ausgeblendet, weil viele Benutzer des Systems dachten, sie würden über diese App Kontakte in ihrem Outlook pflegen, was aber nicht so ist. Die App hat keine Verbindung zu den Outlook-"Kontakten".

Fazit: Mein schon gegebener Hinweis, automatisierte Übersetzungen, die sinnentstellende Aussagen treffen, nicht so auf der Webseite stehen zu lassen, kann ich nur nochmals wiederholen. So etwas verwirrt und sollte vermieden werden. Bei einem Konzern, der ca. 110 Mrd. $ Umsatz im Jahr macht, sollte man sich evtl. mal überlegen, ein paar Leute mit technischem Hintergrund zu beschäftigen, die solche automatisierten Übersetzungen Korrekturlesen und die Fehler beheben (zumindest die gröbsten). 
PS: Stehe für diese Tätigkeit zur Verfügung - entsprechendes Entgelt vorausgesetzt.
