### ISSUE TITLE
RDP блокирует доступ к Smart Card хоста (RDP blocks access to Smart Card host)

### ISSUE THREAD

**Issue by Igor-G-l** [MicrosoftDocs/windows-itpro-docs#6270]
Добрый день!
В свете борьбы с короновирусом, наша компания работает удаленно. Имеем сервер в датацентре с вставленными в него ключами клиент-банков (смарт-карты). Бухгалтера подключаются по РДП и не видят ключей. Хотя если подключиться локально (с консоли) или через VNC, например, то ключи видны!... Как можно решить эту проблему? Бухгалтеров несколько и они должны подменять одна другую. Но передавать ключи, как вы понимаете, не вариант. Буду рад всем предложениям. Спасибо.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 25bb5926-3fbc-a0bd-eccf-1aff82453d37
* Version Independent ID: 16fdeca3-b767-6a36-6aff-de851af5b468
* Content: [Службы смарт-карт и удаленных рабочих столов (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/ru-ru/windows/security/identity-protection/smart-cards/smart-card-and-remote-desktop-services#feedback)
* Content Source: [windows/security/identity-protection/smart-cards/smart-card-and-remote-desktop-services.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/smart-cards/smart-card-and-remote-desktop-services.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Per Bing Translator: Good afternoon!
In light of the fight against coronavirus, our company operates remotely. We have a server in the data center with the keys of the client-banks (smart cards) inserted into it. Accountants are connected by RDP and do not see the keys. Although if you connect locally (from the console) or via VNC, for example, the keys are visible!... How can this problem be solved? There are several accountants and they have to replace one another. But handing over the keys, as you know, is not an option. I'll be happy with all the offers. Thank you.

**Comment by e0i** [comment]
Hello, @Igor-G-l  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
