### ISSUE TITLE
The use of the transport key

### ISSUE THREAD

**Issue by lewiskflo** [MicrosoftDocs/windows-itpro-docs#6271]
I just want to ask when and how the transport key is being used. It is also missing the key exchange of the transport key and the device key. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96185909-5825-db9a-cc04-4045f6dc577e
* Version Independent ID: 9340a575-af61-9c73-7701-702fff99f524
* Content: [How Windows Hello for Business works - Device Registration - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-device-registration#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-how-it-works-device-registration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-how-it-works-device-registration.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mapalko** [comment]
Device Registration is a prerequisite for Windows Hello for Business, but it is a separate topic from WHFB itself. For more information on device registration you should refer to the device registration docs: https://docs.microsoft.com/en-us/azure/active-directory/devices/

**Comment by e0i** [comment]
Hello @lewiskflo 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
