### ISSUE TITLE
When trying to install on Ubuntu-18.04 get error

### ISSUE THREAD

**Issue by kenmartin-unix** [MicrosoftDocs/windows-itpro-docs#6273]
After doing apt-get update
sudo apt-get install mdatp
E: Unable to locate package mdatp
Any help? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2197cba-30ac-1749-e25a-6f39c9ee9d20
* Version Independent ID: bcd14f13-ab59-8e69-5c83-42fee6e51f87
* Content: [Deploy Microsoft Defender ATP for Linux manually - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@kenmartin-unix 

Have you ensured that you have installed the repository sources into apt package list before attempting the install? Please find below the section that explains that and let us know whether the article still needs revision.

https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually#ubuntu-and-debian-systems

Thank you.

**Comment by kenmartin-unix** [comment]
I am now running Debian 10 Buster under WSL.
Fresh start.

Everything is fine up to this point.

ken@LAPTOP-C194811:~$ sudo apt-get install mdatp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  uuid-runtime
The following NEW packages will be installed:
  mdatp uuid-runtime
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 12.7 MB of archives.
After this operation, 39.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://deb.debian.org/debian buster/main amd64 uuid-runtime amd64 2.33.1-0.1 [95.2 kB]
Get:2 https://packages.microsoft.com/debian/10/prod insiders-fast/main amd64 mdatp amd64 100.87.66-insiderfast [12.6 MB]
Fetched 12.7 MB in 8s (1,628 kB/s)                                             
Selecting previously unselected package uuid-runtime.
(Reading database ... 117674 files and directories currently installed.)
Preparing to unpack .../uuid-runtime_2.33.1-0.1_amd64.deb ...
Unpacking uuid-runtime (2.33.1-0.1) ...
Selecting previously unselected package mdatp.
Preparing to unpack .../mdatp_100.87.66-insiderfast_amd64.deb ...
dpkg: error processing archive /var/cache/apt/archives/mdatp_100.87.66-insiderfast_amd64.deb (--unpack):
 new mdatp package pre-installation script subprocess returned error exit status 1
dpkg: error while cleaning up:
 new mdatp package post-removal script subprocess returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/mdatp_100.87.66-insiderfast_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
ken@LAPTOP-C194811:~$ 

Please advise. Thanks.

**Comment by konstruktoid** [comment]
Hi @kenmartin-unix, are you able to dowload the file manually and install the `mdatp_100.87.66-insiderfast_amd64.deb`? If not, please include a debug log, `dpkg --debug=400 mdatp_100.87.66-insiderfast_amd64.deb`

ps. could you also reformat you issue text, using `code`? it's a bit hard to read. thanks.

**Comment by kenmartin-unix** [comment]
Thomas,

Thanks. I've decided to scrap the project for now.

Maybe I'll try again once it becomes more mature.

Too many steps.

**Comment by mikaaho** [comment]
Im experiencing the same error with Ubuntu 18.04 while provisioning Ubuntu inside Docker container. When trying to install manually: dpkg --debug=3773 -i mdatp_100.87.66-insiderfast.amd64.deb i get errors:

D000001: ensure_diversions: new, (re)loading
D000001: ensure_statoverrides: new, (re)loading
D000010: path_remove_tree '/var/lib/dpkg/tmp.ci'
Selecting previously unselected package mdatp.
(Reading database ... 15651 files and directories currently installed.)
Preparing to unpack mdatp_100.87.66-insiderfast.amd64.deb ...
D000001: process_archive oldversionstatus=not installed
D000002: fork/exec /var/lib/dpkg/tmp.ci/preinst ( install )
dpkg: error processing archive mdatp_100.87.66-insiderfast.amd64.deb (--install):
 new mdatp package pre-installation script subprocess returned error exit status 1
D000001: ensure_diversions: same, skipping
D000002: fork/exec /var/lib/dpkg/tmp.ci/postrm ( abort-install )
dpkg: error while cleaning up:
 new mdatp package post-removal script subprocess returned error exit status 1
D000001: ensure_diversions: same, skipping
D000010: path_remove_tree '/var/lib/dpkg/tmp.ci'
D000010: path_remove_tree running rm -rf '/var/lib/dpkg/tmp.ci'
D000010: path_remove_tree '/var/lib/dpkg/reassemble.deb'
Errors were encountered while processing:
 mdatp_100.87.66-insiderfast.amd64.deb

This only happens inside Docker container, i successfully installed via Ansible to one actual server. 
Im trying to test my ansible playbook with Ansible Molecule so this kinda prevents the local testing.

**Comment by konstruktoid** [comment]
@mikaaho, since docker is a special environment and the Ansible installation was successfully installed an actual server, have you tried testing using a Vagrant environment?

**Comment by mikaaho** [comment]
Yes, will try that option also. Thanks.
