### ISSUE TITLE
Wrong information in this article

### ISSUE THREAD

**Issue by snake1glide** [MicrosoftDocs/windows-itpro-docs#6276]
1. In first block file calls "copy_onboarding_pkg.yml", but when it comes to "Create the actual install/uninstall YAML files " it calls "download_copy_blob.yml";
2. It's better to use shell module instead of script module in "Create the onboarding file" section;
3. repo: deb [arch=arm64,armhf,amd64] https://packages.microsoft.com/[distro]/[version]/prod [channel] main
in channel section you should replace with ansible_distribution_release var, like xenial or bionic, not prod\insider-*
4. There is a missing  F letter in id:BC52 8686 B50D 79E3 39D3 721C EB3E 94AD BE12 29C

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 623e0469-826c-5cdf-6dc4-67c80e232d0f
* Version Independent ID: 0f6c33bc-711a-84d6-01bb-04d13f5a85a2
* Content: [Deploy Microsoft Defender ATP for Linux with Ansible - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Hello, @snake1glide 

The article is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by illfated** [comment]
@snake1glide : Thank you for the useful feedback. Pull Request #6332 has been created & merged to resolve the issues you reported. The details will be available in the public document within a few days.
