### ISSUE TITLE
registry not updating, not logs in event viewer

### ISSUE THREAD

**Issue by hodexter** [MicrosoftDocs/windows-itpro-docs#6277]
hi, have followed the instructions and still very lost. using a surface book 2, have updated drivers and firmware for the computer.

have also followed the instructions here to install the msi, however:
1) nothing in event viewer
2) dock still blinking when connected to surface and not charging. (dock has power - connected a phone to the usb port and it charges)
3) regedit reflects :
           Component10CurrentFwVersion: 491c270 (instead of 4ac3970)
           Component20CurrentFwVersion: 4915a70 (instead of 4a1d570)

full details:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\WUDF\Services\SurfaceDockFwUpdate\Parameters
    Component10FirmwareUpdateStatus    REG_DWORD    0x5
    Component10CurrentFwVersion    REG_DWORD    0x491c270
    Component20FirmwareUpdateStatus    REG_DWORD    0x5
    Component20CurrentFwVersion    REG_DWORD    0x4915a70
    Component10OfferFwVersion    REG_DWORD    0x48e2670
    Component20OfferFwVersion    REG_DWORD    0x48e2670
    Component10FirmwareUpdateStatusRejectReason    REG_DWORD    0x0
    Component20FirmwareUpdateStatusRejectReason    REG_DWORD    0x0

if anyone can help, would greatly appreciate. thanks all!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7b356e-3dbd-7f59-845e-a92e05865a52
* Version Independent ID: 711c5497-373f-662c-7fae-ba60f046e50c
* Content: [Microsoft Surface Dock Firmware Update - Surface](https://docs.microsoft.com/en-us/surface/surface-dock-firmware-update#feedback)
* Content Source: [devices/surface/surface-dock-firmware-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-dock-firmware-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@hodexter . Did you enabled windows event log services. Did you sure that log services enabled and running before firmware updated.

**Comment by myty** [comment]
I'm having similar issues trying to get it installed on a Surface Laptop (v1), but I'm not getting any updates to the registry.  This simply does not exist.  HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\WUDF\Services\SurfaceDockFwUpdate

I've uninstalled and resinstalled countless times, and still no luck.

**Comment by e0i** [comment]
Hello, @hodexter 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by joinimran** [comment]
I would suggest opening a support case with Microsoft, it looks like a bug. 

@e0i Can further help you how you can open a support case with Microsoft for the same.

Thanks

**Comment by e0i** [comment]
@hodexter 

In our investigation we have been able to reproduce the problematic behavior and the issue is being passed to the product team as a bug.

Thank you for taking the time to provide feedback. Much appreciated.

**Comment by myty** [comment]
@e0i Is there a page where we might be able to check the status of the bug fix?

**Comment by illfated** [comment]
Forgive me if it seems a little bit ignorant of me, as a non-Surface user, to suggest any kind of solution to your question.

Even so, I would think it is useful to keep watching for new Surface updates in the Microsoft Download pages.
