### ISSUE TITLE
Surface Hub not displaying meeting schedule on welcome screen from resource account

### ISSUE THREAD

**Issue by ronalton1023** [MicrosoftDocs/windows-itpro-docs#6278]
I created a resource account and performed the steps in the Surface Hub documentation and when I set the new hub up with this resource account, there is a huge delay from the time a meeting is schedule to the resource and the time it takes to show up on the Welcome screen. Is there a way to speed up the process?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f8f832f-7ea3-e861-70e8-c1d6bde7bc5c
* Version Independent ID: 0a22489c-b762-521d-7bcb-a33bcd74ada9
* Content: [Known issues and additional information about Microsoft Surface Hub - Surface Hub](https://docs.microsoft.com/en-us/surface-hub/known-issues-and-additional-info-about-surface-hub)
* Content Source: [devices/surface-hub/known-issues-and-additional-info-about-surface-hub.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/known-issues-and-additional-info-about-surface-hub.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @todmccoy
* Microsoft Alias: **v-todmc**

**Comment by e0i** [comment]
@ronalton1023 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
