### ISSUE TITLE
Missing 1st gen Surface Laptop

### ISSUE THREAD

**Issue by nixtar** [MicrosoftDocs/windows-itpro-docs#6279]
Picking apart the 1st gen Surface laptop driver MSI installer it is only checking for:
SystemSKUs=Surface_Laptop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84214a7c-c350-e7df-b096-8509be06d4fe
* Version Independent ID: a07d3fed-001f-4230-c5f7-c3a6caad3223
* Content: [System SKU reference (Surface) - Surface](https://docs.microsoft.com/en-us/surface/surface-system-sku-reference#feedback)
* Content Source: [devices/surface/surface-system-sku-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-system-sku-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Maybe I am misunderstanding your description, but is this something that can be corrected in the documentation?
Or does it affect the driver package file contents?

**Comment by nixtar** [comment]
Sorry, to clarify:

The documentation currently does not contain any information for the first gen Surface Laptop, it only has the second and third gen Surface laptop devices.

**Comment by illfated** [comment]
@nixtar : Thank you for reporting this issue. Your suggestion has been followed up in Pull Request #6383 by @MaratMussabekov and the changes will migrate to the docs.microsoft.com pages within a few days.

**Comment by mypil** [comment]
@nixtar - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/478792e9e8ca776076b12bf329f458565eef6c44.



Thank you for your contribution to make the docs better! Much appreciated!
