### ISSUE TITLE
Telemetry Sample code

### ISSUE THREAD

**Issue by sureshnam** [MicrosoftDocs/windows-itpro-docs#628]
How can i collect telemetry data from my laptop to analyze for my self? Is there an sample code to try

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6e44683-a56a-680b-b5d3-37db2f481494
* Version Independent ID: 870d7125-d56e-c309-9823-851f9a15b26f
* Content: [Windows 10 diagnostic data for the Full diagnostic data level (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/windows-diagnostic-data-1703#feedback)
* Content Source: [windows/configuration/windows-diagnostic-data-1703.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/windows-diagnostic-data-1703.md)
* Service: **unspecified**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by eross-msft** [comment]
This currently isn't something that we cover in this article as it's intended to just be a reference piece. However, I'm including @DaniHalfin since he's the owner of the article and can determine if it's something we might cover in a future version.

**Comment by DaniHalfin** [comment]
@sureshnam - you can see and export the collected data through the accounts dashboard at account.microsoft.com.

Currently, there's no API to query all diagnostic data components. 
You can view it generally through Diagnostic Data Viewer if you'd like.
