### ISSUE TITLE
Linux test

### ISSUE THREAD

**Issue by JakKAaj** [MicrosoftDocs/windows-itpro-docs#6283]
HI, 
Just testing MDATP on Linux x64 with recommended profile. I can't see any information about users logged and in time line shown only alerts no other informations. Please let me know if I need to change something in profile to see more data in MDATP console.  
M
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44a290d4-3386-7f63-0324-4e6219b5dd24
* Version Independent ID: 286954a7-372e-314f-ad9f-d12f5f55b79e
* Content: [Set preferences for Microsoft Defender ATP for Linux - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-preferences)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-preferences.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-preferences.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@JakKAaj - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by azsec** [comment]
@JakKAaj could you share what kind of test did you run? Note that MDATP for Linux is just under public preview and so far it only supports preventative capability for AV. It doesn't support an end-to-end EDR.

**Comment by azsec** [comment]
> @JakKAaj - Thank you for submitting feedback.
> 
> I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.
> 
> If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

What a non-relevant answer and why was the issue closed? This question is about Linux test while you talked about Windows 10 product?

@denisebmsft  @mypil

**Comment by illfated** [comment]
@JakKAaj @azsec : https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements#other-supported-operating-systems

### Other supported operating systems
- macOSX
- Linux (currently, Microsoft Defender ATP is only available in the Public Preview Edition for Linux)

> [!NOTE]
> You'll need to know the exact Linux distros, Android, and macOS versions that are compatible with Microsoft Defender ATP for the integration to work.
>
> Also note that Microsoft Defender ATP is currently only available in the Public Preview Edition for Linux.

**Comment by illfated** [comment]
You may want to open a new issue ticket for each page where you are reasonably sure that it is important to have this Linux-related information replicated.

**Comment by illfated** [comment]
See also ticket #6430 (**Linux support is in preview**) and PR #6477 (**MDATP/Requirements: add Linux Public Preview notes**)

**Comment by azsec** [comment]
@illfated  the question is about missing user logged from the profile that may not be supported and that should have been addressed by PG team. There is nothing related to your issue. Yours are feedback on the content while this question is technical related.

@JakKAaj as far as I know the current MDATP for Linux is only offering preventative capability for Antivirus. It basically means if could help prevent virus/malicious files. The current version doesn't offer you an end-to-end EDR. So from the MDATP portal you cannot see anything like Logged User or Timeline like Windows version because that is limit of the current MDATP for Linux agent.

**Comment by illfated** [comment]
Very well. Thank you for your detailed reply and informative feedback. 👍
