### ISSUE TITLE
Created PR 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#6288]
added new links for windows 10 1803 and 1809.  I am not sure the adjustment while inserting words and format, so I could not see the preview exact site after merging.
I took much care while editing this article. This is the tight work, it's not easy  to me 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa078bf6-a22e-a1e5-4dbd-f7401520d133
* Version Independent ID: 9df06f8b-426c-b444-4478-c6bde84f50db
* Content: [Get support for Windows security baselines - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-security-configuration-framework/get-support-for-security-baselines)
* Content Source: [windows/security/threat-protection/windows-security-configuration-framework/get-support-for-security-baselines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-security-configuration-framework/get-support-for-security-baselines.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@illfated .  @e0i . Please review my PR #6287 .
i think reviewing of this PR is not easy, because it contains different formatted style.
I am sure  added hyperlink is  correct

**Comment by illfated** [comment]
Looks good to me, I am only able to suggest improvements to your issue ticket title text & PR title text.

Suggestion:
**Security Compliance Toolkit: 2018 missing in the version matrix**

**Comment by e0i** [comment]
@RAJU2529 Please do not create blank issues to draw attention to Pull Requests.
