### ISSUE TITLE
Typos in graphic

### ISSUE THREAD

**Issue by blackchr** [MicrosoftDocs/windows-itpro-docs#629]
Under "Policies" in the graphic at the top of this page, there is an entry for "Rembember Crednetials".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5fc2964-2d5a-320c-77b9-948377ca1d62
* Version Independent ID: 6dc6fd2a-2754-0f6c-c8f0-af01f8bf9afd
* Content: [VPN CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpn-csp#feedback)
* Content Source: [windows/client-management/mdm/vpn-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/vpn-csp.md)
* Service: **unspecified**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by Justinha** [comment]
@blackchr thanks for reporting this. It's getting fixed.

**Comment by andreabichsel** [comment]
Issue fixed.
