### ISSUE TITLE
Incomplete Note section

### ISSUE THREAD

**Issue by Ochichka** [MicrosoftDocs/windows-itpro-docs#6291]
The note states that Secure Launch can be enabled if the requirements for Credential Guard, Device Guard and Virtualisation Based Security are met. However this is not true because I have e Secured-core PC, all of the 3 components are enabled and still Secure Launch cannot run. Looks like clarification is needed and troubleshooting section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31d623d9-316c-0ef1-b6be-c3773d77ca21
* Version Independent ID: 83ddb59d-0cfc-34f2-e666-8927d86a04a7
* Content: [System Guard Secure Launch and SMM protection (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@Ochichka . good question,. Which brand and model of processor your laptop or desktop is using..only few processors are supported by secure launch.
Intel i5 7200u does not support secure launch

**Comment by Ochichka** [comment]
Hi @Raju2529, it is Intel i7-8665U CPU which has vPro and all things mentioned in the requirements table. As I said, it is secure-core PC, which means that Microsoft certified it for Secure Launch and all security stuff that Windows 10 supports. The PC brand is Lenovo, the model is X1 Yoga 4th generation.

**Comment by RAJU2529** [comment]
@Ochichka . according to this page **https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-deviceguard#deviceguard-configuresystemguardlaunch**

secure launch supported on enterprise or education .

**Comment by Ochichka** [comment]
@Raju2529 and that is what I have, Win 10 Ent 1909 with Intel vPro i7-8665U and TPM 2.0. As I said, this artcile needs to be more detailed and also it should contain a troubleshooting section.

**Comment by RAJU2529** [comment]
@Ochichka . Wait for few days, let expert users with intel v pro  windows 10 1909 enterprise, will answer your queries. I am not using vpro

**Comment by e0i** [comment]
@Ochichka 

The issue is under investigation, Thank you for providing feedback.

**Comment by Ochichka** [comment]
@e0i, thank you for the information. Since it's been a month, I would like to ask if there are any updates? Thank you.

**Comment by e0i** [comment]
@Ochichka Apologies for the delay as I have been struggling with a growing backlog lately. The issue has been assigned to an independent contributor. Expect a PR within the coming few days. Thank you for following up.

**Comment by e0i** [comment]
@joinimran Any updates with this issue? Thanks.

**Comment by joinimran** [comment]
@e0i I have tried to arrange a secure-core PC but failed to arrange the hardware recommended by Microsoft. 

@Ochichka - I would suggest you please open up a support case with Microsoft to further look into this issue. As you have mentioned that everything is as per Microsoft recommendation then why your service is not working as expected. Engaging Microsoft support will help you to route this issue to the product development team to better answer your query and from there on this document can get updated content.

Thanks
Imran.

**Comment by Ochichka** [comment]
@joinimran, how can I open a support case? I'm individual not company. I would've done it already if I could

**Comment by RAJU2529** [comment]
@Ochichka ,  Will you take a video of the configured settings, including group policy, windows settings, bios settings. I want to see that video, uploAD THE VIDEO in youtube, share the link here.

also, you can post questions on **https://answers.microsoft.com/en-us**
**https://techcommunity.microsoft.com/**

**Comment by joinimran** [comment]
@Ochichka - Please visit https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10 to contact Windows 10 support team and open up a case with Microsoft regarding this issue.

**Comment by illfated** [comment]
I know this has been a long process full of delays, but as a final attempt, I would just like to ask if this could have anything to do with the BIOS mode on the computer, if it is in UEFI mode or Legacy mode.

Based on my experience from replying to many posts about the command `mountvol X: /s` (returning the output `The parameter is incorrect.` where lots of users claim that the documentation for the parameter /s should be removed because it is invalid), it sometimes happens because the users have set their BIOS to Legacy mode instead of UEFI mode. Could this be the case here?

**Comment by Ochichka** [comment]
@illfated, in my case UEFI is fully enabled and configured. And I can successfully mount it by executing the command you mention. @joinimran, I'll purchase the premium Windows support plan as you suggested and hope they will resolve the issue. My concern is that they might say this is product-specific issue with my Lenovo laptop. Which turns into a chicken-egg type of situation. From Lenovo support they say this is Windows issue, and I hope Microsoft won't say the same about Lenovo. That is why I requested this article to be updated and improved.

**Comment by illfated** [comment]
Fair point. I admit that I also find those catch-22 or ("Who came first, the chicken or the egg?") scenarios tedious and very counterproductive. I can only wish you the best of luck.
