### ISSUE TITLE
Also enable Uninstall/Reinstall on Windows client?

### ISSUE THREAD

**Issue by HenkPoley** [MicrosoftDocs/windows-itpro-docs#6293]
It would be useful if `{Uninstall, Install}-WindowsFeature -Name Windows-Defender` was also available on Windows client (e.g. Home, Pro, Education).

Since some malware can corrupt Windows Defender, but there is _no_ endorsed no way to repair it.

To make this a documentation targeted request:

Please document how to reinstall Windows Defender on Windows client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d1dee2b-d86a-0019-f689-81483fab31f5
* Version Independent ID: 02722ca2-1dde-aafb-22e3-67259c4ece37
* Content: [Windows Defender Antivirus on Windows Server 2016 and 2019 - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-on-windows-server-2016)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-on-windows-server-2016.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-on-windows-server-2016.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by kannanb-github** [comment]
It is nice to receive feature add related suggestions. Please send us if you have any question-related documentation specifically the Windows Defender Antivirus on Windows Server 2016 and 2019 - Windows security document. If you want to get the feature added to Windows 10, we suggest you to please use the appropriate UserVoice site to send your feature-add as a suggestion. 

You can disable or enable the Windows defender Antivirus real-time protection if another third party Anti Virus application is installed, but uninstall or reinstall is not an option in Windows 10. 
We appreciate your feedback and request you to give us feedback on this documentation to make the document for improvement to other readers.

**Comment by illfated** [comment]
Looks like there could have been a miss or typo in selecting the correct PR or issue ticket numbers. @HenkPoley : Feel free to open a new ticket if you find that this ticket has resolved your issue.
