### ISSUE TITLE
Recover WIP-protected after unenrollment

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#6294]
Hello,

About this step:
"Where "new_location" is in a different directory. This can be on the employee’s device or on a shared folder on a computer that runs Windows 8 or Windows Server 2012 or newer and can be accessed while you're logged in as a data recovery agent."

Can you please explain what does it mean "while you're logged in as a data recovery agent"? How to login like this using Windows 10 Azure AD Join setup + WIP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16e6e551-830e-f69e-31bc-e109e5b594f4
* Version Independent ID: 3396045c-8295-b801-aba5-11a11dd62dc0
* Content: [Make & verify an EFS Data Recovery Agent certificate (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-and-verify-an-efs-dra-certificate)
* Content Source: [windows/security/information-protection/windows-information-protection/create-and-verify-an-efs-dra-certificate.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/create-and-verify-an-efs-dra-certificate.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
@lightupdifire - Thank you for your query. To login as a data recovery agent, please see how to create a data recovery agent account by https://docs.microsoft.com/en-us/previous-versions/tn-archive/cc875821(v=technet.10)?redirectedfrom=MSDN

This can also be used for the local device account. You can follow the steps under "To create a local recovery agent" in the document. Once your recovery agent account is setup then you can follow the steps provided in the document.

Thanks
Imran

**Comment by lightupdifire** [comment]
@joinimran 
Thanks for the info. Then I think if we have a local admin account on the computer and EFS DRA certificate created for WIP, for the full cloud Windows 10 this should be enough.
