### ISSUE TITLE
Drivers for Mouse, Keyboard, Touch 1809+ PE 

### ISSUE THREAD

**Issue by Spartan-196** [MicrosoftDocs/windows-itpro-docs#6295]
After working with Microsoft I have found that this set of driver folders enabled full keyboard, trackpad, and touch functionality in PE.

|         Folder         |               File               |
|:-----------------------|---------------------------------:|
| IclSerialIOGPIO        |            ialpss2_gpio2_icl.inf |
| IclSerialIOI2C         |              ialpss2_i2c_icl.inf |
| IclSerialIOSPI         |              ialpss2_spi_icl.inf |
| IclSerialIOUART        |            ialpss2_uart2_icl.inf |
| itouch                 |               iaprecisetouch.inf |
| IclChipset             |          icelakepch-lpsystem.inf |
| IclChipsetLPSS         |      icelakepch-lpsystemlpss.inf |
| IclChipsetNorthpeak    | icelakepch-lpsystemnorthpeak.inf |
| ManagementEngine       |                         heci.inf |
| SurfaceAcpiNotify      |      surfaceacpinotifydriver.inf |
| SurfaceBattery         |               surfacebattery.inf |
| SurfaceDockIntegration |       surfacedockintegration.inf |
| SurfaceHidMini         |         surfacehidminidriver.inf |
| SurfaceHotPlug         |               surfacehotplug.inf |
| SurfaceIntegration     |     surfaceintegrationdriver.inf |
| SurfaceSerialHub       |       surfaceserialhubdriver.inf |
| SurfaceService         |     surfaceservicenulldriver.inf |
| SurfaceStorageFwUpdate |       surfacestoragefwupdate.inf |

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b195b1b-81bf-310e-3ff4-e520826e7e94
* Version Independent ID: fb399be5-9fb5-a3f9-f912-ed3fde235f05
* Content: [How to enable the Surface Laptop keyboard during MDT deployment - Surface](https://docs.microsoft.com/en-us/surface/enable-surface-keyboard-for-windows-pe-deployment#feedback)
* Content Source: [devices/surface/enable-surface-keyboard-for-windows-pe-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/enable-surface-keyboard-for-windows-pe-deployment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by joinimran** [comment]
@Spartan-196 - Can you please confirm if these settings are applicable for Surface 1, 2, or 3 or for all.

**Comment by Spartan-196** [comment]
I’ll have to see what devices I have available. 
I was exclusively working with the surface laptop 3 at the time to enable part of a remote workforce.
