### ISSUE TITLE
Windows 10 1909

### ISSUE THREAD

**Issue by joshrpg** [MicrosoftDocs/windows-itpro-docs#6297]
1909 is missing from the windows 10 list. I'm assuming its still v6 though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9ca7cb6-32cb-1517-a9de-c36046955d45
* Version Independent ID: 91041e39-007e-f481-0cd4-177b4039ae12
* Content: [Create mandatory user profiles (Windows 10) - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mandatory-user-profile#feedback)
* Content Source: [windows/client-management/mandatory-user-profile.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mandatory-user-profile.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@joshrpg 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.
