### ISSUE TITLE
To which server does this document refer?

### ISSUE THREAD

**Issue by Ghostmokey582** [MicrosoftDocs/windows-itpro-docs#6298]
There can be up to 5 MBAM servers in a normal environment: 2 database servers, 1 reporting server and 2 IIS servers.  Do we need to apply above information on all servers separately? And if so, which is the preferred order?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67626969-2854-3925-fc2d-9d8a09183796
* Version Independent ID: f442462e-6e55-406d-9a77-4e98e6dc036f
* Content: [Applying hotfixes on MBAM 2.5 SP1 - Microsoft Desktop Optimization Pack](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/apply-hotfix-for-mbam-25-sp1)
* Content Source: [mdop/mbam-v25/apply-hotfix-for-mbam-25-sp1.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/mdop/mbam-v25/apply-hotfix-for-mbam-25-sp1.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by VLG17** [comment]
@Ghostmokey582 i see there was [another issue](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4115) with the exact same question.

I have to say that the answer remains the same, meaning that this site is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. If you have suggestions related to this documentation, please let us know here and we will submit them for review.

As for your question, you can leverage the [MBAM TechNet Forum](https://social.technet.microsoft.com/Forums/en-US/home?forum=mdopmbam&filter=alltypes&sort=lastpostdesc) or submit it through the [User Voice hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app).
