### ISSUE TITLE
ブロックされる サイトについて (What sites are blocked?)

### ISSUE THREAD

**Issue by dev-nawa** [MicrosoftDocs/windows-itpro-docs#6301]
「ネットワーク保護によってブロックされる不審な接続: このアラートは、ユーザー設定のインジケーターリスト内の web サイトまたは web サイトにアクセスしようとしたときに、ブロックモードでネットワーク保護によって停止された場合に生成されます。」と記載がありますが、「または web サイトにアクセスしようとしたときに」という文言は現在の仕様からも不要である認識です。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3c35d83f-c8ac-fc08-edbb-8acffd1ceba0
* Version Independent ID: ddbe845b-be05-baab-7587-38603a04df6d
* Content: [Microsoft Defender ATP の web 脅威に対応する - Windows security](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-atp/web-protection-response#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/web-protection-response.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/web-protection-response.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by denisebmsft** [comment]
As translated by Bing Translator: 

"Suspicious connections blocked by network protection: This alert occurs when you try to access a website or website in a custom indicator list Generated when stopped by network protection in block mode. The wording "or when you try to access a website" is recognized as unnecessary from the current specification."

**Comment by MaratMussabekov** [comment]
Hello @denisebmsft, @dev-nawa,
"this alert is generated when an attempt to access a **malicious website** or a **website in your custom indicator list**", which means, it blocks two types of websites: 1. malicious websites 2. websites in your custom indicator list.
For me, no change in the document is required (at least in the en-us version)
Thank you

**Comment by illfated** [comment]
Maybe this is a translation issue and that the word "malicious" has been lost in the machine translation?

Main ticket post, as translated by Google:
> "Suspicious connection blocked by network protection: This alert is generated when you try to access a website or website in the user-defined indicator list and are blocked by network protection in block mode. However, the phrase "or when trying to access a website" is a recognition that is unnecessary even from the current specification.

@TinaMcN : May I suggest checking with a qualified fluent Japanese reader/speaker to find out if the word "malicious" is missing in the Japanese translation?

**Comment by illfated** [comment]
Update: possible issue with the Japanese kanji in its translated form, based on the content of this section:

## Web 脅威の通知を表示する
Microsoft Defender ATP は、悪質または疑わしい web アクティビティについて次の警告を生成します。
- **ネットワーク保護によってブロック**される不審な接続: このアラートは、ユーザー設定のインジケーターリスト内の web サイトまたは web サイトにアクセスしようとしたときに、ブロックモードでネットワーク保護によって停止された場合に生成されます。
- **ネットワーク保護によって検出された不審な接続:** このアラートは、ユーザー設定のインジケーターリスト内の悪意のある web サイトまたは web サイトにアクセスしようとしたときに、監査専用モードのネットワーク保護によって検出された場合に生成されます。

Possible view from a Japanese reader's viewpoint (as translated by web engine):

## View web threat notifications
Microsoft Defender ATP generates the following alert for malicious or suspicious web activity:
- Suspicious connection blocked by network protection: This alert is generated when you try to access a website or website in the user-defined indicator list and are blocked by network protection in block mode.
- Suspicious connection detected by Network Protection: This alert is generated when an attempt is made to access a malicious website or website in the user-defined indicator list and detected by Network Protection in Audit Only mode. Will be

**Comment by TinaMcN** [comment]
@OfficeGlobal please human translate this article.

**Comment by mypil** [comment]
@TinaMcN @officeglobal - Do you have any updates on this?

thank you.

**Comment by OfficeGlobal** [comment]
@mypil sorry for a delay, the article will be updated within a day.
Could you please assign the upcoming issues to us instead of a comment only?

**Comment by mypil** [comment]
@OfficeGlobal - This is noted. Assigning issue to you. Please let us know once this has been fixed. 

Thank you.

**Comment by mypil** [comment]
@OfficeGlobal - Do you have any updates on this? Is this already resolved?

Thank you!

**Comment by illfated** [comment]
To me, using Bing Translator, it seems to be resolved now. English translation through Bing:
***
**View web threat alerts**

Microsoft Defender ATP generates the following alerts for malicious or suspicious Web activities:

- **Network protection blocked suspicious connections** — This alert is generated when access to a malicious web site or a web site in a custom indicator list is "stopped" by network protection in "block" mode.

- **Network protection detected a suspicious connection** — This alert is generated when network protection in "audit only" mode detects access to a malicious web site or a Web site in a custom indicator list.
***
Previous content (copied from [my April 3 comment above](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6301#issuecomment-608230270):

## Web 脅威の通知を表示する
Microsoft Defender ATP は、悪質または疑わしい web アクティビティについて次の警告を生成します。
- **ネットワーク保護によってブロック**される不審な接続: このアラートは、ユーザー設定のインジケーターリスト内の web サイトまたは web サイトにアクセスしようとしたときに、ブロックモードでネットワーク保護によって停止された場合に生成されます。
- **ネットワーク保護によって検出された不審な接続:** このアラートは、ユーザー設定のインジケーターリスト内の悪意のある web サイトまたは web サイトにアクセスしようとしたときに、監査専用モードのネットワーク保護によって検出された場合に生成されます。
***
Current content in /ja-jp/:

## Web の脅威のアラートの表示
Microsoft Defender ATP は、悪意のあるまたは疑わしい Web 活動に対して次のアラートを生成します。
- **ネットワーク保護によって疑わしい接続がブロックされました — このアラ**ートは、悪意のある Web サイトまたはカスタム インジケーター リスト内の Web サイトへのアクセスが、"ブロック" モードのネットワーク保護によって "停止" されたときに生成されます。
- **ネットワーク保護によって疑わしい接続が検出されました — このアラ**ートは、悪意のある Web サイトまたはカスタム インジケーター リスト内の Web サイトへのアクセスが、"監査のみ" モードのネットワーク保護によって検出されたときに生成されます。

**Comment by mypil** [comment]
@dev-nawa - Thank you for submitting this feedback.

From our understanding, the issue has been resolved so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
