### ISSUE TITLE
Microsoft Defender ATP (Advanced Hunting) Protocol is showing only TCP traffic no UDP

### ISSUE THREAD

**Issue by kareemalhourani** [MicrosoftDocs/windows-itpro-docs#6302]
In Advanced hunting tab I'm trying to query "Protocol" for UDP traffic but i cannot find any, all of them are TCP.

Is there a workaround to find UDP traffic?

Ref: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-devicenetworkevents-table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a36d7458-278b-4eec-237c-ca71c547dbb0
* Version Independent ID: 8c5a7ed7-5ef7-abcf-b37b-d3b7e826c615
* Content: [DeviceNetworkEvents table in the advanced hunting schema - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-devicenetworkevents-table)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-devicenetworkevents-table.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-devicenetworkevents-table.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by mypil** [comment]
@kareemalhourani - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
