### ISSUE TITLE
There is no need to reset PC, if user forgot login password

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#6307]
There is no need to Reset PC in windows 10 ,  without resetting i can able to remove forgotten windows login local password, All account password will store  SAM file. Recently i  got file ntwspass.exe file which is safe file scanned by windows defender. 
i added that file in Windows 10 PE 1909 iso, and i kept for personal usage.
I really tested on own laptop, whether that file is really working or not. But that file is worked and changed the embedded password to blank password to log in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bd25036-bb23-374f-4db7-480b3d27bcc0
* Version Independent ID: 027a84e4-40f5-a4e6-7a86-aa3ad078473d
* Content: [Technical support policy for lost or forgotten passwords - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/password-support-policy#feedback)
* Content Source: [windows/security/identity-protection/password-support-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/password-support-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by e0i** [comment]
Closing because the question is about https://support.microsoft.com/en-us/help/4028457/windows-10-reset-your-local-account-password, which is out of our scope.

Thank you for your ongoing engagement.
