### ISSUE TITLE
Step 9 under Verify section is completely wrong

### ISSUE THREAD

**Issue by peterholdridge** [MicrosoftDocs/windows-itpro-docs#6309]
Step 9 under the "Verify" section is completely wrong. For Hybrid Azure AD Join devices, you do not need to enable "Azure AD Join" for this to work. Hybrid Azure AD Join is already completed with AD Connect. That is the whole point of this exercise - to enroll Hybrid Azure AD Joined devices, not Azure AD Joined devices. Was this mistakenly put in here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy#feedback)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@peterholdridge I think you are looking at this from a different angle. The option presented under step 9 is set to "All" by default. So the point of looking at that is to make sure it was not changed. What you said is also correct:

> Hybrid Azure AD Join is already completed with AD Connect

But AD Connect would not be able to take the right actions, if the setting under step 9 would be set to "None", for example. My take is that we should verify all these 10 steps (requirements) in order to make sure that nothing will "block" our Hybrid Azure AD Join deployment.

**Comment by peterholdridge** [comment]
> @peterholdridge I think you are looking at this from a different angle. The option presented under step 9 is set to "All" by default. So the point of looking at that is to make sure it was not changed. What you said is also correct:
> 
> > Hybrid Azure AD Join is already completed with AD Connect
> 
> But AD Connect would not be able to take the right actions, if the setting under step 9 would be set to "None", for example. My take is that we should verify all these 10 steps (requirements) in order to make sure that nothing will "block" our Hybrid Azure AD Join deployment.

Sir, I'm not sure if you actually are with Microsoft or not, but this reply isn't sufficiently satisfactory. "different angle" isn't a valid argument. This is our experience. If you set Azure AD Join to none, you protect your organization from personal computers joining and it doesn't affect the Hybrid Azure AD Joined computers. This step shouldn't even be in this article since it has no affect on the outcome and setting it to "All" or "Selected" isn't necessary to get this to work.

**Comment by e0i** [comment]
@ManikaDhiman Can you shed light on this question in your own time? Thank you.

**Comment by greg-lindsay** [comment]
Hi, this is a very old issue and I believe the original issue author is correct. If you look at step 4 you will see that the device is already  Azure AD joined.  We are looking to get automatic Intune enrollment, not automatic Azure AD joining.  So, step 9 should just be removed.  This setting has no bearing on the procedure.  I will remove this.

**Comment by greg-lindsay** [comment]
This will be fixed shortly in a PR in the private repo.
