### ISSUE TITLE
I can't download the uninstall script after trial is over - ERROR

### ISSUE THREAD

**Issue by pedroalpha** [MicrosoftDocs/windows-itpro-docs#631]
- Windows 10 enterprise
- Build 17.127
- Trial expired

I can't uninstall the client look at the error: " Failed to create download package 
Http failure response for https://winatpmanagement-us.securitycenter.windows.com/DownloadOffboardingPackage?mgmtTool=2: 403 Forbidden"

p.s: I have the Enterprise Mobility + Security E5 package - Shouldn't I have access to ATP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfc0921d-e59b-5186-0dec-7c2facb66f1c
* Version Independent ID: 1fc0f7ba-f8cd-d071-75de-dc5a1af868c0
* Content: [Onboard endpoints and set up the Windows Defender ATP user access](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/onboard-configure-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/onboard-configure-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/onboard-configure-windows-defender-advanced-threat-protection.md)
* Service: **unspecified**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Please contact your Windows Defender ATP contact for help on offboarding after a trial expires.
