### ISSUE TITLE
Defender ATP through CSP

### ISSUE THREAD

**Issue by win2000b** [MicrosoftDocs/windows-itpro-docs#6313]
Hi, please can you clarify is the licensing requirements have now changed? We can now see this as a standlone product we can license through CSP. Is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by PCParker** [comment]
Hi, from the article I would understand you need to have either on the below products to be able to  use ATP 
Windows 10 Enterprise E5
Windows 10 Education A5
Microsoft 365 E5 (M365 E5) which includes Windows 10 Enterprise E5
Microsoft 365 E5 Security
Microsoft 365 A5 (M365 A5)

**Comment by win2000b** [comment]
Thats my point. There are numerous news articles stating this is now available as standalone. Its available through CSP as standalone as well. Can we get this clarified from the MS team?

**Comment by benfmarshall** [comment]
I also am confused. The skus listed about already have WDATP. What are the minimum license requirements to purchase and deploy the WDATP Standalone sku? Offier ID: e2dcab13-1365-417a-b624-4901e2b252f5
Please advise

**Comment by mjcaparas** [comment]
Yes, any of the licenses listed will provide access to Microsoft Defender ATP. 

The stand alone sku is Microsoft 365 E5 Security.
