### ISSUE TITLE
What are the requirements and costs for Windows Analytics solutions?

### ISSUE THREAD

**Issue by grex86** [MicrosoftDocs/windows-itpro-docs#632]
in Device Health under column number 3 "Diagnostic data requirements" should be written "enhanced" and not "windows 10"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f20e3377-fdbc-ac87-239e-7184db24a685
* Version Independent ID: 0464da82-efa4-b147-bba9-d6802cf9d273
* Content: [Frequently asked questions and troubleshooting Windows Analytics](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-faq-troubleshooting)
* Content Source: [windows/deployment/update/windows-analytics-FAQ-troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-FAQ-troubleshooting.md)
* Service: **unspecified**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
This is fixed.
