### ISSUE TITLE
Do Servicing Stack Update's appear in the Windows Update history?

### ISSUE THREAD

**Issue by Nicholas-Steel** [MicrosoftDocs/windows-itpro-docs#6323]
When clicking "View Update History" in Windows Update, the latest Security Update was installed 14/02/2020 but the latest Servicing Stack Update was released in March.

It seems my most recent issue with the latest Cumulative Update KB4541335 may be caused by the Servicing Stack Update not being installed by Windows Update like it's supposed to be. I haven't tested manually installing the Servicing Stack Update yet.

This all assumes Servicing Stack Updates are supposed to appear within the Windows Update History.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b706f0af-d504-a8ca-7c38-b8bb9283bfad
* Version Independent ID: 14f31acf-9f47-59a6-269f-62ab249fe560
* Content: [Servicing stack updates (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates)
* Content Source: [windows/deployment/update/servicing-stack-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/servicing-stack-updates.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by Nicholas-Steel** [comment]
It looks like they are not listed in Windows Update History. I tried manually installing the March update and got the message that it's already installed.

**Comment by Margaretgo** [comment]
True

**Comment by Nicholas-Steel** [comment]
As an update to this topic, I was able to install KB4541335 after a reboot of my computer (not sure why I needed to reboot for the install to work). This implies I either had the latest Servicing Stack Update and I unknowingly needed to reboot the PC to complete its installation or something... else... was causing the update to fail.

**Comment by e0i** [comment]
@Nicholas-Steel 

The issues section of this repository is intended for documentation and content-related issues.

Would you please discuss the matter via the link below so that that your question gets answered quickly?

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
