### ISSUE TITLE
Fallback order 

### ISSUE THREAD

**Issue by Stroell** [MicrosoftDocs/windows-itpro-docs#6325]
In the following sentence, an "immediately" should be added to avoid confusion when a fallback is happening. This makes it clear, that there is no wait time until the next source is used:

Updates are obtained from sources in the order you specify. If a source is not available, the next source in the list is used (immediately).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c033d14-427d-26d5-eca8-facf190da87d
* Version Independent ID: 624d52e5-6cf5-534e-83c3-66925292ddcd
* Content: [Manage how and where Windows Defender AV receives updates - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/manage-protection-updates-windows-defender-antivirus#fallback-order)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/manage-protection-updates-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/manage-protection-updates-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thanks @Stroell for the feedback! I've made this change and you'll see the update rendering live a little later today. Thank you for helping us improve our documentation.

**Comment by Stroell** [comment]
Amazing! Thanks for the quick fix :-)
