### ISSUE TITLE
missing helpful information for Windows 7

### ISSUE THREAD

**Issue by ryeguy637** [MicrosoftDocs/windows-itpro-docs#633]
The information in this URL I'm adding was critical to making pre-provisioning work with Windows 7 and a WinPE 10 environment.  It should be incorporated into this article somehow.   Otherwise a black screen (for Windows 7) occurs at restart (after Install phase concludes) indicating that the drive cannot be unlocked.
 
https://blogs.technet.microsoft.com/system_center_configuration_manager_operating_system_deployment_support_blog/2016/03/30/windows-versions-prior-windows-10-build-1511-fail-to-start-after-setup-windows-and-configuration-manager-step-when-pre-provision-bitlocker-is-used-with-windows-pe-10-0-586-0-1511/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e11e1beb-b1ed-8a2d-f3d9-810e777fe594
* Version Independent ID: e4f95ae3-0ac2-37b6-ba5e-d1ff67855109
* Content: [How to Enable BitLocker by Using MBAM as Part of a Windows Deployment](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/how-to-enable-bitlocker-by-using-mbam-as-part-of-a-windows-deploymentmbam-25#feedback)
* Content Source: [mdop/mbam-v25/how-to-enable-bitlocker-by-using-mbam-as-part-of-a-windows-deploymentmbam-25.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/how-to-enable-bitlocker-by-using-mbam-as-part-of-a-windows-deploymentmbam-25.md)
* Service: **unspecified**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by Justinha** [comment]
This is live now: https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/how-to-enable-bitlocker-by-using-mbam-as-part-of-a-windows-deploymentmbam-25
