### ISSUE TITLE
Nearly perfect in uselessness, especially for home users

### ISSUE THREAD

**Issue by ADWolfe-LoyNO** [MicrosoftDocs/windows-itpro-docs#6333]
How is it that this page does not have a single example of an ASR rule or any guidance for which rules to enable?
Why is this completely oriented towards network administrators who have tightly maintained firewalls with no consideration of home users?
What are InTune, Endpoint Configuration Manager, etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4144ff8c-3d92-d2d7-27ad-4a37843a1008
* Version Independent ID: 43cc32fc-6e2f-5c30-b758-666a53c0052b
* Content: [Enable ASR rules individually to protect your organization - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/enable-attack-surface-reduction#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/enable-attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/enable-attack-surface-reduction.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by RAJU2529** [comment]
@ADWolfe-LoyNO. This article is also for home users with windows 10 professional or education editions You can able to configure through PowerShell commands.
i added those commands in text file 

[windows defender Enable attack surface reduction rules.txt](https://github.com/MicrosoftDocs/windows-itpro-docs/files/4395132/windows.defender.Enable.attack.surface.reduction.rules.txt)

**Comment by denisebmsft** [comment]
Thank you @ADWolfe-LoyNO for posting your question. And thank you @RAJU2529 for your help! It looks like this is resolved so I am going to close this issue out.
