### ISSUE TITLE
Missing code 0x800B0100

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-itpro-docs#6337]
Add description for the error code 0x800B0100.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f76d96ac-5343-20e2-9d99-9c1cea7ccc2e
* Version Independent ID: a95c9b39-4a66-d726-4404-de5af60ac982
* Content: [Windows Update error code list by component - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-error-reference)
* Content Source: [windows/deployment/update/windows-update-error-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-error-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
(see also tickets #6324 and #5718 for similar (minimalistic) reports)

**Comment by greg-lindsay** [comment]
Please use https://docs.microsoft.com/en-us/windows/deployment/upgrade/setupdiag to analyze upgrade failures. This is the preferred tool now. We don't have the ability to provide guidance for every error code at this time.  The troubleshooting article was written before the SetupDiag tool was available.
