### ISSUE TITLE
CloudAssignedOobeConfig

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/windows-itpro-docs#6340]
Can you explain how this value is created? When I use Windows Offline Autopilot I get values that does not make sense to me. I got 286 and 284 and 270 for example. How is this number put together? Second, I cannot configure SkipCortanaOptIn and SkipEula in AutoPilot Profile, so how is this reflected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17bfe927-f7b7-608b-8537-5c2274ccdced
* Version Independent ID: 5dd9abca-92d9-fbb2-6796-d1f6b9ab3c8b
* Content: [Windows Autopilot for existing devices - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/existing-devices)
* Content Source: [windows/deployment/windows-autopilot/existing-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/existing-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@mypil . please close this issue, because this user already issue #6339

**Comment by mypil** [comment]
@BakkerJan - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
