### ISSUE TITLE
Outlook OST and PST files not protected by Windows Information Protection

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/windows-itpro-docs#6343]
In this Gitlab thread it appears that Outlook OST and PST files are not protected by Windows Information Protection by default, and hence if Outlook is used in Cached Exchange Mode (the default), any mailbox data downloaded by Outlook will not be removed as part of a remote device wipe, nor will it be protected by WIP encryption by default.

This should be highlighted as a major limitation in WIP until it is no longer the case.

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6172

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f23c9b6-81aa-b06d-5c19-196ac933b6ff
* Version Independent ID: 0c7eb396-4274-c546-6063-6d38382b956d
* Content: [Limitations while using Windows Information Protection (WIP) (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/limitations-with-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/limitations-with-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/limitations-with-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@ChrisAtMAF .   Email attachments downloaed from. Outlook. We can able to block or disabled through. Windows defender ASR rules

**Comment by ChrisAtMAF** [comment]
@RAJU2529 But the attachment data is also stored in the OST files so it will still be left on the device in another form, unencryped, if WIP is enabled.

**Comment by RAJU2529** [comment]
@ChrisAtMAF .  I am taking Attack Surface Rule, once you enabled the standard rules via powershell . dangerous aattachments will not will be blocked

**Comment by mypil** [comment]
@ChrisAtMAF - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/90f70b5981d8c347cbe4ced42e1041dad36a0a3e.

Thank you for your contribution to make the docs better! Much appreciated!
