### ISSUE TITLE
missing 0x8024043D

### ISSUE THREAD

**Issue by GitHubSachin** [MicrosoftDocs/windows-itpro-docs#6344]
We see many instances of error code 0x8024043D Can you please add this code to the list and possible fix for that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f76d96ac-5343-20e2-9d99-9c1cea7ccc2e
* Version Independent ID: a95c9b39-4a66-d726-4404-de5af60ac982
* Content: [Windows Update error code list by component - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-error-reference)
* Content Source: [windows/deployment/update/windows-update-error-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-error-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
(Ref. merged PR #6636 )

**Comment by mypil** [comment]
@GitHubSachin - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/bfb3dd398d69a8282d512eaec04fe102a6da5f00. 


Thank you for your contribution to make the docs better! Much appreciated!
