### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by TokenRing** [MicrosoftDocs/windows-itpro-docs#6346]
"Your organization has a well-defined process for application management and deployed." is not a complete sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c360225-c6aa-04e2-6856-500e9bc11320
* Version Independent ID: 4b27602c-27e0-3154-757d-20f483d7e10f
* Content: [Understand Windows Defender Application Control policy design decisions  (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/understand-windows-defender-application-control-policy-design-decisions#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/understand-windows-defender-application-control-policy-design-decisions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/understand-windows-defender-application-control-policy-design-decisions.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
I was unable to find any other pages elsewhere by doing a web search, so I presume this typo has not been discussed much elsewhere. Furthermore, I am guessing that the easiest way to resolve this typo would be to replace the word "deployed" with **deployment** :
- Your organization has a well-defined process for application management and deployment.

Do you have any objections or suggestions for a different phrasing? Feel free to reply with your thoughts on this.

**Comment by RAJU2529** [comment]
@illfated . Just now I commented on your PR.

**Comment by illfated** [comment]
Yes, I noticed. Simply commenting in a PR or issue ticket created or commented in by me is enough to have that page added to my github list of "**Participating**" pages. I always check my [Participating] list before I move on to non-participating pages.

**Comment by mypil** [comment]
@TokenRing - Thank you for pointing this out.

PR #6351 has been created by @illfated to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
