### ISSUE TITLE
Lack of instructions on how to modify certificates is an issue.

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/windows-itpro-docs#6349]
The document implies one must edit the existing Domain Controller certificated template - that is not possible.

I suspect i have to the same instructions as https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki#certificate-templates but i would be nice if it could clearly state that.

If the domain controller cert / cert template instructions are the same for Key Trust and PKI then consider having one unified page for 'configuring DC certificate templates'

One other piece of feedback - this is *waaay* too complex, this is certificates, smartcard and direct access all over again - the only company capable of figuring it out and deploying it will be Microsoft.  

Consider having something that customers who don't have CA servers can use to bootstrap windows one hello in one operation.

my feedback is from ex-windows server product planner / product manager - seriously no one is gonna deploy this at scale in real world, way too hard and complex.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c47de28c-e44b-ca73-efde-fae303e0d3f8
* Version Independent ID: 71202a24-5b2f-844a-acce-d48c46873f2b
* Content: [Hybrid Key trust Windows Hello for Business Prerequisites (Windows Hello for Business) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by scyto** [comment]
i think this issue and https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6350 are the same issue you might want to keep one and close the other

i did get this working but i don't see how mere mortals can! the docs do a good first job of doing full guide for a product that is incredibly complex so well done, the last mile of changes to make each flow euqally detailed and if you could create a flow chart troublehsooting doc that summarizes some of the things scattered across each of the four trust models but that apply equally to all would be super helpful.

This doc https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6350 and this doc https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-authentication#hybrid-azure-ad-join-authentication-using-a-key were what led me to finally figure out i need to wireshark capture and it wasn't as simple as a DNS issue, my CA cert or DCcert!  But no doc ever said 'check the CBP CRL path on the first CRL list that is published!

i love those flow diagrams, that was super useful!

**Comment by MaratMussabekov** [comment]
Hello @scyto ,
basically you don't need to change anything as the default template of AD CA meet all the requirements.
The requirements are listed for third party CAs (as it is stated in the article).
I think it is not possible to create a detailed instruction of "what should be done" for third-party CAs, as the CAs could vary.
What do you think?
Thank you

**Comment by mypil** [comment]
@scyto - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/f2f987dc5b4cf49d8d61e52605d6fca3f73439f5. 


Thank you for your contribution to make the docs better! Much appreciated!
