### ISSUE TITLE
Error code 0x80070781 should be added

### ISSUE THREAD

**Issue by reklov79** [MicrosoftDocs/windows-itpro-docs#635]
What helped with error code 0x80070781 was:
open cmd prompt with administrator rights
enter `takeown /f C:\Windows\ServiceProfiles\LocalService\AppData\Local\Microsoft\NGC /R`
if it asks you to get full access to that file, accept with "Yes"
delete the file C:\Windows\ServiceProfiles\LocalService\AppData\Local\Microsoft\NGC
restart computer and set up new PIN code

See also https://answers.microsoft.com/en-us/windows/forum/windows_10-hello-winpc/login-setup-wont-take-a-pin/248fbc21-eb94-41b5-8e2f-1e134dc5316e although the described method without "/R" was not working for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Service: **unspecified**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by Justinha** [comment]
@reklov79 Thanks for the suggestion. We shared this with the engineering team.
