### ISSUE TITLE
Where is the Key Trust version of this page with this level of detail?

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/windows-itpro-docs#6350]
Where is the Key Trust version of this page with this level of detail?

The page you have for key trust makes little sense as it is unclear if i need to do the same as here or create a new DC cert from the DC template or kerberos template. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd063d0c-8739-15bd-4f16-11b893029845
* Version Independent ID: cd3679fe-dd9c-44f9-04ed-c772a47ca4e4
* Content: [Configuring Hybrid Windows Hello for Business - Public Key Infrastructure (PKI) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mypil** [comment]
@scyto  - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/f2f987dc5b4cf49d8d61e52605d6fca3f73439f5. 


Thank you for your contribution to make the docs better! Much appreciated!
