### ISSUE TITLE
 Password Synchronization with Azure AD Connect link generates 404 not found issue.

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/windows-itpro-docs#6352]
this linkk no longer works, please provide the right link
 Password Synchronization with Azure AD Connect

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c47de28c-e44b-ca73-efde-fae303e0d3f8
* Version Independent ID: 71202a24-5b2f-844a-acce-d48c46873f2b
* Content: [Hybrid Key trust Windows Hello for Business Prerequisites (Windows Hello for Business) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs#public-key-infrastructure)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
(Ref. #6363 )

**Comment by scyto** [comment]
Hi, i solved this - it was an issue with CRL CBP path on an upstream CRL list, noe the certificate.
i think i found a bug in windows 2019 CA that when you set the wrong HTTP CBP path on the CA, issue a couple of certs and then correct it - while the new certs get the right CBP the CRLs lists do not!

Fidinigs in deatil:

-the CRL path on the DC cert (installed locally on win10 machine was right)
-this referenced a HTTP accessible CRL like http://myserver/path/mycaname.crl
-the CRL like http://myserver/path/mycaname.crl had its own CRL attribue pointing to this referenced a HTTP accessible CRL like http://myserver/path/mycaname+.cr
-this file no longer existed, it had right file extension of .crl no cr
-this came about because I fat fingered the CA extension for the CRL CDPS, i corrected that and it worked for all other certs, however it was not corrected in the CRL attribute on the CRL itself.
-republishing the CRLs didn't seem to fix this
-in the end i renewed the CA cert and then republished the CRLs and this fixed the incorrect CRL path attribute on the CRL
_ this would appear to be a server 2019 CA bug!


https://techcommunity.microsoft.com/t5/azure-active-directory-identity/azure-ad-mailbag-windows-hello-for-business/ba-p/445349

**Comment by illfated** [comment]
@scyto : Thank you for reporting the issue. It should now be resolved by Pull Request #6363 by @joinimran .

**Comment by mypil** [comment]
@scyto - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/afe61ce140fa03edd18e2e8830d77928ad259a79. 



Thank you for your contribution to make the docs better! Much appreciated!
