### ISSUE TITLE
What is a BMP field and how does one set it?

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/windows-itpro-docs#6353]
I see the same guidance about BMP fields as here https://support.microsoft.com/en-us/help/291010/requirements-for-domain-controller-certificates-from-a-third-party-ca i can find no instructions on how to modify my windows 2019 CA templates to ensure this.  Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c47de28c-e44b-ca73-efde-fae303e0d3f8
* Version Independent ID: 71202a24-5b2f-844a-acce-d48c46873f2b
* Content: [Hybrid Key trust Windows Hello for Business Prerequisites (Windows Hello for Business) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by scyto** [comment]
I finally got this install working, i still don't know what a BMP field is - i can only assume a windows server 2019 CA does it? (but i can't see this parameter on the DC KDC cert anywhere)

Also please extend the Key Trust flow documentation to include full certificate instructions  of what the cert on a windows 2019 CA needs to be created (like you have in the Cert Trust flow).

**Comment by MaratMussabekov** [comment]
Hello @scyto ,
totally agree, this is pretty confusing,
there is no such thing as "BMP field"
**The certificate template must have an extension that has the BMP data value "DomainController"** - this means that the template must have an extension with value "DomainController"
![image](https://user-images.githubusercontent.com/48041687/78468375-e60d7a80-7730-11ea-98c7-13e5739ba1e9.png)
BMP just means here that it should be encoded as [BMPString](https://docs.microsoft.com/en-us/windows/win32/seccertenroll/about-bmpstring)

I will create a PR to make it more clear.
Thank you

**Comment by mypil** [comment]
@scyto  - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/f2f987dc5b4cf49d8d61e52605d6fca3f73439f5. 


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by adamcrosby** [comment]
@mypil This confusing/incorrect wording about 'BMPString' was fixed in that merged commit, but that merged commit is for a different file.  The https://learn.microsoft.com/en-US/troubleshoot/windows-server/windows-security/requirements-domain-controller URL still says 'Basic Metabolic Panel', which is obviously incorrect.
