### ISSUE TITLE
Please clarify what should be in the subject name field of the DC cert?

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/windows-itpro-docs#6358]
I had awful issues with windows event log saying there wasn't enough info in the subject name to find the DC.
Should the subject name be empty or should it contain something?

Mine only stopped giving these errors when the DC cert was installed in local computer \ other people \ certificates AND the subject field contained.

CN = WINSERVER01
OU = Domain Controllers
DC = &lt;redacted&gt;
DC = com

I am not sure which of these things stopped the errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c47de28c-e44b-ca73-efde-fae303e0d3f8
* Version Independent ID: 71202a24-5b2f-844a-acce-d48c46873f2b
* Content: [Hybrid Key trust Windows Hello for Business Prerequisites (Windows Hello for Business) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
Hello, @sycto

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by joinimran** [comment]
Hello @scyto - Thank you for your feedback on the document. Can you please confirm what information is required to be added in the document so that I can make necessary changes in the doc.

Thanks
Imran.

**Comment by e0i** [comment]
Feel free to re-open this issue with clarifications on the mentioned details and we'd be glad to come up with content updates.

Thank you for providing feedback.
