### ISSUE TITLE
Can the CRL path of the DC cert contain LDAP end points if using windows 10 AAD joined machines (not AD joined)

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/windows-itpro-docs#6359]
I had terrible issues with a CRL server offline error

a combination of removing the LDAP end points from the cert, using HTTP endpoint AND making sure the DC cert subject field was populated with a DN plus in the other people store finally fixed this.

It would be good to have clarification if the LDAP points would be inaccessible to non-AD joined device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c47de28c-e44b-ca73-efde-fae303e0d3f8
* Version Independent ID: 71202a24-5b2f-844a-acce-d48c46873f2b
* Content: [Hybrid Key trust Windows Hello for Business Prerequisites (Windows Hello for Business) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by scyto** [comment]
This clarification is important because in the cert guidelines for cert trust it says 'should' is this a should or must?

**Comment by e0i** [comment]
@scyto An independent contributor will follow-up with necessary clarifications. Thank you.

**Comment by MaratMussabekov** [comment]
Hello @scyto,
For sure, ldap cannot be used in the described scenario, as ldap is not accessible by non-AD joined machines.

**a combination of removing the LDAP end points from the cert, using HTTP endpoint AND making sure the DC cert subject field was populated with a DN plus in the other people store finally fixed this.** - from my experience, using HTTP endpoint and adding cert to trusted root store is enough, are you sure it didn't work without adding DN as a DC cert subject ?

**It would be good to have clarification if the LDAP points would be inaccessible to non-AD joined device.** - it is stated in the "important" section in the same part of the article:
_For Azure AD joined device to authenticate to and use on-premises resources, ensure you:
Install the root certificate authority certificate for your organization in the user's trusted root certificate store.
Publish your certificate revocation list **to a location that is available** to Azure AD joined devices, such as a web-based url._

Thank you
