### ISSUE TITLE
Typo: Prerequisites

### ISSUE THREAD

**Issue by deanellerby** [MicrosoftDocs/windows-itpro-docs#636]
1. Overview
2. Prerequistes (You are here) <- 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c47de28c-e44b-ca73-efde-fae303e0d3f8
* Version Independent ID: 71202a24-5b2f-844a-acce-d48c46873f2b
* Content: [Hybrid Key trust Windows Hello for Business Prerequistes (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md)
* Service: **unspecified**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by Justinha** [comment]
@deanellerby Thanks for reporting this. The corrections should appear later today.

**Comment by Justinha** [comment]
This is fixed at https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs
