### ISSUE TITLE
Please clarify if SSO to domain joined devices is supposed to work?

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/windows-itpro-docs#6361]
When i logged into a windows 10 machine with my WFHB credential (fingerprint, face, pin, or key) i could not access SMB shares on my domain controller or a domain joined NAS.

Is this supposed to work?

If i logon just with my AAD UPN it all works perfectly.

What is the right expectation for SSO?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c47de28c-e44b-ca73-efde-fae303e0d3f8
* Version Independent ID: 71202a24-5b2f-844a-acce-d48c46873f2b
* Content: [Hybrid Key trust Windows Hello for Business Prerequisites (Windows Hello for Business) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by scyto** [comment]
I can confirm this works perfectly in a perfect setup.
As such closing.
Will comment my other issues to provide feedback on what my issues were.

**Comment by illfated** [comment]
Thank you for the closing comment. Always good to know why a ticket gets closed.
