### ISSUE TITLE
Add flow for what happens after logon when accessing say an SMB share on a classic domain joined file server?

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/windows-itpro-docs#6362]
Could you show what the flow would be for someone once they have logged on with WHfB when they access a file server in the hybrid domain.

I.E someone logs on to a win10 AAD joined machine called win10.contoso.com with windows hello.  Then they put a UNC to \\server.contoso.com\share - this is a domain joined server in the same AAD connect domain. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10fcf686-1781-8a62-16bb-b26b3f5982fd
* Version Independent ID: 37d733ad-e809-1674-ffbc-ae3d0c495423
* Content: [How Windows Hello for Business works - Authentication - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-authentication)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-how-it-works-authentication.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-how-it-works-authentication.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by scyto** [comment]
i think this is what i wanted right? https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-authentication#azure-ad-join-authentication-to-active-directory-using-a-key ?

**Comment by matthewlshaw** [comment]
Connecting to SMB shares is disabled within Windows 10 Team, the OS on Surface Hub 2S. See: https://docs.microsoft.com/en-us/surface-hub/differences-between-surface-hub-and-windows-10-enterprise#security-and-lockdown -> Custom File Explorer only grants access to files and folders under My Documents.

**Comment by scyto** [comment]
I can verify the link in my post above is what i was looking for, though it could be clearer that is the scenario.

I actually used it to help me wire shark the issue and I found my win10 client was getting confused because it couldn;t check the CDP CRL path from for CRL two on windows CA (i.e. the path on the DC cert was fine, it was the  CRL path attribute on the CRL in the CDP that pointed the +.crl file that was wrong - due to a CA bug!

You can close this if you feel there is no need for clarification of when those flows apply.

**Comment by e0i** [comment]
@scyto Thank you again for digging further and even coming up with a solution! A contributor will provide a PR as suggested.

**Comment by VLG17** [comment]
@scyto Thank you for pursuing this further and finding the answer on your own. I don't think we should add when the flows apply, because in my opinion there is no way to cover each scenario that might come up. 

I think anyone looking into this should be able to understand in what scenario they are based on the WHfB authentication method described in the article.

**Comment by e0i** [comment]
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation.

Thank you, and stay healthy.
