### ISSUE TITLE
What exactly is needed to let standard users change clock?

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/windows-itpro-docs#6367]
I've defined a custom configuration profile for ./Vendor/MSFT/Policy/Config/UserRights/ChangeSystemTime with the data payload

&lt;![CDATA[Administrators&#xF000;LOCAL SERVICE&#xF000;Users]]&gt;

Although Intune reports a "-2016281112 (Remediation failed)" error on target devices, I see the assignments adjusted in the local group policies. However, standard users still cannot change the clock data and time. Even after reboot.

What else is missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b62d452-1910-d962-0ccc-9ac3f8135f15
* Version Independent ID: 5a4e6f0c-bcd4-8d8b-93f7-5bda7135b931
* Content: [Policy CSP - UserRights - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-userrights#userrights-changesystemtime)
* Content Source: [windows/client-management/mdm/policy-csp-userrights.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-userrights.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@icelava . According to below page, there are two types of policies, one for the user and one for the device.

**https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-configuration-service-provider#policy-scope**


User scope:

./User/Vendor/MSFT/Policy/Config/AreaName/PolicyName to configure the policy.
./User/Vendor/MSFT/Policy/Result/AreaName/PolicyName to get the result.
Device scope:

./Device/Vendor/MSFT/Policy/Config/AreaName/PolicyName to configure the policy.
./Device/Vendor/MSFT/Policy/Result/AreaName/PolicyName to get the result.


I am not a corporate  admin, so i don't have much knowledge in this regard

**Comment by icelava** [comment]
https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-configuration-service-provider

It's not necessary to use ./Device for device-wide configuration; ./Vendor is good enough. Mind you, the setting does get applied to the target computers' local group policy - I can see the Users group defined there. BUT, standard users still cannot change the clock in Date & Time settings.

**Comment by illfated** [comment]
@icelava : I do understand the usefulness of your question, but I also think it could be practical to ask in a MS technet community or similar user problem solving forum page.

Please note that the MicrosoftDocs issue tracker is mainly intended for documentation correction and improvement, so there is no guarantee that your question will be answered authoritatively here.

**Comment by e0i** [comment]
@icelava 

Please find the appropriate link to support channel for your question below

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by icelava** [comment]
> @icelava : I do understand the usefulness of your question, but I also think it could be practical to ask in a MS technet community or similar user problem solving forum page.
> 
> Please note that the MicrosoftDocs issue tracker is mainly intended for documentation correction and improvement, so there is no guarantee that your question will be answered authoritatively here.

I have asked separately before.
https://docs.microsoft.com/answers/questions/18841/standard-users-cannot-sync-clock-after-windows-aut.html?childToView=20401

**Comment by illfated** [comment]
Thank you for your update and the link to your question in the Q&A section.
I don't know your specific scenario, but could this have anything to do with the use of VM servers?
At my workplace, we used to have an annoying time offset on the server, which propagated to the domain clients, but my workplace is a small business with only 20-25 computers and a Windows Server 2016 domain controller. My solution was to implement a frequent (once every 12 hours) NTP update on the VM host server (the OS running directly on the hardware), because our VM gets its time from the HW part of the server. This stabilized our domain time sync a lot.

**Comment by icelava** [comment]
I'm not inclined to believe VMs have anything special that makes them "unwilling" to grant standard users the privilege to change system clock. There are others who are trying this in their own environments/hardware and it appears Windows does not return a proper response after the custom OMA-URI policy is applied, and Intune interprets that as failure. But they can't grant standard users the said privilege either.

**Comment by illfated** [comment]
Regretfully, I must admit that I don't know what should be done to attempt to solve your issue. I can only recommend asking the developers in the Technet forum pages:
- https://social.technet.microsoft.com/Forums/en-US/home

**Comment by scerazy** [comment]
This is an absolute RUBBISH!
User of the machine cannot change the time, how more silly that can get?
