### ISSUE TITLE
2003? 

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/windows-itpro-docs#6368]
Shouldn't the policies for this build soon be out? or might it have been moved?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19461768-ab73-b97c-f754-24e5c75e261f
* Version Independent ID: 58c7b616-f5c7-c503-a689-4fadde8ee061
* Content: [What's new in MDM enrollment and management - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/new-in-windows-mdm-enrollment-management#whats-new-in-mdm-for-windows-10-version-1909)
* Content Source: [windows/client-management/mdm/new-in-windows-mdm-enrollment-management.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/new-in-windows-mdm-enrollment-management.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@xNiklasJern . We are the normal users, so the decision will be from the Microsoft windows 10 designer policy team. The team might introduce new policies or remove existing policies or they might change some upgrades with existing policies.

**Comment by ManikaDhiman** [comment]
Hi @e0i, The [What’s new in MDM for Windows 10, version 2004](https://docs.microsoft.com/en-us/windows/client-management/mdm/new-in-windows-mdm-enrollment-management#whats-new-in-mdm-for-windows-10-version-2004) section lists the policies/nodes added/updated in Windows 10, version 2004. I hope it resolves the issue here.

**Comment by illfated** [comment]
@xNiklasJern : Seeing that the section **What’s new in MDM for Windows 10, version 2004** (as linked above) has been added to the page, I presume your question is answered (also that the version number is now 2004 instead of 2003, which was kind of an unresolved question 2 months back).

**Comment by e0i** [comment]
Closing as suggested. Thank you.
