### ISSUE TITLE
Diskpart CMD 

### ISSUE THREAD

**Issue by Maniano925** [MicrosoftDocs/windows-itpro-docs#637]
Followed the steps but when trying clean or clear disk partition I receive a error message 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4e47c9-b470-be67-acc3-6a763746b854
* Version Independent ID: fdfb6514-3340-54a2-7743-9ce46b91c5e3
* Content: [Windows 10 and Windows 10 Mobile (Windows 10)](https://docs.microsoft.com/en-us/windows/windows-10/#related-topics)
* Content Source: [windows/hub/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/hub/index.md)
* Service: **unspecified**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **brianlic**

**Comment by Justinha** [comment]
@Maniano925 Sorry you having trouble. Which topic were you following? You might also search on https://support.microsoft.com for troubleshooting info.

**Comment by andreabichsel** [comment]
Closing for now, appears to be a support issue.
