### ISSUE TITLE
Erreur de traduction sur "Set up a ring"

### ISSUE THREAD

**Issue by jacbar01** [MicrosoftDocs/windows-itpro-docs#6375]
Le titre de section "Set up a ring" a été mal traduit par la traduction automatique : "Configurer une sonnerie"... mauvais choix de traduction pour le mot "ring", alors qu'il est correctement traduit par "anneau" dans les paragraphes précédents.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: b2e692b1-8354-6b09-dfd7-252585320aac
* Version Independent ID: d1c99e74-66df-760a-39e9-23e5ed2bcfec
* Content: [Configurer Windows Update entreprise via une stratégie de groupe (Windows 10) - Windows Deployment](https://docs.microsoft.com/fr-fr/windows/deployment/update/waas-wufb-group-policy#feedback)
* Content Source: [windows/deployment/update/waas-wufb-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-wufb-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@TinaMcN can you help with this?

**Comment by mypil** [comment]
From Bing Translation: 
section title "Set up a ring" has been mistranslated by the machine translation: "Configure a ringtone" ... wrong translation choice for the word 'ring', while it is correctly translated as 'ring' in the previous paragraphs.

@tinamcn - Can you please assist with this Translation/Localization issue?

Thank you.

cc: @kenwith

**Comment by TinaMcN** [comment]
@jacbar01 merci d’avoir signalé ce problème.
@mypil thanks for evaluating the issue.
@OfficeGlobal please uplift this content to human translation.

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by mypil** [comment]
@OfficeGlobal - Do you have any updates on this? Is this issue already fixed?

Thank you!

**Comment by illfated** [comment]
Looks like the paragraph title is correct now, even in the direct link to the section: https://docs.microsoft.com/fr-fr/windows/deployment/update/waas-wufb-group-policy#configuration-dun-anneauset-up-a-ring

### Configuration d’un anneau

1. Démarrez la Console de gestion des stratégies de groupe (gpmc.msc).
2. Développez **Forêt > Domaines > *\<votre domaine>**.
3. Cliquez avec le bouton droit sur \<votre domaine>, puis sélectionnez Créer un objetGPO dans ce domaine, et le lier ici.
4. Dans la boîte de dialogue Nouvel objetGPO, entrez Windows Update pour Entreprise – Groupe1 en tant que nom du nouvel Objet de stratégie de groupe.
5. Cliquez avec le bouton droit sur l’objet «Windows Update pour Entreprise – Groupe1», puis sélectionnez sur Modifier.
6. Dans l’éditeur de gestion des stratégies de groupe, accédez à Configuration ordinateur > Stratégies > Modèles d’administration > Composants Windows > WindowsUpdate. Vous êtes désormais prêt à démarrer l’affectation de stratégies à cet anneau (groupe) d’appareils.

***
Looks like there are some formatting issues in the text, but that stems from the /en-us/ version of the page. I will open a PR to have those issues resolved in the /en-us/ page.

**Comment by mypil** [comment]
@jacbar01 - Thank you for submitting feedback.

From our understanding, the issue you raised has been resolved so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
