### ISSUE TITLE
Microsoft To-Do - WIP enlightened

### ISSUE THREAD

**Issue by bottsepp** [MicrosoftDocs/windows-itpro-docs#6376]
Hey docs team,

heads up: Microsoft To-Do for Windows 10 will be WIP enlightened starting with v2.16, which will start to roll out to public at April 20th.

Cheers,
Sebastian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ed0150-0172-f3ad-3c7f-3a7141efbe64
* Version Independent ID: 6a978d2b-a0ff-1052-ce00-06f02f30cfa1
* Content: [List of enlightened Microsoft apps for use with Windows Information Protection (WIP) (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
Closing via merged PR #8415 . Thank you.
