### ISSUE TITLE
Get-WindowsUpdateLog throws exception

### ISSUE THREAD

**Issue by amk07** [MicrosoftDocs/windows-itpro-docs#6377]
Get-WindowsUpdateLog throws a file not found exception
a) when the directory "c:\windows\logs\WindowsUpdate" is not present
b) when there is no etl file in the directory "c:\windows\logs\WindowsUpdate"

<img width="613" alt="updatelog error1" src="https://user-images.githubusercontent.com/29729300/78009886-50a06e00-735f-11ea-84cd-8905fcb49eb9.PNG">

Instead of throwing an exception, wouldn't it be better to show a friendly message that the folder or file is not present.

**Comment by mypil** [comment]
@amk07 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by RAJU2529** [comment]
@amk07 , Go to **"C:\windows\logs\WindowsUpdate" **   see .etl  files  are there or not.
If files are found, then you will not get error messages.
But files are not available, that's why you received error messages.

i would recommend you to the latest any of the windows updates after that recheck the commands .
make sure  you must enable windows everts collector service, enable windows log viewer.

**Comment by amk07** [comment]
> @amk07 - May we know which Microsoft document link you used in reference to this issue?
> Please share it with us so we can investigate further. Thank you.

https://docs.microsoft.com/en-us/powershell/module/windowsupdate/get-windowsupdatelog?view=win10-ps

**Comment by RAJU2529** [comment]
@amk07 . the same command i entered in Powershell. worked fine. here is the proof

![Capture03](https://user-images.githubusercontent.com/3296790/78274606-19cc8280-752e-11ea-979e-0ce297df21b2.JPG)

**Comment by amk07** [comment]
> @amk07 . the same command i entered in Powershell. worked fine. here is the proof
> 
> ![Capture03](https://user-images.githubusercontent.com/3296790/78274606-19cc8280-752e-11ea-979e-0ce297df21b2.JPG)

@RAJU2529 Looks like you didn't understand the issue. Kindly read the comment I posted in the issue. I had mentioned two conditions when the command let fails with an exception.

I know the command works well when there are etl files. 
Issue here is an exception is thrown when. 
a) when the directory "c:\windows\logs\WindowsUpdate" is not present
b) when there is no etl file in the directory "c:\windows\logs\WindowsUpdate"

**Comment by illfated** [comment]
@amk07 : I see what you are saying, so let me offer my views on this issue.
1. This error message looks somewhat more friendly to me than most general PowerShell error messages.
2. Even though I am not a real coder, I think this is more of a developer issue than a documentation issue. You may want to provide this feedback to the MS developers via the Feedback Hub
3. Maybe your feedback belongs to PowerShell, I don't know. I hope some of the MS Docs members can recommend where to post.

**Comment by illfated** [comment]
Please also note that PowerShell is developed with flexibility in mind, meaning that it is sometimes necessary to create PS1 scripts to add customized output, just as in ordinary coding (programming).

**Comment by mypil** [comment]
@amk07 - Thank you for submitting feedback.

This repository is intended for feedback on docs specific to Windows ITPro topics and the issue you opened is for MS windows-powershell-docs. You can submit your feedback by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page.

Alernatively, if you are having some technical concerns then you can also contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so your issue can get resolved ASAP.

Thank you for your contribution to make the docs better! We appreciate it!
