### ISSUE TITLE
Windows Hello vs Bitlocker vs Local account passwords

### ISSUE THREAD

**Issue by Kaos-Industries** [MicrosoftDocs/windows-itpro-docs#6380]
Two questions. 

Does Windows Hello utilise drive encryption, or is it simply backed up by the TPM in the same way that BitLocker is? 

What are the differences, if any, between a local account password and a Windows Hello pin?  From the descriptions on this page, they seem to sound the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c34dbafa-df3c-a5a5-32d5-2ce152893534
* Version Independent ID: cebdd9a6-45d7-6306-373c-7d31121f9e16
* Content: [Why a PIN is better than a password (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mapalko** [comment]
Windows Hello is a separate feature from device encryption. Both device encryption and Windows Hello use the TPM for hardware backed keys. This allows us to take advantage of the security properties of the TPM like anti-hammering. 

The Windows Hello PIN is a gesture to authorize a key in the TPM. If you have deployed WHFB or are using an MSA connected account for login, the PIN is used to authorize key based authentication to the IDP (AAD, AD, or MSA). 

The local account password is a local secret on the device. If you are using Windows Hello and you only have a local account, we will encrypt the password using the WHFB key. When you type in the PIN to login, this we will unencrypt the password and use it for login.

**Comment by RAJU2529** [comment]
@Kaos-industries. windows hello is a feature and uses dedicated fingerprint scanner to login purpose only. 
TPM is dedicated hardware  and uses for bitlocker encryption for Drives.
I seen laptops, without fingerprint scanner but they  laptop has embedded with TPM so in this case , users can not able to use windows Hello features.But users can able to bitlocker encryption.

**Comment by mapalko** [comment]
@RAJU2529 Windows Hello incorporates face and PIN in addition to fingerprint. The TPM is used in Windows for a lot of different features. For more information I recommend reading: https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/how-windows-uses-the-tpm 

Windows Hello will use the TPM when it is available to generate keys so it can have the same hardware guarantees as bitlocker. If a device does not have a fingerprint sensor, it can still provision a PIN and use the PIN to do key based authentication to MSA, AD, and AAD.

**Comment by RAJU2529** [comment]
@mapalko . Thanks  for the information.I read . That article contains lots of information. Article mainly focused to software application developer and OEM .  I am normal use, I will keep only few differences.  Earlier I replied to aser in simple way.

**Comment by mypil** [comment]
@Kaos-Industries @RAJU2529 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author-mapalko so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
