### ISSUE TITLE
Titan Security Key Support

### ISSUE THREAD

**Issue by benaltair** [MicrosoftDocs/windows-itpro-docs#6381]
Google Titan keys should be accepted, or an explanation should be provided. Why would you allow a pin or picture password but not a FIDO security key like Titan? It makes no sense from a security perspective and certainly not from the user's perspective.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aacf4c87-5c77-1d03-0c60-bc608fabe2f8
* Version Independent ID: 70d65968-6f5e-8013-0b0b-6d5d660969e0
* Content: [Microsoft-compatible security key - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/microsoft-compatible-security-key#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/microsoft-compatible-security-key.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/microsoft-compatible-security-key.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by beerisgood** [comment]
I vote more for Nitrokey which are trustworthy then the Google ones.

But supporting Fido keys in generally is a more then once already requesting feature

**Comment by mapalko** [comment]
For more information on logging into Windows with FIDO security keys, you should see the Azure documentation on the feature. This has an included list of compatible keys that have implemented the set of functionality listed to be compatible with Windows sign in.

https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-authentication-passwordless#fido2-security-keys

**Comment by beerisgood** [comment]
@mapalko but why is this only on azure doc instead of doc for normal windows usage?
No windows enduser use azure.

**Comment by sulljc** [comment]
I second this post.  Why are Titan keys no longer supported?

**Comment by e0i** [comment]
The issues section of this repository is for article defects. 

Please ask this question via the [Microsoft with the Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app).

Thank you.
