### ISSUE TITLE
&#61440; ?

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/windows-itpro-docs#6384]
What is character 0x61440? Why is it used in the examples instead of &#xF000; ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b62d452-1910-d962-0ccc-9ac3f8135f15
* Version Independent ID: 5a4e6f0c-bcd4-8d8b-93f7-5bda7135b931
* Content: [Policy CSP - UserRights - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-userrights#userrights-changesystemtime)
* Content Source: [windows/client-management/mdm/policy-csp-userrights.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-userrights.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
- http://www.fileformat.info/info/unicode/char/61440/index.htm

(just to copy-paste some info from the web page -- I am not an expert in this field)

**U+61440 is not a valid unicode character.**

| Encodings | |
| -------------------------------- | ----------------------------------- |
| HTML Entity (decimal)	| &#398400;|                          |
| HTML Entity (hex)	| &#x61440;|                          |
| How to type in Microsoft Windows	| Alt +61440|                         |
| UTF-8 (hex)	| 0xF1 0xA1 0x91 0x80 (f1a19180)|     |
| UTF-8 (binary)	| 11110001:10100001:10010001:10000000 |
| UTF-16 (hex)	| 0xD945 0xDC40 (d945dc40)|           |
| UTF-16 (decimal)	| 55 621 56 384|                      |
| UTF-32 (hex)	| 0x00061440 (61440)|                 |
| UTF-32 (decimal)	| 398 400|                            |
| C/C++/Java source code	| "\uD945\uDC40"|                     |
| Python source code	| u"\U00061440"|                      |

**Comment by icelava** [comment]
So visually it looks similar to 0xF000, but I guess they're still different. Why does this page so casually use that character in samples?

**Comment by illfated** [comment]
> So visually it looks similar to 0xF000, but I guess they're still different. Why does this page so casually use that character in samples?


Beats me, wish I knew. Sometimes, the reasons why authors choose the things they do to put in their writings elude me completely, even if I read the text many more times than necessary.

**Comment by e0i** [comment]
@ManikaDhiman Could the character `&#61440` ended up within the examples by mistake?

**Comment by ManikaDhiman** [comment]
Hi @e0i, I updated the examples to use `&#xF000;` instead of `&#61440;`. I hope this helps. Thanks!

**Comment by illfated** [comment]
#please-close

**Comment by schenardie** [comment]
&#61440; is the decimal representation of the HTML character encoding while &#xf000; is the hex.

They should both work.
https://www.fileformat.info/info/unicode/char/f000/index.htm

I found that if you decode the string via https://coderstoolbox.net/string/#!encoding=xml&action=decode&charset=us_ascii and paste into the custom policy it works without the CDATA 
just as in 

Administrators&#61440;(decoded which will be that funny box on the browser)Users

The problem is i cant import that programatically via Graph API.

Can someone help with that? (how should i represent this character inside JSON that when i import it will decode correctly
