### ISSUE TITLE
Issue with Windows Hello PIN login after change password from Domain Controller and requires two attempts to login with Updated pasword 

### ISSUE THREAD

**Issue by dockervenkat** [MicrosoftDocs/windows-itpro-docs#6385]
Issue after change password from Domain Controller

After Changing the password from Domain Controller/ Server. The it requires twice online login with the new updated password for the Subsequent PIN  functionality to work.

Steps to replicate the issue.

Prerequisite:
Windows Server 2019 Enterprise

Windows 10 x64 bit-1909 Enterprise

Steps:
1&gt; Change password for a domain user XX In server
2&gt;Client is connected to domain and enabled for Windows Hello using PIN

3&gt;Login as user XX with the new updated password, Login is successful

4&gt;Now again login with PIN

Error message is show as "You must sign in to this device …."

Inference:
Even after logged in with New password, Windows will not allow subsequent PIN login.

Workaround:
Users again need to login twice with the updated password to use the functionality of PIN

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba665984-14d2-e5f1-a1a4-e8c28b61571d
* Version Independent ID: 4918b293-ce78-154b-a3ee-515557367d8c
* Content: [Windows Hello and password changes (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-and-password-changes#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-and-password-changes.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-and-password-changes.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by dockervenkat** [comment]
We need to fix this issue as Windows Hello PIN is also used by many customers and it needs two attempts to login with the updated password and until then PIN functionality cannot be used.

**Comment by RAJU2529** [comment]
@dockervenkat . Will you try to change the PIN  policy settings in GPO, see it works

**Comment by mapalko** [comment]
@dockervenkat documentation feedback shouldn't be used for opening code issues or bugs. Please follow up through feedback hub and collect a repro of the issue that you are experiencing.
