### ISSUE TITLE
Network\Network Connections\Ability to Enable/Disable a LAN connection

### ISSUE THREAD

**Issue by badsector-82** [MicrosoftDocs/windows-itpro-docs#6386]
Hello. In this document I see that new policies in windows 10 version 1703 include the option to Network\Network Connections\Ability to Enable/Disable a LAN connection. But when I open group policy editor and open this option, it says to be applicable only to Win XP, Server 2003 and Win 2000. What am I doing wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c3e60ec-cf61-c34b-db79-74b13e3ee867
* Version Independent ID: fc5079f7-a563-c627-3a3e-eb84a99e4fd3
* Content: [New policies for Windows 10 (Windows 10) - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/new-policies-for-windows-10)
* Content Source: [windows/client-management/new-policies-for-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/new-policies-for-windows-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@badsector-82 . try to enable or disable policy.and see what happens

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
