### ISSUE TITLE
Drivers updates

### ISSUE THREAD

**Issue by MaratMussabekov** [MicrosoftDocs/windows-itpro-docs#6387]
It states "Drivers (on/off): When "on," this policy will not include drivers with Windows Update."
it looks illogically, shouldn't it be "When "on," this policy will include drivers with Windows Update."?
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2056993d-a700-fba6-8982-e645b182eeea
* Version Independent ID: fb38a86a-cdf6-6fc2-8eb6-fd54f1599f55
* Content: [Deploy updates using Windows Update for Business (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-manage-updates-wufb)
* Content Source: [windows/deployment/update/waas-manage-updates-wufb.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-manage-updates-wufb.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Your observation seems logical. @arcarley can you confirm?

**Comment by arcarley** [comment]
Apologies, the full policy is Disable Drivers. So On actually turns Off drivers (I do concur with you that the policy is confusing). I will update the documentation to reflect such and attempt to clarify! :)

**Comment by e0i** [comment]
Closing via *arcarley*'s commit, [[3ca714c ] Update waas-manage-updates-wufb.md ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/3ca714c8c65fdcec4afd3c2f8fb0b735b0b77202#diff-8c2d55a36926f46a51d9b40832ba0086)

**Comment by illfated** [comment]
(comment copy edited for future readers to assist in previewing the link information directly on this page + linking directly to the repository file)
> Closing via _arcarley_'s commit, https://github.com/MicrosoftDocs/windows-itpro-docs/commit/3ca714c8c65fdcec4afd3c2f8fb0b735b0b77202 / [Update waas-manage-updates-wufb.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-manage-updates-wufb.md)

(only 1 file is present in the commit, so I see no practical use for the #diff link to highlight that single file)
