### ISSUE TITLE
Office 365 Business Desktop

### ISSUE THREAD

**Issue by ruairidhlc** [MicrosoftDocs/windows-itpro-docs#6388]
The documentation advises:
"You must use the O365 ProPlus - Allow and Exempt AppLocker policy files (.zip files) to turn the suite on for WIP.  We don't recommend setting up Office by using individual paths or publisher rules."
Do these XML files apply to the Office 365 Business apps or only the Office 365 ProPlus apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ed0150-0172-f3ad-3c7f-3a7141efbe64
* Version Independent ID: 6a978d2b-a0ff-1052-ce00-06f02f30cfa1
* Content: [List of enlightened Microsoft apps for use with Windows Information Protection (WIP) (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
@ruairidhlc - Thank you for your query, Please note that these XML files applies to Office365 ProPlus and Office2019 application suites. Please go through the Readme file included in the downloaded Zip file for details. 

Thanks
Imran

@e0i FYI Please.

**Comment by ruairidhlc** [comment]
Hey @joinimran thanks for the info, I thought that was the case.  It would make sense for the Business versions to be included as they're offered in M365 Business, and customers of that are licensed for Intune and WIP.

**Comment by joinimran** [comment]
@ruairidhlc  - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://office365.uservoice.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

@e0i FYI Please.
