### ISSUE TITLE
Difference between "Stop and Quarantine" vs "Block File"

### ISSUE THREAD

**Issue by brink668** [MicrosoftDocs/windows-itpro-docs#6389]
We need improved documentation on the differences between "Stop and Quarantine" vs "Block File".  In addition, is there any way to temporarily "ban" a hash/file without Windows ATP Defender from deleting all the corresponding files with it?  There are times when we may ban a hash temporarily but then allow it later on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d99de0-789d-3c71-4bd9-f45e62f82a7b
* Version Independent ID: d56d09f0-1f9a-563e-fee0-142bda27a99b
* Content: [Configure advanced features in Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/advanced-features#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/advanced-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/advanced-features.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by joinimran** [comment]
@brink668 - Thank you for your query. Let me see if I can help you to explain this for you.

For Stop and Quarantine, the potential file's executed process stops working and the system doesn't allow any future execution and place that file in quartine from where on-wards you can continue to investigate the file and if you think that there is a false positive you can release the file from quartine. While in block file, it completely blocks the file and its process execution. See more details at https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/respond-file-alerts

You can add indicator for the hash file block. Please see the details at https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/respond-file-alerts#enable-the-block-file-feature

Hope this will help.

Thanks.
Imran.
