### ISSUE TITLE
Hi, this is 2018 and I use AAD and Windows 10 on prem clients

### ISSUE THREAD

**Issue by heschelpop** [MicrosoftDocs/windows-itpro-docs#639]
how about documentation written specifically for this use case - not updated from context that is not updatable to this use case

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 744990d3-6fb4-a085-de18-b0894c2dbda5
* Version Independent ID: f774568c-506c-cc5f-f6b2-2452cb408667
* Content: [Network security LAN Manager authentication level (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-lan-manager-authentication-level)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-security-lan-manager-authentication-level.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/network-security-lan-manager-authentication-level.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@heschelpop Thanks for the feedback. Can you provide any more detail about what you want to see documented? Any specific questions you want answered?

**Comment by heschelpop** [comment]
Justin,

Here is the thing I figured out after much soul crushing and looking through discussion threads on tech net that went no where, or as I like to call them, Microsoft road kill.  And I say this with much love – I am a Microsoft fan and super user since Windows 286 and I generally think office365 is revolutionary – and Power BI is also an amazing advance that I like a lot.

So, here is the deal – and I speak not from the large enterprise with many well paid consultants and internal it staff not to mention Microsoft support people, but the small business who is likely to actually get way more value from o365 than an enterprise – certainly can adopt the cutting edge stuff more quickly.  Which brings me to the AAD join.

Most small businesses might have the following use case:

They install windows, it creates the non-sequitir decive name Destop-409RTG.  They join that device to AAD.  This device is intended to be connected to remotely.  Heres the rub: then they change the device name to say ACME-REMOTE1.  currently, that change doesn’t roll up to AAD, so when you have NLA enabled on the remote machine, AAD still knows the previous name, the name that existed when you joined it.

The fix is so simple, that the average person who knows enough to be dangerous will be flummoxed because the concept of NLA is awesome and pretty much makes a machine inpenetrable even if its open on the internet – but when you try to connect it doesn’t work and you curse Microsoft as thought it was the dark days of Windows Vista.

However, it was all because you changed the name of the machine after you joined the machine to AAD.  The resolution is amazingly easy – and this would save so much pain that if you could harness it, it would light up a small town.  You either


  1.  Change your device name to what you want before you join to AAD
  2.  If you didn’t do a, but changed after, then you need to
     *   Unjoin the machine from AAD
     *   Go to the AAD admin portal -> devices and delete the machine from the list
     *   Rejoin the machine with the new name and you will see it appear in the AAD admin device list
Problem solved.

________________________________

**Comment by Justinha** [comment]
@heschelpop thanks for sharing this, I wasn't aware if it. Good news it looks like a fix is planned: https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/12980892-machine-rename-azure-ad 
I'll see where we can we publish this info in the interim.

**Comment by heschelpop** [comment]
Ok March 2016 was the comment date. Maybe the team needs reminding?
________________________________

**Comment by heschelpop** [comment]
Gotcha
________________________________
