### ISSUE TITLE
Two "and" words 

### ISSUE THREAD

**Issue by mattwailes** [MicrosoftDocs/windows-itpro-docs#6391]
And listed twice on this sentence.  

(Real time protection and and threats are not remediated by Windows Defender Antivirus.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b88aee4-6727-fa98-1180-29708eea027e
* Version Independent ID: 374c671b-b21c-6eac-d887-892491357eb2
* Content: [Windows Defender Antivirus compatibility with other security products - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-compatibility#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-compatibility.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-compatibility.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
Thanks. I will make the necessary adjustments.
