### ISSUE TITLE
Intune

### ISSUE THREAD

**Issue by ThomasKur** [MicrosoftDocs/windows-itpro-docs#6395]
On this page it's written how the ASR rules are named in Intune and ConfigMgr. But a few of The ASR which have a Intune name assigned are not available in the Intune Portal. For example the following are not available in the Endpoint Protection Profile:
- Block persistence through WMI event subscription
- Block Adobe Reader from creating child processes

When are they available in Intune? Otherwise perhaps remove the name on this page so that customers are not misled to think that they are available in Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6fd4c46-8ba2-4a67-47bb-8fe1b9064b11
* Version Independent ID: ca04d6c8-6943-4b7f-dd59-521b4511d3d5
* Content: [Use attack surface reduction rules to prevent malware infection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by AlphaSeb** [comment]
This is still open.

Block Adobe Reader from creating child processes <is available
Block persistence through WMI event subscription <is missing

**Comment by e0i** [comment]
@AlphaSeb Sending this over to an independent contributor for investigation. Thank you for following up.

**Comment by MaratMussabekov** [comment]
Dear @ThomasKur ,
the option "block persistence through wmi event subscription" is not available (or not available yet) in Intune. I created a PR to fix this in the article.
You can enable this rule using PowerShell or GPO.
Thank you

**Comment by ThomasKur** [comment]
Thanks for the update.

**Comment by denisebmsft** [comment]
Hello, all. I've merged the pull request that @MaratMussabekov opened. Changes will render live on the site tomorrow, about mid-day. Thank you @MaratMussabekov and others for your help!
