### ISSUE TITLE
Something Went Wrong; Username belongs to another Org

### ISSUE THREAD

**Issue by benrfinn** [MicrosoftDocs/windows-itpro-docs#6399]
Hi,

We are trying to deploy Intune/AAD company wide and are we reset laptops and try to connect to AAD we keep getting this response after entering the credentials "That username looks like it belongs to another organization. Try signing in again or start over with a different account". Can you please advise on this? It doesnt happen on every computer and we know some of the computers have not been connected to a test environment. It is driving us insane. What can we do??

**Comment by denisebmsft** [comment]
Hello @benrfinn and thank you for the feedback. To which article does this apply? This will help us route the issue correctly.

**Comment by benrfinn** [comment]
I am not sure exactly. I saw someone had a similar question here and he seemed to get his answer in Private Messages or something. This is the other question. 
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5692
Please advise.

**Comment by DecimalZero** [comment]
I'm having the same issue. What was the fix?

**Comment by illfated** [comment]
From ticket #5692 :

> * Content: [Windows Autopilot for existing devices - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/existing-devices#feedback)
> * Content Source: [windows/deployment/windows-autopilot/existing-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/existing-devices.md)
> * Product: **w10**
> * Technology: **windows**

**Comment by benrfinn** [comment]
Hi @illfated thank you for the link but it is not relevant in the case of this ticket (at least for me). @DecimalZero I opened a ticket with MS and so far they haven't done much. They seem confused so they are using delay tactics at the moment. I'll update this ticket if anything happens. Sorry for the bad news.

**Comment by illfated** [comment]
When @schenardie found a solution to their problem in the other ticket, I can only guess that it was some kind of user error. Otherwise, it would be quite useful to hear about it.

**Comment by schenardie** [comment]
@illfated Is correct in my case it was an error when i was importing the offline profile for autopilot. 
Are you too using offline profile or its just a clean install without anything??? 
I'd make sure the device is not already registered to another company.  also right before login do the shift f10 and check the following keys to see if they have any information and if its correct
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Provisioning\Diagnostics\AutoPilot

hope that helps

**Comment by illfated** [comment]
@benrfinn , @DecimalZero : Any help to be found in the comment above?

**Comment by benrfinn** [comment]
@schenardie You are a brilliant beautiful person. Thank you so much! I was able to find the tenant it belongs to and hopefully we can get it removed. This was the key that can fix a lot of things. Thank you so much!
@illfated yes lol

**Comment by illfated** [comment]
Very good indeed. So, before we move on to closing the ticket, have we learned anything which should be part of the documentation somewhere, to help avoid the same issue happening to other admins?

**Comment by benrfinn** [comment]
I think in relation to that error, which does not have an error code, but does show up in the specific circumstance:
When you are trying to connect a computer with Intune Autopilot and it states "That username looks like it belongs to another organization. Try signing in again or start over with a different account" then you should check the registry at HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Provisioning\Diagnostics\AutoPilot.
Only known resolution at that point is to contact the tenant listed and get the device removed from their tenant.

**Comment by illfated** [comment]
Thank you for the detailed reply. I hope we can find somewhere to add that as part of troubleshooting this topic in the documentation.

@e0i : Maybe someone in the tech writing team could read through this information and see if it can be added to any troubleshooting part of the documentation.

**Comment by schenardie** [comment]
Glad i could help Ben.

I see this being a real issue in the future as people start getting refurbished devices and companies sell older devices to other people or companies. Had some chats with Program Managers and they said the process of getting Microsoft to remove the information from an older tenant is ugly as the person needs to proof they actually own the device and sometimes when you buy a decommd laptop from a company they wont exactly give you a valid tax receipt.

**Comment by benrfinn** [comment]
That's exactly what happened to me. I am located in Myanmar and we were lucky we had the receipt but it didn't have the SSN on it so the receipt was rejected. 

The biggest problem was I gave them a list of domains we owned including testkoekoetech.onmicrosoft.com. I had tested some laptops in a that domain and it was supposed to have been spun down after. It wasn't, but all my access was revoked somehow despite my account still being registered as the admin. 

It turns out that is the domain registered in the registry is testkoekoetech.onmicrosoft.com. Before having this proof the Microsoft help team said we don't own the domain it was registered in which means they don't have enough clear visibility into what domain it belongs to. Lets see what happens now.

Going forward my team will check this registry item before purchasing a used laptop.

**Comment by DecimalZero** [comment]
This is good information, unfortunately, I am using a new laptop that was joined to our dev environment to test the Microsoft Endpoint Manager Autopilot. Dev was successful. Microsoft blew the dev environment away, my 90 days is up. I have no way to remove the laptop from the dev environment so I can have it joined to our production environment. I am going to need someone from Microsoft to help me. **sigh** 

Since our production environment is a hybrid, I am working to finish the Exchange migration so we can remove the AD Connector and update the source authentication to Azure AD, verses using Windows Server AD. Maybe that will help with enrolling the 40 new laptops we have. Fun times. :)

**Comment by e0i** [comment]
>  I'd make sure the device is not already registered to another company. also right before login do the shift f10 and check the following keys to see if they have any information and if its correct

A PR is underway to incorporate this information in the article. Thank you everyone for productive discussion. Much appreciated.

**Comment by joinimran** [comment]
Interestingly the discussed registry path is already mentioned in the troubleshooting document. Please see https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/troubleshooting#windows-10-version-1709-and-above

What I am going to do is to add this specific error information in known issues https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/known-issues and point it the registry path to set this up. hope this will make sense.

**Comment by e0i** [comment]
Closing via #6801

**Comment by B3atP0P** [comment]
Hello - i know this thread goes back a few years but i'm hoping to meet a couple of like minded techs that find these challenges stuff fun. withing reason of course. for a few days ive been getting this 'Something Went Wrong; Username belongs to another Org ... " error on a simple re-install of an OS on a two year old Dell laptop. plenty stong and capable - i just wanted this device to be compliant on my network. anyway, i've tried all sorts of things - reinstalls, oobe, ... - still nothing. if someone is still out there that might have some ideas - please contact me. Thank You.
