### ISSUE TITLE
wrong api example

### ISSUE THREAD

**Issue by BorisKornienko** [MicrosoftDocs/windows-itpro-docs#6402]
NOW
GET https://api.securitycenter.windows.com/api/1e5bc9d7e413ddd7902c2932e418702b84d0cc07/logonusers

MUST BE
GET https://api.securitycenter.windows.com/api/**machines/**1e5bc9d7e413ddd7902c2932e418702b84d0cc07/logonusers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90766224-2329-e33e-d213-77151572db46
* Version Independent ID: e950db47-84a4-99d5-0047-476572578d66
* Content: [Get machine log on users API - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/get-machine-log-on-users?source=docs#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/get-machine-log-on-users.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/get-machine-log-on-users.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Looks plausible, based on the content on the page, listing the following local command if you are running a local HTTP server:
```
GET /api/machines/{id}/logonusers
```
So if this is the blueprint for the FQDN address, it should be a very simple edit to make the necessary change.

**Comment by e0i** [comment]
@BorisKornienko An independent contributor is going to revise the article as per your suggestion. Thank you for the heads up.

**Comment by e0i** [comment]
Closing via #6720
