### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by JavkhlanK** [MicrosoftDocs/windows-itpro-docs#6403]
At #disk-conversion-workflow metadata is spelled wrong: metatdata

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73c22f0-cb0d-e34b-29d8-06829b86784f
* Version Independent ID: 083115ed-f1be-e962-5b0e-5079dec37353
* Content: [MBR2GPT - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/mbr-to-gpt#disk-conversion-workflow)
* Content Source: [windows/deployment/mbr-to-gpt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/mbr-to-gpt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@illfated . Please review this PR if you have free time. Thanks

**Comment by RAJU2529** [comment]
@denisebmsft .Sir i need  some help for configuring windows defender policy  by using ConfigSecurityPolicy.xml file .
But i could not able to create new  xml  nor got the file. So help to me .
here is the site i have already posted the question.

**https://answers.microsoft.com/en-us/windows/forum/all/i-received-error-code-0xc00ce225-when-i-entered/9503a0b4-1143-4578-a563-a83649bfed10**

**Comment by e0i** [comment]
Typo fixed via #6404. Thank you.
