### ISSUE TITLE
How can I make my domain-joined Windows 10 Enterprise x64 1903 and newer MFA at Windows login?

### ISSUE THREAD

**Issue by pmkochie** [MicrosoftDocs/windows-itpro-docs#6408]
I've been trying to figure out where to get the "Multifactor Authentication Server" It seems like it is no longer available from Microsoft for on-premise but when you try to install it in azure you need a premium azure account. But we have MFA for Azure working so it is very confusing. How can I make my domain-joined Windows 10 Enterprise x64 1903 and newer MFA at Windows login?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3b8524-491d-7f49-0445-a34ed47d504c
* Version Independent ID: 1106b56a-45f9-9465-7c7c-2fa9a68ca807
* Content: [Windows Hello for Business Deployment Guide - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-guide#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-deployment-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-deployment-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by MaratMussabekov** [comment]
Hello @pmkochie,
correct, MFA Server [is no longer available](https://docs.microsoft.com/azure/active-directory/authentication/howto-mfaserver-windows)
**How can I make my domain-joined Windows 10 Enterprise x64 1903 and newer MFA at Windows login?** - To secure Windows login, you now need to use Windows Hello for Business.
**when you try to install it in azure you need a premium azure account** - could you please provide more details? which service did you try to install? Are you talking about azure ad premium subscription?
Thank you

**Comment by mypil** [comment]
@pmkochie - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @MaratMussabekov so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
