### ISSUE TITLE
should add extra commands 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#6422]
Already @illfated replied on 29th no 2019 with the lists of relative links to windows defender Powershell cmdlets.
I would to like add all the links to the main article under the Reference links section.
I need feedback or opinion from the authors,I will create  PR after the reply from the authors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f5f37f-9e03-eac1-715b-4a01acfff33e
* Version Independent ID: b7e76481-3859-c8d1-c22d-ee238fadd1e9
* Content: [Use PowerShell cmdlets to configure and run Windows Defender AV - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/use-powershell-cmdlets-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/use-powershell-cmdlets-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/use-powershell-cmdlets-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@RAJU2529 and @mypil, please feel free to add the links as suggested at the top. I think that would be helpful. Thanks!

**Comment by e0i** [comment]
@denisebmsft FYI Joyce has retired from the program. I am including this into the backlog to be sent to an independent contributor. Thank you.

**Comment by denisebmsft** [comment]
Thank you @e0i

**Comment by joinimran** [comment]
@RAJU2529 - Can you please share me the link where ill-fated share his feedback.

**Comment by illfated** [comment]
@joinimran : I think he is referring to my comment in the closed issue ticket **Broken link** #5548 :

From https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5548#issuecomment-559586392
> The redirect link on https://docs.microsoft.com/en-us/powershell/windows/get-started is also broken.
> 
> There is a link named "defender" in the dynamic tree index on the left side of the page, but it only returns the same **404 - Page not found** error:
> 
> * https://docs.microsoft.com/en-us/powershell/module/defender/
> 
> There are working PowerShell cmdlet links, but none of them are written to be a general overview page with links to the other cmdlets.
> 
> The following cmdlet links work as intended, but without any obvious content summarizing page:
> 
> 1. https://docs.microsoft.com/en-us/powershell/module/defender/add-mppreference
> 2. https://docs.microsoft.com/en-us/powershell/module/defender/get-mpcomputerstatus
> 3. https://docs.microsoft.com/en-us/powershell/module/defender/get-mppreference
> 4. https://docs.microsoft.com/en-us/powershell/module/defender/get-mpthreat
> 5. https://docs.microsoft.com/en-us/powershell/module/defender/get-mpthreatcatalog
> 6. https://docs.microsoft.com/en-us/powershell/module/defender/get-mpthreatdetection
> 7. https://docs.microsoft.com/en-us/powershell/module/defender/remove-mppreference
> 8. https://docs.microsoft.com/en-us/powershell/module/defender/remove-mpthreat
> 9. https://docs.microsoft.com/en-us/powershell/module/defender/set-mppreference
> 10. https://docs.microsoft.com/en-us/powershell/module/defender/start-mpscan
> 11. https://docs.microsoft.com/en-us/powershell/module/defender/start-mpwdoscan
> 12. https://docs.microsoft.com/en-us/powershell/module/defender/update-mpsignature
> 
> edit: You may want to save a personal bookmark for the page https://docs.microsoft.com/en-us/powershell/module/?view=win10-ps **PowerShell Module Browser**, although that page does not have any feedback reporting feature like the regular doc articles have. Anyway, it would be nice to hear from the document author, @denisebmsft , if there are any plans to create the Defender PowerShell script cmdlet overview page, or if this improvement needs involvement from the community.

There is also [a follow-up comment I made](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5548#issuecomment-576780815) in the same ticket:
> Yes, thank you. The redirect is working as intended and expected now:
> 
> > For a list of the cmdlets and their functions and available parameters, see the [Defender cmdlets](https://technet.microsoft.com/library/dn433280.aspx) topic.
> 
> (https://technet.microsoft.com/library/dn433280.aspx redirects to https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/use-powershell-cmdlets-windows-defender-antivirus as you said.)
> 
> I think we can ask for this issue to be closed now.

**Comment by RAJU2529** [comment]
@joinimran .  just now @illfated listed all the links  here. So please go through his links.

**Comment by illfated** [comment]
As previously mentioned, https://docs.microsoft.com/en-us/powershell/module/defender/?view=win10-ps seems to be a good place to start.

**Comment by e0i** [comment]
Closing via #7944
