### ISSUE TITLE
Wildcard Clarification

### ISSUE THREAD

**Issue by EnviableOne** [MicrosoftDocs/windows-itpro-docs#6424]
does "A single asterisk (*) can be used anywhere in the string as a wildcard character."
mean this represents a single character or any string of characters.
i.e. could you use this to denote a domain by wilcard?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e6d018-78bd-c673-c970-d4a8c0c68fbf
* Version Independent ID: 3e1a9015-6d27-f117-0eca-bde9a8337a3d
* Content: [Network security Restrict NTLM Add remote server exceptions for NTLM authentication (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-restrict-ntlm-add-remote-server-exceptions-for-ntlm-authentication#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-security-restrict-ntlm-add-remote-server-exceptions-for-ntlm-authentication.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-security-restrict-ntlm-add-remote-server-exceptions-for-ntlm-authentication.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @EnviableOne ,
**mean this represents a single character or any string of characters.** - this means string
**i.e. could you use this to denote a domain by wilcard?** - yes, if you have format like test.contoso.com, you can denote domain like test.*
Thank you

**Comment by illfated** [comment]
Just to be more specific, you can also opt to replace the host names with the wildcard character, e.g. `*.contoso.com` if many of hosts in your list are in the same domain.

**Comment by mypil** [comment]
@EnviableOne - Thank you for submitting feedback.

From our understanding, the issue you raised have been answered by @MaratMussabekov & @illfated so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Comment by AndrewPMI** [comment]
Worth noting that a bare wildcard "*" here on a line alone represents an exception for a **NULL** SPN, not "all SPNs". Some legacy apps which use SSPI don't populate the SPN field (and thus will always fall back to NTLM), but can be permitted with a wildcard entry here. This still permits constraining outbound NTLM usage for other tools like the SMB client, web browsers, RDP client, etc. that always provide SPN data.

Less secure than ideal, but a useful tool in the fight against NTLM usage while keeping legacy apps running. Seeing the policy extended to allow NULL SPNs _only from specific binary paths_ would be even better and allow tightening the screws further.
