### ISSUE TITLE
How does this related to the user specific setting, 'this account supports AES 256 bit encryption'

### ISSUE THREAD

**Issue by CXMelga** [MicrosoftDocs/windows-itpro-docs#6429]
Hello
Can you please clear you the following confusion for me with regards to Windows 2019 Server (AD DS) and this post plus 
user specific setting, 'this account supports AES 256 bit encryption'

If I setup a new domain all defaults and create a new user all defaults (apart from the password), when I logon I get AES 265 encrypted Kerberos tickets. Even though the 'this account supports AES 256 bit encryption' account option is Not selected for the user.
The same happens if I create a KeyTab take it to a Linux server and authenticate against AD I again get an AES encrypted ticket
Therefore on the surface of this the setting 'this account supports AES 256 bit encryption' would appear to be obsolete and of no use in Windows 2019, therefore why it is still there, what am I missing?

Thanks very much in advance
CXMelga

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d05d447-1cc1-1eeb-3c4d-74591874f4e1
* Version Independent ID: 020b4d09-5ce9-e636-0545-1ce27029a921
* Content: [Network security Configure encryption types allowed for Kerberos - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@CXMelga Although not an official MS article, [this blog](https://www.harmj0y.net/blog/redteaming/kerberoasting-revisited/) describes the behaviour quite well.

> According to [Microsoft’s [MS-ADA2]](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-ada2/a75d1c3f-0bb3-470c-99bd-2bb557119483?redirectedfrom=MSDN), “The Key Distribution Center (KDC) uses this information [msDS-SupportedEncryptionTypes] while generating a service ticket for this account.” So even if a domain supports AES encryption (i.e. domain functional 2008 and above) **the value of the msDS-SupportedEncryptionTypes field on the account with the requested SPN registered is what determines the encryption level for the service ticket returned in the Kerberoasting process.**

According to MS-KILE 3.1.1.5 the default value for this field is 0x1C (RC4_HMAC_MD5 | AES128_CTS_HMAC_SHA1_96 | AES256_CTS_HMAC_SHA1_96 = 28) for Windows 7+ and Server 2008R2+. **This is why service tickets for machines nearly always use AES256, as the highest mutually supported encryption type will be used in a Kerberos ticket exchange**

This is where the answer to your question lies:

> If we select “This account supports AES [128/256] bit encryption” in Active Directory Users and Computers, then the msDS-SupportedEncryptionTypes is set to 24, specifying **only** AES 128/256 encryption should be supported.

If you don't specify this explicitely, although in your example you still get AES 265 encrypted Kerberos tickets, this does not exclude the posibility of getting lower encryption grade tickets. If you want to be 100% sure this does not happen, you need to select that checkmark.

**Comment by nam31** [comment]
@CXMelga Please let us know if you still have any question regarding the issue you have raised initially.

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
