### ISSUE TITLE
Linux support is in preview

### ISSUE THREAD

**Issue by memildin** [MicrosoftDocs/windows-itpro-docs#6430]
This page doesn't mention that the Linux support is only currently preview - not GA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
@memildin : Would you be able to provide a link or source, just to be sure, before making this change? (I am not affiliated with Microsoft, at least not yet.)

**Comment by MaratMussabekov** [comment]
Hello @illfated,
it is stated [here](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-linux)
Thank you

**Comment by illfated** [comment]
Very good. Thank you. I will open a PR to have some required "Public Preview Edition" information added to the Linux support information.
