### ISSUE TITLE
Installation instructions lack guidance for intune

### ISSUE THREAD

**Issue by weiss-gal** [MicrosoftDocs/windows-itpro-docs#6431]
in the installation section it is said:
"Application Guard functionality is turned off by default. However, you can quickly install it on your employee’s devices through the Control Panel, PowerShell, or your mobile device management (MDM) solution."

however - no intune or other MDM instructions are provided. although this is the logical way to do it, if you are an enterprise looking to deploy it on multiple machines 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb904674-d586-0a38-0e7c-7ac3e06cbcd9
* Version Independent ID: 549fbb52-6234-2a79-8604-85498e622f98
* Content: [Enable hardware-based isolation for Microsoft Edge (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/install-wd-app-guard#install-application-guard)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/install-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-guard/install-wd-app-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@weiss-gal thank you very much for raising this issue. I've updated the content, and the changes should render live tomorrow sometime.
