### ISSUE TITLE
Feature Availability

### ISSUE THREAD

**Issue by g4gavin** [MicrosoftDocs/windows-itpro-docs#6432]
[Enter feedback here]
Hi, the paper contained is very informative, thought it is labelled as a white paper. What's not clear is whether this method is now available or a work in progress. Can you advise on timelines to completion or where I can get more information on configuration, compatibility and deployment steps please?

Thanks,

G

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe18d494-b699-1364-3871-c5ebae9ec817
* Version Independent ID: 81887393-4f25-e07d-cbfc-f85f93362750
* Content: [Windows Updates using forward and reverse differentials - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/psfxwhitepaper)
* Content Source: [windows/deployment/update/PSFxWhitepaper.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/PSFxWhitepaper.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by TJ2215** [comment]
Hi , Yes this is in effect from 1809 onwards.

**Comment by mypil** [comment]
@g4gavin - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @TJ2215 so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
