### ISSUE TITLE
Group Policy path is no longer valid

### ISSUE THREAD

**Issue by rafalfitt** [MicrosoftDocs/windows-itpro-docs#6433]
Expand the tree to Windows components &gt; Windows Defender &gt; Signature updates and configure the following settings

should be changed to

Expand the tree to Windows Components &gt; Windows Defender Antivirus &gt; Security Intelligence Updates and configure the following settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c033d14-427d-26d5-eca8-facf190da87d
* Version Independent ID: 624d52e5-6cf5-534e-83c3-66925292ddcd
* Content: [Manage how and where Windows Defender AV receives updates - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/manage-protection-updates-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/manage-protection-updates-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/manage-protection-updates-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@rafalfit.  clearly mentioned in note section.
