### ISSUE TITLE
In RDP logon event, Workstation Name and Source Network Address dont match.

### ISSUE THREAD

**Issue by zjxian** [MicrosoftDocs/windows-itpro-docs#6438]
As stated, in a 4624 event generated by rdp session (logon type = 10), the Workstation Name points to the server being logged on, and Source Network Address points to the client IP address.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aefbbdcc-606c-276c-47ee-fe2b2cb65c61
* Version Independent ID: e0979867-e6bc-7fb9-1279-646b319823b0
* Content: [4624(S) An account was successfully logged on. (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624#feedback)
* Content Source: [windows/security/threat-protection/auditing/event-4624.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4624.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by kannanb-github** [comment]
Unlike logon type 2, which is a user logged on to the computer interactively as well as local, the logon type 10 is logged into the computer using terminal services or remote desktop (RDP) access. The remote desktop or terminal services with the source network address of logon type 10 are recorded in the event log with event ID 4624 to identify the source IP address of the client computer or the network address from where the remote desktop access initiated. These details will be helpful for auditing as well as diagnosing the issues.
So the source network pointing to the client computer is logically correct and needed information. As there is no issue found with logon type 10 on the event 4624 log details, please reply if you have any questions here.

**Comment by zjxian** [comment]
Here is the description in https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624

Network Information:

Workstation Name [Type = UnicodeString]: machine name from which logon attempt was performed.    **=>> This is misleading. The Worstation Name is the server being logged on. NOT the client workstation name.**

Source Network Address [Type = UnicodeString]: IP address of machine from which logon attempt was performed.     **=>> This is correct, and indeed the information is needed.**

I'm not arguing about the event log and logic behind it, just hope to improve the document.

**Comment by e0i** [comment]
Closing via #6807
