### ISSUE TITLE
Enterprise Certificate Pinning docs not clear about non-IE/Edge clients

### ISSUE THREAD

**Issue by JeremyRand** [MicrosoftDocs/windows-itpro-docs#6439]
The [Enterprise Certificate Pinning docs](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/b1a7d49de9d57ac60ce0eac79dc04421a711ca4a/windows/security/identity-protection/enterprise-certificate-pinning.md) state:

> Any site certificate triggering a name mismatch causes Windows to write an event to the CAPI2 event log and prevents the user from navigating to the web site using Microsoft Edge or Internet Explorer.

This statement is unclear about what the expected behavior is for TLS clients that are not Edge or IE but which do use CryptoAPI to verify certs.  When I briefly tried it with Chromium, the pinning failure was logged but Chromium loaded the page without errors.  It would be useful to document what the behavior is for other TLS clients that use CryptoAPI to verify certs.

If other TLS clients aren't expected to block the page load by default, it would also be useful to document how this behavior can be changed (e.g. maybe there's a whitelist of TLS client executable filenames like EMET has, or maybe there's some registry key that can make it be enforced system-wide, or maybe there's something special that the TLS client must do to signal to CryptoAPI that pinning should be enforced).

**Comment by MaratMussabekov** [comment]
Hello @JeremyRand ,
**It would be useful to document what the behavior is for other TLS clients that use CryptoAPI to verify certs.** - others do not block anything. I will create a PR to add it to the article.
**If other TLS clients aren't expected to block the page load by default, it would also be useful to document how this behavior can be changed** - sorry, didn't find a way to force cert pinning.

Thank you
