### ISSUE TITLE
Please add to the article...

### ISSUE THREAD

**Issue by hedegaardDK** [MicrosoftDocs/windows-itpro-docs#6440]
Please add to the article, how to also make the "Set a scheduled task to run the powershell script" in a GPO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84fc852e-4ce0-1d6d-fbc8-76732407e576
* Version Independent ID: 30d715c0-35f0-0b52-68da-75a5f85a619b
* Content: [Windows Defender Antivirus Virtual Desktop Infrastructure deployment guide - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/deployment-vdi-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/deployment-vdi-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/deployment-vdi-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by martyav** [comment]
Hi, @hedegaardDK 

I started working with a PM on this issue.

They wanted more context on the ask. They understood it to mean, creating a scheduled task that runs a PowerShell script that downloads updates with a GPO. In their opinion, they wouldn't create the task with a GPO, but would rather distribute a PowerShell script with GPO to create and maintain the task.

I'll be opening a PR soon based on this issue for others to review.

Thanks,
@martyav

**Comment by hedegaardDK** [comment]
Hi @martyav 

I meant, add to the article how to also add a schedule task in Group Policy – Preference, under schedule task, how to add the PowerShell to run from there.
It was just a suggestion to also give the customer help to solve it like this.

And my main problem with this setup was, that I didn’t wanted to have a network share with the definition file, but rather wanted to have it lying local on the Citrix XenDesktop machine’s persistent disk. (I am running Citrix PVS setup)
But I never got it to work, as the definition download script you have in the article was, downloading a new set of files, instead of overwriting the existing file, and couldn’t get it to work with the other GPO settings needed. 

But I am moving towards a new IT setup, where we will close down Citrix, and use 100% Azure cloud with clients joined as “Azure AD Joined”, intune and more.
So I don’t put to much effort into the existing IT setup anymore. 😊
