### ISSUE TITLE
Supported windows versions are not valid

### ISSUE THREAD

**Issue by yogeshasalkar** [MicrosoftDocs/windows-itpro-docs#6441]
I have checked this Group policy on the following operating systems and found that it is not available on this OS.

Windows 8.1 -&gt; 6.3 (Build 9600): Final Build
Windows 8 -&gt; 6.2 (Build 9200): Final Build
Windows Server 2012 -&gt; 6.2 (Build 9200): Final Build
Windows Server 2012 r2 -&gt; 6.3 (Build 9600): Final Build
Windows Server 2008 r2 -&gt; 6.1 (Build 7601): Final Build
Windows Server 2008
Windows 7 -&gt; 6.1 (Build 7601): Final Build

This Group Policy is only applicable on Windows 10, Windows Server 2019.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2715cb88-3ce3-1ba7-b4cb-7893e9d490ea
* Version Independent ID: a38a2b48-6cdd-bb25-5cb3-e00124b9effd
* Content: [Interactive logon Don't display username at sign-in (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-dont-display-username-at-sign-in)
* Content Source: [windows/security/threat-protection/security-policy-settings/interactive-logon-dont-display-username-at-sign-in.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/interactive-logon-dont-display-username-at-sign-in.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Good point. The page itself says, in the Reference section, that "A new policy setting has been introduced in Windows 10 starting with Windows 10 version 1703."

Allow me to open a PR to correct the "Applies to" section, as per your confirmation above.

**Comment by illfated** [comment]
My only uncertainty here is Windows Server 2016, but I am guessing that it should be available there, as long as the server build version is up to date.

**Comment by yogeshasalkar** [comment]
> My only uncertainty here is Windows Server 2016, but I am guessing that it should be available there, as long as the server build version is up to date.
> ***
> edit: I will choose the safe route for my PR, using only your recommended wording at first: "This Group Policy is only applicable on Windows 10, Windows Server 2019."

I have also tested it on latest build of Server 2016 and it is not available on that too.

**Comment by illfated** [comment]
Thank you for confirming this. I chose to use the wording "Applies to: Windows 10, Windows Server 2019" just as my PR title says.

**Comment by yogeshasalkar** [comment]
> Thank you for confirming this. I chose to use the wording "Applies to: Windows 10, Windows Server 2019" just as my PR title says.

When changes will reflect on page? Because it's still the same

**Comment by illfated** [comment]
First of all, my PR #6469 needs to be accepted & merged into the public branch. When that happens, this issue ticket will be closed automatically. 

After that, it will take anything between 1-2 days and a week for the change to migrate from the [`public`](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/public) branch to the docs.microsoft.com page.
