### ISSUE TITLE
the copy paste fields on this doc are incorrect and can cause errors/confusion

### ISSUE THREAD

**Issue by bled1982** [MicrosoftDocs/windows-itpro-docs#6443]
Step 4 "From a command prompt, verify that you have the file. Extract the contents of the archive: " this copy field has extra characters that should not be in the copy field to unzip the file. 

Additional errors in copy fields :

mdatp --health orgId
[your organization identifier] -LINE NEEDS REMOVED 

mdatp --health healthy
1 - LINE SHOULD BE REMOVED 

mdatp --health realTimeProtectionEnabled
1-LINE SHOULD BE REMOVED 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2197cba-30ac-1749-e25a-6f39c9ee9d20
* Version Independent ID: bcd14f13-ab59-8e69-5c83-42fee6e51f87
* Content: [Deploy Microsoft Defender ATP for Linux manually - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Thank you for pointing this out. I will start working on a PR to have those unwanted lines removed.

**Comment by illfated** [comment]
BTW, I will also try to get rid of that "copy" status of the `ls -l` box as well, because that content is only intended to be displayed, not actively copied and pasted into the console by users.

**Comment by bled1982** [comment]
Awesome thanks , I just noticed these when I was testing out on my linux vm .

TJ Bledsoe
Support Engineering | Azure Security
Customer Service & Support | Microsoft Corporation
• v-thbled@microsoft.com<mailto:v-thbled@microsoft.com>
[cid:image001.jpg@01D60DA9.99AEEB60]

**Comment by illfated** [comment]
There you go. Feel free to comment, like & subscribe (just kidding about that "like & subscribe" part, I have obviously watched too much YouTube lately) 😜
