### ISSUE TITLE
Unable to see and apply NodeCache CSP on the Device

### ISSUE THREAD

**Issue by parmeshthee** [MicrosoftDocs/windows-itpro-docs#6448]
As per the documentation "https://docs.microsoft.com/en-us/windows/client-management/mdm/nodecache-csp" the NodeCache is present at LocURIs "./Device/Vendor/MSFT" and "./User/Vendor/MSFT".  But in the windows10 versions 1909 (OS Build 18363.720) and 1809 (OS Build 17763.1098), the NodeCache entry is not present at LocURI "./Device/Vendor/MSFT". However, this is there at LocURIs "./User/Vendor/MSFT" and "./Vendor/MSFT".   
Also unable to add the entry into NodeCache i.e. NodeCache CSP is not being applied on the Device even by following the Oma DM Examples listed on the page "https://docs.microsoft.com/en-us/windows/client-management/mdm/nodecache-csp#oma-dm-examples". The 405 error code is being returned. Is there anything that has been changed on these Windows Versions? Are there any examples that can work on the latest Windows10 versions? Thanks.

**Comment by VLG17** [comment]
@parmeshthee I see that the article has been updated to reflect what you've notices in the newer OS builds

![image](https://user-images.githubusercontent.com/41186174/89635181-44995f80-d8af-11ea-8531-d93edd178bf3.png)

Regarding the error you are getting, i could not find anything else other than checking if a PIN is not set on the device:

![image](https://user-images.githubusercontent.com/41186174/89635143-38150700-d8af-11ea-8e61-1ee151d88cc4.png)

If this does not help, i recommend [opening a support ticket ](https://support.microsoft.com/en-us/contactus/) to look into this further.
