### ISSUE TITLE
MDM Policy CSP examples

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/windows-itpro-docs#6449]
Should include sample values; it's actually not easy to figure out what's the correct data format for each and every policy parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1684b30a-3187-85ce-0cf7-10d1b8298b7f
* Version Independent ID: 9b7170fc-2b39-8e46-7898-894a45de8623
* Content: [Configure Windows Update for Business (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-configure-wufb)
* Content Source: [windows/deployment/update/waas-configure-wufb.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-configure-wufb.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@arcarley is this something we can include in the update we're working on right now?

**Comment by acarley7** [comment]
Yep! I will ensure that we include clear examples and recommended values.
