### ISSUE TITLE
Finally, after almost 1/4 Century. But it's just the start, isn't it?

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/windows-itpro-docs#645]
Good evening
Windows was - and still is - a nightmare for every security aspect, just because there was no complete list of each executable, service, etc. which 'must' have connection to unknown web servers. And it got worse every day, because Windows Servers started to use applications and services, which must not be part of a Server OS. Anyway, we're replacing them just because of such annoying things.

Therefore it's really great that you started this list, thansks a lot.

Of course, this list must be part of the (virtual) system manual, and the list must be complete.
If we google for AppHostRegistrationVerifier.exe, then the search result must immediately lead your customers to an useful description for this application.

Additionally, M$$ should start redesigning svchost. To route probably more than 60 services in an non-transparent using a single exe is... a security nightmare, too.

Kind regards, Thomas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 578aa782-ef76-6a8e-73be-5ac0f0edb179
* Version Independent ID: dae3d33b-c9b1-c487-095d-93aa66a1f0a9
* Content: [Windows 10 connection endpoints](https://docs.microsoft.com/en-us/windows/configuration/manage-windows-endpoints-version-1709)
* Content Source: [windows/configuration/manage-windows-endpoints-version-1709.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/manage-windows-endpoints-version-1709.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by Justinha** [comment]
@schittli Thanks for the feedback. The list of connections is complete. It's tested by our engineering team and the topic is updated with each Windows release.
