### ISSUE TITLE
Group SID WinVersion requirement

### ISSUE THREAD

**Issue by TBUonFleek** [MicrosoftDocs/windows-itpro-docs#6450]
When applying this policy with &lt;accessgroup desc = "S-1-5-32-544"&gt; (Administrators Group) to Semi-Annual Channel (10.0.18363.720) i always get the Error, that the GroupName could not be found.

On my Windows 10 Insider Fast VM & Physical Client it works in any Szenario.

Is there a Windows 10 Version dependency for the AccessGroup SID Feature? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0c28c15-f0be-d732-4d9e-cf5df5e64e8b
* Version Independent ID: 17eba45f-d200-e656-42b9-e1a512931eea
* Content: [Policy CSP - RestrictedGroups - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-restrictedgroups#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-restrictedgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-restrictedgroups.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation and content-related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
