### ISSUE TITLE
In what situations the "info" button is missing on Intune managed Windows 10 devices?

### ISSUE THREAD

**Issue by Emmity** [MicrosoftDocs/windows-itpro-docs#6452]
We have a situation where Windows 10 workstations that are joined to AzureAD auto-register in Intune fine, but on the workstations the "Info" button is missing under the "Access work or school" menu. Only "Disconnect" button exists. The workstations receive settings and apps from Intune, so they are under MDM management according to this page, Info button should be shown. We have tested with multiple 1903 and 1909 devices. What can cause the missing INFO button? This page is missing our situation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39ae2ccd-9f3f-dcb5-3a20-46b1b4fd3d53
* Version Independent ID: b381c208-94b1-2d22-ef16-a57c138a7d72
* Content: [MDM enrollment of Windows-based devices - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/mdm-enrollment-of-windows-devices#feedback)
* Content Source: [windows/client-management/mdm/mdm-enrollment-of-windows-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/mdm-enrollment-of-windows-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @Emmity ,
Can this issue be closed since it seems like you already found the solution? (according to https://github.com/MicrosoftDocs/IntuneDocs/issues/3389)
Thank you
