### ISSUE TITLE
Email address pwdless@microsoft.com unable to accept external emails

### ISSUE THREAD

**Issue by daniel-rogers-gh** [MicrosoftDocs/windows-itpro-docs#6455]
Your message to pwdless@microsoft.com couldn't be delivered.

The group pwdless only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca080bd-ed37-60a8-ec22-b1929166ff0c
* Version Independent ID: d2742e0c-9d66-4b1f-8555-a1fb1546455b
* Content: [Passwordless Strategy - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/passwordless-strategy#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/passwordless-strategy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/passwordless-strategy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
Hm. That means we need to look for a different email address for that page, unless this is a temporary issue.
Alternatively, it could mean that we need to remove the sentence suggesting to use that email address.

**Comment by daniel-rogers-gh** [comment]
Are there alternative places I could ask a question regarding this step/statement:

(2.d.) Remove password capabilities from Windows.

All of the methods that disable passwords also disable the ability to RunAs anything which is integral to administering systems and running standard accounts in least priviliged mode.

It seems odd I can't find anything which addresses this given I don't think it's viable to maintain a fleet of systems without RunAs.

Any recommendations on where to initiate that conversation would be excellent (and perhaps worth placing in this article)

**Comment by illfated** [comment]
Thank you for asking. This issue tracker is mostly intended to improve the documentation pages, either by reporting errors, suggesting improvements, updates or adjustments for the existing docs.

Regarding how to use the software technology, in case it is not described adequately or detailed enough, try the forum pages:
- https://social.technet.microsoft.com/Forums/en-US/home
- https://social.microsoft.com/forums
- https://answers.microsoft.com/

The forum pages are usually quicker to respond and more appropriate for discussions as well as your type of question.

We will more than welcome feedback regarding changes to the existing documentation, so if your research ends up handing you updated information, please comment again and tell us what you found. 😉
