### ISSUE TITLE
Rollback

### ISSUE THREAD

**Issue by ThiloL** [MicrosoftDocs/windows-itpro-docs#646]
How to detect (automatically, mass option) which clients had made a rollback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd88f752-60aa-95df-a7b3-ce3056e64a20
* Version Independent ID: aaf24bdd-548e-8049-8bbb-4911c23999a7
* Content: [Resolve Windows 10 upgrade errors - Windows IT Pro](https://docs.microsoft.com/en-us/windows/deployment/upgrade/resolve-windows-10-upgrade-errors)
* Content Source: [windows/deployment/upgrade/resolve-windows-10-upgrade-errors.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/resolve-windows-10-upgrade-errors.md)
* Service: **unspecified**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
In version 1803 you can run custom actions when there is a rollback, either initiated by a user or by the system see https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-command-line-options#21

**Comment by ThiloL** [comment]
I read there "If the user rolls back their version of Windows, run a script." Does this really include automatic rollbacks by the setup program if something fails?
