### ISSUE TITLE
Notes on permission denied

### ISSUE THREAD

**Issue by tobrz** [MicrosoftDocs/windows-itpro-docs#6462]
Please fix the page after hitting accept or make the "note" more prominent and move it above the sections where you describe clicking accept on the consent page. We spent an entire day trying to determine what a "tenant admin" role was, thinking it was something other than global admin, because we were getting that error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9dae9da-eaf0-c209-7c65-be8d2c1ada12
* Version Independent ID: 28b6788d-7982-23c2-5f19-f80690ebc0ce
* Content: [Pin Reset - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
(Ref. PR **Moved the note section** #6479 )

**Comment by mypil** [comment]
@tobrz - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/8bd6171cb52d2735975394db77c58f9e644414d6. 


Thank you for your contribution to make the docs better! Much appreciated!
