### ISSUE TITLE
Missing Option Informaton in SCEP Profile

### ISSUE THREAD

**Issue by NRL-LEastham** [MicrosoftDocs/windows-itpro-docs#6466]
Hi, there's been an update to the SCEP Profile creation pane.  This update has added the Certificate Type option that can be User or Device.  It would be good to explicitly define the correct setting for this as it relates to a user but the article also refers to devices.
Thanks.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f709fd4-0b5d-b238-4060-222d550cd538
* Version Independent ID: fb3f29da-2236-c47d-6bea-8efbcec8d7d3
* Content: [Using Certificates for AADJ On-premises Single-sign On single sign-on - Microsoft 365 Security](https://docs.microsoft.com/en-gb/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by MaratMussabekov** [comment]
Hello @NRL-LEastham ,
certificate type is User.
I created a PR to add it to the article
Thank you

**Comment by illfated** [comment]
(Ref. PR **update the profile creation instruction** #6494)

**Comment by mypil** [comment]
@NRL-LEastham - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/3c781945b8e8bc024d4f9f6276cfa18fc8d8652e. 


Thank you for your contribution to make the docs better! Much appreciated!
