### ISSUE TITLE
AppLocker Allowed Executable Runs Denied DLL

### ISSUE THREAD

**Issue by bbenavidez** [MicrosoftDocs/windows-itpro-docs#6467]
I am testing AppLocker's functionality to assess suitability for protecting a windows application from tampering. As a test I have a simple executable compiled from C# that displays a window and button. When the button is clicked it uses a single DLL dependency to pull the system time and IP and return it as a string. The window then updates with a message stating the returned string. An AppLocker executable rule was added to allow the executable based on its hash. Additionally, I have generic DLL rules that allow execution of all DLLs in the Windows folder and the Program Files folder. My test executable and its dependency are both in a folder on the desktop (not a valid DLL execution folder).

After ensuring the AppIdSvc is running and doing a gpupdate on the client PC, I was able to run the executable (as expected) but the executable was also able to run its DLL dependency even though the dependency was outside of the Windows/Program Files directories. This was also the case after I replaced that DLL with a tampered one to ensure it wasn't somehow related to the rule created for the executable and to prove that my executable is actually running that dependency (it is). Even after I added an explicit rule to deny both the legitimate and tampered DLLs based on their hash, it's still able to run in both cases. Reviewing the AppLocker logs I don't see any message saying the DLL was or was not allowed to run (it's as if AppLocker never saw it) even though I am able to see that the DLL was accessed by the executable in Process Monitor. Other AppLocker logs show that the executable was allowed to run (letting me know my rules are working - I also ran many other AppLocker tests to ensure it is actually running and it was).
 
Is AppLocker not able to protect the integrity of dependency DLLs based on their hash? Can an allowed executable run any DLL? I've read some articles that rundll32 circumvents the DLL rules by being allowed to run from its safe location while loading and executing DLLs from unsafe locations and there may be something similar here.

**Comment by mypil** [comment]
@bbenavidez - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by bbenavidez** [comment]
Apologies, this is probably less of a documentation issue and more of a functionality issue. The section in question would probably be https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/create-a-rule-that-uses-a-file-hash-condition but, since this isn't so much a documentation change rather than troubleshooting, I'll go ahead and close this issue.

**Comment by illfated** [comment]
@bbenavidez : Thank you for handling this ticket and closing it, based on the fact that you are dealing with a functionality issue rather than documentation.

I hope you will find it easier to post in troubleshooting forums like Technet or other Microsoft social groups, or discuss it with Microsoft support, if you need quicker response.
