### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by azupwn** [MicrosoftDocs/windows-itpro-docs#6470]
[Events List: 4985(S): The state of a transaction has changed] link incorrectly takes you to https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4674

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 599a7585-081e-692a-8f82-b6e9cbfbc0e6
* Version Independent ID: ad2b5094-8c02-0a75-3d3f-0ef2fa510339
* Content: [Audit Other Privilege Use Events (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-other-privilege-use-events#feedback)
* Content Source: [windows/security/threat-protection/auditing/audit-other-privilege-use-events.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/audit-other-privilege-use-events.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Oh. Right. The link should have been the next page in the menu, "[4985(S): The state of a transaction has changed.](https://docs.microsoft.com/windows/security/threat-protection/auditing/event-4985)"
- https://docs.microsoft.com/windows/security/threat-protection/auditing/event-4985

**Comment by illfated** [comment]
Thank you for reporting this typo. 
This should be relatively easy to fix. 
I will open a PR to have it corrected.
The full change may take a while.
Please be patient with the process.
