### ISSUE TITLE
How do I add "Window Manager\Window Manager Group" back into the "Increase Scheduling Priority" (Local Policies \ User Rights Assignment"

### ISSUE THREAD

**Issue by LPonten** [MicrosoftDocs/windows-itpro-docs#6471]

**Comment by denisebmsft** [comment]
Hello @LPonten. To which article does your question apply? This will help us route it to the right writers/team.

**Comment by LPonten** [comment]
https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/increase-scheduling-priority

**Comment by MaratMussabekov** [comment]
hello, @LPonten,
you could do it by performing following steps:
1. go to the policy where you removed "Window Manager\Window Manager Group" from
2. go to **computer configuration>windows** settings, right click on **security settings** and select **export policy**
![image](https://user-images.githubusercontent.com/48041687/81140440-c4e3b800-8f82-11ea-98f2-91e5db69ab7a.png)
3. save the file, open it using notepad
4. find the string called **SeIncreaseBasePriorityPrivilege** and append ***S-1-5-90-0** to it (*S-1-5-90-0 is Window Manager\Window Manager Group)
![image](https://user-images.githubusercontent.com/48041687/81140608-6f5bdb00-8f83-11ea-9fae-2dba914bdbbe.png)
5. save the file, import it back to the policy

Thank you

**Comment by mypil** [comment]
@LPonten  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @MaratMussabekov so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
