### ISSUE TITLE
You can override GPO Policies with Intune MDM

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/windows-itpro-docs#6478]
"NetworkIsolation Group Policy setting takes precedence over MDM Policy settings." You can actually override GPO Policies with Intune MDM -  https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-controlpolicyconflict

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f23c9b6-81aa-b06d-5c19-196ac933b6ff
* Version Independent ID: 0c7eb396-4274-c546-6063-6d38382b956d
* Content: [Limitations while using Windows Information Protection (WIP) (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/limitations-with-wip#feedback)
* Content Source: [windows/security/information-protection/windows-information-protection/limitations-with-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/limitations-with-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
@SLeuthold - Thank you for your feedback. As per my understanding, MDM policy only takeover if that policy is available in CSP so there is no change required in the document. 

If there is please do let me know so that I can look into that and make necessary changes.

Thanks
Imran.

**Comment by mypil** [comment]
@SLeuthold - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @joinimran so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
