### ISSUE TITLE
doWipePersistProvisionedData Method

### ISSUE THREAD

**Issue by Niglb** [MicrosoftDocs/windows-itpro-docs#648]
Is there a way to invoke the doWipePersistProvisionedData method? I do not see it exposed via WMI, only doWipe. Is doWipePersistProvisionedData a parameter on doWipe? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bce891c-a489-48af-74cb-258713a7bcbd
* Version Independent ID: 6ce5a361-3207-2c5f-9595-4f77cf397d73
* Content: [RemoteWipe CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/remotewipe-csp)
* Content Source: [windows/client-management/mdm/remotewipe-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/remotewipe-csp.md)
* Service: **unspecified**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by DaniHalfin** [comment]
Hi @Niglb, this is currently a gap we're aware of. The feature team is considering adding this in future releases. We'll try to update back, but I would advise to follow future releases announcements to find information about this and other improvements.

**Comment by Niglb** [comment]
Thank you very much for this follow up - we manage a very large environment and have gone to a Microsoft image with a provision package. We were looking to script a remote Reset PC while maintaining the provision package.

**Comment by Niglb** [comment]
I do not see these methods available in 1803 - any news on this?

**Comment by DaniHalfin** [comment]
Nothing that we can currently share.

**Comment by aaronlower** [comment]
@Niglb - check the recent WIP fast and slow builds for this new capability! thank you for your feedback.

**Comment by Niglb** [comment]
I just found this method in my preview build fast build machine! Will this find it's way into major releases anytime soon?

**Comment by aaronlower** [comment]
Yes, it is in builds 17712 and higher/newer so look for it in the next major release (code name RS5)

**Comment by carcova** [comment]
Good morning;

I cant run dowipe in Powershell. 

I need a script to format system disk and the option dowipe can help me. 

Can you help me?

How I include library DMWmiBridgeProv.dll?

I test with:

Add-type -path "C:\Windows\System32\DMWmiBridgeProv.dll"

This shows me error.

Thank you very much.
