### ISSUE TITLE
双硬盘如何安装How do I install a dual hard disk

### ISSUE THREAD

**Issue by wangwenjun91** [MicrosoftDocs/windows-itpro-docs#6480]
MDT：
两块硬盘，一块SSD，一块HDD，系统安装到SSD中，HDD分区不变。如何实现？
Two hard disks, one SSD, one HDD, the system is installed into the SSD, the HDD partition is unchanged. How?

**Comment by wangwenjun91** [comment]
> 两块硬盘，一块SSD，一块HDD，系统安装到SSD中，HDD分区不变。如何实现？
> Two hard disks, one SSD, one HDD, the system is installed into the SSD, the HDD partition is unchanged. How?

**Comment by RAJU2529** [comment]
Post your question in Microsoft answer forum and tech immunity microsoft forum
