### ISSUE TITLE
What if MDMWinsOverGP is not present on Device. Who will win Intune or GPO?

### ISSUE THREAD

**Issue by yogeshasalkar** [MicrosoftDocs/windows-itpro-docs#6482]
It is not mentioned in the document that who will win if MDMWinsOverGP is not present on the device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: becd9bd1-6396-3f4a-cc78-c9a06b781516
* Version Independent ID: efeec2a0-08b0-d1fc-72c5-14c23fa11397
* Content: [Policy CSP - ControlPolicyConflict - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-controlpolicyconflict)
* Content Source: [windows/client-management/mdm/policy-csp-controlpolicyconflict.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-controlpolicyconflict.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello, @yogeshasalkar,
by default (i.e. when MDMWinsOverGP is not presented), GPO has a precedence (source: https://docs.microsoft.com/en-us/mem/intune/fundamentals/resolve-gpo-and-microsoft-intune-policy-conflicts)
Thank you

**Comment by yogeshasalkar** [comment]
Hi @MaratMussabekov , thanks for the answer.

**Comment by yogeshasalkar** [comment]
Could anyone from Microsoft could confirm who wins? Intune or GPO?

**Comment by MaratMussabekov** [comment]
Dear @Dansimp , could you please confirm?
I'm pretty sure for the versions prior to 1803 GPO always wins, and since 1803 - GPO wins unless the MDMWinsOverGP is set to 1.

Thank you

**Comment by mypil** [comment]
@ManikaDhiman - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by ManikaDhiman** [comment]
@mypil - The behavior mentioned by @MaratMussabekov above is correct. Thanks!

**Comment by mypil** [comment]
@yogeshasalkar - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @MaratMussabekov and @ManikaDhiman so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
