### ISSUE TITLE
Does application guard use windwosdefenderapplicationguardcsp or apphvsi csp and also respective GPOs are not mentioned

### ISSUE THREAD

**Issue by yogeshasalkar** [MicrosoftDocs/windows-itpro-docs#6483]
This page doesn't have a respective Group Policy setting names. Also which csp does application guard use? this or APPHVSI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a60ddc1-46b6-0e0e-c51c-4d8daf13b8a3
* Version Independent ID: 76543649-84f0-c371-3a8d-4f8d87c7d859
* Content: [WindowsDefenderApplicationGuard CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/windowsdefenderapplicationguard-csp)
* Content Source: [windows/client-management/mdm/windowsdefenderapplicationguard-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/windowsdefenderapplicationguard-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
also these policies pages only  applies to smartphone developers and integrate into windows10 , not for desktop edition

**Comment by MaratMussabekov** [comment]
Hello @yogeshasalkar ,
**This page doesn't have a respective Group Policy setting names.** - I created a PR to add the references to GPO
**Also which csp does application guard use? this or APPHVSI?** - this one
Thank you

**Comment by yogeshasalkar** [comment]
Thanks @MaratMussabekov
