### ISSUE TITLE
Web Link typo on Threat Protection page

### ISSUE THREAD

**Issue by ShaXam-King** [MicrosoftDocs/windows-itpro-docs#6486]
On this page...https://docs.microsoft.com/en-us/windows/security/threat-protection/
...in the "Next generation protection" section there is a link to "URL Protection". The link points to... 
"https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus.md". That results in a 404 error. It appears the ".md" is not supposed to be there.

Thanks!

Dan.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbabaf85-a345-a91e-f4e2-09c2b7871375
* Version Independent ID: bab57f2f-249a-0fe9-4f4a-93d62ce71670
* Content: [Threat Protection (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/)
* Content Source: [windows/security/threat-protection/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/index.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
@ShaXam-King thank you for pointing this out. It's fixed, and you'll see that on the live site sometime between now and this afternoon. The URL is supposed to be https://docs.microsoft.com/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus

**Comment by illfated** [comment]
Nice! Thanks for the quick response. 👍 😃

**Comment by beerisgood** [comment]
Same also for "Behavior monitoring" which redirect to:
"https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-real-time-protection-windows-defender-antivirus.md"

and for "Cloud-based protection" which redirect to:
"https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus.md"

@denisebmsft

**Comment by illfated** [comment]
Oh. Right. I see. Exactly the same type of GitHub link conversion failure as the previous one. `.md` is not supposed to follow along to the links on the docs.microsoft.com pages.
