### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by dominique97** [MicrosoftDocs/windows-itpro-docs#6488]
On the line:
"For more information on enabling MDM with Microsoft Intune, see Setup Windows Device Management."

the link for "Setup Windows Device Management" takes you to a 404 page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc98378-18c5-81bf-769e-d76d26852c91
* Version Independent ID: dd542381-071b-e583-f082-976e8fd91019
* Content: [Onboard Windows 10 machines using Mobile Device Management tools - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-mdm)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-mdm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-mdm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
To me, it looks a bit cumbersome to locate the target page intended for the broken link. Looks like there is some ongoing rewriting of the intune documentation, from "Microsoft intune classic" to modern Microsoft Azure-based Intune. Feel free to suggest where the most relevant information can be found, as well as whether or not the link should be removed or the sentence & link & link text needs to be rewritten to cover the recent changes:

- https://docs.microsoft.com/mem/intune/
- https://docs.microsoft.com/mem/intune/fundamentals/what-is-intune
- https://docs.microsoft.com/mem/intune/fundamentals/what-is-device-management
- https://docs.microsoft.com/mem/intune/enrollment/
- https://docs.microsoft.com/mem/intune/enrollment/device-enrollment
- https://docs.microsoft.com/mem/intune/enrollment/device-management-capabilities
- https://docs.microsoft.com/mem/intune/enrollment/enrollment-options

It could also be necessary to search through Microsoft Endpoint pages to find relevant information, although I only know this topic on a superficial level.

- https://docs.microsoft.com/microsoft-365/business/set-up-windows-devices?view=o365-worldwide

**Comment by illfated** [comment]
@dominique97 : As you can see, your issue has been resolved in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/261b362ee5e9e4704cec60adfd1e48bde5fa1996 and the update is available in the online documentation page.
