### ISSUE TITLE
ipConfig - Trusted Signal - Multiples

### ISSUE THREAD

**Issue by toddjohnson39** [MicrosoftDocs/windows-itpro-docs#6489]
Within a rule using ipConfig signal how are multiple entries handled? Do they all need to evaluate to TRUE, or just one?  Use below as example

&lt;rule schemaVersion="1.0"&gt; 
    &lt;signal type="ipConfig"&gt; 
        &lt;ipv4Prefix&gt;10.10.10.0/24&lt;/ipv4Prefix&gt;
        &lt;ipv4DnsServer&gt;10.10.0.1&lt;/ipv4DnsServer&gt;
        &lt;ipv4DnsServer&gt;10.10.0.2&lt;/ipv4DnsServer&gt;
        &lt;dnsSuffix&gt;corp.contoso.com&lt;/dnsSuffix&gt; 
	&lt;/signal&gt; 
&lt;/rule&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f8c2ce-8edb-60d3-ebf9-bdb625bf66dc
* Version Independent ID: ee1ed0a8-b05c-c499-6504-40b5b298c53b
* Content: [Multifactor Unlock - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/feature-multifactor-unlock)
* Content Source: [windows/security/identity-protection/hello-for-business/feature-multifactor-unlock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/feature-multifactor-unlock.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by Matt-C22** [comment]
@toddjohnson39 All entries will be evaluated as they are under the same RULE, and they will all checked for - TRUE.

You can use the 'OR' factor only **(",")** when there are multiple rules defined, i.e.:
<rule schemaVersion="1.0"> 
	<signal type="ipConfig"> 
	    <dnsSuffix>corp.contoso.com</dnsSuffix> 
	</signal> 
</rule>,
<rule schemaVersion="1.0">
	<signal type="bluetooth" scenario="Authentication" classOfDevice="512" rssiMin="-10" rssiMaxDelta="-10"/>
</rule>
----------------
If you want to define multiple rules and also evaluate all of them to TRUE, use **"<and></and>"**

<rule schemaVersion="1.0">
<and>
  <signal type="ipConfig">
   <dnsSuffix>corp.microsoft.com</dnsSuffix>
  </signal> 
  <signal type="bluetooth" scenario="Authentication" classOfDevice="512" rssiMin="-10" rssiMaxDelta="-10"/>
</and>
</rule>

**Comment by mypil** [comment]
@toddjohnson39 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @Matt-C22 so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Comment by cloidl** [comment]
In order to include two different IP ranges in an OR configuration one would need to use something like the following for example?

<rule schemaVersion="1.0"> 
    <signal type="ipConfig"> 
        <ipv4Prefix>192.168.1.0/24</ipv4Prefix>
    </signal> 
</rule>,  
<rule schemaVersion="1.0"> 
    <signal type="ipConfig"> 
        <ipv4Prefix>10.10.10.0/24</ipv4Prefix>
    </signal> 
</rule>
