### ISSUE TITLE
Failed to create a Live Response session - Machine's protection level doesn't allow to launch a session on it

### ISSUE THREAD

**Issue by sreemanshanker** [MicrosoftDocs/windows-itpro-docs#6491]
hi!
Was facing the issue of not being able to logon to multiple machines with live response (they are all 1909). Keep getting the error Machine's protection level doesn't allow to launch a session on it. Tried looking up the docs on the microsoft website and couldnt find any related to this. Was wondering if i could get some answers here.

**Comment by mypil** [comment]
@sreemanshanker - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@sreemanshanker - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
