### ISSUE TITLE
missing 0x80244010 issue

### ISSUE THREAD

**Issue by baiysou** [MicrosoftDocs/windows-itpro-docs#6492]
delete client wsus download cache ,now need to fix this missing 0x80244010,

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f76d96ac-5343-20e2-9d99-9c1cea7ccc2e
* Version Independent ID: a95c9b39-4a66-d726-4404-de5af60ac982
* Content: [按组件列出的 Windows 更新错误代码列表 - Windows Deployment](https://docs.microsoft.com/zh-cn/windows/deployment/update/windows-update-error-reference#feedback)
* Content Source: [windows/deployment/update/windows-update-error-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-error-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by jaimeo** [comment]
Sorry, I'm not quite following your description. Can you clarify exactly what change you are requesting?

**Comment by mypil** [comment]
@baiysou - We would like to follow up. Can you please respond to the query of @jaimeo?

Thank you!

**Comment by mypil** [comment]
@baiysou - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
