### ISSUE TITLE
Does this also control / remove Windows inbox apps?

### ISSUE THREAD

**Issue by domcote** [MicrosoftDocs/windows-itpro-docs#650]
Will a clean also remove Windows inbox apps such as Solitaire or Duolingo?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f38c1219-3096-f435-13ae-1c325f9d2b82
* Version Independent ID: 8f0002e6-00e0-eb00-b6b9-dcd16034c949
* Content: [CleanPC CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/cleanpc-csp)
* Content Source: [windows/client-management/mdm/cleanpc-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/cleanpc-csp.md)
* Service: **unspecified**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by lcaseybsa** [comment]
This tool has crashed almost every one of my clients surface pro 4 and surface pro 5 devices using the cleanPC option.  This tool has not been fully tested and should be used with extreme caution as it really has so many bugs Its pretty useless at the moment .

**Comment by tFable** [comment]
My experience with CleanPC has also been mixed. I think better documentation is needed to understand exactly what it is doing when triggered. By observation I believe it is going through a "Restore PC" routine but I can't find any documentation to back that claim.

**Comment by csando** [comment]
It seems to execute the "reset this PC"... but after it does other provisioning tasks, so they get wiped out.  I can see it joins the machine to my domain (pc account appears) and runs some other tasks... then resets the PC and bam, you're back to OOBE and it's like nothing ever happened.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@domcote - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
