### ISSUE TITLE
Question sur le Host

### ISSUE THREAD

**Issue by dexter74** [MicrosoftDocs/windows-itpro-docs#6502]
Bonjour,
Pourriez vous faire un guide sur le blocage des DNS (Domaine) via le fichier Host . 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: a536a609-8ee6-5ac4-9fd1-d8d459fedfd9
* Version Independent ID: ac6433b8-548c-4876-088f-088eea5c48e1
* Content: [Windows10, version1809, points de terminaison de connexion pour les éditions non Entreprise - Windows Privacy](https://docs.microsoft.com/fr-fr/windows/privacy/windows-endpoints-1809-non-enterprise-editions#feedback)
* Content Source: [windows/privacy/windows-endpoints-1809-non-enterprise-editions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/windows-endpoints-1809-non-enterprise-editions.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Bonjour
Malheureusement, le blocage du nom de domaine à l'aide du fichier Hosts est hors de portée de ce document.
Cependant, vous pouvez le faire de la manière suivante:
1. allez dans C:\WINDOWS\system32\drivers\etc
2. ouvrez le fichier Hosts
3. allez sur la nouvelle ligne, entrez l'IP localhost (127.0.0.1) puis ajoutez de l'espace puis entrez le nom de domaine que vous souhaitez bloquer (comme sur la capture d'écran)
![image](https://user-images.githubusercontent.com/48041687/80274084-5a648980-86f1-11ea-9b38-f83f4e7ab0a5.png)
4. Enregistrez le fichier

Vous pouvez également voir plus de détails [ici](https://helpdeskgeek.com/how-to/block-websites-using-hosts-file/)

Désolé pour les fautes d'orthographe, il a été traduit à l'aide du traducteur automatique.
Je vous remercie

**Comment by mypil** [comment]
@dexter74 - Merci d’avoir soumis des commentaires.

D’après ce que nous avons compris, la question que vous avez soulevée a été répondue par @MaratMussabekov, nous allons clore cette question.


Merci pour votre contribution pour améliorer les docs! Très apprécié!
