### ISSUE TITLE
Missing info in descriptions for NGP and TVM

### ISSUE THREAD

**Issue by SteveBurkettNZ** [MicrosoftDocs/windows-itpro-docs#6503]
Looks like the Descriptions for Next Generation Protection (NGP) and Threat & Vulnerability Management (TVM) in the Adoption Order section got truncated. They don't include the info about what's included! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7903e2a8-2f3d-daf0-27c4-7397631d96e3
* Version Independent ID: 4ca86831-6873-c391-1fe6-fb13914ee104
* Content: [Prepare Microsoft Defender ATP deployment - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/prepare-deployment)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/prepare-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/prepare-deployment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mypil** [comment]
@SteveBurkettNZ - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/f033ac3. 


Thank you for your contribution to make the docs better! Much appreciated!
