### ISSUE TITLE
0x801c004d  is missing

### ISSUE THREAD

**Issue by nivdolgin** [MicrosoftDocs/windows-itpro-docs#6505]
After applying the new Defender ATP baseline policy, default setting with Hello enabled, some devices throw the following error:

Something went wrong
We weren't able to set up your PIN. Sometimes it helps to try again or you can skip for now and this this later.

For more informaiton on error during PIN setup: https://aka.ms/PINErrors
For additional help, contact your support or IT helpdesk with the following details.
Error code:  0x801c004d  
Correlation ID: [SID]
Timestamp: [long date & time]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by VLG17** [comment]
@nivdolgin I've created a PR and added a new line about this error under the section Errors with unknown mitigation:

**0x801c004d - Unable to enroll a device to use a PIN for login**

For a possible solution, you could check this identical issue: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2900

> Have you tried running "certutil -deletehellocontainer" from cmd or powershell to try cleaning up state?

**Comment by e0i** [comment]
Closing via #6639
