### ISSUE TITLE
Error Running VPN profile update script

### ISSUE THREAD

**Issue by zerrikan** [MicrosoftDocs/windows-itpro-docs#6506]
When running the update VPN profile script on an existing xml VPN profile file, I'm getting an error returned and the new xml file does not have any of the exclusion route data in it.

Exception calling "Insert" with "2" arguments: "Specified argument was out of the range of valid values" 
Line:301 Char:13 ($InputFile = $InputFile[0].Insert($inspoint,$routes)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18462dc7-4de9-9c76-a534-010c11a8ee00
* Version Independent ID: 20f73c06-753e-1ba5-1604-c778aaac2408
* Content: [Optimizing Office 365 traffic for remote workers with the native Windows 10 VPN client - Microsoft 365 Security](https://docs.microsoft.com/en-gb/windows/security/identity-protection/vpn/vpn-office-365-optimization#feedback)
* Content Source: [windows/security/identity-protection/vpn/vpn-office-365-optimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/vpn/vpn-office-365-optimization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **jajo**

**Comment by adamderuwe** [comment]
This script doesn't work.  I have the same issue has @zerrikan

**Comment by adamderuwe** [comment]
@denisebmsft @mypil - any chance we can get an update as to if this will be addressed or not?  Thanks!

**Comment by mypil** [comment]
@adamderuwe - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/3e6aa2959120e9cdddc6bb8ed217284d007c3ced. 


Thank you for your contribution to make the docs better! Much appreciated!
