### ISSUE TITLE
What about on-premise ?

### ISSUE THREAD

**Issue by Sayannara** [MicrosoftDocs/windows-itpro-docs#6507]
The documentation is good, unfortunately, there is less for on-premise. I really miss an operating diagram for this.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 10fcf686-1781-8a62-16bb-b26b3f5982fd
* Version Independent ID: 37d733ad-e809-1674-ffbc-ae3d0c495423
* Content: [Fonctionnement de Windows Hello entreprise-authentification - Microsoft 365 Security](https://docs.microsoft.com/fr-fr/windows/security/identity-protection/hello-for-business/hello-how-it-works-authentication#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-how-it-works-authentication.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-how-it-works-authentication.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@mapalko 

Looks like this feedback is rather suitable for your editorial consideration. Please let me know whether independent contributors could be of any help. Thank you.

**Comment by aczechowski** [comment]
Thanks @Sayannara for the feedback. Given this issue is a couple of years old, I'm going to close it. I don't think it's something we'll be able to get to in the near future. If you're passionate about it, you can reopen this issue and we'll reconsider.
