### ISSUE TITLE
Time Machine backup fails

### ISSUE THREAD

**Issue by shariatpurbasi** [MicrosoftDocs/windows-itpro-docs#6512]
Time Machine backup on macOS Catalina 10.15.4 runs very slow and fails after few hours, while the ATP app is running. Time Machine backup works fine the moment I close the ATP app. _I updated ATP app to the latest using MAU_     

I tried excluding the following items but did not resolve the issues.
```
mdatp --exclusion --add-proces /System/Library/CoreServices/backupd.bundle/Contents/Resources/backupd

mdatp --exclusion --add-folder /System/*

mdatp --exclusion --add-folder /System/Applications/Time\ Machine.app/*

```

**Comment by denisebmsft** [comment]
Looks like this is the same issue as https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6513
