### ISSUE TITLE
page file

### ISSUE THREAD

**Issue by trevorl3124** [MicrosoftDocs/windows-itpro-docs#6514]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b0674a-7bd1-6f30-9e7a-d258ab559138
* Version Independent ID: c1d5e93a-42cb-d29d-bb91-9c38d3a8647f
* Content: [How to determine the appropriate page file size for 64-bit versions of Windows - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/determine-appropriate-page-file-size)
* Content Source: [windows/client-management/determine-appropriate-page-file-size.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/determine-appropriate-page-file-size.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by illfated** [comment]
@trevorl3124 : Unless you have a specific request or suggestion for a documentation imrpovement, I recommend closing this issue.

**Comment by trevorl3124** [comment]
Thanks I’ll take care of it

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
