### ISSUE TITLE
Individual User login limit

### ISSUE THREAD

**Issue by ahmadgeo** [MicrosoftDocs/windows-itpro-docs#6519]
Please advice the status for Cached login attempts for individual user.

What I understand from the article is that a user can use his cached credentials to login as long as Domain Controller isn't available even for infinite count!  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef720207-c5e6-182e-8a34-361244c45641
* Version Independent ID: 4591df7c-e474-9b85-7c09-ce572a66a0a3
* Content: [Interactive logon Number of previous logons to cache (in case domain controller is not available) (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-number-of-previous-logons-to-cache-in-case-domain-controller-is-not-available#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/interactive-logon-number-of-previous-logons-to-cache-in-case-domain-controller-is-not-available.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/interactive-logon-number-of-previous-logons-to-cache-in-case-domain-controller-is-not-available.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@ahmadgeo It seems that a possible value of from 0 to 50 has already been included in the article under the following section,

https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-number-of-previous-logons-to-cache-in-case-domain-controller-is-not-available#possible-values

Please let me know whether this clarifies your question.
