### ISSUE TITLE
Is broken defender able to report in to ATP?

### ISSUE THREAD

**Issue by bradrush** [MicrosoftDocs/windows-itpro-docs#6521]
In the case of defender being in an inoperable state due to scanning a file with two dots in the name or anything of that nature (https://www.techradar.com/news/microsoft-has-just-broken-windows-10s-antivirus-protection-apply-this-fix-straight-away) how would ATP be informed of the broken status since defender appears to be the communication mechanism? Does it have any other methods to report as a fallback or would it somehow fall out of compliance due to lack of reporting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bdb99e4-289a-c09a-c35c-2774fc52a402
* Version Independent ID: 4d325389-c9b8-2601-0ff4-c7b6bf5a6c28
* Content: [Microsoft Defender Advanced Threat Protection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by VLG17** [comment]
@bradrush In that situation (which was fixed shortly after) you would be able to see these "inactive" machines in the [Security Operations Dashboard](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/security-operations-dashboard#sensor-health)

> The Sensor health tile provides information on the individual machine’s ability to provide sensor data to the Microsoft Defender ATP service. It reports how many machines require attention and helps you identify problematic machines.

**Comment by mypil** [comment]
@bradrush - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @VLG17 so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
