### ISSUE TITLE
Message Table for Windows Update Error Codes

### ISSUE THREAD

**Issue by fmike7** [MicrosoftDocs/windows-itpro-docs#6526]
Is there a message table for Windows Update error codes? FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM) does not format Windows Update error codes and ::GetErrorInfo returns nothing when WU interfaces return failed HRESULT codes. Would be helpful to display user-friendly messages instead of error codes.

**Comment by mypil** [comment]
@fmike7 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by fmike7** [comment]
This was actually in reference to this online article: https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-error-reference

It lists WU error codes and descriptions, but it's not clear how to obtain these error descriptions programmatically by those who utilize Windows Update Agent APIs. I was wondering if there is a documented way of loading error description form system messages tables or other APIs.

**Comment by VLG17** [comment]
@fmike7 I'm no developer, but maybe you could leverage this programmatically:

https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes

https://docs.microsoft.com/en-us/windows/win32/debug/system-error-code-lookup-tool

**Comment by mypil** [comment]
@fmike7 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @VLG17 so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
