### ISSUE TITLE
Is it possible to modify the schema of the events in the Storage account?

### ISSUE THREAD

**Issue by jcbendernh** [MicrosoftDocs/windows-itpro-docs#6527]
I have a customer interested in having one consolidated blob container with a folder created for each event type instead of the default blob container each event type.  Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d7c9a2b-c6a2-0c0b-3718-a9c0d2cbbf05
* Version Independent ID: 86974870-2d23-e7e0-e7fb-9a58e4957b00
* Content: [Stream Microsoft Defender Advanced Threat Protection events to your Storage account - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/raw-data-export-storage#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/raw-data-export-storage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/raw-data-export-storage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by VLG17** [comment]
@jcbendernh I think you can leverage streaming ATP Advanced Hunting events to Azure Storage as described here: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/raw-data-export

Although not an official Microsoft source, you can also look at this blog to see a real flow: https://emptydc.com/2019/07/23/microsoft-defender-atp-streaming-api/

**Comment by mypil** [comment]
@jcbendernh - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @VLG17  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
