### ISSUE TITLE
ReadyForWindows Service Moved

### ISSUE THREAD

**Issue by spirrochet** [MicrosoftDocs/windows-itpro-docs#6528]
The link to http://www.readyforwindows.com, redirects to Desktop Analytics: https://docs.microsoft.com/en-us/configmgr/desktop-analytics/ready-for-windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6957383-3bd9-eef9-6410-9c42f8a0b172
* Version Independent ID: a2090374-0fd1-8d67-66de-30c4cf2835f7
* Content: [Overview of Windows as a service (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-overview#feedback)
* Content Source: [windows/deployment/update/waas-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Yes--that doesn't seem like a problem? What change are you suggesting?

**Comment by spirrochet** [comment]
The redirection replaced the old website "readyforwindows.com" so there is no reason to link to the old site, when that resource has been retired. 

So either don't included that link, or discuss what replaced the "readyforwindows.com" listing, such as [Desktop Analytics](https://docs.microsoft.com/en-us/configmgr/desktop-analytics/overview), or just directly link to the page: "https://docs.microsoft.com/en-us/configmgr/desktop-analytics/ready-for-windows"

**Comment by jozefizso** [comment]
The www.readyforwindows.com website does not exists anymore.

```
This site can’t be reachedwww.readyforwindows.com took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT
```

**Comment by jaimeo** [comment]
Fixed. https://github.com/MicrosoftDocs/windows-docs-pr/pull/2778
