### ISSUE TITLE
Configure the Registration Authority Error

### ISSUE THREAD

**Issue by Blacksuit07** [MicrosoftDocs/windows-itpro-docs#6533]
When running the command to register, I get an error.

Command:
Set-AdfsCertificateAuthority -EnrollmentAgent -EnrollmentAgentCertificateTemplate WHFBEnrollmentAgent -WindowsHelloCertificateTemplate WHFBAuthentication -WindowsHelloCertificateProxyEnabled $true

Error: 
WARNING: PS0343: Issuing Windows Hello certificates requires enabling a permitted strong authentication provider, but
no usable providers are currently configured.  These authentication providers are not supported for Windows Hello
certificates: MicrosoftPassportAuthentication.  Windows Hello certificates will not be issued until a permitted strong
authentication provider is configured.

I cannot find any documentation on this error. Anyone have an idea, suggestion, or solution as I cannot find anything while searching the net.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d7753d-30e1-db13-429a-c0b4eaf2c9c5
* Version Independent ID: 5be668ea-fc9d-0fb5-585d-4f5d5575b416
* Content: [Configuring Hybrid Windows Hello for Business - Active Directory Federation Services (ADFS) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-adfs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-adfs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation feedback.

Please consider opening a support ticket via the following link for your question so that it gets answered quickly:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Feel free to re-open this ticket if you feel that the article also needs to be updated.

Thank you, and stay healthy.
