### ISSUE TITLE
Seems like a few 'logon types' are missing

### ISSUE THREAD

**Issue by HenkPoley** [MicrosoftDocs/windows-itpro-docs#6534]
I see at least 0 on my own Windows 10 Pro system as well.

But there are also 12 & 13 listed here: https://markparris.co.uk/2009/11/08/windows-logon-types/

Edit: which got it from: https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-logonsession

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aefbbdcc-606c-276c-47ee-fe2b2cb65c61
* Version Independent ID: e0979867-e6bc-7fb9-1279-646b319823b0
* Content: [4624(S) An account was successfully logged on. (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624#feedback)
* Content Source: [windows/security/threat-protection/auditing/event-4624.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4624.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@HenkPoley 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published via PR #7987.

Thanks for your feedback.
