### ISSUE TITLE
Move between Tenant

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/windows-itpro-docs#6535]
Is it possible to move clients between tenants as it is not recommended, to on-board and off-board at the same time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90534181-66c6-388c-4b09-2f358e864c78
* Version Independent ID: 927e8fa6-72c9-ff10-bd6b-ec044593da18
* Content: [Onboard Windows 10 machines using a local script - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-script#offboard-machines-using-a-local-script)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-script.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-script.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation and content-related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by weyCC81** [comment]
Does Microsoft Support have a Solution?
No, they like to close Tickets (not related to this request)

Do I have a Solution?
Yes

-----

1. Create a GPO for ATP
2. Add the ATP Onboarding (Tenant A) & ATP Offboarding (Tenant B) Scheduled Tasks (not recommended in this documentation)
3. Add a Filter (Item-level targeting: Registry Match) on ATP Onboarding

>not 1 
type MATCHVALUE 
hive HKEY_LOCAL_MACHINE 
key SOFTWARE\Microsoft\Windows Advanced Threat Protection\Status 
valueName OrgId 
valueType REG_SZ 
valueData [Defender ATP GUID from Tenant B]

4. Add a Filter (Item-level targeting: Registry Match) on ATP Offboarding
>not 0 
type MATCHVALUE 
hive HKEY_LOCAL_MACHINE 
key SOFTWARE\Microsoft\Windows Advanced Threat Protection\Status 
valueName OrgId 
valueType REG_SZ 
valueData [Defender ATP GUID from Tenant B]

---

The clients will move from one tenant to the other without losing protection for a long time or interaction with the users to run the scripts on all the clients
