### ISSUE TITLE
No explanation about why we cannot target devices with LOB and Win32 apps

### ISSUE THREAD

**Issue by yvesrosius** [MicrosoftDocs/windows-itpro-docs#6537]
White glove preparation:
https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove#preparation

Additionally, any apps (Win32 or LOB) that are configured to install in the device context and targeted to the user that has been pre-assigned to the Autopilot device will also be installed. Please make sure not to target both win32 and LOB apps to the same device.

Can you please describe why could cause issues? Also, is it recommended to deploy LOB or Win32 apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5b57d1-61b3-39d4-34ff-d6dcb858c250
* Version Independent ID: 42609104-815f-9e7a-39aa-38d92cc910c9
* Content: [Windows Autopilot for white glove deployment - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove#preparation)
* Content Source: [windows/deployment/windows-autopilot/white-glove.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/white-glove.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by MaratMussabekov** [comment]
Dear @yvesrosius ,
Can you please describe why could cause issues? - installation may fail ([source](https://docs.microsoft.com/en-us/mem/intune/apps/lob-apps-windows)). I created a PR to add this info to the article.
Also, is it recommended to deploy LOB or Win32 apps? - there is no preference, both are supported. For Win32 apps there is also an option to use [management extension](https://docs.microsoft.com/en-us/mem/intune/apps/intune-management-extension).
Thank you

**Comment by greg-lindsay** [comment]
We've added clarification to the topic per the PR referenced above. The comment comes directly from Intune docs - see https://docs.microsoft.com/en-us/mem/intune/apps/lob-apps-windows but mainly the reason for not mixing is because it can get complex if things go wrong. Running multiple MSI installs at once can cause failures, but these will be retried multiple times.  It would be pretty bad luck to have each of those retries also fail.
