### ISSUE TITLE
TPM, not TMP

### ISSUE THREAD

**Issue by ntw2** [MicrosoftDocs/windows-itpro-docs#6538]
"Backing up TMP to Active Directory was supported only on Windows 10 version 1507 and 1511."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c3977f-3b78-1d8e-ad8f-50538ad1934f
* Version Independent ID: 46b9ab6d-7a30-4dab-70fa-e1c97cc3ec3e
* Content: [Set up MDT for BitLocker (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/set-up-mdt-for-bitlocker#feedback)
* Content Source: [windows/deployment/deploy-windows-mdt/set-up-mdt-for-bitlocker.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/set-up-mdt-for-bitlocker.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Funny typo. Thank you for pointing it out. 👍
