### ISSUE TITLE
Misleading / ambiguous sentences

### ISSUE THREAD

**Issue by dardie** [MicrosoftDocs/windows-itpro-docs#654]
The sentence 'This command ensures that the user’s current settings become the current state on the Settings Storage Location' in plain reading seems to mean the opposite of what I think you're trying to convey. It would be better rewritten something like 'This command causes the user’s settings to be downloaded from the Settings Storage Location.'

I've found other parts of the UE-V documentation to be similarly equivocal. I think it would be far less effort for the reader if the direction of data between client and server was explained in more direct language.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12653ca8-99b1-2914-8f16-3f8a8461b836
* Version Independent ID: 676eb526-e5da-c526-7279-d653a50cde8e
* Content: [Manage Administrative Backup and Restore in UE-V 2.x](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/uev-v2/manage-administrative-backup-and-restore-in-ue-v-2x-new-topic-for-21)
* Content Source: [mdop/uev-v2/manage-administrative-backup-and-restore-in-ue-v-2x-new-topic-for-21.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/uev-v2/manage-administrative-backup-and-restore-in-ue-v-2x-new-topic-for-21.md)
* Service: **unspecified**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by andreabichsel** [comment]
@justinha Please assign to correct owner

**Comment by Justinha** [comment]
@dardie Thanks for the feedback. We revised the topic to make this point more clear.
