### ISSUE TITLE
ArcSight CEF Mappings 

### ISSUE THREAD

**Issue by harveywargo2** [MicrosoftDocs/windows-itpro-docs#6540]
the AlertTime isn't mapped to deviceReciept time in the jsonParser properties file, LastProcessedTime is

from the properties file 
event.deviceReceiptTime=__createOptionalTimeStampFromString(LastProcessedTimeUtc,"YYYY-MM-DDThh:mm:ss.SSSX")

For ArcSight you need add the following to the JSON Parser Properties file to map all the tokenized json fields to CEF 

event.endTime=__createOptionalTimeStampFromString(AlertTime,"YYYY-MM-DDThh:mm:ss.SSSX")
event.sourceProcessName=ComputerDnsName
event.destinationServiceName=AlertId
event.destinationProcessId=AlertPart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e9ec713-7d81-465c-e7e0-9ecb4fc5024e
* Version Independent ID: 2c2f1ed7-4211-5e8c-ce7a-624a92edecd2
* Content: [Microsoft Defender ATP detections API fields - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/api-portal-mapping#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/api-portal-mapping.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/api-portal-mapping.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by nam31** [comment]
Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)

Thank you.

**Comment by MaratMussabekov** [comment]
Hello @harveywargo2 ,
could you please provide more details?
**the AlertTime isn't mapped to deviceReciept time in the jsonParser properties file, LastProcessedTime is** - is it possible to share this file?
I do not have experience with ArcSight, but LastProcessedTime usually take place later than AlertTime, so it looks more logically to map AlertTime  with DeviceRecieptTime
Thank you

**Comment by Reeced40** [comment]
@harveywargo2 thank you for reaching out. Please can you see the comment above and provide more details so I can investigate further.

**Comment by nam31** [comment]
@harveywargo2 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
