### ISSUE TITLE
lastUpdateTime

### ISSUE THREAD

**Issue by harveywargo2** [MicrosoftDocs/windows-itpro-docs#6541]
lastUpdateTime has the same description as firstEventTime....I don't believe this is correct

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46b14e18-d381-9085-8f1e-1b320ddb03d7
* Version Independent ID: c4551e26-d4ef-078c-28b1-7dc774ad2378
* Content: [Get alerts API - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/alerts)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/alerts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/alerts.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Good point. I agree. Seeing that the description for `lastUpdateTime` is _identical_ to `firstEventTime`, it is obvious that this must be a copy-paste mistake.

Checking the JSON output example below, I notice that the date & timestamp for `lastUpdateTime` happens even after `lastEventTime`, which means that it should probably have a description saying something about a more recent and later check than the last event. I am uncertain how it should be phrased exactly to be correct.

**Comment by illfated** [comment]
Maybe it could be something quite simple, like for example
- The date and time (in UTC) the alert was last updated.

Oh well. I will give it a shot to see if the suggestion above will be acceptable. 
At least it should attract the attention of the page author or manager.

**Comment by harveywargo2** [comment]
From what I have been seeing in the data, I have retrieved about 5K alert events from our subscription.  

It looks like lastUpdateTime is most likely tied to a MDATP azure Processing Time Stamp.  This is just a guess and would need verification from the MDATP team.

For Example firstEvent & lastEvent is data on the endpoint/device.  When that data makes it to azure it gets a different timestamp lastUpdateTime.  THis timestamps is normally used by log/data collectors to make sure they are retrieving the most recent data. 

Hope this helps

**Comment by illfated** [comment]
Fair enough, thank you very much for the feedback. You are welcome to visit the PR I am opening to suggest modifications.

**Comment by illfated** [comment]
OK, I will digest your feedback for a while and see if I can come up with an even more relevant description. It would surely help a lot if either the page author or a topic expert could provide an accurate and precise description to insert there. We will just have to wait and see.

**Comment by mjcaparas** [comment]
Thank you for your feedback. I have verified with the team. 
The description should be: "The time the alert was last updated"

**Comment by harveywargo2** [comment]
Thank you for the update

**Comment by illfated** [comment]
Thank you for replying here in the issue ticket. As you can see in my PR, I have suggested the following main change to the document:
```diff
- lastUpdateTime | Nullable DateTimeOffset | The first occurrence of the event that triggered the alert on that machine.
+ lastUpdateTime | Nullable DateTimeOffset | The date and time (in UTC) the alert was last updated.
```
My suggestion was based on the JSON output, showing that it is the most recent event, as well as the other description line saying
```
alertCreationTime | Nullable DateTimeOffset | The date and time (in UTC) the alert was created.
```
