### ISSUE TITLE
Server 2016 Servicing Stacks and Creating a Image

### ISSUE THREAD

**Issue by HBogart26** [MicrosoftDocs/windows-itpro-docs#6543]
I am in the process of creating a new Image for Server 2016 and quite frankly, this model of patching does not work at all the way it is supposed to.  I am using the Server 2016 DVD Media to create a Image with all the latest patches in it and yet every time I do this (every couple months), the process fails to work the same way as it did in previous months.  I find myself in a situation where it's not patching at all!  I then have to manually add / install Servicing Stacks (all them for some god unknown reason) and it still doesn't patch using WSUS.  I have installed the Servicing Stack KB4550994 and yet, every Cumulative Update shows as not applicable.....  This is beyond frustrating, fix the patching in Windows!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b706f0af-d504-a8ca-7c38-b8bb9283bfad
* Version Independent ID: 14f31acf-9f47-59a6-269f-62ab249fe560
* Content: [Servicing stack updates (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates#feedback)
* Content Source: [windows/deployment/update/servicing-stack-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/servicing-stack-updates.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
I'm sorry this process isn't working well for you and will refer the owner of the feature to this issue.

**Comment by nam31** [comment]
Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)

Thank you.
