### ISSUE TITLE
Can you please also depreciate XPS Printer/Fax Printer/IE11 as being installed by default?

### ISSUE THREAD

**Issue by 29039** [MicrosoftDocs/windows-itpro-docs#6547]
XPS Printer - confusing to users, not needed in favour of PDF, so I remove it from "Turn Windows features on or off" in Programs and Features.

Fax Printer - Same, and nobody even has a 56k modem anymore to even make use of it

IE11 - Security bugs are taking longer to get fixed and it's not even needed for 99% of users. I'm not saying get rid of it completely (compatibility and all that), just take away the icon - just like it does from "Turn Windows features on or off"

If anyone actually needs these things, they can just add it again in the Turn Windows features on or off.

Perhaps a similar thing to removing SMB1 support, where it is prefaced with "<x feature> Automatic Removal" for a while before actually doing it.

**Comment by 29039** [comment]
This comment was in reference to this: https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-deprecated-features

**Comment by 29039** [comment]
Also it's crazy that XPS Viewer has been removed from being installed by default but the XPS Document Writer has not.

**Comment by mypil** [comment]
@29039 - Thank you for providing feedback.

Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the **[Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)**. You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
