### ISSUE TITLE
IMPORTANT: Equivalent GP path, GP name, GP Element is missing for every setting in this document 

### ISSUE THREAD

**Issue by yogeshasalkar** [MicrosoftDocs/windows-itpro-docs#6548]
We should add the equivalent GP information for every setting, just like settings in PolicyCSP have equivalent GP information. It will help to find the respective intune setting for GP.

We should add both the GP path for the setting
Computer config -> Windows setting -> Security setting -> Windows firewall with advanced security
Computer config -> Administrative templates -> Network -> Network connections -> Windows defender firewall

The absence of the GP paths makes the system impossible to decide whether the conflict is happening when same setting configured via Intune and GP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfea4e59-ec8c-cbdf-a039-23612c2266a5
* Version Independent ID: 7058544b-7ef2-a398-366a-cf71520aa9d8
* Content: [Firewall CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/firewall-csp)
* Content Source: [windows/client-management/mdm/firewall-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/firewall-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
@yogeshasalkar Thank you for providing feedback.
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
Thank you for your contribution to make the docs better! Much appreciated!
