### ISSUE TITLE
Is it possible to use this without also subscribing to Cyren?

### ISSUE THREAD

**Issue by mtwelve** [MicrosoftDocs/windows-itpro-docs#6549]
Hello,

The article doesn't make it clear if there is a native list of web filtering categories or if it is a requirement that we utilise the services of Cyren.

Can you clarify if this can be utilised without also subscribing to Cyren?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d1d825-ab12-2f37-b692-5266487ef16f
* Version Independent ID: fef750ac-311b-28b4-1661-16385997815b
* Content: [Web content filtering - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/web-content-filtering)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/web-content-filtering.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/web-content-filtering.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Hi @mtwelve, currently one of the requirements is a partner license, and the only available partner right now is Cyren.
