### ISSUE TITLE
Problem in dark mode

### ISSUE THREAD

**Issue by matifali** [MicrosoftDocs/windows-itpro-docs#655]
Can't read tha caption of the figure in dark mode.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042d10ec-8f56-909c-9f66-f4c1363373b9
* Version Independent ID: 3b72e026-16ea-e9bf-a48b-abb42382ddab
* Content: [Perform an in-place upgrade to Windows 10 with MDT (Windows 10)](https://docs.microsoft.com/en-gb/windows/deployment/upgrade/upgrade-to-windows-10-with-the-microsoft-deployment-toolkit)
* Content Source: [windows/deployment/upgrade/upgrade-to-windows-10-with-the-microsoft-deployment-toolkit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-to-windows-10-with-the-microsoft-deployment-toolkit.md)
* Service: **unspecified**
* GitHub Login: @mtniehaus
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@matifali - are you still having this issue? Which caption & figure are you referring to? 

I tested it in my end and it works well in dark mode, I am able to read the caption on all figures.

**Comment by illfated** [comment]
It is not the caption, but the individual unit names in this image:


![](https://docs.microsoft.com/en-gb/windows/deployment/images/upgrademdt-fig1-machines.png)

Figure 1. The machines used in this topic.
***
The background in the image is transparent, making the names **DC01** / **MDT01** / **PC001** melt into the black background.

**Comment by mypil** [comment]
@illfated - Thanks for pointing this out. Let me see if I can get a PR created to resolve this issue.

**Comment by illfated** [comment]
Looks like it may take a few more hours before the PR change migrates to the docs.microsoft.com page.
The [updated (new) file](https://raw.githubusercontent.com/MicrosoftDocs/windows-itpro-docs/master/windows/deployment/images/upgrademdt-fig1-machines.png) looks fine with black background now:
(https://raw.githubusercontent.com/MicrosoftDocs/windows-itpro-docs/master/windows/deployment/images/upgrademdt-fig1-machines.png)

**Comment by mypil** [comment]
@matifali - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by matifali** [comment]
Yes it's good now. The issue is resolved.
