### ISSUE TITLE
 powershell.exe.config permissions

### ISSUE THREAD

**Issue by agressiv** [MicrosoftDocs/windows-itpro-docs#6550]
RunConfig.bat is attempting to overrwrite powershell.exe.config in C:\Windows\System32\WindowsPowerShell\v1.0.  Even LocalSystem does not have rights to overwrite this file, nor should we be overwriting it.

Consider another means of getting your "useLegacyV2RuntimeActivationPolicy" setting into the runtime, or fix the DLL so that it doesn't need it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb8c41f-5e79-8310-3a2c-e2465d6aac96
* Version Independent ID: f517bcb0-3833-08b3-f3f4-75a732b3c629
* Content: [Update Compliance Configuration Script - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-configuration-script#feedback)
* Content Source: [windows/deployment/update/update-compliance-configuration-script.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-configuration-script.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Thanks for pointing this out. @cinglis-msft can look into this issue? Seems to be a script issue, not a doc issue.

**Comment by cinglis-msft** [comment]
Thanks @agressiv will look into this

**Comment by nam31** [comment]
It was fixed by https://github.com/MicrosoftDocs/windows-itpro-docs/commit/83d9c2cc178f3fe7031e74bcc83e009f19e57109#diff-3adddcf5d18f65ff717f780a424f2435,
