### ISSUE TITLE
Feedback on page for the surface pro X App

### ISSUE THREAD

**Issue by emartin133** [MicrosoftDocs/windows-itpro-docs#6553]
The original title of the X app was sufficient from it original description yet when I tapped on more info none of what was on that next page was any different than it's original information. Also it gave me none of what I was looking for such a GB TB Ghtz. So why bother placing something for me to view if it tell me no more than you already gave from first glance. A waste of my time which means you are looking for a sales pitch but what you got was irritated potential buyer. Now you really need to work hard to capture me w/another product for at least a grand.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 256acd69-4a6d-0475-6089-fe6c92c0b253
* Version Independent ID: 837f26b2-db23-10ba-74bd-d094e6767ad9
* Content: [Surface Pro X app compatibility - Surface](https://docs.microsoft.com/en-us/surface/surface-pro-arm-app-performance)
* Content Source: [devices/surface/surface-pro-arm-app-performance.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-pro-arm-app-performance.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @CoveMiner
* Microsoft Alias: **v-jokai**

**Comment by mypil** [comment]
@emartin133 - Thank you for providing feedback.

Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the **[Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)**. You might find others have made a similar request that you can add to, or you can open a new one.  

Thank you for your contribution to make the docs better! Much appreciated!
