### ISSUE TITLE
Traffic filter sentence incomplete

### ISSUE THREAD

**Issue by klishb** [MicrosoftDocs/windows-itpro-docs#6556]
On this page https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-security-features#traffic-filters

This sentence is incomplete:

"Network admins to effectively add interface specific firewall rules on the VPN Interface"

It should probably read:

"Traffic filters allow network admins to effectively add interface specific firewall rules on the VPN Interface"

**Comment by klishb** [comment]
There is also a missing space after the sentence.

**Comment by illfated** [comment]
Nice, well spotted. Thank you for the suggestion also.
Maybe there is an alternate way to form the sentence, making the beginning and end stay the same, for example:
> Network admins can use Traffic Filters to effectively add interface specific firewall rules on the VPN Interface.

**Comment by klishb** [comment]
That works too.

**Comment by illfated** [comment]
There you go. Feel free to comment in the PR if you find more material to improve in that document.
