### ISSUE TITLE
Autopilot User Driven - Login to AAD page

### ISSUE THREAD

**Issue by KarbonX1** [MicrosoftDocs/windows-itpro-docs#6557]
The AAD sign in page now includes an option that says "Not a XXXX company device?" and if you choose that, it will allow you to completely bypass the autopilot process. When was this added and how to turn that option off?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2434dfb6-ac9a-4ba1-a681-88786c87010a
* Version Independent ID: 47e7470e-ab97-9917-04aa-4ec08a178af5
* Content: [Windows Autopilot User-Driven Mode - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/user-driven#feedback)
* Content Source: [windows/deployment/windows-autopilot/user-driven.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/user-driven.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by MaratMussabekov** [comment]
Hello @KarbonX1,
you can turn it off by configuring the "Automatically setup for work or school" option in autopilot profile.
Source: https://docs.microsoft.com/windows/deployment/windows-autopilot/profiles
Thank you

**Comment by mypil** [comment]
@KarbonX1 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @MaratMussabekov so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
