### ISSUE TITLE
Cost

### ISSUE THREAD

**Issue by m-xen** [MicrosoftDocs/windows-itpro-docs#6558]
It seems very difficult, or impossible in my experience, to find out the cost after the 60 day trial presumably without signing up for the trial. Cyren don't even make mention of ATP on their site, this all seems very beta, is that the case? Will there be more partners for URL filtering in future?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d1d825-ab12-2f37-b692-5266487ef16f
* Version Independent ID: fef750ac-311b-28b4-1661-16385997815b
* Content: [Web content filtering - Windows security](https://docs.microsoft.com/en-gb/windows/security/threat-protection/microsoft-defender-atp/web-content-filtering#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/web-content-filtering.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/web-content-filtering.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Hi @m-xen , this feature is currently being tested and is not yet commercially released (see disclaimer on top of the page). Your comments on confusion surrounding cost and partnerships will be taken into account, thank you!
