### ISSUE TITLE
Reference Service Releases

### ISSUE THREAD

**Issue by danjpadgett** [MicrosoftDocs/windows-itpro-docs#656]
The documentation makes no mention of the MDOP servicing releases. Furthermore this page explicitly lists support for Microsoft SQL Server 2016 SP1, this support is only possible with the March 2017 servicing release. 
https://support.microsoft.com/en-ie/help/4014009/march-2017-servicing-release-for-microsoft-desktop-optimization-pack

The entire MDOP section should make better mention of servicing releases in general, in which order they should be installed and which release is the latest. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bd86f5e-6388-d226-2460-997fc24945d9
* Version Independent ID: aa827a7d-725a-a5d0-f6aa-3f1df8cc310a
* Content: [MBAM 2.5 Supported Configurations](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/mbam-25-supported-configurations)
* Content Source: [mdop/mbam-v25/mbam-25-supported-configurations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/mbam-25-supported-configurations.md)
* Service: **unspecified**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by andreabichsel** [comment]
@justinha Please assign to correct owner.

**Comment by xstaindx** [comment]
July 2018 Servicing Release:

https://support.microsoft.com/en-us/help/4340040/july-2018-servicing-release-for-microsoft-desktop-optimization-pack

**Comment by mypil** [comment]
@danjpadgett - the link shared by xstaindx contains the latest Servicing Release. From our understanding the issue you raised has been answered. If you feel it hasn't been answered please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot close
