### ISSUE TITLE
Does "Deploy Windows Defender Application Control" applies to EFI Systems? 

### ISSUE THREAD

**Issue by joseluiscc** [MicrosoftDocs/windows-itpro-docs#6563]
Hi,

In EFI systems the file SIPolicy.p7b should be located in EFI System partition/Microsoft/Boot. 

Does "Deploy Windows Defender Application Control" applies to EFI Systems? 

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d01189f-01b4-d959-4490-3b65c13bf7a1
* Version Independent ID: e9f06ae5-7f63-ce99-64a0-048306c6c1d6
* Content: [Deploy WDAC policies via Group Policy (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/deploy-windows-defender-application-control-policies-using-group-policy#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/deploy-windows-defender-application-control-policies-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/deploy-windows-defender-application-control-policies-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@joseluiscc . That file is configured as baae policy which allows to boot signed and unsigned files. 
But you can create new WDAC policy and then convert into .bin file, and then deploy in gpo , after wards policy will converted in  .p7b. . Then you copy the file to EFI partition. 

Note. don't try to use in current system. Try to test on reference computer

**Comment by joseluiscc** [comment]
Thanks..!
