### ISSUE TITLE
Wrong information

### ISSUE THREAD

**Issue by j3atuhan** [MicrosoftDocs/windows-itpro-docs#6564]
The fact that limited subset is available is wrong or the above list is incomplete. We enabled at least 2 rules in audit mode that are not listed above with E3 license and they created log entries. 

It is true that you do not get reporting, monitoring and analytics benefits from MS Defender ATP.

Also it conflicts with: 
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction
On that page it says:
"To use the entire feature-set of attack surface reduction rules, you need a Windows 10 Enterprise license. With a Windows E5 license, you get advanced management capabilities including monitoring, analytics, and workflows available in Microsoft Defender Advanced Threat Protection, as well as reporting and configuration capabilities in the Microsoft 365 security center. These advanced capabilities aren't available with an E3 license, but you can still use Event Viewer to review attack surface reduction rule events."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d747289-63b2-f71a-b40c-31b52982215c
* Version Independent ID: b52f6593-03f2-aa57-ec0e-eaef560dcaf0
* Content: [Use attack surface reduction rules in Windows 10 Enterprise E3 - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction-rules-in-windows-10-enterprise-e3#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction-rules-in-windows-10-enterprise-e3.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction-rules-in-windows-10-enterprise-e3.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by VLG17** [comment]
@j3atuhan The prerequisite for using the entire feature-set of attack surface reduction rules is a valid Windows 10 Enterprise license. Not E3 or E5.

E5 will give you on top of that advanced management capabilities, which you don't get with E3 (although you can still use Event Viewer to review attack surface reduction rule events).

So you being able to enable rules with an E3 licese in perfectly fine. I assume you also have Windows 10 Enterprise, which gives you this ability.

**Comment by nam31** [comment]
@j3atuhan Please let us know if you still have any question regarding the issue you have raised initially.

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
