### ISSUE TITLE
Could you please add few sample xml code for this CSP?

### ISSUE THREAD

**Issue by HaoHoo** [MicrosoftDocs/windows-itpro-docs#6565]
Is that possible to add some sample xml code as reference? Just like Office CSP page displayed provide 1 more sample code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2db74c5-16f9-22d3-07e8-043d393fdcc4
* Version Independent ID: 4bdccadf-7f33-ee14-7ada-aca012866794
* Content: [WiredNetwork CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/wirednetwork-csp)
* Content Source: [windows/client-management/mdm/wirednetwork-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/wirednetwork-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@HaoHoo - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/b4fbb889fe528ceeac8b9224430c066db6434ec4. 


Thank you for your contribution to make the docs better! Much appreciated!
