### ISSUE TITLE
SubmitSamplesConsent should be SendSafeSamples or SendAllSamples

### ISSUE THREAD

**Issue by BugMeNot114514** [MicrosoftDocs/windows-itpro-docs#6566]
In the Use PowerShell section says let it set to AlwaysPrompt.
However in the Use Intune section and in the Use Group Policy says,
> Setting to Always Prompt will lower the protection state of the device.

This is a contradiction. Use Powershell tells us to reduce safety.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f8ccc01-1b04-e443-ef75-6ffe6c866dd5
* Version Independent ID: fa2eaa0f-db04-785a-3894-8244947b9cd5
* Content: [Enable cloud-delivered protection in Windows Defender Antivirus - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thank you, @BugMeNot114514, for raising this issue. I'll look into it.

**Comment by mypil** [comment]
@BugMeNot114514 - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/72274729032c9cc923d67cc25413c7c702b0dead. 


Thank you for your contribution to make the docs better! Much appreciated!
