### ISSUE TITLE
Add Cert in certificate Authority

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/windows-itpro-docs#657]
One thought on this page is to add the actual steps for publishing a certificate. I'm fairly certain there should be a step that involves right clicking "Certificate Templates" in the Certification Authority window -> New -> Certificate Template to Issue -> Domain Controller Authentication (Kerberos).

I would also suggest altering the title for this page and this one (https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-pki) so that people like me don't get confused when deploying this to their organization and they go to search for one page in Google and find the other, and then do the wrong steps :)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800b8090-65a9-da9f-a930-1f80dc9f2c2d
* Version Independent ID: b4495b6a-4ca5-7aa1-7964-ef6e19275c4e
* Content: [Configuring Hybrid key trust Windows Hello for Business - Public Key Infrastructure (PKI)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki#publish-certificate-templates-to-a-certificate-authority)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md)
* Service: **unspecified**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by Justinha** [comment]
@thedrum808 Thanks for the feedback. Did you have a suggestion for the title?

**Comment by MikeStephens-MS** [comment]
FIXED: Added the steps to the page.  Also updated the applies to section to include Key trust and certificate trust, respectively

**Comment by thedrum808** [comment]
@justinha - just something that reflects that it deals with Key Trust and not Cert trust. Right now the titles of the Cert trust page and Key trust page are the same, which can be confusing when actually deploying. 

And thanks Mike!
