### ISSUE TITLE
Machine tags

### ISSUE THREAD

**Issue by aggerritsen** [MicrosoftDocs/windows-itpro-docs#6570]
Is there a method for setting machine tags for MDATP at linux machines, like for Windows this is done using registry keys? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbd62860-4e23-8fe8-d23a-51893c1ccf2a
* Version Independent ID: d487bc8c-4ad8-0ffe-07cf-4c1cee4fd3be
* Content: [Microsoft Defender ATP for Linux resources - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-resources#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @aggerritsen , 
for linux machines, you can only set tags using portal (like described [here](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/machine-tags))
You can set tags on OS level only for Windows machines (via registry keys)
Thank you

**Comment by aggerritsen** [comment]
Hi Marat,

Thanks for your answer. Is this a roadmap item that may be available in the near future?

Kind regards, Arjen

**Comment by MaratMussabekov** [comment]
Hello, unfortunately I do not have such information, you can see the planned changes on the [roadmap portal](https://www.microsoft.com/en-us/microsoft-365/roadmap)
Thank you

**Comment by aggerritsen** [comment]
Hi Marat,

It turns out that on Linux the mdatp agent does actually have an option to set the tag, stating that ireflects in the portal:

```
mdatp --edr
EDR option categories:

--edr options:
  --groupids arg            Configure group Ids for the device
  --early-preview arg       Enable/disable EDR early preview
  --set-tag tag name value  Set device tags, specify the tag name and its
                            desired value, Current supported tags: GROUP -
                            allows to set machine tag (reflected in the portal)
  --remove-tag arg          Remove device tag, specify the tag to remove
```

The result being:
```
mdatp --health
appVersion                              : "100.90.70"
cloudAutomaticSampleSubmission          : true
cloudDiagnosticEnabled                  : true
cloudEnabled                            : true
definitionsUpdated                      : "1589785068245"
definitionsUpdatedMinutesAgo            : 121
definitionsVersion                      : 80537
edrDeviceTags                           : [{"key":"GROUP","value":"MON18"}]
edrEarlyPreviewEnabled                  : "disabled"
edrMachineId                            : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
engineVersion                           : "3.0"
healthy                                 : true
licensed                                : true
logLevel                                : "info"
machineGuid                             : "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
orgId                                   : "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
realTimeProtectionAvailable             : true
realTimeProtectionEnabled               : true
releaseRing                             : "InsiderFast"
```

Is seems therefore that there is a possibility to set a tag on the agent, however it is not showing up in het portal at securitycenter.windows.com.

Could you please tell me what the purpose of this tag is? What would be the appropriate value of EDR settings, since I can not find any documentation about these EDR settings. 

Kind regards,
Arjen

**Comment by MaratMussabekov** [comment]
Hello @aggerritsen,
unfortunately, I do not have much information about this either, as the info wasn't published.
This tag is used to [manage machine groups](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/machine-groups).
Have you tried following:
1. remove the tag you added
2. add another Group tag using portal
3. check using **mdatp --health** whether tag is seen in console.

Dear @dansimp, could you please advise?

Thank you

**Comment by mypil** [comment]
@aggerritsen - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @MaratMussabekov so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Comment by jsnguyenwork** [comment]
hey @aggerritsen ,
Did you ever figure out how to tag linux machines and have it show up in security center?
