### ISSUE TITLE
WDDG & WDCG hardware readiness tool: typo & locale issues

### ISSUE THREAD

**Issue by illfated** [MicrosoftDocs/windows-itpro-docs#6574]
As discussed in ticket #5972 (even if that ticket is closed), the script on this page stops working in localized versions of Windows (Dutch mentioned in ticket #5972 specifically). This is caused by the difference in how the strings `64-bit` and `32-bit` occur in non-English localized versions of Windows.

The suggestion in ticket #5972 is to add some regex functionality inside `function CheckOSArchitecture`, like this:

```PowerShell
function CheckOSArchitecture
{
    $OSArch = $(gwmi win32_operatingsystem).OSArchitecture.ToLower()
    Log $OSArch 
    if($OSArch -match ("64\-?\s?bits?"))
    {
        LogAndConsoleSuccess "64 bit archictecture"
    }
    elseif($OSArch -match ("32\-?\s?bits?"))
    {
        LogAndConsoleError "32 bit  archictecture"   
        $DGVerifyCrit.AppendLine("32 Bit OS, OS Architecture failure.") | Out-Null
    }
    else
    {
        LogAndConsoleError "Unknown architecture"
        $DGVerifyCrit.AppendLine("Unknown OS, OS Architecture failure.") | Out-Null
    }
}
```

The word "archictecture" is also misspelled, twice in that function, luckily only in text strings used for logging.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c12e9c4a-af05-9ecd-a791-ac89aa43787c
* Version Independent ID: 76517523-a960-c5fb-ce76-2c3efe642f37
* Content: [Windows Defender Device Guard and Windows Defender Credential Guard hardware readiness tool - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg-readiness-tool)
* Content Source: [windows/security/identity-protection/credential-guard/dg-readiness-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/dg-readiness-tool.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @SteveSyfuhs
* Microsoft Alias: **stsyfuhs**

**Comment by illfated** [comment]
May as well just mention related issues from the other page, since they are all related to the **Windows Defender Device Guard and Windows Defender Credential Guard hardware readiness tool** : 
#5690 #5723 #6054 #6055 (open issues)

The main issue reported here (and described in the closed ticket #5972 ) is possibly related to an unresolved question in the closed ticket #4679 .

**Comment by RAJU2529** [comment]
Great sir. Author plesse accept his PR

**Comment by illfated** [comment]
Please note that the author of the script modification is @RvdHout (Ruud van den Hout).
