### ISSUE TITLE
Configure WIP policies within MEMCM without Azure AD and Intune?

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/windows-itpro-docs#6577]
Everything is In the title. Can we create WIP policies in SCCM without having configured Azure AD and Intune?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f140d60-97d3-8ac3-4d77-a4fb2acbb102
* Version Independent ID: 49560e13-d315-dcc8-8590-b0fbc1128da7
* Content: [Create and deploy a Windows Information Protection (WIP) policy using Microsoft Endpoint Configuration Manager (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-configmgr#feedback)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-configmgr.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/create-wip-policy-using-configmgr.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @Martony78 ,
no, unfortunately, you cannot do it using SCCM only, you need to have MDM solution (see [prerequisites](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip#prerequisites) for more details)
Thank you

**Comment by Martony78** [comment]
Hi Marat,
The prerequisites you linked says Intune OR Configuration Manager. So yes, we can do it according to the documentation
