### ISSUE TITLE
Connect to WPA2 Enterprise wireless network automatically

### ISSUE THREAD

**Issue by Eiffelsturm** [MicrosoftDocs/windows-itpro-docs#6579]
Background: The Surface Hub 2S is configured to use a wireless network with WPA2 Enterprise security. After a device restart, the Surface is not connected to the wireless network anymore. Now, if someone wants to use the Surface Hub, he had to configure the wireless setting again. Without permission not possible. What is Best practices to avoid this scenario?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 338bd236-6aa7-0716-f797-d69ba3fd502e
* Version Independent ID: cb809e57-811a-6092-b472-b37238eb0ab0
* Content: [Verwaltung des Drahtlosnetzwerks (Surface Hub) - Surface Hub](https://docs.microsoft.com/de-de/surface-hub/wireless-network-management-for-surface-hub)
* Content Source: [devices/surface-hub/wireless-network-management-for-surface-hub.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/wireless-network-management-for-surface-hub.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by Reeced40** [comment]
@OfficeGlobal

**Comment by nam31** [comment]
@Eiffelsturm We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
