### ISSUE TITLE
Explorer vs Edge

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/windows-itpro-docs#6580]
Just how different are the two settings?
Windows Components/Windows Defender SmartScreen/Explorer/Configure Windows Defender SmartScreen

Windows Components/Windows Defender SmartScreen/Microsoft Edge/Configure Windows Defender SmartScreen

I have enabled SmartScreen for Edge via Administrative Templates in Intune, and although my Edge settings are now enforced, I do not see the local group policy changing the configuration values; all remain Not configured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6af7069-ddf7-3f4e-f9fa-75139c92fd0a
* Version Independent ID: c07db982-c7d2-82bd-560b-9d13b4eca026
* Content: [Policy CSP - SmartScreen - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-smartscreen#smartscreen-preventoverrideforfilesinshell)
* Content Source: [windows/client-management/mdm/policy-csp-smartscreen.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-smartscreen.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by beerisgood** [comment]
As the name say, one is for windows explorer and one for Microsoft Edge.

Both do the same but you can config it differently. I guess you get confused with the word "Explorer" and old "Internet Explorer" which is now called Edge.

**Comment by icelava** [comment]
No, I'm not confusing it with Internet Explorer. Rather, I'm confused over the various avenues of configuration through Administrative Templates, Endpoint Protection, Device restrictions configuration profiles that seem to have overlapping boundaries of responsibilities and jurisdiction over the SmartScreen settings. It's very murky regarding the effects/consequences of enabling/disabling one over the other.

**Comment by RAJU2529** [comment]
@icelava .   @beerisgood  is said is correct.  It's for windows explorer and not internet explorer. 
There is separate amdx fils is there for internet explorer.  Check the group policy again.

**Comment by icelava** [comment]
Like I mentioned, I know Explorer refers to Windows Explorer and don't care about Internet Explorer since nobody in the company uses that; the default browser is Microsoft Edge. 

However, there are _three_ separate avenues in Intune to configure SmartScreen settings and it's pretty confusing which of them overlap or control different things.

**Comment by icelava** [comment]
Also, when looking at the source referring document https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-protection-windows-10#microsoft-defender-smartscreen-settings

It states "Microsoft Edge must be installed on the device." but these CSP parameters seem to apply to Windows per se and not concern itself with Edge settings? These documentations are incredibly muddy on what they will or will not affect.

**Comment by icelava** [comment]
To my disappointment, but not unsurprisingly, when I take a direct look at local Group Policy editor, the Windows Defender SmartScreen/Explorer node only shows up
SmartScreen/EnableAppInstallControl
SmartScreen/EnableSmartScreenInShell

In Intune's case,
SmartScreen/EnableSmartScreenInShell
SmartScreen/PreventOverrideForFilesInShell

In Windows Security > App & browser control UI case,
SmartScreen/PreventOverrideForFilesInShell
Browser/AllowSmartScreen

Gosh. How long before these all get in sync?

**Comment by RAJU2529** [comment]
@icelava.  Sir do this open the corresponding admx file in policy definitions folder under windows,. Find the which registry key is configured  by the author.

**Comment by joinimran** [comment]
Hello @icelava - I have gone through this discussion and here is my input regarding this. There are many cases where something is available in intune but may not be available in Windows security manger. Modern Management of Windows 10 with Microsoft Intune also has a set of policies, even policies that are duplicative of Group Policy (where applicable, not all Group Policies are available via MDM or CSP). Windows 10 version 1803 and beyond there is a new Policy CSP setting called ControlPolicyConflict that includes the policy of MDMWinsOverGP, where the preference of which policy wins can be controlled, i.e. Microsoft Intune MDM policy. Based on this you can set up the policies as per business requirements. 

If you are still having any issues while setting up policies. Please open up a support case with Microsoft support to better help you with this.

Thanks
Imran.

**Comment by nam31** [comment]
@icelava Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
If you are still having any issues while setting up policies. Please open up a support case with [Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB) to better help you with this.
Thanks.
