### ISSUE TITLE
References to Scripts

### ISSUE THREAD

**Issue by Petitohead** [MicrosoftDocs/windows-itpro-docs#6583]
There are references to scripts in the document.  Can someone please contact me around these references?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08d16473-db61-23bd-7201-f5d7d6a56cc8
* Version Independent ID: 468238c8-8fb4-3dff-3485-07daab0c7833
* Content: [Onboard to the Microsoft Defender ATP service - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/onboarding?source=docs#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/onboarding.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/onboarding.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by MaratMussabekov** [comment]
Hello @Petitohead ,
files that must be edited are InstallMMA.cmd and ConfiguerOMSAgent.vbs, which are considered to be used during the installation of Microsoft Monitoring Agent
However, the agent installation file I took from the link from [this article](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/onboard-downlevel) doesn't have these scripts, it only has a commandline tool which you need to run and specify Workspace ID and Workspace key as parameters.
As it is shown [here](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/agent-windows#add-a-workspace-using-a-script):
setup.exe /qn ADD_OPINSIGHTS_WORKSPACE=1 OPINSIGHTS_WORKSPACE_AZURE_CLOUD_TYPE=0 OPINSIGHTS_WORKSPACE_ID="<your workspace ID>" OPINSIGHTS_WORKSPACE_KEY="<your workspace key>" AcceptEndUserLicenseAgreement=1

Dear @mjcaparas, could you please confirm that the method of installation of MMA described in [Onboard to the Microsoft Defender ATP service](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/onboarding?source=docs#feedback) is incorrect and method described in [Connect Windows computers to Azure Monitor](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/agent-windows) should be used?

Thank you

**Comment by mypil** [comment]
@mjcaparas - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by mjcaparas** [comment]
Checking with team. Will respond once I get more details.

**Comment by mjcaparas** [comment]
@Petitohead and @MaratMussabekov
Yes, I have confirmed. Please just use the Connect Windows computers to Azure Monitor guidance.

**Comment by mjcaparas** [comment]
Revised content is being rolled out.
