### ISSUE TITLE
Misnamed Group Policy in "Configure access to the Microsoft Store (Windows 10)"

### ISSUE THREAD

**Issue by imlukedewitt** [MicrosoftDocs/windows-itpro-docs#6584]
In the article [Configure access to the Microsoft Store (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/stop-employees-from-using-microsoft-store), the policy for disabling the Windows Store is labeled as "Turn off Store application". The correct name is "Turn off **the** Store application"

This distinction is important for people searching for applied policies. I don't mean to be nitpicky.

**Comment by RAJU2529** [comment]
@denisebmsft . please look in to this issue

**Comment by MaratMussabekov** [comment]
Hello @imlukedewitt ,
yes, you are correct:
![image](https://user-images.githubusercontent.com/48041687/81179111-a69dac80-8fc2-11ea-9d4e-f8975798d890.png)
I will create a PR to fix it in the article.
Thank you

**Comment by mypil** [comment]
@imlukedewitt - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/4878044ecceb386bc067e6da0ee697e3281e0029. 


Thank you for your contribution to make the docs better! Much appreciated!
