### ISSUE TITLE
MSERT (x64) download files-- blocked by Windows Defender

### ISSUE THREAD

**Issue by MSFTEfeedback** [MicrosoftDocs/windows-itpro-docs#6585]
Microsoft is blocking Microsoft. What is the world coming to? Says that the file is not signed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5bb1ce3-9128-5385-4417-d22eb5f8cb77
* Version Independent ID: cb6ba731-a2c2-e9b9-7c3e-db781b1b5222
* Content: [Microsoft Safety Scanner Download - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/safety-scanner-download)
* Content Source: [windows/security/threat-protection/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/safety-scanner-download.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by RAJU2529** [comment]
@MSFTEfeedback . wil you give me the link , so that I try to download In my laptop

**Comment by beerisgood** [comment]
> @MSFTEfeedback . wil you give me the link , so that I try to download In my laptop

He already post the link:
> Content: Microsoft Safety Scanner Download - Windows security

look at top in this site:
Download Microsoft Safety Scanner (32-bit)
Download Microsoft Safety Scanner (64-bit)

**Comment by RAJU2529** [comment]
I have downloaded successfully without problems, keeping windows defender is running with advanced configuration. 
here are the screenshots 

![Capture5](https://user-images.githubusercontent.com/3296790/80872171-ea946700-8ccd-11ea-8e33-69beb3bd7929.JPG)
![Capture6](https://user-images.githubusercontent.com/3296790/80872173-ed8f5780-8ccd-11ea-8034-d54944845c29.JPG)
![Capture7](https://user-images.githubusercontent.com/3296790/80872176-ef591b00-8ccd-11ea-8a99-59f5ba4862f4.JPG)
![Capture8](https://user-images.githubusercontent.com/3296790/80872182-f2540b80-8ccd-11ea-8fc8-ba84ed37b62c.JPG)

**Comment by illfated** [comment]
Download working for me as well. Tested both links, the 32-bit version will not run on my computer (wrong OS architecture).
@MSFTEfeedback : Your download might have been a cached (outdated) version. Clear all your browser cache and try again.
