### ISSUE TITLE
Syntax for IP range is wrong

### ISSUE THREAD

**Issue by HartD92** [MicrosoftDocs/windows-itpro-docs#6590]
Syntax for IP ranges in Intune doesn't allow spaces between the IP addresses, but the documentation shows it with spaces:

"An IPv4 address range in the format of "start address - end address" with no spaces included.
An IPv6 address range in the format of "start address - end address" with no spaces included."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b84a77a5-54c7-22c7-b699-c1414c7cd6a1
* Version Independent ID: f78d7bc3-97c8-d8e9-d4f7-5ea82680c738
* Content: [Create Windows Firewall rules in Intune (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/create-windows-firewall-rules-in-intune)
* Content Source: [windows/security/threat-protection/windows-firewall/create-windows-firewall-rules-in-intune.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/create-windows-firewall-rules-in-intune.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@HartD92 - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/afa320da351fed0e9f7329daa68969b257cb422a. 


Thank you for your contribution to make the docs better! Much appreciated!
