### ISSUE TITLE
"Web & Network Protection" section renamed to "Browser" - please update wording and screenshot 

### ISSUE THREAD

**Issue by SergGu** [MicrosoftDocs/windows-itpro-docs#6594]
The screenshot after "During profile creation, you can review and adjust specific settings on the baseline" is not right. In my "Microsoft Defender ATP baseline" ( Version 3 | Microsoft Defender ATP baseline as recommended by Microsoft | 1 | 03/02/20) there is _NO_ "Web & Network Protection" section. Instead, it is located under "Browser" section. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2246e9c-193b-a110-ca52-2110a6e63631
* Version Independent ID: 7328d4a4-1944-c199-db72-a7e3cd350ae9
* Content: [Increase compliance to the Microsoft Defender ATP security baseline - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-machines-security-baseline#review-and-assign-the-microsoft-defender-atp-security-baseline)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-machines-security-baseline.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-machines-security-baseline.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by mypil** [comment]
@SergGu - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/6f361604294734e2a9277f2ab07ab3b566bea30e. 


Thank you for your contribution to make the docs better! Much appreciated!
