### ISSUE TITLE
Mr.

### ISSUE THREAD

**Issue by IVANSEMKOV** [MicrosoftDocs/windows-itpro-docs#6595]
[Въведете обратна връзка тук]

---
#### Подробни данни за документите

⚠ *Не редактирайте този раздел. Задължително е за docs.microsoft.com ➟ връзка към проблем в GitHub.*

* ID: 7c2156ca-1a17-1024-d1e5-76345970ac2f
* Version Independent ID: 56523413-8547-4e97-3eec-9062b9735c11
* Content: [Policy CSP - Wifi - Windows Client Management](https://docs.microsoft.com/bg-bg/windows/client-management/mdm/policy-csp-wifi)
* Content Source: [windows/client-management/mdm/policy-csp-wifi.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-wifi.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@IVANSEMKOV - Благодаря, че изпратихте отзиви.

Можете ли да споделите какъв конкретен проблем имате с този документ? Наистина ще се радваме, ако можете да помогнете, като предоставите повече подробности относно това, което трябва да бъде редактирано.

[Thank you for submitting your feedback.

Can you share what specific issue you have with this document? We would really appreciate it if you can help by providing more details about what needs to be edited.]

**Comment by illfated** [comment]
@mypil : Nice of you to ask if the user wants to contribute. Seeing that the comment text only says [Vŭvedete obratna vrŭzka tuk] ( [Enter feedback here] ), being the default text from the doc page, I would suggest that this ticket can be seen as a mishap or functionality test by the user, not intended as a problem report or doc improvement suggestion.

(Виждайки, че в текста на коментара се казва само [Въведете отзиви тук], като текстът по подразбиране от страницата на документа, бих предложил този билет да се разглежда като неподправен или функционален тест от страна на потребителя, а не като доклад за проблем или подобрение на документа. внушение.)

**Comment by mypil** [comment]
@IVANSEMKOV - Оценяваме всяка обратна връзка, която подобрява съдържанието в документите на Microsoft, но ние не сме имали отговор от вас, така че ние ще бъде затворена този проблем.

Ако има определена област от документите, които можем да подобрим, моля, не се колебайте да отворите нов проблем, като кликнете върху секцията Обратна връзка на конкретния документ на Microsoft, който се намира в долната част на страницата. Благодаря.

[We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we will be closing this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.]
