### ISSUE TITLE
"D365 Layout should be removed since it's not pre-installed in the factory image any longer" 

### ISSUE THREAD

**Issue by yannisle** [MicrosoftDocs/windows-itpro-docs#6597]
"D365 Layout should be removed since it's not pre-installed in the factory image any longer" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701c58ac-56b3-7578-ce96-c876e133e232
* Version Independent ID: 8a66df2a-4fe7-e889-34d3-c69347b71f16
* Content: [HoloLens 2 hardware](https://docs.microsoft.com/en-us/hololens/hololens2-hardware#feedback)
* Content Source: [devices/hololens/hololens2-hardware.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/hololens2-hardware.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by evmill** [comment]
With the merge of the PR above that mentions this Issue, the Layout app is not longer present on that HL2 hardware page.
https://docs.microsoft.com/en-us/hololens/hololens2-hardware#pre-installed-software 
Closing.
