### ISSUE TITLE
Next generation protection

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/windows-itpro-docs#6598]
Behavior monitoring, Cloud-based protection links are 404.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbabaf85-a345-a91e-f4e2-09c2b7871375
* Version Independent ID: bab57f2f-249a-0fe9-4f4a-93d62ce71670
* Content: [Threat Protection (Windows 10) - Windows security](https://docs.microsoft.com/en-gb/windows/security/threat-protection/)
* Content Source: [windows/security/threat-protection/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/index.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by denisebmsft** [comment]
@icelava thank you very much for letting us know about this. Apologies for the inconvenience. The links are fixed and the changes will be live soon.
