### ISSUE TITLE
No way to download anything from the Store with WSUS configuration

### ISSUE THREAD

**Issue by carloreggiani** [MicrosoftDocs/windows-itpro-docs#6600]
It is still not clear the correlation between WSUS configuration and the ability for clients to download application from our Microsoft Business Store (https://businessstore.microsoft.com): users are still getting error message: "This install is prevented by policy. Ask your admin to enable Windows Update.". Could you add in documentation any clarification about WSUS and Windows Store correlation and configuration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe35c19c-fd29-8405-ad9f-441204812e6b
* Version Independent ID: fc0fe6ce-4b92-3cff-d6fa-c791ba2df466
* Content: [Deploy Windows 10 updates using Windows Server Update Services (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-manage-updates-wsus)
* Content Source: [windows/deployment/update/waas-manage-updates-wsus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-manage-updates-wsus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment]
@carloreggiani . Please check the group policy, there is might SRP as setted to disallowed or 
 Policy is modified to run only specific apps..
Check the all registry key under khlm\ software \policies\ machine   hive

**Comment by VLG17** [comment]
@carloreggiani Are you still getting this error? Did it work in the past, or it never worked in your case?

Did you go through the configuration steps described in the article you mentioned? Did you set the intranet Microsoft update service location to your WSUS FQDN?

You can also check [this article](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc720539(v=ws.10)?redirectedfrom=MSDN), which talks about different environment scenarions and different GPO settings which need to be configured in each case. 

My recommendation is to [open a support case](https://support.microsoft.com/en-us/contactus/) in order for a support engineer to look into this issue and the error you are getting and check your configuration. If the conclusion is that we need to add something to the article in terms of configuration, which is currently missing, we will gladly add it.

**Comment by carloreggiani** [comment]
Hi @RAJU2529 and @VLG17: the WSUS policy are fine for Windows Update from our internal WSUS server.

The problem (I openend also a support ticket about this issue last year, no way to resolve) is the key:

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdateDoNotConnectToWindowsUpdateInternetLocations

If it is settet to 1 (as in our case) there is noway to connect to Microsoft Store, also our Businessstore!
There is no other specific registry setting to manage the access or no to the Store: it is the same for Windows Update.

This behaviour is not documented :(

I hope one day to have a registry key to manage internet access for Windows Update and another to manage internet access to Windows Store!

Meanwhile I suggest to integrate this info in documentation.

Carlo

**Comment by jaimeo** [comment]
@arcarley can you help here?

**Comment by RAJU2529** [comment]
@carloreggiani.    set the  policy 
**Computer configuration\Administrative templates\Windows Components\Windows update\
Specify intranet Microsoft update service location**

with your recommendations.

**Comment by e0i** [comment]
Closing via #7899
