### ISSUE TITLE
System/AllowExperimentation

### ISSUE THREAD

**Issue by yogeshasalkar** [MicrosoftDocs/windows-itpro-docs#6601]
The equivalent Group policy for this setting is 'Windows Components/Data Collection and Preview Builds/Disable pre-release features or settings'. This is not mentioned in this documentation. We should mention ADMX info for the setting System/AllowExperimentation

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c833e5b-0fcf-2ace-a90a-3270286d23a9
* Version Independent ID: 64afbc38-e7cc-fc14-9d57-1cd119b2395d
* Content: [Policy CSP - System - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-system#system-allowexperimentation)
* Content Source: [windows/client-management/mdm/policy-csp-system.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-system.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Closing the issue via the author's comments within the proposed PR as quoted below. Thank you.

> The product team informed that they do not want the ADMX info for this policy to be available in public docs. Thanks!

https://github.com/MicrosoftDocs/windows-itpro-docs/pull/6705#issuecomment-656900341
