### ISSUE TITLE
Turn off Windows Location Provider

### ISSUE THREAD

**Issue by yogeshasalkar** [MicrosoftDocs/windows-itpro-docs#6602]
'Windows Components/Location and Sensors/Windows Location Provider/Turn off Windows Location Provider'  this Group policy can be configured using the OMA-URI './Device/Vendor/MSFT/Policy/Config/Location/EnableLocation'. This documentation is missing the 'Location' settings. We should add a document about 'Location'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebc25b0a-f874-466c-cd89-9b87761cccdd
* Version Independent ID: 30929e17-4818-c0ba-30ad-4599305e6a3a
* Content: [Policy CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-configuration-service-provider)
* Content Source: [windows/client-management/mdm/policy-configuration-service-provider.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-configuration-service-provider.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
The associated PR has been closed via the document author's request. Thank you for engaging with the repository.
