### ISSUE TITLE
Missing "RegisterDNS" entry in the ProfileXML file

### ISSUE THREAD

**Issue by pavelrozenberg** [MicrosoftDocs/windows-itpro-docs#6604]
Hello,

Recently you had added an entry in the XML to allow the VPN connection to register the client's IP address in the company's DNS.
Example:
&lt;VPNProfile&gt;  
	... 
	&lt;AlwaysOn&gt;true&lt;/AlwaysOn&gt; 
	&lt;RegisterDNS&gt;true&lt;/RegisterDNS&gt;
&lt;/VPNProfile&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79add4e0-6997-5b15-542c-be3f1c2b1baf
* Version Independent ID: 47bd5f53-cd36-3205-42b1-6d99c68e9b39
* Content: [VPN profile options (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-profile-options?source=docs)
* Content Source: [windows/security/identity-protection/vpn/vpn-profile-options.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/vpn/vpn-profile-options.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Hello @pavelrozenberg 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
