### ISSUE TITLE
KioskBrowser/BlockedUrlExceptions URL Format

### ISSUE THREAD

**Issue by mkuenzie** [MicrosoftDocs/windows-itpro-docs#6606]
Please provide further details on how to format multiple URLs for the BlockedUrlExceptions CSP.   It is not intuitive for use in something like a Custom Intune configuration profile.

**Comment by mkuenzie** [comment]
I believe I found that I needed to use the literal  instead of the `&#xF000;`

**Comment by e0i** [comment]
@mkuenzie 

Somehow your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thank you.

**Comment by mkuenzie** [comment]
@e0i This is the docs page I'm referencing: https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-kioskbrowser

**Comment by e0i** [comment]
Thank you, Passing this to a contributor for investigation.

**Comment by joinimran** [comment]
Hello @mkuenzie - Thank you for your query on the document. Please note that as of now you can block the URLs as described in the documents you have mentioned. I know this is not an intuitive way. I would request you to raise your voice using the Microsoft User Voice channel. This will help to prioritize the implementation of this feature. 

@e0i - FYI & A Please.

**Comment by illfated** [comment]
@joinimran : F.Y.I. : https://practical365.com/microsoft-decommits-user-voice/

https://practical365.com/
