### ISSUE TITLE
Can we change the title of this page to Poilcy "CSPs" supported by HoloLens 2? It makes it clear because the word Policy alone confuses customers

### ISSUE THREAD

**Issue by yannisle** [MicrosoftDocs/windows-itpro-docs#6610]
Can we change the title of this page to Poilcy "CSPs" supported by HoloLens 2? It makes it clear because the word Policy alone confuses customers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60e0d075-794c-6033-fb13-41727ee2e0fd
* Version Independent ID: cd9c8d26-a91a-95a2-c837-af6b3a32d537
* Content: [Policies supported by HoloLens 2 - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policies-supported-by-hololens2)
* Content Source: [windows/client-management/mdm/policies-supported-by-hololens2.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policies-supported-by-hololens2.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Sounds reasonable. Just note that there are 3 pages linked into 1 by the button selector; they may be edited separately:
- https://docs.microsoft.com/en-us/windows/client-management/mdm/policies-supported-by-hololens2
- https://docs.microsoft.com/en-us/windows/client-management/mdm/policies-supported-by-hololens-1st-gen-commercial-suite
- https://docs.microsoft.com/en-us/windows/client-management/mdm/policies-supported-by-hololens-1st-gen-development-edition

There may also be a need to edit the file names to reflect that same change.

**Comment by illfated** [comment]
The corresponding GitHub page links are as follows:
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policies-supported-by-hololens2.md
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policies-supported-by-hololens-1st-gen-commercial-suite.md
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policies-supported-by-hololens-1st-gen-development-edition.md

**Comment by illfated** [comment]
A relevant question now is whether we should rename the page titles and files for the following pages, to follow the same pattern:
- [**Policies supported by Windows 10 IoT Enterprise**](https://docs.microsoft.com/en-us/windows/client-management/mdm/policies-supported-by-iot-enterprise) (linked with the page below)
- [**Policies supported by Windows 10 IoT Core**](https://docs.microsoft.com/en-us/windows/client-management/mdm/policies-supported-by-iot-core) (linked with the page above)
- [**Policies supported by Microsoft Surface Hub**](https://docs.microsoft.com/en-us/windows/client-management/mdm/policies-supported-by-surface-hub) (stand-alone)
- [**Policies that can be set using Exchange Active Sync (EAS)**](https://docs.microsoft.com/en-us/windows/client-management/mdm/policies-that-can-be-set-using-eas) (stand-alone)

**Comment by yannisle** [comment]
I think that’s fair :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by illfated** [comment]
Very good. Thank you. Do you mean also those 6 other pages, or just as it is now?

**Comment by yannisle** [comment]
Sorry I wasn’t clear enough - I recommend changing all pages to include the “CSP” word in the title.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by illfated** [comment]
PR #6627 is now updated as requested and should be complete. Oddly enough, only 1 out of all 9 files showed up as a combined file rename & diff view.
