### ISSUE TITLE
InternetExplorer CSP only?

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/windows-itpro-docs#6611]
Why doesn't this page mention the Browser CSP (although apparently for Edge ver 45 and earlier), the administrative template settings for Edge ver 77 and beyond, and the SmartScreen CSP?

All these silos of documentation can't seem to explain a proper differntiation between browser (Edge) level SmartScreen vs OS (Windows Explorer) level SmartScreen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5413195-c0e2-99e4-5d82-6bffdcbbddb9
* Version Independent ID: b8cef753-139b-0098-ed30-63cca8d5b8b9
* Content: [Available Microsoft Defender SmartScreen Group Policy and mobile device management (MDM) settings (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-available-settings#mdm-settings)
* Content Source: [windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-available-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-available-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
@icelava - Thank you for your feedback. Upon reviewing the document all of the settings are mentioned and those are not dependent on Edge version but Windows 10 version. Most of the settings are supported with Windows 10 version 1607 and later.

Thanks
Imran.

**Comment by e0i** [comment]
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation.

Thanks.
