### ISSUE TITLE
Black background not appearing in Mixed reality capture (MRTK)

### ISSUE THREAD

**Issue by Doberman0** [MicrosoftDocs/windows-itpro-docs#6613]
Having created an application in Unity for the Hololens 1 and setting the skybox to be visible in the Skybox settings, I am able to now see the sky (including the night sky - a black background with white dots representing stars) when using the application. However, when recording a mixed reality video (as per the instructions here at https://docs.microsoft.com/en-us/hololens/holographic-photos-and-videos#capture-a-mixed-reality-video) the night sky is not captured in the video and you can only see objects in the night sky on black surfaces (while the video is recording, the application still renders the night sky normally). You can see the result of a video capture here: https://www.youtube.com/watch?v=8OCIytZaQKE&t=30s from 1:59-2:03 on the black TV screen.

Why is the night sky being rendered in the application, but not in the video? Moreover, is there a way to record the video with the black background/night sky in it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9080af-0e7a-ab5c-fece-c5d3ff8fad57
* Version Independent ID: bbef2a13-2f22-90ef-47fc-ec4d7c75ad80
* Content: [Capture and manage mixed reality photos and videos](https://docs.microsoft.com/en-us/hololens/holographic-photos-and-videos#capture-a-mixed-reality-video)
* Content Source: [devices/hololens/holographic-photos-and-videos.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/holographic-photos-and-videos.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by evmill** [comment]
First off I think you should file a bug via Feedback Hub which directly goes to the HoloLens devs. 
Second, you might get some clearer answers either from the [MRTK ](https://github.com/Microsoft/MixedRealityToolkit-Unity/issues)section or perhaps [unity forums](https://forum.unity.com/forums/windows-mixed-reality.102/). Providing the repro project to Unity will be helpful.
Also if you're looking for faster communication from other Devs, you probably want to check out the [HoloDevelopers Slack Channel](https://holodevelopersslack.azurewebsites.net/)

**Comment by e0i** [comment]
Closing via [Evan's](https://github.com/evmill) [comment](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6613#issuecomment-622015789).
