### ISSUE TITLE
Add and manage machine tags using the portal

### ISSUE THREAD

**Issue by mahybabu** [MicrosoftDocs/windows-itpro-docs#6618]
New Tag option is not showing under Manage Tags option, It's just showing a search box.
Is that step number 3 under the section 'Add and manage machine tags using the portal' right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b42e708-e334-d434-bcc9-e1860ebb36b3
* Version Independent ID: 92e251c5-8613-ce97-9569-02404c9a466a
* Content: [Create and manage machine tags - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/machine-tags)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/machine-tags.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/machine-tags.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by MaratMussabekov** [comment]
Hello @mahybabu ,
It shows search box:
![image](https://user-images.githubusercontent.com/48041687/82184863-be99f800-9901-11ea-955f-3227844b154e.png)
Then, when you start to type the name of new tag, it suggests you to create a new tag:
![image](https://user-images.githubusercontent.com/48041687/82184916-d83b3f80-9901-11ea-8355-15095039575b.png)
Thank you

**Comment by mahybabu** [comment]
Thanks, I have to type to see the option 'Create new'.
