### ISSUE TITLE
Define Enlightened apps on WIP

### ISSUE THREAD

**Issue by DuyYuei** [MicrosoftDocs/windows-itpro-docs#662]
Hi team,
I have a problem , when i define enlightened apps : Office 2016 (word, excel, powerpoint..) and deploy Windows Information Protection. It is not work. Office 2016 apps still status **Personal**

Here is a code when i try use applocker and export file xml

{ AppLockerPolicy Version="1"
  RuleCollection Type="Appx" EnforcementMode="NotConfigured" />
  RuleCollection Type="Dll" EnforcementMode="NotConfigured" />
  RuleCollection Type="Exe" EnforcementMode="NotConfigured">
    FilePathRule Id="921cc481-6e17-4653-8f75-050b80acca20" Name="(Default Rule) All files located in the Program Files folder" Description="Allows members of the Everyone group to run applications that are located in the Program Files folder." UserOrGroupSid="S-1-1-0" Action="Allow">
      Conditions>
        FilePathCondition Path="%PROGRAMFILES%\*" />
      /Conditions>
    /FilePathRule>
    FilePathRule Id="a61c8b2c-a319-4cd0-9690-d2177cad7b51" Name="(Default Rule) All files located in the Windows folder" Description="Allows members of the Everyone group to run applications that are located in the Windows folder." UserOrGroupSid="S-1-1-0" Action="Allow">
      Conditions>
        FilePathCondition Path="%WINDIR%\*" />
      /Conditions>
    /FilePathRule>
    FilePathRule Id="fd686d83-a829-4351-8ff4-27c7de5755d2" Name="(Default Rule) All files" Description="Allows members of the local Administrators group to run all applications." UserOrGroupSid="S-1-5-32-544" Action="Allow">
     Conditions>
        FilePathCondition Path="*" />
      /Conditions>
    /FilePathRule>
    FilePublisherRule Id="334ad552-11cd-42f5-8eb8-3cc9497975a8" Name="WINWORD.EXE, in MICROSOFT OFFICE 2016, from O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      Conditions>
        FilePublisherCondition PublisherName="O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US" ProductName="MICROSOFT OFFICE 2016" BinaryName="WINWORD.EXE">
          BinaryVersionRange LowSection="*" HighSection="*" />
        /FilePublisherCondition>
      /Conditions>
    /FilePublisherRule>
  /RuleCollection>
  RuleCollection Type="Msi" EnforcementMode="NotConfigured" />
  RuleCollection Type="Script" EnforcementMode="NotConfigured" />
/AppLockerPolicy>
}

**Comment by DaniHalfin** [comment]
Hi @DuyYuei, there are a couple reason why that might happen. In general, as mentioned [here](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/wip-app-enterprise-context#review-the-enterprise-context), Enlightened apps can change between Work and Personal, depending on the data being touched. 
There are also multiple other things that need to happen to successfully configure and deploy WIP, and it's hard to figure out just from the AppLocker policy XML. 


I would advise that you look through our [test scenarios](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/testing-scenarios-for-wip), as well as the [best practices](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/guidance-and-best-practices-wip). Finally, you can look at the [event logs](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/collect-wip-audit-event-logs) to try and troubleshoot. If you're still having trouble, you should reach out to us through our [support channels](https://www.microsoft.com/en-us/itpro/windows/support).

**Comment by DaniHalfin** [comment]
tagging @Justinha as FYI.

**Comment by Justinha** [comment]
@DaniHalfin Thanks for your reply!

**Comment by DuyYuei** [comment]
Hi **@DaniHalfin** i will try define by DESKTOP APPS but it not work. How i can define office 2016 Enlightened apps
Thank you
