### ISSUE TITLE
Confusing "Note" box regarding path entries on UEFI systems

### ISSUE THREAD

**Issue by ferdnyc** [MicrosoftDocs/windows-itpro-docs#6622]
The "Note" box at list item 2 of the "Verify the integrity..." section reads:

> If the computer is UEFI-based, the **bootmgr** and **winload** entires under {default} will contain an **.efi** extension.

Ignoring the fact that "entries" is misspelled as "entires", that statement isn't even CLOSE to accurate. In fact, it's actively confusing.

Something like the following would seem to be a more correct expression of the point the note is intending to make:

> If the computer is UEFI-based, the **path** value for `{bootmgr}` and `{default}` will contain an **.efi** extension.

To make it even clearer, an example from a typical install might be helpful, e.g.:

```
identifier              {bootmgr}
device                  partition=\Device\HarddiskVolume2
path                    \EFI\Microsoft\Boot\bootmgfw.efi


identifier              {default}
device                  partition=C:
path                    \Windows\System32\winload.efi
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 388514ac-6488-384c-fb86-e8dfd3970a28
* Version Independent ID: 7cd69358-f4bc-67a2-ba27-ea20f0946e32
* Content: [Advanced advice for Stop error 7B, Inaccessible_Boot_Device - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-inaccessible-boot-device)
* Content Source: [windows/client-management/troubleshoot-inaccessible-boot-device.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/troubleshoot-inaccessible-boot-device.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
bootmgfw.efi is located in EFI partition
winload.efi is located in Windows partition

**Comment by ferdnyc** [comment]
> bootmgfw.efi is located in EFI partition
> winload.efi is located in Windows partition

@RAJU2529 Agreed, and that's exactly my concern. Those are _filenames_ (well, the filename parts of file paths), and only one of them is even in `{default}`.

The statement "the bootmgr and winload entries under {default}" is confusing because it appears to be referring to things that don't actually exist, at least not in that form.

**Comment by mypil** [comment]
@ferdnyc - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/9dba213700528f7aae097ab2f0dbfeb9054d2b61. 


Thank you for your contribution to make the docs better! Much appreciated!
