### ISSUE TITLE
Enlightened, unenlightened or WIP friendly status of Microsoft Publisher unclear

### ISSUE THREAD

**Issue by ChineseWelshman** [MicrosoftDocs/windows-itpro-docs#6623]
This page mentions that Office Professional Plus (now Microsoft 365 apps for Enterprise) is enlightened (Word, Excel, PowerPoint, OneNote, and Outlook) except for a specific note that states Access, Project and Visio as exceptions. The page is totally silent on the status of Microsoft Publisher. Also, the O365 Plus xml files for Allow and Exempt fail to mention Microsoft Publisher at all. what is the status of Microsoft Publisher?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ed0150-0172-f3ad-3c7f-3a7141efbe64
* Version Independent ID: 6a978d2b-a0ff-1052-ce00-06f02f30cfa1
* Content: [List of enlightened Microsoft apps for use with Windows Information Protection (WIP) (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip#feedback)
* Content Source: [windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @ChineseWelshman ,
**The page is totally silent on the status of Microsoft Publisher** - it is unenlightened, I will create a PR to add this information to the article
**the O365 Plus xml files for Allow and Exempt fail to mention Microsoft Publisher at all** - because this file contains enlightened apps only.

Thank you

**Comment by mypil** [comment]
@ChineseWelshman - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/1d70a5414dc57f99795cb59b4d405eb647224891. 


Thank you for your contribution to make the docs better! Much appreciated!
