### ISSUE TITLE
Limit of indicators is now 15000

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#6629]
The current documentation mentions:

There is a limit of **5,000** active indicators per tenant.

however this was recently changed to 15'000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19096ba2-ed3a-36bb-1b23-37da87d73892
* Version Independent ID: fd1ceb0f-9f76-45a8-7ed2-86857fab6ca4
* Content: [Submit or Update Indicator API - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/post-ti-indicator#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/post-ti-indicator.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/post-ti-indicator.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by VLG17** [comment]
@alexverboon The article has been modified and is not reflecting this change:

![image](https://user-images.githubusercontent.com/41186174/88279596-03b91c80-cced-11ea-83ce-56eaa7ffa04e.png)
