### ISSUE TITLE
Do not run the script at each sign-on. It is recommended to run the script once every 30 days.

### ISSUE THREAD

**Issue by santoshseth** [MicrosoftDocs/windows-itpro-docs#663]
How to change this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f029a728-1f53-4576-a6ca-8a19a92626e6
* Version Independent ID: 85f27ad5-84e2-0787-082f-59d2d66c99b5
* Content: [Upgrade Readiness deployment script (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-deployment-script)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-deployment-script.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-deployment-script.md)
* Service: **unspecified**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by DaniHalfin** [comment]
Hi @santoshseth, this script does not run automatically. The referenced line is meant to remind you that if you choose to automate this script and deploy it at scale, you shouldn't run it at each sign-on, but rather once every 30 days. 
Automating this script can be done in several different ways, with System Center Configuration Manager (referenced in the topic) being one of the options.

**Comment by ld0614** [comment]
@DaniHalfin Would it be possible to get a further explanation as to why this needs rerunning and recommended configuration for setting this up in a repeatable way in SCCM please?

Based on the information located [here](https://www.anoopcnair.com/methods-to-configure-telemetry-for-upgrade-readiness/)

```
When you run the deployment script, it initiates a full scan. The size of initial data will be 2 MB. But there after inventories are deltas.
“Windows Compatibility Appraiser” Schedule task is responsible to scan and send Telemetry data.
```

This appears to show that running the script multiple times are now necessary
