### ISSUE TITLE
Windows Education feature

### ISSUE THREAD

**Issue by Dugnychon** [MicrosoftDocs/windows-itpro-docs#6630]
In the prerequisites, Windows Education is missing even though the feature is supported on this version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c06f3ef-5946-862a-ae14-f897fdb518ca
* Version Independent ID: cd6a8b99-b1e9-dff5-f174-a15840b304f0
* Content: [Windows Sandbox - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview#feedback)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@Dugnychon . Thanks for reporting, After verification from the author, he might update the content

**Comment by e0i** [comment]
@Dugnychon 

Upon your feedback, We have updated the content with relevant changes accordingly with the PR, #8059. Thanks.
