### ISSUE TITLE
Enroll in device management

### ISSUE THREAD

**Issue by MilSak** [MicrosoftDocs/windows-itpro-docs#6631]
I am kind of bit confused. I am trying to create a provisioning package to enroll a SH in device management to benefit from MDM policies.. The Surface is joined to local AD.  I am not sure of the service account and password to use to do the authorization.
Is it this a local Ad account or AAD account. 
Any feedback will be much appreciated.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf0f0af-2ca4-8705-fa1a-4fa34fff0d99
* Version Independent ID: 75dd473c-f64d-bb3c-67ac-60831e397395
* Content: [Create provisioning packages (Surface Hub) - Surface Hub](https://docs.microsoft.com/en-us/surface-hub/provisioning-packages-for-surface-hub#feedback)
* Content Source: [devices/surface-hub/provisioning-packages-for-surface-hub.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/provisioning-packages-for-surface-hub.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@MilSak. Your query will be answered by windows domain user experts. Keep waiting for the reply.

**Comment by VLG17** [comment]
@MilSak You can use the provisioning package to enrole a SH in Active Directory, Azure Active Directory or MDM:

![image](https://user-images.githubusercontent.com/41186174/90038215-d816ca00-dccd-11ea-8910-c21c03dd4aeb.png)

I assume you are looking to enrole your SH in Azure Active Directory. The required accounts are different from one enrollment option to another and they are described in the article under the "[Configure settings](https://docs.microsoft.com/en-us/surface-hub/provisioning-packages-for-surface-hub#configure-settings)
)" section:

![image](https://user-images.githubusercontent.com/41186174/90038528-35128000-dcce-11ea-8f55-048321c0102a.png)

**Comment by e0i** [comment]
Hello @MilSak 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
