### ISSUE TITLE
Wrong policy name in Countermeasure section.

### ISSUE THREAD

**Issue by CodeChief** [MicrosoftDocs/windows-itpro-docs#6633]
In the "Countermeasure" section it currently says "Configure the Network security: LDAP server signing requirements setting..." however that does not exist. Possible values are either "Domain controller: LDAP server signing requirements" or "Network security: LDAP client signing requirements". Actually both must be set accordingly to implement the countermeasure without breaking client access as described earlier on the page.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4aad5771-d5cd-4bad-09ed-4e63dad74fcf
* Version Independent ID: b2b80b51-9152-56d1-4719-52e9d6aba281
* Content: [Network security LDAP client signing requirements (Windows 10) - Windows security](https://docs.microsoft.com/en-gb/windows/security/threat-protection/security-policy-settings/network-security-ldap-client-signing-requirements#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-security-ldap-client-signing-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-security-ldap-client-signing-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@Dansimp .after reading  @CodeChief  his comment, i checked on windows 10 1909 with updated admx files, 
i found  **Network security: LDAP server signing requirements**   does not exist.
Only  **Network security: LDAP client signing requirements** is exist

So please look into this issue sir

**Comment by CodeChief** [comment]
Yes I guess the author originally intended it to read "Domain controller: LDAP server signing requirements".

It would also make sense to list all three requirements to remediate the risk (as I understand):
1) The domain controller/LDAP server setting.
2) The LDAP client setting (includes member servers as "clients").
3) The security fix to all clients and servers before activating any of the policies at a required level.

The problem with this fix is the policies can totally lock-out clients at group policy application if you go straight to "required" level are not careful or there is some other issues with the PKI infrastructure or local certificates. So the "Remediation" should include the minimum points to alert the patch reviewer that they really have to read and plan in detail for this one.

**Comment by RAJU2529** [comment]
@CodeChief. Keep  wait, let experts will reply to this article.

**Comment by MaratMussabekov** [comment]
hello @CodeChief , @RAJU2529 ,
it looks like the major part of this article is simply copy-pasted from https://docs.microsoft.com/en-gb/windows/security/threat-protection/security-policy-settings/domain-controller-ldap-server-signing-requirements

Despite the fact that the article is about **Network security: LDAP client signing requirements**, parts **Best practices**, **Vulnerability** and **Potential impact** just simply copied from **Domain controller: LDAP server signing requirements** article.
Part **Countermeasure** was also copied, but author just replaced "Domain controller" with "Network security".

It requires much more changes than simple the fix for **Countermeasure** part.

Thank you

**Comment by MaratMussabekov** [comment]
hello @CodeChief , @RAJU2529 ,
please have a look at https://github.com/MicrosoftDocs/windows-itpro-docs/pull/6770
Thank you

**Comment by illfated** [comment]
New PR #6795 created to replace #6770, due to frequent and extensive changes to the same document page.

**Comment by mypil** [comment]
@CodeChief - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/13fd2d350d666e7c6663f808584c6b1db1c7cc4f. 


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by CodeChief** [comment]
Looks good, thanks!
