### ISSUE TITLE
Reputation-based protection

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/windows-itpro-docs#6634]
There's no such page as "Reputation-based protection" anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9190369-d270-4f74-629b-8f7b4bdf5f94
* Version Independent ID: fd574d3f-58d3-6e04-ed36-b62d6bbbebd0
* Content: [Set up and use Microsoft Defender SmartScreen on individual devices (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-set-individual-device)
* Content Source: [windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-set-individual-device.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-set-individual-device.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@icelava . Yes, I too conformed on windows 10 1909  **Reputation-based protection ** is not there..
The SCreenshot is showing outdated. The current article is updated in the year 2017,.
The Author of the needs to be update.

**Comment by MaratMussabekov** [comment]
Hello @icelava , @RAJU2529 ,
This is the updated version of the article, it show interface for Windows 10 version 2004
Thank you

**Comment by icelava** [comment]
@MaratMussabekov If that is the case, can it please have clearer explanation on the difference between OS/Explorer level SmartScreen vs Edge SmartScreen?

https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-protection-windows-10#microsoft-defender-smartscreen-settings

https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-windows-10#microsoft-defender-smartscreen
(or superceded by Edge administrative template)

**Comment by MaratMussabekov** [comment]
Hello @icelava,
**Microsoft Defender SmartScreen for Microsoft Edge** - shows warning when you try to access dangerous site or try to download malicious file.
**Check apps and files** - shows warning when you try to execute downloaded file.
For me, current description is clear enough.
Which kind of clarification would you recommend to add?
Thank you

**Comment by RAJU2529** [comment]
Now i am using v2004, all options are conformed as shown in screenshot. 
Those settings are worked. I received message while opening edge browser

**Comment by mypil** [comment]
@icelava - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @MaratMussabekov so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
