### ISSUE TITLE
SCEP update policies

### ISSUE THREAD

**Issue by AntoineJo** [MicrosoftDocs/windows-itpro-docs#6635]
Hi, it would be great to add a step-by-step for SCEP updates configuration with SCCM as well :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08d16473-db61-23bd-7201-f5d7d6a56cc8
* Version Independent ID: 468238c8-8fb4-3dff-3485-07daab0c7833
* Content: [Onboard to the Microsoft Defender ATP service - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/onboarding#next-generation-protection)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/onboarding.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/onboarding.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by nam31** [comment]
@AntoineJo Thank you for providing feedback.
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
Thank you for your contribution to make the docs better! Much appreciated!
