### ISSUE TITLE
Additional Step needed for ADFS 2019

### ISSUE THREAD

**Issue by PaulTown** [MicrosoftDocs/windows-itpro-docs#6637]
There is additional steps needed for ADFS 2019 that need to be added to this document.
To get the Enterprise PRT for 2019 you need to run these commands on each 2019 ADFS server.

Add-AdfsScopeDescription -Name ugs
$id = (Get-AdfsApplicationPermission -ServerRoleIdentifiers "http://schemas.microsoft.com/ws/2009/12/identityserver/selfscope" | ?{ $_.ClientRoleIdentifier -eq "38aa3b87-a06d-4817-b275-7a316988d93b" }).ObjectIdentifier
Set-AdfsApplicationPermission -TargetIdentifier $id -AddScope 'ugs'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93cb286c-03a9-187a-77a3-771c1c672342
* Version Independent ID: 875bbfa3-7ee3-960e-9b1c-ff5216a62d8b
* Content: [Configure Device Registration for Hybrid Windows Hello for Business - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by Reeced40** [comment]
@mapalko please can you confirm if this should be added to the article and I'll do the PR.

**Comment by mapalko** [comment]
@PaulTown my understanding is that the ugs scope isn't needed for device registration and it is only an issue for certificate enrollment. We already have a note in the section for configuring adfs and pki: https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-adfs

**Comment by nam31** [comment]
@PaulTown Please let us know if you still have any question regarding the issue you have raised initially.

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
