### ISSUE TITLE
Submission ignored

### ISSUE THREAD

**Issue by dcsoft4** [MicrosoftDocs/windows-itpro-docs#6638]
I submitted https://www.microsoft.com/en-us/wdsi/submission/8ccaceaa-1ad9-4831-ab7e-509636eec032 about 3 weeks ago and there still no analyst comment, and any further communication about it requires us to wait for the analyst's outcome.  Where do we inquire about expected time to response?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9960b9e-e9e3-84b1-6171-37e5239a86aa
* Version Independent ID: 09ffca13-27be-b5d2-24a0-04161f62eb87
* Content: [Software developer resources - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/developer-resources#feedback)
* Content Source: [windows/security/threat-protection/intelligence/developer-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/developer-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by RAJU2529** [comment]
@dcsoft4 . I think it's not ignored, sample might be analysed already , updated antivirus files are updated via server to windows 10 os.

**Comment by levinec** [comment]
Hi @dcsoft4, if you have questions about submissions please contact Microsoft support. This git issues channel is for documentation changes only.
