### ISSUE TITLE
Please add version history

### ISSUE THREAD

**Issue by azsec** [MicrosoftDocs/windows-itpro-docs#6640]
Hi PG team,

Could you please add version history and what changes in each of version? That would help for tracking. Thank you very much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ca25ead-3b5d-4434-1865-0d4fef57ebdf
* Version Independent ID: 8d146609-15b5-b8a0-62bf-108f29248991
* Content: [What's new in Microsoft Defender Advanced Threat Protection for Linux - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-whatsnew#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-whatsnew.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-whatsnew.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Hello @azsec! Thank you for the feedback. Version history is built into GitHub (which is one of the nice things about using GitHub to publish documentation). If you click Edit in the upper right corner, and sign in, you'll see a History button. Click that to view all the versions of the article. I hope this helps!
