### ISSUE TITLE
StartTime or StartDate?

### ISSUE THREAD

**Issue by aikensam** [MicrosoftDocs/windows-itpro-docs#6641]
PauseQualityUpdatesStartDate and PauseFeatureUpdatesStartDate repeat multiple times here but they are StartTime intead of StartDate in "Group Policy Settings Reference Spreadsheet Windows 1809".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1684b30a-3187-85ce-0cf7-10d1b8298b7f
* Version Independent ID: 9b7170fc-2b39-8e46-7898-894a45de8623
* Content: [Configure Windows Update for Business (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-configure-wufb)
* Content Source: [windows/deployment/update/waas-configure-wufb.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-configure-wufb.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by MaratMussabekov** [comment]
Hello @aikensam, agreed, I tested on 1703, 1709 and 1909, all have PauseFeatureUpdatesStartTime.
I will create a PR to add it in the article
Thank you

**Comment by mypil** [comment]
@aikensam - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/198ca6a2e5092007142992f71867545b144339cf. 


Thank you for your contribution to make the docs better! Much appreciated!
