### ISSUE TITLE
MDM reliable party

### ISSUE THREAD

**Issue by frfriel** [MicrosoftDocs/windows-itpro-docs#6642]
The portion on "Make the MDM a reliable party of Azure AD" needs to be updated. You cannot configure MDM as a reliable party in the manner documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f06aa-8465-821f-6ad8-9c04f9be5291
* Version Independent ID: 0f2f73e7-8154-4f7f-a24b-841785c05dd6
* Content: [Azure Active Directory integration with MDM - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/azure-active-directory-integration-with-mdm)
* Content Source: [windows/client-management/mdm/azure-active-directory-integration-with-mdm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/azure-active-directory-integration-with-mdm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **dansimp**

**Comment by Reeced40** [comment]
@frfriel thank you for reaching out and helping improve MS Docs. Please have a look at the article and see if the updated version has fixed your query. Otherwise please let me know what you suggest having changed. Thanks.

**Comment by nam31** [comment]
@frfriel We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
