### ISSUE TITLE
Ambiguous timeframe - "upto 30 days"

### ISSUE THREAD

**Issue by laughingman42** [MicrosoftDocs/windows-itpro-docs#6644]
This line is ambiguous: "Advanced hunting is a query-based threat-hunting tool that lets you explore up to 30 days of raw data." This would mean that we can run queries on data for any 30-day timeperiod (within data retention period selected). Eg: For 180 day data retention, we can run queries on a events between 60 to 90 days ago.
Current behaviour (at least in my instance) seems to indicate the timerange cannot be set beyond last 30 days. Thus even with 180 day retention, hunting cannot be done for events older than 30 days.

If this is the correct understanding, line should specifically reference "within last 30 days of raw data". A good addendum would be how to get to the event data older than 30 days (if such capability exists).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88b10778-0203-5e62-911a-62781a5147ab
* Version Independent ID: 55213ba9-a050-5b98-4453-57258b1df352
* Content: [Overview of advanced hunting in Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-overview)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by mypil** [comment]
@laughingman42 - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/97db7b0e54cb022ac9ea6a1c29f2fe1f8f4bdd43. 


Thank you for your contribution to make the docs better! Much appreciated!
