### ISSUE TITLE
Wrong description for HEALTHATTESTATION_CERT_RETRIEVAL_COMPLETE

### ISSUE THREAD

**Issue by Harmyder** [MicrosoftDocs/windows-itpro-docs#6647]
Description for HEALTHATTESTATION_CERT_RETRIEVAL_COMPLETE (3) is the same as for HEALTHATTESTATION_CERT_RETRIEVAL_FAILED (2). And from Step 3 I infer that it probably should be some kind of success. Even if it is a failure it deserves its own description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b523bfc-d44c-c8dd-30ef-3322b7a74dfe
* Version Independent ID: 16f7a003-3ac8-cc87-6a9d-122a11d796f4
* Content: [Device HealthAttestation CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/healthattestation-csp#feedback)
* Content Source: [windows/client-management/mdm/healthattestation-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/healthattestation-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Should be manageable to find what the actual description should be, although there does not seem to be an exact description on this page. Maybe it could be found by combining the conclusion in one of the previous sections and some other page document related to this topic. This is what I found in the main CSP diagram description:

***

**Status** (Required)

Provides the current status of the device health request.

The supported operation is Get.

The following list shows some examples of supported values. For the complete list of status see Device HealthAttestation CSP status and error codes.

- 0 - (HEALTHATTESTATION_CERT_RETRI_UNINITIALIZED): DHA-CSP is preparing a request to get a new DHA-EncBlob from DHA-Service
- 1 - (HEALTHATTESTATION_CERT_RETRI_REQUESTED): DHA-CSP is waiting for the DHA-Service to respond back, and issue a DHA-EncBlob to the device
- 2 - (HEALTHATTESTATION_CERT_RETRIEVAL_FAILED): A valid DHA-EncBlob could not be retrieved from the DHA-Service for reasons other than discussed in the DHA error/status codes
- 3 - (HEALTHATTESTATION_CERT_RETRI_COMPLETE): DHA-Data is ready for pick up

**Comment by illfated** [comment]
BTW, thank you @Harmyder, for pointing out the issue, it looks like a copy-paste mistake by the original author. Although I cannot promise exactly when, I would like to create a PR to have that text corrected. Just need some research first to find out if this is something which could be found somewhere on the internet, or if it needs to be provided by someone internally in Microsoft.

**Comment by Reeced40** [comment]
@ManikaDhiman please can you confirm if @illfated suggestion is correct?

**Comment by illfated** [comment]
Thank you for asking, @Reeced40 . My guesstimate is picked from the same page, from this section:

- https://docs.microsoft.com/en-us/windows/client-management/mdm/healthattestation-csp#csp-diagram-and-node-descriptions

***

![image](https://user-images.githubusercontent.com/38162891/94562437-a057e780-0265-11eb-8864-6e1934c3ea3e.png)

***

The reported duplicate description can be found in the list beneath "**Device HealthAttestation CSP status and error codes**":

- https://docs.microsoft.com/en-us/windows/client-management/mdm/healthattestation-csp#device-healthattestation-csp-status-and-error-codes

***

![image](https://user-images.githubusercontent.com/38162891/94563008-61766180-0266-11eb-81f3-0e7212b8efba.png)

***

Maybe there could be additional issues on the same page, but I don't know this topic well enough to detect incorrect information within a reasonable time frame.

**Comment by Reeced40** [comment]
@ManikaDhiman @Dansimp please could you assist?

**Comment by illfated** [comment]
If so desired, I could easily open a Pull Request to suggest the necessary change to that document section (Description text for error code 3).

**Comment by ManikaDhiman** [comment]
@Harmyder thanks for pointing out this doc issue. 
@illfated as always, thank you for your valuable inputs. 

After confirming with the product team, I've updated the description of the HEALTHATTESTATION_CERT_RETRIEVAL_COMPLETE error code and also updated the mentions of CERT_RETRI to CERT_RETIEVAL. These updates will be live shortly. Thanks!
