### ISSUE TITLE
NetworkSecurity_MinimumSessionSecurityForNTLMSSPBasedClients  not available

### ISSUE THREAD

**Issue by yogeshasalkar** [MicrosoftDocs/windows-itpro-docs#6651]
NetworkSecurity_MinimumSessionSecurityForNTLMSSPBasedClients  GP -&gt; Network Security: Minimum session security for NTLM SSP based (including secure RPC) clients  is not given in documentation but it is configurable via Intune. I Have tested this setting. Please update it in documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 773b74b2-7dc2-d0e5-1e3b-bd6445bceda4
* Version Independent ID: 34b55057-9078-6bd0-a9ac-2f6403b84be7
* Content: [Policy CSP - LocalPoliciesSecurityOptions - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions)
* Content Source: [windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@yogeshasalkar . Good, you already tested via intune. Will you share the results of the tested?

**Comment by illfated** [comment]
#please-close
