### ISSUE TITLE
Why i can save bitlocker key only in usb?

### ISSUE THREAD

**Issue by yonathanluiz** [MicrosoftDocs/windows-itpro-docs#6654]
![bitlocker](https://user-images.githubusercontent.com/64906019/81182606-63bce400-8f84-11ea-8cf8-e46a14b6af8c.png)

I cleared the TPM and still the problem remains what to do? is there a way to fix without using the BIOS?

**Comment by beerisgood** [comment]
Saving to USB works.
Looks like your key doesn't had a drive letter / don't get recognized at all. Check that first

**Comment by RAJU2529** [comment]
@yonathanluiz . Bitlocker key can be saved in Microsoft account when device is connected to the internet  by enabling BitLocker.
It gives options to take a printout, save key to usb device  and  to Microsoft account

**Comment by yonathanluiz** [comment]
The problem is when I run the option to turn the bitlocker on it automatically tries to generate the key via usb without letting me choose how I want to generate it, and there is not even the option to go back as you can see in the print.

**Comment by RAJU2529** [comment]
@yonathanluiz . It will gives  the options afterwards , because i enabled once  , saved key in usb device , taken printout and key is also saved in microsoft account .

which version of Windows 10, you using, i am using 1909 64bit 18363.815 
https://support.microsoft.com/en-us/help/4026181/windows-10-find-my-bitlocker-recovery-key

**Comment by RAJU2529** [comment]
@yonathanluiz . When i was tested it does not ask Pendrive to connect while unlocking BitLocker from booting, instead, i typed key every time, the computer starts.
I don't know the way to remove the dependency

**Comment by mypil** [comment]
@yonathanluiz - May we know which Microsoft document link you used in reference to this issue? Or are you having some technical issues which requires technical support?

If you have some issues with a particular doc, we would really appreciate it if you are able to help by providing more details as to what should be edited and/or included. Thank you!

**Comment by mypil** [comment]
@yonathanluiz - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  If you're experiencing a technical issue, please contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. 

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page.
