### ISSUE TITLE
Azure Autiomation Examples

### ISSUE THREAD

**Issue by Torxsmind** [MicrosoftDocs/windows-itpro-docs#6655]
Need information on how to configure this settings via a Azure Automation account.  Do we add registry items via State Configuration (DSC) or Update management.  This is being rolled up to Azure Security Center as a vulnerability AZ-WIN-00152, with no discernable remediation plan.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e749183d-e3df-466f-786a-c4af4002c05a
* Version Independent ID: a4f1d6a9-43df-fa36-fc1b-18224911b58a
* Content: [Schedule Windows Defender Antivirus protection updates - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/manage-protection-update-schedule-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/manage-protection-update-schedule-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/manage-protection-update-schedule-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by e0i** [comment]
@Torxsmind 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
