### ISSUE TITLE
Unclear what [channel] should be set to

### ISSUE THREAD

**Issue by dominique97** [MicrosoftDocs/windows-itpro-docs#6656]
Documents tell users which [distro] and [version] to use, but there is not information on what the channel should be, which channels are available, and what the differences are

**Comment by denisebmsft** [comment]
Hello @dominique97. Can you please tell us to which article(s) your feedback applies? This will help us route this issue to the right team/writer.

**Comment by dominique97** [comment]
Sorry bout that!  https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually

**Comment by VLG17** [comment]
@dominique97 I think the information was added to the article, or was this part already in and you don't find it detailed enough.

![image](https://user-images.githubusercontent.com/41186174/90038926-ab16e700-dcce-11ea-9149-a2a783cb8618.png)

**Comment by e0i** [comment]
@dominique97 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
