### ISSUE TITLE
Simultaneously block domain for some users but allow for others

### ISSUE THREAD

**Issue by leniwiec16** [MicrosoftDocs/windows-itpro-docs#6657]
Is it possible to make an exception for certain users to allow traffic for otherwise blocked domain? In other words does the action "allow" have a precedence before "block"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50f2be10-41a0-67ae-222b-1b073bef537b
* Version Independent ID: 3f186b13-aad0-4ba4-e239-d9bb24ff2ebe
* Content: [Manage indicators - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/manage-indicators#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/manage-indicators.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/manage-indicators.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation and content-related issues.

Please consider asking your question via [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channels.

Feel free to re-open this issue if you feel that further revisions needed for the article itself. 

Thank you, and stay healthy.
