### ISSUE TITLE
Feature update deferal content should mention the dependency on telemetry.

### ISSUE THREAD

**Issue by wesk-ms** [MicrosoftDocs/windows-itpro-docs#666]
Change request for page:
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-configure-wufb.md

At the end of the 'Pause Feature Updates' section, we should add a note that states telemetry must be enabled in order to defer feature updates.  This is documented in the GPO:  "Select when Feature Updates are received".

From the GPO help text for _"Computer Configuration\Administrative Templates\Windows Components\Windows Update\Windows Update for Business\Select when Preview Builds and Feature Updates are received"__
"To configure Feature Updates you must have a telemetry level setting of 1 or higher."

**Comment by DaniHalfin** [comment]
Hi @wesk-ms , at the very top of the topic, there's an IMPORTANT tag that states exactly that (as WUfB will not work with telemetry leve of 1 or higher, and not just this specific setting) - 

> [!IMPORTANT] For Windows Update for Business policies to be honored, the Diagnostic Data level of the device must be set to 1 (Basic) or higher. If it is set to 0 (Security), Windows Update for Business policies will have no effect. For instructions, see Configure the operating system diagnostic data level.

Did you notice that? If so, do you feel like there's added benefit to noting that again per-setting?

**Comment by andreabichsel** [comment]
Closing issue for now, please notify if changes are needed.
