### ISSUE TITLE
configure wdav channel with just configuration profile (not command line?)

### ISSUE THREAD

**Issue by annerajb** [MicrosoftDocs/windows-itpro-docs#6661]
Is there a way to configure just the wdav update channel on the profile without having to run a command line / shell command?
Or in the same profile to specify the different update channels for wdav vs everything else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f86d88-a696-926e-cecf-75e114667005
* Version Independent ID: fc49bf6e-3f4e-2f6b-05bc-e75ee4e00333
* Content: [Deploy updates for Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-updates#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-updates.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@annerajb 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
