### ISSUE TITLE
Markdown oddities under Windows 10 Family section

### ISSUE THREAD

**Issue by Tafkae** [MicrosoftDocs/windows-itpro-docs#6668]
Under the Family section, some of the endpoint URLs appear to have been fully or partly italicized at points where it seems like asterisks may have been intended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611b03b8-c215-0f34-c739-7f4bc7fcf51e
* Version Independent ID: 695ca891-bf89-82df-a9a8-90e598512c96
* Content: [Windows 10, version 1903, connection endpoints for non-Enterprise editions - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1903-non-enterprise-editions#feedback)
* Content Source: [windows/privacy/windows-endpoints-1903-non-enterprise-editions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/windows-endpoints-1903-non-enterprise-editions.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MikeEdgar
* Microsoft Alias: **v-medgar**

**Comment by illfated** [comment]
> Under the Family section, some of the endpoint URLs appear to have been fully or partly italicized at points where it seems like asterisks may have been intended.
> 

Good point. Looks like the **Windows 10 Family** table is inconsistent when it comes to escaping asterisks intended to be displayed as asterisks. 
I will open a PR to have those asterisks displayed instead of being read as italic formatting characters.

**Comment by illfated** [comment]
(Ref. PR #6678 - feel free to comment & review the content)
