### ISSUE TITLE
There is no longer a "See full history" option.

### ISSUE THREAD

**Issue by mica** [MicrosoftDocs/windows-itpro-docs#6669]
On version 1909. Please update this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de416fda-04fb-6780-6675-020fdc2426ba
* Version Independent ID: ede7f3c1-ba3a-e331-80d8-c992b3d7f9a4
* Content: [Restore quarantined files in Windows Defender AV - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/restore-quarantined-files-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@mica . This article only;y applies to **Microsoft Defender Advanced Threat Protection (Microsoft Defender ATP)**  not for windows defender  consumer editions

**Comment by denisebmsft** [comment]
Hello @mica and @RAJU2529. Thanks for the feedback, mica, and thank you for helping resolve this, RAJU2529. I took a look at the UI and agree that it has changed since this article was first written. I've updated it, and you will see the changes live sometime tomorrow.
