### ISSUE TITLE
Credential Gaurd- Wi-fi and VPN Considerations 

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/windows-itpro-docs#667]
This section is inaccurate- MSCHAPv2 still works but with a password prompt instead of SSO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b1f3ae7-79ed-fc75-4f36-ad5537d5f928
* Version Independent ID: bdd1e434-0825-7220-9e97-ee4cdd10b897
* Content: [Considerations when using Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-considerations)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-considerations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-considerations.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@fowl2 Thanks for the correction. The Credential Guard engineering team helped us publish a revision to make this more clear.
