### ISSUE TITLE
Add note to show this page is about a produt that has reached EOS

### ISSUE THREAD

**Issue by arcarley** [MicrosoftDocs/windows-itpro-docs#6672]
We should add a note stating that Windows 10 Mobile has reached End of Support as of December 10th, 2019. "Windows 10 Mobile device should continue to work after December 10, 2019, but there will be no updates after that date (including security updates) and device backup functionality and other backend services will be phased out as described above." https://support.microsoft.com/en-us/help/4485197/windows-10-mobile-end-of-support-faq

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37a55e58-a782-0ccf-a200-1554eed26b1d
* Version Independent ID: b02194fd-e682-1382-58bb-2b2312150775
* Content: [Deploy updates to Windows 10 Mobile or Windows 10 IoT Mobile - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-mobile-updates#feedback)
* Content Source: [windows/deployment/update/waas-mobile-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-mobile-updates.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
Sounds good. Have you planned a PR to add that note already, or would you like a PR provided by us contributors, i.e. myself or one of the other regular contributors?

**Comment by illfated** [comment]
(Maybe you could offer a comment in the related & linked issue ticket #6675 ?)

**Comment by arcarley** [comment]
Hello Trond,

Actually, after looking at this page – I think all still relevant information is captured in the other Windows as a Service deployment docs – including the linked Windows Update for Business documentation. Perhaps we can just remove this page completely? I am not sure how many regular views it is getting.. but I do not believe it is currently aiding in management of devices. Thoughts?

Best,
Aria

**Comment by illfated** [comment]
> Hello Trond, Actually, after looking at this page – I think all still relevant information is captured in the other Windows as a Service deployment docs – including the linked Windows Update for Business documentation. Perhaps we can just remove this page completely? I am not sure how many regular views it is getting.. but I do not believe it is currently aiding in management of devices. Thoughts? Best, Aria

Thank you for sharing your thoughts on this matter. I wish I were involved enough in this topic to be able to answer your question in a helpful fashion. Being a humble computer support worker and only contributing here with Microsoft Docs in my spare time, I don't get enough exposure to this topic to have the required knowledge. I recommend asking internally (maybe @denisebmsft may know which group could be of assistance here?) to make sure your question gets its deserved verification before making the final decision.

Best of luck, stay safe & healthy.

Trond B. K. / illfated

**Comment by arcarley** [comment]
Thanks Trond, I will help review internally and ensure that is an okay action before proceeding with removing that docs page. Thanks and all the best! 😊

**Comment by nam31** [comment]
@jaimeo can you please help?

**Comment by jaimeo** [comment]
I'll work with @arcarley (a colleague) directly on this.

**Comment by jaimeo** [comment]
@arcarley where are we with this? Did we decide to just retire this page?

**Comment by jaimeo** [comment]
We've retired this article, so this should be sorted now.

**Comment by Kateyanne** [comment]
@illfated @nam31  Is it OK to close this now?

**Comment by illfated** [comment]
Main ticket comment:
> We should add a note stating that Windows 10 Mobile has reached End of Support as of December 10th, 2019. "Windows 10 Mobile device should continue to work after December 10, 2019, but there will be no updates after that date (including security updates) and device backup functionality and other backend services will be phased out as described above." [support.microsoft.com/en-us/help/4485197/windows-10-mobile-end-of-support-faq](https://support.microsoft.com/en-us/help/4485197/windows-10-mobile-end-of-support-faq)

I think this would be useful to apply in the document page, just to make future readers of the page aware of the status.

**Comment by Kateyanne** [comment]
@illfated are you able to open a PR to include this information?

**Comment by jaimeo** [comment]
This article is retired. It is gone; no longer published. It does not exist.
