### ISSUE TITLE
Applies to 2019 Update needed

### ISSUE THREAD

**Issue by wsmelton** [MicrosoftDocs/windows-itpro-docs#6673]
Please update this article to note whether the it also applies to Window Server 2019...

The assumption would be it is since it affects Windows 10, but it helps to specify it being that it is a Server OS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef8b6967-0e45-bcdd-6d70-54759d9f7ec8
* Version Independent ID: 6651ebc1-04f0-421f-891b-6957ca37da7c
* Content: [Network access - Restrict clients allowed to make remote calls to SAM - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by wsmelton** [comment]
Disregard...figured out this actually does not apply to Window Server 2019

**Comment by wsmelton** [comment]
Attempting to make a remote call for a non-administrator account does show that remote access to the SAM database on Windows Server 2019 is affected...

I receive this message in the System log when an attempt is made, for non-administrator:

```
1 remote calls to the SAM database have been denied in the past 900 seconds throttling window.
For more information please see http://go.microsoft.com/fwlink/?LinkId=787651.
```

**Comment by mypil** [comment]
@wsmelton - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/e2398c0d0ea7894fb25580961ded7fe1c77f4ecd. 


Thank you for your contribution to make the docs better! Much appreciated!
