### ISSUE TITLE
Windows 10 Mobile

### ISSUE THREAD

**Issue by ajp999** [MicrosoftDocs/windows-itpro-docs#6675]
Should the Windows 10 Mobile and Windows 10 Mobile Enterprise editions be removed from the table at the beginning of this page showing the available servicing channels for each Windows 10 edition as these editions are now out of support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5400f8b-2ed0-7960-4e3d-2f3444be7e6b
* Version Independent ID: 81bd37f4-301b-b5ab-cda2-972a72a31ae7
* Content: [Assign devices to servicing channels for Windows 10 updates (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-servicing-channels-windows-10-updates#feedback)
* Content Source: [windows/deployment/update/waas-servicing-channels-windows-10-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-servicing-channels-windows-10-updates.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
Partially related to the following ticket:
- **Add note to show this page is about a product that has reached EOS** **#6672**

**Comment by jaimeo** [comment]
Yep; we're working on a massive overhaul of all these articles this month.

**Comment by e0i** [comment]
@jaimeo Shall we suspend assignment to this issue?

**Comment by e0i** [comment]
The issue is going to be addressed at #6672 (via https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6672#issuecomment-707224731)
