### ISSUE TITLE
Unenlightened app managed by MAM

### ISSUE THREAD

**Issue by jimbo1969** [MicrosoftDocs/windows-itpro-docs#6677]
According to [this](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/limitations-with-wip) document, 
> Only enlightened apps can be managed without device enrollment 

Elaborated as:
> If a user enrolls a device for Mobile Application Management (MAM) without device enrollment, only enlightened apps will be managed. This is by design to prevent personal files from being unintentionally encrypted by unenlighted apps. Unenlighted apps that need to access work using MAM need to be re-compiled as LOB apps or managed by using MDM with device enrollment.

Yet, I am looking at a device that has MAM-WE applied to it, and I see "unenlightened" MS Teams running on it in the corporate enterprise environment (Task Manager > Details > Enterprise context column says [mycompany].com (Unenlightened).  Am I misinterpreting what it means for an app to be "managed"?  Or should this not be possible under MAM-WE?

**Comment by MaratMussabekov** [comment]
Hello @jimbo1969 ,
could you please clarify what do you mean by "MS Teams running on it in the corporate enterprise environment"?
Thank you

**Comment by jimbo1969** [comment]
Hi Marat,
Such is what I tried to do with "(Task Manager > Details > Enterprise context column says [mycompany].com (Unenlightened)."

That is, I have MS Teams running on a device that has MAM-WE applied to it.  MS Teams shows the briefcase icon, indicating that it is running "in the corporate enterprise environment" (using the parlance of MS documentation regarding MAM/WIP).  Further, when I open Task Manager and inspect the "Enterprise Context" column, it shows "[mycompany].com (Unenlightened)", where [mycompany] is a placeholder for the actual name of my company.

I think what is comes down to is my company essentially "hijacking" the MS Teams app, asserting that I cannot use it on my machine outside of their enterprise (i.e. I cannot login into MS Teams with a different account and use it under "personal" context.  The documentation I referenced seemed to preclude such a possibility.  I think the documentation is misleading at least.  

Adding to the confusion is MS going back and forth regarding whether MS Teams is Enlightened or not.  Around the time I made my earlier post, [this document](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip) was changing back and forth showing MS Teams as Enlightened vs not.  As of today, they have it more-properly categorized as "WIP work only".

Really, the whole idea that MAM is something distinct from "Device Management" seems a little bit sketchy, given that the company can simply add any app to their list of "enterprise apps" after you're "registered", and they suddenly own it for all users of the device.  But I digress -- that is a larger issue than what I raised here.

**Comment by MaratMussabekov** [comment]
Hello @jimbo1969,
I tried to reproduce the issue:
1. I created app protection policy. I used following settings:
![image](https://user-images.githubusercontent.com/48041687/88544820-73077700-d033-11ea-9a6d-63b01ef0954d.png)
![image](https://user-images.githubusercontent.com/48041687/88544889-903c4580-d033-11ea-89a9-ceb02921717c.png)
![image](https://user-images.githubusercontent.com/48041687/88544956-b235c800-d033-11ea-8609-a16ba6ead2b6.png)
![image](https://user-images.githubusercontent.com/48041687/88545161-0771d980-d034-11ea-87e2-31d0c811c983.png)
![image](https://user-images.githubusercontent.com/48041687/88545229-21abb780-d034-11ea-8651-028391136fac.png)
2. then assigned it to the user and used this user to set personal device as a workplace-joined.

After that I was still able to log out from teams and sign in as another account (personal one).

Does this scenario look like yours? or I am missing something?

Dear @e0i,
Is it possible to contact the author of this article to ask for confirmation?

Thank you

**Comment by e0i** [comment]
@eross-msft There seems to be an ambiguity concerning whether _MS Teams_ being an _Enlightened_ app or not. An independent contributor could not reproduce the issue. Would you be able to shed light on this matter? Thank you.
