### ISSUE TITLE
Language and a link

### ISSUE THREAD

**Issue by neildotwilliams** [MicrosoftDocs/windows-itpro-docs#668]
I cannot understand this sentence, but it might just be me:
"Additionally, suppress statements which filter out specific events, only apply within that query statement and are not to the entire subscription."

Also a link states "For more info, see Appendix F – Annotated Baseline Subscription Event Query." but Appendix F is the suspect not the baseline.

Great document though!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5862cc7-3f36-5f2e-9ade-f7441f99f818
* Version Independent ID: b8bd1985-7b5b-ea79-976a-7d96ad69335c
* Content: [Use Windows Event Forwarding to help with intrusion detection (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection#bkmk-appendixf)
* Content Source: [windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md)
* Service: **unspecified**
* GitHub Login: @tedhardyMSFT
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@tedhardyMSFT can you clarify the sentence?
@neildotwilliams thanks for the comment and for correcting the link text. I submitted a fix that should appear tomorrow. If you see similar edits, please click Edit in upper right and you can submit the change. We'll pull in that change and you'll be listed as a contributor.
