### ISSUE TITLE
duplication PATH   que ce passe t"il si on est user administrateur

### ISSUE THREAD

**Issue by jgaury** [MicrosoftDocs/windows-itpro-docs#6680]
Pour windows 10 dans panneau de configuration systeme  la variable d'environnement PATH appariait à 2 endroit
panneau de configuration systeme  parametres systeme avancé variables environnement variables envronnement user et variables environnement systeme

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 72d479c1-cedc-05fc-2d73-45342b955037
* Version Independent ID: 8e91c2df-8405-3ec0-210e-1b97e86073cf
* Content: [Variables d’environnement reconnues (Windows 10) - Windows Deployment](https://docs.microsoft.com/fr-fr/windows/deployment/usmt/usmt-recognized-environment-variables?source=docs#feedback)
* Content Source: [windows/deployment/usmt/usmt-recognized-environment-variables.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/usmt/usmt-recognized-environment-variables.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Puis-je demander plus de détails, si vous pourriez être plus précis sur la partie du document à laquelle vous faites référence?
*
(May I ask for more details, if you could be more specific about which part of the document you are referencing?)

**Comment by jgaury** [comment]
que se asse t'il si on est user administrateur laquelle le système prendt'il

**Comment by illfated** [comment]
Je pense que vous aviez l'intention d'écrire ce qui suit: "que se passe-t-il si vous êtes un utilisateur administrateur, quel système faut-il"
*
(I believe you intended to write the following: "what happens if you are an administrator user, which system does it take")

**Comment by illfated** [comment]
Translated text from the original comment (https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6680#issue-615307768)

"For windows 10 in system control panel the PATH environment variable matched in 2 places
control panel system parameters advanced system environment variables user environment variables and system environment variables"

**Comment by illfated** [comment]
My mistake. I should have checked more than 1 translating engine. The actual text says (from https://www.bing.com/Translator) :
*
que se asse t'il si on est user administrateur laquelle le système prendt'il
(what if you're using administrator which system takes it)
*
Je suis désolé, il semble que je manque le point ici. Vous pouvez contacter votre locataire Microsoft Support le plus proche.

(I am sorry, I seem to be missing the point here. You may want to contact your nearest Microsoft Support tenant.)
