### ISSUE TITLE
Windows 10 Deprecated Features - IPv6/Teredo

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/windows-itpro-docs#6681]
Teredo is an IPv6 transition technology that was disabled by default at the same time as the others in 1803. It would be great if it could be added to this page for ease of searching/clarity. 

> **IPv4/6 Transition Technologies (6to4, ISATAP, and Direct Tunnels)**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89b6fda3-06b5-15be-9021-c8126f721c9b
* Version Independent ID: 5a8ff7c5-ed5f-6c18-211c-4af5397b1a17
* Content: [Windows 10 features we’re no longer developing - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-deprecated-features#feedback)
* Content Source: [windows/deployment/planning/windows-10-deprecated-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/planning/windows-10-deprecated-features.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
I will check on this

**Comment by greg-lindsay** [comment]
Adding this manually myself.
