### ISSUE TITLE
Microsoft Teams lies

### ISSUE THREAD

**Issue by smit5334** [MicrosoftDocs/windows-itpro-docs#6689]
Microsoft Teams runs like crap on any Win10 ARM64 device and they refuse to release an ARM64 version of it.  It if runs so "great" on the Surface Pro X, when did the have to put out a firmware update just to keep it from crashing continually.  Take the lies about Microsoft Teams running great off the site so no Enterprise companies are fooled into thinking ARM64 is well supported.  Until MS decides to actually support the full range of products on the ARM64, it is NOT a solution for any company.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8801006e-0612-0d68-18fc-fe5f198c8136
* Version Independent ID: 0a9c5b49-fbfe-f81e-e0db-70da3e1629ba
* Content: [Deploying, managing, and servicing Surface Pro X - Surface](https://docs.microsoft.com/en-us/surface/surface-pro-arm-app-management#feedback)
* Content Source: [devices/surface/surface-pro-arm-app-management.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-pro-arm-app-management.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @CoveMiner
* Microsoft Alias: **v-jokai**

**Comment by mypil** [comment]
@smit5334 - Thank you for providing feedback.

Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the 
**[Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)**. 
You might find others have made a similar request that you can add to, or you can open a new one. 


Thank you for your contribution to make the docs better! Much appreciated!
