### ISSUE TITLE
Windows Kernel DMA Protection on AMD systems

### ISSUE THREAD

**Issue by Mr-nUUb** [MicrosoftDocs/windows-itpro-docs#6693]
Hi!

What is the current state? The documentation mentions only Windows 10 version 1803 and 1809.
Will Windows Kernel DMA Protection support AMD-Vi, AMD IOMMU or SR-IOV in the future?

This is an interesting topic, now that Intel released Thunderbolt to everyone.
ASRock even provides AMD X570 mainboards with the possibility to use Thunderbolt add-in cards and even AMD X570 mainboards with integrated Thunderbolt controllers.
Example: https://www.asrock.com/mb/AMD/X570%20Phantom%20Gaming-ITXTB3/

Best regards
Mr nUUb

EDIT: I opened the issue directly on Github, not on docs.microsoft.com? Was this a bad idea?

**Comment by beerisgood** [comment]
Related:
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3997

**Comment by mypil** [comment]
@Mr-nUUb - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by Mr-nUUb** [comment]
Of course, it is this one:
https://docs.microsoft.com/en-us/windows/security/information-protection/kernel-dma-protection-for-thunderbolt

**Comment by Reeced40** [comment]
@Mr-nUUb thank you for reaching out and helping improve MS Docs. It seems this issue was resolved in a related issue - please see https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5988

**Comment by nam31** [comment]
@Mr-nUUb   Please look into this Document :  https://docs.microsoft.com/en-us/windows/security/information-protection/kernel-dma-protection-for-thunderbolt#frequently-asked-questions

Please let us know if you still have any question regarding the issue you have raised initially.

**Comment by Mr-nUUb** [comment]
@nam31 This does not answer my question at all. My question was: everywhere you mention Intel, what about AMD? AMD does support similar virtualization technologies, so what's the status there? Do you plan on supporting AMD-Vi like you support Intel VT-d? The document you mentioned was not reworked to include this information. You know, Thunderbolt is now supported on AMD, too...

**Comment by Reeced40** [comment]
@Mr-nUUb thank you for clearing this up. Please see this article where it confirms AMD support.  https://docs.microsoft.com/windows-hardware/design/device-experiences/oem-kernel-dma-protection
