### ISSUE TITLE
Key Trust section, but mentions Certificate trust?

### ISSUE THREAD

**Issue by rioux602** [MicrosoftDocs/windows-itpro-docs#6695]
Many mentions of certificates in this page, link seems off : Follow the Windows Hello for Business on premises certificate trust deployment guide

I'm following the "Key Trust" Deployment Guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77ab668a-e750-0503-7c17-093d0ea43644
* Version Independent ID: 37e38b31-4599-3b00-230b-7a488ee71fb2
* Content: [Configure Windows Hello for Business Policy settings - key trust - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-key-trust-policy-settings#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-key-trust-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-key-trust-policy-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by rioux602** [comment]
I tried and followed the whole documentation, sub documentation, and everything I could find related to WHFB for on-prem and couldn't get it to work. I built a PKI infrastructure working, built ADFS server etc. Still can't get my device to "join" ADFS or enroll in Windows Hello. How can I get assistance from Microsoft for my setup?

Thanks!

**Comment by mypil** [comment]
@rioux602   - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
