### ISSUE TITLE
bcdedit /store c:\BCD /set {GUID1} path \windows\system32\winload.exe 

### ISSUE THREAD

**Issue by outofsight** [MicrosoftDocs/windows-itpro-docs#6696]
With this line, go in reboot-loop, without works

**Comment by mypil** [comment]
@outofsight - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by outofsight** [comment]
@mypil just experiment

**Comment by RAJU2529** [comment]
@outofsight   
 **bcdedit /set {GUID} path  \windows\system32\winload.exe**

**Comment by denisebmsft** [comment]
Are we okay to close this issue?

**Comment by RAJU2529** [comment]
@denisebmsft . Let we wait for his or her @outofsight  reply to this issue.

**Comment by outofsight** [comment]
I noticed that with the step 2.3 mentioned [here](https://docs.microsoft.com/it-it/windows/deployment/configure-a-pxe-server-to-load-windows-pe) the machine go in an infinite loop reboot.

In the past, I followed a similar procedure without the sub-step
`bcdedit /store c:\BCD /set {GUID1} path \windows\system32\winload.exe`
and this  old procedure, apparently works.

**Comment by RAJU2529** [comment]
@outofsight . Are you working in organization and are you trying to configure PXE Boot in Seperate server computer.

**Comment by mypil** [comment]
@outofsight - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by outofsight** [comment]
@mypil I'm not in contact with support, no planning to open any ticket. For me the issue is solved.
