### ISSUE TITLE
Upgrade not possible (by manually entering a product key)

### ISSUE THREAD

**Issue by thomashesse** [MicrosoftDocs/windows-itpro-docs#6703]
We try to upgrade some systems from Pro to Enterprise by manually entering the key. But only the Pro Edition is activated instead of the Enterprise Edition.
After checking in the VLSC, i noticed that the same KMS key is stored for the Pro and the Enterprise Edition!? Is this a bug in the VLSC or how can the problem be solved?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b5da9a4b-1942-619f-5d8e-f9611603cce2
* Version Independent ID: e004360e-fb0f-c263-f093-bd2c27021d22
* Content: [Windows 10-Editionsupgrade (Windows 10) - Windows Deployment](https://docs.microsoft.com/de-de/windows/deployment/upgrade/windows-10-edition-upgrades#feedback)
* Content Source: [windows/deployment/upgrade/windows-10-edition-upgrades.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/windows-10-edition-upgrades.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@thomashesse . Did you installed the business of Windows 10  edition?  which contains professional , enterprise, education, etc.

**Comment by thomashesse** [comment]
@RAJU2529 We usually install the Enterprise Edition with OS Deployment. However, we have some special PCs in use, such as Industrial PCs. These systems are always installed / supplied with the Pro Edition. I have defined this as a prerequisite for use, since from a license perspective it is otherwise not a qualified OS, for an enterprise upgrade via an EA.

**Comment by RAJU2529** [comment]
@thomashesse IF system preinstalled Pro edition comes from the factory, then upgrade to Enterprise i think not possible because the factory might be installed consumer edition.
To find the system with pro edition can be upgradable or not,
type below command in cmd run with admin rights
**Dism.exe /Online  /Get-TargetEditions**  

and post the result of the screenshot

**Comment by thomashesse** [comment]
@RAJU2529 I did a sample on 3 systems. All 3 systems show "Enterpise" as possible target edition. 
![grafik](https://user-images.githubusercontent.com/13416705/81803047-66d14a80-9517-11ea-8289-0a8bafc140da.png)
![grafik](https://user-images.githubusercontent.com/13416705/81803072-705ab280-9517-11ea-8249-9b4ac227f2d8.png)
![grafik](https://user-images.githubusercontent.com/13416705/81803095-7781c080-9517-11ea-908a-d97fb145f50c.png)

**Comment by RAJU2529** [comment]
@thomashesse . That means currently running as business edition.  
So you can upgrade. Then I suspect that entered license key is original enterprise key or not. Cross check twice

**Comment by thomashesse** [comment]
@RAJU2529 The Key is correct. After calling with the MSFT Activation Center, she say: all is perfekt and it should be correct that it is the same key for Pro and Enterprise Edition.  
But she also said that an Enterprise ISO must be used. However, this statement is wrong. Back to the same key again. How should a distinction be made during activation (pro and enterprise) if the key is identical? Isn't that the mistake?

I just tried it myself again without success. I copied the key from the VLSC.
![grafik](https://user-images.githubusercontent.com/13416705/81909102-65148f00-95ca-11ea-96a0-89cf9187ffa7.png)

**Comment by thomashesse** [comment]
@RAJU2529 The Key is correct. After calling with the MSFT Activation Center, she say: all is perfekt and it should be correct that it is the same key for Pro and Enterprise Edition.
But she also said that an Enterprise ISO must be used. However, this statement is wrong. Back to the same key again. How should a distinction be made during activation (pro and enterprise) if the key is identical? Isn't that the mistake?
![grafik](https://user-images.githubusercontent.com/13416705/81910426-3d262b00-95cc-11ea-932c-2b1b118810bd.png)

**Comment by RAJU2529** [comment]
@thomashesse . Enterprise iso will work only enterprise key. if the entered key is correct, then why it's not activated.

**Comment by thomashesse** [comment]
@RAJU2529 Good to know. But our issue is a upgrade (Pro -> Ent) not a downgrade (Ent->Pro).

**Comment by mypil** [comment]
@thomashesse   - Thank you for submitting feedback.

I think the best way forward is if you can contact support and open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products  so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by PhantomLord72** [comment]
I cannot upgrade from pro N to enterprise

**Comment by illfated** [comment]
@PhantomLord72 : Please contact your local Microsoft Support to inform them of your issue and that you need help to find out why it does not work.
