### ISSUE TITLE
Have a suggestion for App-V?

### ISSUE THREAD

**Issue by chenjiawei-19881015** [MicrosoftDocs/windows-itpro-docs#671]
Add or vote on suggestions on the Application Virtualization feedback site.
For App-V issues, use the App-V TechNet Forum.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0490acd-e1d3-5cbe-bf08-192103197c98
* Version Independent ID: 04173e0a-9cbf-f249-b0ee-a6b4c79897c9
* Content: [Application Virtualization (App-V) (Windows 10)](https://docs.microsoft.com/en-us/windows/application-management/app-v/appv-for-windows)
* Content Source: [windows/application-management/app-v/appv-for-windows.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/app-v/appv-for-windows.md)
* Service: **unspecified**
* GitHub Login: @MaggiePucciEvans
* Microsoft Alias: **elizapo**

**Comment by DaniHalfin** [comment]
@chenjiawei-19881015 - anything specific you wanted to note here?

**Comment by andreabichsel** [comment]
Informational only, closing issue.
