### ISSUE TITLE
The feature name has been renamed to "Allow or block file" . 

### ISSUE THREAD

**Issue by cventour** [MicrosoftDocs/windows-itpro-docs#6714]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8da58e5-9cd8-8ccf-75a9-327c14ebaa76
* Version Independent ID: 24a29218-59e1-7a1d-c8c7-e61424b5f9ee
* Content: [Endpoint detection and response in block mode - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/edr-in-block-mode#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/edr-in-block-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/edr-in-block-mode.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@cventour . If possible Create PR

**Comment by e0i** [comment]
@cventour The article author has decided to keep the EDR in block mode article as it is. See below the commentary within the relevant PR:

https://github.com/MicrosoftDocs/windows-itpro-docs/pull/7986#issuecomment-674197264

Thank you.
