### ISSUE TITLE
"Policy CSPs supported by Group Policy" vs "ADMX-backed policy CSPs"

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/windows-itpro-docs#6715]
What's the fine line differentiating these categories? Isn't ADMX-backed policies simply Policy CSPs that expose the underlying GP ATs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebc25b0a-f874-466c-cd89-9b87761cccdd
* Version Independent ID: 30929e17-4818-c0ba-30ad-4599305e6a3a
* Content: [Policy CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-configuration-service-provider#policy-csps-supported-by-group-policy-and-admx-backed-policy-csps)
* Content Source: [windows/client-management/mdm/policy-configuration-service-provider.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-configuration-service-provider.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Good question, we may need to hear from the document author about this. I thought it was about the 2 separate file types used to manage the GPOs, but I could be mistaken.

**Comment by RAJU2529** [comment]
I think CSP  policies are configured in Windows 10 Mobile smartphones, ADMX with ADML based policies are configured in Windows 10 desktop editions

**Comment by illfated** [comment]
Fair enough, well replied. I guess that is why it is called Mobile Device Management (MDM).

**Comment by icelava** [comment]
@RAJU2529 If that is the case then all these details should be spelt out clearly and not leaving the reader to guess.

**Comment by RAJU2529** [comment]
@icelava . So in this case, let authors will decide what to do.

**Comment by illfated** [comment]
@e0i : Could you check with the author(s) if we may have a reply regarding this question and what a reasonable explanation would look like, something to add in the documentation?

**Comment by e0i** [comment]
@illfated The issue is in the backlog and a contributor is going to pick it soon. Thank you for pinging me on this. Much appreciated.

**Comment by MaratMussabekov** [comment]
Hello @icelava,
"Policy CSPs supported by Group Policy" - CSPs that have Group Policy analogues
"ADMX-backed policy CSPs" - Those "Policy CSPs supported by Group Policy" that requires special SyncML format to be enabled or disabled.
Thank you

**Comment by illfated** [comment]
Thank you. Happy to see the question replied to with a documentable answer. 🥇 🕺
