### ISSUE TITLE
Please state if enviroment variables and wildcards are supported for Exclusions

### ISSUE THREAD

**Issue by AlphaSeb** [MicrosoftDocs/windows-itpro-docs#6716]
You state that exclusions are supported for "Protect additional folders" but not if they are supported for "Allow specific apps to make changes to controlled folders" - I can not find this info anywhere. According to my tests it seems that wildcards and enviroment variables are not supported. But I'd love to hear a 100% feedback from MS on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 054326d9-bae7-e73f-c250-735f3863c32a
* Version Independent ID: f4b3c1fc-695b-2ba5-d5fe-747a9414441c
* Content: [Add additional folders and apps to be protected - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/customize-controlled-folders#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/customize-controlled-folders.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/customize-controlled-folders.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by AlphaSeb** [comment]
If the answer is no: How am I supposed to allow an application inside the users profile?

**Comment by RAJU2529** [comment]
@AlphaSeb . add the apps in the exclusion list

**Comment by AlphaSeb** [comment]
To add an app to the exclusion list, I have to specify the full path to the .exe file. How am I supposed to do that when the .exe file is in %USERPROFILE% and enviroment variables don't seem to work?

**Comment by RAJU2529** [comment]
@AlphaSeb , use  this   way, RAJU is my username 
**C:\Users\RAJU\myapp.exe**
type the following command in Powershell with admin rights 

**Add-MpPreference -ExclusionPath "C:\Users\RAJU\myapp.exe"**

**Comment by AlphaSeb** [comment]
@RAJU2529  I'm deploying this to several 100 computers, and I don't know the username...That's why we need enviroment variables.

**Comment by RAJU2529** [comment]
@AlphaSeb, after reading your reply, I tested on my windows laptop, Environment variables are supported.

i entered the following commands,


**Add-MpPreference -ExclusionPath "%userprofile%\adwcleaner.exe"
Add-MpPreference -ExclusionPath "%localappdata%\adwcleaner.exe"
Add-MpPreference -ExclusionPath "%appdata\adwcleaner.exe"**

**Comment by RAJU2529** [comment]
@AlphaSeb. the first command excludes the file 
**C:\Users\RAJU\adwcleaner.exe**

the second command excludes the file 
**C:\Users\RAJU\AppData\LocalLow\adwcleaner.exe**

the third  command excludes the file 
**C:\Users\RAJU\AppData\Roaming\dwcleaner.exe**

i would recommend you before deploying to user computers , test these commands in  reference computer

**Comment by e0i** [comment]
Passing the issue to an independent contributor for investigation. Thank you for the discussion so far.
