### ISSUE TITLE
Enabled and Worked 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#6717]
I already  setted this settings via  GPO without seeing this article, But the setting is working fine as indicated in the article.
This article also applies to windows 10 edition with Windows Defender Antivirus.
From my testing, I conformed Antivirus  Windows Defender Antivirus without ATP is working 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a395987-13bd-e303-f2de-9ae4e6949e16
* Version Independent ID: e42163a8-0d69-6981-7e5a-bf0f2075fb32
* Content: [Configure the Windows Defender AV cloud block timeout period - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-cloud-block-timeout-period-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-cloud-block-timeout-period-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/configure-cloud-block-timeout-period-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by e0i** [comment]
@RAJU2529, Thank you for pointing out to the accuracy of the article. Closing the issue as it seems that no problem(s) with the article have been implied. Please feel free to re-open if you think otherwise.
