### ISSUE TITLE
Inconsistent Supported Devices

### ISSUE THREAD

**Issue by slx-io** [MicrosoftDocs/windows-itpro-docs#6719]
At the top of this page, Surface Pro X is not included in the list of supported devices. However Surface Pro X is mentioned elsewhere throughout this page suggesting it is supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be36e174-5760-651b-f97a-b8466d4f877d
* Version Independent ID: 28d210d7-0d47-dd88-edd7-717533fbfa1d
* Content: [What’s new in Surface Dock 2 - Surface](https://docs.microsoft.com/en-us/surface/surface-dock-whats-new)
* Content Source: [devices/surface/surface-dock-whats-new.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-dock-whats-new.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @CoveMiner
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@slx-io . This question will be answered only by @CoveMiner

**Comment by illfated** [comment]
Somewhat indirect on the sales pages, but at least it seems to suggest that it is supported:
- Surface Pro X page: https://www.microsoft.com/en-us/surface/business/surface-pro-x
- The "**Accessories designed for Surface Pro X**" section on the Surface Pro X page shows "Surface Dock"
  and links to https://www.microsoft.com/en-us/surface/business/accessories

That page in turn links to https://www.microsoft.com/en-us/surface/business/accessories#coreui-multifeature-rg3yi2t where the following is listed:
- Surface Dock 2
- Surface USB-C Travel Hub
- Surface Adapters

This page shows Surface Pro X in addition to several other models. Not sure if that is enough to be valid as documentation, though.

**Comment by slx-io** [comment]
I don't think there's any question that it's supported. Keep it simple - you have a device, you have listed devices it supports, this particular document misses a device. That device needs to be added to ensure the document is accurate.

**Comment by illfated** [comment]
Thank you for your positive reply. I will get back to this soon to make a pull request for the requested change.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to receive reports on the existing documentation (factual error reports, improvement suggestions and update requests for new versions).

**Comment by MaratMussabekov** [comment]
Hello @slx-io ,
[Here](https://www.microsoft.com/en-us/p/surface-dock-2/8qd908364sg2?activetab=pivot:techspecstab) it is stated pretty clear (in the specs section), that Surface Pro X is supported.
I will add this info to the article.
Thank you
