### ISSUE TITLE
Create a bootable USB stick

### ISSUE THREAD

**Issue by steve6375** [MicrosoftDocs/windows-itpro-docs#672]
What type of bootable USB stick does it make? MBR-bootable and UEFI-bootable?
If UEFI, doesn't it need to be FAT32?
If FAT32, maximum size of any file is 4GB - what if install.esd is >4GB?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Service: **unspecified**
* GitHub Login: @mtniehaus
* Microsoft Alias: **greglin**

**Comment by egallagh** [comment]
Only the EFI partition on a UEFI device needs to be FAT32.
Check this out:
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/configure-uefigpt-based-hard-drive-partitions

Hope it helps.
Ed Gallagher

**Comment by steve6375** [comment]
I know the UEFI spec. That was not my question however. So it doesn't help.
The doc does not mention if the USB drive that is made is UEFI-bootable.
I want to know if it is as I have seen posts that it is not UEFI-bootable. The posts further go on to say that you should create an ISO and then make a USB drive from the contents of the ISO if you want UEFI booting.
Can someone clarify?

**Comment by egallagh** [comment]
Sorry, I was answering the question that you asked in the previous email: “If FAT32, maximum size of any file is 4GB - what if install.esd is >4GB?”
Install.esd would not be stored on the EFI partition that is required to be FAT32.

Ed

**Comment by egallagh** [comment]
So I took a look at the article.

If we are talking about the same section: “Create a bootable USB stick”, step 1 is insert the USB stick and step 2 is copy the MDTOfflineMedia\Content folder to the USB stick.
Therefor the USB stick must already be partitioned and formatted as either a MBR of UEFI/GPT disk.

At least that is my understanding of it.

Ed

**Comment by WLK33R** [comment]
You can use the Rufus utility to create a bootable UEFI with the MDT Offline Media ISO.

Step-by-step guide
Create a MDT 2013 media (ISO) file.
Start Rufus and insert the USB stick.
In Rufus, select File System to NTFS, and ISO image to your MDT 2013 ISO media.
Then select Partition scheme to GPT (it’s needs to be done in this order, otherwise Rufus changes the partition scheme when selecting the ISO).
Click Start
Go to a machine with UEFI enabled in BIOS, and boot on the USB.

See instructions - https://deploymentresearch.com/Research/Post/471/UEFI-and-NTFS-Friends-to-MDT-2013-at-last
