### ISSUE TITLE
What is the preference key Value for the edrEarlyPreviewEnabled?

### ISSUE THREAD

**Issue by annerajb** [MicrosoftDocs/windows-itpro-docs#6723]
right now the edrEarlyPreviewEnabled can be configured from the command line using
`sudo mdatp --edr --earlyPreview true` can this flag be set on the json file too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44a290d4-3386-7f63-0324-4e6219b5dd24
* Version Independent ID: 286954a7-372e-314f-ad9f-d12f5f55b79e
* Content: [Set preferences for Microsoft Defender ATP for Linux - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-preferences)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-preferences.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-preferences.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by stevenoneill** [comment]
Yes, because even with setting this to true, EDR does not appear to be enabled on Linux.  ATP is generally available, but does not appear to have all features available on all platforms just yet.  This needs to be made more clear.

**Comment by VLG17** [comment]
@stevenoneill just to be sure we're on the same page, you've enabled the Preview mode on one of your Linux **servers**, right? And you're not seeing the server in Microsoft Defender Security Center, or what exactly is missing?

Please make sure you are running one of the following supported distros:

> Microsoft Defender for Endpoint on Linux supports recent versions of the six most common Linux server distributions:
> 
> RHEL 7.2+
> CentOS Linux 7.2+
> Ubuntu 16 LTS, or higher LTS
> SLES 12+
> Debian 9+
> Oracle Linux 7.2
>

**Comment by VLG17** [comment]
@stevenoneill @annerajb just to be sure we're on the same page, you've enabled the Preview mode on one of your Linux **servers**, right? And you're not seeing the server in Microsoft Defender Security Center, or what exactly is missing?

Please make sure you are running one of the following supported distros:

> Microsoft Defender for Endpoint on Linux supports recent versions of the six most common Linux server distributions:
> 
> RHEL 7.2+
> CentOS Linux 7.2+
> Ubuntu 16 LTS, or higher LTS
> SLES 12+
> Debian 9+
> Oracle Linux 7.2
>

**Comment by stevenoneill** [comment]
@VLG17 We enable it.  We see it in the Security Center.  

What is missing is the **EDR** piece of ATP.  **EDR**.

EDR is the telemetry coming in, correct?  There doesn't appear to be any event/telemetry data to search for for Linux server instances.  By contrast, there's a vast amount of data and events from Windows instances.  For example, looking for things under advanced hunting using Kusto queries.

Like, if Windows send events from the various Event Logs, I'd expect to see things like auditd info from a RHEL 7 instance.

**Comment by VLG17** [comment]
@stevenoneill Keeping in mind the configuration is ok and you see it under Security Center, i would look further into troubleshooting the communication itself. You can try the steps described [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-support-connectivity). You could also simulate an attack to generate data, as described [here](https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/edr-for-linux-is-now-available-in-public-preview/ba-p/1890536).

We can help with documentation changes and updates, but technical issues, like the one you are describing, [should be handled by support](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/contact-support). 

Circling back to the initial question, @annerajb i don't see any other way to enable EDR (in the public docs) other than the sudo command.

**Comment by stevenoneill** [comment]
So it just became available 10 days ago according to this:

https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/edr-for-linux-is-now-available-in-public-preview/ba-p/1890536
