### ISSUE TITLE
Machine is not in use issue

### ISSUE THREAD

**Issue by mslsac** [MicrosoftDocs/windows-itpro-docs#6725]
As it currently stands if a computer is locked without any user activity for 7 days it will stop reporting to ATP. So if the computer get compromised by a lateral movement on the network or otherwise without a logged on user, it would not report to the ATP console. I have ran the detection script remotely (without directly logging into the device) on computers that were not reporting to the client and because of this issue ATP was not able to pick up the script and alert the console. Having the computer go into an inactive state and not report to the ATP console because there is not an active user logged into it does not mean it can not get infected, as the device is still turned on and connected to the network.

Either of the two following would most likely solve this issue for most tenant currently using ATP who want their network to be actually fully secured for all turned on devices connected to their network:
1. Turn this off so that there is not inactivity timeout
2. Allow admins to set the time-out period for their individual tenants

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5e07681-222a-ca3c-20f3-c98dabd935fa
* Version Independent ID: 6a9262d1-911f-bd4b-5366-7e6a0e31ca13
* Content: [Fix unhealthy sensors in Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/fix-unhealthy-sensors)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/fix-unhealthy-sensors.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/fix-unhealthy-sensors.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
Please consider sending your input via the Feedback Hub so that it gets addressed via the proper channels:

[Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

The issues section of this repository is intended for documentation and content-related issues.

Thank you.
