### ISSUE TITLE
Two hubs

### ISSUE THREAD

**Issue by starchysock** [MicrosoftDocs/windows-itpro-docs#6727]
What about using two Hubs in a video conference room with a third party PTZ camera, one Hub for the far end and the other for content? Is there a template for this type of operation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2476291-f855-fcfb-ae73-ab19b9065ee3
* Version Independent ID: 91fc4f9c-15a5-911b-1475-50698aeab96a
* Content: [Surface Hub 2S on-demand adoption and training videos - Surface Hub](https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-adoption-videos#feedback)
* Content Source: [devices/surface-hub/surface-hub-2s-adoption-videos.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/surface-hub-2s-adoption-videos.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by VLG17** [comment]
@starchysock You can [Miracast to multiple Hubs](https://docs.microsoft.com/en-us/surface-hub/miracast-over-infrastructure) so it should work.

Although it's not official Microsoft, but [this video](https://www.youtube.com/watch?v=ui0UcUteN5I) shows the capability exists.

**Comment by e0i** [comment]
@starchysock 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
