### ISSUE TITLE
"DHCP Administrators" missing

### ISSUE THREAD

**Issue by 768kb** [MicrosoftDocs/windows-itpro-docs#6728]
The Active Directory Group "DHCP Administrators" is not mentioned here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44e911d3-219e-19b8-4870-07514d9a94a1
* Version Independent ID: 960a7388-560b-90eb-e0ff-d8d2bb6f9a7a
* Content: [Active Directory Security Groups - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/active-directory-security-groups)
* Content Source: [windows/security/identity-protection/access-control/active-directory-security-groups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/access-control/active-directory-security-groups.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@janmadera . Which article are you referring

**Comment by janmadera** [comment]
Article URL:
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/access-control/active-directory-security-groups.md

**Comment by RAJU2529** [comment]
@janmadera .  This issue will be answered by the  Active Directory expert users. 
i am not an expert, so keep waiting for the reply.

**Comment by VLG17** [comment]
@768kb I see that not only "DHCP Administrators" but also "DHCP Users" is missing from this list. I think these groups are not mentioned because they are not a must when creating an AD domain, as per the first sentence: 

![image](https://user-images.githubusercontent.com/41186174/89503128-cb2a4000-d7ce-11ea-9258-d4448031e8a1.png)

**DNS is a must** when creating an AD domain (promoting the first DC), even with older OS versions, **but DHCP is not.**

2008 DC:

![image](https://user-images.githubusercontent.com/41186174/89503332-0e84ae80-d7cf-11ea-92ab-031e55381a2d.png)

2012 and above DC:

![image](https://user-images.githubusercontent.com/41186174/89503897-e34e8f00-d7cf-11ea-93e8-5e624811eef8.png)

**Comment by 768kb** [comment]
@VLG17 Thanks for explaining, this makes sense to me. I have to toughts for you:

1. If you go through the list of groups already listed in the article, you'll find "Hyper-V Administrators" and "IIS_IUSRS", which also are not directly related to Active Directory. How shall someone understand, why they are listed but DHCP is not?

2. Where else will you write the details about "DHCP Administrators" and others, if not centrally here in a article called "Active Directory Security Groups"?

In my oppinion, this list should not only explain groups created when installing Active Directory. It should list all groups which are created by default built-in Roles and Features of Windows Server OS (this excludes exchange and others).

**Comment by VLG17** [comment]
@768kb Fair point, you are right. I'll create a request to add the missing info, and let's see what happens.

**Comment by 768kb** [comment]
@VLG17 Thank you, I am anxiously waiting to see what happens next. :+1:

**Comment by e0i** [comment]
@DulceMontemayor @Dansimp You're authoritative input is needed to resolve this issue. The tests performed by independent contributor, @VLG17 show that the mentioned information should not be added to the article. Can you help decide a way to move forward? See discussion for details. Thank you.

**Comment by aczechowski** [comment]
My initial thought looking at this feedback is why this article is here, as this doc library is for Windows client. So let me check with our colleagues that work on Windows Server content and see if there's a better home for this information. I don't disagree that the list of groups should probably include others that are important like DHCP Admins, but I also want to make sure that we're organizing the content in the best place.

**Comment by aczechowski** [comment]
We just migrated this article (and a few others) to the Windows Server content, and I think they addressed this feedback at the same time. 
https://docs.microsoft.com/windows-server/identity/ad-ds/manage/understand-security-groups
So I'm closing this feedback. If you have any further comments, please open new feedback on the new article.
