### ISSUE TITLE
User targeted vs. Device targeted configuration - Issues and Clarification

### ISSUE THREAD

**Issue by GethinMorris** [MicrosoftDocs/windows-itpro-docs#673]
The below sentence does not read properly and is confusing please could it be clarified:
"For CSPs and policies that supports per user configuration, MDM server could send user targeted setting values to the device the user that enrolled MDM is actively logged in"

Also could you provide more information on what 'others – another user login but that user does not have an MDM account.' means. 
When paired with the bullet above it suggests that only users that have directly registered the device can get user policies applied and any other user using that device will not get user policies. What implications does this have for bulk enrolled devices (i.e. provisioning package) where no 'user' has directly registered the device? Does that mean that no user policies will apply to the device (i.e. all users will be classed as 'others')?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de30f8b-0039-3cb5-0b38-8064d8fb2a3a
* Version Independent ID: f2968413-2951-5c42-dd5a-2a0b974338ca
* Content: [OMA DM protocol support](https://docs.microsoft.com/en-us/windows/client-management/mdm/oma-dm-protocol-support#user-targeted-vs-device-targeted-configuration)
* Content Source: [windows/client-management/mdm/oma-dm-protocol-support.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/oma-dm-protocol-support.md)
* Service: **unspecified**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by nenonix** [comment]
@GethinMorris I am researching your query and although I can see issues of grammar that could be cleaned up, I am not sure if I can address this by way of a content edit. It has been some time since you submitted this issue, have you perhaps found answers elsewhere or can you assist me with suggestions of how the content could be edited or improved?

**Comment by nenonix** [comment]
@GethinMorris Thanks for bringing this to our attention. I will fix the grammatical issues in the content. As to your query: by default if no user-targeted or device-targeted settings are stipulated then it is a device targeted configuration.
