### ISSUE TITLE
Conversion/Replacement from slmgr to VAMT

### ISSUE THREAD

**Issue by thomashesse** [MicrosoftDocs/windows-itpro-docs#6730]
So far we have only managed the keys with slmgr. Are all existing keys automatically taken over by the installation of the VAMT (on the same system) or can at least be imported? Or are the keys lost or does the changeover lead to downtimes?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 01910332-8f6f-c844-6594-d9da807492c5
* Version Independent ID: 13b107a6-b139-671d-d3bd-d53b2de74fdd
* Content: [Installieren des VAMT (Windows 10) - Windows Deployment](https://docs.microsoft.com/de-de/windows/deployment/volume-activation/install-vamt)
* Content Source: [windows/deployment/volume-activation/install-vamt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/volume-activation/install-vamt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by VLG17** [comment]
@thomashesse VAMT is not a replacement of using slmgr.vbs. They are meant to work together. You can find more details [here](https://docs.microsoft.com/en-us/deployoffice/vlactivation/tools-to-manage-volume-activation-of-office) and [here](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn502539(v=ws.11))
