### ISSUE TITLE
Replacement solution for Update Compliance Defender AV reports? Please update article.

### ISSUE THREAD

**Issue by TechTrooper** [MicrosoftDocs/windows-itpro-docs#6731]
How can we monitor Defender AV now that you have removed it from Update Compliance?

The link in this article is directing us to old legacy silverlight portal instructions...
https://docs.microsoft.com/en-us/mem/intune/fundamentals/help-secure-windows-pcs-with-endpoint-protection-for-microsoft-intune

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8062ff-27b0-40ae-92b5-2f1dc851ad54
* Version Independent ID: 5c52fdc9-18e1-56cd-afe3-86db6ca4bbb0
* Content: [Monitor Windows Updates and Windows Defender AV with Update Compliance (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-monitor)
* Content Source: [windows/deployment/update/update-compliance-monitor.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-monitor.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@chinglis can you help with this?

**Comment by chinglis** [comment]
+ @David Mebane<mailto:davidmeb@microsoft.com>, @Shweta Jha<mailto:Shweta.Jha@microsoft.com>, @Thomas Trombley<mailto:thtrombl@microsoft.com>

Shweta,

The articles linked are for classic Intune, and customer is asking for an updated location of where endpoint protection docs are. Can you help me find the right documentation to point customers to for all the alternatives (MEM, security center, ATP).

Overall the feedback from internal FastTrack & Support folks is that the link to MEM documentation alone wasn’t really sufficient. I have extremely limited context in the Antivirus reporting area so can’t really handle this solo.

Thank you 😊

Charles

**Comment by chinglis** [comment]
@Mahyar Ghadiali<mailto:mghadial@microsoft.com> – now that you work on Intune Security, maybe you can help here. ☺

We deprecated Windows Defender AV reporting and based on guidance from @Shweta Jha<mailto:Shweta.Jha@microsoft.com> our understanding is that MEM has various options available to customers today as a replacement. Most customers using the Defender AV report were E3, so this should be generally available to them. Can you help us find the right link in Intune documentation to point customers to who wish to see their AV status and such?

Thanks,
David

From: Charles Inglis <chinglis@microsoft.com>
Sent: Thursday, May 14, 2020 8:16 AM
To: MicrosoftDocs/windows-itpro-docs <reply@reply.github.com>; MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>; David Mebane <davidmeb@microsoft.com>; Shweta Jha <Shweta.Jha@microsoft.com>; Thomas Trombley <thtrombl@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/windows-itpro-docs] Replacement solution for Update Compliance Defender AV reports? Please update article. (#6731)

+ @David Mebane<mailto:davidmeb@microsoft.com>, @Shweta Jha<mailto:Shweta.Jha@microsoft.com>, @Thomas Trombley<mailto:thtrombl@microsoft.com>

Shweta,

The articles linked are for classic Intune, and customer is asking for an updated location of where endpoint protection docs are. Can you help me find the right documentation to point customers to for all the alternatives (MEM, security center, ATP).

Overall the feedback from internal FastTrack & Support folks is that the link to MEM documentation alone wasn’t really sufficient. I have extremely limited context in the Antivirus reporting area so can’t really handle this solo.

Thank you 😊

Charles

**Comment by chinglis** [comment]
David Mebane would like to recall the message, "[MicrosoftDocs/windows-itpro-docs] Replacement solution for Update Compliance Defender AV reports? Please update article. (#6731)".

**Comment by jaimeo** [comment]
@cinglis-msft can you address this?

**Comment by cinglis-msft** [comment]
yes, it is addressed in documentation. there are alternatives, that being said, they are not 1:1.
