### ISSUE TITLE
Clarification around this note... please...

### ISSUE THREAD

**Issue by quickclix75** [MicrosoftDocs/windows-itpro-docs#6732]
Please can you clarify this Note as I am wrking with a client using the VPN Short lived cert issued from Azure AD to access on prem resource. thanks

Note
Currently, it is required that certificates be issued from an on-premises CA, and that SSO be enabled in the user’s VPN profile. This will enable the user to obtain Kerberos tickets in order to access resources on-premises. Kerberos currently does not support the use of Azure AD certificates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b6faee7-5e59-c367-075d-5517d3af4f75
* Version Independent ID: e6d377d5-267e-ec54-3769-6d5863ef6936
* Content: [VPN and conditional access (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-conditional-access)
* Content Source: [windows/security/identity-protection/vpn/vpn-conditional-access.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/vpn/vpn-conditional-access.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @quickclix75 ,
agree, current wording is pretty confusing.
The note means that Azure AD certificates used for establishing VPN connections, but not to providing access to on-premises resources. For users to be able to access these resources, certificates issued by on-premises CA must be deployed to the Windows profiles of the users, and their VPNv2 profiles must contain the <SSO> section.
Thank you

**Comment by e0i** [comment]
@quickclix75  Upon your feedback, We have updated the content with relevant changes accordingly via PR #8293.
