### ISSUE TITLE
What does "Not Used" mean?

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/windows-itpro-docs#6734]
Trying to help answer a question from this Tech Community Forum post, what does "Not Used" mean in the table above?
https://techcommunity.microsoft.com/t5/microsoft-defender-atp/scheduled-scans-with-defender-av-with-atp/m-p/1387560#M465

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a67d9ad-6858-0503-8020-b874b70fb336
* Version Independent ID: 91bd6142-d580-58a8-77ce-024d119daa87
* Content: [Configure Windows Defender Antivirus with Group Policy - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/use-group-policy-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/use-group-policy-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/use-group-policy-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@itguysocal. That means, the specified article is not yet created.

**Comment by VLG17** [comment]
@itguysocal I guess @RAJU2529 answered your question. Can we help with anything else? Do you think we need to add something to the article to make this more clear?

**Comment by illfated** [comment]
There are some unanswered questions out there whether those settings were created for future use, or maybe no longer used (deprecated) and should therefore not be changed, because they might be removed in the future. Such questions appear mostly in connection with more general questions about regular scheduled scans, which used to be a more common policy for legacy protection software.

Maybe a note could be added that those settings should not be changed, because they are not meant to be used or could cause undocumented behaviour.

**Comment by VLG17** [comment]
@illfated My understanding is that the settings exist and can be used but there is no article created to describe them in detail. I think it would be best to hear the author's opinion here.

@nam31 could you help with reaching out to the author for a confirmation regarding what "not used" means in this context?

**Comment by nam31** [comment]
@denisebmsft can you please help here?

**Comment by denisebmsft** [comment]
@itguysocal thank you for posting this question. And @illfated @VLG17 @nam31 @RAJU2529 thank you for your help. 

In this article, "Not used" means that item is no longer relevant. It's carryover stuff from the former versions of antivirus (like Windows Live Security Essentials). It isn't the case that we don't have content for those items yet.

I have updated the article and you will see the changes live on the site later today.

**Comment by denisebmsft** [comment]
The docs have been updated with links to the new articles. https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/use-group-policy-microsoft-defender-antivirus?view=o365-worldwide
