### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by gene0486** [MicrosoftDocs/windows-itpro-docs#6735]
Under "Deployment" section... the statement "... Device Management Admin Console are now are Microsoft Endpoint Manager" is incorrect. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a7f713-d59f-01cf-bd6b-d41e8889cfc8
* Version Independent ID: dc8641da-26b5-1657-cc25-d5dd00ae84d7
* Content: [What's new in Windows 10, version 1909 - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1909#feedback)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1909.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/whats-new-windows-10-version-1909.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@gene0486.  **Device Management Admin Console is renamed to Microsoft Endpoint Manager**

will you accept the above statement?

**Comment by greg-lindsay** [comment]
There's no need to change it very much. There is just a single word ("are") that is repeated and needs to be deleted.

**Comment by greg-lindsay** [comment]
Closing this as I am correcting  it in the private repo.
