### ISSUE TITLE
Can enhanced startup PIN be enabled via Intune?

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/windows-itpro-docs#6737]
I can see how to do it via GPO but we want to use Intune only for AzureAD-joined devices

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feb93192-b78b-a16b-c174-f83e024aa4c4
* Version Independent ID: d7dd6ccd-f984-48d0-49ff-2f5383001fd9
* Content: [BitLocker Key Management FAQ (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-key-management-faq)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-key-management-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-key-management-faq.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @thommck,
unfortunately, Bitlocker CSP doesn't cover this feature (at least currently).
If GPO is not an option, I would recommend to create a PowerShell script that set HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\FVE\UseEnhancedPin value to 1, and deploy it to the machines using Intune.
Thank you

**Comment by mypil** [comment]
@thommck - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @MaratMussabekov so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
