### ISSUE TITLE
Intune MDM equivalents

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/windows-itpro-docs#6738]
Can you point out where the equivalent way of applying these settings via Intune are, rather than Group Policy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5476099c-9d70-97df-8ee6-bc442605cfbd
* Version Independent ID: 49ca0628-bd88-e05b-b705-3b361b57512d
* Content: [BitLocker Group Policy settings (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings#see-also)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-group-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello, not all the policies could be set via intune. 
Available bitlocker policies are described [here](https://docs.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp)
Thank you

**Comment by mypil** [comment]
@thommck - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @MaratMussabekov  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
