### ISSUE TITLE
MultiSubnetFailover?

### ISSUE THREAD

**Issue by Aaron-** [MicrosoftDocs/windows-itpro-docs#674]
Github documentation states you may change the MANAGEMENT_SQL_CONNECTION_STRING to add a failover partner in case of SQL mirroring. Is it a supported scenario as well to add 'MultiSubnetFailover=True' when utilizing SQL Always on? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a31de562-fa30-ba13-c087-042b2fac2ebd
* Version Independent ID: c6dec2d0-9187-e605-8f4b-d7106f190c49
* Content: [Planning for High Availability with App-V Server](https://docs.microsoft.com/en-us/windows/application-management/app-v/appv-planning-for-high-availability-with-appv)
* Content Source: [windows/application-management/app-v/appv-planning-for-high-availability-with-appv.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/app-v/appv-planning-for-high-availability-with-appv.md)
* Service: **unspecified**
* GitHub Login: @MaggiePucciEvans
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by msbemba** [comment]
@Aaron-  Thank you for the feedback. Specifying MultiSubnetFailover=True when utilizing SQL Always on is supported. However, when connecting to something other than an availability group listener or SQL Server 2012 Failover Cluster Instance may result in a negative performance impact, and is not supported.  More information on Sqlclient support for High availability can be found in the below document.

https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/sqlclient-support-for-high-availability-disaster-recovery

**Comment by mypil** [comment]
@Aaron- thank you for submitting feedback.

From our understanding, the issue has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
