### ISSUE TITLE
Surface Go2

### ISSUE THREAD

**Issue by mdwaseem05** [MicrosoftDocs/windows-itpro-docs#6740]
Hello, 

Surface Go 2  SKU info not listed here 

System Model   Surface Go 2
System Type      x64-based PC
System SKU        Surface_Go_2_1927

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de75f7d-a749-ec5f-435b-62bc163a2b72
* Version Independent ID: 8d221f64-7c6b-d604-3dfa-51d8b9163a3f
* Content: [Surface System SKU reference - Surface](https://docs.microsoft.com/en-us/surface/documentation/surface-system-sku-reference#feedback)
* Content Source: [devices/surface/documentation/surface-system-sku-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/documentation/surface-system-sku-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @CoveMiner
* Microsoft Alias: **v-jokai**

**Comment by mypil** [comment]
@mdwaseem05 - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/5a24c8f10151fc1f05a3f365e32acee19d1e898e. 


Thank you for your contribution to make the docs better! Much appreciated!
