### ISSUE TITLE
ID de evento incorrecto o reemplazado por palabras

### ISSUE THREAD

**Issue by illfated** [MicrosoftDocs/windows-itpro-docs#6741]
From issue ticket #4775 (**Error Event ID is invalid**) by @AmadorM :

> I have encountered the same problem comparing the Spanish version of the article with the English version. In the event table for script execution.
>
> ![E](https://user-images.githubusercontent.com/51479071/82042284-eb53d280-96a9-11ea-8bd3-0ea3d5a3953a.png)
>
> ![S](https://user-images.githubusercontent.com/51479071/82042293-edb62c80-96a9-11ea-9967-590bc301acbf.png)

@TinaMcN : May we have a human translation inspection for the Spanish version also?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 13006cbf-ad22-e75a-bf3a-2a6d0b92f088
* Version Independent ID: c9a7a12f-2ef5-b5fa-b515-41ecce5fecd1
* Content: [Solucionar problemas de incorporación ATP de Microsoft defender - Windows security](https://docs.microsoft.com/es-es/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-onboarding#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/troubleshoot-onboarding.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-onboarding.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
@AmadorM : Por favor, siga este ticket para obtener actualizaciones con respecto a los problemas de la tabla.

Please follow this ticket to get updates regarding the table issues.

**Comment by mypil** [comment]
@TinaMcN @officeglobal - Can you please assist with this translation/localization issue?

Thank you.

**Comment by illfated** [comment]
Here are the Spanish tables containing translated or incorrectly handled error ID numbers:

***
Id. de evento | Tipo de error | Pasos de resolución
-- | -- | --
4 | Se encontraron datos de incorporación, pero no se pudieron eliminar | Revisa los permisos en el Registro, específicamente HKLM\SOFTWARE\Policies\Microsoft\Windows Advanced Threat Protection.
base10 | No se pudieron escribir datos de incorporación en el Registro | Revisa los permisos en el Registro, específicamenteHKLM\SOFTWARE\Policies\Microsoft\Windows Advanced Threat Protection.Compruebe que el script se ha ejecutado como administrador.
4,5 | No se pudo iniciar el servicio de SENSE | Comprueba el estado del servicio (comando sc query sense). Asegúrate de que no está en un estado intermedio ('Pending_Stopped', 'Pending_Running') e intenta ejecutar de nuevo el script (con derechos de administrador).Si el equipo ejecuta Windows 10, versión 1607 y la ejecución del comando sc query sense vuelve START_PENDING, reinicie el equipo. Si al reiniciar la máquina no se soluciona el problema, actualiza a KB4015217 y vuelve a intentar la incorporación de nuevo.
4,5 | No se pudo iniciar el servicio de SENSE | Si el mensaje del error es: se ha producido el error de sistema 577 o el error 1058. Tienes que habilitar el controlador ELAM de Antivirus de Windows Defender. Consulta Asegurarse de que Antivirus de Windows Defender no esté deshabilitado por una directiva para obtener instrucciones.
0,30 | El script no pudo esperar a que el servicio empezara a ejecutarse | El servicio pudo haber tardado mucho en iniciarse o se produjeron errores cuando intentaba iniciarse. Para obtener más información sobre eventos y errores relacionados con el sentido, consulte revisar eventos y errores con el visor de eventos.
35 | El script no encontró el valor del Registro de estado de incorporación necesario | Cuando se inicia por primera vez, el servicio de SENSE escribe el estado de incorporación en la ubicación del RegistroHKLM\SOFTWARE\Microsoft\Windows Advanced Threat Protection\Status.El script no lo encontró después de unos segundos. Puedes probarlo manualmente y comprobar si existe. Para obtener más información sobre eventos y errores relacionados con el sentido, consulte revisar eventos y errores con el visor de eventos.
40 | El estado de incorporación del servicio de SENSE no está establecido en 1 | El servicio de SENSE no se incorporó correctamente. Para obtener más información sobre eventos y errores relacionados con el sentido, consulte revisar eventos y errores con el visor de eventos.
65 | Privilegios insuficientes | Vuelve a ejecutar el script con privilegios de administrador.

***
**Problemas conocidos de no cumplimiento**

La siguiente tabla ofrece información sobre problemas de no cumplimiento y cómo puede resolver los problemas.

Caso | Síntomas | Posible causa y pasos de solución de problemas
-- | -- | --
uno | La máquina es conforme al identificador SenseIsRunning OMA-URI. Pero no es conforme a los identificadores OrgId, Onboarding y OnboardingState OMA-URI. | Posible causa: comprueba que el usuario pasó la configuración rápida después de la instalación o actualización de Windows. No se pudo completar la incorporación de configuración rápida pero SENSE ya se está ejecutando.Pasos de solución de problemas: espera a que se complete la configuración rápida.
1 | La máquina es conforme a los identificadores OrgId, Onboarding y OnboardingState OMA-URI, pero no es conforme al identificador SenseIsRunning OMA-URI. | Posible causa: el tipo de inicio del servicio de Sense se estableció como "inicio retrasado". A veces, esto hace que el servidor de Microsoft Intune notifique que la máquina no es conforme a SenseIsRunning cuando se produce la sesión de DM al inicio del sistema.Pasos de solución de problemas: el problema debe corregirse en un plazo de 24 horas.
2 | la máquina no es conforme | Pasos de solución de problemas: asegúrate de que las directivas de incorporación y retirada no se implementaron a la vez en la misma máquina.

***

Id. de evento | Mensaje | Pasos de resolución
-- | -- | --
4 | El servicio de protección contra amenazas avanzada de Microsoft defender no se pudo conectar al servidor en la variable | Asegúrese de que el equipo tiene acceso a Internet.
6 | El servicio de protección contra amenazas avanzada de Microsoft defender no se incorpora y no se encontraron parámetros de integración. Código de error: variable | Vuelve a ejecutar el script de incorporación.
siete | El servicio de protección contra amenazas avanzada de Microsoft defender no pudo leer los parámetros de integración. Código de error: variable | Asegúrese de que el equipo tiene acceso a Internety, a continuación, ejecute todo el proceso de incorporación de nuevo.
99,999 | El servicio de protección contra amenazas avanzada de Microsoft defender no pudo cambiar su tipo de inicio. Código de error: variable | Si el evento se produjo durante la incorporación, reinicia y vuelve a intentar ejecutar el script de incorporación. Para obtener más información, consulta Vuelve a ejecutar el script de incorporación.Si el evento se produjo durante la eliminación, ponte en contacto con soporte técnico.
base10 | El servicio de protección contra amenazas avanzada de Microsoft defender no pudo persistir la información de incorporación. Código de error: variable | Si el evento se produjo durante la incorporación, vuelve a intentar ejecutar el script de incorporación. Para obtener más información, consulta Vuelve a ejecutar el script de incorporación.Si el problema continúa, ponte en contacto con soporte técnico.
4,5 | Protección contra amenazas avanzada de Microsoft defender no se puede iniciar el canal de comandos con la dirección URL: variable | Asegúrese de que el equipo tiene acceso a Internet.
apartado | El servicio de protección contra amenazas avanzada de Microsoft defender no pudo cambiar la ubicación del servicio de telemetría y experiencias del usuario conectado. Código de error: variable | Vuelve a ejecutar el script de incorporación. Si el problema continúa, ponte en contacto con soporte técnico.
veinticinco | El servicio de protección contra amenazas avanzada de Microsoft defender no pudo restablecer el estado de mantenimiento en el registro. Código de error: variable | Ponte en contacto con soporte técnico.
,27 | Error al habilitar el modo de protección contra amenazas avanzada de Microsoft defender en Windows Defender. No se pudo procesar la incorporación. Código de error: variable | Ponte en contacto con soporte técnico.
32 | No se pudieron leer los parámetros de eliminación. Tipo de error: %1, código de error: %2, descripción: %3 | Asegúrese de que el equipo tiene acceso a Internet y, a continuación, ejecute todo el proceso de descarga.
0,30 | Error al deshabilitar el modo $ (compilación. Sense. productDisplayName) en protección contra amenazas avanzada de Microsoft defender. Código de error: %1 | Ponte en contacto con soporte técnico.
32 | El servicio $(build.sense.productDisplayName) no pudo solicitar detenerse después del proceso de eliminación. Código de error: %1 | Comprueba que el tipo de inicio del servicio es manual y reinicia la máquina.
55 | No se pudo crear el registrador automático de Secure ETW. Código de error: %1 | Reinicia la máquina.
63 | Actualiza el tipo de inicio del servicio externo. Nombre: %1, tipo de inicio real: %2, tipo de inicio esperado: %3, código de salida: %4 | Identifica qué está provocando cambios en el tipo de inicio de dicho servicio. Si el código de salida no es 0, corrige el tipo de inicio manualmente al tipo de inicio esperado.
64 | Inicio de un servicio externo detenido. Nombre: %1, código de salida: %2 | Si el evento sigue apareciendo, ponte en contacto con soporte técnico.
68 | El tipo de inicio del servicio es inesperado. Nombre del servicio: %1, tipo de inicio real: %2, tipo de inicio esperado: %3 | Identifica qué está provocando los cambios en el tipo de inicio. Corrige el tipo de inicio de servicio mencionado.
69 | El servicio está detenido. Nombre del servicio: %1 | Inicia el servicio mencionado. Si el problema continúa, ponte en contacto con soporte técnico.

***
These 3 tables are in effect all the non-graphic tables on this page. For some reason, the Machine Translation has decided that it is OK to translate numbers/digits/integers and also replace them with a different number, like a decimal fraction or unknown ordering system (like translating **1** - **2** - **3** or using random conversions to decimals, regardless of increasing original order or not.

A possible workaround could be to surround all the table numbers with MarkDown backticks in the English (/en-us/) version of the article, but it looks a bit odd when there seems to be no other need for this than blocking translation for numbers (which should not be happening in the first place).

**Comment by illfated** [comment]
If making a request to the Machine Translation provider becomes more complicated than expected, feel free to ask me for a Pull Request to the English (/en-us/) page to have the numbers surrounded by MarkDown backticks, isolating the numbers from translation and showing them as a monospaced font/typeface.

**Comment by mypil** [comment]
@OfficeGlobal @TinaMcN - Do you have any updates on this?

Thank you.

**Comment by illfated** [comment]
As previously mentioned, I offer to create a pull request to have those numbers surrounded by MarkDown back ticks to encapsulate them (and possibly isolate them) from being translated. I will leave it to the localization team to decide which solution you prefer in this case.

**Comment by mypil** [comment]
@illfated - Thank you for offering to create the PR, maybe that will be a good approach. Can you please create the PR for this? I can tag the author to get their help to review and approve it for merging.

As always, we really appreciate your proactive and kind assistance to help improve our docs.
