### ISSUE TITLE
Broken link(WMR for LTSC 1809)

### ISSUE THREAD

**Issue by nisaev** [MicrosoftDocs/windows-itpro-docs#6742]
https://software-download.microsoft.com/download/pr/microsoft-windows-holographic-desktop-fod-package31bf3856ad364e35amd64_1.cab
This link is broken. Got 403 error.
https://docs.microsoft.com/en-us/windows/application-management/manage-windows-mixed-reality#enable-windows-mixed-reality-in-wsus

**Comment by RAJU2529** [comment]
@nisaev . Which article are you referring?

**Comment by illfated** [comment]
- Microsoft Docs page: https://docs.microsoft.com/en-us/windows/application-management/manage-windows-mixed-reality
- GitHub page: https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/application-management/manage-windows-mixed-reality.md
***
## Enable Windows Mixed Reality in WSUS

1. [Check your version of Windows 10.](https://support.microsoft.com/help/13443/windows-which-operating-system)

   > [!NOTE]
   > You must be on at least Windows 10, version 1709, to run Windows Mixed Reality.

2. Windows Mixed Reality Feature on Demand (FOD) is downloaded from Windows Update. If access to Windows Update is blocked, you must manually install the Windows Mixed Reality FOD.

   a. Download the FOD .cab file for [Windows 10, version 1903 and 1909](https://software-download.microsoft.com/download/pr/Microsoft-Windows-Holographic-Desktop-FOD-Package-31bf3856ad364e35-amd64.cab), [Windows 10, version 1809](https://software-download.microsoft.com/download/pr/microsoft-windows-holographic-desktop-fod-package31bf3856ad364e35amd64_1.cab), [Windows 10, version 1803](https://download.microsoft.com/download/9/9/3/9934B163-FA01-4108-A38A-851B4ACD1244/Microsoft-Windows-Holographic-Desktop-FOD-Package~31bf3856ad364e35~amd64~~.cab), or [Windows 10, version 1709](https://download.microsoft.com/download/6/F/8/6F816172-AC7D-4F45-B967-D573FB450CB7/Microsoft-Windows-Holographic-Desktop-FOD-Package.cab).

   > [!NOTE]
   > You must download the FOD .cab file that matches your operating system version.

***
**Reported link:** [Windows 10, version 1809](https://software-download.microsoft.com/download/pr/microsoft-windows-holographic-desktop-fod-package31bf3856ad364e35amd64_1.cab)
(https://software-download.microsoft.com/download/pr/microsoft-windows-holographic-desktop-fod-package31bf3856ad364e35amd64_1.cab)

## 403 - Forbidden

**Comment by RAJU2529** [comment]
@nisaev .  That file is not available for download, but you can install on Feature on Demand  option by using Dism.exe online cmd 
**Dism /Online /Add-Capability /CapabilityName:Analog.Holographic.Desktop~~~~0.0.1.0**

for more information, viist below official site 
**https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/features-on-demand-non-language-fod**

**Comment by denisebmsft** [comment]
Thank you @RAJU2529. It looks like this issue is resolved, yes? Closing.
