### ISSUE TITLE
What a headache! Hours wasted just cuz Microsoft likes to makes things more complicated...

### ISSUE THREAD

**Issue by Neckross** [MicrosoftDocs/windows-itpro-docs#6745]
Windows 10 Administrative Templates for Windows 10 November 2019 Update 1909
Windows 10 Administrative Templates for Windows 10 May 2019 Update 1903
Windows 10 Administrative Templates for Windows 10 October 2018 Update 1809
Windows 10 Administrative Templates for Windows 10 April 2018 Update 1803

Device credential or User credential options? why? why? why?
This has worked so well in the past since ADMX 1709, but nonetheless lets go the Microsoft recommended way... So, tested first 1909 using User credentials... never enrolls automatically MDM to Intune. Tested Device credentials... same deal. Uninstalled 1909 ADMX, installed 1803 (which doesn't give you an option to choose Device/User credentials but rather just "Enabled" or "Disabled" and nothing else, simple. Force gpupdate, 2 restarts, 2 ADsync deltas, and boom the HDJ now is MDM managed by Intune. What 5 hours wasted trying to do the Microsoft way, end up using the old method in 5 minutes.

If you're gonna release an option Device/User credentials... at least test it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@Neckross - Thank you for providing feedback.


Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the **[Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)**. You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
