### ISSUE TITLE
Antivirus Exclusions for WDAG

### ISSUE THREAD

**Issue by teojaimes** [MicrosoftDocs/windows-itpro-docs#6747]
Where can I get Microsoft's suggested AV exclusions specifically for devices that have WDAG installed/enabled?  Adding this info to this Q&A section would be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8927df09-e9aa-8c40-290d-0ca7d86ec4e2
* Version Independent ID: ca67bcfc-6120-d6ca-290b-1a7822494c73
* Content: [FAQ - Windows Defender Application Guard (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@teojaimes . Here is the document. 
**https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus**

**Comment by teojaimes** [comment]
Thanks for the reply. I am familiar with that document and does provide some Hyper-v exclusion recommendations but nothing specific to WDAG. Any WDAG specific and MS official recommendations would be very helpful.

**Comment by e0i** [comment]
@denisebmsft It seems authoritative input is needed here. Please let us know whether any assistance from independent contributors needed. Thank you.

**Comment by denisebmsft** [comment]
@e0i thank you, and will do.

**Comment by teojaimes** [comment]
@denisebmsft any update on this? Thanks.

**Comment by denisebmsft** [comment]
@e0i if we could get some assistance from independent contributors, that would be great. I'd welcome the help.

**Comment by e0i** [comment]
@denisebmsft Added to the backlog to be passed to the contributors.

**Comment by VLG17** [comment]
@teojaimes could you share some more details regarding this question? In my understanding, the Application Guard functionality does not intersect that of Windows Defender Antivirus.

What are you looking to exclude?

**Comment by teojaimes** [comment]
@VLG17 I was hoping to get Microsoft's official recommendations on which WDAG related  processes, files, and directories are recommended for AV exclusion. The goal is to help WDAG isolated browsing session performance. Thanks.

**Comment by e0i** [comment]
@denisebmsft 

In an independent contributor's investigation, the related information has not been found as it seems not public and that there seems to be no explicit exclusions for the mentioned service. Would you be able to provide official clarification on this question? Specifically, exclusion lists for WDAG and Hyper-V?
Thank you

**Comment by denisebmsft** [comment]
Thanks, @e0i. We'll get this handled soon. Appreciate your help!

**Comment by sazankha** [comment]
There is no exclusion list required in AV for MDAG/WDAG to function.

**Comment by levinec** [comment]
Thank you @sazankha! Closing this issue due to the answer provided by the PM team.
