### ISSUE TITLE
Works on Surface Laptop 3?

### ISSUE THREAD

**Issue by Lucent** [MicrosoftDocs/windows-itpro-docs#6748]
With Surface UEFI Manager installed and loading the assembly with
[System.Reflection.Assembly]::LoadFile("C:\ProgramData\Microsoft\Surface\Devices\SurfaceUefiManager.dll")
I can read settings with Microsoft.Surface.UefiManager, but any attempt to use Microsoft.Surface.FirmwareOption methods like Find result in errors like:
"Exception calling "Find" with "1" argument(s): "Object reference not set to an instance of an object."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee0ed36d-86b7-cf11-5d81-056c9d50d973
* Version Independent ID: bb4ce7c6-c9d1-e003-bfcf-1b39ac5c6a37
* Content: [Advanced UEFI security features for Surface Pro 3 (Surface) - Surface](https://docs.microsoft.com/en-us/surface/advanced-uefi-security-features-for-surface-pro-3#feedback)
* Content Source: [devices/surface/advanced-uefi-security-features-for-surface-pro-3.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/advanced-uefi-security-features-for-surface-pro-3.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @CoveMiner
* Microsoft Alias: **v-jokai**

**Comment by e0i** [comment]
@Lucent

Can you clarify whether your feedback relates to one of the code examples within the article?
