### ISSUE TITLE
How to disable Kernel DMA Protection

### ISSUE THREAD

**Issue by pl6306** [MicrosoftDocs/windows-itpro-docs#6750]
I have an external gpu enclosure running on thunderbolt. Please let me know how to disable or uninstall Kernel DMA Protection. This keeps crashing my windows! I have checked my BIOS there is no option. This isn't a hardware issue because I dual boot ubuntu and it is rock solid!

![msinfo](https://user-images.githubusercontent.com/173334/82131816-43bcca00-97a7-11ea-83ab-822151ff6154.png)

![1588997845556](https://user-images.githubusercontent.com/173334/82131789-09532d00-97a7-11ea-8166-c3bd27b8e70c.jpeg)

![1588997845554](https://user-images.githubusercontent.com/173334/82131791-0bb58700-97a7-11ea-99be-d6439a6bbee3.jpeg)

**Comment by RAJU2529** [comment]
@pl6306 . Use group policy Editor to disable kernel dma protection. Or modify registry keys

**Comment by denisebmsft** [comment]
It looks like this issue is resolved (thank you @RAJU2529). Closing.

**Comment by pl6306** [comment]
Where is in the group policy edit? Which registry key is it?

**Comment by pl6306** [comment]
If you think it is setting DeviceEnumerationPolicy to 2 to allow all. It isn't. Please put down which registry to change and to what value to turn it completely off

**Comment by e0i** [comment]
Passing this feedback to a collaborator. Thanks.

**Comment by MaratMussabekov** [comment]
Hello @pl6306 ,
Do you have registry key HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\FVE\DisableExternalDMAUnderLock?
If yes, which value does it have?
**I have checked my BIOS there is no option** - have you checked Security>Virtualization tab?

Thank you

**Comment by e0i** [comment]
@pl6306 Feel free to re-open to follow up with the response above. Thank you.

**Comment by AndyODFO** [comment]
This is still a problem and the regedit above does not solve it. It does not turn off DMA kernel protection, which is causing our Thunderbolt devices to disconnect. (Sonnet Echo chassis with a Blackmagic Design Decklink Quad 2 inside) 
We also have a Lenovo laptop, a Legion 7. Lenovo has removed the option to disable Kernel DMA protection from the UEFI bios and removed the possibility of accessing legacy bios for older machines.

**Comment by mtmoroni** [comment]
a google search lead me here to disabling DMA kernel on a Lenovo.  However, my Carbon X1 9th gen with TB4 does have a bios option of disabling kernel DMA - but yet, msinfo32 says its still on.

What was the resolution to this thread?

**Comment by AndyODFO** [comment]
With the help of a Lenovo admin logon to BIOS I was able to force DMA kernel protection off. It was the IOMMU option nested deep in the CPU settings.

**Comment by ArendelleLeah** [comment]
I have the same question, I couldn't find that option to disable DMA(Direct Memory Access) in bios on the motherboard
And I found this page: https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-dmaguard#dmaguard-policies
I tried to set gpedit.msc and regedit to follow that page on my computer, but it didn't work for me.
