### ISSUE TITLE
AboveLock/AllowToasts

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#6754]
Hi there,

can someone confirm the GPO which this setting comes from?
is it
User Configuration\Policies\Administrative Templates\Start Menu and Taskbar\Notifications\Turn off toast notifications on the lock screen ??

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6003aa45-e096-62dd-2db2-ccb551c9c24e
* Version Independent ID: 1739c49c-ffe4-de03-e13e-27f76bfcbb29
* Content: [Policy CSP - AboveLock - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-abovelock)
* Content Source: [windows/client-management/mdm/policy-csp-abovelock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-abovelock.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@schenardie.
1.AboveLock/AllowCortanaAboveLock
 comes from  **GPO\Computer configuration\Administrative templates\Windows components\Search\Allow cortana above lock screen**

2. AboveLock/AllowToasts
comes form  **GPO\user configuration\Administrative templates\Start Menu and taskbar\Turn off toast notifications on the lock screen**

**Comment by mypil** [comment]
@schenardie - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @RAJU2529  so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
