### ISSUE TITLE
Is it positive or negative?

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/windows-itpro-docs#6755]
Policy parameter = DisableCatchupQuickScan
Registry value = DisableCatchupQuickScan
GP name = Scan_DisableCatchupQuickScan
GP label = "Turn on catch-up quick scan"

Is it me or has somebody's language gone horribly wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b1ab2e-1964-5580-7c99-4bd4cd480075
* Version Independent ID: f7b5da46-04cb-3501-65fa-870a3c6f09b8
* Content: [Policy CSP - Defender - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#defender-disablecatchupquickscan)
* Content Source: [windows/client-management/mdm/policy-csp-defender.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-defender.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@icelava . It's positive only. 
GP label = "Turn on catch-up quick scan" is  named according to windows defender scan technology

**Comment by icelava** [comment]
Then why are the underlying parameter/variable names called "Disable"?

**Comment by RAJU2529** [comment]
@icelava .  Sorry I don't know about  intune application and its technologies, let wait for some days to get  replies from  Intune experienced users

**Comment by icelava** [comment]
Intune aside, am I the only one who sees that "disable" in three of the parameter names DO NOT mean "Turn on"? Doesn't "Turn on" mean "_enable_"? Or do I have to return back to English language school?

**Comment by yogeshasalkar** [comment]
Hi @icelava , I think we both have encountered the same issue #6998  This documentation English is very different than they have used in Group Policy settings. If values in Intune have a different meaning than group policy then why did they mapped group policy in this documentation?
This issue is not negligible. Could anybody from MS look into this matter?

**Comment by illfated** [comment]
@icelava & @yogeshasalkar : is this difference only in this documentation page (referenced above), or is it visible in Intune as well as in the GPO files? (I may not have read your comments thoroughly enough to understand if this is already explained.)

1. If the issue exists only in the documentation page, we may be able to affect that by creating a Pull Request to have that conflicting information resolved.
2. If the issue exists in the applications as well as the documentation, this might be necessary to report to the Feedback Hub to get any changes implemented.

**Comment by ManikaDhiman** [comment]
Updated Defender/DisableCatchupFullScan and Defender/DisableCatchupQuickScan policy setting content to align with their GP description. Please note that the default values for these configs is TRUE (1), meaning Disable is active or in other words catchup scans will NOT happen.

@mypil: Please close this issue as fixed.

**Comment by illfated** [comment]
@ManikaDhiman : Thank you very much for your productive follow-up and reply.

For your information; @e0i commented in a different ticket 14 days ago:
> https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6422#issuecomment-656091224
> FYI Joyce has retired from the program. [ ... ]

@denisebmsft : Would you like to close this ticket, as recommended above?
