### ISSUE TITLE
Versions of Win10?

### ISSUE THREAD

**Issue by grkoop** [MicrosoftDocs/windows-itpro-docs#6756]
Can we make it clear what versions of Win10 have WHfB?  Do all of them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f8d124-fd83-f3ab-8249-d11d5967460f
* Version Independent ID: eace54c8-04c9-a717-5ecd-2be8f485cc93
* Content: [Windows Hello for Business Overview (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-overview#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by RAJU2529** [comment]
@grkoop . I think from 1803 onwards, I am not sure.

**Comment by grkoop** [comment]
Exactly.  Unclear

Thank you.

Kind regards,

Gregg Koop
Sr. Service Delivery Manager, MBA, PMP
Microsoft US Public Sector Services
gregg.koop@microsoft.com<mailto:gregg.koop@microsoft.com>
cell: (908) 391-5656

Microsoft Support Hotline       1-800-936-3100
Microsoft Premier/Unified Online: https://serviceshub.microsoft.com<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fserviceshub.microsoft.com%2F&data=02%7C01%7CGregg.Koop%40microsoft.com%7Cd794c503b02f440e405b08d75c88fe1a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637079617207633570&sdata=khlnX3AHx8tZfydgaopKjQ6XQkBlVjfalBUEuWRKWG4%3D&reserved=0>
Cybersecurity Incident Support: Microsoft Premier Incident Response<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdownload.microsoft.com%2Fdownload%2F5%2F1%2F6%2F516F59A7-91EE-4463-8612-C85FD3BEBDC7%2Fmicrosoft-incident-response-and-recovery-process-brief.pdf&data=02%7C01%7CGregg.Koop%40microsoft.com%7C8276db865a2c49ca6dfc08d6e56d699c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636948655414461448&sdata=ZMNOwvnJB%2BV1WTWdPj7Z479Ynhoo0iaz3RSkx0G2UGk%3D&reserved=0>

[cid:image001.jpg@01D62DBD.7C264500]

**Comment by MaratMussabekov** [comment]
Hello @grkoop ,
Windows Hello for Business is available since 1511. However, some deployment scenarios may require newer client versions. For more details please see [Planning a Windows Hello for Business Deployment](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide)
Thank you
