### ISSUE TITLE
Add note about ASC Integration being disabled for Office 365 GCC customers

### ISSUE THREAD

**Issue by Antoniha** [MicrosoftDocs/windows-itpro-docs#6757]
Please can we add this note from here https://docs.microsoft.com/en-us/azure/security-center/security-center-wdatp 
to this page into the 'Important' blue box under the 'integration with Azure Security Center' section please

When you use Azure Security Center to monitor servers, a Microsoft Defender ATP tenant is automatically created and the Microsoft Defender ATP data is stored in Europe by default. If you need to move your data to another location, you need to contact Microsoft Support to reset the tenant. Server endpoint monitoring utilizing this integration has been disabled for Office 365 GCC customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4ed2b3-0390-4d53-2450-14995ee8b0b0
* Version Independent ID: 91b5bb3e-55d4-6a8e-c16d-094f15c28ee7
* Content: [Onboard servers to the Microsoft Defender ATP service - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
@Antoniha : There you go, PR #6765 has been created to suggest adding the important note text you requested. Feel free to comment or follow the updates here on GitHub. (This issue ticket will be closed automatically when (and if) that PR gets merged.

**Comment by Antoniha** [comment]
great thanks!
