### ISSUE TITLE
Scripts call for basic authentication

### ISSUE THREAD

**Issue by jbrysonMSFT** [MicrosoftDocs/windows-itpro-docs#6764]
Since basic authentication (legacy) is being deprecated later this year for EXO.  These scripts should be reviewed and updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01b8ee25-5fce-c0d8-956b-60b1abf35a97
* Version Independent ID: ca999347-60a6-7038-f020-42ece402c905
* Content: [PowerShell for Surface Hub (Surface Hub) - Surface Hub](https://docs.microsoft.com/en-us/surface-hub/appendix-a-powershell-scripts-for-surface-hub#feedback)
* Content Source: [devices/surface-hub/appendix-a-powershell-scripts-for-surface-hub.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/appendix-a-powershell-scripts-for-surface-hub.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by Reeced40** [comment]
@Dansimp please can you help with this issue? Are these scripts going to be updated?

**Comment by Reeced40** [comment]
Hi @nam31. Please can you request merge so issue can be closed when you get a chance.
