### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windows-itpro-docs#6766]
When you follow the link for "Configure certificate infrastructure for SCEP", you will discover that it is a dead link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b4b43c7-e56a-f762-846f-51257983d3ab
* Version Independent ID: fa5d8ebb-02ea-cbc1-9b29-69bb710643e3
* Content: [How to use single sign on (SSO) over VPN and Wi-Fi connections (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/how-to-use-single-sign-on-sso-over-vpn-and-wi-fi-connections)
* Content Source: [windows/security/identity-protection/vpn/how-to-use-single-sign-on-sso-over-vpn-and-wi-fi-connections.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/vpn/how-to-use-single-sign-on-sso-over-vpn-and-wi-fi-connections.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Yes, looks like the target page(s) was/were moved in commit https://github.com/MicrosoftDocs/memdocs/commit/4ae71ed25d10c4189ee8f7758eef021d9d724386 (file specific link: https://github.com/MicrosoftDocs/memdocs/commit/4ae71ed25d10c4189ee8f7758eef021d9d724386#diff-9748553fa83345f099a9e88013c8aeff).
*
The new page link is this one: https://docs.microsoft.com/mem/intune/protect/certificates-scep-configure
*
Oh well. We will just have to amend the broken links whenever we find them. Pity there is no "What links here?" tool to collect all links across the repository to correct for the 1702 changed files and folders.
*
BTW, if you find more of these, please post a comment for everything you find, so I can add them to my PR, which I will create in a moment.

**Comment by illfated** [comment]
Very well, there you are. PR #6767 created to repair the broken link.
(This ticket will be closed automatically when the PR gets merged.)

**Comment by illfated** [comment]
Thank you for your patience. The PR has finally been merged and the link should now be working just fine.

Thank you also for reporting the dead link in the first place. 👍
