### ISSUE TITLE
Documentation without screenshots 

### ISSUE THREAD

**Issue by Anoni-Mouse** [MicrosoftDocs/windows-itpro-docs#6769]
Hello. Documentation without screenshots is like living without imagination. Other websites excel in doing so, Microsoft generally no :(. A picture is worth a thousand words! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed3f7cf-1bab-4806-33e9-e534df9b8cef
* Version Independent ID: 1e8f23b6-f4a5-188c-8f69-eae57b83cb1a
* Content: [Create an Outbound Port Rule (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/create-an-outbound-port-rule)
* Content Source: [windows/security/threat-protection/windows-firewall/create-an-outbound-port-rule.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/create-an-outbound-port-rule.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Sure, I would (more often than not) agree with you in most cases. For this specific case, though, I would like to mention a couple of points worth noting where images might be more distracting than helpful:
- At least 2 operating systems are mentioned in this page, so the images could differ between the OS versions.
- image resolution and selection can sometimes be a source of debate for which size, crop selection, or resolution will be more flexible and useful to the IT-Pro users.
- Some of these interfaces get updated to have a different view. layout, or color default than the first version, adding to the number of pages in need of image updates.
- Some pages are more useful in text format, keeping them shorter, both when scrolling and reading, making it easier to keep the overview for an administrator working in a side-by-side view of the OS and the documentation page.

If you still feel that the page needs to be improved with image content, feel free to post a layout suggestion (use MarkDown coding) to indicate where images are needed and which resolution you think will work best, or start a pull request to add the images you feel are most needed in this page.

**Comment by Reeced40** [comment]
@Anoni-Mouse please see @illfated comments above regarding the screenshots and confirm all in order with this issue and it can be closed?

**Comment by illfated** [comment]
@Reeced40 : Thank you for noticing and commenting on this ticket. I tried looking into the issue again, but I did find that this is exactly one of those Catch-22 scenarios of "damned if you do, damned if you don't". I tried to imagine how to add just one single image from the Windows Defender Firewall user interface, but this quickly led me to the decision-making tree of splitting paths where each decision limits the following set of selections, as well as making it obvious to me that more users will be dissatisfied with my choice of image(s) than those who think it is sufficient.

**Comment by Reeced40** [comment]
Thanks @illfated, I agree, let me check with the team to confirm. @Dansimp please confirm if article will stay as is?

**Comment by nam31** [comment]
@Anoni-Mouse Thank you for providing feedback.
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
Thank you for your contribution to make the docs better! Much appreciated!
