### ISSUE TITLE
"Update Network Unlock certificates" should be enhanced with an Info-Box

### ISSUE THREAD

**Issue by MHimken** [MicrosoftDocs/windows-itpro-docs#6771]
Hi, while technically this one sentence is correct - change the certificates for the server and in the GPO - it should be made clear, that every machine that didn't get the GPO will ask for the PIN at boot. Since a second certificate isn't allowed in this storage on the machine or on the server (I assume for servers its the same, its not stated as far as I can see), its not possible to test if the new certificate works. In short: There's no way to do the certificate exchange without disruption for some machines. 
As this might have a high user impact for mid-sized and large enterprises I suggest adding an info-box here to inform about this.

EDIT I forgot the URL https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock#update-network-unlock-certificates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c13083-9b29-e54b-fd85-8033ec665fcd
* Version Independent ID: ce8c4647-69bc-95d4-2192-6e737d5ad5da
* Content: [BitLocker How to enable Network Unlock (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock#update-network-unlock-certificates)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Closing via #8117
