### ISSUE TITLE
Windows Sandbox automatic installation

### ISSUE THREAD

**Issue by peetrike** [MicrosoftDocs/windows-itpro-docs#6772]
How can Windows Sandbox be installed/enabled automatically, without GUI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c06f3ef-5946-862a-ae14-f897fdb518ca
* Version Independent ID: cd6a8b99-b1e9-dff5-f174-a15840b304f0
* Content: [Windows Sandbox - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@peetrike . By using turning on windows features.

**Comment by peetrike** [comment]
Can You provide feature name?  And is it included in `Get-WindowsOptionalFeature -Online` or in `Get-WindowsCapability -Online`.  Was looking for it but unable to find...

**Comment by VLG17** [comment]
@peetrike Indeed, the feature name is Containers-DisposableClientVM and you enable it with the help of **Enable-WindowsOptionalFeature**

Running **Get-WindowsOptionalFeature -Online -FeatureName "Containers-DisposableClientVM** gives an explicit description:

![image](https://user-images.githubusercontent.com/41186174/90051261-17e6ad00-dce0-11ea-99c0-3ea8c7d6e71d.png)

**Comment by e0i** [comment]
@peetrike 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
