### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/windows-itpro-docs#6773]
At the end of the page it says "encyption algorithm" rather than "encryption algorithm". Missing an "r".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f28f994-ad0f-72e5-79d2-6898421cb2fd
* Version Independent ID: dbb83bbb-73cc-8233-15fb-1363b8ad1cd1
* Content: [Setting the BitLocker encryption algorithm for Autopilot devices - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/bitlocker)
* Content Source: [windows/deployment/windows-autopilot/bitlocker.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/bitlocker.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Fixing this now, thanks!

**Comment by illfated** [comment]
@GenerAhl : "This ensures that the default **encrytion** algorithm is not applied automatically when this is not the desired setting." Anyway, fair report, thanks.

(may as well dub myself "Captain Obvious" for this single comment)
