### ISSUE TITLE
Correction to embedded image in document

### ISSUE THREAD

**Issue by ChristopherHolloway** [MicrosoftDocs/windows-itpro-docs#6777]
![sc-image402](https://user-images.githubusercontent.com/65698320/82523278-5e69a880-9af1-11ea-92ab-db7f28f98b0a.png)

Please correct the highlighted misspelling on the flow diagram, please.

**Comment by RAJU2529** [comment]
@ChristopherHolloway . which article are you referring?. Error should be corrected immediately.

**Comment by e0i** [comment]
@ChristopherHolloway Can you refer to the associated article? A link would be helpful. Thank you.

**Comment by ChristopherHolloway** [comment]
Yes here is the link: https://docs.microsoft.com/en-us/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration 

Sorry for the delays. If you wouldn't mind giving kudos that would be great, and thank you for all your efforts as well.

**Comment by ChristopherHolloway** [comment]
![sc-image402](https://user-images.githubusercontent.com/65698320/83276391-8666a500-a19e-11ea-8bcc-e6bf4e323fc1.png)

Replacement Image, Please swap out and close.

**Comment by RAJU2529** [comment]
@ChristopherHolloway . Thanks for replacement pic, but there is a misspelling again, if we look faraway some distance, again it looks like clicks, instead of 
It should be replaced by press save

**Comment by illfated** [comment]
@ChristopherHolloway : May I ask you to point out where the misspelling is, since your replacement image seems to be the same as the original one (at least at first glance)?

**Comment by e0i** [comment]
@illfated The misspelling is at the very bottom of the first diagram highlighted with yellow.

**Comment by e0i** [comment]
The issue has been noted for investigation by an independent contributor. Thank you for discussion.

**Comment by illfated** [comment]
> @illfated The misspelling is at the very bottom of the first diagram highlighted with yellow.

Thank you. I did not notice earlier, maybe because I did not zoom in on the picture closely enough.

Actually, I think it would be an improvement just to replace the current image with the posted image in https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6777#issuecomment-636032735,

![Smart card sign-in flow](https://user-images.githubusercontent.com/65698320/83276391-8666a500-a19e-11ea-8bcc-e6bf4e323fc1.png)

because the highlighted text in the main comment of the issue ticket does not separate the letters c and l well enough, so it looks like a d (which makes the word seem a bit derogatory).

**Comment by e0i** [comment]
The image has been replaced via PR #7950

**Comment by ChristopherHolloway** [comment]
https://docs.microsoft.com/en-us/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration

The image still lives on the site and has not merged via PR at this time please correct at the earliest.

**Comment by illfated** [comment]
If the ticket had been opened correctly, it would have looked something like this:

***

[Enter feedback here]


---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 132e8bfa-12ba-2ae0-7745-545bcfd909f1
* Version Independent ID: 984c17f4-04a4-bf30-3a9e-3af49209f0bb
* Content: [Certificate Requirements and Enumeration (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration)
* Content Source: [windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
- Document general date for last update change: 04/19/2017 (https://docs.microsoft.com/en-us/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration)
- Document commit (change log) history on GitHub: https://github.com/MicrosoftDocs/windows-itpro-docs/commits/public/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration.md
- image source link: https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/smart-cards/images/sc-image402.png
- image last change date: February 1, 2018, 5:55 PM GMT
- non-migrated image update commit here on GitHub: https://github.com/MicrosoftDocs/windows-itpro-docs/commit/69dfb9c3d8cd823c0b5029cdacb6f4665936bd13 (https://github.com/MicrosoftDocs/windows-itpro-docs/commit/69dfb9c3d8cd823c0b5029cdacb6f4665936bd13?short_path=71098f1#diff-71098f1742018b7e9edc1368c60e3f0c49f6b7bc3f5460babf96bee609f8e367)
