### ISSUE TITLE
Is there any cmd command to export these settings to a file?

### ISSUE THREAD

**Issue by tarikshaikh** [MicrosoftDocs/windows-itpro-docs#678]
Like we have "secedit.exe \export \cfg <path>" to export other Local Security Policy settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f27f2e95-068a-6568-113d-66b378a2f6fe
* Version Independent ID: 6c13ead4-d350-d64c-7d29-3a7e4358d9ea
* Content: [Network List Manager policies (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-list-manager-policies)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-list-manager-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/network-list-manager-policies.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@tarikshaikh this should help: https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/agpm/export-a-gpo-to-a-file

**Comment by Justinha** [comment]
@tarikshaikh sorry, I was reading too fast. I couldn't find any native cmd for this. I found a PowerShell example at https://www.linkedin.com/pulse/export-all-gpo-settings-html-using-powershell-james-sargent

**Comment by tarikshaikh** [comment]
Not sure whether this is helpful or not as I am unable to run the above cmdlets on my machine. But this gave a different angle to think. Thanks.
