### ISSUE TITLE
'In this section' links

### ISSUE THREAD

**Issue by ruairidhlc** [MicrosoftDocs/windows-itpro-docs#6782]
The links for the 'WDAC and AppLocker Overview' and 'WDAC and AppLocker Feature Availability' instead point to 'Plan for Windows Defender Application Control lifecycle policy management' and 'Understand Windows Defender Application Control policy design decisions'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 481aaad1-c3ed-3eb1-bd29-ebad8f264edd
* Version Independent ID: dc5d9c47-e4aa-22ab-cb41-dfed57c517ac
* Content: [Application Control for Windows - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thank you @RAJU2529, for fixing this issue. I am going to close it now.
