### ISSUE TITLE
WDAC Policy Creation on Windows 10 Professional

### ISSUE THREAD

**Issue by ssccaavvookk** [MicrosoftDocs/windows-itpro-docs#6783]
"WDAC policies can only be created on computers running Windows 10 build 1903+ on any SKU, pre-1903 Windows 10 Enterprise, or Windows Server 2016 and above."

When I try to run New-CIPolicy or ConvertFrom-CIPolicy in PowerShell on Windows 10 Pro build 1909, I get the error: "ConvertFrom-CIPolicy : Device Guard is not available in this edition of Windows."

Is the documentation accurate or is there an issue with the powershell cmdlet availability? If it is accurate and there is no issue, can documentation be provided on how to build WDAC policies and binaries without the powershell cmdlets?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aa6cbf4-1e75-d43a-9fee-4bab4428857e
* Version Independent ID: fad52d5c-4a08-9a85-44e3-ae9130894bda
* Content: [WDAC and AppLocker Overview - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/wdac-and-applocker-overview)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/wdac-and-applocker-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/wdac-and-applocker-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@ssccaavvookk.  First enable  **device guard** in your running windows 10  edition. There are many articles are published to create optimized WDAC policies for different environments.

for more information visit below page 
**https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/create-wdac-policy-for-lightly-managed-devices**
**https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/create-wdac-policy-for-fully-managed-devices**

Last year i was successfully created  WDAC policy and deployed in my own l windows 10 laptop.

**Comment by ssccaavvookk** [comment]
I overlooked the documentation on the WDAC Feature Availability page (https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/feature-availability) where it says that the "Cmdlets are available on all SKUs on 1909+ builds." I was running 1909, so that appears to be an error, unless I'm weird and it's meant to be read to not include 1909. When I upgraded the device to build 2004 the cmdlets began working successfully.

**Comment by mypil** [comment]
@ssccaavvookk - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @RAJU2529  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
