### ISSUE TITLE
Scripts documentation missing

### ISSUE THREAD

**Issue by BrianSteingraber** [MicrosoftDocs/windows-itpro-docs#6784]
This main Security Compliance Toolkit page is missing documentation on the PowerShell scripts available in the Scripts folder of each baseline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 014ca19c-6ab8-6eec-321e-72fa22c8f2c3
* Version Independent ID: 948a95a8-cb4f-668a-1988-17830d51845b
* Content: [Microsoft Security Compliance Toolkit 1.0 - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-compliance-toolkit-10)
* Content Source: [windows/security/threat-protection/security-compliance-toolkit-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-compliance-toolkit-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
I have not found an easy way to produce any script documentation yet (being a non-MS employee).
In the meanwhile, I made a pull request to have the last 2 blog links updated to use the newer Baseline blog pages.

If the Security Baseline scripts documentation needs to have its own separate pages, I will most likely not be able to contribute without any pre-processed templates provided by the MS Docs team.

**Comment by illfated** [comment]
BTW, does anyone know if any documentation for the scripts, mentioned above, exist on any other pages, like for example in the PowerShell Docs pages?

**Comment by illfated** [comment]
@BrianSteingraber : I am sorry, I might just be the slowest user on GitHub to realize what the point of a single sentence issue is about.

Did you intend to ask for a list of the 12 ZIP files and sub-listing the name of the script under their respective filenames. e.g. something like this list?


---
### Download Summary:

1. **Windows 10 Version 1909 and Windows Server Version 1909 Security Baseline.zip**
    - (script name(s))
2. **LGPO.zip**
    - (script name(s))
3. **Microsoft Edge v80.zip**
    - (script name(s))
4. **Office365-ProPlus-Sept2019-FINAL.zip**
    - (script name(s))
5. **PolicyAnalyzer.zip**
    - (script name(s))
6. **Windows 10 Version 1507 Security Baseline.zip**
    - (script name(s))
7. **Windows 10 Version 1607 and Windows Server 2016 Security Baseline.zip**
    - (script name(s))
8. **Windows 10 Version 1709 Security Baseline.zip**
    - (script name(s))
9. **Windows 10 Version 1803 Security Baseline.zip**
    - (script name(s))
10. **Windows 10 Version 1809 and Windows Server 2019 Security Baseline.zip**
    - (script name(s))
11. **Windows 10 Version 1903 and Windows Server Version 1903 Security Baseline - Sept2019Update.zip**
    - (script name(s))
12. **Windows Server 2012 R2 Security Baseline.zip**
    - (script name(s))

**Comment by illfated** [comment]
Meh, this was one tedious job I did not expect to be doing on a Wednesday night. I bet that a real coder or scripter would know a quicker way to generate a working script list in less than 10% of the time I have been spending walking through the folders, file by file.

**Comment by illfated** [comment]
Tedious work, but here is what I was asking whether this is what you were asking for.
---

1. **Windows 10 Version 1909 and Windows Server Version 1909 Security Baseline.zip**
    - Baseline-ADImport.ps1
    - Baseline-LocalInstall.ps1
    - Remove-EPBaselineSettings.ps1
    - MapGuidsToGpoNames.ps1

2. **LGPO.zip**
    - LGPO.exe
    - LGPO.pdf

3. **Microsoft Edge v80.zip**
    - Baseline-ADImport.ps1
    - Baseline-LocalInstall.ps1
    - MapGuidsToGpoNames.ps1

4. **Office365-ProPlus-Sept2019-FINAL.zip**
    - Baseline-ADImport.ps1
    - Baseline-LocalInstall.ps1
    - MapGuidsToGpoNames.ps1

5. **PolicyAnalyzer.zip**
    - Merge-PolicyRules.ps1
    - Policy Analyzer.pdf
    - PolicyAnalyzer.exe
    - PolicyAnalyzer_GetLocalPolicy.exe
    - PolicyRulesFileBuilder.exe
    - Split-PolicyRules.ps1

6. **Windows 10 Version 1507 Security Baseline.zip**
    - 10_Client_Install.cmd

7. **Windows 10 Version 1607 and Windows Server 2016 Security Baseline.zip**
    - Client_Install.cmd
    - Domain_Controller_Install.cmd
    - Member_Server_Install.cmd
    - MapGuidsToGpoNames.ps1

8. **Windows 10 Version 1709 Security Baseline.zip**
    - Client_Install.cmd
    - MapGuidsToGpoNames.ps1

9. **Windows 10 Version 1803 Security Baseline.zip**
    - Client_Install_DomainJoined.cmd
    - Client_Install_NonDomainJoined.cmd
    - ClientInstall_Common1.cmd
    - ClientInstall_Common2.cmd
    - MapGuidsToGpoNames.ps1

10. **Windows 10 Version 1809 and Windows Server 2019 Security Baseline.zip**
    - BaselineLocalInstall.ps1
    - MapGuidsToGpoNames.ps1

11. **Windows 10 Version 1903 and Windows Server Version 1903 Security Baseline - Sept2019Update.zip**
    - Baseline-ADImport.ps1
    - Baseline-LocalInstall.ps1
    - MapGuidsToGpoNames.ps1

12. **Windows Server 2012 R2 Security Baseline.zip**
    - (GPO, WMI filters, GP reports, and documentation)

---

Unless I get feedback on what the requested information is about, I will paste this plain list on the page with no further text.

**Comment by illfated** [comment]
Tedious work, but here is what I was asking whether this is what you were asking for.

---

1. **Windows 10 Version 1909 and Windows Server Version 1909 Security Baseline.zip**
    - Baseline-ADImport.ps1
    - Baseline-LocalInstall.ps1
    - Remove-EPBaselineSettings.ps1
    - MapGuidsToGpoNames.ps1

2. **LGPO.zip**
    - LGPO.exe
    - LGPO.pdf

3. **Microsoft Edge v80.zip**
    - Baseline-ADImport.ps1
    - Baseline-LocalInstall.ps1
    - MapGuidsToGpoNames.ps1

4. **Office365-ProPlus-Sept2019-FINAL.zip**
    - Baseline-ADImport.ps1
    - Baseline-LocalInstall.ps1
    - MapGuidsToGpoNames.ps1

5. **PolicyAnalyzer.zip**
    - Merge-PolicyRules.ps1
    - Policy Analyzer.pdf
    - PolicyAnalyzer.exe
    - PolicyAnalyzer_GetLocalPolicy.exe
    - PolicyRulesFileBuilder.exe
    - Split-PolicyRules.ps1

6. **Windows 10 Version 1507 Security Baseline.zip**
    - 10_Client_Install.cmd

7. **Windows 10 Version 1607 and Windows Server 2016 Security Baseline.zip**
    - Client_Install.cmd
    - Domain_Controller_Install.cmd
    - Member_Server_Install.cmd
    - MapGuidsToGpoNames.ps1

8. **Windows 10 Version 1709 Security Baseline.zip**
    - Client_Install.cmd
    - MapGuidsToGpoNames.ps1

9. **Windows 10 Version 1803 Security Baseline.zip**
    - Client_Install_DomainJoined.cmd
    - Client_Install_NonDomainJoined.cmd
    - ClientInstall_Common1.cmd
    - ClientInstall_Common2.cmd
    - MapGuidsToGpoNames.ps1

10. **Windows 10 Version 1809 and Windows Server 2019 Security Baseline.zip**
    - BaselineLocalInstall.ps1
    - MapGuidsToGpoNames.ps1

11. **Windows 10 Version 1903 and Windows Server Version 1903 Security Baseline - Sept2019Update.zip**
    - Baseline-ADImport.ps1
    - Baseline-LocalInstall.ps1
    - MapGuidsToGpoNames.ps1

12. **Windows Server 2012 R2 Security Baseline.zip**
    - (GPO, WMI filters, GP reports, and documentation)

---

I will add this list to my existing PR and presume that this is what you were asking for.

**Comment by illfated** [comment]
1. **Windows 10 Version 1909 and Windows Server Version 1909 Security Baseline.zip**

    - Baseline-ADImport.ps1
    - Baseline-LocalInstall.ps1
    - Remove-EPBaselineSettings.ps1
    - MapGuidsToGpoNames.ps1


2. **LGPO.zip**

    - LGPO.exe
    - LGPO.pdf


3. **Microsoft Edge v80.zip**

    - Baseline-ADImport.ps1
    - Baseline-LocalInstall.ps1
    - MapGuidsToGpoNames.ps1


4. **Office365-ProPlus-Sept2019-FINAL.zip**

    - Baseline-ADImport.ps1
    - Baseline-LocalInstall.ps1
    - MapGuidsToGpoNames.ps1


5. **PolicyAnalyzer.zip**

    - Merge-PolicyRules.ps1
    - Policy Analyzer.pdf
    - PolicyAnalyzer.exe
    - PolicyAnalyzer_GetLocalPolicy.exe
    - PolicyRulesFileBuilder.exe
    - Split-PolicyRules.ps1


6. **Windows 10 Version 1507 Security Baseline.zip**

    - 10_Client_Install.cmd


7. **Windows 10 Version 1607 and Windows Server 2016 Security Baseline.zip**

    - Client_Install.cmd
    - Domain_Controller_Install.cmd
    - Member_Server_Install.cmd
    - MapGuidsToGpoNames.ps1


8. **Windows 10 Version 1709 Security Baseline.zip**

    - Client_Install.cmd
    - MapGuidsToGpoNames.ps1


9. **Windows 10 Version 1803 Security Baseline.zip**

    - Client_Install_DomainJoined.cmd
    - Client_Install_NonDomainJoined.cmd
    - ClientInstall_Common1.cmd
    - ClientInstall_Common2.cmd
    - MapGuidsToGpoNames.ps1


10. **Windows 10 Version 1809 and Windows Server 2019 Security Baseline.zip**

    - BaselineLocalInstall.ps1
    - MapGuidsToGpoNames.ps1


11. **Windows 10 Version 1903 and Windows Server Version 1903 Security Baseline - Sept2019Update.zip**

    - Baseline-ADImport.ps1
    - Baseline-LocalInstall.ps1
    - MapGuidsToGpoNames.ps1


12. **Windows Server 2012 R2 Security Baseline.zip**

    - (GPO, WMI filters, GP reports, and documentation)

**Comment by illfated** [comment]
1. **Windows 10 Version 1909 and Windows Server Version 1909 Security Baseline.zip**

    - Baseline-ADImport.ps1
    - Baseline-LocalInstall.ps1
    - Remove-EPBaselineSettings.ps1
    - MapGuidsToGpoNames.ps1
<br>

2. **LGPO.zip**

    - LGPO.exe
    - LGPO.pdf
<br>

3. **Microsoft Edge v80.zip**

    - Baseline-ADImport.ps1
    - Baseline-LocalInstall.ps1
    - MapGuidsToGpoNames.ps1
<br>

4. **Office365-ProPlus-Sept2019-FINAL.zip**

    - Baseline-ADImport.ps1
    - Baseline-LocalInstall.ps1
    - MapGuidsToGpoNames.ps1
<br>

5. **PolicyAnalyzer.zip**

    - Merge-PolicyRules.ps1
    - Policy Analyzer.pdf
    - PolicyAnalyzer.exe
    - PolicyAnalyzer_GetLocalPolicy.exe
    - PolicyRulesFileBuilder.exe
    - Split-PolicyRules.ps1
<br>

6. **Windows 10 Version 1507 Security Baseline.zip**

    - 10_Client_Install.cmd
<br>

7. **Windows 10 Version 1607 and Windows Server 2016 Security Baseline.zip**

    - Client_Install.cmd
    - Domain_Controller_Install.cmd
    - Member_Server_Install.cmd
    - MapGuidsToGpoNames.ps1
<br>

8. **Windows 10 Version 1709 Security Baseline.zip**

    - Client_Install.cmd
    - MapGuidsToGpoNames.ps1
<br>

9. **Windows 10 Version 1803 Security Baseline.zip**

    - Client_Install_DomainJoined.cmd
    - Client_Install_NonDomainJoined.cmd
    - ClientInstall_Common1.cmd
    - ClientInstall_Common2.cmd
    - MapGuidsToGpoNames.ps1
<br>

10. **Windows 10 Version 1809 and Windows Server 2019 Security Baseline.zip**

    - BaselineLocalInstall.ps1
    - MapGuidsToGpoNames.ps1
<br>

11. **Windows 10 Version 1903 and Windows Server Version 1903 Security Baseline - Sept2019Update.zip**

    - Baseline-ADImport.ps1
    - Baseline-LocalInstall.ps1
    - MapGuidsToGpoNames.ps1
<br>

12. **Windows Server 2012 R2 Security Baseline.zip**

    - (GPO, WMI filters, GP reports, and documentation)
<br>

**Comment by BrianSteingraber** [comment]
I was hoping for 
1. Adding a main "Scripts" bullet with sub bullets for each script.
2. Adding a "What is the <powershellscriptname>?" section for each script.

**Comment by illfated** [comment]
Yeah, I deleted a few comments which I had written mostly because something else was bothering me.
Fair enough, I will handle the eventual message from GitHub that my PR contains a file conflict.
