### ISSUE TITLE
Download link for MBAM ServerUpdate

### ISSUE THREAD

**Issue by ggbce** [MicrosoftDocs/windows-itpro-docs#6785]
In this  page, a link was added to obtain the latest MDOP update (2019-05), but this  package contain only an update for MBAM client. Please add also a link to obtain the latest MDOP update (2018-07) that include many fix for MBAM server... the most important a fix to support SQL Server 2017 !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 604e3922-8536-4cb7-5df7-beb0b7087e58
* Version Independent ID: 4c824538-1e43-8779-63e3-7f2183a9c95a
* Content: [Upgrading to MBAM 2.5 SP1 from MBAM 2.5 - Microsoft Desktop Optimization Pack](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/upgrading-to-mbam-25-sp1-from-mbam-25?source=docs#feedback)
* Content Source: [mdop/mbam-v25/upgrading-to-mbam-25-sp1-from-mbam-25.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/mdop/mbam-v25/upgrading-to-mbam-25-sp1-from-mbam-25.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
I suppose you are referring to these links?
- https://www.microsoft.com/download/details.aspx?id=57157
- https://support.microsoft.com/help/4340040/july-2018-servicing-release-for-microsoft-desktop-optimization-pack

Not quite sure about where to add it, but I am guessing somewhere in the following section:
***
#### Steps to upgrade the MBAM Server (Running MBAM and IIS)
1. Using the MBAM Configurator; remove the Admin and Self Service Portals from  the IIS server
2. Install MBAM 2.5 SP1
3. Do not configure it at this time  
4. Using the MBAM Configurator; re-add the Admin and Self Service Portals to the IIS server 
5. Open an elevated command prompt, type **IISRESET**, and hit Enter.
***
Would it be correct to assume that there needs to be 2 (or 3) new points between existing point 3 and 4?
I notice that KB4340040 states the following:
- You must restart the computer after you apply this hotfix.

Based on this information, I am guessing that there needs to be a mention of the need to reboot in the list of steps, probably before existing step 4.

**Comment by illfated** [comment]
When you have verified what needs to be included, feel free to ask me to provide a PR to have the content added.
