### ISSUE TITLE
There is a typo in symlinkevalution

### ISSUE THREAD

**Issue by volo-zyko** [MicrosoftDocs/windows-itpro-docs#6786]
Should be `symlinkevaluation`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7509570d-b0f5-9719-5105-577af3969fd0
* Version Independent ID: 5867d113-fcbc-6005-2f13-eb7a942f8f80
* Content: [Create symbolic links (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/create-symbolic-links.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/create-symbolic-links.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@volo-zyko - Thank you for pointing this out.

PR #6787 has been created to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
