### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by ITPirate** [MicrosoftDocs/windows-itpro-docs#679]
Ensure that the storage path ends with %username% to ensure that eah (!) user gets a unique folder.

Ensure that the storage path ends with %username% to ensure that each user gets a unique folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f735c74e-f4aa-9839-81fe-050782e09e22
* Version Independent ID: 94ceabf5-70ec-8a81-6eee-8f9aa2671ad6
* Content: [Get Started with UE-V](https://docs.microsoft.com/en-us/windows/configuration/ue-v/uev-getting-started)
* Content Source: [windows/configuration/ue-v/uev-getting-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/ue-v/uev-getting-started.md)
* Service: **unspecified**
* GitHub Login: @MaggiePucciEvans
* Microsoft Alias: **jdecker**

**Comment by andreabichsel** [comment]
Closing issue as fixed.
