### ISSUE TITLE
Embedded video

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/windows-itpro-docs#6791]
The embedded video does not provide much help as we cannot see what the presenters are demonstrating.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c06f3ef-5946-862a-ae14-f897fdb518ca
* Version Independent ID: cd6a8b99-b1e9-dff5-f174-a15840b304f0
* Content: [Windows Sandbox - Windows security](https://docs.microsoft.com/en-gb/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Not sure what you mean. I just watched the whole video right now and I saw the PowerPoint slides as well as the dynamic content (game demonstration, package installation & removal in Windows Sandbox).
*
Granted, the slides and the demos were not kept on the video screen the whole time, but if I wanted to read the details or review the dynamic content, I paused the video at each slide, or selected to rewind the video a bit, for any slide or demo with more details than the presentation slide for the event and the speakers.
*
Could you go a bit more into details, what you were looking for, besides the slides, the Windows Admin Center install/uninstall, and the game demo?

**Comment by e0i** [comment]
Closed via community contributor's comments above. Feel free to re-open with details about the issue and we'd like to follow-up. Thank yoiu.
