### ISSUE TITLE
I need commands of MpDlpCmd.exe

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#6797]
I am using windows 10 2004  64bit build no 19041.264.
I want to configure windows defender using this file **MpDlpCmd.exe**
above file is  settled under this location **C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.2004.6-0**

I searched the commands of **MpDlpCmd.exe** in the internet, but no use, I didn't get commands' 

![Capture](https://user-images.githubusercontent.com/3296790/82749798-403dca00-9dc9-11ea-894e-cccb2573f523.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f25443de-57f4-c8f2-fecb-f58714467894
* Version Independent ID: 1d783d00-ae0d-3eea-9a32-b42dd32e73c2
* Content: [Use the command line to manage Windows Defender Antivirus - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/command-line-arguments-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/command-line-arguments-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/command-line-arguments-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
Well, short of decompiling the program file (which I don't think we are entitled to do), you could try to read the text contents of the program file (`MpDlpCmd.exe`).
*
I have not had much luck in finding anything else than a Chinese forum page where they are trying to figure out the same as you.

**Comment by illfated** [comment]
Reading through the file via WordPad, it looks complicated to determine if I am looking at system calls or DLL calls represented in text format, or if they are valid parameters.

Found this XML while I was browsing:
```xml
<?xml version="1.0" encoding="UTF-8" ?> 
<!-- Copyright (c) Microsoft Corporation -->
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
    <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> 
        <application> 
            <!-- Compatible with Windows 10 -->            
            <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}">
            </supportedOS>
        </application> 
    </compatibility>
    <dependency>
        <dependentAssembly>
            <!-- Modern looking controls via common controls library v6 -->
            <assemblyIdentity
                type="win32"
                name="Microsoft.Windows.Common-Controls"
                version="6.0.0.0"
                processorArchitecture="amd64"
                publicKeyToken="6595b64144ccf1df"
                language="*">
            </assemblyIdentity>
        </dependentAssembly>
    </dependency>
</assembly>
```

Not sure what to make of it, but the names below look less like general system calls and more related to MsMpEng in their names:
```
MpAllocMemory
MpClientUtilExportFunctions
MpConfigClose
MpConfigGetValue
MpConfigGetValueAlloc
MpConfigInitialize
MpConfigOpen
MpConfigUninitialize
MpConveyUserChoiceForDlpNotification
MpFreeMemory
MpGetDlpEvents
MpHandleClose
MpManagerOpen
MpManagerVersionQuery
MpUtilsExportFunctions
```
(Then again, I can easily be mistaken. Ask a real coder & developer about how to localize the information you are looking for.)

**Comment by RAJU2529** [comment]
@illfated . Thanks for the information. Today I decombiled the program, I got all names like above mentioned and I entered those commands, but none of them worked

**Comment by illfated** [comment]
OK, well, then maybe the actual parameters or commands are located in one of the .DLL or .MUI files belonging to the application (I don't know). Otherwise, it looks like we will have to wait until Microsoft releases any form of information or documentation for the command-line utility.

**Comment by e0i** [comment]
I believe that the Trond's comment above answers appropriately the question inherent within the issue. Thank you.

**Comment by RAJU2529** [comment]
@e0i . Please reopen this issue. Because problems does not solved.

**Comment by illfated** [comment]
@RAJU2529 : I don't see how it will help keeping this issue ticket open to solve your issue. To me, it looks more like a support question, seeing that it is not a part of the documentation (at least not yet).

Have you considered checking the TechNet or MSDN pages to ask about the details of this issue? I think we need more information before we can make any changes to the existing documentation.

**Comment by oalieno** [comment]
Just googling this `MpDlpCmd.exe` and found this issue.
After my quick reversing the executable, I found that there are three parameters.

- `-h / -?`: print usage
- `-ShowDlpDetailsDialog`
- `-TestDlpDetailsDialog`

But I'm still not sure what this executable does.

![image](https://user-images.githubusercontent.com/18167730/199291328-280c4178-5b3b-4a3f-a581-603801410e08.png)
