### ISSUE TITLE
RegBack no longer an option

### ISSUE THREAD

**Issue by pcintula** [MicrosoftDocs/windows-itpro-docs#6798]
"Copy all the hives from the Regback folder" is no longer an option as this helpful feature was removed in 1803, unless the user has overridden it beforehand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc264df-cbd1-ac1f-3926-841fcab7dc31
* Version Independent ID: 67c2aea4-0d28-3d8e-e935-8af05291c94e
* Content: [Advanced troubleshooting for Windows boot problems - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/advanced-troubleshooting-boot-problems)
* Content Source: [windows/client-management/advanced-troubleshooting-boot-problems.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/advanced-troubleshooting-boot-problems.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Thanks. We need to add a note, maybe even `[!IMPORTANT]` , about this detail on the page:
- https://support.microsoft.com/en-gb/help/4509719/the-system-registry-is-no-longer-backed-up-to-the-regback-folder-start

**Comment by RAJU2529** [comment]
@illfated . Will you create PR in this issue for adding note

**Comment by illfated** [comment]
Thank you for asking. Yes, I was thinking about it, but I am also still thinking about where in the page that note can be placed to be useful enough for all readers of that page.

Then again, I guess it could be just as simple as starting a PR to add the note, then wait for feedback from the MS Docs team regarding where it fits best and if I need to move it from the place I pick as my suggestion. (As you probably have noticed, I am a bit hesitant to start working on something, if I don't know exactly what it needs to look like before I start. Similar forms of reluctancy are also known as "procrastination" or "indecision" or "indecisiveness".

**Comment by RAJU2529** [comment]
@illfated . Actually this article is needs to be updated with related screenshots. including the withthe actual commands.
Also article should be included note section and support section. because this article is useful to all the. Windows 10 home users.
I can supply the screenshots.

**Comment by illfated** [comment]
OK, sounds like you have a better idea than me what needs to be done here. If you want to, feel free to start a PR to improve the page.

If the PR will contain a lot of changes, maybe you want to open it as a Tentative PR (gray PR symbol instead of green) until you feel that it is ready for publising.

Also: maybe the PR title could be something like **Client Management: update Advanced troubleshooting**

**Comment by e0i** [comment]
Upon your feedback, We have updated the content with relevant changes accordingly via PR #8089
