### ISSUE TITLE
Clarify statement re “bundling software”

### ISSUE THREAD

**Issue by wjk** [MicrosoftDocs/windows-itpro-docs#6799]
What, exactly, does "Software that offers to install other software that is not digitally signed by the same entity" mean? Does this means _all_ binaries in my app must be signed by me to avoid triggering “Uncommon download” warnings? If so, this is an unreasonable requirement. I bundle the Visual C++ runtime redistributable and/or the .NET Core/.NET 5 runtime installers with my setup EXE, because my software takes a dependency on them. I can't unpack them to resign their contents, as then the installer would not be fungible with all other installers for that product, which is important when dealing with machine-wide dependencies. And what about using third-party NuGet packages containing binaries that were signed by the package's author? Need I resign those as well?

Furthermore, I believe that those “Uncommon download” warnings place an excessive burden on third-party developers. Simply put, how can I gain “download reputation” through users downloading and installing my app when every time someone tries to do so Windows accuses it of potentially being malware (despite that code-signing cert I spent $200 a year for). The user must then must click-through two different malware warnings (one presented by Edge, and another by Windows Defender), all of which make it look like the only option available is the Delete button. This makes it really unlikely that the user actually installs my app, thereby providing the “reputation” my app requires. (And no, an EV cert is not an option. I am not a corporation or an LLC, which you must be in order to get an EV cert, and I do not want to deal with the increased tax and regulatory burden that would come as part of founding one.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b16da7d1-e552-e274-9406-5390252b0c04
* Version Independent ID: d0c9b8a8-4fba-4ea8-cfdd-6ae6d67a2e19
* Content: [How Microsoft identifies malware and potentially unwanted applications - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/criteria?source=docs#potentially-unwanted-application-pua)
* Content Source: [windows/security/threat-protection/intelligence/criteria.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/criteria.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Hi @wjk, thank you for your feedback. The team agreed that the statement about bundling software was confusing. We are updating the language to the below statement:

"Bundling software: Software that offers to install other software that is not developed by the same entity or not required for the software to run. Also, software that offers to install other software that qualifies as PUA based on the criteria outlined in this document."

Also, here are some links that maybe helpful to you:
- https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/submission-guide
- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview#submit-files-to-microsoft-defender-smartscreen-for-review
