### ISSUE TITLE
MDATP licensing requirements is incorrect

### ISSUE THREAD

**Issue by louisgohl** [MicrosoftDocs/windows-itpro-docs#6803]
MDATP licensing requirements is incorrect, see also: https://www.microsoftpartnercommunity.com/t5/UK-Modern-Workplace-Community/Announcing-Microsoft-Defender-Advanced-Threat-Protection-MDATP/gpm-p/16338

>Microsoft is removing the Windows E3 license pre-requirement from Microsoft Defender Advanced Threat Protection (MDATP). CSP partners will be able to purchase MDATP for all their supported devices, regardless of their Windows E3 license ownership. To enable this business model, Microsoft is launching standalone offer for CSP on March 2, 2020. In addition, there is no change to existing Windows E5, Microsoft 365 E5 Security and Microsoft 365 E5 offers as those offerings will continue including MDATP.
> 
> Product Offer:
> Microsoft Defender Advanced Threat Protection e2dcab13-1365-417a-b624-4901e2b252f5
> Microsoft Defender Advanced Threat Protection for Education 1a7a1bcc-c7bf-4c6b-b55d-d79a6e3bb3ee

~~Microsoft Defender Advanced Threat Protection requires one of the following Microsoft Volume Licensing offers:
Windows 10 Enterprise E5
Windows 10 Education A5
Microsoft 365 E5 (M365 E5) which includes Windows 10 Enterprise E5
Microsoft 365 E5 Security
Microsoft 365 A5 (M365 A5)~~

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements#licensing-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by Reeced40** [comment]
@louisgohl thank you for reaching out and helping improve MS Docs. Just for clarity, are you suggesting removing the 6 x licenses as per your message above and adding the product offer details? I see this article has been updated recently so please have another look and let me know if you still recommend changes to this article.

**Comment by nam31** [comment]
@louisgohl We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.

Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.

Thank you for providing feedback.
