### ISSUE TITLE
Studio 2 erroneously listed as supported by New Surface Dock 2

### ISSUE THREAD

**Issue by danchar4** [MicrosoftDocs/windows-itpro-docs#6804]
Is the Surface Dock 2 really supported on the Surface Studio 2? Seems this is a typo given that the Studio doesn't have a SurfaceConnect port:

https://docs.microsoft.com/en-us/surface/surface-dock-whats-new

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be36e174-5760-651b-f97a-b8466d4f877d
* Version Independent ID: 28d210d7-0d47-dd88-edd7-717533fbfa1d
* Content: [What’s new in Surface Dock 2 - Surface](https://docs.microsoft.com/en-us/surface/surface-dock-whats-new)
* Content Source: [devices/surface/surface-dock-whats-new.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-dock-whats-new.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @CoveMiner
* Microsoft Alias: **greglin**

**Comment by VLG17** [comment]
@danchar4 I see that Studio 2 is not listed anymore, so it's fixed now.
