### ISSUE TITLE
InternetExplorer policy CSP?

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/windows-itpro-docs#6806]
> For Microsoft Defender SmartScreen Internet Explorer MDM policies, see Policy CSP - InternetExplorer.

Should be Browser policy CSP, even though that's the old Edge version.
https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-browser

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5413195-c0e2-99e4-5d82-6bffdcbbddb9
* Version Independent ID: b8cef753-139b-0098-ed30-63cca8d5b8b9
* Content: [Available Microsoft Defender SmartScreen Group Policy and mobile device management (MDM) settings (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-available-settings#mdm-settings)
* Content Source: [windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-available-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-available-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
@icelava : Do you find the latest page update from PR #8367 sufficient, or do you have further suggestions?
