### ISSUE TITLE
Note section is  repeated two times.

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#6808]
At the top of the page,Note section is. Mentioned two times , and content is same, so remove one Note section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd200806-fa21-1384-e489-be8fe923c666
* Version Independent ID: 9b68cddb-aa39-5269-9a70-dfe6c2ce1ff7
* Content: [Policy CSP - Browser - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-browser)
* Content Source: [windows/client-management/mdm/policy-csp-browser.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-browser.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Thank you @RAJU2529. The pull request that fixes this has been merged, and you will see the changes on the live site later today. I am going to go ahead and close this out.
