### ISSUE TITLE
On-Premise -> On-Premises

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/windows-itpro-docs#6811]
Just need to fix the typo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f520ab6-2fc9-4978-553c-6beff2ec3d9c
* Version Independent ID: 840eb4e6-2871-6812-a64c-8e0b8d6c772a
* Content: [Onboard machines without Internet access to Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/onboard-offline-machines)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/onboard-offline-machines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/onboard-offline-machines.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Thanks. Consider it done.

**Comment by illfated** [comment]
(Resolved in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/26f6d105e97076cfe4df2295d4bf86d166ac8348 )

**Comment by e0i** [comment]
Closing via https://github.com/MicrosoftDocs/windows-itpro-docs/commit/26f6d105e97076cfe4df2295d4bf86d166ac8348
