### ISSUE TITLE
2012 support?

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/windows-itpro-docs#6812]
Is 2012 assumed to be supported since in between 2008R2 and 2012R2?  Or is it intentionally off the list for a reason (and maybe state the reason)?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4ed2b3-0390-4d53-2450-14995ee8b0b0
* Version Independent ID: 91b5bb3e-55d4-6a8e-c16d-094f15c28ee7
* Content: [Onboard servers to the Microsoft Defender ATP service - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by joinimran** [comment]
@J-Fedor - Server 2012 is not supported. Please see details at the following tech community article https://techcommunity.microsoft.com/t5/microsoft-defender-atp/protecting-windows-server-with-windows-defender-atp/bc-p/1564576

Thanks.
Imran.

**Comment by J-Fedor** [comment]
OK, just odd that 2008R2 is covered, but 2012 isn’t.  Seems like something is off to skip a version.
The article doesn’t have any details about it not being supported, just someone stating in the comment section it isn’t.


John Fedor
Principal Architect
Direct:
Support Desk
630.592.6240
630.592.6260
visit peters.com today!
​Stay up-to-date and follow us on social media!
0.5% of Office 365 accounts are compromised monthly, are you protected? Find out HERE.
The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and privileged material
​Unauthorized review, use, disclosure, or distribution is prohibited.
​If you receive this material/information in error, please contact the sender and destroy the material/information.

**Comment by illfated** [comment]
@J-Fedor : In my opinion, it is not difficult to understand why 2012 is unsupported when 2012R2 is supported. 
It is just the same as with 2008 versus 2008R2. 
The latest Release of each version is the supported version (R2).
The older Release is not supported because a newer Release exists.

**Comment by J-Fedor** [comment]
Yeah, but 2008R2 isn’t a supported OS anymore, 2012 is a supported OS.  Code should function, not skip versions on the timeline.


John Fedor
Principal Architect
Direct:
Support Desk
630.592.6240
630.592.6260
visit peters.com today!
​Stay up-to-date and follow us on social media!
0.5% of Office 365 accounts are compromised monthly, are you protected? Find out HERE.
The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and privileged material
​Unauthorized review, use, disclosure, or distribution is prohibited.
​If you receive this material/information in error, please contact the sender and destroy the material/information.

**Comment by illfated** [comment]
Fair enough, thank you for pointing out those details. I leave it to the MS Docs team to decide whether they want to change anything about this in the documentation.
