### ISSUE TITLE
AppLocker function and support differences from implementation via group policy

### ISSUE THREAD

**Issue by ssccaavvookk** [MicrosoftDocs/windows-itpro-docs#6813]
Can any documentation be provided for using AppLocker through this CSP? There are various blogs, from Microsoft and otherwise, with how to implement it. But key details are missing that make me very nervous to use this in a work environment.

Exe's and StoreApps appear to function the same way as AppLocker being deployed by group policy and seem solid.

MSI and Script policies appear to use SRP to enforce, not Applocker. MSI block events are logged under Windows/Applications, not under AppLocker. Scripts don't appear in the event log at all that I could find. AuditOnly mode does not work on either of them (no event logs), which makes it difficult to implement in a work environment. I couldn't find any events with a dll policy in audit only mode, I assume it's the same, but I wasn't brave enough to enable the policy without being able to audit it first.

Which file types specifically use SRP vs AppLocker? Where are the event logs and what are the Event IDs?  

How are the differences in AppLocker and SRP rules interpreted? E.g. SRP does not have rule exceptions like AppLocker, so what happens if I use an XML with exceptions produced by AppLocker local security policy or AaronLocker? 

Is there a way to review the SRP policy after it's been converted from an AppLocker policy in the CSP to analyze for gaps since the large body of knowledge on hardening AppLocker is not applicable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa7dd86-8bcc-bb92-0a66-86e24701e5a4
* Version Independent ID: 277e194c-0fa3-7da6-1814-f6951e440df6
* Content: [AppLocker CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/applocker-csp)
* Content Source: [windows/client-management/mdm/applocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/applocker-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@ssccaavvookk . I prefer to use  SRP, because its easy to add rules,

**Comment by joinimran** [comment]
Hello @ssccaavvookk - Thank you for your query. Specific to App Locker event-related information, please see https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/plan-for-applocker-policy-management 
In the document, Microsoft has provided a lot of information related to App locker events related details and where events are stored. 

If you still have further queries related to the App locker, I would suggest you open a support case with Microsoft to better help you with your questions.

Thanks
Imran.

**Comment by bendunne** [comment]
The log mentioned in the article for MSI & Script. Isn’t populated with events when deploying Applocker via CSP. I also experienced the exact same behaviour.
