### ISSUE TITLE
References to Network Monitor must be removed

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windows-itpro-docs#6815]
[Enter feedback here]
References to Network Monitor must be removed. Network Monitor is past end of life, end of support, and end of security updates. References to Network Monitor must be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8823127-9a9b-141c-6096-e8d40ff6e22c
* Version Independent ID: 02332337-0981-36af-424e-9378487dd4d8
* Content: [Collect data using Network Monitor - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-tcpip-netmon)
* Content Source: [windows/client-management/troubleshoot-tcpip-netmon.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/troubleshoot-tcpip-netmon.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Closing via #7080.
