### ISSUE TITLE
Downloadable report?

### ISSUE THREAD

**Issue by jose-camacaro** [MicrosoftDocs/windows-itpro-docs#6819]
I love the alert trends, so much insight!
**Is MS planning to add a "download report" feature on this view?** It would be great to get the raw data, in order to support the arguments or reports to upper management or executive summaries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05423755-7805-7771-da2c-ffa8b8afc4e5
* Version Independent ID: 299b65a7-c09d-219c-c8fa-a7f0df829fd9
* Content: [Threat protection report in Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/threat-protection-reports)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/threat-protection-reports.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/threat-protection-reports.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
If the feature is present in Microsoft Defender ATP, it should be added to the documentation, so it would be nice to know if that is an existing feature.
*
Then again, if it is not an available feature yet, you may want to file a request for that feature in the Feedback Hub. to present the request to the developers. (One of the Microsoft Docs team members may post a comment about this later.)

**Comment by e0i** [comment]
As suggested, Please consider sending your input via the Feedback Hub so that it gets addressed via the proper channels:

[Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

Thank you.
