### ISSUE TITLE
Why dont you provide links to the download?

### ISSUE THREAD

**Issue by lcaseybsa** [MicrosoftDocs/windows-itpro-docs#682]
All of you smart Harvard educated 6 figure salary idiots never include the dam download link to the software!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6206d15-c29d-0949-9f60-66ba6b845c9e
* Version Independent ID: 166ff693-5e6c-5b82-e362-7d7867fa1d04
* Content: [Diagnostics and Recovery Toolset 10](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/dart-v10/index)
* Content Source: [mdop/dart-v10/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/dart-v10/index.md)
* Service: **unspecified**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by Budohaya** [comment]
the question is not yet answer where can one download this tools , is it it illegal  for your to provide that link , saying it is on MDOP IS NOT ANSWERING THE QUESTION

**Comment by shortpatti** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=56126

**Comment by shortpatti** [comment]
https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/agpm/#a-href-idbkmk-getmdopahow-to-get-mdop
