### ISSUE TITLE
中国经常使用Microsoft官网的程序员。

### ISSUE THREAD

**Issue by rocky-co** [MicrosoftDocs/windows-itpro-docs#6832]
[经常出现乱码]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 4edaae97-455b-d25a-9228-5309e24b4aa3
* Version Independent ID: d38e56a7-d553-e519-95a9-dc93e2cdc771
* Content: [Microsoft Defender SmartScreen 概述（Windows 10） - Windows security](https://docs.microsoft.com/zh-cn/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview)
* Content Source: [windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by rocky-co** [comment]
⚠

**Comment by illfated** [comment]
Translated via machine translation/web engines:

"China often uses Microsoft's official website as a programmer." (Bing Translator)
"Programmers on Microsoft's official website are often used in China." (Google)

我不知道这里的意图是什么，是说一些好话，还是意在表明某种形式的问题。
// 我不知道这是什么意思，是说些好话还是表示某种形式的问题。//

( I do not know what the intention is here, whether it is to say something nice or if it is meant to indicate some form of problem. )
