### ISSUE TITLE
MD ATP sku options update needed

### ISSUE THREAD

**Issue by amessmer-hub** [MicrosoftDocs/windows-itpro-docs#6838]
I have concerns that we no longer need the E5/A5 level of license to add-on to plans. Can you please update page or correct me if i am wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by amessmer-hub** [comment]
Specifically the below pulled from here: https://microsoft.sharepoint.com/teams/windef/atp/SitePages/Home.aspx

Microsoft Defender ATP Standalone SKU FAQs 1) What is the Microsoft Defender ATP Standalone SKU? We are removing the Windows E3 license pre-requirement from Microsoft Defender Advanced Threat Protection (MDATP). Previously, in order to get Microsoft Defender ATP (Windows E5) customers were required to first activate Windows Enterprise (Windows E3) before they could get MDATP. With the standalone SKU, customers will be able to purchase MDATP for their all supported client devices regardless of their Windows E3 license ownership and without the requirement to first have Windows E3. Meaning, those that have Windows Pro can now buy MDATP directly. There is no change to existing Windows E5, M365 E5 Security, and M365 E5 offers as those will continue including MDATP. 2) Why are we doing this? There has been demand from customers who want to purchase MDATP but who do not have or do not want Windows E3. This new SKU will help to unblock customers who are in this scenario. 3) What kind of devices are supported? Any device running Windows Pro or Mac devices. The previously announced standalone MDATP for Mac is now part of this offer. 4) Which Microsoft Defender ATP components are part of this SKU? All Microsoft Defender ATP components are included in this SKU. This includes Threat and Vulnerability Management, Attack Surface Reduction, Next Generation Protection, Endpoint Detection and Response, Auto Investigation and Remediation, Microsoft Threat Experts, and centralized configuration, management, and rich APIs. 5) Does this eliminate the need for Windows E3? No. Windows E3 has a number of capabilities that Windows Pro does not have. There are security capabilities that are not part of Windows Pro that require an E3 license. Buying the standalone SKU does not entitle Windows Pro users to Windows E3 capabilities. The following security capabilities require a Windows E3 license and will not work if the customer moves from Windows Pro to MDATP: • Credential Guard • AppLocker 6) When will this SKU be available? The standalone MDATP SKUs will be available in EA on Feb 1st and in CSP on Mar 1st. 7) How much does this SKU cost? The pricing of this offer is identical to Win E5 Step-up SKU, ~$5 per user/month

**Comment by mjcaparas** [comment]
@amessmer-hub Thank you for your feedback. We will update this topic as required.
In future it is not advisable to expose internal information here.

**Comment by mypil** [comment]
@amessmer-hub - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author @mjcaparas so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Comment by amessmer-hub** [comment]
So no change in the licenses occurred? I have a .pdf that says “5” level of sku’s is no longer required.

Responding to COVID-19 together<https://news.microsoft.com/covid-19-response/>,

Alex Messmer
Digital Sales Representative
Microsoft Cloud Solutions
Phone: 701-433-4527
[cid:image001.jpg@01D0B31C.82FF73E0]

Book meeting with me using Microsoft Bookings?<https://outlook.office365.com/owa/calendar/Microsoft2366643@microsoft.onmicrosoft.com/bookings/>

     Microsoft respects your privacy. To learn more, please read our Privacy Statement<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D81184&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917262437&sdata=%2Fwt%2FfE3BCgJ6PmuSnt1c1Bq1rMBixLTIaHKtAuuylZE%3D&reserved=0>.

  *   If you would prefer not to receive future promotional emails from Microsoft Corporation please click here<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprofile.microsoft.com%2FContactPreferences%2Fsecurepages%2Feeeoptout.aspx&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917262437&sdata=a91to9jpxSasuQlx%2Fv81uFsM83sBJhkJs%2BMu9uTf%2BUE%3D&reserved=0>.
  *   These settings will not affect any newsletters you've requested or any mandatory service communications that are considered part of certain Microsoft services.
  *   To set your contact preferences for other Microsoft Communications, click here<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D92781&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917272432&sdata=6EGyIAbtNLZ17jwTEeV4IinT29A2a%2BmNl1IRSm2qGYw%3D&reserved=0>.

**Comment by amessmer-hub** [comment]
Responding to COVID-19 together<https://news.microsoft.com/covid-19-response/>,

Alex Messmer
Digital Sales Representative
Microsoft Cloud Solutions
Phone: 701-433-4527
[cid:image001.jpg@01D0B31C.82FF73E0]

Book meeting with me using Microsoft Bookings?<https://outlook.office365.com/owa/calendar/Microsoft2366643@microsoft.onmicrosoft.com/bookings/>

     Microsoft respects your privacy. To learn more, please read our Privacy Statement<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D81184&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917262437&sdata=%2Fwt%2FfE3BCgJ6PmuSnt1c1Bq1rMBixLTIaHKtAuuylZE%3D&reserved=0>.

  *   If you would prefer not to receive future promotional emails from Microsoft Corporation please click here<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprofile.microsoft.com%2FContactPreferences%2Fsecurepages%2Feeeoptout.aspx&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917262437&sdata=a91to9jpxSasuQlx%2Fv81uFsM83sBJhkJs%2BMu9uTf%2BUE%3D&reserved=0>.
  *   These settings will not affect any newsletters you've requested or any mandatory service communications that are considered part of certain Microsoft services.
  *   To set your contact preferences for other Microsoft Communications, click here<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D92781&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917272432&sdata=6EGyIAbtNLZ17jwTEeV4IinT29A2a%2BmNl1IRSm2qGYw%3D&reserved=0>.

**Comment by illfated** [comment]
@amessmer-hub : Please see commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/4f899c9ae48950bb091b7d00d95eed4425a10815 from June 5, 2020.
This commit is currently only viewable on GitHub, but will migrate to docs.microsoft.com within a few days.

Please also note, as @mjcaparas mentioned, that unless your personal info in your posted messages is also public information, it is not advisable to expose it here.

**Comment by amessmer-hub** [comment]
Team,

I was under the impression that it was due to me inadvertently posting access to an internal SharePoint not because of the info I was presenting? I have never done a support page correction just started last Oct, my posting of that link was I thought to internal resources only.

Did you by chance read the attached doc here? I have a few customers I’m working with and have gotten conflicting info on about this hence reaching out here to our support docs people.

Justin is a CE and told me E3, Brigitte my TSP told me any license and it can be put on.

[cid:image001.png@01D63D72.F601D690]

[cid:image002.png@01D63D72.F601D690]

Responding to COVID-19 together<https://news.microsoft.com/covid-19-response/>,

Alex Messmer
Digital Sales Representative
Microsoft Cloud Solutions
Phone: 701-433-4527
[cid:image001.jpg@01D0B31C.82FF73E0]

Book meeting with me using Microsoft Bookings?<https://outlook.office365.com/owa/calendar/Microsoft2366643@microsoft.onmicrosoft.com/bookings/>

     Microsoft respects your privacy. To learn more, please read our Privacy Statement<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D81184&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917262437&sdata=%2Fwt%2FfE3BCgJ6PmuSnt1c1Bq1rMBixLTIaHKtAuuylZE%3D&reserved=0>.

  *   If you would prefer not to receive future promotional emails from Microsoft Corporation please click here<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprofile.microsoft.com%2FContactPreferences%2Fsecurepages%2Feeeoptout.aspx&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917262437&sdata=a91to9jpxSasuQlx%2Fv81uFsM83sBJhkJs%2BMu9uTf%2BUE%3D&reserved=0>.
  *   These settings will not affect any newsletters you've requested or any mandatory service communications that are considered part of certain Microsoft services.
  *   To set your contact preferences for other Microsoft Communications, click here<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D92781&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917272432&sdata=6EGyIAbtNLZ17jwTEeV4IinT29A2a%2BmNl1IRSm2qGYw%3D&reserved=0>.

**Comment by illfated** [comment]
Thank you for the feedback. Please forgive me in case I have caused confusion or unneeded distress.

**Comment by illfated** [comment]
Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

**Comment by amessmer-hub** [comment]
Team,

No distress caused just trying to navigate licensing and be customer obsessed. @Cady Aston-Paulson<mailto:cadya@microsoft.com> if you see my previous emails I have been given different answers by CE’s, TSP’s, and our Support Documents page. Not sure who to listen to hear and this is a hot solution for a handful of my current OPTY’s. Do you know what resource we can refer to here?

[cid:image002.png@01D63D91.B51FF110]

[cid:image003.png@01D63D91.B51FF110]
Responding to COVID-19 together<https://news.microsoft.com/covid-19-response/>,

Alex Messmer
Digital Sales Representative
Microsoft Cloud Solutions
Phone: 701-433-4527
[cid:image001.jpg@01D0B31C.82FF73E0]

Book meeting with me using Microsoft Bookings?<https://outlook.office365.com/owa/calendar/Microsoft2366643@microsoft.onmicrosoft.com/bookings/>

     Microsoft respects your privacy. To learn more, please read our Privacy Statement<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D81184&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917262437&sdata=%2Fwt%2FfE3BCgJ6PmuSnt1c1Bq1rMBixLTIaHKtAuuylZE%3D&reserved=0>.

  *   If you would prefer not to receive future promotional emails from Microsoft Corporation please click here<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprofile.microsoft.com%2FContactPreferences%2Fsecurepages%2Feeeoptout.aspx&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917262437&sdata=a91to9jpxSasuQlx%2Fv81uFsM83sBJhkJs%2BMu9uTf%2BUE%3D&reserved=0>.
  *   These settings will not affect any newsletters you've requested or any mandatory service communications that are considered part of certain Microsoft services.
  *   To set your contact preferences for other Microsoft Communications, click here<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D92781&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917272432&sdata=6EGyIAbtNLZ17jwTEeV4IinT29A2a%2BmNl1IRSm2qGYw%3D&reserved=0>.

**Comment by amessmer-hub** [comment]
Team,

Can I have an update on this? The information is incorrect on the licensing page.

Responding to COVID-19 together<https://news.microsoft.com/covid-19-response/>,

Alex Messmer
Digital Sales Representative
Microsoft Cloud Solutions
Phone: 701-433-4527
[cid:image003.jpg@01D656B1.3374A190]

Book meeting with me using Microsoft Bookings?<https://outlook.office365.com/owa/calendar/Microsoft2366643@microsoft.onmicrosoft.com/bookings/>

     Microsoft respects your privacy. To learn more, please read our Privacy Statement<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D81184&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917262437&sdata=%2Fwt%2FfE3BCgJ6PmuSnt1c1Bq1rMBixLTIaHKtAuuylZE%3D&reserved=0>.

  *   If you would prefer not to receive future promotional emails from Microsoft Corporation please click here<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprofile.microsoft.com%2FContactPreferences%2Fsecurepages%2Feeeoptout.aspx&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917262437&sdata=a91to9jpxSasuQlx%2Fv81uFsM83sBJhkJs%2BMu9uTf%2BUE%3D&reserved=0>.
  *   These settings will not affect any newsletters you've requested or any mandatory service communications that are considered part of certain Microsoft services.
  *   To set your contact preferences for other Microsoft Communications, click here<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D92781&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917272432&sdata=6EGyIAbtNLZ17jwTEeV4IinT29A2a%2BmNl1IRSm2qGYw%3D&reserved=0>.


From: Alexander Messmer
Sent: Monday, June 8, 2020 8:58 AM
To: MicrosoftDocs/windows-itpro-docs <reply@reply.github.com>; MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/windows-itpro-docs] MD ATP sku options update needed (#6838)

Team,

I was under the impression that it was due to me inadvertently posting access to an internal SharePoint not because of the info I was presenting? I have never done a support page correction just started last Oct, my posting of that link was I thought to internal resources only.

Did you by chance read the attached doc here? I have a few customers I’m working with and have gotten conflicting info on about this hence reaching out here to our support docs people.

Justin is a CE and told me E3, Brigitte my TSP told me any license and it can be put on.

[cid:image004.png@01D656B1.3374A190]

[cid:image005.png@01D656B1.3374A190]

Responding to COVID-19 together<https://news.microsoft.com/covid-19-response/>,

Alex Messmer
Digital Sales Representative
Microsoft Cloud Solutions
Phone: 701-433-4527
[cid:image003.jpg@01D656B1.3374A190]

Book meeting with me using Microsoft Bookings?<https://outlook.office365.com/owa/calendar/Microsoft2366643@microsoft.onmicrosoft.com/bookings/>

     Microsoft respects your privacy. To learn more, please read our Privacy Statement<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D81184&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917262437&sdata=%2Fwt%2FfE3BCgJ6PmuSnt1c1Bq1rMBixLTIaHKtAuuylZE%3D&reserved=0>.

  *   If you would prefer not to receive future promotional emails from Microsoft Corporation please click here<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprofile.microsoft.com%2FContactPreferences%2Fsecurepages%2Feeeoptout.aspx&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917262437&sdata=a91to9jpxSasuQlx%2Fv81uFsM83sBJhkJs%2BMu9uTf%2BUE%3D&reserved=0>.
  *   These settings will not affect any newsletters you've requested or any mandatory service communications that are considered part of certain Microsoft services.
  *   To set your contact preferences for other Microsoft Communications, click here<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D92781&data=02%7C01%7CAlexander.HansonMessmer%40microsoft.com%7Cad66523c1c9a41dcedb508d74dc4ca5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063379917272432&sdata=6EGyIAbtNLZ17jwTEeV4IinT29A2a%2BmNl1IRSm2qGYw%3D&reserved=0>.
