### ISSUE TITLE
Please update Windows Defender Antivirus to Microsoft Defender Antivirus

### ISSUE THREAD

**Issue by AMaini503** [MicrosoftDocs/windows-itpro-docs#6840]
Expand the tree to Windows components > **Windows Defender Antivirus** and then the Location specified in the table below.  

Isn't the policy now available under Windows components > **Microsoft Defender Antivirus**?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6448160-696e-9823-ca37-b54189530890
* Version Independent ID: e1678a96-0bb7-87fb-1d3e-efcc5984c1fb
* Content: [Remediate and resolve infections detected by Windows Defender Antivirus - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-remediation-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-remediation-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/configure-remediation-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thank you @AMaini503. On my work machine, I see Microsoft Defender Antivirus as you indicate. On my home machine, it's still Windows Defender Antivirus. Nevertheless, I'll get this article updated.

**Comment by RAJU2529** [comment]
@denisebmsft . I seen microsoft defender antivirus on my machine.

**Comment by Jreeds001** [comment]
Hi Denise,

Yes, Thomas and I are in the process of changing these files.

Thanks,
Jeff

**Comment by mypil** [comment]
@AMaini503 @RAJU2529 - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/1556400. 


Thank you for your contribution to make the docs better! Much appreciated!
