### ISSUE TITLE
Unclear wording

### ISSUE THREAD

**Issue by markstan** [MicrosoftDocs/windows-itpro-docs#6841]
"This script allow reset the Windows Update Agent resolving issues with Windows Update."

I'm not sure what's trying to be communicated here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Looks like the text line is just a verbatim copy-paste of the author's description from the gallery.technet.microsoft.com page containing the script. Good point, it needs a bit more text to describe properly what the script does. Also, the current phrasing of that line indicates some minor sub-standard English usage.

Reading the Q & A section of that TechNet gallery page, I found that the script author has created both an introductory page (README.md) and a wiki page for this script tool, here on GitHub:
- https://github.com/ManuelGil/Reset-Windows-Update-Tool/blob/master/README.md
- https://github.com/ManuelGil/Reset-Windows-Update-Tool/blob/master/docs/wiki/en/Home.md

Maybe you could have a quick look at those pages and post back here if you find some phrasing there you would like to see replacing that unclear sentence?

**Comment by VLG17** [comment]
@markstan A detailed description has been added to the article:

> will completely reset the Windows Update client settings. It has been tested on Windows 7, 8, 10, and Windows Server 2012 R2. It will configure the services and registry keys related to Windows Update for default settings. It will also clean up files related to Windows Update, in addition to BITS related data.

**Comment by illfated** [comment]
(ref. #8357 & #8358 )
