### ISSUE TITLE
Strange link in document Ready4Microsoft365.com

### ISSUE THREAD

**Issue by contactbrenton** [MicrosoftDocs/windows-itpro-docs#6842]
the link "Microsoft Defender Advanced Threat Protection (Microsoft Defender ATP)"

mentions this url.
Ready4Microsoft365.com 

When you visit it, it just says "probably not tbh"

Is there an updated version of this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bb97062-4d77-01be-0f3a-fcb81dfb8d7e
* Version Independent ID: 146889db-754c-cf26-9de6-49caae513d02
* Content: [Why you should use Windows Defender Antivirus together with Microsoft Defender Advanced Threat Protection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/why-use-microsoft-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/why-use-microsoft-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/why-use-microsoft-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
Looks like "the jury is still out" on this one. Not much useful information to find in web searches about the site, besides Reddit and some pages referencing the document itself.

- https://www.bing.com/search?q=Ready4Microsoft365.com
- https://www.google.com/search?&q=Ready4Microsoft365.com

You might want to glance at the Reddit page https://www.reddit.com/r/sysadmin/comments/eusy27/microsoft_published_an_unregistered_domain_in_an/ to see what they think of that domain, although there are no definite answers to be found there either.

**Comment by illfated** [comment]
By the way, one of my initial thoughts about that domain circled around the question "What if the intention of the domain name was to be used in an online query to check if the computer in question is ready to enroll in Microsoft365?" Then again, seeing that the domain is registered via the registrar porkbun.com (https://www.whois.com/whois/ready4microsoft365.com) to a very superficially described owner, it does not seem to be the case. It may take quite a while before we see an updated version of the PDF document, depending on how Microsoft wants to go about regarding the usage of that domain name.

**Comment by e0i** [comment]
The link seems to have been fixed, now it points to `https://www.microsoft.com/microsoft-365/windows/microsoft-defender-atp`.
