### ISSUE TITLE
Add Firmware update information for New Surface Dock 2

### ISSUE THREAD

**Issue by danchar4** [MicrosoftDocs/windows-itpro-docs#6844]
Please add firmware update information for the new Surface Dock 2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7b356e-3dbd-7f59-845e-a92e05865a52
* Version Independent ID: 711c5497-373f-662c-7fae-ba60f046e50c
* Content: [Microsoft Surface Dock Firmware Update - Technical information for IT administrators - Surface](https://docs.microsoft.com/en-us/surface/surface-dock-firmware-update)
* Content Source: [devices/surface/surface-dock-firmware-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-dock-firmware-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**
* Label: **devices**

**Comment by javianpicardo33** [comment]
I purchased new surface dock 2 to connect my surface pro 7 to our my two external monitors using usb-c cables. Randomly either one of the monitors would connect through the usb-c ports. Then, I then connected the one HDMI-USC-C wire to Surface Pro 7 device & then both monitors randomly.(50% of the times)

Both monitors are Acer 32 Inch (EB321HQ) with resolution of 1920*1080 through the usb-c port.

Image

To be clear, I firstly connected the surface dock 2 adapter cable to the surface pro 7 and Acer monitors are connected to the surface dock 2 through the usb-c in video capable USB-C connectors. (See image above). In Control panel display; using the "detect monitor" feature there was "no monitor detected" or no signal received in one of the monitors.

I have done windows updates , surface pro 7 drivers/firmware updates, cleared display cache, installed surface Dock 2 driver updates, tried Surface Dock 2 SEMM installation but still there is no luck with detecting both monitors at once.

Temporary resolution found is resetting the video drivers using (Win + Ctrl + Shift + B) which helps in detecting the external monitors together but it is not 100% sound proof solution. Please provide a solution or provide a API interface option to detect new monitors when the Dock 2 adapter is connected.

**Comment by aczechowski** [comment]
I just merged the old PR from @VLG17 in the devices repo to add a note about the dock 2 information on the download center: https://www.microsoft.com/en-us/download/details.aspx?id=101317

So I'm closing this issue
