### ISSUE TITLE
"Assign devices to servicing channels for Windows 10 updates" - DIY Semi Annual Channel instructions don't work on 19H2

### ISSUE THREAD

**Issue by metathinker** [MicrosoftDocs/windows-itpro-docs#6847]
The current version of this page as of May 31, 2020 says:

> **To assign a single devices locally to the Semi-Annual Channel**
>
>1. Go to **Settings > Update & security > Windows Update > Advanced options**.
>1. Select **Defer feature updates**.

However, on my system running Windows Enterprise version 1909 (OS Build 18363.836), it's not possible to "Select **Defer feature updates**" as that button or toggle isn't actually there. The closest analog (see English screenshot below) is an setting "A feature update includes new capabilities and improvements. It can be deferred for this many days: [enter number]".

Would you kindly take a look and correct this documentation page or the product as needed?
![Choose when updates are installed](https://user-images.githubusercontent.com/1039862/83360471-75e93280-a336-11ea-9636-ce9c05d0f06e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5400f8b-2ed0-7960-4e3d-2f3444be7e6b
* Version Independent ID: 81bd37f4-301b-b5ab-cda2-972a72a31ae7
* Content: [Assign devices to servicing channels for Windows 10 updates (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-servicing-channels-windows-10-updates)
* Content Source: [windows/deployment/update/waas-servicing-channels-windows-10-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-servicing-channels-windows-10-updates.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by metathinker** [comment]
I wonder if the whole "Assign devices to Semi-Annual Channel" section of the page, where the quoted instructions came from, is now both wrong and irrelevant, since Microsoft has eliminated the Semi-Annual Channel (Targeted) as noted in that section:

>Due to [naming changes](https://docs.microsoft.com/en-us/windows/deployment/update/waas-overview#naming-changes), older terms like CB and CBB might still be displayed in some of our products, such as in Group Policy. If you encounter these terms, "CB" refers to the Semi-Annual Channel (Targeted)--which is no longer used--while "CBB" refers to the Semi-Annual Channel.

**Comment by RAJU2529** [comment]
@metathinker .Sir are you from Microsoft ?.

**Comment by jaimeo** [comment]
This article is one of many that is about to be either rewritten or retired as part of a major overhaul of all this content. The table of servicing channels (in the first section) should be current, despite the UI mismatch you've identified. The note about naming changes has to remain because there are still corners of the operating system where you can come across the older terminology.

@arcarley can you advise on the UI mismatch reported here?

**Comment by Reeced40** [comment]
@metathinker thank you for helping improve MS Docs. This article has recently been updated. Please let me know if you still need assistance or if anything else needs to be changed in the document.

**Comment by metathinker** [comment]
@Reeced40 In the latest version of this page, the text I quoted above is still unchanged, and it still does not match the actual Windows UI. In fact, the difference is even greater now.

Below is how the Windows Update Advanced Options page looks in Windows v. 20H1 build 19041.508. Now, there is nothing about deferring "Feature Updates" and "Quality Updates" separately, there is just one option to defer all system software updates until a specified date.

From your colleague @jaimeo's previous comment on June 1, I was under the understanding that this page was to go away entirely or at least be totally rewritten, but it seems pretty close to what it was back then.

![image](https://user-images.githubusercontent.com/1039862/94599512-5f4fdb00-0245-11eb-8478-b5a151a194b1.png)

**Comment by arcarley** [comment]
@metathinker I just made edits to the document that haven't been merged into master. This change removes aspects of using the Settings UX. 

Best,
Aria
