### ISSUE TITLE
How WIP works with sensitivity labels link is broken

### ISSUE THREAD

**Issue by uowdaniel** [MicrosoftDocs/windows-itpro-docs#6850]
The topic 
"How WIP works with sensitivity labels"
https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/how-wip-works-with-labels
seems to be broken; clicking on it returns to the General guidance and best practices page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a753e9c-7902-5009-4430-97f32e191334
* Version Independent ID: e374af42-5b17-60bd-ceb1-995dfc5f577a
* Content: [General guidance and best practices for Windows Information Protection (WIP) (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/guidance-and-best-practices-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/guidance-and-best-practices-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/guidance-and-best-practices-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@uowdaniel Could you please also share the article that contains the broken link which you referenced above?

**Comment by uowdaniel** [comment]
Sorry – it was almost four months ago, and I don’t seem to have a record of the article. I’d imagine it was somewhere in the WIP documentation, given that the heading was "How WIP works with sensitivity labels". Most likely I’d have reported it from the actual page, hasn’t that come through?

Googling for "How WIP works with sensitivity labels”, there are Microsoft pages amongst the hits but they no longer seem to have that text on them (presumably they’ve been changed since the last crawl?)

**Comment by illfated** [comment]
Searching for the exact match for the page title "How WIP works with sensitivity labels" only returns page content for this page (by 2 different views). I have tried looking for a change to this page, where this could have changed, but it does not return any useful information of page changes which could explain the origin of this ticket. I can only assume that there has been so much change that even this ticket no longer has the correct originating page, making it close to impossible to find anything, even in the Web Archives (Wayback Machine) without knowing the exact URL for the original page from May 2020.

**Comment by illfated** [comment]
Unfortunately, neither this GitHub ticket page nor the referenced page https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/how-wip-works-with-labels exists in the backups on https://web.archive.org/ ("No URL has been captured for this domain.")

**Comment by VLG17** [comment]
@illfated Thank you for looking into it. It confirms my findings.

@uowdaniel No worries, i understand it's been a long time since you found this. Since we cannot find the original article that contains the incorrect link, i'll just say that it was fixed (until proven wrong) in the meantime.

If we manage to identify it again, we will fix it.
