### ISSUE TITLE
Confusing Example 2- Dates are different

### ISSUE THREAD

**Issue by tomamer** [MicrosoftDocs/windows-itpro-docs#6851]
Example 2 is labelled as: Get all the alerts that created after 2018-10-20 00:00:00
Yet the code related shows:
HTTP GET  https://api.securitycenter.windows.com/api/alerts?$filter=alertCreationTime+gt+2018-11-22T00:00:00Z

Looks like the GET request is pulling data created after 2018-11-22, not 2018-10-20 as the label suggests 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba741c25-911f-7766-5025-70cca2fc65ea
* Version Independent ID: 45808cc4-01b7-3033-dd69-cdf032467064
* Content: [OData queries with Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/exposed-apis-odata-samples)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/exposed-apis-odata-samples.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/exposed-apis-odata-samples.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Resolved by PR #8364 - ticket can be closed.
