### ISSUE TITLE
Link to Microsoft Search improvements is broken

### ISSUE THREAD

**Issue by gtwy** [MicrosoftDocs/windows-itpro-docs#6853]
Hello,

The improvements for Microsoft Search are very important for my company as the 1909 update broke search functionality for most of my users that are using mapped/network drives. When I saw that 2004 was finally available, I checked the notes to see what improvements had been made to searching. Sadly, the link to the improvements goes nowhere. Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d651de3c-b8eb-e8d9-8138-1eadb758bf2e
* Version Independent ID: a19a8b65-0f4a-efd5-7f83-56bd07cc8c3b
* Content: [What's new in Windows 10, version 2004 - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-2004)
* Content Source: [windows/whats-new/whats-new-windows-10-version-2004.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/whats-new-windows-10-version-2004.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
It looks like the link https://insider.windows.com/community-news/desktop-search/ has been redirected. I'll replace this with a better link. Thanks for surfacing the issue!

**Comment by greg-lindsay** [comment]
Ah I see the problem. The link isn't localized properly.
https://insider.windows.com/en-us/community-news/desktop-search/

The link works if you add the en-us into the URL

**Comment by gtwy** [comment]
Good catch. Thanks for quick resolution.

**Comment by greg-lindsay** [comment]
I will also see if I can find out specifically for you if any issues with mapped drives were addressed.

**Comment by gtwy** [comment]
Thanks! I went through the site that you linked. After reading it, I feel hopeful that this will work out. It looks like there is a new "Classic" mode which may take my users back to the way it worked previously.

I understand the need to incorporate OneDrive/Sharepoint searching, and most of my customers benefited from the new search features, but I have a few places experiencing problems searching their on-prem storage.

**Comment by greg-lindsay** [comment]
Let me know if you see that things are fixed. I'll keep searching here for some more info.

**Comment by gtwy** [comment]
Sure! I'll update this thread in a week or two after we run a couple machines with the update. The problems were intermittent, so I won't know immediately if this fixes it.

**Comment by greg-lindsay** [comment]
I found that KB4532695 had some bug fixes for search but I haven't seen any specifically related to mapped drives. If you see the problem isn't resolved maybe you can send me some more details.

Also, if your remote drives are on a NAS, be sure to update the firmware there because sometimes it needs an update to work properly with new features in Windows.

**Comment by greg-lindsay** [comment]
One thing, if you still have issues can you open a new issue here rather than reply to this one. I don't get notifications for issues that are closed.
