### ISSUE TITLE
Delivery Optimization over VPN

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/windows-itpro-docs#6855]
How does the client determine that it's on VPN?  Does this work with all VPN solutions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df445cda-3b0a-2ad7-e3cc-23e159013530
* Version Independent ID: a6bb5f97-d350-f7b7-77f7-b0093322289d
* Content: [Delivery Optimization reference - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization-reference#enable-peer-caching-while-the-device-connects-via-vpn)
* Content Source: [windows/deployment/update/waas-delivery-optimization-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-delivery-optimization-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@narkissit can you advise?

**Comment by lindspea** [comment]
@russrimm thank you for reaching out. Have you got a VPN available to you? There are different VPN apps that you can install.

**Comment by nam31** [comment]
@russrimm We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve. Thank you.
