### ISSUE TITLE
Bug: Password length value range is inaccurate.

### ISSUE THREAD

**Issue by MSRobertD** [MicrosoftDocs/windows-itpro-docs#6856]
This topic states that the supported values for password length are 0-14 characters.  The GPO in this topic supports well above 14 characters as a maximum, e.g. 20.  Please update the topic with the correct value range.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bcaf30b-7304-6874-ba5d-791cc4d435d2
* Version Independent ID: 961def9f-094a-3d1e-82a4-bb152c2e5a1e
* Content: [Minimum password length (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/minimum-password-length)
* Content Source: [windows/security/threat-protection/security-policy-settings/minimum-password-length.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/minimum-password-length.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
@e0i : Would it be OK to ask one of the tech writers to research if there has been any notable changes to the password requirements in Windows 10 in builds released after 04/19/2017, and whether there is a meaningful difference between what is supported by the Password Policy GPO in contrast to the OS itself?

**Comment by illfated** [comment]
@MSRobertD : Sorry, I did not notice your job title before commenting. I only compared your ticket comment with the page contents.

Would you like to see the number 14 increased to 20, or a higher specific number?
Are there any other sources to reference, besides the GPO itself?

**Comment by MSRobertD** [comment]
Thanks for the quick replies.  Here's a bit more context, info from our team, and additional contacts.

I consult for Mike Grimm (mgrimm) on the ENS team.  Our part of the team runs a set of security and privacy certifications for Microsoft, through which we get a host of security functionality in Windows independently verified - including password management.  The standard that we certify against requires support for passwords of 15+ characters, which is how this topic got (and the GPO behind it) got flagged.  

In our own testing, which was not extensive, we were able to get the GPO to work with a password of 20 characters.  So yes, 20 works.  But I do not know if that's the upper limit.  

If you have any questions outside of this thread, feel free to contact me and cc MGrimm if you need an MS-internal contact on the thread.

**Comment by illfated** [comment]
I think that is sufficient documentation to initiate a Pull Request to the page. Thank you for providing the extra information.

Thank you also for the references, which may come in handy, in case anyone asks for references in my upcoming PR.

**Comment by illfated** [comment]
There you go, PR #6875 is ready for review. Feel free to comment and post suggestions if you find anything else in need of updating/adjusting.
