### ISSUE TITLE
mountvol X: /s The parameter is incorrect.

### ISSUE THREAD

**Issue by martinvana** [MicrosoftDocs/windows-itpro-docs#6858]
The description how to disable Device Guard / System Guard may not be sufficient and doesn't offer ways to detect the state of the system in thet respect.

mountvol X: /s
comes with error"
The parameter is incorrect.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#disable-windows-defender-credential-guard)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Please see all the closed issues here in this repository. This "issue" has been discussed for at least 2 years now and the parameter works if you are using the right kind of hardware.

Repository issue search for `mountvol X: /s`: https://github.com/MicrosoftDocs/windows-itpro-docs/search?q=%22mountvol+X%3A+%2Fs%22&type=Issues

- **Disabling Windows Defender Credential Guard is not working with Windows 10 1803 #5190** by ealfan was closed on Oct 23 2019
- **none of this worked - I still am unable to run my virtual machine #4952** by OhiosBatman was closed on Sep 23 2019
- **Instructions regarding Windows Defender Credential Guard EFI variables do not work #4221** by foxbunny was closed on Jun 23 2019
- **variable is incorrect #4084** by lengthmin was closed on Jul 24 2019
- **Command line instructions are incorrect #3234** by RichardRanft was closed on Sep 6 2019
- **Neither the steps worked and nor the tool worked :-( #3108** by sachinmar was closed on Apr 8 2019
- **maybe an extra step is mentioned in the doc? #2663** by sasanmcp was closed on Feb 20 2019
- **Windows Sandbox Enables Windows Defender Credential Guard #2612** by hadeernd was closed on May 7 2019
- **Instructions for disabling not working... #2569** by darnocian was closed on May 9 2019
- **Credential guard enabled but not running... #2327** by haseeb1986 was closed on Apr 16 2019
- **[SOLVED] ERROR!! "The device is not valid as specified" ! #2216** by ahmedbr was closed on Jun 3 2019
- **Can't disable Credential Guard #2141 by tomneko was closed on Feb 28 2019
- **Terminated Credential Guard #1984** by jkd2020-github was closed on Jun 9 2019
- **DOES NOTHING #1924** by cacodemon9000 was closed on Aug 14 2019
- **-SOLVED- It doesn't work for me #1915** by 2IRG-FB was closed on Jun 9 2019
- **Missing parts for VMWARE and HAXM users #1862** by Vahhab was closed on Oct 16, 2018
- **The parameter is incorrect. #1776** by damian123 was closed on Jun 23 2019
- **bcdedit missing DISABLE-VBS identity protection security #1623** by mgeatz was closed on Sep 12, 2018
- **(Solved) Raw-mode is unavailable courtesy of Hyper-V. (VERR_SUPDRV_NO_RAW_MODE_HYPER_V_ROOT) #1556** by DuggerConsulting was closed on Jun 23 2019
- **Credential Guard via Intune #1400** by tmguinn was closed on Apr 11 2019

**Comment by illfated** [comment]
@RAJU2529 : Would you like to point @martinvana to some part of the documentation pointing out what the hardware (and BIOS/UEFI) requirements is for the command to work as expected?

**Comment by RAJU2529** [comment]
@illfated . First of all I want to know , about his laptop or desktop configuration with processor , installed device driver.  Windows 10 os version and edition . Then his entered commands,  and settings he applied

**Comment by martinvana** [comment]
Thanks for the pointers. I guess @illfated directed me to a plenty of bedtime reading ;-)
The system info is:
Dell Inc. Precision T3610
Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
Windows 10 Enterprise 2016 LTSB 64-bit (10.0, Build 14393) (14393.rs1_release.200504-1524)
BIOS Mode is "Legacy" (not UEFI)

The failing command is:
```C:\Windows\system32>mountvol.exe x: /s
The parameter is incorrect. ```

**Comment by illfated** [comment]
> Dell Inc. Precision T3610
> Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
> Windows 10 Enterprise 2016 LTSB 64-bit (10.0, Build 14393) (14393.rs1_release.200504-1524)
> BIOS Mode is "Legacy" (not UEFI)
> 
I could be mistaken, but I think you need UEFI for virtualization to be able to use the /s parameter (in addition to Hyper-V).

Windows Server 2016 Standard (production) on my workplace, where I am able to run the command with the /s parameter, uses UEFI mode and Hyper-V, so I would assume those are part of the requirements.

**Comment by RAJU2529** [comment]
@martinvana . You need UEFI mode and windows 10 1803 and later version with professional or enterprise.

**Comment by illfated** [comment]
Just to add the Windows Server version information from my workplace server, it is as follows:
- Windows Server 2016 (Standard) Version 1607 (OS Build 14393.3686)

**Comment by martinvana** [comment]
Thanks to @illfated and @RAJU2529 for the help confirming that the issue is based on the UEFI mode and not related to Windows vintage (as we both run Version 1607).
I can enable Hyper-V and run Docker, disable (reboot) and run VMW but I cannot have Hyper-V enabled and disable Device Guard / System Guard (at least following the procedure using "mountvol X: /s") what is apparently required for latest VMW 15.5.5 which now "should" be able to coexist with Hyper-V for the first time. But that is a different topic. Thanks for the help!
