### ISSUE TITLE
System/AllowLocation

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/windows-itpro-docs#6860]
When I look at the corresponding sensors.admx, the DisableLocation_2 policy only has two options.

```
<policy name="DisableLocation_2" class="Machine" displayName="$(string.DisableLocation)" explainText="$(string.DisableLocation_Explain)" key="Software\Policies\Microsoft\Windows\LocationAndSensors" valueName="DisableLocation">
      <parentCategory ref="LocationAndSensors" />
      <supportedOn ref="windows:SUPPORTED_Windows7"/>
      <enabledValue>
        <decimal value="1" />
      </enabledValue>
      <disabledValue>
        <decimal value="0" />
      </disabledValue>
</policy>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c833e5b-0fcf-2ace-a90a-3270286d23a9
* Version Independent ID: 64afbc38-e7cc-fc14-9d57-1cd119b2395d
* Content: [Policy CSP - System - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-system)
* Content Source: [windows/client-management/mdm/policy-csp-system.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-system.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @icelava ,
the admx file will be changed, please see the response from Microsoft representative in #8406.
Thank you
