### ISSUE TITLE
What are the RegEdit equivalents of Local Group Policy options for Application Guard?

### ISSUE THREAD

**Issue by dumitrurazvancosmin** [MicrosoftDocs/windows-itpro-docs#6870]
Hi, 

I'm looking for the equivalents of Application Guard customization options in Registry Editor. I get that they can be set through either GPO editor, or Intune (Endpoint Protection profile), but I'm in a scenario in which there's no local AD, and the Intune settings automatically force "Managed/Enterprise mode" for no understandable reason, so I am left with configuring the preferences manually through PowerShell scripts. The problem is that some of the Application Guard settings are in the HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Hvsi hive, but not all of them. Can you please provide a list with all of the locations in RegEdit, of each option that we find in Local GPO Editor?

Thank you in advance!
Razvan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15d066f2-0726-bbf9-3425-756ce7dbadee
* Version Independent ID: 03501802-fb28-a89d-a463-e27d2fea7456
* Content: [Testing scenarios with Windows Defender Application Guard (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/test-scenarios-wd-app-guard)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/test-scenarios-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-guard/test-scenarios-wd-app-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@dumitrurazvancosmin . here is the actual path from windows 10 v2004 onwards 
**Computer Configuration\Administrative Templates\Windows Components\Microsoft Defender Application Guard**

![Capture](https://user-images.githubusercontent.com/3296790/83517560-b2fc2300-a4f6-11ea-90fd-b3f35814a560.JPG)

**Comment by dumitrurazvancosmin** [comment]
Hi,

Thank you very much for your quick reply. I am aware of the Local Group Policy Editor location for the settings, but I figure they must have some correspondence in the local Registry Editor (Regedit). For example some of these settings can also be set through 
![image](https://user-images.githubusercontent.com/66310897/83518942-c9e54a00-a4e3-11ea-804d-c0a92ecb4160.png)

When you set the printing preferences to enabled and value 15 in local group policy editor, where does that write in the Registry?

**Comment by RAJU2529** [comment]
@dumitrurazvancosmin . actual path from GPO  setting application guard enabled settings to regsitry is 

![Capture1](https://user-images.githubusercontent.com/3296790/83521889-7f70c700-a4fd-11ea-86c8-80ccef730f2b.JPG)

**Comment by mypil** [comment]
@dumitrurazvancosmin - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @RAJU2529 so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
