### ISSUE TITLE
Information inconclusive from a client (as in Windows 10 computer) perspective

### ISSUE THREAD

**Issue by EckeD** [MicrosoftDocs/windows-itpro-docs#6873]
The information on this page is inconclusive. It describes a security setting affecting the "SMB server" component. This means on a Windows 10 computer it should affect the computer only if it serves as a "SMB server" - so provides e.g. file shares to other Windows 10 computers.

However on the page is a warning that this setting should be tested carefully because it "_will prevent some clients from successfully authenticating to some servers in your environment_". In this sentence "servers" would always be interpreted as actual Windows Server servers, like Domain Controllers and File Servers, not Windows 10 computers (= clients).
But if the setting is applied to a Windows 10 client, how would that affect authentication to any servers that client is trying to access? It should not, as this setting is only affecting the SMB server-component. Am I right?

I therefore think it should be made clearer if this setting - when applied to a Windows 10 computer - indeed will also affect connections to **other** servers (as in e.g. a file server), or only connections to that specific Windows 10 computer (from other computers).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bbdaa9a-f5a1-ce45-bba1-b895287b96f6
* Version Independent ID: 33e69051-dec8-8137-f854-0b2e3766f62a
* Content: [Microsoft network server Server SPN target name validation level (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/microsoft-network-server-server-spn-target-name-validation-level)
* Content Source: [windows/security/threat-protection/security-policy-settings/microsoft-network-server-server-spn-target-name-validation-level.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/microsoft-network-server-server-spn-target-name-validation-level.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by lindspea** [comment]
@EckeD thank you for reaching out. I'm busy researching this, but in the meantime please have a look at this article and let me know if this helps at all - https://docs.microsoft.com/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3

**Comment by nam31** [comment]
@EckeD  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
