### ISSUE TITLE
Missing URLs which are supposed to be added in proxy

### ISSUE THREAD

**Issue by ravikiran471** [MicrosoftDocs/windows-itpro-docs#6874]
Hi Team,

In the Defender AV documentation for [Configure and validate Windows Defender Antivirus network connections](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus), we don’t see the below URLs for the Security Intelligence Update. While they are available in [Windows Update ](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1809-endpoints#windows-update)section of the [Manage connection endpoints for Windows 10 Enterprise, version 1709, 1803, 1809](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1709-endpoints) etc. 

'https://fe3cr.delivery.mp.microsoft.com/ClientWebService/client.asmx' & 'http://download.windowsupdate.com' 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86b0db3-f979-bd1f-78a4-41247510721a
* Version Independent ID: 5289bb5f-f015-7f38-05a1-26a615ae07aa
* Content: [Configure and validate Windows Defender Antivirus network connections - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @ravikiran471 and thank you for the feedback. I'll get the content updated.

**Comment by ravikiran471** [comment]
Hi Team, any update on this?

**Comment by denisebmsft** [comment]
Hello @ravikiran471. This article has been updated and should now contain the necessary details. More updates will go live later today. If something is still missing, please reopen this issue and mention me (denisebmsft). Thanks!
