### ISSUE TITLE
Documentation needs updating

### ISSUE THREAD

**Issue by astzum** [MicrosoftDocs/windows-itpro-docs#688]
Need to update document "In-place upgrades do not support migrations from BIOS to UEFI " This can be done now using MBR2GPT. 
https://docs.microsoft.com/en-us/windows/deployment/mbr-to-gpt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7ce50b9-cb28-a5ba-58f9-010e69f4fde5
* Version Independent ID: a161fed8-151a-1eca-8663-93e9365877d2
* Content: [Upgrade Readiness requirements (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-requirements)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-requirements.md)
* Service: **unspecified**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by jaimeo** [comment]
@greg-lindsay I think this is in your area.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by nenonix** [comment]
@astzum I have looked into this issue and the content in question refers specifically to in-place upgrades from Windows 7 and Windows 8.1 to Windows 10. The documentation on MBR2GPT states  that "Windows 7, 8, or 8.1 are not officially supported. The recommended method to convert these disks is to upgrade the operating system to Windows 10 first, then perform the MBR to GPT conversion." I hope you will agree that In this specific context the content need not be changed.

**Comment by mypil** [comment]
@astzum - Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
