### ISSUE TITLE
Anyone know if network Protection wil support Macs  in the future?

### ISSUE THREAD

**Issue by Kongcecil** [MicrosoftDocs/windows-itpro-docs#6880]
Hi Alle

Anyone know if network Protection wil support Macs  in the future?

**Comment by RAJU2529** [comment]
@Kongcecil .Might be supported, Microsoft  already started concentrating to improve more features on Microsoft defender

**Comment by Kongcecil** [comment]
Looking forward to more features in the OSX version, hopefully Microsoft have some news soon

Thanks.
