### ISSUE TITLE
MDATP Onboarding in SCCM CB/MECM

### ISSUE THREAD

**Issue by chboeye** [MicrosoftDocs/windows-itpro-docs#6881]
The docs regarding the Onboarding process should refer to this link instead of program and package creation for Current Branch version : https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/windows-defender-advanced-threat-protection
It may have been like this for SCCM 2012 (still on support) but we mainly use MECM/SCCM CB now and should point to the right link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c500256-8bbd-fe0c-32e3-c3193652e5cd
* Version Independent ID: 838f93f8-7e0f-e693-f7cf-eac1569f75c8
* Content: [Onboard Windows 10 machines using Configuration Manager - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-sccm)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-sccm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-sccm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by MaratMussabekov** [comment]
Hello @chboeye ,
not sure what you are talking about.
The article already has the link you provided in the [Onboard Windows 10 devices using Microsoft Endpoint Configuration Manager current branch](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-sccm#onboard-windows-10-devices-using-microsoft-endpoint-configuration-manager-current-branch) section.
It only has the link to program and package creation article in the section [Onboard devices using System Center Configuration Manager](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-sccm#onboard-devices-using-system-center-configuration-manager) section. 
The links don't look inconsistent.
What do you think?
Thank you

**Comment by chboeye** [comment]
On section 3 of https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-sccm#onboard-devices-using-system-center-configuration-manager, it points to https://docs.microsoft.com/en-us/previous-versions/system-center/system-center-2012-R2/gg699369(v=technet.10) - Took me 10 min to find out what I was talking about :D
What do you think?

**Comment by MaratMussabekov** [comment]
Hello @chboeye ,
yes, but this part of the article is dedicated to the older versions of  SCCM (it states "This action is supported in System Center 2012 R2 Configuration Manager.")
The article link to which you want to add, is about the feature supported starting since [Update 1606](https://techcommunity.microsoft.com/t5/configuration-manager-archive/now-available-update-1606-for-system-center-configuration/ba-p/274025), so I think link in section 3 is the correct one.

Thank you

**Comment by chboeye** [comment]
Fine for me, let's leave it as it is :)
