### ISSUE TITLE
Bluetooth LE support

### ISSUE THREAD

**Issue by Naphier** [MicrosoftDocs/windows-itpro-docs#6884]
Does the HoloLens not support Bluetooth LE devices?
DeviceWatcher and AdvertisementWatcher can find our device, but when querying GATT services there is a catastrophic failure exception. Seems like GATT discovery is either not implemented or something else. BT 5 usually means BLE is supported. 
If not is this on the roadmap? If it is on roadmap when can we expect support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ff4a915-cffe-849d-800b-7f339ddb01c0
* Version Independent ID: 6f1c3aa3-8a90-ed5e-9d93-3f09680acaa8
* Content: [Connect to Bluetooth and USB-C devices](https://docs.microsoft.com/en-us/hololens/hololens-connect-devices)
* Content Source: [devices/hololens/hololens-connect-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/hololens-connect-devices.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by evmill** [comment]
https://docs.microsoft.com/hololens/hololens-faq#hololens-settings-lists-devices-as-available-but-the-devices-dont-work
"You can pair other Bluetooth HID and GATT devices together with your HoloLens. However, you may have to install corresponding companion apps from Microsoft Store to actually use the devices."
Is this helpful?

**Comment by Naphier** [comment]
Can you check to see if that's true with HoloLens 2? It seems that it cannot read GATT devices at all. We are writing a companion app.
Thanks!
