### ISSUE TITLE
Specify if Windows Defender Remote Credential Guard and Restricted Admin mode supported

### ISSUE THREAD

**Issue by SergGu** [MicrosoftDocs/windows-itpro-docs#6887]
Hello Microsoft Documentation Team,

It would be good if there is an explicit reference for support or lack of support for **Windows Defender Remote Credential Guard** and **Restricted Admin mode** in Hybrid joined machines.
For more information about RDP hardening features please refer here - https://docs.microsoft.com/en-gb/windows/security/identity-protection/remote-credential-guard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10) - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @SergGu - Thank you for your query. Remote Credential Guard is supported in the Azure AD joined machine. Please see https://docs.microsoft.com/en-us/windows/security/identity-protection/remote-credential-guard#considerations-when-using-windows-defender-remote-credential-guard

This current document is already linked with the Remote Credential Guard document and I feel there is no further input required on this document.

If you still feel there is anything that needs to be added in the document. Please do let me know.

Thanks.
Imran.
