### ISSUE TITLE
Outdated updates

### ISSUE THREAD

**Issue by AndyH16** [MicrosoftDocs/windows-itpro-docs#689]
How often are these MSI files being updated? I'm trying to make it easier for our users to update their Surface devices via System Center.

In particular the Surface Pro (Model 1796), this has a few recent updates posted for February and March yet the MSI file date remains from January 2018 and I think the drivers/firmware contained within the download are actually from an October 2017 release.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586d1246-6e18-b33c-2382-52a53bb392f5
* Version Independent ID: 0ec4aa1e-aac0-98dd-0a47-83e93d854086
* Content: [Download the latest firmware and drivers for Surface devices (Surface)](https://docs.microsoft.com/en-us/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices)
* Content Source: [devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md)
* Service: **unspecified**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
The MSI files are typically released at the same time or shortly following the release of driver and firmware updates to Windows Update, however there are exceptions. The drivers released February 13th to Windows Update were released to Windows Update only and were not made available via MSI. The drivers released March 15th will be made available via MSI, including the improvements made in the February 13th drivers, quite soon. The delay in the publication of these updates to MSI when compared to previous MSIs is related to a new requirement specific to this release which will be documented when we publish the MSI. The best way to keep up-to-date with the latest releases for Surface, either to Windows Update or the Microsoft Download Center, is to subscribe to the Surface Blog for IT Pros (https://blogs.technet.microsoft.com/surface/), where each new update is announced along with details of its content and improvements.

**Comment by AndyH16** [comment]
Thanks for the response, I can now see an update has been posted on 13th.
