### ISSUE TITLE
Correction to the Document

### ISSUE THREAD

**Issue by jonathan-mckinney** [MicrosoftDocs/windows-itpro-docs#6892]
**In the above note it reads:**

Currently, the RestrictedGroups/ConfigureGroupMembership policy does not have a MemberOf functionality. However, you can add a local group as a member to another local group by using the member portion, as shown in the above example.

But this is not true, you cannot add a local group to a local group. If you try, you receive the following error:

`MDM PolicyManager: Merge of policy did not complete successfully, Policy: (ConfigureGroupMembership), Area: (RestrictedGroups), Result:(0x8007056C) **A new member could not be added to a local group because the member has the wrong account type...**`

#### Document Details`

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0c28c15-f0be-d732-4d9e-cf5df5e64e8b
* Version Independent ID: 17eba45f-d200-e656-42b9-e1a512931eea
* Content: [Policy CSP - RestrictedGroups - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-restrictedgroups)
* Content Source: [windows/client-management/mdm/policy-csp-restrictedgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-restrictedgroups.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Checked,  local group cannot be added to a local group.
I will create a PR to correct this info.
Thank you
