### ISSUE TITLE
The link to submission history no longer work

### ISSUE THREAD

**Issue by yaronelh** [MicrosoftDocs/windows-itpro-docs#6897]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c18d83a-e2fe-3652-4e52-f580c8c3397a
* Version Independent ID: 2ef02e21-d2eb-78e2-6819-8330a5fce69e
* Content: [Submit files for analysis by Microsoft - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/submission-guide)
* Content Source: [windows/security/threat-protection/intelligence/submission-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/submission-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by illfated** [comment]
Looks like the link is non-localizable and needs to be specified as /en-us/ to work.
- https://www.microsoft.com/en-us/wdsi/filesubmission

The link above works for me, as long as I am signed in with a personal MS account.

@denisebmsft / @levinec : Would you like me to open a PR to add the /en-us/ part, or do you prefer to write a direct commit to the page?

**Comment by levinec** [comment]
@illfated hold off on this for now, because we aren't supposed to be using language tags. I've opened up a bug with engineering.

**Comment by illfated** [comment]
Thanks, I was a bit distracted to see that the link did not work without /en-us/, especially for this new material. I have seen that some new pages concerning MDATP, especially the promotion-based pages, cab happen to be /en-us/ only, at least in the beginning. Thank you for clearing up that uncertainty.

**Comment by levinec** [comment]
@yaronelh @illfated the engineering fix was deployed and the issue has now been resolved! The link works without the language tag.
