### ISSUE TITLE
Using operating system build number is not a good way to build a Windows 10 collection. Build 10240 is Windows 10 1507.

### ISSUE THREAD

**Issue by kimoppalfens** [MicrosoftDocs/windows-itpro-docs#6898]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08d16473-db61-23bd-7201-f5d7d6a56cc8
* Version Independent ID: 468238c8-8fb4-3dff-3485-07daab0c7833
* Content: [Onboard to the Microsoft Defender ATP service - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/onboarding)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/onboarding.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/onboarding.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by MaratMussabekov** [comment]
Hello @kimoppalfens ,
could you please clarify why it is not a good way?
Onboarding using configuration manager is supported since Windows 10 1607, so you can create a collection which includes all versions starting with 14393 (which is 1607), as it is described in the article.
Seems pretty good way for me.
Thank you

**Comment by kimoppalfens** [comment]
IIRC, back when I wrote my remark the page said to create a collection for the build version to be equal to 14393, not greater than. As a result now uptodate devices would enroll.

**Comment by MaratMussabekov** [comment]
oh, ok, I see now)
Dear @nam31 , I believe the issue could be closed.
Thank you
