### ISSUE TITLE
Missing Products in Licensing requirements?

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/windows-itpro-docs#6899]
I think the following Products are missing under licensing requirements:
- Microsoft Defender Advanced Threat Protection
- Microsoft Defender Advanced Threat Protection for Servers

Source: http://www.microsoftvolumelicensing.com/Downloader.aspx?documenttype=PT&lang=English

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by nam31** [comment]
It was fixed by https://github.com/MicrosoftDocs/windows-itpro-docs/commit/596578fa97fe9b562ee7c0e979a4e3283fdc064a#diff-6701b7a2e1253d31a8b2d4eae1e26628, and I think that the issue could be closed
