### ISSUE TITLE
SCCM / BranchCache / Windows 10 Pro vs Enterprise

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/windows-itpro-docs#690]
Hello,
Can you please confirm if SCCM's use of BranchCache requires Windows 10 clients to be running Enterprise, or if Pro will suffice.  I'm particularly referring to the comparison table for Windows 10 Pro|Enterprise|Education where BranchCache is shown to not be included for Pro - http://wincom.blob.core.windows.net/documents/Win10CompareTable_FY17.pdf

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4cf9245-7575-5c20-2697-3e9009341587
* Version Independent ID: bd86b3cd-f516-05fd-42b6-d4821e12079c
* Content: [Configure BranchCache for Windows 10 updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-branchcache)
* Content Source: [windows/deployment/update/waas-branchcache.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-branchcache.md)
* Service: **unspecified**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by okieselbach** [comment]
Hi,
BranchCache is available for Windows 10 Pro as a client component but provides only BranchCache Bits functionality. Windows 10 Enterprise does provide the full functional set of HTTP, SMB and BITS functionality.
See section "Operating systems for BranchCache client computer functionality" here:
https://docs.microsoft.com/en-us/windows-server/networking/branchcache/branchcache

**Comment by jrochet** [comment]
Thank you.  If you could please confirm, it would be great - does this paragraph (from the page you linked) confirm that SCCM uses BranchCache BITS functionality?:
"Application servers
Supported application servers include computers that are running Windows Server 2016, Windows Server 2012 R2, Windows Server 2012, or Windows Server 2008 R2 with Background Intelligent Transfer Service (BITS) installed and enabled.

In addition, the application server must have the BranchCache feature installed. As examples of application servers, you can deploy Microsoft Windows Server Update Services (WSUS) and Microsoft System Center Configuration Manager Branch Distribution Point servers as BranchCache content servers."

I believe this is the case but just in case I've misinterpreted the info...

**Comment by DaniHalfin** [comment]
@jaimeo \ @greg-lindsay - can you assist ?

**Comment by DaniHalfin** [comment]
@shortpatti can you please reassign to @jaimeo and @greg-lindsay ?

**Comment by JeremyTBradshaw** [comment]
In case you guys would like to close this instead, I'm onboard for that.  I think my own interest is more in the delivery optimization features than BITS capabilities for the purpose of SCCM management/deployment.  Thanks for the original answer and no worries about the rest.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
