### ISSUE TITLE
core Isolation section of Windows 10 Home Edition

### ISSUE THREAD

**Issue by sanjmishra** [MicrosoftDocs/windows-itpro-docs#6900]
This is about "**Core Isolation Section**" of " **Windows 10 Home Edition** " **Windows Security** section under setting.
There is an option there which provides _Memory Integrity on/off switch_. This when switched on in my systems prevented the **VMware Workstation** from launching as the Hyper-V was not there in my system. VMware Workstation was searching for **Hyper-V switch** to be in the ON state which do not exist under "**Windows 10 Home Edition**". Consequently my suggestion is to keep this disabled and provide the message that this is not available under Home Edition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f784502-84dc-1122-eab4-1eeeb08da046
* Version Independent ID: 21f210a7-4c38-8f62-0226-121562617fef
* Content: [Memory integrity - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/memory-integrity)
* Content Source: [windows/security/threat-protection/device-guard/memory-integrity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/device-guard/memory-integrity.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Hi @sanjmishra, it sounds like this is more of an issue about the product and this option showing up in Windows 10 Home, not an issue with the documentation. 

To make sure your feedback reaches the best people to help you, please send it to the Feedback hub: https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app
