### ISSUE TITLE
Save people hassle by including Provider ID

### ISSUE THREAD

**Issue by cmcapellan** [MicrosoftDocs/windows-itpro-docs#6901]
Since many of us are probably using Intune, rather than making us hunt for it, it would be helpful to include directly this section for _Provider/ProviderID/CommercialID_ from :

https://docs.microsoft.com/en-us/windows/client-management/mdm/dmclient-csp

Provider/ProviderID
Required. This node contains the URI-encoded value of the bootstrapped device management account’s Provider ID. Scope is dynamic. This value is set and controlled by the MDM server. As a best practice, use text that doesn’t require XML/URI escaping.

__For Intune, use MS DM Server for Windows desktop__ or SCConfigMgr for Windows mobile for the ProviderID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37a5ef77-5d80-ce40-7243-c96f708e907c
* Version Independent ID: 3e24d136-6af4-2531-31fd-feac09f37901
* Content: [Manually configuring devices for Update Compliance - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-configuration-manual)
* Content Source: [windows/deployment/update/update-compliance-configuration-manual.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-configuration-manual.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by lindspea** [comment]
@cmcapellan thank you for reaching out and helping improve MS Docs. Just for clarification are you suggesting adding the link you provided to this article?

**Comment by cmcapellan** [comment]
Generally speaking, I understand you are writing these docs to be MDM vendor agnostic.  But, I have to think a majority of the people looking at this are using Intune as their MDM, therefore, wherever possible directly providing or linking to the correct Intune setting will save people a lot of time.

Here, you can't implement these instructions without knowing what to use for `ProviderID`. The correct value is on the doc I link to, but a simple sentence in this doc like "If using Intune, _ProviderID_ should be `MS DM Server`, otherwise check with your MDM vendor" would save people a lot of time!
