### ISSUE TITLE
CSP Policy Values Not Correct!!??

### ISSUE THREAD

**Issue by cmcapellan** [MicrosoftDocs/windows-itpro-docs#6903]
Trying to use this page to create OMA-URI policies in Intune. For example, I am trying to add a policy for:

./Device/Vendor/MSFT/Policy/Config/System/AllowTelemetry

The documentation says for Win 10 the correct values are:

> 0 – Security. Information that is required to help keep Windows more secure, including data about the Connected User Experience and Telemetry component settings, the Malicious Software Removal Tool, and Windows Defender. Note: This value is only applicable to Windows 10 Enterprise, Windows 10 Education, Windows 10 Mobile Enterprise, Windows 10 IoT Core (IoT Core), and Windows Server 2016. Using this setting on other devices is equivalent to setting the value of 1.
> 1 – Basic. Basic device info, including: quality-related data, app compatibility, app usage data, and data from the Security level.
> 2 – Enhanced. Additional insights, including: how Windows, Windows Server, System Center, and apps are used, how they perform, advanced reliability data, and data from both the Basic and the Security levels.
> 3 – Full. All data necessary to identify and help to fix problems, plus data from the Security, Basic, and Enhanced levels.

Reading this, a reasonable reader would conclude the valid entries are "0 – Security", "1 – Basic", "2 – Enhanced", and "3 – Full" and attempt to add these values as strings in the Intune Policy. However, this does *NOT* work, the CORRECT values for this policy are the integers 0, 1, 2, 3.

Can you please review these policy values with the MDM and Intune teams to get this right so we are not dealing with incorrect docs please?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c833e5b-0fcf-2ace-a90a-3270286d23a9
* Version Independent ID: 64afbc38-e7cc-fc14-9d57-1cd119b2395d
* Content: [Policy CSP - System - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-system#system-allowtelemetry)
* Content Source: [windows/client-management/mdm/policy-csp-system.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-system.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Closing via #7091
