### ISSUE TITLE
Clarification on subscription licence verification

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/windows-itpro-docs#6908]
On point "Figure 9 - Windows 10 Enterprise subscription in Settings"

Should there be shown a "Windows(R), Professional edition" after Windows 10 E3 or E5 license activation? Could that be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ecbc1-9c02-5681-7214-356be22ac7e8
* Version Independent ID: 73af82f6-079b-6c37-55c4-cb59e921457a
* Content: [Deploy Windows 10 Enterprise licenses - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-enterprise-licenses)
* Content Source: [windows/deployment/deploy-enterprise-licenses.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-enterprise-licenses.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
No, when a user that is enabled for Enterprise signs in on Professional, the Professional will become Enterprise.  This is what is shown in figure 9.

**Comment by weyCC81** [comment]
The description tells otherwise:

"If you use slmgr /dli or /dlv commands to retrieve the activation information for the Windows 10 E3 or E5 license, the license information displayed will be the following: Name: Windows(R), **Professional edition** Description: Windows(R) Operating System, RETAIL channel Partial Product Key: 3V66T"
