### ISSUE TITLE
Additional file rule examples

### ISSUE THREAD

**Issue by ssccaavvookk** [MicrosoftDocs/windows-itpro-docs#6909]
Can additional file rule examples be added in addition to the file path rules? E.g. in step 7 where it says "If appropriate, add additional signer or file rules..." 

I have a Sha256Hash for a file that I want to allow to be executed that I collected from the Event Viewer. How do add a rule specifically for that hash value? What about a publisher? The only way that's clear from this documentation is to create a new policy that scans the path they are in and merging that policy with the main policy. But step 7 gives the impression that there is a more direct way similar to the FilePathRules in step 6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebdf50c3-2221-5d9e-6823-7827e5c7de47
* Version Independent ID: 845470fb-17a6-1fd5-d79a-7b83950b9527
* Content: [Create a WDAC policy for lightly-managed devices (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/create-wdac-policy-for-lightly-managed-devices)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/create-wdac-policy-for-lightly-managed-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/create-wdac-policy-for-lightly-managed-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by lindspea** [comment]
@ssccaavvookk thank you for reaching out. Please have a look at this link and let me know if it helps. I can add it to the article in question if you think it will help other users - https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create

**Comment by ssccaavvookk** [comment]
> @ssccaavvookk thank you for reaching out. Please have a look at this link and let me know if it helps. I can add it to the article in question if you think it will help other users - https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create

@lindspea It is helpful that it contains the list of types of supported rules, for Level and Fallback purposes, but not how to add a particular hash or publisher to the policy.  [New-CIPolicyRule](https://docs.microsoft.com/en-us/powershell/module/configci/new-cipolicyrule?view=win10-ps) powershell cmdlet has the -FilePathRule parameter that is used in this example document, and based on the language "if appropriate, add additional signer or file rules" that those rules listed in the document you linked could similarly be added by commands such as New-CIPolicyRule -HashRule "<hash>" or New-CIPolicyRule -PublisherRule "<publisher info>". But this is not the case. 

From what I've learned, you can only add other types of rules by running a new scan and merging, which requires a process more described in the [fixed-workload example](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/create-initial-default-policy). Or in my case, the [Audit WDAC Policies](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/audit-windows-defender-application-control-policies) document described what I needed.

But the language "If appropriate, add additional signer or file rules to further customize the policy for your organization" is misleading, as the FilePath rule type is unique among the 12 types of rules, and it gives the impression that the previous step that described how to add FilePath rules is a method for additional types of rules, which it is not.

**Comment by lindspea** [comment]
@jsuther1974 please can you assist here.

**Comment by lindspea** [comment]
@ssccaavvookk I found another link - please let me know what you think - https://docs.microsoft.com/powershell/module/applocker/new-applockerpolicy?view=win10-ps

**Comment by nam31** [comment]
@ssccaavvookk We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
