### ISSUE TITLE
Windows-to-Go can be still created with Rufus

### ISSUE THREAD

**Issue by cryptoAlgorithm** [MicrosoftDocs/windows-itpro-docs#6912]
[Enter feedback here]
This page is a little misleading, as the Rufus ISO creation application can still create a Windows-To-Go drive on many different USB drives, external hard disks, and SSDs. I think it is worth mentioning on the page that there is an alternative method of creating a Windows-to-Go drive with Rufus and a link to a suitable Rufus instruction page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93868b54-1342-6a97-ea84-ab75066c837b
* Version Independent ID: 8ee0f61c-67cd-9df6-a8e9-b854d8134587
* Content: [Windows To Go feature overview (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-to-go-overview)
* Content Source: [windows/deployment/planning/windows-to-go-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/planning/windows-to-go-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@cryptoAlgorithm . Yes I used rufus software, for creating windows to go in normal pendrive 64gb.

**Comment by VLG17** [comment]
@cryptoAlgorithm Thank you for raising this point. Although it's a valid point, best practices mandate not to link 3rd party references.
