### ISSUE TITLE
File's classification exists on the device's cache prior to the allow or block action

### ISSUE THREAD

**Issue by muellni6** [MicrosoftDocs/windows-itpro-docs#6913]
Can you clarify what is meant with:
"The allow or block function cannot be done on files if the file's classification exists on the device's cache prior to the allow or block action" in the important section.

As far as I understand from the sentence is, that if a file already run on a system it can not be blocked in the future via indicators. So only system, where the file has never run before, are protected.

Also important for investigation:
Which cache is meant here? Can the cache be cleared? How do i know that the file is already in the cache?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50f2be10-41a0-67ae-222b-1b073bef537b
* Version Independent ID: 3f186b13-aad0-4ba4-e239-d9bb24ff2ebe
* Content: [Manage indicators - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/manage-indicators)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/manage-indicators.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/manage-indicators.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by VLG17** [comment]
@muellni6 I think your understanding is correct. If Windows Defender malware engine already classified a file as malicious/safe you won't be able to use the allow or block function of the indicator.

My understanding is that the device cache refers to Windows Defender Cache. You have a few options here to check it / clear it:

1. Task Scheduler (Local) - Task Scheduler Library - Microsoft - Windows - Windows Defender -> you will see some relevant tasks:

- Windows Defender Cache Maintenance -> running this will clear the Cache.
- Windows Defender Cleanup
- Windows Defender Verification

If you look under the Actions tab, you will see that it runs cmdlet based on mpcmdrun.exe -> more details [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/command-line-arguments-microsoft-defender-antivirus)

If you want to check what's in the Cache, you could have a look under: 

"C:\ProgramData\Microsoft\Windows Defender\Scans\History"
"C:\ProgramData\Microsoft\Windows Defender\Scans\Scans\History"

I don't see any results, but maybe you will. Hope this helps.
