### ISSUE TITLE
Has Device Guard been renamed?

### ISSUE THREAD

**Issue by santoshseth** [MicrosoftDocs/windows-itpro-docs#6915]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19c8d2d2-3d96-c635-76da-c3b43afc1b45
* Version Independent ID: d7d79add-eadc-2e11-4bf7-eac48e4975d8
* Content: [WDAC and virtualization-based code integrity (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/introduction-to-device-guard-virtualization-based-security-and-windows-defender-application-control?redirectedfrom=MSDN)
* Content Source: [windows/security/threat-protection/device-guard/introduction-to-device-guard-virtualization-based-security-and-windows-defender-application-control.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/device-guard/introduction-to-device-guard-virtualization-based-security-and-windows-defender-application-control.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@santoshseth . No its not renamed.windows defender antivirus has renamed to Microsoft defender Antivirus.
