### ISSUE TITLE
Related Topics Links on Attack Surface Reduction page

### ISSUE THREAD

**Issue by dominique97** [MicrosoftDocs/windows-itpro-docs#6922]
[Enter feedback here]
The first bullet in related topics for this page is "Attack surface reduction FAQ" which is a link back to the page itself (https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction)

not sure if there is an FAQ page or not - but if there is, this link is not correct.

the last related topic is "Compatibility of Microsoft Defender with other antivirus/antimalware" - I am not sure how/why this is related.  Nothing in the article references antivirus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d747289-63b2-f71a-b40c-31b52982215c
* Version Independent ID: b52f6593-03f2-aa57-ec0e-eaef560dcaf0
* Content: [Use attack surface reduction rules to prevent malware infection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
PR created to correct the link URL: #6935

**Comment by e0i** [comment]
Closing via #6935. Thank you for your contributions, @illfated and @RAJU2529. Much appreciated.
