### ISSUE TITLE
Cortana voice update

### ISSUE THREAD

**Issue by tmlyon** [MicrosoftDocs/windows-itpro-docs#6924]
As of the Vb update, Cortana no longer supports restarting the device, so this should be updated to the shell speech command "Restart device." Also, the section headers should be simplified from "by using" to just "using."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd4de184-bdeb-2611-8d75-28376e30b0fc
* Version Independent ID: 7b330f9a-d1c0-72f9-0d00-d7fac13e7e00
* Content: [Restart, reset, or recover HoloLens](https://review.docs.microsoft.com/en-us/hololens/hololens-recovery?branch=pr-en-us-2894)
* Content Source: [devices/hololens/hololens-recovery.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/hololens-recovery.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by VLG17** [comment]
@tmlyon Which update are you refering to with "Vb update"? Looking at the article, i can see a note under the Restart section mentioning that:

> Cortana is not available on all devices. Cortana is available to all HoloLens (1st Gen) devices. Cortana is available on HoloLens 2 devices on a build prior to the Windows Holograpic, Version 2004 update.

Does this not address the issue?

**Comment by e0i** [comment]
@tmlyon Please let us know whether the comment above answers your query. Thank you.

**Comment by tmlyon** [comment]
Sorry, as of the 2004 update, this voice command is no longer supported via Cortana but is via system voice commands (no "Hey Cortana" required).  It appears this page has already been changed and this comment is no longer relevant though.
