### ISSUE TITLE
Non-persistent VDI Gold Image Offboarding Steps

### ISSUE THREAD

**Issue by andshrew** [MicrosoftDocs/windows-itpro-docs#6925]
This document includes a procedure for **_"Updating non-persistent virtual desktop infrastructure (VDI) images"_**, and having recently implemented ATP on non-persistent VDI I think there are two steps missing from the procedure.

In addition the document would benefit from clarification as to whether or not the VDI Gold Image should even be onboarded in the ATP in the first place. The procedure currently implies that the Gold Image has previously been onboarded... **_"After booting the master image for online servicing or patching, run an offboarding script to turn off the Microsoft Defender ATP sensor."_**

### **Missing Procedure Step 1**
[After the existing Step 1 of running the offboarding script](https://github.com/MicrosoftDocs/windows-itpro-docs/blame/ae1ced0fb676eac8a43ccd78ae95ee20a87e2a40/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi.md#L123).

Once the offboarding script has successfully run the following registry value remains.
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Advanced Threat Protection\senseGuid`

While this value remains in the Gold Image, once it has been re-sealed for use with non-persistent VDI they will be unable to run the [onboarding script "Onboard-NonPersistentMachine.ps1"](https://github.com/MicrosoftDocs/windows-itpro-docs/blame/ae1ced0fb676eac8a43ccd78ae95ee20a87e2a40/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi.md#L73) because the script will exit early reporting that the `senseGuid` value already exists. The result is that the VDI is not onboarded in to ATP.

**Suggested solution:** Add an additional step to this procedure to delete `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Advanced Threat Protection\senseGuid` from the Gold Image after it has been offboarded from ATP.

### **Missing Procedure Step 2**
This issue may be dependant on your VDI solution. I had this occur with VMware Horizon using Instant Clones.

[After the existing Step 1 of running the offboarding script](https://github.com/MicrosoftDocs/windows-itpro-docs/blame/ae1ced0fb676eac8a43ccd78ae95ee20a87e2a40/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi.md#L123).

With the Gold Image offboarded a new registry key was created. In my case it was named as follows (unknown if it would be the exact same name for everyone):
`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Advanced Threat Protection\696C1FA1-4030-4FA4-8713-FAF9B2EA7C0A`

When the Gold Image is sealed and prepared for use by VMware Horizon for an Instant Clone VDI this registry information appears to be captured in to a Local Group Policy object on the VDI. The result of which is:

- Non-persistent VDI boots up, and onboards itself in to ATP. This process deletes the above registry key and the Sense service reports successful onboarding.
- Group Policy on the VDI refreshes, and the above registry key is re-created (as a result of it being captured in a Local Group Policy object by the VMware image preparation process).
- Sense service detects the creation of this registry key and reports that the VDI has been successfully **offboarded**.

The result is that the VDI is only temporarily onboarded in to ATP.

**Suggested solution:** Add an additional step to this procedure to delete `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Advanced Threat Protection\696C1FA1-4030-4FA4-8713-FAF9B2EA7C0A` from the Gold Image after it has been offboarded from ATP.

Thanks

Andrew

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804f2883-5de4-9d54-d0b4-e64b04984aa8
* Version Independent ID: 0ab9ee92-c5e1-0455-92ba-ed07ed7bd140
* Content: [Onboard non-persistent virtual desktop infrastructure (VDI) machines - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by VLG17** [comment]
@andshrew I think the answer to "clarification as to whether or not the VDI Gold Image should even be onboarded in the ATP in the first place" and "Missing Procedure Step 1" is provided within [this blog post](https://techcommunity.microsoft.com/t5/microsoft-defender-atp/onboarding-and-servicing-non-persistent-vdi-machines-with/ba-p/1360721), under the section **Option 1 – Re-use the existing master**:

> Remember that you should never onboard the VDI master  -> which leads to exactly what you're seeing. 


Regarding your second point "Missing Procedure Step 1", my research confirms the fact that it's specific to using VMware Horizon using Instant Clones. My recommendation is to [reach out to support](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-support) (both Microsoft and VMWare) and check with them this specific scenario and it's consequences. 

If support confirms it's a general issue, we will be able to amend the article.

**Comment by andshrew** [comment]
Hi @VLG17 , thanks for your reply.

I think that blog post clarifies the issues I was seeing; in short don't onboard the gold image when you initially create it but if you later service the gold image using option 1 then it may onboard itself when you next boot it up. It looks like this article has now been updated to add in deleting the `senseGuid` registry entry when you service the image so that looks good now.

I agree with you the second issue does seem to be specific to VMware Instant Clones. So I can certainly put the question to their support. Not sure if you want to close this issue for now as the main issue around deleting the `senseGuid` is resolved now.

**Comment by e0i** [comment]
Closing as resolved. Thank you for the discussion.
