### ISSUE TITLE
iOS and Android support

### ISSUE THREAD

**Issue by wahidsaleemi** [MicrosoftDocs/windows-itpro-docs#6929]
According to https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/whats-new-in-microsoft-defender-atp, iOS and Android are supported but this page does not list them and doesn't provide a link on how to onboard them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by VLG17** [comment]
@wahidsaleemi In the [referenced link](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/whats-new-in-microsoft-defender-atp), the "Support for iOS and Android devices" section is linked to [this article](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-non-windows#turn-on-third-party-integration), which talks about onboarding non-Windows devices.

Regarding Android and iOS:

Microsoft Defender Advanced Threat Protection for Android is in Public Preview: more details [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-android)

Microsoft Defender Advanced Threat Protection for iOS: details coming out later this year

**Comment by wahidsaleemi** [comment]
To clarify, I'm requesting that the page: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements include Android and iOS under "Hardware and Software Requirements --> Other supported operating systems."

**Comment by mjcaparas** [comment]
Thanks for the feedback. 
Updating this topic to include Android.
