### ISSUE TITLE
MDT links do not mention Win 10 support

### ISSUE THREAD

**Issue by theboymango** [MicrosoftDocs/windows-itpro-docs#693]
The links about referring to MDT refer to a version of MDT which, apparently, doesn't support Windows 10 in the What's new and release information sections of the linked resource.
https://docs.microsoft.com/en-us/sccm/mdt/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c72fef0-0e1e-b3b1-2ca2-27df7e2c7f1f
* Version Independent ID: 117497b2-a7c6-45ba-d101-31e1e432dafa
* Content: [Deploy Windows 10 with the Microsoft Deployment Toolkit (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-windows-10-with-the-microsoft-deployment-toolkit#feedback)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-windows-10-with-the-microsoft-deployment-toolkit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/deploy-windows-10-with-the-microsoft-deployment-toolkit.md)
* Service: **unspecified**
* GitHub Login: @mtniehaus
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by lindspea** [comment]
@theboymango Thank you for reaching out.  I'll have a look and get it fixed soonest.

**Comment by mypil** [comment]
@theboymango - please assist to give updates on the clarification question from lindspea? Thank you.

**Comment by mypil** [comment]
@theboymango - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
