### ISSUE TITLE
License Requirements Microsoft Defender ATP

### ISSUE THREAD

**Issue by supercrisz** [MicrosoftDocs/windows-itpro-docs#6933]
on this page, it stated that you need Windows E5 license. But MIcrosoft Defender ATP is also as standalone product available since March 2020. So the need for WIndows E5 license is incorrect in my opinion. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by VLG17** [comment]
@supercrisz According to the [Microsoft Licencing Terms](https://www.microsoft.com/en-us/licensing/product-licensing/products) you can acquire MD ATP under the following licencing programs: EA/EAS, CSP and EES.

![image](https://user-images.githubusercontent.com/41186174/87280517-e8832b80-c4fa-11ea-8aec-d444fbe4fafd.png)

![image](https://user-images.githubusercontent.com/41186174/87280734-25e7b900-c4fb-11ea-9bf4-bbd5fe18ee75.png)

For server licencing, there are a few requirements to keep in mine, when purchasing the standalone licences:

> 2.1 Eligibility to acquire Microsoft Defender Advanced Threat Protection for Servers

> Customers with a combined minimum of 50 licenses for one or more of the following may acquire Server SLs for Microsoft Defender Advanced Threat Protection for Servers (one per covered Server OSE): Microsoft Defender Advanced Threat Protection, Windows E5/A5, Microsoft 365 E5/A5 and Microsoft 365 E5 Security User SLs.

In my opinion the standalone licence option (MD ATP SL) is covered with the note already present in the [referenced article](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements):

![image](https://user-images.githubusercontent.com/41186174/87282332-d6a28800-c4fc-11ea-89f2-f0e81da3e5e3.png)

**Comment by Lumute** [comment]
Does the 50 minimum license requirement for the Server version includes licenses of the Sever version itself?

We run a cloud SaaS platform with a lot more than 50 servers and want to use Defender ATP on it. We do not need any other license apart from Server ones. If we place an order for lets say 150 licenses of "Microsoft Defender Advanced Threat Protection for Servers", does this order by itself cover the requirement?

**Comment by VLG17** [comment]
> Does the 50 minimum license requirement for the Server version includes licenses of the Sever version itself?
> 
> If we place an order for lets say 150 licenses of "Microsoft Defender Advanced Threat Protection for Servers", does this order by itself cover the requirement?

@Lumute I think the answer to your questions is no, although i am not a licencing specialist, and i would advise you to discuss and confirm this over the channel used to purchase the licences.

My understanding is that **extra** to the Defender ATP for Server licences you also need to have a combined minimum of 50 licences for one of the licences described in the note.

**Comment by nam31** [comment]
@Lumute Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
