### ISSUE TITLE
Endpoint Protection for Microsoft Intune is on the deprecated portal

### ISSUE THREAD

**Issue by ncheymol** [MicrosoftDocs/windows-itpro-docs#6934]
You have deprecated a great feature and the only way to have a view on Defender updates and events is to go to the deprecated Intune Silverlight portal for cloud only customers ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8062ff-27b0-40ae-92b5-2f1dc851ad54
* Version Independent ID: 5c52fdc9-18e1-56cd-afe3-86db6ca4bbb0
* Content: [Monitor Windows Updates and Microsoft Defender AV with Update Compliance (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-monitor)
* Content Source: [windows/deployment/update/update-compliance-monitor.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-monitor.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Thanks for your feedback, though this channel is for issues with the actual documentation. If you'd like to share your thoughts on the product or feature itself, by all means please do so at Feedback Hub. That will come to the attention of the feature owners much more efficiently.

@chinglis for awareness.

**Comment by ncheymol** [comment]
The documentation isn't clear about the fact that it is the classic portal. I don't think that classic portal is part of Microsoft Endpoint Manager as MEM is ConfigMgr + MDM and Windows isn't managed via MDM on that version of Intune

**Comment by jaimeo** [comment]
Ah OK, fair enough. @cinglis-msft can you advise?

**Comment by cinglis-msft** [comment]
I updated the references to point to MEM and Defender ATP.

**Comment by e0i** [comment]
Closing via the above response. Thank you for the update.
