### ISSUE TITLE
Example VPN config uses  MachineMethod Eap which other page says isn't valid value

### ISSUE THREAD

**Issue by corruptmem** [MicrosoftDocs/windows-itpro-docs#6936]
The page here: https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-profile-options

Has the sample authentication:

````<MachineMethod>Eap</MachineMethod>  ````

However, on the document describing the valid parameters here: https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp?redirectedfrom=MSDN

It describes the MachineMethod parameter as only accepting the value Certificate:

> VPNv2/ProfileName/NativeProfile/Authentication/MachineMethod
> This is only supported in IKEv2.
> 
> This value can be one of the following:
> 
> * Certificate
> 
> Value type is chr. Supported operations include Get, Add, Replace, and Delete.

Not sure I misunderstand or if this is inconsistent?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79add4e0-6997-5b15-542c-be3f1c2b1baf
* Version Independent ID: 47bd5f53-cd36-3205-42b1-6d99c68e9b39
* Content: [VPN profile options (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-profile-options)
* Content Source: [windows/security/identity-protection/vpn/vpn-profile-options.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/vpn/vpn-profile-options.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@corruptmem You are correct, the value for <MachineMethod>..........</MachineMethod>  should be Certificate.

Keeping in mind the referenced article describes a Sample EAP profile, i think it should look like (i'll try to amend that):

 
    <Authentication>  
      <UserMethod>Eap</UserMethod>   
      <Eap>  
       <Configuration>

**Comment by e0i** [comment]
@corruptmem 

With the help of your feedback, the content has been updated with relevant changes accordingly via #7167. Thanks.
