### ISSUE TITLE
Reset to factory settings

### ISSUE THREAD

**Issue by dariminhas** [MicrosoftDocs/windows-itpro-docs#6939]
In section "Reset to factory settings" first point needs to be updated. It mentions "select Update > Reset". In HoloLens 2 devices (OS build 10.0.19041), Reset Device option sits under Update & Security > Recovery > Reset Device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd4de184-bdeb-2611-8d75-28376e30b0fc
* Version Independent ID: 7b330f9a-d1c0-72f9-0d00-d7fac13e7e00
* Content: [Restart, reset, or recover HoloLens](https://docs.microsoft.com/en-us/hololens/hololens-recovery?source=docs)
* Content Source: [devices/hololens/hololens-recovery.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/hololens-recovery.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by VLG17** [comment]
@dariminhas The section you are refering to is in [the article](https://docs.microsoft.com/en-us/hololens/hololens1-recovery#reset-to-factory-settings) about HoloLens Gen 1, not Gen 2, as you can see if you look on the left side:

![image](https://user-images.githubusercontent.com/41186174/87527959-8a3e8000-c695-11ea-80e4-7b3260534f1c.png)

Please check [the article about HoloLens Gen 2](https://docs.microsoft.com/en-us/hololens/hololens-recovery) for the Gen 2 reset procedure.

**Comment by evmill** [comment]
HL1 recovery doc now states "Recovery" instead of "Reset".
