### ISSUE TITLE
Clarification needed "Prepare your organization for BitLocker: Planning and policies"

### ISSUE THREAD

**Issue by jecarlsen** [MicrosoftDocs/windows-itpro-docs#6944]
With the section: https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/prepare-your-organization-for-bitlocker-planning-and-policies#encryption-keys-and-authentication

In the paragraph, the statement says:
_**Encryption keys and authentication**
...
"... does not provide the pre-startup system integrity verification offered by BitLocker working with a TPM"_

Clarification needed on _"why not having a pre-start system integrity verification"_ is less secure that TPM. 
a) What does it entail "_Not having pre-startup system integrity verification_" as of risks? 
b) What does "pre-startup system integrity verification" provide?
This is to **understand the risk and controls needed** with Bitlocker to go vs TPM.

Perhaps a different article has an explanation? Perhaps you can make a link to this article?

**Comment by lindspea** [comment]
@jecarlsen thank you for reaching out. Please have a look at this link and let me know if it helps at all - https://docs.microsoft.com/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings#a-href-idbkmk-rec1achoose-how-bitlocker-protected-operating-system-drives-can-be-recovered

**Comment by nam31** [comment]
@jecarlsen We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.

Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.

Thank you for providing feedback.
