### ISSUE TITLE
Doc updates 

### ISSUE THREAD

**Issue by bledMS82** [MicrosoftDocs/windows-itpro-docs#6946]
Step 9 is not clear on the file naming convention and the example from the top should be listed in this step (MDATP_MDAV_Tray_and_AutoUpdate2.mobileconfig) , additionally all copy fields should remove the systems reply so that the field can be used to copy the cli directly without having to know what to remove as this may cause confusion , additional book should be shown with expected  outputs of cli . 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 369434e7-66ea-b756-fc21-0104b19a1cd9
* Version Independent ID: 06e0ba16-0dcf-a85c-7855-684892282e84
* Content: [Intune-based deployment for Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-install-with-intune)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-install-with-intune.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-install-with-intune.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@bledMS82 Keeping in mind the note at the top of the article, i think it's best to follow the new steps described [here](https://techcommunity.microsoft.com/t5/microsoft-endpoint-manager-blog/microsoft-endpoint-manager-simplifies-deployment-of-microsoft/ba-p/1322995)

> 
![image](https://user-images.githubusercontent.com/41186174/94453731-b3ad7900-01b9-11eb-9244-a970a315de85.png)
