### ISSUE TITLE
Clarification needed on requirements

### ISSUE THREAD

**Issue by skeeler** [MicrosoftDocs/windows-itpro-docs#6951]
The "Requirements" state that: "Your local PC (where you are connecting from) must be either Azure AD joined or Hybrid Azure AD joined".

Need clarification on the following: Does the local PC need to be Azure AD joined to the same Azure AD domain as the remote PC is joined to? The statement, as written, is ambiguous, and could be interpreted as local/remote may be joined to any Azure AD domain, i.e. not necessarily the same one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10) - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by lindspea** [comment]
@skeeler thank you for reaching out and helping improve MS Docs. Please see this tip regarding your request -  
"Tip - When you connect to the remote PC, enter your account name in this format: AzureAD UPN. The local PC must either be domain-joined or Azure AD-joined. The local PC and remote PC must be in the same Azure AD tenant." Let me know if you need further assistance.
