### ISSUE TITLE
Translations errors caused by missing code block

### ISSUE THREAD

**Issue by sebbu2** [MicrosoftDocs/windows-itpro-docs#6953]
Not all code is in quote/code block, hence it's translated by the translation system.

Especially the ACL strings gets translated wrongly, and make the command not work OR break the system, ie in french translation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
OK, I see. This is about the following section(s):

***

4. If this is your first attempt at resolving your Windows Update issues by using the steps in this article, go to step 5 without carrying out the steps in step 4. The steps in step 4 should only be performed at this point in the troubleshooting if you cannot resolve your Windows Update issues after following all steps but step 4. The steps in step 4 are also performed by the "Aggressive" mode of the Fix it Solution above.
   1. Rename the following folders to *.BAK:
      - %systemroot%\SoftwareDistribution\DataStore
      - %systemroot%\SoftwareDistribution\Download
      - %systemroot%\system32\catroot2

      To do this, type the following commands at a command prompt. Press ENTER after you type each command.
      - Ren %systemroot%\SoftwareDistribution\DataStore *.bak
      - Ren %systemroot%\SoftwareDistribution\Download *.bak
      - Ren %systemroot%\system32\catroot2 *.bak
   2. Reset the BITS service and the Windows Update service to the default security descriptor. To do this, type the following commands at a command prompt. Press ENTER after you type each command.
      - sc.exe sdset bits D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;AU)(A;;CCLCSWRPWPDTLOCRRC;;;PU)
      - sc.exe sdset wuauserv D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;AU)(A;;CCLCSWRPWPDTLOCRRC;;;PU)

***
Very well. I will open a PR to suggest encapsulating more text in MarkDown back ticks, especially the commands and explicit OS information.
