### ISSUE TITLE
Please clarify the Failed Status Values

### ISSUE THREAD

**Issue by PriyaKOMA** [MicrosoftDocs/windows-itpro-docs#6954]
FailedUpdates/Failed Update Guid/Status

Specifies the failed update status (for example, download, install).

Supported operation is Get.
The above status on querying gives 0,8 etc. Can you mention how these values map to install, download etc and the other possible values  

(admin edit: refresh metadata with latest)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85da8b6b-3138-1fe8-15b6-e3ab96c12efb
* Version Independent ID: 236d9dbb-f05e-b3fd-ee43-c2081b4f4300
* Content: [Update CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/update-csp)
* Content Source: [windows/client-management/mdm/update-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/update-csp.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by VLG17** [comment]
@PriyaKOMA could you please provide the output of your query cmd? I want to see the exact value and wording that you are getting.

**Comment by aczechowski** [comment]
Checking with PM to see if we can find more information on these values.
