### ISSUE TITLE
List of supported OSes is incorrect

### ISSUE THREAD

**Issue by artisticcheese** [MicrosoftDocs/windows-itpro-docs#696]
It's supported started with Vista, current documentation lists only Windows 10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5752fb34-9d01-a788-e397-2c17933257ee
* Version Independent ID: 8d01032c-c393-2add-deaf-837bfe219ca2
* Content: [Which editions of Windows support advanced audit policy configuration (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/which-editions-of-windows-support-advanced-audit-policy-configuration)
* Content Source: [windows/security/threat-protection/auditing/which-editions-of-windows-support-advanced-audit-policy-configuration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/which-editions-of-windows-support-advanced-audit-policy-configuration.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@artisticcheese thanks for the comment. I added this point to the opening sentence. The Applies to value at the top only lists Windows 10 because the library is intended for the current release only (although many topics do equally apply to previous versions).
