### ISSUE TITLE
Wildcard to match a partial folder name

### ISSUE THREAD

**Issue by SteveBurkettNZ** [MicrosoftDocs/windows-itpro-docs#6960]
Can you use the wildcard * in a partial folder name?

E.g. Wanting to exclude **C:\WindowsAzure\GuestAgent_2.7.41491.971_2020-05-19_190600\WaAppAgent.exe** but obviously that version number will be periodically changing.

Is an exclusion of **C:\WindowsAzure\GuestAgent_*\WaAppAgent.exe** valid?  This scenario isn't covered in the wildcard exclusion examples given.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c0eddd-98ca-1e7a-bddb-36c7037850fe
* Version Independent ID: 6afa98e8-a402-4ef9-2189-8ecc111c3dba
* Content: [Configure and validate exclusions based on extension, name, or location - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-extension-file-exclusions-microsoft-defender-antivirus#use-wildcards-in-the-file-name-and-folder-path-or-extension-exclusion-lists)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/configure-extension-file-exclusions-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/configure-extension-file-exclusions-microsoft-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by MaratMussabekov** [comment]
Hello @SteveBurkettNZ ,
no, * cannot be used to replace partial folder name, it could only replace the full name, so in your case it would be  C:\WindowsAzure\*\WaAppAgent.exe or just C:\WindowsAzure\*\
Thank you
