### ISSUE TITLE
Intune for Education subscriptions, which include all needed Azure AD and Intune features.

### ISSUE THREAD

**Issue by chiners68** [MicrosoftDocs/windows-itpro-docs#6963]
Intune for education does not seem to contain all Azure AD features required for Autopilot. I configured a school with user driven hybrid AD join devices. I had to add an azure AD premium P1 license otherwise the Hybrid Join in autopilot would not complete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aafc065-6ee6-e3cf-31ba-ab3dd277fb23
* Version Independent ID: 35d3102e-4ff7-9408-8dbd-513b7dfff5c0
* Content: [Windows Autopilot requirements - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-requirements#licensing-requirements)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/windows-autopilot-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Hi, I've checked with some experts and you shouldn't have run into this issue. Did you get any error messages or attempt to troubleshoot the enrollment process?

**Comment by chiners68** [comment]
Hi,
  Hybrid AD join would not complete and remained at pending until I assigned a Azure AD Premium P1 licenses. I raised a case as I was having a number of issues. See below

Alejandro (Microsoft)
Monday, June 8, 2020 9:43 AM GMT
Hello Mark,

I wanted to follow-up with you to make sure you had some necessary information.
For your reference, your ticket number is 20365622.
With regards to our phone conversation, we discussed


  *   having issues receiving policies and communicating with Intune through Hybrid autopilot.
  *   noticed that this devices had no MDM Intune, and was not registering properly on the Azure ad side.
  *   noticed that the only thing missing on the licensing side was the Premium P1 for azure.
  *   just to make sure to start fresh, we have to make sure of the following.
     *   remove from the following Intune - Azure ad devices - autopilot devices - onpremise since it was domain joined.
     *   once its removed from all of the above, restart the process by adding the device to autopilot with the csv.



Have a great day,

please be aware of my working hours below in case you need assistance on this ticket.




Alejandro
M365 Enterprise Technical Advisor
Working hours: Monday through Friday, 5AM-2PM (EST) (UTC-5)

Management Team Email: IntuneSupportMgmt@microsoft.com


[cid:file0_4811a588-c86f-46dc-a83c-4cbb4a10f3b4.png]

**Comment by greg-lindsay** [comment]
Thanks, please let me know the outcome of your case.

**Comment by greg-lindsay** [comment]
Something to be aware of here is that the device registration process is tied to AAD Connect and could take perhaps 30 minutes. Until that happens, you can’t get an Azure AD token, and without the Azure AD token it can’t authenticate to Intune.

It's possible that the AAD Connect process was slow and only completed after you added Azure AD premium.

**Comment by chiners68** [comment]
The case is closed.

Time was not an issue. We had devices left overnight an they remained pending.

Sent from my iPhone

On 15 Jun 2020, at 18:49, Greg Lindsay <notifications@github.com> wrote:

﻿

Something to be aware of here is that the device registration process is tied to AAD Connect and could take perhaps 30 minutes. Until that happens, you can’t get an Azure AD token, and without the Azure AD token it can’t authenticate to Intune.

It's possible that the AAD Connect process was slow and only completed after you added Azure AD premium.

**Comment by greg-lindsay** [comment]
You said the case is closed. What was the solution?

**Comment by chiners68** [comment]
To add the P1 license.

**Comment by greg-lindsay** [comment]
Hmm well this is a bit of a mystery then because the product team says that Intune for Education has all the necessary elements.
