### ISSUE TITLE
Download file fails

### ISSUE THREAD

**Issue by glennamaddy** [MicrosoftDocs/windows-itpro-docs#6965]
DownloadFile fails with 'unable to connect to remote server', there's nothing listening on port 80 on my device

**Comment by denisebmsft** [comment]
Hello @glennamaddy. Can you tell us to which article(s) your feedback applies? This will help us route this issue correctly.

**Comment by glennamaddy** [comment]
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/run-detection-test

**Comment by illfated** [comment]
Have you tried following the **Troubleshoot Microsoft Defender Advanced Threat Protection onboarding issues** checklist?
- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-onboarding

**Comment by mypil** [comment]
@glennamaddy - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @illfated so we will close this issue. If you still experience some technical issues, then it may be best to open a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products so they can help resolve your issue.



Thank you for your contribution to make the docs better! Much appreciated!
