### ISSUE TITLE
Confusion about Cloud Resources Format

### ISSUE THREAD

**Issue by BLTTEST** [MicrosoftDocs/windows-itpro-docs#6973]
Hi Teams,

I'm a little confused about the description of cloud resources: Separate multiple resources with the "|" delimiter. If you don’t use proxy servers, you must also include the "," delimiter just before the "|". 

According to this description, should the Value format without proxy like: "contoso.sharepoint.com,|contoso.visualstudio.com"? However the Value format without proxy given by the article is like: "contoso.sharepoint.com|contoso.visualstudio.com".

If I misunderstand anything, Please correct me.

Best Regards,
Ben

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ad3f92-24de-5eb5-8454-c72d85737183
* Version Independent ID: 900125eb-31ea-faf3-ac30-7c3d7b30f611
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @BLTTEST, correct syntax is with commas.
The value section was fixed already, however it is still incorrect (it misses one comma at the end), I just created a PR to fix that.
Thank you

**Comment by BLTTEST** [comment]
Hi @MaratMussabekov 
It's nice to see it‘s under correcting process and thank you very much for your help!
Best Regards
