### ISSUE TITLE
Applies to Teams and Yammer

### ISSUE THREAD

**Issue by ssccaavvookk** [MicrosoftDocs/windows-itpro-docs#6975]
I believe the idea behind this section should be extended to apply to at least Teams and Yammer as well. While they may not be available on Personal O365 subscriptions, as far as I can tell, it is impossible to create a Cloud Resource rule that can differentiate between different organizations which generally creates the same risk. This is due to WIP network boundaries being limited to domains and subdomains, and not all O365 apps create unique subdomains for each tenant for all apps. E.g. you can make a rule to identify contoso.sharepoint.com and contoso-my.sharepoint.com as Contoso cloud resources, and will prevent workfiles from going to blahblah.sharepoint.com. Outlook, teams, yammer web apps cannot be protected though, because they all use the same domain and subdomains: outlook.office.com, teams.microsoft.com, yammer.com/contoso

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cf748a5-ebfd-ca94-0492-7580094618ee
* Version Independent ID: b51e7663-6ef8-e1d3-6b68-7b897093c157
* Content: [Using Outlook on the web with WIP (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/using-owa-with-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/using-owa-with-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/using-owa-with-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by lindspea** [comment]
@ssccaavvookk thank you for reaching out and helping improve MS Docs. Are you suggesting adding a note to this article and have you checked to see that it does in fact apply to Teams and Yammer?

**Comment by ssccaavvookk** [comment]
I suggest adding it, as of 3 months ago it did apply to Teams and Yammer, but I have taken down my WIP policies to switch to EndPoint DLP (which suffers from the same issue but isn't applicable here). I doubt it has changed, it's a bit of a fundamental implementation problem, but I can no longer verify.

**Comment by lindspea** [comment]
@DulceMontemayor please can you confirm if this is still applicable and I'll do the PR for the article.

**Comment by VLG17** [comment]
@ssccaavvookk Teams is considered a WIP-work only app, hence an unenlightened app. 

In the scenario where you would use Teams only for corporate communication and data, you can add it to the Protected Apps section of your WIP policy. This will cause the app to enforce protection to all the data it works with or has access to. 

I understand that the above behavior is not happening if you add Teams (or Yammer) to the Cloud Resource network element in your WIP policy (although i have not tested it), but why would you do that and not add Teams to the Protected Apps directly and thus have it treat everything as corporate data and have it protected?

**Comment by nam31** [comment]
@ssccaavvookk  Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
