### ISSUE TITLE
outdated admx templates

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#6976]
This article has November 1909 update admx templates download link, but it is outdated, But Microsoft windows 10 v2004 team has already updated the latest templates.
So this download link needs to be updated.
Thanking you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f5f37f-9e03-eac1-715b-4a01acfff33e
* Version Independent ID: b7e76481-3859-c8d1-c22d-ee238fadd1e9
* Content: [Use PowerShell cmdlets to configure and run Microsoft Defender AV - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/use-powershell-cmdlets-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/use-powershell-cmdlets-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/use-powershell-cmdlets-microsoft-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by nam31** [comment]
issue already fixed by
 https://github.com/MicrosoftDocs/windows-itpro-docs/commit/43d5d43ad2b6edc086ac8dfbf018e0e570fcfd96#diff-c645063130d930e77bb92babd75ddeea

**Comment by illfated** [comment]
BTW, the commit is https://github.com/MicrosoftDocs/windows-itpro-docs/commit/9f5807247596e8271076a6b4dffa1ad448662727 (just f.y.i.)

**Comment by illfated** [comment]
@nam31 : Happy to see a new member on the MS Docs team. Welcome.

**Comment by RAJU2529** [comment]
@illfated . Who is new member?

**Comment by illfated** [comment]
Looks like @nam31 has been given a similar position to the one @mypil and @jvsam used to have. I do not have any written evidence, but she closed this ticket as any MS Docs team ticket handler would do.

**Comment by RAJU2529** [comment]
@illfated . Ok thanks.

**Comment by nam31** [comment]
Hi @RAJU2529  and @illfated  Yes, I am the new member :) 
Yes, above solution shared by a Freelancer. Please let me know if there is any conflict with that?

**Comment by RAJU2529** [comment]
@nam31 . No conflict. From the next query onwards, i tag your name for  further PR or issues to look
