### ISSUE TITLE
Value Type for ForceDefenderPassiveMode registry value missing from document

### ISSUE THREAD

**Issue by jowiswel** [MicrosoftDocs/windows-itpro-docs#6978]
The EnforceDefenderPassiveMode registry value needs to be of type REG_DWORD, which is not specified in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4ed2b3-0390-4d53-2450-14995ee8b0b0
* Version Independent ID: 91b5bb3e-55d4-6a8e-c16d-094f15c28ee7
* Content: [Onboard servers to the Microsoft Defender ATP service - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@mypil ,Please close this issue, because this user had already created another issue #6977

**Comment by jowiswel** [comment]
Varadharajan:

Do note that while these issues are the same, they are for two different documents.

One is for this link: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints

The other is for this link: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility

Jon Wiswell II
Americas SCCM Tier 3 Support Escalation Engineer
Jon.Wiswell@Microsoft.com<mailto:Jon.Wiswell@microsoft.com>; (469) 775-3735 | Working Hours: Mon-Fri 10:00am - 7:00pm CDT
Backups: Renato Pacheco<mailto:Renato.Pacheco@microsoft.com>; (469) 775-2307 | Justin Qassis<mailto:Justin.Qassis@microsoft.com>; (469) 775-4818
Manager: Alana Wegfahrt<mailto:alanweg@microsoft.com>; (469) 775-4820 | Microsoft Premier Support: (800) 936-3100

Help us provide you the best service by "Replying All" to all email communications.

Are you running a supported version of Configuration Manager? Click here<https://techcommunity.microsoft.com/t5/Configuration-Manager-Archive/A-quick-note-on-support-for-non-SP2-versions-of-ConfigMgr-2012/ba-p/274049> and here<https://docs.microsoft.com/en-gb/sccm/core/servers/manage/current-branch-versions-supported> to be sure!

**Comment by RAJU2529** [comment]
@jowiswel . ok now I understood. thanks for pointing out.

**Comment by illfated** [comment]
Resolved. #please-close
