### ISSUE TITLE
USMT Add-on for Windows 10 modern apps, Sticky Notes , Edge etc. 

### ISSUE THREAD

**Issue by JanineMarchese** [MicrosoftDocs/windows-itpro-docs#698]
Hi 
We have just had success with using a free MDT/SCCM USMT add-on, "USMTGUI afterburner", that can handle migration of modern apps like Edge favorites and Sticky Notes. 
http://sccmdeploy.dk/?p=731
This is an annoying Windows 8/10 USMT issue handled really clever.
Gina Melford over at Berkeley told me that EhlerTech helped them customizing for other app settings aswell.
JM 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0348996-1907-fe61-e9f3-6b886f69de77
* Version Independent ID: ea00ec20-bf2b-acc0-bd9e-623155cdd331
* Content: [User State Migration Tool (USMT) Technical Reference (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-technical-reference)
* Content Source: [windows/deployment/usmt/usmt-technical-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/usmt/usmt-technical-reference.md)
* Service: **unspecified**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by samohtrelhe** [comment]
Hi
(Thankyou, Janine for the nice words on the Afterburner)
We have just added a bunch of XML files for USMT, handling Firefox and Chrome, Excluding system folders and other drives than C:\ with a guide to implement on SCCM and MDT.
AND updated the documentation for using the USMT Afterburner with a SCCM/MDT implementation guide :-)
http://ehlertech.com/customxmls/

/Sam
