### ISSUE TITLE
Deploying an App to Surface Hub via Intune/Endpoint Manager

### ISSUE THREAD

**Issue by Tosong767** [MicrosoftDocs/windows-itpro-docs#6983]
This article is out of date as the interface has completely changed.
Can someone please update this with the new procedure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40456ae3-80bc-8dc8-44a1-abd3a7cbc994
* Version Independent ID: cf23627b-5861-119e-9aea-43194140aec8
* Content: [Deploy apps to Surface Hub 2S using Intune - Surface Hub](https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-deploy-apps-intune)
* Content Source: [devices/surface-hub/surface-hub-2s-deploy-apps-intune.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface-hub/surface-hub-2s-deploy-apps-intune.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Thanks for bringing up the issue. I've submitted it to the author who will be updating this document. It needs to be scheduled so the update won't happen immediately, but should not take too long.
