### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by iloving** [MicrosoftDocs/windows-itpro-docs#6988]
The link to the M365 deployment advisor is broken.

Correlation ID:ncu#01cb2dc3-ec62-4187-9a14-9ce91a2fef9a
--
  | Error code:0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d34316d0-bb07-27a0-046b-a2534115a176
* Version Independent ID: 7d358473-9967-2d62-10f2-ce761cc674b1
* Content: [Deploy Windows 10 with Microsoft 365 - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-m365)
* Content Source: [windows/deployment/deploy-m365.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-m365.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@greg-lindsay. Issue is conformed by me also after checking.

**Comment by greg-lindsay** [comment]
Can you reach https://portal.office.com/onboarding/WindowsAnalyticsDeploymentAdvisor#/ ?

**Comment by greg-lindsay** [comment]
Try these links and see if they work for you:
https://aka.ms/microsoft365setupguide
https://aka.ms/windowsanalyticssetupguide

**Comment by RAJU2529** [comment]
@greg-lindsay . Below link does not opened. Giving error message. 
https://portal.office.com/onboarding/WindowsAnalyticsDeploymentAdvisor#/

**Comment by iloving** [comment]
https://aka.ms/microsoft365setupguide takes me to  takes me to the M365 deployment advisor as long as I'm logged into my admin account.

https://aka.ms/windowsanalyticssetupguide takes me to https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/overview.  Is that what was intended?

**Comment by e0i** [comment]
@greg-lindsay The link still seems to be broken. Seems to be a redirection issue. Please let us know whether we could help a PR via independent contributors. Thank you.

**Comment by greg-lindsay** [comment]
@iloving yes those are the locations you should see with those links.
