### ISSUE TITLE
Missing word

### ISSUE THREAD

**Issue by L1ttl3J1m** [MicrosoftDocs/windows-itpro-docs#6989]
"Computer Configuration\Windows Settings\"

Should be "Computer Configuration\Policies\Windows Settings\"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed5f0d1b-bfbb-c2a8-76e7-b4b0105160e8
* Version Independent ID: 13684860-a76b-5832-4376-22a585f63fd1
* Content: [Maximum password age (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/maximum-password-age)
* Content Source: [windows/security/threat-protection/security-policy-settings/maximum-password-age.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/maximum-password-age.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@L1ttl3J1m . No missing word. Because article told for windows 10 only, not for windows server..

**Comment by illfated** [comment]
@L1ttl3J1m : I agree with RAJU2529 regarding his conclusion. The policy path described in this documentation page is correct for Windows 10, at least in current builds.

If you can document otherwise, please let us know by showing us examples (links or screenshots) where your suggestion applies.

**Comment by L1ttl3J1m** [comment]
Huh. So it is. I guess I've never gone to edit a group policy locally. Case closed.
