### ISSUE TITLE
Location of Group Policy

### ISSUE THREAD

**Issue by hurikaneman** [MicrosoftDocs/windows-itpro-docs#6992]
Correct me if I'm wrong, should the following:

"Computer Configuration\Windows Settings\Security Settings\Account Policies\Password Policy"

instead be 

"Computer Configuration\Policies\Windows Settings\Security Settings\Account Policies\Password Policy"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5128d9a-e02a-df9b-24cc-32711ad37b54
* Version Independent ID: fecafb19-6b37-1f2e-ba3d-5e0bf0d49d09
* Content: [Password must meet complexity requirements (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements)
* Content Source: [windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@L1ttl3J1m . No missing word. Because article told for windows 10 only, not for windows server..

**Comment by illfated** [comment]
Yes, the article wording is correct, at least for current builds of Windows 10.

If you find any documentation showing `Computer Configuration\Policies\Windows Settings\Security Settings\Account Policies\Password Policy` for any supported build of Windows 10, please add that information to this ticket.

**Comment by hurikaneman** [comment]
Oh, I understand now. Thank you for the reply!
