### ISSUE TITLE
Deploy WDAG via Intune on Windows 10 Education edition, version 1909

### ISSUE THREAD

**Issue by yogeshasalkar** [MicrosoftDocs/windows-itpro-docs#6999]
[Hi, Could anybody confirm whether we can deploy WDAG using Intune to Windows 10 Education edition, version 1909. I tried but getting the error 'Not applicable' in Intune. if this version is not supported then tell me on which windows 10 edition we can deploy WDAG via MS Intune
Thanks]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f43df7b-6ead-de5a-2e41-4d49978ab485
* Version Independent ID: 5497d300-cb21-55f3-7e80-98bc3592635c
* Content: [System requirements for Microsoft Defender Application Guard (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-application-guard/reqs-md-app-guard)
* Content Source: [windows/security/threat-protection/microsoft-defender-application-guard/reqs-md-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-application-guard/reqs-md-app-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@yogeshasalkar . Do you have a compatible processor with windows 10  education or enterprise desktop.

**Comment by yogeshasalkar** [comment]
My pc specifications -
CPU Cores 4 
CPU Virtualization Enabled
RAM 8GB
OS windows 10 education 1909


I can configure WDAG using Group Policy, however I am not able to configure it via Intune. Getting not applicable error.

**Comment by RAJU2529** [comment]
@yogeshasalkar .  that means pc is supported, then wait for replies  from the intune expert users.
Sorry, i am not using intune. so wait.

**Comment by MaratMussabekov** [comment]
Hello, yes, Intune deployment is supported by Enterprise and Education editions.
**Could anybody confirm whether we can deploy WDAG using Intune to Windows 10 Education edition, version 1909. I tried but getting the error 'Not applicable' in Intune** - have you tried to apply the same configuration profile on PC running Enterprise edition? Does result differ?

Thank you

**Comment by nam31** [comment]
@yogeshasalkar We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
