### ISSUE TITLE
BitLocker Network Unlock Certificate Creation

### ISSUE THREAD

**Issue by TRLABz** [MicrosoftDocs/windows-itpro-docs#7002]
[HI.  Please see Step 6 under "Create the Network Unlock Certificate" Here: https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock#create-the-network-unlock-certificate. It mentions setting up a "Friendly Name" but that doesn't seem to be what is required. It needs either a Subject Name or an Alternative Name, but the instructions are not clear about what to provide for either of those.  See this SpiceWorks article for details: https://community.spiceworks.com/topic/2149260-setting-up-bitlocker-network-unlock. Thank you!]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c13083-9b29-e54b-fd85-8033ec665fcd
* Version Independent ID: ce8c4647-69bc-95d4-2192-6e737d5ad5da
* Content: [BitLocker How to enable Network Unlock (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock#create-the-certificate-template-for-network-unlock)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@TRLABz I don't have a way to test this quickly, but as far as i remember, the friendly name goes under the General Tab. (i could be mistaken)

Looking at the Certificate Properties Window, it tells you what to put in for Subject (the user or computer that is receiving the certificate).

![image](https://user-images.githubusercontent.com/41186174/87760308-37410600-c818-11ea-9ccc-855f46810c67.png)

Subject Name - Type: Common Name : computer name that the certificate is being assigned to
Alternative Name - Type: DNS Name: FQDN (servername.domain.com) 

Could you test this and see if it works? If it does we'll need to think of the best way to amend the article.

**Comment by TRLABz** [comment]
@VLG17, will do.  Secondly, did you get spammed by about a thousand new issues with Chinese characters today?

**Comment by VLG17** [comment]
@TRLABz , thank you. Regarding your question, no, fortunately it didn't happen.

**Comment by e0i** [comment]
> @VLG17, will do. Secondly, did you get spammed by about a thousand new issues with Chinese characters today?

@TRLABz 
Yes, And the spam issues have been removed.
