### ISSUE TITLE
Relationship to Secure Score

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#7003]
[Enter feedback here]

How does this fit into the overall M365 Secure Score? Please provide an explanation of this.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc0d8791-9164-d407-98fd-101bc6fc8474
* Version Independent ID: 7a7aa114-8840-1770-2768-38aa2da335a5
* Content: [Exposure score - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/tvm-exposure-score)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/tvm-exposure-score.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/tvm-exposure-score.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
@DeanGross thank you for the question. The exposure score is not directly connected to Microsoft Secure Score. It is just a metric indicating how exposed your devices are based on weaknesses, external/internal threats, and value to your organization. There are some security recommendations that affect just your exposure, and others that can affect your exposure and configuration score. 

Your configuration score is basically the devices pillar in Secure Score. A higher configuration score means a higher Secure Score. There are updates coming soon where these relationships will become clearer.

**Comment by DeanGross** [comment]
The fact the Secure Score has a Devices section is why I asked the question. It would be helpful if we could see some data flow diagrams that showed how various features/apps/services populate the score cards

**Comment by levinec** [comment]
@DeanGross thanks for the feedback!
