### ISSUE TITLE
Relationship to other scores

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#7004]
[Enter feedback here]
How does this relate to the Secure Score and Compliance Scores? please provide an explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe8f0295-d8b3-741c-6731-c4c0492c3d9e
* Version Independent ID: fd7efe34-dc29-bf8a-992d-7a4b436b6b2e
* Content: [Overview of Configuration score in Microsoft Defender Security Center - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configuration-score)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configuration-score.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configuration-score.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Answered in https://github.com/MicrosoftDocs/windows-itpro-docs/issues/7004
