### ISSUE TITLE
Guidance on timeframe for Win 10 E5 license to be available after assignment ?

### ISSUE THREAD

**Issue by SteffanH** [MicrosoftDocs/windows-itpro-docs#701]
I have assigned a W10 E5 license to a user running version 1803, but even after a reboot and logging in again the existing Pro installation is not upgraded to Enterprise.
Is there a way to force windows to check for an available subscription, or additional troubleshooting guidance ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-subscription-activation)
* Content Source: [windows/deployment/windows-10-enterprise-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-enterprise-subscription-activation.md)
* Service: **unspecified**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by kumaarrahul** [comment]
Generally, it takes around 24 hours to get Windows to step-up to Enterprise.

Also, if the devices are connected to a domain controller make sure that the below mentioned GPO/Registry keys are modified as below.

Please Disable ‘Do not connect to any Windows Update Internet locations’ GPO/Registry key.
 
GPO Location:
 
Configure the policy value for Computer Configuration -> Administrative Templates -> Windows Components -> Windows Update -> "Do not connect to any Windows Update Internet locations" to "Disabled".
 
Registry Key Location:
 
Registry Hive: HKEY_LOCAL_MACHINE 
Registry Path: \SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\
 
Value Name: DoNotConnectToWindowsUpdateInternetLocations
 
Value Type: REG_DWORD
Value: 0

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@SteffanH - thank you for submitting feedback.

From our understanding the issue has been answered by kumaarrahul. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
