### ISSUE TITLE
Misspelling in Policy

### ISSUE THREAD

**Issue by jonathan-mckinney** [MicrosoftDocs/windows-itpro-docs#7010]
There is a misspelling in this policy:
Connectivity/DiablePrintingOverHTTP

It should be:
Connectivity/DisablePrintingOverHTTP

However, when you spell it correctly the setting does not work. You must spell it incorrectly in order to enable the setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e70a68f-210c-b27a-3224-2cfd80028e60
* Version Independent ID: c6a94ff0-9ab2-cd09-c053-e09304d0d16a
* Content: [Policy CSP - Connectivity - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-connectivity#connectivity-diableprintingoverhttp)
* Content Source: [windows/client-management/mdm/policy-csp-connectivity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-connectivity.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
@jonathan-mckinney : in which OS version(s) & build(s) have you seen this typo in the GPO AMDX files?

**Comment by jonathan-mckinney** [comment]
The misspelling is not in the admx file, it is on the CSP itself. 
You can see this in the registry as well under: 

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\default\Connectivity\DiablePrintingOverHTTP

This is in Windows 10 1909. If this misspelling is fixed in the documentation it will also need to be fixed in the OS itself...

**Comment by RAJU2529** [comment]
@jonathan-mckinney . Thanks to your intelligent finding. 
Just now I changed in OS too

**Comment by RAJU2529** [comment]
@ManikaDhiman . Will you accept to change in the OS itself  in coming next update. 
I agreed @jonathan-mckinney  findings .

**Comment by illfated** [comment]
> The misspelling is not in the admx file, it is on the CSP itself.
> You can see this in the registry as well under:
> 
> Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\default\Connectivity\DiablePrintingOverHTTP
> 
> This is in Windows 10 1909. If this misspelling is fixed in the documentation it will also need to be fixed in the OS itself...

Oh dear. This is "more than I bargained for" when it comes to helping out with improvements in the MS Docs repository. Knowing that this typo is in the OS itself, this means that the PR to change the documentation will be negligible at best, possibly counterproductive, in light of what needs to be done to fix this typo in the Windows operating system.

@denisebmsft & @mypil : Do you have any suggestions for what our course of action should be here? I worry that the OS typo might not be something we can do much to change, knowing that it has been present for at least 6 months in the real world, maybe longer, depending on how long the GPO has been available in the OS itself.

I look forward to your recommendation for what to do to move forward with this ticket and its related PR.

**Comment by ManikaDhiman** [comment]
I agree with @illfated. We should hold off fixing the typo in the docs until it is fixed in the OS. The setting is mentioned in its misspelt version in the Policy CSP DDF file as well. I can reach out to the policy owner and let them know about this typo, but until they fix it, we should keep the doc as is.

**Comment by jonathan-mckinney** [comment]
Okay I agree as well

**Comment by ManikaDhiman** [comment]
Hi @mypil, @illfated, Here's the update from the product team on this issue: Unfortunately the policy definition itself has a typo so we cannot fix this in the document nor fix in the future unless we introduce a new policy with the name without typo.

So, we would need to close this issue and leave the doc as is. Thanks!

**Comment by mypil** [comment]
@jonathan-mckinney - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author @ManikaDhiman so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
