### ISSUE TITLE
 Programmatically Enroll to Update Compliance

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#7017]
Any plans to  make that possible via api / powershell / cli??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 203edb5f-4274-eafb-323b-01fd55192c85
* Version Independent ID: 7a4beba8-b79b-92c3-59b9-b73c92947083
* Content: [Get started with Update Compliance - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-get-started)
* Content Source: [windows/deployment/update/update-compliance-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-get-started.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@cinglis-msft can you comment?

**Comment by cinglis-msft** [comment]
It is not currently planned, but we have received feedback that it is a feature people would be interested in.

On Jun 29, 2020, at 5:53 PM, Jaime Ondrusek <notifications@github.com> wrote:

﻿

@cinglis-msft<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcinglis-msft&data=02%7C01%7C%7C8e0b555c876b4b82a5d108d81c7f2edb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637290679848584692&sdata=DOHY6SY%2BpavCR7C8pKO9oBGVCb3ZEqZqmIyHvN9FOpg%3D&reserved=0> can you comment?
