### ISSUE TITLE
Defender ATP blocking latency

### ISSUE THREAD

**Issue by Rohit-MITA** [MicrosoftDocs/windows-itpro-docs#7019]
On the note: "There may be up to 2 hours of latency (usually less) between the time the action is taken, and the URL and IP being blocked."

Can you confirm if Defender ATP will block indicators in real time if the actions is set to "Alert and Block", e.g. users  visit ip/domain/website that is an indicator and they will be blocked from accessing the domain/website/ip

If the blocking is not real time, what is the purpose of delayed "blocking"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50f2be10-41a0-67ae-222b-1b073bef537b
* Version Independent ID: 3f186b13-aad0-4ba4-e239-d9bb24ff2ebe
* Content: [Manage indicators - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/manage-indicators)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/manage-indicators.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/manage-indicators.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by MaratMussabekov** [comment]
Hello @Rohit-MITAб
"There may be up to 2 hours of latency (usually less) between the time the action is taken and the URL and IP being blocked" means that it could take up to two hours to the URL/IP to be blocked, after the indicator is configured. When user tries to access blocked URL/IP, the connection is blocked without any delay.
Thank you
