### ISSUE TITLE
Assistance

### ISSUE THREAD

**Issue by wpretorius** [MicrosoftDocs/windows-itpro-docs#702]
Thank you for the excellent explanation. My only issue is, I have built the package and installed same, however I do not see my custom created APN settings anywhere in Window 10, in order to verify and test. Please could you assist on how I will actually confirm my new APN created is available. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7afc636c-5765-b54b-64d7-8f2a6af3e2f7
* Version Independent ID: f4e1bf79-5d06-4015-caeb-ecd5a01491d3
* Content: [Configure cellular settings for tablets and PCs (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/provisioning-apn)
* Content Source: [windows/configuration/provisioning-apn.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/provisioning-apn.md)
* Service: **unspecified**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
You should see the APN configuration for the SIM inserted in the device. To find this setting, select the Start  button, then select Settings  > Network & Internet  > Cellular  > Advanced options.

**Comment by wpretorius** [comment]
Thank you for your response Jeanie, just a last question based on your response. Does one need to set the APN settings per SIM inserted? The only settings I set was the following, is this correct?

[cid:image001.png@01D3D304.31E41F00]

Thanks Wikus


Wikus Pretorius 
technical support team leader
 
tel: +27 11 269 7600 
mobile: +27 82 310 4239
email: wpretorius@ENSafrica.com
offices: ENSafrica Locations

**Comment by jdeckerms** [comment]
I've just learned from the engineering team that an APN set by a provisioning package won't be showing in the Settings UI. They said you can confirm the setting by opening a command prompt as administrator to run the following commands:

>netsh mbn show profiles

This command will list the profiles. Using the "Name" for the listed mobile broadband profile, run:

>netsh mbn show profiles name="name"

This command will list details for that profile, including Access Point Name.

You can also use the command:

>netsh mbn show interface

From the results of that command, get the name of the cellular/mobile broadband interface and run:

>netsh mbn show connection interface="name"

The result of that command will show details for the cellular interface, including Access Point Name.

This was a good question, thanks for bringing it up! I'll be adding this information to the topic.

**Comment by wpretorius** [comment]
Thank you very much for your response, I can now see my APN settings have applied to the device and listed.

If one is not able to see in under settings UI, how would you actually then force the connection to use the created APN? Is one able to set is as Default somehow?


Wikus Pretorius 
technical support team leader
 
tel: +27 11 269 7600 
mobile: +27 82 310 4239
email: wpretorius@ENSafrica.com
offices: ENSafrica Locations
