### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by KoenBekaert** [MicrosoftDocs/windows-itpro-docs#7020]
What is the correct license requirement? the New Microsoft 365 F1 subscription or Microsoft 365 F3 subscription (AKA the Old Microsoft 365 F1 subscription)? 
It's Confusing!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aafc065-6ee6-e3cf-31ba-ab3dd277fb23
* Version Independent ID: 35d3102e-4ff7-9408-8dbd-513b7dfff5c0
* Content: [Windows Autopilot requirements - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-requirements)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/windows-autopilot-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by MaratMussabekov** [comment]
Hello @KoenBekaert ,
the [documentation](https://docs.microsoft.com/en-us/mem/autopilot/licensing-requirements) is correct, both F1 and F3 are supported (as both contain Azure AD Premium P1 and Microsoft Intune)
The [pricing page](https://www.microsoft.com/en-us/microsoft-365/enterprise/firstline?rtc=1) looks outdated as it shows that only F3 supports Autopilot.
Thank you

**Comment by greg-lindsay** [comment]
I believe that F3 used to be required, but later F1 was added.  Now you can have either.
