### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by durbanbr** [MicrosoftDocs/windows-itpro-docs#7021]
Hi,
I would like to understand why some exclusions have two bars, as an example:

% windir% \ SoftwareDistribution \ Datastore **\\** tmp.edb

Also other doubts, as some do not have * before the extension:

% windir% \ Security \ database \ **.chk**

Now two more questions: Are these exceptions the same file names?

% systemdrive% \ System Volume Information \ DFSR \ **$ db_normal $**
% systemdrive% \ System Volume Information \ DFSR \ **$ db_dirty $**
% systemdrive% \ System Volume Information \ DFSR \ **$ db_clean $**
% systemdrive% \ System Volume Information \ DFSR \ **$ db_lostl $**

and this one, is the point right?

% systemroot% \ Sysvol \ Domain \ **.**Scripts.ini

**Comment by durbanbr** [comment]
Excuse me,
I translated the page into Portuguese and it was not so faithful ... But even so I was still in doubt of some things:

Because it has this asterisk here, it means that regardless of the folder it is in, you have to delete this file?
%windir%* \SoftwareDistribution\Datastore\*\Datastore.edb


and keep the doubt of these file names, if it is the name with this symbol $:

% systemdrive% \ System Volume Information \ DFSR \ $ db_normal $
% systemdrive% \ System Volume Information \ DFSR \ $ db_dirty $
% systemdrive% \ System Volume Information \ DFSR \ $ db_clean $
% systemdrive% \ System Volume Information \ DFSR \ $ db_lostl $

**Comment by RAJU2529** [comment]
@durbanbr . Which article are you referring?

**Comment by durbanbr** [comment]
Sorry,
https://docs.microsoft.com/pt-br/windows/security/threat-protection/microsoft-defender-antivirus/configure-server-exclusions-microsoft-defender-antivirus#list-of-automatic-exclusions

**Comment by durbanbr** [comment]
Sorry again, I realized now that the first example didn't paste correctly.

%windir%***** \SoftwareDistribution\Datastore**\*\**tmp.edb

**Comment by illfated** [comment]
@durbanbr : Thank you, both for pointing out the translation issue and asking if the information in the /pt-br/ page is correct or not.

1. The asterisk ( ` * ` ) is frequently used as an indicator that any file name string or data string can be entered there, meaning that some entries use the asterisk ( ` * ` ) to allow for multiple matches to the complete string content.
2. When in doubt, use the /en-us/ page to make sure you get the correct data. See https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-server-exclusions-microsoft-defender-antivirus#list-of-automatic-exclusions for the correct information.
3. Several MS Docs team members are aware that there are multiple issues regarding the automated Machine Translation to other languages. Please use only the translated general text as a guide to find the information you need.
4. Use the /en-us/ page to make sure that you use the correct data when it comes to the technical data information on the page. Unfortunately, there are several known issues with translating MarkDown or HTML code to other languages, especially when it comes to displaying important key data information for your configuration purposes.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

@TinaMcN : I notice that there are multiple discrepancies in the MT /pt-br/ page referenced above. Would it be useful to suggest encapsulating the key string contents in the /en-us/ page with MarkDown back ticks, to try to keep them from being translated, or is this something you would prefer to see corrected in the machine translation tools used by Microsoft?

**Comment by durbanbr** [comment]
Thanks for the reply. I understood the question of *, but what I meant is, in the case of the example mentioned, any folder that comes after the DataStore folder, which has the file Datastore.edb, should be ignored by the antivirus when reading in real time. Is my analysis correct?

About the other question, is there a file called $ db_dirty $ or is $ also a variable?

**Comment by illfated** [comment]
Unfortunately, I don't know the inner workings of Distributed File Server Replication or  `\System Volume Information\DFSR\` databases, but as an educated guess, based on naming conventions for other database systems, I would say that the database names
```
%systemdrive%\System Volume Information\DFSR\$db_normal$
%systemdrive%\System Volume Information\DFSR\$db_dirty$
%systemdrive%\System Volume Information\DFSR\$db_clean$
%systemdrive%\System Volume Information\DFSR\$db_lostl$
```
are most likely internal default names and could be a remnant of older naming conventions from 20+ years back, when database naming conventions often had cryptic origins. I can only suggest browsing through any reliable information sources you come across on the internet, whether it is Microsoft-based or only technical work-related pages, to get an idea of where the names originate from. Going out on a limb, I could risk a guess that the DB name format could have been intended as a possible basis for internal scripting to use the names as internal variables, but not as external variables (at least not originally).

You may want to take a quick look at the pages below to see how other people recommend to deal with them:
- https://community.spiceworks.com/topic/2181365-defender-automatic-exclusions-confirmation
- https://support.microsoft.com/en-us/help/822158/virus-scanning-recommendations-for-enterprise-computers
- https://www.bing.com/search?q=%5CSystem+Volume+Information%5CDFSR%5C

**Comment by illfated** [comment]
As a personal recommendation for the future, I suggest learning more about MarkDown and how it can be used to create
```sql
MarkDown code blocks
```
encapsulated strings (`displayed as monospaced type`) and other neat features to be used in GitHub tickets and comments.

**Comment by durbanbr** [comment]
thank you very much for the answers given. I will study a little more about it and how I will apply it to my anti virus

I'll take a look at how this html programming issue works, because I don't know anything about this "world" !! Thanks again

**Comment by TinaMcN** [comment]
@durbanbr thanks for highlighting the issues.   @illfated the engineers are working on a fix to avoid overlocalization like this on machine translated articles but it may be a few months before it's fixed.  In the meantime it would be helpful to encapsulate the non-localizable strings in the English article.
