### ISSUE TITLE
How do I get the version of the installed software?

### ISSUE THREAD

**Issue by Keagnn** [MicrosoftDocs/windows-itpro-docs#7022]
I would love for this response to include the version of the software that's installed.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 966fa534-25be-a5e5-be9f-b63c1d1c4d9f
* Version Independent ID: 05efaf9b-d5cb-eaba-6cfb-a0f10ed22c8a
* Content: [Get installed software - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/get-installed-software)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/get-installed-software.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/get-installed-software.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by VLG17** [comment]
@Keagnn Could you please pass this feedback forward with the help of [User Voice](https://office365.uservoice.com/)?

When it gets implemented we can add it to the response presented as an example in the docs.
