### ISSUE TITLE
Intune Company Portal has to be downloaded from Google Play?

### ISSUE THREAD

**Issue by yjhgdipgfj** [MicrosoftDocs/windows-itpro-docs#7026]
Hi there, just curious a wording issue in the doc. I see the following statement was made to System Requirement:

https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-android#system-requirements

System Requirements
Android devices running Android 6.0 and above.
Intune Company Portal app is downloaded from Google Play and installed. Device enrollment is required for Intune device compliance policies to be enforced.

Does it means the Company Portal app from other app store is not supported for MDATP? If this is not the case, would it be better to simply mention that Company Portal app is required?

Looking forward for your feedback!

BRs,
-Tim

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ca0f1a2-2eef-9d27-3c88-04ad36c90e48
* Version Independent ID: 4ae18229-4b35-50ff-9476-de3f9ebeafcd
* Content: [Microsoft Defender ATP for Android - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-android)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-android.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-android.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@yjhgdipgfj The article referenced talks about Microsoft Defender ATP for Android, and the official app store for Android is Google Play, so that's why it's explicitely stated like that.

If it were a general article, and not specific for Andoid, it would have been a general statement.

**Comment by nam31** [comment]
@yjhgdipgfj Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
