### ISSUE TITLE
Effect of VPN?

### ISSUE THREAD

**Issue by ArttuArstila** [MicrosoftDocs/windows-itpro-docs#7027]
What parts of web protection rely on VPN functionality? Asking this because you can either disable web protection completely or just the VPN, as instructed here: https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection#configure-web-protection-on-devices-that-run-android

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162e0510-f05e-14fb-486a-32173e3f8c8c
* Version Independent ID: ead06fb0-e149-32c9-99f2-78f3e51537ea
* Content: [Web protection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/web-protection-overview)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/web-protection-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/web-protection-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Hi @ArttuArstila, I heard back from the PMs. On device admin enrolled devices, the VPN functionality is an added capability/configuration to enable the web protection feature. On Android Enterprise enrolled devices, it is the only capability/configuration that enables the web protection feature. So, on Android Enterprise , if you turn off the VPN configuration, it is going to disable the web protection feature. 

I hope that answers your question.
