### ISSUE TITLE
References section that is not linked

### ISSUE THREAD

**Issue by cchapin2020** [MicrosoftDocs/windows-itpro-docs#7028]
[Enter feedback here]
On this page, there is a line that says "see the Security Monitoring Recommendations". It is not linked and there is not a section on the page with that title. What content is being referenced by that statement?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a6ab2f1-4d09-9c9e-dacf-aa45e39a1700
* Version Independent ID: 825aa439-7843-9621-f82c-db37d711a036
* Content: [Audit Kerberos Service Ticket Operations (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-kerberos-service-ticket-operations)
* Content Source: [windows/security/threat-protection/auditing/audit-kerberos-service-ticket-operations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/audit-kerberos-service-ticket-operations.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
There is a page named **Appendix A: Security monitoring recommendations for many audit events** below all of the Audit events sections in the TOC list on the left side of the page:
- https://docs.microsoft.com/windows/security/threat-protection/auditing/appendix-a-security-monitoring-recommendations-for-many-audit-events

Maybe that page can be used as a link target?

**Comment by cchapin2020** [comment]
I agree, I think that was the intended target and a link needs to be added.

Thanks


Chris Chapin
Sr. Consultant – Identity | Secure Infrastructure
Office:    +1 (703) 579-2199
Mobile:  +1 (804) 316-5639
chris.chapin@microsoft.com<mailto:chris.chapin@microsoft.com>

[cid:image001.png@01D64AD3.763D6BE0]

**Comment by e0i** [comment]
Closing via #7032.
