### ISSUE TITLE
Need direct download links

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#7030]
Needed download links for edge browser and for adk 2004 , addson pe 2004
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d651de3c-b8eb-e8d9-8138-1eadb758bf2e
* Version Independent ID: a19a8b65-0f4a-efd5-7f83-56bd07cc8c3b
* Content: [What's new in Windows 10, version 2004 - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-2004?ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-QJM7gBYv2T5Eowt0B2Kprw&epi=je6NUbpObpQ-QJM7gBYv2T5Eowt0B2Kprw&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=%28ir__rmtvdnorickft3adxmdf30kppu2xnfsdqwlrvgyc00%29%287593%29%281243925%29%28je6NUbpObpQ-QJM7gBYv2T5Eowt0B2Kprw%29%28%29&irclickid=_rmtvdnorickft3adxmdf30kppu2xnfsdqwlrvgyc00#servicing)
* Content Source: [windows/whats-new/whats-new-windows-10-version-2004.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/whats-new-windows-10-version-2004.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
I would prefer not to have direct download links on this page as these links can change, and it's a blind link. It's better to link to the summary page that is updated if the links change.
