### ISSUE TITLE
MDATP for Android on Teams Phone Devices

### ISSUE THREAD

**Issue by richardjgreen** [MicrosoftDocs/windows-itpro-docs#7036]
Would it be possible for the article to have some clarification on whether it is supported to deploy the MDATP for Android client to Teams Phone Devices? 

Devices from vendors like Polycom and Yealink are running Android and they have the Company Portal app embedded along with the Microsoft Teams app. On this basis they would be supported but I suspect that the reality is that MDATP for Android will not function well on them.

Many customers are likely to use Dynamic Azure AD Groups to target their Android devices so adding clarification around the Teams Phone devices can help people to ensure that the group they use to target the MDATP install for Android devices will exclude the Teams Phone devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ca0f1a2-2eef-9d27-3c88-04ad36c90e48
* Version Independent ID: 4ae18229-4b35-50ff-9476-de3f9ebeafcd
* Content: [Microsoft Defender ATP for Android - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-android)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-android.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-android.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @richardjgreen ,
Each vendor use its own customized Android, and the possibility of deployment MDATP depends on which features were left in the OS and which were removed. In case device meet all the prerequisites, and the installed OS allows successfully perform all the actions listed [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/android-intune), I do not see any reason why it shouldn't work.
Anyways, as each vendor uses its own customized OS, it is not possible to be sure that MDATP would or would not work on the phone devices, and it is out of the scope of this document.
Dear @Dansimp , could you please confirm?

Thank you

**Comment by e0i** [comment]
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
