### ISSUE TITLE
How to block all websites except few

### ISSUE THREAD

**Issue by VAnjan12** [MicrosoftDocs/windows-itpro-docs#7038]
Hello

I am looking for a solution where we can block all websites except few (say 4) using Indicators or Web content filtering (cyren) in Microsoft Defender ATP. Could you please help me on this?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50f2be10-41a0-67ae-222b-1b073bef537b
* Version Independent ID: 3f186b13-aad0-4ba4-e239-d9bb24ff2ebe
* Content: [Manage indicators - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/manage-indicators#create-indicators-for-ips-and-urlsdomains)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/manage-indicators.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/manage-indicators.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
Check with group policy template,

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation and content-related issues.

Please open a support ticket via the link below so that that your question gets answered.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
