### ISSUE TITLE
Boot BSOD Enabling DG/CG with DG Readiness Tool 3.7, Windows 10 1909

### ISSUE THREAD

**Issue by rugabunda** [MicrosoftDocs/windows-itpro-docs#7044]
Device Guard VBS BSOD: SYSTEM_THREAD_EXCEPTION_NOT_HANDLED_M amdppm.sys; with AMD Ryzen 3600 

Happens using DG readiness Tool or enabling Group Policy `"Virtualization Based Protection of Code Integrity"` and or `"Secure Launch"` enabled. Keyboard and mouse fail to function in windows when bypassing the BSOD by disabling UEFI SecureBoot and enabling CMS in BIOS, system restore is necessary. NX is also enabled in BIOS, why it is not detecting this?

![Compatibility](https://user-images.githubusercontent.com/38260267/85918678-6df8b180-b854-11ea-963e-9b3f549c0ec8.png)

The following minidump was extracted with WinDBG, while disabling all "Incompatible HVCI Kernel Driver Modules".

`0: kd> !analyze -v
*******************************************************************************
* *
* Bugcheck Analysis *
* *
*******************************************************************************

SYSTEM_THREAD_EXCEPTION_NOT_HANDLED_M (1000007e)
This is a very common bugcheck. Usually the exception address pinpoints
the driver/function that caused the problem. Always note this address
as well as the link date of the driver/image that contains this address.
Some common problems are exception code 0x80000003. This means a hard
coded breakpoint or assertion was hit, but this system was booted
/NODEBUG. This is not supposed to happen as developers should never have
hardcoded breakpoints in retail code, but ...
If this happens, make sure a debugger gets connected, and the
system is booted /DEBUG. This will let us see why this breakpoint is
happening.
Arguments:
Arg1: ffffffffc0000005, The exception code that was not handled
Arg2: fffff80ed04d2144, The address that the exception occurred at
Arg3: ffffa488e4d32ee8, Exception Record Address
Arg4: ffffa488e4d32730, Context Record Address

Debugging Details:
------------------

KEY_VALUES_STRING: 1

Key : AV.Fault
Value: Write

Key : Analysis.CPU.Sec
Value: 3

Key : Analysis.DebugAnalysisProvider.CPP
Value: Create: 8007007e on DEVICE

Key : Analysis.DebugData
Value: CreateObject

Key : Analysis.DebugModel
Value: CreateObject

Key : Analysis.Elapsed.Sec
Value: 9

Key : Analysis.Memory.CommitPeak.Mb
Value: 78

Key : Analysis.System
Value: CreateObject

TAG_NOT_DEFINED_202b: *** Unknown TAG in analysis list 202b

DUMP_FILE_ATTRIBUTES: 0x8
Kernel Generated Triage Dump

BUGCHECK_CODE: 7e

BUGCHECK_P1: ffffffffc0000005

BUGCHECK_P2: fffff80ed04d2144

BUGCHECK_P3: ffffa488e4d32ee8

BUGCHECK_P4: ffffa488e4d32730

EXCEPTION_RECORD: ffffa488e4d32ee8 -- (.exr 0xffffa488e4d32ee8)
ExceptionAddress: fffff80ed04d2144 (amdppm!WriteIoMemRaw+0x00000000000000a8)
ExceptionCode: c0000005 (Access violation)
ExceptionFlags: 00000000
NumberParameters: 2
Parameter[0]: 0000000000000001
Parameter[1]: ffffffffffffffff
Attempt to write to address ffffffffffffffff

CONTEXT: ffffa488e4d32730 -- (.cxr 0xffffa488e4d32730)
rax=ffffe4062d11d920 rbx=ffffe4062ce220c0 rcx=0000000000000044
rdx=0000000000000020 rsi=ffffe4062ce22010 rdi=0000000000000001
rip=fffff80ed04d2144 rsp=ffffa488e4d33128 rbp=0000000000000000
r8=0000000000000001 r9=0000000000000020 r10=ffffbd0060180008
r11=0000000000000020 r12=00000000000001c8 r13=0000000000000013
r14=0000000000000001 r15=0000000000000013
iopl=0 nv up ei pl zr na po nc
cs=0010 ss=0018 ds=002b es=002b fs=0053 gs=002b efl=00050246
amdppm!WriteIoMemRaw+0xa8:
fffff80e`d04d2144 46890411 mov dword ptr [rcx+r10],r8d ds:002b:ffffbd00`6018004c=????????
Resetting default scope

CUSTOMER_CRASH_COUNT: 1

PROCESS_NAME: System

WRITE_ADDRESS: fffff8000d6273b8: Unable to get MiVisibleState
Unable to get NonPagedPoolStart
Unable to get NonPagedPoolEnd
Unable to get PagedPoolStart
Unable to get PagedPoolEnd
fffff8000d4de3c8: Unable to get Flags value from nt!KdVersionBlock
fffff8000d4de3c8: Unable to get Flags value from nt!KdVersionBlock
unable to get nt!MmSpecialPagesInUse
ffffffffffffffff

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR: c0000005

EXCEPTION_PARAMETER1: 0000000000000001

EXCEPTION_PARAMETER2: ffffffffffffffff

EXCEPTION_STR: 0xc0000005

LOCK_ADDRESS: fffff8000d5169e0 -- (!locks fffff8000d5169e0)
Cannot get _ERESOURCE type

Resource @ nt!PiEngineLock (0xfffff8000d5169e0) Available
1 total locks

PNP_TRIAGE_DATA:
Lock address : 0xfffff8000d5169e0
Thread Count : 0
Thread address: 0x0000000000000000
Thread wait : 0x0

STACK_TEXT:
ffffa488`e4d33128 fffff80e`d04d2275 : 00000000`00000000 fffff80e`d04f1e9d 00000000`00000000 00000000`00000000 : amdppm!WriteIoMemRaw+0xa8
ffffa488`e4d33130 fffff80e`d04d2365 : 00000000`00000000 00000000`00000000 00000000`00000000 ffffe406`2cf09310 : amdppm!WriteGenAddr+0x6d
ffffa488`e4d33160 fffff80e`d04fda42 : 00000000`00000000 00000000`000000d4 ffffe406`2ce22010 00000000`00000000 : amdppm!WriteGenAddrMaybeHidden+0x1d
ffffa488`e4d33190 fffff80e`d04f6f84 : ffffe406`2d11d920 fffff80e`d04df000 00000000`0007f077 00000000`00000000 : amdppm!InitAcpiCpc+0x2ce
ffffa488`e4d33200 fffff80e`d04f009d : 00001bf9`d30f6fd8 00001bf9`d30f6fd8 ffffa488`e4d33400 ffffe406`2cf09310 : amdppm!ProcLibDeviceStart+0x870
ffffa488`e4d33340 fffff800`0b857c27 : ffffe406`2cf08e58 ffffa488`e4d33400 ffffe406`2cf08e58 ffffa488`e4d33510 : amdppm!EvtDevicePrepareHardware+0xad
ffffa488`e4d33380 fffff800`0b7f0892 : 00000000`00000000 fffff800`0b7e3130 ffffa488`e4d334a0 ffffa488`e4d33460 : Wdf01000!FxPnpDevicePrepareHardware::InvokeClient+0x27 [minkernel\wdf\framework\shared\irphandlers\pnp\pnpcallbacks.cpp @ 347]
ffffa488`e4d333d0 fffff800`0b856d01 : 00000000`00000000 ffffe406`2cf09020 ffffa488`e4d334a0 ffffe406`2cf088b0 : Wdf01000!FxPrePostCallback::InvokeStateful+0x5a [minkernel\wdf\framework\shared\irphandlers\pnp\cxpnppowercallbacks.cpp @ 467]
ffffa488`e4d33410 fffff800`0b855891 : ffffe406`2cf08800 ffffe406`2cf088b0 ffffa488`e4d33510 00000000`00000108 : Wdf01000!FxPkgPnp::pnpPrepareHardware+0xfd [minkernel\wdf\framework\shared\irphandlers\pnp\pnpstatemachine.cpp @ 3601]
ffffa488`e4d33460 fffff800`0b85544b : ffffe406`2cf08801 00000000`00000100 ffffe406`2cf088b0 00000000`00000000 : Wdf01000!FxPkgPnp::pnpEventHardwareAvailable+0x51 [minkernel\wdf\framework\shared\irphandlers\pnp\pnpstatemachine.cpp @ 1399]
ffffa488`e4d334a0 fffff800`0b8571be : 00000000`00000002 ffffe406`2cf088b0 ffffe406`2cf088b0 00000000`00000004 : Wdf01000!FxPkgPnp::pnpEnterNewState+0x177 [minkernel\wdf\framework\shared\irphandlers\pnp\pnpstatemachine.cpp @ 1234]
ffffa488`e4d33530 fffff800`0b856f6e : 00000000`00000000 ffffe406`2cf08a10 ffffe406`2cf089e8 00000000`0000000c : Wdf01000!FxPkgPnp::pnpProcessEventInner+0x1e6 [minkernel\wdf\framework\shared\irphandlers\pnp\pnpstatemachine.cpp @ 1152]
ffffa488`e4d335b0 fffff800`0b85eece : 00000000`00000000 ffffe406`2cf088b0 00000000`0000001b 00000000`00000288 : Wdf01000!FxPkgPnp::pnpProcessEvent+0x19a [minkernel\wdf\framework\shared\irphandlers\pnp\pnpstatemachine.cpp @ 933]
ffffa488`e4d33640 fffff800`0b7dbc53 : ffffe406`2cf088b0 00000000`0000001b 00000000`00000288 00000000`00000000 : Wdf01000!FxPkgPnp::_PnpStartDevice+0x1e [minkernel\wdf\framework\shared\irphandlers\pnp\fxpkgpnp.cpp @ 2025]
ffffa488`e4d33670 fffff800`0b7e2c82 : ffffe406`2c5078a0 ffffe406`2cf09020 ffffe406`2cc11620 00000000`00000000 : Wdf01000!FxPkgPnp::Dispatch+0xb3 [minkernel\wdf\framework\shared\irphandlers\pnp\fxpkgpnp.cpp @ 765]
ffffa488`e4d336e0 fffff800`0d14deb9 : ffffa488`e4d33860 ffffe406`2cc11620 00000000`00000001 ffffe406`2cbf93e0 : Wdf01000!FxDevice::DispatchWithLock+0x112 [minkernel\wdf\framework\shared\core\fxdevice.cpp @ 1430]
ffffa488`e4d33740 fffff800`0d7cb556 : ffffe406`2a1ec870 ffffe406`2cbf93e0 00000000`00000000 00000000`00000000 : nt!IofCallDriver+0x59
ffffa488`e4d33780 fffff800`0d194dce : ffffe406`2a1ec870 00000000`00000000 ffffe406`2cbf93e0 fffff800`00000000 : nt!PnpAsynchronousCall+0xea
ffffa488`e4d337c0 fffff800`0d20b8ac : 00000000`00000000 ffffe406`2a1ec870 fffff800`0d1f9200 fffff800`0d1f9200 : nt!PnpSendIrp+0x5e
ffffa488`e4d33830 fffff800`0d7ca838 : 00000000`00000000 00000000`00000000 ffffe406`2cbf93e0 00000000`00000000 : nt!PnpStartDevice+0x88
ffffa488`e4d338c0 fffff800`0d7ca707 : ffffe406`2c2319a0 00000000`00000000 00000000`00000001 fffff800`0d1f9686 : nt!PnpStartDeviceNode+0xec
ffffa488`e4d33950 fffff800`0d7b6888 : ffffe406`2c2319a0 ffffa488`e4d33a18 00000000`00000001 00000000`00000001 : nt!PipProcessStartPhase1+0x6f
ffffa488`e4d339a0 fffff800`0d83d0f8 : ffffe406`2d197500 ffffa488`e4d33b01 ffffa488`e4d33ab0 fffff800`00000000 : nt!PipProcessDevNodeTree+0x3b0
ffffa488`e4d33a60 fffff800`0d21097e : 00000001`00000003 ffffe406`2d197570 ffffbd00`00000000 ffffe406`2d197570 : nt!PiProcessStartSystemDevices+0x60
ffffa488`e4d33ab0 fffff800`0d137945 : ffffe406`2c60a0c0 ffffe406`2a102a60 fffff800`0d515280 ffffe406`2a102a60 : nt!PnpDeviceActionWorker+0x45e
ffffa488`e4d33b70 fffff800`0d1d2135 : ffffe406`2c60a0c0 00000000`00000080 ffffe406`2a0b9380 00000000`00000001 : nt!ExpWorkerThread+0x105
ffffa488`e4d33c10 fffff800`0d27d9a8 : ffffbd00`5f440180 ffffe406`2c60a0c0 fffff800`0d1d20e0 00000000`00000000 : nt!PspSystemThreadStartup+0x55
ffffa488`e4d33c60 00000000`00000000 : ffffa488`e4d34000 ffffa488`e4d2e000 00000000`00000000 00000000`00000000 : nt!KiStartSystemThread+0x28

SYMBOL_NAME: amdppm!WriteIoMemRaw+a8

MODULE_NAME: amdppm

IMAGE_NAME: amdppm.sys

IMAGE_VERSION: 10.0.18362.693

STACK_COMMAND: .cxr 0xffffa488e4d32730 ; kb

BUCKET_ID_FUNC_OFFSET: a8

FAILURE_BUCKET_ID: AV_amdppm!WriteIoMemRaw

OSPLATFORM_TYPE: x64

OSNAME: Windows 10

FAILURE_ID_HASH: {05b9e458-6c10-43a8-4dc2-664f23edafb4}

Followup: MachineOwner
--------- `

**Comment by RAJU2529** [comment]
@rugabunda . Disable secure launch in group policy. Keep only VBS . 
Recheck the result using dg tool.

Boot the windows into safemode and cut all the problematic .sys files , paste those files in  to other location say D:\backupsys\

Note:: before cutting or moving those.sys files you must take ownership of files and folders

**Comment by rugabunda** [comment]
i had removed all drivers and had the same bsod.  for whatever reason NX protection started working by itself and the issue fixed itself without any changes on my behalf
