### ISSUE TITLE
Whitelist Intune as Manage Installer

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#7046]
How can the Intune Management Extension be added as a managed installer so only applications deployed by it are automatically whitelisted??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07fdf27b-1ead-1b6e-c793-a2ad259a4f6a
* Version Independent ID: 8da1f371-73d4-c79f-a97b-80170e7860af
* Content: [Authorize apps deployed with a WDAC managed installer (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-managed-installer)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-managed-installer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-managed-installer.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
The issues section of this repository is used for documentation fixes.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
