### ISSUE TITLE
Discrepancy in paths at DMClient page and ddf files.

### ISSUE THREAD

**Issue by Harmyder** [MicrosoftDocs/windows-itpro-docs#7049]
At the page address of DMClient is ./Vendor/MSFT/DMClient but in the corresponding ddf file it is both ./User/Vendor/MSFT/DMClient and ./Device/Vendor/MSFT/DMClient.

As per [User targeted vs. Device targeted configuration](https://docs.microsoft.com/en-us/windows/client-management/mdm/oma-dm-protocol-support#user-targeted-vs-device-targeted-configuration)

> By default, if no prefix with ./device or ./user, it is device targeted configuration.

From this, I infer that ./Vendor would rather map to ./Device/Vendor but not to ./User/Vendor. So it makes the matter even more confusing.

When I set all three possible addresses, I see that they all aliases, but is it always true?

    <LocURI>./Vendor/MSFT/DMClient/Provider/MCConfigMgr/Push/PFN</LocURI>
    <LocURI>./User/Vendor/MSFT/DMClient/Provider/MCConfigMgr/Push/PFN
    <LocURI>./Device/Vendor/MSFT/DMClient/Provider/MCConfigMgr/Push/PFN</LocURI>

I use your ddf files to generate a management tree for testing purposes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 613a93fe-ef09-40aa-f088-a476c4de4214
* Version Independent ID: a9efe92b-dd9a-e4a3-9e99-cb16f5a1af11
* Content: [DMClient CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/dmclient-csp)
* Content Source: [windows/client-management/mdm/dmclient-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/dmclient-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
@Harmyder : Thank you for providing feedback to the MS Docs articles.

Did you close this issue ticket by mistake, or would you like to add a closing comment to explain why it should be closed?

**Comment by Harmyder** [comment]
@illfated while adding information to the issue after creation I found all answers I needed. Though I think that it would be useful to clarify at the page that DMClient is available for both User and Device. Thank you.

**Comment by illfated** [comment]
Thank you for the additional feedback. Fair enough. We may want to look into that.

@ManikaDhiman : Do you find the feedback useful enough to reopen the ticket, in case it can be used to add improvements to the document?

**Comment by ManikaDhiman** [comment]
@illfated: Yes, it would be good to reopen the ticket to update the doc per the feedback. I have already reached out to the policy owner to confirm the update. I will update the doc as soon as I hear from them. Thanks!

**Comment by illfated** [comment]
@Harmyder : You are welcome to reopen this ticket to make it easier for us to track the progress.

**Comment by illfated** [comment]
Thanks. 👍

**Comment by ManikaDhiman** [comment]
Per inputs from the product team, added a section for ."/Vendor/MSFT" in the [DMClient CSP doc](https://docs.microsoft.com/en-us/windows/client-management/mdm/dmclient-csp). The DDF updates are being tracked by the product team internally. The [DMClient DDF file doc](https://docs.microsoft.com/en-us/windows/client-management/mdm/dmclient-ddf-file) will be updated when the updates are available in the actual DDF file. 

@e0i: Please review and close this issue. Thanks!

**Comment by illfated** [comment]
Thank you for the update. That looks like good news to me. I am glad to see that the information was useful enough to keep this ticket alive a bit longer.

**Comment by ManikaDhiman** [comment]
Closing this issue as the required updates have been added to the doc.
