### ISSUE TITLE
"Installing an application package with the Device Portal" is out of date

### ISSUE THREAD

**Issue by WikkidEdd** [MicrosoftDocs/windows-itpro-docs#7054]
There are a few things that aren't as clear as they could be due to being related to an older version of the device portal.

"In the left navigation, navigate to the Apps page ." - This is now found under Views -> Apps

"Under App Package browse to the .appx file that is associated with your application" - There is no reference to App Package in the current version of device portal UI and the latest version of the Hololens 2 OS also supports msix.

Screenshot it out of date

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa5bcb46-0ea7-d1a8-3c77-ef809c8be0ff
* Version Independent ID: d9e3557b-084f-5a32-a8df-d8e97df43d49
* Content: [Manage custom apps for HoloLens](https://docs.microsoft.com/en-us/hololens/holographic-custom-apps)
* Content Source: [hololens/holographic-custom-apps.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/holographic-custom-apps.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by evmill** [comment]
@Sean-Kerawala / @hferrone I'm aware this page is outdated on our side, do you have a page that is more current? Trying to gauge if updates are needed in this repo or if yours is current point references there.

**Comment by hferrone** [comment]
I'm honestly not sure @evmill, might have to ping @mattzmsft for more info?

**Comment by evmill** [comment]
@hferrone Looks like mixed-reality has a section.
https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-device-portal#apps
I think it's fair to update the page this issue calls out with the issues it calls out. I also believe we should isolate the VS2015 to HL1 and then list the new recommended versions from Install the Tools for HL2.
This will probably land on my plate.

**Comment by hferrone** [comment]
@evmill  Sounds good to me.

**Comment by evmill** [comment]
Page in /hololens is updated to link to /mixed-reality which has the newest info for HL2.
