### ISSUE TITLE
Discrepancy in access type for ./Vendor/MSFT/Provider/ProviderID/Push/PFN

### ISSUE THREAD

**Issue by Harmyder** [MicrosoftDocs/windows-itpro-docs#7061]
The page states the following:

> Provider/ProviderID/Push/PFN   
> ...   
> Supported operations are Add, Get, and Replace.

But corresponding [DMClient DDF file](https://docs.microsoft.com/en-us/windows/client-management/mdm/dmclient-ddf-file) states this:

            <NodeName>PFN</NodeName>
            <DFProperties>
              <AccessType>
                <Add />
                <Delete />
                <Get />
                <Replace />
              </AccessType>

When I tried, to send Delete Command. The device returned OK, but the node was still accessible. So, it looks like Delete doesn't work.

_I use your ddf files to generate a reference management tree for my test framework and it would be nice if I could rely on them._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 613a93fe-ef09-40aa-f088-a476c4de4214
* Version Independent ID: a9efe92b-dd9a-e4a3-9e99-cb16f5a1af11
* Content: [DMClient CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/dmclient-csp)
* Content Source: [windows/client-management/mdm/dmclient-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/dmclient-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@Harmyder 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published with PR #7897.

Thanks for your feedback.
