### ISSUE TITLE
Case mismatch w/ ddf file CertificateStore CSP

### ISSUE THREAD

**Issue by Harmyder** [MicrosoftDocs/windows-itpro-docs#7062]
E.g. My - MY and Root - ROOT

Actually OMA requires the following:

> _URI used in SyncML DM MUST be treated and interpreted as case sensitive._   
> From: SyncML Device Management Tree and Description, Version 1.1.2

If it is not the case for Windows MDM, it would be nice to mention it somewhere in [OMA DM protocol support](https://docs.microsoft.com/en-us/windows/client-management/mdm/oma-dm-protocol-support)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3255266f-dbeb-d8fc-0653-eaa8aa9041e0
* Version Independent ID: 7f527c79-48e4-74cd-e102-ad87c96de6c2
* Content: [CertificateStore CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/certificatestore-csp)
* Content Source: [windows/client-management/mdm/certificatestore-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/certificatestore-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
@Harmyder - Thank you for your feedback. I need a few clarifications before making any changes. Can you please confirm that My and Root mention in the CertificateStore CSP https://docs.microsoft.com/en-us/windows/client-management/mdm/certificatestore-csp where it is a case sensitive works as expected or we need to make changes in CertificateStore CSP page. 

Please share your insight so that I can proceed with changes.

Thanks
Imran.

**Comment by Harmyder** [comment]
@joinimran From my experience Windows MDM protocol is case insensitive, so it doesn't matter MY of My. But this feature of Microsoft protocol version doesn't get mentioned anywhere and this is confusing a bit because OMA protocol is case-sensitive.

**Comment by joinimran** [comment]
@Harmyder - this means that we need to mention a note stating that Microsoft protocol version of OMA is case insensitive. 

Is this correct?

**Comment by Harmyder** [comment]
@joinimran Yes, I think so.

**Comment by e0i** [comment]
@Harmyder 

Upon your feedback, The content has been updated with relevant changes. See PR: #7959. Thanks.
