### ISSUE TITLE
Compatible Windows version unclear

### ISSUE THREAD

**Issue by lechku** [MicrosoftDocs/windows-itpro-docs#7068]
Hi!
I was reading this article at docs. microsoft.com and it statest that the policy "Specify deadlines for automatic updates an retarts" is recommended for Windows 10 versions 1709 and above.

If I want to deploy this setting via GPO, it states this GPO is supported on "At least Windows Server 2016, Windows 10 Version 1903". Github file confirms this. Can you update the official page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44aabe97-360e-0655-09ec-5d1e352bdb1a
* Version Independent ID: 1c729c42-741d-ecb7-6490-a4bfdd029263
* Content: [Erzwingen von Compliance-Terminen mit Richtlinien in Windows Update for Business (Windows 10) - Windows Deployment](https://docs.microsoft.com/de-de/windows/deployment/update/wufb-compliancedeadlines)
* Content Source: [windows/deployment/update/wufb-compliancedeadlines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/wufb-compliancedeadlines.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@arcarley can you confirm or advise?

**Comment by arcarley** [comment]
@lechku the Group Policy template unfortunately is just showing what release this policy was added in (1903), but we in fact backported this policy to 1709 and below to ensure all customers have access to such. You can set this policy for any device on 1709 and above. I will work to get the template versions allowed adjusted accordingly.

**Comment by lechku** [comment]
@arcarley Thank you for this clarification! 
So changing my 1809 GPO should work?  I  do not need to modify the .admx first, right?

**Comment by arcarley** [comment]
Correct, any 1809 device should be able to have the "Specify deadlines for automatic updates and restarts" policy set on it. (It should even be available in local GP or you can use the newer ADMX templates)

**Comment by e0i** [comment]
Closing via the answers above. Thank you.
