### ISSUE TITLE
Does the client machine need to be joined to the same AAD domain

### ISSUE THREAD

**Issue by SvenAelterman** [MicrosoftDocs/windows-itpro-docs#7070]
The article states that both systems must be joined to Azure AD. It might be implied that they must be joined to the same AAD tenant, but it should be explicit if that's the case. An MSP might want to connect to their customers' systems. In that scenario, the client at the MSP side would be joined to the MSP's AAD instance, and the customer's RDP host would be joined to the customer's instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10) - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @SvenAelterman ,
**It might be implied that they must be joined to the same AAD tenant, but it should be explicit if that's the case.** - it stated in the TIP section in the article:
![image](https://user-images.githubusercontent.com/48041687/87787371-f3b8bd00-c854-11ea-9fde-ecb6d886f657.png)
Thank you

**Comment by SvenAelterman** [comment]
@MaratMussabekov Thanks... I missed that :(
