### ISSUE TITLE
Good information, but...

### ISSUE THREAD

**Issue by upmyoung** [MicrosoftDocs/windows-itpro-docs#7071]
It doesn't belong here. The Azure AD join process is not unique to Hello for Business, and no one would ever look for it here. This belongs in a section dedicated to Windows (and Azure) authentication and user/device identity, such as https://docs.microsoft.com/en-us/azure/active-directory/devices/ , although that section is woefully incomplete as well. This should also be combined with the section on windows authentication here https://docs.microsoft.com/en-us/windows/win32/secauthn/authentication-portal and here https://docs.microsoft.com/en-us/windows-server/security/windows-authentication/windows-logon-scenarios, as well as a host of other tidbits you've got squirreled away, to make clear and complete description of how the components of authentication and credentialing work together in the modern age of Azure and Windows 10. It's a nice story. You're not doing yourselves any good by hiding it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96185909-5825-db9a-cc04-4045f6dc577e
* Version Independent ID: 9340a575-af61-9c73-7701-702fff99f524
* Content: [How Windows Hello for Business works - Device Registration - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-device-registration#hybrid-azure-ad-joined-in-managed-environments)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-how-it-works-device-registration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-how-it-works-device-registration.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mapalko** [comment]
@upmyoung can you clarify your feedback on https://docs.microsoft.com/en-us/windows/win32/secauthn/authentication-portal and here https://docs.microsoft.com/en-us/windows-server/security/windows-authentication/windows-logon-scenarios? Is the ask to include general WHFB authentication information on these pages?

Those changes are unrelated from your feedback to move the device registration diagrams, correct?

**Comment by e0i** [comment]
@upmyoung Closing because there hasn't been any response from your side regarding details of the defect in the documentation. Feel free to re-open to follow up. Thank you, and stay healthy.
