### ISSUE TITLE
The context of the note and its usage of 'What we deploy *at Microsoft*' is open to interpretation

### ISSUE THREAD

**Issue by 1RedOne** [MicrosoftDocs/windows-itpro-docs#7081]
The meaning of this note is not clear to us.

> Note

>Automatic exclusions apply only to Windows Server 2016 and above. *The default antimalware policy we deploy at Microsoft doesn't set any exclusions by default.*

Does this refer to the default policy one gets with Windows Defender built into Windows?  If there are default exclusions, why aren't they visible within the UI on Windows 10 **Settings \ Virus and Threat protection \ Exclusion** 

To double check, I cross-referenced with a Server 2016 VM on the newest patch and the Exclusion list is empty there too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c0eddd-98ca-1e7a-bddb-36c7037850fe
* Version Independent ID: 6afa98e8-a402-4ef9-2189-8ecc111c3dba
* Content: [Configure and validate exclusions based on extension, name, or location - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-extension-file-exclusions-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/configure-extension-file-exclusions-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/configure-extension-file-exclusions-microsoft-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by MaratMussabekov** [comment]
Hello @1RedOne ,
these exclusions are not visible by design. 
I will create a PR to change a Note section.
Thank you
