### ISSUE TITLE
Typo in Windows Insider Release docs

### ISSUE THREAD

**Issue by sshiv** [MicrosoftDocs/windows-itpro-docs#7082]
In page https://docs.microsoft.com/en-us/hololens/hololens-insider?source=docs#windows-insider-release-notes
Under Windows Insider Release Notes 
there is a typo in the word "available" & features

As of our Windows Holographic May 2020 Update release all of our release preview feautres [features] are now generally avalible [available]!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dafbb989-d1f4-0411-81ce-f761e83bdeba
* Version Independent ID: e8fdf590-c7f0-6b07-9407-33bdf2ca7453
* Content: [Insider preview for Microsoft HoloLens](https://docs.microsoft.com/en-us/hololens/hololens-insider?source=docs#windows-insider-release-notes)
* Content Source: [hololens/hololens-insider.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-insider.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by illfated** [comment]
There you go. PR https://github.com/MicrosoftDocs/Hololens/pull/2 is now available(!) for review.

**Comment by illfated** [comment]
At first, I was surprised that the HoloLens pages don't produce tickets in their own repository, given that the Pull Requests are placed in the HoloLens repository. 
Then again, I presume that issues may gain a wider audience when they are posted to the Windows IT-Pro Docs issue ticket repository.
