### ISSUE TITLE
What happens when we still use DHA Service V1 url 

### ISSUE THREAD

**Issue by jigargandhi** [MicrosoftDocs/windows-itpro-docs#7085]
We are currently using v1 version of DHA service url. Should we deprecating it? Is it going to be obsoleted?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b523bfc-d44c-c8dd-30ef-3322b7a74dfe
* Version Independent ID: 16f7a003-3ac8-cc87-6a9d-122a11d796f4
* Content: [Device HealthAttestation CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/healthattestation-csp#dha-report-v3-schema)
* Content Source: [windows/client-management/mdm/healthattestation-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/healthattestation-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@jigargandhi 

The issues section of this repository is intended for documentation and content-related issues.

It seems that this question can best be answered via [Windows 10 Support Channels](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

You may open a support ticket via the link above for your question.

The issues section of this repository is for content fixes regarding documentation. Feel free to re-open in case you would like to suggest improvements to the article itself.

Thank you.
