### ISSUE TITLE
Configuration manager CB should be mentioned instead of 2012 R2

### ISSUE THREAD

**Issue by Yupiter2005** [MicrosoftDocs/windows-itpro-docs#7087]
WDATP Onboarding hasn't been introduced in 2012 R2 (released back in 2013). This was done only in ConfigMgr 1910 released in 2019/12

**Comment by e0i** [comment]
@Yupiter2005 Can you provide a link to the article that this problem stems from? Thank you.

**Comment by e0i** [comment]
@Yupiter2005 Please feel free to re-open this issue with a clarification about which article this issue stems from. Thank you.
