### ISSUE TITLE
Who to contact?

### ISSUE THREAD

**Issue by msnriggs** [MicrosoftDocs/windows-itpro-docs#7088]
Who to contact to get started with an integration partnership is not clear. Thie linked pages do not include any way to contact Microsoft or apply for partnership.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afd513c3-d291-0e1e-d904-acf7c9f66765
* Version Independent ID: c1490bb4-5d49-5529-630f-0a13d99b5e77
* Content: [Become a Microsoft Defender ATP partner - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/get-started-partner-integration)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/get-started-partner-integration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/get-started-partner-integration.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
To me, it looks like it is mandatory to go through the 4 steps listed on the page.
1. Subscribe to a Microsoft Defender ATP Developer license (https://winatpregistration-prd.trafficmanager.net/Developer/UserAgreement?Length=9)
2. Have a **joint customer approve the suggested integration design** and have it **tested and demoed to the Microsoft Defender ATP team**
3. Become a Microsoft Intelligent Security Association (MISA) member (https://www.microsoft.com/security/partnerships/intelligent-security-association)
4. Get listed in the Microsoft Defender ATP partner application portal (Notice the detailed description of this step, it lists several tasks to complete.)

**Comment by e0i** [comment]
@msnriggs Please let us know whether the commentary above answers your question. Thank you.
