### ISSUE TITLE
Windows ATP Alerts extremely slow to come in

### ISSUE THREAD

**Issue by jmcadams-r7** [MicrosoftDocs/windows-itpro-docs#7089]
I'm using ATP in a test lab, and alerts are very slow to come in. It's a defender ATP instance hooked up to one machine. Using EICAR test files and the PowerShell script to trigger alerts will create a new alert in the ATP dashboard, but they can take up to hours to show up. 

Is there anything I can do to speed that up? 

(The VM I'm running is on gigabit fiber, so I don't think this is a network speed issue). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 578a2a0c-d8ec-de9f-0a2a-450d1087ecf7
* Version Independent ID: 14b80f24-ed8e-9b63-d3f6-85852467b679
* Content: [Manage Microsoft Defender Advanced Threat Protection alerts - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/manage-alerts)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/manage-alerts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/manage-alerts.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Depending on how much time it takes for any useful reply & follow-up from a topic-savvy MS Docs team member to arrive here, you may want to consider joining and posting your question in the Tech Community section for Microsoft Defender Advanced Threat Protection: https://techcommunity.microsoft.com/t5/microsoft-defender-advanced/ct-p/MicrosoftDefenderAdvanced

I also hope you are aware that this repository is originally intended as a reporting instance for errors, improvement suggestions, or update/modernization requests for the Microsoft documentation pages.

I know, sometimes you may get a useful answer from one of the team members, but it is also a very good chance that this can take a lot of time, depending on the importance of your issue ticket content compared to the existing documentation content and any need for it to be updated or changed, based on the resulting outcome of your question.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

**Comment by e0i** [comment]
@jmcadams-r7 

As mentioned by *illfated,* Please consider sending your input via the Feedback Hub so that it gets addressed via the proper channels:

[Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

The issues section of this repository is for content fixes regarding documentation. Feel free to re-open in case you would like to suggest improvements to the article itself.

Thanks again.
