### ISSUE TITLE
Specifying the maximum percentage of CPU utilization during a scan, for Windows Defender, does nothing at all.

### ISSUE THREAD

**Issue by vorrin** [MicrosoftDocs/windows-itpro-docs#7092]
The local policy for setting the maximum CPU usage that Windows Defender can obtain, during a scan... flat out doesn't work. 
There are vast tutorials all over the place, on how to set said policy up, and yet, after doing so, on a Windows 10 Pro, using an i5-6600k processor, having admin etc etc etc, it flat out does nothing. Windows Defender keeps hogging however much CPU it decides it needs, and that's that. 

So this is the worst kind of option, hidden, entrail-y looking, well documented both in the group policy manager and on the internet, yet a complete placebo. 

Is it temporarily broken, is it broken on my machine only, am I doing something wrong, or was it just documented but never implemented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ede71cb-45c3-0fb4-31e7-3538a0eaffb5
* Version Independent ID: 7c295a83-b94a-76ec-4e42-4388c4358170
* Content: [Configure scanning options for Microsoft Defender AV - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-advanced-scan-types-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/configure-advanced-scan-types-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/configure-advanced-scan-types-microsoft-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation feedback.

Please consider opening a support ticket via the following link for your question for an answer.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Feel free to re-open this ticket if you feel that documentation content also needs to be updated.

Thank you.
