### ISSUE TITLE
Licensing requirements incorrect

### ISSUE THREAD

**Issue by davebirr** [MicrosoftDocs/windows-itpro-docs#7094]
**Incorrect portion:**
Microsoft Defender Advanced Threat Protection requires one of the following Microsoft Volume Licensing offers:

Windows 10 Enterprise E5
Windows 10 Education A5
Microsoft 365 E5 (M365 E5) which includes Windows 10 Enterprise E5
Microsoft 365 E5 Security
Microsoft 365 A5 (M365 A5)

**Correction:**
Microsoft Defender Advanced Threat Protection is also available for purchase from a Cloud Solution Provider (CSP).  When purchased via CSP it does not require Microsoft Volume Licensing offers listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
Closing via #7925
