### ISSUE TITLE
Wrong text description

### ISSUE THREAD

**Issue by theme-me** [MicrosoftDocs/windows-itpro-docs#7099]
There is an error in the first paragraph of the Chinese description. For details, please refer to the red box in the picture. "赚钱钱" should be changed to "赚钱"
![image](https://user-images.githubusercontent.com/33180458/86751364-30283400-c071-11ea-9dc3-80cd5b479140.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a844e3a3-52b3-1497-0ac7-b4c57b0df714
* Version Independent ID: 6a96c9cb-9ad0-9af9-a00c-eedf41d3ebee
* Content: [Coin miner - Windows security](https://docs.microsoft.com/zh-cn/windows/security/threat-protection/intelligence/coinminer-malware#feedback)
* Content Source: [windows/security/threat-protection/intelligence/coinminer-malware.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/intelligence/coinminer-malware.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **levinec**

**Comment by TinaMcN** [comment]
@theme-me, thank you for the feedback.
@officeGlobal, please human translate this article for Chinese-Simplified and check that this error is fixed. 
@e0i can you please also assign this to @officeGlobal.

**Comment by OfficeGlobal** [comment]
@theme-me , @TinaMcN article was HumanTranslated and published live
