### ISSUE TITLE
Windows 10 x64 updates failing systematically for 4 months already

### ISSUE THREAD

**Issue by Arno2m** [MicrosoftDocs/windows-itpro-docs#710]
List of cumulative updates failing one after another, both through update functionality, and when downloaded from Microsoft portal and launched independantly:
2018-04 KB4093112: failure 0x80092004
2018-03 KB40088776: failure 0x80092004
2018-02 KB4074588: failure 0x80073715
2018-01 KB4058258: failure 0x8007315
I tried Microsoft helpdesk online.... but after several attempts, they did not solve it, and even the last operator closed the call, not only leaving me with problem unsolved, but even without saying goodbye, or sorry, or that they would need to work on it.
I left a comment when Microsoft sent me their Customer Satisfaction Survey, but no-one ever came back to me...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a97de48f-e863-7786-5958-c76a831486e5
* Version Independent ID: b0dc0baf-e3d0-fba5-e2ac-9c6de32e4aab
* Content: [Submit Windows 10 upgrade errors using Feedback Hub](https://docs.microsoft.com/en-us/windows/deployment/upgrade/submit-errors)
* Content Source: [windows/deployment/upgrade/submit-errors.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/submit-errors.md)
* Service: **unspecified**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by andreabichsel** [comment]
Please submit this issue with the Feedback Hub (see https://docs.microsoft.com/en-us/windows/deployment/upgrade/submit-errors). Thank you!

**Comment by Zinou16** [comment]
Hi,
I've tried to upgrade from Windows 10 1703 version to 1809, but after the second boot, the setup process cancels and start restoring the old OS. the error code is **0xC1900101 - 0x4001E**.
The setupact.log shows this entries;
"**FatalError [0x090001] PANTHR Exception (code 0xC0000005: ACCESS_VIOLATION) occurred at 0x00007FFFB4C75087 in C:\Windows\System32\provengine.dll (+0000000000005087).  Minidump attached (107228 bytes) to diagerr.xml and C:\Windows\Panther\mndA758.diagerr.mdmp.**"
"**SETUPPLATFORMCOMM: Progress message received: Phase: OOBE Boot, Operation: Unknown, Percentage: 47%**"
"**SP     WINDEPLOY error code is 0x80004005. Will not attempt uninstall**"

Thanks for your help.

**Comment by illfated** [comment]
@Zinou16 : 13000 pages filled with suggestions on how to deal with that problem:
https://www.bing.com/search?q=FatalError+%5B0x090001%5D+PANTHR+Exception+%28code+0xC0000005%3A+ACCESS_VIOLATION%29+occurred+at
(removing temporary files and old install folders are among the suggested fixes)
