### ISSUE TITLE
Step 3 under "Uninstall Symantec" about SEP Manager is not accurate?

### ISSUE THREAD

**Issue by blakebourgeois** [MicrosoftDocs/windows-itpro-docs#7102]
It appears that the guidance in Broadcom's article does not do what is proposed here.

It is possible to create an install package that does uninstall all current and old installs of Symantec and all of it's components. However, it only does this in the scope of an pre-installation package. After the uninstall, the installation of SEP proceeds as normal. There is no way within SEPM to create an uninstall only package. It may be possible to rig something up in which you kill the installation after the initial reboot, but the guidance doesn't seem to be complete or accurate. I've gone through this within SEPM and cannot replicate the claim within the article of using SEPM to uninstall SEP in support of a MDATP transition. 

At this point it appears the only reliable methods are to uninstall the program directly or to use wmic uninstall or some other similar method to automate it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97bdf3fb-4957-9040-5cae-af5ce734f260
* Version Independent ID: 70c59e7e-4fc5-a20f-0705-a0cbb35f10fd
* Content: [Phase 3 - Onboard to Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-onboard)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-onboard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-onboard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thank you @blakebourgeois for your helpful feedback. I'll look into this and will get the content updated soon.

**Comment by denisebmsft** [comment]
Hello again @blakebourgeois. I've updated the article and changes will go live later today. Thank you again for your feedback.
