### ISSUE TITLE
Dead Devices

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/windows-itpro-docs#7105]
Could we have some guidance on how to remove devices that are dead, stolen, not able to be "offboarded" in the normal manner?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25f5ab5a-e755-9139-83c5-d6192b9a3e91
* Version Independent ID: 6e93cf86-0e83-5282-f659-e535c4ac35e2
* Content: [Offboard devices from the Microsoft Defender ATP service - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/offboard-machines)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/offboard-machines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/offboard-machines.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@mjcaparas We consider this issue to be an editorial feedback that would be worth your attention. Please let us know whether we can help in coming up with a PR. Thank you.

**Comment by mjcaparas** [comment]
@mattsmacblog - For scenarios where the machine is dead, stolen etc, it might be best to look into endpoint management solutions such as  MDM.

Detailed offboarding instructions for typical scenarios are covered for each management tool: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints

**Comment by mattsmacblog** [comment]
Sure but this makes the product less valuable as having a ton of stale/inactive entries that are counting towards you stats that you're unable to get rid of is quite annoying.  I already have a duplicate entry for the exact same device and I can't get rid of the inactive duplicate.  

It seems like a basic feature to be able to delete devices you know aren't coming back...  Water Damaged, Stolen, got wiped and reloaded with a different OS etc...
