### ISSUE TITLE
DHCP Option ID 234 is wrong

### ISSUE THREAD

**Issue by hzjfans** [MicrosoftDocs/windows-itpro-docs#7107]
[Enter feedback here]
DHCP Option ID is 235 not 234.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df445cda-3b0a-2ad7-e3cc-23e159013530
* Version Independent ID: a6bb5f97-d350-f7b7-77f7-b0093322289d
* Content: [Delivery Optimization reference - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization-reference#feedback)
* Content Source: [windows/deployment/update/waas-delivery-optimization-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-delivery-optimization-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Did you know you can make simple edits like this yourself? Just select the "Edit" button (right next to the "Feedback" button) and make the fix. We'll welcome the contribution.
