### ISSUE TITLE
SCCM Only

### ISSUE THREAD

**Issue by alanburchill** [MicrosoftDocs/windows-itpro-docs#7108]
This page seems to be very SCCM focused.... how can i rollout these options with Intune?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08d16473-db61-23bd-7201-f5d7d6a56cc8
* Version Independent ID: 468238c8-8fb4-3dff-3485-07daab0c7833
* Content: [Onboard to the Microsoft Defender ATP service - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/onboarding)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/onboarding.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/onboarding.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by joinimran** [comment]
Hello @alanburchill - Thank you for your query, please see [Enforce compliance for Microsoft Defender ATP with Conditional Access in Intune](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection) and [Configure Microsoft Defender ATP in Intune](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-configure) for details regarding deployment of Microsoft Defender ATP in Intune.

Thanks
Imran.
