### ISSUE TITLE
Windows 10 editions feature comparison out of date

### ISSUE THREAD

**Issue by dianagrig03** [MicrosoftDocs/windows-itpro-docs#7110]
Hello, 

The Windows editions feature comparison presented in the article: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2O8jv is not up to date (shows last update in 2019) and does not include the additions that the Defender ATP standalone license brings for the Windows 10 Pro editions.

I have found indeed this: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PBG7 and I was wondering if this is the official upgraded version.

Thank you for all your help – it is much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by joinimran** [comment]
@dianagrig03 - Thank you for your query. Please note that this information is available as a note in the document. Please see the attached screenshot. If there is any clarification needed, please do let me know.

![image](https://user-images.githubusercontent.com/47118050/88471276-fb492780-cf20-11ea-9001-ab501e823a2a.png)
