### ISSUE TITLE
Links to ignite 2018 talks do not work

### ISSUE THREAD

**Issue by stevensnicole** [MicrosoftDocs/windows-itpro-docs#7111]
Had hoped to check out one of the talks. Unfortunately it looks as if the 2018 Ignite content has either been moved or removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d316fa-6a88-682f-c517-c7e470c8d1c9
* Version Independent ID: 29856db9-5019-5a31-0f1b-feee833a6044
* Content: [Windows as a service - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-as-a-service)
* Content Source: [windows/deployment/update/windows-as-a-service.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-as-a-service.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
It is possible to look up those sessions, but not directly via those links.
1. Start on the page https://myignite.techcommunity.microsoft.com/sessions (might change dynamically)
2. Browse a few pages ahead, maybe 4 or 5.
3. Search for the unique keyword from the link you want to visit.
4. Open the search result.

2 first link results from my own searches:

- https://myignite.techcommunity.microsoft.com/sessions/81009?source=sessions
- https://myignite.techcommunity.microsoft.com/sessions/81010?source=sessions

I hope this will help you to find those videos you would like to watch.

**Comment by stevensnicole** [comment]
@illfated 
Many thanks for the links, have had a good trawl through them !
