### ISSUE TITLE
Block persistence through WMI event subscription | Not available in Intune

### ISSUE THREAD

**Issue by AlphaSeb** [MicrosoftDocs/windows-itpro-docs#7112]
Block persistence through WMI event subscription is NOT available in Intune. Please update the article.

Quote from MS Intune Support:

My name is --- , the Senior Support Professional who will be working with you on this Service Request. You may reach me directly using the contact information mentioned in the signature, referencing the case number 20349519

As discussed, this feature is yet not available in Intune. But you can try to deploy it as XML or PowerShell to the devices from Intune for now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d747289-63b2-f71a-b40c-31b52982215c
* Version Independent ID: b52f6593-03f2-aa57-ec0e-eaef560dcaf0
* Content: [Use attack surface reduction rules to prevent malware infection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction#block-persistence-through-wmi-event-subscription)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by joinimran** [comment]
@AlphaSeb - Thank you for your query. Please note that this information is already available in the document. Please see the attached screenshot.

![image](https://user-images.githubusercontent.com/47118050/88463478-7c2a0400-cecc-11ea-96e6-82ae0e8ef35e.png)
