### ISSUE TITLE
windows 10 v2004 admx link needed

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#7114]
Lastest  admx templates for windows 10 v2004 link needs to be  added 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65d57fa8-9c9b-63cc-7248-175242963432
* Version Independent ID: 9cd96c93-8f46-64db-a162-02da1e1f63cc
* Content: [Hide notifications from the Windows Security app - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications)
* Content Source: [windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Hi @RAJU2529 and thank you for your help with this. Issue resolved, yes?
