### ISSUE TITLE
in windows 10 v2004 path is different 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#7116]
I like to add a path for windows 10 v2004, Windows Defender Security Center is renamed to Windows Security.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65d57fa8-9c9b-63cc-7248-175242963432
* Version Independent ID: 9cd96c93-8f46-64db-a162-02da1e1f63cc
* Content: [Hide notifications from the Windows Security app - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications)
* Content Source: [windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-security-center/wdsc-hide-notifications.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Thank you @RAJU2529! Issue resolved, yes? I am going to close it but please let us know if this is not correct.
