### ISSUE TITLE
Images in document are out of date

### ISSUE THREAD

**Issue by vegarjb** [MicrosoftDocs/windows-itpro-docs#7120]
The screen shots do not reflect the current day reality. They are old and from a FAT client

**Comment by denisebmsft** [comment]
Hello @vegarjb, can you please tell us to which article(s) your feedback applies? It will help us route this issue correctly. Thank you!

**Comment by e0i** [comment]
@vegarjb Please feel free to re-open this issue by following up with the source of the article that this problem stems from. Thank you.
