### ISSUE TITLE
Update WhileGlove Requirements 

### ISSUE THREAD

**Issue by naylormat** [MicrosoftDocs/windows-itpro-docs#7121]
On fighting to test while glove on a rebuilt laptop we ran into an issues where you cannot enter provisioning mode if the AutoPilot profile specifies a langue selection.  
In this situation, the Language and region where set as part of the OS install, meaning that on booting the laptop did non prompt the user for a language, keyboard or region and instead went straight to the autopilot login screen, preventing us from entering into the White Glove provisioning options.  

Setting the Langue / Region in the Autopilot profile corrected this issue, enabling the provisioning mode to be selected though the use of the Windows key. 

This should be clarified in the White Glove documentation to ensure the Langue mode is set to user specified, or provide other way to enter the provisioning menu from the AutoPilot sign in screen 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5b57d1-61b3-39d4-34ff-d6dcb858c250
* Version Independent ID: 42609104-815f-9e7a-39aa-38d92cc910c9
* Content: [Windows Autopilot for white glove deployment - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove)
* Content Source: [windows/deployment/windows-autopilot/white-glove.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/white-glove.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Hi,

Can I get some clarification here?

In the first sentence you said that provisioning mode is blocked if there is a language specified in the Autopilot profile, but in the second paragraph you said that setting the language in the profile corrected the issue.

When you say "provisioning mode" are you referring to the [technician flow]([url](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove#technician-flow)) or the [user flow](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove#user-flow)?

Thanks,
-Greg

**Comment by naylormat** [comment]
Hi,


To clarify what I mean, is that if you administratively set a language via
autopilot profiles, the second step in the technician flow is skipped, and
goes automatically to the 4th user flow step ( the branded sign in screen )
without anyway to enter into the white glove provisioning mode.

Removing the pre set language from the auto pilot profiles enables the user
to select there own language, and thus enables a technician to enter  the
white glove provisioning mode.

While the documentation Alludes to this requirement, it would help to
clarify the requirement to NOT pre specify any languages in the autopilot
profile for white gloving to work

Cheers,
Mat

**Comment by joinimran** [comment]
@naylormat - Just to clear one more thing, Can have you tired pressing Windows key for 5 times to enter in the technician provisioning mode.

**Comment by naylormat** [comment]
Yep, tried - once at the login prompt you cannot enter into the technician
provisioning mode

**Comment by e0i** [comment]
Closing via #7984
