### ISSUE TITLE
Standalone Defender ATP Requirements?

### ISSUE THREAD

**Issue by kyjeeper** [MicrosoftDocs/windows-itpro-docs#7125]
[Enter feedback here]
Can there be clarification on the requirements for Defender ATP now that there is a standalone license SKU that no longer requires E5? Can a customer buy Defender ATP standalone and only have Windows 10 Pro and other support OS's, without having Windows 10 Enterprise (or Education) licensed in their environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by joinimran** [comment]
@kyjeeper - Looks like relevant information is available as a note in the doc.

![image](https://user-images.githubusercontent.com/47118050/88462659-8ea13f00-cec6-11ea-88dd-4fe7f7253ee7.png)

**Comment by jseerden** [comment]
Please clarify in which CSP licenses Microsoft Defender ATP is available. Options such as Microsoft 365 Business Premium + Microsoft 365 E5 Security and Microsoft Defender ATP Standalone are not documented. Also needs updating here: https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-users-benefit-from-the-service

**Comment by joinimran** [comment]
@jseerden - Microsoft Defender ATP is available as a standalone product as well. No volume license is required.
see details at  https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements. You can also contact your Cloud Service Provider to get more details.

Thanks.
Imran.

**Comment by e0i** [comment]
Hello @kyjeeper 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
