### ISSUE TITLE
Protected domains separator ambiguous 

### ISSUE THREAD

**Issue by velden** [MicrosoftDocs/windows-itpro-docs#7135]
Comma vs. pipe

**From the webpage:**

```
Protected domains
Specify the domains used for identities in your environment. All traffic to the fully-qualified domains appearing in this list will be protected. Separate multiple domains with the "," delimiter.

```
**From the Intune built-in help (tooltip):**

```
Specify the DNS names that form your corporate network. These are used in conjunction with the IP ranges that you specify to define your corporate network boundary. Multiple values can be specified by separating individual entries with a '|'.

This setting is required to have Windows Information Protection enabled.

For example: corp.contoso.com|region.contoso.com
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ad3f92-24de-5eb5-8454-c72d85737183
* Version Independent ID: 900125eb-31ea-faf3-ac30-7c3d7b30f611
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@velden 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
