### ISSUE TITLE
Unclear how settings affect servers

### ISSUE THREAD

**Issue by NetMage** [MicrosoftDocs/windows-itpro-docs#7138]
The page specifies how client and domain controllers respond to differing levels, but is unclear on how this setting affects regular servers.

It also fails to mention at least one fallback usage: when the user is logging on with a local SAM account instead of a domain account (such as RDP with local credentials) this setting affects the connection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 744990d3-6fb4-a085-de18-b0894c2dbda5
* Version Independent ID: f774568c-506c-cc5f-f6b2-2452cb408667
* Content: [Network security LAN Manager authentication level (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-lan-manager-authentication-level)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-security-lan-manager-authentication-level.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-security-lan-manager-authentication-level.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by SwiftOnSecurity** [comment]
@NetMage What's your scenario where servers are using different authentication than other machines?

**Comment by joinimran** [comment]
@NetMage - Thank you for your feedback. Please note that all documents are as per standard and in policies, there is no scenario information available. If there is any specific requirement, you can open a support case with Microsoft.

Thanks.
Imran.
