### ISSUE TITLE
Add (Implicit Add supported)

### ISSUE THREAD

**Issue by Harmyder** [MicrosoftDocs/windows-itpro-docs#7141]
There is no definition for "Implicit Add". Neither in MS nor in OMA documentation. Does this mean that Replace works like Add if there is no such node?

One can find this term in _OMA DM standards_ section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de30f8b-0039-3cb5-0b38-8064d8fb2a3a
* Version Independent ID: f2968413-2951-5c42-dd5a-2a0b974338ca
* Content: [OMA DM protocol support - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/oma-dm-protocol-support)
* Content Source: [windows/client-management/mdm/oma-dm-protocol-support.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/oma-dm-protocol-support.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
@Dansimp - Do you have any idea what definition does implicit add holds. I am not able to find this anywhere on the internet even in OMA site.

**Comment by e0i** [comment]
> @Dansimp - Do you have any idea what definition does implicit add holds. I am not able to find this anywhere on the internet even in OMA site.

cc @ManikaDhiman
