### ISSUE TITLE
Duplicate Entry?

### ISSUE THREAD

**Issue by Kirtar22** [MicrosoftDocs/windows-itpro-docs#7146]
[Enter feedback here]
Hi team, 

Can you please verify "Policy Name" in Step 1 and Step 2 (in TABLE) under "Enforce local account restrictions for remote access" ?
Looks duplicate. 

Regards,

Kirtar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74d32ee6-c7ff-9328-97d6-40ad82c73392
* Version Independent ID: 01f10cbb-4cae-077f-8245-7b0ada8305d7
* Content: [Local Accounts (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/local-accounts)
* Content Source: [windows/security/identity-protection/access-control/local-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/access-control/local-accounts.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@Kirtar22 ,i checked this article and compared with group policy of windows 10 v2004,, i found step 1  policy name must be replaced with  
**User Account Control: Admin Approval Mode for the Built-in Administrator account**

**Comment by aczechowski** [comment]
It looks like this issue is fixed at some point along the way. Please reopen if not the case.
