### ISSUE TITLE
Incorrect reg path for policy

### ISSUE THREAD

**Issue by ShortOrderCookie** [MicrosoftDocs/windows-itpro-docs#715]
On Enterprise Win10, setting this policy (AllowTelemetry), Computer Configuration > Administrative Templates > Windows Components > Data Collection and Preview Builds.
sets the registry value "AllowTelemetry" in this location:
   HKLM\Software\Policies\Microsoft\Windows\DataCollection
Not at this path:  
   HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\DataCollection

So is the policy really making the correct setting or should we set values at the stated registry path?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd4517a5-256d-8e67-5153-1f6d9ef737ba
* Version Independent ID: a656e3b9-f1f6-2dff-26c0-38ed670293b6
* Content: [Configure Windows diagnostic data in your organization (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/configure-windows-diagnostic-data-in-your-organization)
* Content Source: [windows/configuration/configure-windows-diagnostic-data-in-your-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/configure-windows-diagnostic-data-in-your-organization.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **jdecker**

**Comment by DaniHalfin** [comment]
Hi @ShortOrderCookie , I believe you are correct, however, I'd like to double check with the feature team, as this information was initially populated with their collaboration.
The ADMX definitely suggests that the path used is the one you're suggesting.

**Comment by mypil** [comment]
@ShortOrderCookie - Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
