### ISSUE TITLE
Not all versions support Tamper Protection

### ISSUE THREAD

**Issue by cventour** [MicrosoftDocs/windows-itpro-docs#7150]
It seems Tamper protection is not available for versions prior to 19H1 while the documents states that it is supported on 1709 and newer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a2f0402-82fb-83ff-122a-2f19c5288eeb
* Version Independent ID: 52f80b09-0e90-464d-0c4d-00479361fa9b
* Content: [Protect security settings with tamper protection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by e0i** [comment]
Closing as it has been suggested that the article is correct as it is. See the comment, https://github.com/MicrosoftDocs/windows-itpro-docs/pull/7946#pullrequestreview-467774360
