### ISSUE TITLE
Will clearing the TPM require a BitLocker code on reboot?

### ISSUE THREAD

**Issue by dryphi** [MicrosoftDocs/windows-itpro-docs#7152]
Note that I'm trying to provide feedback on this page:
https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/initialize-and-configure-ownership-of-the-tpm

The document states "Clearing the TPM resets it to an unowned state. After you clear the TPM, the Windows 10 operating system will automatically re-initialize it and take ownership again."
If I restart Windows after clearing the TPM, will a BitLocker code be required? Will the drive still be encrypted? Will Windows function normally or will this make the partition unrecoverable? Please describe further exactly what this means.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805915dd-11ed-01bb-47b8-7cd715275703
* Version Independent ID: 5542a776-c895-b09b-d3eb-54cd8307b202
* Content: [Troubleshoot the TPM (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/initialize-and-configure-ownership-of-the-tpm)
* Content Source: [windows/security/information-protection/tpm/initialize-and-configure-ownership-of-the-tpm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/tpm/initialize-and-configure-ownership-of-the-tpm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @dryphi - Thank you for asking this question. Please note that clearing TPM can result in many issues if you don't own the backup key or if you don't own the machine it can result in many issues. Please see https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/initialize-and-configure-ownership-of-the-tpm#precautions-to-take-before-clearing-the-tpm for more details. 

Thanks.
Imran.

**Comment by dryphi** [comment]
Hi, thanks for the response.
Yes I do own the machine and hence the backup key.
Please clarify what you mean. Thanks

**Comment by illfated** [comment]
You will want to have a full backup on hand, as well as a ready-to-use restore plan, in case anything goes wrong after clearing the TPM (as stated in the linked document page). Clearing a TPM without a backup and restore plan is not recommended and can cause data loss unless you are 100% successful in restoring the TPM key to its original value afterwards.
