### ISSUE TITLE
? Question regarding MMAT 

### ISSUE THREAD

**Issue by rscphat** [MicrosoftDocs/windows-itpro-docs#7153]
is the MMAT tool still in maintenance  ( Last update 12 month ago ? )

what about open issues: https://github.com/WindowsDeviceManagement/MMAT/issues 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7e875fa6-9fa9-1d42-ab68-a1b0285a0666
* Version Independent ID: 618c4d23-f231-bac3-33ad-87f9d4952492
* Content: [Mobile Geräteverwaltung - Windows Client Management](https://docs.microsoft.com/de-de/windows/client-management/mdm/)
* Content Source: [windows/client-management/mdm/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/index.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Relevant pages:
- https://github.com/WindowsDeviceManagement/MMAT
- https://github.com/WindowsDeviceManagement/MMAT/issues
- https://github.com/WindowsDeviceManagement/MMAT/pulls
- https://github.com/WindowsDeviceManagement/MMAT/blob/master/README.md

**Comment by e0i** [comment]
@Dansimp Would you be able to clarify whether the MMAT tool is still under maintenance? Thank you.
