### ISSUE TITLE
Why does access control not seem to work according to the documentation?

### ISSUE THREAD

**Issue by David263** [MicrosoftDocs/windows-itpro-docs#7157]
This page, and other documentation, doesn't explain what I've observed. Let's say my local account username is Mike. I use Explorer to go to some part of the file system I don't have access to. I pick an unimportant folder that contains folders and files that are not critical to Windows. Call that folder A. I view the properties of A and select Security > Advanced. I take ownership of A and its descendents. No problem there. But then I edit the permissions of Mike and give myself full access rights. But some descendents of A can be deleted and some cannot (of course, a folder cannot be tree-deleted if any contained file or folder cannot be deleted, but that is not the issue here). Those that cannot be deleted correctly show Mike to have full rights. However, Mike is also in Administrators, which may have restricted rights! Doesn't the limitations of Administrators also apply to Mike, who has an Admin-type account?

So the documentation should explain which permissions entries apply to Mike. Mike appears to be in Users and Administrators, but is that the whole list? What is the minimum permissions editing required to allow contained files and folders to be deleted by Mike himself but without changing the permissions of other groups?

Also, this documentation needs to explain inherited permissions, containers, and other subtleties much better. There needs to be a complete tutorial on these subjects. If the information is already there, it needs to be organized and presented better, so questions like this one can be answered in a reasonable amount of time.

David, Windows 10 Home Version	10.0.18362 Build 18362
System Type	x64-based PC
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac7121e0-fdc4-451d-e16e-c5dc8eac517a
* Version Independent ID: 71044eb7-fc67-9f17-196a-366d9f9ec849
* Content: [Access Control Overview (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/access-control)
* Content Source: [windows/security/identity-protection/access-control/access-control.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/access-control/access-control.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@David263 , , I used registry key trick to take full ownership of the folders and files for the particular username.
I take ownership, only if i required it.

**Comment by joinimran** [comment]
Hello @David263 - Thank you for your feedback here. I have gone through the submitted details. There are a few things involved here. The system folders are protected from the permissions side as well as registry entries to ensure that those folders safe and secure for Windows. Normally, the Administrator account is disabled by default to ensure that no unauthorized access can take place and the newly created accounts are added to the Admin group of the computer. Only the Administrator of the computer has full permission and control. If the user Mike is a member of the Admin group only he still can't perform many operations. Where ever there is a admin permission required we normally run the shell with the Administrator user to perform these actions.

For more information related to accounts, please see  https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/local-accounts

Thanks
Imran.

**Comment by David263** [comment]
Thank you, Imran, for the information and the link. The linked file gives much confusing information, possibly because of the use of undefined terms and possibly because of the ambiguity in meaning of "administrative account", which can mean the built-in Administrator account OR a user account with Administrators rights. I still have only vague ideas about who can change file permissions and how it is done. (Furthermore, the linked file says to use Group Policy, **which is advised by many Help files**, but Group Policy is **not available** on Windows Home.)

For example, that file says, "members of the Administrators group on a local server have Full Control permissions on that computer." This contradicts what you wrote in which you claim that the Administrator account is special and different from user accounts in the administrators group. If I have to choose between what Microsoft documents and what you wrote, I must choose Microsoft, because I have no idea who you are or what you actually know for certain. I see no clear documented difference between the Administrator account and a user account with Administrators rights.

**Comment by joinimran** [comment]
@David263 - Actually there is a difference between the administrator and Admin account. The administrator has full access and full permissions to do anything with OS. On the other hand, the Admin account has a limitation or the user added in the Admin Group has much access but still not as powerful as the administrator. You can say the user added in the admin group can is a sub-admin. That user still needs to use run as Admin option for many of the settings and other activities that can harm the computer. 

Thanks.
Imran.

**Comment by David263** [comment]
Imran, I find your comment very unclear. Again, you use language very imprecisely and make sweeping claims without any references or evidence. I can't believe anything you say, unfortunately. I would say, honestly, that you either don't know much about Windows security or you don't know how to communicate well. I can't tell which is the case.
