### ISSUE TITLE
List+Description of assignable permissions?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/windows-itpro-docs#7158]
Where can I find the list of permissions which can be assigned to a role? Is it documented anywhere, or should I go to the portal?
I mean permissions like "Weaknesses (vulnerabilities) page", "Configure storage settings", "Approve or dismiss pending remediation actions", "Manage Alerts", etc.etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0c70c9-d302-7375-aaed-eb6a2087fee2
* Version Independent ID: 15f40eca-1ab9-2558-4768-b1dd9c5b70a5
* Content: [Use role-based access control to grant fine-grained access to Microsoft Defender Security Center - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/rbac)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/rbac.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/rbac.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@andrePKI . I think you must use the Microsoft ATP  portal to configure.

**Comment by MaratMussabekov** [comment]
Hello @andrePKI ,
unfortunately, there is no article with the detailed information about the permissions in Microsoft docs. General list of the available permissions could be found [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/user-roles#permission-options).
thank you
