### ISSUE TITLE
spelling error: donwloaded

### ISSUE THREAD

**Issue by bane58** [MicrosoftDocs/windows-itpro-docs#7159]
[Enter feedback here]
Spelling error on page. 

"Insert a USB key containing the donwloaded update."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2434dfb6-ac9a-4ba1-a681-88786c87010a
* Version Independent ID: 47e7470e-ab97-9917-04aa-4ec08a178af5
* Content: [Windows Autopilot User-Driven Mode - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/user-driven#user-driven-mode-for-hybrid-azure-active-directory-join-with-vpn-support)
* Content Source: [windows/deployment/windows-autopilot/user-driven.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/user-driven.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Thank you for reporting this typo. PR #7156 should resolve this ticket.

**Comment by greg-lindsay** [comment]
Merged PR, thanks!
