### ISSUE TITLE
What permission do you need?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/windows-itpro-docs#7160]
Many people get stuck at square one: no access or not even a clue where to start (which portal/page/blade).
Could we please have something like "You need to be in the xxx administrator role to perform this task" and "Open the portal at https://...." in the beginning of all these how to instructions?
Thanks in advance ;-) 👍 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b246db4-2ef2-fc54-8db1-7a75a4974304
* Version Independent ID: 57290170-ba72-9f26-5a9c-311f6980ea19
* Content: [Create and manage roles for role-based access control - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/user-roles)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/user-roles.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/user-roles.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@andrePKI  Upon your feedback, We have updated the content with relevant changes accordingly via PR #8091. Thanks.
