### ISSUE TITLE
Xml error in ApplicationControlCSPddf, version 1903

### ISSUE THREAD

**Issue by Harmyder** [MicrosoftDocs/windows-itpro-docs#7162]
The following message comes up when I'm trying to parse ApplicationControlCSPddf.xml in 1903 version.

Unable to parse any XML input. Error on line 294: The element type "MgmtTree" must be terminated by the matching end-tag "</MgmtTree>".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 393fcbf0-cfb3-e921-b96d-79abda94bd88
* Version Independent ID: 634fbc24-d5f3-70b6-3db1-76c0ad853977
* Content: [Configuration service provider reference - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference#csp-ddf-files-download)
* Content Source: [windows/client-management/mdm/configuration-service-provider-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/configuration-service-provider-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello, @Harmyder ,
yes, you are correct the XML file is incorrect, it contains one extra </Node> tag. You can remove it, then file will work normally.

Dear @e0i ,
Is it possible to contact person who can edit the files from Download Center? To tell about the issue with this ApplicationControlCSPddf.xml file?

Thank you

**Comment by e0i** [comment]
@ManikaDhiman Can you have the incorrect XML file fixed and re-uploaded? Independent contributors don't have access to the Download Center. Thank you.

**Comment by ManikaDhiman** [comment]
Hi @e0i, the DDF files on the Download Center are simply copies of the actual DDF files. Any DDF file related issue should not be treated as a doc issue. Even if we fix it in the doc, the issue would still remain open in the actual DDF file. Thanks!
