### ISSUE TITLE
"BIOS" -> "SYSTEM"

### ISSUE THREAD

**Issue by yoichinak** [MicrosoftDocs/windows-itpro-docs#7163]
>## 既定のローカルシステムアカウント
>### BIOS
>システムアカウントは、オペレーティングシステムと Windows で実行されるサービスによって使用されます。

"BIOS" は誤りで、正しくは  "SYSTEM" ではないでしょうか。[英語版](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/local-accounts#default-local-system-accounts) を確認しました。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 74d32ee6-c7ff-9328-97d6-40ad82c73392
* Version Independent ID: 01f10cbb-4cae-077f-8245-7b0ada8305d7
* Content: [ローカルアカウント (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/ja-jp/windows/security/identity-protection/access-control/local-accounts)
* Content Source: [windows/security/identity-protection/access-control/local-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/access-control/local-accounts.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/local-accounts#default-local-system-accounts :


## <a href="" id="sec-localsystem"></a>Default local system accounts

### SYSTEM
The SYSTEM account is used by the operating system and by services that run under Windows. There are many services and processes in the Windows operating system that need the capability to sign in internally, such as during a Windows installation. The SYSTEM account was designed for that purpose, and Windows manages the SYSTEM account’s user rights. It is an internal account that does not show up in User Manager, and it cannot be added to any groups. 

On the other hand, the SYSTEM account does appear on an NTFS file system volume in File Manager in the **Permissions** portion of the **Security** menu. By default, the SYSTEM account is granted Full Control permissions to all files on an NTFS volume. Here the SYSTEM account has the same functional rights and permissions as the Administrator account.

**Note**  
To grant the account Administrators group file permissions does not implicitly give permission to the SYSTEM account. The SYSTEM account's permissions can be removed from a file, but we do not recommend removing them.

***
https://docs.microsoft.com/ja-jp/windows/security/identity-protection/access-control/local-accounts#既定のローカルシステムアカウントdefault-local-system-accounts :

## <a href="" id="sec-localsystem"></a> 既定のローカルシステムアカウント

### BIOS
システムアカウントは、オペレーティングシステムと Windows で実行されるサービスによって使用されます。 Windows のインストール時など、内部でサインインする機能が必要な多くのサービスとプロセスが Windows オペレーティングシステムにあります。 システムアカウントはその目的に合わせて設計されており、Windows はシステムアカウントのユーザー権利を管理します。 これは、ユーザーマネージャーに表示されず、どのグループにも追加できない内部アカウントです。
一方、システムアカウントは、[**セキュリティ**] メニューの [**アクセス許可**] にあるファイルマネージャーの NTFS ファイルシステムボリュームに表示されます。 既定では、SYSTEM アカウントには、NTFS ボリューム上のすべてのファイルに対するフルコントロールのアクセス許可が与えられます。 システムアカウントには、管理者アカウントと同じ機能権限と権限があります。
**注** アカウント管理者にグループファイルのアクセス許可を付与しても、システムアカウントに対して暗黙的にアクセス許可が与えられることはありません。 システムアカウントのアクセス許可はファイルから削除できますが、削除はお勧めしません。

**Comment by illfated** [comment]
@TinaMcN : I suggest manual translation of that section title (sub-heading H2), because it is not practical to change it in the en-us source page.

See my comment above for a comparison between the /en-us/ page and the /ja-jp/ version.
The sub-heading (H2) is incorrectly translated by Machine Translation.
I do not recommend encapsulating a section title in MarkDown back ticks to convert it to a monospace typeface (font) while trying to avoid translation of that word.

**Comment by TinaMcN** [comment]
@yoichinak この問題を報告していただきありがとうございます。 機械翻訳ツールの問題のようです。 記事は人間が翻訳されます。 それは数日で修正されるべきです。 (Thank you for reporting this issue.  It appears to be a problem with our machine translation tool.  The article will be human translated.  It should be fixed in a few days.) @OfficeGlobal, please let us know when the file is human translated.

**Comment by OfficeGlobal** [comment]
@yoichinak article was HumanTranslated. The string is fixed at live page

**Comment by illfated** [comment]
## 既定のローカル システム アカウント

### SYSTEM

SYSTEM アカウントは、オペレーティング システムおよび Windows で実行されるサービスによって使用されます。 Windows オペレーティング システムには、Windows のインストール時などに、内部的にサインイン機能が必要になるサービスやプロセスが多数あります。 SYSTEM アカウントは、その目的のために設計されていて、SYSTEM アカウントのユーザー権利は Windows が管理します。 この内部アカウントはユーザー マネージャーには表示されません。また、どのグループにも追加できません。

その一方で、SYSTEM アカウントは、ファイル マネージャーの NTFS ファイル システム ボリュームには表示されます (**[セキュリティ]** メニューの **[アクセス許可]** の部分)。 既定では、SYSTEM アカウントには、NTFS ボリュームのすべてのファイルに対するフル コントロールのアクセス許可が付与されています。 この SYSTEM アカウントには、Administrator アカウントと同じ機能性の権利とアクセス許可があります。

注: アカウントに Administrators グループ ファイルのアクセス許可を付与しても、SYSTEM アカウントに暗黙的にアクセス許可を付与することにはなりません。 SYSTEM アカウントのアクセス許可はファイルから削除できますが、そのアクセス許可の削除はお勧めしません。
