### ISSUE TITLE
Block Office communication application from creating child processes: User Defined not described

### ISSUE THREAD

**Issue by SteffanH** [MicrosoftDocs/windows-itpro-docs#7164]
Section link: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction#block-office-communication-application-from-creating-child-processes

When configuring this ASR, there are the standard options to choose from, and "User defined"; what does that option do ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d747289-63b2-f71a-b40c-31b52982215c
* Version Independent ID: b52f6593-03f2-aa57-ec0e-eaef560dcaf0
* Content: [Use attack surface reduction rules to prevent malware infection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction#rule-block-credential-stealing-from-the-windows-local-security-authority-subsystem-lsassexe)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@SteffanH . Will you share the screenshots

**Comment by SteffanH** [comment]
![image](https://user-images.githubusercontent.com/866619/87417101-f951a100-c5cf-11ea-8e40-339290267db3.png)

**Comment by RAJU2529** [comment]
@SteffanH . Are you trying to configure via MDM intune portal or microsoft defender atp portal.

**Comment by SteffanH** [comment]
@RAJU2529 Via Endpoint Manager -> Endpoint Security -> Attack Surface Reduction

**Comment by RAJU2529** [comment]
@SteffanH . Sorry then I don't have knowledge about endpoint manager, so wait for few days let expert users will give solutions

**Comment by MaratMussabekov** [comment]
Hello @SteffanH ,
There are three default values for ASR rules:
1. not configured - ASR doesn't work
2. enable - ASR works
3. audit mode - ASR doesn't work, but events are logged.

You can use management tools (MDM, SCCM or GPO) to configure ASR, or set it manually using Powershell
In case you use both, value set by management tools will overwrite value set using PowerShell.

But, if you use management tools and set ASR rule to "User defined", it will just take the value which was set manually using Powershell.

This is how it works from my experience, but it was never confirmed in Microsoft Docs. Dear @e0i , is it possible to contact author to ask for confirmation?

Thank you

**Comment by RAJU2529** [comment]
@MaratMussabekov , i used PowerShell to configured ASR set to Enabled. 
also in GPO, only User defined option is not available.

**Comment by e0i** [comment]
Closing via #8090

**Comment by RAJU2529** [comment]
@e0i. I am little confused after seeing PR created by @MaratMussabekov .
how can I use powershell with user defined cmdlet.
will you give me the command

**Comment by illfated** [comment]
@RAJU2529 : Your request might be slightly difficult to follow up on, because the User Defined cmdlet will most likely depend on the specific environment (operating system versions or network topology) for the individual manager or department. My only guess would be that it could be a specific threat that the individual IT department is trying to defend themselves against, more specifically the method they have chosen to apply their selected method of attack prevention.
