### ISSUE TITLE
List machines now return machines from last 6 months and not last 30 days

### ISSUE THREAD

**Issue by noblevarghese** [MicrosoftDocs/windows-itpro-docs#7175]
[Enter feedback here]

Hi Team,

It appears like the list machines API is returning last 6 months data and not last 30 days. I can see lot of machines now. This was not the case few days back.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce06635a-e51d-4eed-427d-0119edc1d58c
* Version Independent ID: f62a5abb-7920-2129-0874-f10ad42172d7
* Content: [List machines API - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/get-machines)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/get-machines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/get-machines.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by noblevarghese** [comment]
I have got confirmation for sources that the behaviour is changed from 30days to 6 months. But not updated in Docs

**Comment by mjcaparas** [comment]
Yes, updates coming shortly.
