### ISSUE TITLE
UserAccountControl_UseAdminApprovalMode Value Type

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/windows-itpro-docs#7176]
In the document "LocalPoliciesSecurityOptions/UserAccountControl_UseAdminApprovalMode" use integer or moore?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 773b74b2-7dc2-d0e5-1e3b-bd6445bceda4
* Version Independent ID: 34b55057-9078-6bd0-a9ac-2f6403b84be7
* Content: [Policy CSP - LocalPoliciesSecurityOptions - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions#localpoliciessecurityoptions-useraccountcontrol-allowuiaccessapplicationstopromptforelevation)
* Content Source: [windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@goxia . Only  Integers are accepted 

0 - Disabled: 
1 - Enabled:

**Comment by goxia** [comment]
> @goxia . Only Integers are accepted
> 
> 0 - Disabled:
> 1 - Enabled:

@RAJU2529 Thank you a lot. the content will be update to Docs?

**Comment by RAJU2529** [comment]
@goxia . no need to update again , because those details are already in this article
