### ISSUE TITLE
Update the extension question

### ISSUE THREAD

**Issue by RayJDM** [MicrosoftDocs/windows-itpro-docs#7177]
Question about the possibility to make WD AG work with extensions - in FAQ it says its not possible, however it was added in recent Windows 10 update. Should be reflected in the FAQ site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8927df09-e9aa-8c40-290d-0ca7d86ec4e2
* Version Independent ID: ca67bcfc-6120-d6ca-290b-1a7822494c73
* Content: [FAQ - Microsoft Defender Application Guard (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-application-guard/faq-md-app-guard)
* Content Source: [windows/security/threat-protection/microsoft-defender-application-guard/faq-md-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-application-guard/faq-md-app-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@RayJDM . Will you share the articlelink that you pointing out.

**Comment by RayJDM** [comment]
FAQ page:
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-application-guard/faq-md-app-guard#why-arent-employees-able-to-see-their-extensions-in-the-application-guard-edge-session

Extensions support:
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-security-windows-defender-application-guard#extension-support-inside-the-container

**Comment by RAJU2529** [comment]
@RayJDM . according to me WDAG supported by edge browser to monitor untrusted and malicious website links.
but extensions will not monitor. I am not sure.
let WDAG edge expert users will answer to your question.
