### ISSUE TITLE
CRL questions

### ISSUE THREAD

**Issue by johnjohnjohn87** [MicrosoftDocs/windows-itpro-docs#7179]
Hello,
We are in the process of implementing WHfB with Key Trust and I had a few questions about the CRL requirements. I see that the CRL is required for WHfB to work, but what happens if the CRL breaks or is unavailable? Does that break enrollment, or all WHfB sign-ins in the organization?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c47de28c-e44b-ca73-efde-fae303e0d3f8
* Version Independent ID: 71202a24-5b2f-844a-acce-d48c46873f2b
* Content: [Hybrid Key trust Windows Hello for Business Prerequisites (Windows Hello for Business) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mapalko** [comment]
If the CRL is not available or broken, it will result in WHFB authentication failing.
