### ISSUE TITLE
The default Diagnostic Level for Windows 10 Pro is not mentioned in this article. What's the default level for Windows 10 Pro?

### ISSUE THREAD

**Issue by pjchacong** [MicrosoftDocs/windows-itpro-docs#718]
What's the default Diagnostics Level for Windows 10 Pro? Only Enterprise and Education versions are mentioned in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd4517a5-256d-8e67-5153-1f6d9ef737ba
* Version Independent ID: a656e3b9-f1f6-2dff-26c0-38ed670293b6
* Content: [Configure Windows diagnostic data in your organization (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/configure-windows-diagnostic-data-in-your-organization#feedback)
* Content Source: [windows/configuration/configure-windows-diagnostic-data-in-your-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/configure-windows-diagnostic-data-in-your-organization.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@pjchacong The default level for Windows 10 Pro is FULL.
