### ISSUE TITLE
What about Windows Hello users?

### ISSUE THREAD

**Issue by johnjohnjohn87** [MicrosoftDocs/windows-itpro-docs#7180]
Sorry if this isn't the correct page for this question, but I couldn't find documentation around hybrid deployment for users who have already been using Windows Hello. I've heard that before WHfB enrollment is deployed the old Hello credentials should be removed, but I can't find any clear documentation on that process.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4784e8f-6d35-78d8-9160-7b39832a58d8
* Version Independent ID: 7f79559a-3a6d-473b-1ec1-66746c461318
* Content: [Windows Hello for Business Key Trust New Installation - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-new-install.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by RAJU2529** [comment]
@johnjohnjohn87 . This question is complecated

**Comment by MaratMussabekov** [comment]
Hello @johnjohnjohn87 ,
**I couldn't find documentation around hybrid deployment for users who have already been using Windows Hello.** - there are no any special requirements.
**I've heard that before WHfB enrollment is deployed the old Hello credentials should be removed** - I never seen this requirement in official documentation. Could you please provide any source?
From my experience, presence of Windows Hello doesn't affect the deployment of WHfB.

Thank you
