### ISSUE TITLE
Missing IDs

### ISSUE THREAD

**Issue by brportela** [MicrosoftDocs/windows-itpro-docs#7181]
Page is not updated to the current event ids that we see on clients, missing from event id 49 and forward

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab6dfd3e-71ac-7987-80d7-5bd380bed06a
* Version Independent ID: 9eb3c26b-e61c-2c8b-35a0-415c2a26bfed
* Content: [Review events and errors using Event Viewer - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/event-error-codes)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/event-error-codes.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/event-error-codes.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@mjcaparas Would you be able to help us identify the rest of the missing event IDs? We’d like to come up with revisions accordingly. Thank you.

**Comment by PatrikHanssonIntersolia** [comment]
Any progress here? Still missing ID49 in the list.

**Comment by e0i** [comment]
@adirdidi There is an independent contributor who is assigned to take care of this issue who can come up with a PR once the essential information has been obtained. That's why help had been wanted. Please let me know if you intend to pick the issue up from here. Thanks.

**Comment by adirdidi** [comment]
I didn't removed the help tag.
Regardless, I don't see how someone not from the product group can handle this ask.
And yes - I'm working on it.

**Comment by e0i** [comment]
Noted, Thank you!

**Comment by adirdidi** [comment]
Updated: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/event-error-codes.
