### ISSUE TITLE
"Block persistence through WMI event subscription" is not available in Intune

### ISSUE THREAD

**Issue by alexlushsevernunival** [MicrosoftDocs/windows-itpro-docs#7182]
Landed on this page from a MSATP Security Recommendation "Block persistence through WMI event subscription", the setting is described on the page but in Intune there is no such setting. Has it been renamed or removed for some reason?

Others are having this issue, see the following user voice item:
https://microsoftintune.uservoice.com/forums/291681-ideas/suggestions/40862476-asr-rule-block-persistence-through-wmi-event-subs

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d747289-63b2-f71a-b40c-31b52982215c
* Version Independent ID: b52f6593-03f2-aa57-ec0e-eaef560dcaf0
* Content: [Use attack surface reduction rules to prevent malware infection - Windows security](https://docs.microsoft.com/en-gb/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction#block-persistence-through-wmi-event-subscription)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by VLG17** [comment]
@alexlushsevernunival Looking at the article it's stated that the Intune and Config. Manager name of this rule is not yet available.

![image](https://user-images.githubusercontent.com/41186174/93743671-1bcbf000-fbf9-11ea-8b92-1352c8bdd041.png)

The rule only applies to Windows Server and 10 starting with build 1903 for now.

**Comment by alexlushsevernunival** [comment]
@VLG17 - Appreciate its not yet available, but if that's the case then MSATP shouldn't be spitting out recommendations to enable something that's not available! Does anyone have an ETA on when this will be available? Specifically for Intune in our case.
