### ISSUE TITLE
This needs to be updated for new Endpoint Manager

### ISSUE THREAD

**Issue by frehnejc** [MicrosoftDocs/windows-itpro-docs#7185]
Needs to be updated for the new portal experience https://endpoint.microsoft.com/.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc63299-cc1c-e031-deb7-915914b8f94e
* Version Independent ID: 356eaba5-16b0-952f-fc19-c8d5be5feb5f
* Content: [Demonstrate Autopilot deployment - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm#configure-microsoft-intune-auto-enrollment)
* Content Source: [windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
I will do another run through and update this as soon as I can. I'll leave the issue open until I can get this completed.

**Comment by e0i** [comment]
Fixed via https://github.com/MicrosoftDocs/windows-itpro-docs/commit/c62e96dc46cc1645f1d811a02985d6dec41f3426#diff-08a3ecf1411414d2c482a969f5344c352e43a95ad6933dc3cf617c4dccc4ac9f Thanks.

**Comment by illfated** [comment]
(just to have the commit link show a pop-up bubble:) https://github.com/MicrosoftDocs/windows-itpro-docs/commit/c62e96dc46cc1645f1d811a02985d6dec41f3426
