### ISSUE TITLE
Automatic VPN connection order

### ISSUE THREAD

**Issue by jasonkatz424** [MicrosoftDocs/windows-itpro-docs#7187]
You mention "The Automatic option means that the device will try each of the built-in tunneling protocols until one succeeds. It will attempt from most secure to least secure."

You do not explicitly state in the documentation which protocols will be tried in what order.  It would be helpful to explicitly say the order:

1. IKEv2 
2. L2TP/IPSec
3. SSTP
4. PPTP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 746fd1a2-12c0-692c-f22a-251b370df7d7
* Version Independent ID: 71ca5f84-9afb-4007-6d2d-db953756feca
* Content: [VPN connection types (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-connection-type)
* Content Source: [windows/security/identity-protection/vpn/vpn-connection-type.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/vpn/vpn-connection-type.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @jasonkatz424 ,
Could you please provide any source where it is stated that the order is IKEv2, L2TP/IPSec, SSTP and PPTP?
From my experience, the order is IKEv2, SSTP, PPTP, and L2TP (even though L2TP is more secure than PPTP).
Thank you
