### ISSUE TITLE
12 anti virus scan engines detect MDATPAnalyzer tool as malware

### ISSUE THREAD

**Issue by SergioCBPC** [MicrosoftDocs/windows-itpro-docs#7189]
Was trying to verify client connectivity to troubleshoot a "misconfigured" error.
I downloade the tool from this URL https://aka.ms/mdatpanalyzer  which I found in the microsoft docs page for verifying connectivity to Microsoft Defender ATP service URLs.

When I tried to execute the MDATPClientAnalyzer.cmd, bitdefender removed the MDATPClientAnalyzer.PS1 file and therefore failed to analyze.

I uploaded the entire analyzer zip file to virus total and came back with 12 anti virus engines reporting as malware.

**Comment by RAJU2529** [comment]
@SergioCBPC . Which article are you reffering?

**Comment by SergioCBPC** [comment]
> @SergioCBPC . Which article are you reffering?

This article is from where I downloaded the analyzer tool:
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet#verify-client-connectivity-to-microsoft-defender-atp-service-urls

**Comment by RAJU2529** [comment]
@SergioCBPC. @denisebmsft .  I also tested that zip file on the virus total website,m I received the same result. below is the screenshot 
![Capture](https://user-images.githubusercontent.com/3296790/87755353-783f1780-c824-11ea-860b-58a312ad6b75.JPG)

**Comment by e0i** [comment]
@mjcaparas Can you check the link for MDATPAnalyzer tool? It seems that the tool is somehow recognized as malware. Thanks.

**Comment by mjcaparas** [comment]
Applications without known reputation, or while it is building reputation, will show warnings when downloaded or installed.

This does not prevent users from still clicking through to download or run the application. 

To do so, they can select ("More info") > "Run anyway" option within SmartScreen prompt window.  


Our tools are regularly updated and new versions may be gaining reputation when you first encounter them.  If you are concerned by the warning, please download the file and then inspect our digital signature and compare the file hash to the one listed on our site.

The hash for this particular file (MDATPClientAnalyzer.cmd) is: 6D7371378479A2A48A7B5C00D9A0EE6E68B2743E2C0150EAB93C2ACA804C5882
