### ISSUE TITLE
What does the MDMWinsOverGP = 0 means?

### ISSUE THREAD

**Issue by yogeshasalkar** [MicrosoftDocs/windows-itpro-docs#7191]
Hi MS team,
I just want to know what does the MDMWinsOverGP = 0 means? Does it mean that GP always wins in case of conflict or does it means only the setting of that platform (GP or Intune) wins using which it has set lastly (**latest configuration**)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: becd9bd1-6396-3f4a-cc78-c9a06b781516
* Version Independent ID: efeec2a0-08b0-d1fc-72c5-14c23fa11397
* Content: [Policy CSP - ControlPolicyConflict - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-controlpolicyconflict)
* Content Source: [windows/client-management/mdm/policy-csp-controlpolicyconflict.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-controlpolicyconflict.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by ManikaDhiman** [comment]
@yogeshasalkar: Apparently, this has already been answered via #6482 and #6522. 

@e0i: Could you review and close this issue? Thanks!

**Comment by e0i** [comment]
@yogeshasalkar Can you confirm whether the response provided via https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6482#issuecomment-619337333 answers your question? Thank you.
