### ISSUE TITLE
Can't setup PIN in order to setup Fingerprint 0x80090016

### ISSUE THREAD

**Issue by ThomasDommerholt** [MicrosoftDocs/windows-itpro-docs#721]
I can change my PIN, but it gives an error beneath the 'I forgot my PIN' line with: 'Sorry - this PIN isn't working for your organization's recourses. Tap or click here to fix it.'. When I tap this it opens a window to setup my PIN, but when I hit the 'Set up PIN' button it says 'Something went wrong. We weren't able to set up your PIN. Sometimes it helps to try again, or you can skip for now and do this later.'. Then it says 'For more information on errors during PIN setup: https://aka.ms/PINErrors' but my error is not listed and the steps doesn't help either. Error code: 0x80090016. Please help because I just want to setup a fingerprint so I can sign in with it, which by the way worked before.

**Comment by andreabichsel** [comment]
You can get help from https://support.microsoft.com/en-us, which also includes information on contacting Microsoft Support.
