### ISSUE TITLE
processflow

### ISSUE THREAD

**Issue by zhmbd** [MicrosoftDocs/windows-itpro-docs#722]
to have intimated on innovative real on time in time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93349abc-4222-9185-29e4-1a62b9d3071b
* Version Independent ID: cf46b086-ee87-a57c-36b1-72fdfa5ea139
* Content: [Microsoft Store for Business and Education (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/)
* Content Source: [store-for-business/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/index.md)
* Service: **unspecified**
* GitHub Login: @TrudyHa
* Microsoft Alias: **trudyha**

**Comment by andreabichsel** [comment]
Closing this issue for now. If you have doc feedback, please let us know!
