### ISSUE TITLE
My Work My Way

### ISSUE THREAD

**Issue by rezwansarker** [MicrosoftDocs/windows-itpro-docs#724]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18f4e162-df37-fe9a-85df-7b78a7d91912
* Version Independent ID: c1142f24-8cd3-cbf4-9713-36834841246a
* Content: [Policy CSP - WindowsDefenderSecurityCenter](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-windowsdefendersecuritycenter)
* Content Source: [windows/client-management/mdm/policy-csp-windowsdefendersecuritycenter.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-windowsdefendersecuritycenter.md)
* Service: **unspecified**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by andreabichsel** [comment]
Closing this for now. If you have any doc feedback, please let us know!
