### ISSUE TITLE
upgrade readiness script

### ISSUE THREAD

**Issue by ESLAVANADE** [MicrosoftDocs/windows-itpro-docs#726]
Why it is mandatory to run the script every 30 days ?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ESLAVANADE - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@ESLAVANADE - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
