### ISSUE TITLE
Copy paste errors 

### ISSUE THREAD

**Issue by GMelford** [MicrosoftDocs/windows-itpro-docs#728]
Hi
It is a long time ago usmt did only migrate office 2010.. 🙄

Also, to get more comprehensive xml files for USMT, also handling current Firefox and Chrome editions (plus avoiding backing up tonnes of redundant stuff) I highly Ehlertechs "XML reference collection" at
http://ehlertech.com/customxmls/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ddec814-76f2-9d7b-88d1-27eff2770257
* Version Independent ID: ccb8d9bb-e1f9-785d-10d7-ad4e77145e1b
* Content: [What does USMT migrate (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-what-does-usmt-migrate)
* Content Source: [windows/deployment/usmt/usmt-what-does-usmt-migrate.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/usmt/usmt-what-does-usmt-migrate.md)
* Service: **unspecified**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
@GMelford Thank you for your comment, please note that USMT now migrates many software settings including Office2010. You can find the list at https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-what-does-usmt-migrate#a-href-idbkmk-2asupported-applications

Thanks.

**Comment by mypil** [comment]
@GMelford - Thank you for submitting feedback.

From our understanding, the issue has been answered by joinimran. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
