### ISSUE TITLE
LTCS for VDI Guidance

### ISSUE THREAD

**Issue by adamgourd** [MicrosoftDocs/windows-itpro-docs#731]
It would be nice to have some guidance with regard to the use of LTSC for VDI. In general, I would argue that VDI scenarios fall more into the "general-purpose user" category versus the "special-purpose devices" described in relation to LTSC. It seems as if some VDI solution vendors are recommending LTSC for VDI, but I am concerned that customer's will run into issues down the road (e.g. MS Office support as per https://blogs.technet.microsoft.com/windowsitpro/2018/02/01/changes-to-office-and-windows-servicing-and-support/. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6957383-3bd9-eef9-6410-9c42f8a0b172
* Version Independent ID: a2090374-0fd1-8d67-66de-30c4cf2835f7
* Content: [Overview of Windows as a service (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-overview)
* Content Source: [windows/deployment/update/waas-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-overview.md)
* Service: **unspecified**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by havealoha** [comment]
I would like to see a response from Microsoft regarding this.

**Comment by shortpatti** [comment]
@jaimeo, can you take a look at this issue?

**Comment by jaimeo** [comment]
Yes, I will get hold of some PMs in this area and direct them to this query.

**Comment by mypil** [comment]
@jaimeo - We would like to follow up on this. Do you have any updates? Thanks.

**Comment by jaimeo** [comment]
I have freshly brought this to the attention of relevant senior PMs.

**Comment by jaimeo** [comment]
I've heard back from internal SMEs, who state that LTSC is not the preferred solution for VDI--it's made for things like medical and engineering devices where things need to be up all the time and rarely change. See https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/LTSC-What-is-it-and-when-should-it-be-used/ba-p/293181 and https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/Changes-to-Office-and-Windows-servicing-and-support/ba-p/151509 .

**Comment by mypil** [comment]
@adamgourd - From our understanding the issue you raised has been answered. If you feel it hasn't been answered please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.

**Comment by deucalion** [comment]
@adamgourd As I'm in a similar situation (having to oversee a larger academic VDI project) - MSFT thankfully published this today: https://techcommunity.microsoft.com/t5/Core-Infrastructure-and-Security/Windows-10-Build-1803-VDI-Optimization-Script-Primer/ba-p/377613

I was originally planning to use LTSC, but if it's not a supported approach, I can only hope MSFT publishes more guidance like this in the future.
