### ISSUE TITLE
Confused about how to turn on "Only elevate executables that are signed and validated" setting

### ISSUE THREAD

**Issue by pushkin-** [MicrosoftDocs/windows-itpro-docs#733]
I'm looking at [this](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/user-account-control-only-elevate-executables-that-are-signed-and-validated.md) page entitled:

>Only elevate executables that are signed and validated

And I have no idea how to set this up. I have Windows 10 Home and want to make sure that Windows doesn't run executables that aren't signed. Is it on by default?

It points me to a location:
>Computer Configuration\Windows Settings\Security Settings\Local Policies\Security Options

But that's not an absolute path. From where do I follow that path?

I searched for "User Access Control" and get taken to a page to change my User Access Control settings. The slider is at the top: 
![image](https://user-images.githubusercontent.com/6374473/38842635-b6ae9b64-41b0-11e8-8575-dc0e6726788a.png)

Is that enough, or do I need to do something else?

**Comment by brianlic-msft** [comment]
I think this should go to @Justinha instead.

**Comment by pushkin-** [comment]
I posted on [superuser](https://superuser.com/questions/1314839/how-to-turn-on-only-elevate-executables-that-are-signed-and-validated-setting), and it looks like I can just set the reg key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\ValidateAdminCodeSignatures` to 1.

So I got the problem solved, but I'll keep this open for now. If you think the instructions are clear for most users, then feel free to close this.

**Comment by Justinha** [comment]
@pushkin Thanks for the feedback. Glad to hear you got it working. Another way is to open any of these security settings is to open secpol.msc (type that in the Run dialog for example) and then that policy path will make more sense. I think this is something that Enterprise admins know, so I won't add it at this time. But if more readers express similar confusion, we can revisit this.

**Comment by pushkin-** [comment]
@Justinha I'm on Windows 10 Home and can't find that file. Is that by chance only available to Windows 10 Pro users?

**Comment by Justinha** [comment]
I'm not on Home edition but I'm pretty sure it's there. Click Start > type Run and press Enter,  then type secpol.msc in the Run dialog and OK. Does that work?

**Comment by Justinha** [comment]
@pushkin- I'm not on Home edition but I'm pretty sure it's there. Click Start > type Run and press Enter, then type secpol.msc in the Run dialog and OK. Does that work?
