### ISSUE TITLE
PluginProfile/ServerUrlList - comma or semi-colon separated list?

### ISSUE THREAD

**Issue by blackchr** [MicrosoftDocs/windows-itpro-docs#734]
This document states:
VPNv2/ProfileName/PluginProfile/ServerUrlList
Required for plug-in profiles. Comma separated list of servers in URL, hostname, or IP format.

However, two Microsoft examples show semi-colon separated lists:
https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-profile-xsd
https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-profile-options
<PluginProfile>
        <ServerUrlList>testserver1.contoso.com;testserver2.contoso..com</ServerUrlList>

One of these two needs to be corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8b1b81d-3c35-0315-d149-f10af3a409b2
* Version Independent ID: c34e7acb-ece7-d76f-fb41-470e19119ee0
* Content: [VPNv2 CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp)
* Content Source: [windows/client-management/mdm/vpnv2-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/vpnv2-csp.md)
* Service: **unspecified**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@blackchr - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
