### ISSUE TITLE
Dead "microsoft" link

### ISSUE THREAD

**Issue by Scottmca** [MicrosoftDocs/windows-itpro-docs#736]
Under Supported Devices and drivers the link for "Microsoft" is dead.  It should link to https://support.microsoft.com/en-us/help/4094045/surface-devices-that-work-with-windows-10-s

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ce6147b-57c3-b40d-2d1e-3aa04a3d5606
* Version Independent ID: c453ea14-6842-4af7-42c0-6ef8e2336c6c
* Content: [Test Windows 10 S on existing Windows 10 education devices](https://docs.microsoft.com/en-us/education/windows/test-windows10s-for-edu#feedback)
* Content Source: [education/windows/test-windows10s-for-edu.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/test-windows10s-for-edu.md)
* Service: **unspecified**
* GitHub Login: @CelesteDG
* Microsoft Alias: **celested**

**Comment by CelesteDG** [comment]
@Scottmca - Thank you very much for the feedback. I've made this change today and pushed the PR. Hopefully the change goes live this afternoon.
