### ISSUE TITLE
formatting error

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/windows-itpro-docs#737]
There is a section appearing as code in this documentation that I believe was meant to be formatted as normal text... It can be viewed on a web browser as such.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f93ed48c-b6c8-bbb9-9533-58c5e8e59a73
* Version Independent ID: 0d396e6a-e616-94ca-ab2c-8a19a5df031d
* Content: [Copying the MBAM 2.5 Group Policy Templates](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/copying-the-mbam-25-group-policy-templates)
* Content Source: [mdop/mbam-v25/copying-the-mbam-25-group-policy-templates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/copying-the-mbam-25-group-policy-templates.md)
* Service: **unspecified**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by shortpatti** [comment]
the formatting issue has been resolved in issue #758.
