### ISSUE TITLE
appearing as code

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/windows-itpro-docs#738]
"Got a suggestion for MBAM?" appears as code on the website, not as normal text. Pretty sure this issue persists throughout the documentation on MBAM. 

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b542fc76-4120-3f11-f297-c0e1af49e8c3
* Version Independent ID: 1c796ee2-7982-2df1-c82c-3cd231867acf
* Content: [How to Deploy the MBAM Client to Desktop or Laptop Computers](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/how-to-deploy-the-mbam-client-to-desktop-or-laptop-computers-mbam-25)
* Content Source: [mdop/mbam-v25/how-to-deploy-the-mbam-client-to-desktop-or-laptop-computers-mbam-25.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/how-to-deploy-the-mbam-client-to-desktop-or-laptop-computers-mbam-25.md)
* Service: **unspecified**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by shortpatti** [comment]
@thedrum808,  Thank you for your feedback.  I will take care of the formatting.
