### ISSUE TITLE
v1709 updates

### ISSUE THREAD

**Issue by forumer** [MicrosoftDocs/windows-itpro-docs#743]
This doc references v1607 but v1709 was released right around the 10/13/2017 date of this doc. It would be good to have this doc updated to fully reflect the current Win 10 release and to make sure it's further updated when v1803 is released. For example, v1709 added the Remove People Bar GPO, per https://partnersupport.microsoft.com/en-us/par_clientsol/forum/par_win/disable-show-people-option-group-policy/e444107b-237c-48ca-84df-5cf1f433d6a6 - But this GPO does not appear to work with Win 10 Pro v1709. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c00b4ec7-c493-9205-01e2-7c54dfa4bbde
* Version Independent ID: a6b045e0-1802-424f-003e-28f635c36157
* Content: [Group Policy settings that apply only to Windows 10 Enterprise and Education Editions (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/group-policies-for-enterprise-and-education-editions)
* Content Source: [windows/client-management/group-policies-for-enterprise-and-education-editions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/group-policies-for-enterprise-and-education-editions.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **dongill**

**Comment by vandreytrindade** [comment]
Any news about it?

**Comment by dalinvuth1997** [comment]
great.

**Comment by durried** [comment]
Not only do we need confirmation with each version update but this list by my testing is ridiculously short, many of the Microsoft Edge settings do NOT work in Windows 10 Professional and I've just tested them again in the latest version 1809!

**Comment by vandreytrindade** [comment]
Ok Microsoft, so this is the last changes?

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by halolly** [comment]
still waiting for an updated document...

**Comment by maude1424** [comment]
Really need this updated.  I cannot find anything online that shows the differences between Pro and Enterprise GPO settings.  Using this to determine whether or not we need to go to Enterprise!

**Comment by illfated** [comment]
@jvsam : Would it be practical to reference the Feedback Hub for alerting the technicians of this missing GPO documentation for Enterprise customers using 1709 and newer versions? Or do you have any connections with the tech writing team who might have the necessary documentation for the required updates?

**Comment by nam31** [comment]
Thank you for providing feedback.
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
Thank you for your contribution to make the docs better! Much appreciated!
