### ISSUE TITLE
Enroll HybridJoin device - user assingment

### ISSUE THREAD

**Issue by dudus999** [MicrosoftDocs/windows-itpro-docs#744]
Hi,
 I use autoenrolment scenario for domain joined computer. Intune is set up to standalone. My device is joined to ad azure (connect type Hybrid Join) with success, device is enrolled to Intune but without user assigment. When I open company portal I see "This device hasn't been set up for corparate use yet...." . When I try assign I see message that "device is already beging managed by an organization﻿ ". In Intune console I see this device and MDM is enabled. What can I do to assign user to device?

My previous expirence is that after auto enrolment I open company portal and only choose device category . Now I don't understand what happens why device is treated as unerolled if it is enrolled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Service: **unspecified**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by bally-singh** [comment]
Does this work when Intune is configured in a Hybrid state with SCCM? I am getting the error message:

MDM Enroll: Server Returned Fault/Code/Subcode/Value=(NotSupported) Fault/Reason/Text=(MDM CoManagement blocked for ConfigMgr licensed user).

If this only works with co-management, can this document please be updated?

**Comment by rem-87** [comment]
I have a question about the requirements:
Does "Enterprise has MDM service already configured " mean MDM User Scope is enabled in AAD?

**Comment by ermacia91** [comment]
If you are doing MDM enrollment in W10 1709 or higher, the Company Portal is not needed (nor will it work). The OS will use the enrollment mechanism of W10. The way to assign a user (though I would not expect it to work after device based enrollment) is to go into Settings > Accounts > Access work or school and add the user account.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@dudus999 - thank you for submitting feedback.

From our understanding the issue has been answered by ermacia91. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
