### ISSUE TITLE
Device Requirements

### ISSUE THREAD

**Issue by giterdn** [MicrosoftDocs/windows-itpro-docs#748]
I suggest more content on the constraints of the existing "device requirements", as it relates to a single computer sharing 2 Hello-capable cameras, is added.  Case in point, Dell makes a 24" display that is Skype-certified and Hello-compatible.  In their documentation, Dell advise that a Hello-equipped laptop (e.g. Surface Pro) connected or docked to the display can only allow the 24" display's Hello camera be used if the laptop's on-board camera is disabled (please refer to page 57 of http://downloads.dell.com/manuals/all-products/esuprt_display_projector/esuprt_display/dell-p2418hzm-monitor_user%27s_guide_en-us.pdf).  I presume this to be an architectural constraint of the Hello service and submit it should be documented here under device requirements, again presuming this isn't an oversight in the design of the Surface Pro or Dell display.  Ideally a Surface Pro would automatically use the on-board camera when being used by itself, and automatically use the Dell display's camera when connected/docked to the display.  Thank you.  P.S. I have submitted feedback in the Feedback Hub at https://aka.ms/Lujqaz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59c4b7fc-8a91-5d34-d483-f644c248ad30
* Version Independent ID: 1f14bf28-71e0-121d-7890-c2d3b921c106
* Content: [Windows Hello biometrics in the enterprise (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-biometrics-in-enterprise)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-biometrics-in-enterprise.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-biometrics-in-enterprise.md)
* Service: **unspecified**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
I'm going to go with the infamous @MikeStephens-MS tag

**Comment by MikeStephens-MS** [comment]
- FIXED
There's not a good place to add this on this page, so I added it to our FAQ.  This is a known issue and the feature team knows about it and they are investigating it.  No ETA.  Update should visible in when we publish next.  Thank you for the feedback 
- Mike
