### ISSUE TITLE
SCCM and WDAC

### ISSUE THREAD

**Issue by StarkCaptain** [MicrosoftDocs/windows-itpro-docs#755]
It is not clear in the documentation, if you use SCCM to managed WDAC policies, does this conflict with using this method to roll out WDAC policies or are they separate from one another? Will SCCM overwrite the SiPolicy.p7b file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07fdf27b-1ead-1b6e-c793-a2ad259a4f6a
* Version Independent ID: 8da1f371-73d4-c79f-a97b-80170e7860af
* Content: [Deploy Managed Installer for Windows Defender Device Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/deploy-managed-installer-for-device-guard)
* Content Source: [windows/security/threat-protection/device-guard/deploy-managed-installer-for-device-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/device-guard/deploy-managed-installer-for-device-guard.md)
* Service: **unspecified**
* GitHub Login: @mdsakibMSFT
* Microsoft Alias: **justinha**

**Comment by mdsakibMSFT** [comment]
Currently you can only have one active SiPolicy.p7b file on a system. The last management authority to write the policy wins. If there was already a policy deployed over GP and then SCCM targeted the same device the SCCM policy would over-write what was there previously.
