### ISSUE TITLE
Import Start Layout

### ISSUE THREAD

**Issue by danbu** [MicrosoftDocs/windows-itpro-docs#759]
I just found this documentation and these pages are must better than older versions and makes Windows 10 configuration must clearer.  The only thing I see missing here is use of the Import-StartLayout PowerShell commandlet (https://docs.microsoft.com/en-us/powershell/module/startlayout/import-startlayout?view=win10-ps).  We use this rather than group policy as it just sets a default configuration and lets our clients change it completely if they which (which is why we don't use the Group Policy option).

Thanks for the clear documentation keep up the great work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee213fb5-bcbf-620f-d832-bfe2ed9cb16d
* Version Independent ID: 2457bc44-1d1f-6bd1-75b4-984f97df2615
* Content: [Manage Windows 10 Start and taskbar layout  (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/windows-10-start-layout-options-and-policies#feedback)
* Content Source: [windows/configuration/windows-10-start-layout-options-and-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/windows-10-start-layout-options-and-policies.md)
* Service: **unspecified**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
Thanks for the feedback, @danbu!
