### ISSUE TITLE
"Device provisioning during OOBE" section may be out of date

### ISSUE THREAD

**Issue by tFable** [MicrosoftDocs/windows-itpro-docs#760]
Hello,

Can you please clarify which version of Windows 10 this article (or any article for that matter) applies to? Especially in the modern provisioning space, there are moving parts from one version of Windows 10 to the next.

As an example, we (or the Premier support engineers we've engaged with) are not able to verify by testing on Win10 1709 (various build #) the following statements in this article:

"The provisioning engine always applies provisioning packages persisted in the C:\Recovery\Customizations folder on the OS partition..."

coupled with:

"The provisioning engine always applies provisioning packages embedded in the installed Windows image during Windows Setup OOBE pass regardless of whether the package is signed and trusted."

Premier support will verify that provisioning packages that reside in c:\recovery\customizations are not processed during the oobeSystem pass. On the contrary, the .ppkg's present in c:\recovery\customizations will process if, after the files are dropped in c:\recovery\customizations the system is sysprep'ed with the "/generalize" clause. This means that the .ppkg's are being applied, not during the oobe pass but during one of the following passes:

- Generalize
- Specialize
- AuditSystem
- AuditUser

We are also following up with the Product team but I also wanted to ping the docs team in case this is simply a documentation issue and the behavior has changed in 1709.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f207b491-f262-43cf-1002-8f3fb2a052c6
* Version Independent ID: 5358ed30-928c-e397-04e7-7f4c602777e2
* Content: [How provisioning works in Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-how-it-works#provisioning-packages)
* Content Source: [windows/configuration/provisioning-packages/provisioning-how-it-works.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/provisioning-packages/provisioning-how-it-works.md)
* Service: **unspecified**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
This was written for the first version of Windows 10. I'll check with the engineering team on whether there have been changes.

**Comment by tFable** [comment]
Hello,

Thanks for your reply. 

I see that the issue was closed by "andreabichsel". I don't believe the query in the original request was answered. 

Can you update us on what the engineering team's feedback was, please?

**Comment by andreabichsel** [comment]
Sorry, reopening until answered.

**Comment by mypil** [comment]
@jdeckerms - Do you have any updates from the engineering team? Thanks.

**Comment by mypil** [comment]
@jdeckerms - We would like to follow up on this. Do you have any updates from the engineering team? Thanks.

**Comment by mypil** [comment]
@jdeckerms - We would like to follow up on this. Do you have any updates from the engineering team? Thanks.

**Comment by mypil** [comment]
@officedocsbot assign @jdeckerms

**Comment by PrinceMarkieD** [comment]
I am interested in installing apps for Assigned Access or Shell-Replace during OOBE, with all the lockdowns. the PPKG works if launched after landing on the desktop. It hangs at "Installing Provisioning packages" if launched automatically during OOBE.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by joinimran** [comment]
@tFable - Did you get a chance to hear back from the engineering team or the Primer support team. Can you please share your input so that I can proceed with updating the document content as requested. 

Thanks.

**Comment by joinimran** [comment]
@tFable / @jdeckerms Do you guys have any update on this? Anything from the engineering team?
