### ISSUE TITLE
Need more info....

### ISSUE THREAD

**Issue by RalphMalph2** [MicrosoftDocs/windows-itpro-docs#761]
There are many on/off options relating to the Start Menu such as "Show more tiles in start", "Show most used apps", or "Chose which folders appear in Start" and more. EVERY ONE OF THOSE OPTIONS needs to be discussed in this article in order to be complete. If those options can be set/controlled via the .xml file show example for each one, if it is in the registry, show where and so on and so forth. Absolutely nothing must be left off. If it can be placed in one of the 4 locations on start menu or taskbar, then it must be covered here and all things needed to know to fully control these settings for ALL users by sys admins etc must be shown here or it is an incomplete article. I see the link to info on TaskBar is there, but no info on some of the other items I mentioned such as showing the "Picture" button on left side of start menu, or the "File Explorer" on the left side, so, many things are missing in this article on how to configure the start menu and taskbar. Please update with complete details and examples for every possible start menu option. Nothing left out. It is a good start and I have used the info successfully but need gaps to be covered so I have 100000% control of ALL aspects of the Start Menu and the users default Windows experience, no exceptions!!!! Nothing must ever be hidden from  sys admins not ever be prevented fro us have full control. (THAT INCLUDES UPDATING, not part of this article of course, BUT WE MUST HAVE 1000000000000000% CONTROL OF THAT PART OF OS, STOP THEM FOREVER FROM COMING IN IF WE WANT, BE ABLE TO SEE AND INDIVIDUALLY PICK AND CHOOSE WHICH ONES WE WANT AND PERMANENTLY BLOCK ANY WE DON"T. MUST NEVER EVER CHANGE SYSTEM IN WAYS LIKE REMOVING CONTROL PANEL WITH OUT OUR CONSENT!) THAT MUST ALSO INCLUDE LOCATION OF ADVERTISING ID SO IT CAN BE CHANGED TO ALL ZEROS OR NINES AND ALL INFO FOR THE EVIL ITEM POLLUTED OVER ENTIRE WORLD. HOW EVIL OF MS TO DO THAT TO THEIR CUSTOMER ESPECIALLY THE ENTERPRISE PEOPLE SUCH AS MY SELF.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee213fb5-bcbf-620f-d832-bfe2ed9cb16d
* Version Independent ID: 2457bc44-1d1f-6bd1-75b4-984f97df2615
* Content: [Manage Windows 10 Start and taskbar layout  (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/windows-10-start-layout-options-and-policies#start-options)
* Content Source: [windows/configuration/windows-10-start-layout-options-and-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/windows-10-start-layout-options-and-policies.md)
* Service: **unspecified**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
I compared the Start options in Settings to the topic, and I see that "Show more tiles on Start" is not mentioned in the documentation. I'll contact the engineering team to see if there is a Group Policy or MDM setting that you can use to manage it. 

All of the other Start options in Settings are covered in the policy table for "Start options".  For example, if you look at the "local setting" column, you'll see "Show most used apps" -- the Policy column for that setting lists the policy settings that control it. For File Explorer and other folders, "AllowPinnedFolder" lets you select the folders (see the full list here: https://docs.microsoft.com/en-us/windows/configuration/wcd/wcd-policies#start)

The XML file only configures the layout of tiles. Other Start settings can be configured using Group Policy or MDM. Note that the MDM settings can also be configured in a provisioning package - I'll add a note to the topic to clarify that.

**Comment by jdeckerms** [comment]
I found out that "Show more tiles" allows 4 columns of medium-sized tiles rather than the default 3. I'm adding a note to the topic to explain that you turn on that setting before you export your Start layout (if you want that size of layout).
