### ISSUE TITLE
Secure Boot issues.

### ISSUE THREAD

**Issue by crkinard** [MicrosoftDocs/windows-itpro-docs#765]
Following these instructions when trying to load a Surface gives a "Secure Boot Violation" error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6a95648-e93d-fdd5-b52f-afca6e49a139
* Version Independent ID: 607d9bc8-de81-eb28-5326-434e1cf6a696
* Content: [Configure a PXE server to load Windows PE (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/configure-a-pxe-server-to-load-windows-pe)
* Content Source: [windows/deployment/configure-a-pxe-server-to-load-windows-pe.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/configure-a-pxe-server-to-load-windows-pe.md)
* Service: **unspecified**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by andreabichsel** [comment]
Please see https://support.microsoft.com/en-us for help with this issue.
