### ISSUE TITLE
How to self-register

### ISSUE THREAD

**Issue by zhaijintao1qwe** [MicrosoftDocs/windows-itpro-docs#767]
[Enter feedback here]

How to self-register equipment in MDM, what needs to be done on the server? Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b95868d3-c141-0038-69b2-7a6a84d817d8
* Version Independent ID: b68e29a4-fe87-3c20-4abc-06ab815f33ee
* Content: [Azure AD and Microsoft Intune - Automatic MDM enrollment in the new Portal](https://docs.microsoft.com/en-us/windows/client-management/mdm/azure-ad-and-microsoft-intune-automatic-mdm-enrollment-in-the-new-portal)
* Content Source: [windows/client-management/mdm/azure-ad-and-microsoft-intune-automatic-mdm-enrollment-in-the-new-portal.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/azure-ad-and-microsoft-intune-automatic-mdm-enrollment-in-the-new-portal.md)
* Service: **unspecified**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @zhaijintao1qwe ,
To self-register corporate devices to MDM, you need to deploy GPO on the local AD server. More details here: [Enroll a Windows 10 device automatically using Group Policy](https://docs.microsoft.com/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)

Thank you

**Comment by mypil** [comment]
@zhaijintao1qwe - From our understanding, the issue you raised has been MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
