### ISSUE TITLE
Best guide I've saw on syntax. thanks

### ISSUE THREAD

**Issue by rafaelvanderville** [MicrosoftDocs/windows-itpro-docs#768]
I do think though, that when I dived into the Scanstate/loadstate syntax it became unclear what to do when I want to migrate user profiles from one domain to another: https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-scanstate-syntax
It turned out to be rater complex > /MU:"Domain1\Test user1":"Domain2\test user2" /ue:*\* /ui:"Domain1\Test user1" 
NOT very user friendly.
Recommended:
I ended used the GUI from EhlerTech, as it set the whole thing up. Logging, file-list (what was copied), decryption, etc. 
and I could just copy the command from the usmtgui interfaces Command line window.

Rafael - IT- Université catholique de Louvain

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89c5c9e7-3e5e-b448-e3ce-f4f0ca5bfbc0
* Version Independent ID: bee454fd-4983-ab4d-b330-62a21cb61aef
* Content: [Migrate User Accounts (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-migrate-user-accounts)
* Content Source: [windows/deployment/usmt/usmt-migrate-user-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/usmt/usmt-migrate-user-accounts.md)
* Service: **unspecified**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by Malind19** [comment]
@mypil There are urls for the complete syntax explanations available in the article. It is mentioned in the article. Please let me know if any other ways to improve this. https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3214

**Comment by illfated** [comment]
@rafaelvanderville : As you can see, the PR #3214 has been merged into the Github version of the page. It may take a few days for the change to migrate to the docs.microsoft.com page, but in the meanwhile, you can consider your comment post noticed and responded to in a positive way.

**Comment by mypil** [comment]
@officedocsbot close
