### ISSUE TITLE
Posibility to have multiple Management Tools

### ISSUE THREAD

**Issue by RefleCs** [MicrosoftDocs/windows-itpro-docs#771]
It is possible to have multiple Management tools. Just tested this with SCCM and Intune as Management tools. STfB is now syncing with both tools.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35591c95-f30d-db89-1d46-10ac8605e393
* Version Independent ID: d8db65bc-8448-2236-2880-2cf4eee17a2f
* Content: [Distribute apps with a management tool (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/distribute-apps-with-management-tool)
* Content Source: [store-for-business/distribute-apps-with-management-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/distribute-apps-with-management-tool.md)
* Service: **unspecified**
* GitHub Login: @TrudyHa
* Microsoft Alias: **trudyha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
@RefleCs Can you please elaborate your query in detail so that we can better help you regarding this.

We recommend using MDM as a management tool.

Thanks.

**Comment by mypil** [comment]
@RefleCs - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
