### ISSUE TITLE
Section omits details of the hidden C:\$GetCurrent\Logs

### ISSUE THREAD

**Issue by jschlackman** [MicrosoftDocs/windows-itpro-docs#774]
This section on log examination does not mention the log files located in the hidden C:\$GetCurrent\Logs location. When I eventually found this location using Procmon.exe, the log file it contained was invaluable in identifying an issue that was blocking he Windows Upgrade Assistant at 0% installation (after the download completed and was verified).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aed724a-73f2-3b93-d273-8b8302086ea1
* Version Independent ID: 728c8856-ee32-1ba9-a0c4-4a5791f89a89
* Content: [Log files - Windows IT Pro](https://docs.microsoft.com/en-us/windows/deployment/upgrade/log-files)
* Content Source: [windows/deployment/upgrade/log-files.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/log-files.md)
* Service: **unspecified**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
@jschlackman Thank you for sharing this information. It has been forwarded for addition in doc. 

Thanks.

**Comment by mypil** [comment]
@jschlackman - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
