### ISSUE TITLE
Missing ZIP files 

### ISSUE THREAD

**Issue by gcatalfo** [MicrosoftDocs/windows-itpro-docs#775]
I see that the ZIP files are missing for multiple devices. I have a stack of Surface Book 2's that I need to image and deploy with MDT/WDS that I can't without the driver and firmware package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586d1246-6e18-b33c-2382-52a53bb392f5
* Version Independent ID: 0ec4aa1e-aac0-98dd-0a47-83e93d854086
* Content: [Download the latest firmware and drivers for Surface devices (Surface)](https://docs.microsoft.com/en-us/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices)
* Content Source: [devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices.md)
* Service: **unspecified**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by BRecords** [comment]
ZIP files are no longer produced for Surface driver and firmware packs as their contents are redundant with the contents of the MSI. Use **msiexec /a**, the administrative install function, to extract the contents of the MSI just like you would with a ZIP. You can then import just the same as you would with the ZIP into your MDT deployment share.
There are specific instructions provided in the blog post for the initial release of the Surface Book 2 drivers:
https://blogs.technet.microsoft.com/surface/2017/11/28/surface-book-2-drivers-and-firmware-initial-release/

**Comment by gcatalfo** [comment]
Got it. Thanks!
