### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by czrik** [MicrosoftDocs/windows-itpro-docs#776]
Configure Multi-Factor Authentication returns a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddbb85-f5df-b124-2783-0330d9da2e06
* Version Independent ID: aff516a2-3bb0-843d-5652-e25f90bab00f
* Content: [Sign in to Surface Hub with Microsoft Authenticator](https://docs.microsoft.com/en-us/surface-hub/surface-hub-authenticator-app#feedback)
* Content Source: [devices/surface-hub/surface-hub-authenticator-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/surface-hub-authenticator-app.md)
* Service: **unspecified**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
Thanks for letting us know. The link will be fixed today.
