### ISSUE TITLE
Create and manage machine groups in Windows Defender ATP

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#777]
on the docs page: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/machine-groups-windows-defender-advanced-threat-protection

The following remediation levels are described. 

- Remediation level for automated investigations
- No remediation
- Require approval (all folders)
- Require approval (non-temp folders)
- Require approval (core folders)
- Fully automated

Could you provide a bit more detail what all folders, non-temp folders and especially "**core-folder**s" means? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c912a9f9-2198-07ff-3ecb-e4d025b7c958
* Version Independent ID: 2781f02e-3869-498d-69fa-fc73d01ff661
* Content: [Create and manage machine groups in Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/machine-groups-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/machine-groups-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/machine-groups-windows-defender-advanced-threat-protection.md)
* Service: **unspecified**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Hi alexverboon, 
Thank you for your feedback. We've recently updated [this topic](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/automated-investigations-windows-defender-advanced-threat-protection#understand-the-automated-investigation-flow). 

In the section "How threats are remediated" we've included a table with an explanation of the automation levels and its corresponding description. 

Hope that helps!
