### ISSUE TITLE
Adding the taskbar portion

### ISSUE THREAD

**Issue by StarScreamV2x** [MicrosoftDocs/windows-itpro-docs#778]
If I import the StartLayout without the taskbar customizations, it works.  If I add the taskbar customizations I get the following: 
PS C:\windows\system32> Import-StartLayout -LayoutPath c:\windows\temp\layout.bin -MountPath c:\
PS C:\windows\system32> Import-StartLayout -LayoutPath c:\windows\temp\layout.bin -MountPath c:\
Import-StartLayout : The file C:\windows\temp\layout.bin is not a valid layout file
At line:1 char:1
+ Import-StartLayout -LayoutPath c:\windows\temp\layout.bin -MountPath  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-StartLayout], InvalidDataException
    + FullyQualifiedErrorId : System.IO.InvalidDataException,Microsoft.Windows.StartLayout.Commands.ImportStartLayoutC
   ommand

PS C:\windows\system32> Import-StartLayout -LayoutPath c:\windows\temp\layout.bin -MountPath c:\
Import-StartLayout : The file C:\windows\temp\layout.bin is not a valid layout file
At line:1 char:1
+ Import-StartLayout -LayoutPath c:\windows\temp\layout.bin -MountPath  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-StartLayout], InvalidDataException
    + FullyQualifiedErrorId : System.IO.InvalidDataException,Microsoft.Windows.StartLayout.Commands.ImportStartLayoutC
   ommand

PS C:\windows\system32> Import-StartLayout -LayoutPath c:\windows\temp\layout.xml -MountPath c:\
Import-StartLayout : The file C:\windows\temp\layout.xml is not a valid layout file
At line:1 char:1
+ Import-StartLayout -LayoutPath c:\windows\temp\layout.xml -MountPath  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-StartLayout], InvalidDataException
    + FullyQualifiedErrorId : System.IO.InvalidDataException,Microsoft.Windows.StartLayout.Commands.ImportStartLayoutC
   ommand

PS C:\windows\system32> Import-StartLayout -LayoutPath c:\windows\temp\layout.xml -MountPath c:\
PS C:\windows\system32>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140f038c-e307-78f0-5165-309e0cf34ca5
* Version Independent ID: b1011259-ee05-21a4-5308-aabc8b0dd74b
* Content: [Configure Windows 10 taskbar (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/configure-windows-10-taskbar)
* Content Source: [windows/configuration/configure-windows-10-taskbar.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/configure-windows-10-taskbar.md)
* Service: **unspecified**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@StarScreamV2x I'm sorry you're having issues with your Start and taskbar layout but I can't troubleshoot it for you. The best way to get help would be to contact Microsoft Support (https://support.microsoft.com/en-us/contactus/), or you can post in the Forum (https://social.technet.microsoft.com/Forums/windows/en-US/home?forum=win10itprogeneral).

**Comment by jdeckerms** [comment]
@kazysm Thanks for pointing that out. The full XML example in the topic includes it, but it should be called out in the steps as well. I'm adding that step to the "Configure the taskbar" procedure.
