### ISSUE TITLE
Is this a joke?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/windows-itpro-docs#779]
So this is everything that can be configured in Windows nowadays?
Where is the documentation on networking, printers, the registry, console commands, startup options, disk config and so on???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ab1d555-4c62-ec55-4fb6-d233cddd0654
* Version Independent ID: c0dad820-d199-c3cc-4d98-53d331e6aa17
* Content: [Configure Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/)
* Content Source: [windows/configuration/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/index.md)
* Service: **unspecified**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@Bartolomeus-649 The Windows 10 documentation focused on things that were new or changed from previous versions of Windows. If there is specific information you need, please submit your suggestions. It will help if, with your suggestion, you explain the importance of the information to your business/enterprise. That will help us triage the request.

**Comment by Bartolomeus-649** [comment]
We need to know where to find the complete, current and up to date documentation for Windows. That is, the entire Windows OS.

**Comment by jdeckerms** [comment]
@Bartolomeus-649 The Windows 10 documentation for IT pros is all located here: https://docs.microsoft.com/en-us/windows/windows-10/

The Windows 10 documentation for consumers (end-users) is in the Tips app in Windows 10 and online here: https://support.microsoft.com/en-us/products/windows?os=windows-10 

Windows 10 documentation for software developers is located here: https://docs.microsoft.com/en-us/windows/#pivot=developer

Windows 10 documentation for hardware developers is located here: https://docs.microsoft.com/en-us/windows/#pivot=hardware-dev

**Comment by Bartolomeus-649** [comment]
ok, so where in https://docs.microsoft.com/en-us/windows/windows-10/ do I find how to set up a null share in Windows 10?

**Comment by jdeckerms** [comment]
@Bartolomeus-649 Does "Network security: Allow LocalSystem NULL session fallback" meet your needs? https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-allow-localsystem-null-session-fallback

**Comment by jdeckerms** [comment]
Also, there is "Network access: Shares that can be accessed anonymously" https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-shares-that-can-be-accessed-anonymously and "Network access: Restrict anonymous access to Named Pipes and Shares" https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-restrict-anonymous-access-to-named-pipes-and-shares

**Comment by Bartolomeus-649** [comment]
Still nothing like these:
- https://support.microsoft.com/en-us/help/3034016/ipc-share-and-null-session-behavior-in-windows
- https://support.microsoft.com/en-us/help/289655/how-to-enable-null-session-shares-on-a-windows-2000-based-computer

No where can you find a section that describes networking in Windows any longer.  I remember when NT came out and there were huge sections in TechNet, where everything related to networking could be found...from printers to protocol binding order for a NIC.

**Comment by Bartolomeus-649** [comment]
where is this for Windwos 10 and Server 2016?
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc787191(v%3dws.10)

**Comment by jdeckerms** [comment]
I remember those days too. And when your new computer arrived with two huge manuals - one for Windows and one for DOS. :)

 Of course, those were also the days when just about everything was unfamiliar to most customers and had to be explained in detail. Over the years, there's been a decrease in the amount of content per OS version for a number of reasons: too many pages made it more difficult for customers to find the information they needed, the number of pages made it difficult to keep information updated, and a huge number of those pages had few (if any) views. The current documentation tries to address the most common needs of the enterprise admin.

**Comment by Bartolomeus-649** [comment]
It's not the enterprise admin who need the documentation the most.  It my customers, small companies of perhaps 1-30 that doesn't even have any IT staff at all.

And as a MS partner it is almost IMPOSSIBLE these days for find any documentation that really describe, elaborate and clarify how stuff really work.

**Comment by jdeckerms** [comment]
I understand that the small business market needs a type and level of documentation that we don't currently have in our library. I'll pass on the request.

**Comment by andreabichsel** [comment]
Closing for now, issue is being tracked.
