### ISSUE TITLE
No auto-restart description

### ISSUE THREAD

**Issue by jeff-bb** [MicrosoftDocs/windows-itpro-docs#781]
No auto-restart with logged on users for scheduled automatic updates installations appears to only apply to locally / console logged on users (locked or unlocked is fine). It appears to not apply to disconnected RDP sessions. The documentation does not reflect this and implies that it will work for all instances of users logged on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184809a-63ff-ecc2-ab67-9c9f4df900f8
* Version Independent ID: ac25ee6c-4c57-58b3-1313-e4a53f53c5a1
* Content: [Manage device restarts after updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-restart)
* Content Source: [windows/deployment/update/waas-restart.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-restart.md)
* Service: **unspecified**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
@jaimeo - can you take a look?

**Comment by jaimeo** [comment]
Researching.

**Comment by tFable** [comment]
Hello,

Could you please update this post with your findings? I'm also interested in this.

Thanks!
t

**Comment by jeff-bb** [comment]
From my side, the support incident has been closed by MS as "not a bug". They claim that a disconnected RDP session is not a logged in user, so the device reboots are valid. We have to warn our users that if they work from home or after hours that they will get rebooted. I was also told that the documentation would not be updated to reflect this information.

**Comment by tFable** [comment]
Hey @jeff-bb : I know it may not make much of a difference at this point but I'd like to respectfully disagree what the statements of MS. A disconnected session is still a _logged on_ session. As an example of this, disconnected RDP sessions still cause user authentication attempts against AD. This is why when a user account has it password changed, if a disconnection RDP session exists that had been logged on with the old password, it will cause authentication attempts against AD to cause a password lockout.

Hey @jaimeo and @DaniHalfin does Microsofot want to take any action on either the behavior, the documentation or both?

**Comment by jeff-bb** [comment]
Of course I (and the company I work for) disagree. This behavior is different from the previous OS and is undesirable in all aspects. When the restart orchestrator runs, it only ignores wtsEnum'd sessions that are wtsDisconnected. So the logging shows, "no user logged in, skipping NoAutoRestartCheck" and falls back to the newer style of Windows 10 restart behavior (restart, engagedRestart, etc). The documentation tells you to go one path or the other, but by treating disconnected different from connected/console, it creates a path where we have to define both behaviors and "hope for the best".

**Comment by mypil** [comment]
@DaniHalfin @jaimeo - Do you have any updates on this? Thanks.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot close
