### ISSUE TITLE
included SQL Server Express edition version

### ISSUE THREAD

**Issue by SuHwak** [MicrosoftDocs/windows-itpro-docs#783]
Is VAMT still installing SQL Server 2012 Express edition if you select the option to let VAMT install SQL server Express Edition? 
Seeing that SQL 2012 SP4 is out of mainstream support, and company policy dictates that I must not install software that is out of mainstream support, I wonder if its still SQL 2012 that is being installed as part of VAMT?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db3d4459-a57d-a227-a9ee-47a9d25fd8e1
* Version Independent ID: 43374c7a-f5d7-8168-6a0d-285f8fb29693
* Content: [Volume Activation Management Tool (VAMT) Technical Reference (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/volume-activation/volume-activation-management-tool)
* Content Source: [windows/deployment/volume-activation/volume-activation-management-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/volume-activation/volume-activation-management-tool.md)
* Service: **unspecified**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **greglin**

**Comment by jdeckerms** [comment]
@SuHwak This is out of date, thanks for bringing it to our attention. The option to install SQL Server Express from the ADK was removed in Windows 10, version 1703. The topic will be updated today.
