### ISSUE TITLE
Block persistence in WMI Event subs isn't listed in Intune

### ISSUE THREAD

**Issue by nivdolgin** [MicrosoftDocs/windows-itpro-docs#7895]
The "[Block persistence through WMI event subscription](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction#block-persistence-through-wmi-event-subscription)" rule/setting isn't listed when creating ASR rules in Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d747289-63b2-f71a-b40c-31b52982215c
* Version Independent ID: b52f6593-03f2-aa57-ec0e-eaef560dcaf0
* Content: [Use attack surface reduction rules to prevent malware infection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction#block-persistence-through-wmi-event-subscription)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by joinimran** [comment]
Hello @nivdolgin - Thank you for your query. Please note that this feature is not listed as available in intune. This is something that is already mentioned in the document (intune name: not available). This is already requested as a feature and you can also vote for this feature request in the user voice channel (https://microsoftintune.uservoice.com/forums/291681-ideas/suggestions/40862476-asr-rule-block-persistence-through-wmi-event-subs)

As soon as this will be available, this will be listed on the document.  As a workaround, 

You can simply use a custom Configuration Profile in Intune with the CSP GUID for the ASR rule.

OMA-URI: ./Vendor/MSFT/Policy/Config/Defender/AttackSurfaceReductionRules
Data type: String
Value: {e6db77e5-3df2-4cf1-b95a-636979351e5b}=1

Thanks
Imran.
