### ISSUE TITLE
old link

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#7896]
[Enter feedback here]
the link to connect-msolservice points to a page that is no longer being updated. please change the link to point to something current.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb427fd5-e30d-101e-7905-544f9eb5081e
* Version Independent ID: bf829c27-33f5-b9b5-7923-9dd47dd10657
* Content: [Use basic permissions to access Microsoft Defender Security Center - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/basic-permissions)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/basic-permissions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/basic-permissions.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Possibly https://docs.microsoft.com/powershell/module/msonline/connect-msolservice?view=azureadps-1.0

Other search results: https://www.bing.com/search?q=Connect-MsolService+site%3Amicrosoft.com

Any specific preferences to follow here, when choosing a replacement?

**Comment by joinimran** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by joinimran** [comment]
@illfated - Thanks, the 1st link is the correct one. Created PR for the same.

**Comment by e0i** [comment]
Closing via #8804. Thanks.
