### ISSUE TITLE
Incomplete information when creating and applying Web Content Filtering Policy

### ISSUE THREAD

**Issue by Jonerz** [MicrosoftDocs/windows-itpro-docs#7898]
### Further clarification is required regarding creating and loading the plist for "Web Content Filtering Policy"

1. Save the following content to your device as com.apple.webcontent-filter.mobileconfig

**How?**

_Suggested:_ 

**a.** Using a text editor (eg VSCode), copy and paste the content in to a new file and save it with the following name

**com.apple.webcontent-filter.mobileconfig**

_Ensure that any additional file extensions (ie .XML) are removed and make a note of the location you are saving the file._

**b.** Verify that the mobileconfig file was created correctly using plutil.

`$ plutil -lint /PathToFile/com.apple.webcontent-filter.mobileconfig`

eg.

`$ plutil -lint ~/Documents/com.apple.webcontent-filter.mobileconfig`

Plutil should return a result of "OK" validating that the mobileconfig file is valid. 

`/PathToFile/com.apple.webcontent-filter.mobileconfig: OK`

**Signing the profile with your new certificate**

`/usr/bin/security cms -S -N "MyNewCertificate" -i /PathToUnsigned/com.apple.webcontent-filter.mobileconfig -o /PathToSigned/com.apple.webcontent-filter.mobileconfig`

Eg.

`/usr/bin/security cms -S -N "MyNewCertificate" -i ~/Documents/Unsigned/com.apple.webcontent-filter.mobileconfig -o ~/Documents/Signed/com.apple.webcontent-filter.mobileconfig`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2354a123-9769-6450-34b6-05e586bbdb4f
* Version Independent ID: d3812533-1ea2-787b-8682-8c143dae9de1
* Content: [New configuration profiles for macOS Catalina and newer versions of macOS - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-sysext-policies)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-sysext-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-sysext-policies.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Closed via #8318
