### ISSUE TITLE
Credetial Guard available for Non Enterprise OS Sku's?

### ISSUE THREAD

**Issue by mario-sit** [MicrosoftDocs/windows-itpro-docs#7900]
[Enter feedback here]
Hi! i just startet the ["HVCI and Windows Defender Credential Guard hardware readiness tool"](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg-readiness-tool) on a Windows 10 **PRO** machine and saw that there is now the OS Sku Pro and Home listed. 
`###########################################################################
OS and Hardware requirements for enabling Device Guard and Credential Guard
 1. OS SKUs: Available only on these OS Skus - Enterprise, Server, Education, Enterprise IoT, **Pro, and Home**
 2. Hardware: Recent hardware that supports virtualization extension with SLAT
To learn more please visit: https://aka.ms/dgwhcr
###########################################################################`
has that changed? ore is it still only avaible on the Enterprise edition. Thanx for the Info!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **v-tea**

**Comment by MaratMussabekov** [comment]
Hello @mario-sit ,
I believe info in [this article](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg-readiness-tool) is incorrect and Credential Guard is not supported in Windows 10 Pro and Home.
Also, it was never announced.
I will create a PR to remove this info from the article

Thank you

**Comment by mario-sit** [comment]
Hi Marat!

I thought the same. Thanks very much.

Regards Mario

**Comment by beerisgood** [comment]
The DG & DC Readiness tool should get updated then too.

Related: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5690

**Comment by HenkPoley** [comment]
`msinfo32` shows Credential Guard under active services for virtualization based security, on my Windows 10 Pro 2004 system.

So it works at least on some 10 Pro editions.

**Comment by HenkPoley** [comment]
The 'DG & DC readiness tool' that beerisgood links to is an ancient version,

**Comment by beerisgood** [comment]
> The 'DG & DC readiness tool' that beerisgood links to is an ancient version. That should have flashing warning lights that it is old.

I know. See my second link
Microsoft need to fix that
