### ISSUE TITLE
Windows Hello for Business forgotten PIN user experience

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#7902]
Hello,

About **Windows Hello for Business forgotten PIN user experience**, video added shows how to setup PIN and not how to reset it when forgotten PIN.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23a14bad-9353-85fa-7f9f-b5db2be529f6
* Version Independent ID: ade91093-e916-281c-5645-00b4c3643d1c
* Content: [Windows Hello for Business Videos - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-videos#windows-hello-for-business-forgotten-pin-user-experience)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-videos.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-videos.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mapalko** [comment]
The linked video is showing the correct experience. If the user forgets their PIN and selects the I forgot my PIN button, we use their password to launch a new session and then guide the user through provisioning a new PIN. Because the user is creating a new PIN the experience is very similar to PIN setup.

**Comment by lightupdifire** [comment]
@mapalko 
Interesting how can you forget your PIN if you never have it... Normally MS articles more precise about article content and its steps, but if you find that all is correct, then never mind.
