### ISSUE TITLE
How to expose Windows 10 settings if explorer.exe is not running

### ISSUE THREAD

**Issue by breakpoint7** [MicrosoftDocs/windows-itpro-docs#7906]
Noticed that several Window Settings options seem to have dependencies on explorer.exe - for instance, Language Preferences won't work unless explorer.exe is running  If a custom shell is used, is there a way to expose settings?  In Windows 7, this was do-able by shelling out to something link intl.cpl and then clicking on Language Preferences.  This doesn't appear to work with Windows 10 unless explorer.exe is running.

**Comment by denisebmsft** [comment]
Hello @breakpoint7 and thanks for the feedback. Can you please tell us to which article(s) your feedback applies? This information will help us route your issue to the correct writer/team. Thanks!

**Comment by breakpoint7** [comment]
https://docs.microsoft.com/en-us/windows/configuration/kiosk-shelllauncher

Context:  Sometimes we might want to use a custom shell to replace explorer.exe but still be able to display configuration settings in Windows.

**Comment by illfated** [comment]
Oh. I see. This page and most of the other pages below https://docs.microsoft.com/en-us/windows/configuration/ are missing their Feedback section, as well as the direct Edit feature, making it a bit more cumbersome to look up the GitHub version of the page:
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/kiosk-shelllauncher.md
- (https://docs.microsoft.com/en-us/windows/configuration/kiosk-shelllauncher)

**Comment by joinimran** [comment]
Hello @breakpoint7 - Thank you for your query. Please note this functionality is not available but you can ask for this by raising your voice using Microsoft User Voice Channel for Windows 10.

Thanks 
Imran.

**Comment by illfated** [comment]
@e0i : Do you have any useful links to the User Voice page for the ticket author in this case?

**Comment by e0i** [comment]
Hello, Feedback can be provided via the following channel,

[Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

Thank you.
