### ISSUE TITLE
Highlight requirement of ADFS

### ISSUE THREAD

**Issue by panthshadowclaw** [MicrosoftDocs/windows-itpro-docs#7911]
Need better highlighting/propagation of ADFS requirement and that third party federation providers are not supported.  
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02eda72c-ccd2-e8d8-4f7e-6edf95b79408
* Version Independent ID: be08aee5-2403-c131-0f39-005e1271d5f1
* Content: [Hybrid Windows Hello for Business Prerequisites - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs#federation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by joinimran** [comment]
Hello @panthshadowclaw - Thank you for your query. We already have a detailed document that can cover all aspects of ADFS implementation. Please see https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/design/ad-fs-requirements

Thanks.
Imran.
