### ISSUE TITLE
Two sets of endpoints

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/windows-itpro-docs#7917]
"Issues related to HTTP/Proxy" and "Device cannot access update files" sections both have different ranges of URLs. Is there some nuance as to which range is required for different purposes?
Having a single clearly marked list of required endpoints is very important for businesses configuring updates. Ideally, this info should be presented in its own high-level doc called "Networking requirements" or something like that, perhaps under the "Plan" section of the ToC. It shouldn't be buried in a troubleshooting doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349d337e-ca0f-a40a-a522-bd1ae71c7d1e
* Version Independent ID: 50f0c3b0-eaad-89c0-eb3c-878e7564d6f6
* Content: [Windows Update troubleshooting - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-troubleshooting#issues-related-to-httpproxy)
* Content Source: [windows/deployment/update/windows-update-troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-troubleshooting.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by joinimran** [comment]
@dcbrown16 - What I am understanding is that you are saying that the information provided in the doc under the heading "Issues related to HTTP/Proxy" and "Device cannot access updated files" should be somewhere on the main page. Can you please refer to where this information should be placed?

**Comment by dcbrown16** [comment]
@joinimran 
The main issue is that the listed URLs are not the same in those two locations. Why are there different lists?

Issues related to HTTP/Proxy
*.download.windowsupdate.com
*.dl.delivery.mp.microsoft.com *.delivery.mp.microsoft.com *.emdl.ws.microsoft.com

Device cannot access update files
http://windowsupdate.microsoft.com
http://*.windowsupdate.microsoft.com
https://*.windowsupdate.microsoft.com
http://*.update.microsoft.com
https://*.update.microsoft.com
http://*.windowsupdate.com
http://download.windowsupdate.com
https://download.microsoft.com
http://*.download.windowsupdate.com
http://wustat.windows.com
http://ntservicepack.microsoft.com
https://*.prod.do.dsp.mp.microsoft.com
http://*.dl.delivery.mp.microsoft.com
https://*.delivery.mp.microsoft.com
https://tsfe.trafficshaping.dsp.mp.microsoft.com

The less important issue is that it would be best if the required connectivity were listed as a prerequisite/setup step.
Perhaps this document or a new doc in that section of the Table of Contents would be appropriate.
https://docs.microsoft.com/en-us/windows/deployment/update/eval-infra-tools

**Comment by jaimeo** [comment]
@arcarley which SME can we work with to get all these endpoint lists correct?

**Comment by jaimeo** [comment]
Update: we have a SME now working on getting us the correct list of endpoints, which we'll update everywhere. The suggestion for a new article is a great one, not least b/c it will give us ONE place to list the endpoints that all other references can link to--that way there is only one location to keep up to date.

**Comment by dcbrown16** [comment]
Great, thanks. I'm in Azure support but this point comes up fairly frequently on advisory cases for us. I'm v-dibr internally if you need my input on anything.

**Comment by joinimran** [comment]
Great start @jaimeo - Looking forward to see this info updated and available.

**Comment by e0i** [comment]
Addressed via https://github.com/MicrosoftDocs/windows-itpro-docs/commit/0f26cd1d82e151cf3d32178ff43837b535bbf219#diff-34338e7fe1eae11badcf34e92d170b80b67ac6caef4c38e4e2a40ab59a859d2d
