### ISSUE TITLE
Delay information incorrect

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/windows-itpro-docs#7921]
This is completely incorrect they should appear within minutes:

"It can take several days for devices to begin reporting to the Microsoft Defender ATP service."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab6dfd3e-71ac-7987-80d7-5bd380bed06a
* Version Independent ID: 9eb3c26b-e61c-2c8b-35a0-415c2a26bfed
* Content: [Review events and errors using Event Viewer - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/event-error-codes)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/event-error-codes.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/event-error-codes.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@SwiftOnSecurity The NOTE with misleading details has been removed form the article thanks to your feedback.
