### ISSUE TITLE
Outdated recommendation

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/windows-itpro-docs#7922]
Although this may have matched Microsoft's customer messaging and culture in 2017, there are no Microsoft professionals I'm aware of who recommend using this. This should only be used on advice of company counsel, it's not Microsoft's role to recommend legal language or warnings. Especially since it breaks 1-step biometric Windows Hello.

Recommend changing wording to describe feature and discourage use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8897b50b-10e9-5d0b-6150-c1834a296a20
* Version Independent ID: bed1c6d9-91c3-02f2-12c9-58229886118a
* Content: [Interactive Logon Message text (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-message-text-for-users-attempting-to-log-on)
* Content Source: [windows/security/threat-protection/security-policy-settings/interactive-logon-message-text-for-users-attempting-to-log-on.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/interactive-logon-message-text-for-users-attempting-to-log-on.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @SwiftOnSecurity - Thank you for your feedback here. Please note that are just examples that Microsoft shared. These are not recommended and you can use based on your company's internal policy.

Thanks.
Imran.
