### ISSUE TITLE
Windows 10 E5 License needed

### ISSUE THREAD

**Issue by denishol** [MicrosoftDocs/windows-itpro-docs#7926]
[Enter feedback here]

The article states:

> Before trying out this feature, make sure you have the following:
> 
> Windows 10 Enterprise E5 license

Is a Windows 10 E5 License really needed? I thought, a Microsoft ATP license + Windows 10 E3 would be sufficient. 
Is a Microsoft 365 E3 + Microsoft 365 E5 Security add on (which includes MDATP) sufficient for the web content filtering?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d1d825-ab12-2f37-b692-5266487ef16f
* Version Independent ID: fef750ac-311b-28b4-1661-16385997815b
* Content: [Web content filtering - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/web-content-filtering)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/web-content-filtering.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/web-content-filtering.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Hi @denishol 

Thank you for your question. I checked with the Marketing team and from what I understand, for Web Content Filtering to work you need to be able to see reports and configure it in Microsoft Defender Security Center. You technically have three options:
1. Have the Windows 10 Enterprise E5 license. 
2. Microsoft 365 E3 + Microsoft 365 E5 Security add on. 
3. Windows 10 E3 + the Microsoft Defender ATP standalone SKU (but this doesn’t make sense as you are better off getting Windows 10 Enterprise E5 license, and the price is no different).

Hope that helps. I'll update the docs to show the second option.
