### ISSUE TITLE
Desktops is not a default controlled folder access location

### ISSUE THREAD

**Issue by shashankg10** [MicrosoftDocs/windows-itpro-docs#7927]
I've tested out just by enabling CFA in audit mode from Intune, not adding any locations, when I test out the CFA using https://demo.wd.microsoft.com/Page/CFA2, the application doesn't report any event ID's 1124 in the event logs.

Where as if I do it for Documents and Pictures folder it does. Correct me if I am wrong. If not, 'd request you to please change the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 054326d9-bae7-e73f-c250-735f3863c32a
* Version Independent ID: f4b3c1fc-695b-2ba5-d5fe-747a9414441c
* Content: [Add additional folders and apps to be protected - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/customize-controlled-folders)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/customize-controlled-folders.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/customize-controlled-folders.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by beerisgood** [comment]
Protected desktop make too much false positives.
That's why they're removed it. It was included before so looks like the docs is outdated

**Comment by RAJU2529** [comment]
@shashankg10 . You can add desktop in controlled folder access

**Comment by shashankg10** [comment]
Yea, manually adding %USERPROFILE%\Desktop it works fine.
