### ISSUE TITLE
Check Microsoft Defender is in Passive Mode

### ISSUE THREAD

**Issue by jenujose** [MicrosoftDocs/windows-itpro-docs#7929]
In the section "Verify that Microsoft Defender Antivirus is in passive mode", I'm not sure if the following commands are correct. 

"Run the Get-MpComputerStatus cmdlet."
"In the list of results, look for AntivirusEnabled: True."

I took a look at a machine that has only Defender installed and another machine that has both Defender and Symantec installed, and in both cases the AntiVirusEnabled:True is the value that I see.

Also, For command prompt command:
"Type sc query windefend, and then press Enter."

We need more guidance as to what to look for after this command has been executed to verify that Defender is in fact running in passive mode. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bae59608-208f-5cec-39a4-95466faa0646
* Version Independent ID: 20c0ab0d-fb2b-3d79-3fcb-d555fc95db14
* Content: [Phase 2 - Set up Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-setup)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-setup.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-setup.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@jenujose thank you so much for this feedback. I will check on this and will post an update here soon. Really appreciate you taking the time to post this great question.

**Comment by denisebmsft** [comment]
@jenujose and @e0i, just a quick note to let you know I have not forgotten about this. We are discussing the content updates internally. I will post another update as soon as I get the article updated.

**Comment by e0i** [comment]
Thank you for the updates, @denisebmsft

**Comment by peteforest** [comment]
Hi!

We added the ForceDefenderPassiveMode registry key (as MS recommends) to our Windows Server 2019 (1809) registry, because of 3rd party AV. 
And the question is the same: How could I check that Windows Defender is in passive mode?
Real-Time protection is **On on the GUI** , and the Get-MPComputerStatus command also gives: **RealTimeProtectionEnabled       : True**

Thank you your answer,
Pete

**Comment by shanibu** [comment]
If you run the Get-MPComputerStatus command, it WILL state if it is in passive mode in the AMRunningMode. If you are running EDR Block mode as well, it will state EDR over passive. 
![image](https://user-images.githubusercontent.com/75799750/101796443-edaecb80-3ad6-11eb-82c3-a160e4e778c3.png)

**Comment by denisebmsft** [comment]
Thank you all for the feedback and for your help! The article has been updated, and here's the procedure to confirm Antivirus is running in passive mode: (1) On a Windows device, open Windows PowerShell as an administrator; (2) Run the Get-MpComputerStatus cmdlet; and (3) In the list of results, look for either AMRunningMode: Passive Mode or AMRunningMode: SxS Passive Mode.
