### ISSUE TITLE
Add Symantec to the exclusion list for Microsoft Defender ATP

### ISSUE THREAD

**Issue by jenujose** [MicrosoftDocs/windows-itpro-docs#7930]
For the section "Add Symantec to the exclusion list for Microsoft Defender ATP", the list of Symantec executables that need to be whitelisted in Defender ATP would be helpful. 

I found these services/processes for Symantec: which would be recommended to whitelist in Defender ATP?

https://knowledge.broadcom.com/external/article/170706/processes-and-services-used-by-endpoint.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bae59608-208f-5cec-39a4-95466faa0646
* Version Independent ID: 20c0ab0d-fb2b-3d79-3fcb-d555fc95db14
* Content: [Phase 2 - Set up Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-setup)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-setup.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-setup.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thank you @jenujose! Appreciate the feedback! I'll dig into this and will post an update here soon.

**Comment by denisebmsft** [comment]
@jenujose thank you again for the excellent suggestion. I added a note to the article and included the link you suggested. The changes should be live later today. I'm going to close this issue for now since I've updated the content, but please let me know if you have any other questions or concerns.
