### ISSUE TITLE
Defender AV Passive Mode

### ISSUE THREAD

**Issue by jenujose** [MicrosoftDocs/windows-itpro-docs#7931]
This section talks about a registry key to allow for Server to go into passive mode. 
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-setup#set-microsoft-defender-antivirus-to-passive-mode-on-windows-server

What's unclear is what OS'es this apply to. Does this apply to Server OS's lower than 2016 where Defender is not an option (e.g 2008 R2, 2012 R2 require SCEP for AV)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bae59608-208f-5cec-39a4-95466faa0646
* Version Independent ID: 20c0ab0d-fb2b-3d79-3fcb-d555fc95db14
* Content: [Phase 2 - Set up Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-setup)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-setup.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-setup.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by MaratMussabekov** [comment]
Hello @jenujose ,
Microsoft Defender Antivirus is available only for Windows Server 2016 and later and for Windows 10. Product, used in Windows Server 2012 R2 and prior was called Windows Defender. 
Thank you

**Comment by e0i** [comment]
Hello @jenujose 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
