### ISSUE TITLE
AppLocker CSP via WMI Bridge Provider

### ISSUE THREAD

**Issue by iamacarpet** [MicrosoftDocs/windows-itpro-docs#7932]
Could we have some docs on how to use the AppLocker CSP via the WMI Bridge Provider please?

I have an example policy (attached), but I can't get the machine to accept it via PowerShell after a lot of trying.

[applocker_internal.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/4962834/applocker_internal.zip)

I tried a few things, then after seeing your [other documentation about submitting XML via Powershell](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/kiosk-mdm-bridge.md), ended up with this:

```powershell
$namespaceName = "root\cimv2\mdm\dmmap"
$className = "MDM_AppLocker_ApplicationLaunchRestrictions01_StoreApps03"
$parentID = "./Vendor/MSFT/AppLocker/ApplicationLaunchRestrictions"

$policyData = Get-Content C:\applocker_internal.xml -Raw

Add-Type -AssemblyName System.Web

$pdata = [System.Web.HttpUtility]::HtmlEncode($policyData);

New-CimInstance -Namespace $namespaceName -ClassName $className -Property @{ParentID=$parentID;InstanceID="StoreApps";EnforcementMode="Enabled";Policy=$pData}
```

I've tried various things from changing the XML formatting and including the XML header, to doing it with and without the HTML encoding suggested in the other guide and seem to cycle between these two errors:

```
New-CimInstance : The requested object could not be found.
At line:1 char:1
+ New-CimInstance -Namespace $namespaceName -ClassName $className -Prop ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MDM_AppLocker_A...icationLaun...):CimInstance) [New-CimInstance], CimException
    + FullyQualifiedErrorId : MI RESULT 6,Microsoft.Management.Infrastructure.CimCmdlets.NewCimInstanceCommand
```

```
New-CimInstance : A general error occurred that is not covered by a more specific error code.
At line:1 char:1
+ New-CimInstance -Namespace $namespaceName -ClassName $className -Prop ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MDM_AppLocker_A...s01_StoreApps03:CimInstance) [New-CimInstance], CimException
    + FullyQualifiedErrorId : MI RESULT 1,Microsoft.Management.Infrastructure.CimCmdlets.NewCimInstanceCommand
```

However, if I omit the policy and enforcement mode, it seems to work, suggesting it is a validation error against those two fields:

```
PS C:\Windows\system32> New-CimInstance -Namespace $namespaceName -ClassName $className -Property @{ParentID=$parentID;InstanceID="Block999"}


EnforcementMode :
InstanceID      : Block999
ParentID        : ./Vendor/MSFT/AppLocker/ApplicationLaunchRestrictions
Policy          :
PSComputerName  :
```

What am I doing wrong?

And/or, how would you achieve something similar in your own example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa7dd86-8bcc-bb92-0a66-86e24701e5a4
* Version Independent ID: 277e194c-0fa3-7da6-1814-f6951e440df6
* Content: [AppLocker CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/applocker-csp)
* Content Source: [windows/client-management/mdm/applocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/applocker-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **dansimp**

**Comment by iamacarpet** [comment]
Found a better example of passing XML in the VPNv2 CSP docs:

https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/vpn-device-tunnel-config#example-windows-powershell-script

Which we can turn into something like this:

```powershell
$ProfileName = "DEMO11045"
$xmlFilePath = "C:\applocker_internal.xml";

$a = Test-Path $xmlFilePath
echo $a

$ProfileXML = Get-Content $xmlFilePath

echo $ProfileXML

$ProfileNameEscaped = $ProfileName -replace ' ', '%20'

$Version = 201606090004

$ProfileXML = $ProfileXML -replace '<', '&lt;'
$ProfileXML = $ProfileXML -replace '>', '&gt;'
$ProfileXML = $ProfileXML -replace '"', '&quot;'

$nodeCSPURI = './Vendor/MSFT/AppLocker/ApplicationLaunchRestrictions/AppLockerA1Comms0'
$namespaceName = "root\cimv2\mdm\dmmap"
$className = "MDM_AppLocker_ApplicationLaunchRestrictions01_StoreApps03"

$session = New-CimSession

try
{
$newInstance = New-Object Microsoft.Management.Infrastructure.CimInstance $className, $namespaceName
$property = [Microsoft.Management.Infrastructure.CimProperty]::Create("ParentID", "$nodeCSPURI", 'String', 'Key')
$newInstance.CimInstanceProperties.Add($property)
$property = [Microsoft.Management.Infrastructure.CimProperty]::Create("InstanceID", "$ProfileNameEscaped", 'String', 'Key')
$newInstance.CimInstanceProperties.Add($property)
$property = [Microsoft.Management.Infrastructure.CimProperty]::Create("EnforcementMode", "Enabled", 'String', 'Property')
$newInstance.CimInstanceProperties.Add($property)
$property = [Microsoft.Management.Infrastructure.CimProperty]::Create("Policy", "$ProfileXML", 'String', 'Property')
$newInstance.CimInstanceProperties.Add($property)

$newInstance

$session.CreateInstance($namespaceName, $newInstance)
$Message = "Created $ProfileName profile."
Write-Host "$Message"
}
catch [Exception]
{
$Message = "Unable to create $ProfileName profile: $_"
Write-Host "$Message"
exit
}
$Message = "Complete."
Write-Host "$Message"
```

It doesn't throw errors anymore, but it creates an empty object that doesn't exist in WMI Explorer

```


ParentID        : ./Vendor/MSFT/AppLocker/ApplicationLaunchRestrictions/AppLockerA1Comms0
InstanceID      : DEMO11045
EnforcementMode : Enabled
Policy          : &lt;RuleCollection Type=&quot;Appx&quot; EnforcementMode=&quot;Enabled&quot;&gt;      &lt;FilePublisherRule Id=&quot;3ebc0e91-5951-4469-bb6d-cf81956c7965&quot;
                  Name=&quot;All signed packaged apps&quot; Description=&quot;Allows members of the Everyone group to run packaged apps that are signed.&quot;
                  UserOrGroupSid=&quot;S-1-1-0&quot; Action=&quot;Allow&quot;&gt;       &lt;Conditions&gt;         &lt;FilePublisherCondition PublisherName=&quot;*&quot;
                  ProductName=&quot;*&quot; BinaryName=&quot;*&quot;&gt;           &lt;BinaryVersionRange LowSection=&quot;*&quot; HighSection=&quot;*&quot; /&gt;
                  &lt;/FilePublisherCondition&gt;       &lt;/Conditions&gt;     &lt;/FilePublisherRule&gt; &lt;/RuleCollection&gt;
PSComputerName  :

EnforcementMode :
InstanceID      : DEMO11045
ParentID        : ./Vendor/MSFT/AppLocker/ApplicationLaunchRestrictions/AppLockerA1Comms0
Policy          :
PSComputerName  :

Created DEMO11045 profile.
```

Looking back at the SyncML examples here:

https://docs.microsoft.com/en-us/windows/client-management/mdm/applocker-csp#recommended-deny-list-for-windows-information-protection

They all have to create the "grouping" node used in the parent, although WMI doesn't look like it provides an interface to do this: if the WMI interface is untested, could this be a bug where it can't create the grouping?

**Comment by joinimran** [comment]
Hello @iamacarpet - Thank you very much for sharing the details. I would suggest you open up a support case with Microsoft to better help you. I don't feel anything that can be modified in the document as of now. If there would be anything that needs a modification in the document or if there will be any bug in WMI, that will be routed properly to the internal team at Microsoft. 

Thanks.

@e0i  FYI&A please.

**Comment by e0i** [comment]
Hello,

Looks like this question can best be answered via relevant [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channels. 

Please consider checking with [Microsoft Community](https://answers.microsoft.com/en-us/windows/forum/windows_10) or [contacting support](https://support.microsoft.com/contactus) for your problem; The issues section of this repository is for content fixes in documentation.

If you feel that the associated article also needs to be updated for any reason feel free to re-open this issue or [contribute with a pull request](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/CONTRIBUTING.md).

Thank you.

**Comment by leo180c** [comment]
> Could we have some docs on how to use the AppLocker CSP via the WMI Bridge Provider please?
> 
> I have an example policy (attached), but I can't get the machine to accept it via PowerShell after a lot of trying.
> 
> [applocker_internal.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/4962834/applocker_internal.zip)
> 
> I tried a few things, then after seeing your [other documentation about submitting XML via Powershell](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/kiosk-mdm-bridge.md), ended up with this:
> 
> ```powershell
> $namespaceName = "root\cimv2\mdm\dmmap"
> $className = "MDM_AppLocker_ApplicationLaunchRestrictions01_StoreApps03"
> $parentID = "./Vendor/MSFT/AppLocker/ApplicationLaunchRestrictions"
> 
> $policyData = Get-Content C:\applocker_internal.xml -Raw
> 
> Add-Type -AssemblyName System.Web
> 
> $pdata = [System.Web.HttpUtility]::HtmlEncode($policyData);
> 
> New-CimInstance -Namespace $namespaceName -ClassName $className -Property @{ParentID=$parentID;InstanceID="StoreApps";EnforcementMode="Enabled";Policy=$pData}
> ```
> 
> I've tried various things from changing the XML formatting and including the XML header, to doing it with and without the HTML encoding suggested in the other guide and seem to cycle between these two errors:
> 
> ```
> New-CimInstance : The requested object could not be found.
> At line:1 char:1
> + New-CimInstance -Namespace $namespaceName -ClassName $className -Prop ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (MDM_AppLocker_A...icationLaun...):CimInstance) [New-CimInstance], CimException
>     + FullyQualifiedErrorId : MI RESULT 6,Microsoft.Management.Infrastructure.CimCmdlets.NewCimInstanceCommand
> ```
> 
> ```
> New-CimInstance : A general error occurred that is not covered by a more specific error code.
> At line:1 char:1
> + New-CimInstance -Namespace $namespaceName -ClassName $className -Prop ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (MDM_AppLocker_A...s01_StoreApps03:CimInstance) [New-CimInstance], CimException
>     + FullyQualifiedErrorId : MI RESULT 1,Microsoft.Management.Infrastructure.CimCmdlets.NewCimInstanceCommand
> ```
> 
> However, if I omit the policy and enforcement mode, it seems to work, suggesting it is a validation error against those two fields:
> 
> ```
> PS C:\Windows\system32> New-CimInstance -Namespace $namespaceName -ClassName $className -Property @{ParentID=$parentID;InstanceID="Block999"}
> 
> 
> EnforcementMode :
> InstanceID      : Block999
> ParentID        : ./Vendor/MSFT/AppLocker/ApplicationLaunchRestrictions
> Policy          :
> PSComputerName  :
> ```
> 
> What am I doing wrong?
> 
> And/or, how would you achieve something similar in your own example?
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 6aa7dd86-8bcc-bb92-0a66-86e24701e5a4
> * Version Independent ID: 277e194c-0fa3-7da6-1814-f6951e440df6
> * Content: [AppLocker CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/applocker-csp)
> * Content Source: [windows/client-management/mdm/applocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/applocker-csp.md)
> * Product: **w10**
> * Technology: **windows**
> * GitHub Login: @lomayor
> * Microsoft Alias: **dansimp**

Hi @iamacarpet,

I have the exact error "The requested object could not be found." when I try to apply the Applocker (StoreApps) via Powershell, do you have any solution of this?

Thanks
Leo
