### ISSUE TITLE
Windows Hello For Business Azure MFA Certificate Trust Deployment Issue

### ISSUE THREAD

**Issue by martikardos** [MicrosoftDocs/windows-itpro-docs#7942]
Hi,

We tried to implement Windows Hello for Business with Azure MFA in a Hybrid Azure AD Joined Certificate Trust Deployment according to the documentation (https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust).
All the prerequisites were fulfilled, but the Windows Hello for Business provisioning didn't start and the PIN couldn't be set until we configured the AD FS Global Authentication Policy - Primary Authentication Methods to use Forms Authentication on the Intranet section as well. (Certificate Authentication, Microsoft Passport Authentication and Windows Authentication were already added to the configuration.)
The error appeared both on AD FS server and W10 client side in the Event Log and the user didn't get the appropriate certificate.
On the client side the dsregcmd /status Ngc Prerequisite Check section showed the following:
AdfsRefreshToken: No
PreReqResult: WillNotProvision

After adding Forms Authentication to the Primary Authentication Methods, the provisioning has started (Azure MFA worked as a second factor for provisioning) and the user certificate has been enrolled automatically.

On the client side the dsregcmd /status Ngc Prerequisite Check section now showed the following:
AdfsRefreshToken: Yes
PreReqResult: WillProvision

Thanks and Regards,
Marta
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b6560ef-2f8c-0c12-6074-8e0d446a1a42
* Version Independent ID: 9e3072f3-d962-92f2-9088-dd5a6a247a50
* Content: [Hybrid Certificate Trust Deployment (Windows Hello for Business) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by joinimran** [comment]
Hello @martikardos - Thank you for sharing your findings. Can you please suggest if there are any changes required in the document. What I have presumed that the document worked as expected and all the instruction are cleared as required. If there is anything that needs to be added in the document, please feel free to let me know. I will be happy to add in the document. 

Thanks. 
Imran.
