### ISSUE TITLE
Good directions however, three points of clarification

### ISSUE THREAD

**Issue by rugbycubsf** [MicrosoftDocs/windows-itpro-docs#7947]
1. It is not clear if we need to create another separate profile alongside the current one or if we should add to existing.
2. Does the current version support these new settings or do we wait for an updated ATP client
3. The Web Filtering config is signed by Jamf but shows unverified (likely due to a mismatch in the corporate name and the cert name).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2354a123-9769-6450-34b6-05e586bbdb4f
* Version Independent ID: d3812533-1ea2-787b-8682-8c143dae9de1
* Content: [New configuration profiles for macOS Catalina and newer versions of macOS - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-sysext-policies)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-sysext-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-sysext-policies.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @rugbycubsf - Thank you for your query. Can you please confirm what macOS you are talking about? For profiles, you can modify the current profiles. I would suggest creating a new profile and confirm that it is working fine. All of the settings are supported by the current version. Please see jamf documentation at https://www.jamf.com/jamf-nation/articles/649/creating-a-signing-certificate-using-jamf-pro-s-built-in-certificate-authority for signing the certificate. If there is still an issue, please feel free to contact Microsoft support.

Thanks
Imran.
