### ISSUE TITLE
issue: Windows Setup InstallFrom

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/windows-itpro-docs#7951]
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-command-line-options#installfrom

/InstallFrom Specifies a different Install.wim file to use during Windows Setup. But it's more time it's not available, so what exactly are its usage restrictions?

**Comment by joinimran** [comment]
Hello @goxia - Thank you for posting your query regarding /InstallFrom.

Please note that this option helps to use a different .wim file during the installation. As mentioned in the document if you have a 32-bit version of setup and wanted to install a 64-bit version of Windows, you can use the 64-bit version of the .wim file. This option can also be used when you have a custom-created .wim file for Windows installations. 

When you are installing it normally, you don't need to use this option. But when you have created a custom .wim file or want to use any other .wim file, place it in any directory and then specify the path for that directory by using this option. This way it can work as expected.

@e0i - FYI&A Please.

Thanks
Imran.

**Comment by goxia** [comment]
> Hello @goxia - Thank you for posting your query regarding /InstallFrom.
> 
> Please note that this option helps to use a different .wim file during the installation. As mentioned in the document if you have a 32-bit version of setup and wanted to install a 64-bit version of Windows, you can use the 64-bit version of the .wim file. This option can also be used when you have a custom-created .wim file for Windows installations.
> 
> When you are installing it normally, you don't need to use this option. But when you have created a custom .wim file or want to use any other .wim file, place it in any directory and then specify the path for that directory by using this option. This way it can work as expected.
> 
> @e0i - FYI&A Please.
> 
> Thanks
> Imran.

Thank you @joinimran , I have noticed the syntax requirements for this parameter and have been able to use it correctly.
