### ISSUE TITLE
Automatically enter Computer Named based on SQL lookup

### ISSUE THREAD

**Issue by davida1992** [MicrosoftDocs/windows-itpro-docs#7952]
We have been using WDS with MDT with some time and it works well for the most part, robust and has rarely given us issues or problems. 

All of our machines are named in the following format: ROOM-PC-NUMBER (For example R004-PC-203)

All of our PC details are stored in our CMDB, which includes the computer serial number and computer name. 

Ideally, what I would like to happen to save time, would be for MDT to launch, and in the computer name, instead of it being a random name, it should query our SQL database running behind our CMDB. It should find the serial number in the database that matches the PC serial number, and it should name it the same name as in the CMDB.

Is there a way of doing this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02d07ede-1437-53e7-8ea5-3ee441cda67d
* Version Independent ID: 8b657df5-9053-7611-9132-f9113d439a7c
* Content: [Get started with the Microsoft Deployment Toolkit (MDT) (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/get-started-with-the-microsoft-deployment-toolkit)
* Content Source: [windows/deployment/deploy-windows-mdt/get-started-with-the-microsoft-deployment-toolkit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/get-started-with-the-microsoft-deployment-toolkit.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
Hello, @davida1992  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
