### ISSUE TITLE
Automated investigations statistics - 7 days not 30

### ISSUE THREAD

**Issue by s207307** [MicrosoftDocs/windows-itpro-docs#7954]
The "Automated investigations statistics" section should read "7 days" vice "30 days".
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/security-operations-dashboard?source=docs#automated-investigations-statistics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dec0f3e-e970-48ed-68d5-56200c566ac7
* Version Independent ID: 89757f65-c389-c826-347a-c0a9839b3042
* Content: [Microsoft Defender Security Center Security operations dashboard - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/security-operations-dashboard)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/security-operations-dashboard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/security-operations-dashboard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by denisebmsft** [comment]
Thank you for the feedback, @s207307. We've made the fix, and the change will render live later today.
