### ISSUE TITLE
Add -ValidateMapsConnection

### ISSUE THREAD

**Issue by nathanmcnulty** [MicrosoftDocs/windows-itpro-docs#7961]
Incomplete documentation of command line arguments

Add -ValidateMapsConnection

Reference:
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-network-connections-microsoft-defender-antivirus#validate-connections-between-your-network-and-the-cloud

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f25443de-57f4-c8f2-fecb-f58714467894
* Version Independent ID: 1d783d00-ae0d-3eea-9a32-b42dd32e73c2
* Content: [Use the command line to manage Microsoft Defender Antivirus - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/command-line-arguments-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/command-line-arguments-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/command-line-arguments-microsoft-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by e0i** [comment]
@nathanmcnulty 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published via PR #8072. Thanks for your feedback.
