### ISSUE TITLE
Linux support information is not up-to-date on the "Minimum requirements for Microsoft Defender ATP" page

### ISSUE THREAD

**Issue by zsmuller** [MicrosoftDocs/windows-itpro-docs#7963]
The page says:
> Linux (currently, Microsoft Defender ATP is only available in the Public Preview Edition for Linux)

And below that in a note:
>Also note that Microsoft Defender ATP is currently only available in the Public Preview Edition for Linux.

However since 23rd June MDATP for Linux is generally available.
See: https://techcommunity.microsoft.com/t5/microsoft-defender-atp/microsoft-defender-atp-for-linux-is-now-generally-available/ba-p/1482344

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by joinimran** [comment]
Hello @zsmuller - Thank you for your feedback. I have reviewed the provided information and found that this note/information is no more available in the doc.

If there is anything else I can help you with. Please do let me know.

Thanks.
Imran.

**Comment by illfated** [comment]
(ref. #8248 )

**Comment by illfated** [comment]
(also ref. #8050 )
