### ISSUE TITLE
Wrong link on the "Submit and view feedback for this product" button

### ISSUE THREAD

**Issue by zsmuller** [MicrosoftDocs/windows-itpro-docs#7964]
At the botton of the page there're two buttons.
Above the buttons is the following text: "Submit and view feedback for"
And the first button says: "This product"

Clicking it takes us to here:
https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app

Below the title it says: "Applies to Windows 10"

The first paragraph of this page says:
> The Feedback Hub app lets you tell Microsoft about any problems you run into while using Windows 10. You can also send suggestions to help us improve your Windows experience.

It seems that the product feedback button of MDATP for Linux takes the user to the "Feedback Hub app" that is built into Windows 10 and is meant to collect user feedback on using Windows 10.
Btw. the same button+link combo is on all the pages of the MDATP for Linux documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef3b1143-53ee-892c-59c8-5cfa12e017c2
* Version Independent ID: 29f6c231-15bd-296b-cca9-7ef6ba8192df
* Content: [Microsoft Defender ATP for Linux - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-linux)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-linux.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-linux.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Fair point. there should be some form of distinction in place to use other links when the page is not directly related to Windows 10 or Windows Server per se.

I believe those buttons are used carte blanche for all Feedback sections for the MS Docs pages, maybe as part of the overall docs.microsoft.com site. Some of the page sections are omitted from having Feedback, but otherwise most of them use the exact same form or CSS (I don't know exactly what is used to handle the pages site-wide, I am not that deep into HTML or web site development.)

**Comment by joinimran** [comment]
Hello @zsmuller - Thank you for your feedback. The point you have raised makes sense but this is the same layout applied to all Microsoft products. 
I would suggest you to use a user-voice channel to request for this. If there is anything else related to this document that needs correction, please do let me know. 

@e0i - Please guide @zsmuller how to open a request on the user-voice channel. 

Thanks.
Imran.
