### ISSUE TITLE
RDP for Azure AD Joined machines - Unclear assertions, or general errors

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/windows-itpro-docs#7965]
There are a few problems with this page, that need clarifying to make it useful:

- Adding Authenticated Users to Remote Desktop Users is pretty broad; this probably shouldn't be recommended generally
- The 'note' box under step 3 communicates many ideas; and these probably shouldn't be floating amongst the steps like this. Consider explaining some of the reasoning a bit stronger, or at least splitting each different note into its own note box.
- The green 'tip' box after step 4 says `enter your account name in this format: ``AzureAD UPN`` `. This seems particularly nonsensical and doesn't appear to work. This should also probably be made into its own section: 'Connect to a remote machine'
- The note after the tip after step 4 is also fairly random here; what is Remote Desktop Connection 6.0? Why wouldn't you be able to connect using it? How is this involved in Azure AD sign-on?

I suspect the whole page really needs to be readjusted after several different authors have added information to it.

It also doesn't really provide a top-to-bottom guide on how to setup and use Remote Desktop Connection between Azure AD machines; even after following this guide I am still inexplicably getting an unknown username and password error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10) - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by Karr** [comment]
All good points that need to be addressed sooner than later.  I am surprised this even passed quality inspection.  Can we say this entire page = "Soup Sandwich".  Completely worthless in so many ways and the only way people find a way to connect is with some butchery of the RDP connection file and lowering security.  Format to login was AzureAD\UPN btw.  Unreal... Microscrap should be ashamed of what it does at times.

**Comment by e0i** [comment]
With the help of your feedback, the issue has been reviewed and an update to the documentation has been published via PR #8314. Thanks for your feedback.
