### ISSUE TITLE
Incorrect informaton and copy-paste from a server article

### ISSUE THREAD

**Issue by PM735** [MicrosoftDocs/windows-itpro-docs#7969]
The text in bold below is not correct and confirmed by testing. The builtin account does not allow any logon in Safe Mode on domain-joined computers. A similar issue has been discussed here and closed without any correction or definitive response from Microsoft.

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4214

Quote 1:
=========
Safe mode considerations
When you start a device in safe mode, the disabled administrator account is enabled only if the computer is non-domain joined and there are no other active local administrator accounts. If the computer is joined to a domain, the disabled administrator account is not enabled. **If the administrator account is disabled, you can still access the computer by using safe mode with the current administrative credentials. For example, if a failure occurs using a secure channel with a domain-joined computer, and there is no other local administrator account, you must restart the device in safe mode to fix the failure.**

How to access a disabled Administrator account
You can use the following methods to access a disabled Administrator account:

**When there is only one local administrator account that is disabled, start the device in safe mode (locally or over a network), and sign in by using the credentials for the administrator account on that computer.
When there are local administrator accounts in addition to the built-in account, start the computer in safe mode (locally or over a network), and sign in by using the credentials for the administrator account on that device.** An alternate method is to sign in to Windows by using another local Administrator account that was created.

=========

The text in italic looks like a copy-paste from a similar server article.
This article is dedicated to WIndows 10, so it is not clear what servers the text is talking about.

Quote 2:
=========

_When multiple domain-joined servers have a disabled local Administrator_ account that can be accessed in safe mode, you can remotely run psexec by using the following command: net user administrator /active: no.

=========

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de5d73e7-c632-1202-fe3c-ec79db06f10c
* Version Independent ID: 4554a4b1-5d77-e7a2-6dde-6bd3a47850cf
* Content: [Accounts Administrator account status (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/accounts-administrator-account-status)
* Content Source: [windows/security/threat-protection/security-policy-settings/accounts-administrator-account-status.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/accounts-administrator-account-status.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello, also, it is not clear why it is "net user administrator /active: no", when we need to enable the account? It should be "net user administrator /active: yes"
Thank you

**Comment by e0i** [comment]
@-

With the help of your feedback, the content has been updated with relevant changes accordingly via PR #8105
