### ISSUE TITLE
Correction - Configure the offline media

### ISSUE THREAD

**Issue by WLK33R** [MicrosoftDocs/windows-itpro-docs#797]
The documentation reads  "On MDT01, using File Explorer, copy the CustomSettings.ini file from the E:\MDTBuildLab\Control folder to E:\MDTOfflineMedia\Content\Deploy\Control. Overwrite the existing files."
I believe the customsettings.ini should be copied from E:\MDTProduction\Control

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Service: **unspecified**
* GitHub Login: @mtniehaus
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by nenonix** [comment]
@WLK33R Thank you, I need to confirm this and then will proceed. Any information you can add to help me confirm the change would be greatly appreciated.
