### ISSUE TITLE
Deployment script also need psexec

### ISSUE THREAD

**Issue by WolfgangSauer** [MicrosoftDocs/windows-itpro-docs#7971]
The pilot script is using psexec. This seems also be a requirement for the deployment script since psexec is called in the runconfig.bat script. But psexec.exe is not available in the deployment directory. How is the planned process for broad deployment?

Thanks
Wolfgang

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 203edb5f-4274-eafb-323b-01fd55192c85
* Version Independent ID: 7a4beba8-b79b-92c3-59b9-b73c92947083
* Content: [Get started with Update Compliance - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-get-started)
* Content Source: [windows/deployment/update/update-compliance-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-get-started.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@cinglis-msft can you address this?

**Comment by cinglis-msft** [comment]
This is being worked on.

**Comment by RAJU2529** [comment]
@WolfgangSauer . You can download **psexec** from below link
**https://docs.microsoft.com/en-us/sysinternals/downloads/psexec**

**Comment by WolfgangSauer** [comment]
Thanks for the hint, but thats obvious :-) My expectation with the deployment script is that it will NOT use psexec because it will be deployed by Intune/CM/other tool. And therefore it is running already with LocalSystem permissions. Psexec may be used for test purposes in the pilot script.

**Comment by jaimeo** [comment]
@cinglis-msft , can you address this?
