### ISSUE TITLE
URL does not work

### ISSUE THREAD

**Issue by thutrang162** [MicrosoftDocs/windows-itpro-docs#7972]
the link "Create and deploy Windows Information Protection (WIP) app protection policy with Intune and MAM" at the bottom of the page is not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ad3f92-24de-5eb5-8454-c72d85737183
* Version Independent ID: 900125eb-31ea-faf3-ac30-7c3d7b30f611
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@denisebmsft . I think below links are suitable 
**https://docs.microsoft.com/mem/intune/apps/app-protection-policies**
**https://docs.microsoft.com/windows/security/information-protection/windows-information-protection/create-wip-policy-using-configmgr**

**Comment by illfated** [comment]
404 link URL:
- https://docs.microsoft.com/intune/deploy-use/create-windows-information-protection-policy-with-intune

I could be mistaken, but I wonder if the following URL is closer to the original target:
- https://docs.microsoft.com/mem/intune/apps/windows-information-protection-policy-create

Also, seeing how prevalent the use of **Microsoft Azure** is becoming these days, I wonder if the link to the Azure version also should be included in the link list.

- https://docs.microsoft.com/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure

**Comment by e0i** [comment]
Closing via merged PR #8386
