### ISSUE TITLE
This doc is out dated

### ISSUE THREAD

**Issue by sandytsang** [MicrosoftDocs/windows-itpro-docs#7974]
Hello, this doc has not been updated over a year, base on our test with IoT Enterprise 2004, there are lots of Policy CSP are missing from the documentation. Maybe policy CSP that works aren't listed here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91e04c6-f8ea-a661-1ab6-4239c5362cf3
* Version Independent ID: faace880-a3cf-1bd1-aed8-3098ea442eb3
* Content: [Policy CSPs supported by Windows 10 IoT Enterprise - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csps-supported-by-iot-enterprise#feedback)
* Content Source: [windows/client-management/mdm/policy-csps-supported-by-iot-enterprise.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csps-supported-by-iot-enterprise.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@sandytsang .If possible ,list all the working CSP policies those are not updated here

**Comment by illfated** [comment]
Are the new Policy CSPs available somewhere else, like in the OS files or external downloads?

**Comment by sandytsang** [comment]
@RAJU2529  There are 1155 Policy CSP in total, I didn't test all of them. :) Tested ./Vendor/MSFT/Policy/Config/Update/AllowAutoWindowsUpdateDownloadOverMeteredNetwork in Iot Enterprise LTSC 2019 and Iot Enterprise, version 2004, and it works. So at least this one is missing from the list. 

This list mentioned Update/ConfigureDeadlineForFeatureUpdates is supported, but I tested in Iot Enterprise LTSC 2019, it doesn't  work. Event log said "system cannot find the file specified". The same setting works in Iot Enterprise, version 2004

This document has not mention if it is for LTSC or SAC, since IoT enterprise has two update channel, it should be mentioned.

**Comment by RAJU2529** [comment]
@sandytsang . Author wil update after testing those policies

**Comment by e0i** [comment]
There have been recent updates to the Policy CSP documentation that includes the mentioned policies. See link: 

https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update#update-allowautowindowsupdatedownloadovermeterednetwork

Thank you.
