### ISSUE TITLE
Mac OS Risk Score

### ISSUE THREAD

**Issue by shashankg10** [MicrosoftDocs/windows-itpro-docs#7980]
I have on-boarded Mac OS, machines its been more than a week, the device risk score is none and the exposure score is also none. Is this okay ? I belive it should report the risk level on the machine atleast.
![image](https://user-images.githubusercontent.com/66464126/88784046-27370800-d1c2-11ea-85a8-955692c2fd2f.png)

**Comment by denisebmsft** [comment]
Hello @shashankg10. Can you please tell us to which article(s) your feedback applies? This information will help us route the issue to the correct writer/team.

**Comment by shashankg10** [comment]
Hi,

This is the link I am referring to, which talks about Risk level: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/machines-view-overview

In my dashboard I only see the risk score for Windows Machine, but for Mac Os the risk level in None.

**Comment by aczechowski** [comment]
Doing repo cleanup, I'm closing this issue as the article was moved to a new repo, you can find the current article at 
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machines-view-overview?view=o365-worldwide
I'm sending this issue (and others for this area) to the current authors for their review. If there's still an update needed, please file new feedback on the current article in the other repo.
