### ISSUE TITLE
Schema Changes

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#7981]
[Enter feedback here]
Please add a link to this article about schema changes, https://techcommunity.microsoft.com/t5/microsoft-defender-atp/advanced-hunting-data-schema-changes/ba-p/1043914. I just spend a long time troubleshooting some old examples. It would have been helpful if the official docs site included some information about those changes 6 months ago.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 465c3bf3-a207-3113-1052-f237a224ebfb
* Version Independent ID: 733dac2c-2e47-8c0e-a0c1-fd925c3184ea
* Content: [Advanced hunting schema reference - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-schema-reference)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-schema-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-schema-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by e0i** [comment]
Closing via merged PR #7997 that addresses this issue. Thank you.
