### ISSUE TITLE
What permissions are needed when accessing with Service Principal

### ISSUE THREAD

**Issue by RafCox** [MicrosoftDocs/windows-itpro-docs#799]
I try to retrieve alerts through the Graph API using a registered Application (service principal), but this always results in a permission denied; what Application Permissions are needed to access the WD ATP api's? Can you provide an example?
tx
Raf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8d6a80c-c8ce-9d2c-1958-2322ee8e90e0
* Version Independent ID: 2c51d73c-6f49-7163-f8ec-934b92484f14
* Content: [Use the Windows Defender Advanced Threat Protection exposed APIs](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/exposed-apis-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/exposed-apis-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/exposed-apis-windows-defender-advanced-threat-protection.md)
* Service: **unspecified**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by 0xmilkmix** [comment]
any update? also getting 'Authorization has been denied for this request' when using a key generated from Azure AD following this method.

It however works using client secret from SIEM connector pane in SecurityCenter. This method is however less convenient if you want to delegate multiple accesses or be able to easily revoke them.

**Comment by mjcaparas** [comment]
Hi 0xmilkmix,

Thanks for reaching out! I'm getting touch with our engineers. 

I'll get back to you :)

**Comment by mjcaparas** [comment]
We've recently updated our API docs, please see if the updates address your issue:https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/use-apis
