### ISSUE TITLE
Can not delete a device tag

### ISSUE THREAD

**Issue by PawanGupta01** [MicrosoftDocs/windows-itpro-docs#7991]
No option to delete a device tag as shown in below link- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/machine-tags

See below image- 
![image](https://user-images.githubusercontent.com/69029264/89004556-100e2c80-d320-11ea-8a57-8b87b809c8ac.png)

**Comment by RAJU2529** [comment]
@PawanGupta01 .  see below 
If you need to remove a tag that was added using the above Registry key, clear the contents of the Registry key data instead of removing the 'Group' key.

**Comment by PawanGupta01** [comment]
Thanks Raju. I was trying different methods randomly and got rid of this tag by manually removing the device tag from all the devices (I was lucky there were only 2 devices). I will keep this method next time handy
