### ISSUE TITLE
What if the detection doesn't work?

### ISSUE THREAD

**Issue by pctsltd** [MicrosoftDocs/windows-itpro-docs#7992]
I think you should provide a link to what to do or how to troubleshoot if the detection doesn't work. I just setup ATP and the detection hasn't worked on two different machines. The detection command in the onboarding when run in powershell (disappears as it should) but nothing gets reported to the portal. 

Please provide some links or documentation to troubleshooting these kinds of issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1a58ecc-aa01-3b7a-c1f7-a039063c7c38
* Version Independent ID: b1b9a0ef-fd7e-96e2-730d-01158fb93eee
* Content: [Run a detection test on a newly onboarded Microsoft Defender ATP device - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/run-detection-test)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/run-detection-test.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/run-detection-test.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by MaratMussabekov** [comment]
Hello @pctsltd ,
there is no article in Microsoft docs that helps to troubleshoot the described issue.
I would recommend to create a topic in [Microsoft Support](https://support.microsoft.com/en-us) portal.
Thank you

**Comment by e0i** [comment]
Closing via #8078
