### ISSUE TITLE
Isolation feature to allow RMM

### ISSUE THREAD

**Issue by pctsltd** [MicrosoftDocs/windows-itpro-docs#7993]
I don't see any documentation here that outlines how you remotely work on a device that is isolated? Could the documentation be updated to describe how one would do this? Most of the time especially when working from home its not possible to visit a device onsite. 

Is it possible to set an exclusion to allow a RMM tool to connect to an isolated PC? This would be very useful when a PC is isolated so we can run remote cleanup.

Or can we use "Live Response" when the PC is in isolate mode?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e7dfb91-0447-9a84-bca7-a4e139330935
* Version Independent ID: 2b5864c3-bcdc-4202-0b4c-758020565652
* Content: [Take response actions on a device in Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/respond-machine-alerts)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/respond-machine-alerts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/respond-machine-alerts.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by joinimran** [comment]
Hello @pctsltd - Thank you for your query. Please note that you can use Live Response regardless of location using a remote shell. Visit https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/live-response for more details on how you can get a benefit of using Live Response.

Thanks.
Imran.

**Comment by e0i** [comment]
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
