### ISSUE TITLE
linux is now supported

### ISSUE THREAD

**Issue by mikefrankland** [MicrosoftDocs/windows-itpro-docs#8000]
[Enter feedback here]

Defender now supports linux right?
![image](https://user-images.githubusercontent.com/46350042/89176982-27336100-d550-11ea-82cc-fc1509f75573.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 034ffda3-6ef7-13f4-6341-82ac3c11f455
* Version Independent ID: 5527ef3f-6361-b037-d9c3-3d520cf2ef2c
* Content: [Supported operating systems and platforms for threat and vulnerability management - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/tvm-supported-os)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/tvm-supported-os.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/tvm-supported-os.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Hi @mikefrankland yes that is true, but linux and mac are not currently supported by threat and vulnerability management. I'll add a note so it's clearer.
