### ISSUE TITLE
Applies to in document may create confusion

### ISSUE THREAD

**Issue by vanessabruwer** [MicrosoftDocs/windows-itpro-docs#8006]
The document is about Defender Antivirus, but the applies to indicates that this is about Defender ATP - this creates confusion. Could this be made clearer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d1dee2b-d86a-0019-f689-81483fab31f5
* Version Independent ID: 02722ca2-1dde-aafb-22e3-67259c4ece37
* Content: [Microsoft Defender Antivirus on Windows Server 2016 and 2019 - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-on-windows-server-2016)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-on-windows-server-2016.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-on-windows-server-2016.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
This looks similar to the issue ticket #7106 and its solution in PR #8005 , so the same approach is likely useful here.

**Comment by RAJU2529** [comment]
@e0i . Assign pr #8053, to review it.

**Comment by illfated** [comment]
Looks resolved now, so this ticket should be ready for closing.
