### ISSUE TITLE
Update this page to show apps included in Windows 10 2004

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/windows-itpro-docs#8017]
This page doesn't have current info related to Windows 10 2004.
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/application-management/apps-in-windows-10.md

I updated app names in #8016 but didn't add the 2004 app list.

**Comment by AdamGrossTX** [comment]
One additional request on this - if there is a difference between SKUs (Home, Pro, Ent, Edu) can you indicate that as well?

**Comment by e0i** [comment]
Obtained a list of apps included in version 2004 and an independent contributor is going to follow-up with necessary changes. Thank you for feedback.

**Comment by e0i** [comment]
Closing via #8352
