### ISSUE TITLE
MDM policies transposed for new policies in the change to diagnostic data collection docs

### ISSUE THREAD

**Issue by jasonrpeterson** [MicrosoftDocs/windows-itpro-docs#8019]
The MDM policy names appear to be swapped for the Limit dump and diagnostic log collection policies.  

A final set of changes includes two new policies that can help you fine-tune diagnostic data collection within your organization. These policies let you limit the amount of optional diagnostic data that’s sent back to Microsoft.

The **Limit dump collection** policy is a new policy that can be used to limit the types of crash dumps that can be sent back to Microsoft. If this policy is enabled, Windows Error Reporting will send only kernel mini dumps and user mode triage dumps.
Group Policy: Computer Configuration > Administrative Templates > Windows Components > Data Collection and Preview Builds > Limit Dump Collection
MDM policy: System/ **LimitDiagnosticLogCollection**

The **Limit diagnostic log** collection policy is another new policy that limits the number of diagnostic logs that are sent back to Microsoft. If this policy is enabled, diagnostic logs are not sent back to Microsoft.
Group Policy: Computer Configuration > Administrative Templates > Windows Components > Data Collection and Preview Builds > Limit Diagnostic Log Collection
MDM policy: System/**LimitDumpCollection**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 345f01ee-e894-106b-d405-f05c41b69940
* Version Independent ID: a324f689-3229-9ccd-a844-6064820601d8
* Content: [Changes to Windows diagnostic data collection - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/changes-to-windows-diagnostic-data-collection)
* Content Source: [windows/privacy/changes-to-windows-diagnostic-data-collection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/changes-to-windows-diagnostic-data-collection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by e0i** [comment]
Closing via #8136
