### ISSUE TITLE
Broken link for "See Email scanning limitations"

### ISSUE THREAD

**Issue by Yupiter2005** [MicrosoftDocs/windows-itpro-docs#8020]
The bookmark link is broken in

Email scanning **See Email scanning limitations**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ede71cb-45c3-0fb4-31e7-3538a0eaffb5
* Version Independent ID: 7c295a83-b94a-76ec-4e42-4388c4358170
* Content: [Configure scanning options for Microsoft Defender AV - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-advanced-scan-types-microsoft-defender-antivirus#email-scanning-limitations)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/configure-advanced-scan-types-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/configure-advanced-scan-types-microsoft-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by e0i** [comment]
Fixed via community-contributed PR, #8031. Thanks.
