### ISSUE TITLE
Add "Gateway" to links

### ISSUE THREAD

**Issue by Oppedijk** [MicrosoftDocs/windows-itpro-docs#8023]
Please change the references in the text, add "Gateway" (added in bold)

Setup Azure Log Analytics **Gateway**(formerly known as OMS Gateway) to act as proxy or hub:
Azure Log Analytics Agent **Gateway**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f520ab6-2fc9-4978-553c-6beff2ec3d9c
* Version Independent ID: 840eb4e6-2871-6812-a64c-8e0b8d6c772a
* Content: [Onboard devices without Internet access to Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/onboard-offline-machines)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/onboard-offline-machines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/onboard-offline-machines.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
Closing via #8157
