### ISSUE TITLE
Unclear which scripts need to be copied to the start folder.

### ISSUE THREAD

**Issue by RowdyChildren** [MicrosoftDocs/windows-itpro-docs#8025]
Which files need to be copied for non-persistent VDI isn't clear. If you are onboarding a device and you want single entries you still need the .cmd in the startup folder but you are only executing the PowerShell. The article reads like you only need to copy the PowerShell script to the startup folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804f2883-5de4-9d54-d0b4-e64b04984aa8
* Version Independent ID: 0ab9ee92-c5e1-0455-92ba-ed07ed7bd140
* Content: [Onboard non-persistent virtual desktop infrastructure (VDI) devices - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by MaratMussabekov** [comment]
Hello @RowdyChildren , as I can see, the proposed change was already commited by https://github.com/MicrosoftDocs/windows-itpro-docs/commit/26faf9fc3481324e811b9ddaf276af063e1cbb89.

But isn't it confusing now? for example, I am going to implement a single entry, and it reads like I need to copy CMD file two times - in step 2 and in step 3. What do you think?

Can't we, do it following way:
2. Copy the extracted files from the .zip into golden/master image under the path C:\WINDOWS\System32\GroupPolicy\Machine\Scripts\Startup.
a. if you are not implementing a single entry for each device: copy WindowsDefenderATPOnboardingScript.cmd
b. if you are implementing a single entry for each device: copy both Onboard-NonPersistentMachine.ps1 and WindowsDefenderATPOnboardingScript.cmd

Thank you

**Comment by RowdyChildren** [comment]
The wording makes a lot more sense! I did the original PR while in the
field based on customer feedback.

**Comment by e0i** [comment]
@RowdyChildren 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published via PR #8203. Thanks for your feedback.
