### ISSUE TITLE
KDC_ERR_KEY_EXPIRED

### ISSUE THREAD

**Issue by cscherb** [MicrosoftDocs/windows-itpro-docs#8027]
This page says KDC_ERR_KEY_EXPIRED cannot occur in event 4768 - this is wrong. If you logon to a terminal server, diconnect you session and change you password you will find Events with Event-ID 4768 and Result Code 0x17 after a while in security eventlog.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94cebf1d-b16d-4ddc-b532-be829b858938
* Version Independent ID: 3707f457-98d5-e5b3-c749-99afe0d6d495
* Content: [4768(S, F) A Kerberos authentication ticket (TGT) was requested. (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4768#feedback)
* Content Source: [windows/security/threat-protection/auditing/event-4768.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4768.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@cscherb Could you share such an event? It's strange that looking at the [article about event 4768](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4768) it's clearly stated that

`This event doesn't generate for Result Codes: 0x10, 0x17 and 0x18. Event “4771: Kerberos pre-authentication failed.” generates instead.`
