### ISSUE TITLE
Registry Key Question

### ISSUE THREAD

**Issue by beefy80** [MicrosoftDocs/windows-itpro-docs#8028]
Can you confirm what you mean about this bit: To opt out, set the registry key HKLM\Software\Microsoft\Windows NT\CurrentVersion\502505fe-762c-4e80-911e-0c3fa4c63fb0 to a name of DataRequireGatedScanForFeatureUpdates and a value of 0.  Is this a string value, Dword??? Trying to understand how this is implemented as I have been testing this on a device that is on a "Safeguard Hold" but cannot get this working.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eec6796-90d0-4909-c837-2c7f848aacb7
* Version Independent ID: afd14c22-5dd2-1153-bdfe-d53bae985061
* Content: [Update Compliance - Feature Update Status report - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-feature-update-status)
* Content Source: [windows/deployment/update/update-compliance-feature-update-status.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-feature-update-status.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@cinglis-msft

**Comment by RAJU2529** [comment]
@jaimeo ,  setting REG_DWORD  to 0,  will stop installing feature updates

**Comment by cinglis-msft** [comment]
@RAJU2529 is correct, exact directions:


1.	Right click on the “Current version” and create a new key with the name “502505fe-762c-4e80-911e-0c3fa4c63fb0”.
2.	To opt-out, set the type as “REG_DWORD” and data as “0”.

**Comment by jaimeo** [comment]
@cinglis-msft will you be making the edit to the article?

**Comment by RAJU2529** [comment]
I think, i can create PR after getting permission from article author

**Comment by jaimeo** [comment]
@RAJU2529 good deal; go ahead and propose the edit in a PR and we'll process it. Thanks!

**Comment by RAJU2529** [comment]
@jaimeo , Check nd verify PR

**Comment by jaimeo** [comment]
@RAJU2529 which PR? Actually, just tag cinglis-msft in your PR as he should review it.

**Comment by e0i** [comment]
Changes have been merged via #8048. Thank you for discussion.
