### ISSUE TITLE
Potential Need for an Update?

### ISSUE THREAD

**Issue by jcoffi** [MicrosoftDocs/windows-itpro-docs#8030]
It looks like 

```
VPNv2/ProfileName/NativeProfile/Authentication/Certificate
Reserved for future use.

VPNv2/ProfileName/NativeProfile/Authentication/Certificate/Issuer
Reserved for future use.

VPNv2/ProfileName/NativeProfile/Authentication/Certificate/Eku
Reserved for future use
```
might not be accurate anymore. I was able to use these parameters without an error in Intune to setup a device based Always-On VPN.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8b1b81d-3c35-0315-d149-f10af3a409b2
* Version Independent ID: c34e7acb-ece7-d76f-fb41-470e19119ee0
* Content: [VPNv2 CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp?redirectedfrom=MSDN)
* Content Source: [windows/client-management/mdm/vpnv2-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/vpnv2-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@ManikaDhiman Can we confirm whether the above configuration paths are no longer reserved for future use? We’d like to revise the article accordingly. Thank you.

**Comment by ManikaDhiman** [comment]
Hi @e0i The product team confirmed that those fields are nonfunctional and “reserved for future use" as correctly mentioned in the doc. Hence, closing this issue as no doc update is needed. Thanks!
