### ISSUE TITLE
Missing "Moderate blocking level"

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/windows-itpro-docs#8033]
There is now a "Moderate blocking level."

Please document what this means and how it is different than "Default Microsoft Defender blocking level"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f0f5a3-f095-3fa4-90dd-7dee8ccb49ad
* Version Independent ID: 1bec5d66-a92a-4b0d-b9d8-f43c9eab4a50
* Content: [Specify cloud-delivered protection level in Microsoft Defender Antivirus - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/specify-cloud-protection-level-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/specify-cloud-protection-level-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/specify-cloud-protection-level-microsoft-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@SwiftOnSecurity , yes i conformed

**Comment by e0i** [comment]
@SwiftOnSecurity Please confirm whether the PR #8040 provided by a community contributor addresses your concern. Thank you.
