### ISSUE TITLE
Incorrect implication this is an ATP feature

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/windows-itpro-docs#8035]
We asked our partner businesses to turn these security features on, and they came back and told us they didn't because the documentation says the features only apply to ATP. Please clarify this applies to all Defender users.

- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-cloud-block-timeout-period-microsoft-defender-antivirus
- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-block-at-first-sight-microsoft-defender-antivirus
- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/prevent-changes-to-security-settings-with-tamper-protection
- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-network-connections-microsoft-defender-antivirus
- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/specify-cloud-protection-level-microsoft-defender-antivirus
- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/enable-cloud-protection-microsoft-defender-antivirus
- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/utilize-microsoft-cloud-protection-microsoft-defender-antivirus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f0f5a3-f095-3fa4-90dd-7dee8ccb49ad
* Version Independent ID: 1bec5d66-a92a-4b0d-b9d8-f43c9eab4a50
* Content: [Specify cloud-delivered protection level in Microsoft Defender Antivirus - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/specify-cloud-protection-level-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/specify-cloud-protection-level-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/specify-cloud-protection-level-microsoft-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
@SwiftOnSecurity : You closed this issue ticket before anything could be followed up here. Did you find the issue to be incorrect or already reported?

**Comment by dr-angel** [comment]
Possibly reported elsewhere, but linked articles are misleading, as they only state "Applies to: Microsoft Defender Advanced Threat Protection (Microsoft Defender ATP)", when these features can be applied without a subscription for ATP. @SwiftOnSecurity, please come tend to your sysmon config... so many PRs waiting

**Comment by e0i** [comment]
@SwiftOnSecurity

With the help of your feedback, the content has been updated with relevant changes accordingly via PR #8182. Thank you.
