### ISSUE TITLE
stupidity

### ISSUE THREAD

**Issue by wschlossberg** [MicrosoftDocs/windows-itpro-docs#8041]
" Note
The month indicator for this release is 04 instead of 03 to avoid confusion with Windows releases in the year 2003."

**And to create confusion with Windows releases in the year 2004.**
stupid stupid stupid
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d651de3c-b8eb-e8d9-8138-1eadb758bf2e
* Version Independent ID: a19a8b65-0f4a-efd5-7f83-56bd07cc8c3b
* Content: [What's new in Windows 10, version 2004 - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-2004)
* Content Source: [windows/whats-new/whats-new-windows-10-version-2004.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/whats-new-windows-10-version-2004.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
There were no Windows OS releases in 2004.

**Comment by wschlossberg** [comment]
It’s still stupid

 

Regards,

Bill Schlossberg

 <mailto:bschlossb@gmail.com> bschlossb@gmail.com (New Email Address) 

Mobile/MMS:  203-979-5217  Stamford, CT

 

 


Sender’s Search terms, reminders, notes to self:
