### ISSUE TITLE
Microsoft Account same as AAD account?

### ISSUE THREAD

**Issue by johnwildes** [MicrosoftDocs/windows-itpro-docs#8043]
Hello, I'm wondering about this document and policy, when it says Microsoft account I believe this to be an MSA (outlook.com, live.com, hotmail.com or msn.com) account.  Not an AAD account assigned by my organization correct? Would the document benefit from clarifying this or linking to that definition if it exists?  

thanks
john

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4cc6a1f-7cdf-22cd-4b26-b5535de7cae6
* Version Independent ID: 5b2cf033-52ba-651f-5ad9-1d9fa97b21a5
* Content: [Accounts Block Microsoft accounts (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/accounts-block-microsoft-accounts)
* Content Source: [windows/security/threat-protection/security-policy-settings/accounts-block-microsoft-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/accounts-block-microsoft-accounts.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello,
**when it says Microsoft account I believe this to be an MSA (outlook.com, live.com, hotmail.com or msn.com) account. ** - yes, correct.
**Would the document benefit from clarifying this or linking to that definition if it exists?** - I added link to the article
Thank you

**Comment by e0i** [comment]
@johnwildes 

Content has been according to your feedback via PR #8147. Thank you.
