### ISSUE TITLE
Create and Link Ansible Galaxy Project

### ISSUE THREAD

**Issue by nwerker** [MicrosoftDocs/windows-itpro-docs#8045]
For somebody who is new to ansible this is a superb documentation! But I think for somebody who uses ansible in their infrastructure it could be benefitial to create an ansible galaxy role and add the link in this documentation. Is this planned in the near future and if not is there a way to contribute this? 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 623e0469-826c-5cdf-6dc4-67c80e232d0f
* Version Independent ID: 0f6c33bc-711a-84d6-01bb-04d13f5a85a2
* Content: [Bereitstellen von Microsoft Defender ATP für Linux mit Ansible - Windows security](https://docs.microsoft.com/de-de/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Hello, @nwerker You may contribute to the article via the following link and public contributions are most welcome:

https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md

Please feel free to re-open this issue with specifics and independent contributors would be able to come up with necessary modifications. Thank you.
