### ISSUE TITLE
Is Credential Guard available on Windows 10 Pro?

### ISSUE THREAD

**Issue by mtwelve** [MicrosoftDocs/windows-itpro-docs#8046]
Hello,

This document is in conflict with this Windows 10 SKU comparison page - https://www.microsoft.com/en-gb/windowsforbusiness/compare

This document makes only one reference under the, [Baseline protections section](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-requirements#baseline-protections), to needing Enterprise/Education.

The SKU comparison page clearly states CG is available with Pro.

Are there differences in what CG can do between Enterprise and Pro?

Is it available in Pro but unsupported?

Is there a nuance I am missing or is this documentation out of date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0238a73f-da06-ae17-c61d-85ae54e0f7cb
* Version Independent ID: e5bb4a25-a7c3-3a16-bd95-d6f2513402e0
* Content: [Windows Defender Credential Guard Requirements (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-requirements#baseline-protections)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@mtwelve , i used professional edition and enterprise edition, in both sku's  Credential Guard is  available.

**Comment by e0i** [comment]
With the help of your feedback, the issue has been reviewed and an update to the documentation has been published via PR #8181. Thanks for your feedback.
