### ISSUE TITLE
TCP / IP pipeline  and hybrid authentication

### ISSUE THREAD

**Issue by jackadam1981** [MicrosoftDocs/windows-itpro-docs#8047]
The TCP / IP pipeline scheme is missing.

Missing hybrid authentication.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e6204280-0cde-d489-7973-f0e62c854675
* Version Independent ID: fd7b5637-b83c-0f93-247d-c8cf2942a475
* Content: [使用 MDT 数据库暂存 Windows 10 部署信息（Windows 10） - Windows Deployment](https://docs.microsoft.com/zh-cn/windows/deployment/deploy-windows-mdt/use-the-mdt-database-to-stage-windows-10-deployment-information)
* Content Source: [windows/deployment/deploy-windows-mdt/use-the-mdt-database-to-stage-windows-10-deployment-information.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/use-the-mdt-database-to-stage-windows-10-deployment-information.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
This topic talks about the MDT database. There is no authentication other than that on the local MDT server.  Please clarify what you think needs to be changed or added.

**Comment by greg-lindsay** [comment]
本主题讨论MDT数据库。除了本地MDT服务器上的身份验证外，没有其他身份验证。请说明您认为需要更改或添加的内容。

**Comment by jackadam1981** [comment]
我在另一台服务器上使用docker运行sqlserver，所以需要使用tcp/ip协议，使用混合验证模式验证。

**Comment by jackadam1981** [comment]
I use docker to run SQL Server on another server. How to connect.

**Comment by e0i** [comment]
Closing via the article author's comment above.
