### ISSUE TITLE
In windows 10v2004

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#8049]
In windows 10 v2004 with latest admx templates, after checking, i found  Signature Updates** is replaced to Security Intelligence Updates
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c376152e-d0c8-288d-c5e1-2a7c7d4472b4
* Version Independent ID: 3d14560c-b351-86d0-3de4-a059c9cbf6d8
* Content: [Apply Microsoft Defender Antivirus updates after certain events - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/manage-event-based-updates-microsoft-defender-antivirus#cloud-report-updates)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/manage-event-based-updates-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/manage-event-based-updates-microsoft-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by e0i** [comment]
@RAJU2529 Can you expand a little more about the implications of this defect in the article? What exactly needs to be updated? Thank you.

**Comment by RAJU2529** [comment]
@e0i in gp policy this name **Signature Updates** is changed to **Security Intelligence Updates**

**Comment by e0i** [comment]
Noted, Thank you for the clarification.

**Comment by e0i** [comment]
Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.
