### ISSUE TITLE
Linux support for MDATP is GA

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/windows-itpro-docs#8050]
https://techcommunity.microsoft.com/t5/microsoft-defender-atp/microsoft-defender-atp-for-linux-is-now-generally-available/ba-p/1482344

Please remove preview language in this docs article in relation to Linux.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@SLeuthold . yes I understood, that particular belongs to linux.  But in this article, other operating system requirements also mentioned, so linux also included

**Comment by SLeuthold** [comment]
The article notes that Linux support is in "Preview" however, that is incorrect. Linux support is GA.

**Comment by mjcaparas** [comment]
Thanks, updates underway.

**Comment by illfated** [comment]
(ref. #8248)

**Comment by illfated** [comment]
(also ref. #7963 )
