### ISSUE TITLE
Unclear on what DVD/ISO to be mounting

### ISSUE THREAD

**Issue by AlBrough** [MicrosoftDocs/windows-itpro-docs#8051]
[...]
Updating the Schema
[...]
2. Type cd /d x:\support\adprep where x is the drive letter of the DVD or mounted ISO.

This is rather vague on which media should be mounted to run this process - this section should rather read:
1. Mount Windows Server install media, if not already present
2. Open an elevated command prompt.
3. Type cd /d x:\support\adprep where x is the drive letter of the DVD or mounted ISO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c400ea-f52d-b45b-a871-31c94262084d
* Version Independent ID: 9465e043-990f-cb8b-2d4b-33dc8d3c21bf
* Content: [Update Active Directory schema for cert-trust deployment (Windows Hello for Business) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-ad-prereq)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-ad-prereq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-ad-prereq.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
Closing via #8137
