### ISSUE TITLE
Instructions require reordering

### ISSUE THREAD

**Issue by bchurchill** [MicrosoftDocs/windows-itpro-docs#8055]
The yum-config-manager isn't installed on RHEL systems by default.  To install it, the yum-utils package is needed.  This is already in the instructions, but it appears in the instructions after the use of the yum-config-manager command.  The instruction to install yum-utils just needs to be moved up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2197cba-30ac-1749-e25a-6f39c9ee9d20
* Version Independent ID: bcd14f13-ab59-8e69-5c83-42fee6e51f87
* Content: [Deploy Microsoft Defender ATP for Linux manually - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Closing via #8141.
