### ISSUE TITLE
Incorrect location

### ISSUE THREAD

**Issue by RubenMeneses** [MicrosoftDocs/windows-itpro-docs#8056]
I don't believe that “Audit Credential Validation” exists under “Detailed Tracking” but under “Account Logon” instead. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 739bc932-12f0-9595-fbd2-d5b0df73fe93
* Version Independent ID: cd1f89ad-34db-bb96-e9ef-2137958c9403
* Content: [Advanced security audit policy settings (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/advanced-security-audit-policy-settings)
* Content Source: [windows/security/threat-protection/auditing/advanced-security-audit-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/advanced-security-audit-policy-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Confirmed, “Account Logon”:
![image](https://user-images.githubusercontent.com/48041687/91198466-035dd800-e716-11ea-8be8-101704f02f06.png)
“Detailed Tracking”:
![image](https://user-images.githubusercontent.com/48041687/91198520-1670a800-e716-11ea-98e0-c1cacdd87b4d.png)

**Comment by e0i** [comment]
Closing via #8140
