### ISSUE TITLE
License info

### ISSUE THREAD

**Issue by pnwnightowl** [MicrosoftDocs/windows-itpro-docs#8061]
Please include licenses details for running MDATP on MacOS; similar to the licenses details for Windows page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7a3b63b-afc5-1b25-3a30-e75c788f4a93
* Version Independent ID: 85498c85-fe13-fead-3bac-44db5614db0d
* Content: [Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-mac)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-mac.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-mac.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
With the help of your feedback, the issue has been reviewed and an update to the documentation has been published via PR #8135. Thanks for your feedback.
