### ISSUE TITLE
make and model values dell

### ISSUE THREAD

**Issue by frenkeh** [MicrosoftDocs/windows-itpro-docs#8067]
Hi,

Just want to mention that the %make% Value for Dell should be "Dell Inc." Instead of Dell. 
It cost me a few hours to figure out why my drivers weren't injected. 
Can you change this in the instructions? It might help other people. 

Page: https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt 
Subject: Create the logical driver structure in MDT

Kind Regards, 
Frank van Es 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt#feedback)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Will do, thanks for the catch!
