### ISSUE TITLE
the users do not know their password

### ISSUE THREAD

**Issue by rishtech** [MicrosoftDocs/windows-itpro-docs#8070]
If the user doesn't know their passsword, how they will sign in to their machine for the first time.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca080bd-ed37-60a8-ec22-b1929166ff0c
* Version Independent ID: d2742e0c-9d66-4b1f-8555-a1fb1546455b
* Content: [Passwordless Strategy - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/passwordless-strategy)
* Content Source: [windows/security/identity-protection/hello-for-business/passwordless-strategy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/passwordless-strategy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by rishtech** [comment]
When SCRIL, is enabled the password gets changed on prem, the same will be replicated to AzureAD. 
Now all the other devices which users is using preferbly not windows, will break authentication. 
Until and unless, it's and ideal world of only windows 10 devices.
A typical use case, Outlook app on IOS and android will prompt the user to enter their credential, when the password has been changed on-prem, and the user doesn't know the password now.
I would like some steps to be mentioned for these kind of scenarios as well.

**Comment by msbemba** [comment]
@rishtech Thank you for your feedback. This works only with win10 and 11 and does not connect to the password in AD or AAD which works with M365/outlook and other Microsoft apps.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @rishtech Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
