### ISSUE TITLE
Expert on demand 

### ISSUE THREAD

**Issue by mikki** [MicrosoftDocs/windows-itpro-docs#8074]
[Enter feedback here]

Hi Team

I have a Microsoft 365 E5 license!. Is the expert on demand service included with M365 E5 or Do i need to buy premier support?

your help would be appreciated 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2afabca-45f7-1cc0-5de2-a8a659154946
* Version Independent ID: 365edbfc-259c-44f6-ad5d-614c18d4c08c
* Content: [Microsoft Threat Experts - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-threat-experts)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-threat-experts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-threat-experts.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
Hello, @mikki 

Your licensing question can be best answered via the appropriate  support channel linked below:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

The issues section of this repository is for documentation issues.

Thank you.
