### ISSUE TITLE
When will 'Block persistence through WMI event subscription' be available through Intune?

### ISSUE THREAD

**Issue by alexlushsevernunival** [MicrosoftDocs/windows-itpro-docs#8079]
Block persistence through WMI event subscription - When will this policy be available through Intune please? All the other ASR rules are available except this one.

You have security recommendations for Microsoft Defender Security Center pointing to this page and saying to use Intune, but no way to deploy the setting using Intune.
![image](https://user-images.githubusercontent.com/23653153/90391044-5edbf600-e084-11ea-80cd-8371a8ab6f04.png)

Also got a user voice item open on this issue here:
https://microsoftintune.uservoice.com/forums/291681-ideas/suggestions/40862476-asr-rule-block-persistence-through-wmi-event-subs
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d747289-63b2-f71a-b40c-31b52982215c
* Version Independent ID: b52f6593-03f2-aa57-ec0e-eaef560dcaf0
* Content: [Use attack surface reduction rules to prevent malware infection - Windows security](https://docs.microsoft.com/en-gb/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction#block-persistence-through-wmi-event-subscription)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@alexlushsevernunival , still not available,  only the windows 10 v1903 qnd later version engineering design  team can answer this question.

**Comment by e0i** [comment]
@alexlushsevernunival

It seems that it has already been documented in the article that the mentioned feature is not yet available. The issues section of this repository is used to track documentation problems, and given that there is no defect with the article, and that there is already a user voice for the problem, the issue is being closed.

Feel free to re-open this issue if you'd like to report a specific defect with the documentation itself.

Thank you.
