### ISSUE TITLE
Table Confusion

### ISSUE THREAD

**Issue by newark123** [MicrosoftDocs/windows-itpro-docs#8080]
/genconfig and /nocompress are included in both axis

But the info about compatibility is contradictory .

I don't know which is right but it looks messed up  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c7e6db2-1517-e9b9-cd9a-6a6aaf84ccc3
* Version Independent ID: daab80f9-640e-36c9-e60a-084901b11c05
* Content: [ScanState Syntax (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-scanstate-syntax#how-to-use-ui-and-ue)
* Content Source: [windows/deployment/usmt/usmt-scanstate-syntax.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/usmt/usmt-scanstate-syntax.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@newark123 , We can use   scanstate    /genconfig   with  /nocompress 
or     /nocompress  with /genconfig

**Comment by RAJU2529** [comment]
Mark  X should be sremoved .  @e0i ,  Please look into this issue #8080

**Comment by greg-lindsay** [comment]
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8162
