### ISSUE TITLE
 Example # 2 heading has NTLM spelled as NTML

### ISSUE THREAD

**Issue by ShaXam-King** [MicrosoftDocs/windows-itpro-docs#8081]
The Example # 2 heading has NTLM spelled as NTML. The rest of the article is correct it appears. We don't want anyone to think Windows NT has it's own markup language ;-) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1814eead-2dcd-c8d6-96dd-b4ce2590fb08
* Version Independent ID: df05098f-6d60-1b9d-c674-a964c5ac8d03
* Content: [Behavioral blocking and containment - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/behavioral-blocking-containment)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/behavioral-blocking-containment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/behavioral-blocking-containment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
👍 Very good, thank you for pointing out the typo (as well as the funny side of the misspelling). 😄

A Pull Request will be available shortly to resolve the issue.
