### ISSUE TITLE
Request a Driver Updates section in here as well since it also is a source of questions.

### ISSUE THREAD

**Issue by SillyKeith** [MicrosoftDocs/windows-itpro-docs#8085]
[Enter feedback here]
This is a great public article for OS Updates.  Have folks thought about also adding a "How Driver Updates work" section too?  I helped write and update the "Updating Drivers and Driver Servicing" on osgwiki and a central spot like this seems like a perfect place for public content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349d337e-ca0f-a40a-a522-bd1ae71c7d1e
* Version Independent ID: 50f0c3b0-eaad-89c0-eb3c-878e7564d6f6
* Content: [Windows Update troubleshooting - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-troubleshooting)
* Content Source: [windows/deployment/update/windows-update-troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-troubleshooting.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@jaimeo It seems that this documentation feedback is suitable for your consideration. Please advise. Thank you.

**Comment by jaimeo** [comment]
@SillyKeith it's a great suggestion. How about you get in touch with me and @arcarley internally and let's see what we can come up with?

**Comment by e0i** [comment]
Closing via Jamie's suggestion above. Thank you.
