### ISSUE TITLE
Document that creating outbound firewall rules for some services does not work

### ISSUE THREAD

**Issue by carlreinke** [MicrosoftDocs/windows-itpro-docs#8093]
Creating outbound rules for some services (ex. BITS and Cryptographic Service) does not work on Windows 10 (see [this question on SuperUser](https://superuser.com/questions/994306/what-firewall-rules-will-allow-windows-update-and-only-windows-update-to-work) which mirrors my own experience trying to create similar rules on Windows 10).

Please document the services that creating outbound firewall rules will not work for.

(I'd prefer to report this as a bug in Windows, but Feedback Hub is a black hole, and it's unclear how else to get someone's attention.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c673d2f-a224-8f9c-c3c8-fd8c09d084dc
* Version Independent ID: f6668ab2-72b0-1a58-f18b-09252f068e9d
* Content: [Create an Outbound Program or Service Rule (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/create-an-outbound-program-or-service-rule)
* Content Source: [windows/security/threat-protection/windows-firewall/create-an-outbound-program-or-service-rule.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/create-an-outbound-program-or-service-rule.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@carlreinke . I read your question. 
BITS and cryptographic services are essential for windows update.

do you want to block all services executable files except BITS and cryptographic .
 will you take video how you created  outbound rules and upload to Youtube then paste the link here

**Comment by carlreinke** [comment]
Sorry, I wasn't clear,  I have the Windows Firewall set to disallow connections that do not match any rules.  I want to allow BITS and other services without allowing all services that use svchost.exe.

I don't think a YouTube video is going to be terribly useful.

**Comment by RAJU2529** [comment]
@carlreinke  this modification rule is complected , let windows experts will answers

**Comment by VLG17** [comment]
@carlreinke My recommendation is to use [UserVoice](https://windowsserver.uservoice.com/forums/295047-general-feedback) for submitting this feedback. This is the official feedback channel monitored by engineering.

I think there is more that needs to be understood behing the desire to allow just certain services and not all services that use svchost.exe. I don't think there is a defined list of services for which you can create outbound allow rules and other for which you cannot. It sounds specific to this scenario which needs to be understood in detail. 

You could also [open a support ticket](https://support.microsoft.com/en-my/contactus/), so a support engineer can look at your outbound rules, how you configured them and why they are not working. If the conclusion is that indeed for certain services you cannot set outbound rules, we can gladly specify this in the article.
