### ISSUE TITLE
Add note about FSMO Role

### ISSUE THREAD

**Issue by darkhawk311** [MicrosoftDocs/windows-itpro-docs#8094]
It should be noted that the PDC Emulator FMSO role must reside on one of the 2016+ domain controllers before the groups will be available.  If the the role is on 2012 R2 or below, a search for KeyAdmin will produce no results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdb237b7-6181-5638-8e9a-fa52fe5327d5
* Version Independent ID: 27b14b20-65f1-302a-cd74-3c1443d8a863
* Content: [Hybrid Windows Hello for Business - Directory Synchronization - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-dir-sync)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-dir-sync.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-dir-sync.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by MaratMussabekov** [comment]
Hello @darkhawk311 ,
From my experience, the group appears after the AD schema extension during the deploying of the first AD DC running Windows Server 2016, it didn't required PDC emulator to run WS 2016 in my case.
Could you please advise, was this required in your deployment?
Thank you

**Comment by darkhawk311** [comment]
We have a mix of 2019 and 2012 r2 servers.   The group appeared after
moving the FSMO role to a 2019 DC.

Timmy Roussel
504.329.8274 mobile

**Comment by MaratMussabekov** [comment]
Dear @e0i ,
would it be possible to contact author to ask for clarification? Is moving PDC emulator role to domain controller running WS 2016+ required or not?
Thank you

**Comment by darkhawk311** [comment]
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-faq Why is the Key Admins group missing, I have Windows Server 2016 domain controller(s)? The Key Admins and Enterprise Key Admins groups are created when you install the first Windows Server 2016 domain controller into a domain. Domain controllers running previous versions of Windows Server cannot translate the security identifier (SID) to a name. To resolve this, transfer the PDC emulator domain role to a domain controller running Windows Server 2016. Sent from Mail for Windows 10 From: MaratMussabekovSent: Tuesday, September 1, 2020 6:10 AMTo: MicrosoftDocs/windows-itpro-docsCc: darkhawk311; MentionSubject: Re: [MicrosoftDocs/windows-itpro-docs] Add note about FSMO Role (#8094) Dear @e0i ,would it be possible to contact author to ask for clarification? Is moving PDC emulator role to domain controller running WS 2016+ required or not?Thank you—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by MaratMussabekov** [comment]
Hello @darkhawk311 ,
good point, I will create a PR.
Thank you

**Comment by e0i** [comment]
With the help of your feedback, the issue has been reviewed and an update to the documentation has been published with the PR #8199. Thank you.
