### ISSUE TITLE
Deployment Model

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#8097]
Hello,

About Note "If the object truly does not exist, then your environment does not bind you to a specific deployment or require changes to accommodate the desired deployment type."

Can you please explain this, we do have ADFS, but command "Get-AdObject" returns an error, so what to use in the Planning Worksheet? Do we require changes or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5739fab2-c6db-a7a9-b0e7-2bf4b85912a7
* Version Independent ID: 82c58053-c1d7-d938-1b0f-f3f7f70ada3b
* Content: [Planning a Windows Hello for Business Deployment - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-planning-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-planning-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by MaratMussabekov** [comment]
Hello @lightupdifire , are you sure Device Registration Services is deployed successfully on your AD FS? Have you tried to find the object using ADSIEdit?
Thank you

**Comment by lightupdifire** [comment]
@MaratMussabekov 
Pfew, ADSIEdit did the trick this time, seems have looked before in the wrong ADSIEdit Connection. Case close.
