### ISSUE TITLE
List of enlightened Microsoft apps

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#8099]
Hello,

Any plans to include WVD in WIP?
Right now if I'm connected via WVD, inside in WVD local disk mapping allowed by default, this means I can copy corporate data directly to my PC drive and data will be not encrypted on my PC.
WVD uses Remote Desktop msrdc.exe and msrdcw.exe, not sure if we should simply import app info from file or wait for some update on WIP policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ed0150-0172-f3ad-3c7f-3a7141efbe64
* Version Independent ID: 6a978d2b-a0ff-1052-ce00-06f02f30cfa1
* Content: [List of enlightened Microsoft apps for use with Windows Information Protection (WIP) (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip#list-of-enlightened-microsoft-apps)
* Content Source: [windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@lightupdifire According to [this thread](https://techcommunity.microsoft.com/t5/windows-virtual-desktop/remote-desktop-client-on-windows-10-doesn-t-appear-to-support/m-p/1372916) it works but it's quite tricky to configure it right. More details [here](https://blog.ciaops.com/2020/05/09/remote-desktop-app-for-wvd-doesnt-work-with-wip/).

Looking at the WVD Roadmap and the [latest announcements](https://techcommunity.microsoft.com/t5/windows-virtual-desktop/announcing-new-management-security-and-monitoring-capabilities/m-p/1699543) i don't see anything related to WIP.

**Comment by lightupdifire** [comment]
@VLG17 
From our side, we don't see any errors, like cannot update feed or start Remote Desktop.
I do see the app as "enlightened", issue is that data copied from the Remote Desktop to my PC not encrypting.
Then maybe good to add a FAQ for WIP for WVD support?
