### ISSUE TITLE
Cannot sign in with Azure AD O365 account

### ISSUE THREAD

**Issue by GH4TP** [MicrosoftDocs/windows-itpro-docs#810]
Cortana does not allow me to sign in with an O365 account. I have verified the account’s Azure AD status but Cortana wants a .live / windows account saying it cannot find the AD O365 account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 192c6282-8795-78d7-1b1f-c2e2fac833a0
* Version Independent ID: 653498e2-435b-519d-c198-94d8e74523da
* Content: [Set up and test Cortana with Office 365 in your organization (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/cortana-at-work/cortana-at-work-o365)
* Content Source: [windows/configuration/cortana-at-work/cortana-at-work-o365.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/cortana-at-work/cortana-at-work-o365.md)
* Service: **unspecified**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by andreabichsel** [comment]
The best way to get help with this issue is to contact Microsoft Support. Contact links are on https://support.microsoft.com/en-us/contactus/.
