### ISSUE TITLE
Add release notes for July and August 2020

### ISSUE THREAD

**Issue by brettaweston** [MicrosoftDocs/windows-itpro-docs#8100]
The release notes for July and August 2020 are missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1528404e-3ead-d3aa-e0aa-59e5a8b4889a
* Version Independent ID: d8c3bf1c-232e-a388-326d-830447baef19
* Content: [Manage Microsoft Defender Antivirus updates and apply baselines - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/manage-updates-baselines-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/manage-updates-baselines-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/manage-updates-baselines-microsoft-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@brettaweston THANK YOU for raising this issue. I am looking into it.

**Comment by denisebmsft** [comment]
Hello @brettaweston and thanks again for the feedback. We have updated the article and the changes will be live later today.
