### ISSUE TITLE
Microsoft Intune does not show scan results

### ISSUE THREAD

**Issue by ryanhelmer** [MicrosoftDocs/windows-itpro-docs#8107]
Please do not close this without revising the documentation (this issue was already mentioned, but then closed), because this is a documentation issue (and perhaps also a product issue).

These instructions are inaccurate:

> 1. In Intune, go to Devices > All Devices and select the device you want to scan.
> 2. Click the scan results in Device actions status.

The only thing it shows is that the scan _status_  (completed). It does NOT show the _results_ of the scan. The results are the most important part. Where does one find the _results_ of the scan in Intune, and in Microsoft Defender Security Center?

Thank you very much for your help! 
Ryan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84b48087-97c2-e6c2-2080-e5fcdb662268
* Version Independent ID: 6f1caca8-c986-7364-bd2c-7975c9509ff6
* Content: [Review the results of Microsoft Defender AV scans - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/review-scan-results-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/review-scan-results-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/review-scan-results-microsoft-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by MaratMussabekov** [comment]
Hello,
**The only thing it shows is that the scan status (completed). It does NOT show the results of the scan.** - confirmed, I believe the Intune section should be removed from the article at all (I have just created a PR)
**Where does one find the results of the scan in Intune, and in Microsoft Defender Security Center?** - tried to find it, but didn't succeed, Action Center in Microsoft Defender Security Center only shows the event, it doesn't show the results. I think it is not possible to collect this data using Microsoft Defender Security Center, dear @e0i, would it be possible to reach the author for confirmation?
Dear @ryanhelmer , If you need to collect scan results data from all the computers in your network, I would recommend to create a PowerShell script that would collect the data and then distribute this script using Intune/GPO.
Thank you

**Comment by e0i** [comment]
Closing via the answer above and the merged PR #8313.
