### ISSUE TITLE
Lacking partner submission information

### ISSUE THREAD

**Issue by 9b** [MicrosoftDocs/windows-itpro-docs#8108]
There is no contact information for who to submit partner applications/requests to within Microsoft. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afd513c3-d291-0e1e-d904-acf7c9f66765
* Version Independent ID: c1490bb4-5d49-5529-630f-0a13d99b5e77
* Content: [Become a Microsoft Defender ATP partner - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/get-started-partner-integration)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/get-started-partner-integration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/get-started-partner-integration.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
Closing via #8312.
