### ISSUE TITLE
Outdated process

### ISSUE THREAD

**Issue by zachsaltzman** [MicrosoftDocs/windows-itpro-docs#811]
The instructions in this doc for Defender ATP setup and on-boarding process in the Azure portal with Intune seem to be a few versions old. For example you don't need to use a custom profile to configure Defender ATP endpoint on-boarding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc98378-18c5-81bf-769e-d76d26852c91
* Version Independent ID: dd542381-071b-e583-f082-976e8fd91019
* Content: [Onboard Windows 10 machines using Mobile Device Management tools](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-endpoints-mdm-windows-defender-advanced-threat-protection#onboard-windows-10-machines-using-microsoft-intune)
* Content Source: [windows/security/threat-protection/windows-defender-atp/configure-endpoints-mdm-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/configure-endpoints-mdm-windows-defender-advanced-threat-protection.md)
* Service: **unspecified**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Thank you for your feedback! We're working on updating the content to include an updated version.

**Comment by zachsaltzman** [comment]
Hi - the article is still showing the same outdated screenshots for the Azure Intune profile. Does it take some time for the doc to update and refresh?
