### ISSUE TITLE
How fresh is the software inventory from the endpoint?

### ISSUE THREAD

**Issue by wagoddin-diveplane** [MicrosoftDocs/windows-itpro-docs#8121]
While this is a great feature, I find myself asking the same question over and over again... how fresh or accurate is the endpoint inventory that we see in this console and that the CVE and other product data is joined to?  When I go out to my team and push for a software update, it would make our lives a whole lot better if we could force an update to push to the cloud when we were done doing updates on a particular machine.  This way our threat dashboard is now up to date and accurate for that endpoint.  At a minimum, it would be nice if you timestamped that data collected and made it available in the GUI and also document how long a 'normal' (not forced) inventory occurs on each end point and then pushes to the cloud.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc646df4-fc3c-9a3d-7f17-b12777c4a659
* Version Independent ID: 1b37afc4-6615-e88a-d9d4-6cb29e26059e
* Content: [Software inventory in threat and vulnerability management - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/tvm-software-inventory)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/tvm-software-inventory.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/tvm-software-inventory.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Hi @wagoddin-diveplane thank you for your feedback! I have shared it with the PM team. It typically takes two hours for data to be reflected in the Microsoft Defender Security Center. However, engineering changes are currently in the works to significantly reduce this time. Stay tuned!
