### ISSUE TITLE
Event 4723 - change password - XML log file - success/faulire distinction

### ISSUE THREAD

**Issue by washuu** [MicrosoftDocs/windows-itpro-docs#8122]
[Enter feedback here]

How we can tell if the result was success or failure by looking at the XML log entry? Even in the given example, it's not obvious. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c212537b-4a03-97e7-3406-76e6f73e8b9e
* Version Independent ID: 9d08ffbc-03b4-5b41-4229-76898f9c791e
* Content: [4723(S, F) An attempt was made to change an account's password. (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4723)
* Content Source: [windows/security/threat-protection/auditing/event-4723.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4723.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello, checked in the test environment.
In case password was changed successfully, following events are appears:
1. 4768 A Kerberos authentication ticket (TGT) was requested.
2. 4738 A user account was changed.
3. 4723 An attempt was made to change an account's password.
4. 4364 An account was logged off.

In case new password fails to meet the password policy:
1. 4768 A Kerberos authentication ticket (TGT) was requested.
2. 4364 An account was logged off.

So it doesn't behave like it is described in the article: **This event generates every time a user attempts to change his or her password. For domain accounts, a Failure event generates if new password fails to meet the password policy.**

Dear @e0i ,
can we contact the author for confirmation?

Thank you
