### ISSUE TITLE
Third party AMSI dll loaded failure when EnableSvchostMitigationPolicy is set to 1

### ISSUE THREAD

**Issue by koron21** [MicrosoftDocs/windows-itpro-docs#8123]
[Enter feedback here]

This policy: **Enable Svchost.exe mitigation policies** will cause performance issues on Windows Server 2019 with Third party AV. We got a case reported by Symantec where issue comes in when symAMSI.dll failed to be loaded due to it is not signed by Microsoft, this dll load occurs in many places which consumed CPU cycles.  SymAMSI.dll is probably Symantec’s implementation library talking with our amsi.dll.

Symantec published an public KB saying this GPO needs to be turned off for their products to work.
https://knowledge.broadcom.com/external/article/197096

Apart from Symantec, AV like Sophos also reported the policy not working well with their products. 
Can we add some additional statement into this GPO saying it might cause issues with 3rd party AV due to their AMSI implementation is not signed by Microsoft?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4cb845a-e2f6-0bcb-ea4b-7b3ab8365f2a
* Version Independent ID: 4d2f43a5-2c93-c4b3-64ff-85e48e92092a
* Content: [Policy CSP - ServiceControlManager - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-servicecontrolmanager#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-servicecontrolmanager.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-servicecontrolmanager.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Heidilohr
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@crown21. I also read the documensite provided by you. Let Microsoft AMSI analysis will test whether  SYMAMSI.dll will let requirements o AMSI.

**Comment by illfated** [comment]
Ref. Pull Request #8322 for the addition of an important note regarding this policy.
