### ISSUE TITLE
Weakness Scan Intervals

### ISSUE THREAD

**Issue by benpaul4u** [MicrosoftDocs/windows-itpro-docs#8125]
Please add details on frequency of Weakness Scan. For example, I have fixed the Vulnerabilities listed for a system. But it still shows as active. How long do I need to wait for the system to be excluded from the Vulnerabilities list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e827de-5cf9-4506-880f-908d454f5807
* Version Independent ID: a9da7cb9-222f-084a-7a1a-36730cf0e669
* Content: [Weaknesses found by threat and vulnerability management - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/tvm-weaknesses)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/tvm-weaknesses.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/tvm-weaknesses.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Hi @benpaul4u. When a change is made on a device, it typically takes two hours for the data to be reflected in the Microsoft Defender Security Center. However, it may sometimes take longer.
