### ISSUE TITLE
Please update to reflect Configuration Manager Current Branch support for bitlocker management

### ISSUE THREAD

**Issue by adamgourd** [MicrosoftDocs/windows-itpro-docs#8128]
Please update to reflect Configuration Manager Current Branch support for bitlocker management
https://docs.microsoft.com/en-us/mem/configmgr/protect/
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e5380a-53da-6df1-1952-1be89d9b5969
* Version Independent ID: 82af0c50-fb10-3ad3-1f1d-74a068ea6fa7
* Content: [BitLocker Management Recommendations for Enterprises (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @adamgourd ,
It states "Companies that image their own computers using Microsoft System Center 2012 Configuration Manager SP1 (SCCM) **or later** can use an existing task sequence to pre-provision BitLocker"
Doesn't  "or later" means support of Current Branch? 
Thank you
