### ISSUE TITLE
Run custom actions during feature update link is not working

### ISSUE THREAD

**Issue by SergioCalderonR** [MicrosoftDocs/windows-itpro-docs#813]
The Run custom actions during feature update link is broken. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c880203c-6a5b-28e7-c74d-152890baa955
* Version Independent ID: 59c9eb13-dd44-358a-130d-ca1e020573ba
* Content: [What's new in Windows 10, version 1803](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1803)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1803.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1803.md)
* Service: **unspecified**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by lizap** [comment]
Hi, Sergio - can you check again? We had a delay between content publishing, but it's working for me now. Thanks!

**Comment by sandytsang** [comment]
Yes, I did a pull request for another link that is wrong, should remove "review" in hyperlink,see #815, they only merged our request and closed my pull request.

**Comment by SergioCalderonR** [comment]
I also edited the document to fix the link. I suppose they will approve it soon.
