### ISSUE TITLE
Link to Azure IPs needs updating.

### ISSUE THREAD

**Issue by jmmowrer** [MicrosoftDocs/windows-itpro-docs#8138]
Azure IP link needs to be updated to go here: https://www.microsoft.com/en-us/download/details.aspx?id=56519
The current link points to the Azure IP doc that is deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83207fc9-2c91-eb07-4237-6bb1f42e3778
* Version Independent ID: 5db33cf3-2dcb-bb33-a252-3a13ca9737f9
* Content: [Configure device proxy and Internet connection settings - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
Closing via #8145. Thank you.
