### ISSUE TITLE
Is CHAP the only affected protocol?

### ISSUE THREAD

**Issue by ivandretvic** [MicrosoftDocs/windows-itpro-docs#8142]
We have been implementing Azure MFA NPS extension, and have found that using MS CHAP v2 also requires the setting to be enabled in order for users to be able to successfully sign in. Can we please get clarity on all Protocol's impacted?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a421f9ba-160f-a394-1297-94143ecdc51f
* Version Independent ID: b30be967-331a-be20-45d8-12991445cbe7
* Content: [Store passwords using reversible encryption (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/store-passwords-using-reversible-encryption)
* Content Source: [windows/security/threat-protection/security-policy-settings/store-passwords-using-reversible-encryption.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/store-passwords-using-reversible-encryption.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@ivandretvic According to [this article](https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-nps-extension-vpn) :

> **If you configure Extensible Authentication Protocol (EAP), you must use either Microsoft Challenge-Handshake Authentication Protocol (CHAPv2) or Protected Extensible Authentication Protocol (PEAP)**. No other EAP is supported.
