### ISSUE TITLE
Scheduled Task Duration

### ISSUE THREAD

**Issue by gerrynicol** [MicrosoftDocs/windows-itpro-docs#8146]
[Enter feedback here]
Hi There,
It is mentioned in the document that the scheduled task runs every 5 minutes for one day. After a day, does the scheduled task no longer run? If that is the case, what happens if a desktop is provisioned but a user with an M365 license logs in after that period of time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @gerrynicol - Thank you for your query. Please note that the task will only run for 5 mins a 1 day. After that, it will run the next day. If the device is already provisioned then it will show a success and if not provisioned then it will provisioned the device based on the license assigned to the user logged in to the device.  
Thank
Imran.
