### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by bledMS82** [MicrosoftDocs/windows-itpro-docs#8150]
The link for windows sandbox is broken and redirects to an invalid page : https://www.microsoft.com/security/blog/2018/10/26/microsoft-defender-antivirus-can-now-run-in-a-sandbox/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9d6b543-3693-7771-9cd1-b8f57e304310
* Version Independent ID: 5ba25ca7-32ac-2d28-cc69-e6bf53dede66
* Content: [What's new in Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/whats-new-in-microsoft-defender-atp)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/whats-new-in-microsoft-defender-atp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/whats-new-in-microsoft-defender-atp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by denisebmsft** [comment]
Hello @bledMS82. Thank you so much for telling us about the broken link. It's fixed, and you'll see the update live later today. We appreciate your help in keeping our content high quality.
