### ISSUE TITLE
IP only supports individual IPs, not a range or CIDR

### ISSUE THREAD

**Issue by douglasos** [MicrosoftDocs/windows-itpro-docs#8152]
Please add to the documentation that IP ranges or CIDR is not supported, only individual IPs can be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8f1e347-cbff-c68e-1ac1-7b18417ad792
* Version Independent ID: 385679a4-1bde-c920-5c8c-76cb4d76fd30
* Content: [Create indicators for IPs and URLs/domains - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/indicator-ip-domain)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/indicator-ip-domain.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/indicator-ip-domain.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by MaratMussabekov** [comment]
Hello, checked and confirmed

**Comment by e0i** [comment]
With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
