### ISSUE TITLE
Registry Settings for Server OS's (2016+)

### ISSUE THREAD

**Issue by dylanlawton** [MicrosoftDocs/windows-itpro-docs#8154]
Hi - do these registry settings apply to server OS's? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184809a-63ff-ecc2-ab67-9c9f4df900f8
* Version Independent ID: ac25ee6c-4c57-58b3-1313-e4a53f53c5a1
* Content: [Manage device restarts after updates (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-restart)
* Content Source: [windows/deployment/update/waas-restart.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-restart.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@eross-msft , @arcarley do you happen to know?

**Comment by arcarley** [comment]
Servers today only receive quality updates, but the policies on that page pertaining to deploying quality updates or to update experience apply to Server OS's. Note anything available in 1607 and above is available to Server 2016 and above and similarly anything available in 1809 and above is available to Server 2019 and above. This is additionally noted in the GP templates and the CSP documentation, Please let me know if you have any further questions.

**Comment by dylanlawton** [comment]
Thanks for the quick responses everyone - the specific registry entry i'm interested in is to prevent reboots happening outside of the active hours, referenced as "SetActiveHours" which intend to set to 0 on 2016/2019 servers. I will try in my lab to see if it does prevent reboots happening outside of the active hours. Dylan.
