### ISSUE TITLE
UserRights/DenyLocalLogOn this setting has incorrect Group Policy matching

### ISSUE THREAD

**Issue by yogeshasalkar** [MicrosoftDocs/windows-itpro-docs#8156]
UserRights/DenyLocalLogOn this setting has incorrect Group Policy mapping. This setting should map to 'Deny log on locally' not 'Deny log on as a service'. Please confirm and update.

Thanks,
Yogesh Asalkar,
Compliance Research Analyst | Qualys.Inc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b62d452-1910-d962-0ccc-9ac3f8135f15
* Version Independent ID: 5a4e6f0c-bcd4-8d8b-93f7-5bda7135b931
* Content: [Policy CSP - UserRights - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-userrights)
* Content Source: [windows/client-management/mdm/policy-csp-userrights.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-userrights.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@yogeshasalkar . Just now i checked on windows 10 v2004 with updated admx templates 

in GPO, there are two policies namely

1. Deny log on as a service
2. Deny log on locally

i don't about CSP  settings, let  article author will reply.

**Comment by ManikaDhiman** [comment]
Per the DDF, the doc correctly displays the mapping of the UserRights/DenyLocalLogOn policy setting to the GP setting. The description of the UserRights/DenyLocalLogOn policy setting also matches with that of the "Deny log on as a service" GP setting. Closing this issue as no doc update is needed. Thanks!

**Comment by yogeshasalkar** [comment]
Reopen this issue again.

As per my initial comment, 
Correct equivalent GP for UserRights/DenyLocalLogOn setting is 'Deny log on locally' not 'Deny log on as a service'.

Following is my configuration and analysis.


I have configured UserRights/DenyLocalLogOn to DESKTOP-ASPE38Q\xya
![intune config](https://user-images.githubusercontent.com/50020908/102220255-952c6380-3f06-11eb-9465-2f359e9327a9.JPG)

![Succeeded](https://user-images.githubusercontent.com/50020908/102220287-9fe6f880-3f06-11eb-88d8-656b08afce8f.JPG)


Now on the actual system 'Deny log on locally' setting gets reflected.
![actual result on target](https://user-images.githubusercontent.com/50020908/102220582-066c1680-3f07-11eb-8356-a2f805db2f41.JPG)


As per the documentation Deny log on as a service should get reflected but in reality 'Deny log on locally' is getting affected.

Please take this issue on priority.

Thanks

**Comment by yogeshasalkar** [comment]
@ManikaDhiman @e0i
