### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/windows-itpro-docs#817]
Paragraph starting with "Windows Hello for Business", bullet point starts with "Is is easier". Should be "It is easier".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c880203c-6a5b-28e7-c74d-152890baa955
* Version Independent ID: 59c9eb13-dd44-358a-130d-ca1e020573ba
* Content: [What's new in Windows 10, version 1803](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1803)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1803.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1803.md)
* Service: **unspecified**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by ChicagoJay** [comment]
Under Configuration, on this page, it says "Co-management
Intune and System Center Configuration Manager policies have been added to enable hyrid Azure AD-joined authentication. "  It should be "... hybrid Azure AD-joined authentication."

**Comment by asrarhusain14** [comment]
<a href="https://hindi.thetecnology.com/shayari-sangrah/">Windows Hello for Business</a>

**Comment by mypil** [comment]
@officedocsbot assign @mypil
