### ISSUE TITLE
No joy

### ISSUE THREAD

**Issue by hafizullahchishti** [MicrosoftDocs/windows-itpro-docs#8171]
First of all, all these steps could have been rolled into a batch file.

Second: It did not work. I'm still getting the error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
Could we have some details about your scenario and OS versions?

**Comment by hafizullahchishti** [comment]
Brand-new installation of Win7/64 on a freshly-reformatted 500Gb disk.
10-year-old Asus mainboard hosting an AMD Phenom II processor that had no
difficulty with Win10/64.

The board has only 4Gb of RAM, so I opted for Win7 as being a little-less
RAM-hungry than Win10.

Since my comment, I re-installed Win7 and get the same 80244019 error
manually running Windows Update - before any application installs or
customizations.  Is there any other information that would be helpful?
Thank you.

 

  _____

**Comment by illfated** [comment]
Thank you for your details. I am uncertain about the use of Windows 7, since I don't know if your license is personal or business. Windows 7 is not supported anymore, at least not for personal use (https://support.microsoft.com/en-us/help/4057281/windows-7-support-ended-on-january-14-2020).

**Comment by hafizullahchishti** [comment]
Yes, it is for personal use. But the problem still should not be occurring.
I've installed Win7 many times on different systems and this is the first
time I've seen this.

 

  _____

**Comment by illfated** [comment]
In principle, I agree with you when it comes to errors that should be (and might have been) fixed while Windows 7 was still supported.

Based on the current situation, I recommend using the various forums to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Just to make sure, I hope you are aware that this repository is used to report issues in the linked documentation.
Even if some users have received help with their questions, it varies a lot if the technical writers can provide any assistance.
The MS Docs team members are also quite occupied with following up requests to improve or update the documentation.

Your point about the possibility of changing the listed procedures is still valid, though.

General disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

**Comment by hafizullahchishti** [comment]
I've been banging my head on this for days. I've searched the forums, found
a lot of voodoo solutions, and tried the suggestions that seemed reasonable.
I'm going to try a wipe/re-install one more time, and maybe try XP. This
system is to be a gift to someone who is shut-in due to covid and doesn't
have a herfy-enough system to Zoom without jankiness.

 

There might be a small issue with rolling the commands into a single
batchfile, such as someone's security app flagging it as dangerous, but that
could be worked-around by giving it a .txt extension and instructions to
rename it as .bat after download. Anyone who can follow those instructions
at the CLI could certainly do a simple rename. 

 

  _____

**Comment by illfated** [comment]
Fair enough. Your working goal is commendable.

I wish you good luck, although patience may be needed in this repository.

**Comment by hafizullahchishti** [comment]
I wiped the drive partitions & re-established them, then re-installed Win7.
Same error. However, I was able to (finally!) find and download Service Pack
1, and an update package "KB3020369-x64" that seem to have installed
cleanly. Woody Leonhard also has some observations, which I will look into. 

Thanks for your time.

   

Hafizullah
@}->-`-,---

**Comment by illfated** [comment]
Oh. Right. Fair point about Service Pack 1. SP1 was a requirement for quite a long time in the Windows 7 support period. I guess it must have been at least 5 years since I converted to Windows 10, so I had almost forgotten about that bit of support trivia. Anyway, this repository is not meant for support inquiries, so I will ask for this ticket to be closed.

**Comment by illfated** [comment]
#please-close
