### ISSUE TITLE
Apply this to a USB NAS drive?

### ISSUE THREAD

**Issue by azhermit** [MicrosoftDocs/windows-itpro-docs#8179]
I am trying to safely remove a USB network attached drive plugged into my router. Trying to follow the steps above does not work because even though I've mapped the windows to the drive and it appears in My PC right clicking on it does not give me the option of stopping it like a flash drive. I don't want to just yank it out. Suggestions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 844ba8b2-4c73-698b-80f8-68bb2d272d4c
* Version Independent ID: 05847067-81fe-17ea-5e61-2346c90c5fe2
* Content: [Windows 10 default media removal policy - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/change-default-removal-policy-external-storage-media)
* Content Source: [windows/client-management/change-default-removal-policy-external-storage-media.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/change-default-removal-policy-external-storage-media.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by Teresa-Motiv** [comment]
I'm not sure that these instructions apply in your situation; they're for the case where a USB drive plugs directly into the computer. If the NAS is connected to the router instead of the computer, I think the computer treats it as another device on the network and not as a drive, so you won't see the "Safely remove" option.

I have a NAS that's connected to my router by Ethernet cable, and there's an app on my computer that I can use to send it shutdown or reboot commands. But my computer treats the NAS as another computer on the network, not a drive.

**Comment by azhermit** [comment]
Thank you for sharing. I hadn't thought of connecting via Ethernet instead
of USB and sharing as any other computer on the network. Not sure whether
there's a SATA to Ethernet adapter, but I know there's a USB to Ethernet
adapter. So it may be possible.
May I ask what the app is on your computer that can send a shutdown or
reboot command to your Ethernet connected NAS? I am familiar only with
Windows' "safely remove" and as you say, it can't see the NAS.

**Comment by Teresa-Motiv** [comment]
The app is from the NAS manufacturer, and came with the NAS. 

If you've successfully connected the device to the router by USB, and it's available on the network, you probably don't need to use Ethernet. In any case, the NAS manufacturer should provide information about the best way to connect and operate your NAS.

**Comment by e0i** [comment]
It seems that your question has been answered by the article author.

Please note that the issues section of this repository is intended for documentation feedback.

Should you have any further issues similar to this one, please consider opening a product support ticket here:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Feel free to re-open this issue if you feel that there are further suggestions to improve the documentation itself.

Thank you for providing feedback.
