### ISSUE TITLE
Windows Autopilot - new features missing

### ISSUE THREAD

**Issue by carvakas** [MicrosoftDocs/windows-itpro-docs#818]
Hi, I just updated my demo Surface Pro 4 to 1803 and did a reset, however I did not see many of the new UI when going through and AutoPilot installation, in fact it 'lost' my custom branding?

When will I see the new features (as in the video) appear?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c880203c-6a5b-28e7-c74d-152890baa955
* Version Independent ID: 59c9eb13-dd44-358a-130d-ca1e020573ba
* Content: [What's new in Windows 10, version 1803](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1803)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1803.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1803.md)
* Service: **unspecified**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by DieterHelmutGreiner** [comment]
I have installed Windows 10 Pro 1803 (MSDN ISO) from scratch.
I also don‘t see the new locked provisioning UI however the custom branding is still displayed.

**Comment by greg-lindsay** [comment]
My apologies, apparently there was a delay getting this page into the UI, but it should be available very soon.

**Comment by thbch** [comment]
What means "very soon" in this case? End of May? We didn't find any new settings in Intune, so how are these steps configured?

**Comment by DaniHalfin** [comment]
@mtniehaus might be able to comment here.

**Comment by R2D2components** [comment]
Remove and discard any and all changes you have made to this pc or device. This request comes from the owner of said device and didn’t
Authorize such change please contact me as soon as you can thank you for your time 

Jason Robertson

**Comment by mypil** [comment]
@greg-lindsay @DaniHalfin @mtniehaus - Do you have any updates on this issue? Thank you.

**Comment by DaniHalfin** [comment]
I believe Windows Autopilot features have been updated independently, in the Windows Autopilot content. 
Don't know that all of it was coupled with the OS release. 
@greg-lindsay might be able to comment further.

**Comment by mtniehaus** [comment]
This is a very old thread.  All 1809 and previous features are documented, both in the Windows and Intune docs.  If there are any specific items that someone thinks are missing, great, but right now I don't see anything actionable in this issue.

**Comment by mypil** [comment]
@officedocsbot close
