### ISSUE TITLE
Clarification on the Connect app deprecation

### ISSUE THREAD

**Issue by miguedevel** [MicrosoftDocs/windows-itpro-docs#8184]
[Enter feedback here]

In the section where the article states that the Connect app is being changed to an optional feature, the document links to a MS Docs article where the feature to connect a computer to a Miracast display is explained. But, in fact, what the Connect app does is to allow a PC to be the receiver of a Miracast stream, which is the opposite of what the linked article explains. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215fea14-a9f3-6ed1-8aa3-8cbb4cbfc398
* Version Independent ID: ea54caae-1d90-fe54-217d-c43221cfce09
* Content: [Windows 10 - Features that have been removed - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-removed-features)
* Content Source: [windows/deployment/planning/windows-10-removed-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/planning/windows-10-removed-features.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
I agree, this is confusing. The article talks about sending a stream not receiving one.  I'm removing the link. This change should publish this afternoon. Thanks for catching this.
