### ISSUE TITLE
Licensing Microsoft Defender ATP 

### ISSUE THREAD

**Issue by Peterf992** [MicrosoftDocs/windows-itpro-docs#8185]
Hi all,

I've got a question about the next licensing situation for Defender ATP:

All users have a seperate account, but are using a pool of devices. Only one device at the time, but everytime they start a new shift they will grab one of the available devices. When licensing MD ATP you're only allowed to use 5 different concurrent devices per licensed user. Does this mean that they when they grab the 6th device they are not able to login because the account is already registered on 5 different devices? Or is the device deleted from the registered devices when they logout of the device and wont there be any issue when they login to the 6th different account?

"Eligible Licensed Users may use Microsoft Defender Advanced Threat Protection on up to **five concurrent devices**. Microsoft Defender Advanced Threat Protection is also available for purchase from a Cloud Solution Provider (CSP). When purchased via a CSP, it does not require Microsoft Volume Licensing offers listed." 
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements

Thanks,
Peter

**Comment by joinimran** [comment]
Hello @Peterf992 - Thank you for your query. I would suggest you contact your Microsoft Accounts Manager to better help you with your query. 

Thanks
Imran.
