### ISSUE TITLE
use of Global Administrator role is not needed

### ISSUE THREAD

**Issue by MarzelLaning42** [MicrosoftDocs/windows-itpro-docs#8186]
Hi,

"The user who activates the setting must have permissions to create an app in Azure Active Directory (AAD). This is typically someone with a Global administrator role."

Please rephrase the sentence because it makes the reader think Azure AD Global Admin role is needed, where as the actual role is Security Administrator + Cloud Application Administrator. I think Microsoft documentation should be written with a least access privilege perspective.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ea5131f-6f6d-0520-56ac-5f8995c3e388
* Version Independent ID: 08b14dd1-05f9-4436-a343-ab39781c1957
* Content: [Enable SIEM integration in Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/enable-siem-integration)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/enable-siem-integration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/enable-siem-integration.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by VLG17** [comment]
@MarzelLaning42 According to [this article](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/add-application-portal) the required permission to create an app in Azure Active Directory (AAD) is one of the following roles: Global Administrator, Cloud Application Administrator, Application Administrator, or owner of the service principal.

I'll create a PR to include this.

**Comment by MarzelLaning42** [comment]
Hi. Whilst the roles you mention are correct. The context is for SIEM connectors where one also needs Security Administrator.
"Prerequisites:
The user who activates the setting must have permissions to create an app in Azure Active Directory (AAD). This is typically someone with a Global administrator role."

"Prerequisites:
The user who activates the setting must have permissions to create an app in Azure Active Directory (AAD) in addition to Microsoft Defender ATP administrator role."

**Comment by e0i** [comment]
@MarzelLaning42 

With the help of your feedback, the content has been updated with relevant changes accordingly with the PR #8325. Thanks.
