### ISSUE TITLE
Correcting event name typo

### ISSUE THREAD

**Issue by zeno-mcdohl** [MicrosoftDocs/windows-itpro-docs#8187]
Should "TCM and TCM-WMI event sources" not be "TPM and TPM-WMI event sources"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd33d92-681d-90ff-28bd-95b52306b677
* Version Independent ID: 99495e6f-0d7b-bd5f-e003-962d3a4d7b15
* Content: [Guidelines for troubleshooting BitLocker - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/troubleshoot-bitlocker)
* Content Source: [windows/security/information-protection/bitlocker/troubleshoot-bitlocker.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/troubleshoot-bitlocker.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by illfated** [comment]
Good point. Well spotted. See PR #8197 for the correction.
