### ISSUE TITLE
Domain Central Store paths table is rendering as raw Markdown/HTML table

### ISSUE THREAD

**Issue by gdukevt** [MicrosoftDocs/windows-itpro-docs#819]
The Domain Central Store paths table is rendering as raw Markdown/HTML table. See attached screenshot.

![30-16-51-56-microsoft edge](https://user-images.githubusercontent.com/36242940/39450120-3b4df3e6-4c98-11e8-9ee2-f71756a2da6c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 758d5448-7062-2519-a47b-7763a595471e
* Version Independent ID: 4e966ec3-b088-604d-a8c5-15e89a398ded
* Content: [How to Download and Deploy MDOP Group Policy (.admx) Templates](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/solutions/how-to-download-and-deploy-mdop-group-policy--admx--templates)
* Content Source: [mdop/solutions/how-to-download-and-deploy-mdop-group-policy--admx--templates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/solutions/how-to-download-and-deploy-mdop-group-policy--admx--templates.md)
* Service: **unspecified**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by lizap** [comment]
Thanks for raising this issue - we've updated the article so the table is formatted correctly. Thank you!
