### ISSUE TITLE
Multiple LogonCommand example and Debug information missing.

### ISSUE THREAD

**Issue by hasan-hasanov** [MicrosoftDocs/windows-itpro-docs#8191]
I read the documentation but it will be very beneficial to add example for LogonCommand that has more than 1 script execution inside. Maybe I am doing it wrong but I did not managed to execute 2 scripts with any LogonCommand variation. Having an example would certainly help clarify things.

Also there is no information on where can I find the logs of these commands (if there are any). If something fails during command execution there is no way (nor that I've found) to get some visibility of the problems.

It will be really beneficial if you specify if these scripts are run in parallel or sequential.

One last thing that I have noticed is that these commands currently does not run as Administrator. I have to ByPass every script that I have mapped inside of Sandbox.
For example if I want to execute test.ps1 script which is mapped inside of Windows Sandbox I have to first execute:

`powershell.exe -ExecutionPolicy Bypass -File C:\Users\WDAGUtilityAccount\Desktop\Sandbox\test.ps1` 

command to get the permissions which is not documented or I am doing it wrong again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2efc9d32-0f98-0804-78a4-4caccdfac010
* Version Independent ID: 797bb0d3-bade-98f6-fe85-508764571f37
* Content: [Windows Sandbox configuration - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by hasan-hasanov** [comment]
I just wanted to add that after an update of Windows sandbox the scripts are ran in hidden windows. I do not think that there is any way to configure this. 

Could you guys add some information about that as well?

What I mean is that every command window that is spawned from the logon command is hidden.

**Comment by VLG17** [comment]
@hasan-hasanov You can find [in this article](https://techcommunity.microsoft.com/t5/windows-kernel-internals/windows-sandbox-config-files/ba-p/354902) 2 examples. Hope it helps.

Regarding your question, it's stated in the article you linked that only one command can be invoked, not multiple.

> Logon command: Specifies **a single command** that will be invoked automatically after the sandbox logs on.

I recommend [involving support](https://support.microsoft.com/en-my/contactus/) in order for a support engineer to look at the code you are running inside the sandbox and answer your technical questions. If the conclusion is that we need to add something to the article, we will do that.
