### ISSUE TITLE
Send file samples configuration not present in ConfigMgr

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#8192]
Hello, 
It appears that the configuration settings for:

- Send safe samples automatically
- Send all samples automatically

is not present in the ConfigMgr endpoint protection policy, would be great if this  could be added, so that we don't end up using a mix of configuration tools i.e. GPO AND ConfigMgr.  

 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f8ccc01-1b04-e443-ef75-6ffe6c866dd5
* Version Independent ID: fa2eaa0f-db04-785a-3894-8244947b9cd5
* Content: [Enable cloud-delivered protection in Microsoft Defender Antivirus - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/enable-cloud-protection-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/enable-cloud-protection-microsoft-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by jenujose** [comment]
@alexverboon I am tackling a similar issue at a client. My assumption was that the "Enable auto sample file submission to help Microsoft determine whether certain detected items are Malicious" under AntiMalware Policy --> Advanced was the equivalent for this setting. But you are right, there's no option for "Send all samples automatically" in CM which results in users being prompted for Sample Submission requests.

**Comment by VLG17** [comment]
@alexverboon I recommend using the [dedicated UserVoice for Configuration Manager](https://configurationmanager.uservoice.com/forums/300492-ideas) to submit this feedback and get the option added to CM.

As soon as it's added we can update the article to reflect the change.
