### ISSUE TITLE
two links are broken, one link is not related 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#8193]
The following links are broken:
1. **Protecting the pre-OS environment with UEFI**
2. **Microsoft System Center 2012 Endpoint Protection**

Below link is  not related
1. **Windows 10 Enterprise Evaluation**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c795c8ef-7caf-b8a7-4118-b00b1899eef8
* Version Independent ID: cd85b6b4-d160-0c44-15ea-4b7c02fbe0eb
* Content: [Secure the Windows 10 boot process - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/secure-the-windows-10-boot-process)
* Content Source: [windows/security/information-protection/secure-the-windows-10-boot-process.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/secure-the-windows-10-boot-process.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Fixed via #8195
