### ISSUE TITLE
No such thing as Everyone group

### ISSUE THREAD

**Issue by dloder0** [MicrosoftDocs/windows-itpro-docs#8194]
Everyone is a well-know SID, but is not a group. Not sure what is trying to be conveyed here.  Something with Pre-Windows 2000 Compatible Access group perhaps?  Mentions it is possible to change Everyone but does not link to an explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 486e8a12-8230-6ae2-264f-73c76b266682
* Version Independent ID: 2f47f94f-b416-beac-c75d-8908e4000e66
* Content: [Special Identities (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/special-identities)
* Content Source: [windows/security/identity-protection/access-control/special-identities.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/access-control/special-identities.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
"Everyone" is a special identity that behaves like a group (and is presented as a group container) in Windows 10, Windows Server 2016 and earlier. One of its uses is backwards compatibility, all the way to before Windows 2000. Some of its irregularity is that you cannot view its access rights or members.

- https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/bb727067(v=technet.10)#appendix-a-built-in-predefined-and-special-groups
- https://docs.microsoft.com/windows/security/identity-protection/access-control/active-directory-security-groups#prewindows2000-compatible-access
- https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn617202(v=ws.11)#everyone
- https://support.microsoft.com/help/243330/well-known-security-identifiers-in-windows-operating-systems

**Comment by MaratMussabekov** [comment]
Hello,
**Everyone is a well-know SID, but is not a group.** - special identities are usually referred as groups in Microsoft docs
**Mentions it is possible to change Everyone but does not link to an explanation.** - good point, I created a PR to add more details.

Thank you
