### ISSUE TITLE
Computer Account Objects Don't Expire

### ISSUE THREAD

**Issue by jricha34** [MicrosoftDocs/windows-itpro-docs#820]
Computer account objects do not expire so this bit " If the machine's account has expired, it will no longer be able to authenticate with the domain." is wrong. This bit is probably also wrong "Devices that cannot authenticate with the domain must be removed from the domain and rejoined to it." but it has more variables involved and saying you have to rejoin is the simplest shortest way to tell people how to fix it. 

This policy allows you to specify for when the CLIENT machine will decide to submit a password change. It can also be overridden with a reg pop. See https://support.microsoft.com/en-us/help/154501/how-to-disable-automatic-machine-account-password-changes  If computer passwords expired, you would need to update a Domain Component as well as a member component to avoid the issues you are talking about. And if the accounts did expire it would make this statement from the article wrong too " Increasing this interval significantly, or setting it to 0 so that the device no longer change their passwords, gives a malicious user more time to undertake a brute-force password-guessing attack against one of the machine accounts."

So repeat after me "Computer Accounts DO NOT EXPIRE"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee4cd61-060d-9df3-ab84-9a80883d7b75
* Version Independent ID: aba04203-4843-b412-ea79-44fd07e93023
* Content: [Domain member Maximum machine account password age (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/domain-member-maximum-machine-account-password-age#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/domain-member-maximum-machine-account-password-age.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/domain-member-maximum-machine-account-password-age.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@jricha34 Hey Joe, thanks for the explanation! I revised the text accordingly. Is it more clear now? I didn't add the reg key, but let us know if we should add that or a link to the KB.

**Comment by jricha34** [comment]
Hey Justin!

If I am looking at the right thing, no, it still isn't right. I still see "If the machine's password has expired, it will no longer be able to authenticate with the domain.". Machine account passwords simply do not expire; domains do not treat them like user accounts. You can set computers to NEVER change their password in AD and they will work just fine.

You also may want to mention that in NT4 timeframe the passwords were changed every 7 days, this was too often in large orgs as it created a lot of unnecessary replication churn so do not lower this value to low or it couldn't impact your domain controllers in larger environments with lots of computers or a lot of slow links to replicate across.

Oh, I just found a blog post for you to help...

https://blogs.technet.microsoft.com/askds/2009/02/15/machine-account-password-process-2/

   joe
Machine Account Password Process | Ask the Directory ...<https://blogs.technet.microsoft.com/askds/2009/02/15/machine-account-password-process-2/>
Hi, this is Manish Singh from the Directory Services team and I am going to talk about the machine account password process. Ever wondered what goes on with your machine account in Active Directory? Here is a brief set of question and answers to clear things up. The machine account password change ...
blogs.technet.microsoft.com




________________________________

**Comment by Justinha** [comment]
Hey Joe, sorry for delay on this. I revised the Best Practices section again. Let us know if you see any inaccuracies.
