### ISSUE TITLE
.NET | Protecting your code from reverse-engineers makes your application a virus?

### ISSUE THREAD

**Issue by itzplayz0001** [MicrosoftDocs/windows-itpro-docs#8201]
Hello, 
I have used an obfuscator to secure my application, but windows defender identifies it as a virus! 
How will we developers protect our source codes? It clearly states this "
Obfuscator: A type of malware that hides its code and purpose, making it more difficult for security software to detect or remove.
". Then how do we fix this issue? 

`MY CODE HAS FUNCTIONS SUCH AS IF FILE EXISTS AND MORE LIKE THAT...`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b16da7d1-e552-e274-9406-5390252b0c04
* Version Independent ID: d0c9b8a8-4fba-4ea8-cfdd-6ae6d67a2e19
* Content: [How Microsoft identifies malware and potentially unwanted applications - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/criteria)
* Content Source: [windows/security/threat-protection/intelligence/criteria.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/criteria.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by RAJU2529** [comment]
this question will be answered  by .net application developers

**Comment by itzplayz0001** [comment]
bruh.... I am a .NET developer and am working hard to fix this

**Comment by RAJU2529** [comment]
@itzplayz0001 . Sorry i am not .net developer, so you should use all your knowledge from the basic to hard level, try to fix.

**Comment by itzplayz0001** [comment]
@RAJU2529 Bro do you have any idea about what you're saying? This is a problem to do with protectors not coding.... -_-

**Comment by levinec** [comment]
Hi @itzplayz0001, thank you for your questions, but this GitHub issues forum is intended for documentation fixes.

If you believe that your application or program has been incorrectly detected by Microsoft security software, submit the relevant files for analysis. You can then dispute the detection if necessary. 

- [File submission portal ](https://www.microsoft.com/en-us/wdsi/filesubmission/)
- [Submit files for analysis FAQ](https://docs.microsoft.com/windows/security/threat-protection/intelligence/submission-guide)
- [How do I dispute the detection of my program?](https://docs.microsoft.com/windows/security/threat-protection/intelligence/submission-guide#how-do-i-dispute-the-detection-of-my-program)
