### ISSUE TITLE
Server version 

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#8205]
[Enter feedback here]

How come Server 2019 is not listed? Is there an equivalent product for that OS?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de03924b-fea3-8d37-b31d-e8b5e63ca196
* Version Independent ID: 6acc49c3-b3b9-f847-a056-195da9082c48
* Content: [Windows Defender Firewall with Advanced Security (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/windows-firewall-with-advanced-security)
* Content Source: [windows/security/threat-protection/windows-firewall/windows-firewall-with-advanced-security.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/windows-firewall-with-advanced-security.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
Based on the video from Robert McMillen on 22 July 2020, https://www.youtube.com/watch?v=YQcklFuWrcw , it is still named "Windows Defender Firewall with Advanced Security". This indicates that the page should mention Windows Server 2019 as well, under "Applies to", unless a different procedure is required to run the described procedure.

**Comment by e0i** [comment]
@DeanGross  The missing version detail has now been listed in the documentation via the merged PR #8482. Thank you for providing feedback.
