### ISSUE TITLE
Multi App Kiosk Assigned Access configuration schema links

### ISSUE THREAD

**Issue by jjchaos** [MicrosoftDocs/windows-itpro-docs#8209]
The documentation at https://docs.microsoft.com/en-us/windows/configuration/kiosk-xml shows several examples for XML files. However the schema links in the configurations appear to be outdated. We are unable to successfully provision packages on Windows 10 1909. 

For example:
xmlns="http://schemas.microsoft.com/AssignedAccess/2017/config"
xmlns:v2="http://schemas.microsoft.com/AssignedAccess/201810/config"
xmlns:v3="http://schemas.microsoft.com/AssignedAccess/2020/config"

Can someone please provide an updated example XML file that will work with 1909?

**Comment by jjchaos** [comment]
Any update?

**Comment by e0i** [comment]
Hello, This issue has been assigned to an independent contributor and in progress. Thank you for following up.

**Comment by joinimran** [comment]
@Dansimp - Can you please share your input on this. Looks like the URLs mentioned are not accessible. Need your input to proceed further. 

Thanks
Imran.

**Comment by joinimran** [comment]
@denisebmsft - Need your help with this issue. Can you please confirm what changes are required in this document? I can create PR for the same.

Thanks
Imran.

**Comment by jjchaos** [comment]
Can someone please let me know how to get this working on Windows 10 1904? This issue has been open for over 4 months and we are still unable to get multi app kiosk mode working per the instructions.

**Comment by joinimran** [comment]
@jjchaos - I was waiting for the author's input but I would suggest you open a support case with Microsoft to expedite this process. 

@e0i - Can you please guide @jjchaos on how to open up a support case with Microsoft to proceed further.

Thanks.
Imran.

**Comment by joinimran** [comment]
Hello @jjchaos - Can you please confirm what error you are getting while using the sample XMLs? The sample XMLs looks good to me and the schema URLs are not only used here but in many other CSPs and they are working as expected.

Thanks.
Imran.

**Comment by jjchaos** [comment]
Imran - the provisioning package simply fails to apply. We are trying this on Win 10 1904. Can you provide an known working XML file for multi-app kiosk mode for this version? We have tried every sample XML we've come across and all fail, even across multiple computers / models.

**Comment by e0i** [comment]
@jjchaos 

Based on the contributors assessment, it seems that XML files are in order. 

It looks like this is a support question that can best be answered via relevant [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channels. 

Please consider checking with [Microsoft Community](https://answers.microsoft.com/en-us/windows/forum/windows_10) or [contacting support](https://support.microsoft.com/contactus) for your problem; The issues section of this repository is for content fixes in documentation.

If you feel that the associated article also needs to be updated for any reason feel free to re-open this issue or [contribute with a pull request](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/CONTRIBUTING.md).

Thank you.
