### ISSUE TITLE
Will this feature support blocking individual URLs or customising categories?

### ISSUE THREAD

**Issue by mtwelve** [MicrosoftDocs/windows-itpro-docs#8213]
Will this feature support blocking individual URLs or customising categories?

Defender ATP doesn't seem to have a UserVoice site for me to browse or raise this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d1d825-ab12-2f37-b692-5266487ef16f
* Version Independent ID: fef750ac-311b-28b4-1661-16385997815b
* Content: [Web content filtering - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/web-content-filtering)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/web-content-filtering.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/web-content-filtering.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Hi @mtwelve. Thank you for your question. Currently, web content filtering does not support blocking individual URLs or customizing categories. This feature is still in preview, and your questions have been documented. 

To set up a custom blocked URLs list, I suggest looking into Office 365 ATP Safe Links: https://docs.microsoft.com/microsoft-365/security/office-365-security/set-up-a-custom-blocked-urls-list-atp

If you have other product-related questions, please use the Feedback Hub: https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app
