### ISSUE TITLE
Wrong information about Account Operators

### ISSUE THREAD

**Issue by alex-456** [MicrosoftDocs/windows-itpro-docs#8214]
I think the following statement is a contradiction. 

"Members of the Account Operators group cannot manage the Administrator user account, **the user accounts of** administrators, or the Administrators, **Server Operators, Account Operators**, Backup Operators, or Print Operators groups.

"By default, this built-in group has no members, and it can create and manage users and groups in the domain, including its **own membership and that of the Server Operators group**."

In my experience, the membership of the two groups Account Operators and Server Operators cannot be edited.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 44e911d3-219e-19b8-4870-07514d9a94a1
* Version Independent ID: 960a7388-560b-90eb-e0ff-d8d2bb6f9a7a
* Content: [Active Directory-Sicherheitsgruppen (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/de-de/windows/security/identity-protection/access-control/active-directory-security-groups)
* Content Source: [windows/security/identity-protection/access-control/active-directory-security-groups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/access-control/active-directory-security-groups.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@alex-456 One can edit the "Members" tab of Account and Server Operators, but not the "Member of" tab.

My understanding is that the second sentence talks about the "Members" tab which can be edited. 

![image](https://user-images.githubusercontent.com/41186174/94410501-1a15a580-0180-11eb-8ea4-b79cf2d5d5dc.png)

![image](https://user-images.githubusercontent.com/41186174/94410545-27329480-0180-11eb-893f-b1f09c31aadf.png)
