### ISSUE TITLE
Instructions no longer match to endpoint.microsoft.com

### ISSUE THREAD

**Issue by jwojan** [MicrosoftDocs/windows-itpro-docs#8216]
Now that Intune has been moved to endpoint.microsoft.com, the instructions for creating these USB policies in Intune no longer map to the correct locations/UI in this new portal. As a result, a person cannot follow along and create these USB policies to achieve the goal in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f395d314-f7cd-6d89-b392-b0af0e527d36
* Version Independent ID: dffc4bff-3403-9b7a-3ccb-69f92ece2672
* Content: [How to control USB devices and other removable media using Intune (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/device-control/control-usb-devices-using-intune#prevent-installation-and-usage-of-usb-drives-and-other-peripherals)
* Content Source: [windows/security/threat-protection/device-control/control-usb-devices-using-intune.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/device-control/control-usb-devices-using-intune.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Closing via #8491.
