### ISSUE TITLE
Possible incorrect failure code

### ISSUE THREAD

**Issue by miwent** [MicrosoftDocs/windows-itpro-docs#8219]
The descriptive text for failure code  0XC000006E is "Unknown user name or bad password." but from the [ntstatus.h](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55) page 0xC000006E is defined as "STATUS_ACCOUNT_RESTRICTION", which appears to be the correct description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80307c25-b809-e9b8-bab2-d37d3de7e920
* Version Independent ID: 24c32be1-2fc3-f22f-7e6c-da4049bf8458
* Content: [4625(F) An account failed to log on. (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4625)
* Content Source: [windows/security/threat-protection/auditing/event-4625.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4625.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@miwent 

With the help of your feedback, the content has been updated with relevant changes accordingly via above PR. Thanks.
