### ISSUE TITLE
CA server version requirement for AAD join device cert trust model

### ISSUE THREAD

**Issue by SeanXuMSFT** [MicrosoftDocs/windows-itpro-docs#8222]
[Enter feedback here]
in this document, it says we need windows 2012 R2 CA, however, for other deployment model such as cert trust for hybrid AAD join device, they only required windows 2012 CA.

please kindly confirm why only this deployment model requires 2012 R2 CA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f709fd4-0b5d-b238-4060-222d550cd538
* Version Independent ID: fb3f29da-2236-c47d-6bea-8efbcec8d7d3
* Content: [Using Certificates for AADJ On-premises Single-sign On single sign-on - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by SeanXuMSFT** [comment]
hi @e0i , is there any update about this request?

**Comment by e0i** [comment]
Hello, @SeanXuMSFT The issue is being reviewed by an independent contributor for investigation.

**Comment by SeanXuMSFT** [comment]
hi @e0i ,may i know if there is any progess?

**Comment by e0i** [comment]
Hello, The issue is still in the backlog of an independent contributor. Thank you for your patience with the process.

**Comment by joinimran** [comment]
@mapalko - Can you please answer this query. if there is anything that needs to be added to the document, please feel free to let me know. I will create PR for the same. I couldn't find anything related to this.

Thanks 
Imran.

**Comment by illfated** [comment]
Looking forward to a comment from mapalko, just so I know if it is safe to start my own PR for the same document page. 
I have been itching to start a PR to clean up some incorrect MarkDown formatting in the document.

**Comment by illfated** [comment]
Very well, I managed to get the changes I wanted done to this document (in PR #8899), so a new PR can be opened in case this ticket requires a new document update.

**Comment by joinimran** [comment]
@mapalko - Can you please suggest any changes required in this document that can handle the customer concern?

@e0i - FYI & A Please.
