### ISSUE TITLE
No documentation about strange behaviour of Windows blocking HID Access to FIDO2 Devices

### ISSUE THREAD

**Issue by riedel** [MicrosoftDocs/windows-itpro-docs#8223]
The Windows Fido2 documentation is terrible compared to the original  FIDO2 documentation. Instead of providing access to a better API and compete on quality, there is enforcement to use this underdocumented API. Unfortunately the MS api does not seem to be a one to one translation.

At least it would be fair that microsoft explains that they block unelevated access to the CTAP API of the Hardware. 

Further Microsoft should provide a migration guide from CTAP to webauthn.h for developers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9884247-29d3-eacb-25cb-60c712fa561c
* Version Independent ID: 020c8ae8-dd46-4ef2-9e11-5aea3059f0ed
* Content: [WebAuthn APIs - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/webauthnapis)
* Content Source: [windows/security/identity-protection/hello-for-business/WebAuthnAPIs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/WebAuthnAPIs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @riedel Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
