### ISSUE TITLE
How to link searchbox to db.

### ISSUE THREAD

**Issue by asqararslonov2008** [MicrosoftDocs/windows-itpro-docs#8225]
I have a xampp and I create database in phpmyadmin.but I know me need to work with php in this code.

**Comment by denisebmsft** [comment]
Hello @asqararslonov2008 and thank you for posting your question here. Can you please tell us to which article(s) your question applies? This information will help us route the issue correctly. Thanks!

**Comment by e0i** [comment]
We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.

Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.

Thank you for providing feedback.
