### ISSUE TITLE
editing applocker rules

### ISSUE THREAD

**Issue by jackvdbuk** [MicrosoftDocs/windows-itpro-docs#8233]
Step 5 states to edit the GPO which has applocker present in it however it states this here:
Caution:  You should never edit an AppLocker rule collection while it is being enforced in Group Policy. Because AppLocker controls what files are allowed run, making changes to a live policy can create unexpected behavior. For info about testing policies, see Test and update an AppLocker policy.   Note:  If you are performing these steps by using Microsoft Advanced Group Policy Management (AGPM), check out the GPO before exporting the policy.  

https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/edit-an-applocker-policy

This conflicts the information provided on this page. please confirm if Applocker should be amended directly on the GPO or should be exported then re-imported into the GPO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 581707e7-4b0d-f6e0-93d9-e28b4f681d4b
* Version Independent ID: b4419a4e-c14e-9360-7bb9-43faa3ec447e
* Content: [Test and update an AppLocker policy (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/test-and-update-an-applocker-policy)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/applocker/test-and-update-an-applocker-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/applocker/test-and-update-an-applocker-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
Instead of using an application locker, we can use the Software Restriction Policy  directly in GPO

**Comment by joinimran** [comment]
Hello @jackvdbuk - Thank you for your query. Please note that the document https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/test-and-update-an-applocker-policy can only be used when you are planning to deploy the App locker policy for the 1st time. 

When you are editing or modify the policy, there are a few precautions that need to be taken care of. In the document https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/edit-an-applocker-policy it states the following 

You can edit an AppLocker policy by adding, changing, or removing rules. However, you cannot create a new version of the policy by importing additional rules. To modify an AppLocker policy that is in production, you should use Group Policy management software that allows you to version Group Policy Objects (GPOs). If you have created multiple AppLocker policies and need to merge them to create one AppLocker policy, you can either manually merge the policies or use the Windows PowerShell cmdlets for AppLocker. You cannot automatically merge policies by using the AppLocker snap-in. You must create one rule collection from two or more policies. The AppLocker policy is saved in XML format, and the exported policy can be edited with any text or XML editor. 

Thanks 
Imran.
