### ISSUE TITLE
Get-DeliveryOptimizationPerfSnap has a new option -PeerInfo

### ISSUE THREAD

**Issue by clamb123** [MicrosoftDocs/windows-itpro-docs#8239]
The doc says:
Starting in Windows 10, version 2004, Get-DeliveryOptimizationPerfSnap has a new option -PeerInfo which returns a real-time list of the connected peers.

No it doesn't! See attachment.

![PeerInfo](https://user-images.githubusercontent.com/66670497/92480384-ba5d5780-f1dc-11ea-8b28-8beaf06831aa.png)

(admin edit, fixing doc details for latest)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e39e363-99f3-a517-ef03-c4f177790551
* Version Independent ID: 6e39e363-99f3-a517-ef03-c4f177790551
* Content: [Set up Delivery Optimization - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/do/waas-delivery-optimization-setup)
* Content Source: [windows/deployment/do/waas-delivery-optimization-setup.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/do/waas-delivery-optimization-setup.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @cmknox
* Microsoft Alias: **carmenf**

**Comment by jaimeo** [comment]
@narkissit can you advise?

**Comment by RAJU2529** [comment]
I am  checking

**Comment by aczechowski** [comment]
At some point along the way this was fixed, a typo I think for the cmdlet name. The PeerInfo parameter is on the Get-DeliveryOptimizationStatus cmdlet, which is what's currently noted. Closing this issue.
