### ISSUE TITLE
Add 1709 and 1803 in the "New for <Windows Version>" section

### ISSUE THREAD

**Issue by tFable** [MicrosoftDocs/windows-itpro-docs#824]
Hello,

This page has not been updated to show changes to WCD in ADK 1709 and 1803. Does this mean there have been no changes to WCD since 1703?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc6a7f82-c972-6aea-f045-08fb57a99ae6
* Version Independent ID: 384fe96b-ace9-3e34-e5e9-24bb7409e0e8
* Content: [Provisioning packages (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-packages)
* Content Source: [windows/configuration/provisioning-packages/provisioning-packages.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/provisioning-packages/provisioning-packages.md)
* Service: **unspecified**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@tFable In 1709 and 1803, there were changes to the settings available in WCD, but not general changes to the tool itself. The reference content for the settings is current as of 1803: https://docs.microsoft.com/en-us/windows/configuration/wcd/wcd

**Comment by tFable** [comment]
@jdeckerms Thanks for the quick response!

I think it would be valuable to have a section that describes the changes in available settings for each new WCD version (e.g. settings removed and added with each new version) It would act as a quick way to assess whether the new version is relevant to our particular WCD scenarios.

Without that, we have to go through the entire set of available settings and see if there are any changes/removals for the existing ones or if any new ones were added.

Thanks!

**Comment by jdeckerms** [comment]
@tFable That's a good suggestion, thanks! I'll include a summary of setting changes in our next release.

**Comment by tFable** [comment]
Thank you @jdeckerms !
