### ISSUE TITLE
Remote host allows delegation of non-exportable credentials

### ISSUE THREAD

**Issue by andy2002a** [MicrosoftDocs/windows-itpro-docs#8241]
The guide currently says "Must allow delegation of non-exportable credentials", but it does not specify the GPO required to do so. 

Setting the GPO "Remote host allows delegation of non-exportable credentials" to "Enabled" should be added to the guide. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c826587d-2e65-083f-254d-75f188158f08
* Version Independent ID: 746596b5-c1df-9ea0-abcc-f6ff97874e40
* Content: [Protect Remote Desktop credentials with Windows Defender Remote Credential Guard (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/remote-credential-guard)
* Content Source: [windows/security/identity-protection/remote-credential-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/remote-credential-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@andy2002a . thanks for pointing out. I am checking

**Comment by RAJU2529** [comment]
@andy2002a . After checking on windows 10 v2004, i conformed, your assumption is correct.
