### ISSUE TITLE
404 error for Network Monitor download link

### ISSUE THREAD

**Issue by kuacci** [MicrosoftDocs/windows-itpro-docs#8242]
The link for Network Monitor download link returns 404 response like below:
![image](https://user-images.githubusercontent.com/5857515/92551987-1b933280-f292-11ea-89df-c7b229116d23.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8823127-9a9b-141c-6096-e8d40ff6e22c
* Version Independent ID: 02332337-0981-36af-424e-9378487dd4d8
* Content: [Collect data using Network Monitor - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-tcpip-netmon)
* Content Source: [windows/client-management/troubleshoot-tcpip-netmon.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/troubleshoot-tcpip-netmon.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@kuacci . Network monitor is  depreciated or retired from project.

**Comment by illfated** [comment]
Well, if Network Monitor is fully deprecated and the page is mostly about Network Monitor, the whole page should be retired (either removed completely from any links leading to the page, or demoted to the archives).

I am not entirely sure what the preferred method of removal is here, so I will wait for feedback from the MS Docs team members.

**Comment by kuacci** [comment]
Agree with @illfated , we should make an announcement or remove the link which link to a deprecated product. Based on my understanding, the 404 response not a good approach for people who reading Microsoft Docs.

**Comment by illfated** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=4865

![image](https://user-images.githubusercontent.com/38162891/93583805-ad8eef80-f9a4-11ea-807a-aac31b1f76f0.png)

**Comment by illfated** [comment]
# Collect data using Network Monitor

In this topic, you will learn how to use Microsoft Network Monitor 3.4, which is a tool for capturing network traffic.

> [Note]
> Network Monitor is the archived protocol analyzer and is no longer under development. **Microsoft Message Analyzer** is the replacement for Network Monitor. For more details, see [Microsoft Message Analyzer Operating Guide](https://docs.microsoft.com/message-analyzer/microsoft-message-analyzer-operating-guide).

To get started, [download and run NM34_x64.exe](https://www.microsoft.com/download/details.aspx?id=4865). When you install Network Monitor, it installs its driver and hooks it to all the network adapters installed on the device. You can see the same on the adapter properties, as shown in the following image.

![Adapters](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/images/nm-adapters.png?raw=true)

When the driver gets hooked to the network interface card (NIC) during installation, the NIC is reinitialized, which might cause a brief network glitch.
