### ISSUE TITLE
Compatible browser for Network protection

### ISSUE THREAD

**Issue by PawanGupta01** [MicrosoftDocs/windows-itpro-docs#8243]
Once this feature is switch ON in blocked mode, does it have the capability to work in all the browsers apart from IE and Edge?

**Comment by denisebmsft** [comment]
Hello @PawanGupta01 and thank you for the feedback. Can you please tell us to which article(s) this applies? It'll help us route this issue correctly. Thanks!

**Comment by PawanGupta01** [comment]
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/network-protection

About Network Protection feature of Windows Defender Security Center

**Comment by denisebmsft** [comment]
Thanks @PawanGupta01

**Comment by aczechowski** [comment]
Doing repo cleanup, I'm closing this issue as the article was moved to a new repo, you can find the current article at
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/network-protection?view=o365-worldwide
I'm sending this issue (and others for this area) to the current authors for their review. If there's still an update needed, please file new feedback on the current article in the other repo.
