### ISSUE TITLE
Wrong hyperlink of "Security Recommendation" in the table

### ISSUE THREAD

**Issue by donnyatmsft** [MicrosoftDocs/windows-itpro-docs#8246]
it points to "Remediation" and should point to https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/tvm-security-recommendation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d1b587-1f0b-4922-63fc-3d732ca6a739
* Version Independent ID: 8a6787b7-9a54-d27b-6fe4-a7012c115ca9
* Content: [Threat and vulnerability management dashboard insights - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/tvm-dashboard-insights)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/tvm-dashboard-insights.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/tvm-dashboard-insights.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Good catch, thank you! Updating now, and it will be fixed later this afternoon.
