### ISSUE TITLE
Wrong info about Linux in Public preview

### ISSUE THREAD

**Issue by write4joy** [MicrosoftDocs/windows-itpro-docs#8248]
In the prereqs for Linux the page says that Linux is in public preview. I am quite certain that this is wrong and that Linux is GA in MDATP.

Thanks,

Predrag

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by joinimran** [comment]
Hello @write4joy - Can you please confirm which document you are talking about. The current document doesn't says that Linux is in public preview. 

Thanks.
Imran.

**Comment by joinimran** [comment]
@write4joy - Can you please confirm if there is anything else we can do to make this document more helpful, please feel free to share. 

@e0i - FYI Please.

**Comment by illfated** [comment]
Hmm, weird, this ticket was created after the page was updated with correct information in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/1c234eb4476ebd78b3121392cec1146aadc6377d 
I don't think there exists any PR for it, other than the collective merges to the public branch.
I also have got a distinct memory of mjcaparas commenting in a similar ticket (other than this one and #7963) that she would personally correct it.
Give me a few minutes and I will look up which ticket caused the change.

**Comment by illfated** [comment]
There you go. #8050 was the ticket from the same day (August 12, 2020).

**Comment by illfated** [comment]
#please-close

**Comment by joinimran** [comment]
@e0i - Looks like the document is all ok. We are good to close this.
