### ISSUE TITLE
PPPC Identifier wrong

### ISSUE THREAD

**Issue by marckerr** [MicrosoftDocs/windows-itpro-docs#8252]
In this documentation for “New configuration profiles for macOS Catalina and newer versions of macOS” there appear to be some errors. It notes using com.microsoft.wdav.epsext for the identifier in PPPC however that is not working. If you use com.microsoft.wdav, also changing that in the Code Requirements, it does work. Also the graphic for the System Extension shows an Approved Kernel Extension being set but does not show the details for that. That KEXT approval does not appear to be needed.

Also is this document intended to replace https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-install-with-jamf#create-jamf-policies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2354a123-9769-6450-34b6-05e586bbdb4f
* Version Independent ID: d3812533-1ea2-787b-8682-8c143dae9de1
* Content: [New configuration profiles for macOS Catalina and newer versions of macOS - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-sysext-policies)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-sysext-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-sysext-policies.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by marckerr** [comment]
My issue with com.microsoft.wdav.epsext vs com.microsoft.wdav appears to be resolved. It's still unclear from the new document if it is intended to replace the other documentation "JAMF-based deployment for Microsoft Defender ATP for Mac"

**Comment by joinimran** [comment]
@marckerr - Can you please confirm what resolved the issues? What changes should be made in the document to reflecting the correct information?

Thanks 
Imran.

**Comment by joinimran** [comment]
@marckerr - It was great to hear that your issue was resovled. Is there any information available at your end that can help to make this documentation better. 

@e0i - FYI&A Please.

Thanks
Imran

**Comment by illfated** [comment]
@marckerr : If possible, please reply whether this documentation has been updated enough or if it still needs clarification based on your original issue.
