### ISSUE TITLE
Needs Updated Screenhots

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/windows-itpro-docs#8254]
Many of the screenshots in this doc are out of date. Can you update them please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39ae2ccd-9f3f-dcb5-3a20-46b1b4fd3d53
* Version Independent ID: b381c208-94b1-2d22-ef16-a57c138a7d72
* Content: [MDM enrollment of Windows 10-based devices - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/mdm-enrollment-of-windows-devices)
* Content Source: [windows/client-management/mdm/mdm-enrollment-of-windows-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/mdm-enrollment-of-windows-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
@AdamGrossTX - Thank you for your feedback on the document. It looks like the images in the documents are up to date. Is there any specific image you can point on. Or the version of Windows 10 you are referring to. I have checked this on Windows 10 1909 and Windows 10 2004.

Thanks.
Imran.
