### ISSUE TITLE
Can we explicitly state that MDAV should not be disabled and must be in passive mode as a pre-req?

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/windows-itpro-docs#8255]
[Enter feedback here]
It seems that we don't explicitly state that you cannot have MDAV disabled in order for this to work (or will it still work if you completely disable MDAV?  I have doubts but do not know for sure).

Many customers with 3rd party AV explicitly disable MDAV despite the fact that there is passive mode in W10. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8da58e5-9cd8-8ccf-75a9-327c14ebaa76
* Version Independent ID: 24a29218-59e1-7a1d-c8c7-e61424b5f9ee
* Content: [Endpoint detection and response in block mode - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/edr-in-block-mode)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/edr-in-block-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/edr-in-block-mode.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by joinimran** [comment]
@vboyev-MSFT - I think we have covered this part in document Q&A section here at https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/edr-in-block-mode#will-edr-in-block-mode-have-any-impact-on-a-users-antivirus-protection

So the statement "No. EDR in block mode does not affect third-party antivirus protection running on users' devices. EDR in block mode kicks in if the primary antivirus solution misses something, or if there is a post-breach detection. EDR in block mode works just like Microsoft Defender Antivirus in passive mode, with the additional steps of blocking and remediating malicious artifacts or behaviors that are detected." says the same thing in different wording. 

Thanks
Imran.

**Comment by vboyev-MSFT** [comment]
@joinimran - Why are the requirements for EDR in Block mode to successfully function buried in the FAQ?
"Ensure MDAV is not disabled by policy and that cloud based protection is enabled" is a clear, direct statement that has very little room for interpretation - why would we want to state that in ambiguous indirect manner to leave doubt in a customer's mind about precisely what is required for this feature to work?.
