### ISSUE TITLE
typo in PIN がパスワードより安全な理由

### ISSUE THREAD

**Issue by yoichi** [MicrosoftDocs/windows-itpro-docs#8256]
I found following typos:

* 誤: PIN はハードウェアによってサポートされいます。→ 正: PIN はハードウェアによってサポートされ**て**います。
* 誤: トラステッド プラットフォーム モジュール (TPM) チップによりサポーとされています。→ 正: トラステッド プラットフォーム モジュール (TPM) チップによりサポー**ト**されています。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c34dbafa-df3c-a5a5-32d5-2ce152893534
* Version Independent ID: cebdd9a6-45d7-6306-373c-7d31121f9e16
* Content: [PIN がパスワードより安全な理由 (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by denisebmsft** [comment]
@TinaMcN can you take a look?

**Comment by TinaMcN** [comment]
@yoichi この問題を報告していただきありがとうございます。機械翻訳ツールの問題のようです。  私は人間の翻訳のために記事を送った。
(Thank you for reporting this issue. It appears to be a problem with our machine translation tool. I sent the article to be human translated.)
@officeglobal, please let us know when the updated article is published.

**Comment by illfated** [comment]
Took me a couple of tries before I realised that the first kanji is not part of the page text.

https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password#pin-はハードウェアによってサポートされいますpin-is-backed-by-hardware
誤: PIN はハードウェアによってサポートされいます。(Wrong: "PIN is supported by hardware.")
 正: PIN はハードウェアによってサポートされています。(Correct: "PIN is supported by the hardware.")

(first sentence below the heading)
誤: トラステッド プラットフォーム モジュール (TPM) チップによりサポーとされています。("Trusted Platform Module (TPM) chip is used as a support.")
正: トラステッド プラットフォーム モジュール (TPM) チップによりサポートされています。("Supported by The Trusted Platform Module (TPM) chip.")

****

Hello PIN は、トラステッド プラットフォーム モジュール (TPM) チップによりサポーとされています。
Automated translation: Hello PINs are supported by Trusted Platform Module (TPM) chips.

**Comment by TinaMcN** [comment]
@yoichi this article is now translated by a human.  Can you please verify if the issues are fixed and close this issue if it looks ok to you?  Thanks again for reporting it.

**Comment by yoichi** [comment]
It has not been fixed and the problem reported remains present.
https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password

**Comment by TinaMcN** [comment]
@yoichi, the article has been human translated again.  If there are still typos can you please add screenshots that show exactly what the typos are?

**Comment by yoichi** [comment]
@TinaMcN
<img width="945" alt="image" src="https://user-images.githubusercontent.com/107537/147386459-0dd55898-7f8c-4af9-a73a-fd73f6a90cf7.png">

**Comment by TinaMcN** [comment]
@yoichi thank you for the screenshot.  I sent to the translators to check it.

**Comment by TinaMcN** [comment]
@yoichi the article has been updated.   Can you please check it to see if the typos are fixed now? https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password

**Comment by yoichi** [comment]
I've confirmed the fix. Thanks!

**Comment by TinaMcN** [comment]
Thanks for confirming @yoichi and thanks again for reporting the issue.
