### ISSUE TITLE
unclear example

### ISSUE THREAD

**Issue by gonz-kelv** [MicrosoftDocs/windows-itpro-docs#8259]
In the Wildcard section for the Question mark, the first example says this

`C:\MyData\my would include C:\MyData\my1.zip`

Should it be?

`C:\MyData\my? would include C:\MyData\my1.zip`

To reflect the wildcard counting the zip file since it matches it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c0eddd-98ca-1e7a-bddb-36c7037850fe
* Version Independent ID: 6afa98e8-a402-4ef9-2189-8ecc111c3dba
* Content: [Configure and validate exclusions based on extension, name, or location - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-extension-file-exclusions-microsoft-defender-antivirus?source=docs#use-wildcards-in-the-file-name-and-folder-path-or-extension-exclusion-lists)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/configure-extension-file-exclusions-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/configure-extension-file-exclusions-microsoft-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@gonz-kelv , use this 

**C:\MyData\*.zip**

above command will  exclude all  .zip files located in C:\MyData\

**Comment by gonz-kelv** [comment]
Im referring to the ? wildcard options and auditing if the doc is correctly representing how Microsoft Defender will interpret ? wildcard exclusions. Im not trying to find a method to exclude all files in folder. Thanks @RAJU2529

**Comment by joinimran** [comment]
Hello @gonz-kelv - You are right. I have updated the example and created a PR. This will be reflected soon in the document. 

Thanks.
Imran.
