### ISSUE TITLE
More troubleshooting information needed

### ISSUE THREAD

**Issue by gaknigge** [MicrosoftDocs/windows-itpro-docs#826]
It appears a common problem with multi-app kiosk provisioning packages is inability to import the package. The common error as seen in the Provisioning Packages area of Windows 10 Settings is: A provisioning error has occurred. More information can be found in the event viewer. But neither of these locations gives much of a clue as to what actually needs to change. 
As a start, please provide a fully-working example xml file. Customers can then test building a package from that and make sure we can at least import the provisioning package.
Also, help on the various Event Viewer errors that can occur during failed application of a provisioning package would be great. Without more support in this article, the information in the related article "https://docs.microsoft.com/en-us/windows/configuration/lock-down-windows-10-to-specific-apps" will not be accessible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dbf525c-0d5e-5ec5-63ef-ef9417291ec3
* Version Independent ID: e73e7ae6-cdda-fef0-95a6-24cadbdf7261
* Content: [Troubleshoot multi-app kiosk (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/multi-app-kiosk-troubleshoot#feedback)
* Content Source: [windows/configuration/multi-app-kiosk-troubleshoot.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/multi-app-kiosk-troubleshoot.md)
* Service: **unspecified**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@gaknigge We provide a full XML file at https://docs.microsoft.com/en-us/windows/configuration/kiosk-xml however it cannot be applied as is, because any kiosk configuration XML relies on the account existing (on the device for a local account, or in the domain or Azure AD for your domain or tenant). 

I'll ask the engineering team for additional troubleshooting information to add to the topic, including Event Viewer details. Thanks for the suggestion!

**Comment by tschuyler99** [comment]
I have found that the only thing that is not working is rs5:autolaunch. I can make all the other parts work by using the right part of each section including the account. But, I have never been able to get any package to load if any app has the rs5:autolaunch="true" statement. Any ideas? I was able to get 4 apps in start menu tiles and everything. I need an app to auto-launch though
