### ISSUE TITLE
Feedback regarding https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4769 and https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4768

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-itpro-docs#8263]
Hi,
after clarifying internally, I learned that these events seem to not list the TicketFlags (https://tools.ietf.org/html/rfc4120#section-5.3), but rather list the KDCOptions (https://tools.ietf.org/html/rfc4120#section-5.4.1)). I recommend correcting the docs here and also adding the description for bit 14 of KDCOptions (https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-sfu/17b9af82-d45a-437d-a05c-79547fe969f59)
Best regards and thanks a lot,
Steven

**Comment by joinimran** [comment]
Hello @ghost - Thank you for your feedback. As I have reviewed the document and found that TicketsFlasgs related information is already available in the document. 

![image](https://user-images.githubusercontent.com/47118050/96162679-424c2500-0f32-11eb-823a-87c97a25cc27.png)

Thanks.
Imran.
