### ISSUE TITLE
Windows Troubleshooter

### ISSUE THREAD

**Issue by zeiche** [MicrosoftDocs/windows-itpro-docs#8269]
[Enter feedback here]
Any chance of not recommending running Troubleshooting? In all of the years that application has been available, it has never once fixed a single issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349d337e-ca0f-a40a-a522-bd1ae71c7d1e
* Version Independent ID: 50f0c3b0-eaad-89c0-eb3c-878e7564d6f6
* Content: [Windows Update troubleshooting - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-troubleshooting)
* Content Source: [windows/deployment/update/windows-update-troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-troubleshooting.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
i have used builtin windows troubleshooters this diagnostic tool fixed many issues.
But few issues are  not controlled by builtin troubleshooters.
