### ISSUE TITLE
1803

### ISSUE THREAD

**Issue by somewhatlogical** [MicrosoftDocs/windows-itpro-docs#827]
Why do you fail to update the .ISOs with education on the VLK site.  TechNet has Enterprise.  Consumers can upgrade.  Education can be upgraded through the update process to 1803.

Seriously, when Creator's was released it was like 4 months prior to Education hitting VLK sites.  Additionally, your documentation has failed to be updated for the latest release.

Will you be supporting your products throughout their lifecycle, or is your new guidance that you will not support your products until months after their lifecycle has begun?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4568d58-3e3f-4984-464a-814ea5d14069
* Version Independent ID: 2ed023b5-e4e0-30ca-ca7d-c34eae9d3d2a
* Content: [Windows 10 editions for education customers](https://docs.microsoft.com/en-us/education/windows/windows-editions-for-education-customers)
* Content Source: [education/windows/windows-editions-for-education-customers.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/windows-editions-for-education-customers.md)
* Service: **unspecified**
* GitHub Login: @CelesteDG
* Microsoft Alias: **celested**

**Comment by e0i** [comment]
@somewhatlogical 

The issues section of this repository is for product documentation issues.

Please consider opening a product support ticket by the following link below for your feedback so that it gets addressed quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by somewhatlogical** [comment]
I'm pretty sure this has been on the vlk foe a while now.  Thanks for the quick response!

**Comment by e0i** [comment]
@officedocsbot close
