### ISSUE TITLE
Bluetooth, not such a good idea in the Windows' way

### ISSUE THREAD

**Issue by AngelusGi** [MicrosoftDocs/windows-itpro-docs#8273]
Please update the bluetooth module on Windows 10. Is a little bit embarrassing using a Bluetooth device on windows such as an headset. Please consider to rewrite and modernize this module. Windows is the only operating system in which is nearly impossible to use a device

https://aka.ms/AA9l8gc

**Comment by denisebmsft** [comment]
Hello @AngelusGi, and thank you for the feedback. Can you please tell us to which article this feedback applies? This information will help us route the issue to the correct writer/team.
