### ISSUE TITLE
Memory integrity: Not enough detailed information

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/windows-itpro-docs#8279]
No info on prerequisites or other dependencies.

This is the page you arrive on when you click the "Learn more" link under "Memory integrity" for "Core isolation" in the "Device security" section of the "Windows security" settings in Windows. And the reason 90% of the people there click the "Learn more" link is because they are experiencing some issue or problem related to "Memory integrity", for example they might have tried to turn on "Memory integrity" and got an error message saying something like: "Memory integrity can't be started. There may be an incompatibility on your device.".

So, make sure there are enough info in here to resolve any issues an end user might have regarding "Memory integrity" and any operation associated with it. Also there should be read-more-links to where you can find more detailed info on "Memory integrity" and anything else on which it depends on or  which depend on it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f784502-84dc-1122-eab4-1eeeb08da046
* Version Independent ID: 21f210a7-4c38-8f62-0226-121562617fef
* Content: [Memory integrity - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/memory-integrity)
* Content Source: [windows/security/threat-protection/device-guard/memory-integrity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/device-guard/memory-integrity.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by RAJU2529** [comment]
memory integriry needs compatible processors with windows 10 1909 or later professional or enterprise os

**Comment by Cyberchipz** [comment]
I understand that 'Bartolomeus-649' may have been looking for a list of compatible processors; perhaps for future equipment selection?  I would agree that simply observing and acknowledging that it requires "compatible processors" isn't sufficient information.  And, I guess that since it's not an issue for me ATM; I haven't been curious enough to research this and determine if the information is available.  But, it looks off topic for here; am I wrong?

**Comment by beerisgood** [comment]
And Ryzen 5-2600 support memory integrity (HVCI). All above too.

So yeah a minimum CPU should be listed for both AMD and Intel.

**Comment by RAJU2529** [comment]
@beerisgood . Is your processor is fully supported to Memory interity. .Then show the screenshot..
I will add AMD processors list in this article. 
Also Intel i5 7200U  2.75Ghz  Kabylake is also supported.

**Comment by RAJU2529** [comment]
@e0i . I suggest to add all  supported processors models from  INTEL and AMD Inc.
What's  is your opinion? reply here.

**Comment by beerisgood** [comment]
> @beerisgood . Is your processor is fully supported to Memory interity. .Then show the screenshot..

<img width="651" alt="HVCI" src="https://user-images.githubusercontent.com/9625159/93363262-4ad41180-f847-11ea-8f76-e8362a81ebca.png">
<img width="673" alt="DG Readiness" src="https://user-images.githubusercontent.com/9625159/93363268-4dcf0200-f847-11ea-9725-427c1279e5d9.png">

**Comment by RAJU2529** [comment]
@beerisgood . Thanks for the proof. 
I noted amd model processor.
I create PR once I get at least 10 processors list

**Comment by joinimran** [comment]
@levinec - Can you please coordinate with internal teams to see what content should be added in the document or internally Microsoft has any supported CPU related information that can be added in the document. 

Thanks.
Imran.

**Comment by RAJU2529** [comment]
@joinimran . we need form a team consists of  AMD based windows users and INTEL based windows users . And should coordinate with document team.  to tackle with all issues related for document

**Comment by joinimran** [comment]
I understand this @RAJU2529 - At Microsoft the internal development team may have all this info while releasing the product/feature. Keeping this in mind I have engaged the doc author to check with the dev team. 

Thanks
Imran.

**Comment by levinec** [comment]
@Bartolomeus-649 thanks for your question. Based on your feedback, we are revising the experience for users when they select "Learn more" from the Windows Security setting.

In the meantime, these articles should help give your more info about memory integrity and the issue you experienced:
- https://support.microsoft.com/en-us/windows/why-do-incompatible-drivers-prevent-using-memory-integrity-0b7ae567-74de-ee03-1030-9e6fe0d6f4b6 
-https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-vbs

**Comment by albertoween** [comment]
![Captura de pantalla (395)](https://user-images.githubusercontent.com/20495056/104846593-9a9d1500-58db-11eb-8126-ee92cea7ac41.png)

**Comment by albertoween** [comment]
![Captura de pantalla (395)](https://user-images.githubusercontent.com/20495056/104846622-be605b00-58db-11eb-9097-2c9121604bdd.png)
![Captura de pantalla (394)](https://user-images.githubusercontent.com/20495056/104846623-c02a1e80-58db-11eb-8e0b-1a41d343ec41.png)
![Captura de pantalla (393)](https://user-images.githubusercontent.com/20495056/104846624-c0c2b500-58db-11eb-8c5b-79c89e580b3f.png)
![Captura de pantalla (392)](https://user-images.githubusercontent.com/20495056/104846625-c1f3e200-58db-11eb-96c6-8ab2cee2ed9e.png)
![Captura de pantalla (391)](https://user-images.githubusercontent.com/20495056/104846626-c28c7880-58db-11eb-8b10-b5444e3b67b9.png)
![Captura de pantalla (390)](https://user-images.githubusercontent.com/20495056/104846627-c3250f00-58db-11eb-944e-671ae39ae65b.png)
