### ISSUE TITLE
Clarity for Microsoft Intune for Education SKU

### ISSUE THREAD

**Issue by shuurajou** [MicrosoftDocs/windows-itpro-docs#828]
The Microsoft Intune for Education provides an organisation with access to some features normally reserved for Azure AD Premium, such as auto-MDM enrolment. It’d be useful to clarify in this document if the education SKU get the Autopilot benefit (or not). 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40564b31-c91f-2769-e3e0-0b72121a9951
* Version Independent ID: 2ad13ef4-41c5-3ce3-ddaa-827291fcc944
* Content: [Overview of Windows Autopilot](https://docs.microsoft.com/en-gb/windows/deployment/windows-autopilot/windows-10-autopilot)
* Content Source: [windows/deployment/windows-autopilot/windows-10-autopilot.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-10-autopilot.md)
* Service: **unspecified**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by Tdiwestyguy** [comment]
@Shuurajou

In the Prerequisites, it says, 

Devices have to be pre-installed with Windows 10 Professional, Enterprise -->>or EDUCATION<---, of version 1703 or later

**Comment by DaniHalfin** [comment]
Hi @shuurajou - Windows Autopilot content has been updated. Is this issue still relevant?

**Comment by DaniHalfin** [comment]
@shortpatti please close this. Thanks!
