### ISSUE TITLE
MFA Issue more detailed info

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/windows-itpro-docs#8280]
> Multi-factor authentication
> ...
> 
> If the device is running Windows 10, version 1809 or later:
> 
> Windows 10, version 1809 must be updated with KB4497934. Later versions of Windows 10 automatically include this patch.
> 
> When the user signs in on a Hybrid Azure AD joined device with MFA enabled, a notification will indicate that there is a problem. Click the notification and then click Fix now to step through the subscription activation process. See the example below:

Can you elaborate on this MFA Issue?  Does this "Fix now" process have to be done once per device?  Every time a user logs in?  Has it been addressed in 1903, 1909 or 2004 so that it's no longer a problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Hi, 

The content says "Later versions of Windows 10 automatically include this patch." So you don't need to download the patch, but the user still needs to enter MFA credentials.  This is a security precaution. AFAIK this is by design so although it is referred to as 'fixing' something it really is just a normal MFA requirement.

**Comment by greg-lindsay** [comment]
I'm checking to see if the behavior is expected, or if there has been a change.  I'll post back here what I find out.

**Comment by greg-lindsay** [comment]
I received a response back and no, there's no change to the behavior. This is the expected thing to see if MFA is enabled, because it's needed to secure the device.

**Comment by mattsmacblog** [comment]
OK thanks.  Could you clarify the text perhaps so it says 1809 version with the patch and newer versions require the following MFA process?  It reads like you're doing a Fix after a Patch but it's how it is.  

Is the MFA request obvious to the User?  Microsoft Windows licensing activation is requesting approval etc... (a screenshot perhaps)

I'm trying to read the documentation as a business wanting to go from Windows 10 Enterprise KMS to Windows 10 Enterprise Subscription Activation.  Obviously this is quite a change from going from pre-licensing Windows prior to a user getting the device and now making it something they have todo / approve.
