### ISSUE TITLE
Invalid Download link

### ISSUE THREAD

**Issue by BigIve** [MicrosoftDocs/windows-itpro-docs#8282]
[Enter feedback here]

Hi, the link on the page to download the network monitor tool takes you to a page that says it is no longer available.  Can this please be fixed?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8823127-9a9b-141c-6096-e8d40ff6e22c
* Version Independent ID: 02332337-0981-36af-424e-9378487dd4d8
* Content: [Collect data using Network Monitor - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-tcpip-netmon)
* Content Source: [windows/client-management/troubleshoot-tcpip-netmon.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/troubleshoot-tcpip-netmon.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@BigIve < download link will be removed shortly ,  i already request to article author

**Comment by illfated** [comment]
Resolved in PR #8793 / commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/1865a9df9f82722523430f8f75b274980892ed48 .

#please-close

**Comment by illfated** [comment]
This was actually resolved in PR #8278 / commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/56fac2bbc7cc3f2e66c32aac0c6410fea41b1e63 .

Anyway, we would still like to see this ticket closed.

#please-close
