### ISSUE TITLE
Intune - custom intune profile - no longer needed

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/windows-itpro-docs#8284]
No need to create a custom configuration in intune anymore as mentioned in current documentation. The capability to enable pin reset is now native to intune's Account Protection (preview) profile
![image](https://user-images.githubusercontent.com/28310425/93118906-f84ff500-f68e-11ea-89b2-0cc84a3be884.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9dae9da-eaf0-c209-7c65-be8d2c1ada12
* Version Independent ID: 28b6788d-7982-23c2-5f19-f80690ebc0ce
* Content: [Pin Reset - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by joinimran** [comment]
@CHDAFNI-MSFT - Thank you for your feedback. Can you please confirm which portion of the document needs to be removed or updated or a note should be added.

Thanks.
Imran.

**Comment by CHDAFNI-MSFT** [comment]
@joinimran - I believe this section [https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset#configure-windows-devices-to-use-pin-reset-using-microsoft-intune](url) can be removed or altered. It states to create a 'custom device policy' in order to utilize the PIN reset (recovery) feature, however according to the screenshot - this is now possible natively without the need of a custom policy.
![image](https://user-images.githubusercontent.com/28310425/95791971-83cd9d80-0cb0-11eb-8bdc-53f465f9be58.png)

**Comment by illfated** [comment]
(ref. #8457 )

**Comment by illfated** [comment]
Not sure why the PR got closed, I can only presume it got closed due to technical challenges handling the image content.

**Comment by e0i** [comment]
The contents of the PR has been merged and published live. Thank you.
