### ISSUE TITLE
Is there a way to retrive more than 10000?

### ISSUE THREAD

**Issue by DanEhrlich** [MicrosoftDocs/windows-itpro-docs#8285]
Is there a way to retrieve more that 10000 machines from the 'List Machines API'?  I could not find a way to do this.

Thank you,
Dan Ehrlich

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fa8feaf-4173-4c3e-e4bb-e43ff05445d0
* Version Independent ID: fcf8ffb0-ddb4-23bc-7f5d-a94970ab0d6d
* Content: [Supported Microsoft Defender Advanced Threat Protection APIs - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/exposed-apis-list)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/exposed-apis-list.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/exposed-apis-list.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by joinimran** [comment]
Hello @DanEhrlich - Thank you for your query. Please note that it is not possible to get more than 10000 machines on a page. See List machine API limits and other details at https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/get-machines

Thanks.
Imran.

**Comment by DanEhrlich** [comment]
Imran,

I understand that the page size is 10000.  It also implies I should be able to retrieve subsequent pages.  My question is how to get pages after the first one.

Thanks,
Dan

**Comment by joinimran** [comment]
@mjcaparas - Do you have any info that can help to answer @DanEhrlich query. I couldn't find it anywhere on the docs or on the web.

Imran.

**Comment by mjcaparas** [comment]
@DanEhrlich 

I checked with our team and here's the response:

API supports OData queries. 
You can skip 10k results to get the 2nd page, skip 20k results to get the 3rd page, etc.. 
The skip syntax work like that: {base url}/api/machines?$skip=10000
