### ISSUE TITLE
MI can not be enabled on most DIY PCs, but no info about it

### ISSUE THREAD

**Issue by vinixwu** [MicrosoftDocs/windows-itpro-docs#8289]
MI can not be enabled on most DIY PCs. However, there is no topic about this. People can only see an option that can never turn on, with no help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f784502-84dc-1122-eab4-1eeeb08da046
* Version Independent ID: 21f210a7-4c38-8f62-0226-121562617fef
* Content: [Memory integrity - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/memory-integrity)
* Content Source: [windows/security/threat-protection/device-guard/memory-integrity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/device-guard/memory-integrity.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by RAJU2529** [comment]
@vinixwu . Memory integrity needs compatible processors with recommended features as given by windows hardware. 
Device guard might be enabled before MI.
I have enabled MI on Intel i5 7200u with compatible digitally signed device driver's

**Comment by joinimran** [comment]
Hello @vinixwu - Thank you for your feedback. Please note that you need to check your CPU manufacturer datasheet to see if this feature is supported or not.

The document team is also going to update the document with other useful information required for this feature. See https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8279 for details. 

Thanks.
Imran.
