### ISSUE TITLE
Adding Azure AD groups using SID works but not using name

### ISSUE THREAD

**Issue by sveinungre** [MicrosoftDocs/windows-itpro-docs#8292]
The documentation say that we can add Azure AD groups to local groups using Azure AD group name, however I can only get this working when using the Azure AD group SID. Incorrect documentation I assume?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0c28c15-f0be-d732-4d9e-cf5df5e64e8b
* Version Independent ID: 17eba45f-d200-e656-42b9-e1a512931eea
* Content: [Policy CSP - RestrictedGroups - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-restrictedgroups)
* Content Source: [windows/client-management/mdm/policy-csp-restrictedgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-restrictedgroups.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Nice work, good control over these issue tickets. Only a few more than 300, compared to WindowsServerDocs 1.9K -- I wish the ServerDocs team was as big and effective as the Windows IT-Pro Docs team.
