### ISSUE TITLE
Broken link - What's new in Windows 10, version 1909 - Windows Insiders

### ISSUE THREAD

**Issue by mimeeker** [MicrosoftDocs/windows-itpro-docs#8294]
Customer has noted that the link at the bottom of this page under See Also for:

"What's new in Windows 10, version 1909 - Windows Insiders" points to  https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home-1909 

https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home-1909 is a broken link. They include this page in their internal documentation and are requesting an update as they have a number of users trying to access that info.

**Comment by RAJU2529** [comment]
@mimeeker . Which article are you referring?

**Comment by mimeeker** [comment]
@RAJU2529  - the link is on this page: https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1909

**Comment by RAJU2529** [comment]
@mimeeker . Thanks , I check the link

**Comment by mimeeker** [comment]
All - just checking in on behalf of the customer to see if there's been any progress on this?
