### ISSUE TITLE
Standalone licensing?

### ISSUE THREAD

**Issue by josuvil** [MicrosoftDocs/windows-itpro-docs#8301]
Hello, I'm seeing that there is now a standalone Microsoft Defender Advanced Threat Protection (MDATP) license offering through EA. I wondering if we should include that licensing option here. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements?source=docs)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by MaratMussabekov** [comment]
Hello @josuvil,
Standalone licenses could be only purchased through CSP, and it is already mentioned in the note in the article: "Microsoft Defender Advanced Threat Protection is also available for purchase from a Cloud Solution Provider (CSP). When purchased via a CSP, it does not require Microsoft Volume Licensing offers listed."
So I believe no further information is required in the article. What do you think?
Thank you

**Comment by e0i** [comment]
Closing as it has been found that no revisions need to be provided to the documentation. Thank you.
