### ISSUE TITLE
Windows Defender new field AllowNetworkProtectionOnWinServer

### ISSUE THREAD

**Issue by pinguon** [MicrosoftDocs/windows-itpro-docs#8304]
hi, is there this new field: AllowNetworkProtectionOnWinServer

I can't find any informations about it...

**Comment by RAJU2529** [comment]
@pinguon . search in Group policy editor. 
in windows 10 client we can enable network protection

**Comment by pinguon** [comment]
> 
> 
> @pinguon . search in Group policy editor.
> in windows 10 client we can enable network protection

jes but thats EnableNetworkProtection not AllowNetworkProtectionOnWinServer

**Comment by e0i** [comment]
@pinguon Can you provide a link to the which documentation article that this problem stems from? The issue tracker of this repository is used to track documentation feedback. Thank you.

**Comment by pinguon** [comment]
hi

https://docs.microsoft.com/de-de/windows/security/threat-protection/microsoft-defender-atp/enable-network-protection
is nothing about this new? feature: AllowNetworkProtectionOnWinServer
