### ISSUE TITLE
Missing Content: Checksum values for the downloaded file (MSERT.exe) are not provided or available

### ISSUE THREAD

**Issue by DLKirchmer** [MicrosoftDocs/windows-itpro-docs#8307]
ISSUE:
After clicking the link to download the Microsoft Safety Scanner, a best (and my standard) practice is to perform a Checksum calculation on the file for comparison with the vendor provided value for that file.

The information required to perform a comparison against is not available on the download page.

MISSING CONTENT:
Name: MSERT.exe
Size: 121043888 bytes (115 MiB)
SHA256: D4C8D0F2FD43271C14A30C4827EF6E09AC8DCAF05FF3FF9CF8ECBBCD6D57051B

RESOLUTION:
Add the missing information to the download page in a location close to the link that initiates the download of the file.

FIX FORWARD:
Update the standard template used for all download links on any content pages.
Require three (3) mandatory fields to display the: File Name, File Size, and SHA256 value for each item that can be downloaded from the page.

Thank you,

David Kirchmer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5bb1ce3-9128-5385-4417-d22eb5f8cb77
* Version Independent ID: cb6ba731-a2c2-e9b9-7c3e-db781b1b5222
* Content: [Microsoft Safety Scanner Download - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/safety-scanner-download)
* Content Source: [windows/security/threat-protection/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/safety-scanner-download.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Hi @DLKirchmer, thank you for your feedback. Since this is more of a product issue than a documentation issue, please send feedback about the checksums using the feedback hub: https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app

**Comment by illfated** [comment]
@levinec : if what you say is the recommended route of reporting, may I suggest changing the link on the referenced page to point to the download page, instead of using the direct download link? By reporting the issue here, it is (as of now) a fairly reasonable reporting instance, based on the fact that the referenced MS Docs page contains direct download links.

**Comment by DLKirchmer** [comment]
Hi @levinec,

When I follow the link in your comment on Sep 22 the following is displayed:

"The Feedback Hub app lets you tell Microsoft about any problems you run into **while using Windows 10.** You can also send suggestions to help us improve your Windows experience."

This issue I am reporting has absolutely nothing to do with **Windows 10**.  I could be using a Mac or another *nix build and see the exact same issue.

_The page:_ <https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/safety-scanner-download.md> 

_has a direct download link:_ <https://go.microsoft.com/fwlink/?LinkId=212732>

_behind the label:_ **Download Microsoft Safety Scanner (64-bit)**.

Clicking on the link starts the download of the **MSERT.exe** file.

My suggestion is related to the formatting of the content on the page where the link is located that allows a user to download the Microsoft Safety Scanner.

Now that I am looking more closely at the page, another issue that jumps out at me is the first step listed in the **"How to run a scan"** section.  1. Download this tool and **open it.**  With the current state of "security" on the web being well below what should be expected, instructing a user to "Download this tool and **open it.**" is the last thing anyone with a bit of wit about them would do.

Since my feedback about adding missing content to a documentation page was somehow deemed a "product issue" I suppose my next step will be to create a pull request and update the page myself.  Knowing the MSERT.exe changes on a frequent basis, what resource or code is available to dynamically generate a valid checksum when a new version of the MSERT.exe is released?

Looking forward to your reply.

Thanks,

David Kirchmer

**Comment by illfated** [comment]
@DLKirchmer : Fair point. Suggesting a safer procedure when downloading program files (.exe) from any site, there should be a page with both the file to be downloaded and a valid checksum for the download available for any user, regardless of their personal need to validate the checksum when downloading.

I presume the importance is higher for a security product than for non-security applications.
