### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by mobiusnz** [MicrosoftDocs/windows-itpro-docs#831]
https://www.microsoft.com/en-us/WindowsForBusiness/upgrade-analytics appears to be a blank page.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24771310-237e-adf7-be33-59355a87f243
* Version Independent ID: e2792588-8318-98a2-a5bd-ff5cbba75e0e
* Content: [Get started with Upgrade Readiness (Windows 10)](https://docs.microsoft.com/en-nz/windows/deployment/upgrade/upgrade-readiness-get-started)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-get-started.md)
* Service: **unspecified**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by jaimeo** [comment]
Interesting--are you saying the link (to the blank page) appears in the topic listed as the content source here (Get started with Upgrade Readiness)? Because I don't find that link in that page. However, there is such a link out of the Upgrade Readiness Requirements topic and, just as you say, that link doesn't seem to resolve. I'm investigating....

**Comment by jaimeo** [comment]
Aha! Yes, marketing changed that URL and don't seem to have set up a redirect. I'll update the topics that include it. Thanks for letting us know.

**Comment by stephenion** [comment]
Hi, that link above "Go to the Upgrade Readiness page on Microsoft.com" -  https://www.microsoft.com/en-us/WindowsForBusiness/upgrade-analytics  still appears to lead to a blank page, where should it be pointing at ?

**Comment by jaimeo** [comment]
Sorry, I'm not finding where the old link still appears. I just grepped for that string in every Upgrade Readiness topic and did not find it. **In what topic are you still seeing the old link?**

**Comment by stephenion** [comment]
Hi,
On this page,
https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-get-started

The text-

Go to the Upgrade Readiness page on Microsoft.com<http://Microsoft.com> and select New Customers > to start the process.

Thanks,
Steve

**Comment by jaimeo** [comment]
AHA! Thanks very much--my searches didn't find it because it was hidden behind a FWlink. Now I can search for that and fix all instances.

**Comment by R2D2components** [comment]
Please discontinue use any and all works with this device and computer proper authorization has not been obtained and request additional res prices to reconfigure said device or home computer. Please notify me as soon as possible

Jason Robertson
