### ISSUE TITLE
Proxy Service URL's

### ISSUE THREAD

**Issue by dcaddick** [MicrosoftDocs/windows-itpro-docs#8316]
The inclusion of a spreadsheet here with details is very much appreciated.
Having said that - it could possibly be improved with indicating the direction of the traffic flow for each component?

We have two customers looking at deploying at scale with Proxy/Traffic arrangements in restricted areas.
We will have outbound comms enabled - but not inbound
It would be extremely useful to understand which of these are inbound/outbound?

Examples:
1. Microsoft Defender Antivirus Content Delivery Network (CDN) - Security Intelligence updates - assumed as inbound? 
2. MAPS - Used by Microsoft Defender Antivirus to provide cloud-delivered protection - inbound or outbound or both?
3. Upload location for files submitted to Microsoft via the Submission form or automatic sample submission - assumed outbound?
4. Used for Microsoft Defender SmartScreen reporting and notifications - inbound or outbound or both? 

Hope this makes sense?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2748359b-273d-7faa-6a63-7a6ebea450d2
* Version Independent ID: f4885da5-9a83-13aa-789e-1751db586404
* Content: [Set up Microsoft Defender ATP deployment - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/production-deployment)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/production-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/production-deployment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@dcaddick . From my point of view , all are considered as both outbound with inbound. 
client computers send requests (outbound) to Microsoftserver computers and then receivees information From that server sends the output towards the client computers ( Inbound)

**Comment by MaratMussabekov** [comment]
Hello @dcaddick ,
All connections are outbound and initiated by your computer. There is no need to allow any inbound traffic.
The article states:
"The following downloadable spreadsheet lists the services and their associated URLs that your network **must be able to connect to.** Ensure that there are no firewall or network filtering rules that would deny access **to these URLs**, or you may need to create an allow rule specifically for them."

Thank you

**Comment by illfated** [comment]
@MaratMussabekov : Thank you for verifying. It makes sense, too. Some sites may block outbound traffic from reaching any other sites than those determined safe by the company.

**Comment by nam31** [comment]
@dcaddick Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
