### ISSUE TITLE
Feature Updates

### ISSUE THREAD

**Issue by felizondojr** [MicrosoftDocs/windows-itpro-docs#8320]
[Enter feedback here]
I would remove "...around March and September" from the Feature Update section and replace with H1 and H2 or first half and second half of each calendar year.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7945e873-514b-d650-91be-4524567486cb
* Version Independent ID: 31b8f828-3e70-7ddb-ea23-4b9128ce0ccb
* Content: [Windows 10 updates, channels, and tools - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/get-started-updates-channels-tools?source=docs)
* Content Source: [windows/deployment/update/get-started-updates-channels-tools.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/get-started-updates-channels-tools.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by e0i** [comment]
Closing via #8350
