### ISSUE TITLE
Missing words

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/windows-itpro-docs#8330]
Under heading Update WinRE, you find the sentence 

> It then applies servicing stack Dynamic Update, since its s are used for updating other s.

In stead of a "proper" word, there's only the letter **s**. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7734ca5-0770-5bbd-7da5-dda4c1cf5ae0
* Version Independent ID: cb98ef23-d0c6-e62e-b72b-9b5f5d724e8e
* Content: [Update Windows 10 media with Dynamic Update - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/media-dynamic-update)
* Content Source: [windows/deployment/update/media-dynamic-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/media-dynamic-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @SteveDiAcetis
* Microsoft Alias: **jaimeo**

**Comment by baardhermansen** [comment]
I just noticed that this repeats itself in the Note field below too. 

> Skip adding the latest cumulative update to Winre.wim because it contains unnecessary s in the recovery environment. The s that are updated and applicable are contained in the safe operating system Dynamic Update package.

**Comment by SteveDiAcetis** [comment]
Thanks Baard, I’ll take a look and get it fixed shortly - Steve

**Comment by illfated** [comment]
Compare with the latest update 4 months ago, in May, commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/533be11c0ab3b2807c5a7e82f8bf163aad3c8b28 (Fixed missing word) where the word "updates" was inserted.

**Comment by e0i** [comment]
@baardhermansen The content has been updated by **SteveDiAcetis** via the commits from https://github.com/MicrosoftDocs/windows-itpro-docs/commit/97f7c1fe51e07772d2e3a3d1f714e6d10a042892#diff-1370a21e394a60ac9da84dac81124271 onward. Thank you, as always for your feedback.
