### ISSUE TITLE
Types of Groups

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#8332]
[Enter feedback here]
Step 5 states that we need to use an AAD Security Group, does that mean that we cannot use an M365 Group, or is this an oversight that needs to be corrected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b246db4-2ef2-fc54-8db1-7a75a4974304
* Version Independent ID: 57290170-ba72-9f26-5a9c-311f6980ea19
* Content: [Create and manage roles for role-based access control - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/user-roles)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/user-roles.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/user-roles.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by MaratMussabekov** [comment]
Hello, just tried to create a role assignment using this manual - only security groups are supported.
Thank you
