### ISSUE TITLE
Need more clarification on "install the repository configuration" step

### ISSUE THREAD

**Issue by jmmowrer** [MicrosoftDocs/windows-itpro-docs#8336]
Under "Ubuntu and Debian Systems" section, on the part "Install the repository configuration:", it should be noted that the "[channel]" should be changed to the desired channel such as "insiders-fast", etc.  Copying the command as-is leads to unsuccessful install.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2197cba-30ac-1749-e25a-6f39c9ee9d20
* Version Independent ID: bcd14f13-ab59-8e69-5c83-42fee6e51f87
* Content: [Deploy Microsoft Defender ATP for Linux manually - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello,
it is already stated in the article:
![image](https://user-images.githubusercontent.com/48041687/97091976-4fb38e80-1659-11eb-8732-4a3fffa2bbc1.png)
Anyways, I will add a clarification.
Thank you
