### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by kingfr0z** [MicrosoftDocs/windows-itpro-docs#8338]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfc0921d-e59b-5186-0dec-7c2facb66f1c
* Version Independent ID: 1fc0f7ba-f8cd-d071-75de-dc5a1af868c0
* Content: [Onboard devices to the Microsoft Defender ATP service - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/onboard-configure)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/onboard-configure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/onboard-configure.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
@kingfr0z : Would you like to add anything else to your post, or is this just a test of the reporting feature in the documentation?

If this is just a test, please close the ticket when able.
