### ISSUE TITLE
Can I use an external camera with windows hello for business and how reliable it is?

### ISSUE THREAD

**Issue by rahulkj30** [MicrosoftDocs/windows-itpro-docs#8346]
No. Windows 10 currently only supports one Windows Hello for Business camera and does not fluidly switch to an external camera when the computer is docked with the lid closed. The product group is aware of this and is investigating this topic further.

**Comment by denisebmsft** [comment]
Hello @rahulkj30 and thanks for posting feedback. This does not appear to be a documentation issue and it looks like it's resolved, so I am going to close this for now.
