### ISSUE TITLE
Microsoft Defender for Endpoint (Linux) will not start if /opt is a symlink

### ISSUE THREAD

**Issue by RowdyChildren** [MicrosoftDocs/windows-itpro-docs#8347]
If /opt is a symlink MSDE for Linux will not start. This is for security reasons and the solution is to create a bind mount for /opt/microsoft. This was confirmed directly with the PG

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09c6c11b-345f-a930-7466-fcb5d35794bc
* Version Independent ID: 358b1d57-15e6-a943-b9e2-3ebbc9bc4c6d
* Content: [Troubleshoot installation issues for Microsoft Defender ATP for Linux - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-support-install)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-support-install.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-support-install.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@RowdyChildren . Your query will be answered by linux experienced users.

**Comment by RowdyChildren** [comment]
> @RowdyChildren . Your query will be answered by linux experienced users.
@RAJU2529 I am not asking a question I am making a statement. This is a known situation that needs to be addressed by a doc writer.

**Comment by RAJU2529** [comment]
@RowdyChildren. I am not familiar with linux , so that's why I said this article editied by author or by contributor. so wait for few days'.
@e0i assign user to look in this issue #8347.

**Comment by e0i** [comment]
Hello, @RowdyChildren Thank you for the heads up and going through PG for confirmation. An independent contributor is going to revise the article accordingly based on your suggestion.
