### ISSUE TITLE
Conflicting and confusing information

### ISSUE THREAD

**Issue by christopherggg** [MicrosoftDocs/windows-itpro-docs#835]
https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/What-s-new-for-IT-pros-in-Windows-10-version-1803/ba-p/188568

https://blogs.technet.microsoft.com/windowsitpro/2017/07/27/waas-simplified-and-aligned/

In the blogs above it states: "The Semi-Annual Channel replaces the Current Branch [CB] and Current Branch for Business [CBB] concepts." This implies that both CB and CBB are replaced with a single channel.

However, in your own documentation for setting up deployment rings (https://docs.microsoft.com/en-us/windows/deployment/update/waas-servicing-channels-windows-10-updates and https://docs.microsoft.com/en-us/windows/deployment/update/waas-deployment-rings-windows-10-updates and https://docs.microsoft.com/en-us/windows/deployment/update/waas-manage-updates-wufb) you state that CB and CBB are replaced with SAC-T and SAC respectively, i.e. they are still two separate deployment rings. If we have deployment rings set up per your documentation, with our TARGETED devices configured to SAC-Targeted (via GPO or otherwise) they will actually receive 1803 *AFTER* the SAC configured devices due to you designating 1803 as SAC BEFORE SAC-Targeted. This is the opposite result of what we expect, and the opposite of how you have release Feature Updates in the past.

For example: 1709 was designated SAC-Targeted BEFORE it was designated SAC. It was ready for TARGETED deployment (SAC-T on 10/17/2017) BEFORE it was ready for broad deployment (SAC on 12/12/2017).

Another example: 1703 was designated CB on 4/11/2017, then designated CBB on 7/11/2017

With 1803 you are doing the complete opposite. Do you see how this might cause confusion? 

So, do we configure our TARGETED devices as SAC-Targeted, or as SAC with custom deferral lengths for each deployment ring? For the enterprise, what does configuring devices as Semi-Annual (Targeted) actually accomplish now? Either way your documentation needs to be updated and clarified to match what your current intention is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5400f8b-2ed0-7960-4e3d-2f3444be7e6b
* Version Independent ID: 81bd37f4-301b-b5ab-cda2-972a72a31ae7
* Content: [Assign devices to servicing channels for Windows 10 updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-servicing-channels-windows-10-updates)
* Content Source: [windows/deployment/update/waas-servicing-channels-windows-10-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-servicing-channels-windows-10-updates.md)
* Service: **unspecified**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
@jaimeo - can you take a look

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@christopherggg - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
