### ISSUE TITLE
Link to "Windows 10 release information" in section Servicing Channels is broken.

### ISSUE THREAD

**Issue by Borkason** [MicrosoftDocs/windows-itpro-docs#8351]
Link to "Windows 10 release information" in section Servicing Channels is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6957383-3bd9-eef9-6410-9c42f8a0b172
* Version Independent ID: a2090374-0fd1-8d67-66de-30c4cf2835f7
* Content: [Overview of Windows as a service (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-overview#servicing-channels)
* Content Source: [windows/deployment/update/waas-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment]
@Borkason . Thanks for pointing out. I am fixing the link now.

**Comment by RAJU2529** [comment]
@jaimeo . Please look in to this PR #8355. .

**Comment by e0i** [comment]
Closing via #8355.
