### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by bakad01** [MicrosoftDocs/windows-itpro-docs#8353]
The wdavkext.kext file is not in the suggested directory so the fix failed

Any more suggestions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72abfa66-ddf0-4fd6-152d-b66ebad98525
* Version Independent ID: c72a3ba7-cd9e-3b40-1bd6-dea45c5f690e
* Content: [Troubleshoot kernel extension issues in Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-support-kext)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-support-kext.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-support-kext.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@bakad01 Are you still having this issue? What do you have under /Library/Extensions? My research confirms that you should see wdavkext.kext there.

Is your macOS version up to date? 

> **Starting with macOS High Sierra (10.13)**, macOS requires all kernel extensions to be explicitly approved before they are allowed to run on the device.
