### ISSUE TITLE
Guide for stop errors/blue screen errors is out of date

### ISSUE THREAD

**Issue by td47** [MicrosoftDocs/windows-itpro-docs#8354]
The guide seems rather out of date. Although it was updated August 2020, there is NO mention of updates history links for 1909 and 2004 based systems.

There is mention of Driver Verifier, but this is not needed as the functionality is already included in the later windows 10 levels (it is actually mentioned in the linked article).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b85544e-69dc-04ef-3ae7-98864d7a7529
* Version Independent ID: af0af832-7663-ab3b-7283-2948819465ac
* Content: [Advanced troubleshooting for Stop error or blue screen error issue - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-stop-errors)
* Content Source: [windows/client-management/troubleshoot-stop-errors.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/troubleshoot-stop-errors.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Closing via merged PR #8356. Thank you.
