### ISSUE TITLE
columns reversed for one entry

### ISSUE THREAD

**Issue by obivon** [MicrosoftDocs/windows-itpro-docs#836]
In the table of "Available features by version" the following entry has its elements in the wrong columns:
Not available 	Add a root certificate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b16f5b-2bd8-1fb9-bd9c-23e24d0eaec8
* Version Independent ID: 5ad30750-3905-f466-e834-0430fc646d78
* Content: [Determine the licensing version and features to use in IEAK 11 (Internet Explorer Administration Kit 11 for IT Pros)](https://docs.microsoft.com/en-us/internet-explorer/ie11-ieak/licensing-version-and-features-ieak11)
* Content Source: [browsers/internet-explorer/ie11-ieak/licensing-version-and-features-ieak11.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/internet-explorer/ie11-ieak/licensing-version-and-features-ieak11.md)
* Service: **unspecified**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by shortpatti** [comment]
@obivon, I changed the column entries.
