### ISSUE TITLE
TYPO ON MICROSOFT DOCS WEBSITE

### ISSUE THREAD

**Issue by CLEVELAND2024** [MicrosoftDocs/windows-itpro-docs#8361]
Just a small typo, but still an error.  Am I only able to submit feedback for Microsoft through GitHub?

-Jennifer Cleveland

![MicrosoftDocs_TYPO](https://user-images.githubusercontent.com/71947128/94350487-9d5dbc80-0003-11eb-9f02-3770bd68ff46.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5862cc7-3f36-5f2e-9ade-f7441f99f818
* Version Independent ID: b8bd1985-7b5b-ea79-976a-7d96ad69335c
* Content: [Use Windows Event Forwarding to help with intrusion detection (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection)
* Content Source: [windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Thank you for pointing out the typo. That one should be easy to correct.

Also: Please, PLEASE don't use CAPS when writing a title. It comes across as shouting to others.
This is not media front page news (Donald Trump) we are talking about, nor international politics.

If you are able to edit the title line and make use of regular text instead of all uppercase, it would be appreciated.

**Comment by illfated** [comment]
I notice that your user name is all caps too, is this because you keep your Caps Lock key stuck in the ON position a lot of the time?

**Comment by illfated** [comment]
There you go. Pull Request #8362 is ready for review. The PR will also automatically close this ticket when merged.

Regarding your question:
> Am I only able to submit feedback for Microsoft through GitHub?

Welcome to the Windows Server documentation repository. You are number #8361 in this section alone, so probably hundreds of thousands of people have posted in the combined issue ticket repositories before you dropped in. You are a new tourist in a well-established arena. If you had taken the time to browse around this repository, you would have known that this GitHub repository has been available for 2 years now and more than 8K issue tickets have been filed for the Windows Server docs alone. There are many other repositories for the other documentation, so please search around and get informed.
