### ISSUE TITLE
Documentation update required - WVD WIN 10 multisession support

### ISSUE THREAD

**Issue by SokoloffMaxim** [MicrosoftDocs/windows-itpro-docs#8363]
Please update documentation to expain wther it is supported to use wufbto update WVD WIN 10 multisession, and also provide the detailed process on how to do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2056993d-a700-fba6-8982-e645b182eeea
* Version Independent ID: fb38a86a-cdf6-6fc2-8eb6-fd54f1599f55
* Content: [Windows Update for Business (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-manage-updates-wufb)
* Content Source: [windows/deployment/update/waas-manage-updates-wufb.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-manage-updates-wufb.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@arcarley

**Comment by VLG17** [comment]
@SokoloffMaxim [According to Christiaan Brinkhoff](https://twitter.com/Brinkhoff_C/status/1272829525680848897) you can by leveraging the steps described in [this article](https://docs.microsoft.com/en-us/windows/deployment/update/waas-configure-wufb). What do you think?

**Comment by jaimeo** [comment]
@arcarley can you advise here?

**Comment by e0i** [comment]
The answer provided by **VLG17** seems sufficient. Thanks.
