### ISSUE TITLE
So no .exe file allowed ????

### ISSUE THREAD

**Issue by fbifido** [MicrosoftDocs/windows-itpro-docs#8368]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc63299-cc1c-e031-deb7-915914b8f94e
* Version Independent ID: 356eaba5-16b0-952f-fc19-c8d5be5feb5f
* Content: [Demonstrate Autopilot deployment - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm)
* Content Source: [windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
@fbifido : Could you add more details to your question, so we may better understand what you want to know, and maybe understand if there is a need for more detailed description in the documentation?

**Comment by greg-lindsay** [comment]
Please provide a more descriptive feedback, I don't know what the issue is with the doc.
