### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/windows-itpro-docs#8370]
"Configure the **** policy setting " just below the heading Countermeasures looks like a placeholder. I assume the **** shoul be replaced by the actual name?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bcaf30b-7304-6874-ba5d-791cc4d435d2
* Version Independent ID: 961def9f-094a-3d1e-82a4-bb152c2e5a1e
* Content: [Minimum password length (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/minimum-password-length)
* Content Source: [windows/security/threat-protection/security-policy-settings/minimum-password-length.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/minimum-password-length.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@andrePKI , thanks for reporting, I am fixing now .

**Comment by RAJU2529** [comment]
@e0i, @nam31,  assign user to verify this PR #8372

**Comment by e0i** [comment]
This issue has been addressed via merged PR #8372 by a community contributor, Thank you @andrePKI , and @RAJU2529 .
