### ISSUE TITLE
Microsoft safety scanner

### ISSUE THREAD

**Issue by dyd1947** [MicrosoftDocs/windows-itpro-docs#8374]
[Enter feedback here]
Look at the scan result: unknown malware was detected but not deleted. I am a genuine Win10 Home Edition computer, We hope to delete the unknown malware detected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5bb1ce3-9128-5385-4417-d22eb5f8cb77
* Version Independent ID: cb6ba731-a2c2-e9b9-7c3e-db781b1b5222
* Content: [Microsoft Safety Scanner Download - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/safety-scanner-download)
* Content Source: [windows/security/threat-protection/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/safety-scanner-download.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by RAJU2529** [comment]
@dyd1947, Zip all the detected malware files  and sumbit  to micrsosoft antivirus  analysis lab server .
Sign in with microsoft account on below site ,send the samples
**https://www.microsoft.com/en-us/wdsi/filesubmission/**

For better security purposes and Real time protection , use builtin microsoft defender antivirus  , enable it enable windows firwall, with enable controlled folder access, enable block at firstsight.
