### ISSUE TITLE
Query regarding MDM Unenrollment initiated by the User.

### ISSUE THREAD

**Issue by palslav** [MicrosoftDocs/windows-itpro-docs#8376]
Hi,

 We are facing one Issue regarding MDM Unrenrollment process initiated by User,
In which when MDM server is receiving Unenrollment the request, it does not contain Meta value for Alert(**1226**) in the SyncBody.
Please find following logs for the same behavior :

[Windows MDM Sync request for device guid <> <SyncML xmlns="SYNCML:SYNCML1.2">

```
<SyncBody>
<Alert>
<CmdID>2</CmdID>
<Data>1201</Data>
</Alert>
<Alert>
<CmdID>3</CmdID>
<Data>1224</Data>
<Item>
<Meta/>
<Data>user</Data>
</Item>
</Alert>
<Alert>
<CmdID>4</CmdID>
<Data>1226</Data>
<Item>
<Meta/>
<Data>1</Data>
</Item>
</Alert>
<!-- other device information -->
<SyncBody>
```

Earlier, Under this Alert tag we had a Meta tag which contained string : "**com.microsoft:mdm.unenrollment.userrequest**" as part of User Initiated disconnection, on basis of which MDM Server proceeds with further action.
`<Alert>
<CmdID>4</CmdID>
<Data>**1226**</Data>
<Item>
<Meta>
<ns2:Type>**com.microsoft:mdm.unenrollment.userrequest**</ns2:Type>
</Meta>
<Data>1</Data>
</Item>
</Alert>`

But now the above <Meta> that MDM Server receives is Empty tag without any String (<Meta/>).
This behavior can be seen on various windows versions like : 1803, 1809, 1903, 1909 and 2004 that has been tested and getting the same result.
In this document nothing is updated or mentioned regarding change in unenrollment process initiated by the User.

Can we use the alert value 1226 without the "com.microsoft:mdm.unenrollment.userrequest" value be used to trigger unenrollment for the device. Any reason why the type has been removed from these versions.

Please clarify on same so that we can proceed on this.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d8375f-a60e-dbad-453b-80c933249b1b
* Version Independent ID: 2b233d8a-6eda-ce21-9da5-6a2ccee81372
* Content: [Disconnecting from the management infrastructure (unenrollment) - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/disconnecting-from-mdm-unenrollment#user-initiated-disconnection)
* Content Source: [windows/client-management/mdm/disconnecting-from-mdm-unenrollment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/disconnecting-from-mdm-unenrollment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by palslav** [comment]
Hi,

Any updates regarding this?

Thanks,
Pallav

**Comment by joinimran** [comment]
Hello @palslav - thank you for posting your query here. Looks like this is not a document related issue but a support request. I would suggest you open a support case with Microsoft so that they can better help you with this. From the support team, if required they will route this to the relevant document management team to see if there is anything missing or need any changes in the document. 

@e0i - Can you please guide @palslav on how a support request can be opened.
