### ISSUE TITLE
MICROSOFT

### ISSUE THREAD

**Issue by DatGoodArt** [MicrosoftDocs/windows-itpro-docs#8379]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0080ea96-3ae5-49ee-d621-eb8ffbd14a4f
* Version Independent ID: d17b7412-6993-4347-174c-9f20d045af00
* Content: [Policy CSP - ApplicationDefaults - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-applicationdefaults#applicationdefaults-defaultassociationsconfiguration)
* Content Source: [windows/client-management/mdm/policy-csp-applicationdefaults.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-applicationdefaults.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
This ticket does not appear to have any useful content. Unless we get any updates from the OP (Original Poster), it appears to be ready for closing.
