### ISSUE TITLE
Which windows server versions support cloud delivered protection

### ISSUE THREAD

**Issue by weiss-gal** [MicrosoftDocs/windows-itpro-docs#8385]
[Enter feedback here]
although windows client versions are mentioned, I could not find anywhere a clear statement saying which windows server versions support cloud delivered protection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f249ddfc-a83d-e53f-5c95-3e9cb0294929
* Version Independent ID: 5a8cf2bc-e2b4-2f63-8425-ea291c564cd6
* Content: [Use next-generation technologies in Microsoft Defender Antivirus through cloud-delivered protection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/utilize-microsoft-cloud-protection-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/utilize-microsoft-cloud-protection-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/utilize-microsoft-cloud-protection-microsoft-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by VLG17** [comment]
@weiss-gal According to [this article](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-in-windows-10), Windows Server 2016 and 2019.

**Comment by e0i** [comment]
Hello @weiss-gal 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
