### ISSUE TITLE
FileSystem CSP examples

### ISSUE THREAD

**Issue by adamenger** [MicrosoftDocs/windows-itpro-docs#8387]
Hi there! Trying to deploy a FileSystem CSP but I don't see any examples on this page. Could we get some examples of how the FileSystem CSP can be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c76d6513-e6ba-dedf-46f7-8da348adb2c1
* Version Independent ID: 050be118-822f-20e6-7b47-fe5c867e8ea8
* Content: [FileSystem CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/filesystem-csp)
* Content Source: [windows/client-management/mdm/filesystem-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/filesystem-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @adamenger - Thank you for your query. Can you please explain your use case so that we can better help you with this?  Can you also please confirm the operating system you are trying to deploy for this CSP. This CSP is only applicable to Mobile and Mobile Enterprise versions of Windows. Please see https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference for details and confirm if you are meeting the requirements.

Thanks.
Imran

**Comment by adamenger** [comment]
Thanks for pointing that out- I didn't notice that this was for windows mobile only. We can close this unless you all think an example would be helpful for anybody else who wants one in the future.

Thanks for looking at this!

**Comment by illfated** [comment]
The content at the very top of the page should be enough content, although I notice that there are 2 distinct **Note** lines which are regular text & indented by a quote mark (vertical gray bar at the far left edge of the document). I am seriously considering making a Pull Request to have those 2 lines converted to the de facto MS standard colored Note blobs instead. See my copied example text snippet below:

***

# FileSystem CSP


The FileSystem configuration service provider is used to query, add, modify, and delete files, file directories, and file attributes on the mobile device. It can retrieve information about or manage files in ROM, files in persistent store and files on any removable storage card that is present in the device. It works for files that are hidden from the user as well as those that are visible to the user.

> **Note**  FileSystem CSP is only supported in Windows 10 Mobile.
> 
> 
> 
> **Note**   This configuration service provider requires the ID\_CAP\_CSP\_FOUNDATION and ID\_CAP\_CSP\_OEM capabilities to be accessed from a network configuration application.

***

Notice in particular that the first Note specified that "FileSystem CSP is only supported in Windows 10 Mobile."

**Comment by illfated** [comment]
The more I think about it, the more I become certain that the page needs to have those 2 notes converted to proper MS codestyle colored Note blobs.

I will open a PR to have that change done, as well as indicating that the PR intends to close this issue ticket.

**Comment by illfated** [comment]
There you go. PR #8908 is ready for review, comments, and suggestions.

**Comment by joinimran** [comment]
@e0i - This has been sorted out. We are good to close this issue.

**Comment by illfated** [comment]
Fair enough, it will be closed anyway.
