### ISSUE TITLE
Name of installer for APPV sequencer has changed on Windows ADK 1803

### ISSUE THREAD

**Issue by ChrisAtFCPS** [MicrosoftDocs/windows-itpro-docs#839]
It seems that with the release of Windows ADK 1803 which, in and of itself, has been somewhat problematic with multiple fails along the way... errors during download, broken links, etc... the instructions above are no longer accurate because the command line installer for the app-v sequencer is no longer an EXE and is now under a totally different name -- "Appman Auto Sequencer-x86_en-us.msi" or "Appman Sequencer on amd64-x64_en-us.msi" or "Appman Sequencer on x86-x86_en-us.msi"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410b9952-998e-4564-78c1-62d92f778b57
* Version Independent ID: 8b4e065f-03bd-5911-e473-56420605090a
* Content: [Install the App-V Sequencer (Windows 10)](https://docs.microsoft.com/en-us/windows/application-management/app-v/appv-install-the-sequencer)
* Content Source: [windows/application-management/app-v/appv-install-the-sequencer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/app-v/appv-install-the-sequencer.md)
* Service: **unspecified**
* GitHub Login: @MaggiePucciEvans
* Microsoft Alias: **elizapo**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by markgcharles** [comment]
Yes i'd also like to understand if this is the only way we can get our hands on the Sequencer. No dedicated installer anymore?
Why "Appman Sequencer"? In a corporate env this name change causes problems.

**Comment by denisebmsft** [comment]
I think the original issue is now resolved, so I'm closing this with kind regards.
