### ISSUE TITLE
Unclear whether we need both kernel and system extensions

### ISSUE THREAD

**Issue by macmillernz** [MicrosoftDocs/windows-itpro-docs#8394]
[Enter feedback here]
I have deployed these new profiles to my test machine using Jamf and removed the kernel extension policy and it appears to get blocked now.
Do we need both in the interim?
<img width="427" alt="Screen Shot 2020-10-02 at 9 17 00 AM" src="https://user-images.githubusercontent.com/47721519/94860147-1e003b00-0492-11eb-8dde-9da656034641.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2354a123-9769-6450-34b6-05e586bbdb4f
* Version Independent ID: d3812533-1ea2-787b-8682-8c143dae9de1
* Content: [New configuration profiles for macOS Catalina and newer versions of macOS - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-sysext-policies)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-sysext-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-sysext-policies.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@macmillernz What macOS Version are you running? According to the linked article, you need the kernel extension.

> In alignment with macOS evolution, we are preparing a Microsoft Defender for Endpoint for Mac update that leverages system extensions **instead of kernel extensions.This update will only be applicable to macOS Catalina (10.15.4) and newer versions of macOS.**

**Comment by e0i** [comment]
@macmillernz 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
