### ISSUE TITLE
Add instructions for the system extension and network extension policy.

### ISSUE THREAD

**Issue by macmillernz** [MicrosoftDocs/windows-itpro-docs#8395]
[Enter feedback here]
I love how comprehensive these instructions are, but would be good to see the system and network extension policy instructions here too

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f791dc07-b2c6-3003-a829-cd1ec03a2918
* Version Independent ID: 2c53adbc-600f-60b2-e8b2-b907335f4862
* Content: [Set up the Microsoft Defender ATP for macOS policies in Jamf Pro - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@macmillernz **Step 8** talks about system policy extension and **Step 9** about Network Policy extension. Would you like to see something else added to these? Could you share more details around what should be added?
