### ISSUE TITLE
TLS requirement and enable cloud-delivered protection

### ISSUE THREAD

**Issue by bledMS82** [MicrosoftDocs/windows-itpro-docs#8398]
TLS requirements not listed for Defender ATP communications to azure  . No mention of enable cloud protection requirement for TVM full functionality example reporting AV enabled . 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by VLG17** [comment]
@bledMS82 Do you think a note linked to [this article](https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/enforcement-of-tls-1-2-for-connections-to-microsoft-defender-atp/ba-p/1085358) would suffice for the first point?

Regarding the second point, what would you like to see added to the article? Do you have a link that talks about "enable cloud protection requirement"? I'm not sure what you are refering to. Thanks in advance!

**Comment by joinimran** [comment]
Hello @bledMS82 - Thank you for your query. Please note this document is only intended to describe minimum requirements to run the ATP. Defender by default communicates on an encrypted channel with intune. This is only required to take care of TLS requirements when working on specific use cases.

For your send point, please visit https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/next-gen-threat-and-vuln-mgt to see in details for Threat and vulnerability management. Keeping all this information in view I feel that this document has all the necessary information as a minimum requirement to run Windows Defender.

Thanks.
Imran.

@e0i - FYI&A, Please.
