### ISSUE TITLE
Intune Link

### ISSUE THREAD

**Issue by win2000b** [MicrosoftDocs/windows-itpro-docs#8400]
Please can someone review the Intune link for this article. THe one detailed is
https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-configure

This doesn't allow you to schedule scans. Is there a better link?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aeeaa89-e3b9-7dd5-81f2-7cb1f37d925d
* Version Independent ID: 76f816fa-8acd-a260-7d4b-c1a541b785db
* Content: [Schedule regular quick and full scans with Microsoft Defender AV - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/scheduled-catch-up-scans-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/scheduled-catch-up-scans-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/scheduled-catch-up-scans-microsoft-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by VLG17** [comment]
@win2000b Good catch. I guess [this ](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-windows-10) is the correct link. I'll create a request to have it added.
