### ISSUE TITLE
Need help with https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-timelanguagesettings#timelanguagesettings-configuretimezone

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#8402]
[Enter feedback here]
Hello, Can someone help me with deployment values on, TimeLanguageSettings/ConfigureTimeZone

On review, the article does not provide the DATA TYPE or supported Policy configuration Values required to push an "MDM" URI based policy to the Device.

It says:
Specifies the time zone to be applied to the device. 
-->This is the standard Windows name for the target time zone.

I tried string, and integer values from timezone "NAME" with no success.   I tried Integer value "4" for PST, with no success. 

Reference articles:
https://support.microsoft.com/en-us/help/973627/microsoft-time-zone-index-values
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-time-zones

Could someone kindly update the article confirming data type such as "String/Integer" and the data values or syntax required, or where an admin would go to obtain these values?

thanks!
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86ff0ddd-37e5-2f87-920c-f83b07d4ebb1
* Version Independent ID: ca02de5e-14cb-5f64-b7e4-9b5fe738029f
* Content: [Policy CSP - TimeLanguageSettings - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-timelanguagesettings#timelanguagesettings-configuretimezone)
* Content Source: [windows/client-management/mdm/policy-csp-timelanguagesettings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-timelanguagesettings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by clenh2o** [comment]
Tdiwestyguy, the document at Microsoft says "Specifies the time zone to be applied to the device. This is the standard Windows name for the target time zone."  This can be translated to mean that the value is a "STRING" and will accept the values assigned to Windows.  You can get the value directly from a computer by running "tzutil.exe /g" at a command prompt.
This solution courtesy of :  https://www.petervanderwoude.nl/post/configure-time-zones-via-windows-10-mdm/
