### ISSUE TITLE
Step 11: Deploy Microsoft Defender ATP for macOSにて、マニフェストファイルは必要ありません 他

### ISSUE THREAD

**Issue by fnifni** [MicrosoftDocs/windows-itpro-docs#8408]
# Step 11: Deploy Microsoft Defender ATP for macOS

- 4. Navigate to Advanced Computer Searches.

実際には、コンピュータを選択し、歯車アイコンを選択することで、次のステップを行うことができます

- 8. Select Open. Set the Display Name to Microsoft Defender Advanced Threat Protection and Microsoft Defender Antivirus.
  - Manifest File: Select Upload Manifest File.

マニフェストファイルについて作成する記述がありません
実際にマニフェストファイルなしで構成してもMDATPは動作します

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f791dc07-b2c6-3003-a829-cd1ec03a2918
* Version Independent ID: 2c53adbc-600f-60b2-e8b2-b907335f4862
* Content: [Set up the Microsoft Defender ATP for macOS policies in Jamf Pro - Windows security](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies#step-11-deploy-microsoft-defender-atp-for-macosstep-11-deploy-microsoft-defender-atp-for-macos)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Machine Translation from Japanese, along with the original document text in English:

> # No manifest file is required

> ## Step 11: Deploy Microsoft Defender ATP for macOS
> * iv. Navigate to Advanced Computer Searches.
>
> **In fact, you can do the next step by selecting your computer and selecting the gear icon**
>
> * viii. Select Open. Set the Display Name to Microsoft Defender Advanced Threat Protection and Microsoft Defender Antivirus.
>
>
>   * Manifest File: Select Upload Manifest File.
>
> **There is no description to create about the manifest file**
> **MDATP works even if you actually configure it without a manifest file**
> 

I assume there is potential for looking into the correctness of the documentation here.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub. I don't know the topic well enough to give any feedback on the topic.

I can only recommend to be aware of the fact that this repository is mainly for documentation feedback (which I assume this is), so hopefully someone with technical knowledge of Microsoft Defender ATP for macOS will reply here with questions and suggestions for how to move forward with this issue.

**Comment by fnifni** [comment]
I'm providing feedback based on the results of a successful operation so that people using this document are not confused.
If my feedback is different from the purpose of this Github repository, then please close this ticket.
I will keep these bad knowns to share internally.

**Comment by illfated** [comment]
Fair enough, thank you for providing a clarification.

Are there any obvious mistakes in the Japanese translation, so we can point out any errors to the translation team?

I don't know, I do not know how to read kanji, so it will be helpful if you can point out any errors in the machine translated document.
