### ISSUE TITLE
Does not include SmartScreen policy settings for Chromium-based Edge (version 77 and later)

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/windows-itpro-docs#8409]
This article covers configuring SmartScreen for the old, non-Chromium based version of Edge (version 45 and earlier).

It does not cover the new settings for new Chromium edge, (version 77 and later), which are documented here: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#smartscreen-settings-policies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5413195-c0e2-99e4-5d82-6bffdcbbddb9
* Version Independent ID: b8cef753-139b-0098-ed30-63cca8d5b8b9
* Content: [Available Microsoft Defender SmartScreen Group Policy and mobile device management (MDM) settings (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-available-settings)
* Content Source: [windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-available-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-available-settings.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@ChrisAtMAF   **https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#smartscreen-settings-policies**
in the above site page, all  SmartScreen settings in ms edge policies are added.  

The following sub policiees for smartscreen settings are  clearly explained 
1.PreventSmartScreenPromptOverride	
2.PreventSmartScreenPromptOverrideForFiles	
3.SmartScreenAllowListDomains	
4.SmartScreenEnabled
5.SmartScreenForTrustedDownloadsEnabled
6.SmartScreenPuaEnabled

**Comment by ChrisAtMAF** [comment]
Hi,

Yes, those are the settings I am referring to. However, please note at the top of the page you referenced:

> This article applies to Microsoft Edge version 77 or later.

And regarding the settings on this page:

https://docs.microsoft.com/en-us/microsoft-edge/deploy/group-policies/security-privacy-management-gp

> You've reached the documentation for Microsoft Edge version 45 and earlier

This is because there are two different sets of Microsoft Defender SmartScreen policies, depending on whether Edge <45 or Edge >77 is targeted.  So, on this page:

**Administrative Templates\Windows Components\Windows Defender SmartScreen\Microsoft Edge\Configure Windows Defender SmartScreen** applies to Edge <45
**Administrative Templates\Microsoft Edge\SmartScreen settings\Configure Microsoft Defender SmartScreen** applies to Edge >77

**Administrative Templates\Windows Components\Windows Defender SmartScreen\Microsoft Edge\Prevent bypassing Windows Defender SmartScreen prompts for sites** applies to Edge <45
**Administrative Templates\Microsoft Edge\SmartScreen settings\Prevent bypassing Microsoft Defender SmartScreen prompts for sites** applies to Edge >77

**Administrative Templates\Windows Components\Windows Defender SmartScreen\Microsoft Edge\Prevent bypassing Windows Defender SmartScreen prompts for files** applies to Edge <45
**Administrative Templates\Microsoft Edge\SmartScreen settings\Prevent bypassing of Microsoft Defender SmartScreen warnings about downloads** applies to Edge >77

Since this page only references Edge <45 settings, it needs to be updated with the new policies for Edge> 77, under 'Group Policy settings', and the 'Recommended Group Policy and MDM settings for your organization' need updating for Edge> 77.

**Comment by RAJU2529** [comment]
@ChrisAtMAF . Now i understood the real issues, so this article author  need to be update because there is no edit option

**Comment by e0i** [comment]
Closing via #8542. Thanks.
