### ISSUE TITLE
More Information

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/windows-itpro-docs#8410]
How long after you update wdapt does the client pull it down?
How do you manually sync that information?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d1d825-ab12-2f37-b692-5266487ef16f
* Version Independent ID: fef750ac-311b-28b4-1661-16385997815b
* Content: [Web content filtering - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/web-content-filtering)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/web-content-filtering.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/web-content-filtering.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by VLG17** [comment]
@SquirrelAssassin The [article you linked](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/web-content-filtering) talkes about a public preview feature of Defender for Endpoint.

What part of the document you linked are you reffering to with the questions you asked? Could you please share some more details?
