### ISSUE TITLE
Please Add details about supported enrollment device type with Conditional access and defender ATP compliance policy

### ISSUE THREAD

**Issue by sufuruka** [MicrosoftDocs/windows-itpro-docs#8414]
Could you please add or modify Docs Information?
In currently Docs confuse which enrolled devices type are supported or not.

[Current Information]
Before you begin
[!WARNING]
It's important to note that Azure AD registered devices is not supported in this scenario.</br>
Only Intune enrolled devices are supported.

[Request to add information]
Azure AD registered + Intune enrollment device does not support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 787a0651-234a-ce78-acc4-7de2a7de3ac8
* Version Independent ID: f7814aa8-be34-882b-0806-cc71160795b7
* Content: [Configure Conditional Access in Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-conditional-access)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-conditional-access.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-conditional-access.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by VLG17** [comment]
@sufuruka Could you please share some more details regarding "Azure AD registered + **Intune enrollment device** does not support."

You mean a device which is currently in the intunre enrollment process but not yet enrolled, or what exactly?

**Comment by e0i** [comment]
@sufuruka Please feel free to re-open this issue with an answer to the above query to proceed with investigation. Thank you.
