### ISSUE TITLE
where to apply this setting

### ISSUE THREAD

**Issue by tecxx** [MicrosoftDocs/windows-itpro-docs#8416]
this page does not clearly describe whether this setting should be applied to DCs only (where the tickets are created) or also on member servers and clients.
based on our tests we did not see any difference in kerberos ticket encryption when we modify this setting on clients/servers. however, modifying this setting on the DC immediately restricts the tickets to the types specified in the setting.

so we conclude it is sufficient to "harden" this setting only at the DC level. the member servers/clients anyway do not issue tickets so this setting should have no effect. is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d05d447-1cc1-1eeb-3c4d-74591874f4e1
* Version Independent ID: 020b4d09-5ce9-e636-0545-1ce27029a921
* Content: [Network security Configure encryption types allowed for Kerberos - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@tecxx Your understanding is correct. The "hardenning" happens at the DC level, where the KDC who grants the tickets resides. 

From a client perspective the only requirement is that it has a Kerberos client installed (which Windows has), and that it can communicate with the KDC to get it’s tickets.

Keep in mind that the recommendation is to have only AES encryption types allowed (disable RC4). More details [here](https://docs.microsoft.com/en-us/windows-server/security/kerberos/preventing-kerberos-change-password-that-uses-rc4-secret-keys)

**Comment by tecxx** [comment]
@VLG17 thanks for confirming.
i am asking because this microsoft article from 2011:
https://docs.microsoft.com/en-us/archive/blogs/openspecification/windows-configurations-for-kerberos-supported-encryption-type
is confusing in this regard. on the very bottom of the page it mentions " _You can use the Local Security Policy to change the setting on the local machine only, or an administrator can use group policy to apply it to multiple machines including DCs in the domain._ "
based on my understanding - and your confirmation - this is old/invalid information?

**Comment by VLG17** [comment]
@tecxx It is indeed old information, but i wouldn't say invalid. It's just one piece of the puzzle.

Although you can specify the supported encryption type locally on the client, in the end in order for a ticket to be granted and for communication to take place, the client and domain controller must be able to agree on a supported encryption type. That's why i say the hardenning happens on the DC side, because if the DC is not configured to support (msDS-SupportedEncryptionTypes) the encryption type that the client is relaying (KRB_AS_REQ)for then the communication will not occur.

**Comment by tecxx** [comment]
thank you very much.
