### ISSUE TITLE
This  article needs to be update again ,  i am going to edit very soon 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#8417]
I found certain policy paths are  changed in windows v2004, like configure  Microsoft Defender SmartScreen is  located in different path say

**Administrative Templates\Microsoft Edge\SmartScreen settings\Configure Microsoft Defender SmartScreen**

and few other policy paths is also changed, so i am going to edit this article very soon.

![msedge](https://user-images.githubusercontent.com/3296790/95216034-4334d680-080f-11eb-9145-f96643e4febf.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5413195-c0e2-99e4-5d82-6bffdcbbddb9
* Version Independent ID: b8cef753-139b-0098-ed30-63cca8d5b8b9
* Content: [Available Microsoft Defender SmartScreen Group Policy and mobile device management (MDM) settings (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-available-settings)
* Content Source: [windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-available-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-available-settings.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@Dansimp ,  I  found three different locations for policy setting  **Configure Windows Defender SmartScreen**

1. **Administrative Templates\Windows Components\File Explorer\Configure Windows Defender SmartScreen**
2. **Administrative Templates\Windows Components\Windows Defender SmartScreen\Explorer\Configure Windows Defender SmartScreen**
3. **Administrative Templates\Windows Components\Windows Defender SmartScreen\Explorer\Microsoft Edge\Configure Windows Defender SmartScreen**
so what should i do   now ,  i stopped editing because i am confused

i am using windows 10 v2004 64bit   build no 19042.546
here are the proofs 
![01JPG](https://user-images.githubusercontent.com/3296790/95229255-fad0e500-081d-11eb-8a24-2e936e9ef7ce.JPG)
![02](https://user-images.githubusercontent.com/3296790/95229272-fefd0280-081d-11eb-988c-a6dbdcf0c2ee.JPG)
![03](https://user-images.githubusercontent.com/3296790/95229283-01f7f300-081e-11eb-8418-afa46192344b.JPG)

**Comment by RAJU2529** [comment]
@e0i   @nam31,  @illfated  . three members  look into this issue #8417 .

**Comment by illfated** [comment]
Thank you for mentioning me, but I must admit I am not an expert on this topic.
Please allow for MS Docs team members or technical writers to confirm.

**Comment by e0i** [comment]
@RAJU2529 You don't really need to tag us as we are already going through the issues regularly. Thank you.

**Comment by e0i** [comment]
@RAJU2529 If you intend to update the article, you may go ahead and create a Pull Request and explain your rationale for the contribution within the description of the PR. There’s no need to create an issue for contributions that one plans to make. Thank you.
