### ISSUE TITLE
Live response - advanced feature

### ISSUE THREAD

**Issue by ayfukumo** [MicrosoftDocs/windows-itpro-docs#8421]
[Enter feedback here]
According to docs, if the customer selected role as Live response - Advanced, the customer can "Upload a file to the remote device".
But we tried to this feature, when we set only "Live response - Advanced", MDATP's GUI "Upload file to library" is disabled.
So we cannot upload local file to remote device.

Then we added "Managed security settings in Security Center" role, "Upload file to library" button is enabled and we can upload local file to remote device.

I guess this is document bug, because Antonio(anvascon) said this is by design via e-mail.

Could you check this issue and if document bugs, please resolve this issue.
If you have any concerns or questions, please let me konw. (ayfukumo@microsoft.com)

Cheers,
Ayumi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b246db4-2ef2-fc54-8db1-7a75a4974304
* Version Independent ID: 57290170-ba72-9f26-5a9c-311f6980ea19
* Content: [Create and manage roles for role-based access control - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/user-roles#permission-options)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/user-roles.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/user-roles.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@ayfukumo . Please record video and upload in online storage, paste the link.  So  That MDATP advanced experienced users can give solution.
I am not an expert in this case.

**Comment by ayfukumo** [comment]
Hi,

I will prepare recoded videos regarding this issue.

Cheers,
Ayumi

**Comment by ayfukumo** [comment]
Hi,

My colleague Kei makes record video regarding this issue.
Could you check video from below URL?
[​mp4 icon] https://microsoftapc.sharepoint.com/:v:/t/nagano/Edtho16_6oFCnIPjqY2sJ2kBLUdDb4TdPUayUpux5Bq0Sw?e=wyn5xh

Please let me know if you have any concerns or questions.

Cheers,
Ayumi

**Comment by ayfukumo** [comment]
Hi,

Could you tell me where is data store for our recorded video?
I tried to compressed but it exceeded to GitHub's limitation.

Cheers,
Ayumi

**Comment by RAJU2529** [comment]
@ayfukumo . upload the recorded video  to Google drive or one drive and share the link, then paste the link here. 
or else upload in YouTube, paste the link

**Comment by ayfukumo** [comment]
https://1drv.ms/u/s!AgFD4Gly0bpLgbBsnPbhySt6RovwZw?e=J28bvt

Could you download video from above link?

**Comment by joinimran** [comment]
Hello @ayfukumo - Thank you for sharing the details. Looks like I can't access the video from any of the above-mentioned links. I have noted a point when you raise the issue regarding a document that **because Antonio(anvascon) said this is by design via e-mail.** Can you please forward me that email.

@anvascon - Can you please share your input regarding this so that I can make necessary changes in the document.

Thanks
Imran.

**Comment by ayfukumo** [comment]
Hi,

Could you try below links?
https://1drv.ms/v/s!AgFD4Gly0bpLgbBtNVjWNKNHQ5brxw?e=q95jdD

Thanks,
Ayumi

**Comment by joinimran** [comment]
Thanks, @ayfukumo - I have seen the video and what I have found is that you have selected Live Response Capabilities as "Basic" when the upload file was grayed out. In your query, you have mentioned that when you have selected Live Response as "Advance" it was grayed out. Whereas, when the upload file was grayed out or available, the only change that happened was Manage security settings from the security center option was not checked.

![image](https://user-images.githubusercontent.com/47118050/103504590-a9b2aa80-4e79-11eb-89b5-e6a987fa0bc6.png)

Whereas in the document it is listed to use the advance option for the file upload option.

![image](https://user-images.githubusercontent.com/47118050/103504692-03b37000-4e7a-11eb-8256-5999123aca82.png)
