### ISSUE TITLE
Support for Windows Home edition yes/no?

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/windows-itpro-docs#8425]
This page mentions the following: https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure

When looking at the following page though: https://www.microsoft.com/en-us/windowsforbusiness/compare, we see no support mentioned for Home edition?

So my questions would be:
a) Is Home edition supported or not supported for targetign WIP?

Thanks in advance,

Kenneth van Surksum

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ad3f92-24de-5eb5-8454-c72d85737183
* Version Independent ID: 900125eb-31ea-faf3-ac30-7c3d7b30f611
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@kennethvs . I think Professional , education and enterprise editions are supported

**Comment by illfated** [comment]
@kennethvs : https://www.microsoft.com/en-us/windowsforbusiness/compare is correct, Windows 10 Home is not supported.

Which part of the referenced MS Docs page causes confusion in this regard? The "**Applies to:**" section?

Please note that unless specified, the Microsoft Docs pages for Windows 10 are specifically targeting IT Pros, as showcased here:
- https://docs.microsoft.com/en-us/windows/windows-10/ **(Windows 10 resources and documentation for IT Pros)**

**Comment by illfated** [comment]
Please also note that the majority of the pages are intended for Enterprise use, so there are cases where not even Windows 10 Pro is supported.

**Comment by e0i** [comment]
@kennethvs 

It seems that the question has been answered by the community,  and thus the issue is being marked as resolved. 

Please note that the issues section of the repository is intended for corrections in technical documentation.

Should you need to ask a similar question again, consider asking the question via the [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channel.

Thank you.

**Comment by kennethvs** [comment]
@e0i: My comment was referring to the https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure page which mentions support for WIP-WE on Windows Home.

Also related to the "intended for enterprise use" remark, Even though the OS is Home, the application (Office 365) is targeted towards Enterprise. 

If it's still not supported I will log an issue on the page mentioned above and ask them to remove the reference to Windows Home.

/Kenneth
