### ISSUE TITLE
Specify IKEv2 Certificate Requirements for DHGroup

### ISSUE THREAD

**Issue by zerqent** [MicrosoftDocs/windows-itpro-docs#8427]
This page should address the Certificate Requirements of changing the DHGroup.

E.g. from my testing if you need to use an RSA-group you need an RSA Certificate (with a specific key length?). If you need an ECP-group you need an ECP-certificate etc.

And must the client and server match?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbee818c-da2f-3243-473f-f98dabfe9514
* Version Independent ID: d5ff7378-808e-5530-988d-fa769aa8b849
* Content: [How to configure Diffie Hellman protocol over IKEv2 VPN connections (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/how-to-configure-diffie-hellman-protocol-over-ikev2-vpn-connections)
* Content Source: [windows/security/identity-protection/vpn/how-to-configure-diffie-hellman-protocol-over-ikev2-vpn-connections.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/vpn/how-to-configure-diffie-hellman-protocol-over-ikev2-vpn-connections.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@DulceMontemayor Can you help with finding the IKEv2 Certificate Requirements for DHGroup? Thank you.
