### ISSUE TITLE
Device Inventory

### ISSUE THREAD

**Issue by josuvil** [MicrosoftDocs/windows-itpro-docs#8429]
Hello, just to let you know that this document refers to a Device List, but the navigation and page now shows Device Inventory. Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18da4497-3712-ac71-4643-5e49b531716a
* Version Independent ID: e46cd2be-d129-2255-4be1-4567911a3d12
* Content: [View and organize the Microsoft Defender ATP devices list - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/machines-view-overview)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/machines-view-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/machines-view-overview.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@josuvil .I checked article now, no  changes. 
If possible , post screenshots mark error as yellow.

**Comment by josuvil** [comment]
Sure. On the document, you show “Devices List” on the navigation page. You also show “Devices list” snippet. However, the product shows “Devices Inventory” now.

From document:

[cid:image001.png@01D69EF0.0CB5A9A0]


From the product: https://securitycenter.windows.com/machines

[cid:image002.png@01D69EF0.0CB5A9A0]

**Comment by RAJU2529** [comment]
@josuvil . There is no screenshot.

**Comment by josuvil** [comment]
![document snippet](https://user-images.githubusercontent.com/28968872/95658407-271f8680-0ae8-11eb-8600-919fd5e78a2c.png)
![portal-snippet](https://user-images.githubusercontent.com/28968872/95658413-2edf2b00-0ae8-11eb-9866-07be42f7e77b.png)

**Comment by VLG17** [comment]
@josuvil As the note at the top of the article you referenced indicates, there is a transition ongoing at the moment from Microsoft Defender ATP to Microsoft Defender for Endpoint, during which 

> We'll be updating names in products and in the docs in the near future

![image](https://user-images.githubusercontent.com/41186174/96988394-f4847d80-152c-11eb-994b-34db4f37cb67.png)


What you're seeing is the old wording, which will be updated to reflect what you see in the article.

Just as a sidenote, if you look at the [video taking about TVM dashboard insights](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/tvm-dashboard-insights) you'll see another name used: Machines List

![image](https://user-images.githubusercontent.com/41186174/96988345-e2a2da80-152c-11eb-98e3-c55832e5342f.png)

**Comment by e0i** [comment]
Hello @josuvil 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered,

Thanks.
