### ISSUE TITLE
Need more on Startlayout enactment with ImportEdgeAssets

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#843]
The process guide for Startlayout is great. 

I am running through guide on +ImportEdgeAssets, but I'm not seeing how this is supposed to work.   I could use a hand with updated, clearer documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800fa3a7-e6c8-5525-401b-e69a6ccfa66d
* Version Independent ID: c2d24d10-a365-4720-ec22-57b2e12340b4
* Content: [Policy CSP - Start](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-start)
* Content Source: [windows/client-management/mdm/policy-csp-start.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-start.md)
* Service: **unspecified**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by nam31** [comment]
@Tdiwestyguy the article has been updated. Please let us know if you still have any question regarding the issue you have raised initially.
