### ISSUE TITLE
Incorrect information for Server Operators

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/windows-itpro-docs#8431]
https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/active-directory-security-groups#server-operators
The first sentence is not correct. "Members in the Server Operators group can administer domain servers."  It should state domain controllers instead of domain servers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44e911d3-219e-19b8-4870-07514d9a94a1
* Version Independent ID: 960a7388-560b-90eb-e0ff-d8d2bb6f9a7a
* Content: [Active Directory Security Groups (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/active-directory-security-groups#server-operators)
* Content Source: [windows/security/identity-protection/access-control/active-directory-security-groups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/access-control/active-directory-security-groups.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by poortom1004** [comment]
I have created a pull request to correct this.
https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8495

**Comment by e0i** [comment]
@poortom1004 Thank you for coming up with a PR for this issue.
