### ISSUE TITLE
Seem to be missing audit events

### ISSUE THREAD

**Issue by RobG-MSFT** [MicrosoftDocs/windows-itpro-docs#8432]
Hey guys,

So I have a customer asking about event ID 5379; which apparently is a new audit event starting with Windows Server 2019, and does not show up on the site.  

We are looking for information about this audit event.  Things like the actual event and what it shows for in the event.  How do you go about enabling this audit event with Advanced Audit Policy.  Like what needs to be configured for this event to show up?

The other more general question as well.  Since we are not listing this event what other new(er) audit events are missing from the site as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5d459d6-c31f-9c6f-5772-7d175f34f2fb
* Version Independent ID: d292a4aa-eb88-5d76-633a-6a986f6d0eb6
* Content: [Audit User Account Management (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-user-account-management?source=docs)
* Content Source: [windows/security/threat-protection/auditing/audit-user-account-management.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/audit-user-account-management.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@RobG-MSFT My research shows that Event ID 5379 is an Audit Success event. It appeares when a user performs a read operation on stored credentials in Credential Manager.

You don't need to do/enable anything for it to appear in Security log under Event Viewer. 

Newer events (if they exists) including Event ID 5379 should be added to the linked article as soon as a separate page will be created for them and linked, as is the case with the other Event IDs presented in the linked you referenced.
