### ISSUE TITLE
Automatic MDM enrollment guide no longer accurate. Settings have been moved to the Intune portal

### ISSUE THREAD

**Issue by Wartz** [MicrosoftDocs/windows-itpro-docs#8433]
This document is no longer applicable since the Intune app has moved to its own portal. For example, configuring the MDM user scope is now done in the Intune Portal instead of the Azure portal.

https://endpoint.microsoft.com/#blade/Microsoft_Intune_DeviceSettings/DevicesEnrollmentMenu/windowsEnrollment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b95868d3-c141-0038-69b2-7a6a84d817d8
* Version Independent ID: b68e29a4-fe87-3c20-4abc-06ab815f33ee
* Content: [Azure AD and Microsoft Intune - Automatic MDM enrollment in the new Portal - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/azure-ad-and-microsoft-intune-automatic-mdm-enrollment-in-the-new-portal)
* Content Source: [windows/client-management/mdm/azure-ad-and-microsoft-intune-automatic-mdm-enrollment-in-the-new-portal.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/azure-ad-and-microsoft-intune-automatic-mdm-enrollment-in-the-new-portal.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@Wartz I'll add a note about this, until the article will be changed or removed. Hope this is ok with you.
