### ISSUE TITLE
Incorrect error code

### ISSUE THREAD

**Issue by BigIve** [MicrosoftDocs/windows-itpro-docs#8434]
HI, I was just trying the test malware file on this page.  It was successfully blocked by defender, however, the event ID didn't match the documentation.

The event logs showed an Event ID of **1116**, **NOT 2050** as indicated on the page.  Infact the 2050 code isn't even mentioned on the page that the link takes you to.

Just thought you'd like to know.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86b0db3-f979-bd1f-78a4-41247510721a
* Version Independent ID: 5289bb5f-f015-7f38-05a1-26a615ae07aa
* Content: [Configure and validate Microsoft Defender Antivirus network connections - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-network-connections-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/configure-network-connections-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/configure-network-connections-microsoft-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@BigIve . Will you post the screenshot , so that the experts will analyze the issue.

**Comment by BigIve** [comment]
Sure,
![image](https://user-images.githubusercontent.com/22046653/95935379-d331dc00-0e1e-11eb-9553-0309fb894ea1.png)
This is what showed up in my event log.

**Comment by illfated** [comment]
PR #8871 is available for review, comments and suggestions.
