### ISSUE TITLE
Security/RequireDeviceEncryption is not supported on HoloLens 2

### ISSUE THREAD

**Issue by kagillig** [MicrosoftDocs/windows-itpro-docs#8438]
The following page lists that Security/RequireDeviceEncryption is supported on HoloLens 2 devices but it is not so it should be removed from the list: https://docs.microsoft.com/en-us/windows/client-management/mdm/policies-in-policy-csp-supported-by-hololens2. Thanks!

**Comment by VLG17** [comment]
@kagillig Good catch, because Bitlocker is always enabled on HoloLens 2. I'll create a request to have it removed from the list.
