### ISSUE TITLE
EDR is unavailable for Linux, please advise.

### ISSUE THREAD

**Issue by stevenoneill** [MicrosoftDocs/windows-itpro-docs#8439]
EDR is unavailable for Linux, please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0cd332f-6f82-3ea4-c12e-b6e5cb5a1f42
* Version Independent ID: 45e9d876-3d16-7698-620c-5af21e24dc32
* Content: [Migrate from Symantec to Microsoft Defender for Endpoint - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-migration)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-migration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-migration.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@stevenoneill . if possible will you post the screenshot, so that experts I'll analyze the issue

**Comment by stevenoneill** [comment]
Thanks for the reply @RAJU2529.  Here is a screenshot showing that the app_version is 101.10.34 from the InsiderFast relaese ring, edr early preview is enabled, but there is NO edr_configuration_version.

![image](https://user-images.githubusercontent.com/15053495/95659072-ad3dcc00-0aec-11eb-814d-3137dbb4048a.png)

Additionally, by what I am seeing in /var/log/microsoft/mdatp log files, all indications are that EDR is truly not fully enabled.

Finally,  when I search on Bing or google or whatever for "edr_configuration" there are no results, which is really surprising.  I had assumed that if this was truly available, even as a preview, there'd be some search documentation on those settings and at least 1 blog post from anyone promoting it.

https://www.google.com/search?q=%22edr_configuration%22&rlz=1C1GCEB_enUS905US906&oq=%22edr_configuration%22&aqs=chrome..69i57j0.3379j0j4&sourceid=chrome&ie=UTF-8

Looking forward to any further info you can provide.

**Comment by RAJU2529** [comment]
@stevenoneill , Sorry i am not an expert in this case, because I have no idea in LINUX OS, so wait for few days. Linux expert users will give solutions

**Comment by e0i** [comment]
Hello, @stevenoneill  thank you for providing feedback.

The issues section of this repository is intended for documentation feedback.

Please consider opening a support ticket via the following link for your question so that it gets answered quickly:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Feel free to re-open this ticket if you feel that documentation also needs to be updated.

**Comment by stevenoneill** [comment]
Sounds good. Thank you for the confirming that EDR on Linux is not currently available.
