### ISSUE TITLE
Status of kernel DMA protection on AMD platforms

### ISSUE THREAD

**Issue by Mr-nUUb** [MicrosoftDocs/windows-itpro-docs#8444]
My question #6693 was not answered at all.
Everywhere you mention Intel, what about AMD? AMD does support similar virtualization technologies, so what's the status there? Do you plan on supporting AMD-Vi like you support Intel VT-d? The document you mentioned was not reworked to include this information. You know, Thunderbolt is now supported on AMD, too...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b83e95-63de-87c5-929c-d5f25e33d124
* Version Independent ID: 743ead3f-b4a5-1589-6577-e1d12aaa1b92
* Content: [Kernel DMA Protection (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/kernel-dma-protection-for-thunderbolt)
* Content Source: [windows/security/information-protection/kernel-dma-protection-for-thunderbolt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/kernel-dma-protection-for-thunderbolt.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@Mr-nUUb . We must verify detailedly before editing this article for support of AMD processors. 
Also in AMD official website , there is no detailed technical specifications of each processors. But intel have seperate website to read all specifications from available data sheets.

**Comment by nam31** [comment]
@Mr-nUUb this article confirms support for AMD. 
https://docs.microsoft.com/windows-hardware/design/device-experiences/oem-kernel-dma-protection
Please let us know if you still have any question regarding the issue you have raised initially.

**Comment by nam31** [comment]
@Mr-nUUb Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
