### ISSUE TITLE
Comparison PDF Link Broken

### ISSUE THREAD

**Issue by dltmurphy** [MicrosoftDocs/windows-itpro-docs#8445]
The link for the Comparison PDF under licensing leads to https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PBG7 which gives the below error:

`{"Code":"DocumentGone","Message":"StorageDocumentNotFoundException : Document with id 'RE2PBG7', tenant 'am' is now gone (i.e. the document probably expired and thus no longer available).","Resource":null}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@dltmurphy . Thanks for reporting here . I will fix today .

**Comment by RAJU2529** [comment]
@dltmurphy here t
[Windows10_CommercialEdition_Comparison.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/5363063/Windows10_CommercialEdition_Comparison.zip)
he comparison table

**Comment by illfated** [comment]
Ref. commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/4a8312bab19419e5f6c59fbbbba1c0b8317ecc1b . This ticket is now resolved and can be closed.

**Comment by e0i** [comment]
The broken link has been replaced via PR #8446. Thank you.
