### ISSUE TITLE
Intune section is out of date

### ISSUE THREAD

**Issue by bradrush** [MicrosoftDocs/windows-itpro-docs#8451]
Hi there, the section that suggests how to instigate a scan from Intune is out of date since the Intune portal has now become Endpoint Protection manager. I am quite keen to know how to do the same from the new portal so await the update.

Thanks very much

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f555df5-133e-940d-a1b9-1c225a7e0c98
* Version Independent ID: fa2c4d7b-19aa-685a-e4b9-9b17afd6526e
* Content: [Run and customize on-demand scans in Microsoft Defender AV - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/run-scan-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/run-scan-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/run-scan-microsoft-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by joinimran** [comment]
@bradrush - Thank you for your feedback on the document. You are right that intune is now endpoint protection manager. I have reviewed the document and found that the instruction for running a scan from endpoint protection manager is available in the document. 
I have followed the same instruction and this works fine for me.  Please see, https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/run-scan-microsoft-defender-antivirus#use-microsoft-endpoint-configuration-manager-to-run-a-scan 

If you have anything else I can help you with, please do let me know.

@e0i FYI&A Please.

Thanks 
Imran.
