### ISSUE TITLE
Confusing text

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/windows-itpro-docs#8452]
This text “ You can configure the password policy settings in the following location by using the Group Policy Management Console:
Computer Configuration\Windows Settings\Security Settings\Account Policies\Password Policy
If individual groups require distinct password policies, these groups should be separated into another domain or forest, based on additional requirements.” is confusing, because one could also use finegrained password policies.
I presume this article has evolved from a single domain wide policy description after which fgp policies were added.
I would propose a rework of the article, to structure this as follows
- describe the single domain wide policy and its settings
- if individual groups require distinct pw policies, you can use fgp policies
- describe fgp policies 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d91fe29b-40f5-cac0-76bb-342ef4131328
* Version Independent ID: 97f45f65-51ef-1e78-7de2-75a991298793
* Content: [Password Policy (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-policy)
* Content Source: [windows/security/threat-protection/security-policy-settings/password-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/password-policy.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
Closing via #8583
Thanks
