### ISSUE TITLE
Do not expore passwords?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/windows-itpro-docs#8453]
According to this (summary, item 3): https://www.microsoft.com/en-us/research/wp-content/uploads/2016/06/Microsoft_Password_Guidance-1.pdf
Microsoft recommends since 2016(!) to not expire password.
Best practice as decribed here is in contradiction to that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed5f0d1b-bfbb-c2a8-76e7-b4b0105160e8
* Version Independent ID: 13684860-a76b-5832-4376-22a585f63fd1
* Content: [Maximum password age (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/maximum-password-age)
* Content Source: [windows/security/threat-protection/security-policy-settings/maximum-password-age.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/maximum-password-age.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@andrePKI [The article you linked](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/maximum-password-age#considerations) contains also a section which references the Microsoft Password Guidance and talks about the new recommandations:

![image](https://user-images.githubusercontent.com/41186174/97899451-fe368e00-1d41-11eb-8481-db4e0cb1fe77.png)

**Comment by nam31** [comment]
@andrePKI Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Comment by andrePKI** [comment]
@nam31 Yes, I am happy with the explanation and the current text (although it requires readers to read it to the end to find the considerations). Thank you
