### ISSUE TITLE
Wrong section

### ISSUE THREAD

**Issue by Eddddeee** [MicrosoftDocs/windows-itpro-docs#8460]
![image](https://user-images.githubusercontent.com/56706640/95947139-8ea74000-0e20-11eb-8e23-76702a8ebf47.png)

The highlight words is not only for "Choose how BitLocker-protected removable drives can be recovered" but for above 3 policies. These words should be in an new line. For example,

![image](https://user-images.githubusercontent.com/56706640/95947327-eba2f600-0e20-11eb-81d2-b9032ed30dd8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e21c26e-1320-04e1-d103-e64751235f9f
* Version Independent ID: 48b4da0f-2bb0-98d8-20f9-acd30a0e4a34
* Content: [BitLocker recovery guide (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-recovery-guide-plan)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-recovery-guide-plan.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-recovery-guide-plan.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Fair point. Thank you for reporting that issue. I will post a Pull Request to have that text formatted properly.

**Comment by illfated** [comment]
There you go. Pull Request #8462 is ready for review.
