### ISSUE TITLE
WMIDiag?

### ISSUE THREAD

**Issue by MilanKrocek** [MicrosoftDocs/windows-itpro-docs#8461]
Hello,

I have found WMIDiag (even download link doesn't exist) is no longer supported. Which Powershell script should be used to get more information?

Thanks.

MK

**Comment by RAJU2529** [comment]
@MilanKrocek  here is the tool
[WMIDiag.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/5382128/WMIDiag.zip)

**Comment by MilanKrocek** [comment]
Thank you.

MK
