### ISSUE TITLE
Group Policy tree has the wrong folder name for Security Intelligence Updates

### ISSUE THREAD

**Issue by andrewgiese** [MicrosoftDocs/windows-itpro-docs#8463]
In the section regarding the Group Policy configurations for controlling Microsoft Defender updates, step 4 states that the policies are under **Windows components > Microsoft Defender Antivirus > Signature Updates**. However, when referring to this documentation in helping a customer, I discovered that the Signature Updates folder does not exist and instead it should refer to Security Intelligence Updates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e749183d-e3df-466f-786a-c4af4002c05a
* Version Independent ID: a4f1d6a9-43df-fa36-fc1b-18224911b58a
* Content: [Schedule Microsoft Defender Antivirus protection updates - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/manage-protection-update-schedule-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/manage-protection-update-schedule-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/manage-protection-update-schedule-microsoft-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@andrewgiese , thanks for pointing out. I am fixing now

**Comment by denisebmsft** [comment]
Thank you @andrewgiese for opening this issue, and @RAJU2529 for fixing the content.
