### ISSUE TITLE
On this zh-tw page, a sentense misused a zh-cn character

### ISSUE THREAD

**Issue by wbxshiori** [MicrosoftDocs/windows-itpro-docs#8467]
The zh-tw variant of the page contains a "于" in sentence "僅適用于下列裝置：", where it should be "於". "于" here is the way zh-cn uses.  In zh-tw, "于" is barely used except in surnames.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 5b42e708-e334-d434-bcc9-e1860ebb36b3
* Version Independent ID: 92e251c5-8613-ce97-9569-02404c9a466a
* Content: [建立及管理裝置標記 - Windows security](https://docs.microsoft.com/zh-tw/windows/security/threat-protection/microsoft-defender-atp/machine-tags)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/machine-tags.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/machine-tags.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by denisebmsft** [comment]
@TinaMcN can you take a look?

**Comment by TinaMcN** [comment]
@wbxshiori thanks for reporting this.  This page is machine translated and it may be a problem with the machine translation tool.  I searched for 于" in other zh-tw articles on docs.microsoft.com https://docs.microsoft.com/zh-tw/search/?terms=%E4%BA%8E and found numerous examples.  Would many of them also be incorrect?    If so, I can ask the machine translation tool team to investigate.

**Comment by wbxshiori** [comment]
@TinaMcN Sorry for late replay.  For everything I can see in your link, yes, all of them are incorrect.  Please contact the translation tool team.

**Comment by illfated** [comment]
Thank you for the good feedback. Nice to know.

**Comment by TinaMcN** [comment]
@wbxshiori I have passed this on to the machine translation tool and they will investigate it.  I will let you know when there is news on it.

**Comment by TinaMcN** [comment]
@wbxshiori this article is now human translated.  Can you please check if the issue is fixed?  Thank you!
