### ISSUE TITLE
Microsoft Intune hyperlink is broken

### ISSUE THREAD

**Issue by jeffreymcclain** [MicrosoftDocs/windows-itpro-docs#8471]
In the [Deployment and Provisioning](https://docs.microsoft.com/en-us/windows/client-management/manage-windows-10-in-your-organization-modern-management#deployment-and-provisioning) section, the [Microsoft Intune](https://docs.microsoft.com/en-us/intune/understand-explore/introduction-to-microsoft-intune) hyperlink at the end of the first bullet point is broken.

It should probably be changed to a corresponding hyperlink such as the following: https://docs.microsoft.com/en-us/mem/intune/fundamentals/what-is-intune (although I noticed this page also seems to be a bit buggy, after a few seconds it randomly jumps to the "Try the interactive guide" section which seems to include a legacy video player (the play button and control icons look weird).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2dbf610-169d-936a-28d7-f9b8710720b3
* Version Independent ID: ded12365-1392-17d6-6f73-23bbe49ab97b
* Content: [Manage Windows 10 in your organization - transitioning to modern management - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/manage-windows-10-in-your-organization-modern-management#deployment-and-provisioning)
* Content Source: [windows/client-management/manage-windows-10-in-your-organization-modern-management.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/manage-windows-10-in-your-organization-modern-management.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Good point, the MS Intune pages were moved to the /mem/ directory structure during the last couple of years.

What do you think about using the main MS Intune overview page, https://docs.microsoft.com/mem/intune/?

**Comment by jeffreymcclain** [comment]
@illfated Seems reasonable to me, thanks for the quick response!

**Comment by illfated** [comment]
Just as a side note: I opted for the alternate page https://docs.microsoft.com/mem/intune/fundamentals/ for a simpler overview in my PR #8486 -- feel free to comment & suggest in that page.
