### ISSUE TITLE
Why Insider for a Generally Available product?

### ISSUE THREAD

**Issue by RABurnettMCSE** [MicrosoftDocs/windows-itpro-docs#8472]
So why enroll in Insider when mdtap edr is GA for MAC OSX? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c91a5cfb-d32d-3864-c1d5-aec39558f66f
* Version Independent ID: dbd2647e-88a6-ff22-4eab-ef628ac2e605
* Content: [Enable Microsoft Defender ATP Insider Device - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/endpoint-detection-response-mac-preview)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/endpoint-detection-response-mac-preview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/endpoint-detection-response-mac-preview.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
Closing via #8518 
Thanks
