### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by zafodB** [MicrosoftDocs/windows-itpro-docs#8473]
Link on top of page doesn't work (anymore?). Link underneath the title at the beginning of the article doesn't work. The link text is as follows:

`Microsoft Defender Advanced Threat Protection (Microsoft Defender ATP) `

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbabaf85-a345-a91e-f4e2-09c2b7871375
* Version Independent ID: bab57f2f-249a-0fe9-4f4a-93d62ce71670
* Content: [Threat Protection (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/)
* Content Source: [windows/security/threat-protection/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/index.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@zafodB . Thanks for point out. I am fixing it now.

**Comment by illfated** [comment]
For future reference, the resulting error code from the old link is as follows:

`{"Code":"DocumentGone","Message":"StorageDocumentNotFoundException : Document with id 'RE2PBG7', tenant 'am' is now gone (i.e. the document probably expired and thus no longer available).","Resource":null}`

**Comment by e0i** [comment]
Closing via #8475
