### ISSUE TITLE
Wrong supported value for "Update/AutomaticMaintenanceWakeUp"

### ISSUE THREAD

**Issue by ChizuruOkamoto** [MicrosoftDocs/windows-itpro-docs#8474]
Wrong supported value for "Update/AutomaticMaintenanceWakeUp"

The supported value is True or False, but isn't it a mistake of 0 or 1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ca58bd-f279-7739-0140-c4bd56784768
* Version Independent ID: 1d2ecc90-58a3-6bcd-84ae-ef04d7a3b7b4
* Content: [Policy CSP - Update - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update#update-automaticmaintenancewakeup)
* Content Source: [windows/client-management/mdm/policy-csp-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@ChizuruOkamoto , Wrong values are entered,  what you said is correct. i am fixing it now.

**Comment by RAJU2529** [comment]
proof 
![Uploading Capture.JPG…]()

**Comment by nam31** [comment]
Closing via #8476 
Thanks
