### ISSUE TITLE
Windows IT Pro Blog attach

### ISSUE THREAD

**Issue by felizondojr** [MicrosoftDocs/windows-itpro-docs#8479]
Can we add https://techcommunity.microsoft.com/t5/windows-it-pro-blog/bg-p/Windows10Blog to the reference section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcc8a7ec-75d7-894c-9499-cbb4c3807ea7
* Version Independent ID: a4c97095-7c09-1bff-690d-90c8cdeee6c2
* Content: [Get started with Windows Update - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-overview)
* Content Source: [windows/deployment/update/windows-update-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@felizondojr . Ya sure I will add soon

**Comment by illfated** [comment]
@felizondojr : Which reference section did you have in mind? The one in the TOC list?
If so, do you mean as a document in parallel to the page referenced in this ticket?

**Comment by felizondojr** [comment]
To the main reference section

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by illfated** [comment]
Maybe the document is shown differently to me than others. Oh well. I will leave it for Varadharajan to follow up, because I could not find it.

**Comment by nam31** [comment]
Closing via #8592 
Thanks
