### ISSUE TITLE
MDATP Evaluation Lab permissions

### ISSUE THREAD

**Issue by dismembered3po** [MicrosoftDocs/windows-itpro-docs#8480]
Hello,

I'm the lead trainer for an MSSP, and I've been working to provide training to my teams.  As part of that, I would like to be able to leverage the built-in Evaluation Lab abs Simulations/Tutorials to get folks some hands-on experience with the platform.

According to the documentation ([https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/evaluation-lab]), in order for users to access the lab, they need to have the "Manage Security Settings" enabled in their role.

![image](https://user-images.githubusercontent.com/46356358/96284476-3a789900-0fa3-11eb-8570-4072aba33a07.png)

However, regardless of the configurations of my custom user roles, user cannot even see the "Evaluation and Tutorial" section in the console unless they're assigned the default "Microsoft Defender ATP administrator (default)" role, which then gives them access to EVERYTHING.  Even enabling all of the permissions available for a custom role does not work.

![image](https://user-images.githubusercontent.com/46356358/96285516-adceda80-0fa4-11eb-8daa-a6f9205127bd.png)

Is there some other permission somewhere that I need to be looking at for this?  Obviously, I can't give all my users platform admin rights.

Thank you.

**Comment by RAJU2529** [comment]
@dismembered3po. Which article are you referring to?

**Comment by illfated** [comment]
Most likely this page:


---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12e5744d-46dd-7f90-e42e-70caf9dd56d2
* Version Independent ID: 1a627400-9585-e482-3820-e58f6c172a87
* Content: [Microsoft Defender ATP evaluation lab - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/evaluation-lab)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/evaluation-lab.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/evaluation-lab.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by dismembered3po** [comment]
Yeah, it's 

https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/evaluation-lab

For whatever reason it didn't show as a link, and for some reason, it's not letting me add it as a link from my mobile at thus point, either.

**Comment by illfated** [comment]
Fair enough, thanks for confirming. We will just have to wait for someone familiar with the topic, like the document author or the MS Docs technical writers (or possibly other experienced users of the technology) to reply and suggest what needs to be done here.

Please also note that the primary purpose of this repository is to improve the documentation by suggesting improvement changes to the document pages.

**Comment by dismembered3po** [comment]
@illfated 

Fair enough.  I'd be satisfied with either figuring out what I'm missing or with the documentation being updated to reflect what's what.

**Comment by illfated** [comment]
Very well. I would like to take this small opportunity to explain why your URL did not show up as a link in your main post. Here on GitHub, the URLs do not need to be enclosed in brackets to show up as clickable links, you simply post them as they are (use the Preview feature of a post to see when any URL can be read as a clickable link). I don't know whether you are going to use GitHub for other purposes than posting issues you find, but it may come in handy to read about Git Flavored MarkDown (GFM) to see what you can do when editing a post or comment to add practical code blocks or URLs when adding content examples and references.

**Comment by mjcaparas** [comment]
2 conditions must be met for each user to see eval lab:
1.	Sufficient role (‘ViewData’ for RO, ‘Managed security settings’ for RW \ full access)
2.	Must have access to All machine groups, if the tenant has enabled RBAC V2 and created at least a single machine group.

My guess is condition 2 is not met.

**Comment by dismembered3po** [comment]
@mjcaparas  Thanks for the info here.  I'll take another shot at this.

**Comment by dismembered3po** [comment]
@mjcaparas Yep.  That certainly worked better.

I think the documentation should include the information about the device groups, as well.
