### ISSUE TITLE
Is there an intention to support macOS devices with Defender ATP installed?

### ISSUE THREAD

**Issue by mtwelve** [MicrosoftDocs/windows-itpro-docs#8481]
Is there an intention to support macOS devices with Defender ATP installed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162e0510-f05e-14fb-486a-32173e3f8c8c
* Version Independent ID: ead06fb0-e149-32c9-99f2-78f3e51537ea
* Content: [Web protection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/web-protection-overview)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/web-protection-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/web-protection-overview.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Hi @mtwelve it is currently not supported, but the work it is in progress!
