### ISSUE TITLE
Referenced link to the "Sample - gather.ps1" has not been tested on Windows 10

### ISSUE THREAD

**Issue by tim-toolman** [MicrosoftDocs/windows-itpro-docs#8485]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af8c59c3-65e9-1e4c-f78d-8d2770e88690
* Version Independent ID: 0d0b65d8-5026-8232-5658-561d88cc2065
* Content: [Simulate a Windows 10 deployment in a test environment (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/simulate-a-windows-10-deployment-in-a-test-environment?source=docs)
* Content Source: [windows/deployment/deploy-windows-mdt/simulate-a-windows-10-deployment-in-a-test-environment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/simulate-a-windows-10-deployment-in-a-test-environment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Points worth of note:

- https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/simulate-a-windows-10-deployment-in-a-test-environment?source=docs
- (2.) Download the [sample Gather.ps1 script](https://go.microsoft.com/fwlink/p/?LinkId=619361) from the TechNet gallery and copy it to a directory named C:\MDT on PC0001. (https://go.microsoft.com/fwlink/p/?LinkId=619361)
- The go.microsoft.com URL redirects to https://gallery.technet.microsoft.com/Perform-a-standalone-MDT-227fdcd0
- Last updated: 4/10/2014 (April 10, 2014) (!)
- Also worth noting: https://docs.microsoft.com/en-us/teamblog/technet-gallery-retirement (TechNet Gallery Retirement): "We are retiring the TechNet Gallery. Make sure to back up your code. [[Learn More]](https://docs.microsoft.com/teamblog/technet-gallery-retirement)"

**Comment by illfated** [comment]
Also documented on the TechNet Gallery page:

**Verified on the following platforms**

|                        |     |
| ---------------------- | --- |
| Windows 10             | No  |
| Windows Server 2012    | No  |
| Windows Server 2012 R2 | No  |
| Windows Server 2008 R2 | No  |
| Windows Server 2008    | No  |
| Windows Server 2003    | No  |
| Windows Server 2016    | No  |
| Windows 8              | Yes |
| Windows 7              | Yes |
| Windows Vista          | No  |
| Windows XP             | No  |
| Windows 2000           | No  |

**<sub>This script is tested on these platforms by the author. It is likely to work on other platforms as well. If you try it and find that it works on another platform, please add a note to the script discussion to let others know.</sub>**

**Comment by illfated** [comment]
GitHub search for related code: https://github.com/search?l=PowerShell&q=%22Gather.ps1%22&type=Code

We might want to check if MDT Standalone operation could be an issue in Windows 10 deployment.

**Comment by MaratMussabekov** [comment]
Hello,
I checked the content of gather.ps1, and the only thing it does is running ZTIGather.wsf script in debug mode.
As ZTIGather.wsf supports Windows 10 (https://github.com/tyglander/MDT/blob/master/ZTIGather.wsf), I do not see any problem with using it.
Thank you

**Comment by nam31** [comment]
@tim-toolman Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
