### ISSUE TITLE
Please update the ASC requirement - there is no more "standard" tier

### ISSUE THREAD

**Issue by memildin** [MicrosoftDocs/windows-itpro-docs#8487]
Azure Security Center doesn't have a "Standard tier" since Ignite 2020. 
Part of the rebrand was to remove this. 
**Microsoft Defender for Endpoint** is included with **Azure Defender for servers** which is the CWPP integrated inside Azure Security Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by nam31** [comment]
Closed via #8586 
Thanks
