### ISSUE TITLE
How to accomplish the suggested action?

### ISSUE THREAD

**Issue by fred339** [MicrosoftDocs/windows-itpro-docs#8488]
The page says:

> You should not see this event after system startup, so we recommend that you monitor it when it occurs outside the system startup process.

But, it doesn't suggest HOW to do either:
1) monitor it - I'm not seeing any instances of it in the log when there should be.
2) outside the system startup process.  How to limit the time window like this?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b74caf2-50df-c41f-38f5-120604753608
* Version Independent ID: ddf2c109-9983-822f-ed52-12f004e52b6c
* Content: [5025(S) The Windows Firewall Service has been stopped. (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5025)
* Content Source: [windows/security/threat-protection/auditing/event-5025.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-5025.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@fred339 My understanding is that you won't always see Event ID 5025 in Event Viewer. You can try and stop the Firewall service and see if you can generate it, but i doubt it. I was unable to make it appear in System log on a Windows 10 device.

Regarding monitoring, i would recommend looking into Windows Firewall with Advanced Security in Event Viewer. I'm not sure what you're looking for, but this will give you a lot of details, such as:

![image](https://user-images.githubusercontent.com/41186174/98387945-be7de800-205a-11eb-9d02-903ca2725a38.png)


For more details, check this [link](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/ff428140(v=ws.10)?redirectedfrom=MSDN#to-view-events-for-windows-firewall-with-advanced-security-in-event-viewer).

**Comment by nam31** [comment]
@fred339  Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
