### ISSUE TITLE
Setting update

### ISSUE THREAD

**Issue by Jlouden9** [MicrosoftDocs/windows-itpro-docs#8489]
Hi,

Just wondering if the settings around Endpoint detection and response (MDM) in step 5. It references settings that are no longer present.

Cheers
John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4a20ccd-c954-e4f7-07ca-eba122d01340
* Version Independent ID: ee4176d5-3fe6-f65b-6a78-a06f94ae73c0
* Content: [Onboarding using Microsoft Endpoint Manager - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/onboarding-endpoint-manager)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/onboarding-endpoint-manager.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/onboarding-endpoint-manager.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Just to point out visually which section this is:

- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/onboarding-endpoint-manager#endpoint-detection-and-response

***

5.  Select settings as required, then select  **Next**.

    ![Image of Microsoft Endpoint Manager portal](https://github.com/MicrosoftDocs/windows-itpro-docs/raw/public/windows/security/threat-protection/microsoft-defender-atp/images/cea7e288b5d42a9baf1aef0754ade910.png)

    > [!NOTE]
    > In this instance, this has been auto populated as Microsoft Defender ATP has already been integrated with Intune. For more information on the integration, see [Enable Microsoft Defender ATP in Intune](https://docs.microsoft.com/mem/intune/protect/advanced-threat-protection-configure#to-enable-microsoft-defender-atp). <br>
    

    ![Image of Microsoft Endpoint Manager portal](https://github.com/MicrosoftDocs/windows-itpro-docs/raw/public/windows/security/threat-protection/microsoft-defender-atp/images/2466460812371ffae2d19a10c347d6f4.png)

**Comment by VLG17** [comment]
@Jlouden9 I've tested and the interface looks the same for me as in the article. What exactly are you seeing that's different? Could you share a printscreen of that?

**Comment by nam31** [comment]
@Jlouden9  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
