### ISSUE TITLE
no valid endpoint *.windowsupdate.microsoft.com

### ISSUE THREAD

**Issue by tomrydl** [MicrosoftDocs/windows-itpro-docs#8490]
It seems that this endpoint *.windowsupdate.microsoft.com is no longer valid for Windows 10.
pls update this page, especially list of endpoints used for Windows Update https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-troubleshooting#device-cannot-access-update-files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349d337e-ca0f-a40a-a522-bd1ae71c7d1e
* Version Independent ID: 50f0c3b0-eaad-89c0-eb3c-878e7564d6f6
* Content: [Windows Update troubleshooting - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-troubleshooting#device-cannot-access-update-files)
* Content Source: [windows/deployment/update/windows-update-troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-troubleshooting.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by jaimeo** [comment]
@arcarley is this the same issue we had with https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6904#event-3757174356? Does this article need to have the same list as the one referenced in that PR?

**Comment by jaimeo** [comment]
Same/similar issue as https://github.com/MicrosoftDocs/windows-itpro-docs/issues/7917; we now have identified the right SMEs to get us the correct list. We'll put that list in an existing article in the "Prepare" block of articles so people can know earlier in the process which endpoints must work--then we'll link any other references to the list to that article.

**Comment by illfated** [comment]
Related progress? (commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/0f26cd1d82e151cf3d32178ff43837b535bbf219 , direct file link: https://github.com/MicrosoftDocs/windows-itpro-docs/commit/0f26cd1d82e151cf3d32178ff43837b535bbf219#diff-34338e7fe1eae11badcf34e92d170b80b67ac6caef4c38e4e2a40ab59a859d2d)

**Comment by jaimeo** [comment]
@illfated yes this issue should be resolved by the edits in the other PR.

**Comment by Kateyanne** [comment]
@illfated are we able to close this now?

**Comment by illfated** [comment]
Yes, I think we are good to close this ticket. Would have liked to link the related PR to this ticket, but given that it might be one of the internal PRs, it may be out of reach for the general public. As long as the page is updated accordingly, it should be just fine.

**Comment by illfated** [comment]
#please-close
