### ISSUE TITLE
Select "Upload manifest file" - then what

### ISSUE THREAD

**Issue by mbrrg** [MicrosoftDocs/windows-itpro-docs#8493]
When uploading the wdav package the instruction says "Manifest File: Select Upload Manifest File." but there is no manifest file to upload. I suspect this is just a typo and that this piece of the instruction should be removed?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f791dc07-b2c6-3003-a829-cd1ec03a2918
* Version Independent ID: 2c53adbc-600f-60b2-e8b2-b907335f4862
* Content: [Set up the Microsoft Defender ATP for macOS policies in Jamf Pro - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies#step-10-schedule-scans-with-microsoft-defender-atp-for-mac)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
Closing via #8517 
Thanks
