### ISSUE TITLE
Please remove reference to Windows Home Edition

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/windows-itpro-docs#8494]
Submitted a feedback item earlier on whether Windows Home was supported Yes/No. Outcome was No and the github issue closed. see: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8425

Since Windows Home is not supported, please remove any reference on this page.

From the page:
If the same user and device are targeted for both MDM and MAM, the MDM policy will be applied to devices joined to Azure AD. For personal devices that are workplace-joined (that is, added by using Settings > Email & accounts > Add a work or school account), the MAM-only policy will be preferred but it's possible to upgrade the device management to MDM in Settings. _Windows Home edition only supports WIP for MAM-only; upgrading to MDM policy on Home edition will revoke WIP-protected data access._

Thanks in advance,

/Kenneth
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ad3f92-24de-5eb5-8454-c72d85737183
* Version Independent ID: 900125eb-31ea-faf3-ac30-7c3d7b30f611
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @kennethvs ,
I believe the article is correct and no change is required.
Win 10 Home could be used for WIP in MAM-WE deployments.
Please see the comments in the following article: https://techcommunity.microsoft.com/t5/microsoft-intune/windows-information-protection-amp-the-windows-home-edition/m-p/149870
Thank you
