### ISSUE TITLE
No indication where Sandbox config file should be located

### ISSUE THREAD

**Issue by rhanajoy** [MicrosoftDocs/windows-itpro-docs#8496]
The article doesn't say where the Windows Sandbox configuration file should be stored

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2efc9d32-0f98-0804-78a4-4caccdfac010
* Version Independent ID: 797bb0d3-bade-98f6-fe85-508764571f37
* Content: [Windows Sandbox configuration - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@rhanajoy My understainding is that it does not need to be saved somewhere specific. To use the config. file you created, you just double-click it (wherever you saved it) or you invoke it via cmd after you have changed to path to where the config. file is located.

In the example presented in the article, the config. file is located under "Temp" folder.

> C:\Temp> MyConfigFile.wsb
