### ISSUE TITLE
Data gathered is worded with the term such as

### ISSUE THREAD

**Issue by Alslinet** [MicrosoftDocs/windows-itpro-docs#8505]
Since our users are entitled to know what information we collection. Using the term "such as" is not good enough. It needs to be more specific. Or link to more specific information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8444bd2d-358c-0f37-5e23-1a9b6165dfa2
* Version Independent ID: 870991ef-02ac-d15a-c287-b7801c793781
* Content: [Microsoft Defender ATP data storage and privacy - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/data-storage-privacy)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/data-storage-privacy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/data-storage-privacy.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by nam31** [comment]
@Alslinet Thank you for providing feedback.
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
Thank you for your contribution to make the docs better! Much appreciated!
