### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Cryptonewsmedia** [MicrosoftDocs/windows-itpro-docs#8506]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a952d6-62a1-7cc4-c4ff-b67b3c5554bd
* Version Independent ID: e2ca10ed-e883-c924-1b62-17c3c8e6ca64
* Content: [User Account Control (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/user-account-control-overview)
* Content Source: [windows/security/identity-protection/user-account-control/user-account-control-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/user-account-control/user-account-control-overview.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Looks like a test from the docs pages. Very likely that this one can be closed (unless the ticket author posts back).
