### ISSUE TITLE
Add dates

### ISSUE THREAD

**Issue by jmmowrer** [MicrosoftDocs/windows-itpro-docs#8508]
Can dates please be added for each version for when it releases?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 287292d6-355f-5ad8-b29d-3fcc4b2604ca
* Version Independent ID: 1bcc491b-3736-6a85-3551-7aade2ff5f8a
* Content: [What's new in Microsoft Defender Advanced Threat Protection for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-whatsnew)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-whatsnew.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-whatsnew.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
Thank you for providing feedback.
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
Thank you for your contribution to make the docs better! Much appreciated!
