### ISSUE TITLE
Incorrect screenshot in step 4

### ISSUE THREAD

**Issue by dominique97** [MicrosoftDocs/windows-itpro-docs#8509]
[Enter feedback here]
The screenshot for step 4: Configure Notifications settings, sub step 7

the 2nd screenshot shows that the Preferences Domain is "macOS 10.15 [Catalina] or Newer"  this is incorrect.

The preferences domain should be com.microsoft.wdav

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f791dc07-b2c6-3003-a829-cd1ec03a2918
* Version Independent ID: 2c53adbc-600f-60b2-e8b2-b907335f4862
* Content: [Set up the Microsoft Defender ATP for macOS policies in Jamf Pro - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies#step-4-configure-notifications-settings)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
(ref. #8457 )

**Comment by illfated** [comment]
Ref. #8713

**Comment by nam31** [comment]
Closing via #8713 
Thank you
