### ISSUE TITLE
Learn how to configure VPN connections in Microsoft Intune - Dead Link

### ISSUE THREAD

**Issue by ianc911** [MicrosoftDocs/windows-itpro-docs#8510]
The link "Learn how to configure VPN connections in Microsoft Intune" in the "Learn More" section is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79add4e0-6997-5b15-542c-be3f1c2b1baf
* Version Independent ID: 47bd5f53-cd36-3205-42b1-6d99c68e9b39
* Content: [VPN profile options (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-profile-options)
* Content Source: [windows/security/identity-protection/vpn/vpn-profile-options.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/vpn/vpn-profile-options.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
Closing via #8561 
Thanks
