### ISSUE TITLE
EDR BLock Mode GA

### ISSUE THREAD

**Issue by pulporange** [MicrosoftDocs/windows-itpro-docs#8511]
[EDR in Block Mode seems to be out of Preview ?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8da58e5-9cd8-8ccf-75a9-327c14ebaa76
* Version Independent ID: 24a29218-59e1-7a1d-c8c7-e61424b5f9ee
* Content: [Endpoint detection and response in block mode - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/edr-in-block-mode)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/edr-in-block-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/edr-in-block-mode.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thank you @pulporange for the feedback! I've updated the content, and my changes will be live later today.
