### ISSUE TITLE
Why AMD CPUs are not included?

### ISSUE THREAD

**Issue by TSparkas** [MicrosoftDocs/windows-itpro-docs#8514]
Hello,

Why AMD CPUs are not included in this documentation? In this article it's stated that AMD also supports System Guard Secure Launch: https://www.microsoft.com/security/blog/2020/09/01/force-firmware-code-to-be-measured-and-attested-by-secure-launch-on-windows-10/

Regards,
Tomas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31d623d9-316c-0ef1-b6be-c3773d77ca21
* Version Independent ID: 83ddb59d-0cfc-34f2-e666-8927d86a04a7
* Content: [System Guard Secure Launch and SMM protection (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection?source=docs)
* Content Source: [windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@TSparkas I've created a request to add a note about AMD processors (via the link you shared) until a separate section will get created and added to the article. Hope this is ok with you.

**Comment by e0i** [comment]
Closing via #8870. Thanks.
