### ISSUE TITLE
Create an NDES-Intune authentication certificate template

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#8515]
Hello,

I guess we must select an object Computer and select the computer and not the group? Or group?
Step: "8. Type NDES server in the Enter the object names to select text box and click OK."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f709fd4-0b5d-b238-4060-222d550cd538
* Version Independent ID: fb3f29da-2236-c47d-6bea-8efbcec8d7d3
* Content: [Using Certificates for AADJ On-premises Single-sign On single sign-on - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by VLG17** [comment]
@lightupdifire It's the computer account. I think [this article](https://techcommunity.microsoft.com/t5/intune-customer-success/support-tip-how-to-configure-ndes-for-scep-certificate/ba-p/455125) provides more details:

The certificate should include both client and server authentication under Extensions tab -> Application policies. On the Security tab, **the computer account of the NDES server** should have Read and Enroll permission:

![image](https://user-images.githubusercontent.com/41186174/100010336-cbc80000-2dd8-11eb-8394-890e90409232.png)

**Comment by lightupdifire** [comment]
@VLG17 
Worked by selecting Group that contains NDES computer object.
