### ISSUE TITLE
SCEP certificate | InternalServerError

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#8519]
Hello,
Deploying SCEP certificate receive an error:
<<<
{ "error": { "code": "InternalServerError", "message": "{\r\n \"_version\": 3,\r\n \"Message\": \"An internal server error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: xxx - 
Url: https://fef.msub06.manage.microsoft.com/DeviceConfiguration_2010/StatelessDeviceConfigurationFEService/deviceManagement/deviceConfigurations?api-version=5020-08-21\",\r\n \"CustomApiErrorPhrase\": \"\",\r\n \"RetryAfter\": null,\r\n \"ErrorSourceService\": \"\",\r\n \"HttpHeaders\": \"{}\"\r\n}", 
"innerError": { "date": "2020-10-22T13:18:26", "request-id": "xxx", "client-request-id": "xxx" } }}
>>>
Is it something known? any clue why error can be?

**Comment by denisebmsft** [comment]
Hello! To which article(s) does your feedback apply? This information will help us route the issue to the correct writer/team.

**Comment by lightupdifire** [comment]
@denisebmsft 
It was this:
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert
Seems too many tabs dropped link :)

**Comment by VLG17** [comment]
@lightupdifire Did you specify the UPN for SAN in the form {{UserPrincipalName}}? This could have an impact.

Also, i see you also opened a [support request](https://docs.microsoft.com/en-us/answers/questions/136690/intune-windows-hello-for-business-scep-aadj-whfb-c.html) regarding this issue. What was the outcome? Should we add something to the documentation about this?
