### ISSUE TITLE
AzureAD\Emailaddress

### ISSUE THREAD

**Issue by cashew76** [MicrosoftDocs/windows-itpro-docs#8523]
FYI in case you did not know.  RDP does work when auth via AzureAD\Emailaddress

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10) - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@cashew76 I guess this was fixed in the documentation. At the moment the article references only:

AzureAD\the-UPN-attribute-of-your-user and AzureAD\yourloginid@domain.com

I don't see AzureAD\Emailaddress being presented as an option in the article.

**Comment by illfated** [comment]
I assume that the ticket creator may have based the statement on a scenario where AzureAD\Emailaddress is identical to AzureAD\yourloginid@domain.com
