### ISSUE TITLE
Wrong data type of DisableEnhancedNotifications

### ISSUE THREAD

**Issue by hdc0** [MicrosoftDocs/windows-itpro-docs#8526]
The data type of `DisableEnhancedNotifications` should be `REG_DWORD`, not `REG_SZ`.

**Comment by RAJU2529** [comment]
@hdc0 which article are you referring!

**Comment by hdc0** [comment]
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md

**Comment by RAJU2529** [comment]
@hdc0.  thanks for reporting. i am fixing the error now.

**Comment by nam31** [comment]
Closing via #8533 
Thank you
