### ISSUE TITLE
Changes already integrated

### ISSUE THREAD

**Issue by gruppenrichtlinien** [MicrosoftDocs/windows-itpro-docs#853]
New 1803:
- Added a policy to turn off notifications network usage
It´s already in, see 9. Live Tiles and 17.5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8228962-7158-6be1-e791-e6535b88f343
* Version Independent ID: 46e4c7f3-e8b0-ebc9-da58-b69149803937
* Content: [Manage connections from Windows operating system components to Microsoft services (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/manage-connections-from-windows-operating-system-components-to-microsoft-services#feedback)
* Content Source: [windows/configuration/manage-connections-from-windows-operating-system-components-to-microsoft-services.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/manage-connections-from-windows-operating-system-components-to-microsoft-services.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic-msft**

**Comment by brianlic-msft** [comment]
@gruppenrichtlinien can you provide more info here?

**Comment by gruppenrichtlinien** [comment]
On the list:
What's new in Windows 10, version 1803 Enterprise edition
Here's a list of changes that were made to this article for Windows 10, version 1803:
- Added a policy to turn off notifications network usage

You added this point, but this policy is already there since 1607/1703 or 1709. The same policy is defined in point 9. Live Tiles and again "new in 1803" under 17.5

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by lindspea** [comment]
@gruppenrichtlinien Thank you for reaching out and helping improve MS docs.  Please can you clarify if there is something that needs to be amended in the document?

**Comment by mypil** [comment]
@gruppenrichtlinien - can you please assist to give updates on the clarification question from lindspea? Thank you.

**Comment by gruppenrichtlinien** [comment]
@mypil. sorry. I was wrong. The name of the policy is identical, but not the setting itself. I mixec it up.
10.: User Configuration > Administrative Templates > Start Menu and Taskbar > Notifications > Turn Off notifications network usage
18.5.: Computer Configuration > Administrative Templates > Start Menu and Taskbar > Notifications > Turn off Notifications network usage

**Comment by illfated** [comment]
@gruppenrichtlinien : Feel free to close this ticket, since your issue appears to be resolved.
