### ISSUE TITLE
Ransomware (German Version)

### ISSUE THREAD

**Issue by Felix-B1** [MicrosoftDocs/windows-itpro-docs#8531]
My Feedback (German Version): / Mein Feedback (Deutsche Version)
https://docs.microsoft.com/de-de/windows/security/threat-protection/intelligence/ransomware-malware
--
Unter "Schutz vor Ransomware" steht:
- Informieren Sie Ihre Mitarbeiter, damit Sie Social-Engineering-und Speer-Phishing-Angriffe erkennen können.

Bei dem Wort "Speer-Phishing" hat sich ein "e" eingeschlichen. Spear-Phishing müsste es heißen.

Ich würde noch den Punkt "Ransomware identifizieren / entschlüsseln" hinzufügen.

Man könnte es zum Beispiel folgendermaßen formulieren:
---
Ransomware identifizieren / entschlüsseln
Für einige Ransomware-Varianten existieren Entschlüsselungsprogramme, die die verschlüsselten Dateien ohne Lösegeldzahlung entschlüsseln können. Diese Programme werden von Firmen aus dem Sicherheitsbereich entwickelt, sobald eine Schwachstelle  entdeckt wird. 

Über die nachfolgenden Internetseiten können Ransomware-Opfer prüfen, ob es ein passendes Enschlüsselungsprogramme für ihren persönlichen Fall gibt:

https://id-ransomware.malwarehunterteam.com/
https://www.nomoreransom.org/
https://www.bleib-virenfrei.de/it-sicherheit/ransomware-liste/
---

Die Links werden im Wikipedia Artikel "Ransomware" unter "Bestimmung von Ransomware" empfohlen. Ich halte diese ebenfalls für sinnvoll.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b3640220-fd9e-74e2-2c54-d01b7e68a76d
* Version Independent ID: e4c3923e-88e4-93b7-b717-2b91ec838ad9
* Content: [Ransomware - Windows security](https://docs.microsoft.com/de-de/windows/security/threat-protection/intelligence/ransomware-malware)
* Content Source: [windows/security/threat-protection/intelligence/ransomware-malware.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/ransomware-malware.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by illfated** [comment]
@TinaMcN : The reported issue is that the expression "spear-phishing" becomes halfway translated ("Speer-Phishing-Angriffe") where the expression "spear phishing" should not be translated in German. It is a loanword used in many languages to differentiate the IT technical term from the hunting method, but I have not confirmed this other than in Scandinavian languages and in German.

Reported section : **Schutz vor Ransomware** (How to protect against ransomware)

- https://docs.microsoft.com/de-de/windows/security/threat-protection/intelligence/ransomware-malware#schutz-vor-ransomwarehow-to-protect-against-ransomware

> - Informieren Sie Ihre Mitarbeiter, damit Sie Social-Engineering-und **Speer**-Phishing-Angriffe erkennen können.

@Felix-B1 : Thank you for reporting this translation issue, which will be taken care of by the MS Docs translation team members.

(Vielen Dank, dass Sie dieses Übersetzungsproblem gemeldet haben, das von den Mitgliedern des MS Docs-Übersetzungsteams betreuen wird.)

Please note: Microsoft will not add external links to their documentation pages, unless the page already contains external security links or the suggested link(s) belong to a well-known Microsoft Partner organization. Also note, regarding suggestions for adding content to a page, please use the English (/en-us/) pages to open a ticket (in English) to suggest improvement changes.

(Bitte beachten Sie: Microsoft fügt seinen Dokumentationsseiten keine externen Links hinzu, es sei denn, die Seite enthält bereits externe Sicherheitslinks oder die vorgeschlagenen Links gehören einer bekannten Microsoft Partner-Organisation an. Beachten Sie auch, dass Sie in Bezug auf Vorschläge zum Hinzufügen von Inhalten zu einer Seite bitte die englischen (/en-us/) Seiten verwenden, um ein Ticket (in englischer Sprache) zu öffnen, um Verbesserungsänderungen vorzuschlagen.)

**Comment by TinaMcN** [comment]
@Felix-B1 Vielen Dank, dass Sie über dieses Problem berichtet haben. Es scheint ein Problem mit unserem maschinellen Übersetzungstool zu sein. Ich schickte den Artikel, um von Menschen übersetzt zu werden.  @officeglobal, bitte lassen Sie es uns wissen, wenn der aktualisierte Artikel veröffentlicht wird.
(Thank you for reporting this issue. It appears to be a problem with our machine translation tool. I sent the article to be human translated. @officeglobal, please let us know when the updated article is published.)

**Comment by TinaMcN** [comment]
@Felix-B1 Da Sie bereits früher hervorragendes Feedback zu den Inhalten der deutschen Dokumente gegeben haben, wollte ich Sie darüber informieren, dass wir ein Pilotprojekt starten, um Community-Bearbeitung (PRs) und Feedback (Probleme) zu den Inhalten der deutschen Version von Microsoft Teams (https://docs.microsoft.com/de-de/microsoftteams/teams-overview)  zu ermöglichen. Wir haben einen deutschen Linguisten in Bereitschaft, der im Dezember und Januar alle Vorschläge überprüfen wird.
Wenn Sie Zeit haben, sich die Übersetzungsqualität der Inhalte der deutschen Version von Teams anzusehen, würden wir uns über Ihr Feedback freuen. Beachten Sie, dass der Inhalt eine Mischung aus von Menschen übersetzten und teilweise maschinell übersetzten Artikeln ist – die MT-Artikel haben oben ein lila Banner. Die Bearbeitungsfunktion wird nur für von Menschen übersetzte Artikel aktiviert sein. Wenn Sie noch jemanden kennen, der interessiert sein könnte, uns zu helfen, können Sie diese Information gerne weiterleiten.
Mit freundlichen Grüßen
Tina
Lokalisierungsmanager für Dokumentinhalte für Teams, M365, Windows, SharePoint, Exchange, Microsoft Edge, Surface usw.

**Comment by levinec** [comment]
@TinaMcN @OfficeGlobal @Felix-B1 @illfated is this issue resolved? Can it be closed?

**Comment by illfated** [comment]
Looks resolved to me, the phrase "Spear-Phishing-Angriffe" is correctly named as 'Spear' instead of "Speer".

Would be nice to have the necessary changes confirmed by the ticket author @Felix-B1 , though.

**Comment by levinec** [comment]
I closed this issue because it seemed resolved. @Felix-B1 please comment here if you think this issue still needs work.
