### ISSUE TITLE
Elaborate on Device Credential vs User Credential supportability

### ISSUE THREAD

**Issue by daduckMSFT** [MicrosoftDocs/windows-itpro-docs#8532]
Can we reiterate, in this document, how the GPO's "User Credential" is the only supported option for Intune at this time - and that Device Credential works, but is not yet supported for Intune (and might be for other MDM's?)

Some of the information is confusing in here, and having this clarified would be ideal. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy?source=docs#)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @daduckMSFT ,
could you please have a look at PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8605?
Thank you

**Comment by daduckMSFT** [comment]
Looks great! Thank you! 👍

**Comment by daduckMSFT** [comment]
Actually - a quick glance - it looks like this is mentioned: 

**Device Credential** Credential Type will also work, however, it is not yet supported for MDM solutions (including Intune) yet. It is not recommended to use this option until support is announced.

I don't know if this is correct; I added a review, but I'm not sure if this is the right process to go with for these doc updates. I believe that this option might be supported for other MDM's, but not Intune officially yet.

**Comment by MaratMussabekov** [comment]
Hello @daduckMSFT ,
how about:
**Device Credential** Credential Type will also work, however, it is not supported by Intune yet. It is not recommended to use this option until support is announced.

Does it look better?

Thank you

**Comment by nam31** [comment]
@daduckMSFT can you please give your input ?

**Comment by daduckMSFT** [comment]
I think a better terminology here would be something such as:

Device Credential Credential Type may also work; however, it is not supported by Intune yet. It is not recommended to use this option until support is announced.
________________________________

**Comment by nam31** [comment]
Closing via #8746 
Thank you
