### ISSUE TITLE
Policies tab hidden

### ISSUE THREAD

**Issue by p-p-s** [MicrosoftDocs/windows-itpro-docs#8535]
I can open the Properties for my USB device from the Disk Management window, but that small Properties window looks quite different. In particular it has no Policies tab. But it has a Hardware tab with a small table "All disk drives:" and in there the USB drive is shown as Samsung Portable SSD T5 SCSI Disk Device. When I select it in the table I can click a Properties button below the table and that shows your Properties window with the Policies tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 844ba8b2-4c73-698b-80f8-68bb2d272d4c
* Version Independent ID: 05847067-81fe-17ea-5e61-2346c90c5fe2
* Content: [Windows 10 default media removal policy - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/change-default-removal-policy-external-storage-media)
* Content Source: [windows/client-management/change-default-removal-policy-external-storage-media.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/change-default-removal-policy-external-storage-media.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by VLG17** [comment]
@p-p-s I have tested and i can reproduce what you're seeing. I'll create a request to update the content.

**Comment by Teresa-Motiv** [comment]
Fix is live.
#please-close
