### ISSUE TITLE
Update/DetectionFrequency Info

### ISSUE THREAD

**Issue by rkremkau** [MicrosoftDocs/windows-itpro-docs#8537]
@arcarley Would it be possible to have the Policy CSP description include the same info as GPO for Detection Frequency, specifically:

Note: If the "Configure Automatic Updates" policy is disabled, this policy has no effect.

This is indicated if the admin references: Update/UpdateServiceUrlAlternate but many likely don't.

Also, can the specific values be noted for the policy. Values for frequency (Enabled and 1-22), Disabled and Not Configured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ca58bd-f279-7739-0140-c4bd56784768
* Version Independent ID: 1d2ecc90-58a3-6bcd-84ae-ef04d7a3b7b4
* Content: [Policy CSP - Update - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update#update-detectionfrequency)
* Content Source: [windows/client-management/mdm/policy-csp-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @rkremkau - Thank you for your query regarding the document. Please note that all of the CSPs are written in a uniform format. Keeping that in view, the requested information can not be added to the document. The document has the necessary description for this and other CSPs.

@e0i FYI&A Please.

Thanks.
Imran.
