### ISSUE TITLE
Use Group Policy to hide the Microsoft Defender AV interface from users

### ISSUE THREAD

**Issue by chibs89** [MicrosoftDocs/windows-itpro-docs#8547]
Is it planned to make this available as  an user gpo?
If we set it and log on as an administrator, we can't controll the Settings or findings of the defender via GUI on the machine.
Since Microsoft has decided to make Windows Security available for all Users as an extra Appx Shortcut in the Startmenu we have can't restrict the Users from using it. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 117e0cad-123d-5b77-3879-1b4e08271b1c
* Version Independent ID: 13bca309-67d1-5fa4-628d-2ef6f84a70d0
* Content: [Ausblenden der Antivirus-Oberfläche von Microsoft Defender - Windows security](https://docs.microsoft.com/de-de/windows/security/threat-protection/microsoft-defender-antivirus/prevent-end-user-interaction-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/prevent-end-user-interaction-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/prevent-end-user-interaction-microsoft-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@chibs89 thank you for posting this question. I'm looking into this.

**Comment by denisebmsft** [comment]
Hello @chibs89. See this article for hiding the Microsoft Defender Antivirus interface from users: [Use Group Policy to hide the Microsoft Defender AV interface from users](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-antivirus/prevent-end-user-interaction-microsoft-defender-antivirus#use-group-policy-to-hide-the-microsoft-defender-av-interface-from-users)

If that does not work, please contact technical support.

**Comment by chibs89** [comment]
Like I said. This Group Policy is just a computer policy and does prevent the admin user also to access the Microsoft Defender AV and the answer is to set the same computer policy? The Problem is, that Microsoft removes the working control panel step by step to the new fancy looking Settings Apps.
