### ISSUE TITLE
Error 500 if no Value for UPN is given

### ISSUE THREAD

**Issue by w3p706** [MicrosoftDocs/windows-itpro-docs#8548]
I discovered in Step "Create a SCEP Certificate Profile" > Point 14, that if you do not provide a value to the SAN UPN Setting like `{{UserPrincipalName}}` saving of the profile will fail with error 500 / InternalServerError
I tried at least 5 times which all of them failed until I provided a value for the upn.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f709fd4-0b5d-b238-4060-222d550cd538
* Version Independent ID: fb3f29da-2236-c47d-6bea-8efbcec8d7d3
* Content: [Using Certificates for AADJ On-premises Single-sign On single sign-on - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert#prepare-the-network-device-enrollment-services-ndes-service-account)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by lightupdifire** [comment]
@w3p706 
I have the same issue. Tested with {{UserPrincipalName}} and with CN={{UserPrincipalName}}, but policy stuck in "Pending" and not apply to device. have u managed to deploy the policy to the device if use {{UserPrincipalName}}?

**Comment by w3p706** [comment]
The issue with pending is not related to the SAN. There is somewhere
documented a requirement that the policy for the SCEP and the CA
certificate must have the same assignment. When I used the same group for
the CA-Policy instead of all devices it began to work.
Im on mobile so I‘m cuttently not able to provide a reference.

{{UserPrincipalName}} as SAN worked fine for me.

**Comment by lightupdifire** [comment]
@w3p706 
Thanks, will revert back to {{UserPrincipalName}}, but it was already created like this, and then I got only "Pending" status... Will try to play with groups like u say.
If possible to ask, your Windows 10 device, does it has a network connectivity to the on-prem domain and NDES server?

**Comment by w3p706** [comment]
@lightupdifire 
The solution that made my profile get applied is described here: [Requirement to have "Trusted Root profile" group assignment same as one used for SCEP profile](https://github.com/MicrosoftDocs/IntuneDocs/issues/2252)

My test machine does have local connectivity. But I did not see any https requests in the IIS-logs of the NDES server up until the profiles were assigned the same group. I had an other problem in the permission of the cert template, an this caused the profile to show as failed. 

So if the state is "pending" the profile does not reach the client , if the state of the profile is "failed" there is a problem with the enrollment of the profile (application proxy => ndes-server => ca).

**Comment by illfated** [comment]
(ref. #8597)

**Comment by lightupdifire** [comment]
@w3p706 
FYI. for me the {{UserPrincipalName}} worked too.

**Comment by illfated** [comment]
That seems to be the suggested solution in the PR (#8597 ) linked above. Feel free to comment in that PR if you find that it needs even more improvement.

**Comment by illfated** [comment]
To me, it looks like the PR #8732 (commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/13294d73d61a328ace8df07518939a88077b87d2) has already added the necessary change to that line, as well as modified the preceding text:
```PowerShell
12. Specify **User Principal Name (UPN)** as a **Subject Alternative Name** parameter. Set its value as {{UserPrincipalName}}.
```
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/5d460c78b68d3ffe04baeb29f672134f584754e4/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md#L653-L655

@lightupdifire : Could you confirm if commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/13294d73d61a328ace8df07518939a88077b87d2 solves your issue with this page?
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md#create-a-scep-certificate-profile

**Comment by illfated** [comment]
@w3p706 : Sorry, forgot that this is your issue ticket. Are you available to confirm my comment content above?

**Comment by illfated** [comment]
This issue ticket is resolved by content added in PR #8732 .

**Comment by illfated** [comment]
#please-close

**Comment by nam31** [comment]
Closing via #8732 
Thank you
