### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by gutjahr** [MicrosoftDocs/windows-itpro-docs#855]
The word 'joint' in 'create a new local Windows account and joint it to a local user group' has an extra 't'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 309bae29-c769-5051-6c3f-aebeb455cd34
* Version Independent ID: bbdfad82-025e-8aee-b3fc-bcfb8b110674
* Content: [Accounts CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/accounts-csp)
* Content Source: [windows/client-management/mdm/accounts-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/accounts-csp.md)
* Service: **unspecified**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by andreabichsel** [comment]
Fixed--thank you!
