### ISSUE TITLE
Missing User Right - Obtain an impersonation token for another user in the same session

### ISSUE THREAD

**Issue by ixtlanian** [MicrosoftDocs/windows-itpro-docs#8551]
User Right **_Obtain an impersonation token for another user in the same session_**, which is available in Windows 10, Windows Server 2016/2019 is not documented.
Please document and also, if possible, please provide a table of user rights by OS version (2012-2019), including default OOB user rights assignments.
It would be good to understand how user rights and user rights assignment evolve from version to version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7de1fb45-91eb-f37f-8106-81bf82a5602e
* Version Independent ID: 1c765989-4c50-4b89-83fe-a8625f0f9fd5
* Content: [User Rights Assignment (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-rights-assignment)
* Content Source: [windows/security/threat-protection/security-policy-settings/user-rights-assignment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/user-rights-assignment.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @ixtlanian - Thank you for your query. I have reviewed the document and found that the document has the necessary relevant information. For your specific query, please see https://social.technet.microsoft.com/Forums/windows/en-US/999dedb8-c6fa-4f2f-a5ca-e48f43bc956e/user-rights-assignment-obtain-an-impersonation-token-for-another-user-in-the-same-session?forum=ws2016

Also, I would like to suggest you open a request on a user voice channel for a separate document required as you mentioned. 

@e0i  will guide you on how to open a user voice request. 

Thanks.
Imran.

**Comment by ixtlanian** [comment]
Imran, you did not provide any explanation on the missing user right. THe document does not contain the user right I mentioned. There cannot possibly be a separate document for this as it's clearly a mistake in this document. Please assign this issue to the owner of the document.

**Comment by illfated** [comment]
(ref. #8902 )

**Comment by ixtlanian** [comment]
I would like to check that this was closed correctly.
**Obtain an impersonation token for another user in the same session** was indeed added to the list of User Rights.
However, the hyperlink on that item leads to the article on **Impersonate a client after authentication**, which is a different User Right.

**Comment by Damien-Sugden** [comment]
This is still very much an issue and should not be closed at all.

There's a page that lists all the User Rights Assignment elements and their meanings here:
https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-rights-assignment

Within that page, there is an entry for:

Obtain an impersonation token for another user in the same session

The link for that entry is wrong. it is linking to:

https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/impersonate-a-client-after-authentication

..Which is wrong - This is a completely different User Right Assignment (fir impersonate a client after authentication).
The page for the right the OP has listed is missing.

**Comment by JimSycurity** [comment]
This is still an issue and should not have been closed.  See comment above from Damien-Sugden for a detailed explanation of what is still incorrect in the docs.
