### ISSUE TITLE
Helpful DISM hint

### ISSUE THREAD

**Issue by Jason-Slater** [MicrosoftDocs/windows-itpro-docs#8553]
When using the DISM command within a task sequence running PS the following path to cmd.exe is required.
Example:
    c:\windows\sysnative\cmd.exe /c Dism /online /Get-FeatureInfo /FeatureName:Windows-Defender-Features
    c:\windows\sysnative\cmd.exe /c Dism /online /Get-FeatureInfo /FeatureName:Windows-Defender

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bae59608-208f-5cec-39a4-95466faa0646
* Version Independent ID: 20c0ab0d-fb2b-3d79-3fcb-d555fc95db14
* Content: [Symantec to Microsoft Defender for Endpoint - Phase 2, Setting Up - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-setup)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-setup.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/symantec-to-microsoft-defender-atp-setup.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @Jason-Slater and thank you for the feedback! I am looking into this.

**Comment by illfated** [comment]
Cool. I was unaware of this virtual link feature in Windows 10.

**Comment by e0i** [comment]
Addressed via commit, https://github.com/MicrosoftDocs/windows-itpro-docs/commit/3ce9d29020d43cec8f85f734293c61e7d4e54453#diff-d86914a1852d8b6dce5c0e010552158c271495f73b42c5b47ff81a4574e8cb4d Thank you.

**Comment by illfated** [comment]
(just to add the commit link for easier hover view of the commit name info & date of the commit: https://github.com/MicrosoftDocs/windows-itpro-docs/commit/3ce9d29020d43cec8f85f734293c61e7d4e54453)
