### ISSUE TITLE
Procedure to install ADMX templates is seriously flawed

### ISSUE THREAD

**Issue by pv2b** [MicrosoftDocs/windows-itpro-docs#8557]
In the section "Configure the auto-enrollment for a group of devices", there is a procedure for downloading and installing Administrative Templates into the central group policy store of a domain controller. First of all, I think it's a bit questionable to even be including this information in-line in the procedure, since it clutters the document, especially when the advice given to how to perform the procedure is a bit misleading.

Step 1 provides download links to an MSI containing the ADMX files for recent versions of Windows 10. This is fine, but it would be helpful to give some kind of advice about which version of the ADMX files to download in case you have a mixed environment. Why would you want to download earlier ADMX files, and is there any downside to download later ones? If not, maybe best to just provide a link to the latest, or even better to a page that will always contain the latest versions, so this document does not need to be continually kept up to date with new Windows 10 versions.

Step 2 provides the advice "Install the package on the Domain Controller". No! Unneccessary software should never be installed on the domain controller, and there is in fact no reason to directly touch the domain controller in this case. Why Microsoft decides to distribute what amounts to just a folder of files that needs to be manually copied into another location as an MSI file is beyond me, but there's no reason to "install" it on the DC. This will be especially clunky if the DC is running Windows Server Core. This step should be changed to installing the package on any machine you like. It doesn't matter. It's just an archive of files.

Step 3 provides the advice to navigate to the correct directory. This is fine I guess.

Step 4 provides the advice to "Rename the extracted Policy Definitions folder to PolicyDefinitions.". This makes no sense, the folder is already labelled PolicyDefinitions and does not need to be renamed.

Step 5 provides the advice to "Copy PolicyDefinitions folder to C:\Windows\SYSVOL\domain\Policies.". Again, this is counter to reasonable practices. This ignores that the SYSVOL folder may be on another drive, and also encourages working directly on the Domain Controller, which is not neccessary. Instead, this process should instruct the user to copy the files into \\\\contoso.com\SYSVOL\contoso.com\Policies (replacing contoso.com with the domain FQDN.) It correctly then notifies the user of the implications of doing this, linking out to an article. This also completely ignores the possibility of there already being a PolicyDefinitions folder. Fortunately, the linked article (https://docs.microsoft.com/en-us/troubleshoot/windows-client/group-policy/create-and-manage-central-store) provides better guidance.

Step 6 provides the advice to "Restart the Domain Controller for the policy to be available." No. Not only is this unneccessary, but it can actually delay the process of DFS-R replication of SYSVOL to other domain controllers, since it's possible that the administrator reboots the domain controller in the middle of SYSVOL replication. This would mean that SYSVOL replication would pause, leaving an incomplete set of PolicyDefinitions on other domain controllers, leading to unexpected behaviour until the DFS replication process has resumed. In addition, requiring this unneccessary step will make the deployment more complicated, requiring a scheduled outage of the domain controller. This step should just be skipped entirely, alternatively it should instead recommend waiting until SYSVOL DFSR replication has completed.

In summary, the procedure given for deploying a central group policy store does not adhere to reasonable practices. It encourages working directly on the domain controller, including installing an MSI package onto it, it calls for writing directly to the C:\WINDOWS\SYSVOL folder, when it's just as good to just write the data through the \\\\CONTOSO.COM\SYSVOL path from any administrative workstation in the domain, it gives no advice for how to handle a pre-existing PolicyDefinitions folder, and contains other minor errors.

The worst part is that this entire section of documentation is entirely unneccessary and introduces a burden to keep that section up to date. Whoever wrote this section already knows about the document "How to create and manage the Central Store for Group Policy Administrative Templates in Windows" (https://docs.microsoft.com/en-us/troubleshoot/windows-client/group-policy/create-and-manage-central-store) since this is already linked from the article in question.

My suggestion is to simply delete the entire subsection in the document with the flawed procedure for creating a central store for Group Policy Administrative Templates, and replace it to a link to the much better and more complete "How to create and manage the Central Store for Group Policy Administrative Templates in Windows" document as part of the prerequisites.

This will make the document easier to read (because it does not clutter the document with unneccesary basic Windows Server admin knowledge) and will also make it easier to maintain, since you do not duplicate information about how to manage a central store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy#configure-the-auto-enrollment-for-a-group-of-devices)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
( ref. #9419 )
