### ISSUE TITLE
Delete "Configure the auto-enrollment Group Policy for a single PC" section

### ISSUE THREAD

**Issue by pv2b** [MicrosoftDocs/windows-itpro-docs#8558]
Hello.

The entire section "Configure the auto-enrollment Group Policy for a single PC" should be merged into the "Configure the auto-enrollment for a group of devices", by replacing the procedure using Local Group Policy with one just using Group Policy.

As you correctly suggest yourselves, using Local Group Policy to auto-enroll a PC is not a recommended procedure. Instead, for testing with a limited scope of devices, why not simply recommend them to use Group Policy linked to an OU or with the appropriate security filtering?

As it stands, this section is simply cluttering the document with a procedure that the author themselves acknowledge is inadvisable. Just delete it. If someone has a valid reason to use Local Group Policy (such as not wanting to be burdened by change control procedures regarding Group Policy just for testing purposes), they'll already know how to do it, and can adapt the procedure for using Group Policy without it being explicitly documented, cluttering the document's primary purpose.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello,
Even though it is not recommended, it is supported, so it should be covered in docs.
Also, this method allows to join computers in scenarios where AD is not integrated with Azure AD.
I believe it shouldn't be deleted, as long as it is clearly noted that the method is not advisable.

Thank you
