### ISSUE TITLE
Windows value strings for 20H2...

### ISSUE THREAD

**Issue by steve-prentice** [MicrosoftDocs/windows-itpro-docs#8559]
For "Update/TargetReleaseVersion" it says "Value type is a string containing Windows 10 version number. For example, 1809, 1903.".

What would the value be for 20H2... would it be 20H2, or would it be 2010? Just for clarity please.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ca58bd-f279-7739-0140-c4bd56784768
* Version Independent ID: 1d2ecc90-58a3-6bcd-84ae-ef04d7a3b7b4
* Content: [Policy CSP - Update - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update#update-targetreleaseversion)
* Content Source: [windows/client-management/mdm/policy-csp-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@steve-prentice . I think , it should be 2010 , not 20H2

**Comment by illfated** [comment]
@steve-prentice , @RAJU2529 : Please note the [Windows 10 release information](https://docs.microsoft.com/windows/release-information/) page information:

***

#### Windows 10 release history

Learn more about the contents of Windows 10 updates at Windows 10 Update History.

▶ **Version 20H2 (OS build 19042)**
▶ **Version 2004 (OS build 19041)**
▶ **Version 1909 (OS build 18363)**
▶ **Version 1903 (OS build 18362)**
▶ **Version 1809 (OS build 17763)**
▶ **Version 1803 (OS build 17134)**
▶ **Version 1709 (OS build 16299) - End of service**
▶ **Version 1703 (OS build 15063) - End of service**
▶ **Version 1607 (OS build 14393)**
▶ **Version 1511 (OS build 10586) - End of service**
▶ **Version 1507 (RTM) (OS build 10240)**

***

Also note: 
- **20H2** looks less like a recent year number (i.e. 2020, which could lead to people saying "This is the 2020 version, the only version released in 2020."), also to keep it different from 2004 (which in theory could have been 20H1 ).
- **2004** (theoretical 20H1) is at least different from 2003, which was a Windows Server version.

**Comment by steve-prentice** [comment]
Thanks illfated, although that doesn't answer the question at all.

After trying it myself, turns out RAJU2529 was basically right... the answer was 2009.... so I guess the 20H2 memo didn't get as far as the CSP and registry. ;-)

**Comment by illfated** [comment]
Fair enough. Thanks for the feedback. Are you sure about the value 2009? It does not seem to belong in any lists, unless it is about some unusual or rare software package, like Delphi 2009 (from the year 2008).

Oh well. There are likely more version discrepancies out there than anyone could document anyway.

**Comment by steve-prentice** [comment]
Just for completeness it relates to what the registry says is the Windows version ID:

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ReleaseId

Using anything other than what's listed there (i.e. trying 20H2 rather than the listed 2009) causes the CSP to fail and not apply.

**Comment by RAJU2529** [comment]
@steve-prentice . just now I checed I in my machine, releaseID  is settled to 2009

**Comment by illfated** [comment]
Thanks for confirming that 2009 works, even if it should have been a different string according to documentation.
