### ISSUE TITLE
Give an example how to give user rights with MDM Policy CSP

### ISSUE THREAD

**Issue by PanuSaukko** [MicrosoftDocs/windows-itpro-docs#856]
With Windows 10 1803 you can grant user rights with MDM Policy CSP. The documentation is missing what is the correct syntax to grant user rights to specific users/groups. Because MDM policy's are used in cloud-only environments, the examples should include how you can grant the user rights to Azure AD users/groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b62d452-1910-d962-0ccc-9ac3f8135f15
* Version Independent ID: 5a4e6f0c-bcd4-8d8b-93f7-5bda7135b931
* Content: [Policy CSP - UserRights](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-userrights#userrights-allowlocallogon)
* Content Source: [windows/client-management/mdm/policy-csp-userrights.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-userrights.md)
* Service: **unspecified**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by Cragsworth** [comment]
Would really like some examples here, what is the CSP expecting User SIDs? in what format. I cannot consume these CSPs with the information provided.

**Comment by MariciaAlforque** [comment]
Added examples and link to well known SIDs.

**Comment by dan529** [comment]
Your examples seem to be flawed.  I can't get this to work using the SIDs.  Are you sure this is the correct syntax?

**Comment by Heidilohr** [comment]
Hi Patti,

What should I do to find the correct syntax?

Thanks,

Heidi Lohr
Writer
Studio C
Phone (Skype): +1 425-703-4140 (Ext. 34140)

________________________________

**Comment by Heidilohr** [comment]
@dan529 The dev team informed me that this feature is only supported in the next major Windows release, and you won't be able to use it before then unless you're using an Insider build.

**Comment by schenardie** [comment]
So you saying this will only work with 1809??  Its working on 1803 currently but only one group added as a String (example Administrators)  but if 2 groups are needed on the same Settings it doesn't work.  Already tried with "name1;name2" "name1; name2" "name1,name2" "name1, name2" "<Data>Name1&#xF000;Name2</Data>" "Name1&#xF000;Name2"  can someone provide more info on how to get the these settings working?? Thanks

**Comment by schenardie** [comment]
Anyone following this issue?

**Comment by Illnasty** [comment]
Hey MS, just tell these people the truth that everything in this article doesn't work!

Here's what I did to get it to work.
1. The separator for the values like "Remote Desktop Users" and "Administrators" is &#61440;
   - Will that work as "Remote Desktop Users&#61440;Administrator" ?
   -Absolutely NOT!
2. Go to https://coderstoolbox.net/string/#!encoding=xml&action=decode&charset=us_ascii
  -Set string conversion to XML, Decode, and US-ASCII
  -Input = &#61440;
  -This will spit back a rectangle box in the Output
  -Copy that rectangle box and put it in the middle as the separator -  Remote Desktop UsersAdministrators
    - DO NOT COPY FROM HERE; IT WILL NOT WORK!!!

So here's the kicker!
  -USE EDGE Browser.  It WILL NOT WORK in Chrome

**Comment by Illnasty** [comment]
Ok so it actually converts the code here!  Putting spaces to help:
 - Input = & # 6 1 4 4 0 ;

**Comment by shortpatti** [comment]
@Illnasty, Thank you for your feedback.  I'll look into this policy and make the necessary changes.

**Comment by schenardie** [comment]
@Illnasty thanks for that mate.  Mine is still not working.  I'm decoding the code provided at the website and pasting in between AdministratorsRemote Desktop Users as a simple string and the OMA is ./Device/Vendor/MSFT/Policy/Config/UserRights/AccessFromNetwork but still not working.  Are you adding any more coding as per the page?? ie <Data> ??  thanks

**Comment by shortpatti** [comment]
So that I can get a better understanding, why doesn't \&#xF000; work as the separator?

**Comment by schenardie** [comment]
Hi patti.  it give s catastrophic failure. i got it working too following @Illnasty solution.  the code **&#xF000 ;** is not encoded, so if you use it between the groups (like admin &#xF000 ; Authenticated users) it wont work. you need to go to the website and encoded it to xmk (then you are left with that square symbol)  that is what you copy and paste in between the groups. Funny thing is that if you encode, copy the square and paste on the input line and decode, if are left with  &#61440 ; and not &#xF000 ; anymore

**Comment by shortpatti** [comment]
@schenardie, thank you for the response.  Now that I understand it better, and your response makes sense, it sounds like the code in the doc needs to be replaced and a note added about the \&#xF000 code not being encoded :)

**Comment by schenardie** [comment]
Well to be honest it says on the documentation
"Here are examples of data fields. The encoded 0xF000 is the standard delimiter/separator" but that is not clear how you encode it. And also i got that working via GUI, if you try to import that via Graph API passing either encoded or decoded it doest work. Once it reaches Intune if you check via the GUI its something like ??and a square.  So it cannot currently be automated.

If you could check that it would be great.  It makes all the difference on fully automated environments.  Thanks @shortpatti

**Comment by shortpatti** [comment]
@schenardie, you bet, I'll check with the engineering team about this one.

**Comment by schenardie** [comment]
Also since we're at it. The empty input (<Data></Data>) works but it gives a catastrophic error as well on the event logs.  If you can dig the right input which doesn't generate errors would be very helpful. Thanks again

**Comment by schenardie** [comment]
Any news?

**Comment by Heidilohr** [comment]
@schenardie I'm getting in touch with the engineering team. I'll let you know if there are any new developments.

**Comment by mypil** [comment]
@Heidilohr - Do you have any updates on this? Thanks.

**Comment by Ricardo-Cz** [comment]
Pay attention if you use the "Recommended value" of the ["1809 MDM Security Baseline Preview"](http://download.microsoft.com/download/2/C/4/2C418EC7-31E0-4A74-8928-6DCD512F9A46/1809-MDM-SecurityBaseLine-Document-[Preview].zip) Excel sheet for the AllowLocalLogon CSP. "Users Administrators" will lock out everybody of his device because of the wrong separator. If deleting the rule doesn't work configure it to "Users".

**Comment by illfated** [comment]
> Ok so it actually converts the code here! Putting spaces to help:
> 
> * Input = & # 6 1 4 4 0 ;

Just to remind users of Github; MarkDown code block fences ( **```** ) are useful to show code and not letting the web page convert it into symbols:
```
* Input= &#61440;
```

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by Ricardo-Cz** [comment]
For me it works if I use the CDATA syntax and the separator as described in the documentation. The settings are applied successfully on the client but the verification in Intune fails. I get an "Error" for all user rights settings in the "per setting status" of my profile. Can somebody confirm this behavior?

Example of a setting:
OMA URI: ./Device/Vendor/MSFT/Policy/Config/UserRights/AllowLocalLogOn
Value:
`<![CDATA[Users&#xF000;Administrators]]>`

**Comment by PeterKlapwijk** [comment]
@Ricardo-Cz I can confirm this behavior. I also used OMA URI: ./Device/Vendor/MSFT/Policy/Config/UserRights/AllowLocalLogOn The policy is successfully applied, but in Intune it shows an error  -2016281112 (Remediation failed)

**Comment by schenardie** [comment]
Is there a way to get the policy to be applied and the status on Intune show 	
Succeeded using custom profiles??

**Comment by illfated** [comment]
@ManikaDhiman : Sorry to ping you about this in your otherwise busy schedule,
but maybe you could answer the unanswered questions here?

**Comment by billgatesfan** [comment]
After fighting over few months with Intune Premier support, here is the answer we got from them : 

> Essentially the issue is caused because of the encoding of the user groups used when adding the users into the policy.
> When Intune does a GET on the value set, it expects it to match what was sent in an ADD or REPLACE, in this case due to the encoding, it doesn’t which is why we see the remediation failed message:
> This is documented in the following article - https://docs.microsoft.com/en-us/intune/custom-settings-windows-10#find-the-policies-you-can-configure 
> 
> To work with Intune, the setting must support the Add, Replace, and Get operations. If the value returned by the Get operation doesn't match the value supplied by the Add or Replace operations, then Intune reports a compliance error.
> This error can be safely ignored as it is expected.

While this is "understandable" from technical point of view, I am still surprised that they did not implemented some additional code to handle this. 
From a customer point of view, I did nothing wrong and errors are reported anyway in Intune... For me, I still see this as a bug.

**Comment by prlpl** [comment]
Beware of browsers for coding/decoding

**Comment by schenardie** [comment]
Has anyone found a way to deploy the decoded character via graph api? (not using the CDATA, i dont really want to see the profile failing for settings which i know are implemented).

Thanks

**Comment by joinimran** [comment]
@PanuSaukko - This is something that is not yet available in a way that can be deployed easily. I would suggest you put this as an idea in the Azure User Voice portal. This is the only best way to highlight and get this sorted out in a way this should be.

@nam31 - Please guide the user on how an idea can be submitted on the Azure User Voice channel. 

Thanks.
Imran.

**Comment by nam31** [comment]
@PanuSaukko thank you for engaging with the community here for the docs.
I know the product teams are always looking for user feedback and how to make Azure better . They keep a close tab on user feedback and it would be awesome if you could add your voice in [User Voice](https://feedback.azure.com/forums/34192--general-feedback)

**Comment by djatw0rk123** [comment]
I entered the boilerplate MSFT recommendation:

<SyncBody>
    <Replace>
      <CmdID>2</CmdID>
      <Item>
        <Meta>
          <Format>chr</Format>
          <Type>text/plain</Type>
        </Meta>
        <Target>
          <LocURI>./Device/Vendor/MSFT/Policy/Config/UserRights/BackupFilesAndDirectories</LocURI>
        </Target>
        <Data>Authenticated Users&#xF000;Administrators</Data>
      </Item>
    </Replace>
  <Final/>
  </SyncBody>
</SyncML>

https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-userrights#userrights-accessfromnetwork

Doesn't work, registry entries are 'Dirty'

Still looking for a way to manage these settings for compliance.

**Comment by szafrankk** [comment]
Idk if this has been worked on or not but after a long fight I've found how to do this...

What I've done is that I've pasted this into value: S-1-5-32-544&#61440;S-1-5-32-555
That's without any CDATA's, rectangle characters, and so on. Just use &#61440; as a separator.

**Comment by schenardie** [comment]
Yeah that does work indeed. Been using like that for a year now. The issue is that you cant programatically write that from graph api. For someone doing it for one tenant its easy enough to do it on the web browser. But 3 dozen tenants it get tricky. If anyone ever find a way to pass unicode characters via graph api please share here.

**Comment by szafrankk** [comment]
@schenardie do you also happen to know how to pass an empty value? Like - I'd like a right not to be assigned to any user role, how do I pass a string, which is empty. That's the bit I'm missing too... Theoretically they've mentioned <Data></Data> but I think what they meant was <![CDATA[]]> but that doesn't seem to work :(

Thanks in advance

**Comment by schenardie** [comment]
<Data></Data>

Does it. 

Just that will empty any groups that already exist.
