### ISSUE TITLE
Max number of tags?

### ISSUE THREAD

**Issue by jose-camacaro** [MicrosoftDocs/windows-itpro-docs#8562]
Is there a limit to the amount of tags that can be created? I no longer see the automatic option that would read "Create new tag" when I'm typing the name of a tag that doesn't exist.

Additionally, is there is single place where all tags can be administered or listed?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b42e708-e334-d434-bcc9-e1860ebb36b3
* Version Independent ID: 92e251c5-8613-ce97-9569-02404c9a466a
* Content: [Create and manage device tags - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/machine-tags)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/machine-tags.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/machine-tags.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by VLG17** [comment]
@jose-camacaro There is no limit (according to the public docs) to the amount of tags that can be created. The only limit refers to the maximum characters in a tag:

![image](https://user-images.githubusercontent.com/41186174/98378591-ea936c00-204e-11eb-8b2d-e72961b76188.png)

Regarding your second questions, you could export the device list and filter after tags.

https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/machines-view-overview#tags--groups

![image](https://user-images.githubusercontent.com/41186174/98379079-8c1abd80-204f-11eb-9944-7fb28abb9fc8.png)

**Comment by nam31** [comment]
@jose-camacaro Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Comment by jose-camacaro** [comment]
It must have been a temporary issue, because -without doing anything differently- I can see the "Create new" option when typing names in the tag field. Thanks anyway.
