### ISSUE TITLE
examples incorrect

### ISSUE THREAD

**Issue by sanderdewit** [MicrosoftDocs/windows-itpro-docs#8564]
The examples are incorrect.
The AppID is the actual application/executable and the DriverFilePath should contain the addins etc.

Current this is in reverse.

$rule = New-CIPolicyRule -DriverFilePath '.\ERP1.exe' -Level FileName -AppID '.\temp\addin1.dll'
$rule += New-CIPolicyRule -DriverFilePath '.\ERP1.exe' -Level FileName -AppID '.\temp\addin2.dll'
New-CIPolicy -Rules $rule -FilePath ".\AllowERPAddins.xml" -UserPEs

$rule = New-CIPolicyRule -DriverFilePath '.\winword.exe' -Level FileName -Deny -AppID '.\temp\addin3.dll'
New-CIPolicy -Rules $rule -FilePath ".\BlockAddins.xml" -UserPEs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35daeda2-a9df-bbb6-06fd-57c303301c4f
* Version Independent ID: e74f8724-bca4-b496-dbc1-15bd29c0a1bd
* Content: [Use a Windows Defender Application Control policy to control specific plug-ins, add-ins, and modules  (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-policy-to-control-specific-plug-ins-add-ins-and-modules)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-policy-to-control-specific-plug-ins-add-ins-and-modules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-policy-to-control-specific-plug-ins-add-ins-and-modules.md)
* Product: **w10**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
@sanderdewit - Do you want to say that the correct code will like 

$rule = New-CIPolicyRule -DriverFilePath '.\.\temp\addin1.dll' -Level FileName -AppID '.\ERP1.exe'
$rule += New-CIPolicyRule -DriverFilePath '.\temp\addin1.dll' -Level FileName -AppID '.\ERP1.exe'
New-CIPolicy -Rules $rule -FilePath ".\AllowERPAddins.xml" -UserPEs

$rule = New-CIPolicyRule -DriverFilePath '.\temp\addin3.dll' -Level FileName -Deny -AppID '.\winword.exe'
New-CIPolicy -Rules $rule -FilePath ".\BlockAddins.xml" -UserPEs

**Comment by sanderdewit** [comment]
that is correct.

**Comment by sanderdewit** [comment]
Just a small comment. in the correct example, you added an additional dot for the first one.
before:
$rule = New-CIPolicyRule -DriverFilePath '..\temp\addin1.dll' -Level FileName -AppID '.\ERP1.exe'

after:
$rule = New-CIPolicyRule -DriverFilePath '.\temp\addin1.dll' -Level FileName -AppID '.\ERP1.exe'

**Comment by joinimran** [comment]
Thanks @sanderdewit. Its all set now.

**Comment by nam31** [comment]
Closing via #8599. Thanks
