### ISSUE TITLE
Step 3 is missing what information should go in the text box when selecting public client.

### ISSUE THREAD

**Issue by keithtyler** [MicrosoftDocs/windows-itpro-docs#8567]
Step 3 is missing what information should go in the text box when selecting public client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 306ba013-6806-a377-14ea-10d32c7aef66
* Version Independent ID: a0f976c1-3fb7-9679-cf1d-697cc0058122
* Content: [Use Microsoft Defender Advanced Threat Protection APIs - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/exposed-apis-create-app-nativeapp)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/exposed-apis-create-app-nativeapp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/exposed-apis-create-app-nativeapp.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by nam31** [comment]
@keithtyler  With the help of your feedback, the issue has been reviewed and an update to the documentation has been published with PR #8598. Thanks for your feedback.
