### ISSUE TITLE
application/user context

### ISSUE THREAD

**Issue by keithtyler** [MicrosoftDocs/windows-itpro-docs#8568]
Shouldn't that be user context

User Context:
Used to perform actions in the API on behalf of a user.

Steps that needs to be taken to access Microsoft Defender ATP API with ~~application~~ context:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fa7a534-0c88-a3b6-5b27-81d735779fad
* Version Independent ID: cf641b62-a2b2-54fb-d885-15c5d7200215
* Content: [Access the Microsoft Defender Advanced Threat Protection APIs - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/apis-intro)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/apis-intro.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/apis-intro.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by nam31** [comment]
Closing via #8582 
Thanks
