### ISSUE TITLE
Give an example how to utilize RestrictedGroups feature

### ISSUE THREAD

**Issue by PanuSaukko** [MicrosoftDocs/windows-itpro-docs#857]
The documentation doesn't have any information in what format you define:
- which groups you want to manage
- which members are added to the group

There should be an example how to utilize this feature. The example should include how to add Azure AD users/members to a group, because this feature will be used in cloud-only environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0c28c15-f0be-d732-4d9e-cf5df5e64e8b
* Version Independent ID: 17eba45f-d200-e656-42b9-e1a512931eea
* Content: [Policy CSP - RestrictedGroups](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-restrictedgroups)
* Content Source: [windows/client-management/mdm/policy-csp-restrictedgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-restrictedgroups.md)
* Service: **unspecified**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by patlewis-MSFT** [comment]
Provided Example:
OMA-URI: ./Device/Vendor/MSFT/Policy/Config/RestrictedGroups/ConfigureGroupMembership

Data:
<groupmembership>
    <accessgroup desc="Administrators">
        <member name="AzureAD\CSPTest@contoso.com" />
        <member name="CSPTest22306\administrator" />
        <member name = "AzureAD\patlewis@contoso.com" />
    </accessgroup>
    <accessgroup desc = "testcsplocal">
        <member name = "CSPTEST22306\patlewis" />
        <member name = "AzureAD\CSPTest@contoso.com" />
    </accessgroup>
</groupmembership>

Few notes here that may be helpful:
* You must include the local administrator in the administrators group or the policy will fail
* Include the entire UPN after AzureAD

**Comment by patlewis-MSFT** [comment]
For some reason my pasted data didn't show up.  This should be the data:

<groupmembership>
    <accessgroup desc="Administrators">
        <member name="Administrator" />
        <member name="AzureAD\CSPTest@contoso.com" />
        <member name="CSPTest22306\patlewis" />
        <member name = "AzureAD\patlewis@contoso.com" />
    </accessgroup>
    <accessgroup desc = "testcsplocal">
        <member name = "CSPTEST22306\patlewis" />
        <member name = "AzureAD\CSPTest@contoso.com" />
    </accessgroup>
</groupmembership>

**Comment by patlewis-MSFT** [comment]
<groupmembership>
    <accessgroup desc="Administrators">
        <member name="Administrator" />
        <member name="AzureAD\CSPTest@contoso.com" />
        <member name="CSPTest22306\patlewis" />
        <member name = "AzureAD\patlewis@contoso.com" />
    </accessgroup>
    <accessgroup desc = "testcsplocal">
        <member name = "CSPTEST22306\patlewis" />
        <member name = "AzureAD\CSPTest@contoso.com" />
    </accessgroup>
</groupmembership>

**Comment by patlewis-MSFT** [comment]
```xml
<groupmembership>
    <accessgroup desc="Administrators">
        <member name="Administrator" />
        <member name="AzureAD\CSPTest@contoso.com" />
        <member name="CSPTest22306\patlewis" />
        <member name = "AzureAD\patlewis@contoso.com" />
    </accessgroup>
    <accessgroup desc = "testcsplocal">
        <member name = "CSPTEST22306\patlewis" />
        <member name = "AzureAD\CSPTest@contoso.com" />
    </accessgroup>
</groupmembership>
```

**Comment by e0i** [comment]
@officedocsbot close

**Comment by chanderjeet** [comment]
How about adding a group to local admins. How is that done?

**Comment by scerazy** [comment]
Is it even possible? Anf if not, then WHY NOT?

**Comment by e0i** [comment]
@chanderjeet Thank you for following up. The issue is being passed to an independent contributor for investigation.

**Comment by MaratMussabekov** [comment]
Hello, @chanderjeet, @scerazy 
To add a group to a local admins:
<groupmembership>
    <accessgroup desc = "Administrators">
        <member name = "contoso\Group"/>
    </accessgroup>
</groupmembership>

You can add user, AD group or Azure AD group to a local admins group using its full name or SID.

Thank you

**Comment by JeremyTBradshaw** [comment]
> Provided Example:
> OMA-URI: ./Device/Vendor/MSFT/Policy/Config/RestrictedGroups/ConfigureGroupMembership
> 
> Data:
> 
> ```
> <groupmembership>
>     <accessgroup desc="Administrators">
>         <member name="AzureAD\CSPTest@contoso.com" />
>         <member name="CSPTest22306\administrator" />
>         <member name = "AzureAD\patlewis@contoso.com" />
>     </accessgroup>
>     <accessgroup desc = "testcsplocal">
>         <member name = "CSPTEST22306\patlewis" />
>         <member name = "AzureAD\CSPTest@contoso.com" />
>     </accessgroup>
> </groupmembership>
> ```
> 
> Few notes here that may be helpful:
> 
> * You must include the local administrator in the administrators group or the policy will fail
> * Include the entire UPN after AzureAD

@patlewis-MSFT Is there any guidance on how to properly include the local Administrator account?  Do we just do it like this:
`<member name = "Administrator" />`

**Comment by scerazy** [comment]
@MaratMussabekov,

Never ever managed to get it working. I have it like that in Configuration Profile, but never was added to machine to which it was assigned to!
