### ISSUE TITLE
How to remove unused tags from Defender ATP

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/windows-itpro-docs#8573]
I once created a tag and assigned it to a device. The device now has been deleted and I would like to get rid of the tag. But it still appears in the filter list. How do I remove the tag from ATP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b42e708-e334-d434-bcc9-e1860ebb36b3
* Version Independent ID: 92e251c5-8613-ce97-9569-02404c9a466a
* Content: [Create and manage device tags - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/machine-tags)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/machine-tags.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/machine-tags.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by VLG17** [comment]
You can use the [Defender for Endpoint API](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/add-or-remove-machine-tags) to achieve that goal.

> Request example:
> 
> POST https://api.securitycenter.microsoft.com/api/machines/1e5bc9d7e413ddd7902c2932e418702b84d0cc07/tags
> Content-type: application/json
> {
>   "Value" : "test Tag 2",
>   "Action": "Remove"
> }

**Comment by andrePKI** [comment]
Thanks, looks great and I will try that ASAP!

**Comment by VLG17** [comment]
@andrePKI Have you tested this? Did it work?

**Comment by andrePKI** [comment]
I tried, but it is not what I am looking for. The tag is not attached to any machine, but nevertheless present in the Defender Security Center, e.g. at the Device Inventory blade, in the filter list. Over time, this will clutter the list with unused tag values.

So, if anybody knows another way to remove the tag value from the tenant....

**Comment by VLG17** [comment]
@andrePKI I suggest [reaching out to support](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/contact-support) in order to get an answer. 

Our goal here is to update the documentation if needed, so when you find an answer let us know what it is and we can add that information to the article you linked, so others can reference it in the future.
