### ISSUE TITLE
realTimeProtectionAvailable = false (/Library/Extensions/wdavkext.kext - No such file or directory)

### ISSUE THREAD

**Issue by watermarking** [MicrosoftDocs/windows-itpro-docs#8576]
When my macOS was updated to Catalina 10.15.7 version, the defender cannot work.

And I can see below message when I try to fix it from 'Action needed' section.

"Real-time protection could not be turned on. Contact your administrator."

$ mdatp --health
appVersion                                  : "101.10.76"
automaticDefinitionUpdateEnabled            : true
cloudAutomaticSampleSubmissionConsent       : "safe"
cloudDiagnosticEnabled                      : false
cloudEnabled                                : true
conflictingApplications                     : null
definitionsStatus                           : "upToDate"
definitionsUpdated                          : "1604420553348"
definitionsUpdatedMinutesAgo                : 1
definitionsVersion                          : "82454"
edrConfigurationVersion                     : "199999.5357656.4857923.1-8bfc70654028d7538466fe5e8f308732e928f343"
edrDeviceTags                               : []
edrEarlyPreviewEnabled                      : "disabled"
edrGroupIds                                 : ""
edrMachineId                                : "fe7dbe203f56270cff16b715054085ce9689037b"
engineVersion                               : "3.0"
engineVersionV2                             : null
healthy                                     : false
licensed                                    : true
logLevel                                    : "info"
machineGuid                                 : "dd4318fa-5f5d-5d06-8d34-420677bbdf92"
networkEventsSubsystem                      : null
networkProtectionStatus                     : "stopped"
orgId                                       : "d7c7c745-195f-4223-9c7a-99fb420fd000"
passiveModeEnabled                          : false
productExpiration                           : "1618082061000"
**realTimeProtectionAvailable                 : false**
realTimeProtectionEnabled                   : true
realTimeProtectionSubsystem                 : null
releaseRing                                 : "Internal"

$ sudo kextutil /Library/Extensions/wdavkext.kext
Password:
**Can't stat /Library/Extensions/wdavkext.kext - No such file or directory.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72abfa66-ddf0-4fd6-152d-b66ebad98525
* Version Independent ID: c72a3ba7-cd9e-3b40-1bd6-dea45c5f690e
* Content: [Troubleshoot kernel extension issues in Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-support-kext)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-support-kext.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-support-kext.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
The issues section of this repository is intended for product documentation issues.

Please consider opening a product support ticket by the following link below for your problem,

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
