### ISSUE TITLE
Broken link in BitLocker documentation

### ISSUE THREAD

**Issue by loganrosen** [MicrosoftDocs/windows-itpro-docs#8578]
There's a broken link to [Tip of the Day: Bitlocker without TPM or USB](https://blogs.technet.microsoft.com/tip_of_the_day/2014/01/22/tip-of-the-day-bitlocker-without-tpm-or-usb/), which redirects to a page saying that the content was removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde8beb2-6800-cf3c-c927-91ed2827eb6c
* Version Independent ID: 7264f37a-e40a-3cd8-d28c-5b2b772eff15
* Content: [BitLocker (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-overview)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-overview.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Content found in the WayBack Machine (web.archive.org):
- https://web.archive.org/web/20190420201930/https://blogs.technet.microsoft.com/tip_of_the_day/2014/01/22/tip-of-the-day-bitlocker-without-tpm-or-usb/

Short article, 5(6) sentences with an image, followed by comments from other users.

**Comment by illfated** [comment]
Alternative link: https://social.technet.microsoft.com/Forums/en-US/eac2cc67-8442-42db-abad-2ed173879751/bitlocker-without-tpm?forum=win10itprosetup

**Comment by nam31** [comment]
Closing via #8623 
Thank you
