### ISSUE TITLE
is device-code flow supported for defender atp apis?

### ISSUE THREAD

**Issue by t-rojan** [MicrosoftDocs/windows-itpro-docs#8589]
I've been trying to call the defender APIs using device code flow auth, but after authenticating the Azure IdP says "Your sign-in was successful but your admin requires the device requesting access to be managed by xxxx to access this resource". Azure AD logs state that the login failed because there's a conditional access policy that requires a managed device - but the Azure AD logs do not show any CA policies having matched and there's isn't such a policy. I am wondering if device code flow isn't supported for these APIs.

Use-case I'm trying to build is a CLI for our sec-ops team to quickly isolate a large number of devices. Clicking through the UI is too slow. Intent is a CLI that they can authenticate with using their admin id. Given the client is a script app auth didn't seem like the right choice. If device code flow is not support. What auth scheme is recommended for this scenario?

**Comment by denisebmsft** [comment]
Hello @t-rojan. Is there a specific article for which your question applies? This information will help us route the issue correctly.

**Comment by e0i** [comment]
@t-rojan Please feel free to re-open this issue with information on from which article exactly the problem stems from. Thanks.

**Comment by illfated** [comment]
Or better still, if you go back to the related MS Docs page and open a new ticket from there, that would be ideal.
