### ISSUE TITLE
Device Authentication settings could cause certificate prompt to appear on Azure AD Registered devices (Android, iPhone)

### ISSUE THREAD

**Issue by Alexey-Zheltov** [MicrosoftDocs/windows-itpro-docs#8593]
[Enter feedback here]

I would suggest to change PowerShell command below in "Configure Device Authentication in AD FS" section:

PS C:>Set-AdfsGlobalAuthenticationPolicy -DeviceAuthenticationEnabled $true -DeviceAuthenticationMethod All

Instead of using "All" we should use "SignedToken" to prevent certificate prompt to appear on Azure AD Registered Devices after enabling Device Authentication on ADFS 

PS C:>Set-AdfsGlobalAuthenticationPolicy -DeviceAuthenticationEnabled $true -DeviceAuthenticationMethod SignedToken
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93cb286c-03a9-187a-77a3-771c1c672342
* Version Independent ID: 875bbfa3-7ee3-960e-9b1c-ff5216a62d8b
* Content: [Configure Device Registration for Hybrid Windows Hello for Business - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
Ref. PR #8595

**Comment by illfated** [comment]
I presume this issue is resolved in the linked PR by the same author.

**Comment by illfated** [comment]
#please-close
