### ISSUE TITLE
Kiosk Browser App

### ISSUE THREAD

**Issue by nicolonsky** [MicrosoftDocs/windows-itpro-docs#860]
Is the kiosk browser app mentionet already available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f49c3f-ba5c-49e9-fad2-88cac155920a
* Version Independent ID: dc5e1f7e-61a8-bf2c-34b8-4046d024f4c2
* Content: [Set up a kiosk or digital signage on Windows 10 Pro, Enterprise, or Education (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/setup-kiosk-digital-signage)
* Content Source: [windows/configuration/setup-kiosk-digital-signage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/setup-kiosk-digital-signage.md)
* Service: **unspecified**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@nicolonsky Thanks for asking about this! I just checked and it isn't available in the store yet, but should be soon (in the next week or so). I'll add a note to the topic.
