### ISSUE TITLE
Testing leaving feedback on localized page

### ISSUE THREAD

**Issue by TinaMcN** [MicrosoftDocs/windows-itpro-docs#8600]
Test of feedback control on Korean page.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: b73c22f0-cb0d-e34b-29d8-06829b86784f
* Version Independent ID: 083115ed-f1be-e962-5b0e-5079dec37353
* Content: [MBR2GPT - Windows Deployment](https://docs.microsoft.com/ko-kr/windows/deployment/mbr-to-gpt)
* Content Source: [windows/deployment/mbr-to-gpt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/mbr-to-gpt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Thank you, the test looks quite OK, referencing the localized page https://docs.microsoft.com/ko-kr/windows/deployment/mbr-to-gpt .

**Comment by TinaMcN** [comment]
#please-close

**Comment by illfated** [comment]
Looks like that feature might be specific to the Windows Server Docs repository, and not working here (I will have a go at it anyway).

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
@nam31 : For your information, please see above.

**Comment by nam31** [comment]
Thank you @illfated
