### ISSUE TITLE
Error 5 Extract a specific image index from install.wim

### ISSUE THREAD

**Issue by MooreSys** [MicrosoftDocs/windows-itpro-docs#8602]
Receive an Error 5 on Step 3: If you have multiple image indexes in the installation media, select Extract a specific image index from install.wim... and choose the image index you want from the dropdown menu. In this example, we have chosen Windows 10 Enterprise.

If I do the entire image it works fine. Just can not extract a single index. I have checked the permission up one side and down the other. I have event tried it directly on the SCCM Server with my global Admin for SCCM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0867909f-7afe-2192-0659-27c182f90553
* Version Independent ID: 97eb09fc-39fb-9101-753e-3d9377d8284f
* Content: [Perform in-place upgrade to Windows 10 via Configuration Manager - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-cm/upgrade-to-windows-10-with-configuraton-manager)
* Content Source: [windows/deployment/deploy-windows-cm/upgrade-to-windows-10-with-configuraton-manager.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-cm/upgrade-to-windows-10-with-configuraton-manager.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by nam31** [comment]
@MooreSys Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)
Thank you.

**Comment by illfated** [comment]
@MooreSys : Thank you for your report. If you do get any feedback, directly related to this document, from contacting your nearest Microsoft Support tenant or other support contact, please feel free to share any reports of inconsistent or incorrect documentation with us. We strive to make the documentation more correct and user friendly, but we do rely on feedback to get such improvements made. Thank you.

**Comment by greg-lindsay** [comment]
Hi, just a comment here to maybe help. See https://docs.microsoft.com/en-us/mem/configmgr/osd/get-started/manage-operating-system-images this option is available starting in version 1902, so maybe check your version of config mgr.

**Comment by greg-lindsay** [comment]
Some images are included in this article that might help too. https://www.niallbrady.com/2019/08/07/how-to-select-an-index-when-importing-an-upgrade-package-into-sccm/

**Comment by illfated** [comment]
@MooreSys : See the comments above. Hope This Helps.
