### ISSUE TITLE
Link wrong

### ISSUE THREAD

**Issue by gitralf** [MicrosoftDocs/windows-itpro-docs#8606]
There is a link under "this page" (near the end) that points to the review-branch:

Once you have Azure AD join or hybrid Azure AD join in place, you can learn more about executing user-based DSRs, by visiting this page.

points to: https://review.docs.microsoft.com/de-de/microsoft-365/compliance/gdpr-dsr-windows?branch=siosulli-wps&view=o365-worldwide

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6b4302c0-7fd1-3334-c2de-a72ba1445bfa
* Version Independent ID: 6ff45232-1db9-8166-d3ae-1fa290ab0fa5
* Content: [Technische Bereitstellung des Datenverarbeitungsdienstes für Windows - Windows Privacy](https://docs.microsoft.com/de-de/windows/privacy/deploy-data-processor-service-windows)
* Content Source: [windows/privacy/deploy-data-processor-service-windows.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/deploy-data-processor-service-windows.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **siosulli**

**Comment by illfated** [comment]
Page message:

***

## We are sorry, the page is<br> forbidden.

You do not have permission with this credential, please<br> sign out to try with others and go back again.

[ Sign Out ]

***

Please note that this is not a broken link as such, but it is an access limitation to allow only those who have signed up for the Data Processor Service for Windows Enterprise Public Preview.

Have you signed up for the **Data Processor Service for Windows Enterprise Public Preview** and tried logging in from a user account with credentials to access this service?

(Myself, I don't have any Enterprise access account, so I don't know what the expected result should be.)

**Comment by nam31** [comment]
@gitralf The issue is being closed since your question seems to be answered by @illfated  
Please let us know if you still have any question regarding the issue you have raised initially.
Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Comment by illfated** [comment]
@gitralf : Looking forward to any feedback you have got time to share with us. 🙂
