### ISSUE TITLE
Duplicate entry in "Windows 10 features we’re no longer developing"

### ISSUE THREAD

**Issue by hematogender** [MicrosoftDocs/windows-itpro-docs#8609]
There's a duplicate Microsoft Edge entry in [this](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/planning/windows-10-deprecated-features.md) document.

![image](https://user-images.githubusercontent.com/46577620/98599736-2a738100-22e5-11eb-85cd-8af020f7a242.png)

**Comment by RAJU2529** [comment]
@hematogender . Which article are you talking about?

**Comment by hematogender** [comment]
@RAJU2529 The one I linked -- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/planning/windows-10-deprecated-features.md

**Comment by RAJU2529** [comment]
@hematogender , Thanks for pointing out, I am fixing duplicate entry now.

**Comment by illfated** [comment]
See PR #8613 for the request to remove the duplicate entry.

**Comment by denisebmsft** [comment]
Thank you, all!
