### ISSUE TITLE
Premium connector - need to call out license options

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/windows-itpro-docs#8616]
why this is a premium connect defies belief.
WDTAP comes with big boy Windows 365 E5 - but to run this flow you need to buy more - its not enough

anyhow... whilst the not so bright people are in charge - can you please call out reference to the SKU options needed to run this flow;   per flow SKU should be sufficient

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8685b2-578c-2f4a-67a0-d0b80e9f0383
* Version Independent ID: 9ccbc58d-7a5f-725e-021f-2ecb43669576
* Content: [Microsoft Defender ATP Flow connector - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/api-microsoft-flow)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/api-microsoft-flow.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/api-microsoft-flow.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by VLG17** [comment]
@bakerm00 More details about premium connectors licencing [here](https://docs.microsoft.com/en-us/power-automate/triggers-introduction#licensing-for-premium-connectors).

> You need a [standalone Power Apps license](https://powerapps.microsoft.com/pricing/) or [Power Automate license](https://flow.microsoft.com/pricing/) to access all premium, on-premises, and custom connectors. Microsoft 365 plan licensees can use standard connectors but cannot use premium connectors.

Do you feel we should add a note about this to the [referenced article](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/api-microsoft-flow)?

**Comment by bakerm00** [comment]
yes - exposing the licensing Costs is integral to adoption and something like this stops things in track of adoption - because it was a hidden cost.
