### ISSUE TITLE
set device tagging for defender security centre

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/windows-itpro-docs#8617]
what options exist for device tagging with linux agent to show in security centre?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2197cba-30ac-1749-e25a-6f39c9ee9d20
* Version Independent ID: bcd14f13-ab59-8e69-5c83-42fee6e51f87
* Content: [Deploy Microsoft Defender ATP for Linux manually - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@bakerm00 Have you looked into the now generally available endpoint detection and response (EDR) capabilities in Microsoft Defender for Endpoint on Linux server?

You can use the [custom detections](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/custom-detection-rules) feature and filter after DeviceID.

**Comment by bakerm00** [comment]
> @bakerm00 Have you looked into the now generally available endpoint detection and response (EDR) capabilities in Microsoft Defender for Endpoint on Linux server?
> 
> You can use the [custom detections](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/custom-detection-rules) feature and filter after DeviceID.

doesn't look to fit with our existing divisional delegation model and segregated teams.  TAGS work

**Comment by VLG17** [comment]
@bakerm00 Understood. I see there is this option available, don't know if it helps in your scenario:

https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-resources

![image](https://user-images.githubusercontent.com/41186174/106882983-0c50cd80-66e8-11eb-9a33-6b25720674f3.png)

Also, please keep in mind that our goal here is to update the documentation, if needed. So if you feel like something is missing or needs to be changed in regards to the linked article, let us know. If you need more technical details related to tagging and the options that exists or are in the roadmap for Microsoft Defender for Endpoint for Linux, please [reach out to support](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/contact-support).
