### ISSUE TITLE
Clarifications requested please

### ISSUE THREAD

**Issue by PeteSimons** [MicrosoftDocs/windows-itpro-docs#8618]
I am working with a customer who has found this article very interesting but has asked for clarity on three specific points.  Can anyone provide any advice and update the document t provide clarity on these:

1. The article refers to using a **Azure AD Certificate Authority** but doesn't provide any detail on what this is and the customer cant find any reference to this elsewhere - can we provide a link to supporting content or clarify what this is?  Current text says:

_"Azure AD Certificate Authority - It is a requirement that the client certificate used for the cloud-based device compliance solution be issued by an Azure Active Directory-based Certificate Authority (CA). An Azure AD CA is essentially a mini-CA cloud tenant in Azure. The Azure AD CA cannot be configured as part of an on-premises Enterprise CA."_

2. Not clear on if the VPN client need to be configured using the VPNv2 CSP rather than the standard VPN config template using the GUI as that seems to require the selection of a certificate profile which implies that the compliance certificate is a secondary certificate rather than the primary one used for authentication (or does enabling the CA config effectively override the initial selection in which case why is it mandatory…)?

3. Not clear whether once successfully configured it would result in an ‘always-on’ machine VPN connection and if so whether it’s a candidate for use as the VPN when ‘building’ a hybrid AAD join machine with AutoPilot when remote? …and if not, why not?

**Comment by James-Simms** [comment]
Thanks Peter!

Btw, I'm the customer and in case it's not immediately clear to anyone reading, it's this article that I'm looking at:

https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-conditional-access

James

**Comment by lindspea** [comment]
@James-Simms @PeteSimons thanks for reaching out and helping improve MS Docs. I'm investigating to provide more information. Will revert shortly.

**Comment by illfated** [comment]
Normal comment content, if the ticket had been opened from the referenced page:

***

[Enter feedback here]


---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b6faee7-5e59-c367-075d-5517d3af4f75
* Version Independent ID: e6d377d5-267e-ec54-3769-6d5863ef6936
* Content: [VPN and conditional access (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-conditional-access)
* Content Source: [windows/security/identity-protection/vpn/vpn-conditional-access.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/vpn/vpn-conditional-access.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by lindspea** [comment]
@PeteSimons @James-Simms If you are referring to the note it means that Azure AD certificates are used for establishing VPN connections, but not to providing access to on-premises resources. For users to be able to access these resources, certificates issued by on-premises CA must be deployed to the Windows profiles of the users, and their VPNv2 profiles must contain the section. Let me know if you need any further info.

**Comment by James-Simms** [comment]
Hi @lindspea,
No, I'm not worried about accessing on-premise resources, we can handle that later if we need it.  I'm interested in the Azure AD certificates; the article refers to an Azure AD Certificate Authority and an Azure AD Token Broker service which I can't find referenced anywhere else so keen to understand how I would go about setting them up.

When it comes to the VPN client configuration does it need to be done using the VPN2 CSP as I think it's implying?  The Intune VPN client configuration policy seems to mandate the selection of a certificate profile but it doesn't look like it's possible to configure one of these using the Azure AD CA (unless it appears once you have one and the first answer solves the challenge!)

The final question (once it's all working for general usage) is can it be used as the VPN when ‘building’ a hybrid AAD join machine with AutoPilot when remote (ie over VPN)?

**Comment by PeteSimons** [comment]
Hi @lindspea 
Any update on this - or do you know who I can contact in Microsoft for further input?  This article does look to be very interesting, but just needs some additional clarity for the customer to be able to follow the guidance.
Thanks
Peter

**Comment by lindspea** [comment]
@illfated would you perhaps know more about this? @PeteSimons @James-Simms you might need to raise a support request in Azure Portal or alternatively @nam31 please ask the author for help.

**Comment by illfated** [comment]
Thank you for asking, but my general IT experience from customer support and small business management does not include this specific topic or Azure usage in general. Sorry.

**Comment by James-Simms** [comment]
OK, after some more digging I've managed to get to the bottom of the first question so should be able to answer the other two with some experimentation!

For anyone else who's interested, I found the pointer to the answer in the F5 documentation here: https://techdocs.f5.com/kb/en-us/products/big-ip_apm/manuals/related/apm-f5-access-windows-10-using-intune/3.html

The configuration of the Certificate Authority is actually in the Conditional Access module in the Azure Portal here:
![image](https://user-images.githubusercontent.com/74308060/103550003-2a849d00-4ea0-11eb-9763-32b500d63304.png)

In terms of the documentation for this Windows 10 feature (ie https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-conditional-access) I think it would be useful to update it to reference where to find the documentation for this Conditional Access Certificate Authority.  Even if it's just using the link in the image above (https://aka.ms/vpnca) (even though the page that it takes you to isn't 100% what I'd expect...)

**Comment by lindspea** [comment]
> OK, after some more digging I've managed to get to the bottom of the first question so should be able to answer the other two with some experimentation!
> 
> For anyone else who's interested, I found the pointer to the answer in the F5 documentation here: https://techdocs.f5.com/kb/en-us/products/big-ip_apm/manuals/related/apm-f5-access-windows-10-using-intune/3.html
> 
> The configuration of the Certificate Authority is actually in the Conditional Access module in the Azure Portal here:
> ![image](https://user-images.githubusercontent.com/74308060/103550003-2a849d00-4ea0-11eb-9763-32b500d63304.png)
> 
> In terms of the documentation for this Windows 10 feature (ie https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-conditional-access) I think it would be useful to update it to reference where to find the documentation for this Conditional Access Certificate Authority. Even if it's just using the link in the image above (https://aka.ms/vpnca) (even though the page that it takes you to isn't 100% what I'd expect...)

That's amazing thanks @James-Simms. I'll add a link to that article.

**Comment by illfated** [comment]
PR #8914 is ready for review, comments, and suggestions.

**Comment by nam31** [comment]
Closing via #8914 
Thank you
