### ISSUE TITLE
Server 2012 and later with AD, Bitlocker setup

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/windows-itpro-docs#8621]
[Enter feedback here]
Can a link be added on how to configure bitlocker recovery code storage on Server 2012 and later, using active directory?  I have yet to find an article from Microsoft, that talks about that, it is always Server 2008 / Windows Vista, at least not with a BING search.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5476099c-9d70-97df-8ee6-bc442605cfbd
* Version Independent ID: 49ca0628-bd88-e05b-b705-3b361b57512d
* Content: [BitLocker Group Policy settings (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-group-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by rconiv** [comment]
That should, but with at least Server 2019, the add the Bitlocker Drive Encryption Administration Utility has changed from what is in that article.  The bitlocker password recovery viewer option isn't there. 
![Screenshot 2020-11-19 103555](https://user-images.githubusercontent.com/72881999/99708710-0afdf600-2a53-11eb-97a5-09f9dae9c0f6.png)
The first note, which has a link to backing up the recovery information takes you to https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/backup-tpm-recovery-information-to-ad-ds which states that this can't be done after Windows 10 1511, though I am doing it with a system on 2003.  The second note on the main MDT page states the same thing.  The link in that article is for how to set it up in Server 2012, for Windows 8.X.

**Comment by VLG17** [comment]
@rconiv The printscreen you shared is from a Windows Server 2019? If you expand BitLocker Drive Encryption Administration Utility, don't you see BitLocker Recovery Password Viewer as with previous server versions? I did not get to test it, but i will.

I think there is a bit of misunderstanding here between the 2 functionalities described in the article: backup of Bitlocker Recovery Password to AD and backup of TPM information to AD. The first and second note both talk about the TPM information, not about Bitlocker Recovery Password.

Starting with Windows 10, version 1607 you can no longer backup TPM information to AD (the ADMX templates are no longer there if you update).

But you can backup the Bitlocker Recovery Password, which is a different thing. That's my understanding.

**Comment by rconiv** [comment]
Your right, I missed a step, and the bitlocker recovery password viewer was already checked.

That would make sense.  I can pull up the recovery ID and 48 digit recovery code through AD Users and computers by right clicking and going to the properties of the specific computer.   It is just how I read it, it makes it sound like you can't store anything to do with bitlocker after that version of Windows 10 in AD, and have to use Azure.

After I posted this, I found that I had to go in to the Windows Components\Bitlocker Drive Encryption\Operating System Drivers on Server 2019, and probably also 2016, to setup bitlocker to save on to AD.  Now I just need to figure out how to get the server policy to force the workstation to bitlocker its self  Right now, I still have to do it manually.

MBAM will be another issue I have to fight at some point, but think that is more of a licensing or lack there of issue currently.

![image](https://user-images.githubusercontent.com/72881999/100274419-3da46480-2f13-11eb-8fd3-c54e81afa0cd.png)

**Comment by VLG17** [comment]
@rconiv Happy to hear that there is more clarity now regarding this topic. Circling back to my initial question, i think it would make sense to add a note about the ["Set up MDT for BitLocker"](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/set-up-mdt-for-bitlocker) article in the [article](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings) that you referenced when creating this issue, correct?

**Comment by nam31** [comment]
Closing via #8772
