### ISSUE TITLE
Seem you guy about got the code you want i supose your about ready to  crash my computer!!

### ISSUE THREAD

**Issue by danielklenda85** [MicrosoftDocs/windows-itpro-docs#8624]

**Comment by danielklenda85** [comment]
my computer keeps crashing and a dam screen with a sad face and a link says stop code.
  FYI Github  you are linked to everyone of my system setting

**Comment by danielklenda85** [comment]
if my computer crash i  will know who to blame

**Comment by danielklenda85** [comment]
Daniel  Patrick Klenda Salina Kansas 67401 USA Not Married not in jail!

**Comment by denisebmsft** [comment]
Hello @danielklenda85. Is there a specific article to which your feedback applies? It looks like the issue you are having is not a documentation (help content) related issue. Have you tried calling tech support?

**Comment by illfated** [comment]
This is spam. It has happened before, sometimes it just pops out of nowhere, randomly. No need to keep this ticket open.

**Comment by illfated** [comment]
#please-close

**Comment by danielklenda85** [comment]
it pops up every time i snip & Sketch

**Comment by illfated** [comment]
@danielklenda85 : Get yourself a Malware removal program to get rid of the unwanted behaviour on your computer. If you find it difficult to manage yourself, ask someone for help or contact your nearest computer support department to get assistance with your computer software issues.

**Comment by danielklenda85** [comment]
> Hello @danielklenda85. Is there a specific article to which your feedback applies? It looks like the issue you are having is not a documentation (help content) related issue. Have you tried calling tech support?

Nope my layer
