### ISSUE TITLE
Acronyms which are not explained

### ISSUE THREAD

**Issue by injosef** [MicrosoftDocs/windows-itpro-docs#8625]
For some reason we are referring to two separate but unexplained acronyms in the licensing section:

" following may acquire Server SLs"
&
"Microsoft 365 E5 Security User SLs"

What in the world is a "SL"? Software-License? Why not spell it out instead, this saving of electrons benefits nobody
 ;-)

We also write "one per covered Server OSE" without explaining the acronym OSE in this context, or at all.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
According to https://www.microsoft.com/en-us/licensing/product-licensing/windows-server , the initialism "OSE" means Operating System Environment and refers to Virtual Machines more often than physical direct computer/server machine installations. For practical purposes, it is sometimes interchangeable.

### Features

|    | Datacenter | Standard |
| -- | :--------: | :------: |
| Core functionality of Windows Server | ✓ | ✓ |
| Operating system environment (OSEs/Hyper-V containers) | Unlimited | 2* |
| Windows Server containers | Unlimited | Unlimited |
| Host Guardian Service | ✓ | ✓ |
| Storage Replica | ✓ | ✓ |
| Shielded Virtual Machines | ✓ |  |
| Software-defined networking | ✓ |  |

*Standard edition permits use of one running instance of the server software in the physical OSE on the licensed server (in addition to two virtual OSEs), if the physical OSE is used solely to host and manage the virtual OSEs.

***

Regarding the initials "SL", which likely means "Server License". Would be nice to have it referenced and confirmed based on any existing Microsoft page.

**Comment by VLG17** [comment]
@injosef The article has been updated to reflect these changes.
