### ISSUE TITLE
Indicator response is different from what mentioned in API docs

### ISSUE THREAD

**Issue by nithinpaladion** [MicrosoftDocs/windows-itpro-docs#8629]
Hi Team,
We are getting a different response for indicator API. Its not as per the API documentation. The sample response i am getting is shown below.

{
    "@odata.context": "https://api.securitycenter.windows.com/api/$metadata#Indicators",
    "value": [
        {
            "id": "1",
            "indicatorValue": "1.1.1.1",
            "indicatorType": "IpAddress",
            "action": "AlertAndBlock",
            "createdBy": "username",
            "severity": "Medium",
            "category": 1,
            "application": null,
            "educateUrl": null,
            "bypassDurationHours": null,
            "title": "title",
            "description": "description",
            "recommendedActions": null,
            "creationTimeDateTimeUtc": "2020-10-30T12:09:40.7725623Z",
            "expirationTime": null,
            "lastUpdateTime": "2020-10-30T12:09:40.7725623Z",
            "lastUpdatedBy": null,
            "rbacGroupNames": [],
            "rbacGroupIds": [],
            "notificationId": null,
            "notificationBody": null,
            "version": null,
            "mitreTechniques": [],
            "historicalDetection": false,
            "lookBackPeriod": null,
            "generateAlert": true,
            "additionalInfo": null,
            "createdByDisplayName": "displayUser",
            "createdBySource": "source",
            "certificateInfo": null
        }
    ]
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8572ac65-6c4e-2cc5-93d4-5a58b62b0f1a
* Version Independent ID: 71fd7c2b-7cb8-38ae-d347-f07c4644ae69
* Content: [List Indicators API - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/get-ti-indicators-collection)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/get-ti-indicators-collection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/get-ti-indicators-collection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by lindspea** [comment]
@nithinpaladion thank you for reaching out and helping improve MS Docs. Just to check, did you use the server closes to your geo location?

**Comment by lindspea** [comment]
@nithinpaladion please confirm if you have seen my response above, and if you still need assistance.

**Comment by illfated** [comment]
… and in case you return to this ticket, feel free to learn about MarkDown / GitHub Flavored MarkDown and its practical application in GitHub ticket comments:

```meta
{
    "@odata.context": "api.securitycenter.windows.com/api/$metadata#Indicators",
    "value": [
        {
            "id": "1",
            "indicatorValue": "1.1.1.1",
            "indicatorType": "IpAddress",
            "action": "AlertAndBlock",
            "createdBy": "username",
            "severity": "Medium",
            "category": 1,
            "application": null,
            "educateUrl": null,
            "bypassDurationHours": null,
            "title": "title",
            "description": "description",
            "recommendedActions": null,
            "creationTimeDateTimeUtc": "2020-10-30T12:09:40.7725623Z",
            "expirationTime": null,
            "lastUpdateTime": "2020-10-30T12:09:40.7725623Z",
            "lastUpdatedBy": null,
            "rbacGroupNames": [],
            "rbacGroupIds": [],
            "notificationId": null,
            "notificationBody": null,
            "version": null,
            "mitreTechniques": [],
            "historicalDetection": false,
            "lookBackPeriod": null,
            "generateAlert": true,
            "additionalInfo": null,
            "createdByDisplayName": "displayUser",
            "createdBySource": "source",
            "certificateInfo": null
        }
    ]
}
```
(example of MarkDown code block fence with syntax highlighting)
