### ISSUE TITLE
Examples required for "Supported Actions"

### ISSUE THREAD

**Issue by jimmyeao** [MicrosoftDocs/windows-itpro-docs#8632]
[Enter feedback here]
Frequent mention is made to "supported actions, add delete" etc but I can't see any guidance on how to correctly build this up - ie is the command encapsulated in a string, e,g, <<"/delete">> or is it added to the OMA-URI string?
It would be useful to have some examples
Sorry for the bad formatting, greater than signs are an issue in markup!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8b1b81d-3c35-0315-d149-f10af3a409b2
* Version Independent ID: c34e7acb-ece7-d76f-fb41-470e19119ee0
* Content: [VPNv2 CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp?redirectedfrom=MSDN)
* Content Source: [windows/client-management/mdm/vpnv2-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/vpnv2-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @jimmyeao ,
**Frequent mention is made to "supported actions, add delete" etc but I can't see any guidance on how to correctly build this up - ie is the command encapsulated in a string** - yes, exactly, like this:
```
      <Add>
        <CmdID>10003</CmdID>
        <Item>
          <Target>
            <LocURI>./Vendor/MSFT/VPNv2/VPNProfileName/NativeProfile/Authentication/UserMethod</LocURI>
          </Target>
          <Data>Eap</Data>
        </Item>
      </Add>
```
It would be useful to have some examples - there are some examples on the bottom of the article.
Please let me know if you have any other questions.
Thank you

**Comment by jimmyeao** [comment]
Hi thanks for getting back to me.
The examples do not appear to match up to how (for an example) a VPN profile would be removed. In MEM, the console here is expecting an XML file for the VPN profile only, with the OMA-URI being specified separately, and there is no obvious way to create a delete action here:
![image](https://user-images.githubusercontent.com/5197831/99884065-291a5080-2c23-11eb-90d5-a54287edb0b5.png)

The experience in the MEM console is not consistent with the examples in this article (https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp?redirectedfrom=MSDN) as the profile.xml does not contain the OMA-URI, merely the VPN settings.

**Comment by joinimran** [comment]
Hello @jimmyeao - Thank you for sharing your feedback about the document. I have reviewed the document and found that the document contains all of the required information with some of the most common examples. 

If there is something specific you are looking for please let us know. If you are having some challenges to do some configuration for this CSP please open up a support case with the Microsoft support team to better help you with the specific issue. 

Thanks.
Imran.

**Comment by jimmyeao** [comment]
@joinimran Thanks for taking the time to review, but unfortunately (for me!) this does not move me forwards. I engaged with our Fastrack expert on this, and they also have no details on how to delete a custom OMA-URI policy from a machine using MEM (intune). Perhaps I should be asking this question on the intune pages? would it just be as simple as putting `<delete></delete>` in the stringxml after defining the OMA-URI as per my example above?

**Comment by joinimran** [comment]
I am not sure about this. I would suggest you open up a support case with MS Team. @nam31 Can guide you on how you can quickly open a support case with MS. I have tried to find out if there is any possibility to use <delete> code in XML but there is no luck. This is something that MS support can answer or route your query to the internal team responsible for VPN handling in Windows 10.
Thanks
Imran.

**Comment by nam31** [comment]
@jimmyeao Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)
Thank you.
