### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by SeeingBlue** [MicrosoftDocs/windows-itpro-docs#8634]
[Enter feedback here]

The following quote is listed on the below page. This quote contains two links which result in 404 responses.
> Learn how to use Pool Monitor and how to use the data to troubleshoot pool leaks.

The links are: https://support.microsoft.com/help/177415 & https://blogs.technet.com/b/markrussinovich/archive/2009/03/26/3211216.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7aab622-1bde-637a-8999-cac5f3f68ac4
* Version Independent ID: 16af5e10-0748-ec6f-f539-2ee8563c3702
* Content: [Advanced troubleshooting for Windows-based computer freeze issues - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-windows-freeze#use-pool-monitor-to-collect-data-for-the-physical-computer-that-is-no-longer-frozen)
* Content Source: [windows/client-management/troubleshoot-windows-freeze.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/troubleshoot-windows-freeze.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Closest I could get for the URL text "use the data to troubleshoot pool leaks":
- https://docs.microsoft.com/en-us/archive/blogs/markrussinovich/pushing-the-limits-of-windows-paged-and-nonpaged-pool#tracking-pool-leaks

**Comment by illfated** [comment]
The support article is a dead end, at least as the page content and existence goes. WayBack Machine says "**Nothing found for this domain**".

**Comment by nam31** [comment]
Closing via #8640 
Thanks
