### ISSUE TITLE
Keep the smartcard service up and running on the servers

### ISSUE THREAD

**Issue by Tibiatgithub** [MicrosoftDocs/windows-itpro-docs#8635]
Hello ITPros,

We are experiencing issues on the server during smart card authentication using RDP. The following error popped up during the smartcard authentication using RDP after connecting to VPN/bastion host
"_No valid certificates were found on this smart card
Please try another smart card or contact your administrator._"

Specifically, when connecting to VPN using RDP Server, the security key does not work, and the issue can be temporarily fixed if we enable and start the smartcard service on the server we are trying to RDP but the service automatically stops after some time because the service start type is "Trigger start".  

We Would like to know if there is need of mini driver because the existing smartcard uses a minidriver which works in all cases, not depended on smartcard service of the servers. And also if there is any permanent fix to keep the smartcard service up and running on the servers or any other possibility for the authentication failure.

Thank you in advance for your help!

**Comment by nam31** [comment]
Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)
Thank you.

**Comment by illfated** [comment]
@Tibiatgithub : Just to provide you with additional suggested resources:

You may want to look elsewhere for answers, unless you have suggestions 
for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by
 providing the users a way to report factual errors,
 improvement suggestions and request updates for new versions.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/
