### ISSUE TITLE
HKEY_LOCAL_MACHINE\Policies registry path correct?

### ISSUE THREAD

**Issue by nnpcYvIVl** [MicrosoftDocs/windows-itpro-docs#864]
Many registry keys in this document reference `HKEY_LOCAL_MACHINE\Policies`

> e.g. Create a REG_DWORD registry setting named LetAppsAccessLocation in **HKEY_LOCAL_MACHINE\Policies\Microsoft\Windows\AppPrivacy** with a value of 2 (two).

Is this a mistake? Shouldn't they all be replaced with `HKEY_LOCAL_MACHINE\SOFTWARE\Policies`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8228962-7158-6be1-e791-e6535b88f343
* Version Independent ID: 46e4c7f3-e8b0-ebc9-da58-b69149803937
* Content: [Manage connections from Windows operating system components to Microsoft services (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/manage-connections-from-windows-operating-system-components-to-microsoft-services)
* Content Source: [windows/configuration/manage-connections-from-windows-operating-system-components-to-microsoft-services.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/manage-connections-from-windows-operating-system-components-to-microsoft-services.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic-msft**

**Comment by DaniHalfin** [comment]
Hi @nnpcYvIVl , thanks for raising this issue. It has been fixed.

**Comment by shortpatti** [comment]
Fixed
