### ISSUE TITLE
Note on Windows 10 page re SAC naming could be more clear around Windows Server

### ISSUE THREAD

**Issue by jeanfrancoislarente** [MicrosoftDocs/windows-itpro-docs#8646]
There's a note in this page:
> Note
>With this release and future releases, the Windows 10 release nomenclature is changing from a year and month pattern (YYMM) to a year and half-year pattern (YYH1, YYH2).

In some pages, WIndows Server information is grouped together and in others it's less clear. The above note mentions the future Windows 10 nomenclature but makes no mention of Windows Server. Although I assume this is to be the same, could someone clear this up somewhere on the Windows Server page(s) or address it in the above note?

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a31db82-81be-16aa-9e39-62c6810517d8
* Version Independent ID: 30fe7813-ac6e-8167-02d6-9fa5e530a3f6
* Content: [What's new in Windows 10, version 20H2 - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-20h2)
* Content Source: [windows/whats-new/whats-new-windows-10-version-20H2.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/whats-new-windows-10-version-20H2.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
This article is only about Windows 10, so it's a bit out of scope to discuss Windows Server. I understand though that it would be nice to understand how the naming change affects all Windows software releases. The statement about naming for Windows Server is here: https://docs.microsoft.com/en-us/windows-server/get-started/whats-new-in-windows-server-2004

It isn't quite as clear, but it does say that "Windows Server, version 20H2 is the next Semi-Annual Channel release of Windows Server, version 2004."
