### ISSUE TITLE
Skype for Business Integration

### ISSUE THREAD

**Issue by brianajensen1** [MicrosoftDocs/windows-itpro-docs#8649]
This setting is labeled Skype for Business Integration, but also talks about Outlook communication and now shouldn't this also control Teams communication?

I think this now needs to be labeled differently in the portal and the documentation needs to be updated as well to include Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cdec3d1-2aa7-c1c5-003f-a938ae32cd6f
* Version Independent ID: 84a60c18-6188-4712-f94c-e64a2a92d666
* Content: [Integrate Microsoft Defender ATP with other Microsoft solutions - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/threat-protection-integration)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/threat-protection-integration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/threat-protection-integration.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by joinimran** [comment]
Hello @brianajensen1 - Thank you for your feedback on this document. I have gone through the document and found that as of now the documentation looks good. Actually, Microsoft Defender for Office365 covers all the aspects of Outlook and MS Teams management. You can see more details on how Microsoft Defender for Office365 covers the Outlook and MS Teams communication at https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-atp?view=o365-worldwide

Hope this clarifies your concern. 

Thanks
Imran.

**Comment by brianajensen1** [comment]
Hi, thank you for the comment, however this issue with documentation is referring to Microsoft Defender for Endpoint, not Defender for Office 365.  The link to the specific section is https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/threat-protection-integration#skype-for-business

**Comment by joinimran** [comment]
@brianajensen1 - Maybe I was not able to define my comment correctly. As you have mentioned in the issues that "This setting is labeled Skype for Business Integration, but also talks about Outlook communication and now shouldn't this also control Teams communication?" 

I have answered that Outlook and MS teams come under the umbrella of Office365 and they are covered/protected by Microsoft Defender for Office365.

If there is any specific modification you are proposing in the document. Please let me know. I will make those changes and will send the feedback to the author of the document for review. 

Do you want this to be removed or if there should be any specific changes in the document you are looking for. Please let me know.

Thanks.
Imran.

**Comment by brianajensen1** [comment]
Sorry, I thought by referencing the documentation that it would be clear.

Microsoft Defender for Endpoint has, under Advanced Features, Skype for business integration (Enables 1-click communication with users (https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/advanced-features#skype-for-business-integration), however does this control Teams communications as well.  It states that it controls Outlook communications in the documentation, however the Skype for business integration button doesn't mention that in the Advanced features, nor does it mention Teams.  Please remember that SFB is being retired, so we need to know if this controls SFB and Teams now and what about future?

![2021-02-28_9-02-26](https://user-images.githubusercontent.com/50712269/109426675-b77d3b80-79a3-11eb-92d1-abe18e4219cc.png)

**Comment by joinimran** [comment]
Thank you for sharing this document and this clears everything. Please note that it only applies to Outlook as a communication medium. As of now, this is not available for Teams. If you wanted to see MS Teams there, I would suggest you to rise your voice using User Voice Channel. This will help Microsoft to add this in the future. 

@e0i - Please guide the user how to open a request in User Voice Channel.

Thanks.
Imran.
