### ISSUE TITLE
Please update this documentation to describe on how to enroll WVD virtual machines joined to Azure active directory domain services

### ISSUE THREAD

**Issue by SokoloffMaxim** [MicrosoftDocs/windows-itpro-docs#8652]
[Enter feedback here]
Please update this documentation to describe on how to enroll WVD virtual machines joined to Azure active directory domain services.

Currently there is no information/confirmation whether i can use MDM for WVD Win  10 Multisession  2009 VMs joined to Azure ADDS

Issue:
I enabled GPO to enroll my WVD WMS as described in this documentation , but getting this error:
http://prntscr.com/vklaxe

I m trying to follow your troubleshooting steps https://docs.microsoft.com/en-us/mem/intune/enrollment/troubleshoot-windows-enrollment-errors , and find some section related to 76 event id cod. Looks like i am having different type of issue.
Thank you in advance
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @SokoloffMaxim,
**Please update this documentation to describe on how to enroll WVD virtual machines joined to Azure active directory domain services.** - there is a dedicated article for WVD - https://docs.microsoft.com/en-us/mem/intune/fundamentals/windows-virtual-desktop

**Currently there is no information/confirmation whether i can use MDM for WVD Win 10 Multisession 2009 VMs joined to Azure ADDS** - currently it is not supported, as it is stated [here](https://docs.microsoft.com/en-us/mem/intune/fundamentals/windows-virtual-desktop#windows-10-enterprise-multi-session)

Thank you
