### ISSUE TITLE
Link for Windows 10 November 2019 AADMX needs to updated

### ISSUE THREAD

**Issue by bupton-advicent** [MicrosoftDocs/windows-itpro-docs#8655]
Link for Administrative Templates (.admx) for Windows 10 November 2019 Update (1909) needs to be https://www.microsoft.com/download/confirmation.aspx?id=100591 not https://www.microsoft.com/download/confirmation.aspx?id=1005915

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@bupton-advicent . thanks for pointing out. I am updating the link.

**Comment by bupton-advicent** [comment]
Thanks!



​
Brent Upton
Systems Engineer
Precision planning software
​for every planning strategy
Follow us:Twitter |LinkedIn 
CONFIDENTIALITY NOTICE: This e-mail, including attachments, is intended solely for the person or entity to which it is addressed and may contain confidential, privileged and/or proprietary information. Any review, dissemination, distribution, copying, printing, or other use of this e-mail by persons or entities other than the addressee or his/her authorized agent is prohibited. If you have received this e-mail in error, please contact the sender immediately and delete the material from your computer. You may notify this individual that you no longer wish to receive any commercial e-mails from this sender by replying to this e-mail or by sending a written request to 10700 W. Research Drive, Suite One, Attn: Marketing, Milwaukee, WI  53226.

**Comment by illfated** [comment]
The PR looks good to me, the link works fine as long as you want to start the download directly.

(Hmm, I forgot to check whether anyone knows if the link should lead to the download page without starting the download.)
