### ISSUE TITLE
Examples confusing and Private Use Unicode difficult to work with

### ISSUE THREAD

**Issue by PsychoData** [MicrosoftDocs/windows-itpro-docs#8656]
These examples are not explained, and are sometimes confusing. 
Some of the types of entries (including what seems like the most-commonly useful - SIDs - have no example) 

For example, it mentions that well-known group names are supported, but doesn't outline how to find the names or which names are well-known. If I wanted to add Hyper-V Admins, I should be able to use ```S-1-5-32-578``` but ```Hyper-V Administrators``` might also work. But if I made a Local Group "Project X", I would probably need to use it's SID, but maybe ```Project X``` would work, as long as they had a Project X group locally for it to find. Or perhaps ```Contoso\Project X``` would work for Hybrid-joined machines.

Looking at the lines with &#61440; or &#xF000; (```&#61440; or &#xF000;```, yes they are theoretically the same) - where is that Character coming from? It appears to be a "Private area use" [Code](https://unicode-table.com/en/search/?q=f000) unicode character - but what is that from? 
![image](https://user-images.githubusercontent.com/3719116/99409654-99417300-28bf-11eb-9479-f74e8d30c705.png)

Is that a hardcoded, high-unicode character, that this provider has to use, or can it be swapped for any separator that might be available and not so difficult to have to deal with encoding the high-unicode character? Which would allow something like ```Authenticated Users|Project X Group```. It isn't clear if this is just the field-separator you are required to use or just an arbitrary character. 

Additionally, browsers can have a bad habit of converting high/unknown unicode values to boxes, and there isn't a way to tell which box is the right box. For example, while I am writing this, I have three different versions of this copied to my clipboard, but I still don't know which, if any, is right. Usually the clipboard won't save duplicate entries, so even though they all come back as 61440 when I check them in https://unicodelookup.com / I feel like there is something different between them

![image](https://user-images.githubusercontent.com/3719116/99411887-1968d800-28c2-11eb-95eb-6961ed7af222.png)

Why are the SIDs listed like this ```*S-1-5-32-544``` - is the asterisk important?  There isn't an actual example using SIDs either, which should really get added, since SID is apparently the only way to add anything other than the well-known entities. 

How could you add Domain Accounts on Hybrid Joined machines? Only through SID? 

There is just a lot that is not outlined in this 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b62d452-1910-d962-0ccc-9ac3f8135f15
* Version Independent ID: 5a4e6f0c-bcd4-8d8b-93f7-5bda7135b931
* Content: [Policy CSP - UserRights - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-userrights#userrights-allowlocallogon)
* Content Source: [windows/client-management/mdm/policy-csp-userrights.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-userrights.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @PsychoData - Thank you for raising your concern, Please note that the document now has a link that is specific to SID structures and their values, please see https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/81d92bba-d22b-4a8c-908a-554ab29148ab this link is also added in the document for future reference. 

Specific to the character usage, there are many other peoples having the same concerns. I would request you to raise your voice using the Microsoft rise your voice channel for better implementation of this.

@e0i  FYI&A Please.
