### ISSUE TITLE
Please Update Support Information

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/windows-itpro-docs#8658]
When encountering problems where data does not flow into Log Analytics, this article appears to be unsupported.  Our support case was transferred from Intune, to Azure, to Log Analytics, to PowerBI teams over 4 weeks and 3 cases.  Each team saying it's not their responsibility.  Yesterday we were told that this "feature" is not supported under regular coverage and requires "paid support" to troubleshoot, and our 3rd support was closed.  Perhaps the first paragraph should remove "is the recommended method..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb8c41f-5e79-8310-3a2c-e2465d6aac96
* Version Independent ID: f517bcb0-3833-08b3-f3f4-75a732b3c629
* Content: [Update Compliance Configuration Script - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-configuration-script)
* Content Source: [windows/deployment/update/update-compliance-configuration-script.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-configuration-script.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by cinglis-msft** [comment]
@Skatterbrainz, that sounds super frustrating. Sorry to hear that. Please reach out to me directly chinglis@microsoft.com, we'll work with you directly.
