### ISSUE TITLE
Date needs to be corrected ; clarify applicable products

### ISSUE THREAD

**Issue by PeteHaigh-MSFT** [MicrosoftDocs/windows-itpro-docs#8662]
Howdy - the pub date is 2018! But with the coverage of DfE it is clearly much newer than that. 

It is also confusing that the doc is "Deploy and enable Microsoft Defender Antivirus" but the Applies to: only includes Microsoft Defender for Endpoint which is an additional licensed product. Please add Defender Antivirus to the bulleted list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95629861-d1e1-232c-5727-4ebc831f90d6
* Version Independent ID: f653f426-604c-30ed-b2c0-31b44c2f7117
* Content: [Monitor and report on Microsoft Defender Antivirus protection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/report-monitor-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/report-monitor-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/report-monitor-microsoft-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by VLG17** [comment]
@PeteHaigh-MSFT I guess the pub date is coming from when the article was published initially (during ATP times) and does not the GA date of DfE. Do you think it should?

Regarding your second point, although i understand the reasoning, i see that many other cases that talk about Microsoft Defendar Antivirus have under "Applies to:" DfE 

For example: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility

@nam31 I think it would be best to involve the content author here for more clarifications.

**Comment by PeteHaigh-MSFT** [comment]
Cheers for getting back to me. Yes publish date should reflect how current the page content is rather than original first publish date - unless the change was a minor correction (grammatical only for example).

And yes, we should be consistent so if it is agreed that we should list both products in "Applies to" then this should be changed everywhere it is relevant. Some of the pages may be DfE only but core antivirus docs will cover both.

**Comment by nam31** [comment]
@denisebmsft can you please give your inputs here?

**Comment by denisebmsft** [comment]
Hello @PeteHaigh-MSFT and thank you for your feedback. I'll get the "Applies to" section fixed.
