### ISSUE TITLE
Correction To Microsoft Defender SmartScreen "login", replace with "log in"

### ISSUE THREAD

**Issue by secdev-01** [MicrosoftDocs/windows-itpro-docs#8665]
[Enter feedback here]
`Microsoft Defender SmartScreen events appear in the Microsoft-Windows-SmartScreen/Debug login Event Viewer.`

s/b 

`Microsoft Defender SmartScreen events appear in the Microsoft-Windows-SmartScreen/Debug log in Event Viewer.`

log in , not login.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4edaae97-455b-d25a-9228-5309e24b4aa3
* Version Independent ID: d38e56a7-d553-e519-95a9-dc93e2cdc771
* Content: [Microsoft Defender SmartScreen overview (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview)
* Content Source: [windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Very good point. I wonder if we could even throw in a comma, just to make it very clear (or obvious):

`Microsoft Defender SmartScreen events appear in the Microsoft-Windows-SmartScreen/Debug log, in Event Viewer.`

Might not be preferable, but it highlights the existing sentence issue for me.

**Comment by illfated** [comment]
There you go. PR #8667 is ready for review, comments and general viewing.
