### ISSUE TITLE
Add 429

### ISSUE THREAD

**Issue by jmmowrer** [MicrosoftDocs/windows-itpro-docs#8666]
Please add 429 error code indicating quota exceeded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2901229-dd1d-32ea-6a18-afbc69567db9
* Version Independent ID: 360670a6-a010-1601-7a5b-61850e26fedf
* Content: [Common Microsoft Defender ATP API errors - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/common-errors)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/common-errors.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/common-errors.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by nam31** [comment]
Closing via #8708
