### ISSUE TITLE
Check Grammar

### ISSUE THREAD

**Issue by matambanadzo** [MicrosoftDocs/windows-itpro-docs#8669]
... see the main MIcrosoft Defender for EndpointP for Mac page for...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 369434e7-66ea-b756-fc21-0104b19a1cd9
* Version Independent ID: 06e0ba16-0dcf-a85c-7855-684892282e84
* Content: [Intune-based deployment for Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-install-with-intune)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-install-with-intune.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-install-with-intune.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Thanks. I will open a Pull Request to have that typo corrected, and the metadata description name updated as well.

**Comment by illfated** [comment]
There you go, PR #8675 is ready for review, browsing, comments, and suggestions, as you please. That PR will close this issue ticket when the commit is merged into the [`public`](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/public) branch of [MicrosoftDocs/windows-itpro-docs](https://github.com/MicrosoftDocs/windows-itpro-docs) .
