### ISSUE TITLE
Reference to 2016 in "System Center Configuration Manager, current branch (2016)" is confusing.

### ISSUE THREAD

**Issue by davidpaMSFT** [MicrosoftDocs/windows-itpro-docs#867]
What is "(2016)" in "System Center Configuration Manager, current branch (2016)" referring to? This should be removed as it is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea8a5770-37e4-d118-4178-1bbc9f94550d
* Version Independent ID: 214c6852-b2cc-d0d5-c07a-9e662707aa23
* Content: [Deploy, manage, and report on Windows Defender Antivirus](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/deploy-manage-report-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/deploy-manage-report-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/deploy-manage-report-windows-defender-antivirus.md)
* Service: **unspecified**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by andreabichsel** [comment]
Thank you for pointing this out! I changed the sentence, and changes should be live by noon PST tomorrow.
