### ISSUE TITLE
What about access from non-Windows devices such as Azure AD registered MacOS and mobile devices?

### ISSUE THREAD

**Issue by felinepc** [MicrosoftDocs/windows-itpro-docs#8674]
The documentation stated the requirements for access to Azure AD joined Windows 10 PCs via RDP from other Windows devices. But it does not mentioned access from non-Windows devices. For example, MacOS/iOS etc have official Microsoft RDP client apps, and they can be Azure AD registered as well. Is access from these devices supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10) - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @felinepc ,
in the article, it states:
**Your local PC (where you are connecting from) must be either Azure AD joined or Hybrid Azure AD joined if using Windows 10 version 1607 and above, or Azure AD registered if using Windows 10 version 2004 and above. Remote connections to an Azure AD joined PC from an unjoined device or a non-Windows 10 device are not supported.**

So for AAD-Joined - must be Win 10 1607 or newer, for AAD-registered - Win 10 2004 or newer, and non-windows 10 devices are not supported.
Thank you
