### ISSUE TITLE
Different OS on Sandbox possible?

### ISSUE THREAD

**Issue by msheets1** [MicrosoftDocs/windows-itpro-docs#8677]
Even if it's not, having an FAQ for things that are NOT possible can be just as helpful (Because it can help you end your quest -- I'm currently stuck trying to find an answer to that question... and even our official page doesn't have it. :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c06f3ef-5946-862a-ae14-f897fdb518ca
* Version Independent ID: cd6a8b99-b1e9-dff5-f174-a15840b304f0
* Content: [Windows Sandbox - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@msheets1 . Mention all the questions those are araised in your mind. Any of Our expert person will answer your questions.

**Comment by VLG17** [comment]
@msheets1 It's not possible to have a different OS on Windows Sandbox because Windows Sandbox is built upon the Windows 10 OS running on the machine. More details [here](https://techcommunity.microsoft.com/t5/windows-kernel-internals/windows-sandbox/ba-p/301849).

> Dynamically generated Image
> At its core Windows Sandbox is a lightweight virtual machine, so it needs an operating system image to boot from. One of the key enhancements we have made for Windows Sandbox is **the ability to use a copy of the Windows 10 installed on your computer**, instead of downloading a new VHD image as you would have to do with an ordinary virtual machine.

**Comment by nam31** [comment]
@msheets1 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
