### ISSUE TITLE
Can't join to AD Domain

### ISSUE THREAD

**Issue by esenciatech** [MicrosoftDocs/windows-itpro-docs#868]
After upgrade to Win 10 v 1803. We can't join to Windows AD. 
=== error ===
Note: This information is intended for a network administrator.  If you are not your network's administrator, notify the administrator that you received this information, which has been recorded in the file C:\WINDOWS\debug\dcdiag.txt.

The domain name "domain" might be a NetBIOS domain name.  If this is the case, verify that the domain name is properly registered with WINS.

If you are certain that the name is not a NetBIOS domain name, then the following information can help you troubleshoot your DNS configuration.

DNS was successfully queried for the service location (SRV) resource record used to locate a domain controller for domain "alien":

The query was for the SRV record for _ldap._tcp.dc._msdcs.alien

The following domain controllers were identified by the query:

DC1
DC02

However no domain controllers could be contacted.

Common causes of this error include:

- Host (A) or (AAAA) records that map the names of the domain controllers to their IP addresses are missing or contain incorrect addresses.

- Domain controllers registered in DNS are not connected to the network or are not running.

===== end of error ====

We check AD, DNS and WINS and it is correct. 

We revert to previous version, join to domain is fine. 

Please help!

**Comment by andreabichsel** [comment]
Hi, the best way to get help is to contact Microsoft Support (https://support.microsoft.com/en-us/contactus/), or you can post in the Forum (https://social.technet.microsoft.com/Forums/windows/en-US/home?forum=win10itprogeneral).
