### ISSUE TITLE
3rd bullet point in Requirements section is confusing, and linked page is unrelated to the link's text

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/windows-itpro-docs#8682]
The 3rd bullet point is this:

> The enterprise AD must be registered with Azure Active Directory (Azure AD)

The text "registered with Azure Active Directory (Azure AD)" is linked to https://docs.microsoft.com/en-us/windows/client-management/mdm/azure-active-directory-integration-with-mdm

The linked page contains basically no information about registering your "enterprise AD" with Azure AD.  Instead, that page is a somewhat convoluted set of sections that are sort of unrelated to anything specific.  The entire page could almost stand to be deleted, and this requirement entry on this page could stand to also be deleted.

If this requirements bullet point is supposed to be asking for something else it should be clarified.  If not, it should be deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Would this page be a better suggestion for that link?
- https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/azure-ad (**Integrate on-premises Active Directory domains with Azure Active Directory**)

**Comment by JeremyTBradshaw** [comment]
@illfated Yes, that is perfect.  Thanks.  I think the bullet point itself is a little obvious considering the context, but it's a fair point to state and with the link you suggested, at least it lines up and makes sense.

**Comment by illfated** [comment]
Very well, thank you for your feedback. I am planning on making a PR to suggest the link URL change.

Besides the link change, would you be able to formulate more direct suggestions of any further changes mentioned in your main ticket comment above?

**Comment by JeremyTBradshaw** [comment]
I think this could be an improved version of that 3rd bullet point could be:

> - On-premises AD must be [integrated with Azure AD (via Azure AD Connect)](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/azure-ad)

I opted for "AD" and "Azure AD" versus spelling them out whereas they are already abbreviated this way in other text on the same page, so I think it's a worthy and safe move.  Feel free to go with that, or even keep it as is, but with the updated link you suggested, which is the correct one for the point being made in the bullet.

Thanks again.

**Comment by illfated** [comment]
Ref. #8715 and PR commit https://github.com/illfated/windows-itpro-docs/commit/8a7931d2561dad5f7ffa2ec61008a9b7377e9f20 .

**Comment by illfated** [comment]
There you go. PR #8715 is ready for review, browsing, suggestions and comments.
