### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by cwmoriarty** [MicrosoftDocs/windows-itpro-docs#8683]
"Erin M. Hagens" is split into three tokens: "Erin", "M", and "Havens"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5128d9a-e02a-df9b-24cc-32711ad37b54
* Version Independent ID: fecafb19-6b37-1f2e-ba3d-5e0bf0d49d09
* Content: [Password must meet complexity requirements (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements)
* Content Source: [windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by cwmoriarty** [comment]
also 'grin'...

**Comment by RAJU2529** [comment]
@cwmoriarty . Thanks for pointing out . I am fixing it now.
