### ISSUE TITLE
Dead link to Dropping the “Untrusted Font Blocking” setting

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/windows-itpro-docs#8687]
The Related Content section of the article has a link to [Dropping the “Untrusted Font Blocking” setting](https://blogs.technet.microsoft.com/secguide/2017/06/15/dropping-the-untrusted-font-blocking-setting/) but that link redirects to <https://docs.microsoft.com/en-us/archive/blogs/content-removed>. The correct address seems to be <https://techcommunity.microsoft.com/t5/microsoft-security-baselines/dropping-the-quot-untrusted-font-blocking-quot-setting/ba-p/701068>.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91a1567e-cc12-b203-65ac-5023aa3997f7
* Version Independent ID: 946c6dcf-3ee7-47c3-a973-edbf955da875
* Content: [Block untrusted fonts in an enterprise (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/block-untrusted-fonts-in-enterprise)
* Content Source: [windows/security/threat-protection/block-untrusted-fonts-in-enterprise.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/block-untrusted-fonts-in-enterprise.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Thank you, both for reporting the 404 error and for suggesting the replacement URL. Will fix.
