### ISSUE TITLE
Register domian joined computers as devices - Work Place Join deprected as of 1607?

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/windows-itpro-docs#869]
I am curious if the Work Place Join GPO - Register domain joined computers as device is unneeded and deprecated as of 1607?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Service: **unspecified**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by tijs0289** [comment]
I was wondering the exact same. We initially tried that one but it seems we need AD connect for that. We don't want AD Connect as we use AD DS.
These terms like workplace/hybrid join are made more confusing for admins and users every day.

**Comment by e0i** [comment]
@MariciaAlforque Any further clarifications or updates regarding this issue? We would like to follow up. Thanks.

**Comment by egallagh** [comment]
I do not have any updates on this other than to say that 1607 is no longer supported. Recommend closure.

**Comment by e0i** [comment]
Hello @hoyty76 ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
