### ISSUE TITLE
Query if this reflects the current configuration of MEM

### ISSUE THREAD

**Issue by Jlouden9** [MicrosoftDocs/windows-itpro-docs#8693]
The Instructions for MEM don't align with the portal. Currently if you go to Endpoint Security -> AntiVirus - >Realtime Protection there is a setting call "Turn On Network Protection". Which of these is the correct method to enable Network Protection?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71868539-63d8-b250-f9d4-83a4052f4f74
* Version Independent ID: ed5658cf-173f-47bf-ed76-a68d89ea5c4b
* Content: [Turn on network protection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/enable-network-protection)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/enable-network-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/enable-network-protection.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by MaratMussabekov** [comment]
Hello @Jlouden9 ,
for me, MEM shows exactly the same options as described in the article.
Could you please provide more details, where is this option presented in AntiVirus section?

Thank you

**Comment by MaratMussabekov** [comment]
Hello @Jlouden9 ,
Could you please provide more details, where is this option presented in AntiVirus section? I am not able to find it

Thank you

**Comment by levinec** [comment]
Hi @Jlouden9, the instructions in the documentation are accurate and will guide you to the correct place to turn on network protection.

I tried to follow your path, but didn't find "Realtime Protection". Closing this issue for now.
![image](https://user-images.githubusercontent.com/40870842/103709682-0096ad80-4f68-11eb-8d7a-f809d0d9c92a.png)
