### ISSUE TITLE
Unclear "Important" note at the end of doc

### ISSUE THREAD

**Issue by Ayrezy** [MicrosoftDocs/windows-itpro-docs#8695]
The important note at the end of the doc to say that when using endpoint DLP Defender AV has real-time protection turned on is unclear on impact for those using 3rd party AV. The note seems to suggest that that Defender AV will go to real-time protection even in passive mode, which may indicate that it would conflict with a 3rd party AV. My understanding is that endpoint DLP has a special real-time protection mode and can still run side by side with a 3rd party AV. It would be good to update and add another line to be clear on impact with 3rd party AV. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b88aee4-6727-fa98-1180-29708eea027e
* Version Independent ID: 374c671b-b21c-6eac-d887-892491357eb2
* Content: [Microsoft Defender Antivirus compatibility with other security products - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility?source=docs#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @Ayrezy and thanks for raising this question. I'll follow up on this.

**Comment by VLG17** [comment]
@Ayrezy My understanding is that Defender AV in passive mode will not conflict with 3rd party AV installed on the endpoint, as described [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/defender-compatibility). Going further, since Endpoint DLP depends on Defender AV real-time protection, that would imply that Endpoint DLP will not conflict with 3rd party AV solutions.

> If an onboarded device is protected by a third-party antimalware client, Microsoft Defender Antivirus on that endpoint will enter into passive mode.

> Microsoft Defender Antivirus will continue to receive updates, and the mspeng.exe process will be listed as a running a service, **but it will not perform scans and will not replace the running third-party antimalware client**.
> 
> **The Microsoft Defender Antivirus interface will be disabled, and users on the device will not be able to use Microsoft Defender Antivirus to perform on-demand scans or configure most options.**

Do you think adding a link to the above would provide more clarity in the article you referenced in this issue?

**Comment by Ayrezy** [comment]
Hi,

I'm not sure it does to be honest and this is where the confusion comes in.

If a customer is using Defender for Endpoint (ATP) then we support passive mode as per this link: Microsoft Defender Antivirus compatibility with other security products - Windows security | Microsoft Docs<https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility#antivirus-and-microsoft-defender-for-endpoint>. In which case, we have generally have compatibility with the 3rd party AV as Defender AV is running in the background not with real time protection enabled. However, we only support passive mode when Defender for Endpoint is used (extra subscription), and if a customer does not have this subscription then when a 3rd party AV is installed Defender AV goes into auto-disabled mode.

The note in the article I refer to states that even when passive mode is configured (as with Defender for Endpoint) we enter real time protection mode. As far as I understand we also put the AV into real-time protection mode when auto-disabled without Defender for Endpoint.

The suggestion in the note is that Defender will go into real-time protection mode which counters the notion in the other articles that the AV is in passive or auto-disabled and therefore won't conflict. From what I understand though even though Defender goes into real-time protection mode we go into a special real time protection mode that isn't actively scanning and will not conflict with a 3rd party AV (even though we enter this real time mode).

We clarify this in this post here: Extend data loss prevention to your devices with Microsoft Endpoint Data Loss Prevention, now generally available - Microsoft Security<https://www.microsoft.com/security/blog/2020/11/10/extend-data-loss-prevention-to-your-devices-with-microsoft-endpoint-data-loss-prevention-now-generally-available/>

In addition, we heard feedback from some of you that you’d like to be able to leverage your existing security investments. Endpoint DLP integrates with Microsoft Defender for Endpoint, but it is also compatible with most anti-virus software, which enables you to have a choice and extend the investments you’ve already made.

So I suppose my ask is, do we add a note to say - even though the AV is in real-time protection mode if a 3rd party AV is registered on the system there should not be a conflict.

I hope this makes sense.

Thanks

Chris


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by nam31** [comment]
Closing via #8768
