### ISSUE TITLE
MDT docs - Create a Win 10 ref image

### ISSUE THREAD

**Issue by gerdesj** [MicrosoftDocs/windows-itpro-docs#8696]
In the section entitled: _Edit the Unattend.xml file for Windows 10 Enterprise_, there is an important information box regarding patching the product with WSIM 1903 update.  The current version of ADK is 2004 and that update is not needed.  There is a lot of information on that page and when following it for the first time, it is easy to overlook that.  I did!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0eb8c97-caa0-bb05-4b91-14ad2adc4aac
* Version Independent ID: 0cc541a3-8198-c029-d795-308e673ee2f4
* Content: [Create a Windows 10 reference image (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image)
* Content Source: [windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@gerdesj , Thanks for pointout, But WSIM1903 update is only needed for those users installed ADK 1903  and they didn't installed ADK 2004.

**Comment by greg-lindsay** [comment]
I will add to the note with information saying this only applies to ADK version 1903 
https://docs.microsoft.com/en-us/windows-hardware/get-started/what-s-new-in-kits-and-tools#whats-new-in-the-windows-adk-for-windows-10-version-1903
