### ISSUE TITLE
Sysvol Exclusions - Path to files

### ISSUE THREAD

**Issue by gruppenrichtlinien** [MicrosoftDocs/windows-itpro-docs#8697]
Automatic exclusions for SYSVOL files:
%systemroot%\Sysvol\Domain\*.adm
%systemroot%\Sysvol\Domain\*.admx
%systemroot%\Sysvol\Domain\*.adml
%systemroot%\Sysvol\Domain\Registry.pol
%systemroot%\Sysvol\Domain\*.aas
%systemroot%\Sysvol\Domain\*.inf
%systemroot%\Sysvol\Domain\*.Scripts.ini
%systemroot%\Sysvol\Domain\*.ins
%systemroot%\Sysvol\Domain\Oscfilter.ini

Shouldn´t it be:
%systemroot%\Sysvol\Domain\Policies\*\ADM\*.adm
%systemroot%\Sysvol\Domain\Policies\PolicyDefinition\*.admx
%systemroot%\Sysvol\Domain\Policies\PolicyDefinition\*\*.adml
%systemroot%\Sysvol\Domain\Policies\*\Registry.pol
%systemroot%\Sysvol\Domain\Policies\*\Machine\Applications\*.aas
%systemroot%\Sysvol\Domain\Policies\*\Machine\Microsoft\Windows NT\SecEdit\*.inf
%systemroot%\Sysvol\Domain\Policies\*\Machine\Microsoft\Windows NT\Audit\*.csv
%systemroot%\Sysvol\Domain\Policies\*\Machine\Scripts\Scripts.ini

install.ins is from IE Maintainance, oscfilter.ini is from Remote Install Service and both are obsolet

Or is the %systemroot%\Sysvol\Domain\*.admx recursive and valid for all *.admx within the path?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9b6379-e575-9819-eca1-a0952f66b655
* Version Independent ID: 34d81602-ffa2-5be6-67ef-b42b3b6f17ee
* Content: [Configure Microsoft Defender Antivirus exclusions on Windows Server 2016 or 2019 - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-server-exclusions-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/configure-server-exclusions-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/configure-server-exclusions-microsoft-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
> Automatic exclusions for SYSVOL files:
> %systemroot%\Sysvol\Domain*.adm
> %systemroot%\Sysvol\Domain*.admx
> %systemroot%\Sysvol\Domain*.adml
> %systemroot%\Sysvol\Domain\Registry.pol
> %systemroot%\Sysvol\Domain*.aas
> %systemroot%\Sysvol\Domain*.inf
> %systemroot%\Sysvol\Domain*.Scripts.ini
> %systemroot%\Sysvol\Domain*.ins
> %systemroot%\Sysvol\Domain\Oscfilter.ini
> 

I have done a superficial search, but not yet found exactly the rules for how the asterisk (`*`) works in the exclusion lists. I just thought it could be useful for this issue ticket to have the correct path details in your quote. Please note that your quoted lines seem to be missing a backslash in each line, right after `%systemroot%\Sysvol\Domain`:

***

#### SYSVOL files

- `%systemroot%\Sysvol\Domain\*.adm`
- `%systemroot%\Sysvol\Domain\*.admx`
- `%systemroot%\Sysvol\Domain\*.adml`
- `%systemroot%\Sysvol\Domain\Registry.pol`
- `%systemroot%\Sysvol\Domain\*.aas`
- `%systemroot%\Sysvol\Domain\*.inf`
- `%systemroot%\Sysvol\Domain\*.Scripts.ini`
- `%systemroot%\Sysvol\Domain\*.ins`
- `%systemroot%\Sysvol\Domain\Oscfilter.ini`

***

Regular wildcard definition usually dictates that this only applies to the first name part of the listed file names, but the rules might be different in Microsoft Defender Antivirus. I just don't know what the case is here.

**Comment by denisebmsft** [comment]
Thank you @nam31 for raising this issue, and @illfated for your help. I'll reach out to the appropriate program managers to confirm what we should have in the content, and I'll post an update here soon.

**Comment by illfated** [comment]
Thanks to @gruppenrichtlinien for reporting this issue (@nam31 works for the MS Docs team as a case handler, as far as I know).

**Comment by denisebmsft** [comment]
Thanks all for your help! I got a little help from a PM and have updated the article. Changes will render live later today (at around 4 p.m. Pacific Time). Please let me know if there are any other issues with the article. Thanks again!
