### ISSUE TITLE
SetupDiag cannot handle large log files

### ISSUE THREAD

**Issue by Anoni-Mouse** [MicrosoftDocs/windows-itpro-docs#8701]
Hello
Several Windows 7 fail the IPU to Windows 10 and rollback. I used SetupDiag to diagnose the Panther folder but this folder is so huge (around 1.7 GB) and Setupact.log is larger than 260 MB. The tool fails to diagnose such large files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ad81361-15d8-0e95-9d5f-090dbf270f10
* Version Independent ID: c0c32397-d5d6-cce1-79fd-c310bec05240
* Content: [SetupDiag - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/upgrade/setupdiag)
* Content Source: [windows/deployment/upgrade/setupdiag.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/setupdiag.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
Hello,

Looks like this question can best be answered via relevant [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channels. 

Please consider checking with [Microsoft Community](https://answers.microsoft.com/en-us/windows/forum/windows_10) or [contacting support](https://support.microsoft.com/contactus) for your problem; The issues section of this repository is for content fixes in documentation.

If you feel that the associated article also needs to be updated for any reason feel free to re-open this issue or [contribute with a pull request](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/CONTRIBUTING.md).

Thank you.

**Comment by ScottHendrix-MSFT** [comment]
The best way to get help for SetupDiag is to submit Feedback via the Feedback Hub and include the word SetupDiag in the title.

Yes, SetupDiag does have issues parsing large log files, but 260 MB is not large enough to trip it up in my testing.  Windows has a process limit of 2GB and SetupDiag will fail when the logs are near that 2GB size.  I have done some work in this space to make it better, but its not really fixed.
