### ISSUE TITLE
Referencing the old concept of hybrid Intune

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/windows-itpro-docs#8703]
I tried editing the page directly but got a 404 error so I'll leave my comment as feedback instead.
We write "Configuration Manager (MEMCM) standalone or _hybrid mode_ with Intune" which isn't in use anymore. Ref: https://docs.microsoft.com/en-us/mem/configmgr/mdm/understand/what-happened-to-hybrid

We should reference a cloud attached or Co-Managed configuration instead.

/Anders

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3135ceea-f682-4667-6b91-4f30ac30eca7
* Version Independent ID: 4bfb7b1e-bd5c-798a-cf8c-409adea2efa9
* Content: [Create a WDAC policy for fully-managed devices (Windows 10) - Windows security](https://review.docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/create-wdac-policy-for-fully-managed-devices)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/create-wdac-policy-for-fully-managed-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/create-wdac-policy-for-fully-managed-devices.md)
* Product: **w10**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Fair enough, I will open and create a PR to suggest the change.
