### ISSUE TITLE
Missing value for UPN as SAN when creating the SCEP profile

### ISSUE THREAD

**Issue by shanjin90** [MicrosoftDocs/windows-itpro-docs#8706]
[Enter feedback here]
When i followed the doc to do the configuration, it failed to create the SCEP profile. the issue is at step 14:
14 Specify User Principal Name (UPN) as a Subject Alternative Name value. **Need to type value as {{UserPrincipalName}}**
Also, the screenshot still reflects the old Intune portal. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f709fd4-0b5d-b238-4060-222d550cd538
* Version Independent ID: fb3f29da-2236-c47d-6bea-8efbcec8d7d3
* Content: [Using Certificates for AADJ On-premises Single-sign On single sign-on - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by nam31** [comment]
Closing via #8732
