### ISSUE TITLE
New Profile Type in Intune

### ISSUE THREAD

**Issue by ThomasKur** [MicrosoftDocs/windows-itpro-docs#8711]
In the section on how to configure Credential Guard with Intune only the Endpoint Protection Profile is mentioned. There is also a Profile in the Endpoint Security Section called Account Protection which provides this option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#enable-windows-defender-credential-guard-by-using-intune)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **v-tea**

**Comment by nam31** [comment]
Closing via #8800 
Thank you
