### ISSUE TITLE
Reversion to insecure blob storage wildcard addresses

### ISSUE THREAD

**Issue by phillym** [MicrosoftDocs/windows-itpro-docs#8712]
Hi there,

Back in 2019 I raised a ticket to get the MDATP (DfE) documentation to remove recommendations for excluding *.blob.core.windows.net from proxy auth and TLS interception. https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4942

Now this page is recommending this exclusion again for down-level DfE clients. Specifically for MMA which is required for down-level versions of Windows (Server 2016 and older). https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet#microsoft-monitoring-agent-mma---proxy-and-firewall-requirements-for-older-versions-of-windows-client-or-windows-server

Can you please do your best to refine this list to actual required endpoint DNS names, at the very least a wildcard pattern that doesn't open up all of Azure Blob storage?

The reasons for this are two-fold:
1. Prevent opening up a data exfiltration vector for devices affected by the proxy auth exclusion
2. Allow for firewall rules that use DNS lookups to populate dynamic firewall objects (these won't work with wildcarded DNS names for obvious reasons)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83207fc9-2c91-eb07-4237-6bb1f42e3778
* Version Independent ID: 5db33cf3-2dcb-bb33-a252-3a13ca9737f9
* Content: [Configure device proxy and Internet connection settings - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by phillym** [comment]
My apologies, this was fixed a month prior to me logging this issue:
https://github.com/MicrosoftDocs/windows-itpro-docs/commit/512f91cd651220c31c5d92496e8bfe3120655bef
I will close this issue. Thanks for all of the good work team!

**Comment by illfated** [comment]
We appreciate the community effort. Thank you for your feedback. Thank you also for being considerate and following up on your ticket.
