### ISSUE TITLE
https://photos.app.goo.gl/Ed5j4nNRtJohRq9z6

### ISSUE THREAD

**Issue by Anthony3881** [MicrosoftDocs/windows-itpro-docs#8717]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eac5b31-35fd-b4af-8fe2-90edba89b647
* Version Independent ID: e34049b2-9a2d-bece-2752-48fcb49e0cf4
* Content: [Diagnostic Data Viewer for PowerShell Overview (Windows 10) - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/microsoft-diagnosticdataviewer)
* Content Source: [windows/privacy/Microsoft-DiagnosticDataViewer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/Microsoft-DiagnosticDataViewer.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
"spam". Sort of funny, though.

#please-close
