### ISSUE TITLE
Cannot get it working

### ISSUE THREAD

**Issue by alenat10** [MicrosoftDocs/windows-itpro-docs#8718]
The Deployment guide is cumbersome. With multiple branches and unclear instructions. I have a Hybrid scenario with ADFS and could not find any clear guidance even after multiple tries; it looks like the guide is mostly oriented to AAD Connect only environment. My suggestions would be to provide several end-to-end manuals; some parts will be the same in those docs, but at least the sequence will be clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7fada9e-af96-ceee-137d-ce6e83241518
* Version Independent ID: d424587b-8451-76ba-b572-cd7298e045fa
* Content: [Hybrid Key Trust Deployment (Windows Hello for Business) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by nam31** [comment]
@alenat10 Thank you for providing feedback.
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
Thank you for your contribution to make the docs better! Much appreciated!
