### ISSUE TITLE
This page is showing the documentation code rather than the intended formatted output

### ISSUE THREAD

**Issue by bryhall** [MicrosoftDocs/windows-itpro-docs#872]
The page is showing most of the content as HTML code rather than its intended formatted output.  It looks correct in GitHub, but not on docs.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1b01ebb-0239-2f68-9934-ee6690825af3
* Version Independent ID: 893e002a-9da5-3cd9-3880-3365abc76474
* Content: [How to Deploy the App-V 5.0 Server Using a Script](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/appv-v5/how-to-deploy-the-app-v-50-server-using-a-script)
* Content Source: [mdop/appv-v5/how-to-deploy-the-app-v-50-server-using-a-script.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/appv-v5/how-to-deploy-the-app-v-50-server-using-a-script.md)
* Service: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by andreabichsel** [comment]
Hi, the best way to get help is to contact Microsoft Support (https://support.microsoft.com/en-us/contactus/), or you can post in the Forum (https://social.technet.microsoft.com/Forums/windows/en-US/home?forum=win10itprogeneral).

**Comment by lizap** [comment]
Thanks for raising this issue - we've updated the article so the table is formatted correctly. Thank you!
