### ISSUE TITLE
CSP Policy - Authentication/AllowEAPCertSSO

### ISSUE THREAD

**Issue by Kouky1** [MicrosoftDocs/windows-itpro-docs#8720]
Hello,

I am implementing Windows 10 native VPN (ikev2) with cert-based authentication to on-premise (gw is fortigate)

When VPN connects, it will add *Session cert-based credentials to Credential Manager, so it is trying to enforce this type of authentication also for on-premise resources.

But some resources support only NTLM (SSO) - Only option how to disable of enforcing cert-based authentication for on-premise resources and be able to authenticate via NTLM is registry key MACHINE\System\CurrentControlSet\Control\Lsa\DisableDomainCreds which disable Credential Manager from caching credentials.

I also found CSP Policy Authentication/AllowEAPCertSSO which should do what I need but it has no effect.

Does anybody know more information about the purpose of this policy ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 845fc177-23cf-0b2c-4b2b-5ac3966763a6
* Version Independent ID: ef4248eb-9b9f-24ec-631e-d65ae2ae3ecf
* Content: [Policy CSP - Authentication - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-authentication#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-authentication.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-authentication.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @Kouky1 - Thank you for putting your query. Can you please confirm what is OS version.

Thanks.
Imran.

**Comment by joinimran** [comment]
Hello @Kouky1 - I am waiting for your information so that I can better help you and we can make this documentation more helpful for everyone. 

Thanks.
Imran.

**Comment by Kouky1** [comment]
Hello, I just tested it again, it is Windows 10.0.19042.685 Enterprise.

**Comment by joinimran** [comment]
Hello @Kouky1 - Thank you for sharing the required details. I have checked and couldn't found any better suggestion but the best way to get this rolling out is to contact the Microsoft support team. Microsoft support team will better help to route this issue to the concerned team within Microsoft.

@nam31 - Can you please guide @Kouky1 on how to contact the Microsoft support team.

Thanks.
Imran

**Comment by nam31** [comment]
@Kouky1
Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)
Thank you.
