### ISSUE TITLE
specified syntax not working: mdatp config passive-mode enabled

### ISSUE THREAD

**Issue by bencze1** [MicrosoftDocs/windows-itpro-docs#8721]
Hi

From this page I have tried following command:
 mdatp config passive-mode enabled

I get the following error:
Configure passive mode:
  --value arg           Accepted values: enabled, disabled

Something looks to be wrong ith the help page or my mdatp, may I add, the error message is also a bit unclear. :)
Trying with versions 101.04.76 and 101.12.99.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbd62860-4e23-8fe8-d23a-51893c1ccf2a
* Version Independent ID: d487bc8c-4ad8-0ffe-07cf-4c1cee4fd3be
* Content: [Microsoft Defender ATP for Linux resources - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-resources)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-resources.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @bencze1 - Looks like the command is asking to input argument --value. Can you please try the following command?

**mdatp config passive-mode --value enabled** and see how it goes.

Thanks 
Imran.

**Comment by bencze1** [comment]
That does actually work. Googling on the string that's the syntax given in the Mac document, the Linux document said:

Configuration | Turn on/off AV passive mode | mdatp config passive-mode [enabled\|disabled]

I experimented back when I needed this and solved it by using the following syntax:
mdatp --config passiveMode on
which is kind of a completely different thing I'm not even sure where or how I found it.
So apparently the funtionality is there it's just the article that needs adjustment.
Thanks for getting back to me.

![image](https://user-images.githubusercontent.com/25345171/101883381-77be6900-3b97-11eb-942f-6f8ec9e12039.png)

**Comment by illfated** [comment]
(ref. #8798 )

**Comment by konstruktoid** [comment]
Ref https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8822

**Comment by nam31** [comment]
Closing via #8797
