### ISSUE TITLE
Could not configure windows explorer policy settings using OMA-URI

### ISSUE THREAD

**Issue by yogeshasalkar** [MicrosoftDocs/windows-itpro-docs#8722]
[Hi Team,
I was configuring the following settings but I am getting an error Remediation Failed (system cannot find specified file) 0x87d1fde8 as shown in the screenshot.

Are the OMA-URIs right? Anything I'm Missing?

https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-admx-windowsexplorer

OMA-URI : ./User/Vendor/MSFT/Policy/Config/ADMX_WindowsExplorer/NoViewContextMenu  
Value Integer: 1

OMA-URI : ./User/Vendor/MSFT/Policy/Config/ADMX_WindowsExplorer/NoDrives  
Value Integer: 67108863

OMA-URI : ./User/Vendor/MSFT/Policy/Config/ADMX_WindowsExplorer/NoViewOnDrive
Value Integer: 67108863

OMA-URI : ./User/Vendor/MSFT/Policy/Config/ADMX_WindowsExplorer/NoNetConnectDisconnect
Value Integer: 1

![Intune admx](https://user-images.githubusercontent.com/50020908/100611136-d7667a00-3336-11eb-83c9-01bea99f0053.JPG)

 ] 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe02a28-215f-f176-6086-8e79fcb48471
* Version Independent ID: f9143995-669d-be4d-3632-be2d0517d452
* Content: [Policy CSP - ADMX_WindowsExplorer - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-admx-windowsexplorer)
* Content Source: [windows/client-management/mdm/policy-csp-admx-windowsexplorer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-admx-windowsexplorer.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@yogeshasalkar Are you still seeing this error? 

Could you try to collect the MDM diagnostic logs [as described here](https://docs.microsoft.com/en-us/windows/client-management/mdm/diagnose-mdm-failures-in-windows-10) and see if you can find more details?

Could you also check it's not a text formating issue of the path that you used in the OMA-URI?

**Comment by yogeshasalkar** [comment]
Issue has been resolved after more research. These settings are applicable on Latest insider preview build.

Thanks for No Help 😅
