### ISSUE TITLE
king860619

### ISSUE THREAD

**Issue by king860619** [MicrosoftDocs/windows-itpro-docs#8723]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f784502-84dc-1122-eab4-1eeeb08da046
* Version Independent ID: 21f210a7-4c38-8f62-0226-121562617fef
* Content: [Memory integrity - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/memory-integrity)
* Content Source: [windows/security/threat-protection/device-guard/memory-integrity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/device-guard/memory-integrity.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by illfated** [comment]
Looks like a test comment. No useful information provided.

#please-close
