### ISSUE TITLE
Targeted Release freeze for 20H2

### ISSUE THREAD

**Issue by jgossvmware** [MicrosoftDocs/windows-itpro-docs#8724]
If we wanted to freeze the OS to stay at 20h2 for 30 months, using MDM,  What XML settings can be used, previously we have been using 
https://github.com/vmware-samples/euc-samples/blob/master/Windows-Samples/Custom%20Settings/Windows%20Update%20for%20Business/TargetVersion-2004.xml

In the XML we are entering 20h2 and that does not appear to be supported. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a31db82-81be-16aa-9e39-62c6810517d8
* Version Independent ID: 30fe7813-ac6e-8167-02d6-9fa5e530a3f6
* Content: [What's new in Windows 10, version 20H2 - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-20h2)
* Content Source: [windows/whats-new/whats-new-windows-10-version-20H2.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/whats-new-windows-10-version-20H2.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
I am researching now. Stay tuned.

**Comment by jgossvmware** [comment]
@greg-lindsay Thank you  I will look forward to your findings.

**Comment by greg-lindsay** [comment]
I've confirmed that this is a bug and it is going to be resolved soon. However at this time it isn't possible to use the XML file because the CSP rejects the "H" letter.  A workaround for now is to use deferrals. I am sorry I don't have an ETA on fixing this but I personally think it won't be too long, on the order of weeks rather than months.
