### ISSUE TITLE
Targeted Release CSP

### ISSUE THREAD

**Issue by jgossvmware** [MicrosoftDocs/windows-itpro-docs#8725]
Will this CSP have support for 20H2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ca58bd-f279-7739-0140-c4bd56784768
* Version Independent ID: 1d2ecc90-58a3-6bcd-84ae-ef04d7a3b7b4
* Content: [Policy CSP - Update - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update?source=docs#update-targetreleaseversion)
* Content Source: [windows/client-management/mdm/policy-csp-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
According to [this article](https://docs.microsoft.com/en-us/windows/client-management/mdm/new-in-windows-mdm-enrollment-management), the CSP policy  **Update/TargetReleaseVersion** has been added starting with Windows 10, Version 1803 and is included in all newer releases.

Have you checked with 20H2 and could not find it?

**Comment by VLG17** [comment]
@jgossvmware I did not tag you previously. Could you have a look please and share your thoughts?

**Comment by nam31** [comment]
@jgossvmware We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
