### ISSUE TITLE
Related Link - Intune Infrastructure - 404

### ISSUE THREAD

**Issue by Crimsonfox89** [MicrosoftDocs/windows-itpro-docs#8729]
The link to "Network infrastructure requirements for Microsoft Intune" is outdated and returns a 404 error.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84727d31-ea2d-7437-68cc-2d0b7d5a4ff9
* Version Independent ID: 502dcdcd-87a6-c050-c957-a476cb22afc7
* Content: [Connection endpoints for Windows 10, version 1809 - Windows Privacy](https://docs.microsoft.com/en-gb/windows/privacy/manage-windows-1809-endpoints)
* Content Source: [windows/privacy/manage-windows-1809-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/manage-windows-1809-endpoints.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Thank you for the report. That is yet another link in need of correcting, a remnant from before Intune was moved to the /mem/ subdirectory.

Going to check if I can dig up the new location and write a PR to have it resolved.

**Comment by illfated** [comment]
First of all, there is the overarching page(s):
- https://docs.microsoft.com/en-us/mem/intune/
- https://docs.microsoft.com/en-us/mem/intune/fundamentals/
- https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new

Then, there are some pages that sort of get close to the topic, but not 100% exactly what the descriptive link text says:
- https://docs.microsoft.com/en-us/mem/intune/fundamentals/network-bandwidth-use
- https://docs.microsoft.com/en-us/mem/intune/fundamentals/supported-devices-browsers
- https://docs.microsoft.com/en-us/mem/intune/fundamentals/deployment-guide-intune-setup
- https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-planning-guide
- https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints

I am not familiar enough with this topic to know exactly which page or linkable section to look for here, so any help with locating a suitable page link would be very useful for resolving this issue.

**Comment by illfated** [comment]
Maybe the solution will be to find the closest matching page while also rephrasing the URL link text description.

**Comment by Crimsonfox89** [comment]
> Maybe the solution will be to find the closest matching page while also rephrasing the URL link text description.

I think the closest is 

[https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints](https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints) so it could be changed to 

[Network endpoints for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints)

based on the fact that the linking article is regarding endpoints.

**Comment by illfated** [comment]
Thank you very much for the feedback. I will go ahead and make a PR to suggest the changes for the referenced page.

**Comment by illfated** [comment]
There you go. PR #8745 is ready for browsing, review, comments, and suggestions.
