### ISSUE TITLE
Support for policy merging is not documented

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/windows-itpro-docs#8735]
Is it possible to document which CSP settings support policy merging (https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-antivirus-policy#policy-merge-for-settings - implies that not all Defender CSP support policy merge )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f65802b-f3e2-1c15-d972-b23e53ed7e72
* Version Independent ID: cc29ae16-e01e-aad1-3768-d6b8a0b60b1a
* Content: [Defender CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/defender-csp)
* Content Source: [windows/client-management/mdm/defender-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/defender-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @vboyev-MSFT - Thank you for your feedback on this. I have checked to get information that can be added to see what policies are supported merging. But looks like it's very difficult to go through all of the policies and that can create many complications. 
While going through https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-antivirus-policy#policy-merge-for-settings I found that this is something automated **Intune evaluates the settings that policy merge supports, for each user or device as taken from all applicable policies. Those settings are then merged into a single superset of policy.**

This means that there is no input required from the user, Whenever a user will try to merge the policy, Intune will automatically take care of the things and will check if the policy is mergeable or not. 

Hope this answers your question.

Thanks
Imran.
