### ISSUE TITLE
Need to document WHFB provisioning and Authentication on WPJ state with Intune. how they manage WHFB PIN on WPJ

### ISSUE THREAD

**Issue by NagaCSC** [MicrosoftDocs/windows-itpro-docs#8739]
we have come across WHFB PIN provisioned on WPJ state (AAD Registered) and we do not have the document about it.
Also how you identify the WHFB and deprovision if no longer need to have WHFB. [Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 789566d4-463a-4c64-bf89-fb963ac29f80
* Version Independent ID: 02946732-bb29-d8e6-cedd-7f5e508f8798
* Content: [Manage Windows Hello in your organization (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-manage-in-organization)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-manage-in-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-manage-in-organization.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by joinimran** [comment]
Hello @NagaCSC - You can deprovision WHFB using the following document https://support.microsoft.com/en-us/topic/using-whfbtools-powershell-module-for-cleaning-up-orphaned-windows-hello-for-business-keys-779d1f3f-bb2d-c495-0f6b-9aeb940eeafb - Did you get a chance to try this?

Thanks
Imran.
