### ISSUE TITLE
Please define the difference between first an third party browsers

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/windows-itpro-docs#8747]
Please define the difference between first an third party browsers. For example, the section that says URL paths are supported by first party browsers, is that IE and Edge or does that include Chrome an Safari too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8f1e347-cbff-c68e-1ac1-7b18417ad792
* Version Independent ID: 385679a4-1bde-c920-5c8c-76cb4d76fd30
* Content: [Create indicators for IPs and URLs/domains - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/indicator-ip-domain)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/indicator-ip-domain.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/indicator-ip-domain.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
According to a simple web search, the term "first party browser" includes Apple Safari and Google Chrome:
- https://www.bing.com/search?q=%22first+party+browser%22&filters=ex1%3a%22ez5_18234_18599%22&sp=-1&pq=%22first+party+browser&sc=0-19

**Comment by itguysocal** [comment]
That is the problem, its ambiguous because in most all other scenarios "first party" refers to the main vendor (Microsoft) so that would mean Edge and IE are "first party." And 3rd party would be Safari, Chrome and Firefox. However, the O365 Service Description refers to modern browsers within 2 releases, etc. So we need clarification on what is meant by first party (MSFT vs Non-MSFT)

**Comment by RAJU2529** [comment]
@itguysocal . First party means, Browser comes with windows OS . say example
Internet Explorer or Microsoft edge legacy browser.
Moreover  chorme or firefox  are third party browsers on windows 10.
On MAC OS,  Safari browser is first patty browser.

**Comment by illfated** [comment]
@denisebmsft : Could we ask if any of the tech writers or the tech department could cite some form of reference where this is clarified?

**Comment by MaratMussabekov** [comment]
Hello, in terms of Microsoft, first-party browsers are only those which were developed by Microsoft (IE, Edge)
Thank you

**Comment by illfated** [comment]
PR #8889 is now ready for review, comments, and suggestions. @MaratMussabekov : Thank you for creating the PR and adding the requested changes.
