### ISSUE TITLE
Please indicate whether wildcards are supported

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/windows-itpro-docs#8748]
Please indicate whether "Encrypted URLs (full path)" means that a wildcard can be supported like http://site.com/folder/*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8f1e347-cbff-c68e-1ac1-7b18417ad792
* Version Independent ID: 385679a4-1bde-c920-5c8c-76cb4d76fd30
* Content: [Create indicators for IPs and URLs/domains - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/indicator-ip-domain)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/indicator-ip-domain.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/indicator-ip-domain.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@itguysocal .
for example  only
  *. microsoft.com is supported.
  *.intel.com is supported

**Comment by itguysocal** [comment]
can the documentation be more clear about wildcard support for "full path"  otherwise its not clear whether something like this is expected to work: http://site.com/folder/* or whether

**Comment by MaratMussabekov** [comment]
Hello @itguysocal ,
As I checked, it will not return any error if you try to create indicator for `http://site.com/folder/*`, however, it will not work as expected.
So I believe wildcards are not supported. It supports only FQDN or URL, and if you need to block http://site.com/folder/*, I would recommend to use FQDN **site.com**.

Thank you
