### ISSUE TITLE
Update Windows Business support please!

### ISSUE THREAD

**Issue by domcote** [MicrosoftDocs/windows-itpro-docs#875]
Windows Business support is currently often "blank". Example: Windows Business does NOT support ApplicationManagement/RequirePrivateStoreOnly, but is DOES support ApplicationManagement/AllowStore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64ac43f2-2742-087b-1512-1dd0f4e469e4
* Version Independent ID: f52b9d2b-c877-c18a-fd45-3a47e4c39e29
* Content: [Policy CSP - ApplicationManagement](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-applicationmanagement#applicationmanagement-allowstore)
* Content Source: [windows/client-management/mdm/policy-csp-applicationmanagement.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-applicationmanagement.md)
* Service: **w10**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by nam31** [comment]
@domcote the article has been updated. Please let us know if you still have any question regarding the issue you have raised initially.
