### ISSUE TITLE
COPYPE.CMD not found

### ISSUE THREAD

**Issue by Sorbe** [MicrosoftDocs/windows-itpro-docs#8752]
Following direction as shown, results in 

C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools>copype.cmd amd c:\winpe_amd64
'copype.cmd' is not recognized as an internal or external command,
operable program or batch file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6a95648-e93d-fdd5-b52f-afca6e49a139
* Version Independent ID: 607d9bc8-de81-eb28-5326-434e1cf6a696
* Content: [Configure a PXE server to load Windows PE (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/configure-a-pxe-server-to-load-windows-pe)
* Content Source: [windows/deployment/configure-a-pxe-server-to-load-windows-pe.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/configure-a-pxe-server-to-load-windows-pe.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@Sorbe . I think you have entered wrong command. 
show the screenshot of entered comnand..
eventhough I installed same adk on windows I modified .wim files

**Comment by Sorbe** [comment]
I’m pretty sure the documentation is now incorrect.   The MS deployment docs say to use “COPYPE.CMD” which fails because the command appears to have been renamed to “CopyDandI.cmd”.

**Comment by RAJU2529** [comment]
@Sorbe . which version ADK did you installed in your windows os 
i have attached .cmd files   , download and extarct the file and  copy to  this location 
**C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\** 

[Desktop.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/5642232/Desktop.zip)

**Comment by illfated** [comment]
Maybe it is not clear enough in the article, but it mentions the Windows PE tools in the first sentence:

> This walkthrough describes how to configure a PXE server to load Windows PE by booting a client computer from the network. Using the Windows PE tools and a Windows 10 image file, you can install Windows 10 from the network.

Maybe the download link for WinPEsetup.exe needs to be added to the **Prerequisites** section?

**Comment by RAJU2529** [comment]
@illfated , you  misunderstood the line, @Sorbe   said **copyPE.cmd** is missing, i  have many times installed windows 10 ADK and windows 10 PEaddson seperately ,  i never missed out this file copyPE.cmd ,  
Also this file **copyPE.cmd** contains scripts  to copy the required files from windows 10  ADK sub folders.

**Comment by illfated** [comment]
OK, fair enough. I will leave the discussion to you who know what to troubleshoot in this situation.

**Comment by nam31** [comment]
Closing via #8857 
Thank you
