### ISSUE TITLE
Explain better the ASR pre-req

### ISSUE THREAD

**Issue by darioongit** [MicrosoftDocs/windows-itpro-docs#8753]
I think this sentence should be re-written to make clearer what are the pre-requisites

Attack surface reduction features across Windows versions
You can set attack surface reduction rules for devices running any of the following editions and versions of Windows:

Windows 10 Pro, version 1709 or later
Windows 10 Enterprise, version 1709 or later
Windows Server, version 1803 (Semi-Annual Channel) or later
Windows Server 2019
To use the entire feature-set of attack surface reduction rules, you need a Windows 10 Enterprise license. With a Windows E5 license, you get advanced management capabilities including monitoring, analytics, and workflows available in Defender for Endpoint, as well as reporting and configuration capabilities in the Microsoft 365 security center. These advanced capabilities aren't available with an E3 license, but you can still use Event Viewer to review attack surface reduction rule events.

something like:

Attack surface reduction features across Windows versions
You can set attack surface reduction rules for devices running any of the following editions and versions of Windows:

- Windows 10 Pro, version 1709 or later
- Windows 10 Enterprise, version 1709 or later
- Windows Server, version 1803 (Semi-Annual Channel) or later
- Windows Server 2019

To use the entire feature-set of attack surface reduction rules, you need:

- Windows Defender Antivirus as primary AV (real-time protection on)
- [Cloud-Delivery Protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/enable-cloud-protection-microsoft-defender-antivirus) on (some rules require that)
- Windows 10 Enterprise E5 or E3 License or Microsoft 365 Business License

With a Windows E5 license, you get advanced management capabilities including monitoring, analytics, and workflows available in Defender for Endpoint, as well as reporting and configuration capabilities in the Microsoft 365 security center. These advanced capabilities aren't available with an E3 license, but you can still use Event Viewer to review attack surface reduction rule events.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d747289-63b2-f71a-b40c-31b52982215c
* Version Independent ID: b52f6593-03f2-aa57-ec0e-eaef560dcaf0
* Content: [Use attack surface reduction rules to prevent malware infection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction?source=docs)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by VLG17** [comment]
@darioongit According to the [FAQ for ASR](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction-faq), the scenario with Microsoft 365 Business license + Microsoft Defender AV enabled in **not supported**, so i don't think that should be added to the article. The information that's already present in the article describes the supported scenario, which is an enterprise Windows 10 license.

> Do I need to have an enterprise license to run ASR rules?

> The full set of ASR rules and features **is only supported if you have an enterprise license for Windows 10**. A limited number of rules may work without an enterprise license. If you have Microsoft 365 Business, set Microsoft Defender Antivirus as your primary security solution, and enable the rules through PowerShell. However, **ASR usage without an enterprise license is not officially supported and the full capabilities of ASR will not be available.**
> 
>

**Comment by darioongit** [comment]
the information are not aligned, but I think the license is required only for the reporting things

https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/demystifying-attack-surface-reduction-rules-part-1/ba-p/1306420

#5 What are the specific requirements for enabling ASR rules?

Yes, the requirements are the following:

Computers running Windows 10, versions 1709 and later,  Windows Server version 1803 (Semi-Annual Channel or later) and Windows Server 2019
Windows 10 Pro/Enterprise/Education
Microsoft Defender antivirus must be active (cannot be in passive mode!)
Some rules require cloud-delivered protection to be enabled
**Although ASR rules do not require an E5 license, with E5 you’ll gain enhanced optics and data insights, thanks to the power of the Microsoft Cloud.**

For more information on the differences between E3 and E5 for ASR rules, please refer to Attack surface reduction features across Windows versions

In future parts of this blog, we will cover the different reporting mechanisms and you’ll be able to see the exact benefits of E5 for ASR rules.

btw, the Microsoft 365 Business license isn't the main change here

**Comment by nam31** [comment]
@denisebmsft, can you please give your inputs here?

**Comment by denisebmsft** [comment]
Thank you @nam31 and everyone for your help. And thank you @darioongit for the feedback. We have someone updating the content. I'll keep this issue open for now and will post an update once the content has been updated. Thanks again!

**Comment by denisebmsft** [comment]
Asset moved to /microsoft-365/security/defender-endpoint/attack-surface-reduction

**Comment by Kateyanne** [comment]
@denisebmsft is this Issue ready to be closed now?

**Comment by denisebmsft** [comment]
The assigned writer is still working on this. I will update this work item as soon as the content fixes are in. @Kateyanne thank you for your help managing these!

**Comment by denisebmsft** [comment]
My colleague has updated this article and it looks like this issue has been addressed. Thank you @darioongit for raising this and everyone for your help!

**Comment by darioongit** [comment]
Thank you so much for your support!!!
________________________________
