### ISSUE TITLE
Deployment for Linux Windows defender is too complicated

### ISSUE THREAD

**Issue by eturnersumi** [MicrosoftDocs/windows-itpro-docs#8757]
Customers struggle with following along this documentation to deploy Windows Defender for Linux. Are there plans to simplify the deployment steps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2197cba-30ac-1749-e25a-6f39c9ee9d20
* Version Independent ID: bcd14f13-ab59-8e69-5c83-42fee6e51f87
* Content: [Deploy Microsoft Defender ATP for Linux manually - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jesspent** [comment]
This issue i am having is when running     
sudo apt-get install mdatp i get this error "Unable to correct problems, you have help broken packages"

But yes there are too many steps to install Microsoft Defender ATP on Ubuntu - I'm not a Linux admin and its just seems way too complicated - However i managed to install and setup docker with running applications on Ubuntu

**Comment by nam31** [comment]
@eturnersumi Thank you for providing feedback.
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
Thank you for your contribution to make the docs better! Much appreciated!

**Comment by jesspent** [comment]
@nam31  this is for linux not windows. can you please reopen

**Comment by illfated** [comment]
@jesspent / @eturnersumi : May I ask one of you to open a new ticket for this issue? 
You can do so by using the following link:
- https://github.com/MicrosoftDocs/windows-itpro-docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%20e2197cba-30ac-1749-e25a-6f39c9ee9d20%0A*%20Version%20Independent%20ID%3A%20bcd14f13-ab59-8e69-5c83-42fee6e51f87%0A*%20Content%3A%20%5BDeploy%20Microsoft%20Defender%20ATP%20for%20Linux%20manually%20-%20Windows%20security%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows%2Fsecurity%2Fthreat-protection%2Fmicrosoft-defender-atp%2Flinux-install-manually)%0A*%20Content%20Source%3A%20%5Bwindows%2Fsecurity%2Fthreat-protection%2Fmicrosoft-defender-atp%2Flinux-install-manually.md%5D(https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindows-itpro-docs%2Fblob%2Fpublic%2Fwindows%2Fsecurity%2Fthreat-protection%2Fmicrosoft-defender-atp%2Flinux-install-manually.md)%0A*%20Product%3A%20**w10**%0A*%20GitHub%20Login%3A%20%40Dansimp%0A*%20Microsoft%20Alias%3A%20**dansimp**

You may also want to enlist the help of some of the Linux users frequenting these page, particularly when it comes to phrasing what you would like to see improved.
