### ISSUE TITLE
Microsoft Endpoint Configuration Manager wrong title

### ISSUE THREAD

**Issue by ariendg** [MicrosoftDocs/windows-itpro-docs#8758]
Microsoft Endpoint Configuration Manager is the wrong product name in the steps with:
Go to the Microsoft Endpoint Manager admin center (https://endpoint.microsoft.com) and log in.
so it should be "Microsoft Endpoint Manager".

Microsoft Endpoint Manager Configuration Manager (MEMCM) is another product and console and this product as a specific is not (yet) part of the https://endpoint.microsoft.com.
So someone mixed up the names? Please let me know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f8ccc01-1b04-e443-ef75-6ffe6c866dd5
* Version Independent ID: fa2eaa0f-db04-785a-3894-8244947b9cd5
* Content: [Turn on cloud-delivered protection in Microsoft Defender Antivirus - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/enable-cloud-protection-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/enable-cloud-protection-microsoft-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@ariendg  . thanks for pointing out .

**Comment by illfated** [comment]
Fair point. Microsoft Endpoint Manager (MEM) and Microsoft Endpoint Manager Configuration Manager (MEMCM) are the correct names.
Have you found more than one page pages containing incorrect names for the products?

**Comment by illfated** [comment]
(ref. PR #8808 )

**Comment by nam31** [comment]
Closing via #8808 
Thank you

**Comment by ariendg** [comment]
> 
> 
> Fair point. Microsoft Endpoint Manager (MEM) and Microsoft Endpoint Manager Configuration Manager (MEMCM) are the correct names.
> Have you found more than one page pages containing incorrect names for the products?

I this think the full name on https://docs.microsoft.com/en-us/mem/configmgr/core/understand/microsoft-endpoint-manager-faq
Should be Microsoft Endpoint Manager Configuration Manager
And not Microsoft Endpoint Configuration Manager
But this is another topic, has nothing to do with the mixup in this issie. Microsoft has clearly chosen to do the branding this way..

**Comment by illfated** [comment]
Issue solved. Please open a new ticket if you find any new issues.

The name is now spelled correctly: **Microsoft Endpoint Manager Configuration Manager**
