### ISSUE TITLE
Microsoft Defender Antivirus - how to install?

### ISSUE THREAD

**Issue by rccnw** [MicrosoftDocs/windows-itpro-docs#8762]
[Enter feedback here]
I arrived at this page looking for installation info for Microsoft Defender Antivirus.  
Didn't find a download link as expected.
After spending a few minutes and following the available links, I'm completely confused.  All I see is content talking about how great it is, no clue how to get it.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e97678b-eaff-f61c-68d7-8af45f2b2396
* Version Independent ID: 1eb2afc3-9522-0330-a67e-826d7381fb8a
* Content: [Next-generation protection in Windows 10, Windows Server 2016, and Windows Server 2019 - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-in-windows-10)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-in-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-in-windows-10.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @rccnw and thank you for the feedback! My apologies for the confusion. I have updated the article to include information such that Microsoft Defender Antivirus is built into Windows 10, Windows Server 2019, and Windows Server 2016. I have also added a link to this article near the end: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-on-windows-server-2016#install-microsoft-defender-antivirus-on-windows-server-2016-or-2019

My changes will be live later today. Thank you again for your feedback!
