### ISSUE TITLE
Is it required to setup cron task for mdatp definitions update?

### ISSUE THREAD

**Issue by igor-safonov** [MicrosoftDocs/windows-itpro-docs#8769]
This article has instructions to setup cron task to update mdatp package.
Is it required to have another task to run `mdatp --definition-update` or does it happen out of the box?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5471d691-d943-ceb7-7388-de5c06d1c48f
* Version Independent ID: 0f1c11c6-fa8e-9383-ea34-b262b03e15bf
* Content: [How to schedule an update of the Microsoft Defender for Endpoint (Linux) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-update-mde-linux)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-update-MDE-Linux.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-update-MDE-Linux.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Good question. Wish I knew. Looking forward to the answer, which I hope will be that the existing package solution uses some kind of regular or trigger update check somehow.

**Comment by MaratMussabekov** [comment]
Hello @igor-safonov ,
no, there is no need for additional cron task, definition updates are installed automatically by default. 
You may disable auto updates by configuring mdatp_managed.json file, as it is described [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-preferences).

Thank you

**Comment by illfated** [comment]
Thanks for the explanation. I was sort of thinking about JSON and internal update functionality, but have not been digging deep enough into this topic.

**Comment by konstruktoid** [comment]
That document is kind of messy, and since everything else regarding `mdatp` is systemd perhaps timers should be recommended instead.

Another option is using `sudo mdatp config automatic-definitions-update --value enable` and verify with `mdatp health`.

```sh
$ sudo mdatp health | grep 'definition'
automatic_definition_update_enabled         : true
definitions_updated                         : Jan 05, 2021 at 05:51:13 PM
definitions_updated_minutes_ago             : 193
definitions_version                         : "83130"
definitions_status                          : "up_to_date"
```

**Comment by illfated** [comment]
I wonder how long it will take before it becomes an issue that MDATP has changed its name to Microsoft Defender for Endpoint.

**Comment by konstruktoid** [comment]
@illfated, oh... I didn't even realized it had changed... When did that happen?

**Comment by illfated** [comment]
Q4 of 2020, I presume. I don't remember the exact details, but it should be available from some of the MS pages. Let me check it and get back to you.

**Comment by illfated** [comment]
https://www.zdnet.com/article/microsoft-renames-and-unifies-more-products-under-microsoft-defender-brand/

> ## Microsoft renames and unifies more products under Microsoft Defender brand
>
> #### Microsoft Threat Protection, Defender ATP, Azure Security Center, and others brought under the Microsoft Defender umbrella brand.
>
> After rebranding Windows Defender as Microsoft Defender in early 2019, Microsoft is renaming and bringing more products under the Defender brand, the company announced today at its yearly Ignite developer conference.
>
> Starting Sept. 22, the Microsoft Defender product line will be expanded and split across two branches as Microsoft 365 Defender for end-user environments and Azure Defender for cloud and hybrid infrastructure, respectively.
>
> The Microsoft 365 Defender line will include:
> 
> - **Microsoft 365 Defender** (previously Microsoft Threat Protection)
> - **Microsoft Defender for Endpoint** (previously Microsoft Defender Advanced Threat Protection)
> - **Microsoft Defender for Office 365** (previously Office 365 Advanced Threat Protection)
> - **Microsoft Defender for Identity** (previously Azure Advanced Threat Protection)

**Comment by illfated** [comment]
Even though the name change to "Microsoft Defender for Endpoint" started as early as September 2020, there are still a bunch of pages in need of updating. Just to add a little bit more information, in case it can be useful later:
- https://docs.microsoft.com/mem/
- https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/manage-atp-post-migration-configuration-manager
- https://www.microsoft.com/microsoft-365/microsoft-endpoint-manager?rtc=1
- https://docs.microsoft.com/mem/endpoint-manager-overview

Useful to remember when checking URL addresses: /mem/ = MEM = Microsoft Endpoint Manager

**Comment by konstruktoid** [comment]
Thanks @illfated! I was stuck looking at the `mdatp` name and hadn't realized this was a thing coming.

**Comment by nam31** [comment]
@igor-safonov, Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
