### ISSUE TITLE
Powershell Module

### ISSUE THREAD

**Issue by Ayanmullick** [MicrosoftDocs/windows-itpro-docs#877]
There should be a Powershell module for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bffe4a4-5840-c6dc-7e5d-850850478f8e
* Version Independent ID: 522eb808-1848-84de-79a8-51a54bddb8ee
* Content: [Windows Security Baselines](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-security-baselines)
* Content Source: [windows/security/threat-protection/windows-security-baselines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-security-baselines.md)
* Service: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **sagaudre**

**Comment by shortpatti** [comment]
@Justinha, can you take a look at this one?

**Comment by Justinha** [comment]
@Ayanmullick Thanks for the suggestion and sorry for late reply. This has been shared with the engineering team.
