### ISSUE TITLE
Weird Prerequisites

### ISSUE THREAD

**Issue by erottier** [MicrosoftDocs/windows-itpro-docs#8776]
The Prerequisites states:
"Network infrastructure in place to reach your on-premises domain controller. If the machines are external, this can be achieved using any VPN solution."

But I cannot find any need for reaching the on-prem DCs from external devices.

Is this requirement strange, or am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c175ce-52a4-8b46-716f-106b4d55106c
* Version Independent ID: 374a7e9d-6e4f-f188-328b-4ca2651a9481
* Content: [Configure Azure AD joined devices for On-premises Single-Sign On using Windows Hello for Business - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mapalko** [comment]
The purpose of this guide is to enable SSO to on-premises resources, for example an on-prem network file share. In order to get a TGT to access on-prem resources, the device will need to have line of sight to the DC and to the on-prem resource.

**Comment by illfated** [comment]
@erottier : I notice that a lot of people overthink that statement and make it more complicated than it is. It is meant to be a simple preparation step, not any elaborate infrastructure change. After all, it is more or less about a transition from a normal existing local network, via a set of preparations, to become ready to join Azure Active Directory.

**Comment by erottier** [comment]
> The purpose of this guide is to enable SSO to on-premises resources, for example an on-prem network file share. In order to get a TGT to access on-prem resources, the device will need to have line of sight to the DC and to the on-prem resource.

Is it really true?

When I open Outlook I get WhfB instead of my on-prem authetication window. Understandable, but it's not a requirement that I need a VPN per sé.

Also, @illfated, as I understand this, you could use a AAD-joined laptop within the org building to access on-prem file servers, then also no VPN needed.

So my conclusion is, that VPN is simply NOT a prerequisite, but a _nice to have_ to access on-prem resources from outside of the company. But that was always the case anyway!

**Comment by illfated** [comment]
I am not an expert on this topic, so I don't know if I can answer your topical question correctly.

Please review the related discussion about this very same page in issue ticket #8172 to see if your question is better answered there.

**Comment by illfated** [comment]
Oh, and yes. That much is true. VPN is not a requirement per se, just a "nice to have" feature in relevant cases.

**Comment by nam31** [comment]
@erottier Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
