### ISSUE TITLE
Windows Server 2019 Defender-GUI

### ISSUE THREAD

**Issue by EdmondN1** [MicrosoftDocs/windows-itpro-docs#8778]
Dears,

While implementing the Defender AV on the Windows Server 2019 we have found that it is different than the Windows Server 2016, the Defender-GUI feature isn't part of server 2019 as the Defender AV is showing in the Windows Security Center.

Appreciate if you can advise and update accordingly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d1dee2b-d86a-0019-f689-81483fab31f5
* Version Independent ID: 02722ca2-1dde-aafb-22e3-67259c4ece37
* Content: [Microsoft Defender Antivirus on Windows Server 2016 and 2019 - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-on-windows-server-2016)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-on-windows-server-2016.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-on-windows-server-2016.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@EdmondN1 , You need to enable those features by using PowerShell command,

**Install-WindowsFeature -Name Windows-Defender**
or 
**Install-WindowsFeature -Name Windows-Defender-GUI**

verify whether service is  running and enabled 
**Get-Service -Name windefend**
**Get-Service -Name mpssvc**

**Comment by denisebmsft** [comment]
Thank you @EdmondN1 for posting your question, and thank you @RAJU2529 for your help. It looks like the article has the corret PowerShell cmdlets and information. I'm going to close this for now, but if you still have questions, please let us know.

**Comment by illfated** [comment]
(Just to reiterate the commands provided by @RAJU2529 , but in MarkDown code blocks with syntax highlighting.)

```PowerShell
# install the Windows Defender service (CLI)
Install-WindowsFeature -Name Windows-Defender
```

```PowerShell
# install the Windows Defender service with GUI
Install-WindowsFeature -Name Windows-Defender-GUI
```

```PowerShell
# Verify that the service is running and enabled:
Get-Service -Name windefend
Get-Service -Name mpssvc
```
