### ISSUE TITLE
How should we troubleshoot errors and issues with a tool that does not exists anymore?

### ISSUE THREAD

**Issue by ATR-Master** [MicrosoftDocs/windows-itpro-docs#8779]
In einem Problembehandlungsartikel vom 12.11.2020 beschreiben sie auf der Microsoft Docs Seite "Problembehandlung für drahtlose Netzwerkverbindungen" die Fehlersuche bzw. Protokollanalyse mit dem Netzwerk Monitor 3.4. Dieses Tool wurde vor mehr als 5 Jahren abgekündigt und kann seit diesem Zeitpunkt nicht mehr geladen werden. 
Es wurde zudem durch den Microsoft Message Analyzer ersetzt, der von Microsoft im Jahre des Herrn 2020 abgekündigt wurde und daher ebenfalls nicht mehr von der Microsoft Download-Seite geladen werden kann.
Preisfrage: Was soll so was?? Macht es Spaß, die Anwender / Nutzer für dumm zu verkaufen und ihnen Tools zu zeigen, die es schon lange nicht mehr gibt? Wäre der Artikel aus dem Jahre 2010 würde ich ja nichts sagen, aber 12. November 2020 und dann sowas - geht gar nicht!!
Also: Mit welchem Tool sollen wir jetzt diese Fehlersuche durchführen? (By the way: Windows 10 hat dafür nichts mehr an Board und eine Download-Option wurde bei der Abkündigung von Microsoft Message Analyzer auch nicht angegeben). 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 52fa26a8-efe0-9d8d-eef8-eb8fa7b2e640
* Version Independent ID: f217d015-3ccb-decd-ad07-29e07c4d2760
* Content: [Erweiterte Problembehandlung bei der 802.1 x-Authentifizierung - Windows Client Management](https://docs.microsoft.com/de-de/windows/client-management/advanced-troubleshooting-802-authentication)
* Content Source: [windows/client-management/advanced-troubleshooting-802-authentication.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/advanced-troubleshooting-802-authentication.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **tracyp**

**Comment by e0i** [comment]
@ATR-Master

The date of the article looks recent because of the minor revisions that have been introduced to the article recently, and the core of the article is probably already very old. 

_Das Datum des Artikels sieht aufgrund der geringfügigen Überarbeitungen, die kürzlich in den Artikel eingeführt wurden, neu aus, und der Kern des Artikels ist wahrscheinlich bereits sehr alt._

**Comment by ATR-Master** [comment]
Einen Artikel aktualisieren bedeutet, seinen Kern und seine Kernaussage sowie weitere Informationen auf den neuesten Stand zu bringen! Wenn es das Tool für Troubleshooting nicht mehr gibt, dann ist der Artikel entweder hinfällig oder muß komplett überarbeitet werden. Eine halbherzige Antwort, das der Kern des Textes wohl alt wäre, ist eher Ausdruck von Hilflosigkeit, denn Zeichen von sinnvoller Arbeitsauffassung! Das Teil gehört vollständig überarbeitet und nicht bloß um ein paar Sätze ergänzt, die sinnlos sind, weil das Troubleshooting-Tool nicht mehr verfügbar ist. Was ist daran so schwer???

 

Von: Onur [mailto:notifications@github.com] 
Gesendet: Sonntag, 27. Dezember 2020 13:48
An: MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>
Cc: ATR-Master <aterveen@t-online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [MicrosoftDocs/windows-itpro-docs] How should we troubleshoot errors and issues with a tool that does not exists anymore? (#8779)

 

@ATR-Master <https://github.com/ATR-Master> 

The date of the article looks recent because of the minor revisions that have been introduced to the article recently, and the core of the article is probably already very old.

Das Datum des Artikels sieht aufgrund der geringfügigen Überarbeitungen, die kürzlich in den Artikel eingeführt wurden, neu aus, und der Kern des Artikels ist wahrscheinlich bereits sehr alt.
