### ISSUE TITLE
MS Docs vs MS Support conflicting content

### ISSUE THREAD

**Issue by aydeisen** [MicrosoftDocs/windows-itpro-docs#8780]
There are some minor discrepancies between this document and the [Virus scanning recommendations for Enterprise Computers](https://support.microsoft.com/en-us/help/822158/virus-scanning-recommendations-for-enterprise-computers) support article.  Does one supersede the other and, if not, what's the difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9b6379-e575-9819-eca1-a0952f66b655
* Version Independent ID: 34d81602-ffa2-5be6-67ef-b42b3b6f17ee
* Content: [Configure Microsoft Defender Antivirus exclusions on Windows Server 2016 or 2019 - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-server-exclusions-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/configure-server-exclusions-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/configure-server-exclusions-microsoft-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
@aydeisen : I think it is important to keep in mind that the support.microsoft.com page contains general advice for virus scanning regardless of AV Software solution, whereas the MS Docs page deals with Microsoft Defender for Endpoint specifically. In this regard, neither page supersedes the other, you just need to use the one that matches your AV Software solution.

Please also note that the support.microsoft.com page links to the MS Docs page specifically for Microsoft Defender, for Microsoft Defender-specific advice.

My advice is to use the page that matches your scenario.

**Comment by denisebmsft** [comment]
Thank you @aydeisen for posting your feedback here. And thank you @illfated and @MaratMussabekov for your help. I am going to close this issue, but if you still have any questions, please let us know.

**Comment by aydeisen** [comment]
@denisebmsft @illfated @MaratMussabekov 

Thank you for your responses.  Just one follow-up:  While I respect the note in the support article, according to a note in `docs`, the automatic exclusion rules only apply during an RTP scan and not during a scheduled scan.  So, if a scheduled scan is implemented, which list would be used for the explicit exclusions that are needed?

![image](https://user-images.githubusercontent.com/14042645/102394982-88f8e280-3fa8-11eb-942b-385d7dbfe0c0.png)

**Comment by illfated** [comment]
To me, it appears somewhat obvious (after reading the full document page) that _any other exclusion lists_ are available to a scheduled scan. Only the Automatic exclusions are omitted during a Full/Quick or On-demand scan. See also the quoted paragraph below:

## A few points to keep in mind

- Custom exclusions take precedence over automatic exclusions.

- Automatic exclusions only apply to Real-time protection (RTP) scanning. Automatic exclusions are not honored during a Full/Quick or On-demand scan.

- Custom and duplicate exclusions do not conflict with automatic exclusions.

- Microsoft Defender Antivirus uses the Deployment Image Servicing and Management (DISM) tools to determine which roles are installed on your computer.
