### ISSUE TITLE
Configuration Profile Clarification needed for Catalina 10.15.4 and higher.

### ISSUE THREAD

**Issue by stelladew** [MicrosoftDocs/windows-itpro-docs#8783]
I was looking at this guide for deploying Defender via JAMF.  I see the link for the new configuration profiles for Catalina 10.15.4 and higher including Big Sur.  What the page does not clarify is:
1. What is you deployed the config files for 10.15.3 or lower, and then upgraded to 10.15.4 or higher.  Do you need to remove those previous deployed configuration profiles and then add the new ones for Catalina 10.15.4 and higher including Big Sur?
2. Can you just leave those configuration profiles on there an install the new ones for Catalina 10.15.4 and higher including Big Sur?   
There should be some clarification on what the exact scope is for which configuration profiles and more important, what you should do if you already deployed configuration profiles and the macOS was upgraded to 10.15.4 or higher.  

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f067243-d029-ec35-cb1d-cc271b00d0a1
* Version Independent ID: 121d2480-5bbc-9a8e-68a6-17f708dc21d4
* Content: [Deploying Microsoft Defender ATP for macOS with Jamf Pro - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-install-with-jamf)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-install-with-jamf.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-install-with-jamf.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
@stelladew Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following this guide at [Contact Microsoft Defender for Endpoint support](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/contact-support)
Thank you.
