### ISSUE TITLE
Version "101.12.99" was release since las week and the documentation has not been updated. 

### ISSUE THREAD

**Issue by deargued** [MicrosoftDocs/windows-itpro-docs#8784]
Please update the documentation with "101.12.99" and provide the details of it.
![MDE for Linux](https://user-images.githubusercontent.com/62759892/101697261-1da99080-3a3d-11eb-9bc9-ee6d5095fc31.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ca25ead-3b5d-4434-1865-0d4fef57ebdf
* Version Independent ID: 8d146609-15b5-b8a0-62bf-108f29248991
* Content: [What's new in Microsoft Defender Advanced Threat Protection for Linux - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-whatsnew#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-whatsnew.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-whatsnew.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Resolved in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/41aa1b595f3897f3695d45f1ad0572b1fa3f022e

#please-close
