### ISSUE TITLE
Image are not readable in dark theme

### ISSUE THREAD

**Issue by meziantou** [MicrosoftDocs/windows-itpro-docs#8788]
Most images on this page have a transparent background. When using the dark theme, the black text is not readable.

Images should have a white background as the first image.

![image](https://user-images.githubusercontent.com/509220/101706827-f2806a80-3a57-11eb-80eb-89f87ba1a5fc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f23363fd-0777-63f3-3a2f-0e5062968a39
* Version Independent ID: 9abd2dc6-d872-4369-5fa4-fab497b53357
* Content: [Windows Sandbox architecture - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-architecture#feedback)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-architecture.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-architecture.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Fair point. The dark text needs a white background, at least as a background for the text, to keep it readable.

I assume this needs some layer editing, so my skills are not sufficient yet to provide a working sample.

I hope someone else in this project have got those skills already, otherwise this may take some time to solve.

**Comment by meziantou** [comment]
I've created a PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8789 that changes the background of these images to white.

**Comment by illfated** [comment]
Thanks. That solves my immediate worry about how this ticket should be solved. I admit that I have acquired some ambition toward discrete editing of transparent images, so only the text is contrasted on opaque background, while the rest of the image not covered by figures or text could be transparent. But that is in my future, not the present.

Glad to see that you have acquired the knowledge to create a PR and how to make it reference & close a ticket resolved by the PR.
