### ISSUE TITLE
Windows Pro Support?

### ISSUE THREAD

**Issue by MarcoJanse** [MicrosoftDocs/windows-itpro-docs#879]
This CSP is also used by Intune as a device configuration profile, right? Will Windows 10 Pro be supported in the near future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a05802f-9d0f-9aeb-3c8e-8b92f1284202
* Version Independent ID: 1fd9efc2-8946-75e4-27f3-95ac43a9d987
* Content: [BitLocker CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp)
* Content Source: [windows/client-management/mdm/bitlocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/bitlocker-csp.md)
* Service: **w10**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by janwerner** [comment]
Would like to hear about this too. Why is Windows 10 Pro not supported?

**Comment by gutjahr** [comment]
+1. 
Devices shipping from the vendor are often Pro. On InstantGo capable devices we need AutoPilot to apply these CSP settings before the encryption automatically kicks off, at which point the device is Pro. The uplift to Enterprise happens a bit later in the initial setup process.

**Comment by MariciaAlforque** [comment]
BitLocker CSP will be supported in Pro in the upcoming Windows 10 release.

**Comment by SoccerCore11** [comment]
@MariciaAlforque can you please be more specific? Are you talking about the 1809 release? Are ALL settings in the BitLocker CSP supported with Win 10 Pro?
