### ISSUE TITLE
Why not provide or not have support for the OSEnablePrebootInputProtectorsOnSlates

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/windows-itpro-docs#8792]
Does the OSEnablePrebootInputProtectorsOnSlates description not included in this document for unsupported or other reasons?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a05802f-9d0f-9aeb-3c8e-8b92f1284202
* Version Independent ID: 1fd9efc2-8946-75e4-27f3-95ac43a9d987
* Content: [BitLocker CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp?source=docs)
* Content Source: [windows/client-management/mdm/bitlocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/bitlocker-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello, it is currently not supported.
The only option I would recommend is to set it using PowerShell.
Thank you

**Comment by goxia** [comment]
> Hello, it is currently not supported.
> The only option I would recommend is to set it using PowerShell.
> Thank you

Well, it seems that this method can only be used at present.
Thank you.
