### ISSUE TITLE
EDR in Block Mode only if primary AV is not Defender

### ISSUE THREAD

**Issue by SteBeSec** [MicrosoftDocs/windows-itpro-docs#8794]
Hello everybody,

I think the documentation of the "EDR in Block Mode" feature is missing one key point: This feature is only recommended if a company is not using MDAV or MDFE as their primary AV solution.
Proof: Matt Soseman (Microsoft Security Architect) stated this in the comments of this YouTube Video introducing the "EDR in Block Mode" feature: https://www.youtube.com/watch?v=0d5PcgHN8mw&lc=UgxE9aVNzj_X0Lq51194AaABAg.9G7dMpnjdW_9H5T1sxaPaF

I think this is a verry important information and therefore should be part of the Microsoft Docs Page of "EDR in Block Mode"

Best regards
Stefan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8da58e5-9cd8-8ccf-75a9-327c14ebaa76
* Version Independent ID: 24a29218-59e1-7a1d-c8c7-e61424b5f9ee
* Content: [Endpoint detection and response in block mode - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/edr-in-block-mode)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/edr-in-block-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/edr-in-block-mode.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by MaratMussabekov** [comment]
Hello @SteBeSec ,
**This feature is only recommended if a company is not using MDAV or MDFE as their primary AV solution.** - I am not sure this statement is correct.

**Proof: Matt Soseman (Microsoft Security Architect) stated this in the comments**  -  he said: "That is correct, it's really meant for cases where MDAV and MDFE is not the primary - EDR in block mode acts as a second layer of defense should the primary not see the threat." -  He never stated that it is the **ONLY** scenario when it is need to be enabled.

On the **Frequently asked questions** section of this article:
**Do I need to turn EDR in block mode on even when I have Microsoft Defender Antivirus running on devices?**

**We recommend keeping EDR in block mode on, whether Microsoft Defender Antivirus is running in passive mode or in active mode. EDR in block mode gives you an added layer of defense with Microsoft Defender for Endpoint. It allows Defender for Endpoint to take actions based on post-breach behavioral EDR detections.**

I would recommend not to add the statement that it should be enabled only if MDAV is not the primary antivirus.

Thank you.
