### ISSUE TITLE
This page updates to reflect RTP available in passive mode, what's the reason for this change? RTP should not be available in passive mode!

### ISSUE THREAD

**Issue by MS-binche** [MicrosoftDocs/windows-itpro-docs#8795]
This page updates to reflect RTP available in passive mode, what's the reason for this change? RTP should not be available in passive mode!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b88aee4-6727-fa98-1180-29708eea027e
* Version Independent ID: 374c671b-b21c-6eac-d887-892491357eb2
* Content: [Microsoft Defender Antivirus compatibility with other security products - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @MS-binche and thank you for posting your question. This article was updated per program manager request. It is correct that real-time protection is still active, even if Microsoft Defender Antivirus is in passive mode.
