### ISSUE TITLE
iOS/Android Support

### ISSUE THREAD

**Issue by ThijsLecomte** [MicrosoftDocs/windows-itpro-docs#8796]
[Enter feedback here]

Can the docs be updated in order to distinguish if Android/iOS support offboarding?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c6849fb-03d4-2fa8-c442-97dcb2bd21ee
* Version Independent ID: 43da3d0e-5626-57f7-80a0-6c44b4f96ffc
* Content: [Offboard machine API - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/offboard-machine-api)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/offboard-machine-api.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/offboard-machine-api.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by nam31** [comment]
Thank you for providing feedback.	
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.	
Thank you for your contribution to make the docs better! Much appreciated!
