### ISSUE TITLE
Azure AD Connect

### ISSUE THREAD

**Issue by larsjuhlandersen** [MicrosoftDocs/windows-itpro-docs#880]
I´am still puzzled how it works in the Azure AD Connected scenario?  you mentioned having a local AD with Azure AD connect the Activation of the Windows E3 subscription is durable, however your only describe the Join Azure AD part ?
I have on prem AD Windows Server 2016, I have latest Azure AD Connect, im syncing all directory including the computer accounts, and E3 assigned to a user.
Do I still have to join the computer to Azure AD ? I would think I need the computer On Prem to handle all the group policies, scripts an so fort I have running ?
So how would the Activation work for me?
thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ecbc1-9c02-5681-7214-356be22ac7e8
* Version Independent ID: 73af82f6-079b-6c37-55c4-cb59e921457a
* Content: [Deploy Windows 10 Enterprise licenses](https://docs.microsoft.com/en-us/windows/deployment/deploy-enterprise-licenses)
* Content Source: [windows/deployment/deploy-enterprise-licenses.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-enterprise-licenses.md)
* Service: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Activation to Enterprise works by recognizing the user that signs in and stepping the OS up from Pro to Enterprise when that user signs in. The user is signed up for Subscription Activation in Azure, so the device needs to be connected to Azure in order to recognize that user. It sounds like you've done that. Is it not working for you?

**Comment by bmomartins** [comment]
Hello guys,

What if OS registers in Azure AD (using AD Connect, hybrid joined mode) and Windows 10 does not activate? A bunch of "0x8018002B" errors in EnterpriseMgmt Event Viewer log.

Missing tools to troubleshoot delays adoption. Opening a support case is the only option left?

Kind regards,

**Comment by BigDaddy2012** [comment]
https://tech.xenit.se/windows-10-subscription-activation-hybrid-azure-ad-joined-devices/

Have a look at this guys..

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by j0rt3g4** [comment]
#Solving issue on PR #3628

**Comment by mypil** [comment]
@larsjuhlandersen - Thank you for submitting feedback. 

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
