### ISSUE TITLE
Wscore_MicrosoftWindowsWinsockAFD does not contain element AFD_EVENT_BIND error

### ISSUE THREAD

**Issue by rohitsawai** [MicrosoftDocs/windows-itpro-docs#8801]
When I tried to apply filter - **Wscore_MicrosoftWindowsWinsockAFD.AFD_EVENT_BIND.Status.LENTStatus.Code == 0x209** for finding entries containing - **STATUS_TOO_MANY_ADDRESSES** . I'm getting an error that is saying _Wscore_MicrosoftWindowsWinsockAFD does not contain element AFD_EVENT_BIND_ .  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c2ae54-4348-565f-ffbc-e9d95436ac8e
* Version Independent ID: f3c8b6f8-ed47-3628-f064-8773b91cd921
* Content: [Troubleshoot port exhaustion issues - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-tcpip-port-exhaust)
* Content Source: [windows/client-management/troubleshoot-tcpip-port-exhaust.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/troubleshoot-tcpip-port-exhaust.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by STO123456789** [comment]
So you know I archive this message and I have already started the case because there’s a group on get hub that has planted a python in my phone and I found it after seven years of having it there I’m glad you guys got your kicks out of my pictures and that shit but I am not putting that shit back in my fucking phone keep sending me that shit so I can show it to these people dumb ass

Ernesto

**Comment by STO123456789** [comment]
My attorney is ready to proceed we have I am going to press charges I promise on my kid’s souls I won’t stop till your all in jail and you will pay for this with your ass

**Comment by STO123456789** [comment]
My attorney is ready to proceed we have I am going to press charges I promise on my kid’s souls I won’t stop till your all in jail and you will pay for this with your ass

**Comment by STO123456789** [comment]
My attorney is ready to proceed we have I am going to press charges I promise on my kid’s souls I won’t stop till your all in jail and you will pay for this with your ass

**Comment by e0i** [comment]
Hello,

Looks like this question can best be answered via relevant [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channels. 

Please consider checking with [Microsoft Community](https://answers.microsoft.com/en-us/windows/forum/windows_10) or [contacting support](https://support.microsoft.com/contactus) for your problem; The issues section of this repository is for content fixes in documentation.

If you feel that the associated article also needs to be updated for any reason feel free to re-open this issue or [contribute with a pull request](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/CONTRIBUTING.md).

Thank you.
