### ISSUE TITLE
What to do when Diagnostic Data Viewer - no access

### ISSUE THREAD

**Issue by D-Jeffrey** [MicrosoftDocs/windows-itpro-docs#8802]
It worked before the last update/reboot and it had sample data, no I get the message
"The current user has no access to local diagnostic data'.  Not very useful when the diagnostic tool cannot diagnose errors or permissions issues.  
There should be a comment on what permission or services are required so we can check for that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54254070-539b-6cf2-f988-c80ad685c5fa
* Version Independent ID: 5bbe5140-eee5-abc3-1a26-1c0d13eab358
* Content: [Diagnostic Data Viewer Overview (Windows 10) - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/diagnostic-data-viewer-overview)
* Content Source: [windows/privacy/diagnostic-data-viewer-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/diagnostic-data-viewer-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Would you be able to provide which Windows 10 version and OS build you use now and what it was before you updated?

Could you post a screen shot or snippet of the affected setting?

**Comment by D-Jeffrey** [comment]
Windows Insider 20236.1  The problem when away, not sure if it was because I used powershell to  Enable-DiagnosticDataViewing

When I did that it mentioned the 'Connected User Experience and Telemetry service was not running.

I run troubleshooting wizard and it did not find the issue...
Diagnostics Troubleshooting Wizard

Description
Faulting Application Path:             C:\WINDOWS\system32\msdt.exe
Creation Time:                                   11/20/2020 4:33:04 PM
Problem:                                             Problem not fixed
Status:                                                  Report sent

Problem signature
Problem Event Name:           ScriptedDiagFailure
PackageId:                    Microsoft Corporation.NetworkDiagnosticsNetworkAdapter.4.0
RootCause:                    180194715
Version:                      1.0.0.0
DynamicParameter:             Default

Extra information about the problem
Bucket ID:                                            5123a215692c897e888ca25a1e6da774 (127856065272)


I tried by turning off using Disbale-DiagnosticDataViewing


[cid:image001.png@01D6D161.41D04750]

This is a different message is that there was no Sample Policies and no button to click on to enable telemetry
So if you stop the Connect User Experience and Telemetry service you will recreated the screen...  it looks like this...

[cid:image002.png@01D6D162.7A856110]

Therefor the repair instructions would be for the Troubleshooting Wizard to be check to see if it checks the run state of the service and the DOCS page to explain to check the service run state as well.

And now I broke the service again... so what does this error mean and how should it be fixed...
[cid:image003.png@01D6D162.D866BC20]

The service is still running...


*sign*

Maybe a reboot will fix that..

Restarting the service I get this message...
[cid:image004.png@01D6D163.1C06E630]

I'm thinking this service does not like to be restarted...

**Comment by illfated** [comment]
> Windows Insider 20236.1  The problem went away, not sure if it was because I used PowerShell to `Enable-DiagnosticDataViewing`
>

Well, hmm. Thank you for providing the details. I am somewhat skeptical to whether Insider builds can be trusted to deliver 100% expected results. You may want to report this to the Insider build team using the Windows Feedback feature to make them aware of any potential unresolved issues.

> When I did that it mentioned the 'Connected User Experience and Telemetry' service was not running.
>
> I ran troubleshooting wizard and it did not find the issue...
>
> ```
> Diagnostics Troubleshooting Wizard
>
> Description
> Faulting Application Path:    C:\WINDOWS\system32\msdt.exe
> Creation Time:                11/20/2020 4:33:04 PM
> Problem:                      Problem not fixed
> Status:                       Report sent
>
> Problem signature
> Problem Event Name:           ScriptedDiagFailure
> PackageId:                    Microsoft Corporation.NetworkDiagnosticsNetworkAdapter.4.0
> RootCause:                    180194715
> Version:                      1.0.0.0
> DynamicParameter:             Default
>
> Extra information about the problem
> Bucket ID:                    5123a215692c897e888ca25a1e6da774 (127856065272)
> ```
>

Fair enough, thanks for the details. I hope the tech writers may find this information useful.

> I tried turning off using Disbale-DiagnosticDataViewing
>
> [cid:image001.png@01D6D161.41D04750]
>
> This is a different message is that there was no Sample Policies and no button to click on to enable telemetry
> So if you stop the Connect User Experience and Telemetry service you will recreated the screen...  it looks like this...
>
> [cid:image002.png@01D6D162.7A856110]
>
> Therefore, the repair instructions would be for the Troubleshooting Wizard to be checked to see if it checks the running state of the service on the DOCS page to explain to check the service run state as well.
>

I still think that you would want to report this to the Insider build team using the Windows Feedback feature.

> And now I broke the service again... so what does this error mean and how should it be fixed...
>
> [cid:image003.png@01D6D162.D866BC20]
>
> The service is still running...
>
>
> `*sigh*`
>
> Maybe a reboot will fix that..
> Restarting the service I get this message...
>
> [cid:image004.png@01D6D163.1C06E630]
>
> I'm thinking this service does not like to be restarted...
>

Please note that your screenshot images seem to be blocked from this GitHub ticket by the email message filter.
You may want to upload the images directly via the web page if you believe they are essential to your message.

**Comment by Reeced40** [comment]
@D-Jeffrey thank you for reaching out. Please confirm if your original query has been solved. I also found an article https://answers.microsoft.com/insider/forum/insider_wintp-insider_security-insiderplat_pc/diagnostic-data-viewer-missing-if-data-viewing-is/16e9fb6b-5a55-4181-aff6-d89f20df5784and related issue - https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1687  for you to have a look at. Let me know if you need further assistance.

**Comment by D-Jeffrey** [comment]
Answers pages is gone.  "Page Not Found
We are sorry we weren't able to find what you are looking for."

As for it fixing the problem.  Well I upgrade my computer for the first time in 8 years so... assuming I'm ok to test a new computer.  It works on the new computer (which is an Insider as well).

it is a pretty cool app.  a whole lot easier than using EventVwer.  Let's call it working.  Close.

Thanks,
Darren
