### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#8809]
The link to investigate devices in MCAS is broken, please fix. it currently points to https://docs.microsoft.com/en-us/cloud-app-security/wdatp-integration#investigate-machines-in-cloud-app-security. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70acebee-16af-18f5-4069-1e4ae0d71fc6
* Version Independent ID: 1dfed329-80c0-b9aa-f168-31f15b43866d
* Content: [Configure Microsoft Cloud App Security integration - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-cloud-app-security-config)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-cloud-app-security-config.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-cloud-app-security-config.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Thanks for reporting the broken link. Confirmed. 404 is the result when clicking that link, both above and in the documentation:
- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-cloud-app-security-config#view-the-data-collected

***

## View the data collected

To view and access Microsoft Defender for Endpoint data in Microsoft Cloud Apps Security, see [Investigate devices in Cloud App Security](https://docs.microsoft.com/cloud-app-security/wdatp-integration#investigate-machines-in-cloud-app-security).

***

Looks like the file `investigate-machines.md` has been deleted, possibly during a clean-up when renaming "Microsoft Defender ATP" to Microsoft Endpoint:
- https://github.com/MicrosoftDocs/windows-itpro-docs/search?q=Investigate+machines

Old archive content:
- https://web.archive.org/web/20201014085523/https://docs.microsoft.com/en-us/cloud-app-security/wdatp-integration#investigate-machines-in-cloud-app-security

***

At least 2 sides to this issue:
1. More than one document using that file link can be found. This change should be amended to fix those broken links.
2. Most of the existing documentation refers to apps, security, installation, alerts, users and management, but hardly any mention of "device" or "devices". Is the concept of "device" a much less relevant topic in Microsoft Cloud App Security integration?

**Comment by illfated** [comment]
Turns out that https://docs.microsoft.com/cloud-app-security/mde-integration#investigate-devices-in-cloud-app-security is the new URL, meaning that the "WDATP" links now probably use the new name "Microsoft Defender for Endpoint (MDE)" and therefore need to be corrected (wdatp -> mde).

Keep that in mind when finding old links still using "wdatp" as part of their URL.

**Comment by illfated** [comment]
Also, thanks to @MaratMussabekov for finding the new URL format. I was not fully aware of this 15 days ago.

**Comment by e0i** [comment]
Closing via #8885. Thanks.
