### ISSUE TITLE
It would be helpful to share WHERE this Registry key is stored now that the name has changed

### ISSUE THREAD

**Issue by ChrisAtFCPS** [MicrosoftDocs/windows-itpro-docs#881]
Many people do not want to manage by GPO but would rather deploy certain settings locally.  Because of the name change to the policy, the old registry key doesn't seem to be taking effect.  Only when I open the LSA control panel and change it does it take effect.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47d74338-f3b8-dfea-b619-5f5be3482226
* Version Independent ID: 879abaca-ac1d-a27e-7cc8-f5b2933e7eeb
* Content: [Interactive logon Don't display last signed-in (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-do-not-display-last-user-name)
* Content Source: [windows/security/threat-protection/security-policy-settings/interactive-logon-do-not-display-last-user-name.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/interactive-logon-do-not-display-last-user-name.md)
* Service: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
I would expect it under Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon but I can't see which entry corresponds to Do not display last user name or Don't display last signed-in. 
I'll pass it along if I can find it but I think best practice is to edit secpol.msc if you want to apply these settings only locally. That's preferable to editing the registry directly.

**Comment by beanmeister** [comment]
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\DontDisplayLastUserName according to the Group Policy Settings Reference for 1803

**Comment by beanmeister** [comment]
Edit to the above; as Justinha mentioned, this would be the same as setting it in GPO and wouldnt be best practice to edit manually, however it might be useful for troubleshooting.
