### ISSUE TITLE
Confusing text

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#8810]
The Note about server licensing is confusing. some words are repeated and acronyms are not defined. Please review and edit this so that people that are not familiar with server licensing terminology can understand what is needed. The whole topic of Defender for Endpoint in regards to servers is very confusing and needs to be simplified. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Existing Note blob:

> [!NOTE]
> Customers with a combined minimum of 50 licenses for one or more of the following may acquire Server SLs for Microsoft Defender Defender for Endpoint for Servers (one per covered Server OSE): Microsoft Defender for Endpoint, Windows E5/A5, Microsoft 365 E5/A5 and Microsoft 365 E5 Security User SLs. This license applies to Defender for Endpoint for Linux.


Proposed change:

> [!NOTE]
> Customers may acquire Server Licenses (SLs) (one per covered Server Operating System Environment (OSE)) for Microsoft Defender Defender for Endpoint for Servers if they have a combined minimum of 50 licenses for one or more of the following User Licenses:
> - Microsoft Defender for Endpoint
> - Windows E5/A5
> - Microsoft 365 E5/A5
> - Microsoft 365 E5 Security

I could be mistaken about some of the details. If you do have specific knowledge in this topic, please advise.

**Comment by DeanGross** [comment]
This is definitely an improvement but Defender is still repeated in "Microsoft Defender Defender for Endpoint for Servers"

**Comment by illfated** [comment]
> This is definitely an improvement but Defender is still repeated in "Microsoft Defender Defender for Endpoint for Servers"

Aha, thank you. I must have been tired when I posted last time. I could make a PR to have the duplicate word removed separately, that should be easy to get approved.

**Comment by illfated** [comment]
On the other hand, I might as well combine the 2 goals in 1 PR, final review & merge may be delayed due to the upcoming holidays anyway.

**Comment by illfated** [comment]
There you go. PR #8861 is ready for review, comments, and suggestions.
