### ISSUE TITLE
Potential Out of Date information

### ISSUE THREAD

**Issue by paflaher** [MicrosoftDocs/windows-itpro-docs#8818]
On the docs page it states that Linux is not supported but planned.

Based on - https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/microsoft-defender-atp-for-linux-is-now-generally-available/ba-p/1482344

It would seem that it is now GA supported on Linux, if this is correct can this be updated to reflect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e907ba50-a076-6fe7-d3ea-87fdbce5ed1b
* Version Independent ID: dbb7073e-e7d3-83f4-22ea-698134062cb2
* Content: [Supported operating systems and platforms for threat and vulnerability management - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/tvm-supported-os)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/tvm-supported-os.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/tvm-supported-os.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by illfated** [comment]
I could very well start a PR to update the table and make it show the various Linux distros as supported, but (to me) it seems a bit difficult to find the list of supported features for Linux Server (OS only, or the same support features as for Windows Server OS). So, basically, I have no problem starting a PR, but I would need to see the current support table list for supported features on Linux to make a complete table row change for the supported distros.

Maybe one of the Tech Writers know more about the availability for these features. @konstruktoid : Have you seen the list of supported features?

**Comment by konstruktoid** [comment]
I think https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-preferences could be used to find supported options, but I haven't seen a list @illfated 

@paflaher, and you are correct. `Not supported (planned)` should be replaced with `Supported` at least since we don't have a list of "Security assessment support".

**Comment by illfated** [comment]
👍🏻 Thank you for the feedback. I thought I should ask, just because you seem to be quite updated on current Linux technologies.

**Comment by illfated** [comment]
There are a couple of options for what to add in the **Security assessment support column** when creating the PR to update the table:
- enter only "Supported" or "See preferences" (linked)
- fill in only "Operating System (OS) vulnerabilities"
- fill in all 5 lines as in the fully supported Windows versions

Anyway, it needs to be reviewed and evaluated in the PR. I will open one, then we'll see.

**Comment by illfated** [comment]
There you go. PR #8820 is ready for review. I based my suggested new content both on the preceding MacOS support and also listed the distros according to the TechNet blog page.

**Comment by levinec** [comment]
@paflaher @illfated thank you for working on this. However, the supported systems and platforms for threat and vulnerability management are sometimes different from the minimum requirements for Microsoft Defender for Endpoint list (as stated in the note in the documentation). Even though TVM is part of MDE, it currently does not support Linux.

**Comment by illfated** [comment]
OK, fair enough. I thought it was supposed to show a supported state, but I trust you know this topic better than me or the others here, so we trust your decision to close this ticket and its related PR.
