### ISSUE TITLE
APIC Virtualization and SMM Firmware Measurement missing in documentation

### ISSUE THREAD

**Issue by sveinungre** [MicrosoftDocs/windows-itpro-docs#8819]
On a HP EliteDesk 800 G6 Desktop Mini PC model, I have additional values not mentioned in this documentation.

AvailableSecurityProperties:
8 = APIC Virtualization (I belive, it adds up with what I see in msinfo32)

SecurityServicesConfigured:
4 = SMM Firmware Measurement (I belive, it adds up with what I see in msinfo32)

SecurityServicesRunning:
4 = SMM Firmware Measurement (I belive, it adds up with what I see in msinfo32)

**Comment by RAJU2529** [comment]
@sveinungre Which article are you referring to

**Comment by sveinungre** [comment]
https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity

**Comment by RAJU2529** [comment]
@sveinungre  Could you post the screenshot of system info 32

**Comment by sveinungre** [comment]
Yes attached. But I'm sure you can reach out to the correct team to confirm this.




Sveinung

**Comment by RAJU2529** [comment]
@sveinungre  where is the screenshot

**Comment by sveinungre** [comment]
Mm I attached in email but I see it did not work. Lets try this:

![image](https://user-images.githubusercontent.com/49359654/102458000-e4c47980-4043-11eb-82f6-bf65061d983a.png)

![image](https://user-images.githubusercontent.com/49359654/102458022-ec841e00-4043-11eb-9313-38fcc1720c30.png)

![image](https://user-images.githubusercontent.com/49359654/102458030-f0b03b80-4043-11eb-91ee-54031ade6b66.png)

**Comment by illfated** [comment]
PR #8887 is available for review, comments, and suggestions. Thanks to @joinimran for the PR.

**Comment by levinec** [comment]
PR is merged. Thanks!
