### ISSUE TITLE
Suspect documentation content for Create global objects Right

### ISSUE THREAD

**Issue by PishPoshery** [MicrosoftDocs/windows-itpro-docs#882]
[Enter feedback here]

The content below in the Create Global Objects documentation appear to have been cut and paste from the Create Token Object right listed just before it.

https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-global-objects

Windows examines a user's access token to determine the level of the user's privileges. Access tokens are built when users log on to the local device or connect to a remote device over a network. When you revoke a privilege, the change is immediately recorded, but the change is not reflected in the user's access token until the next time the user logs on or connects. Users with the ability to create or modify tokens can change the level of access for any currently logged on account. They could escalate their privileges or create a denial-of-service (DoS) condition.

Countermeasure
Do not assign the Create a token object user right to any users. Processes that require this user right should use the Local System account, which already includes it, instead of a separate user account with this user right assigned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e54fd0e4-8388-8c8d-6e0b-aa24fc6449b4
* Version Independent ID: 14f950fd-3333-d362-af35-a313854fab9a
* Content: [Create global objects (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-global-objects)
* Content Source: [windows/security/threat-protection/security-policy-settings/create-global-objects.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/create-global-objects.md)
* Service: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@PishPoshery -  Thank you for submitting feedback. 

The content has been updated with the changes that you requested for. However, it may take a few days for the content changes to reflect in the article. Thanks.

**Comment by mypil** [comment]
@officedocsbot close
