### ISSUE TITLE
Firmware-embedded activation key

### ISSUE THREAD

**Issue by Flo9211** [MicrosoftDocs/windows-itpro-docs#8821]
Hey.

Since Get-WmiObject has been superseded by Get-CimInstance starting in PowerShell 3.0 I had problems with (Get-WmiObject -query ‘select * from SoftwareLicensingService’).OA3xOriginalProductKey. I used (Get-CimInstance -query `select * from SoftwareLicensingService').OA3xOriginalProductKey instead.
Maybe makes sense to add.

Best,
Florian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ecbc1-9c02-5681-7214-356be22ac7e8
* Version Independent ID: 73af82f6-079b-6c37-55c4-cb59e921457a
* Content: [Deploy Windows 10 Enterprise licenses - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-enterprise-licenses#feedback)
* Content Source: [windows/deployment/deploy-enterprise-licenses.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-enterprise-licenses.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by nam31** [comment]
Closing via #8868 
Thank you
