### ISSUE TITLE
Incorrect cli info 

### ISSUE THREAD

**Issue by bledMS82** [MicrosoftDocs/windows-itpro-docs#8822]
To enable or disable real-time-protection the cmd's are 

mdatp config real-time-protection --value enabled
mdatp config real-time-protection --value disabled

please update as the --value is missing in the docs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07f72a75-ca85-0651-1512-8ffb62d0ab7b
* Version Independent ID: 6e15dd30-1db2-4a18-a18c-c343e1d508cd
* Content: [Resources for Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-resources#configuring-from-the-command-line)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-resources.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
(ref. #8721, #8797)
