### ISSUE TITLE
It is wrong explanation about license requirements

### ISSUE THREAD

**Issue by jyama4ta** [MicrosoftDocs/windows-itpro-docs#8823]
[Enter feedback here]
The note on 'Windows 10 Enterprise requirements' explains cx don't need Azure AD activation. However, it is different from Product terms <https://www.microsoft.com/en-us/licensing/product-licensing/products>. PT requires Azure AD-based activation as below. This description is misleading to customers. So could you please consider to remove the notes? Thank you.

>3.8 Windows 10 Multitenant Hosting
Customers with Windows 10 Enterprise Per User SLs (excluding local only), Windows 10 Education Per User SLs, or VDA Per User SLs using Azure AD-based activation may install the Windows 10 Creators Update or later version software on a virtual machine running on Microsoft Azure (notwithstanding anything to the contrary in the Outsourcing Software Management clause) or a shared server with a Qualified Multitenant Hosting Partner ("QMTH") identified at www.microsoft.com/Qualified_Multitenant_Hoster_Program. Rights to install and use the software with a QMTH do not apply if the QMTH is using a Listed Provider as a Data Center Provider. Each Licensed User may access up to four instances of the software. Azure Government customers may use KMS activation in lieu of Azure AD-based activation. When configuring the image(s) on Microsoft Azure, Customers must indicate their use of the multitenant hosting for Windows 10 and adhere to other software configuration requirements available at https://docs.microsoft.com/en-us/windows/deployment/vda-subscription-activation. Partner based deployment requirements are available at www.microsoft.com/Qualified_Multitenant_Hoster_Program. This section does not apply to Students receiving access to software through Student Use Benefit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation#requirements)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jyama4ta** [comment]
Please note that KMS activation is allowed in the case of Azure Government customers only.

**Comment by greg-lindsay** [comment]
The notes in the article are correct.  The product team document probably needs to be clarified.  There is much confusion about activation because Subscription Activation is believed to be for all activation, but it is not. Subscription Activation is for stepping up from Pro to Enterprise.

**Comment by jyama4ta** [comment]
In my experience, Windows support team told us that there are licensing concerns if Win10 on Azure VMs are activated by KMS activation. Also, License team says that Win10 on Azure VMs must be activated by AAD-based activation (i.e. Subscription Activation). So, we should use Win10 pro image as following doc.
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/windows-desktop-multitenant-hosting-deployment
