### ISSUE TITLE
Colliding file paths when cloning repository

### ISSUE THREAD

**Issue by konstruktoid** [MicrosoftDocs/windows-itpro-docs#8824]
```sh
Cloning into 'windows-itpro-docs'...
remote: Enumerating objects: 327, done.
remote: Counting objects: 100% (327/327), done.
remote: Compressing objects: 100% (156/156), done.
remote: Total 335228 (delta 244), reused 230 (delta 169), pack-reused 334901
Receiving objects: 100% (335228/335228), 863.19 MiB | 12.41 MiB/s, done.
Resolving deltas: 100% (263756/263756), done.
Updating files: 100% (8522/8522), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'windows/deployment/images/configmgr-assets.PNG'
  'windows/deployment/images/configmgr-assets.png'
```

**Comment by illfated** [comment]
If this is done on a Windows computer, it seems to indicate that there is at least one file with a duplicate name, but with different case on the extension part of the file name. Not sure if this is related to one of my attempts to replace an existing image containing uppercase .PNG with an image using only lowercase (but that was more than a year ago, perhaps from when I started contributing to this repository.

You may want to check out which one of the image files is actually used by a document in this repo (hopefully not both) to see if it would be possible to suggest removing the offending file from this repo.
