### ISSUE TITLE
Powershell definition update script 

### ISSUE THREAD

**Issue by gsmitheidw** [MicrosoftDocs/windows-itpro-docs#8827]
The unpacking powershell script on this page is a bit broken. For example $args = @("/x") on the 5th line is never actually used at all! What happens on a subsequent run that pulls down a new GUID? It's not at all clear.

Also would it not be better to get rid of the oldfashioned "cmd /c" and use pure powershell such as:
Start-Process $vdmpackage $unpackargs -Wait  etc

Furthermore this should be made much more generic, many will want to run this from an azure script session extracting to Azure files share for clients. "c:\" should be replicable with a unc path. 

Thanks,

Graham

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84fc852e-4ce0-1d6d-fbc8-76732407e576
* Version Independent ID: 30d715c0-35f0-0b52-68da-75a5f85a619b
* Content: [Microsoft Defender Antivirus Virtual Desktop Infrastructure deployment guide - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/deployment-vdi-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/deployment-vdi-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/deployment-vdi-microsoft-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
Thank you for the insight and suggestions. I am sure this will be considered by the MS Docs team and forwarded to the software team.

By the way, have you considered using the Windows Feedback feature to send response to the developers? That channel is considered a quicker route to reach the developers.

**Comment by gsmitheidw** [comment]
The feedback link at the bottom of the page directly references this GitHub issue page, I just followed the logical button on the page. 

Why wouldn't developers be directly watching GitHub as a first port of call? Not very "DevOps". Where should I be submitting issues?  If it's not GitHub under the section in bold heading text marked Feedback, then it isn't very clear.

**Comment by MaratMussabekov** [comment]
Hello @gsmitheidw ,
**$args = @("/x") on the 5th line is never actually used** - fixed at PR #8867
**Also would it not be better to get rid of the oldfashioned "cmd /c" and use pure powershell** - I checked it, tried to extract from mpam-fe.exe using powershell, but unfortunately it didn't work, so it looks like it simply doesn't support it (i tried to do it several different ways). I think for now it should be left as "cmd /c", and when there will be a way to execute it using powershell, the docs must be updated accordingly.
**"c:" should be replicable with a unc path.** - not sure about UNC path, I'd rather use system variable, please have a look at #8867

Thank you

**Comment by nam31** [comment]
Closing via #8867 
Thank you
