### ISSUE TITLE
StatusCode: 404, ReasonPhrase: 'Not Found' listing machine via api/machines

### ISSUE THREAD

**Issue by sunilprabha** [MicrosoftDocs/windows-itpro-docs#8830]
I have created a console application with app id , got a bearer token from Azure AD  and sent to api/machine to  list get all machines, i have granted Machine.Read.All, However i get this response 404 

StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
    IsSuccessStatusCode: false
    ReasonPhrase: "Not Found"
    RequestMessage: {Method: GET, RequestUri: 'https://api.securitycenter.windows.com/api/machine', Version: 1.1, Content: <null>, 

            var httpClient = new HttpClient();
            var request = new HttpRequestMessage(HttpMethod.Get, "https://api.securitycenter.windows.com/api/machine");
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", Accesstoken);
            var response = httpClient.SendAsync(request).GetAwaiter().GetResult();
What does this mean . When I log on to defender https://securitycenter.windows.com/machines  i see lot of machines. 
Please point me in the correct direction.
Regards
Sunil Prabha

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce06635a-e51d-4eed-427d-0119edc1d58c
* Version Independent ID: f62a5abb-7920-2129-0874-f10ad42172d7
* Content: [List machines API - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/get-machines)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/get-machines.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/get-machines.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
Hello,

Looks like this question can best be answered via relevant [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channels. 

Please consider checking with [Microsoft Community](https://answers.microsoft.com/en-us/windows/forum/windows_10) or [contacting support](https://support.microsoft.com/contactus) for your problem; The issues section of this repository is for content fixes in documentation.

If you feel that the associated article also needs to be updated for any reason feel free to re-open this issue or [contribute with a pull request](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/CONTRIBUTING.md).

Thank you.
