### ISSUE TITLE
Upgrade Readiness mentioned

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/windows-itpro-docs#8833]
This page mentions using Upgrade Readiness which is deprecated.  May want to change it out to Desktop Analytics.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34937b5e-eda3-9c93-c31b-0701ea61198a
* Version Independent ID: 36f54d9f-503d-ea0a-bff2-3441571f8d44
* Content: [Quick guide to Windows as a service (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-quick-start)
* Content Source: [windows/deployment/update/waas-quick-start.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-quick-start.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
Thanks for the feedback & reference. Looks like this will be an ongoing process, still 500+ pages containing that expression:

**539 results for ""Upgrade Readiness""**
- https://docs.microsoft.com/en-us/search/?terms=%22Upgrade%20Readiness%22

**Comment by yogkumgit** [comment]
@russrimm Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
