### ISSUE TITLE
Experience/DisableCloudOptimizedContent

### ISSUE THREAD

**Issue by KoryKliner** [MicrosoftDocs/windows-itpro-docs#8838]
Experience/DisableCloudOptimizedContent is double-listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e8ecbe3-ba72-ec44-0591-7f604d50b1e3
* Version Independent ID: 9d5ff118-d539-dd6e-ae3e-102392c22287
* Content: [Policy CSP - Experience - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-experience)
* Content Source: [windows/client-management/mdm/policy-csp-experience.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-experience.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by ManikaDhiman** [comment]
Hi @KoryKliner, Thanks for pointing this out. I removed the duplicate Experience/DisableCloudOptimizedContent entry from the topic; updates will be live shortly. Thanks again for the feedback!

**Comment by illfated** [comment]
Resolved in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/4efc7e487dddc7fd10fe13f4f536496a359c0a9a . Should be live now.
