### ISSUE TITLE
Audit Events not working on Win10 Business Edition

### ISSUE THREAD

**Issue by CDjgould** [MicrosoftDocs/windows-itpro-docs#8839]
The documentation clearly states that these audit events should work on Windows 10 Business Edition. However I've applied them through the Intune Security Baseline policy and they do NOT work. Event Viewer clearly states that the "Policy is rejected by licensing" for all of them.

Here are the settings that error due to this "licensing" error. 
```
Audit | Object Access Audit Other Object Access Events (Device) | error
Audit | Object Access Audit Other Object Access Events (Device) | error
Audit | Object Access Audit Detailed File Share (Device) | error
Audit | Object Access Audit Detailed File Share (Device) | error
Audit | Policy Change Audit Other Policy Change Events (Device) | error
Audit | Policy Change Audit Other Policy Change Events (Device) | error
Audit | Account Logon Audit Credential Validation (Device) | error
Audit | Account Logon Audit Credential Validation (Device) | error
Audit | Audit Other Logon Logoff Events (Device) | error
Audit | Audit Other Logon Logoff Events (Device) | error
Audit | Detailed Tracking Audit PNP Activity (Device) | error
Audit | Detailed Tracking Audit PNP Activity (Device) | error
Audit | Detailed Tracking Audit Process Creation (Device) | error
Audit | Detailed Tracking Audit Process Creation (Device) | error
Audit | Audit User Account Management (Device) | error
Audit | Audit User Account Management (Device) | error
```

You can check the documents for each one and see they are listed as supported.

And an example of event viewer (audit other logon/logoff events)
![Untitled](https://user-images.githubusercontent.com/22243767/102572075-25120f00-40b9-11eb-9ab3-b69450ba9bed.png)

![Untitled2](https://user-images.githubusercontent.com/22243767/103178797-229b7c00-4854-11eb-8ddc-d664b58e7f64.png)

So is it supported or not? I don't know but I've been unable to get an answer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dabca3f2-2b25-dc4d-9486-57ddfed187f8
* Version Independent ID: 561d395b-ef2d-589f-7bb3-c72e6862ca53
* Content: [Policy CSP - Audit - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-audit#audit-accountlogonlogoff-auditotherlogonlogoffevents)
* Content Source: [windows/client-management/mdm/policy-csp-audit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-audit.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@CDjgould It is supported starting with Windows 10, version 1903, according to the footnotes. What Windows 10 version are you using?

> 6 - Available in Windows 10, version 1903.

**Comment by CDjgould** [comment]
@VLG17 I'm fully updated to 20H2. Windows 10 Business (upgraded from Pro with the Microsoft 365 business premium licensing). It should work according to all the documentation but clearly shows in the audit logs as errors due to licensing.

**Comment by CDjgould** [comment]
I realized I didn't also post the windows event log that showed the "rejected by licensing policy" image. I've updated the original post with it. Event ID 827.

**Comment by illfated** [comment]
Judging by the license level, I would think you have got access to Microsoft Support for this kind of issue, or have I misunderstood something?

(Just thinking that maybe feedback from Microsoft Support could be helpful to improve the document.)

**Comment by VLG17** [comment]
@CDjgould Thank you for your answered and the details added. As @illfated also mentioned, i think the best thing would be to reach out to [Windows 10 Support](https://support.microsoft.com/contactus). If they conclude that the documentation will need to be changed, we will gladly do that.

**Comment by nam31** [comment]
Thank you for providing feedback. 
Your initial question seems to have been answered by @VLG17 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)
Thank you.
