### ISSUE TITLE
Windows 10, version1803 Group Policies

### ISSUE THREAD

**Issue by cas77** [MicrosoftDocs/windows-itpro-docs#884]
There is no information about the new Group Policies in Windows 10, version 1803.
If there are no new/different Group Policies in Windows 10, version 1803 one should drop a short info about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c3e60ec-cf61-c34b-db79-74b13e3ee867
* Version Independent ID: fc5079f7-a563-c627-3a3e-eb84a99e4fd3
* Content: [New policies for Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/new-policies-for-windows-10)
* Content Source: [windows/client-management/new-policies-for-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/new-policies-for-windows-10.md)
* Service: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **dongill**

**Comment by shortpatti** [comment]
@jdeckerms, can you take a look at this one?  Let me know if I need to reassign it :)

**Comment by jdeckerms** [comment]
That one is Corey’s, thanks!

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by j0rt3g4** [comment]
@mypil Let's link the author since I'm not aware of such changes so I can add the note into the PR :)

**Comment by mypil** [comment]
@coreyp-at-msft @DaniHalfin @Justinha @mjcaparas @greg-lindsay @jaimeo - Can you please share your insights on this issue?

Thank you.

**Comment by j0rt3g4** [comment]
Adding a link to a spreadsheed where all the changes into policies by versión can be filtered and obtained.
PR #3766 

![image](https://user-images.githubusercontent.com/5489996/58123927-91254c00-7bd2-11e9-91f6-df0d431d387f.png)

**Comment by mypil** [comment]
@cas77 - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
