### ISSUE TITLE
Incorrect Update?

### ISSUE THREAD

**Issue by maxgara** [MicrosoftDocs/windows-itpro-docs#8840]
I recently noticed that at some point this page seems to have been updated to reflect the idea that event 4625 is logged only in the circumstances that "an account logon attempt failed when the account was already locked out. It also generates for a logon attempt after which the account was locked out." This is at odds with my own professional experience seeing this event logged for all instances of logon failure. I am not sure where to find official information to confirm that this is incorrect, other than the text in the event log itself which states simply "This request is generated when a logon request fails. It is generated on the computer where access was attempted."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80307c25-b809-e9b8-bab2-d37d3de7e920
* Version Independent ID: 24c32be1-2fc3-f22f-7e6c-da4049bf8458
* Content: [4625(F) An account failed to log on. (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4625)
* Content Source: [windows/security/threat-protection/auditing/event-4625.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4625.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@maxgara Looking at the 4625 EventID, specificaly the Failure Information section, the Failure reason is "Account locked out", which would confirm the description presented.

Are you seeing 4625 events with other Failure reasons?

Maybe it's also worth checking your [Account lockout policy](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/hh994563(v=ws.11)).

**Comment by ruffy91** [comment]
@VLG17 There are also event 4625 events specifying the other 20 available reasons. Probably most seen in the field:
0xC0000064 | User logon with misspelled or bad user account
0xC000006A | User logon with misspelled or bad password

The misunderstanding most probably stems from the fact that the same Event ID (and description article) is used for "Audit Logon" and "Audit Account Lockout".
The updated description is only true for the "Audit Account Lockout" policy but is also linked for the "Audit Logon" policy.
They should probably be separate entries

![image](https://user-images.githubusercontent.com/344634/103180092-e89d9a80-4892-11eb-8c6e-ef257e18f347.png)

**Comment by maxgara** [comment]
@VLG17 yes I mainly see event 4625 with other failure reasons, with most common ones being those @ruffy91 mentioned. Personally I think having 2 different entries for the same event would be misleading, it would be better to have a single entry which accurately describes the event code in all circumstances. Information about audit policies could be useful as an additional section.

**Comment by nam31** [comment]
@Dansimp, can you please give your insights here?

**Comment by dcjacob1999** [comment]
@jay98014 confirmed the event is logged for any logon failure, not just "an account logon attempt failed when the account was already locked out". I recommend we amend the doc to reflect the true nature of the event
@Dansimp tagging for visibility
