### ISSUE TITLE
Jamf Pro Defender Notifications Instructions are Incorrect

### ISSUE THREAD

**Issue by wmehilos** [MicrosoftDocs/windows-itpro-docs#8842]
The listed instructions in Step 4 provide a pre-built mobile config profile, which while it is in PLIST format, is not the same kind of PLIST that Jamf Pro expects when uploading MCX settings. The full `.mobileconfig` Profile can be signed and uploaded the same way the Network Filter payload can be in Step 9, otherwise, a bare PLIST with only the key/value pairs required for each settings domain should be provided (without all the PayloadIdentifier information, UUIDs, and so on) like it is for the MS Defender settings in Step 3. As it is now, you're basically telling people to commit .mobileconfig-ception by storing a full mobile config file inside of a mobile config profile. In some albeit limited testing on my own hardware, this profile, created and deployed as directed, does not successfully allow notifications and the user will still be prompted for permission. 

It's also my understanding that the `GroupingType` key doesn't apply to macOS, only iOS 12 and above. 

The following is a semi-working PLIST that I created with a community created custom schema JSON that accurately enables and locks Notifications settings for Defender (though it doesn't seem to be locking the AutoUpdate notifications) when deployed using an Application and Custom Settings config profile Payload with Jamf Pro 10.26.1.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>NotificationSettings</key>
    <array>
      <dict>
        <key>AlertType</key>
        <integer>2</integer>
        <key>BadgesEnabled</key>
        <true/>
        <key>BundleIdentifier</key>
        <string>com.microsoft.autoupdate2</string>
        <key>CriticalAlertsEnabled</key>
        <true/>
        <key>NotificationsEnabled</key>
        <true/>
        <key>ShowInLockScreen</key>
        <true/>
        <key>ShowInNotificationCenter</key>
        <true/>
        <key>SoundsEnabled</key>
        <true/>
      </dict>
      <dict>
        <key>AlertType</key>
        <integer>2</integer>
        <key>BadgesEnabled</key>
        <true/>
        <key>BundleIdentifier</key>
        <string>com.microsoft.wdav.tray</string>
        <key>CriticalAlertsEnabled</key>
        <true/>
        <key>NotificationsEnabled</key>
        <true/>
        <key>ShowInLockScreen</key>
        <true/>
        <key>ShowInNotificationCenter</key>
        <true/>
        <key>SoundsEnabled</key>
        <true/>
      </dict>
    </array>
  </dict>
</plist>
```
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f791dc07-b2c6-3003-a829-cd1ec03a2918
* Version Independent ID: 2c53adbc-600f-60b2-e8b2-b907335f4862
* Content: [Set up the Microsoft Defender ATP for macOS policies in Jamf Pro - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @wmehilos - Thank you for your feedback. Can you please confirm in step 4, where we can place this code? The current notif.mobileconfig file from Github will be replaced by this code?

Thanks
Imran

**Comment by nam31** [comment]
@wmehilos Can you please provide your input?

**Comment by nam31** [comment]
@wmehilos We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve. Thank you.

**Comment by motionbug** [comment]
In Jamf Pro now you do not need a custom XML setting. There is now a macOS notifications payload that can deploy the notification settings you need. 

Just remember your Bundle ID is: **com.microsoft.wdav.tray**

This works. See below

![CleanShot 2021-08-30 at 11 56 54@2x](https://user-images.githubusercontent.com/36737/131322185-f8ef1cf0-2579-44ff-91d3-755e1fe3cc29.png)
