### ISSUE TITLE
Remove the Jamf enrollment page

### ISSUE THREAD

**Issue by mbrrg** [MicrosoftDocs/windows-itpro-docs#8856]
Is setting up Jamf Pro device enrollment really in the scope for Defender setup? It just increases the confusion. You should expect Jamf to be setup already.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba08e466-0a94-5356-6dcb-3fda32e21cf8
* Version Independent ID: b59676b9-bf73-a885-a1d9-a84ca1107d33
* Content: [Enroll Microsoft Defender ATP for macOS devices into Jamf Pro - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-enroll-devices)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-enroll-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-enroll-devices.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by aczechowski** [comment]
Doing repo cleanup, I'm closing this issue as the article was moved to a new repo, you can find the current article at
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-jamfpro-enroll-devices?view=o365-worldwide
I'm sending this issue (and others for this area) to the current authors for their review. If there's still an update needed, please file new feedback on the current article in the other repo.
