### ISSUE TITLE
Functionality and features available in each state table is wrong

### ISSUE THREAD

**Issue by MS-binche** [MicrosoftDocs/windows-itpro-docs#8859]
Can we revise the table by engaging the engineering team, this table is 100% wrong, example is that RTP is not available when defender in passive mode while the table marks RTP available in passive mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b88aee4-6727-fa98-1180-29708eea027e
* Version Independent ID: 374c671b-b21c-6eac-d887-892491357eb2
* Content: [Microsoft Defender Antivirus compatibility with other security products - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @MS-binche. Thanks again for posting your feedback on my article. The article has been updated and should be correct as it is right now. Please let me know if you have any further questions.
