### ISSUE TITLE
ADBA on 2016

### ISSUE THREAD

**Issue by EDTIVA** [MicrosoftDocs/windows-itpro-docs#886]
Change applies to section to say Server 2016.  See comments section here for info that it is supported https://blogs.technet.microsoft.com/askcore/2016/10/19/windows-server-2016-volume-activation-tips/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d0692f7-f4e8-5d5d-7d38-db343161ae4b
* Version Independent ID: 9f852760-394c-0621-de03-362aa21dc335
* Content: [Activate using Active Directory-based activation (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/volume-activation/activate-using-active-directory-based-activation-client#feedback)
* Content Source: [windows/deployment/volume-activation/activate-using-active-directory-based-activation-client.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/volume-activation/activate-using-active-directory-based-activation-client.md)
* Service: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@EDTIVA - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
