### ISSUE TITLE
wrong mask descriptions in 4147

### ISSUE THREAD

**Issue by MValiukh** [MicrosoftDocs/windows-itpro-docs#8863]
Why does the description of event 4147 say that mask 0x80 is ENCRYPTED_TEXT_PWD_ALLOWED? But in fact the mask 0x80 is WORKSTATION_TRUST_ACCOUNT!!! Where to get the correct masks of this event for monitoring - since the description has the wrong information?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881049ef-5df0-bc80-12b1-bb27217cdad5
* Version Independent ID: 71ddceeb-db97-27ca-c45c-e4745541b970
* Content: [4741(S) A computer account was created. (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4741)
* Content Source: [windows/security/threat-protection/auditing/event-4741.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4741.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Do you have any reference or source for your statement? From my preliminary searches on the web, it seems that others agree to the following:

| Property Flag                   | Hex value | Decimal value |
| :------------------------------ | :-------: | ------------: |
| SCRIPT                          |   0x0001  |             1 |
| ACCOUNTDISABLE                  |   0x0002  |             2 |
| HOMEDIR_REQUIRED                |   0x0008  |             8 |
| LOCKOUT                         |   0x0010  |            16 |
| PASSWD_NOTREQD                  |   0x0020  |            32 |
| PASSWD_CANT_CHANGE              |   0x0040  |            64 |
| ENCRYPTED_TEXT_PWD_ALLOWED      |   0x0080  |           128 |
| TEMP_DUPLICATE_ACCOUNT          |   0x0100  |           256 |
| NORMAL_ACCOUNT                  |   0x0200  |           512 |
| Disabled Account                |   0x0202  |           514 |
| Enabled, Password Not Required  |   0x0220  |           544 |
| Disabled, Password Not Required |   0x0222  |           546 |
| INTERDOMAIN_TRUST_ACCOUNT       |   0x0800  |          2048 |
| WORKSTATION_TRUST_ACCOUNT       |   0x1000  |          4096 |
| SERVER_TRUST_ACCOUNT            |   0x2000  |          8192 |

Is there any new documentation available elsewhere that we don't know about yet?

**Comment by MValiukh** [comment]
First, the fact that incorrect information can be found on the official Microsoft website is a huge problem! Many companies when building an information security incident monitoring system and during cyber-attack investigations use this source as the main source. In this case, when we talk about event 4741 and userAccountControl 0x80 - this is very critical, because in the monitoring system will happen a critical event - Encrypted Text Password Allowed but in fact this is a normal Workstation Trust Account event. This situation could cause the cyber investigation to be untrue because of an incorrect description of the event and could lead to legal risks for the company.
1.	You can do a simple test: you can add a computer to the domain and view 4741 event on the domain controller. The userAccountControl mask will be 0x80 if the computer was entered manually and 0x85 if the computer was entered by the script.
2.	On your website https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4741 even in the screenshot you can see that the example is taken event 4741 where the mask is 0x80 - below it says Workstation Trust Account. Take a look at.
![image](https://user-images.githubusercontent.com/68642582/103127947-1a004580-469c-11eb-83b1-3442df3b5d45.png)
3.	There is a source that gives the correct information: the book Windows Security Monitoring: Scenarios and Patterns. The description in that book is exactly the same as the correct information.
Page 254 Listing 7-12: Event ID 4741: A computer account was created.
It says below:
«All new computer objects, which are not domain controllers, have the 'Workstation Trust Account' flag enabled in UAC.
Computer account creation event uses the same schema as user account creation, but adds some extra fields.»
Next
Page 151 Table 5-2: User Account UAC Flags
![image](https://user-images.githubusercontent.com/68642582/103127966-2d131580-469c-11eb-9df7-bb430b974036.png)
0x80 - Workstation Trust Account – Enabled
So if 0x85
![image](https://user-images.githubusercontent.com/68642582/103127995-487e2080-469c-11eb-8cc3-cc70d7a197c2.png)
0x80 - Workstation Trust Account – Enabled
0x04 - Password Not Required – Enabled
0x01 - Account Disabled

**Comment by illfated** [comment]
Very interesting. That looks like we should do our best to rectify that missed change. I will ask the MS Docs team members to confirm the importance of this information and decide how to make the necessary changes.

**Comment by MValiukh** [comment]
Is there any update on this case?

**Comment by dcjacob1999** [comment]
@jay98014 confirmed the masks in the doc are from an incorrect (non user-facing mapping). I recommend we remove the 4147 mask table and replace with the aforementioned link. Thank you Jay!
@Dansimp  tagging for visibility

**Comment by MValiukh** [comment]
You closed case? But information about wrong mask 0x80 - ENCRYPTED_TEXT_PWD_ALLOWED is still present in description on event 4741!


________________________________
