### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/windows-itpro-docs#8864]
For more information, see Assign administrator and non-administrator roles to uses with Azure Active Directory.
(near the bottom of the page)

uses should read users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb427fd5-e30d-101e-7905-544f9eb5081e
* Version Independent ID: bf829c27-33f5-b9b5-7923-9dd47dd10657
* Content: [Use basic permissions to access Microsoft Defender Security Center - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/basic-permissions)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/basic-permissions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/basic-permissions.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
@andrePKI : Thank you for pointing out the typo. I am going to make a PR to request the necessary change update.

Note: I see now that the typo is quite inconspicuous as in seemingly making sense, or being so close to the correct word that it is easily missed by most native English speakers.

**Comment by illfated** [comment]
There you go. PR #8865 is ready for review, comments and suggestions.
