### ISSUE TITLE
6in4 (v6v4tunnel)

### ISSUE THREAD

**Issue by treysis** [MicrosoftDocs/windows-itpro-docs#887]
This function has ceased to work. However, it's not exactly 6to4, but still a transition technology. Has this been forgotten to be mentioned under deprecated features? Also, if it is newly disabled in 1803 (as opposed to 1709 and before), is there a way to enable it? Documentation on this is very scarce.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c274f8df-31da-f58a-36af-dc7eb6ace762
* Version Independent ID: 0e33637d-e094-edbc-04f9-e8d5e6c642c6
* Content: [Windows 10, version 1803 - Features that have been removed](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-1803-removed-features)
* Content Source: [windows/deployment/planning/windows-10-1803-removed-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-10-1803-removed-features.md)
* Service: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by treysis** [comment]
Any news on this?

**Comment by treysis** [comment]
Really no news? It's also an issue on every insider build.

**Comment by grawity** [comment]
> Has this been forgotten to be mentioned under deprecated features?

It's mentioned under the name of "Direct Tunnels".

**Comment by treysis** [comment]
Well, I understand that now. However, it says it has "always" been disabled by default. But from at least Vista up until including 1709 it was working just fine. Disabled in this sense probably only meant that there is no default setup and you have to find your own tunnel broker to enable/activate it. However, with 1803 even activation is not possible anymore. Nettun.inf has simply been purged. No way to activate it anymore.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @treysis,
in the article it doesn't says that it is "disabled in 1803", instead, it says: "We are no longer actively developing these features and may remove them from a future update"
as to disabled, it says about previous versions, not 1803 (in the "Instead you can use" column) 
so I think, the article shouldn't be updated, what do you think?
Thank you

**Comment by treysis** [comment]
Dear @MaratMussabekov 
thank you for your reply. v6v4tunnel was simply broken in 1803 because they changed how it is working. It has been fixed with the new method in 1809 and is working fine again. So, whatever they mean by "disabled", this was simply a bug that got fixed after all.

**Comment by mypil** [comment]
@treysis -  Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
