### ISSUE TITLE
Missing endpoint in Microsoft Store section

### ISSUE THREAD

**Issue by ruffy91** [MicrosoftDocs/windows-itpro-docs#8874]
Microsoft Store also needs connection to the HTTPS endpoint "livetileedge.dsx.mp.microsoft.com" to work.
Blocking connection to this endpoint stops the Microsoft Store App from loading any content

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 86af6b9e-99a1-3626-0ba9-285ddf3681d0
* Version Independent ID: 455af345-7fc9-24d6-f554-b78cbccd3419
* Content: [Verbindungsendpunkte für Windows 10 Enterprise, Version 20H2 - Windows Privacy](https://docs.microsoft.com/de-de/windows/privacy/manage-windows-20h2-endpoints)
* Content Source: [windows/privacy/manage-windows-20H2-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/manage-windows-20H2-endpoints.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Gental-Giant
* Microsoft Alias: **v-hakima**

**Comment by ruffy91** [comment]
Also the following endpoints are additionally required to install any store apps.
Maybe someone related to Microsoft should check the tests which lead to this list, the methodology is probably flawed.
The list of endpoints is incomplete and as such misleading and should be revised.

- cid-8b18c79bcc1cb456.users.storage.live.com (probably wrong attributed to OneDrive in the list as *.storage.live.com)
- jcmsfd.account.microsoft.com (missing completely)
- logincdn.msauth.net (required for login with Microsoft account in Store App)
- storeedgefd.dsx.mp.microsoft.com
- substrate.office.com (probably wrong attributed to Office in the list)
- store-images.s-microsoft.com (missing completely)
- statics-storeexp-neu-ms-com.akamaized.net (missing completely)
- www.microsoft.com (missing completely, oddly it is really required to load any app)
- paymentinstruments.mp.microsoft.com
- purchase.mp.microsoft.com

**Comment by illfated** [comment]
Interesting. That looks like such a big job that I can't imagine how much work that involves for someone paid to do exactly that kind of work. I don't envy them.

**Comment by joinimran** [comment]
Hello @ruffy91 - Thank you for sharing your feedback here. Can you please confirm the source of the URLs you have mentioned missing in the documents. I was trying to get this fixed but I am not able to get any concrete information regarding some of the mentions URLs.

Thanks.
Imran
