### ISSUE TITLE
Windows Defender endpoints incomplete and typo

### ISSUE THREAD

**Issue by ruffy91** [MicrosoftDocs/windows-itpro-docs#8876]
The endpoint for Cloud-based Protection "wdcpalt.microsoft.com" is missing.
The endpoint for SmartScreen is "*.smartscreen.microsoft.com" and not "*smartscreen.microsoft.com" (missing dot)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a439d706-e19e-9d96-d83f-a42cf1b1d89c
* Version Independent ID: 423fa9b1-b910-9b9c-7dc2-57eefdd72531
* Content: [Windows 10, Version 20H2: Verbindungsendpunkte für Nicht-Enterprise-Editionen - Windows Privacy](https://docs.microsoft.com/de-de/windows/privacy/windows-endpoints-20h2-non-enterprise-editions)
* Content Source: [windows/privacy/windows-endpoints-20H2-non-enterprise-editions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/windows-endpoints-20H2-non-enterprise-editions.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Gental-Giant
* Microsoft Alias: **v-hakima**

**Comment by Gental-Giant** [comment]
Good catch. Thank you!

**Comment by Gental-Giant** [comment]
#sign-off

**Comment by illfated** [comment]
@Gental-Giant : Have you started working on a PR to resolve this issue?

**Comment by illfated** [comment]
@ruffy91 : I presume your tickets don't overlap each other, so separate tickets get separate Pull Requests to resolve them. OK?

**Comment by illfated** [comment]
PR #8893 is now available for review, comments, and suggestions.

**Comment by nam31** [comment]
Closing via #8893 
Thank you
