### ISSUE TITLE
Missing package names for windows 10 1803

### ISSUE THREAD

**Issue by jandreacola** [MicrosoftDocs/windows-itpro-docs#888]
article is tagged as applicable to 1803, but does not have a list of 1803 applications

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9c3129d-3c8d-b508-f298-3333499bb180
* Version Independent ID: 97b70720-82d8-60a4-3958-00ceed34aa1b
* Content: [How to keep apps removed from Windows 10 from returning during an update](https://docs.microsoft.com/en-us/windows/application-management/remove-provisioned-apps-during-update)
* Content Source: [windows/application-management/remove-provisioned-apps-during-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/remove-provisioned-apps-during-update.md)
* Service: **w10**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Heidilohr** [comment]
Thanks for your comment. You're right about the 1803 information is missing, but that's because we fixed the issue before version 1803, so this article technically only applies to versions 1703 and 1709. We're working on an update to make that clearer right now.

**Comment by Heidilohr** [comment]
You'll have to create your own registry keys when upgrading from 1607.
