### ISSUE TITLE
How do I disable the proxy configuration?!

### ISSUE THREAD

**Issue by Brz3z1nsky** [MicrosoftDocs/windows-itpro-docs#8883]
I set up a proxy address using the tips on this page, but now I need to disable it and I don't know how to do it.

Configurei um endereço de proxy usando as dicas desta página, mas agora preciso desabilitá-lo e não sei como fazer.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 83207fc9-2c91-eb07-4237-6bb1f42e3778
* Version Independent ID: 5db33cf3-2dcb-bb33-a252-3a13ca9737f9
* Content: [Definir configurações de conexão à Internet e proxy do dispositivo - Windows security](https://docs.microsoft.com/pt-br/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by VLG17** [comment]
@Brz3z1nsky If you used the GPO method, you just need to disable the GPOs which you have enabled previously. If you used the netsh command, you need to run netsh winhttp reset proxy which will give you :

> C:\Windows\system32>netsh winhttp reset proxy
>  Current WinHTTP proxy settings:
>      Direct access (no proxy server)
