### ISSUE TITLE
Only half done

### ISSUE THREAD

**Issue by daejsl** [MicrosoftDocs/windows-itpro-docs#8888]
The information given here is not covering all the needed steps. The zipfile is unpacked but nothing is mentioned of running the python file to create the onboarding file.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 623e0469-826c-5cdf-6dc4-67c80e232d0f
* Version Independent ID: 0f6c33bc-711a-84d6-01bb-04d13f5a85a2
* Content: [Deploy Microsoft Defender ATP for Linux with Ansible - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
@konstruktoid : Would you like to confirm, and maybe suggest something to describe what is needed?

Happy new year to you all! 🥳

**Comment by konstruktoid** [comment]
Hi @daejsl, https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md#create-ansible-yaml-files uses `unarchive` to unpack into the `/etc/opt/microsoft/mdatp` directory.

But you are correct. Both the Ansible and Puppet pages lacks information about running `MicrosoftDefenderATPOnboardingLinuxServer.py`

**Comment by konstruktoid** [comment]
Doesn't the tests work after running the playbook?

```sh
ansible -m shell -a 'mdatp connectivity test' all
ansible -m shell -a 'mdatp health' all
```

**Comment by VLG17** [comment]
@daejsl Are the steps described under the [Deployment section](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible#deployment) not what you are looking for? Would you add something to it?
