### ISSUE TITLE
systemd requirement not documented

### ISSUE THREAD

**Issue by christophjahn** [MicrosoftDocs/windows-itpro-docs#8894]
The page misses the fact that `systemd` is required for the pre-/post-install scripts to work. Debian 9 supports SystemV init in addition to `systemd` and that condition is not mentioned

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef3b1143-53ee-892c-59c8-5cfa12e017c2
* Version Independent ID: 29f6c231-15bd-296b-cca9-7ef6ba8192df
* Content: [Microsoft Defender ATP for Linux - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-linux)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-linux.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-linux.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by konstruktoid** [comment]
Hi @christophjahn, `systemd` is the default init system for Debian since Jessie (https://wiki.debian.org/systemd) and `systemd` itself uses the SystemV init scripts when there's no service file available, see https://www.freedesktop.org/software/systemd/man/systemd-sysv-generator.html.

Supporting multiple init systems without any actual benefits and where `systemd` is the default system for Debian (and many others), seems like unnecessary work.

**Comment by christophjahn** [comment]
I did not mean to imply that I want SysV init added. But the fact that `systemd` is required needs to be documented. I lost several hours on this subject and needed to look into the source code of the pre-/post-install scripts

On Debian 9 there are two other packages that needed installation for me, but I will open a separate ticket for these.

**Comment by illfated** [comment]
Fair enough, `systemd` is not even mentioned on the page, so perhaps we could open a PR to suggest a mention of that fact. Have you got any particular phrasing in mind? Suggestions are welcome.

**Comment by konstruktoid** [comment]
But if you follow the instructions on https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md (or the Ansible or Puppet instructions), isn't the correct services installed?

https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-linux.md#installation-instructions

**Comment by christophjahn** [comment]
> 
> 
> But if you follow the instructions on https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md (or the Ansible or Puppet instructions), isn't the correct services installed?

I am not sure what you mean. Could you please rephrase?

**Comment by christophjahn** [comment]
> 
> 
> Fair enough, `systemd` is not even mentioned on the page, so perhaps we could open a PR to suggest a mention of that fact. Have you got any particular phrasing in mind? Suggestions are welcome.

I would simply modify the Linux distros, that officially support SysV init and add " (only with systemd)". Example: "Debian 9 or higher (only with systemd)"

Alternatively, one could add a separate bullet point between "Supported Linux server distributions and versions:" and "Minimum kernel version 3.10.0-327", that says "- `systemd` must be installed"

**Comment by illfated** [comment]
> I am not sure what you mean. Could you please rephrase?

There are 3 documented install methods:
- Manual deployment: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually
- Deploy with Puppet: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-puppet
- Deploy using Ansible: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible

1. Which one of these have you tried?
2. What were your results?
3. Were the correct services installed?

**Comment by christophjahn** [comment]
Manual installation was attempted but failed entirely, since the pre- and post-install scripts of the Debian package contain invocations of `systemctl`, which obviously does not exist when SysV init is used.

**Comment by konstruktoid** [comment]
@christophjahn, how do you install a Debian 9 without systemd?

**Comment by illfated** [comment]
> @christophjahn, how do you install a Debian 9 without systemd?

I read his reply as suggesting that Debian 9 uses a replacement service for `systemd` — but I may easily have misunderstood it.

**Comment by christophjahn** [comment]
Debian 9 supports `systemd` (installed by default) or SysV init. The latter can be installed via `apt-get install sysvinit-core`, which replaces `systemd`. @konstruktoid , this should answer your question.

**Comment by konstruktoid** [comment]
Thanks @christophjahn, I didn't know about that package.
