### ISSUE TITLE
Add description for 0x800707E7

### ISSUE THREAD

**Issue by Sumitdhiman** [MicrosoftDocs/windows-itpro-docs#8898]
Often seen is error code 800707E7 during an upgrade. 

In the logs, the entry is something like this:

` pSPExecuteApply: Migration phase caught exception: Win32Exception: User profile suffix mismatch, upgrade cannot continue: The specified profile is intended for a device of a different type than the specified device. [0x000007E7]
`
`2020-12-29 07:49:01, Warning               SP     User profile suffix mismatch: upgrade asked for "XXXXX", actual suffix is: "XXXXX.000"`

The solution that works in many cases is to remove the Invalid profiles in the Registry. Not 100 percent applicable though.

https://superuser.com/questions/1318983/windows-10-update-1803-renamed-the-user-account-folder-with-000-suffix/1519965#comment2352352_1519965

I have a Setupact.log if someone wants to check.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 528014e0-02e5-2d77-a229-4895731bb872
* Version Independent ID: 4f46b620-e345-c9e4-70fa-ae4f5a8e48b9
* Content: [Resolution procedures - Windows IT Pro - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/upgrade/resolution-procedures)
* Content Source: [windows/deployment/upgrade/resolution-procedures.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/resolution-procedures.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Thank you for your contribution. Please be patient, your ticket will be looked into later by the MS Docs team.

(Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub. I don't know the topic well enough to give any feedback on the topic.)

**Comment by Reeced40** [comment]
@Sumitdhiman thank you for pointing this out and helping improve MS Docs. This is not a Microsoft Document so I cannot add it to the article, but would it help if I linked this article in the document to help other users?  https://answers.microsoft.com/windows/forum/all/update-problem-error-code-8007007e/a04549b2-a04c-4183-b386-df229e7c0669

**Comment by Sumitdhiman** [comment]
Thanks, Reeced40. I am getting a page not found on that Answers link. Can you please check the same?

**Comment by Reeced40** [comment]
@Sumitdhiman apologies, try this one https://answers.microsoft.com/en-us/windows/forum/all/update-problem-error-code-8007007e/a04549b2-a04c-4183-b386-df229e7c0669

**Comment by Sumitdhiman** [comment]
Thank you. Actually, the error code is 800707E7, running the error lookup tool says the following.

```
D:\Work>Err 800707E7
# No results found for hex 0x800707e7 / decimal -2147022873
# as an HRESULT: Severity: FAILURE (1), FACILITY_WIN32 (0x7), Code 0x7e7
# for hex 0x7e7 / decimal 2023
  ERROR_PROFILE_DOES_NOT_MATCH_DEVICE                            winerror.h
# The specified profile is intended for a device of a
# different type than the specified device.
# 1 matches found for "800707E7"
```

You may consider these(my experience says both answers are right)

[Win 7 to Win 10 upgrade error (0x800707E7 - 0x3000D)
](https://answers.microsoft.com/en-us/windows/forum/all/win-7-to-win-10-upgrade-error-0x800707e7-0x3000d/1273bc1e-8a04-44d4-a6b2-808c9feeb020
)

[Win 10 upgrade error: User profile suffix mismatch, 0x800707E7 - 0x3000D
](https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_install/win-10-upgrade-error-user-profile-suffix-mismatch/0f006733-2af5-4b42-a2d4-863fad05273d?page=3)

**Comment by Reeced40** [comment]
@nam31 merge is done so can be closed thank you.

**Comment by nam31** [comment]
Closing via #9096 
Thank you
