### ISSUE TITLE
Spelling in logon type CachedRemoteInteractive

### ISSUE THREAD

**Issue by LordMike** [MicrosoftDocs/windows-itpro-docs#8904]
The value `12` for the logon type is indicated as `CashedRemoteInteractive`. It should probably be `CachedRemoteInteractive`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aefbbdcc-606c-276c-47ee-fe2b2cb65c61
* Version Independent ID: e0979867-e6bc-7fb9-1279-646b319823b0
* Content: [4624(S) An account was successfully logged on. (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624)
* Content Source: [windows/security/threat-protection/auditing/event-4624.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4624.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@LordMike , thanks for pointing out. I already created PR to fix .

**Comment by illfated** [comment]
PR #8910 is ready for review, comments, and suggestions.

**Comment by nam31** [comment]
Closing via #8910
Thank you
