### ISSUE TITLE
Desktop app product name

### ISSUE THREAD

**Issue by nhoj01** [MicrosoftDocs/windows-itpro-docs#8907]
Hello:

The documentation is not clear about how you get the product name when adding a desktop apps. I assume that you get this information using the get-applockerfileinformation ps command, but want to make sure.

In addition the documentation says "Regarding to how to get the Product Name for the Apps you wish to Add, please reach out to our Windows Support Team to request the guidelines"

Please provide the details for getting the product name in this documentation.

Thank you.

**Comment by illfated** [comment]
Just to get a clearer picture of which part of the documentation you are referring to, do you have a link to the page that brought you here?

**Comment by nhoj01** [comment]
Sure thing, here is the link

https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure#add-desktop-apps

**Comment by illfated** [comment]
Thank you. The following is what your issue ticket would have looked like if you had pressed the button **[ This page ]** at the bottom:
***

[Enter feedback here]


---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ad3f92-24de-5eb5-8454-c72d85737183
* Version Independent ID: 900125eb-31ea-faf3-ac30-7c3d7b30f611
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure#add-desktop-apps)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Please be patient, since this repository is made to improve the documentation and not as much for direct user support.

Just in case you find that the wait for response posts from the MS Docs team takes more time than expected, please consider using the following forums to ask and see if the response is quicker:

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

**Comment by illfated** [comment]
PowerShell reference:

- https://docs.microsoft.com/powershell/module/applocker/get-applockerfileinformation?view=win10-ps
- https://docs.microsoft.com/powershell/module/applocker/?view=win10-ps

**Comment by VLG17** [comment]
@nhoj01 Correct, you get the Product Name by using the _Get-AppLockerFileInformation_ Powershell cmdlet.

**Comment by illfated** [comment]
@nhoj01 : If I read your initial ticket comment, it looks like you are asking for the addition of a better description with the command
```PowerShell
Get-AppLockerFileInformation
```
added, alongside a reference link to the PS page on how to use it.

**Comment by nhoj01** [comment]
I believe those updates should address my concerns.
