### ISSUE TITLE
Lack of Cost details on option 3

### ISSUE THREAD

**Issue by thomasforde** [MicrosoftDocs/windows-itpro-docs#8911]
[Enter feedback here]
Option 1 and Option 2 requires a separate license, so what does option 3 require? Is it included in something else, or just free of charge. lack of info so to what it option 3 can generate of cost..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4ed2b3-0390-4d53-2450-14995ee8b0b0
* Version Independent ID: 91b5bb3e-55d4-6a8e-c16d-094f15c28ee7
* Content: [Onboard Windows servers to the Microsoft Defender ATP service - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by thomasforde** [comment]
If you click the link above with the text "For a practical guidance on what needs to be in place for licensing and infrastructure, see Protecting Windows Servers with Defender for Endpoint." that points to here. https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/protecting-windows-server-with-windows-defender-atp/ba-p/267114#M128

You again get a answer that dictates the price as in option 1 and option 2. So again using links confused the reader as to what the actual cost might be, including me..

**Comment by illfated** [comment]
I see. There is a whole comment page full of discussions below the article, many of them (if not most of them) asking about the cost options.

**Comment by illfated** [comment]
Maybe I am thinking too far "out of the box" here, but it seems to me that the individual devices need separate licenses or a site license ( >50 seats) to be correctly licensed. Configuration of the management server does not appear to be dependent on licensing, the individual devices to be protected will depend on some form of license.

**Comment by adirdidi** [comment]
Addressed, you should see the change during noon PST tomorrow.
