### ISSUE TITLE
InternalDefinitionUpdateServer parameter for MDATP for Linux

### ISSUE THREAD

**Issue by churos78** [MicrosoftDocs/windows-itpro-docs#8913]
[linux preferences](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-preferences)
Can I somehow configure my own update URL or FIle share as with the Windows version? The linux version lacks a parameter for this in docs.  

Or how to create local mirror virus / malware definitions

**Comment by illfated** [comment]
When filled in correctly, your ticket would have included the following text (below the line):

***


[Enter feedback here]


---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44a290d4-3386-7f63-0324-4e6219b5dd24
* Version Independent ID: 286954a7-372e-314f-ad9f-d12f5f55b79e
* Content: [Set preferences for Microsoft Defender ATP for Linux - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-preferences)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-preferences.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-preferences.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
@konstruktoid : Maybe you would say that this is an easy question to answer, but I don't quite remember where to look.

**Comment by konstruktoid** [comment]
Hi @churos78, I don't thinks it's possible but someone from MSFT should verify.
`mdatp health` doesn't return that value by default and 
`mdatp config automatic-definitions-update` only accepts `enabled, disabled`.

**Comment by joinimran** [comment]
Hello @churos78 - Thank you for your query here, but this is not possible for MDATP for Linux. This is something that can be done using Windows. (https://docs.microsoft.com/powershell/module/defender/update-mpsignature?view=win10-ps) but you can request this feature using the User Voice Channel.

@e0i - FYI & A Please.
