### ISSUE TITLE
Microsoft Defender for Endpoint standalone missing

### ISSUE THREAD

**Issue by SilviaEid** [MicrosoftDocs/windows-itpro-docs#8917]
Hi,

in the below list of required licenses Microsoft Defender for Endpoint as a standalone product is missing. This is confusing for customers, because they think that they need one of the listed products as a prerequisite for Microsoft Defender for Endpoint:

Licensing requirements

Microsoft Defender for Endpoint requires one of the following Microsoft volume licensing offers:
•Windows 10 Enterprise E5
•Windows 10 Education A5
•Microsoft 365 E5 (M365 E5) which includes Windows 10 Enterprise E5
•Microsoft 365 E5 Security
•Microsoft 365 A5 (M365 A5)

Best regards,

Silvia Eid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by Reeced40** [comment]
@SilviaEid thank you for pointing this out. I see the article was updated this week and there is a note regarding licensing. Please check and let me know if you still think any more information must be added in.

**Comment by SilviaEid** [comment]
Hi Reece,

Thank you for your answer. I checked the article and it still does not say that customers can license Microsoft Defender for Endpoint (the client license, not the server license) as a standalone product. There are only the suite licenses that include the product, but not the standalone product. That is why we are often contacted by customers, because this makes them think that they need the suite licenses as a basis for the Microsoft Defender for Endpoint standalone license. So for example Windows 10 E5 + Microsoft Defender for Endpoint, since the article says Microsoft Defender for Endpoint requires one of the suites.

If I could change it I would simply add the Microsoft Defender for Endpoint standalone license to the list:

Licensing requirements
Microsoft Defender for Endpoint requires one of the following Microsoft volume licensing offers:

  *   Windows 10 Enterprise E5
  *   Windows 10 Education A5
  *   Microsoft 365 E5 (M365 E5) which includes Windows 10 Enterprise E5
  *   Microsoft 365 A5 (M365 A5)
  *   Microsoft 365 E5 Security
  *   Microsoft 365 A5 Security
Best regards,

Silvia Eid

**Comment by Reeced40** [comment]
@Reeced40 Hi there. I see you commented yesterday on the article requesting that I change the points in the table, but its seems to be reading exactly the same as you suggested. Please let me know if there's anything else you want me to add. Thanks.

**Comment by SilviaEid** [comment]
Hi Reece,

Thank you for your message. Sorry if my email was not 100% clear.

This is the list as it is now (yellow):

Licensing requirements
Microsoft Defender for Endpoint requires one of the following Microsoft volume licensing offers:

  *   Windows 10 Enterprise E5
  *   Windows 10 Education A5
  *   Microsoft 365 E5 (M365 E5) which includes Windows 10 Enterprise E5
  *   Microsoft 365 A5 (M365 A5)
  *   Microsoft 365 E5 Security
  *   Microsoft 365 A5 Security
This is the list how I would change it (green). I would add Microsoft Defender for Endpoint, since this is a valide license for the product as well and it is currently missing. (Therefore many customers think, they cannot order it without ordering one of the products that are currently in the list):

Licensing requirements
Microsoft Defender for Endpoint requires one of the following Microsoft volume licensing offers:

  *   Windows 10 Enterprise E5
  *   Windows 10 Education A5
  *   Microsoft 365 E5 (M365 E5) which includes Windows 10 Enterprise E5
  *   Microsoft 365 A5 (M365 A5)
  *   Microsoft 365 E5 Security
  *   Microsoft 365 A5 Security
  *   Microsoft Defender for Endpoint (standalone)
I hope that makes it clear.

Best regards,

Silvia Eid

**Comment by adirdidi** [comment]
The standalone license was added to the list.

**Comment by Reeced40** [comment]
@SilviaEid Thank you for clearing this up. It seems to have been fixed in the interim. Please confirm your side. Thanks. Love Shrek.

**Comment by SilviaEid** [comment]
Hi Reece,

Yes, I checked it today and it is fixed. Thanks a lot!

Best regards,

Silvia

**Comment by illfated** [comment]
@SilviaEid : Thank you for posting your feedback. Glad to see that it has been updated. 😃 🙂
