### ISSUE TITLE
Device encryption uses AES 128 algorithm  MBAM server cant change algoritmh for already encrypted drive

### ISSUE THREAD

**Issue by nascar3000** [MicrosoftDocs/windows-itpro-docs#8918]
Device encryption uses AES 128 algorithm and  MBAM server cant change algorithm for already encrypted drive
if Administrator sets up different algorithm than AES 128, MBAM policies cannot enforce to change current algorithm to requested one and client will be reported as non-compliant to MBAM server so it will reported as non-compliant in all reports. 
Please add a note about cannot change algorithm after device encrypted unless decrypt/encrypt device again. 

Thanks
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29116f85-264f-d031-be7b-e32a1816cd28
* Version Independent ID: 640478e6-a367-4e47-a177-3a10dd006d1c
* Content: [Overview of BitLocker Device Encryption in Windows 10 - Microsoft 365 Security](https://docs.microsoft.com/en-gb/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10#bitlocker-device-encryption)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
Closing via #8977 
Thanks
