### ISSUE TITLE
Premium Intune Account ?

### ISSUE THREAD

**Issue by edbakermct** [MicrosoftDocs/windows-itpro-docs#8919]
[Enter feedback here]
This text appears in the re requisites section

**A Premium Intune account** | This guide will describe how to obtain a free 30-day trial premium account that can be used to complete the lab.

No such thing - i think it may mean an intune license with a premium azure ad license as well..
-- | --

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc63299-cc1c-e031-deb7-915914b8f94e
* Version Independent ID: 356eaba5-16b0-952f-fc19-c8d5be5feb5f
* Content: [Demonstrate Autopilot deployment - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm)
* Content Source: [windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
(ref. #8939 )

**Comment by nam31** [comment]
Closing via #8939 
Thank you
