### ISSUE TITLE
Initiate live connection possible after Isolating machine

### ISSUE THREAD

**Issue by PawanGupta01** [MicrosoftDocs/windows-itpro-docs#8920]
After isolating machine, is it still possible to take remote of system by initiating live connection via security center?

**Comment by nam31** [comment]
@PawanGupta01 Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Can you please let us know the which part of the documentation you are referring to, or can you provide link to the page from which you were directed here?
Thanks

**Comment by PawanGupta01** [comment]
Mine is not an issue with the documentation but a question on below product
feature of Security Center
- Device Isolation
- Initiate Live connection

**Comment by nam31** [comment]
@PawanGupta01 
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)
Thank you.
