### ISSUE TITLE
PUA protection section

### ISSUE THREAD

**Issue by Longshot9** [MicrosoftDocs/windows-itpro-docs#8922]
Page says - 

Use Group Policy to configure PUA protection
On your Group Policy management computer, open the Group Policy Management Console, right-click the Group Policy Object you want to configure, and select Edit.

In the Group Policy Management Editor, go to Computer configuration and select Administrative templates.

Expand the tree to Windows Components > Microsoft Defender Antivirus.

Double-click Configure detection for potentially unwanted applications.

Select Enabled to enable PUA protection.

In Options, select Block to block potentially unwanted applications, or select Audit Mode to test how the setting will work in your environment. Select OK.

Deploy your Group Policy object as you usually do.

-------

"Microsoft Defender Antivirus" is not in there.  "Windows Defender Antivirus" is and there is no option that I can find for configure detection for pua.  Please update.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b27975a-fa49-d9cd-d500-792448c57f9e
* Version Independent ID: 21c3eb7b-065a-b68a-8a88-dfce45571b0d
* Content: [Block potentially unwanted applications with Microsoft Defender Antivirus - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/detect-block-potentially-unwanted-apps-microsoft-defender-antivirus#configure-pua-protection-in-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/detect-block-potentially-unwanted-apps-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/detect-block-potentially-unwanted-apps-microsoft-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@Longshot9 , This article describes correctly, but you need download and install  October  2020  admx templates for windows 10 20h2  from this  site
**https://www.microsoft.com/en-us/download/details.aspx?id=102157**

how to install and copy the updated templates to windows partition, post your question in  **https://answers.microsoft.com/en-us/**

**Comment by RAJU2529** [comment]
@Longshot9 , here is the screenshot of my windows 10 20h2
![upload1](https://user-images.githubusercontent.com/3296790/103964070-87be6e00-5180-11eb-88bc-297429425c12.JPG)

**Comment by Longshot9** [comment]
ah I see the issue now, i'm looking at the domain group policy.  is it in there?

**Comment by RAJU2529** [comment]
@Longshot9 . I think same policies can be used or modify for domain based devices.

**Comment by nam31** [comment]
Closing via #8931 
Thank you
