### ISSUE TITLE
Configure Devices with MDM policy

### ISSUE THREAD

**Issue by jandreacola** [MicrosoftDocs/windows-itpro-docs#8928]
Please add a section on how to Configure Devices with MDM policy.  In the Intune docs, there is a description on how to do it, but it refers to OMS (now Log Analytics) and there are no clear instructions on how to get the workspace ID https://docs.microsoft.com/en-us/mem/intune/protect/windows-update-compliance-reports#use-update-compliance 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 203edb5f-4274-eafb-323b-01fd55192c85
* Version Independent ID: 7a4beba8-b79b-92c3-59b9-b73c92947083
* Content: [Get started with Update Compliance - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-get-started)
* Content Source: [windows/deployment/update/update-compliance-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-get-started.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
I think a better approach would be to get the Intune docs to include this information, and then we can link to that. The reason is that if the info is in more than one place, it's harder to keep everything up to date and in sync.

@cinglis-msft can we follow up on that?

**Comment by e0i** [comment]
@cinglis-msft Please let us know whether we could help with this. Thanks.

**Comment by cinglis-msft** [comment]
I will make a note to work on this.

**Comment by e0i** [comment]
Fixed in https://github.com/MicrosoftDocs/windows-itpro-docs/commit/0a45c0a88462083eaaee98f8dc5a429dda727933
