### ISSUE TITLE
Add configuration option of maximumOnDemandScanThreads 

### ISSUE THREAD

**Issue by jmmowrer** [MicrosoftDocs/windows-itpro-docs#8929]
There is a configuration option called "maximumOnDemandScanThreads" which can be set to 1 to only use 1 CPU vs. 2 during scheduled scans.  Tudor has the deets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44a290d4-3386-7f63-0324-4e6219b5dd24
* Version Independent ID: 286954a7-372e-314f-ad9f-d12f5f55b79e
* Content: [Set preferences for Microsoft Defender ATP for Linux - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-preferences#sample-profile)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-preferences.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-preferences.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by konstruktoid** [comment]
Hi, @jmmowrer. Keeping track of configuration and preference changes is always messy.
Do you, or Tudor, have any information on how to completely dump the configuration of an available MDE on Linux?
