### ISSUE TITLE
Unable to filter machines vulnerabilities response using API using OData

### ISSUE THREAD

**Issue by arcastaneda** [MicrosoftDocs/windows-itpro-docs#8932]
Attempting to use the API to retrieve machinesVulnerabilities with the 'Critical' severity property using OData filter on the API. 

GET ../vulnerabilities/machinesVulnerabilities?$filter=severity+eq+'Critical'
expected response from the API is to only list vulnerability objects with Critical in the severity property only. However, I get a mixmatch of responses from low to high, no critical's. Putting in in other values such as 'Medium' or 'Low' change the response list, but is still inconsistent with expected output. Putting in 'Low' will still return a mix of all severities. 

The filter is error checking correctly though. Placing a query like "?$filter=severity+eq+'test'" returns an empty list (as expected, because no vulnerability has a "test" severity value). 

I believe this is an issue on the API backend processing the OData request. 

edit: link to article with the API https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/get-all-vulnerabilities-by-machines

**Comment by RAJU2529** [comment]
@arcastaneda  Which article are  you referring to

**Comment by arcastaneda** [comment]
@RAJU2529 This is the one I am working with: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/get-all-vulnerabilities-by-machines

It says "The OData $filter is supported on all properties". The filter **does** work as intended when I use it on fields like "Id", "cveID", or "MachineID", but it does **not** work properly when using it on the "severity" property.

**Comment by RAJU2529** [comment]
@arcastaneda , this article is beyond my knowledge, so wait for few days. let our expert's team will answer your questions

**Comment by Reeced40** [comment]
@arcastaneda thank you for pointing this out. Would you recommend I add a note to the article stipulating that the filter does not work properly when using it on the "severity" property?

**Comment by datesy12** [comment]
Is there any update on this???

**Comment by adirdidi** [comment]
The issue with the filter was fixed.
