### ISSUE TITLE
conflicting recommendations, likely typo

### ISSUE THREAD

**Issue by steve-pence** [MicrosoftDocs/windows-itpro-docs#8934]
[Enter feedback here] You say this. "Many devices now come with large internal drives. You can set Delivery Optimization to take better advantage of this space (especially if you have large numbers of devices) by changing the minimum file size to cache. If you have more than 30 devices in your local network or group, **change it from the default 50 MB to 10 MB.** If you have more than 100 devices (and are running Windows 10, version 1803 or later), set this value to 1 MB.

To do this in Group Policy, go to Configuration\Policies\Administrative Templates\Windows Components\Delivery Optimization and **set Minimum Peer Caching Content File Size to 100 (if you have more than 30 devices)** or 1 (if you have more than 100 devices)."

For the 30 device case, in the first paragraph, the recommendation is 10 MB, but in the second paragraph the instructions say set it to 100 MB.  This is seriously confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d745280-391c-4f6d-6a35-7125fa263548
* Version Independent ID: 0ccd8add-b5fb-469c-509e-e009c43a00ac
* Content: [Set up Delivery Optimization - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization-setup)
* Content Source: [windows/deployment/update/waas-delivery-optimization-setup.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-delivery-optimization-setup.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment]
@steve-pence , Thanks for pointing out, Article author will look in this issue.And it will be fixed very soon after testing and conformation

@nam31, Will you look in this issue #8934

**Comment by jaimeo** [comment]
@narkissit can you advise on this?

**Comment by narkissit** [comment]
That's a great find.
The 
sorry for the late response here, the notification from github went to my spam folder :( 
The correct value is 10MB so this sentence should be:
"set Minimum Peer Caching Content File Size to **10** (if you have more than 30 devices)"

**Comment by Kateyanne** [comment]
@steve-pence would you like to open a Pull Request to change the documentation?

**Comment by steve-pence** [comment]
I'm not familiar with this process of how the documentation is maintained.
I would certainly like to see it changed, but I don't want to be involved
in the details of how that happens. I just noticed the issue and reported
it.

Thanks,
Steve

**Comment by illfated** [comment]
Fair enough. I can easily do it, unless someone on the team simply wants to create a direct commit.

**Comment by Kateyanne** [comment]
Hi @illfated please create a PR. Thank you!

**Comment by illfated** [comment]
There you go. PR #9427 is available for review, comments, and suggestions. We may want to let @JohanFreelancer9 check for possible grammar improvements now that we have the opportunity.
