### ISSUE TITLE
clarify enterprise sku

### ISSUE THREAD

**Issue by rrsit** [MicrosoftDocs/windows-itpro-docs#8935]
based on the discussion here https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4025, the following confirmation from MSRC 61355 and the resulting PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8435 - 

could [this](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-requirements) page also be updated to specifically list "Windows 10 Enterprise" in the requirements list, to avoid confusion from Windows 10 Pro/Home? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0238a73f-da06-ae17-c61d-85ae54e0f7cb
* Version Independent ID: e5bb4a25-a7c3-3a16-bd95-d6f2513402e0
* Content: [Windows Defender Credential Guard Requirements (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-requirements)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-requirements.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@rrsit , Article will be updated soon after verifying and conformation from windows 10 enterprise edition experts

**Comment by illfated** [comment]
I think it could be as simple as opening a PR to make that change, because the PR content will be evaluated before merging.

**Comment by illfated** [comment]
(ref. #8937 )
