### ISSUE TITLE
Azure Gen2 VMs and Credential Guard

### ISSUE THREAD

**Issue by truekonrads** [MicrosoftDocs/windows-itpro-docs#8938]
The credential guard documentation says that it is unavailable on Azure and that future Gen2 VMs will support it. Gen2 is already available on Azure, does it mean that credential guard is supported or that the available Gen2 VMs are still not compatible? The documentation is unclear and requires a revision

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **v-tea**

**Comment by illfated** [comment]
(ref. #8967 )

**Comment by nam31** [comment]
Closing via #8967 
Thank you
