### ISSUE TITLE
Instructions for modifying WindowsPE do not work with latest deploument kit / winpe

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/windows-itpro-docs#8940]
firstly the path names have changed 
secondly none of the reagent files are store in the ADK or current winpe any more 

I have no clue how / when to get the reagent files for winpe from, please revise article verifying it works on win10 ADK and winpe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73c22f0-cb0d-e34b-29d8-06829b86784f
* Version Independent ID: 083115ed-f1be-e962-5b0e-5079dec37353
* Content: [MBR2GPT - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/mbr-to-gpt)
* Content Source: [windows/deployment/mbr-to-gpt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/mbr-to-gpt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@scyto , for your 1st question, could you tell me the files paths are changed?
for 2nd question, I conformed, article says correct, i conformed on my asus laptop.
i found three reagent files under windows 10 ADK 2004 with adds on PE.
to use reagents files, download and install windows 10 2004 and install windows 10 2004 adds on PE.
here is the proof

![Capture](https://user-images.githubusercontent.com/3296790/104185896-9edcb480-543b-11eb-8d0e-ac12b4de741c.JPG)

**Comment by Reeced40** [comment]
@scyto thank you for reaching out. Please confirm if you saw the above comment from @RAJU2529 and if you still need further assistance.

**Comment by scyto** [comment]
I was using windows insider winpe and ADK and I assure you the paths were fundamentally different with no reagent in any subdir (maybe this is why I never managed to make a working winpe disk either..

i just downloaded and installed the latest insider version and everything looks ok maybe there was a broken build, (wish i had taken screenshot) to prove it.

In terms of making this documentation better i found a far faster / better solution - just boot from a Windows Server or Windows ISO that matches the version of OS installed (in my case and insider version_ go to the recovery command line (instead of completing setup) and run mbr2gpt - you folks sure like making things way more complex than they need to be.....

**Comment by scyto** [comment]
oh on uninstalling the ADK and winpe, i think i see the issue, 

I assumed "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Setup\amd64\sources" was part of winpe - it isn't it is part of the ADK, when I installed i chose these options first time around (because an article I found telling me how to make a winpe image told me that's all i needed to get winpe working) 

![image](https://user-images.githubusercontent.com/11369180/106330381-fcdd0a80-6237-11eb-9848-b48be1a18913.png)

anyhoo my way is both faster and easier esp when running mulitple OS builds.

**Comment by Reeced40** [comment]
@scyto thanks again for pointing that out. I'll let the team have a look at it and update accordingly if necessary @greg-lindsay

**Comment by Reeced40** [comment]
@nam31 this can be closed thank you.
