### ISSUE TITLE
Where is the "Windows Sandbox" in the Windows Admin Center

### ISSUE THREAD

**Issue by Joe-houghton** [MicrosoftDocs/windows-itpro-docs#8941]
Watching the video, I see that they enable and Manage Windows Sandbox from the Admin Centre. I cannot find how to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c06f3ef-5946-862a-ae14-f897fdb518ca
* Version Independent ID: cd6a8b99-b1e9-dff5-f174-a15840b304f0
* Content: [Windows Sandbox - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@e0i , Will  you look into this issue #8941

**Comment by MaratMussabekov** [comment]
Hello @Joe-houghton ,
1. can you connect to this win 10 machine using Admin Center?
2. Do you have Windows Sandbox feature installed on windows 10 machine? (it must be installed prior to be enabled)
Thank you

**Comment by Joe-houghton** [comment]
Hello, @MaratMussabekov ,

Yes I have sandbox enabled on my PC and have Admin centre installed. I have been through all the options in admin centre but cannot see any called "Windows Sandbox" as per the video.

It is impossible to tell in the video where this feature is located.

**Comment by MaratMussabekov** [comment]
Hello @Joe-houghton ,
I tried to reproduce the situation:
1. installed sandbox on Win10 machine (running Windows 10 Pro 2004)
2. enabled powershell remoting
3. connect to it using Windows Admin Center

And I am not able to see Windows Sandbox as well. Other features working as expected.
**It is impossible to tell in the video where this feature is located.** - I believe there should be a separate section on the left pane

The possible reasons could be:
1. some additional extension should be installed on Windows Admin Center
2. Sandbox Management is a preview feature, not in general availability.

Dear @Dansimp, could you please advise? 
I am not sure whether this discussion is related to the topic of the article, or it is within Windows Admin Center documentation scope.

Thank you
