### ISSUE TITLE
We need to add clarification to the channel/version for the MDE repo.

### ISSUE THREAD

**Issue by YongRhee-MSFT** [MicrosoftDocs/windows-itpro-docs#8943]
[Enter feedback here]

Dear Sir or Madam,

/*
For example, if you are running CentOS 7 and wish to deploy MDATP for Linux from the insiders-fast channel:

Bash

Copy
sudo yum-config-manager --add-repo=https://packages.microsoft.com/config/centos/7/insiders-fast.repo
*/

After this portion, we should have the following note:
For production environments, use the Production channel:
sudo yum-config-manager --add-repo=https://packages.microsoft.com/config/centos/7/prod.repo

Note:  For any version of RHEL/CENTOS/Oracle 7.0 thru 7.10, please use 7 repo.

Thanking you in advance,
Yong Rhee [yongrhee@microsoft.com]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2197cba-30ac-1749-e25a-6f39c9ee9d20
* Version Independent ID: bcd14f13-ab59-8e69-5c83-42fee6e51f87
* Content: [Deploy Microsoft Defender ATP for Linux manually - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by konstruktoid** [comment]
Hi @YongRhee-MSFT, every example on that page is using `insiders-fast`. Perhaps we should replace that with the `prod` since MDE for Linux has gone GA.

**Comment by YongRhee-MSFT** [comment]
Hi Thomas,
I'm adding the feature PM's and Dev leads for MDE for Linux to see if they are on-board with replacing everything with 'prod' instead of just pointing out that for production deployments, customers should be using Prod.
Thanks,
Yong

**Comment by YongRhee-MSFT** [comment]
Totally agree, let’s point to production

Thanks,
Mati

From: Yong Rhee <yongrhee@microsoft.com>
Date: Wednesday, 13 January 2021 at 15:10
To: MicrosoftDocs/windows-itpro-docs <reply@reply.github.com>, MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>, Helen Allas <hallas@microsoft.com>, Tudor Dobrila <Tudor.Dobrila@microsoft.com>, Tomer Hevlin <Tomer.Hevlin@microsoft.com>, Mati Goldberg <Mati.Goldberg@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/windows-itpro-docs] We need to add clarification to the channel/version for the MDE repo. (#8943)
Hi Thomas,
I’m adding the feature PM’s and Dev leads for MDE for Linux to see if they are on-board with replacing everything with ‘prod’ instead of just pointing out that for production deployments, customers should be using Prod.
Thanks,
Yong

**Comment by YongRhee-MSFT** [comment]
Thx Mati.

Thomas, can we get that going?

Yong

**Comment by konstruktoid** [comment]
@YongRhee-MSFT, see https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8960

**Comment by YongRhee-MSFT** [comment]
Thx Thomas for your help.  Yong

**Comment by illfated** [comment]
This ticket will automatically close when PR #8960 gets merged.

**Comment by e0i** [comment]
#8960 had been closed.
