### ISSUE TITLE
Infinite Black Screen After Boot Up 

### ISSUE THREAD

**Issue by Sypticle** [MicrosoftDocs/windows-itpro-docs#895]
Im on a Alienware Aurora R6 Desktop and i updated to Windows 10 version 1803 and got a black screen in the middle of the screen after i restarted the pc so i restarted it again and i couldn't login to my PC because it was stuck on a infinite black screen right before the login screen,
it had a loading symbol there and i thought it was updating again so i left it for 30-60 minutes and never went away.
I have fixed it by getting into the BIOS and going back to the previous build, it would't let me into the BIOS but i just restarted 3 times in a row and it let me in (it doesnt let you get into BIOS by holding shift after booting the system up)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c880203c-6a5b-28e7-c74d-152890baa955
* Version Independent ID: 59c9eb13-dd44-358a-130d-ca1e020573ba
* Content: [What's new in Windows 10, version 1803](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1803)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1803.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1803.md)
* Service: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by andreabichsel** [comment]
Hi, the best way to get help is to contact Microsoft Support (https://support.microsoft.com/en-us/contactus/), or you can post in the Forum (https://social.technet.microsoft.com/Forums/windows/en-US/home?forum=win10itprogeneral).
