### ISSUE TITLE
Attack Surface Reduction Rules and Network Protection - List as not available in Passive Mode

### ISSUE THREAD

**Issue by jmmowrer** [MicrosoftDocs/windows-itpro-docs#8956]
Can we add notes about Attack Surface Reduction Rules and Network Protection require real-time protection in active mode?  This way customers know why they wouldn't see ASR Rule notifications if they are in Passive mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b88aee4-6727-fa98-1180-29708eea027e
* Version Independent ID: 374c671b-b21c-6eac-d887-892491357eb2
* Content: [Microsoft Defender Antivirus compatibility with other security products - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by MaratMussabekov** [comment]
Hello @jmmowrer ,
it is already mentioned in relevant articles - for [Attack Surface Reduction Rules](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction#requirements-for-warn-mode-to-work) and for [Network Protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/network-protection#requirements).
Thank you
