### ISSUE TITLE
Inconsistent use of 'Defender ATP' and 'Defender for Endpoint 

### ISSUE THREAD

**Issue by jguerin** [MicrosoftDocs/windows-itpro-docs#8961]
The contents page on the left refers to 'Defender ATP' whereas the pages have been updated to say 'Defender for Endpoint'. This occurs throughout the entire section, and is not limited to this single page.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0de0146-6f7c-ec51-005e-02b081dd53da
* Version Independent ID: 15288014-66db-7fe6-a39c-ce6c69651042
* Content: [Microsoft Defender ATP for non-Windows platforms - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/non-windows)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/non-windows.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/non-windows.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by adirdidi** [comment]
Updated across the entire TOC.

**Comment by illfated** [comment]
Nice. Thanks for the updates.
