### ISSUE TITLE
Memory Integrity documentation is not documentation

### ISSUE THREAD

**Issue by johnwbyrd** [MicrosoftDocs/windows-itpro-docs#8962]
The linked page is not documentation for the Memory Integrity feature.

This is an advertisement for the Memory Integrity feature.

Unless you can describe exactly how Memory Integrity works, how it is started, its means for protection, and what kinds of attacks it stops, then this is ordinary security by obscurity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f784502-84dc-1122-eab4-1eeeb08da046
* Version Independent ID: 21f210a7-4c38-8f62-0226-121562617fef
* Content: [Memory integrity - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/memory-integrity)
* Content Source: [windows/security/threat-protection/device-guard/memory-integrity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/device-guard/memory-integrity.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Hi @johnwbyrd, we’re working on revamping this page. In the meantime, please check out these two docs for more information related to memory integrity:

[Virtualization-based Security (VBS)](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-vbs) 
[Virtualization Based Security System Resource Protections](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/vbs-resource-protections)
