### ISSUE TITLE
How to add powershell scripts in full language mode with UMCI rule enabled in WDAC

### ISSUE THREAD

**Issue by andimoll** [MicrosoftDocs/windows-itpro-docs#8963]
I have tried to use signed powershell scripts in order to get full language mode and have added the signer to my WDAC policy.
However I still get a constrained language mode error. Is it even possible to use full language mode when I sign my scripts? I cannot find any information in your documentation on this here: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control

**Comment by MaratMussabekov** [comment]
Yes, it allows to run script in a full language mode. Are you sure you whitelisted the publisher correctly? 
For example, try to whitelist the rule using filepath rule instead of publisher rule - is it still blocked?
Thank you

**Comment by e0i** [comment]
Closing as the requested information already exists in the article.

**Comment by illfated** [comment]
Thanks for the closing comment. Appreciated.
