### ISSUE TITLE
Missing information on added support for office installations and updates

### ISSUE THREAD

**Issue by TheBaban** [MicrosoftDocs/windows-itpro-docs#8966]
Just above the Requirements section, it is state the following:
Support for new types of downloads:
Office installations and updates
Xbox game pass games
MSIX apps (HTTP downloads only)

But in the requirements section it is stated:
Types of download packages supported by Delivery Optimization:
Microsoft 365 Apps and updates = 1709 (for more information, see Delivery Optimization and Microsoft 365 Apps)

So 2 possibilities:
1: the added support for Office in win 10 v2004 (different from what was available from 1709) needs to be documented
or
2: remove "Office installations and updates" from the "Support for new types of downloads" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb67e518-6f60-23e0-2545-c2839e2b4159
* Version Independent ID: e9a31629-e3cb-0367-31c4-5661284d89bf
* Content: [Delivery Optimization for Windows 10 updates - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization)
* Content Source: [windows/deployment/update/waas-delivery-optimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-delivery-optimization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@narkissit can you advise on the correct edit to do here?

**Comment by RAJU2529** [comment]
@jaimeo . I will look into group policy editor

**Comment by RAJU2529** [comment]
in gpo, there is no options, so the article author needs to check the article again,

**Comment by jaimeo** [comment]
We need the SME, @narkissit to advise on what is most accurate.
