### ISSUE TITLE
Potential Article Correction

### ISSUE THREAD

**Issue by SAdamsCDFW** [MicrosoftDocs/windows-itpro-docs#8969]
Can you please review the Network Isolation Wildcard Settings section?  I think the following entry has an error:
Trust any domain that ends with the text contoso.com. Matching sites include spearphishingcontoso.com, contoso.com, and www.contoso.com.

I believe the spearphishingcontoso.com should actually be spearphishing.contoso.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41a8c802-79ca-1593-c045-2ed150e9ce40
* Version Independent ID: 3dabd613-2eee-7c65-6f30-6746c8fb5bdf
* Content: [Configure the Group Policy settings for Microsoft Defender Application Guard (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-application-guard/configure-md-app-guard)
* Content Source: [windows/security/threat-protection/microsoft-defender-application-guard/configure-md-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-application-guard/configure-md-app-guard.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
Fair point. Given that `contoso.com` [40.113.200.201] exists somewhere in the domain `ntwk.msn.net` and that www.contoso.com is translated via DNS to www.microsoft.com, it would be very likely that `spearphishingcontoso.com` should not exist. On the other hand, I would like to see confirmed the existence of `spearphishing.contoso.com` before recommending that change. The main difference is that the domain [contoso.com] already exists, so you could in theory have a virtually unlimited number of hostnames in that domain, one of them being named 'spearphishing'. (I know, some hostnames may just as easily be hidden for testing purposes, just like domain names being hidden / not advertised to the Internet.)

**File change history** (quite short, only 2 changes here on GitHub):
- https://github.com/MicrosoftDocs/windows-itpro-docs/commits/public/windows/security/threat-protection/microsoft-defender-application-guard/configure-md-app-guard.md

All feedback for the page **Configure Microsoft Defender Application Guard policy settings** :
- https://github.com/MicrosoftDocs/windows-itpro-docs/issues?utf8=%E2%9C%93&q=%223dabd613-2eee-7c65-6f30-6746c8fb5bdf%22&in=body
    - https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3720 GP setting "Prevent enterprise websites from loading non-enterprise content..." in 1809 does not match docs
    - https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4408 Provide better explanation for . (dot character) behavior in WDAG
    - https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4887 **Moved '.' syntax description to a separate table**
    - https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4668 Must have proxy servers as neutral for WDAG
    - https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5136 "Turn on Windows Defender Application Guard in Enterprise Mode" description is out of date

Please note in particular that @iadgovuser1 mentions the current name in https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4408#issuecomment-528979610 and that the same name (`spearphishingcontoso.com`) is mentioned by @jdgregson in https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4887#issuecomment-528992074 in his PR #4887 .

I would like to offer a Pull Request to have that name changed, but I can not get myself to do this before I see any evidence, or good reference validating that name correction.

**Comment by SAdamsCDFW** [comment]
I think my biggest concern is that if this is correct I could register customnamecontoso.com and circumvent the security in Defender Application Guard.  I would expect .contoso.com to not allow that as it would be a big security hole.

**Comment by jdgregson** [comment]
Hello @SAdamsCDFW,

As @illfated pointed out, this change was discussed issue #4408 and fixed in PR #4887.

To summarize, this was not a mistake and `spearphishingcontoso.com` should not be changed to `spearphishing.contoso.com`. Rather, this is a warning that `.contoso.com` is the equivalent of `*contoso.com`, or in English, "trust any domain name that ends in `contoso.com`".

This is most likely not what you want to use, since `.contoso.com` would include `notarealwebsitecontoso.com` since it ends in `contoso.com`. If you are wanting to allow contoso.com and all of its subdomains, you should use both `..contoso.com` and `contoso.com` instead.

**Comment by SAdamsCDFW** [comment]
I see what you guys are saying.  Thank you.

**Comment by illfated** [comment]
You are welcome. Thanks to both of you for the good follow-up. 👍🏻
