### ISSUE TITLE
0x801C03ED - No permission to Join Device to AAD

### ISSUE THREAD

**Issue by tonkzy** [MicrosoftDocs/windows-itpro-docs#8971]
Error code `0x801C03ED` can also be returned if the user does not have permission to join a device to AAD

Reference [AAD Device settings](https://portal.azure.com/#blade/Microsoft_AAD_Devices/DevicesMenuBlade/DeviceSettings/menuId/):
![image](https://user-images.githubusercontent.com/44408139/104748221-60037300-5749-11eb-8965-cd5b087dc71e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
Judging by the relevant table in the document page, it looks like the permission issue should be covered by a different error code:

| Hex        | Cause                                                              | Mitigation                       |
| :--------: | :----------------------------------------------------------------- | :------------------------------- |
|    ....    |                                                                    |                                  |
|    ....    |                                                                    |                                  |
|    ....    |                                                                    |                                  |
| 0x801C0003 | User is not authorized to enroll.                                  | Check if the user has permission to perform the operation​. |
| 0x801C03E9 | Server response message is invalid                                 | Sign out and then sign in again. |
| 0x801C03EA | Server failed to authorize user or device.                         | Check if the token is valid and user has permission to register Windows Hello for Business keys. |
| 0x801C03EB | Server response http status is not valid                           | Sign out and then sign in again. |
| 0x801C03EC | Unhandled exception from server.                                   | sign out and then sign in again. |
| 0x801C03ED | Multi-factor authentication is required for a 'ProvisionKey' operation, but was not performed. <br> -or- <br> Token was not found in the Authorization header. <br> -or- <br> Failed to read one or more objects. <br> -or- <br> The request sent to the server was invalid. | Sign out and then sign in again. If that doesn't resolve the issue, unjoin the device from Azure Active Directory (Azure AD) and rejoin.
| 0x801C03EE | Attestation failed.                                                | Sign out and then sign in again. |
|    ....    |                                                                    |                                  |
|    ....    |                                                                    |                                  |
|    ....    |                                                                    |                                  |

On the other hand, may I presume you have based your statement on rigorous testing and/or other online documentation?

**Comment by tonkzy** [comment]
This is based on extensive testing using Windows AutoPilot, users need to be given permission to Join devices to AAD, otherwise the error code `0x801C03ED` is returned.

Ideally there should be a different and explicit error code for this, but that would be over the windows team for further development.

**Comment by illfated** [comment]
Very well, thank you for the follow-up. I presume the MS Docs team tech writers will want to follow up on this as well.

Unless this gets too much delay, I will hold out for the tech writers to offer a suggested change, but feel free to suggest how it could be added correctly to the existing table.
