### ISSUE TITLE
Reference is broken

### ISSUE THREAD

**Issue by GreggRevak** [MicrosoftDocs/windows-itpro-docs#8972]
The page says "For more info about where this area is and how to decide on your protection level, see the Manage the WIP protection mode for your enterprise data section of the policy creation topics", however the section referred to ("Manage the WIP protection mode for your enterprise data") is not a link and cannot be found in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f018eba-b076-4010-5117-6b8195b5eb4d
* Version Independent ID: 70d25fee-acb2-faa4-9ddc-1fee3b54f033
* Content: [Mandatory tasks and settings required to turn on Windows Information Protection (WIP) (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/mandatory-settings-for-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/mandatory-settings-for-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/mandatory-settings-for-wip.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Could the following page link can be used there and still match the text? Or any other link from the related page groups on the left hand side?
- https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip
