### ISSUE TITLE
Hardware compatibility with M1

### ISSUE THREAD

**Issue by juhap** [MicrosoftDocs/windows-itpro-docs#8974]
Please include information on this page about the compatibility of Defender for Endpoint for Mac with the new M1 chip.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7a3b63b-afc5-1b25-3a30-e75c788f4a93
* Version Independent ID: 85498c85-fe13-fead-3bac-44db5614db0d
* Content: [Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-mac)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-mac.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-mac.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by juhap** [comment]
For reference, here's a comment from 30/12/2020 stating that M1 support is coming, but not yet there:
https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/microsoft-defender-atp-for-mac-is-moving-to-system-extensions/bc-p/2023952/highlight/true#M1048

**Comment by VLG17** [comment]
@juhap We will be able to add that information as soon as it's released. Currently waiting for it to be released according the the comments you've shared.

**Comment by CsbGymGSju** [comment]
Anything new?  This is a huge problem.
