### ISSUE TITLE
Enterprise Vs Education

### ISSUE THREAD

**Issue by ittechandres** [MicrosoftDocs/windows-itpro-docs#8976]
Wondering if this is off but at the bottom where the Win 10 upgrade paths are, it has a (D)owngrade mark under the Enterprise column for the Education row of Windows 10.

I just wanted to know if this is accurate and Enterprise is actually considered a downgrade from the Education edition of Windows.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08436cb0-d0b6-0961-9e57-291b24d73644
* Version Independent ID: 36264f52-d3ac-4e50-f8e8-b09d6b210490
* Content: [Windows 10 upgrade paths (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-upgrade-paths)
* Content Source: [windows/deployment/upgrade/windows-10-upgrade-paths.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/windows-10-upgrade-paths.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
It is neither an upgrade nor a downgrade, but functionally since your user data is not maintained it behaves the same as a downgrade.

**Comment by illfated** [comment]
Interesting viewpoint, I had forgotten to look at it that way.

**Comment by ittechandres** [comment]
That is a very interesting point. Currently studying for the MD-100 and
101T so I will keep that in mind.

I appreciate the knowledge.

**Comment by greg-lindsay** [comment]
Also have a look here in this chart Education is viewed as an upgrade from Enterprise (Enterprise > Education). What I'm saying is there are no feature advantages to Education vs. Enterprise AFAIK.

https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-edition-upgrades
