### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nicolonsky** [MicrosoftDocs/windows-itpro-docs#898]
Please provide some documentation on how to configure the restricted groups. I found some information accessing the CIM Policy CSP namespace but an official documentation would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0c28c15-f0be-d732-4d9e-cf5df5e64e8b
* Version Independent ID: 17eba45f-d200-e656-42b9-e1a512931eea
* Content: [Policy CSP - RestrictedGroups](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-restrictedgroups)
* Content Source: [windows/client-management/mdm/policy-csp-restrictedgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-restrictedgroups.md)
* Service: **w10**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by nenonix** [comment]
@nicolonsky Thank you for the helpful contribution. Can you share what you have discovered and work with me to suggest what should be included so we can submit a change to the content? Thank you.

**Comment by mypil** [comment]
@nicolonsky - We would like to follow up on this. Can you please respond to the query of nenonix? Thanks.

**Comment by mypil** [comment]
@nicolonsky - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
