### ISSUE TITLE
Make page title consistent with Navigation

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#8980]
This page title does not match the left side navigation which is confusing. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4a20ccd-c954-e4f7-07ca-eba122d01340
* Version Independent ID: ee4176d5-3fe6-f65b-6a78-a06f94ae73c0
* Content: [Onboarding using Microsoft Intune - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/onboarding-endpoint-manager)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/onboarding-endpoint-manager.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/onboarding-endpoint-manager.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by adirdidi** [comment]
Fixed.

**Comment by DeanGross** [comment]
Thanks, but I'm not seeing the change. Does it take a while to become visible?

**Comment by adirdidi** [comment]
Yes, it will be updated on a later publication.

**Comment by illfated** [comment]
@DeanGross : Feel free to post back if you don't see the published change in a week's time or so.

**Comment by adirdidi** [comment]
Week? It will be live around 11 AM PST.

**Comment by illfated** [comment]
Thank you. Sorry for estimating the time incorrectly.

**Comment by adirdidi** [comment]
No worries. BTW - it's already live.
