### ISSUE TITLE
Make page title consistent with navigation

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#8981]
This page title does not match the left side navigation which is confusing. 
---

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24957830-5519-a9e9-d7c6-81283f1591ea
* Version Independent ID: 0200f46c-1346-6ff1-6b68-4ccd93a10508
* Content: [Onboarding using Microsoft Endpoint Manager - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/onboarding-endpoint-configuration-manager)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/onboarding-endpoint-configuration-manager.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/onboarding-endpoint-configuration-manager.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by adirdidi** [comment]
Fixed.
