### ISSUE TITLE
Policy path in tables needs updating

### ISSUE THREAD

**Issue by pnwnightowl** [MicrosoftDocs/windows-itpro-docs#8982]
In the tables for policies that reference build 1607 or greater, the path to the policy needs to be updated.  Currently, the last folder branch name is "Defer Windows Update", when in fact it needs to be "Windows Update for Business".

For example, in the Release Branch Policies table, the entry for GPO for Windows 10, version 1607 or later:
Computer Configuration > Administrative Templates > Windows Components > Windows Update > **Defer Windows Updates** > Select when Feature Updates are received

Should be:
Computer Configuration > Administrative Templates > Windows Components > Windows Update > **Windows Update for Business** > Select when Feature Updates are received

If you take a look at the section named: Configure when devices receive Windows Insider Preview builds
You are referencing the correct location in the first bullet point.

If you take a look in the latest WindowsUpdate.adml you will see the reference mapping:

    <string id="DeferUpdateCat">Windows Update for Business</string>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1684b30a-3187-85ce-0cf7-10d1b8298b7f
* Version Independent ID: 9b7170fc-2b39-8e46-7898-894a45de8623
* Content: [Configure Windows Update for Business (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-configure-wufb)
* Content Source: [windows/deployment/update/waas-configure-wufb.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-configure-wufb.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment]
@pnwnightowl . thanks for pointing out. I look into this issue.

**Comment by RAJU2529** [comment]
@pnwnightowl . I checked the article, most of the policy should be update. For 20H2  different policies are added in templates.

**Comment by pnwnightowl** [comment]
I don’t see any updates to the doc, unless there are pending publish state that I cannot see.  I attached a screen shot of the Windows Update GPO while using the 20H2 ADMX and you can see there is only a Windows Update for Business folder; no Defer Windows Update folder as indicated in the doc.

[cid:image002.png@01D6EF29.C1421780]

[cid:image004.png@01D6EF29.C1421780]

**Comment by nam31** [comment]
Closing via #9413 
Thank you
