### ISSUE TITLE
Contradiction about edition information for "Network Protection" prerequisites

### ISSUE THREAD

**Issue by hidemaruki** [MicrosoftDocs/windows-itpro-docs#8983]
[フィードバックをこちらに入力してください]
Contradiction about edition information for "Network Protection" prerequisites

Regarding the prerequisites for [Network Protection], the first URL below says 
"Windows 10 Pro, Enterprise E3, E5", but the second URL says " Windows 10 Enterprise edition, version 1709 or higher (also known as the Fall Creators Update)".  

If [Network Protection] is also available on "Windows 10 Pro", please correct the article.

https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-atp/network-protection
https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-np

[ネットワーク保護]に関する前提条件のEditionの情報に矛盾がある
[ネットワーク保護]の前提条件に関して、下記の1つ目のURLでは、「Windows 10 Pro、Enterprise E3、E5」とあるが、２つ目のURLでは、「Windows 10 Enterprise edition、バージョン1709以上 (秋の作成者の更新とも呼ばれます)」と記載がある。[ネットワーク保護]は「Windows 10 Pro」でも利用できるのであれば記事を訂正頂きたい。
https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-atp/network-protection
https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-np
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 911c3faa-a7a0-2085-15d2-bf4717506e87
* Version Independent ID: 2518f6db-c21c-433e-7e24-21a4260a1158
* Content: [ネットワーク保護に関する問題をトラブルシューティングする - Windows security](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-np)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/troubleshoot-np.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-np.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
(translation to English, using translator engine)

**Inconsistent Edition information in Prerequisites for Network Protection**

[Enter your feedback here]
Regarding the prerequisites for [Network Protection], the first URL below says "Windows 10 Pro, Enterprise E3, E5", but the second URL says "**Windows 10 Enterprise edition, version 1709 or higher (Autumn).** Also known as Creators Update) ".
If [Network Protection] is also available on "Windows 10 Pro", please correct the article.

***

The first document page should also say only "Windows 10 Enterprise edition" (or maybe "Windows 10 Enterprise E3, E5").
