### ISSUE TITLE
 About the support edition of "Attack surface reduction"

### ISSUE THREAD

**Issue by hidemaruki** [MicrosoftDocs/windows-itpro-docs#8984]
[フィードバックをこちらに入力してください]
Although it is written that "Attack surface reduction" can also be used with a "Pro" license,
In the case of "E3 License", it is written that it can be operated using "Event Viewer".
Isn't it correct for "Pro and E3 License"?
If not, please remove the "Pro" notation from support.
------------------------------------------------------------
Attack surface reduction features across Windows versions
You can set attack surface reduction rules for devices running any of the following editions and versions of Windows:

Windows 10 Pro, version 1709 or later
Windows 10 Enterprise, version 1709 or later
Windows Server, version 1803 (Semi-Annual Channel) or later
Windows Server 2019
To use the entire feature-set of attack surface reduction rules, you need a Windows 10 Enterprise license. With a Windows E5 license, you get advanced management capabilities including monitoring, analytics, and workflows available in Defender for Endpoint, as well as reporting and configuration capabilities in the Microsoft 365 security center. These advanced capabilities aren't available with an E3 license, but you can still use Event Viewer to review attack surface reduction rule events.
------------------------------------------------------------
https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5d747289-63b2-f71a-b40c-31b52982215c
* Version Independent ID: b52f6593-03f2-aa57-ec0e-eaef560dcaf0
* Content: [攻撃表面の縮小ルールを使用してマルウェアの感染を防止する - Windows security](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by MaratMussabekov** [comment]
Hello @hidemaruki ,
It works following way:
1. Windows 10 pro and Windows Server do not support entire feature set of ASR ([Source](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction-faq#do-i-need-to-have-an-enterprise-license-to-run-asr-rules))
2. Windows 10 Enterprise and Windows 10 Enterprise E3 support all features, but doesn't support advanced management capabilities
3. Windows 10 Enterprise E5 supports everything

The paragraph you are talking about, is related to the statements 2 and 3 above, it is not related to Windows 10 pro.

Dear @denisebmsft , could you please confirm?

Thank you

**Comment by hidemaruki** [comment]
Hello, @MaratMussabekov ,
Thank you for reply.

You mean "Attack Surface Reduction" need "Windows 10 Enterprise" lisence only.

So I think I can apply Attack surface reduction to "Windows 10 Pro" without upgrading actual OS to "Windows 10 Enterprise E3 or E5" if only I have "Windows 10 Enterprise E3 or E5" license.
I think I can apply Attack surface reduction to "Windows Server 2019" if only I have "Windows 10 Enterprise E3 or E5" license, also.

Dose it makes sense?
If my understanding is correct, I completely agree with your text.
