### ISSUE TITLE
Brown,s Hub Service

### ISSUE THREAD

**Issue by bdan9559** [MicrosoftDocs/windows-itpro-docs#8985]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7b0bed0-d344-9e32-f789-ddebb0309ecf
* Version Independent ID: 6c821f59-d507-df49-19c7-9a98dd162bf0
* Content: [Windows 10, version 1709 and newer optional diagnostic data (Windows 10) - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/windows-diagnostic-data?source=docs)
* Content Source: [windows/privacy/windows-diagnostic-data.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/windows-diagnostic-data.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
@bdan9559 : Did you intend to write anything here, or is this just a test?
