### ISSUE TITLE
does the connector need to be installed on all Azure ADJ machines or just one

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/windows-itpro-docs#8987]
Confused by this step https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert#download-intune-certificate-connector

Does this need to be done on client machine or EVERY client machine.
If the latter why can't this be pushed automatically from Intune - installing manually on every machine seems odd.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f709fd4-0b5d-b238-4060-222d550cd538
* Version Independent ID: fb3f29da-2236-c47d-6bea-8efbcec8d7d3
* Content: [Using Certificates for AADJ On-premises Single-sign On single sign-on - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by Reeced40** [comment]
@scyto thank you for reaching out and helping improve MS Docs. It is necessary to use application proxy as its Azure AD feature that enables users to access on-premises web applications from a remote client.

**Comment by scyto** [comment]
Thanks, my point is I think there are other ways to do that too - like exposing  the device enrollment endpoint directly to the internet via say an Ngix reverse proxy.

I am not saying one has to document how to do that, rather a) confirm that the requirement is that device enrollment endpoint is required to be accessible from the internet and b)it is ok for customers do that in other ways c)that azure app proxy is great if you don't have an existing proxy like say nginx (which I have and would take me 30 seconds to setup vs huge amount of work for the azure app proxy).

Your call.

**Comment by Reeced40** [comment]
@scyto thank you for pointing this out. We are continuously improving the doc set here, but for now we will leave the documentation as is and the team will update when necessary. Thanks again.

**Comment by Reeced40** [comment]
@nam31 this can be closed thank you.

**Comment by nam31** [comment]
@scyto Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
