### ISSUE TITLE
Do i have to use Azure Application proxy

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/windows-itpro-docs#8988]
Do i need to follow the the Azure Application proxy instructions?
If I have an existing reverse proxy (like nginx) can I use that instead?

https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert#create-a-web-application-proxy-for-the-internal-ndes-url

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f709fd4-0b5d-b238-4060-222d550cd538
* Version Independent ID: fb3f29da-2236-c47d-6bea-8efbcec8d7d3
* Content: [Using Certificates for AADJ On-premises Single-sign On single sign-on - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert#download-intune-certificate-connector)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by joinimran** [comment]
Hello @Scyto, thank you for your query. And yes it is necessary to use application proxy as its Azure AD feature that enables users to access on-premises web applications from a remote client.

I have also created a PR to link this to the more information page at MS Docs.

Thanks.
Imran.

**Comment by scyto** [comment]
Pretty certain the requirement is to access the app. There are many ways to do that, AAD proxy is but one.
