### ISSUE TITLE
The description problem of proxy server

### ISSUE THREAD

**Issue by BLTTEST** [MicrosoftDocs/windows-itpro-docs#8989]
Hi Teams,

The description of "proxy server" is: Specify the proxy servers your devices will go through to reach your cloud resources. Using this server type indicates that the cloud resources you’re connecting to are enterprise resources.

The description of "internal proxy server": This list shouldn’t include any servers listed in your Proxy servers list. Proxy servers must be used only for non-WIP-protected (non-enterprise) traffic. Separate multiple resources with the ";" delimiter.

I'm not sure if it's a conflict?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ad3f92-24de-5eb5-8454-c72d85737183
* Version Independent ID: 900125eb-31ea-faf3-ac30-7c3d7b30f611
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure#manage-the-wip-protection-mode-for-your-enterprise-data)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello BLTTEST, thank you for posting your query. Please note that there is a difference in both and that is reflected in the description of Proxy Server and Internal Proxy Server. If there is any suggestion, please feel free to let me know.

Thanks.
Imran.

**Comment by BLTTEST** [comment]
Hi @joinimran 

I read it again. "Proxy servers" and "Internal proxy servers" are both used to indicate enterprise resources, but "proxy server" traffic won't be protected by WIP. Do I understand this correctly？

Another thing is Intune "Cloud resources" denied value format "contoso.sharepoint.com,|contoso.visualstudio.com,". Intune tips say you should use "contoso.sharepoint.com|contoso.visualstudio.com". Can you kindly confirm this?

**Comment by nam31** [comment]
Closing via #9042 
Thank you
