### ISSUE TITLE
<code> html tag not wrapping with smaller viewports

### ISSUE THREAD

**Issue by georgeescott** [MicrosoftDocs/windows-itpro-docs#899]
Viewing this page on an iPhone or device with a smaller viewport (w: ~500px) the `<code>` html tag and text within it doesn't wrap with the page and overflows cutting off the content.

An example on this specific page is: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.BingWeather_8wekyb3d8 bbwe]` that gets cut off.

Either adding the CSS `word-break: break-word` or `max-width: 100%; overflow-wrap: break-word;` to the `code` tag resolves the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9c3129d-3c8d-b508-f298-3333499bb180
* Version Independent ID: 97b70720-82d8-60a4-3958-00ceed34aa1b
* Content: [How to keep apps removed from Windows 10 from returning during an update](https://docs.microsoft.com/en-us/windows/application-management/remove-provisioned-apps-during-update)
* Content Source: [windows/application-management/remove-provisioned-apps-during-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/remove-provisioned-apps-during-update.md)
* Service: **w10**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by georgeescott** [comment]
I've also just noticed that `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.BingWeather_8wekyb3d8 bbwe]` in [windows/application-management/remove-provisioned-apps-during-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/remove-provisioned-apps-during-update.md) has a space in `Microsoft.BingWeather_8wekyb3d8 bbwe` that it shouldn't.

**Comment by Heidilohr** [comment]
Hi, George. That space was actually a forced line break to try to keep the code from going off the page. We're working on an update to fix that as we speak.
