### ISSUE TITLE
Registry change also required?

### ISSUE THREAD

**Issue by rcmpgi** [MicrosoftDocs/windows-itpro-docs#8992]
I set this audit policy on Windows 10 1607 LTSB and nothing was logged.
Apparently the following registry value also needs to be configured on most versions of Windows 10:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Storage\HotPlugSecureOpen = 1 (REG_DWORD)
Can the page be updated to add this crucial additional step - or the products affected be fixed to make this unnecessary?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42b3c94c-914d-f3d9-9869-85b0e03972fc
* Version Independent ID: 9120cada-d893-3f79-6b37-c92777212384
* Content: [Monitor the use of removable storage devices (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/monitor-the-use-of-removable-storage-devices)
* Content Source: [windows/security/threat-protection/auditing/monitor-the-use-of-removable-storage-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/monitor-the-use-of-removable-storage-devices.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
Just now I tested on windows 10 20h2 build no 19042.746
I conformed without Adding registry key, event audit logs are created successfully with event ID
 4663.
so I think adding Registry key is not required for  20H2 edition.

**Comment by MaratMussabekov** [comment]
Hello,
checked on several different builds of Windows 10.
Some of them doesn't have HotPlugSecureOpen registry key at all, and removable storage audit works without any additional actions.
Other builds have HotPlugSecureOpen set to 0. On these computers, removable storage audit started logging the events only after setting the key to 1, or after removing of it.

I believe it worth to add some note to the article, like:

> [!NOTE] 
> Some versions of Windows 10 may require registry key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Storage\HotPlugSecureOpen to be set to 1 to start logging the removable storage audit events.

Dear @dansimp, could you please advise?

Thank you

**Comment by RAJU2529** [comment]
@Dansimp . after reading feedback from @MaratMussabekov , I agree with his point.

**Comment by dcjacob1999** [comment]
The registry change starts the logging of Removable Storage Auditing events. I recommend this step be added to the MSDoc instructions
