### ISSUE TITLE
screenshots are poor quality and unreadable

### ISSUE THREAD

**Issue by strausy** [MicrosoftDocs/windows-itpro-docs#8993]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f791dc07-b2c6-3003-a829-cd1ec03a2918
* Version Independent ID: 2c53adbc-600f-60b2-e8b2-b907335f4862
* Content: [Set up the Microsoft Defender ATP for macOS policies in Jamf Pro - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@strausy i agree , in some screenshots, its difficult to read, i  took that pic, i  made to visible, i will add that pic here , will you able to read  the sentences inside the screenshot
![onboarding-macos01](https://user-images.githubusercontent.com/3296790/105358981-df4ae800-5c1c-11eb-8369-4be60176d9ce.png)

**Comment by strausy** [comment]
Much better. The documentation is great (albeit time consuming for JAMF MDM). The screenshots being readable would make it that much better. 

Thank you!

**Comment by RAJU2529** [comment]
@strausy , Thanks for replying, yes 
![onboarding-macos02](https://user-images.githubusercontent.com/3296790/105361847-225a8a80-5c20-11eb-9d35-12bac08783a6.png)

**Comment by joinimran** [comment]
Hello @strausy - Thank you for your feedback. I have reviewed your request and found that all of the images show in the document  are full-size images. These are compacted  as required for the page. If you right-click on the image and open the image required in a new tab will show you the full screen image with all the required details. 

Thanks
Imran.

@nam31 - FYI Please.

**Comment by nam31** [comment]
@strausy Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
