### ISSUE TITLE
Certificate indicators based on having the actual certificate is not optimal.  We should be able to just imput the certificate parameters. 

### ISSUE THREAD

**Issue by waydaws** [MicrosoftDocs/windows-itpro-docs#8994]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e56d5e-bd24-b23a-ab4e-2a1253e09d14
* Version Independent ID: 93ff9b4e-f401-3d75-965e-106b7ce646c3
* Content: [Create indicators based on certificates - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/indicator-certificates)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/indicator-certificates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/indicator-certificates.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by joinimran** [comment]
Hello @waydaws - Thank you for your feedback. Can you please explain in a little more detail what parameters are required to be added in the document so that I can look into this?

Thanks
Imran.

**Comment by waydaws** [comment]
@jonimran.  Yes, for example the Signer Distinguished Name, as they're sometimes specified in IOCs (and sometimes better than hashes for controlling what's allowed or not).

**Comment by joinimran** [comment]
Thanks for your reply @waydaws - I am sorry I didn't get your point. Can you please let me know which part of the document needs to change/updated with what information?

**Comment by waydaws** [comment]
Ah, I see.  It's not the document.  I was trying to comment on product itself.

**Comment by nam31** [comment]
Thank you for providing feedback.
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
Thank you for your contribution to make the docs better! Much appreciated!
