### ISSUE TITLE
Fix description of devicelock/maxinactivitytimedevicelock 

### ISSUE THREAD

**Issue by Alex-Saad** [MicrosoftDocs/windows-itpro-docs#8995]
In the article it is written that the Integer for devicelock/maxinactivitytimedevicelock should be set in minutes, but this is not correct. The values are in seconds. This has been tested and caused mass dissatisfaction as people's PCs were locked after 5 seconds of inactivity! 

I had to search for another article to confirm that: https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-asprov/7dcdd2c3-43ca-4425-b8d4-443b1d2c0638

Please fix ASAP!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a3dde0-fe8d-25d3-3a7e-83acf9c394c6
* Version Independent ID: 2c654710-0be1-1d50-9972-6ccf9d072bf1
* Content: [Policy CSP - DeviceLock - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-devicelock#devicelock-maxinactivitytimedevicelock)
* Content Source: [windows/client-management/mdm/policy-csp-devicelock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-devicelock.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@Alex-Saad , Thanks for pointing out, I am fixing now

**Comment by illfated** [comment]
(ref. #8997 )

**Comment by nam31** [comment]
Closing via #8997 
Thank you
