### ISSUE TITLE
Dell BIOS tool change

### ISSUE THREAD

**Issue by Sup3rlativ3** [MicrosoftDocs/windows-itpro-docs#900]
Dell CCTK is now Dell Command | Configure and is a part of the Dell Client Command Suite. The new package can be found at the link below.

http://en.community.dell.com/techcenter/enterprise-client/w/wiki/7532.dell-command-configure

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c3977f-3b78-1d8e-ad8f-50538ad1934f
* Version Independent ID: 46b9ab6d-7a30-4dab-70fa-e1c97cc3ec3e
* Content: [Set up MDT for BitLocker (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/set-up-mdt-for-bitlocker)
* Content Source: [windows/deployment/deploy-windows-mdt/set-up-mdt-for-bitlocker.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/set-up-mdt-for-bitlocker.md)
* Service: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by greg-lindsay** [comment]
Sorry for getting to this very late. I've updated the doc with the current tool link.
