### ISSUE TITLE
The meaning of what was said is lost

### ISSUE THREAD

**Issue by Alaladdin** [MicrosoftDocs/windows-itpro-docs#9000]
RU: Numerous mistakes in the endings of words, duplicate words. The meaning of what was said is lost

![image](https://user-images.githubusercontent.com/22962274/105393078-fdb8df80-5c2c-11eb-9d82-5e6f7158e81e.png)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 3621dedd-460e-2afd-e6d6-ac7a5d0d6911
* Version Independent ID: 298b96a7-17d2-6c1f-a2d1-81c24ad80e81
* Content: [Настройка журнала Защитник Windows брандмауэра (Windows 10) - Windows security](https://docs.microsoft.com/ru-ru/windows/security/threat-protection/windows-firewall/configure-the-windows-firewall-log)
* Content Source: [windows/security/threat-protection/windows-firewall/configure-the-windows-firewall-log.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/configure-the-windows-firewall-log.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
@TinaMcN can you please take a look at this issue?

**Comment by TinaMcN** [comment]
@Alaladdin thank you very much for reporting this.  It appears to be a problem with our machine translation tool.  I have reported it to our MT tool team and hope to have it fixed soon.

**Comment by illfated** [comment]
We may want to keep this ticket open to track the status of the Machine Translation issue. Otherwise, it would feel like no need to check back for a status.

**Comment by TinaMcN** [comment]
@Alaladdin this article has now been translated by a human.  Can you please confirm if it's fixed now?

**Comment by Alaladdin** [comment]
yes, now everything is fine

**Comment by TinaMcN** [comment]
@Alaladdin thank you for confirming and thanks again for reporting the issue.  Let me know if you notice any other issues in the Russian translations.   Can you please close this issue now?
