### ISSUE TITLE
Add JAMF instructions if possible

### ISSUE THREAD

**Issue by strausy** [MicrosoftDocs/windows-itpro-docs#9001]
Many of the Microsoft Defender for Endpoint for Mac pages include very detailed instructions for configuring it using JAMF or Intune. This page is lacking the JAMF specifics needed to make it easier to understand, specifically the Preference Domain The name of the preference domain (com.company.application) needed for plist files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 870e6699-64bf-a816-ad17-1f3f1b9d229d
* Version Independent ID: f51f0314-5ace-5041-002f-3ad464240b62
* Content: [How to schedule scans with MDATP for macOS - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-schedule-scan-atp)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-schedule-scan-atp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-schedule-scan-atp.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello, @strausy This feature is not yet available in JAMF. See the open thread at JAMF community portal at https://www.jamf.com/jamf-nation/discussions/38085/microsoft-defender-atp-quick-full-scan-config-profile
I would suggest you open a feature request for this.

@e0i FYI & A.
