### ISSUE TITLE
Lernen Ohne Limit

### ISSUE THREAD

**Issue by c3333** [MicrosoftDocs/windows-itpro-docs#9003]
Lernen  ohne  Limit 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75240ad-db64-8d89-4d61-f789fd632e04
* Version Independent ID: f76f946c-7e33-5041-f442-92bd38886d85
* Content: [Assign Security Group Filters to the GPO (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/assign-security-group-filters-to-the-gpo)
* Content Source: [windows/security/threat-protection/windows-firewall/assign-security-group-filters-to-the-gpo.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/assign-security-group-filters-to-the-gpo.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Closing as missing feedback.

**Comment by illfated** [comment]
Yes, this looks like just a misplaced test sample. Good call to close it.
