### ISSUE TITLE
More detail needed on firewall rules needed to resolve ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by mildsauce** [MicrosoftDocs/windows-itpro-docs#9024]
The section: "Why am I getting the error message "ERR_NAME_NOT_RESOLVED" after not being able to reach PAC file" recommends creating two firewall rules to allow traffic. 
1. Please add details on if both of these these rules are inbound or outbound rules. If they are inbound, can we restrict the remote IP addresses it can accept connections from so this is not exposed on the network when deployed in security conscious environments? 
2. Is port 67 the local port or the remote port for the first firewall rule? 
3. For the second rule it says "but scoped to local port 68" then in step 4 says to enter port 67 for the local port?

If I follow these directions as written, you end up with two identical rules. More details are needed from you so admins can deploy this without making assumptions or needing to experiment their way through a supported feature. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8927df09-e9aa-8c40-290d-0ca7d86ec4e2
* Version Independent ID: ca67bcfc-6120-d6ca-290b-1a7822494c73
* Content: [FAQ - Microsoft Defender Application Guard (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-application-guard/faq-md-app-guard)
* Content Source: [windows/security/threat-protection/microsoft-defender-application-guard/faq-md-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-application-guard/faq-md-app-guard.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by VLG17** [comment]
@mildsauce Thank you for bringing this up. My comments below:

1. Both rules are inbound. Restricting the IP range could lead to this error again, so the recommendation is to leave it unrestricted. If you do need to restrict it, test it before.
2. Port 67 is the local port
3. Good observation, I will create a chage request for this. It should be port 68.

**Comment by nam31** [comment]
Closing via #9211 
Thanks
