### ISSUE TITLE
Windows Sandbox rail mode not in docs

### ISSUE THREAD

**Issue by yffengdong** [MicrosoftDocs/windows-itpro-docs#9025]
In the video, I see that they use Admin Center, deploy a package with rail mode wsb file(24:59), and open start menu and run like remoteapp(26:48) in Windows Sandbox.
It's not in docs and I do not know how to deploy rail mode wsb file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c06f3ef-5946-862a-ae14-f897fdb518ca
* Version Independent ID: cd6a8b99-b1e9-dff5-f174-a15840b304f0
* Content: [Windows Sandbox - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yffengdong** [comment]
<img width="460" alt="chrome_Pjr0MkIzsd" src="https://user-images.githubusercontent.com/20380669/105943689-bb642800-609c-11eb-9e41-cd3b9cad7ce9.png">
Windows Sandbox deply package with admin center requirement

<img width="479" alt="chrome_oimiEcDQ4x" src="https://user-images.githubusercontent.com/20380669/105943787-00885a00-609d-11eb-9dbc-6cb5394780e7.png">
Rail mode in start menu

**Comment by yffengdong** [comment]
#8941

**Comment by Reeced40** [comment]
@yffengdong thank you for reaching out. I work on the writing/editing side of the docs. Is there a change you recommend to the article to help other users? Let me know if this article is helpful - https://docs.microsoft.com/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file

**Comment by Reeced40** [comment]
@yffengdong please confirm if the link above helped resolve your issue.

**Comment by nam31** [comment]
@yffengdong We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve. Thank you.

**Comment by timmontague** [comment]
@Reeced40 That document does not mention "remote applications integrated locally" (RAIL) mode which was demonstrated in the video at 26:48. In RAIL mode an application running in the Sandbox is integrated with the host OS and the Sandbox desktop is not shown. https://docs.microsoft.com/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file does not explain how to do that

**Comment by illfated** [comment]
( Ref. #9529 )

**Comment by robbycuenot-rh** [comment]
I stumbled across Windows Sandbox the other day and have been building configurations for various use cases-- however it appears that RailMode is still not documented here. Using Process Explorer I'm able to see it in the settings, and adding <RailMode>enable</Railmode> to a .wsb file does not cause it to crash, however I'm still unable to get it working as shown in the demo. Does anyone have insight into this feature?
