### ISSUE TITLE
Miracast not enabled on LTSC 2019,  the UWP Project to this screen removed

### ISSUE THREAD

**Issue by sarahbj82** [MicrosoftDocs/windows-itpro-docs#9026]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c696c9ed-b095-68ff-d50d-df345daf8a4a
* Version Independent ID: 50ad3b26-8e9b-6a56-7b3c-56c1374c4747
* Content: [What's new in Windows 10 Enterprise LTSC 2019 - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/ltsc/whats-new-windows-10-2019)
* Content Source: [windows/whats-new/ltsc/whats-new-windows-10-2019.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/ltsc/whats-new-windows-10-2019.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by Reeced40** [comment]
@sarahbj82 thank you for reaching out.  Just for clarity, please can you elaborate on what is missing from this article and I will investigate further. I work on the writing/editing side of Docs and would like to add anything that would be helpful to other users as well.

**Comment by nam31** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve. Thank you.
