### ISSUE TITLE
Translation mistake

### ISSUE THREAD

**Issue by jessy-manc** [MicrosoftDocs/windows-itpro-docs#9027]
Hello,

There is an error in the french version of this page :
The environment variables 'TEMP' and 'TMP' must not be translated into french, and must be kept as its original version.

Actually they are respectively written as 'TEMPORAIRE' and 'TECHNOLOGIQUE'.

[environment variables](https://docs.microsoft.com/fr-fr/windows/deployment/usmt/usmt-recognized-environment-variables#9916e-353)

Best regards.
---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 72d479c1-cedc-05fc-2d73-45342b955037
* Version Independent ID: 8e91c2df-8405-3ec0-210e-1b97e86073cf
* Content: [Variables d’environnement reconnues (Windows 10) - Windows Deployment](https://docs.microsoft.com/fr-fr/windows/deployment/usmt/usmt-recognized-environment-variables)
* Content Source: [windows/deployment/usmt/usmt-recognized-environment-variables.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/usmt/usmt-recognized-environment-variables.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by denisebmsft** [comment]
@TinaMcN, can you take a look? Thanks!

**Comment by RAJU2529** [comment]
@denisebmsft ,  I checked the french article, and i found  symbol  **:**  is  missing  in many places

**Comment by RAJU2529** [comment]
there is  a gap between  C  and SIDL  in french article 

C SIDL_DEFAULT_LOCAL_APPDATA

**Comment by TinaMcN** [comment]
Hi @jessy-manc thanks for reporting it.  It appears to be a machine-translation problem.  I sent the article for human translation which should be complete in approx 3 days.

**Comment by illfated** [comment]
There are also spaces around the % % signs, which should be next to their keywords and without spacing.
- currently: Fait référence au dossier AppData dans% DEFAULTUSERPROFILE %.
- should be: Fait référence au dossier AppData dans `%DEFAULTUSERPROFILE%`.

**Comment by illfated** [comment]
@RAJU2529 : you have recently made a PR to a page like this one in the /en-us/ repository, right?

**Comment by RAJU2529** [comment]
@yea   it's in English version

**Comment by illfated** [comment]
Very well, then I presume the issue of the separated C character from `SIDL_DEFAULT_LOCAL_APPDATA` will be resolved in the source document.

**Comment by e0i** [comment]
Manually verified to be fixed. Thanks.
