### ISSUE TITLE
Typo: "Welcome to Microsoft Defender for Endpoint, the new name for Microsoft Defender for Endpoint."

### ISSUE THREAD

**Issue by jordi-j** [MicrosoftDocs/windows-itpro-docs#9028]
At the top of the document there's a phrase that says "Welcome to Microsoft Defender for Endpoint, the new name for **Microsoft Defender for Endpoint**.". It should say "... the new name for **Microsoft Defender Advanced Threat Protection**" or something to that effect. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa63fbe-c611-fe9c-7f86-bd33e27bd788
* Version Independent ID: 74f63ac9-7436-b6f4-51f9-35c7efe6f77a
* Content: [Onboard Windows 10 multi-session devices in Windows Virtual Desktop - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/onboard-windows-10-multi-session-device)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/Onboard-Windows-10-multi-session-device.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/Onboard-Windows-10-multi-session-device.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@e0i , I took  example  name from below article 
**https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection**

**Comment by illfated** [comment]
(ref. #9032 )

**Comment by adirdidi** [comment]
I'm closing the PR mentioned, as I'm already taking care of that.
Thank you.

**Comment by illfated** [comment]
> I'm closing the PR mentioned, as I'm already taking care of that.
> Thank you.

OK, fair enough. Thank you for the update.

**Comment by illfated** [comment]
By the way, will the correction commit be added as a standalone update, possibly reference this ticket and close it with the text "Closes #9028" on a single line, 2 lines below the commit message title?
