### ISSUE TITLE
help please i don have control withn my pc

### ISSUE THREAD

**Issue by alexaguilar89** [MicrosoftDocs/windows-itpro-docs#9034]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f784502-84dc-1122-eab4-1eeeb08da046
* Version Independent ID: 21f210a7-4c38-8f62-0226-121562617fef
* Content: [Memory integrity - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/memory-integrity)
* Content Source: [windows/security/threat-protection/device-guard/memory-integrity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/device-guard/memory-integrity.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by RAJU2529** [comment]
@alexaguilar89 .
   The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

you can get all help from answers.microsoft.com

**Comment by illfated** [comment]
#please-close
