### ISSUE TITLE
ASR Rule process exclude

### ISSUE THREAD

**Issue by pinguon** [MicrosoftDocs/windows-itpro-docs#9035]
Hi,

it's never written how a process can be excluded from the ASR rules ...

e.g. from different USB Sticks 

so means different "drive" and different "folder" the EXE File is always the same.

DriveA/folder1/setup.exe
DriveB/folder2/setup.exe

can I solve that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b801a8e-cbbe-97c8-34a9-b95d996e3ac1
* Version Independent ID: e3e84852-629c-e63a-7d41-d5a8ef278d0b
* Content: [Attack surface reduction frequently asked questions (FAQ) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction-faq)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction-faq.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @martyav
* Microsoft Alias: **v-maave**

**Comment by VLG17** [comment]
@pinguon When defining the ASR exclusion, you need to specify the path. In you case, you have different paths, although the process is the same - setup.exe

> to exclude files and folders from ASR rules, use the following cmdlet:

> Add-MpPreference -AttackSurfaceReductionOnlyExclusions "<**fully qualified path or resource**>"

More details [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/enable-attack-surface-reduction#powershell)

>

**Comment by pinguon** [comment]
hi, thanks for your answer, 
but that means I can't fix my problem with different paths?

DriveA/folder1/setup.exe
DriveB/folder2/setup.exe

folder is a variable with 8 digits of the date...

**Comment by illfated** [comment]
If you use variables to name folders, you are constantly generating potential new attack vectors for Microsoft Defender to analyze. If you really need to generate a new path every day, you should also invest the same amount of time to add that path to the exclusion list manually or via some kind of macro you might be able to create on your side.
