### ISSUE TITLE
Please change footnotes to extra column in table

### ISSUE THREAD

**Issue by yvesrosius** [MicrosoftDocs/windows-itpro-docs#9036]
Please change footnotes to extra column in table. Suggested headers:
Windows Edition, Supported?, Since Windows Version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c80b4305-2983-15b5-8c94-2ea9e3addb48
* Version Independent ID: 538aa3f8-c819-6d9a-9499-32b3eff0fd90
* Content: [Policy CSP - Storage - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-storage)
* Content Source: [windows/client-management/mdm/policy-csp-storage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-storage.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
The changes proposed doesn't fit the CSP articles' template. Thank you for the suggestion.
