### ISSUE TITLE
JSON examples incorrect

### ISSUE THREAD

**Issue by atz** [MicrosoftDocs/windows-itpro-docs#9037]
The examples (auth token response, for example) have quoted integer strings instead of integers like `"559"`.  In testing, it appears actual JSON numbers are returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b835bf35-1614-2d8d-13ab-176c6d839047
* Version Independent ID: ed4653f3-e393-dd42-5960-87888c08ba40
* Content: [Pull Microsoft Defender for Endpoint detections using REST API - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/pull-alerts-using-rest-api)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/pull-alerts-using-rest-api.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/pull-alerts-using-rest-api.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by adirdidi** [comment]
Resolved, thank you.
