### ISSUE TITLE
Is there an example / documentation ?!

### ISSUE THREAD

**Issue by alexa872** [MicrosoftDocs/windows-itpro-docs#9038]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a93860-0460-2f14-dce9-e485d3735371
* Version Independent ID: bf7bec96-f6aa-cc76-4779-5245fcd14323
* Content: [Supported Microsoft Defender Advanced Threat Protection response APIs - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/supported-response-apis)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/supported-response-apis.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/supported-response-apis.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

Hello, thanks for your attention, I would like to ask about these api functions, can I really call them and how to call them, im kinda building a av that work with windows defender, some thing for the collage, i really would like to figure it out ! At least how to load them, the article does only show the functionality of each one, a example would help, or at least the header file and the parameters needed....thank you again for your time and have a nice day

**Comment by adirdidi** [comment]
The page you refer to is obsolete and I'll remove it.
The samples for the APIs mentioned in this doc are available at: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/machineaction and https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/files.
