### ISSUE TITLE
Revision request and proposal for keep pre-translated terms

### ISSUE THREAD

**Issue by yoshiband** [MicrosoftDocs/windows-itpro-docs#9041]
[フィードバックをこちらに入力してください]
Hello, whom it may concern

I found some mistakes in the Japanese version of this page.
The modification points are listed below, so please review them.

And I have another proposal, that is, how about keeping original words which is used in actual menu like the following example?
For example, the "Status" column of the table in the "Automated investigation status" section, it is much easier to understand the description for real context.

original -> translation

Running -> Running (実行中)
Partially investigated -> Partially investigated (一部調査)
No threats found -> No threats found (脅威無し)
Pending action (保留中のアクション) -> Pending action (保留中のアクション)
Remediated -> Remediated (修復)
Partially remediated -> Partially remediated (一部修復)
Terminated by system -> Terminated by system (システムによって終了)
Failed -> Failed (失敗)
Queued -> Queued (順番待ち)
Waiting for device -> Waiting for device (デバイス待ち)
Terminated by user -> Terminated by user (ユーザーによって終了)

### No. 1
Link URLs are inserted in the wrong position.
Wrong
> 組織のセキュリティ運用チームの一員である場合は、アクション センター ( ) で保留中の修復アクションと完了した修復アクションを表示できます https://securitycenter.windows.com/action-center 。 [調査] ページ ( ) を使用 して、 https://securitycenter.windows.com/investigations 調査に関する詳細を表示することもできます。

Proposal
> 組織のセキュリティ運用チームの一員である場合は、アクション センター (https://securitycenter.windows.com/action-center) で保留中の修復アクションと完了した修復アクションを表示できます。[調査] ページ (https://securitycenter.windows.com/investigations) を使用して、調査に関する詳細を表示することもできます。

### No. 2
The link is broken in the first row of "調査の一覧のフィルター" ("Filters for the list of investigations") section
> ステータス      (「 自動調査の状態」を参照)

### No. 3
The Description corresponding to "Pending action" is misplaced in "自動調査の状態" ("Automated investigation status") section.
> Pending action (保留中のアクション)        (**nothing!**)

### No. 4
Link URL is inserted in the wrong position
Wrong
> 保留中のアクションを表示および承認 https://securitycenter.windows.com/action-center するには、アクション センター ( ) にアクセスします。

Proposal
> 保留中のアクションを表示および承認するには、アクション センター (https://securitycenter.windows.com/action-center) にアクセスします。

### No. 5
Incorrect translation
Wrong
> この例の画像では、自動調査は午前 10 時 26 分 59 分に開始され、午前 10 時 56 分 26 分に終了しました。 そのため、調査全体が 29 分 27 秒間実行されました。

Proposal
> この例の画像では、自動調査は 10:26:59 AM に開始され、10:56:26 AM に終了しました。そのため、調査全体が 29 分 27 秒間実行されました。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8f76dfd0-7e7c-c34c-e099-76e940edc1d2
* Version Independent ID: ac03415f-4729-efb6-239f-6476a1347207
* Content: [自動調査の詳細と結果を表示する - Windows security](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-atp/auto-investigation-action-center)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/auto-investigation-action-center.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/auto-investigation-action-center.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by nam31** [comment]
@TinaMcN Can you please assist with this translation/localization issue?

**Comment by TinaMcN** [comment]
@yoshiband thank for your detailed feedback.  The article was machine translation and it appears to have many issues.  I have sent the article to be human translated, this will take approx. 2-3 days.  Hopefully most of the issues will then be fixed.
Even though it is a good suggestion unfortunately we are not able to translate terms leaving both English and Japanese e.g.
Running -> Running (実行中)
The reason is because whenever a file is human translated all of the source (English ) and translated terms are automatically sent to our translation memory database which we use to recycle translations.  So in this example the translation memory would think an approved translation for "Running" is "Running (実行中)" and might accidentally include the English word in a different scenario when "running" is used.

**Comment by yoshiband** [comment]
Thank you for your comment.
And I understand the reason that you are not able to write both English and Japanese concurrently.

Thank you very much for updating.

**Comment by TinaMcN** [comment]
@yoshiband the article has now been translated by a human.  Can you please check if it is ok now and you can close this issue if it looks ok to you now.  Thanks for your understanding about the limits of not being able to write both English and Japanese.

**Comment by yoshiband** [comment]
@TinaMcN - Thank you very much. I think it's ok, so I would like to close this issue.
