### ISSUE TITLE
The video on this page is not relevant anymore

### ISSUE THREAD

**Issue by sakaldeepyadav** [MicrosoftDocs/windows-itpro-docs#9043]
The video on this page is not relevant anymore like ATP does not exist.  please change the video. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bdb99e4-289a-c09a-c35c-2774fc52a402
* Version Independent ID: 4d325389-c9b8-2601-0ff4-c7b6bf5a6c28
* Content: [Microsoft Defender for Endpoint - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
> The video on this page is not relevant anymore like ATP does not exist. please change the video.

Fair point, the branding "Microsoft Defender Advanced Threat Protection" is outdated, so it needs to be replaced (or maybe removed until an updated video becomes available).

https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection.md#L28-L34

```diff
  Microsoft Defender for Endpoint is an enterprise endpoint security platform designed to help enterprise networks prevent, detect, investigate, and respond to advanced threats.
  <p></p>

- >[!VIDEO https://www.microsoft.com/videoplayer/embed/RE4wDob]

  Defender for Endpoint uses the following combination of technology built into Windows 10 and Microsoft's robust cloud service:

```

If there is a new video available, it should be just as easy to resolve as a link update.

**Comment by adirdidi** [comment]
Thank you for your report. Our marketing team is already working on updating the videos, and for now - the current videos will remain in the page.
