### ISSUE TITLE
Clarity on MDE for Linux alongside MMA

### ISSUE THREAD

**Issue by KieryBUK** [MicrosoftDocs/windows-itpro-docs#9045]
Please can we add clarity into the two cautions on this page to explicitly state that MDE on Linux can run alongside the MMA on Linux. We have customers asking this and under the impression this is not supported (which it is) due to the wording in the Caution. 

Explicitly stating "Microsoft Defender for Endpoint can run alongside the Microsoft Monitoring Agent" in bot the caution blocks would solve this challenge.

Many thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef3b1143-53ee-892c-59c8-5cfa12e017c2
* Version Independent ID: 29f6c231-15bd-296b-cca9-7ef6ba8192df
* Content: [Microsoft Defender ATP for Linux - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-linux)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-linux.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-linux.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Sounds useful to me, thank you for commenting and suggesting.

CC: @konstruktoid - Would you be able to comment on this, in case you can point out any useful details for us Windows-heads?

**Comment by konstruktoid** [comment]
Sorry, I don't have any information or experience regarding running multiple fanotify-based security solution side by side.

**Comment by KieryBUK** [comment]
I agree but customers get confused. I've fielded multiple questions from customers now asking if this warning applies to the MMA. They see the MMA as a security solution as they want to use it for Azure Defender and Azure Sentinel - both which are seen as "security solutions". A short note to explicitly qualify it out seems sensible, and would easily remove this customer confusion.

**Comment by MaratMussabekov** [comment]
Hello, I believe adding such note will cause a bigger confusion.
Dear @dansimp, could you please advise?
Thank you

**Comment by mjcaparas** [comment]
Checking with the team.

**Comment by mjcaparas** [comment]
Team concurs with comment made by @MaratMussabekov re: 
Monitoring Agent neither third-party nor protection product.
Monitoring Agent is not a security solution.
