### ISSUE TITLE
Common folder variables page

### ISSUE THREAD

**Issue by 89z** [MicrosoftDocs/windows-itpro-docs#9046]
I used to visit this page:

https://web.archive.org/web/20180606140951/microsoft.com/en-us/wdsi/help/folder-variables

To reference Common folder variables. However since 2018, the page now redirects
here:

https://microsoft.com/wdsi

Is it possible to restore this page, or is a similar page available?

**Comment by illfated** [comment]
"Common folder variables" is not considered a specific part of the Security field of operations, but rather a part of understanding the Operating System itself. See if the page linked below can be just as useful to you, as well as searching for the variables in other Windows 10 pages where this should be part of the reference material.

- https://docs.microsoft.com/windows/deployment/usmt/usmt-recognized-environment-variables (MS Docs)
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/usmt/usmt-recognized-environment-variables.md (GitHub version)

When searching for the variables, consider using the search term `command line environment variables`, a familiar phrase to most users who dig into the command line (cmd) environment.

**Comment by nam31** [comment]
@89z Thank you for providing feedback.
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
Please note that the issues section of the repository is intended for corrections in technical documentation.
Thank you for your contribution to make the docs better! Much appreciated!
