### ISSUE TITLE
Typo Correction

### ISSUE THREAD

**Issue by gwreed** [MicrosoftDocs/windows-itpro-docs#905]
The last sentence in the Unified Extensible Firmware Interface (UEFI)-based deployments section reads "You do not need to update or change your task sequences in any way to accommodate UFEI." 

Should be UEFI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Service: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by andreabichsel** [comment]
Fixed--thank you!
