### ISSUE TITLE
English -> Chinese Translation Error

### ISSUE THREAD

**Issue by kaneorotar** [MicrosoftDocs/windows-itpro-docs#9051]
"手表 Dana Huang 解释为什么 Windows Hello 企业版 PIN 比密码更安全。" should be "观看 Dana Huang 解释为什么 Windows Hello 企业版 PIN 比密码更安全。"

"Watch" was incorrectly translated to "手表" which means the time-telling device. It should be "观看" which means view/observe.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c34dbafa-df3c-a5a5-32d5-2ce152893534
* Version Independent ID: cebdd9a6-45d7-6306-373c-7d31121f9e16
* Content: [PIN 为何优于密码 (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/zh-cn/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
Thank you. Feels a little bit like "Windows Nín hǎo" now that you point out that machine translation error. 😄

@TinaMcN : Would you be so kind as to inform the translator managers to have a look at that issue?

***

**手表** Dana Huang 解释为什么 Windows Hello 企业版 PIN 比密码更安全。

> [!VIDEO https://www.youtube.com/embed/cC24rPBvdhA]

PIN 绑定到设备

***

https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md

**Watch** Dana Huang explain why a Windows Hello for Business PIN is more secure than a password.

> [!VIDEO https://www.youtube.com/embed/cC24rPBvdhA]

**Comment by nam31** [comment]
@TinaMcN Can you please assist with this translation/localization issue?

**Comment by TinaMcN** [comment]
@kaneorotar thank you for reporting this.  The article is machine translated and it incorrectly understood the meaning of "watch" in this context.   I passed on to the MT tool team so they can investigate to see if they can fix it in the tool.  If not I'll get the article human translated.

**Comment by TinaMcN** [comment]
@kaneorotar the article is human translated and the issue appears to be fixed.  Can you please close it if it looks ok to you?  Thanks again for telling us about this issue.
