### ISSUE TITLE
Collect diagnostic data for file submissions command does not work.

### ISSUE THREAD

**Issue by jozefizso** [MicrosoftDocs/windows-itpro-docs#9055]
The command `cd c:\program files\windows defender` on the page does not work on Windows 10 Enterprise 2019 LTSC.

```
Set-Location : A positional parameter cannot be found that accepts argument 'files\windows'.
At line:1 char:1
+ cd c:\program files\windows defender
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34df903a-7faf-bff1-802c-cf5081ce258e
* Version Independent ID: ac1f1b04-d27a-5fdb-292e-32998d10b35f
* Content: [Troubleshoot problems with attack surface reduction rules - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-asr)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/troubleshoot-asr.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-asr.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by beerisgood** [comment]
Paths with spaces must be marked with **"** at the front and at the back

**Comment by adirdidi** [comment]
Fixed, thank you.
