### ISSUE TITLE
Collect diagnostic data for file submissions command does not work.

### ISSUE THREAD

**Issue by jozefizso** [MicrosoftDocs/windows-itpro-docs#9056]
The command `mpcmdrun -getfiles` does not work on Windows 10 Enterprise 2019 LTSC.

```
mpcmdrun : The term 'mpcmdrun' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ mpcmdrun -getfiles
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (mpcmdrun:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34df903a-7faf-bff1-802c-cf5081ce258e
* Version Independent ID: ac1f1b04-d27a-5fdb-292e-32998d10b35f
* Content: [Troubleshoot problems with attack surface reduction rules - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-asr)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/troubleshoot-asr.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-asr.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@jozefizso   . you have entered wrong command in wrong place.

**Comment by adirdidi** [comment]
@jozefizso The error format indicate that you've tried to run the command from a PowerShell session, and not from an elevated command prompt as the documentation instructs.
I've just tested the command on a Windows 10 Ent 2019 LTSC machine and it does work:
![image](https://user-images.githubusercontent.com/68847945/106534512-ee734500-64fc-11eb-9a48-ab9ab7569ec9.png)

Closing the issue.
