### ISSUE TITLE
Use audit mode to measure impact command does not work

### ISSUE THREAD

**Issue by jozefizso** [MicrosoftDocs/windows-itpro-docs#9057]
The command `Set-MpPreference -AttackSurfaceReductionRules_Actions AuditMode` does not work on Windows 10 Enterprise 2019 LTSC.

```
Set-MpPreference : A general error occurred that is not covered by a more specific error code.
At line:1 char:1
+ Set-MpPreference -AttackSurfaceReductionRules_Actions AuditMode
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Set-MpPreference],
   CimException
    + FullyQualifiedErrorId : MI RESULT 1,Set-MpPreference
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 751781d9-0e3b-85ea-21c7-2714a39041f5
* Version Independent ID: b14c1d00-5f56-d3c6-0847-8d2967740680
* Content: [Evaluate attack surface reduction rules - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/evaluate-attack-surface-reduction)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/evaluate-attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/evaluate-attack-surface-reduction.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by RAJU2529** [comment]
@jozefizso . you not mentioned asr rules in command. so its wrong

**Comment by RAJU2529** [comment]
@jozefizso , you need to use  PowerShell  command  to  enter the commands


**Add-MpPreference -AttackSurfaceReductionRules_Ids 7674BA52-37EB-4A4F-A9A1-F0F9A1619A2C -AttackSurfaceReductionRules_Actions AuditMode**

![Capture](https://user-images.githubusercontent.com/3296790/106545838-1b8d1b00-6530-11eb-84a5-b53b796a241e.JPG)

**Comment by RAJU2529** [comment]
@jozefizso , to know  all  ASR ids, visit below page 
**https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction**

**Comment by illfated** [comment]
PR #9099 is now merged. The changes should be live on docs.microsoft.com in a day or less time than that.

**Comment by nam31** [comment]
Closing via #9099
Thanks
