### ISSUE TITLE
Dead download link on the page

### ISSUE THREAD

**Issue by SergGu** [MicrosoftDocs/windows-itpro-docs#9063]
Hello, There is dead download link on the page.

The link is https://www.microsoft.com/download/details.aspx?id=54795
It is under "The guide is available in PDF format for offline viewing: Download the guide in PDF format" section.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b674bf82-b910-2b06-86f4-f454dc74026f
* Version Independent ID: 7c8d5db0-107a-ced6-106e-ef11e80e5c7c
* Content: [Evaluate Microsoft Defender Antivirus - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/evaluate-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/evaluate-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/evaluate-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@SergGu . Thanks for reporting to us. Issue is conformed from my side too.

**Comment by adirdidi** [comment]
Please check again, it's working on my end.

**Comment by RAJU2529** [comment]
specified link is working today

**Comment by adirdidi** [comment]
@SergGu Please check again and confirm closing this issue.

**Comment by SergGu** [comment]
The file is available for download. Thank you very much for quick response.

**Comment by adirdidi** [comment]
Thank you for reporting and confirming.
