### ISSUE TITLE
More information on SetEduPolicies

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#9064]
Its not clear what are the implications of setting up SetEduPolicies on Windows Pro or if they break any license agreement.

In theory Education institutions should own a educational license (which by default works with LockScreenImageUrl) So more information is needed if is a breach to set a non eductional device running windows 10 pro with the SetEduPolicies and what changes are implemented on the device once such policy is enabled.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ff22cb-61e7-606b-516c-cae53ac02869
* Version Independent ID: 3bccae3f-7ef6-8d56-ab21-02a85131d398
* Content: [Personalization CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/personalization-csp)
* Content Source: [windows/client-management/mdm/personalization-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/personalization-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@schenardie You can find [here](https://docs.microsoft.com/en-us/education/windows/configure-windows-for-education) the Windows 10 configuration recommendations for EDU customers. We can see that:

> We recommend that all Windows 10 devices in an education setting be configured with **SetEduPolicies enabled**

> 
![image](https://user-images.githubusercontent.com/41186174/109805120-bb22f380-7c2b-11eb-9f0d-7a8abb106a13.png)

From [this article](https://docs.microsoft.com/en-us/windows/configuration/set-up-shared-or-guest-pc) describing the concept of _shared PC _mode_, i would say you can enable SetEduPolicies on Windows 10 PCs, but that would imply that the PC needs to be used in a shared PC model.

![image](https://user-images.githubusercontent.com/41186174/109805938-ba3e9180-7c2c-11eb-94fa-ef3dca41d55b.png)

If you want to use Personalization CSP, you need to have SetEduPolicies enabled and SharedPC CSP set.

![image](https://user-images.githubusercontent.com/41186174/109806085-f1ad3e00-7c2c-11eb-99b7-d9466560e2e7.png)

**Comment by schenardie** [comment]
I understand all the requirements of the feature but my question remain unanswered. I want to know if its ilegal from the point of view of licensing for me to setup non educational windows with the setedupolicy so i can implement the lockscreenimageurl csp. If not i believe the documentation could be changed to clarify this. If it is indeed a breach o license then the note should be changed. To state that it can be set but its against the licensing.
