### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#9065]
The link to download the upload baseline is broken
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1447d5c3-2847-6a77-4f02-9e15333a709e
* Version Independent ID: 4eabe8ac-4289-66b8-1a7d-15e2c9adaf91
* Content: [Update Baseline - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-baseline)
* Content Source: [windows/deployment/update/update-baseline.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-baseline.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
Hmm, OK. You mean that the download itself is broken, not the link to the download page?

Working links:
- https://docs.microsoft.com/en-us/windows/deployment/update/update-baseline#policies-included-in-the-update-baseline
- https://www.microsoft.com/en-us/download/details.aspx?id=101056
- https://www.microsoft.com/en-us/download/confirmation.aspx?id=101056

**Comment by illfated** [comment]
Alternative download link:
- https://www.microsoft.com/en-us/download/confirmation.aspx?id=101056&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1

**Comment by DeanGross** [comment]
weird, its working now thanks
