### ISSUE TITLE
Setup Intune + Autopilot two articles, unclear how to do both?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/windows-itpro-docs#9067]
There appear to be multiple sections for endpoint management articles and I'm starting to wonder if we have intune and autopilot setup correctly.

This article talks about just enrolling devices into intune using GPO

Docs > Windows > Client management > Mobile Device Management has this article
https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy

And then we have this article that talks about enrolling in autopilot using GPO, but not in intune...

Docs > Enterprise Mobility + Security > Microsoft Endpoint Manager > Autopilot
https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid#create-and-assign-an-autopilot-deployment-profile

We are trying to enroll existing devices into intune, and also enroll them in autopilot moving forward. However, the instructions in these two articles are not exactly similar...

We opened service ticket 23906196, to troubleshoot Prt issues and are still trying to understand the best way to configure things correctly.

**Comment by denisebmsft** [comment]
Hello @jonwbstr and thank you for raising this question. Is your feedback primarily for this particular article: https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy

**Comment by jonwbstr** [comment]
1) there are two areas in docs for intune articles. That's confusing.
2) there are 3 scenarios. Intune, autopilot, both. I found articles for 2
of 3 scenarios. Would be nice to have the 3rd scenario covered somewhere.

The feedback is not on the article specifically, it's that the article
doesn't acknowledge there are 3 scenarios, or have a link to the other
article which is related to deploying intune via autopilot.


P.s. I'm honestly not even sure why someone would enroll devices in
autopilot via gpo. Once enrolled they have to be wiped again. Just weird.

**Comment by jonwbstr** [comment]
I realized I may have been mixing up my terminology. Microsoft Endpoint Manager Admin Center encompasses both Intune and Autopilot. Autopilot and Intune seem to be joined at the hip. The current layout for documentation having intune and autopilot in completely separate areas is confusing given the admin center is trying to put them under the same umbrealla.

Feel free to close this issue whenever, I don't really expect any changes to happen, just wanted to pass on feedback on how the documents are organized incase it hasn't been brought up by someone already.

**Comment by e0i** [comment]
@jonwbstr Thank you for coming up with further clarifications about the nature of the issue. Closing based on your suggestion.
