### ISSUE TITLE
Applies To is missing Operating System versions

### ISSUE THREAD

**Issue by amoraa246** [MicrosoftDocs/windows-itpro-docs#9068]
The Applies To states Windows 10 and Windows Server 2016. However, if you go into the Event IDs listed, they mention that they are supported by as back as Windows Server 2008. Furthermore, there's an older article with similar information which does state it's supported by as old as 2008/Win7: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn319068(v=ws.11)

I am hoping this can be updated. I stumbled on this when a co-worker (at Microsoft) asked me to help confirm if this applies to 2012 R2, which I am sure it does. 

Josh Mora - Support Escalation Engineer (Windows Directory Services)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e547f09f-4557-20a3-b7e5-ae2b3a22dcc9
* Version Independent ID: 549096ce-c453-1268-556a-837632f9408e
* Content: [Audit File System (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-file-system)
* Content Source: [windows/security/threat-protection/auditing/audit-file-system.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/audit-file-system.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@amoraa246 Under review. Thank you for the valuable feedback.

**Comment by VLG17** [comment]
@amoraa246 Do you think it makes sense to add a note pointing to the "old" article in regards to older OSs it applies to? If we start adding older OSs to the Applies to: list, we need to always update them as soon as they reach end of support (like Windows 7,8, 2008 R2).
