### ISSUE TITLE
Some images hard to read with page background in dark mode

### ISSUE THREAD

**Issue by bjeans** [MicrosoftDocs/windows-itpro-docs#9069]
Many of the images on this page do not display well when viewed with dark theme.  As an example (https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/images/2-dynamic-working.png) the labels appear to be in black and the image background is transparent therefore making the text appear as dark on dark.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f23363fd-0777-63f3-3a2f-0e5062968a39
* Version Independent ID: 9abd2dc6-d872-4369-5fa4-fab497b53357
* Content: [Windows Sandbox architecture - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-architecture)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-architecture.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-architecture.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@bjeans . thanks for pointing out
 I wil to try to fix.

**Comment by joinimran** [comment]
Hello @bjeans bjeans - Thank you for posting your query. I am going to look into this and will get back to you.

Thanks
Imran.

**Comment by joinimran** [comment]
Hello @bjeans - I have checked and found that these images look normal in dark mode. 

![image](https://user-images.githubusercontent.com/47118050/110247352-ac22a500-7f8d-11eb-8d47-5bf8a22a9ce0.png)

@nam31 - FYI & A Please.

**Comment by nam31** [comment]
@bjeans Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
