### ISSUE TITLE
This is utterly hopeless :-(

### ISSUE THREAD

**Issue by JanineMarchese** [MicrosoftDocs/windows-itpro-docs#907]
Sorry friends (at MS)
This is simply a totally hopeless crappy mess. After Windows 10 1607 it has not been possible to migrate a simple start menu for a user?
This windows 10 project seems to be constant BETA project :-(

I'm REALLY upset!! Get your shit together and build a consistent platform and a decent User migration tool for SCCM/MDT or get USMT up to speed.

JESUS!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 061157dc-8fc8-3f9d-c01f-37f22fbdf1c7
* Version Independent ID: 0b0b6797-9367-eb7c-22ef-5f2b8bbfe592
* Content: [Start layout XML for desktop editions of Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/start-layout-xml-desktop)
* Content Source: [windows/configuration/start-layout-xml-desktop.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/start-layout-xml-desktop.md)
* Service: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by StarScreamV2x** [comment]
Ditto

**Comment by jdeckerms** [comment]
@JanineMarchese and @StarScreamV2x I understand your frustration; the best way to get your feedback viewed and considered by the engineering team is to submit it in the Feedback Hub.
