### ISSUE TITLE
Need clarity on the Intune v/s GPO processing

### ISSUE THREAD

**Issue by karandiwan** [MicrosoftDocs/windows-itpro-docs#9070]
Hi,
    I need more clarity in context of Intune v/s Windows 10 ADMX (GPO) policies and the statement under the NOTE section: "MDMWinsOverGP only applies to policies in Policy CSP. It does not apply to other MDM settings with equivalent GP settings that are defined on other configuration service providers": 

1. As I understand, ADMX are for Group Policy settings which have been built for AD (and now also available within Intune), and whilst MDMWinsOverGP, its **ONLY** applicable to Policy CSP and **does not apply to other MDM settings with equivalent GP settings that are defined on other CSPs**, am I correct in thinking that the ADMXs sit in second part of that statement?.
2. If my understanding is indeed correct, then will ADMX still win if we have a conflicting ADMX GPO which might be applying on a Win10 device from AD (in HAADJ scenario)? Is there a similar processing model to L-S-D-OU?
3. Also aren't ADMXs which are available within Intune (under the hood) applied as a CSP/OMA-URI settings "./Device/Vendor/MSFT/Policy/Config/<ADMXIngestName>~Policy~<ADMXNamespace>~<ADMXCategory>/<PolicyName>" ? If this point is indeed true then the second part of that NOTE statement does not make any sense?

Thanks
Karan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: becd9bd1-6396-3f4a-cc78-c9a06b781516
* Version Independent ID: efeec2a0-08b0-d1fc-72c5-14c23fa11397
* Content: [Policy CSP - ControlPolicyConflict - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-controlpolicyconflict?source=docs)
* Content Source: [windows/client-management/mdm/policy-csp-controlpolicyconflict.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-controlpolicyconflict.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @karandiwan - Thank you for posting your query here. I am going to look into this and will get back to you.

Thanks
Imran.

**Comment by JeremyTBradshaw** [comment]
@karandiwan / @joinimran @nam31 @denisebmsft Can I please add the question to this issue - has this other MS Docs page been archived in error?: https://github.com/MicrosoftDocs/IntuneDocs/blob/master/intune/fundamentals/resolve-gpo-and-microsoft-intune-policy-conflicts.md

It has been referenced in #6482 but no longer can the docs.microsfot.com version of the link be accessed.  It seems like that page is still relevant, unless I'm mistaken somehow.

**Comment by nam31** [comment]
Closing via #9219
Thank you
