### ISSUE TITLE
Intune support for LTSC 2019 Update for business

### ISSUE THREAD

**Issue by sandytsang** [MicrosoftDocs/windows-itpro-docs#9072]
Hello, in this doc, it said "Microsoft Intune supports Windows 10 Enterprise LTSC 2019 and later. This includes support for features such as Windows Autopilot. However, note that Windows Update for Business (WUfB) does not currently support any LTSC releases, therefore you should use WSUS or Configuration Manager for patching.". 

I think this is incorrect. I asked in tech community from Iot product team, the answer was " Yes you can use Intune to manage IoT Enterprise 2019 LTSC updates. You can choose to use Intune, WSUS, or ConfigMgr. You can use these tools for version 2004 and 2019."

https://techcommunity.microsoft.com/t5/learn-iot/ask-the-iot-expert-windows-10-iot-enterprise/td-p/1551016

Regards, Sandy

**Comment by denisebmsft** [comment]
Hello @sandytsang. Thanks for posting your question here. Can you please tell us to which article your question applies? This information will help us route the issue correctly.

**Comment by sandytsang** [comment]
@denisebmsft Hello, this is the article. Thanks for responding 🙏

https://docs.microsoft.com/en-us/windows/whats-new/ltsc/whats-new-windows-10-2019#microsoft-intune

**Comment by MaratMussabekov** [comment]
Hello @sandytsang ,
I will try to reproduce this scenario to check.
Thank you

**Comment by MaratMussabekov** [comment]
Hello @sandytsang ,
Just tried to configure updates using Intune, and still unable to set it for LTSC devices.
Thank you

**Comment by sandytsang** [comment]
@MaratMussabekov  I tested this with LTSC 2019, and I am able to configure updates using Intune. and I blogged about it few months ago. https://sandyzeng.com/manage-windows-iot-enterprise-with-microsoft-endpoint-manager-intune/

**Comment by MaratMussabekov** [comment]
Hello @sandytsang ,
I tried to create device profile to manage updates, and LTSC is missing from the available channels:
![изображение](https://user-images.githubusercontent.com/48041687/107111091-f3beef80-686e-11eb-996f-82d0ed5b8e68.png)
I meant that by saying I wasn't able to set updates from LTSC devices.
Thank you

**Comment by sandytsang** [comment]
@MaratMussabekov Intune UI "Update Ring" is not the only way to configure update settings. Can use Policy CSP to configure Windows update settings for LTSC https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update

That's why, the statement of "Intune cannot manage update to LTSC 2019, need use WSUS or ConfigMgr is not correct, and misleading people not use Intune to manage LTSC at all. " 

And take a look this doc, you don't need and cannot assign LTSC to other update channel, LTSC is the only servicing channel for LTSC. Unlike other versions of Windows, that can choose SAC or Insider. The UI update ring doesn't have LTSC, I think it doesn't want to misleading people think can change from SAC to LTSC or other way around. But you can still manage all the update configuration by using customer OMA-URL (Policy CSP). 

https://docs.microsoft.com/en-us/windows/deployment/update/waas-servicing-channels-windows-10-updates

**Comment by Kateyanne** [comment]
@MaratMussabekov  could you advise next steps on this open issue? Thank you.

**Comment by MaratMussabekov** [comment]
Dear @Kateyanne ,
I believe the issue can be closed, as the PR was merged recently.
Thank you!

**Comment by Kateyanne** [comment]
@nam31 Issue can now be closed
