### ISSUE TITLE
"throttling is enhanced" link is dead

### ISSUE THREAD

**Issue by dongearhart** [MicrosoftDocs/windows-itpro-docs#9081]
The link in the Delivery Optimization section to information about enterprise throttling (https://docs.microsoft.com/en-us/windows-insider/at-work-pro/wip-4-biz-whats-new#new-download-throttling-options-for-delivery-optimization-build-18917) goes to a 404 not found page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d602e13e-c1af-958b-8574-a020c49a4b89
* Version Independent ID: f77197b5-cabd-25e7-473a-f4aa663ff6e9
* Content: [What's new in Windows 10 deployment - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-whats-new#delivery-optimization)
* Content Source: [windows/deployment/deploy-whats-new.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-whats-new.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Only to simplify the link address, in case it helps troubleshooting the issue:
- https://docs.microsoft.com/windows-insider/at-work-pro/wip-4-biz-whats-new => 404 - Page not found

(Note the /windows-insider/ part, could be useful to dig within that directory or nearby directories.)

**Comment by illfated** [comment]
Old archive content that the link used to point to:
- http://web.archive.org/web/20200324204759/https://docs.microsoft.com/en-us/windows-insider/at-work-pro/wip-4-biz-whats-new#new-download-throttling-options-for-delivery-optimization-build-18917

**Comment by illfated** [comment]
Found it. The content has been moved to the archives of the Windows insider subdirectory:
- https://docs.microsoft.com/en-us/windows-insider/archive/new-for-business#new-download-throttling-options-for-delivery-optimization-build-18917
