### ISSUE TITLE
Policy is rejected by licensing

### ISSUE THREAD

**Issue by LingTjal** [MicrosoftDocs/windows-itpro-docs#9084]
Doesn't seem to work with a Microsoft 365 Business Premium license:

MDM PolicyManager: Policy is rejected by licensing, Policy: (Configure), Area: (LocalUsersAndGroups), Result:(0x82B00006) Unknown Win32 Error code: 0x82b00006.

It's working in a different tenant with EMS E3, but not with Microsoft 365 Business Premium.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b0c55a7-9aaa-d395-409e-59c2595c8e9e
* Version Independent ID: cf8e5a71-a8fc-1d43-6eed-03d3f2490693
* Content: [Policy CSP - LocalUsersAndGroups - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localusersandgroups)
* Content Source: [windows/client-management/mdm/policy-csp-localusersandgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-localusersandgroups.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @LingTjal ,
Are you sure pc is running Windows 10 20H2?
Are you sure Microsoft 365 Business Premium license is properly assigned?
Thank you

**Comment by nam31** [comment]
@LingTjal We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Comment by afield1235** [comment]
@nam31 @MaratMussabekov 
 I have this issue as well. We switched from Mobility and Security E3 + Microsoft Business Standard to now Business Premium and 50% of our laptops are having the exacty same check in Issue. Why is this even a problem? Embarrasing.

Can we re-open this??????
