### ISSUE TITLE
Microsoft has changed things?

### ISSUE THREAD

**Issue by GreggHales** [MicrosoftDocs/windows-itpro-docs#909]
Well, looks like the above only applies to version 1703 of Windows 10 perhaps?
I have 1709, and multiple attempts to upgrade to 1803, like a massive number of others worldwide, ends in failure and the dreaded reboot loop.
Tried following the above, but unfortunately, there is no record in Event Viewer in Windows Logs\Application for winsetupdiag02. 
There is however an event 1001 from the source Windows Error Reporting, but unfortunately it takes a slightly different method of writing out the information, which makes it  useless in comparison to the above method, whereby the above simply gives you codes to find quick answers. 
Perhaps Microsoft could update this document to reflect what to look for in the 1709 version of Windows 10?
Will hold off updating clients pc's until I can work out what is going wrong, and feel that this latest update is far more stable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68640934-3744-abdd-8c69-1c01c85ddf9b
* Version Independent ID: 3821be03-0231-2707-452b-78b375cbde1a
* Content: [Windows error reporting - Windows IT Pro](https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-error-reporting#feedback)
* Content Source: [windows/deployment/upgrade/windows-error-reporting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/windows-error-reporting.md)
* Service: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by j0rt3g4** [comment]
#Resolved in #3702

**Comment by mypil** [comment]
@GreggHales - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
