### ISSUE TITLE
These pages need to include some additional details about the setting

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/windows-itpro-docs#9093]
It's great that we can see what setting will be enabled. But what does the setting actually do? What is the end user impact or expected outcome of enabling specific settings? A link to the relevant docs article for each setting would be very helpful, especially since many organization are now interested in moving from GPO to MDM policy settings management via MEM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b1ab2e-1964-5580-7c99-4bd4cd480075
* Version Independent ID: f7b5da46-04cb-3501-65fa-870a3c6f09b8
* Content: [Policy CSP - Defender - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#defender-allowscanningnetworkfiles)
* Content Source: [windows/client-management/mdm/policy-csp-defender.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-defender.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
@SLeuthold Thank you for providing feedback.
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
Thank you for your contribution to make the docs better! Much appreciated!
