### ISSUE TITLE
What must be changed, if you have the newest Version W10 20H2 x64 (AMD)?

### ISSUE THREAD

**Issue by DcPSDcPS** [MicrosoftDocs/windows-itpro-docs#9094]
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c12e9c4a-af05-9ecd-a791-ac89aa43787c
* Version Independent ID: 76517523-a960-c5fb-ce76-2c3efe642f37
* Content: [Windows Defender von Device Guard und Windows Defender Credential Guard - Microsoft 365 Security](https://docs.microsoft.com/de-de/windows/security/identity-protection/credential-guard/dg-readiness-tool)
* Content Source: [windows/security/identity-protection/credential-guard/dg-readiness-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/dg-readiness-tool.md)
* Product: **w10**
* GitHub Login: @SteveSyfuhs
* Microsoft Alias: **stsyfuhs**

**Comment by DcPSDcPS** [comment]
Page https://docs.microsoft.com/de-de/windows/security/identity-protection/credential-guard/dg-readiness-tool
Script

If I tested my version (with an active DG/CG), there was printed a reference to "DG_Readiness.ps1 -Disable" 
Where ist a real reference to this routine? 
Goal: Using Bluestack with hardware-virtualiser is only possible without windows hyper-v (deaktivatet feature, but it seems to work in Background trough DG/DC
Because the machine has many users, working with regedit seems to be a small "worst case".
Thanks

**Comment by MaratMussabekov** [comment]
Hello @DcPSDcPS ,
Have you seen [this](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage) article?

Thank you

**Comment by nam31** [comment]
@DcPSDcPS We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
