### ISSUE TITLE
Input not valid when adding network boundary

### ISSUE THREAD

**Issue by SRE93** [MicrosoftDocs/windows-itpro-docs#9095]
[Enter feedback here]
The article describes the following syntax:
URL <,proxy>|URL <,proxy>|/*AppCompat*/

When I add this like mentioned I receive the following error:
![image](https://user-images.githubusercontent.com/39616319/107208444-dff7c280-6a01-11eb-9f5f-7a0acf27b03b.png)

Could you please update this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ad3f92-24de-5eb5-8454-c72d85737183
* Version Independent ID: 900125eb-31ea-faf3-ac30-7c3d7b30f611
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@SRE93 Is this a test environment where you use Contoso as your domain? I assume it is, otherwise you need to replace Contoso with the domain name that you are using.

**Comment by SRE93** [comment]
No, it isn't. Contoso is just a placeholder, I used the correct domain of us ;)

**Comment by VLG17** [comment]
@SRE93 Could you test it without the comma after URL? (I know the documentation says to use it)

For me it works without comma. Also every example I found online did not use a comma, when not using a proxy:

**Comment by SRE93** [comment]
Without comma it is working, I just mentioned this to update the documentation :)

**Comment by nam31** [comment]
Closing via #9397 
Thank you
