### ISSUE TITLE
Clarification on Task Sequence Variable: DriverGroup001

### ISSUE THREAD

**Issue by amosjeff** [MicrosoftDocs/windows-itpro-docs#9103]
On Step 6: **Create the deployment task sequence**, when setting the Task Sequence Variable, **%Make%**  is not a recognized  Property (When I run the command  **wmic computersystem get /?** , **Make** is NOT one of the properties) I think the correct property that corresponds to Dell Inc. (For a Dell computer) is **%Manufacturer%**.

I submit that it should be `Value: Windows 10 x64\%Manufacturer%\%Model%` instead. I tested this in my environment and it works. Also we typically run Dell hardware. Please advise if I missed something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@amosjeff . i  executed  below command in windows 10  client machine 
**wmic computersystem get /?**

i received  model and  manufacturer  output 
similarly, i  executed  both  below commands and worked fine 
**wmic computersystem get manufacturer**
**wmic computersystem get model**

![Capture02](https://user-images.githubusercontent.com/3296790/107635816-cbc9f480-6c91-11eb-9941-c78373428532.JPG)

**Comment by amosjeff** [comment]
@RAJU2529 , Thanks for the correction. I think the screenshot and some text should also be updated. See images below.

![ms2](https://user-images.githubusercontent.com/10274724/107692327-da9cb100-6c69-11eb-813d-51a06e59c640.JPG)


![ms](https://user-images.githubusercontent.com/10274724/107692341-e1c3bf00-6c69-11eb-9e5b-d62667cc3e05.JPG)

**Comment by MaratMussabekov** [comment]
Hello @amosjeff ,
I believe it shouldn't be changed.
%make% is a built-in MDT variable that matches the "manufacturer" parameter value of **wmic computersystem**.
Dear @greg-lindsay, could you please confirm?

Thank you

**Comment by amosjeff** [comment]
@MaratMussabekov ,

You are right coz now not all my drivers are being loaded after changing it to %Manufacturer%.

**Comment by nam31** [comment]
@amosjeff The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
