### ISSUE TITLE
Windows Update - Dead links

### ISSUE THREAD

**Issue by Shwaffle** [MicrosoftDocs/windows-itpro-docs#9104]
Under _How do I reset Windows Update components?_

The script links are dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
From https://docs.microsoft.com/windows/deployment/update/windows-update-resources#how-do-i-reset-windows-update-components

## How do I reset Windows Update components?

[Reset Windows Update Client settings script](https://gallery.technet.microsoft.com/scriptcenter/Reset-WindowsUpdateps1-e0c5eb78) will completely reset the Windows Update client settings. It has been tested on Windows 7, 8, 10, and Windows Server 2012 R2. It will configure the services and registry keys related to Windows Update for default settings. It will also clean up files related to Windows Update, in addition to BITS related data.

[Reset Windows Update Agent script](https://gallery.technet.microsoft.com/scriptcenter/Reset-Windows-Update-Agent-d824badc) allows you to reset the Windows Update Agent, resolving issues with Windows Update.

***

Note that the script links point to gallery.technet.microsoft.com — a retired site address now redirecting to https://docs.microsoft.com/samples/browse/?redirectedfrom=TechNet-Gallery (**Browse code samples**).

I seem to recall that at least one of the 2 scripts is present on GitHub in an updated form, but I am not sure if that is the solution we want to use for the docs.microsoft.com pages. It would have been better to link the original scripts, if they can be found in the archive pages.

**Comment by illfated** [comment]
From the WayBack Machine / Web Archives:
1. https://web.archive.org/web/20201204152233/https://gallery.technet.microsoft.com/scriptcenter/Reset-Windows-Update-Agent-d824badc (Reset Windows Update Client settings script)
2. https://web.archive.org/web/20210122003227/https://gallery.technet.microsoft.com/scriptcenter/Reset-WindowsUpdateps1-e0c5eb78 (Reset Windows Update Agent script)

**Comment by illfated** [comment]
See also ticket #9129 regarding the same issue.

**Comment by jaimeo** [comment]
We are working on new hosting locations right now and will update the article once they're in place.

**Comment by jaimeo** [comment]
Working on alternate hosting solution for these.

**Comment by illfated** [comment]
(ref. #4930, #9195, #9216, #9237, #9218, #9287, #9304, #9315)

**Comment by jaimeo** [comment]
Per advice of WU SMEs, that section of the article was rewritten to preclude the need for the scripts altogether. https://github.com/MicrosoftDocs/windows-docs-pr/pull/4920

**Comment by jaimeo** [comment]
All related issues can be closed for the same reason.
