### ISSUE TITLE
Broken link https://support.microsoft.com/en-us/office/a34a400a-51d5-f2a1-c8c0-7a6c9c49cb78

### ISSUE THREAD

**Issue by beaucoup1980** [MicrosoftDocs/windows-itpro-docs#9106]
Link: https://support.microsoft.com/en-us/office/a34a400a-51d5-f2a1-c8c0-7a6c9c49cb78 Guidelines for enabling smart card logon with third-party certification authorities.

is broken, goes to an Error - Office.com page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f64c6e7-4002-fe69-b8a0-aa3539949ee6
* Version Independent ID: 3e71c3a7-6654-d31a-37eb-7cc84d0b8a72
* Content: [Windows Hello for Business Deployment Known Issues - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-issues)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-deployment-issues.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-deployment-issues.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by RAJU2529** [comment]
@beaucoup1980 .   Thanks for pointing out. I will fix

**Comment by illfated** [comment]
The correct link (https://docs.microsoft.com/troubleshoot/windows-server/windows-security/enabling-smart-card-logon-third-party-certification-authorities) is available in the document (https://docs.microsoft.com/windows/security/identity-protection/hello-for-business/hello-deployment-issues) and it works as expected & intended.

**Comment by illfated** [comment]
#please-close
