### ISSUE TITLE
Methods on WMI providers.

### ISSUE THREAD

**Issue by dfconroy** [MicrosoftDocs/windows-itpro-docs#911]
Is it possible to execute a WMI method from MDM? I'm trying to disable/enable an Adapter using the Win32_NetworkAdapter methods and get a 406. 

<Exec>
         <CmdID>disable</CmdID>
         <Item>
            <Target>
               <LocURI>./cimV2/Win32_NetworkAdapter/Win32_NetworkAdapter.DeviceID%3D%221%22/Disable</LocURI>
            </Target>
         </Item>
      </Exec>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04405438-4b80-b996-3421-a831353be2f7
* Version Independent ID: 5c0bf4d4-fa8b-85d4-41dd-3267534f3217
* Content: [WMI providers supported in Windows 10](https://docs.microsoft.com/en-us/windows/client-management/mdm/wmi-providers-supported-in-windows)
* Content Source: [windows/client-management/mdm/wmi-providers-supported-in-windows.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/wmi-providers-supported-in-windows.md)
* Service: **w10**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
Hello @dfconroy Win32_NetworkAdapter class only supports data reading. Enabling / Disabling is the part of NetworkAdapter Configuration which is not supported as of now. Please see https://docs.microsoft.com/en-us/windows/client-management/mdm/wmi-providers-supported-in-windows#win32-wmi-classes

Thanks.

**Comment by mypil** [comment]
@dfconroy - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
