### ISSUE TITLE
Missing line breaks in "Saved Windows Credentials Protected"

### ISSUE THREAD

**Issue by takondo** [MicrosoftDocs/windows-itpro-docs#9114]
I think there should be line breaks for each hyphen in the later half of "Saved Windows Credentials Protected". Here's what we have now:

============
The following considerations apply to the Windows Defender Credential Guard protections for Credential Manager: - Windows credentials saved by Remote Desktop Client cannot be sent to a remote host. Attempts to use saved Windows credentials fail, displaying the error message "Logon attempt failed." - Applications that extract Windows credentials fail. - When credentials are backed up from a PC that has Windows Defender Credential Guard enabled, the Windows credentials cannot be restored. If you need to back up your credentials, you must do this before you enable Windows Defender Credential Guard. Otherwise, you cannot restore those credentials.
============

This is what it should look like?

===========
The following considerations apply to the Windows Defender Credential Guard protections for Credential Manager:
 - Windows credentials saved by Remote Desktop Client cannot be sent to a remote host. Attempts to use saved Windows credentials fail, displaying the error message "Logon attempt failed."
 - Applications that extract Windows credentials fail. 
 - When credentials are backed up from a PC that has Windows Defender Credential Guard enabled, the Windows credentials cannot be restored. If you need to back up your credentials, you must do this before you enable Windows Defender Credential Guard. Otherwise, you cannot restore those credentials.
==========

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b1f3ae7-79ed-fc75-4f36-ad5537d5f928
* Version Independent ID: bdd1e434-0825-7220-9e97-ee4cdd10b897
* Content: [Advice while using Windows Defender Credential Guard (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-considerations)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-considerations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-considerations.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
Closing via #9120 
Thanks
