### ISSUE TITLE
Plist isn't in the content no more that you download from MS

### ISSUE THREAD

**Issue by Erziram** [MicrosoftDocs/windows-itpro-docs#9115]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f791dc07-b2c6-3003-a829-cd1ec03a2918
* Version Independent ID: 2c53adbc-600f-60b2-e8b2-b907335f4862
* Content: [Set up the Microsoft Defender ATP for macOS policies in Jamf Pro - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by Erziram** [comment]
Plist isn't in the content no more that you download from MS, instead, there is a Python script which is now not explained in these steps

**Comment by VLG17** [comment]
Details about the script are referenced in the Defender Security Center Page. I think adding a note about that in the article could help, what do you think?

![image](https://user-images.githubusercontent.com/41186174/110614755-53c0f280-819b-11eb-8134-2ea9385aa3bb.png)

**Comment by VLG17** [comment]
@Erziram I have tested and if you follow the steps described in the article, meaning Deployment method: Mobile Device Management, the onboarding package contains the .plist file.

The python file is contained in the onboarding package that is generated when you choose Deployment method: Local script, but that's not what the article describes.

**Comment by nam31** [comment]
@Erziram Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
