### ISSUE TITLE
Add instructions or download/tool for getting file hashes

### ISSUE THREAD

**Issue by beeeeswax** [MicrosoftDocs/windows-itpro-docs#9117]
It would be nice if some guidance were given on how to get the hashes for files that need to be added to the allow list.  Or better yet the ability to browse for a file from the ATP console to obtain a hash, although I accept that's probably out of scope for reports on this git.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39750ecf-cd05-d2ab-c20c-0c31544d7a3f
* Version Independent ID: 399a3897-85a2-1e0f-1e5d-56e4510a55c6
* Content: [Create indicators for files - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/indicator-file)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/indicator-file.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/indicator-file.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@beeeeswax . I think you can use third party application,vto get file hash value.

**Comment by nam31** [comment]
@beeeeswax, Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)
Thank you.

**Comment by illfated** [comment]
@beeeeswax : I would also suggest using the Feedback Hub (OS client or web page) to post that issue to make the developers more aware of this request.
