### ISSUE TITLE
About Multi-factor authentication issue

### ISSUE THREAD

**Issue by Castermeek** [MicrosoftDocs/windows-itpro-docs#9127]
[Enter feedback here]
It says as issue has been identified with HAADJ and MFA.
I have tried on 1703, 1903 and 2004.
I did not see any issue that user with MFA enabled and logon to HAADJ devices.

Could anyone explain what the issue is?

Thank you.
-chiyao-

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation#multi-factor-authentication)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
Hello,

Looks like this question can best be answered via relevant [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channels. 

Please consider checking with [Microsoft Community](https://answers.microsoft.com/en-us/windows/forum/windows_10) or [contacting support](https://support.microsoft.com/contactus) for your problem; The issues section of this repository is for content fixes in documentation.

If you feel that the associated article also needs to be updated for any reason feel free to re-open this issue or [contribute with a pull request](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/CONTRIBUTING.md).

Thank you.
