### ISSUE TITLE
Script link not working

### ISSUE THREAD

**Issue by markstan** [MicrosoftDocs/windows-itpro-docs#9129]
Is there an alternative download site for the script?  Gallery was recently decommissioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Working on it. We'll put them on PowerShell Gallery or in a particular GitHub repo for that purpose, as appropriate.

**Comment by RAJU2529** [comment]
@jaimeo . I am waiting to see new links .

**Comment by jaimeo** [comment]
@RAJU2529 you don't need to worry about it. I'll update the article when we get the scripts set up.

**Comment by illfated** [comment]
See also ticket #9129 regarding the same issue.

**Comment by illfated** [comment]
Duplicate of #9104

#please-close
