### ISSUE TITLE
Invalid link group policy tech center. 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#9132]
Just now I checked link of group policy tech center, which is entirely different and description about group policy tech center  is not needed  because , group policy tech center hosted by technet is removed.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5413195-c0e2-99e4-5d82-6bffdcbbddb9
* Version Independent ID: b8cef753-139b-0098-ed30-63cca8d5b8b9
* Content: [Available Microsoft Defender SmartScreen Group Policy and mobile device management (MDM) settings (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-available-settings)
* Content Source: [windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-available-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-available-settings.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
PR #9178 is ready for final review & merge.

**Comment by nam31** [comment]
Closing via #9178 
Thank you
