### ISSUE TITLE
Windows Education E3 & Shared Device Activation

### ISSUE THREAD

**Issue by sumtnk** [MicrosoftDocs/windows-itpro-docs#9133]
Hi, 

According to terms of use institutions with Windows Education A3/A5 assigned to all Education Qualified Users are licensed to run Windows 10 Education or Windows 10 Enterprise on any shared device with a qualifying operating system within the organisation

It is not clear how Activation works on Shared Devices. Does it activate against the first user that logs in and if so, does this take up a license from the five devices which can be upgraded for each user license?

Thanks, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by MaratMussabekov** [comment]
Hello,
**Does it activate against the first user that logs in** - no, the computer must be activated using Windows 10 Pro Education. Then, when users with assigned A3/A5 license logs in, they can use A3/A5 features.
Thank you

**Comment by sumtnk** [comment]
Hi,

Okay so the computer activates using Win 10 Pro Edu, but then when a user assigned with A3/A5 logs in it also does an edition upgrade to Win 10 Edu and therefore takes one of five device assignments they have for this? I can't see how this would work in an environment where there are shared devices like a lab?

Thank you,

**Comment by MaratMussabekov** [comment]
Hello,
I suppose the question is, will the limit of allowed computers run out in a scenario when students use computers randomly? - no, it will not. The limit of five devices doesn't mean that student can log in to five devices only, it means they cannot be logged in to more that five computers at the same time.

These licenses are user-based, not device-based. For example, you have 10 shared devices in the lab. Students use them randomly. Student A logged on Computer 1. They entered their credentials and can use A3/A5 features. Student B logged on Computer 1 after that. They also prompted for credentials. If they also have A3/A5 license assigned, they can use A3/A5 features as well. If you see their account on Microsoft 365 portal, both will have Computer 1 in the listed devices. Let's imagine Student A worked on five different computers. When they log in to the sixth device, the first computer will be simply removed from the list. 

Thank you

**Comment by sumtnk** [comment]
Thank you, that's very helpful and provides much more clarity. 

The article says "Up to five devices can be upgraded for each user license." which led to the confusion, it should state "Up to five devices can be upgraded for each user license at the same time.".

**Comment by nam31** [comment]
Closing via #9290 
Thank you
