### ISSUE TITLE
Typo in article https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-machines-security-baseline

### ISSUE THREAD

**Issue by darolt1** [MicrosoftDocs/windows-itpro-docs#9135]
There is a typo with this:
365 Microsoft 365 Defender

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2246e9c-193b-a110-ca52-2110a6e63631
* Version Independent ID: 7328d4a4-1944-c199-db72-a7e3cd350ae9
* Content: [Increase compliance to the Microsoft Defender ATP security baseline - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-machines-security-baseline)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-machines-security-baseline.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-machines-security-baseline.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by RAJU2529** [comment]
@darolt1 . Thanks for pointing out. I am fixing  now.

**Comment by RAJU2529** [comment]
@e0i . I could not able to edit in content source site,  but I editted in other site . , luckily I was successfully editted.

**Comment by darolt1** [comment]
Thanks!

**Comment by denisebmsft** [comment]
This is fixed, and the updates will show up on the live site later today. Thank you so much for letting us know about this!

**Comment by darolt1** [comment]
Great - thanks!
