### ISSUE TITLE
AppData/Roaming redirection is removed.

### ISSUE THREAD

**Issue by cas77** [MicrosoftDocs/windows-itpro-docs#914]
In Windows 10, version 1803 the AppData/Roaming is not redirectable any more.
The 'Location"' tab is gone. The  Folder Redirection Group Policy for the AppData/Roaming doesn't function and alerts that "The folder is not redirectable".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c274f8df-31da-f58a-36af-dc7eb6ace762
* Version Independent ID: 0e33637d-e094-edbc-04f9-e8d5e6c642c6
* Content: [Windows 10, version 1803 - Features that have been removed](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-1803-removed-features)
* Content Source: [windows/deployment/planning/windows-10-1803-removed-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-10-1803-removed-features.md)
* Service: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by deucalion** [comment]
It would've been nice if MSFT had communicated that. We're using this feature in our company and are struggling to have that update not kill us and our profiles by blocking 1803 for now.

Words fail me.

**Comment by cas77** [comment]
Hi,
Microsoft Support has confirmed that it is a bug. A fix is coming.
