### ISSUE TITLE
old product name - Azure ATP

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#9142]
Azure ATP is now called Defender for Identity, please update the text on this page. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d99de0-789d-3c71-4bd9-f45e62f82a7b
* Version Independent ID: d56d09f0-1f9a-563e-fee0-142bda27a99b
* Content: [Configure advanced features in Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/advanced-features)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/advanced-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/advanced-features.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Should be fairly easy, only 3 visible uses on that page. Any other changes you would recommend at the same time?

**Comment by illfated** [comment]
PR #9143 is now ready for review, comments & suggestions. Feel free to leave a comment or suggestions for further improvements.
