### ISSUE TITLE
Update troubleshooting Resolution Proceedures missing 0xCA codes

### ISSUE THREAD

**Issue by td47** [MicrosoftDocs/windows-itpro-docs#9144]
[Enter feedback here]
Windows 10 Insiders (and others) might see 0xCA errors codes (e.g. 0xCA00A005) and have no information to know how to proceed. Please update the referenced document, to help Insiders, and others who are testing updates for you, and to better support the technical and support community.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 528014e0-02e5-2d77-a229-4895731bb872
* Version Independent ID: 4f46b620-e345-c9e4-70fa-ae4f5a8e48b9
* Content: [Resolution procedures - Windows IT Pro - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/upgrade/resolution-procedures?source=docs)
* Content Source: [windows/deployment/upgrade/resolution-procedures.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/resolution-procedures.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
I am checking the depth of information we have about this type of error.

**Comment by greg-lindsay** [comment]
0xCA00A005 means DPX_E_CONTAINER_UNSUPPORTED_TYPE
I believe that DPX stands for Delta Package Expander.
I'm still looking for more information.

**Comment by greg-lindsay** [comment]
The error usually means the header of a file is corrupted. Supported containers for DPX are CAB and PSF files. One of these files is likely corrupt. Searching the logs should reveal which file is the problem.

**Comment by greg-lindsay** [comment]
Would it be possible to obtain the log file? Either setuperr or setupact should have the line with the 0xCA00A005 code.

**Comment by greg-lindsay** [comment]
Closing this issue for now. If you have a log file please add it to this issue.

**Comment by td47** [comment]
@greg-lindsay Apologies for not being able to send you the users log file. This initial report was from a colleague in the private FB group "Windows Insiders Scoop Fans UK", who reported that one of his Insiders updates created this error. It seems that a new later update had overcome the issue and overwritten the logs, 
However, the fact that this issue occurred while using a Microsoft Update, and the resultant error was NOT documented in the "Troubleshooting Resolution Procedures" latest official document, was the whole reason for requesting this update. After all, it is Microsoft code that is creating this error, and if tech-admins need to diagnose what to do, and how best to check and remediate the situation, it would be best to at least have supporting documentation keep abreast of upcoming code releases, and the error codes they are likely to see going forward.
