### ISSUE TITLE
"Inaccessible Boot Device" from gaps in GPT entries

### ISSUE THREAD

**Issue by tbrownaw** [MicrosoftDocs/windows-itpro-docs#9145]
One cause of "Inaccessible Boot Device" which I do not see listed here is that it will occur on GPT disks if there is a blank GPT entry before the entry for the boot partition. Which I found after using non-Windows tools to rearrange partitions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 388514ac-6488-384c-fb86-e8dfd3970a28
* Version Independent ID: 7cd69358-f4bc-67a2-ba27-ea20f0946e32
* Content: [Advanced advice for Stop error 7B, Inaccessible_Boot_Device - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-inaccessible-boot-device)
* Content Source: [windows/client-management/troubleshoot-inaccessible-boot-device.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/troubleshoot-inaccessible-boot-device.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
Closing via #9220 
Thank you
