### ISSUE TITLE
Missing settings in policy?

### ISSUE THREAD

**Issue by derekharkin** [MicrosoftDocs/windows-itpro-docs#9147]
Some settings that are not in the current Windows versions (20H2). 
There appears to be no settings around dump or diagnostic log collection under 
Group Policy: Computer Configuration > Administrative Templates > Windows Components > Data Collection and Preview Builds > 
No settings for: 
- Limit Dump Collection
- Limit Diagnostic Log Collection

![1](https://user-images.githubusercontent.com/4546689/107961329-a8f35500-6f9d-11eb-8a82-acba6345ce9d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 345f01ee-e894-106b-d405-f05c41b69940
* Version Independent ID: a324f689-3229-9ccd-a844-6064820601d8
* Content: [Changes to Windows diagnostic data collection - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/changes-to-windows-diagnostic-data-collection)
* Content Source: [windows/privacy/changes-to-windows-diagnostic-data-collection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/changes-to-windows-diagnostic-data-collection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **siosulli**

**Comment by derekharkin** [comment]
Also neither setting seems to be documented in the CSP

https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-system

**Comment by RAJU2529** [comment]
@derekharkin. Thanks for pointing out, I sorted out this issue. Just now i  got updated admx templates which available in the release preview.

**Comment by joinimran** [comment]
@RAJU2529 - Can you please share with me the link for this ADMX template?

**Comment by RAJU2529** [comment]
@joinimran , Microsoft does not released updated admx files , but I got data collection files from windows insider preview  21313  iso file.

if  copy this  **datacollection.admx**   and  **datacollection.adml**  to  windows 10  20h2  OS  ,  you will get  the following  errror when you run **SFC /SCANNOW** with admin rights.

[DataCollection.zip](https://github.com/MicrosoftDocs/windows-itpro-docs/files/6059070/DataCollection.zip)

**Comment by joinimran** [comment]
@RAJU2529 This means this will be available in 21H1 or 21H2 version of Windows?

**Comment by RAJU2529** [comment]
@joinimran . windows insider preview  21313  iso.
it might will come in either 21H1 or 21H2

**Comment by siosulli** [comment]
@derekharkin I'm closing this ticket out now as I from what I can see the settings are available for the content documented at https://docs.microsoft.com/en-us/windows/privacy/changes-to-windows-diagnostic-data-collection

If this is incorrect please re-open the ticket with details.
