### ISSUE TITLE
This document needs clarification

### ISSUE THREAD

**Issue by Clickbaitcake** [MicrosoftDocs/windows-itpro-docs#9148]
It has not been made clear here that the methods described in this page also apply to Server 2019. It should be made obvious that the Windows 10 deployment methods are the same on Server 2019. 

The guide is confusing because there is another section titled "Onboard Windows servers" people will gravitate there when looking for Server 2019 onboarding instructions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ff9ad1c-b552-4325-b8a6-5c1e472771dc
* Version Independent ID: 0c014427-0fa5-9977-4eb9-a81c1865ad02
* Content: [Onboarding tools and methods for Windows 10 devices - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by adirdidi** [comment]
I will clarify the reference on the servers page, to indicate that users should follow the same Windows 10 instructions.

**Comment by adirdidi** [comment]
The change will go live around 11 AM PST tomorrow.

**Comment by illfated** [comment]
Thank you for the quick update & closing comment. 👍🏻

**Comment by Clickbaitcake** [comment]
A similar issue is present in: 
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9149
