### ISSUE TITLE
Applicability is wrong

### ISSUE THREAD

**Issue by Clickbaitcake** [MicrosoftDocs/windows-itpro-docs#9149]
This document says this:

> Applies to:
>     Windows Server 2008 R2 SP1
>     Windows Server 2012 R2
>     Windows Server 2016
>     Windows Server (SAC) version 1803 and later
>     Windows Server 2019 and later
>     Windows Server 2019 core edition
>     Microsoft Defender for Endpoint

This information is incorrect. The steps outlined in this document do not apply to `Windows Server 2019 and later Windows Server 2019 core edition`  The steps outlined here are for 2019:  https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints

Please can the document be changed to focus only on earlier versions of Windows server? Please point people back towards this page for Server 2019 deployment: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints

This issue kind of relates to this similar issue:
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9148

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4ed2b3-0390-4d53-2450-14995ee8b0b0
* Version Independent ID: 91b5bb3e-55d4-6a8e-c16d-094f15c28ee7
* Content: [Onboard Windows servers to the Microsoft Defender ATP service - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by adirdidi** [comment]
Resolved as part of the other issue.
