### ISSUE TITLE
Provisioning Lock

### ISSUE THREAD

**Issue by NigelbrownIBM** [MicrosoftDocs/windows-itpro-docs#915]
How can we enable locking the device during provisioning during?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c880203c-6a5b-28e7-c74d-152890baa955
* Version Independent ID: 59c9eb13-dd44-358a-130d-ca1e020573ba
* Content: [What's new in Windows 10, version 1803](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1803)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1803.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1803.md)
* Service: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by j0rt3g4** [comment]
You'd need to do the device enrolled into Intune 1st as the article explains it.

**Comment by j0rt3g4** [comment]
#3710 substitute #3709 because this last one was mixed up with another issue.

**Comment by mypil** [comment]
@NigelbrownIBM - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
