### ISSUE TITLE
Are any exclusions required for Defender to live happily?

### ISSUE THREAD

**Issue by Clickbaitcake** [MicrosoftDocs/windows-itpro-docs#9150]
If another antivirus software is installed like CarbonBlack or CrowdStrike, do the Defender files and paths need to be excluded from in these other products? For example: CarbonBlack could tamper, touch and break Defender files in C:\SYSTEM\DEFENDER (Not the correct path, just an assumption for examples sake)

If Defender does in-fact require exclusion from other products, please can these exclusions be listed? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b88aee4-6727-fa98-1180-29708eea027e
* Version Independent ID: 374c671b-b21c-6eac-d887-892491357eb2
* Content: [Microsoft Defender Antivirus compatibility with other security products - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by beerisgood** [comment]
This isn't Defender fault then. Third party tools need handle this correctly.

Or stay with Defender and live without such nonsense problems.

**Comment by Clickbaitcake** [comment]
> 
> 
> This isn't Defender fault then. Third party tools need handle this correctly.

Its not a fault at all, but if Defender requires other products do not touch its files then it must be documented. All other vendors do this. 

> Or stay with Defender and live without such nonsense problems.
Thats great in practice but some folks have a mandate to run certain anti-virus solutions, its silly and yes maybe nonsense but a real use case none the less. Again, if Defender needs exclusions to work correctly with other vendors, it needs to be documented.

**Comment by MaratMussabekov** [comment]
Hello @Clickbaitcake ,
**If another antivirus software is installed like CarbonBlack or CrowdStrike, do the Defender files and paths need to be excluded from in these other products?** - no, they don't. Microsoft Defender Antivirus files are considered as system files and are not touched by third-party antiviruses.
However, you should remember that Windows Server 2016 doesn't support passive mode, and in this case you should remove Defender Antivirus prior to installation of the third-party antivirus.

Thank you
