### ISSUE TITLE
Key-trust or certificate-trust?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/windows-itpro-docs#9155]
This page confuses me. Too many ifs and whens. At the top it states "applies to key-trust". 
Next is written "The key-trust model needs Windows Server 2016 domain controllers, which configure the key registration permissions **automatically**; however, the certificate-trust model does not and requires you to add the permissions manually."

We have only Server2016 DCs. So I skip the section "Configure Permissions for Key Synchronization".
Now, do I need to add the AAD Connect service account to  **KeyAdmins** or **KeyCredential Admins** (we only have the first one in our Users container and it is spelled **Key Admins**), or is that not necessary?

We have no problems, except that when a user changes the HfB PIN, they need to lock/unlock their workstation and stay signed in for about half an hour. I assume this is because the attribute msDS-KeyCredentialLink needs to be updated.
But we have given read/write all attributes to the local group the service account is a member of, on the OU where our users accounts are +all descendant objects. So maybe we have solved this a different way.
Anyway, to me this document is unclear: _does_ or _does it not_ apply to key-trust and Server2016 DCs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47038bf5-6fcf-46be-3e72-49bd40be3d60
* Version Independent ID: 7e850cee-96cc-3902-6c5f-bebaa836fb24
* Content: [Configure Hybrid Windows Hello for Business Directory Synch - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-dir-sync)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-dir-sync.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-dir-sync.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by MaratMussabekov** [comment]
Hello @andrePKI ,
**At the top it states "applies to key-trust"**. - it is incorrect. Article applies to Certificate Trust deployments

**Now, do I need to add the AAD Connect service account to KeyAdmins or KeyCredential Admins (we only have the first one in our Users container and it is spelled Key Admins), or is that not necessary?** - yes it is necessary.

As it is stated in note: "If you already have a Windows Server 2016 domain controller in your domain, you can skip Configure Permissions for Key Synchronization. In this case, you should use the pre-created group **_KeyAdmins in step 3 of the "Group Memberships for the Azure AD Connect Service Account" section of this article._**"

You need to add AAD Connect service account to this group to allow it to manage keys. If your are using WS2016, you need to use KeyAdmins group. If you do not have WS2016, you do not have KeyAdmins group, you need to create an alternative group (here it was named KeyCredential Admins) and add service account to it.

Thank you

**Comment by nam31** [comment]
Closing via #9240 
Thank you
