### ISSUE TITLE
What is the UWP API of the "Bluetooth/LocalDeviceName"?

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/windows-itpro-docs#916]
I want the space character in the Bluetooth name, like: ABC 5678, the Windows 10 iot core only support set the device name which is no allowed space character. I can set the Bluetooth local name with space character use by provisioning package. But the provisioning package set the fixed Bluetooth local name, is there a UWP API to change the Bluetooth local device name?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9596a57e-365e-2809-1f8d-8aebbda5bc36
* Version Independent ID: 4a287709-2466-93eb-cc2f-9f7566277abb
* Content: [Policy CSP - Bluetooth](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-bluetooth)
* Content Source: [windows/client-management/mdm/policy-csp-bluetooth.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-bluetooth.md)
* Service: **w10**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
Hello, @moyanming Thank you for your query here. Please note that you can use _ in a replacement of spacebar. Additionally, this document is related to Windows all version other than Windows IoT core. You can request this feature for Windows 10 IoT using the user's voice channel. 

@mypil Can further guide you on how to request for the new feature using user voice channel. 

Thanks.

**Comment by mypil** [comment]
@moyanming - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by moyanming** [comment]
> Hello, @moyanming Thank you for your query here. Please note that you can use _ in a replacement of spacebar. Additionally, this document is related to Windows all version other than Windows IoT core. You can request this feature for Windows 10 IoT using the user's voice channel.
> 
> @mypil Can further guide you on how to request for the new feature using user voice channel.
> 
> Thanks.

Hi @joinimran ,
The name of the Bluetooth can be used for all version of the Windows 10 and includes Windows 10 IoT. So, there is no API can be used for all version of the Windows 10.
I can change the Bluetooth name to "ABC 1234" in the provisioning package, but this name is fixed. So I need a API can do this.

**Comment by joinimran** [comment]
@moyanming Can you please share any screenshot that will further help me to understand this more clearly and then maybe I will be in much better situation to help/guide you regarding your query.

Thanks.

**Comment by mypil** [comment]
@moyanming - We would like to follow up with you. Can you please respond to the question of joinimran?

Thank you,

**Comment by mypil** [comment]
@moyanming - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by moyanming** [comment]
> @moyanming Can you please share any screenshot that will further help me to understand this more clearly and then maybe I will be in much better situation to help/guide you regarding your query.
> 
> Thanks.

Hi @joinimran @mypil ,
Please see the picture below. [I can set](https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/add-a-provisioning-package-to-an-image) the "LocalDeviceName" of the "Bluetooth" by use “Windows Imaging and Configuration Designer” to "ABC 5678". But the Bluetooth name is fixed to "ABC 5678" for every IoT devices. As we have known that different IoT device should have a different Bluetooth name. So, is there API can be used to change the name of the Bluetooth?
![QQ截图20190502211742](https://user-images.githubusercontent.com/13234209/57269346-afab2380-70b9-11e9-9a71-2203e9255699.jpg)
