### ISSUE TITLE
Would like clarification on this doc

### ISSUE THREAD

**Issue by ChrisVanY** [MicrosoftDocs/windows-itpro-docs#9161]
If an admin misses assigning a license to a mac user and deploys the agent silently to that user with Intune or Jamf does the end user get a prompt after/during install regarding the lack of license?  What about if they open the app?  It appears to say that the end user will only get this prompt only if the agent is installed manually and no license is found for the user.  Would be helpful to clarify the experience.  Thank you!  Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 182834da-b37e-3918-c5bd-a738499bbf36
* Version Independent ID: a0daf8b8-e8c7-c2dd-b722-4038cb1535b3
* Content: [Troubleshoot license issues for Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-support-license#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-support-license.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-support-license.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
( ref. https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4866 )

**Comment by nam31** [comment]
Closing via MicrosoftDocs/microsoft-365-docs#4866
