### ISSUE TITLE
You will need to stop the Cryptographic Service before you can delete or rename the Catroot2 folder.

### ISSUE THREAD

**Issue by amirsoofi** [MicrosoftDocs/windows-itpro-docs#9167]
In section 2 add:
net stop cryptsvc

So that in section 4a, this line succeeds:
ren %systemroot%\System32\Catroot2 Catroot2.bak

Otherwise you will see "access denied".

Reference:
https://answers.microsoft.com/en-us/windows/forum/all/access-denied-on-open-commands/2d31ce25-46a7-4ba0-838d-5b842e9991fa

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources#reset-windows-update-components-manually)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment]
@amirsoofi . Thanks for pointing out. I checked  some  commands also, there are some mistakes in lines, i will fix  it very soon.
Thanking you

**Comment by illfated** [comment]
PR #9168 is now merged. This issue ticket should be ready for closing.

#please-close
