### ISSUE TITLE
Small error in poweshell script.

### ISSUE THREAD

**Issue by PaulSIsaac** [MicrosoftDocs/windows-itpro-docs#917]
There is a small error in the multi to one line script:
$path="file path"
(Get-Content $path -Raw).Replace("'r'n","") | Set-Content $path -Force

'r'n should be `r`n

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634fceac-5b42-aea1-5f0d-fb58ad0a9f36
* Version Independent ID: aae4e148-f14d-ba03-2824-e2fff6a7185c
* Content: [ADMXIngestion (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/wcd/wcd-admxingestion)
* Content Source: [windows/configuration/wcd/wcd-admxingestion.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/wcd/wcd-admxingestion.md)
* Service: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
Thanks for pointing out the problem, @PaulSIsaac  -- I checked with the engineer, who tested it and found that correct version is: (Get-Content $admxFile -Raw).Replace("`r`n","") | Set-Content $admxFile -Force

Note the change from $path to $admxFile . Also, the punctuation for r and n are backticks, not the single quote I had previously. The topic will be updated today.
