### ISSUE TITLE
Autopilot enrollment stop working after build 2004

### ISSUE THREAD

**Issue by nvovka1** [MicrosoftDocs/windows-itpro-docs#9170]
We are 3-d party MDM vendor and use on-premise application. 
Before build 2004 enrollment was working for more then 2 years. But with same environment same device same Azure tenant and application only different build version. It dosn't work starting from 2004.
Profile is installed on device, device added to tenant but on profile overview it show Sync could not be initiated  0x80072f0c

Any ideas is it a bug in new build or something was changed in enrollment profile?

**Comment by RAJU2529** [comment]
@nvovka1   Which article are you referring to?

**Comment by nvovka1** [comment]
@RAJU2529 
https://docs.microsoft.com/en-us/windows/client-management/mdm/azure-active-directory-integration-with-mdm

**Comment by RAJU2529** [comment]
@nvovka1 , Sorry, i don't have knowledge about Autopilot, so wait for few days, Autopilot expert users will answer your queries.

**Comment by nvovka1** [comment]
@RAJU2529 
I am not sure that it is only Autopilot could be issue
I try to google error 0x80072f0c and in next article it say some issue with certificate
https://docs.microsoft.com/en-us/windows/win32/api/bits2_5/nf-bits2_5-ibackgroundcopyjobhttpoptions-setclientcertificatebyname

On our discovery svc we use next article to enroll device
https://docs.microsoft.com/en-us/windows/client-management/mdm/on-premise-authentication-device-enrollment
https://docs.microsoft.com/en-us/windows/client-management/mdm/certificate-authentication-device-enrollment

Maybe issue could be somewhere in certificate, but the flow used same as it worked with builds before 2004

**Comment by e0i** [comment]
@nvovka1 

It seems that your question has been answered by the community.

The issues section of this GitHub repository is used for documentation feedback.

Should you have any further issues similar to this one, please consider opening a product support ticket here:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Feel free to re-open this issue if you feel that there are further suggestions to improve the documentation itself.

Thank you for providing feedback.

**Comment by nvovka1** [comment]
@e0i 
1. It was not answered
2. I was in discussing this issue with Microsoft support since October 2020 and at the end they advice to post it here maybe developer can help me.

**Comment by illfated** [comment]
@e0i : Would you be able to recommend the best way to get in touch with the developers regarding this case, which seems not to have been resolved by contacting Microsoft Support?
