### ISSUE TITLE
Layout issue 

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/windows-itpro-docs#9174]
The note after step 4 extends into the text including step 5 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9dae9da-eaf0-c209-7c65-be8d2c1ada12
* Version Independent ID: 28b6788d-7982-23c2-5f19-f80690ebc0ce
* Content: [Pin Reset - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by RAJU2529** [comment]
@andrePKI . Thanks for pointing out. I  am trying to fix it now. Thanking you.

**Comment by illfated** [comment]
PR #9175 is ready for final review & merge.

**Comment by illfated** [comment]
PR #9175 is now merged and the content change should be live within the next day or so, unless there is any issues publishing the updated content.
