### ISSUE TITLE
Include settings for Warn mode in enabling ASR settings

### ISSUE THREAD

**Issue by jsyfib** [MicrosoftDocs/windows-itpro-docs#9176]
Please add the new Warn Mode ASR option to the setting page.  It's unclear to me whether Warn Mode would be setting option 3 when enabled via GPO or what the setting would be when configured via PoSH.

Warn Mode: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction#warn-mode-for-users

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4144ff8c-3d92-d2d7-27ad-4a37843a1008
* Version Independent ID: 43cc32fc-6e2f-5c30-b758-666a53c0052b
* Content: [Enable attack surface reduction rules - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/enable-attack-surface-reduction)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/enable-attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/enable-attack-surface-reduction.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Hi @jsyfib, thanks for pointing this out! I'll work on getting the doc updated.

**Comment by e0i** [comment]
Closing because the article now lives in another repository,

https://github.com/MicrosoftDocs/microsoft-365-docs/commits/public/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md

Thanks
