### ISSUE TITLE
Deployment for Linux Windows defender is too complicated [copied from #8757]

### ISSUE THREAD

**Issue by eturnersumi** [MicrosoftDocs/windows-itpro-docs#9177]
Customers struggle with following along this documentation to deploy Windows Defender for Linux. Are there plans to simplify the deployment steps?

Ex. An Admin that's not an expert with Linux devices may not know to turn on/allow updates in order to download ATP when receiving the below error message. A comprehensive end to end experience for what is required would ease some of the difficulty faced with this deployment. 

**Error message**: _"Unable to correct problems, you have help broken packages"_ when running [sudo apt-get install mdatp] 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2197cba-30ac-1749-e25a-6f39c9ee9d20
* Version Independent ID: bcd14f13-ab59-8e69-5c83-42fee6e51f87
* Content: [Deploy Microsoft Defender ATP for Linux manually - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp

**Comment by konstruktoid** [comment]
Hi @eturnersumi, which deployment steps are you referring to and can you include a more comprehensive log?

**Comment by eturnersumi** [comment]
@jesspent can you chime in here?

**Comment by MaratMussabekov** [comment]
Hello @eturnersumi , 
this error may mean that the package dependencies cannot be installed. Please make sure that all prerequisites described [here](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide) are met.

Also run `dpkg --get-selections | grep hold` to check whether some of the packages on your system are held

Thank you
