### ISSUE TITLE
Does the cache expire?

### ISSUE THREAD

**Issue by git14** [MicrosoftDocs/windows-itpro-docs#9182]
Does the logon cache expire? Can the cached credentials be used indefinitely if the computer cannot reach a domain controller?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef720207-c5e6-182e-8a34-361244c45641
* Version Independent ID: 4591df7c-e474-9b85-7c09-ce572a66a0a3
* Content: [Interactive logon Number of previous logons to cache (in case domain controller is not available) (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-number-of-previous-logons-to-cache-in-case-domain-controller-is-not-available)
* Content Source: [windows/security/threat-protection/security-policy-settings/interactive-logon-number-of-previous-logons-to-cache-in-case-domain-controller-is-not-available.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/interactive-logon-number-of-previous-logons-to-cache-in-case-domain-controller-is-not-available.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@git14 The cached credentials don't expire. 

They can get overwritten though, as described in the article. Also, it's not recommended to use this policy.

> The value of this policy setting indicates the number of users whose logon information the server caches locally. If the value is 10, the server caches logon information for 10 users. When an 11th user logs on to the device, the server overwrites the oldest cached logon session.

**Comment by git14** [comment]
@VLG17 thanks for the answer. I would recommend updating the docs with that bit of information since it is not documented anywhere. If there is other documentation with that information please let me know.

**Comment by nam31** [comment]
Closing via #9401 
Thank you
