### ISSUE TITLE
Hibernate mode not visible from start-menu using these policies

### ISSUE THREAD

**Issue by mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh** [MicrosoftDocs/windows-itpro-docs#9186]
SCENARIO
1.    Please describe the user scenario(s) in elaborate detail
Users working on Windows 10 devices with the Microsoft Security Baseline enabled (this will disable Sleep State 1-3, but not enable 4). Thus we have tried to enable sleep state 4, but this is not possible through powercfg /h or the following CSP-policies: 
•	Power/TurnOffHybridSleepOnBattery -> 1 (Hybrid Sleep)
•	Power/TurnOffHybridSleepPluggedIn -> 1 (Hybrid Sleep)
•	Start/HideHibernate -> 0 (default) – False (do not hide). 
2.    For the above user scenario(s), what is the expected result?
Since hibernation is enabled using either powercfg /h or the CSP-policies, we would expect for the hibernate button to show in the start menu. Users may use this button to put their system into sleep mode 4 (hibernate) manually. 
3.    For the above user scenario(s), what is the observed result?
The hibernation button will NOT show in the start menu. Users are thus not able to put their systems into sleep mode 4 (hibernate) manually through start-menu. 

Solution: 
We cannot enable S-modes 1-3 whilst these are blocked by the Microsoft Security Baesline. There is an additional registry key that needs to be set by Microsoft when the aforementioned powercfg /h or CSP-policies are set: 
•	(HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FlyoutMenuSettings
ShowHibernateOption DWORD
0 = Remove
1 = Add. 
We have now done this manually in a separate configuration, I hope Microsoft will be able to document this issue here and fix it in a later release. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efe2ec03-bfd6-c13b-0e5a-a11129342f3e
* Version Independent ID: 8151028c-e9a1-c8a4-3f5e-26d62b14b3de
* Content: [Policy CSP - Power - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-power)
* Content Source: [windows/client-management/mdm/policy-csp-power.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-power.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh   This article does not stated about  start menu,  instead of it deals with only advanced configuration settings for power configuration.

**Comment by mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh** [comment]
@RAJU2529 in Microsoft Support case 121012225001620 the issue is confirmed by the Product Group. 

If you don't want to document it in this article, could you please link in this documentation to the documentation about the flyoutmenu? It seems documented nowhere (at least I couldn't find it being documented).

**Comment by joinimran** [comment]
@mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh - Can you please share the support thread here so that I can review and make necessary changes to the document

Thanks
Imran.

**Comment by nam31** [comment]
@mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
