### ISSUE TITLE
Set-OUPermissions.ps1 script?

### ISSUE THREAD

**Issue by hbudach** [MicrosoftDocs/windows-itpro-docs#9188]
I'm not seeing this script via the link provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt#feedback)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by K3rat005** [comment]
Same problem.  working to setup MDT and can't find the script.

**Comment by RAJU2529** [comment]
@hbudach  @K3rat005 , You can download from  here .  
**https://github.com/DeploymentArtist/SWP1/tree/master/Scripts**

**Comment by RAJU2529** [comment]
@e0i, may I add the below link in this  article 
**https://github.com/DeploymentArtist/SWP1/tree/master/Scripts**

**Comment by RAJU2529** [comment]
@nam31 . I am going to edit this article, but I will not add a script link.
I make  some words to **BOLD** and  updating the adobe reader link and version number

**Comment by greg-lindsay** [comment]
The forward link was set to https://gallery.technet.microsoft.com/Configure-permissions-in-2326651a but this no longer exists. I am editing the forward link, which should fix the problem almost immediately.

**Comment by greg-lindsay** [comment]
This is working now.

**Comment by RAJU2529** [comment]
@greg-lindsay . please look into this PR #9196
