### ISSUE TITLE
Error code 0x80070422

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-itpro-docs#9189]
Missing error code 0x80070422 and related description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb9f2a2-76ad-8301-7d80-e33a7bb80a1b
* Version Independent ID: dd070c32-53d5-53d6-7ba2-a4361b5263bb
* Content: [Windows Update common errors and mitigation - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-errors)
* Content Source: [windows/deployment/update/windows-update-errors.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-errors.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Document links:
- https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-errors
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-errors.md

Different page from issue ticket #9190 (**Error code 0x80070422**), but the content issue is the same (hence the ticket title).

**Comment by illfated** [comment]
From issue ticket #9190:

> Missing error code 0x80070422 and related description.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: f76d96ac-5343-20e2-9d99-9c1cea7ccc2e
> * Version Independent ID: a95c9b39-4a66-d726-4404-de5af60ac982
> * Content: [Windows Update error code list by component - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-error-reference)
> * Content Source: [windows/deployment/update/windows-update-error-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-error-reference.md?rgh-link-date=2021-02-22T19%3A54%3A45Z)
> * Product: **w10**
> * Technology: **windows**
> * GitHub Login: @jaimeo
> * Microsoft Alias: **greglin**

## PLEASE NOTE: THIS IS ABOUT A DIFFERENT PAGE THAN THE POST ABOVE

(@RAJU2529 : PLEASE LEAVE THIS ONE UNCHANGED, WE ARE TALKING ABOUT 2 SEPARATE PAGES HERE.)

**Comment by RAJU2529** [comment]
@illfated . I will not touch this page.

**Comment by illfated** [comment]
Fair enough. Keep in mind that the closing of the other ticket means that this ticket will now have to manage 2 separate pages.

**Comment by nam31** [comment]
Closing via #9411 
Thank you
