### ISSUE TITLE
Any plan to fix FOD package download link or replace the file on server with correct one?

### ISSUE THREAD

**Issue by fookie** [MicrosoftDocs/windows-itpro-docs#9192]
There's no feedback portal on the docs page so I have to manually add the relevant links here. 

The FOD.cab download link on this page for Windows 10, version 2004 is the wrong one. I have submitted the details under [this update](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/71b3d5e0a37363ae00149d8ffc6267cb5dcf9b16) a month ago but it haven't been fixed yet. 

> I checked FOD files for 2004 and 1903/1909, they have same MD5(94C065BD11CD6881BF90ECE5D4235EA1). It seems they're both for 1909/1903 and unable to be installed on Windows 10 20H2.

Please fix that ASAP. I need to install the FOD.cab on a computer that has no Internet access to use a VR headset. And there's nowhere I can find the download link.

Content: [Enable or block Windows Mixed Reality apps in enterprises](https://docs.microsoft.com/en-us/windows/application-management/manage-windows-mixed-reality)
Content Source: [windows/application-management/manage-windows-mixed-reality.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/application-management/manage-windows-mixed-reality.md)

**Comment by RAJU2529** [comment]
@fookie,  This issue has been reported , under processing , 
So  @e0i, so please close this issue

**Comment by e0i** [comment]
@RAJU2529 I appreciate you taking the time to help deal with the issues in this repository but this issue seems to have no duplicate as you've suggested. Plus we don't close issues without addressing the raised concerns first.

**Comment by e0i** [comment]
@fookie Under investigation. Thank you.

**Comment by e0i** [comment]
@tmlyon It seems that the link that has been introduced via the following commit points to a file for an older version. Can you take a look? Thanks.

Commit: [Update manage-windows-mixed-reality.md by @tmylon](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/71b3d5e0a37363ae00149d8ffc6267cb5dcf9b16)

**Comment by MaratMussabekov** [comment]
Dear @tmlyon ,
if it is not currently possible to fix this link, may be we should temporarily remove it, to avoid confusion?
Thank you

**Comment by illfated** [comment]
> if it is not currently possible to fix this link, may be we should temporarily remove it, to avoid confusion?

Looks like a good suggestion. The page has not seen any new updates since January.

**Comment by tmlyon** [comment]
I believe the corrected link should be https://software-download.microsoft.com/download/pr/6cf73b63/Microsoft-Windows-Holographic-Desktop-FOD-Package~31bf3856ad364e35~amd64~~.cab
I haven't yet tested to verify though. Unclear how this got corrupted in file delivery though.

**Comment by e0i** [comment]
@tmlyon Thank you for providing the much needed info! An independent contributor is going to revise the article with your suggestion.
