### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by munrobasher** [MicrosoftDocs/windows-itpro-docs#9195]
The link to "Reset Windows Update Client settings script" is broken.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-gb/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment]
@munrobasher . This issue has been already esculated by other user , Microsoft team looking to hosting new location. 
 Team is already working , so please close this issue now.
@e0i . please close this issue

**Comment by e0i** [comment]
This issue is going to be addressed in #9104 

Thanks
