### ISSUE TITLE
Suggested change: multi-factor auth for developers, not just admins

### ISSUE THREAD

**Issue by jbrucker** [MicrosoftDocs/windows-itpro-docs#9198]
In the section titled "For software venders and developers" it recommands:
>
> * Require multi-factor authentication for admins.
>
Why not require multi-factor auth for everyone?  A vector of attack is to break into a
developer's account on Github and push an update containing malicious code, which
may then be automatically built and distributed (such as a Ruby gem or Python module
that other apps use).
Multi-factor auth would help prevent this, of course.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41cf42f0-fcdc-989a-aa24-c59550ad863b
* Version Independent ID: e251ca8d-1cde-f1af-43fd-4f5010abd414
* Content: [Supply chain attacks - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/supply-chain-malware)
* Content Source: [windows/security/threat-protection/intelligence/supply-chain-malware.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/supply-chain-malware.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by nam31** [comment]
@jbrucker, thank you for providing feedback.
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
Thank you for your contribution to make the docs better! Much appreciated!
