### ISSUE TITLE
Update of target OS

### ISSUE THREAD

**Issue by dev-nawa** [MicrosoftDocs/windows-itpro-docs#9199]
【Change before】
****************************************************** ***************************
Applicable target
• Windows 10
• Windows 10 Mobile
• Microsoft Edge
****************************************************** ***************************
[After change]
****************************************************** ***************************
Applicable target
• Windows 10
• Windows 10 Mobile
• Microsoft Edge
• Windows 8.1 or later
• Windows Server 2012 or later
****************************************************** ***************************

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4edaae97-455b-d25a-9228-5309e24b4aa3
* Version Independent ID: d38e56a7-d553-e519-95a9-dc93e2cdc771
* Content: [Microsoft Defender SmartScreen overview (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview)
* Content Source: [windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by MaratMussabekov** [comment]
Hello,
I will check the applicable targets and create a PR
Thank you

**Comment by MaratMussabekov** [comment]
Hello,
The article s about features provided by smartscreen to protect Edge on Windows 10. It is not applicable for Windows Server or Windows 8.1.
Also applicable for https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9151

Thank you

**Comment by illfated** [comment]
Looks like the issue has been answered by the MS Docs community.

#please-close
