### ISSUE TITLE
Remove taskbar only once

### ISSUE THREAD

**Issue by Bobsik** [MicrosoftDocs/windows-itpro-docs#920]
Hello, I have question for the taskbar layout. Is there any way to unpin all default apps, add our list of apps, but apps which user can unpin by himself ? Basically it would only once unpin apps, pin our apps (f.e. Internet Explorer and Explorer) and leave user to do with it whatever he wants?! By this way user have to has got pinned the apps the "hard way" (=if I after that unpin the app, relogin (somewhere I have seen the restart explorer.exe will be sufficient to do so) pinned apps come back by the layout, it is not ideal..) it might be useful in certain cases of course.. I have thought about that and only find a way to after login of new user to overwrite the layout without any app in user's profile itself, but it seems overcomplicated

**Comment by andreabichsel** [comment]
Is this what you're looking for? https://docs.microsoft.com/en-us/windows/configuration/windows-10-start-layout-options-and-policies
