### ISSUE TITLE
Update of target OS

### ISSUE THREAD

**Issue by dev-nawa** [MicrosoftDocs/windows-itpro-docs#9200]
【Change before】
****************************************************** ***************************
Requirements
Windows 10 version 1709 or later | Microsoft Defender AV real-time protection and cloud-delivered protection must be enabled

****************************************************** ***************************

[After change]
****************************************************** ***************************
Requirements
Windows 10 version 1709 or later	Microsoft Defender AV real-time protection and cloud-delivered protection must be enabled
Windows Server 2016 or later    	Microsoft Defender AV real-time protection and cloud-delivered protection must be enabled

****************************************************** ***************************

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71064247-63c3-cb57-5f05-a1ea40b01d97
* Version Independent ID: 684863fb-0302-945d-d42e-ed35f5e6269d
* Content: [Use network protection to help prevent connections to bad sites - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/network-protection)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/network-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/network-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by MaratMussabekov** [comment]
Hello,
I will check the requirements and create a PR
Thank you

**Comment by MaratMussabekov** [comment]
Hello @dev-nawa ,
Were you able to implement network protection on Windows Server 2016?
According to 
https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/protecting-windows-server-with-windows-defender-atp/ba-p/267114#M128, network protection is only supported since Windows Server 1803.

Thank you

**Comment by nam31** [comment]
Closing via #9267 
Thank you
