### ISSUE TITLE
Key Admins and Enterprise Key admins are protected with AdminSDHolder

### ISSUE THREAD

**Issue by archeon1004** [MicrosoftDocs/windows-itpro-docs#9202]
Hi,

In the text there is description of groups Key Admins and Enterprise Key admins and in the table the field protected with ADMINSDHOLDER is set to NO, while it's not true.

To confirm that I've created a new user account. Checked admincount attribute value and added then to the Key Admins group. 
After sdpropagator task went through the admincount attribute was set to 1.

Could you please verify and update the documentation please? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44e911d3-219e-19b8-4870-07514d9a94a1
* Version Independent ID: 960a7388-560b-90eb-e0ff-d8d2bb6f9a7a
* Content: [Active Directory Security Groups (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/active-directory-security-groups#key-admins)
* Content Source: [windows/security/identity-protection/access-control/active-directory-security-groups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/access-control/active-directory-security-groups.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello,
I will try to reproduce it and will let you know
Thank you

**Comment by archeon1004** [comment]
Thank you!
By the way, would it be possible to add more detailed description of what those groups are? The description of Enterprise Key Admins group is "Members of this group can perform administrative actions on key objects within the forest.". Would it be possible to add at least link to other documentation pointing to the key object?

**Comment by MaratMussabekov** [comment]
Hello, 
Yes, you are right, the group is protected by ADMINSDHOLDER.
**Would it be possible to add at least link to other documentation pointing to the key object?** - as far as google shows, there is no such article in Microsoft Docs.

Thank you

**Comment by archeon1004** [comment]
@MaratMussabekov  MS uses google to search? 😄 
I done additional deep dive on this and found that this groups gives full privileges on ms-DS-Key-Credential-Link. Would it be possible for you to confirm this and perhaps add this to this doc?

**Comment by MaratMussabekov** [comment]
Hello @archeon1004 ,
**MS uses google to search?** - no, MS uses Bing. I am not working in Microsoft, so I am free to use Google )
**this groups gives full privileges on ms-DS-Key-Credential-Link. Would it be possible for you to confirm this** - yes, confirmed. For example, it is mentioned here - https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-dir-sync#configure-permissions-for-key-synchronization
**perhaps add this to this doc** - I do not think it should be added here. It already states "Members of this group can perform administrative actions on key objects within the domain." which actually means the same as privileges on msDS-KeyCredentialLink. It also will look inconsistent, as other groups do not have such descriptions (on object-level).

Thank you

**Comment by archeon1004** [comment]
@denisebmsft Any news when to expect the update? 😄

**Comment by nam31** [comment]
Closing via #9218 
Thank you

**Comment by archeon1004** [comment]
@nam31  @MaratMussabekov Thank you! :)
