### ISSUE TITLE
Configuring IPv4 address it is not optional it is mandatory when setting a WIP policy. Please correct ASAP

### ISSUE THREAD

**Issue by ami857** [MicrosoftDocs/windows-itpro-docs#9208]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ad3f92-24de-5eb5-8454-c72d85737183
* Version Independent ID: 900125eb-31ea-faf3-ac30-7c3d7b30f611
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
Closing via #9410 
Thank you
