### ISSUE TITLE
Citation for legal precedent - Interactive Logon Message text

### ISSUE THREAD

**Issue by davwheat** [MicrosoftDocs/windows-itpro-docs#9209]
> Legal precedents have established that organizations that display warnings to users who connect to their servers over a network have a higher rate of successfully prosecuting trespassers.

Are there any citations available for this claim? I feel like putting this in documentation without any real proof isn't a great idea.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8897b50b-10e9-5d0b-6150-c1834a296a20
* Version Independent ID: bed1c6d9-91c3-02f2-12c9-58229886118a
* Content: [Interactive Logon Message text (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-message-text-for-users-attempting-to-log-on)
* Content Source: [windows/security/threat-protection/security-policy-settings/interactive-logon-message-text-for-users-attempting-to-log-on.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/interactive-logon-message-text-for-users-attempting-to-log-on.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@davwheat . I configured college  desktop  , when authorized users trying to login in the desktop, they get messages  regaring 
covid 19  preventing steps.

**Comment by nam31** [comment]
@davwheat, Thank you for providing feedback.	
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.	
Thank you for your contribution to make the docs better! Much appreciated!

**Comment by davwheat** [comment]
@nam31 Your suggesting that I send feedback via the Windows 10 feedback hub about documentation that says to open an issue on GitHub to leave feedback.

Fantastic stuff. 😂

**Comment by illfated** [comment]
@e0i : Would you be know if any of the MS Docs team members knows enough about the legal implications and legal matters in the documentation, to ask them if this is something we should reply to here?

**Comment by nam31** [comment]
@davwheat, Please note that the issues section of the repository is intended for corrections in technical documentation.
For your original query, we can involve the author for the guidance.
@Dansimp, can you help?

**Comment by illfated** [comment]
Just as a comparison, if that text had been placed in an article page on Wikipedia, it would automatically be tagged as [Citation needed] as a request to add a valid reference.

**Comment by davwheat** [comment]
> Please note that the issues section of the repository is intended for corrections in technical documentation.

I'd personally interpret an unsubstantiated claim as an error that should be backed up in some form or removed.

**Comment by vinaypamnani-msft** [comment]
@davwheat I recently updated this article and removed the unsubstantiated claim, so I'm going to go ahead and close this issue. Thanks for raising this doc issue, and please continue to do so, so we can improve the docs!
