### ISSUE TITLE
Server 2012 (non-R2) documentation missing

### ISSUE THREAD

**Issue by yllekz** [MicrosoftDocs/windows-itpro-docs#9212]
Hello, we have non-R2 Server 2012 systems we need to onboard to Defender for Endpoint. Presently, the documentation seems to omit this OS entirely, and it really needs to be in there, considering 2008 R2 (an older OS) is supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4ed2b3-0390-4d53-2450-14995ee8b0b0
* Version Independent ID: 91b5bb3e-55d4-6a8e-c16d-094f15c28ee7
* Content: [Onboard Windows servers to the Microsoft Defender for Endpoint service - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-server-endpoints.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by adirdidi** [comment]
2012 non R2 is not supported, this is not a documentation issue.
