### ISSUE TITLE
Windows activation for GCC High

### ISSUE THREAD

**Issue by kerbos** [MicrosoftDocs/windows-itpro-docs#9213]
We need a statement that mentions that this is not available for GCC High and DoD at this time. And be kept updated when/if it becomes available. Are the authors aware of this limitation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
(ref. #9264 )

**Comment by nam31** [comment]
Closing via #9264 
Thank you
