### ISSUE TITLE
try

### ISSUE THREAD

**Issue by whiplash696** [MicrosoftDocs/windows-itpro-docs#9215]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 001a64c5-bdea-ae9f-578e-a785bca20d23
* Version Independent ID: b521d32a-cf9f-8b6a-0411-fd77537673e1
* Content: [Overview of endpoint detection and response capabilities - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/overview-endpoint-detection-response)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/overview-endpoint-detection-response.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/overview-endpoint-detection-response.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Looks like a test comment, no real issue content here.

#please-close
