### ISSUE TITLE
Link to article not valid

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/windows-itpro-docs#9222]
There are references to URL https://www.microsoft.com/CloudandHosting/licensing_sca.aspx, which is no longer valid. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ecbc1-9c02-5681-7214-356be22ac7e8
* Version Independent ID: 73af82f6-079b-6c37-55c4-cb59e921457a
* Content: [Deploy Windows 10 Enterprise licenses - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-enterprise-licenses)
* Content Source: [windows/deployment/deploy-enterprise-licenses.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-enterprise-licenses.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
The sentence in question is the following one:

## Virtual Desktop Access (VDA)

Subscriptions to Windows 10 Enterprise are also available for virtualized clients. Windows 10 Enterprise E3 and E5 are available for Virtual Desktop Access (VDA) in Windows Azure or in another [qualified multitenant hoster](https://www.microsoft.com/CloudandHosting/licensing_sca.aspx).

**Comment by nam31** [comment]
Closing via #9245 
Thank you
