### ISSUE TITLE
HoloLens supported CSPs Page not shown in TOC

### ISSUE THREAD

**Issue by evmill** [MicrosoftDocs/windows-itpro-docs#9223]
Hello,

The page https://docs.microsoft.com/windows/client-management/mdm/policies-in-policy-csp-supported-by-hololens2 is not shown in the table of contents. I am not that familiar with your docs structure but I believe that this should be listed somewhere. 

Thanks,
-Evan   /   https://docs.microsoft.com/hololens/docs person 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659d0469-51e7-bf41-6913-c249d05548b6
* Version Independent ID: 7732d212-5328-9c03-7270-572146c074e8
* Content: [Policies in Policy CSP supported by HoloLens 2 - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policies-in-policy-csp-supported-by-hololens2)
* Content Source: [windows/client-management/mdm/policies-in-policy-csp-supported-by-hololens2.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policies-in-policy-csp-supported-by-hololens2.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by ManikaDhiman** [comment]
Hi @evmill, Thanks for pointing this out. TOC is now updated with the correct filenames to display the [Hololens 2 topic](https://docs.microsoft.com/en-us/windows/client-management/mdm/policies-in-policy-csp-supported-by-hololens2) and other policies in Policy CSP topics. Thanks again for your valuable feedback!

**Comment by nam31** [comment]
@evmill Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Comment by evmill** [comment]
I missed the initial mail. Yes this addition to the TOC is sufficient. Thanks so much for the update!!
