### ISSUE TITLE
sidtype command syntax

### ISSUE THREAD

**Issue by Frediloc** [MicrosoftDocs/windows-itpro-docs#9224]
In the body of the text

It appears that this:
`sc sidtype <Type> <ServiceName>`

Should be changed to this:
`sc sidtype <ServiceName> <Type>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df1d6ca4-d733-03f6-7c5a-d0bd584fb805
* Version Independent ID: 4d3a7607-cdbf-72d8-0cf0-d3b173eca352
* Content: [Create an Inbound Program or Service Rule (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/create-an-inbound-program-or-service-rule)
* Content Source: [windows/security/threat-protection/windows-firewall/create-an-inbound-program-or-service-rule.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/create-an-inbound-program-or-service-rule.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@Frediloc . Thanks for pointing out. I am fixing that error.

**Comment by illfated** [comment]
The suggested correction is available for review, comments and suggestions in the PR #9232 .
