### ISSUE TITLE
I think you should also include "go.microsoft.com" in the Security intelligence updates Alternate Download Location (ADL) section.

### ISSUE THREAD

**Issue by dev-nawa** [MicrosoftDocs/windows-itpro-docs#9227]
I think you should also include "go.microsoft.com" in the Security intelligence updates Alternate Download Location (ADL) section.
When I check MpCmdRun-System.log, the connection destination is recorded as "https://go.microsoft.com/***".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86b0db3-f979-bd1f-78a4-41247510721a
* Version Independent ID: 5289bb5f-f015-7f38-05a1-26a615ae07aa
* Content: [Configure and validate Microsoft Defender Antivirus network connections - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-network-connections-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/configure-network-connections-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/configure-network-connections-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
Hmm. I wonder, is it needed, though? https://go.microsoft.com/ is just a jump pointer to other URL addresses in the microsoft.com universe.
