### ISSUE TITLE
Defender Autoexclusions for Windows 10 ? 

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#924]
Hello, 

With regards to the DisableAutoExclusions setting, I noticed that this option also exists for Windows 10 and found the following reference: 

https://msdn.microsoft.com/en-us/library/windows/desktop/dn455323(v=vs.85).aspx
Beginning in Windows 10: Allows an administrator to specify if the Automatic Exclusions feature for Server SKUs should be turned off.

It's a bit confusing as it talks about Windows 10 and Server SKUs. 

I would appreciate if the article could be updated to include Windows 10 that and describes the default exclusions that are applied there if not the same. When running get-MpPreference I see that on a windows 10 client the default setting is: 

DisableAutoExclusions         : False

I came across this , since I have the Hyper-V feature enabled on my Windows 10 client, but it did not seem to apply auto exclusions there. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9b6379-e575-9819-eca1-a0952f66b655
* Version Independent ID: 34d81602-ffa2-5be6-67ef-b42b3b6f17ee
* Content: [Automatic and customized exclusions for Windows Defender AV on Windows Server 2016](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by andreabichsel** [comment]
Thank you for your feedback! I'm following up with the product team and will update based on their input.

**Comment by andreabichsel** [comment]
I added a note to the topic explaining that the setting is only supported on Windows Server. While it exists in Windows 10, it doesn't have an effect on exclusions. Changes should be live by noon tomorrow PST.
