### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by CoMMyCZ** [MicrosoftDocs/windows-itpro-docs#9241]
The link is broken:

**Reset this PC**
The 'reset this PC' recovery function now includes a *cloud download option*.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d651de3c-b8eb-e8d9-8138-1eadb758bf2e
* Version Independent ID: a19a8b65-0f4a-efd5-7f83-56bd07cc8c3b
* Content: [What's new in Windows 10, version 2004 - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-2004)
* Content Source: [windows/whats-new/whats-new-windows-10-version-2004.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/whats-new-windows-10-version-2004.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Ah, yes. Seen this before, it usually happens to all the links containing `wip-4-biz-whats-new`. Feel free to create new tickets for any page linking to the page `wip-4-biz-whats-new`.

This is outdated Insider Preview material and has been moved to the Archives. Thank you for pointing this out. I will make a PR to resolve the linking issue.

**Comment by illfated** [comment]
Also, BTW, I have decided to replace 8 outdated links on the same page, so once my soon-to-be-available Pull Request gets merged, it should not take long before we can move on to looking for outdated links elsewhere.

**Comment by illfated** [comment]
(For reference: The outdated link reported in this ticket (to be replaced) is this one:
- https://docs.microsoft.com/windows-insider/at-work-pro/wip-4-biz-whats-new#new-reset-this-pc-option-cloud-download-build-18970

The offending part of the link (no longer existing directory and page name) is this: `/at-work-pro/wip-4-biz-whats-new`

**Comment by illfated** [comment]
There you go. PR #9244 is ready for review, comments & suggestions. Feel free to comment or suggest further improvements.
