### ISSUE TITLE
Key Trust or Cert Trust 

### ISSUE THREAD

**Issue by dbona75** [MicrosoftDocs/windows-itpro-docs#9242]
Hello , please specify if the feature is available for WHFB in Key Trust or Cert Trust architecture.

It seems it works only in the Cert Trust WHFB model .

Thanks in advance

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f50a8599-301a-5993-1a86-e722f66ffcf2
* Version Independent ID: fffd0fc9-97f6-cfa9-70fb-7f1308804de0
* Content: [Dual Enrollment - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-dual-enrollment)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-feature-dual-enrollment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-feature-dual-enrollment.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by nam31** [comment]
Closing via #9277 
Thank you
