### ISSUE TITLE
Windows Server 2016, disable automatic Reboot outside of active hours

### ISSUE THREAD

**Issue by Pootch** [MicrosoftDocs/windows-itpro-docs#9247]
For me the "active hours" is the most stupid feature for a server OS ever.
We do not want to automatically reboot our server if we have installed OS updates via windows update OUTSIDE of active hours.
There is no way to control this via GPO. Please get rid of this stupid feature or implement a GPO to **disable reboots outside of active hours.**

**Comment by illfated** [comment]
@Pootch : Your reasoning is fair, although this is not a practical arena to get your message across to the developers.

Please use either the Windows 10 Feedback Hub (desktop app) or the web equivalent (sorry for not remembering the URL) to share your idea with the developers.

Please note that this repository and this issue ticket system is intended for improvement suggestions and documentation purposes only.
