### ISSUE TITLE
Microsoft Defender for Endpoint licensing for RDSH

### ISSUE THREAD

**Issue by JelmerBarhorst** [MicrosoftDocs/windows-itpro-docs#9252]
It is unclear if a Remote Desktop Session host (e.g. Windows Server 2019 multi user) is regarded as a per-user deployment as is with WVD and Windows 10 Multi-user or that it requires a server license.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender for Endpoint - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements#licensing-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by lindspea** [comment]
@JelmerBarhorst thank you for reaching out. I found this old article regarding RDSH - https://techcommunity.microsoft.com/t5/ask-the-performance-team/remote-desktop-services-rds-2012-session-deployment-scenarios/ba-p/375596. I'm still doing some more research but please let me know if it helps at all.

**Comment by JelmerBarhorst** [comment]
@lindspea Thanks for the article, but I can't see any references to Defender for Endpoint (or it's previous name) in that article.

**Comment by illfated** [comment]
I know it may seem difficult to tell, but the main thing to be aware of is clearly pointed out in one of the Note blobs:

Customers may acquire server licenses (one per covered server Operating System Environment (OSE)) for Microsoft Defender for Endpoint for Servers if they have **a combined minimum of 50 licenses** for one or more of the following user licenses:

- Microsoft Defender for Endpoint
- Windows E5/A5
- Microsoft 365 E5/A5
- Microsoft 365 E5/A5 Security

The main point here is that you need to have at least 50 user licenses first, before you can acquire a Server license.

**Comment by lindspea** [comment]
Thanks @illfated. @JelmerBarhorst please let me know if this helped answer your question.

**Comment by JelmerBarhorst** [comment]
@illfated thanks, but how to license servers in general was not the question, that is clearly explained. However, the question was regarding RDSH. It's not logical to license both users and the underlying VM. With Win10 multi-user it is also not required to license the VM, only the users are required to have a license which makes sense.

One could argue that a) RDSH vm's do not require a separate Defender for Endpoint license or b) iff RDSH vm's need to be licensed with Defender for Endpoint, when having more than 50 users the surplus doesn't require a Defender for Endpoint user license as the underlyning server is already licensed.. 

Option a seems the most logical, but it is not reflected in the licensing terms.

**Comment by lindspea** [comment]
@JelmerBarhorst thank you. @illfated do you recommend adding option A as a note in the article?

**Comment by illfated** [comment]
Seems reasonable, while it would also be preferable if one of the actual MS Docs team members could confirm that we should go ahead and add that clarification.

@mjcaparas or @denisebmsft : Would you be able to confirm the correctness, clarification, and practicality of the suggested text?

> **RDSH VMs do not require a separate Defender for Endpoint license.**

**Comment by JelmerBarhorst** [comment]
Thanks for updating the docs page!

**Comment by illfated** [comment]
If you find that the document has been updated sufficiently and correctly to resolve this issue, feel free to close this ticket.
