### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by ces3dev** [MicrosoftDocs/windows-itpro-docs#9253]
[Enter feedback here]
Hi,

The link that is supposed to lead me to how to setup Defender with Microsoft Cloud App Security (MCAS), where it says "See Microsoft Defender for Endpoint integration with Microsoft Cloud App Security for detailed...", is broken. It says "404 - Page not found - Hmm, we couldn't find this link, but here are some related search results that may be helpful" when I clicked on the link. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70acebee-16af-18f5-4069-1e4ae0d71fc6
* Version Independent ID: 1dfed329-80c0-b9aa-f168-31f15b43866d
* Content: [Configure Microsoft Cloud App Security integration - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-cloud-app-security-config#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-cloud-app-security-config.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-cloud-app-security-config.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by ces3dev** [comment]
I believe this might be the new link?

https://docs.microsoft.com/en-us/cloud-app-security/mde-integration

**Comment by adirdidi** [comment]
Thank you for reporting, the link was fixed (the updated page will go live later today).
