### ISSUE TITLE
Update documentation to provide a quick guide which option to choose when enroll WVD multisession devices

### ISSUE THREAD

**Issue by sokoloffmaks** [MicrosoftDocs/windows-itpro-docs#9256]
Hi, can you please update documentation to provide a quick guide which option to choose when enroll specifically WVD multisession devices? 
It is not clear , what exactly required to be selected in GPO MDM settings , device or users credentials when it comes to multisession windows 10 VMs
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @sokoloffmaks ,
The described scenario is not currently supported (both intune support for multi session WVD and enrollment using device credentials are not supported yet), please see more details [here](https://docs.microsoft.com/en-us/mem/intune/fundamentals/windows-virtual-desktop#windows-10-enterprise-multi-session).


Thank you

**Comment by illfated** [comment]
(Just posting the expanded link, in case someone would like to have a better look at it before going there.)
- https://docs.microsoft.com/en-us/mem/intune/fundamentals/windows-virtual-desktop#windows-10-enterprise-multi-session
