### ISSUE TITLE
Wrong preference domain for Notifications in the documentation for JAMF

### ISSUE THREAD

**Issue by ConstantinLorenz** [MicrosoftDocs/windows-itpro-docs#9265]
Under  [Step 4: Configure notifications settings](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies#step-4-configure-notifications-settings) In point 7 in the screenshot the wrong preference domain is entered. The preference domain for notifications in macOS is com.apple.notificationsettings, and not com.microsoft.wdav.

![image](https://user-images.githubusercontent.com/62985896/110249986-42000500-7f79-11eb-9fa2-fcc4dc1f74cb.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f791dc07-b2c6-3003-a829-cd1ec03a2918
* Version Independent ID: 2c53adbc-600f-60b2-e8b2-b907335f4862
* Content: [Set up the Microsoft Defender ATP for macOS policies in Jamf Pro - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies#step-6-grant-full-disk-access-to-microsoft-defender-for-endpoint)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Looks like a reasonable assertion, but do you know if that needs to be changed for the 8 text occurrences as well, in addition to the 3 images containing the current text?

**Comment by maximvelichko** [comment]
@illfated , in my opinion the best way to fix it is to use specific JAMF Notifications payload content, as JAMF now supports notifications natively (it did not when the documentation was created)

The original intent of notif.mobileconfig (that one downloads first in Step 4) was to simply import it into JAMF using the Upload button as on the screenshot:
![image](https://user-images.githubusercontent.com/13109133/110254771-6a6e0c00-7f45-11eb-882e-ef8e7d5b1a23.png)

This can be mentioned as an alternative method to configure notifications (it can be convenient for those who does not want to input parameters manually)

**Comment by illfated** [comment]
Interesting. Would that be something we should add to the page in addition to the existing content?

Does it replace the need for any mention of the `com.apple.notificationsettings` value?

**Comment by ConstantinLorenz** [comment]
The notification feature should replace the previous manual upload. It is much easier for the user to understand what is set in for the notifications.

![image](https://user-images.githubusercontent.com/62985896/110255656-1b4fc780-7f95-11eb-8279-28dc8eac1e0b.png)
![image](https://user-images.githubusercontent.com/62985896/110255788-cc566200-7f95-11eb-9cbd-89095156cc2c.png)

**Comment by illfated** [comment]
Sounds like a useful solution. Are the images above (sorry for not knowing the details of this topic well enough) the ones we should use, or could you provide images of what it should look like, in case they are from the document page?

**Comment by maximvelichko** [comment]
@ConstantinLorenz 's screenshots look great. I would use them as is.

As a full disclosure, I haven't tested this configuration end to end myself.

**Comment by illfated** [comment]
Fair enough. I believe there is at least 1 PR targeting this page for a different issue, so there is still some time to do some research, before creating a PR where it is less likely to end up with a file conflict.

**Comment by ConstantinLorenz** [comment]
Hi, I have made better screenshots. I have translated the content of the notif.mobileconfig into the Jamf Notifications Feature.  You can use them now.

![image](https://user-images.githubusercontent.com/62985896/110295689-afe81300-7ff1-11eb-9be6-e4f8ac68ec2b.png)

![image](https://user-images.githubusercontent.com/62985896/110296183-503e3780-7ff2-11eb-9e37-65f14b877305.png)

**Comment by VLG17** [comment]
@ConstantinLorenz Could you check the article now? It looks like it was updated to reflect the new method.

**Comment by nam31** [comment]
@ConstantinLorenz Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
