### ISSUE TITLE
MaxInactivityTimeDeviceLock Documentation incorrectly specifies seconds instead of minutes

### ISSUE THREAD

**Issue by toggenation** [MicrosoftDocs/windows-itpro-docs#9266]
Hi Trying to use 

./Device/Vendor/MSFT/Policy/Config/DeviceLock/MaxInactivityTimeDeviceLock

The documentation says time in seconds but I think it should be minutes.

![image](https://user-images.githubusercontent.com/4483692/110260027-afa24480-7ffe-11eb-8292-407cbd64ee7b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a3dde0-fe8d-25d3-3a7e-83acf9c394c6
* Version Independent ID: 2c654710-0be1-1d50-9972-6ccf9d072bf1
* Content: [Policy CSP - DeviceLock - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-devicelock#devicelock-maxinactivitytimedevicelock)
* Content Source: [windows/client-management/mdm/policy-csp-devicelock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-devicelock.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
Just now i verified in group poicy editor, and i  conformed  time is in seconds only.

Policy setting: Interactive logon: Machine inactivity limit

Location in the Local Security Policy snap-in:

Computer Configuration/Windows Settings/Security Settings/Local Policies/Security Options/

**Comment by joinimran** [comment]
@toggenation - Can you please share any screenshot showing that this input is required in Mins instead of seconds.

**Comment by toggenation** [comment]
From here => https://docs.microsoft.com/en-us/windows/client-management/mdm/devicelock-csp it specifies minutes
![image](https://user-images.githubusercontent.com/4483692/110382257-c011f800-80ae-11eb-9616-e9e0da820a39.png)

But here => https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-devicelock#devicelock-maxinactivitytimedevicelock it specifies seconds.

![image](https://user-images.githubusercontent.com/4483692/110382426-00717600-80af-11eb-94ca-fa5bbb590b2a.png)

But in testing when I set it to seconds ( 15*16 =900) it took I think 900 minutes to lock but setting it to 15 minutes I got the expected behaviour.

This is a screenshot of a working intune policy works with it specified in minutes
![image](https://user-images.githubusercontent.com/4483692/110382937-b63cc480-80af-11eb-97c5-a5ea76783c9a.png)

And the original link to where I found the mention of minutes instead of seconds:

https://social.technet.microsoft.com/Forums/en-US/a427d387-8a64-439b-9a7f-66115dfa7c07/intune-screen-timeout-for-windows-10-desktop?forum=microsoftintuneprod#9fb63275-771c-4337-a1d5-b49f67ffbfc2
