### ISSUE TITLE
MS Safety Scanner shoots first, asks questions later

### ISSUE THREAD

**Issue by DASCert** [MicrosoftDocs/windows-itpro-docs#9268]
Dear Microsoft.

If I wanted to be treated like an incompetent idiot, I'd buy iOS devices.  I don't ... and I don't.

I ran Microsoft Safety Scanner v1.0.3001.0 today and it identified some files which it thought I shouldn't have.  But it didn't ask me, before removing them, and it didn't give me the opportunity to investigate them.  For example, I would have liked to have known the date/time stamp on the files as well as the permissions.  That might have given me some idea of how long the files had been resident on the computer and it might have identified the userid that allowed them to be created.  I would have been able to confirm whether or not they were really malware, you see.

You allow the user to "view detailed results of the scan" but those results are not really detailed, are they?  No, to get the details, the user has to find the location of the log file (%windir%\debug\msert.log) and review that,  Not even a link to the log file on the results screen, though.

And then, through the log file, I see that the program has "removed" a number of files that did were not malware,

Luckily, we have shadow copies and backups enabled on that computer so I was able to recover my work.

But tell me, why are you doing to your users what Apple does to its users?

**Comment by illfated** [comment]
As much as I have sympathy for that kind of issue happening to you, it is still a support issue or some form of complaint to the developers. Although I am not a Microsoft employee or part of the MS Docs team of technical writers, I still find your description to be less useful here in a documentation repository, intended for documentation improvement based on the current state of Windows and its applications.

I suggest posting your story to the developers by using the Feedback Hub app or its web equivalent (sorry for not remembering the URL), as well as filing this as a support incident to Microsoft Support to resolve how to avoid this type of issue happening to you again.

**Comment by nam31** [comment]
@DASCert 
Thank you for providing feedback.
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
Thank you for your contribution to make the docs better! Much appreciated!

**Comment by DASCert** [comment]
Hello again.

The Microsoft Web Site  (docs.microsoft.com), which contains a page relating to the Microsoft Safety Scanner, had two links at the bottom of the page which appears to be an attempt to address the situation when a user wishes to "Submit and view feedback for "this product" and "this page".

Both links resolved to this site.

If this is not the correct place to post the solicited feedback, perhaps the error lies with whoever is managing docs.microsoft.com.  Judging by some of the other issues listed, it would appear that I wasn't the first to be misdirected.  Admittedly, it seemed strange that Microsoft would be using Github but since they have lost the plot in so many other areas, it was not outside the bounds of possibility.

Special thanks to @illfated for their enlightening description of the difficulty faced by those whose first language is not English coupled with their friendly tone.  

Despite the advice to provide feedback via other means, I think I'll pass on that opportunity.

**Comment by illfated** [comment]
> Despite the advice to provide feedback via other means, I think I'll pass on that opportunity.

Very well, fair enough. That is your privilege. Thanks for the feedback. I can always wish that there would be better solutions in place everywhere, working optimally, but, alas, we don't live in an ideal world and therefore often find ourselves at a loss. Thank you for sharing your perspective of the issues.
