### ISSUE TITLE
Add SHA256 hash

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/windows-itpro-docs#9269]
Please add SHA256 hashes to this page.
Security aware customer need this to fulfil national requirements (clean source principal).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5bb1ce3-9128-5385-4417-d22eb5f8cb77
* Version Independent ID: cb6ba731-a2c2-e9b9-7c3e-db781b1b5222
* Content: [Microsoft Safety Scanner Download - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/safety-scanner-download)
* Content Source: [windows/security/threat-protection/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/safety-scanner-download.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by VLG17** [comment]
@trudolf-msft Is the note in the article not enough? Would you like to add more details about SHA-256?

![image](https://user-images.githubusercontent.com/41186174/111150926-65d5d300-8597-11eb-883b-efa559fb4e7e.png)

**Comment by trudolf-msft** [comment]
Hi,

My customer is looking for the exact SHA256 hash of the downloaded files to verify authencity.

Kind regards,
Thomas
________________________________

**Comment by illfated** [comment]
I presume most of us could use an online tool (I used https://emn178.github.io/online-tools/sha256_checksum.html) or installed app to verify the checksum(s) of our downloaded file(s), but for that to be secure, I also presume we would need the uploading personnel to have produced the checksums on files before uploading, as well as posting the verified checksums to the same page as the uploads.

Example: my checksums from the above linked page are the following:
- `7637c9b1219ef5b2d2c5451cbc01f92e8073c557f5e1d8e6b61f1bb46bb123f0` (64-bit)
- `396f8ade747df4e98727627ecc9bb838aef4a1ef7c805f5d129b2c5893f8c078` (32-bit)

Not sure how much this helps, but I only provided this as an example.

**Comment by beerisgood** [comment]
> I presume most of us could use an online tool (I used https://emn178.github.io/online-tools/sha256_checksum.html) 

Or use https://www.virustotal.com/gui/home/upload
which display MD5, SHA1, SHA256 under details tab

**Comment by trudolf-msft** [comment]
Hi,

Thanks.
It's not about how to calculate or check the hash but to publish on this website.
Like we do it for Security Updates on the corresponding download page.

Kind regards,
Thomas
________________________________

**Comment by illfated** [comment]
Yes, that is more or less one of my points in my previous comment, but I guess it was not obvious enough. It would be wise to publish SHA checksums for any file download, not just the security software.

**Comment by aczechowski** [comment]
This article moved with the Microsoft 365 security intelligence content, so isn't in this repository or owned by our content team: https://learn.microsoft.com/microsoft-365/security/intelligence/safety-scanner-download
I'm closing this issue as it's not actionable by my team. If the issue is still outstanding, please file feedback on the current article to notify the current content team.
