### ISSUE TITLE
Good but....

### ISSUE THREAD

**Issue by Joewen101** [MicrosoftDocs/windows-itpro-docs#927]
Instructions are good.
However permissions need to be more granular. I need staff to be able to add devices to auto-pilot but not have access to manage permissions or app purchases or distribution etc...
I just need someone to add devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e62232-54ab-fa9d-1e31-7a65e7506a12
* Version Independent ID: 51a94f92-9ff4-12e7-2f97-1bbe34855400
* Content: [Roles and permissions in Microsoft Store for Business and Education (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/roles-and-permissions-microsoft-store-for-business)
* Content Source: [store-for-business/roles-and-permissions-microsoft-store-for-business.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/roles-and-permissions-microsoft-store-for-business.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Joewen101 - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
