### ISSUE TITLE
Typo in the URL

### ISSUE THREAD

**Issue by MikeParker365** [MicrosoftDocs/windows-itpro-docs#9270]
Disable spelt incorrectly in the URL please update :-) 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e70a68f-210c-b27a-3224-2cfd80028e60
* Version Independent ID: c6a94ff0-9ab2-cd09-c053-e09304d0d16a
* Content: [Policy CSP - Connectivity - Windows Client Management](https://docs.microsoft.com/en-gb/windows/client-management/mdm/policy-csp-connectivity#connectivity-diableprintingoverhttp)
* Content Source: [windows/client-management/mdm/policy-csp-connectivity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-connectivity.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@MikeParker365 , Thanks for pointing out, at first i fix  the word  disble  in this article, afterwards, Microsoft documentation team will  fix in url.

**Comment by illfated** [comment]
(ref. #9272 )

**Comment by nam31** [comment]
Closing via #9272 
Thanks
