### ISSUE TITLE
Sparse File Documentation links to 404

### ISSUE THREAD

**Issue by import-au** [MicrosoftDocs/windows-itpro-docs#9279]
The link for Sparse Files in the getfile note is a 404.

Current Redirects to:
https://docs.microsoft.com/en-us/windows/desktop/fileio/sparse-files/

Probably should go to maybe?
https://docs.microsoft.com/en-us/windows/win32/fileio/sparse-files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8c6bee9-e792-395d-0b9c-b46b90e45843
* Version Independent ID: 72c4ca50-76ac-6663-3cf6-b5fac1b348ef
* Content: [Live response command examples - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/live-response-command-examples?branch=pr-en-us-638#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/live-response-command-examples.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/live-response-command-examples.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@import-au , Thanks for pointing out.

**Comment by illfated** [comment]
(ref. #9280 )
