### ISSUE TITLE
Correction / Clarification on Scripting Host.

### ISSUE THREAD

**Issue by secdev-01** [MicrosoftDocs/windows-itpro-docs#9282]
`This does no apply to scripting engines, including Powershell`

Should likely read 

`This does _not_ apply to scripting engines, including Powershell`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 054326d9-bae7-e73f-c250-735f3863c32a
* Version Independent ID: f4b3c1fc-695b-2ba5-d5fe-747a9414441c
* Content: [Customize controlled folder access - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/customize-controlled-folders)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/customize-controlled-folders.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/customize-controlled-folders.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@secdev-01 . Thanks for pointing out.

**Comment by denisebmsft** [comment]
Thank you @secdev-01 for catching these typos. They are fixed, and you will see the revisions live later today. Thank you for helping us to improve our documentation!
