### ISSUE TITLE
Insecure login option...

### ISSUE THREAD

**Issue by null1984** [MicrosoftDocs/windows-itpro-docs#9283]
[I hope this reaches the correct page and displays properly. Potentially serious problem here. I like this article alot, you certainly are speaking my language, not that anything new was learned, but nice to see someone who sees things as I do. I especially like the part where you advocated use of a device specific PIN, rather than an account-wide password, which I consider to be extremely insecure for the very reasons you outlined here. Not sure you included this specific example, but this is what concerns me. Windows is not giving me the choice to set PIN as my only accepted login option. It is now insisting that the device also accepts my outlook password. This is extremely insecure and uncharacteristically irresponsible from Microsoft. I'm not sure when this started but it needs to stop immediately. If I use a device to login to my outlook address , it has to use my outlook password, which is the same as my account password. I might find myself logging into this account from all sorts of places and devices, both secure and insecure, hotel WiFi for example. Now, if some malicious so and so intercepts this, they will not only be able to access my central email account, which frankly is better protected to due new device login notifications etc, but they will then be able to login and gain root access to my main device. Kind of blasts a gaping wide hole in the concept of "military grade encryption" does it not?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c34dbafa-df3c-a5a5-32d5-2ce152893534
* Version Independent ID: cebdd9a6-45d7-6306-373c-7d31121f9e16
* Content: [Why a PIN is better than a password (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by RAJU2529** [comment]
@null1984 . If your device comes with finger print reader or fingerprint scanner, then Windows will ask the users to setup fingerprint reader to set-up finger print and then it will ask to setup PIN..
my laptop does not came fingerprint reader, so I bought usb finger print reader it just like scandisk ultra pendrive size only. 
and I completed setup fingerprint and PIN .

**Comment by nam31** [comment]
@null1984 Thank you for providing feedback.
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
Thank you for your contribution to make the docs better! Much appreciated!
