### ISSUE TITLE
Links to scripts referenced in this article are broken and go to a search

### ISSUE THREAD

**Issue by phillhocking** [MicrosoftDocs/windows-itpro-docs#9287]
Hello, I came upon some Windows update issues and noticed that the links referencing specific scripts are not found and redirect to a [Browse Code Samples](https://docs.microsoft.com/en-us/samples/browse/?redirectedfrom=TechNet-Gallery) page that does not have these scripts as hits. 

![image](https://user-images.githubusercontent.com/4030898/110619045-3284e580-814c-11eb-8186-044921be767f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
Duplicate of issue tickets #4930, #9104, #9216, #9237, and #9281 .

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4930#issuecomment-805021222 :
> Fixed via https://github.com/MicrosoftDocs/windows-itpro-docs/commit/15e9a411fce64546f8572b29691f782b3f4badb1#diff-fc5cd38a44f9cd55d877749fbddbe9dabdf373fbf2348b20aba9581b44062630
> 
> See: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9315#issuecomment-800640519
>
> > Fixed via https://github.com/MicrosoftDocs/windows-itpro-docs/commit/15e9a411fce64546f8572b29691f782b3f4badb1#diff-fc5cd38a44f9cd55d877749fbddbe9dabdf373fbf2348b20aba9581b44062630

**Comment by illfated** [comment]
@phillhocking : Are you available to confirm that this ticket can be closed now, based on the committed changes?

**Comment by phillhocking** [comment]
@illfated it does appear this is good to close, thanks!
