### ISSUE TITLE
Additional Points on Licensing

### ISSUE THREAD

**Issue by desinnic** [MicrosoftDocs/windows-itpro-docs#9288]
[Hello I am an SEE working at Microsoft and often work with Customers on SA cases. I was looking to request some information added to make a specific point for customers. We often see the customers misunderstanding the licensing prerequisites for Subscription Activation. We often see customers failing to license Windows 10 Pro or assuming that you only need an SA license to fully license Windows. Is it possible to add some detail to the first section of the document that makes it clear that customers must have Windows 10 licensed with Pro before they can use SA]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation#feedback)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by VLG17** [comment]
@desinnic In my opinion this prerequisite is stated clearly twice, in the beginning of the article.

> Starting with Windows 10, version 1703 Windows 10 Pro supports the Subscription Activation feature, enabling users to “step-up” from Windows 10 Pro to Windows 10 Enterprise automatically **if they are subscribed to Windows 10 Enterprise E3 or E5.**

> If you are running Windows 10, version 1703 or later:

> **Devices with a current Windows 10 Pro license** can be seamlessly upgraded to Windows 10 Enterprise.

Also, the [4th article/part](https://docs.microsoft.com/en-us/windows/deployment/deploy-enterprise-licenses) under "Subscription Activation" states exactly that:

![image](https://user-images.githubusercontent.com/41186174/113990148-d6e86d80-9859-11eb-9f12-2b2bdad77b43.png)

I think you could use this one to convey the message, if the article you linked is not enough (although it should be).

**Comment by nam31** [comment]
@desinnic  Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
