### ISSUE TITLE
Vmsp.exe missing in hyper-v process exclusions

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#929]
In the article "Recommended antivirus exclusions for Hyper-V hosts" there is an additional process listed that should be considered to be excluded:

**- Vmsp.exe**
Note Starting with Windows Server 2016, this file may have to be configured as a process exclusion within the antivirus software.

https://support.microsoft.com/en-us/help/3105657/recommended-antivirus-exclusions-for-hyper-v-hosts

You might want to consider to add this to the list as well, the question is, is this process also included in the auto exclusions for server 2016?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9b6379-e575-9819-eca1-a0952f66b655
* Version Independent ID: 34d81602-ffa2-5be6-67ef-b42b3b6f17ee
* Content: [Automatic and customized exclusions for Windows Defender AV on Windows Server 2016](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by andreabichsel** [comment]
Thank you for your feedback! I'm confirming with the product team and will update the topic as soon as I hear back.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @alexverboon ,
Vmsp.exe is still not excluded automatically. You can exclude it manually as it is described [here](http://scug.be/wim/2019/01/09/hyper-v-2019-configure-antivirus-exclusions-in-windows-defender-antivirus/) (the article is for Windows Server 2019, but for the 2016 actions will be the same)
Thank you

**Comment by mypil** [comment]
@alexverboon - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
