### ISSUE TITLE
DC Discovery process for Windows Hello for Business

### ISSUE THREAD

**Issue by msft-jaiverma** [MicrosoftDocs/windows-itpro-docs#9292]
[Enter feedback here]

In a large enterprises, DCs are not located in single site. It appears that DC Discovery process is different for WHfB clients and it does not use DCLocator process. it is useful if DC Discovery process is defined in greater details, so that we can plan domain controller placement site wise. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1da1ac4-4e67-5970-6d10-19aac6e853f6
* Version Independent ID: 4f4b45eb-d479-3699-1ef1-a1a20030d675
* Content: [Having enough Domain Controllers for Windows Hello for Business deployments - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by MaratMussabekov** [comment]
Hello,
**It appears that DC Discovery process is different for WHfB clients and it does not use DCLocator process.** - can you please provide source for this information? 
As I understand, WHfB clients use Kerberos Key Distribution Center for authentication, which is discovered through *_kerberos._tcp.DnsDomainName* SRV record by DC Locator.
Thank you

**Comment by msft-jaiverma** [comment]
@MaratMussabekov  - DNS records _kerberos._tcp record does not differentiate between 2019 or 2016 or 2012r2 Domain Controllers. It appears that client uses DS_10 flag while using Netlogon service and calling dsgetdc with parameter DS_DIRECTORY_SERVICE_10_REQUIRED.

**Comment by MaratMussabekov** [comment]
Hello,
**It appears that client uses DS_10 flag while using Netlogon service and calling dsgetdc with parameter DS_DIRECTORY_SERVICE_10_REQUIRED** - yes, that's correct, but how this detail helps to better plan number of DCs? the article is pretty simple, says "plan enough WS 2016 domain controllers for each site that hosts WHfB users", i believe Kerberos flags are out of its scope.
Dear @mapalko , could you please advise?

Thank you

**Comment by mapalko** [comment]
It is also not clear to me why this specific detail is required for planning. It seems like it is more detail than needed for this particula article.

**Comment by nam31** [comment]
@msft-jaiverma Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
