### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by GreggRevak** [MicrosoftDocs/windows-itpro-docs#9295]
There is a broken link in the text:
For Azure AD enrollment to work for an Active Directory Federated Services (AD FS) backed Azure AD account, you must enable password authentication for the intranet on the ADFS service as described in solution #2 in this article.  The link referenced by the text "this article" (https://go.microsoft.com/fwlink/?LinkId=690246) is not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f06aa-8465-821f-6ad8-9c04f9be5291
* Version Independent ID: 0f2f73e7-8154-4f7f-a24b-841785c05dd6
* Content: [Azure Active Directory integration with MDM - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/azure-active-directory-integration-with-mdm)
* Content Source: [windows/client-management/mdm/azure-active-directory-integration-with-mdm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/azure-active-directory-integration-with-mdm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
- https://go.microsoft.com/fwlink/?LinkId=690246

The page can not be found, even when logged in on a Microsoft account, so we may as well just consider removing that reference with the link in it.

**Comment by illfated** [comment]
https://docs.microsoft.com/windows/client-management/mdm/azure-active-directory-integration-with-mdm#integrated-mdm-enrollment-and-ux
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/azure-active-directory-integration-with-mdm.md#integrated-mdm-enrollment-and-ux

For Azure AD enrollment to work for an Active Directory Federated Services (AD FS) backed Azure AD account, you must enable password authentication for the intranet on the ADFS service as described in solution \#2 in [this article](https://go.microsoft.com/fwlink/?LinkId=690246).

Once a user has an Azure AD account added to Windows 10 and enrolled in MDM, the enrollment can be manages through **Settings** > **Accounts** > **Work access**. Device management of either Azure AD Join for corporate scenarios or BYOD scenarios are similar.

**Comment by GreggRevak** [comment]
> * https://go.microsoft.com/fwlink/?LinkId=690246
> 
> The page can not be found, even when logged in on a Microsoft account, so we may as well just consider removing that reference with the link in it.

The content in the link is important and must be found as it is an integral part of the configuration process being detailed in the document. I suggest finding the reference, not just removing it.

**Comment by illfated** [comment]
(ref. #9299 )
