### ISSUE TITLE
Regarding the "Configure removal of items from Quarantine folder" Value "Default setting"

### ISSUE THREAD

**Issue by kahosoka** [MicrosoftDocs/windows-itpro-docs#9297]
[Enter feedback here]
Hello Team,

We would like you to revise the "Configure removal of items from Quarantine folder" value for "Default setting".
At present, it is described as "Never removed", but actually "90" is set when it is confirmed from the get-MpPreference command.
This should indicate that the default value is "Delete after 90 days".

Get-MpPreference Result:
PS C:\WINDOWS\system32> Get-MpPreference | out-string -stream | select-string "QuarantinePurgeItemsAfterDelay"
QuarantinePurgeItemsAfterDelay                : 90

PS C:\WINDOWS\system32>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6448160-696e-9823-ca37-b54189530890
* Version Independent ID: e1678a96-0bb7-87fb-1d3e-efcc5984c1fb
* Content: [Remediate and resolve infections detected by Microsoft Defender Antivirus - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-remediation-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/configure-remediation-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/configure-remediation-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@kahosoka . Thanks for pointing out. I will investigate soon and I willl change in article if necessary.

**Comment by RAJU2529** [comment]
@kahosoka, what you said is correct, i checked through the group policy editor, the default setting is 0, but when I checked through PowerShell default is  90.

again i configured to 30 days in GPO and then checked through PowerShell it shows 30 days.

**Comment by kahosoka** [comment]
@RAJU2529 Thank you for your response! 
When I checked the GPO, it was surely "0".
Checked the "MPSupportFiles.cab" contained in "MPRegistry.txt".
As a result, in the default state, "90" was registered in PurgeItemsAfterDelay of effective policy.
Therefore, we understand that the default value is not "Never removed" but "90".

**Comment by nam31** [comment]
Closing via #9314 
Thanks
