### ISSUE TITLE
Fix the table

### ISSUE THREAD

**Issue by Neeraj-6596** [MicrosoftDocs/windows-itpro-docs#930]
I'm guessing the "Feature type Feature Description Self-Service Server" parts were supposed to format as a table. Please fix so it's easier to read.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bb30d47-ff78-f104-c8b5-8a13c4c5ba8d
* Version Independent ID: 48629b17-253b-d85f-6285-7c1d656ef5ff
* Content: [Illustrated Features of an MBAM 2.5 Deployment](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/illustrated-features-of-an-mbam-25-deployment)
* Content Source: [mdop/mbam-v25/illustrated-features-of-an-mbam-25-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/illustrated-features-of-an-mbam-25-deployment.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by lizap** [comment]
Thanks for raising this issue - we've updated the article so the table is formatted correctly. Thank you!
