### ISSUE TITLE
Section of what data is collected by MDE

### ISSUE THREAD

**Issue by YulelogPagoda** [MicrosoftDocs/windows-itpro-docs#9300]
I'm sitting on the phone with a bank that wants to use this product and we've had four or five calls talking about data handling.... they want to have this data in very clear terms. 

_"file data (such as file names, sizes, and hashes)"?_ 
does that mean the files will be collected? 
_"process data (running processes, hashes)"_
does this mean the process memory? 

This kind of stuff has to be very specific.

**Comment by denisebmsft** [comment]
Hello @YulelogPagoda! Can you please tell us to which article(s) your feedback applies?

**Comment by YulelogPagoda** [comment]
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/data-storage-privacy

**Comment by denisebmsft** [comment]
@YulelogPagoda thank you!

**Comment by aczechowski** [comment]
Doing repo cleanup, I'm closing this issue as the article was moved to a new repo, you can find the current article at
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/data-storage-privacy?view=o365-worldwide
I'm sending this issue (and others for this area) to the current authors for their review. If there's still an update needed, please file new feedback on the current article in the other repo.
