### ISSUE TITLE
LogonCommand Directive is not updating Microsoft Edge when container is initialized

### ISSUE THREAD

**Issue by donguish** [MicrosoftDocs/windows-itpro-docs#9302]
The [Windows Sandbox Config page](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file) explains at [Logon command](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file#logon-command) how to specify the directive to execute a script inside the container after login (which I suppose means "initialization of the container?").

However I seem to be unable to initialize a Sandbox with an updated version Microsoft Edge.
At the time of writing pre-installed Edge version in Windows Sandbox is the old version (pre-chromium). The latest version works just fine if manually updated inside the container, however from script it doesn't initialize for lack of admin privileges (that actually makes some kind of sense being a sandbox?).

**WIndows Sandbox config file:**
```
<Configuration>
  <VGpu>Disable</VGpu>
  <MappedFolders>
    <MappedFolder>
      <HostFolder>D:\Sandbox\Shared</HostFolder>
      <SandboxFolder>C:\Users\WDAGUtilityAccount\Desktop</SandboxFolder>
      <ReadOnly>true</ReadOnly>
    </MappedFolder>
  </MappedFolders>
  <AudioInput>Disable</AudioInput>
  <ProtectedClient>Enable</ProtectedClient>
  <LogonCommand>
    <Command>C:\Users\WDAGUtilityAccount\Desktop\scripts\edgeUpdate.cmd</Command>
  </LogonCommand>
</Configuration>
```

**edgeUpdate.cmd script file:**
```
REM Download latest version of Edge
curl -L "https://go.microsoft.com/fwlink/?linkid=2108834&Channel=Stable&language=en" --output C:\users\WDAGUtilityAccount\Desktop\edge.exe

REM Install Edge
C:\users\WDAGUtilityAccount\Desktop\edge.exe /verysilent /suppressmsgboxes
```

I feel like the problem may be related to the fact that manually I am actually updating an existing version of the installed software, while from script I am asking to download new software and execute(?). :)

**Comment by e0i** [comment]
Hello,

Looks like this question can best be answered via relevant [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channels. 

Please consider checking with [Microsoft Community](https://answers.microsoft.com/en-us/windows/forum/windows_10) or [contacting support](https://support.microsoft.com/contactus) for your problem; The issues section of this repository is for content fixes in documentation.

If you feel that the associated article also needs to be updated for any reason feel free to re-open this issue or [contribute with a pull request](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/CONTRIBUTING.md).

Thank you.
