### ISSUE TITLE
Broken Links on the page

### ISSUE THREAD

**Issue by shubhamjain1704** [MicrosoftDocs/windows-itpro-docs#9304]
[Enter feedback here]
Reset Windows Update Client settings script and Reset Windows Update Agent script have broken links to technet website which redirects to https://docs.microsoft.com/en-in/samples/browse/?redirectedfrom=TechNet-Gallery.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-in/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment]
@shubhamjain1704 . all broken links in this article are already been esculated by other users. Microsoft documentation team working for new hosting site to upload

**Comment by RAJU2529** [comment]
@e0i .  I am going to add note in this article, about Microsoft documentation team is working on new hosting site to upload files.

**Comment by RAJU2529** [comment]
@nam31 . I already created PR for this issue #9305 . so please look into this PR
