### ISSUE TITLE
Defender ATP on OSX 11.2 

### ISSUE THREAD

**Issue by Treah** [MicrosoftDocs/windows-itpro-docs#9309]
Hey all I am sure you are aware of this but the information about fixing this issue says to run the below command. 
`sudo kextutil /Library/Extensions/wdavkext.kext`

on my system at least the above wdavkext.kext does not exist on the system to be able to run. Not sure if this is the version of the OS or the version of ATP that we are using.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72abfa66-ddf0-4fd6-152d-b66ebad98525
* Version Independent ID: c72a3ba7-cd9e-3b40-1bd6-dea45c5f690e
* Content: [Troubleshoot kernel extension issues in Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-support-kext#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-support-kext.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-support-kext.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
> Starting with macOS High Sierra (10.13), macOS requires all kernel extensions to be explicitly approved before they are allowed to run on the device.

Maybe you have not approved the extension, thereby making it denied by the OS?

**Comment by illfated** [comment]
(See also https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8353#issuecomment-732388278)

**Comment by Treah** [comment]
> (See also [#8353 (comment)](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8353#issuecomment-732388278))

Looked at that and the user never got back to you. Oddly mine kinda worked it self out without me having to do anything as defender went to a good status no longer complaining about a missing extension. So I think when the OS updates which they have been doing a lot recently it breaks the kernel extension or something and then gets reloaded down the line. I will check my good running system to see if that file came back into the file system location again tho and report back.

**Comment by VLG17** [comment]
@Treah As mentioned in [#8353 ](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8353#issuecomment-732388278) the file should be where it's stated. If it's not, then it's something specific to that system that should be troubleshooted further, but by default the file should be there.

**Comment by Treah** [comment]
I am not sure what to tell you because on my working OSX 11.2.3 system there is no file located in that location. 
The contents of /Library/Extensions/ is "HighPointIOP.kext, HighPointRR.kext, SoftRAID.kext" There is no file named wdavkext.kext and ATP is working correctly on this system. 
<img width="358" alt="OSXkext" src="https://user-images.githubusercontent.com/12091471/114050787-6b92a180-9841-11eb-8880-b1f046664a35.png">

**Comment by nam31** [comment]
@Treah  Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
