### ISSUE TITLE
Typo "[プロパティ]****"→"**\[プロパティ]**"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#9312]
Typo "[プロパティ]****"→"**\[プロパティ]**"

ja-jp: "https://docs.microsoft.com/ja-jp/windows/security/threat-protection/auditing/apply-a-basic-audit-policy-on-a-file-or-folder"
![apply-a-basic-audit-policy-on-a-file-or-folder_j](https://user-images.githubusercontent.com/40815708/111296372-c0525a80-868f-11eb-9067-b25b8aebd54b.png)

en-us: "https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/apply-a-basic-audit-policy-on-a-file-or-folder"
![apply-a-basic-audit-policy-on-a-file-or-folder_e](https://user-images.githubusercontent.com/40815708/111296380-c34d4b00-868f-11eb-8725-7f7c4d2cf6ec.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 9794457c-74fc-bb69-b3d9-071becdfbda4
* Version Independent ID: 532a2e78-0acd-7b53-9bb1-e90f33788eba
* Content: [ファイルまたはフォルダーに基本的な監査ポリシーを適用する (Windows 10) - Windows security](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/auditing/apply-a-basic-audit-policy-on-a-file-or-folder)
* Content Source: [windows/security/threat-protection/auditing/apply-a-basic-audit-policy-on-a-file-or-folder.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/apply-a-basic-audit-policy-on-a-file-or-folder.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
@TinaMcN can you please take a look at this?

**Comment by TinaMcN** [comment]
@hyoshioka0128 thanks for reporting it.  It is a known issue with the Machine Translation tool that *'s incorrectly appear in some content.  I hope we'll have a fix for this issue soon but in the meantime I sent this article to be human translated and it should be complete in approx. 3 days.

**Comment by TinaMcN** [comment]
@hyoshioka0128 the article has now been human translated and no ** appear.  If it looks ok to you now can you please close.  Thanks again for reporting it.
