### ISSUE TITLE
[LOC]Fixed inappropriate japanese "マルウェアと他の&について"→"マルウェアとその他の脅威について"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#9317]
[LOC]Fixed inappropriate japanese "マルウェアと他の&について"→"マルウェアとその他の脅威について"

ja-jp: "https://docs.microsoft.com/ja-jp/windows/security/threat-protection/intelligence/understanding-malware"
![understanding-malware_j](https://user-images.githubusercontent.com/40815708/111439632-e8ea5b00-8748-11eb-9b7f-262a828770ce.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 836636b4-7016-9076-1ef5-fc851ff62934
* Version Independent ID: b970ebb8-a0e1-86c0-eb44-af37d084f6a4
* Content: [マルウェアと他の&について - Windows security](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/intelligence/understanding-malware)
* Content Source: [windows/security/threat-protection/intelligence/understanding-malware.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/understanding-malware.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by nam31** [comment]
@TinaMcN, Can you please assist with this translation/localization issue?

**Comment by illfated** [comment]
Just to clarify, the correction is in the issue ticket title text:
- **マルウェアと他の&について** = "About Malware and Other &" (notice the incorrectly inserted Latin ampersand **&** within the kanji)
- **マルウェアとその他の脅威について** = "About malware and other threats"

**Comment by TinaMcN** [comment]
@hyoshioka0128 thank you for reporting the issue in this machine translated article and @illfated thanks for the clarification.  I sent the article to be human translated and it should be completed in ~3 days.

**Comment by TinaMcN** [comment]
@hyoshioka0128 the article has been human translated now.  Can you please check if it's ok now and close if it is.  Thanks!

**Comment by hyoshioka0128** [comment]
@TinaMcN | @illfated | @nam31 - Fixed. Thanks!
Closed #9317 .
