### ISSUE TITLE
Broken "Left pane"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#9318]
Broken "Left pane"

ja-jp: "https://docs.microsoft.com/ja-jp/windows/security/threat-protection/auditing/event-4670"
![event-4670](https://user-images.githubusercontent.com/40815708/111448441-c14bc080-8751-11eb-8b4e-8e2246c094a6.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e5862cc7-3f36-5f2e-9ade-f7441f99f818
* Version Independent ID: b8bd1985-7b5b-ea79-976a-7d96ad69335c
* Content: [Windows イベント転送を使用して侵入検出を支援する (Windows 10) - Windows security](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection)
* Content Source: [windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
EN-US page: https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4670

Ja-JP page: https://docs.microsoft.com/ja-jp/windows/security/threat-protection/auditing/event-4670

The Japanese page definitely shows an overlay issue from the left side pane into the rest of the page, making it close to impossible to report from the exact page in question.

The manual text box "Filter by title" in the TOC section is visibly too long, as well as some of the TOC links also overlay the center part of the page, covering the buttons from which to create a new issue ticket or give feedback on the product in question.

**Comment by illfated** [comment]
The page seems to be so badly broken, that even when using the \<Tab\> key to skip between linked parts of the main document on the page, there does not appear to be any Tab index entry for the button shown as
![image](https://user-images.githubusercontent.com/38162891/111517738-b09d4980-8755-11eb-97f4-35a3532e0c50.png)
at the bottom of the page https://docs.microsoft.com/ja-jp/windows/security/threat-protection/auditing/event-4670 , making it as good as impossible to create a new ticket from that page. Even browsing through the generated HTML code for the page, it does not appear to contain any link code for the "This page" button.

**Comment by illfated** [comment]
@TinaMcN : Could you ask the Machine Translation team check if it would be possible to restore the default functionality in this Japanese page?

**Comment by TinaMcN** [comment]
@hyoshioka0128 thank you for reporting this issue.  It is happening not just for Japanese but the other languages too.  @illfated I have seen this kind of issue before and it's most likely caused by an invalid html bold tags in the English content, probably left over from when this content was migrated from .html to .md format.
![image](https://user-images.githubusercontent.com/53281468/111528654-a90e7e00-871e-11eb-8198-ae9b4ffa00a9.png)
Can you please remove the <b> tags from the English topic, then I can get the article relocalized and hopefully fix the problem in the localized pages.

**Comment by illfated** [comment]
> @hyoshioka0128 thank you for reporting this issue. It is happening not just for Japanese but the other languages too. @illfated I have seen this kind of issue before and it's most likely caused by an invalid html bold tags in the English content, probably left over from when this content was migrated from .html to .md format.
> ![image](https://user-images.githubusercontent.com/53281468/111528654-a90e7e00-871e-11eb-8198-ae9b4ffa00a9.png)
> Can you please remove the tags from the English topic, then I can get the article relocalized and hopefully fix the problem in the localized pages.

Thank you very much, that is an excellent point. Sure thing, I can make a PR to suggest a removal of the invalid tags.

**Comment by illfated** [comment]
There you go. PR #9328 is ready for review, comments, and suggestions.

**Comment by TinaMcN** [comment]
PR #9328 is closed and the left pane looks ok now.  @hyoshioka0128 can you please close it?

**Comment by hyoshioka0128** [comment]
@TinaMcN @ghost - Thanks! Fixed.
Closed #9318 .
