### ISSUE TITLE
zip file doesn't contain file instructions expect

### ISSUE THREAD

**Issue by natedogith1** [MicrosoftDocs/windows-itpro-docs#9320]
The instructions state that the downloaded zip will contain mdatp_onboarding.json, but after downloading I find it contains MicrosoftDefenderATPOnboardingLinuxServer.py which seems to create the json file when run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 623e0469-826c-5cdf-6dc4-67c80e232d0f
* Version Independent ID: 0f6c33bc-711a-84d6-01bb-04d13f5a85a2
* Content: [Deploy Microsoft Defender ATP for Linux with Ansible - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by konstruktoid** [comment]
Hi @natedogith1, can you verify that you downloaded the correct zip file?

![image](https://user-images.githubusercontent.com/7956715/111820848-e0755a00-88d9-11eb-8613-975a2a1dff73.png)

**Comment by natedogith1** [comment]
Seems that "Local Script" was incorrectly selected instead of "Your preferred Linux configuration management tool".
