### ISSUE TITLE
Is this 1.2 or 2.0

### ISSUE THREAD

**Issue by kgold2** [MicrosoftDocs/windows-itpro-docs#9322]
I wonder if this page is for TPM 1.2.  I have TPM 2.0 and I don't see a way to change the owner password.  BTW, it's not a random number.  It's empty.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c91ae55-29b0-a5e1-b715-a72ac4270050
* Version Independent ID: a102db60-b94c-573a-6ba9-9970d9ac5b44
* Content: [Change the TPM owner password (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/change-the-tpm-owner-password)
* Content Source: [windows/security/information-protection/tpm/change-the-tpm-owner-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/tpm/change-the-tpm-owner-password.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@kgold2 . TPM v1.2

**Comment by kgoldman** [comment]
It does say TPM 1.2 way down in the text for one item, but the title still says TPM.  Since most, maybe all, Windows 10 systems, require TPM 2.0, the ambiguous title can mislead the reader.

**Comment by nam31** [comment]
Closing via #9332 
Thank you

**Comment by illfated** [comment]
https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/change-the-tpm-owner-password is updated. Thank you, all.
