### ISSUE TITLE
Explain why did Microsoft changed defaults 

### ISSUE THREAD

**Issue by mailinglists35** [MicrosoftDocs/windows-itpro-docs#9325]
Please explain in detail the reasoning of changing default behaviour (NT/2000 workstations required ctrl alt del, xp and up no longer required ctrl-alt-del)

I never understood why did Microsoft made this flip of defaults. It would make a very interesting read if you could explain how you all sat down and decided that you would no longer show "press ctrl-alt-del to logon" on login screen.

Was it a burden for users to press ctrl-alt-del? Were too many users with disabilities affected by this? Something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37a73a55-d78f-64cc-4764-51f3e0a87d4c
* Version Independent ID: 68ee2547-18a5-ad1c-725d-c2a8960c7f54
* Content: [Interactive logon Do not require CTRL+ALT+DEL (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-do-not-require-ctrl-alt-del)
* Content Source: [windows/security/threat-protection/security-policy-settings/interactive-logon-do-not-require-ctrl-alt-del.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/interactive-logon-do-not-require-ctrl-alt-del.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
@mailinglists35 Thank you for providing feedback.
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mailinglists35** [comment]
I this the entire Feedback hub content should be migrated to a github issues repository and the FH app should be simply eol'd or become a frontend to the github issues.
