### ISSUE TITLE
Use Microsoft Endpoint Manager to turn on cloud-delivered protection steps are totally wrong

### ISSUE THREAD

**Issue by NicklasHalme** [MicrosoftDocs/windows-itpro-docs#9326]
The title and steps for turn on cloud-delivered protection in Microsoft Endpoint Configuration Manager is totally wrong.
Should be something like this:

TITLE: Use Microsoft Endpoint Configuration Manager to turn on cloud-delivered protection
STEPS:
Open the Microsoft Endpoint Configuration Manager console.
Navigate to \Assets and Compliance\Overview\Endpoint Protection\Antimalware Policies.
Select the "Default Client Antimalware Policy" (or create new Antimalware Policy).
Select Properties. Then click "Cloud Protection Service".
Define the appropriate settings. For more information please see: https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/endpoint-antimalware-policies#cloud-protection-service
Click OK once ready.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f8ccc01-1b04-e443-ef75-6ffe6c866dd5
* Version Independent ID: fa2eaa0f-db04-785a-3894-8244947b9cd5
* Content: [Turn on cloud-delivered protection in Microsoft Defender Antivirus - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/enable-cloud-protection-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/enable-cloud-protection-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by VLG17** [comment]
@NicklasHalme The steps described in the article are for Microsoft Endpoint Manager. which Configuration Manager is part of.

![image](https://user-images.githubusercontent.com/41186174/118453326-c0a6ba80-b6ff-11eb-9ef5-55d485e4acd8.png)

The last paragraph from section "Use Microsoft Endpoint Manager to turn on cloud-delivered protection" contains the [link you mentioned](https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/endpoint-antimalware-policies#cloud-protection-service) regarding configuring Microsoft Endpoint Configuration Manager.

![image](https://user-images.githubusercontent.com/41186174/118453475-efbd2c00-b6ff-11eb-870a-4eea936639ea.png)
