### ISSUE TITLE
customer_tenant_id switch support for the new Microsoft 365 security portal

### ISSUE THREAD

**Issue by SergGu** [MicrosoftDocs/windows-itpro-docs#9329]
Security Center https://securitycenter.windows.com?tid=customer_tenant_id is working fine as documented. But we can not find a similar option for a new https://security.microsoft.com/ portal. Is there an option for the new Microsoft 365 security portal?
Please document if available or note down that this feature does not exist today.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89a134d0-e7f2-a215-e885-c66919a87982
* Version Independent ID: 1c278d45-94fe-d1b4-adff-1b1b3ddbb1d8
* Content: [Access the Microsoft Defender Security Center MSSP customer portal - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/access-mssp-portal)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/access-mssp-portal.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/access-mssp-portal.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by SergGu** [comment]
After some testing i found [https://security.microsoft.com?tid=customer_tenant_id](https://security.microsoft.com?tid=customer_tenant_id) working for a new Microsoft 365 security portal, but not every time. The browser need to be freshly opened and "clean" of previous login sessions.

**Comment by VLG17** [comment]
@SergGu  I see both the docs and [the blog](https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/multi-tenant-access-for-managed-security-service-providers/ba-p/1533440) you commented on talk about using: **https://securitycenter.Microsoft.com/?tid=<CustomerTenantId>**

And you pointed out that **https://security.microsoft.com?tid=customer_tenant_id** worked for you.

Are you saying that **https://securitycenter.Microsoft.com/?tid=<CustomerTenantId>** does not work at all? I'm just trying to understand what needs to be added/changed in article you linked.

**Comment by mjcaparas** [comment]
@SergGu Please refer to: https://docs.microsoft.com/en-us/microsoft-365/security/defender/mssp-access?view=o365-worldwide#manage-access
