### ISSUE TITLE
[MVP Request] I am having difficulties interpreting these log failures. Please help

### ISSUE THREAD

**Issue by Sumitdhiman** [MicrosoftDocs/windows-itpro-docs#933]
Hi, Sumit Dhiman an Insider MVP this side. Can you please check these. I can't find any trace why the upgrade failed.
https://1drv.ms/f/s!AnFlXCjVbtMviRDF_mI1k8pj0Nst
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a97de48f-e863-7786-5958-c76a831486e5
* Version Independent ID: b0dc0baf-e3d0-fba5-e2ac-9c6de32e4aab
* Content: [Submit Windows 10 upgrade errors using Feedback Hub](https://docs.microsoft.com/en-us/windows/deployment/upgrade/submit-errors)
* Content Source: [windows/deployment/upgrade/submit-errors.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/submit-errors.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by andreabichsel** [comment]
Hi Sumit, we can only address doc feedback. You'll get a better response if you submit these to the Feedback Hub feedback-hub:///?referrer=resolveUpgradeErrorsPage&tabid=2&contextid=81&newFeedback=true&feedbackType=2&topic=submit-errors.md. Thank you!
