### ISSUE TITLE
missing update sources

### ISSUE THREAD

**Issue by obaidanwarshaikh** [MicrosoftDocs/windows-itpro-docs#9331]
The excel sheet containing update sources/URLs is missing a few critical update sources:

Windows Defender (MpCmdRun.exe)
definitionupdates.microsoft.com
go.microsoft.com

Reference: https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1803-endpoints#windows-defender

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83207fc9-2c91-eb07-4237-6bb1f42e3778
* Version Independent ID: 5db33cf3-2dcb-bb33-a252-3a13ca9737f9
* Content: [Configure device proxy and Internet connection settings - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by obaidanwarshaikh** [comment]
this is the document that needs updating: https://download.microsoft.com/download/8/a/5/8a51eee5-cd02-431c-9d78-a58b7f77c070/mde-urls.xlsx

**Comment by mjcaparas** [comment]
I believe the sheet has now been updated.

**Comment by obaidanwarshaikh** [comment]
yes the links are there now, thanks.
