### ISSUE TITLE
Content filter instructions

### ISSUE THREAD

**Issue by PhantomPhixer** [MicrosoftDocs/windows-itpro-docs#9335]
[1. Jamf now has support for content filter settings built in so can be set in the interface
2. the scoping needs explaining better as some should only be scoped to macOS11 and others only to less than 11]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f791dc07-b2c6-3003-a829-cd1ec03a2918
* Version Independent ID: 2c53adbc-600f-60b2-e8b2-b907335f4862
* Content: [Set up the Microsoft Defender ATP for macOS policies in Jamf Pro - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@PhantomPhixer Thank you for bringing this up. I've created a PR to address the first point. Regarding the second one, can you think of a wording that you would like to see in the article related to the scope?

In my opinion there are just to many variables to keep in mind when scoping and it's subjective to each environment.

**Comment by PhantomPhixer** [comment]
I had forgotten about this! For the scoping it's a matter of matching scopes to profile types. E.G. don't deploy KEXT to 10.11 or 12.x.  and no point deploying system extensions to 10.10  as they don't work.
would also be far simpler if you  had the profiles downloadable as either plists or mobile config's to allow direct importing to any MDM system, stops typo's and frustration.
