### ISSUE TITLE
Revision request for translation/localization

### ISSUE THREAD

**Issue by yoshiband** [MicrosoftDocs/windows-itpro-docs#9336]
[フィードバックをこちらに入力してください]
Hello, whom it may concern,

I found a mistake in the Japanese version of this page.

Wrong
> 一方、アクションが "許可" に設定されている場合、Microsoft Defender AV はファイルの実行を検出またはブロックします。

Correct
> 一方、アクションが "許可" に設定されている場合、Microsoft Defender AV はファイルの実行を検出もブロックもしません。

The correspond sentence in the original English is as follows
> On the other hand, if the Action is set to "Allow", Microsoft Defender AV will not detect nor block the file from being run.

So, the original sentence says "will not detect nor block the file", which means denial meaning.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 50f2be10-41a0-67ae-222b-1b073bef537b
* Version Independent ID: 3f186b13-aad0-4ba4-e239-d9bb24ff2ebe
* Content: [インジケーターを作成する - Windows security](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-atp/manage-indicators)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/manage-indicators.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/manage-indicators.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by denisebmsft** [comment]
@TinaMcN can you take a look?

**Comment by TinaMcN** [comment]
@yoshiband thank you for reporting this issue.  It appears to be a machine translation issue.  I sent the article to be human translated and it should be done within 3 days.

**Comment by TinaMcN** [comment]
@yoshiband the article is human translated now.   I hope the issue is fixed now, please let me know if it's not ok.
