### ISSUE TITLE
Clarifications on supported versions for Device Health Monitoring

### ISSUE THREAD

**Issue by v-rechau** [MicrosoftDocs/windows-itpro-docs#9339]
This CSP page mentions that Device Health Monitoring is not available for any Windows 10 devices running Pro.

Meanwhile, the related documentation about the Intune Data Collection Policy which enables the Device Health Monitoring on the device states that the feature is available for Windows 10 Pro versions 1903 and up, similar to the Enterprise version, as long as they have the required Update KBs installed.

> [https://docs.microsoft.com/en-us/mem/analytics/troubleshoot#bkmk_2016281112](https://docs.microsoft.com/en-us/mem/analytics/troubleshoot#bkmk_2016281112)
> Startup performance insights are only available for devices running version 1903 or later of Windows 10 Enterprise, Education, or Pro. 
> Windows 10 Pro versions 1903 and 1909 require KB4577062.
> Windows 10 Pro versions 2004 and 20H2 require KB4577063.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bc61164-274e-73af-5b02-c89411eed714
* Version Independent ID: 808cc715-2577-9cf2-3b95-ed464aaf8847
* Content: [Policy CSP - DeviceHealthMonitoring - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-devicehealthmonitoring)
* Content Source: [windows/client-management/mdm/policy-csp-devicehealthmonitoring.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-devicehealthmonitoring.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
( ref. #9409 )

**Comment by nam31** [comment]
Closing via #9409 
Thank you
