### ISSUE TITLE
This document recommends a different setting for “Turn off Microsoft Defender Antivirus.” than what other document suggest (the latter actually fixed issue for customer))

### ISSUE THREAD

**Issue by anaguile** [MicrosoftDocs/windows-itpro-docs#9341]
[ From RAVE case 24527130   https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mcafee-to-microsoft-defender-setup#enable-microsoft-defender-antivirus-on-your-windows-client-devices recommends “Turn off Microsoft Defender Antivirus.” to be set to "Disabled" but https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/use-group-policy-microsoft-defender-antivirus says it should be “Not Configured” instead to ensure any installed third-party antivirus apps work correctly, that setting is what actually fixed the problem in customer's scenario, which was Defender not going into passive mode despite being onboarded on MDE with McAfee AV installed (they provided the feedback that this should be addressed/corrected).]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89449bef-485d-caff-f3a5-c892b3d33056
* Version Independent ID: 669feff2-5757-3c24-c803-28d6ad2f8d12
* Content: [McAfee to Microsoft Defender for Endpoint - Setup - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mcafee-to-microsoft-defender-setup#enable-microsoft-defender-antivirus-on-your-windows-client-devices)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mcafee-to-microsoft-defender-setup.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mcafee-to-microsoft-defender-setup.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@anaguile . Turn off Microsoft Defender Antivirus  set to Disabled means still Microsoft Defender runs background.

Turn off Microsoft Defender Antivirus. set to Enabled means  Microsoft Defender is turned off.

**Comment by RAJU2529** [comment]
PR #9343 is  complicated , i taken care while editing this article, so i request reviewers to review changed parts must be reviewed.

**Comment by anaguile** [comment]
@RAJU2529 
i checked the document and it still shows the same statement:
3. Choose Edit policy setting, and make sure that policy is disabled. This enables Microsoft Defender Antivirus.

I understood this was changed, can you confirm this is the case?

**Comment by RAJU2529** [comment]
@anaguile . changes will be visible after few days

**Comment by illfated** [comment]
The commit (https://github.com/MicrosoftDocs/windows-itpro-docs/commit/5118d9868ffe59c63308c1040ada40a61485bc15) changes here on GitHub have still not migrated to docs.microsoft.com as of the time of this comment:
- https://docs.microsoft.com/microsoft-365/security/defender-endpoint/mcafee-to-microsoft-defender-setup?view=o365-worldwide
(still showing the document date **03/03/2021**)

**Comment by illfated** [comment]
Looks like the target document has been moved to the following location:
- https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mcafee-to-microsoft-defender-setup.md

Not sure if the linked PR and its resulting commit will be migrated there, but we could try asking the team members if this will be handled in the private repository `MicrosoftDocs-pr` (only visible for team members).

**Comment by anaguile** [comment]
@RAJU2529 , @illfated 

Just to make sure, the original suggested change does not seen to be replicated yet. I was informed that changes should be visible after a few days. 

Usually, how long does this take?

**Comment by anaguile** [comment]
Just in case:

the suggested change was from:
3. Choose Edit policy setting, and make sure that policy is disabled. This enables Microsoft Defender Antivirus.

to:
3. Choose Edit policy setting, and make sure that policy is Not Configured. This enables Microsoft Defender Antivirus.

This based on https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/use-group-policy-microsoft-defender-antivirus as it reads:

Turn off Microsoft Defender Antivirus | Not used (This setting must be set to Not configured to ensure any installed third-party antivirus apps work correctly)


The above was also confirmed on a customer case, where changing "Turn off Microsoft Defender Antivirus" to "Not Configured" solved the problem (Defender not running in passive mode when another 3rd party A/V (McAfee) is active)

**Comment by illfated** [comment]
@anaguile : Please open a new issue ticket based on the new location of the document. To continue posting here will slow down any attempts we make to follow up on your comments, since this ticket references the wrong page.
