### ISSUE TITLE
Incorrect command for collecting current RTP statistics

### ISSUE THREAD

**Issue by larsakerlund** [MicrosoftDocs/windows-itpro-docs#9342]
The article mentions that the following command is used for collecting real-time protection statistics, which is the same command as enabling real-time protection:

```bash
mdatp config real-time-protection --value enabled
```

In order to output the statistics and follow the rest of the article, the following command must be run instead:

```bash
mdatp diagnostic real-time-protection-statistics --output json > real_time_protection.json
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14a27ce8-3346-683a-8b6c-96407d83842b
* Version Independent ID: 58315d85-ae54-2708-7404-8597cb493604
* Content: [Troubleshoot performance issues for Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-support-perf)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-support-perf.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-support-perf.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
This issue has already been fixed from another branch. Closing via https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4919#issuecomment-857242264

Thanks.
