### ISSUE TITLE
boot

### ISSUE THREAD

**Issue by planksta** [MicrosoftDocs/windows-itpro-docs#9344]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c795c8ef-7caf-b8a7-4118-b00b1899eef8
* Version Independent ID: cd85b6b4-d160-0c44-15ea-4b7c02fbe0eb
* Content: [Secure the Windows 10 boot process - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/secure-the-windows-10-boot-process)
* Content Source: [windows/security/information-protection/secure-the-windows-10-boot-process.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/secure-the-windows-10-boot-process.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@planksta . No proper description.

**Comment by e0i** [comment]
Missing feeedback.
