### ISSUE TITLE
Setting Expectations

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#9345]
How long does it take after an access package is created before it is ready to be used? please provide some timeframes so that we know what to expect.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b37e3a59-0253-44ec-074a-8910c1f35fc1
* Version Independent ID: 5fbabf34-55a4-7220-a0e9-d0a26c115bff
* Content: [Grant access to managed security service provider (MSSP) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/grant-mssp-access)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/grant-mssp-access.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/grant-mssp-access.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by joinimran** [comment]
Hello @DeanGross - Thank you for your query, Please note that access packages once ready are ready to be used. There is no wait time for this. But yes, you can setup the package life cycle to define the expiry of the package. See https://docs.microsoft.com/en-us/azure/active-directory/governance/entitlement-management-access-package-create#lifecycle for details.

Thanks
Imran.

**Comment by nam31** [comment]
@DeanGross Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
