### ISSUE TITLE
Web Content Filtering Policy Refresh seems more than 2 hours

### ISSUE THREAD

**Issue by Shwet88** [MicrosoftDocs/windows-itpro-docs#9346]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d1d825-ab12-2f37-b692-5266487ef16f
* Version Independent ID: fef750ac-311b-28b4-1661-16385997815b
* Content: [Web content filtering - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/web-content-filtering)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/web-content-filtering.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/web-content-filtering.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by Shwet88** [comment]
I recently have enabled the web content filtering policy for some of my workstations, and have noticed its taking much more than 2 hours to get it refreshed and applied to required devices. almost a day. 
I have noticed the time lag in both Microsoft Edge and Chrome, and in Chrome its even more, suspicious sites remained unblocked for more than a day. 
If the policy refresh is dependent on some factors please advise on that and same can also be updated on this article's page.

**Comment by nam31** [comment]
@Shwet88 Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)
Thank you.
