### ISSUE TITLE
Incorrect Instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#9349]
I do not see the Settings/Alert Notification menu item that is described in the instructions. I think that this may have been moved/renamed when the portals were consolidated. Please review and update as appropriate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71efdf59-617b-c2cb-301c-145aa43b0890
* Version Independent ID: a9e5313e-9000-0e6b-2ca2-be066116f69b
* Content: [Configure alert notifications in Microsoft Defender for Endpoint - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-email-notifications#create-rules-for-alert-notifications)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-email-notifications.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-email-notifications.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by nam31** [comment]
Closing via https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4551
Thank you
