### ISSUE TITLE
Please add links to SCCM content if you mention it

### ISSUE THREAD

**Issue by cliffhobbs** [MicrosoftDocs/windows-itpro-docs#935]
In one of the "Note" sections you state:

"You can also add these features to an online image by using either DISM or Configuration Manager."

It would be REALLY good if you could make this a hyperlink to the relevant area in the SCCM Docs that tell me HOW to do it in SCCM as I can't find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by DaniHalfin** [comment]
Hi @cliffhobbs - we don't have any specific guidance to enable Windows features through Configuration Manager. It would come down to creating a configuration baseline that enables this feature either through DISM or PowerShell. 

Do you feel like it would be beneficial to link out to guidance on how to create and configure configuration baselines in Configuration Manager?
