### ISSUE TITLE
Link for "Security policy violation indicators" under Share endpoint alerts with Microsoft Compliance Center is not getting redirected properly.

### ISSUE THREAD

**Issue by vikassou** [MicrosoftDocs/windows-itpro-docs#9350]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d99de0-789d-3c71-4bd9-f45e62f82a7b
* Version Independent ID: d56d09f0-1f9a-563e-fee0-142bda27a99b
* Content: [Configure advanced features in Microsoft Defender for Endpoint - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/advanced-features#share-endpoint-alerts-with-microsoft-compliance-center)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/advanced-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/advanced-features.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Thank you for pointing out that 404 error. That is definitely a mishap from when the link was added or converted in the source document.

**Comment by illfated** [comment]
By the way, it would be useful if most of the text had been entered in the comment post instead of the title, but I assume it is the result of not being aware of the ticket format when posting from the reporting page (I don't remember what the reporting page looks like at the moment).
