### ISSUE TITLE
Clarification on startup scripts needed for single vs multiple entry per device

### ISSUE THREAD

**Issue by DavidSchrag** [MicrosoftDocs/windows-itpro-docs#9354]
I am confused about the script(s) to run at startup and the choice to have single vs. multiple entries per device.

The article says 

> If you are not implementing a single entry for each device, copy WindowsDefenderATPOnboardingScript.cmd.
> If you are implementing a single entry for each device, copy both Onboard-NonPersistentMachine.ps1 and WindowsDefenderATPOnboardingScript.cmd.

Later it says

> For single entry for each device:
> Select the PowerShell Scripts tab, then click Add (Windows Explorer will open directly in the path where you copied the onboarding script earlier). Navigate to onboarding PowerShell script Onboard-NonPersistentMachine.ps1.

> For multiple entries for each device:
> Select the Scripts tab, then click Add (Windows Explorer will open directly in the path where you copied the onboarding script earlier). Navigate to the onboarding bash script WindowsDefenderATPOnboardingScript.cmd.

So the first section indicates that the single entry per device option requires both the .ps1 and the .cmd script, because both have to be copied. But the second section indicates that the single entry option requires only the .ps1 script, because there is no instruction to add the .cmd script to the GPO.

Perhaps the .ps1 script calls the .cmd script, and that's why it's not necessary to have both triggered by the startup script GPO? If so, it would be helpful to clarify that, because as it is, the instructions look contradictory.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804f2883-5de4-9d54-d0b4-e64b04984aa8
* Version Independent ID: 0ab9ee92-c5e1-0455-92ba-ed07ed7bd140
* Content: [Onboard non-persistent virtual desktop infrastructure (VDI) devices - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi#onboard-non-persistent-virtual-desktop-infrastructure-vdi-devices-1)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-vdi.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by MaratMussabekov** [comment]
Hello @DavidSchrag ,
**Perhaps the .ps1 script calls the .cmd script** - yes, it does, it is seen on the line 82 of the script.
Thank you

**Comment by nam31** [comment]
Closing via https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4554
Thank you

**Comment by JonathanPitre** [comment]
Can you please clarify what's the difference between option 1 and option 2 ?

Also, why is the DeviceTagging reg value gets apply with the ps1 when the article clearly says it's only applicable to Windows 2008 R2 ?

See Line 129 of the Onboard-NonPersistentMachine.ps1 script
See documentation at https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-vdi?view=o365-worldwide
![image](https://user-images.githubusercontent.com/15003329/213327472-80f3a841-814b-4bc9-b1d3-3aa94eca8506.png)
