### ISSUE TITLE
Missing documentation for Microsoft.Gaming.Install.InstallActivity event

### ISSUE THREAD

**Issue by riverar** [MicrosoftDocs/windows-itpro-docs#9355]
The Diagnostic Data Viewer app lists events labeled `Microsoft.Gaming.Install.InstallActivity`, presumably related to Xbox services built into Windows. This telemetry appears to be **required** and **not documented**.

![image](https://user-images.githubusercontent.com/475132/112058580-fd976c00-8b17-11eb-9132-07166d3778ad.png)

I've also previously filed this feedback on Feedback Hub: https://aka.ms/AAbma2r

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43f50265-384b-fe61-c722-8c736878fc02
* Version Independent ID: e715c498-6512-7823-32ce-483130a68af1
* Content: [Windows 10, version 20H2 and Windows 10, version 2004 required diagnostic events and fields (Windows 10) - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/required-windows-diagnostic-data-events-and-fields-2004)
* Content Source: [windows/privacy/required-windows-diagnostic-data-events-and-fields-2004.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/required-windows-diagnostic-data-events-and-fields-2004.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by illfated** [comment]
Thank you for referencing your post on the Feedback Hub. Hoping we will get some tech feedback for the documentation sooner or later.

**Comment by brianlic-msft** [comment]
Thank you for bringing this to our attention. After investigation, we determined that this is a bug and will be fixed.

**Comment by siosulli** [comment]
Closing out this issue as the approval for this event has been removed so a doc update wasn't required. 
It has been fixed it on the backend.

**Comment by riverar** [comment]
@brianlic-msft Got it, thanks!

**Comment by siosulli** [comment]
Thanks for clarification @brianlic-msft!
