### ISSUE TITLE
Windows 10 1803

### ISSUE THREAD

**Issue by Gaz2600** [MicrosoftDocs/windows-itpro-docs#936]
Does this process work on Win10 1803?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140f038c-e307-78f0-5165-309e0cf34ca5
* Version Independent ID: b1011259-ee05-21a4-5308-aabc8b0dd74b
* Content: [Configure Windows 10 taskbar (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/configure-windows-10-taskbar)
* Content Source: [windows/configuration/configure-windows-10-taskbar.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/configure-windows-10-taskbar.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@Gaz2600 Yes, it should. If you encounter problems on 1803 with the process, please submit feedback to the engineering team via the Feedback Hub, thanks!
