### ISSUE TITLE
Documentation on PlumbIKEv2TSAsRoutes option?

### ISSUE THREAD

**Issue by tomdan-MSFT** [MicrosoftDocs/windows-itpro-docs#9360]
The document currently shows the PlumbIKEv2TSAsRoutes option in the tree at the top of the article but there's no explanation below on what this option actually sets on the VPN client.  Can we get more details added to the document on the PlumbIKEv2TSAsRoutes option?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8b1b81d-3c35-0315-d149-f10af3a409b2
* Version Independent ID: c34e7acb-ece7-d76f-fb41-470e19119ee0
* Content: [VPNv2 CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp)
* Content Source: [windows/client-management/mdm/vpnv2-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/vpnv2-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
I tried searching the entire docs.microsoft.com site for at least some information about "PlumbIKEv2TSAsRoutes", but came up with nothing:
- https://docs.microsoft.com/en-us/search/?terms=PlumbIKEv2TSAsRoutes

(Sorry for making it look like a meme, but "Wow, such empty." comes to mind.)

**Comment by nam31** [comment]
Closing via #9468  
Thank you
