### ISSUE TITLE
Extra "\" characters listed for paths to files

### ISSUE THREAD

**Issue by tomdan-MSFT** [MicrosoftDocs/windows-itpro-docs#9361]
Near the top of the article we list a path for files that include extra "\" :

The XSDs for all EAP methods are shipped in the box and can be found at the following locations:

C:\\Windows\\schemas\\EAPHost
C:\\Windows\\schemas\\EAPMethods

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8b1b81d-3c35-0315-d149-f10af3a409b2
* Version Independent ID: c34e7acb-ece7-d76f-fb41-470e19119ee0
* Content: [VPNv2 CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp)
* Content Source: [windows/client-management/mdm/vpnv2-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/vpnv2-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@tomdan-MSFT . Thanks for pointing out.
