### ISSUE TITLE
How do PINS differ from Passwords 

### ISSUE THREAD

**Issue by lericah** [MicrosoftDocs/windows-itpro-docs#9365]
So if a PIN becomes more complex is it not just a password? Doesn't this make computers more vulnerable since people are familiar with complex passwords buy they associate a PIN with a 4-digit code?

Importantly if I login to computer A and B with the same Microsoft account; will A and B have 2 seperate,  locally stored PINS or can I login to computer B with Computer A's PIN

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c34dbafa-df3c-a5a5-32d5-2ce152893534
* Version Independent ID: cebdd9a6-45d7-6306-373c-7d31121f9e16
* Content: [Why a PIN is better than a password (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password#pin-can-be-complex)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by RAJU2529** [comment]
PIN is stored in local machine and does not stored in Microsoft account.
Moreover  PIN can create only after enabling of Fingerprint reader by scanning of Fingerprint.
I think both fingerprint and PIN are both stored in TPM module.

**Comment by lericah** [comment]
I don't have a fingerprint reader on the laptop in question and I don't
have a fingerprint even associated with that Microsoft Business Account

**Comment by nam31** [comment]
@lericah Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)
Thank you.
