### ISSUE TITLE
Unclear Supported values

### ISSUE THREAD

**Issue by BoomRaccoon** [MicrosoftDocs/windows-itpro-docs#9367]
[Enter feedback here]
It's not stated what the default value for Networking and ClipboardRedirection is. I presume it's 'Enable' but it would be good to clearly state that.
Adding the missing value would make it consistent throughout the page.

Have a good one.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2efc9d32-0f98-0804-78a4-4caccdfac010
* Version Independent ID: 797bb0d3-bade-98f6-fe85-508764571f37
* Content: [Windows Sandbox configuration - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
To me, just by reading the document (even though I don't know this topic yet), it is clear that those values are already defined and described as you requested:

***
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file#networking :

### Networking

Enables or disables networking in the sandbox. You can disable network access to decrease the attack surface exposed by the sandbox.

`<Networking>value</Networking>`

Supported values:
- *Disable*: Disables networking in the sandbox.
- *Default*: This is the default value for networking support. This value enables networking by creating a virtual switch on the host and connects the sandbox to it via a virtual NIC.

***
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file#clipboard-redirection :

### Clipboard redirection

Enables or disables sharing of the host clipboard with the sandbox.

`<ClipboardRedirection>value</ClipboardRedirection>`

Supported values:
- *Disable*: Disables clipboard redirection in the sandbox. If this value is set, copy/paste in and out of the sandbox will be restricted. 
- *Default*: This is the default value for clipboard redirection. Currently copy/paste between the host and sandbox are permitted under *Default*.

***
The default value for both of those settings is ***Default***, which in this case means "Enabled". The only other option is to **Disable** the feature in question.

**Comment by MaratMussabekov** [comment]
Hello @BoomRaccoon ,
I agree with @illfated , these parameters doesn't support "Enabled" value. They only have "Disable" and "Default".

Thank you

**Comment by nam31** [comment]
@BoomRaccoon Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Comment by BoomRaccoon** [comment]
I did some testing and am confused now and realized I'd have to look at XML first to understand how this works.

@illfated I am not even sure about that anymore. You can input anything and it just goes to default, you can even input some random XML tags.
I sure just thought that 'Enable' is implemented but wasn't 100% sure because it's not listed.
Ignoring all that. My main issue is that it just looks inconsistent having it listed for some and omitted for others. Changing it everywhere like in vGPU, you'd be able to shorten the explanation of 'Default' and place that in 'Enable'.

@MaratMussabekov Actually @illfated  said 'it is clear that those values are already defined and described as you requested' so that would mean they are supported. But again, testing showed me you can actually input any crazy stuff without an error.

Sorry for the late response.

**Comment by illfated** [comment]
@BoomRaccoon : Based on what you are saying, I would assume that the only supported manual value is "Disabled", while whatever you write other than that, it becomes enabled.

Disclaimer: I do not have access to hardware or software required to test that assumption, but that is my logical conclusion based on your comment, 
\<Note\> given that your test scenario is not influenced at all by any other software or configuration changes \</Note\> .

**Comment by illfated** [comment]
Caveat emptor: Please also note that I have no experience whether some form of AutoUpdate or Refresh or similar is required to read the new values.

**Comment by MaratMussabekov** [comment]
Hello,
yes, just adding "disable" and "enable" values would be much better and it would be consistent with other features. However, it is a product issue, not a documentation issue, the article just describes product as it is.
Thank you
