### ISSUE TITLE
Issues with wildcard exclusion documentation

### ISSUE THREAD

**Issue by mb-northwave** [MicrosoftDocs/windows-itpro-docs#9368]
In the table under heading "Use wildcards in the file name and folder path or extension exclusion lists":

Text for wildcard "*" reads:
`C:\somepath\*\Data would include any file in C:\somepath\Archives\Data and its subfolders and C:\somepath\Authorized\Data and its subfolders`
The phrase "and its subfolders" should not be "code" on both cases.

Text for wildcard "?" reads:
`C:\MyData\my? would include C:\MyData\my1.zip
`
I assume that is incorrect, I would expect that to only match "C:\MyData\my1", but not the ".zip" part.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cb87dc6-ceae-eeae-795c-bf13a308155f
* Version Independent ID: 185ce073-3086-4152-2bed-d1aff8f94aa7
* Content: [Configure and validate exclusions based on extension, name, or location - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-extension-file-exclusions-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/configure-extension-file-exclusions-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/configure-extension-file-exclusions-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
(ref. #9372 )

**Comment by denisebmsft** [comment]
thank you @mb-northwave for letting us know about this issue. And thank you @MaratMussabekov for your pull request. I've accepted your changes and the updates will render live later today. I'm going to close this issue but please let us know if you have any further questions.
