### ISSUE TITLE
Protected domains and Network domains

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#9369]
Hello,

Can you please share more information in which case should be added the Protected domains and Network domains,
And what kind, is it a user account domain that the user uses to login into tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df27add-73fe-4f0b-7e30-face0f95cda3
* Version Independent ID: 3ec647d9-3470-8d8b-a941-d56f6522a35e
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @lightupdifire ,
**Can you please share more information in which case should be added the Protected domains and Network domains,** - as it is already stated in the article, protected domains - domains used for identities in your environment (for example, used for UPN suffixes). Network domains - all other DNS suffixes used in your environment.
**And what kind, is it a user account domain that the user uses to login into tenant?** - yes, for Protected domain, you should use domain user uses to login.

For example: company abc.com purchased company def.com. All users from def.com were transferred to abc.com domain, but some resources (applications) are still in old domain. In this case abc.com will be Protected domain, def.com - Network domain.

Thank you

**Comment by lightupdifire** [comment]
@MaratMussabekov
But is it mandatory or optional to add to this section?

**Comment by MaratMussabekov** [comment]
Hello, it is optional.
thank you

**Comment by lightupdifire** [comment]
Hello @MaratMussabekov 
What is the difference then between:
Protected domain and Corporate identity domain?
How they work together, they do the same thing? Can you please explain more?

**Comment by MaratMussabekov** [comment]
Hello @lightupdifire ,
they are the same. Corporate identity is the primary one, any additional domain that is also used for identity could be added as "protected domain".
Thank you

**Comment by lightupdifire** [comment]
Hello @MaratMussabekov 
So as an example we have 4x managed domains:
1. qwe.com
2. asd.com
3. zxc..com
4. iop.com

The iop.com is the primary one, so we will add it to the Corporate identity domain section.
If we will not add 1-2-3 domains in the protected domains, the data still is encrypted and it shows the Corporate identity domain "iop.com".
If we add the 1-2-3 domains in the protected domains, the data will be the encrypted same way? And the Corporate identity domain "iop.com" will be still shown on the encrypted data?

**Comment by MaratMussabekov** [comment]
Hello,
**If we add the 1-2-3 domains in the protected domains, the data will be the encrypted same way?** - yes
**And the Corporate identity domain "iop.com" will be still shown on the encrypted data?** - yes
Thank you

**Comment by lightupdifire** [comment]
@MaratMussabekov Thanks for the information, maybe good to add in FAQ? If not, then I will close this case.
