### ISSUE TITLE
Typo in item 25. Windows Spotlight last bullet DisableWindowsConsumerFeatures: HKEY_LOCAL_MACHINE_MACHINE

### ISSUE THREAD

**Issue by CJMakris** [MicrosoftDocs/windows-itpro-docs#9373]
The last bullet point in Section 25. Windows Spotlight (https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services#25-windows-spotlight) references a key containing a hive that should not exist:

`HKEY_LOCAL_MACHINE_MACHINE\SOFTWARE\Policies\Microsoft\Windows\CloudContent`

This should likely be corrected to:

`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\CloudContent`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abd3113-b803-87b6-ef7f-6893bcc5ceb5
* Version Independent ID: 6f7ca1ee-d19c-42bb-7db5-6158fc160e32
* Content: [Manage connections from Windows 10 operating system components to Microsoft services - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services)
* Content Source: [windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @linque1
* Microsoft Alias: **robsize**

**Comment by illfated** [comment]
Wow, that looks like a copy-paste error to me. Thank you for reporting this. "`HKEY_LOCAL_MACHINE_MACHINE`" sounds like someone forgot to turn off the echo machine... ;-)

Anyway, I will get right to it and open a Pull Request to have that "copy-pasta" removed.

**Comment by illfated** [comment]
`*sigh*` — it took more time than I expected to search for the origin of this confounded typo/copy-paste error.

Commit: https://github.com/MicrosoftDocs/windows-itpro-docs/commit/2c9314b0f63141b6aaa993d76644c087b0253906 (**Consumer endpoints** (#86))

Pull Request: **From private repo** #3422 (May 2, 2019)

Commit line: https://github.com/MicrosoftDocs/windows-itpro-docs/commit/2c9314b0f63141b6aaa993d76644c087b0253906#diff-22e2027c57658f70e0196237e2d931d00bc79100df2ab6dc2f105016ab1ef5b7R2042

```
- Create a new REG_DWORD registry setting named **DisableWindowsConsumerFeatures** in **HKEY_LOCAL_MACHINE\_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent** with a **value of 1 (one)**
```
***
- Create a new REG_DWORD registry setting named **DisableWindowsConsumerFeatures** in **HKEY_LOCAL_MACHINE\_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent** with a **value of 1 (one)**

***

Still looks like a copy-paste error, so I can only SMH at the fact that nobody noticed this enough to report it before now.

**Comment by illfated** [comment]
Pull Request #9374 is ready for review, comments and suggestions. Feel free to visit the page.

**Comment by siosulli** [comment]
This has been fixed as part of https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9373
