### ISSUE TITLE
What about Server 2019?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#9375]
Many of the pages in this section do not state that they apply to Windows Server 2019. Do they, if so, please update the pages to explicitly state this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 298f0a3a-6bf5-7ee8-db4a-21548ad8a22d
* Version Independent ID: 11ee3f53-ed64-7a84-0a7b-ba94c7ff09b1
* Content: [Isolated Domain (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/isolated-domain)
* Content Source: [windows/security/threat-protection/windows-firewall/isolated-domain.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/isolated-domain.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
Closing via #9470 
Thank you
