### ISSUE TITLE
Notes on how to access the EFI partition would be handy

### ISSUE THREAD

**Issue by haymansfield** [MicrosoftDocs/windows-itpro-docs#9376]
Notes on how to access the EFI partition would be handy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ff92b92-8c0f-e92f-43ff-7e2df4b4468b
* Version Independent ID: e48742d4-5066-5758-f207-ac3c424e0d75
* Content: [Disable Windows Defender Application Control policies  (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/disable-windows-defender-application-control-policies)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/disable-windows-defender-application-control-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/disable-windows-defender-application-control-policies.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@haymansfield . I will give you steps afternoon

**Comment by nam31** [comment]
@haymansfield Thank you for providing feedback.
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
Thank you for your contribution to make the docs better! Much appreciated!
