### ISSUE TITLE
Error in 4624(S) docs

### ISSUE THREAD

**Issue by ashmohabd** [MicrosoftDocs/windows-itpro-docs#9377]
There’s an error in “Workstation Name” description. It says “machine name *to* which logon attempt was performed.” It should be *from* which.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aefbbdcc-606c-276c-47ee-fe2b2cb65c61
* Version Independent ID: e0979867-e6bc-7fb9-1279-646b319823b0
* Content: [4624(S) An account was successfully logged on. (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624)
* Content Source: [windows/security/threat-protection/auditing/event-4624.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4624.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Based on the description in the document, I would say that you are correct in reporting that as an issue. Ref. the following part of the document:

***

<img src="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/images/event-4624.png" alt="Event 4624 illustration" width="438" height="668" hspace="12" align="left" />

***Subcategory:***&nbsp;[Audit Logon](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-logon)

***Event Description:***

This event generates when a logon session is created (on destination machine). It generates on the computer that was accessed, where the session was created.

> **Note**&nbsp;&nbsp;For recommendations, see [Security Monitoring Recommendations](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624#security-monitoring-recommendations) for this event.

***

Notice in particular the Workstation Name in this snippet, `WIN-GG82ULGC9GO`, which is a typical Windows-generated computer name (possibly a VM instance?).

![image](https://user-images.githubusercontent.com/38162891/112895168-13d79600-90dd-11eb-8ddf-94932e9913f6.png)

***
<br>
I will have a go at making a PR to correct that glitch, in addition to checking the text for possible phrasing improvements and formatting issues.

**Comment by illfated** [comment]
There you go. PR #9378 is ready for review, comments, and suggestions.
