### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/windows-itpro-docs#9381]
The "Special Groups" links are broken.  They had valuable information such as the registry keys needing to be set for auditing special groups after configuring the advanced audit settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef7bc351-2473-a6f8-542f-8f03f0d640eb
* Version Independent ID: b5d9a985-092c-6beb-4bf8-dd18549f58fc
* Content: [Audit Special Logon (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-special-logon)
* Content Source: [windows/security/threat-protection/auditing/audit-special-logon.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/audit-special-logon.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
Closing via #9384 
Thank you

**Comment by poortom1004** [comment]
Doesn't seem like this has been resolved.  As for the broken links, there are 3 of them. All of them are links to the same exact URL. If you simply search for "Special Groups", you will quickly find them. The URLs for those links should be updated to https://techcommunity.microsoft.com/t5/ask-the-directory-services-team/special-groups-auditing-via-group-policy-preferences/ba-p/395095
