### ISSUE TITLE
Update Extend code documentation for new releases

### ISSUE THREAD

**Issue by Sumitdhiman** [MicrosoftDocs/windows-itpro-docs#9387]
I see that under the extended code phase table, only 5 phases are described. On the new releases of Windows 10, I see some reports of 600XX error code as well. Possible to update this, please?

https://answers.microsoft.com/en-us/windows/forum/all/windows-10-upgrade-failed-to-2004/c7fa508a-3a5f-4e8e-8543-37823d4cfd7e

https://techcommunity.microsoft.com/t5/windows-insider-program/help-unable-to-update-insider-build-to-new-version/m-p/2191444

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b70118b1-730b-8e97-20a1-1d8cf0f33d53
* Version Independent ID: b3db47a2-df6a-03d0-1cdf-3e90017e7824
* Content: [Upgrade error codes - Windows IT Pro - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-error-codes)
* Content Source: [windows/deployment/upgrade/upgrade-error-codes.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/upgrade-error-codes.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by MaratMussabekov** [comment]
Hello, this issue was already discussed in https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2301
Dear @greg-lindsay , is there any update regarding adding codes for finalize phase?
Thank you!

**Comment by greg-lindsay** [comment]
I have a task in my backlog to update the process phases for Windows Setup. However, the preference now is to use the SetupDiag tool to analyze upgrade errors and not refer to the codes listed here. Sorry I cannot update this page at this time.
