### ISSUE TITLE
Registry keys for provisioned apps - wrong syntax

### ISSUE THREAD

**Issue by happybear88** [MicrosoftDocs/windows-itpro-docs#939]
This reg-file won't work. The first two lines should be
```
Windows Registry Editor Version 5.00
;1709 Registry Keys
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9c3129d-3c8d-b508-f298-3333499bb180
* Version Independent ID: 97b70720-82d8-60a4-3958-00ceed34aa1b
* Content: [How to keep apps removed from Windows 10 from returning during an update](https://docs.microsoft.com/en-us/windows/application-management/remove-provisioned-apps-during-update)
* Content Source: [windows/application-management/remove-provisioned-apps-during-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/remove-provisioned-apps-during-update.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Anoni-Mouse** [comment]
It isn't only confusing but also frustrating. Each Windows build has its own apps that are slightly different from the other builds. Microsoft isn't making this easy especially for enterprise admins who require preparing Windows images to deploy them with SCCM or MDT. Windows Enterprise/Professional are a toy operating systems. We want something like Windows 7, a real OS ready for enterprise, not a toy OS with lots of built-in apps and packages that are useless! Even the simple Calculator or calc.exe was removed as a win32 application and replaced by a horrible app! What the heck Microsoft! If I had an alternative to the simplicity of Windows I would have switched to that OS long time ago!

**Comment by Heidilohr** [comment]
I've updated the document to correct the syntax. The update should appear this afternoon.

**Comment by R2D2components** [comment]
Please stop you progress on this device or computer. This is not a company computer or device it is a personal home device or computer. Around this time our system was attacked and we do not authorize any app changes or reconfiguring of any kind please contact me quickly

Jason Robertson

**Comment by Heidilohr** [comment]
@R2D2components This is a question best answered by [Microsoft Support](https://support.microsoft.com/).
