### ISSUE TITLE
What keys are used for signing 

### ISSUE THREAD

**Issue by CXMelga** [MicrosoftDocs/windows-itpro-docs#9390]
Hello,
Great article but can you please help me with the following to clarify

When I think of signing I think of the following scenario

When signing a message you need to use a 'key' this key needs to be trusted by the other side (either they use the same key aka symmetric or they trust the public key asymmetric). 

So my questions is which keys are in use here when it comes to signing (I assume symmetric) and how are they derived (created) and stored) ? for example does it use Diffie–Hellman key exchange to arrive at a shared key?

Please advise

Charlie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4aad5771-d5cd-4bad-09ed-4e63dad74fcf
* Version Independent ID: b2b80b51-9152-56d1-4719-52e9d6aba281
* Content: [Network security LDAP client signing requirements (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-ldap-client-signing-requirements)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-security-ldap-client-signing-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-security-ldap-client-signing-requirements.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello, 
asymmetric keys are used, keys are exchanged during [TLS handshake](https://docs.microsoft.com/en-us/windows/win32/secauthn/tls-handshake-protocol)
also recommend to read [this article](https://social.technet.microsoft.com/wiki/contents/articles/2980.ldap-over-ssl-ldaps-certificate.aspx)

Thank you
