### ISSUE TITLE
Missing current GA released platform build info 

### ISSUE THREAD

**Issue by bledMS82** [MicrosoftDocs/windows-itpro-docs#9391]
Needs updated with the March release info 

AMEngineVersion                 : 1.1.18000.5
AMProductVersion                : 4.18.2103.3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5b2e02d-b56d-00d5-b4c6-0a76aa88f2af
* Version Independent ID: 0f82785d-7014-22d7-6b7e-a995b3ab0814
* Content: [Manage Microsoft Defender Antivirus updates and apply baselines - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/manage-updates-baselines-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/manage-updates-baselines-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/manage-updates-baselines-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thank you @bledMS82. Docs will be updated ASAP. I am working on this.

**Comment by denisebmsft** [comment]
The article has been updated and how has the latest updates.
