### ISSUE TITLE
Is that last section entirely correct?

### ISSUE THREAD

**Issue by TwattyBollox** [MicrosoftDocs/windows-itpro-docs#9392]
The last part, states that:

"System-managed page files automatically grow up to three times the physical memory or 4 GB (whichever is larger) when the system commit charge reaches 90 percent of the system commit limit. This assumes that enough free disk space is available to accommodate the growth."

Whereas other pages include:

"3 × RAM or 4 GB, whichever is larger. _This is then limited to the volume size ÷ 8._
However, it can grow to within 1 GB of free space on the volume if required for crash dump settings.

So, is that still correct? Does it indeed limit it to 1/8 the size of the drive?
It's important, as most 240GB SSDs would only alow a maximum of 30GB, whereas most 16GB RAM systems would need 48GB at 3xRAM ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e75e49c-84c9-d8ee-f8c0-9363ff51da93
* Version Independent ID: eb5feac0-5692-1cc5-a6b4-48a50d57e316
* Content: [Introduction to the page file - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/introduction-page-file)
* Content Source: [windows/client-management/introduction-page-file.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/introduction-page-file.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by e0i** [comment]
@TwattyBollox Your feedback is under investigation. Thanks for the catch.

**Comment by MaratMussabekov** [comment]
Hello,
**So, is that still correct? Does it indeed limit it to 1/8 the size of the drive?** - yes, it is correct. Checked on a computer with 80Gb C: drive with 16Gb ram. Pagefile never grow for more than 1/8 of the volume size.
Thank you

**Comment by TwattyBollox** [comment]
Hi ... why was this reopened?

**Comment by e0i** [comment]
Hello, The PR haven’t had been merged by the time I have re-opened the issue. Closing now as it has been merged. Thank for following up.
