### ISSUE TITLE
Incorrect reference to Patch Tuesday

### ISSUE THREAD

**Issue by tryste-mx** [MicrosoftDocs/windows-itpro-docs#9395]
This Article > Configure when devices receive Quality Updates > "Quality updates are typically published on the first Tuesday of every month..."

This is incorrect; quality updates are published on the **_second_** Tuesday of every month.

-tryste

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1684b30a-3187-85ce-0cf7-10d1b8298b7f
* Version Independent ID: 9b7170fc-2b39-8e46-7898-894a45de8623
* Content: [Configure Windows Update for Business (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-configure-wufb)
* Content Source: [windows/deployment/update/waas-configure-wufb.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-configure-wufb.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
( ref. #9402 )
