### ISSUE TITLE
Incorrect UPN for MDT_JD account

### ISSUE THREAD

**Issue by jfpanisset** [MicrosoftDocs/windows-itpro-docs#9398]
The userPrincipalName for an AD account is defined as "upn prefix" @ "upn suffix" where the suffix is typically the DNS domain name:

https://docs.microsoft.com/en-us/windows/win32/ad/naming-properties

This is also documented for the -UserPrincipalName of New-ADUser:

https://docs.microsoft.com/en-us/powershell/module/addsadministration/new-aduser?view=winserver2012r2-ps&viewFallbackFrom=windowsserver2019-ps

So under step 1.2, the sample PowerShell command to create the MDT_JD domain joiner account should likely read:

New-ADUser -Name MDT_JD -UserPrincipalName MDT_JD@CONTOSO.COM ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
( ref. PR #9406 )

**Comment by nam31** [comment]
Closing via #9406 
Thank you
