### ISSUE TITLE
Enable Cloud-Delivered Protection - MECM Section Missing

### ISSUE THREAD

**Issue by AndyWilsonIT** [MicrosoftDocs/windows-itpro-docs#9399]
Hi there

I was just reviewing this documentation and noticed there are no directions for enabling cloud-delivered protection via Configuration Manager specifically. Initial summary indicates this is possible:

> - Microsoft Intune
> - Microsoft Endpoint **Configuration** Manager
> - Group Policy
> - PowerShell cmdlets

But the subsequent section headers don't reflect this, substituting MECM for Microsoft Endpoint Manager (i.e. Intune).

Hope this helps. If I am right about this, it would be useful to know to process for MECM if that can be shared, as it is something I'm currently looking at (though I suspect I may well be able to work it out soon enough anyway).

Thanks
Andy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b28135e-60e4-8872-ebe5-bc56c00e3869
* Version Independent ID: e6504d3d-0e50-4a5d-e996-dfdf67c88a91
* Content: [Turn on cloud-delivered protection in Microsoft Defender Antivirus - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/enable-cloud-protection-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/enable-cloud-protection-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by nam31** [comment]
Closing via [#4838](https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4838)
Thank you
