### ISSUE TITLE
Confusing content - not clear which PowerShell cmdlet it applies to

### ISSUE THREAD

**Issue by happybear88** [MicrosoftDocs/windows-itpro-docs#940]
The whole article is very confusing, because it never mentions the actual cmdlet(s) that result in the issue. For example, in this statement "If you removed the packages by running a PowerShell cmdlet on the device while Windows was online."

It appears, the issue occurs when only the following command was used
`Get-AppXProvisionedPackage -online | Remove-AppxProvisionedPackage -online`

However, it's not clear whether the issue occurs if the following command was **also** used:
`Get-AppXPackage -AllUsers | Remove-AppxPackage -AllUsers`

Probably not, but you've got to make it clear. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9c3129d-3c8d-b508-f298-3333499bb180
* Version Independent ID: 97b70720-82d8-60a4-3958-00ceed34aa1b
* Content: [How to keep apps removed from Windows 10 from returning during an update](https://docs.microsoft.com/en-us/windows/application-management/remove-provisioned-apps-during-update)
* Content Source: [windows/application-management/remove-provisioned-apps-during-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/remove-provisioned-apps-during-update.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by mariuselix** [comment]
well, this doesn't only apply to PowerShell...for example, I'm building a C# WPF application that updates from one W10 version to the other in an enterprise environment and I need to use this.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by j0rt3g4** [comment]
Taken considerations on this thread on PR #3146

**Comment by mypil** [comment]
@happybear88 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
