### ISSUE TITLE
Trusted Signal is not possession factor

### ISSUE THREAD

**Issue by RichardvanNuland** [MicrosoftDocs/windows-itpro-docs#9400]
I am missing information that describes that the phone (or network) as trusted signal second factor should not be considered a 'possession' factor. When I connect a mobile phone using bluetooth as "user A" then this device is paired on device level. So when "user B" logs on and the phone of "user A" is still within range, it still acts as 2nd factor unlock.

This means that true MFA for data on the device itself is still not realised.

Another aspect is that with PIN + Trusted Signal you are in a ackward situation when something happens with your phone or when you are in a location where you need to switch off your phone (e.g. airplane).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f8c2ce-8edb-60d3-ebf9-bdb625bf66dc
* Version Independent ID: ee1ed0a8-b05c-c499-6504-40b5b298c53b
* Content: [Multi-factor Unlock - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/feature-multifactor-unlock)
* Content Source: [windows/security/identity-protection/hello-for-business/feature-multifactor-unlock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/feature-multifactor-unlock.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by VLG17** [comment]
@RichardvanNuland When we talk about MFA with Multi-factor Unlock it's in the context of Windows Hello, meaning we are talking about protecting **identities**, not the device where you are logging on to using your identity. So what the article describes is correct, related to protecting identities.

The scenario that you are describing, although a valid one, refers to the device itself, which should (and can) be protected with other authentication methods, that could lock out user B completely.

Regarding your second point, in my opinion it's a matter of user education. There are a lot of corner cases like the one you presented (facilities where you are not allowed to use your phone for example) where you will be unable to leverage your selected Trusted provider, but one should be aware of these and user education can contribute to that.

**Comment by RichardvanNuland** [comment]
I am a bit lost about this response. With Windows Hello for Business you want to protect the identities. This applies for both user A and user B. The issue here is that the (access key to the) identity can be retrieved by only using the PIN. And the PIN is always the fallback factor. What other authentication methods can prevent this? What is the Microsoft solution to provide true MFA to the (access keys to the) identity that is on the device itself?

Face Recognition + PIN : OK, but doesn’t always work
Fingerprint + PIN : OK, but doesn’t always work
PIN alone: NOK, required fallback method, can be secured further:
PIN + Trusted Signal: NOK --> And now? Should we give all our employees also an expensive Security Key?

Regards,
Richard

**Comment by hbogit** [comment]
Dear mister Greco. Unaware of all the effort building for internet and its users you put in it I also did not ask you if I could use the addon de-bugger. I just did. Sorry for that. I know in this situation it much to ask but would you geld me one more time. It is not only you that I have to be grateful for, but all the people that helped me. I don't know who but trying to find. You're help and from all they others will not be unappreciated. So my second wish is if you could help to find these wonderful people as you are. This help will not be unappreciated. Han

**Comment by Aarojas3012a** [comment]
Revelopement resusge

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Onur ***@***.***>
Enviado: Thursday, August 18, 2022 8:41:18 AM
Para: MicrosoftDocs/windows-itpro-docs ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: Re: [MicrosoftDocs/windows-itpro-docs] Trusted Signal is not possession factor (#9400)


Closed #9400<https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9400> as not planned.

**Comment by hbogit** [comment]
Please don't remove this from the link below

**Comment by hbogit** [comment]
Mijn telefoon voorspelt tekst. Hier komt de volgende boodschap uit;

" Ik wil je nog steeds een beetje op tijd thuis zijn en dat is een probleem met de instellingen en dat ik al die tijd nog niet ontvangen hebben we het niet zo lang u een keer met Bitdefender en ik kan het me ook niet herinneren dat ik een kleine toelichting op het bericht dat de eerste keer met je verjaardag ik wens jullie heel veel plezier en succes met Bitdefender."

Op dit moment ben ik niet ingelogd bij Bitdefender. Wat is nodig om af te kunnen ronden? Ik heb zo'n behoefte aan duidelijkheid!

Han
