### ISSUE TITLE
Around#1Microsoft365Live_I_Love_gitbuh

### ISSUE THREAD

**Issue by Aarojas3012a** [MicrosoftDocs/windows-itpro-docs#9403]
Manuel Aarón Rojas Salinas 
Microsoft Developer World
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1290b230-fb6a-705b-00ca-c0fd63f08d18
* Version Independent ID: 6c9b1a0b-6544-31bf-f409-b48e5e55eb79
* Content: [Enable offline upgrades to Windows 10 for Windows Embedded 8.1 Handheld devices - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/enable-offline-updates-for-windows-embedded-8-1-handheld-devices-to-windows-10)
* Content Source: [windows/client-management/mdm/enable-offline-updates-for-windows-embedded-8-1-handheld-devices-to-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enable-offline-updates-for-windows-embedded-8-1-handheld-devices-to-windows-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Looks like a test comment.

#please-close

**Comment by Aarojas3012a** [comment]
> Manuel Aarón Rojas Salinas
> Microsoft Developer World
> [Enter feedback here]
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 1290b230-fb6a-705b-00ca-c0fd63f08d18
> * Version Independent ID: 6c9b1a0b-6544-31bf-f409-b48e5e55eb79
> * Content: [Enable offline upgrades to Windows 10 for Windows Embedded 8.1 Handheld devices - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/enable-offline-updates-for-windows-embedded-8-1-handheld-devices-to-windows-10)
> * Content Source: [windows/client-management/mdm/enable-offline-updates-for-windows-embedded-8-1-handheld-devices-to-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enable-offline-updates-for-windows-embedded-8-1-handheld-devices-to-windows-10.md)
> * Product: **w10**
> * Technology: **windows**
> * GitHub Login: @ManikaDhiman
> * Microsoft Alias: **dansimp**
