### ISSUE TITLE
registry path does not exist

### ISSUE THREAD

**Issue by ayushidera** [MicrosoftDocs/windows-itpro-docs#9405]
the registry path "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge" does not exist in my registry key.
i want to disable "open in chrome" pop up when I'm using Microsoft edge.

**Comment by RAJU2529** [comment]
@ayushidera Which article are you referring to

**Comment by nam31** [comment]
@ayushidera , can you please let us know the article you are referring to?

**Comment by illfated** [comment]
@ayushidera : Without a link to the document where you have found this registry key, we are unable to do anything to improve the documentation.

To be clear, I am unable to locate any MicrosoftDocs documents containing that specific registry key, even when searching all of GitHub (public repositories). Are you sure you haven't confused any documents belonging to some other repository, maybe outside of the Microsoft organization?

**Comment by nam31** [comment]
@ayushidera We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve. Thank you.
