### ISSUE TITLE
Device based policy paths that are equivalent seems wrong

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/windows-itpro-docs#9408]
From my reading the example seems wrong.
> For device wide configuration the Device/ portion may be omitted from the path, deeming the following paths respectively equivalent:
> 
> ./Vendor/MSFT/Policy/Config/AreaName/PolicyName to configure the policy.
> ./Vendor/MSFT/Policy/Result/AreaName/PolicyName to get the result.

I suspect this intended to say this...
./Device/Vendor/MSFT/Policy/Config/AreaName/PolicyName
./Vendor/MSFT/Policy/Config/AreaName/PolicyName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef67aab0-cd98-5bd9-1285-14d6f6dcc881
* Version Independent ID: 12055585-601f-596b-8620-120f52ec392c
* Content: [Policy CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-configuration-service-provider#policies)
* Content Source: [windows/client-management/mdm/policy-configuration-service-provider.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-configuration-service-provider.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Not sure I follow what you are suggesting. The [important] note blob seems to explain it quite correctly as is:

![image](https://user-images.githubusercontent.com/38162891/114478469-9a709500-9bfe-11eb-9819-9ebd3547f8e8.png)

**Comment by MaratMussabekov** [comment]
Hello, I believe author meant that they are equivalent to the paths above, not equivalent to each other.
I will create a PR
Thank you!

**Comment by illfated** [comment]
Fair enough, thank you for interpreting the issue ticket differently from my interpretation. 👍🏻

**Comment by nam31** [comment]
Closing via #9453 
Thank you
