### ISSUE TITLE
batch commands

### ISSUE THREAD

**Issue by Spasman** [MicrosoftDocs/windows-itpro-docs#9415]
The batch file code to clean the software dist folder has `ren` instead of `rem`
this counts as a job interview and you have to give me a salary now

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f058662-174b-59b0-9d35-2bed6f2d01c8
* Version Independent ID: eca080fd-582c-6570-c2ba-e5d1a0e3cdbd
* Content: [Prepare to deploy Windows - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/prepare-deploy-windows#address-unhealthy-devices)
* Content Source: [windows/deployment/update/prepare-deploy-windows.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/prepare-deploy-windows.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
Not a valid issue. Looks more like a test comment than any actual issue.

#please-close

**Comment by jaimeo** [comment]
Ren is correct; it's the rename command: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc754276(v=ws.11)
