### ISSUE TITLE
There really needs to be some clarification somewhere about the difference between "Real-Time Protection" and "On-Access Protection." Both are configurable and this doc is the only reference to "On-Access Protection" but does not define what it does or why the two can be enabled independently of each other.

### ISSUE THREAD

**Issue by zebulonsmith** [MicrosoftDocs/windows-itpro-docs#9417]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b1ab2e-1964-5580-7c99-4bd4cd480075
* Version Independent ID: f7b5da46-04cb-3501-65fa-870a3c6f09b8
* Content: [Policy CSP - Defender - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#defender-allowonaccessprotection)
* Content Source: [windows/client-management/mdm/policy-csp-defender.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-defender.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
@zebulonsmith : Thank you for creating this ticket. Could I ask you to edit this ticket by moving the entire title text to the main ticket comment, while leaving a shorter description in the title?

Suggestion for a title text:
- **Policy CSP - difference between "Real-Time Protection" and "On-Access Protection"**

**Comment by e0i** [comment]
@illfated It’s OK. The title is descriptive enough.

@zebulonsmith Under investigation. Thanks for the feedback.

**Comment by zebulonsmith** [comment]
Thanks, all!

**Comment by joinimran** [comment]
Hello @zebulonsmith - Thank you for putting your query. Please note that Real-time protection ensures that activities include events, such as processes making unusual changes to existing files, modifying or creating automatic startup registry keys and startup locations (also known as auto-start extensibility points, or ASEPs), and other changes to the file system or file structure.

Whereas On-Access protection gives your system protection when the files are accessed or downloaded.  See https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-windows-10 get more understanding on On-Access protection.

Specific to this document, this is made up with a template to provide basic information regarding policy CSPs. So this information can't be added to the document. 

Thanks
Imran.

@e0i - FYI Please.
