### ISSUE TITLE
This page mentions Windows 10 Mobile/Phone. That product has been retired years ago.

### ISSUE THREAD

**Issue by AMeeus** [MicrosoftDocs/windows-itpro-docs#9418]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 286cc7cd-bdc1-a8ef-db31-429ea5f6a2a5
* Version Independent ID: baef37c3-ed11-b4cc-4ac0-19d08ee6e0f0
* Content: [Assign devices to servicing channels for Windows 10 updates (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-servicing-channels-windows-10-updates)
* Content Source: [windows/deployment/update/waas-servicing-channels-windows-10-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-servicing-channels-windows-10-updates.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
( ref. #9454 )

**Comment by nam31** [comment]
Closing via #9454 
Thank you
