### ISSUE TITLE
Test-NetConnection and a list of Peers

### ISSUE THREAD

**Issue by treestryder** [MicrosoftDocs/windows-itpro-docs#9420]
In the section titled "Clients aren't able to connect to peers offered by the cloud service" it is suggested to install the Telnet client to test a connection to a TCP port. This can also be done with the native Powershell cmdlet Test-NetConnection.

    Test-NetConnection -ComputerName 192.168.9.17 -Port 7680

Found this page while looking for a way to list Delivery Optimization Peers. As I believe we have misconfigured peering and are connecting to more than we intended. If there is a way to list Peers, please add it to the Troubleshooting section.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb67e518-6f60-23e0-2545-c2839e2b4159
* Version Independent ID: e9a31629-e3cb-0367-31c4-5661284d89bf
* Content: [Delivery Optimization for Windows 10 updates - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization)
* Content Source: [windows/deployment/update/waas-delivery-optimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-delivery-optimization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
From https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization-setup#monitor-delivery-optimization

"Starting in Windows 10, version 2004, Get-DeliveryOptimizationStatus has a new option -PeerInfo which returns a real-time list of the connected peers."

**Comment by treestryder** [comment]
Thank you @jaimeo , so it does. Interesting. I am unsure who these peers are. Based on their IP addresses, they certainly are not on my network. 

For others, that command would be very handy in the Troubleshooting section.

**Comment by illfated** [comment]
> I am unsure who these peers are. Based on their IP addresses, they certainly are not on my network.

Correct me if I am mistaken, but isn't there an option to select if you want to allow connections to peers only on your local network or if you want to allow connections from everywhere outside as well?

**Comment by treestryder** [comment]
There is, but we are new to this and the options are not obvious. We are looking to restrict the peering to both PCs in our domain AND PCs on the same local area network. I see now that our chosen Download Mode "HTTP blended with peering across a private group (2)" will peer only with devices in our domain, however it will peer outside of the LAN. Not seeing an option that achieves both of our desires, this is probably our best option, as we are concerned about malicious peers. 

It was seeing the number of peers that alerted me that this wasn't working as expected, and "Get-DeliveryOptimizationStatus -PeerInfo" that showed the peers were outside of my home LAN, and it is [this documentation](https://docs.microsoft.com/en-us/mem/intune/configuration/delivery-optimization-settings) that I am trusting for those peers (shown as random looking IP addresses, as so many are working from home) being members of our domain.

**Comment by nam31** [comment]
Closing via #9492 
Thank you
