### ISSUE TITLE
Hyperlinks not working

### ISSUE THREAD

**Issue by Saibaschbeis** [MicrosoftDocs/windows-itpro-docs#9422]
Hyperlinks on this site are not working (e.g. "configure custom policies" link).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c3e60ec-cf61-c34b-db79-74b13e3ee867
* Version Independent ID: fc5079f7-a563-c627-3a3e-eb84a99e4fd3
* Content: [New policies for Windows 10 (Windows 10) - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/new-policies-for-windows-10)
* Content Source: [windows/client-management/new-policies-for-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/new-policies-for-windows-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Hello @Saibaschbeis and thank you for the feedback. This particular article isn't being updated, but here is a link you can try for information about configuring policies in Intune: https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-policy

I hope this helps!
