### ISSUE TITLE
Enterprise / Education environment Scenario post about Win10 Home

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/windows-itpro-docs#9423]
Can you clarify / make a Scenario post about what is pretty standard in the Enterprise / Education environment.  Which is:

We buy devices with Windows 10 Home because we have site-wide licenses for MS products and can "upgrade" / re-image via SCCM to Windows 10 Enterprise and KMS activate them.  This saves us $30-$40 per machine ordered.

Moving to Intune / MDM in a WorkFromHome world.  With Subscription Activate we have KMS activated Windows 10 Enterprise devices with an underlying Win10 Home Digital Key and all this documentation is about Win10 Pro.  Further reading seems to imply it's only for Win10 Pro but other things I've read say it should work...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6443e532-640d-81c0-8215-b711bd1977d4
* Version Independent ID: fc504984-91d7-b586-04ec-4c751fb48998
* Content: [Windows 10 Subscription Activation - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Thanks for bringing up this scenario. I am bringing it to the attention of the product team and based on what they say I'll try to update the article.

**Comment by greg-lindsay** [comment]
Hi - the answer I received is that Win10 Pro is the qualifying license for the Enterprise subscription. If you start with Home, it won't work (currently) to upgrade directly to Enterprise using Subscription Activation.  This might change in the future. I can't make any promises but the product team is aware of the scenario.

**Comment by mattsmacblog** [comment]
Thanks Greg, it would be great to know if this is on the roadmap.  As it effects purchasing...  Current OS = Enterprise KMS, underlying Digital Key that we never care about is Home.  Subscription Activate seems to ignore the Enterprise KMS part and goes oh this must be some Home Users device even though it's in Intune, Azure or Domain bound etc... etc...  ie clearly not a Home PC...
