### ISSUE TITLE
Please clarify IoT Enterprise support

### ISSUE THREAD

**Issue by DeployWindowsCom** [MicrosoftDocs/windows-itpro-docs#9424]
Could you please clarify IoT enterprise support, SAC and LTSC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162c8434-b3ab-e235-43ce-ed435d6cd06e
* Version Independent ID: 18b29b82-f1ad-81b8-2ea4-f7bebc506487
* Content: [Configuration service provider reference - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference)
* Content Source: [windows/client-management/mdm/configuration-service-provider-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/configuration-service-provider-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @DeployWindowsCom - Thank you for writing your query. I was going through your query and the document and it makes me confused about what exactly you are looking for? What sort of support you are looking for in IoT. https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference#csps-supported-in-windows-10-iot-core explains the supported CSP for IoT core is the only CSP supported in IoT environments. 

Thanks.
Imran.
@e0i FYI Please.

**Comment by DeployWindowsCom** [comment]
thanks for coming back!
There is a Win10 IoT enterprise SKU (not IoT Core) that seems to have a "mixed result" of success in applying different CSPs and settings. Would be nice to know what is supported and not.
There several references on blogs in this topic for instance: 
https://sandyzeng.com/manage-windows-iot-enterprise-with-microsoft-endpoint-manager-intune/
https://techcommunity.microsoft.com/t5/learn-iot/ask-the-iot-expert-windows-10-iot-enterprise/m-p/1578999#M12
I have tested quite a bit myself with different result as well
I hope this clarifies the question/request, if there is anything I can help with just shout out
