### ISSUE TITLE
<strong> tags not valid and causing localization issue

### ISSUE THREAD

**Issue by TinaMcN** [MicrosoftDocs/windows-itpro-docs#9426]
This article contains a number or <strong> tags which are not valid .md syntax, probably left over from a previous conversion of this content
![image](https://user-images.githubusercontent.com/53281468/114915578-926c4d00-9dd8-11eb-8c5c-b6fd176af259.png)

According to the wiki topic (https://review.docs.microsoft.com/en-us/office-authoring-guide/contribute-how-to-write-use-markdown?branch=main) Bolding is done as follows
![image](https://user-images.githubusercontent.com/53281468/114915746-d0697100-9dd8-11eb-9499-b43490b9ec8c.png)

This issue was causing the localized TOC's to be overlaid on the article.  We manually fixed the loc articles but if the English article is updated in future it will break the localized articles again.

Please replace the  <strong> tags with the appropriate Bold syntax.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef67aab0-cd98-5bd9-1285-14d6f6dcc881
* Version Independent ID: 12055585-601f-596b-8620-120f52ec392c
* Content: [Policy CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-configuration-service-provider)
* Content Source: [windows/client-management/mdm/policy-configuration-service-provider.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-configuration-service-provider.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Below is a snippet from the relevant section in https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-configuration-service-provider.md

Please note that there are 10 pairs of `<strong>` / `</strong>` used in addition to MarkDown italics encapsulation.

There seems to be an issue with MarkDown **Bold** and _italics_ in the same sentence or line, making it difficult to have parts of the same continuous text string only in **Bold** while also making parts of the same continuous text string (without spaces) to be **_italics as well as bold_**. 

Note: it works when applying it to text with spaces. The difficult part is the URI paths like **Policy/Config/_AreaName/PolicyName_** — although it seems to work when used in comments here on GitHub. That could easily be the case for GitHub Flavored MarkDown, a special version of MarkDown. I do not know yet if the MS Docs GitHub source pages will be converted correctly to HTML if GFM style is applied to the source document. Some testing may be needed to verify how it works.

```html
<a href="" id="policy-config-areaname"></a>**Policy/Config/**<strong>*AreaName*</strong>  
<p style="margin-left: 20px">The area group that can be configured by a single technology for a single provider. Once added, you cannot change the value.

<p style="margin-left: 20px">Supported operations are Add, Get, and Delete.

<a href="" id="policy-config-areaname-policyname"></a>**Policy/Config/**<strong>*AreaName/PolicyName*</strong>  
<p style="margin-left: 20px">Specifies the name/value pair used in the policy.

<p style="margin-left: 20px">The following list shows some tips to help you when configuring policies:

-   Separate substring values by the Unicode &\#xF000; in the XML file.

> [!NOTE]
> A query from a different caller could provide a different value as each caller could have different values for a named policy.
-   In SyncML, wrap this policy with the Atomic command so that the policy settings are treated as a single transaction.
-   Supported operations are Add, Get, Delete, and Replace.
-   Value type is string.

<a href="" id="policy-result"></a>**Policy/Result**  
<p style="margin-left: 20px">Groups the evaluated policies from all providers that can be configured.

<p style="margin-left: 20px">Supported operation is Get.

<a href="" id="policy-result-areaname"></a>**Policy/Result/**<strong>*AreaName*</strong>  
<p style="margin-left: 20px">The area group that can be configured by a single technology independent of the providers.

<p style="margin-left: 20px">Supported operation is Get.

<a href="" id="policy-result-areaname-policyname"></a>**Policy/Result/**<strong>*AreaName/PolicyName*</strong>  
<p style="margin-left: 20px">Specifies the name/value pair used in the policy.

<p style="margin-left: 20px">Supported operation is Get.

<a href="" id="policy-result"></a>**Policy/ConfigOperations**  
<p style="margin-left: 20px">Added in Windows 10, version 1703. The root node for grouping different configuration operations.

<p style="margin-left: 20px">Supported operations are Add, Get, and Delete.

<a href="" id="policy-configoperations-admxinstall"></a>**Policy/ConfigOperations/ADMXInstall**  
<p style="margin-left: 20px">Added in Windows 10, version 1703. Allows settings for ADMX files for Win32 and Desktop Bridge apps to be imported (ingested) by your device and processed into new ADMX-backed policies or preferences. By using ADMXInstall, you can add ADMX-backed policies for those Win32 or Desktop Bridge apps that have been added between OS releases. ADMX-backed policies are ingested to your device by using the Policy CSP URI: <code>./Vendor/MSFT/Policy/ConfigOperations/ADMXInstall</code>. Each ADMX-backed policy or preference that is added is assigned a unique ID. For more information about using Policy CSP to configure Win32 and Desktop Bridge app policies, see <a href="win32-and-centennial-app-policy-configuration.md" data-raw-source="[Win32 and Desktop Bridge app policy configuration](win32-and-centennial-app-policy-configuration.md)">Win32 and Desktop Bridge app policy configuration</a>.

> [!NOTE]
> The OPAX settings that are managed by the Microsoft Office Customization Tool are not supported by MDM. For more information about this tool, see [Office Customization Tool](/previous-versions/office/office-2013-resource-kit/cc179097(v=office.15)).
<p style="margin-left: 20px">ADMX files that have been installed by using <strong>ConfigOperations/ADMXInstall</strong> can later be deleted by using the URI delete operation. Deleting an ADMX file will delete the ADMX file from disk, remove the metadata from the ADMXdefault registry hive, and delete all the policies that were set from the file. The MDM server can also delete all ADMX policies that are tied to a particular app by calling delete on the URI, <code>./Vendor/MSFT/Policy/ConfigOperations/ADMXInstall/{AppName}</code>.

<p style="margin-left: 20px">Supported operations are Add, Get, and Delete.

<a href="" id="policy-configoperations-admxinstall-appname"></a>**Policy/ConfigOperations/ADMXInstall/**<strong>*AppName*</strong>  
<p style="margin-left: 20px">Added in Windows 10, version 1703. Specifies the name of the Win32 or Desktop Bridge app associated with the ADMX file. 

<p style="margin-left: 20px">Supported operations are Add, Get, and Delete.

<a href="" id="policy-configoperations-admxinstall-appname-policy"></a>**Policy/ConfigOperations/ADMXInstall/**<strong>*AppName*/Policy</strong>  
<p style="margin-left: 20px">Added in Windows 10, version 1703. Specifies that a Win32 or Desktop Bridge app policy is to be imported.

<p style="margin-left: 20px">Supported operations are Add, Get, and Delete.

<a href="" id="policy-configoperations-admxinstall-appname-policy-uniqueid"></a>**Policy/ConfigOperations/ADMXInstall/**<strong>*AppName*/Policy/*UniqueID*</strong>  
<p style="margin-left: 20px">Added in Windows 10, version 1703. Specifies the unique ID of the app ADMX file that contains the policy to import.

<p style="margin-left: 20px">Supported operations are Add and Get. Does not support Delete.

<a href="" id="policy-configoperations-admxinstall-appname-preference"></a>**Policy/ConfigOperations/ADMXInstall/**<strong>*AppName*/Preference</strong>  
<p style="margin-left: 20px">Added in Windows 10, version 1703. Specifies that a Win32 or Desktop Bridge app preference is to be imported.

<p style="margin-left: 20px">Supported operations are Add, Get, and Delete.

<a href="" id="policy-configoperations-admxinstall-appname-preference-uniqueid"></a>**Policy/ConfigOperations/ADMXInstall/**<strong>*AppName*/Preference/*UniqueID*</strong>  
<p style="margin-left: 20px">Added in Windows 10, version 1703. Specifies the unique ID of the app ADMX file that contains the preference to import.

<p style="margin-left: 20px">Supported operations are Add and Get. Does not support Delete.
```

I also just realized that if the Machine Translation only reads the HTML page source, and not the MarkDown GitHub source, we may be able to use a workaround by replacing the `<strong> </strong>` codes with `<b> </b>` code instead. Does anyone else have experience with this from earlier?

**Comment by TinaMcN** [comment]
@illfated thanks for the info.  For your question about the Machine Translation, both MT and Human Translation are done on the .md files, not the published .html version.

**Comment by illfated** [comment]
Many thanks for confirming the source used in MT and HT. I will have another look into this tomorrow, since it's bedtime for me around now, hoping to find something additional to report back when I know more.

**Comment by e0i** [comment]
@TinaMcN Hello Tina, I’m routing this to independent contributors and expect a fix soon. Thank you for the feedback, and stay safe.

**Comment by MaratMussabekov** [comment]
Hello, please have a look at https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9430,
would it work?

Thank you

**Comment by illfated** [comment]
( ref. #9430 )

Well, at least it works here on GitHub, I just hope it is not limited to GFM. Anyway, it should work for the Machine Translation since MT uses the GitHub source for translation, so I have added my approval to the PR.

**Comment by illfated** [comment]
PR #9430 has been merged now, so I hope we will be seeing any improvement soon.

**Comment by illfated** [comment]
Checked translated versions of the document, the following pages look good:
- https://docs.microsoft.com/zh-cn/windows/client-management/mdm/policy-configuration-service-provider (简体中文/Chinese-Simplified)
- https://docs.microsoft.com/zh-tw/windows/client-management/mdm/policy-configuration-service-provider (中國傳統的/Chinese-Traditional)
- https://docs.microsoft.com/de-de/windows/client-management/mdm/policy-configuration-service-provider (Deutsch/German)
- https://docs.microsoft.com/es-es/windows/client-management/mdm/policy-configuration-service-provider (Español/Spanish)
- https://docs.microsoft.com/fr-fr/windows/client-management/mdm/policy-configuration-service-provider (Français/French)
- https://docs.microsoft.com/ja-jp/windows/client-management/mdm/policy-configuration-service-provider (日本語/Japanese)

While I don't know if there are any other languages with frequent layout and translation issues from Machine Translation, I think this should be fairly representative.

**Comment by TinaMcN** [comment]
@illfated @MaratMussabekov thanks very much for your help with this.

**Comment by TinaMcN** [comment]
There are a few more articles with the same issue, I opened this new issue: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9449
