### ISSUE TITLE
Details on events do not apply to Core install option 

### ISSUE THREAD

**Issue by carlosmayol** [MicrosoftDocs/windows-itpro-docs#9429]
I would like to have a note to highlight this does not apply to Core flavors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5da550e8-6065-7666-46b1-7bfb84ad775e
* Version Independent ID: ffbb3f81-73d3-c5e9-ca5a-abbb36320661
* Content: [Understanding Application Control event IDs (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/event-id-explanations)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/event-id-explanations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/event-id-explanations.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
Closing via #9471 
Thank you
