### ISSUE TITLE
Register HP50g

### ISSUE THREAD

**Issue by renuac** [MicrosoftDocs/windows-itpro-docs#9431]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34937b5e-eda3-9c93-c31b-0701ea61198a
* Version Independent ID: 36f54d9f-503d-ea0a-bff2-3441571f8d44
* Content: [Quick guide to Windows as a service (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-quick-start)
* Content Source: [windows/deployment/update/waas-quick-start.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-quick-start.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
Looks like a test comment. No issue information presented above.

#please-close
