### ISSUE TITLE
Doesn't address greenfield Win10 Enterprise

### ISSUE THREAD

**Issue by bmilbauer** [MicrosoftDocs/windows-itpro-docs#9433]
This article doesn't address the scenario of bare-metal imaging new machines with a Windows 10 Enterprise ISO, specifically where to get the key from a Windows 10 E3 or Microsoft 365 E3 license, and how to assign the license and activate Windows in that scenario. It seems to only address upgrading from Win10 Pro. I can't find the relevant info for me anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf22b00-1c7f-5fd8-7e21-f3a50da00a15
* Version Independent ID: f118fd3a-d0b3-ae53-0b59-a049fe18eb15
* Content: [Windows 10 Enterprise E3 in CSP - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-e3-overview)
* Content Source: [windows/deployment/windows-10-enterprise-e3-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-enterprise-e3-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
@MaratMussabekov : This looks similar to things you have provided answers to in the past. Would you be able to suggest some answers or see if the documentation needs improvement here?

**Comment by MaratMussabekov** [comment]
Hello @bmilbauer ,
**This article doesn't address the scenario of bare-metal imaging new machines with a Windows 10 Enterprise ISO** - Windows 10 Enterprise E3 in CSP doesn't work this way. You should install Windows 10 Pro, then user who has Microsoft 365 E3 license must login to it. Then Enterprise features become available.
Thank you

**Comment by nam31** [comment]
@bmilbauer Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
