### ISSUE TITLE
MFA Server is not required for WHFB

### ISSUE THREAD

**Issue by PaulTown** [MicrosoftDocs/windows-itpro-docs#9434]
[Enter feedback here]
The doc section https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-guide#assumptions seems to be suggesting MFA server is required for MFA.  However Azure MFA works just fine and is what is used most often these days.

We would like to see this verbiage corrected .

Change "Multi-factor Authentication Server to support MFA during Windows Hello for Business provisioning"
TO "Multi-factor Authentication is required during Windows Hello for Business provisioning"

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3b8524-491d-7f49-0445-a34ed47d504c
* Version Independent ID: 1106b56a-45f9-9465-7c7c-2fa9a68ca807
* Content: [Windows Hello for Business Deployment Overview - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-guide#assumptions)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-deployment-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-deployment-guide.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by nam31** [comment]
Closing via #9472 
Thank you
