### ISSUE TITLE
Subject Name (CN) with special characters

### ISSUE THREAD

**Issue by sbv2291** [MicrosoftDocs/windows-itpro-docs#9438]
Our {{OnPrem_Distinguished_Name}} value is having a comma and hence it's not able to generate the certificate. Our DN looks like below

Example DN: CN="LastName\, FirstName,OU=UserAccounts,DC=corp,DC=contoso,DC=com"

I found below an article that says to add quotes in CN value but not able to find a way to use it as the value for {{OnPrem_Distinguished_Name}} is generating automatically from AD connect. 

https://docs.microsoft.com/en-us/mem/intune/protect/certificates-profile-scep#avoid-certificate-signing-requests-with-escaped-special-characters

So now I know that I need to pass value like below to make it work but the question is how to pass that value?
CN=""LastName\, FirstName”,OU=UserAccounts,DC=corp,DC=contoso,DC=com"

Many organizations using LastName, FirstName format so it's a very common situation so can we include a way to generate the certificate in such scenarios?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f709fd4-0b5d-b238-4060-222d550cd538
* Version Independent ID: fb3f29da-2236-c47d-6bea-8efbcec8d7d3
* Content: [Using Certificates for AADJ On-premises Single-sign On single sign-on - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by sbv2291** [comment]
Able to fix the issue. Can you please consider adding below two points in the DOC so it helps everyone in future. 

Main credit goes to Cici Wu-MSFT : https://docs.microsoft.com/en-us/answers/questions/364488/windows-hello-for-business-certificate-issue.html

Point 1: If {{OnPrem_Distinguished_Name}} is having comma in CN value then Subject name format must be CN="{​​​​​​​​{​​​​​​​​OnPrem_Distinguished_Name}​​​​​​​​}​​​​​​​​"

Point 2: If the subject name lenght is more than 64 characters , need to disable name length enforcement using command "certutil -setreg ca\EnforceX500NameLengths 0" on Internal CA server
Reference: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc784789(v=ws.10)?redirectedfrom=MSDN#disable-dn-length-enforcement

**Comment by nam31** [comment]
Closing via #9455 
Thank you
