### ISSUE TITLE
Too many wrong PIN attempts - description missing.

### ISSUE THREAD

**Issue by identityiskey** [MicrosoftDocs/windows-itpro-docs#9445]
[Enter feedback here]
Hi there is a section missing that describes what happens if there are too many wrong PIN attempts. Does the account get blocked? Does the Input be throttled? Is the TPM reset? Consequences are unclear at all.
Also from a security perspective - which Windows Event IDs we can look for for wrong PIN inputs to get a central overview over our organization?

All the best

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba665984-14d2-e5f1-a1a4-e8c28b61571d
* Version Independent ID: 4918b293-ce78-154b-a3ee-515557367d8c
* Content: [Windows Hello and password changes (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-and-password-changes)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-and-password-changes.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-and-password-changes.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by joinimran** [comment]
Hello @identityiskey, 
By default, nothing will happen but if we apply local group policies we can set the Account lockout threshold and Account lockout duration.
for example, if we set the Account lockout threshold to 5 invalid logon attempts and Account lockout duration to 5 minutes then after 5 invalid attempts account will be locked for 5 minutes. To do this follow the following steps:
Press the Windows Key + R, type gpedit.msc, and hit Enter to open the Local Group Policy Editor.
In the navigation pane on the left-hand side, navigate to Computer Configuration > Windows Settings > Security Settings > Account Policies > Account Lockout Policy.
Click the Account Lockout Policy key. You should see the following three settings in the right-hand side pane: Account lockout duration, Account lockout threshold, and the Reset account lockout counter after.
Thanks.
