### ISSUE TITLE
Dead Link to Local Administrator Password Solution

### ISSUE THREAD

**Issue by dovicsak** [MicrosoftDocs/windows-itpro-docs#9446]
Under the section "Create unique passwords for local accounts with administrative rights", the second bullet point includes a link that is not working. The link for download points to https://www.microsoft.com/download/details.aspx?id=46899 but clicking on this link returns a 404 error in the Download Center. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74d32ee6-c7ff-9328-97d6-40ad82c73392
* Version Independent ID: 01f10cbb-4cae-077f-8245-7b0ada8305d7
* Content: [Local Accounts (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/local-accounts)
* Content Source: [windows/security/identity-protection/access-control/local-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/access-control/local-accounts.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
### Local Administrator Password Solution (LAPS)

- https://www.microsoft.com/en-us/download/details.aspx?id=46899

Please test the linked page again. The page is available to me, using the following browsers:
- Mozilla Firefox 88.0 (64 bit)
- Microsoft Edge Version 90.0.818.46 (Official build) (64-bit)
- Google Chrome Version 90.0.4430.85 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/38162891/116009946-752b5000-a61c-11eb-951a-3121d4007972.png)

**Comment by RAJU2529** [comment]
@dovicsak . link is working fine, just now I downloaded those tool

**Comment by dovicsak** [comment]
Maybe there was a temporary outage on Friday. The link is also working for me now.
