### ISSUE TITLE
Can we clarify what versions of Windows do not (yet) have SSUs built into the monthly cumulative update?

### ISSUE THREAD

**Issue by ElizabethGreene** [MicrosoftDocs/windows-itpro-docs#9447]
In the "Simplifying on-premises deployment of servicing stack updates" section, can we make it more clear that the SSU's are only included in the cumulative updates for 2004 and 20H2, and that older revisions of Windows 10 still require the independent SSU?  If you aren't looking for that distinction it's very easy to overlook.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b706f0af-d504-a8ca-7c38-b8bb9283bfad
* Version Independent ID: 14f31acf-9f47-59a6-269f-62ab249fe560
* Content: [Servicing stack updates (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates#why-should-servicing-stack-updates-be-installed-and-kept-up-to-date)
* Content Source: [windows/deployment/update/servicing-stack-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/servicing-stack-updates.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment]
@ElizabethGreene . SSU updates are not included in v2004 and 20h2 too. We have to download separately from  Microsoft update catalogue official website. Each SSU must installed before installing CLU on windows 10 OS. 
I have own experience from 1803 onwards

**Comment by ElizabethGreene** [comment]
> @ElizabethGreene . SSU updates are not included in v2004 and 20h2 too. We have to download separately from Microsoft update catalogue official website. Each SSU must installed before installing CLU on windows 10 OS.
> I have own experience from 1803 onwards

Thanks for replying.  The permanent advisory for servicing stack updates is [Microsoft's MSRC Advisory: ADV990001](https://msrc.microsoft.com/update-guide/en-us/vulnerability/ADV990001).  According to it, if you have the January 2021 SSU, KB4598481, for Windows 10 2004 or 20H2 then you should get all future SSUs inside the cumulative update.  I had a customer that thought all versions of Windows 10 had the SSU bundled in, and so I created this gitHub request is to ask that we update this docs page to make that more clear.

I hope this helps.

**Comment by MaratMussabekov** [comment]
Hello @ElizabethGreene ,
 **can we make it more clear that the SSU's are only included in the cumulative updates for 2004 and 20H2** - the article states "The combined monthly cumulative update will be available on Windows 10, version 2004 and later". It looks like it is clear that all versions prior to 2004 do not have this feature. 
 **If you aren't looking for that distinction it's very easy to overlook** - for me everything looks ok, if you recommend to reword this section, could you please advise, which wording would be better to make this section more clear?

Thank you

**Comment by nam31** [comment]
Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
