### ISSUE TITLE
Interactive Logon Machine Inactivity Limit - 1 Second

### ISSUE THREAD

**Issue by learningdaily** [MicrosoftDocs/windows-itpro-docs#9448]
[Enter feedback here]
Using the Settings Catalog to deploy a Device Configuration Profile. The LocalPoliciesSecurityOptions/InteractiveLogon_MachineInactivityLimit Setting incorrectly applies to Windows 10 systems. 

Enabling the setting forces the "inactivity" time limit to be 1 second. I believe Windows is looking for an integer, like 15 minutes or 900 seconds, not a 0 or 1.

From Local Group Policy:
Interactive logon: Machine inactivity limit.

Windows notices inactivity of a logon session, and if the amount of inactive time exceeds the inactivity limit, then the screen saver will run, locking the session.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 773b74b2-7dc2-d0e5-1e3b-bd6445bceda4
* Version Independent ID: 34b55057-9078-6bd0-a9ac-2f6403b84be7
* Content: [Policy CSP - LocalPoliciesSecurityOptions - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions#localpoliciessecurityoptions-interactivelogon-machineinactivitylimit)
* Content Source: [windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Good point. Looks like the text …

***

Valid values:
- 0 - disabled 
- 1 - enabled (session will lock after amount of inactive time exceeds the inactivity limit)

***

… could easily have been copy-pasted from one of the previous sections.

You are right, those lines go against the preceding text:

***

Default: not enforced.

Value type is integer. Supported operations are Add, Get, Replace, and Delete.

***

According to the information above, the text underneath "Valid values:" in this section should be changed to something like

- Elapsed seconds of inactivity, which can range from zero (0) to 599,940 seconds (166.65 hours).

***

My text suggestion is copied from https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit#possible-values, based on the lookup recommendation of Matt Day on **Microsoft Endpoint Manager Intune Feedback**
- https://microsoftintune.uservoice.com/users/4370353172-matt-day
- https://microsoftintune.uservoice.com/forums/291681-ideas/suggestions/42775955-bug-with-configuration-profile-that-sets-interacti

**Comment by illfated** [comment]
( ref. #9486 )

**Comment by nam31** [comment]
Closing via #9486 
Thank you
