### ISSUE TITLE
Windows 10 Iot entreprise is it supported by WUFB?

### ISSUE THREAD

**Issue by JuGhithub** [MicrosoftDocs/windows-itpro-docs#9456]
I need to manage Windows 10 IOT enterprise 2016 and 2019 with Intune to manage Software Updates.

WUFB can support Windows 10 IOT Enterprise (LTSC and SAC?)

Tank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09aa9f9-959c-479b-f727-03f292e92b0a
* Version Independent ID: 4664a228-83be-157b-fc75-45abe14abc27
* Content: [Onboarding to Windows Update for Business (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/wufb-onboard)
* Content Source: [windows/deployment/update/wufb-onboard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/wufb-onboard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by joinimran** [comment]
Hello @JuGhithub - Thank you for posting your query. Please note that as of now, you can not manage Windows 10 IoT with WUfB. The only supported SKUs are 
Windows 10 Education
Windows 10 Enterprise
Windows 10 Pro
Windows 10 S (for Windows 10, version 1709 and earlier)

You can always use the user voice channel to request this feature for WUfB.  @nam31 can guide you on how you can request a new feature using the user voice channel. 

Thanks
Imran.

**Comment by nam31** [comment]
@JuGhithub Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
