### ISSUE TITLE
Credential Guard Disable

### ISSUE THREAD

**Issue by lturn9** [MicrosoftDocs/windows-itpro-docs#9458]
Edition	Windows 10 Home
Version	20H2
Installed on	‎3/‎26/‎2021
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0

[Enter feedback here]
Tried to disable Credential Guard but rec'd an error saying "DG
_Readiness_Tool_ver3.6.psl" is not recognized as an Internal or External Command, operable program or Batch File.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **v-tea**

**Comment by RAJU2529** [comment]
@lturn9 .. THis tool will not execute by ordinary command, you must to do special commands
first  copy  **DG_Readiness_Tool_ver3.6.ps1**   to  **C:\DG**
open windows PowerShell with admin rights 
then type  below line 
**cd C:\DG**
then type  below line 
** .\DG_Readiness_Tool_v3.6.ps1**

**Comment by nam31** [comment]
@lturn9 Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)
Thank you.
