### ISSUE TITLE
I don't see documentation for the OneDrive variable

### ISSUE THREAD

**Issue by lenraphael** [MicrosoftDocs/windows-itpro-docs#946]
which I thought resolves to a user's locally synched OneDrive top level folder.  I also don't one for the locally synched SharePoint Team or Personal folder. But it might be because that doesn't exist.  Is there one for that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72d479c1-cedc-05fc-2d73-45342b955037
* Version Independent ID: 8e91c2df-8405-3ec0-210e-1b97e86073cf
* Content: [Recognized Environment Variables (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-recognized-environment-variables)
* Content Source: [windows/deployment/usmt/usmt-recognized-environment-variables.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/usmt/usmt-recognized-environment-variables.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @lenraphael ,
both OneDrive and Sharepoint are separate products, not the part of Windows OS. That's why any variable related to those products couldn't be considered as Windows 10 environment variable and is not within the scope of this article.
Thank you

**Comment by mypil** [comment]
@lenraphael - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by j0rt3g4** [comment]
PR #3708

**Comment by mypil** [comment]
@officedocsbot close
