### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by CronoMkI** [MicrosoftDocs/windows-itpro-docs#9460]
"Dell Inc" should be "Dell Inc."
If you forget the period, the driver injection doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb440d06-32d1-c982-7736-0588cb4d8718
* Version Independent ID: 37cfa729-ee6d-3af4-dbbd-547797e37397
* Content: [Build a distributed environment for Windows 10 deployment (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/build-a-distributed-environment-for-windows-10-deployment)
* Content Source: [windows/deployment/deploy-windows-mdt/build-a-distributed-environment-for-windows-10-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/build-a-distributed-environment-for-windows-10-deployment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
I tried looking for the text "Dell Inc" on that page, but could not find it. Maybe I did not look carefully enough, but normal search (Ctrl-F) did not find it.

Could you point to where on the page this typo is located?

**Comment by greg-lindsay** [comment]
This is a good catch. The doc isn't this one however, it is deploy-a-windows-10-image-using-mdt.md

**Comment by greg-lindsay** [comment]
Fixed
