### ISSUE TITLE
Como descobrir a lista de usuarios em cache? Logon Interativo Windows 10

### ISSUE THREAD

**Issue by RenanZampier** [MicrosoftDocs/windows-itpro-docs#9464]
Como faço para descobrir que um determinado login esta em cache ? 
O caso era que um determinado computador precisava de suporte remoto, porém o software da VPN estava corrompido/com erro.
Como Usuários não possuem perfil ADM, como poderíamos verificar outros perfis de usuários em cache (Logon Interativo) para informar a senha e/ou solicitar que outro usuário do setor faça o login.

Ainda não descobri

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: ef720207-c5e6-182e-8a34-361244c45641
* Version Independent ID: 4591df7c-e474-9b85-7c09-ce572a66a0a3
* Content: [Logon interativo Número de logons anteriores a cache (caso o controlador de domínio não está disponível) (Windows 10) - Windows security](https://docs.microsoft.com/pt-br/windows/security/threat-protection/security-policy-settings/interactive-logon-number-of-previous-logons-to-cache-in-case-domain-controller-is-not-available)
* Content Source: [windows/security/threat-protection/security-policy-settings/interactive-logon-number-of-previous-logons-to-cache-in-case-domain-controller-is-not-available.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/interactive-logon-number-of-previous-logons-to-cache-in-case-domain-controller-is-not-available.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Use uma instância de suporte real, como o Suporte da Microsoft ou os Fóruns da Microsoft. Este repositório se destina apenas ao aprimoramento da documentação.

Gostaria de poder ajudar, mas este repositório não se destina a problemas regulares de suporte, solicitações de suporte ou perguntas de suporte.

Isenção de responsabilidade: não sou afiliado à Microsoft ou às equipes do Microsoft Docs aqui no GitHub.

A intenção deste repositório é melhorar a documentação existente, proporcionando aos usuários uma forma de relatar erros factuais, sugestões de melhorias e solicitar atualizações para novas versões.

Experimente os seguintes recursos para entrar em contato com usuários que podem ajudá-lo:
- Fóruns TechNet: https://social.technet.microsoft.com/Forums/pt-BR/home
- MSDN: https://social.msdn.microsoft.com/Forums/pt-BR/home
- Comunidade Microsoft: https://answers.microsoft.com/pt-br

***

Please use a real support instance like Microsoft Support or Microsoft Forums. This repository is intended for documentation improvement only.

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/pt-BR/home
- MSDN: https://social.msdn.microsoft.com/Forums/pt-BR/home
- Microsoft Community: https://answers.microsoft.com/pt-br

**Comment by illfated** [comment]
How do I find out that a particular login is cached?

The case was that a particular computer needed remote support, but the VPN software was corrupted/in error.

Because Users do not have an ADM profile, as we could check other profiles of cached users (Interactive Login) to enter the password and/or request that another user in the industry log in.

I haven't figured it out yet

***
( Translation from the main issue ticket comment, written in Brazilian Portuguese. )
