### ISSUE TITLE
Mistranslation  into Japanese in the "Trusted Boot" chapter

### ISSUE THREAD

**Issue by bean1310** [MicrosoftDocs/windows-itpro-docs#9465]
I found a mistranslation shown below in the "Trusted Boot" chapter:
- Original: "Trusted Boot takes over where Secure Boot leaves off. "
- Japanese: 「セキュア ブートがオフになっている場合は、トラスト ブートが後を引き継ぎます。」

I think an appropriate translation is 「セキュア ブートの後、トラスト ブートに引き継がれます。」.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 0d30d792-78bc-d594-ea45-5ca6b29dec72
* Version Independent ID: eff8bd5f-9480-59cb-0355-aa389be6e5f1
* Content: [Windows 10 のブート プロセスのセキュリティ保護 - Microsoft 365 Security](https://docs.microsoft.com/ja-jp/windows/security/information-protection/secure-the-windows-10-boot-process#feedback)
* Content Source: [windows/security/information-protection/secure-the-windows-10-boot-process.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/secure-the-windows-10-boot-process.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
I sort of suspected that this might happen, sooner or later, just did not know when. Is it mistranslated as "trustworthy footwear" or "the mountain hiking boot that can be relied on"? It would not surprise me if it did. 😉 

@TinaMcN : Looks like the Machine Translation needs to be checked to see if it can be improved, or just have the section translated by a human.

By the way: Here is the direct link to the related section:
- https://docs.microsoft.com/ja-jp/windows/security/information-protection/secure-the-windows-10-boot-process#trusted-boot

**Comment by TinaMcN** [comment]
@bean1310 thanks for reporting it.  It appears to be a machine translation issue.  I sent the article to be human translated and it should be completed in approx. 3 days.

**Comment by TinaMcN** [comment]
The article has been human translated but the issue isn't fixed yet.  I have asked the translators to fix it.

**Comment by TinaMcN** [comment]
@bean1310 this should be fixed now, can you please check to see if it looks ok now?  If so, please close it.  Thanks again for reporting this issue!

**Comment by bean1310** [comment]
LGTM!
Thanks for this fix!
