### ISSUE TITLE
<strong> tags causing issue in more localized articles

### ISSUE THREAD

**Issue by TinaMcN** [MicrosoftDocs/windows-itpro-docs#9467]
As described in https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9449 there are a number of windows/client-management files which contain <strong> tags which are not valid .md syntax.  In addition to the files in that issue we found more which are causing the translated TOCs and page layout to look crazy.  Hopefully this will be the last of them.

windows-docs-pr/windows/client-management/mdm/activesync-csp.md
windows-docs-pr/windows/client-management/mdm/alljoynmanagement-csp.md
windows-docs-pr/windows/client-management/mdm/certificatestore-csp.md
windows-docs-pr/windows/client-management/mdm/clientcertificateinstall-csp.md
windows-docs-pr/windows/client-management/mdm/cmpolicy-csp.md
windows-docs-pr/windows/client-management/mdm/cmpolicyenterprise-csp.md
windows-docs-pr/windows/client-management/mdm/customdeviceui-csp.md
windows-docs-pr/windows/client-management/mdm/defender-csp.md
windows-docs-pr/windows/client-management/mdm/devicestatus-csp.md
windows-docs-pr/windows/client-management/mdm/device-update-management.md
windows-docs-pr/windows/client-management/mdm/dmacc-csp.md
windows-docs-pr/windows/client-management/mdm/dmclient-csp.md
windows-docs-pr/windows/client-management/mdm/enterpriseapn-csp.md
windows-docs-pr/windows/client-management/mdm/enterpriseappmanagement-csp.md
windows-docs-pr/windows/client-management/mdm/enterprisedesktopappmanagement-csp.md
windows-docs-pr/windows/client-management/mdm/enterprisemodernappmanagement-csp.md
windows-docs-pr/windows/client-management/mdm/maps-csp.md
windows-docs-pr/windows/client-management/mdm/nodecache-csp.md
windows-docs-pr/windows/client-management/mdm/unifiedwritefilter-csp.md

@illfated can you please help with this one also?

**Comment by illfated** [comment]
Thank you for providing this list of document pages where this issue is present. Sure, I am happy to help. I just need to start it tomorrow, since it is already long past my bedtime at this hour. I am fine with changing all of them in one PR or create separate PRs for all of them, so feel free to suggest which method you prefer that I should use.

Using local source on my computer and Git Extensions to push my changes, it does not make much difference to me, so feel free to choose which solution you prefer to manage here on GitHub.

**Comment by TinaMcN** [comment]
@illfated this can definitely wait until tomorrow!  I think all in one PR is probably easier but I don't have a strong preference.  Really appreciate your help with these issues!

**Comment by illfated** [comment]
There you go. PR #9474 is ready for review, comments, and suggestions.

**Comment by danielklenda85** [comment]
Hello what is this?

**Comment by illfated** [comment]
@danielklenda85 : I can't find anything pointing to why you should have been subscribed to this thread, but feel free to unsubscribe by using the button **[Unsubscribe]** on the right hand side of this GitHub page:

![image](https://user-images.githubusercontent.com/38162891/116730331-ae7f0980-a9e8-11eb-94db-ddc3d870d204.png)

**Comment by TinaMcN** [comment]
The PR is completed so we can close this now. @ghost thanks for your help
