### ISSUE TITLE
Correct procedure to change the password

### ISSUE THREAD

**Issue by dbona75** [MicrosoftDocs/windows-itpro-docs#9475]
[Enter feedback here]

Hello ,

the procedure to change the PIN is wrong.  Log on with the old pin or password, press Ctrl+Alt+Del and choose “Change a password”, click "sign in options", click the virtual smart card icon, change the pin.

the affected paragraph is "change PIN"

regards

dabona@microsoft.com
Customer Engineer - Identity and Security
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c79fe78b-8e95-6e36-ea61-c52b49f57138
* Version Independent ID: d17c6afc-e66f-2918-5d1e-76df2130dcb8
* Content: [Use Virtual Smart Cards (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-use-virtual-smart-cards)
* Content Source: [windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-use-virtual-smart-cards.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-use-virtual-smart-cards.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Thank you for pointing out the omission. Would you be so kind as to comment again (or edit your ticket) to add a link to which chapter, paragraph, or section this affects?

**Comment by dbona75** [comment]
Hello

Thanks for asking

Change the pin

Regards



Da: Trond B. Krokli ***@***.***>
Inviato: Thursday, April 29, 2021 6:29 PM
A: MicrosoftDocs/windows-itpro-docs ***@***.***>
Cc: Daniele Bona ***@***.***>; Author ***@***.***>
Oggetto: Re: [MicrosoftDocs/windows-itpro-docs] Correct procedure to change the password (#9475)


Thank you for pointing out the omission. Would you be so kind as to comment again (or edit your ticket) to add a link to which chapter, paragraph, or section this affects?

-

**Comment by illfated** [comment]
Very well, a simple search for that term points to the table in this section:

- https://docs.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-use-virtual-smart-cards#create-and-delete-virtual-smart-cards-programmatically


## Create and delete virtual smart cards programmatically

Virtual smart cards can also be created and deleted by using APIs. For more information, see the following classes and interfaces:

-   [TpmVirtualSmartCardManager](/previous-versions/windows/desktop/legacy/hh707171(v=vs.85))

-   [RemoteTpmVirtualSmartCardManager](/previous-versions/windows/desktop/legacy/hh707166(v=vs.85))

-   [ITpmVirtualSmartCardManager](/windows/win32/api/tpmvscmgr/nn-tpmvscmgr-itpmvirtualsmartcardmanager)

-   [ITPMVirtualSmartCardManagerStatusCallBack](/windows/win32/api/tpmvscmgr/nn-tpmvscmgr-itpmvirtualsmartcardmanagerstatuscallback)

You can use APIs that were introduced in the Windows.Device.SmartCards namespace in Windows Server 2012 R2 and Windows 8.1 to build Microsoft Store apps to manage the full lifecycle of virtual smart cards. For information about how to build an app to do this, see [Strong Authentication: Building Apps That Leverage Virtual Smart Cards in Enterprise, BYOD, and Consumer Environments | Build 2013 | Channel 9](https://channel9.msdn.com/events/build/2013/2-041).

The following table describes the features that can be developed in a Microsoft Store app:

| Feature                                      | Physical Smart Card | Virtual Smart Card |
| :------------------------------------------- | :------------------ | :----------------- |
| Query and monitor smart card readers              | Yes                      | Yes                     |
| List available smart cards in a reader, and retrieve the card name and card ID                 | Yes           | Yes        |
| Verify if the administrative key of a card is correct      | Yes                      | Yes                     |
| Provision (or reformat) a card with a given card ID        | Yes                      | Yes                     |
| Change the PIN by entering the old PIN and specifying a new PIN      | Yes                      | Yes                     |
| Change the administrative key, reset the PIN, or unblock the smart card by using a challenge/response method | Yes     | Yes      |
| Create a virtual smart card                       | Not applicable           | Yes                     |
| Delete a virtual smart card                       | Not applicable           | Yes                     |
| Set PIN policies                                  | No                       | Yes                     |

**Comment by illfated** [comment]
Hmm. I am somewhat in doubt here. The table lists features, not procedures.

Is the feature really _named_ "Log on with the old pin or password, press Ctrl+Alt+Del and choose “Change a password”, click "sign in options", click the virtual smart card icon, change the pin." ?

**Comment by dbona75** [comment]
Hello , this is the part to modify :

***@***.***D73D40.773A26E0]

In

The PIN for virtual smart card can be changed by logging with the old pin or password, pressing Ctrl+Alt+Del and choose "Change a password", click "sign in options", click the virtual smart card icon, change the pin.



The article says :

This topic for the IT professional describes requirements for virtual smart cards, how to use virtual smart cards, and tools that are available to help you create and manage them.

Regards


Da: Trond B. Krokli ***@***.***>
Inviato: Thursday, April 29, 2021 9:36 PM
A: MicrosoftDocs/windows-itpro-docs ***@***.***>
Cc: Daniele Bona ***@***.***>; Author ***@***.***>
Oggetto: Re: [MicrosoftDocs/windows-itpro-docs] Correct procedure to change the password (#9475)


Hmm. I am somewhat in doubt here. The table lists features, not procedures.

Is the feature really named "Log on with the old pin or password, press Ctrl+Alt+Del and choose "Change a password", click "sign in options", click the virtual smart card icon, change the pin." ?

-

**Comment by dbona75** [comment]
Hello,

I am just telling that this procedure is not correct ... nothing to do with working programmatically


Changing the PIN

The PIN for virtual smart card can be changed by pressing Ctrl+Alt+Del, and then selecting the TPM virtual smart card under Sign in options.


Here the real way to do that


How to change the PIN of a smart card - My Smart Logon<https://www.mysmartlogon.com/knowledge-base/change-pin-smart-card/>



Da: Trond B. Krokli ***@***.***>
Inviato: Thursday, April 29, 2021 9:28 PM
A: MicrosoftDocs/windows-itpro-docs ***@***.***>
Cc: Daniele Bona ***@***.***>; Author ***@***.***>
Oggetto: Re: [MicrosoftDocs/windows-itpro-docs] Correct procedure to change the password (#9475)


Very well, a simple search for that term points to the table in this section:

  *   https://docs.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-use-virtual-smart-cards#create-and-delete-virtual-smart-cards-programmatically<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows%2Fsecurity%2Fidentity-protection%2Fvirtual-smart-cards%2Fvirtual-smart-card-use-virtual-smart-cards%23create-and-delete-virtual-smart-cards-programmatically&data=04%7C01%7Cdaniele.bona%40microsoft.com%7C37272a337a424a76e64708d90b44eb40%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637553212915435562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qwgPSg3Zh6W%2B98YQWInROBmaLlvwHcheZV3k4oNzFg0%3D&reserved=0>

Create and delete virtual smart cards programmatically

Virtual smart cards can also be created and deleted by using APIs. For more information, see the following classes and interfaces:

  *   TpmVirtualSmartCardManager</previous-versions/windows/desktop/legacy/hh707171(v=vs.85)>
  *   RemoteTpmVirtualSmartCardManager</previous-versions/windows/desktop/legacy/hh707166(v=vs.85)>
  *   ITpmVirtualSmartCardManager</windows/win32/api/tpmvscmgr/nn-tpmvscmgr-itpmvirtualsmartcardmanager>
  *   ITPMVirtualSmartCardManagerStatusCallBack</windows/win32/api/tpmvscmgr/nn-tpmvscmgr-itpmvirtualsmartcardmanagerstatuscallback>

You can use APIs that were introduced in the Windows.Device.SmartCards namespace in Windows Server 2012 R2 and Windows 8.1 to build Microsoft Store apps to manage the full lifecycle of virtual smart cards. For information about how to build an app to do this, see Strong Authentication: Building Apps That Leverage Virtual Smart Cards in Enterprise, BYOD, and Consumer Environments | Build 2013 | Channel 9<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fchannel9.msdn.com%2Fevents%2Fbuild%2F2013%2F2-041&data=04%7C01%7Cdaniele.bona%40microsoft.com%7C37272a337a424a76e64708d90b44eb40%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637553212915445555%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cOpKuX9eWcBude36Hf2E0tI0UbWUeaqjUwpBOWpZu%2Bk%3D&reserved=0>.

The following table describes the features that can be developed in a Microsoft Store app:
Feature
Physical Smart Card
Virtual Smart Card
Query and monitor smart card readers
Yes
Yes
List available smart cards in a reader, and retrieve the card name and card ID
Yes
Yes
Verify if the administrative key of a card is correct
Yes
Yes
Provision (or reformat) a card with a given card ID
Yes
Yes
Change the PIN by entering the old PIN and specifying a new PIN
Yes
Yes
Change the administrative key, reset the PIN, or unblock the smart card by using a challenge/response method
Yes
Yes
Create a virtual smart card
Not applicable
Yes
Delete a virtual smart card
Not applicable
Yes
Set PIN policies
No
Yes

-

**Comment by e0i** [comment]
Under investigation. Thank you for the feedback.
