### ISSUE TITLE
Script Missing - Link Unhelpful

### ISSUE THREAD

**Issue by MFisherIT** [MicrosoftDocs/windows-itpro-docs#9477]
The link to the script "Events 16962 - 16969 Reader" still point to the gallery.technet.microsoft.com. Navigation is redirected to docs.microsoft.com/en-us/samples/browse. Searching for script at "Browse Code Samples" page returns zero results. The page will need to be updated and/or the script link corrected:

Link is as follows and likely found between lines 90 and 100 of "network-access-restrict-clients-allowed-to-make-remote-sam-calls.md":
https://gallery.technet.microsoft.com/Events-16962-16969-Reader-2eae5f1d

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef8b6967-0e45-bcdd-6d70-54759d9f7ec8
* Version Independent ID: 6651ebc1-04f0-421f-891b-6957ca37da7c
* Content: [Network access - Restrict clients allowed to make remote calls to SAM - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
(similar issue ticket to #9435 [**Parsing Script Missing**](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9435))
