### ISSUE TITLE
Working with other virtualization products

### ISSUE THREAD

**Issue by ebraiter** [MicrosoftDocs/windows-itpro-docs#9479]
How does the Sandbox work with other virtualization products like VMware Workstation or Oracle VirtualBox?
I read somewhere that Sandbox and older versions of VMware Workstation causes issues. Still the case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c06f3ef-5946-862a-ae14-f897fdb518ca
* Version Independent ID: cd6a8b99-b1e9-dff5-f174-a15840b304f0
* Content: [Windows Sandbox - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @ebraiter - Thank you for posting your query, Windows Sandbox works normally on the VM. If there is any specific use case or issues you are facing, please contact Microsoft support for the same. 

Thanks.
Imran.

**Comment by nam31** [comment]
@ebraiter Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
