### ISSUE TITLE
Wrong Event IDs

### ISSUE THREAD

**Issue by bcb44** [MicrosoftDocs/windows-itpro-docs#9483]
This page says that the product these IDs are for is Windows 10 but I think it uses event IDs that are for Windows Server 2000 and Windows 2003 and XP. The other pages in this section (basic auditing) are mixed with whether they use the correct IDs or not

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 641c6a4f-906f-5f83-239c-8e7191958a3d
* Version Independent ID: 3c3ecbc9-0efb-c16c-fb91-3de8e4d720a9
* Content: [Audit account management (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/basic-audit-account-management)
* Content Source: [windows/security/threat-protection/auditing/basic-audit-account-management.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/basic-audit-account-management.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by dcjacob1999** [comment]
Event IDs typically do not change on Windows. An easy fix is to state the document applies to Windows 10 AND Windows Server, 2003, XP
