### ISSUE TITLE
S-1-5-17 is not 'This Organization' but IUSR

### ISSUE THREAD

**Issue by ADNinja** [MicrosoftDocs/windows-itpro-docs#9491]
S-1-5-17 is not 'This Organization' but IUSR. Looks like a copy-paste mistake.
Correct on this page: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/81d92bba-d22b-4a8c-908a-554ab29148ab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44e911d3-219e-19b8-4870-07514d9a94a1
* Version Independent ID: 960a7388-560b-90eb-e0ff-d8d2bb6f9a7a
* Content: [Active Directory Security Groups (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/active-directory-security-groups)
* Content Source: [windows/security/identity-protection/access-control/active-directory-security-groups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/access-control/active-directory-security-groups.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Please forgive my ignorance, but where did you find `S-1-5-17` on the reported page? I am only able to find 20 occurrences of `S-1-5-21` and 30 occurrences of `S-1-5-32`.

- https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/active-directory-security-groups

**Comment by ADNinja** [comment]
Sorry, wrong article!
