### ISSUE TITLE
GPO list for Win10

### ISSUE THREAD

**Issue by htcfreek** [MicrosoftDocs/windows-itpro-docs#9493]
Please add a list of all gpos for Windows 10 like you have for Microsoft Edge and update it on every admx change.

**Comment by denisebmsft** [comment]
Hello @htcfreek. Can you please tell us to which article(s) your feedback applies? This information will help us route the issue correctly. Thank you!

**Comment by htcfreek** [comment]
There doesn't exists any article like I suggested.

I think an article like the existing one for [MS Edge](https://docs.microsoft.com/de-de/DeployEdge/microsoft-edge-policies) would help admins while configure Windows 10. There isn't any information about all GPOs for Windows 10 and there is no information what has changed from feature update to the next feature update too.

**Comment by denimike** [comment]
I see it that way to and would be happy about such an article

**Comment by nam31** [comment]
@htcfreek Thank you for providing feedback.	
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.	
Thank you for your contribution to make the docs better! Much appreciated!

**Comment by htcfreek** [comment]
@nam31
 Done: https://aka.ms/AAcfso4
