### ISSUE TITLE
PS command to get XML output does not work

### ISSUE THREAD

**Issue by johne-landfall** [MicrosoftDocs/windows-itpro-docs#9496]
PS command to get XML output does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90843710-ba95-4eba-a69b-473e013877be
* Version Independent ID: 4a41937a-d268-8503-1860-16a25e327cc1
* Content: [EAP configuration - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/eap-configuration)
* Content Source: [windows/client-management/mdm/eap-configuration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/eap-configuration.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@johne-landfall . Powershell command clearly works i confirmed after testing on my windows 10 21H1 64bit  laptop.

![Capture](https://user-images.githubusercontent.com/3296790/117482853-9a0bb580-af82-11eb-8b8d-50a84d3ee246.JPG)

**Comment by illfated** [comment]
> PS command to get XML output does not work

In terms of expressions used in IT, "does not work" is too generic and not specific enough to express what you mean. You may want to be more precise to express exactly what "does not work" means in this context.

**Comment by joinimran** [comment]
Hello @johne-landfall - Thank you for putting your query here. Can you please share more details on what exactly is not working for you. Can you please try running the command with Administrative privileges to see how it goes? If you can share more details with screenshot may help us to better guide you.

Thanks.
Imran.

**Comment by e0i** [comment]
Hello, @johne-landfall The description is too vague for contributors to follow up with, and one of the commenters haven’t been able to reproduce the issue.

Further, we track down documentation issue in this repository so ;please refer to the [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10).

Also feel free to re-open this issue if there is anything specific that is going wrong with the `EAP Configuration` article. Thanks.
