### ISSUE TITLE
Set up School PC - Local Administrator Account / Password

### ISSUE THREAD

**Issue by idominiki** [MicrosoftDocs/windows-itpro-docs#9497]
Hello together,
I just used the Set Up School PCs App to configure our PCs.

I don't want to connect to an Azure AD, so I choosed "Continue without account" under "Login".
![Bildschirmfoto 2021-05-06 um 09 38 09](https://user-images.githubusercontent.com/62521486/117259907-cb836480-ae4e-11eb-8785-a1ffc559a019.png)

After the successful installation and configuration I can login as guest user. Also I've seen, that there is an Administrator Account without a password which is disabled. Is there any possibility to activate and login with this local administrator Account?

Edit: If I want to login with administrator and no password I got the error "account disabled".

Thanks and Greets
Dominik

**Comment by denisebmsft** [comment]
Hello @idominiki. Can you please tell us to which article(s) your feedback applies? It looks like you might actually have a case for technical support, rather than a documentation issue.

**Comment by idominiki** [comment]
Hi @denisebmsft 

Thanks for your help! I looked here but don't found an answer. 

https://github.com/MicrosoftDocs/windows-itpro-docs/blob/a8deac4c441fd632da54e7cf5e75a1151a2e2e4e/education/windows/set-up-school-pcs-shared-pc-mode.md

How can I contact the technical team?

Greets
Dominik

**Comment by illfated** [comment]
To be exact, these are the pages in question:
- https://docs.microsoft.com/en-us/education/windows/set-up-school-pcs-shared-pc-mode
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/education/windows/set-up-school-pcs-shared-pc-mode.md

(The docs.microsoft.com page in question does not have a Feedback or "This page" reporting button.)

**Comment by e0i** [comment]
Hello, @idominiki 

> 
> How can I contact the technical team?
> 

You may contact support through this link for this specific problem: [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

The feedback form that you have submitted this feedback from is for issues related to the technical documentation. Please feel free to re-open this issue if you feel there is something wrong with the article.

Thank you for taking the time to provide feedback, and stay healthy.
