### ISSUE TITLE
Contradictory Proxy Information

### ISSUE THREAD

**Issue by Digiroka** [MicrosoftDocs/windows-itpro-docs#9499]
The information on this page is contradictory:

https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure#proxy-servers
**PROXY SERVER TEXT:** 
Specify the proxy servers your devices will go through to reach your cloud resources. **Using this server type indicates that the cloud resources you’re connecting to are enterprise resources.**

https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure#internal-proxy-servers
**INTERNAL PROXY SERVER TEXT:**
This list shouldn’t include any servers listed in your Proxy servers list. **Proxy servers must be used only for non-WIP-protected (non-enterprise) traffic.** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df27add-73fe-4f0b-7e30-face0f95cda3
* Version Independent ID: 3ec647d9-3470-8d8b-a941-d56f6522a35e
* Content: [Create a Windows Information Protection (WIP) policy with MDM using the Azure portal for Microsoft Intune (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
@Digiroka : In what way is the text contradictory? I am afraid I don't see the implication you refer to. Have I missed something important?

### Proxy servers

Specify the proxy servers your devices will go through to reach your cloud resources. 
Using this server type indicates that the cloud resources you’re connecting to are enterprise resources.

This list shouldn’t include any servers listed in your Internal proxy servers list. 
Internal proxy servers must be used only for WIP-protected (enterprise) traffic.
Separate multiple resources with the ";" delimiter.

```console
proxy.contoso.com:80;proxy2.contoso.com:443
```

### Internal proxy servers

Specify the internal proxy servers your devices will go through to reach your cloud resources. Using this server type indicates that the cloud resources you’re connecting to are enterprise resources.

This list shouldn’t include any servers listed in your Proxy servers list. 
Proxy servers must be used only for non-WIP-protected (non-enterprise) traffic.
Separate multiple resources with the ";" delimiter.

**Comment by Digiroka** [comment]
@illfated 

The contradiction is:

Proxy servers:
Using this server type indicates that the cloud resources you’re connecting to **are enterprise resources**.

Internal proxy servers
This list shouldn’t include any servers listed in your Proxy servers list.
**Proxy servers must be used only for non-WIP-protected (non-enterprise)** traffic.

So - are proxy servers used for enterprise or non-enterprise traffic?

**Comment by illfated** [comment]
Good question. Thank you for providing the clarification.
