### ISSUE TITLE
Difference between installed and provisioned apps

### ISSUE THREAD

**Issue by gcfishe** [MicrosoftDocs/windows-itpro-docs#950]
Can you provide an explanation of the difference between an installed or provisioned app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce0131fb-6b3a-5905-1738-253cf37e3b2d
* Version Independent ID: cab448be-54ae-539e-22ba-3d202a468d4f
* Content: [Windows 10 - Apps](https://docs.microsoft.com/en-us/windows/application-management/apps-in-windows-10)
* Content Source: [windows/application-management/apps-in-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/apps-in-windows-10.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by nischl** [comment]
You need more info than already given in second paragraph:

- Provisioned:
Installed the first time you sign into Windows. You'll see a tile or Start menu item for these apps, but they aren't installed until the first sign-in.
- Installed:
 Installed as part of the OS.

**Comment by hanbuivan** [comment]
Why are the Provisioned applications listed in 2 tables?

**Comment by lizap** [comment]
Some apps moved from provisioned to installed - that's why they show up in multiple tables. When that happens, we try to note it in the footnotes for the table. Thanks!
