### ISSUE TITLE
Get-TPM

### ISSUE THREAD

**Issue by felizondojr** [MicrosoftDocs/windows-itpro-docs#9501]
I would add Get-TPM cmdlet to the section on how to validate TPM information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d919cb35-d493-3da2-f90a-2c8440266d57
* Version Independent ID: 4aa3eea4-9311-d21a-35ee-ed8e9498b10e
* Content: [BitLocker overview and requirements FAQ (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-overview-and-requirements-faq?source=docs)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-overview-and-requirements-faq.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-overview-and-requirements-faq.yml)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Seems like a good idea. Will you be making a Pull Request to have the document updated?

**Comment by felizondojr** [comment]
Oh, I can actually make the change? Cool! Are there a set of instructions/procedures I need to follow?

​Regards,

Fernando Elizondo
Microsoft CE - Modern Work
+1 (469) 7754712
***@***.***
________________________________

**Comment by illfated** [comment]
Well, I have been using GitHub for more than 6 years, so it has been more or less obvious and self-explanatory to me. Then again, I presume it is a learning curve for newcomers.

In your case, I would recommend having a firm idea where to place the text and code you want to ad, so you are prepared before diving into the document source.

The source page in question is the following: https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-overview-and-requirements-faq.yml (as linked above in your main issue ticket).

In that page, find an edit button (maybe a pen icon?) on the right hand side of the screen.
Click that button to start editing the source.

When you have finished editing, scroll down to the bottom and write a short descriptive title (for example **Bitlocker FAQ: add Get-TPM cmdlet**

(Feel free to write additional descriptive text in the next empty field, about the change itself, or your reasoning behind this change.)

After you have completed those tasks, save your changes, which will then change the page to make it ready for creating the Pull Request.

If you at any step in the process find that you want to redo something, feel free to abandon your change and start editing the source page again.

Please also be aware that several other contributors, as well as Microsoft Docs team members, are available to answer your questions. Ask in the comments whenever you need more information.

I would have provided a link to a manual page, but most of them target programmers or independent contributors using Desktop tools, which is a big sidestep in the learning process.

**Comment by illfated** [comment]
Please also note: One of the advantages of creating a Pull Request in the public pages (in contrast to the internal Microsoft private repository) is that there is usually someone on hand to follow up the PR you create, as well as providing improvement suggestions or reviewing your PR before merging.

**Comment by e0i** [comment]
Hello @felizondojr Thank you for your interest in contributing to the IT Pro repository!

The repository could definitely use some help in the `bitlocker` topic areas. When you create a PR by following the steps as advised, your contribuions will be reviewed and approved.

Thanks again, and we are looking forward to your contributions.

@illfated Thank you for the introduction and your helpful commentaries as always.

**Comment by e0i** [comment]
Patching this to an independent contributor as there haven't a PR. Thanks for the discussion.
