### ISSUE TITLE
Azure MFA using WHFB no longer supported

### ISSUE THREAD

**Issue by jgallucci32** [MicrosoftDocs/windows-itpro-docs#9506]
We were informed by MSFT support today that following these instructions when using Azure AD Connect even though it is fully functional is no longer supported. Please update the documentation to provide a warning to users wanting to use the on-premise model with Azure MFA using Azure AD Connect that they cannot use this method. Instead they must re-deploy with one of the Hybrid models.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c2ca3e-9d15-5a4a-971a-bc1eb3cb2637
* Version Independent ID: ca1f6f75-8129-24d1-2426-21effa0ab151
* Content: [Validate and Deploy MFA for Windows Hello for Business with key trust - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-key-trust-validate-deploy-mfa)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-key-trust-validate-deploy-mfa.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-key-trust-validate-deploy-mfa.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
Thank you for this feedback. Do you still have the MS Support ticket number stored somewhere, in case any of the Microsoft Docs team members would like to ask for it later? (I don't need it, I just thought I should check, just in case.)

I also presume someone from the MS Docs team of tech writers will post questions at a later time.

**Comment by illfated** [comment]
( ref. https://github.com/MicrosoftDocs/windowsserverdocs/issues/5519 )

**Comment by jgallucci32** [comment]
@illfated Yes the ticket number is 2104260010006727

**Comment by illfated** [comment]
@e0i : FYI - maybe invite one of the tech writers or the page author to have a look at the report?

**Comment by e0i** [comment]
Under investigation. Thank you for the feedback.

**Comment by VLG17** [comment]
@jgallucci32 Do you feel like the note at the beginning of the article is adressing this topic? 

![image](https://user-images.githubusercontent.com/41186174/128844105-70ed9c14-c50c-4956-958f-8380f6ea179a.png)

If not, what statement would you like to see added? Could you come up with an example?

**Comment by jgallucci32** [comment]
@VLG17 No, that statement addresses a different topic. It addresses MFA Server which is different than the Microsoft Azure MFA extension to AD FS described in [Microsoft and third-party additional authentication methods](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-additional-authentication-methods-for-ad-fs#microsoft-and-third-party-additional-authentication-methods)

A more appropriate statement would be something like this:
> As of `Month Date, Year` , Microsoft will no longer support Microsoft Azure MFA as a third-party authentication method to AD FS for the on-premises deployment model when Active Directory is connected to Azure using Azure AD Connect. You must use one of the Hybrid deployment models for WHFB when Azure AD Connect is configured in your environment.

**Comment by e0i** [comment]
@mapalko Can you take a look? Thanks.

**Comment by mapalko** [comment]
I am no longer the area owner for this docs section.

**Comment by yogkumgit** [comment]
@paolomatarazzo

**Comment by paolomatarazzo** [comment]
I don't think the existing article needs to be updated. It clearly calls out that it applies to on-premises deployment type and after the *important* note: "Windows Hello for Business requires all users perform multi-factor authentication prior to creating and registering a Windows Hello for Business credential. On-premises deployments can use certificates, third-party authentication providers for AD FS, or a custom authentication provider for AD FS as an on-premises MFA option.".
I'm not sure if I misinterpreted the ask, but it seems correct.

**Comment by jgallucci32** [comment]
It's generally assumed if third-party and/or custom auth providers are supported then so would a first-party plugin. In this case the first-party MFA adapter for Azure is not supported, but other third party or custom ones are. This should be explicitly called out.

Most people purchasing Microsoft products expect them to integrate with each other first before non-microsoft products.

**Comment by paolomatarazzo** [comment]
@jgallucci32 thank you for clarifying. However, I don't agree with your statement. The MFA adapter is not supported in the context of on-premises deployments. Please check the definition of on-premises deployment here: https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-technology#on-premises-deployment
