### ISSUE TITLE
duplicate instructions 

### ISSUE THREAD

**Issue by bobert13581** [MicrosoftDocs/windows-itpro-docs#9516]
section 6 (in the 2nd set of steps) in 'Configure Certificate Superseding for the Domain Controller Authentication (Kerberos) Certificate Template' is duplicating the instructions found immediately after in 'Unpublish Superseded Certificate Templates'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800b8090-65a9-da9f-a930-1f80dc9f2c2d
* Version Independent ID: b4495b6a-4ca5-7aa1-7964-ef6e19275c4e
* Content: [Configure Hybrid Azure AD joined key trust Windows Hello for Business - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
Possibly 4 years old information, depending on which individual parts of the text you refer to.

Original document, from commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/1ef5e46e08c1a1c1a727b31348eaebf17cf12835:
- https://github.com/MicrosoftDocs/windows-itpro-docs/commit/1ef5e46e08c1a1c1a727b31348eaebf17cf12835#diff-83898d1110fb9584b454946a4426718dc93edd60c15173fabc6ae4c2c42dc733

**Configure Hybrid Azure AD joined Windows Hello for Business: Public Key Infrastructure** blame view (hello-hybrid-key-whfb-settings-pki.md):
- https://github.com/MicrosoftDocs/windows-itpro-docs/blame/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md

I don't think the original author (**Mike Stephens**) is available, at least not easily as a GitHub user.

Maybe @mapalko could share some insight or views on this matter?

**Comment by VLG17** [comment]
@bobert13581 I would say that section 6 (in the 2nd set of steps) in 'Configure Certificate Superseding for the Domain Controller Authentication (Kerberos) Certificate Template' is exposing directly how to unpublish the certificate templates you included in the superseded templates list, while the subsequent section is dedicated to unpublishing Superseded Certificate Templates and provides comprehensive details about how to do that (which include what was already stated).

I don't think it's needed to remove anything.
