### ISSUE TITLE
8 errors and 3 warnings were reported

### ISSUE THREAD

**Issue by ModQuadWarren** [MicrosoftDocs/windows-itpro-docs#9517]
Followed the guide exactly as written, with the exception of changing the domain, admin password, using 'Education' instead of 'Enterprise,' and updated WSUS to our local server address.

I've tried this process on two different newly imaged MDT Servers, 2 different HV Servers using 2 different ISOs.
Firewalls are disabled just to rule that out. All permissions are correct - everything looks exactly as it's supposed to according to your guide, yet it failed after installing ref image to HV client. ADK and MDT are the latest/greatest, running Server 2019 Standard. Have also tried increasing VM RAM to 4 GB.

The process stops after applying Win10 image - BDD log is full of errors. I'm not even sure where to start because googling these error codes basically tells me "uh, something went wrong but we don't know what'

Please help - I'd really like to implement MDT/WDS into our environment but not even being able to get desired results with basic documentation is becoming quite disheartening.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0eb8c97-caa0-bb05-4b91-14ad2adc4aac
* Version Independent ID: 0cc541a3-8198-c029-d795-308e673ee2f4
* Content: [Create a Windows 10 reference image (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image)
* Content Source: [windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by ModQuadWarren** [comment]
Following up with some error codes:
**In the BDD.LOG file, there are these errors:**
  Console > Failure when attempting to copy boot files.	ztiRunCommandHidden	5/12/2021 12:42:38 PM	0 (0x0000)

FAILURE ( 5616 ): 15299: Verify BCDBootEx	LTIApply	5/12/2021 12:42:38 PM	0 (0x0000)

Litetouch deployment failed, Return Code = -2147467259  0x80004005	LiteTouch	5/12/2021 12:42:38 PM	0 (0x0000)

**There are many errors in the SMSTS.LOG file as well:**
Failed to save environment to  (80070057)	TSManager	5/12/2021 12:36:59 PM	748 (0x02EC)

Failed to save the current environment block. This is usually caused by a problem with the program. Please check the Microsoft Knowledge Base to determine if this is a known issue or contact Microsoft Support Services for further assistance.
The parameter is incorrect. (Error: 80070057; Source: Windows)	TSManager	5/12/2021 12:36:59 PM	748 (0x02EC)

Failed to persist execution state. Error 0x(80070057)	TSManager	5/12/2021 12:36:59 PM	748 (0x02EC)

Failed to save execution state and environment to local hard disk	TSManager	5/12/2021 12:36:59 PM	748 (0x02EC)

Failed to save environment to  (80070057)	TSManager	5/12/2021 12:37:01 PM	748 (0x02EC)

Failed to save the current environment block. This is usually caused by a problem with the program. Please check the Microsoft Knowledge Base to determine if this is a known issue or contact Microsoft Support Services for further assistance.
The parameter is incorrect. (Error: 80070057; Source: Windows)	TSManager	5/12/2021 12:37:01 PM	748 (0x02EC)

Failed to persist execution state. Error 0x(80070057)	TSManager	5/12/2021 12:37:01 PM	748 (0x02EC)

Failed to save execution state and environment to local hard disk	TSManager	5/12/2021 12:37:01 PM	748 (0x02EC)

^^ these last four errors happen several times ^^

Failed to run the action: Install Operating System. 
Unknown error (Error: 000015F0; Source: Unknown)	TSManager	5/12/2021 12:42:38 PM	748 (0x02EC)

The execution of the group (Install) has failed and the execution has been aborted. An action failed.
Operation aborted (Error: 80004004; Source: Windows)	TSManager	5/12/2021 12:42:38 PM	748 (0x02EC)

Failed to run the last action: Install Operating System. Execution of task sequence failed.
Unknown error (Error: 000015F0; Source: Unknown)	TSManager	5/12/2021 12:42:38 PM	748 (0x02EC)

Task Sequence Engine failed! Code: enExecutionFail	TSManager	5/12/2021 12:42:38 PM	748 (0x02EC)

Task sequence execution failed with error code 80004005	TSManager	5/12/2021 12:42:38 PM	748 (0x02EC)

RegQueryValueExW is unsuccessful for Software\Microsoft\SMS\Task Sequence, SMSTSEndProgram	TSManager	5/12/2021 12:42:38 PM	748 (0x02EC)

GetTsRegValue() is unsuccessful. 0x80070002.	TSManager	5/12/2021 12:42:38 PM	748 (0x02EC)

Error Task Sequence Manager failed to execute task sequence. Code 0x80004005	TSManager	5/12/2021 12:42:38 PM	748 (0x02EC)

Again, everything is up to date and the process outlined on this page is followed very closely.
Any help would be appreciated.

**Comment by ModQuadWarren** [comment]
I just wanted to follow up on this - the crux of the problem was this error: Fix Failure (5616): 15299: Verify BCDBootEx 
Basically, the new ADK (2004) breaks the task sequence in MDT.

The fix was [this](https://www.deploymentresearch.com/making-mdt-work-with-windows-adk-2004-for-bios-machines/) This process injects a script after the  New Computer/Verify step in Task Sequence.
Issue resolved! I now have a fully functional reference machine (VM)

Should I leave this report open so this can be reported to Microsoft?
Thanks!

**Comment by greg-lindsay** [comment]
Hi @ModQuadWarren I will add this support link to the article, thanks for figuring out the resolution - sorry for the slow response.  I am updating the article today and you should see the change tomorrow. Thanks again!
