### ISSUE TITLE
We need to limit by groups.

### ISSUE THREAD

**Issue by cking22001** [MicrosoftDocs/windows-itpro-docs#952]
Collections would be a great way to do this. Let us set permission on what apps a user sees!!! I need to have general group that all can get then some special apps for a few groups. Having to directly assign apps to individual users is a PIA!

Please please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e01999c4-a97e-8f90-6d2d-1fb38bd42f48
* Version Independent ID: e9417d57-7355-987d-827b-f753905eec5f
* Content: [Manage private store settings (Windows 10)](https://docs.microsoft.com/en-us/microsoft-store/manage-private-store-settings#private-store-collections)
* Content Source: [store-for-business/manage-private-store-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/manage-private-store-settings.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@cking22001 - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Windows 10 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
