### ISSUE TITLE
 Description text for "KeyUsage" is duplicated under "EKUMapping".

### ISSUE THREAD

**Issue by naykroveg** [MicrosoftDocs/windows-itpro-docs#9521]
Description text for "KeyUsage" is duplicated under "EKUMapping".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba73a4d0-cfe2-e988-58ba-ead197ea2e30
* Version Independent ID: 3070acc3-ea72-f425-3179-b4d26baf7027
* Content: [ClientCertificateInstall CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/clientcertificateinstall-csp)
* Content Source: [windows/client-management/mdm/clientcertificateinstall-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/clientcertificateinstall-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Sorry for being so slow to see what you mean. I had to swap back and forth between the search terms and read through the sections for 10 minutes until I finally saw what you may be referring to:

***

**ClientCertificateInstall/SCEP/*UniqueID*/Install/EKUMapping**  
Required. Specifies extended key usages. Subject to SCEP server configuration. The list of OIDs are separated by a plus <strong>+</strong>. For example, <em>OID1</em>+<em>OID2</em>+<em>OID3</em>.

Data type is string.
Required for enrollment. Specifies the key usage bits (0x80, 0x20, 0xA0, etc.) for the certificate in decimal format. The value should at least have the second (0x20), fourth (0x80) or both bits set. If the value doesn’t have those bits set, the configuration will fail.

Data type is int.

Supported operations are Add, Get, Delete, and Replace.

***

**ClientCertificateInstall/SCEP/*UniqueID*/Install/KeyUsage**  
Required for enrollment. Specify the key usage bits (0x80, 0x20, 0xA0, etc.) for the certificate in decimal format. The value should at least have second (0x20) or forth (0x80) or both bits set. If the value doesn’t have those bits set, configuration will fail.

 Supported operations are Add, Get, Delete, and Replace. Value type is integer.

**Comment by illfated** [comment]
Just to sum up: I presume the text we need to remove is the following (as shown in the diff below) :

```diff
  **ClientCertificateInstall/SCEP/*UniqueID*/Install/EKUMapping**  
  Required. Specifies extended key usages. Subject to SCEP server configuration. The list of OIDs are separated by a plus <strong>+</strong>. For example, <em>OID1</em>+<em>OID2</em>+<em>OID3</em>.
  
  Data type is string.
- Required for enrollment. Specifies the key usage bits (0x80, 0x20, 0xA0, etc.) for the certificate in decimal format. The value should at least have the second (0x20), fourth (0x80) or both bits set. If the value doesn’t have those bits set, the configuration will fail.
- 
- Data type is int.
- 
- Supported operations are Add, Get, Delete, and Replace.
```

**Comment by illfated** [comment]
I would also like to mention that **any MarkDown pages** still using the HTML tags \<strong\> \</strong\> (as well as the \<em\> \</em\> tags) need to have those tags replaced with real MarkDown code to avoid causing Machine Translated pages to break due to formatting issues during translation, based on the content in the GitHub .md files.

Due to how Machine Translation works, it is safe to say that those HTML tags are deprecated in the Microsoft MarkDown files.

**Comment by naykroveg** [comment]
> Just to sum up: I presume the text we need to remove is the following (as shown in the diff below) :
> 
> ```diff
>   **ClientCertificateInstall/SCEP/*UniqueID*/Install/EKUMapping**  
>   Required. Specifies extended key usages. Subject to SCEP server configuration. The list of OIDs are separated by a plus <strong>+</strong>. For example, <em>OID1</em>+<em>OID2</em>+<em>OID3</em>.
>   
>   Data type is string.
> - Required for enrollment. Specifies the key usage bits (0x80, 0x20, 0xA0, etc.) for the certificate in decimal format. The value should at least have the second (0x20), fourth (0x80) or both bits set. If the value doesn’t have those bits set, the configuration will fail.
> - 
> - Data type is int.
> - 
> - Supported operations are Add, Get, Delete, and Replace.
> ```

Yes, that is what I meant. Also, note that the actual description for **ClientCertificateInstall/SCEP/UniqueID/Install/KeyUsage**
is missing the data type part: "**Data type is int**"

**Comment by illfated** [comment]
> Also, note that the actual description for **ClientCertificateInstall/SCEP/UniqueID/Install/KeyUsage**
> is missing the data type part: "**Data type is int**"

Thank you very much. I did not notice that detail before you mentioned it. I just noticed that when the datatype is string, there is no "Supported operations are" paragraph.
