### ISSUE TITLE
Please add a note

### ISSUE THREAD

**Issue by dbona75** [MicrosoftDocs/windows-itpro-docs#9523]
Please add this note in Countermeasure part : if the a service account is configured in log on properties of a windows service it requires the network log on rights to the domain controllers, to start properly. 

Daniele Bona
Security & Identity

dabona@microsoft.com

**Comment by illfated** [comment]
@dbona75 : May we know which document article you are referring to?

**Comment by dbona75** [comment]
https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/deny-access-to-this-computer-from-the-network

**Comment by illfated** [comment]
Thank you. Normally, if the issue had been reported via the **[:octocat: This page]** button in the Feedback section, the primary ticket comment post would have contained the following descriptive text:

***

[Enter feedback here]


---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 192bc7af-26af-6a5e-ac99-ad133b1a4081
* Version Independent ID: 3d44ce52-c5c3-d506-925c-03aecee43201
* Content: [Deny access to this computer from the network (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/deny-access-to-this-computer-from-the-network)
* Content Source: [windows/security/threat-protection/security-policy-settings/deny-access-to-this-computer-from-the-network.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/deny-access-to-this-computer-from-the-network.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Preliminary draft of the MarkDown code necessary to add such a Note blob:

```markdown

> [!NOTE]
> If the service account is configured in the logon properties of a Windows Service,
> it requires Network Logon rights to the domain controllers to start properly.

```
Note: Even though there is a visual line break in this view, the sentence will be contiguous in the colored Note blob.

**Comment by dbona75** [comment]
Perfect for me !

Scarica Outlook<https://aka.ms/qtex0l> per iOS
________________________________
Da: Trond B. Krokli ***@***.***>
Inviato: Thursday, May 13, 2021 11:23:40 PM
A: MicrosoftDocs/windows-itpro-docs ***@***.***>
Cc: Daniele Bona ***@***.***>; Mention ***@***.***>
Oggetto: Re: [MicrosoftDocs/windows-itpro-docs] Please add a note (#9523)


Preliminary draft of the MarkDown code necessary to add such a Note blob:

> [!NOTE]
> If the service account is configured in the logon properties of a Windows Service,
> it requires Network Logon rights to the domain controllers to start properly.


Note: Even though there is a visual line break in this view, the sentence will be contiguous in the colored Note blob.

**Comment by illfated** [comment]
There you go, PR #9531 is now ready for review, comments, and improvement suggestions.
