### ISSUE TITLE
WDAC managed installer instructions missing a step

### ISSUE THREAD

**Issue by timbrigham-onecall** [MicrosoftDocs/windows-itpro-docs#9524]
Within configure-wdac-managed-installer.md there is at least one missing step. 

After creating the applocker policy document AppLocker_MI_PS_ISE.xml there is no further reference to what do with this file once the edits are complete. I believe this needs to include a "Set-AppLockerPolicy xxx" or similar statement.

**Comment by RAJU2529** [comment]
@timbrigham-onecall .which article are talking about  Applocker or WDAC

**Comment by RAJU2529** [comment]
@timbrigham-onecall . Simply you can download  WDAC  wizard tool, and  create policy and configure

**Comment by timbrigham-onecall** [comment]
@RAJU2529 , I was referring to this specific documentation.  

https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/configure-wdac-managed-installer.md

There are detailed instructions on creating AppLocker_MI_PS_ISE.xml for the creation of a managed installer, but there are no instructions within that document (or a link to an outside source) of what needs to be done with it to apply the configuration.

**Comment by RAJU2529** [comment]
@timbrigham-onecall , read Enable the managed installer option in WDAC policy

**Comment by timbrigham-onecall** [comment]
I'm familiar with the Set-RuleOption and Set-CIPolicyIdInfo commands, and they are applicable to the code integrity configuration files.. 

I believe those instructions are intended for the working file that is from
"Copy the DefaultWindows_Audit policy into your working folder from C:\Windows\schemas\CodeIntegrity\ExamplePolicies\DefaultWindows_Audit.xml".. which is not AppLocker_MI_PS_ISE.xml

**Comment by RAJU2529** [comment]
@timbrigham-onecall , Codeintegrity  folder contains default .bin file and it belongs to WDAC

**Comment by e0i** [comment]
@timbrigham-onecall

An independent contributor is going to provide the missing instruction steps thanks to your feedback! 

This documentation repository is open-source. If you encounter any errors like this one and there is something you can do to improve the article, [you may submit a Pull Request](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/CONTRIBUTING.md). Your contribution then will be reviewed and approved accordingly.

**Comment by illfated** [comment]
(This is how the main issue ticket comment could have appeared if it had been opened via the button ![Screenshot 2021-05-30 175849](https://user-images.githubusercontent.com/38162891/120111082-c75a1680-c170-11eb-93bb-88d41c3c9f38.png) at the end of the page https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/configure-wdac-managed-installer . )

***

Within configure-wdac-managed-installer.md there is at least one missing step.

After creating the applocker policy document AppLocker_MI_PS_ISE.xml there is no further reference to what do with this file once the edits are complete. I believe this needs to include a "Set-AppLockerPolicy xxx" or similar statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5881f449-2567-9d50-99be-0b6cdb1218d7
* Version Independent ID: e4d0109a-54dc-3bb9-d4c5-cad8fdf93179
* Content: [Configure a WDAC managed installer (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/configure-wdac-managed-installer)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/configure-wdac-managed-installer.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/configure-wdac-managed-installer.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@timbrigham-onecall My understanding is that after you create the AppLocker policy, you would [import it into a GPO](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/import-an-applocker-policy-into-a-gpo). That's where you would use the .xml file AppLocker_MI_PS_ISE.xml.

To import an AppLocker policy into a GPO

In the Group Policy Management Console (GPMC), open the GPO that you want to edit.
In the console tree under Computer Configuration\Policies\Windows Settings\Security Settings\Application Control Policies, click AppLocker.
Right-click AppLocker, and then click Import Policy.
In the Import Policy dialog box, **_locate the XML policy file_**, and click Open.
The AppLocker dialog box will notify you of how many rules were imported. Click OK.
