### ISSUE TITLE
Sandbox documentation missing RAIL mode

### ISSUE THREAD

**Issue by timmontague** [MicrosoftDocs/windows-itpro-docs#9529]
In the Sandbox overview video embedded in https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md it demonstrates "remote applications integrated locally" (RAIL) mode at 26:48. In RAIL mode an application running in the Sandbox is integrated with the host OS and the Sandbox desktop is not shown. The Sandbox configuration documentation does not explain how to enable that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2efc9d32-0f98-0804-78a4-4caccdfac010
* Version Independent ID: 797bb0d3-bade-98f6-fe85-508764571f37
* Content: [Windows Sandbox configuration - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by timmontague** [comment]
Duplicate:  #9025

**Comment by illfated** [comment]
@timmontague : Maybe you want to open a new ticket. It seems that your reference may have been misunderstood, so both tickets are closed now.

Please note: If you ever write "Duplicate: #xxxx" in a comment, it will be interpreted as you saying 
"Please close this current ticket, it is a duplicate of another open issue ticket on the same exact issue."

**Comment by bjoljo** [comment]
Any updates regarding this? Where is the documentation covering RAIL mode?
