### ISSUE TITLE
Win Hello for Business with pre-configured sign-in situations

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/windows-itpro-docs#953]
Hey guys,

What's the expected behavior for devices that recieve a MAM policy with Windows Hello for Business enabled, but already have a PIN or facial login previously configured for the user account they're logged in with? Does Hello for Business adopt the PIN, or does it not apply at all?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ad3f92-24de-5eb5-8454-c72d85737183
* Version Independent ID: 900125eb-31ea-faf3-ac30-7c3d7b30f611
* Content: [Create a Windows Information Protection (WIP) policy with MAM using the Azure portal for Microsoft Intune (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-mam-intune-azure)
* Content Source: [windows/security/information-protection/windows-information-protection/create-wip-policy-using-mam-intune-azure.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/create-wip-policy-using-mam-intune-azure.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by Justinha** [comment]
@thedrum808 sorry for delay. Passing along this from our engineering team:
Hello for Business will adopt that PIN.  When the user MAM enrolls it will show the create a PIN page and may ask for the PIN.  Then it enrolls a key and optionally a certificate.   If the PIN doesn’t meet the policy set by the organization the user will be asked to change it.

**Comment by thedrum808** [comment]
Thanks Justin! That helps a ton.

________________________________
