### ISSUE TITLE
Link seems to be broken

### ISSUE THREAD

**Issue by yossibanai** [MicrosoftDocs/windows-itpro-docs#9534]
This link at the end of the article: Microsoft Defender for Endpoint](https://www.microsoft.com/windowsforbusiness?ocid=docs-fileless), seems to be broken. The page it links to is the generic Windows 10 page, and has nothing to do with Microsoft Defender for Endpoint.

**Comment by illfated** [comment]
Are you talking about the page **Windows 10 devices for business** (https://www.microsoft.com/en-us/windowsforbusiness) — or are you talking about some other page where there is a link pointing to that page?

If the latter is correct, then please tell us which page this is about. It is possible that you have missed the reporting button.

**Comment by yossibanai** [comment]
Sorry, I thought my content will include the information about the source page. 

The page I was reading is https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/fileless-threats#feedback. The broken link I'm referring to is in this paragraph:

Defeating fileless malware
At Microsoft, we actively monitor the security landscape to identify new threat trends and develop solutions to mitigate classes of threats. We instrument durable protections that are effective against a wide range of threats. Through AntiMalware Scan Interface (AMSI), behavior monitoring, memory scanning, and boot sector protection, Microsoft Defender for Endpoint](https://www.microsoft.com/windowsforbusiness?ocid=docs-fileless) can inspect fileless threats even with heavy obfuscation. Machine learning technologies in the cloud allow us to scale these protections against new and emerging threats.

Does this help?

**Comment by illfated** [comment]
https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/fileless-threats#defeating-fileless-malware

Thank you, that helps a lot. If you had used the button **[**:octocat: **This page ]** as in the image below;

![image](https://user-images.githubusercontent.com/38162891/118591057-d40b6180-b7a3-11eb-8145-c8203e278b4d.png)

it would have produced the accompanying text:

***

[Enter feedback here]


---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ac7d184-cde4-80cf-8e93-ae174ad7c938
* Version Independent ID: 751c5d5d-170b-b09e-ff80-2efabdb6b7a5
* Content: [Fileless threats - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/fileless-threats#defeating-fileless-malware)
* Content Source: [windows/security/threat-protection/intelligence/fileless-threats.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/fileless-threats.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

***

Not to worry, it will be possible to continue from here.
