### ISSUE TITLE
Add registry location to documentation and its detail

### ISSUE THREAD

**Issue by kafold** [MicrosoftDocs/windows-itpro-docs#9536]
[Enter feedback here]
The page does not mention the registry location backed by the group policy.
Group Policy : Computer Configuration\Windows Settings\Security Settings\Local Policies\Security Options.

I was looking into the [CIS Windows Server 2019 benchmark v1.2.0](https://workbench.cisecurity.org/files/3238) and in section 2.3.5.4 of the former document the registry location for this policy is said to be HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NTDS\Parameters:LDAPServerIntegrity. 

I could not find the registry details anywhere. I usually use the site admx.help to get registry details. But it is not mentionned there.

Recommendation : Add the registry detail in this documentation page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5db8802-afa2-017d-d898-46653a641ba7
* Version Independent ID: 23f9dca4-94a1-0803-e038-cf80bce83fc0
* Content: [Domain controller LDAP server signing requirements (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/domain-controller-ldap-server-signing-requirements)
* Content Source: [windows/security/threat-protection/security-policy-settings/domain-controller-ldap-server-signing-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/domain-controller-ldap-server-signing-requirements.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@kafold You can read this article from Microsoft, which includes the location of a registry key.

**https://support.microsoft.com/topic/client-service-and-program-issues-can-occur-if-you-change-security-settings-and-user-rights-assignments-0cb6901b-dcbf-d1a9-e9ea-f1b49a56d53a**
