### ISSUE TITLE
Add registry location to doc for Domain controller: Refuse machine account password changes

### ISSUE THREAD

**Issue by kafold** [MicrosoftDocs/windows-itpro-docs#9537]
[Enter feedback here]
The page does not mention the registry location backed by the group policy.
Group Policy : Computer Configuration\Policies\Windows Settings\Security Settings\Local Policies\Security Options\Domain controller: Refuse machine account password changes.

I was looking into the [CIS Windows Server 2019 benchmark v1.2.0](https://workbench.cisecurity.org/files/3238) and in section 2.3.5.5 of the former document the registry location for this policy is said to be HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters:RefusePasswordChange.

I could not find the registry details anywhere. I usually use the site admx.help to get registry details. But it is not mentionned there.

Recommendation : Add the registry detail in this documentation page.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e5893a8-51c7-c42c-904d-e606bfb14123
* Version Independent ID: d9478fe8-244c-8f26-e89a-e1658db66ebf
* Content: [Refuse machine account password changes policy (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/domain-controller-refuse-machine-account-password-changes)
* Content Source: [windows/security/threat-protection/security-policy-settings/domain-controller-refuse-machine-account-password-changes.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/domain-controller-refuse-machine-account-password-changes.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@kafold 

Thank you for spotting the missing registry value. An independent contributor is going to verify the claim in your feedback and revise the article based on your suggestion.

This documentation repository is open-source, so please feel free to come up with any suggestions via submitting a [Pull Request](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/CONTRIBUTING.md), and your contributions are going to be reviewed. 

Bonne journée!
