### ISSUE TITLE
No way to disable TPM...

### ISSUE THREAD

**Issue by kolonuk** [MicrosoftDocs/windows-itpro-docs#9539]
Need a method to disable TPM if there is no "Turn Off" option.

**Comment by denisebmsft** [comment]
Hello @kolonuk. Thank you for posting your feedback here. Can you please tell to which article(s) this applies? It'll help us route this issue to the correct writer/team.

**Comment by e0i** [comment]
@kolonuk Please feel free to re-open this issue with the associated article for your content feedback. Thank you.
