### ISSUE TITLE
Missing System/AllowUpdateComplianceProcessing

### ISSUE THREAD

**Issue by jsnyder33** [MicrosoftDocs/windows-itpro-docs#9540]
Documentation is missing "System/AllowUpdateComplianceProcessing" which is required for Update Compliance as of 5/10/2021.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c833e5b-0fcf-2ace-a90a-3270286d23a9
* Version Independent ID: 64afbc38-e7cc-fc14-9d57-1cd119b2395d
* Content: [Policy CSP - System - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-system)
* Content Source: [windows/client-management/mdm/policy-csp-system.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-system.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@bitslacker . thanks for pointing out. I am going to add that policy now.

**Comment by illfated** [comment]
( ref. #9554 )
