### ISSUE TITLE
Duplicate/Error in Options Column of GPO-Table

### ISSUE THREAD

**Issue by Reittier** [MicrosoftDocs/windows-itpro-docs#9546]
The descriptions (Option column) of the GPO settings

"Allow favorites sync"
and 
"Allow extensions in the container"

in the table are a duplicate. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad59e7d-574d-7bd5-3fc9-a9656e186258
* Version Independent ID: e827f939-99b2-31e7-b65a-ee3ad499573e
* Content: [Configure the Group Policy settings for Microsoft Defender Application Guard (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-application-guard/configure-md-app-guard)
* Content Source: [windows/security/threat-protection/microsoft-defender-application-guard/configure-md-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-application-guard/configure-md-app-guard.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by joinimran** [comment]
Hello @Reittier - Thank you for your feedback. I was looking for the duplicate entries in the document but couldn't find anything. Can you please confirm if the referenced document is the correct one. 

Thanks.

**Comment by joinimran** [comment]
Hello @Reittier -  I was looking for the duplicate entries in the document but couldn't find anything. Can you please confirm if the referenced document is the correct one.

**Comment by Reittier** [comment]
Hi @joinimran - The Error was already fixed at May 21. 3 days after I posted it here at May 19.
You can see here https://github.com/MicrosoftDocs/windows-itpro-docs/blob/e22ca366247da22a4571075f7bce5e6f23647fa8/windows/security/threat-protection/microsoft-defender-application-guard/configure-md-app-guard.md 
the duplicate was still there, but with commit 832aff3e5a4f6e45bb0df6aabd8678686c505be2 it was fixed already.

So I close that now.
