### ISSUE TITLE
Teams firewall prompt, policy rules and local policy merge

### ISSUE THREAD

**Issue by flatfour67** [MicrosoftDocs/windows-itpro-docs#9547]
The page show the Teams prompt as an example - this is somewhat frustrating as with local policy merge disabled, there is no way to deploy the Teams firewall rules via GPO/MDM, since they need to specify the path to teams.exe in each user profile - and we are informed on the same page that wildcard rules are not supported.

A description of how to centrally deploy rules for Teams that do permit blocking of local policy merge would be more useful, or at the very least not using the worst possible example imaginable in the screenshot?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88e8e24b-481e-babb-a4e7-c5639f2492a2
* Version Independent ID: f61e0165-fd95-0fc4-a52c-0b4c40735ea3
* Content: [Best practices for configuring Windows Defender Firewall - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/best-practices-configuring)
* Content Source: [windows/security/threat-protection/windows-firewall/best-practices-configuring.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/best-practices-configuring.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by joinimran** [comment]
Hello @flatfour67 - Thank you for your message. Please note that these are known issues with MS teams and will be addressed with future releases. In the meantime, please create rules for new applications before 1st lunch as that can help users have a better experience. 
Thanks.
