### ISSUE TITLE
window 11

### ISSUE THREAD

**Issue by Velski1234** [MicrosoftDocs/windows-itpro-docs#9548]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a31db82-81be-16aa-9e39-62c6810517d8
* Version Independent ID: 30fe7813-ac6e-8167-02d6-9fa5e530a3f6
* Content: [What's new in Windows 10, version 20H2 - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-20h2)
* Content Source: [windows/whats-new/whats-new-windows-10-version-20H2.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/whats-new-windows-10-version-20H2.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
I need more information to address this issue. Please reopen with more details.
