### ISSUE TITLE
Logging into a windows app with an org account always prompts for Windows Hello setup

### ISSUE THREAD

**Issue by rbishop-etq** [MicrosoftDocs/windows-itpro-docs#9550]
As part of our current license, we have Intune, which allows for the use of Windows Hello for Business.
We have this fully disabled as we need users to only login to their apps via full password along with MFA. The issue is that machines logging in to our environment are not respecting this policy.

When a user with a newly imaged device (not joined to any domain) tries to login to an MS app such as Teams or Edge, it pops up with the option to stay logged in to their apps (first image), which will essentially add the MS account to windows for them. If they click OK there, they then get a message stating that "YOUR ORGANIZATION" requires that they setup a windows hello PIN (third image), which to put it simply, is a lie. We DO NOT want them to setup a PIN and our Intune policy accurately reflects this.
We have found that the only way to fully bypass this prompt for the user to setup a PIN, is to have them set a registry key to disable windows hello for business on their local machine.

We see this as a large oversight, as the message telling the user that their ORGANIZATION is the one requiring this, is an issue in and of itself (when it is nothing more than a default local machine policy or lack thereof generating this need), but what really should be happening is when a user is logging in to a company account from any PC, it should be referencing the policy as set in that tenant to determine what is actually needed in order to login and connect their machine to that tenant.

I am submitting this bug report as i was directed by the Microsoft support rep as part of the ticket i sent in, in which no fix could be found outside of the manual registry keys or manual local group policy to be set on the local machine BEFORE the user tries logging in. Ticket TrackingID#2103300040000250

![image](https://user-images.githubusercontent.com/83786785/118903279-b38ef480-b8d4-11eb-82c5-398e013ef644.png)
![image](https://user-images.githubusercontent.com/83786785/118903294-bb4e9900-b8d4-11eb-9a8a-bc7a23d56a06.png)
![image](https://user-images.githubusercontent.com/83786785/118903305-c1447a00-b8d4-11eb-828c-69502e0c0fb0.png)

**Comment by denisebmsft** [comment]
Hello @rbishop-etq. Can you please tell us to which article(s) this applies? This information will help us route the issue to the correct writer/team.

**Comment by rbishop-etq** [comment]
Sorry, i'm not sure. This is the location i was directed to leave this bug report by MS support team as part of my ticket with them.
It concerns windows hello for business on Windows 10 machines if that helps?

**Comment by RAJU2529** [comment]
@rbishop-etq , uncheck mark  Allow my organisation to manage my device. and proceed  further.

What do you  Imaged device means ?

**Comment by RAJU2529** [comment]
@rbishop-etq . you mentioned in your post , **When a user with a newly imaged device** 
what do you mean by imaged device.?

**Comment by illfated** [comment]
I am fairly certain that "imaged device" is any Windows computer installed with a configured ISO, tailored to their specific needs.

The only part I could think of as uncertain in that setup, is whether it is a clean Microsoft environment or if there is any 3rd party software in the ISO.

**Comment by rbishop-etq** [comment]
Yes, its just a cleanly imaged device using MS media. Though we have other apps get installed, the Local Group policy and corresponding REG settings are all default per MS generic image.

**Comment by rbishop-etq** [comment]
@denisebmsft 
Can you please share some explanation why you have closed this?
Is this Windows issue going to be fixed?

**Comment by rbishop-etq** [comment]
@denisebmsft 
Please provide an update

**Comment by rbishop-etq** [comment]
@e0i Can you provide any update?
There has been no response by @denisebmsft
