### ISSUE TITLE
Can I use an external camera when my laptop is closed or docked?

### ISSUE THREAD

**Issue by ydewk** [MicrosoftDocs/windows-itpro-docs#9552]
[Enter feedback here]
Can I use an external camera when my laptop is closed or docked?
As of Windows 10 21H1 this is now possible with dual cameras, as the external camera from now on is the default one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f7820d-5521-10fb-3970-a7403b9a83c1
* Version Independent ID: 81acb0ad-2d46-bd0b-abb5-7c2e851d7a71
* Content: [Windows Hello for Business Frequently Asked Questions (FAQ) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-faq)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-faq.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-faq.yml)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by I-Cat** [comment]
> [Enter feedback here]
> Can I use an external camera when my laptop is closed or docked?
> As of Windows 10 21H1 this is now possible with dual cameras, as the external camera from now on is the default one.
> 
> #### Document Details
>  _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 98f7820d-5521-10fb-3970-a7403b9a83c1
> * Version Independent ID: 81acb0ad-2d46-bd0b-abb5-7c2e851d7a71
> * Content: [Windows Hello for Business Frequently Asked Questions (FAQ) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-faq)
> * Content Source: [windows/security/identity-protection/hello-for-business/hello-faq.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-faq.yml)
> * Product: **w10**
> * GitHub Login: @mapalko
> * Microsoft Alias: **mapalko**

>> You can If you disable the driver that tells the os to snooze / go to sleep while the lid is closed.

**Comment by illfated** [comment]
> You can If you disable the driver that tells the OS to snooze / go to sleep while the lid is closed.

This may even be not necessary on some laptops, depending on brand and model. Some laptops, especially ones designed to be used with a docking, may already be aware of connected external screens while the integrated screen is closed. As long as the external web camera does not show any driver issues or compatibility issues with the communication software, it should be no problem at all.

**Comment by I-Cat** [comment]
> > You can If you disable the driver that tells the OS to snooze / go to sleep while the lid is closed.
> 
> This may even be not necessary on some laptops, depending on brand and model. Some laptops, especially ones designed to be used with a docking, may already be aware of connected external screens while the integrated screen is closed. As long as the external web camera does not show any driver issues or compatibility issues with the communication software, it should be no problem at all.

Yes a Need more info label should be issued.
Also I do not see any infromation on what kind of  system that is running.
I suggest the Issue Template needs to be updated.

**Comment by illfated** [comment]
> Can I use an external camera when my laptop is closed or docked?

@ydewk : Could you please provide some more information about your scenario and hardware? In most cases, this should not be an issue.

**Comment by e0i** [comment]
Closing as the question has been answered by the community. Thanks for the discussion.
