### ISSUE TITLE
could not able to find the settings for Allow extensions in the container and Allow favorites sync

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#9555]
I could not able to find the following settings for 
a. Allow extensions in container
b. Allow favorites sync
under this  **Computer Configuration\Administrative Templates\Windows Components\Microsoft Defender Application Guard**
![Capture](https://user-images.githubusercontent.com/3296790/119013111-4f436200-b9b4-11eb-8130-8cf089da8b1e.JPG)

i am using Windows 10 21H1 64bit prerelease build no 19043.985
BuildLab ::19041.vb_release.191206-1406
BuildLabEx ::19041.1.amd64fre.vb_release.191206-1406
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad59e7d-574d-7bd5-3fc9-a9656e186258
* Version Independent ID: e827f939-99b2-31e7-b65a-ee3ad499573e
* Content: [Configure the Group Policy settings for Microsoft Defender Application Guard (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-application-guard/configure-md-app-guard)
* Content Source: [windows/security/threat-protection/microsoft-defender-application-guard/configure-md-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-application-guard/configure-md-app-guard.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by e0i** [comment]
It is not clear how this relates to the documentation. Please submit product feedback via the [Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

Thanks.
