### ISSUE TITLE
WDAC Conflict with Virtualization Based Protection of Code Integrity

### ISSUE THREAD

**Issue by benavidezb** [MicrosoftDocs/windows-itpro-docs#9556]
I have found that there is a compatibility issue between enabling [Virtualization Based Protection of Code Integrity](https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity) and creating custom WDAC policies. Specifically, deploying a signed policy which does not allow unsigned policies alongside enabling Virtualization Based Protection of Code Integrity with UEFI Lock will cause boot failures while Secure Boot is enabled. I think it would be good to note this conflict by creating a warning of some sort somewhere on the WDAC page. This issue may require validation by Microsoft, though, in case my issue is rooted elsewhere. I did find that turning off Virtualization Based Protection of Code Integrity allowed me to boot, but it's not clear if that now means I can't use HVCI with custom WDAC policies at all.

It would also be helpful to note exactly what is being done when Virtualization Based Protection of Code Integrity is enabled, namely that a WDAC policy called "Microsoft Windows Driver Policy" with Policy ID D2BDA982-CCF6-4344-AC5B-0B44427B6816 is applied with rule 6 and rule 9 enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b5e396-a7d4-af3c-fde2-5b8374d0ad27
* Version Independent ID: 9ea74c2f-76d4-9735-ac2b-cc38e1bd00f6
* Content: [Deploying Windows Defender Application Control (WDAC) policies (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control-deployment-guide#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control-deployment-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control-deployment-guide.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@benavidezb . Did you tested wadc policy in audio mode before applying to main device.
recently Microsoft released WADC wizard policy creator, you can download below site
https://webapp-wdac-wizard.azurewebsites.net/

**Comment by benavidezb** [comment]
@RAJU2529, I did. Audit mode of course works (note also that I am also using Windows' default rules from Windows\schemas\CodeIntegrity). Although I did not try signing and enforcing policy signers in audit mode. My guess is that it would result in the same boot failure which I'll explain below. My WDAC policy creation workflow is to first check that nothing important is being blocked with audit mode (unsigned policy) and then switch to enforcement mode and sign the policy. Note that enabling rule 6 (Unsigned System Integrity Policy) will allow the device to boot which I am guessing is because the Microsoft Windows Driver Policy is unsigned. However, this approach is not acceptable because I think my policy could then simply be replaced with an unsigned policy (not secure - see [Disable Windows Defender Application Control policies](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/disable-windows-defender-application-control-policies)). Disabling rule 6 and requiring signed policies protects my policy from being replaced or disabled; however, it doesn't allow the Microsoft Windows Driver Policy to apply. My theory is that if UEFI Lock is selected from the Virtualization Based Protection of Code Integrity GPO/CSP then when the Microsoft Windows Driver Policy is blocked for being unsigned it also triggers the UEFI Lock. It may be that enabling HVCI's Virtualization Based Protection of Code Integrity WITHOUT UEFI Lock could also resolve this (rather than completely disabling it) but I have not tried that yet (changing around WDAC policies can be labor intensive, especially using CSPs as is my case). I would be curious what Microsoft's recommendation is for this. It would also be useful to note that recommendation in this documentation and/or the Virtualization Based Protection of Code Integrity documentation.

**Comment by benavidezb** [comment]
Update on this. It turns out that disabling Virtualization Based Protection of Code Integrity does not actually address the boot failure issue. That problem may be specific to Dell's Secure Boot which I am working with them on. However, having this does appear to conflict with unsigned policies. When the Microsoft Windows Driver Policy is applied it appears to remove unsigned policies on reboot.

**Comment by illfated** [comment]
Looks interesting. I wonder if Dell will have to look into whether they will be able to create signed policies by working with Microsoft to get any official Dell unsigned policies signed, to make them work as intended.

**Comment by benavidezb** [comment]
Their first line support agreed to elevate the issue. Hopefully they can clarify this. Even using the Allow All policy with the Unsigned Policy rule disabled results in a boot failure. I was thinking maybe the policy signing cert needs a chain to the Secure Boot DB but I'm not sure.

**Comment by illfated** [comment]
I applaud your efforts and hope you get some working results out of this. Whenever there are any indications that the documentation could be approved, feel free to point that out. I am not familiar enough with this topic, but there are technical writers looking into tickets like this one, in case there are documentation issues to be handled.
