### ISSUE TITLE
The options "I want more" or "Not a fan" in windows spotlight disappeared after I upgrade the win10 version

### ISSUE THREAD

**Issue by chucklu** [MicrosoftDocs/windows-itpro-docs#956]
Hi team,
     When I lock the screen, the spotlight will show an image and I can choose "I want more" or "not a fan" previously.
     However, when I upgrade the system version to 1709
      OS Name:                   Microsoft Windows 10 Pro
      OS Version:                10.0.16299 N/A Build 16299
     The options disappeared,  how could I fix this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0286c17f-aca8-c9bc-597c-86b70165c72e
* Version Independent ID: be2bdcde-8667-4ff5-c4e5-bd50696d9341
* Content: [Configure Windows Spotlight on the lock screen (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/windows-spotlight)
* Content Source: [windows/configuration/windows-spotlight.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/windows-spotlight.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by chucklu** [comment]
Hi @jdeckerms , I have tired turn off windows spotlight and restart my computer , turn on it again.
But it still keeps the same, did not show the option “more” and "not a fan".
The following picture illustrate the lock screen of my computer:
![image](https://user-images.githubusercontent.com/3004057/40527641-1b86275e-6020-11e8-8125-ece7ac79c1ad.png)

I have tried to search the feedback hub, find somebody else submit an issue already.
The difference is that the windows spotlight on my computer can change automatically,but without options to choose. 
When will you fix this bug? 
![image](https://user-images.githubusercontent.com/3004057/40528063-09ffe13a-6022-11e8-97c3-09941bf55b6c.png)

**Comment by jdeckerms** [comment]
Hi @chucklu That appears to be old feedback (before the Anniversary Update), so I recommend that you enter a new feedback issue with your details. You can also contact Microsoft Support (https://support.microsoft.com/en-us/contactus/) for assistance.
