### ISSUE TITLE
Confusion regarding AppLocker CSP support with Windows 10 Business edition

### ISSUE THREAD

**Issue by theonlycoder** [MicrosoftDocs/windows-itpro-docs#9560]
Hi,

In the matrix showing which CSPs are supported on which Windows 10 editions, the AppLocker CSP is listed as being supported on all editions of Windows 10 other than Windows 10 Business.

However, the AppLocker documentation @ https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/requirements-to-use-applocker says the following:

> _"You can use the AppLocker CSP to configure AppLocker policies on any edition of Windows 10 supported by Mobile Device Management (MDM)."_

In the same table it also makes clear that all AppLocker rule types can be configured and enforced on "Windows 10". Nowhere within the article is there any mention of any editions being excluded.

My (possibly flawed) thinking would be that because Windows 10 Business is just the edition that Windows 10 Pro changes to when enrolled into Microsoft 365, you would expect the same AppLocker functionality that is available on Pro edition to be available if the install is converted to Business edition.

It would be good to get some clarity on this in the documentation.

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162c8434-b3ab-e235-43ce-ed435d6cd06e
* Version Independent ID: 18b29b82-f1ad-81b8-2ea4-f7bebc506487
* Content: [Configuration service provider reference - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference)
* Content Source: [windows/client-management/mdm/configuration-service-provider-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/configuration-service-provider-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@theonlycoder , Thanks for pointing out, according to you windows10 for business OS is supported all CSP configuration right?

**Comment by RAJU2529** [comment]
@e0i . Will you confirm that are ALL CSP configurations are supported by windows 10 business?
If yes means, i will edit this article, i will put a tick mark under the business edition.
Conform from article writers too.

**Comment by RAJU2529** [comment]
@e0i. Just now I clearly observed the table formats in this article, I found many changes must be edited to make this visible better.

**Comment by theonlycoder** [comment]
> @theonlycoder , Thanks for pointing out, according to you windows10 for business OS is supported all CSP configuration right?

I would assume it is fully supported for the reasons I mentioned, but I am not sure - I am in the process of setting up a test at the moment. I consulted the documentation to try and get the "official" answer, but the conflicting statements mean I'm still unclear.

**Comment by theonlycoder** [comment]
> @e0i . Will you confirm that are ALL CSP configurations are supported by windows 10 business?
> If yes means, i will edit this article, i will put a tick mark under the business edition.
> Conform from article writers too.

The question regarding CSPs other than the AppLocker CSP is an interesting one. After raising this issue, I noticed the same thing you probably have - that there are quite a few CSPs that don't have anything in the Business edition column - no tick or cross.

**Comment by RAJU2529** [comment]
@e0i   For this issue #9560,   on 31st May 2021 , I created PR #9632 .
so please assign user to verify PR #9632 

https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9632

**Comment by RAJU2529** [comment]
sincere thanks to @JohanFreelancer9 for suggestions to improve this article and Thanks to @Dansimp and @ghost.

This issue #9632 is already merged. so we can close this issue.

**Comment by theonlycoder** [comment]
Thanks everyone for your efforts with this.

This is perhaps my lack of understanding regarding the review process for changes to Docs, but I haven't seen any comments confirming from a product engineering point of view that the CSPs that have been marked as supported are in fact all supported on Business edition? Just want to make sure we haven't accidentally made an assumption that may not be accurate in all cases?

**Comment by RAJU2529** [comment]
@theonlycoder . Verification will begin I think, if engineering team wants any changes to this article, after that changes will be added further in this article.

**Comment by theonlycoder** [comment]
I should add to the above that my testing of the AppLocker CSP on Business edition is so far only partially successful. Only EXE policies seem to be applying on the endpoint and not MSI/script or packaged app policies. I have also tried joining an Enterprise edition machine to the same Intune tenant with the same policies and all policy types appear to be working. This could well be a separate issue that is not related to the accuracy of the docs (particularly as the CSP is at least partially working), but having an accurate statement in the docs regarding what "should" work would be helpful. I have a support case open regarding this issue at the moment.

**Comment by theonlycoder** [comment]
> @theonlycoder . Verification will begin I think, if engineering team wants any changes to this article, after that changes will be added further in this article.

Hi @RAJU2529, thanks for coming back. You don't sound all that sure that that is definitely the process? It seems unusual that something would be publicly published first before it's reviewed for technical accuracy. Again, this could just be my ignorance of the process, but would appreciate some sort of confirmation that it has somehow been confirmed as technically accurate and we're not just assuming. What also makes me concerned that there may be a technical error is the fact that the Business edition column already existed before I raised this issue, but with empty cells in most cases. That makes me think that potentially the cells were intentionally left blank (or at least didn't have a tick) for some reason in previous versions?

**Comment by aczechowski** [comment]
We are completely refactoring the CSP documentation, automating the creation of the reference content based on information directly from the DDF and ADMX files. We'll migrate *some* of the relevant information from the existing content, but generally rely on the DDF/ADMX info as the source of truth. This process also involves automating the CSP applicability based on the details in the DDF. For example, see https://learn.microsoft.com/windows/client-management/mdm/policy-csp-defender which is already updated to the new format. Here's a snip of one of the applicability tables:
![image](https://user-images.githubusercontent.com/26784733/212386261-fe2c3dad-7e98-47fc-b928-563110f26eb1.png)
You'll notice that the Business SKU is missing from that list...that's because it's NOT identified in the DDF. We're working with the engineering team to determine a method to identify additional applicability categories in the future, but for now it's unfortunately out of scope because the data isn't there. Which is also probably why it was vague in the past. So it's a known issue that we're working on, but it actually does require engineering effort to surface the data in a way that we can consume it with our automation. I'm closing this issue.
