### ISSUE TITLE
please update to instruct when to add Edge

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/windows-itpro-docs#9569]
Which order should Edge be added?

https://www.catalog.update.microsoft.com/Search.aspx?q=edge-stable

Perhaps it is part of Features on Demand...?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7734ca5-0770-5bbd-7da5-dda4c1cf5ae0
* Version Independent ID: cb98ef23-d0c6-e62e-b72b-9b5f5d724e8e
* Content: [Update Windows 10 media with Dynamic Update - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/media-dynamic-update)
* Content Source: [windows/deployment/update/media-dynamic-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/media-dynamic-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @SteveDiAcetis
* Microsoft Alias: **jaimeo**

**Comment by VLG17** [comment]
@anwarmahmood1 According to [the list of Features on Demand](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/features-on-demand-non-language-fod), Edge is not part of it (Internet Explorer is).

**Windows 10 version 20H2** -> Edge is already installed as default browser
**Windows 10 releases RS4 through 20H1** -> see [this article](https://support.microsoft.com/en-us/topic/update-in-wsus-for-the-new-microsoft-edge-for-windows-10-version-1809-1903-1909-and-2004-october-29-2020-b4980418-4ec4-dee7-3b17-1c6499bd127c)
**Windows 10 releases prior to RS4 (and Windows 7, 8.1, and earlier)** -> Windows updates to install Microsoft Edge aren't available for these versions. Consider other options for deploying Microsoft Edge to these devices such as [Configuration Manager](https://docs.microsoft.com/en-us/configmgr/apps/deploy-use/deploy-edge?bc=https%3a%2f%2fdocs.microsoft.com%2fDeployEdge%2fbreadcrumb%2ftoc.json&toc=https%3a%2f%2fdocs.microsoft.com%2fDeployEdge%2ftoc.json) or [Intune](https://docs.microsoft.com/en-us/intune/apps/apps-windows-edge/?bc=https%3a%2f%2fdocs.microsoft.com%2fDeployEdge%2fbreadcrumb%2ftoc.json&toc=https%3a%2f%2fdocs.microsoft.com%2fDeployEdge%2ftoc.json).

**Comment by anwarmahmood1** [comment]
These are not features on demand.  Microsoft provides Edge via Microsoft Update Catalog; see
The new Microsoft Edge for Windows 10 Version 1909 for x64-based Systems (KB4584642)
https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=4bd85c12-c8f3-4929-99bf-41a6731ae270

Microsoft Edge-Stable Channel Version 92 Update for x64 based Editions (Build 92.0.902.62)
https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=d15c66d9-91fe-4880-8095-ca7e21847d6a

So, where in the sequence should these .MSU/.CAB be added?

**Comment by VLG17** [comment]
@anwarmahmood1 I know they are not, but you asked initially so I thought to answer that 

> Perhaps it is part of Features on Demand...?

In my opinion these would qualify as Optional Components (I have not tested this).

**Comment by anwarmahmood1** [comment]
Thanks VLG17.

As long as there are versions of Windows 10 that are still supported but which do not have new Edge pre-installed, the instructions ought to have tested instructions to apply new Edge offline.
________________________________

**Comment by anwarmahmood1** [comment]
Why has this issue been closed? There is still no mention of Edge on the website.
