### ISSUE TITLE
When should the 'remove adobe Flash Player' update be added?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/windows-itpro-docs#9570]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7734ca5-0770-5bbd-7da5-dda4c1cf5ae0
* Version Independent ID: cb98ef23-d0c6-e62e-b72b-9b5f5d724e8e
* Content: [Update Windows 10 media with Dynamic Update - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/media-dynamic-update)
* Content Source: [windows/deployment/update/media-dynamic-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/media-dynamic-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @SteveDiAcetis
* Microsoft Alias: **jaimeo**

**Comment by e0i** [comment]
Can you elaborate on what is not right with the documentation? The feedback is missing a description. Thanks.

**Comment by anwarmahmood1** [comment]
The article specifies the order to apply updates.

Where in this order does "remove Adobe Flash Player" go? At the beginning, with the SSU and CU? Probably not. After the .NET cumulative updates? Probably.

**Comment by SteveDiAcetis** [comment]
Thanks for the feedback. Yes, likely after cleanup and before exporting. I'm planning to make an update soon, hopefully in the next week or so .. - Steve

**Comment by e0i** [comment]
Closing based on the authors response above. Thanks for the feedback.
