### ISSUE TITLE
when should I add Defender Antivirus Antimalware updates?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/windows-itpro-docs#9571]
https://www.catalog.update.microsoft.com/Search.aspx?q=defender%20antivirus%20antimalware
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7734ca5-0770-5bbd-7da5-dda4c1cf5ae0
* Version Independent ID: cb98ef23-d0c6-e62e-b72b-9b5f5d724e8e
* Content: [Update Windows 10 media with Dynamic Update - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/media-dynamic-update)
* Content Source: [windows/deployment/update/media-dynamic-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/media-dynamic-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @SteveDiAcetis
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment]
@anwarmahmood1 .  You must add  .cab file or .msu file to operating system .wim file  via offline dism commands.
or you may add  .cab file or .msu file to the running windows 10 OS via online dism command.

DISM.exe /Online /Add-Package /PackagePath:C:\defender-dism-x64.cab

**Comment by anwarmahmood1** [comment]
no @RAJU2529  that won't work.  You must use the supplied PowerShell script to integrate Microsoft Defender updates.

I know what to do, and I know how to do it; but this page should mention it so that IT Pros can incorporate Defender.

**Comment by MaratMussabekov** [comment]
Hello @anwarmahmood1 ,
the article is about dynamic updates, adding of defender updates is out of its scope.
Thank you
