### ISSUE TITLE
Manage additional Windows Update settings

### ISSUE THREAD

**Issue by sbhesser** [MicrosoftDocs/windows-itpro-docs#9573]
Couple questions
under Configure Automatic Updates, there is an option to update other MS products. I noticed when checked, this also updates products that are not MS, like drivers for instance. Will the option Do not include drivers with Windows Updates keep this driver updating from occurring? Win 7 did not do this, I would prefer updates update the MS stuff including other MS products but not vendor specific driver software including print, network, sound, etc.
Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efb8dfd-971e-7257-f8b7-f80843989eb8
* Version Independent ID: d7808728-bb89-a06e-a103-ec1c74682f64
* Content: [Manage additional Windows Update settings (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-wu-settings)
* Content Source: [windows/deployment/update/waas-wu-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-wu-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by jaimeo** [comment]
@arcarley can you clarify? Do we need an edit here?

**Comment by RAJU2529** [comment]
@sbhesser . You can enable below policy 
Do not include driver's with windows updates.
So that windows will not update device drivers  through windows update.

I already enabled above said policy to prevent unwanted BSOD crash by incompatible driver's.

**Comment by e0i** [comment]
@sbhesser Looks like your query has been answered by the community via the response above. 

Please feel free to re-open this issue if you have a suggestion to improve the article. 

Thanks.
