### ISSUE TITLE
Seperate out intune vs Store for business

### ISSUE THREAD

**Issue by Minkus32** [MicrosoftDocs/windows-itpro-docs#9576]
[Enter feedback here]
Its really confusing in that document when you keep both the intune and store for business configuration stuff together.
Can you move the Store for Business sections in their their own document as its entirely unnecessary to try and scrool through or skip sections that din't apply to a purely intune deployment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc63299-cc1c-e031-deb7-915914b8f94e
* Version Independent ID: 356eaba5-16b0-952f-fc19-c8d5be5feb5f
* Content: [Demonstrate Autopilot deployment - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm)
* Content Source: [windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by msbemba** [comment]
@Minkus32 Thank you for your feedback. This document talks about both configurations and once the Windows store for business is deprecated in Feb 2023, it will be updated only with the intune information.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Minkus32 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
