### ISSUE TITLE
Example Policy Files and Description Not Making Sense

### ISSUE THREAD

**Issue by ivassallo19** [MicrosoftDocs/windows-itpro-docs#9577]
When testing WDAC for Windows 10 21H1 x64, I took the example policy AllowMicrosoft.xml as it states "It includes the rules from DefaultWindows and adds rules to trust apps signed by the Microsoft product root certificate." and thinking that this should do what I want.

I discovered recently that the policy DefaultWindows_Audit.xml contains these lines:

```
  <EKUs>
    <EKU ID="ID_EKU_WINDOWS" Value="010A2B0601040182370A0306" />
    <EKU ID="ID_EKU_WHQL"    Value="010A2B0601040182370A0305" />
    <EKU ID="ID_EKU_ELAM"    Value="010A2B0601040182373D0401" />
    <EKU ID="ID_EKU_HAL_EXT" Value="010a2b0601040182373d0501" />
    <EKU ID="ID_EKU_RT_EXT"  Value="010a2b0601040182370a0315" />
    <EKU ID="ID_EKU_STORE" FriendlyName="Windows Store EKU - 1.3.6.1.4.1.311.76.3.1 Windows Store" Value="010a2b0601040182374c0301" />
    <EKU ID="ID_EKU_DCODEGEN" FriendlyName="Dynamic Code Generation EKU - 1.3.6.1.4.1.311.76.5.1" Value="010A2B0601040182374C0501" />
    <EKU ID="ID_EKU_AM" FriendlyName="AntiMalware EKU -1.3.6.1.4.1.311.76.11.1 " Value="010a2b0601040182374c0b01" />
  </EKUs>
```

Whereas the policy AllowMicrosoft.xml does not, and only includes:

```
  <EKUs>
    <EKU ID="ID_EKU_STORE" FriendlyName="Windows Store EKU - 1.3.6.1.4.1.311.76.3.1 Windows Store" Value="010a2b0601040182374c0301" />
  </EKUs>
```

So by this, the statement that "It includes the rules from DefaultWindows" seems false?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b77ce817-c051-7617-7520-6f9a47845859
* Version Independent ID: 84150e0c-b9b8-9194-857c-eadd54ec7bcf
* Content: [Example Windows Defender Application Control (WDAC) base policies (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/example-wdac-base-policies)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/example-wdac-base-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/example-wdac-base-policies.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @ivassallo19 - Thank you for your feedback. Based on your feedback. Please note the information provided in the document is correct. The AllowMicrosoft.xml has the policy but the one you are referring is in DefaultWindows_Audit.xml which is not as described in the description. 
Hope this clarifies. 
Thanks.
Imran.

@e0i - FYI Please.
