### ISSUE TITLE
The steps suggested on this page don't work

### ISSUE THREAD

**Issue by mauriziomacrina** [MicrosoftDocs/windows-itpro-docs#9579]
After configuring WDAC, I'm still getting event 836 on CLSID:
cd3afa7b-b84f-48f0-9393-7edc34128127 

I followed the suggestion on this page by adding this setting to my WDAC policy:
<Setting Provider="AllHostIds" Key="AllKeys" ValueName="EnterpriseDefinedClsId">
  <Value>
    <Boolean>true</Boolean>
  </Value>
</Setting>

No luck, cd3afa7b-b84f-48f0-9393-7edc34128127 keeps getting blocked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f316427f-86b4-1b53-727b-64b49cd0e16f
* Version Independent ID: 834aaa0f-ede0-9819-e4b3-ba49217da5da
* Content: [Allow COM object registration in a WDAC policy (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @mauriziomacrina ,
could you please provide your XML file and Set-CIPolicySetting cmdlet you executed?
Thank you

**Comment by MaratMussabekov** [comment]
Hello @mauriziomacrina ,
could you please provide your XML file and Set-CIPolicySetting cmdlet you executed, so I can try to reproduce the issue?
Thank you

**Comment by e0i** [comment]
@mauriziomacrina The issue is thus being closed based on your reply. Thanks for following up.
