### ISSUE TITLE
Windows update failure

### ISSUE THREAD

**Issue by jeffreyalanpowell** [MicrosoftDocs/windows-itpro-docs#9582]
[Enter feedback here]The Windows 10 update process always fails to restart for the final step of installation. I then have to switch off and restart manually which causes my laptop to undo (attempted) changes and restore me to the pre-existing version.
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb67e518-6f60-23e0-2545-c2839e2b4159
* Version Independent ID: e9a31629-e3cb-0367-31c4-5661284d89bf
* Content: [Delivery Optimization for Windows 10 updates - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization#troubleshooting)
* Content Source: [windows/deployment/update/waas-delivery-optimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-delivery-optimization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@arcarley I think this person could use some technical help.

**Comment by RAJU2529** [comment]
@jaimeo . This @jeffreyalanpowell  person should  uninstall incompatible softwares and uninstall existing third party antivirus softwares. Also I don't know what's the exact condition of his running windows OS  
Technical person shooter analysis his computer windows os physically  So that we come to know the exact root cause of the failures

**Comment by jeffreyalanpowell** [comment]
I've now uninstalled all third party software. I get ''update & shut
down'/restart'' options', neither of which seem to result in finalised
updates or state having done so.
