### ISSUE TITLE
non-functioning links

### ISSUE THREAD

**Issue by Grimsupanoob** [MicrosoftDocs/windows-itpro-docs#9584]
The links in the below section section, are not functional and provide a 404 error.. 

Windows Insider for Business
We recently added the option to download Windows 10 Insider Preview builds using your corporate credentials in Azure Active Directory (AAD). By enrolling devices in AAD, you increase the visibility of feedback submitted by users in your organization – especially on features that support your specific business needs. For details, see Windows Insider Program for Business.

You can now register your Azure AD domains to the Windows Insider Program. For more information, see Windows Insider Program for Business.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c696c9ed-b095-68ff-d50d-df345daf8a4a
* Version Independent ID: 50ad3b26-8e9b-6a56-7b3c-56c1374c4747
* Content: [What's new in Windows 10 Enterprise LTSC 2019 - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/ltsc/whats-new-windows-10-2019)
* Content Source: [windows/whats-new/ltsc/whats-new-windows-10-2019.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/ltsc/whats-new-windows-10-2019.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@Grimsupanoob . Thanks for pointing out. I am fixing the links now,

**Comment by RAJU2529** [comment]
@e0i , Is this person @Grimsupanoob is a Microsoft employee?

**Comment by Grimsupanoob** [comment]
@RAJU2529 Yes

**Comment by RAJU2529** [comment]
@Grimsupanoob .Sorry, in your profile description Microsoft employee is not mentioned ,So that's why I asked to @e0i .

**Comment by Grimsupanoob** [comment]
> @Grimsupanoob .Sorry, in your profile description Microsoft employee is not mentioned ,So that's why I asked to @e0i .

No worries. Updated the profile

**Comment by RAJU2529** [comment]
@Grimsupanoob , I need your help with this article **https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference**

Tick mark is not properly aligned.

**Comment by illfated** [comment]
@RAJU2529 : I don't know 100% if I have found the issue, but if you mean that you were expecting to see every and all of the 96 table title columns being perfectly aligned, you are destined to be disappointed.

Please note that some of the table title rows will never align properly with some of the other tables, because the spacing is determined by the content length of the cells beneath the column titles, and that the content may be very different between some of the tables.

**Comment by RAJU2529** [comment]
@illfated . just now created PR #9632

**Comment by illfated** [comment]
Aha, OK, thank you. Now I see. You found some redundant/excessive blank cells(columns) pushing the content 1 column too far to the right. Very good. Thank you for being diligent and looking into these details.

I can only apologize for my ignorance when it comes to the CSP topic and its content values, so I will only be able to comment on the formatting (when needed).

**Comment by RAJU2529** [comment]
@illfated  For this issue #9584, so I already created PR #9585 .

**Comment by illfated** [comment]
Yes, I know. I just wanted a more visible link to the child PR based on your observations made earlier in this issue ticket. It may be useful as a reference if anyone should have questions to the origins later. I also recognize the risk that this issue ticket could accidentally get closed prematurely if the last PR gets merged before the first one.
