### ISSUE TITLE
I need to edit this article

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#9586]
According to this **https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9560**  issue, In some CSP's  business edition must be supported. in this article, few CSP's  Home and Pro editions are supported, why business editions are not supported mentioned in this article

Also  under EnterpriseDesktopAppManagement CSP ,, Cross mark is outside  .
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162c8434-b3ab-e235-43ce-ed435d6cd06e
* Version Independent ID: 18b29b82-f1ad-81b8-2ea4-f7bebc506487
* Content: [Configuration service provider reference - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference#feedback)
* Content Source: [windows/client-management/mdm/configuration-service-provider-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/configuration-service-provider-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
I am going to arrange the table format, with footnotes

**Comment by RAJU2529** [comment]
@e0i . just now created PR for this issue #9586.
Here is the PR #9632 .
and the link is  **https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9632**

**Comment by e0i** [comment]
If the PR addresses the original issue *9560*, it is not needed to create yet another issue for the PR. Thanks.
