### ISSUE TITLE
Unclear Sentence

### ISSUE THREAD

**Issue by vankraa** [MicrosoftDocs/windows-itpro-docs#9597]
[Enter feedback here]
This sentence sounds awkward to me and it difficult to understand:

This is also resilient, if the signing status of the file changes and necessary for deny rules to ensure that changing/stripping the signature doesn’t result in a different hash than what was in the policy being used by CI.

-Alex
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74ef7917-edec-5597-4689-1ffbf6735918
* Version Independent ID: 41f7ceb2-ad16-812c-3766-b9a9a72a42c1
* Content: [Understand Windows Defender Application Control (WDAC) policy rules and file rules (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create#more-information-about-filepath-rules)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Very well, thank you for the report. I am able to see the unnecessary difficulties of having such a long sentence in the first place, even though English is not my first language.

Preliminary/draft:

> This is also resilient, in case the signing status of the file changes. It is also necessary, in order to deny rules to ensure that changing or stripping of the signature does not result in creating a hash different from the one originally present in the in the policy used by CI.

Anyway, whatever a suggested phrasing may be in a Pull Request, it will be expertly reviewed during copy review.
