### ISSUE TITLE
Changing Settings with a <valuelist> attribute

### ISSUE THREAD

**Issue by toanyonebutyou** [MicrosoftDocs/windows-itpro-docs#960]
I am specifically trying to configure an Outlook 2016 GPO that only forces 3 days of synced mail. The ADMX gets ingested just fine and I can configure a piece of the setting just fine as well. 

Where the issue lies is each setting is tied to a value for 2 registry keys. One is a <value> another is a <ValueList>. I can set the value and that sets the number of Months to sync, but not days. The ability to set days is contained withing the <valueList> area which I can not seem to access in my OMA-URI. Example of XML below. (for some reason I had to replace the <,> with dashes because the XML markup would not show up on its own)

-policy name="L_CachedExchangeModeSyncSlider" class="User" displayName="$(string.L_CachedExchangeModeSyncSlider)" explainText="$(string.L_CachedExchangeModeSyncSliderExplainText)" presentation="$(presentation.L_CachedExchangeModeSyncSlider)" key="software\policies\microsoft\office\16.0\outlook\cached mode"-
      -parentCategory ref="L_CachedExchangeMode" /-
      -supportedOn ref="windows:SUPPORTED_Windows7" /-
      -elements-
        -enum id="L_SelectCachedExchangeModeSyncSettings" valueName="syncwindowsetting"-
          -item displayName="$(string.L_SyncSliderThreeDays)"-
            -value-
              -decimal value="0" /-
            -/value-
            -valueList-
              -item key="software\policies\microsoft\office\16.0\outlook\cached mode" valueName="syncwindowsettingdays"-
                -value-
                  -decimal value="3" /-  <-----------------HOW DO I SET THIS VALUE IN A OMAURI?
                -/value-
              -/item-
            -/valueList-
          -/item-

I need to be able to call the second value in my OMA-URI but I dont know how to call upon a value list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f5ed380-12c6-ad56-3f3b-1a0fe190acc9
* Version Independent ID: ecdc3e8c-21e4-0a4c-6208-67905a4e57d4
* Content: [Win32 and Desktop Bridge app policy configuration](https://docs.microsoft.com/en-us/windows/client-management/mdm/win32-and-centennial-app-policy-configuration)
* Content Source: [windows/client-management/mdm/win32-and-centennial-app-policy-configuration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/win32-and-centennial-app-policy-configuration.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by okieselbach** [comment]
Here a bit more information what we are trying to achieve. We are using ADMX backed policies with Intune:</br>
https://docs.microsoft.com/en-us/windows/client-management/mdm/understanding-admx-backed-policies</br>
we ingested the outlook admx (outlk16.admx) file and then try to configure a certain setting. The documentation has no example for valueLists.</br>
</br>
This is the OMA-URI we are using:</br>
`./User/Vendor/MSFT/Policy/Config/Outlook16~Policy~L_MicrosoftOfficeOutlook~L_ToolsAccounts~L_Exchangesettings~L_CachedExchangeMode/L_CachedExchangeModeSyncSlider`
</br>
we tried several ways to configure the setting, but we can only control the first decimal in the enum:
`<enabled/><data id="L_SelectCachedExchangeModeSyncSettings" value="0"/>`</br>
</br>
What do we need to add to set the second decimal value in the valueList as mentioned above (compare admx xml file for setting `enum id="L_SelectCachedExchangeModeSyncSettings"`)

**Comment by nickcowley** [comment]
Hello
Did you manage to get an answer to the <valueList> issue of figure it out as having a similar issue myself?

Cheers

**Comment by toanyonebutyou** [comment]
Yeah, eventually through a yammer group we found out that a value pair is not able to be set via custom policy ingestion at this time. You have to set the first value then push a powershell script to set the regkey for the second.

**Comment by nickcowley** [comment]
Thanks for the quick reply - better start writing some PowerShell then :-)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@toanyonebutyou - Thank you for submitting this feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
