### ISSUE TITLE
Windows 10 For Business Onboarding Kit - Dead Link

### ISSUE THREAD

**Issue by theznerd** [MicrosoftDocs/windows-itpro-docs#962]
The Windows 10 for Business Onboarding Kit does not appear to be available anymore. Normally I would submit a pull request to fix if I had an updated link, but I'm not sure if this is something that the Microsoft team wants to include anymore since I can't find a replacement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ddb91e1-7d83-8d67-f01f-a28c9d5b97e9
* Version Independent ID: 5532261e-d698-271c-7780-162d4131726b
* Content: [Windows 10 Enterprise FAQ for IT pros (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-enterprise-faq-itpro)
* Content Source: [windows/deployment/planning/windows-10-enterprise-faq-itpro.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-10-enterprise-faq-itpro.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by lindspea** [comment]
@theznerd thank you for reaching out and helping improve MS docs.  I'll investigate and let you know.

**Comment by mypil** [comment]
@theznerd - can you please assist to give updates on the clarification question from lindspea? Thank you.

**Comment by illfated** [comment]
Section **[User experience](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-enterprise-faq-itpro#user-experience)**
(https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-enterprise-faq-itpro#user-experience)

Chapter 2, **[How will people in my organization adjust to using Windows 10 Enterprise after upgrading from Windows 7 or Windows 8.1?](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-enterprise-faq-itpro#how-will-people-in-my-organization-adjust-to-using-windows-10-enterprise-after-upgrading-from-windows-7-or-windows-81)**
Last sentence of the paragraph: 
> To help you make the transition a seamless one, download the [Windows 10 for Business Onboarding Kit](https://blogs.technet.microsoft.com/windowsitpro/2016/06/28/windows-10-for-business-onboarding-kit/) and see our end user readiness resources.

The docs.microsoft.com link is https://blogs.technet.microsoft.com/windowsitpro/2016/06/28/windows-10-for-business-onboarding-kit/ -- but instead the page redirects to https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/bg-p/Windows10Blog (which does not list any visible means of looking up "Windows 10 For Business Onboarding Kit".

Doing a search (https://www.bing.com/search?q=Windows+10+For+Business+Onboarding+Kit&qs=n&form=QBLH&sp=-1&pq=windows+10+for+business+onboarding+kit&sc=0-38&sk=&cvid=F9690EBFE2EC4F42B3CDBB6D8F5CA616), the closest thing I could locate easily was this: 
https://info.microsoft.com/Windows-10-for-Business-Onboarding-Kit-TY.html
(I don't think that page contains enough content to solve the issue.)

**Comment by theznerd** [comment]
@illfated has what you are looking for @lindspea. Sorry I did not respond sooner!

**Comment by illfated** [comment]
Thank you for replying, at least. Have you been able to locate the Windows 10 For Business Onboarding Kit in any other way so far?

**Comment by theznerd** [comment]
Unfortunately not - but I have also not been looking very intently :)

The link you sent seems promising though.

**Comment by mypil** [comment]
@brianlic-msft - we need your insights on this issue. Do you happen to know the correct URL for the Windows 10 for Business Onboarding Kit? The URL found in the article appears to redirect to a different link -https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/bg-p/Windows10Blog.  

Please let us know what is the correct URL link for this so a PR can be created or please advise on how to proceed with this. Thank you.

**Comment by mypil** [comment]
@brianlic-msft - I would like to follow up on this. Do you have any updates?

@Justinha - do you happen to have any info about this issue? Hope you can share your insights. 

Thank you.

**Comment by mypil** [comment]
@brianlic-msft - I would like to follow up on this. Do you have any updates?
@DaniHalfin @Justinha - do you happen to have any info about this issue? Hope you can share your insights.

Thank you.

**Comment by DaniHalfin** [comment]
@greg-lindsay should be able to help out here.

**Comment by Justinha** [comment]
I think it's here now: https://info.microsoft.com/Windows10AdoptionPlanningKit.html 

see the bullet that mentions end user readiness assets

**Comment by lindspea** [comment]
@theznerd let me know if you're happy with the link provided by @Justinha and I will have it added to the document. Thanks for the help!

**Comment by mypil** [comment]
@theznerd - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
