### ISSUE TITLE
good idea but bad execution

### ISSUE THREAD

**Issue by GeNusX1** [MicrosoftDocs/windows-itpro-docs#963]
Please make this Setting to an USER Policy. A Admin needs for example all Pages in the Settings App. A normal User only a few.  	Currently is this scenario not possible. Thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eed80fd0-c052-b4d6-0282-4414c64791a4
* Version Independent ID: d055667c-9365-45a8-2a1e-8491d0067303
* Content: [Manage the Settings app with Group Policy (Windows 10)](https://docs.microsoft.com/en-us/windows/client-management/manage-settings-app-with-group-policy)
* Content Source: [windows/client-management/manage-settings-app-with-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/manage-settings-app-with-group-policy.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **dongill**

**Comment by Charrlleess** [comment]
Hi there,

Is it possible to apply this settings via GPO?
I'm searching everywhere on the web and it seems it is not available on the GPMC even after importing the ADMX files from 1607 1703 1709.

**Comment by GeNusX1** [comment]
Where is the problem? Since 1703 you have a new GPO. More Information here: https://docs.microsoft.com/en-us/windows/client-management/manage-settings-app-with-group-policy
That's all well and good, but it is only a Computer GPO and not a User. Either all Settings on or all off as well as Administrator.

**Comment by Charrlleess** [comment]
The problem is that I don’t have the option on the GPMC on my domain controllers to apply this policy globally it is available though on local group policy editor. I have already imported the ADMX files from 1703. :/

**Comment by GeNusX1** [comment]
You import the ControlPanel.admx (Filedate 2017-04-11 for 1703) and of course the ADML Files to your central store \\FQDN\SysVol\FQDN\Policies\PolicyDefinitions? Important: Don't set this regkey to 1 https://support.microsoft.com/en-us/help/2917033/an-update-is-available-to-enable-the-use-of-local-admx-files-for-group.

**Comment by Charrlleess** [comment]
It worked. I was not replacing the old ADMX files with the new ones I was just pasting the new files instead. 

Thanks a lot

**Comment by DaniHalfin** [comment]
@andreabichsel \  @shortpatti - please close. Thanks! :)
