### ISSUE TITLE
Please provide more full examples with datavalues included

### ISSUE THREAD

**Issue by torewillmar1969** [MicrosoftDocs/windows-itpro-docs#9634]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 167fe82b-002b-39a5-ffc4-e77e10e23302
* Version Independent ID: 6d416711-11b7-8231-0ced-343cbd7103f1
* Content: [SurfaceHub CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/surfacehub-csp)
* Content Source: [windows/client-management/mdm/surfacehub-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/surfacehub-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @torewillmar1969 - Thank you for posing your query here. Please note that we have covered all of the basic examples and information required for SurfaceHub CSP. If there is something specific you are looking for, I would suggest you to please contact the Microsoft Support Team.

Thanks
@e0i FYI&A Please.
