### ISSUE TITLE
Sandbox documentation missing RAIL mode

### ISSUE THREAD

**Issue by timmontague** [MicrosoftDocs/windows-itpro-docs#9637]
In the Sandbox overview video embedded in https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md it demonstrates "remote applications integrated locally" (RAIL) mode at 26:48. In RAIL mode an application running in the Sandbox is integrated with the host OS and the Sandbox desktop is not shown. The Sandbox configuration documentation does not explain how to enable that.

**Comment by illfated** [comment]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c06f3ef-5946-862a-ae14-f897fdb518ca
* Version Independent ID: cd6a8b99-b1e9-dff5-f174-a15840b304f0
* Content: [Windows Sandbox - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@e0i . I think I shuld  one point of system requirements in this article.
**Needed Compatible Virtualization enabled Processors**

**Comment by bitching** [comment]
waiting for this doc.
@VLG17 @e0i

**Comment by bitching** [comment]
@e0i writer-input-required, seriously?
common..  @timmontague stated this question very clear.
just watch [this video](https://www.microsoft.com/videoplayer/embed/RE4rFAo) at 25:00, there are two options: ```WSB file [full desktop]``` and ```WSB file [rail]``` 
```WSB file [full desktop]``` : video at 25:50-26:47
```WSB file [rail]``` : video at 26:48-27:12

[windows sandbox document](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file.md) only gave us guide to ```WSB file [full desktop]``` .
there is not a single document mentioned how to create a ```WSB file [rail]```.

**Comment by vinaypamnani-msft** [comment]
@Fei1Yang I'm following up on this, and intent to update the docs soon once I get some clarity.

**Comment by bitching** [comment]
@Fei1Yang 
I found [a clue here at page 211/212](https://www.manfredhelber.de/wp-content/uploads/Pr%C3%A4sentation-WBSC-Ignite-2019-final.pdf).
It seemd ``Rail Mode`` is an unimplemented feature when announcing, maybe the demo in the video is just a **video**.

@vinaypamnani-msft 
It's been half a month, any progress?
If ``Rail Mode`` is still in developing``(although it has been announced for 3 years)``, plz let us know.
If it has been canceled, also plz let us know.
Just say it out and we can end the meaningless waiting.

**Comment by vinaypamnani-msft** [comment]
@Fei1Yang @bitching RAIL mode was not released publicly, and as such I've removed the link to the video from the official docs to avoid confusion. The change should be live later today.
