### ISSUE TITLE
Location of Config file

### ISSUE THREAD

**Issue by BasicWombat** [MicrosoftDocs/windows-itpro-docs#9649]
Unless I'm missing it, where does the configuration file get saved?
Or where is it located to edit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2efc9d32-0f98-0804-78a4-4caccdfac010
* Version Independent ID: 797bb0d3-bade-98f6-fe85-508764571f37
* Content: [Windows Sandbox configuration - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file)
* Content Source: [windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Although I don't have personal experience using Windows Sandbox, I can offer an educated guess based on the document contents:
- https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file#using-a-configuration-file

## Using a configuration file

To use a configuration file, double-click it to start Windows Sandbox according to its settings. You can also invoke it via the command line as shown here:

```batch
C:\Temp> MyConfigFile.wsb 
```

To me, this indicates that you may place your `.wsb` wherever you like, for example in a `%TEMP%` folder.
- https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file#mapped-folders

```xml
<MappedFolders>
  <MappedFolder> 
    <HostFolder>absolute path to the host folder</HostFolder> 
    <SandboxFolder>absolute path to the sandbox folder</SandboxFolder> 
    <ReadOnly>value</ReadOnly> 
  </MappedFolder>
  <MappedFolder>  
    ...
  </MappedFolder>
</MappedFolders>
```

Although the configuration values `<HostFolder>` and `<SandboxFolder>` are specific to the Mapped Folders configuration, the text "absolute path to the" indicates to me that you will likely be required to use absolute paths for most of your own configuration needs, removing the need to place the `.wsb` file in any specific folder, leaving you free to choose where to store the `.wsb` files, depending on your usage.

Then again, I am not an expert, I have merely looked for clues based on the available documentation.

**Comment by BasicWombat** [comment]
This is my bad and I realize that now. I was expecting to be a central config file to edit instead of creating a new one then running Sandbox from it. Thanks.
