### ISSUE TITLE
Erroneous URL 

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/windows-itpro-docs#9653]
In two locations on the page, there's references to the URL https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/content-source-location-scenarios, but that redirects to https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/define-site-boundaries-and-boundary-groups, which is not relevant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cfd6413-90f7-040b-04be-9662ddfac827
* Version Independent ID: 1b931a7c-deb3-6384-0c3b-3492fd720b6f
* Content: [Best practices - deploy feature updates during maintenance windows - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/feature-update-maintenance-window)
* Content Source: [windows/deployment/update/feature-update-maintenance-window.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/feature-update-maintenance-window.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
The new link https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/fundamental-concepts-for-content-management#content-source-priority is suggested in PR #9656 (as well as some formatting updates). Does this solution seem practical to you?

**Comment by danielklenda85** [comment]
On Thursday, June 3, 2021, Baard Hermansen ***@***.***> wrote:
> In two locations on the page, there's references to the URL
https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/content-source-location-scenarios,
but that redirects to
https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/define-site-boundaries-and-boundary-groups,
which is not relevant.
>
> ________________________________
>
> Document Details
>
> ⚠ Do not edit this section. It is required for docs.microsoft.com ➟
GitHub issue linking.
>
> ID: 8cfd6413-90f7-040b-04be-9662ddfac827
> Version Independent ID: 1b931a7c-deb3-6384-0c3b-3492fd720b6f
> Content: Best practices - deploy feature updates during maintenance
windows - Windows Deployment
> Content Source:
windows/deployment/update/feature-update-maintenance-window.md
> Product: w10
> Technology: windowsSo why are you screwing in my house when I left
GitHub Login: @jaimeo

**Comment by illfated** [comment]
> The new link [docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/fundamental-concepts-for-content-management#content-source-priority](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/fundamental-concepts-for-content-management#content-source-priority) is suggested in PR #9656 (as well as some formatting updates). Does this solution seem practical to you?

@baardhermansen : I intended to point this question to you. Are you happy with the suggested change?

**Comment by baardhermansen** [comment]
@illfated Yes, that link seems correct to me.
