### ISSUE TITLE
Incompatibility with ConfigMgr's Remote Control ability

### ISSUE THREAD

**Issue by perfectly-preserved-pie** [MicrosoftDocs/windows-itpro-docs#9657]
Hi,

Enabling Windows Defender Remote Credential Guard on the ConfigMgr Site Server prevents the use of ConfigMgr's Remote Control Feature.
The Remote Control session immediately terminates with the message "Viewer disconnected."
Disabling RCG on the site server made it work again. 

Not sure if this is appropriate feedback for this article (this is my first time providing feedback) but I wanted to let someone know because it had me pulling my hair out for a while! It'd be nice to have this is a warning under the "Considerations" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c826587d-2e65-083f-254d-75f188158f08
* Version Independent ID: 746596b5-c1df-9ea0-abcc-f6ff97874e40
* Content: [Protect Remote Desktop credentials with Windows Defender Remote Credential Guard (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/remote-credential-guard)
* Content Source: [windows/security/identity-protection/remote-credential-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/remote-credential-guard.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @perfectly-preserved-pie ,
are you sure Kerberos, not NTLM, is used for Remote Control in your environment? 
Thank you
