### ISSUE TITLE
OMA-URL for CommercialID is incorrect

### ISSUE THREAD

**Issue by kistersr** [MicrosoftDocs/windows-itpro-docs#9659]
The OMA-URI: ./Vendor/MSFT/DMClient/Provider/MS DM Server/CommercialID string is incorrect. I believe the correct OMA-URI is ./Vendor/MSFT/DMClient/Provider/ProviderID/CommercialID. Can you please confirm and update the doc if necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47a41574-4118-dff7-f9ae-047b2dbdf30f
* Version Independent ID: 4f48d7a5-3965-60a4-221c-c519253bfc29
* Content: [Configuring Microsoft Endpoint Manager devices for Update Compliance - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-configuration-mem?source=docs)
* Content Source: [windows/deployment/update/update-compliance-configuration-mem.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-configuration-mem.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@chinglis can you check and advise?

**Comment by cinglis-msft** [comment]
Both work, but ProviderID is the more generally applicable OMA-URI. I have submitted a PR for this: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9661. Thank you, @kistersr

**Comment by vinaypamnani-msft** [comment]
Closing the issue, as this was addressed.
