### ISSUE TITLE
Policy Update Check

### ISSUE THREAD

**Issue by ivassallo19** [MicrosoftDocs/windows-itpro-docs#9663]
Just wanted to check on this policy:
ADMX_PowerShellExecutionPolicy/EnableScripts
It states "Available in the latest Windows 10 Insider Preview Build" and this document was last updated on 10/26/2020.
Wanted to check that this is up to date, and still not included in the current release of Windows 10 21H1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 462317b9-37a4-cb4d-e2bb-1fbe4deda4a4
* Version Independent ID: 9866e3c5-1d9e-e40f-8f3a-beffb77087d6
* Content: [Policy CSP - ADMX_PowerShellExecutionPolicy - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-admx-powershellexecutionpolicy)
* Content Source: [windows/client-management/mdm/policy-csp-admx-powershellexecutionpolicy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-admx-powershellexecutionpolicy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @ivassallo19 ,
these policies are still only in preview.
Thank you
