### ISSUE TITLE
ADMX_ Policies only supported on Enterprise SKU

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#9664]
If the whole intent of introducing CSP base policies is to get rid of legacy Group Policy why are all those CSPs locked out to enterprise SKU??? If we want to have the excact same amount of settings deployed what we had on Windows 10 PRO Domain Joined to do that on a AAD Only environement we are required to have Enteprise SKU now??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 883c3d65-cf13-9dce-cc70-f0055b2726fb
* Version Independent ID: ed01f214-ef07-38f9-e09e-418b0fc528ce
* Content: [Policy CSP - ADMX_MicrosoftDefenderAntivirus - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-admx-microsoftdefenderantivirus)
* Content Source: [windows/client-management/mdm/policy-csp-admx-microsoftdefenderantivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-admx-microsoftdefenderantivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@denisebmsft . Sir Many of the organisation deployed windows 10 professional based computers and managed to intune .
I tbink Professional edition having enabling ADMX templates . so this article  needs to be updated and tick mark must be to added to professional edition. 
Please reply your opinion. and ask to article author in this regard.

**Comment by denisebmsft** [comment]
@RAJU2529 thank you! I will look into this.

**Comment by e0i** [comment]
@denisebmsft Any updates on this? Thanks.

**Comment by denisebmsft** [comment]
Still awaiting confirmation from PMs.

**Comment by denisebmsft** [comment]
Greetings all! I have confirmed that at this time, the ADMX templates are supported for Enterprise.
