### ISSUE TITLE
Updated video?

### ISSUE THREAD

**Issue by cwidhelm** [MicrosoftDocs/windows-itpro-docs#9665]
Is there an updated video that could be put here?  The one embedded is very old: https://youtu.be/g1rIcBhhxpA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2dbf610-169d-936a-28d7-f9b8710720b3
* Version Independent ID: ded12365-1392-17d6-6f73-23bbe49ab97b
* Content: [Manage Windows 10 in your organization - transitioning to modern management - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/manage-windows-10-in-your-organization-modern-management)
* Content Source: [windows/client-management/manage-windows-10-in-your-organization-modern-management.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/manage-windows-10-in-your-organization-modern-management.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @cwidhelm Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
