### ISSUE TITLE
Are double quotation marks unnecessary?

### ISSUE THREAD

**Issue by kayuuji** [MicrosoftDocs/windows-itpro-docs#9669]
[Enter feedback here]
For a description of [Configuring Policy Using Intune](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset#configuring-policy-using-intune), We have confirmed that enclosing URLs in double quotation marks has no effect.

Value: Provide a semicolon delimited list of domains needed for authentication during the PIN reset scenario. An example value would be **"**signin.contoso.com;portal.contoso.com**"**

I thought it would be better to fix the description and capture.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9dae9da-eaf0-c209-7c65-be8d2c1ada12
* Version Independent ID: 28b6788d-7982-23c2-5f19-f80690ebc0ce
* Content: [Pin Reset - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset?source=docs#configuring-policy-using-intune)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
Hello, @kayuuji 

This issue has been addressed with the commit, https://github.com/MicrosoftDocs/windows-itpro-docs/commit/31939be3bc76a31327092f1d4b8c7831ac0356ad

The URLs are no longer in quotation marks.

Thank you for bringing this to attention and feel free to provide feedback again.
