### ISSUE TITLE
Come fronteggiare i pericoli nelle email

### ISSUE THREAD

**Issue by emanuelcelano** [MicrosoftDocs/windows-itpro-docs#9670]
ENG : We want to contribute to the protection of your readers with a very useful article on the DANGER OF EMAILS. There is also an infographic. Here are all the elements that need to be considered when receiving an email, before taking any action: https://www.analisideirischinformatici.it/sicurezza/i-principali-pericoli-nelle-email-identificarli-e-proteggersi/

ITA : Desideriamo fornire un contributo a tutela dei vostri lettori con un articolo molto utile sul PERICOLO DELLE EMAIL. Vi è anche una infografica. Ecco tutti gli elementi che occorre considerare alla ricezione di una email, prima di compiere qualsiasi azione : https://www.analisideirischinformatici.it/sicurezza/i-principali-pericoli-nelle-email-identificarli-e-proteggersi/

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 525475a3-7896-0b85-98f8-5d09d5203258
* Version Independent ID: 3d159a78-f190-0fee-d6e8-71eebd6c995e
* Content: [Tendenze e tecniche di phishing - Windows security](https://docs.microsoft.com/it-it/windows/security/threat-protection/intelligence/phishing-trends)
* Content Source: [windows/security/threat-protection/intelligence/phishing-trends.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/intelligence/phishing-trends.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@emanuelcelano This documentation repository is partly open-source. You are welcome to come up with a Pull Request to improve the content. Thank you.
