### ISSUE TITLE
PHISHING

### ISSUE THREAD

**Issue by emanuelcelano** [MicrosoftDocs/windows-itpro-docs#9671]
ENG : We want to contribute to the protection of your readers with a very useful article on the DANGER OF EMAILS. There is also an infographic. Here are all the elements that need to be considered when receiving an email, before taking any action: https://www.analisideirischinformatici.it/sicurezza/i-principali-pericoli-nelle-email-identificarli-e-proteggersi/

ITA : Desideriamo fornire un contributo a tutela dei vostri lettori con un articolo molto utile sul PERICOLO DELLE EMAIL. Vi è anche una infografica. Ecco tutti gli elementi che occorre considerare alla ricezione di una email, prima di compiere qualsiasi azione : https://www.analisideirischinformatici.it/sicurezza/i-principali-pericoli-nelle-email-identificarli-e-proteggersi/

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 08af6103-ad16-f4d5-fd46-38bf88b18423
* Version Independent ID: 872dc72c-b12c-97e0-ea1e-ab7882be12f4
* Content: [Come proteggere dagli attacchi di phishing - Windows security](https://docs.microsoft.com/it-it/windows/security/threat-protection/intelligence/phishing)
* Content Source: [windows/security/threat-protection/intelligence/phishing.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/intelligence/phishing.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Duplicate of #9670
