### ISSUE TITLE
Better document

### ISSUE THREAD

**Issue by paulaustin-automutatio** [MicrosoftDocs/windows-itpro-docs#9685]
[Enter feedback here]

Please can you improve the documentation to provide a complete example on how you are supposed to update policies? The docs should show how you go from user/group names in AzureAD to the values required in this file.

Someone else had posted this script which converts from the GUID to the numerical S-1-12-1.

```
param(
    [String] $ObjectId
)

$bytes = [Guid]::Parse("$ObjectId").ToByteArray()
$array = New-Object 'UInt32[]' 4

[Buffer]::BlockCopy($bytes, 0, $array, 0, 16)
$sid = "S-1-12-1-$array".Replace(' ', '-')
Write-Output $sid

```

This would be a lot easier if you could just use something like AzureADObjectID\[GUID] rather than having to jump through a lot of hoops and internet searches to find out what to do.

I'm getting the following error when trying to add a policy for /Vendor/MSFT/Policy/Config/LocalUsersAndGroups/Configure

Syncml(400): The requested command could not be performed because of malformed syntax in the command.

This error isn't very useful as it doesn't tell me what the error is or what part of the file has the error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b0c55a7-9aaa-d395-409e-59c2595c8e9e
* Version Independent ID: cf8e5a71-a8fc-1d43-6eed-03d3f2490693
* Content: [Policy CSP - LocalUsersAndGroups - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localusersandgroups)
* Content Source: [windows/client-management/mdm/policy-csp-localusersandgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-localusersandgroups.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by paulaustin-automutatio** [comment]
Googling shows that this might now work on Window 10 Business edition, can you confirm this?

**Comment by MaratMussabekov** [comment]
Hello @paulaustin-automutatio
**This would be a lot easier if you could just use something like AzureADObjectID[GUID] rather than having to jump through a lot of hoops and internet searches to find out what to do** - as it was mentioned in #9683, Graph API should be used to retrieve SID

**I'm getting the following error when trying to add a policy** - is it possible to provide command?
Thank you
