### ISSUE TITLE
AzureAD group member of local Administrators group on Hybrid AzureAD joined device

### ISSUE THREAD

**Issue by toxarisswe** [MicrosoftDocs/windows-itpro-docs#9689]
Hello.
If I have a Hybrid Azure AD joined device. The user that sign in to the device with a domain user that is synchronized to AzureAD. That user is member of a AzureAD group. If I then configure that AzureAD group to be a member of the local administrators group. Would then that user be able to elevate privilege to administrator?

I have this scenario setup in a lab environment, I can see that the AzureAD group SID is member of the local Administrators group, but still the user isn't able to elevate to administrator on the device.

Its not fully clarified in the documentation if this is supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b0c55a7-9aaa-d395-409e-59c2595c8e9e
* Version Independent ID: cf8e5a71-a8fc-1d43-6eed-03d3f2490693
* Content: [Policy CSP - LocalUsersAndGroups - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localusersandgroups)
* Content Source: [windows/client-management/mdm/policy-csp-localusersandgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-localusersandgroups.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Hello, @toxarisswe

Please feel free to reopen this PR by responding to the question provided by an independent contributor. Thanks.
