### ISSUE TITLE
Configure the auto-enrollment for a group of devices

### ISSUE THREAD

**Issue by gabelong** [MicrosoftDocs/windows-itpro-docs#969]
Testing this out, the option for Auto MDM enrollment with AAD token is not in the latest version of Server. Need more detail and qualification of where to apply this policy and if deviations occur between Server versions, specify. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy#configure-the-auto-enrollment-for-a-group-of-devices)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by ermacia91** [comment]
+1 on this question - wondering the same as Win Server 2016 latest update does not include it.

**Comment by jeremyhagan** [comment]
I created a central GPO store and copied in PolicyDefinitions folder from Windows 10 1709 and the option was present.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by j0rt3g4** [comment]
PR #3729

**Comment by mypil** [comment]
@gabelong - Thank you for submitting feedback.

From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
