### ISSUE TITLE
Screen shot is outdated

### ISSUE THREAD

**Issue by jandreacola** [MicrosoftDocs/windows-itpro-docs#9699]
Screenshot of Update Compliance workspace Overview shows Windows Defender.  This is not available in the solution today

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cf1e851-9449-cd9d-0f8a-af797154ca88
* Version Independent ID: 9ce3da25-2bfc-d558-1853-0d16d8f26c40
* Content: [Using Update Compliance (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-using)
* Content Source: [windows/deployment/update/update-compliance-using.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-using.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@chinglis can you update?
