### ISSUE TITLE
Remove Microsoft Classoom link. Microsoft Classroom does not exist anymore.

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/windows-itpro-docs#970]
Under "Get Minecraft: Education Edition" and then "Prerequisites" you refer to Microsoft Classroom. Please remove it.
This issue is transferred from https://github.com/MicrosoftDocs/feedback/issues/30

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fe9707f-b9ca-382f-3183-307cc95fef55
* Version Independent ID: 87247748-3614-d257-5d20-32439db6df96
* Content: [Get Minecraft Education Edition](https://docs.microsoft.com/en-us/education/windows/get-minecraft-for-education)
* Content Source: [education/windows/get-minecraft-for-education.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/get-minecraft-for-education.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **trudyha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by lindspea** [comment]
@Powerhelmsman thank you for reaching out and helping improve MS docs.  I'll investigate and have it fixed soonest.

**Comment by mypil** [comment]
@Powerhelmsman - Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
