### ISSUE TITLE
Link to the Configuration Manager Team blog at the bottom of the page not working

### ISSUE THREAD

**Issue by ybeltrikov** [MicrosoftDocs/windows-itpro-docs#9700]
The link to the Configuration Manager Team blog in the Related topics section produces 'Access denied' error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0867909f-7afe-2192-0659-27c182f90553
* Version Independent ID: 97eb09fc-39fb-9101-753e-3d9377d8284f
* Content: [Perform in-place upgrade to Windows 10 via Configuration Manager - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-cm/upgrade-to-windows-10-with-configuraton-manager)
* Content Source: [windows/deployment/deploy-windows-cm/upgrade-to-windows-10-with-configuraton-manager.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-cm/upgrade-to-windows-10-with-configuraton-manager.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Fixing link now. It will be published today.
