### ISSUE TITLE
Issue with Resetting PIN after logged in successfully

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/windows-itpro-docs#9703]
In the section https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset#reset-pin-from-settings

It states that if you are already logged in you can reset the PIN from Settings however that option doesn't seem to exist in our systems. The only options are Change or Remove. If the user has forgotten their PIN the "I Forgot my PIN" option would be useful but not present. Our systems are joined to an internal AD environment and we have Azure AD P1 but we are not using a hybrid setup yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9dae9da-eaf0-c209-7c65-be8d2c1ada12
* Version Independent ID: 28b6788d-7982-23c2-5f19-f80690ebc0ce
* Content: [Pin Reset - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset#using-pin-reset)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by VLG17** [comment]
@MarcLaf You could try to delete the contents of the NGC folder, restart and try again - as described [here](https://answers.microsoft.com/en-us/windows/forum/all/pin-sign-in-problem/2038fccf-09b8-4522-8653-a733faee0324). If that does not help, I recommend opening a support request. If it's concluded that the linked documentation is missing anything, we'll be able to add it.
