### ISSUE TITLE
HP SoftPaq Download Manager discontinued

### ISSUE THREAD

**Issue by korzynski** [MicrosoftDocs/windows-itpro-docs#9707]
Under Step 5, The section titled "For the HP EliteBook 8560w"
https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt#for-the-hp-elitebook-8560w

HP SoftPaq Download Manager is no longer available. It has been replaced by HP Image Assistant available at https://www.hp.com/us-en/ads/clientmanagement/overview.html

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@korzynski . Thanks for pointing out. I will add new link ..

**Comment by MaratMussabekov** [comment]
Hello @korzynski ,
please have a look at https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9899
Thank you
