### ISSUE TITLE
ProductType 3 WvD

### ISSUE THREAD

**Issue by RichardvanNuland** [MicrosoftDocs/windows-itpro-docs#9709]
"For server operating systems that are not domain controllers, use ProductType="3"." --> This is wrong as this also includes Windows 10 multi session.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7937ded2-6bd7-e34e-08a8-5e7f6e9ffe4c
* Version Independent ID: b4313161-be46-059c-6a6c-1af2a90252f6
* Content: [Create WMI Filters for the GPO (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/create-wmi-filters-for-the-gpo)
* Content Source: [windows/security/threat-protection/windows-firewall/create-wmi-filters-for-the-gpo.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/create-wmi-filters-for-the-gpo.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Dear @RichardvanNuland ,
please have a look at #9901
Thank you
