### ISSUE TITLE
Logon as service User right assignment query

### ISSUE THREAD

**Issue by Afsars12** [MicrosoftDocs/windows-itpro-docs#9710]
Hi Team,

I have created a local group that I want to assign to a log as a service right using group policy. I also have one global security group through which I control this right, I am adding a global group as a member of the Local group.

However, is it mandatory to add below default users with the global group to the local group as its members for log an as service right?

o	NT AUTHORITY\SERVICE
o	NT SERVICE\ALL SERVICES
o	NT AUTHORITY\LOCAL SERVICE;
o	NT AUTHORITY\NETWORK SERVICE;
o	NT AUTHORITY\SYSTEM.

Regards
Afsar 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5e80164-9c36-119e-928f-9830c3129e5b
* Version Independent ID: 6c175435-0d64-d803-6d01-4f2cdba1a6f8
* Content: [Log on as a service (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/log-on-as-a-service)
* Content Source: [windows/security/threat-protection/security-policy-settings/log-on-as-a-service.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/log-on-as-a-service.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Hello @Afsars12 

You can find the answers that you are looking for through the [Windows 10 Support Portal](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10).

Feel free to re-open this issue if there is anything specific that you would like to bring up about the documentation.

Thank you.
