### ISSUE TITLE
Script errors on page

### ISSUE THREAD

**Issue by davidguest44** [MicrosoftDocs/windows-itpro-docs#9717]
The syntax of the cscript in "Scenario #2" reads "cscript.exe c:\windows\system32\slmgr.vbs /ipk NPPR9-FWDCX-D2C8J-H872K-2YT43</pre>".  With the current version of the vbs this fails.

It should be "cscript.exe c:\windows\system32\slmgr.vbs /ipk NPPR9-FWDCX-D2C8J-H872K-2YT43"

the /pre needs to be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6443e532-640d-81c0-8215-b711bd1977d4
* Version Independent ID: fc504984-91d7-b586-04ec-4c751fb48998
* Content: [Windows 10 Subscription Activation - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation#existing-enterprise-deploymentsScript%20deployed%20which%20seems%20to%20resolve%20the%20issue)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@davidguest44 . thanks for pointing out.
