### ISSUE TITLE
What does 100% of data collection mean in the table?

### ISSUE THREAD

**Issue by Nasdebigle** [MicrosoftDocs/windows-itpro-docs#9718]
In the "Diagnostic data settings" portion of the page, you mention "Data collection" 100% for "Required (Basic)" setting.
Can you be more specific about what 100% means?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c364e-fcf4-8667-17d7-f9a3ec71e1a9
* Version Independent ID: f98f8870-d594-f5df-f6b6-44c9806db7d8
* Content: [Configure Windows diagnostic data in your organization (Windows 10) - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization)
* Content Source: [windows/privacy/configure-windows-diagnostic-data-in-your-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/configure-windows-diagnostic-data-in-your-organization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @Nasdebigle - Thank you for posting your query. Please note that 100% data collection means that all of the basic diagnostic data collected will be sent to Microsoft. So the question will be, what data is being collected in Basic. Please see https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization#required-diagnostic-data. In this portion, we have described what basic data/information is collected in the Basic category. 

Thanks
Imran.

@e0i - FYI&A Please.
