### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by mitian233** [MicrosoftDocs/windows-itpro-docs#9719]
[在此处输入反馈]
表格中的“主页”应为“Home”，此处的Home特指Windows的一个零售版本，不应翻译。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3bfdcb45-ac06-394c-6320-252f17f0eb71
* Version Independent ID: 7236e516-fe18-a336-78b4-ff42842619b8
* Content: [从 S 模式切换到 Windows 10 专业版/企业版 - Windows Deployment](https://docs.microsoft.com/zh-cn/windows/deployment/windows-10-pro-in-s-mode)
* Content Source: [windows/deployment/windows-10-pro-in-s-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-10-pro-in-s-mode.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

English translation:

(Enter feedback here)
The "home page" in the table should be "Home", where Home refers to a retail version of Windows and should not be translated.

**Comment by TinaMcN** [comment]
@mitian233 thank you for sharing the feedback.  I think this is an issue with overtranslation during the machine translation process.  I sent the article to be human translated which should fix the issue.  It should be completed in 3 days.
