### ISSUE TITLE
Invesgations page

### ISSUE THREAD

**Issue by pilcherd** [MicrosoftDocs/windows-itpro-docs#972]
=> Investigations page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dec0f3e-e970-48ed-68d5-56200c566ac7
* Version Independent ID: 89757f65-c389-c826-347a-c0a9839b3042
* Content: [Windows Defender Advanced Threat Protection Security operations dashboard](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/security-operations-dashboard-windows-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/windows-defender-atp/security-operations-dashboard-windows-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/security-operations-dashboard-windows-defender-advanced-threat-protection.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Thank you for your feedback. We'll fix the typo.
