### ISSUE TITLE
GPO for Disable Memory integrity switch???

### ISSUE THREAD

**Issue by shawnjcm** [MicrosoftDocs/windows-itpro-docs#9726]
The GPO instructions for Disable Memory Integrity Switch found at https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-security-center/wdsc-device-security#disable-memory-integrity-switch does not seem to exist in Group Policy Management. 

Is there perhaps some other ADMX template required? I am unable to find anything supporting this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1311b0a-9022-b1db-ddd5-d5c57a4fde22
* Version Independent ID: e0dcb960-8145-2590-de7a-3a75118c3c5f
* Content: [Device security in the Windows Security app - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-security-center/wdsc-device-security#disable-memory-integrity-switch)
* Content Source: [windows/security/threat-protection/windows-defender-security-center/wdsc-device-security.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-security-center/wdsc-device-security.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@shawnjcm  yes you are correct. Disabling memory integrity is a part of hypervisor code integrity .

**Comment by shawnjcm** [comment]
> @shawnjcm yes you are correct. Disabling memory integrity is a part of hypervisor code integrity .

Yep understand that but not quite what I was enquiring about. I was enquiring about not being able to find it in GPO Management and if it requires additional ADMX templates...
