### ISSUE TITLE
Windows 11 requirements mismatch regarding TPM 1.2 vs TPM 2.0

### ISSUE THREAD

**Issue by sundhaug92** [MicrosoftDocs/windows-itpro-docs#9727]
This page says 2.0, https://docs.microsoft.com/en-us/windows/compatibility/windows-11/ mentions this as a soft floor with 1.2 being the hard floor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db554047-b9ca-f5c9-d79f-4a70686a66db
* Version Independent ID: e05bf4bc-ab29-9d32-bd53-5ca3e70aba1b
* Content: [Windows 11 requirements - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/windows-11-requirements)
* Content Source: [windows/whats-new/windows-11-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/windows-11-requirements.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@sundhaug92 

Both pages now show TPM 2.0 as a requirement.

Thank you for the feedback.
