### ISSUE TITLE
Set AllowDeviceNameInTelemetry with Intune

### ISSUE THREAD

**Issue by win2000b** [MicrosoftDocs/windows-itpro-docs#973]
Is there a way other that PowerShell to set the value for AllowDeviceNameInTelemetry to enabled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4273a259-c3c7-dca7-6353-954068d740a7
* Version Independent ID: 1084ea77-95c4-4e4a-da6c-f4d8668f9ebf
* Content: [Enrolling devices in Windows Analytics (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started)
* Content Source: [windows/deployment/update/windows-analytics-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-get-started.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by Dlogsdon-cwps** [comment]
Sorry, I am having trouble setting AllowDeviceNameInTelemetry.
First, I don't see it in the DMClient CSP, and second what are the values?
I am guessing "Integer" and 1 for yes.
Any help would be appreciated.
Thanks

**Comment by win2000b** [comment]
In the end I had to set it via a powershell script

$registryPath = "HKLM:\Software\Policies\Microsoft\Windows\DataCollection"
$Name = "AllowDeviceNameInTelemetry"
$value = "1"
New-ItemProperty -Path $registryPath -Name $name -Value $value `
    -PropertyType DWORD -Force | Out-Null

**Comment by cconrado** [comment]
@andreabichsel It's true that in DMClient the "Allow Device Name" setting isn't listed. It's also not in the graph that shows what was added in 1803. Can this get added?

**Comment by mtwelve** [comment]
Why is this closed?

There is no documentation on how to configure this using the DM Client CSP as per the other settings and so the original issue is still open.

 https://docs.microsoft.com/en-gb/windows/client-management/mdm/dmclient-csp

**Comment by PanuSaukko** [comment]
It seems that you need to have Win10 1809 to set "Allow Device Name" via MDM channel. Please update the documentation. https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-system#system-allowdevicenameindiagnosticdata

**Comment by hkusulja** [comment]
So, can you give example how to turn on this feature via Intune / CSP policy?

System/AllowDeviceNameInDiagnosticData

Tx
