### ISSUE TITLE
If the device does not have a firmware embedded activation key.

### ISSUE THREAD

**Issue by npiasecki** [MicrosoftDocs/windows-itpro-docs#9732]
If the device does not have a firmware embedded activation key, what do you do? Contribute to the destruction of the Earth by throwing away perfectly functional computers?

**Comment by RAJU2529** [comment]
so in this case, you need to  buy another product key or activation key

**Comment by npiasecki** [comment]
It turns out that for Windows 10 Enterprise Subscription Activation,the firmware embedded key is only needed for new deployments. My problem was an existing machine with a valid Windows 10 Pro license that was Azure AD Hybrid Joined to a Microsoft 365 E5 subscription. This machine would not upgrade to Enterprise while others would, so o assumed it was related to the lack of an embedded key as it was a machine I built myself. Instead, the issue seemed to be that I had also connected the machine to a different "work or school" account that does not have enterprise rights because I have two jobs. As soon as I disconnected the second work account and rebooted it activated to Enterprise. So the takeaway is Subscription Activation doesn't work if you have two jobs, if you want Enterprise you need to disconnect the account that doesn't have it.

**Comment by RAJU2529** [comment]
Sorry I am expert of Azure , so wait for few days to get proper response from Azure experts

**Comment by denisebmsft** [comment]
@npiasecki, can you please tell us to which article(s) your feedback applies?

**Comment by npiasecki** [comment]
Sorry I was on mobile and I guess it stripped all of the linking stuff. The article was https://docs.microsoft.com/en-us/windows/deployment/deploy-enterprise-licenses ... there is overlap with https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation ... I guess my scenario of having two work accounts might be unusual but it definitely would have been helpful if it was clearer than the firmware embedded key bit is only necessary if you're signing into windows on a newly-imaged machine. The whole process of Subscription Activation is difficult to debug because there's surprisingly little information on it in the Event Viewer.

**Comment by Tom11880** [comment]
Hi Nicholas,

pardon me for hijacking this thread, but I'm currently working on a C# project that involves a QR-code scanner which emulates a keyboard.

So after some search I came across this old article from 2009/2010 on your blog: http://nicholas.piasecki.name/blog/2009/02/distinguishing-barcode-scanners-from-the-keyboard-in-winforms

Is there any chance that you still have the source of the project and would you be able to share it with me?

Thanks & regards
Thomas

**Comment by frankroj** [comment]
Thanks @npiasecki  for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
