### ISSUE TITLE
Minimum system requirements for windows 11 fulfilled and yet I receive the error

### ISSUE THREAD

**Issue by treasuregem** [MicrosoftDocs/windows-itpro-docs#9733]
I tested if my laptop will support windows 11 or not using the application provided (PC health at a glance) and it gave me an error that My system can not run windows 11. I guess my system requirements are fulfilled with reference to the minimum system requirements given on the windows 11 website page. 

I have the following spect of my laptop:
1. Processor :	Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, 2592 Mhz, 4 Core(s), 8 Logical Processor(s)
2. Installed Physical Memory (RAM): 	12.0 GB
3. Storage: 250 GB SSD
4. TPM: Ready to Use, Specification version 2.0 (from TPM.msc)
             TpmPresent                : True (from get-tpm)
             TpmReady                  : True
             TpmEnabled                : True
             TpmActivated              : True
             TpmOwned                  : True
             RestartPending            : Trus
             ManufacturerIdTxt         : INTC
             ManufacturerVersion       : 302.12.0.0
             ManufacturerVersionFull20 : 302.12.0.0
5.  BIOS Mode:	UEFI
6.  Secure Boot State:	On
7. Display Devices:  Card Name:    Intel(R) HD Graphics 530
                               Driver Model: WDDM 2.1
                               Card name: NVIDIA GeForce GTX 950M
                               Driver Model: WDDM 2.7
8. Display: 1920 x 1080 (Recommended)
9. Microsoft account and internet: Yes (using Windows 10 , Version: 21H1 OS Build 19043.1081 using winver, Pre-installed)
10. DirectX: DirectX 12 (from dxdiag)

 I don't understand what my system is lacking.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db554047-b9ca-f5c9-d79f-4a70686a66db
* Version Independent ID: e05bf4bc-ab29-9d32-bd53-5ca3e70aba1b
* Content: [Windows 11 requirements - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/windows-11-requirements)
* Content Source: [windows/whats-new/windows-11-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/windows-11-requirements.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@treasuregem reason is simple  , cjecking application has been developed based latest intel processors starting from 8th generation onwards.
**https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors**

**Comment by treasuregem** [comment]
Well thanks for the clarification. They should have mentioned this in the list of minimum requirements of processor.

**Comment by WozSoftware** [comment]
The 9th gen HEDT and Threadripper are also missing from the supported CPU list. 

What I am trying to get to the bottom of is what change was made between 7th and 8th gen CPUs and or Mobos that mean 7th gen become e-waste in the middle of a huge silicon fab capacity shortage. I could find nothing walking through Intel ARK to explain the restruction

**Comment by RAJU2529** [comment]
I think the supported cpu list might be updated very soon, also currently cpu list is for  OEM  vendors to pre-installed windows 11. 
Also, few processor laptops do not come with windows 10 preinstalled.

**Comment by Fiery-WA** [comment]
Bloody Microflacid  are liars!! 

They keep adding new features and so the complexity of the OS slowly grows. At some point, it wilp outgrow the currently set minimal hardware requirements (which haven’t changed since Windows 7 came out, by the way). What will they do then? What will happen to old PCs that were running Windows 10 until now and are still in perfect working condition, but can’t be updated because they don’t meet the new hardware requirements? Will Microsoft forcefully try to upgrade them, which would prevent them from working? Will they deactivate the license?

Microsoft hasn’t provided a clear answer to that yet.

**Comment by mahdiameri** [comment]
Hello. I would love to have Windows 11 installed on my computer.
Unfortunately it does not allow. Help me please .
 #9739  #RAJU2529  #denisebmsft

**Comment by mahdiameri** [comment]
Hello again . I download Windows 11. Unfortunately permission. Does not install. Windows installed on the computer. Windows 10 Enterprise is installed. How to send a photo thanks.
#9739

**Comment by mahdiameri** [comment]
Hello again . I download Windows 11. Unfortunately permission. Does not install. Windows installed on the computer. Windows 10 Enterprise is installed. How to send a photo thanks. #9739 
![Win 11 No 1](https://user-images.githubusercontent.com/22918975/123797593-97329e80-d8fb-11eb-8602-a57e4edd35cf.jpg)

**Comment by mahdiameri** [comment]
![Win 11 Yes 1](https://user-images.githubusercontent.com/22918975/123798284-45d6df00-d8fc-11eb-98f8-355aa865986f.jpg)
![Win 11 Yes 3](https://user-images.githubusercontent.com/22918975/123798287-47080c00-d8fc-11eb-9932-2998c6565663.jpg)
![Win 11 Yes 4](https://user-images.githubusercontent.com/22918975/123798289-47a0a280-d8fc-11eb-8b30-8cf3df60fb74.jpg)
![Win 11 Yes 5](https://user-images.githubusercontent.com/22918975/123798293-48d1cf80-d8fc-11eb-9f45-446d30cbe6c3.jpg)
In the event that . Windows allows. Install via Windows boot.
please guide me . What should. To do. Can I use powerful Windows 11? Thanks . From you and all your good colleagues. #9745  #9749 #9751 #9739

**Comment by WozSoftware** [comment]
Just read article. Looks like 8th gen is rock hard limit. Looks like it is about virtualization services in the cpu generations. So my ryzen is good. My xeon box no :(

**Comment by mahdiameri** [comment]
![WindowsPCHere ptur](https://user-images.githubusercontent.com/22918975/123801572-a7e51380-d8ff-11eb-8b4f-9886c4154cf2.PNG)
#9745

**Comment by mahdiameri** [comment]
![WindowsPCd](https://user-images.githubusercontent.com/22918975/123802446-8e909700-d900-11eb-824c-63762cfbb18a.PNG)
#9752

**Comment by RAJU2529** [comment]
@mahdiameri . Conform do your pc have TPM 2.0 and it's enabled in bios. Also UEFI mode is enabled and secure boot is enabled in bios. Currently running windows 10 os is  Booted with secure boot and tpm is enabled and active.
Don't send screenshots here.
post your problem's below site.

https://answers.microsoft.com/en-us/windows/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1

**Comment by RAJU2529** [comment]
@WozSoftware . Yesterday night I successfully installed windows 11 insider preview on intel i5   7200U processor based laptop..

**Comment by mahdiameri** [comment]
Last Windows 11 insider preview allow to Failed install.
Processor.   Pentium  (R) Dual-Core E5700 @ 3.00GHz 3.00 GHz  Installed.
 4.00 GB RAM
System.   type 64-bit operating system, x64-based processor
install. Failed of Computer
I Failed installed windows 11 insider preview

‫‪VARADHARAJAN K‬‏ ***@***.***‬‏> در تاریخ سه‌شنبه ۲۹ ژوئن
۲۰۲۱ ساعت ۱۸:۲۵ نوشت:‬

**Comment by mahdiameri** [comment]
install. Failed of Boot USB Computer
I Failed installed windows 11 insider preview



‫‪mahdiameri‬‏ ***@***.***‬‏> در تاریخ چهارشنبه ۳۰ ژوئن ۲۰۲۱
ساعت ۱۰:۵۸ نوشت:‬

**Comment by mahdiameri** [comment]
Last Windows 11 insider preview allow to Failed install. 
Processor.   Pentium  (R) Dual-Core E5700 @ 3.00GHz 3.00 GHz  Installed.   4.00 GB RAM  
System.   type 64-bit operating system, x64-based processor 
install. Failed of Computer 
I Failed installed windows 11 insider preview
install. Failed of Boot USB Computer
I Failed installed windows 11 insider preview @RAJU2529 @e0i @WozSoftware  @denisebmsft 
![W11 1](https://user-images.githubusercontent.com/22918975/123916343-c9dda500-d996-11eb-9ca1-a6feeb9f70b2.jpg)
![W11 2](https://user-images.githubusercontent.com/22918975/123916360-ce09c280-d996-11eb-97f9-5b82c017a9e0.jpg)

**Comment by treasuregem** [comment]
On WIndows 11 website the Compatibility check software (PC Health Check
app) is getting updated I guess. I see "Coming Soon" instead of download.
May be they are updating the supported hardware.
[image: image.png]

**Comment by RAJU2529** [comment]
@treasuregem . Yes you are correct. That application has been from 28th June I think.
Application developer working on more fixes in based on processors compatibility.

**Comment by treasuregem** [comment]
I just updated my windows 10 to windows 11 from Windows Insider Program
(under windows update). It still showed me that my system does not meet
minimum requirements for windows 11, but I still continue as I know that my
system meets provided windows 11 minimum requirements. The process was:
1. Under Update and security click Windows Insider Program (last option)
2. Clicked Get started
3. Linked my Microsoft login Account
4. Three options appeared. I selected Dev Channel (I do not recommend this
since it might have bugs). Better select Beta Channel which is recommended
(but i have not tried this).
5. Then System restarts.
6. After restarting go back to Update and security settings and check for
new updates.
It will show new updates which will have Windows 11. I don't know If I will
face any problem in future since I just updated to Windos 11.

This is my Device Spec screenshot:
[image: image.png]

**Comment by mahdiameri** [comment]
Thank you! Thanks to the developer, able, always, success.
Your developers did a great job. Only the best Windows in the world.
Thank you very much and all the colleagues.
I would like Windows 11 to be installed on my computer. I tried all the
methods.
Through the boot. By USB. Via Windows Update. Unfortunately I did not
succeed.
please guide me. I can use the great features of Windows 11.
Thanks again for your sincere cooperation.
Have a good #9395 #9743 #9744 #9766 #9770
W11 B 2



‫‪treasuregem‬‏ ***@***.***‬‏> در تاریخ جمعه ۲ ژوئیهٔ ۲۰۲۱
ساعت ۱۰:۲۶ نوشت:‬

**Comment by treasuregem** [comment]
@mahdiameri The only way i see to upgrade to windows 11 is through insider program. Follow the steps i mentions in earlier message, to upgrade to windows 11 through insider program. The other important thing, i guess, is that your system should be already running a genuine Windows 10 and should be updated to its latest build. And then upgrade to windows 11 via dev channel (or anyother channel if possible) of insider program.
