### ISSUE TITLE
Unable to access the system after "Bypass Traverse Checking" right was revoked from Everyone and Users

### ISSUE THREAD

**Issue by gexgd0419** [MicrosoftDocs/windows-itpro-docs#9737]
> Organizations that are extremely concerned about security may want to remove the Everyone group, and perhaps the Users group, from the list of groups that have the Bypass traverse checking user right.

I removed these two groups, and now I am denied access to the **logon screen**, on a newly-installed Windows 10 system. It just showed me a black or frozen screen. Rebooting into safe mode cannot solve this issue.

It turns out that UWP apps (including some system components such as LockApp.exe) cannot work with Bypass traverse checking right revoked, (possibly) because the root directories of the file system and the NT object manager grant app packages no access, failing all traverse checks. For example, "C:\\Windows" grants "ALL APPLICATION PACKAGES" read and execute permission, but the root directory "C:\\" grants app packages no access, so traverse checking will fail and "C:\\Windows" will not be accessible. In the NT object manager, the parent directory of "\\Sessions\\X\\AppContainerNamedObjects" also grants app packages no access.

This document doesn't tell me that removing these two groups will leave the system in an unusable state, though.

(admin edit, refreshing doc details with latest)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bdf00c57-677f-fd79-f516-2937e0c3e894
* Version Independent ID: f3dd08b3-bc0e-03ac-c429-fb8f34d6e760
* Content: [Bypass traverse checking (Windows 10)](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/bypass-traverse-checking)
* Content Source: [windows/security/threat-protection/security-policy-settings/bypass-traverse-checking.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/bypass-traverse-checking.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by msbemba** [comment]
@gexgd0419 Thank you for your feedback. Sorry about the delay. I was able to get back in after removing the two groups in windows 10 21H2. If this continues to be a problem, I'd recommend contacting Microsoft support.

Hope this helps!

Thanks
Sri

**Comment by gexgd0419** [comment]
I tested it again in a virtual machine with Windows 10 Pro 22H2 64-bit and all its latest updates installed.

- <kbd>Win</kbd>+<kbd>R</kbd>, then enter `secpol.msc`.
- Go to Local Policies > User Rights Assignment, remove Everyone and Users from Bypass traverse checking, click OK.
- Log off current user.

You won't see the logon screen after logging off. It just shows a black screen, and you can't do anything. Rebooting does not help, either. (That's why I used a virtual machine to test this)

You can connect to it via RDP (so the system is actually running), but still, all you can see is a black screen.

I used a Windows 10 21H2 ISO file created by Microsoft's media creation tool to install the system in the virtual machine, then used Windows Update to update it to 22H2, with no third-party software installed.

**Comment by msbemba** [comment]
@gexgd0419 Thank you for your feedback. I will pass this information to the author to verify if things have changed. I'll update you shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
Email sent to author.

**Comment by msbemba** [comment]
@gexgd0419 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11446

Once the author approves, the changes will be live.

CC : @vinaypamnani-msft 

Thanks
Sri
