### ISSUE TITLE
Response

### ISSUE THREAD

**Issue by gregghanpeter** [MicrosoftDocs/windows-itpro-docs#9738]
[Enter feedback here] Windows says my PC doesn't meet the requirements. MY PC is only 4 months old and I can't afford to build a new gaming rig that's faster than the one I have. I see millions of new PC purchases when 11 is released.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89477b73-196f-567b-1b5f-37cafb4d004e
* Version Independent ID: e707dec5-83ae-9953-d6a5-bede20f19c77
* Content: [Plan for Windows 11 - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/windows-11-plan)
* Content Source: [windows/whats-new/windows-11-plan.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/windows-11-plan.md)
* Product: **w11**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@gregghanpeter . Which processor is installed in your PC   and model number of processor too.

**Comment by gregghanpeter** [comment]
AMD 3800X

**Comment by RAJU2529** [comment]
@gregghanpeter , as per microsoft site   AMD ryzen 7 3800X is compatible
Also Microsoft clearly stated only listed processors is for OEM vendors to add pre-installed windows 11.
So that end users might get windows 11 on not listed processors might get upgraded

**Comment by gregghanpeter** [comment]
Thanks for the information!
