### ISSUE TITLE
Windows 11 

### ISSUE THREAD

**Issue by mahdiameri** [MicrosoftDocs/windows-itpro-docs#9739]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 272c8c94-dd81-589c-2938-456de9d6edad
* Version Independent ID: e7dd144a-e07a-a900-d904-8488c34aeaa6
* Content: [Windows 11 overview - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/windows-11)
* Content Source: [windows/whats-new/windows-11.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/windows-11.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mahdiameri** [comment]
https://play.google.com/store/apps/details?id=com.pairetepaidvpn.freevpnproxy.vpn

‫‪mahdiameri‬‏ ***@***.***‬‏> در تاریخ دوشنبه ۲۸ ژوئن ۲۰۲۱
ساعت ۰:۰۶ نوشت:‬

**Comment by RAJU2529** [comment]
@e0i . there is no proper issue from @mahdiameri  so close this issue #9739.

**Comment by mahdiameri** [comment]
Hello. Cool, thanks! 
Thanks to the programmer, able, Always, succeed and win. 
The support I found to be excellent with a very fast response time. 
The best Powerful of sites. Only https://docs.microsoft.com/en-us/windows/whats-new/windows-11/
And https://github.com/ 
This tool is great and I love it  This is the app for more than 5 stars.  have a nice day

**Comment by mahdiameri** [comment]
Hello. I would love to have Windows 11 installed on my computer.
Unfortunately it does not allow. Help me please .

**Comment by RAJU2529** [comment]
I am using windows 11 insider preview build. .
you should post your problem's in answers.microsoft.com website
