### ISSUE TITLE
Fix a word

### ISSUE THREAD

**Issue by CupertinoDude** [MicrosoftDocs/windows-itpro-docs#9740]
The word block in this sentence must be black instead: "a list of known 'bad' SRTM measurements (also known as a black list),"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50c07fb5-e000-a334-45a9-844e596d9080
* Version Independent ID: facb9dad-ba91-7d1f-5296-9289667fa7e3
* Content: [How a Windows Defender System Guard helps protect Windows 10 - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-system-guard/how-hardware-based-root-of-trust-helps-protect-windows)
* Content Source: [windows/security/threat-protection/windows-defender-system-guard/how-hardware-based-root-of-trust-helps-protect-windows.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-system-guard/how-hardware-based-root-of-trust-helps-protect-windows.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Hello @CupertinoDude, and thank you for posting your question here. We actually mean a block list. The article is correct.

**Comment by CupertinoDude** [comment]
Though you did not mention that, but I deeply apologize for missing the cultural aspect of the naming. I am glad the industry is shifting away from using colors to label functional attributes.
