### ISSUE TITLE
Confusing/incorrect information

### ISSUE THREAD

**Issue by Rvvhub** [MicrosoftDocs/windows-itpro-docs#9742]
This page has 2 paragraphs starting with "If the Audit Kernel Object setting is configured, the following events are generated:"

Only 1 can be correct, but which?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a1381d8-6a56-c404-79bb-8625655c7b59
* Version Independent ID: edd888c9-893d-04f0-8d38-f575d3953f4b
* Content: [Audit Audit the access of global system objects (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/audit-audit-the-access-of-global-system-objects)
* Content Source: [windows/security/threat-protection/security-policy-settings/audit-audit-the-access-of-global-system-objects.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/audit-audit-the-access-of-global-system-objects.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@Rvvhub . Thanks for pointing out. i am correcting now
