### ISSUE TITLE
TPM v1.2 become a big issue now for many

### ISSUE THREAD

**Issue by MaHmoud2285** [MicrosoftDocs/windows-itpro-docs#9746]
[Enter feedback here]
Hi, I have HP PC z240 and i have all the windows 11 requirements except the TPM version
i have TPM v1.2 like everyone suffering to have windows 11 because of the TPM v2.0
i do need help to have the TPM v2.0
so i can use windows 11

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a149789-67c1-e126-129b-6e77e831086d
* Version Independent ID: dd04d845-c098-46e5-fedf-92ba8fc64615
* Content: [Trusted Platform Module Technology Overview (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/trusted-platform-module-overview)
* Content Source: [windows/security/information-protection/tpm/trusted-platform-module-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/tpm/trusted-platform-module-overview.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by Eliezerure** [comment]
Hello, the same thing happens to me. I have all the requirements to install windows 11. I have HP Elitebook 8570w with TPM V1.2 technology and I need v2.0. Can you help me?

**Comment by e0i** [comment]
Hello,

This feedback can best be processed via the [Feedback Hub app](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub).

This repository contains product documentation.

Thank you.
