### ISSUE TITLE
Needs updating

### ISSUE THREAD

**Issue by guymerdm** [MicrosoftDocs/windows-itpro-docs#9749]
[Enter feedback here]
It is clearly well beh8ind the times.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a149789-67c1-e126-129b-6e77e831086d
* Version Independent ID: dd04d845-c098-46e5-fedf-92ba8fc64615
* Content: [Trusted Platform Module Technology Overview (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/trusted-platform-module-overview)
* Content Source: [windows/security/information-protection/tpm/trusted-platform-module-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/tpm/trusted-platform-module-overview.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@guymerdm Please suggest your feedback to improve the documentation. Thanks

**Comment by msbemba** [comment]
@guymerdm Thank you for your feedback. We are extremely sorry about the delay in getting back to you. Looks like there have been multiple updates and reviews done on the document in the past 2 years and it is up to date.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @guymerdm Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
