### ISSUE TITLE
Typo "can ot"

### ISSUE THREAD

**Issue by catawalks** [MicrosoftDocs/windows-itpro-docs#9750]
There is a typo at the end of the documentation for Bitlocker Network Unlock. It should read "can not" but instead reads "can ot".

"recovery key to unlock the computer if it **can ot** be connected to the network."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6af3b9fa-46d2-0696-7c81-78c54b910e0f
* Version Independent ID: 446e417c-6630-9673-dfa6-757511acde0c
* Content: [BitLocker Network Unlock FAQ (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-network-unlock-faq)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-network-unlock-faq.yml](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-network-unlock-faq.yml)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@e0i, This issue #9750  can be closed safely now  . This issue has been solved
