### ISSUE TITLE
Allow Update Compliance processing Value

### ISSUE THREAD

**Issue by erottier** [MicrosoftDocs/windows-itpro-docs#9751]
Hi,

I followed these instructions, to enable "Allow Update Compliance processing" via Intune configuration profile.

I've included this in my profile:
"OMA-URI: ./Vendor/MSFT/Policy/Config/System/AllowUpdateComplianceProcessing
Data type: Integer
Value: 16"

What I found was that with this code the hex code is 10 and the decimal is 16. According to other website it should be hex 16 and dec. 22.

Regards.

(for example: https://www.thewindowsclub.com/enable-update-compliance-processing)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47a41574-4118-dff7-f9ae-047b2dbdf30f
* Version Independent ID: 4f48d7a5-3965-60a4-221c-c519253bfc29
* Content: [Configuring Microsoft Endpoint Manager devices for Update Compliance - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-configuration-mem)
* Content Source: [windows/deployment/update/update-compliance-configuration-mem.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-configuration-mem.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@cinglis-msft can you advise?

**Comment by erottier** [comment]
> @cinglis-msft can you advise?

I seem to have to set the value to 22.
I advise more testing by others then me to be sure. Also, the updates I make take 48 hours to come through in Log Analytics, so every error I make are visible after 2 full days.

This means it sets the decimal to 22, but the hexadecimal to the wanted 16.

**Comment by RAJU2529** [comment]
@erottier Just now i enabled that policy using group policy  editor,  16 is correct for  decimal, and10  is for hexadecimal 
here is the proof
![Capture](https://user-images.githubusercontent.com/3296790/123931835-82fba980-d9ae-11eb-83f0-44be75b1a98f.JPG)

**Comment by erottier** [comment]
I'm starting to wonder if both values are 'correct'. Since 22 decimal is higher then 16 decimal, maybe the system interprets both as valid?

As you can see, my values are working fine as well although they are different.
![aucp](https://user-images.githubusercontent.com/25172811/124081511-eee01f80-da4b-11eb-9aee-df0b4a6370f9.png)

I am in agreement that the GPO values are probably the right ones.
As stated before, I had waited a little over the 24 hours the panel in Azure told me. I got nothing. After 48 hours data showed up, so my initial conclusion may be skewed.

**Comment by cinglis-msft** [comment]
16 decimal is what is required. This policy value actually goes into a bitmap on the backend. It does not _yet_ affect data flow to Update Compliance. It was added a requirement pre-emptively so that folks have enough time to activate the policy before it is actually required for data to flow. Thus, that is why all values still technically "work"... It is essentially unused right now.

**Comment by erottier** [comment]
> 16 decimal is what is required. This policy value actually goes into a bitmap on the backend. It does not _yet_ affect data flow to Update Compliance. It was added a requirement pre-emptively so that folks have enough time to activate the policy before it is actually required for data to flow. Thus, that is why all values still technically "work"... It is essentially unused right now.

Thanks! That explains a LOT.

The only thing which _could_ be done is maybe clarify the doc that 16 is decimal? (for people using regedit) Or should it be clear enough since Intune (and the GPO) pushes decimals anyway?
