### ISSUE TITLE
wrong anchor text link

### ISSUE THREAD

**Issue by cat-engine** [MicrosoftDocs/windows-itpro-docs#9753]
I think the anchor text link for "Keeping Windows 11 up-to-date" is wrong. It should be https://www.microsoft.com/en-us/windows/windows-11-specifications#primaryR3 instead of https://www.microsoft.com/windows/windows-10-specifications#primaryR5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db554047-b9ca-f5c9-d79f-4a70686a66db
* Version Independent ID: e05bf4bc-ab29-9d32-bd53-5ca3e70aba1b
* Content: [Windows 11 requirements - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/windows-11-requirements)
* Content Source: [windows/whats-new/windows-11-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/windows-11-requirements.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@cat-engine . For this issue, I already created PR #9748

**Comment by RAJU2529** [comment]
@e0i . So please look in this PR #9721 to merge

**Comment by cat-engine** [comment]
> @cat-engine . For this issue, I already created PR #9721

Got it and have seen the link is corrected.

**Comment by RAJU2529** [comment]
@cat-engine . This issue is solved. so please close this issue from your side.
