### ISSUE TITLE
The page does not say what 'S-mode' is actually *for*

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [MicrosoftDocs/windows-itpro-docs#9765]
Moreover, I gather that, for some reason, Windows 11 will restrict the availability of this 'mode'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 693c3223-df7f-9fbb-ce68-d3fb1ec04d53
* Version Independent ID: 2e2a1281-750a-63f6-f412-c466f44d03c9
* Content: [Windows 10 Pro in S mode - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/s-mode)
* Content Source: [windows/deployment/s-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/s-mode.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@LinuxOnTheDesktop , I think S-mode means **Security mode**

**Comment by e0i** [comment]
Hello, @LinuxOnTheDesktop

It seems that the function of what S-mode can already be inferred from the context of the article. Further, there is a statement in the [Deployment](https://docs.microsoft.com/en-us/windows/deployment/s-mode#deployment) section that explains what the S-mode is for.

Thank you for your feedback.
