### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by Rvvhub** [MicrosoftDocs/windows-itpro-docs#9766]
Minor typo: 

"To limit the number of changed domain credentials "

should be:

"To limit the number of cached domain credentials "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3ded1fc-7605-b135-d643-fdc2f40fbb0c
* Version Independent ID: 3e5a97a6-4557-19a1-9980-fbc602251573
* Content: [Network access Do not allow storage of passwords and credentials for network authentication (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-do-not-allow-storage-of-passwords-and-credentials-for-network-authentication)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-access-do-not-allow-storage-of-passwords-and-credentials-for-network-authentication.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-access-do-not-allow-storage-of-passwords-and-credentials-for-network-authentication.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@Rvvhub . thanks for pointing out.

**Comment by denisebmsft** [comment]
Than you @Rvvhub for letting us know about this, and thank you @RAJU2529 for fixing it. The update will be live a little later this morning.
