### ISSUE TITLE
会自动切换为来宾

### ISSUE THREAD

**Issue by wolfcai** [MicrosoftDocs/windows-itpro-docs#9771]
[在此处输入反馈]

修改成为经典过段时间又会自动切换成来宾，这个怎么进行修改
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6d2e7001-2014-c6a1-99ca-26b51950d4e3
* Version Independent ID: e9683068-96ac-500b-a068-32f98415933b
* Content: [Windows 10 应用商店中的本地帐户的网络访问 (和安全)  - Windows security](https://docs.microsoft.com/zh-cn/windows/security/threat-protection/security-policy-settings/network-access-sharing-and-security-model-for-local-accounts)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-access-sharing-and-security-model-for-local-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/network-access-sharing-and-security-model-for-local-accounts.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
The translated comment is:

Modify becomes a classic over time and automatically switches to guests, how to modify this

**Comment by e0i** [comment]
Hello, @wolfcai 

Please refer to the [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) channel for your product related questions.

Also let us know if you think there is something that could be done to improve the article that you have referred in this feedback.

Thank you.
