### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by mahdiameri** [MicrosoftDocs/windows-itpro-docs#9775]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 272c8c94-dd81-589c-2938-456de9d6edad
* Version Independent ID: e7dd144a-e07a-a900-d904-8488c34aeaa6
* Content: [Windows 11 overview - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/windows-11)
* Content Source: [windows/whats-new/windows-11.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/windows-11.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@e0i , There is no proper feedback, so please close this issue #9775.
