### ISSUE TITLE
add manage preview builds link must be added

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#9776]
I want to add managing of preview builds across your  organization  link and its  explanation (not own )
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 272c8c94-dd81-589c-2938-456de9d6edad
* Version Independent ID: e7dd144a-e07a-a900-d904-8488c34aeaa6
* Content: [Windows 11 overview - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/windows-11)
* Content Source: [windows/whats-new/windows-11.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/windows-11.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@greg-lindsay . Sir please tell your opinion in this regard.

**Comment by e0i** [comment]
@RAJU2529 As always, you are welcome to come up with a PR to propose the contributions that you have mentioned. Thanks.

**Comment by RAJU2529** [comment]
@e0i, Just now created PR  #9841 , so please look into this PR #9841 .
Thanking you.

**Comment by RAJU2529** [comment]
this issue has been solved, so i am closing my side.
