### ISSUE TITLE
applies to windows 11 to be added

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#9780]
As per the windows 11 system requirements ,TPM 2.0 is  needed, so  windows 11 must be added  to  applies to section
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a149789-67c1-e126-129b-6e77e831086d
* Version Independent ID: dd04d845-c098-46e5-fedf-92ba8fc64615
* Content: [Trusted Platform Module Technology Overview (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/trusted-platform-module-overview)
* Content Source: [windows/security/information-protection/tpm/trusted-platform-module-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/tpm/trusted-platform-module-overview.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @RAJU2529 ,
please have a look at https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9898
Thank you
