### ISSUE TITLE
Windows 10 GPO

### ISSUE THREAD

**Issue by origoman** [MicrosoftDocs/windows-itpro-docs#9781]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 739bc932-12f0-9595-fbd2-d5b0df73fe93
* Version Independent ID: cd1f89ad-34db-bb96-e9ef-2137958c9403
* Content: [Advanced security audit policy settings (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/advanced-security-audit-policy-settings?source=docs)
* Content Source: [windows/security/threat-protection/auditing/advanced-security-audit-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/advanced-security-audit-policy-settings.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@origoman . you have not described any issues

**Comment by RAJU2529** [comment]
@e0i . There is no proper feedback so close this #9781.
