### ISSUE TITLE
add the following windows 10 versions

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#9784]
please include the following windows versions  in the below article 
**https://docs.microsoft.com/windows-hardware/design/device-experiences/vbs-resource-protections**

**Windows 10, version 21H2
Windows 10, version 21H1
Windows 10, version 20H2
Windows 10, version 20H1
Windows 10, version 1909
Windows 10, version 1903
Windows 10, version 1809**

Because i used and verified the above windows 10 os versions, I conformed  **VBS** is fully compatible.

**Comment by greg-lindsay** [comment]
I will send an email to the author of that page. That page is not part of this repository.
