### ISSUE TITLE
Windows 11 

### ISSUE THREAD

**Issue by sweetunicorn30** [MicrosoftDocs/windows-itpro-docs#9789]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a149789-67c1-e126-129b-6e77e831086d
* Version Independent ID: dd04d845-c098-46e5-fedf-92ba8fc64615
* Content: [Trusted Platform Module Technology Overview (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-GB/windows/security/information-protection/tpm/trusted-platform-module-overview)
* Content Source: [windows/security/information-protection/tpm/trusted-platform-module-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/tpm/trusted-platform-module-overview.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@sweetunicorn30 . No proper feedback,  so please  @e0i close this issue #9789

**Comment by sweetunicorn30** [comment]
thank you :)
