### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by geoken** [MicrosoftDocs/windows-itpro-docs#9790]
There is a small typo in the following section;

`For example, the name "Erin M. Hagens" is split into three tokens: "Erin", "M", and "Havens". Because the second token is only...`

It refers to the display name as 'Ha**g**ens' initially, then later as 'Ha**v**ens'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5128d9a-e02a-df9b-24cc-32711ad37b54
* Version Independent ID: fecafb19-6b37-1f2e-ba3d-5e0bf0d49d09
* Content: [Password must meet complexity requirements (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements)
* Content Source: [windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@geoken  Thanks for pointing out. I am fixing this typo error.

**Comment by denisebmsft** [comment]
Thank you @geoken for letting us know about this. And thank you @RAJU2529 for the fix. The article has been updated, and you'll see the updated content live later today (at around 4 p.m. Pacific Time). Closing this issue.
