### ISSUE TITLE
Cannot find "Certificate Template" section under MMC (Windows 2019-2022)

### ISSUE THREAD

**Issue by tdsan** [MicrosoftDocs/windows-itpro-docs#9796]
[Enter feedback here]

I am trying to find the section under the MMC after I select "Add/Remove Snapins. Not sure if it exists.
![image](https://user-images.githubusercontent.com/4975020/125134099-dcfa1e80-e0d4-11eb-8ef1-3259cc716055.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20f487a0-5d22-9db1-67b8-b8e16aa07d23
* Version Independent ID: 14d72ae1-1b8c-4682-7226-f115b69061a8
* Content: [Get Started with Virtual Smart Cards - Walkthrough Guide (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-get-started)
* Content Source: [windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-get-started.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @tdsan ,
are you sure AD CA role is installed on the server you are doing it?
Thank you

**Comment by MaratMussabekov** [comment]
Hello @tdsan ,
did you have a chance to check it?
Thank you
