### ISSUE TITLE
idk kinda did this by itself

### ISSUE THREAD

**Issue by Hav0ksHELL** [MicrosoftDocs/windows-itpro-docs#9797]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738225b2-66a4-e0dd-47fb-faf333ed52d1
* Version Independent ID: d9d3274c-3ee7-ed3a-6cd8-6b387027562c
* Content: [Diagnose MDM failures in Windows 10 - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/diagnose-mdm-failures-in-windows-10?redirectedfrom=MSDN)
* Content Source: [windows/client-management/mdm/diagnose-mdm-failures-in-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/diagnose-mdm-failures-in-windows-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@e0i , No proper feedback for this issue #9797 , so please close this #9797
