### ISSUE TITLE
Remove PCmover Express reference

### ISSUE THREAD

**Issue by bcross** [MicrosoftDocs/windows-itpro-docs#9807]
Lapilink's PCmover Express will cease to be free starting July 31st, 2021. It is currently not free for commercial use. Because these two facts conflict with USMT's free for commercial use solution, please remove the reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde8580a-bd82-ebd2-3767-f3ee662a904e
* Version Independent ID: 94323219-e4ed-8761-723e-06be33c3b9cc
* Content: [User State Migration Tool (USMT) Overview (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-overview)
* Content Source: [windows/deployment/usmt/usmt-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/usmt/usmt-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
I will add a note that it is not free. The purpose of the article is not to provide only guidance that is free.
