### ISSUE TITLE
Add Description of Illegal Password Characters

### ISSUE THREAD

**Issue by Jitsusama** [MicrosoftDocs/windows-itpro-docs#9808]
It would be quite useful to have a description of what characters are invalid for a password, either on this page, or some other page (this is the closest page I could find.) This is particularly useful when wanting to protect AD authentication attempts on a front end system by outright blocking AD authentication if the provided password has an illegal character in it.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5128d9a-e02a-df9b-24cc-32711ad37b54
* Version Independent ID: fecafb19-6b37-1f2e-ba3d-5e0bf0d49d09
* Content: [Password must meet complexity requirements (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements)
* Content Source: [windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@Jitsusama The article refferenced lists the allowed characters : 

> The password contains characters from three of the following categories:
> 
> Uppercase letters of European languages (A through Z, with diacritic marks, Greek and Cyrillic characters)
> Lowercase letters of European languages (a through z, sharp-s, with diacritic marks, Greek and Cyrillic characters)
> Base 10 digits (0 through 9)
> Non-alphanumeric characters (special characters): (~!@#$%^&*_-+=`|\(){}[]:;"'<>,.?/) Currency symbols such as the Euro or British Pound aren't counted as special characters for this policy setting.
> Any Unicode character that's categorized as an alphabetic character but isn't uppercase or lowercase. This group includes Unicode characters from Asian languages.

So if you're looking for the "illegal" characters, it would be all except the above allowed ones, right?

**Comment by Jitsusama** [comment]
@VLG17; from my reading, that states what a password should have to meet complexity requirements, but does not state what characters are legal or illegal. If that description does end up equating to the list of valid characters, then explicitly stating that would meet a developer's needs for validation nicely.

**Comment by msbemba** [comment]
@Jitsusama Thank you for your feedback. Windows allows all [UTF-16](http://en.wikipedia.org/wiki/UTF-16) characters set in passwords. However, if the policy is enabled, passwords must meet the minimum requirements when they are changed or created.

Hope this helps!

Thanks
Sri
