### ISSUE TITLE
edit review for "BitLocker cannot encrypt a drive: known issues"

### ISSUE THREAD

**Issue by verdy-p** [MicrosoftDocs/windows-itpro-docs#9821]
In the "Resolution" section, "To repair the security descriptor of BDESvc, open an elevated PowerShell window and enter the following command:"

> `sc sdset bdesvc D:(A;;CCDCLCSWRPWPDTLORCWDWO;;;SY)(A;;CCDCLCSWRPWPDTLORCWDWO;;;BA)(A;;CCLCSWRPLORC;;;BU)(A;;CCLCSWRPLORC;;;AU)S:(AU;FA;CCDCLCSWRPWPDTLOSDRCWDWO;;;WD)`

This command does not work without the quotation marks (because the SDDL string contains semicolons and parentheses,)

This should be:

> `sc sdset bdesvc "D:(A;;CCDCLCSWRPWPDTLORCWDWO;;;SY)(A;;CCDCLCSWRPWPDTLORCWDWO;;;BA)(A;;CCLCSWRPLORC;;;BU)(A;;CCLCSWRPLORC;;;AU)S:(AU;FA;CCDCLCSWRPWPDTLOSDRCWDWO;;;WD)"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31baa23e-2ca3-617f-c061-cfbcff4909ce
* Version Independent ID: fa64d25d-48ef-8c20-7227-ea78b6294bf4
* Content: [BitLocker cannot encrypt a drive  known issues - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/ts-bitlocker-cannot-encrypt-issues)
* Content Source: [windows/security/information-protection/bitlocker/ts-bitlocker-cannot-encrypt-issues.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/ts-bitlocker-cannot-encrypt-issues.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by RAJU2529** [comment]
@verdy-p ,  without quotation marks given command, is worked in normal command prompt with elevated admin rights.

![Capture03](https://user-images.githubusercontent.com/3296790/126433469-ce46078c-1d39-4c3c-8695-25ebc6ae969a.JPG)

Please share the PowerShell working command  screenshots here

**Comment by verdy-p** [comment]
Your screenshot is made inside CMD. But in the powershell (used by default on Windows) this command line does not work without the "quotes". and all other users complaining in comments of the article experiment in fact the same problem (and they provided the screenshots in Powershell).
It is good practice to use these "quotes" around any SDDL, just because of parentheses.

**Comment by aczechowski** [comment]
This article was migrated to the Windows troubleshooting content library, which is owned by another team in support. I've shared this issue with them if they want to take action on it. I'm closing this issue as there's nothing actionable for my team since this content no longer exists in this repository.
