### ISSUE TITLE
set-OUPermissions.ps1 appears to be truncated

### ISSUE THREAD

**Issue by dcdorsey777** [MicrosoftDocs/windows-itpro-docs#9828]
The file, it appears to me, is truncated in the middle of a line.  Am I not able to view the complete file?

It ends on line 54, which in its entirety, is:
dsacls.exe $OrganizationalUnitDN

**Comment by RAJU2529** [comment]
@dcdorsey777  Which article are you referring to?

**Comment by e0i** [comment]
@dcdorsey777 Please feel free to reopen this PR with a reference to the article that this problem appears. Thanks.
