### ISSUE TITLE
Typo on the "Manage additional Windows Update settings" page

### ISSUE THREAD

**Issue by Minteck** [MicrosoftDocs/windows-itpro-docs#9830]
Hello, there is a little typo in this part of the [Manage additional Windows Update settings](https://docs.microsoft.com/en-us/windows/deployment/update/waas-wu-settings) page:
> Specify Intranet Microsoft update service location allows admins to point devices to an internal Microsoft update service location, while Do not connect to any Windows Update Internet locations gives them to option to restrict devices to just that internal update service.

It says "gives them to option to restrict" instead of "gives them the option to restrict".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efb8dfd-971e-7257-f8b7-f80843989eb8
* Version Independent ID: d7808728-bb89-a06e-a103-ec1c74682f64
* Content: [Manage additional Windows Update settings (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-wu-settings)
* Content Source: [windows/deployment/update/waas-wu-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-wu-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by Crimsonfox89** [comment]
Opened PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9897 to fix this
