### ISSUE TITLE
can i add MFA link in this article

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#9832]
Can I add Multi-Factor Authentication (MFA) link  in this article 
**https://www.microsoft.com/security/blog/2020/01/15/how-to-implement-multi-factor-authentication/**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa733db-e564-bd3f-d41b-241b27b13b40
* Version Independent ID: ef647afb-e298-af7b-5523-2076d3f2c9c6
* Content: [Prepare for Windows 11 - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/windows-11-prepare)
* Content Source: [windows/whats-new/windows-11-prepare.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/windows-11-prepare.md)
* Product: **w11**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by msbemba** [comment]
@RAJU2529 Thank you for your feedback. Sorry about the delay in answering this issue.

While the link presented is very useful, it can only be linked to a document if it is entirely related to the topic discussed. I'd not recommend linking this for now.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @RAJU2529 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
