### ISSUE TITLE
Need help finding the right setting under group policy

### ISSUE THREAD

**Issue by RaycomSports** [MicrosoftDocs/windows-itpro-docs#9844]
Hello - I'm a video editor in Charlotte, NC and need some guidance on setting the **right to raise the thread priority.**   We use Avid software and this is how it authorizes the user as a licensed user.  I had no problems getting IT to set this up at my last facility.  The company I work for **now** has a corporate IT dept in another state that only responds to emailed cases from the head of IT here.  So they won't call - only email help at their leisure.  Any guidance you can offer would be a massive help.

![domain_user_thread_priority](https://user-images.githubusercontent.com/87995714/127030502-3759f099-19e9-41f0-8d08-077691e72d68.PNG)

**Comment by RAJU2529** [comment]
@RaycomSports . Have you contacted to the avid technical support team?

**Comment by RaycomSports** [comment]
yes- much of what I am asking is from Avid support.   All testing on my part points to group policy settings- because I can authorize the software as a local admin.  But when I force update the group policy in testing - the authorization is gone.  This also happens on its's own daily with GP being updated by IT.  Avid referred me to three links including here and their case comments posted below in bold.  Appreciate any thoughts.

Refer : https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/increase-scheduling-priority

https://avid.secure.force.com/pkb/articles/en_US/How_To/Windows-User-Rights-Requirements-for-Media-Composer?retURL=%2Fpkb%2Farticles%2Fen_US%2Ferror_message%2FAAE-1177&popup=true
>>>

https://avid.secure.force.com/pkb/articles/en_US/how_to/What-should-I-look-for-if-the-Avid-Assist-application-will-not-run-after-installation

**We can't dictate what your group policy is, and so a lot of this is going to fall on your (and IT's) shoulders to figure out. It sounds like you are stuck. Here are some considerations, and one of the most important things is that the user MUST have the right to raise the thread priority. Make sure the Avid users on the local machine have that right!**

**Comment by denisebmsft** [comment]
Hello @RaycomSports. Seems like you need to contact Microsoft technical support for this issue. I did find one article that might be what you are looking for: https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreadpriority

**Comment by RaycomSports** [comment]
Thanks denisebmsft- I'm looking for help anywhere I can find it - and as an editor not an IT guru I'm asking and posting anywhere I can.  Would you or RAJU2529 have any thoughts as to how to narrow my inquiry- contacting Microsoft support seems like a pretty wide open first step.  Any help to narrow the field would be appreciated.

> Hello @RaycomSports. Seems like you need to contact Microsoft technical support for this issue. I did find one article that might be what you are looking for: https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreadpriority. This does not appear to be a documentation issue, so I am going to close it for now. But if you do run into an issue with docs, please let us know.

**Comment by RAJU2529** [comment]
@RaycomSports , You may follow the below link for setting thread priority 
**https://www.microsoftpressstore.com/articles/article.aspx?p=2233328&seqNum=7**

The avid media application developers team should create group policy templates for windows admx and adml files.

Note: Above link is non-Microsoft website.

**Comment by RaycomSports** [comment]
Thank you all for the additional input.  RAJU2529 I didn't know that templates could be made and shared regarding group policy.
That's a great idea.

**Comment by RAJU2529** [comment]
> Thank you all for the additional input. RAJU2529 I didn't know that templates could be made and shared regarding group policy.
> That's a great idea.

Because I have seen  Many vendors given templates for their products, say Adobe dc arcobat reader, 7-zip, Java.

**Comment by RaycomSports** [comment]
The corporate level of IT here makes this difficult - when I have built edit facilities elsewhere- I never had this problem because IT was 3 guys.
