### ISSUE TITLE
Applies to windows 11 must be added

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#9850]
After reading this article , windows 11 is eligible so Windows 11 must be added to Applies  to section.
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6957383-3bd9-eef9-6410-9c42f8a0b172
* Version Independent ID: a2090374-0fd1-8d67-66de-30c4cf2835f7
* Content: [Overview of Windows as a service (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-au/windows/deployment/update/waas-overview?source=docs)
* Content Source: [windows/deployment/update/waas-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
I appreciate the assistance, however, this article does NOT completely apply to Windows 11 (the release cadence is different). It would be inaccurate to include it in the "applies to" list.
