### ISSUE TITLE
Can we please mention the easiest way: Get-WindowsAutopilotInfo.ps1 -Online?

### ISSUE THREAD

**Issue by vazome** [MicrosoftDocs/windows-itpro-docs#9857]
There is no need to do all these steps with capturing hardware ID if you just do Get-WindowsAutopilotInfo -Online via CMD (Shift + F10) in OOBE.
```
Set-ExecutionPolicy -Scope Bypass -Force
Install-Script -Name Get-WindowsAutopilotInfo -Force
Get-WindowsAutopilotInfo.ps1 -Online
```
Sure doing it offline is an option but in my opinion first one must be the easiest: Get-WindowsAutopilotInfo.ps1 -Online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc63299-cc1c-e031-deb7-915914b8f94e
* Version Independent ID: 356eaba5-16b0-952f-fc19-c8d5be5feb5f
* Content: [Demonstrate Autopilot deployment - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm#configure-company-branding)
* Content Source: [windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by vazome** [comment]
Also, no need to finishing OOBE if there is possibility to invoke CMD after network configuration

**Comment by yogkumgit** [comment]
@greg-lindsay Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@frankroj Please help us in resolving this issue. Thanks

**Comment by frankroj** [comment]
This article is a demonstration and walkthrough. Its purpose is not to show every possible use of the Get-WindowsAutopilotInfo script, nor every possible way to get the hardware ID. It just shows one way to accomplish the task. While there are certainly multiple ways to accomplish the task of obtaining the hardware ID, including possible easier ways, there is no need to add additional ways to this particular article. We appreciate the feedback but at this time my opinion is that there is no need to change the article.
