### ISSUE TITLE
text

### ISSUE THREAD

**Issue by Deezlw11** [MicrosoftDocs/windows-itpro-docs#9861]
[اكتب ملاحظاتك هنا]

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ docs.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: 54254070-539b-6cf2-f988-c80ad685c5fa
* Version Independent ID: 5bbe5140-eee5-abc3-1a26-1c0d13eab358
* Content: [Diagnostic Data Viewer Overview (Windows 10) - Windows Privacy](https://docs.microsoft.com/ar-sa/windows/privacy/diagnostic-data-viewer-overview)
* Content Source: [windows/privacy/diagnostic-data-viewer-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/diagnostic-data-viewer-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@e0i, No proper description of this issue #9861. So please close this issue #9861
