### ISSUE TITLE
i wnte mods

### ISSUE THREAD

**Issue by hotboy1123** [MicrosoftDocs/windows-itpro-docs#9876]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4edaae97-455b-d25a-9228-5309e24b4aa3
* Version Independent ID: d38e56a7-d553-e519-95a9-dc93e2cdc771
* Content: [Microsoft Defender SmartScreen overview (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview)
* Content Source: [windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@e0i  there is no proper feedback so close this issue #9876.
