### ISSUE TITLE
Uninstall App via ./Device/Vendor/MSFT/EnterpriseDesktopAppManagement/MSI/

### ISSUE THREAD

**Issue by dfconroy** [MicrosoftDocs/windows-itpro-docs#9877]
I've install an MSI via:

./Device/Vendor/MSFT/EnterpriseDesktopAppManagement/MSI/OurTestApp/DownloadInstall

and it's shown in the Managed of Work/School.

However, when I send an Delete command to uninstall it, it comes back as 200 but the name is still shown in the Managed section of Work/School. And if I send the delete again it returns a 404.

How do we go about removing the listed app from the 'Areas Managed By...' section?

**Comment by RAJU2529** [comment]
@dfconroy . Which article are you referring to?

**Comment by dfconroy** [comment]
[enterprisedesktopappmanagement](https://docs.microsoft.com/en-us/windows/client-management/mdm/enterprisedesktopappmanagement-csp)

This doesn't remove the app from the Areas Managed By screen under settings. 

`<SyncML xmlns="SYNCML:SYNCML1.1">
  <SyncBody>
    <Delete>
      <CmdID>12345</CmdID>
      <Item>
        <Target>
          <LocURI>./Device/Vendor/MSFT/EnterpriseDesktopAppManagement/MSI/%7B1803A630-3C38-4D2B-9B9A-0CB37243539C%7D</LocURI>
        </Target>
      </Item>
    </Delete>
    <Final/>
  </SyncBody>
</SyncML>`

**Comment by dfconroy** [comment]
@e0i Does this issue not belong here, since the issue remains an MDM issue and these docs reference how-tos with MDM? 

The ongoing issue is with this CSP:
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enterprisedesktopappmanagement-csp.md

When an app is removed/uninstalled via MDM, it remains listed under the 'Managed By' area in school/work settings.
