### ISSUE TITLE
How to use memory dump to collect data if no scroll lock key is present on the keyboard?

### ISSUE THREAD

**Issue by mariusstaub** [MicrosoftDocs/windows-itpro-docs#9879]
My feedback is about the following section:

> When the computer exhibits the problem, hold down the right CTRL key, and press the Scroll Lock key two times to generate a memory dump.

Many laptop keyboards do not have a scroll lock key any more. Please update the page with information about what to do in this case. 

For my computer model I found a replacement key combination for scroll lock but I need to press multiple keys at the same time and it seems that the data collection does not start when I press these keys.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7aab622-1bde-637a-8999-cac5f3f68ac4
* Version Independent ID: 16af5e10-0748-ec6f-f539-2ee8563c3702
* Content: [Advanced troubleshooting for Windows-based computer freeze issues - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-windows-freeze)
* Content Source: [windows/client-management/troubleshoot-windows-freeze.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/troubleshoot-windows-freeze.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@mariusstaub There is the option of using .dump command to create a dump file - https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/creating-a-dump-file-without-a-system-crash
