### ISSUE TITLE
Incorrect Path for Windows Update exclusion

### ISSUE THREAD

**Issue by MatthiasMulterer** [MicrosoftDocs/windows-itpro-docs#988]
Incorrect:
%windir%\SoftwareDistribution\Datastore\\*\Datastore.edb

Correct:
%windir%\SoftwareDistribution\Datastore\Datastore.edb

Could you please verify my information and correct the article? 

Thanks a lot!

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7c9b6379-e575-9819-eca1-a0952f66b655
* Version Independent ID: 34d81602-ffa2-5be6-67ef-b42b3b6f17ee
* Content: [Automatische und benutzerdefinierte Ausschlüsse für Windows Defender AV auf Windows Server2016](https://docs.microsoft.com/de-de/windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by andreabichsel** [comment]
I fixed the link, and changes should be live on the English site by end of day.
