### ISSUE TITLE
Access .extension.rights.source.de.md

### ISSUE THREAD

**Issue by AfirstS** [MicrosoftDocs/windows-itpro-docs#9880]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b5e396-a7d4-af3c-fde2-5b8374d0ad27
* Version Independent ID: 9ea74c2f-76d4-9735-ac2b-cc38e1bd00f6
* Content: [Deploying Windows Defender Application Control (WDAC) policies (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control-deployment-guide)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control-deployment-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control-deployment-guide.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@e0i,  no proper feedback to this issue, so close this
