### ISSUE TITLE
[LOC]Fixed inappropriate japanese "Azure アプリケーション プロキシAD" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#9884]
ja-jp:"https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert"
![hello-hybrid-aadj-sso-cert_j](https://user-images.githubusercontent.com/40815708/128635058-6a6ef618-7e38-4341-94d9-6b8fde343d46.png)

en-us:"https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert"
![hello-hybrid-aadj-sso-cert_e](https://user-images.githubusercontent.com/40815708/128635066-737265ae-4e3b-46d7-8e48-dd69d63fe42b.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f709fd4-0b5d-b238-4060-222d550cd538
* Version Independent ID: fb3f29da-2236-c47d-6bea-8efbcec8d7d3
* Content: [Using Certificates for AADJ On-premises Single-sign On single sign-on - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by TinaMcN** [comment]
@hyoshioka0128 thanks for reporting the issue.  The article will be human translated which will hopefully fix the problem.  It should be completed in approx. 3 days.

**Comment by TinaMcN** [comment]
@hyoshioka0128 the article has been human translated now.  Can you please check if it looks ok now and close if it's correct.

**Comment by hyoshioka0128** [comment]
@TinaMcN - Thanks! Fixed.
Closed #9884 .
