### ISSUE TITLE
Page references Network Monitor and MMA - both of which are deprecated

### ISSUE THREAD

**Issue by TotallyInformation** [MicrosoftDocs/windows-itpro-docs#9889]
[Enter feedback here]

Please fix this page as neither of the referenced tools are current any more - how are you supposed to monitor bandwidth without these tools?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8823127-9a9b-141c-6096-e8d40ff6e22c
* Version Independent ID: 02332337-0981-36af-424e-9378487dd4d8
* Content: [Collect data using Network Monitor - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-tcpip-netmon)
* Content Source: [windows/client-management/troubleshoot-tcpip-netmon.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/troubleshoot-tcpip-netmon.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@TotallyInformation The [download link for Network Monitor 3.4 (archive)](https://www.microsoft.com/en-us/download/details.aspx?id=4865) works.  

Regarding Microsoft Message Analyzer, as per the [official blog](https://docs.microsoft.com/en-us/openspecs/blog/ms-winintbloglp/dd98b93c-0a75-4eb0-b92e-e760c502394f) :

November 25 2019.  There is currently no Microsoft replacement for Microsoft Message Analyzer in development at this time.  For similar functionality, **please consider using a 3rd party network protocol analyzer tool such as Wireshark.**

**If you already have Microsoft Message Analyzer installed, you may continue to use it, along with the OPN parsers you have already downloaded.**
