### ISSUE TITLE
 Incorrect variable name in Step 6 - substep: edit the Windows 10 task sequence

### ISSUE THREAD

**Issue by dcdorsey777** [MicrosoftDocs/windows-itpro-docs#9894]
In Step 6 "Create the deployment task sequence", under substep "edit the Windows 10 task sequence", the text instructions in Step 2-a-iii specify to set DriverGroup001 to Windows 10 x64\%Manufacturer%\%Model%

%Manufacturer% is the incorrect variable name.  The variable name for the manufacturer name is %Make%.  This is shown correctly farther down the page in the figure "The task sequence for production deployment".  However, I was very frustrated for 2 days trying to get this to work before I realized it.  

Hope someone can correct this for the next poor knucklehead to try to learn MDT.

I guess this error is understandable because the command find the manufacturer name is wmic computersystem get manufacturer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c66f2a3-5be3-e3cf-b90f-c9ce2f6ecf9d
* Version Independent ID: c9ed7f55-3770-73a4-5ee4-deee16eb7600
* Content: [Deploy a Windows 10 image using MDT (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@dcdorsey777 . Thanks for the information. I will correct those mistakes

**Comment by dcdorsey777** [comment]
This does not appear to be corrected.  What am I missing?  The error still appears in the document at: https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/deploy-a-windows-10-image-using-mdt#edit-the-windows-10-task-sequence

I have cleared my browser cache.  Is there another step I need to take to see the updated document?

***@***.***

Dave Dorsey
PCFD
