### ISSUE TITLE
Deploying signed policies has incomplete and inaccurate instructions

### ISSUE THREAD

**Issue by KenBenjamin** [MicrosoftDocs/windows-itpro-docs#9895]
In the section [Deploying signed policies](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/deployment/deploy-wdac-policies-with-script#deploying-signed-policies), The example is incomplete, doesn't work when made complete, and doesn't tie into the previous steps. I suggest the following code block replace the steps:

```powershell
$MountPoint = 'C:\EFI'
$EFIDestinationFolder = "$MountPoint\Microsoft\Boot\CiPolicies\Active"

$EFIPartition = (Get-Partition | Where-Object IsSystem).AccessPaths[0]

mkdir $MountPoint -Force
mountvol $MountPoint $EFIPartition
Copy-Item -Path $PolicyBinary -Destination $EFIDestFolder -Force
mountvol $MountPoint /D # Unmount
```

I addition, the whole subsection should be merged up into the containing section between steps 3 and 4, with step 4 becoming step 5, and the reboot as step 6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abfc58da-2ac1-e8b7-b4e7-8f61e7f103ab
* Version Independent ID: 2dfd2a31-cf0d-8a11-94da-842792f892d1
* Content: [Deploy Windows Defender Application Control (WDAC) policies using script (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/deployment/deploy-wdac-policies-with-script#deploying-signed-policies)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/deployment/deploy-wdac-policies-with-script.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/deployment/deploy-wdac-policies-with-script.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jsuther1974
* Microsoft Alias: **jogeurte**

**Comment by MaratMussabekov** [comment]
Hello @KenBenjamin ,
**$EFIPartition = (Get-Partition | Where-Object IsSystem).AccessPaths[0]** - wouldn't it return system partition instead of EFI partition?
**mountvol $MountPoint $EFIPartition** - not sure what this command suppose to do
**the whole subsection should be merged up into the containing section** - agree

Thank you

**Comment by MaratMussabekov** [comment]
Dear @KenBenjamin , please have a look at https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9988
Thank you

**Comment by KenBenjamin** [comment]
@MaratMussabekov,

I don't see where your new code gets the EFI partition nor does it pass it to `mountvol`. Here are the answers to your questions:

$EFIPartition = (Get-Partition | Where-Object IsSystem).AccessPaths[0] - wouldn't it return system partition instead of EFI partition? _Yes and no. The EFI partition is labelled as a "System" partition whereas a normal boot partition e.g. C: is labelled as a "Basic" partition. You can check this yourself by running `Get-Partition` on your PC._
 
mountvol $MountPoint $EFIPartition - not sure what this command suppose to do _This is what actually *mounts* the partition to the mountpoint. Without it, you have no way to access the partition data. Basically, you're saying, hey, put a link to the EFI partition over here in this directory on C:._

I recommend against the commit #9988 as-is since it doesn't solve the problem and has other errors. I recommend you keep the code I created. It's as clean as I can make it and it works for me.
