### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by dstones** [MicrosoftDocs/windows-itpro-docs#990]
Passsword

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1da1ac4-4e67-5970-6d10-19aac6e853f6
* Version Independent ID: 4f4b45eb-d479-3699-1ef1-a1a20030d675
* Content: [Planning an adequate number of Windows Server 2016 Domain Controllers for Windows Hello for Business deployments](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-adequate-domain-controllers.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by justink-ase** [comment]
I can't seem to find that on this page.

**Comment by dstones** [comment]
it's in the "AS Requests" tables

**Comment by shortpatti** [comment]
To clarify, the typo is in the images.

**Comment by MikeStephens-MS** [comment]
FIXED!!
This should be fixed in today's update

**Comment by mypil** [comment]
@dstones - Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.

**Comment by illfated** [comment]
Fixed in https://github.com/MicrosoftDocs/windows-itpro-docs/commit/804a8d2899f37721c60b04eae1036e4530e063d9#diff-8ae6181675f262059bc59b5497313210 - according to MikeStephens-MS.
(Lot of other fixes in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/804a8d2899f37721c60b04eae1036e4530e063d9 - hence the diff link above.)
