### ISSUE TITLE
UUID in the Japanese-localized docs is wrong

### ISSUE THREAD

**Issue by tayasuta** [MicrosoftDocs/windows-itpro-docs#9900]
There is an extra one digit in the UUID in the Japanese-localized docs below. I suggest we remove this.

https://docs.microsoft.com/ja-jp/windows/client-management/mdm/policy-csp-bluetooth#servicesallowedlist-usage-guide
![image](https://user-images.githubusercontent.com/44643923/129468420-baa5ba43-2cbf-4e72-9374-e27b0f962416.png)

This is the original article.
https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-bluetooth#servicesallowedlist-usage-guide
![image](https://user-images.githubusercontent.com/44643923/129468454-f7714643-b28c-428c-bcf2-3f49ccc938f4.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 9596a57e-365e-2809-1f8d-8aebbda5bc36
* Version Independent ID: 4a287709-2466-93eb-cc2f-9f7566277abb
* Content: [Policy CSP - Bluetooth - Windows Client Management](https://review.docs.microsoft.com/ja-jp/windows/client-management/mdm/policy-csp-bluetooth?branch=main)
* Content Source: [windows/client-management/mdm/policy-csp-bluetooth.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-bluetooth.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@ManikaDhiman , I could not able to edit the Japanese document.

**Comment by denisebmsft** [comment]
Hi @TinaMcN! Can you please take a look at this issue? Thanks!

**Comment by TinaMcN** [comment]
@tayasuta thanks for reporting the issue, I sent the article to be human translated which will hopefully fix the problem, it should be completed within a week.

**Comment by TinaMcN** [comment]
@tayasuta the issue has been fixed.  Please close if it looks ok to you now.  Thanks again for reporting it.
https://docs.microsoft.com/ja-jp/windows/client-management/mdm/policy-csp-bluetooth#servicesallowedlist-usage-guide

**Comment by tayasuta** [comment]
@TinaMcN It looks good to me.  I'll close this issue. Thank you!
