### ISSUE TITLE
The URL is not valid

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/windows-itpro-docs#9907]
The file download URL at the bottom of the document is invalid. For example: MDTSample 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7ab08370-69ab-d025-cea2-c41c3aa4b908
* Version Independent ID: 9f5603f8-10e6-2651-3120-6d5627217cc9
* Content: [准备使用 MDT 部署 (Windows 10) - Windows Deployment](https://docs.microsoft.com/zh-cn/windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Some of the locations in the appendix have been retired. I'll need to either find a new location or remove these links.

**Comment by RAJU2529** [comment]
@greg-lindsay. MDTsample.zip  link is working and I downloaded zip file.

also Set-OUpermissions.ps1 link is redirected to below site

**https://github.com/DeploymentArtist/SWP1/tree/master/Scripts**

Gather.ps1 link is redirected  to below site

**https://docs.microsoft.com/zh-cn/samples/browse/?redirectedfrom=TechNet-Gallery**

**Comment by greg-lindsay** [comment]
The set-oupermissions script has a valid link to the author's github location.
gather.ps1 seems to have been removed. I fixed this in another PR but the entire article was then reverted so I lost that fix. I'll fix it again.
