### ISSUE TITLE
Rewriting Creating the OU structure in Prepare for deployment with MDT

### ISSUE THREAD

**Issue by 0x750** [MicrosoftDocs/windows-itpro-docs#9910]
In the [Create the OU structure](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt#create-the-ou-structure) section, the working directory is set to `C:\Setup\Scripts`, it would be a better practice to create this folder in `$home`, like `~\Setup\Scripts`.

The OU names and path file is saved and displayed in the documentation as a `.txt` file, then imported with the `Import-CSV` command.

It would be clearer if the CSV file was created before the Powershell script.

In the following Powershell snippet : 

```powershell
$oulist = Import-csv -Path c:\oulist.txt
ForEach($entry in $oulist){
    $ouname = $entry.ouname
    $oupath = $entry.oupath
    New-ADOrganizationalUnit -Name $ouname -Path $oupath
    Write-Host -ForegroundColor Green "OU $ouname is created in the location $oupath"
}
```

- The file `c:\oulist.txt` __does not exist__, it is created right after as `C:\Setup\Scripts\oulist.txt`.
- Many lines are useless.

This snippet can be shorter as the following : 

```powershell
Import-CSV -Path $home\Setup\Scripts\oulist.csv | ForEach-Object {
    New-ADOrganizationalUnit -Name $_.ouname -Path $_.oupath
    Write-Host -ForegroundColor Green "OU $($_.ouname) is created in the location $($_.oupath)"
}
```

This section would be clearer like this : 

[...]

## Create the OU structure

Switch to **DC01** and perform the following procedures on **DC01**:

To create the OU structure, you can use the Active Directory Users and Computers console (dsa.msc), or you can use Windows PowerShell.

Copy the following list of OU names and paths into a CSV file and save it as `~\Setup\Scripts\oulist.csv`.

```csv
OUName,OUPath
Contoso,"DC=CONTOSO,DC=COM"
Accounts,"OU=Contoso,DC=CONTOSO,DC=COM"
Computers,"OU=Contoso,DC=CONTOSO,DC=COM"
Groups,"OU=Contoso,DC=CONTOSO,DC=COM"
Admins,"OU=Accounts,OU=Contoso,DC=CONTOSO,DC=COM"
Service Accounts,"OU=Accounts,OU=Contoso,DC=CONTOSO,DC=COM"
Users,"OU=Accounts,OU=Contoso,DC=CONTOSO,DC=COM"
Servers,"OU=Computers,OU=Contoso,DC=CONTOSO,DC=COM"
Workstations,"OU=Computers,OU=Contoso,DC=CONTOSO,DC=COM"
Security Groups,"OU=Groups,OU=Contoso,DC=CONTOSO,DC=COM"
```

Next, copy the following commands into a file and save it as `~\Setup\Scripts\ou.ps1`. Be sure that you are viewing file extensions and that you save the file with the `.ps1` extension.

```powershell
Import-CSV -Path $home\Setup\Scripts\oulist.csv | ForEach-Object {
    New-ADOrganizationalUnit -Name $_.ouname -Path $_.oupath
    Write-Host -ForegroundColor Green "OU $($_.ouname) is created in the location $($_.oupath)"
}
```

Lastly, open an elevated Windows PowerShell prompt on DC01 and run the `ou.ps1` script:

```powershell
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force
Set-Location $home\Setup\Scripts
.\ou.ps1
```

This will create an OU structure as shown below.

[...]

Can i submit a PR that references this issue ?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ab08370-69ab-d025-cea2-c41c3aa4b908
* Version Independent ID: 9f5603f8-10e6-2651-3120-6d5627217cc9
* Content: [Prepare for deployment with MDT (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Hi, the suggestions appear to be good. Please go ahead and submit a PR if you'd like to. Thanks!

**Comment by 0x750** [comment]
Hello @greg-lindsay,

Please have a look at my PR #9912.

Thans in advance,
Benoit

**Comment by 0x750** [comment]
Closing as the PR #9912 was merged.
