### ISSUE TITLE
See Resolve Windows 10 upgrade errors

### ISSUE THREAD

**Issue by jacobjjjj** [MicrosoftDocs/windows-itpro-docs#9913]
There needs to be a clearer differential of "See Resolve Windows 10 upgrade errors" in terms of what you are talking about as to "See Resolve errors in upgrading to Windows 10" as opposed to "See Resolve Windows 10 errors in Windows Upgrades".

More clarity is needed is need to explain whether the article refers to upgrading "to Windows 10" or "windows 10 upgrades within Windows 10".

Reference: 

https://docs.microsoft.com/en-us/windows/deployment/upgrade/log-files

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aed724a-73f2-3b93-d273-8b8302086ea1
* Version Independent ID: 728c8856-ee32-1ba9-a0c4-4a5791f89a89
* Content: [Log files and resolving upgrade errors - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/upgrade/log-files)
* Content Source: [windows/deployment/upgrade/log-files.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/log-files.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
The article is about upgrade errors.  The upgrade process occurs any time the operating system version changes.

**Comment by jacobjjjj** [comment]
What is this supposed to mean please, upgrades to Windows 10 or upgrades within Windows 10?

As I stated, is it about upgrading to Windows 10, from a version prior to Windows 10 i.e. Windows 7, or is it about upgrades within Window 10?  If it is the later, I’m not sure logs within, for example the the Panther folder, are relevant.
