### ISSUE TITLE
PIN Caching encryption functions

### ISSUE THREAD

**Issue by jepryor** [MicrosoftDocs/windows-itpro-docs#9918]
The section on PIN Caching refers to RtlEncryptMemory and RtlDecryptMemory functions. Is this still accurate for current versions of Windows?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01db3c4c-a866-d367-72fb-86866a9ff2c6
* Version Independent ID: 5bc85899-f203-fd08-e6d8-deb9736fb17e
* Content: [Smart Card Architecture (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/smart-cards/smart-card-architecture)
* Content Source: [windows/security/identity-protection/smart-cards/smart-card-architecture.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/smart-cards/smart-card-architecture.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@jepryor According to the [requirements section](https://docs.microsoft.com/en-us/windows/win32/api/ntsecapi/nf-ntsecapi-rtlencryptmemory#requirements) it is valid for newer Windows versions.
