### ISSUE TITLE
@Cirnohalo you can find your answer here:

### ISSUE THREAD

**Issue by Cirnohalo** [MicrosoftDocs/windows-itpro-docs#9923]
@Cirnohalo you can find your answer here:

https://stackoverflow.com/questions/41047093/how-to-launch-a-win32-application-to-run-like-a-windows-10-assigned-access-appx

https://stackoverflow.com/questions/40492539/windows-10-assigned-access-app-fails-to-start-due-to-not-registered-for-windows

"**We got the confirmation that the Assigned Access mode doesn’t support Win32 apps yet, including Win32 apps converted with the Desktop Converter.**

It is a known issue in RS1 which can pick Converted app in setting UI. We have a planned fix for this in RS2 but do not guarantee it will be delivered soon.

Please see this article for how to use Shell Launcher to config a kiosk device that runs a Classic Windows application as the user interface: https://technet.microsoft.com/en-us/itpro/windows/manage/set-up-a-kiosk-for-windows-10-for-desktop-editions"

_Originally posted by @VLG17 in https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5144#issuecomment-553891651_

**Comment by Cirnohalo** [comment]
@VLG17  hi, when will this problem be fixed?

**Comment by e0i** [comment]
@Cirnohalo 

You can direct product related feedback to [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10).

This is a technical documentation repository.
