### ISSUE TITLE
Missing colon in page title

### ISSUE THREAD

**Issue by campbellkerr** [MicrosoftDocs/windows-itpro-docs#9926]
Nitpick - the page title (as seen in the browser title bar) is missing a colon between "Network security" and "Allow...."

`	<meta property="og:title" content="Network security Allow Local System to use computer identity for NTLM (Windows 10) - Windows security" />`

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2042e4d7-06ac-96c0-414a-02c1479344d8
* Version Independent ID: 20a0d568-3b2b-7eeb-cdd8-11ad2e780222
* Content: [Network security Allow Local System to use computer identity for NTLM (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-allow-local-system-to-use-computer-identity-for-ntlm?source=docs)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-security-allow-local-system-to-use-computer-identity-for-ntlm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-security-allow-local-system-to-use-computer-identity-for-ntlm.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @campbellkerr ,
I tried to fix it, however, Microsoft Docs portal doesn't allow using colons in page titles.
Thank you

**Comment by denisebmsft** [comment]
@campbellkerr, thank you for the feedback. @MaratMussabekov thank you for your help! The article has been updated, and the changes will be live later today.
