### ISSUE TITLE
Missing CSP info in docs

### ISSUE THREAD

**Issue by owaisfarooqui-MEM** [MicrosoftDocs/windows-itpro-docs#9927]
ADMX_Terminal (Windows insider only)
LocalPoliciesSecurityOptions/Accounts_EnableAdministratorAccountStatus

These are not included in the policy csp doc but exist on Windows and works as expected
Also the ADMX policy csp now does not work on latest Windows 10 insider but works on Windows 11 insider only. That might need correction in the docs as well 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe02a28-215f-f176-6086-8e79fcb48471
* Version Independent ID: f9143995-669d-be4d-3632-be2d0517d452
* [Policy CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-configuration-service-provider)
* Content Source: [windows/client-management/mdm/policy-configuration-service-provider.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-configuration-service-provider.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MehdiAliakbar32** [comment]
Thanks

**Comment by VLG17** [comment]
@owaisfarooqui-MEM I've created a PR to add info about LocalPoliciesSecurityOptions/Accounts_EnableAdministratorAccountStatus.

Regarding ADMX_Terminal, are you refering to ADMX_TerminalServer? That's already present [here](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-admx-terminalserver)
