### ISSUE TITLE
Needs a description of how to configure the Windows 11 Start menu

### ISSUE THREAD

**Issue by micachi** [MicrosoftDocs/windows-itpro-docs#9930]
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/customize-and-export-start-layout.md

It was announced that Windows 11 will be released on October 5, but organization administrators are aware that they need to be prepared for this. We are aware that the Start Menu layout policy does not work with traditional configuration methods.
Therefore, I need to explain the new setting method, but there is no corresponding document.

**Comment by RAJU2529** [comment]
@micachi Still Windows 11 RTM is not released, after commercial release windows 11 team members will update required information.
Thanking you.

**Comment by micachi** [comment]
There is only one month left before Windows 11 is released. It is also available today as a consumer preview.
This information is urgently needed to ensure a correct evaluation in the preview version.
Without this assessment, I wouldn't even be able to determine if I could move to Windows 11.

Thank you.

**Comment by micachi** [comment]
I have confirmed that a new document has been created here.
https://docs.microsoft.com/en-us/windows/configuration/customize-start-menu-layout-windows-11

Therefore, this problem has been resolved. I will close it.
