### ISSUE TITLE
AllowSignInOptions

### ISSUE THREAD

**Issue by cloidl** [MicrosoftDocs/windows-itpro-docs#9931]
[Enter feedback here]
I have a Customer who is trying to follow the steps in this article but it doesn't appear like it works as described. It does working using the AllowSignInOptions registry, which is all I could get from a number of Technical Advisors too. Would it be possible to incorporate some of the Microsoft Forum responses, like the following and the AllowSignInOptions registry key, into this article?

https://answers.microsoft.com/en-us/windows/forum/windows_10-hello/how-to-disable-windows-hello/05ab5492-19c7-4d44-b762-d93b44a9cf65

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 789566d4-463a-4c64-bf89-fb963ac29f80
* Version Independent ID: 02946732-bb29-d8e6-cedd-7f5e508f8798
* Content: [Manage Windows Hello in your organization (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-manage-in-organization)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-manage-in-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-manage-in-organization.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by RAJU2529** [comment]
@cloidl Would you like to add enable  sign in through windows hello   or disable windows hello through registry key in this article.

**Comment by cloidl** [comment]
> @cloidl Would you like to add enable sign in through windows hello or disable windows hello through registry key in this article

Disable Windows Hello through Registry

**Comment by bxmd** [comment]
Why not include all possible values, so both?

**Comment by cloidl** [comment]
Is this change to the documentation going to be made and if so when?

**Comment by mapalko** [comment]
@Cloidl, has you customer tried following the instructions here: https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-aad-join-cloud-only-deploy?

**Comment by cloidl** [comment]
@mapalko @RAJU2529 Is there any update on a potential update to this article to include those registry keys?

**Comment by mapalko** [comment]
Those registry keys are not settings associated with Windows Hello and are not officially supported for this use case. We do not have plans to include those registry settings in our public documentation. And are investigating whether there are issues with supported, documented ways to disable the feature.
