### ISSUE TITLE
Difference

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#9932]
In Para 2, you say there is a destructive and a non-destructive PIN reset. But you do not say what the practical difference is, from a user perspective. If the user has forgotten their PIN, why would they care whether the reset is destructive or non-destructive?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9dae9da-eaf0-c209-7c65-be8d2c1ada12
* Version Independent ID: 28b6788d-7982-23c2-5f19-f80690ebc0ce
* Content: [Pin Reset - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by MaratMussabekov** [comment]
Hello,
from admin's point of view:
destructive - doesn't require additional config, removes user's key
non-destructive - requires additional configuration effort, preserves user's key

from user's point of view:
destructive - only works from settings app
non-destructive - works from both settings app and lock screen

**If the user has forgotten their PIN, why would they care whether the reset is destructive or non-destructive?** - user does not see it

Thank you
