### ISSUE TITLE
Network isolation policy could use more information

### ISSUE THREAD

**Issue by bmilbauer** [MicrosoftDocs/windows-itpro-docs#9933]
This could use some elaboration on exactly what the network isolation policy does, example behavior, etc. 

I read through the page and was left a bit unclear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad59e7d-574d-7bd5-3fc9-a9656e186258
* Version Independent ID: e827f939-99b2-31e7-b65a-ee3ad499573e
* Content: [Configure the Group Policy settings for Microsoft Defender Application Guard (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-application-guard/configure-md-app-guard#network-isolation-settings)
* Content Source: [windows/security/threat-protection/microsoft-defender-application-guard/configure-md-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-application-guard/configure-md-app-guard.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by MaratMussabekov** [comment]
Hello @bmilbauer,
**This could use some elaboration on exactly what the network isolation policy does, example behavior, etc.** - it helps application guard to identify which network segments are considered as trusted by your company. You can check articles from **Recommended content** section, especially [Application Guard testing scenarios](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-application-guard/test-scenarios-md-app-guard).
Thank you
