### ISSUE TITLE
Interactive logon: Machine inactivity limit - Intune configuration not currently working

### ISSUE THREAD

**Issue by lXbalanque** [MicrosoftDocs/windows-itpro-docs#9937]
I've confirmed this in my own environment but not sure if it is worth updating the documentation here... the configuration setting does not currently allow you to set a value for this setting, so, it is useless at the moment. 

Here's an MSFT forum post with confirmation from other users: https://docs.microsoft.com/en-us/answers/questions/288741/is-this-a-bug-with-intune-configuration-profiles-a.html?sort=votes

-----
Interactive logon: Machine inactivity limit.

Windows notices inactivity of a logon session, and if the amount of inactive time exceeds the inactivity limit, then the screen saver will run, locking the session.

Default: not enforced.

Value type is integer. Supported operations are Add, Get, Replace, and Delete.

GP Info:

GP Friendly name: Interactive logon: Machine inactivity limit
GP path: Windows Settings/Security Settings/Local Policies/Security Options
Valid values: From 0 to 599940, where the value is the amount of inactivity time (in seconds) after which the session will be locked. If it is set to zero (0), the setting is disabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 773b74b2-7dc2-d0e5-1e3b-bd6445bceda4
* Version Independent ID: 34b55057-9078-6bd0-a9ac-2f6403b84be7
* Content: [Policy CSP - LocalPoliciesSecurityOptions - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-LocalPoliciesSecurityOptions?WT.mc_id=Portal-fx#localpoliciessecurityoptions-interactivelogon-machineinactivitylimit)
* Content Source: [windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @lXbalanque ,
yes, it was reported earlier, but it is product issue, not a documentation issue. I changed the document in https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9486, but the bug itself is still in place.
As a workaround, you can create a powershell script that changes the value of registry key **HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\InactivityTimeoutSecs** and distribute it using Intune.

thank you
