### ISSUE TITLE
Enable Data Sharing

### ISSUE THREAD

**Issue by jpoling1** [MicrosoftDocs/windows-itpro-docs#994]
The Upgrade Readiness deployment script page references a link to "Enable Data Sharing" that is supposed to be on this page.  It does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24771310-237e-adf7-be33-59355a87f243
* Version Independent ID: e2792588-8318-98a2-a5bd-ff5cbba75e0e
* Content: [Get started with Upgrade Readiness (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-get-started#enable-data-sharing)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-get-started.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by jaimeo** [comment]
Ah yes, I see. Thanks for that. Instead, that should be linking to "Enrolling Devices in Windows Analytics" (https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started). I'll fix.
