### ISSUE TITLE
Banging head on desk

### ISSUE THREAD

**Issue by indianfoodyummy** [MicrosoftDocs/windows-itpro-docs#9940]
It is somewhere between infuriating and just wildly disappointing that we could articulate the problem and yet not solve it.
In short: problem = "Human-readable Firewall rule name not present in 5152, 5156 and 5157 Windows event logs"
Implemented solution = "Human-readable Firewall rule name **still not present** in 5152, 5156 and 5157 Windows event logs"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313fceb3-ccf2-576d-e145-3354cf89c61f
* Version Independent ID: 9c626ecf-9360-8bf8-d3fb-ff5b85fbe394
* Content: [Filter origin audit log improvements - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/filter-origin-documentation)
* Content Source: [windows/security/threat-protection/windows-firewall/filter-origin-documentation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/filter-origin-documentation.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Benny-54
* Microsoft Alias: **v-bshilpa**

**Comment by MaratMussabekov** [comment]
Hello @indianfoodyummy ,
**Implemented solution = "Human-readable Firewall rule name still not present in 5152, 5156 and 5157 Windows event logs"** - "Filter Origin" field identifies the rule that blocked the connection, it doesn't contain the name, but contains GUID (which could be easily converted to DisplayName). Display names of objects are not usually used in event logs, since they could vary on different locales.
Thank you

**Comment by indianfoodyummy** [comment]
Understood, and thank you.

I will admit the new field is *less bad* to search for than the old field.  I did not say “Good”…just less bad.

Note that if you’re working in a large organization and data-mining across 10000’s or 100000’s of computers, merging the per-endpoint-specific guid to the rule name from logs is computationally inefficient for investigating individual hosts, bordering on impossible across all hosts/at scale.

I don’t find the display complexity argument very compelling.  Most of the fields in the log are explicitly UNICODE_STRING. Also, It’s easier to fix data-display problems than no-data problems.

Lastly, the key point is just that the situation is astoundingly illogical:

1.	Someone recognized a problem (rule name not in log, people complaining about it for 20 years).
2.	Someone thought “Let’s fix that!” By the way, Someone did a Great Job up to here
3.	Someone then makes a change, but literally does not fix the recognized problem?!

 

This situation is so absurd, it makes me literally wonder if the change was introduced intentionally to aggravate people requesting rule names in log events? 

 

However, as I said above, the new change makes log mining suck a lot less than it used to (merging 10’s of RTID’s instead of 10000’s of RTID’s per 515x Events), so I do appreciate the change. But obviously, I still think it was 100% the wrong change to make, and the original issue is still untouched in my mind.

 

Best regards,

-NICK
