### ISSUE TITLE
Update screenshot

### ISSUE THREAD

**Issue by Beschorr** [MicrosoftDocs/windows-itpro-docs#9943]
Hi team - the screenshot of the toast in this topic (
![image](https://user-images.githubusercontent.com/43045782/132575342-b0182156-36a2-4d4d-bba2-aa6c39182370.png)
)

Is out-of-date. There are some further changes planned for that toast, so we might want to plan to update it once Nickel ships.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e09345e7-0b81-b2f5-410f-54a855adc39d
* Version Independent ID: c57c1b34-3999-54db-bf17-830af9dcf6bb
* Content: [Customize Windows Security contact information - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-security-center/wdsc-customize-contact-information?source=docs)
* Content Source: [windows/security/threat-protection/windows-defender-security-center/wdsc-customize-contact-information.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-security-center/wdsc-customize-contact-information.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello, the screenshot was removed by https://github.com/MicrosoftDocs/windows-itpro-docs/commit/d164f0e48c961288671bf254d786b6cfb656f729#diff-77d7f11d2d99dad4ab9ed10595634f216e232417b4afa0f3f7405b361f72028a
**There are some further changes planned for that toast, so we might want to plan to update it once Nickel ships** - is it planned for 21H2 version?
Thank you
