### ISSUE TITLE
Google open source

### ISSUE THREAD

**Issue by asitm0207** [MicrosoftDocs/windows-itpro-docs#9945]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74dfa615-409b-54ec-f168-024a1b1d8df8
* Version Independent ID: 609c2afa-c2fa-296e-8ec0-619e98cd3a13
* Content: [Install and Configure VAMT (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/volume-activation/install-configure-vamt)
* Content Source: [windows/deployment/volume-activation/install-configure-vamt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/volume-activation/install-configure-vamt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@e0i , Close this issue #9945.
