### ISSUE TITLE
System Guard Secure Launch and SMM protection question

### ISSUE THREAD

**Issue by mikegan** [MicrosoftDocs/windows-itpro-docs#9948]
[Enter feedback here]
Hi all,
We are trying this feature on our system,but got fail.

For this feature - System Guard Secure Launch and SMM protection
Is it support Legacy boot mode bios? or it only support UEFI boot mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31d623d9-316c-0ef1-b6be-c3773d77ca21
* Version Independent ID: 83ddb59d-0cfc-34f2-e666-8927d86a04a7
* Content: [System Guard Secure Launch and SMM protection (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@mikegan < It supports only UEFI Mode,

**Comment by mikegan** [comment]
> @mikegan < It supports only UEFI Mode,

Thanks your information.
