### ISSUE TITLE
Issue with ongoing enforcement of policy (using Update function)

### ISSUE THREAD

**Issue by guitarfreak58** [MicrosoftDocs/windows-itpro-docs#9949]
I am currently testing a scenario where majority of systems are configured with the Restrict function of the LocalusersAndGroups CSP. Let's say a user requests administrative privileges as an exception - what I've configured in intune is to make an exclusion group to exclude this policy, and when the user's machine is moved into this group, they are also assigned an alternative version of this CSP that uses the Update function instead. This version of the policy only contains one group from the Restricted version, as we still want to ensure the IT support group has admin rights on the machine for any troubleshooting. I am also assigning a script to this exclusion group that promotes the user to an administrator.

What I've noticed is the when the policy switches, the previous list of admins remains, which is fine. The IT support group is listed in both the old and new policy, so the transition itself works fine. However, once i am an admin, if I am mischievous and decide to go into Computer Management and manually remove any other groups from Administrators, I noticed that the policy does NOT reinforce adding the IT support group. Even if I sync the device multiple times, the one group does not get added back to administrators - the only way to force it back on is to re-edit the profile in Intune and save it.

Should this policy be regularly enforced like the older RestrictedGroups CSP? Or is it only a one-time apply? I certainly hope that the Restriction function is regularly enforced like the old CSP. I haven't tested this with Restrict but I'm thinking I should verify it now. Thank you for your help!

**Comment by denisebmsft** [comment]
Hello @guitarfreak58. Can you please tell us to which article(s) your feedback applies? This information will help us route the issue correctly.

**Comment by guitarfreak58** [comment]
https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localusersandgroups

I am just trying to verify whether the policy should constantly apply to the device, or if it is a 1-time update to systems, as this is not called out in the documentation and it appears to only be working once with the Update function. Thank you
