### ISSUE TITLE
Problems with upgrade check

### ISSUE THREAD

**Issue by twasserman** [MicrosoftDocs/windows-itpro-docs#9951]
I ran dxdiag on my Windows 10 laptop. It reported no problems and found WDDM 2.1 and DirectX, but that doesn't appear to be sufficient for a Win11 upgrade on the machine. (Everything else passed OK on WhyNotWin11 except that my CPU is 6th generation, not the current 11th.)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db554047-b9ca-f5c9-d79f-4a70686a66db
* Version Independent ID: e05bf4bc-ab29-9d32-bd53-5ca3e70aba1b
* Content: [Windows 11 requirements - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/windows-11-requirements)
* Content Source: [windows/whats-new/windows-11-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/windows-11-requirements.md)
* Product: **w11**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@twasserman . We cannot give comments on Microsoft windows OS policy, I am a normal user like you having a laptop with **intel i5 7thgen 7200U**, even though all requirements are met, but not in the windows 11 CPU list.
We can do something as of now, please write your concern as feedback in feedback hub.
