### ISSUE TITLE
Inconsistent Note and bullet on the plan page

### ISSUE THREAD

**Issue by lukepfaff** [MicrosoftDocs/windows-itpro-docs#9954]
On the Plan for Windows 11 page this note is included

 Note

If you use Windows Update for Business to manage feature update deployments today, you will need to leverage the Target Version policy rather than Feature Update deferrals to move from Windows 10 to Windows 11. Deferrals are great for quality updates or to move to newer version of the same product (from example, from Windows 10, version 20H2 to 21H1), but they cannot migrate a device between products (from Windows 10 to Windows 11).
Also, Windows 11 has a new End User License Agreement. If you are deploying with Windows Update for Business Target Version or with Windows Server Update Services, you are accepting this new End User License Agreement on behalf of the end-users within your organization.

But then on the Prepare page you have this bullet.  They seem to be in conflict with one another.  The first note seems to say you can't use Feature Update Policys to move to Windows 11 and you should use a Target Version Policy instead.  But then this next bullet is saying that Feature Update will work fine to go to Win 11.  Not sure which is right.

If you use Microsoft Intune and have a Microsoft 365 E3 license, you will be able to use feature update deployments to easily update devices from one release of Windows 10 to another, or to upgrade Windows 10 devices to Windows 11. You can also continue using the same update experience controls to manage Windows 10 and Windows 11.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89477b73-196f-567b-1b5f-37cafb4d004e
* Version Independent ID: e707dec5-83ae-9953-d6a5-bede20f19c77
* Content: [Plan for Windows 11 - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/windows-11-plan?source=docs)
* Content Source: [windows/whats-new/windows-11-plan.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/windows-11-plan.md)
* Product: **w11**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Feature update deployment in Intune is different than feature update deferrals.
https://docs.microsoft.com/en-us/mem/intune/protect/windows-10-feature-updates

I know the use of similar terminology here is confusing. I'll try to clarify the article.
