### ISSUE TITLE
Is it really MFA?

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/windows-itpro-docs#9965]
The documentation for PIN registration and recovery refers to multifactor authentication. This document [Windows Hello for Business Provisioning](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-provisioning) shows a connection to "Azure MFA". But what methods are allowed to be registered? Are they the methods configured in the old MFA Settings page in Azure AD? Or the methods enabled for SSPR? Or something else? We find that people can register a phone for text messages, even though this is not enabled as a valid method for MFA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9dae9da-eaf0-c209-7c65-be8d2c1ada12
* Version Independent ID: 28b6788d-7982-23c2-5f19-f80690ebc0ce
* Content: [Pin Reset - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by Air-Git** [comment]
So the question is: is it accurate to call it Azure MFA? Or does it really just mean a Microsoft PIN recovery registration service?

**Comment by MaratMussabekov** [comment]
Hello @Air-Git ,
**what methods are allowed to be registered? Are they the methods configured in the old MFA Settings page in Azure AD? Or the methods enabled for SSPR?** - methods set in your MFA provider
**is it accurate to call it Azure MFA?** - no, it is not. Third-party MFA providers could be used as well
**Or does it really just mean a Microsoft PIN recovery registration service?** - those are two different services. MFA provides authentication, Microsoft PIN reset service only allows to change PIN
Thank you
