### ISSUE TITLE
Wrong information about KDC Authentication OID

### ISSUE THREAD

**Issue by dokessle** [MicrosoftDocs/windows-itpro-docs#9966]
The article says that "Inclusion of the KDC Authentication OID in domain controller certificate is not required for key trust authentication from Hybrid Azure AD joined devices." This is absolutely not true according to this article: https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-trust-prereqs#public-key-infrastructure.

Please remove or clarify this information. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800b8090-65a9-da9f-a930-1f80dc9f2c2d
* Version Independent ID: b4495b6a-4ca5-7aa1-7964-ef6e19275c4e
* Content: [Configure Hybrid Azure AD joined key trust Windows Hello for Business - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki#domain-controller-certificate-template)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by MaratMussabekov** [comment]
Hello @dokessle , both articles are correct.
it says: "Inclusion of the KDC Authentication OID in domain controller certificate is not required for key trust authentication from **Hybrid Azure AD joined devices.** The OID is required for enabling authentication with Windows Hello for Business to on-premises resources by **Azure AD joined devices.**"
The article you provided is applicable for Hybrid Windows Hello for Business environments. Azure AD joined devices could be used in Hybrid Windows Hello for Business environments, therefore the requirements contain KDC Authentication.

To make long story short - if you only have hybrid azure ad joined devices - no need for KDC Authentication OID in certificate template. If you have azure ad joined ones - KDC Authentication OID need to be added.

Thank you
