### ISSUE TITLE
Cached group membership?

### ISSUE THREAD

**Issue by toxarisswe** [MicrosoftDocs/windows-itpro-docs#9967]
Hello.
I have setup a scenario where we assign a specific AAD Group as local administrator. If I then add a user to the AAD group the user will become local administrator as expected. But when I remove the user from the AAD group the user is still local administrator even after a reboot. Now a few days later when I verify the status again, then the user have lost its local administrator privileges. Is there any cache containing the users membership, and if so is there any way to trigger a refresh of that cache? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b0c55a7-9aaa-d395-409e-59c2595c8e9e
* Version Independent ID: cf8e5a71-a8fc-1d43-6eed-03d3f2490693
* Content: [Policy CSP - LocalUsersAndGroups - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localusersandgroups)
* Content Source: [windows/client-management/mdm/policy-csp-localusersandgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-localusersandgroups.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Hello,

You may direct your question to the [Microsoft Community](https://answers.microsoft.com/en-us). It is a new platform where users can collaborate with each other on product questions like this.

The issues section of this public repository is for tracking problems with the information in the documentation.

Thanks.
