### ISSUE TITLE
Missing Event ID 3091

### ISSUE THREAD

**Issue by miketheitguy** [MicrosoftDocs/windows-itpro-docs#9977]
The page here appears to be missing Event ID 3091. Not sure if that's new to Server 2022 or not :)

Example of what I'm seeing.

The description for Event ID 3091 from source Microsoft-Windows-CodeIntegrity cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

148
\Windows\assembly\NativeImages_v4.0.30319_64\System.Dire573b08f5#\a6f90e82e7d018da76da10212cd4f49f\System.DirectoryServices.AccountManagement.ni.dll
3236495362
True
False
False
False
-1
True
10
Base_Audit
6
031017

The handle is invalid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5da550e8-6065-7666-46b1-7bfb84ad775e
* Version Independent ID: ffbb3f81-73d3-c5e9-ca5a-abbb36320661
* Content: [Understanding Application Control event IDs (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/event-id-explanations)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/event-id-explanations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/event-id-explanations.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@miketheitguy I see the article contains details about Event ID 3091 now:

<html>
<body>
<div class="table-scroll-wrapper has-inner-focus" tabindex="0" role="group" aria-label="Horizontally scrollable data" style="box-sizing: inherit; outline-color: inherit; overflow: auto hidden; color: rgb(23, 23, 23); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Event ID | Explanation
-- | --
3090 | Allow executable/dll file
3091 | Audit executable/dll file
3092 | Block executable/dll file

</div><p style="box-sizing: inherit; margin: 1rem 0px 0px; padding: 0px; outline-color: inherit; overflow-wrap: break-word; color: rgb(23, 23, 23); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">3090, 3091, and 3092 events are generated based on the status code of whether a binary passed the policy, regardless of what reputation it was given or whether it was allowed by a designated MI. The SmartLocker template that appears in the event should indicate why the binary passed/failed. Only one event is generated per binary pass/fail. If both ISG and MI are disabled, 3090, 3091, and 3092 events will not be generated.</p>
</body>
</html>
