### ISSUE TITLE
audo

### ISSUE THREAD

**Issue by ALI0ne** [MicrosoftDocs/windows-itpro-docs#9991]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6cc248-f9e9-6fca-f2b0-46497ba91a4f
* Version Independent ID: 27815eeb-485e-11ec-c78f-d14893f36add
* Content: [Security auditing (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/security-auditing-overview)
* Content Source: [windows/security/threat-protection/auditing/security-auditing-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/security-auditing-overview.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@e0i . please close this issue #9991 immediately.
