### ISSUE TITLE
MS Product Updates

### ISSUE THREAD

**Issue by felizondojr** [MicrosoftDocs/windows-itpro-docs#9996]
Can we expand on the Microsoft product updates under the Types of updates managed by Windows Update for Business section? A lot of my customers want a definitive list of MS products supported in such scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2056993d-a700-fba6-8982-e645b182eeea
* Version Independent ID: fb38a86a-cdf6-6fc2-8eb6-fd54f1599f55
* Content: [Windows Update for Business (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-manage-updates-wufb?source=docs)
* Content Source: [windows/deployment/update/waas-manage-updates-wufb.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-manage-updates-wufb.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
The update types listed there aren't products, but at a higher level--the different KINDS of updates. And as far as I know, they only apply to Windows itself, not other products, which I believe are updated by Microsoft Update. But we could consider adding a separate list of _products_ that Windows Update for Business can handle, if it can handle products other than Windows per se.

@arcarley your thoughts?

**Comment by arcarley** [comment]
Agreed. The updates specified are all updates for Windows products, I do not think we need to specify such as it is in the Windows section - no?

**Comment by RAJU2529** [comment]
@jaimeo . I believe  earlier microsoft office  versions in msi format installed by the users or by admins,. So microsoft updates  office updates and windows too.

**Comment by arcarley** [comment]
Only if "Allow updates for other Microsoft Products" is selected. In that case it is also very few (ex. Office Click to Run updates come that way but no new office updates). Further, those updates follow all the rules of quality updates and cannot be separately managed with WUfB policies... Please leave the page as is for now.

**Comment by jaimeo** [comment]
Closing per PM recommendation.
