### ISSUE TITLE
文档排版异常

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/windows-itpro-docs#9997]
文档排版异常，请修复。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3fa733db-e564-bd3f-d41b-241b27b13b40
* Version Independent ID: ef647afb-e298-af7b-5523-2076d3f2c9c6
* Content: [为 Windows 11 做好准备 - What's new in Windows](https://docs.microsoft.com/zh-cn/windows/whats-new/windows-11-prepare)
* Content Source: [windows/whats-new/windows-11-prepare.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/windows-11-prepare.md)
* Product: **w11**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@goxia you can get help from answers microsoft community.

**Comment by goxia** [comment]
> @goxia you can get help from answers.microsoft.com

I mean there's a problem with some of the typography in this document.

**Comment by e0i** [comment]
@goxia Can you be more specific about the problem with the typography in this document? Are the characters displaying not correctly?
